### ISSUE TITLE
Industrial Squeezer - Massive Tick time with a full Tank and Items in the Inventory

### ISSUE THREAD

**Issue by mallrat208** [BluSunrize/ImmersiveEngineering#1]
Edit: This persists as of version 0.1.9, I've added more in the second comment.

Using version 0.1.6 whenever the squeezer has items and a full tank it causes some issues. I'm able to walk around but I can't interact with anything in terms of opening GUI's or even using NEI to spawn items.

I used WarmRoast to see what was going on and saw an absolutely massive tick time for blusunrize.immersiveengineering.common.blocks.metal.TileEntitySqueezer.updateEntity()

![WarmRoast Screencapture](http://puu.sh/hE0p9/de7ef486fb.png)

Unless I'm mistaken that should indicate it's around line 76 in TileEntititySqueezer.java where  you're going to get a call to DieselHandler.getPlantoilOutput()

```java
				if(tick>=80)
				{
					while(inputs>0)
						for(int i=0; i<9; i++)
						{
							ItemStack stack = this.getStackInSlot(i);
							if(stack!=null)
							{
								int f = DieselHandler.getPlantoilOutput(stack);
								if(f>0)
									if(tank.getFluidAmount()+f<=tank.getCapacity())
									{
										tank.fill(new FluidStack(IEContent.fluidPlantoil,f), true);
										this.decrStackSize(i, 1);
										inputs--;
										update = true;
									}
									else
										break;
							}
						}
					tick=0;
				}
```

So...  I preface this by saying I'm not fantastic with Java...

It seems to me that the break statement gets called if the internal tank can't hold the additional amount of Plant Oil squeezing the seeds would create. It however would break the For loop only. The While Loop will still evaluate true and immediately put you back into the For Loop starting a never ending cycle that results in the massive calls to the oreDictionary causing a bad day.

**Comment by mallrat208** [comment]
Alright, so the current version of IE (0.1.9) has had some stuff added  to the Fermenter and Industrial Squeezer that prevents allows the main while loop to be exited once the tank is full to capacity. 

```java
				if(tick>=80)
				{
					while(inputs>0 && tank.getFluidAmount()<tank.getCapacity())
						for(int i=0; i<9; i++)
							if(tank.getFluidAmount()<tank.getCapacity())
							{
								ItemStack stack = this.getStackInSlot(i);
								if(stack!=null)
								{
									int f = DieselHandler.getPlantoilOutput(stack);
									if(f>0)
										if(tank.getFluidAmount()+f<=tank.getCapacity())
										{
											tank.fill(new FluidStack(IEContent.fluidPlantoil,f), true);
											this.decrStackSize(i, 1);
											inputs--;
											update = true;
										}
										else
											break;
								}
							}
					tick=0;
				}
```

The additional bit added to the while loop that checks the current fluid level vs capacity doesn't seem to work well.

I think the problem stems from the fact that it is possible to have room in the tank but not enough to actually process all of the  seed inputs for oil, so you end up stuck in the same loop as last time. This is most noticeable when Squeezer is hooked up to another tank or pipe network of some sort where it's possible for an odd amount to have been transferred out.

After talking with Tahg a bit last night it looks like the easiest fix would actually be to just remove the While loop itself since you're already iterating through the squeezer's inventory in the for loop,

**Comment by BluSunrize** [comment]
Not quite since the while loop is designed to make it so 9 items are always processed even if all 9 are in the same slot. I need to find another way

**Comment by BluSunrize** [comment]
Fixed
