### ISSUE TITLE
[Suggestion] Config option for blast furnace

### ISSUE THREAD

**Issue by JAWSAWN** [BluSunrize/ImmersiveEngineering#100]
Simply add config option to change how many ticks it takes to make steel in the blast furnace.

**Comment by Ayrrow** [comment]
I'd prefer a higher tier furnace. 

But as it is currently, Steel production is too slow even with three or four furnaces.

**Comment by PawnedSauce** [comment]
As what @Ayrrow said, to add on, they can also add a system for machine upgrades along new tiers of machines

**Comment by JAWSAWN** [comment]
How would you upgrade a blast furnace honestly?

**Comment by Ayrrow** [comment]
@JAWSAWN make a new furnace block that makes steel very quickly using iron + charcoal + loads of power? Pretty sure I saw a render floating around the other day for a multiblock that looks just like that...

**Comment by theunkn0wn1** [comment]
IMHO,
An idea for an upgrade to the existing blast furnace can be as follows:
[1]An upgraded furnace should require a fair amount of steel to craft
[2]the upgraded furnace should require additional fuel per unit processed
[3][a]Machine should require additional external heating.
[3][b]Additional external heaters/increased energy input should decrease time per unit.

**Comment by JAWSAWN** [comment]
It's a realism mod anyways...
Attaching bellows will increase the steel production speed. And maybe mechanical bellows that run off energy?

**Comment by theunkn0wn1** [comment]
Given it is a realism mod...
Perhaps beyond just mechanical bellows one could perhaps setup an oxygen refinement system for direct injection into the upgraded blast furnace?
By the electrolysis of water into Oxygen and Hydrogen and pumping (via the bellows) the oxygen into the furnace one would increase the throughput of the furnace, as pure oxygen is a required part of producing steel IRL. (Based on BOF methods)...

**Comment by BluSunrize** [comment]
The blast furnace will not get that config option. A different way of steel production is planned.
