### ISSUE TITLE
Crash on server start - Still got a ConcurrentHashMap in WorldTick

### ISSUE THREAD

**Issue by CanisArtorus** [BluSunrize/ImmersiveEngineering#1000]
As seen in our crashed attempt to start up a server:

http://pastebin.com/kpBJpGmf

The ConcurrentHashMap.KeySet() thing (issue #983) is happening somewhere else.

What surprises me greatly is that my personal client system for composing the modpack has no such error nor issue running java v 8u60.  It only occurs when trying to start our dedicated server machine.

**Comment by mindforger** [comment]
yeah that was a compile derp, just update :)

**Comment by BluSunrize** [comment]
Is your server on J8? And what version of IE are you on?

**Comment by mindforger** [comment]
yeah i removed my comment too ... it's a compiled java .. i presume it's based in the same basic source as this strange commercial "Xnig" version (+ it's extensions) and he compiled it on arch linux

**Comment by BluSunrize** [comment]
Yeah but with IE 0.7.3 Java version shouldn't make a difference. I make the cast to Map, which should disregard that keyset bogus.

**Comment by malte0811** [comment]
Um, this is probably my fault... I just checked the line the crash happens on and it is from my new drill animation code. I call `keySet` in there without casting to Map first since that usually isn't necessary.
@mindforger, I am very confused about which java version they used, bevause in the line after the one you quoted it says something about OpenJDK, which isn't by Oracle AFAIK.

**Comment by BluSunrize** [comment]
WELP.
At least it means that my fix still works until proven wrong. >_>

Also, this is issues #1000, so be proud of yourselves people, you break this mod waaaay too much.

**Comment by malte0811** [comment]
IE seems to be getting all the powers of 10 this week... My last PR contained 2 commits, one of them was the 1000th commit on master, the other one was my 100th commit to IE, and now we got issue/PR 1000 as well!

**Comment by BluSunrize** [comment]
And you are also to blame for the 1000th issue xD
All the big numbers belong to you malte =P

**Comment by CanisArtorus** [comment]
Thanks guys, That's basically what I thought would be happening.
I'll keep the populous in line while we wait for a fair update cycle.

Time for a bottle of apple juice (fermented or otherwise) it is then.
