### ISSUE TITLE
Crash when opening world with cart livery mod

### ISSUE THREAD

**Issue by InuYasha86000** [BluSunrize/ImmersiveEngineering#1001]
I tried to test out your mod with my modpack as it seems like a really cool power mod, however, from the error in the log, it shows something happens between immersive engineering and another mod: Cart Livery: http://pastebin.com/ctQqXWhZ this is when I go to open a world, it boots up minecraft perfectly but crashes after trying to load a world. here's a link to my modpack for testing if need be: http://www.technicpack.net/modpack/the-valley-testing-phase.797682

**Comment by InuYasha86000** [comment]
I know this issue is closed but I wanted to say thank you for the quick fix and prompt update. I know everyone appreciates the work you guys do.

**Comment by BluSunrize** [comment]
Thank you, much appreciated =)
