### ISSUE TITLE
All customNPCs from the customNPCs mod drop Epic Shader Grabbags with 100% chance

### ISSUE THREAD

**Issue by filloax** [BluSunrize/ImmersiveEngineering#1003]
It appears that mods' NPCs are considered bosses. TCon had this problem too with yellow hearts, could we maybe get a blacklist in the config for entities that can drop grabbags?

Edit: similar case with Tconstruct https://github.com/SlimeKnights/TinkersConstruct/issues/1073

**Comment by BluSunrize** [comment]
Something that isn't a boss shouldn't implement that interface. The developer is a dunce for doing so. >_>
I'll do a fix with the next version.

**Comment by filloax** [comment]
Probably be assumed npcs would only be used for bosses, dumb nonetheless
Il 09/Mar/2016 17:06, "BluSunrize" <notifications@github.com> ha scritto:

**Comment by BluSunrize** [comment]
Fixed with this:
https://github.com/BluSunrize/ImmersiveEngineering/commit/05b2cb3953e0061a33f016c3c2b7bedfb9c5b99f
