### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Evulperson** [BluSunrize/ImmersiveEngineering#1004]
Hey Guys, I love the idea of this mod.

I'm an experienced mod user, running 100+ mods on my Minecraft currently and I would absolutely love to add this into my pack, but I can't seem to get it to work. I've removed everything else during troubleshooting and still unable to get it to load.

Here is my error sheet
[http://pastebin.com/8xDg3rg1](http://pastebin.com/8xDg3rg1)

Looking forward to getting this running =]

**Comment by malte0811** [comment]
Update forge.

**Comment by Evulperson** [comment]
every time I update forge, it causes issues with other mods, but I'll give it a shot.

update: hahaha so much for experienced. it is always the most obvious thing isn't it. Thanks Malte0811
    I had to update... nothing. first time it didn't cause any issues. Thanks again bro.
