### ISSUE TITLE
Server Crashes with IE 0.6 and up

### ISSUE THREAD

**Issue by Leyoki** [BluSunrize/ImmersiveEngineering#1006]
Hi and first of all, thanks for the attention.
My case: I play on an own hosted 1.7.10 server with mods and plugins and was using IE 0.5.4 totally fine with other mods.

The thing is I wanted to update to the lastest version (being now the 0.7.3, but I still tried from 0.6 and up) and resulted in a crash.
I documented myself about cauldron and how it's outdated so I updated forge (last recommended version 1558) and get rid of the plugins for IE sake, but I still crashed... only on server and after disabling the arc furnace recycling since I searched on this issues forum, before disabling was stuck on loading.

I don't know what I'm doing wrong, or if there's any colission with another mod or what, so I came here as a last resource. With all other mods it starts just fine with client Minecraft.

Here's the crash Report: https://gist.github.com/Leyoki/23d1beef75826b7183ee

PD: Sorry if my English isn't perfect, not my native language.

**Comment by BluSunrize** [comment]
And there is no crashreport there, so I can't help you.
Use pastebin or a similar site to provide it, please?

**Comment by Leyoki** [comment]
Sorry, I tried to use the "Embed" format... still new to this site.
Now crash report is provided.

**Comment by malte0811** [comment]
That is the same crash as #1000. A release with a fix will probably be published during the next few days.

**Comment by Leyoki** [comment]
@malte0811 Oh, I see. I checked that post before but I didn't figure out if there was a solution (nor seing the crash report if it was the same).
My apologies if I asked for something stupid then. Glad to see there's a solution on the way if what you say is correct.

**Comment by BluSunrize** [comment]
Should be fixed now.
