### ISSUE TITLE
Some ideas for this mod. 

### ISSUE THREAD

**Issue by iceman11a** [BluSunrize/ImmersiveEngineering#1008]
I have some ideas. and I think you mite like them

1) Street Lights. (You have poles for power. Why not add street lights. Run Low or Medium voltage lines on each pole that has a street light to light that light. Only pole with a medium or low voltage wire will work. 

2) Working traffic lights. On poles. Run a Low or Medium Voltage wire to each traffic light. Use a block to control light operations. Controller all so needs power.

3) Electric Signs. Power by the wire. where we can make them as small as a block or put them together to make larger signs. Right clicking on sign you can add text to it. The sign lights up when given power. Place on blocks or any thing else. 

4) Redstone Wire. An option to send a redstone signal over a wire. Option of 16 colors like the bundled cable.  Will need a control block for this. 

Thanks for reading this post on my ideas. Have a nice day.

**Comment by laz2727** [comment]
Last one exists in Immersive Integration.


2016-03-11 20:44 GMT+05:00 iceman11a <notifications@github.com>:

**Comment by BluSunrize** [comment]
1) Already implemented, maybe actually check the mod first =P
2) Doesn't feel very retrofuturistic, nor is it very useful since Minecraft doesn't really have traffic ^^
3) Hrrm. Maybe. neon signs are a bit early for IE's time period as well, but unpowered caution signs (that work like paintings) are actually on the ToDo.
4) Just as @laz2727 said, check Immersive Integration.

**Comment by iceman11a** [comment]
1) Sorry I can't find any thing like this in the mod. can you give me a name for this. and how it's attached to the pole.

2) The idea behind this is just looks. Some thing that makes it look like a street. In my world I do have streets and roads. I even have a gas station. 

3) Sorry, I'm not talking about  neon signs. I mean just plan signs that light up. That's it. 
4) Sorry I never saw any videos on this.So can you give me some idea on what to look for. I didn't see any thing related to redstone wire. Or a way to string on the poles.

**Comment by XFactHD** [comment]
1) the powered lantern, if that doesn't exist for you, you are using a really freakin' old version of IE

**Comment by PrincessRTFM** [comment]
Maybe make the caution signs light up (either just a texture thing or actually emit a little bit of light) when powered? Could be a cool feature, switch them on with a breaker switch when the area's unsafe, like for mining, then turn them off when you "lock" the doors or something...

**Comment by iceman11a** [comment]
1) The power lantern is not a street light. I fount that I and I haven't figure out how it works yet, There's all so a flood light and I have no idea how this works all so. 

Does any one have an updated video showing me how all this crap works and the new stuff all so. I just can't keep up with this stuff. I all so fount info about some kind of fluid tank. So IE has some kind of tank that we can use and I don't see that all so. 

PrincessRTFM, That mite be an idea all so. The idea I had was for building that we build we could put lighted signs next to the doors or a bigger lighted sign in the front yard or somethings. 

I need some thing that can update me on this and show me how to do this things I can't figure out how to get them to work.

**Comment by BluSunrize** [comment]
There is a friggin /book/ on IE.
It's called the Engineer's Manual. it describes every single damn feature the mod has to offer, including the powered lanterns and floodlights. It even has a search function.
Also there is this wonderful thing called google in which you just have to enter "Immersive Integration" to find the exact mod that adds redstone wires.
It's not that difficult and it's not my job as a dev to forcefeed this to you.
