### ISSUE TITLE
Player Data Not being saved/being deleted

### ISSUE THREAD

**Issue by Solace7** [BluSunrize/ImmersiveEngineering#1010]
Upon updating IE to 0.7.3 I started getting this bug where certain items in my inventory or backpack would disappear, or duplicate. Morphs from the morph mod that I had are gone, and my Chromaticraft progression data is being reset as well.
When I downgrade to 0.7.2 the issue is no longer there, which leads me to believe its IE related.

**Comment by malte0811** [comment]
Could you please upload a server log (if this is a dedicated server, client log otherwise) of
1. a session before data went missing (the session when the data was meant to be saved) and
2. a session where you noticed data went missing
to gist.github.com (doesn't complain about large files like pastebin does)?

**Comment by Solace7** [comment]
Before Missing Data
https://gist.github.com/Solace7/e98c8f9ae38e18321f8d
Missing Data[bye bye exchanger]
https://gist.github.com/Solace7/9190774ea2182adf55fc

**Comment by malte0811** [comment]
Ok, those logs didn't help at all, if items are vanishing, they are doing so without throwing an exception that has its stacktrace printed to the log. Besides, the changes from 0.7.2 to 0.7.3 were quite small and shouldn't affect anything like player data. No items were added between these versions, so the version change shouldn't cause the id map to overflow or anything like that. The only new things were 2 new shaders, but those aren't different from the other shaders in any way that I am aware of.
Just to avoid misunderstandings: Changing the IE version from 0.7.2 to 0.7.3 without changing anything else results in item loss? And reverting back to 0.7.2 (again, without any other changes) fixes it?

**Comment by Solace7** [comment]
That was the case, but now even with 0.7.2 my items are missing/duplicating, though it only seems to be in the backpack which leads me to believe its Iron Backpacks problem.
[https://github.com/gr8pefish/IronBackpacks/issues/62](url)
