### ISSUE TITLE
Idea for mod

### ISSUE THREAD

**Issue by Gray5** [BluSunrize/ImmersiveEngineering#1011]
How about multiblock capacitors? Like ender io, but shaped and fancy?

**Comment by BluSunrize** [comment]
Nah. Boring and hard to code. Dynamic multiblocks with syncing tiles aren't very fun. Also, no point either since just putting multiple capacitors acomplishes the same thing.

**Comment by Gray5** [comment]
Not dynamic, multiblock like a sheetmetal tank to store a great amout rf.

**Comment by BluSunrize** [comment]
point stands that multiple capacitors would accomplish the same thing. The multiblock wouldn't have more storage because of balance, so there is no point to use it over multiple capacitors.

**Comment by PrincessRTFM** [comment]
Also, wire-chaining capacitors looks kinda cool.
