### ISSUE TITLE
EU to RF conversion

### ISSUE THREAD

**Issue by Lanrik** [BluSunrize/ImmersiveEngineering#1012]
If in eu network has a multiple packets, then wire connector dont transfer any energy, but request some.

**Comment by PrincessRTFM** [comment]
Could you clarify this? I don't really understand what you're saying here.

**Comment by mindforger** [comment]
reduce "loss" for your cables in IE config to 0 and see if it persists!

**Comment by Lanrik** [comment]
Ok, i think i find a problem. Sum of all energy packets exceeded wire transfer rate. Sorry.

**Comment by mindforger** [comment]
@Lanrik you can close this issues if it is solved :)
