### ISSUE TITLE
MineTweaker and IE unable to create new world

### ISSUE THREAD

**Issue by Joshwoo69** [BluSunrize/ImmersiveEngineering#1013]
http://pastebin.com/MR153kXM

**Comment by malte0811** [comment]
And that's why duplicate code is bad: I fixed this crash for pages with one crafting recipe, I didn't know that the same code was there a few hundred lines further in the same file for pages with multiple recipes.

**Comment by Joshwoo69** [comment]
Eurgh... possible to fix? Migjt wanna poke at blu too...

**Comment by malte0811** [comment]
No need to poke him, I know how to fix this, I was just saying that I fixed this bug before, but for pages with only one recipe. this time it is happening for pages with more than one recipe.

**Comment by Joshwoo69** [comment]
Ah great.. so when? Soon I guess...

**Comment by BluSunrize** [comment]
damnit malte xD

Also, I don't need poking, I get emails for every message posted on thsi issue tracker.

**Comment by MokahTGS** [comment]
I'm getting a crash with IE and Minetweaker:

http://pastebin.com/1qaK115U

Is this the same issue or something else?

**Comment by Joshwoo69** [comment]
@mokahTGS  sorry this is not the same issue. Please go and make a new one.

**Comment by MokahTGS** [comment]
OK, thanks!

**Comment by Joshwoo69** [comment]
Blu: quick question will you ush this ypdate soon? I would want tp have it but I cannot compile :(

**Comment by BluSunrize** [comment]
@malte0811 still has somethign he wants to PR afaik. I'll wait for his go ahead
