### ISSUE TITLE
[BUG] Immersive Engineering MV and HV capacitor is not queryable by OC

### ISSUE THREAD

**Issue by hron84** [BluSunrize/ImmersiveEngineering#1014]
**Note:** this is a cross-mod bug report, linking to MightyPirates/OpenComputers#1688 Please read the conversation there.

I'm trying to make a universal energy storage reader API, but ImmersiveEngineering's capacitors behaves weird.
LV capacitor can be read without any issue, but MV or HV capacitors returns with nil and "unknown error" when I try to use object.getEnergyStored() or object.getMaxEnergyStored() calls.

ImmersiveEngineering 0.7.3
OpenComputers 1.5.22.46

**Comment by BluSunrize** [comment]
cc @malte0811, this is your area of expertise, since I don't know anything about the computer mods .~.

**Comment by malte0811** [comment]
Ok, I know what is causing this, I am comparing to classes with == instead of `isAssignableFrom` or whatever that method is called. So it is a very simple fix, I will fix it this afternoon.
