### ISSUE TITLE
Multiblock Lighting Issues

### ISSUE THREAD

**Issue by MrKiel** [BluSunrize/ImmersiveEngineering#1017]
0.7.4: 

I'm having some issues with lighting on the multiblocks. 

In many cases, blocks directly adjacent to a multiblock (coke oven, squeezer, fermenter etc) will show a light level of 9+ in Waila, but the multiblock shows a light level of 0 (zero) all over. 

Anything I can do to correct this?

EDIT: Restarting the game seems to fix it, perhaps this is a bug with only freshly made multiblocks?
Update: It seems this bug appears when first placing multiblocks or adjusting the immediate area around them. Relogging / Restarting does seem to fix it. 

![2016-03-14_03 43 41](https://cloud.githubusercontent.com/assets/10761194/13763435/1f6adb44-ea3e-11e5-8cf7-cb5f8651124a.png)
![2016-03-14_23 38 28](https://cloud.githubusercontent.com/assets/10761194/13763442/2adc1a74-ea3e-11e5-978d-cf0de88489f4.png)
![2016-03-14_23 38 39](https://cloud.githubusercontent.com/assets/10761194/13763444/32ba5850-ea3e-11e5-9220-e261c139ef6a.png)
![2016-03-14_23 38 50](https://cloud.githubusercontent.com/assets/10761194/13763445/32d7093c-ea3e-11e5-996d-102c1df66431.png)
![2016-03-14_23 38 34](https://cloud.githubusercontent.com/assets/10761194/13763446/32e4b708-ea3e-11e5-8a2e-93333a8f845b.png)

**Comment by XFactHD** [comment]
Are you using Optifine?

**Comment by malte0811** [comment]
Are you using OptiFine? I have never seen this bug...

**Comment by MrKiel** [comment]
Not Optifine but fastcraft is installed. Strangely enough it only seems to affect indoor multiblocks - those built outdoors are fine!

I'll try without fastcraft and post results shortly.

**Comment by MrKiel** [comment]
Must have been fastcraft as removing that has resolved it. 

Thanks!
