### ISSUE TITLE
[BUG] Computercraft support

### ISSUE THREAD

**Issue by Skyrich** [BluSunrize/ImmersiveEngineering#1018]
-On the Fermenter and the Industrial Squeezer the getInputStack functions didn't work. CC says i attempt to call nil. 
-On the Fermenter whenever i tried something with Slot 1 it says its not a Slotnumber between 1 and 9

**Comment by malte0811** [comment]
Both are typos I made, the getInputStack method is missing the t in input, so it is called getInpuStack, but it should work. The second bug should only affect getRecipe for the first slot, I am throwing an exception if the slot is less than 2 instead of less than one.
