### ISSUE TITLE
Bottling machine leaking

### ISSUE THREAD

**Issue by Storm-Engineer** [BluSunrize/ImmersiveEngineering#1019]
I just noticed on the private server I play on, that the Bottling machine keeps slowly taking fluid apparently forever at a rate of roughly 30 mb per second, even if it doesn't get fluid containers to fill so its internal buffer should get filled up.

I left the machine connected to two almost full tanks of Creosote oil, using IE's own pipes, and next time I checked my tanks were almost empty! I can see the mb's ticking down slowly as long as both:
- tanks get redstone signal to output
- pipes are connected to Bottling machine

I could not find any info anywhere in the size of its buffer, or any mention of similar issue.

Infinity Evolved modpack 2.3.5 (IE 0.6.5.1)

**Comment by PrincessRTFM** [comment]
`IE 0.6.5.1`

Pretty sure blu's going to tell you to test again on the latest release.

**Comment by mindforger** [comment]
yeah you should test it with the latest release first :D fixes an aweful lot of stuff :)

**Comment by AHrubik** [comment]
I suspect this is tied to my issue.

https://github.com/BluSunrize/ImmersiveEngineering/issues/1032
