### ISSUE TITLE
I don't know bug or not

### ISSUE THREAD

**Issue by Udosa** [BluSunrize/ImmersiveEngineering#102]
when i look Crusher recipes on NEI
http://prntscr.com/7lgujs
How i can get fire ?)

**Comment by AEnterprise** [comment]
if nei displays fire it means that it's trying to display "null" so that recipe has an invalid input

**Comment by BluSunrize** [comment]
Interesting. No idea how that happened. Will look into it.

**Comment by BluSunrize** [comment]
Fixed!
