### ISSUE TITLE
Crash between Minetweaker and IE

### ISSUE THREAD

**Issue by MokahTGS** [BluSunrize/ImmersiveEngineering#1020]
I'm getting this crash on load:

http://pastebin.com/1qaK115U

**Comment by malte0811** [comment]
Update MineTweaker.

**Comment by MrBloodowrth** [comment]
ImmersiveEngineering-0.7.4.jar

MineTweaker3-1.7.10-3.0.10.jar

http://pastebin.com/8jnz0nAj

**Comment by XFactHD** [comment]
Update MineTweaker.

**Comment by mindforger** [comment]
'Update MineTweaker.'
to 3.0.10**B**

to be more specific
