### ISSUE TITLE
Idea and request

### ISSUE THREAD

**Issue by RyuuCZ** [BluSunrize/ImmersiveEngineering#1022]
I have small idea to make this mod better and some realistic
1st ... the MV and HV kabel is taking small DMG if in 100RF/t (0,5HP per 0,5s) ... larger FR/t= more DMG
http://i.imgur.com/3Q1jlnr.png

2nd when wires are crossed ... and in if in difference RF/t ... it will burn (short-circuit) ... in <250RF/t
http://i.imgur.com/Ev881VU.png
and it is not transfer power from "A" wire to "B" wire

if you can make 1st its will best ... 2nd is small idea from real life

PS ... make a other wire relay for pulling cable on top side of wooden post or on the wall (similarly the wire connector)
Minecraft verzion used: 1.7.10

**Comment by BluSunrize** [comment]
For one: Try it with please.
Secondly: No.Both suggestions have been made before and they cannot be fulfilled. It's impossible to do those collision calculations without killing the server.
