### ISSUE TITLE
ImmersiveEngineering Incompatible with MT3 unless intergration is turned off

### ISSUE THREAD

**Issue by Winseven4lyf** [BluSunrize/ImmersiveEngineering#1025]
ImmersiveEngineering 0.7.4 is not working with Minetweaker3 3.0.10, unless I turn built-in intergration off. [http://pastebin.com/M67Ecvan](url)

**Comment by mallrat208** [comment]
You may want to update to Minetweaker 3.0.10B, it had a few fixes including
``
Fixed recipes not reloading on servers, sometimes (thanks to mrammy)
``

**Comment by BluSunrize** [comment]
Yeah, exactly that. IE needs 3.0.10B. It was in the changelog, just noone ever reads those, eh?

**Comment by AEnterprise** [comment]
@BluSunrize can't you put that in the @Mod annotation so forge displays a nice screen stating you need atleast that version instead of crashing? might save the players that don't bother with changelogs (and yourself) alot of trouble

**Comment by BluSunrize** [comment]
No I can't because minetweaker didn't change it's internal version number between those two. Otherwise I would have.

**Comment by AEnterprise** [comment]
alright didn't know that, thanks

**Comment by Winseven4lyf** [comment]
Getting the 3.0.10B dev full version just crashed it sooner than before :|

**Comment by Winseven4lyf** [comment]
The dev core version didn't help either

**Comment by mindforger** [comment]
"dev" means unobfuscated code get the version without "dev" in it's name

**Comment by BluSunrize** [comment]
Don't use dev versions. They're nto for you, they're for devs. Hence the name.
And if you say "it crashes sooner", at least provide a log.

**Comment by Winseven4lyf** [comment]
There also wasn't a 3.0.10B non dev version, also i will get the log

**Comment by Winseven4lyf** [comment]
Wait? now minetweaker is the problem :| http://pastebin.com/zNgX1yHA

**Comment by BluSunrize** [comment]
Yes. There absolutely is a non dev version. Took me 30 seconds of google.
http://minecraft.curseforge.com/projects/minetweaker3/files/2259434

**Comment by Winseven4lyf** [comment]
THANX BLU :grin:

**Comment by Winseven4lyf** [comment]
And now im getting a 503 error... :imp:

**Comment by Winseven4lyf** [comment]
Well then I used google and then turns out MT3 3.0.10B was on the TITLE PAGE, not the DOWNLOADS :expressionless:

**Comment by Winseven4lyf** [comment]
Well thx for the help :blue_heart:
