### ISSUE TITLE
Power stops transferring after server restart

### ISSUE THREAD

**Issue by ShaneCourtrille** [BluSunrize/ImmersiveEngineering#1026]
Ender IO Capacitor Bank (source) <-> MV connecter <-> HV Transformer <-> HV Relay <-> HV Relay <-> HV Transformer <-> MV Connector <-> MV Capacitor (destination)

Power stops pulling each time the server restarts.  The MV connector which is connected to the Ender IO Capacitor Bank shows it has power stored and ready to transfer but the MV Connector connected to the MV Transformer at the end shows 0 power stored.  If I break an HV transformer on either end and reconnect things then power starts to flow again.  

Thoughts?  I'm thinking I'll put an MV Capacitor between the Ender IO and the HV Transformer to see if that resolves it.

**Comment by BluSunrize** [comment]
replicate it without EnderIO and it's an IE issue =P

**Comment by mindforger** [comment]
@ShaneCourtrille advice for mod compatibility 
ALWAYS define the flow direction of the conduits(or capacitors face) when connecting to and IE connector! Ender IO has a funny behaviour when using IE wires or other mod cables between two endergy storages!
so ALWAYS define energy flow directions when switching between EIO stuff and other mods

**Comment by ShaneCourtrille** [comment]
@mindforger I had already thought of that and did so.  

The thing that makes it an IE issue to me is the fact the MV connector off the Ender IO capacitor has a charge to it so at the very least IE should be pulling that.  Also breaking the chain and reconnecting seems to indicate an issue with IE pulling power after a server restart.  Reconnecting the chain triggers the proper code that starts the pull logic up.  I'll get an HV capacitor in the there and see what happens.

**Comment by BluSunrize** [comment]
IE can't output if EIO refuses to accept the power ^^

**Comment by ShaneCourtrille** [comment]
EIO was the source.  The destination is pure IE (Arc Furnace after the MV Capacitor).  I removed EIO as the source and have a fully charged HV Capacitor now.

HV Capacitor (source - fully charged) <-> MV connecter (*) <-> HV Transformer <-> HV Relay <-> HV Relay <-> HV Transformer <-> MV Connector <-> MV Capacitor (destination - 0 RF)

Still has the same problem and the MV Connector (*) still shows 1024/1024 RF in Waila.  The transformer is just not pulling it.  Confirmed by the MV Capcitor (destination) being completely empty.  Trying to verify if removing/re-adding the MV connector is enough to restart the power moving or if I have to do it to the HV Transformer instead..

**Comment by mindforger** [comment]
@ShaneCourtrille you are underestimating the logic behind EIO's capacitors, (AFAIK and recognized by behaviour, no idea about the code) as long as a "target" has the capability of holding, keeping AND sharing/sending charge, they tend to equalize the charge among the "batterys"

which means either IE/BluSunrize may have to check if it's connectors are returning the proper "can send power" info when connected to a "battery type" component (i have the fuck no idea when this is checked on EIO side) 

or you have to carefully define the flow direction on the conuits and EIO capacitory
which tends for me to be a better solution, as mods are designed to bring a little bit of challenge and a minimum of brainpower to make good working designs ... well at least in my opinion :P

it is working as it is, you have just to be a bit more carefull ... by the way this issue also shows when using flux ducts from TE ... not the goldish versions with internal storage, they work just beautiful but cause quiet a bit ticklag

**Comment by ShaneCourtrille** [comment]
@mindforger: I have removed EIO from the scenario.  Now it's pure IE as shown in my last post.  Still need to verify if it requires a transformer reset to get things going or not..

**Comment by MatthiasMann** [comment]
@mindforger the EIO capacitors do not have any special intelligence - the balancing of power is in the conduits. If a capacitor side is configured to either input only or output only mode then they behave as any other pure unidirectional RF block on that side (output will push energy if the neighbor tile accepts it, input will allow the neighbor tile to push energy into the cap bank as long as it has space).

**Comment by malte0811** [comment]
I have fixed this, but I don't know when I will push the commit since I am in Austria right now and WiFi is a bit complicated. It is an issue with chunkloading and the energy net, so not related to EnderIO in any way.

**Comment by ShaneCourtrille** [comment]
@malte0811 Good news.. thanks.  Do you have a recommended work around? Don't chunk load anything in IE or are there specific things not to chunk load for now?

**Comment by malte0811** [comment]
As a workaround you can try placing a redstone breaker with a timer triggering every minute or so anywhere within loaded chunks. If I fixed the same bug you had, energy should be able to flow once the timer has triggered once.
I wasn't talking about chunkloading as in ChickenChunks or world anchors, I was talking about loaded chunks in general. If the chunks the power is going to are loaded later (can be something like 1 tick) than the chunk the power is coming from the cached connections are not reset, causing the energy source to ignore the new output.
