### ISSUE TITLE
Placing solid blocks anywhere above a multiblock causes it to render as very very dark.

### ISSUE THREAD

**Issue by Znailxxor** [BluSunrize/ImmersiveEngineering#1027]
As evidenced by this screenshot:
http://i.imgur.com/3c9ZFF7.png

Tested with all levels of smooth lighting, doesn't make a difference.
Having Optifine installed or not does not appear to matter.

**Comment by BluSunrize** [comment]
Are you using optifine?

**Comment by Barhandar** [comment]
#1017 sounds similar.

**Comment by Znailxxor** [comment]
> Are you using optifine?

I was, but testing it again with Optifine disabled made no difference.

**Comment by Znailxxor** [comment]
It could be Fastcraft, will remove that and see if the issue persists.

**Comment by BluSunrize** [comment]
Mkay, try without fastcraft. Might be that then. If it is: Sorry. But I can't do anything against those optimizing mods. They'll do anythign to squeeze out some extra FPS and I can't really prevent taht.

**Comment by Znailxxor** [comment]
Yup, it's Fastcraft.

**Comment by Barhandar** [comment]
>But I can't do anything against those optimizing mods. They'll do anythign to squeeze out some extra FPS and I can't really prevent taht.

I've never seen this issue with Thaumcraft and Magneticraft despite their fancy rendering and using Fastcraft always. Your fancy rendering didn't have the issue before, too.

**Comment by BluSunrize** [comment]
My rendering is more efficient than Thaumcraft ;)
I render my multiblocks as ISRBH, which means they are brawn like normal blocks. Thaucmraft uses TESRs, TileEntitySpecialRenderers, which update on every rendertick.
My method is more efficient and nicer on clients, at the cost of being static.

None of this matters though, since in 1.8 it's all entirely different. Rendering for 1.7 won't be changed anymore.

**Comment by Barhandar** [comment]
>My rendering is more efficient than Thaumcraft ;)

Anyone's everything is more efficient than Thaumcraft's.  
>I render my multiblocks as ISRBH, which means they are brawn like normal blocks.

And their downside is that they're affected by light as well, even when they really should not be (like placing blocks next to lowest block of furnace preheater darkening entire side). Or funny effects if solid blocks are placed in front of improved blast furnace.

**Comment by BluSunrize** [comment]
Yeah, and I can't help that. Hence why this topic is closed.
