### ISSUE TITLE
Force-Enable Hammer Crushing = True Not working

### ISSUE THREAD

**Issue by fullphaser** [BluSunrize/ImmersiveEngineering#1028]
Not sure if this is one of those features or bugs, recently upgraded to 0.7.4 and noticed the hammer was not making grit. I assumed it was because it detected Rotarycraft and turned it off perhaps, but I tried to use the 

    B:"Force-Enable Hammer Crushing"=true

To no avail, any thoughts? 

This would be in the version 0.1.11 Tame the World Modpack for config / other mods if anyone is curious

**Comment by BluSunrize** [comment]
Are you trying to crush ores or ingots?

**Comment by fullphaser** [comment]
Trying to crush ores with the hammer, 

Ingots produce plates as expected.

**Comment by BluSunrize** [comment]
Oh right. That config is unused. Forgot about that.
Just make sure "Disable Hammer Crushing" is set to false.

**Comment by fullphaser** [comment]
Hm. 

It is as well, I'm trying to think of other tech mods in place, because I know you mentioned in the past if there's another mod that makes Dust IE will drop the Grit from hammer recipe. 

Just confused as it was working in 0.651 as far as I know and didn't see anything in the changelog for 0.7 that might have prompted it.

**Comment by BluSunrize** [comment]
Yeah because in 0.7 changed its concepts of crushing and with the introduction of plates, ingots couldn't get crushed anymore and stuff.

**Comment by fullphaser** [comment]
Ah So Hammer + Ore != Grit in 0.7? Sorry for my confusion, I just wanted to get it all cleared up, gotta shuffle some things around in HQM and all.

**Comment by mindforger** [comment]
well, just as an idea, make hammer recipes a mietweaker thing?

**Comment by BluSunrize** [comment]
Nono, Hammer + Ore Should still return 1 grit. Unless it's been disabled.

**Comment by fullphaser** [comment]
I know you've mentioned in the past that it gets disabled if another mod makes dust, how does it do that check? Is it just looking in the Ore Dictionary that grit is assigned to and seeing if anything else is in there?

**Comment by BluSunrize** [comment]
No. It should just go through the oredict and for ever ore that has a dust, it will add a crafting recipe with the hammer. But only when the config option to disable it is set to false.

**Comment by fullphaser** [comment]
Hmmm 

![2016-03-21_18 23 23](https://cloud.githubusercontent.com/assets/15974903/13936231/9fda5738-ef92-11e5-8aa8-ab493da11985.png)

![capture - copy](https://cloud.githubusercontent.com/assets/15974903/13936235/a695b2a2-ef92-11e5-98fc-9033c120ed19.PNG)

![capture2 - copy](https://cloud.githubusercontent.com/assets/15974903/13936236/a6960040-ef92-11e5-88e8-e706255f91cc.PNG)

Any thoughts?

**Comment by fullphaser** [comment]
Well Tiny Update, I ran it stand alone and I'm still getting the issue (no other mods installed) so Now I'm really confused. I tested versions 0.7 - 0.7.4 and it's persistent. I genuinely have no clue. Is there anything else in the config file that might halt things?

**Comment by MonaMoonlight** [comment]
I have been trying to get the hammer crushing to work, but even when the config option to disable it is set to false, it simply will not crush ores into grits/dusts.
Seeing as the config option for force-enable hammer crushing is unused, this is actually an issue of the hammer not working fully.

It does still work with ingots into plates, but if I want the grits/dusts to make electrum, for instance, I need to first gather enough material to make a crusher, alternatively use Thermal Expansion's Pulverizer, which is something I've been looking to move away from.
