### ISSUE TITLE
Crash when added Charcoal recipe in Coke Oven

### ISSUE THREAD

**Issue by Tsyklop** [BluSunrize/ImmersiveEngineering#1029]
I try added Charcoal recipe(I deleted an existing recipe.)

Minetweaker script: 

`
val oreWood = <ore:oreWood>;
var Charcoal = <minecraft:coal:1>;
CokeOven.removeRecipe(Charcoal);
CokeOven.addRecipe(Charcoal , 500, oreWood, 1800);
`

Crash - http://pastebin.com/Gj9qgGik

**Comment by Tsyklop** [comment]
ADD. If i try view recipe creosote bottle or cell etc... - crash, same error

**Comment by mallrat208** [comment]
What the heck is registered as oreWood

**Comment by Tsyklop** [comment]
@mallrat208 ohhhh..my god... yes... my bad. my bag.
I not notice it. Thanks.
