### ISSUE TITLE
Tanks leak fluid when outputting to the same piping. 

### ISSUE THREAD

**Issue by AHrubik** [BluSunrize/ImmersiveEngineering#1032]
Mod Version: ImmersiveEngineering-0.7.4

A single tank outputting to a pipe line seems to be able to feed and then hold its inventory when the destination is full. Multiple tanks (in this scenario 4+) outputting to pipes that eventually combine continue to output even when the destination is full resulting in voided fluids.

First detected in IM 0.7.1.2. Updating to 0.7.4 didn't fix the bug.

**Comment by BluSunrize** [comment]
What type of tank, what output, pictures of the setup?

**Comment by AHrubik** [comment]
Immersive Engineering multiblock tanks storing Buildcraft oil outputting through IE pipes to a BC Additions refinery which in turn outputs Hot Fuel Gas through IE pipes to a BC Additions cooling tower which in turn outputs BC fuel to IE tanks through IE pipes.

More testing last night showed that as long as only 1 tank in the setup is outputting oil into the system and there is only one destination tank for the BC fuel everything works as intended. Turning on a 2nd output tank or enabling a secondary output tanks cause liquids to void.

I'm at work now but I'll get you pictures and a video tonight of it.

**Comment by AHrubik** [comment]
Screenshots.
![2016-03-25_18 59 01](https://cloud.githubusercontent.com/assets/6053583/14056596/efd2baa6-f2bb-11e5-8599-d4ccd3027042.png)
![2016-03-25_18 59 12](https://cloud.githubusercontent.com/assets/6053583/14056599/fa195754-f2bb-11e5-9703-bb0ec39c3907.png)
![2016-03-25_18 59 30](https://cloud.githubusercontent.com/assets/6053583/14056600/fd574034-f2bb-11e5-935d-11eeffd69c6c.png)
