### ISSUE TITLE
[Suggestion] Add a config option to disable village house generation

### ISSUE THREAD

**Issue by filloax** [BluSunrize/ImmersiveEngineering#1034]
I mean the one where the engineer spawns.

**Comment by BluSunrize** [comment]
Has been requested multiple times. Guess it's not to bad of an idea.

@malte0811 you wanna chuck it into your PR or should I?

**Comment by malte0811** [comment]
I thought it was already in there? I'll check, if it isn't, I'll just include it.

**Comment by Joshwoo69** [comment]
@malte0811 checked it is in your PR

**Comment by BluSunrize** [comment]
My bad. Missed that. Closing this then.
