### ISSUE TITLE
Suggestion - Item Elevator/Dumb waiter

### ISSUE THREAD

**Issue by TheQuantumGeneral** [BluSunrize/ImmersiveEngineering#1035]
Basically, I have always felt conveyors to be the coolest way to move things, but their verticality or lack thereof has always irked me (even redstone can be vertical). I suggest an item elevator, making it look gear or hydraulic powered would also suit the theme of the mod (imo) quite well. 

Basically it accepts items, then moves them up or down to be retrieved by a conveyer comes back, upside to it is compactness, downside to it is it's slower than a conveyer ramp (only moving a stack at a time) 

Imagine this sort of shape, but obviously a better texture, more in line with your mod - https://camo.githubusercontent.com/4e7633f652713cf5fdc796c27ec550f2a58f336f/687474703a2f2f696d6775722e636f6d2f6c5944506b79352e706e67

also here is an example i mocked up lol - http://i.imgur.com/oV4KQrb.png

**Comment by mindforger** [comment]
same idea for the same purpose but a bit different style, a paternoster style elevator with multiple scoops going around 2 gears with a raising and a lowering side

you can insert items into the elevator from any north, south, east or west face(only when facing one of the active sides!), items from the raising side are spit out from the top face and items from the lowering side are spit out from the down face
multiple paternoster can be stacked to increase transport height
