### ISSUE TITLE
IE's recalculateCraftingRecipes fails to handle unknown IRecipes

### ISSUE THREAD

**Issue by Gaelan** [BluSunrize/ImmersiveEngineering#1036]
When joining a world with MineTweaker and Uncomplication, IE tries to recalculate recipes after MineTweaker does its thing, and runs into a custom IRecipe added by Uncomplication and raises a NullPointerException ([line]) and prevents joining the world. Note that `checkRecipes` handles this correctly.

[line]: https://github.com/BluSunrize/ImmersiveEngineering/blob/ab82aef869ad30551ae0e9ba1056e4bae42022ed/src/main/java/blusunrize/lib/manual/ManualPages.java#L718

Pinging @Aroma1997 and @stanhebben.

**Comment by malte0811** [comment]
#1013. Known bug that has been fixed for the next version.

**Comment by Aroma1997** [comment]
Afaik, this has been fixed in IE.

**Comment by BluSunrize** [comment]
As malte already said: It has been. >_>

**Comment by Gaelan** [comment]
Whoops!
