### ISSUE TITLE
Suggestion - Oil

### ISSUE THREAD

**Issue by Vingyy** [BluSunrize/ImmersiveEngineering#1040]
I really love this mod's style and how much it differs from other mods, but it feels like there is something missing. We have a Diesel generator but the only way to power it (from Immersive Engineering) is BioDiesel. Now I'm all for being environmentally friendly, but sometimes you need a cheap and dirty way of producing power. I think Oil would be a perfect addition to this mod. Just imagine a whole field of pumpjacks and dereks in the Immersive Engineering style all leading to a refinery to be made into usable fuel. I think it's time for a little black gold.

**Comment by James-T-Oudvoure** [comment]
Blusunrize has said he's not going to implement oil into the mod, because a biodiesel generator can only work using biodiesel. He was reluctant to try and make it work with Buildcraft oil.

**Comment by James-T-Oudvoure** [comment]
Also, why would you go through all of the effort to drill, pump, and refine this crap when biodiesel production is relatively easy to set up?

**Comment by Cracks777** [comment]
i use minetweaker to add oil as a fuel to the biodiesel generator and it works.

**Comment by BluSunrize** [comment]
Intersting, @Cracks777, because my dieselgen doesn't feature any Minetweaker integration...

Now, admittedly, the idea of a big oil jack is attractive, true that.
I wouldn't mind oil so much if it didn't come with the obligation of then making it into fuel and compatible with Buildcraft. I'd love to use my own complex refinery, but I fear that people would just go for BC's cheap one. And technically, normal fuel doesn't work in a diesel engine, because that uses compression ignition. So if anything, I'd make oil refine into diesel (not bio) to make that logical.
I'll run the idea past Hazard.

**Comment by Vingyy** [comment]
@James-T-Oudvoure It would be better than BioDiesel and I feel like this mod isn't about being the most efficient. Take the Crusher for example. Why build an expensive and large multiblock when a few decent pulverizers could do the same thing?

**Comment by Cracks777** [comment]
mabie its modtweaker then,

**Comment by BluSunrize** [comment]
@Vingyy The people that use pulverizers instead probably just shouldn't use this mod. I don't really care to compete with those.

@Cracks777 I doubt that. I don't think you even use a script to accomplish that.

**Comment by Cracks777** [comment]
@BluSunrize the dieselgen runs on buildcraft fuel also, so i refine oil in the refinery ( using minetweaker script) to make fuel to burn in the dieselgen.

**Comment by AHrubik** [comment]
It'd be awesome if you put in a diesel refinery but instead of going away from Buildcraft compatibility (it is still a game) lower the tick burn for gas from 18 to 16 and then add diesel with a tick burn of 24 to push people to make diesel. People would use it.

**Comment by Vingyy** [comment]
@BluSunrize I made a few rough possibilities for the pumpjacks if you're interested http://imgur.com/zzK7woI

Oil could be different than BC fuel, It could use the Core Sample Drill and it would work like the Excavator instead of actually spawning in the world. You could drill around until you found a reservoir and then build the machines to pump it out. It would probably have to run out, so it would be balanced.

I have a few ideas for conveyor belts too. I think a switch belt that changed flow direction when a redstone signal is input would be useful. Like how vanilla rails work. Also a way to stop a belt would be nice

**Comment by BluSunrize** [comment]
@Cracks777 You still didn't get it, right? I have internal compat for that. I just don't like the fact that I have it.

@AHrubik meh. Diesel generally isn't more powerful.

**Comment by Joshwoo69** [comment]
petrol? or Fuel Oil...
(https://en.wikipedia.org/wiki/Fuel_oil)

**Comment by AEnterprise** [comment]
@BluSunrize you might wana talk to @AlexIIL as he's been working on a new new refinery system for BC that is alot more complex

**Comment by BluSunrize** [comment]
Very vague statement @AEnterprise =P

**Comment by Vingyy** [comment]
@BluSunrize I'm not really sure what the max size for multiblocks is, but <a href="http://imgur.com/92AYPOU">here</a> is a prototype for a derrick if you're interested. Using <a href="https://www.google.com/search?q=pumpjack&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiY8tfIpPDLAhUBYSYKHYMEB1kQ_AUIBygB&biw=1600&bih=799#tbm=isch&q=oil+derrick&imgrc=CvywHmXFuwZlIM%3A">this</a> as a reference.

Is there any value to my ideas? Are these things possible?

**Comment by AEnterprise** [comment]
@BluSunrize not exactly sure, i think it's more pneumaticraft complex but i've only seen some code and gui's pass along, didn't see it in action yet, it's also not fully done or released yet

**Comment by Cracks777** [comment]
forgot, i have a custom build that adds oil as a fuel for the dieselgen

**Comment by BluSunrize** [comment]
@Cracks777: OH REALLY? WELL THAT'S A LOVELY LICENSE VIOLATION YOU GOT THERE. Get the hell off my github.

**Comment by Cracks777** [comment]
? How is it a licence violation? i couldnt find a licence anywhere?

**Comment by laz2727** [comment]
If there's no license, it means that the license is "all rights reserved" -
you can't do anything with it and you can barely look at the code.

**Comment by BluSunrize** [comment]
My code is visible source, but all compilations need to be authorized. Hence why Malte is perfectly fine in handing out debug versions, since I give him that permission. Heck I should really draft a custom license one of these days.

**Comment by elkillo** [comment]
This seems like an interesting addition but maybe it should work more like the excavator? as in there are oil veins and the pump jack can be built to acquire it. Just my 2 cents on this.

**Comment by Alexismachina** [comment]
I mean, if you want people to not use the buildcraft one, the IE one could have a better ratio for producing fuel or making fuel faster(maybe even both), at  the cost of more power requirement and materials?

**Comment by mindforger** [comment]
@Alexismachina would you care to read the whole answer? BC is cheap as hell! he does not want it cheap! By the way this topic is almost necro :P

**Comment by Alexismachina** [comment]
Alrigth

**Comment by elkillo** [comment]
my bad =P

**Comment by kittsville** [comment]
You can run the IE generator off of oil if it's first refined in a [Magneticraft refinery](http://ftbwiki.org/Refinery_%28Magneticraft%29) into light oil/heavy oil/natural gas. The refinery produces way too much fuel for the amount the generator uses but that's just a balance issue. It otherwise keeps with multiblock aesthetic.
![Generator Room](https://cloud.githubusercontent.com/assets/6013087/15523088/965dbd58-220f-11e6-93a4-07ef6fdb22da.png)

**Comment by mindforger** [comment]
@kittsville but that is not the point of this issue! It was about having a native support of oil -> somesortofcomplexrefinery -> somesortoffuel -> diesel power .. but BC fuel is way to cheap to accomplish and I am sure on your own comment your way is the same ... why do people not read the answers!?

**Comment by kittsville** [comment]
@mindforger I read the answers, specifically:

>I wouldn't mind oil so much if it didn't come with the obligation of then making it into fuel...

My comment was to make people aware that a compatible refinery system exists that keeps with IE's multiblock aesthetic.

W.r.t. fuel being too cheap, as I stated it is just a balance issue. This can be fixed by tweaking the amount of fuel the generator consumes or the oil's generation in each mod's respective config files. I did just that when switching to using the IE generator and it has worked fine for months.

**Comment by SynfulChaot** [comment]
I'd love to see your take on the entire oil refining process.  I don't think i'm the only one who would disable the BuildCraft refinery in packs with more in-depth refining processes.

**Comment by alfuken** [comment]
+1 for IE oil industry. Don't think about BC compat, a) not everybody uses BC, and b) who needs BC when everything you need is present in IE?

**Comment by HappyPineapple** [comment]
Hey [Click Here](https://minecraft.curseforge.com/projects/immersive-petroleum?gameCategorySlug=mc-mods&projectID=268250) and stop hslling @BluSunrize

**Comment by mindforger** [comment]
wow ... necro posting AND advertising another mod vial "Click here" link

next time just mention only the mod n ame, linking "Click here" is highly suspicious

but indeed there is the addon mod **immersive petroleum** just doing this

**Comment by HappyPineapple** [comment]
thank you .................... I think

**Comment by BluSunrize** [comment]
Christ on a bike.
