### ISSUE TITLE
Issue with Industrial Coke Oven and Creosote OIl

### ISSUE THREAD

**Issue by Vingyy** [BluSunrize/ImmersiveEngineering#1041]
When setting up an Industrial Coke oven I hooked it up to a Tank with fluid pipes, but there is an issue. The oil was not being ejected at first, but that isn't the main issue. When I came back to it, the oven says it has negative oil and there isn't oil in the tank, so I'm not really sure what's going on.

**Comment by AlterAkima** [comment]
Immersive Integration issue.

**Comment by BluSunrize** [comment]
Correct. Not my mod.

**Comment by Cracks777** [comment]
this has been fixed IIRC in the latest version of Immersive Integration.
