### ISSUE TITLE
Tier below Arc Furnace

### ISSUE THREAD

**Issue by Vingyy** [BluSunrize/ImmersiveEngineering#1042]
The Arc furnace is a very interesting and powerful machine. It is extremely fast, but it is also very expensive and requires maintenance. I think there should be some kind of basic smelter below the arc furnace, but is still better than a vanilla furnace. I suppose there is the external heater, but I don't think that is as interesting as a multiblock machine. Perhaps some sort of powered vat similar to Tinkers' Construct (in look not how it works) that can only smelt 1-2 types of ore/dust at a time, maybe external heaters could be incorporated into it somehow.

**Comment by BluSunrize** [comment]
The tier below it is called "Improved Blast Furnace"
Progression is intended as is.
