### ISSUE TITLE
Badass Mining Drill on mobs

### ISSUE THREAD

**Issue by MineWitherMC** [BluSunrize/ImmersiveEngineering#1044]
Hello, I found a bug with Mining Drill: when u attack mobs neither biodiesel or drill head deplete. So it's basically a badass "sword" without durability/consumables with +10 damage (2-hit zombie kill)

**Comment by BluSunrize** [comment]
Yeah but it also costs almost a full stack of steel to make.

**Comment by MineWitherMC** [comment]
So, it's correct?

**Comment by BluSunrize** [comment]
Well it's not intended, but I'm not seriously bothered again.
