### ISSUE TITLE
StackOverflow

### ISSUE THREAD

**Issue by Ksnz** [BluSunrize/ImmersiveEngineering#1045]
http://pastebin.com/qXMYS1Wh
When update to 0.7.5

Reverting to 0.7.4 fix that

**Comment by BluSunrize** [comment]
@malte0811 Your new energy system probably did that =P

**Comment by malte0811** [comment]
Yep, but only because `invalidate` seems to be called on chunkLOAD. Is that normal?

**Comment by BluSunrize** [comment]
I don't even know anymore. Invalidate went to shit in 1.8, I moved to breakBlock instead

**Comment by malte0811** [comment]
> KCauldron Version: pw.prok:KCauldron:1.7.10-1614.200 Official

Please try without Cauldron/KCauldron, so on a normal forge server.

**Comment by malte0811** [comment]
@Ksnz Did removing (K)Cauldron help?

**Comment by BluSunrize** [comment]
No futher info given, issue closed.
