### ISSUE TITLE
[0.75] Village house generates even with option disiabled in desert village

### ISSUE THREAD

**Issue by filloax** [BluSunrize/ImmersiveEngineering#1046]
![2016-04-07_22 12 57](https://cloud.githubusercontent.com/assets/3884952/14365468/1a28343c-fd0e-11e5-99d0-1da09d3c38dd.png)

*disabled

**Comment by malte0811** [comment]
Is that a normal desert biome or one added by a mod?

**Comment by filloax** [comment]
Biomes o plenty,  I'll say exactly which one should soon as I get home

**Comment by filloax** [comment]
It's Xeric Shrubland (HOT, PLAINS, SANDY in biomedict)
