### ISSUE TITLE
[Suggestion] Pumping creosote out of oven

### ISSUE THREAD

**Issue by p75369** [BluSunrize/ImmersiveEngineering#1048]
I suspect I'm just doing this wrong (if I am though, can I turn this into a suggestion of "please work like this)? 

I'm trying to pump creosote out of my coke ovens using the attached setup and it's not working. The same setup was working when I was using it to take milk out of an MFR rancher though.
It does work when the pump is adjacent to an oven, at the cost of aesthetics though.

http://i.imgur.com/8BrtRRD.png
(I thought I could upload a picture here, but "something went really wrong"... how helpful ¬_¬)

**Comment by theunkn0wn1** [comment]
Two things I noticed on a cursory glance over:
Last I checked pumps must be directly attached to the inventory they are to extract from with the orange port facing toward said inventory yet neither criteria appears to have been met. Also, the pump must be powered in order to extract fluids


As for the rancher, does that device auto output ?

**Comment by mallrat208** [comment]
The Rancher does auto-output and pipes/pumps , like theunk0wn1 metioned, don't have suction like you're trying to do unfortunately.

**Comment by theunkn0wn1** [comment]
So in conclusion, not a bug. Unfortunately the piping system within IE simply does not behave in your expected manor. 

Though I do agree with what you attempted, the idea of being able to have a centralized pumping station is much more logical and  practical than the current implementation.

**Comment by p75369** [comment]
Thanks both, I thought that would be the case, ammended the title to suit the "please make it work like this" request.

**Comment by mindforger** [comment]
>with the orange port facing toward said inventory

slightly wrong :) blue is input, orange is output

**Comment by theunkn0wn1** [comment]
Oops... I knew that.... Yeah minor slip up on my part there. Was pulling from memory 🤗
