### ISSUE TITLE
Conveyor Belts connections issue

### ISSUE THREAD

**Issue by iTpyn** [BluSunrize/ImmersiveEngineering#105]
In IE 0.2.4 connection between Conveyor Belts taking items down gets broken. Arrow is showing the direction of items transferring

It's fine wneh there're only 2 belts
http://i.imgur.com/NLZSUIm.jpg

As soon as you place third, connection gets broken
http://i.imgur.com/dPdqp9X.jpg

Issue doesnt affect belts taking items up
http://i.imgur.com/tlggPEv.jpg

**Comment by BluSunrize** [comment]
Ah, thanks, I'll look into it
