### ISSUE TITLE
IC2 power transmission bugged when using IC2 cables

### ISSUE THREAD

**Issue by empirebuilder1** [BluSunrize/ImmersiveEngineering#1050]
I'm either an idiot, missing something, or the victim of some rather annoying power transport bugs.  

Bear with me, this might get lengthy.  

So I found your mod not that long ago - It was the true answer to all my prayers. Finally, proper hanging cables! I promptly built a 500 meter HV transmission line from my main industrial center to an outlying friend's base that's been struggling along on a couple coal fired generators just to keep the creepers away. I happily hooked all the required cables together and threw the switch - alas! The power refused to flow!  

So I jumped into a creative game for the sake of resource conservation, and tested a few usage cases. 
* The first: A basic [batbox - to - batbox transmission](http://i.imgur.com/2HXWcxG.png). The batbox on the right is fed by a solar panel, and outputs energy to the second batbox, which accepts it readily and with no problems. 
* The second: Batbox-to-Batbox, but [with an IC2 cable in between](http://i.imgur.com/cwLkOjH.png). The batbox on the right continues to feed power to the batbox on the left, but with a single bit of IC2 cable on the transmitting connector. Still no issues. 
* And then the third: [Same as the two above](http://i.imgur.com/jLMuTzp.png), but with the wire connectors on both the transmitting and receiving ends attached to IC2 cable. Aha, the problem becomes apparent! No power will flow!  

So the issue is thus: When a wire connector from Immersive Engineering is attached to an IC2 cable, it can transmit power fine but refuses to accept power in any way. If I were to guess, it would have something to do with the mod "conforming" the power to the RF standard before transmitting it, as using the Engineer's Voltmeter [reports the transmitting wire connector](http://i.imgur.com/czB2mxI.png) has it's RF buffer full.  

Edit: I can work around this by using HV Transformers from IC2 whenever I need to change between power networks, but this is inconvenient and expensive, and leads to more than a few problems when I leave the area. (since IC2 machines don't function in unloaded chunks! D'oh!)

**Comment by AlterAkima** [comment]
IC2 energy storage only output from one side, the one with the dot.

**Comment by mindforger** [comment]
you hit it dead on, this mod is based on RF it is not designed to be an multi way converter, it just pleases some needs by converting RF to EU not the other way around :)

**Comment by empirebuilder1** [comment]
I still have a difficult time understanding why outputting directly to a machine works, but outputting to a cable does not. Regardless of the conversion taking place, it should still be able to output EU to a cable, or maybe the conversion code doesn't work well with the IC2 energy net. Either way, Extra Utilities in this case has a direct EU to RF transformer, so I think I'll get into the habit of conforming my electricity to RF before transmitting it long distances, or at least keep working around it using IC2 transformers which are slightly cheaper.
