### ISSUE TITLE
[Crash Bug] Achievement Screen Crash

### ISSUE THREAD

**Issue by MonaMoonlight** [BluSunrize/ImmersiveEngineering#1053]
In the achievement screen, going to the top, where the background is mostly dirt, up to the point where you can see sand, causes the game to crash by way of some sort of out of bounds error.

> Description: Rendering screen
> 
> java.lang.IllegalArgumentException: bound must be positive
> 	at java.util.Random.nextInt(Unknown Source)
> 	at net.minecraft.client.gui.achievement.GuiAchievements.func_146552_b(GuiAchievements.java:320)
> 	at net.minecraft.client.gui.achievement.GuiAchievements.func_73863_a(GuiAchievements.java:210)
> 	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1061)
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
> 	at net.minecraft.client.main.Main.main(SourceFile:148)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

I have tested this with and without mods, with only IE in mod folder, and with all except IE in mod folder, and it only occurs when IE is in.

**Comment by BluSunrize** [comment]
I have not the foggiest. That's a purely vanilla contained crash .-.

**Comment by MonaMoonlight** [comment]
@BluSunrize What other information do you need?

**Comment by BluSunrize** [comment]
Well you can give me the full log, pastebinned, but I'm not sure if that does anything. I understand Mojangs code too little to see the obvious piece on this one.

However, if this only triggers by going all the way up on the screen, can you play without scolling up there?

**Comment by MonaMoonlight** [comment]
I think it has to do with the positions of the achievements above the workbench one, so maybe if you moved them down so the're at or below the lowest rendered dirt in the background and tested? That may be grasping at a straw, but it's the only thing I can think of that might cause it to go out of bounds, 'cause no other mod achievement trees go further than that, and when those mods are loaded, the crash doesn't happen.
