### ISSUE TITLE
Improved blast furnace multiblock size discrepancy.

### ISSUE THREAD

**Issue by NolanSyKinsley** [BluSunrize/ImmersiveEngineering#1054]
The multiblock to make the improved blast furnace is 3x4x3 yet the completed structure is 4x5x5 (it expands 2 blocks in one direction, 1 block in another, plus 1/2 block in height), and there doesn't seem to be a way to dictate which way it expands, at least not that I have seen.

This makes it incredibly difficult to plan out or implement a base design or automation system, and comes as quite a shock when you first build it. Multiblocks should only shrink or stay within the constraints of the structure used to build them, they really shouldn't expand on completion. I would rather have a slightly more expensive, larger multiblock and know exactly what I am getting into than a cheaper smaller multiblock that seems to have a mind of it's own about where it expands.

A way to set the orientation would be nice as well, maybe using an engineering block in the multiblock to signify the front( may just be missing how to orient it currently).

**edit**

I can see the size discrepancy goes even farther now, it appears the mutliblock also expands one block below the multiblock base structure, as seen here. http://i.imgur.com/P8w9zYm.png

**Comment by p75369** [comment]
Maybe you post some pictures on what you're seeing because it sounds like something isn't working for you.

[You should see this.](http://imgur.com/a/x7x0H)

**Comment by NolanSyKinsley** [comment]
edited post just before I saw you commented.

**Comment by p75369** [comment]
Yeah, glitched, those are actually several multiblocks layered over eachother (one full multiblock per constituant block it seems). I had that happen to me once, break a block and try forming it again.

**Comment by p75369** [comment]
Also, regarding the orientation the side you hammer will be the front.

**Comment by NolanSyKinsley** [comment]
The multiblock always does this on forming to me, I just tried relogging after forming and it does revert to it's correct shape.

**Comment by AlterAkima** [comment]
The sides should have only one vent, not nine, likely Optifine messing arround with the models.

**Comment by NolanSyKinsley** [comment]
I tried without optifine, it does seem to be the issue. When I make the multiblock without it I do see all blocks of the multiblock turn into the blast furnace for a single frame, but then they collapse into one.

**Comment by NolanSyKinsley** [comment]
Closing due to being caused by outside mod.
