### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by Roadhog360** [BluSunrize/ImmersiveEngineering#1055]
---- Minecraft Crash Report ----
// Shall we play a game?

Time: 12/04/16 16:09
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: vazkii/botania/api/item/TinyPotatoRenderEvent
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: vazkii/botania/api/item/TinyPotatoRenderEvent
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
	at java.lang.Class.privateGetPublicMethods(Class.java:2894)
	at java.lang.Class.getMethods(Class.java:1607)
	at cpw.mods.fml.common.eventhandler.EventBus.register(EventBus.java:60)
	at blusunrize.immersiveengineering.common.util.compat.BotaniaHelper.init(BotaniaHelper.java:60)
	at blusunrize.immersiveengineering.common.util.compat.IECompatModule.doModulesInit(IECompatModule.java:76)
	at blusunrize.immersiveengineering.ImmersiveEngineering.init(ImmersiveEngineering.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	... 10 more
Caused by: java.lang.ClassNotFoundException: vazkii.botania.api.item.TinyPotatoRenderEvent
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 44 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 653820848 bytes (623 MB) / 1813757952 bytes (1729 MB) up to 3194421248 bytes (3046 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 CoFHTweaks v1.1.2 Minecraft Forge 10.13.4.1558 131 mods loaded, 131 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHI	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10.jar) 
	UCHI	appliedenergistics2-core{rv2-stable-4} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHI	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UCHI	NotEnoughItems{1.0.5.111} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
	UCHI	OpenModsCore{0.7} [OpenModsCore] (minecraft.jar) 
	UCHI	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHI	<CoFH Tweak>{1.7.10R1.1.2} [CoFH Tweak ASM] (CoFHTweaks-[1.7.10]1.1.2-89.jar) 
	UCHI	debug{1.0} [debug] (Dense-Ores-Mod-1.7.10.jar) 
	UCHI	lucky{5.1.0} [Lucky Block] ([1-7-10]_Lucky_Block_v5-1-0.jar) 
	UCHI	simplecore{1.1.1.1} [SimpleCore API] ([1.7.10]simplecore-1.7.10-1.1.1.1.jar) 
	UCHI	fusion{1.6.0} [Fusion] ([1.7.10] Fusion v1.6.0.jar) 
	UCHI	netherrocks{1.3.0} [Netherrocks] ([1.7.10] Netherrocks v1.3.0.jar) 
	UCHI	simpleores{1.6.0} [SimpleOres 2] ([1.7.10] SimpleOres 2 v1.6.0.jar) 
	UCHI	aesthetics{1.1.0} [Aesthetics] ([1.7.10] Aesthetics v1.1.0.jar) 
	UCHI	machines{1.0.0} [Machines] ([1.7.10] Machines v1.0.0.jar) 
	UCHI	FLabsBF{4.3} [Better Furnaces] ([1.7.10]Better_Furnaces_V4.3.jar) 
	UCHI	craftablechain{1.2} [Craftable Chain] ([1.7.2]CraftableChain.jar) 
	UCHI	woolarmor{1.0} [Wool Armor] ([1.7.2]woolarmour.jar) 
	UCHI	IC2{2.2.628-experimental} [IndustrialCraft 2] (_Industrial-Craft-2-Mod-Experimental-1.7.10.jar) 
	UCHI	AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels] (AdvancedSolarPanel-1.7.10-3.5.1.jar) 
	UCHI	AgriCraft{1.7.10-1.3.1} [AgriCraft] (AgriCraft-1.7.10-1.3.1.jar) 
	UCHI	appliedenergistics2{rv2-stable-4} [Applied Energistics 2] (appliedenergistics2-rv2-stable-4.jar) 
	UCHI	ATG{0.10.0} [Alternate Terrain Generation] (ATG-1.7.10-0.12.0.jar) 
	UCHI	CoFHCore{1.7.10R3.1.2} [CoFH Core] (CoFHCore-[1.7.10]3.1.2-325.jar) 
	UCHI	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHI	ThermalFoundation{1.7.10R1.2.3} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.3-112.jar) 
	UCHI	ThermalExpansion{1.7.10R4.1.2} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.2-240.jar) 
	UCHI	BigReactors{0.4.3A} [Big Reactors] (BigReactors-0.4.3A.jar) 
	UCHI	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHI	Botania{r1.6-174} [Botania] (Botania r1.6-174.jar) 
	UCHI	DraconicEvolution{1.0.1c} [Draconic Evolution] (Draconic-Evolution-1.7.10-1.0.1c.jar) 
	UCHI	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) 
	UCHI	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) 
	UCHI	BuildCraft|Core{7.0.8} [BuildCraft] (buildcraft-7.0.8.jar) 
	UCHI	Forestry{3.5.7.16} [Forestry for Minecraft] (forestry_1.7.10-3.5.7.16.jar) 
	UCHI	Railcraft{9.10.0.0} [Railcraft] (Railcraft_1.7.10-9.10.0.0.jar) 
	UCHE	ImmersiveEngineering{0.7.5} [Immersive Engineering] (ImmersiveEngineering-0.7.5.jar) 
	UCHI	MineFactoryReloaded{1.7.10R2.8.0} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHI	TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct] (TConstruct-1.7.10-1.8.5(1).jar) 
	UCHI	B0bGrowsOre{2.3.1} [B0bGary's Growable Ores] (B0bGary's Growable Ores-2.3.1 for 1.7.10.jar) 
	UCHI	BiblioCraft{1.10.3} [BiblioCraft] (BiblioCraft[v1.10.3][MC1.7.10].jar) 
	UCHI	BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition] (BiblioWoods[Forestry][v1.7].jar) 
	UCHI	BiblioWoodsNatura{1.3} [BiblioWoods Natura Edition] (BiblioWoods[Natura][v1.3].jar) 
	UCHI	BinnieCore{2.0-pre9} [Binnie Core] (binnie-mods-2.0-pre9.jar) 
	UCHI	Botany{2.0-pre9} [Botany] (binnie-mods-2.0-pre9.jar) 
	UCHI	ExtraBees{2.0-pre9} [Extra Bees] (binnie-mods-2.0-pre9.jar) 
	UCHI	ExtraTrees{2.0-pre9} [Extra Trees] (binnie-mods-2.0-pre9.jar) 
	UCHI	Genetics{2.0-pre9} [Genetics] (binnie-mods-2.0-pre9.jar) 
	UCHI	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-2.jar) 
	UCHI	bookshelf{1.2.0} [Bookshelf] (Bookshelf-1.7.10-1.2.0.jar) 
	UCHI	BuildCraft|Builders{7.0.8} [BC Builders] (buildcraft-7.0.8.jar) 
	UCHI	BuildCraft|Energy{7.0.8} [BC Energy] (buildcraft-7.0.8.jar) 
	UCHI	BuildCraft|Robotics{7.0.8} [BC Robotics] (buildcraft-7.0.8.jar) 
	UCHI	BuildCraft|Silicon{7.0.8} [BC Silicon] (buildcraft-7.0.8.jar) 
	UCHI	BuildCraft|Transport{7.0.8} [BC Transport] (buildcraft-7.0.8.jar) 
	UCHI	BuildCraft|Factory{7.0.8} [BC Factory] (buildcraft-7.0.8.jar) 
	UCHI	CarpentersBlocks{3.3.5} [Carpenter's Blocks] (Carpenter's Blocks v3.3.5 - MC 1.7.10.jar) 
	UCHI	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCHI	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHI	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCHI	props{2.0.2} [Decocraft] (Decocraft-2.0.2_1.7.10.jar) 
	UCHI	emeraldobsidianmod{1.3.1} [Emerald & Obsidian tools/armor mod] (emeraldobsidianmod-1.7.10-1.3.1.jar) 
	UCHI	EnderIO{1.7.10-2.2.8.381} [Ender IO] (EnderIO-1.7.10-2.2.8.381.jar) 
	UCHI	EnderStorage{1.4.7.36} [EnderStorage] (EnderStorage-1.7.10-1.4.7.36-universal.jar) 
	UCHI	etfuturum{1.5.5} [Et Futurum] (Et Futurum-1.5.5.jar) 
	UCHI	harvestcraft{1.7.10i} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10i.jar) 
	UCHI	ExtraTiC{1.4.5} [ExtraTiC] (ExtraTiC-1.7.10-1.4.5.jar) 
	UCHI	fastleafdecay{1.1} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.1.jar) 
	UCHI	ForbiddenMagic{1.7.10-0.562} [Forbidden Magic] (Forbidden Magic-1.7.10-0.562.jar) 
	UCHI	foxlib{1.7.10-0.7.0} [FoxLib] (FoxLib-1.7.10-0.7.0.jar) 
	UCHI	furnus{1.72} [Furnus] (Furnus-1.7.10-1.72.jar) 
	UCHI	GraviSuite{1.7.10-2.0.3} [Graviation Suite] (GraviSuite-1.7.10-2.0.3.jar) 
	UCHI	guideapi{1.7.10-1.0.1-20} [Guide-API] (Guide-API-1.7.10-1.0.1-20.jar) 
	UCHI	HopperDuctMod{1.3.2} [Hopper Ducts] (hopperductmod-1.7.10-1.3.2.jar) 
	UCHI	IC2NuclearControl{2.1.2a} [Nuclear Control 2] (IC2NuclearControl-2.1.2a.jar) 
	UCHI	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) 
	UCHI	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHI	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
	UCHI	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.0} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	MineFactoryReloaded|CompatAtum{1.7.10R2.8.0} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.0} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.0} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.0} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.0} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	MineFactoryReloaded|CompatForestry{1.7.10R2.8.0} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.0} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	MineFactoryReloaded|CompatIC2{1.7.10R2.8.0} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	MineFactoryReloaded|CompatMystcraft{1.7.10R2.8.0} [MFR Compat: Mystcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.7.10-1.1.0.33-universal.jar) 
	UCHI	ProjRed|Core{4.7.0pre12.95} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre12.95-Base.jar) 
	UCHI	ProjRed|Exploration{4.7.0pre12.95} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre12.95-World.jar) 
	UCHI	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.0} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.0} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.0} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.0} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.0} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.0} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.0} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.0} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.0-104.jar) 
	UCHI	morechisels{@VERSION@} [More Chisels] (MoreChisels-1.7.10-1.0-28.jar) 
	UCHI	NetherOres{1.7.10R2.3.1} [Nether Ores] (NetherOres-[1.7.10]2.3.1-22.jar) 
	UCHI	OpenMods{0.7} [OpenMods] (OpenModsLib-1.7.10-0.7.jar) 
	UCHI	OpenBlocks{1.4} [OpenBlocks] (OpenBlocks-1.7.10-1.4.jar) 
	UCHI	OpenPeripheralCore{1.0} [OpenPeripheralCore] (OpenPeripheral-1.7.10-AIO-2.jar) 
	UCHI	OpenPeripheralIntegration{0.2} [OpenPeripheralIntegration] (OpenPeripheral-1.7.10-AIO-2.jar) 
	UCHI	OpenPeripheral{0.3} [OpenPeripheralAddons] (OpenPeripheral-1.7.10-AIO-2.jar) 
	UCHI	ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHI	ProjRed|Transportation{4.7.0pre12.95} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
	UCHI	ProjRed|Compatibility{4.7.0pre12.95} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre12.95-Compat.jar) 
	UCHI	ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHI	ProjRed|Fabrication{4.7.0pre12.95} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre12.95-Fabrication.jar) 
	UCHI	ProjRed|Illumination{4.7.0pre12.95} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre12.95-Lighting.jar) 
	UCHI	ProjRed|Expansion{4.7.0pre12.95} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre12.95-Mechanical.jar) 
	UCHI	rftools{2.93} [RFTools] (rftools-2.93.jar) 
	UCHI	Roguelike{1.3.4} [Roguelike Dungeons] (roguelike-1.7.10-1.3.4.jar) 
	UCHI	sinhikabark{1.7.2-0.03} [Sinhika's Bark] (SinhikaBark-1.7.2-0.03.jar) 
	UCHI	StorageDrawers{1.7.10-1.9.7} [Storage Drawers] (StorageDrawers-1.7.10-1.9.7.jar) 
	UCHI	Tails{1.7.10-1.4.1a} [Tails] (Tails-1.7.10-1.4.1a.jar) 
	UCHI	ThermalDynamics{1.7.10R1.0.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.0.0-122.jar) 
	UCHI	witchery{0.20.0} [Witchery] (witchery-1.7.10-0.20.0.jar) 
	UCHI	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHI	ForgeRelocation{0.0.1.4} [ForgeRelocation] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
	UCHI	MCFrames{1.0} [MCFrames] (ForgeRelocation-1.7.10-0.0.1.4-universal.jar) 
	UCHI	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
	UCHE	aobd{2.7.1} [Another One Bites The Dust] (AOBD-2.7.1.jar) 
	UCHI	denseores{1.0} [Dense Ores] (Dense-Ores-Mod-1.7.10.jar) 
	UCHI	IguanaTweaksTConstruct{1.7.10-2.0.3} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.0.3.jar) 
	UCHI	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 359.06' Renderer: 'GeForce GTX 645/PCIe/SSE2'
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	AE2 Version: stable rv2-stable-4 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.1.2-325
	ThermalFoundation: -[1.7.10]1.2.3-112
	ThermalExpansion: -[1.7.10]4.1.2-240
	Mantle Environment: Environment healthy.
	MineFactoryReloaded: -[1.7.10]2.8.0-104
	TConstruct Environment: Environment healthy.
	NetherOres: -[1.7.10]2.3.1-22
	ThermalDynamics: -[1.7.10]1.0.0-122
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8

Here's that crash report I promised. Posted here as you told me to.
What gives?

**Comment by Joshwoo69** [comment]
ohhh my god... PLEASE PUT IT in pastebin or something...

**Comment by Joshwoo69** [comment]
also.. not our problem... botania issues. update botania.

**Comment by Roadhog360** [comment]
Why? It's still going to be a wall of text?

**Comment by mindforger** [comment]
@Roadhog360 but the wall is behind a link, your issue is ginormous and makes me cringe when i have to scroll all the way to get eventual additional text, just be nice and do it

**Comment by Roadhog360** [comment]
A wall is a wall.

On 12 Apr 2016, at 11:07 PM, mindforger <notifications@github.com<mailto:notifications@github.com>> wrote:


@Roadhog360<https://github.com/Roadhog360> but the wall is behind a link, your issue is ginormous and makes me cringe when i have to scroll all the way to get eventual additional text, just be nice and do it

**Comment by mindforger** [comment]
> A wall is a wall.

obviously in your head, why can't you be nice? you are awaiting others to solve your problems but you wont give in to them, thats not really fair

but before this derails, i'll shut up
just as Josh said
>also.. not our problem... botania issues. update botania.

**Comment by Roadhog360** [comment]
Eh, I'm messing with you, if you couldn't already tell. Lighten up, please.

On 12 Apr 2016, at 11:22 PM, mindforger <notifications@github.com<mailto:notifications@github.com>> wrote:


A wall is a wall.

obviously in your head, why can't you be nice? you are awaiting others to solve your problems but you wont give in to them, thats not really fair

but before this derails, i'll shut up
just as Josh said

also.. not our problem... botania issues. update botania.

**Comment by Joshwoo69** [comment]
@roadhog360 welcome to github. we take all seriousness here.

> vazkii/botania/
here the have the evidence. update botania.
and I have no idea why vazkii and IE have in relation.

**Comment by BluSunrize** [comment]
Okay, let's make this very clear.
When you report an issue? You ALWAYS spoiler the crashlogs. Developers may chose to ignore your issue simply because you don't, or even better decide to be a douche about it afterwards.
Secondly, I do appreciate the help, but it is noones job but mine or my contributors to lecture people on their manners on this tracker. Backseat modding leaves a bad impression, but thank you for your concern @Joshwoo69

Finally:
Your Botania is ages old. Update it. Issue closed.

**Comment by Roadhog360** [comment]
I didn't see any editing features to spoiler it in.
And for the LOVE OF GOD, MY ACTIONS WERE JUST A PLAYFUL JOKE! Do you know what that is, people, because I don't think ANY of you do!

On 13 Apr 2016, at 12:48 PM, BluSunrize <notifications@github.com<mailto:notifications@github.com>> wrote:


Okay, let's make this very clear.
When you report an issue? You ALWAYS spoiler the crashlogs. Developers may chose to ignore your issue simply because you don't, or even better decide to be a douche about it afterwards.
Secondly, I do appreciate the help, but it is noones job but mine or my contributors to lecture people on their manners on this tracker. Backseat modding leaves a bad impression, but thank you for your concern @Joshwoo69<https://github.com/Joshwoo69>

Finally:
Your Botania is ages old. Update it. Issue closed.

**Comment by Roadhog360** [comment]
Well, I apologise if my actions seemed rude in any way. Earlier I misread your comment as also calling me a douche, when that didn't seem to be what you were doing. Again, I am sory for that little explosion there.
Also, your solution didn't seem to work.

**Comment by BluSunrize** [comment]
If my solution doesn't work, then you show us the new crashlog.

**Comment by Roadhog360** [comment]
How do I see that on Tehnic?

On 14 Apr 2016, at 12:23 AM, BluSunrize <notifications@github.com<mailto:notifications@github.com>> wrote:


If my solution doesn't work, then you show us the new crashlog.

**Comment by BluSunrize** [comment]
Your game crashes. It generates a crashlog. You copy it to pastebin, you link it to us. Literally the same way you got the initial log.

**Comment by Roadhog360** [comment]
I pasted my previous one from the launcher.

On 14 Apr 2016, at 4:23 AM, BluSunrize <notifications@github.com<mailto:notifications@github.com>> wrote:


Your game crashes. It generates a crashlog. You copy it to pastebin, you link it to us. Literally the same way you got the initial log.

**Comment by BluSunrize** [comment]
Then do the same AGAIN?!

**Comment by Roadhog360** [comment]
http://pastebin.com/RhzKKA6i

**Comment by Joshwoo69** [comment]
update Another one bites the dust.

**Comment by Roadhog360** [comment]
How much do I have to update?

**Comment by Joshwoo69** [comment]
get version checker for minecraft too.

**Comment by BluSunrize** [comment]
Just make sure to keep all your mods on latest >__<

Not going for latest versions makes you miss out on a lot of content and bugfixes. If there's updates, always get them.

**Comment by Roadhog360** [comment]
Alright. I'll tell you guys how it works when I get home?

On 14 Apr 2016, at 7:58 AM, BluSunrize <notifications@github.com<mailto:notifications@github.com>> wrote:


Just make sure to keep all your mods on latest >__<

Not going for latest versions makes you miss out on a lot of content and bugfixes. If there's updates, always get them.

**Comment by Roadhog360** [comment]
Updates worked! Thanks so much everyone!
And since this is GitHub, I'll be more serious in the future.
