### ISSUE TITLE
Issue with Issues

### ISSUE THREAD

**Issue by mindforger** [BluSunrize/ImmersiveEngineering#1056]
hey BluSunrize, i thought about helping out with the issues issue and most certainly the wall of text 

you can deploy a "ISSUES_TEMPLATE.md" file in your project to always present the poster an tempplate with ccertain informations

have a look at my example
https://github.com/mindforger/IssuesTemplateExample

you deploy a .github folder and the file inside the folder

**Comment by Joshwoo69** [comment]
I agree to this. +1

**Comment by mindforger** [comment]
you can add a link to the optifine issue tracker to the template .. didn't know until now there is such tracker XD 

https://github.com/sp614x/optifine/issues

**Comment by malte0811** [comment]
What do you think about [this](https://github.com/malte0811/ImmersiveEngineering/blob/tmp/CONTRIBUTING.md)? It is not an issue template, but I don't want users to include all the explanations about reporting a bug in their bug report. The forge repository uses the contributing.md file as well, [this](https://github.com/MinecraftForge/MinecraftForge/issues/new) is what it looks like when reporting an issue.

**Comment by mindforger** [comment]
yeah i am kinda sure most will not even see the link above XD but you can combine it with a tempplate that tells you in h3 size to read the guide and remove the line afterwards XD

**Comment by malte0811** [comment]
Good idea, I'll add that tomorrow

**Comment by malte0811** [comment]
"Fixed" in 89b189b7652f883bc76e0c7551f8ae22c3630fdb, I just forgot to reference the issue.

**Comment by BluSunrize** [comment]
Man, am I glad I have you guys for figurign this stuff out =P

I'll probably tend to the PR tomorrow, I have massive travel exhaustion because of PAX. ^^
