### ISSUE TITLE
Items not visible in Coke Furnace

### ISSUE THREAD

**Issue by mgwerner** [BluSunrize/ImmersiveEngineering#1059]
Neither wood nor charcoal are visible in the furnace, although wood is being processed.  This occurs upon placement of wood into furnace, but seems to correct if chunk is unloaded and reloaded.  Have not been able to reproduce with coal.

**Comment by AlterAkima** [comment]
Is Optifine present? If so, not an issue.

**Comment by mgwerner** [comment]
Yes, Optifine is running.  Conflict?

**Comment by AlterAkima** [comment]
No, it changes the way some rendering works, most of time it just doens't cooperate with mods.

**Comment by mgwerner** [comment]
Is there a fix, or simply unload-reload?

**Comment by AlterAkima** [comment]
The best solution is to remove Optifine.

**Comment by mgwerner** [comment]
Not an option, give too much boost in FPS.  Unless there is an alternative to the poorly-rendered code in the graphics of Minecraft.  Suggestions?

**Comment by Joshwoo69** [comment]
there is Fastcraft by player

**Comment by Joshwoo69** [comment]
or COFHTweaks(I wouldn't recommend it though my MC textures became invisible :/ )

**Comment by mgwerner** [comment]
OK, thanks, will look into the alternatives.  Cheers

**Comment by BluSunrize** [comment]
Yeah optifine issue. Closed.
