### ISSUE TITLE
Fermenter and Squeezer not checking slot restrictions on the ISidedInventory interface

### ISSUE THREAD

**Issue by KoxAlen** [BluSunrize/ImmersiveEngineering#106]
In the current form you can "pipe in" anything into any slot
(_Look at the liquid container slots_)
Using: 0.2.4
![image](https://cloud.githubusercontent.com/assets/1060483/8374812/c449f222-1bf8-11e5-9d64-85a9edfb8f8a.png)

**Comment by BluSunrize** [comment]
Fixed!
