### ISSUE TITLE
Assembler outputting everything

### ISSUE THREAD

**Issue by charles7926** [BluSunrize/ImmersiveEngineering#1060]
In the last few days my assembler has started outputting everything instead of just the final recipe.  Meaning even if the first recipe is used in the second and the second in the third, the assembler will only output the first recipe.

**Comment by BluSunrize** [comment]
This was caused by your fix in the last version, wasn't it, @malte0811? I should have spotted that. My bad.

**Comment by malte0811** [comment]
Yes, I forgot to check whether the item is an ingredient...
