### ISSUE TITLE
Gregtech API Issue

### ISSUE THREAD

**Issue by g234987** [BluSunrize/ImmersiveEngineering#1061]
I'm getting a crash with ImmersiveEngineering when attempting to connect a MV connector from a kinetic generator to an IC2 batbox. The open eye report details the statcktrace and installed mods. The issue looks to be pretty straightforward outdated API (NoClassDefFoundError) problem. Can you update to the latest GT api? 

This issue can be reproduced by putting a connector on both the batbox and generator. As soon as the wire is connected the crash will occur. The crash will occur again on world restart preventing any further loads of the world.

I'm running ImmersiveEngineering-0.7.5 and gregtech_6.01.08

Open Eye Report:
http://openeye.openmods.info/crashes/2de6017ae0a4ec1453756d6bda58a9e1

Thanks

**Comment by BluSunrize** [comment]
IE only supports GregTech 5, not 6

**Comment by g234987** [comment]
Well that explains the crash. Any idea if/when GT 6 support will be added? I assume it won't be as 1.7.10 is being superseded in favor of 1.8/1.9?

Also a note to anyone who finds this in Google. Disabling GT compat in the config will allow you to load any world affected by the crash again

Thanks for your work on the mod

**Comment by BluSunrize** [comment]
Yeah 1.8 currently doesn't feature GT or IC integration and I don't intend to apply sucha  major update to 1.7

**Comment by g234987** [comment]
Fair enough. I wouldn't expect you to if you're already working on new versions.
