### ISSUE TITLE
java.lang.IllegalArgumentException: bound must be positive

### ISSUE THREAD

**Issue by lightning02** [BluSunrize/ImmersiveEngineering#1062]
Hi Guys, 
The entire server crash when this error occur and it crash again if someone reach the same coordinates with no possibility to log-in again.
Forge in use: 1614 (1.7.10)
When the crash occurred the player was flyng around with a Flans mod plane from British Military content pack but the error seems to blame immersive in the crash report.
Also, in the thermos-54 server logs it says to "report this error to Forge", but forge doesn't seems to support 1.7.10 anymore, should I notify it anyway?
The Log: http://pastebin.com/aLPzZA8u
The Crash: http://pastebin.com/UYc1Q16m
![f620c3a4bce24374a114da1653adfeee027adb651be7e0062c pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/11884147/14605073/32d06920-0577-11e6-868d-f77ca1b7343d.png)

**Comment by mindforger** [comment]
sounds like a broken config, can you check your ore generation configs for any modifications that regard the minimum and maximum height of a certain ore to spawn? (sounds like it has been reversed or maybe modified in a typo manner) 

and for the code, there coould be a sanity check or two if i have not overseen them in the future :)

**Comment by BluSunrize** [comment]
Yeah, I'd love to see your configs, this seems to be a broken limiter. I guess sanity checks would be appropriate there, but still this might be easily fixable on the user side.

**Comment by lightning02** [comment]
Oh my...yeah, it was the config! how did you knew? :o
sorry for have been stupid :/ I really had no idea what happened
Thank you very much for your patience >_<

**Comment by BluSunrize** [comment]
It's fine ^^

**Comment by lightning02** [comment]
There is a last thing that I would may ask since I'm here, I realized that there are no ore veins related to Osmium, is there any plan to raise a compatibility with Mekanism? :o
I'm just curious, not demanding

**Comment by mindforger** [comment]
you can define veins all on your own using minetweaker
`mods.immersiveengineering.Excavator.removeMineral('Nickel');`
this is to remove existing veins
`mods.immersiveengineering.Excavator.addMineral('Redstone', 100, 0, ["oreRedstone","oreChargedCertusQuartz"] ,[90.0,10.0]);`
this is a sample that spawns a "common(100)" vein with 90% Redstone and 10% charged certus
