### ISSUE TITLE
texture bug with improved furnace

### ISSUE THREAD

**Issue by Jewler103** [BluSunrize/ImmersiveEngineering#1065]

**Comment by malte0811** [comment]
We will need a screenshot to even know what you mean by "texture bug", and probably a mod list to figure out what is going on. You can generate a mod list by pressing and holding F3 and C for 10 seconds, then releasing. That will crash MC, the crash report will contain a mod list.

**Comment by mindforger** [comment]
just by guess, you are using optifine and the IBF is rendered oddly ... optifine bug, update to the latest preview at least ... but IE does not officially support optifine :)

**Comment by BluSunrize** [comment]
No futher info supplied, issue closed.
