### ISSUE TITLE
crash on launch 

### ISSUE THREAD

**Issue by MikePotato** [BluSunrize/ImmersiveEngineering#1067]
hello.
I have added Immersive Engineering to a ftb modpack, and whenever i try to launch it it crashes.
Without the mod it works fine tho.. 
Here is the error in the log: http://pastebin.com/gBDtZRB0 
Here is the full log (if its needed): http://paste.feed-the-beast.com/view/78c6df54
if anyone knows what to do, please help me.

**Comment by malte0811** [comment]
Update forge. The version you are using was old when IE was first released if I remember correctly.

**Comment by MikePotato** [comment]
thank you, ill try that.

**Comment by BluSunrize** [comment]
Closed on the assumption of fix. Will be reopened if issue persists.
