### ISSUE TITLE
Issue building Jar

### ISSUE THREAD

**Issue by PawnedSauce** [BluSunrize/ImmersiveEngineering#107]
I have the appropriate libs downloaded but it seems to throw a fit about TileRenderIE in command prompt. Perhaps I have a wrong version of the lib?

Here is a screenshot of the output : http://i.imgur.com/dayXZEd.png

EDIT: Meanwhile I will look into the code an see what it requires

**Comment by BluSunrize** [comment]
It doesn't like the fact that the file is named "WallMount" whereas the java class is named "Wallmount" blame git for not recognizing a change of capitalization as a file change.
