### ISSUE TITLE
Railgun Crash if changed 1.7.10.jar\bbu.class

### ISSUE THREAD

**Issue by SvEgiiVEteR** [BluSunrize/ImmersiveEngineering#1070]
https://gist.github.com/25705253c718f91b0f9a51cd5728c661

**Comment by BluSunrize** [comment]
Are your running Optifine?

**Comment by SvEgiiVEteR** [comment]
@BluSunrize no, only fastcraft-1.23.jar
tried to look up the recipe and also crash.

**Comment by BluSunrize** [comment]
try it without fastcraft

**Comment by SvEgiiVEteR** [comment]
http://i.imgur.com/vLLEFf5.png Railgun in fire
ок

**Comment by BluSunrize** [comment]
You don't modify core classes. Ever. Not like that anyway.

Your modpack is way too crowded. You'll have to try and see what mod causes this because this is not necessarily an IE issue.
Remove half the mods see if it still crashes. if it doesn't it's a mod from the other half.
Keep on halving the mods till you find what does it.

**Comment by SvEgiiVEteR** [comment]
@BluSunrize ImmersiveEngineering not like I've changed \ 1.7.10.jar \ bbu.class
I sent up a log with a minimum of mods
```
 	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
		UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (INFO_GUI_3_S_NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
		UCHIJAAAA	ExtendedPotions{1.2} [Extended Potions] (0EXT_LIB_zExtendedPotions-MC1.7.10-1.2.jar) 
		UCHIJAAAA	ImmersiveEngineering{0.7.6} [Immersive Engineering] (2_7_ImmersiveEngineering-0.7.6.jar) 
		UCHIJAAAA	Waila{1.5.10} [Waila] (INFO_GUI_2_S_Waila-1.5.10_1.7.10.jar)
```
modify classes bbu.class crash occurs
return the original bbu.class
and everything is OK

bbu.class need to change that to correct fonts (as I have in the screenshot), if the file has been modified assets\minecraft\font\glyph_sizes.bin.
he changed that to Russian letters were not small.
I can not change bbu.class, I can set Optifayn, he too will solve the problem with a shift in the font side

**Comment by BluSunrize** [comment]
NO. You don't change a base Minecraft class. That's violation of license no less.Bad enough that us coremodders do it.

Do the thing with halving your mods to find out what cross-mod interaction causes it or I can't help you.

**Comment by SvEgiiVEteR** [comment]
OptiFine_1.7.10_HD_U_D4.jar solves my problem with the font and does not break the game, but he made a bad and causes problems with the current FPS and frequent crash?
For this reason, correct bbu.klass that he simply pushed FONT best solution. in the game so many problems and bugs and poor optimization ...
19 version of the game came out, and the game authors can not correct fonts. a shame

I am doing the modpack, that would be it was nice and comfortable to play and not be upset because of bad the FPS, or small print.
nor any license shall not spoil the vision or interfere with play comfortably.

Okay ... thank you "for help" will play a very bad Font ....
http://i.imgur.com/WquCvWX.png
http://i.imgur.com/Ii9RIg5.png
http://i.imgur.com/iCQSZAD.png
install OptiFine - bad idea from him more problems and FPS. :(
and edit this file, I can not bbu.class ... I should not ... but why the authors of the game do not, do not repair their bugs or problems which year.

**Comment by BluSunrize** [comment]
Okay, sorry to say mate. But your English is shit. I can barely understand what you're trying to get across. I told you twice how you should deal with the error and how to detect what mod interaction is causing it.

I'm going to close this issue, no point to it.

**Comment by SvEgiiVEteR** [comment]
consent to my bad English))
no mode that causes the error.

error is caused by editing bbu.class
but I can not edit it, I need edit, otherwise my fonts are very bad as in the screenshot above.
OptiFine I also can not install him more trouble and no good, but hi repairs my fonts

**Comment by laz2727** [comment]
Впервые слышу про проблемы с шрифтами.

2016-04-29 16:37 GMT+05:00 SvEgiiVEteR <notifications@github.com>:

**Comment by mindforger** [comment]
@BluSunrize what he means to describe is, he needs to edit the file because the font is bad when using russian language

and for whatever reason it is crashing since the last update .. nothing you can fix easily i think

@SvEgiiVEteR keep running your minecraft WITH otpifine, but update to the very very very latest preview snapshot, optifine had an update dealing with a lot of errors lately

**Comment by BluSunrize** [comment]
Well that's his friggin problem then!
If he's running a modified baseclass, I refuse to help. That's license violation. If your fonts look shite, I'm sorry, but there's nothing to be done about it, except maybe play the game in English.

**Comment by SvEgiiVEteR** [comment]
@mindforger thanks that explained my bad english.
optifine with a lot of problems ...
@BluSunrize Of course I can use English, but the game is declared the support of the Russian language. I can get the Russian language and it should not cause any problems, but they are!
and me and others to have to solve them by correcting the files bbu.klass, glyph_sizes.bin. because the developers of this game do not do.

" If your fonts look shite, I'm sorry, "
there is not your fault))

**Comment by Bogdan-G** [comment]
ASM conflict problems
