### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 36 	at net.minecraft.potion.Potion.<init>(Potion.java:68)

### ISSUE THREAD

**Issue by SaMoSe12** [BluSunrize/ImmersiveEngineering#1071]
[crash-2016-04-30_02.10.34-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/243494/crash-2016-04-30_02.10.34-client.txt)

I hope this helps. 
I can't get past the phase 3 of the starting process.

**Comment by Joshwoo69** [comment]
try version 0.7.5?

**Comment by malte0811** [comment]
@Joshwoo69 The changes I made should not affect this, they only affect how the result is calculated, not the result itself.
@SaMoSe12 try deleting the "potions" section in ImmersiveEngineering.cfg.

**Comment by TheJulianJES** [comment]
Same problem, fresh install with only Immersive Engineering.
@malte0811 workaround also didn't work for me.

**Comment by TheJulianJES** [comment]
I generated my config with version 0.7.5, updating to 0.7.6 works now.
This generated:
´´´
potions {
    # The potion ID for the Conductive potion effect
    I:Conductive=26

    # The potion ID for the Flammable potion effect
    I:Flammable=24

    # The potion ID for the Slippery potion effect
    I:Slippery=25

    # The potion ID for the Sticky potion effect
    I:Sticky=27
}
´´´

**Comment by malte0811** [comment]
Ok, it was my fault, mainly because I forgot to replace `==` with `!=` in one place.

**Comment by Kenkron** [comment]
For people from the future (like me).  If you had this problem in 0.7.6, upgraded to 0.7.7, and still have this problem, try deleting the old config file.

**Comment by gnif** [comment]
This issue is caused by a bug in the way the potionType array is extended, this commit fixes this:

21986b55fe9998b7d9b86df2e5cb7d985eca7fd1
