### ISSUE TITLE
Can not form the "Arc Furnace"

### ISSUE THREAD

**Issue by TheJulianJES** [BluSunrize/ImmersiveEngineering#1072]
So my problem is simple, the Arc Furnace simply won't form when clicking the cauldron with the "Engineer's Hammer". I have tried this multiple times, also rotated it in different directions. So I created a fresh instance with only IE 0.7.6 after running into issue #1071. So using the config from 0.7.5 fixed #1071. I also used the latest Forge (forge:1.7.10-10.13.4.1614-1.7.10:universal) but I couldn't form the Arc Furnace. So I have some screenshots now: http://imgur.com/a/yY3Zl
I hope somebody can help me ;) Also sorry for my bad English, I'm also German.
This is also a issue in singleplayer and multiplayer.

**Comment by laz2727** [comment]
Rightclick ALL the blocks. It's pretty hard to guess the right location of
most multiblocks of IE.

2016-04-30 16:43 GMT+05:00 TheJulianJES <notifications@github.com>:

**Comment by TheJulianJES** [comment]
Never mind.

**Comment by BluSunrize** [comment]
@laz2727 bullshit. It's guaranteed to be the cauldron on the arc furnace.

**Comment by Joshwoo69** [comment]
RTFM? the says on that particular block..

**Comment by laz2727** [comment]
I know, but the exact block is not documented.

2016-05-01 4:55 GMT+05:00 Josh <notifications@github.com>:

**Comment by mallrat208** [comment]
I call shenanigans 

`ie.manual.entry.arcfurnace2=To form the structure, assemble it as shown on the first page, then click the cauldron with an Engineer's Hammer.<br><br>Energy is input through the three connectors at the back, and supplying the control panel at the front with a redstone signal will turn off the machine. Right-clicking the panel, 'bucket' or vat will open the interface.`

That's lifted from en_US.lang

**Comment by laz2727** [comment]
Cauldron is what, 27 blocks big?

2016-05-01 13:12 GMT+05:00 Andrew W. <notifications@github.com>:

**Comment by mindforger** [comment]
http://minecraft.gamepedia.com/Cauldron 
gosh ...

**Comment by BluSunrize** [comment]
No, absolutely correct here Mind.
@laz2727 if you are unaware of vanilla Minecraft blocks, that's not my fault, is it? xD
