### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by DumkinDV** [BluSunrize/ImmersiveEngineering#1074]
Please help.
Crash.
http://pastebin.com/bUFbNScd

**Comment by malte0811** [comment]
#1071, my fix in #1073 will hopefully be merged soon.
Until then you can try this: In your minecraft folder there is a folder called `config`. In that folder there is a file called `ImmersiveEngineering.cfg`. Open that file in a text editor of your choice (for example Wordpad or Notepad++ on Windows) and scroll down until you see a line saying `potions {`. Replace this lines and the following lines (Up to a line just saying `}`) with the stuff below:

> potions {
    # The potion ID for the Conductive potion effect
    I:Conductive=26
    # The potion ID for the Flammable potion effect
    I:Flammable=24
    # The potion ID for the Slippery potion effect
    I:Slippery=25
    # The potion ID for the Sticky potion effect
    I:Sticky=27
}

**Comment by DumkinDV** [comment]
Thanks you!

**Comment by BluSunrize** [comment]
fixed with v0.7.7
