### ISSUE TITLE
0.7.6 crash

### ISSUE THREAD

**Issue by Auzze** [BluSunrize/ImmersiveEngineering#1075]
hey,
Working on a new pak and was going to add IMM but seam to be crashing.

Crash Report
http://pastebin.com/W9Brifhk

Not 100% sure why, it's the only mod in for testing

**Comment by XFactHD** [comment]
There is a pending PR that fixes this, you will have to wait for it to be merged. In the meantime you can use the workaround mentioned in #1074.

**Comment by Auzze** [comment]
Thanks..


On Sun, May 1, 2016 at 11:00 AM, XFactHD <notifications@github.com> wrote:

> There is a pending PR that fixes this, you will have to wait for it to be
> merged. In the meantime you can use the workaround mentioned in #1074
> <https://github.com/BluSunrize/ImmersiveEngineering/issues/1074>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/BluSunrize/ImmersiveEngineering/issues/1075#issuecomment-216005945>
>



-- 
Stuart (Auzze) Mitchell
Australia

**Comment by BluSunrize** [comment]
fixed with v0.7.7
