### ISSUE TITLE
Suggestion: Conveyor Belts should require power

### ISSUE THREAD

**Issue by SkylordJoel** [BluSunrize/ImmersiveEngineering#1077]
What the title says. It feels a bit hacky without using any power.

**Comment by escman1999** [comment]
would the connectors even render properly when connected?

**Comment by BluSunrize** [comment]
Feel free to write your own conveyor mod for that? I prefer mine powerless =P

**Comment by James-T-Oudvoure** [comment]
What a dumb idea.

**Comment by Joshwoo69** [comment]
@James : play factorio then... all belts are unpowered.

**Comment by laz2727** [comment]
Slow item transfer has always been free.

**Comment by Barhandar** [comment]
It would bog down conveyors without meaningfully contributing to gameplay - same reason why Factorio conveyors are free. Especially since IE has actual items on them that can despawn, not like Factorio (never despawn) or Magneticraft (no entities, items are stored in conveyor belt TE).

**Comment by BluSunrize** [comment]
Items on IE conveyors don't despawn. They only will when they are colliding with a chest and can't be input into it. That's when despawn is allowed to prevent backed up chests killing servers.

**Comment by BluSunrize** [comment]
Also, topic closed, sicne it's clearly not happening.
