### ISSUE TITLE
[Bug] Uranium Mineral Deposit not outputting

### ISSUE THREAD

**Issue by Skyqula** [BluSunrize/ImmersiveEngineering#108]
Using Immersive Enginering 0.2.4 and Big Reactors 0.4.3A there seems to be an issue with uranium deposits. The Engineers Manual seems to indicate that it recognises uranium (only 35% lead isntead of 100% without a uranium mod). Now I am aware that BR does not add uranium ore but instead yellorium ore that is oredicted with uranium.

http://i.imgur.com/HWUufN0.png

Yellorium blocks and blutonium blocks work fine with the Thermoelectric generator.

**Comment by BluSunrize** [comment]
I've made a possible fix for this
please reopen the issue if this bug persists in the upcoming versions of IE.

**Comment by Skyqula** [comment]
The issue is still there using version 0.3.1. http://i.imgur.com/tYtJtOy.png

Just to be sure, the problem is that the uranium vein isnt detecting yellorium ore to generate.

I would suggest making mineral deposits configurable, the spawn chance of a deposit, the rarity of deposit types, wich block goes in each deposit and the weight of that block. Ideally with the ability to add custom deposits. That removes the dependancy of autodetecting and gives modpack makers alot of freedom. Like adding stones as a possible output.

I love the excavator btw. I love the concept and I love the current configs.

**Comment by BluSunrize** [comment]
it goes by oredict. And Yellorium is registered as Uranium. Weird. I'll look into it.

**Comment by BluSunrize** [comment]
reopen this if the bug persists in the upcoming 0.3.2

**Comment by Skyqula** [comment]
The bug still exists with 0.3.2. Only this time it says the deposit is 100% Lead (http://i.imgur.com/9Lg1hld.png), still not outputting annything. Tried rebuilding the multiblock(s) and didnt fix it either.

**Comment by BluSunrize** [comment]
Are you sure that your BigReactors is configured so that Yellorium is registered as Uranium?

**Comment by Skyqula** [comment]
Yes, just double checked. Yellorium (uranium) blocks and Blutonium (Plutonium) blocks work with the thermo electric generator, so that works.

**Comment by BluSunrize** [comment]
That is not a valid check. My ThermoelecticGen can use Uranium /and/ Yellorium. Use Minetweaker to look up what an Item is registered as.

**Comment by Skyqula** [comment]
Ah, found the mistake. It registers all the dusts, ingots and blocks, yet not the ore. Still leaves the bug where there is no output at all incase of no uranium ore.

**Comment by BluSunrize** [comment]
that is because Minetweaker works after IE when it comes to dealing with the dictionary
I'll see if I can add Yellorium to the excavators list.
In the meantime, I do believe BigReactors has a config for enabling Uranium oredicting.

**Comment by Skyqula** [comment]
Yes, that config is enabled. And works for everything but the ore ;)

**Comment by BluSunrize** [comment]
Ah. I see. Well the Minerals will have a "replacement" system in future versions, which checks for another ore if the original one can't be found =)
