### ISSUE TITLE
[1.8.9] Wire connectors doesn't transfer energy to Capacitors from EnderIO

### ISSUE THREAD

**Issue by Eufranio** [BluSunrize/ImmersiveEngineering#1081]
Nothing happen when connecting wire connector/relay in capacitor banks from EnderIO, then link them.
http://prntscr.com/azhyuf
http://prntscr.com/azhz0w

**Comment by laz2727** [comment]
Try setting up the input-output sides.

**Comment by AlterAkima** [comment]
We already did.

**Comment by malte0811** [comment]
I am pretty sure that I know what is causing this, I will fix it tomorrow.

**Comment by Eufranio** [comment]
Thanks :grinning:

**Comment by BluSunrize** [comment]
Fixed in the latest release
