### ISSUE TITLE
Post dupe bug (On latest version of IE that is on Curse forge)

### ISSUE THREAD

**Issue by Insufficient-Charge** [BluSunrize/ImmersiveEngineering#1082]
I've not tested this with the aluminum and steel posts, but at least for the wooden ones, I was able to dupe. This is a custom pack I threw together on Curse Forge, since I saw that IE finally came out on there. Steps to reproduce:

1. Place wooden post down.
2. Add an extension at the top of the post.
3. Break the EXTENSION.
4. Gain a new wooden post from that broken extension, while the original post still stands.

**Comment by oitsjustjose** [comment]
Yup - having the same issue. Not game-breaking with wooden posts ;D

**Comment by BluSunrize** [comment]
Fixed in the latest release
