### ISSUE TITLE
No hemp rope coil connectors?

### ISSUE THREAD

**Issue by Insufficient-Charge** [BluSunrize/ImmersiveEngineering#1083]
I really liked using hemp rope as decoration (it was actualy at the same time I found the other bug) but didn't it have specific hemp rope wire connectors before? The coil itself is craftable, and in the game, but it can't connect to wire connectors that usually transmit IF. Any reason why the connectors are not ingame, or was it an accident?

**Comment by AlterAkima** [comment]
You are looking for the Structural Cable Connector. http://i.imgur.com/e36AGuD.png

**Comment by Insufficient-Charge** [comment]
Dang, that stuffs expensive on steel...alright, thanks!
