### ISSUE TITLE
Lanterns not giving light

### ISSUE THREAD

**Issue by Insufficient-Charge** [BluSunrize/ImmersiveEngineering#1084]
As the title says, they are not giving light. I can't remember if they need power or not, but if they do, then ignore this =P but here is a snapshot
![2016-05-02_15 23 58](https://cloud.githubusercontent.com/assets/13188566/14966881/33cc7324-107a-11e6-9470-0be9f5f314bf.png)

**Comment by mindforger** [comment]
http://ftb.gamepedia.com/Powered_Lantern

and i am very sure it is clearly documented in the manual

**Comment by bookerthegeek** [comment]
Yes, but the lantern in the picture is not a powered lantern. It is a normal lantern that requires no power.

**Comment by bookerthegeek** [comment]
http://ftb.gamepedia.com/Lantern_(Immersive_Engineering) is the one in the picture.

**Comment by BluSunrize** [comment]
Yeah, TileEntityLantern is currently not implementing ILightValue. Will fix.
Once again, IE 1.8.9 is very much incomplete, so stuff like this is bound to happen.

**Comment by BluSunrize** [comment]
Fixed in the latest release
