### ISSUE TITLE
Wierd Waterwheels? 

### ISSUE THREAD

**Issue by Insufficient-Charge** [BluSunrize/ImmersiveEngineering#1085]
Okay, I've been playing with IE for one day, I've found 4 major to semi-major issues. This is a big major... It's probably aready been reported.
I placed down 2 "sets" of water wheels. Basicly 1 kinetic dynamo with 3 water wheels on them each.
I had to move the second one. Once I started breaking the water wheels, the ones slightly to the right (if you're facing the wheels) just disappeared. Poof. Gone.
Steps to reproduce:
Place 2 kinetic dynamos, 4 blocks apart. (That's what I had.)
Attach 3 water wheels to each dynamo.
Start breaking the wheels and see if some of them disappeared.

Don't know if the axe I used matters, or that I was flying with a thaumostatic harness. The axe I used was a peridot axe from the Silent's gems mod.

**Comment by mindforger** [comment]
i remember this issue, something was off in the rendering when you stand close to the wheel and th center block leaves your view it sometimes visually disappeared

please clarify: 
-either you can't see it under certain angles of view? (screenshot of your view please)
-or the waterwheel actually disappears completely, independend of view angle
-or completeley vanishes into air (no breakable block anymore)

**Comment by Insufficient-Charge** [comment]
Completely vanishes into thin air...will take a snapshot when I get the chance. All 3 wheels disappear.

**Comment by BluSunrize** [comment]
Fixed in the latest release
