### ISSUE TITLE
Server crashes trying to profile recipes for arc furnace recycling [1.8.9]

### ISSUE THREAD

**Issue by F4ndroid** [BluSunrize/ImmersiveEngineering#1086]
http://pastebin.com/DfvcEp2H
Only happens when running on a server, singleplayer runs fine with IE. I can link to the scripts if necessary.

**Comment by mindforger** [comment]
also check your other mod configs to be in sync with the server, sounds like a broken recipe exchange (seen in other mod)

**Comment by BluSunrize** [comment]
I have not the slightest idea what's happening there O_o
First time I've ever seen a non-descript error. @malte0811, any ideas?

**Comment by malte0811** [comment]
No idea. It gets even weirder than the non-descript error: The line it claims to be crashing on seems to be empty apart from a closed curly bracket (`}`). Did you do anything to the code between commiting and building (e.g. organise imports)?

**Comment by BluSunrize** [comment]
Nope. That code hasn't been touched in a good 1 1/2 weeks.

**Comment by mindforger** [comment]
did you notice the  `ImmersiveEngineering{${version}} [Immersive Engineering] (ImmersiveEngineering-0.8-23.jar) ` looks odd to me, maybe separat issue?

**Comment by malte0811** [comment]
The crashes in both #1078 and this don't make any amount of sense. The lines for both crashes contain nothing but curly brackets (`{` and `}`). I just ran the IE version on curseforge through a decompiler, the lines are actually empty (except for brackets) in the decompiled code. Looking at the bytecode of the curseforge version in eclipse does not help either, the line in this crash is just a `goto` in bytecode and the one in #1078 does not even exist in bytecode. And to make thing even worse, the method this crash is happening in can only throw a `NullPointerException` if `facing`, `TileEntity.getPos()` or `IBlockstate.getBlock()` are `null` and none of them should EVER be `null`,
