### ISSUE TITLE
Gunpowder barrel

### ISSUE THREAD

**Issue by AkaruC** [BluSunrize/ImmersiveEngineering#1088]
What I've shown you on discord: pretty much not working.
Do not explode with any way of redstone or even a good old flint and steel
https://gyazo.com/bd7feffb11b65c2287a6f17b5623df6f
Also notice the 0 levers in creative mode

**Comment by malte0811** [comment]
@BluSunrize https://gist.github.com/malte0811/12a957cfd54b36bfd19d8a3a1cfe47c1
That exception is throw when you try to light the barrel.

**Comment by BluSunrize** [comment]
I already know that one malte, and fixed it. That was reported even before Akaru made this one =P

**Comment by BluSunrize** [comment]
I can't replicate the failure to ignite btw. Redstone works for me and so does flint and steel

**Comment by BluSunrize** [comment]
Fixed in the latest release
