### ISSUE TITLE
Coke Oven cannot connect to item pipes/hoppers

### ISSUE THREAD

**Issue by CJL48** [BluSunrize/ImmersiveEngineering#1089]
In version 0.8-23, the coke oven multiblock does not connect to item pipes placed next to it, and hoppers next to it do not interact with the internal inventory. Could this be an unintended side effect of the blast furnace change?
Reproduce: Put any item transport block next to oven, either for input or output. Watch nothing happen.
Versions:
IE 0.8-23
Minecraft 1.8.9
Forge 11.15.1.1764

**Comment by BluSunrize** [comment]
Fixed in the latest release
