### ISSUE TITLE
[1.8.9] Issue with Arc furnace rendering

### ISSUE THREAD

**Issue by dylanwi** [BluSunrize/ImmersiveEngineering#1091]
Immersive engineering and JEI are the only mods I have installed and this is what happened when I constructed the Arc furnace.
http://imgur.com/CWXxJkv

But then I rebuilt it and it rendered like normal
http://imgur.com/5mVSo50

**Comment by BluSunrize** [comment]
yaeh. Clientside rendering issue. reloging also fixes the problem.
