### ISSUE TITLE
Suggestion:  Water wheels output same RF touching any amount of flowing water. 

### ISSUE THREAD

**Issue by delet3r** [BluSunrize/ImmersiveEngineering#1092]
Apologies if this is not the right place for suggestions, I saw one about adding Oil to the mod and no one seemed to mind...

Any player like myself that loves the watermills in a build also gets shafted by not getting full power out of them.  I build them into a stream or some other semi realistic build, and get 25 rf/t from three wheels, but then my neighbor makes a tiny box with a setup in it, with source blocks literally on top of the wheel, or in spots that look like it would force the wheel to go backwards, and he gets 80ish.  So the best setups, are, unfortunately, the worst looking.  Doesnt seem to fit for the best looking mod.

So my suggestion would be to jsut have the wheels output the same no matter how much flowing water they touched.  Then people building them into a waterfall of some sort and trying for a nice looking build get full power out of them.

**Comment by Insufficient-Charge** [comment]
Naturally, in the real world, water comes in from the top for water wheels, or from a waterfall. I would try that :D it might make it look a little nicer and give a bit more power. Although, the going backwards-ish ones are kinda odd.

**Comment by mindforger** [comment]
you can build them fancy and have full power, but you require forge multiplart blocks for best experience
let me build a quick demo and post pic .. only if @BluSunrize allows this, because it would be some sort of spoiler :P

**Comment by BluSunrize** [comment]
No. Water wheels will keep their power generation relative to the flow vectors of the water. That is game design. If people stick them into ugly boxes, they're uncreative and don't deserve better =P

**Comment by delet3r** [comment]
Just so you know how people are setting these up, its not the box that is what I was talking aobut, its this:

http://i.imgur.com/dhIn9Lq.png

There is no way, in or out of a box, to get that amount of power out of them, and make that look normal.   There is water around the entire wheel.  

Anyway thanks for your time,

**Comment by BluSunrize** [comment]
I don't give a shit.
If that is what Infinity forces players to do, that's there problem, not mine. I encourage artistic builds even if that means sacrificing effiency. I love Minecraft for its sandbox and creativity in building, not for the "perfect machine setup". That stuff is boring to me. Over-optimization leads to stagnation, and stagnation is something I dislike.

**Comment by delet3r** [comment]
"If that is what Infinity forces players to do, that's there problem, not mine. I encourage artistic builds even if that means sacrificing effiency. "

I think you are making assumptions or I didnt explain myself correctly.   None of this is about Infinity, thats just the tag that the person who made the image put on it.  9 out of 10 builds I see use water wheels exactly like that, and i do not play infinity.  Almost EVERYONE makes water wheels the way I showed you.  

"if that means sacrificing efficiency".  Well thats my point, anyone who wants an artistic build sacrifices efficiency, some people like a bit of both.  If its all about being artistic then why even connect them to a kinetic generator, why not have them connect to a big metal rod that moves some gears which turn a big stone, and we can put wheat in it and get flour as an output.  thats much more artistic than a Kinetic Generator block making rf, right?

So i assumed, as most people would, that the mod was supposed to be a _blend _of artistic build, along with 'tech', balance, etc.  

As for over optimization... dude IE has many 'over optimized' things to it, why do you think everyone uses it?  Do you not realize, if MOST people are using the water wheels like I showed you, no one gives a shit about how they look, they want the most power for their input.  The cost is low, for a passive generator that never breaks down, and runs night and day, etc. Water wheels are like the msot over optimized thing EVER!   Sheesh.  You seem to be a fan of redpower, notice Elorram made her windmills break down over time?  Vaskii made passive flowers disappear?  Vaskii was the one who posted on reddit about 'over optimization' being a bad thing for mods.  So you create the most optimized passive generator in the entire community, then say you want to sacrifice efficiency?  Makes no sense. 

Just yesterday, people on the server I am on said 'just make biodiesel, it's the simplest and easiest way to make ethanol from crops'.  Biodiesel IS overoptimized, compared to even MFR ethanol!  Its so simple, its painful. 

Oh well do what you want, its your mod.

**Comment by BluSunrize** [comment]
I try to not balance against other mods as much as I can. IE is its own thing. If you want to build ugly as fuck waterwheel cells? So be it. Your creative decision.
Topic done.
