### ISSUE TITLE
(1.8.9) (IE 0.8-23) Concrete and Hempcrete slabs no texture.

### ISSUE THREAD

**Issue by Insufficient-Charge** [BluSunrize/ImmersiveEngineering#1093]
once again, playing with the very nice looking blocks from IE for decor, I have found a bug. But, of course, it is beta, so it's expected :D.
![2016-05-04_14 35 11](https://cloud.githubusercontent.com/assets/13188566/15026804/dc8c86b6-1205-11e6-96a3-d89cdcad66a8.png)
![2016-05-04_14 35 14](https://cloud.githubusercontent.com/assets/13188566/15026807/df689fa0-1205-11e6-9939-24224855d029.png)

**Comment by BluSunrize** [comment]
Fixed in the latest release
