### ISSUE TITLE
Thermoelectric Generator Crash

### ISSUE THREAD

**Issue by Plurp13** [BluSunrize/ImmersiveEngineering#1095]
I placed the generator next to a lava source block and crashed so hard I can't even open the world now.

http://pastebin.com/2pDiyxLF There's the crash, help please.

**Comment by malte0811** [comment]
@BluSunrize The only explanation for this that I can come up with is that some mod is creating an `IBlockState` that does not have a block for a block that is not air. And that would be quite weird in my opinion, even though it doesn't specifically say that `getBlock` can't be null.
@Plurp13 What other blocks are surrounding the generator? If you don't remember and @BluSunrize permits it I will upload an version of IE in which the thermoelectric generator does not work so you can check.

**Comment by BluSunrize** [comment]
Yeah, I figured as much. Include it in your PR if you don't mind, I wanna build today.

**Comment by Plurp13** [comment]
Wait so you don't need to know what's around it? You figured it out? I think it was just surrounded by stone and air anyway.

**Comment by malte0811** [comment]
@BluSunrize I have an unpushed commit that fixes about all issues that have been reported on 1.8, I'll add one small thing and then push
@Plurp13 You probably had flowing lava on one side. I found out by accident, I made a mess of my testing area by spilling a bucket of water, replaced the water source with a thermoelectric generator and crashed.

**Comment by Plurp13** [comment]
Aha! Yes I placed the lava first and then the generator on to what had started to flow. Somehow I suspected if I'd placed the lava second I might not have had a problem haha. Thanks for helping so fast! ^.^

**Comment by BluSunrize** [comment]
Fixed in the latest release
