### ISSUE TITLE
[1.8.9] StackOverflowError with Fluid Pipe and Sheetmetal Tank

### ISSUE THREAD

**Issue by XFactHD** [BluSunrize/ImmersiveEngineering#1096]
When I place a fluid pipe on a sheetmetal tank, MC crashes with a StackOverflow: http://pastebin.com/PeHeUAcY. The sheetmetal tank was built the intended way and **not** by using the finished multiblock found in the creative tab.

Forge version: 1.8.9-11.15.1.1808
IE version: 0.8-23

**Comment by CJL48** [comment]
I've experienced this crash in 0.8-23 as well, trying to use the tank for bio-diesel storage.
I've done some more testing: connecting with enderio and buildcraft fluid pipes does not cause a crash, and other containers, including metal barrels and enderio tanks connect to IE pipes just fine. It is only connecting IE fluid pipes to the sheetmetal tank that causes a crash.

**Comment by BluSunrize** [comment]
Fixed in the latest release
