### ISSUE TITLE
[Suggestion] Rotary plant cutter

### ISSUE THREAD

**Issue by SkylordJoel** [BluSunrize/ImmersiveEngineering#1098]
It would be an animated model of a rotating blade or something which would cut wood within it's radius. It could either cut the entire tree by destroying one block (like in real life), or it could move up and down to cut at different heights. It would obviously require power. The wood would drop below the trees on the ground, as opposed to magically teleporting into the cutter.
EDIT: it should also have a different blade or something to cut down normal plants, like sugar cane, hemp, etc.

**Comment by mindforger** [comment]
yeah UT99 style :D or like Quake XD scnr

**Comment by Insufficient-Charge** [comment]
I like the idea :D but IE doesn't have any machine *yet* that actually has moving blocks, just moving animations (which I so totally love). Or the saw blade of it could be an entity.
On another note, the "generation" that IE is made in does not have much with sensors/things like that, so the cutter magically  knowing that a sapling is no longer a tree is kinda odd.

**Comment by SkylordJoel** [comment]
It would be a moving entity that checks for blocks and cuts them if they exist. It wouldn't know when a sapling is a tree - it would just keep spinning (and using power) until it cuts logs.

**Comment by elkillo** [comment]
maybe somthing like a Sawmill looking machine that has a massive belt saw, would fit the theme at the very least.

**Comment by mindforger** [comment]
nah, he want's to automatically and animated chop down trees

**Comment by laz2727** [comment]
youtube.com/watch?v=CpdZyJ0Y1jE

2016-05-18 10:57 GMT+05:00 mindforger <notifications@github.com>:

**Comment by mindforger** [comment]
yeah eh no i think something more portable ... moving machines is kind of ... tricky :P

**Comment by elkillo** [comment]
Hay a chainsaw powered by bio-d would be freaking awesome and the drill would have a friend :P
