### ISSUE TITLE
[1.8.9] Mining Drill Crash

### ISSUE THREAD

**Issue by sueZtheGreat** [BluSunrize/ImmersiveEngineering#1099]
The game crashed with this crash report: [http://pastebin.com/wi6h9BbJ](url)

I looked at stone while having a mining drill with drill head selected.

I've tested it a few times, it also crashes when looking at furnaces.

This first happened in LAN mode, but it also happens in singleplayer.

The only mod installed is IE.

**Comment by malte0811** [comment]
First of all: very nice bug report!
I have fixed this yesterday, but have forgotten to push the commit. For people trying to replicate this bug: one of the blocks that would be broken when breaking the currently focussed block with the drill has to have different blockstates than the focussed one.

**Comment by BluSunrize** [comment]
I'll leave the fixing of this to your upcoming PR then.

**Comment by sueZtheGreat** [comment]
Thank you for the quick response! I'll get back to testing!

**Comment by BluSunrize** [comment]
I'll reopen this, because I almsot forgot that no PR to fix this had been made.

**Comment by sueZtheGreat** [comment]
Oh, sorry about that.
