### ISSUE TITLE
CrashReport

### ISSUE THREAD

**Issue by EndermanParty** [BluSunrize/ImmersiveEngineering#110]
I placed the kinetic dynamo's with watermills, placed the lv energy cables, then continued to place copper wire. Once i placed copper wire from one Lv conduit to the next I proceeded to crash. 
Also - I'm using 2.4 From Curseforge, However as I type this a new build has been released. Ill check if it has been fixed and either add or remove this post.
Here's the log:
http://pastebin.com/1NWLPzkA

**Comment by BluSunrize** [comment]
Closed until relevant again

**Comment by EndermanParty** [comment]
yeah sorry, it was fixed in 3.0
