### ISSUE TITLE
Pipe Rendering Error

### ISSUE THREAD

**Issue by CJL48** [BluSunrize/ImmersiveEngineering#1102]
Fluid pipes render as if all 6 sides are connected to another block, regardless of actual configuration.

Version:
MC 1.8.9
Forge 11.15.1.1764
IE 0.8-24
Image:
![2016-05-06_19 39 28](https://cloud.githubusercontent.com/assets/8433790/15088500/f49bc316-13c2-11e6-87ee-7f42be7918da.png)

**Comment by BluSunrize** [comment]
fixed for upcoming release
