### ISSUE TITLE
No crafting recipe for coke dust

### ISSUE THREAD

**Issue by CJL48** [BluSunrize/ImmersiveEngineering#1103]
In both 0.8-23 and 0.8-24, the grinder recipe for coke dust is missing an input value (should be coal coke), making it impossible to produce coke dust, as dropping coal coke into the grinder produces nothing.
This makes it impossible to use the arc furnace for anything, especially producing steel, and the arc furnace requires electrodes, which are made out of graphite.
Version:
MC 1.8.9
Forge 11.15.1.1764
IE 0.8-23/24

**Comment by BluSunrize** [comment]
fixed for upcoming release
