### ISSUE TITLE
[1.8.9]Arc Furnace can't place the Lever

### ISSUE THREAD

**Issue by LYDfalse** [BluSunrize/ImmersiveEngineering#1104]
Arc Furnace can't place the Lever

**Comment by Joshwoo69** [comment]
pics? no logs? there WAS a line to ask you to put a log...

**Comment by malte0811** [comment]
If I didn't miss anything this bug should be quite trivial to fix, just some lines that need to be uncommented.
Logs aren't required, but a more precise description of the bug would have been nice. Something along the lines of "In the latest 1.8.9 version of IE (0.8-24) it is impossible to place a lever on the controll panel of the arc furnace."

**Comment by XFactHD** [comment]
@Joshwoo69 He is trying to place a lever on the redstone control block of the arc furnace, what kind of log output should he be getting?

**Comment by BluSunrize** [comment]
yeah, no logs, but a proper phrasing and some netiquette never hurt nobody.

**Comment by BluSunrize** [comment]
Dealt with.
