### ISSUE TITLE
[1.8.9] Crash with BuildCraft 7.2.6

### ISSUE THREAD

**Issue by miuirussia** [BluSunrize/ImmersiveEngineering#1106]
When I connected BC pipe to Improved Blast Furnace and turned it to the left (see picture in attachment), it crashed with this:
http://pastebin.com/90a9Fbsf

![location](https://cloud.githubusercontent.com/assets/1270028/15094054/455ba48c-14aa-11e6-8bef-b321fc57692d.png)

I hope that everything is fine explained

**Comment by AEnterprise** [comment]
this is buildcraft crashing but the cause lies within IE, looking at the code (https://github.com/BuildCraft/BuildCraft/blob/7.2.x/common/buildcraft/transport/PipeTransportItems.java#L502) IE is returning true when checking for capability but it returns null when actually fetching the capability

**Comment by BluSunrize** [comment]
*grmph*
Buildcraft should still nullcheck that >_>

I'll fix it.

**Comment by AEnterprise** [comment]
then what's the point of asking a TE if it has the capability? if a TE claims to have the capability it should return it, returning null is breaking the methods contract

**Comment by BluSunrize** [comment]
Yes. I am aware that I fucked up. I personally try to nullcheck everything I can though. Because you never know what idiot developer returns null where they shouldn't. *cough*

**Comment by AEnterprise** [comment]
most mod's don't have complex TE's where in some cases they have the capability in others they don't, so it should be fine

**Comment by asiekierka** [comment]
@BluSunrize And we don't do double null checks because if we did such bugs would not be caught. (Also, less code executed on the CPU is always nice.)

**Comment by BluSunrize** [comment]
I was kidding, for crying out loud xD
I know I am a derp

**Comment by AEnterprise** [comment]
sorry, kinda hard to know when someone is kidding and when not :)

**Comment by BluSunrize** [comment]
I'm sarcastic most of the time, don't worry, you'll get used to it. =P
