### ISSUE TITLE
[Suggestion] Steel Tools

### ISSUE THREAD

**Issue by CptPeterPL** [BluSunrize/ImmersiveEngineering#1107]
A simple idea - Steel tools. Stronger than iron, less efficient than diamond but more durable

**Comment by James-T-Oudvoure** [comment]
I support this idea. Immersive Engineering is probably the only steel adding mod without steel tools. Besides, it makes no sense to be operating big 1920-30s era technology and yet still be useing iron tools.

**Comment by James-T-Oudvoure** [comment]
I support this idea. Immersive Engineering is probably the only steel adding mod without steel tools. Besides, it makes no sense to be operating big 1920-30s era technology and yet still be using iron tools.
