### ISSUE TITLE
(Suggestion/Issue) Lantern Prioritize

### ISSUE THREAD

**Issue by porteriscool** [BluSunrize/ImmersiveEngineering#111]
This is just a suggestion, but could also be considered an issue, maybe you could prioritize the lanterns to stay connected to either wall mounts or prioritize lanterns to stay connected to the first block they connect to, or even stay connected to blocks directly from IE because when you place something like a wall mount down, then the lantern, the two blocks connect, and then if you place a block underneath, it will connect to the block that was just placed possibly due to a block/ chunk update. If this could be possible, great, if not, no worries.
![2015-06-26_13 44 48](https://cloud.githubusercontent.com/assets/12450943/8383633/8f719d78-1c09-11e5-9584-09605f0b9d7d.png)
![2015-06-26_13 44 54](https://cloud.githubusercontent.com/assets/12450943/8383634/90b6ef9e-1c09-11e5-8e0b-f3fd5bab2ab5.png)

**Comment by BluSunrize** [comment]
The lantern priorizes the block beneath it, because tehy were originally designed to go on wooden poles. Not much to be done until I actually rewrite them at some point in the future.
