### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Fensus** [BluSunrize/ImmersiveEngineering#1110]
I'm trying to add IE to an existing modpack, but it won't work.
Sorry if the solution is right infront of me, im not good with this stuff.

Have been trying to do the same as in #1074 , but haven't worked for me.
Have also tried both 0.7.5 and 0.7.6 versions, my Java should be up to date, updated right before crash.

here's crash report:

http://pastebin.com/4Cj1CyaZ

**Comment by malte0811** [comment]
Update forge.

**Comment by Fensus** [comment]
did originally try this, apparantly I failed. Thanks for the help and quick response :)
