### ISSUE TITLE
[1.8.9] Wooden Post rendering glitch

### ISSUE THREAD

**Issue by Xiaminou** [BluSunrize/ImmersiveEngineering#1115]
This wooden post is going crazy:
![2016-05-10_00 41 16](https://cloud.githubusercontent.com/assets/8670392/15130487/fb00261a-1648-11e6-9049-a4a522146937.png)
![2016-05-10_00 47 30](https://cloud.githubusercontent.com/assets/8670392/15130488/fb037a18-1648-11e6-9e4e-468252b40d17.png)

This is somehow linked to a bug I encountered with Industrialcraft (look at the machines behind) as the glitch happens at the same time.
Here it is: http://bt.industrial-craft.net/view.php?id=1857

**Comment by BluSunrize** [comment]
You know what would help? Tellign us what version you are running. Also, other mods, etc.

**Comment by Xiaminou** [comment]
http://pastebin.com/XCmZpMi0

**Comment by BluSunrize** [comment]
did that render glitch by any chance fix itself on relogging?

**Comment by Xiaminou** [comment]
Yes, as said on the Industrialcraft bug report, it fixes itself by relogging but happens within a few seconds after that when I have my farm on.

**Comment by XFactHD** [comment]
I can also reproduce this if I place a water source block and destroy it by playing any kind of block in the source block's space. This happens to all the models in IE. In terms of IC2: If the flowing water hits the IC2 machines, they do the same thing your screenshot shows.

**Comment by Xiaminou** [comment]
Looks like I'm still getting this bug.

**Comment by Xiaminou** [comment]
Just reproduced it:

1. Place a wooden post
2. Grow Oak saplings with bonemeal

https://youtu.be/TJcvv4x7z_I
