### ISSUE TITLE
[Suggestion] Air Vents and Auto/Assisted Farming

### ISSUE THREAD

**Issue by DrakoAlcarus** [BluSunrize/ImmersiveEngineering#1116]
These kind of go hand in hand:

The air vents serve as a way to pump pressurized air out into the open. It has uses (depending on the pressure, if that's even possible) that could push items and entities, much similar to a conveyor, but it can go through non-solid blocks where conveyors can't go like through crops for item clean up or mob farms, so they can spawn and get pushed. Or bait in a steel cage can be added to attract mobs.

Edit: Another thing to add would be a sawmill. The conveyor will just pull logs from one end, and push out extra wood compared to just crafting it.

Here is a design I came up with for building it. The radiator keeps the blade cool, and adds to the overall look of the machine.
<a href="http://imgur.com/qnmkrgw"><img src="http://i.imgur.com/qnmkrgw.png?1" title="source: imgur.com" /></a>
The MV connectors just show possible points where energy can be accepted.

**Comment by James-T-Oudvoure** [comment]
While I'm not entirely sure about the air vents (although it does sound interesting), this mod really needs an automated farming system.

**Comment by mindforger** [comment]
please use search first before double posting stuff ... well at least the lower half of your suggestion :) 
https://github.com/BluSunrize/ImmersiveEngineering/issues/602

**Comment by DrakoAlcarus** [comment]
I added something else. Thank you for informing me about the double post, @mindforger.
