### ISSUE TITLE
Flickering HV connectors

### ISSUE THREAD

**Issue by Plurp13** [BluSunrize/ImmersiveEngineering#1117]
My HV connectors are behaving very strangely, they work but they look weird and keep flickering. I got some screen shots that hopefully show what I mean.

![screen shot 2016-05-10 at 11 20 14 am](https://cloud.githubusercontent.com/assets/8428847/15152167/3eb46a34-16a2-11e6-8fd2-be751bdcb3f1.png)
![screen shot 2016-05-10 at 11 20 19 am](https://cloud.githubusercontent.com/assets/8428847/15152142/33f109d6-16a2-11e6-9305-5166d5fac6f0.png)
![screen shot 2016-05-10 at 11 20 34 am](https://cloud.githubusercontent.com/assets/8428847/15152208/641ad27c-16a2-11e6-9737-6f4a218f66bf.png)

**Comment by BluSunrize** [comment]
What the heck...

Some mod causing a spam of render updates maybe....but that shouldn't affect their properties...

**Comment by malte0811** [comment]
What version is this?

**Comment by BluSunrize** [comment]
0.8 - 25, I know the server this is on.

**Comment by Plurp13** [comment]
A similar thing is happening with the fluid pipe too.

**Comment by MagieMalone** [comment]
http://i.imgur.com/9mbEiR6.png
http://i.imgur.com/79C5znf.png

**Comment by malte0811** [comment]
@MagieMalone What version of IE?

**Comment by MagieMalone** [comment]
0.8-26
