### ISSUE TITLE
[1.8.9][0-8.25] Cannot get Biodiesel into Diesel Generator

### ISSUE THREAD

**Issue by Xiaminou** [BluSunrize/ImmersiveEngineering#1118]
![2016-05-10_20 38 49](https://cloud.githubusercontent.com/assets/8670392/15158361/df82ab90-16ef-11e6-9eb2-899b061831d1.png)

I have tried different pipes and even outputting directly from a tank but nothing works. I'm not sure if I'm doing something wrong or if it's a bug.
Also Immersive Engineering's pipes do not work at all.

**Comment by mindforger** [comment]
you could trying to hook the capacitor in series b etween generator and your equip, also make sure you define the sides of the capacitor as in and output, EIO stuff handles power a tiny bit different

**Comment by Xiaminou** [comment]
the problem is not with the capacitor, as I'm already extracting from Ender IO capacitors and it's working fine. But I tried an IE's capacitor just in case, and still nothing.

**Comment by XFactHD** [comment]
Did you try using IE's Fluid Pipes?

**Comment by bookerthegeek** [comment]
He said he did in the first post.

**Comment by XFactHD** [comment]
Oh, I must have missed that.

**Comment by BluSunrize** [comment]
So what is the issue? No power output? Or no fluid input? Because it works perfectly fine for me in dev.

**Comment by Xiaminou** [comment]
I believe it is no fluid input, because it would produce power even if capacitors are full and therefore pump fluid, right?

What pipes did you use to make it work?

**Comment by XFactHD** [comment]
His own pipes (IE pipes).

**Comment by Xiaminou** [comment]
Well IE's pipes don't work at all for me, they don't transfer any liquid and from what it renders, don't connect to any machines.

**Comment by Xiaminou** [comment]
Doing some more testing I now found a new bug, if you place fluid pipes and then place a tank at the end of the line it won't send fluid, however if you place the tank first and then connect it with pipes it will.
Pipes also render funny when you place them like they did before, however they now fix themselves with block updates.

**Comment by Xiaminou** [comment]
Reproduced: https://youtu.be/8fqym5r__dM

**Comment by Xiaminou** [comment]
Just tested 1.10.2 and I still can't get Bio Diesel inside the Diesel Generator.

**Comment by MalkContent** [comment]
try putting the redstone engineering block on the other side.
for some reason one mirror orientation has no fluid input. for me it is when the redstone engineering block is on the left side (with radiator blocks being the back, generator blocks being the front)
