### ISSUE TITLE
[1.8.9][0-8.25] Transformers visual bug(s)

### ISSUE THREAD

**Issue by Xiaminou** [BluSunrize/ImmersiveEngineering#1119]
The items versions of the transformers' connectors do not match the block versions' connectors. For the HV Transformer, the HV Connector is on the left for the item version, but it is on the right for the block version. See for yourself:
![2016-05-11_02 34 30](https://cloud.githubusercontent.com/assets/8670392/15166666/7533c7ce-1721-11e6-810a-9c968160786b.png)
![2016-05-11_02 38 28](https://cloud.githubusercontent.com/assets/8670392/15166667/75344906-1721-11e6-8881-839985b60179.png)
![2016-05-11_02 36 04](https://cloud.githubusercontent.com/assets/8670392/15166690/a5584326-1721-11e6-906d-1f2de2a98043.png)
![2016-05-11_02 36 08](https://cloud.githubusercontent.com/assets/8670392/15166691/a5586dec-1721-11e6-8429-da2b12357f77.png)

And this happened when I tried connecting wires to it:
![2016-05-11_02 43 22](https://cloud.githubusercontent.com/assets/8670392/15166751/2527b410-1722-11e6-9488-40c3487ad6e4.png)

**Comment by BluSunrize** [comment]
The rendered connectors are dynamic based on where you attach a wire.

**Comment by malte0811** [comment]
@BluSunrize Please reopen this, the connection offsets are wrong. The last picture shows this, the gray strip on the post is a wire ending a bit above the connector.

**Comment by Xiaminou** [comment]
Still getting this with ImmersiveEngineering-0.8-27

**Comment by Xiaminou** [comment]
reproduced: https://youtu.be/Z15jwo58lbA
