### ISSUE TITLE
HV cable -> copper cable

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#112]
Upon connecting two HV wire relay blocks together via High-Voltage Wire Coil, the HV cable immediately transmutes itself into copper cable. with an RF transfer rate of ~250 rf/t
when attempting to use copper cable on the same blocks, the expected chat warning appears: "You cannot attach this wire here"
IE version 3.0 running on FTB Infinity (no other non-default mods added)
Built against commit 0d4efb56cedd661ef25470147bfa145de17c2261.
Log: http://paste.feed-the-beast.com/view/bb791029
![image](https://cloud.githubusercontent.com/assets/3110986/8384438/c75b38ca-1bf5-11e5-8f9c-8ef35ec2af94.png)

**Comment by BluSunrize** [comment]
Yeah, definetly my fault. Will fix it asap.
