### ISSUE TITLE
[1.8.9][Suggestion] Rotate the Industrial Fermenter/Squeezer 180°

### ISSUE THREAD

**Issue by Xiaminou** [BluSunrize/ImmersiveEngineering#1123]
![2016-05-12_17 01 00](https://cloud.githubusercontent.com/assets/8670392/15219257/60188e9a-1863-11e6-9b96-666cd54a495e.png)

Both machines are made to be connected to the Refinery either directly or via pipes. However only one of them is rotated so that when it faces the same way as the refinery the fluid output is on the same side as the refinery. As you can see in the screenshot the Industrial Fermenter is facing the wrong way.

This is not a big deal but for the purpose of immersion I would like to see either of those machines rotated 180° so all of them face the same way. Or maybe have two different ways of building it so they can both go on either sides, but I'd think that's more complicated.

**Comment by malte0811** [comment]
If this is what you mean, it is already possible by just mirroring the unformed multiblock:
![2016-05-12_20 46 34](https://cloud.githubusercontent.com/assets/10406104/15226367/b29b8d06-1882-11e6-8d2f-3da03dd031e1.png)

**Comment by Xiaminou** [comment]
It is exactly what I'm suggesting, thank you. I didn't know, that's great. Did it say that somewhere in the manual, did I miss it?

**Comment by BluSunrize** [comment]
Nope. Says it nowhere. One of those features that users are free to discover themselves =P

**Comment by Xiaminou** [comment]
Well it's a great feature! But I still think it should be included in the book somewhere.
