### ISSUE TITLE
[Suggestion] Pipe Valves

### ISSUE THREAD

**Issue by berinhardt** [BluSunrize/ImmersiveEngineering#1124]
It would be amazing if you could add some sort of valve block that could block the flow or connect to some of the adjacent pipes. It would also be great if you could control it with redstone.

**Comment by James-T-Oudvoure** [comment]
I support this.

**Comment by Joshwoo69** [comment]
I will leave my support. also add redstone capabilities to toggle on and off with redstone.

**Comment by BluSunrize** [comment]
Moving this discussion to #1328 so I don't have to reiterate what I said there.
