### ISSUE TITLE
[1.8.9] Water Wheel Rendering Glitch

### ISSUE THREAD

**Issue by Flying4ssassin** [BluSunrize/ImmersiveEngineering#1125]
In my world there is a tower of watermills generating RF for me. Occasionally when I go into certain chunks or look away from it for too long they render like this:
![2016-05-13_17 51 09](https://cloud.githubusercontent.com/assets/19353597/15262894/5e8b45ce-1933-11e6-9a99-b911b8551a98.png)
![2016-05-13_17 50 57](https://cloud.githubusercontent.com/assets/19353597/15262897/5e8e3522-1933-11e6-8b01-fc2d415bee1b.png)
![2016-05-13_17 51 01](https://cloud.githubusercontent.com/assets/19353597/15262898/5e90cff8-1933-11e6-895e-93aeecc480d6.png)

This causes a massive drop in frame rate which can get aggravating. I can fix it by either reloading the world or going in and out of the nether or even just going far enough away that it isn't within rendering range.

Here is the list of mods in the form of a crash log: http://pastebin.com/kVMJe03H

*Fixed crash log link

**Comment by mindforger** [comment]
to be honest, this looks like more a design problem, did i count right and your waterwheel blades are inside the wall, sometimes causing a z-fight through the wall?

the link of your crash report is broken, but i guess you tried reproducing this without optifine? i knwo several mods that caused z-fighting and resulting FPS drops in the past

**Comment by Flying4ssassin** [comment]
The way I built it was as follows if you are looking down:
CCCCC
CwwwC
CwwwC
CwwwC
CwwwC
CwwwC
CXXXC
CCCCC

C=Cobblestone
w=Waterwheel
X=Space for flowing water

The parts poking out of the cobblestone are going through the flowing water block and the cobble stone because it is rendering 5+ water wheels rotating in the place of one.

I am not using optifine in any case.

**Comment by malte0811** [comment]
@mindforger I have seen something similar in my test world some time ago (when writing 4789c8714da6a7f740fcebcfd7efc794cd0cd709). Either all or at least most TE's in the chunk render in "standart" state, so a waterwheel is rendered centered on every block of a waterwheel and connectors are rendered as if placed on the top of the block below and without wires. I personally suspect the kinetic dynamos, there is some [weird code](https://github.com/BluSunrize/ImmersiveEngineering/blob/072e990b36a93fb7f197fabf1edb9f90c63ad160/src/main/java/blusunrize/immersiveengineering/common/blocks/metal/TileEntityDynamo.java#L63) in their `readFromNbt`-method.

**Comment by Flying4ssassin** [comment]
@malte0811 So what can I do to fix this?

**Comment by malte0811** [comment]
No idea. I will put a potential fix into the next version, but until then I can't really do anything about it.
