### ISSUE TITLE
[1.8.9]-[Visual Bug] Tinkers Construct/Immersive Engineering Compatability

### ISSUE THREAD

**Issue by Voxel-Friend** [BluSunrize/ImmersiveEngineering#1126]
Not sure who to report to, so I am posting this to both github issue trackers.
TCon Version:	1.8.9-2.2.1
IE Version:	0.8-26

When melting down non-Tinkers metals in the smeltery, the graphics for the molten metals are invisible. Note that in the provided screenshots that they are functionally still there. This phenomenon also occurs when pouring out of a faucet. There is no issue with the "Cooling" fade animation, the block just appears to phase into existence.

So far only IE metals have been tested, and the phenomenon has appeared using IE Uranium and IE Constantan.
![2016-05-13_17 29 20](https://cloud.githubusercontent.com/assets/12395262/15263509/540cce04-1930-11e6-8c6d-35362b7e6267.png)

![2016-05-13_16 54 14](https://cloud.githubusercontent.com/assets/12395262/15263321/a28fb2fa-192e-11e6-88d7-2523a14d1295.png)

**Comment by Voxel-Friend** [comment]
https://github.com/SlimeKnights/TinkersConstruct/issues/2079

**Comment by SpartanSamuel** [comment]
I'm hosting a 1.8.9 server with both of these mods installed and am receiving an error regarding the compatability between the two that I think is relevant to this issue (may be the cause, I have no idea).

http://pastebin.com/KuK7DzkU.

Hopefully this helps fix your issue.

**Comment by BluSunrize** [comment]
Spartan, your issue is unrelated, it's an error message you can neglect, and you'd have to take it up with TCon, it's their side.

As for the original issue? Not sure, but I feel like blaming TCon since it's their main rendering code?

**Comment by Voxel-Friend** [comment]
No idea, your the modders, not I. Like I said, I reported to both repos for
this very reason. Thank you for your continued awesomeness.

On Sat, May 14, 2016 at 5:44 PM, BluSunrize <notifications@github.com>
wrote:

> Spartan, your issue is unrelated, it's an error message you can neglect,
> and you'd have to take it up with TCon, it's their side.
>
> As for the original issue? Not sure, but I feel like blaming TCon since
> it's their main rendering code?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/BluSunrize/ImmersiveEngineering/issues/1126#issuecomment-219255700>
>



-- 
She is my life.

**Comment by malte0811** [comment]
Blu, this is IE's fault, not tinkers. I have fixed it, I just need to show you the colors the fluids have now to check whether those colors are correct (I didn't want to do that while you were streaming).

**Comment by BluSunrize** [comment]
Okaaaay...How did I fuck up? xD

**Comment by malte0811** [comment]
Fluid color isn't just RGB, it has what I asssume is an alpha value before the RGB. So I added an `|0xFF000000` to `getColor`, but molten uranium looks nearly black now.

**Comment by BluSunrize** [comment]
that seems odd....

**Comment by mallrat208** [comment]
huh, I thought it used RGBA

**Comment by malte0811** [comment]
If the last value was alpha, wouldn't the fluids have rendered half-transparent, but in a wrong color? The constantan color looks good when adding alpha in front, uranium doesn't.

**Comment by malte0811** [comment]
Nevermind the color thing, I was still using the biodiesel texture from debugging... looks much better now
![2016-05-15_16 13 23](https://cloud.githubusercontent.com/assets/10406104/15274653/f6b974d0-1ab7-11e6-9355-e68c78ae1c57.png)
