### ISSUE TITLE
[1.8.9] Fluid Pipes not connecting to Refinery Output Port

### ISSUE THREAD

**Issue by TheRubberDuckie** [BluSunrize/ImmersiveEngineering#1129]
IE Version: 0.8-26

After making the refinery, the two input ports on it are able to be connected with fluid pipes but the output port on the front isn't.
![2016-05-14_18 29 18](https://cloud.githubusercontent.com/assets/19367553/15271493/fcfce496-1a01-11e6-9b1d-cfe715462c21.png)
![2016-05-14_18 31 40](https://cloud.githubusercontent.com/assets/19367553/15271498/25a52a20-1a02-11e6-8232-ff30555b4018.png)
Mods List:
![mods](https://cloud.githubusercontent.com/assets/19367553/15271501/5dac464c-1a02-11e6-83c2-cd6006dde3aa.PNG)

**Comment by CJL48** [comment]
I've had this issue as well, but it's purely visual: the pipes can still carry biodiesel into tanks or the generator. Have you tried connecting the pipes to an output?
