### ISSUE TITLE
[1.8.9] Balloon behaviors don't match manual description 

### ISSUE THREAD

**Issue by 3TUSK** [BluSunrize/ImmersiveEngineering#1132]
E.g.
> or, when no block is targeted, they will be placed in the air infront of you.

Actually you can't do that for unknown reason.

> Sneak-clicking allows you to set a height offset for the balloon

Fail to set height offset, for unknown reason

> you can attach Hemp Rope and Steel Wire to the balloon

Then rope/wire become invisible. ~~(which let me remember those wires on connectors)~~

Found by @Amamiya-Nagisa

**Comment by malte0811** [comment]
The last point is my fault, I completely forgot about the balloon when changing the wire rendering system. I'm interested to see how much I have to tweak to get shaders working.

**Comment by BluSunrize** [comment]
Save yourself the trouble of shaders, Malte. I don't intend to bring them back for balloons. It was a bit gimmicky and useless anyway.
As for not being able to do height or mid-air placing: I didn't get around to fully add them back yet. They are just in as basic blocks. It's a beta after all.

**Comment by malte0811** [comment]
Shaders *should* be easy to get working with my system since I have a model for the block itself anyways. But if they aren't implemented for balloons anyways, it will be pretty much trivial to fix the last point.

**Comment by 3TUSK** [comment]
None found typo in title? XD
