### ISSUE TITLE
[1.8.9] [Question] Assembler missing?

### ISSUE THREAD

**Issue by Cobra1117** [BluSunrize/ImmersiveEngineering#1133]
In the 1.8.9 version, I'm unable to find the assembler in the Engineer's Manual, and the structural arms needed to construct it in previous versions are no longer in the game. Has this been left out intetionally, or is this a bug?

Tested with:
Minecraft: 1.8.9
Immersive Engineering: 0.8-26

**Comment by BluSunrize** [comment]
It's not in yet. That's why it's a damn beta .___.

**Comment by Cobra1117** [comment]
Sorry! Was just making sure, since I didn't see it mentioned anywhere in the changelogs!
