### ISSUE TITLE
[Graphical Bug] Water Wheel Shadow

### ISSUE THREAD

**Issue by thebrianlenz** [BluSunrize/ImmersiveEngineering#1134]
There seems to be a shadow rendering issue with the Water Wheels. From what I can tell, as soon as I place water over them (one block behind center), there is a shadow cast over the entire wheel. If the water is placed directly over the center point, the shadow is not cast (though this isn't always true apparently).

I've tried removing the framing around the wheels and that did not prevent the shadows from being cast.

![](http://i.imgur.com/t9oVUvm.png)

Version 0.7.5 in Minecraft 1.7.10 in the Infinity Evolved Skyblock pack, version 1.1.0 of IE:S.

**Comment by BluSunrize** [comment]
Fastcraft issue. Might actually be fixed in newer versions of IE, correct @malte0811?

**Comment by malte0811** [comment]
Yes, fixed in 0.7.6, but I recommend updating to 0.7.7.

**Comment by elkillo** [comment]
i am having a similar issue however i am using the 1.8.9 version (8.26 i believe) without fast craft installed and both my water and wind mills are having shadow issues.
