### ISSUE TITLE
[1.8.9]Tank forms instead of Silo

### ISSUE THREAD

**Issue by Voxel-Friend** [BluSunrize/ImmersiveEngineering#1135]
Version 0.8-26
As the recipe for the first five layers of the silo is identical to that of the tank, when attempting to form the silo a tank forms instead.
![2016-05-16_07 15 56](https://cloud.githubusercontent.com/assets/12395262/15289191/18442752-1b36-11e6-974f-202b18e11ec2.png)

**Comment by AlterAkima** [comment]
Keep it hollow inside, they are not the same.

**Comment by Voxel-Friend** [comment]
Then the manual needs to be updated to reflect that. According to the manual, the top three layers of the silo is not hollow, and the next three are.
