### ISSUE TITLE
(MC 1.7.10) Serverside Error resulting in user disconnect

### ISSUE THREAD

**Issue by Vaygrim** [BluSunrize/ImmersiveEngineering#1136]
MC 1.7.10 / ImmersiveEngineering 0.7.1.2 / Forge 1614
http://pastebin.com/FqD8ntcp

Player "Peake81" was whipping across our server via Skyhook (he has a line of suspended steel cable going from his base to spawn) when he suddenly got disconnected from the server due to a "Bad Packet". I'm actually not 100% sure if this is IE or not, but since it involved skyhooks while disconnecting .. and has errors from the IE mod all over the server side error, I figured it was worth a check. Right now, the players gets immediately disconnected the moment he tries to connect to the server.

I realize 1.7.10 is considered 'old' nowadays, so I'm not expecting miracles. I'm mostly just looking for a solution that will get this player back on the server. 

Halp? <3

**Comment by Vaygrim** [comment]
Uh follow up note: there was no 'crash' on the client's side for this, so no crash logs from that end. Server didn't crash, so no crash log there. Just a set of errors rattled off to the server's console. If testing is needed, I can arrange for access to the server, or I can post full server logs here?

Just let me know!

**Comment by malte0811** [comment]
Try removing all entities named `skylineHook`. That should help. The skyline hooks were not really intended to be saved to NBT, so they will misbehave after being loaded from NBT. The first disconnect was probably caused by something else, this "crash" will happen with any skyline hook entity loaded from NBT.

**Comment by Vaygrim** [comment]
Well I went and removed the entire line of steel cabling and anchors that the player in question was using to travel when this happened. I then rebooted the server. How would I go about removing these 'skylineHook' entities?

**Comment by malte0811** [comment]
Try `/cofh killall skylineHook`, but I don't know whether that only works for living entities. Otherwise it may be necessary to use MCEdit or something like that, but I don't know much about those programs.

**Comment by malte0811** [comment]
Did the command resolve the error? My edit just meant that the command does work on skyhooks even though they aren't living entities.

**Comment by Vaygrim** [comment]
I was JUST about to come post about this!
"/cofh killall skylineHook" did nothing. Command yielded the results "No entities found". User is still unable to log in. :(

**Comment by Vaygrim** [comment]
I've got an updating going out to this server today, jumping to IE 0.7.7 for 1.7.10, we are hoping this might iron things out.

**Comment by malte0811** [comment]
The update to 0.7.7 won't change anything as the changes from 0.7.6 to 0.7.7 did not touch anything even remotely related to this. Where did you perform the command I gave you? Near the wires that aren't there any more or somewhere completely different?

**Comment by Vaygrim** [comment]
Well I figured the command was server-wide, for all loaded chunks. The 'problem area' on the map where the incident happened should have been chunk loaded at the time, but I'll try it again just in case here in the next hour.

**Comment by SpartanSamuel** [comment]
Sorry for intruding, but if that doesn't work there's something else you may try.

Go into [world] > playerdata > 0e8b137f-b05d-4441-92f3-16e1d379f21e.dat. I used this site to convert the player name to his UUID. I open my players' files using NBTExplorer but I'm sure there's other solutions out there. Once you have it open, expand the 'Pos' entry and adjust his coordinates elsewhere. Spawning him outside of the chunk causing the issue will get him in, but it won't solve the problem of what kicked him.

Hope that helps.
