### ISSUE TITLE
[1.8.9][0.8-26] Ethanol not bottling

### ISSUE THREAD

**Issue by SoldierKucha** [BluSunrize/ImmersiveEngineering#1138]
![2016-05-17_18 36 48](https://cloud.githubusercontent.com/assets/15803655/15322702/7b550202-1c68-11e6-9a2d-fe408334a483.png)

**Comment by elkillo** [comment]
i can confirm this neither the fermenter or squeezer do this either i cannot put seed oil or ethanol into glass bottles or buckets. the refinery and bottler both do not as well
