### ISSUE TITLE
how disable ore gen

### ISSUE THREAD

**Issue by jem991** [BluSunrize/ImmersiveEngineering#114]
how disable ore gen

**Comment by DoughnutDev** [comment]
Read you configs it tell you how to disable them...

**Comment by jem991** [comment]
Which I do not understand the vein size.

**Comment by BluSunrize** [comment]
veinsize = blocks per vein.
It makes perfect sense, since the other values aren't a "size" >_>

**Comment by jem991** [comment]
Sorry!! I'm simple man.
veinsize = veinsize
blocks per vain = block per vein :D
