### ISSUE TITLE
[1.8.9][bug] conveyor belt not moving items uphill or down properly

### ISSUE THREAD

**Issue by elkillo** [BluSunrize/ImmersiveEngineering#1140]
when using conveyor belts to move up and down hill the items tend to pop off when going downhill and get stuck hopping on the slop going up hill. is this a known issue or did i break something? i'm using the curse client and do not have fast craft installed. Version 0.8 - 26. To be clear the belts work perfectly fine when on the same plane but when going up or down the items almost seem to be falling through the belt when they reach the slope.

**Comment by mindforger** [comment]
what other mods do you have installed? this is a pain that goes on since ever but nobody was able to find the culprit as with IE alone it always works fine ... must have to be some other mod doing stuff to floating items or something on the server side. 
Do you play MP or SP? If MP what kind of Server Base, clean forge or something like cauldron?)

**Comment by elkillo** [comment]
i use clean forge from the curse client i play exclusively SSP with this pack. all mods are 1.8.9 and are current versions available on curse.

i use the following mods

better Foliage
blood magic
botania unoffical 1.8.9
buuildcraft
chameleon (lib mod)
Chisels and bits
clay world gen
Computercraft and computer craftedu
cooking for blockheads
endertanks
extra utilities 2
fast leaf decay
Immersive engineering
IC2
inventory tweaks
iron backpack
iron chests
journeymap
JEI
JEI resources
Mantle
Ore tweaker (to add extra iron there isnt enough for IE xD)
Pams harvestcraft
Psi
real time clock
Reliquary v1.3
SAO UI
shetiphianCore
simple harvest
storage drawers
thaumcraft
Tinker construct 2
waila

**Comment by mindforger** [comment]
blood magic
XU
fast leaf decay
IC2
iron chests
Mantle
TinkersC
Pam's
Storage Drawers
waila
ThaumC
BC

thats all similaritys i could spopt with my pack so far

**Comment by 3TUSK** [comment]
@Amamiya-Nagisa can confirm it as well IIRC

**Comment by elkillo** [comment]
i think once i get home ill disable all mods outside you list and try each one by one till i find the culprit. i can however tell you its not better foliage as i have tried disabling it already.

**Comment by malte0811** [comment]
Happens in my dev-environment as well, if there are no blocks below the belt the items will fall through and if there is they get stuck on the edge of the first conveyor. I'll look into fixing this now.

**Comment by elkillo** [comment]
i can confirm it does happen to players as well and malte's description is correct.
