### ISSUE TITLE
[1.8.9][possible bug] dropping conveyors not dropping into some vanilla inventories below it

### ISSUE THREAD

**Issue by elkillo** [BluSunrize/ImmersiveEngineering#1142]
the Dropping conveyors don't seem to drop into some vanilla inventories, this includes vanilla furnaces top slot for input, trapped chests (which normal conveyors don;t insert into) to name a couple. They do however drop into hoppers are far as i can tell. Is this intended? or did a find a bug?

**Comment by malte0811** [comment]
Fixed. The belts were inserting into the side of the inventory.

**Comment by elkillo** [comment]
Thank you for your and bluSun's hard work :)
