### ISSUE TITLE
[1.7.10] crash with latest EE3

### ISSUE THREAD

**Issue by Keyarose** [BluSunrize/ImmersiveEngineering#1143]
The newest version of EE3 seems to have changed its API, causing a crash.

IE version: 0.7.7
EE3 version: 0.3.0.511

crash log: http://pastebin.com/VAVMX29L

**Comment by mindforger** [comment]
seems like an unintended change! 
https://github.com/pahimar/Equivalent-Exchange-3/issues/1045

**Comment by Keyarose** [comment]
Looks like it got fixed on EE3's side, closing this.
