### ISSUE TITLE
Crash with newly updated EE3.

### ISSUE THREAD

**Issue by border999** [BluSunrize/ImmersiveEngineering#1145]
http://pastebin.com/mCP54QpG

**Comment by malte0811** [comment]
#1143

**Comment by mindforger** [comment]
@malte0811 where do you see the connection O_o i don't see any connection, this looks like an "impossible" error trace to me, maybe more likely an optifine issue!? if not enlighten me XD

@border999 just a side note, your Java is WAY out of date and just barely behind a version mark where minecraft would not run before ;D

**Comment by malte0811** [comment]
Ok, I take it back. I didn't actually look at the crash, I just thought that a single EE update wouldn't have more than one compatibility crash.

**Comment by border999** [comment]
@mindforger and what version of java would you recommend then? because the latest version of java has issues when it comes to minecraft.

**Comment by XFactHD** [comment]
I am using the latest version of Java 8 and I haven't had any issues so far.

**Comment by border999** [comment]
can't accolade more than 1.5gb. what is your EXACT version. and what arguments are you running?

**Comment by malte0811** [comment]
If that is the case you are using the 32 bit version.

**Comment by XFactHD** [comment]
I am using update 92 and because of the insane amount of mods I am using, I allocated 10GB, but I am not using any other special arguments.

**Comment by border999** [comment]
@malte0811 It checked and made sure to download 64-bit java.

**Comment by mindforger** [comment]
like @XFactHD mentioned Java 8 Update91 should be the latest

**Comment by border999** [comment]
@mindforger it's 92 now and it works. thanks @XFactHD for the info.

**Comment by BluSunrize** [comment]
So this issue is fixed+closed?

**Comment by border999** [comment]
Looks like it was figured out on EE3's end but thanks for looking at it anyways.
