### ISSUE TITLE
The WAILA fix causes other render issues

### ISSUE THREAD

**Issue by BluSunrize** [BluSunrize/ImmersiveEngineering#1155]
Namely this one:
http://puu.sh/p13J0/8f71e3e9b3.jpg

Highlighting a block with WAILA on fucks up the skybox. Doesn't happen when that WAILA workaround of enabling blend is commented out.
I'm still trying to figure it out myself, @malte0811 , it might be something with the event priorities.

**Comment by malte0811** [comment]
Does it happen when you are not looking at a block? So if the WAILA window is hidden?

**Comment by BluSunrize** [comment]
Nope. Only present with WAILA overlay.

**Comment by malte0811** [comment]
Then it is possible that I have to cache even more GL state, the fix is running independent from the WAILA window.

**Comment by BluSunrize** [comment]
It's the blend being disabled in skybox, I believe. I'm trying to see if I can get around it with the fog event right now.

**Comment by BluSunrize** [comment]
Yep, that did it, hopefully

**Comment by malte0811** [comment]
Out of couriosity, do you know where the sun is rendered? Which class?

**Comment by BluSunrize** [comment]
RenderGlobal.renderSky()

**Comment by malte0811** [comment]
What do you think about this alternative fix? Btw, `RenderGlobal.renderSky()` seems to be unused (breakpoint does not trigger), the real code seems to be starting at line 1317 (`this.renderEngine.bindTexture(locationSunPng);`).

**Comment by BluSunrize** [comment]
I assume that alternate fix works without the fog event then? In which case: Be my guest.

**Comment by malte0811** [comment]
Yes. The relevant part is that I am using the `GlStateHelper` instead of direct GL calls. The rest is just leftover stuff from testing that either doesn't hurt or even improves performance.
