### ISSUE TITLE
[1.8.9][bug] metal press textures randomly break and look like there are 4 of them stacked

### ISSUE THREAD

**Issue by elkillo** [BluSunrize/ImmersiveEngineering#1158]
title says it all ill attach a photo
![2016-05-23_18 34 25](https://cloud.githubusercontent.com/assets/19398102/15487532/1b178636-211c-11e6-997d-75efe8c478ff.png)
![2016-05-23_19 22 46](https://cloud.githubusercontent.com/assets/19398102/15487536/20fb0eb0-211c-11e6-8279-d7692d66cf03.png)

**Comment by mindforger** [comment]
IE Version? Forge Version? Optifine removed while reproduced (if present)? SMP or SSP?

**Comment by elkillo** [comment]
IE: 8 - 26, forge 11.15.1.1902, optifine and fast craft not installed, latest java 8. Only render changing mod i know of is better foliage and unable to exactly reproduce it sorta randomly happens. sorry posted real quick before work yesterday and forgot guidelines. Reloading world is temp fix

**Comment by malte0811** [comment]
This used to happen when forming the multiblock, I believe I fixed that case.
If I understand this correctly it now happens at random times (not directly after forming the press and not immidiately after loading the chunk on the client)? Do you have a kinetic dynamo in the same chunk as the presses? If you have, please remove it, replace it with some other generator for now and see whether the bug stops happening. Something like this has happened before and I suspect that the dynamos cause it.

**Comment by elkillo** [comment]
So the dynamo isn't not in the same chunk but is nearby. I can simply move the press if that's the case

**Comment by elkillo** [comment]
on a side note how do i close an issue post like this?

**Comment by BluSunrize** [comment]
should say "close issue" right next to "comment" at the bottom of the box. Don't do it on this one though, I'll do that after I've pulled Malte's fix.

**Comment by elkillo** [comment]
ahh i see it now. thanks for that. i will also leave it open as instructed,
