### ISSUE TITLE
List of issues (from our talk on discord)

### ISSUE THREAD

**Issue by AkaruC** [BluSunrize/ImmersiveEngineering#1160]
Crusher bounding boxes 
Concrete (and potential other blocks) with chisel and bits
Manual rf values being 0rf/t (atleast the preheaters, possibly others)
Crash with BC (and others, Neotech for example) pipes on multiblocks (this case was a squeezer)

**Comment by BluSunrize** [comment]
1) Will look at
2) fixed
3) atm working on it
4) fixed

Dibs on all of these malte, I'll deal with them.

**Comment by BluSunrize** [comment]
Dealt with, crusher fixed and preheater fixed and referenced to another issue.
