### ISSUE TITLE
[1.8.9][possible bug] Capacitors, dynamos, and thermoelectric generators not outputting to BC

### ISSUE THREAD

**Issue by elkillo** [BluSunrize/ImmersiveEngineering#1162]
IE Version 8 - 26
BC Version 7.2.6
Forge version 11.15.1.1902
Capacitors and other power generating and distributing machines do not seem to outputting to BC pipes. The accept from them just fine but wont output to pipes at all (wooden or otherwise). IE connectors however can power BC machines.

**Comment by malte0811** [comment]
Yes, IE uses a different system (IF) than RF internally. The wires will convert from RF to IF and vice versa without any additional losses.

**Comment by elkillo** [comment]
Ahh I see, that makes sense as it does just say "flux" and not redstone flux. I also had a question about thermoelectric generators. Can I ask here or would you prefer a new topic

**Comment by malte0811** [comment]
I would say ask it here and if it turns out to be a bug, open a new issue.

**Comment by elkillo** [comment]
Well I was wondering about thermoelectric generators can I stack them? As in if I put them one on top of the other will they transmit flux to the on above them? Because I'm trying to build a more compact TEG setup

**Comment by malte0811** [comment]
They don't, and I don't think that it is planned to make them behave like that. @BluSunrize?

**Comment by BluSunrize** [comment]
Nope, not planned at all.
Also, issue closed.
