### ISSUE TITLE
[1.8.9] Arc Furnace Isseus

### ISSUE THREAD

**Issue by Veggetossj** [BluSunrize/ImmersiveEngineering#1163]
Found several issues with the Arc Furnace:

1. When multiple type of grit are inside, i.e. lead and silver. After smelting the lead into an ingot and putting it in the output slots inside the machine. If it then smelts the silver grit, the silver ingot does not get created in the output slots.

2. When a stack of ingots is in the output slots inside the machine, any other grit that gets smelted afterwards, does not appear in the output slots.

**Comment by malte0811** [comment]
I have fixed 2 issues with the arc furnace for the next release:
1. The arc furnace only processes one item at a time.
2. The output of the arc furnace will be voided if the first output slot is filled with a different output.
Are these the same issues as the ones you reported?

**Comment by Veggetossj** [comment]
Yes, they are the same
