### ISSUE TITLE
Engineer's Toolbox "NullPointerException: Updating Screen Events", enables Item Duplication

### ISSUE THREAD

**Issue by Shoob189** [BluSunrize/ImmersiveEngineering#1164]
Immersive Engineering: 0.8-27
Forge: 11.15.1.1902
Full crash log: http://pastebin.com/5SJDW61K

Shift clicking some items into the Engineer's Toolbox causes a "NullPointerException: Updating screen events" in a lambda function in the isWiring() function, crashing the client

Some items confirmed to cause crash:
Steel ingot
Thaumcraft  5.2.4 Thaumometer

Confirmed multiple times on SMP. Server does not crash.

Toolbox inventory doesn't seem to be properly synced on crash, allowing item duplication via this process:
1. Put items in toolbox
2. close toolbox
3. open toolbox, pull item out into player inventory
4. without closing the toolbox, shift click in steel ingot causing crash
5. when player logs back in, the items removed from the toolbox will be in the player inventory and the toolbox, duplicating them

**Comment by malte0811** [comment]
Confirmed, I forgot a nullcheck when converting the checks to lambdas. I'll push a fix in a minute.
