### ISSUE TITLE
Suggestion: Faraday suits

### ISSUE THREAD

**Issue by malte0811** [BluSunrize/ImmersiveEngineering#1169]
For anyone who does not know what a Faraday suit is: watch a bit of this [video](http://www.youtube.com/watch?v=bTkjgBRiCsE&t=9m0s)

We talked about this on IRC briefly yesterday and the problem is as follows (assuming that there were no misunderstandings):

I want Faraday suits, mainly to be able to do kind of an HV show. @BluSunrize does not want the coil to become useless as a defense mechanism which would happen if the Faraday suit protected you from the arcs.

I think I found a solution which will make both possible: Adding a "low power" mode to the tesla coil that consumes less power (x0.5?), but has a lower range (3 block radius?) and allows Faraday suits to work due to lower current. This mode could be activated by shift-rightclicking the TC with an engineers hammer while the TC is turned off or doesn't have enough power to run (IRL: because fiddling with the primary circuit of an active TC is quite deadly, in-game: to prevent intruders from switching defense coils to low-power mode). Using a Faraday suit at normal power mode would result in massive damage to the suit and fire damage in addition to the normal HV damage to the player (because of the molten parts of the suit).

For recipes, aluminum dust or something like that might work well. The suit should take very little damage from low power tesla arcs, but a lot of damage from any other source.

Another thing that might be neat in relation to tesla coils would be fluorescent/neon tubes that can be held or placed in the world as entities. Fluorescent tubes start glowing when they are near an active tesla coil, not enough to light up the environment, but enough to look cool.

If this suggestion is accepted, I would like to implement it myself (apart from the model/texture which would look shit if I made one).

**Comment by XFactHD** [comment]
I really love the idea with the fluorescent tubes, I once saw a show were two people played Star Wars with a red and a blue fluorescent tube over a tesla coil.

**Comment by malte0811** [comment]
I have seen similar things, for example someone wielding 2 fluorescent tubes while being hit by 2 meter arcs in a faraday suit. My idea were colourable tubes (normal mc colouring or even RGB) that could be turned using shift-mousewheel. In 1.9 it would be a nice thing to add dual-wielding support for.

**Comment by AEnterprise** [comment]
maybe make it so that you can't change the coils mode when it's receiving power at all? as you are working with live wires

that would also mean nobody can mess with it from the outside

**Comment by malte0811** [comment]
I have implemented the Faraday suit, now I need to add the fluorescent tubes.
@AEnterprise it can't be switched from high- to low-power mode or vice versa while it is active, trying to do so will result in `Float.MAX_VALUE` (somewhere around 3.5*10^38) of unblockable damage. Preventing redstone mode switching might be a bit of a bad idea since you couldn't switch it twice in a row with that change because switching the RS mode of a disabled coil results in an enabled coil. So if you accidentally switch the RS mode you won't be able to turn it back off without looking for a lever.

**Comment by malte0811** [comment]
Fluorescent tubes that work as items are not gonna happen, I have spent 2 days trying to get it working and the only way that works will break if any other mod using that method messes up (google "TileEntityItemStackRenderer.instance" for details).
I will implement them as placable entities though, thyley will probably be ready later today.

**Comment by laz2727** [comment]
You can just make them visible in the dark.

**Comment by malte0811** [comment]
That is what I was trying to do, here is the problem: without the hacky part I mentioned I can either use a model, which AFAIK always uses lighting, or I register the item to use a TESR, which is called with a `null`-TileEntity and without the ability to access the itemstack in any way that I am aware of. Unless there is something like a static variable storing the itemstack being rendered... @BluSunrize, have you ever seen such a variable?

**Comment by malte0811** [comment]
Fluorescent tube entities are mostly working, I'll push it tomorrow. For now, here is a screenshot of the tubes:
![2016-06-04_22 34 00](https://cloud.githubusercontent.com/assets/10406104/15801942/b74e9c38-2aa4-11e6-9a67-89288cd89742.png)
They can be colored in the engineer's workbench in any RGB color and they flicker when active.

**Comment by AEnterprise** [comment]
@malte0811 they would only glow when holding them in your hand right? if that's the case you can just look at the stack the player is currently holding to get the itemstack

**Comment by malte0811** [comment]
1. Multiplayer. What if one player is holding a red tube that is active and one is holding a green tube that is not active?
2. Other entities can hold items as well, e.g. zombies.

**Comment by malte0811** [comment]
I'm pretty much done, just missing the manual entry and a recipe. I'm working on the manual entry/page now, has anyone got an idea for a crafting recipe or at least for ingredients?

**Comment by laz2727** [comment]
Steel plates for the suit? Graphite electrodes, glowstone and glass for lights?

**Comment by malte0811** [comment]
The suit is currently crafted using aluminium dust, I have changed that to be aluminium plates. I completely forgot about glowstone when thinking about recipes, thank you.
