### ISSUE TITLE
Drill crash issue with Railcraft

### ISSUE THREAD

**Issue by bosto2** [BluSunrize/ImmersiveEngineering#117]
[IE](http://www.curse.com/mc-mods/minecraft/231951-immersive-engineering)-  0.2.4
[FML](http://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.7.10.html#Downloads)- 7.10.99.99
[RC](http://www.railcraft.info/about-the-mod/)-   9.6.1.0
I build a drill from IE with a steel drill head , increased storage and speed (also i broke a block with it so it was damaged)
Then i build a small RC iron tank put biodiesel in it and tried charging the drill by putting it in the tank the server crashed and crashes every time its booted up
[Crash log](http://pastebin.com/UUm1BeUu) (expires:26/7/2015)

**Comment by BluSunrize** [comment]
I wanne blame this one on @CovertJaguar for an uncaught reflection, but I'll try to implement a fix.
