### ISSUE TITLE
[1.8.9][Request] Can we get assembler machine back?

### ISSUE THREAD

**Issue by hron84** [BluSunrize/ImmersiveEngineering#1170]
Please, put back assembler machine. I loved it from Infinity, this is a purely awesome device. Sadly, it is missing from at least the engineers manual.

**Comment by BluSunrize** [comment]
Ugh. Apart from the fact that it /is/ back in the latest version, how much more do I need to state "It's a beta I'm still porting it"? There's even an issue here that you would have found if you searched for "assembler" that told you the same thing.

**Comment by hron84** [comment]
@BluSunrize searching reveals the construct, but the engineers manual index misses it (can't find under any category), that's why i could not discover the addition. Thanks for the headsup anyway.

Btw, you totally took me wrong. I do not wanted to blame you why you are not addd it back yet, it was just a kind feature request. OK, it was not as kind as it should, but definitely not a complaint or a crying. I really love your mod, it has awesome machines and I even appreciate your hard work to improve the machine's outfit while you also porting them. Please, don't get me wrong, I am just a little, but patient fan of IE. I am really sorry if I hurted you unintentionally or accidentally.

**Comment by BluSunrize** [comment]
Eh, it's alright. Vented a stressful evening there. Apologies =P

**Comment by hron84** [comment]
@BluSunrize OK. Can you take a look why manual does not list assembler in classical categories? Or am I missing it? I cannot find it in heavy machinery, nor in the other machine group too.
