### ISSUE TITLE
Silo (apparently) voiding items 1.8.9

### ISSUE THREAD

**Issue by It-IS-Lupus** [BluSunrize/ImmersiveEngineering#1173]
The current version for 1.8.9,  .27 I believe. 

Built a silo, ran extra utilities transfer pipes from a chest up to the top. A transfer pipe on the bottom to pull out just a chests worth to keep available. 

Cobblestone goes in fine, but doesn't pull out. I've tried adding a Redstone signal. 

Tried pulling out by Hand. Nothing. Looking at the silo it doesn't tell me item being stored or number stored. Nor does it have a cobblestone picture on the side

Haven't tried feeding into a Hopper to then dump into the silo.

**Comment by XFactHD** [comment]
Can you reproduce this if you fill the silo via hoppers?

**Comment by malte0811** [comment]
Fixed. This is an IE bug, even though it only happens with transfer pipes. The `IItemHandler.insertItem` method was modifying the input stack, which is forbidden according to the Javadoc.

**Comment by It-IS-Lupus** [comment]
Xfact, I would have tried that next but needed to leave for work. 

Malte, will transfer nodes be able to pull out properly until the next beta?

**Comment by XFactHD** [comment]
No problem, I just wanted to point it out. :smile:
