### ISSUE TITLE
[Recipe][fixed] conflicted with NuclearCraft 

### ISSUE THREAD

**Issue by Kratzwurst** [BluSunrize/ImmersiveEngineering#1174]
hello everyone,

i play the modpack project ozone v 1.7.10 - mc 1.7.10 with your actually version 0.7.7 of immersive.
when i crafting the recipe "sheet metal block" in the crafting table, than become i the "empty cell" from the mod nuclearcraft as result.

here an picture of this issue
http://fs5.directupload.net/images/160602/7amjgcdg.png

greets

**Comment by laz2727** [comment]
Your link is broken.

**Comment by Kratzwurst** [comment]
wait, i reupload the picture

**Comment by laz2727** [comment]
Pic is fine, link isn't.

**Comment by Kratzwurst** [comment]
now it's works fine ;)

**Comment by laz2727** [comment]
Actually, you have the stimmedcow, so you can press the button in the vanilla workbench and craft the sheet blocks for now.

**Comment by Kratzwurst** [comment]
ah okay, thank you for the helpful answer. i have now testing it and works finfe. thank you very much...

have a nice day
