### ISSUE TITLE
[suggestion] alternate method for repairing drill head.

### ISSUE THREAD

**Issue by elkillo** [BluSunrize/ImmersiveEngineering#1175]
as it stands now i almost exclusively mine with the IE drill now (as it is frikkin awesome). i've come to an issue where i really do not get enough EXP to keep repairing it with steel. Vanilla repair mechanics have a stacking cost for each repair. So i was wondering if maybe an alternate method for repairing would be possible. Maybe an electric mig welder that re-welds and repairs the drill head. Or maybe a metal recasting where you melt down the low durability drill head back into steel (not the full amount maybe 18 ish ingots) to make the repair process i little less painful. ive gone through anvils and my repairs are 40+ exp each =P. this is ofc only a suggestion thanks for the AWESOME work guys =D

**Comment by James-T-Oudvoure** [comment]
A new method to repair things would be very nice.

**Comment by toric55** [comment]
anyone know of a mod that removes the increasing cost of repairs?
