### ISSUE TITLE
[1.8.9] Transformers don't attach to Posts

### ISSUE THREAD

**Issue by shizuka** [BluSunrize/ImmersiveEngineering#1178]
Singleplayer 1.8.9, IE 0.8-27 with Forge 1902

![image](https://cloud.githubusercontent.com/assets/676381/15802157/8365bf1c-2a6f-11e6-84f4-8ec401272cad.png)

Not sure if I'm doing something wrong or if it's just beta, but Transformers do not shrink and attach to Posts, regardless of placement.

Tested with and without Optifine, with and without Equanimity resource pack, outcome all the same.

**Comment by elkillo** [comment]
i believe that feature inst fully implemented or is broken. btw how did you get the poles to have the arms on them? i cant seem to do that.

**Comment by shizuka** [comment]
Use-click with the hammer on the topmost block of the pole. Attach a thing below the arm and it automatically flips, or can place both ends as shown.

**Comment by chrisbecke** [comment]
I cannot get things to attach to the top part of Posts in 1.8.9 at all. Even when placed midway, on initial placement the item does not draw correctly, but as shown, the hitbox is anticipating the rotation (which does happen as soon as the player refreshes the area by changing something else near the post, or logging out and back in).

![2016-06-11_20 05 45](https://cloud.githubusercontent.com/assets/6085581/15986753/89ed673a-3010-11e6-983e-494021b18369.png)


![2016-06-11_20 05 26](https://cloud.githubusercontent.com/assets/6085581/15986746/5e8a8fd2-3010-11e6-813b-e1a5e2aa7bac.png)

**Comment by mindforger** [comment]
@chrisbecke any presence of optifine or cauldron/bukkit? if yes please retry without

**Comment by chrisbecke** [comment]
If I WAS using either of those, I would have mentioned up front, and  tested in a SSP game without them.

**Comment by BluSunrize** [comment]
@chrisbecke next time, open a new issue. Otherwise this will go unrecognized.
The top part of the post has no support for those small connectors, it only has arms.
The second one is a vanilla/general 1.8.9 issue, where rendering happens before priority updates.

**Comment by mindforger** [comment]
`If I WAS using either of those, I would have mentioned up front` the majority of people do not mention using optifine while having it, what should make me think you were not just because you are you ... don't be so rude it was just an advice

**Comment by chrisbecke** [comment]
Wait - this is just me being stupid and all I need to do is use the hammer on it to give it some arms? pebkac.
