### ISSUE TITLE
Refinery liquid output crash

### ISSUE THREAD

**Issue by KoxAlen** [BluSunrize/ImmersiveEngineering#118]
Version: 0.3.0
Crash log: https://gist.github.com/KoxAlen/fb96b35b4c724301b90c

How to reproduce:
Place a IFluidHandler(I used fluiducts) on the intended output and another one on the opposite side of the machine, make sure you are voiding it or there is enough space to empty the internal tank of the Refinery, the game will crash on the tick the internal tank gets fully empty.

[Reference code](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/blocks/metal/TileEntityRefinery.java#L98-L112)
For what I gather, the Refinery will try to output to both and if the tank gets completely empty on the first .drain, the second getFluid will crash with NPE

**Comment by BluSunrize** [comment]
Yeah. I'm looking into it, thanks =)
