### ISSUE TITLE
Accessability for the blind.

### ISSUE THREAD

**Issue by Tristaric** [BluSunrize/ImmersiveEngineering#1180]
Right so.
I'm legally blind. Two inches away from my screen as of writing this issue.
Every time I open the Engineer's Manuel, the entire GUI size gets smaller
to the point where I might get bloodshot eyes if I try to read it.
Some option to either bold the text, or change the font, or just fix the GUI size switch thing
I'm 90% sure someone already reported that GUI size bug so I'm not going to repeat that explanation unless needed.
This is using Immersive Engineering 0.8-27 on 1.8.9.

**Comment by Tristaric** [comment]
I also just put your IRC channel on Autojoin. so if you feel like talking there would be best, then now that's a possibility.

**Comment by laz2727** [comment]
You can try to resize the game window, it works sometimes.

**Comment by Tristaric** [comment]
It's already on fullscreen .-.;

**Comment by BluSunrize** [comment]
There's a config option about the GuiSize changing, see if that does anything for you. Otherwise I'll have to see about improving accessibility for detrimental nearsightedness. I worked in colourblindness for Vaygrim back in the day, after all =P

**Comment by laz2727** [comment]
Resize it *down*.

**Comment by Tristaric** [comment]
saddist
that makes it even harder as it makes the GUI
EVEN SMALLER :I

**Comment by laz2727** [comment]
It depends on your gui size, some books render as smallest in fullscreen
and changing window size might make it bigger. I have a lot of these
problems on my 1280x1024 monitor.

**Comment by BluSunrize** [comment]
Improved accessibility has been implemented with https://github.com/BluSunrize/ImmersiveEngineering/commit/ecac92f682e70b7246ca475d58817b84e579c438
Will be in the next release!
