### ISSUE TITLE
Treated Wood will not burn.

### ISSUE THREAD

**Issue by James-T-Oudvoure** [BluSunrize/ImmersiveEngineering#1182]
There's nothing else to say really. If you try to light treated wood on fire, it just goes out immediately.

**Comment by PrincessRTFM** [comment]
That's some effective treatment!

**Comment by elkillo** [comment]
^ +1 for this

**Comment by Alaberti** [comment]
Did you...did you want it to burn? I don't want it to burn. I like my treated wood non-flammable myself. Let the peasant wood burn, not my immaculately reconstructed super-wood I say. Anyone fancy a mint julip? I'm suddenly overtaken with a mighty thirst.

**Comment by James-T-Oudvoure** [comment]
Why not make it a configuration option if it burns or not?

**Comment by James-T-Oudvoure** [comment]
Either make it configurable or just make it not flammable period. It didn't used to be flame-retardant, and since real treated wood can still burn, it makes sense for this treated wood to burn.

**Comment by mindforger** [comment]
cresosote impregnated wood is normally fire proof

**Comment by James-T-Oudvoure** [comment]
Well, BluSunrize said that it shouldn't burn.

**Comment by mindforger** [comment]
that is what he said, what i said was my opinion to this

**Comment by Alaberti** [comment]
Once the cat is out of the bag...but yes, back to the topic at hand, is this actually a bug, as in the wood should burn but doesn't? Or is this a request to make non-burning wood burn?

**Comment by James-T-Oudvoure** [comment]
Yes. It's a bug. Treated wood should burn, I remember it burning in previous versions.
