### ISSUE TITLE
[Suggestion] Make single-block mode for drill

### ISSUE THREAD

**Issue by abculatter2** [BluSunrize/ImmersiveEngineering#1183]
Similar to the chem thrower's pilot light mode, it would be nice if the drill had its shift-clicking single-block-breaking functionality replaced with a mode that can be toggled with a shift-rightclick.

**Comment by James-T-Oudvoure** [comment]
What purpose would this serve exactly?

**Comment by elkillo** [comment]
i believe the reason it doesn't is that its suppose to be a multi block mining solution and not a single block one as that is basically a pickax.For convenience sake it might be useful.

**Comment by abculatter2** [comment]
If that were the case, then the shift-clicking for single block mode shouldn't exist. I personally wouldn't mind if it were removed and you had to use a pickaxe for single blocks, though.
