### ISSUE TITLE
[Question] Aluminium Scaffoding can't use Carpenter's Blocks

### ISSUE THREAD

**Issue by karakufire** [BluSunrize/ImmersiveEngineering#1186]
I favour using steel scaffoldings into carpenter's blocks. but saddly, aluminium scaffoldings can't do.
I have a question in there. Why this problem happen?

**Comment by BluSunrize** [comment]
I assume this is on 1.7.10?

**Comment by karakufire** [comment]
Yes, this happend in 1.7.10.

**Comment by BluSunrize** [comment]
It's something to do with block solidity, how blocks are flagged as opaque and full blocks.
Btu to be entirely honest with you, I don't care about fixing such minor things for 1.7.10. My development focus has moved to the newer versions of Minecraft, so this won't get addressed in the near future.

**Comment by karakufire** [comment]
Thank you for answering. I only wondered what deffernce between steel and aluminium scaffoldings.

**Comment by mindforger** [comment]
probably a forgotten line ;D you can look at both files in the repository side by side, maybe you can pinpoint the difference in their attributes :D
