### ISSUE TITLE
Messed up textures in IE Version 0.7.7

### ISSUE THREAD

**Issue by BigFear** [BluSunrize/ImmersiveEngineering#1187]
As you can read in the title, I got messed up textures. 
The MV Transformers or the LV Wire Connector for example. I also made a screenshot, to show you my current problem... D: I tried to use another texturepack or version but the problem kept showing up.
![2016-06-10_17 02 50](https://cloud.githubusercontent.com/assets/19859708/15969707/73ab9bfc-2f31-11e6-9132-3dcfdeea179f.png)

**Comment by malte0811** [comment]
What other mods are you using? Especially ones like Optifine?

**Comment by BigFear** [comment]
Well, that's what I'm calling fast reply!!! I am currently using optifine and oder 289 Mods in the so called Resonant Rise 3 Pack.

**Comment by malte0811** [comment]
Try removing optifine and see whether the problem goes away. Optifine is not supported by IE, as it should say in the contributing guidelines that also should have told you to add a mod list when you first reported this bug.

**Comment by BigFear** [comment]
Well, that actually did the job for me. Thank you very much :+1:
