### ISSUE TITLE
StackOverflow on server restart

### ISSUE THREAD

**Issue by AlterAkima** [BluSunrize/ImmersiveEngineering#1189]
Forge 11.15.1.1890 || IE 0.8-27
Whenever we reload the server, a tank in the world crashes.
The culprit tank is connected to a Buildcraft fluid pipe with a gate, may be the cause.
http://pastebin.com/7SUb2vaR

**Comment by malte0811** [comment]
There are a many crashes like this one, all have the same cause: On 1.7.10, `master()` returned `null` if the current TE was the master, now it returns `this`. I'm going through all methods that call `master()` right now to fix them.

**Comment by Eufranio** [comment]
When it will be released? I play with Alter and we are just waiting for this to play...
