### ISSUE TITLE
[1.8.9] Engineer's Toolbox - game crashes when I try to put in shears

### ISSUE THREAD

**Issue by nlharlowe** [BluSunrize/ImmersiveEngineering#1194]
I searched the issues and didn't see this listed, figured I'd report it. The crash only seems to occur when I try to put the shears into the toolbox. The shears had been used a couple of times, so the durability bar was not maxed, if that helps. Reproduced twice. The toolbox takes TiCon tools just fine, as well as the IE hammer. This happened on a single player world.

Here's the crash log: http://pastebin.com/ZCBKK501

Edit: A few more details - turns out the crash happens when trying to put in other vanilla materials into the "Anything" section of the toolbox. I've been putting them in via shift click. Putting them in manually doesn't crash. Shift click still works with IE stuff and TiCon tools, just not with vanilla stuff, and possibly anything that would go in the misc storage in the toolbox.

**Comment by malte0811** [comment]
#1168
Known and fixed for the next release.
