### ISSUE TITLE
Having trouble making silos FTB Infinity

### ISSUE THREAD

**Issue by heavyp** [BluSunrize/ImmersiveEngineering#1195]
As far as I know I'm using the correct build plan. 4 treated fence posts with aluminum sheet metal block in the middle. then 5 hollow layers with a 3x3 on top. I'm using the engineers hammer everywhere but the silo wont show. Anyone else having issues? Help is appreciated. Thanks

**Comment by elkillo** [comment]
trying using it the hammer on the very bottom aluminium sheet metal block. If that is a no go then try to make sure something isn't out of place im sure you built it correctly but we got to check everything.

**Comment by BluSunrize** [comment]
I need a picture. And teh block you have to click is one of the middle blocks of the 2nd layer.

**Comment by heavyp** [comment]
![silo](https://cloud.githubusercontent.com/assets/5709681/16051603/6c1d3b7a-322e-11e6-85ed-c395b38f1f6a.jpg)
First level

**Comment by heavyp** [comment]
Yes, I have been right-clicking on the bottom middle block. I've clicked all the blocks haha

**Comment by heavyp** [comment]
![image](https://cloud.githubusercontent.com/assets/5709681/16051653/a0ccc750-322e-11e6-8e1f-cd0d355e1c06.png)
2nd layer and hollow except for top

**Comment by heavyp** [comment]
![image](https://cloud.githubusercontent.com/assets/5709681/16051701/d236f81a-322e-11e6-9c0e-e8dfe07f21e6.png)
Before final 3x3 top layer

**Comment by heavyp** [comment]
![image](https://cloud.githubusercontent.com/assets/5709681/16051757/17233556-322f-11e6-8a39-2a73cc430cec.png)

**Comment by heavyp** [comment]
Sorry to spam. Just being detailed.

**Comment by heavyp** [comment]
GOT IT!
![image](https://cloud.githubusercontent.com/assets/5709681/16052713/69ac67b2-3233-11e6-8891-1322613559f1.png)

I was helping my friend... He was using Aluminum sheet metal instead of just plain ol' iron sheet metal. Sorry to waste your time and thanks for the awesome mod!

**Comment by BluSunrize** [comment]
*facepalm*

Fair enough, glad you figured it out!

**Comment by elkillo** [comment]
Oh and here i forgot it had to be iron! Sorry about that
