### ISSUE TITLE
Railgun doesn't zoom, or use RF.

### ISSUE THREAD

**Issue by Insufficient-Charge** [BluSunrize/ImmersiveEngineering#1196]
I only checked the railgun. I do not have the upgraded capacitors upgrade on my railgun, just the zoom function. I hold shift and the "scope" pops up, but when I scroll I see the bar on the right go up, but I don't get a zoom. So it's basically useless.

Later, I looked at the gun's internal buffer of RF, and it did not go down.

**Comment by BluSunrize** [comment]
If you'd read the guidelines, you'd have saved me asking these questions:
What version of Minecraft + IE?
Do you use Optifine?
What modpack/other mods are you playing with?

**Comment by Insufficient-Charge** [comment]
No optifine. 1 version behind, but the changelog only said something about potion ID's. I am playing with a large amount of mods, would you like me to look for some specific ones?

**Comment by BluSunrize** [comment]
You still didn't tell me what version of Minecraft >_>
Check if you are using Modular Powersuits for instance.

**Comment by AlterAkima** [comment]
I can confirm the not using power part, but not the zoom, on 1.8.9, latest release.

**Comment by Insufficient-Charge** [comment]
Minecraft 1.8.9, sorry, it's been a while since I reported a bug...and yes,
I do have Modular power suits.

**Comment by BluSunrize** [comment]
Try removing MPS and Numina and see if you can reproduce it.

**Comment by BluSunrize** [comment]
To clarify: I can reproduce neither the lack of power consumption, nor the lack of zoom. I need more info, pictures and reproduction instructions to clarify this issue.

**Comment by Insufficient-Charge** [comment]
Finally got myself updated to the latest version on Curse forge. Power is being used, however...
Before:
![2016-06-20_21 27 49](https://cloud.githubusercontent.com/assets/13188566/16216763/182de4ba-3733-11e6-9cc8-2fc5e2080138.png)

After:
![2016-06-20_21 27 55](https://cloud.githubusercontent.com/assets/13188566/16216772/23121a0e-3733-11e6-8175-1df031ecbd46.png)

**Comment by mindforger** [comment]
now try without as requested :)
PowerSuits mess with the Zoomstate of Minecraft and can lead to this Issue

**Comment by BluSunrize** [comment]
And that is WHY I said try it without Numina and MPS. Not "report it again showcasing the same issue" >_>

**Comment by mindforger** [comment]
additional hint or maybe a solution, go into NUMIA config and disable the FOV-Fix

**Comment by mindforger** [comment]
@BluSunrize i threw a bug report over to the NUMINA guy to make it's tweak off by default or adding an option or maybe API, let's see how that goes :)

i found several other topics over the internet blaming NUMIA, but you can disable the FOVFix in their options, it was because of the PowerSuits Zooming like craszy when on 200% walkspeed

**Comment by BluSunrize** [comment]
Why is still open anyway? Lol.

**Comment by mindforger** [comment]
dunno, to let people know about the option in optifine ? :D
