### ISSUE TITLE
Please identify a license

### ISSUE THREAD

**Issue by xarses** [BluSunrize/ImmersiveEngineering#1197]
Please add a LICENCE file or the like. Without one, your code while posted publicly, may not be copied, modified, distributed, or used. If you aren't sure which license to apply, please see helpful sites like http://choosealicense.com/

**Comment by BluSunrize** [comment]
...nope? I get to do whatever I want with my code, If I don't clarify a license, that's ym choice. I don't let myself be pressured into it either.

**Comment by xarses** [comment]
That's completely fine. You have complete control over what you do with your code. I'm just asking you to clarify your stance in your repo. This is useful to clarify how others can interact with your code.

In your case, its still useful to clarify this by asserting your Copy-rights (you have them by default). Again you don't have to do anything.

**Comment by BluSunrize** [comment]
I do infact have plans for a custom license, I just haven't gotten around to writing it yet. As it currently stands the lack of license means all rights reserved.

**Comment by gdude2002** [comment]
Did you end up getting around to this?
