### ISSUE TITLE
[1.8.9] Water wheels, The bane of FPS and summoning of satan.

### ISSUE THREAD

**Issue by UnstableCodeScarlet** [BluSunrize/ImmersiveEngineering#1199]
Basically, I was hooking up some water wheels, and the  water leaked on to my second dry wheel, caused some lag, and as soon as I took the water off teh second wheel, the before relog puu.sh happened. After relogging, the after relog happened, and fps was fine.

Before Relog: http://puu.sh/pwTE4/b4837713dd.jpg

After Relog: http://puu.sh/pwTO0/c99262e8bf.jpg

**Comment by malte0811** [comment]
Should be fixed for the next version.
