### ISSUE TITLE
Suggestion: dimension blacklist for pump.

### ISSUE THREAD

**Issue by delet3r** [BluSunrize/ImmersiveEngineering#1202]
I realize I probably represent a small minority, but it would be great if you could blacklist dimensions with the Pump, instead of just making it run like an enderthermic pump to reduce lag from pumping nether lava.  BC pump works this way, you can just make it not work in the nether.  

The 'convert to stone' works well for players who like pumping nether lava but it is worse for those of us who pump out lava lakes near bedrock in the overworld.  Instead of making more ores visible, it covers them in stone.  Again, I realize my opinion is probably not the most common one.

**Comment by malte0811** [comment]
There used to be a feature in 1.7.10 that would have helped you event though it was completely different from a blacklist, but it apparently got lost while porting to 1.8: Pumps could be individually set to produce cobblestone or not by shift-rightclicking them with an engineer's hammer (this only worked when 'convert to stone' was enabled). @BluSunrize did that feature just get lost or did you intentionally remove it? If it got lost accidentally I'll re-add it

**Comment by BluSunrize** [comment]
It got lost, that is my bad x3
I totally forgot about it too. If you wanna port it back in Malte, be my guest.
