### ISSUE TITLE
Machine builder 

### ISSUE THREAD

**Issue by Dijkstra1** [BluSunrize/ImmersiveEngineering#1203]
I love that IE uses multiblock structures for all of it's machines, the only thing is I am constantly open the book to see what needs to place where, I have to ideas that would make building machines easier, the first idea, block that one place can cycle IE machines, and show a ghost block in world as guide, or second idea and block that when machine pattern has been set, right clicking with the hammer will place the blocks needed from your inventory, or says you are missing block x.

**Comment by mindforger** [comment]
i am preeeetty sure this was discussed earlier and i mention to remember either me or somebody els throwing the ghost block rendering from botania in to this topic but i can't find it nor can i remember the outcome anymore

**Comment by BluSunrize** [comment]
Yes, Mind found it.
Verdict hasn't changed. It's only a 5x5x5 structure and half of that is air. It's not /that/ hard to remember.
