### ISSUE TITLE
Curse Forge description is misleading

### ISSUE THREAD

**Issue by Insufficient-Charge** [BluSunrize/ImmersiveEngineering#1205]
Well, from what I've seen, Ic2 power doesn't work for the IE cables. However, the description for the mod in Curse Forge says that it does. It also says that it uses RF, when it sorta has a new thing called IF, which doesn't seem to connect to other machines alien to IE...Unless you use a capacitor with an RF cable coming out of the output side.

**Comment by escman1999** [comment]
what version of IE are you using?

**Comment by malte0811** [comment]
Ic2 compat: #1087
Yes, it may be a good idea to tell people about IF and RF.

**Comment by BluSunrize** [comment]
Yeah the Curse Forge description is still relevant to 1.7.10
I shoudl probably update it.
