### ISSUE TITLE
Thermoelectric generators causing alot of lag.

### ISSUE THREAD

**Issue by Insufficient-Charge** [BluSunrize/ImmersiveEngineering#1206]
Well, when I had some running my bc quarry, and since they were chunk loaded...
I ran around looking for IE stuff because this lag only happened after I updated IE. Removing the thermoelectric generators killed the lag. I am using the latest version on Curse Forge.

**Comment by Insufficient-Charge** [comment]
It seems to only lag when I had my uranium blocks around it. But then I tried placing them back down again, and as far as I can tell, no more lag.

Maybe it's just a conversion from Old IE -> New IE lag. Hmm.

**Comment by Insufficient-Charge** [comment]
Uhm, ok, this is Pneumaticrafts fault. Again, a false issue report...Sorry :(

**Comment by mindforger** [comment]
sorry for stretching this issue, but do you have a link to this issue with Pneumaticraft? I am interested in your problem as i have issues with Pneumaticraft too and struggle to find any info or a place to report stuff
