### ISSUE TITLE
Light comes through concrete.

### ISSUE THREAD

**Issue by Insufficient-Charge** [BluSunrize/ImmersiveEngineering#1207]
I litterly just went to 3 diffrent mod authors about this and was totally wrong. I hope this is correct...

I had a lot of lag in my world after I updated IE. At first I thought for some reason Pneumaticrafts etching acid was effecting my performance. Well, no.
My base is over an ocean. The entire floor is concrete. When I updated, light could go through concrete, so that is what was making me lag, was the updates under my base.

Unfortunately this means when you fix this, there will be more lag, but at least it will be fixed... >.<
:D

**Comment by BluSunrize** [comment]
Dude. You have opened like 3 issues now. Can you at least read the friggin guidelines once and give us info on the versions and other mods you use?!

**Comment by Insufficient-Charge** [comment]
Well, it's the latest version on Curse Forge, which is 0.8-27, and, as I said before, I have many mods in my modpack, and would you like me to look for any specific ones? I do have MPS and Numina, since mod authors like asking that.

**Comment by Insufficient-Charge** [comment]
Don't know what mod would make IE's concrete let light shine through, since when I updated the pack IE was the only upgrade.

**Comment by mindforger** [comment]
open your game (to be sure make a copy) and while ingame,. press F3+C (minimum 6 seconds) to force a crash and then post it on gitbash or pastebin and put a link here
only the crashlog in your crashlog folder not the gamelog!

**Comment by malte0811** [comment]
While I agree that a mod list is a requirement for a good bug report, in this case it wasn't necessary for fixing the bug.
IE blocks return `false` in `isBlockOpaque`. Therefore the default light opacity (that is used if there is no metadata override) is set to 0 in the `Block` constructor, making all blocks translucent
