### ISSUE TITLE
[Help] coke oven action detecting

### ISSUE THREAD

**Issue by MikePotato** [BluSunrize/ImmersiveEngineering#1209]
Is there any way to detect (with a **redstone signal**) if a coke oven is empty or full?

**Comment by elkillo** [comment]
if your using the 1.8.9 version a buildcraft gate can read the status of the tank. i do not believe it has native support if i'm not mistaken, otherwise trying using a comparitor next to it to see if there is a reaction.

**Comment by MikePotato** [comment]
Thank you, ill try that

**Comment by elkillo** [comment]
your welcome :+1:
