### ISSUE TITLE
Trouble with MV wire connectors

### ISSUE THREAD

**Issue by TennePG** [BluSunrize/ImmersiveEngineering#121]
When I first logged into my world when I updated to V. 0.3.1, All of the wires weren't working correctly, so I had to break and then replace them all, and then they worked. After switching dimensions, the MV wires I had wouldn't let me connect/cut wires at all, but the LV wires allowed me to do connect/cut wires. I think there may be a problem with MV wires, and maybe even HV, but I haven't gotten around to testing HV yet.

**Comment by wafflemans** [comment]
I experienced this as well. In addition to what you said, HV relays only accepted LV cables, and said all others are invalid. Breaking and replacing stops the problem.

**Comment by BluSunrize** [comment]
funnily enough, I just found that bug myself, when doing other things. Will be fixed :D

**Comment by mindforger** [comment]
another related bug maybe http://puu.sh/iEJD5/0f06027650.jpg this is a HV transformer

**Comment by BluSunrize** [comment]
Yeah, probably related to the same problem

**Comment by wafflemans** [comment]
@mindforger from what it looks like, that seems more like a graphical error that what we are describing, but never the less it is an error.

**Comment by BluSunrize** [comment]
No, fairly sure it's related. Due to the limitType, which is not being read from NBT correctly.

**Comment by wafflemans** [comment]
One more thing: occasionally the wire would disappear after exiting and re-entering the world. Might have been fixed with the other bug
