### ISSUE TITLE
[Suggestion] Secondary sources of Gunpower

### ISSUE THREAD

**Issue by ravenstormchaser** [BluSunrize/ImmersiveEngineering#1212]
One of the things i ran into with this mod is the fact that a main toy, the pistol and its ammo, uses an inordinate amount of gunpowder yet there is no mod included source of said gunpowder. 

I can understand the idea that its available in vanilla with a mob farm but the issue that creates is that the generation of gunpowder is a fraction of the output of said farm at best. Having a source of mod included gunpowder other then Creepers would be handy and keeps the tone of the mod if done right. 

My suggestion would be to add a pair of resources to the list, something simple or already in on one of the lists somewhere, maybe. Or have the alternate source be something single mob farm-able like say Blazes. That way you can make a mob farm dedicated to just one creature in a smaller more compact space and dont have to deal with the extraneous outputs from an all inclusive farm. 

Or another option is to come up with uses for the standard mob farm parts that dont currently have many/any uses like zombie flesh. 

I only suggest it as I would really like to see your mod be more self contained without having to find say another mod to use the outputs of a farm for gunpowder or to just add another way to make gunpoweder.

**Comment by elkillo** [comment]
yes this is a useful thing to have as i always feel that i dont ever have enough gun powder to use that awesome sidearm.

**Comment by abculatter2** [comment]
You can use modtweaker to add uses for mob drops yourself.

For example, one thing that I added was a refinery recipe that uses a lot of steam and creosote oil to make half as much plant oil as creosote, as a use for excess creosote. I've also considered adding a way to turn rotten flesh into small amounts of creosote, either as a coke oven recipe or more likely a fermenter recipe. You could look into this yourself.

**Comment by bookerthegeek** [comment]
@abculatter2 care to link to a pastbin of that script? 😀

**Comment by abculatter2** [comment]
http://minetweaker3.powerofbytes.com/wiki/Mods:Immersive_Engineering_Support
