### ISSUE TITLE
[Suggestion] Make Structual Arms connect to arms above and below.

### ISSUE THREAD

**Issue by ViciousVinnyD** [BluSunrize/ImmersiveEngineering#1213]
I'm loving the functionality that allows Structial Arms placed in front and behind each other to connect into a single prism.

Would it be ok if this functionality also included above and below? This would allow for some very nice long-range pylons ;3

![20160625151744_1](https://cloud.githubusercontent.com/assets/10350888/16357227/05a4bb12-3ae8-11e6-95b2-b378f8dbc789.jpg)

I was also wondering if we could also have wood structual arms? They would look godlike on my windmill ^^

Would it also mabie be possible to make structual arms climbable, like scaffolding is?

**Comment by BluSunrize** [comment]
That's 1.7.10. That's not getting any new features.
These structural arms haven't been ported to 1.8.9 yet, but I'll look into it there.
