### ISSUE TITLE
[1.8.9] Custom NPC's drop Epic Shader Grabbag with 100% chance / Bosses blacklist absent

### ISSUE THREAD

**Issue by Kyndle** [BluSunrize/ImmersiveEngineering#1214]
This issue was fixed by adding a bosses blacklist in the 1.7.10 branch, but the blacklist is non-existent in the master branch! 

Here's the previous closed issue for reference and for more information:
https://github.com/BluSunrize/ImmersiveEngineering/issues/1003

Here's the mentioned 1.7.10 commit: 
https://github.com/BluSunrize/ImmersiveEngineering/commit/05b2cb3953e0061a33f016c3c2b7bedfb9c5b99f

**Comment by BluSunrize** [comment]
Yeah commit hasn't been ported to 1.8.9 yet. I'll look into it.
