### ISSUE TITLE
[1.7.10] Computer support: no support for OpenComputers?

### ISSUE THREAD

**Issue by McSharidan** [BluSunrize/ImmersiveEngineering#1216]
Reading through the fine printed manual in-game, there appears to be "computer" support in Immersive Engineering.

Through a couple of simple tests, it turns out that only ComputerCraft is supported. OpenComputers doesnt seem to be supported. Is this an issue with Immersive Engineering or should I go ask the OC team about this?

**Comment by malte0811** [comment]
IE machines that support cc support oc (there is one exception, but that is just one method). However, it is required to use an adapter to connect the machines to the oc network. I believe it says so in the manual entry on general computer support.
Btw, cc/oc support for 1.8 is halfway done.

**Comment by McSharidan** [comment]
I was using an adaptor but it still couldnt see the IE machines. Must be a glitch in the pack then. My apologies.
