### ISSUE TITLE
Not general an Issue but i found something for you

### ISSUE THREAD

**Issue by mindforger** [BluSunrize/ImmersiveEngineering#1217]
Hi BluSunrize

i just stumbled upon the following document while surfing some issues on optifine :D

https://github.com/octarine-noise/simpledeobf/blob/master/README.md#have-optifine-will-debug

you can actually include optifine into your dev-env to have a monitor on how it is fucking up with your stuff XD

**Comment by BluSunrize** [comment]
...but I don't want to? xD
I don't support optifine. That's it. No further info needed!
