### ISSUE TITLE
[1.8.9] Storage Crates do not keep contents when broken

### ISSUE THREAD

**Issue by belathus** [BluSunrize/ImmersiveEngineering#1218]
We just updated Immersive Engineering, and we noticed that breaking storage crates now drop their contents to the ground, even when broken with silk touch. I'm guessing this isn't intended.

**Comment by malte0811** [comment]
No, that isn't intended. I derped in ac34942f774f7c0a14674aa6b06efb04e37dbf86, every item in the inventory is dropped ignoring things like the crates dropping behavior. I also forgot to mention the change in the commit.
