### ISSUE TITLE
Fluid Pipes do not insert into Railcraft blocks

### ISSUE THREAD

**Issue by chrisbecke** [BluSunrize/ImmersiveEngineering#1219]
Playing FTB: Infinity Evolved Skyblock / Expert mode. (1.7.10)

I build a Railcraft Water Siding, and connected it to a Buildcraft water tank using Immersive Engineerings Fluid Pipes and verified that the RC Water Tank does insert water into the IE pipes, which do in turn insert into fluid inventories.
This works. Nice.
Then I replace the BC tank with Railcrafts Hobbyist Steam Engine.

Problem: Water is not being inserted into the Hobbyist Steam Engine. I also tried a couple of other Railcraft blocks - such as the water siding, and while IE Fluid Pipes will accept water from RC blocks that auto eject, the pipes will not insert water. :/

**Comment by elkillo** [comment]
did you turn the hobbyist engine on? i know there is a small issue with railcraft engines not accepting water till they receive a redstone signal.

**Comment by chrisbecke** [comment]
I provided coal, and turned it on. This was a mistake as it heated up without accepting any water and I touched it with a bucket in my hand and it blew up.
