### ISSUE TITLE
1.7.10 v0.7.7 Item Silo not accepting fluids via fluid pipe

### ISSUE THREAD

**Issue by bcatly** [BluSunrize/ImmersiveEngineering#1220]
When I try to connect the fluid pipe to the item silo it will not connect at all to it. I have tried doing this at the bottom as well as at the top, right clicking it with the hammer but still it does not connect. Is this a bug or am I just doing something wrong?

[http://imgur.com/a/cFLKE](url)

**Comment by mindforger** [comment]
you sure you phrased your issue correctly ?

i mean "**fluid** pipe to the **item** silo"
this can't obvioulsy work in any way!

and you link is broken

**Comment by bcatly** [comment]
Ah, I guess it was my mistake then. I thought both the tank and silo were capable of storing liquids but I guess not. Thanks for the help.
