### ISSUE TITLE
[1.7.10] Error on initializating IE pls help

### ISSUE THREAD

**Issue by Pandora1337** [BluSunrize/ImmersiveEngineering#1224]
Here's log file, pls help to fix it I really like this mod. 
http://pastebin.com/1HLe20Dx
What do I need to do?

**Comment by malte0811** [comment]
First of all, *read the contributing guidelines!* Your IE version is outdated by 3 versions and btw, 1.7.10 isn't supported any more.
Update IE to 0.7.7 and delete the `potions`-sections in your config.
(If you don't know what a config is: Go into your minecraft folder (where you got your crash report from and where you get screenshots), there is a subfolder called `config`. In that folder there is a file called `ImmersiveEngineering.cfg`, open that in a text editor. Scroll down until you see `potions {`. Delete this line and all following lines up to a line containing just a `}`.)

**Comment by Pandora1337** [comment]
Thank you a lot! It is working now!
