### ISSUE TITLE
[1.8.9] Disconnecting because of too large packet

### ISSUE THREAD

**Issue by petakii** [BluSunrize/ImmersiveEngineering#1227]
We play on a small modded server with 33 mods and about a week ago, we started to got disconnected. First we only got the "Disconnected" error, but later this:

"Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet 0/53 (S35PacketUpdateTileEntity) was larger than I expected, found 1 bytes extra whilst reading packet 53"

I started to disable the mods and at the end it only happened when IE was enabled. Since there's no crashlog I can't attach one. When I disable IE, nothing happens, no disconnect. Sometimes it disconnects after a few minutes, sometimes at the moment when we join. It doesn't matter if 0, 1 or 2 player are online and we sometimes got disconnected together or alone. After a few hours of testing it only happens with IE. I'm not sure but it seems that it happens around chunks where IE stuff is. (our base if pretty big and there's a lot of IE stuff there)

Installed mods:
mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
Forge{11.15.1.1902} [Minecraft Forge] (forge-1.8.9-11.15.1.1902-1.8.9.jar) 
BiomesOPlenty{3.0.0} [Biomes O' Plenty] (BiomesOPlenty-1.8.9-3.0.0.2004-universal.jar) 
BuildCraft|Core{7.2.7} [BuildCraft] (buildcraft-7.2.7.jar) 
BuildCraft|Silicon{7.2.7} [BC Silicon] (buildcraft-7.2.7.jar) 
BuildCraft|Transport{7.2.7} [BC Transport] (buildcraft-7.2.7.jar) 
BuildCraft|Builders{7.2.7} [BC Builders] (buildcraft-7.2.7.jar) 
BuildCraft|Energy{7.2.7} [BC Energy] (buildcraft-7.2.7.jar) 
BuildCraft|Robotics{7.2.7} [BC Robotics] (buildcraft-7.2.7.jar) 
BuildCraft|Factory{7.2.7} [BC Factory] (buildcraft-7.2.7.jar) 
Chameleon{1.8.9-1.1.2} [Chameleon] (Chameleon-1.8.9-1.1.2.jar) 
correlatedpotentialistics{0.2.3_01} [Correlated Potentialistics] (CorrelatedPotentialistics-0.2.3_01.jar) 
ImmersiveEngineering{0.8-28} [Immersive Engineering] (ImmersiveEngineering-0.8-28.jar) 
IC2{2.3.262-ex18} [IndustrialCraft 2] (industrialcraft-2-2.3.262-ex18.jar) 
inventorytweaks{1.60-40-e06e29a} [Inventory Tweaks] (InventoryTweaks-1.60-40.jar) 
JEI{2.28.18.186} [Just Enough Items] (jei_1.8.9-2.28.18.186.jar) 
journeymap{1.8.9-5.2.3} [JourneyMap] (journeymap-1.8.9-5.2.3-unlimited.jar) 
jeresources{0.4.0} [Just Enough Resources] (JustEnoughResources-1.8.9-0.4.0.23.jar) 
malisiscore{1.8.9-2.1.6} [MalisisCore] (malisiscore-1.8.9-2.1.6.jar) 
malisisdoors{1.8.9-3.1.4} [MalisisDoors] (malisisdoors-1.8.9-3.1.4.jar) 
mantle{1.8.9-0.9.2.jenkins102} [Mantle] (Mantle-1.8.9-0.9.2.jar) 
Morpheus{1.8.9-2.0.58} [Morpheus] (Morpheus-1.8.9-2.0.58.jar) 
cfm{3.6} [MrCrayfish's Furniture Mod] (MrCrayfishFurntiureModv3.6.1(1.8.9).jar) 
smf{1.4} [Scarab's Missing Furniture Mod] (smf-1.4.jar) 
StorageDrawers{1.8.9-2.6.4} [Storage Drawers] (StorageDrawers-1.8.9-2.6.4.jar) 
storagenetwork{1.11.1-final} [Storage Network] (StorageNetwork-1.8.9-1.11.1-final.jar) 
Baubles{1.1.3.0} [Baubles] (Baubles-1.8.9-1.1.3.0.jar) 
Thaumcraft{5.2.4} [Thaumcraft] (Thaumcraft-1.8.9-5.2.4.jar) 
Waila{1.6.0} [Waila] (Waila-1.6.0-B3_1.8.8.jar) 
WailaHarvestability{1.1.7} [Waila Harvestability] (WailaHarvestability-mc1.8.x-1.1.7.jar) 
wawla{1.1.4.168} [What Are We Looking At] (Wawla-1.8.9-1.1.4.171.jar) 
denseores{1.0} [denseores] (denseores-1.8-alpha-2.0.3.jar) 

It happend with and without Optifine too.

Java and Forge and IE is the latest on all machines.

**Comment by malte0811** [comment]
Please either

- upload the whole save to dropbox or somewhere similar or

- (if the file is too large): Go to [https://dinnerbone.com/minecraft/tools/coordinates/](https://dinnerbone.com/minecraft/tools/coordinates/) and enter the coordinates of your base. In your save, in the folder `region`, you should find the file the linked tool specified. Upload that file AND the `level.dat` file (root folder of the save) to somewhere.

Once you have uploaded the file(s), post the links here or, if you don't want them to be public, you can send them to me by Email (address is on my github page) or PM them to @BluSunrize on IRC (#bluSunrize on esper.net)

Is that pack available for download anywhere? Everyone is lazy, so if I can download it by pressing one button I'd rather do so than download every mod by itself.

**Comment by petakii** [comment]
Here's everything you need: https://drive.google.com/open?id=0Bw3iaCSlghnDQUtZdFpWc2NPQkU

The base is around x: -1477 y: 103 z: 554, I attached a JourneyMap waypoint in case you are using it.

I hope you'll find something :) Thanks for the help!

**Comment by malte0811** [comment]
I did "some" testing and found that the bug went away after removing the drive bay from Correlated Potentialistics. 
@unascribed do you have any idea what could cause this and do you still maintain 1.8.9? I looked at the NBT data involved and it didn't look weird, even though it is quite a few layers deep:
![nbtdrive](https://cloud.githubusercontent.com/assets/10406104/16708977/bc070588-4603-11e6-92b8-11149471902a.png)
Another thing I noticed is that [this](http://pastebin.com/sy9dtfNv) stacktrace is written to the client log for each drive inside a drive bay when the bay is broken.

**Comment by petakii** [comment]
I took out the drill from the terminal and the bug was gone for a while, but when I disconnected with the drill in my inventory, other players got dropped down and the server went into an infinite loop of errors. After restarting the server we got instantly dropped for 4-5 times and we can join only after that. And the same restarts when I disconnect. Other players can join, but gets the original packet error and get disconnected.

**Comment by unascribed** [comment]
I'm still doing bugfixes for 1.8.9, but new features (like the one I'm working on at the moment) won't be backported.

The NBT for the drive bay looks fine — the way I do drive syncing is a bit strange, I'll look into this.

**Comment by malte0811** [comment]
@unascribed I have found a pretty minimal setup for reproducing this bug:
![2016-07-09_21 41 43](https://cloud.githubusercontent.com/assets/10406104/16709902/12df199e-461e-11e6-8906-7123cf38ede1.png)
The drive has to be filled to some amount, I am not exactly sure how much (I use a 1k drive with roughly 550 bytes filled). The left interface is not configured, the right one is configured to export jungle wood (just some random item). Putting jungle wood into the left interface causes the disconnect about 1/4 of the time. The bug seems to fix itself after some disconnects, so it may be necessary to restart the server frequently.
@petakii Your ore processing system forms a loop, conveyors going up have to have a solid block beneath them. That causes a loop of iron ore, the 2 interfaces in your system behave exactly like my setup. You can close this issue since it isn't related to IE.

**Comment by unascribed** [comment]
So wait, it's the interfaces? That's kinda weird...

**Comment by petakii** [comment]
Interesting, because I have used that ore processing system for a while without any loop, maybe it updated since. This system is heavily WIP as I'm lack of space. Anyways, thanks both of you for the help :) Sorry for opening it in IE, but as I mentioned it worked without it, at least we reminded unascribed :D
Closing it.
