### ISSUE TITLE
inquiry regarding 1.9 & 1.10+

### ISSUE THREAD

**Issue by kotoroshinoto** [BluSunrize/ImmersiveEngineering#1229]
I am curious as to the intent as far as minecraft & forge version updates going forward.

It seems the mod community is gradually shifting away from 1.8. 

I assume the current focus is porting from 1.7.10 to the system used in new versions, but I know little about the changes that ocurred from 1.8 -> 1.9 -> 1.10 etc.

Are these ports going to be relatively easy when the time comes?

Its somewhat sad how fractured the mod versioning is becoming, with some mods not even having broken away from 1.7 and others still being stuck on 1.8. It is becoming difficult to create interesting mod combinations with the newer versions of minecraft that one might want to be using.

That being said i'm not blaming you or demanding rapid pacing, i'm simply curious as to what should be expected in the future. I am well aware that mojang has been releasing updates at fairly rapid pace and that that is hard to keep up with.

**Comment by BluSunrize** [comment]
1.9 is coming in due time. That is all.
