### ISSUE TITLE
[1.8.9] Crash when breaking multiblock with Optifine installed

### ISSUE THREAD

**Issue by petakii** [BluSunrize/ImmersiveEngineering#1232]
Originally posted this to sp614x/optifine#224, but seems it's not optifine's fault.

The game crashes when breaking a multiblock structure, but only happens with optifine installed. All other nearby players are dropped down too.

Crash log:
http://pastebin.com/VipmuuWM

**Comment by malte0811** [comment]
Did you read the bloody contributing guidelines? If it only happens with Optifine, it isn't a valid bug. And I personally think that this is Optifines fault, I will post a comment in their tracker in a minute.

**Comment by petakii** [comment]
Yes, I've read that and thats why I first posted to their repo. I wrote here too because of the answer I got there.
