### ISSUE TITLE
Aluminium processing (suggestion)

### ISSUE THREAD

**Issue by Louddy** [BluSunrize/ImmersiveEngineering#1233]
Hi, I really like that you used bauxite ore instead of "aluminium ore", and I would like to go thought and finish what has been started. It would be really nice to have a process close to the real aluminium processing.

Bauxite ore could go into the crusher to make alumina dust( skipping some part of the process but this is minecraft( if you want to know we are skipping a part where we heat the bauxite dust(mixed with water) with steam to remove slicon and skipping a part where we add NaCl to separate aluminite and other stuff(regarding those two steps that would require a lot of work we could just add a mold press that has nacl and separates the dust, or just skip them like I initially suggested)). 

Then the alumina dust could go into an "aluminium smelter" which pours the alumina dust into reduction cells( heating them a lot and passing current through the cell to separate the O3 in alumina from the Al2O3 and thus create a aluminium.

I know this is a lot of work for both the devs and the players just to make aluminium process more realistic but because of mods that use aluminium ore, all of my friends though pure aluminium existed in the nature. If you go though and uae these suggestion, the "aluminium smelter" could be renamed to "electrolitic reducer" and serve other purpose such as creating hydrogen from water.

Thank you for your attention, if you have any questions don't hesitate to contact me.
xaviergenereux@hotmail.com

Sources: http://www.aluminiumleader.com/production/aluminum_production/
https://en.m.wikipedia.org/wiki/Aluminium_oxide

**Comment by Louddy** [comment]
If this isn't the right place for suggestion please let me know

**Comment by KnightMiner** [comment]
The thing is, all other ores just require smelting to process, which is not realistic for most of them. From a gameplay perspective, I don't want to set up a complicated system just to process aluminim, or any single ore really. It might be fun as a build, but shouldn't be required.

**Comment by Louddy** [comment]
Many ores like copper or gold exist in a natural pure state and only require smelting. The complete process of aluminium could result in making some huge benefits for the players, e.g. like 4 aluminium for 1 bauxite ore, keep in mind that many player run modpacks wich allow "aluminium ore" to be smelted in furnaces. So yes, it would not be required.

**Comment by BluSunrize** [comment]
You're looking for gregtech. You won't find it here.
I refuse to go that far out with the realism, because I don't feel like it would enhance my gameplay experience.
I made specific choices of calling the ore "Bauxite" and never using "Aluminium Powder" but "Grit" instead (because powdered Aluminium kinda burns your face off)
But an entire processing queue just for that one ore? No sorry, I dislike that.

**Comment by Louddy** [comment]
Even though I appreciate your quick response, it kinda feels bad that you didn't read my entire suggestion, also I dislike gregtech so that's why I posted here, the idea I wanted to elaborate was more of the introduction of a single machine like the "electrolitic reducer" that could have other use.
I agree with you that a line of machine for one ore would be a pretty bad idea. Anyway keep up the good work your mod is great.

**Comment by BluSunrize** [comment]
I did read the full suggestion. It'd be foolish to reply if I didn't.
Your only other suggestion was "making hydrogen", and I have no use for hydrogen atm, nor really interest in it. Therefore, the machine would have one single use, leading me back to my argument.

**Comment by Louddy** [comment]
It's cool man thank you for your time, sorry for the false accusation. Also I wanted to know, is there a list of the planned upcoming changes or just any planned upcoming changes?

**Comment by Louddy** [comment]
Also the machine could be used to separate other things such as bronze into copper and tin. But right now I realize that you are right and it's a bit too complicated for aluminium (also it's not that usefull atm).
