### ISSUE TITLE
[1.7.10] Error in console

### ISSUE THREAD

**Issue by MJRLegends** [BluSunrize/ImmersiveEngineering#1234]
I get this message in the console for my mod pack, http://pastebin.com/UWRFUTqQ Personally i blame IC2/Simply Jetpacks for this error but is there anything i can do to bypass it or could you add a patch?

**Comment by MJRLegends** [comment]
Would a config refresh help me here? Just a thought

**Comment by AEnterprise** [comment]
it's just the arc furnace recipe profiler that is trying to analize armor for recycling but in the first one something is going wrong and the rest have recipes that are not regular crafting, the game should still run fine

**Comment by MJRLegends** [comment]
Ok so how can we fix the first issue?

**Comment by AEnterprise** [comment]
does it need fixing? the server should just run fine, it seems to me like some mod is messing with the oredict but iirc the handler is pretty robust in that if for whatever reason it fails the rest should still work fine

**Comment by MJRLegends** [comment]
Yeah it works fine, but i dont like to see errors in the console

**Comment by MJRLegends** [comment]
I can try and remove mods and load it up and see which mod is the issue causing IE to error on it
