### ISSUE TITLE
energie splitting and transformator cable burn problem

### ISSUE THREAD

**Issue by Kenshij** [BluSunrize/ImmersiveEngineering#1235]
ImmersiveEngineering-0.7.7.jar
immersiveintegration-0.6.8.jar
played in Revolution|3 Modpack (ATLauncher)

two problems, simple setup -> HV transformator, full HV capacitor, two empty MV capacitor

first problem, cable burns :
with transformator in the middle HV cable to transformator, MV cable to first MV capacitator
-> all ok
from first to second MV capacitator wiring with MV cable
-> the MV cable from transformator to first capazitator burns
=> transformator outputs to much rf in cable, but book say lowes cable counts

second problem, connector not splitting equal :
put MV connector on the ground, wire with MV cable and connector the full capazitator and the two empty capazitator to the connector on the ground (or line empty capazitator in a row)
-> only one capazitator is charched, but book says connector split energy equaly

**Comment by Louddy** [comment]
Also experiencing this, the energy doesn't split correctly.

**Comment by malte0811** [comment]
I have fixed the energy not splitting correctly, that was a derp in one of my previous commits. I can't reproduce the first issue though, can you please send a screenshot of your setup and the value of `Cable transfer rates` in the IE config file.

**Comment by Kenshij** [comment]
# The maximum length cables can have. Copper and Electrum should be similar, Steel is meant for long range transport, Structural Rope & Cables are purely decorational
    I:"Cable length" <
        16
        16
        32
        32
        32
     >

    # The percentage of power lost every 16 blocks of distance for the cable tiers (copper, electrum, HV, Structural Rope & Cable(no transfer) )
    D:"Cable loss" <
        0.05
        0.025
        0.025
        1.0
        1.0
     >

    # The transfer rates in RF/t for the cable tiers (copper, electrum, HV, Structural Rope & Cable(no transfer) )
    I:"Cable transfer rates" <
        256
        1024
        2048
        0
        0
     >

You connect the cable to the capacitator first, and in the end you connect them to the transformator.

Have tested ist with LV cable and an capacitator and preheater, same problem, the connector overloads the cable.

![2016-07-20_11 37 24](https://cloud.githubusercontent.com/assets/11033477/17020483/1af31c52-4f42-11e6-9046-f92b18604db8.png)
![2016-07-20_12 24 07](https://cloud.githubusercontent.com/assets/11033477/17020482/1af18176-4f42-11e6-9e57-cfdb08ebfb52.png)

**Comment by sassenach1** [comment]
Kenshij, I notice that elsewhere you are using the revolution pack, and that the config you posted seems to be from there as well. I've had similar problems as well, and decided to test identical set ups using Revolution and Vanilla + IE. Whereas the Revolution setup would burn up wires as a device reached RF capacity, the identical setup on vanilla+IE would be fine. 

I would therefore suggest that this is more a pack issue than a de jure Immersive Engineering one. Furthermore, swapping out the Revolution IE config for the default config seems to solve the issue. If you wish, then, to simply avoid the wire burn out issue you might swap out the config. If you wish to investigate the source of the issue, the config seems to be what you would investigate.

**Comment by Barhandar** [comment]
>I suspect this might be the root of the problem.

It's not the root, it's the symptom of a problem in IE's code that is not uncovered with default settings. By description IE wiring should be impervious to splitting to consumers, and burn if too much power is _provided_, instead. Basically, if only a single connector is on a power generator, wiring should never burn. If there are two connectors, the actual avail of the generators involved needs to be checked, and if it combined is higher than wire capacity, _then_ it should burn (and if avail of a single generator is higher than the connector's throughput, it would be nice if the connector reflected it visually, i.e. became "glowing red" from power attempting and being unable to pass through).

**Comment by mindforger** [comment]
first of, this is 1.7.10 and power systems have changed a lot since this necrotic issue has been edited last :)

second, RF is push based and as far as i understood the wire code, it remembers the power that has been pushed through it and accumulates this with ever push in this tick, when the power pushed exceeds the limit, it simply burns! It depends on the connectors attached that limit the inrush and the push capacity of the inputting device

please correct me if i am wrong
