### ISSUE TITLE
Power Generation

### ISSUE THREAD

**Issue by Louddy** [BluSunrize/ImmersiveEngineering#1238]
I wanted to know if you are happy with the power generation you are offering at the moment, ( By happy I mean you don't want to add anything new.) If you do take ideas for new unique power generation that will, I think fit with this mod, just comment, I have few (they are pretty balanced tbh).

**Comment by laz2727** [comment]
A reactor is coming (probably).

**Comment by PrincessRTFM** [comment]
Will there ever be any solar power? We've got wind and water, might as well complete the passive power trio.

**Comment by Louddy** [comment]
IMO solar powet doesn't really fit the retro/industrialistion style of IE but if the concept is good it could be interesting.

**Comment by KnightMiner** [comment]
I've never been a fan of mod added solar panels, it's basically just crafting a few items then you have free power, no need for an interesting system or any additional maintenance/resource consumption

**Comment by Louddy** [comment]
This is just an idea, and I have a few concepts for it, but I think it would be cool to get more of the hydroelectric type of generation, like some sort of hydroelectric dam. I believe that it would be possible to make it a good source of power like it is irl but also pretty balanced since it would require late game materials. It could be a good use for concrete and would require a lot of steel (like all IE multiblock do haha). The power generated could work with a sort of pressure system with the water contained behing the dam. @BluSunrize what do you think?

**Comment by elkillo** [comment]
personally i Already build dams out of hempcrete and using water mills. Maybe a steel higher speed watermill maybe feasible? or maybe adding some sort of maintenance for the kinetic dynamos in the form of seed oil lubricant for the steel water/wind mills. just my 2 cents on the topic, tough i agree with louddy about solar not fitting well unless it was used with a boiler tower to redirect heat to a steam tower. and the panels themselves would need to multi-blocks or at least there needs to be a lot em.

**Comment by bookerthegeek** [comment]
Factorization has a nice solar boiler setup.
