### ISSUE TITLE
HV Connectors have negative RF value

### ISSUE THREAD

**Issue by Crystalyx** [BluSunrize/ImmersiveEngineering#1239]
![2016-07-15_22 15 20](https://cloud.githubusercontent.com/assets/8289541/16892946/e675f7bc-4b3e-11e6-995c-0ad2ac415bf0.png)
![2016-07-15_22 14 47](https://cloud.githubusercontent.com/assets/8289541/16892945/e6749386-4b3e-11e6-8014-d08abbc13f33.png)

**Comment by malte0811** [comment]
Did you even look at the contributing guidelines? Modlist, version of IE and MC and steps to reproduce are missing.

**Comment by Crystalyx** [comment]
ModPack - SpaceAstronomy 4.7 + ProjectE-1.7.10-PE1.10.0+StevesFactoryManager-A90
Immersive Engeeniring-0.7.7

**Comment by AEnterprise** [comment]
i have noticed this in alot of different IE versions as well, it seems to heapen when your machines are drawing more power then you are providing and have quite alot of machines drawing power. i'm not on the latest IE versions though

**Comment by malte0811** [comment]
I assume you don't have some sort of small reproducible setup for this bug?

**Comment by ReikaKalseki** [comment]
I have the same issue, and it appears that once a connector goes negative, it turns into something of an RF black hole...

![](http://i.imgur.com/EN1KKJS.jpg)

**Comment by malte0811** [comment]
You probably don't have some sort of reproducible setup either? Because having such a thing would be really helpful.
(Just as a note, I will not be working on IE and probably not even respond to github comments for the next 3 weeks.)

**Comment by ReikaKalseki** [comment]
My setup is somewhat unstable in its power draw, and is thus not really truly reproducible. It consists of an ME system, the engines pictured, some Forestry biomass engines offscreen, and a few TE/EiO machines. The ME system load varies wildly, as does steam supply.

**Comment by AEnterprise** [comment]
@malte0811 there is no 'easy' reproducable setup, from what i've seen it heapens when you have a unstable system where your power input keeps up most of the time but when your system suddenly requires alot more power this can heapen

**Comment by malte0811** [comment]
It is possible that 244d69e29145595f47c28ec2cbc01326dbd7a60d fixes this, but since I can't replicate the issue I am not sure. @AEnterprise you said you noticed this in multiple versions. Can you specify which ones? More specifically, have you seen this happen before version 0.7.5?

**Comment by AEnterprise** [comment]
@malte0811 i have seen this before but on 1.7.10 i have not realy used IE much on 1.8+

**Comment by ReikaKalseki** [comment]
> a unstable system where your power input keeps up most of the time but when your system suddenly requires alot more power

This describes my case accurately. I am also on 1.7.10, and cannot and will not try 1.8+.
