### ISSUE TITLE
[1.8.9] Excavator's bucket wheel rotates into the wrong direction

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#1241]
... including sideways ^^
Seems that the direction of the rotation is fixed and independent of the excavators orientation.
![derpywheel](https://cloud.githubusercontent.com/assets/7753414/16927706/0ff80944-4d2f-11e6-8bf9-e9e2623ccca9.png)

MC 1.8.9, Forge 1902, IE 0.8-28, JEI 1.8.9-2.28.18.186, InventoryTweaks-1.60-40  (no optifine)

**Comment by KnightMiner** [comment]
I don't see an issue with sideways rotation, whatever works to mine the ores :P

**Comment by MalkContent** [comment]
it can also be backwards though, dragging the buckets with their bottoms through the dirt. that can't be effective, can it? :P

**Comment by mindforger** [comment]
please add your version of minecraft and IE to your report and also chekc for the presence of optifine and test it without optifine installed first, also polease not the link to the contribution guidelines https://github.com/BluSunrize/ImmersiveEngineering/blob/master/CONTRIBUTING.md

**Comment by MalkContent** [comment]
done
