### ISSUE TITLE
[Suggestion] machines that need maintenance emit redstone signal

### ISSUE THREAD

**Issue by tod** [BluSunrize/ImmersiveEngineering#1243]
I love the idea that the machines need maintenance every once in a while, like the electrodes in the arc furnace. However, it would be nice if we could somehow detect that maintenance needs to be done. My thought is that it emits a redstone signal from some part of the machine. That way we can hook up an alarm system. (An IE themed alarm would be awesome too. Something like the nuclear control howler alarm.)

**Comment by UndeadZeratul** [comment]
Reminds me of how GT had you going into the maintenance panel to replace some piece that was faulty or something similar.  Having some way of presenting that information to the player is important, so having a specialized port emit a redstone signal would be good to allow the player to hook up whatever they want to the machine to display maintenance being required, however having an IE solution would be nice as well.
