### ISSUE TITLE
Suggestion: conveyor belts responding to redstone signal

### ISSUE THREAD

**Issue by pagameba** [BluSunrize/ImmersiveEngineering#1245]
It would be really useful to be able to stop conveyor belts in some situations, perhaps by applying a redstone signal.  This would allow 'buffering' items in chests and releasing them when a machine is ready to accept more items.

**Comment by PrincessRTFM** [comment]
I think Blu's already said no to this, but maybe an ejector block that spits items out from an adjacent inventory and is disable by redstone signal would be workable?

**Comment by pagameba** [comment]
Interesting, that was sort of what I was thinking originally - a kind of 'trapped' chest that conveyors or other pipes could only extract from when it receives (or doesn't receive) a signal.  I was thinking of it in conjunction with my incinerator suggestion ( #1244 ) as a way of buffering items to be destroyed and having a manual release to send them in, kind of a safety net!

Then I thought it would be more generically useful to apply the logic to conveyor belts.  You can think of conveyors as the equivalent of item pipes found in other mods, most of which have some mechanism for control via redstone.

But if the author is not interested then no worries ... can always rig up something with vanilla hoppers, just less convenient :)
