### ISSUE TITLE
[1.7.10] Crash when using Gregtech 6

### ISSUE THREAD

**Issue by Dukat863** [BluSunrize/ImmersiveEngineering#1248]
When connecting Kinetic Dynamo's Output side, and a _full_ LV Capacitor's _Output_ side, the game crashes immediately and when loading, thus making the world unusable.

The crash log mentions this:

```
java.lang.NoClassDefFoundError: gregtech/api/interfaces/tileentity/IBasicEnergyContainer
    at blusunrize.immersiveengineering.common.util.compat.GregTechHelper.gregtech_isValidEnergyOutput(GregTechHelper.java:142)
```

Setting B:"Enable Compatmodule: gregtech" to false in ImmersiveEngineering.cfg does not fix this problem.

Here's the crash log:
[crash-2016-07-24_00.40.56-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/379986/crash-2016-07-24_00.40.56-server.txt)

**Comment by malte0811** [comment]
There are, for some reason, 2 different config options dealing with GT support. The one you disabled is responsible for recipes etc, I don't know whether that part is compatible. The config option you need to disable is somewhere in the `general`-section of the config, it is about converting RF to GT EU.

**Comment by Dukat863** [comment]
Thanks, setting B:"GregTech Compatability" to false fixed it.

However, this option should then be set to false by default, to prevent future issues like this until it is fixed.
