### ISSUE TITLE
[1.7.10] missing wire

### ISSUE THREAD

**Issue by LemonNick** [BluSunrize/ImmersiveEngineering#1250]
I have on the server is the world skyblock. If this world is to place the wires , then the server is rebooted , they disappear . In the ordinary world works.
Version IE 0.7.5

**Comment by mindforger** [comment]
can you reproduce this issue with 0.7.7 ? Are there other mods installed? please Press and hold F3 + c for minimum 6seconds to force a crash and append the crashlog as attachment or via pastebin for an overview of your mods

**Comment by LemonNick** [comment]
Upgrading to 0.7.7 did not help. I have several worlds : world, skyworld, nether. The problem is only observed in the world. And in the nether, skyworld - wires disappear after a server restart . Bugs do not have any , crash too. 
The player puts the wire . Reboot the server . Wire disappeared . 

No chunk loaders do not use
