### ISSUE TITLE
[Potential Issue] [URGENT] Power doesn't transmit through LV, MV, or HV Wires

### ISSUE THREAD

**Issue by iancbogue** [BluSunrize/ImmersiveEngineering#1252]
I downloaded a world by DrRageHard, from his Surviving With Immersive Engineering Series. Power was working fine in his videos, but as soon as I open it up, (and I have tested this is a world of my own) no power is transmitted. I have WAILA, and when I look on any of the connectors, I see that there is no power being transmitted. Now this is interesting: the very first connector **after** the power source (eg: Kinetic Dynamo) has full power stored _in_ the connector. This is very weird. Any help?

**Comment by talbiston** [comment]
I am seeing the same problem. release 0.10 - 54 .. I can place a capacitor block directly on a Dynamo and it will charge or a charged capacitor directly on an external heater or pump etc ... and power will pass but if i try and use connectors and wires then no power will pass.

**Comment by BluSunrize** [comment]
could you provide pictures please?

**Comment by ThatGuy435** [comment]
@BluSunrize 

I'm able to replicate this on 1.12.2 with Forge 14.23.0.2512, no other mods besides Immersive Engineering, verified capacitor charge with the Engineer's Voltmeter: https://imgur.com/a/ucgv7

Dynamo puts out power as evidenced by the LV Capacitor direct attached (input hidden between) but it never makes it to the second capacitor.
