### ISSUE TITLE
[1.7.10] Launcher Crash and Re-occuring Error

### ISSUE THREAD

**Issue by catz28** [BluSunrize/ImmersiveEngineering#1253]
Hi I'am kind of new to modding in Minecraft and have installed Minecraft Forge version 1.7.10 but every time I launch the game it crashes even though I am solely running ImmersiveEngineering. Help please.
http://pastebin.com/y6JHwY0J     Pastebin crash report link

**Comment by BluSunrize** [comment]
You're using an outdated version of Forge. Update forge and you should be good to go.

**Comment by catz28** [comment]
Now the launcher will not open after I click launch and the java does not load, should I be more patient and wait or is there something else?

**Comment by BluSunrize** [comment]
What exactly did you do?

**Comment by catz28** [comment]
I think forge is the problem as when I start the launcher with forge nothing opens

**Comment by BluSunrize** [comment]
That is not an answer to my question. If you want help, I'll need details. Did you update Forge, if so, to what version?

**Comment by catz28** [comment]
i downloaded the latest forge version 1614

**Comment by BluSunrize** [comment]
And it does not even produce any errors?
Vanilla launcher, MultiMC or another launcher?

**Comment by catz28** [comment]
Hi I was using another launcher and that was the problem so I downloaded another launcher called Mc-Launcher

**Comment by BluSunrize** [comment]
From personal experience: Use vanilla or MultiMC. They are easy to handle and not prone to breaking.

Anyway, issue resolved, hopefully.

**Comment by catz28** [comment]
Thank you so much! I changed the launcher and updated the forge and now it works perfectly! After 2 hours of play through I would like to say great mod!
