### ISSUE TITLE
[Suggestion] Steam power

### ISSUE THREAD

**Issue by Azormik** [BluSunrize/ImmersiveEngineering#1255]
My idea is that you can make steam using a boiler of some sort that can be filled with water buckets using some kind of dispenser or manually and it has to be heated with coal or another type of fuel. The steam pipes could be made out of copper and made a little skinnier compared to the other pipes mainly for aesthetic purposes . Some machines I thought of are pistons powered by steam that can be controlled with a pump/valve and the pump/valve has to be powered with another source of power from IE. The pistons can be pushed higher than a normal vanilla piston (1-7 blocks) and maybe there can be platforms that you can add to extend the movable area sort of like slime blocks. Maybe a 5x5 - 7x7 area can be the max size. 
Another Machine I thought of is a filling station similar to the water filling station but instead of water it fills containers with steam as well as weapons powered with steam (read my other post about weapon ideas). There could also be steam storage tanks and smaller variants that you can throw as a type of explosive/concussion grenade if you combine it with slag or nuggets.
There could also be steam vents that could be used for decoration or defense (steam can burn) and pipe openings that work like note blocks and they sound like an organ.

**Comment by BluSunrize** [comment]
IE is not getting a steamboiler, I've clarified that multiple times.
