### ISSUE TITLE
setting excavator vein size to -1 results in config error.

### ISSUE THREAD

**Issue by toric55** [BluSunrize/ImmersiveEngineering#1256]
this setting:

# The maximum amount of yield one can get out of a chunk with the excavator. Set a number smaller than zero to make it infinite
I:"Excavator: Mineral Depletion”=-1
leads to this:
[01:39:15] [Client thread/ERROR]: An exception occurred while loading config file ImmersiveEngineering.cfg. This file will be renamed to ImmersiveEngineering.cfg_20160805_013915.errored and a new config file will be generated.

no other errors, in IE 0.7.7 sorry if its not mutch help. also tried with a space between = and -, just incase =- was a special operator (no java experience.) exact same error.

**Comment by BluSunrize** [comment]
YOU STILL DIDN'T INCLUDE THE FULL LOG. >_<
I literally told you that that one line of the log told me nothing. Yet that is still all you gave. Come on man, details!

**Comment by toric55** [comment]
oh. thought your just meant any errors proceeding before and after. setting up example instance now. wont clutter up the log with other things.

**Comment by BluSunrize** [comment]
No, you will. I want the full log. On pastebin or another site. If you omit information, that is not helping.

**Comment by toric55** [comment]
http://pastebin.com/8ef3C5Af

sorry. just thought setting up an IE only instance would clean up some junk from unrelated mods.

**Comment by BluSunrize** [comment]
Yep there you go. There is an issue in the config file and it's probably not the -1
Would you please pastebin your config file as well? The errored one that is.

**Comment by mindforger** [comment]
haha i bet i see it from here, i am pretty sure you are using the wrong quote character, do not use any fancy schmancy editor like wordpad, plain ol text editor does it's job here most perfect

@BluSunrize besides him posting the whole logfile, look very very close at his post, those are 2 very different quote symbols

**Comment by BluSunrize** [comment]
Yep. That's what I figured. Hence why I want the config.

**Comment by toric55** [comment]
http://pastebin.com/MnCfr41u

funny. simply using textedit. about as simple and editor as you can get...

**Comment by toric55** [comment]
http://pastebin.com/Ma15pe4M

**Comment by toric55** [comment]
aand its working. of course. anyway, thanks for putting up with me and helping me figure it out.

**Comment by toric55** [comment]
thanks for the tip.
