### ISSUE TITLE
Failing to save NBT for entity CapabilityHandler_CartShaders.serializeNBT

### ISSUE THREAD

**Issue by Tickbuz** [BluSunrize/ImmersiveEngineering#1258]
There is consistent failure to save a chunk with an entity from IE which I could not understand.
Minecraft 1.10.2 with Forge 12.18.1.2045. Using IE 0.10-30 compiled from source.
Error log: http://pastebin.com/1r8QSbfw
Can provide further testing if necessary.

**Comment by BluSunrize** [comment]
Yeah, welcome to the fact that this is a prebuild and not officially released. Long since fixed.

**Comment by Tickbuz** [comment]
Didn't mean to offend. Just thought about testing the build. Sorry for any inconvenience.
