### ISSUE TITLE
[1.10][minor] Crusher does not stop spinning when disabled

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#1260]
When an active crusher is disabled via OpenComputer commands the blades remain spinning however the crusher otherwise acts as expected.

Steps to reproduce:
1. Build, power, and provide iron ore(any vanilla ore seems to cause this) to a Crusher
2. Attach a properly configured OpenComputer to the Crusher's RS port
3. Disable the Crusher via the LUA command 
   `component.ie_crusher.setEnabled(false)`
4. Observe the spinning blades

Example setup:
![image](https://cloud.githubusercontent.com/assets/3110986/17467051/b937fcfe-5cce-11e6-97f6-03fe0811c750.png)
# 

using IE 0.10-35 built against commit b6a1895
FTB Unstable version 4.2.6

EDIT: this also seems to occur if the Crusher runs out of power in the middle of an operation

**Comment by malte0811** [comment]
Is this happening on a dedicated server, an integrated server or both?

**Comment by theunkn0wn1** [comment]
I discovered this issue while playing around on a integrated server, nothing fancy. I'll attempt to reproduce this on a dedicated server when I get the chance.

**Comment by theunkn0wn1** [comment]
This issue does not seem to occur on a Dedicated server, only in the integrated server
