### ISSUE TITLE
Dupe glitch with engineer workbench, need 2 players

### ISSUE THREAD

**Issue by vadimyer** [BluSunrize/ImmersiveEngineering#1261]
ImmersiveEngineering version: 0.7.5.
Server version: Thermos B55

Here's the process:
1) Player #1 has 3 diamonds, opens up the workbench, places them to any slot.
2) Player #2 opens up the workbench, shift+click (or just click - didn't test it) and the diamonds are in his inventory now. Player #1 doesn't see the diamonds anymore, but he can click on the empty slot where they were and get the diamonds to his inventory as well.

**Comment by mindforger** [comment]
is this reproducible with normal forge ? cauldron and such modded servers are not supported

**Comment by vadimyer** [comment]
I'll try this on plain forge.

**Comment by SFort** [comment]
I can confirm that this bug is still in
ImmersiveEngineering:0.10-57
Forge: 12.18.3.2254

**Comment by BluSunrize** [comment]
Yet the question of it being Sponge, Cauldron or otherwise serversoftware related was never solved. More details.

**Comment by SFort** [comment]
Normal forge and i don't think any mods would change anything to do with this

**Comment by mindforger** [comment]
pleas epress and hold F3 + C until you crash and uipload that crashlog to pastebin and post it ... how sould one reproduce this without knowing the other mods ... or you reproduce it with ONLY IE installed ... then you can claim that other mods have nothing to do with it

**Comment by SFort** [comment]
Sure thing,
[Pastebin](https://pastebin.com/83tr4yS8)
Would have gladly done a clean test if this did not require two players to test.
