### ISSUE TITLE
Floodlight CTD on placement

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#1263]
Mabie related to #1262?
Issue: Client crashes when a floodlight is placed into the world.
[CrashLog] (https://gist.github.com/theunkn0wn1/79901809c8f64d451207f61884e60180)

-----------------------
MC version 1.10.2, IE build b6a1895

**Comment by AppleYay** [comment]
are you sneak clicking to place the floodlight or not. For every crash of mine, I have not been sneak clicking when I use the hammer on it.

**Comment by theunkn0wn1** [comment]
No, just placing the block, though our two *might* be related.

**Comment by AppleYay** [comment]
Actually, testing this in a new instance and noticing in any case the floodlights don't function nor have textures, it seems they are not done. I reviewed the code for floodlights and quite a few notes say the same.

**Comment by BluSunrize** [comment]
It's not even officially released yet, for flips sake ._.

**Comment by AppleYay** [comment]
I thought that was odd since past versions allowed me to use it :c

**Comment by theunkn0wn1** [comment]
It's not at release yet, not everything is done yet. I just didn't expect a
crash to come of this.

**Comment by clurect** [comment]
I got the same issue.
This crashlog is when I placed it: http://pastebin.com/PYtPytE3
This is when the server restarted: http://pastebin.com/vKSWSvY8

**Comment by BluSunrize** [comment]
See other linked issue
