### ISSUE TITLE
Soaryn says hi.

### ISSUE THREAD

**Issue by rbandboy** [BluSunrize/ImmersiveEngineering#1264]
Excavator's Bucket Wheel does not render - WAILA does render that the wheel has formed as the multiblock.

**Comment by BluSunrize** [comment]
What he doesn't even report it himself now? Disappointing.

**Comment by WayofTime** [comment]
We already gave rbandboy heck in chat, don't worry.

**Comment by BluSunrize** [comment]
Fair enough. Next time, read the damn contribution guidelines. You are notified of them when filing an issue, so respect them.
