### ISSUE TITLE
Visual Rendering Bug (with apologies to BluSunrize)

### ISSUE THREAD

**Issue by rbandboy** [BluSunrize/ImmersiveEngineering#1265]
My apologies to BluSunrize, his work is amazing and I should not have been so careless in posting on his github in a mocking tone.
Using ImmersiveEngineering-0.8-32.jar
(as well as JEI and waila)

In an attempt to recreate Soaryn's missing bucketwheel render bug, I discovered a visual rendering glitch in creating excavators.  Sadly, I was not able to recreate Soaryn's issue directly, but found an issue that ties at least in some part to what might have caused the issue.

![2016-08-09_17 51 49](https://cloud.githubusercontent.com/assets/4001839/17537637/93a23ffc-5e5b-11e6-876a-0fd7b17aa0e9.png)
^This picture did not have a completed wheel when forming the structure.
![2016-08-09_17 55 34](https://cloud.githubusercontent.com/assets/4001839/17537640/a4fe28ba-5e5b-11e6-9315-51a33c77f1c1.png)
^The visual render remained after breaking the multi-block.

While the machines are quite robust and resilient when one click is applied to the heavy engineering block that allows the multi-block excavator to form, the visual issue reveals itself when holding the activation of the engineer's hammer across multiple blocks in the multi-block structure, in particular when other blocks are selected first, then the action is held going to the activation block.

![2016-08-09_17 55 24](https://cloud.githubusercontent.com/assets/4001839/17537665/d6d54576-5e5b-11e6-8434-dfb31f502e40.png)

Break and replace fixes the visual glitch, and I assume (due to insufficient testing) that the excavator works as intended regardless of the rendering.

---

Again, my apologies for posting such a terrible bug report.  It was intended in humor, as the joke was floating around to delegate the issue of posting bugs to Github to someone else in chat.  I apologize if my initial posting may have caused anger or frustration.

**Comment by mindforger** [comment]
i remember fastcraft doing funny things on clientside and even when only used on serverside with lighting

**Comment by rbandboy** [comment]
The pack that I tested this on was not using Fastcraft.  Essentially, I made a curse instance that pulled forge, IE, JEI and Waila.

**Comment by BluSunrize** [comment]
Where would a curse instance pull IE from? O_o

**Comment by rbandboy** [comment]
I don't know where Curse pulls its mods from for building modpacks, but https://mods.curse.com/mc-mods/minecraft/231951-immersive-engineering lists 0.8-32 as the most recent release build.

**Comment by BluSunrize** [comment]
Oh right. Sorry. I thought you were dealing with a 1.10 build, not 1.8. Nevermind me. xD

**Comment by rbandboy** [comment]
I could probably build a 1.10 instance if IE had an alpha listing...

**Comment by porteriscool** [comment]
I dont know if this counts as another visual bug, but here is an example that Soaryn encountered that I clipped 30 seconds for you to see the problem/bug, i dont know what is happening xD. https://clips.twitch.tv/soaryn/VictoriousWormBlargNaut

**Comment by rbandboy** [comment]
The reason why this report is named "(with apologies to BluSunrize)" was because of a joke bug report that I posted of the render issue that was absolutely terrible during Soaryn's stream - this was my attempt to re-create the issue.

**Comment by BluSunrize** [comment]
Comment has been deleted. Proper bug reports, and on the correct topic, if you'd please.
