### ISSUE TITLE
Item not named as it should 

### ISSUE THREAD

**Issue by 00danx** [BluSunrize/ImmersiveEngineering#1266]
The name for the railgun is inconsistent to its real live variant. If one fallows the crafting recipe with uses coils, to launch projectiles, it should be called a Coilgun. The railgun uses metal sleds on eider sides of the projectile to induce a magnetic flux, as the projectile completes the circuit. Propelling it forwards.

**Comment by BluSunrize** [comment]
And that is why, if you read the manual, you would have discovered that "Railgun" is a nickname given to what is actually a "Portable Induction Catapult".
Check your facts.
