### ISSUE TITLE
[1.10] Interface bug with revolver reloading

### ISSUE THREAD

**Issue by AsukaLangleyfag** [BluSunrize/ImmersiveEngineering#1269]
![2016-08-14_03 25 57](https://cloud.githubusercontent.com/assets/8681532/17645967/0a837868-61cf-11e6-9307-7d4ccdc3ffa7.png)
![2016-08-14_03 26 23](https://cloud.githubusercontent.com/assets/8681532/17645970/0f46073a-61cf-11e6-9593-7a766aac77f4.png)
I have: Optifine, latest Forge (2061), BetterFps, Mekanism, Jei and Psi.

**Comment by theunkn0wn1** [comment]
Please remove Optifine and attempt to reproduce. 
Blu does NOT give support to users with Optifine or the related mods.

Also, unable to reproduce using the FTB Unstable pack(current) against b6a1895f80d5aedfa385096711b82e671c4d00ae

**Comment by theunkn0wn1** [comment]
I error-ed when testing, issue is valid as optifine is not the trigger as i am testing without it.

Description:
The revolver behaves in rather unexpected and clearly unintended ways including but not limited to the rendering glitch stated in the OP.

Steps to reproduce:

1. make/spawn in a revolver
2. place revolver into a workbench and add the **Extended magazine** to it
3. remove revolver and place it in the hotbar as to equip it like any tool.
4. Attempt to load revolver ( i suggest shift-clicking for maximum effect)
![image](https://cloud.githubusercontent.com/assets/3110986/17646990/41387bb4-6194-11e6-9ac8-ea69158c02a5.png)

**Comment by BluSunrize** [comment]
I am reasonably sure that I know what causes this.
The server side of the GUI opens before the client side, and updates the container item. As a result (since this GUI doesn't contain the upgrades), the client revolver is temporarily only aware of its bullets, but not its upgrades.
Can you reproduce this on a server, or is it SSP only?

**Comment by BluSunrize** [comment]
Actually, nevermind
found the actual problem and fixed it!

**Comment by BluSunrize** [comment]
durr, should leave this open for a commit

**Comment by theunkn0wn1** [comment]
Guess saying it is reproducible with a dedicated server is a little late?

**Comment by BluSunrize** [comment]
Yup =P
