### ISSUE TITLE
Crash using NEI with hemp seeds

### ISSUE THREAD

**Issue by pja1982** [BluSunrize/ImmersiveEngineering#127]
Both Crash when using NEI to view recipes using hemp
http://pastebin.com/7MFDUZPY
http://pastebin.com/6cHqShsX

**Comment by BluSunrize** [comment]
You should report this to @Tonius since it says "neiintegration" in the stacktrace.

**Comment by pja1982** [comment]
Fixed with latest NEI-Integration
