### ISSUE TITLE
[1.7.10] Engineer's Toolbox cannot hold TiCon tools in the tool slots

### ISSUE THREAD

**Issue by Zsashas** [BluSunrize/ImmersiveEngineering#1272]

**Comment by malte0811** [comment]
This has been added in 1.8.9 and I believe @BluSunrize said that there won't be any more 1.7.10 versions unless something breaks really badly, so this probably won't be backported.

**Comment by BluSunrize** [comment]
Correct. 1.7 is feature complete, issue closed.
