### ISSUE TITLE
[1.7.10] wires and wooden post disappear after reload or dimension change.

### ISSUE THREAD

**Issue by JFMillerUSA** [BluSunrize/ImmersiveEngineering#1277]
When are you going to update for 1.7.10 I'm using version 7.7

**Comment by mindforger** [comment]
when you got a reproducible world to download with only IE installed it would be probably possible

you could also present some more details about sour setup, maybe screenshots or a forced crashlog (F3 + c for 6 seeconds) so we could see what your setup is :)

but with this less details there is no chance of finding any error and it is announced that only critical bugfixes will be made for 1.7.10

**Comment by SteamDragon** [comment]
Same is Valid for 1.10.2 0.10 - 44

**Comment by SteamDragon** [comment]
![2016-10-07_21 24 21](https://cloud.githubusercontent.com/assets/2781806/19201268/a521409a-8cd5-11e6-8234-4e0c2f4f0147.png)
