### ISSUE TITLE
[1.10] Wires and Connectors render as black (lighting issue)

### ISSUE THREAD

**Issue by mezz** [BluSunrize/ImmersiveEngineering#1280]
![2016-08-18_16 15 46](https://cloud.githubusercontent.com/assets/916092/17793902/c4a3a324-655f-11e6-81a1-7517dbe4d839.png)

This is on FC with the latest 1.10 build.
Any wire or connector I place is black as in the screenshot.
Relogging does not resolve the issue.

**Comment by BluSunrize** [comment]
Yeah, known issue. Still figuring out how to reproduce and fix it .~.

**Comment by VermillionX** [comment]
I'm also getting this, but only for connectors. Additionally, the connectors are invisible if optifine is installed.
I think it may be caused by having connectors attached to non-IE machines.

**Comment by BluSunrize** [comment]
Renderissues related to optifine won't be catered to.
Them beign black without is known.

**Comment by mindforger** [comment]
"Them beign black without is known."
maybe their rendering state is sensed as "obstructed by something" and probably dropped by optifine for FPS reasons !?

**Comment by BluSunrize** [comment]
Honestly, I think it's the vertex format. Still haven't gotten around to looking at that

**Comment by devilunaworkshop** [comment]
I did run into same issue.

![2016-08-28_20 25 49](https://cloud.githubusercontent.com/assets/21285218/18035911/e974644c-6d5f-11e6-956a-742cc11cc935.png)

No optifine thou (also cable rendering bug).

**Comment by BluSunrize** [comment]
Fixed thanks to #1341
