### ISSUE TITLE
[1.10] Hammering to construct a multiblock causes inventory havoc

### ISSUE THREAD

**Issue by mezz** [BluSunrize/ImmersiveEngineering#1282]
![2016-08-18_16 30 32](https://cloud.githubusercontent.com/assets/916092/17794076/32e42268-6561-11e6-89f1-b78ca717f88d.png)
![2016-08-18_16 30 41](https://cloud.githubusercontent.com/assets/916092/17794077/32f8850a-6561-11e6-9244-a12726daa800.png)

Before and after screenshots of hammering a Blast Furnace into becoming a multiblock.
My armor disappears and is replaced with items from my inventory.
If I try to craft anything in my player inventory it looks like it works, but if I open any other intenvory (besides the one opened with E) it will show that nothing was crafted and my items are back to how they were before.
As a workaround, relogging fixes this issue.

**Comment by mindforger** [comment]
please attach a forced crashlog by pressing F3 + C for 6 seconds
there may be mod interactions

**Comment by mezz** [comment]
I was able to reproduce with just IE.

![2016-08-18_23 39 49](https://cloud.githubusercontent.com/assets/916092/17801143/26f463e6-659d-11e6-9569-e961952ba664.png)
![2016-08-18_23 39 54](https://cloud.githubusercontent.com/assets/916092/17801144/26f4726e-659d-11e6-91df-e1f963ab573a.png)

Forced Crashlog:
https://gist.github.com/mezz/508381d8d1d101edc39dc5f6786d20d1

**Comment by theunkn0wn1** [comment]
Also encountering this issue and found it to be quite severe.
Renders the client completly unusable until i bounce the client by locking the items in the hotbar so they cannot be replaced with others from the inventory (or vice versa)
Forced crash log is attached below
[crash-2016-08-19_14.14.30-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/427906/crash-2016-08-19_14.14.30-client.txt)

IE build b6f01de20a1887e82147c714fd9f84d4cad020f3

**Comment by BluSunrize** [comment]
Issue is easily fixed by relogging, for one, and yes, has been a known issue for a week or so now. Working on it.
