### ISSUE TITLE
[1.10] Connectors placed against machines sometimes render facing the wrong way

### ISSUE THREAD

**Issue by mezz** [BluSunrize/ImmersiveEngineering#1283]
![2016-08-18_16 43 56](https://cloud.githubusercontent.com/assets/916092/17794303/0dee62e6-6563-11e6-9443-d1b4d102351e.png)

I placed this connector against an EnderIO capacitor.
The bounding box here is correct, it should be sideways.
If I place a block next to the connector to cause a block update, the connector will render in the correct orientation.

**Comment by BluSunrize** [comment]
nigh-impossible to find a fix for. Minecraft renders before the Tile has parsed it's facing info to the client.

**Comment by laz2727** [comment]
Make it update yourself?

**Comment by mezz** [comment]
I worked around a similar issue in Forestry by using the block states for the facing like vanilla does, means I couldn't pack multiple types of block into one though.
