### ISSUE TITLE
for1.7.10 Bug

### ISSUE THREAD

**Issue by sirohigan** [BluSunrize/ImmersiveEngineering#1284]
Sorry. There is bug.
immersiveintegration-0.7.7 for 1.7.10
Forge10.13.4.1614-1.7.10
OptiFine_1.7.10_HD_B8　OR　OptiFine_1.7.10_HD_D1

https://youtu.be/QmS6hLpe66c
Please look here.　　（これを見てほしいです。）
Depiction has become strange.　（描画が変になっています。）
Although it repaired if put again.　（もう１度入りなおすと直りますが。）
Burning effect of Blast Furnace is also invisible.　（高炉の燃焼エフェクトが表示されないです。）

0.7.5 occurred any time.　　（0.7.5でも起きました。）
Conflict with OptiFine is looks like this is the cause.　（OptiFineとの競合が原因の様です。）
Can you fix it?　　（修正は可能でしょうか？）

I'm sorry in poor English.
（下手な英語ですいません。）

**Comment by ArukaAlter** [comment]
1.7 is done. Optfine tends to break the multiblocks models and animations, it does not happens every time.

**Comment by mindforger** [comment]
also update your optifine! this issue has been dealt with on both sides but optifine still tends to fuck up sometimes

**Comment by sirohigan** [comment]
It was repaired in OptiFine_1.7.10_HD_U_D6.　（バージョンD6を使うと直りました）
Thank you for the information.　　（情報ありがとうです）

**Comment by BluSunrize** [comment]
Optifine issue that I can't, and refuse to, fix. Closed.
