### ISSUE TITLE
Crash when adding Minetweaker mod

### ISSUE THREAD

**Issue by IceT2** [BluSunrize/ImmersiveEngineering#1285]
Just added Minetweaker ver 'MineTweaker3-1.7.10-3.0.10' to my MC 1.7.10 client. The client crashes, where the client was working ok before adding Minetweaker. Since the log / crash report indicate an issue with Immersive Engineering, I was wondering if its a Minetweaker issue, or an Immersive Engineering issue ?
I've uploaded  a zip file which contains the 'latest.log' file and the crash report. Hope you can assist. 
[crash-2016-08-20.zip](https://github.com/BluSunrize/ImmersiveEngineering/files/428174/crash-2016-08-20.zip)

Many thanks .......

**Comment by BluSunrize** [comment]
You need to use 3.0.10b

**Comment by IceT2** [comment]
Apologies, I didn't know there was a later version. I tried your suggestion & it worked. Many thanks.
