### ISSUE TITLE
[1.8.9][0.8-32] Pipes connect to Coke Ovens, but are useless

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#1286]
Immersive Engineering 0.8 - 32
Forge x1902
MC 1.8.9
As far as I can tell, the only way to extract creosote oil from a Coke Oven using IE is by placing a Fluid Pump directly next to the Coke Oven and supplying it with a redstone signal, like you would to have a pump pick up fluid-blocks from the world.
Connecting a Fluid Pump to the Coke Oven indirectly via pipes does nothing and pipes on their own neither (the latter being intentional, judging by other issues).  
So either it's a bug that the Fluid Pump can't be connected indirectly, or pipes maybe shouldn't connect to the Coke Oven.

**Comment by BluSunrize** [comment]
Pumps can't draw indirectly. They never could. pump goes directly on the oven. Pipes connect because the oven is a valid Fluid Container

**Comment by MalkContent** [comment]
huh. i first tried pumps with barrels and had them connected indirectly there. That worked, but i suppose the fluid pump didn't enhance the throughput then :D

**Comment by Nova001Sol** [comment]
It has an internal tank, meaning pipes will connect to it. Useful for when pipes from other mods have autopull. EnderIO's fluid conduits come to mind. It's much like why item pipes connect to the bottom of a furnace despite it not outputting items itself. But regardless, I suggest you close this issue now that it has been solved.
