### ISSUE TITLE
[Feature Suggestion] Display addition in Engineers Manual

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#1288]
When looking at multiblock structures "build-manual", one can hover over the questionmark and get a list of blocks needed. If this function could also check the player inventory for these blocks and display how many you already have in a red or green number (too few/enough), that'd be sweet. Also I'd leave an amount of (0) uncolored, that way one can immediatly see that they don't have any of that block yet, just by color.

**Comment by Voxel-Friend** [comment]
I second this suggestion.

**Comment by MalkContent** [comment]
Oh! bonus would be if it could look into toolboxes :D 
and display the number like (24+9) for 24 in your inventory, 9 inside your combined toolboxes

**Comment by BluSunrize** [comment]
I added something of the likes. It adds a little tick mark if you have enough. It won't search toolboxes, I figured it'd just cause confusion for people forgetting what they have in there and then going "this is broken, I clearly don't have that block in my inventory"
