### ISSUE TITLE
[1.8.9][0.8-32] Minor: Fuel loss when tinkering on Mining Drill

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#1289]
IE 0.8-32
forge x1902
MC 1.8.9

When putting the Mining Drill with an already installed Large Tank and with Biodiesel > 2000mB (value w/o the Large Tank) into the ~~Drill~~ Engineer's Workbench, your fuel will drop to 2000mB if you modify the drill, i.e. change Drill Heads.
edit: fixed description

**Comment by BluSunrize** [comment]
The commit above only fixed this for 1.10. A 1.8 fix is coming later today

**Comment by MalkContent** [comment]
thanks for figuring out that description
also: meh :D I'm happy if it's fixed for 1.10
