### ISSUE TITLE
[1.10.2] [0.10-38] Faraday Suit Recipes are wrong.

### ISSUE THREAD

**Issue by erindalc** [BluSunrize/ImmersiveEngineering#1292]
The chest plate recipe is the one the should be for the legs, and similarly the legs recipe is the chest plate shape. The same is true with the helmet and boots.

**Comment by BluSunrize** [comment]
Ah, right, yeah, the order in teh array changed. Thanks ^^

**Comment by BluSunrize** [comment]
Fixed, see commit above
