### ISSUE TITLE
[1.10.2][0.10-38] NPE connecting to server - 1.10.2

### ISSUE THREAD

**Issue by Towsty** [BluSunrize/ImmersiveEngineering#1293]
IE: 0.10 -38
Forge: 12.18.1.2071

Loading client and server have no problems. As soon as I attempt to connect to the server, the client console is blasted with a wall-o-text, the client never connects though. Nothing crashes. I've attached the client log and the server log. Lines in question are begin around 28289.

[fml-client-latest.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/431434/fml-client-latest.txt)
[fml-server-latest.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/431436/fml-server-latest.txt)

**Comment by Towsty** [comment]
Oddly enough - this only exists when EvilCraft is also in the pack.

**Comment by Morpheus1101** [comment]
Seems im having the same issue, and its is precisely related to EvilCraft

**Comment by Morpheus1101** [comment]
EvilCraft Mod Devaloper is taking a look to see if its in his end..

**Comment by BluSunrize** [comment]
Reported to EvilCraft:
https://github.com/CyclopsMC/EvilCraft/issues/468
