### ISSUE TITLE
[1.10.2][0.10-38] Metal Rods are not oredicted as rods, only as sticks

### ISSUE THREAD

**Issue by erindalc** [BluSunrize/ImmersiveEngineering#1294]
![2016-08-22_21 11 56](https://cloud.githubusercontent.com/assets/12499779/17876973/1b3362ec-68ad-11e6-9b2a-904dd882e5ee.png)

This may well be an intended feature, but I figured I would bring it up.

**Comment by BluSunrize** [comment]
That is perfectly intentional.
