### ISSUE TITLE
1.10.2 - Conveying some bugs.

### ISSUE THREAD

**Issue by Tristaric** [BluSunrize/ImmersiveEngineering#1295]
During my first initial test of IE, faffing around with the multiblocks, I've really only come across one bug that was reportable. So uh, congrats.

(Major) 1; Both the standard conveyor and dropper conveyor spawned from the creative inventory are always turned into ghost items. Spawning them in through JEI, or through the /give command, gives a proper non-ghost conveyor, though.
(Minor) 2; The conveyors in the multiblock instruction display thing have a purple and black checkerboard pattern on it.

Side note: I did come across multiple bugs with the ammo, but I didn't report those, as I know they're being redesigned.
Cheers, mate.

**Comment by Sermax18** [comment]
Just craft in crafting table L=Leather I=Iron R=Redstone
L L L
I R I

**Comment by BluSunrize** [comment]
Fixed for upcoming release, see commit above
