### ISSUE TITLE
Suggestions for all supported versions

### ISSUE THREAD

**Issue by Tristaric** [BluSunrize/ImmersiveEngineering#1296]
The ability to rotate the multiblock display thing in the IE guide book.
I'm requesting this because there was a conveyor belt hidden behind other blocks in one of the multiblocks (Assembler)

Also, ability to mouse over the blocks on the display to see which ones they are would also be great, as I've been having troubles differentiating some of them with my bad eyesight.
Cheers, again.

**Comment by BluSunrize** [comment]
You can click and drag them, and number 2 is too hard to trace
