### ISSUE TITLE
[1.10.2] Crash On creating World

### ISSUE THREAD

**Issue by Morpheus1101** [BluSunrize/ImmersiveEngineering#1298]
When trying to make a SP world it causes the game to crash and remain in a frozen state, Crash log @ http://pastebin.com/zfaKmFbt

**Comment by BluSunrize** [comment]
I believe this is a cross-mod interaction issue. My suspicion is that one of the other mods registers "null" as an entity render
It'd be greatly appreciated if you could figure out which mod that is. The easiest way is to remove half the mods. If it works, it's an issue in a removed mod. So use that half, and remove half again. So on and so forth until you figure out which singular mod it is.
It's tedious, but helps a lot in debugging!

**Comment by Morpheus1101** [comment]
ok i'll make a start now, i more remove all mods and add in each by Alphabetically...its long...but it helps

**Comment by Morpheus1101** [comment]
Would having a Mod that removes Vanilla Gold Ore generation be the issue?

**Comment by BluSunrize** [comment]
Not at all. This looks like a render bug.
Alphabetic I wouldn't recommend. Doing the half and half thing is waaaay faster.

**Comment by Morpheus1101** [comment]
Narrowed down to 8 possible Mods

**Comment by Morpheus1101** [comment]
And the problamatic mod is EvilCraft

**Comment by BluSunrize** [comment]
probably the same issue as #1293 then

**Comment by Morpheus1101** [comment]
Quite possible by the looks of things

**Comment by c0rn3j** [comment]
EvilCraft got an update and I do not have a problem anymore.
