### ISSUE TITLE
[1.10] Some of the ores seems to be missing from the game

### ISSUE THREAD

**Issue by LordHellscream** [BluSunrize/ImmersiveEngineering#1299]
I just installed this mod to an existing world, but I was only able to find copper and nickel and cannot find any of the other ores.

Before you said it is bad luck: I have huge automated quarry that mines hundreds of blocks per minutes (using the Rftools builder quarry), I've been doing this over a couple of hours, all I got (from this mod) are copper and nickel.

**Comment by mindforger** [comment]
do you have ore retrogen active? does your COFH Core override ore gen by chance ?
maybe https://github.com/BluSunrize/ImmersiveEngineering/issues/180 works for you

**Comment by malte0811** [comment]
Is COFHCore even available for 1.10?

**Comment by Sasikaa** [comment]
The COFHcore is dead? This mod is not updated 1.8, 1.9, 1,10...

**Comment by LordHellscream** [comment]
I realized what's going on: my quarry automatically pump the ores into my processing operation (using SAG mills for crushing) , it appears that the crushing process of iron and other vanilla ores sometimes produce copper and nickel powders, that's why i'm getting those ingots.

Now I moved my quarry several hundreds blocks away this time im ACTUALLY getting the ores

**Comment by BluSunrize** [comment]
Oh, so you didn't turn on Retrogen. That'd do it. Issue solved then?
