### ISSUE TITLE
[1.10.2][0.10-38] Water Wheels kill fps

### ISSUE THREAD

**Issue by VermillionX** [BluSunrize/ImmersiveEngineering#1301]
Both with and without optifine a single waterwheel completely destroys fps (250+ fps down to 10-20 fps). The effect becomes worse the with more wheels.
Similarly, windmills do the same but deal nowhere as much damage to fps as the water wheels.
This occurs whether the wheel is turning or not, and even when it's not attached to a dynamo.

**Comment by BluSunrize** [comment]
Yeah, known. Got an idea for fixing it already.

**Comment by BluSunrize** [comment]
Should be a little better in future releases. Alas, there is not too much I can do about it, that is just how the new rendering affects performance .~.
