### ISSUE TITLE
Conveyor Belt 'magnet' pickup

### ISSUE THREAD

**Issue by the-creamster** [BluSunrize/ImmersiveEngineering#1302]
After hearing that the conveyor belts are keeping there items in the presence of a magnet; heard it to be fixed with the enderio magnet. So i decided to test other 'magnets'

Results:
- Botania ring of magnetisation(standard & upgraded one) picks up items
- BM sigil of magnetism picks up items

**Comment by BluSunrize** [comment]
and if you properly read the changelog, you'd be aware that Blood Magic's is to change in the future, I have talked to Way. Botania compat is coming back, with it will magnet prevention.
