### ISSUE TITLE
(1.10.2) Breaking Barrels crashes the game

### ISSUE THREAD

**Issue by Pihrra** [BluSunrize/ImmersiveEngineering#1305]
Using IE 10.38 for MC 1.10.2, the game crashes after breaking a barrel connected to a refinery with fluid pipes. The save then refuses to reload. Hopefully I have a backup.

http://pastebin.com/M7469a5j

**Comment by mindforger** [comment]
for a workaround, if you have mcedit, you can open the save game, teleport to the location and delete the fluid pipes and the barrel for once and get your game running again 

but mcedit is vanilla based, so you may have to guess which block is which :)

**Comment by Pihrra** [comment]
I would've tried that but since I have a literally a 1 minute old backup it's just easier/faster to just roll back but thank you ;-)

**Comment by BluSunrize** [comment]
Should be fixed in future releases
