### ISSUE TITLE
[1.10.2] invisible connectors

### ISSUE THREAD

**Issue by MrEvilCookie** [BluSunrize/ImmersiveEngineering#1306]
invisible Lv. Mv and Hv connectors(( 
![2016-08-23_14 25 10](https://cloud.githubusercontent.com/assets/20132158/17890258/8efe071e-693d-11e6-81bb-ae12e2f4e98d.png)

**Comment by mindforger** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/1280

**Comment by BluSunrize** [comment]
Are you using Optifine?

**Comment by MrEvilCookie** [comment]
yup

**Comment by MrEvilCookie** [comment]
without optifine my game is crashing(( . please cane you fix this?

**Comment by mindforger** [comment]
please post the crashreport (via pastebin or as attachment, not as wall of text please)

**Comment by MrEvilCookie** [comment]
oops , no crash report(( 
![crashes](https://cloud.githubusercontent.com/assets/20132158/17908922/08d80718-698b-11e6-8147-168f68d871f5.JPG)   P.S. sorry my system in Russian(

**Comment by mindforger** [comment]
"without optifine my game is crashing" "oops , no crash report" there is something wrong with your logic 
please go into your logs folder of your client installation, remove all logs, fire the game up **one time** and then post the log
i smell an out of memory problem with default options

**Comment by MrEvilCookie** [comment]
I have allocated 6gb of RAM and the game now not crashing )) but in singleplayer 5 fps(

**Comment by mindforger** [comment]
hold F3 + C for 6 seconds (maybe more when you are lagging hard) this forces a crash and a crashlog that you can post, maybe we can fiddle it out if BluSunrize does not mind to go slight off topic here

**Comment by MrEvilCookie** [comment]
http://pastebin.com/bpkFVTst

**Comment by mindforger** [comment]
i see quiet a few mods present that may not be required client side and are just for fashion...
is FTBUtils reuired on client side?
maybe remove dynamic surroundings for testing purpose?

DONT FORGET TO BACKUP BEFORE EDITING YOUR MODLIST

it looks as your mod list is not tested very well to harmonize as many mods have interactions that do not work quiet well and optifine is able to lighten the issues but brings in other incompatibilities

**Comment by MrEvilCookie** [comment]
I assembled my modpack in curse client for 5 minutes)
