### ISSUE TITLE
[1.10.2] No Animation When Powered - Blast Furnace Preheaters

### ISSUE THREAD

**Issue by SwordKorn20** [BluSunrize/ImmersiveEngineering#1307]
Hi I'm not 100% sure if this is a bug or I'm just being crazy, but there's no noise or animation to tell if the Blast Furnace Preheaters are actually working. So figured I would at least mention it.

**Comment by BluSunrize** [comment]
Yeah they didn't have an animation in 1.8 either. No news there =P
