### ISSUE TITLE
[1.10.2] Diesel Generator Crash

### ISSUE THREAD

**Issue by MasterGeneral156** [BluSunrize/ImmersiveEngineering#1308]
I've attempted to pump one of the liquids into the generator (The white liquid, Plant Oil?) and it caused a server crash. Restarting causes a crash when the chunk the generator is in is loaded.

[Crash Report](http://pastebin.com/Z7Zbapje)

The liquid is getting pumped in via Ender IO Conduits.

**Comment by TauMaxim** [comment]
Can second this: http://pastebin.com/SK5fASdi

**Comment by kane-thornwyrd** [comment]
@TauMaxim you can give a try to [MCEdit](http://www.mcedit.net/), but keep in mind that because you're using modded, and MCEdit isn't made for this, the navigation and block identification may be really "funky"...

**Comment by Pkr1345** [comment]
Same for me except it was with Forestry's biomass and ethanol. I can't continue with the world until a fix is made or until i remove IE. (Don't want to because of my massive setup I have)

**Comment by skruis** [comment]
Just wanted to 2nd the situation with the Ender IO pressurized fluid conduit inserting Biodiesel into the Generator causing an instant crash. I'll try to insert with a different pipe or with the IE pipes when the server isn't in use.

**Comment by chazwarp923** [comment]
Also happens to me http://pastebin.com/W4S4DQkp

**Comment by BluSunrize** [comment]
Fixed for upcoming release, see commit above

**Comment by skruis** [comment]
Thanks for the quick fix!
