### ISSUE TITLE
Arc Furnace Not Accepting Osmium Ore (Mekanism)

### ISSUE THREAD

**Issue by DMIL421** [BluSunrize/ImmersiveEngineering#1309]
I can manually place Osmium Ore into the Arc Furnace, but I am unable to pipe it in like other ores.

Using EnderIO Item conduits for item transport.

**Comment by BluSunrize** [comment]
Would be great if you also specified what versions you are using, like it asks you to in the contribution guidelines ;)

**Comment by DMIL421** [comment]
Apologies, I'm not seeing the guidelines anywhere, even looking for them now. I'll try to give as much info as I can. Just let me know if you need more info. I'm happy to help.
Forge 2066.
Immersive Engineering 0.10-38. 
EnderIO 1.10.2-3.0.1.96_beta

I can pull the full modlist, but those are the pertinent ones.

**Comment by mindforger** [comment]
![snip](https://cloud.githubusercontent.com/assets/2683555/17959132/aa6ed3ea-6a9e-11e6-93f3-56df1b67cd72.PNG)

you can press F3 + C for 6 seconds to generate a crash and crashlog, it contains everything usefull, attach it or spoiler it via pastebin, please don't text wall it

**Comment by DMIL421** [comment]
Here's that crashlog.

[crash-2016-08-26_06.42.06-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/439394/crash-2016-08-26_06.42.06-client.txt)

THis is on a dedicated server, hosted on a Linux Server.

Let me know if there is anything else I can do to help. I'm loving the mod, very grateful for all the hard work you've put into it.

**Comment by BluSunrize** [comment]
I cannot reproduce this.
Using this setup:
http://puu.sh/qX8zD/cf3b6db980.jpg

Osmium ore is taken from the chest and put into the furnace.
Could you maybe show your setup to clarify?

**Comment by DMIL421** [comment]
Funny enough, I just retested myself, and now it is working, where it wasn't before. I don't have an explanation, but no longer a problem. Closing this. Sorry about that.
