### ISSUE TITLE
 [1.10.2] Can not craft treated wood planks

### ISSUE THREAD

**Issue by PhoenixSmith** [BluSunrize/ImmersiveEngineering#1310]
I do not seem to be able to create treated wood in the latest version-

http://imgur.com/icGdIzw

I also can not extract creostate with bottles at the moment.

**Comment by BluSunrize** [comment]
Bottles for creosote are deprecated. They wil lbe removed eventually.
Use a bucket in the middle. I dunno why JEI doesn't display it, but the middle needs to be a fluid container with Creosote. Buckets are easiest.
