### ISSUE TITLE
ru_RU lang

### ISSUE THREAD

**Issue by Sermax18** [BluSunrize/ImmersiveEngineering#1311]
when it will be?

**Comment by mindforger** [comment]
feel free to contribute!

**Comment by BluSunrize** [comment]
I'll write a russian traslation when I have learned russian. Try me again in ~25 years?

Otherwise, feel free to submit your own translation? xD

**Comment by sosenka1** [comment]
Могу предложить мой перевод на 1.9.8 
Прежде чем ставить поменяй расширение на .lang 
[ru_RU.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/434807/ru_RU.txt)

**Comment by mindforger** [comment]
>I can offer my translation 1.9.8
Before you change the extension put on .lang

**Comment by slendercreeper1010** [comment]
I can help to translate too.

**Comment by sosenka1** [comment]
давай

**Comment by BluSunrize** [comment]
For all future work on this translation, please open a PullRequest. I don't add translations manually, PRs make it far easier to manage+monitor. Thank you.
