### ISSUE TITLE
1.10.2 conveyor belt

### ISSUE THREAD

**Issue by sosenka1** [BluSunrize/ImmersiveEngineering#1312]
it is not possible to supply conveyor belt and sometimes when you read the book the crash happens

[1.10.2-forge1.10.2-12.18.1.2053 (2016-08-24).txt](https://github.com/BluSunrize/ImmersiveEngineering/files/434744/1.10.2-forge1.10.2-12.18.1.2053.2016-08-24.txt)

**Comment by mindforger** [comment]
i have no idea what 
`Current CompileTask:+ C2:1746192 35236  4 Blusunrize.lib.manual.gui.GuiManual::func_73863_a (1356 bytes)`
means but i see his memory beeing flooded with permanent data, maybe a memory leak
also inidcation

> Event: 1723.307 Executing VM operation: ParallelGCFailedAllocation
Event: 1723.330 Executing VM operation: ParallelGCFailedAllocation done
Event: 1729.631 Executing VM operation: ParallelGCFailedAllocation
Event: 1729.653 Executing VM operation: ParallelGCFailedAllocation done
Event: 1735.880 Executing VM operation: ParallelGCFailedAllocation
Event: 1735.903 Executing VM operation: ParallelGCFailedAllocation done
Event: 1742.150 Executing VM operation: ParallelGCFailedAllocation
Event: 1742.173 Executing VM operation: ParallelGCFailedAllocation done

**Comment by malte0811** [comment]
> [L] Running under TLauncher 1.731 Legacy

I don't think we support cracked launchers, do we? And you seem to be using some weird JRE as well:

> Event: 1745.894 Thread 0x0000000027a7a800 Exception <a 'java/lang/InterruptedException': sleep interrupted> (0x0000000796088458) thrown at [D:\re\workspace\8-2-build-windows-amd64-cygwin\jdk8u25\1677\hotspot\src\share\vm\prims\jvm.cpp, line 3141]

**Comment by BluSunrize** [comment]
Yup. Cracked laucnhers are not supported. Buy the game you fucking cheapskate.

With custom JDK (linux java according to my expert) and a non supported launcher,I refuse to offer support.

**Comment by sosenka1** [comment]
well, if that's the case, then convinced

**Comment by Sermax18** [comment]
you support Multimc?
