### ISSUE TITLE
[1.10.2] 0.10-38 Toolbox Crash

### ISSUE THREAD

**Issue by TheXWolf** [BluSunrize/ImmersiveEngineering#1313]
Recently updated from Forge 2041 to 2070 and now every time I attempt to open the toolbox it crashes.
Crashlog: [http://pastebin.com/A1D2v46J](url)

I tried porting backwards just a bit (was updating based on requirements from mods like JEI) and dropped down to 2060 and that didn't seem to help, so I'm not sure which forge version broke it but it's someplace slightly above 2041. I know 2051 & 2053 added/updated the RenderTooltipEvent which maybe has something to do with it? Hope the info helps.

**Comment by BluSunrize** [comment]
Issue thrown by JEI, please try to report to them first, this ain't my fault as far as I am aware
