### ISSUE TITLE
[Maybe Bug] 1.10.2 Fermenter slower than Squeezer

### ISSUE THREAD

**Issue by Greg9711** [BluSunrize/ImmersiveEngineering#1314]
^^ Title ^^
And they both use the same amount of power

**Comment by sosenka1** [comment]
this is most likely not a bug

**Comment by mindforger** [comment]
and the report is quiet incimplete also

**Comment by Greg9711** [comment]
Ok i have 1 Fermenter and 1 Squeezer hooked up to 2 Refineries and they are hooked up to 3 Diesel Generators. With all 3 Generators running and both Refineries also working the Squeezer is always full of Plant Oil and the Fermenter cant keep up and its internal tank slowly drains.

**Comment by mindforger** [comment]
and the used IE version is?
what are you feeding the fermeter and the squeezer with?
have you checked the outcome beeing equal in the manual?

**Comment by Greg9711** [comment]
(facepalm) i´m using hemp in the Squeezer and it gives more liquid and sugar cane in the other one xD i forgot that hemp gives more. Sorry :P
