### ISSUE TITLE
[1.10.2](0.10-38) - Wires are invisible after relaunching Minecraft

### ISSUE THREAD

**Issue by Boingboingsplat** [BluSunrize/ImmersiveEngineering#1315]
After placing wires on LV connectors and relays and then closing and restarting Minecraft, they are invisible. They still transfer power, and drop copper coils when using wirecutters on a connector as expected, but don't render at all. This is occurring on an SMP server.

**Comment by marcin212** [comment]
:+1:

**Comment by mindforger** [comment]
1. you didn't read the contribution guidelines
2. read them now
3. use the search next time please https://github.com/BluSunrize/ImmersiveEngineering/issues/1281

**Comment by Boingboingsplat** [comment]
This seemed like a different issue to me, as that one had to do with wires not rendering depending on player position, and nothing to do with them disappearing entirely on relaunch, but sorry!
