### ISSUE TITLE
Placing Floodlights 1.10.2 crashes 

### ISSUE THREAD

**Issue by Oxosorrel** [BluSunrize/ImmersiveEngineering#1316]
Crash log:
[http://pastebin.com/iiwxCrhK](url)

Placing the flood light, the model appears, no texture, just black... then less than a second later, it crashes. 

This occurs in a freshly created world, running JUST ImmersiveEngineering-0.10-38 and no other mods, crashes. Occurs on a server and on single player.

Tested both latest forge-1.10.2-12.18.1.2073 and recommended forge-1.10.2-12.18.1.2011 got the same crash.

Using reasonably current Java 1.8.0_91.

I hope its not a video graphics driver issue, I'll test it on another PC soon to eliminate that possibility.

**Comment by FiveEYZ** [comment]
Here is the same crash, but on a spongeforge server:
https://gist.github.com/FiveEYZ/aaf432a83ccfb91dfbdd67d71c028049

**Comment by theunkn0wn1** [comment]
They are not finished yet, known issue. #1263

**Comment by BluSunrize** [comment]
Possibly fixed for upcoming release, see commit above, will need Malte to help me with this later.

**Comment by coalman321** [comment]
quick question related to this, is there any way to clear the block because it is stuck in one of my worlds.....

**Comment by mindforger** [comment]
mcedit would be a possibility

**Comment by AEnterprise** [comment]
the easiest way would be to go in the forge config and enable to remove erroring TE's, load up the world, make sure it's gone and then turn the config back off

**Comment by coalman321** [comment]
ok thanks. got it fixed and working again. :smile:
