### ISSUE TITLE
external heater crash! :C

### ISSUE THREAD

**Issue by iluvdemomanandjunkrat** [BluSunrize/ImmersiveEngineering#1317]
http://pastebin.com/TZES1kWs

**Comment by GirafiStudios** [comment]
The crash have nothing to do with Immersive Engineering.
Looks like it is Minespeed (Whatever that is?).

**Comment by mindforger** [comment]
this one is nice i didn't even find **anything** related with that "minespeed" thingy, but toally not even close to IE, what made you think this is caused by IE ?! would be interesting to know

it's something between Biomes O Plenty grass stuff and this "minespeed" thingy that trys to make a grass block into a chest or soemthing like that

**Comment by ArukaAlter** [comment]
The minespeed.tp bit relates to Torch Placer IIRC, @mindforger

**Comment by KnightMiner** [comment]
> `minespeed.tp`

[Torch Placer](https://mods.curse.com/mc-mods/minecraft/250084-torchplacer) maybe? MineSpeed is the author of that mod and the initials "to" fit the name.

But yeah, I don't see anything in that report related to Immersive Engineering. At most modifying an IE block changed a light level causing this Torch Placer thing to do stuff, likely passing the wrong blockstate for a light level check.

**Comment by iluvdemomanandjunkrat** [comment]
mindforger i dont know how to code but it crashes after placing external heater.

**Comment by XFactHD** [comment]
As @mindforger said, the external heater issues a block update when it is placed (standard behaviour, every block does this) and this causes a light update which makes the torch placer mod go ham and try to access a method from a random block with the wrong block state. This means that any block could cause this crash.

**Comment by mindforger** [comment]
try to find an issue tracker for torch playcer and report it there and link to this issue, there is barely anything IE can do to fix this **i guess**

**Comment by BluSunrize** [comment]
This is not an issue with the external heater. We don't expect you to be able to code, but we do expect you to read the flipping guidelines when you report an issue.
And after multiple people have told you that this is not an IE issue, I would instead recommend that you report this to TorchPlacer and BoP.

Issue closed.
