### ISSUE TITLE
[1.10.2] Pipes voiding liquids

### ISSUE THREAD

**Issue by Pihrra** [BluSunrize/ImmersiveEngineering#1318]
Pipes sometimes seem to void liquids (IE 0.10-38)
I have pipes running from a refinery to a generator. I wanted to store some Biodiesel in a ExtraUtils drum so I put it next to the pipe as seen in the screenshot. Once I had drained enough diesel I removed the drum but I noticed the refinery was still draining and my generator wasn't running.
Removing and replacing the pipe stopped the problem. 
I had the same problem occur with a previous (self compiled) build of IE with an IE multiblock tank but then I wasn't sure what was causing the issue so I didn't report it just stopped using the tanks.
![2016-08-25_15 21 11](https://cloud.githubusercontent.com/assets/215052/17970798/52e97514-6ad8-11e6-9a2d-cb36359be9a3.png)
Forced crashlog : http://pastebin.com/rq4jTnAz

**Comment by BluSunrize** [comment]
Fixed for future releases, see commit above
