### ISSUE TITLE
creosote recipes/getting from oven

### ISSUE THREAD

**Issue by uxsvent** [BluSunrize/ImmersiveEngineering#1319]
down loaded ver 38 for mc1.10.2 on curse and cannot get oil from oven in bucket or bottle. cannot craft wood because cant get oil.

**Comment by kane-thornwyrd** [comment]
[Please read the guidelines for contributing !
![screenshot_28](https://cloud.githubusercontent.com/assets/625236/17993707/6aa47b84-6b52-11e6-9a9d-ef5d6e05a4ca.png)
](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/CONTRIBUTING.md)

**Comment by SamJBarney** [comment]
I'll add it for him since I'm getting the same thing.

Bug: I am unable to extract creosote oil from the coke oven using a bottle.
Reproduce: Put an empty bottle in the upper-right slot in the Coke Oven.
It happens every time I try to do so.
This is happening in single player.

A lit of mods can be found [here](http://pastebin.com/zUTmbjjH)

**Comment by ArukaAlter** [comment]
Creosote Bottles were removed, there are only buckets now.

**Comment by BluSunrize** [comment]
Yep. Bottles are deprecated. If you can reproduce not getting a BUCKET filled. Then we have a problem.

**Comment by NerdMcBoon** [comment]
I'm having the same problem.

I can't use bottles or buckets to get creosote oil out of the coke oven or any other liquid container.
I'm using IE 0.10-38 with Forge 1.10.2-12.18.1.2075.
It worked a few days ago, and I didn't add any new mods, so I think it might be a problem with a recent Forge update.

[Mod list](http://pastebin.com/nKgXyBZ9).

**Comment by AniMaid** [comment]
I have the same issue.
Just IE, trying with forge 2011 and 2075

![2016-08-28_17 52 20](https://cloud.githubusercontent.com/assets/16230841/18038116/502e31bc-6d48-11e6-9e92-1faadb7fd6c5.png)

**Comment by mindforger** [comment]
i think this is an issue about the forge buckets, IC2 did some strange stuff resultiung in a 1:1000 duplication with EIO fluid storage for example ... maybe you can get hints off EIO dev about those funky forge vs vanilla bucket issues

**Comment by BluSunrize** [comment]
I do believe to have found the cause for this issue and will be able to fix it when I am back from my holiday, on wednesday.
A temporary fix for you folks would be installing TInkers Construct (In fact, maybe just Mantle alone will fix this), or some other mods that enable Forge's universal buckets.

Memo to self: Move Universal Bucket initialization to main mod class instaead of IEContent

**Comment by KnightMiner** [comment]
Its Tinkers that does it rather than Mantle. You might be able to enable it in the Forge config for it to work though.

**Comment by AEnterprise** [comment]
yeah, forge has a config option you can enable the universal bucket with

**Comment by calloatti** [comment]
Maybe this helps, from the log:

[14:53:07] [Client thread/ERROR] [FML]: Trying to activate the universal filled bucket too late. Call it statically in your Mods class. Mod: Immersive Engineering

**Comment by BluSunrize** [comment]
I already declared that I am aware of the issue. I just can't fix it yet.

**Comment by BluSunrize** [comment]
Fixed, see commit above
