### ISSUE TITLE
railgun, revolver, and drill problems 

### ISSUE THREAD

**Issue by slendercreeper1010** [BluSunrize/ImmersiveEngineering#1326]

**Comment by slendercreeper1010** [comment]
the drill, and revolver have no sound and revolver goes mad then i try to charge it
![2016-08-25_01 21 14](https://cloud.githubusercontent.com/assets/21247723/17981845/134e5dbc-6b0e-11e6-85a2-4eaed9639607.png)
like that

**Comment by slendercreeper1010** [comment]
version 1.10.2

**Comment by ArukaAlter** [comment]
Missing critical information, such as mod version or other mods present, not to mention the amount of issues you have opened and closed, there's a edit button.

**Comment by slendercreeper1010** [comment]
im sorry sor spamming

**Comment by slendercreeper1010** [comment]
mod version is 0.10-38

**Comment by slendercreeper1010** [comment]
im new in the github sorry again

**Comment by slendercreeper1010** [comment]
i tryed without any mods (even optifine) and the railgun still have weird animation of charging

**Comment by kane-thornwyrd** [comment]
[Please read the guidelines for contributing !
![screenshot_28](https://cloud.githubusercontent.com/assets/625236/17993707/6aa47b84-6b52-11e6-9a9d-ef5d6e05a4ca.png)
](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/CONTRIBUTING.md)

**Comment by LordHellscream** [comment]
Having the exact same issue. Railgun is held pointing downward while charging.
Using IE 0.10-38 (for 1.10.2), Forge version 2073

**Comment by BluSunrize** [comment]
Good lord this is some awful reporting.
Yes. The railgun points downward.
The revolver does not have a charging animation. Use the correct terms.
The drill has never had sound.
The revolver not having sound seems quite off to me, Did you maybe turn sounds off, or are you wearing ear defenders?

Also,"I have never used git before" doesn't pull if there is a massive message saying "read hte guidelines" when you open an issue.

Now, clear concise information on the sound bug please, the railgun one is known already.

**Comment by Bitterholz** [comment]
@BluSunrize Aside from Shitty Reporting
I can confirm the missing firing sound for the revolver. No problems with the drill.

Allthough the Chemthrower voids liquids...

**Comment by BluSunrize** [comment]
Voids how?

**Comment by LordHellscream** [comment]
I can confirm the revolver has no sound effect while firing, not wear ear defender or anything of the sort.
Haven't tried the drill so cannot comment.

**Comment by BluSunrize** [comment]
Fixed, see commit above

**Comment by LordHellscream** [comment]
when is the actually fix going to be available on curseforge? thanks

**Comment by BluSunrize** [comment]
When I've released the next build. Patience is a virtue.

**Comment by LordHellscream** [comment]
Your mod is just too awesome, and railgun is just too cool, patience is very difficult under these circumstances :)
