### ISSUE TITLE
(1.10.2) IE not loading.

### ISSUE THREAD

**Issue by Darcoon** [BluSunrize/ImmersiveEngineering#1327]
After dropping the mod into my mods folder I went on happy and exited to play with IE in 1.10.2 only to discover it had not loaded, it didn't even detect the mod so I went on a little troubleshooting and here are the results:
IE does not load.
IE Isn't even detected seen as ctrl+F in the terminal text looking for "Immersive" gave no result.
It is running on Minecraft 1.10.2 on Linux lubuntu v.16.04.
I have tested different versions of forge, that being 12.18.1.2052,12.18.1.2070 and 12.18.1.2073 all on both my normal Install and a complete new one with no other things installed then forge and IE.
I also tested it in my server and it has the same issue, it runs on forge 12.18.1.2052.
I suspect it being something with Linux/ Lubuntu but I don't know what.

I would be happy to supply any more info on system details and such.
Hope this helps,

~Darcoon

**Comment by malte0811** [comment]
It works on Debian, so I doubt it is caused by Linux... Please upload the log (to pastebin or gist) even if it does not say anything about IE, there may be something usefull in there. Only cause for this that I can think of would be a wrong file, so please run sha256sum on your IE jar and post the hash here so someone (probably me) can check whether you are using the right file.

**Comment by Darcoon** [comment]
Okay Here is the Sha256sum:
63fc174c091dcb526edfee167481283f480090e62ff730038514c7d739500b0d  ImmersiveEngineering-0.10-38-sources.jar
And here is the pastebin to the log:
http://pastebin.com/vAjeiS6D

**Comment by Joshwoo70** [comment]
Wait... Why are you using sources? Not the majn download?

**Comment by Darcoon** [comment]
Okay than did not notice that xD
for some reason it downloaded the sources file instead of the normal one, re downloaded an retried  and it now works just fine.
Thanks Josh :+1:
