### ISSUE TITLE
[Build 38] Chemthrower loading voids Liquids

### ISSUE THREAD

**Issue by Bitterholz** [BluSunrize/ImmersiveEngineering#1329]
**Stats:**
- Minecarft:
  - 1.10.2
- Mode:
  - SSP
- Forge:
  - 12.18.1.2073
- IE:
  - Build 38
- Additional Mods:
  - JEI
  - IC2exp
  - Tconstruct
  - Mantle
  - Chameleon
  - Storage Drawers
  - Open Computers

**Description**
Trying to load the Chemthrower from any tank drains liquid from the Tank but doesnt get stored in the Chemthrowers internal tank. AKA Fluid is lost. Not yet testable with a Chemthrower that allready contains liquid, since you simply cant load them.

**How to Reproduce**
RMB-Click a Chemthrower onto any Tank that contains Liquids, watch the Tank drain. Chemthrower does not gain any Liquid, regardless of the Type of Liquid

**Comment by BluSunrize** [comment]
Are you in creative? =P

**Comment by Bitterholz** [comment]
@BluSunrize dont know if i was...it could have been that i switched to creative(tested yesterday evening). Dont remember right now...
Will test again in a few

**Comment by Bitterholz** [comment]
@BluSunrize Yes it appears i have been in creative.

Odd tho...shouldnt it fill from the tank and not use any Liquid at all? or is that a standard behavior for player-held fluid containers in Creative?

**Comment by BluSunrize** [comment]
Standard behavior in Forge's default fluid utilities. If it's an empty item in creative, it is used to empty the tank. Only way around that is my own filling util methods, and I'm too lazy! ^_^
