### ISSUE TITLE
[1.10.2] non - placeable horizontal conveyor belts 

### ISSUE THREAD

**Issue by MrEvilCookie** [BluSunrize/ImmersiveEngineering#1330]
I can place vertical conveyor belt . but I can't place horizontal conveyor belts(
if I try to place the conveyor belt , it is not placing ( I'm playing in single player . in my mod pack ( www.dropbox.com/s/20exsamva3hdtcb/Eri%20craft%201.10.2.rar?dl=0 ) . and it happening every time

**Comment by kane-thornwyrd** [comment]
[Please read the guidelines for contributing !
![screenshot_28](https://cloud.githubusercontent.com/assets/625236/17993707/6aa47b84-6b52-11e6-9a9d-ef5d6e05a4ca.png)
](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/CONTRIBUTING.md)

**Comment by MrEvilCookie** [comment]
ok

**Comment by BluSunrize** [comment]
Same issue as #1295
