### ISSUE TITLE
Excavator Not Working Properly

### ISSUE THREAD

**Issue by Utildayael** [BluSunrize/ImmersiveEngineering#1332]
Odd visual bug and probably otherwise...

Excavator bucket assembly is... well.. sideways. It's perpendicular to the engine instead of parallel.

Screenshot:
http://imgur.com/a/8Qb4E

It spins along the proper access but the whole wheel spins sideways.

Doesn't seem to ever bring up any ore/dirt/anything either. :(

Oh and it keeps spinning even if machine has no power. I even broke the engine and it is still spinning. Had to re-build the engine to apply redstone to make it stop and then break the wheel. 

Took whole thing apart. Rebuilt. Now have invisible bucket wheel.

Logged off. Came back. Same. Broke machine and wheel. Logged off and back on, rebuilt, sideways wheel again.

MC 1.10.2
Forge 12.18.1.2065
IE 0.10-38

Thanks

**Comment by Utildayael** [comment]
Update: Moved whole unit to a different vein and it IS pulling ores like it should but the wheel is still sideways and spinning sideways like in my screenshot. So that at least downgrades this to just a weird visual bug. :)

Thanks!

**Comment by BluSunrize** [comment]
Fixed for future release, see #1361
