### ISSUE TITLE
Hoppers into conveyor belts spill items

### ISSUE THREAD

**Issue by gchpaco** [BluSunrize/ImmersiveEngineering#1333]
Hoppers feeding into conveyor belts spill items, like you used a dropper.

Observed:
![2016-08-26_23 37 46](https://cloud.githubusercontent.com/assets/17789/18025693/a9b4ea72-6be6-11e6-8206-d1a8df4554d0.png)

(Don't mind the Botania mana flashes)

Expected outcome is no spilling.

What I do that works as a workaround is this:
![2016-08-26_23 39 13](https://cloud.githubusercontent.com/assets/17789/18025696/c8accf58-6be6-11e6-88e9-ea176a70e7d0.png)
But that's kinda lame, and requires Botania for the open crate.

**Comment by gchpaco** [comment]
Happens with using EnderIO item conduits, too.

**Comment by BluSunrize** [comment]
Generally it's great if you read the contribution guidelines. Luckily, I can tell from the vertical conveyor that you're on latest 1.10.

Will investigate when I'm off holiday.

**Comment by kane-thornwyrd** [comment]
[Please read the guidelines for contributing :smile: 
![screenshot_28](https://cloud.githubusercontent.com/assets/625236/17993707/6aa47b84-6b52-11e6-9a9d-ef5d6e05a4ca.png)
](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/CONTRIBUTING.md)

**Comment by BluSunrize** [comment]
Yo @kane-thornwyrd. I appreciate the effort you put in, but you don't have to copypaste that under every issue. ESPECIALLY not if I already told them to read the guidelines and have responded.

**Comment by BluSunrize** [comment]
Fixed for upcoming release, see commit above
