### ISSUE TITLE
External Heater could't power Alchemical Furnace

### ISSUE THREAD

**Issue by Cyl18** [BluSunrize/ImmersiveEngineering#1334]
![Pic](https://cloud.githubusercontent.com/assets/14993992/18026204/dd5c2e36-6c71-11e6-9d50-668de9daf8f7.png)

![Pic](https://cloud.githubusercontent.com/assets/14993992/18026163/11eb5d80-6c71-11e6-90e6-1203dd898d4a.png)

**Comment by kane-thornwyrd** [comment]
[Please read the guidelines for contributing :smile: 
![screenshot_28](https://cloud.githubusercontent.com/assets/625236/17993707/6aa47b84-6b52-11e6-9a9d-ef5d6e05a4ca.png)
](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/CONTRIBUTING.md)

**Comment by Cyl18** [comment]
I forgot to give it redstone signal.

![8l ujh i0keu4tea44jn 9](https://cloud.githubusercontent.com/assets/14993992/18026386/8e9588e6-6c77-11e6-99c2-70c0b31bc7e1.png)

Sorry for my poor English...
