### ISSUE TITLE
Cannot render Railgun

### ISSUE THREAD

**Issue by Cyl18** [BluSunrize/ImmersiveEngineering#1335]
[crash-2016-07-22_00.16.38-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/440557/crash-2016-07-22_00.16.38-client.txt)

**Comment by Cyl18** [comment]
Crash By the mod "Better Fonts"

Sorry for my poor English.

**Comment by kane-thornwyrd** [comment]
Don't worry, at least you found the answer, thank you for contributing.
