### ISSUE TITLE
TileEntityMetalPress breaks capability contract

### ISSUE THREAD

**Issue by williewillus** [BluSunrize/ImmersiveEngineering#1337]
Most modders reasonably assume that if `hasCapability` returns true, we will get something non null from `getCapability`. If that is not the case, and we have to null check every single call to getCapability, then the whole purpose of hasCapability is lost.

The metal press breaks this contract. It returns true for IItemHandler always in `hasCapability`, but potentially returns null in `getCapability`. This is causing crashes in Botania's "The Spectator" Bauble, which searches through inventories looking for matching items to the one in hand. It does a `hasCapability` check before calling `getCapability` but due to this bug it crashes because IE still returns null even though `hasCapability` returned true.

I propose either revising hasCapability to be more accurate, or returning an empty immutable IItemHandler instead of null.

Thanks

**Comment by williewillus** [comment]
See https://github.com/williewillus/Botania/issues/459

**Comment by BluSunrize** [comment]
Taken note of, cheers.
For future reference though, please specify what version of IE, k?

**Comment by williewillus** [comment]
heh, sorry
the player was playing 0.10-38

**Comment by BluSunrize** [comment]
Fixed for upcoming release, see commit above
