### ISSUE TITLE
[1.10.2] Water wheels are invisiblesss

### ISSUE THREAD

**Issue by epicskymi** [BluSunrize/ImmersiveEngineering#1338]
not using optifine  and no errors just cant see them

**Comment by theunkn0wn1** [comment]
Please read the guidelines to contributing if you seek support here, you could not have missed the link.
IE version, forge version, mods and, if you could, a log please.

**Comment by BluSunrize** [comment]
^ that

**Comment by BluSunrize** [comment]
Closed due to lack of further information
