### ISSUE TITLE
[1.10.2] Refinery: Crash when trying to pump in biodiesel back into refinery.

### ISSUE THREAD

**Issue by devilunaworkshop** [BluSunrize/ImmersiveEngineering#1339]
[crash-2016-08-28_02.47.27-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/440928/crash-2016-08-28_02.47.27-server.txt)
[crash-2016-08-28_02.45.41-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/440929/crash-2016-08-28_02.45.41-server.txt)

Server crashes, when piping biofuel from the barrel back into rafinery trough the side input pipe. (using only IE barrel and pipe)

**Comment by Bitterholz** [comment]
Why the heck do you even want to do that? XD

But yeah tha should not result in a NPE

**Comment by devilunaworkshop** [comment]
Well, the drill description says "Fill in refinery" but refinery doesn't accept drill in any slot (also doesn't accept jerrycan into the GUI), Thought it might be due to insufficient amount of fuel (less then 10 buckets), so i tried to pump back some biodiesel back into refinery to get over 10 buckets in it.

**Comment by Bitterholz** [comment]
The Drill should be fillable from any kind of Tank by Right-Clicking...same as the Chemthrower.
Same goes for Jerrycans, since these are juts Modified Buckets in the end.


But yeah refinery not accepting Jerrycans seems odd...
Does it accept Buckets? If not, the Slot might be broken.

**Comment by devilunaworkshop** [comment]
Jerrycan does not fill from barrel(treated wood). 
Buckets are accepted, but don't output as biodiesel buckets (refinery keeps empty bucket in input slot)
IC2 Universal Fluid Cells are accepted and filled.

**Comment by BluSunrize** [comment]
Crash aside, could you please provide screenshots of hte refinery GUI and hte stuff you put inside it?

**Comment by devilunaworkshop** [comment]
![2016-08-28_20 15 01](https://cloud.githubusercontent.com/assets/21285218/18035732/ab926d3a-6d5b-11e6-83ee-8112bd48d49d.png)
![2016-08-28_20 15 16](https://cloud.githubusercontent.com/assets/21285218/18035734/ab94f0e6-6d5b-11e6-8345-e31e71f12e60.png)
![2016-08-28_20 15 44](https://cloud.githubusercontent.com/assets/21285218/18035733/ab93ef66-6d5b-11e6-9720-8c2168f55b31.png)

**Comment by Bitterholz** [comment]
Seems like sth is messing up the Fluid containers...i noticed some error messages about universal buckets on IE startup too @BluSunrize

**Comment by devilunaworkshop** [comment]
Also I seem to run into trouble with cable rendering, and wooden posts not extending arms when using engi hammer on them, Should i open issue for each separately or put it under "e-net and accesories troubles" collective topic?

**Comment by BluSunrize** [comment]
@Bitterholz could you maybe actually copy that exact message? Or better even, pastebin me an entire log, including all startup stuffs.

**Comment by BluSunrize** [comment]
@devilunaworkshop We already have issues on rendering, please confirm if they are the same you are experiencing.

**Comment by devilunaworkshop** [comment]
@BluSunrize Yes, I can confirm i run into already posted issues with cable rendering and black connectors.
No issue with the wooden posts. Going to open one.

**Comment by Bitterholz** [comment]
@BluSunrize im somehow unable to recreate the problem...will try on tho

**Comment by BluSunrize** [comment]
Fixed in the upcoming release, I hope.
