### ISSUE TITLE
Immersive Engineering Oredict Crash

### ISSUE THREAD

**Issue by Aceyan2001** [BluSunrize/ImmersiveEngineering#134]
http://pastebin.com/9kg970Wa

**Comment by wafflemans** [comment]
Can you give us more details like forge version and mod version?

**Comment by Aceyan2001** [comment]
Mod version: 0.3.2
Forge: 1.7.10.10.13.4.1472

**Comment by BluSunrize** [comment]
Yeah this is usually caused by an outdated forge version. Full log please.

**Comment by Aceyan2001** [comment]
I just loaded 0.3.2 of the mod and forge 1.7.10.10.13.3.1389 and it works beautifully. Not sure why but downgrading the forge version works.
