### ISSUE TITLE
[Suggestion] Tesla compatibility for cables

### ISSUE THREAD

**Issue by Boundarybreaker** [BluSunrize/ImmersiveEngineering#1340]
I've been using the Tesla system recently, and I've been having trouble finding good cables that easily convert between it, RF, and EU. Could you maybe add that to IE cables? It'd be really helpful and it'd make Tesla a lot more viable as an energy system.

**Comment by KnightMiner** [comment]
I'm pretty sure IE cables no longer support EU, but supporting Telsa would be great as quite a few 1.10 mods are using that instead of RF

**Comment by marcin212** [comment]
IE doesn't support IC2's EU anymore, but the code for MC1.7 is still present in MC1.10 version. Maybe it's planned for a future update?

https://github.com/BluSunrize/ImmersiveEngineering/blob/1.10/src/main/java/blusunrize/immersiveengineering/common/blocks/metal/TileEntityConnectorLV.java#L385-L416

**Comment by malte0811** [comment]
Regarding EU compat: #1087
Quote from @BluSunrize on curseforge:

> Currently no plans for Tesla, no. I realize the subreddit has a massive boner for it, but to me it's just ANOTHER system I'd have to adapt to. I dislike ForgeCapabilities as is, and Tesla uses "long" instead of "int" which advocates powercreep and massively high energy numbers, and I'm not fond of that. (Then again, ever going to 2.147 billion is a bit messed up to begin with)

**Comment by BluSunrize** [comment]
Yeap. Thank you for digging that out, Malte.
My stance on that remains unchanged. If that'll changein the future? Depends. For now? Nope.
