### ISSUE TITLE
[1.10.2] Ticking entity crash from Railgun

### ISSUE THREAD

**Issue by Regulith** [BluSunrize/ImmersiveEngineering#1342]
After fooling around with some IE tech earlier in my single player world, the game is now crashing every time I try loading back into it. I'm not that great at reading crash logs, so I might be assuming too much here, but it seems fairly evident it's related to the Railgun based on testing.

I was really interested in the Railgun, so I made one, charged it up, and fired an Aluminum Rod into the side of a block of dirt. I was curious what would happen if I broke the block it had lodged itself in, so I did. After seeing the rod continue flying and burrowing into the next block, I replaced the one I had broken, effectively covering the projectile. I exited the game shortly after, and came back later only to find that it wouldn't let me back in.

I reproduced this three times in Creative: first exactly as it originally happened, then by firing a Steel Rod and not breaking any blocks, and finally the previous method with **only** IE installed. I got the same result each time, none of the worlds in which a Railgun has been fired into a block can be loaded anymore.

The initial crash log and accompanying mod list is here: 
http://pastebin.com/eM6hxeMr 

The crash log for just IE is here: 
http://pastebin.com/Kup7X4DY 

Let me know if there's anything I can do with my world(s) to help.

**Comment by BluSunrize** [comment]
Thank you for the report, I will address this issue when I return from my holiday.

**Comment by BluSunrize** [comment]
Fixed, see commit above
