### ISSUE TITLE
[1.10.2][0.10-38] Unable to place horizontal conveyor belts nor the dropping version

### ISSUE THREAD

**Issue by kane-thornwyrd** [BluSunrize/ImmersiveEngineering#1343]
Hello, and thank you to take a moment to review this issue.

- I am unable to place horizontal conveyor belts nor the dropping version.
- It happen directly at world creation, I've done nothing else than trying to place those and the vertical ones.All picked from the creative tab.
- On a creative singleplayer instance with only IE installed.
- [Here is the manually triggered debug crash](https://gist.github.com/kane-thornwyrd/82e732e74bce411639c18b8b93f86cec)

Look somehow like https://github.com/BluSunrize/ImmersiveEngineering/issues/1330, or https://github.com/BluSunrize/ImmersiveEngineering/issues/1295 but with a "cleaner" reporting.

**Comment by AniMaid** [comment]
I have this same issue, crafting the belts manually gives a place able item, it is only the creative tab spawned items that have this issue.

**Comment by kane-thornwyrd** [comment]
Yes, I know, I reviewed the previous bug reports, hence the "All picked from the creative tab". And those spawned via JEI works too, but Blu should focus on vanilla + IE, and it's still a creative bug.

**Comment by BluSunrize** [comment]
Yeah and we already have an open issuefor that, specifically #1295, which is not a bad report. So why open another one?

**Comment by kane-thornwyrd** [comment]
ok, as you wish
