### ISSUE TITLE
[1.10.2] Pump causes adjecent block textures to be see-trough.

### ISSUE THREAD

**Issue by devilunaworkshop** [BluSunrize/ImmersiveEngineering#1345]
![2016-08-28_20 44 40](https://cloud.githubusercontent.com/assets/21285218/18035935/aa11b6c8-6d60-11e6-96d9-8eaa01949402.png)

When blocks placed near top of the pump, texture facing the pump disappears.

**Comment by BluSunrize** [comment]
Fixed with https://github.com/BluSunrize/ImmersiveEngineering/commit/78794f608049482963e84d8a986053449e414f50
