### ISSUE TITLE
[1.10.2] Windmill wall detection is backwards.

### ISSUE THREAD

**Issue by AniMaid** [BluSunrize/ImmersiveEngineering#1347]
The wall detection for windmills is looking behind it for walls. I was trying to make a nice pretty structure to support the windmills I was making and discovered this. Loading a new instance with just forge and IE to make sure it wasn't weird mod interactions.

This doesn't turn:
![2016-08-28_17 09 55](https://cloud.githubusercontent.com/assets/16230841/18037971/a40aaae4-6d44-11e6-942c-6096269d7c5d.png)

This does:
![2016-08-28_17 09 42](https://cloud.githubusercontent.com/assets/16230841/18037970/a3360d66-6d44-11e6-9d36-74133d7431df.png)

**Comment by MalkContent** [comment]
arguably neither should :D

**Comment by Bitterholz** [comment]
@MalkContent But that would be overly realistic. Also, normal windmill buildings blocks alot of the area behind the actual Windmill too and it works.

@BluSunrize I can confirm this issue in my clean IE-38 testworld

**Comment by BluSunrize** [comment]
Fixed for upcoming release, see commit above
