### ISSUE TITLE
IngredientStack API List not working

### ISSUE THREAD

**Issue by MakerTim** [BluSunrize/ImmersiveEngineering#1348]
https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/api/ApiUtils.java#L348

When i give it a List, it always fails
Or the list is empty -> indexoutofbounds
Or i fill the list (what should) -> get the message that i didn't supply it with the correct arguments

just a NOT (!) in the second part of the if will fix it

**Comment by BluSunrize** [comment]
I assume you are trying to create an addon? Are you working on 1.8 or 1.10?

**Comment by MakerTim** [comment]
I made my own modpack and added Pam's Harvestcraft to the Squeezer and Fermenter
only; when i add lists, it isnt wokring, oredic/items/itemstacks are working like intended

i got everytime the message in my catch with
'Recipe Ingredients must always be ItemStack, Item, Block, List<ItemStack> or String (OreDictionary name); "+input+" is invalid'
when i do lists (Lists of ItemStacks)

**Comment by BluSunrize** [comment]
that was not an answer to either of my questions.
Did you use your own code to add these recipes or did you use Minetweaker/Crafttweaker/a mod someone else made?
And:  What version? 1.8 or 1.10?

**Comment by MakerTim** [comment]
Sorry, my bad
Made my own mod & 1.10

**Comment by BluSunrize** [comment]
Fixed, see commit above
