### ISSUE TITLE
[1.10.2] Assembler won't craft with fluids

### ISSUE THREAD

**Issue by AniMaid** [BluSunrize/ImmersiveEngineering#1349]
Mods: IE, Tinker's Construct, Mantle (TiCon and mantle needed to actualyl get buckets of creosote)

Attempting to use an assembler to craft with fluids fails.

![2016-08-28_18 13 50](https://cloud.githubusercontent.com/assets/16230841/18038335/9cc2c18e-6d4b-11e6-98d1-0e58b1455bd5.png)

Additionally putting a bucket of creosote into the assembler will successfully craft but the bucket is lost forever.

**Comment by BluSunrize** [comment]
Thanks for the report, will investigate on wednesday.

**Comment by BluSunrize** [comment]
Fixed for upcoming release, see commit above
