### ISSUE TITLE
(v0.3.2) Lightning rods still don't generate energy

### ISSUE THREAD

**Issue by JAWSAWN** [BluSunrize/ImmersiveEngineering#135]
Fences reaching the clouds? Casting witchery rituals to drop lightning on them? Still does not work

Unless you coded a way that something is preventing it? Does the code prevent manual strikes like thunderstriking items or witchery rituals? At least its a frickin lightning rod! It supposed to prevent nearby land to burned down by lightnings. So maybe nerf the power it generates (still don't know how much) and increase the chances of lightning strike with lesser fences?

**Comment by wafflemans** [comment]
It might have to do with the type of lightning witchery is summoning. The lightning rod does generate energy when struck by natural lightning. You just have to wait!

**Comment by BluSunrize** [comment]
fairly sure I fixed it, because my test-summoning of lightning worked. Try making a twilight forest portal, those lightning bolts are confirmed to work

**Comment by JAWSAWN** [comment]
But where should the lightning strike? on any of 3 blocks or the middle part?

**Comment by BluSunrize** [comment]
On the top fence.
