### ISSUE TITLE
1.10.2 crash on startup server

### ISSUE THREAD

**Issue by DarkCorvuz** [BluSunrize/ImmersiveEngineering#1350]
[crash-2016-08-29_07.44.23-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/441935/crash-2016-08-29_07.44.23-server.txt)

I'm sorry if i misinterpreted the crash log. I'm not really proficient at reading those yet.
If you could point me out what went wrong that would be great.
It's a bit weird since in singleplayer it does launch.

**Comment by BluSunrize** [comment]
I can't tell you what exactly causes this and will investigate as soon as I am off holiday, but for now, a temporary fix for you would be disabling the Arc Furnace's recycling function in the IE config on the server.

**Comment by DarkCorvuz** [comment]
thx for the quick response and quickfix

**Comment by BluSunrize** [comment]
I am actually quite throughly confused at this one. Could you please produce this crash again and then provide me with the latest log out of your logs folder? I will need to see the entire log for more info, just the crash alone isn't doign it :/

**Comment by Synize** [comment]
Hey Blu, hope this helps i had the same issue. Seems like i had the server crash then after the first crash the server would no start again until i disabled the arc furnace Recycling as you mentioned above.

I have attached the logs for both the first crash and then the second log where the instance would no longer start.

[Second_crash-2016-09-05_04.29.32-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/454403/Second_crash-2016-09-05_04.29.32-server.txt)
[First_crash-2016-09-05_04.11.04-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/454404/First_crash-2016-09-05_04.11.04-server.txt)

**Comment by UnNinja** [comment]
Any idea what's causing this? We're experiencing this issue, but not every reboot. It seems to happen randomly.
[Latest crash log](http://pastebin.com/PkHRf4fz)
