### ISSUE TITLE
Possible textures missing or Not Responding message.

### ISSUE THREAD

**Issue by fullforceofpower** [BluSunrize/ImmersiveEngineering#1351]
Mod List:

EnderCore-1.10.2-0.4.1.49-beta
EnderIO-1.10.2-3.0.1.94_beta
ImmersiveEngineering-0.10-38
jei_1.10.2-3.9.0.244
journeymap-1.10.2-5.2.4-unlimited
Mekanism-1.10.2-9.1.1.290
MekanismGenerators-1.10.2-9.1.1.290
MekanismTools-1.10.2-9.1.1.290
refinedstorage-0.9.4
MCMultiPart-1.2.1-universal

crash is as follows

http://pastebin.com/v8sCENg7

Fullforce

**Comment by laz2727** [comment]
Increase your memory allocation. 1gb is way too little for mekanism.

**Comment by BluSunrize** [comment]
Yep. That's definitely the issue. 2gigs is the MINIMUM for modded Minecraft, although I would recommend 4gigs if possible.
