### ISSUE TITLE
1.10.2 Diesel Generator Crash

### ISSUE THREAD

**Issue by Pkr1345** [BluSunrize/ImmersiveEngineering#1353]
When testing the forestry Biomass and Ethanol in the diesel generator, game crashed immediately and is dead until either mod is removed. 

Crash report
http://pastebin.com/ikcZjgHL

**Comment by mindforger** [comment]
soo you found out you are having a similar issue to https://github.com/BluSunrize/ImmersiveEngineering/issues/1308#issuecomment-243285118 so why dupe posting then? 
please close this one :)

**Comment by BluSunrize** [comment]
Always search before you report.
