### ISSUE TITLE
Strange cruser rendering [1.10.2][0.10-38]

### ISSUE THREAD

**Issue by gt22** [BluSunrize/ImmersiveEngineering#1354]
In JEI crusher rendering rotated a bit, cannot descripe, just look at screenshot
![image](https://cloud.githubusercontent.com/assets/17099450/18087534/617cb35e-6ebe-11e6-9ab4-32bdc230866a.png)

**Comment by Bitterholz** [comment]
@gt22  Im almost tempted to say this is intentional...

@BluSunrize If it is, I think it looks good this way.

**Comment by BluSunrize** [comment]
Fixed for upcoming release, see commit above
