### ISSUE TITLE
[1.10.2][0.10-38] Invissible models

### ISSUE THREAD

**Issue by DrVexsear** [BluSunrize/ImmersiveEngineering#1355]
OS: Netrunner 17
Information on 1 screenshot
Connectors, transformator and don't know yet not render.
It's may be optifine, but optifine need me.
![6](https://cloud.githubusercontent.com/assets/20053056/18093279/076a36a6-6ed8-11e6-9517-85e1b20d6efa.png)
![2016-08-30_17 32 52](https://cloud.githubusercontent.com/assets/20053056/18093365/4411d83e-6ed8-11e6-92e5-284d1036628d.png)
![2016-08-30_17 32 56](https://cloud.githubusercontent.com/assets/20053056/18093366/4416c9ac-6ed8-11e6-896b-6b00b24aefa1.png)
![2016-08-30_17 33 03](https://cloud.githubusercontent.com/assets/20053056/18093367/44256ec6-6ed8-11e6-8ad9-b61e066eb52f.png)

**Comment by Bitterholz** [comment]
First, try without Optifine, that mod really just messes every others mods models up.
Second pls choose a more descriptive Title... "Don't Render" sounds like you IE to stop rendering things.

Also, this issue is known and will likely be fixed in IE-Build 39

**Comment by Bitterholz** [comment]
@DrVexsear reason for your closing of the issue pls

**Comment by BluSunrize** [comment]
Because it is optifie. And optifine issues are not dealt with. Closing is legitimate.

**Comment by Bitterholz** [comment]
@BluSunrize well he didnt state that it came diwn to OF derping shit up again. But yeah i was expecting that. Its just a manner of friendlyness to update ones issue with a "(Not)Solved by XYZ"

**Comment by mindforger** [comment]
@Bitterholz, look up the other issues that already deal with the problem
you are not the first, so it's also a duplicate issue ... 
and now wait until Malte has a chance to throw in his idea and let it compile

**Comment by Bitterholz** [comment]
I know it is duplicate and its not my issue. All im saying is its good practice to comment on what did or didnt fix your issue. Not just close it with a "might be X"

**Comment by mindforger** [comment]
> I know it is duplicate and its not my issue

then you should know that this repeating pattern of issues with all the same content take time to answer and start to get annoying very fast, thus it is helpfull to view other peoples issues first, check if there is beeing worked on and consider of attaching your own 2 cents if they are worth to mention or wait and monitor the topic for a upcoming solution

**Comment by DrVexsear** [comment]
At furst, I'm from russia and my knowleges of English on level: I bed. And I translate all verbatim.
Reason it's your answer, Bitterholz. 

> Also, this issue is known and will likely be fixed in IE-Build 39

Also, on half of issues, whats Viewed me did not have a transformer.

**Comment by DrVexsear** [comment]
And wires after rebooting also become invisibles.

**Comment by Bitterholz** [comment]
That issue will also likely be adressed in 0.10-39.
As far as i know, Malte allready has a fix for that cooked up

**Comment by mindforger** [comment]
> Also, on half of issues, whats Viewed me did not have a transformer

okay i see that point
you can then take one of the existing active issues and tell there that you have a similar probelm and **also** the whole transformer is not rendering (those issues do not "belong" to someone)
posting into an (active) issue with a problem that is very close to yours but having a different source is no problem, you will be informed then to post a new issue if required
but posting the (i believe it was) 10th time same issue to an known problem again makes _you_ look like you have never searched existing issues before ... it's really nothing against _you_ posting an issue, but about the general behaviour of other people postig issues before checking if it is already known or not ... and well your post just looked like exact such a person's post

**Comment by BluSunrize** [comment]
Transformer renders the same way connectors do. Hence, all the issues are exactly the same
