### ISSUE TITLE
Crash upon typing in Engineer's Manual

### ISSUE THREAD

**Issue by squirrelkiller** [BluSunrize/ImmersiveEngineering#1356]
I apologize with lack of crash log, it does not seem to be generating one.

Due to lack of log I have included the entirety of the current console output I could access:
http://pastebin.com/8HvPYqSt

Cause seems to be typing in the Manual. 
I am assuming this is the cause based on how it has happened, I have had it a few times in the journal but not sure if it is something else as I have tabbed out to come back to this crash, not sure what the cause is if I am wrong.

**Comment by mindforger** [comment]
your java runtime is crashing, do you have some more details or could you create an fresh new logfile and attach it?

**Comment by squirrelkiller** [comment]
I can pop in and do so immediately. The run time has crashed repeatedly while trying to get a proper crash report, each time related to the Manual. I basically need to push it until it crashes. I am unable to get this to crash again now that I specifically test the pages it has crashed in before while on, as well as the search function. It does not seem to be crashing. I am now suspecting it is because of time usage, rather than anything specific. I do know however it is ONLY happening in the Manual. Based off of several hours of play without an issue but when I go to study the Manual properly and sort through all the features to compare with other mods it crashes.

**Comment by BluSunrize** [comment]
Please check the logs folder and give us the latest from that. That should be a full log.

**Comment by squirrelkiller** [comment]
http://pastebin.com/iG3aRM3P

Sorry I have never had to report a crash lacking a proper log before.

**Comment by BluSunrize** [comment]
Huh. That doesn't include Forge's statistic report. Can you tell us how powerful your machine is, and how much memory you have allocated to Minecraft?

**Comment by AEnterprise** [comment]
looks like there is a bug in your JVM you ran into, usually updating java fixes these kinds of crashes

**Comment by mindforger** [comment]
@squirrelkiller just open your log folder from your minecraft installation, remove all files from the folder, start the game until it crashes, then go back to the log folder and attach them to your response, pastebin has a limited line count and truncates the needed informations
![snipsnip](https://cloud.githubusercontent.com/assets/2683555/18119092/2221044e-6f59-11e6-960b-167fa26d539e.PNG)

**Comment by squirrelkiller** [comment]
System specs from a crash report of an unrelated crash, same instance nothing has been changed since then:

Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 446398304 bytes (425 MB) / 3069706240 bytes (2927 MB) up to 4056416256 bytes (3868 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4352m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.32 Powered by Forge 12.18.1.2075 93 mods loaded, 93 mods active
[all the stuff related to mods being loaded]
	Launched Version: forge-12.18.1.2075
	LWJGL: 2.9.4
	OpenGL: AMD Radeon R7 200 Series GL version 4.5.13447 Compatibility Profile Context 16.300.2311.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x AMD FX(tm)-6300 Six-Core Processor

**Comment by squirrelkiller** [comment]
This is the file after it got moved into the .gz after a new instance was loaded. It is not truncating the issue.
[2016-08-31-2.log.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/446562/2016-08-31-2.log.txt)

**Comment by mindforger** [comment]
-Xmx**4352m** VS Memory: 446398304 bytes (425 MB) / 3069706240 bytes (2927 MB) up to 4056416256 bytes **(3868 MB)**

i am tempted to say this JVM should not even start but it looks like you got an memory problem there
more memory assigned to the JVM than your System can provide! reduce your max memory to 3GB

also what i was expecting, your client uses the default launcher JRE bundled with minecraft
please install Windows Offline (64-Bit) from the [java.com](http://www.java.com/de/download/manual.jsp) site

**Comment by BluSunrize** [comment]
Yeah, I figured as much. Memory mismatch. Mindforger put it perfectly.

**Comment by squirrelkiller** [comment]
Stange it using that, as I have the latest (installed last night) JDK installed I also have 8GB of memory, which is odd. No idea what is up there then. IDK, blame Java. Strange that only your manual has triggered this after 4 hours of game play.

**Comment by mindforger** [comment]
the JDK does not always properrly register the JRE thus Minecraft may fallback to the default bundled version, you can also check your launcher profile, ther is a field for the JVM location
do you use FTB launcher or default launcher?

**Comment by squirrelkiller** [comment]
Curse launcher. It is not detecting the JRE now that I go digging, Gonna reinstall then just grab the JRE if that fails.

**Comment by mindforger** [comment]
Curse is using the default Launcher, you may open the Standard Launcher (it may be hidden somewhere when installed via curse) and edit your curse related profile manually

**Comment by squirrelkiller** [comment]
Ok that fixed it. Turns out you need to toggle a seemingly (at a glance) unrelated option to be able to allow Curse to just force your JRE on Minecraft, (Grumble this is why I liked MultiMC grumble grumble never had these issues grumble.)

Thank you for the assistance.

Now back to making sense of all that autoprocessing.

**Comment by mindforger** [comment]
all just a thing of acclimatization :) if MultiMC just had provided a simple share modpack function like curse does without registration crap, I would have prefered it over curse client ... depends on your requirements obviously but taste is something that should not be argued about
