### ISSUE TITLE
Creosote Oil cannot be removed from Coke Oven/ Creosote Oil item missing

### ISSUE THREAD

**Issue by TheYaMeZ** [BluSunrize/ImmersiveEngineering#1357]
I've made my first Coke oven in the game and while trying to make treated wood I realized that the Treated Wood recipe doesn't include Creosote oil, it's just an empty space in the middle.
Most likely because of this, i'm unable to put a bucket or bottle into the output slot of the coke oven to get the oil out.
IE is the only mod i've installed.

Version 10.38 of IE
Version Build 2076 of forge (Also tried 2011)
Minecraft 1.10.2

**Comment by BluSunrize** [comment]
Has already been addressed and fixed for the coming version
