### ISSUE TITLE
Solidity Problems on certain Modells

### ISSUE THREAD

**Issue by Bitterholz** [BluSunrize/ImmersiveEngineering#1358]
As of the latest Changeset from August 31, certain Modells appear as Solid blocks.
This results in Lighting Problems and wrongly applied Backface Culling, causing a "look through the world" problem on all blocks wich have a side next to said modells.

Occurs both on SSP and SMP, no extra mods installed

Some Images to clarify:
![2016-09-01_09 45 21](https://cloud.githubusercontent.com/assets/3910862/18160623/9f764fb4-702e-11e6-8958-e87c526fa67f.png)
![2016-09-01_09 46 56](https://cloud.githubusercontent.com/assets/3910862/18160635/a55f4fac-702e-11e6-8853-27ab7afc5b92.png)

Modells confirmed affected:
- Adv. Blast Furnace(lighting issue as well)
- Electric Lamp
- PreHeaters
- Fluid Pipes
- Tesla Coil
- Charger

**Comment by BluSunrize** [comment]
Funnily enough, I just noticed that myself. At least this gives me an error to close! =P

**Comment by BluSunrize** [comment]
Fixed for future release, see commit above
