### ISSUE TITLE
[Feature Request] allow changing the lanterns' "attachment point" with hammer

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#1359]
[0.8-32]
right now lanterns always get this attach-thingy when you place them against a block (except when placing them against the top of a block)
it'd be neat to be able to rotate through those different attachment orientations with the help of the hammer, to save some time when having something specific in mind
that is all :)

**Comment by BluSunrize** [comment]
Fixed for upcoming release, see commit above
