### ISSUE TITLE
[1.8.9][0.8-32]/[1.10.2][0.10-38] Minor: unpowered powered lanterns appear completely black

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#1360]
feels like a lighting issue, i dunno.
tested with both versions

**Comment by Bitterholz** [comment]
Fixed in upcomming version 0.10-39

**Comment by BluSunrize** [comment]
Yeah, should probably be the same issues other models had and should be fixed in future. However @MalkContent PLEASE read the contribution guidelines and actually show pictures next time.

**Comment by MalkContent** [comment]
will do
