### ISSUE TITLE
[1.10.2] Exavator Bucket-wheel not rotating correctly 

### ISSUE THREAD

**Issue by Crazy-KSK** [BluSunrize/ImmersiveEngineering#1361]
http://i.imgur.com/vUE5UQN.jpg
the Bucket-wheel always stays in the same orientation visually no matter the machines orientation 
nothing but building it seems to be required to make it happen

IE: build just now from 1.10 branch
Forge: 1.10.2-12.18.1.2076

**Comment by Bitterholz** [comment]
:+1:  can confirm

Also Bucketwheel markably decreases overall rendering performance when spinning. Down from 200~FPS to ~75
Not at all critical but could use some optimisation if possible(I know thats hard in MC)

**Comment by BluSunrize** [comment]
Fixed for future release, see commit above
