### ISSUE TITLE
[1.10.2] Ear Defender helmet causes inventory to glitch 

### ISSUE THREAD

**Issue by Crazy-KSK** [BluSunrize/ImmersiveEngineering#1362]
I combined a pair of Ear Defenders straight from the creative inventory  with a  golden helmet and put it on my head and now my inventory looks like this http://i.imgur.com/fozs00Z.png as you can see it also makes water not render
might take a few times opening and closing to make it happen, it also seems to be strangely directional so some spinning around may be required 

IE: build just now from 1.10 branch
Forge: 1.10.2-12.18.1.2076

Edit: they also don't render right on the player 
item in hand = http://i.imgur.com/q3qCXYP.jpg
no item = http://i.imgur.com/1Dag4V9.jpg
switching between item and none also makes entities and the moving parts of IE machines flicker

**Comment by BluSunrize** [comment]
Fixed for future release, see commit above
