### ISSUE TITLE
[1.10.2] Posts arms not rendering correctly 

### ISSUE THREAD

**Issue by Crazy-KSK** [BluSunrize/ImmersiveEngineering#1363]
http://i.imgur.com/b2yq3Jo.jpg
hammering a post to add an arm either makes and invisible arm, an arm without collision or renders a post in place of an arm

IE: build today from 1.10 branch
Forge: 1.10.2-12.18.1.2076

**Comment by Bitterholz** [comment]
:+1:  can confirm.
Either the arm has no BB or has a BB and is invisible. Havent had a new post rendered yet.

Will test on for block updates eg.

**Comment by BluSunrize** [comment]
The rendering a post in place is just lack of an update. Next block placement in that chunk fixes it.
Cannot reproduce lack of bounding boxes

**Comment by Crazy-KSK** [comment]
Can't seem to make the bounding box disappear either anymore must have been a fluke

**Comment by BluSunrize** [comment]
Closed then.
