### ISSUE TITLE
[0.8-32]/[0.10-38] Minor: (normal) Lanterns provide torch light level, not glowstone

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#1367]
Engineer's Manual states Lanterns would provide the same light as glowstone, but they emit light level 14 in their own block, not 15.
Powered Lanterns _do_ emmit glowstone level light.

white wool block has light level 1 when standing on top:
![lanternlight](https://cloud.githubusercontent.com/assets/7753414/18200101/8072b0dc-7103-11e6-9ddb-5ae31481451f.png)

**Comment by kane-thornwyrd** [comment]
Work as intended I guess. Seems like a good motivation to power his lanterns, right ?

**Comment by MalkContent** [comment]
Maybe. It is still at odds with the description in the Engineer's Manual. I don't particularly care what changes.

**Comment by BluSunrize** [comment]
Fixed by commit above btw.
