### ISSUE TITLE
Crushing Ores not working

### ISSUE THREAD

**Issue by TheVanoq** [BluSunrize/ImmersiveEngineering#137]
The crafting recipe of "Engineer's Hammer" in combination with any ingot does not work. Grit cannot be produced.

Latest Forge-Version, latest IE-Version.

https://i.imgur.com/GYOY9lb.png

**Comment by wafflemans** [comment]
It works for me
![2015-06-27_21 03 22](https://cloud.githubusercontent.com/assets/10857677/8395103/085937e4-1d10-11e5-84db-b063bf9ebc8d.png)

**Comment by TheVanoq** [comment]
So some other mod must be interfering.

http://i.imgur.com/MOura9h.png

Any known incompatibilities?

**Comment by TheVanoq** [comment]
Logfile: http://pastebin.com/raw.php?i=0gSV2p1w

**Comment by wafflemans** [comment]
Just did some testing, and it looks like thermal expantion/foundation is causing the problem

**Comment by TheVanoq** [comment]
Is there any way to fix this using configs without disabling any of the mods? I would like to play with both mods but sadly this makes progression in IE impossible, as you probably know.

Thanks for the quicky replies by the way, I appreciate it!

**Comment by AEnterprise** [comment]
this is intended, if other mods adds a dust or a metal IE doesn't add the grit crafting recipe but you should be able to use the TE iron dusts instead of the grit in recipes

**Comment by BluSunrize** [comment]
@AEnterprise got it right. That recipe only exists for crushing ores when using IE standalone. It is disabled when another mod adds the dust, because I have to assume that they also add a way of generating said dust.
It is solely for earlygame standalone IE, but is disabled when stuff like pulverizers exist, because balance.

**Comment by ewanm89** [comment]
Just  a note shouldn't something be done in the Engineer's Manual to make this clear, as reading the ore processing section does not mention this in any way.
