### ISSUE TITLE
[0.10-38] revolver inventory slots accept whole stacks when shift-clicked into

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#1371]
A stack of cartridges in a chamber slot doesn't give you more ammo, but get's wasted in a single shot and replaced with a single casing.  
Anywho, mildly annoying because this way, you can't shift-click spam until you reloaded your revolver.

edit: this is not an issue in the 0.8 version, to save you the trouble :)

**Comment by BluSunrize** [comment]
Fixed for future release, see commit above
