### ISSUE TITLE
[0.10-38] revolver dualwielding has both revolvers shoot at once

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#1372]
...which makes it look super cool, but, thanks to post-damage invurnability, rather ineffective.
Suggestion: either make them fire alternately or hack it so the left revolver is fired with lmb when wielding two revolvers.
The former method keeps the ability to punch (because you might have a bayonett or want to break potatoes or something), the second one allows you to fire a select revolver, which you might want to do, say, because of it being loaded with different ammo. (say, one revolver with buckshot, one casull)
Just my 2 cents

**Comment by BluSunrize** [comment]
Already dealt with.
