### ISSUE TITLE
[1.10.2] Two Arc Furnace bugs

### ISSUE THREAD

**Issue by Crazy-KSK** [BluSunrize/ImmersiveEngineering#1373]
1. Per one item of steel produced it takes 4 items of coke dust one from each of the 4 slots.
2. A full furnace can't keep up with outputting all the slag, looks like it only outputs one slag per cycle even though 12 have been produced it also doesn't output any at all if the slag slot is full.

IE: build today from 1.10 branch
Forge: 1.10.2-12.18.1.2076

**Comment by BluSunrize** [comment]
Fixed for future releases, see commit above
