### ISSUE TITLE
[1.10.2] Breaking a block of the miner while its running causes the wheel to keep turning

### ISSUE THREAD

**Issue by Crazy-KSK** [BluSunrize/ImmersiveEngineering#1374]
http://i.imgur.com/LcAcuvQ.jpg
Breaking a block of the miner while its running causes the wheel to keep turning it also flipped in this case and stayed flipped once I reformed it also sometimes turns black until the miner is reformed.
http://i.imgur.com/7QWhimG.jpg
No blackness while its formed properly though. 

IE: build today from 1.10 branch
Forge: 1.10.2-12.18.1.2076

**Comment by BluSunrize** [comment]
Okay, can you try that again with a proper and factual report? And maybe some punctuation? "turns back in shame" is hardly scientific.
