### ISSUE TITLE
[0.8-32]/[0.10-38] Diesel Generator doesn't connect to pipes when Redstone Engineeringblock is on left side

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#1379]
It works fine if the redstone engineering block is on the right side.
The back here being the radiator blocks, the front being the generator blocks.
![dieselgennopipeconnection](https://cloud.githubusercontent.com/assets/7753414/18226859/05f28c40-7213-11e6-99e2-0a7c180ab27a.png)

**Comment by BluSunrize** [comment]
Fixed for future releases, see commit above
