### ISSUE TITLE
Wires dont attach to connectors after waiting a while.

### ISSUE THREAD

**Issue by XMertdx** [BluSunrize/ImmersiveEngineering#138]
Guys i used electrum wires and mv connectors a lot(know electrum is mv from forge craft) but and they always connect. But after sometime when i tried to attach another electrum wire to connector, it said "You cannot connect this wire to here". To attach i always need to replace but to connect previous wires , i need to break all of previous connectors too. İs this a bug or did i miss something?

**Comment by XMertdx** [comment]
I know, very bad spelling :D

**Comment by mindforger** [comment]
this is an known bug and will be fixed in next version :)

**Comment by XMertdx** [comment]
Thanks :)
