### ISSUE TITLE
[1.10.2] Industrial Hemp seeds can be planted on any soil block

### ISSUE THREAD

**Issue by Roxforbraynz** [BluSunrize/ImmersiveEngineering#1380]
IE 0.10-38
Forge 1.10.2 - 12.18.1.2056

Industrial hemp is plantable on dirt, grass, (most likely) mycelium, and BiomesOP custom dirt/grass in addition to farmland. More soil blocks added by other mods are likely.

**Comment by Majestyc2k1** [comment]
I can also verify non-tilled Fertilized Soil from Random Things.

**Comment by BluSunrize** [comment]
Fixed for future releases, see commit above
