### ISSUE TITLE
Problem with mcmode.info file

### ISSUE THREAD

**Issue by TeddyTheBeer** [BluSunrize/ImmersiveEngineering#1382]
I can't fully enjoy the mode because MC tells me that I have no mcmde.info file. This apparently result in Coke oven not filling bottles with oil and machines not working even though they are all powered.

**Comment by AEnterprise** [comment]
those are 2 seperate things, the mcmod.info file has no impact at all on how the mod works

**Comment by BluSunrize** [comment]
Always provide a log. And this is not an issue. Has zero effect on the game

**Comment by TeddyTheBeer** [comment]
Thank you for your response. Still, Coke oven does not fill bottles with oil and machines not working even though they are all powered.

**Comment by BluSunrize** [comment]
Issue one is alredy fixed
issue two you might wanna report in a separate thread. And please read the contribution guidelines this time.

**Comment by TeddyTheBeer** [comment]
Sorry. But I am too old and new in MC. This is the first time I use forum and report sthg.

**Comment by BluSunrize** [comment]
That's fine, you can learn after all.
