### ISSUE TITLE
Problem with immersive eng. mode

### ISSUE THREAD

**Issue by TeddyTheBeer** [BluSunrize/ImmersiveEngineering#1383]
Thank you for your response. Still, Coke oven does not fill bottles with oil and machines not working even though they are all powered. Conveyor belts cannot be placed and most object are totally black.

I installed everything (minecraft, forge and mode) again but the problem is the same.

**Comment by TeddyTheBeer** [comment]
![2016-09-04_13 54 15](https://cloud.githubusercontent.com/assets/21981522/18230850/f9af32a4-72a7-11e6-8f4c-bf45129b1814.png)

**Comment by TeddyTheBeer** [comment]
I is impossible to place conveyor belts. That arrow is all I get.

**Comment by TeddyTheBeer** [comment]
![2016-09-04_14 03 18](https://cloud.githubusercontent.com/assets/21981522/18230861/6cca9d14-72a8-11e6-9652-d09f522b4512.png)

And I still can't fill bottles with oil even when coke oven is full.

**Comment by BluSunrize** [comment]
...right, one by one.
First off, please use the search function before you open new issues. Secondly, it's advisable to make different issue threads for different issues. Reporting them all in one makes it very hard for me to keep track.
Coke Bottles are deprecated. They will be removed. Buckets cannot be filled in the oven, that is a know bug and has been fixed. You can find multiple issues already reported of that.
The Conveyors have ALSO been fixed already. Once again, the clsoed issues include this as reported and fixed.
The black rendering is fixed as well.

Finally "Machines not working even though they are all powered" tells me nothing. I need to know which machines, what they fail to do and see pictures of your setup.

**Comment by TeddyTheBeer** [comment]
Thank you for your patience. One more thing. If all these issues are fixed
where can I get fixed mode? I have just download it again and there are no
changes.



2016-09-04 14:07 GMT+02:00 BluSunrize <notifications@github.com>:

**Comment by BluSunrize** [comment]
The fixed build isn't released yet. I have fixed the issues all and pushed the fixes to here, but they only go live when I release the next version (version numer 39) on Curse. There is no ETA for that.

**Comment by TeddyTheBeer** [comment]
Ok. I will wait. Thank you.

2016-09-04 14:19 GMT+02:00 BluSunrize <notifications@github.com>:

**Comment by bookerthegeek** [comment]
@BluSunrize

You are a patient person that is for sure.

**Comment by BluSunrize** [comment]
I'm usually not. I'm tryign to better myself =P

**Comment by TeddyTheBeer** [comment]
The best lesson about patience I got from Yoda when StarWars were first
played in Poland

2016-09-04 22:47 GMT+02:00 BluSunrize <notifications@github.com>:
