### ISSUE TITLE
[Question] How to get liquids out of the big tank

### ISSUE THREAD

**Issue by Dijkstra1** [BluSunrize/ImmersiveEngineering#1386]
In Immersive Engineering to pull liquids out of tank, one needs a pump if it does not auto push out, maybe i missing something as i can put the pump on the big tank from Immersive Engineering as the block for outputting liquids from only has one tall gap around and the pump is to block tall and does not line up with out put, therefor I can not pull liquids out of my tank. I also tried putting pipe on the bottom of the output, hoping that liquids would auto output but seems not.

**Comment by MalkContent** [comment]
pipe at bottom block, add redstone signal to bottom block -> auto output

**Comment by Dijkstra1** [comment]
Thanks will give that ago

**Comment by mindforger** [comment]
i think @BluSunrize has made a special exception for this case when you place the pump adjacent to the bottom block and put a pipe inbetween it will work as if it is attached to it, but only for this special case as i remember

**Comment by BluSunrize** [comment]
Somewhat. I allowed the tank to output 144mb/T, but pumps only take 50mb, UNLESS there is a pump down the line. That allows them to accept more

**Comment by grabvba** [comment]
I am also having trouble getting the tank to supply fuel to the diesel generator. The tank's input is on the top. Output is on one of the sides of the bottom block (I have tried all five sides of the block) there is one pipe segment, a powered fluid pump (input on the tank side, output on the generator side) with a lever attached to the first pipe segment on the output side (also tried input side), and 4 pipe segments connecting to the left side of the generator. I have also tried the same setup without the pump. The generator has a HV connector connected to a HV capacitor via HV cable. Can not get the generator to run. 

When I attach the generator directly to my refinery and bypass the tank and pump, the generator will run.

1.10.2
IE Build 10-38

As with my last report, server is online. Have not tested the tank in single player.

**Comment by BluSunrize** [comment]
If the Tank does not have a redstone signal on the bottom block, it will not output. And the pump will not draw from a distance.

**Comment by grabvba** [comment]
I still can not get it to work. I even put a redstone torch directly on the bottom block of the tank. 

http://imgur.com/a/hbvo5

**Comment by BluSunrize** [comment]
Is the pump set to input on the other side?

**Comment by grabvba** [comment]
Yes it is.

**Comment by BluSunrize** [comment]
I'll look into it

**Comment by BluSunrize** [comment]
There we go, fixed for version 40. It's currently building, but curse approval is slow atm so it might be an hour or two.

**Comment by BluSunrize** [comment]
Actually, it approved surprisingly fast!
Here you go! 
https://minecraft.curseforge.com/projects/immersive-engineering/files/2328568

**Comment by grabvba** [comment]
Awsome thanks! I need to head to bed. I will test it tomorrow and get back to you.

**Comment by grabvba** [comment]
Ok -40 allowed us to transfer fluid from one tank to another and vice versa. However we are still unable to  fuel and run the generator. Tried with and without a pump. Tried re-building the generator, tried a rs torch on the generator as well as a lever. When we connect our refinery directly to the generator, the generator runs. It seems to not run when connected to a tank.

**Comment by happysmash27** [comment]
I have the same problem. Has this been solved yet?

**Comment by happysmash27** [comment]
I have it powered, redstone on both the tank and pump, everything! Still no generator running though...

**Comment by BluSunrize** [comment]
Please don't necropost on a 2 1/2 year old issue. Yes, it was solved immediately by someone actually reading how it works.
You'll need to provide pictures of your setup for us to even attempt to assist you.

**Comment by happysmash27** [comment]
I ended up fixing it on my own – apparently the problem was that I forgot to connect the bottom of the tank to the main system at all 🤦
