### ISSUE TITLE
Railgun charge level interface

### ISSUE THREAD

**Issue by Zorg14** [BluSunrize/ImmersiveEngineering#1387]
Hi, Blu! I've got an issue with your mod. When I pick up railgun I don't see charge level emitter as it used to be. It's not so big deal, but I think it would be nice to fix this little bug)
Minecraft v. 1.10.2
Immersive Engineering v. 0.10-38
no other mods at all.

Maybe I'm doing something wrong?)

![2016-09-05_22 57 02](https://cloud.githubusercontent.com/assets/22012202/18255653/56208dfa-73b4-11e6-9e6e-989207c035fa.png)

**Comment by BluSunrize** [comment]
Latest release has a charge counter again!
