### ISSUE TITLE
Squeezer/Fermenter Crash

### ISSUE THREAD

**Issue by zcorcoran** [BluSunrize/ImmersiveEngineering#1388]
The Squeezer and Fermenter crash in 0.10-39 for me when they actually start to do work. Running Forge 12.18.1.2076.

If I put a stack of items (of any amount) into either machine, they start working, then the game crashes. This crash report is from the Squeezer. replicated in a fresh instance with only Forge and IE: http://pastebin.com/k2UeeAcu

**Comment by zcorcoran** [comment]
Looks like the refinery does the same thing. The crash looks essentially identical each time, with the last line in the stacktrace (i.e. at blusunrize.immersiveengineering.common.blocks.metal.TileEntityRefinery.func_73660_a(TileEntityRefinery.java:61)) referencing whichever machine is the culprit.

**Comment by BluSunrize** [comment]
ah crap
I know what caused that.

**Comment by BluSunrize** [comment]
Fixed for version 40. It's currently building, but curse approval is slow atm so it might be an hour or two.

**Comment by BluSunrize** [comment]
Actually, it approved surprisingly fast!
Here you go! 
https://minecraft.curseforge.com/projects/immersive-engineering/files/2328568
