### ISSUE TITLE
NPE attempting to use Assembler

### ISSUE THREAD

**Issue by gchpaco** [BluSunrize/ImmersiveEngineering#1391]
Version is 0.10-40.  Assembler has creosote in it, and I was attempting to get it to make treated wood but accidentally made a chest shape with oak planks while oak planks were in inventory, after which it died.  Leftmost recipe slot was empty.

Crashlog as follows:
[crash-2016-09-06_02.34.37-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/456387/crash-2016-09-06_02.34.37-server.txt)

**Comment by gchpaco** [comment]
Should add, it now crashes every time on startup now.

**Comment by BluSunrize** [comment]
Thanks, will look into it!

**Comment by BluSunrize** [comment]
Fixed for future releases, see commit above!
