### ISSUE TITLE
[0.8-32]/[0.10-40] Crate Comparator-Output does not update when content changed by automation

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#1392]
i.e. in/output by hopper/hopper cart/conveyor will not update the comparator output.
maybe it requires the gui to show up/comparator output is updated on gui close?
edit: i am mostly adding the 0.8 version as an affected one so you can be sure that it's not a bug that came from the conversion 1.8.9 -> 1.10.2

**Comment by BluSunrize** [comment]
It does indeed, I have noticed that myself. Will be addressed.

**Comment by MalkContent** [comment]
hooray :)
Little sidenote: I tried to workaround with dropping conveyors over a chest, but that means you can't open the chest (because of the conveyor) and also not measure the chest with a comparator. Might just stay this way, but thought it worth mentioning.

**Comment by BluSunrize** [comment]
Fixed for future releases, see commit above!
