### ISSUE TITLE
All Engineer's Blueprints Traded For Are Blank

### ISSUE THREAD

**Issue by DMIL421** [BluSunrize/ImmersiveEngineering#1393]
Playing on a server, using current release from CurseForge.

[crash-2016-09-06_12.35.38-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/457613/crash-2016-09-06_12.35.38-client.txt)

I've been trading with IE villagers for the last hour or so, and every one of the Engineer's Blueprints that I've gotten at rank 4 trades has been blank. Is this intended? I could be missing some aspect. I'm trying to get the Graphite Electrodes BP specifically, but I've not gotten any of the other blueprints either.

**Comment by Pihrra** [comment]
I've just noticed the same thing on my world but I can't be sure the villager in question didn't spawn while running a previous version of IE.

**Comment by BluSunrize** [comment]
Fixed for future releases, see commit above
