### ISSUE TITLE
[0.10-40]Assembler not using  internal creosote oil

### ISSUE THREAD

**Issue by GeneWeaver** [BluSunrize/ImmersiveEngineering#1394]
assembler will only use buckets of oil not internal tank.

forge-1.10.2-12.18.1.2076
ImmersiveEngineering-0.10-40

PS love the mod thanks a ton

**Comment by grabvba** [comment]
Same build, can confirm.

**Comment by BluSunrize** [comment]
Fixed for future releases, see commit above!
