### ISSUE TITLE
Port MineTweaker support in the 1.9.4/1.10.2 version

### ISSUE THREAD

**Issue by majix560** [BluSunrize/ImmersiveEngineering#1395]
Please port the MineTweaker for minecraft 1.7.10 to the minecraft 1.9.4/1.10.2 version of IE using CraftTweaker,
which is the minecraft 1.8.9/1.9.4/1.10.2 port of MineTweaker
Edit:
Repost of a comment on the wrong repo.
https://github.com/jaredlll08/CraftTweaker/issues/54

**Comment by BluSunrize** [comment]
Done! Latest release has compat again
