### ISSUE TITLE
Crash when starting client

### ISSUE THREAD

**Issue by Malfisogoro** [BluSunrize/ImmersiveEngineering#1396]
[crash-2016-09-06_18.14.52-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/457985/crash-2016-09-06_18.14.52-client.txt)

[fml-client-latest.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/457986/fml-client-latest.txt)

Without Immersive Engineering, everything loads ok. If it's a conflict, I'm not sure what with. I'm really looking forward to adding this mod to my modpack.

**Comment by Kiyaku** [comment]
Remove optifine, it should load then. Current version doesn't seem to work with IE.

**Comment by Malfisogoro** [comment]
Yeah, that fixed it.. Wish they'd play nice together because Optifine is required by the Conquest Reforged mod, but if I have to pick between the two, I think I'll take Immersive Engineering.

**Comment by mindforger** [comment]
it has been reported to optifine already, let's see what happens there
