### ISSUE TITLE
1.7.10 issue with powering IC2 wires

### ISSUE THREAD

**Issue by KyeDuo** [BluSunrize/ImmersiveEngineering#1397]
I am still in 1.7.10 and noticed this issue. (I also don't know if you still work on 1.7.10)
I can receive power from IC2 wires, but I have encountered an issue where a setup would not power the wires:
big reactor steam turbines were the power source
HV connectors and wires were used
tested with IC2 glass fiber and IC2-HV wires
nothing attached to the IC2 wires would get power, but directly connecting the IE-HV wires to the devices would result in power flow.

mods list
mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1566-1.7.10.jar) 
Forge{10.13.4.1566} [Minecraft Forge](forge-1.7.10-10.13.4.1566-1.7.10.jar) 
CodeChickenCore{1.0.7.47} [CodeChicken Core](minecraft.jar) 
NotEnoughItems{1.0.5.120} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
OpenComputers|Core{1.5.22.46} [OpenComputers (Core)](minecraft.jar) 
PlayerAPI{1.4} [Player API](minecraft.jar) 
RenderPlayerAPI{1.4} [Render Player API](minecraft.jar) 
RenderPlayerAPIEnhancer{1.4} [Render Player API Enhancer](minecraft.jar) 
SmartCore{1.0.3} [Smart Core](minecraft.jar) 
OpenModsCore{0.9.1} [OpenModsCore](minecraft.jar) 
<CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
WarpDriveCore{1.7.10-1.3.27.-} [WarpDriveCore](minecraft.jar) 
BinniePatcher{1.7.1} [Binnie Patcher](minecraft.jar) 
FastCraft{1.23} [FastCraft](fastcraft-1.23.jar) 
battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye](1.7.10-MB_Battlegear2-Bullseye-1.0.8.3.jar) 
zeldaswordskills{1.7.10-2.4} [Zelda Sword Skills](1.7.10-zeldaswordskills-2.4.jar) 
qCraft{${version}} [qCraft]([1.7.10] qCraft-1.2-OpenMCport-RobijnvogelTweak.jar) 
DamageIndicatorsMod{3.2.3} [Damage Indicators]([1.7.10]DamageIndicatorsMod-3.2.3.jar) 
CoFHCore{1.7.10R3.1.3} [CoFH Core](CoFHCore-[1.7.10]3.1.3-327.jar) 
BuildCraft|Core{7.1.17} [BuildCraft](buildcraft-7.1.17.jar) 
BuildCraft|Silicon{7.1.17} [BC Silicon](buildcraft-7.1.17.jar) 
BuildCraft|Transport{7.1.17} [BC Transport](buildcraft-7.1.17.jar) 
BuildCraft|Factory{7.1.17} [BC Factory](buildcraft-7.1.17.jar) 
additionalpipes{4.7.0} [Additional Pipes](additionalpipes-4.7.1.jar) 
IC2{2.2.825-experimental} [IndustrialCraft 2](industrialcraft-2-2.2.825-experimental.jar) 
ImmibisCore{59.1.1} [Immibis Core](immibis-core-59.1.1.jar) 
AdvancedRepulsionSystems{59.0.3} [Advanced Repulsion Systems](adv-repulsion-systems-59.0.3.jar) 
AdvancedMachines{59.0.2} [Advanced Machines](advanced-machines-59.0.2.jar) 
armourersWorkshop{1.7.10-0.39.6} [Armourer's Workshop](Armourers-Workshop-1.7.10-0.39.6.jar) 
plushieWrapper{0.0.0} [Plushie Wrapper](Armourers-Workshop-1.7.10-0.39.6.jar) 
bdlib{1.9.4.109} [BD Lib](bdlib-1.9.4.109-mc1.7.10.jar) 
BiblioCraft{1.11.4} [BiblioCraft](BiblioCraft[v1.11.4][MC1.7.10].jar) 
Forestry{4.2.15.63} [Forestry for Minecraft](forestry_1.7.10-4.2.15.63.jar) 
BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition](BiblioWoods[Forestry][v1.7].jar) 
BigReactors{0.4.3A} [Big Reactors](BigReactors-0.4.3A.jar) 
BinnieCore{2.0-pre14} [Binnie Core](binnie-mods-2.0-pre14.jar) 
Botany{2.0-pre14} [Botany](binnie-mods-2.0-pre14.jar) 
ExtraBees{2.0-pre14} [Extra Bees](binnie-mods-2.0-pre14.jar) 
ExtraTrees{2.0-pre14} [Extra Trees](binnie-mods-2.0-pre14.jar) 
Genetics{2.0-pre14} [Genetics](binnie-mods-2.0-pre14.jar) 
qmunitylib{1.0} [QmunityLib](QmunityLib-1.7.10-0.1.114-universal.jar) 
bluepower{0.2.962} [Blue Power](BluePower-1.7.10-0.2.962-universal.jar) 
BuildCraft|Builders{7.1.17} [BC Builders](buildcraft-7.1.17.jar) 
BuildCraft|Energy{7.1.17} [BC Energy](buildcraft-7.1.17.jar) 
BuildCraft|Robotics{7.1.17} [BC Robotics](buildcraft-7.1.17.jar) 
BuildCraft|Compat{7.1.5} [BuildCraft Compat](buildcraft-compat-7.1.5.jar) 
CarpentersBlocks{3.3.8} [Carpenter's Blocks](Carpenter's Blocks v3.3.8 - MC 1.7.10.jar) 
chococraft{4.1.5} [Clienthax's ChocoCraft](ChocoCraft-4.1.5.jar) 
CloudMaster{1.0} [CloudMaster](CloudMaster_1.7.10-1.3.jar) 
BuildMod{v1.0} [Build Mod](coroutil-1.1.3 for MC v1.7.10.jar) 
CoroPets{v1.0} [CoroPets](coroutil-1.1.3 for MC v1.7.10.jar) 
CoroAI{v1.0} [CoroAI](coroutil-1.1.3 for MC v1.7.10.jar) 
ExtendedRenderer{v1.0} [Extended Renderer](coroutil-1.1.3 for MC v1.7.10.jar) 
ConfigMod{v1.0} [Extended Mod Config](coroutil-1.1.3 for MC v1.7.10.jar) 
craftguide{1.6.8.2} [CraftGuide](CraftGuide-1.6.8.2-forge.jar) 
creativecore{1.2.0} [CreativeCore](CreativeCore v1.2.2 mc1.7.10.jar) 
CustomSpawner{3.3.0} [DrZhark's CustomSpawner](CustomMobSpawner 3.3.0.zip) 
darkcore{0.3} [Dark Core](darkcore-0.3-86.jar) 
DimensionalAnchors{59.0.3} [Dimensional Anchors](dimensional-anchor-59.0.3.jar) 
DragonsRadioMod{1.6.3} [Dragon's Radio Mod](DragonsRadioMod-MC1.7.10-1.6.3.jar) 
MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod](DrZharks MoCreatures Mod v6.3.1.zip) 
SlimevoidLib{2.0.4.7} [Slimevoid Library](SlimevoidLibrary-2.0.4.7.jar) 
DynamicTransport{0.1.2.0} [Dynamic Transport](DynamicTransport-0.1.2.0.jar) 
EnderStorage{1.4.7.33} [EnderStorage](EnderStorage-1.7.10-1.4.7.33-universal.jar) 
extracarts{1.7.10-0.8.0} [Extra Carts](ExtraCarts-1.7.10-0.8.0.jar) 
fairylights{0.6} [Fairy Lights](fairylights-0.6-1.7.10.jar) 
ForecastersBackpacks{@VERSION@} [Forecaster's Backpacks](ForecastersBackpacks-1.7.10-1.0.6.jar) 
Railcraft{9.12.2.0} [Railcraft](Railcraft_1.7.10-9.12.2.0.jar) 
ImmersiveEngineering{0.7.7} [Immersive Engineering](ImmersiveEngineering-0.7.7.jar) 
Mantle{1.7.10-0.3.2.jenkins184} [Mantle](Mantle-1.7.10-0.3.2.jar) 
Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct](TConstruct-1.7.10-1.8.8.jar) 
MagicBees{2.4.3} [Magic Bees](magicbees-1.7.10-2.4.3.jar) 
gendustry{1.6.3.132} [GenDustry](gendustry-1.6.3.132-mc1.7.10.jar) 
iChunUtil{4.2.2} [iChunUtil](iChunUtil-4.2.2.jar) 
GraviGun{4.0.0-beta} [GraviGun](GravityGun-4.0.0-beta.jar) 
IC2BackpackHUD{3.0} [IC2 Backpack HUD](IC2 Backpack HUD v3.0 - MC 1.7.10.zip) 
IGWMod{1.1.11-32} [In-Game wiki Mod](IGW-Mod-1.7.10-1.1.11-32-universal.jar) 
inventorytweaks{1.58-147-645ca10} [Inventory Tweaks](InventoryTweaks-1.58-147.jar) 
iridiummod{0.8} [Iridium Mod](iridiummod-1.7-0.8.jar) 
IronChest{6.0.62.742} [Iron Chest](ironchest-1.7.10-6.0.62.742-universal.jar) 
journeymap{5.1.4} [JourneyMap](journeymap-1.7.10-5.1.4-unlimited.jar) 
malisiscore{1.7.10-0.14.3} [MalisisCore](malisiscore-1.7.10-0.14.3.jar) 
malisisdoors{1.7.10-1.13.1} [Malisis' Doors](malisisdoors-1.7.10-1.13.1.jar) 
cfm{3.4.7} [§9MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.4.7%281.7.10%29.jar) 
Mystcraft{0.12.3.01} [Mystcraft](mystcraft-1.7.10-0.12.3.01.jar) 
NEIAddons{1.12.14.40} [NEI Addons](neiaddons-1.12.14.40-mc1.7.10.jar) 
NEIAddons|Developer{1.12.14.40} [NEI Addons: Developer Tools](neiaddons-1.12.14.40-mc1.7.10.jar) 
NEIAddons|AppEng{1.12.14.40} [NEI Addons: Applied Energistics 2](neiaddons-1.12.14.40-mc1.7.10.jar) 
NEIAddons|Botany{1.12.14.40} [NEI Addons: Botany](neiaddons-1.12.14.40-mc1.7.10.jar) 
NEIAddons|Forestry{1.12.14.40} [NEI Addons: Forestry](neiaddons-1.12.14.40-mc1.7.10.jar) 
NEIAddons|CraftingTables{1.12.14.40} [NEI Addons: Crafting Tables](neiaddons-1.12.14.40-mc1.7.10.jar) 
NEIAddons|ExNihilo{1.12.14.40} [NEI Addons: Ex Nihilo](neiaddons-1.12.14.40-mc1.7.10.jar) 
neiintegration{1.1.1} [NEI Integration](NEIIntegration-MC1.7.10-1.1.1.jar) 
ObsidiPlates{3.0.0.18} [ObsidiPlates](ObsidiPlates-1.7.10-universal-3.0.0.18.jar) 
OpenMods{0.9.1} [OpenMods](OpenModsLib-1.7.10-0.9.1.jar) 
OpenBlocks{1.5.1} [OpenBlocks](OpenBlocks-1.7.10-1.5.1.jar) 
ForgeMultipart{1.2.0.344} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.344-universal.jar) 
OpenComputers{1.5.22.46} [OpenComputers](OpenComputers-MC1.7.10-1.5.22.46-universal.jar) 
openmodularturrets{2.2.2-217} [Open Modular Turrets](OpenModularTurrets-1.7.10-2.2.2-217.jar) 
OpenPeripheralCore{1.3} [OpenPeripheralCore](OpenPeripheral-1.7.10-AIO-7.jar) 
OpenPeripheral{0.5.1} [OpenPeripheralAddons](OpenPeripheral-1.7.10-AIO-7.jar) 
OpenPeripheralIntegration{0.5} [OpenPeripheralIntegration](OpenPeripheral-1.7.10-AIO-7.jar) 
plantmegapack{4.29} [Plant Mega Pack](plantmegapack-4.29-1.7.10-1492.jar) 
PortalGun{4.0.0-beta-6} [PortalGun](PortalGun-4.0.0-beta-6.jar) 
PowerConverters{1.7.10_3.3.0-jenkins.76} [Power Converters](PowerConverters-1.7.10_3.3.0-jenkins.76.jar) 
SmartMoving{15.6} [Smart Moving](SmartMoving-1.7.10-15.6.jar) 
SmartRender{2.1} [Smart Render](SmartRender-1.7.10-2.1.jar) 
TardisMod{0.994} [Tardis Mod](tardismod-1.7.10-0.994-124-DS.jar) 
TiCTooltips{1.2.5} [TiC Tooltips](TiCTooltips-mc1.7.10-1.2.5.jar) 
tinkersdefense{1.2} [Tinkers' Defense](Tinkers-Defense-1.2.1.jar) 
Tubestuff{59.0.4} [Tubestuff](tubestuff-59.0.4.jar) 
TwilightForest{2.3.7} [The Twilight Forest](twilightforest-1.7.10-2.3.7.jar) 
chunkbase_villageinfo_ssp{2.1} [Village Info (SSP)](VillageInfoSSP-1.7.10-2.1.jar) 
WarpDrive{1.7.10-1.3.27.-} [WarpDrive](WarpDrive-1.7.10-1.3.27.-.jar) 
wawla{1.3.1} [What Are We Looking At](Wawla-1.3.1-1.7.10.jar) 
weaponmod{v1.14.3} [Balkon's WeaponMod](weaponmod-1.14.3.jar) 
weather2{v2.3.10} [Localized Weather & Storms](weather2-2.3.10 for MC v1.7.10.jar) 
WR-CBE|Core{1.4.1.9} [WR-CBE Core](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
WR-CBE|Addons{1.4.1.9} [WR-CBE Addons](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
WR-CBE|Logic{1.4.1.9} [WR-CBE Logic](WR-CBE-1.7.10-1.4.1.9-universal.jar) 
zcraftingmanager{1.1.0} [Crafting Manager](zCraftingManager ALPHA 1.0.18 mc1.7.10.jar) 
zssaddon{1.7.10-alpha-0.0.5-2} [Zelda Sword Skills - Addon](zeldaswordskillsaddon-v0.0.5a-2-.jar) 
zipline{1.0} [Zipline](Zipline-1.0%281.7.10%29.jar) 
zoommod{1.2} [zoommod](ZoomMod-1.2_1.7.10.jar) 
McMultipart{1.2.0.344} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.344-universal.jar) 
ForgeMicroblock{1.2.0.344} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.344-universal.jar) 
zcraftingmanagercore{1.1.0} [Crafting Manager Core](minecraft.jar)

**Comment by malte0811** [comment]
I believe this is a known issue that wasn't ever fixed, but 1.7.10 isn't being developed any more. IE for 1.8+ does not have EU compat, I am working on an addon adding wires that transfer EU (but no RF) though. The addon is mostly functional, I just need to talk to Blu about some changes to IE that would make writing the addon a lot easier (I am currently working with a modified version of IE for the addon) and add proper textures for the new connectors.

**Comment by KyeDuo** [comment]
I didn't expect it to be, but I still posted anyway. I do have a work around.
