### ISSUE TITLE
[0.10-40] Arc Furnace electrodes always "point" North.

### ISSUE THREAD

**Issue by 50m31-AW** [BluSunrize/ImmersiveEngineering#1398]
Regardless of which direction the front of the Arc Furnace itself is facing, its electrodes will always render with the forward center one towards the North with the other two to the Southeast/West of it.

https://imgur.com/a/TzxTx

IE: 0.10-40
Forge: 12.18.1.2076

**Comment by BluSunrize** [comment]
Fixed for future releases, see commit above
