### ISSUE TITLE
[0.10-40] Weird slab rendering with smooth lighting off.

### ISSUE THREAD

**Issue by 50m31-AW** [BluSunrize/ImmersiveEngineering#1399]
If smooth lighting is turned off, IE slabs render wierdly. Slabs in the lower half of a block will render near-pitch black on the top, and slabs in the upper half of a block will render near-pitch black on the bottom. Additionally, sanding on top of a slab in the lower half of a block will cause the horizon and sky to darken.

This doesn't happen with any of the vanilla slabs, just IE added ones.

https://imgur.com/a/CCncj

IE: [0.10-40]
Forge: 12.18.1.2076

**Comment by KnightMiner** [comment]
Sounds like Blu needs to set useNeighborLighting to true

**Comment by BluSunrize** [comment]
Fixed for future releases, see commit above
