### ISSUE TITLE
Hemp Seeds Not Planting

### ISSUE THREAD

**Issue by DoughnutDev** [BluSunrize/ImmersiveEngineering#14]
Hemp Seeds are not planting on farmland. I have ArgiCraft installed. So I am wondering if that is an issue with that. For now I added a recipe to turn hemp seeds into the actual plant from NEI and you can plant that.

**Comment by BluSunrize** [comment]
Can't reproduce that one. Screenshots?

**Comment by DoughnutDev** [comment]
They just don't plant due to argicraft crops sticks enable for vanilla
seeds.

**Comment by BluSunrize** [comment]
Doesn't seem to be a way for me to fix that, since AgriCraft seems to lack an API or IMC support

**Comment by DoughnutDev** [comment]
Ahh okay it is easy fix for server just disable the feature. I just wanted
to let you know so if anyone else has the issue.

**Comment by mallrat208** [comment]
I found something in AgriCrafts changelogs;


> +    -ADDED: Other mods can make their seed/fruit compatible by registering the seed as "seed<YourPlantName>" and the fruit as "crop<YourPlantName>" to the ore dictionary

I'm not sure if this is actually still functional however or if it would work in this instance.

**Comment by BluSunrize** [comment]
Doesn't work like that, sadly. AgriCraft would have to internally support IE seeds.

**Comment by DoughnutDev** [comment]
Yeah that should work.

**Comment by DoughnutDev** [comment]
Oops sorry my email did not refresh did not mean to post that to be rude.
It just did not show that you replied. Sorry Blu

**Comment by InfinityRaider** [comment]
I've added support for Hemp Seeds from my side.

**Comment by DoughnutDev** [comment]
Oh sweet thanks.

**Comment by BluSunrize** [comment]
Sweet deal, thanks! :D

**Comment by InfinityRaider** [comment]
Had to clone and compile your repo though, hope you don't mind.
