### ISSUE TITLE
Crash Placing a Connector on Big Reactors Power Tap

### ISSUE THREAD

**Issue by Stargazeer** [BluSunrize/ImmersiveEngineering#140]
I get this crash when placing a HV connector directly on a Big Reactors power tap. Just thought you should know.
http://pastebin.com/EEkAsLPx

Edit: Crash log moved to pastebin as suggested.

**Comment by BluSunrize** [comment]
Please spoiler your crashlogs using pastebin or something. But thanks for the heads up, will be fixed in future versions

**Comment by beepbeat** [comment]
Same happens if it is placed between ThermDyn Cryo-Ducts, so there is more than one Connection.

**Comment by BluSunrize** [comment]
fixed with latest commit
