### ISSUE TITLE
[0.10-40] Pipes don't render if connected to other pipes on all 6 sides.

### ISSUE THREAD

**Issue by 50m31-AW** [BluSunrize/ImmersiveEngineering#1400]
Like the title says, if a pipe is connected to other pipes on all 6 sides, it won't render. The hitbox is still there, but the pipe itself is completely invisible. 

https://imgur.com/T1OwQrd

IE: 0.10-40
Forge: 12.18.1.2076

**Comment by BluSunrize** [comment]
Fixed for future releases, see commit above
