### ISSUE TITLE
[1.10.2] [Bug] Diesel generator does not accept bio diesel 

### ISSUE THREAD

**Issue by Dijkstra1** [BluSunrize/ImmersiveEngineering#1401]
I would have reported this sooner but was pretty sure the mod pack I am using was not update IE, I know why know. Anyway got latest version of IE working after about half hour and check if it been fixed seemed not have I even broke the multi block (that reminds when every i break a multi block my client crashes) and reformed it and still it not take bio diesel in.
Attached below is a video, maybe that show it something as simple as me doing something wrong.
[IE DG.zip](https://github.com/BluSunrize/ImmersiveEngineering/files/458545/IE.DG.zip)

IE Version: ImmersiveEngineering-0.10-40
Forge Version: forge-1.10.2-12.18.1.2076

**Comment by BluSunrize** [comment]
Can't reproduce that one...
Is that a vanilla redstone block below the tank?
Also, if your client crashes when breaking multiblocks, I'd like that reported.

**Comment by Dijkstra1** [comment]
Yes vanilla redstone block, and will get a crash you can have 3 or 4 if like but there pretty much all the same

**Comment by BluSunrize** [comment]
Just one (in a new issue mind you) is fine.
And yeah, I cannot reproduce that fluid output bug...

**Comment by Dijkstra1** [comment]
Well I can still  reproduce it and got you fresh [crash report](https://github.com/BluSunrize/ImmersiveEngineering/issues/1403) not more than hour old

**Comment by RehabOholic** [comment]
I would like to add that I am having issue with this as well. For me it doesn't look like the pipes are not connecting to the generator. I have tried both inputs and it doesn't want to connect.

**Comment by BluSunrize** [comment]
@RehabOholic make sure you are on the latest build, number 40, the bug you are describing should have been fixed.

**Comment by grabvba** [comment]
Build 40, 1.10.2, 2076, same issue. We can pump bio diesel between tanks, from the refinery to tanks, from the refinery directly to the generator but not from a tank to the generator.

**Comment by Dijkstra1** [comment]
Can confirm what @grabvba is saying i can get bio diesel into my diesel generator if i pipe straight the refinery, but not from tanks be it the nice IE one, the enderio or even mekanism ones, and some where even set auto output, I have even tried auto output from a tank right next to the diesel generator fluid input, it seems the only way to but bio diesel into the diesel generator, is to pipe it from the refinery

**Comment by jrbeilke** [comment]
Having the same issue. Cannot get biodiesel out of an IE tank into the generator directly.

Had to put an EnderIO tank next to my IE tank set to pull from the IE tank. Then set the EnderIO tank to push into the IE pipes hooked up to my biodiesel gen to workaround this.

**Comment by LordBhael** [comment]
I would like to jump on this bandwagon.  I am having a similar problem.  When trying to experiment with the mod in creative mode, I made a diesel generator, put an IE tank next to it filled with biodiesel, and connected it with IE pipes.  Next I created an empty capacitor to collect RF.  I double-checked everything against YouTube videos to verify things were connected correctly, and things didn't work.  I tried adding an IE pump to the mix, verified all the inputs and outputs were correct, tried various combinations of redstone signals, tried reversing the connections, everything I could think of forwards and backwards.  It appears that I could get biodiesel to the pump, but not into the generator.  After reading jrbeilke's comment, I installed EnderIO and was able to get the thing running just by connecting the IE tank to the generator with EnderIO pressurized pipes.

**Comment by BluSunrize** [comment]
And I will ask you as well to /please/ provide some pictures!
It's barely possible to recreate any issues if noone provides some dang pictures.

**Comment by LordBhael** [comment]
Absolutely.  Give me a few minutes to recreate it for you.  Also, I assume it might be useful to give you a list of the mods I am using at the time?

I was just about to start experimenting a bit with it again, anyway.

**Comment by LordBhael** [comment]
![2016-11-21_14 39 17](https://cloud.githubusercontent.com/assets/16249912/20501769/7a554c30-aff8-11e6-9a9d-053251fc560b.png)

This is the minimalist setup I tried that, I believe, should work.  Both tanks are half full of biodiesel and being supplied with a redstone signal. The generator is not receiving a signal, and is connected to an empty HV capacitor. Removing one of the tank connections does not rectify the problem, nor does reducing the number of connections coming off the generator.  Inverting the generator does nothing (as it should) and neither does removing the redstone signal from the tanks (again, as it should be). Adding a pump (with power and redstone signal) to each tank setup will get biofuel to the pump, but not to the generator.  

![2016-11-21_14 48 24](https://cloud.githubusercontent.com/assets/16249912/20502039/9a397bba-aff9-11e6-97d1-bbf2234bcebb.png)

Replacing the pipes with EnderIO fluid pipes, set to extract from the tank without a redstone signal works just fine, though.

Again, I suspect it might be something with another mod I am using somewhere.  I am going to continue experimenting to test that hypothesis and hopefully identify the issue.

**Comment by mindforger** [comment]
the redstone signal has to be applied to the output block not anywhere

**Comment by LordBhael** [comment]
Brilliant!  That completely takes care of the issue.  Thank you!

I'm not sure why it worked the first time I tested it with only IE installed, but...meh. It works beautifully.  Thank you again for creating the mod I always though *censored* should have been!  I mean, really, a one cubic meter ore crusher?!?
