### ISSUE TITLE
[1.10.2] [Bug?]  [Question] Is this a bug

### ISSUE THREAD

**Issue by Dijkstra1** [BluSunrize/ImmersiveEngineering#1402]
This fells like a bug tell @BluSunrize is a bug or intended

[![](https://img.youtube.com/vi/y9P0_F7VdVM/0.jpg)](https://www.youtube.com/watch?v=y9P0_F7VdVM)

**Comment by BluSunrize** [comment]
Read the contribution guidelines? Mod versions, etc.
This looks like 1.7, in which case, I really don't care! :D

**Comment by Dijkstra1** [comment]
It is 1.10.2 like stated in the title

IE Version: ImmersiveEngineering-0.10-40
Forge Version: forge-1.10.2-12.18.1.2076

**Comment by BluSunrize** [comment]
In which case, yes that's a bug I will try to address.

**Comment by BluSunrize** [comment]
I've blacklisted drills for melting. Closed.
