### ISSUE TITLE
graphical glitch when you break 3 waterwheels at the same time

### ISSUE THREAD

**Issue by jamerthegamer** [BluSunrize/ImmersiveEngineering#1404]
i used a tinkers' lumber axe  at an angle which caused a graphical glitch and caused local lag and fps drop
![image](https://cloud.githubusercontent.com/assets/22061021/18326304/bcc6b60e-750a-11e6-89b6-4b4f1162842f.png)

![image](https://cloud.githubusercontent.com/assets/22061021/18326311/c56e4be6-750a-11e6-86a7-b2191cdb1fb8.png)

**Comment by kane-thornwyrd** [comment]
Beautiful !

**Comment by Hypsellis** [comment]
I love it too <3
