### ISSUE TITLE
[0.10-40] Wooden Barrels not placing

### ISSUE THREAD

**Issue by RicTakaden** [BluSunrize/ImmersiveEngineering#1405]
When attempting to place wooden barrels in the world, nothing is placed and the item doesn't leave my  inventory.  However attempting to walk into the space where the barrel was clicked causes my character to stop moving as if something was there.  Occasionally, after more attempts to place barrels, they will appear in every spot clicked previously, and can be broken to obtain another barrel, effectively duping them, but they can't be interfaced with at all even if they do show up.

Forge ver. is forge-1.10.2-12.18.1.2011

**Comment by BluSunrize** [comment]
I cannot reproduce this. This sounds like crossmod interaction. Could you please try to figure out which other mod causes this?

**Comment by RicTakaden** [comment]
No other mods are installed, just Forge and IE

**Comment by mindforger** [comment]
>No other mods are installed
does this include optifine?
did you play single player or multiplayer?
if multiplayer, did you use a plain forge server or some sort of cauldron/thermos ?

**Comment by RicTakaden** [comment]
Optifine is not installed, there is nothing except the version of forge I mentioned and IE 0.10-40. it was in a single player world.  
I'm beginning to think it is something with my hardware or drivers, similar problems occur with a variety of blocks added by the mod, including treated wood planks and sheet metal blocks.

**Comment by mindforger** [comment]
press F3 + C for minimum 6 seconds to force a crash and post it so we can have a look at your specs ... having blocks not beeing rendered can sometimes be an graphics card issue but it won't explain the issues with your inventory ... also double check your hard drive is not full

**Comment by RicTakaden** [comment]
[IE Crash Report.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/464639/IE.Crash.Report.txt)

Here is the crash report.  The drive minecraft runs from has about 85 GB of free space so it shouldn't be that.
