### ISSUE TITLE
Incompatible with Optifine/Enchiridon combination

### ISSUE THREAD

**Issue by mrtomwolf** [BluSunrize/ImmersiveEngineering#1407]
Crashing on start up:
http://pastebin.com/2U2nmpiE

Also have to say that this is one of the, if not the best tech mods ever.

**Comment by VT-14** [comment]
Looks like a rendering crash.  Try removing Optifine.

**Comment by mrtomwolf** [comment]
Indeed it was a conflict with Optifine, unfortunately playing without it in a modpack is out of the question so I'll have to make do without IE =( I'll try again in future updates of both optifine and IE and report back if the issue gets solved.

**Comment by mrtomwolf** [comment]
Installing only IE and Optifine worked fine, so it seems to be a three way conflict or a particular setting I use in Optifine that causes the crash.

**Comment by mrtomwolf** [comment]
After a lot of trial and error I've found that it's a sexy threeway that causes the problem.

IE
Of
Enchiridion
https://mods.curse.com/mc-mods/minecraft/enchiridion

http://pastebin.com/RU1R8Kv1

The error occurs at the very end at the last loading process before the menu shows up.
