### ISSUE TITLE
Placing Treated wood planks

### ISSUE THREAD

**Issue by It-IS-Lupus** [BluSunrize/ImmersiveEngineering#141]
Hello, I've noticed that when placing treated wood planks you are able to place them within the same block space as your player model. This doesn't treat the blocks as solid(you can walk out of them) nor do you recieve "suffocation" damage when inside said blocks. I know that the open blocks team had this issue with the dev null.

**Comment by Pihrra** [comment]
A similar issue was already posted and closed : https://github.com/BluSunrize/ImmersiveEngineering/issues/81
tl;dr it's normal
