### ISSUE TITLE
Assembler wont craft cakes with the latest IE 1.10.2[Forge .2075 and .2076]

### ISSUE THREAD

**Issue by KillerRamer** [BluSunrize/ImmersiveEngineering#1410]
So I'm trying to make a little cake assembly line, got a source of milk pumping through, However no matter what I try, either through bucket or the internal tank the assembler isn't allowing me to craft cake.  Tried updating forge but that didn't help either. I've only tested this in singleplayer however. 

![2016-09-08_12 49 00](https://cloud.githubusercontent.com/assets/2716673/18359390/bacfa06e-75c7-11e6-9a56-f86151b1bcce.png)
![2016-09-08_12 49 10](https://cloud.githubusercontent.com/assets/2716673/18359391/bad79cc4-75c7-11e6-8de4-8f724884f5b6.png)

Mod list:
http://pastebin.com/kaWF7xff

**Comment by kane-thornwyrd** [comment]
You failed the link XD, here for the lazy like me: [http://pastebin.com/kaWF7xff](http://pastebin.com/kaWF7xff)

**Comment by BluSunrize** [comment]
Can't reproduce that, so, fixed for future releases =P
