### ISSUE TITLE
[0.10-40] Floodlight "flickers" and kills framerate.

### ISSUE THREAD

**Issue by 50m31-AW** [BluSunrize/ImmersiveEngineering#1411]
When the floodlight is turned on it emits a light level of 15 perfectly fine like a normal light source would, however the 32 block long cone of light that it produces will cyclically "flicker" between being on and off. The cone will stay on for 11 seconds, but then turn off and stay off for 14 seconds, before turning back on for 11 seconds to turn off for another 14 seconds after that, repeating ad infinitum; absolutely killing framerate with all the lighting updates. Additionally, turning turning the Floodlight off by removing the redstone signal will not stop it from emiting a normal light level of 15 until it is broken, simply forcing a block update won't cut it.

http://imgur.com/a/0TCac

IE: 0.10-40
Forge: 12.18.1.2076

**Comment by BluSunrize** [comment]
Fixed for future releases, see commit above
