### ISSUE TITLE
Conveyor belt invisible in this setup

### ISSUE THREAD

**Issue by laserlemons** [BluSunrize/ImmersiveEngineering#1412]
It works fine, though visually it's missing.

![2016-09-08_14 16 08](https://cloud.githubusercontent.com/assets/6501298/18367339/8675ef00-75cf-11e6-9ccc-b839cad948b2.png)

**Comment by BluSunrize** [comment]
http://puu.sh/r9DHE/7bd9467713.jpg

I think I fixed it. Commit incoming!

**Comment by BluSunrize** [comment]
Fixed for future releases, see commit above!
