### ISSUE TITLE
Into the machine after the crash, the destruction of the machine game

### ISSUE THREAD

**Issue by PeakXing** [BluSunrize/ImmersiveEngineering#1413]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IC2core (industrialcraft-2-2.6.55-ex110.jar)
  TANLoadingPlugin (ToughAsNails-1.9.4-1.0.11.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.54-beta.jar)
Contact their authors BEFORE contacting forge

// Ooh. Shiny.

Time: 9/9/16 8:01 AM
Description: Rendering Block Entity

java.lang.IllegalArgumentException: Cannot set property PropertyBoolInverted{name=_1dynamicrender, clazz=class java.lang.Boolean, values=[false, true]} as it does not exist in BlockStateContainer{block=minecraft:piston, properties=[extended, facing]}
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:210)
    at blusunrize.immersiveengineering.client.render.TileRenderMetalPress.renderTileEntityAt(TileRenderMetalPress.java:32)
    at blusunrize.immersiveengineering.client.render.TileRenderMetalPress.func_180535_a(TileRenderMetalPress.java:20)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:147)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:125)
    at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:989)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1727)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1556)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1335)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:114)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:210)
    at blusunrize.immersiveengineering.client.render.TileRenderMetalPress.renderTileEntityAt(TileRenderMetalPress.java:32)
    at blusunrize.immersiveengineering.client.render.TileRenderMetalPress.func_180535_a(TileRenderMetalPress.java:20)

-- Block Entity Details --
Details:
    Name: immersiveengineering:MetalPress // blusunrize.immersiveengineering.common.blocks.metal.TileEntityMetalPress
    Block type: ID #486 (tile.immersiveengineering.metalMultiblock // blusunrize.immersiveengineering.common.blocks.metal.BlockMetalMultiblocks)
    Block data value: 0 / 0x0 / 0b0000
    Block location: World: (-395,5,-682), Chunk: (at 5,0,6 in -25,-43; contains blocks -400,0,-688 to -385,255,-673), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
    Actual block type: ID #33 (tile.pistonBase // net.minecraft.block.BlockPistonBase)
    Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(TileEntityRendererDispatcher.java:147)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:125)
    at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:989)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1727)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1556)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['PeakXing'/217, l='MpServer', x=-392.01, y=4.00, z=-681.02]]
    Chunk stats: MultiplayerChunkCache: 289, 289
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-385,4,-673), Chunk: (at 15,0,15 in -25,-43; contains blocks -400,0,-688 to -385,255,-673), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
    Level time: 7155 game time, 7155 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 82 total; [EntityPig['猪'/128, l='MpServer', x=-353.32, y=4.00, z=-723.09], EntitySlime['史莱姆'/129, l='MpServer', x=-386.43, y=4.75, z=-735.53], EntitySheep['羊'/130, l='MpServer', x=-354.40, y=4.00, z=-712.50], EntityChicken['鸡'/131, l='MpServer', x=-363.16, y=4.00, z=-713.87], EntityHorse['马'/132, l='MpServer', x=-362.47, y=4.00, z=-625.24], EntityPig['猪'/133, l='MpServer', x=-366.74, y=4.00, z=-627.55], EntitySheep['羊'/134, l='MpServer', x=-358.76, y=4.00, z=-612.82], EntityPig['猪'/136, l='MpServer', x=-356.36, y=4.00, z=-603.45], EntityPig['猪'/137, l='MpServer', x=-355.24, y=4.00, z=-604.83], EntitySlime['史莱姆'/310669, l='MpServer', x=-427.19, y=5.25, z=-749.64], EntityChicken['鸡'/138, l='MpServer', x=-353.50, y=4.00, z=-603.50], EntityItemFrame['Item Frame'/13, l='MpServer', x=-503.03, y=7.50, z=-746.50], EntitySlime['史莱姆'/296201, l='MpServer', x=-353.17, y=4.00, z=-608.81], EntityItem['item.tile.immersiveengineering.metalDecoration0.rs_engineering'/312329, l='MpServer', x=-394.50, y=4.50, z=-681.50], EntitySheep['羊'/142, l='MpServer', x=-342.44, y=4.00, z=-757.41], EntitySheep['羊'/143, l='MpServer', x=-345.78, y=4.00, z=-752.99], EntityChicken['鸡'/145, l='MpServer', x=-341.78, y=4.00, z=-757.12], EntityItemFrame['Item Frame'/18, l='MpServer', x=-503.03, y=7.50, z=-706.50], EntityCow['牛'/146, l='MpServer', x=-344.37, y=4.00, z=-752.30], EntityPig['猪'/148, l='MpServer', x=-348.77, y=4.00, z=-722.60], EntityPig['猪'/150, l='MpServer', x=-350.54, y=4.00, z=-713.73], EntitySheep['羊'/157, l='MpServer', x=-351.50, y=4.00, z=-602.50], EntityChicken['鸡'/158, l='MpServer', x=-348.88, y=4.00, z=-602.32], EntitySlime['史莱姆'/203175, l='MpServer', x=-407.38, y=4.76, z=-696.23], EntityChicken['鸡'/166, l='MpServer', x=-327.50, y=4.00, z=-626.50], EntityChicken['鸡'/167, l='MpServer', x=-325.50, y=4.00, z=-626.50], EntityChicken['鸡'/168, l='MpServer', x=-321.75, y=4.00, z=-624.55], EntityChicken['鸡'/169, l='MpServer', x=-328.50, y=4.00, z=-632.50], EntitySheep['羊'/170, l='MpServer', x=-325.12, y=4.00, z=-643.13], EntitySlime['史莱姆'/171567, l='MpServer', x=-451.40, y=4.92, z=-674.36], EntityPlayerSP['PeakXing'/217, l='MpServer', x=-392.01, y=4.00, z=-681.02], EntitySlime['史莱姆'/115380, l='MpServer', x=-410.92, y=5.25, z=-731.42], EntityVillager['村民'/61, l='MpServer', x=-455.50, y=5.00, z=-757.50], EntityVillager['村民'/62, l='MpServer', x=-455.50, y=5.00, z=-756.50], EntityVillager['村民'/65, l='MpServer', x=-449.87, y=5.00, z=-751.47], EntityVillager['村民'/67, l='MpServer', x=-447.50, y=5.00, z=-760.50], EntitySlime['史莱姆'/289607, l='MpServer', x=-350.30, y=4.00, z=-608.03], EntityVillager['村民'/68, l='MpServer', x=-439.97, y=4.00, z=-724.43], EntityVillager['村民'/69, l='MpServer', x=-438.83, y=3.94, z=-711.28], EntitySlime['史莱姆'/288833, l='MpServer', x=-330.26, y=4.55, z=-690.21], EntityVillager['村民'/70, l='MpServer', x=-432.54, y=4.94, z=-707.49], EntityVillager['村民'/71, l='MpServer', x=-444.31, y=3.94, z=-710.50], EntitySheep['羊'/72, l='MpServer', x=-433.85, y=4.00, z=-666.57], EntitySheep['羊'/73, l='MpServer', x=-438.06, y=4.00, z=-658.97], EntitySheep['羊'/74, l='MpServer', x=-440.28, y=4.00, z=-660.45], EntityVillager['村民'/77, l='MpServer', x=-429.52, y=4.00, z=-724.65], EntitySlime['史莱姆'/104268, l='MpServer', x=-345.85, y=5.17, z=-733.47], EntitySlime['史莱姆'/78, l='MpServer', x=-405.80, y=4.00, z=-646.60], EntitySheep['羊'/79, l='MpServer', x=-424.85, y=4.00, z=-672.31], EntitySheep['羊'/80, l='MpServer', x=-419.54, y=4.00, z=-659.97], EntitySheep['羊'/81, l='MpServer', x=-425.52, y=4.00, z=-666.27], EntityPig['猪'/82, l='MpServer', x=-426.69, y=4.00, z=-671.17], EntitySheep['羊'/83, l='MpServer', x=-426.81, y=4.00, z=-657.83], EntitySlime['史莱姆'/240080, l='MpServer', x=-453.20, y=4.00, z=-672.75], EntitySheep['羊'/84, l='MpServer', x=-431.02, y=4.00, z=-669.78], EntitySlime['史莱姆'/91, l='MpServer', x=-421.38, y=4.00, z=-669.04], EntitySlime['史莱姆'/285656, l='MpServer', x=-348.13, y=4.13, z=-601.34], EntityCow['牛'/93, l='MpServer', x=-413.14, y=4.00, z=-628.66], EntityCow['牛'/94, l='MpServer', x=-404.29, y=4.00, z=-618.80], EntitySlime['史莱姆'/117471, l='MpServer', x=-382.74, y=4.00, z=-645.89], EntitySlime['史莱姆'/95973, l='MpServer', x=-363.38, y=4.00, z=-602.40], EntitySlime['史莱姆'/193892, l='MpServer', x=-338.37, y=4.00, z=-688.62], EntitySlime['史莱姆'/260458, l='MpServer', x=-342.66, y=5.00, z=-700.10], EntityItem['item.tile.immersiveengineering.conveyor.immersiveengineering:conveyor'/106, l='MpServer', x=-395.86, y=4.00, z=-680.72], EntitySlime['史莱姆'/244329, l='MpServer', x=-408.62, y=4.00, z=-740.36], EntitySlime['史莱姆'/216174, l='MpServer', x=-448.18, y=4.00, z=-686.75], EntityPig['猪'/110, l='MpServer', x=-385.50, y=4.00, z=-633.90], EntityPig['猪'/111, l='MpServer', x=-399.45, y=4.00, z=-624.93], EntityPig['猪'/112, l='MpServer', x=-395.65, y=4.00, z=-627.82], EntityPig['猪'/113, l='MpServer', x=-399.28, y=4.00, z=-636.25], EntitySheep['羊'/114, l='MpServer', x=-389.12, y=4.00, z=-624.37], EntitySheep['羊'/115, l='MpServer', x=-394.17, y=4.00, z=-622.21], EntityPig['猪'/120, l='MpServer', x=-375.41, y=4.00, z=-635.27], EntityChicken['鸡'/121, l='MpServer', x=-372.29, y=4.00, z=-630.02], EntityChicken['鸡'/122, l='MpServer', x=-373.50, y=4.00, z=-625.50], EntitySlime['史莱姆'/183672, l='MpServer', x=-374.00, y=5.10, z=-620.13], EntityCow['牛'/123, l='MpServer', x=-378.80, y=4.00, z=-615.70], EntityCow['牛'/124, l='MpServer', x=-354.17, y=4.00, z=-756.40], EntityCow['牛'/125, l='MpServer', x=-357.35, y=4.00, z=-758.20], EntitySheep['羊'/126, l='MpServer', x=-360.41, y=4.00, z=-729.55], EntityPig['猪'/127, l='MpServer', x=-352.74, y=4.00, z=-725.52], EntitySlime['史莱姆'/197244, l='MpServer', x=-415.83, y=4.08, z=-679.14]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:496)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.jackhuang.hellominecraft.launcher.Launcher.main(Launcher.java:114)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_91, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1393122824 bytes (1328 MB) / 2479800320 bytes (2364 MB) up to 3207856128 bytes (3059 MB)
    JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx3072m
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.32 Powered by Forge 12.18.1.2076 Optifine OptiFine_1.10.2_HD_U_C2 26 mods loaded, 26 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.1.2076.jar) 
    UCHIJAAAA   Forge{12.18.1.2076} [Minecraft Forge](forge-1.10.2-12.18.1.2076.jar) 
    UCHIJAAAA   BiomesOPlenty{5.0.0.2082} [Biomes O' Plenty](BiomesOPlenty-1.10.2-5.0.0.2082-universal.jar) 
    UCHIJAAAA   Chameleon{1.10-2.1.7} [Chameleon](Chameleon-1.10-2.1.7.jar) 
    UCHIJAAAA   ChestTransporter{2.5.1} [Chest Transporter](ChestTransporter-1.10.2-2.5.1.jar) 
    UCHIJAAAA   chiselsandbits{12.1} [Chisels & Bits](chiselsandbits-12.1.jar) 
    UCHIJAAAA   dailies{1.10.2-2} [DailiesMod](dailies-1.10.2-2.jar) 
    UCHIJAAAA   endercore{1.10.2-0.4.1.54-beta} [EnderCore](EnderCore-1.10.2-0.4.1.54-beta.jar) 
    UCHIJAAAA   mantle{1.10.2-0.10.4.jenkins163} [Mantle](Mantle-1.10.2-0.10.4.jar) 
    UCHIJAAAA   tconstruct{1.10.2-2.4.0.jenkins325} [Tinkers' Construct](TConstruct-1.10.2-2.4.0.jar) 
    UCHIJAAAA   immersiveengineering{${version}} [Immersive Engineering](ImmersiveEngineering-0.10-40.jar) 
    UCHIJAAAA   JEI{3.9.0.247} [Just Enough Items](jei_1.10.2-3.9.0.247.jar) 
    UCHIJAAAA   EnderIO{1.10.2-3.0.1.104_beta} [Ender IO](EnderIO-1.10.2-3.0.1.104_beta.jar) 
    UCHIJAAAA   extraalchemy{0.2.8.1-beta} [Extra Alchemy](extraalchemy-0.2.8.1-beta.jar) 
    UCHIJAAAA   golems{6.02} [Extra Golems](ExtraGolems[1.10.2]-6.02.jar) 
    UCHIJAAAA   flatcoloredblocks{mc1.10-v4.1} [Flat Colored Blocks](flatcoloredblocks-mc1.10-v4.1.jar) 
    UCHIJAAAA   IC2{2.6.55-ex110} [IndustrialCraft 2](industrialcraft-2-2.6.55-ex110.jar) 
    UCHIJAAAA   inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks](InventoryTweaks-1.61-58.jar) 
    UCHIJAAAA   mycommands{1.9.4-1.10.2-02} [MY Commands](MyCommands-1.9.4-1.10.2-02.jar) 
    UCHIJAAAA   SaltMod{1.8.c} [Salty Mod](SaltyMod-1.10-1.8.c_beta-1_.jar) 
    UCHIJAAAA   StorageDrawers{1.10.2-3.2.7} [Storage Drawers](StorageDrawers-1.10.2-3.2.7.jar) 
    UCHIJAAAA   ToughAsNails{1.0.11} [Tough As Nails](ToughAsNails-1.9.4-1.0.11.jar) 
    UCHIJAAAA   icse{1.1.0.0} [I Can See Everything](Wawla-1.10.2-2.3.0.201.jar) 
    UCHIJAAAA   wawla{2.3.0.201} [What Are We Looking At](Wawla-1.10.2-2.3.0.201.jar) 
    UCHIJAAAA   yannmod{0.1} [Yann's Mod](yann's mod.jar) 
    Loaded coremods (and transformers): 
IC2core (industrialcraft-2-2.6.55-ex110.jar)

TANLoadingPlugin (ToughAsNails-1.9.4-1.0.11.jar)
  toughasnails.asm.transformer.BlockCropsTransformer
  toughasnails.asm.transformer.EntityRendererTransformer
  toughasnails.asm.transformer.WorldTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.54-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 355.82' Renderer: 'GeForce GT 650M/PCIe/SSE2'
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - chiselsandbitsIntegration (Enabled/Not Forced)

```
EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker.):
              * Optifine is installed. This is NOT supported.
             This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
Detailed RF API diagnostics:
              * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/PeakXing/Desktop/喂妖妖灵么/.minecraft/mods/ImmersiveEngineering-0.10-40.jar!/cofh/api/energy/EnergyStorage.class
              * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/PeakXing/Desktop/喂妖妖灵么/.minecraft/mods/ImmersiveEngineering-0.10-40.jar!/cofh/api/energy/IEnergyConnection.class
              * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/PeakXing/Desktop/喂妖妖灵么/.minecraft/mods/ImmersiveEngineering-0.10-40.jar!/cofh/api/energy/IEnergyContainerItem.class
              * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/PeakXing/Desktop/喂妖妖灵么/.minecraft/mods/ImmersiveEngineering-0.10-40.jar!/cofh/api/energy/IEnergyHandler.class
              * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/PeakXing/Desktop/喂妖妖灵么/.minecraft/mods/ImmersiveEngineering-0.10-40.jar!/cofh/api/energy/IEnergyProvider.class
              * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/PeakXing/Desktop/喂妖妖灵么/.minecraft/mods/ImmersiveEngineering-0.10-40.jar!/cofh/api/energy/IEnergyReceiver.class
              * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/PeakXing/Desktop/喂妖妖灵么/.minecraft/mods/ImmersiveEngineering-0.10-40.jar!/cofh/api/energy/IEnergyStorage.class
              * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/PeakXing/Desktop/喂妖妖灵么/.minecraft/mods/ImmersiveEngineering-0.10-40.jar!/cofh/api/energy/ItemEnergyContainer.class
              * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/PeakXing/Desktop/喂妖妖灵么/.minecraft/mods/ImmersiveEngineering-0.10-40.jar!/cofh/api/energy/TileEnergyHandler.class
              * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/PeakXing/Desktop/喂妖妖灵么/.minecraft/mods/ImmersiveEngineering-0.10-40.jar!/cofh/api/energy/TileEnergyHandler.class

Launched Version: 1.10.2-forge1.10.2-12.18.1.2076
LWJGL: 2.9.4
OpenGL: GeForce GT 650M/PCIe/SSE2 GL version 4.5.0 NVIDIA 355.82, NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: No
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: 简体中文 (中国)
Profiler Position: N/A (disabled)
CPU: 8x Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
OptiFine Version: OptiFine_1.10.2_HD_U_C2
Render Distance Chunks: 8
Mipmaps: 4
Anisotropic Filtering: 1
Antialiasing: 0
Multitexture: false
Shaders: null
OpenGlVersion: 4.5.0 NVIDIA 355.82
OpenGlRenderer: GeForce GT 650M/PCIe/SSE2
OpenGlVendor: NVIDIA Corporation
CpuCount: 8
```

**Comment by 3TUSK** [comment]
...

The title should be "After breaking any of IE machine, game will crash immediately"

**Comment by mindforger** [comment]
and the crashlog should be spoilered like the [guidelines for contributing](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/CONTRIBUTING.md) to this repository tell you

**Comment by theunkn0wn1** [comment]
Please try removing Optifine as it is not supported and is known to cause trouble
