### ISSUE TITLE
[0.10-40] Refinery won't accept items.

### ISSUE THREAD

**Issue by 50m31-AW** [BluSunrize/ImmersiveEngineering#1414]
The refinery won't accept any items in any slot with the exception of empty buckets in the biodeisel output slot. This means that the ethanol and plant oil can't be supplied manually via buckets, and mining drills/chem throwers can't be filled directly in it.

IE: 0.10-40
Forge: 12.18.1.2076

**Comment by BluSunrize** [comment]
Fixed for future releases, see commit above
