### ISSUE TITLE
[0.10-40] Arc Furnace output issues.

### ISSUE THREAD

**Issue by 50m31-AW** [BluSunrize/ImmersiveEngineering#1415]
While fooling around with the Arc Furnace, I noticed a couple issues.

The first is that it won't auto-output anything if all of the primary input slots have items in them, this results in the machine getting gummed up rather quickly if you're trying to smelt items in bulk.

The second issue is that it outputs an extra item per stack in the output slots. It outputs an item and decrements the number of items in the stack normally until it gets to the last item, at which point it outputs but decrements the item count to a stack with 0 items in it (like this https://imgur.com/a/bu8tu) and then outputs that before being done with the stack. This wouldn't be so much of an issue if it weren't for the fact that one could triple the amount of resources per ore if they used only one input slot at a time, and then crushed the ingots back into grit to triple and smelt again in a loop for infinite resources. 

IE: 0.10-40
Forge: 12.18.1.2076

**Comment by BluSunrize** [comment]
Fixed for future releases, see commit above!
