### ISSUE TITLE
Metal Barrel/Pipe Game Crash & Invisible Connectors/Relays

### ISSUE THREAD

**Issue by dshatnerIII** [BluSunrize/ImmersiveEngineering#1417]
Good afternoon,
I have been using the mod or about a month now (very great by the way) for MC version 1.10.2 and have run into 2 issues recently.
1) Any connectors or relays placed down in the world are invisible.  Only when placed/set. If broken appear/visible as an item on the ground, also visible when held and in the inventory.
2) GAME CRASH: I placed a metal barrel on top of a single pipe segment and the game crashed and needed to be restored from backup.  I have attached the Crash Report.

[MC Crash Report_09092016_Metal Barrel Placed on Top of Pipe Segment.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/464513/MC.Crash.Report_09092016_Metal.Barrel.Placed.on.Top.of.Pipe.Segment.txt)

**Comment by malte0811** [comment]
Regarding 1) Please read the contributing guidelines, Optifine is not supported and the invisible connectors sound like something Optifine would cause.
Regarding 2) Again, please read the contributing guidelines! This was fixed in later versions of IE (6b11c8c30e72b8e84427f75aabe1534084be31ee).

**Comment by dshatnerIII** [comment]
Thank you for your response. Optifine was the issue.
