### ISSUE TITLE
suggestion for sound

### ISSUE THREAD

**Issue by Chinthor** [BluSunrize/ImmersiveEngineering#1418]
This is possibly beyond the scope of the mod. It is also silly and unnecessary. But it might be awesome if it could be pulled off, perhaps for April 1.

I'm looking for a sound effect that is like having many speakers or other sound sources that play the same sound at the same time. It would not just be the standard sound effect that can have multiple copies playing over each other. There would be one master sound or audio track playing. The volume of it would depend on how close you are to any of the sources. And if a source is broken, destroyed, or stops being a source, the sound from that point is faded out.

Now, this would help a lot of mods that add noisy machines. Unless a person likes the audio chaos. A small thing for IE would be a sound effect applied to the conveyor belts. Any piece of belt is only considered to be a sound source if it has an item in it. When the item passes and the belt is empty, it is no longer a sound source and the sound from that point fades. This way the sound would have no overlap and yet be able to follow a cluster of items down the belt.

Here's the silly part. Seeing the way this mod looks and works, I want the conveyor belt sound effect to be "Powerhouse." https://youtu.be/kQ6XY0nLZBI?t=92
I want that soundtrack to follow any moving items around my factory. If I have everything working at full capacity, it will never end.

**Comment by dshatnerIII** [comment]
Insanely impractical, but pretty funny specifically that song effect on the belts.

**Comment by Chinthor** [comment]
I know, right? Oh, well. Tell you what. If it is insanely impractical and involves system-breaking tweaks to various rendering engines, just give it to Soryn. Seems to be a good fit. Either he'll come up with something utterly ridiculous but workable, or we'll see it sometime after we see a finished Xycraft.

**Comment by BluSunrize** [comment]
How do I phrase my reply best apart from "Wat?"
IE has sound effects. Conveyors will not get one. I like my users not being pissed at me.
