### ISSUE TITLE
problem of compatibility between Cupronickel and Constantan

### ISSUE THREAD

**Issue by Hypsellis** [BluSunrize/ImmersiveEngineering#1419]
I link this issue here too https://github.com/EXTER7/Substratum/issues/21

**Comment by kane-thornwyrd** [comment]
Can you explain what happen ?

**Comment by BluSunrize** [comment]
I used to oredict to Cupronickel as well, when I still has gregtech compat. I did not realize that another Mod added it as well. Will look into it.

**Comment by BluSunrize** [comment]
Are you sure you are on the latest version of Substratum? Because the one I am testing with, 1.8.1.0, just allows the use of Constantan in recipes.

**Comment by Hypsellis** [comment]
Yeah that I know it works, I thought more to use it in Tinkers Construct, Foundry or IE machines.

**Comment by BluSunrize** [comment]
You can. That is what I'm saying. Substratum Oredicts their Cupronickel to both "Cupronickel" and "Constantan". Their metal can be used for TinkersConstruct, because the Constantan metal for TCon was written by me, and is oredict based.
And it also works for anything in Foundry as well.
I would like you to present a definite example of what you *cannot* craft with either metal. And using the latest versions of Foundry and Substratum.

**Comment by Hypsellis** [comment]
Ok so let do a little list for what I saw (it could have more):
- Curponickel rods, gears and plates can't be crafted with Constantan ingots
- Constantan dust can't be crafted with one Copper and Nickel dusts, 4 Cupronickel tiny dusts, or 2  Copper and Nickel tiny dusts.
- Mortar can't be used on Constantan ingots for crafting constantan/cupronickel dust.
- Constantan dusts can't turned into 4 tiney Cupronickel dusts
- Cupronichel heating coil from TechReborn can't be crafted with Constantan ingots
- surely a lot more I forget

**Comment by Hypsellis** [comment]
If you really want to see the difference, here is a pictures of all the recipes possible with Cupronickel ingots:
![2016-09-14_11 54 45](https://cloud.githubusercontent.com/assets/17103411/18507894/7e62e294-7a72-11e6-8937-a13faa2056be.png)
![2016-09-14_11 54 46](https://cloud.githubusercontent.com/assets/17103411/18507896/7e6325ba-7a72-11e6-822c-54e2eeca7b39.png)
![2016-09-14_11 54 49](https://cloud.githubusercontent.com/assets/17103411/18507898/7e648b4e-7a72-11e6-8016-a780408ca711.png)
![2016-09-14_11 54 50](https://cloud.githubusercontent.com/assets/17103411/18507895/7e6300d0-7a72-11e6-80d0-6e775faa1c6c.png)
![2016-09-14_11 54 52](https://cloud.githubusercontent.com/assets/17103411/18507899/7e68a030-7a72-11e6-81f1-80d3d5adbecc.png)
![2016-09-14_11 54 55](https://cloud.githubusercontent.com/assets/17103411/18507897/7e645e58-7a72-11e6-94ee-117d8d711df1.png)
![2016-09-14_11 54 56](https://cloud.githubusercontent.com/assets/17103411/18507900/7f4b1154-7a72-11e6-8426-fb08a14eaca4.png)
![2016-09-14_11 54 58](https://cloud.githubusercontent.com/assets/17103411/18507905/7f5e9c2e-7a72-11e6-9b02-ab5b1c1824e6.png)
![2016-09-14_11 55 00](https://cloud.githubusercontent.com/assets/17103411/18507901/7f4d379a-7a72-11e6-9876-b4dba1e27254.png)
![2016-09-14_11 55 03](https://cloud.githubusercontent.com/assets/17103411/18507904/7f536674-7a72-11e6-8b00-2c74a07f79d7.png)
![2016-09-14_11 55 06](https://cloud.githubusercontent.com/assets/17103411/18507903/7f518566-7a72-11e6-87bf-2c83798e3297.png)
![2016-09-14_11 53 04](https://cloud.githubusercontent.com/assets/17103411/18507902/7f4ec34e-7a72-11e6-8821-2d83133b700e.png)
![2016-09-14_11 53 10](https://cloud.githubusercontent.com/assets/17103411/18507906/7f5ee5b2-7a72-11e6-934f-669be9d7f65f.png)
![2016-09-14_11 53 13](https://cloud.githubusercontent.com/assets/17103411/18507907/7f615e64-7a72-11e6-9eda-4d89591fd735.png)
![2016-09-14_11 53 14](https://cloud.githubusercontent.com/assets/17103411/18507909/7f656f86-7a72-11e6-91aa-817faa90292a.png)
![2016-09-14_11 53 16](https://cloud.githubusercontent.com/assets/17103411/18507908/7f640ea2-7a72-11e6-8b66-320a8e9364ef.png)
![2016-09-14_11 53 17](https://cloud.githubusercontent.com/assets/17103411/18507910/7f733c4c-7a72-11e6-8405-4e5451bf5e71.png)
![2016-09-14_11 53 18](https://cloud.githubusercontent.com/assets/17103411/18507912/7f7393ea-7a72-11e6-83a8-8f36b3a4d7ce.png)
![2016-09-14_11 53 20](https://cloud.githubusercontent.com/assets/17103411/18507911/7f7384f4-7a72-11e6-8e31-949d39e24312.png)
![2016-09-14_11 53 22](https://cloud.githubusercontent.com/assets/17103411/18507915/7f8599c8-7a72-11e6-9f12-9a0bb732c35a.png)
![2016-09-14_11 53 23](https://cloud.githubusercontent.com/assets/17103411/18507913/7f774f12-7a72-11e6-896d-03f2c2439885.png)
![2016-09-14_11 53 24](https://cloud.githubusercontent.com/assets/17103411/18507914/7f7a1940-7a72-11e6-9e92-63c1d549c55d.png)
![2016-09-14_11 53 26](https://cloud.githubusercontent.com/assets/17103411/18507916/7f89bfee-7a72-11e6-95dc-f8c7f1b79846.png)
![2016-09-14_11 53 28](https://cloud.githubusercontent.com/assets/17103411/18507919/7f8d0a14-7a72-11e6-9e7e-f9891cfe3663.png)
![2016-09-14_11 53 30](https://cloud.githubusercontent.com/assets/17103411/18507918/7f8ceb10-7a72-11e6-845a-71ef1551161d.png)
![2016-09-14_11 53 31](https://cloud.githubusercontent.com/assets/17103411/18507917/7f8c6370-7a72-11e6-8ac4-3445181debd8.png)
![2016-09-14_11 53 32](https://cloud.githubusercontent.com/assets/17103411/18507920/7f94738a-7a72-11e6-8628-2a2f57528beb.png)
![2016-09-14_11 53 34](https://cloud.githubusercontent.com/assets/17103411/18507921/7f9b2d10-7a72-11e6-9892-c002bf86a0b2.png)
![2016-09-14_11 53 37](https://cloud.githubusercontent.com/assets/17103411/18507922/7fa06b9a-7a72-11e6-9f5d-2db3032a1ec5.png)
![2016-09-14_11 53 39](https://cloud.githubusercontent.com/assets/17103411/18507923/7fa97ba4-7a72-11e6-815f-ebae38ac1ede.png)
![2016-09-14_11 54 29](https://cloud.githubusercontent.com/assets/17103411/18507924/7fac3164-7a72-11e6-863a-9c6c8c6c9fa1.png)
![2016-09-14_11 54 30](https://cloud.githubusercontent.com/assets/17103411/18507926/7fb21250-7a72-11e6-8c50-967e89dbdd31.png)
![2016-09-14_11 54 32](https://cloud.githubusercontent.com/assets/17103411/18507927/7fb235dc-7a72-11e6-9c36-8adc07191e05.png)
![2016-09-14_11 54 34](https://cloud.githubusercontent.com/assets/17103411/18507925/7faec046-7a72-11e6-84d0-3590ba69d329.png)
![2016-09-14_11 54 36](https://cloud.githubusercontent.com/assets/17103411/18507928/7fb305ac-7a72-11e6-8783-78d53876f369.png)
![2016-09-14_11 54 38](https://cloud.githubusercontent.com/assets/17103411/18507930/7fc4e6dc-7a72-11e6-955f-8d8b6655154d.png)
![2016-09-14_11 54 39](https://cloud.githubusercontent.com/assets/17103411/18507929/7fbf636a-7a72-11e6-849c-6615f093be97.png)
![2016-09-14_11 54 41](https://cloud.githubusercontent.com/assets/17103411/18507932/7fcacebc-7a72-11e6-882b-250773972d80.png)
![2016-09-14_11 54 43](https://cloud.githubusercontent.com/assets/17103411/18507931/7fc6f63e-7a72-11e6-9737-6b192679666f.png)

**Comment by Hypsellis** [comment]
And now all the recipes with Constantan ingots:
![2016-09-14_11 55 43](https://cloud.githubusercontent.com/assets/17103411/18508019/d7a7dd82-7a72-11e6-9494-063c21cc6838.png)
![2016-09-14_11 55 45](https://cloud.githubusercontent.com/assets/17103411/18508021/d7ad88f4-7a72-11e6-8621-b100fbaf879f.png)
![2016-09-14_11 55 47](https://cloud.githubusercontent.com/assets/17103411/18508018/d7a7bab4-7a72-11e6-9a18-8ab199942bb1.png)
![2016-09-14_11 55 49](https://cloud.githubusercontent.com/assets/17103411/18508017/d7a7b320-7a72-11e6-92a9-64f803c40e23.png)
![2016-09-14_11 55 51](https://cloud.githubusercontent.com/assets/17103411/18508020/d7ac77f2-7a72-11e6-864a-f782b3b94e6d.png)
![2016-09-14_11 55 52](https://cloud.githubusercontent.com/assets/17103411/18508016/d7a71c30-7a72-11e6-9e1a-43ec4ba1bd98.png)
![2016-09-14_11 55 54](https://cloud.githubusercontent.com/assets/17103411/18508024/d7bf7b5e-7a72-11e6-9bd4-ed85f2225ff9.png)
![2016-09-14_11 55 55](https://cloud.githubusercontent.com/assets/17103411/18508022/d7baf99e-7a72-11e6-93bb-2f4bbcedd47d.png)
![2016-09-14_11 55 57](https://cloud.githubusercontent.com/assets/17103411/18508023/d7bc51ae-7a72-11e6-9d7a-6aa11df4b919.png)
![2016-09-14_11 55 59](https://cloud.githubusercontent.com/assets/17103411/18508025/d7c07932-7a72-11e6-8af3-f123ce5d33f3.png)
![2016-09-14_11 56 00](https://cloud.githubusercontent.com/assets/17103411/18508026/d7c123aa-7a72-11e6-919a-f52846028a88.png)
![2016-09-14_11 56 02](https://cloud.githubusercontent.com/assets/17103411/18508027/d7c51b2c-7a72-11e6-8e10-82ae84e86d2e.png)
![2016-09-14_11 56 04](https://cloud.githubusercontent.com/assets/17103411/18508028/d7cdefea-7a72-11e6-9344-e360b8b4cea8.png)
![2016-09-14_11 56 06](https://cloud.githubusercontent.com/assets/17103411/18508032/d7d81e66-7a72-11e6-9e72-e5c247e73a1f.png)
![2016-09-14_11 56 07](https://cloud.githubusercontent.com/assets/17103411/18508029/d7d2a486-7a72-11e6-8e96-d295de5d0140.png)
![2016-09-14_11 56 09](https://cloud.githubusercontent.com/assets/17103411/18508030/d7d3ff52-7a72-11e6-8659-39473445fe78.png)
![2016-09-14_11 56 12](https://cloud.githubusercontent.com/assets/17103411/18508031/d7d48300-7a72-11e6-9587-fa1b0a83d536.png)

So yes I think there are some compatibilies issues with the difference of number of recipes between the two ores.

**Comment by AEnterprise** [comment]
i'm sorry but i believe the question here was 'give a list of what you can't make', that's just a wall of images of what you can make (causing a headace for my email client with all those pictures), that first list would have been enough i think

**Comment by BluSunrize** [comment]
Jesus wept, that's a load of images.
And I present you:
- Cupronickel Rods, Gears and Plates made with constantan:
http://puu.sh/raQbl/824ffe58f7.jpg
http://puu.sh/raQee/6f783dcbf4.jpg
http://puu.sh/raQet/14dfb11e09.jpg
- Constantan made with Non-IE dusts
http://puu.sh/raQfC/c4f3416f11.jpg
I don't support tiny dusts because I cba.
- Mortar used to crush Constantan
http://puu.sh/raQik/2d9b194d53.jpg
- TechReborn was never mentioned in the original report, take that up with them

Everything necessary you mentioned is totally possible.

**Comment by Hypsellis** [comment]
Hm it's maybe an issue caused by UniDict, I don't really know.

**Comment by BluSunrize** [comment]
Tell me which versions of the mods you are using.

**Comment by BluSunrize** [comment]
I wouldn't even have to ask that question if you read the blasted contribution guidelines in the first place and made a decent issue report.

**Comment by Hypsellis** [comment]
Substratum 1.8.1.0 and IE 0.10-40

**Comment by BluSunrize** [comment]
Yep. Same here. Recipes work fine. Issue irrelevant. Issue closed.
