### ISSUE TITLE
NPE: Tessellating block model

### ISSUE THREAD

**Issue by nikita488** [BluSunrize/ImmersiveEngineering#1420]
http://pastebin.com/1EpSVymB

**Comment by kane-thornwyrd** [comment]
MC 1.10.2
IE 0.10-40

@nikita488 Did you contacted your modpack author or is it you ?

**Comment by nikita488** [comment]
This is my modpack and i play on server. I just jump with Tinkers Construct "Slimesling" and my game crashed (I do this a lot and never crashed but this time i get crash)

**Comment by malte0811** [comment]
This is probably some sort of race condition (code running between the `containsKey`- and the `get`-call), there are at least 2 bits of code that could run simultaneously with the code that crashed (one by me and one by @BluSunrize). I will push a commit that should fix this later today.

**Comment by BluSunrize** [comment]
Fixed for future releases, see commit above
