### ISSUE TITLE
[0.8-32]/[0.10-40] Crusher+OpenComputers getInputStack errors when queried out of bounds

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#1421]
https://github.com/BluSunrize/ImmersiveEngineering/blob/1.10/src/main/java/blusunrize/immersiveengineering/common/util/compat/opencomputers/CrusherDriver.java#L84

The problem is that there is no way of knowing how many input stacks there are without iterating through them until you hit an error, meaning you have to pcall it.
It'd be awesome if it returned nil and the error description instead of outright erroring.
Either that or give the crusher a new queueLength function so we can get the bounds without probing it :)
Now that i think about it, I probably prefer the latter.

Edit:
On third thought, just get the whole inputstacks table. That would allow seeing the size and it would prevent issues like "size = getSize(); for i = 1, size do crusher.getInputStack(i) end" *iterates* "o darn, the crusher finished the stack in slot 1 and now getInputStack(size) errors", or missing stacks because they shift index during computation.

**Comment by malte0811** [comment]
There used to be a `getQueueSize` method, but it seems like I removed it and didn't readd it when porting CC/OC compat to 1.8.
I'll look into changing `getInputStack` to `getInputQueue`, it should be pretty straightforward. @BluSunrize should I remove `getInpuStack` or keep it and mark it as deprecated?

**Comment by BluSunrize** [comment]
Totally forgot about this one!
@malte0811 do whatever you think is best, I know nothing of OC, so I really don't know xD

**Comment by BluSunrize** [comment]
Fixed, see commit above
