### ISSUE TITLE
Cannot get IE power to transfer to EU/IC2 machines/storage 

### ISSUE THREAD

**Issue by dshatnerIII** [BluSunrize/ImmersiveEngineering#1424]
Issue: Cannot get IE power to operate IC2 machines. Tried connecting in various ways using MV and LV cables/connectors directly from a MV capacitor to IC2 machines and/or storage (battbox). Will not power or register at all on the IC2 machines.
 I hope this is not a stupid complaint but I have tried looking everywhere for a straight forward answer. I am trying to use limited mods, IE, IC2 & Forestry only as the main mods only (others installed: waila, journeymaps, forge). 
-MC v1.10.2
-IE v40

FTB makes it sound like it should be as simple as placing a lv/MV connector onto the IC2 machine and connecting with appropriate cable should convert and power the IC2 machine...

**Comment by ArukaAlter** [comment]
Power conversion isn't a thing anymore.

**Comment by dshatnerIII** [comment]
IC2 v2.6.27 installed

**Comment by dshatnerIII** [comment]
Ohh.. I am new to using mods and was looking forward to using the -IE power for everything. So there is no way to convert for IC2 and forestry at all? If so that is unfortunate. And thank you for your response.

**Comment by ArukaAlter** [comment]
Forestry uses RF, IE connectors can convert IF to RF.
As for EU, Malte said he might work on an addon for conversion or IE-esque EU transport.

**Comment by dshatnerIII** [comment]
Awesome I really appreciate your assistance. I'll close the issue.
