### ISSUE TITLE
Coke Oven accepts empty bottles in the "empty bucket" slot

### ISSUE THREAD

**Issue by The-Fireplace** [BluSunrize/ImmersiveEngineering#1425]
You said [here](https://github.com/BluSunrize/ImmersiveEngineering/issues/1319) that bottles can no longer be filled with Creosote, yet the Coke Oven still allows you to put empty bottles in the top right slot.
Steps to reproduce: Build a coke oven, then put a Glass Bottle in the top right slot.
This happened in Singleplayer.
Tested on IE 0.10-40

**Comment by ArukaAlter** [comment]
Creosote bottles are deprecated, use buckets.

**Comment by The-Fireplace** [comment]
@ArukaAlter I know. That is why I made this issue. If it can't make Creosote Bottles, it doesn't need to allow Glass Bottles in the slot anymore.

**Comment by BluSunrize** [comment]
I can't change that. I tried, in fact, just now changing the code to a different detection for fluid containers. But as long as glass bottles are valid fluid containers , they will go into my slots because I accept any empty fluid containers.
