### ISSUE TITLE
Enderio conduits not working with thermoelectric generator [1.10.2]

### ISSUE THREAD

**Issue by UnNinja** [BluSunrize/ImmersiveEngineering#1426]

**Comment by UnNinja** [comment]
:/ note to self, don't post bug reports while doing 37 things at once.

A user on my server has reported that enderio eoncuits seem to not pull power out of thermoelectric generators. tested with the conduit connected on all sides, and they get power if they use IE wires to pull the power our

**Comment by theunkn0wn1** [comment]
That would be because IE generators output IF rather than RF IIRC. 
EIO expects RF which it can get from connectors but not directly from the generator
