### ISSUE TITLE
Client crash [1.10.2]

### ISSUE THREAD

**Issue by UnNinja** [BluSunrize/ImmersiveEngineering#1427]
[Crash log](http://pastebin.com/6EAv8UMh)
user said they attempted to connect one lv to another. one of the relays had a handful of wires linked to lv connectors

**Comment by theunkn0wn1** [comment]
Can you reproduce this without Optifine?

**Comment by malte0811** [comment]
Duplicate of #1420, should be fixed by 3ac6c5808069de010d9880520edefc31377331db.

**Comment by BluSunrize** [comment]
I'll close this then ^^
