### ISSUE TITLE
TCon 2.5.0 API change broke IE

### ISSUE THREAD

**Issue by xannor** [BluSunrize/ImmersiveEngineering#1430]
https://gist.github.com/xannor/3d7ff33268c65612694132e6f81c179a

Looks like Tinkers changed something in their latest release and your helper broke.

**Comment by KnightMiner** [comment]
Quote from the changelog:

> This update comes with several internal restructures and WILL break compatibility with some other mods. The changes are easy to adapt to, however.

So yeah, its expected which one of the reasons 2.5.0 is still considered an alpha

**Comment by BluSunrize** [comment]
Ya. I know. I told boni to tell people that I've already fixed it. I just haven't built and published yet.
