### ISSUE TITLE
crash with TConstruct & Jurassicraft updates

### ISSUE THREAD

**Issue by RebeccaRedstone** [BluSunrize/ImmersiveEngineering#1431]
Using Immersive Engineering v 1.10.2 - 40 
All was well until I updated Jurassicraft and TConstruct. 

See gist[here] (https://gist.github.com/RebeccaRedstone/b5d562e414601193547e7e3783406c07)

**Comment by RebeccaRedstone** [comment]
Turns out I had not yet updated Jurassicraft - so this would just be with the latest version of TConstruct v 2.5.0. :)

**Comment by Cassiobsk8** [comment]
same here but i dont have Jurassicraft, i just update TConstruct.

**Comment by ArukaAlter** [comment]
Read the recent closed issues, it is already fixed for the next version.
