### ISSUE TITLE
problem of compatibility between IC2 and IE Uranium

### ISSUE THREAD

**Issue by Hypsellis** [BluSunrize/ImmersiveEngineering#1433]
I report again this issue because from what seems to be said in the IC2 issue tracker, the problem really comes from ImmersiveEngineering. http://bt.industrial-craft.net/view.php?id=1996

**Comment by bookerthegeek** [comment]
I am confused as to what you are wanting. Please provide a use case / example or this as a problem, and your ideal solution.

**Comment by mindforger** [comment]
as from the IC2 Bug Report i understand he wants IC2 Uranium Ore to be smeltable into IE Uranium Ingots !? Boy this craves for a Minetweaker Oredict checkup, hope it will be available for 1.10 soon

**Comment by BluSunrize** [comment]
Furnaces recipes do not use the ore dictionary. I have explained this twice now. Your only option is the IE crusher into dust, into ingot. This is not an error, this is IC2's choice not to have an ingot for Uranium, and I cannot do a whole lot about it.

**Comment by Hypsellis** [comment]
Minetweaker is already disponible for 1.10, and use minetweaker is surely the worst thing to do.

**Comment by BluSunrize** [comment]
Okay, let me phrase this as simple as possible:
This is NOT unwanted behaviour, and NOT a compat problem. IC2 specifically does not add Uranium ingots. The fact that *their* Uranium Ore does not smelt into *my* ingots is absolutely intentional and good the way it is.

**Comment by bookerthegeek** [comment]
@BluSunrize Oh I know this. I am asking @Hypsellis to spell out what he wants so I could Barney style a response for him. :smile: 

@Hypsellis I'm still waiting for your answer.

**Comment by Hypsellis** [comment]
If you still wait my answer, it's that you didn't read well all we wrote about it. And I think I already explained enough well the problem. Anyway since it doesn't seem to have any solutions, I suppose this issue can be closed.

**Comment by BluSunrize** [comment]
No, you have in fact, not explained your actual example. What I personally would like to know is the recipe process you are missing. From how I *think* I understood you, your thought process is as follows:
Uranium Ore (IC2) -> Furnace -> Uranium Ingot (IE)
You are expecting to get IE's ingots out of IC2s ore, is that correct?

**Comment by Hypsellis** [comment]
Yeah it's that, and it's pretty strange that it's yourself who ask me for doing what, I think it's pretty obvious, for using uranium ingot to craft and use machines which need it in IE...

**Comment by BluSunrize** [comment]
No machine in IE needs Uranium to craft. It is currently solely used as a heatsource for the Thermoelectic Generator.
Meanwhile, IC2's uranium has actual uses *and* their uranium blocks work *just as well* for IE's generator. So I am honestly confused as to what the issue.
And on the offchance of repeating myself: I do not add the smelting recipe for IC2's uranium ore. It smelts into their ingots, because it's their mod.

**Comment by Hypsellis** [comment]
IC2 haven't any Uranium ingots, they use particular items similar to dust which is got with thermal centrifuge, so really far from the IE Uranium processing. http://wiki.industrial-craft.net/index.php?title=Uranium#Uranium-238

**Comment by BluSunrize** [comment]
You are absolutely missing the point.
IC2 adds Uranium as that weird blob instead of an ingot. However: You can still craft Uranium blocks with that. You do not *need* an ingot.

**Comment by Hypsellis** [comment]
I don't think you can make an Uranium block with Uranium from IC2 since IC2 doesn't add any Uranium blocks...

**Comment by BluSunrize** [comment]
Yes. Yes it does. You literally linked it above.
But by all means, have a look at it again, in my dev environment, right now:
http://puu.sh/raNga/b4380c5b34.jpg

**Comment by Hypsellis** [comment]
Yeah sorry, I had forgotten about this one.

**Comment by Hypsellis** [comment]
All the recipes possible with IC2 Uranium ore:
![2016-09-14_12 05 45](https://cloud.githubusercontent.com/assets/17103411/18508312/f7d53cf2-7a73-11e6-906c-62e864e4130d.png)
![2016-09-14_12 05 17](https://cloud.githubusercontent.com/assets/17103411/18508310/f7d45454-7a73-11e6-8209-72c892d04953.png)
![2016-09-14_12 05 20](https://cloud.githubusercontent.com/assets/17103411/18508308/f7d3c660-7a73-11e6-9881-ee0d82ea42d8.png)
![2016-09-14_12 05 22](https://cloud.githubusercontent.com/assets/17103411/18508313/f7d608d0-7a73-11e6-8b40-c6ce0db1e308.png)
![2016-09-14_12 05 24](https://cloud.githubusercontent.com/assets/17103411/18508311/f7d50e9e-7a73-11e6-912b-6ff379aaaea4.png)
![2016-09-14_12 05 29](https://cloud.githubusercontent.com/assets/17103411/18508309/f7d41b88-7a73-11e6-901b-f6026a6ed2c7.png)
![2016-09-14_12 05 30](https://cloud.githubusercontent.com/assets/17103411/18508317/f7ea5e02-7a73-11e6-8a38-53ee17dbd99a.png)
![2016-09-14_12 05 32](https://cloud.githubusercontent.com/assets/17103411/18508314/f7e83578-7a73-11e6-9634-5647f6295811.png)
![2016-09-14_12 05 35](https://cloud.githubusercontent.com/assets/17103411/18508318/f7ec4e4c-7a73-11e6-8841-4090f9e22a70.png)
![2016-09-14_12 05 36](https://cloud.githubusercontent.com/assets/17103411/18508315/f7e91470-7a73-11e6-9b66-256d24e70f09.png)
![2016-09-14_12 05 37](https://cloud.githubusercontent.com/assets/17103411/18508319/f7edc36c-7a73-11e6-93fd-55e7872e2431.png)
![2016-09-14_12 05 39](https://cloud.githubusercontent.com/assets/17103411/18508316/f7e960b0-7a73-11e6-93e9-c8cdb72a3753.png)

**Comment by Hypsellis** [comment]
And now with IE Uranium ore:
![2016-09-14_12 06 41](https://cloud.githubusercontent.com/assets/17103411/18508350/1b9850b6-7a74-11e6-9a03-3a0cd834b40a.png)
![2016-09-14_12 06 42](https://cloud.githubusercontent.com/assets/17103411/18508346/1b952882-7a74-11e6-85d5-545acd75d63c.png)
![2016-09-14_12 06 43](https://cloud.githubusercontent.com/assets/17103411/18508347/1b956356-7a74-11e6-8687-ca4f2ef9bb0e.png)
![2016-09-14_12 06 44](https://cloud.githubusercontent.com/assets/17103411/18508348/1b9595ba-7a74-11e6-8718-418818bf7b5b.png)
![2016-09-14_12 06 45](https://cloud.githubusercontent.com/assets/17103411/18508351/1b9c2466-7a74-11e6-848e-b7a383ecb8ac.png)
![2016-09-14_12 06 47](https://cloud.githubusercontent.com/assets/17103411/18508349/1b96a5e0-7a74-11e6-9923-d3ae8eb5a9ac.png)
![2016-09-14_12 06 48](https://cloud.githubusercontent.com/assets/17103411/18508352/1ba870b8-7a74-11e6-9127-7bca5524ef5b.png)
![2016-09-14_12 06 49](https://cloud.githubusercontent.com/assets/17103411/18508354/1babc4de-7a74-11e6-886c-34ee3c0f69e3.png)
![2016-09-14_12 06 50](https://cloud.githubusercontent.com/assets/17103411/18508353/1ba94ca4-7a74-11e6-84d1-fafdca0d5ddb.png)
![2016-09-14_12 06 50_2](https://cloud.githubusercontent.com/assets/17103411/18508355/1bad7c16-7a74-11e6-9871-587e841096cb.png)
![2016-09-14_12 06 51](https://cloud.githubusercontent.com/assets/17103411/18508356/1baedd54-7a74-11e6-98d3-48cbbde45c1a.png)
![2016-09-14_12 06 52](https://cloud.githubusercontent.com/assets/17103411/18508357/1bb50b3e-7a74-11e6-8f97-98cf9230f512.png)
![2016-09-14_12 06 53](https://cloud.githubusercontent.com/assets/17103411/18508358/1bbd51e0-7a74-11e6-87cb-3a2576794198.png)
![2016-09-14_12 06 55](https://cloud.githubusercontent.com/assets/17103411/18508359/1bbd74b8-7a74-11e6-9b5f-ad176c24a55c.png)
![2016-09-14_12 06 38](https://cloud.githubusercontent.com/assets/17103411/18508361/1bc23f20-7a74-11e6-87f5-4856f0cbda69.png)

**Comment by AEnterprise** [comment]
great another picture wall, if you are using the IC2 ore please look further then just recipes using the ore, look at the recipes to make the uranium block and work your way back through the uranium proccessing chain

iirc you wana run the ore through a pulverizer and then put the pulerized stuff in a thermal thing

**Comment by BluSunrize** [comment]
Seriously. You have *no* valid issue here. Everything you have specifically described as wanting to do, you *can* do.
IC2 Uranium is used for everything IC2. Should you ever want to make anything from IC2, you're covered.
IE has ONE SINGLE USE for Uranium. The Thermoelectric Generator. That requires *Uranium Blocks*. And the blocks for IC2 work *just fine*

Unless you present me with a specific recipe that *requires* IE Uranium and that the result of *cannot* be substituted by IE, this issue is invalid.

**Comment by Hypsellis** [comment]
Okay I think that the best is to close this issue because everybody is annoyed and I think that nobody here want to get into fights for knowing who has right or wrong, so just let's stop here.

**Comment by BluSunrize** [comment]
...wow, what a massive timewaste. I mean, I'm honestly trying to help you here. Or I am at least trying to explain that you can use everything as you currently have it. The fact that you chose to cancel the conversation is helping nobody.

**Comment by Hypsellis** [comment]
I just hate to fight me with people, it's stupid and childish and I passed the old for that. This discussion began to be very be very strained and will have surely finished into a fight, so I prefer to stop everything here.Anyway you told me that there are no ways to solve this problem.

**Comment by bookerthegeek** [comment]
I must be stupid but I am still unsure what the issue is.

WHAT is it you want?  I do not want to fight, I truly am curious as to what you are asking.

**Comment by AEnterprise** [comment]
to me it just seems like he doesn't know how to craft the uranium block
