### ISSUE TITLE
Treated Wood Slabs Can't Be Pulled By Sticky Piston

### ISSUE THREAD

**Issue by Swat6** [BluSunrize/ImmersiveEngineering#1434]
In version 0.10-40 and minecraft version of 1.10.2.

**Comment by kane-thornwyrd** [comment]
It's more than just the treated wood slabs !

![2016-09-12_06 49 17](https://cloud.githubusercontent.com/assets/625236/18424984/91f9d7e0-78b5-11e6-97e0-7a24fa073a3a.png)

All the slab are affected !

**Comment by BluSunrize** [comment]
*Shrug*
It won't ever work for slabs, since they use TileEntities. Same for most blocks in IE. For the few that don't use them...I'm not that bothered, tbh :V
