### ISSUE TITLE
Wire Relays can be attached to devices requiring a Wire Connector with no warning.

### ISSUE THREAD

**Issue by calloatti** [BluSunrize/ImmersiveEngineering#1436]
Latest version 1.10.2

Wire Relays can be used where Wire Connectors are required, with no warning at all, and you are left wondering why things don't work at all.

Desired behavior: Do not allow Wire Relays to be used where a Wire Connector is required and issue a warning, just like when using the wrong cable version (LV, MV, HV)

**Comment by mindforger** [comment]
This sounds pretty lazy ... Wire Relays can be attached almost anywhere, so why making a special case when attaching them to an RF-Recevier? The are called "relay" as in relaying wires and not "connector" as in connecting the wire to something.

**Comment by BluSunrize** [comment]
...What? Read the manual. It clearly states what connectors do and what relays are for. That's the basic principle of IE's wiring system. It's not that difficult .-.

**Comment by calloatti** [comment]
Oh well, with that attitude don't expect any more contributions from me.

**Comment by BluSunrize** [comment]
O...kay. Sure. Have a very nice day.

**Comment by BluSunrize** [comment]
I will keep title and original report though. Makes it easier to remember what this was about.
