### ISSUE TITLE
TCon Crash

### ISSUE THREAD

**Issue by WolfieWaffle** [BluSunrize/ImmersiveEngineering#1438]
When enabling support for TCon, I get this crash:
http://pastebin.com/0gei4EgK

**Comment by BluSunrize** [comment]
Please search previous issues before reporting, this is a duplicate of #1431 and #1429
Will be fixed in the next release, the new TCon version clearly said that all addons would break.

**Comment by WolfieWaffle** [comment]
Ok sorry
