### ISSUE TITLE
Feature: In-world fluids

### ISSUE THREAD

**Issue by WolfieWaffle** [BluSunrize/ImmersiveEngineering#1439]
Currently there is no in world fluids for diesel, plant oil, or anything. Low priority, but would be nice.

**Comment by BluSunrize** [comment]
Literally no point to that. They wouldn't have any sensible effects

**Comment by WolfieWaffle** [comment]
I suppose, it just feels weird though right clicking on the ground with a bucket and nothing happening. You could make some of them flammable like Buildcraft oil

**Comment by AEnterprise** [comment]
it would allow storing it in multiblock tanks with the BC floodgate and pump

**Comment by WolfieWaffle** [comment]
^
