### ISSUE TITLE
Suggestion: Item Splitter

### ISSUE THREAD

**Issue by WolfieWaffle** [BluSunrize/ImmersiveEngineering#1440]
Either have an option in the item router to divide stacks evenly between outputs, or make another item. Has some niche uses and doesn't affect the rest of the mod much at all.

**Comment by BluSunrize** [comment]
Eeeh. Splitting conveyor belt doesn't split stacks but alternates between left and right. Might add a router thingy, but not high on the todo.

**Comment by WolfieWaffle** [comment]
hm, I haven't seen the splitting conveyor belt. Is that in a beta version?

**Comment by BluSunrize** [comment]
I basically just finished it, not released yet. Check Twitter or latest commits =P

**Comment by kane-thornwyrd** [comment]
@WolfieWaffle follow @BluSunrize on Beam :)

**Comment by discodancepant** [comment]
It would be cool if the splitter could be shift+right clicked with a hammer to switch the output between Left/Middle/Right, Left/Middle, Middle/Right, and Left/Right. The first option would obviously split it three ways.

**Comment by BluSunrize** [comment]
Except there is no decent way to render that, otherwise I would have done it =)

**Comment by discodancepant** [comment]
I thought something like this might work. (try not to pay attention to my terrible texturing/modelling)
https://www.dropbox.com/s/xnmy3en99wo7dnj/conveyor_sorter.png?dl=0
The blue parts are supposed to look like a strip door often used in industrial environments.

**Comment by WolfieWaffle** [comment]
I think if you made the blue a bit less vibrant and used something besides "In' and "Out" it could work well. It just depends on if mod author wants to use it.

**Comment by BluSunrize** [comment]
Not sure if I'd do that for the splitter, but damn. Those strip doors are a fantastic idea for decoration! Mind if I take that idea for conveyors in general? :D

**Comment by discodancepant** [comment]
yeah dude, do whatever. just had an idea I thought you could use.

"In" and "Out" was mostly to show what was where on the model because the sides are too similar. On an actual model you would see the moving conveyor strip at each side.

**Comment by KnightMiner** [comment]
Would it be odd to have two separate? A simple one that acts like the one now, and an advanced configurable one with the strip doors? That way you get the full function without loss of the simplicity/aesthetic of the old one.

**Comment by discodancepant** [comment]
Sounds like a lot of work on his part for a niche function. It would be cool/useful, but take even more time to develop, time taken away from perhaps more pressing features. If it could be developed through the api by a third party, that would be the better answer IMO. BluSunrize would have to change the API a little for that to happen though (as far as i can tell anyway).
