### ISSUE TITLE
Unknown crash when trying to load game

### ISSUE THREAD

**Issue by samiscool51** [BluSunrize/ImmersiveEngineering#1443]
What is the bug?
A Crash
[crash-2016-09-13_08.44.49-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/468491/crash-2016-09-13_08.44.49-client.txt)

What did you do to make it happen?
My java was sad and did not want to play minecraft 
(in real life i updated some mods, can't remember witch ones tho, but they don't use IE in any way like calling classes or using items from it)

Does it happen every time you do this?
tested it 3 times (once with optifine out of the mod folder, still happened) and the same result

Did this happen on a dedicated server (multiplayer servers), in LAN multiplayer or in singleplayer?
unknown if this happens to servers

What other mods were installed when the bug happened?
[modlist.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/468494/modlist.txt)

I am now sad because i can't play minecraft because java is sad
(i don't talk like this in real life)

**Comment by Alaberti** [comment]
You updated Tinker's Construct I'd wager. You might be able to load it if you turn of the Tinker's compat setting in the IE config.

**Comment by theunkn0wn1** [comment]
Yep, updated TConstruct is causing this. Known issue that has been delt with in an upcoming release.
#1442

**Comment by BluSunrize** [comment]
^ what they said. Please search before creating new issues.
