### ISSUE TITLE
Tinkers compat with new alpha

### ISSUE THREAD

**Issue by Voxel-Friend** [BluSunrize/ImmersiveEngineering#1445]
You probably already are aware, but just in case: New Tinkers alpha (1.10.2-2.5.0) has some internal changes made that breaks compatability for mods.
![i-thought-you-ought-to-know](https://cloud.githubusercontent.com/assets/12395262/18473953/245df254-7985-11e6-886b-1488eb906d4c.jpg)

**Comment by xWoom** [comment]
yes me too, this is a part from my crash report

	at blusunrize.immersiveengineering.common.util.compat.TConstructHelper.preInit(TConstructHelper.java:77)
	at blusunrize.immersiveengineering.common.util.compat.IECompatModule.doModulesPreInit(IECompatModule.java:67)
	at blusunrize.immersiveengineering.ImmersiveEngineering.preInit(ImmersiveEngineering.java:86)

**Comment by KnightMiner** [comment]
You could have tried searching for the issue to see if it's been reported 8 times already just to check if he knew first. Take #1431 for example.

**Comment by theunkn0wn1** [comment]
![image](https://cloud.githubusercontent.com/assets/3110986/18475036/bf7c26fe-7979-11e6-8fde-ec95faec3517.png)
9th time now, you guys just don't learn
Duplicate, fixed for upcoming releases
![image](https://cloud.githubusercontent.com/assets/3110986/18475159/4d8fe408-797a-11e6-906b-74dede4dcc0b.png)

**Comment by BluSunrize** [comment]
^ what they said. *Please* use the searchfunction.

**Comment by Voxel-Friend** [comment]
T.T Sorry I have a bad habit of not looking in closed issues only open ones.
