### ISSUE TITLE
Suggestion: Nerf the Crusher

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#1446]
as of version 08-32/10-40 the crusher outputs additional dusts for a few recipes:
- nickel for iron ore
- gold for copper ore
- lead for uranium ore, silver ore
- silver for lead ore

The absolute seas of nickel (which isn't used for anything besides nickel blocks and turning it into constantan, the latter of which also has limited application) you drown in from crushing iron ore make nickel ore itself rather redundant.
Also the finding 2 copper ore is as good as finding a single gold ore, in terms of getting gold is insane.
The remaining extra-output recipes don't seem to matter too much because their ores are relatively rare.

Unless there are good reasons for these extra outputs, i think they should be nerfed down to a flexible chance that can be set in the recipes.

**Comment by BluSunrize** [comment]
This is, indeed, a bug. There is supposed to be a chance system on these outputs, getting them with a 100% chance is something I never meant to implement. I was just being pretty stupid =P

**Comment by BluSunrize** [comment]
Fixed for future releases, see commit above!
