### ISSUE TITLE
Flood light cycles off and on and has a missing texture.

### ISSUE THREAD

**Issue by ProsperCraft** [BluSunrize/ImmersiveEngineering#1447]
ImmersiveEngineering-0.10-40
Minecraft version 1.10.2
Modpack - Allthemods

![2016-09-13_07 11 37](https://cloud.githubusercontent.com/assets/4427684/18475042/2b0e74aa-7982-11e6-9694-7382f3332a21.png)

**Comment by BluSunrize** [comment]
Duplicate of #1411
