### ISSUE TITLE
THE TINKERS CONSTRUCT ISSUE IS FIXED FOR FUTURE RELEASES. STOP REPORTING IT.

### ISSUE THREAD

**Issue by KristjanKr** [BluSunrize/ImmersiveEngineering#1448]
What happens: Game crashes on startup

What should happen: It shouldn't crash

Crash log: https://paste.ee/p/aWhnz

**Comment by KnightMiner** [comment]
Congrats, you are the tenth to report this issue by now, you really should search before creating another duplicate. #1431 has all the information you need.

**Comment by AEnterprise** [comment]
sugestion: could the title of this changed to crash with tinkers on startup, leave it open and put a giant note it's fixed in the next version? seems to be the only way for people to notice it's a duplicate

**Comment by BluSunrize** [comment]
Knowing people, that probably still would give me issue reports. But Ill do it for shits and giggles.

**Comment by psychofad** [comment]
haha, I noticed it so it must work, Just came here to see if it was reported :P

**Comment by mindforger** [comment]
i heared "shits" ? :) count me in >) :P

**Comment by BluSunrize** [comment]
Closing this, since the fix is released now.
