### ISSUE TITLE
[0.10-40] scaffold onto/into pipe

### ISSUE THREAD

**Issue by GeneWeaver** [BluSunrize/ImmersiveEngineering#1450]
book claims this is possible but i am unable to do this with steel or wood scaffold

THANKS

**Comment by BluSunrize** [comment]
Yep. With Forge's current model system, that's a lot less simple. It's on my todo list tho.

**Comment by BluSunrize** [comment]
It's back in...kinda. Not climbable, but you can cover the pipes.
