### ISSUE TITLE
[0.10-40] Post rendering issue

### ISSUE THREAD

**Issue by Senjosei** [BluSunrize/ImmersiveEngineering#1452]
if you right click a post with a hammer to make an extension it renders this until the post or another post is updated (e.g placing a block next to it)

1. Placed the post
![2016-09-14_15 53 46](https://cloud.githubusercontent.com/assets/17807328/18506052/52f5dc5c-7a94-11e6-93d5-8d1c92b0789d.png)
2. After right clicking
![2016-09-14_15 53 54](https://cloud.githubusercontent.com/assets/17807328/18506053/53313dc4-7a94-11e6-8521-6efebd090e2c.png)
3. After placing and removing a block next to it
![2016-09-14_15 54 15](https://cloud.githubusercontent.com/assets/17807328/18506054/534d3a24-7a94-11e6-806d-dda87b257be8.png)
4. Placing wood and steel post
![2016-09-14_15 54 41](https://cloud.githubusercontent.com/assets/17807328/18506055/5353288a-7a94-11e6-92ef-6c1265ede7c3.png)
5. Right click wooden post
![2016-09-14_15 54 46](https://cloud.githubusercontent.com/assets/17807328/18506056/5354c14a-7a94-11e6-82b4-c7231d2b2a02.png)
6. Right click steel post (wood post fixes it self)
![2016-09-14_15 54 50](https://cloud.githubusercontent.com/assets/17807328/18506057/53592dac-7a94-11e6-87a8-7bc49fb6366d.png)
7. Right click the other side of wood post
![2016-09-14_15 54 56](https://cloud.githubusercontent.com/assets/17807328/18506058/535b47fe-7a94-11e6-9c36-d3e18f69b797.png)
8. Destroyed steel post arm
![2016-09-14_15 55 08](https://cloud.githubusercontent.com/assets/17807328/18506060/5381a67e-7a94-11e6-8886-95a13a3f4ddc.png)

**Comment by BluSunrize** [comment]
are you using Optifine by any chance? because the lighting on those posts looks off.

**Comment by Senjosei** [comment]
yes but even with it turned off it still bugged but i just found out an interesting thing.
whether im using optifine or not it seems that its affected by what angle? or position? im right clicking at.
sometime it renders correctly but if i change where im looking at, sometimes its bugged

**Comment by BluSunrize** [comment]
Well for future reference, issues with optifine don't count. This one in particular does happen otherwise as well, and I can't really fix it. However, any blockupdate will immediately fix the rendering. So just placing another block or smth, and it'll look alright. Sorry that this is an inconvenience, but there is not a whole lot that can be done for this.
