### ISSUE TITLE
[0.10-40] FPS drop when looking at waterwheel

### ISSUE THREAD

**Issue by guachitonico** [BluSunrize/ImmersiveEngineering#1453]
I run minecraft 1.10 at about 130FPS overall. However, when I look at my waterwheel setup (3 waterwheels mostly surrounded by wooden planks, connected with IE wiring), FPS drop to about 40 (the drop is about 40% fps)
The F3 debugger shows that the 'game renderer -> Entities -> Block entities' is the responsible of the slow down.

I will be happy to do more debugging, if needed.

**Comment by malte0811** [comment]
What version of IE are you using? If you are using a version before build 39 (0.10-39), try updating. That version might fix or at least reduce the lag they cause.

**Comment by guachitonico** [comment]
I'm using 0.10-40

**Comment by miuirussia** [comment]
Confirm that issue in latest build from source code

**Comment by BluSunrize** [comment]
Yeah. I can't help it. New rendering in TESRs isn't pretty.

**Comment by RobertLSnead** [comment]
I have the same problem! :(  I was not sure what was causing it till I checked several posts!  Thanks for sharing!  Hopefully we will see a fix for this?

**Comment by BluSunrize** [comment]
You probably won't. I can't really fix this any further than it is.

**Comment by guachitonico** [comment]
Surely it's just one or two functions taking up most of the time, right? During the next days, if not tomorrow, I'll try to pinpoint the bottleneck.

**Comment by BluSunrize** [comment]
Yeah, It's the function that renders the model. I can easily improve FPS by having it not render.

**Comment by guachitonico** [comment]
It would be an easy fix for sure :smiley: 
Jokes aside, I can't recall this happening in previous IE versions, that's why I find it weird.

**Comment by BluSunrize** [comment]
Because "previous versions" were 1.7 and rendering changed entirely in 1.8.

**Comment by AEnterprise** [comment]
could the forge animation api help in making it less intensive or are you already using that?

**Comment by malte0811** [comment]
I have done some optimizing on the waterwheel render (still need to port those changes to the windmills), see the commit above. It isn't perfect, but with 20 waterwheels in an otherwise empty superflat world I get ~15 FPS on master and ~30 FPS on 05743f120016858ae75a02fa25a7b6bc3f45571e.

**Comment by BluSunrize** [comment]
It's not the animation that does it. It's the rendering of the quads.

**Comment by guachitonico** [comment]
Great to see at least some optimization can be done for it.

**Comment by enzyme-a113-2** [comment]
Better with Mod's windmills / waterwheels don't lag, and they are just as graphically complex, so there must be a way to render them more efficiently.

**Comment by malte0811** [comment]
I think I've got it now:
![2016-09-24_18 44 55](https://cloud.githubusercontent.com/assets/10406104/18809835/079c23d8-8287-11e6-9be9-c0c227b101fc.png)
(Those are 32 water wheels!)
I will probably push the fix tomorrow, since I will be working on a different project (rendering in n-dimensional space) this evening.
@enzyme-a113-2 thank you for pointing me at Better with mods, their code sort of pushed me into the right direction, though the stuff I have written is even more low-level than theirs.

**Comment by guachitonico** [comment]
Awesome news! Can't wait to try out the new build.

**Comment by enzyme-a113-2** [comment]
Nice fix, but you also need to change the excavator's wheel to use the new rendering method. (it still causes massive lag)

**Comment by BluSunrize** [comment]
he doesn't /need/ to do anything. He might do it if you actually use a "please" in  a sentence ;)
