### ISSUE TITLE
[1.10.2 feature] 3x3x3 multiblock capacitors  . and inserter 

### ISSUE THREAD

**Issue by MrEvilCookie** [BluSunrize/ImmersiveEngineering#1455]
Please can you add 3x3x3 multiblock capacitors & inserters like in factorio or magneticraft?
![screenshot-of-magneticraft-mod-27](https://cloud.githubusercontent.com/assets/20132158/18519002/e69465da-7aaa-11e6-9b9d-f7308abd8937.png)
![placeonfarside](https://cloud.githubusercontent.com/assets/20132158/18519010/ec4cf2d0-7aaa-11e6-8ca2-dd6414ed0102.gif)

**Comment by BluSunrize** [comment]
Nah. Never played Factorio nor used Magneticraft. Besides, what's the point in ripping off an existing mod?

**Comment by MrEvilCookie** [comment]
3x3x3 capacitors?

**Comment by BluSunrize** [comment]
No.
