### ISSUE TITLE
Skyhook Fails in Survival.

### ISSUE THREAD

**Issue by Batbaha** [BluSunrize/ImmersiveEngineering#1456]
I have two points setup with HV connectors and wiring.  If I grab the connector in survival with the Skyhook I take half a heart of damage and just fall.    If I do the exact same procedure in Creative no issues, it works fine. 

Using MC 1.7.10 IM ver 0.7.7

**Comment by BluSunrize** [comment]
Are you holding the button down?

**Comment by Batbaha** [comment]
Ok, this is weird, I was holding the button down as it would work in Creative fine.  I just double checked in Survival and it worked.  I must not have been holding it down.  Odd I would in Creative but not Survival but alas that would be an EU issue ;)

Thank you for the reply and Skyhook is working as intended.

Apologies 
Bat,

**Comment by BluSunrize** [comment]
That was an easy fix! Glad we figured that out! :D
