### ISSUE TITLE
Strange RF throughput issues

### ISSUE THREAD

**Issue by JamesArhy** [BluSunrize/ImmersiveEngineering#146]
In 0.1.9 I was able to make 3-4 electrum connections off of a single MV connector with no issue.  After upgrading to 0.3.3 things get sketchy starting on the third connection.  I used to have a single MV capacitor with an input connector and output connector but recently had to put two additional connectors on the capacitor to sort out the load issue.  I'm not sure if this is by design but I wanted to bring it up in case it wasn't.

**Comment by BluSunrize** [comment]
Wires used to put all teh power into the first machine they can reach. That behaviour was changed in 0.2.0, wires will now distribute energy equally to all connected outputs.
