### ISSUE TITLE
[0.10-41] Can't form the Assembler multiblock

### ISSUE THREAD

**Issue by Pihrra** [BluSunrize/ImmersiveEngineering#1460]
I seem to be unable to make the assembler. The Engineer Manual shows green ticks in the materials list so I'm using the right blocks. I triple checked that I put them in the right place according to the manual but nothing happens when I click one of the conveyor belt (or any other block for that matter).
I had the same issue with version 0.10-40.

(Sorry for the empty issue at first I pressed Enter a bit too soon.)

**Comment by BluSunrize** [comment]
Please read the contribution guidelines and follow them, because I cannot reproduce the issue.

**Comment by Pihrra** [comment]
Sorry I pressed Enter a bit too soon I hopped to fix it before anyone would find it but I failed.

**Comment by BluSunrize** [comment]
Pictures? =P

**Comment by Pihrra** [comment]
Oh my god ! I was so sure I did it right but I put the redstone engineering blocks in the wrong place ! I've been stuck for two days trying to make it checking each time for mistakes, updating mods, removing mods I didn't use, etc. 
Well I guess I'll have to have my eyes checked. Sorry for wasting your time.

**Comment by BluSunrize** [comment]
No problem! Better to have it resolved like this than be confused for another week, right? :D

**Comment by Pihrra** [comment]
Exactly ! Someone just had to point it out for me.
