### ISSUE TITLE
[0.10-41] Crash on Processing Ingot with Crusher

### ISSUE THREAD

**Issue by Alsender** [BluSunrize/ImmersiveEngineering#1461]
Minecraft Version: 1.10.2
Forge Version: 12.18.1.2080
Operating System: Linux (amd64) version 4.4.0-36-generic
Java Version: 1.8.0_91
Crash Report: http://pastebin.com/RYZ6rXca

As the title says, when I drop an ingot (iron) into the crusher to get grit, my game crashes.  Ores seem to process just fine.  This was working on 0.10-40.

**Comment by BluSunrize** [comment]
Fixed version is pending approval on Curse right now.
