### ISSUE TITLE
Crashing after update w/Tinkers Construct

### ISSUE THREAD

**Issue by CycnusJones** [BluSunrize/ImmersiveEngineering#1462]
Immersive Engineering version 0.10-41 is causing a crash during Pre-initialization when installed along side Tinkers Construct version 2.4.0.jenkins325.  Immersive Engineering version 0.10-40 loads fine with the same version of Tinkers Construct.

Here is the crash log: [http://pastebin.com/XGr8iGAG]

**Comment by BluSunrize** [comment]
Update Tinkers or use the old IE.
New IE requires TCon v2.5.0 or later

**Comment by CycnusJones** [comment]
I downgraded IE already, thanks for the quick response. I didn't realize Tinkers had an upgrade, settings weren't showing alpha.  Thanks again!!

**Comment by KnightMiner** [comment]
I believe you can actually add a version to the "after" dependency in your main mod class to limit what versions it will load with, at least it works with "required-after" so I don't see why it wouldn't with "after".

It would be nicer for Forge to tell people of the issue rather than a crash

**Comment by BluSunrize** [comment]
Yeah, I know, I forgot about doing that sadly. Already daelt with for next version
