### ISSUE TITLE
Crash at start with v. 41/42

### ISSUE THREAD

**Issue by mrtomwolf** [BluSunrize/ImmersiveEngineering#1464]
With v. 40 it works fine:

http://pastebin.com/6eGd8M6X

**Comment by GirafiStudios** [comment]
You need to update Tinkers Construct to atleast version 2.5.0. Also duplicate of https://github.com/BluSunrize/ImmersiveEngineering/issues/1463

**Comment by mrtomwolf** [comment]
Ok, guess I'm switching to alpha builds to be able to use a beta build ;) Thanks for the quick reply.

**Comment by GirafiStudios** [comment]
No problem :) You can also switch back to v. 40 of IE if you prefer that I guess!

**Comment by mrtomwolf** [comment]
Nah, there's much more excitement to be found out here on the bleeding edge ;)

**Comment by mrtomwolf** [comment]
Confirmed that it works with Tinkers 2.5.1
