### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by calloatti** [BluSunrize/ImmersiveEngineering#1465]
`#################################################
         ForgeGradle 2.2-SNAPSHOT-c438b06        
  https://github.com/MinecraftForge/ForgeGradle  
#################################################
               Powered by MCP unknown               
             http://modcoderpack.com             
         by: Searge, ProfMobius, Fesh0r,         
         R4wk, ZeuX, IngisKahn, bspkrs           
#################################################
Found AccessTransformer: ImmersiveEngineering_at.cfg
:extractMcpMappings SKIPPED
:deobfCompileDeobfDepTask0 SKIPPED
:deobfCompileDeobfDepTask1 SKIPPED
:deobfCompileDeobfDepTask2 SKIPPED
:deobfCompileDeobfDepTask3 SKIPPED
:deobfCompileDeobfDepTask4 SKIPPED
:deobfCompileRemapDepSourcesTask5 SKIPPED
:deobfCompileRemapDepSourcesTask6 SKIPPED
:deobfCompileRemapDepSourcesTask7 SKIPPED
:deobfCompileRemapDepSourcesTask8 SKIPPED
:deobfCompileRemapDepSourcesTask9 SKIPPED
:deobfCompileDummyTask
:getVersionJson
:extractUserdev UP-TO-DATE
:downloadClient SKIPPED
:downloadServer SKIPPED
:splitServerJar SKIPPED
:mergeJars SKIPPED
:applyBinaryPatches SKIPPED
:deobfProvidedDummyTask
:extractDependencyATs SKIPPED
:extractMcpData SKIPPED
:genSrgs SKIPPED
:deobfMcMCP SKIPPED
:sourceApiJava UP-TO-DATE
:compileApiJava UP-TO-DATE
:processApiResources UP-TO-DATE
:apiClasses UP-TO-DATE
:sourceMainJava UP-TO-DATE
:compileJavaZ:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\ArcFurnace.java:4: error: package minetweaker does not exist
import minetweaker.IUndoableAction;
                  ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\ArcFurnace.java:5: error: package minetweaker does not exist
import minetweaker.MineTweakerAPI;
                  ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\ArcFurnace.java:6: error: package minetweaker.api.item does not exist
import minetweaker.api.item.IIngredient;
                           ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\ArcFurnace.java:7: error: package minetweaker.api.item does not exist
import minetweaker.api.item.IItemStack;
                           ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\ArcFurnace.java:9: error: package stanhebben.zenscript.annotations does not exist
import stanhebben.zenscript.annotations.Optional;
                                       ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\ArcFurnace.java:10: error: package stanhebben.zenscript.annotations does not exist
import stanhebben.zenscript.annotations.ZenClass;
                                       ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\ArcFurnace.java:11: error: package stanhebben.zenscript.annotations does not exist
import stanhebben.zenscript.annotations.ZenMethod;
                                       ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\ArcFurnace.java:15: error: cannot find symbol
@ZenClass("mods.immersiveengineering.ArcFurnace")
 ^
  symbol: class ZenClass
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\ArcFurnace.java:19: error: cannot find symbol
	public static void addRecipe(IItemStack output, IIngredient input, IItemStack slag, int time, int energyPerTick, @Optional IIngredient[] additives, @Optional String specialRecipeType)
	                             ^
  symbol:   class IItemStack
  location: class ArcFurnace
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\ArcFurnace.java:19: error: cannot find symbol
	public static void addRecipe(IItemStack output, IIngredient input, IItemStack slag, int time, int energyPerTick, @Optional IIngredient[] additives, @Optional String specialRecipeType)
	                                                ^
  symbol:   class IIngredient
  location: class ArcFurnace
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\ArcFurnace.java:19: error: cannot find symbol
	public static void addRecipe(IItemStack output, IIngredient input, IItemStack slag, int time, int energyPerTick, @Optional IIngredient[] additives, @Optional String specialRecipeType)
	                                                                   ^
  symbol:   class IItemStack
  location: class ArcFurnace
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\ArcFurnace.java:19: error: cannot find symbol
	public static void addRecipe(IItemStack output, IIngredient input, IItemStack slag, int time, int energyPerTick, @Optional IIngredient[] additives, @Optional String specialRecipeType)
	                                                                                                                           ^
  symbol:   class IIngredient
  location: class ArcFurnace
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\ArcFurnace.java:84: error: cannot find symbol
	public static void removeRecipe(IItemStack output)
	                                ^
  symbol:   class IItemStack
  location: class ArcFurnace
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\ArcFurnace.java:37: error: cannot find symbol
	private static class Add implements IUndoableAction
	                                    ^
  symbol:   class IUndoableAction
  location: class ArcFurnace
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\ArcFurnace.java:89: error: cannot find symbol
	private static class Remove implements IUndoableAction
	                                       ^
  symbol:   class IUndoableAction
  location: class ArcFurnace
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\BlastFurnace.java:5: error: package minetweaker does not exist
import minetweaker.IUndoableAction;
                  ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\BlastFurnace.java:6: error: package minetweaker does not exist
import minetweaker.MineTweakerAPI;
                  ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\BlastFurnace.java:7: error: package minetweaker.api.item does not exist
import minetweaker.api.item.IIngredient;
                           ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\BlastFurnace.java:8: error: package minetweaker.api.item does not exist
import minetweaker.api.item.IItemStack;
                           ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\BlastFurnace.java:10: error: package stanhebben.zenscript.annotations does not exist
import stanhebben.zenscript.annotations.Optional;
                                       ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\BlastFurnace.java:11: error: package stanhebben.zenscript.annotations does not exist
import stanhebben.zenscript.annotations.ZenClass;
                                       ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\BlastFurnace.java:12: error: package stanhebben.zenscript.annotations does not exist
import stanhebben.zenscript.annotations.ZenMethod;
                                       ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\BlastFurnace.java:19: error: cannot find symbol
@ZenClass("mods.immersiveengineering.BlastFurnace")
 ^
  symbol: class ZenClass
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\BlastFurnace.java:23: error: cannot find symbol
	public static void addRecipe(IItemStack output, IIngredient input, int time, @Optional IItemStack slag)
	                             ^
  symbol:   class IItemStack
  location: class BlastFurnace
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\BlastFurnace.java:23: error: cannot find symbol
	public static void addRecipe(IItemStack output, IIngredient input, int time, @Optional IItemStack slag)
	                                                ^
  symbol:   class IIngredient
  location: class BlastFurnace
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\BlastFurnace.java:23: error: cannot find symbol
	public static void addRecipe(IItemStack output, IIngredient input, int time, @Optional IItemStack slag)
	                                                                                       ^
  symbol:   class IItemStack
  location: class BlastFurnace
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\BlastFurnace.java:80: error: cannot find symbol
	public static void removeRecipe(IItemStack output)
	                                ^
  symbol:   class IItemStack
  location: class BlastFurnace
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\BlastFurnace.java:137: error: cannot find symbol
	public static void addFuel(IIngredient input, int time)
	                           ^
  symbol:   class IIngredient
  location: class BlastFurnace
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\BlastFurnace.java:195: error: cannot find symbol
	public static void removeFuel(IItemStack output)
	                              ^
  symbol:   class IItemStack
  location: class BlastFurnace
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\BlastFurnace.java:33: error: cannot find symbol
	private static class Add implements IUndoableAction
	                                    ^
  symbol:   class IUndoableAction
  location: class BlastFurnace
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\BlastFurnace.java:85: error: cannot find symbol
	private static class Remove implements IUndoableAction
	                                       ^
  symbol:   class IUndoableAction
  location: class BlastFurnace
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\BlastFurnace.java:146: error: cannot find symbol
	private static class AddFuel implements IUndoableAction
	                                        ^
  symbol:   class IUndoableAction
  location: class BlastFurnace
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\BlastFurnace.java:200: error: cannot find symbol
	private static class RemoveFuel implements IUndoableAction
	                                           ^
  symbol:   class IUndoableAction
  location: class BlastFurnace
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\BottlingMachine.java:4: error: package minetweaker does not exist
import minetweaker.IUndoableAction;
                  ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\BottlingMachine.java:5: error: package minetweaker does not exist
import minetweaker.MineTweakerAPI;
                  ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\BottlingMachine.java:6: error: package minetweaker.api.item does not exist
import minetweaker.api.item.IIngredient;
                           ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\BottlingMachine.java:7: error: package minetweaker.api.item does not exist
import minetweaker.api.item.IItemStack;
                           ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\BottlingMachine.java:8: error: package minetweaker.api.liquid does not exist
import minetweaker.api.liquid.ILiquidStack;
                             ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\BottlingMachine.java:10: error: package stanhebben.zenscript.annotations does not exist
import stanhebben.zenscript.annotations.ZenClass;
                                       ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\BottlingMachine.java:11: error: package stanhebben.zenscript.annotations does not exist
import stanhebben.zenscript.annotations.ZenMethod;
                                       ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\BottlingMachine.java:15: error: cannot find symbol
@ZenClass("mods.immersiveengineering.BottlingMachine")
 ^
  symbol: class ZenClass
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\BottlingMachine.java:19: error: cannot find symbol
	public static void addRecipe(IItemStack output, IIngredient input, ILiquidStack fluid)
	                             ^
  symbol:   class IItemStack
  location: class BottlingMachine
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\BottlingMachine.java:19: error: cannot find symbol
	public static void addRecipe(IItemStack output, IIngredient input, ILiquidStack fluid)
	                                                ^
  symbol:   class IIngredient
  location: class BottlingMachine
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\BottlingMachine.java:19: error: cannot find symbol
	public static void addRecipe(IItemStack output, IIngredient input, ILiquidStack fluid)
	                                                                   ^
  symbol:   class ILiquidStack
  location: class BottlingMachine
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\BottlingMachine.java:76: error: cannot find symbol
	public static void removeRecipe(IItemStack output)
	                                ^
  symbol:   class IItemStack
  location: class BottlingMachine
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\BottlingMachine.java:29: error: cannot find symbol
	private static class Add implements IUndoableAction
	                                    ^
  symbol:   class IUndoableAction
  location: class BottlingMachine
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\BottlingMachine.java:81: error: cannot find symbol
	private static class Remove implements IUndoableAction
	                                       ^
  symbol:   class IUndoableAction
  location: class BottlingMachine
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\CokeOven.java:4: error: package minetweaker does not exist
import minetweaker.IUndoableAction;
                  ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\CokeOven.java:5: error: package minetweaker does not exist
import minetweaker.MineTweakerAPI;
                  ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\CokeOven.java:6: error: package minetweaker.api.item does not exist
import minetweaker.api.item.IIngredient;
                           ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\CokeOven.java:7: error: package minetweaker.api.item does not exist
import minetweaker.api.item.IItemStack;
                           ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\CokeOven.java:9: error: package stanhebben.zenscript.annotations does not exist
import stanhebben.zenscript.annotations.ZenClass;
                                       ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\CokeOven.java:10: error: package stanhebben.zenscript.annotations does not exist
import stanhebben.zenscript.annotations.ZenMethod;
                                       ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\CokeOven.java:14: error: cannot find symbol
@ZenClass("mods.immersiveengineering.CokeOven")
 ^
  symbol: class ZenClass
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\CokeOven.java:18: error: cannot find symbol
	public static void addRecipe(IItemStack output, int fuelOutput, IIngredient input, int time)
	                             ^
  symbol:   class IItemStack
  location: class CokeOven
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\CokeOven.java:18: error: cannot find symbol
	public static void addRecipe(IItemStack output, int fuelOutput, IIngredient input, int time)
	                                                                ^
  symbol:   class IIngredient
  location: class CokeOven
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\CokeOven.java:75: error: cannot find symbol
	public static void removeRecipe(IItemStack output)
	                                ^
  symbol:   class IItemStack
  location: class CokeOven
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\CokeOven.java:28: error: cannot find symbol
	private static class Add implements IUndoableAction
	                                    ^
  symbol:   class IUndoableAction
  location: class CokeOven
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\CokeOven.java:80: error: cannot find symbol
	private static class Remove implements IUndoableAction
	                                       ^
  symbol:   class IUndoableAction
  location: class CokeOven
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\CraftTweakerHelper.java:7: error: package minetweaker does not exist
import minetweaker.MineTweakerAPI;
                  ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\CraftTweakerHelper.java:8: error: package minetweaker does not exist
import minetweaker.MineTweakerImplementationAPI;
                  ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\CraftTweakerHelper.java:9: error: package minetweaker.MineTweakerImplementationAPI does not exist
import minetweaker.MineTweakerImplementationAPI.ReloadEvent;
                                               ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\CraftTweakerHelper.java:10: error: package minetweaker.api.item does not exist
import minetweaker.api.item.IIngredient;
                           ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\CraftTweakerHelper.java:11: error: package minetweaker.api.item does not exist
import minetweaker.api.item.IItemStack;
                           ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\CraftTweakerHelper.java:12: error: package minetweaker.api.item does not exist
import minetweaker.api.item.IngredientStack;
                           ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\CraftTweakerHelper.java:13: error: package minetweaker.api.liquid does not exist
import minetweaker.api.liquid.ILiquidStack;
                             ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\CraftTweakerHelper.java:14: error: package minetweaker.api.oredict does not exist
import minetweaker.api.oredict.IOreDictEntry;
                              ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\CraftTweakerHelper.java:15: error: package minetweaker.util does not exist
import minetweaker.util.IEventHandler;
                       ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\CraftTweakerHelper.java:20: error: package minetweaker.api.minecraft does not exist
import static minetweaker.api.minecraft.MineTweakerMC.getItemStack;
                                       ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\CraftTweakerHelper.java:20: error: static import only from classes and interfaces
import static minetweaker.api.minecraft.MineTweakerMC.getItemStack;
^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\CraftTweakerHelper.java:21: error: package minetweaker.api.minecraft does not exist
import static minetweaker.api.minecraft.MineTweakerMC.getLiquidStack;
                                       ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\CraftTweakerHelper.java:21: error: static import only from classes and interfaces
import static minetweaker.api.minecraft.MineTweakerMC.getLiquidStack;
^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\CraftTweakerHelper.java:64: error: cannot find symbol
	public static ItemStack toStack(IItemStack iStack)
	                                ^
  symbol:   class IItemStack
  location: class CraftTweakerHelper
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\CraftTweakerHelper.java:71: error: cannot find symbol
	public static Object toObject(IIngredient iStack)
	                              ^
  symbol:   class IIngredient
  location: class CraftTweakerHelper
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\CraftTweakerHelper.java:90: error: cannot find symbol
	public static Object[] toObjects(IIngredient[] iStacks)
	                                 ^
  symbol:   class IIngredient
  location: class CraftTweakerHelper
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\CraftTweakerHelper.java:98: error: cannot find symbol
	public static FluidStack toFluidStack(ILiquidStack iStack)
	                                      ^
  symbol:   class ILiquidStack
  location: class CraftTweakerHelper
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\CraftTweakerHelper.java:103: error: cannot find symbol
	public static class ExcavatorEventHandler implements IEventHandler<ReloadEvent>
	                                                     ^
  symbol:   class IEventHandler
  location: class CraftTweakerHelper
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\CraftTweakerHelper.java:103: error: cannot find symbol
	public static class ExcavatorEventHandler implements IEventHandler<ReloadEvent>
	                                                                   ^
  symbol:   class ReloadEvent
  location: class CraftTweakerHelper
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\CraftTweakerHelper.java:106: error: cannot find symbol
		public void handle(ReloadEvent event)
		                   ^
  symbol:   class ReloadEvent
  location: class ExcavatorEventHandler
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\Crusher.java:4: error: package minetweaker does not exist
import minetweaker.IUndoableAction;
                  ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\Crusher.java:5: error: package minetweaker does not exist
import minetweaker.MineTweakerAPI;
                  ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\Crusher.java:6: error: package minetweaker.api.item does not exist
import minetweaker.api.item.IIngredient;
                           ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\Crusher.java:7: error: package minetweaker.api.item does not exist
import minetweaker.api.item.IItemStack;
                           ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\Crusher.java:9: error: package stanhebben.zenscript.annotations does not exist
import stanhebben.zenscript.annotations.Optional;
                                       ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\Crusher.java:10: error: package stanhebben.zenscript.annotations does not exist
import stanhebben.zenscript.annotations.ZenClass;
                                       ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\Crusher.java:11: error: package stanhebben.zenscript.annotations does not exist
import stanhebben.zenscript.annotations.ZenMethod;
                                       ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\Crusher.java:15: error: cannot find symbol
@ZenClass("mods.immersiveengineering.Crusher")
 ^
  symbol: class ZenClass
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\Crusher.java:19: error: cannot find symbol
	public static void addRecipe(IItemStack output, IIngredient input, int energy, @Optional IItemStack secondaryOutput, @Optional double secondaryChance)
	                             ^
  symbol:   class IItemStack
  location: class Crusher
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\Crusher.java:19: error: cannot find symbol
	public static void addRecipe(IItemStack output, IIngredient input, int energy, @Optional IItemStack secondaryOutput, @Optional double secondaryChance)
	                                                ^
  symbol:   class IIngredient
  location: class Crusher
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\Crusher.java:19: error: cannot find symbol
	public static void addRecipe(IItemStack output, IIngredient input, int energy, @Optional IItemStack secondaryOutput, @Optional double secondaryChance)
	                                                                                         ^
  symbol:   class IItemStack
  location: class Crusher
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\Crusher.java:86: error: cannot find symbol
	public static void removeRecipe(IItemStack output)
	                                ^
  symbol:   class IItemStack
  location: class Crusher
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\Crusher.java:39: error: cannot find symbol
	private static class Add implements IUndoableAction
	                                    ^
  symbol:   class IUndoableAction
  location: class Crusher
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\Crusher.java:91: error: cannot find symbol
	private static class Remove implements IUndoableAction
	                                       ^
  symbol:   class IUndoableAction
  location: class Crusher
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\Excavator.java:5: error: package minetweaker does not exist
import minetweaker.IUndoableAction;
                  ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\Excavator.java:6: error: package minetweaker does not exist
import minetweaker.MineTweakerAPI;
                  ^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\Excavator.java:7: error: package stanhebben.zenscript.annotations does not exist
import stanhebben.zenscript.annotations.*;
^
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\Excavator.java:14: error: cannot find symbol
@ZenClass("mods.immersiveengineering.Excavator")
 ^
  symbol: class ZenClass
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\Excavator.java:187: error: cannot find symbol
	@ZenClass("mods.immersiveengineering.MineralMix")
	 ^
  symbol:   class ZenClass
  location: class Excavator
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\Excavator.java:26: error: cannot find symbol
	private static class AddMineral implements IUndoableAction
	                                           ^
  symbol:   class IUndoableAction
  location: class Excavator
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker\Excavator.java:103: error: cannot find symbol
	private static class RemoveMineral implements IUndoableAction
	                                              ^
  symbol:   class IUndoableAction
  location: class Excavator
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
100 errors
 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 25.239 secs
`

**Comment by BluSunrize** [comment]
PLEASE read the contribution guidelines and spoiler your logs. Noone wants that massive wall of text.
Secondly: I don't do support on custom building. If you can't figure it out, you probably shouldn't be custom building.
Thirdly: You're missing a library.

**Comment by calloatti** [comment]
I solved it. Work on you social skills.

**Comment by BluSunrize** [comment]
Lol.
