### ISSUE TITLE
[0.10.42] Startup crash with tinkers construct

### ISSUE THREAD

**Issue by fehrnah** [BluSunrize/ImmersiveEngineering#1466]
I just upgraded to 0.10.42 on my curse install and the game now crashes at startup.

[http://pastebin.com/WDx6ifGt](http://pastebin.com/WDx6ifGt)

The crash seams to be related to tinkers construct.

**Comment by BluSunrize** [comment]
Yeah. You either need to use IE build 40 or use TCon 2.5.0+
Also, please use the search function next time =)
