### ISSUE TITLE
[1.10.2] non-animated guns & tools

### ISSUE THREAD

**Issue by MrEvilCookie** [BluSunrize/ImmersiveEngineering#1467]
revolver , mining drill , railgun & chemthrower are without animation 
I'm plaing singleplayer , forge, immersive engineering build 41 , with/without OF

**Comment by BluSunrize** [comment]
What do you mean "without animation"? Revolvers and Chemthrowers never had an animation to begin with. And Railgun and Drill didn't have one in 1.8 either. You really need to work on your issuereporting. Please follow the guidelines.
