### ISSUE TITLE
ver 0.10.42 crash

### ISSUE THREAD

**Issue by RobertLSnead** [BluSunrize/ImmersiveEngineering#1468]
Not sure if this is known and being worked on but here is the crash that I received when loading...

**---- Minecraft Crash Report ----

WARNING: coremods are present:
  CXLibraryCore (More-Furnaces_CXLibrary-1.10.2.jar)
  IC2core (industrialcraft-2-2.6.61-ex110.jar)
  CCCDeobfPlugin (unknown)
  NWRTweak (Redstone-Paste-Mod-1.10.2.jar)
  FMLPlugin (Inventory-Tweaks-Mod-1.10.2.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.78-universal.jar)
  TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.5.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.1.8.79-universal.jar)
  NEICorePlugin (NotEnoughItems-1.10.2-2.1.1.147-universal.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.54-beta.jar)
  MalisisCorePlugin (malisiscore-1.9.4-4.1.1.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 9/16/16 2:28 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: slimeknights/tconstruct/tools/TinkerTraits
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:610)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:255)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: slimeknights/tconstruct/tools/TinkerTraits
	at blusunrize.immersiveengineering.common.util.compat.TConstructHelper.preInit(TConstructHelper.java:74)
	at blusunrize.immersiveengineering.common.util.compat.IECompatModule.doModulesPreInit(IECompatModule.java:68)
	at blusunrize.immersiveengineering.ImmersiveEngineering.preInit(ImmersiveEngineering.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:595)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:607)
	... 10 more
Caused by: java.lang.ClassNotFoundException: slimeknights.tconstruct.tools.TinkerTraits
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 39 more
Caused by: java.lang.ArrayIndexOutOfBoundsException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1014823488 bytes (967 MB) / 2098200576 bytes (2001 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.1.2088 Optifine OptiFine_1.10.2_HD_U_C2 90 mods loaded, 90 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCH	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCH	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2088.jar) 
	UCH	Forge{12.18.1.2088} [Minecraft Forge] (forge-1.10.2-12.18.1.2088.jar) 
	UCH	CodeChickenCore{2.1.8.79} [CodeChicken Core] (minecraft.jar) 
	UCH	NotEnoughItems{2.1.1.147} [Not Enough Items] (NotEnoughItems-1.10.2-2.1.1.147-universal.jar) 
	UCH	OpenComputers|Core{1.6.0.3-rc.1} [OpenComputers (Core)] (minecraft.jar) 
	UCH	agriculturalexpansion{r-1.2.0} [Agricultural Expansion] (AgriculturalExpansion[1.9.4][1.10.2]-r1.2.1.jar) 
	UCH	aquaculture{1.4.0} [Aquaculture] (Aquaculture-Mod-1.10.2.jar) 
	UCH	arrowcammod{2.2.0} [Arrow Cam Mod] (ArrowCamMod-1.10.2-2.2.0.jar) 
	UCH	backpack{3.0.1} [Backpack] (backpack-3.0.1-1.10.2.jar) 
	UCH	betterbuilderswands{0.6.5} [Better Builder's Wands] (Better-Builders-Wands-Mod-1.10.2.jar) 
	UCH	Baubles{1.2.1.0} [Baubles] (Botania_Baubles-Mod-1.9.4.jar) 
	UCH	Botania{r1.8-321} [Botania] (Botania-unofficial.r1.8-321.jar) 
	UCH	baublesstuff{2.0.10} [Baubles Stuff] (Botania_baublesstuff-2.0.10.jar) 
	UCH	Chameleon{1.10-2.1.7} [Chameleon] (Chameleon-1.10-2.1.7.jar) 
	UCH	ChestTransporter{2.5.2} [Chest Transporter] (ChestTransporter-1.10.2-2.5.2.jar) 
	UCH	ChickenChunks{2.1.3.36} [ChickenChunks] (ChickenChunks-1.10.2-2.1.3.36-universal.jar) 
	UCH	chisel{MC1.9.4-0.0.6.33} [Chisel] (Chisel-Mod-1.10.2.jar) 
	UCH	chiselsandbits{12.1} [Chisels & Bits] (chiselsandbits-12.1.jar) 
	UCH	cei{1.3} [Chunk Edge Indicator] (Client Only - Chunk-Edge-Indicator-Mod-1.10.2.jar) 
	UCH	llor{1.1.0-mc[1.9-1.10.2]} [Light Level Overlay Reloaded] (Client Only - Light-Level-Overlay-Reloaded-Mod-1.10.2.jar) 
	UCH	IC2{2.6.61-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.61-ex110.jar) 
	UCH	CompactSolars{5.0.4.328} [Compact Solar Arrays] (CompactSolars-Mod-1.10.2.jar) 
	UCH	correlatedpotentialistics{1.1.3} [Correlated Potentialistics] (Correlated-Potentialistics-Mod-1.10.2.jar) 
	UCH	craftingtweaks{6.1.12} [Crafting Tweaks] (CraftingTweaks_1.10.2-6.1.12.jar) 
	UCH	MineTweaker3{3.0.11} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.11.jar) 
	UCH	cyclopscore{0.7.7} [Cyclops Core] (CyclopsCore-1.9.4-0.7.7.jar) 
	UCH	D3Core{1.3.0.59} [DÂ³Core] (D3Core-1.9.4-1.3.0.59.jar) 
	UCH	torohealthmod{1.10.2-1} [ToroHealth Damage Indicators] (damage-indicators-mod-by-torocraft-1.10.2.jar) 
	UCH	easyBreeding{5.0.0} [Easy Breeding] (easybreeding-1.9.4-4.0.1.jar) 
	UCH	Waila{1.7.0} [Waila] (Waila-Mod-1.9.4.jar) 
	UCH	enderrift{1.1.0} [Ender-Rift] (Ender-Rift-Mod-1.10.2.jar) 
	UCH	endercompass{1.2.3.2} [Ender Compass] (EnderCompass-1.9.x-1.2.3.2.jar) 
	UCH	endercore{1.10.2-0.4.1.54-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.54-beta.jar) 
	UCH	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-alpha-1.0.1.jar) 
	UCH	mantle{1.10.2-1.0.0.jenkins170} [Mantle] (Mantle-1.10.2-1.0.0.jar) 
	UCH	tconstruct{1.10.2-2.4.0.jenkins325} [Tinkers' Construct] (TConstruct-1.10.2-2.4.0.jar) 
	UCE	immersiveengineering{0.10-42} [Immersive Engineering] (ImmersiveEngineering-0.10-42.jar) 
	UCH	JEI{3.9.3.252} [Just Enough Items] (jei_1.10.2-3.9.3.252.jar) 
	UCH	EnderIO{1.10.2-3.0.1.107_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.107_beta.jar) 
	UCH	EnderStorage{2.1.3.75} [EnderStorage] (EnderStorage-1.10.2-2.1.3.75-universal.jar) 
	UCH	everlastingabilities{1.1.1} [EverlastingAbilities] (EverlastingAbilities-1.9.4-1.1.1.jar) 
	UCH	ExtraBitManipulation{1.10.2-2.1.0} [Extra Bit Manipulation] (ExtraBitManipulation-1.10.2-2.1.0.jar) 
	UCH	shadowmc{3.4.4} [ShadowMC] (ExtraRails_ShadowMC-1.10.2-3.4.4.jar) 
	UCH	ExtraRails{1.1.1} [Extra Rails] (ExtraRails-1.10.2-1.1.1.jar) 
	UCH	OpenComputers{1.6.0.3-rc.1} [OpenComputers] (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar) 
	UCH	FFS{1.9.4-1.6.4-b28} [Fancy Fluid Storage] (Fancy Fluid Storage-1.9.4-1.6.4-b28.jar) 
	UCH	SonarCore{3.1.4} [SonarCore] (FluxNetworks_SonarCore-1.9.4-3.1.4.jar) 
	UCH	FluxNetworks{1.0.6} [Flux Networks] (FluxNetworks-1.9.4-1.0.6.jar) 
	UCH	fe{1.2.1} [Food Expansion] (FoodExpansion1.2.4-1.10.2.jar) 
	UCH	harvestchevsky{b8} [Gentle Harvest] (Gentle-Harvest-Mod-1.10.2.jar) 
	UCH	fishing{1.4.4} [Fishing Net Mod] (GiacomosFishingNet1.10.2-1.4.4.jar) 
	UCH	hopperducts{1.4.8} [Hopper Ducts] (hopperducts-mc1.9.4-1.4.8.jar) 
	UCH	incense{0.1} [Incense] (Incense.jar) 
	UCH	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (Inventory-Tweaks-Mod-1.10.2.jar) 
	UCH	ironchest{1.10.2-7.0.9.796} [Iron Chest] (ironchest-1.10.2-7.0.9.796.jar) 
	UCH	transprot{1.2.0} [Transprot] (Item-Transportation-Mod-1.10.2.jar) 
	UCH	KeepingInventory{2.1} [Keeping Inventory] (KeepingInventory-1.10.2-2.1.jar) 
	UCH	Lumberjack{1.3.1.39} [Lumberjack] (Lumberjack-1.9.4-1.3.1.39.jar) 
	UCH	malisiscore{1.9.4-4.1.1} [MalisisCore] (malisiscore-1.9.4-4.1.1.jar) 
	UCH	malisisdoors{1.9.4-5.0.4} [MalisisDoors] (malisisdoors-1.9.4-5.0.4.jar) 
	UCH	moarsigns{3.2.0} [MoarSigns] (MoarSigns-Mod-1.9.4.jar) 
	UCH	cxlibrary{1.2.2} [CXLibrary] (More-Furnaces_CXLibrary-1.10.2.jar) 
	UCH	MoreFurnaces{1.8.2} [More Furnaces] (MoreFurnaces-1.10.2-1.8.2.jar) 
	UCH	Morpheus{1.10.2-3.1.7} [Morpheus] (Morpheus-1.10.2-3.1.7.jar) 
	UCH	recipehandler{0.5} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.5(1.10.2).jar) 
	UCH	fodc{1.9.1} [Ore Dictionary Converter] (OreDictionaryConverter-1.9.1.jar) 
	UCH	parachutemod{1.5.2} [Parachute Mod] (Parachute-Mod-1.10.2.jar) 
	UCH	progressiveautomation{@VERSION@} [Progressive Automation] (ProgressiveAutomation-1.10.2-1.6.51-Tweaked.jar) 
	UCH	randomthings{3.7.5} [Random Things] (RandomThings-MC1.10.2-3.7.5.jar) 
	UCH	redstonepaste{1.7.4} [Redstone Paste] (Redstone-Paste-Mod-1.10.2.jar) 
	UCH	routerreborn{1.10.2-4.0.1.20_universal} [Router Reborn] (RouterReborn-1.10.2-4.0.1.20_universal.jar) 
	UCH	Signals{1.0} [Signals] (Signals-1.10.2-0.4.3-universal.jar) 
	UCH	SimilsaxTranstructors{1.10.2.18} [Similsax Transtructors] (Similsax-Transtructors-Mod-1.10.2.jar) 
	UCH	simplebarrels{1.25h} [Simple Barrels] (simplebarrels-1.10.2-2002-1.25h.jar) 
	UCH	SolarFluxReborn{1.3r} [Solar Flux Reborn] (SolarFluxReborn_1.10.2-1.3r.jar) 
	UCH	StorageDrawers{1.10.2-3.2.7} [Storage Drawers] (StorageDrawers-1.10.2-3.2.7.jar) 
	UCH	storagenetwork{1.12.9} [Storage Network] (StorageNetwork-1.9.4-1.12.9.jar) 
	UCH	tesla{1.2.1.49} [TESLA] (Tesla-1.10.2-1.2.1.49.jar) 
	UCH	throwabletorchmod{1.4} [ThrowableTorchMod] (Throwable-Torch-Mod-1.9.4.jar) 
	UCH	thutcore{3.2.3} [ThutCore] (thutcore-1.9.4-3.2.3.jar) 
	UCH	thuttech{3.0.9} [Thut's Tech] (thuttech-3.0.9.jar) 
	UCH	Torcherino{4.2s} [Torcherino] (Torcherino-4.2s.jar) 
	UCH	Translocator{2.1.2.29} [Translocator] (Translocators-1.10.2-2.1.2.29-universal.jar) 
	UCH	va{1.10.2-1.3} [Vanilla Automation] (va-1.10.2-1.3.jar) 
	UCH	vanillamagic{1.10.2-0.16.1.2} [Vanilla Magic] (vanillamagic-1.10.2-0.16.1.2.jar) 
	UCH	WailaHarvestability{1.1.8} [Waila Harvestability] (WailaHarvestability-mc1.10.2-1.1.8.jar) 
	UCH	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.0.203.jar) 
	UCH	wawla{2.3.0.202} [What Are We Looking At] (Wawla-1.10.2-2.3.0.203.jar) 
	UCH	Waypoints{1.9.4-1.2.1} [Waypoints] (Waypoints-Mod-1.9.4.jar) 
	Loaded coremods (and transformers): 
CXLibraryCore (More-Furnaces_CXLibrary-1.10.2.jar)
  cubex2.cxlibrary.CoreModTransformer
IC2core (industrialcraft-2-2.6.61-ex110.jar)
  
CCCDeobfPlugin (unknown)
  
NWRTweak (Redstone-Paste-Mod-1.10.2.jar)
  net.fybertech.nwr.NWRTransformer
FMLPlugin (Inventory-Tweaks-Mod-1.10.2.jar)
  invtweaks.forge.asm.ContainerTransformer
CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.78-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
TransformerLoader (OpenComputers-MC1.10.2-1.6.0.3-rc.1.jar)
  li.cil.oc.common.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.10.2-3.7.5.jar)
  lumien.randomthings.asm.ClassTransformer
CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.1.8.79-universal.jar)
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
NEICorePlugin (NotEnoughItems-1.10.2-2.1.1.147-universal.jar)
  codechicken.nei.asm.NEITransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.54-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
MalisisCorePlugin (malisiscore-1.9.4-4.1.1.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13397 Compatibility Profile Context 15.200.1055.0' Renderer: 'AMD Radeon HD 8610G'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	CodeChickenCore: ignoreInvalidMCVersion state: false
	D3Core: Debug: false Silliness: true AprilFools: true PastPost:false
	EnderIO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker.):
                  * Optifine is installed. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Detailed RF API diagnostics:
                  * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Users/-Robert-/Documents/Curse/Minecraft/Instances/RALS%201.10.2/mods/extrautils2-1.10.2-alpha-1.0.1.jar!/cofh/api/energy/EnergyStorage.class
                  * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Users/-Robert-/Documents/Curse/Minecraft/Instances/RALS%201.10.2/mods/extrautils2-1.10.2-alpha-1.0.1.jar!/cofh/api/energy/IEnergyConnection.class
                  * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Users/-Robert-/Documents/Curse/Minecraft/Instances/RALS%201.10.2/mods/extrautils2-1.10.2-alpha-1.0.1.jar!/cofh/api/energy/IEnergyContainerItem.class
                  * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Users/-Robert-/Documents/Curse/Minecraft/Instances/RALS%201.10.2/mods/extrautils2-1.10.2-alpha-1.0.1.jar!/cofh/api/energy/IEnergyHandler.class
                  * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Users/-Robert-/Documents/Curse/Minecraft/Instances/RALS%201.10.2/mods/extrautils2-1.10.2-alpha-1.0.1.jar!/cofh/api/energy/IEnergyProvider.class
                  * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Users/-Robert-/Documents/Curse/Minecraft/Instances/RALS%201.10.2/mods/extrautils2-1.10.2-alpha-1.0.1.jar!/cofh/api/energy/IEnergyReceiver.class
                  * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Users/-Robert-/Documents/Curse/Minecraft/Instances/RALS%201.10.2/mods/extrautils2-1.10.2-alpha-1.0.1.jar!/cofh/api/energy/IEnergyStorage.class
                  * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Users/-Robert-/Documents/Curse/Minecraft/Instances/RALS%201.10.2/mods/extrautils2-1.10.2-alpha-1.0.1.jar!/cofh/api/energy/ItemEnergyContainer.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/-Robert-/Documents/Curse/Minecraft/Instances/RALS%201.10.2/mods/extrautils2-1.10.2-alpha-1.0.1.jar!/cofh/api/energy/TileEnergyHandler.class
                  * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Users/-Robert-/Documents/Curse/Minecraft/Instances/RALS%201.10.2/mods/extrautils2-1.10.2-alpha-1.0.1.jar!/cofh/api/energy/TileEnergyHandler.class**

**Comment by KindarConrath** [comment]
I have had the same issue, for the time being I was able to fix it by disabling tconstruct compat in the IE configs.

**Comment by BluSunrize** [comment]
Please read the contribution guidelines and spoiler your crashlog.
Either use IE build 40 or upgrade TCon to version 2.5.0+
