### ISSUE TITLE
Uneven splitting conveyor belt distribution

### ISSUE THREAD

**Issue by WolfieWaffle** [BluSunrize/ImmersiveEngineering#1469]
This is a test I did to test the distribution of the splitting conveyor belt. The gray box drops items one at a time. This should have given 16 items to each chest (64 were put in the gray box) but the distributions were as shown in the picture.

I did this test multiple times, with the same result.
![2016-09-16_15 04 26](https://cloud.githubusercontent.com/assets/8770485/18602656/3a3ef78a-7c28-11e6-8951-7bfba234be88.png)

**Comment by BluSunrize** [comment]
It can't split Item entities in half. So if items combine, it won't be able to split them apart again. Nothing I can do about that.

**Comment by WolfieWaffle** [comment]
Will they combine at this proximity? I thought I split them up into single stacks, but that is a possibility. I know that Minefactory reloaded had conveyor belts that didn't allow players to pick them up or combine.

**Comment by BluSunrize** [comment]
My conveyors work differently. Trust me, I tried to fix this for a good 2 hours before I comitted them, to no avail.

**Comment by WolfieWaffle** [comment]
So if two conveyors are too close, they might combine items?

**Comment by BluSunrize** [comment]
yes
