### ISSUE TITLE
[Suggestion] Add an extracting conveyor belt

### ISSUE THREAD

**Issue by JAWSAWN** [BluSunrize/ImmersiveEngineering#147]
When the hoppers are nice, they dont really fit into IE much. We need a special type of conveyor belt that automatically extracts from side of the inventory and connects to conveyor belts.

**Comment by JAWSAWN** [comment]
I have an better idea actually, instead of adding new craftable belt why not upgrade the existing one on the world? Like right clicking a belt with hopper should turn it into export mode, like bc pipes but conveyor belts.

**Comment by BluSunrize** [comment]
I'll take it into consideration
