### ISSUE TITLE
Crash on game init w/ Tinker's Construct running alongside IE.

### ISSUE THREAD

**Issue by Fokson** [BluSunrize/ImmersiveEngineering#1471]
Game crashes on init when both Immersive Engineering and Tinker's Construct are present.  The stacktrace states it's a TC crash, however IE is the one that reports 'errored' on init (and it seems to be stemming from a compatibility method called by IE).  Both mods function fine if the other is taken out.

Crashlog: http://puu.sh/rdL31/5bc9846322.txt

MC: 1.10.2
IE: 0.10-42
TCon: 1.10-2.3.3a
^ Mantle: 1.10.2-1.0.0

Thanks for your time!

**Comment by Joshwoo70** [comment]
"Either use IE build 40 or upgrade TCon to version 2.5.0+" -blusunrize
thanks :)

**Comment by Fokson** [comment]
Wonderful!  Sorry, I must have missed where ever you quoted that from, but thanks for letting me know!
