### ISSUE TITLE
[MC 1.10.2 IE 0.10-42] Shift-clicking Manual into Toolbox spontaneously spawns 64 Manuals

### ISSUE THREAD

**Issue by Terumoc** [BluSunrize/ImmersiveEngineering#1474]
When I try to shift-click to quickly insert the Engineer's Manual into the Engineer's Toolbox, it suddenly explodes into 64 manuals :) Using the slower click-to-pickup-and-drop method it acts normally.

Before shift-clicking:
![image](https://cloud.githubusercontent.com/assets/285093/18606209/83eb29da-7c6e-11e6-8c32-160ff269419e.png)

After shift-clicking:
![image](https://cloud.githubusercontent.com/assets/285093/18606216/9f21f5c6-7c6e-11e6-9c80-5a76cce21151.png)

As in the topic, this is on Minecraft 1.10.2 and the latest version of IE I have found, 0.10-42. Let me know if any other information would be useful.

**Comment by BluSunrize** [comment]
Can't replicate this :/

**Comment by psychofad** [comment]
I have, and its not just manuals, this is a serious dupe glitch as it also works with the bag of holding and other bags or items which do not stack normally.  For me, to get this to work reliably, the last row of the toolbox must have at least 3 different items in it, then I shift click the bag and it fills the remaining slots in the toolbox with copies of the bag and the bag i shift clicked becomes a stack of bags.  All items inside are duplicated and you can unstack the stack of bags to retrieve the items from them as well.

Opposite of this, If I try to shift click a stack of blocks into the Toolbox, it deletes all of them except for 1 which it inserts into the toolbox.

**Comment by Terumoc** [comment]
I just tried some more and indeed, it seems to only happen when there is one or more items already in the slots of the bottom section of the Toolbox. Adding a single water wheel or a windmill seems to be enough to cause shift-clicking a manual to duplicate it.

Other items I've successfully duplicated using the same thing include Angel Rings from ExtraUtils2, Backpacks from Forestry, vanilla Books and Quills, the book Materials and You from Tinker's Construct.

Would a list of mods help if you can't otherwise duplicate it? I'm not sure what else I can do to help.

**Comment by psychofad** [comment]
I could easily provide a list of mods as well if that is helpful!

**Comment by BluSunrize** [comment]
I've found the issue and I believe I fixed it. Next push will include a relevant commit

**Comment by Terumoc** [comment]
Great, glad to hear it!
