### ISSUE TITLE
IM 1.10.2 crash

### ISSUE THREAD

**Issue by Majestyc2k1** [BluSunrize/ImmersiveEngineering#1475]
Got the following crash when I updated my modpack to IM 0.10-41. I got the same crash with 0.10-42 also.

[http://pastebin.com/M56yq6Xf]

**Comment by KnightMiner** [comment]
Duplicate of #1464. Update Tinkers or downgrade Immersive Engineering.

**Comment by BluSunrize** [comment]
Correct. Also, Immersive Engineering is abbreviated to IE, not IM =P
