### ISSUE TITLE
[1.7.10] [MineTweaker] Adding IE Hammer crafting recipes, dupes the hammer

### ISSUE THREAD

**Issue by Robijnvogel** [BluSunrize/ImmersiveEngineering#1478]
Hello,

If I use Minetweaker to add a "IE Hammer + something = IE Hammer(damage + 1) + something else"-recipe and I test the recipe in-game, the recipe will leave the intact hammer in the crafting table and drop a hammer with 1 damage on the ground and Minetweaker tells me that it can not do a damage transformation on an item that has subtypes.

I wonder if you and the guys from Minetweaker can figure out a solution for this.
I will report this on the MineTweaker issue tracker as well.

I have searched for the word "hammer" in your issues and did not find this issue reported there.

**Comment by discodancepant** [comment]
you don't want IE Hammer + something = IE Hammer(damage + 1)
use IE Hammer + something = something else

For example:
recipes.addShaped(<minecraft:chest>, [[<ImmersiveEngineering:tool>, <ore:ingotCopper>]]);
The crafting will leave a hammer in the crafting slot, but with damage. Try a whole stack if you don't believe me.

(This recipe is only an example. Obviously it doesn't really make sense to make a wood chest out of copper)

**Comment by BluSunrize** [comment]
Yep, basically. I already handle damage.

**Comment by Robijnvogel** [comment]
Thank you!
So how do I make a recipe that'd actually consume the hammer?

**Comment by BluSunrize** [comment]
You can't, I'm sorry to say. It only gets consumed when it reaches 100% damage.

**Comment by Voidi** [comment]
Try the noReturn function, at least it work for vanilla buckets. http://minetweaker3.powerofbytes.com/wiki/Tutorial:Advanced_Recipes#Output_reuse_and_transformations

**Comment by Robijnvogel** [comment]
To be clear, I am not planning on making a crafting recipe that actually consumes the whole hammer. I was just trying to point out that the anticipation of certain usage of your Hammer, might have taken away the possibility of certain other "mis"-uses. :)

However, I will try what Voidi intended (I will also try it the intended way though).

**Comment by Robijnvogel** [comment]
I managed to crash my game instance by testing if using `<ImmersiveEngineering:tool>.noReturn().transformDamage()`
would result in a nullpointer exception. (Whispers: It did.)

The other way around it doesn't crash and it consumes both the complete hammer **and** the damaged hammer.

Everything works! Thank you!
