### ISSUE TITLE
[0.10-41]Fluid pump does not pump lava from the nether

### ISSUE THREAD

**Issue by mainframecn** [BluSunrize/ImmersiveEngineering#1479]
The fluid pump will not pump lava in the nether, the same setup will pump water/nether in the overworld.
Removed all mods except IE and JEI. To make sure the setup was alright i did the same setup in mc1.7.10 that worked perfectly.

Setup consists of 3 pipes, creative cap, pump, tank and redstone signal.

**Comment by Joshwoo70** [comment]
cause it is not supposed to i think? you hook it up with pipes.. it cannot pump fluids grom the work AFAIK.

**Comment by malte0811** [comment]
It is supposed to pump from the world. Did you apply a redstone signal to the pump? Is the side of the pump touching the lava set to input?

**Comment by mainframecn** [comment]
Thanks for the replies. I forgot to mention that i did use a redstone signal, otherwise it wouldn't work in the overworld either. Yes it is connected to lava, or again it wouldn't work in the overworld either.

**Comment by BluSunrize** [comment]
I've tried in my dev environment and it works fine. Could you please provide screenshots?

**Comment by BluSunrize** [comment]
Woops, didn't mean to close.

**Comment by mainframecn** [comment]
I've done 2 setups in a test world. Overworld works / nether doesn't, same setup.

![2016-09-17_19 10 04](https://cloud.githubusercontent.com/assets/10155115/18609799/fd1d145c-7d0a-11e6-8f56-f70143e7a767.png)
![2016-09-17_19 13 12](https://cloud.githubusercontent.com/assets/10155115/18609800/fd1ddba8-7d0a-11e6-9f84-22d7f42bf29b.png)
![2016-09-17_19 13 42](https://cloud.githubusercontent.com/assets/10155115/18609801/fd2386a2-7d0a-11e6-955e-c060ec3bc942.png)

**Comment by BluSunrize** [comment]
How long have you left it running before you decided it wasn't working? Because with big fluid sources, it takes a while to add them all to the list of pump-able fluids.

**Comment by BluSunrize** [comment]
Alternatively, try making a small lava pool in the nether and see if it can pump that?

**Comment by mainframecn** [comment]
great idea. I've tried it and let mc run over night, i didn't pump anything.

![2016-09-18_05 01 30](https://cloud.githubusercontent.com/assets/10155115/18612537/28defe0a-7d5d-11e6-8935-63e53a334d8a.png)

**Comment by BluSunrize** [comment]
I dunno what to tell you, it works for me :/

http://puu.sh/rfmVN/9e1b831a8c.jpg

**Comment by mainframecn** [comment]
I understand, thanks very much for taking the time to help. 
Could it be a combination of java (VM) parameters and/or forge? Just now I've a clean install with only JEI and IE, forge v12.18.1.2092. Even removed the custom java vm parameters. 
Difference between the 2 "clean" installs is that the last install i removed all the folders except mods, the other time i removed only the config and other mods. Not sure what the problem is, but it is pretty clear IE is not to blame. 
I will try to narrow it down a bit.

**Comment by malte0811** [comment]
#1569 might be a duplicate of this, can you give me the X/Z coordinates of your pumps as well?
