### ISSUE TITLE
[0.8-32]/[0.10-41] Minor: comment on Core Samples range

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#1480]
core samples seem to be per chunk, but range i.e. from 0, 0 to 16 ,16 with a neighboring sample being from i.e. 0, 16 to 16, 32 -- instead of being from 0, 0 to 15, 15 and the neighboring being 0, 16 to 15, 31

**Comment by BluSunrize** [comment]
from -> to is a "smaller than" system. 0>=i<16
Absolutely intentional^^
