### ISSUE TITLE
[1.10.2] [feature request]

### ISSUE THREAD

**Issue by MrEvilCookie** [BluSunrize/ImmersiveEngineering#1481]
1. Inserter conveyor belts
![default](https://cloud.githubusercontent.com/assets/20132158/18607856/e4fb9ac0-7ce1-11e6-8627-4af0edf794c1.PNG)
 2,terminal (computer) 
![default](https://cloud.githubusercontent.com/assets/20132158/18607910/3d137f74-7ce3-11e6-8052-f4f3ff2d7d11.PNG)
3. cameras
![ewdawdwad](https://cloud.githubusercontent.com/assets/20132158/18607959/66b8e782-7ce4-11e6-813f-746af17f5928.PNG)
4. turrets
![aadwdawdaw](https://cloud.githubusercontent.com/assets/20132158/18607977/0da973ae-7ce5-11e6-9240-48446876a2ce.png)
.5 trashcan with filter
![default](https://cloud.githubusercontent.com/assets/20132158/18608011/e5b9034a-7ce5-11e6-9f60-37aaa5078247.PNG)

**Comment by BluSunrize** [comment]
...right. That's a ... unique drawing.
I'll just do the numbers:
1: No. For one that is an extractor, not an inserter, and I already have something else in mind.
2: No, cba, honestly.
3: No, I can't render that, nor does it fit in IE.
4: Maybe. Turrets have been considered before but it's not an immediate todo.
5: If anything, Incinerator, maybe.
