### ISSUE TITLE
[0.10-42]crash on startup with tinkers construct

### ISSUE THREAD

**Issue by MorgothUK** [BluSunrize/ImmersiveEngineering#1482]
Taking either or of these 2 mods out of the mod pack fixes the issue, both seem fine on their own.

gets mid way through loading to the main menu then CTD, crash log attached

[crash-2016-09-17_17.06.31-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/478258/crash-2016-09-17_17.06.31-client.txt)
[crash-2016-09-17_16.54.17-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/478259/crash-2016-09-17_16.54.17-client.txt)

**Comment by GirafiStudios** [comment]
This have been reported numerous times before. Another time please search on closed issues.
Your solution is to either go back to a earlier version of Immersive Engineering or updating Tinkers Construct to v. 2.5.0 or newer.

**Comment by BluSunrize** [comment]
Yes. That. Use the search function, please.

**Comment by Zorg14** [comment]
Sorry) my bad)
