### ISSUE TITLE
[1.10.2] Metal Press ignoring NBT for press items (Craft Tweaker + Tinkers Construct)

### ISSUE THREAD

**Issue by Kiyaku** [BluSunrize/ImmersiveEngineering#1484]
IE version: 0.10-42
Craft Tweaker: 3.0.11
TConstruct: 2.5.1
Forge: 2089

I'm trying to use the Tinkers Construct presses for making tool parts using craft tweaker. This is the script i use:

`mods.immersiveengineering.MetalPress.addRecipe(<tconstruct:pick_head>.withTag({Material: "iron"}), <minecraft:iron_ingot> * 2, <tconstruct:cast>.withTag({PartType: "tconstruct:pick_head"}), 500);`

But no matter which cast item i use, it will always craft the pick head item, it ignores the PartType tag. 

Let me know if i can provide any other info! 

Thanks,
SC

**Comment by BluSunrize** [comment]
Casts don't allow NBT data, currently.

**Comment by Kiyaku** [comment]
That makes a lot of sense then! 
Are there any plans on allowing casts to have NBT? :) 

Cheers,
SC

**Comment by BluSunrize** [comment]
probably not, because that would mean that casts named in an anvil would no longer work :/
