### ISSUE TITLE
IE closing, but not crashing, the game

### ISSUE THREAD

**Issue by whitestarx0312** [BluSunrize/ImmersiveEngineering#1485]
Forge: forge-12.18.1.2080
IE: ImmersiveEngineering-0.10-42

Issue: Upon loading the game with IE, the game works for several seconds but then closes with the "minecraft has stopped working message." During the few seconds of stability, you can do anything like normal: change settings, create new worlds, or join old ones. However, the game always ends up with the message after a few seconds. There is no crash log generated, but I will link to the full log. Removing IE fixes the issue.

Log: https://www.dropbox.com/s/tscmv9l0pbok4n4/fml-client-latest.log?dl=0

**Comment by theunkn0wn1** [comment]
Can this issue be reproduced without Optifine?

**Comment by whitestarx0312** [comment]
Yep.
https://www.dropbox.com/s/tu9wlpleli3v02n/fml-client-latest.log?dl=0

**Comment by whitestarx0312** [comment]
It started happening even with IE disabled, starting a new instance fixed it.
