### ISSUE TITLE
crusher dupe bug

### ISSUE THREAD

**Issue by bloche14** [BluSunrize/ImmersiveEngineering#1486]
Forge 10.13.4.1614-1.7.10 
IE 0.7.7
Minetweaker
Immersive Integration
Railcraft
Modtweaker
Thermal Foundation
TickDynamic

Playing on SMP server. Someone built a crusher, it got "stuck" while processing ores (taking them in but not outputting dusts anymore). After some experimentation (involving rebuilding the crusher), any crusher on the server now accepts everything but outputs double or more what it should.

This leads to very easy infinite metal by crushing ingots for 2+ dusts.

Not sure if this is solved on   ##post-1.7.10 or what

**Comment by BluSunrize** [comment]
Have you tried restarting the server? That should reset the recipes.

**Comment by bloche14** [comment]
Thanks, I tried restarting the server, which did not fix the problem at first; however, restarting the server after having deconstructed all crushers seemed to have fixed it when rebuilding them after restart; except the same problem repeated itself once soon after, when a crusher became "stuck" again.

I don't know if this can be related but there had been a power outage while the server machine was running, a while before the problems started happening, but the problem happened after multiple server restarts since the power outage.

**Comment by bloche14** [comment]
The server was running tickdynamic - and it turns out disabling it seems to have fixed the problem!

**Comment by BluSunrize** [comment]
Ah! Well good that you figured that out.
