### ISSUE TITLE
IC2 machines use endless energy

### ISSUE THREAD

**Issue by Terpo** [BluSunrize/ImmersiveEngineering#149]
Forge 1448
industrialcraft-2-2.2.739-experimental
ImmersiveEngineering-0.3.3
(full modlist @ http://blog.terpo.org/upload/mc/modlist.txt)

--------------------------------------------------------------------------------

Even if a machine / storage of IC2 has reached the maximum EU storage power, it still drains RF from capacitors.

-----------------------------------------------------------------------------------

http://youtu.be/tv4L4WnT2WI

**Comment by BluSunrize** [comment]
Thanks for the report, will be fixed in future =)
