### ISSUE TITLE
[1.10.2] ImmersiveEngineering not compatibility with thaifixes4.2 and optifine.

### ISSUE THREAD

**Issue by comdarksider** [BluSunrize/ImmersiveEngineering#1492]
ImmersiveEngineering in 1.10.2 vesion 42 latest not compatibility with thaifixes4.2 and optifine.
Link error crash code :  http://pastebin.com/fXAivrb5

another mod download link  :
Thaifixes4.2-1.10.2 -  https://github.com/lion328/ThaiFixes/releases/tag/4.2-1.10.2
OptiFine updated on 25.08.2016 -  http://optifine.net/adloadx?f=OptiFine_1.10.2_HD_U_C3.jar

**Comment by XFactHD** [comment]
The crash is coming from OptiFine.
IE won't ever be compatible with OptiFine as it is a goddamn pain in the backside to make custom rendering stuff compatible with OptiFine.
ThaiFixes is changing MC's FontRenderer meaning that almost any mod that accesses it directly will be incompatible.

**Comment by BluSunrize** [comment]
Optifine is not supported and I already told you so on CurseForge before you filed this issue.
