### ISSUE TITLE
Server crash 1.10.2 - 0.10-42

### ISSUE THREAD

**Issue by TheMrCaveman** [BluSunrize/ImmersiveEngineering#1493]
Server won't boot with ImmersiveEngineering-0.10-42

See crashreport : http://pastebin.com/gPwKkDfk

**Comment by GirafiStudios** [comment]
Duplicate of #1482 and many others. Please use the search function before reporting another time.

**Comment by BluSunrize** [comment]
^ that.
The search function exists, PLEASE make use of it.
