### ISSUE TITLE
[0.10-40] Crusher causing entire server crash

### ISSUE THREAD

**Issue by Urijahuri** [BluSunrize/ImmersiveEngineering#1494]
Had a Crusher built when I upgraded to IE version 0.10-40 on DonutCraft modpack, but now its unusable, as any time I throw anything into it, the server immediately crashes, not sure what the issue is, but I am, simply trying to create Coke dust.

honestly I wouldn't be too worried about this except its the only way to make the HOP graphite to work the Arc furnace, even adding compatibility with the IC2 Macerator would help alleviate this issue.

**Comment by BluSunrize** [comment]
well it would help if you actually provided a crashlog? ^^

**Comment by Urijahuri** [comment]
Sure thing.

http://pastebin.com/dZLwCBzJ

**Comment by BluSunrize** [comment]
Well, first off, you are using build 41, not build 40 as you said, and this issue is fixed by using build 42, which has been released on CurseForge already =)

**Comment by Urijahuri** [comment]
ahh alright, (said 40 in game, might be why)
