### ISSUE TITLE
can't pipe oil out of a coke oven

### ISSUE THREAD

**Issue by peltco** [BluSunrize/ImmersiveEngineering#1495]
I can't seem to be able to pipe oil out of a coke oven. I'm trying to use IE fluid pipes to pipe oil out of a coke oven and either into a tank and/or (wooden) barrel. The pipes connect but no oil is being extracted

IE version 0.10.42

**Comment by BluSunrize** [comment]
please provide pictures of your setup.

**Comment by erindalc** [comment]
Are you using a pump? Did you provide it with a redstone signal? @BluSunrize The Coke oven doesn't auto output does it?

**Comment by peltco** [comment]
![2016-09-20_08 58 56](https://cloud.githubusercontent.com/assets/1384991/18660415/8f424c56-7f10-11e6-80ba-6491c53ec13e.png)

I'm trying to pipe out of the bottom of my coke oven and it goes into the top of my tank

**Comment by BluSunrize** [comment]
Pumps do not draw from a distance. They needed to be connected to the oven directly.

**Comment by peltco** [comment]
that seems to help. After some tweaking i got something working now but it seems that a pump by default only pumps out of the bottom. Maybe it would be nice it could also pump out of the side of a coke oven (and in order to make this placable by default allow all sides to pump in?)

**Comment by Boingboingsplat** [comment]
You can adjust inputs and outputs on the pump with the Engineer's Hammer. This is all detailed in the Engineer's Manual.

**Comment by kane-thornwyrd** [comment]
And you can even shift click hammer on a face to adjust the opposed one !

**Comment by BluSunrize** [comment]
^ what they said =P
