### ISSUE TITLE
[0.10-42] Wawla causes an error when hovering over a metal or wooden barrel

### ISSUE THREAD

**Issue by erindalc** [BluSunrize/ImmersiveEngineering#1497]
Waila-1.7.0-B3_1.9.4.jar
Wawla-1.10.2-2.3.0.206.jar

![2016-09-19_19 17 26](https://cloud.githubusercontent.com/assets/12499779/18652178/513bb310-7e9e-11e6-95a8-4e1e237307dd.png)

**Comment by BluSunrize** [comment]
Can you reproduce this without wawla?

**Comment by erindalc** [comment]
I will try.

**Comment by erindalc** [comment]
![2016-09-20_13 43 00](https://cloud.githubusercontent.com/assets/12499779/18681933/326067ca-7f38-11e6-94d1-09e496c32aa4.png)

With Wawla disabled, it works fine.

**Comment by BluSunrize** [comment]
weeeeeird. I'll look into it, thanks!
