### ISSUE TITLE
[#41] Engineer's Toolbox duplicating and changing items.

### ISSUE THREAD

**Issue by laserlemons** [BluSunrize/ImmersiveEngineering#1498]
When shift-clicking the Engineer's Manual and Engineer's Blueprint into the toolbox it fills every slot of the "anything" section with that item, as well as turning the item you clicked into a stack of 5+. I also noticed that shift-clicking an LV Connector into a toolbox that already had some LV Relays in it turned the connectors into relays and stacked them.

After shift-clicking the manual into the toolbox:
![2016-09-19_00 55 28](https://cloud.githubusercontent.com/assets/6501298/18657517/c76522fe-7eaf-11e6-9300-501ac4fac11e.png)

It may be noteworthy that the modpack I'm playing has Inventory Tweaks in it.

**Comment by BluSunrize** [comment]
Duplicate of #1474, please use the search function next time
