### ISSUE TITLE
(v0.3.3) [Major bug] Revolvers not quite working at all

### ISSUE THREAD

**Issue by JAWSAWN** [BluSunrize/ImmersiveEngineering#150]
Issue with all types of bullets. Revolver shooting is super broken.
Pushes player forward, shows minecart sitting activity, and sometimes noclips player.

**Comment by greg2-1** [comment]
i can attest to this one as well

**Comment by BluSunrize** [comment]
And you're both late to the party.

420a8b43053e67b158944dbd97b5467d87bbb03a

**Comment by JAWSAWN** [comment]
How this even happened? XD

The best bug in the modding history IMO ;P

**Comment by BluSunrize** [comment]
Check the file history. That usually explains how it happened.
