### ISSUE TITLE
Engineer's Toolbox destroys stacks w/shift+click

### ISSUE THREAD

**Issue by VallenFrostweaver** [BluSunrize/ImmersiveEngineering#1501]
When shift+clicking a **stack** of items into the Engineer's Toolbox it will only move 1 into it and reduce the remaining stack to 1 total. Any less than a stack does not reproduce this error.  Picking up the stack and placing into the toolbox works fine

Version 0.10-42.

**Comment by BluSunrize** [comment]
Most likely related to #1498

**Comment by BluSunrize** [comment]
Fixed for future release
