### ISSUE TITLE
[Feature Reuqest] Progression Integration

### ISSUE THREAD

**Issue by majix560** [BluSunrize/ImmersiveEngineering#1502]
I would like to request that you integrate Immersive Engineering for MC 1.10.2 with the [Progression](https://minecraft.curseforge.com/projects/progression/) mod's api to allow pack authors that include both IE and Progression (like me) to directly determine/limit when players can make the various multi-block machines.
I do not see how I can do this, unless I can prevent players from opening the gui.
But that would allow players to make them and still use them by interacting with them in-world outside of their gui.

**Comment by BluSunrize** [comment]
You can add NBT Tags to hammers in order to define whether they can form multiblocks, if that helps?
A  NBTTagList containing strings for the names of the multiblocks, the list is saved with the key "multiblockInterdiction"

But I'll look into direct integration.

**Comment by bookerthegeek** [comment]
That would be pretty cool.

**Comment by BluSunrize** [comment]
Alrighty, I can report back on this.
I have looked into progression and its API system and I have talked to the dev as well.
All in all, I have decided to not integrate with it. The mod currently officially proclaimed dead by the dev, and noone has taken over the project. It most likely won't advanced to future MC versions which makes compat irrelevant in the long run.

However, I will expand the current interdiction system to support an inverted option. Hammers are to be able to have a tag list of multiblocks they are /allowed/ to craft. Definitely not as expansive as Progression, but the best I can do.

**Comment by BluSunrize** [comment]
With that commit, hammers can now have either multiblocks forbidden or allowed with an NBTTagList of strings.
The list with the key "multiblockPermission" is for multiblocks allowed to form and "multiblockInterdiction" for the forbidden ones (name is stupid, I know, but legacy reasons)
The full list of mutliblock names is as follows:

IE:ArcFurnace
IE:Assembler
IE:BlastFurnace
IE:BlastFurnaceAdvanced
IE:BucketWheel
IE:CokeOven
IE:Crusher
IE:DieselGenerator
IE:Excavator
IE:Fermenter
IE:MetalPress
IE:Refinery
IE:SheetmetalTank
IE:Silo
IE:Squeezer
