### ISSUE TITLE
Crashes Minecraft

### ISSUE THREAD

**Issue by Luckie21** [BluSunrize/ImmersiveEngineering#1504]
[crash-2016-09-21_20.01.24-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/486361/crash-2016-09-21_20.01.24-client.txt)
It crashes my game every time I try to place a block but i can do everything else fine  without it crashing. Please Help

**Comment by BluSunrize** [comment]
Could you please provide more information? What mods are you using, are you using a specific launcher, etc?

**Comment by Luckie21** [comment]
Updating forge fixed it thanks malte0811
