### ISSUE TITLE
Item Duplication with the toolbox

### ISSUE THREAD

**Issue by ProsperCraft** [BluSunrize/ImmersiveEngineering#1505]
Still working on the player to get the exact details, he sent me this screenshot.

![2016-09-21_22 47 51](https://cloud.githubusercontent.com/assets/4427684/18793252/1af65d38-8177-11e6-9bfc-f98184954953.png)

I will see if I can get with him and shoot a video for you on it.

**Comment by BluSunrize** [comment]
Known issue, see #1498
Please consider using hte search function next time =)
