### ISSUE TITLE
(Suggestion) Lantern Upgrade

### ISSUE THREAD

**Issue by porteriscool** [BluSunrize/ImmersiveEngineering#151]
If you possibly want a new suggestion, what you could do is create an upgraded version of the lantern which takes power and has a larger radius of light source. More importantly, when these lanterns have power and a redstone signal, they are on, when they dont have power however, they are off. You can add onto this however you see fit, its just a suggestion though. Have fun with this idea blu.

**Comment by BluSunrize** [comment]
"larger radius" isn't that easy without fake light blocks
