### ISSUE TITLE
[0.10-42] Power randomly stops flowing - Requires SMP server restart

### ISSUE THREAD

**Issue by bryanspears** [BluSunrize/ImmersiveEngineering#1511]
I'm having a difficult time isolating the cause, but even when all we (4-man multiplayer game) had was a triple water wheel and two windmills powering a crusher and an external heater there would be times we'd log in and the power system was locked up. No power movement either through specific connections or capacitors. Machines seemed to use their internal buffers just fine, but wires seemed busted. A server restart was required to get things working again.

There weren't any obvious exceptions in server or client logs. Here's all I got from the server after logging in.

> [01:03:23] [Netty Epoll Server IO #1/INFO] [FML]: Client protocol version 2
> [01:03:23] [Netty Epoll Server IO #1/INFO] [FML]: Client attempting to join with 74 mods : ChestTransporter@2.5.2,blockdrops@1.0.11,Waila@1.7.0,tesla@1.2.1.49,trashslot@6.3.6,rftools@5.24,deathcounter@1.1.0,platforms@1.2.0,ftbu@2.1.0,dra
> conicevolution@2.0.0,justenoughbuttons@1.10.2-1.6.2,bdlib@1.12.2.12,wawla@2.3.0.202,SilentLib@1.0.12,mcp@9.19,reborncore@2.7.2.45,jeibees@0.9.0.2,cookingforblockheads@4.2.15,journeymap@1.10.2-5.2.4,inventorytweaks@1.61-58-a1fd884,OpenCom
> puters@1.6.0.3-rc.1,ftbl@2.1.0,Morpheus@1.10.2-3.1.7,SuperMultiDrills@1.4.1,waterstrainer@1.3.0,jeresources@0.5.1.56,progressiveautomation@1.6.51,mcmultipart@1.2.1,fluxedredstone@2.4.1.50,hammerz@1.10-0.0.0.3,shetiphiancore@3.3.1,brandon
> score@2.1.0,refinedstorage@1.0.5,ironchest@1.10.2-7.0.11.797,WorldEditCuiFe@1.0.2,InfernalMobs@1.7.1,ToughAsNails@1.0.11,RTG@1.10.2,immersiveengineering@0.10-42,Forge@12.18.1.2093,Roguelike@1.5.4,valkyrielib@1.10.2-0.10.4,chameleoncreepe
> rs@1.4.1,Chameleon@1.10-2.1.7,SonarCore@3.1.6,easyBreeding@5.0.0,StorageDrawers@1.10.2-3.2.7,gendustry@1.6.4.21,EnderBags@2.0.1,SpiceOfLife@1.3.6,gearswap@1.2.6,OpenComputers|Core@1.6.0.3-rc.1,ElecCore@1.5.311,gravestone@1.5.6,icse@1.1.0
> .0,advgenerators@0.9.20.14,AppleCore@2.0.1,deepresonance@1.2.4,FastLeaveDecay@1.1,recallstones@0.6.3,nethermetals@1.1.2,FML@8.0.99.99,rftoolsdim@4.30beta50,reborncore-mcmultipart@2.7.2.45,worldedit@6.1.4,SolarFluxReborn@1.4r,IGWMod@1.3.0
> -5,environmentaltech@1.10.2-0.10.4b,JEI@3.10.0.261,FloodLights@1.2.7-145,WailaHarvestability@1.1.9,FluxNetworks@1.0.7,forestry@5.2.12.258,morebees@1.10.2-1.1.3
> [01:03:23] [Netty Epoll Server IO #1/INFO] [journeymap]: CLIENT
> [01:03:23] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
> [01:03:23] [Server thread/INFO] [mcjty.lib.varia.Logging]: SMP: Sync dimensions to client
> [01:03:23] [Server thread/INFO]: OldCrazyMonkey[/192.168.1.157:48664] logged in with entity id 60 at (-2881.3977326810764, 148.0, 1119.604272977464)
> [01:03:23] [Server thread/INFO]: OldCrazyMonkey joined the game
> [01:03:23] [Server thread/INFO] [Waila]: Player EntityPlayerMP['OldCrazyMonkey'/60, l='world', x=-2881.40, y=148.00, z=1119.60] connected. Sending ping
> [01:03:23] [Server thread/INFO] [mcjty.lib.varia.Logging]: SMP: Player logged in: Sync diminfo to clients
> [01:03:23] [Server thread/INFO] [mcjty.lib.varia.Logging]: Sync dimension info to clients!
> [01:03:23] [ForkJoinPool-1-worker-11/INFO] [OpenComputers]: Starting OpenComputers version check.
> [01:03:23] [Server thread/INFO] [mcjty.lib.varia.Logging]: Send dimlet rules to the client
> [01:03:23] [Server thread/INFO] [mcjty.lib.varia.Logging]: Rules packet size: 5598 of 8192
> [01:03:23] [Server thread/INFO] [STDOUT]: [mcjty.lib.preferences.PreferencesProperties:syncToClient:31]: syncToClient: style = STYLE_FLAT_GRADIENT
> [01:03:24] [ForkJoinPool-1-worker-11/INFO] [OpenComputers]: Running the latest OpenComputers version.
> [01:03:28] [Netty Epoll Server IO #1/WARN] [Waila]: elec332.core.compat.handlers.WailaCompatHandler$CapabilityProvider.getNBTData:107
> [01:03:28] [Netty Epoll Server IO #1/WARN] [Waila]: mcp.mobius.waila.network.Message0x01TERequest.channelRead0:133
> [01:03:28] [Netty Epoll Server IO #1/WARN] [Waila]: Catched unhandled exception : [class blusunrize.immersiveengineering.common.blocks.metal.TileEntityConnectorHV] java.lang.NullPointerException
> [01:06:22] [Netty Epoll Server IO #1/WARN] [Waila]: elec332.core.compat.handlers.WailaCompatHandler$CapabilityProvider.getNBTData:107
> [01:06:22] [Netty Epoll Server IO #1/WARN] [Waila]: mcp.mobius.waila.network.Message0x01TERequest.channelRead0:133
> [01:06:22] [Netty Epoll Server IO #1/WARN] [Waila]: Catched unhandled exception : [class blusunrize.immersiveengineering.common.blocks.metal.TileEntityConnectorLV] java.lang.NullPointerException
> [01:06:25] [Netty Epoll Server IO #1/WARN] [Waila]: elec332.core.compat.handlers.WailaCompatHandler$CapabilityProvider.getNBTData:107
> [01:06:25] [Netty Epoll Server IO #1/WARN] [Waila]: mcp.mobius.waila.network.Message0x01TERequest.channelRead0:133
> [01:06:25] [Netty Epoll Server IO #1/WARN] [Waila]: Catched unhandled exception : [class blusunrize.immersiveengineering.common.blocks.metal.TileEntityDynamo] java.lang.NullPointerException
> [01:06:43] [Netty Epoll Server IO #1/WARN] [Waila]: elec332.core.compat.handlers.WailaCompatHandler$CapabilityProvider.getNBTData:107
> [01:06:43] [Netty Epoll Server IO #1/WARN] [Waila]: mcp.mobius.waila.network.Message0x01TERequest.channelRead0:133
> [01:06:43] [Netty Epoll Server IO #1/WARN] [Waila]: Catched unhandled exception : [class blusunrize.immersiveengineering.common.blocks.metal.TileEntityCapacitorHV] java.lang.NullPointerException
> [01:09:42] [Netty Epoll Server IO #1/WARN] [Waila]: elec332.core.compat.handlers.WailaCompatHandler$CapabilityProvider.getNBTData:107
> [01:09:42] [Netty Epoll Server IO #1/WARN] [Waila]: mcp.mobius.waila.network.Message0x01TERequest.channelRead0:133
> [01:09:42] [Netty Epoll Server IO #1/WARN] [Waila]: Catched unhandled exception : [class blusunrize.immersiveengineering.common.blocks.metal.TileEntityCapacitorLV] java.lang.NullPointerException
> [01:09:44] [Netty Epoll Server IO #1/WARN] [Waila]: elec332.core.compat.handlers.WailaCompatHandler$CapabilityProvider.getNBTData:107
> [01:09:44] [Netty Epoll Server IO #1/WARN] [Waila]: mcp.mobius.waila.network.Message0x01TERequest.channelRead0:133
> [01:09:44] [Netty Epoll Server IO #1/WARN] [Waila]: Catched unhandled exception : [class blusunrize.immersiveengineering.common.blocks.wooden.TileEntityWoodenPost] java.lang.NullPointerException
> [01:24:58] [Netty Epoll Server IO #1/WARN] [Waila]: elec332.core.compat.handlers.WailaCompatHandler$CapabilityProvider.getNBTData:107
> [01:24:58] [Netty Epoll Server IO #1/WARN] [Waila]: mcp.mobius.waila.network.Message0x01TERequest.channelRead0:133
> [01:24:58] [Netty Epoll Server IO #1/WARN] [Waila]: Catched unhandled exception : [class blusunrize.immersiveengineering.common.blocks.stone.TileEntityBlastFurnace] java.lang.NullPointerException
> [01:24:59] [Server thread/INFO]: OldCrazyMonkey lost connection: TextComponent{text='Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEve
> nt=null, insertion=null}}
> [01:24:59] [Server thread/INFO]: OldCrazyMonkey left the game
> [01:30:55] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 3006ms behind, skipping 60 tick(s)

Later when a friend joined. The server started spewing messages like this

> [07:02:31] [Server thread/WARN]: Fetching addPacket for removed entity
> [07:03:03] [Server thread/WARN]: Fetching addPacket for removed entity
> [07:03:17] [Server thread/WARN]: Fetching addPacket for removed entity
> [07:03:19] [Server thread/WARN]: Fetching addPacket for removed entity
> [07:03:19] [Server thread/WARN]: Fetching addPacket for removed entity
> [07:03:23] [Netty Epoll Server IO #4/WARN] [Waila]: elec332.core.compat.handlers.WailaCompatHandler$CapabilityProvider.getNBTData:107
> [07:03:23] [Netty Epoll Server IO #4/WARN] [Waila]: mcp.mobius.waila.network.Message0x01TERequest.channelRead0:133
> [07:03:23] [Netty Epoll Server IO #4/WARN] [Waila]: Catched unhandled exception : [class blusunrize.immersiveengineering.common.blocks.wooden.TileEntityWoodenCrate] java.lang.NullPointerException
> [07:03:27] [Server thread/WARN]: Fetching addPacket for removed entity
> [07:03:28] [Server thread/WARN]: Fetching addPacket for removed entity
> [07:03:33] [Server thread/WARN]: Fetching addPacket for removed entity
> [07:03:33] [Server thread/WARN]: Fetching addPacket for removed entity
> [07:03:34] [Server thread/WARN]: Fetching addPacket for removed entity
> [07:03:34] [Server thread/WARN]: Fetching addPacket for removed entity
> [07:03:34] [Server thread/WARN]: Fetching addPacket for removed entity
> [07:03:50] [Server thread/WARN]: Fetching addPacket for removed entity
> [07:03:50] [Server thread/WARN]: Fetching addPacket for removed entity
> [07:03:51] [Server thread/WARN]: Fetching addPacket for removed entity
> [07:03:51] [Server thread/WARN]: Fetching addPacket for removed entity
> [07:03:53] [Server thread/WARN]: Fetching addPacket for removed entity
> [07:03:53] [Server thread/WARN]: Fetching addPacket for removed entity
> [07:05:04] [Server thread/WARN]: Fetching addPacket for removed entity
> [07:05:04] [Server thread/WARN]: Fetching addPacket for removed entity
> [07:05:07] [Server thread/WARN]: Fetching addPacket for removed entity
> [07:05:07] [Server thread/WARN]: Fetching addPacket for removed entity
> [07:05:14] [Server thread/WARN]: Fetching addPacket for removed entity
> [07:05:41] [Server thread/WARN]: Fetching addPacket for removed entity
> [07:05:47] [Server thread/WARN]: Fetching addPacket for removed entity
> [07:07:47] [Server thread/WARN]: Fetching addPacket for removed entity
> [07:07:48] [Server thread/WARN]: Fetching addPacket for removed entity
> [07:07:54] [Server thread/WARN]: Fetching addPacket for removed entity
> [07:07:59] [Server thread/WARN]: Fetching addPacket for removed entity

Those will continue spamming the log until all players log off and I restart the server.

I know it's not much to go on, but this basically prevents play unless I restart the server every time someone wants to play. :frowning: 

Thanks for the mod! It's been fun so far!

**Comment by malte0811** [comment]
Is this happening on a normal forge server or on something like Cauldron?

**Comment by bryanspears** [comment]
Forge plus the mods listed in the first block.

**Comment by mindforger** [comment]
this sounds like an corrupted TE data or IE trying to associate client data to a block not beeing an TE anymore.

there is an option to remove erroring TEs in forge, maybe that one helps, but disable it once you are having no errors anymore!

**Comment by bryanspears** [comment]
Waila causing errors when looking at an IE entity could cause all kinds of stuff to be removed from the above log. And it's not isolated. This is a broad issue. Most, if not all, of the IE infrastructure we've placed has been broken and replaced since we've had this issue.

**Comment by malte0811** [comment]
The exception is thrown [here](https://github.com/Elecs-Mods/ElecCore/blob/master/src/main/java/elec332/core/compat/handlers/WailaCompatHandler.java#L107). I copied the raytrace method called in that line to my dev environment, it returns `null` when you are passing the border of a block (so just as the block moves into focus). I am not sure why this is happening, but I suspect that WAILA is using a different raytrace algorithm that triggers in some corner cases where the vanilla one does not.
@elec332 it would be nice if you could add a null-check for the return value of that raytrace. The overriding raytrace methods in IE forward to the default one in at least some of the cases where this is happening and the bounding box values are correct.

**Comment by bryanspears** [comment]
Could this cause the electrical grid freezing we're experiencing?

I appreciate the crazy fast debugging going on here. :smile:

**Comment by malte0811** [comment]
No idea as of right now. I don't know what those errors are doing to the TileEntities, if they are completely removing the TE, it would make sense.
I haven't yet managed to replicate the energy net freezing, you could try temporarily removing WAILA or, if possible, disabling ElecCore's WAILA integration and see whether the problem goes away.

**Comment by bryanspears** [comment]
I'd guess they're not removing the entities as a server restart fixes all the things. Grid power starts flowing again, etc.

I'm 99% sure it's SMP only and requires more than one unique player logging in and out of the server. A sync issue. Only happens after multiple players have been online, then everyone leaves, and eventually someone logs back in to find some or all of the grid frozen.

**Comment by bryanspears** [comment]
Disabled all Waila mods last night. Things worked fine, but they always do after a server restart.

Logged in this morning and the entire grid is frozen. The crusher won't even turn on when ore is thrown in. However, it does accept it and queue it. Just won't run and process the ore until I restart the server.

**Comment by Elec332** [comment]
Oh, great.
I fixed it in my dev-env, but im currently rewriting the compat handler system, so I cannot publish it yet.
