### ISSUE TITLE
[Suggestion] Fluid Pipes with "windows"

### ISSUE THREAD

**Issue by ToadsworthLP** [BluSunrize/ImmersiveEngineering#1512]
If you have lots of fluid pipes, it's sometimes hard to see which one transports which fluid, so it would be nice to have a window to see what's flowing through. Something like a "Window Fluid Pipe", which is created by right-clicking a fluid pipe with a glass pane. This _may be_ very hard to implement, but it would look great!

**Comment by BluSunrize** [comment]
Except that nothing flows "through" them. Pipes transfer instantly. They don't store fluid.

**Comment by ToadsworthLP** [comment]
Never noticed that! Looks like I was just EXPECTING that it flows, because of literally every other mod that adds fluid transport!

**Comment by mindforger** [comment]
enderio ender fluid conduits do the same ... the other pipes are for "tier"ing the type of ducts ... also it costs way more rendering performance to have such fancy animations :)
