### ISSUE TITLE
Crates lose contents when broken with Psi

### ISSUE THREAD

**Issue by dannydjdk** [BluSunrize/ImmersiveEngineering#1513]
When broken with the Psi "break block" spell, storage crates lose all their contents. When broken with an axe, they retain inventory as expected.
I haven't seen this problem when breaking blocks with NBT or meta data from other mods which is why I'm reporting this here.

Forge 12.18.1.2092
Immersive Engineering 0.10-42
Psi 1.0-39

**Comment by ArukaAlter** [comment]
Break Block spells also wipes out banner data, it's a issue on Psi, I've reported it over to Vazkii with no response yet.
