### ISSUE TITLE
[suggestion] aluminum,treatedwood and steel fencegates

### ISSUE THREAD

**Issue by ilordnightmarei** [BluSunrize/ImmersiveEngineering#1515]
ti wold be nice to have matching fence gates fore these fences cause why not and it feels odd that theirs fences for them and no fence gates.

**Comment by calloatti** [comment]
Use the EnderIO painting machine and paint a standard gate with a steel or treated wood fence and you will have you steel/treated wood gates:

http://i.imgur.com/p8EFhk3.png

**Comment by ilordnightmarei** [comment]
oh well then i didnt think of that

**Comment by calloatti** [comment]
EnderIO is available for 1.10.2. I use it in 1.10.2

"For 1.8/1.9/1.10 versions go to the project site, then select 'Files' from the menu."

https://mods.curse.com/mc-mods/minecraft/ender-io#t1:other-downloads
