### ISSUE TITLE
[0.10-42] Conveyor belts cause "Player moved wrongly!" errors when ridden upon

### ISSUE THREAD

**Issue by bryanspears** [BluSunrize/ImmersiveEngineering#1516]
I haven't narrowed down the circumstances, but we had the following occur:
- Player "hitting head" on a block while riding conveyor belt (you're stuck and it jitters visually)
- Pressing shift then jumping to get "unstuck" off a belt (this is only when stuck, I know you can get off a belt normally very easily)

A friend of mine has also reported getting stuck on a belt and having to break the belt to get free of it, but I haven't been able to reproduce.

**Comment by kane-thornwyrd** [comment]
Can you specify in which versions your are playing ? a forced crash log could be an answer.
