### ISSUE TITLE
[0.10-42] Conveyor belts visually glitch to another configuration

### ISSUE THREAD

**Issue by bryanspears** [BluSunrize/ImmersiveEngineering#1517]
Typically it was always showing a flat belt, then suddenly for a few (5-15 or so) ticks (felt like less than a second) you'd see it visually glitch to an upward diagonal belt in the same direction. Then quickly revert back.

This did not appear to impact item movement at all.

**Comment by kane-thornwyrd** [comment]
I have just to request:
* Can you join a force crash log ? (you know, because knowing the env in which you play is useful to debug)
* Can you make a video of the glitch ? (It's optional, but could greatly help)
