### ISSUE TITLE
Some weird rendering

### ISSUE THREAD

**Issue by bakaxyf** [BluSunrize/ImmersiveEngineering#152]
- [gif](https://drive.google.com/file/d/0B7-sQxp-PWE3RTRrTlozTk9vdk0/view?usp=sharing)

- ![8qm_vi _r 0 j 18uo dr](https://cloud.githubusercontent.com/assets/10368307/8430114/9bfc6dde-1f60-11e5-9a63-f67d594108e0.jpg)

**Comment by wafflemans** [comment]
So let me get this straight: The structural arm's slope goes up at the start of a new chunk?

**Comment by BluSunrize** [comment]
You're also no supposed to extent the thign infinetly. It's got a max reach of 8.
