### ISSUE TITLE
.42 Assembler unable to craft concrete

### ISSUE THREAD

**Issue by kinnon21** [BluSunrize/ImmersiveEngineering#1521]
I have an assembler set up in my world filled with water and creosote oil. I feed it slag, clay and gravel and it's unable to craft. I have tried the sand recipe for concrete as well and it's unsuccessful. It does make treated wood planks though.

**Comment by BluSunrize** [comment]
Fixed with this commit:
https://github.com/BluSunrize/ImmersiveEngineering/commit/898c6365551916b6201fafd7d87190e906618e0c
I accidentally tagged the wrong issue in it.
