### ISSUE TITLE
Excavator Wheel renders sideways

### ISSUE THREAD

**Issue by calloatti** [BluSunrize/ImmersiveEngineering#1522]
Version: Built from source 2016-09-30

http://i.imgur.com/gsrMpJ8.png

Full log: http://pastebin.com/b1bU6ezr

**Comment by BluSunrize** [comment]
*blames @malte0811 and his beautiful performance improvements*

I'll fix it in a moment.

**Comment by calloatti** [comment]
I thought so.. If I recall correctly this was an old fixed bug.

**Comment by BluSunrize** [comment]
How to debug all possible permutations:
http://puu.sh/rsUCQ/80ba651f77.jpg

Might be tanking framerate a little. 
Found the fix tho. Commit follows in a few minutes

**Comment by malte0811** [comment]
Um, what were you doing when you took that screenshot? I get 25-30 FPS with 11 bucket wheels and a couple of waterwheels (after fixing the rotation) and I am pretty sure your computer is better than mine, so it seems weird that you are getting 10 FPS with 8 bucket wheels.
Btw, you haven't fixed the normal windmill's model yet, it is facing in a different direction than the improved one.

**Comment by BluSunrize** [comment]
I have not changed any render based code, I solely changed the rotation calls.
