### ISSUE TITLE
Unable to use Lead on Treated Wood Fence

### ISSUE THREAD

**Issue by calloatti** [BluSunrize/ImmersiveEngineering#1523]
Version: built from source 2016/09/30

Right click on a treated wood fence with a Lead does nothing.

Expected: Lead should tie itself to treated wood fence like other fences.

http://i.imgur.com/xW6CCCT.png

Full log: http://pastebin.com/b1bU6ezr

**Comment by kane-thornwyrd** [comment]
If memory serve Fences and Slabs from IE are not typical blocks but Tile Entities, I'm interested in the answer you'll get :)

**Comment by VT-14** [comment]
Mod fences usually don't work with leads, and I think its an issue with vanilla Minecraft itself.

I heard that from some other 1.7.10 mod at some point; before Minecraft added 5 new types of fences.  Maybe it has changed.

**Comment by BluSunrize** [comment]
Vanilla leads are hardcoded to only work with instances of BlockFence. While I cannot make my fences an instance of those, I /can/ make a custom handling that still allows attachment.
I will see to this, it's actually a cool idea =3

**Comment by BluSunrize** [comment]
Well after investigating this a bit, turns out, Minecraft isn't too cool with things extending it's leashes. I can't easily do this on IE's side, sadly, but I'll look into maybe getting a PR into Forge that allows custom blocks to hold leashes.

**Comment by calloatti** [comment]
Not a big deal, I thought it was just a one liner change. Will pay more attention next time before going out on an expedition and get a vanilla fence.
