### ISSUE TITLE
Electrician villager giving negative quantity of wires

### ISSUE THREAD

**Issue by LemADEC** [BluSunrize/ImmersiveEngineering#1526]
As of ImmersiveEngineering-0.10-42 with forge1.10.2-12.18.1.2094
![image](https://cloud.githubusercontent.com/assets/4776032/19010596/3daabbbe-8783-11e6-83de-35198e17285c.png)

**Comment by GirafiStudios** [comment]
Duplicate of https://github.com/BluSunrize/ImmersiveEngineering/issues/1470 and have already been fixed :)
