### ISSUE TITLE
[0.10.42] Suggestion: Enable the Metal Press to accept items from the lower left side.

### ISSUE THREAD

**Issue by calloatti** [BluSunrize/ImmersiveEngineering#1527]
Right now, to send items to the metal press, you have to do it from the left side second row block like for example using an item buffer from EnderIO pushing items (but it could be a vanilla hopper):

http://i.imgur.com/YQhU74A.png

It would be great if the metal press would also accept items from the lower left block, like this:

http://i.imgur.com/WZRTpqz.png

The change suggested enables to do more aesthetic pleasing setups.

**Comment by BluSunrize** [comment]
That makes zero sense though.
The whole point is that items run along the conveyor, so inserting into the block below doesn't really fit.

Also, you can just make the buffer push upwards and put a conveyor on, if it bothers you that much .-.

**Comment by calloatti** [comment]
Yes, I know it does not make sense, but it doesn't hurt anyway.

And yes, I can push up to a conveyor on top, but then the items pile up in mid air, instead of being pushed one by one.

Anyway, it's not life or death, but it would be nice to have.

Right now I just put two item buffers one on top of the other and the bottom one pushes to the top one, and that one pushes to the side.

**Comment by BluSunrize** [comment]
Yeah no, sorry, not gonna make that change. There is little point to it and it flat out doesn't fit the aesthetics of the machine
