### ISSUE TITLE
Zetta industries Big Batteries compatibility

### ISSUE THREAD

**Issue by demethan** [BluSunrize/ImmersiveEngineering#1528]
IE will output to the battery but the batter won't output to a IE connector unless there is an RF device from  other mods in between. Exempl BB>RFTools Cell>IE connector.

Not sure if its Zetta or IE.  Will post in both. 

many thanks. 

Ref: https://github.com/marcin212/Zetta-Industries/issues/47

**Comment by BluSunrize** [comment]
If their battery is not outputting power to my connectors, that almost sounds like it's on their side.
Would be great if you specified versions btw.

**Comment by marcin212** [comment]
fixed

**Comment by demethan** [comment]
confirmed fixed
