### ISSUE TITLE
blusunrize.immersiveengineering.client.models.ModelCoresample:func_188616_a:141]: java.lang.IllegalStateException: not enough data

### ISSUE THREAD

**Issue by vlce-versa** [BluSunrize/ImmersiveEngineering#1529]
Getting this error when getting a core sample from the drill, and it's invisible in my inventory

Error:
http://pastebin.com/HFi1j7Z2

Screenshot:
https://postimg.org/image/h52lb4zkb/

Mods:
http://pastebin.com/epiukrtq

**Comment by BluSunrize** [comment]
Please submit errors using pastebin or gist so we are not presented with a wall of text.

Also, could you please provide a modlist and tell us what mineral the sample contains?
Please read the contibution guidelines next time.

**Comment by vlce-versa** [comment]
Updated my Report

**Comment by BluSunrize** [comment]
Can you replicate the issue without a resource pack?

**Comment by vlce-versa** [comment]
Yes, same issue with vanilla textures.

**Comment by malte0811** [comment]
Optifine is not supported, as it says in the contributing guidelines.

**Comment by vlce-versa** [comment]
So I can either have a smooth Minecraft experience or Immersive Engineering, I think my choices are clear then ;) thanks anyway
