### ISSUE TITLE
Cannot seem to plant industrial Hemp seeds

### ISSUE THREAD

**Issue by cyhim** [BluSunrize/ImmersiveEngineering#153]
I cannot seem to plan Industrial hemp seeds. Or did I miss something?

**Comment by BluSunrize** [comment]
Are you using Agricraft and do you have it configured to disable vanilla farming?

**Comment by cyhim** [comment]
Yes,  the server is set up that way.  




Sent from my Verizon Wireless 4G LTE smartphone


-------- Original message --------

**Comment by BluSunrize** [comment]
There's your problem. But the latest Agricraft has a hemp crop, so there's your answer too.
