### ISSUE TITLE
[Suggestion] Point to point wired power transportation over unloaded chunks

### ISSUE THREAD

**Issue by wormzjl** [BluSunrize/ImmersiveEngineering#1531]
As the title suggests
This would allow some interesting builds with IE, such as sever-wide power network and remote installations without the use of energy-teleporters
A good reference is chromaticraft's lumen transportation system

The system in IE could be as following:
Need specialized equipment (extreme voltage transformer + large steel electric pole)
Power transfer is point to point, build substations if needs to be divided
Reasonable power loss, for transportation over vast distances 

I've seen an indev mod which made this possible before, but was never published.
This will make things many people have dreamed of become possible

**Comment by malte0811** [comment]
Unless Blu removed that when porting to 1.10, IE wires should be capable of transfering energy through unloaded chunks as long as both ends of the connection are loaded. It might be a good idea to put this into the manual, I forgot to add the note when I ported the change to 1.8.

**Comment by wormzjl** [comment]
How was the power loss then?
I mean I want to use it to transport power over 1000+ blocks

**Comment by malte0811** [comment]
Power loss is just as it would be if the chunks were loaded (so you might need to either reduce loss in the config or make an addon adding extra long range wire) and it should work on 1.7 if you are using a recent version (I believe I added this in 0.7.5, but you should use 0.7.7).

**Comment by wormzjl** [comment]
Oh this is really cool
Thank you!
