### ISSUE TITLE
[1.10.2][0.10-42] Tesselating block in world

### ISSUE THREAD

**Issue by Alaberti** [BluSunrize/ImmersiveEngineering#1532]
http://pastebin.com/r0btev17

Client crash for a player on my server near an Excavator. Only happened once so couldn't perform a test without optifine.

IE 0.42
MC 1.10.2
Optifine U C3

**Comment by Joshwoo70** [comment]
optifine not supported ;)

**Comment by malte0811** [comment]
This one is actually not caused by Optifine, it is a race condition between the rendering thread and the network thread, I will fix it right now.

**Comment by Alaberti** [comment]
Awesome, thanks!
