### ISSUE TITLE
[1.8.9] Crusher recipes ignore secondary output chance

### ISSUE THREAD

**Issue by WTFNoNamesLeftoO** [BluSunrize/ImmersiveEngineering#1534]
All crusher recipes from IE as well as costum ones ignore the secondary output's chance. At first I thought it was my fault because my costum recipes weren't working as intented, but after further investigation I realized that the fault must lie within IE itself. Crushing anything with a secondary output will yield the second item 100% of the time (although the source code states chances of 10% or less). Proof: Throw iron ore into the crusher; it will create 1 nickel grit everytime.
(Tested with IE 0.8-32 /  forge-11.15.1.1902)

**Comment by ArukaAlter** [comment]
Recently fixed in 1.10

**Comment by WTFNoNamesLeftoO** [comment]
Good to hear. I still would love to see this bug getting fixed for 1.8.9 though.

**Comment by GirafiStudios** [comment]
1.8.9 is no longer being developed I think :)

**Comment by BluSunrize** [comment]
Correct. 1.8 is not planned for any releases in the near future.

**Comment by WTFNoNamesLeftoO** [comment]
Alright, thanks for the clarification.
