### ISSUE TITLE
[1.10.2][0.10-42] Diesel Generator fuel inputs missing blue dot.

### ISSUE THREAD

**Issue by calloatti** [BluSunrize/ImmersiveEngineering#1536]
The two fuel inputs in the Diesel Generator should have a blue dot to indicate they are inputs, to maintain visual consistency in the UI. The squeezer, the fermenter and the refinery have blue/orange dots in their fluid inputs/outputs.

**Comment by BluSunrize** [comment]
*shrug*
Complain to the artist, I guess =P
I'll add the dots.
