### ISSUE TITLE
[1.10.2][0.10-42] Steel Scaffolding covering a Pipe is not climbable

### ISSUE THREAD

**Issue by calloatti** [BluSunrize/ImmersiveEngineering#1537]
The Steel Scaffolding covering a Pipe is not climbable. See Image. Player is not able to climb on top of catwalk using the steel scaffolding column, since the top steel scaffolding has a pipe inside.

Technically it may be a pipe with just a steel scaffolding decoration, but to the player it looks like a steel scaffolding with a pipe inside. It should be climbable.

http://i.imgur.com/OFA4fMe.png

**Comment by BluSunrize** [comment]
see #1499
