### ISSUE TITLE
[1.10.2][0.10-42] Pipes are sometimes invisible

### ISSUE THREAD

**Issue by calloatti** [BluSunrize/ImmersiveEngineering#1538]
http://i.imgur.com/opGXXSK.png

**Comment by BluSunrize** [comment]
Please read the contribution guidelines and provide a modlist.

**Comment by calloatti** [comment]
`Mods:
  BetterFps-1.3.2
  Chameleon-1.10-2.1.7
  ChunkAnimator-MC1.9.4-1.2
  ClayWorldGen-1.1.0-1.10.2
  ClientTweaks_1.10.2-1.1.14
  CraftingTweaks_1.10.2-6.1.16
  DrCyanosLootableBodies_1.10.2-2.2.0
  ElevatorMod[V.1.2.0][MC.1.10.2]
  EnderCompass-1.9.x-1.2.3.2
  EnderCore-1.10.2-0.4.1.56-beta
  EnderIO-1.10.2-3.0.1.117_beta.jar
  EnderIO-1.10.2-3.0.1.120_beta
  Excore-1.6.2-1.10.2
  FastLeafDecay-v11
  FinderCompass-1.10.2
  ForeverEnoughItems-1.0.16-1.10.2
  Gentle_Harvest_1.9_b8
  GiacomosCompass1.10.2-1.0
  ImmersiveEngineering-0.10-42
  InventoryTweaks-1.61-58
  jei_1.10.2-3.12.5.303
  JustEnoughCalculation-1.10.2-2.1.1.jar
  JustEnoughCalculation-1.10.2-2.1.2
  JustEnoughResources-1.10.2-0.5.3.61
  LLOverlayReloaded-1.1.0-mc[1.9-1.10.2]
  Mantle-1.10.2-1.0.0
  MapWriter-1.10.2-2.6.19
  MCMultiPart-1.2.1-universal
  netherportalfix-mc1.9.4-4.0.1
  ProgressiveAutomation-1.10.2-1.6.51
  quickhotbar_1102_1.04
  RTG-1.10.2-4.1.1.2
  SimplyCaterpillar-Forge-6.0.1.22
  StorageDrawers-1.10.2-3.2.7
  StorageNetwork-1.9.4-1.12.9
  supercraftingframe-1.10.2-1.2.1.87
  TConstruct-1.10.2-2.5.3
  usefulrecipes-2.1.0.0-HOTFIX-1
  VeinMiner-0.34.1-1.9r571+73be663
  Waila-1.7.0-B3_1.9.4
  WailaHarvestability-mc1.10.2-1.1.9
  Wawla-1.10.2-2.3.1.211
`

Full log: http://pastebin.com/y3EszAuw

**Comment by laserlemons** [comment]
Is it on a chunk border? I know that can cause similar visual glitches with other mods' pipes.

**Comment by calloatti** [comment]
No chunk border, about 4 blocks xyz from borders, no other mods pipes near it

**Comment by mindforger** [comment]
does this happen always to the same segments, regulary or only when placed or when placing soemthing besides it?

**Comment by calloatti** [comment]
I does not happen always to the same segments. I only saw it a few times. The list of mods is from the log of MultiMC, so everything is there, The list is wrong by the way, since it is just a list of files in the mods folder, with the extension removed, so for example:

EnderIO-1.10.2-3.0.1.117_beta.jar
EnderIO-1.10.2-3.0.1.120_beta

The first file is actually EnderIO-1.10.2-3.0.1.117_beta.jar**.old** so it does not get loaded by Minecraft. But anyway that is not relevant.

Not using Optifine and aware of imcompatibility with IE. 

Maybe BetterFps-1.3.2 could be a problem?

https://minecraft.curseforge.com/projects/betterfps

**Comment by mindforger** [comment]
there is a github ... makes it better than optifine imho :)
https://github.com/Guichaguri/BetterFps
