### ISSUE TITLE
[1.10.2] [0.10 - 42] Crash while placing certain blocks

### ISSUE THREAD

**Issue by Aleszp** [BluSunrize/ImmersiveEngineering#1543]
While placing down certain blocks (Lantern, barrel, concrete block) game crashes with error:
java.lang.NoSuchMethodError: net.minecraft.block.Block.getSoundType(Lnet/minecraft/block/state/IBlockState;Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;Lnet/minecraft/entity/Entity;)Lnet/minecraft/block/SoundType
After restarting minecraft and reloading world the block is placed, which (with this error) suggests that it's probably something wrong with bock placing sounds.

Happens both with optifine and other mods, without optifine or with IE (+forge) only. 
Tested in SSP and CSP.
Forge: forge-1.10.2-12.18.1.2011

fml crash report: http://pastebin.com/vv3TceW3
other mods used: http://pastebin.com/dUj5Ydrk (but happens with forge only too)

**Comment by malte0811** [comment]
Try updating forge.

**Comment by Aleszp** [comment]
Updating to forge-1.10.2-12.18.1.2095 didn't help either.
