### ISSUE TITLE
Dedicated Server crash on startup

### ISSUE THREAD

**Issue by xannor** [BluSunrize/ImmersiveEngineering#1545]
I get a server crash on startup with the latest IE 0.10-43 on 1.10.2.

https://gist.github.com/xannor/27c874f659b79c02ce01c1dd28f53bc9

**Comment by C0rn3j** [comment]
Same error, forge 2095, build 42 worked fine.

**Comment by BluSunrize** [comment]
Can you please quickly check if this build works?

http://puu.sh/rA74b/5b1159ca34.jar

**Comment by C0rn3j** [comment]
Loads fine
