### ISSUE TITLE
Breaking Convey Belts w/ Mining Drill

### ISSUE THREAD

**Issue by BLUESHADOW2020** [BluSunrize/ImmersiveEngineering#1547]
Oops, forgot version in title: [1.10.2 v0.10-44]

Conveyor belts broken via adjacency using the mining drill become broken conveyer belts with a name that ends in ..name (2 dots intentional). These don't move items when placed and have broken textures. Upon placing these down after breaking them a second time (can't remember if adjacent or just normal) the game crashed and continues to crash ever time I load that world. (Crash log: http://pastebin.com/YM22BbWv). I opened the world in world edit and looked at the conveyor I placed when I crashed and it had a different tag compound thing than the others (One that didn't crash me: https://gyazo.com/857a8953a80634550346173fcd6f0008, the one that did: https://gyazo.com/1d5ea0fd3c5025da48fd99589ce94a2b), upon deleting the problem conveyor belt using mc edit the world could be successfully loaded again. The mods installed are as follows: Better Fps (by Guichaguri), Block Drops (JEI Addon) (by MrRiegel), Immersive engineer (of course), Inventory tweaks (by Kobata), Item Scroller (by masa_), Just Enough Buttons (by universal), Just Enough Items (by mezz), Just Enough Resources (by Way2muchnoise) and Mouse Tweaks (by YaLTeR97). Thank you for your time.

**Comment by BluSunrize** [comment]
the issues created by invalid belts aside for now. You shouldn't have those in the first place.

I am unable to reproduce the issue of the mining drill dropping the invalid ones, the ones that drop for me are fine. Is this in singeplayer or on a server, and could you include what Forge version you're using?

**Comment by BLUESHADOW2020** [comment]
Sorry for the delay, yay timezones. It' s single player world and I was using forge-12.18.1.2094, but this also occurs with forge-12.18.1.2095, forge-12.18.1.2093, forge-12.18.1.2092 and probably more (I don't have all day). I tried going back to forges most recent recommended build (forge-12.18.1.2011) but this didn't fix it either, instead, it made another bug, every time I place a conveyor belt my game crashed (http://pastebin.com/xmf6wT0Q) but when I go back into the world the conveyor belt has been successfully placed and works just fine. Also here is a video I me recreating the bug just in case you dont believe me: https://drive.google.com/file/d/0B3iPMBQk375aelEwMGdCcDlrb1U/view?usp=sharing

**Comment by malte0811** [comment]
Managed to reproduce this, I'll look into fixing it now.

**Comment by malte0811** [comment]
This one is fixed, #1546 is an independent issue though, I might look into that one tomorrow.
