### ISSUE TITLE
Compiling error again

### ISSUE THREAD

**Issue by PawnedSauce** [BluSunrize/ImmersiveEngineering#155]
Here is a screenshot of the command prompt output from compiling.

![CMD](http://i.imgur.com/ZD13E4h.png)

Is there a way to do this by myself to save the hassle of having to bother you? :smiley:

**Comment by wafflemans** [comment]
are you trying to build it as a usable mod?

**Comment by BluSunrize** [comment]
ah, it's that stupid filename stuff again, where git doesn't realize capitalization changes exist.

**Comment by BluSunrize** [comment]
Should be fixed with that commit

**Comment by greg2-1** [comment]
@PawnedSauce wich versions of the library files are you using(because T have the newest versons of all of them and i wont compile)

**Comment by PawnedSauce** [comment]
You have yo figure it out its quite obvious
