### ISSUE TITLE
[Suggestion] Use Capabilities to enable lightning from Weather2 to work with the lightningrod

### ISSUE THREAD

**Issue by The-Fireplace** [BluSunrize/ImmersiveEngineering#1550]
So, this idea is based around Lex's whole explanation of Capabilities as being an easy way for mods to interact, and what they are supposedly capable of. I haven't tried them, so I apologize if this wouldn't work.

Basically, what would happen is Weather2 would attach a capability to its naturally generated lightning (Not if the storm was called by a weather machine), and IE would check lightning for this capability when the lightningrod is struck. This way, we don't have people abusing it with Blood Magic, but people with Weather2 can still use the lightningrod. What do you think?

**Comment by BluSunrize** [comment]
Not necessarily a bad idea. I'll look into that.

**Comment by Corosauce** [comment]
Never thought of using capabilities for that, but they are wonderfully generic so sounds possible! I'll have to look into this too.

**Comment by The-Fireplace** [comment]
Alternatively, adding the data to the entity's NBTTagCompound and checking that would probably also work.

**Comment by BluSunrize** [comment]
Closing this now, since I never really kept on it. 1.12 is now no longer supported
