### ISSUE TITLE
[1.10.2] Assembler + Mekanism crash

### ISSUE THREAD

**Issue by Terpo** [BluSunrize/ImmersiveEngineering#1551]
Forge: 1.10.2 - 12.18.1.2094
Involved Mods: 
- ImmersiveEngineering-0.10-42.jar
- Mekanism-1.10.2-9.2.0.292.jar
- MekanismGenerators-1.10.2-9.2.0.292.jar
- MekanismTools-1.10.2-9.2.0.292.jar

Modlist: http://blog.terpo.org/upload/mc/modlist.txt

Crashlog: http://pastebin.com/mAj513qt

A member of my server crashed it last night. He tried to connect something from Mekanism with the assembler. More details about it will follow later today.

**Comment by malte0811** [comment]
I think I fixed this for build 43, maybe try updating to build 44. This is usually caused by placing certain recipes in the assembler, not by connecting something to it, so it might still happen in build 44.

**Comment by Terpo** [comment]
I will tell this to my member, he can try it with a new version in sp then.

**Comment by BluSunrize** [comment]
No response in over a month, issue closed.
