### ISSUE TITLE
Cannot pump into or out of refinery. MC 1.10.2, IE 0.10-44

### ISSUE THREAD

**Issue by mopsyd** [BluSunrize/ImmersiveEngineering#1552]
As the title says, nothing pumps into or out of the refinery in the most recent version. Nothing of value in the log, seems to simply not recognize any attempt, although pipes hook up in the correct places. Attempted with all of the following:

-IE Pipes
-Ender I/O Fluid Conduits
-Ender I/O Fluid Tank (also pressurized fluid tank, neither worked)
-Refined Storage Fluid Export Bus

**Comment by mopsyd** [comment]
If relevant, these are the mods running when the issue arose:

AdditionalLootTables_1.10.2-1.06
  zz-backpacks 1.10.2 - 3.1.2
  BaseMetals_1.10.2-2.4.0.11
  Baubles-1.9.4-1.2.1.0
  bdlib-1.12.2.12-mc1.10.2
  BBG-1.9.4-5.0.0
  BetterFps-1.3.2
  Cavern_1.10-v1.1.1
  ChickenChunks-1.10.2-2.1.3.36-universal
  chiselsandbits-12.4
  CodeChickenCore-1.10.2-2.1.8.79-universal
  CraftableHorseArmor-1.3.0-1.10
  EndMetals_1.9-1.0.4
  EnderCompass-1.9.x-1.2.3.2
  EnderIO-1.10.2-3.0.1.120_beta
  EnderCore-1.10.2-0.4.1.56-beta
  Grapple-Hooks-1.10.2-1.0.8
  GraveStone Mod 1.5.5
  Guide-API-1.10.2-2.0.2-45
  ImmersiveEngineering-0.10-44
  InventoryTweaks-1.61-58
  ironchest-1.10.2-7.0.9.796
  jei_1.10.2-3.12.5.303
  JustEnoughResources-1.10.2-0.5.1.54
  liteloader-1.10-SNAPSHOT-release
  Mantle-1.10.2-1.0.0
  MCMultiPart-1.2.1-universal
  natura-1.10.2-4.0.0.81
  nethercore-1.10.2-2.0.2
  NetherMetals_1.9-1.1.2
  OpenComputers-MC1.10.2-1.6.0.3-rc.1
  orespawn-2.0.0.5-1.10.2
  platforms-1.10.0-1.2.0
  Railcraft_1.10.2-10.0.0-beta-2
  refinedstorage-1.1.3
  Ruins-1.10.2
  shetiphiancore-1.10.0-3.3.1
  thedragoncore-1.1.0
  mod_voxelMap_1.6.15_for_1.10.0
  Waila-1.7.0-B3_1.9.4
  Waystones_1.10.2-2.0.5
  Wawla-1.10.2-2.3.0.206
  WTF-Expedition-1.10.2_1.0

**Comment by BluSunrize** [comment]
Already fixed, see #1548
