### ISSUE TITLE
[1.10.2]Splitting Conveyor belts don't work

### ISSUE THREAD

**Issue by iPencil** [BluSunrize/ImmersiveEngineering#1554]
1.10.2, Forge 2094, Immersive Engineering 0.10 - 44:

http://i.imgur.com/pGBIDng.png

Using a splitting conveyor to send half of my crafted food over to a dropper, half to the other dropper. It seems that when it's not fully stacked items (64) it moves the item into one direction, then when moving the next one in line, the items merge into one stack and all go into the same direction. Not a single item ever goes into the other direction as this happens with every 2 items after that as well.

If I attempt to put chests/hoppers/inventories next to them they all get stuck like this:
http://i.imgur.com/xk1wxP1.png

Note those items getting stuck I have also very rarely had happen with dropping conveyors as can be seen here:
http://i.imgur.com/AseMAEU.png

**Comment by BluSunrize** [comment]
I can't prevent items from stacking. Nothign to be done about that sorry to say.

**Comment by iPencil** [comment]
Urgh that blows :/ That pretty much makes the splitting conveyor unusable . Sad, it's a pretty nice idea! What about items getting stuck at the end of the conveyor?

**Comment by BluSunrize** [comment]
The getting stuck might actually be a legitimate issue. Please try and see if placing another conveyor between the splitter and the chest makes the insertion work.

**Comment by iPencil** [comment]
Just tested it. Putting another conveyor belt there causes the mentioned stacking issue, but when using already stacked items, they no longer get stuck!

**Comment by iPencil** [comment]
Also, I've just noticed that a hopper adds a long enough delay where no 2 items are present that the stacking does not occur, so at least you can get around that issue and splitting conveyors are useful again! *yay*

**Comment by BluSunrize** [comment]
Yaaay!

**Comment by Minamikaze392** [comment]
> 
> 
> Also, I've just noticed that a hopper adds a long enough delay where no 2 items are present that the stacking does not occur, so at least you can get around that issue and splitting conveyors are useful again! _yay_

Hoppers push an item every 8 ticks, and is fast enough to make 2 items stack and breaks the splitting conveyor.

EDIT: My workaround is to use an extracting conveyor belt with maximum delay of 20 ticks, and make the items fall 1 block every conveyor, so that the items are far apart enough until they are splitted.

An example of smelting with 4 furnaces:
![image](https://user-images.githubusercontent.com/40918110/103198569-99537a80-4923-11eb-9d63-fe494a750dce.png)

**Comment by BluSunrize** [comment]
**this issue was closed 4 years ago, for goodness sake**
