### ISSUE TITLE
[Suggestion] Idea to improve short-ranged wiring and improve usefulness for the lower voltage wires.

### ISSUE THREAD

**Issue by laserlemons** [BluSunrize/ImmersiveEngineering#1558]
In my opinion, the wires in the mod are great for transporting energy long distance, but they get too messy when dealing with short distances. My idea is to do away with connector blocks. It'd be a whole lot easier to wire up machines if they all worked similar to the Powered Lantern, allowing for direct wire connection, while also being able to daisy-chain them. Each machine (including capacitors) could have a required wire voltage, which would encourage the use of lower tier wires and transformers (which no-one really uses because almost everything can be hooked up to an HV connector).

One issue that could be caused by this is that it'd be hard to see where wires are connected in tight configurations, which can be alleviated by allowing the wire cutters to turn machines semi-transparent or highlight wires through blocks.

**Comment by ToadsworthLP** [comment]
There are config options to adjust the wire's ranges and transport capacity, this could help together with some Mintweaker magic to re-balance the wires. I disagree in terms of removal of the connectors. They just look so nice, and isn't that what sets IE apart from most other tech mods? And for the voltage thing: It would not make much sense having giant machines like the excavator not being able to accept high voltage, though the idea itself is interesting.

**Comment by laserlemons** [comment]
I didn't say the large machines shouldn't require high voltage.

**Comment by laserlemons** [comment]
Closed because I thought of a more realistic suggestion. I'll put it up in a separate post.
