### ISSUE TITLE
[0.10-44]Refinery voiding Ethanol and Plant Oil

### ISSUE THREAD

**Issue by Susjin** [BluSunrize/ImmersiveEngineering#1560]
I made a setup for biodiesel, but when i pump the two liquids inside the refinery, they just get voided, i already tried configuring redstone control but nothing changes

I tried to pump with fluid pipes from IE, conduits from EIO and from a tank directly

**Comment by kane-thornwyrd** [comment]
Thank you for your report, 
can you attach the listing of all the mods installed and a forced crash log, I advertise you to use [gist](https://gist.github.com/) for this.

Thank you :)

**Comment by BluSunrize** [comment]
Has already been reported and fixed, please try using the search function before creating an issue
See #1548
