### ISSUE TITLE
[Suggestion] Make LV and MV wires more useful and give a reason to use transformers.

### ISSUE THREAD

**Issue by laserlemons** [BluSunrize/ImmersiveEngineering#1561]
LV: Allow connector chaining, remove relays. Keep 16 block range.
This would make LV wires much less messy when wiring small, densely packed machines.

MV: Increase range to either 24 or 32 blocks.
This would give people a reason to use MV instead of HV for general power transport, especially if the destination needs to drop to LV using a transformer.

HV: Increase crafting cost slightly.
These wires, in my opinion, are overused right now since they're objectively better than the others.

Capacitors: Require matching connectors so people stop using them as pseudo-transformers with a built-in power buffer.

**Comment by calloatti** [comment]
I start with LV and switch to HV as soon as I can for everything. No point in using MV. And yes, never used transformers, I use capacitors as pseudo transformers while rewiring LV to HV.

**Comment by c727** [comment]
@BluSunrize any feedback for this? _Capacitors: Require matching connectors so people stop using them as pseudo-transformers with a built-in power buffer._
