### ISSUE TITLE
[MC 1.10.2][IE 0.10-44][TiCon 2.5.3][Forge 2094] Updating Screen Events crash

### ISSUE THREAD

**Issue by Alaberti** [BluSunrize/ImmersiveEngineering#1562]
http://pastebin.com/mbjru9hj

Had a player attempt to make wire cutters in a TiCon crafting station. Reported on their tracker: https://github.com/SlimeKnights/TinkersConstruct/issues/2472

**Comment by Alaberti** [comment]
http://pastebin.com/70xZYY5k 

Player discovered this issue occurs with vanilla crafting tables as well.

**Comment by malte0811** [comment]
Duplicate of #1549, already fixed.

**Comment by Alaberti** [comment]
My apologies, I didn't search hard enough
