### ISSUE TITLE
Conveyors have a missing texture in hand

### ISSUE THREAD

**Issue by Peach774** [BluSunrize/ImmersiveEngineering#1563]
As the title says, when in your hand, conveyors have a pink and black texture but are fine when placed

**Comment by BluSunrize** [comment]
Please read the contribution guidelines and provide a modlist.

**Comment by Peach774** [comment]
Mod List
Cosmetic Armor Reworked (by ZLainSama)
Calculator (by Ollie_Lansdell)
Storage Drawers (by jaquadro)
Crafting Tweaks (by BlayTheNinth)
Just Enough Resources (JER) (by Way2muchnoise)
Immersive Craft (by McJty)
Just Enough Items (JEI) (by mezz)
Nomadic Tents (by sky_01)
Capsule (by Lythom7)
Apple Shields Mod (by Vadis365)
Cyclops Core (by kroeser)
Chisels & Bits (by AlgorithmX2)
Common Capabilities (by kroeser)
RFTools Dimensions (by McJty)
Recall Stones (by VanhalMinecraft)
Additional Banners - Expand your options. (by darkh4x)
HelpFixer (by matthewprenger)
FFS - Fancy Fluid Storage (by Lordmau5)
Iron Chests (by progwml6)
FTB Utilities (by FTB)
EvilCraft (by kroeser)
ElecCore | Rendering Library (by Elec332)
JourneyMap (by techbrew)
Not Enough Wands (by romelo333)
Morpheus (by Quetzi)
OreDictionaryConverter (by EXTER7)
Baubles (by azanor)
Runes of Wizardry (by xilef11)
Soul Shards: The Old Ways (by SgtPunishment)
Chest Transporter (by CubeX2)
Extra Utilities (by RWTema)
ValkyrieLib (by ValkyrieofNight)
Advanced Generators (by bdew)
MoarSigns (by Gory_Moon)
Gendustry (by bdew)
TOP Addons (by DrManganese)
EnderTanks (by ShetiPhian)
Cooking for Blockheads (by BlayTheNinth)
Super Crafting Frame (by Edgar_Allen)
Mantle (by mDiyo)
Forestry (by SirSengir)
Pam's HarvestCraft (by MatrexsVigil)
Environmental Tech (by ValkyrieofNight)
Inventory Sorter (by cpw11)
Ender Zoo (by CrazyPants_MC)
AutoPackager (by smbarbour)
ModTweaker (by jaredlll08)
MCMultiPart (by amadornes)
Redstone Paste (by FyberOptic)
Sonar Core (by Ollie_Lansdell)
The One Probe (by McJty)
Terrain Crystals (by BaileyHoll)
Reliquary v1.3 (by P3pp3rF1y)
FastLeafDecay (by Olafskii)
McJtyLib (by McJty)
Biomes O' Plenty (by Glitchfiend)
MmmMmmMmmMmm (by bonusboni)
Chisel (by tterrag1098)
Underp Hangables (by masa_)
Tinkers Construct (by mDiyo)
Zoology (by RWTema)
TechReborn (by modmuss50)
Ender IO (by CrazyPants_MC)
Roots (by elucent)
Flat Colored Blocks (by AlgorithmX2)
Chameleon (by jaquadro)
CraftTweaker (by jaredlll08)
EnderCore (by tterrag1098)
Extra Bit Manipulation (by MolecularPhylo)
RFTools (by McJty)
NoNausea (by lumien231)
PSIonic Upgrades (by yrsegal)
MultiStorage (by ShetiPhian)
Runes of Wizardry - Classic Dusts Pack (by xilef11)
BetterAchievements (by Way2muchnoise)
Quark (by Vazkii)
Refined Storage (by raoulvdberge)
Integrated Dynamics (by kroeser)
Progression (by joshiejack)
More Overlays (by feldim2425)
RebornCore (by modmuss50)
GraveStone Mod (by EuhDawson)
Waila Harvestability (by squeek502)
FTBLib (by FTB)
Totemic (by ljfa)
ShetiPhianCore (by ShetiPhian)
Compass Coordinates (by Quetzi)
Waila (by ProfMobius)
BaublesHud (by Gigabit1011)
BdLib (by bdew)
Bagginses (by lorddusk)
Holographic Victory Monument (by abecderic)
Terrain Crystals Add-ons (by BaileyHoll)
Item Scroller (by masa_)
Ranged Pumps (by raoulvdberge)
StacksOnStacks (by Madxmike856)
ShadowMC (by shadowfactsmc)
Extra Rails (by shadowfactsmc)
Cyberware (by stuntrally)
MalisisCore (by Ordinastie)
MalisisDoors (by Ordinastie)
Psi (by Vazkii)
MalisisBlocks (by Ordinastie)
JEI Bees (by bdew)
Bagelsmore: The Return (by Ollie_Lansdell)
Goetia (by elucent)
Guide-API (by TehNut)
Blood Magic (by WayofTime)
AutoRegLib (by Vazkii)
Immersive Engineering (by BluSunrize)
OpenComputers (by Kethtar)
ProjectE (by sinkillerj)
Magneticraft (by cout970)
More Bees (by Proffeser_science)
[SBM] Wooden Shears (by darkguardsman)
Morph-o-Tool (by Vazkii)
Botania (by Vazkii)
Natura (by mDiyo)
Railcraft (by CovertJaguar)
Aroma1997Core (by Aroma1997)
AromaBackup (by Aroma1997)
LootBags (by Malorolam)
KleeSlabs (by BlayTheNinth)
TESLA (by darkh4x)
Tesla Coils (by GunnerWolfe)
Deep Resonance (by McJty)
Embers (by elucent)
Ding (by iChun)

**Comment by BluSunrize** [comment]
I don't see it in the list (which btw. please put on pastebin or gist next time, to save us the wall of text) but I have to ask:
 Are you using Optifine?
Also, are these broken conveyors named correctly, or are they wrongly named like the ones gotten out of Project E?
Do they have broken textures in JEI, and if so, can you provide a screenshot?

**Comment by Peach774** [comment]
I am not using optifine. They are named correctly and were from crafting them manually. I will get a JEI screenshot later
