### ISSUE TITLE
[1.10.2_0.10-44] Player inventory rollback on accessing machine inventory

### ISSUE THREAD

**Issue by Crazy-KSK** [BluSunrize/ImmersiveEngineering#1565]
Dropping items via ctrl+q and then accessing a machine inventory rolls back the player inventory as in this video
https://p.fuwafuwa.moe/rjyism.webm 
manual crash right after
http://pastebin.com/Jme2etKc
I'm in creative mode and the world is peaceful 

Forge: 1.10.2-forge1.10.2-12.18.2.2099
ImmersiveEngineering-0.10-44

**Comment by BluSunrize** [comment]
Can you replicate this by putting the diamonds in a chest instead of throwing them?
Because I'm pretty sure this is a vanilla client sync issue.

**Comment by Crazy-KSK** [comment]
No, only doping them works and I have to be using  hotkeys to do so, either ctrl+q or just q, drag drop outside the inventory does not work.

**Comment by malte0811** [comment]
1. Seems to be creative mode only... So not as bad as it might be.
2. It happens with vanilla crafting tables as well, so not necessarily IE related. I'm testing vanilla and forge without mods right now

**Comment by BluSunrize** [comment]
That is definitely a vanilla sync issue then, similarly to how shiftclicking an item back into the creative menu and then trying to spawn an item from JEI won't fill that slot in question. Not IEs fault ^^

**Comment by BluSunrize** [comment]
Closed, because vanilla issue
