### ISSUE TITLE
[Suggestion] Decorative Coils

### ISSUE THREAD

**Issue by KindarConrath** [BluSunrize/ImmersiveEngineering#157]
I would like to suggest that decorative coils can attach to any wire connector.  As is, it can only connect to the HV Relay and that can only be hung upside down.

**Comment by BluSunrize** [comment]
there is a structural connector which can accept hemp rope and steel cable.

**Comment by KindarConrath** [comment]
ok, I was hoping I could balance my power lines with the decorative cables.

**Comment by BluSunrize** [comment]
That's what those are for =P

**Comment by KindarConrath** [comment]
But the look so different from the MV connectors I have on the other side!  :P

**Comment by BluSunrize** [comment]
I can't easily attach decorative cable to MV connectors though, that doesn't work with the current system.

**Comment by KindarConrath** [comment]
Ohhh, ok!

**Comment by KindarConrath** [comment]
Then i'm going to suggest for a future enhancement that you can disguise the structural connectors as other connectors.
