### ISSUE TITLE
[1.10.2_0.10-44] Lighting Rod "Required Materials" does not match images in manual.

### ISSUE THREAD

**Issue by calloatti** [BluSunrize/ImmersiveEngineering#1572]
In the Lightining Rod entry in the manual the images show capacitors and other things not listed in the "Required Materials"

And elements listed are not seen in the images. Something does not match.

http://i.imgur.com/fti4CeN.png

http://pastebin.com/Sn0MDfLT

**Comment by kane-thornwyrd** [comment]
Can you follow the contributing guidelines please ? :)
