### ISSUE TITLE
[0.10 - 44] Toolbox destroys stacks of items.

### ISSUE THREAD

**Issue by laserlemons** [BluSunrize/ImmersiveEngineering#1573]
Looks like the toolbox bug is inverted now.

Before shift-click:
![2016-10-11_23 30 09](https://cloud.githubusercontent.com/assets/6501298/19299689/b9fb44f6-900a-11e6-807f-63ddb19d4233.png)

After shift-click:
![2016-10-11_23 30 17](https://cloud.githubusercontent.com/assets/6501298/19299692/baf40500-900a-11e6-930b-45c1695034da.png)

**Comment by kane-thornwyrd** [comment]
Is this relkated to https://github.com/BluSunrize/ImmersiveEngineering/issues/1501 ?

**Comment by laserlemons** [comment]
I would assume it has to do with the way #1501 was fixed.
