### ISSUE TITLE
Question: Is the Bottling Machine gone in the latest version?

### ISSUE THREAD

**Issue by calloatti** [BluSunrize/ImmersiveEngineering#1574]
If it is, can we have it back?

**Comment by BluSunrize** [comment]
Yes, it's been gone since 1.8. Funny that people only notice it now.
I plan to readd it at some point soon, but I want to make a new model for it.

**Comment by James-T-Oudvoure** [comment]
What do you not like about the current model? It looks alright to me, not that I'm saying that you have no right to change it if you want, but why do you not like the current model?

**Comment by BluSunrize** [comment]
I'm not satisfied with my own work on it, so I want to change it ^^

**Comment by calloatti** [comment]
Thank you for your reply.
