### ISSUE TITLE
Crash when placing IE blocks in 1.10.2

### ISSUE THREAD

**Issue by the1bladesmith** [BluSunrize/ImmersiveEngineering#1577]
The game crashes whenever I place a immersive engineering block (crate, coke oven brick, etc.) with a java.lang.NoSuchMethod error.  Crash report is attached.
[crash-2016-10-12_19.58.00-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/525923/crash-2016-10-12_19.58.00-client.txt)

**Comment by mindforger** [comment]
click search, insert "placing block crash" 4th result
https://github.com/BluSunrize/ImmersiveEngineering/issues/1543

**Comment by BluSunrize** [comment]
^ what he said.
