### ISSUE TITLE
[Feature Request/Bug] Core Sample Drill does not work with frames

### ISSUE THREAD

**Issue by Simon-Bitdiddle** [BluSunrize/ImmersiveEngineering#1578]
WRT Funky Frames, Core Sample Drill does not move with the frame and prevents it from moving.

**Comment by mindforger** [comment]
so  does an assembled excavator, what are you trying? it is not supposed to be moved, why don't you break it before moving and place it down again?

**Comment by BluSunrize** [comment]
Intentional. Multiblocks are not supposed to be moved because it might break their functionality.
