### ISSUE TITLE
[question/bug] Floodlight non-functioning

### ISSUE THREAD

**Issue by James-T-Oudvoure** [BluSunrize/ImmersiveEngineering#1579]
Did you disable the floodlight on purpose? Not only does it look like someone removed the light bulb:
![2016-10-12_20 33 24](https://cloud.githubusercontent.com/assets/14304823/19333617/d7dcb63c-90bc-11e6-9256-a04f6f3d5421.png)
But the thing won't light up, even when connected to a power source:
![2016-10-12_20 50 47](https://cloud.githubusercontent.com/assets/14304823/19333850/97fc4e3c-90bd-11e6-8595-17711dc5d707.png)
And the hammer doesn't effect it at all.

**Comment by 50m31-AW** [comment]
I don't see any levers/RS torches/etc. in your setup. Is it recieving a redstone signal as well? I'm pretty sure it needs to be powered both with IF and a redstone signal.

**Comment by James-T-Oudvoure** [comment]
I checked the manual, and it said nothing about that.

**Comment by malte0811** [comment]
It does need a redstone signal to operate (from code and from experience, I will add that to the manual entry if I don't forget to do so), it works when one is applied. I am looking into the broken rotation and the missing glass now.

**Comment by mindforger** [comment]
mindforger hands malte0811 a new bulb ... scnr

**Comment by BluSunrize** [comment]
"How many Germans does it take to exchange a lightbulb?"
"Only one. We're efficient."

**Comment by James-T-Oudvoure** [comment]
I'd also like to add, since we're on the topic of redstone, the breaker switch doesn't emit a redstone signal. If this is intentional, the manual page will need to be updated.
