### ISSUE TITLE
Connecting to IC2 causes constant power draw

### ISSUE THREAD

**Issue by ratmage99** [BluSunrize/ImmersiveEngineering#158]
When a wire is attached to any IC2 machine (tested with macerator and electric furnace,) power is drawn at a constant rate regardless of whether power is requested or not. It seems to just be a power void once the machine is full of power.

**Comment by porteriscool** [comment]
I have the same problem, and I have mine hooked up to a macerator, mfe, extractor, and compressor.

**Comment by Terpo** [comment]
Same as #149 and should already be fixed for the next release.

**Comment by BluSunrize** [comment]
Correct

**Comment by awebneck** [comment]
I'm seeing this issue still with version 0.5.4

**Comment by mindforger** [comment]
try update first to 0.6.0
