### ISSUE TITLE
[0.10 - 44] Buckshot only damages with one projectile.

### ISSUE THREAD

**Issue by laserlemons** [BluSunrize/ImmersiveEngineering#1580]
It seems like it only does damage with one projectile, no matter how many actually hit. It's probably due to the Minecraft's damage cooldown/delay.

**Comment by theunkn0wn1** [comment]
That would be a vanilla limitation. The first projectile hits causing damage and starting the invulin timer nulling the other projectiles damage. 

Perhaps this could be worked around by causing projectiles to 'stick' to NPCs for a few ticks and delivering the sum of the total projectiles damage in one go?
