### ISSUE TITLE
Redstone Breaker can only be placed facing one direction

### ISSUE THREAD

**Issue by James-T-Oudvoure** [BluSunrize/ImmersiveEngineering#1582]
Before placing:
![2016-10-13_10 04 10](https://cloud.githubusercontent.com/assets/14304823/19354487/7640d280-912c-11e6-9e55-099e3e1d75cc.png)
After placing:
![2016-10-13_10 04 12](https://cloud.githubusercontent.com/assets/14304823/19354494/7fba4774-912c-11e6-8a0c-9e91ff7d49f8.png)

**Comment by BluSunrize** [comment]
Yep. Has been like this since 1.8. Slow on the pickup, eh? =P

This was due to the new model system and how much worse it became to do more dynamic rendering.

**Comment by James-T-Oudvoure** [comment]
So, this is never going to be fixed?

**Comment by malte0811** [comment]
I am working on it, the structural connectors do the same thing (just without bounding boxes and connection offsets), so a lot of the code is already there. I also made some changes to the CONTRIBUTING.md file regarding duplicate reports, here is a gist of my new version: https://gist.github.com/malte0811/16ead6325c7c0a278d7097132ce4305c

**Comment by BluSunrize** [comment]
Heh, fair enough Malte. I'll wait for you contibution then.
Thanks buddy ^^
