### ISSUE TITLE
1.10.2/.44 When harvesting a pipe covered with steel scaffolding, you only get the pipe back.

### ISSUE THREAD

**Issue by calloatti** [BluSunrize/ImmersiveEngineering#1583]
The scaffolding vanishes.

Minecraft 1.10.2 Only IE mod, no other mods. Forge 2099

http://imgur.com/a/367qB

**Comment by StarvingPoet** [comment]
Also occurs with wood scaffolding

**Comment by BluSunrize** [comment]
Yeah, it would occur with any of them. I'll see to it on the weekend.
