### ISSUE TITLE
Typo in "transformerPost.obj"

### ISSUE THREAD

**Issue by calloatti** [BluSunrize/ImmersiveEngineering#1584]
Maybe the lines:

```
244 usemtl transformer
245 s off

```
Should be:

`244 usemtl transformers off`

https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/resources/assets/immersiveengineering/models/block/connector/transformerPost.obj

**Comment by BluSunrize** [comment]
No. No it should not.
Forge ignores the "s" argument in OBJ files anyways.
