### ISSUE TITLE
8 Planks + 1 creosote bottle = 8 treated wood planks + 64 creosote bottles

### ISSUE THREAD

**Issue by jwoey** [BluSunrize/ImmersiveEngineering#1586]
**What is the bug?**  
Crafting 8 treated wood planks using a creosote bottle yields 64 creosote bottles (in addition to the expected treated wood) instead of 1 empty glass bottle.
**What did you do to make it happen?**  
Filled glass bottles with creosote from a coke oven, used crafting station from TiCo to craft.  I did not test vanilla or other crafting tables.  Using a bucket of creosote did not have the same duplication problem.
**Does it happen every time you do this?** 
Yes
**Did this happen on a dedicated server (multiplayer servers), in LAN multiplayer or in singleplayer?**
LAN multiplayer & singleplayer.  Have not tested dedicated server.
**What other mods were installed when the bug happened?**
I am using All the Mods modpack for 1.10.2. I'm one release behind (I am using the latest version of Immersive Engineering).

**Here are the mods i've added to the pack:**
Realistic Terrain Generation (latest)
BiomeTweaker

**Here is the default modlist for the pack:**
Just Enough Items (JEI) (by mezz)
Simpleretrogen (by cpw11)
Soul Shards: The Old Ways (by SgtPunishment)
BetterBedrockGen (by Gigabit1011)
EnderBags (by Gigabit1011)
Baubles (by azanor)
Nashorn Scripting Library (by TarynWinterblade)
Resource Loader (by lumien231)
Custom Main Menu (by lumien231)
Experience Rings (by MrComputerGhost)
Chisels & Bits (by AlgorithmX2)
Fast Leaf Decay (by lumien231)
Cooking for Blockheads (by BlayTheNinth)
MMD OreSpawn (by jriwanek)
Deep Resonance (by McJty)
AbyssalCraft (by Shinoow)
End Metals (by jriwanek)
Storage Drawers (by jaquadro)
Psi (by Vazkii)
Iron Chests (by progwml6)
Not Enough Wands (by romelo333)
Bloodmoon (by lumien231)
Ender IO (by CrazyPants_MC)
McJtyLib (by McJty)
Tomb Many Graves (by M4thG33k)
Morpheus (by Quetzi)
Tinkers Construct (by mDiyo)
Random Things (by lumien231)
TESLA (by darkh4x)
EnderCore (by tterrag1098)
Better Agriculture (by knoxhack)
Packing Tape (by gigaherz)
Environmental Tech (by ValkyrieofNight)
OpenComputers (by Kethtar)
RFTools (by McJty)
Nether Metals (by knoxhack)
Enderthing (by gigaherz)
No Mob Spawning on Trees (by oldjunyi)
Flat Colored Blocks (by AlgorithmX2)
Grapple Hooks (by Kloonder)
Forestry (by SirSengir)
RFTools Dimensions (by McJty)
AutoPackager (by smbarbour)
Bagginses (by lorddusk)
The One Probe (by McJty)
Chameleon (by jaquadro)
Actually Additions (by Ellpeck)
Mantle (by mDiyo)
Chisel (by tterrag1098)
ValkyrieLib (by ValkyrieofNight)
BdLib (by bdew)
Easy Breeding (by anthonysheets)
Bookshelf (by darkh4x)
Correlated Potentialistics (by unascribed)
EnderTanks (by ShetiPhian)
Dark Utilities (by darkh4x)
Advanced Generators (by bdew)
AtomicStryker's Infernal Mobs (by AtomicStryker)
Inventory Tweaks (by Kobata)
Pam's HarvestCraft (by MatrexsVigil)
Platforms (by ShetiPhian)
Progressive Automation (by VanhalMinecraft)
Roots (by elucent)
ShadowMC (by shadowfactsmc)
ShetiPhianCore (by ShetiPhian)
Sleeping Bag (by shadowfactsmc)
Substratum (by EXTER7)
AppleCore (by squeek502)
The Spice of Life (by squeek502)
Roguelike Dungeons (by Greymerk)
Quark (by Vazkii)
OreDictionaryConverter (by EXTER7)
Just Enough Resources (JER) (by Way2muchnoise)
CraftTweaker (by jaredlll08)
Ender Zoo (by CrazyPants_MC)
MmmMmmMmmMmm (by bonusboni)
Item Scroller (by masa_)
Gendustry (by bdew)
Crafting Tweaks (by BlayTheNinth)
Water Strainer (by Rubironi)
Giacomo's Fishing Net (by Zacomat)
Reliquary v1.3 (by P3pp3rF1y)
Sonar Core (by Ollie_Lansdell)
Calculator (by Ollie_Lansdell)
Bullseye (by Glitchfiend)
UniDict (by WanionCane)
Biomes O' Plenty (by Glitchfiend)
MobTotems (by CorwinJ)
Extra Utilities (by RWTema)
PSIonic Upgrades (by yrsegal)
Signals (by MineMaarten)
Natural Pledge (by yrsegal)
Just Enough Forestry Bees (JEFB) (by MrDimkas_Studio)
Extra Rails (by shadowfactsmc)
Waila (by ProfMobius)
Waila Harvestability (by squeek502)
Wawla - What Are We Looking At (by darkh4x)
MalisisCore (by Ordinastie)
MalisisDoors (by Ordinastie)
WTF's Expedition: CaveBiomes, Ores, Trees, and Tweaks (by WhiskytangoFox)
stimmedcow : NoMoreRecipeConflict (by Oliv1er)
ElecCore | Rendering Library (by Elec332)
TheDragonLib (by Moritz30)
ArmorPlus (by Moritz30)
NetherPortalFix (by BlayTheNinth)
Guide-API (by TehNut)
Blood Magic (by WayofTime)
Charset (by Vazkii)
Immersive Engineering (by BluSunrize)
FTBLib (by FTB)
FTB Utilities (by FTB)
AppleSkin (by squeek502)
Crossroads MC (by Technomancer_isTaken)
JourneyMap (by techbrew)
ZeroCore (by ZeroNoRyouki)
Extreme Reactors (by ZeroNoRyouki)
Compact Solars (by progwml6)
AutoRegLib (by Vazkii)
Morph-o-Tool (by Vazkii)
Pressure Pipes (by bdew)
RebornCore (by modmuss50)
TechReborn (by modmuss50)
Just Enough Calculation (by Towdium)
Login Shield (by Glasspelican)
Cyberware (by stuntrally)
Refined Storage (by raoulvdberge)
MCMultiPart (by amadornes)
More Bees (by Proffeser_science)
Botania (by Vazkii)
RFTools Control (by McJty)
Tinkers' Tool Leveling (by bonusboni)
Brandon's Core (by brandon3055)
Draconic Evolution (by brandon3055)
Railcraft (by CovertJaguar)

This is my first bug report.  I hope I've not done anything wrong.

**Comment by ArukaAlter** [comment]
Ask it to the Railcraft dev, IE doesn't have bottles anymore so they must be the ones from RC.

**Comment by jwoey** [comment]
aha thank you. my mistake.

**Comment by calloatti** [comment]
Can confirm same thing happening to me using creosote bottles from railcraft

**Comment by ArukaAlter** [comment]
@calloatti what did I just said? .-.

**Comment by jwoey** [comment]
sounded like he or she was just supporting your claim that it was Railcraft, not challenging it.  I looked on the railcraft github and this issue is already there.  Sorry for wasting folks' time.
