### ISSUE TITLE
Wire cutters crafting crash

### ISSUE THREAD

**Issue by niccosaint** [BluSunrize/ImmersiveEngineering#1587]
While I tried to craft wire cutters on crafting table on the server it crashes me with this:
[crash-2016-10-13_18.50.01-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/527710/crash-2016-10-13_18.50.01-client.txt)

I don't know whose fault is this...

**Comment by Simbrine** [comment]
I already created an issue; see #1549

**Comment by mindforger** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/search?q=wire+cutter+crash&type=Issues&utf8=%E2%9C%93 sorry but i had to

**Comment by niccosaint** [comment]
Woops, I haven't noticed this one ヘ（。□°）ヘ
