### ISSUE TITLE
Steam Power generation?

### ISSUE THREAD

**Issue by InkDragon** [BluSunrize/ImmersiveEngineering#159]
Would it be possible to add a turbine to be used with the kinetic dynamo so that steam from mods like flaxbeard's steam power could be harnessed as a way to generate RF

**Comment by BluSunrize** [comment]
You should suggest that to twitter.com/Damien_hazard =P

**Comment by MyDeloreanWontStart** [comment]
FSP steam can be converted to fluid steam with one block already in FSP.
