### ISSUE TITLE
Suggestion: Increase plate recipe cost...

### ISSUE THREAD

**Issue by VallenFrostweaver** [BluSunrize/ImmersiveEngineering#1590]
...to encourage mod exploration like more use of your Metal Press. Keep the recipe the press uses the same (cheap 1:1) but increase the cost for using your tinker hammer or have the hammer damaged much much more. I have found many people will never make a Metal Press because they can just use the tinker hammer.

To come clean, I have to admit that I didn't think of this. I saw an example of something like this on the Embers mod by Elucent (4 ingots + hammer = 1 plate but later a machine will have 1:1) and it makes sense. I know your mod already has certain cost increases to it and that may not be the answer but I feel this would help welcome exploring your mod considerably (at least in theory).

**Comment by BluSunrize** [comment]
Eh. No, not to fond of cost increase. Greg and IC2 require 2 ingots if you make the plate manually, and I don't like that.
Hammer's maximum damage is configurable so that can be a balancing factor you set yourself, but I won't take more materials.

**Comment by ArukaAlter** [comment]
IC2 uses only one ingot for manual plates making IE cost the same, only Greg does two.
