### ISSUE TITLE
Laggy redstone connectors.

### ISSUE THREAD

**Issue by marcin212** [BluSunrize/ImmersiveEngineering#1591]
When my buddy is not on our server, his redstone connectors lag heavily. Much more than when he is online.

https://img.bymarcin.com/screenshot-2016-10-14_17-42-54.png
JVisualVM sampler-snapshot: https://dl.dropboxusercontent.com/u/25172450/IE-lag.nps

Immersive Engineering 0.10 - 44

**Comment by BluSunrize** [comment]
After folding that out a little more, it seems to lag out most in the world updates. Combine that with the fact that it happens when your buddy is not on the server, and it's most likely that it's force-loading chunks.

I'll look into this.
