### ISSUE TITLE
Pipe Linking Persistance / Rendering Bug

### ISSUE THREAD

**Issue by StarvingPoet** [BluSunrize/ImmersiveEngineering#1593]
Mods Installed: http://pastebin.com/JVAX9Ezr

But I've also tested it on a IE only setup.

In short - if you use your hammer to prevent two pipes from connecting, then remove either one of those pipes, placing new pipes will cause them to reconnect without rendering the connection thus preventing you from disconnecting them again.  The visual error persists on server and client restarts and the only way to fix it is to remove both pipe sections and replace them.

See the following album:
http://imgur.com/a/DgWDA

**Comment by malte0811** [comment]
Fixed.
