### ISSUE TITLE
Un-removeable double Tooltips

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [BluSunrize/ImmersiveEngineering#1595]
https://minecraft.curseforge.com/projects/immersive-engineering?comment=1134

**Comment by BluSunrize** [comment]
Please read the contribution guidelines.
The issue you are (failing to be) describing is only present if you play with advanced tooltips on, aka F3+H.

This is not a bug, it's a feature for those that want to see OreDict names on their items. If other mods provide the same feature, nothing I can really do.

**Comment by GirafiStudios** [comment]
Although I do agree with you Blu, I guess you would always add a config option? :)

**Comment by BluSunrize** [comment]
Eh. For something tiny as that, it's almost a waste of a variable. But I'll consider it, depending on the response of the original poster.

**Comment by KnightMiner** [comment]
I would argue for a config option as well. I have seen a few too many mods add this feature without a config to disable it (EnderCore is just one of the nice ones that has a config to remove it), plus it would be nice to have the choice of which implementation I prefer (which in this case is the EnderCore version as I can make it only visible on "Shift", my tooltips are way to cluttered in debug as it is)
