### ISSUE TITLE
Crash crafting Wire Cutters in ProjectE Philosopher Stone Crafting Table

### ISSUE THREAD

**Issue by MokahTGS** [BluSunrize/ImmersiveEngineering#1596]
ImmersiveEngineering-0.10-44

ProjectE-1.10.2-PE1.0.6B

Got a crash to desktop trying to craft the wire cutters in the philosophers stone crafting UI from ProjectE:

http://pastebin.com/gyTMkxiP

**Comment by MokahTGS** [comment]
Update...it crashed again with the vanilla crafting table.  It isn't related to ProjectE.

**Comment by BluSunrize** [comment]
Duplicate. Please use the search function.
#1549
