### ISSUE TITLE
Bug with Refinery

### ISSUE THREAD

**Issue by Kryllyk** [BluSunrize/ImmersiveEngineering#1601]
I'm not able to automatically input fluids into the Refinery on the FTB One Server.  The Fermenter and Squeezer extract the fluids just fine, but then the fluids just disappear when attached to the Refinery.  I've tried multiple orientations and pipes to get the fluid into the Refinery.  We are currently using Immersive Engineering 0.10-44 version on the FTB Infinity 1.10.2 pack.

**Comment by galweg** [comment]
Was just about to report this also. I added Immersive Engineering 0.10-44 to Hermitpack 1.0.1 and am having the same issue.  Refinery won't accept liquid input via fluid pipes or Ender IO fluid conduits.

**Comment by BluSunrize** [comment]
Yup, known issue, see #1548 

Closed because duplicate, fixed for next released
