### ISSUE TITLE
Compile error of current code

### ISSUE THREAD

**Issue by calloatti** [BluSunrize/ImmersiveEngineering#1604]
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\ModCompatability.java:10: error: cannot find symbol
                return rf/(double)Config.getInt("euConversion");
                                        ^
  symbol:   method getInt(String)
  location: class Config
Z:\MINECRAFT\ImmersiveEngineering-master\build\sources\main\java\blusunrize\immersiveengineering\common\util\compat\ModCompatability.java:14: error: cannot find symbol
                return (int)eu*Config.getInt("euConversion");
                                     ^
  symbol:   method getInt(String)
  location: class Config
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
:compileJava FAILED

FAILURE: Build failed with an exception.

**Comment by Joshwoo70** [comment]
1. do you know how to install JDK? (and set environmental variables?
2. do you know how gradlew.bat works? (and how to use a ckmmand prompt?
if you do not know any of the following.. don't compile code.

**Comment by calloatti** [comment]
That may be it:

HTTP ERROR 404

Problem accessing /job/IC2_110/lastSuccessfulBuild/artifact/build/libs/industrialcraft-2-2.6.87-ex110-api.jar. Reason:

    Not Found

**Comment by BluSunrize** [comment]
Your git fucked up. The ModCompatability class was removed.

**Comment by Joshwoo70** [comment]
try git pull to grab the latest one

**Comment by BluSunrize** [comment]
Also, we generally don't assist with custom builds.
This is my form of version control:
If you can figure out how to build it, you can probably assist with debugging. If you can't? Yeah tough.

**Comment by calloatti** [comment]
It's not "My git"

I just download the zip, extract files, and run gradlew.bat build

And yes. "Yeah tough". As I said before, work on your general attitude towards life. Right now, being like that will not get you to far, trust me on that one.

I was also a stupid cunt when I was your age, then I grew up and learned not to be a dick to everyone. It's so much better and rewarding, believe me. You are missing on a lot of stuff.

**Comment by Joshwoo70** [comment]
being resonable... don't piss off a mod dev. They give you free content (aka mods) for you. let him be himself. doing so may incite more bad words.

**Comment by malte0811** [comment]
While I do agree that custom builds should only be done by people who know what they are doing, to "know what one is doing" is a bit of a diffuse term. When I first built IE (0.1.9) I was doing it according to instructions I found on a reddit thread about IE, but I had been writing Java code for 3-4 years. So I knew how to help with debugging and quickly learned how to do bug fixes myself, but I wouldn't have been able to do a custom build without instructions.

**Comment by BluSunrize** [comment]
Well now that I have been called a "stupid cunt", I don't really feel like assisting anymore. 
That insult was a bit uncalled for, I'd say.
Protip: Don't insult the guy who's dedicated 4 years of his life to the entertainment of the community. For free.

My "being a dick to everyone" in regards to custom builds kinda stems from the fact that some fuckwits have leaked IE back before it released. Some even uploaded it to Curse and tried to claim it as their own. Can you understand why I'm not particularly thrilled about custom builds? To add to that, those builds nigh untraceable in a crashlog and gets me issues that might make no sense to me because someone distributed their own fucked up version. I don't really need that.
