### ISSUE TITLE
[1.10.2 Help Question] Extracting Fluids From Pump

### ISSUE THREAD

**Issue by Morpheus1101** [BluSunrize/ImmersiveEngineering#1605]
I have the pump setup in the nether right above lava, i have power to it on the top via a HV cable, a lever to provide a redstone signal, 1 side set to extract and i used EIO fluid conduit to xfer lava into an EnderStorage Tank, tinkers tank, evilcraft tank, gyth tank to no fluid xer ... i also tried attaching directly to the pump with the same result, tried using the fluid pipes from IE but no connection.   I've read an re-read the engineers guide book a dozen times an not sure what it is im missing.
![mmd](https://cloud.githubusercontent.com/assets/10524952/19424810/cbcafa0a-946f-11e6-832f-3ac1091b346b.png)

**Comment by mindforger** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/1479
https://github.com/BluSunrize/ImmersiveEngineering/issues/1569
...

**Comment by Morpheus1101** [comment]
Yes that was exactly it, i moved the pump to X:80 z:1080 an it worked perfectly fine .. thankyou and apologies for no tlookin ahrder for other refrences :D
