### ISSUE TITLE
Ticking block entity - no GregTech being used

### ISSUE THREAD

**Issue by ranma862** [BluSunrize/ImmersiveEngineering#1606]
Crash report: http://pastebin.com/2Wes3axm

It's not every time, just sometimes near my windmill & LV connector to LV capacitor setup.

**Comment by malte0811** [comment]
Does this happen without Optifine?

**Comment by BluSunrize** [comment]
This is probably another NPE on the NetHandler Instance, malte. The Chunkloading issue.

**Comment by ranma862** [comment]
I'm not using Optifine.

BluSunrize, is this a known bug then?

**Comment by malte0811** [comment]
Um, line 92 of your crashlog says "FML: MCP 9.32 Powered by Forge 12.18.2.2105 Optifine OptiFine_1.10.2_HD_U_C4_pre 96 mods loaded, 96 mods active".
"Sometimes near my ... setup" does not sound like something that happens on startup to me, but INSTANCE should never be null in the next version, so this is probably fixed?

**Comment by ranma862** [comment]
...well that's super weird. I deliberately took Optifine out of my mods folder because it made the Railcraft beta blocks not render.

It's not on startup, no, it's when I connect to the server and it starts to load the world. There were two times where it loaded and I was wiring the windmill & capacitor just fine, and I logged off for a while and came back. Now, every time I try to connect to the server it's crashing during the world load.

Appreciate that the next version should have a fix though.

**Comment by malte0811** [comment]
That's what I meant by "on startup", I should have used a more definite term. It *should* be fixed in the next version, as a temporary fix logging into an empty world before logging into your "real" world  might help.

**Comment by ranma862** [comment]
Okay, good to know, thank you! While posting and poking around we fixed it with a fill command at the offending block locations, but I will try the empty-world login later.
