### ISSUE TITLE
Crusher Process Queue culpable for "Tried to read NBT tag that was too big"

### ISSUE THREAD

**Issue by codewarrior0** [BluSunrize/ImmersiveEngineering#1607]
ImmersiveEngineering-0.10-44.jar for Minecraft 1.10.2

Playing on a multiplayer server, several other players and I were suddenly disconnected with `java.lang.RuntimeException: Tried to read NBT tag that was too big; tried to allocate: 2097172bytes where max allowed: 2097152`. We saw the same error each time we tried to log in.

Investigation with MCEdit 2 showed the crusher had nearly nine thousand itemstacks in its process queue:

![image](https://cloud.githubusercontent.com/assets/307683/19428992/04602e3a-93e9-11e6-9e5c-653698aaaa85.png)

Deleting the crusher solved the problem.

**Comment by BluSunrize** [comment]
Could you please show a few more entries of that queue? It appears that the processes aren't stacking as intended.

**Comment by AEnterprise** [comment]
how is the crusher being used? had this heapen on a server once as well, turns out someone had made a dozen quarries in the mining dimension that all fed in the same crusher and that was unable to keep up (also caused alot of lag with all the quarries and chunkloading of them)

**Comment by codewarrior0** [comment]
Can't show you right now, but I remember I did open up a lot of those and all the ones I saw were `inputSize=1`.

I also remember glancing at the crusher code and seeing that the "stack" argument was set to false when calling some-function-or-another.

**Comment by codewarrior0** [comment]
Also, might be worth pointing out that the 2MB limit on reading NBT tags is new in 1.8/1.9 and never came up in 1.7, so the queue limits might need tightening.

**Comment by BluSunrize** [comment]
Found the issue. Using actual insertion (pipes, hoppers, conveyors) doesn't use the stacking feature of the queues. Only thrown in items are stacking. Fix incoming.

**Comment by AEnterprise** [comment]
well the 2MB limit to NBT isn't bad, if you are saving 2MB of data in a single NBT tag you are almost surely doing something wrong

**Comment by bookerthegeek** [comment]
@AEnterprise Ever tried to move all your base inside of A.E. drives inside of golden bags?
