### ISSUE TITLE
[1.10.2] [0.10 - 45] Crash on server start

### ISSUE THREAD

**Issue by Hastling** [BluSunrize/ImmersiveEngineering#1608]
http://pastebin.com/6b8bVGMU

**Comment by KaneHart** [comment]
Also getting this. Why also the forced bump in required forge version? Recommended in 2099.

**Comment by Hastling** [comment]
They bumped the required forge version cause in 2103 Forge started re-working the configuration system, and that config change is present in IE 0.10 - 45 as denoted byt he change log prompting you to delete the old config.

**Comment by KaneHart** [comment]
Thanks for the info. It does suck when they leap forward when you have mods that might not be able to upgrade latest forge like Sponge.

**Comment by Ommina** [comment]
My crash for the same thing: http://pastebin.com/15bVDerg  although I'm not sure it offers anything useful other than a slightly different list of mods.

Server only (client worked).  Reverting to 44 lets it start.

**Comment by Nikslg** [comment]
2104 caused crash too.

**Comment by drewbit** [comment]
Same crash, here's my log if it helps.

http://pastebin.com/yGchMvgg

**Comment by Vaerys-Dawn** [comment]
i am also experiencing this
http://pastebin.com/trKWnz8E

**Comment by mindforger** [comment]
@Ommina @Nikslg @drewbit @Vaerys-Dawn 
did you care to read what @Hastling wrote and gave it a try? Be sure to read through an issue before posting "same here" next time please

if you have already tested it and it did not work also post this information! 
It is hard to guess what you have done already when your only post content is "same here"

**Comment by drewbit** [comment]
Was a new install, Didn't even have an old config.

**Comment by mindforger** [comment]
thy :)

**Comment by juleskickflip** [comment]
Having the same issue. Here is my report: http://pastebin.com/PYziE2S3

Started working on a new server today, downloaded the latest Forge version 2107 on all my chosen mods, seems IE is the one causing the errors and not allowing my server to start. When I remove the .jar it boots up perfectly.

**Comment by BluSunrize** [comment]
I've figured out what causes the issue. Fix will come today.

**Comment by KaneHart** [comment]
Thanks for the update Blu :)

**Comment by Siigari** [comment]
Thank you!

**Comment by Hastling** [comment]
Version 0.10-46 still crashes the server.
http://pastebin.com/qeMqnFmW
