### ISSUE TITLE
[1.10.2] [0.10 build 45] mcmod.info not detected, and the ability to "Disable" and open the config for the mod is missing.

### ISSUE THREAD

**Issue by KamranMackey** [BluSunrize/ImmersiveEngineering#1610]
In the latest build of Immersive Engineering, for some reason mcmod.info is not being detected, and the buttons "Disable" and "Config" are not showing up. I was wondering if this could be fixed.

I have attached an image showing the issue.

![image](https://cloud.githubusercontent.com/assets/1617100/19462275/db5bace2-94a8-11e6-8689-0c205ce0be87.png)

**Comment by BluSunrize** [comment]
IE doesn't have an ingame config system. And right now it can't get one either, because the new config system isn't supported yet

**Comment by KamranMackey** [comment]
@BluSunrize Can the mcmod.info issue at least be fixed?
