### ISSUE TITLE
Lycanite Mobs + IE Crash

### ISSUE THREAD

**Issue by sherkas** [BluSunrize/ImmersiveEngineering#1611]
Im not 100% whose mod is causing it, but its clear the fire from the one mod is effecting the other. Hopefully you can look into it and fix it so it doesnt conflict with other mods too (and ill be posting this for lycanite to work with your mod). Im pretty sure I killed one of his mobs that spawned a shadowfire (like fire) and it of course touched a IE Connector. Other then that im not too sure.

Heres the crashlog:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  IC2core (industrialcraft-2-2.6.87-ex110.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.56-beta.jar)
  CoreMod (TickProfiler-1.10.2.jenkins.10.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.0.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
  ChiselCorePlugin (Chisel-MC1.9.4-0.0.6.53.jar)
Contact their authors BEFORE contacting forge

// I blame Dinnerbone.

Time: 10/17/16 9:04 PM
Description: Exception ticking world

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=type, clazz=class blusunrize.immersiveengineering.common.blocks.metal.BlockTypes_Connector, values=[CONNECTOR_LV, RELAY_LV, CONNECTOR_MV, RELAY_MV, CONNECTOR_HV, RELAY_HV, CONNECTOR_STRUCTURAL, TRANSFORMER, TRANSFORMER_HV, BREAKERSWITCH, REDSTONE_BREAKER, ENERGY_METER, CONNECTOR_REDSTONE]} as it does not exist in BlockStateContainer{block=shadowmobs:shadowfire, properties=[age, east, north, south, up, west]}
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196)
    at blusunrize.immersiveengineering.common.blocks.metal.BlockConnector.isSideSolid(BlockConnector.java:88)
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.isSideSolid(BlockStateContainer.java:486)
    at lycanite.lycanitesmobs.core.block.BlockFireBase.func_176196_c(BlockFireBase.java:204)
    at lycanite.lycanitesmobs.core.block.BlockFireBase.func_180650_b(BlockFireBase.java:108)
    at net.minecraft.block.Block.func_180645_a(Block.java:480)
    at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:471)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:220)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Unknown Source)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Server thread
Stacktrace:
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196)
    at blusunrize.immersiveengineering.common.blocks.metal.BlockConnector.isSideSolid(BlockConnector.java:88)
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.isSideSolid(BlockStateContainer.java:486)
    at lycanite.lycanitesmobs.core.block.BlockFireBase.func_176196_c(BlockFireBase.java:204)
    at lycanite.lycanitesmobs.core.block.BlockFireBase.func_180650_b(BlockFireBase.java:108)
    at net.minecraft.block.Block.func_180645_a(Block.java:480)
    at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:471)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:220)

-- Affected level --
Details:
    Level name: world
    All players: 0 total; []
    Chunk stats: ServerChunkCache: 118 Drop: 0
    Level seed: 1335369667001754041
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 0 game time, 0 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_101, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1274708680 bytes (1215 MB) / 2076049408 bytes (1979 MB) up to 5193859072 bytes (4953 MB)
    JVM Flags: 9 total; -Xms2048M -Xmx5124M -XX:PermSize=512M -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:+CMSClassUnloadingEnabled -XX:ParallelGCThreads=2 -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10
    IntCache: cache: 0, tcache: 0, allocated: 3, tallocated: 104
    FML: MCP 9.32 Powered by Forge 12.18.2.2105 50 mods loaded, 50 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.2.2105-universal.jar) 
    UCHIJAAAA   Forge{12.18.2.2105} [Minecraft Forge](forge-1.10.2-12.18.2.2105-universal.jar) 
    UCHIJAAAA   Aroma1997Core{${version}} [Aroma1997Core](Aroma1997Core-1.9.4-1.1.1.0.jar) 
    UCHIJAAAA   Aroma1997CoreHelper{1.1.1.0} [Aroma1997Core|Helper](Aroma1997Core-1.9.4-1.1.1.0.jar) 
    UCHIJAAAA   AromaBackup{1.0.1.1} [AromaBackup](AromaBackup-1.9.4-1.0.1.1.jar) 
    UCHIJAAAA   AromaBackupRecovery{1.0} [AromaBackup Recovery](AromaBackup-1.9.4-1.0.1.1.jar) 
    UCHIJAAAA   Baubles{1.2.1.0} [Baubles](Baubles-1.9.4-1.2.1.0.jar) 
    UCHIJAAAA   betterbuilderswands{0.6.5} [Better Builder's Wands](BetterBuildersWands-0.6.5-1.10r138+8595fc7.jar) 
    UCHIJAAAA   BiomesOPlenty{5.0.0.2068} [Biomes O' Plenty](BiomesOPlenty-1.10.2-5.0.0.2068-universal.jar) 
    UCHIJAAAA   Botania{r1.8-321} [Botania](Botania-unofficial.r1.8-321.jar) 
    UCHIJAAAA   chameleoncreepers{1.4.1} [Chameleon Creepers](chameleoncreepers-1.4.1-1.10.2.jar) 
    UCHIJAAAA   chisel{MC1.9.4-0.0.6.53} [Chisel](Chisel-MC1.9.4-0.0.6.53.jar) 
    UCHIJAAAA   endercore{1.10.2-0.4.1.56-beta} [EnderCore](EnderCore-1.10.2-0.4.1.56-beta.jar) 
    UCHIJAAAA   mantle{1.10.2-1.0.0.jenkins170} [Mantle](Mantle-1.10.2-1.0.0.jar) 
    UCHIJAAAA   tconstruct{1.10.2-2.5.6.jenkins409} [Tinkers' Construct](TConstruct-1.10.2-2.5.6.jar) 
    UCHIJAAAA   immersiveengineering{0.10-44} [Immersive Engineering](ImmersiveEngineering-0.10-44.jar) 
    UCHIJAAAA   JEI{3.12.8.323} [Just Enough Items](jei_1.10.2-3.12.8.323.jar) 
    UCHIJAAAA   Waila{1.7.0} [Waila](Waila-1.7.0-B3_1.9.4.jar) 
    UCHIJAAAA   EnderIO{1.10.2-3.0.1.120_beta} [Ender IO](EnderIO-1.10.2-3.0.1.120_beta.jar) 
    UCHIJAAAA   ExtraUtils2{1.0} [ExtraUtils2](extrautils2-1.10.2-alpha-1.1.0c.jar) 
    UCHIJAAAA   ezstorage{2.2.5} [EZStorage 2](ezstorage-2.2.5.jar) 
    UCHIJAAAA   fastleafdecay{v11} [Fast Leaf Decay](FastLeafDecay-v11.jar) 
    UCHIJAAAA   gravestone{1.5.7} [Gravestone](GraveStone Mod 1.5.7.jar) 
    UCHIJAAAA   IC2{2.6.87-ex110} [IndustrialCraft 2](industrialcraft-2-2.6.87-ex110.jar) 
    UCHIJAAAA   inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks](InventoryTweaks-1.61-58.jar) 
    UCHIJAAAA   journeymap{1.10.2-5.2.4} [JourneyMap](journeymap-1.10.2-5.2.4-unlimited.jar) 
    UCHIJAAAA   lycanitesmobs{1.15.1.4 - MC 1.10.2} [Lycanites Mobs](LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
    UCHIJAAAA   arcticmobs{1.15.1.4 - MC 1.10.2} [Lycanites Arctic Mobs](LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
    UCHIJAAAA   demonmobs{1.15.1.4 - MC 1.10.2} [Lycanites Demon Mobs](LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
    UCHIJAAAA   desertmobs{1.15.1.4 - MC 1.10.2} [Lycanites Desert Mobs](LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
    UCHIJAAAA   forestmobs{1.15.1.4 - MC 1.10.2} [Lycanites Forest Mobs](LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
    UCHIJAAAA   freshwatermobs{1.15.1.4 - MC 1.10.2} [Lycanites Freshwater Mobs](LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
    UCHIJAAAA   infernomobs{1.15.1.4 - MC 1.10.2} [Lycanites Inferno Mobs](LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
    UCHIJAAAA   junglemobs{1.15.1.4 - MC 1.10.2} [Lycanites Jungle Mobs](LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
    UCHIJAAAA   mountainmobs{1.15.1.4 - MC 1.10.2} [Lycanites Mountain Mobs](LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
    UCHIJAAAA   plainsmobs{1.15.1.4 - MC 1.10.2} [Lycanites Plains Mobs](LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
    UCHIJAAAA   saltwatermobs{1.15.1.4 - MC 1.10.2} [Lycanites Saltwater Mobs](LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
    UCHIJAAAA   shadowmobs{1.15.1.4 - MC 1.10.2} [Lycanites Shadow Mobs](LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
    UCHIJAAAA   swampmobs{1.15.1.4 - MC 1.10.2} [Lycanites Swamp Mobs](LycanitesMobsComplete 1.15.1.4 [1.10.2].jar) 
    UCHIJAAAA   mcmultipart{1.2.1} [MCMultiPart](MCMultiPart-1.2.1-universal.jar) 
    UCHIJAAAA   oretweaker{1.0.2-1.10.2} [Ore Tweaker](OreTweaker-1.0.2-1.10.2.jar) 
    UCHIJAAAA   harvestcraft{1.9.4-1.10.2f} [Pam's HarvestCraft](Pam's HarvestCraft 1.9.4-1.10.2f.jar) 
    UCHIJAAAA   refinedstorage{1.1.3} [Refined Storage](refinedstorage-1.1.3.jar) 
    UCHIJAAAA   rftools{5.54} [RFTools](rftools-1.10-5.54.jar) 
    UCHIJAAAA   rftoolsdim{4.43} [RFTools Dimensions](rftoolsdim-1.10-4.43.jar) 
    UCHIJAAAA   Roguelike{1.5.4} [Roguelike Dungeons](RoguelikeDungeons-1.10.2-1.5.4.jar) 
    UCHIJAAAA   TickProfiler{1.10.2.jenkins.10} [TickProfiler](TickProfiler-1.10.2.jenkins.10.jar) 
    UCHIJAAAA   UnifiedItems{1.3.2.54} [Unified Items](UnifiedItems-1.10.2-1.3.2-54.jar) 
    UCHIJAAAA   UniDict{1.10.2-2.3b} [UniDict](UniDict-1.10.2-2.3b.jar) 
    Loaded coremods (and transformers): 
IC2core (industrialcraft-2-2.6.87-ex110.jar)

EnderCorePlugin (EnderCore-1.10.2-0.4.1.56-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
CoreMod (TickProfiler-1.10.2.jenkins.10.jar)

CoreMod (Aroma1997Core-1.9.4-1.1.1.0.jar)

FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
ChiselCorePlugin (Chisel-MC1.9.4-0.0.6.53.jar)
  team.chisel.common.asm.ChiselTransformer
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerHarvestTools (Enabled/Forced)
        - TinkerMeleeWeapons (Enabled/Forced)
        - TinkerRangedWeapons (Enabled/Forced)
        - TinkerModifiers (Enabled/Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - TinkerModelRegister (Enabled/Forced)
        - WailaIntegration (Enabled/Not Forced)

```
EnderIO: No known problems detected.
Detailed RF API diagnostics:
              * RF API class 'EnergyStorage' is loaded from: jar:file:/C:/Minecraft110server/mods/mcjtylib-1.10-2.1.4.jar!/cofh/api/energy/EnergyStorage.class
              * RF API class 'IEnergyConnection' is loaded from: jar:file:/C:/Minecraft110server/mods/mcjtylib-1.10-2.1.4.jar!/cofh/api/energy/IEnergyConnection.class
              * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/C:/Minecraft110server/mods/mcjtylib-1.10-2.1.4.jar!/cofh/api/energy/IEnergyContainerItem.class
              * RF API class 'IEnergyHandler' is loaded from: jar:file:/C:/Minecraft110server/mods/mcjtylib-1.10-2.1.4.jar!/cofh/api/energy/IEnergyHandler.class
              * RF API class 'IEnergyProvider' is loaded from: jar:file:/C:/Minecraft110server/mods/mcjtylib-1.10-2.1.4.jar!/cofh/api/energy/IEnergyProvider.class
              * RF API class 'IEnergyReceiver' is loaded from: jar:file:/C:/Minecraft110server/mods/mcjtylib-1.10-2.1.4.jar!/cofh/api/energy/IEnergyReceiver.class
              * RF API class 'IEnergyStorage' is loaded from: jar:file:/C:/Minecraft110server/mods/mcjtylib-1.10-2.1.4.jar!/cofh/api/energy/IEnergyStorage.class
              * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/C:/Minecraft110server/mods/mcjtylib-1.10-2.1.4.jar!/cofh/api/energy/ItemEnergyContainer.class
              * RF API class 'TileEnergyHandler' is loaded from: jar:file:/C:/Minecraft110server/mods/mcjtylib-1.10-2.1.4.jar!/cofh/api/energy/TileEnergyHandler.class
Detailed Tesla API diagnostics:
              * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
              * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
              * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
              * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
              * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
              * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
              * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
              * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
              * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
              * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
              * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

Profiler Position: N/A (disabled)
Player Count: 0 / 20; []
Is Modded: Definitely; Server brand changed to 'fml,forge'
Type: Dedicated Server (map_server.txt)
```

**Comment by mindforger** [comment]
just a guess

block=shadowmobs:shadowfire

the log seems to show a block(a connector) went up in fire or something while IE was accessing it

maybe a weak check somewhere in the code but also possible that you have a world corruption
