### ISSUE TITLE
Latest version of IE causing crash on server (crash log attached)

### ISSUE THREAD

**Issue by Vaerys-Dawn** [BluSunrize/ImmersiveEngineering#1612]
http://pastebin.com/trKWnz8E

**Comment by KamranMackey** [comment]
@Vaerys-Dawn Damn that is an old machine. Linux 2.6.32 and Java 8 update 5....you should update it :D

**Comment by mindforger** [comment]
what the heck, this is a creeper.host ... are they serious?

**Comment by BluSunrize** [comment]
VPS updates usually don't happen that often. As long as it runs, there is no point to update it =P
This might very well be a server they have had since ~2014.
