### ISSUE TITLE
No power transfer between generators to capacitors ( or any machine ) 

### ISSUE THREAD

**Issue by licbris** [BluSunrize/ImmersiveEngineering#1613]
Hi, is there some list of non-compatible mods for immersive engineering? I tried everything to make it work on my mod pack, and still doesn't work... hope you can help. 

 

The specific problem is that energy doesn't transfer from any type of generator to capacitors or directly to the machines 

 

Multiblock structures generate work... Like ovens and machines ( creative )  but there is no way to make them work or do what there are suppose to do. 

1.7.10
I tried with and without optifine.

**Comment by BluSunrize** [comment]
Could you please provide detailed examples and screenshots?

**Comment by JVanhook** [comment]
im having the same problem i have water wheels that worked before that now put out 0 power to enderio capacitor, diesel generator doesnt seem to run at all which could be tied to this bug

**Comment by licbris** [comment]
https://imgur.com/gallery/IZLmv

Here are some test i do on different machines and yet no power ( electricity made) I suppose is cuz an incompatibility on mods.  If it is, could you be so kind to see wich one. Thanks you so much!

**Comment by licbris** [comment]
I found the incompatible mod.
Is the geoactivity mod... hope you can find a way to make it compatible.

**Comment by BluSunrize** [comment]
Well, 1.7.10 isn't really receiving support anymore. Also: that's not how you take Screenshots. You don't take photos of the monitor. You can just press F2 in minecraft .-.

**Comment by mindforger** [comment]
What I understand is an Issue with EnderIO, this is well known and the simplest fix **in most cases** is to ALWAYS setup the flow direction of power when exchangeing power with EIO!

EIO has an internal capacitor equalization function, when you only have EIO Caps and Cables, they share all the same amount of power through all caps

but when there is another mod not capable of providing the required info, the power starts oscilating or does not flow at all! So defining the flow direction always helps

**Comment by TheBlueTroll** [comment]
Umm what's with the talk about enderio? Its already stated that the normal wires are the one not working, due to a bug with geoactivity mod.

**Comment by mindforger** [comment]
I was just generally hinting in this context that before blaming mod interactions there should always be care taken to ensure you have no power loops and undefined flow directions! (mostly about what JVanhook wrote)

Also "the normal wires are the one not working" don't you think it is possible that one of the receiving ends behind the wire could possibly have an issue with how they work?

Just try a very simple setup, 2 EIO Capacitors, 1 full and 1 empty, put IE connectors and wires between them and do NOT define the flow direction, set it to auto ... now you have a wonderful energy swing, once the full capacitor drained into the formerly empty one, the power flow reverses until the cable loss eaten up all RF

**Comment by TheBlueTroll** [comment]
The point I'm making is that this is a issue where NONE of the wire systems work at all, enderIO isn't even installed, and your talking about something that quite frankly doesn't matter in the context of this issue. Great, I'll be sure to set flow on EIO conduits, but it not only doesn't solve the issue, it also doesn't help the issue. 
You did look at the screenshots he provided right?

**Comment by mindforger** [comment]
and your two posts until yet have helped way less than mine they just started an argument

PS read to which post I related and now see it in this context: people use search, find this topic because it matches their "power transfer issue" search, and there is an advice to check if everything is setup correctly before reporting their issue ... i wrote an advice, you just started an argument

**Comment by mindforger** [comment]
i removed my comments before this escalates, you seem to have something against a good meant hint to check your power setup for possible power loops and undefined flow behaviour

**Comment by TheBlueTroll** [comment]
I was asking for clarification as to why you felt it necessary to start talking about EIO when it doesn't matter, that sort of stuff is what forums are for, not the issue tracker of a mod.

on the other side, i do confirm that GeoActivity does cause the power system to break, and for me the voltmeter to break,and upon removal of GeoActivity the power system and voltmeter start working correctly again on 1.7.10.
mods : 
- Geoactivity 1.6 for 1.7.10
- Immersive Engineering 0.7.7 for 1.7.10
- Nei 1.0.5.120 for 1.7.10
- CodeChickenCore 1.0.7.47 for 1.7.10

To be clear to anyone in the future/google GeoAvtivity breaks IE on Minecraft 1.7.10

 So @BluSunrize you can go ahead and "wont fix" and "close" this issue

**Comment by TheBlueTroll** [comment]
"What I understand is an Issue with EnderIO, this is well known and the simplest fix in most cases is to ALWAYS setup the flow direction of power when exchangeing power with EIO!"

my problem is that this is basically you saying the issue is Enderio, and regardless of how you think it sounds, to other people it sounds like the fix for this issue is screwing with EIO, which more then likely ends up with more issues on the EIO error tracker and here.
 advice is for forums, not a issue tracker.

**Comment by licbris** [comment]
Sorry for the "screenshots; btw great answer blue troll

**Comment by mindforger** [comment]
>my problem is that this is basically you saying the issue is Enderio, and regardless of how you think it sounds, to other people it sounds like the fix for this issue is screwing with EIO, which more then likely ends up with more issues on the EIO error tracker and here.
advice is for forums, not a issue tracker.

oh come on, i told you i was referring to the post of JVanhook and calling out EIO was just a popular example of how "features" can misbehave, i was just **HINTING** to check power flow with EIO as an god damn example, why do you have to engage this shit again and again you are very provoking
