### ISSUE TITLE
Mulitplayer disconnect issue - IE-0.10.47

### ISSUE THREAD

**Issue by RyanP1991** [BluSunrize/ImmersiveEngineering#1615]
Forge Version - 12.18.2.2107 (latest one)
Immersive Engineering Version - 0.10.47 (latest one)

I have just updated my custom pack for 1.10.2 (https://minecraft.curseforge.com/projects/the-ryrypatpatpackpack-1-10-2)

All players joining multiplayer are all reporting the following issue:

Internal Exception: io.netty.handler.codec.DecoderException: The received string length is longer than maximum allowed (23 > 20)

**Comment by InsomniaKitten** [comment]
May I ask why you closed this issue? Because I'm also having the same problem with my modpack after updating some mods including IE. It may be coincidence but I'm still curious.

**Comment by RyanP1991** [comment]
I closed this issue because I automatically assumed it was immersive engineering causing the issue but even though I rolled IE back the issue still persisted so I will slowly update miss and see which one is causing the issue.

**Comment by mindforger** [comment]
sounds like an item with too large NBT, something like a golden bag of holding inside a crate inside a golden bag of holding... for example

i assume someone thought it might be a nice idea to stuff large inventorys into each other

**Comment by BluSunrize** [comment]
I'd like to see a full log on that, really. Because just that one line really doesn't help :/

**Comment by RyanP1991** [comment]
Mindforger I thought that too but everyone had just started the map.

Is there any particular file that this error will be outputted to?

**Comment by InsomniaKitten** [comment]
I'm not entirely sure that it's IE causing the issue, but then again it's really hard to tell with this kind of stuff. Here's a log of me connecting to my server anyway, as requested, @BluSunrize. Weirdly, at the end of the log, it doesn't say anything about a disconnection. It just continues to load stuff as normal, but once it gets to that point at the end of the file, my screen is showing the dirt background with the Internal Exception message as mentioned above. I'm working on debugging my pack now to figure out what might be causing it. @RyanP1991 since you are also having this issue, please keep me updated on your progress of finding the source of the issue, it'll help solve this faster.

[hastebin.com/raw/agilexoxel](http://hastebin.com/raw/agilexoxel)

**Comment by AEnterprise** [comment]
looks like there is a missmatch of mods and/or version on the client and server, the client is receiving packets from the server with non existant id's and mismatched id's, the data ends up at the wrong handler due to that it reads to much or not enough data causing this

**Comment by mindforger** [comment]
kind of looks like a broken package while syncing configs 

[tconstruct-Config]: Syncing Config with Server
right before the first one

and a secondary more big explosion with EIO
[EnderCore]: Reset configs to client values for com.enderio.core.common.config.ConfigHandler
but this may just be a random line while printing the exception

**Comment by InsomniaKitten** [comment]
I just want to clarify that I don't have Ender IO, just Ender Core itself. As for Tinkers' Construct.. Maybe recent changes in the mod are causing issues with existing tools and materials in the world, I'll take a look into it.

**Comment by mindforger** [comment]
sorry I meant EnderCore but writing EIO is a habit :P

**Comment by InsomniaKitten** [comment]
Rolling back to version [0.2.0](https://minecraft.curseforge.com/projects/tinkers-tool-leveling/files/2333049) of Tinker Tool Leveling resolved the issue. Something with the new config syncing feature is causing this issue I'm guessing.

**Comment by InsomniaKitten** [comment]
The issue has also been brought up on the GitHub for the mod recently. 
https://github.com/SlimeKnights/TinkersToolLeveling/issues/12
Any further discussion should probably be done over there.

**Comment by RyanP1991** [comment]
Apologize for not being here to assist you guys, just got home from work, but seems you managed to find the issue, thank you for help InsomniaKitten and you all.
