### ISSUE TITLE
UI design - Liquid Amount in Displays

### ISSUE THREAD

**Issue by mDiyo** [BluSunrize/ImmersiveEngineering#1616]
Liquid amounts display in a very small amount. Buckets are generally used for operations or as comparison. A "mB" of any liquid is so small that it would never be used for anything that consumes a set amount of liquid such as making treated wood.

Additionally, the unit type is hardcoded and cannot be changed via lang file. https://github.com/BluSunrize/ImmersiveEngineering/blob/5b779f3269cbb84f23907c12e5ecc65eced89cf4/src/main/java/blusunrize/immersiveengineering/client/ClientUtils.java#L1264

**Comment by mindforger** [comment]
>A "mB" of any liquid is so small that it would never be used for anything that consumes a set amount of liquid such as making treated wood

have you seen the recipes for biodiesel ? 8mb+8mb = 16mb 

what, besides your point with the hard coded type would you change? what alternative display would you choose? By the way every other mod uses mB as unit besides tinkers calculating ingots and nuggets whenit is an castable liquid

**Comment by BluSunrize** [comment]
Hai Diyo 
Thought you were still on 1.5.2 because of Magic Maiden? =P 
I thought millibucket was a quite "known" unit. While I'm not against the idea of making the unit changeable in the lang file, I don't know of any other mod that does so.
As for using a bigger unit: I'd rather not. As mindforger said, the recipes produce small quantities. I could look into formatting the tooltip to show full buckets if mB count goes over 1000

**Comment by mDiyo** [comment]
Magic Maiden is 1.6.4 :P I've been playing 1.10.2 for some time.

mB being a common unit does not make it the right unit to display all the time. In the coke oven, there's a slot for a bucket on the side. It would make more sense to display units in the amount of buckets you can get out of the oven than how many individual drops you have.

Tinkers' Construct displays its molten metals as ingot amounts, then as nuggets, then whatever is left over. I'm sure you could do something like this: https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/library/client/GuiUtil.java#L206

Regarding biodiesel: The combination of two liquids into another could just as easily be tiny or full buckets. That's less about what you can do with them and more that you're mixing two things.

**Comment by SpazzMods** [comment]
It's like the US using Imperial and everywhere else using Metric, in this case, the Mod uses the Metric, common, liquid display. And you are the United States. It's too common, and extremely easy to convert.
500 = 1/2 bucket
1000 = 1 bucket

I'll agree, it'd be nice to see "1 Bucket" But at least with the mB it's keeping with the 'metric' volume measurement all other mods use.
