### ISSUE TITLE
Jerry can problem with tank

### ISSUE THREAD

**Issue by James-T-Oudvoure** [BluSunrize/ImmersiveEngineering#1617]
Using the current version (0.10-47), the jerry can behaves bizarrely with the fluid tank. Whenever you take liquid from a tank containing, lets say, 30,000mb, it takes 10,000mb as usual, leaving 20,000. However, when I put that liquid back in, it puts 10,000mb back into the tank, but leaves 9000mb in the can. Additionally, whenever I use the jerry can on a tank, it places a fluid source block where I right clicked.

**Comment by mindforger** [comment]
legacy bucket code ?

**Comment by BluSunrize** [comment]
What tank are you using it on?

**Comment by James-T-Oudvoure** [comment]
Just the normal IE metal tank multiblock. As far as I know, it works perfectly fine with both single block barrels.

**Comment by BluSunrize** [comment]
I have been unable to reproduce this.

Which fluid specifically was this?
Also, were you in creative mode at the time?

**Comment by James-T-Oudvoure** [comment]
All fluids.
And no, I wasn't in creative, if I was, it would just take fluid away when I right clicked.
