### ISSUE TITLE
[1.10.2 -- IE v47] Config lacks comments (except for compat booleans)

### ISSUE THREAD

**Issue by ElvenChaos** [BluSunrize/ImmersiveEngineering#1618]
The ore generation section of the config isn't documented, which order are the values in?
Snippet from config: http://pastebin.com/uVxFRQuB
IE 47

**Comment by KaneHart** [comment]
Now is that Oregen? because there is another that says oregen. 

oregen {

**Comment by ElvenChaos** [comment]
I don't see such an entry, and I'm pretty sure this section is listen ore density, min and max height values, variation, etc. I just want to make sure I know exactly which values I'm changing :X Also, IE 45 overhauled its config to a new system, are you sure you aren't on an old config? If you are on an old config and you have the values described to you, mind posting them? :D

Current IE 47 Full Config: http://pastebin.com/U63Rvz5x

**Comment by KaneHart** [comment]
I'm an idiot I needed to regen my config :)

**Comment by ElvenChaos** [comment]
I just realized I could dig around in the source code, so I tried to find the world gen in it, and via "public OreGen(String name, IBlockState state, int maxVeinSize, Block replaceTarget, int minY, int maxY,int chunkOccurence, int weight)"

I would think the 5 fields are:
Max Size
Min Height
Max Height
Chunk Occur. (Tries per chunk)
Weight (if less than 100, becomes % chance per try)

But I'm just guesstimating.

**Comment by BluSunrize** [comment]
If you regen a new config, the ore stuff should all have comments on it

**Comment by BluSunrize** [comment]
I might have spoken a bit early there. It appears that somehow comments get lost. I assume that's due to me usigng the "old" config system as well in order to load the config parts for compatability (since I can'T easily do those staticly)

**Comment by BluSunrize** [comment]
I took the liberty to rename this, and I'll try to address it today. This doesn't really warrant another build, but it definitely needs to be fixed.

**Comment by ElvenChaos** [comment]
Thank you! In the mean time, is the order of the oregen variable I listed earlier correct? I can work on stuff from there.

**Comment by BluSunrize** [comment]
Yeah, it's
Vein size, lowest possible Y, highest possible Y, veins per chunk, chance for vein to spawn (out of 100)

Setting VeinSize to 0 disables generation.
