### ISSUE TITLE
required version of forge

### ISSUE THREAD

**Issue by Napkin** [BluSunrize/ImmersiveEngineering#1619]
Hi there, wouldn't latest recommended version of forge (12.18.2.2099) be enough instead of unstable (12.18.2.2104)?

> [21:35:56] [Server thread/ERROR]: Encountered an unexpected exception
> net.minecraftforge.fml.common.MissingModsException: Mod immersiveengineering (Immersive Engineering) requires [Forge@[12.18.2.2104,]]
> Missing Mods:
>         Forge : [12.18.2.2104,] 

Thanks!

**Comment by BluSunrize** [comment]
Nope. 2104 is required due to the new Forge Config system.
