### ISSUE TITLE
Rendering Issue with Decorative Coils

### ISSUE THREAD

**Issue by porteriscool** [BluSunrize/ImmersiveEngineering#162]
When facing north, I have a problem in which I can't see the hemp rope coil, however, when facing south, I see the hemp coils perfectly fine. If any more information needed, please ask. By the way. I am currently running v. 0.3.3.
![2015-07-02_13 09 53](https://cloud.githubusercontent.com/assets/12450943/8483087/13e11b0e-20bc-11e5-9583-948b277b1bad.png)
![2015-07-02_13 10 01](https://cloud.githubusercontent.com/assets/12450943/8483088/14c7fed4-20bc-11e5-8729-0cf96ea9d65a.png)

**Comment by BluSunrize** [comment]
I can't reproduce this one :/
Could you try it in a test world without the AE stuff and enderchest and things? Just the corridor+wires?

**Comment by porteriscool** [comment]
Can't reproduce it either in a single player test world. Seems to be a bug on another mods part that causes the rendering issue. Will see what mod causes it and report back. Might take some time though considering I have "124" mods installed.

**Comment by BluSunrize** [comment]
somethign else hooking into rendering and not resetting translations or something .~.

**Comment by porteriscool** [comment]
Yeah seems like that might be the case.
