### ISSUE TITLE
Server crashes when placing breakers, likely introduced in recent commit

### ISSUE THREAD

**Issue by tubofbutter** [BluSunrize/ImmersiveEngineering#1620]
Forge version 1.10.2 - 12.18.2.2107
IE version 0.10-47
No other server mods were used
Empty superflat world

Steps to reproduce:
1. Start the Forge server.
2. Join and place a Breaker Switch or Redstone Breaker.
3. Server errors until it finally stops. https://bpaste.net/show/ae87b8ea8879

IE 0.10-44 does **NOT** crash when placing breakers, commit malte0811@71726df67d9d0cad692564cdc379c8851f2826d5 is probably to blame.

**Comment by malte0811** [comment]
I know, should be fixed by malte0811@f2a07c6642ee89d7080cd1f1d5326e06b0db4dd1

**Comment by tubofbutter** [comment]
Thanks! Looking forward to the build.

**Comment by iPencil** [comment]
Also looking forward to that build! Server is currently unplayable. Will probably have to downgrade :(

**Comment by KaneHart** [comment]
Also looking for the build.

**Comment by BluSunrize** [comment]
Haven't had a lot of time to do IE stuff over the past few days. Most I did was a little bit of chisel support. Build is planned for sunday or monday.

**Comment by gdude2002** [comment]
As I'm running on a production server, I couldn't wait for the build, so I compiled one myself. 

I can confirm that this problem is fixed.
