### ISSUE TITLE
Gunpowder barrel

### ISSUE THREAD

**Issue by James-T-Oudvoure** [BluSunrize/ImmersiveEngineering#1624]
When the gunpowder barrel explodes, it makes no noise. Also, no matter what triggers a gunpowder barrel to explode, it will always countdown, unlike TNT which explodes if triggered by another explosion.

**Comment by James-T-Oudvoure** [comment]
This is also present in version 0.10-48.

**Comment by WesCook** [comment]
Semi-related, but the gunpowder barrel in general could use a buff, I think.  The explosion radius seems equal to that of regular TNT, and it doesn't chain together as well either.  A 3x3x3 of TNT is a larger explosion than a 3x3x3 of Gunpowder Barrels.

**Comment by BluSunrize** [comment]
Well, it's designed for mining, as it keeps 100% of the drops. Having it be less powerful+applicable than normal TNT seems like an adequate balance to that...
