### ISSUE TITLE
Conveyors with metal press next to them don't have the open side

### ISSUE THREAD

**Issue by The-Fireplace** [BluSunrize/ImmersiveEngineering#1626]
![2016-10-22_14 17 18](https://cloud.githubusercontent.com/assets/5914284/19621922/cb83e98e-9862-11e6-92c8-e653c50a9df1.png)
That metal barrier shouldn't be there when it has the machine there.

**Comment by BluSunrize** [comment]
That's quite hard to detect since MetalPress isn't really a conveyor block.
I'll look into it, but it's very low priority, and effectively requires special casing and possibly core references in the API (don't quite remember my own code for this)

**Comment by AEnterprise** [comment]
maybe an IConveyerConnector interface that they can implement? that could take a pos and side argument to do a check if it should connect or not

**Comment by BluSunrize** [comment]
Yeah, I'll look into adding that.

**Comment by Doragoon01** [comment]
Just a reminder, the assembler has the same problem
