### ISSUE TITLE
Negative RF Transmission?

### ISSUE THREAD

**Issue by lamialily** [BluSunrize/ImmersiveEngineering#163]
I've been messing around with Immersive Engineering to see if the node-based power transmission would function across unloaded chunks (in case nodes were cached), but I found rather the opposite issue -- at large distances (enough for the voltmeter to read 100.00 or more RF losses, whether or not all chunks along the way are loaded), the voltmeter reports that capacitors pulling power from the lines are going into the negatives, and in cross-mod interactions, WAILA reports likewise on other RF-accepting blocks. Sanity checks seem to reset the value to 0 every time the world's saved, though.

I've tested this in a sandbox with bare-minimum equipment necessary to test -- IE (of course), Railcraft for a chunkloader, Thermal Expansion for a creative energy cell, NEI for chunk guidelines during assembly.

Addendum: Was the RF losses read by the voltmeter meant to be represented in percentages?

**Comment by BluSunrize** [comment]
yeah, the localization on them is derped. as for negative throughput: will investigate, thanks .~.
