### ISSUE TITLE
Ear Defenders not actually blocking sound(0.10-47)

### ISSUE THREAD

**Issue by Lumindia** [BluSunrize/ImmersiveEngineering#1630]
The Ear Defenders don't seem to be muffling any sounds at all once configured in the engineer's worktable. I've tried various configurations of noise gates + tickboxes, the volume still sounds the same.

**Comment by BluSunrize** [comment]
Oh come on Lumin. You know better than this. Version numbers, screenshots, etc =P

**Comment by Lumindia** [comment]
the version number is in the issue name, and it's kind of hard to take pictures of a sound related issue.

**Comment by ArukaAlter** [comment]
The screenshot required is of the configuration of the Ear Defenders when put in the Engineering Workbench.

**Comment by Lumindia** [comment]
http://puu.sh/rSN4m/f709f9f69c.jpg
http://puu.sh/rSN7Q/a8a5f01546.jpg
http://puu.sh/rSN8h/18944c80ab.jpg
http://puu.sh/rSN8A/b04a1e7bfa.jpg

Which of these configurations SHOULD be blocking out all sound? None of them work.

**Comment by malte0811** [comment]
Happens in my dev environment as well, I'll look into it.
