### ISSUE TITLE
server crash

### ISSUE THREAD

**Issue by CookieHunteRRR** [BluSunrize/ImmersiveEngineering#1631]
https://gist.github.com/CookieHunteRRR/1d0abe28f56cd483bb15339bae6b1157
i'm just launched a server and this happened
it happening every time i'm launching the server
i'm launched the forge 2107 server

**Comment by BluSunrize** [comment]
...wut.
Looks like the creosote somehow winds up being null...

can you reproduce this without Gregtech?

**Comment by CookieHunteRRR** [comment]
Ok, i'll try

**Comment by CookieHunteRRR** [comment]
Well, i'm deleted greg and this problem gone
