### ISSUE TITLE
[1.10.2][Bug]Mt added ore vein is detected, but not mined

### ISSUE THREAD

**Issue by iPencil** [BluSunrize/ImmersiveEngineering#1632]
1.10.2, Forge 2107, IE 0.10 - 47:

I've added a vein containing both Deep Resonance and RFTools ore via minetweaker:
http://i.imgur.com/eYZJEVE.png
It has roughly the same rarity as Plat, spawns in the overworld and gives 95% DR ore and 5% dim shards.

The vein is also correctly detected by the manual:
http://i.imgur.com/rwfZZMc.png

One of my players has managed to find the vein on the map:
http://i.imgur.com/0N6EOHV.png

As you can see, the machine and the ore drill are in the same chunk:
http://i.imgur.com/4MSfUow.jpg
(Mind you this user has about 7 excavators running atm, he knows how to set one up properly)

When assembling and powering the excavator, it starts digging up soil and then just runs without bringing anything up:
http://i.imgur.com/J6eDmUo.png

We've tried rebuilding it twice, restarted the server, gave it unlimited power, tweaked a few values on the MT script, nothing.

I can provide more information if needed :)
Thank you

**Comment by BluSunrize** [comment]
Is it actually not producing ore, or is it just rendering as empty?

**Comment by iPencil** [comment]
Oh sorry I wasn't clear on that. It is not producing any ore, the buckets are spinning but no ore is mined.

**Comment by malte0811** [comment]
The chances aren't in percent, they are relative to 1. So the command should be
`mods.immersiveengineering.Excavator.addMineral("Resonating", 5, 0.05, ["oreResonating", "oreDimensional"], [0.95, 0.05], [0]);`
(Only necessary for the fail chance, the mineral chances are scaled properly, but it gives more exact results if you scale it to one yourself)
It works for me with those chances.

**Comment by iPencil** [comment]
@malte0811 

Okay I've changed it to what you have said, the mt wiki might be outdated. it's now


`mods.immersiveengineering.Excavator.addMineral("Resonating", 5, 0.15, ["oreResonating", "oreDimensional"], [0.95, 0.05], [0);`


However it's still not producing anything for me :/
I've restarted the server twice, done another ore drill just to be sure, machine is still in the same chunk. Broke the machine a few times. Rebuilt the entire thing. Bucket still come up empty :/

**Comment by iPencil** [comment]
Okay, I've tried this in single player now. Set the weight absurdly high (500) so I instantly found one. Fresh map, all the settings as u had them. Setup the miner, it starts mining the dirt and grass, then empty buckets. :(

Btw, I've also updated minetweaker from CraftTweaker-1.10.2-3.0.12 to CraftTweaker-1.10.2-3.0.13 just in case that matters.

**Comment by BluSunrize** [comment]
Alright, I just tried this:
`Excavator.addMineral("Testite", 500, 0.1, ["oreDiamond","oreEmerald"], [0.75, 0.25]);`

Went into my test world, looked around for a bit, found a natural vein, set up the miner, and got Diamond and Emerald ores.

@iPencil could you try replacing oreResonating and oreDimension with Diamond and Emerald? Just to check if it's the output products?
Also, see what happens if you don't use the dimension array.

**Comment by malte0811** [comment]
@iPencil your dimension array is missing the closing square bracket, I don't know how MT reacts to that. Otherwise the command looks like what I used yesterday (It is still necessary to add the dimensional shard ore to the oredict, so don't remove that part of the script).

**Comment by iPencil** [comment]
@malte0811 
Sorry that seems to be a typo on here exclusively. 
The first screenshot and my script both have the closing bracket:

`mods.immersiveengineering.Excavator.addMineral("Resonating", 5, 0.15, ["oreResonating", "oreDimensional"], [0.95, 0.05], [0], false);`

I will try all your suggestions in a minute, might be that the MT wiki is outdated and I'll leave out the boolean at the end. I've tried to use dirt & stone before but that also didn't work. I'll give it another shot!

**Comment by iPencil** [comment]
Alright, thanks @BluSunrize I left out the dimension ID entirely and it worked in single player! When I tried it in MP it initially didn't work, but after another drilling it seems like the constant mt script switching messed up the yield as it was showing as -1. Manually set yield with /ie mineral command and now it's producing ore! Thanks alot both of you for the help :)
