### ISSUE TITLE
ToDo: Add an offset/partial texture system to Item Shaders

### ISSUE THREAD

**Issue by mezz** [BluSunrize/ImmersiveEngineering#1634]
All these are big blank textures for me:
immersiveengineering:revolvers/shaders/revolver_sponsor
immersiveengineering:items/shaders/chemthrower_sponsor
immersiveengineering:items/shaders/drill_diesel_sponsor
immersiveengineering:items/shaders/railgun_sponsor

You can investigate for yourself using the newly released TextureDump mod:
https://github.com/mezz/TextureDump

<3

**Comment by BluSunrize** [comment]
come on mezz, at least show me the sheet <3

**Comment by BluSunrize** [comment]
Keeping this open as a reminder btw.
Fry's idea of using offset specifications isn't bad, but not as easily applicable as it sounds. Will have to mull this over and come up with a good design.

Refurbishing this into a ToDo: Add offset and partial textures to Shader system.

**Comment by BluSunrize** [comment]
Shader Commit has happened, see
https://github.com/BluSunrize/ImmersiveEngineering/commit/da596e593c3ea28ae35c50ff2dad6baf1fd10471
https://github.com/BluSunrize/ImmersiveEngineering/commit/e449629ffd52329b55ee681a1c07f29c68aabb56
https://github.com/BluSunrize/ImmersiveEngineering/commit/267cf97eb74843702490162401dd4f84c0787353
https://github.com/BluSunrize/ImmersiveEngineering/commit/a5d513fefee97aeaa102461e1bdfbcf46eae77ae
https://github.com/BluSunrize/ImmersiveEngineering/commit/6249cb9077ff4a8cd3904b594cf36762091dc8c4

Issue resolved.

**Comment by mezz** [comment]
Fancy! Looks really cool Blu.
