### ISSUE TITLE
Railgun ammo

### ISSUE THREAD

**Issue by Doragoon01** [BluSunrize/ImmersiveEngineering#1636]
The railgun only uses metal rods from immersive engineering.  It doesn't use iron and steel sticks from other mods in the ore dictionary.

**Comment by kane-thornwyrd** [comment]
Also @Doragoon01 in which version of MC/IE ?

**Comment by Doragoon01** [comment]
In my case, BaseMetals.
I'm sorry, I'd assumed more mods added iron rods/sticks than actually do. (OT:Is tinkers the only other mod with metal sticks?)  The sticks were ore dictionary-ed and work in all the IE recipes so i assumed they would work with the railgun until they didn't.
Once again, I'm sorry.  I'd assumed this was just an oversight.  Since this problem is unique to my modpack (and is a simple fix in my case), I can just change everything over to your rods.

Anyways, thank you for everything.

**Comment by BluSunrize** [comment]
well, I know that TCon's toolrods aren't OreDicted in 1,10 anymore.
I'll look into why BaseMetals won't work
