### ISSUE TITLE
Squeezer Auto-Output Broken?

### ISSUE THREAD

**Issue by robotbrain** [BluSunrize/ImmersiveEngineering#1637]
https://imgur.com/a/SLh2k

**Comment by kane-thornwyrd** [comment]
[Please read the guidelines for contributing :smile: 
![screenshot_28](https://cloud.githubusercontent.com/assets/625236/17993707/6aa47b84-6b52-11e6-9a9d-ef5d6e05a4ca.png)
](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/CONTRIBUTING.md)

**Comment by Joshwoo70** [comment]
it is kinda clear from the image where blu needs to fix.. even though he didn't follow the guidelines..

**Comment by kane-thornwyrd** [comment]
@Joshwoo70 I agree,
but it's crucial to have all the relevant informations at hand than having to engage in conjectures given the little few hints from 2 screenshots. 
I mean, that's cool he's reporting issue, but putting more than 2s in, at the very least, leaving an "hello", maybe, and "MC1.10.2/F12.18.2.2114/IE0.10-47" would not have hurt him much, would it ?

**Comment by robotbrain** [comment]
Her,  and mc 1.10.2,latest forge and IE as of right now.

**Comment by robotbrain** [comment]
I can provide a MultiMC if needed

**Comment by robotbrain** [comment]
*MultiMC instance

**Comment by BluSunrize** [comment]
I actually requested this issue to be brought over from CurseForge, so I was already aware of its precedent. All I needed was a picture to confirm an initial suspicion.

Will work on this today.
