### ISSUE TITLE
Silo not allowing output but for hopper

### ISSUE THREAD

**Issue by VallenFrostweaver** [BluSunrize/ImmersiveEngineering#1639]
Without using another mod to pull the items from the outputs on the bottom of the silo the only way I can now output items is with a hopper underneath making the side outputs on the bottom block look like they can be used but in fact they do not function unless with non-IE mods (conveyors no longer work to pull items out. 

Currently using Minecraft 1.10.2 - IE 0.10-47

**Comment by malte0811** [comment]
Normally applying a redstone signal should cause it to auto-output, but the relevant code is currently commented out. I will rewrite that code for the new inventory system tommorow unless Blu wants to do that.

**Comment by BluSunrize** [comment]
I already did a few hours ago. Just unpushed ^^
