### ISSUE TITLE
Floodlight issues.

### ISSUE THREAD

**Issue by xenoflot** [BluSunrize/ImmersiveEngineering#1641]
Hi guys,

Been playing with floodlights in SMP today. My server is in Chicago, I'm in Australia. I've noticed a few quirks that I suspect are unintended behaviour.

1. Very long delays and/or inconsistent behaviour of light source rendering when toggling redstone. Sometimes the "Local" light source comes on and sometimes the flood cone as well. Sometimes one but not the other. Sometimes one turns off, sometimes both. Sometimes neither. Sometimes it goes off about 10-15 seconds after I flip the lever. I don't believe that delays are due to connection latency as I can open chests and GUIs instantly. 

2. "Local" light does not vanish when the floodlight is broken with a pickaxe. Placing another block where the floodlight was, will extinguish the light. However placing another floodlight will not affect it.

3. Local and cone lights don't vanish when the floodlight runs out of power.

4. No change in the rendering of the floodlight reflector. I actually once saw it silvery but usually it's just an orange colour, I think bright or dark depending on whether the local light is "on".

Cheers!

**Comment by malte0811** [comment]
What version of IE are you using? Build 48?

**Comment by xenoflot** [comment]
/facepalm I knew I forgot something. Build 47

**Comment by BluSunrize** [comment]
tbf, this was reported before 48 was built and released. But yeah, give it a shot with the updated version ^^

**Comment by xenoflot** [comment]
Odd, I searched for "flood" and "flood light" but I didn't spot anything. 
I'll give 48 a go. Thanks!

**Comment by xenoflot** [comment]
Takes about 10 seconds for the cone light to toggle but I guess that's just an artefact of updating lighting for so many blocks. Otherwise toggling reliably in v48. Thanks!

**Comment by ColonelClink** [comment]
> "Local" light does not vanish when the floodlight is broken with a pickaxe. Placing another block where the floodlight was, will extinguish the light. However placing another floodlight will not affect it.

 This is happening for me in release 58. Regression, perhaps?
