### ISSUE TITLE
Post bug

### ISSUE THREAD

**Issue by Twetch** [BluSunrize/ImmersiveEngineering#1642]
when you click with hammer on wooden or any other post to extend it will spawn another one but if you place relay on it than it show correctly (tested on ImmersiveEngineering-0.10-48)

[https://i.gyazo.com/0a2911a54e45ae5420aa566e5a6fb392.png](url)

**Comment by mindforger** [comment]
github broke your link :(

https://i.gyazo.com/0a2911a54e45ae5420aa566e5a6fb392.png

**Comment by BluSunrize** [comment]
@Twetch please read the contribution guidlines and use the search function next time.
We always want to know your IE version.
And this is an old issue filed under "can't really fix" because block rendering happens before Tiles sync their data. So we're shit outta luck there.
