### ISSUE TITLE
not sure why but it keeps crashing i don't even have a crusher built

### ISSUE THREAD

**Issue by snacdaws** [BluSunrize/ImmersiveEngineering#1643]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.3.jar)
  CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  AppleCore (AppleCore-mc1.10.2-2.0.1.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.56-beta.jar)
  CCLCorePlugin (codechickenlib-1.10.2-2.4.1.101-universal.jar)
  BCModPlugin (zz-backpacks 1.10.2 - 3.1.3.jar)
  DLFMLCorePlugin (DynamicLights-1.10.2.jar)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.0.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 28/10/16 3:48 PM
Description: Ticking block entity

java.lang.ArrayIndexOutOfBoundsException: 0
    at blusunrize.immersiveengineering.common.blocks.TileEntityMultiblockPart.isDummy(TileEntityMultiblockPart.java:231)
    at blusunrize.immersiveengineering.common.blocks.metal.TileEntityCrusher.func_73660_a(TileEntityCrusher.java:88)
    at net.minecraft.world.World.func_72939_s(World.java:1804)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at blusunrize.immersiveengineering.common.blocks.TileEntityMultiblockPart.isDummy(TileEntityMultiblockPart.java:231)
    at blusunrize.immersiveengineering.common.blocks.metal.TileEntityCrusher.func_73660_a(TileEntityCrusher.java:88)

-- Block entity being ticked --
Details:
    Name: immersiveengineering:Crusher // blusunrize.immersiveengineering.common.blocks.metal.TileEntityCrusher
    Block type: ID #345 (tile.immersiveengineering.metalMultiblock // blusunrize.immersiveengineering.common.blocks.metal.BlockMetalMultiblocks)
    Block data value: 1 / 0x1 / 0b0001
    Block location: World: (-85,70,275), Chunk: (at 11,4,3 in -6,17; contains blocks -96,0,272 to -81,255,287), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Actual block type: ID #345 (tile.immersiveengineering.metalMultiblock // blusunrize.immersiveengineering.common.blocks.metal.BlockMetalMultiblocks)
    Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1804)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['faze_pigman'/56, l='MpServer', x=-73.16, y=73.00, z=246.85]]
    Chunk stats: MultiplayerChunkCache: 169, 169
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-44,64,256), Chunk: (at 4,4,0 in -3,16; contains blocks -48,0,256 to -33,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 1483060 game time, 170009 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 20 total; [EntityBat['Bat'/32, l='MpServer', x=-37.03, y=16.61, z=186.48], EntityPixelmon['Swadloon'/64, l='MpServer', x=-107.50, y=64.50, z=241.50], EntityPixelmon['Spearow'/65, l='MpServer', x=-33.50, y=68.50, z=217.50], EntityPixelmon['Pidgeotto'/66, l='MpServer', x=-14.50, y=63.50, z=280.50], EntityBat['Bat'/38, l='MpServer', x=-14.99, y=11.88, z=253.33], EntityPixelmon['Butterfree'/71, l='MpServer', x=-141.50, y=75.50, z=242.50], NPCTrainer['7'/40, l='MpServer', x=-11.90, y=62.30, z=169.98], EntityPixelmon['Pidgey'/73, l='MpServer', x=-126.50, y=65.50, z=205.50], EntityPixelmon['Abra'/74, l='MpServer', x=-69.50, y=71.50, z=207.50], EntityPixelmon['Pachirisu'/75, l='MpServer', x=-133.50, y=73.50, z=236.50], EntityPixelmon['Abra'/77, l='MpServer', x=-41.50, y=64.50, z=173.50], EntityPixelmon['Pidgeot'/78, l='MpServer', x=-137.50, y=69.50, z=216.50], NPCTutor['Rancher'/18, l='MpServer', x=-122.33, y=63.85, z=274.00], EntityPixelmon['Bellsprout'/83, l='MpServer', x=-108.50, y=67.50, z=213.50], EntityPixelmon['Spearow'/84, l='MpServer', x=-105.50, y=67.50, z=207.50], EntityBat['Bat'/21, l='MpServer', x=-73.55, y=47.10, z=246.75], EntityPlayerSP['faze_pigman'/56, l='MpServer', x=-73.16, y=73.00, z=246.85], EntityBat['Bat'/29, l='MpServer', x=-45.69, y=19.10, z=182.49], EntityBat['Bat'/30, l='MpServer', x=-39.15, y=17.10, z=188.91], EntityBat['Bat'/31, l='MpServer', x=-37.67, y=17.43, z=188.00]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2660)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:392)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1788478760 bytes (1705 MB) / 3907518464 bytes (3726 MB) up to 5758779392 bytes (5492 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6178m -Xms256m -XX:PermSize=256m
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP 9.32 Powered by Forge 12.18.2.2114 65 mods loaded, 65 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.2.2114.jar) 
    UCHIJAAAA   Forge{12.18.2.2114} [Minecraft Forge](forge-1.10.2-12.18.2.2114.jar) 
    UCHIJAAAA   Aroma1997Core{${version}} [Aroma1997Core](Aroma1997Core-1.9.4-1.1.1.0.jar) 
    UCHIJAAAA   backpacks16840{3.1.3} [Backpacks!](zz-backpacks 1.10.2 - 3.1.3.jar) 
    UCHIJAAAA   movillages{1.5.2} [Mo' Villages]([1.9.4]Mo' Villages-1.5.2.jar) 
    UCHIJAAAA   mantle{1.10.2-1.1.1.194} [Mantle](Mantle-1.10.2-1.1.1.jar) 
    UCHIJAAAA   tconstruct{1.10.2-2.5.6b.jenkins424} [Tinkers' Construct](TConstruct-1.10.2-2.5.6b.jar) 
    UCHIJAAAA   immersiveengineering{0.10-48} [Immersive Engineering](ImmersiveEngineering-0.10-48.jar) 
    UCHIJAAAA   JEI{3.13.0.334} [Just Enough Items](jei_1.10.2-3.13.0.334.jar) 
    UCHIJAAAA   AppleCore{2.0.1} [AppleCore](AppleCore-mc1.10.2-2.0.1.jar) 
    UCHIJAAAA   Aroma1997CoreHelper{1.1.1.0} [Aroma1997Core|Helper](Aroma1997Core-1.9.4-1.1.1.0.jar) 
    UCHIJAAAA   Aroma1997sDimension{1.0} [Aroma1997's Dimensional World](Aroma1997s-Dimensional-World-1.9.4-1.2.0.2.jar) 
    UCHIJAAAA   AromaBackup{1.0.1.1} [AromaBackup](AromaBackup-1.9.4-1.0.1.1.jar) 
    UCHIJAAAA   AromaBackupRecovery{1.0} [AromaBackup Recovery](AromaBackup-1.9.4-1.0.1.1.jar) 
    UCHIJAAAA   Baubles{1.3.0} [Baubles](Baubles-1.10.2-1.3.0.jar) 
    UCHIJAAAA   Botania{r1.9-335} [Botania](botania r1.9-335.jar) 
    UCHIJAAAA   ccmm{1.1} [CombatCooldown--](ccmm-1.10.2-1.1.jar) 
    UCHIJAAAA   ChestTransporter{2.5.3} [Chest Transporter](ChestTransporter-1.10.2-2.5.3.jar) 
    UCHIJAAAA   chisel{MC1.10.2-0.0.7.3} [Chisel](Chisel-MC1.10.2-0.0.7.3.jar) 
    UCHIJAAAA   cxlibrary{1.2.2} [CXLibrary](cxlibrary-1.10.2-1.2.2.jar) 
    UCHIJAAAA   cyclicmagic{1.7.21} [Cyclic](Cyclic-1.10.2-1.7.21.jar) 
    UCHIJAAAA   DynamicLights{1.4.3} [Dynamic Lights](DynamicLights-1.10.2.jar) 
    UCHIJAAAA   DynamicLights_onFire{1.0.7} [Dynamic Lights Burning Entity Module](DynamicLights-1.10.2.jar) 
    UCHIJAAAA   DynamicLights_creepers{1.0.6} [Dynamic Lights Creeper Module](DynamicLights-1.10.2.jar) 
    UCHIJAAAA   DynamicLights_dropItems{1.1.0} [Dynamic Lights EntityItem Module](DynamicLights-1.10.2.jar) 
    UCHIJAAAA   DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module](DynamicLights-1.10.2.jar) 
    UCHIJAAAA   DynamicLights_mobEquipment{1.1.0} [Dynamic Lights Mob Equipment Light Module](DynamicLights-1.10.2.jar) 
    UCHIJAAAA   DynamicLights_flameArrows{1.0.1} [Dynamic Lights Fiery Arrows Light Module](DynamicLights-1.10.2.jar) 
    UCHIJAAAA   DynamicLights_floodLights{1.0.3} [Dynamic Lights Flood Light](DynamicLights-1.10.2.jar) 
    UCHIJAAAA   DynamicLights_otherPlayers{1.0.9} [Dynamic Lights OtherPlayers Light Module](DynamicLights-1.10.2.jar) 
    UCHIJAAAA   DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module](DynamicLights-1.10.2.jar) 
    UCHIJAAAA   endercore{1.10.2-0.4.1.56-beta} [EnderCore](EnderCore-1.10.2-0.4.1.56-beta.jar) 
    UCHIJAAAA   Waila{1.7.0} [Waila](Waila-1.7.0-B3_1.9.4.jar) 
    UCHIJAAAA   EnderIO{1.10.2-3.0.1.120_beta} [Ender IO](EnderIO-1.10.2-3.0.1.120_beta.jar) 
    UCHIJAAAA   excore{1.6.2} [EXCore](Excore-1.6.2-1.10.2.jar) 
    UCHIJAAAA   ExtraUtils2{1.0} [ExtraUtils2](extrautils2-1.10.2-alpha-1.2.1.jar) 
    UCHIJAAAA   zerocore{1.10.2-0.0.8.0} [Zero CORE](zerocore-1.10.2-0.0.8.0.jar) 
    UCHIJAAAA   bigreactors{0.4.5.18} [Extreme Reactors](ExtremeReactors-1.10.2-0.4.5.18.jar) 
    UCHIJAAAA   fastleafdecay{v11} [Fast Leaf Decay](FastLeafDecay-v11.jar) 
    UCHIJAAAA   fw{1.3.0} [Fullscreen Windowed](FullscreenWindowed-1.10.2-1.3.0b.jar) 
    UCHIJAAAA   grapple_hooks{1.0.8} [Grapple Hooks](Grapple-Hooks-1.10.2-1.0.8.jar) 
    UCHIJAAAA   HoloInventory{2.0.3.139} [HoloInventory](HoloInventory-1.9.4-2.0.3.139.jar) 
    UCHIJAAAA   HungerInPeace{1.0.0} [Hunger In Peace](HungerInPeace-mc1.9.4-1.0.0.jar) 
    UCHIJAAAA   inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks](InventoryTweaks-1.61-58.jar) 
    UCHIJAAAA   ironchest{1.10.2-7.0.11.797} [Iron Chest](ironchest-1.10.2-7.0.11.797.jar) 
    UCHIJAAAA   journeymap{1.10.2-5.3.0b2} [JourneyMap](journeymap-1.10.2-5.3.0b2-unlimited.jar) 
    UCHIJAAAA   testdummy{1.11} [MmmMmmMmmMmm](MmmMmmMmmMmm-1.11.jar) 
    UCHIJAAAA   craftelytra{1.1} [Craftable Elytra](modid-1.1-1.10.2.jar) 
    UCHIJAAAA   MoreFurnaces{1.8.2} [More Furnaces](MoreFurnaces-1.10.2-1.8.2.jar) 
    UCHIJAAAA   netherportalfix{1.0} [Nether Portal Fix](netherportalfix-mc1.9.4-4.0.1.jar) 
    UCHIJAAAA   harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft](Pam's HarvestCraft 1.9.4-1.10.2g.jar) 
    UCHIJAAAA   pixelmon{5.0.0-beta10} [Pixelmon](Pixelmon-1.10.2-5.0.0-beta10-universal.jar) 
    UCHIJAAAA   pixelextras{2.2.1} [Pixel Extras](PixelExtras-1.10.2-2.2.1-universal.jar) 
    UCHIJAAAA   simpleharvest{1.05} [Simple Harvest](simpleharvest-1.10.2-2002-1.05.jar) 
    UCHIJAAAA   simpleretrogen{4.0.1+8} [Simple Retrogen](simpleretrogen-1.10-4.0.1+8.jar) 
    UCHIJAAAA   slabcraftmod{6.03} [Slabcraft](Slabcraftmod v6.03 - MC1.10.2 Forge.jar) 
    UCHIJAAAA   staircraftmod{6.02} [Staircraft](Staircraftmod v6.02 - MC1.10.2 Forge.jar) 
    UCHIJAAAA   supercraftingframe{1.2.1.88} [Super Crafting Frame](supercraftingframe-1.10.2-1.2.1.88.jar) 
    UCHIJAAAA   VeinMiner{0.34.1_1.9-73be663} [Vein Miner](VeinMiner-0.34.1-1.9r571+73be663.jar) 
    UCHIJAAAA   VeinMinerModSupport{0.34.1_1.9-73be663} [Mod Support](VeinMiner-0.34.1-1.9r571+73be663.jar) 
    UCHIJAAAA   WailaHarvestability{1.1.9} [Waila Harvestability](WailaHarvestability-mc1.10.2-1.1.9.jar) 
    UCHIJAAAA   waterstrainer{1.3.1} [Water Strainer](WaterStrainer-1.9.4-1.3.1.jar) 
    UCHIJAAAA   icse{1.1.0.0} [I Can See Everything](Wawla-1.10.2-2.3.0.206.jar) 
    UCHIJAAAA   wawla{2.3.0.202} [What Are We Looking At](Wawla-1.10.2-2.3.0.206.jar) 
    Loaded coremods (and transformers): 
ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.3.jar)
  team.chisel.common.asm.ChiselTransformer
CXLibraryCore (cxlibrary-1.10.2-1.2.2.jar)
  cubex2.cxlibrary.CoreModTransformer
AppleCore (AppleCore-mc1.10.2-2.0.1.jar)
  squeek.applecore.asm.TransformerModuleHandler
EnderCorePlugin (EnderCore-1.10.2-0.4.1.56-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
CCLCorePlugin (codechickenlib-1.10.2-2.4.1.101-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
BCModPlugin (zz-backpacks 1.10.2 - 3.1.3.jar)
  brad16840.common.asm.ClassTransformer
DLFMLCorePlugin (DynamicLights-1.10.2.jar)
  atomicstryker.dynamiclights.common.DLTransformer
CoreMod (Aroma1997Core-1.9.4-1.1.1.0.jar)

FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 372.70' Renderer: 'GeForce GTX 750/PCIe/SSE2'
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerHarvestTools (Enabled/Forced)
        - TinkerMeleeWeapons (Enabled/Forced)
        - TinkerRangedWeapons (Enabled/Forced)
        - TinkerModifiers (Enabled/Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - TinkerModelRegister (Enabled/Forced)
        - WailaIntegration (Enabled/Not Forced)

```
EnderIO: No known problems detected.
Detailed RF API diagnostics:
              * RF API class 'EnergyStorage' is loaded from: jar:file:/D:/Curse/Instances/1.10.2%20Pixelmon/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/EnergyStorage.class
              * RF API class 'IEnergyConnection' is loaded from: jar:file:/D:/Curse/Instances/1.10.2%20Pixelmon/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/IEnergyConnection.class
              * RF API class 'IEnergyContainerItem' is loaded from: jar:file:/D:/Curse/Instances/1.10.2%20Pixelmon/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/IEnergyContainerItem.class
              * RF API class 'IEnergyHandler' is loaded from: jar:file:/D:/Curse/Instances/1.10.2%20Pixelmon/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/IEnergyHandler.class
              * RF API class 'IEnergyProvider' is loaded from: jar:file:/D:/Curse/Instances/1.10.2%20Pixelmon/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/IEnergyProvider.class
              * RF API class 'IEnergyReceiver' is loaded from: jar:file:/D:/Curse/Instances/1.10.2%20Pixelmon/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/IEnergyReceiver.class
              * RF API class 'IEnergyStorage' is loaded from: jar:file:/D:/Curse/Instances/1.10.2%20Pixelmon/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/IEnergyStorage.class
              * RF API class 'ItemEnergyContainer' is loaded from: jar:file:/D:/Curse/Instances/1.10.2%20Pixelmon/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/ItemEnergyContainer.class
              * RF API class 'TileEnergyHandler' is loaded from: jar:file:/D:/Curse/Instances/1.10.2%20Pixelmon/mods/ImmersiveEngineering-0.10-48.jar!/cofh/api/energy/TileEnergyHandler.class
Detailed Tesla API diagnostics:
              * Tesla API class 'Tesla' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.Tesla)
              * Tesla API class 'TeslaCapabilities' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.capability.TeslaCapabilities)
              * Tesla API class 'ITeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaConsumer)
              * Tesla API class 'ITeslaHolder' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaHolder)
              * Tesla API class 'ITeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.ITeslaProducer)
              * Tesla API class 'BaseTeslaContainer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainer)
              * Tesla API class 'BaseTeslaContainerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.BaseTeslaContainerProvider)
              * Tesla API class 'InfiniteTeslaConsumer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumer)
              * Tesla API class 'InfiniteTeslaConsumerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaConsumerProvider)
              * Tesla API class 'InfiniteTeslaProducer' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducer)
              * Tesla API class 'InfiniteTeslaProducerProvider' could not be loaded (reason: java.lang.ClassNotFoundException: net.darkhax.tesla.api.implementation.InfiniteTeslaProducerProvider)

Launched Version: forge-12.18.2.2114
LWJGL: 2.9.4
OpenGL: GeForce GTX 750/PCIe/SSE2 GL version 4.5.0 NVIDIA 372.70, NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: No
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 8x Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
```

**Comment by snacdaws** [comment]
it worked perfectly a few hours ago but doesn't now

**Comment by snacdaws** [comment]
just tried a save backup from yesterday and the issue is gone but i haven't re-enabled all my mods yet......

**Comment by BluSunrize** [comment]
Singleplayer or Server?

Also, please read the contribution guidelines and put your log on pastebin next time.

**Comment by snacdaws** [comment]
Single player 

And sorry I am new to bug reporting 

I just started playing 1.10.2 a month ago 

Also I generally play older versions well after the newest version of minecraft is out so I never had a reason to report bugs

Also I can't understand why but the issue is gone tho I had to mess around with my backups and removing ie and loading minecraft up then closing minecraft and re-enableing ie
