### ISSUE TITLE
1.10.2 RF not converting to EU

### ISSUE THREAD

**Issue by Degrath** [BluSunrize/ImmersiveEngineering#1649]
I am unable to get the RF to convert to Eu and power anything IC2. Is there something I am not doing or has something broke lately?

Immersive Engineering 1.10.2 - 84
Industrialcraft 2 2.6.86-ex110
Forge 12.18.2.2114

**Comment by ArukaAlter** [comment]
It was removed times ago, conversion is no longer possible.

**Comment by Degrath** [comment]
Can you link to the post or information about its removal? Just curious as to why now that I know it was removed. thanks for the fast reply

**Comment by transcondriver** [comment]
See: #1087 That thread seems to hold some answers pertinent to your issue.

**Comment by BluSunrize** [comment]
Yep, conversion has been removed. Very much intentional. Issue closed.
