### ISSUE TITLE
Railcraft Creosote & IE Treated Planks

### ISSUE THREAD

**Issue by jco2641** [BluSunrize/ImmersiveEngineering#1654]
MC: 1.10
Forge: 12.18.2.2116
IE: 0.10-48
Railcraft: 10.0.0.0

If using a stack of more than 1 Railcraft creosote bottle in the IE treated plank recipe, the bottle stack size becomes 2n-1 on each crafting click.

Steps:
Place 2 creosote bottles in center of stacks of wood planks
Click once to craft 8 treated planks
There are now 3 bottles in center
Click again, now 5 bottles
Again, now 9 bottles
Again, now 17 bottles
etc.

**Comment by ArukaAlter** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/1586

**Comment by BluSunrize** [comment]
As far as I am aware, that issue is on Railcraft's side, not mine.
