### ISSUE TITLE
IE console spam and Frozen Client when changing video settings with Optifine HD U D1 & D2.

### ISSUE THREAD

**Issue by SirChamomile** [BluSunrize/ImmersiveEngineering#1657]
Console is spammed with:
```
[21:52:46] [Client thread/WARN]: Unable to resolve texture due to upward reference: #side in immersiveengineering:models/block/ieScaffolding
[21:52:46] [Client thread/ERROR]: MultiModel minecraft:builtin/missing is empty (no base model or parts were provided/resolved)
```

**Comment by malte0811** [comment]
Are you talking about the shaders IE adds (http://ftb.gamepedia.com/Shaders) or about shaders that are meant to improve general visual appearance?
If the former, what shaders where you swapping on what item?
If the latter, what shader mod are you using and what shaders where you switching? I don't know if @BluSunrize wants to support them (I would assume they do a fair amount of changes to vanilla rendering, but we haven't had a bug report about them before, so there isn't any official opinion on this).
And, as it asks you to state in the contributing guidelines, what version of MC, what version of IE and what other mods are you using?

**Comment by SirChamomile** [comment]
Hi malte0811!

Thanks for getting back to me. I'm sorry for dropping in without being thorough. I pulled some lines out of a recent crash report to give you an idea of my setup:

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1442749880 bytes (1375 MB) / 4268163072 bytes (4070 MB) up to 4268163072 bytes (4070 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.2.2118 Optifine OptiFine_1.10.2_HD_U_D1 73 mods loaded, 73 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2118.jar) 
	UCHIJA	Forge{12.18.2.2118} [Minecraft Forge] (forge-1.10.2-12.18.2.2118.jar) 
	UCHIJA	Baubles{1.3.0} [Baubles] (Baubles-1.10.2-1.3.0.jar) 
	UCHIJA	Botania{r1.9-337} [Botania] (Botania r1.9-337.jar) 
	UCHIJA	AkashicTome{1.0-4} [Akashic Tome] (AkashicTome-1.0-4.jar) 
	UCHIJA	antiqueatlas{1.9.4-4.3.0} [Antique Atlas] (antiqueatlas-1.9.4-4.3.0.jar) 
	UCHIJA	AntiqueAtlasOverlay{1.2} [AntiqueAtlasOverlay] (antiqueatlas-1.9.4-4.3.0.jar) 
	UCHIJA	mantle{1.10.2-1.1.1.194} [Mantle] (Mantle-1.10.2-1.1.1.jar) 
	UCHIJA	tconstruct{1.10.2-2.5.6b.jenkins424} [Tinkers' Construct] (TConstruct-1.10.2-2.5.6b.jar) 
	UCHIJA	immersiveengineering{0.10-48} [Immersive Engineering] (ImmersiveEngineering-0.10-48.jar) 
	UCHIJA	JEI{3.13.0.339} [Just Enough Items] (jei_1.10.2-3.13.0.339.jar) 
	UCHIJA	AppleCore{2.0.1} [AppleCore] (AppleCore-mc1.10.2-2.0.1.jar) 
	UCHIJA	Morphtool{1.0-12} [Morph-o-Tool] (Morph-o-Tool-1.0-12.jar) 
	UCHIJA	Psi{r1.0-41} [Psi] (Psi-r1.0-41.jar) 
	UCHIJA	Quark{r1.0-57} [Quark] (Quark-r1.0-57.jar) 
	UCHIJA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJA	BetterFoliage{2.1.1} [Better Foliage] (BetterFoliage-MC1.10-2.1.1.jar) 
	UCHIJA	BiomesOPlenty{5.0.0.2089} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2089-universal.jar) 
	UCHIJA	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.2-45.jar) 
	UCHIJA	BloodMagic{1.9.4-2.1.0-66} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.1.0-66.jar) 
	UCHIJA	Chameleon{1.10-2.1.7} [Chameleon] (Chameleon-1.10-2.1.7.jar) 
	UCHIJA	mcmultipart{1.3.0} [MCMultiPart] (MCMultiPart-1.3.0-universal.jar) 
	UCHIJA	CharsetLib{0.3.0-pre15} [‽] (Charset-0.3.0-pre15.jar) 
	UCHIJA	CharsetAudio{0.3.0-pre15} [♫] (Charset-0.3.0-pre15.jar) 
	UCHIJA	CharsetCarts{0.3.0-pre15} [U] (Charset-0.3.0-pre15.jar) 
	UCHIJA	CharsetDecoration{0.3.0-pre15} [⚿] (Charset-0.3.0-pre15.jar) 
	UCHIJA	CharsetDrama{0.3.0-pre15} [!] (Charset-0.3.0-pre15.jar) 
	UCHIJA	CharsetFarming{0.3.0-pre15} [;] (Charset-0.3.0-pre15.jar) 
	UCHIJA	CharsetGates{0.3.0-pre15} [&] (Charset-0.3.0-pre15.jar) 
	UCHIJA	CharsetPipes{0.3.0-pre15} [|] (Charset-0.3.0-pre15.jar) 
	UCHIJA	CharsetStorage{0.3.0-pre15} [#] (Charset-0.3.0-pre15.jar) 
	UCHIJA	CharsetTweaks{0.3.0-pre15} [*] (Charset-0.3.0-pre15.jar) 
	UCHIJA	CharsetWires{0.3.0-pre15} [+] (Charset-0.3.0-pre15.jar) 
	UCHIJA	CharsetWrench{0.3.0-pre15} [/] (Charset-0.3.0-pre15.jar) 
	UCHIJA	chisel{MC1.10.2-0.0.7.3} [Chisel] (Chisel-MC1.10.2-0.0.7.3.jar) 
	UCHIJA	chiselsandbits{12.6} [Chisels & Bits] (chiselsandbits-12.6.jar) 
	UCHIJA	customoregen{1.10.2} [customoregen] (CustomOreGen-1.10.2-1.4.1.jar) 
	UCHIJA	IC2{2.6.87-ex110} [IndustrialCraft 2] (industrialcraft-2-2.6.87-ex110.jar) 
	UCHIJA	forestry{5.2.16.310} [Forestry] (forestry_1.10.2-5.2.16.310.jar) 
	UCHIJA	ElecCore{1.6.328} [ElecCore] (ElecCore-1.10.2-1.6.328.jar) 
	UCHIJA	deepresonance{1.2.9} [DeepResonance] (deepresonance-1.10-1.2.9.jar) 
	UCHIJA	endercore{1.10.2-0.4.1.58-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.58-beta.jar) 
	UCHIJA	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UCHIJA	EnderIO{1.10.2-3.0.1.125_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.125_beta.jar) 
	UCHIJA	extraalchemy{0.3.0.3-release} [Extra Alchemy] (extraalchemy-0.3.0.3-release.jar) 
	UCHIJA	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-alpha-1.2.1.jar) 
	UCHIJA	geographicraft{0.7.5} [GeographiCraft] (GeographiCraft-1.9.4-0.7.5.jar) 
	UCHIJA	gravestone{1.5.8} [Gravestone] (GraveStone Mod 1.5.8.jar) 
	UCHIJA	inventorytweaks{1.62-dev-66-c082db3} [Inventory Tweaks] (InventoryTweaks-1.62-dev-66.jar) 
	UCHIJA	ironchest{1.10.2-7.0.11.797} [Iron Chest] (ironchest-1.10.2-7.0.11.797.jar) 
	UCHIJA	jeibees{0.9.0.4} [JEI Bees] (jeibees-0.9.0.4-mc1.10.2.jar) 
	UCHIJA	journeymap{1.10.2-5.3.0b2} [JourneyMap] (journeymap-1.10.2-5.3.0b2-unlimited.jar) 
	UCHIJA	jeresources{0.5.1.56} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.1.56.jar) 
	UCHIJA	mfs{7.0.2} [Minecraft Flight Simulator] (Minecraft Flight Simulator-1.10.2-7.0.2.jar) 
	UCHIJA	testdummy{1.11} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.11.jar) 
	UCHIJA	naturescompass{1.2.0} [Nature's Compass] (NaturesCompass-1.10.2-1.2.0.jar) 
	UCHIJA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2g.jar) 
	UCHIJA	gunpowder{1.1_1.9.4} [Placeable Gunpowder] (PlaceableGunpowder-1.1_1.9.4.jar) 
	UCHIJA	railcraft{10.0.0} [Railcraft] (Railcraft_1.10.2-10.0.0.jar) 
	UCHIJA	StorageDrawers{1.10.2-3.3.0} [Storage Drawers] (StorageDrawers-1.10.2-3.3.0.jar) 
	UCHIJA	refinedstorage{1.2-beta5} [Refined Storage] (refinedstorage-1.2-beta5.jar) 
	UCHIJA	rftools{5.57} [RFTools] (rftools-1.10-5.57.jar) 
	UCHIJA	rftoolscontrol{1.5.1} [RFTools Control] (rftoolsctrl-1.10-1.5.1.jar) 
	UCHIJA	rftoolsdim{4.43} [RFTools Dimensions] (rftoolsdim-1.10-4.43.jar) 
	UCHIJA	Roguelike{1.5.4} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.4.jar) 
	UCHIJA	roots{0.204} [Roots] (roots-1.10.2-0.204.0.jar) 
	UCHIJA	RTG{4.1.1.5} [Realistic Terrain Generation] (RTG-1.10.2-4.1.1.5.jar) 
	UCHIJA	SpiceOfLife{1.3.6} [The Spice of Life] (SpiceOfLife-mc1.9.4-1.3.6.jar) 
	UCHIJA	waystones{2.0.8} [Waystones] (Waystones_1.10.2-2.0.8.jar) 
	UCHIJA	worldstripper{1.1.1-1.10.2} [World Stripper] (World-Stripper-1.1.1-1.10.2.jar) 
	UCHIJA	wtfcore{1.10.2_v1.1} [wtfcore] (WTF-Expedition_1.10.2_v1.1.jar) 
	UCHIJA	UniDict{1.10.2-2.3b} [UniDict] (UniDict-1.10.2-2.3b.jar) 

I was using the built-in shaders mod in Optifine HD U D1. I've found after further testing that this issue occurs any time the resource pack is re-loaded in-game, or when video setting are adjusted in-game using Optifine HD D2 and D1. This is without any shaders loaded. I believe that this is the fault of Optifine for hanging the client. However, this particular interaction may be a cause of the hang, and not just a symptom. Using the HD U C3 version of Optifine, the client reloads the resourcepacks successfully. While watching the log during the reload, I can see that IE still spams the console. If there's more I can do to test let me know what you want and I'll try it when I have the time.

**Comment by BluSunrize** [comment]
Yeah, IE will print that to the console, and so will a load of other mods. The new models throw /loads/ of issues during baking, and that baking occurs on every resource reload.
The freezing isn't because of that, but because reloading resources always freezes the client, so this isn't really an issue, it's just how things are :/

**Comment by SirChamomile** [comment]
Understandable. This particular freeze hangs the client permanently, but when rolling back to C3 it was fixed so I'll report further crashes to the folks at Optifine. Thanks!
