### ISSUE TITLE
On startup asks for a  mod that it depends on

### ISSUE THREAD

**Issue by Dutch26** [BluSunrize/ImmersiveEngineering#1658]
on start up asks for a another mod but  i cant find it anywhere...pls help

**Comment by mindforger** [comment]
Please review the [guidelines for contributing](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/CONTRIBUTING.md) to this repository.

**Comment by BluSunrize** [comment]
It would help if you said /what/ mod it required

**Comment by malte0811** [comment]
The only mod IE requires is MC Forge version 12.18.2.2104+. Forge is what makes (probably) all other mods in your pack work, without it it would be very hard to install more than 1-2 mods at a time.
You are probably using the recommended version of Forge which is 5 builds earlier than the one IE needs (2099). If you are using MultiMC, you can change the Forge version by pressing "Edit instance", "install Forge" (or something like that) and select version 2104 or later.

**Comment by BluSunrize** [comment]
No response from the original poster, issue severely uninformative, closed.
