### ISSUE TITLE
[Bug] Blast Furnace Can't Use Charcoal

### ISSUE THREAD

**Issue by homemmakako** [BluSunrize/ImmersiveEngineering#166]
Although the book says you can use charcoal as fuel for the blast furnace, the furnace doesn't seems to accept it. Also NEI only shows coal coke and coal coke block as valid fuels.

Since we are on the topic, I'd suggest adding an electric blast furnace. It just needs to happen :laughing: steel takes a bit more than 3 (or precisely π) eternities to craft. Something must be done about this ( please? :stuck_out_tongue_closed_eyes:  )

**Comment by BluSunrize** [comment]
was already reported and fixed in #83, also nope.
