### ISSUE TITLE
concurrent modification exception crash when using voltimeter

### ISSUE THREAD

**Issue by Efimero** [BluSunrize/ImmersiveEngineering#1660]
when I right-click to see the power of a IE power container with the voltimeter, it sometimes crashes with this error:
<details>
<summary>Crash log</summary>
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.3.jar)
  ForgelinPlugin (Forgelin-1.0.5.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 3/11/16 3:37
Description: Exception ticking world

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$KeyIterator.next(Unknown Source)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:114)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)
	at WorldServerOF.func_72835_b(WorldServerOF.java:37)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$KeyIterator.next(Unknown Source)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:114)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)
	at WorldServerOF.func_72835_b(WorldServerOF.java:37)

-- Affected level --
Details:
	Level name: The Abyss
	All players: 1 total; [EntityPlayerMP['Efimero'/732, l='The Abyss', x=-196,71, y=41,00, z=-153,35]]
	Chunk stats: ServerChunkCache: 510 Drop: 0
	Level seed: -7884842174284175409
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-252,64,69), Chunk: (at 4,4,5 in -16,4; contains blocks -256,0,64 to -241,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 8813821 game time, 9323842 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 69163 (now: false), thunder time: 28417 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_05, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 168757896 bytes (160 MB) / 1597243392 bytes (1523 MB) up to 1597243392 bytes (1523 MB)
	JVM Flags: 25 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1536m -Xmx1536m -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -XX:+DisableExplicitGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ParallelGCThreads=2
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.32 Powered by Forge 12.18.2.2116 Optifine OptiFine_1.10.2_HD_U_D2 29 mods loaded, 29 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2116.jar) 
	UCHIJAAAA	Forge{12.18.2.2116} [Minecraft Forge] (forge-1.10.2-12.18.2.2116.jar) 
	UCHIJAAAA	immersiveengineering{0.10-48} [Immersive Engineering] (ImmersiveEngineering-0.10-48.jar) 
	UCHIJAAAA	JEI{3.13.0.341} [Just Enough Items] (jei_1.10.2-3.13.0.341.jar) 
	UCHIJAAAA	abyssalcraft{1.9.3.4} [AbyssalCraft] (AbyssalCraft-1.10.2-1.9.3.4.jar) 
	UCHIJAAAA	appleskin{1.0.4} [AppleSkin] (AppleSkin-mc1.10.2-1.0.4.jar) 
	UCHIJAAAA	Baubles{1.3.BETA11} [Baubles] (Baubles-1.10.2-1.3.BETA11.jar) 
	UCHIJAAAA	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.2-45.jar) 
	UCHIJAAAA	BloodMagic{1.9.4-2.1.0-66} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.1.0-66.jar) 
	UCHIJAAAA	Botania{r1.9-337} [Botania] (Botania r1.9-337.jar) 
	UCHIJAAAA	Chameleon{1.10-2.1.7} [Chameleon] (Chameleon-1.10-2.1.7.jar) 
	UCHIJAAAA	chisel{MC1.10.2-0.0.7.3} [Chisel] (Chisel-MC1.10.2-0.0.7.3.jar) 
	UCHIJAAAA	shadowmc{3.4.9} [ShadowMC] (ShadowMC-1.10.2-3.4.9.jar) 
	UCHIJAAAA	clipboard{@VERSION@} [Clipboard] (Clipboard-1.10.2-1.0.0.jar) 
	UCHIJAAAA	MineTweaker3{3.0.13} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.13.jar) 
	UCHIJAAAA	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.13.jar) 
	UCHIJAAAA	FFS{1.10.2-1.6.5-b31} [Fancy Fluid Storage] (Fancy Fluid Storage-1.10.2-1.6.5-b31.jar) 
	UCHIJAAAA	fixchiselstonegen{1.10.2-1.0} [Fix Chisel Stone Gen] (fixchiselstonegen-1.10.2-1.0.jar) 
	UCHIJAAAA	mcmultipart{1.2.1} [MCMultiPart] (MCMultiPart-1.2.1-universal.jar) 
	UCHIJAAAA	mousetweaks{2.6.4} [Mouse Tweaks] (MouseTweaks-2.6.4-mc1.10.2.jar) 
	UCHIJAAAA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2g.jar) 
	UCHIJAAAA	realdrops{1.0.7} [Realistic Item Drops] (RealisticItemDrops-1.0.7.jar) 
	UCHIJAAAA	realtimeclock{1.10-0.6.3} [Real Time Clock] (RealTimeClock-1.10-0.6.3.jar) 
	UCHIJAAAA	StorageDrawers{1.10.2-3.4.0} [Storage Drawers] (StorageDrawers-1.10.2-3.4.0.jar) 
	UCHIJAAAA	refinedstorage{1.2-beta6} [Refined Storage] (refinedstorage-1.2-beta6.jar) 
	UCHIJAAAA	roots{0.204} [Roots] (roots-1.10.2-0.204.0.jar) 
	UCHIJAAAA	soundfilters{0.9_for_1.9} [Sound Filters] (SoundFilters-0.9_for_1.9.4.jar) 
	UCHIJAAAA	substratum{1.8.1.0} [Substratum] (Substratum-1.10.2-1.8.1.0.jar) 
	Loaded coremods (and transformers): 
ChiselCorePlugin (Chisel-MC1.10.2-0.0.7.3.jar)
  team.chisel.common.asm.ChiselTransformer
ForgelinPlugin (Forgelin-1.0.5.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['Efimero'/732, l='The Abyss', x=-196,71, y=41,00, z=-153,35]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
</details>

**Comment by mindforger** [comment]
okay, that one is strange O_o
you may update your java Version

Java Version: 1.8.0_05, Oracle Corporation

current is 1.8.0_111

this may or may not help but it is always better to have java up to date

**Comment by malte0811** [comment]
I would blame Optifine, especially with Optifine classes in the stacktrace (WorldServerOF.func_72835_b(WorldServerOF.java:37))

**Comment by mindforger** [comment]
i was not sure if this class really depends to OF the crash log was missing the imporqant lines at the end unfortunately
