### ISSUE TITLE
Crash with WarpDrive mod

### ISSUE THREAD

**Issue by axelpx** [BluSunrize/ImmersiveEngineering#1661]
Here is the crashlog. It always happen in DIM-3 of the WarpDrive (Hyperspace) and always after a restart of the server (server is unable to start until the dimension DIM-3 is wiped).

http://pastebin.com/t99HZht9

Mods version:
WarpDrive: WarpDrive1.7.10-1.3.30.
Immersive Engineering: ImmersiveEngineering-0.7.7.jar

Server core: Thermos:1.7.10-1614.57

**Comment by mindforger** [comment]
an Mekanism chunkloader tried to chunkload something and broke with that attempt, can you reproduce this with using forge only?
