### ISSUE TITLE
Energy conduit does not take power from thermoelectric generator Immersive engineering

### ISSUE THREAD

**Issue by TheMrCaveman** [BluSunrize/ImmersiveEngineering#1663]
Issue Description:

Energy conduit does not take rf power from thermoelectric generator This used to work in 1.7.10!

What happens:

Place down a thermoelectric generator setup.
Connect energy conduit from thermoelectric generator to vibrant capacitor bank.
No energy is transported

What you expected to happen:

rf flow from thermoelectric generator to capacitor bank

Steps to reproduce:

1.Place down a thermoelectric generator setup.
2.Connect energy conduit from thermoelectric generator to vibrant capacitor bank.
3.Try to make working connection
...

Affected Versions:

EnderIO: 1.10.2-3.0.1.125
EnderCore:1.10.2-0.4.1.58
Immersive Engineering 0.10-48
Minecraft: 1.10.2
Forge:12.18.2.2114

**Comment by BluSunrize** [comment]
Thermoelectric Gens output IF, not RF. You'll need wire connectors.

**Comment by TheMrCaveman** [comment]
MM this energy system with mods in 1.10.2 is a holy mess @ the moment. 
Wire connectors are pretty limited.

**Comment by Zettt** [comment]
This does not seem to be working. I'm playing the current DW20 1.10 pack on Curse. I have a Thermoelectric Engine next to two uranium blocks, and two water sources, hooked up with MV Wire Connectors to either a capacitor bank directly, or the connectors to some conduits. Neither way causes the capacitor bank to charge.

**Comment by mindforger** [comment]
did you check to connect it o the input side? the one with the blue dot

**Comment by BluSunrize** [comment]
@Zett please provide pictures  =)

**Comment by Zettt** [comment]
![2016-11-28_02 38 06](https://cloud.githubusercontent.com/assets/42497/20665315/0ac58dbe-b514-11e6-9944-423af4ac57f7.png)

@BluSunrize

**Comment by laz2727** [comment]
They have to have the opposing temperatures on opposing sides.

**Comment by mindforger** [comment]
do you have Tesla API installed? EIO and IE can only opperate using Tesla API

i was mislead (misleaded ?!) by thinking you try to power IE Capacitors

**Comment by BluSunrize** [comment]
@Zett what @laz2727 said. the temperature gradients need to be on opposing sides, that*s how thermoelectrics work ^^

@mindforger what are you on about? IE doesn't support Tesla. =P

**Comment by Zettt** [comment]
@laz2727 How embarassing. I thought some in-between update caused a bug.

**Comment by mindforger** [comment]
@BluSunrize you do not? I thought the connectors do translate to tesla .... or what the heck mod do I mess up atm ?

**Comment by BluSunrize** [comment]
@mindforger I have never supported Tesla and don't ever intend to. I dislike Tesla quite a bit and have been vocal on that in the past. I don't intend to dig the topic out again =)

**Comment by mindforger** [comment]
nahh all gud, i may mixed that with placing stuff right to each other instead of using wires in an AE2 issue, my head was only half awake the day...
