### ISSUE TITLE
Redstone Connectors Rendering [0.10-48]

### ISSUE THREAD

**Issue by Doragoon01** [BluSunrize/ImmersiveEngineering#1664]
Redstone connectors are not rendering the colour changes, neither from changing from input to output, nor changing channels.
Also, I had a strange situation when i came back later, a connector rendered the same as an nearby connector, despite being on a different channel.  (white channel connector rendered as black)

**Comment by malte0811** [comment]
I fixed this yesterday but didn't push the commit. The same thing happens with structural connectors, I fixed that as well. I also fixed balloons being rotatable (I assume that was a bug, there was no code indicating it?) and made them colourable again. I will push the commit later today.
