### ISSUE TITLE
IF into EU

### ISSUE THREAD

**Issue by Reydenge** [BluSunrize/ImmersiveEngineering#1666]
Hello, i have a quastion - how can i trasform energy from ImmersiveEngineering to power mechanisms from IndustrialCraft ?

**Comment by ArukaAlter** [comment]
You can't, it has been this way since 1.8, and the feature won't come back anytime soon.
You can try Industrial Wires for IE style EU-only transference.

**Comment by mindforger** [comment]
@malte0811 made an IE addon for this caseif i remember correct

**Comment by BluSunrize** [comment]
To my knowledge, Malte's addon only transports EU through wires. It won't convert power.

I specifically distanced myself from that option because I realized that it brought a major imbalance to the game.
As such, IF -> EU transformation won't happen.

**Comment by Reydenge** [comment]
It's very bad to hear such words, but also thank you for the anwser.
