### ISSUE TITLE
1.10.2 Infinity Lite Creosote Duplication

### ISSUE THREAD

**Issue by Unbansheee** [BluSunrize/ImmersiveEngineering#1674]
When multiple creosote bottles are placed into a crafting station along with wood in order to make treated wood planks, and shift-clicked out, the creosote bottles in the center of the recipe for a full stack of 64.

This bug is present in version 1.0.1 of Infinity Lite, running Immersive Engineering 0.10-48
The creosote bottles are from the Railcraft mod, and are the only ones available in the pack.

Video footage here: https://youtu.be/5NEUSKoj0cA

**Comment by BluSunrize** [comment]
Have you reported this to Railcraft?

**Comment by CovertJaguar** [comment]
In the latest version of Railcraft, the Creosote Bottle is just a normal item, it doesn't have a container item or anything. So I have no idea what the issue is here, but I don't think its on my end.

**Comment by liach** [comment]
Does it happen with only Railcraft and Immersive Engineering? A third mod listening to crafting events might cause this.

**Comment by ariosos** [comment]
Can confirm this bug. Here's what happens -

Put 1 creosote can with 8 planks around it and it works as intended.
Put **2 cresote cans** in the middle and 8 planks around it. Pull out the treated planks. The creosote duplicates by 1.

**Comment by liach** [comment]
Looks like an IE bug.

**Comment by JaRyCu** [comment]
I have this happening in the Direwolf20 for MC 1.10 modpack as well.

**Comment by viveleroi** [comment]
I'm having the same issue but with a custom 1.10 modpack, I do have both Railcraft and IE.

**Comment by liach** [comment]
@BluSunrize How can Railcraft fix this?

**Comment by BluSunrize** [comment]
I dunno? That's for them to figure out, not me.

**Comment by liach** [comment]
So it's not an issue any more?

**Comment by BluSunrize** [comment]
Well I don't add bottles. So it's not my issue.

**Comment by CovertJaguar** [comment]
My Bottles are just items. Don't see how it could be my issue either. They aren't anything fancy. Works fine without IE.

**Comment by BluSunrize** [comment]
Doesn't work at all without IE because there wouldn't be any treated wood, mate =P
