### ISSUE TITLE
Strange behavior with Posts

### ISSUE THREAD

**Issue by TheLegitimantis** [BluSunrize/ImmersiveEngineering#1675]
Minecraft version 1.10.2
Forge version 12.18.2.2114
IE version 0.10-48

Sometimes, in certain areas of the world, posts behave very strangely. Looking at them from certain angles makes them invisible, and right clicking the top of them with a hammer visually does nothing, but the hit box is still extended, and connectors can still be placed on it. These connectors appear to float until the game is reloaded, at which point the arms of the pole are rendered correctly.

Also, sometimes it is impossible to climb a pole. It is as if arms have been extended off of the top block in all four directions; there is no visual effect or visible hitbox, but climbing the pole is only possible if you can jump and 'grab onto' the top block from a different block.

**Comment by XFactHD** [comment]
The extensions not being rendered until you relog is known and it is an issue with MC itself. It can also be fixed by simply placing a block next to the post to cause a block update.

**Comment by BluSunrize** [comment]
^ that, basically =P

**Comment by XFactHD** [comment]
@Blusunrize you could try calling worldObj.markBlockRangeForRenderUpdate(pos, pos) in onUpdatePacket() in TileEntityIEBase, that might fix issues where rendering is affected by values in your TileEntities.
