### ISSUE TITLE
Floodlights not working properly

### ISSUE THREAD

**Issue by TheMrCaveman** [BluSunrize/ImmersiveEngineering#1678]
Issue Description:

FloodLights won't turn on.

What happens:

When you connect lv wire to floodlight and connect it to proper power source it won't turn on.

Versions:

Minecraft 1.10.2
Forge 12.18.2.2123
Immersive Engineering 0.10-48

**Comment by Crossfire50** [comment]
Turn the floodlight on with a lever.

**Comment by TheMrCaveman** [comment]
That works sometimes

**Comment by mindforger** [comment]
@TheMrCaveman did you wait a couple of seconds between flipping the lever? it may take a moment to spawn and despawn the light source blocks

**Comment by TheMrCaveman** [comment]
eehm yes i will take a look @ it properly tonight and see if i can record the behaviour of this issue!

**Comment by markriemann** [comment]
Not working still.

When i hook up a breaker switch to the floodlight, it rotates the floodlight and not light turns on.
![floodlight](https://cloud.githubusercontent.com/assets/5578510/22263967/edfa2424-e23b-11e6-84db-d5374ad25a77.png)


Versions:
Minecraft 1.10.2
Forge 12.18.3.2185
Immersive Engineering 0.10-53

**Comment by mindforger** [comment]
i can not see a lever on your floodlight

**Comment by markriemann** [comment]
Thanks. That was the issue. Missed that.
