### ISSUE TITLE
[0.10-48] Possible crash with RFTools Builder + Wooden Storage Crate

### ISSUE THREAD

**Issue by SPMoo66** [BluSunrize/ImmersiveEngineering#1679]
I activated a Builder (quarry mode) with an IE Wooden Storage Crate on top and the server crashed. It only happened the second time I activated it, not the first, so it doesn't happen 100% of the time.

https://github.com/McJty/RFTools/issues/837

http://pastebin.com/HbHcbH33

**Comment by mindforger** [comment]
>and the server crashed

crash report, used version, forge version, modlist ... so many questions

**Comment by SPMoo66** [comment]
Sorry, @mindforger I left the crashlog alone in the linked issue. Though, the exact version of IE used was in the title to begin with.

**Comment by BluSunrize** [comment]
Yeah issue on IE's side
Will fix.
