### ISSUE TITLE
Excavator MultiBlock Structure 

### ISSUE THREAD

**Issue by porteriscool** [BluSunrize/ImmersiveEngineering#168]
I am currently trying to create the Excavator multiblock structure according to what the engineer's manual states and how to construct it, however, when I hit each block, and I mean I hit every block that is visible with the engineer's hammer to try and form this multiblock structure, it didn't create the Excavator structure. I made it on the ground and in the air for both testing purposes just to make sure that I wasn't doing anything wrong. Currently running on version 0.3.3. If anymore info needed, ask and I shall proceed to answer to the best of my ability.
![2015-07-03_08 39 16](https://cloud.githubusercontent.com/assets/12450943/8499337/dc5a974c-215f-11e5-8422-d212409c7bfd.png)
![2015-07-03_08 39 23](https://cloud.githubusercontent.com/assets/12450943/8499341/de1699fa-215f-11e5-8563-aec48ae42204.png)
FIXED: This build in the picture above is wrong, however fixed the build itself, but still doesn't create the structure.
![2015-07-03_08 39 38](https://cloud.githubusercontent.com/assets/12450943/8499342/df1ee5fa-215f-11e5-81f4-cab7818f02a3.png)
![2015-07-03_08 39 46](https://cloud.githubusercontent.com/assets/12450943/8499344/e0029dd6-215f-11e5-8087-16b2a0c07b8b.png)

**Comment by BluSunrize** [comment]
you click it from the center at the back, works perfectly fine for me.

**Comment by porteriscool** [comment]
I built now four of these structures, one in the ground, one sitting on the ground, one raised above the ground, and one higher than the previous one that was raised above the ground, and none of these structures want to be built.

**Comment by BluSunrize** [comment]
360° view and a disasembled (wheel seperate) one too, please?

**Comment by porteriscool** [comment]
Will do tomorrow, unfortunately not near my computer right now and most convenient time for me to be near my computer is tomorrow, I am currently on my phone. So tomorrow, I'll get those images for you.

**Comment by porteriscool** [comment]
Seemed to fix after launching my launcher again. Don't know what was wrong to begin with, but seems fixed.
