### ISSUE TITLE
[question] relic shadder grabbag 

### ISSUE THREAD

**Issue by Tsukiumy** [BluSunrize/ImmersiveEngineering#1681]
i was doing the gaia ritual from botania, and after killing the gaia II i dropped some of those, but i cant open these, only convert it to the epic one, is it intended, to be some added via some sort of config, or wasn't implemented yet?

**Comment by mindforger** [comment]
you mnean you convert it from a "relic shader grabbag" to an "epic <whatever> shader" ? thats totally intended then. 

you can right cklick with the shader on any object listed in the lore to make it looking better :)

**Comment by BluSunrize** [comment]
You can't open Relic-level shader grabbags because bags are designed to only drop shaders of their level or above.
And since there are not Relic-level shaders, and the Cosmic level is gone without Avaritia, there is nothing the bag an decrypt into.
