### ISSUE TITLE
CraftTweaker dependency for compile

### ISSUE THREAD

**Issue by jco2641** [BluSunrize/ImmersiveEngineering#1682]
After cloning this repository and trying to build it, the compiler blows up with errors about minetweaker classes being undefined.
The dependency isn't listed in build.gradle, and there isn't a definition of a local lib directory to find required jars in.
I've found and built the current Crafttweaker, but I don't know where to put the .jars in to make forge-grade and idea happy.

**Comment by GirafiStudios** [comment]
Fix already PRed https://github.com/BluSunrize/ImmersiveEngineering/pull/1673

**Comment by BluSunrize** [comment]
PR has been adopted
