### ISSUE TITLE
Voltmeter crashing server

### ISSUE THREAD

**Issue by TheLegitimantis** [BluSunrize/ImmersiveEngineering#1683]
Sometimes, using a voltmeter on a machine with a large volume of RF moving through it will crash my server. Sometimes it happens and sometimes it doesn't.

Here is my server's crash report: http://pastebin.com/c2bQsaU6

This happens with capacitors and the excavator, mostly.

This happens with 0.10-48, Forge version 12.18.2.2114

**Comment by malte0811** [comment]
Does this happen only when actually right-clicking with the voltmeter or at a random time when looking at a machine? (I would "prefer" the latter since I would know what is causing this in that case)

**Comment by TheLegitimantis** [comment]
This happens when looking at the machine with the meter held in hand. I've never had an issue with right clicking with it.
