### ISSUE TITLE
Transformer cable rendering issues

### ISSUE THREAD

**Issue by xenoflot** [BluSunrize/ImmersiveEngineering#1685]
Hi, some transformer cable/connector rendering issues remain in the current version.

1. I placed down 4 HV transformers such that the LV side is on the left. http://i.imgur.com/aScRzVP.png
2. After attaching HV cables, one of the transformers has flipped orientation. http://i.imgur.com/eGsl5FE.png
3. I removed the HV cables and the orientation returned to the original however after connecting a LV cable to the correct connector, the connected transformer flipped. http://i.imgur.com/6NgSY2L.png
4. After stripping back and reconnecting the HV cables, a different one has flipped. http://i.imgur.com/LOIhXmq.png
5. The flipping when the LV wire is connected seems mostly consistent. http://i.imgur.com/NbMwkjW.png

Cheers!

immersiveengineering-0.10-48
forge 2122

**Comment by BluSunrize** [comment]
Yeah the logic on those connections is a bit wonky. In theory it should be based on distance from the connector.

**Comment by malte0811** [comment]
I'll see how hard fixing this would be, if it is doable reasonable quickly, I'll fix it now.

**Comment by xenoflot** [comment]
If I may make a suggestion, don't have dynamic flip/rotation at all. Just enforce LV/MV wires to the short side and HV wires to the tall side, and let the engineer sort out visually-crossed wires by rotating the transformer around the Y axis using the hammer. That way engineers can decide for themselves if they want connector heights to line up in a row, or untangle visually crossed wires (if external connections result in them). In theory that should be easier to code, too.

**Comment by malte0811** [comment]
It is doable, it is just a mess in its current form (I did something similar with breaker switches). I will rewrite that code when I have time for it, maybe tomorrow or Sunday.
