### ISSUE TITLE
Cutters don't disconnect wires on HV Transformer connectors, but still use durability.

### ISSUE THREAD

**Issue by xenoflot** [BluSunrize/ImmersiveEngineering#1686]
Subject says it all, I think!

immersiveengineering-0.10-48
forge 2122

Cheers!

**Comment by BluSunrize** [comment]
They actually do work. Click the bottom block.

The wirecutters currently fail to check for the masterblock, and as such, only work when clicking the bottom block of the transformer. I'll throw a more convenient fix for this in the next push.

**Comment by xenoflot** [comment]
OK, I see what you mean. If I click the bottom block, I do get the wires back.

Regarding cutter durability, I think the call to that function needs to be made dependent on a successful call of the "release wires" function, because my cutters are taking damage any time I right-click on a transformer base or any kind of connector, regardless of whether there are wires present or not.

Thanks!

**Comment by BluSunrize** [comment]
That's a fair point, I'll include that in the fix.
