### ISSUE TITLE
Charging Station Dupe Bug

### ISSUE THREAD

**Issue by Lipo1990** [BluSunrize/ImmersiveEngineering#1687]
I've encoutered a duplication bug on the Immersive Engineering version 0.10-48 with the Charging Station.
If you hold a chargable Object in the second hand an use the Charging station it gets duplicated.

Some sample pictures with a railgun:
http://puu.sh/smxIt/a849fc03f8.jpg
http://puu.sh/smxPm/83c3d3a307.jpg
http://puu.sh/smxMO/cd57de8605.jpg
http://puu.sh/smxR4/a8309b4791.jpg

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/blocks/metal/TileEntityChargingStation.java#L308 `EntityEquipmentSlot.MAINHAND` needs to be `hand`. I won't make a PR for this since it is an easy 1 line fix.

**Comment by BluSunrize** [comment]
Yep, found that after got the mail on this one. Will be included in the next batch push.
