### ISSUE TITLE
Tesla Coils(?) crash the games sound manager

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#1692]
I assume it's the tesla coils because i got a 5x5 square surrounded by them and the crash doesn't seem to happen without the tesla coils on.

IE 48
mc 10.0.2
forge x2122

crashlog:
http://pastebin.com/a2W9VWmj

edit: pastebinned the crashlog

**Comment by AEnterprise** [comment]
github doesn't have spoilers but you can put the crash in a gist/pastebin and then put the link to it instead of the full log in your post

**Comment by BluSunrize** [comment]
Next time, please read the contribution guidelines and spoiler your crashlog =)

I'm a little stumped on what causes this one though. Shouldn't be able to throw a concurrent modification exception here. Sounds for the tesla coil are only processed in its clientside update method

**Comment by mindforger** [comment]
didn't you deal with that error in the past with the generator and crusher? i could not find the issues anymore but the report looked very similar

**Comment by malte0811** [comment]
> Sounds for the tesla coil are only processed in its clientside update method

No they aren't. [This](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/blocks/metal/TileEntityTeslaCoil.java#L280) call is in the `receiveMessageFromServer` method, which is probably called from the networking thread. I'll implement a thread safe way for that, shouldn't take too long.

**Comment by BluSunrize** [comment]
fair enough.
Think you can get it PRed today?

**Comment by malte0811** [comment]
If I don't find any other nasty bugs I should be able to make the PR today.
