### ISSUE TITLE
Refinery not outputing biodiesel. [Direwolf20 1.10.2]

### ISSUE THREAD

**Issue by Dregek** [BluSunrize/ImmersiveEngineering#1693]
Immersive Engineering 0.10 - 48

Refinery refuses to output Biodiesel regardless of the fluid system use. I have attached every fluid pipe possible to the refinery output slot including directly linking a tank. breaking and reforming the refinery multi-block has no effect.

**Comment by BluSunrize** [comment]
Could you please provide some pictures of your setup?

**Comment by Dregek** [comment]
https://imgur.com/a/VKn7q

ignore the posts in the background having no cables im rewiring read for hv lines

**Comment by BluSunrize** [comment]
Have you tried it with IE pipes as well?

**Comment by Dregek** [comment]
Yes, soon as ender io's pipes wouldn't pump I tried IE's fluid pipes. i have now moved the refinery into another area and it pulled out from the internal tank but only if I put an ended io tank adjacent to it. It wont push directly into pipes

**Comment by BluSunrize** [comment]
I think the problem is, that EIO conduits don't accept fluid input. To my knowledge they can only pull out themselves. Which is a bit odd but there you are.

**Comment by DanceInferno** [comment]
Same issue same pack. I can connect EnderIO pressurized fluid conduits from both the Squeezer and Fermenter to IE tanks without issue. I can connect an EnderIO Fluid Tank to the Refinery output and the Biodiesel is outputed to that. I can then connect the conduits to the Fluid Tank and it outputs to the IE tank ok. So there is an issue it seems between the EnderIO conduits and the Refinery.

**Comment by BluSunrize** [comment]
Well @DanceInferno if you read above, IE pipes might be the solution to your problem since EIO ones apparently don't work.
