### ISSUE TITLE
Startup crash

### ISSUE THREAD

**Issue by Akai1** [BluSunrize/ImmersiveEngineering#1695]
Game [crashes](https://gist.github.com/Akai1/411d6f689e2006828ba9b92a67060634) on startup.

**Comment by BluSunrize** [comment]
Already fixed. Wait for Build 49 on Curse.

**Comment by BluSunrize** [comment]
Actually, I have to add to that.
That doesn't look like a normal TConstruct build number.
That looks like a custom build. Pretty sure neither me, nor boni cater to those.
