### ISSUE TITLE
tinkers and immersive

### ISSUE THREAD

**Issue by MeinKraft** [BluSunrize/ImmersiveEngineering#1696]

**Comment by Cours3r** [comment]
I'm having the same issue. Attached is the crash log.
[crash-2016-11-19_15.07.27-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/601704/crash-2016-11-19_15.07.27-client.txt)

**Comment by mindforger** [comment]
first, please spoiler it, using pastebin, tihs wall of text is hard to read

second please post the actual crashlog not the logfile

This crash report has been saved to: /games/ni750123_1/ftproot/minecraft/./crash-reports/crash-2016-11-19_20.05.45-server.txt
