### ISSUE TITLE
[1.10.2] Teslacoil Crash

### ISSUE THREAD

**Issue by ProxyPlayerHD** [BluSunrize/ImmersiveEngineering#1698]
I wondered what the Flourecend Tube does.
I was Able to Place it and thought to myself
"maybe placing it near a Tesla Coil will Light it up!"
and so i did it. Nothing Happend tho. Filled with Disapointment i looked into the Creative menu for Other Things that i haven't seen yet. found the Gun Powder Barrel and placed it near the Coil. game decided that was bad anc Instantly Crashed.

TL;DR
Gunpowder Barrel + Teslacoil = Crash

http://pastebin.com/Np9WYVT0

**Comment by malte0811** [comment]
Leaving the crash aside, the fluorescent tube should light up when near an active tesla coil. I'll take a look at that later today.
What version of IE are you using? 48 or 49?

**Comment by ProxyPlayerHD** [comment]
wait. nope... no no no no.
Turns out i'm just an Idiot. because i didn't gave the Tesla Coil a Redstone Signal.
so, not the Tesla Coil in Combination with the Barrel made me Crash. instead just the Barrel itself.

There some More blocks that do the same.
and some Pages in the Manual.

**Comment by BluSunrize** [comment]
If pages in the manual make you crash, please submit a separate issue with crashlogs.
Thank you ^^
