### ISSUE TITLE
Crash when opening Arc Furnace entry in manual

### ISSUE THREAD

**Issue by primetoxinz** [BluSunrize/ImmersiveEngineering#1699]
Forge : 1.10.2-12.18.2.2151
ImmersiveEngineering : 0.10-49
http://paste.ee/p/oBChV

**Comment by malte0811** [comment]
Try removing Optifine, it is not supported as stated in the contributing guidelines.

**Comment by JadeDrgn** [comment]
This happens to me as well without optifine on version 0.10-50
http://pastebin.com/nUNs54cV

**Comment by primetoxinz** [comment]
it was fixed by dc3b707
