### ISSUE TITLE
Immersive Engineering and Tinkers Construct incompat

### ISSUE THREAD

**Issue by NEXUS2345** [BluSunrize/ImmersiveEngineering#1700]
Attempting to boot up a modpack with Immersive Engineering and Tinkers Construct, crashes during startup.

Crash reports: https://gist.github.com/NEXUS2345/a40526b10b38643e03762baaad39b042

Immersive engineering version 0.10-49
Tinkers Construct 2.4.6b

**Comment by BrisingrAerowing** [comment]
I get the same crash. Same versions as well.

**Comment by NEXUS2345** [comment]
Woops, realised it is a dupe of #1697, so I will close this.

**Comment by NEXUS2345** [comment]
@BrisingAerowing downgrade to 0.10-48 or find the Maven build of Tinkers
