### ISSUE TITLE
coke oven doesn't work with fluid pipe

### ISSUE THREAD

**Issue by AnnonymousTrollerXXD** [BluSunrize/ImmersiveEngineering#1701]
I'm making automatic treated wood factory but the problem is the fluid pipe do not transport cresote from coke oven.Did it a feature or a bug? if it a feature please add the improved coke oven.But if it a bug
Please fix it or you will be quickscoped by ShakingShrek THX

**Comment by kane-thornwyrd** [comment]
[Please read the guidelines for contributing :smile: 
![screenshot_28](https://cloud.githubusercontent.com/assets/625236/17993707/6aa47b84-6b52-11e6-9a9d-ef5d6e05a4ca.png)
](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/CONTRIBUTING.md)

**Comment by BluSunrize** [comment]
^ that

Please provide us with pictures of your setup, otherwise we won't be able to assist with your issue.
