### ISSUE TITLE
[1.10.2] Minor recipe issue with Graphite Electrode

### ISSUE THREAD

**Issue by b0bst3r** [BluSunrize/ImmersiveEngineering#1705]
ImmersiveEngineering-0.10-49

In Engineers Workbench JEI shows the recipe as a 2x2 grid of HOP Graphite Ingots, however that recipe does not work and the only one that does in the Workbench is 1 single stack of 4 ingots.

**Comment by BluSunrize** [comment]
Fixed this because I was impatient. Sorry malte <3
