### ISSUE TITLE
Crash on modpack load

### ISSUE THREAD

**Issue by the-creamster** [BluSunrize/ImmersiveEngineering#1706]
https://github.com/suranis/TC-Expert-Mode-Modpack/issues/1

**Comment by XFactHD** [comment]
Your link is broken.

**Comment by BluSunrize** [comment]
that link gives me a 404, I think your repo might be private.

**Comment by the-creamster** [comment]
yeah its a private repo; let me see what i can do.

**Comment by the-creamster** [comment]
Ok to begin with i'm getting the following crashes at different stages of pack loading(normally around stage 2/3) with my one which is tweaked off the previous working build. The strange thing about it is that i can launch the pack by the other admin which has identical mod versions and it doesn't crash on me.

The order in which they were crashing seem to correspond to the mod loading order:

Draconic Evolution
Ender Storage
Immersive Engineering
Translocators
CodeChicken Lib
Crash Reports
Draconic Evolution: https://gist.github.com/the-creamster/f61988d0bd1ec74a0d7f3012649cce99
CodeChicken Lib: https://gist.github.com/the-creamster/125991568c9fa3cf3681ee58a470d777
Translocators: https://gist.github.com/the-creamster/2cb3fe5103e13f50497319952dc749fb
Immersive Engineering: https://gist.github.com/the-creamster/f168aba00ebe944ef86645abd0768ee4
Ender Storage: https://gist.github.com/the-creamster/da52b6bbeb67637a62ecf4b27a8e7c6f

Any thoughts as to why my tweaked pack crashes and the other one with identical version isn't???
Cheers, The_Creamster.

**Comment by mindforger** [comment]
for IE it's simple
>java.lang.NoSuchMethodError: slimeknights.tconstruct.library.materials.BowMaterialStats.<init>(FFF)V

you need build 49 as tinkers added new bow stuff causing this crash

for the others, I have no idea but as a rough guess would be to use a proper minecraft version you are using the built in 1.8.0_25 but current is _111 or even higher :D

**Comment by BluSunrize** [comment]
the IE error is fixed by using build 49. For the rest: Not my problem =P

**Comment by mindforger** [comment]
no @BluSunrize it IS Version 49!

**Comment by BluSunrize** [comment]
Exactly. They need 50. 49 doesn't have the version check. (I sneakily fixed it)

**Comment by the-creamster** [comment]
for some even weirder reason J8 update 111 doesn't work for me. MC doesn't even launch as it juts gives me invalid memory heap error. its a 1.10.2 pack btw

**Comment by the-creamster** [comment]
I was using build 50 just back-dated to build 49

**Comment by mindforger** [comment]
maybe you accidentially downloaded the 32bit version, common mistake

http://javadl.oracle.com/webapps/download/AutoDL?BundleId=216434

**Comment by the-creamster** [comment]
it must have yet i selected the 64-bit installer; thx for the link
