### ISSUE TITLE
[IE 49] Splitting Conveyor Belt/Dropping Conveyor Belt don't input into inventories/item routers

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#1707]
Both the Splitting Conveyor and the Dropping Conveyor only drive the entities against the side of any inventory block rather than moving the item into it.

to clarify: dropping conveyor belts can use their dropper to input into inventories, but they can't use their conveyor to input from the side

ie 49
forge x2122
mc 1.10.2

**Comment by BluSunrize** [comment]
Huh. Never considered that on the droppers. Cheers for the report, I'll look into it.
