### ISSUE TITLE
[IE 49] Minor: Crusher Recipes in JEI don't show input items

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#1708]
The recipes are still working, though, so no biggie.

ie 49
jei_1.10.2-3.13.3.373
forge x2122
mc 1.10.2

**Comment by BluSunrize** [comment]
Has already been fixed in Build 50, go update =P

**Comment by MalkContent** [comment]
o dang, updates dropping fast now. thanks <3

**Comment by BluSunrize** [comment]
well 49 was a bit of a rushjob, so I had to followup =P
