### ISSUE TITLE
[IE 50] Jump Cushions cause crash

### ISSUE THREAD

**Issue by Doragoon01** [BluSunrize/ImmersiveEngineering#1709]
Looking at a Jump Cushion Block crashes the client.  (Other cloth blocks are fine.)

at blusunrize.immersiveengineering.common.blocks.BlockIETileProvider.getExtendedState(BlockIETileProvider.java:204)
	at blusunrize.immersiveengineering.common.blocks.cloth.BlockClothDevice.getExtendedState(BlockClothDevice.java:92)

*Yes i'm aware of the contribution guidelines, i'm just not good at figuring out what is needed.  I hope this information helps.

**Comment by mindforger** [comment]
the full crashlog for example would help alot and the used version like described in the guideline

and if you read the guideline, please do not text wall it, either attach the file or upload it to pastebin or something like this

**Comment by BluSunrize** [comment]
This is fine actually.
I know where the issue lies. My fault when I made shaders work on balloons.

I'll see to fixing this, thank you for the report.

**Comment by BluSunrize** [comment]
^ that should fix it, but I'll leave this open for now.

**Comment by Doragoon01** [comment]
version was in the post title, and i'll try to figure out how to pastebin before next time.  Thank you for your help.

**Comment by xenoflot** [comment]
@BluSunrize Did this make it into release 50?
I'm getting something that looks pretty similar with 0.10 - 50: http://pastebin.com/CWjZFZBw

**Comment by BluSunrize** [comment]
The title of hte report has "IE 50" in it. >_>
So no, it didn't make it in. Otherwise this would be closed as well.

**Comment by xenoflot** [comment]
Apparently some days I'm not as sharp as usual!
