### ISSUE TITLE
[QUESTION] Lightning rod

### ISSUE THREAD

**Issue by Dmitchell94** [BluSunrize/ImmersiveEngineering#1711]
So after trying to figure out how to get the lightning rod to work and trying to use the Weather2 mod by corus to force lightning, I read that the lightning rod will generate its own lightning in a storm. Now will this work with a mod like the Weather mod thay replaces vanilla weather?

**Comment by BluSunrize** [comment]
Yeah, should do, to my knowledge.

**Comment by Dmitchell94** [comment]
Glad to hear that, now to figure out why my lightning rod is not working
