### ISSUE TITLE
FTB Infinity Evolved crash when using arc furnace

### ISSUE THREAD

**Issue by Simcra** [BluSunrize/ImmersiveEngineering#1712]
http://paste.feed-the-beast.com/view/e6dedbc6

**Comment by bookerthegeek** [comment]
Put your logs on ghist and link them.w

**Comment by mindforger** [comment]
there is no crashlog, onlay a seemingly truncated logfile, please upload the actual crashlog!

**Comment by Simcra** [comment]
http://pastie.org/private/h8hjq2qce0pnfyb826jyw

**Comment by mindforger** [comment]
thx :)

**Comment by BluSunrize** [comment]
That's a 1.7 issue. I really don't cater to those anymore.

@Simcra what exactly did you do to the furnace? Because it erroring out on finding its master block. That shouldn't happen unless it was moved with frames or something like that.

**Comment by Simcra** [comment]
@BluSunrize Absolutely nothing, it happened at a random interval and I have tried a number of possible fixes such as rebooting the server and rolling back the server, so far the only solution has been to get rid of the arc furnace by using MCEdit.

**Comment by BluSunrize** [comment]
You're the first person ever to report this and 1.7 has been dead for a while, hence why I have to ask that stuff.
Is your ArcFurnace built on a chunk border? If so, could you please provide a screenshot on how the border separates it?
Also, is this issue when you are logged in, or is the server running and crashing without people logged on?

**Comment by Simcra** [comment]
It is possible that the arc furnace is built on a chunk border, the crash occurs when any player joins the server and it is a client-side only crash. The server is unaffected.
