### ISSUE TITLE
[Feature Request] Adaptive Pipe Valve

### ISSUE THREAD

**Issue by mindforger** [BluSunrize/ImmersiveEngineering#1715]
I just had an idea about an pipe addition! 

an adaptive pipe valve ... adaptive in the sense like the valve itself beeing useless and behaving like a normal pipe UNTIL you add either a handwheel (fancy looking, rotating when activated with an open/close indicator) or add an electric valve gear that can be triggered from redstone signal

the idea to use the adaptive aproach should minimize the blockstates required for the valve design, as it connects to the gear or wheel like to a pipe and the handwheel or gearbox will cover the open pipe face

if you don't mind to go through this blockstate fuzz, you can make it a vavle with a handwheel that reactos to redstone as a single block :)

for the adaptive aproach, just imagine the funtion of an thermostat valve on your radiator, where the handwheel moves the pin of the valve

or make the handwheel/gearbox attach to any common pipe converting it to a valve then

**Comment by BluSunrize** [comment]
Mind, we've been over this. Adding and removing stuff from the pipesystem is a logistical nightmare.
Why do people keep requesting valves .-.

**Comment by mindforger** [comment]
well it just flashed into my mind and i've forgotten about this issue with the logistics

sorry :P

but for a real steampunk flavour pipes just **_neeeeed_** handwheel valves XD

**Comment by ToadsworthLP** [comment]
@mindforger Yeah, would be nice to have. Also, it's not steampunk because there's no steam =D
