### ISSUE TITLE
cpw.mods.fml.common.LoaderException: java.lang.NoSuchFieldError: rock

### ISSUE THREAD

**Issue by eslachance** [BluSunrize/ImmersiveEngineering#172]
While attempting to integrate 0.3.3, I get this error. 
http://pastebin.com/EXjcpPnr

Putting back the previous I was using (0.2.3) makes the error disappear.

**Comment by eslachance** [comment]
Note: Adding to the Direwolf20 pack on FTB Launcher.

**Comment by BluSunrize** [comment]
You downloaded the deobfuscated version for whatever reason, instead of the normal download. I mean, it does say "for mod developers only" on it...

**Comment by eslachance** [comment]
Oh I think I understand. On the page, the deobfuscated version at the bottom is a link, while the filename for the regular version isn't. Didn't quite notice the Download button at the top-right, in grey, very unobtrusive...
