### ISSUE TITLE
Shader Lag

### ISSUE THREAD

**Issue by Doragoon01** [BluSunrize/ImmersiveEngineering#1721]
I'm sorry this isn't going to be very helpful, but it's the best i can come up with.

The shader items are causing a lot of client/render lag.  If I just search JEI for "shader:" then my FPS gets cut in half.  The same thing happens if i open an inventory with a lot of them in side, or if they are dropped on the ground as entities.

I'm currently running MC 1.10.2, Forge 2104, and IE 50

**Comment by BluSunrize** [comment]
Can you reproduce that in an instance with just IE?
Can you check if performance is worse compared to IE Build 48?

**Comment by Doragoon01** [comment]
Just tested it in a new world with just IE and JEI, and it was still there.  I filled a chest with shaders and confirmed that it was still causing lag.  
I then loaded up the world with only IE, and opening the chest still causes the FPS drop. An empty chest does not cause any FPS drop, nor do chests filled with other random items.

**Comment by BluSunrize** [comment]
Okay, it appears I introduced this with my shader rework then.
I have a vague suspicion as to what caused this, will investigate.

Thank you for the report.

**Comment by BluSunrize** [comment]
I can't replicate this in a manner as dramatic as you describe. The shaders in JEI make me lose ~8-10 frames, but nothing more.
What FPS values do you usually run with that gets cut in half by them?

**Comment by Doragoon01** [comment]
I'm normally at 60 fps.  This was dropping me to 20-30 fps.  Each individual shader being rendered is insignificant.  It's only with a full inventory of them, or creative tab/JEI open to that page that it is a problem.  It's not game breaking since i tend not to need high FPS while rummaging in inventories, nor are there usually dozens of shaders littering my floors.

I only noticed this because some other mod's recent update has been causing so much render lag that my husband (and his slower computer) couldn't take it.  While I was trying to sort out the cause (running around with alt-F3 on) the graph went red when flipping through JEI looking for something else.  This was unusual, and i looked into it as a possible cause.  It wasn't.  (As for the cause of the original frame drops, i'm suspecting it's BoP.  So not your fault.)

Regardless, thank you for looking into it.
