### ISSUE TITLE
[Feature Request] Mid tier power generation - burning ethanol

### ISSUE THREAD

**Issue by xepps** [BluSunrize/ImmersiveEngineering#1723]
I've recently started playing through the latest direwolf20 pack, trying to use IE as much as possible.  One issue I've had is about the different kinds of power gen, and I think there is a gap that needs filling. 

The water wheel, and wind mills all generate between 20 and 70 rf/t, and thermoelectric generator sits at 40rf/t (with uranium and water). These are place and forget generators, and I think they are well balanced within the mod.

Then there's the lightning rod that generates 16000000 rf. I haven't yet tried this, as I'm not sure if it will generate a reliable enough source of rf. Forgive me if this feature is actually suitable for my request, as one lightning strike every half an hour is roughly equivalent to 512rf/t. How frequently can I expect these strikes?

Lastly, there's the diesel generator that generates 4096rf/t, but requires a lot of infrastructure to keep it maintained (ability to grow, for example, 1 potato and 1 seed per second), along with fermenters, squeezers, refineries, pumps and power to go with them. 

What I want to suggest is another active generator that is somewhere in between: burning ethanol. Since it would require some of the infrastructure required to make diesel (a farm and fermenter), I feel it would be balanced outputting around 512rf/t. This would also make mv cables more useful, as I think they are under utilised at the moment.

After thought: I guess a way to quickly implement this would be to let the diesel generator burn ethanol.

**Comment by GB-Hijacker** [comment]
I thought about this as well, but I don't know how Blu has coded his objects. In the config files, the diesel has a definitive output figure while the dynamo has an output that is augmented (multiplied I guess?) by speed of the wheel attached.

I would say to keep with the realism IE strives for, a mid tier generator like a standby home generator would be more ideal. Make it a multiblock, but have its intake take ethanol and maybe a power output of something like 1024. Abother option would be to have the diesel multiblock be constructed like normal, but it's really an ethanol gen. Attach a "diesel manifold upgrade" to it, whack the hammet, and it turns into the diesel.

**Comment by xepps** [comment]
Agreed - another (smaller) multiblock would be ideal to burn ethanol.

**Comment by mindforger** [comment]
well you could probably use the search or scroll through the list and find in many of the closed issues almost every time the same explanations of why Blu does not think so! :)

**Comment by BluSunrize** [comment]
@mindforger wut?
Think you're on the wrong issue?

I don't think I've ever commented on mid-tier powergen suggestions before.
Only thing I can say on the matter is that it's currently not my main focus. I can definitely keep it in mind for the future, but right now it's not something I want to work on ^^

**Comment by mindforger** [comment]
i think i should remove this firefox-like extension from chrome ... it did this like 3 times now even in forums ... stupid IT service forbidding the use of firefox ... sorry ...  i think the extension sometimes send the posts to the wrong tab

**Comment by BluSunrize** [comment]
It's fine, no worries =P

**Comment by xepps** [comment]
@BluSunrize Thanks for considering my suggestion. For your information, my in game solution to my problem was a load of thermoelectric generators (around 15 seemed to be enough). It doesn't seem the most elegant, but I think it was the best solution available. Doesn't detract from my love for the mod though.
