### ISSUE TITLE
[1.10.2] Wrong amount of Coke/Blast bricks dropped

### ISSUE THREAD

**Issue by 016Nojr** [BluSunrize/ImmersiveEngineering#1724]
When I break 9 blocks from a formed Coke Oven or a Blast Furnace with a Tinkers Construct hammer it gives me 18 of the blocks (Drops 2 from each block) instead of the 9 it should give me.

Modpack: Direwolf 1.0.0
Forge: 12.18.2.2124
IE: 0.10-48
TiCon: 1.10.2-2.5.6b

This was done on a server.

@xbony2

**Comment by BluSunrize** [comment]
Can you reproduce this in singleplayer?
Can you reproduce this with just TCon and IE?

**Comment by 016Nojr** [comment]
* I can not reproduce this in singleplayer


But here comes the interesting part, in SINGLEPLAYER when I tried this I ended up getting **8** bricks instead of 9 or 18 when breaking a formed coke/blast oven.

This was tried with the DIrewolf pack and with a pure instance with just TiCon and IE

All versions are the latest

Forge: 12.18.2.2151
TiCon: 2.5.6b
IE: 0.10-50

**Comment by xbony2** [comment]
oh noes

damn it

y u do this

not again

@boni-xx

**Comment by BluSunrize** [comment]
I was wondering why he tagged you, lol

**Comment by ArukaAlter** [comment]
I can confirm that breaking in singleplayer causes one block to be lost, it's a long running issue, but I hadn't the time to report it myself.

**Comment by yepidoodles** [comment]
I am also seeing this on my SpongeForge Server.

Versions:
SpongeForge: 5.2.0-BETA-2223
Forge: 2221
Immersive Engineering: 0.10-57
Tinkers' Construct: 2.6.3
Modpack: https://www.technicpack.net/modpack/172-dragontech-testserver.408937

- Alice
[DTMC](http://dragontechmc.com)

**Comment by ArukaAlter** [comment]
It is on Sponge's side.

**Comment by 016Nojr** [comment]
> It is on Sponge's side.

I dont run Sponge in singleplayer though ;)
