### ISSUE TITLE
Crash when trying to view Squeezer (latest java and Immersive engineering, Forge 1.10.2

### ISSUE THREAD

**Issue by snacdaws** [BluSunrize/ImmersiveEngineering#1726]
[crash-2016-11-24_11.13.42-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/611794/crash-2016-11-24_11.13.42-client.txt)

**Comment by mindforger** [comment]
duplicate number 9 ... seeeeriuosly use the search, it is also on the front page of open issues!

**Comment by BluSunrize** [comment]
You cannot "sticky" issues on github. Instead, you could read the contribution guidelines before posting and use the search function ;)
