### ISSUE TITLE
[Feature Request] Give config setting to allow custom tool/custom wiring items in Toolbox

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#1728]
it'd be kinda neat if one could allow items from other mods in these toolbox slots :)

**Comment by PrincessRTFM** [comment]
Kinda like Bibliocraft's config, where you give it words that it checks for in the name of the item? That could be pretty cool, yeah.

**Comment by BluSunrize** [comment]
There is an API that allows it, but it requires the other mod to hook into it.
I do not plan for it to become a config option.

**Comment by MalkContent** [comment]
that's fair
