### ISSUE TITLE
Cannot power rftools machines with wire connectors 

### ISSUE THREAD

**Issue by primetoxinz** [BluSunrize/ImmersiveEngineering#173]
https://imgur.com/a/VhaHd

**Comment by BluSunrize** [comment]
Might help if you switch the capacitor to output =)

**Comment by primetoxinz** [comment]
my bad, but none the less the screen still doesn't get power https://imgur.com/a/LyGj2

**Comment by BluSunrize** [comment]
and are you sure you want power going into the screen? because last I checked you needed to power a screen controller.
@McJty this is your mod, input please.

**Comment by primetoxinz** [comment]
yeah, that's it. derp

**Comment by McJty** [comment]
Indeed. It is the screen controller you need to power. Not the individual screens.
