### ISSUE TITLE
Creosote Oil dont fill into Glass-Bottles anymore

### ISSUE THREAD

**Issue by Wubbbi** [BluSunrize/ImmersiveEngineering#1730]
Hey =)

In Version 0.10-50, Creosote Oil from Coke Oven dont fill into Glass-Bottles anymore. But they did in 0.10-48 (DW20 Pack). Did you change that? Is that your intention?

Greetings

**Comment by mindforger** [comment]
creosote bottles are no intended use anymore since 1.10 but should still work when railcraft is installed
but there was a multiplication bug with railcraft that has been fixed with the last builds, maybe thats an outcome of this fix?

**Comment by Wubbbi** [comment]
Ahh ok so thats the Point. I now play on a Server without Railcraft and thats why I does not work anymore.
Well, do you maybe consider to add this back? Because the problem is that the buckets don't stack and my Storage system (chests or AE2) are spammed with those buckets. Also, we dont have any "Tank-System" on our server. So I would say either add back the support for Glass-Bottels or maybe add something like the Railcraft Tanks from 1.7.10 to store those fluids. Otherwise, its pretty furstrating. Or even let this buckets stack! :(

Greetings

**Comment by BluSunrize** [comment]
IE features tanks. They are dynamic sized like Railcraft (and I won't do that either) but tanks are in the mod.

I have no plans to readd glass bottles. Not worth the trouble. You should easily be able to use IEs assembler to craft with fluids anyway.

**Comment by MalkContent** [comment]
*tags on* it'd be neat if one could use the jerry cans to craft treated wood/concrete

**Comment by BluSunrize** [comment]
You can >_>

**Comment by Arminius** [comment]
Hey, I know this is an old issue, but wouldn't it be best if you added a hint into the manual that you can use the jerry can for crafting treated planks and concrete? I never knew this worked until I read this thread.

Also, does the jerry can only work for IE recipes or can it also work for other mods' recipes asking for fluid buckets? Of all the recipes I tried, only buckets worked.
