### ISSUE TITLE
[Suggestion]:  Tesla coil and Fluorescent Tube enhancements

### ISSUE THREAD

**Issue by rahangar** [BluSunrize/ImmersiveEngineering#1733]
I've been playing around with the Tesla coil and the fluorescent tubes, and I have to say they are both a lot of fun.  I have some questions and suggestions.

Question 1:  What is the reason why tubes fall (like sand)?  It is interesting that they do, but just wondering what is the intent?

Suggestion 1:   Arcs between the coil and transparent materials (e.g. glass placed as a border/fence around the coil)
Suggestion 2:   Arcs bounce around transparent materials for a few seconds
Suggestion 3:   Arc color and thickness are configurable
Suggestion 4:   Arcs can zap bees
Suggestion 5:   A block that shimmers like the Fluorescent Tube when inside the electric field, but can be chiseled via Chisels & Bits.

I'm trying to create something like this:

http://a.tgcdn.net/images/products/additional/large/362c_luminglass_inmotion.gif

thanks,

**Comment by BluSunrize** [comment]
Answer to the question: They are entities, not blocks. Entities respect gravity.

1) Arcs already earth themselves into floor and ceiling. There wont be any specifics based on transparency.
2) Nope. Lightning isn't fun to animate as is.
3) No plans for that, as changing the colour of an arc usually requires a gasfilled container. And I don't see myself adding gaschambers to this mod .-.
4) While it sounds fun, it's basically impossible to code that and quite nonsensical ^^
5) Blocks cannot be animated like that. The render engine doesn't allow for it.

**Comment by MalkContent** [comment]
You could add natural gas underground. And portable chickencages that warn you. (I'm kidding, but only half ^^)
