### ISSUE TITLE
Forestry multi Farm pulling items from Conveyor

### ISSUE THREAD

**Issue by robbcrg** [BluSunrize/ImmersiveEngineering#1734]
Confirmed to exist on V.50 ...

I am not sure this is a bug or a feature request. But in any case having items pulled off the conveyor is problematic.

If the conveyor runs too close to the base farm area of the Multifarm the MultiFarm will suck the items (assuming it matches the multfarm config) off conveyors. This is a challenge when building a MultiFarm using only using Immersive Engineering as the output of the farm needs to feed back saplings, seeds, etc. back into the farm to keep it running. And that means the items end up being in range of the MultiFarm 'vacuum'    Rather surprising the MultiFarm range for vacuuming items seems be approx 2 below the base farm level.

My solution for this is to keep the conveyors below the farm and use EnderIO pipes for the recycling. I adjusted the EnderIO pipes to be a more Immersive Engineering recipe as a play balance for my little group.  Note that MultiFarms no longer auto-recycle their items making that a job for the player.

cccccccccc
dddddddd-----
bbbbbbbb-----
                 -----
                 H----

In this ASCII illustration the farm is 4 tall (as they are) with Crops (c), dirt (d) and base (stone brink) followed by an empty row and then the Hatch (H). At the H level the MultiFarm will suck up floating items. So getting the output of H to feed back into H is a challenge. 

I hope that make sense.

Having a sideways push/pull would work assuming it had overflow (for EnderIO I use priorities to feed items back to the Hatch then if that is full drop them onto the conveyor). But that is a feature request.  The redstone wires are used to kill power when the farm output is no longer needed. The redstone wiring is a big advantage to my builds.

A picture showing an example:

![2016-11-25_11 08 32](https://cloud.githubusercontent.com/assets/11152254/20633855/b41620b6-b2ff-11e6-9cb9-094ac182417d.png)

**Comment by BluSunrize** [comment]
I can ask mezz to respect the magnetism guidelines that I setup with WayOfTime.
But on my side, there is nothing I can do.

**Comment by robbcrg** [comment]
Thanks for looking into it. For now i will just have to use alternate pipes for this use case.

**Comment by BluSunrize** [comment]
mezz wrote a fix for this. Not sure if it's released yet, but it is on his github, so I'll close this.
