### ISSUE TITLE
[IE-50] Splitting Conveyores can insert into Inventories in front of them (not the sides though)

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#1736]
A bit strange to explain, but see the below setup and ignore the SuperCircuitMaker circuit (that one just regulates the dropping speed of the hopper).

![conveyorinsertglitch](https://cloud.githubusercontent.com/assets/7753414/20636201/e18232e2-b368-11e6-927d-803cf1e1856c.png)

The hopper next to the circuit drops onto the splitting conveyor, which should have split the stack of Stone between the two conveyor lines. Instead, the right line got half the stack and the hopper in between the lines gets the other half (by the by player is facing west here). Also works with a chest between the lines, so it's not the hopper weirdly collecting the stacks that go to the left.
My best guess is, that the straight conveyor left of the splitter starts pushing the stack entities very early, so it collides with the hopper, making the conveyor insert the stacks into it. Which would make the splitting conveyor the catalyst, but not the real issue.

I hope this is comprehensible.

Edit: Might also be that the splitting conveyor actually CAN insert, just not to the sides (where it pushes it), but to the front (where it usually doesn't push it)

Edit2: Yea, that is what is happening. The splitting conveyor inserts it. I'll make a picture of the setup that did it for me tomorrow.

Edit3: In the following setup, throw items against the hopper/block above it, they will drop onto the splitting conveyor and be close enough to get inserted into the hopper by it.

![splitconveyorinsertglitch](https://cloud.githubusercontent.com/assets/7753414/20639704/3924ac48-b3cb-11e6-8253-cffe90727d93.png)

**Comment by BluSunrize** [comment]
I do believe this is related to another issue where splitting conveyors wouldn't insert into inventories left and right. Instead, they called the super method, which means they tried to insert to the front.
I believe to have fixed this for a future release, after I release IE 51, I'd like to hear back on this, okay? ^^

**Comment by MalkContent** [comment]
Yea, I think so, too :) I was just 2 minutes from going to sleep when I went "wait a minute...", so I just corrected the issue real quick and not much else

**Comment by BluSunrize** [comment]
check if 51 fixed this and report back. I'll reopen this if the issue persists

**Comment by MalkContent** [comment]
nope, works nicely :)
