### ISSUE TITLE
[Feature Request] Allow Efficiency Enchantment on Hammer/give improved Hammer

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#1737]
The scaffolds are awesome tools to help errect buildings and you can play around with them all you want, because you got the hammer to tear them down without wasting tool durability on it. However, once you got enchantet pickaxes, they are much faster at doing that, which is a shame.
So it'd be neat if you could upgrade the hammer through enchantment or craft an improved version (maybe using the old one). Maybe dieselpowered :>
https://www.youtube.com/watch?v=e39nFQrTsXg&t=10s

**Comment by BluSunrize** [comment]
Fulfilled by
https://github.com/BluSunrize/ImmersiveEngineering/commit/ad718fd71ec1fab078ae962733deb9a95c574c06
