### ISSUE TITLE
[Client Crash] Squeezer causing client side crash

### ISSUE THREAD

**Issue by mshirey** [BluSunrize/ImmersiveEngineering#1738]
Immersive Engineering:  version 0.10 - 50
No Optifine, Fastcraft, etc.
Forge: 1.10.2 - 12.18.2.2151
Crash Report: [http://pastebin.com/K10Rwb8b](http://pastebin.com/K10Rwb8b)

Basically, created a squeezer.  After finalizing the machine with the hammer, I noticed there were some rendering issues such as textures in a couple of places flickering.  It looked like there were multiple model parts in the same space causing Z-fighting.  The hit-box was also off as I could walk through all of the blocks on the barrel side of the model.

I decided to re-log to see if the issue to be fixed that way.  The client then crashed just as the world was about to be displayed.  I repeated the process with crash results two more times before creating this report.

The server is not complaining at all.  There are no errors, warnings, or messages of any kind other than the normal login messages on the server.  This appears to be completely client side.  Thankfully I have a world backup from about fifteen minutes ago so I'm going to restore that.

Please let me know if there's any other information I can provide.

Thanks for the great mod,

-- Matthew

**Comment by snacdaws** [comment]
have u tried it without actually additions or using a older version of actually additions

just a suggestion from looking at the log

**Comment by mshirey** [comment]
I backed up both the client and server that were borked just in case someone wanted me to try something like this.  The server is busy right now, but I'll set it up later and I'll try removing Actually Additions and report the results here.

Thanks,

-- Matthew

**Comment by BluSunrize** [comment]
No idea why Actually Additions would interfere I see no reference to in the log files.
First off, I'd recommend you try if this issue is actually reproducable. And if so, check if it's only reproduceable in that specific chunk or others as well.
Should it still happen, one of the first mods I'd try to turn off for a test would be Mekanism, since it has recently been known to cause a multitude of issues.

**Comment by mshirey** [comment]
This issues is definitely reproducible.  I repeated the process, with complete restarts of server and client, three times before reporting the issue.  As for attempting it in a different chunk, that wouldn't be possible as far as I know since I cannot even complete loading the game.  The crash happens just as the world starts to display right after logging in.  I might be able to find another player that was in a different chunk at the time and see if they can log in.  If so, I will report on that as well.

As for Mekanism, I can certainly try removing it.  But I honestly haven't had any serious issues with Mekanism with the latest versions.

Thank you,

-- Matthew

**Comment by BluSunrize** [comment]
Well, obviously you have to reset the world to a backup to perform each test.
Roll back to before creating the multiblock, try another chunk, report crashes.
Roll back again, chuck out mekanism, create the multiblock again, report crashes.

**Comment by mshirey** [comment]
I have done as requested and tried every combination I can think of and at this point I cannot reproduce this issue from scratch.

The only bit of additional information I think I can add at this point is that I am fairly certain that I created the original bugged squeezer crossing a chunk border.

So I'll close this as Unable to Reproduce, but maybe the information will be helpful in the future.  

Thanks so much.

-- Matthew
