### ISSUE TITLE
[Feature Request] Diffrent Tiers of Strcutures by Material used

### ISSUE THREAD

**Issue by Malrama** [BluSunrize/ImmersiveEngineering#1739]
Hey =)

currently, some Sheetmetals (e.g. Lead, Constantan) are not "usefull" in anyway and a more decorative or storage Block. But what do you think about giving them a use? What is when you let people decide what materials they use to build e.g. a Tank and give that tank diffrent tiers depending on the metal used. e.g. a Lead 3x3 Tank can store up to ... 120Buckets. A Iron 520Buckets. A Steal 1020Buckets. (Ignore the numbers itself, its more about the Idea). So you can make those materials usefull in someway.
Of curse, its not about machines. They should stay as they are. (Or you can implement 1-2 Blocks that can be switched out defining the tier. Like energy efficientcy or abilitys).

Why I am asking for this is because I have like 1000 Ingots of Lead, 1000 Ingots of Silver, 1000 Ingots of Nickel and 1000 Ingots of Allumium. And I have 0 Ingots of Iron. The reason is, that those "Additional" Materials are never really used in some way. Yeah, I need 1-2 ingots of lead for the capacitor. Ok, 10-20 Ingots of silver for Electrum. All fine. But this will make them very wanted and give them actuall use.

I hope you consider this in your future development.

Have a nice day.

**Comment by BluSunrize** [comment]
The idea is not necessarily a bad one, except that you don't wanna use lead for a tank. At least not for drinking water :D

I'll give it a thought.

**Comment by PrincessRTFM** [comment]
Maybe something similar for the silo. Actually, what about scaffolding, too? We've got different kinds of sheet metal, it'd be nice to be able to match the scaffolding to it.
