### ISSUE TITLE
So how do I bring HV power "downwards"

### ISSUE THREAD

**Issue by eslachance** [BluSunrize/ImmersiveEngineering#174]
Seems like a silly question, but since HV Connectors can only accept a single connection, and HV Relays can only be placed "under" a block, how am I supposed to bring power from, say, power generation at the top of a 150-block tower (don't ask) down to "sea-level"? Would I absolutely need to spend resources on making transformers or HV capacitors just for this purpose?

I'm not sure I actually understand why HV Connectors can only have one connection.

**Comment by wafflemans** [comment]
like this
![2015-07-03_15 16 31](https://cloud.githubusercontent.com/assets/10857677/8505277/9599173e-2196-11e5-9adf-0c6d2ecf3f38.png)

**Comment by eslachance** [comment]
Ok, so, that doesn't explain why, specifically, HV power can't be brought straight downwards when both LV and MV are fine with it. In fact, connecting 2 HV connectors vertically works fine, it's just that it's too high to do it in one connection. It this just simply arbitrary, that HV can't connect to more than one? I don't need like 6 connections, just... 2.

**Comment by mindforger** [comment]
because LV and MV isolators are pretty small and thus capable of holding the cable while staning upright while beeing fixed on a pole without breaking, when HV connectors are larger and thus more fragile and not able to withstand the stress. By hanging downwards and beeing mounted freely moving, they can adapt to the forces more easily wihout breaking ... okay ... this one was creepy :P

**Comment by wafflemans** [comment]
That was more of an example, but you can have hv relays like this
![2015-07-03_15 29 59](https://cloud.githubusercontent.com/assets/10857677/8505367/6a1b45c6-2198-11e5-85c3-0658bd2bd203.png)
you need to think both horizontally and vertically

**Comment by eslachance** [comment]
@mindforger 's explanation is actually sufficient for me. I'm not an electrical engineer so I'll take your word for it :)

I ended up doing this:
![2015-07-03_18 42 50](https://cloud.githubusercontent.com/assets/643344/8505446/be23d532-21b3-11e5-85ab-e0d6377bd3b0.png)

Let's say my old base (which is moving to down there) is... a little bit of a mess.
![2015-07-03_18 44 18](https://cloud.githubusercontent.com/assets/643344/8505455/cc80db7a-21b3-11e5-9cd1-6b9b0882abe3.png)

**Comment by tebruuls** [comment]
Wafflemans that system works but is resource intensive. A steeper slope on the wires should be better.

**Comment by tebruuls** [comment]
Deep you posted a better one already.

**Comment by wafflemans** [comment]
I was just too lazy to make a steep slope. it was more of "here's what you can do"

**Comment by BluSunrize** [comment]
Apart from mind's fairly scientifical explanation, it's also a form of balance. HV is supposed to be top-notch, and as such comes with some limitations =P
