### ISSUE TITLE
Squeezer wasting power when having incomplete recipes

### ISSUE THREAD

**Issue by mindforger** [BluSunrize/ImmersiveEngineering#1741]
forge 1.7.10 1614
IE 0.7.7

i just stumbled upon an issue with the squeezer

when I only insert a partial recipe, it starts already working infinitely without producing anything

as an example, just drop 1 coke dust into an squeezer and it will start squeezing but never stop until it has the full recipe to output the hop graphite

**Comment by BluSunrize** [comment]
1.7 issues? Come on Mind, you know I don't do those anymore =P

**Comment by mindforger** [comment]
well it MAY be an issue in 1.10 still, i just wanted you to know ... and i won't switch to 1.10 until this power mess is gone and everybody switched to FE XD

**Comment by BluSunrize** [comment]
I tried it in 1.10 couldn't reproduce it, went "The fuck was he reporting", looked at this issue again and only then realized it was 1.7 x3

**Comment by mindforger** [comment]
kay :) glad to hear ... now i have to makeup how i modify my machinery to put in always exactly the number of items in one slot per run

**Comment by BluSunrize** [comment]
Yeah let's just go with "I encourage creativity in managing your inventory" =P
