### ISSUE TITLE
External Heater: Cable connections

### ISSUE THREAD

**Issue by Garbius** [BluSunrize/ImmersiveEngineering#1743]
The external heater cannot be connected with power cables from other mods in 0.10-50. 
I have tested with Advanced Cables, EnderIO power conduits and Fluxed Redstone cables and none of them will connect to any face of the heater. 

Other mods were present during the initial testing, but I have ruled out mod conflicts by limiting to Advanced Cables, IE and JEI only.

**Comment by ArukaAlter** [comment]
They accept IF, transferred from the IE cables, not RF.

**Comment by Garbius** [comment]
They do, however other blocks like the preheater seamlessly convert RF to IF and thus work with other cables. Not having the external heater doing the same is inconsistent, which is why I reported it as a bug.

**Comment by BluSunrize** [comment]
Closed, because any IE machine accepts all three types of power now.

**Comment by mindforger** [comment]
by all three you mean IE intern(IF?), Forge Energy(FE?) and RF ?

**Comment by BluSunrize** [comment]
Yep
