### ISSUE TITLE
[Feature Request] Multiblock capacitor

### ISSUE THREAD

**Issue by Wubbbi** [BluSunrize/ImmersiveEngineering#1744]
Hello everyone, its me again! :D

I have a brand new Idea I would like to share with you. Little sidenote: Currently, I am playing on a server that only runs Immersive Engineering + Magic mods, so my whole game gameplay is about using your extremly wonderfull mod! :)

Now to the Idea:

In my last [Feature Request] I came out with an Idea about how to make the additional Materials more usefull and give the player more possibilities to decide how to build and how worthy it is to use certain materials.
Currently, I am a bit ... lets say unhappy ... with the situation of capacitors (Block to store energy):

1. They are very cheap (compared to other mods and to the materials you need for them to craft)
2. They can't store a lot of energy
and (most importantly for me) 3. Its a pretty mess to create some sort of storrage room with them. Like connecting them to each other. E.g. 6x MV-Capacitor to get a storage system of 6MRF.

What do you think about the following Idea:

1. Keep those current capacitors as they are.
2. Use them to create multiblocks, to get one huge (In the amount of RF and Space they need) Capacitor.

What is about to following construction:

C = MV-Capacitor
L = Block of Lead
R = Block of Redstone

CCCCC
CLRLC
CCCCC

After rightclicking the center Capacitor Block (As always ;D) you will get one big capacitor with 4 input and 4 output panels that can store up to ... 25? MRF

Of course you can vartiate this. Like 2x2 3x3 2x3 4x3 4x4 etc.

You can always make people switch Lead with Electrum for even more Energy that can be stored. Or switch other Materials (*Hint, we need to make more use out of them PLEASE). Depending on how you build that, your "big capacitor" can store diffrent amounts of energy and has a variable amount of in- and outputs. Or you can use MV-LV-HV Capacitors which end up in diffrent amounts of Energy storage.

(Please remeber that all my Numbers etc. are just here to explain what I am about. I am not into balancing!).

This would be really awesome and give us so much more possibilities.
(And I wont miss EnderIO anymore for their capacitors).

Best wishes and greetings and again thank you for your awesome mod!

Respectfull

Malrama

**Comment by ArukaAlter** [comment]
Not a new idea at all, already refused before.

**Comment by Wubbbi** [comment]
Well, if so, even today, its pretty sad tbh. There is so much potential behind it and finally a way to make use of all the new materials added by IE. I am really tired of only usining Iron and Wood for all my constructions. I am begging you! Drain this Nickel, Lead and Silver out of my Soul! Make me use it like there is no morning. I am not even happy to find them (unlike iron ofcourse!). :(

Anyway, this is my idea, my suggestion and I will stay for it as long as I am playing IE (which is probably a long long time! :D)

**Comment by ArukaAlter** [comment]
There was a solid reason for it to be negated, you may want to search and read.

**Comment by Doragoon01** [comment]
I really don't understand the third complaint.  Capacitors already output to the sides.  I have giant arrays of capacitors that work fine.  I pull a comparator signal from the input block and from the output block, and run them into an RS NOR latch and my generator fills it when the output block gets low and stops when the input block gets full.  It works perfectly.
As far as higher storage capacity... Last time i checked, a barrel of diesel fuel fills two capacitors.  That's an insane amount of energy.  From wikipedia, diesel fuel has an energy density of 35.8, while batteries are all under 3.  The ratio should be more like 10:1.
If you need power, go diesel.  why would you need to store more than a 27 (3x3x3) capacitor's worth of power?

**Comment by BluSunrize** [comment]
See #1455 and #1011
Not happening ^^
