### ISSUE TITLE
Assembler Link Crash [MC 1.10.2] [v0.10-50]

### ISSUE THREAD

**Issue by Neros64** [BluSunrize/ImmersiveEngineering#1745]
When I click on Assembler in the Engineer's Manual my game will crash. I'm using ImmersiveEngineering-0.10-50.jar for Minecraft 1.10.2
Crash Report: [http://pastebin.com/gtrYJdbE](http://pastebin.com/gtrYJdbE)

**Comment by Zenith-One** [comment]
+1 - this just happened to me as well

**Comment by BluSunrize** [comment]
Duplicate of #1704, please use the search function. Also, fixed already for future releases.

**Comment by Neros64** [comment]
Nothing showed up when I searched it. I had no idea their was a fixed thread either. Thank you.
