### ISSUE TITLE
[1.10.2  0.10-50] Fermenter Question

### ISSUE THREAD

**Issue by VallenFrostweaver** [BluSunrize/ImmersiveEngineering#1747]
What is this slot used for on the Fermenter? See image below.

http://imgur.com/a/h75mC

**Comment by BluSunrize** [comment]
Item output, if a recipe specifies one.
Just because vanilla IE doesn't do so doesn't mean other mods/Crafttweaker can't do it

**Comment by VallenFrostweaver** [comment]
Ok. Not used to seeing compatibility options like this with other unspecified mods. Thanks.
