### ISSUE TITLE
[1.10.2] [v.0.10-50] Silo not considered a storage device by most mods

### ISSUE THREAD

**Issue by winsrp** [BluSunrize/ImmersiveEngineering#1748]
While attaching a silo bottom connection to other mods, i.e storage networks, Refined storage, steves factory manager, etc... it is not counted as a storage device and contents are not taken into account.

*sad face*

**Comment by BluSunrize** [comment]
Could you please adhere to the contribution guidelines and state which versions you are using?

**Comment by winsrp** [comment]
sorry about that., fixed

**Comment by winsrp** [comment]
checking a little bit, it seems to be related to some sort of enforcement of only being able to take 1 item out at a time from the silo, instead of as much as is being requested.

**Comment by winsrp** [comment]
also testes RFtools, and it can input items but it cannot output them, also it cannot effectively know how many items are in the inventory.
