### ISSUE TITLE
Client crashes on workbench is mined

### ISSUE THREAD

**Issue by Dijkstra1** [BluSunrize/ImmersiveEngineering#1751]
I mined the workbench and my client crashed here is the report.
https://gist.github.com/Dijkstra1/4a154cfeef3f71b85dadbec86a0174d9

**Comment by BluSunrize** [comment]
This was most likely related to my introduction of Shaders on blocks. I missed an obvious nullpointer.
Should be fixed in future releases.

I will close this when release 51 happens

**Comment by BluSunrize** [comment]
51 is released, try if the error persists =P
