### ISSUE TITLE
Engineer's Hammer rotates mod blocks that have facing block states and looses tile entity data

### ISSUE THREAD

**Issue by An-Sar** [BluSunrize/ImmersiveEngineering#1753]
This happened specifically with my mod PrimalCore. I have work tables and shelves that use facing states and also store inventory in NBT. I notice the vanilla furnace and the ic2 macerator both rotate safely. I would like to support the feature safely if possible, any insight if this is something I need to look at on my end or have you supported those tiles specifically?

**Comment by BluSunrize** [comment]
Look at
>public boolean rotateBlock(World world, BlockPos pos, EnumFacing axis)
In Block.java
That's all I call, so if you need special handling, I'd recommend you override that for your base block and check if the Tile needs to do anythign special on rotating.
I personally would handle it with an IRotateableTile interface on the TE and then in the block just do
>if(tile instanceof IRotateableTile)
>((IRotateableTile)tile).doRotateShenanigans()
or something like that.

**Comment by An-Sar** [comment]
Nice, I will look into this thank you.

**Comment by BluSunrize** [comment]
Report if it works, so I can close this =P

**Comment by An-Sar** [comment]
will do

**Comment by An-Sar** [comment]
Fixed. My shouldRefresh was not setup properly. Testing and rotating safely now. Thank you for the feedback
