### ISSUE TITLE
[IE 50] Pam's Harvestcraft and the Assembler

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#1754]
Any harvestcraft recipes that use water can't be crafted by the assembler using the liquid. It is possible to craft them with the assembler, but only using the items.
I don't know if Pam didn't register something in the recipes that is normally registered, or what else is going on.

One more thing is: Pam adds a couple of recipes that can cycle themselves. For instance, all oredicted fish can be crafted into a regular mc vanilla fish. That fish, however is also oredicted as a fish, so the assembler will reuse that fish to craft itself again, never outputting it from the assembler. Seems like a product of the assembler holding on to crafted items for further use with the other recipes in the assembler.

Edit:
IE 50
Pam's HarvestCraft 1.9.4-1.10.2h
forge x2166
mc 1.10.2

**Comment by BluSunrize** [comment]
found a fix for this, just forgot to tag the issue in the commit, so:

https://github.com/BluSunrize/ImmersiveEngineering/commit/fadebd69fbf71c84ddbd98116717f95b8ff39f20

^ that one does the trick, issue closed =3
