### ISSUE TITLE
You cannot attach this wire here

### ISSUE THREAD

**Issue by HeKontrolls** [BluSunrize/ImmersiveEngineering#1755]
Hello, I am currently playing Infinity Lite 1.10, When I try to connect any LV, MV, HV, to a wire connector LV, MV, HV I can link from one connector to the other but I am unable to link to a third and so on. I have tried several different ways but I am stuck and do not know if this is a bug or I am doing something wrong. I have used this mod heavily in the past with no issue like this before.

**Comment by ArukaAlter** [comment]
Read the manual, connectors can have only one connection, you have to use relays.
