### ISSUE TITLE
[0.10-48][1.10.2] Powered Lantern Lighting Issues

### ISSUE THREAD

**Issue by samuelroy21** [BluSunrize/ImmersiveEngineering#1756]
So once upon a time, I made some powered lanterns for inside my base. I left, came back, and they looked like this:
http://imgur.com/a/T1O5i

**Comment by BluSunrize** [comment]
I...don't really see the issue? .-.

**Comment by mindforger** [comment]
they are powered and have a lit but the environment seems not to be lit, sounds to me like somethign like optifine or fastcraft is beeing installed probably !?
