### ISSUE TITLE
[0.10-48][1.10.2] Conveyors && Item Routers not inserting into mek machines

### ISSUE THREAD

**Issue by samuelroy21** [BluSunrize/ImmersiveEngineering#1757]
In my factory, I wanted some conveyors to insert into some mek machines. They couldn't. Yes, I did set them up so that the appropriate side was set as an input. Item Routers also did not work.

**Comment by malte0811** [comment]
It seems like Mekanism is still using the 1.7 inventory system (ISidedInventory) which isn't supposed to be used any more in 1.8+. IE does not support the old system, only the new, capability based system.

**Comment by Joshwoo70** [comment]
cross posted to mek bug tracker.

**Comment by BluSunrize** [comment]
Good luck with that. xD
