### ISSUE TITLE
[related to #165] Crusher "ate" my draconium ore

### ISSUE THREAD

**Issue by TheQuadShot** [BluSunrize/ImmersiveEngineering#176]
I dropped some draconium ore into the crusher, it started very briefly then stopped. Like the vid on bug 165. I tried breaking the structure and the ore isn't anywhere to be found. What I expected was the ore to be crushed or "rejected" and "spit" out of it unprocessed.  I'm running ver. 3.3

**Comment by BluSunrize** [comment]
There is no "rejection" on the crusher. If you throw something in, it's either processed or never seen again. In the second regard, it kinda works like a quite beautiful trash bin.

**Comment by mindforger** [comment]
how about ejecting "scrap" to indicate "you wasted your stuff" ... as for server play, you might think it bugged on you and throw in your precious stuff again and fail twice without noticing what you've done wrong ... make it compatible/oredict to the scrap from IC2 so it could be reused somehow :P

**Comment by TheQuadShot** [comment]
Is this in the book somewhere and I just missed it!? AFAIK that makes this the only machine in the "game" that destroys an ore that it can't process, Seems like a pretty important fact to let users know, I'm a bit erked about it, because I can't trust it in an automated processing "plant".
