### ISSUE TITLE
[Crash] NPE when updated from 0.10-50 to 0.10-51

### ISSUE THREAD

**Issue by Endag** [BluSunrize/ImmersiveEngineering#1760]
**IE Version + Forge Version:**
IE: immersiveengineering-0.10-51
Forge: 1.10.2-12.18.2.2125

**Crashlog:**
http://paste.ee/p/eEFgN

**What happened:**
Tried to update IE to version 0.10-51 but when server tried to load world i got NPE.

**Reproducability:**
Easy:
1)  need only IE-0,10-51 and SimpleGenertors-1.10.2-0.10.5b in instance
2) create net world, place SG Furnace Generator in world and connect it to IE capacitor with IE power wires
3) save & exit
4) update IE to 0.10-51
5) try to load world -> get crash
optional:
6) revert IE to 0.10-50 and world load just fine

**Comment by BluSunrize** [comment]
Yeah that is absolutely my bad.
I actually annotated that method as nonnull and then I returned null there like an idiot.
Thanks for the report, I'll get this fixed as fast as possible

**Comment by hron84** [comment]
Thanks.
