### ISSUE TITLE
Thermoelectric detecting blocks not next to it.

### ISSUE THREAD

**Issue by Darcoon** [BluSunrize/ImmersiveEngineering#1762]
I don't know if this is on purpose or not but my thermoelectric generator detects blocks that 2 blocks up.

This makes for some strange interference, I had a setup with a blutonium block with 4 thermoelectric generators around it each touching a block of packed ice, this should generate 120 RF/tick according to FTB wiki. On its own it did just that but then I place the same setup above but then with IE's block of uranium and all of the sudden it did 84 RF/tick which is correct if it were uranium.

So I tested it a bit more, Stacked 3 setups and tested the one with the blutonium and came to this conclusion:

bottom: 84 RF/tick
mid: 102 RF/tick --- What? how did that come to be?
top: 120 RF/tick

so it does not happen downwards I think but its is very confusing.

Here are some technical details:
Sever/client on Forge 12.18.2.2171-universal
IE version is 0.10-51
Extreme reactors version is 1.10.2-0.4.5.19

I'd be happy to provide more info if needed hope you can fix this if it is a bug ( I think so because I couldn't find anything about this).

**Comment by BluSunrize** [comment]
Could you please provide some pictures of your setup?

**Comment by Darcoon** [comment]
Most definitely here's a link: http://imgur.com/P7QMWAA
Made it all blutonium now but for some reason the top one doesn't generate anything anymore no idea why.

**Comment by Darcoon** [comment]
Hmm it seems to have something to do with the two below, if they're both generating the top one doesn't if the mid one is generating the top one generates at half capacity an if the bottom one is generating it works at normal 120 RF/tick.
Here are some images: 
http://imgur.com/LThwSsp
http://imgur.com/oIGaYK1

**Comment by BluSunrize** [comment]
Those are some really small images ^^
Could please provide some bigger closeups? Maybe separate the layers so we can get a good look at it?

**Comment by Darcoon** [comment]
I can indeed here are some images (bigger this time :D):
http://imgur.com/M0HIRZ1
http://imgur.com/1SujsOc
