### ISSUE TITLE
Lightning Rod Manual Crash

### ISSUE THREAD

**Issue by SpikeyTheDJ** [BluSunrize/ImmersiveEngineering#1763]
Crash when opening lightning rod page in IE Manual. 
I removed all other mods from MC and with just IE 10-50  & forge 1.10.2-12.18.2.2120
problem persists
I ran into the problem on our lan server, it also happens in single player

[crash-2016-12-03_08.49.28-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/628912/crash-2016-12-03_08.49.28-client.txt)

**Comment by MalkContent** [comment]
try with latest IE/forge, report back :)

**Comment by BluSunrize** [comment]
User didn't report back yet, so, closed?
