### ISSUE TITLE
opened the assembler tab on ur manual 

### ISSUE THREAD

**Issue by Phizzhead** [BluSunrize/ImmersiveEngineering#1764]
https://gist.github.com/Phizzhead/e23031533893c434d51da68a2054005a

**Comment by Alaberti** [comment]
Before everyone on this forum blows you up for not using the guidelines:

- What version of IE on you using?
- What version of Forge?
- Do you have optifine?

**Comment by ArukaAlter** [comment]
If I recall correctly, this is already fixed for the next release.

**Comment by ArukaAlter** [comment]
See https://github.com/BluSunrize/ImmersiveEngineering/issues/1704

**Comment by BluSunrize** [comment]
The fix is released as well, go update.
