### ISSUE TITLE
[Suggestion]Conveyerbelt that changes direction with redstone-signal

### ISSUE THREAD

**Issue by Nezraddin** [BluSunrize/ImmersiveEngineering#1765]
Hello *waves*

After playing around with how to put more than one metal-press on the same input'convyerbelt - itemrouter sadly seems to fail there since you need to filter pretty much always the same item for all metal presses - I was wondering if there would be a possibility for a conveyerbelt that changes direction when it receives a redstone signal.

Pretty much like the vanilla tracks, so having only two possible directions (so you need to place the conveyer right) and at a redstone signal it changes 90°.

No idea if that is actually possible with how the conveyers work at the moment or coding wise (technical-noob here) but I thought I throw this suggestion in while I dare to actually send it :)

**Comment by ToadsworthLP** [comment]
That sounds pretty damn useful.

**Comment by BluSunrize** [comment]
I'll look into it.

**Comment by Bitterholz** [comment]
A conveyor Turntable? Would be pretty damn neat!

**Comment by MalkContent** [comment]
a turntable would be sweet, yea.
that being said, you can already line select:
http://www.sinister-lore.de/picdump/conveyorlineselect.png

**Comment by Nezraddin** [comment]
Ah... guess I'm thinking too simple *laughs*
Actually I really looked at the vanilla-tracks mechanic and thought "this would be nice for conveyers".
I know the track mechanic is bad in this case since it's acting on compass-direction (if I remember right) so a simple way I thought would be:

- a special conveyer belt (like the one which drops things or moves up a wall) which turns 90° clockwise on redstone signal (and 90° counterclockwise once the signal stops of course)
Of course this conveyer wouldn't be allowed to send the redstone signal away from itself or it would stop the conveyers which are connected to it.

That was my thought when writing this suggestion. Of course a turntable-multiblock or something like that would look nice, too (would be a very small multiblock then I guess).
A block under the conveyer sounds nice, too - after all most machines have their input at least one block aboth the ground - but at the same time both would bring difficulties in tight spaces cause you always would have to plan for two blocks (or more in multiblock) aboth each other, so latest if you let different conveyers move aboth each other you get problems.

Ehm... just my thoughts about it. Of course in the end it's all up to the devs if they want to add it and how they add it. Just thought I should explain my initial thought when writing this. :)

And thanks for the picture. Never even thought about trying such a setup. ^^" (but I still keep hoping for a turntable-conveyerbelt which looks a bit more in line with the mod, really love to make factory like structures with conveyers, heh :] )

**Comment by BluSunrize** [comment]
I was absolutely planning to do the simple one. There was no plans for a turntable yet, lol.

**Comment by Nezraddin** [comment]
Kinda happy to hear that. 
I think a simple one would fit best into the conveyerbelt-system in the end. So *cheers for it* :]

**Comment by MalkContent** [comment]
How about using the splitting conveyor. 3 modes, to be toggled with RMB-hammer. Mode 1: auto-alter (default), Mode 2: left on default, right on redstone high, Mode 3: right on default, left on redstone high.

This would mean you can't stop the conveyor with redstone anymore, though.

**Comment by BluSunrize** [comment]
This one is going to be a separate one. I didn't add a whole dynamic conveyor system for nothing.
Also, the one you are describing is essentially what the switch conveyor would be.
Mode 1 is the splitters current mode, mode 2 is the redstone conveyor with the left and right depending on how you placed it.
No real point to cram that into an existing one when I can just as easily make a new one to keep it clean and organized.

**Comment by MalkContent** [comment]
I don't think of it as "crammed", I think of it as tight and versatile ^^. And my counterpoint would be that there is no point in creating unnecessary bloat, also to keep it clean and organized.
Anyways, I don't want to intrude any further. You obviously already have a more concrete thing in mind, which I probably don't see fully. And the minor thing that I don't do any work towards it anyways :D

**Comment by BluSunrize** [comment]
Turntable does this now.
