### ISSUE TITLE
0.10-52 can crash botania mana brust

### ISSUE THREAD

**Issue by frank89722** [BluSunrize/ImmersiveEngineering#1766]
I just updated immersive enginneering to 0.10-52 (with Botaniar1.9-339)
When     
compat {
        B:Botania=true

It can crash the game when mana spreader start working.
I just change it to false, and it work fine now

Sorry for my bad English.

**Comment by BluSunrize** [comment]
Please provide a crashlog, as asked by the contribution guidlines

**Comment by frank89722** [comment]
Sorry, I forgot it O_O..
http://pastebin.com/dQP9nsrV

**Comment by BluSunrize** [comment]
I have...no idea why IE would cause this .-.
I don't actually do anything with Manabursts. Are you quite sure that this is the correct crashlog? Can you reproduce this reliably?

**Comment by frank89722** [comment]
I think I can't reproduce this reliably.

Some people hava same issue and they go to Botania Github report it but Vazkii always says He can't fix this. Another mod is breaking the data watcher.

And I just find I way to stop the crash and I report here.
I'm not very sure this is IE's issue Orz...
