### ISSUE TITLE
[MC 1.10.2] Crash when shooting railgun 

### ISSUE THREAD

**Issue by EtherG** [BluSunrize/ImmersiveEngineering#1768]
I got a crash when shooting the railgun with steel rods
Version: 0.10-48
http://paste.ee/p/3z9nw

**Comment by EtherG** [comment]
I think its the railgun shot entity that's causing it.
it crashes every time i join the game

**Comment by Bitterholz** [comment]
Might be wrong Import...
@BluSunrize are you sure you meant to use:
`com.google.common.base.Optional;`
instead of
`java.util.Optional;`
at
https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/entities/EntityRailgunShot.java#L7

**Comment by BluSunrize** [comment]
Yes, I'm quite sure, since EntityItemFrame uses the Google optional as well ^^

I do believe that there is something messing with DataManagers, but I can't prove, nor pinpoint it.
But the fact that Botania seems to suffer a similar issue (see #1766) leads me to believe that it's not necessarily our mods that are the root cause of this.

**Comment by malte0811** [comment]
@EtherG is there any difference in mod versions or configs between server and client at all? This might happen if some `DataSerializer`'s are registered only on the server or in a different order on the client vs. the server. I don't know whether any mods register serializers based on the config, but I know that there are mods registering serializers (Steve's carts and Charset register some for sure, I don't know who else)

**Comment by mconwa01** [comment]
I'm getting a very similar issue with both the railgun shot and the fluorescent tube.

I see that there's some inconsistency in the first parameter to `EntityDataManager.createKey()` among the entity classes (https://github.com/BluSunrize/ImmersiveEngineering/tree/master/src/main/java/blusunrize/immersiveengineering/common/entities):
* `EntityIEProjectile` uses `EntityIEProjectile.class` (sounds right)
* `EntityChemthrowerShot` uses `EntityChemthrowerShot.class` (sounds right)
* `EntityRailgunShot`, `EntityRevolvershot` and `EntityRevolvershotFlare` all use `EntityIEProjectile.class` (sounds wrong, even though they're all subclasses of IEProjectile)
* `EntityIEExplosive` uses `EntityIEProjectile.class` (sounds wrong)
* `EntityFluorescentTube` uses `EntityChemthrowerShot.class` (sounds wrong)

Could this be where the wires are getting crossed?

(Also see https://github.com/Vazkii/Botania/issues/2114#issuecomment-272708867. In this case, the "offending" classes are all part of the same mod, but perhaps they could still be loaded/initialized in a different order.)
