### ISSUE TITLE
Mekanism 295 | IE 52 | Forge 2171 - Unable to get CCW facing of down

### ISSUE THREAD

**Issue by Alaberti** [BluSunrize/ImmersiveEngineering#1769]
http://pastebin.com/Vf5FeJ6m

Mekanism 295 
IE 52 
Forge 2171 

¯\_(ツ)_/¯

https://github.com/aidancbrady/Mekanism/issues/4039

**Comment by Alaberti** [comment]
Please help?

**Comment by BluSunrize** [comment]
Mekanism issue. Aiden needs to fix that.
