### ISSUE TITLE
[Bug][Crash] Ticking Block Entity

### ISSUE THREAD

**Issue by MysticAura** [BluSunrize/ImmersiveEngineering#1770]
MC: 1.10.2
Forge: 2166
Mod: ImmersiveEngineering-0.10-52

Happened after teleporting into someones base, and now happens whenever I try and reload the world.

[Crash Log](http://pastebin.com/WjipMu7P)

**Comment by BluSunrize** [comment]
I'll look into that, think I know what the issue is Am 05.12.2016 4:00 vorm. schrieb MysticAura <notifications@github.com>:MC: 1.10.2
Forge: 2166
Mod: ImmersiveEngineering-0.10-52
Happened after teleporting into someones base, and now happens whenever I try and reload the world.
Crash Log
