### ISSUE TITLE
There was a critical exception handling a packet on channel immersiveengineering

### ISSUE THREAD

**Issue by Kehaan** [BluSunrize/ImmersiveEngineering#1771]
Hello

Sorry for first following up on my issue now. (Cant find my previous one, so making a new issue here)
This issue is on a dedicated server. The console is writing the following:
http://pastebin.com/SXweL5Yw
I am using 1.10.2-12.18.2.2171 Forge.
Not using Optifine or Fastcraft, but using Foamfix.

The following modlist: https://gyazo.com/0e8e84c1e8862bda9f026a10a4538dc8

Let me know if you need any more info. It seems like everything works, and it seems to be happening randomly, so i cant recreate it. Just the console log that informs of the above.

**Comment by BluSunrize** [comment]
Please specify if you are using Cauldron, Sponge, Thermos or some other thing.

**Comment by Kehaan** [comment]
I just use forge :) Nothing else on the server besides above modlist.

**Comment by Joshwoo70** [comment]
foamfix should work with IE. i tested it so far and it works.

**Comment by AEnterprise** [comment]
can you verify that all the mods are the same versions on the client and the server? looks like the server sends a packet the client doesn't know about and fails to handle

**Comment by Kehaan** [comment]
I can confirm that both server and client use same mods (Its just a zip of the mods from the client, moved to server and unzipped)

Mods client:
![13b38579062f9d48da848719859040e9](https://cloud.githubusercontent.com/assets/6755642/20919577/d3ad18e4-bb9c-11e6-87cc-860c38153554.png)

Mods server:
![113132c0bc3e9f86a3f20486e64ca8f9](https://cloud.githubusercontent.com/assets/6755642/20919451/2d9d467c-bb9c-11e6-8f23-130ba402acf1.png)
![41cae982a765ebeae2a6e00fb0927daf](https://cloud.githubusercontent.com/assets/6755642/20919464/33e748e8-bb9c-11e6-95f5-c068ab0ff7da.png)
![eac819d9b27fe0e2668acb7cb90a3966](https://cloud.githubusercontent.com/assets/6755642/20919473/3bb88ef6-bb9c-11e6-8574-ca786b4d770d.png)
