### ISSUE TITLE
Problem connecting wires to connectors

### ISSUE THREAD

**Issue by Antonyvw** [BluSunrize/ImmersiveEngineering#1772]
Im having an issue connecting copper wires to connectors. I can connect the first wire but when I then try to add second wire from connector on to its next point along the line (either connector or machine) - I get the following message:-

"You cannot attach this wire here"

Obviously if I cant string the wire from one post to another or to a machine, I'm stumped. Probably me doing something wrong but any ideas on how to solve it please?

Antony

**Comment by BluSunrize** [comment]
Use relays. Connectors are in and outputs, they only take one wire. Relays are used in between.
