### ISSUE TITLE
cannot get a reading from core sample drill

### ISSUE THREAD

**Issue by Antonyvw** [BluSunrize/ImmersiveEngineering#1773]
I have connected up a core sample drill. It drills down and the drill returns up. But when I right click it to find out what the sample contains I get no response. What am I doing wrong?
Thanks
Antony

**Comment by BluSunrize** [comment]
It should give you an item. That item tells you the sample, its location and when the sample was taken.
Pretty sure the manual details this.

**Comment by Antonyvw** [comment]
Ive double checked and repeated it in both creative and survival - but I get no item back from it once it has completed its job.
Thanks
Antony

**Comment by BluSunrize** [comment]
Could you please provide your versions used? I am unable to reproduce this, since this setup:
![Example Image](http://puu.sh/sFYDz/4fbb3cebde.png)

Immediately netted a result.

**Comment by Antonyvw** [comment]
I'm not sure where the image has come from as I did not post an image and it looks more like a video Ive been watching as mine is not on a flat world.
Anyway as to the version it is 0.10.52. I'm also using minecraft version 1.10.2. I do have other mods on but I have removed the 2 I have found it conflicts with (which are building bricks and Quark)

**Comment by BluSunrize** [comment]
Well duh, the picture is from my own dev environment.
I set up a sample drill, with a creative capacitor, rightclicked it once to start the drilling, then clicked it again after the drilling finished to get the coresample that you see me holding in that picture.
Point of the matter is, I cannot replicate your issue.
Could you please tell me how your are powering the sampledrill?

**Comment by Antonyvw** [comment]
Its being powered by either windmill or watermill. Ive tried both and had no success. As I said it does complete its cycle so power is clearly getting through. But it is just not giving me a the sample at the end. Ive just tried it set up as you have it but still same results - no sample at end

**Comment by Joshwoo70** [comment]
> Its being powered by either windmill or watermill. Ive tried both and had no success. As I said it does complete its cycle so power is clearly getting through. But it is just not giving me a the sample at the end. Ive just tried it set up as you have it but still same results - no sample at end
we want pictures thats what blu wants.

**Comment by Antonyvw** [comment]
Ok here is how I have connected it to a windmill.

![2016-12-06_12 38 28](https://cloud.githubusercontent.com/assets/24394848/20925852/33da5d26-bbb1-11e6-9b6a-8f96b8b53f11.png)

**Comment by BluSunrize** [comment]
So if you rightclick it with an empty hand, what happens?

**Comment by Antonyvw** [comment]
Nothing happens. Ive tried looking in my inventory and also putting a chest next to it but regardless of what I try nothing is given. I have seen on two occasions it says on screen 'core sample'. But even then it has given no actual item

**Comment by BluSunrize** [comment]
uhm...can you try that again without a texture pack? >_>
Also, I'd like to have a full mod list.

**Comment by Antonyvw** [comment]
Removing the texture pack had no effect. As to the list of mods installed they are as follows:-

ArichitectureCraft
AutoregLib
Base Metals
BdLib
Covers
Drycoanos ore spawner
electricAdvantage
Hopper Ducts
Immersive Engineering
JEI
LunatariusCore
Lux
MCMultipart
Missing Pieces
Optifine
Power Advantage
Quark
Railcraft
Schematica
Steam Advantage
Villagebox

**Comment by Antonyvw** [comment]
A new developement.
Having removed the texture pack - as I said I got no difference. But when I removed it and optifine I now get the sample.
So I think I have solved it for myself it seems to be a combination of the textures and optifine. It gives me a resolution but at a loss of the textures I prefer.

**Comment by bookerthegeek** [comment]
So either optifine is messing with the texture,  or the texture pack is missing a texture for the sample.

**Comment by BluSunrize** [comment]
Optifine was gonna be my suggestion, hence why I asked for modlist.
So, for future reference: The contribution guidelines very clearly say that you MUST be able to reproduce the issue without optifine. Please remember that for next time, so we can save ourselves the timewasting.

My guess is that Optifine fucks up my custom model. To noones surprise rally, given that mods trackrecord. Try adding the texturepack again to see if the coresample is still visible.
Plus, this only changed the model. Meaning that the machine absolutely works, you just got an invisible item out of it. It's in your inventory, and you should see a tooltip when hovering over, you just can't see the model because of Optifine.

**Comment by Carnaxus** [comment]
The issue is shaders.  If you're using a shader, turn it off.  The core samples are probably all in your inventory but invisible at this point.
