### ISSUE TITLE
[0.10-52] Silo/Strip Curtain lag & Strip curtain conveyor hover

### ISSUE THREAD

**Issue by VallenFrostweaver** [BluSunrize/ImmersiveEngineering#1774]
When attaching a strip curtain to a redstone lamp and having a series of items fed past it (example: cobblestone being fed from a silo and back into the same silo via conveyors in a loop or even into another silo) each time the lamp lights from the items passing through there is a massive lag spike.

Creating a circle of conveyors does not reproduce this lag spike. I can only reproduce with a silo.

Strip Curtains also appear several blocks above a conveyor belt when dropped onto one.

**Comment by mindforger** [comment]
single or multiplayer? how long is the spike?
light updates can generate a noticable lag!

**Comment by MalkContent** [comment]
yea, quick lightupdates are bad mkay.
iirc. removing light has especially bad performance.

**Comment by VallenFrostweaver** [comment]
Light updates or not, this only reproduces with a silo involved in my experience so far.

Single player. About .5 seconds but since it happens every 1-2 seconds that's very noticeable. A constant stutter every 1-2 seconds is the effect and it's kinda painful.

As for a picture, I attached one below. It will cause lag spikes anywhere on the conveyors with the lamp/strip set up on it and the cobble going through. Single track, dual, split - it all reproduces regardless.

[http://imgur.com/a/fa7BR](url)
![image](https://cloud.githubusercontent.com/assets/13642054/20928857/909d5230-bbbf-11e6-841a-962edc8e014f.png)

**Comment by MalkContent** [comment]
chances are updating the silos rendering depending on the light is even more ressource intensive
try the same setup without feeding stuff out of/into the silos and use hoppers to supply/catch instead
near the silos ofc

**Comment by mindforger** [comment]
but this would be something that Blu probably can optimize, thus i asked for the screen for better reproduction :)

**Comment by BluSunrize** [comment]
I beleive changes made since have improved this.
