### ISSUE TITLE
IE1.10 TC1.10 item dupe bug

### ISSUE THREAD

**Issue by mariodelpozo** [BluSunrize/ImmersiveEngineering#1776]
dont know if its a issue from IE or TC but i crafted treated wood in a TC crafting station that was placed next tom a coke oven. and when i shit clicked the crafted items in to my inventory i got a full stack of bottles and all of the planks got crafted into treated wood. i only had 3 bottles of creosote oil in the crafting table and 2 stacks of planks. playing on the direwolf20 1.10 pack (v1.1.3)

**Comment by BluSunrize** [comment]
Update IE, this is an old issue.
