### ISSUE TITLE
[MC 1.7.10][IE 0.7.7] Switching fluids on Bottling Machine

### ISSUE THREAD

**Issue by BayneMc** [BluSunrize/ImmersiveEngineering#1777]
If I use a bottling machine for a fluid, bottle all of it, then change to a different fluid, it no longer works. I've been breaking a block on it then re-assembling it but I wonder if there is another way to reset it?

**Comment by BluSunrize** [comment]
there's probably a little bit of residue fluid left. Vanilla bottles only take 333mB of water, so with a bucket of water, that leaves you with a leftover mB.
