### ISSUE TITLE
[1.10.2] crash whis GregTech 5 Unofficial

### ISSUE THREAD

**Issue by Ktor-usm** [BluSunrize/ImmersiveEngineering#1778]
Immersive Engineering crash whis GregTech 5 Unofficial on minecraft 1.10.2. I contact developer of GT5u and he say what problem is not on GT5u side.
forge 12.18.3.2185
Immersive Engineering 0.10 - 52
GregTech 5 Unofficial 5.10.06 
[http://paste.ee/p/B94IM](http://paste.ee/p/B94IM)

**Comment by BluSunrize** [comment]
GT5U is somehow messing with the creosote. No idea how exactly, since the mod isn't visible source to my knowledge, but as far as I am aware, there is nothing I can do.

**Comment by Ktor-usm** [comment]
Should I ask developer GT5U the source for you? or you will not deal with this problem?

**Comment by BluSunrize** [comment]
well as far as I am aware, I can't DO anything to fix it. Somehow, the registry name for Creosote ends up being null. Which means that either, my fluid variable turned to null , or the fluid was removed from the registry. Neither of that should be possible on my end.
I'll see if I can chuck GT into my dev instance and set a few breakpoints. Would you please provide me with a link to the version you used? Afaik it's not on Curse.

**Comment by Ktor-usm** [comment]
Oh, now I see, can not be accessed through the site. I found it through the curse of the launcher. just in case, here's a link to it on my Google drive: [https://drive.google.com/file/d/0B0et32q6pboTYnpubjI3REZURzg/view](https://drive.google.com/file/d/0B0et32q6pboTYnpubjI3REZURzg/view)

**Comment by Ktor-usm** [comment]
I find this version on githab [https://github.com/Blood-Asp/GT5-Unofficial/tree/1.10.2](https://github.com/Blood-Asp/GT5-Unofficial/tree/1.10.2)
thank you for trying to fix it

**Comment by BluSunrize** [comment]
So, I've had a dig through their codebase, seems to be a weird edgecase between GT and me, which also explains why it doesn't happen with Railcraft.

I'll look into fixing this on my end.
