### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by UnwrittenFun** [BluSunrize/ImmersiveEngineering#178]
- ie.manual.entry.revolver4 - cabapilities
- ie.manual.entry.steelconstruction1 - decorational (most would say decorative)

These I'm not sure on, possibly intentional but transferrate is not typically one word
- ie.manual.entry.wiring1 - transferrate
- ie.manual.entry.introduction1 - transferrates
- ie.manual.entry.highvoltage0 - transferrate

**Comment by BluSunrize** [comment]
thanks =P
