### ISSUE TITLE
Cannot exit Engineer's Manual

### ISSUE THREAD

**Issue by Xiaminou** [BluSunrize/ImmersiveEngineering#1781]
After browsing through the manual I couldn't exit it. Had to kick myself out of the server.
This only happened once, and I don't know why.

Minecraft: 1.10.2
Forge: 2183
Mods: [list.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/637256/list.txt)

**Comment by BluSunrize** [comment]
What did you try to exit it? Because I can't reproduce that one.

**Comment by Xiaminou** [comment]
I tried escape, I tried e, I tried backpack. Then started pressing random buttons.

Like I said it's only ever happened once and it's been fine ever since. Who knows what it could have been.

**Comment by BluSunrize** [comment]
Well then. I'm closing this, because unreproducable edgecase.

**Comment by Xiaminou** [comment]
fair enough.
