### ISSUE TITLE
(0.10.52) Metal press' c̶o̶n̶v̶e̶y̶o̶r̶s̶ ̶d̶o̶n̶'̶t̶ ̶w̶o̶r̶k̶/Cannot put molds on

### ISSUE THREAD

**Issue by jzburda** [BluSunrize/ImmersiveEngineering#1786]
I tried both N/S and E/W positions, and the Metal press won't accept any molds (Tried plate mold) and the conveyors on the metal press won't push items

**Comment by jzburda** [comment]
P.S. I apologize for the Core Sample issue I made awhile back. I feel now it was very ignorant of me to question the purpose of the Core Sample's code hooks.

**Comment by BluSunrize** [comment]
Could you please provide pictures and detail the issue a bit more?

**Comment by jzburda** [comment]
I tried to get the mold in as the book says, which is to right click on the multiblock. I guess I'll make a small video on it, because that's the only way I can represent it

**Comment by BluSunrize** [comment]
Yeah, I could reproduce it in my dev environment. Legit issue, will fix.
