### ISSUE TITLE
Block Interfere doesn't Occur After Placing New Blocks

### ISSUE THREAD

**Issue by porteriscool** [BluSunrize/ImmersiveEngineering#179]
As you can see, there is a block in front of the wires, and these blocks were placed after I placed the wires. As you know Blu, when there is a block that interferes with the connecting of wires, the wires don't place. However, in this situation, after I place the wires, I can place blocks in front of the connections and the wires don't break. I am currently running on version 0.3.3. If you need anymore info on this, please ask.
![2015-07-04_11 16 08](https://cloud.githubusercontent.com/assets/12450943/8508429/19fb9ef0-223e-11e5-8816-ba592b7ae8da.png)
![2015-07-04_11 16 13](https://cloud.githubusercontent.com/assets/12450943/8508430/1aa226b2-223e-11e5-886f-897475fac7c0.png)

**Comment by BluSunrize** [comment]
that is not a bug.
