### ISSUE TITLE
IE, TiC and Lightning Craft compatibility issues.

### ISSUE THREAD

**Issue by Urijahuri** [BluSunrize/ImmersiveEngineering#1790]
So through trial and error I've discovered that the cause of an issue is Immersive engineering being installed along with the other two.

The issue is that IE makes it so that LC cannot use its TiC recipes. I've already told the owner of that mod, and am simply informing you in case this is something that needs to be fixed upon your end.

**Comment by BluSunrize** [comment]
Could then maybe reference what they said? Their issues? Pictures? Versionnumbers?
Anything requested kindly in the contribution guidelines? ^^

**Comment by Urijahuri** [comment]
Version 2.7.0 in LC, version 2.6.1 in TiC and 0.10-52 in IE.
LC dev said they would look into it as they don't know whats causing it either.
The bug removes the TiC smelter recipes for LC resources (blocks, dusts, rods, ingots, etc)
the issue was discovered in a large modpack but was rounded down to still happen with only TiC (and dependants) IE, LC, and JEI installed.

How it should look:
https://i.imgur.com/jXDvSJt.png

How it looks with IE added:
https://i.imgur.com/uJ971aJ.gif

**Comment by BluSunrize** [comment]
What's the white items?
Also I don't quite know how this relates to me? I've never even heard of that metal or mod before tbh. I don't know how IE would be interfering with it. .~.

**Comment by Urijahuri** [comment]
The white items don't technically exist (you can't make those in TiC yet)

I'm not sure how IE is interfering with it. I am assuming that its a conflict with the compatibility add-ons between LC and IE.

**Comment by sblectric** [comment]
This was an error on my end, and I have fixed it in my latest release.

**Comment by BluSunrize** [comment]
Cool! Issue closed then ^^
