### ISSUE TITLE
Convert RF to EU

### ISSUE THREAD

**Issue by ExDomino** [BluSunrize/ImmersiveEngineering#1792]
Hello.

The doc says "Before version 0.8, IndustrialCraft 2's Energy Units (EU) can be converted to RF through the LV Wire Connector, and RF can also be converted to EU. Attaching the LV Wire Connector to an appropriate side of an EU-accepting or outputting block will allow the block to convert it automatically: 4 RF will convert to 1 EU, and 0.25 EU will convert to 1 RF."

My question is: after 0.8 how to convert RF to EU ?

**Comment by theunkn0wn1** [comment]
You don't. IE no longer acts as a power conversion mod.
You may find [this](https://github.com/BluSunrize/ImmersiveEngineering/issues/1087) thread to contain  relevant reasoning as to why this is the case

**Comment by laz2727** [comment]
With a Forestry tin engine.

2016-12-11 11:54 GMT+05:00 theunkn0wn1 <notifications@github.com>:

**Comment by BluSunrize** [comment]
RF to EU conversion was removed due to balance issues. It won't return.
