### ISSUE TITLE
[Suggestion] a way to automate farming

### ISSUE THREAD

**Issue by alpha8196** [BluSunrize/ImmersiveEngineering#1793]
I know there's like a hand full of mod that can do this,but I would really like to see a IE's style farming system,not like ender IO's farming station instead,I hope to see something kind of like how hydraulicraft did it,a farming method that does not use a "magical block" or literally a magic ritual,but with a more industrial or, as the introduction of this mod says, a retro-futurism feeling

**Comment by mindforger** [comment]
the idea has been discussed several times without outtcome yet

do you have some sort of immerse idea that would not look obscure? the problem is even today, we still have tractors and harvesting machines driving across large fields either by hand or like robots, but nothing "automatic" like you would expect (MFR harvester as example)

it would miss the immersion, but i also stay with you, there has to be a way XD

**Comment by alpha8196** [comment]
I'm thinking of a machine made out of three sections,and plants grows in  basket-ish things like those vegetable factories uses which can be transported to different section via conveyor belts or mechanic arms or whatever, 
the first section would be used load/unload dirt or other block the crop grows in to the baskets manually(at least for the first time),it'll also have some sort of seed planter to plant seeds that comes from a hopper like structure above it(will probably be an input and a internal inventory for seeds),if the dirt/substance needs to be tilted,an extra machine will need to be installed(like how preheaters attached to a blast furnace)

the second section will be where the plants grow,I'm imagining some sort of chamber or shelves or hangers where these baskets stay,perhaps a sprinkler,or fertilizer or a light source could be installed to speed up the growth process

the third section is where the crops been harvested,when the crops are fully grown,their basket will unload what they contain in to a sieve,the sieve will separate the dirt and the crops,the dirt will be collected by the original basket and send to the first section to be replanted,and the crops will be moved to a export pipe which it either pop out of the machine or get into an adjacent inventory(or with a internal inventory as a buffer)

p.s. this will probably not work for tree farming ,not sure about cactus and sugar cane

Disclaimer : this is just an idea without very clear thinking or any background knowledge of mod making,so please show some mercy if something is wrong ....... Plz?

**Comment by mindforger** [comment]
while i like the idea of growing stuff in pots making them moveable, this would not work in any static automated way, plants grow at different speeds so you'd need some sort of intelligent mechanic to pick up the matured plants in their pots to harvest and retreat them to grow again

But still, i like your gerneal idea, 
some sort of multiblock planthouse would allow for using the dirt blocks as they are beneath them and the space for the plants for regular growth and rendering
above the plant there are either haning a set of tools per plant or a moving multitool scanning the plants and fields, harvesting the plants or tilling the dirt, watering in the meantime ... also artificial (and switchable) light sources to allow nocturnal plants to grow and non nocturnal plants inside a cave without ugly torch placement

**Comment by p75369** [comment]
As mindforger said, this has come up before #602 

I may be biased, but I do still like the idea of a combine harvester on rails. The inteligent aspect of this suggestion just seems a tad too... scifi for me.

**Comment by bookerthegeek** [comment]
@mindforger I would say you can as long as the block in question passes along that you can plant on it. I would look at the planters from garden stuff as an example off the top of my head.

**Comment by mindforger** [comment]
@p75369 thank you ... i think github needs a noteblock feature for fast access to issues XD

**Comment by popps73x** [comment]
Immersive engineering farmer?  multiblock structure.  scaffolding at the four "corners" of the farm 4 blocks tall.  Rails of? scaffolding or light machine blocks connecting the sides.  a cross beam of machine blocks with a piston below and a wooden tank above.  The farm would need water and power and optionally fertilizer (bonemeal).  farm would operate visually like a Build Craft quarry as it waters the crops when it passes over them and harvest/replants ready crops.  the entire structure must be covered in glass?  :)  maybe?  lol

**Comment by Bitterholz** [comment]
What id really like is a multiblock Structure that encases a Rectangular Field (longer than whide) and runs a harvesting bar across it every so often...

**Comment by mindforger** [comment]
>ImmersiveEngineering is not Steampunk .... (by BluSunrize)

we already had something like this in https://github.com/BluSunrize/ImmersiveEngineering/issues/602

:) we should focus on new ideas or wait for Blu to com up with something in the future

**Comment by Joshwoo70** [comment]
what mindforger said. also please look at the readme.md file... it is CLEARLY stated it is retrofuture x(

**Comment by omega025** [comment]
alpha8196, your description reminded me of old photos of les cultures maraîchères (a French form of intensive urban farming) and the glass cloches they'd sometimes use, such as:  https://s-media-cache-ak0.pinimg.com/736x/a8/d4/97/a8d4976725928c56c8bfb2c620a912b9.jpg or https://s-media-cache-ak0.pinimg.com/736x/4e/a7/96/4ea796335b86d43c89398425bea594bd.jpg .  It'd be a bit tricky to get it to look right in Minecraft's cube style, but I think it'd look pretty neat and fit the retrofuturist style of IE.

I do, however, like the horizontal combine setup proposed by Bitterholz and the commenters in #602 .

**Comment by PONYRYDE** [comment]
I was just passing by.

How about a (3x3x4) multiblock vacuum tube like cloche similar to the existing charger, with a single plant inside on the central bottom dirt block and a light at the top. High yield from the one plant could be offset by power consumption, bonemeal, water. A few of these hooked up to a pump and with wires would make a cool frankensteinian lab.

**Comment by mindforger** [comment]
single block glashouses ... brilliant idea!

but in the view of IEs own fluid pipes it would look a bit ridiculous, having a plant in a glass container facing a fluid pipe with almost the size of the container XD

lets make it a 2 block height multiblock, an let the base connect to a fluid pipe and the top has a power port

@BluSunrize  do we have yet any conveyor belt that will route items to an alternative route if the target inventory is full?

i have an image in my brain with several of those 2x1x1 glasshouses in a row, a pipe running behind them and a chain of those "alternate route inserting conveyors" above the pipe feeding bonemeal into the glasshouses accepting only one bonemeal which can not be removed and will be consumed after 10 to 20 seconds or so

and when the machine is full, the conveyor moves the item along to the next conveyor

and the power can be inserted from the top

**Comment by XFactHD** [comment]
The "alternate route inserting conveyor" is called dropping conveyor :).

**Comment by alpha8196** [comment]
@PONYRIDE another reason that one block space might not be enough would be crops like industrial hemps,also @mindforger if farming cactus and sugar cane, more space may be needed, unless they are shrunk like how agricraft did it

**Comment by mindforger** [comment]
well 3x1x1 then
this would also enable to attach a powerport on the back of the middle block instead the top
and the top block has a dispenser at the top and the top also is the insert port for the bonemeal then

**Comment by BluSunrize** [comment]
Yes Mind, the dropping conveyor is that routing alternator.
A structure for each plant is a bit of a nuissance, tbh, not to mention the abhorent amount of TileEntities.

A central structure seem more appealing, I just haven't come up with a design I fancy yet ^^

**Comment by PONYRYDE** [comment]
Yeah I was figuring a two blocks of growing room in a 3x3x4, that allows for a one block trunked tree even and maybe flowers as a crop. I don't know anything about modding but maybe it is possible to not do any special rendering or even to have the crop growing at all (full grown crops look better) rather just output appropriate drops. From experience large crops in constant growth and/or faster tick rates invariably impact on performance and the only time you need to automate farming is when you want a lot of production.

**Comment by mindforger** [comment]
if we are talking about retrofuture, i always got a hang of thinking about bioshock 

and tubed plants is totally a thing that would fit this picture

you could also say building the crusher is a nuissance just for crushing ore but it has style!

i understand the thing with the TEs but as i already asked for the core sample drill, can't you make it a real multiblock with your chunkrenderthingy?

something like a tube with scaffold at the bottom, a new block (soild/sand-growthchamber, built from soil/sand in the middle + sheetmetal bottom slot + shears top slot + 2 glasspanes left and right slot + 2 contantan wires in the upper corners and LV wires in the lower corners) in the middle position and a hopper on top

**Comment by PONYRYDE** [comment]
I see you've got the picture. Is it even possible to have a transparent mutiblock to avoid having to re-render the crop?
I was thinking two, four or eight of these, with appropriate input requirements, would be enough to supply a refinery.

**Comment by Bitterholz** [comment]
It sure is posible to render Parts of a Model Solid and other Parts Translucent. as long as the Model does not have a rather dynamic state, like a Pipe e.g.

**Comment by mindforger** [comment]
i mean, i could easily place a large prop from decocraft in 1.7.10 with a small bounding box without disturbing the rendering of the block colliding with the prop .... but i think that is TE rendering and have no clue how the rendering stuff behaves when you do it only with chunkupdates instead of Tile Rendering

**Comment by BluSunrize** [comment]
The bottling machine is an example of a multipass multiblock, so yes, it's possible.

**Comment by omega025** [comment]
Just for fun and to help visualize the ideas in this thread, I've thrown together a rough Chisels & Bits mockup of what the 1-block cloche/vacuum tube greenhouses @mindforger's excited about could look like:  http://imgur.com/wJ58Vkg.  I exercised some creative license to keep them simple:  Hypothetically, fluid pipes encased in scaffolding connect to the bottoms of the 'greenhouses', RF is taken in at the top to power grow lights inside, and bonemeal is pulled out of the chests by hoppers on conveyor belts and taken up by each 'greenhouse' as they pass by.  If one already has a bonemeal in its inventory, the bonemeal doesn't get inputted and passes onto the next one.  Drops are outputted by the same block face and placed onto the conveyor belt, which leads to a routing block that sorts plant drops and excess bonemeal that didn't get picked up.  A more detailed model could have moving mechanical parts on the inside of the cloches to provide automation visuals and make it look less like "magic block" behavior.

I don't know if it's even possible for blocks to receive inputs from conveyor belts that aren't pointed towards them, or if inputs and outputs can be handled with the same block face, but like I said, this was mostly just to playing around with the visual style.

**Comment by BluSunrize** [comment]
Wow that is actually very very nice looking!
I'll look into a design using glass tubes for sure ^_^

(Just currently tied up with other IE work and exams)

**Comment by mindforger** [comment]
YES that is totaly what i had in mind, but i would alter it a tiny bit, to have the power on a side and the top beeing the fertilizer slot to use the dropper conveyor :D

**Comment by PONYRYDE** [comment]
@omega025 that's more epic than I would of imagined. So far I've mostly avoided C&B from fear of it consuming me, what you have done there justifies that fear.

**Comment by omega025** [comment]
@PONYRYDE Your fear is justified. Pls send help.

**Comment by BluSunrize** [comment]
It's a thing now \o/

**Comment by alpha8196** [comment]
woohoo!
