### ISSUE TITLE
Disconnected from Server

### ISSUE THREAD

**Issue by Elvarion** [BluSunrize/ImmersiveEngineering#1794]
- ImmersiveEngineering-0.10-52

Not sure if this something from Immersive Engineering, but I could only see Immersive Engineering being referenced in the log so Ill post hit here. If its not Immersive Engineering feel free to close it!

Was running around and got kicked from the server.
This error was printed in the console
http://pastebin.com/FghUJ62T
Could login just fine again, and its been working fine for the 30min or so Ive been logged in.

I see its refering to something about the skyhook.
Was not using the skyhook at that time and had not been doing so in the past 1½ hour maybe~

Not sure if this is of any help or not ^^

**Comment by threehams** [comment]
I'm getting an error with the same stacktrace, but it happens on every connection attempt.

I was using the skyhook (HV power line on level ground), and was kicked from the server with the reason "flying is not enabled on this server". I enabled flying on the server to get around that (apparently, it just happens sometimes). On reconnect, I see the above error, and am immediately kicked again.

If screenshots of the area help, I can get them, if I can manage to log in again.
