### ISSUE TITLE
Duplicate piston block

### ISSUE THREAD

**Issue by TheGuy20** [BluSunrize/ImmersiveEngineering#1795]
**What is the bug?** 
Duplicate piston block
**What did you do to make it happen?**
Place a conveyor belt down on a block, then place a piston block on the conveyor and then break the piston.
It returns 2 pistons. 
Place 8 conveyors on ground(doesn't matter if connected or not) and then 8 pistons. Break the first piston and get back 9 pistons. The remaining 7 pistons each drop 1 piston when broken. 

Noticed this on a server. Tested it more in single player

What other mods were installed when the bug happened? 
Direwolf 20 modpack 1.10 version
Happens in version 10.51 as well as 10.52 of Immersive Engineering

**Comment by BluSunrize** [comment]
can you reproduce it without the conveyor?

**Comment by TheGuy20** [comment]
Yes. Must be something other than IE causing it.
