### ISSUE TITLE
[1.10.2] Excavator lag spikes.

### ISSUE THREAD

**Issue by reppinfreedom** [BluSunrize/ImmersiveEngineering#1796]
Some sort of memory leak or something going on with the Excavator. One running bogs the game down and starts freezing it up each garbage collection cycle after a few minutes running, four side by side bog the game down into massive lag spikes every garbage collection cycle instantly.

The only way I can run them without bogging my game down is to make a enclosed room ten blocks away, face away from them, and turn them on with a switch...

Nothing else has the issue. Can create tons of water wheels and windmills without problem. But, turn on an excavator... Lag lag lag! I turned off excavator particles in mod setting, even though I never saw any...

I even turned off virtual memory in Vista SP2 to make sure the lags were not caused by memory swapping to disk, nope... Still spikes...

**Comment by malte0811** [comment]
I have a mostly working fix for this, just need to fix some caching issues. I'll push it either later today or tomorrow.
