### ISSUE TITLE
[Suggestion]  S:preferredOres in Village Gen

### ISSUE THREAD

**Issue by katur239** [BluSunrize/ImmersiveEngineering#1797]
Can we get the items spawned in the storage crates in the village building to respect the S:preferredOres config instead of placing IE versions of ingots and things?

**Comment by BluSunrize** [comment]
Loot is handled by ResourcePacks these days. I can't easily influence it from the code side, but you can easily use a RP yourself to modify it.

**Comment by katur239** [comment]
could you tell me how to do it for a SP world by chance? Doing it as a normal resource pack doesn't seem to work since it's client side.

Thanks

**Comment by BluSunrize** [comment]
I believe this is what you are looking for:
http://minecraft.gamepedia.com/Loot_table#Custom_Maps
