### ISSUE TITLE
How to use Multiblock whitelist/blacklist nbt tags in engineer's hammer?

### ISSUE THREAD

**Issue by majix560** [BluSunrize/ImmersiveEngineering#1799]
How do I need to setup the Engineer Hammer's NBT tags to enable the whitelist and/or blacklist of multiblock formations?

**Comment by majix560** [comment]
How the heck am I supposed to write [these](https://github.com/BluSunrize/ImmersiveEngineering/issues/1502#issuecomment-250000755) as an NBT tag onto the engineer's hammer?
When I try using the [NBTEditor mod](https://minecraft.curseforge.com/projects/nbtedit) to write them they don't stick.
By "don't stick" I mean the hammer's nbt tags remain completely unchanged when I click "push to world" with the taglist's mentioned in the above linked comment having been made.
But if I don't add any tags and just change the tags built in, the changes save.

**Comment by bookerthegeek** [comment]
I imagine with minetweaker.

**Comment by BluSunrize** [comment]
Yep, the idea is that you either have a recipe that gives you that item, or you write the tags manually using a helpermod and then have HQM or a similar mod return it as a quest reward.
