### ISSUE TITLE
BuildCraft Quarry Doesn't Recognize IE Ores

### ISSUE THREAD

**Issue by DoughnutDev** [BluSunrize/ImmersiveEngineering#18]
Like the title says they won't pick up IE ores. I am going to test this with Ender Quarry too. Here is the screenshot http://puu.sh/hNnpm/28ea864fb2.jpg

**Comment by DoughnutDev** [comment]
So when you look at BC recipes with copper or any other ore from IE or even IC2 it says Un-named -1 for that item when it is cycling through the different types of copper it can use in that recipe.

**Comment by BluSunrize** [comment]
That sounds more like a Buildcraft Error...

**Comment by DoughnutDev** [comment]
Yeah that is what I was thinking too. I will mess around with it.
