### ISSUE TITLE
[Suggestion] method to retroactively add blocks generated at worldgen to a world already created

### ISSUE THREAD

**Issue by neonfrontier** [BluSunrize/ImmersiveEngineering#180]
If it doesn't exist already and it's not too hard to do, just hoping to see this. There are some mods around that can already do it.

**Comment by BluSunrize** [comment]
It's called retrogen and I have considered it, but so far it hasn't seemed necessary, since the ores added by IE are very common.
Thermal Foundation adds everything except for aluminium, and that is brought in by tinkers.
Also, someone on Reddit I think made a script for CoFH to retrogen IE ores...

**Comment by neonfrontier** [comment]
Awesome, maybe that script can be linked to or put somewhere for people to reach? :)

**Comment by BluSunrize** [comment]
http://pastebin.com/sUGaLWEk

There you go, cofh script =3
