### ISSUE TITLE
Thermoelectric Generator doesn't extract his energy to other mods

### ISSUE THREAD

**Issue by ExDomino** [BluSunrize/ImmersiveEngineering#1800]
Hello. On our server, the thermoelectric generator doesn't produce any energy at all. It is placed and there is a water source and a lava source beside it, in front of each other, but no energy is produced. The documentation says that 15 RF/t would be produced in this case. Minecraft 1.10.2, Mod version: 0.10-52.

**Comment by ExDomino** [comment]
Fix: In fact, they are working, but completely incompatible with Ender IO Energy Conduit.

**Comment by VT-14** [comment]
Power API issue.  Immersive Engineering generators produce Immersive Flux (IF) which is 1 to 1 with RF.  The IE wires do have coding to convert IF to the CoFH RF API (and maybe Forge Energy?), but it is not handled at the generator.  I believe IF was made so IE is not dependent on an external power system (RF took a while to update when mods started porting to 1.8).

I assume there is a good reason for the conversion to be handled this way, but I don't know what it is (I only know super basic programming).  I will say that it would be convenient if generators could output RF/Tesla/ForgeEnergy directly.

**Comment by BluSunrize** [comment]
Ah, that's my bad. I forgot to move the ThermoElectric over to the new energy utility methods that allow RF and FU compat. Thanks for pointing it out, I'll see to fixing thins.

**Comment by ExDomino** [comment]
Can you add a config option to make that the word IF is replaced by RF ?
Because it's really annoying to have a lot of different energy names, even if they are 1:1.

**Comment by BluSunrize** [comment]
Nope, because that's misrepresenting. All IE internal calculations are done with Immersive Flux, and as such, its GUIs, WAILA and One Probe will display it as such.
It can be converted 1:1 to RF or FU, but it actually is a different codebase.

**Comment by ExDomino** [comment]
I know it's totally different, for you, but for us, players, it's the same thing. If RF and IF is 1:1, for us, RF = IF and it's just confusing to see another name there.

**Comment by BluSunrize** [comment]
It says "Flux" in the manual, and players are quite obviously aware that it's the same thing, lol. Otherwise, feel free to tell every other dev to relabel everything to "Forge Units", since that is apparently the new standard now x3

**Comment by bookerthegeek** [comment]
Forge Units.... I think, perversely, I prefer Extra Utities name for it.
