### ISSUE TITLE
Conveyor belt texture problem when placed

### ISSUE THREAD

**Issue by Serico86** [BluSunrize/ImmersiveEngineering#1801]
I have this problem when I place conveyor belt
in my hand there's no problem..I use the latest version of the mod and MC 1.10.2

![2016-12-17_02 52 02](https://cloud.githubusercontent.com/assets/24575754/21283572/f02d8ee8-c404-11e6-8ed1-bdcb08b78c64.png)

**Comment by BluSunrize** [comment]
Where did you get the conveyor item from?
Was it crafted? If so, which workbench did you craft it in?
Does the item have a proper tooltip?
What items do you get back when you break these conveyors?

(also, please never say "I use the latest version", always state your version number ^^)

**Comment by Serico86** [comment]
The version is 0.10-53
I'm using refined storage. In the tinkers workbench and vanilla got same problem.. In creative work perfect (the name is Conveyor Belt)
When i craft and break conveyor (picked up in creative mode) the name is "tile.immersiveengineering.conveyor.name" and when i placed it again, change direction and the texture is missing
I'm in singleplayer and I use Optifine 1.10.2 HD U D4 and BetterFps 1.3.2...I tried to remove them but the problem still present

**Comment by BluSunrize** [comment]
Could you show an image of your crafting grid?
Specifically, I'll need you to remove Optifine and BetterFPS, put the recipe in and then hover your cursor over the output.
I know this sounds oddly specific, but that's the best way to get a lot of information on the matter.

Is this a custom modpack, or are you using a public one?
Could you provide a test crash please? Hold F3+C, then upload the log to pastebin or a similar site and provide a link.

**Comment by Serico86** [comment]
I removed the config file (i just put 0 on oregen vein).. now work but i have another issue.. the conveyor cross texture when i change direction with the hammer.. i recorded a video:
[https://www.youtube.com/watch?v=JhAJX7jfh2E](url)

Here there is a pastebin of a test crash when the conveyor texture are crossed:
[http://pastebin.com/jVWXDWTj](url)

**Comment by progheal** [comment]
Having the same issue but is reproduced via ProjectE.
The conveyor belt pulled out of ProjectE transmutation table has the same issue as OP has (texture missing and the item name becomes `tile.immersiveengineering.conveyor..name`). Freshly crafted conveyor belt via vanilla workbench works fine.

Happens in the modpack Skyexchange 1.3.2, using Immersive Engineering 0.10-56 and ProjectE 1.2.0.

**Comment by BluSunrize** [comment]
That'S ProjectE's fault. They don't copy stuff with NBT data. Nothing I can't do about it.
