### ISSUE TITLE
Liquids using tints are not colored in tank rendering

### ISSUE THREAD

**Issue by KnightMiner** [BluSunrize/ImmersiveEngineering#1803]
![2016-12-17_20 37 43](https://cloud.githubusercontent.com/assets/12155288/21291090/2fbed9ba-c499-11e6-97ee-76c9e6c244aa.png)

Any liquids which use tinting to add their colors (such as nearly any liquid from Tinkers) only displays as a colorless liquid. Shown in the picture is purple slime on the left, and molten emerald on the right.

Using Immersive Engineering 1.10.2 0.10-53, and Forge 12.18.3.2185.

**Comment by BluSunrize** [comment]
I'll look into that, cheers for the report
