### ISSUE TITLE
getting fluid from tank to bottle?

### ISSUE THREAD

**Issue by Antonyvw** [BluSunrize/ImmersiveEngineering#1805]
Just a quick question. How do I get fluid out of a tank into bottles?

I have a coke oven set up so the fluid is put into a tank. But I cant figure out how to get the fluid from there into bottles.

**Comment by laz2727** [comment]
Bottler?

2016-12-18 12:51 GMT+05:00 Antonyvw <notifications@github.com>:

**Comment by laz2727** [comment]
Bottling Machine. There's a search function in the book.

2016-12-18 13:11 GMT+05:00 Antonyvw <notifications@github.com>:

**Comment by BluSunrize** [comment]
And they are probably playing 1.10 unless stated otherwise, which doesn't feature the bottling machine. Sorry to say @laz2727 but you're no helping =P

@Antonyvw IE currently doesn't feature any creosote bottles, so could you please detail which mod provides the creosote bottles your are trying to make?

Also, please provide your version number.

**Comment by Antonyvw** [comment]
Ok thanks for the update. I was using just the basic glass bottle from minecraft itself as I did not see any other empty bottles. And as for version I'm running Minecraft 1.10.2 with the latest version if IE.

**Comment by BluSunrize** [comment]
please check JEI to see if you actually have a mod that adds a creosote bottle.
Because if you don't, you won't be able to fill a bottle ^^

**Comment by Antonyvw** [comment]
The only other mod I have installed that uses creosote is Railcraft. But at the moment that mod is not complete and many of its features like the coke oven are not yet available.
I know I'm able to just put a bucket into IE's coke oven to get the creosote but I had hoped to be able to bottle it. But I shall be patient and wait for you to complete that section of your update. I much appreciate your time and effort so its not a big deal to wait.
