### ISSUE TITLE
[1.10.2] Crash inmany crafting tables with Shader Grabbag

### ISSUE THREAD

**Issue by Naheulf** [BluSunrize/ImmersiveEngineering#1808]
**What is the bug?** 
"The _client_ game crashed with this crash report: " [crash report](https://gist.github.com/Naheulf/d152e83f2add4f924cd91cccf6eaabd2).

**What did you do to make it happen?**
In crafting table, Place a "Restonia Crystal" (Actually Additions) in top-left slot and place two "Epic Shader Grabbag" (IE) in middle slot (3x3 crafting table) or in bottom-right (2x2 crafting table). Crash only in few relatives positions.
I tried to combine "Epic Shader Grabbag" with many other items from few mods: It doesn't crash but make strange recipes. E.g. Glass Bottle + Epic Shader Grabbag (IE) --> 2 x Rare Shader Grabbag.

**Does it happen every time you do this?**
Yes. Each times I make this recipe.

**Does it happen if you do something else as well?**
I not seen that.

**Did this happen on a dedicated server (multiplayer servers), in LAN multiplayer or in singleplayer?**
"I first noticed this on a server, but it happens in singleplayer as well."

**What other mods were installed when the bug happened?**
Many but not optifine and other optimization mods. See [crashReport](https://gist.github.com/Naheulf/d152e83f2add4f924cd91cccf6eaabd2).

**Comment by BluSunrize** [comment]
Think I know a fix for this.
I'll look into it.

Thank you for the well-formatted report, it's appreciated =)

**Comment by BluSunrize** [comment]
^ that commit fixed it.
