### ISSUE TITLE
[1.10.2] Q: Scaffolding Slopes

### ISSUE THREAD

**Issue by Bitterholz** [BluSunrize/ImmersiveEngineering#1809]
Whats the likelyness of Scaffolding Slopes making a Re-Appearance in 1.10?
Im really missing just even the simple 45° ones for decorative purpose. It just allways looked awsome with them!

**Comment by BluSunrize** [comment]
Yeah I haven't gotten around to getting them back in, because their dynamically sloping model is hard to do in the new rendering system.
It's still on my list.

**Comment by Bitterholz** [comment]
Well even just having the 45° one would make me super happy!

How about ditching the dynamicness? Would be fine with me if we had 1x1, 2x1, 2x1 and 4x1 ones
