### ISSUE TITLE
render issue with enderIO

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#181]
EIO = "Ender IO";
IE = "Immersive Engineering";

When configuring IO sides to any capacitor from EIO, the IE cables in the world stop rendering and incorrectly render on the 3D display of EIO's config GUI.
![image](https://cloud.githubusercontent.com/assets/3110986/8509740/e7e44f3e-226a-11e5-88ed-f76ac34790dd.png)
upon exiting the EIO GUI, things go back to normal.

issue seems to also occur when looking through an Ender IO from EIO....
![image](https://cloud.githubusercontent.com/assets/3110986/8509747/5cf3dd44-226b-11e5-8335-9e14fa2306c9.png)
(shot from underground to show where the cables end up rendering)

**Comment by BluSunrize** [comment]
Yeah, can't really do much about that one. It's how EIO does their weird rendering thing
