### ISSUE TITLE
ExtraUtils Generator + Fluid Pipe crash

### ISSUE THREAD

**Issue by jar555** [BluSunrize/ImmersiveEngineering#1810]
Full log: http://pastebin.com/2P1mbBeV

I was connecting a fluid pipe to the extra utilities 2 magma generator when the client crashed. I was able to remove the pipe using MCedit and my client stopped crashing.

**Comment by Lazarix** [comment]
I'm getting the same error: http://pastebin.com/7wacHD0A

This happens for me because someone placed the pipe in the nether. it crashes when i go into the nether now

**Comment by BluSunrize** [comment]
@Lazarix was the pipe in your case also placed next to an XU generator, or something else?

**Comment by BluSunrize** [comment]
I'd like either of you to try to replicate this in an environment with just Forge, IE and ExtraUtils please, and submit the errorlogs.

**Comment by BluSunrize** [comment]
This has been confirmed to be an Extra Utils issue, Tema should be able to fix this in the next release.

**Comment by megalous** [comment]
https://github.com/rwtema/extrautilities/issues/1199
