### ISSUE TITLE
[1.7.10] Rendering Issue when far out in the world

### ISSUE THREAD

**Issue by Dalarrus** [BluSunrize/ImmersiveEngineering#1818]
When you go far out in a world, in my case, I was at an X of 2,256,492, certain ingame models fail to render properly. The most noticable of which is the Wire connectors, 
![2016-12-24_01 06 59](https://cloud.githubusercontent.com/assets/12202558/21465755/9cc22536-c975-11e6-81bd-cd938533d7b9.png)

Water mills appear to render normally, as do the whole blocks and the wires.

**Comment by ArukaAlter** [comment]
1.7 is no longer supported.
