### ISSUE TITLE
[1.10.2] Assembler Crashloop NPE

### ISSUE THREAD

**Issue by Bitterholz** [BluSunrize/ImmersiveEngineering#1819]
Running IE Build 53 in DW20-1.10-1.2.1
Added recipe for IC2's Circuit into the Assembler, now the World is in a crash-loop caused by an NPE when checking for available Ingredients in the Assemblers TileEntity.
Log:
http://pastebin.com/6NhYwstb

Minecraft: 1.10.2
Forge: 12.18.3.2185
IE: Build 53

**Comment by BluSunrize** [comment]
Most likely related to #1804
Fixed for future releases =)
