### ISSUE TITLE
[Suggestion] Make power tiers incompatible

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#182]
suggestion: Make the different Tiers of power (L/M/HV) incompatible.
imho, one should not be able to pump HV power into an LV appliance, as doing so would greatly damage/destroy the appliance due to overheating\frying the circuitry.
Without good reason (besides conscientious effort for realism by the player) The transformers have no use besides stepping up the voltage for transportation; one currently has no need to step-down the voltage as any appliance will accept HV charge regardless of if its labeled as an L/MV appliance.

<OP>
Built against Commit 6c7e8133a65187033ab35e843ecbca353aa94a87

Connected an LV capacitor to my HV power line.... 
Capacitor accepted power at full HV rate

I was under the understanding that the three tiers of power are directly incompatible with one another, hence the need for transformers
I was expecting the LV capacitor to either
 (a)accept no power from MV/HV 
or 
(b)explode like when an machine from IC2/GT was given too much power.

</OP>
Edit: corrected spelling mistakes...

**Comment by wafflemans** [comment]
Well ic2 is weird, and most RF based storage mediums are backwards compatible. it just doesn't have the storage capabilities of a HV capacitor

**Comment by theunkn0wn1** [comment]
I expected the LV capacitor to malfunction if provided with such high voltage input, as it is significantly more energy than it was designed to hold\process.
 I understand that RF storage devices does not care about how much they receive in one tick by default, but I had expected the LV/MV/HV energy nets introduced in this mod to be directly incompatible given this is a 'realism' type mod; one should not be capable of pumping HV current into an LV capacitor with impunity.

I referenced IC:2 as it introduces an (IMHO) really effective deterrent to mixing power tiers. I understand no such mechanic currently exists within this mod, but expected something, like direct incompatibility between tiers, to have been introduced by now.

**Comment by wafflemans** [comment]
if it's a suggestion then sounds good

**Comment by MyDeloreanWontStart** [comment]
I don't know about this, it mat break compatibility with other RD mods. Also people would think the mod is copying if2.

**Comment by XFactHD** [comment]
I think they are already different in the what can input and output. At least it seems to be because you can configure the energy input and output.
It's exactly the same thing as with the different tiers of Thermal Expansion Energy Cells, which means the problem, if existing, is not in the RF API.

**Comment by BluSunrize** [comment]
I willl /never/ make machines explode based on power.
As for them accepting any sort of power: Sorry buddy, that's how RF works. I cannot change that without making IE incompatible with any other RF mod. Also, even though HV lines can feed into LV capacitors, the capacitor still only accepts 256RF/t so the HV lines is entirely pointless and wasteful.
