### ISSUE TITLE
[IE 0.10-52] Revolver creating Empty Casings when loaded with Buckshot Shells.

### ISSUE THREAD

**Issue by MrBlockers** [BluSunrize/ImmersiveEngineering#1820]
I'm not sure if the Revolver is supposed to be capable of loading buckshot, but it seems that the revolver is hard-coded to replace the spent ammunition with Empty Casings regardless of what type you use. (Buckshot uses shells in its recipe.)

**Comment by BluSunrize** [comment]
Thanks for the report, I'll look into it
