### ISSUE TITLE
[Bug] Fluid pipes and Extra utilities generators crash

### ISSUE THREAD

**Issue by Zankyou** [BluSunrize/ImmersiveEngineering#1822]
When I place a fluid pipe on either the magmatic or the heated restone generator, the game crashes.
EnderIO Fluid conduicts in combination with the Extra utilities generators do not cause a crash. 
I've turned off all the other mods and it still causes the crash. 

Crashlog:
[http://pastebin.com/PWFMgt4y](url)

**Comment by VT-14** [comment]
#1810 

Please use the searchbar before posting a new issue to avoid duplicate reports.

**Comment by Zankyou** [comment]
I'm sorry, I did search though.

**Comment by BluSunrize** [comment]
I doubt that, since searching for "generator" brings that issue up quite quickly.
