### ISSUE TITLE
[Improvement] Add a scrollbar to the manual

### ISSUE THREAD

**Issue by xbony2** [BluSunrize/ImmersiveEngineering#1824]
It's missing! D:

It's not really missing, it's just that the "Tools and Simple Machines" category is too big, and that it has no room to append it I believe. Search works though.

**Comment by BluSunrize** [comment]
Scroll down in the category with the assembler at the bottom Am 28.12.2016 11:29 nachm. schrieb xbony2 <notifications@github.com>:It's missing! D:
It's not really missing, it's just that the "Tools and Simple Machines" category is too big, and that it has no room to append it I believe. Search works though.

**Comment by xbony2** [comment]
Welp, that works ^_^ It would be nice if there was a scroll bar or a way to know that scrolling was option, though.

**Comment by BluSunrize** [comment]
Yeah, I know I need to add that, just didn't get around to it yet. Last release was a bit rushed =P
