### ISSUE TITLE
Missing creosote oil

### ISSUE THREAD

**Issue by DoctorDitto** [BluSunrize/ImmersiveEngineering#1829]
Creosote Oil seems to be missing from my game. The texture is purple and black and the coke oven won't let me put it in a bucket.

**Comment by ArukaAlter** [comment]
Creosote bottles were removed, but the liquid missing texture is the issue.

**Comment by DoctorDitto** [comment]
It seems to be missing from the world itself. The creosote bucket isn't showing up in NEI either.

**Comment by XFactHD** [comment]
MC version? IE version?

**Comment by DoctorDitto** [comment]
Sorry, I'm on version 1.10.2 on minecraft and version 0.10-54 on IE.

**Comment by ArukaAlter** [comment]
Couldn't confirm, the liquid showed normal in the Coke Oven UI, and could be bucketed out as well.
Some other mod may be the culprit.

**Comment by BluSunrize** [comment]
^ This.
Please try to figure out which other mod causes the interference.
First, of course, you just test with IE, and nothing else, and see if it works,
After that, you take your modpack, remove half the mods and see if the issue persists. If it does, take half out of the remaining ones and keep going like that. Should the issue ever "disappear", you know that you have removed the interferring mod and you can check the last removed ones to figure out which of them caused it.

**Comment by DoctorDitto** [comment]
So it turns out that railcraft was the issue. Meh, I didn't really use it anyways. Thank you

**Comment by KnightMiner** [comment]
Sounds like an issue with the fluid registration order, I use RC and IE and it works fine.

**Comment by DoctorDitto** [comment]
How would I fix that?
