### ISSUE TITLE
All cartridge textures are messed up

### ISSUE THREAD

**Issue by ArukaAlter** [BluSunrize/ImmersiveEngineering#1830]
IE 0.10-54
Forge 12.18.3.2185

![](http://i.imgur.com/rZaTVCz.png)

**Comment by BluSunrize** [comment]
Is this upon starting a new game? Or have you used the reload function for textures and resources?

**Comment by ArukaAlter** [comment]
I had a vanilla resource pack loaded before, but the cartridges were using these textures before unloading the resource pack.
