### ISSUE TITLE
Cannot transmit power using IE cable

### ISSUE THREAD

**Issue by akitainuowner** [BluSunrize/ImmersiveEngineering#1831]
I can take power from an IE generator using ender IO conduit but cannot get power at all when using IE wire.  Same for powering anything that needs wire will not power not even the lantern.

Version is 10.54

![2016-12-30_15 54 25](https://cloud.githubusercontent.com/assets/4693506/21559886/1a70b00a-cea9-11e6-8459-e98e56ca5773.png)
![2016-12-30_15 54 28](https://cloud.githubusercontent.com/assets/4693506/21559889/1decb30a-cea9-11e6-8c16-4facd818fd77.png)

**Comment by BluSunrize** [comment]
I'll look into this when I get back from my holidays.
Thanks for the report.

**Comment by malte0811** [comment]
The blocks you are using look like LV relays to me. You need to use LV connectors to get energy into and out of the net. You can not connect multiple wires to a connector, that is the purpose of relays.

**Comment by kane-thornwyrd** [comment]
most.common.mistake.

**Comment by BluSunrize** [comment]
Hah! Didn't even see that. I'm a derp.

Yeah it's an LV relay, it doesn't work like that. xD
