### ISSUE TITLE
Game experiences extreme lag after placing down a wooden, steel, or aluminum post

### ISSUE THREAD

**Issue by DoctorDitto** [BluSunrize/ImmersiveEngineering#1832]
MC Version: 1.10.2
IE: 0.10-54

When I place a post in my world, it creates an immense lag spike, which renders the game useless. The only fix is to go in through MCEdit and remove the post from the world.

**Comment by DoctorDitto** [comment]
So after testing out each and everyone of my mods, the problem seems to be NEI

**Comment by BluSunrize** [comment]
Mkay. Closed I guess?
