### ISSUE TITLE
Client crash when in specific area of the world

### ISSUE THREAD

**Issue by thefiz** [BluSunrize/ImmersiveEngineering#1836]
Whenever a player is in a specific area of the world, their client crashes, and a report is generated.  Based on what I'm seeing in the report, the issue is IE.  Please correct me if I'm wrong.

I'd like to keep IE, but the only way to fix this right now is to disable it.

(This is the version in the Direwolf20 1.10 pack, Dec29 beta)

[crash-2017-01-01_17.19.57-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/680224/crash-2017-01-01_17.19.57-client.txt)

**Comment by BluSunrize** [comment]
Most likely caused by RWTema's generators. See #1810
