### ISSUE TITLE
CraftTweaker Recipes No Longer Display in JEI

### ISSUE THREAD

**Issue by Ommina** [BluSunrize/ImmersiveEngineering#1837]
Through some recent changes in the interaction between CraftTweaker and JEI (predicated by a desire to eliminate the connection timeouts many were experiencing when attempting to connect to a server), Immersive Engineering recipes added through CraftTweaker no longer appear in JEI.

They work, but do not display, which is less than totally lovely.

I don't know the details of the solution, but I'm told it can (or will be, or something like that) found at jaredlll08/CraftTweaker#127

Thanks!

**Comment by Joshwoo70** [comment]
... fixed in latest JEI and crafttweaker. update to latest version.

**Comment by Ommina** [comment]
Both versions are current.

However, I may not have been wholly clear.  IE recipes have _stopped_ working _after_ the update to the most recent versions of JEI and CraftTweaker.

**Comment by jaredlll08** [comment]
IE has to update as well, all mods that have Minetweaker integration need to update

**Comment by BluSunrize** [comment]
@jaredlll08 that sorta stuff is something you should then inform people off =P
The MT wiki states which mod has internal support, so maybe contacting those authors is a good idea next time xD

**Comment by jaredlll08** [comment]
yea sorry, this is my fault :/ It slipped my mind until it was too late :(

Also the wiki is very out of date, it still lists blood magic as having internal support

**Comment by BluSunrize** [comment]
Fixed with this commit:
https://github.com/BluSunrize/ImmersiveEngineering/commit/a6d730485e2bcee2f965b7e809edf42a4b610ff7
