### ISSUE TITLE
[Suggestion] A config option to change the drop rate of hemp seeds from tall grass.

### ISSUE THREAD

**Issue by TheCorruption** [BluSunrize/ImmersiveEngineering#1840]
I'm playing with better with mods which adds its own hemp crop, so I tried looking for a config to disable the IE seeds, but I couldn't find anything that changed the drop.

**Comment by WesCook** [comment]
Better with Mods can override the Immersive Engineering hemp drop, or it can disable its own.  Personally I opt for IE's hemp as it grows faster and I think looks nicer.

**Comment by KnightMiner** [comment]
Same, I just disabled the Better With Mods hemp crop seed drop from grass, but required the unprocessed hemp from Better With Mods as the drop.

**Comment by TheCorruption** [comment]
Well, I like the BWM hemp better, it fits better in farms, there should at least be a config for it.

**Comment by WesCook** [comment]
There is, in the BWM config.

```
# Replaces drop from IE Industrial Hemp with BWM Hemp [default: true]
B:"Override Hemp Drop"=true
```

**Comment by TheCorruption** [comment]
I'm not trying to replace the fully grown hemp drop, I'm trying to stop the IE seeds from dropping from tall grass.

**Comment by WesCook** [comment]
Ah, I assumed it was from grass drops.  Getting back a different plant seed would be strange.

Sorry, I don't have an answer in that case.
