### ISSUE TITLE
Startup Crash

### ISSUE THREAD

**Issue by MrFrostmaul** [BluSunrize/ImmersiveEngineering#1841]
Hello,

We have this crash on startup of server.  http://pastebin.com/s1FvnCre 
Running ImmersiveEngineering-0.10-54.jar   and forge forge-1.10.2-12.18.3.2185.jar   also, TConstruct is the latest version.

**Comment by BluSunrize** [comment]
Report to TCon, please, the crash is definitely on their side.
However, I don't believe it's caused by them. You are somehow missing java's vecmath library, which shouldn't ever be possible, really.
Is this a custom server or are you customer of a server hosting company like CreeperHost?

**Comment by MrFrostmaul** [comment]
Ok thanks, sorry. Found the issue. Forge was corrupting its libraries when generating them from the jar we had downloaded. Working now with good libraries.
