### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by UnuAlex** [BluSunrize/ImmersiveEngineering#1842]
Hi! Every time i start the game it gets crashed because of IE. I already updated mod to 0.7.7 and forge to latest version(1.7.10 - 10.13.4.1614) and still doesn't work. What to do to fix it?

Here is the crash log: http://pastebin.com/8ii0sdDN

**Comment by BluSunrize** [comment]
Delete your IE config.

**Comment by UnuAlex** [comment]
That worked, thank you mate!
