### ISSUE TITLE
Tesselating block in world w/ extra utilities 2 magma generator

### ISSUE THREAD

**Issue by Ryahn** [BluSunrize/ImmersiveEngineering#1843]
Hello,

We have a few instances where we are getting a crash with our users in our mod pack when using IE wiht EU2.

It occurs when trying to place an IE pipe on top of a magma generator from EU2.

This is the crash - https://gist.github.com/Ryahn/773c7d6e36dfeeed79f6255e3e84776c

**Comment by BluSunrize** [comment]
Issue in XU. To my knowledge, Tema is working on/has released a fix,
