### ISSUE TITLE
chisel and bits

### ISSUE THREAD

**Issue by Sitherious** [BluSunrize/ImmersiveEngineering#1845]
i love your mod and i love chisel and bits also, works great in single player but it doesnt work in multiplayer as i get this error.

https://github.com/AlgorithmX2/Chisels-and-Bits/issues/225

**Comment by BluSunrize** [comment]
@AlgorithmX2 I assume a SideOnly(CLIENT) would actually fix this on my end, but may I ask what exactly you are doing to even trigger that?

**Comment by AlgorithmX2** [comment]
You'd be correct, I simply was reflecting the block class to see if you were overriding a method.

Reflection tends to load things that just class loading doesn't 

Line in question if your interested: https://github.com/AlgorithmX2/Chisels-and-Bits/blob/777279a8140e964cf9ff4af93aad8762954d9893/src/main/java/mod/chiselsandbits/chiseledblock/BlockBitInfo.java#L265
