### ISSUE TITLE
java.lang.NullPointerException: Ticking entity

### ISSUE THREAD

**Issue by Hypsellis** [BluSunrize/ImmersiveEngineering#1846]
I got this crash while walking on the world, I don't know what caused it. http://pastebin.com/mpRy5uQz

**Comment by BluSunrize** [comment]
I'd assume either a null sound or an undefined category.
Means some other mod is doing something wrong.

I'll add a check.

**Comment by Hypsellis** [comment]
I think it's Dynamic Surroundings which do something wrong, I will report it to his owner too.
