### ISSUE TITLE
Can't place Wire Connector in some machines

### ISSUE THREAD

**Issue by SibMaus** [BluSunrize/ImmersiveEngineering#1848]
I've download the mod yesterday and was amused by it. I really liked this realist approach. So I was testing everything that could be done, and encountered this problem that I can't place Wire Connectors in the Squeezer, Fermenter, Refinery nor the Assembler. Everytime I try to place it, the respective machine GUI appears and so I can't power them.

I'm not using any other mod apart from IE, Optifine and BetterFPS. Tried doing the same in different worlds but no luck. Also, I don't know if it's supposed to be like that, but in the same machines, the GUI will appear if I click in any block.

**Comment by ArukaAlter** [comment]
You don't know the vanilla mechanic to hold the sneak key to not open GUIs?

**Comment by SibMaus** [comment]
I actually didn't know that... Seems like I'm just dumb. Anyway thanks, that solved my problem. So there wasn't any issue with the mod
