### ISSUE TITLE
Vertical Conveyor Belts Render as Normal Conveyor Belts On Reload

### ISSUE THREAD

**Issue by Archeagus** [BluSunrize/ImmersiveEngineering#1849]
Occasionally, vertical conveyor belts will take on the appearance of the normal conveyor belts in each block tile. The result is a stack of hovering horizontal conveyor belts or ramped conveyor belts one over the other. They still ACT as vertical conveyor belts and will still deliver items to their desired location, but they just appear broken and count as the entire block in regards to the hitbox and item/player collision.
This occurs randomly with any and all initial loads of the game from the launcher and the only way to change is to close the game completely and restart the launcher and hope for the best.

Version 1.10.2: 0.10-54

**Comment by BluSunrize** [comment]
Could you provide pictures please?
