### ISSUE TITLE
SkyFactory 3: Post Extension issue

### ISSUE THREAD

**Issue by Dadcraft73** [BluSunrize/ImmersiveEngineering#1851]
Just had an issue show up in my latest Sky Factory 3 video, when attempting to right click on the Posts to extend the sides I got a strange display/graphical error.  Instead of extending the "arms" it instead showed another pole in the air beside the existing pole.  See Screen Shot for details. 
![iebug](https://cloud.githubusercontent.com/assets/24500294/21943071/b1096076-d99d-11e6-9c15-cd870b835055.png)

Screen shot may be dark, I apologize.

**Comment by BluSunrize** [comment]
Just place another block next to it or relog or something. It's just a render update issue. Can't do much about it.

**Comment by AEnterprise** [comment]
@BluSunrize can't you triger said block/rendering update when the data has synced to the client?
