### ISSUE TITLE
[0.10-54] [1.10.2] Client Crash when breaking Ores

### ISSUE THREAD

**Issue by clifftrials** [BluSunrize/ImmersiveEngineering#1854]
Not sure why, but when breaking an ore from this mod, the client will crash. I tested this on my server with other members, and only the individual who breaks the block will crash. The ores we tested thus far were only Silver Ore and Uranium Ore. The crash log doesn't mention Immersive Engineering, but we're only experiencing it with the Ores from this mod thus far. 

Crash with Silver Ore: http://pastebin.com/wBL9Dqqq

Crash with Uranium Ore: http://pastebin.com/qjPDppNC

I have tried breaking the Ore with a pick in survival --> Client Crashed.
I have tried breaking the Ore with my fist in Creative --> Client Crashed.
I have tried placing the Ore elsewhere in the world (1000s blocks away) --> Works.
I have tried breaking the Ore that was placed elsewhere --> Client Crashed.
This crash does not occur in Single Player.

Any ideas? 

Edit: I've also posted an Issue report with Applied Energistics 2, since it's referenced in the error log: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2758

**Comment by BluSunrize** [comment]
Not my fault, as far as I can see.

**Comment by mindforger** [comment]
he blamed it also on AE2, corrupted world is the guess over there

**Comment by Bitterholz** [comment]
AE Issue has been closed allready, confirming its a broken world.

@clifftrials Id recommend returning your world to a previous backup, if you have one.
Otherwhise there aint much that the mods can do about this(aka nothing).
In case you do not have a Backup, im very sorry to tell you but that world is done for...

**Comment by clifftrials** [comment]
Thanks for the response guys. I'll weigh in my options and proceed. Cheers!

**Comment by AEnterprise** [comment]
if you don't have a backup you could always try to make a new world with the same seed and copy over the region files, unless you did some major mod updates that might work (or in case mods did add new items/blocks id's might have shifted and break even worse, depends on the world age)
