### ISSUE TITLE
[Request] Additional options for Ore Duplication

### ISSUE THREAD

**Issue by Bitterholz** [BluSunrize/ImmersiveEngineering#1855]
Hi,

Ive played with IE for a while now, and ive come to notice its way to "Increase ore Yield" is awfully similar to the way most mods do it, aka. Crush it before smelting for 2x the Dank Ores.

Id love to see a bit more complexity to the whole "Ore Processing" approach. Maybe even an option to increase the Yield above 200%.

Most interesting in that regard is, in my eyes, the way IC2 handles this. AkA. Crush->Wash->Centrifuge->Smelt. Wich Yields you a total of 222% of the Original Ore(2x washed ore & 2x tiny ore dust[a nugget]), a Piece of Stone Dust and an additional 11% of an additional ore(assuming each ore has a compound of impurities, e.g. iron Yields one Tiny Gold Dust).

It would be brilliant if IE would offer a similar Process, allowing the Player to get extra Yield for extra Work, instead of a simple 1-2-Punch to double ores

**Comment by BluSunrize** [comment]
I dislike ore multiplication that goes beyond 2, so I don't plan on it.
Plus it'd require fully changing the entire system on an existing release, which is not a good thing to do from a developers perspective.
