### ISSUE TITLE
Crusher Process Queue causing error: "Tried to read NBT tag that was too big"

### ISSUE THREAD

**Issue by jacobped** [BluSunrize/ImmersiveEngineering#1858]
Much like issue #1607 
On a multiplayer server filling up the crusher with cobblestone kicks clients with the following error: "Tried to read NBT tag that was too big"

### Versions:
* Minecraft: 1.10.2
* Forge: forge-1.10.2-12.18.3.2202-universal

### Mods on server and client:
* **ImmersiveEngineering-0.10-54**
* tinyprogressions-1102-1017
* EnderIO-1.10.2-3.1.156
* EnderCore-1.10.2-0.4.1.62-beta
* NotEnoughItems-1.10.2-2.1.3.182-universal
* jei_1.10.2-3.14.2.401
* CodeChickenCore-1.10.2-2.4.0.100-universal
* CodeChickenLib-1.10.2-2.5.1.185-universal

Picture of the error on the client:
![image](https://cloud.githubusercontent.com/assets/1295472/22033308/4c70142c-dce8-11e6-850d-a11ba0243cde.png)
A look at the region chunks file with NBTExplorer shows the following which i believe is for the crusher:
![image](https://cloud.githubusercontent.com/assets/1295472/22033529/27c64000-dce9-11e6-88ca-792eda8e5acd.png)

I have recreated the issue multiple times, and can supply a server-zip for testing, where it happens within 5 minutes. Just not sure it it's okay to supply that. :)
Destroying the crusher have fixed the issue every time.

**Comment by BluSunrize** [comment]
Maybe don't put 2546 stacks of stuff in your crusher, lol.

**Comment by jacobped** [comment]
Heh, yea. It would certainly help having a way to stop it from accepting more. :)

**Comment by BluSunrize** [comment]
there's two options for that.
Either I destroy anything thrown in afterwards. Or I don't and you have a load of item entities instead that kill your server.
Neither option would please the players, and both would require them to regulate their input. So they might as well regular their input now. =P

**Comment by codewarrior0** [comment]
All three options are displeasing. 

You can't do much if the items are rolled in via plain conveyors, but for item insertion, you can at least reject items if the process queue is long. This means smart inserters like Conduits, Itemducts can refrain from inserting more, and even the Dropping Conveyor should roll the item along instead of dropping it in.

**Comment by jacobped** [comment]
I'm closing this issue. Not because it is solved, but because it's old and clearly wont be solved. :)
And thank you for your work and great effort!
