### ISSUE TITLE
[suggestion] Provide a way to deal with item overflows from conveyors

### ISSUE THREAD

**Issue by canassa** [BluSunrize/ImmersiveEngineering#1860]
Hello,

First, I would to say that this mod is really awesome, thank you for investing your time into creating such an amazing work.

Second, I would to make a suggestion regarding the conveyors. I am currently playing on a server with the Direwolf20 1.10 pack but I am personally trying to only use Immersive Engineering. My main trouble right now is how to deal with items overflowing when the conveyor destination has no space left. I managed to workaround that by looping the conveyors and waiting from the destination to empty. But sometimes that's not possible.

A common scenario is when trying to send seeds to the presser, if the presser is full the seeds will just start to accumulate in the conveyor.

I guess that a easy way to solve this would be to add a default route to the item router, so the item router would first try to insert into it's marked destination and after that fallback to the default route.

Thanks!

**Comment by BluSunrize** [comment]
yeah, fallback to the router could be done.
What you should be able to do right now, is use a dropping conveyor. It will try to insert into an inventory below it, and if it can't, it will keep going horizontally.

**Comment by Bitterholz** [comment]
Yeah im using dropping conveyors in my IC2 Factory to feed the macines safely and loop arround Overflows.

Should work with most machines

**Comment by canassa** [comment]
Thanks! I didn't think about using the dropping conveyor as way to control overflows. I think this solves my problem. 😄
