### ISSUE TITLE
[Dupe Bug][0.10-55] Bottling machine

### ISSUE THREAD

**Issue by bbgott** [BluSunrize/ImmersiveEngineering#1861]
MC: 1.10.2
Forge: 12.18.3.2185
IE: 0.10-55

If you use a conveyor belt to feed buckets into the bottling machine.  If there are more than 2 empty buckets queued up waiting to go into the bottling machine, it begins to massively dupe the buckets.  As it runs, it'll pull a bucket in, but doesn't seem to decrement the buckets waiting to go into the machine.  It'll continue grabbing buckets from the input queue and feed them thru the system.  It seems to only render one bucket going thru, but multiple buckets will get ejected.  It gets out of hand quickly.

**Comment by BluSunrize** [comment]
Cheer's, I'll look into fixing that.
In the meantime, I'd recommend using a hopper, since those insertions won't allow for duping.

**Comment by omega025** [comment]
Can confirm this happens with bottles too:  https://i.imgur.com/xEdWxGs.jpg

**Comment by bookerthegeek** [comment]
Question, is this duping the liquid?

**Comment by bbgott** [comment]
My experience didn't seem to be duping the liquid, just the containers.  Once the liquid ran out, the machine would just spit out the empty containers.

**Comment by BluSunrize** [comment]
Yes, it only dupes containers. I have also long since fixed it, I just haven't pushed to git in a while because I'm working on more stuff. =P

**Comment by omega025** [comment]
Thanks for the hard work, @BluSunrize!
