### ISSUE TITLE
[Suggestion] Hopper Conveyor Belt

### ISSUE THREAD

**Issue by JAWSAWN** [BluSunrize/ImmersiveEngineering#1863]
I have suggested this waaay back when this mod just released, but wanted to suggest again.
For people like me trying to use only the IE Belts to move stuff around, a hopper belt would be pretty nice. 
It basically removes the need of an hopper extracting from the inventory and exporting to the belt. Instead with this type of hopper it imports from the inventory that is touching (like a chest or a machine) and puts it on the belt system. 

I couldn't think of this before, but a simple filter option to this hopper would make things much nicer.

Also it should respond to redstone signal just like a hopper.

**Comment by JAWSAWN** [comment]
Also mod "Simply Conveyors" have already implemented this. 
https://github.com/Zundrel/Simply-Conveyors

**Comment by Bitterholz** [comment]
I do like the Idea! Given how bad Hoppers are for Tickrate and how obnocious they look, a Conveyor that takes stuff out of chests would be amazing

Maybe even require Power? idk

**Comment by BluSunrize** [comment]
Well if hoppers are bad for tickrate, why would you assume an extracting coneyor, with a filter no less, is better? =P

**Comment by Bitterholz** [comment]
Depends on the Implementation, last ive seen, hoppers where quite the Tickrate Hoggers on me servers.

Im pretty confident you could make a Extracting Conveyor that is efficient and aesthetically pleasing

**Comment by JAWSAWN** [comment]
Hm, I thought it would look like a normal conveyor belt with like arrow textures maybe, but adding a sideways hopper-like model would be interesting, also agree on performance thing, but it doesn't mean it would be bad.
Also powered with energy seems like a bad idea, hoppers don't work with power.

**Comment by BluSunrize** [comment]
In any case, yes I have considered it, I just haven't gotten around to working on it. ^^

**Comment by Jomik** [comment]
Please make this 😄 It'd be the last conveyor we need to be able to use them completely. Should be able to accept input from any side, or at least any side other than beneath perhaps.

**Comment by TeamSpen210** [comment]
This is implemented now, although not the filter/redstone.

**Comment by mindforger** [comment]
i don't know about the redstone function, indeed something usefull and probably(tm) easy to implement feature, but the filtering should be doable with an item rotuer underneath already ?! ... funny the issue is still open though :D
