### ISSUE TITLE
IE Crash with IC2C (OreDictionary)

### ISSUE THREAD

**Issue by Speiger** [BluSunrize/ImmersiveEngineering#1865]
One of my testers gave me a crashlog that is again bound to IE and its a really weird one.
First of all i am not sure if it is classics or your fault. Thats why i ask you what the problem could be.

Crashlog:
https://gist.github.com/JAWSAWN/a27fee65e75e25f8227a8b20326a4687

This is the function that is crashing.
```
private void addValuableOre(Item item, int meta, int value)
{
	Block block = Block.getBlockFromItem(item);
	if(block == null || block == Blocks.AIR)
	{
		return;
	}
	//This line crashes. Only with IE
	ClassicRecipes.oreRegistry.registerValueableOre(block.getStateFromMeta(item.getMetadata(meta)), value);
}
```
This is what calls the function:
```
@SubscribeEvent
public void onOreRegistering(OreRegisterEvent evt)
{
	String oreClass = evt.getName();
	ItemStack ore = evt.getOre();
	if(oreClass.equals("oreCopper"))
	{
		addValuableOre(ore.getItem(), ore.getMetadata(), 3);
	}
}
```
Here is the thing, it should not crash. Its a nullpoint exception but my "onOreRegistering" kicks only in when my registries (Also the OreRegistry) is already initilaized.
And even if you registered a null item or if the block would be null my Block == null or AIR check should prevent these kind of things.

So do you have any idea what could cause this kind of issue?
The only thing i could think of if threading is causing issues...

**Comment by Speiger** [comment]
Ok it seems to be neither IEs fault nor IC2cs fault.
From what i see and it gives me a headache some mod causes that all mods get no longer in the way it should be.
Yes i register myself to the EventRegistry before my Registry loader is inited. On the other hand my OreRegistry gets added to the same call. The only difference is: There is things between those things...
These kind of bugs only can happen with threading modloading which is bad idea in itself...
sry for bugging you...

**Comment by Joshwoo70** [comment]
@asiekierka
pinging foamfix author.

**Comment by AEnterprise** [comment]
@Speiger are you sure about that? as far as i knew foamfix only reduced ram usage by working on model stuff

**Comment by Speiger** [comment]
@AEnterprise the guy removed foamfix and the crashes stopped.
But when i checkt codewise i found no reason why it would happen.
But it's 100% that something caused a threaded like load of mods.
Because that is the only way this crash could happen.

**Comment by AEnterprise** [comment]
then most likely is another mod that does the threaded loading, it divides the mods into groups to be threaded and without foamfix the order of loading changes causing your mod to be loaded from a seperate thread instead of after the rest

**Comment by Speiger** [comment]
@AEnterprise you have the modlist look it up.
But a threaded loading system is a bad idea...
Mods should be loaded in an order after each other and not paralleled.
That makes modcompat just harder.
