### ISSUE TITLE
How to fill bottles on bottling machine

### ISSUE THREAD

**Issue by Antonyvw** [BluSunrize/ImmersiveEngineering#1867]
Ok I may just be being thick here but I cant seem to get the bottle to fill on the bottling machine (Latest update for MC 1.10.2). Ive tried adding them directly onto the belt Ive tried adding a new conveyor to the end and also feeding said conveyor with via a hopper. It leaves the hopper and travels the conveyor right up to the point where it should then go onto the machine but it stops at the first conveyor of the machine.
What have I missed? And how do I feed the bottles correctly?

**Comment by ArukaAlter** [comment]
If you are trying to fill the bottles with creosote, the news is: creosote bottles are deprecated and were removed (unless you have Railcraft)

**Comment by Antonyvw** [comment]
Thanks for that. But Ive also tried the above with buckets and get the same problem

**Comment by BluSunrize** [comment]
Could you please provide a picture of your setup?

**Comment by Antonyvw** [comment]
Hope this helps

![2017-01-22_14 33 18](https://cloud.githubusercontent.com/assets/24394848/22184962/4b91d01e-e0d4-11e6-9fbb-ea4ce6ae32cb.png)

**Comment by BluSunrize** [comment]
That does indeed help.
You put a relay on the machine instead of a connector. Relays can't insert energy, your machine lacks power.
