### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by Sitherious** [BluSunrize/ImmersiveEngineering#1869]
i am unsure what caused this.

console error: https://paste.ubuntu.com/23858083/

crash report: https://paste.ubuntu.com/23858076/

**Comment by BluSunrize** [comment]
Try again with latest IE, you're a version behind.

**Comment by Sitherious** [comment]
Ok

**Comment by PlayersOfNewAge** [comment]
Hello BluSunrize. I am playing Tekkit-Legends and I want to play your immersive engineering mod. But game is open and quickly crashing. What can I do?

**Comment by mindforger** [comment]
make a new issue, and click the link on the top which tells you to read the contributing guidelines, follow them and create an bug report according to it :)

**Comment by BluSunrize** [comment]
^ what he said.
