### ISSUE TITLE
Game crashes when loading world - Space astronomy pack

### ISSUE THREAD

**Issue by Foppwin** [BluSunrize/ImmersiveEngineering#1872]
Hi guys.

I hope that I do no waste your time to much. but I would really like to have some help.

How do I figure out what the error is and what to do about it.
I have tried using MCedit but dont know what to look for. I have seen a bunch of videos but nothing helps me.

I am sure that I am asking a question that someone else have posted before. I just dont know that I should search for to avoid that. so sorry in advance

http://pastebin.com/paWHQ26s

Thanks Foppwin

**Comment by Joshwoo70** [comment]
please report to modpack author before contactingup us. https://github.com/MJRLegends/Space-Astronomy-Feedback-
