### ISSUE TITLE
Pipes going North-South render weird

### ISSUE THREAD

**Issue by BrisingrAerowing** [BluSunrize/ImmersiveEngineering#1876]
Pipes going North-South don't connect to each other, while ones going East-West do.

See screenshot for what happens
![2017-01-28_16 30 04](https://cloud.githubusercontent.com/assets/250409/22399989/6eea053e-e577-11e6-958b-1742194eeb81.png)

**Comment by Bitterholz** [comment]
also puttin on/off a covering Scaffolding causes the nearby pipes to disconnect like crazy
