### ISSUE TITLE
[Suggestion] Green Copper Sheet Metal

### ISSUE THREAD

**Issue by the-realest-stu** [BluSunrize/ImmersiveEngineering#1877]
It seems a bit odd that copper sheet metal isn't already a thing. It would also be cool if it was green, allowing it to be used for roofing, as green copper sheet metal seems to be an extremely popular roofing choice in real life

**Comment by BluSunrize** [comment]
I might be misremembering my history here, but I believe that those roofs used to be copper coloured. Just time and weather oxidized it to be green. But I'll put it up for discussion.

**Comment by the-realest-stu** [comment]
well, yeah, but everyone now is used to seeing them as green. And the green looks cool. Maybe have a copper colored version, which can be crafted with water to get a green version?

**Comment by mindforger** [comment]
copperish greeenish mixed tint with a slight weight over to green

or make it adjustable :)

but absolute a yes for copper sheet metal use :)

**Comment by the-realest-stu** [comment]
If I'm not mistaken, aren't the copper blocks green? It would then make sense for the sheet metal to be green as well.

**Comment by Bitterholz** [comment]
As ive got a Big cathedral in my City, wich roof is 100% copper plated and just got renovated last year, I can confirm that the plates quickly turn green. Within a matter of about a month it was completely green again.

So yeah, a decorative green copper sheetmetal block set would be nice!

**Comment by VT-14** [comment]
From a few minutes of research on Wikipedia, it seems like copper will take a few years to form its verdigris colored patina from natural weathering.

That can obviously be sped up or slowed down using various treatments.  I'm sure the aforementioned cathedral was treated to make the roof green again as quickly as possible.


Personally, I would say make it green.  That's the color people making a 'copper' roof would go for.
