### ISSUE TITLE
Russian translation ImmersiveEngineering-0.7.7

### ISSUE THREAD

**Issue by lex1975** [BluSunrize/ImmersiveEngineering#1879]
This is not a bug report. I made a full translation mode version ImmersiveEngineering-0.7.7 in the Russian language. Please add.
[ru_RU(0.7.7).zip](https://github.com/BluSunrize/ImmersiveEngineering/files/748652/ru_RU.0.7.7.zip)

**Comment by malte0811** [comment]
1. There won't be any new versions of Immersive Engineering for MC 1.7.10 (unless something really unexpected happens), so submitting bug reports or improvements for 1.7.10 versions is mostly useless. If you want to add a translation (which we would appreciate very much), you should translate the 1.10.2 version (`master` branch).
2. Translations are usually added through [Pull Requests](https://help.github.com/articles/about-pull-requests/) like [this one](https://github.com/BluSunrize/ImmersiveEngineering/pull/535). An advantage of PR's is e.g. the ability to comment specific lines of the changes and suggest changes to them.

**Comment by lex1975** [comment]
Your mod is wonderful. But there are many other great mods until they adapted to the new version minecraft. For example Twilight Forest, BuildCraft, LOTR. Please add my translation, and lay version 0.7.7.1 now, as the alpha version, if you do not have time to check. I tested my translation in the game many times. Russian users will be grateful to you.
On the translation version under 1.10 I will try to work in his spare time. I need to create an assembly to test minecraft 1.10.

**Comment by riki00008** [comment]
как с
качать

**Comment by Remint32** [comment]
> 
> 
> как с
> качать

@riki00008 Читай внимательно - автор прикрепил файл к комментарию задачи.
