### ISSUE TITLE
Excavator not outputting/generating.

### ISSUE THREAD

**Issue by Skyqula** [BluSunrize/ImmersiveEngineering#188]
Hello, been trying to get some custom mineral deposits going using a mod called lodeloader: http://minecraft.curseforge.com/mc-mods/232319-lodeloader

To my surprise, the excavator didnt output at all. So i tried removing lodeloader, still didnt work. Make new worlds, rebuilding the excator, different deposit etc. nothing worked.

So I made a clean install. Just minecraft, forge 1448 and Immersive Enginering 0.3.3. And... doesnt work. Tested with a silver and a pyrite vein (http://i.imgur.com/ng0imEl.jpg). The excavator does not produce anny ores.

This problem already existed with #108 when it didnt pick up the uranium. It would show lead in the book as the only ore and the excavator would never output (dispite lead being there).

I am once again going to suggest making the ore lists fully configurable. As it seems that unless a specific set of ores(mods) is used, it just doesnt work. If pack creators can force wich ores are used we could simply prevent this from happening.

**Comment by BluSunrize** [comment]
Picture of your setup, please. Because it won't work if you don't set it up correctly.

**Comment by Skyqula** [comment]
Since the picture was already there, thought id show it in a video: https://www.youtube.com/watch?v=IL7ZSlGvJDI&feature=youtu.be

**Comment by BluSunrize** [comment]
The wheel needs to touch the ground.

**Comment by Skyqula** [comment]
Right, apparently it needs to be on a naturally generated piece of stone (breaks dirt, doesnt work then). Perhaps an idea to add that to the manual?

**Comment by BluSunrize** [comment]
Well quite honestly, I'd expected people to just build this thing on the ground, rather than in the air.^^
It does not need natural stone or anything, I just needs some surface below it. It will then dig a little trench and produce ores from there.

**Comment by Skyqula** [comment]
Well, I looked at it like a MFR laser drill. Considering the book mentions the engine first I found it more convenient to build it up higher as the bucket will goes higher/lower from it. From a realism point of view I should have build it on the ground though xD

Either way, its working. So is LodeLoader, its so much better balanced then a laser drill/quarry, I like it. Also gives a reason to go out in the world and build a rail network.

**Comment by BluSunrize** [comment]
Glad you like it :D

**Comment by Hund** [comment]
I cant get it to work. I have built ground around it and it still doesnt output anything?

**Comment by BluSunrize** [comment]
Pictures.

**Comment by Hund** [comment]
https://imgur.com/7ljDHmS

**Comment by BluSunrize** [comment]
How much power is it getting, is it in a chunk with minerals, etc.?

**Comment by Hund** [comment]
I'm running a dieselgenerator. But I tried with a creative cell from TE just to rule that part out to.
It's just a vanilla biome. I have done some manual mining here myself so I know for a fact there is ores here. :)

**Comment by BluSunrize** [comment]
No, you don't. You use the core sample drill to see if there's a mineral in the chunk.
Mineral != Ore >-<

**Comment by Hund** [comment]
Hm. Didnt know about that thing. It told me there's no ore here?

**Comment by Hund** [comment]
So.. Whats the point with the Excavator? :P

**Comment by BluSunrize** [comment]
Read the book for goodness sake. When you put it in a chunk with minerals it generates ore >_<

**Comment by Hund** [comment]
I read the book. I read all the pages about the Excavator, dieselgenerator, industrial squeezer etc. It didnt say a word about a Core sample drill or how the Excavator really worked. Some dev said it generates ores from nothing. So I asumed it worked just like a Laser drill from MFR.

**Comment by BluSunrize** [comment]
http://puu.sh/j2RAH/cea28a1d38.png
There.
And when you click on minerals you'll find this on page 2:
http://puu.sh/j2RCt/032107931a.png
