### ISSUE TITLE
[1.10.2] Creosote oil issues

### ISSUE THREAD

**Issue by GenTex** [BluSunrize/ImmersiveEngineering#1880]
Railcraft - 1.10.2 - 10.0.1
IE - 0.10-55
Optifine - 1.10.2_HD_U_D4

I have checked previous reports of the issue, but mostly all of them are prior to a few releases of both Railcraft and IE. 

I am not sure which of the mods is at issue here as we had Railcraft first and because we could not make Creosote oil, we decided to install IE in order to generate it. 

The issues are the following:
1. We can't fill the buckets or bottles in the coke oven or from any type of container
2. The oil does not have a texture
3. Even if I use the bottler, I am not able to fill the bottles

I have tried to play without Optifine in the hopes that maybe the texture is fixed, that did not help.
Also, the only way to create Treated Wood planks is to spawn in the "Creosote Oil Bucket" and then use it on the crafting table. 

I am not going to mention the other bugs with the mod, such as: pipes not able to extract the oil from the furnace, weird render issue of the pipes when facing a specific way, dupping of the bottles when using the bottler, etc. as these have been previously mentioned and I believe these will be fixed in the upcoming patch.

Please let me know if I am doing something wrong or if I missed something. 

![1](https://cloud.githubusercontent.com/assets/25464646/22482204/e26b165e-e7ef-11e6-8d39-9cb9a524c1d9.png)
![2](https://cloud.githubusercontent.com/assets/25464646/22482208/e2757180-e7ef-11e6-857d-cda074beb4f4.png)
![3](https://cloud.githubusercontent.com/assets/25464646/22482205/e26d0978-e7ef-11e6-8431-99a07f8e9e91.png)
![bottle not working](https://cloud.githubusercontent.com/assets/25464646/22482207/e272942e-e7ef-11e6-9f70-22fb68a04e1f.png)
![bottler is not filling up the bottles](https://cloud.githubusercontent.com/assets/25464646/22482206/e27262ce-e7ef-11e6-90c6-48c729997c12.png)
![bucket not working](https://cloud.githubusercontent.com/assets/25464646/22482210/e27a59e8-e7ef-11e6-9ac8-a507ef522b48.png)
![crafting](https://cloud.githubusercontent.com/assets/25464646/22482211/e2916caa-e7ef-11e6-914a-8fea54672454.png)
![no texture and plenty to fill 3 buckets](https://cloud.githubusercontent.com/assets/25464646/22482212/e29044d8-e7ef-11e6-8d5a-c3de01797964.png)

**Comment by BluSunrize** [comment]
That looks like an invalid fluid for creosote oil. Can you reproduce this without railcraft?

Also regarding the other issues:
1) Pipes don't extract, pumps do
2) I have yet to successfully reproduce that
3) It's fixed, just not pushed.

**Comment by GenTex** [comment]
I have just tested the mod again by removing RailCraft and the creosote oil was fixed. I am not sure which of the two mods is actually making the issue as when I test them in separate instances, both work fine as standalone. But once I add the other one, the issue is back. Is there a way to load the mods in a specific way just like Skyrim/Fallout4 require to have a specific order? I would like to test if loading one mod before the other could make a difference.

As for the other bugs, I have tested a bit more the mod without rail craft and I have the following:
1. I am aware that the pipes can't suck the creosote oil, so I have used a pump. Unfortunately it doesn't pump out the oil from the furnace. The only way I managed to take it out was to use Fluid Conduits from EnderIO and to pump the oil from the furnaces in the IE pipes (see bellow)

![2017-01-31_21 30 51](https://cloud.githubusercontent.com/assets/25464646/22486261/b5939f3c-e800-11e6-9fc8-6779f6f1d5b6.png)
![2017-01-31_21 35 47](https://cloud.githubusercontent.com/assets/25464646/22486262/b59a415c-e800-11e6-90ac-e8212eb03c79.png)


2. I believe the weird render issues may be a result of some kind of weird interactions with RailCraft. I have tried to reproduce it again as without RailCraft and I could not do it at all. (I am not 100% sure if it's because of RailCraft or because I wasn't that lucky this time)

**Comment by GenTex** [comment]
Just a quick update regarding the issue with the creosote oil.

I have disabled the creosote fluid from the RailCraft mod and now the oil from IE is working properly for now. I can't fully integrate it in RailCraft but will work for now. Now I don't have the texture issue and I can use the buckets in the furnace, fill up the bottles and the buckets with the oil and so on.

It's not the best fix, but a temporary one until the solution can be found. 

Also, just as an additional note, the oil from RC is different from the oil from IE, at least as texture (see bellow)
![2017-01-31_23 15 36](https://cloud.githubusercontent.com/assets/25464646/22488800/fd4e2bc0-e80b-11e6-99c0-d64b0ef72926.png)
![2017-01-31_23 15 44](https://cloud.githubusercontent.com/assets/25464646/22488799/fd48fec0-e80b-11e6-9caf-f56d3bbefceb.png)

**Comment by BluSunrize** [comment]
Pumps do /not/ draw from a distance. Dunno why people constantly think they do, the book says nothing of that.
Put the pump directly next to the oven and it'll work.

And yeah, I dunno what Railcraft does with their oil, tbh...
I'll see if I can have a peak inside Covert's sources

**Comment by BluSunrize** [comment]
I can't even properly reproduce this. The fluids exist peacefully in my dev-environment .-.

[Image](http://puu.sh/tJrxf/a7483f6eee.jpg)

**Comment by KnightMiner** [comment]
It is worth mentioning that on world startup Forge chooses a fluid to be the default when two have the same name. There is a chance this error only happens if railcraft's oil is chosen, which you might be able to force by installing just railcraft then reopening the world with railcraft and IE.

**Comment by GenTex** [comment]
I am not sure why we have this issue. As stated before, we initially
started the server only with railcraft installed however because of the
lack of some important items, we decided to add IE. (about 100hours in our
play)

I will post the list of mods that we are using once I get home. Maybe there
is something else that is creating the issue.

**Comment by enricotagliavini** [comment]
I can also confirm the issue and my world was created with Railcraft, without IE. IE was added later on. Disabling Railcraft's fluid works as a workaround for me as well.

**Comment by swehunter2000** [comment]
I can confirm the issue in Direwolf20 1.10 pack (Version 1.5.1 Release)

I fixed it on my server using a MineTweaker script.

`val BucketFilled = <forge:bucketFilled>;
val CreoBucket = BucketFilled.withTag({FluidName:"creosote", Amount:1000});

recipes.addShaped(<railcraft:tie>,
 [[null, CreoBucket, null],
  [<ore:slabWood>, <ore:slabWood>, <ore:slabWood>]]);
  
  recipes.addShaped(<railcraft:tie>,
 [[null, CreoBucket, null],
  [<ore:slabWood>, <ore:slabWood>, <ore:slabWood>]]);`

**Comment by Telknor** [comment]
I fixed this issue by just setting the creosote=false in railcraft.cfg  This fixed the oil issue for both railcraft and industrialcraft 2's universal fluid cell when using immersive engineering.

**Comment by BluSunrize** [comment]
Suspected to be a Forge issue anyway. Closed.

**Comment by ericcotelnu** [comment]
It is a forge issue, as when I hover over a bucket of it in JEI, the mod says "Minecraft Forge". They'll need to fix it on their end. Helpful this bug report exists, as I'm getting this issue myself (and came about the temp fix on my own with the railcraft.cfg edit).

**Comment by ericcotelnu** [comment]
(Sorry somehow I can't edit my last in this silly browser) - I disabled everywhere now, seems it wasn't enough to just edit railcraft.cfg.

**Comment by ericcotelnu** [comment]
file:///home/eric/Dropbox/Pictures/Screenshot_20170619_231216.png

**Comment by ericcotelnu** [comment]
![screenshot_20170619_231216](https://user-images.githubusercontent.com/68096/27315034-483987a0-5545-11e7-9464-05f8db5c14d7.png)

Thought you might want to see the NBT data part, it says null. WTH?

**Comment by ericcotelnu** [comment]
FYI, I was able to resolve my own issue by fixing the level.dat file - it had a bogus entry for creosote: it was thermalfoundation:creosote changed it to immersiveengineering:creosote . Not recommended for newbies. Had to go into the fluid registry.

**Comment by janagyjr** [comment]
Just got a report about this on a server I help admin, thanks for all the useful information guys. Saved us some big headaches down the road.

**Comment by Ravalli03** [comment]
I'm having trouble finding the fluid registry to change it.  The modpack i'm playing has stuff gated by treated wood.  Any help would be great

**Comment by Natrukei** [comment]
But that bug just can't only stick with railcraft. I have the same issue (only difference: The texture is fully pink and not pink-black) while never even having railcraft installed in the modpack!

And in the level.dat there is only immersiveengineering:creosote

**Comment by Ravalli03** [comment]
Then you have thermal mods installed, change it to thermalfoundation:creosote and will fix it

**Comment by ottmiche** [comment]
I had the problem that Forge was overwriting creosote oil, which resulted in a conflict between the Forge oil and the IE oil
Solved by deleting immersiveengineering:creosote in the fluid list in the level.dat file
