### ISSUE TITLE
Random DW20 Server crashing (not sure it's an IE issue)

### ISSUE THREAD

**Issue by OldDogy** [BluSunrize/ImmersiveEngineering#1883]
CrashLog:
http://pastebin.com/Kg0xaa8c

Not sure the issue is Immersive Engineering, it was the first thing in the crash. But I need help.
This is not the first time this has happen, I don't know how or why it starts happening, but last time i restarted the world cause I couldn't figure it out.

Basically if any player joins the server the server crashes with this error, doesn't matter where the player is located. On the last server there was no sponge included, on this one there is sponge. but i don't believe that is the issue since the server was running just fine for weeks.

Any help, or a pointer to what i should do would be much appreciated !

**Comment by BluSunrize** [comment]
Update IE.
