### ISSUE TITLE
I can't seem to get the squeezer working 

### ISSUE THREAD

**Issue by feralxmad** [BluSunrize/ImmersiveEngineering#1884]
I  have a pic of the squeezer and I can't seem to get it to turn into the multi block someone help 
https://imgur.com/gallery/IXaBB
Here is the link to my set up

**Comment by BluSunrize** [comment]
Did you rightclick the barrel in the middle with the hammer?

**Comment by feralxmad** [comment]
Yes I have  right clicked the barrel nothing,I've tried too look on YouTube and good for refrences on how to build the squeezer but I found nout

**Comment by feralxmad** [comment]
Do you have any ideas or could you join my server and show me

**Comment by BluSunrize** [comment]
I generally don't join servers for that, no.
We'll need more pictures, of all three layers. Also please actually take screenshots this time instead of using your phone.

**Comment by feralxmad** [comment]
![image](https://cloud.githubusercontent.com/assets/25554765/22621726/4cad41b0-eb22-11e6-8e31-77f4388f59af.png)

**Comment by feralxmad** [comment]
![image](https://cloud.githubusercontent.com/assets/25554765/22621730/5ef56816-eb22-11e6-99d4-a231c30b2e20.png)

**Comment by feralxmad** [comment]
![image](https://cloud.githubusercontent.com/assets/25554765/22621735/738bf8a8-eb22-11e6-85b5-5a44fd55c630.png)

**Comment by feralxmad** [comment]
![image](https://cloud.githubusercontent.com/assets/25554765/22621741/8bcbfd64-eb22-11e6-9675-e79cc3d46179.png)

**Comment by feralxmad** [comment]
![image](https://cloud.githubusercontent.com/assets/25554765/22621744/a51d5312-eb22-11e6-97aa-08be58be05a5.png)

**Comment by feralxmad** [comment]
![image](https://cloud.githubusercontent.com/assets/25554765/22621750/b9539828-eb22-11e6-9fcf-1ba9462b70b0.png)

**Comment by feralxmad** [comment]
![image](https://cloud.githubusercontent.com/assets/25554765/22621757/e0a307a6-eb22-11e6-9640-03e18d4899df.png)

**Comment by feralxmad** [comment]
there are all 3 of the stages,

**Comment by BluSunrize** [comment]
and then you rightlick the middle barrel on the side between redstone and light engineering block.

(also, unrelated, but be careful with the pictures you upload. Some stuff in the background you probably don't want people to see ;) )

**Comment by feralxmad** [comment]
Thank you so much for your help (: (and I had to delete a few time I uploaded the pics lol

**Comment by TehStoneMan** [comment]
You might find it easier to use the in-game screenshot function - F2

**Comment by AEnterprise** [comment]
just for reference: another handy way of making screenshots on windows in the build in 'snipping tool' program, can do fullscreen or rectangular area

**Comment by BluSunrize** [comment]
I'll close this then, if it's resolved.
