### ISSUE TITLE
Conveyor belts arent conveyor belts after getting from Project E tablet

### ISSUE THREAD

**Issue by darkrage000** [BluSunrize/ImmersiveEngineering#1888]
Conveyor belts are no longer usable and give a purple/black render image when you get them from a tablet from Project E as well as from a energy condenser

I also notice that the entity name of the new object is title.immersiveengineering.conveyor..name
please note the double decimal at the 'name' part.

Version 0.10-55
Modpack SkyExchange

**Comment by BluSunrize** [comment]
ProjectE replicates items without NBT data. Nothing I can do about it.
