### ISSUE TITLE
Russian translation ImmersiveEngineering 0.10-55

### ISSUE THREAD

**Issue by lex1975** [BluSunrize/ImmersiveEngineering#1889]
I translated most of your mod into Russian. Not translated tooltips for shaders.
[IE_0.55_ru_RU.zip](https://github.com/BluSunrize/ImmersiveEngineering/files/758152/IE_0.55_ru_RU.zip)

**Comment by BluSunrize** [comment]
please submit a pullrequest, that is far easier than manually adding the file and stuff and allows proper crediting, as well as input by other contributors.

**Comment by lex1975** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/compare/master...lex1975:patch-1?expand=1
I'm not good at programming and design on this site. Well I know Russian, but English is bad.

**Comment by BluSunrize** [comment]
merged.
