### ISSUE TITLE
Question: Fluid transport?

### ISSUE THREAD

**Issue by Voxel-Friend** [BluSunrize/ImmersiveEngineering#189]
Since there is no native duct/pipe/tube/etc. to transport the fluids added by IE, It is hard to  create a succinct personal modpack. Is this currently a planned feature? I do not want to have to get ExU just for transfer nodes, Buildcraft Is a option but again, I'd only be adding it for the pipes, and I'd rather not. TD is a thought, but it requires thermal foundation which would add multiple ores and I'd rather not gum up my world with a bunch of ore that would only have 1-2 uses. any thoughts on this? Thanks.

P.S. For the record, I do enjoy mods like BC, ExU, TD, and EIO... they just don't fit with want I currently want for this current instance I'm planning.

**Comment by porteriscool** [comment]
You don't need pipes, you can manually insert buckets into the structures that have liquids that output, and receive a buckets worth of that liquid that you just pulled out, and you can then dump the fluids into their respective structures manually as well.

**Comment by Voxel-Friend** [comment]
Would be kinda annoying having to stop what I'm doing to manually transport each and ever bucket any time I'm running low... but it is an option I was not aware of. Still.

**Comment by mallrat208** [comment]
Yeah, at that point you'd be better off just adding BuildCraft. The newer
versions are modular so if you only want pipes, that's all you have to
install.

**Comment by tebruuls** [comment]
This is a good idea as this mod was meant to be able to be used stand-alone. There would also have to be more conveyor belts like extracting etc.

**Comment by BluSunrize** [comment]
Pro tip: Connected machines. The only fluid transport you would need is Biodiesel. Place the squeezer+fermenter against the sides of the refinery and the generator at its output, problem solved.
Alternatively, use ConveyorBelts and glass bottles.

Fluid transport is not planned for now, because its a pita to code.

**Comment by Voxel-Friend** [comment]
O.O Didn't realize that was a thing. Thanks Blu
