### ISSUE TITLE
Possible broken MineTweaker integration breaking Draconic Evolution JEI integration? 

### ISSUE THREAD

**Issue by brandon3055** [BluSunrize/ImmersiveEngineering#1890]
Ok so i'd like to start off by saying this is one of the weirdest bugs i have ever had the displeasure of debugging and i still have no idea what is actually going on or if IE is even the cause. Whats actually being broken is DE's JEI fusion recipe handler.

Here is what i know: 
This issue started in SkyFactory3 Some users reported that DE fusion recipes where others dont have this issue at all (First weird thing about this only seems to affect some installations/systems)

Some people have reported that removing ModTweaker when running on the curse launcher fixes it (I cant test this because the curse launcher does not agree with my internet) I tested this on the legacy launcher and found that removing ModTweaker does not help and nether did removing Minetweaker ether.  
I then transferred the entire pack to MultiMC for further testing and found that doing so made the issue go away. (Second wierd thing this seems to somehow be affected by the launcher used) 

I did manage to get this issue to show up in MMC by enabling the following mods:
BrandonsCore-1.10.2-2.1.3.82-universal
ChickenChunks-1.10.2-2.2.0.52-universal
ClientTweaks_1.10.2-1.1.16
CodeChickenCore-1.10.2-2.4.0.101-universal
CodeChickenLib-1.10.2-2.5.2.198-universal
CraftTweaker-1.10.2-3.0.17
Draconic-Evolution-1.10.2-2.0.7.168-universal
ImmersiveEngineering-0.10-55 or 56
jei_1.10.2-3.14.3.403
ModTweaker2-2.0.9
MTLib-1.0.1

Im not sure how Chicken chunks could be related to this as it does not even have a JEI plugin.
Downgrading IE to 54 fixes the issue.

If you can make any sense of that then your doing better then i am because i dont have a clue. And as with all good bugs i could no recreate this in dev. 
As i said i dont even know if this is your fault but IE seems to atleast have something todo with this.

**Comment by BluSunrize** [comment]
Should be fixed. Release due today.
