### ISSUE TITLE
[Bug] Crusher texture scaled wrong when using Optifine

### ISSUE THREAD

**Issue by ElKameleon** [BluSunrize/ImmersiveEngineering#1893]
Minecraft 1.10.2 IE-55

When optifine is enabled, the crushers textures are scaled at a 2x factor. Tried on multiple worlds/installations, issue is resolved when optifine is disabled. This is the only multiblock structure that i've used where i'v seen this behavior.

**Comment by ArukaAlter** [comment]
Optifine does mess somethings with rendering, but this graphical bug is not always reproduceable.

**Comment by ElKameleon** [comment]
I can gladly provide reproducible evidence when I'm near my computer with Minecraft installed. This also affects my girlfriends instance which uses radically different hardware. My assumption is there is something slightly different about that model that's causing the issue. It's not game-breaking by any means, just ugly.

**Comment by ArukaAlter** [comment]
We know how the models behave when it happens, but Blu doesn't support Optifine, and the issue randomly goes away from time to time.
