### ISSUE TITLE
About bucket wheel excavator

### ISSUE THREAD

**Issue by forestbat** [BluSunrize/ImmersiveEngineering#1896]
The edition of IE which I play is 0.10.55，when I am using the bucket wheel excavator，bucket wheel rotated，but there is no mine in the bucket wheel，and I put some dirt under the bucket wheel。
What happened？

**Comment by forestbat** [comment]
The whole machine is in the same chunk，and the chunk has a coal mineral vein。

**Comment by BluSunrize** [comment]
Sorry for responding to this so late.
I'd need to see some pictures of the setup, if the issue still persists.

**Comment by mindforger** [comment]
@BluSunrize i had this issue too, there was a tiny cave below the excavator and it stopped until i closed up the cavity beneath the wheel ... would it be possible to add an chat message when right cklicking the excavator telling your things like "operating", "no power", "cavity breach" ... or something like that to help out with such issues?
