### ISSUE TITLE
Description: Registering texture

### ISSUE THREAD

**Issue by Marekone** [BluSunrize/ImmersiveEngineering#1897]
crash report: [http://pastebin.com/ZbfJKqC6](url)

it seems to be a texture conflict between IE and another mod.

**Comment by XFactHD** [comment]
I doubt this has anything to do with IE, please report this to SGCraft.

**Comment by Marekone** [comment]
thanks! that helped me a lot! I just updated SG Craft to the newest version and everything works fine!
