### ISSUE TITLE
[1.7.10] Graphic Bug - Bottling Machine - Added Galacticraft Oxygen Tank via Minetweaker

### ISSUE THREAD

**Issue by nidico100** [BluSunrize/ImmersiveEngineering#1898]
Graphic bug, when you add Oxygen Tanks from galacticraft to bottling machine via minetweaker.
The Tank is ways bigger than before when in the machine. Functionality is given, but doesn't look that fancy.
http://imgur.com/NGluekh

**Comment by ArukaAlter** [comment]
1.7 is no longer supported.
