### ISSUE TITLE
[0.10-55] Redstone wires dont carry signals over relays

### ISSUE THREAD

**Issue by Paul17041993** [BluSunrize/ImmersiveEngineering#1899]
Redstone wires don't carry any signals over HV relays despite being connectable to them, so the only way to relay the wires is with multiple red wire connectors.

**Comment by BluSunrize** [comment]
Well, tbh, HV relays shouldn't even accept those wires. They were supposed to use RS connectors only.
However, you bring up an excellent point, I should add specific relays for them, so that not every point is an in- or output.

**Comment by BluSunrize** [comment]
Relays don't take those wires anymore, closing this.
