### ISSUE TITLE
Explosive round propels me to point of impact 

### ISSUE THREAD

**Issue by TheQuadShot** [BluSunrize/ImmersiveEngineering#190]
http://youtu.be/eTlcSjkpoBU
The Dragon rounds and buckshot do as well

**Comment by BluSunrize** [comment]
All rounds do, long since fixed, check the closed issues.

**Comment by TheQuadShot** [comment]
I checked all issues not just "is:issue is:open" my search was "is:issue dragon, is:issue explosive, is:issue round" the search results were 0.. The only search that got a hit was "is:issue buckshot" and was bug #8. Try it for yourself... If I had seen it I wouldn't have filed it. I do it for EVERY bug I file
