### ISSUE TITLE
Multiblock intergration with The One Probe

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [BluSunrize/ImmersiveEngineering#1900]
The One Probe does not correctly show/detect multiblocks names
![2017-02-17_12 38 15](https://cloud.githubusercontent.com/assets/21071450/23062349/1674ff7a-f50e-11e6-91db-6023a54d8492.png)

Using the DireWolf20 pack version 1.4.1;
Immersive Engineering version 0.10-54
WAILA version 1.7.0-B3
The One Probe Version 1.3.3
mcjty lib version 2.3.4
Compat layer 0.1.7

**Comment by BluSunrize** [comment]
Pretty sure that used to work fine too, but I haven't kept up with One Probe at all, since I don't use the mod myself. I'll look into this, thanks for the report.
