### ISSUE TITLE
[0.10-56] CraftTweaker recipes for the Bottling Machine not consuming liquid, no matter what

### ISSUE THREAD

**Issue by starg09** [BluSunrize/ImmersiveEngineering#1901]
It seems to detect the required amount ok, but won't consume the liquid after processing the inserted item. As an example, the line:

`mods.immersiveengineering.BottlingMachine.addRecipe(<extrautils2:wateringcan:0>, <extrautils2:wateringcan:1000>, <liquid:water> * 4000);`

takes an empty watering can from ExU2, along with 4 buckets of water, and fills it again. It won't fill until 4000mB are inserted into the machine, but once that's there it'll fill all the cans you want, never consuming the liquid.

"Vanilla" recipes (empty bottle + 1000mB of water) seem to work properly.

Tested with IE 0.10-56, ExU2 1.3.0 and Forge 2221.

**Comment by malte0811** [comment]
Happens in my dev environment as well (unless I am doing something wrong again), I'll take a look at the code now.

**Comment by malte0811** [comment]
This is fixed, I did find a dupe bug though (more specifically, a n->n*(n+1)/2 bug) which I will fix now.

**Comment by starg09** [comment]
Great, thank you! :)
