### ISSUE TITLE
[1.10.2] Graphics Bug - IE Wooden Post & Tank models flicker and disappear

### ISSUE THREAD

**Issue by PorkchopFu** [BluSunrize/ImmersiveEngineering#1904]
The wooden post and tank models (after placing in the world) tend to disappear and flicker from time to time. The wooden post does this every time I look at it at close range and the tank does it at moderate distance but more occasionally. The tank will also sometimes stop rendering the fill bar and retain only a gray background for the fill window, and will render correctly after I leave the chunk and revisit it.

**Comment by BluSunrize** [comment]
Could you please produce a debug crash? To do so, hold F3+C for 10 seconds.
Put the crashlog on pastebin or gist and then link it here.

**Comment by PorkchopFu** [comment]
Thanks for the help. The crash report link is below.

http://pastebin.com/Zxzj0P88

**Comment by malte0811** [comment]
Optifine is not supported. Does this issue happen without it?

**Comment by PorkchopFu** [comment]
Ahh. I haven't tried it without OptiFine, but I'll check in the morning. OptiFine really gives me the features that I need, so if it is the cause, I think I'll just have to deal with it. Do you have any plans to support OptiFine in the future? Also, if you don't mind me asking, what about the OptiFine code/architecture is causing you to not support it? Thanks.

**Comment by malte0811** [comment]
I don't think there are plans to support it in the future. The problem about Optifine is that it modifies a lot of MC's rendering code without being open source, so we don't know what it modifies (BTW, does anyone know which law applies if I, living in Germany, decompile Optifine (don't know where the author lives)? I think I would be allowed to decompile OF by German law to ensure "Interoperatibilität" with IE...). Another problem is that Optifine has no deobf-builds, which means that we can't just install it in a normal development environment (at least that is what it used to be like, I don't know whether 1.10 changed anything there. I'll have to try it).

**Comment by malte0811** [comment]
I just tried to reproduce this bug with OF installed and wasn't able to get the models to flicker (lighting was broken though). I had another look at your mod list, could you try removing the XRay mod you have installed (Fgt X-Ray).

**Comment by mindforger** [comment]
„Another problem is that Optifine has no deobf-builds“ the dev told me you can deobf it yourself in one of the issues regarding IE. Also the how to, but I am not on my pc, I can not look it up yet

**Comment by malte0811** [comment]
I remembered that as well, simpledeobf is the term you want to search for. I got it partially working, I'll try again later.

**Comment by malte0811** [comment]
So I just got Optifine working in my dev environment. simpledeobf is nice, but a bit unstable. This doesn't help me for this issue since I can't replicate it anyways, but might be usefull in the future.

**Comment by PorkchopFu** [comment]
I'll try removing xray, but I'm almost 100% sure that it was flickering before I added it. I just added it to debug ore generation for the unfinished Railcraft for 1.10.2.

**Comment by PorkchopFu** [comment]
Oddly enough, I haven't seen the tanks flicker since I opened this ticket, but I have seen the status bar go grey, and the posts still go invisible on me. I really wish OF would provide clear documentation to open compatibility with the modding community, as doing so would expand their client base and make everyone happier.

**Comment by mindforger** [comment]
@malte0811 @PorkchopFu you should exchange the settings of optifine, it is HIGHLY depending on the config on how optifine behaves! I am now almost certain that @PorkchopFu uses multi-thread chunkloading, this is prone to flickering stuff

**Comment by PorkchopFu** [comment]
I am running "OptiFine 1.10.2 HD U D6" and do not have an option for 'multi-core chunkloading' under 'options>video settings>performance', only 'lazy chunkloading' which is currently set to "OFF" and cannot be toggled.

@mindforger , do you have a suggestion for how to disable multi-core chunkloading in my version of optifine? Thanks.

**Comment by mindforger** [comment]
i just read it's not available for every user, depends on the system, sorry :P
