### ISSUE TITLE
Crash when using railgun

### ISSUE THREAD

**Issue by nicro950** [BluSunrize/ImmersiveEngineering#1906]
We got a client crash on the target of a railgun using steel rods on the skyfactory 3 modpack on a private server. Here is the crash report:
[crash-2017-02-19_14.49.03-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/785890/crash-2017-02-19_14.49.03-client.txt)
 the crash report

**Comment by malte0811** [comment]
Try updating Immersive Engineering and Draconic Evolution.

**Comment by nicro950** [comment]
I am going to try that

**Comment by BluSunrize** [comment]
No further replies, issue closed
