### ISSUE TITLE
[suggestion] map for core samples

### ISSUE THREAD

**Issue by Terpo** [BluSunrize/ImmersiveEngineering#1908]
I would really enjoy to have an item that can store the information of core samples. Something like a map where you can insert a sample. The sample information could show up as colorized chunk or something. And when you mouse over the chunk it will give you the latest stored sample information like the timestamp, the vein and left blocks.

I did something with Journeymap last time but it was a bit of a pain.
![minerals](https://cloud.githubusercontent.com/assets/4256058/23126810/c88e2c88-f778-11e6-9416-6af4071c9087.png)

**Comment by BluSunrize** [comment]
Sorta a thing now. With the next release, Core Samples can be placed in the world and rightclicked with a vanilla map to add a marker.
