### ISSUE TITLE
Broken rendering on multiblock pages in the manual

### ISSUE THREAD

**Issue by Serifina** [BluSunrize/ImmersiveEngineering#1909]
Rendering for blocks, primarily engineering blocks, is broken in the manual, showing the purple/black texture. The blocks render properly in-world however. The formed multiblocks do show correctly in the manual and in-world. Also, the blocks broken in the multiblock render show properly on the pages where their crafting recipe is shown.

![2017-02-20_17 58 12](https://cloud.githubusercontent.com/assets/8071736/23144585/85da98fe-f796-11e6-83f9-eb92f6bae8dd.png)

Full modlist [here](http://pastebin.com/M4wpLZ0Q). I've tried without FoamFix as well, just in case. As far as I know none of the other mods should affect rendering in the book but I could be wrong.

**Comment by BluSunrize** [comment]
Can you please produce a debug crash by holding F3+C for 10 seconds and then provide that log here?

**Comment by Serifina** [comment]
[crash-2017-02-21_09.43.28-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/790442/crash-2017-02-21_09.43.28-client.txt)

**Comment by BluSunrize** [comment]
Can you try removing Chameleon and the mods that depend on it?

**Comment by Serifina** [comment]
Removed Chameleon, Storage Drawers, and Drawers & Bits. Same result, unfortunately.

**Comment by BluSunrize** [comment]
I find myself completely unable to replicate this though. Try removing chisel, otherwise I'd say attempt a binary search.
I'm pretty sure this is crossmod related...

**Comment by Serifina** [comment]
You were right, it is Chisel causing it to happen. I guess I'll go report this on that github, then.

**Comment by BluSunrize** [comment]
yeah that was the next thing I was gonna mention: You might be running an outdated chisel =P

I'll close this then, glad it's fixed.
