### ISSUE TITLE
Water wheel - kinetic dynano = 0 power

### ISSUE THREAD

**Issue by Dustmuz** [BluSunrize/ImmersiveEngineering#191]
i have a waterwheel setup with 3 wheels, and a kinetic dynamo on one side..
no matter how i turn the dynano, it will not generate any kind of power.
i have tried placing TE cells on all sides but the one where the wheel is, and none of them gets any power, dispite the wheels are turning.
it doenst matter which way i turn the wheels either..

Is it me that have done something wrong??

as a side note.. shouldnt the wheels be turning all the time??, or is it intentional that they halt after a few seconds, and then go again a few seconds later?
Versions:
Forge - 10.13.4.1481
MC - 1.7.10
IE - 0.3.3

**Comment by Dustmuz** [comment]
made the exact same setup as above (in a creative world) 
and there it worked..

Survival does not generate power
Creative does

**Comment by BluSunrize** [comment]
BS, worldmode has nothing to do with it.
Very likely to be a user error.

**Comment by Dustmuz** [comment]
this is actually not BS..
belive it or not..

i'll gladly make you a video of both setups

**Comment by BluSunrize** [comment]
The world mode cannot have anything  to do with it. Trust me, I know what I have written. And it works for everyone else after all
