### ISSUE TITLE
Feature request; Wire connector reverse mode.

### ISSUE THREAD

**Issue by Paul17041993** [BluSunrize/ImmersiveEngineering#1912]
In my current world I've been using HV lines for all external lines, simply because they look nice and are super convenient compared to running physical cables everywhere. However, while mekanism (and other RF cables) can inject power directly into the wire connectors due to their internal buffers, the connectors don't automatically inject available power into other cables (a good design choice actually, prevents the RF cable nonsense that COFH conduits have), nor is there a way for the other cables to pull out of them as they don't fill their own buffers or have an out buffer.

My request is that we can whack a connector with the hammer and switch it to "reverse mode", which basically instead of transmitting its buffer to accepting connectors it will become an accepting connector and charge its internal buffer, allowing cables to pull out of said buffer. Optionally you could allow reversed connectors to be seen as a power source so mekanism cables for example wont need to be switched to pull mode.

Attaching two images of a melon farm that makes use of the HV wires, I use HV capacitors for each line simply to transmit the power to the main line in the house (think of it as a insulated twisted cable, like those used on poles connecting to underground cables);
<img width="492" alt="screenshot_37" src="https://cloud.githubusercontent.com/assets/3912867/23296213/2c05988a-fac8-11e6-80f4-6f1bdee1094d.png">
<img width="535" alt="screenshot_38" src="https://cloud.githubusercontent.com/assets/3912867/23296215/2fbf3576-fac8-11e6-9c09-d73d0d69a53e.png">
Two lines of universal cable are on the capacitors simply because they only pull at half rate for some reason (640EU/t), if I use the ultimate cables then only the one line is needed (2,560EU/t).

**Comment by BluSunrize** [comment]
The simple reason that this is not a thing is the fact that RF is a push based system. You generally do not 'draw' power for it, an all machines are desiged to accept energy pushed into them, not to withdraw it from connected cables. All generators for IF, RF or FU are generally designed to push all the power they are creating out, and machines will accept power as long as they are not full.
I don't even know why Mekanism has a "pull"-mode for its wires, tbh.

From what I understand, your use-case for this is: Mekanism cables should draw from IE connectors, right?
Well, Mekanism cables should really allow power being inserted into them...

**Comment by Paul17041993** [comment]
In 1.7.10 the RF API was push-pull, you had the option for either method in your code, did they change this in 1.10?

All you need to do is change the connector to be treated as a RF source when in reverse mode, the external cables can then just drain from connector's buffer like they do with other power sources.

I will also note as well that the IE capacitors will not push RF to universal cables without setting the cables to pull mode, so I'm going to be checking the code for both IE and mekansim to make sure they're implemented correctly (I know enderIO definitely isn't...).

**Comment by BluSunrize** [comment]
Yeah I'd definitely believe that to be on Mek's side. IE connectors will always try to push out, and they are perfectly capable of pushing into anything that is willing to accept them .-.

**Comment by Paul17041993** [comment]
A problem arises however if a connector is attached to a two-directional block or cable, you'll end up with the RF flowing both ways down the line and applying a loss that shouldn't be there.

A simple reverse mode (fill the connector's buffer instead of drain it) helps solve this problem and eliminates the need of a buffer capacitor or similar block for compatibility with certain mods.

No idea about mekanism currently as its code is very fragmented and @aidancbrady looks to have disappeared...
