### ISSUE TITLE
[1.10.2] [0.10-56] JEI Recipe Issue.

### ISSUE THREAD

**Issue by TheBritishBrotherhood** [BluSunrize/ImmersiveEngineering#1913]
Hello.

Im not sure if this is a fault of yours or JEI's but there are no recipes showing for machines.

Coal coke, steel etc doesn't show the recipes within the blast furnace and coke oven etc.

JEI version: JEI_1.10.2-3.14.6.412

**Comment by BluSunrize** [comment]
Have been unable to reproduce this so far. Can you try with just IE and JEI? If it works then, it's probably a cross-mod issue.
