### ISSUE TITLE
[suggested] Small tweak to a few machine rates

### ISSUE THREAD

**Issue by laxboy119** [BluSunrize/ImmersiveEngineering#1914]
I have been playing around with a world focused on IE, and one problem I have is that when you feed fermenters and squeezers from a silo ran by a redstone signal to conveyors, the silo outputs slightly faster than the machines process items, leading to spillage and the waste of items/ a ton of items stuck on the belts

I would suggest either slightly slowing the silo down or speeding up the machines just a hair so that they run at the same speeds, otherwise i have to throw in an anti overfill mechanism that really ruins the look of the factory

**Comment by BluSunrize** [comment]
Well, the config features adjustable speed for the Squeezer...

**Comment by laxboy119** [comment]
It would just make more sense as a stock setting. As it stands it doesn't make much sense that when you are using only IE for your fuel production that it doesn't work very nicely, especially when to keep up with it you have to babysit it and turn the silo on and off. A timer could be used, but then you have to incorporate a timer into your build and it starts looking ugly...


Anyway thanks for responding love the mod and my factory looks amazing because of it
