### ISSUE TITLE
Coke oven rendering issue

### ISSUE THREAD

**Issue by Liiw** [BluSunrize/ImmersiveEngineering#1915]
Hello,

I have IE installed with numerous othe mods. 

Minecraft version 1.10.2. 
forge-1.10.2-12.18.3.2221

After building and clicking on the coke oven, I experienced rendering issue. Functionality does not seem to be affected. Although when I break the oven bricks, the "ghost" blocks occasionally drop granting me more brick blocks every time. Note that while I am playing with Optifine, I tried it without Optifine and still the following occured:

![image](https://cloud.githubusercontent.com/assets/14122419/23344486/084a777a-fc86-11e6-82f3-b4cff75c734d.png)

**Comment by BluSunrize** [comment]
After this render glitch occured, try placing any other block next to the coke oven.
Probably just a chunkupdate required.

Not much to be done to fix this. Happens when rendering is faster than Tiles syncing :/

**Comment by Liiw** [comment]
Hello again!

Unfortunately that did not remedy the issue. I even tried relogging into the server. I forgot to mention earlier that I am playing on a spongeforge server with betterFPS and foamfix (both mods also on client side). Could this be a mod conflict and if so, how could I trace this?

**Comment by malte0811** [comment]
Does this happen on a non-sponge server? SpongeForge belongs into the category "(K)Cauldron and similar server software" (in my oppinion) and is therefore not supported (see the [contributing guidelines](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/CONTRIBUTING.md#other-mods)).

**Comment by Liiw** [comment]
Hello once again,

I did some testing in a singleplayer world to see if this has something to do with the server. It probably does, because the coke ovens were looking like they should after activating them with the hammer (see image attached). Although, at the moment of activation, the bricks momentarily "lunged" at my direction a distance of one block. It looked similar to what I am experiencing on the server, but it was just for a split second. 

Maybe, on the server, the blocks are "getting stuck" in this "lunge" state and this is somehow causing the issue.  It might be spongeforge or some other mod which perhaps somehow affects client-server sync, I would not know. 

![image](https://cloud.githubusercontent.com/assets/14122419/23367161/f6e0d31c-fd11-11e6-82e9-ff502bc2d514.png)

Since this issue probably is not caused by IE, I am closing it. Thank you for your time and suggestions! If in the future, I manage to pinpoint the excact cause of this issue, I will report back.
