### ISSUE TITLE
Anti ID conflict Issue.

### ISSUE THREAD

**Issue by 63502** [BluSunrize/ImmersiveEngineering#1918]
Immersive Engineering potion effects seem to disagree with Anti ID conflict. AIDC repeatedly registers IE's potion effects as having conflicting ID's, even though I have made sure that they do not. I do not know if this problem is on IE's end or AIDC's, but I have a sneaking suspicion that it has something to do with the way that IE registers its potion id's automatically. IE does not have any way to stop the automatic registering of potion ids or any way to manually assign them in the config, so I am at a bit of a loss as to how to actually fix this.

I have made a comment on the Anti ID Conflict Curse page as well.

Immersive Engineering 0.10 - 57
AntiIdConflict-1.5-1.10

**Comment by 63502** [comment]
EDIT: This may be a bug that is not be on IE's end, but am going to leave this open just in case it isn't.

**Comment by XFactHD** [comment]
Why do you even need AntiIDConflict? Block and item IDs cannot collide anymore and in my opinion, if a mod lets the player choose the potion IDs the author is doing something wrong.

**Comment by 63502** [comment]
Ok first of all, Anti ID Conflict doesn't even deal with blocks and items in the first place. Specifically, it lists the ID's and ID conflicts for Mods themselves, biomes, dimensions, enchantments, and potions. All of these can still collide and cause problems (hence AIDC's existence). These types of conflicts are only fixed in 1.11.2 versions, hence the mod author stating that as of 1.11.2, AIDC is depreciated.

> Starting 1.11, forge forces mods to use registries for everything. Registries auto distribute ids, so AIC is now deprecated. -elix_x

Not having the option to assign potion and enchantment ID's manually is a real pain when conflicts happen, and since some game features are dependent on potion effects, conflicts can break gameplay completely.

**Comment by 63502** [comment]
EDIT: Just read a curse comment by elix_x about the exact bug I am talking about.

> Well, if you see one mod and it's conflicting, then your probably seeing something like this:
146: , immersiveengineering.smth.smth
See that sneaky comma? Yeah, that's a weird bug (in most cases with IE), which still can't fix. And sadly probably wont (1.10 being replaced by 1.11 and deprecation of AIC).

It is definitely a bug with AIDC, so issue closed. :(

**Comment by XFactHD** [comment]
"Not having the option to assign potion and enchantment ID's manually is a real pain when conflicts happen, and since some game are dependent on potion effects, conflicts can break gameplay completely."
That's why I said that mods should handle those IDs internal.

**Comment by BluSunrize** [comment]
Potion IDs aren't simple numbers in 1.10 either. They are proper ResourceLocations. There should be no conflict at this point.
