### ISSUE TITLE
potion bucket has missing texture

### ISSUE THREAD

**Issue by cleverpanda** [BluSunrize/ImmersiveEngineering#1919]
![image](https://cloud.githubusercontent.com/assets/2975515/23449612/f959da42-fe1c-11e6-9b5e-06920d6485cc.png)

**Comment by mindforger** [comment]
you are missing context, please post MC and Mod versions used and some backround informations
you could post a forced crashlog by pressing and holding F3 + C until it crashes

also check if this is reproducible without betterFPS/optifine or other optimizing mods

just by chance, did you create this world with only railcraft installed , adding IE to a later time?

**Comment by cleverpanda** [comment]
version 57, just released, newest forge, this is the only mod installed, new world

**Comment by BluSunrize** [comment]
Please still produce a debug crash as instructed.
Generally, saying "latest/newest version" is not acceptable, because when we look at the issue 3 days later it might be out of data already.
