### ISSUE TITLE
Infinite deposits not generating

### ISSUE THREAD

**Issue by Skyqula** [BluSunrize/ImmersiveEngineering#192]
In the config file is the following setting:

    # The maximum amount of yield one can get out of a chunk with the excavator. Set a number smaller than zero to make it infinite
    I:"Excavator: Mineral Depletion"=76800

So as the comment suggests, making the number smaller then zero should make it infinite, like for example -1. The result however is that no deposits generate, tested a 20x8 chunk area. Normally a 2x4 chunk area is enough to spot one.

**Comment by toric55** [comment]
@BluSunrize 
so does this mean that you can no longer make veins infinite? or does it simply fix the issue described. asking because getting very confused when IE regens the cfg and throws an error into the log when i set vein size to -1. the cfg still says that it should work.

**Comment by mindforger** [comment]
you may add the error messages and the full vein config line

**Comment by toric55** [comment]
# The maximum amount of yield one can get out of a chunk with the excavator. Set a number smaller than zero to make it infinite
    I:"Excavator: Mineral Depletion”=-1

[01:39:15] [Client thread/ERROR]: An exception occurred while loading config file ImmersiveEngineering.cfg. This file will be renamed to ImmersiveEngineering.cfg_20160805_013915.errored and a new config file will be generated.

not too mutch help, unfortunatly.

**Comment by BluSunrize** [comment]
@toric55 for one. Open a new issue, don't dig out one from friggin 2015.
Then: IE Version if you'd please. And that error does not say at all WHY it failed to load, is there more to this?

**Comment by toric55** [comment]
ok. was just making sure it was an error, and the functionality was still supposed to be there.
