### ISSUE TITLE
[Suggestion] New Razor Wire stacking

### ISSUE THREAD

**Issue by b0bst3r** [BluSunrize/ImmersiveEngineering#1924]
As it is now - http://i.imgur.com/rrbpkOx.png 

Any chance you can make the edges do the same as the wire below or even better have them stagger inwards (as it is now) on the bottom and outwards on the top layer?

**Comment by BluSunrize** [comment]
I'm afraid I don't quite understand what you are asking for. Could you clarify which edges you want me to change to what?

**Comment by b0bst3r** [comment]
Forgive my very dodgy looking editing but so it looks something like this (but in proportion) http://i.imgur.com/W1r5ZU3.png

**Comment by BluSunrize** [comment]
Oh, you want a wooden extension upwards in order to stack them?
I never really considered people stacking them, but yeah, I can look into that.

**Comment by b0bst3r** [comment]
Yeah people will stack them as they can be jumped over by mobs.

**Comment by mindforger** [comment]
> Yeah people will stack them as they can be jumped over by mobs.

how about an pushback effect additional to the damage to prevent mobs climbing or jumping it ?

**Comment by BluSunrize** [comment]
http://puu.sh/uqzIh/a1aed42404.jpg
http://puu.sh/uqzIy/401d68c169.jpg

This this roughly what you had in mind?
Also, not sure on the pushback myself. Might be too much, because along with slowing them down, it'd keep entities in long enough to do tremendous damage, and I don't want the wire to be too powerful.

**Comment by b0bst3r** [comment]
Perfect :)

**Comment by Voxel-Friend** [comment]
Just curious, what happens when they are stacked 3+ high?
Something like
><><><><><><
but vertical?

**Comment by BluSunrize** [comment]
To answer that and close this: It looks silly. Don't stack it 3+ high =P
