### ISSUE TITLE
Turntables turning extended pistons deletes blocks when unextended in a new orientation

### ISSUE THREAD

**Issue by deathaplenty** [BluSunrize/ImmersiveEngineering#1925]
How to reproduce:
1. place a piston onto a turntable
2. extend piston
3. rotate piston base to face the block you want to destroy.
4. retract piston

I've tested this on bedrock, tile entities such as the furnace, and multiblock structures . It will delete those, too. Tile entities drop their inventories. Multiblock structures actually drop the block instead of deleting it.

**Comment by BluSunrize** [comment]
*grumble*
That's because turrets don't handle rotation properly. Great, now I gotta special case that shit again >=c

Thanks for the report, I'll look into it ^^

**Comment by deathaplenty** [comment]
Note this was on version 10-56. I just noticed the 10-57 update. Just adding that in case it helps. :)
