### ISSUE TITLE
[Suggestion] Automated Armour/Tool Repair

### ISSUE THREAD

**Issue by SynfulChaot** [BluSunrize/ImmersiveEngineering#1928]
Would it be possible to have a machine capable of automating the repair of basic tools?

**Comment by VT-14** [comment]
Based on what Blu said in #1905, I don't have high hopes.

**Comment by alpha8196** [comment]
hmmm…how about some sort of chamber kind of like this 
https://s-media-cache-ak0.pinimg.com/originals/ee/69/51/ee6951ad3ec10a1fe78afe1ef6d5f19a.jpg with welding arms in it and when damaged item is suspended inside the welding arm will move around and weld(repair) with the cost of energy and soldering tin; and yes this will make no sense if used on leather and wood stuff

**Comment by HappyPineapple** [comment]
How about if it was used on leather or wood stuff it would repair it and also minorly improve it. Side note there would be a chance for wood and leather to catch on fire and destroy it cmpleatly.
