### ISSUE TITLE
Unable to load the game with this mod installed (ftb infinity)

### ISSUE THREAD

**Issue by Craftypiston** [BluSunrize/ImmersiveEngineering#193]
The game fails to load when i install this mod. I play with the ftb infinity mod pack. I don't know how to read a error report so i can't really provide you with better information then the crash log: http://textuploader.com/i44d

**Comment by BluSunrize** [comment]
FTB Infinity is using an outdated Forge Version. Unless you update it manually, there is no way to fix this.
