### ISSUE TITLE
A fatal error has occurred, this connection is terminated

### ISSUE THREAD

**Issue by Ghost77788** [BluSunrize/ImmersiveEngineering#1930]
So i have been happily playing skyfactory 3.06 and after getting to the fun parts i get this error.

Here is the log.
http://pastebin.com/0sTA9YvN

Furthermore i saw in another post that people were using mt reload, i have never even heard of it or used it.
But the error still occurs. Also i was able to get back on after installing a fresh IE.jar. It lasted 15 min atmost.

Thank you for your time.

**Comment by BluSunrize** [comment]
Thanks for the report.
The log provided look incomplete, I'm afraid.
For further investigation, could you please reproduce this issue, and immediately after upload the latest log file (should be "logs/fml-client-latest") and the latest crashreport from the "crash-reports" folder?

**Comment by Ghost77788** [comment]
Where is the crash folder located.

**Comment by Ghost77788** [comment]
http://pasted.co/38b78616

**Comment by BluSunrize** [comment]
I need your client crash, not the server one. And the crashlog folder is located exactly where hte normal logs folder is.

**Comment by BluSunrize** [comment]
Additionally, that log you provided is incomplete. Please produce the crash again and *then* provide the *full* log. Only with full logs will I be able to investigate this issue.

**Comment by Ghost77788** [comment]
Apologies for my imcompetence, here it finally is.
https://www.dropbox.com/s/vw1s210ljzcwfqa/fml-client-latest.log?dl=0
And i hope this is the crash l;og i do not have a folder named crash, just a folder named logs and these were the 2 logs in there after redoing the crash.
https://www.dropbox.com/s/vj658kn5i827itf/latest.log?dl=0

**Comment by BluSunrize** [comment]
Can you try disabling WAILA and see if you're able to connect then?

**Comment by Ghost77788** [comment]
The skyfactory 3 pack doesnt have waila, it does have wawla. Is that the one and would i be still able to connect to the server seeing as the packs dont allign

**Comment by Ghost77788** [comment]
I tried it without wawla and the error stil occured.

Here is the log.
https://www.dropbox.com/s/l7ephe4qowr7xcd/fml-client-latest2.log?dl=0
https://www.dropbox.com/s/487on72c5a71j1r/latest2.log?dl=0

**Comment by BluSunrize** [comment]
Skyfactory uses HWYLA, a fork of WAILA. And yes, disabling it should still let you connect.
I can't see anything pointing to IE in that log either, so the waila packet issue is my only guess.

**Comment by Ghost77788** [comment]
Ok thank you i will try that.

**Comment by Ghost77788** [comment]
Sorry for late reaction, your suggestion worked.

Thank you very much for your help.

**Comment by BluSunrize** [comment]
Glad to hear that fixed it.
I'll close this then.
