### ISSUE TITLE
Engineers hammer can rotate extended piston base, which can lead to block deletion.

### ISSUE THREAD

**Issue by deathaplenty** [BluSunrize/ImmersiveEngineering#1932]
This bug is similar to issue #1925 in that the extended piston base can be rotated (in this case with the Engineer's Hammer right click ability) before being retracted in a new orientation to delete a block.

How to reproduce:
1. place a piston
2. power it
3. rotate the piston base with hammer right click until piston base faces a block
4. un-power piston

**Comment by BluSunrize** [comment]
Now, despite this being marked as fixed, please feel free to report any further issues of this kind you noticed.
I have only special cased this for Pistons. There is bound to be other blocks that behave oddly on rotation as well. Any input on this is always appreciated ^_^
