### ISSUE TITLE
[1.10.2] Conveyor Belts Not Elevating on Shift-Click

### ISSUE THREAD

**Issue by spamfaux** [BluSunrize/ImmersiveEngineering#1935]
I am using the FTB Infinity Lite 1.10 Modpack managed through curse.

When using conveyor belts on flat ground they will not elevate when using the engineer hammer to shift-right click them. I've checked the controls and don't notice any conflicting control schemes.

**Comment by spamfaux** [comment]
Update: Holding somehting in the off hand inhibits the ability to shift-right click them and get a result. Just did it wihout torches in my hand and the conveyor hopped up.

**Comment by BluSunrize** [comment]
I'll have to assume this is a cross-mod conflict as well. Can't reproduce this in my dev environment...

**Comment by XFactHD** [comment]
This is not a cross-mod conflict, it is a forge bug @amadornes found while working on SCM. I unfortunately don't know exactly anymore what the problem was.

**Comment by AEnterprise** [comment]
yeah the both hands being checked thing while only the main hand is used
