### ISSUE TITLE
Refinery stopped working!

### ISSUE THREAD

**Issue by Thodebo** [BluSunrize/ImmersiveEngineering#1938]
The refinery in my base used to work. I have 2 moo fluid cows in putting the Ethanol and That other stuff. in the refinery whit EnderIO fluid cables. After a 2 Irl days the machine stopped working. I have replaced everyting and it still doesn't work. The only thing that changed around my base is that i have put a roof on top of it.

Playing on Project Ozone 2

**Comment by BluSunrize** [comment]
Provide pictures of the setup, please.

**Comment by Thodebo** [comment]
Oh nevermind! Sorry! the machine started working again when i rebuild everthing somewhere else :/

Sorry, If I bothered you.
