### ISSUE TITLE
Texture/model issue

### ISSUE THREAD

**Issue by alphanerd132** [BluSunrize/ImmersiveEngineering#1939]
I am getting this issue with your mod that is keeping it from loading. It gets stuck at model reloading. 

(no base model or parts were provided/resolved)
[13:33:38] [Client thread/ERROR] [FML]: MultiModel minecraft:builtin/missing is empty (no base model or parts were provided/resolved)
[13:33:41] [Client thread/WARN]: Unable to resolve texture due to upward reference: #side in immersiveengineering:models/block/ieScaffolding

**Comment by BluSunrize** [comment]
Are you using resourcepacks?
Also, could you please provide a mod list?

**Comment by alphanerd132** [comment]
No resource pack, this is a fresh pack build. And I can try to get a mod list but it will take a while. I have 100 mods in the pack. It is essentially the hermitpack but with ought a few mods that are having the same issue. When a mod has this issue, I usualy just don't use it but I realy enjoy your mod.

**Comment by BluSunrize** [comment]
Are you using optifine, currently?

**Comment by alphanerd132** [comment]
No. I usualy don't use it with packs because it is quite buggy with packs. And I just about got the list. ill generate a pastbin link

**Comment by alphanerd132** [comment]
Here is the mod list:  http://pastebin.com/KrQRZCcN
If you would like, I can give you a list of the mods that have the same kind of hold up on loading to see if there is a common trend between all of them.

**Comment by BluSunrize** [comment]
Could you try removing Chisel?

**Comment by alphanerd132** [comment]
sure. give me a sec to launch

**Comment by alphanerd132** [comment]
I see what you mean. It could be Chisel trying to make one of your blocks into a partial block and it is not handling it properly.

**Comment by alphanerd132** [comment]
EEYY we launched properly. THANKS! I will try throwing the others in and see if they work. If so, I will contact the dev of Chisel and inform him.

**Comment by alphanerd132** [comment]
And thanks for the speedy response! I was expecting to wait at least an hour for a response.

**Comment by alphanerd132** [comment]
No, it seems to be caused by mods independently. No idea why it would do that but it is. Ill do some more research on this issue and send ya a message if i figure out exactly what is causing the model manager to lock up. I have had this issue and all my friends have had this issue with 1.10 packs.

**Comment by BluSunrize** [comment]
Make sure you are using the latest version of Chisel.

**Comment by alphanerd132** [comment]
will do. But after some work, it seems that chisel is a carrier of a problem. There seems to be a deep rooted problem that I am trying to find. It seems that it is not just 1 mod causing these issues. I have no idea. I am still bashing my head trying to find it.
