### ISSUE TITLE
[Suggestion] Tinker's integration - Treated Wood

### ISSUE THREAD

**Issue by Voxel-Friend** [BluSunrize/ImmersiveEngineering#1942]
Since Boni removed the Splinters modifier from wooden handles in tinkers, Treated wood handles are effectively rendered pointless. My suggestion is to buff the handle modifier and possibly the overall material durability, as it is a higher quality form of wood.

**Comment by KnightMiner** [comment]
Last I checked, it already has slightly better stats than regular wood.

**Comment by Voxel-Friend** [comment]
Does it? *Checks*... *Blush* Derp

**Comment by BluSunrize** [comment]
I was unaware that Boni removed splinters as well (why does noone ever tell me things? D:)
I might look into revising it, but I don't want it to be too powerful either.
