### ISSUE TITLE
Crash: TileEntityFakeLight cannot be cast to gcewing.architecture.ShapeTE

### ISSUE THREAD

**Issue by NillerUdenDild** [BluSunrize/ImmersiveEngineering#1944]
Hey!

Whenever I try to place an ArchitectureCraft Roof Tile block directly in front of an IE Floodlight, my game crashes. Here's the crashlog: http://pastebin.com/eXqzj22n

It happened on a dedicated server, using the modpack "Dongland" version 2.6, with the latest IE

![2017-03-07_20 50 47](https://cloud.githubusercontent.com/assets/21295394/23674920/ddc7f754-0377-11e7-8b4b-f8543fc55c55.png)
![2017-03-07_20 48 56](https://cloud.githubusercontent.com/assets/21295394/23674922/ddcda082-0377-11e7-9621-ef3aabef0bc7.png)
![2017-03-07_20 50 41](https://cloud.githubusercontent.com/assets/21295394/23674921/ddc96134-0377-11e7-9d7b-941a71bbfe52.png)

**Comment by BluSunrize** [comment]
I would recommend reporting that to ArchitectureCraft. I assume they use TileEntity without checking their type.
