### ISSUE TITLE
Can't realize PowerCrops seeds with Kinetic Dynamo

### ISSUE THREAD

**Issue by SoniEx2** [BluSunrize/ImmersiveEngineering#1947]
Steps to reproduce:

1. Get [PowerCrops](https://minecraft.curseforge.com/projects/powercrops)
2. Follow the instructions on that page.

I expected the seeds to realize. But they didn't.

**Comment by SoniEx2** [comment]
Upon further testing, it seems to work if I drop it on top of a capacitor. But not on a kinetic dynamo...

**Comment by BluSunrize** [comment]
Wait...your own mod doesn't work with IE, and you're expecting me to fix it, yet you don't tell me what relevant code I need to change?
Clearly this is something you already know the reason for, so why are you trying to force me to investigate it?

**Comment by SoniEx2** [comment]
I don't know why it doesn't work. The kinetic dynamo doesn't seem to expose any power APIs? Yet at the same time it does return an energy capability... But it doesn't support any operations?

**Comment by BluSunrize** [comment]
It doesn't have any internal storage. It's a direct-output device.
I'd sorta expect you to understand how RF/IF/FU works if you're writing a mod for it...

**Comment by SoniEx2** [comment]
Well I didn't expect the generator to not have any internal storage, since every other mod does.

Thanks anyway, guess I just need to tell ppl that.
