### ISSUE TITLE
[1.10.2 v0.10-57] Chemthrower turret fuel switch

### ISSUE THREAD

**Issue by VallenFrostweaver** [BluSunrize/ImmersiveEngineering#1948]
I put a full metal barrel of creosote hooked up to a chemthrower turret and the internal reservoir of the turret turned the creosote into ethanol.

**Comment by BluSunrize** [comment]
I've not been able to reproduce this.
Were you able to make a setup that consistently did this, or was a one-off issue?

**Comment by VallenFrostweaver** [comment]
It's consistent for me. I'll get you more details in a day or so. I'm not
able to access that instance atm where I'm at.

**Comment by VallenFrostweaver** [comment]
Hmm. I have no idea what I was on the day I reported this but I can't reproduce it at all anymore either. Sooo... I close this. Sorry for the wasted time. :/
