### ISSUE TITLE
[IE 0.10-57] Water shot with chemthrower through lava lights entities on fire.

### ISSUE THREAD

**Issue by deathaplenty** [BluSunrize/ImmersiveEngineering#1949]
It's pretty novel. Fill your chemthrower up with water, put a lava source between you and your victims, and then burn them with water so hot it lights them on fire. 

This probably isn't that big of an issue, at least not one big enough to worry about. I'm just documenting it.

I haven't tested this with other non-flammable liquids (liquids the pilot light won't light)

**Comment by Joshwoo70** [comment]
pretty interesting bug.. though it should turn into steam...
