### ISSUE TITLE
[Suggestion/Request] Dependencies

### ISSUE THREAD

**Issue by VallenFrostweaver** [BluSunrize/ImmersiveEngineering#1950]
Is it much to add in the dependencies when you u/l to Curseforge? Each time I update I then have to reload the modpack 3 times to also add in a new version of JEI and then The One Probe. It would be nice is all. Feel free to close this.

**Comment by KnightMiner** [comment]
What exactly are you asking for? Do you want IE to state dependencies better, or to automatically update the other mods? If the latter, it is not a feature available on Curseforge.

**Comment by bookerthegeek** [comment]
I think that they would like the dependancies to auto update when installing the mods through the curse launcher.

**Comment by XFactHD** [comment]
That would be possible but I think only for hard dependencies like a library mod.

**Comment by VallenFrostweaver** [comment]
Nothing that complex. But if you find a mod on Curse there is a tab that lists dependencies and dependants.  It would be nice to have those listed there is all - or just a small reminder on the home descroption saying these other mods are required.

**Comment by bookerthegeek** [comment]
Gotcha, so not when installing the mod throught the launcher, but when downloading feom cuese forge.

You just want the dependancies listed on the dependancies page then right?

**Comment by VallenFrostweaver** [comment]
Yes pls pls!

**Comment by bookerthegeek** [comment]
I think Blue has to do that, unless he has added ithers to the curse page to be allowed to modify it

**Comment by mallrat208** [comment]
Dependencies on curse don't work that way. You can specify if something is a required library which will then download the latest available version or you can initiate if it's an optional library, say like JEI as it's not required to run the mod, it doesn't actually specify a version to download.

**Comment by bookerthegeek** [comment]
I believe he is asking for it to be listed [here](http://i.imgur.com/QCmmfIu.png) on curseforge.


![CurseForge Optional Dependencies Page](http://i.imgur.com/QCmmfIu.png)

**Comment by BluSunrize** [comment]
Blu, no E. I'm particular on that.

And yeah, sure I'll look into doing this in future ^^

**Comment by bookerthegeek** [comment]
Fixed it.

**Comment by mallrat208** [comment]
It'll add it there, but it won't tell the launcher you require those updates that @VallenFrostweaver was talking about

**Comment by BluSunrize** [comment]
Yeah, pretty sure that only works for mandatory libs. Because I know that Curse's launcher automatically grabs Baubles along with Botania, for instance (or at least used to. Haven'T used it in ages)

Don't think it'll work for optional libraries though, and IE has no hard dependencies.

**Comment by bookerthegeek** [comment]
And yes it still does the Blu

@mallrat208 

BookerTheGeek
>Gotcha, so not when installing the mod through the launcher, but when downloading from curse forge.
>
>You just want the dependencies listed on the dependencies page then right?

VallenFrostweaver
>Yes pls pls!
