### ISSUE TITLE
[IE 0.10-57] Placeable liquids such as Ethanol destroy water

### ISSUE THREAD

**Issue by deathaplenty** [BluSunrize/ImmersiveEngineering#1952]
How to reproduce:
1. Obtain a bucket of your favorite flavor of IE fluid
2. Pour it into a pool of water

It's pretty handy for clearing unwanted ponds, but absolutely horrible for oceans. The fluids will follow terrain, effectively undercutting the water above.

**Comment by omega025** [comment]
Liquids useful in industrial eco-warfare against other players on a server?  Sounds like a feature to me. ;)
