### ISSUE TITLE
Balloons not rendering in the End

### ISSUE THREAD

**Issue by Samrel556** [BluSunrize/ImmersiveEngineering#1953]
Balloons don't render properly in the End. I first noticed this on Sky Factory 3 version 3.0.6 in creative mode. I then tested it in Sky Factory 3 version 3.0.8 and also an instance with just IE. Happened all three times. All three were in single player. I did not modify either Sky Factories. Here's what it looks like. 
![2017-03-09_23 04 10](https://cloud.githubusercontent.com/assets/18405229/23784030/ca0f0d64-051c-11e7-956a-edeef5841c8b.png)
![2017-03-09_23 04 23](https://cloud.githubusercontent.com/assets/18405229/23784031/ca10d45a-051c-11e7-8c7b-803669fa1b7f.png)

**Comment by BluSunrize** [comment]
Sorry Malte, I didn't see you'd done work on this one until I had pushed it. I was just browsing the headlines and decided to look into this one.
Was a funky  lookiking issue though, and we basically figured out the same fix anyway x3
