### ISSUE TITLE
Let's over-complicate Farming

### ISSUE THREAD

**Issue by discodancepant** [BluSunrize/ImmersiveEngineering#1955]
I have a few ideas for the new Glass farming. [think hydroponics] Instead of a bit of tilled earth, if you have a bit of rocks as grow-medium at the bottom. Water or nutrient enriched water pumped to the tubes will cause growth. You could do both, with water growing the plants slowly and the nutrient solution increasing the speed or yield of the plants.

It would be a cool little effect to see water sprinkle occasionally from the top of the bell.

There could be a simple block system to make a mixture of metal dust to make the nutrient enriched water, and then pump the water to the system.

**Comment by discodancepant** [comment]
To add to the idea:
currently there is a connection to the top of the bell. if you change it to the back top side of the bell with a light bulb on the inside of the back top portion and add a water connection to the top, I think that would work.

**Comment by BluSunrize** [comment]
You know, I don't see myself just trashing the concept I worked on over the past 4 days...

**Comment by discodancepant** [comment]
wife had a baby ... kinda put life on hold. it's just an idea: if it's too late, or you don't like the idea that's fine.

**Comment by mindforger** [comment]
well, i don't see an new ideas on this, regarding the last discussion, he hits pretty much dead on

**Comment by discodancepant** [comment]
OK, well, it seems my ideas are moot at this point. feel free to close the issue. I looked for the old discussion thread on this, but it must be a bit buried.
