### ISSUE TITLE
Problem with crusher

### ISSUE THREAD

**Issue by VictorIP513** [BluSunrize/ImmersiveEngineering#1956]
Game version: 1.10.2
Mod version: 0.10-57
Forge version: 12.18.3.2254

After the "assembly" of the crusher, its model is displayed incorrectly. "The second crusher" is not a block (through it you can pass, put blocks). In this case, if you remove the main, the model of the second one remains. It is not possible to re-assemble a crusher at this place. This problem occurs only when playing on the server, in a singleplayer the problem is not observed.
![ie](https://cloud.githubusercontent.com/assets/17339800/23798695/5568e18a-05d8-11e7-8cb9-31de3ff84bb6.png)
![ie2](https://cloud.githubusercontent.com/assets/17339800/23798696/556ae502-05d8-11e7-9d09-aeb058a2c6c2.png)

**Comment by BluSunrize** [comment]
Is this on a server, and if yes, is the server running SpongeForge?

**Comment by VictorIP513** [comment]
Yes, i am using SpongeForge (version: 5.2.0.22.19)
