### ISSUE TITLE
Crash caused by the the Refinery

### ISSUE THREAD

**Issue by GeorgeZn** [BluSunrize/ImmersiveEngineering#1957]
As the title implies, the refinery is causing the crash, and, by the little information that I can get from the report, it's trying to divide by zero, why? I have no clue. Anyway, dropping the crash file here, I'll see if I can fix anything with MCEdit
[crash-2017-03-10_09.17.05-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/834334/crash-2017-03-10_09.17.05-server.txt)

**Comment by BluSunrize** [comment]
Could you tell me which recipe you were trying to use with the machine?

**Comment by GeorgeZn** [comment]
I was making biodiesel if I recall correctly, and I just had dropped the hemp seeds in the squeezer for it to make the plant oil i needed to make it

**Comment by GeorgeZn** [comment]
I also lowered some power and time requirements in the configuration file, if that's of any help

**Comment by BluSunrize** [comment]
Please show your config file then.

**Comment by GeorgeZn** [comment]
Ok, I finally got home, here's the file (sorry for the delay).
[config.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/834774/config.txt)

**Comment by BluSunrize** [comment]
The time modifier for the refinery mustn't be lower than 1.
I'll make sure to safeguard against this in future.

**Comment by GeorgeZn** [comment]
Oh, ok the if I just return the energy costs to a value of 1 this issue should stop?

**Comment by BluSunrize** [comment]
Yep!
Reason for this is that currently it handles time as:
floor( basetime * Modifier)
if basetime is 1, and modifier is 0.9, that's 0.9, and if you floor that it's 0. Which then results in a division by 0 later on.
I'll absolutely safeguard against that in future, but for you, right now, simply setting that config to 1 again will fix it.
