### ISSUE TITLE
[suggestion] plates and sheetmetal for every (metal) ingot

### ISSUE THREAD

**Issue by epiz** [BluSunrize/ImmersiveEngineering#1959]
I don't know if a lot of people would use them for decoration, but a gold plated roof would be cool maybe. I would like to have the plates for consistency because I'd like to change some recipes in my mod pack to use plates instead of ingots and it would be nice if all plates are from Immersive Engineering and have similar textures.

Some plates might be useful for future IE recipes, gold is a good material for electronics and silver is good for mirrors maybe? idk

**Comment by BluSunrize** [comment]
They have textures now too. Will be in the next release, so I'll close this
