### ISSUE TITLE
Arc Furnace doesn't split items on input

### ISSUE THREAD

**Issue by 4AM-Campfire** [BluSunrize/ImmersiveEngineering#1962]
The Arc Furnace doesn't split items on input making it very hard (or impossible) to effectively automate.

**Expected:** Items spread evenly into all 12 input slots **OR** to cook 12 items from a single stack at once
**Result:** Items stack into a single slot, cooking 1 at a time

When you push ore/dust into the top (via Conveyors or Hoppers) every item just stacks up in the first input slot, so instead of cooking 12 items at once you only cook 1. Shift-clicking via the GUI also just stacks everything into one slot. This is different from the Squeezer and Fermentor which process 8 items at once from the same stack.

This seems to be an error as the machine is meant for mass producing ingots, but when you automate it you end up with effectively a giant single slot furnace until you overfeed it with Ore.

**Comment by TomyLobo** [comment]
Suggestion: If you don't want to change the current behaviour for everyone, make a button to toggle it.
Actually Additions' Double Crusher also has this feature, but I'd suggest you use a button label different from theirs :)

**Comment by Gravlok** [comment]
It would be really nice get that thing fixed up. I was so eager to go back to minecraft and set up my base IE retro style and make all my ore processing and enriching stuff made by Arc Furnace. This one detail is really painful to overcome.

**Comment by malte0811** [comment]
Fixed for the next 1.11 release.

**Comment by Gravlok** [comment]
What about 1.10? Many modpacks are based on this version... There is no love left for 1.10?

**Comment by malte0811** [comment]
See https://github.com/BluSunrize/ImmersiveEngineering/pull/2237#issuecomment-311308689

**Comment by TomyLobo** [comment]
So you're not planning any further 1.10 releases. What if people PRed and tested the changes for you?

**Comment by BluSunrize** [comment]
Doesn't change the fact that I'd have to pull and build and write changelog and release and all that stuff.
Plus the easiest way to encourage people to move ahead is to just keep going. We don't need another 1.7.

**Comment by Gravlok** [comment]
IMO it doesn't encourage but forces people to keep going...

**Comment by BluSunrize** [comment]
Not forcing. It's not like I'm leaving behind completely broken versions that force people to move along to be able to play at all. I'm just having the new content added to new versions.

IE was entirely too late in moving to 1.11.2, I'm not making that mistake again for 1.12.

**Comment by Gravlok** [comment]
So we can assume you didn't say "No" overall and that one nuisance will be eventually fixed some day?

**Comment by BluSunrize** [comment]
No. I'm not working on 1.10 anymore. What's so hard to understand about that?
