### ISSUE TITLE
[1.10.2[ Aluminum vs. Aluminium

### ISSUE THREAD

**Issue by JasonMcRay** [BluSunrize/ImmersiveEngineering#1963]
Just a simple request from a simple man. Can we get both oreDictionary tags on items from Aluminium (Aluminum and Aluminium)?

So I can use aluminium from different mods in IE recipes?

Thank you very much

**Comment by BluSunrize** [comment]
Which other mod is incorrectly using Aluminium?
General convention is that OreDict entries are in US English. Basically every mod does this.

**Comment by JasonMcRay** [comment]
Oh I had no idea that there is a convention. I was used that fair amount of mods in the past were just using both. GregTech 5U is using just *Aluminium oredict.

So should I just ignore this and use minetweaker to re-register GT aluminium to aluminum to avoid the classic: "not my fault its theirs" on both sides? :)

**Comment by BluSunrize** [comment]
Well, honestly, I'd try to encourage whoever is maintaining GT to do what basically any other dev does, but yeah, re-registering might be your best approach.
The irritating thing about doing recipes for both is that it'd appear twice in JEI, meaning you'd see double recipes for everything involving aluminum/aluminium ^^"

**Comment by JasonMcRay** [comment]
I opened an issue on GT tracker about this. Either something will be done about this on either side or it will be just some "annoyance" that modpack maker must workaround :)

**Comment by mindforger** [comment]
uhoh Jason you just poked a wasp nest :D

**Comment by JasonMcRay** [comment]
Honestly @mindforger , I poke so many wasp nests that I developed immunity against wasps. That's a boon given to us dedicated to make GregTech work with anything anytime :D

**Comment by BluSunrize** [comment]
I'll close this, as I already stated that I don't fancy dealing with the recipe nightmare .-.
