### ISSUE TITLE
Using Quark's Charcoal Block in (Improved) Blast Furnaces

### ISSUE THREAD

**Issue by nichdel** [BluSunrize/ImmersiveEngineering#1964]
Quark (a vanilla+ style mod by Vazkii) adds a charcoal block made by crafting 9 pieces of charcoal together. Blast & Improved Blast Furnaces don't accept it. Would it be possible/reasonable to support this?

Thanks for your time & work.

**Comment by BluSunrize** [comment]
Yeah I've heard of Quark once or twice. =P

Didn't realize Vaz had added a charcoal block though. I'll look into it, cheers for the report.

**Comment by ArukaAlter** [comment]
Just to be aware, Actually Additions and Mekanism have charcoal blocks too.

**Comment by BluSunrize** [comment]
Did not know about the former, did not care about the latter =P

**Comment by BluSunrize** [comment]
Ah, sweet, there's a fix. Cheers Vazkii ^^
