### ISSUE TITLE
[0.10-57] Turrets don't accept EnderIO Conduits

### ISSUE THREAD

**Issue by trunksbomb** [BluSunrize/ImmersiveEngineering#1965]
They just don't connect. Trying on a regular Gun Turret in both the bottom and rear ports.

Actually they just won't take anything? Tried Transfer Pipes from Extra Utilities 2 and even an IE conveyor belt.

**Comment by generilisk** [comment]
Refined Storage importers can't place into them either.

**Comment by BluSunrize** [comment]
fixed with the next release, see this commit:
https://github.com/BluSunrize/ImmersiveEngineering/commit/4d26c045ecce67c05151b82732d84cdcc1e5cde6
