### ISSUE TITLE
[Request] Windmill height relevance config option

### ISSUE THREAD

**Issue by Baughn** [BluSunrize/ImmersiveEngineering#1966]
We're playing on a skyblock pack (SF3), with nothingness all around us. And yet even so, the windmills produce less power if they're placed lower down, despite there being absolutely nothing to block to flow of air.

Would it be possible to add a config option to disable that mechanic? They're mostly for flavor anyway, it's true, but it would be nice to have believable mechanics.

Also I could then tell people to stop building enormous cobblestone towers, and stick with airships.

**Comment by NicosaurusRex99** [comment]
Further suggestion, tiered windmills. dependent on size! larger mills take more wind but produce more power and smaller basically run 24/7
