### ISSUE TITLE
Step ladder - a creature comfort.

### ISSUE THREAD

**Issue by marcin212** [BluSunrize/ImmersiveEngineering#197]
How about adding an item like a step ladder? Sometimes you just need to hop up  a couple blocks to reach somewhere. Instead of placing dirt/cobble you could craft a ladder item that when placed (anywhere, unlike vanilla ladders) would allow you to climb those few blocks and then simply dismantled (eg. with a right-click, or one punch) back to an inventory item.
It could be craftable from different materials to give you different climb heights (wood - 3, iron - 5, steel - 7).

**Comment by primetoxinz** [comment]
unsure if this should be separate but maybe a way to climb the wooden posts, such as  adding the little metal pegs like in real life

**Comment by mindforger** [comment]
an self extending ladder, with length depending on how high the next walkable block is but limited to 3 oder 4 blocks total, which is leaned at an slight angle against the top block ... would also suffice the required height to climb a pole! 
Dismantled by ctrl+shift+rightclick, as you need shift rightlick for so much other things that you won't risk falling from the ladder while ducking to stay on the ladder and rightclicking to place something

**Comment by MyDeloreanWontStart** [comment]
Immersive engineering becomes the ladder mod

**Comment by warlordjones** [comment]
*quietly takes notes for BrassUtils*

**Comment by johnfg12** [comment]
i would love to have ladders good for industrial builds :D
