### ISSUE TITLE
[Bug] Mixer receiving water input stops mixing concrete

### ISSUE THREAD

**Issue by omega025** [BluSunrize/ImmersiveEngineering#1970]
When playing around with the new mixer, I've noticed that it will quite happily mix concrete when the vat is filled with water and has no active water input, but when I switch on a connected water pump to keep the mixer filled with water, the mixer stops producing liquid concrete and the output switches to water instead (though the mixing animation continues).  Only after I switching the water pump back off and add another barrel or tank to allow the backlogged water to "drain out" from the mixer, will concrete will be produced again.

**Comment by omega025** [comment]
Also, tangential question - is there a way to automate material inputs for the mixer? I've tried dropping items into the vat but that doesn't seem to do the trick, so I'm assuming there isn't an automation feature yet.  If not, maybe this could be achieved with an add-on block, like the preheaters for the blast furnace?  (Or just with items being dropped in.)

**Comment by omega025** [comment]
Adding a note to mention that I did read the closed issue about mixer fluid control (https://github.com/BluSunrize/ImmersiveEngineering/issues/1927), but contrary to Blu's comment, this issue seems to occur even when all recipe ingredients for concrete are present in large stacks (close to 64).

**Comment by BluSunrize** [comment]
Inputting ingredients? Try the hatches with the blue dots at the back.
Outputting fluids? New fluid router will assist with this. There is basically no other way to detect something to be an in- or output fluid.

**Comment by omega025** [comment]
Ah, those are hatches!  Attaching a conveyor belt to them works, thanks for clearing that up Blu.
