### ISSUE TITLE
[ToDo] Multi-level concrete blocks

### ISSUE THREAD

**Issue by omega025** [BluSunrize/ImmersiveEngineering#1971]
Loving the new liquids so far. I did notice, however, that dumping liquid concrete with a jerrycan will produce rather large patches of dried concrete - on average, from one click (1000mB of liquid concrete) I've been getting 20x16 diamond-shaped patches with 190 concrete slabs.  Can liquid concrete be made to flow more slowly and produce fewer slabs?

**Comment by BluSunrize** [comment]
If it flows slower it wouldn't ever properly cover things since it'd dry too quick, making it quite useless.
I have considerations to have the dried blocks be of different levels. Concrete "carpet" if you will, and a quarter/threequarter slab.

**Comment by omega025** [comment]
That seems like a reasonable compromise.  Could enable more interesting decoration options for people who prefer not to use Chisels&Bits, too.

**Comment by BluSunrize** [comment]
I've done this thing. Just forgot to tag the issue in the commit.
