### ISSUE TITLE
[1.10] Power loss seems to be way too high.

### ISSUE THREAD

**Issue by Paul17041993** [BluSunrize/ImmersiveEngineering#1972]
In the config files, there should only be .025% loss every 16 blocks for HV cable, but in reality the actual loss is _far far_ from that, by a factor of about 80...

In testing I peaked out a HV line to 32kRF/t, sent it over less than 200 blocks and lost about 20% of the power at the end, according to the numbers above however this should only be less than .3% loss? where on earth is the rest of the loss % coming from...?

**Comment by malte0811** [comment]
The power loss indeed seems to be higher than expected, I'm taking a look right now.

**Comment by malte0811** [comment]
And once again I didn't read properly, you misunderstood 2 things about the config option:
1. 0.025 doesn't mean 0.025%, it means 0.025 absolute so 2.5%.
2. The given loss is for the maximum wire length, so it's 2.5% per 32 blocks.

So the loss should be about 15%=2.5%*(200/32). I guess that counts as "about 20%"?

**Comment by Paul17041993** [comment]
oook then I guess I'll have to change the config to be at least 10 times less lossy, because with that value the HV wires aren't going to carry any power at all over the 1.6km distance I need it to...

It seems like the loss mechanic could work better, IC2's for example clocks down individual units as a way to replicate voltage droop, countering that simply involves increasing the voltage and decreasing the current and loss in the process. IE's loss basically treats each type as running the same, low, voltage and as a result they all perform mostly the same when you exclude the additional utilisation bonus.

**Comment by malte0811** [comment]
@BluSunrize I have a suggestion regarding long range energy transmission (warning, long text):
Being able to transmit energy over long distances with reasonable losses would be quite nice, especially since transmission through unloaded chunks is a thing. The main argument against UHV wires with low losses in the past was (IIRC) that everyone would just use it for everything which would defeat the purpose of lower voltage wiring (I believe that most people either don't know or don't care about additional losses for transmitting less than maximum power). My suggestion would be to add UHV wires (with very low losses/block) with a couple of twists:
1. They can't be connected directly to a machine accepting Flux energy. Think of it as a multi-100kV power line: There are machines that use a couple of kV as input voltage, but virtually no machine uses >100kV input. The only way to use UHV is to run it through a step-down transformer.
2. The (up- and down-stepping) transformers have losses. IRL transformers of that size have losses of 1-2%, since IE is "old" tech that could probably be increased to something like 5%. Efficiency would be dependent on the percentage of used power capacity, IRL transformers seem to do the same thing ![Power vs efficiency](https://www.copper.org/environment/sustainable-energy/transformers/images/graph1.gif)
These transformers would probably be multiblocks, something like this, but with only one phase ![](http://www.samgor.com/sites/default/files/transformer.jpg).

That way using UHV would only be feasible for pretty long distance transmission lines.
Implementing such a system should not be too hard, I don't really care who does the implementation if you like it.
Do you like the idea or not? It is just a random idea from a chemistry lesson.

**Comment by mindforger** [comment]
i would LOVE to have a beefy multiblock transformer .. i always build some sort of off base power stations and transfer the energy to my base because of the noise of the diesel gens and the uglyness of other energy sources

**Comment by Paul17041993** [comment]
I was originally going to suggest making the HV connectors incompatible with most machinery, however that would break compatibility with machines that need more than what MV connectors can provide...

So UHV makes the most sense, in a summary;
- add UHV relays, these can carry wire over 64 blocks and should look longer, likely about 1.5 blocks hanging down (much like a vanilla door but needs a block above it instead of below)
- probably add UHV wire, mostly the same as HV wire but should use more aluminium than steel and be thinner (3 al., 1 st. wire, 8 per craft instead of 4?)
- a multiblock transformer, 3 terminals each side, either 3x3x3 or 5x3x3, steel casing, dense copper core but not sure about coolant...

Each UHV line should carry the same power as HV but at a much lower loss and without the standard connectors. UHV could carry 2-4 times more power than HV but 6 lines already carries just under 200kRF/t, so it makes more sense to use more lines and poles for anything greater than that.

An additional option is HVDC, which is commonly used above AC in main line distribution as its both cheaper and much more efficient over long long distances, however it requires some [complex and expensive hardware](https://en.wikipedia.org/wiki/HVDC_converter) at each end. This could be tier 5 and would have virtually no distance loss but a small conversion loss.

**Comment by malte0811** [comment]
A few notes on what you said:
1. 64 block wires are not going to happen, rendering is already messy/broken when the wire goes through more than 2 chunks (unfixable without major performance losses or change to MC).
2. IE does not have 3 phase power, so I would suggest adding single phase transformers (so one connection on each side). If you want 3 lines for some reason, you could just split the line up or build 3 transformers.
3. UHV should in my oppinion have transformer losses, I personally don't think that basically lossless power transmission fits IE.
4. HVDC wasn't really that effective between WW1 and WW2 if I understood wikipedia correctly (mostly mechanical converters, motors attached to generators). That would be the time period where I would place IE, probably closer to WW1 than WW2.

**Comment by mindforger** [comment]
@malte0811 HVDC groundwires are a thing in germany you should know, they are perfect and pretty much lossless in transportation, main issue like you noticed is power conversion and load balnce in meshed power net

to control the power flow you'd need to adjust voltage a bit
with transformers and variable power taps this is not problem but for DC your need powerfull DCDC converter with loss .. same goes for the AC inverter to get it back to "normal" power networks

china employs a 500kV HVDC air-line for long range transmission afaik ... i like the idea of using HVDC to explain incoompatibility to "normal" LV MV HV distribution and the transformers are not transsformer 

i would like to propose as idea an multiblock AC/HVDC converter
`DC CO HV`
`SB CA SB`

DC = HVDC connector
CO = HVCoil
HV = HV Connector
SB = Steelblock
CA = Capacitor

maybe replace the steelblocks by some sort of circuitblock or whatever, but the capacitor and the coil together work as AC inverter ... well, this apperatus lacks the required rectifying components to make AC to DC dunny what can be done about that

**Comment by malte0811** [comment]
I know that HVDC is good these days, but from what I understand it wasn't too feasible in the time of the Weimar republic (which is IMO the time IE's tech is from). Also, just attaching a cap and an inductor (with internal resistance) to DC isn't going to produce AC if I understood everything correctly, it will produce a damped sine wave for a short period and after that reach a steady state, you need some sort of high power switching component. Rectifying could be done using mercury arc valves, I believe they were available at the time (I may well be wrong there).
But as a general question, shouldn't we wait for a statement from Blu on whether he wants this in IE before we start planning details?

**Comment by bookerthegeek** [comment]
@malte0811 I like the transformer pictured.

Most long distance high voltage lines tend to use more than one strand. why not have multiple inputs so that you can actually power the LDHV lines at full power? Say if one Line can care the Max that one HV line can before melting, that way I can run massive amounts of power, which is what this is for correct?

**Comment by Paul17041993** [comment]
@malte0811 
1 - looking at that now actually, I'll just have to see how mc handles it and what could be changed.
2 - the problem with only having the single phase is it may make it too 'OP', having it pseudo-three-phase would encourage it to only be used in main distribution lines. That and the full thing would look better :)
3 - guess I forgot to mention that, yes there should be a loss in the transformers, though looking at the current code that may need a fair amount of extra work...?
4 - mercury arc valves were invented in 1902 and improved significantly around 1930, so I'm pretty sure they would have been used a fair amount during the WWII era, though they would have especially been used for legacy compatibility with existing DC grids. For bonus comparison, nuclear power didn't come around until after 1950, yet I see uranium and lead concrete in IE... :U

**Comment by Paul17041993** [comment]
Prototype code working, I'll likely commit this as-is to my own branch and fix the rendering tomorrow.
http://prntscr.com/elf9ex

**Comment by Paul17041993** [comment]
https://github.com/Paul17041993/ImmersiveEngineering/commit/15a139c7b4fe44040dc40bb9f3c845851f01a8b8

**Comment by BluSunrize** [comment]
I don't yet to know how I will approach this. I honestly don't want another wire tier, but I do agree something needs to be done about loss.

Just to put something out however: Don't try to sort IE into a real world timeframe. It's got freehanging, uninsulated wires that go along with self-thinking turrets and railguns. This is a work of fiction and I'll just grab whatever I can make stylistically fit in, I don't actively go "this wasn't invented in 1910" x3

**Comment by Paul17041993** [comment]
Well the wire rendering doesn't seem too problematic, but there's definitely issues with chunk updates and bad frustum culling.

<img width="1442" alt="screenshot_43" src="https://cloud.githubusercontent.com/assets/3912867/24078115/502052bc-0cb8-11e7-9042-eaf16c91058b.png">

I'll likely put this all in an add-on mod if @BluSunrize feels it doesn't fit in the main mod.

**Comment by malte0811** [comment]
The frustrum culling is what I was talking about. See #1281 for more details, but it boils down to the fact that a) making it work as well as it does now was a fair amount of work and b) no one has been able to figure out a way to make the chunks outside the frustrum render without using TESRs which would be bad for performance.

**Comment by Paul17041993** [comment]
There's ways that I'm pretty sure will work better, though I'm not going to worry about it until UHV is fully developed.

**Comment by Paul17041993** [comment]
I'm going to note this as well; adding the UHV tier to the main mod means that the config file has to be deleted and re-generated, because for some reason forge currently doesn't check if the arrays are of the correct size when it applies them...

Other than adding a special UHV tier, I cant think of any straightforward solutions that don't have their own problems, but here's a list;
- change loss to a more fixed value instead of a %, eg 128RF is lost in HV but independent of distance, still could be an undesired loss however
- massively reduce the loss % when multiple connectors are paired, however this could be abused just by attaching dummy connectors...
- remove HV connectors like I already mentioned, but again, MV doesn't provide enough flow to some 3rd-party machines, unless we add a high current MV connector/receptacle?
- could disable HV connectors accepting energy, though might still have the above issue but with sources instead of machines (some single block generators produce _heaps_ of power...)
