### ISSUE TITLE
[Suggestion] Mixers fill with water during rain if unsheltered

### ISSUE THREAD

**Issue by omega025** [BluSunrize/ImmersiveEngineering#1976]
Given that mixers can contain more than one kind of liquid, and that vanilla cauldrons fill with water during rainfall, perhaps mixers could be made to fill with small amounts of water at the top of the vat if left exposed to the sky during rain.  This would be a mildly helpful feature when mixing concrete, and would encourage players to take steps to protect their potion-making equipment from the elements to prevent contamination (like in real life facilities that make things for human consumption).

As a bonus, this would also allow mixers to double as an automate-able rainwater source on challenge maps that lack water source blocks.

**Comment by HappyPineapple** [comment]
Good Idear
