### ISSUE TITLE
Assembler ejecting crafting materials

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#1977]
Issue: When crafting Essences from **mystical agriculture**  via the assembler involving a crystal, the assembler ejects the crystal as soon as a crafting operation is completed, even though it is a set ingredient. The product of the crafting operation is not ejected, as expected, as it is involved in the 2nd and 3rd recepie.

----------
Expected behavior: the crystal is retained in the Assembler's inventory for further crafting

Actual behavior: The crystal is ejected upon the completion of a single crafting operation

-----------
steps to reproduce:
1. Correctly form,power, and provide an output for an Assembler.
2. Set the first crafting recipe to produce `Prudentium Essence` via the `Inferium essence` and the `Infusion Crystal` items
3. Set the Second crafting recipe to produce `Intermedium essence` via `Inferium essence` and the `Infusion crystsal` items
4. Set the Final crafting recipe to produce `Superium essence` via `intermedium essence` and the `Infusion crystsal` items
5. Insert the `Inferium essence` and the `Infusion Crystal` items into the assemblers inventory via pipes or manually and let craft

The assembler will successfully re-use the crystal it ejects if it is reintroduced, however it is unexpected for the crystal to be ejected to begin with given the `Prudentium Essence` is NOT ejected as it is also further used in other set recipes

---------
reference for crafting recipes

![image](https://cloud.githubusercontent.com/assets/3110986/24084460/f06e07ac-0ca7-11e7-9406-ac2bf7eb558b.png)

reference for setup
![image](https://cloud.githubusercontent.com/assets/3110986/24084473/1e4b1566-0ca8-11e7-9743-dab96dd0a914.png)

--------------
IE Version 10-57 Curse release ([I can't seem to build IE from source...](https://gist.github.com/theunkn0wn1/6befb51b293ec5cecb69d4382384700b))
mysticalagriculture version [1.10.2]-1.4.4a

**Comment by BluSunrize** [comment]
Well I've tested this, and yes, the Crystal is ejected.
I've also tried the Master Infusion Crystal, and that one stays within the machine.

Honestly, I don't think that's bad balance, tbh. If you wanna do it with the normal crystal, you'll need to setup an itemrouter+feedback system, whereas with the more expensive one, you can avoid it.
I find that quite interesting and appealing for a balance choice, despite it being purely accidental =P

**Comment by theunkn0wn1** [comment]
Having a feedback system involving just IE conveyors and item routers is
prohibitively time expensive. Given how, according to  Refined Storage's
auto crafting solution, to craft a dozen of the blue essence I need the
better part of 1k of the raw input. Given how slowly the Assembler works
with default configs and the time it would take to move the crystal back
and forth via Conveyors I would be better off doing the crafting myself.

To make 12 of the desired product it would require ( 4**3)*12 or 768 unique
crafting operations. Given how it takes several seconds to move an item 5
meters via Conveyors and the item would have to be returned to the input
after every iteration, it is impractical to use IE due to this bug.

Plus, it is inconsistent for the Assembler to eject a crafting item. The
fact that it will use the very same item if it is reintroduced and that the
other intermediate products are not ejected is confusing and counter
intuitive.


On Mar 20, 2017 10:29, "BluSunrize" <notifications@github.com> wrote:

Well I've tested this, and yes, the Crystal is ejected.
I've also tried the Master Infusion Crystal, and that one stays within the
machine.

Honestly, I don't think that's bad balance, tbh. If you wanna do it with
the normal crystal, you'll need to setup an itemrouter+feedback system,
whereas with the more expensive one, you can avoid it.
I find that quite interesting and appealing for a balance choice, despite
it being purely accidental =P

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/BluSunrize/ImmersiveEngineering/issues/1977#issuecomment-287835580>,
or mute the thread

**Comment by BluSunrize** [comment]
Found a decent fix for this. Damageable items without subtypes are treated as ingredients.

Also added a recursive function to, for instance, use a water bucket and then use Water Essence from Mystical Agriculture to refill it.

**Comment by theunkn0wn1** [comment]
Thanks for the fix, would it be possible to get some help getting [IE to build again?](https://gist.github.com/theunkn0wn1/4c481b39e0a7351a80e6d41185a2e3f4) I presume the next release is still a fair bit of time away and i would really like to try out (and perhaps break!) the new features. It doesn't seem like I'm missing any dependencies and Java is reasonably up to date(1.8.0_121)...

**Comment by malte0811** [comment]
Comment out the line that is crashing, Blu accidentally added it to a commit some time ago. See https://twitter.com/BluSunrize/status/846845727376592899 for a screenshot of what that line is about.

**Comment by BluSunrize** [comment]
Yeah sorry, no point around that. I needed to commit the IE content file =P

Should hopefully be fixed today, if Hazard finishes the textures.

**Comment by theunkn0wn1** [comment]
Thanks for the quick replies 😄
The IEContent error is understandable and is readily worked around by commenting it out for the time being.

As for the error with IEFluid.java? It kinda needs to stay out Java complained about a missing override.

**Comment by BluSunrize** [comment]
I have no idea. IOExceptions are weirdly broken in the buildscripts, but I dunno why.

**Comment by theunkn0wn1** [comment]
Welp... time to find a turret... Got it to build. 
For (my) future reference using `setupDecompWorkspace` and **_NOT_** `setupCIWorkspace` works out.
I know, i know... ive been told off for this before...

Anywhoom thanks for the support you two, really appreciate it.

**Comment by BluSunrize** [comment]
It's *always* Decomp. There is basically no point to CI. Decomp is superior =P

**Comment by malte0811** [comment]
If you just want to compile stuff Dev might also be a good choice IIRC, it deobfuscates MC without decompiling it which takes a lot of time with Decomp.
