### ISSUE TITLE
Turret inventory appears to be broken.

### ISSUE THREAD

**Issue by AgentA1cr** [BluSunrize/ImmersiveEngineering#1978]
This may be one issue or two, I'm not sure. Firstly, the turret is deleting the contents of it's inventory, seemingly whenever the chunk it's in is unloaded. Also, it will not connect to enderio item conduits, though it will connect to the redstone conduits. (Yes, I am trying to connect them to the item ports, not just anywhere.) Is there any other info that would be helpful?

**Comment by BluSunrize** [comment]
It won't connect to EIO conduits anyway, the release 57 is missing the inventory capability for other blocks to interface with. That's been fixed.

I can't seem to replicate the loss of inventory however. Is it happening when you close hte singleplayer world and restart it?

**Comment by AgentA1cr** [comment]
Yes, that causes it. I'm pretty sure I've also seen it happen when I travel a significant distance away and then come back, but I can't seem to replicate that behavior at the moment. Closing and reopening the world definitely does it though.

**Comment by malte0811** [comment]
I was able to replicate this using the latest Maven build (while working on IndustrialWires), I will test and possible fix this in my IE dev environment either later today or tomorrow.

**Comment by malte0811** [comment]
Fixed.

**Comment by AgentA1cr** [comment]
Thanks. Can't wait for the next build!

**Comment by AgentA1cr** [comment]
Also, I just took a look at industrial wires, and that's getting added to my modded instance.

**Comment by BluSunrize** [comment]
Haha, yeah that makes sense for it to be broken. Thanks malte x3
