### ISSUE TITLE
Glitched Extra Nickel Ore generating

### ISSUE THREAD

**Issue by Zsashas** [BluSunrize/ImmersiveEngineering#1981]
Occasionally I'll find a Nickel Ore block while mining that has the black and magenta missing texture, and has metadata 15 instead of 4, and is entirely useless.

**Comment by malte0811** [comment]
Are you using some external mod like Thermal Foundation for ore generation?

**Comment by Zsashas** [comment]
No Thermal mods in this instance at all. In fact, this time around, ore generation has been largely untouched from defaults. The only things I changed were increasing some magic ores.

**Comment by BluSunrize** [comment]
Which version of IE is this?

**Comment by Zsashas** [comment]
0.7.7 if the filename is accurate.

**Comment by BluSunrize** [comment]
Minecraft 1.7.10 is no longer supported, I'm afraid.

**Comment by mindforger** [comment]
which tools did you use to mine the ore? i am afraid that issue is coming from mining stuff with tinkers tools (+ addons) .. i occasionally have this with dirt and stone but never had it with any ores yet

**Comment by Zsashas** [comment]
The ore block is generating in the world glitched. I went down into some caves and saw the black and magenta block just sitting there, this isn't from being mined by some modded tool.

**Comment by BluSunrize** [comment]
Still not supported anymore, and most likely a crossmod issue, since this has never been reported in the past 2 years >_>
