### ISSUE TITLE
Post rendering malfunctions

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#1984]
This only seems to occur with posts (of any variant) placed at Y-level = 63

Issue: Post extensions fail to render; posts stop rendering completely if the player looks up toward the sky (angle of ascension >=60 deg).
The rendering fixes itself when either the world is reloaded or a different post is placed (at a different elevation) within the same chunk and extension applied.

Possible steps to reproduce:
(1)Load any world (new and old both exhibit this issue)
(2) place a Steel post into the world, its base block MUST be on y-coordinate 63
(3) use the hammer to add an extension
(4) observe

-------------
Screenies:
![image](https://cloud.githubusercontent.com/assets/3110986/24232071/b242cc4c-0f45-11e7-8513-a7a2aede343e.png)
![image](https://cloud.githubusercontent.com/assets/3110986/24232221/a1f47240-0f46-11e7-83e6-0a253348dad5.png)
![image](https://cloud.githubusercontent.com/assets/3110986/24232253/dd5cb644-0f46-11e7-87ed-ddb33a8e31a8.png)

--------------
Immersive Engineering Version 10-57 Curse

**Comment by housleyjk** [comment]
This looks like an optifine issue. Are you using optifine? Does this occur without it?

**Comment by theunkn0wn1** [comment]
... no Optifine.

**Comment by bartczam** [comment]
No optifine neither, but I see same bug happening with Garden Cloche - basically with anything type of _device, so it is not isolated to posts only. Placing things on different Y fixes the issue, but 63 is the worst case :)

**Comment by malte0811** [comment]
And so are 15, 31, 47 and any other 16n-1. Horizontal chunks are quite well known, vertical chunks exist in vanilla MC for rendering purposes. The bottom block of the post does the rendering, the upper blocks are theoretically invisible. If you can't see the (vertical) chunk the bottom block is in nothing will be rendered. This affects every machine in IE that is bigger than one block and there isn't a proper way to fix it (as far as we know). The post could be rendered by the middle block, but that wouldn't improve the situation that much.

**Comment by theunkn0wn1** [comment]
If it has something to do with Vertical chunks, then why does placing an additional post fix this?

**Comment by bartczam** [comment]
Thanks for detailed explanation! I'll just avoid building at 16n-1 locations. 

Maybe we could have a new blocks instead: post stand, post pole and post top with the behavior of connecting the items to post top, but still being 1x1 block?

This way bug could be avoided (and I am sure people would make interesting builds - like different height posts)
