### ISSUE TITLE
[1.10.2 - v0.10-57] Automated Workbench issues

### ISSUE THREAD

**Issue by VallenFrostweaver** [BluSunrize/ImmersiveEngineering#1988]
#1. Bottom right where the blueprints goes in the workbench UI will accept items first if not occupied.
#2. Bottom right most slot of item inventory will not fill if being piped into the workbench.
#3. (minor graphical glitch) When making ammunition the image that is used is either the the dragon breath shot (if using the specialized projectiles bluebrint) or the casull cartridge (if using the common projectiles blueprint) that is made on the workbench just before leaving the workbench edge (after it is "pressed"). Once it has left it then it looks like the correct ammunition that was being crafted.

See images below:
1 & 2
![ie](https://cloud.githubusercontent.com/assets/13642054/24412196/ae96d01e-13cf-11e7-9798-c55d3a667aa4.png)

3
![ie2](https://cloud.githubusercontent.com/assets/13642054/24412751/3a4c6faa-13d1-11e7-9f50-9358a377acc0.png)

**Comment by BluSunrize** [comment]
Looking into it.

**Comment by BluSunrize** [comment]
Found it, thanks for the report ^^
