### ISSUE TITLE
FlameThrower ignores disabled PVP

### ISSUE THREAD

**Issue by Speiger** [BluSunrize/ImmersiveEngineering#1989]
A sever i help out right now, has a Issue where a invisible person runs around with a IE Flamethrower and kills other people.
Thats not a problem in it self.
But the problem is that PVP is disabled.
It would be nice if you could fix that.

To give some help assist this check would be needed if the entity that was hit is a player. (and yes arrows use that to its the Arrow hitcode).
```
if (raytraceresult != null && raytraceresult.entityHit != null && raytraceresult.entityHit instanceof EntityPlayer)
{
        EntityPlayer entityplayer = (EntityPlayer)raytraceresult.entityHit;
        if (this.shootingEntity instanceof EntityPlayer && !((EntityPlayer)this.shootingEntity).canAttackPlayer(entityplayer))
        {
             raytraceresult = null;
         }
}
```
If you dont have time to fix that i could take care of patching it and pullrequest it.

**Comment by BluSunrize** [comment]
I can look into it, sure, but I would point out, that you should probably chuck assholes like that from your server. If people don't respect the rules, they can leave.

**Comment by Speiger** [comment]
xD Its not my server. Its a friend i am helping out. And thats not easy since there is a lot of people on the server. (120 People at peak from what i heard)

**Comment by Speiger** [comment]
An Expected Release date?

**Comment by BluSunrize** [comment]
Nope, no dates, because I'm taking a break atm, lest I burn out. Was put on twitter.

**Comment by Speiger** [comment]
Let me guess 1.11?

**Comment by BluSunrize** [comment]
I have not done any work, at all, towards 1.11
I just need a break from Minecraft in general. I hope to be coming back to it in a two weeks or so.

**Comment by Speiger** [comment]
Ok have fun. I report that back.
