### ISSUE TITLE
Duping Multiblock Structures

### ISSUE THREAD

**Issue by Speiger** [BluSunrize/ImmersiveEngineering#1990]
Sry another thing. Same server xD
On this one i cant really help because i am a noob at multistructures.
But i could investigate that. I doubt that i would find much.

But here are two awesome pics how you could build IE Multistructures.
Issue Report: 

> When right clicking a coke brick structure with an engineers hammer, it goes from:
https://gyazo.com/bb6b68b0cc4496bd63a770e24c813678
to something like
https://gyazo.com/e7b8f2f734e3fd89208ad360c95e79f1 (usually it's a lot more irregular, but it seems to render extra sides to the multiblock)
which basically dupes the coke brick used for the oven, and it can be broken down for a lot more coke oven bricks.
Also happens with the Blast Furnace. 
It also affects Arc Furnaces (https://gyazo.com/8561414be07f391fc28382a53730911a), which can affect the multiblock's functionality.

Really funny bug.

**Comment by BluSunrize** [comment]
Lemme guess: Spigot?

**Comment by Speiger** [comment]
Nope. Sponge 1.10.2

**Comment by BluSunrize** [comment]
Eh yeah. Meant that.
It's a known issue with Sponge. No clue what causes it.

**Comment by Speiger** [comment]
hmmm could be some kind of BlockPosCompression or something... (Its a bad addition i think (Blockpos in itself))

**Comment by pfeiferocks** [comment]
What sponge build are you using?
I have it also with spongeforge-1.10.2-2254-5.2.0-BETA-2264.jar

**Comment by icyevilfantasy** [comment]
after some investigation in the sponge config, i've found a temporary work-arround for this issue (and maybe a hint for the developer)

disable the ´optimizations´-module in ´config/sponge/global.conf´:

```
modules {
  # ...
  optimizations=false
  # ...
}
```

**Comment by BluSunrize** [comment]
The only hint I get out of that is that Sponge still breaks things and I can't cater to that =P

**Comment by mindforger** [comment]
https://github.com/SpongePowered/SpongeForge/blob/c021366e88b97545b53faaf11403489f6fbfac70/src/main/java/org/spongepowered/mod/mixin/core/item/MixinItemShears.java#L137

just did a quick checkup where this option is used

**Comment by icyevilfantasy** [comment]
@mindforger it seems that it fixes both - rendering issue (flickering) and the multi-block duplication

**Comment by malte0811** [comment]
@mindforger you are right, this is caused by the async lighting combined with the fact that IE block light levels depend on the TE. See [here](https://github.com/SpongePowered/SpongeForge/issues/1343#issuecomment-293702318)

**Comment by kyle-mathis** [comment]
Also for anyone who who is on a server and doesn't have access to the sponge configs, if you build it in a box that is pitch black(light level 0) with no light sources, it won't render/form improperly.
