### ISSUE TITLE
Rendering NPE ( turret related? )

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#1991]
So i was tinkering around with turrets in a test world when the server crashed with the below error. This error recurs whenever I attempt to reload the world, making it unrecoverable. At the time i was placing EIO redstone conduits but at least 6 IE Turrets where within LoS and IE is at the top of the crashlog stack.

This occurred on a test world, so I don't mind loosing it; just rather it not recur on anyone's live worlds.
This occurred while in single-player using the Integrated Server

IE build  d6f4f386d43af2c070d2a675eaceeb14bffc20c6 (with that workaround for IEContent.java)
[Full log] ( https://gist.github.com/theunkn0wn1/23dcf6a635f02ea141a55a27f1d5a510)
[Crash-log] ( https://gist.github.com/theunkn0wn1/62b81e9330faae513f3844b6fab3ca25)
Should I also report this to EIO?

Edit: tried to fix grammar...

**Comment by BluSunrize** [comment]
I found this issue already, in my own dev environment. I fixed it too, just haven't pushed it yet.

**Comment by theunkn0wn1** [comment]
Alright then, guess I'll wait for you to push before having another go at it. My apologies for the duplicate.

Btw, are you aware that in some circumstances turrets can shoot through walls?

**Comment by BluSunrize** [comment]
does the bullet actually go through the wall?

**Comment by theunkn0wn1** [comment]
Yep

**Comment by BluSunrize** [comment]
heh, funny
Shouldn't be doing that.
If you can reproduce it, open a new issue.
