### ISSUE TITLE
[Suggestion] Inverted squeezer/fermenter multiblock

### ISSUE THREAD

**Issue by Karmacopper** [BluSunrize/ImmersiveEngineering#1992]
I note whilst playing with these blocks it is difficult to elegantly route their I/O as the both have the same orientation. I would like to suggest either allowing them to be made as they are now or mirrored OR reversing one or other block. This would allow more compact and less resource intense routing as part of a power system.

**Comment by BluSunrize** [comment]
They can be mirrored. You should try it =P

**Comment by Karmacopper** [comment]
Oh really, damn, silly me for not trying it
