### ISSUE TITLE
[1.10.2][Feature Request] Disable machines via cfg

### ISSUE THREAD

**Issue by Redlotus99** [BluSunrize/ImmersiveEngineering#1993]
I love the mod and use it in a few mod packs that I have made and appreciate all the work you have put into it. The multi-blocks are awesome!

With that said, is there a possible way to add the ability to disable certain machines via the cfg file?  At the moment I have to just make whichever machine I want to disable (usually excavator) use an insane amount of RF/t. I would greatly love to see the ability to disable specific machines if the need arises.

**Comment by ToadsworthLP** [comment]
Isn't removing the recipe with Crafttweaker an option?

**Comment by mindforger** [comment]
@ToadsworthLP the machines are multiblocks, you can not disable a part without disabling other machines

**Comment by Redlotus99** [comment]
@mindforger yes that was exactly my issue. I think with having some options to disable certain machines it would be beneficial for the longer running modpacks. I am in the process of making a tech-based modpack with quests and I am attempting to disable all quarries in the pack, but don't have that option with IE, but I really prefer to have IE in the pack being such a great mod.

**Comment by ArukaAlter** [comment]
@Redlotus99 you can remove the ore veins with MineTweaker/CraftTweaker, it's the most direct solution for your problem

**Comment by BluSunrize** [comment]
You can dis/enable them on the hammer. NBTTagLists named "multiblockPermission" or "multiblockInterdiction" can be used to specify a number of strings for the multiblocks. 

the strings are as follows:
IE:ArcFurnace
IE:Assembler
IE:BlastFurnace
IE:BlastFurnaceAdvanced
IE:BottlingMachine
IE:BucketWheel
IE:CokeOven
IE:Crusher
IE:DieselGenerator
IE:Excavator
IE:Fermenter
IE:Lightningrod
IE:MetalPress
IE:Mixer
IE:Refinery
IE:SheetmetalTank
IE:Silo
IE:Squeezer

**Comment by mindforger** [comment]
totally forgot about this, but it still will be listed in the book am i right?

**Comment by BluSunrize** [comment]
Yes it would, since that mechanic is more designed for gating purposes. For packmakers to have recipes that add more NBT to a hammer to allow more multiblocks. Upgrading, if you will.

**Comment by Redlotus99** [comment]
I appreciate the input I'll have to look into how to disable it via the hammer as I'm not that well versed how to do this via the NBTTagLists.

**Comment by BluSunrize** [comment]
You'll have to adjust crafting recipes with Minetweaker/Crafttweaker, effectively

**Comment by mindforger** [comment]
@BluSunrize does modifying the hammer recipe also change the NBT of hammers present in your spawned villager houses? (i honestly don't think so) if not how could one modify them? same for loot chests in this case

**Comment by BluSunrize** [comment]
The houses use loot table files, they're found in the resources like textures and models.
