### ISSUE TITLE
[Feature request] A horse mill and a grinding stone

### ISSUE THREAD

**Issue by Ash70** [BluSunrize/ImmersiveEngineering#1995]
It might be a stretch but would it fit in the 'feel' of this mod to add a [horse mill](https://www.google.nl/search?q=horse+mill&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi8utfO5oHTAhXGyRoKHZ0vDlsQ_AUICCgB&biw=1366&bih=640) and a grinding stone (the stone could be powered by the horse mill or by a water or wind mill). It would give horses and donkeys an extra use (low tech power) and the grinding stone could act as a grinder for ores and wheat?

**Comment by KnightMiner** [comment]
I'm not sure how well it would fit in Immersive Engineering due to the industrial theme (way past horse power), but it might be an idea for [Better With Mods](/BeetoGuy/BetterWithMods) to use with its mechanical power.

**Comment by BluSunrize** [comment]
Eh, I don't think mechanical power fits IE too well, so I don't think this will see implementation.
