### ISSUE TITLE
[Test results] Garden Cloche

### ISSUE THREAD

**Issue by Bitterholz** [BluSunrize/ImmersiveEngineering#1998]
### Working Well:
-  Crop growth triggers no Chunk Updates at all
- Items get auto-exported onto Conveyors
- Cloche with full inventory stops producing (and pauses the animations)

### Issues:
- Model corrupts on chunk updates(Bottom loses texture and/or translucent parts disappear)
- Bars like Water and Power do not update while viewing the Inventory
- Bars like Water and Power display snapshots and only update those every second UI interaction
- Growth animations of tall crops stutters when power is not sufficiently provided and does not "unstutter" when power is sufficiently provided again, until a player interaction
- Crop growth sometimes is behind the output rate, when fertilizer is applied before the growth process starts
- Applying fertilizer items after growth has been started does not recognise the presence of fertilizer for a while

### Possible improvements:
- Limit soil slot item count to a single item
- Limit seed slot item count to 1 and make it accept shift+clicking(later one is not really necessary but handy)
- Maybe slow crop growth animation down instead of making it stutter on insufficient power/water supply

**Comment by BluSunrize** [comment]
Issues, by number:
1) Multipass rendering sucks, see twitter
2) That's why it's got 0 chunk updates =P
3) see 2)
4) I can't really optimize animation based on power? It adds a certain amount to the timer every time it draws power. If it only has enough power every 4th tick or so, yeah it'll look stuttery. It's basically impossible to avoid that.
5) I might be able to sync them up more frequently.
6) That's what the little bar is for. It takes a bunch of water and one fertilizer and fills that bar, then slowly drains it as it grows. When it's empty, it grabs another dosage.

Improvements:
1) It is limited. Shiftclick in Minecraft is broken.
2) see 1)
3) see 4) above.

**Comment by mindforger** [comment]
>If it only has enough power every 4th tick or so, yeah it'll look stuttery. It's basically impossible to avoid that.

you fixed an similar issue already in the past by pausing the process until the internal buffer has reached a minimum power level before restarting operation ("hystersis") to reduce stuttering to a mere on/off toggle every now and then

**Comment by Bitterholz** [comment]
How about slowing the animation by the percentage of power inside the capacitor?
Aka. It needs enough power to keep that growth lamp nice and bright

**Comment by BluSunrize** [comment]
I did things. =P

**Comment by Bitterholz** [comment]
@BluSunrize
Amazing work!
Will rerun test as soon as im home today!

**Comment by omega025** [comment]
With the 0.10-58-73 test build, the flickering problem does indeed seem to be fixed, though the crops, dirt, and bulb are no longer visible through the cloche glass except at its seams (though the wooden base is still visible).

**Comment by Bitterholz** [comment]
New issue just arose, Growth animation and fertilizer use continue even when the Belljars inventory is stuffed.

**Comment by Bitterholz** [comment]
- Glass pieces are now way better looking
- Growth Lamp particle visibilty has improved alot((previously was barely seeable)
- Placing Tiles near the Cloches no longer causes laggy model re-renders
- No noticable FPS impact even with 100 Cloches on screen

**Comment by Bitterholz** [comment]
- Animations are synchronized
- Status Bars are synched

**Comment by BluSunrize** [comment]
Try again with that commit, should prevent rendering if backstuffed.

Jenkins build is here:
http://ci.blamejared.com/job/ImmersiveEngineering-1.10.2/74/

**Comment by Bitterholz** [comment]
@BluSunrize 
### Issue
- Red Sand is not a valid soil for Sugarcane
- Red Sand is not a valid soil for Cactus
- Inserting a Mushroom of any kind to be farmed results in a missing texture Block

### Suggestion:
- Maybe make mushrooms farmable too? Could make them not require Power but more water while being slower than the other crops

**Comment by BluSunrize** [comment]
Mushrooms *are* farmable. No idea why the render is broken :V

I'll look into it, probably the last thing I'll do tonight though.

**Comment by Bitterholz** [comment]
Well at least in my test they didnt result in any Output and had a broken render.

Also, can confirm Build 74 fixes the ongoing animations on stuffed inventory

BUT, now all large crop animations are stuttery(jumping to the a growth stage every ssecond or so)

**Comment by Bitterholz** [comment]
Ill have to correct myself, mushrooms DO grow, but the texture is borked

**Comment by Bitterholz** [comment]
@BluSunrize found an edgecase on the stuffed Inventory. If you remove a stack on items that have a multi output, like e.g. Wheat, it puts in a single items and continues growing but wastes the Items

Iven the same items that should go in the newly free slot get wasted

**Comment by BluSunrize** [comment]
Mushrooms and stuttery renders are fixed.

The slot waste thingy is a pain in the butt to address. In general, checking for the "slot fillability" for multiple outputs is irritating and inefficient. Do you think anyone would really notice that edgecase? =P

Gonan go pass out now.

**Comment by Bitterholz** [comment]
Eh yeah since most people will automate it anyways, i guess that nobody will notice.

**Comment by omega025** [comment]
Another issue with the garden cloches (in test build 75, MC 1.10.2):  I have a setup of 30 cloches growing wheat and sugarcane and everything works fine while the cloches are charging with RF or running off of (depleting) their stored RF.  Once the cloches are fully charged with RF and continue to draw power from the grid, however, my framerate crashes from ~45 fps to 1 or 2 fps and the slowdown persists until I hit the breaker to cut power.  After cutting power, the framerate returns to normal as the cloches run off of stored RF again.

**Comment by MaxHenkes** [comment]
Another bug:
I was messing around with it and changed the cloche to require 2000mb of water:
http://i.imgur.com/7PVRbcD.png
Filled it up completely, and it took 2000mb of water and got started, however when it ran out, it wouldn't drain the next 2000mb for some reason.
http://image.prntscr.com/image/be7b88f38d124e08ae16aebeeef79b45.png

Adding more water solves it:
http://i.imgur.com/YWh8zLP.png

Maybe a rounding error?

**Comment by BluSunrize** [comment]
I found hte issue with the fluid

However, I can't seem to replicate the issue you are describing @omega025. Could you provide screenshots of your setup?

**Comment by omega025** [comment]
The setup is this one:  https://imgur.com/a/Y4Nrx  The photos aren't that great, though, given the space constraints in which I could take screenshots.  If necessary, I could upload the world save.

(For the record, re-tested with 0.10-58-77, and the issue persists.)

**Comment by BluSunrize** [comment]
Could you please replicate the cloche setup clean outside of that factory? Just the cloches + power wires? I want to make sure no external components are affecting it.

**Comment by omega025** [comment]
Hmm, just rebuilt the cloche setup with just power (incl. transformers) and water, and couldn't replicate the fps drop.  The timing of the fps drop was consistently specific to the moment when the cloches hit full charge, though - perhaps it's a more general issue that occurs when having more than a certain number of machines drawing power from the grid after their internal stores are fully charged?

**Comment by malte0811** [comment]
1. What are you using for a power supply? A creative cap?
2. What other machines are connected to the breaker you use to stop the lag?

**Comment by omega025** [comment]
1. Yes, creative capacitor.  Creative capacitor > MV capacitor > breaker > MV connectors > transformers > powered lamps > LV connectors > cloches.
2.  Other machines:  4 capacitors, 10 powered lamps, 2 Assemblers (only 1 running).

To see if the powered lamps were the cause, I just made a copy of the original build and removed all the powered lamps.  Fps drop went to a more moderate 8-20 fps, which is comparable to the 10-30 fps I seem to be getting with the breaker off given everything else going on in the factory.

**Comment by omega025** [comment]
That being said, going back to my 'clean rebuild' and recreating the transformers > powered lanterns > LV connectors > cloches setup (and throwing in 14 extra frivolous ones to test it) doesn't reintroduce the fps drop.

**Comment by malte0811** [comment]
Have you tried loading (a copy of) your build world with just IE? That should remove any non-IE influences. Are there a lot of chunk updates starting to happen when the cloches fill up? Chunk updates are the only way of causing lag I have found so far.

**Comment by omega025** [comment]
@malte0811  Yes - when reloading the build with just IE and no other mods, the fps drop remains (from low 30s to 6-12 fps).

Side note - if I reload the build with IE and Optifine, the fps drop is instead from upper 30s to lower 20s.

What is noticeable now without the other mods, however, is that the powered lamps are flickering on and off when the cloches hit full charge.  I recall this flickering and a smaller fps drop being present with previous builds of IE before the cloches, but never took note of any associations with machines having full/partial charge.  So this might be an already-existing issue unrelated to the cloches and having a large number of cloches just makes it more severe.

**Comment by malte0811** [comment]
I feel like it would be easier to solve this by "local" debugging instead of "remote" debugging. Could you upload the save somewhere? I am running out of ideas here

**Comment by omega025** [comment]
Sure thing.  Would you like the world save from before or after the no-mods-except-IE stripping of non-IE mod blocks?

**Comment by malte0811** [comment]
Since it is happening with just IE and I have neither C&B nor Hatchery installed in my dev-env, the version after loading with just IE should be fine. I'd say just use the smaller one.

**Comment by omega025** [comment]
Here's a dropbox link:  https://www.dropbox.com/s/d17yxuchgzp00n0/Cloche%20-%20just%20IE.zip

**Comment by malte0811** [comment]
Ok, I seem to have misread what you wrote about the powered lamps. I thought you had said that removing them did not change the lag in a noticable way, which appears to be the exact opposite of what you said? That is what was confusing me since flickering lamps are a very plausible cause of lag.
It would be possible to fix this by making the lamp turn on only if the energy buffer is full (but still allowing it to run until the buffer is empty), but I don't think this needs to be fixed. People just have to supply enough power to the lamps or put them in empty chunks, just as with redstone clocks.

**Comment by omega025** [comment]
It strikes me as odd that the lamps weren't receiving enough power in this setup - a creative capacitor and the machinery "downstream" were all able to charge fully, but the lamps weren't?

Even if there is a plausible explanation for the above, surely there's some way of comveying that the lamps aren't receiving enough power that doesn't crash a person's fps and offer few clues as to the problem (considering other machines are able to fully charge).  Could a specialized texture animation showing flickering light lighten the fps load?

**Comment by darkshadow543** [comment]
I was testing the most recent stable commit, and am confused why there is a insert at the bottom, since conveyers don't push into the bottom of blocks, is that a texture thing, or a designed thing?  Also, I thought about making a sneak-peek video on the garden cloche, since it looks nearly complete and am asking permission to do so.

**Comment by BluSunrize** [comment]
Vertical conveyors can insert from the bottom.
Also I know that some people enjoy clean item-transport management.

And yeah sure, make a video.
