### ISSUE TITLE
Crash when placing non-Connector block in space where connector used to be

### ISSUE THREAD

**Issue by MysteriousAges** [BluSunrize/ImmersiveEngineering#2]
... or something like that, probably.

Full crash report: https://gist.github.com/MysteriousAges/1655db896c8600f0921c

**Comment by BluSunrize** [comment]
probably fixed =P

**Comment by MysteriousAges** [comment]
Hrm... Maybe not. ;D

https://gist.github.com/MysteriousAges/2d42929c3c4fcc88c47a

Crash when placing a structural anchor in a spot where LV Connector used to be.

**Comment by BluSunrize** [comment]
Yeah it was ya derp! :D
