### ISSUE TITLE
[Suggestion] Floodlight positioning

### ISSUE THREAD

**Issue by Yusunoha** [BluSunrize/ImmersiveEngineering#2001]
the floodlight is a nice block to light up a large area, but it's always a pain to get the aim right of the light.
would it be possible to add an item, or modify a current item, where you can right-click on a block to save it's position, and use that item on the floodlight to automatically set the floodlight to that position? ofcourse if the aimed position isn't within 32 blocks of the floodlight you won't be able to input that position.

**Comment by BluSunrize** [comment]
It'd be a very one-use item, so I don't really like the idea.
If it were representable in existing IE items (like the hammer being hte configuration tool for everything), yes, but there is no easy way to make it fit. And I don't really see myself adding an extra item for this.
