### ISSUE TITLE
[Suggestion/Request] Dyeable fluid pipes

### ISSUE THREAD

**Issue by nnystyxx** [BluSunrize/ImmersiveEngineering#2002]
More or less what it says, just being able to add a stripe of color to fluid pipes would be nice (rendering in place of the darker gray area) a la how conveyor belts can be dyed. It doesn't necessarily have to affect whether they connect, if that would pose a problem, I just think it'd look cool and help to distinguish what's going through those pipes.

**Comment by mindforger** [comment]
dunno if that feature made it over to 1.10 but in 1.7 you could already color the pipes, but not with a stripe only as a whole (i would prefere that stripe version too) 

it weas never documented as feature but i made a hell lot of use of it

**Comment by bookerthegeek** [comment]
It did not unless it is not a crafting recipe or having to hit the pipe in world with the dye.

**Comment by mindforger** [comment]
oh yeah forgot to mention, you hit the pipe with the dye (vanilla ones and oredicted only work afaik) you can mix yourself any color by applying it multiple times togehter with other colors ... don't quote me on that but i believe it had 8 levels of intensity per color

**Comment by BluSunrize** [comment]
It worked like dyeable armor effectively. It's not in 1.10 as of yet because I initially lacked the capability to do so. I considered bringing it back, but as a more generalized feature:

A paint sprayer for IE so that you don't need to click each pipe 8 times to get the right colour >_>

It's on my ToDo under "Some Time", but I might be able to rush it out for this update...

**Comment by mindforger** [comment]
can i paint my generator in bright yellow then? also, will you add a shader for the generator then? I want an "MAN" Shader for that if possible XD :P

**Comment by BluSunrize** [comment]
God no.
You do realize that the generator is a 128x128 image, right?
For shaders, try multiplying that by 12 or something. mezz would kill me if I took that much space out of the texture map.

Plus, recolouring other stuff is tricky. On the pipes it's simple, they're all light grey, you just slap the colour on. The generator has elements with colour. Airfilters, radiator, the redstone control. Can't just colour those in.

**Comment by bookerthegeek** [comment]
>Mezz would kill me
muhaha... Most likely

**Comment by mindforger** [comment]
>XD :P

well it was a brainfart anyways but i thought i'll leave it for the giggles XD

i well remember the discussion about the texturemap .. i can still can remember the taste of my popcorn :P

**Comment by nnystyxx** [comment]
Ideal execution: a configurable paint sprayer that works on the pipes as well as other dyeable items to replicate the exact color inside, every time, without having to play dye math.
