### ISSUE TITLE
[Test build 0.10-58-72] Crash upon placing redstone wire connector

### ISSUE THREAD

**Issue by omega025** [BluSunrize/ImmersiveEngineering#2003]
When using the test build 0.10-58-72 from Jenkins with MC 1.10.2, placing a redstone wire connector in the world causes MC to crash a split second after the connector's model appears, and the save file can't be loaded by MC again (presumably because the redstone wire connector is still placed in the world).  The launcher gives the following error message:

> The game crashed whilst ticking block entity
>Error: java.lang.AbstractMethodError: Method blusunrize/immersiveengineering/common/blocks/metal/TileEntityConnectorRedstone.getWorld()Lnet/minecraft/world/World; is abstract

**Comment by omega025** [comment]
Er, by 73 I mean 72.  Sorry about that!

**Comment by malte0811** [comment]
Could you post a full stacktrace? I have been using a home-made build about as recent as the latest maven build without issues in development.

**Comment by malte0811** [comment]
Fixed. @BluSunrize the `getWorld` method of the `IRedstoneConnector` interface needs to be renamed to something else, e.g. `getWorldRS`, it would be nice if you could do that.
In a deobf environment the `getWorld` method of `TileEntity` is identical to the one from `IRedstoneConnector`, but in an obfuscated environment this isn't the case: The `TileEntity` version is renamed to something stupid, so Java can't find `getWorld` which is needed for `IRedstoneConnector`. Weird (but pretty logical) bug.

**Comment by omega025** [comment]
Fixed right before I could post the stacktrace.  Points for efficiency.

**Comment by BluSunrize** [comment]
I'll see to it, Malte.
