### ISSUE TITLE
Vehicles

### ISSUE THREAD

**Issue by HappyPineapple** [BluSunrize/ImmersiveEngineering#2005]
hi can you pleas add planes and some mec suits kind of like the things from Avatar or The Matrix: Revolutions & planes I think the parts should be small multi-block structure so say for example : 
the left wing would be assembled and could be modified in the engineers workbench so say you only had one gun you could only put only one gun on the one wing and then place all the parts together so the wings and engine ect.

So could you plz consider this sugestion siriously thanks HappyPineapple_🍍

**Comment by BluSunrize** [comment]
nope.

**Comment by HappyPineapple** [comment]
Oh well thanks any way
