### ISSUE TITLE
Fermenter/Squeezer Pipe Output Locations

### ISSUE THREAD

**Issue by mgwerner** [BluSunrize/ImmersiveEngineering#2006]
Thanks for continuing to develop this mod, I really enjoy the aesthetic.

Using ImmersiveEngineering-0.10-57

With the MC 1.7.10 version, the Fermenter and Squeezer had four faces, and could be attached from any face directly to the sides of the Refinery.  However, now when the two are placed on the left and right of the Refinery, one of them must be placed facing the rear.  This looks fine, but when attaching levers two are on the front and one on the back, from the POV of the player.

Simply aesthetic, not a functionality issue.

**Comment by mindforger** [comment]
if i remember right, you can wrench them to mirror the sides

**Comment by BluSunrize** [comment]
You can just build the structure mirrored. >_>

**Comment by mgwerner** [comment]
OK, thanks for the fast reply.  I tried the hammer, to no effect, will try the wrench.  Cheers!

**Comment by BluSunrize** [comment]
It's always the hammer. It's not after the structure is built. You literally mirror it during the build process. If the pipe usually goes right, it goes left instead. If the barrels are placed on the middle and left row, they go on the middle and right row.

**Comment by AEnterprise** [comment]
@BluSunrize would maybe an button in the book that mirrors the building guide be an option? that makes makes this little known feature more public and easier to make the mirrored structure for those who rarely make them

**Comment by mgwerner** [comment]
I second the suggestion about mentioning mirroring in the manual.  Have been trying to wrench the thing for a while, then saw the new message and the edit.

**Comment by BluSunrize** [comment]
I never edited anything, you just didn't see my message =P

**Comment by AEnterprise** [comment]
i think he's refering to the edit in mindforgers message, he originally said wrench instead of hammer

**Comment by BluSunrize** [comment]
yeah but neither work in the first place and I commented a good 10 minutes before they said "I'm trying the wrench" >_>

**Comment by mgwerner** [comment]
It was the other guy who edited, and I am in China with really bad internet, so my pages take ages to load.  I was fiddling with the hammer for a while when I loaded the page, did not reload before I commented, so did not see BluSunrise'e edit. Sorry for any confusion.

**Comment by AEnterprise** [comment]
doesn't matter realy now i'd say

if you like the mirroring in the book should i open a seperate issue for that since this one is closed and a bit off-topic for it?

**Comment by BluSunrize** [comment]
Too much coding effort for too little benefit tbh. That's one of the things people just "figure out".
I don't see myself adding it.
