### ISSUE TITLE
Bugged out coke oven and reinforced blast furnace, maybe more in FTB Beyond 1.3

### ISSUE THREAD

**Issue by coneyaw** [BluSunrize/ImmersiveEngineering#2008]
Pictures do this more justice than words could. Only the "real" structure is right clickable to access interface.

![](https://puu.sh/vfWQA/59a69788c3.jpg)

![](https://puu.sh/vfozZ/96738bd767.jpg)

**Comment by KaneHart** [comment]
Is this MP and does it have Sponge? If so this is their issue and not IE.

**Comment by coneyaw** [comment]
I did a mod search for "sponge" and no results, yes this is MP, the DevCoFTB servers to be exact.

**Comment by BluSunrize** [comment]
Sponge isn't really a mod, it's a serverside software. Ask your serveradmin if it'S a Sponge/Spongeforge server..

Are you using Optifine?

**Comment by coneyaw** [comment]
no optifine.`I got a "probably" from a member of the server when I asked if it was running sponge.

**Comment by KaneHart** [comment]
I'm pretty sure it's Sponge then can you in game type /sponge tps if that gives you bad permissions or shows the tps then it's Sponge then please close the topic. If it gives you unknown command then let us know.

This the Sponge report:
https://github.com/SpongePowered/SpongeForge/issues/1343

**Comment by coneyaw** [comment]
`

**Comment by iancbogue** [comment]
I tried this on a server that I am on. It doesn't have sponge.

**Comment by mindforger** [comment]
@iancbogue thats nice to know, but do you have the same issue? 

if you do have the same issue, press and **hold** f3+c while ingame (not menu screen) until it crashes and attach the crashlog as file or via pastebin so we have an insight on your modpack and system
