### ISSUE TITLE
Gun Turret does not save cartridges stored in it when exiting game and reloading.

### ISSUE THREAD

**Issue by calloatti** [BluSunrize/ImmersiveEngineering#2009]
IE 0,.10.57
MC 1.10.2

Start a single player game, place a Gun Turret, put some cartridges in it, exit the game.

Start the saved game again, check Gun Turret, no cartridges. Seems like that info is not being saved.

**Comment by malte0811** [comment]
Duplicate of #1978, the fix will be included in the next release.

**Comment by BluSunrize** [comment]
^ this

**Comment by calloatti** [comment]
I searched for Gun Turret and did not find it. Any ETA on new release?

**Comment by BluSunrize** [comment]
it gets released when I'm not teetering on the edge of modding burnout. Check twitter for details.
