### ISSUE TITLE
Feature Request: Make kills by turrets drop XP orbs.

### ISSUE THREAD

**Issue by calloatti** [BluSunrize/ImmersiveEngineering#2011]
Make turret kills drop XP orbs, since they already drop loot.

This would be consistent with vanilla MC behaviour, like for example your dogs killing mobs.

Also it would make it more attractive to use the turrets in mob farms. versus other mods killing contraptions.

**Comment by BluSunrize** [comment]
pretty sure I'd need a fake player for that and wolves are specialcased.
I can look into it, because I legitimately don't know the conditions for XP drop, but I can't guarantee it'll be workable, because I don't intend to use FakePlayers for the turrets.

**Comment by calloatti** [comment]
I suspect it involves fake players. but I dont really know what I am talking about.

Maybe you could check out the killer joe from Ender IO...

Thanks for the reply anyway.
