### ISSUE TITLE
No ores spawning, bauxite, copper, lead, nickel, silver, uranium

### ISSUE THREAD

**Issue by rendrag92** [BluSunrize/ImmersiveEngineering#2012]
Hi
 I cannot get any of the ores listed in title to spawn in my world, I have been into the config files in immersive engineering and change the retrogen to true on all the ore still nothing I changed the retrogen_key from default to true still nothing (I changed it back to default), i have been trying to fix this for 3 days if I don’t have the ores I am unable to actually do anything except make a few machines I can't make a jet pack due to no copper all I need is the ores spawn so I can mine them and eventually make advanced things.
[Doc1.docx](https://github.com/BluSunrize/ImmersiveEngineering/files/913320/Doc1.docx)

**Comment by theunkn0wn1** [comment]
Can you please attach your IE config files, logs, and list of mods/modpack name either as a gist or via pastebin.
What version of IE are you using and is it up to date?
Have you tried deleting the IE config file?
Do the Ores generate in New worlds? 
Do you have other mods installed that mess with oregen?

**Comment by mindforger** [comment]
@rendrag92 please do not post office documents, firstly there are many people out there not using microsoft office at all and secondly they are often abused to spread malware and are generally a security risk

not that i want to say you are spreading malware, but it is not good to send people ms office documents, people tend to lower their guard when usiong them very often over the internet and can get infected more easily by real malicious files

my hint is to use pastebin or compareable websites that allow to paste text for free, so you do not need to use an app to read them :)

**Comment by rendrag92** [comment]
i apologise mindforger first time using github i didn't even know it existed until today

**Comment by rendrag92** [comment]
@theunkn0wn1 i juts had a look after delete the IE config and its seems to of fixed itself the ore has hast started spawning

**Comment by mindforger** [comment]
yeah it was just a general hint for security :D nothing you'd have to apologize

**Comment by theunkn0wn1** [comment]
No problem, glad we're found a fix.

 But yeah, *.Doc/x have no place here and I totally ignored it for the reasons Mindforger stated above.
