### ISSUE TITLE
"You cannot attach this wire here" Immersive Engineering Resonant Rise 4

### ISSUE THREAD

**Issue by AdvitoS** [BluSunrize/ImmersiveEngineering#2013]
So I recently started playing Resonant Rise 4 on the ATLauncher, and focused mainly on Immersive Engineering. I am having an issue where I cannot attach two of the same type of wire to its respective connector on a wooden post. The game tells me that "you cannot attach this wire here" and everywhere I look, no one has the same problem.

BTW: The mod version is the latest (0.10 - 57)

**Comment by BluSunrize** [comment]
Check the manual Connectors accept a single wire. Relays are for the points inbetween.

**Comment by calloatti** [comment]
Connectors (dark brown) are for input and output.

Relays (light brown or green) are for connectring wires together.
