### ISSUE TITLE
Sometimes the ChemThrower turret does not turn towards the target

### ISSUE THREAD

**Issue by calloatti** [BluSunrize/ImmersiveEngineering#2014]
ImmersiveEngineering-0.10-57
Java is version 1.8.0_121, using 64-bit architecture.
Forge Mod Loader version 12.18.3.2272 for Minecraft 1.10.2

See pics, turret fires without moving to point at target

http://imgur.com/a/LVBfL

Mod list:

https://pastebin.com/VzLJ03gh

**Comment by theunkn0wn1** [comment]
Can confirm, if the target is at the edge of the effective targeting range, or manages to increase range to the edge of the turret's firing range it will be shot at but the turret will not turn toward. 
Can reporduce with d199bd0cef4abd48a72bf70f00cc0c2d94f9d475

Easy steps to reproduce: (**! Do this in creative if you want to live !** )
1. Place, power, and arm a turret
2. configure turret to fire at players (target Self!)
3. Move self to edge of firing range and move about the perimeter
4. observe
