### ISSUE TITLE
[request] Concrete connected textures

### ISSUE THREAD

**Issue by Bihlbo** [BluSunrize/ImmersiveEngineering#2015]
I love using the concrete provided by this mod. Because we most often see concrete IRL poured into large slabs, I'd like to be able to recreate that for my buildings. I'd like an alternate form of concrete that has borders just like the concrete tile block, but with connected textures so the borders only show on the edges of a continuous multi-block section of concrete. Like a concrete tile block that is arbitrarily large. I'd also like a second version of this block that looks and functions exactly the same way, but doesn't connect to the first block. In this way I can build a 9x18 floor that looks like it was poured as 3x3 slabs, with borders between each slab, for instance.

I might as well throw this here, but are you planning on using the new concrete powder as a replacement for the gravel in the IE concrete recipe? I vote yes.

**Comment by ml0130** [comment]
@Bihlbo So what you are saying is that you would like to be able to to pour liquid Concrete into a mold and have it be shaped to what you want it to be

**Comment by Bihlbo** [comment]
No. That IS cool. But what I'm saying is that the border on the edges of a concrete tile block looks cool, but it would be cooler/also cool if that border was around all the connected "concrete road" blocks as a whole, using connected textures, instead of around each block. In other words, exactly the same way that Quite Clear Glass from EnderIO works. Make a 3x3, border's around the whole 9 connected blocks but not around each block. Additionally, a second version of the exact same block that doesn't connect, so I can have 2 3x3 structures next to each other with a border around each and along the connection between them.

If you search for "Brutalism architecture" on the web you'll see dozens of buildings made with large slabs of concrete that have a border between them. I want to recreate that using IE concrete.

**Comment by ml0130** [comment]
@Bihlbo I see now what you mean and you are right it would be nice if concrete had connected textures

**Comment by brotazoa** [comment]
Perhaps a system in which the outer blocks of any given pour will have borders once dried, but the inner blocks will be without border. The NBT or Metadata for this would be set at 'dry time'. That way if you want to have a 3x3 slab, you would just have to contain the pour within a 3x3 area. You could then repeat the process using the previous concrete as a containing edge and the borders would remain. Any placed block would simply have borders all the way around without a connecting texture.

**Comment by ml0130** [comment]
@brotazoa that would be nice for a more realistic mechanic witch would work well for #2016. For the texture do you mean basically having a flat texture to were it seems that it's a connected texture but it's not?

**Comment by brotazoa** [comment]
@ml0130 To clarify for texture: Any block resulting from a pour would have connected textures with blocks in the same pour. Meaning that exterior blocks would have borders around the edge and interior blocks would have no borders. Resulting in an area that looks to be one large block of concrete. Any block placed by hand would have borders all the way around, irregardless of neighboring concrete blocks.

**Comment by Bihlbo** [comment]
That makes a tremendous amount of sense!

**Comment by ml0130** [comment]
@brotazoa the makes total seance. That would be nice. Plus having a smooth pour would look better.

**Comment by BluSunrize** [comment]
I won't be doing connected textures for concrete, I'm afraid.
Making it based on the casting is almost impossible and would require a lot of TileEntity work at the very least, and I don't see myself making CTM stuff for it, especially since it would enforce it with no real way to disable it.
