### ISSUE TITLE
[request] Liquid Concrete and Molds

### ISSUE THREAD

**Issue by ml0130** [BluSunrize/ImmersiveEngineering#2016]
On top of #2015 it would also be cool if we had liquid concrete. What I was thinking was being able to make molds and pouring concrete into the molds. If we could do this it would be nice then we could make more realistic building with in the game.

**Comment by Bihlbo** [comment]
That's already a feature! https://youtu.be/BLo-qpHW1CE?t=6m30s

**Comment by BluSunrize** [comment]
^ this?
Fluid Concrete is in the game .-.

**Comment by TheGuyRunningSouth** [comment]
I read it more as asking to be able to put down a block, let's say a stair
mold for example, and pour the fluid concrete in and it would dry into
concrete stairs. It's a cool idea, but I'm not sure how practical it would
be in practice or coding it.
