### ISSUE TITLE
[BUG] conveyor belts not rendering correctly

### ISSUE THREAD

**Issue by LiEyWe** [BluSunrize/ImmersiveEngineering#2018]
conveyor belts are sometimes rendering incorrectly.
http://imgur.com/a/y1PPx

Edit:

MC Version: 1.10.2
Forge Version: 12.18.3.2185

I am playing on a server. This rendering issue appears not everytime. Relogging does not 'fix' this.

**Comment by malte0811** [comment]
As it is right now, we don't know what version of MC you are using (probably 1.10.2, definitely not 1.7.10). We also don't know what precise version of IE and what other mods you use, whether this is on a server, LAN or singleplayer, etc. Please read the contributing guidelines (The CONTRIBUTING.md file) and modify the report to comply with them.

**Comment by LiEyWe** [comment]
Update: This happens only if there are resource packs loaded that do not have IE textures.

**Comment by BluSunrize** [comment]
without debug crash there's nto much we can do here.
