### ISSUE TITLE
[Suggestion] Add a way to make conveyor belts NOT disable when receiving a redstone signal

### ISSUE THREAD

**Issue by PapiDimmi** [BluSunrize/ImmersiveEngineering#2019]
I tried to use a conveyer belt in a setup of mine, but it doesn’t work, because it’s right next to a pressure plate.

My suggestion is to either make the belt ignore a redstone signal when shift + right-clicked with the Engineer’s Hammer ***or*** to add a new type of craftable conveyor belt that ignores a redstone signal.

**Comment by calloatti** [comment]
This please. Also the Excavator lever turning off the conveyor belt setup to get the ore is anoying.

Maybe a config option?

**Comment by PapiDimmi** [comment]
>Maybe a config option?

Nah, I’d prefer to have both the default redstone-deactivated conveyor belts and redstone-ignoring conveyor belts available.

There are already multiple types of craftable conveyor belts, so another one probably wouldn’t be that big of a deal. Or, like I said, its mode could be changed using the Engineer’s Hammer. Either way, it would be very, very useful.

**Comment by Bihlbo** [comment]
I've seen in other mods that the redstone torch can act as a sort of tool for minor things like this. I could see R-clicking a conveyor belt with a redstone torch to make it ignore signals. Without any other reason to ever do that action, I don't think it would conflict, and it keeps you from having to add a whole new thing.

**Comment by AEnterprise** [comment]
the other option would be to just move your belts over 1 block :P

**Comment by PapiDimmi** [comment]
@AEnterprise That wouldn’t work in some setups, including mine.

**Comment by PapiDimmi** [comment]
@AEnterprise That wouldn’t work in some setups, including mine.

What if you have a redstone torch, pressure plate, lever, _etc._ next to a conveyor belt that’s _vital_ to your setup? You can’t move either the redstone source or the conveyor belt, so the only option would be to have a conveyor belt that doesn’t react to redstone signals.

**Comment by AEnterprise** [comment]
unless you are working in an extremely small area you can always move stuff arround, and if the area is to small you can just dig a hole and make the area bigger

a simple solution would just be moving the conveyer line op/down a block or 2

**Comment by PapiDimmi** [comment]
Well, that wouldn’t work in my case, and I can think of many situations where you don’t want conveyor belts to be affected by redstone signal.

Adding a different type of belt that’s craftable and does not respond to redstone signals, or allowing you to switch with the Engineer’s Hammer, would be very useful and probably not too difficult to implement.

**Comment by mindforger** [comment]
and yet again you guess how simple stuff is, feel free to implement it and file a pullrequest :D

**Comment by PapiDimmi** [comment]
@mindforger Oh, fuck off. You know very well that I don’t code Java, yet I still have all the right in the world to claim that something is simple. I know that it’s simple, as I do, in fact, have a brain, but that doesn’t mean that I can file a pull request.

**Comment by BluSunrize** [comment]
Don't tell my contributors to fuck off, that's incredibly rude. Also, I recently added this, so stop bitching.

**Comment by PapiDimmi** [comment]
>Don't tell my contributors to fuck off, that's incredibly rude.

You know what’s rude? Telling me that my opinions and ideas are invalid because I don’t code Minecraft mods; telling me that I can’t think a certain way because I don’t operate in a certain field.

I have been nice until now. I’m tired of being told that I have to file a pull request rather than suggesting features, because otherwise, my opinion and idea is, apparently, invalid. “If it’s so easy, just do it yourself!” That is such an incredibly ignorant thing to say.

**Comment by BluSunrize** [comment]
I think mind was making a point that you cannot claim something to be "easy" if you legitimately don't know how to do it yourself.
As you said, you have no knowledge of Java, so your evaluation of the work effort is unreasoned and neglectable. While poking fun at it might have been unnecessary, replying with "fuck off" is probably not the best approach.

As for it being rude, you used the word "fuck". I believe swearing at someone is considered rude. I'd know this, I do it myself frequently.

**Comment by PapiDimmi** [comment]
>I think mind was making a point that you cannot claim something to be "easy" if you legitimately don't know how to do it yourself.

I said “Adding a different type of belt that’s craftable and does not respond to redstone signals, or allowing you to switch with the Engineer’s Hammer, would be very useful and **probably not too difficult to implement**.” I did not say that it’s _easy_; I said that it’s _probably_ not _too difficult_ to implement. Stop taking my words and twisting them to your liking, just to make me look bad.

Even if I _did_ outright call it an easy task, that doesn’t mean that I would _have_ to know how to do it myself. Compared to more difficult tasks, I assume that parking a bus would not be necessarily a difficult task, yet I don’t know how to do it. Are you going to start a flame war for that, too?

>As you said, you have no knowledge of Java, so your evaluation of the work effort is unreasoned and neglectable. While poking fun at it might have been unnecessary, replying with "fuck off" is probably not the best approach.

I said what I did because @mindforger has crossed the line. If he or she wants to be like sand (coarse, rough, and gets everywhere) once or twice, that’s fine, but being a plague over and over again for the same reasons is rather irritating, wouldn’t you reckon?

>As for it being rude, you used the word "fuck". I believe swearing at someone is considered rude.

Of course it’s rude; that’s why I said it. I wouldn’t say a word like “frick,” would I? That just makes me look like a pussy. Expletives are a way of expressing emotion, particularly anger, and I think I did so quite well.

**Comment by BluSunrize** [comment]
Just cut it mate. Deals done, feature is implemented, arguing gets you nowhere.

**Comment by PapiDimmi** [comment]
I don’t know why you felt the need to chime in. I clearly won this argument, but it was between me and @mindforger to begin with, and I’d really appreciate if he or she would explain if they actually think that saying that something is _probably_ not a difficult task is rude, or if they just want to annoy me.

**Comment by BluSunrize** [comment]
The reason I'm chiming in is BECAUSE IT'S MY ISSUE TRACKER YOU NITWIT.
THIS IS MY FRACKING PROJECT YOU ARE COMMENTING ON.
I'M THE DUDE WHO ADDED THE DAMN THING YOU REQUESTED JUST YESTERDAY.

And mindforger happens to be a valued contributor to this project and I get along with him. So I'm not letting you cuss at him go unnoticed. There also wasn't an argument to "win", you were just being plain rude to someone who notified you of your lack of expertise.
Meanwhile, you've been quite the nuisance to other developers, judging by your activity history on github, so hey guess I've finally had the pleasure then.
