### ISSUE TITLE
[Suggestion] Breaker Switches for LV, MV and HV

### ISSUE THREAD

**Issue by 3TUSK** [BluSunrize/ImmersiveEngineering#202]
So far, we have got some connectors with three tires, and the same as our capacitors. Why not do the same on our breaker switches?
(This idea is from one of my friends.)

**Comment by Kodos-Atoz** [comment]
As of 0.4.0, Breaker switches exist, though there's only one tier that can accept two connections of the same tier (e.g. you can't have a HV wire and a MV wire with the breaker in between)

**Comment by wafflemans** [comment]
also because lazy programmers are lazy

**Comment by Kodos-Atoz** [comment]
Not really sure how this is an example of that, but okay

**Comment by 3TUSK** [comment]
Okay I understand... never mind it...

**Comment by BluSunrize** [comment]
@wafflemans Yeah maybe don't call me lazy on my own issue tracker? Douche.

Breaker Switches in 0.4.0 work for any voltage. But they are literally just switches, not connectors, that's why they only accept two wires and only of the same type.

**Comment by wafflemans** [comment]
Don't worry @BluSunrize I'm really lazy too
