### ISSUE TITLE
Menu Screen goes black when Immersive Engineering is used

### ISSUE THREAD

**Issue by ArchmageAlex** [BluSunrize/ImmersiveEngineering#2020]
Immersive Engineering for 1.10 modpacks breaks my client. It makes my menu screen go completely black. I can click on things, but the screen remains black. In some modpacks it makes the main screen black but with a small version of the background in the bottom left.

It is definitely this mod, removing it fixes the problem. Any idea why this happens or how to fix it?

**Comment by mindforger** [comment]
No idea, you could probably be a more helpful bug reporter if you would post the required information ... There was a Link right at the top to the contribution guidelines when you created the issue. Infos like MC Version, mod Version, other mods involved, forced Crash report kg Holding F3 and C pressed for ~10 seconds ;)

**Comment by ArchmageAlex** [comment]
It happens even with no other mods. Minecraft version 1.10.2.  Forge version 12.18.3.2281. Mod version 0.10-57.  Force report https://pastebin.com/3K8U1TS7

It also happens in -all- MC 1.10 versions of the modpacks Tolkiencraft 3, All The Mods, FTB Beyond, One Elf Squared, to name a few. I can't find anyone anywhere to help me figure out what's going on. 

https://cdn.discordapp.com/attachments/197814484281196545/303337386971103232/unknown.png

**Comment by mindforger** [comment]
This was the log and not the crashlog, from a distance it looks like a corrupted minecraft or resource pack, please make the crashlog like i descrined and post it, you maybe having additional stuff like optifine installed

**Comment by mindforger** [comment]
Also check if your gfx drivers are up to date

**Comment by ArchmageAlex** [comment]
F3 + c isn't crashing my client, I tried 4 different times, holding it for at least 30 secs. Also my drivers are up to date.

The weird thing is that it is -Definitely- IE causing this. No other mods or combination mods causes this. Only when Immersive Engineering is in the mod folder does this happen. Does IE change the menu screen in some way? Is there some setting I can turn off or something to alter in the Jar? I wasn't able to find anything in the config.

**Comment by mindforger** [comment]
Optifine and some other special mods are changing the rendering, they mostly don't document their changes, which makes debugging impossible. Please try it again and start to remove those “optimizing“ mods like foamfix, optifine, fastcraft and other mods that change the menu screen. If you find the combo causing it we hab continue. Currently nobody seems to be able to reproduce this except you

**Comment by BluSunrize** [comment]
for the record: IE does *nothing* with the menu screen. Not a single thing.

**Comment by malte0811** [comment]
You could try updating Java, the version you are currently using is the one included by Mojang which was published either in autumn 2015 or 2014 and is therefore severely outdated.
