### ISSUE TITLE
Shaders in .10-57?

### ISSUE THREAD

**Issue by robertmaxton42** [BluSunrize/ImmersiveEngineering#2022]
Are shaders still obtainable in .10-57? JEI doesn't report the grab-bags existing in villager trades or as a wither drop, and a our wither grinder hasn't produced any over a thousand-ish withers. Am I missing a config option, perhaps?

**Comment by robertmaxton42** [comment]
Hm. IE villagers do sell them, then? I've gone through a half-dozen villagers until they run out of trades without founding even a common one - are they intended to be rare? (Mostly I'm suspicious because I'm running a modpack that's, ahem, known for ineffable config changes and so my first instinct has become to make sure they're not disabled - should I expect to see the village trades in JEI if they're there?)

**Comment by BluSunrize** [comment]
I don't offer any direct config option to disable them.
I am confused as to them not showign in JEI however. Have you checked creative?

**Comment by robertmaxton42** [comment]
The items themselves exist, but JEI normally shows a villager trade as a "recipe" for an item if you can get it from a trade, and indeed things like the iron drills and the engineer's toolbox show up in the list of trades. Grab-bags don't, however.

**Comment by BluSunrize** [comment]
What pack is that?

**Comment by robertmaxton42** [comment]
FTB Beyond... 1.2.1, I believe? Though we've updated incrementally since then.

**Comment by robertmaxton42** [comment]
Would it help if I sent you a screenshot of the JEI tab I mean? I'm in class atm but I can get you one in an hour or two.

**Comment by BluSunrize** [comment]
Might be worth checking their Minetweaker scripts and stuff like that.

I'm fairly convinced taht this is not an IE issue

**Comment by robertmaxton42** [comment]
First place I looked :P. `normal.zs` only mentions IE twice, once to rename Bauxite Ore to Aluminum and once to add tin plates to the the hammer "recipe."

Any other ideas?

**Comment by BluSunrize** [comment]
Not in the slightest.
Thing is, I don't even *offer* an option to disable shaders. :V

**Comment by robertmaxton42** [comment]
Hah. Okay, so it's *probably* just my getting unlucky with trades, though as noted it is weird that it's not in the JEI. I'll go through a few more villages and get back to you.

**Comment by BluSunrize** [comment]
Actually, thinking about it, Vilalgers might not offer them anymore. Don't think I ever readded them to the trade list after the villager profession system was introduced. Guess this could be my bad after all.

Would recommend slaying some dragons or other bosses for now .-.

**Comment by robertmaxton42** [comment]
Hmm... Elder guardians too? The dragon's a pain to resummon, is the biggest problem >.>

**Comment by BluSunrize** [comment]
anything with a boss health bar, effectively.

**Comment by robertmaxton42** [comment]
Heh. That'll do. I'll get to looking for new villages, then :p.
