### ISSUE TITLE
1.10.2 Mixer not working

### ISSUE THREAD

**Issue by LawsOfScience** [BluSunrize/ImmersiveEngineering#2026]
Hey, I have an issue with the mixer.
I have built the mixer and added water into it and made sure that water isn't flowing out of the multiblock. However, once I try to add materials (such as two sand, one clay, and one gravel), the mixer does not do anything. And no, the mixer is not turned off via redstone.
If the mixer is still in dev, please let me know. Thanks for reading, sorry if this has a simple fix and I'm too stupid to see.

**Comment by BluSunrize** [comment]
could you provide pictures of your setup please?

**Comment by LawsOfScience** [comment]
![screen shot 2017-04-19 at 7 03 39 pm](https://cloud.githubusercontent.com/assets/24637919/25205941/303a5fea-2533-11e7-9494-27178637bd4f.png)

![screen shot 2017-04-19 at 7 03 50 pm](https://cloud.githubusercontent.com/assets/24637919/25205932/297ab6dc-2533-11e7-9b50-1f590cddda00.png)

![screen shot 2017-04-19 at 7 06 09 pm](https://cloud.githubusercontent.com/assets/24637919/25205951/46a2cb00-2533-11e7-8802-51b1e92718bc.png)

![screen shot 2017-04-19 at 7 06 04 pm](https://cloud.githubusercontent.com/assets/24637919/25205959/4ecf7f80-2533-11e7-8142-8a59818d7add.png)

Tried with both clay and clay blocks. Hope that helps.

**Comment by BluSunrize** [comment]
Ah, I think it's because there is no space for the output. If the tank is full of water concrete can't be made. But I believe @malte0811 fixed this already for the next release?

**Comment by LawsOfScience** [comment]
Ah, okay. Thanks for the info :)

**Comment by malte0811** [comment]
Yep, fixed as part of #1979. With that fix you won't need to have any free space at all for the mixer to start working.

**Comment by BluSunrize** [comment]
closing this now, since the new release is due soon.
