### ISSUE TITLE
0.10-57 Splitting a cable stack targeting a connector allows you to connect multiple connectors

### ISSUE THREAD

**Issue by deathaplenty** [BluSunrize/ImmersiveEngineering#2028]
Basically, this bug allows you to connect more than one connector to another connector without a relay between, bypassing the "you cannot attach this wire here" error message.

How to replicate:
1. grab a stack of cable
2. right click a connector, setting the entire stack to that connector
3. split the stack; hold right click and drag across your inventory is a good method
4. connect each single wire to as many other connectors as you wish

**Comment by malte0811** [comment]
Duplicate of #1975. Fixed for the next release.

**Comment by deathaplenty** [comment]
My apologies for the dupe. Cheers.
