### ISSUE TITLE
[0.10-57] Arc Furnace texture glitch [not sponge server]

### ISSUE THREAD

**Issue by Cassiobsk8** [BluSunrize/ImmersiveEngineering#2031]
It happened only on the server and only with the arc furnace when it forms it stays that way
http://imgur.com/a/8pHBd

It works normal but when I break a block I need to press "F3 + A" to disappear it

Does not happen in single player
My server is not  Sponge server
All 5 member of the server see the glitch as well

Edit: The problem is solved if you leave the area and come back

**Comment by mindforger** [comment]
Well if it is not sponge, at least list all mods used in the mod folder :)

**Comment by Cassiobsk8** [comment]
Mod list:
https://pastebin.com/qRdTJRvi

**Comment by mindforger** [comment]
Can you test again without extendedrenderer or foamfix?

**Comment by mindforger** [comment]
Also try to use a newer java the version bundled with mc is extremely outdated

**Comment by malte0811** [comment]
And without Optifine?

**Comment by mindforger** [comment]
did i miss optifine in that list??? yes without optifine also please :)

**Comment by BluSunrize** [comment]
Also, it's probably just the usual renderglitch. If F3+A fixes it then so will any block update.
