### ISSUE TITLE
Is there a way to access the Mining Drill GUI? I can't find it.

### ISSUE THREAD

**Issue by calloatti** [BluSunrize/ImmersiveEngineering#2032]
I mean this: (drill.png)

![image](https://cloud.githubusercontent.com/assets/12817862/25314322/08eaf5a2-2818-11e7-8f2b-fc9f039fd1af.png)

**Comment by malte0811** [comment]
Put it in an Engineer's Workbench.
Reminder for either me (when I am done with IW stuff), Blu (when he no longer burnt out) or someone else: The shader slot is overlapping with the rightmost upgrade slot.

**Comment by calloatti** [comment]
Thanks, and sorry for asking a question here.
