### ISSUE TITLE
About the repost of IE

### ISSUE THREAD

**Issue by forestbat** [BluSunrize/ImmersiveEngineering#2033]
I'm an editor of a Chinese （not only for Chinese）minecraft encyclopedia website www.mcmod.cn。Now we want to repost your mod there and we still will direct players to curseforge and clarify the author is you，do you agree to give us the authority？

**Comment by BluSunrize** [comment]
Why not just link to Curse Forge?

**Comment by calloatti** [comment]
@BluSunrize  It seems they just post a description and other stuff and a link to the mod page (curse, etc)

No actual jar downloads.

**Comment by forestbat** [comment]
@BluSunrize Because of the special network（GFW）in China and some people can't log curseforge，and I‘m sorry there are too many new players don't know curseforge。

**Comment by BluSunrize** [comment]
Generally not too happy with rehosting. I'd prefer if CurseForge remained the primary link you offer with a mirror being put down for people that can't access CF. That should ensure everyone still having access.

That said, I oppose all forms of monetization of my content, so stick to that.

Also, I think you should poke the Avaritia devs before using their icon as your avatar >_>

**Comment by 3TUSK** [comment]
> If we had had internationalization support from curseforge for its ui by any chance.
