### ISSUE TITLE
[Suggestion][IE0.10-57] Change amount of potion liquid per bottle.

### ISSUE THREAD

**Issue by Suthek** [BluSunrize/ImmersiveEngineering#2036]
I've been playing around with the mixer and bottler for potion making and I noticed that the bottler uses 333mB per created potion, thus giving us 3 potions per bucket of potion liquid as well as 1mB left in the system, which will prevent the bottler from taking in other liquids and choking the production line until you clear the system by either destroying and remaking the multiblock or using a barrel or TE Tank or something similar to flush the remaining mB out. It'd be much easier if the ratio was changed to either 2 or 4 potions per bucket of liquid.

**Comment by BluSunrize** [comment]
Bottles have always been 333mB. This has been a thing for years and years. A full cauldron can fill 3 bottles, and we don't have float amounts, as such, one bottle stores 333mB. This is the convention everyone has worked with since 1.2.5 or sooner, so I will not be changing it.

**Comment by Suthek** [comment]
Alright, I didn't know about that;  I haven't played many mods using potion generation and didn't make the jump from 3-cauldron uses to 1/3rd mB. That is my bad, sorry. 

As a matter of fact, I wasn't sure how to report this; it's not really a bug as it's working as designed and -- as I now know -- as per norm, but that 1mB (per Bucket of potion) of remaining liquid can still really mess with automation unless one automatically sends a tank or something that can take in an arbitrary amount of liquid down the pipeline to flush it, break the machine or produce 999 potions to get to 333mb of rest liquid for a 1000th complete potion. Even if you refill it with the same liquid, that mB will in the worst case end up in the mixer (since both hold 8 buckets and 1mB is left in the bottler), messing things up there. I mostly just wanted to inform that this issue exists, since I felt that it might not have been what you intended.
