### ISSUE TITLE
Tesla Coil Bug

### ISSUE THREAD

**Issue by whitestarx0312** [BluSunrize/ImmersiveEngineering#2037]
**What is the bug? E.g. "The game crashed with this crash report: <Link to crashlog>".**

When tesla coils are used to kill blazes, they do not drop their items. Tested with naturally spawning, creatively spawned, and spawned from other mods. All other mobs drop their items like normal.

**What did you do to make it happen? E.g. "I threw a revolver into a crusher".**

Setup a tesla coil and place blazes around it.

**Does it happen every time you do this? Does it happen if you do something else as well? E.g. "The game crashes with a similar crash whenever an item that can not be processed in the crusher is thrown into one.".**

Yes, every time.

**Did this happen on a dedicated server (multiplayer servers), in LAN multiplayer or in singleplayer? E.g. "I first noticed this on a server, but it happens in singleplayer as well".**

Singleplayer and on a server.

**What other mods were installed when the bug happened? Crashlogs always contain a modlist, so you can skip this part if you already provided one. You can generate a crash and therefore a mod list by pressing and holding F3 and C for 10 seconds, then releasing. Example: "This happened when playing version 2.4.2 of the FTB Infinity modpack" or "A list of mods can be found here: <link to pastebin/gist/...>" or "Only IE was installed when this happened".**

This is an IE bug. (ImmersiveEngineering-0.10-57)

**Comment by BluSunrize** [comment]
Blazes only drop their items when players attack them.
Much like the chemthrower issue of the same type, I am not entirely certain whether fixing this requires a fake player. I really don't want to have to deal with that, since they are a bit akward.

I'll look into it eventually but I'm not doing dev work atm.

**Comment by whitestarx0312** [comment]
Mmk, that makes sense. I just realized there's a bunch of different mob killing items that wont drop them either. I wouldn't worry about it, seems like a vanilla thing!

**Comment by calloatti** [comment]
You can use an EnderIO powered spawner to spawn them and an EnderIO killerjoe to kill them. Or use Woot

**Comment by BluSunrize** [comment]
Yes although that does defeat the point of asking about the Tesla Coil and wasn't the subject of this issue.

**Comment by calloatti** [comment]
But it solves OP problem. Feel free to delete my comment if you dislike it.

**Comment by bookerthegeek** [comment]
@whitestarx0312 the issue as stated is that blazes will only drop blaze rod when killed by a player. Currently yhe tesla coil does not tell the blaze it is a player when it kills it so that the blaze does not drop rods upon death.

@BluSunrize I guess the question then is the tesla a mob grinder or a base defense device?

**Comment by whitestarx0312** [comment]
Oh boy. There was a reason I wrote the issue off as a vanilla problem and closed the issue so fast. Blaze rods being player only isn't something IE is responsible for and made this issue irrelevant so please treat it as so. (Since technically this is not an IE bug)

**Comment by BluSunrize** [comment]
why the heck are we even elaborating on this any more?
For one, the Tesla Coil is base defense. It always has been. That was the concept when designing it. Mobgrinding  is a secondary, yet mostly plausible function.
Secondly, I've literally said that up top Booker. I explained the issue and whitestar clearly understood me and chose to close the issue in favor of the chemthrower one which is mildly related.

What followed now was uncalled advertising and an effective summary of what was already discussed.
