### ISSUE TITLE
Crash when turret targets mob from Lycanite's Mobs

### ISSUE THREAD

**Issue by Mike-T4** [BluSunrize/ImmersiveEngineering#2039]
Exactly what it says in the title. Targetting certain Lycanite's Mobs, at least the Jabberwock mob. (I did not test every single mob since that would take forever)
Lycanite's Mobs website: http://lycanitesmobs.com/
Crash Log: [rip.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/956418/rip.txt)
Happened on a single-player game, but happens on LAN servers too.
It seems to happen every time. (I specifically tested this with the "Jabberwock" mob)

**Comment by malte0811** [comment]
Probably fixed. I was too lazy to actually install Lycanite's mobs into my dev environment, but the crash makes some amount of sense (At a Java code level, not at a Minecraft code level) and the crash that made sense should not happen any more.
