### ISSUE TITLE
Crash when using debug world

### ISSUE THREAD

**Issue by NicosaurusRex99** [BluSunrize/ImmersiveEngineering#2040]
Title sums up the error, probably an issue loading a block

https://paste.ee/p/cYI6g

Video to show how to get the debug world

https://youtu.be/EHqr9vBau3o?t=2m55s

**Comment by BluSunrize** [comment]
Can you reproduce this without the codechicken mods?

Also, given that it's the Debug World, not really an issue people would commonly encounter :V

**Comment by NicosaurusRex99** [comment]
sorry for my delay i ran out of internet, ill give it a shot

**Comment by NicosaurusRex99** [comment]
Was able to recreate with just IE installed https://paste.ee/p/Ill9d
