### ISSUE TITLE
[0.10-57] Empty casing dupe

### ISSUE THREAD

**Issue by le0z00s** [BluSunrize/ImmersiveEngineering#2042]
When using revolver with extended magazine and speedloader, after you reload a gun, you receive 14 empty casings instead of 8. The revolver itself still has 6 empty casings inside which gives you 6 free casings after every reload.

At first I thought that I either can't count or I'm seeing things, but after re-logging and loading new set of 38 bullets (revolver + mag + 3 speedloaders) and shooting them all, I ended up having 56 empty casings.

**Comment by malte0811** [comment]
Fixed, as well as 2 desyncs in the revolver GUI.
