### ISSUE TITLE
[1.10.2] 0.10-57 blast furnace texture bug

### ISSUE THREAD

**Issue by WildKarrade** [BluSunrize/ImmersiveEngineering#2045]
So there's no crash, server error, and anything related to this just you get this visual bug when hitting the blocks with a hammer to form a furnace. It still works like this, it just visually offsets and you can walk through it.

http://i.imgur.com/AXe5JrZ.jpg

**Comment by malte0811** [comment]
If it is a SpongeForge server, this is a duplicate of a lot of other issues. This is (AFAIK and IMO) on their side to fix since they are multithreading stuff that usual runs on a single thread.
Btw, you can include pictures in your bug report by dragging them into the editing field.

**Comment by WildKarrade** [comment]
I did not know that you could include pictures so thank you! And it is a SpongeForge server, unfortunately that seems to be the only way to get decent performance now from my testing as of late. Thank you for the information.
