### ISSUE TITLE
[1.10.2] [0.10-57] Crash with Turrets and Explosive Cartridges

### ISSUE THREAD

**Issue by cybercat5555** [BluSunrize/ImmersiveEngineering#2046]
I placed the HE rounds in a turret to test something, and it worked fine for a bit, then after a while, I got this crash: https://pastebin.com/mjjWufb8 . Its also worth noting I got the same crash by trying to invert a turret containing the same type of ammo. I saw the message saying the turret has been inverted, then it created the same crash.

I don't see IE mentioned in the crash report, but the crash occurred shortly after the turret fired. Sorry in advanced if its not an IE issue

**Comment by theunkn0wn1** [comment]
Does this occur without FoamFix?

**Comment by cybercat5555** [comment]
Yes, same crash with the same trigger, even without Foamfix

**Comment by theunkn0wn1** [comment]
hmm, I am unable to unable to reproduce using 10-58 built against 0bec35d0f562120401672289ccdffd9c180cbec0

I loaded and powered a turret with High-Explosive cartridges and sent it against a few hundred Zombies and was unable to induce your crash. I also tried inverting the turret's redstone control with the ammo inside and was also unable to reproduce. 

----------
 Please note that your Java install is also out of date, logs reporting version `1.8.0_25` when the current version is `1.8.0_131`; can you please try updating java and reproduce?

---------
Does this issue occur with just Immersive Engineering and its dependents or only within this pack?
If it occurs only inside the pack, its probably a mod conflict.
That is quite a huge modpack you have there, is that a public pack pack? if so, can you please provide a link so i can help determine if it is a mod conflict.

**Comment by cybercat5555** [comment]
It seems that updating Java has fixed the crash, seems to be working properly now, thanks for the help!

**Comment by cybercat5555** [comment]
Hm, it seems the crash has returned, however from a different source-I accidentally redirected a damaging (red) Refraction laser onto a turret, which then caused the crash, but I removed IE, which seems to have fixed it, I can re-enter the world that I previously could not re-enter, so it may be linked to the turrets somehow getting "damaged", from either the splash damage from the HE rounds, or the fire damage from the laser, which can ignite blocks.

**Comment by BluSunrize** [comment]
What's your System language?

**Comment by cybercat5555** [comment]
excuse my noobishness, but how do I find that?

**Comment by malte0811** [comment]
What language is Windows in? When you try to shut down your computer, does it say "Shutdown", "Herunterfahren" or what?

**Comment by cybercat5555** [comment]
wow, I have no idea why that didn't occur to me, but its in english
