### ISSUE TITLE
[request] auto reload for the revolver

### ISSUE THREAD

**Issue by ImelchorI** [BluSunrize/ImmersiveEngineering#2047]
its a pretty stylish weapon, and id love to use it more. only thing that irks me is the way you have to reload it manually by shift right clicking, taking the casings out and putting new bullets in.

i know there is the speedloader, but those dont stack.

i wonder if it would be possible to just carry the bullets in your inventory, and right clicking with an empty revolver plays a couple seconds long animation where the it gets reloaded.

the speed loader would simply speed up this animation and make it almost instant. so it would still be very useful in a pinch.

maybe it would even be possible to have a reload button.

**Comment by BluSunrize** [comment]
The speedloader is the fast way, sneak+rightclicking and doing it in the GUI is the slow way. Both already exist.

**Comment by ImelchorI** [comment]
yes, i just thought it would be a nice quality of life addition.

technically it wouldnt change much with a loading animation. it would still take a couple seconds to reload the gun, and go much faster with a speed loader.

but you wouldnt have to open up the interface and fiddle around with the inventory.

**Comment by BluSunrize** [comment]
Well, animation is not easily done anyway. Rendering in 1.10 is still way to shit to support that.
Number 2, if you do it without the GUI you have no control over which bullets are loaded and have fun shooting flares when you needed armorpierce.
Number 3, it's not that bad in the GUI. You can trippleclick to grab all the empties and shift-click on the fresh ones to load them all in one.

While the suggestion is appreciated, I will not be adding this.
