### ISSUE TITLE
Suggestion: More uses for Slag

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#2048]
Especially since the mixer brought on a very clay conserving way of creating concrete, slag is mostly a throwaway byproduct now.
So i did some googling and wikipedia diving and basically historically slag could be resmelted for additional metal gained, which i personally would find redundant, or it could be turned into slag glass.
Sooo I'd suggest introducing non- or barely translucent slag glass blocks :) colorable, with a bit of a swirl to it maybe. I mean there's google images for pictures of slag glass. I think it looks pretty :)
Mostly just for looks, but you could turn it into a requirement or a cheaper recipe for the HV relays. Or whatever else can be come up with.

**Comment by ArukaAlter** [comment]
IC2 slag can be reprocessed into some coal dust and a small pile of gold dust (equivalent to one nugget), it's a valid patch.

**Comment by Bihlbo** [comment]
Another easy method to increase the utility of slag would be to simply add the ability to throw it into the crusher for sand.
