### ISSUE TITLE
Finishing a multiblock with the hammer only works from one side

### ISSUE THREAD

**Issue by TomyLobo** [BluSunrize/ImmersiveEngineering#2051]
1. Place blocks for the automated workbench multiblock structure
2. Stand on one of the engineering blocks
3. Right-click the central treated wooden slab
Expected behaviour: Multiblock is finalized
Actual behaviour: Nothing happens

Solution:
Iterate over the 4 cardinal directions by putting loop here:
https://github.com/BluSunrize/ImmersiveEngineering/blob/6a5adc5eb15749efc12918a11ca4d806639c7e3f/src/main/java/blusunrize/immersiveengineering/common/items/ItemIETool.java#L194
I submitted a PR (#2052) with the necessary changes.

A video highlighting the issue is available here: https://youtu.be/1i6YThFW8lI

**Comment by BluSunrize** [comment]
We've already had this discussion on irc. The answer remains the same.

**Comment by TomyLobo** [comment]
Well your reason was that I was only 1 out of 995k downloads who was having this problem.
That is why I opened this issue so you can get some more voices on this subject.

The reason why you should fix a bug is because it's the right thing to do, not because people are complaining about it to you personally.

I've made it as easy as possible for you to do that. All you need to do is merge that PR.
I even stuck to your ridiculous whitespace policy (tabs and everythingcrammedtogetherwithnospaceswhereeverpossible), so you wouldn't be able to object on that basis.

**Comment by TomyLobo** [comment]
A summary of our IRC conversation about the topic:
First of all I introduced the issue, using screenshots and by describing what I observed:
* `<TomyLobo> http://ctrlv.in/949523 ok so i got this thing constructed... now where do i click?`
  `<TomyLobo> http://ctrlv.in/949524 this is what it looks like from below`
  `<TomyLobo> i rightclicked, leftclicked and shift-rightclicked every single block there`

With no reply on the channel, I later figured it out on my own, but still consider it a bug and took the steps I could in order to guide other people around it:
* `<TomyLobo> oh, it depends on the direction you face`
  `<TomyLobo> now that is seriously unintuitive`
  `<TomyLobo> amended the wiki accordingly`

When finally someone replied, I described the issue in more detail:
* `<TomyLobo> [apparently,] whether the machine can be hammered into its proper shape depends on the cardinal direction you're facing`
    * `<BluSunrize> [That you have to stand in front of the machine] is made quite obvious I feel by the render in the manual.`
      `<BluSunrize> it also works if you stand infont of it `
      `<BluSunrize> and if you click the little box button it shows a render of the active structure`
      `<BluSunrize> which usually serves as a guideline to where "the front" is`
        * `<TomyLobo> that 3d view is rotatable`

Since I'm of the opinion that software should just work, I made a suggestion on how to fix the issue (basically automating the way I solved the issue for myself :)):
* `<TomyLobo> cant you just [automatically] try all 4 directions instead of just one?`
    * `<BluSunrize> no, I can't because that's infinitely more codework`
      `<BluSunrize> structuredetection is already a pain in the ass`
        * `<TomyLobo> huh?`
          `<TomyLobo> let me take a look`
          `<TomyLobo> https://github.com/BluSunrize/ImmersiveEngineering/blob/6a5adc5eb15749efc12918a11ca4d806639c7e3f/src/main/java/blusunrize/immersiveengineering/common/items/ItemIETool.java#L194 just put a loop there`
          `<TomyLobo> loop through the 4 cardinal directions, done`
            * `<BluSunrize> nah. It works as is`
                * `<TomyLobo> it would work better with virtually no extra code complexity`
                    * `<BluSunrize> it would work the exact same, really`
                      `<BluSunrize> quite an edge case issue`
                      `<BluSunrize> given that literally noone else has ever complained about this.`
                      `<BluSunrize> I'd rate 1 in 995k downloads an edge case ^^`

Frustrated with the lack of care on @BluSunrize's part, I questioned his dedication to certain aspects of software quality:
* `<TomyLobo> well either you care about UX or you don't`
    * `<BluSunrize> Oh, I very much do`
      `<BluSunrize> that's why I tell people to RTFM`
      `<BluSunrize> instead of using some 3rd party wiki that's probably full of misinformation`
        * `<TomyLobo> it's not IN the manual`
          `<TomyLobo> on the wiki there's at least the info about the hammer`
          `<TomyLobo> and where to hit the machine`
          `<TomyLobo> (and now that i edited it, also the information about orientation)`
            * `<BluSunrize> well, it appears that the majority of players just, I dunno`
              `<BluSunrize> experiment a bit?`
              `<BluSunrize> learning by doing?`
                * `<TomyLobo> well if you document 95%, and someone does everything correctly, they will assume they did something wrong`
                  `<TomyLobo> not that there is some step missing`

I'd like to expand on the UX part a bit:
If your users need to read the manual in order to get your software working, you have lost on the UX front.
Do you need to read a manual in order to operate Microsoft Word? Nope, the basic functionality is all there in the main interface and you can start writing text right away.

It doesn't even care whether I click a button coming from the left, right, top or bottom.

Since you're unwilling to fix this issue, I hope the next user who runs into the same issue will find my note in that "3rd party wiki that's probably full of misinformation".

**Comment by theunkn0wn1** [comment]
@TomyLobo ... just stop, please. 
You appear to be the first person to have reported this as an issue, over the entire lifespan of IE, that does qualify an edge-case.
Over the course of using this mod, and intentionally seeking out to break it, I have not encountered this issue. The Multi-block formation seems perfectly intuitive and, imho, does not currently require fixing.
>If it isn't broke: Don't fix it

-------
I thank you for taking the effort for identifying a bug within IE and offering a fix to the community, We do appreciate it. (Even if Blu met it with the cold shoulder...) As this is an edge-case and has not been priorly reported even though it has existed for some time, it has been seen as not necessary to merge your PR. I must advise against engaging in hostilities against Blu, it is completely pointless and needless.
