### ISSUE TITLE
[Minor] Suggestion: Squeezer Recipe for Packed Ice

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#2053]
4 ice in the squeezer = 1 packed ice, 3 buckets of water
cosmetics and uses for non-melting ice aside, the super rare packed ice is the most efficient coolant for thermoelectric generators, so worth getting :) also one more use for the squeezer, yay

**Comment by BrisingrAerowing** [comment]
A quick and dirty (and untested) CraftTweaker script to add this:

``` text
import mods.immersiveengineering.Squeezer;

val packed_ice = <minecraft:packed_ice>;
val ice = <minecraft:ice> * 4;
val water = <fluid:water> * 3000;

# Change the 200 to whatever energy usage you want.
Squeezer.addRecipe(packed_ice, water, ice, 200);

```
