### ISSUE TITLE
Suggustion: Railgun turret

### ISSUE THREAD

**Issue by darkshadow543** [BluSunrize/ImmersiveEngineering#2054]
We have turrets for the revolver and the chemical thrower, so why not the railgun.  The idea is to make it a long range turret, but it does not target in a 10-20 block radius around it.  Not only that it consumes a lot of power since, you know, the high powered electro-magnets, and before I forget, add the charging time.  Also, it would be interesting if fired rods shattered glass and penetrated soft blocks, anything you can break with your fist, like dirt, leaves, gravel, ect.., and lose momentum in the process.   Its just an Idea

**Comment by BluSunrize** [comment]
Not yet. ^_^
