### ISSUE TITLE
 [1.10.2][0.10-57] Immersive Engineering Conveyors can't insert into Railcraft Inventories

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#2055]
i don't know if i maybe could crossreference the complete issue and not just via comment :x https://github.com/CovertJaguar/Railcraft/issues/1190

**Comment by malte0811** [comment]
Since they are using an inventory type that has been outdated for about a year now, I would consider this to be a "wontfix", but Blu will have to decide that.

**Comment by BluSunrize** [comment]
Oh this is abso-fucking-lutely a "won't fix"
I mean, if the RC folks are going on record saying "We're not gonna use Forge's inventory system" then by all means, they can stay unsupported :D

**Comment by calloatti** [comment]
>abso-fucking-lutely

How professional...

**Comment by MalkContent** [comment]
this is a hobby and not a profession :P

**Comment by BluSunrize** [comment]
I never claimed to be professional! I'm just a reasonably skilled amateur =P

**Comment by MalkContent** [comment]
well RC guys seem to have a problem with the current state of the cap
sadness. welp. translation hoppers it is
