### ISSUE TITLE
Blast Furnace Preheater Not Working

### ISSUE THREAD

**Issue by Gamemaster2198** [BluSunrize/ImmersiveEngineering#2056]
I'm not sure if this is supposed to be but the Blast Furnace Preheater doesn't work for some reason, I added power, connected to an Improved Blast Furnace, tried making steel, but both preheaters did not activate at all. Also I'm running the latest version of IE.

**Comment by BluSunrize** [comment]
How are you determining them to not be active? The only way to tell is by production going faster.

**Comment by Gamemaster2198** [comment]
Oh... sorry for wasting your time BluSunrize. my mistake
