### ISSUE TITLE
Forge launcher freezes and crashes on startup with Tinker's Construct.

### ISSUE THREAD

**Issue by ExAdventurer** [BluSunrize/ImmersiveEngineering#2057]
[fml-client-latest.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/973511/fml-client-latest.txt)

[fml-junk-earlystartup.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/973512/fml-junk-earlystartup.txt)

[latest.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/973516/latest.txt)

**Comment by mindforger** [comment]
There is no crash in your log an nothing that points to IE beeing the culprit. Can you post a crashlog please? Just a shot into the blue, you have an nvidia gfx card? And minecraft does not start anymore?

**Comment by malte0811** [comment]
From the log I'd say MC is starting and then freezing in one of the model loading phases. I wanted to compare the fml_latest log to one of my own logs (since this mod combination works for me), but MultiMC apparently decided that generating those logs would not be necessary, so I didn't.

**Comment by mindforger** [comment]
nah i suspect the nvidia driver issue, but there were a couple of new versions inbetween, it seems odd that it pops up just yet, unless he plays minecraft the first time since this one version

**Comment by malte0811** [comment]
I know about the driver issue, but I thought MC would just crash as soon as it tries to init OpenGL and not in the middle of loading models?

**Comment by Pihrra** [comment]
From the first file he appears to use a ATI Radeon HD 2400 Pro.
Holy s#it this thing came out 10 years ago.
