### ISSUE TITLE
[1.10.2] [0.10-57] Blast Furnace smelting progression bug

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#2058]
You can start smelting an iron ingot and replace it with an iron block. It will then take the smelting time and ressources to turn an iron ingot into steel, but output a block of steel.
While this is open to some cheesy abuse by people who want to save on charcoal/coke, this works the other way around, too, resulting in a very pricy steel ingot that you have to wait for forever.
To make this work, you have to switch the items directly. You can't pull the item inside the blast furnace out, then put the other item in.
Issue present on both regular and improved blast furnace.

ie 0.10-57
forge x2272

**Comment by Gamemaster2198** [comment]
Thanks! It worked, except the visual didn't work... But it worked still, thanks dude!

**Comment by malte0811** [comment]
Fixed.

**Comment by MalkContent** [comment]
:D well i didn't search closed tickets :x
