### ISSUE TITLE
[Minor] Suggestion: Replace Hopper in Dropping Conveyor Recipe with Iron Trapdoor

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#2059]
Mostly just because i think it feels fitting. (both flat, dropping conveyor has no inventory and also just drops the stuff if there's nothing underneath)
close at will

**Comment by Bitterholz** [comment]
The Dropping Conveyor actually serves as a Hopper in terms of Item insertion. So the Hopper as requirement is quite logical I think.

**Comment by MalkContent** [comment]
yea, but conveyors already can insert. the only thing special to the dropping one is, that it will go down if it can and straight otherwise

**Comment by BluSunrize** [comment]
Yeah tbf, I totally forgot Iron Trapdoors were a thing.
Saves an iron ingot, as well as the hassle of making a chest, so I think this is a sensible balance change ^^
