### ISSUE TITLE
[Suggestion] Allow single fluid refining with the refinery

### ISSUE THREAD

**Issue by SynfulChaot** [BluSunrize/ImmersiveEngineering#206]
Would it be possible to allow the refining process with only one fluid input for those of us that want to use the IE Refinery for BC fuel refining?

**Comment by BluSunrize** [comment]
Not without rewriting the entire thing, no.

**Comment by XFactHD** [comment]
@BluSunrize couldn't you just use water as second input (I know that this is not what the initial post asks for)?

**Comment by BluSunrize** [comment]
Yes. you could. I won't. There's minetweaker for that. DIY. How you solve it is not my concern. but I will not rewrite the Refinery just for BC fuel.
