### ISSUE TITLE
Detecting conveyer[Idea/Suguestion]

### ISSUE THREAD

**Issue by darkshadow543** [BluSunrize/ImmersiveEngineering#2066]
An idea to increase control of production is to add a detecting conveyer, which released an output when an item is on top of it.  With the new garden cloche, this would be handy as some plants grow faster than others.  Idea for a recipe is to have a conveyer and a wooden pressure plate.

**Comment by MalkContent** [comment]
strip curtains detect items passing through :)

**Comment by TheGuyRunningSouth** [comment]
THAT's what those do.

**Comment by BluSunrize** [comment]
![image](http://puu.sh/vJryz/03e7b8c952.png)

Yup.

**Comment by darkshadow543** [comment]
How do I get the signal out of those?  In the beta I'm testing, it does not read out a signal

**Comment by darkshadow543** [comment]
![2017-05-08_22 20 12](https://cloud.githubusercontent.com/assets/14943673/25833063/b2fbd450-343c-11e7-8273-c2ae63775811.png)
This is my set up

**Comment by MalkContent** [comment]
It only applies the weakest of signals to the block it is placed against, meaning you can only capture it if you put it direktly into a redstone sensitive block. In vanilla+ie, your best bet would be to use a Redstone Wire Connector (even though that might look a little silly).
Kinda forgot about that, would have added that, otherwise, sorry.

**Comment by BluSunrize** [comment]
Right, yeah, they only do weak signal.

That change was made because if they emitted a strong signal to the block attached to, they would stop the conveyor below them.
Given that there is a redstone-immune conveyor now, anyone got any objections to me making it a strong signal again?

**Comment by MalkContent** [comment]
Nope, sounds good :)
Maybe also make it give out a signal to the sides of it, where darkshadow tried to grab the signal here? not sure about that one though.
