### ISSUE TITLE
[0.10-57] Engineering Hammer mining speed issues

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#2067]
Normally the engineering hammer breaks down IE blocks fairly quickly, but sometimes it takes very long.
I mostly notice this with scaffolding, but this affects other blocks, too.
I can't seem to find a system behind it, but I am assuming that this is not intentional.

Sidenote: It'd be neat if the hammer could receive the efficiency enchant, or if there was a powered hammer or something, so the hammer would stay relevant for building with scaffolding, rather than being outshined by enchanted picks :)

Mods:
ImmersiveEngineering-0.10-57
Railcraft_1.10.2-10.1.1
OpenComputers-MC1.10.2-1.6.2.7
SuperCircuitMaker-1.0.4
chiselsandbits-12.12
jei_1.10.2-3.14.7.416
MCMultipart 1.4.0
AppleCore-mc1.10.2-2.1.2
AppleSkin-mc1.10.2-1.0.5

forge x2272
MC 1.10.2

**Comment by BluSunrize** [comment]
Well it's not designed to work on everything.
It's mostly aimed to break machines quickly, not decoration blocks

**Comment by MalkContent** [comment]
Yea, but sometimes it works, other times it doesn't, for the same blocks.
I'm talking about steel scaffolding and engineering blocks.

**Comment by MalkContent** [comment]
can't reproduce anymore
