### ISSUE TITLE
Item Router Sorting Issue

### ISSUE THREAD

**Issue by whitestarx0312** [BluSunrize/ImmersiveEngineering#2069]
**What is the bug?** 
I setup an item router but it doesn't seem to be respecting my filters. Specifically, I setup sand to go the green route and for some reason it just keeps spitting it up (white route). I Even tried to block the white route by specifying an arbitrary item but it still outputs items to the white route.
http://imgur.com/a/hbU0q
**What did you do to make it happen?** 
Specify an item to go to the green route, block all outer routes, it will output the item to the white route.
**Does it happen every time you do this? Does it happen if you do something else as well? E.g. "The game crashes with a similar crash whenever an item that can not be processed in the crusher is thrown into one.".**
Yes, this happens even with items other than sand.
**Did this happen on a dedicated server (multiplayer servers), in LAN multiplayer or in singleplayer? E.g. "I first noticed this on a server, but it happens in singleplayer as well".**
Tested in singleplayer, but I assume it happens in multiplayer.
**What other mods were installed when the bug happened?** 
ImmersiveEngineering-0.10-57
https://pastebin.com/QePDqe4c

**Comment by BluSunrize** [comment]
Actually not an issue with the item router, but with the crusher. It's outputting to the wrong side.

Will be fixed.
