### ISSUE TITLE
Crash with Garden Cloche and Ender Lily

### ISSUE THREAD

**Issue by angelnc1989** [BluSunrize/ImmersiveEngineering#2071]
Minecraft: 1.10.2
Forge: 12.18.3.2281
IE: 0.10-58
Singleplayer - Creative Flat World

Game crashed with this crash report: https://pastebin.com/cXbHnx7W

It happened when I shift-clicked an Extra Utilities 2 Ender Lily into the Garden Cloche.
The world now crashes everytime on loadup.

**Comment by mindforger** [comment]
i would love to see the reason, looks like someone hijacked the renderer and used a list type that does not support the addAll function
do you have foamfix or optifine present? (not as far as i can tell fomr the crash report, just asking to be sure)

**Comment by malte0811** [comment]
This isn't anything weird, it is just the enderlily returning an immutable list of quads. The Connection models do the same I think, Blu changed that there. Should be pretty trivial to fix since it just requires making a new arraylist from the old list.

**Comment by mindforger** [comment]
yeah thats what i thougt i just was under the impression the renderer were supposed to return a mutateable list

**Comment by angelnc1989** [comment]
No foamfix or optifine.

**Comment by Shadowhunter82** [comment]
Hey
Will there be a fix for the 1.10.2 version of IE to?
Greeds
Shadowhunter82

**Comment by BluSunrize** [comment]
When I get around to it...

**Comment by Notawallplan** [comment]
This bug can actually brick areas on a server since it actually works fine... except for the fact that you can crash if you load the model up in your render distance.

**Comment by Zendreax** [comment]
So uh... 
This bug can be abused to the point of shutting down beyond servers.

**Comment by BluSunrize** [comment]
Well it doesn't shut down the server, it just crashes the clients. It's a clientside only issue.
If you have a user on that server who is abusing this, you probably want to talk to your admin to get that asshole off your server =P

**Comment by Zendreax** [comment]
If someone places a cloche directly infront or within rendering distance of the new player spawn, any user that logs in immediately crashes, anyone from across the world is oblivious and goes within render distance of the cloche, they crash. A server admin (not knowing that it will crash him) goes to try to remove the clock, then crashes as well. (all this actually happened lol)

**Comment by malte0811** [comment]
We discussed this on IRC for a bit yesterday: I agree with you that a new 1.10 build would be nice, but I can't do anything about it. It isn't as bad as you describe it though: The crash log contains info on the position of the cloche (line 59 in the OP's log). By running `/setblock minecraft:air` (from the server console if all admins are in range for crashing) on those coordinates the crash should be fixed.

**Comment by Notawallplan** [comment]
But a new 1.10 build is required to add in the custom models or support.
Tema uses a wierd crop render which makes it do the same thing it does to
saplings instead of the normal crop render.

On May 29, 2017 1:43 AM, "malte0811" <notifications@github.com> wrote:

We discussed this on IRC for a bit yesterday: I agree with you that a new
1.10 build would be nice, but I can't do anything about it. It isn't as bad
as you describe it though: The crash log contains info on the position of
the cloche (line 59 in the OP's log). By running /setblock minecraft:air
(from the server console if all admins are in range for crashing) on those
coordinates the crash should be fixed.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/BluSunrize/ImmersiveEngineering/issues/2071#issuecomment-304576923>,
or mute the thread

**Comment by BluSunrize** [comment]
Except we already established that it's not Tema's fault.

**Comment by lassehknudsen** [comment]
I have seen the crash with in the Invasion modpack, when i placed a enderlily on endstone inside the gloche. I dont know if this adds, is there any workaround i can use, this is single player. And i crash each time i load, with the first crash right when i placed the lily in the gloche

**Comment by bbqx** [comment]
lassehknudsen, the only option I know of is to use the program mcEdit to replace the Cloche with dirt or stone. The you should be able to use your world again. 

Garden cloche is an awesome addition to the Immersive Engineering and seems way more server friendly then huge fields of plants every where,
Thanks again to BluSunrize for bringing imagination and coding skill to the moded Minecraft community.

**Comment by TheGuyRunningSouth** [comment]
If you're lucky enough to know it's coordinates,  you could /setblock air
it from server console. Or, if you know the general area and don't care
about a bit of overkill, you could always start small and slowly expand the
area you're clearing until you remove it.

**Comment by malte0811** [comment]
You don't need to be lucky and you don't need to clear the whole area. As I said in my previous comment the exact position of the cloche is in the crash report (I gave a line number for the OP's crash, look for a similar line in your log). You will need to set that block to air, using setblock or MCEdit or whatever method you want. The upper blocks of the cloche will still be there, but they shouldn't crash, you should be able to break them by hand.
