### ISSUE TITLE
[0.10-0.58] Cloche Comments

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#2072]
- Grass in the Cloche renders grey
- Melons output whole, which is neat, but IE offers nothing to automatically break them and use them for autocrafting (i.e. harvestcraft food, potions). Maybe at recipe that turns them into slices? (melon + bayonett? ^^)
- Mushrooms can be grown on Mycelium, but you have to be stupid lucky to even find that. Maybe also allow Podzol?
- Bone Meal feels weak as a fertilizer. (+25% bonus compared to water only) I'd probably rather build 5 instead of 4 cloches before i set of and build infrastructure for automatic bone meal generation. Maybe the fertilization factor of water and bonemeal was supposed to add (100% and 125%) or maybe I'm just being greedy.
- pumpkins are a more efficient source of plantoil, provided you power a single assembler crafting them into seeds (cloche output per cycle: 1 pumpkin = 4 pumpkin seeds = 320mB vs 2 hemp seeds = 240mB
- harvestcraft crops output a seed, which feels a bit strange, since you can craft all the actual produce into their respective seed anyways and they are not used for plantoil, like the vanilla/IE seeds
  - harvestcraft white mushroom seems to grow on dirt, but not on mycelium
- last but not least: with all the excess product (seeds, hemp fibers) etc. I'd really like a way to destroy items other than building my own cactus/lava pit :x

anyways, love the thing!

**Comment by Mike-T4** [comment]
I think melons should just be harvested as slices TBH. That's their vanilla behavior. Plus, you could craft slices in melon blocks if you really have to.

I personally think bonemeal is alright.

**Comment by BluSunrize** [comment]
While I do consider some of these concerns valid, I am a little disappointed that they come now, after weeks of the thing being available to test on Jenkins.
There is a [full thread](https://github.com/BluSunrize/ImmersiveEngineering/issues/1998) on this issuetracker dedicated to all the things people found while playing with it and I figured that this was more than enough time for stuff like that to be brought up.
Just now, that I was hoping to declare the 1.10 builds done, so I can move to 1.11, all of this stuff suddenly floods in. Feels a bit late tbh :V

**Comment by Mike-T4** [comment]
Ah, I wasn't aware that this was meant to be the last 1.10 build though. Oops.

**Comment by MalkContent** [comment]
I was unaware of the thing being available :/
I don't mind it staying as is until i can move to 1.11
the only bug is a cosmetic one, the rest is just QoL

**Comment by MalkContent** [comment]
one more tag on:
wheat output of the cloche is 1 wheat and 2 seeds
don't know if intentional (as in: more seeds because of plant oil), but it feels like this could have been switched accidentally

**Comment by Mike-T4** [comment]
@MalkContent Wow, I didn't even notice that. That very much looks unintentional.

**Comment by belathus** [comment]
Honestly, I feel that the growth speed of the cloche without bone meal is incredibly fast. If it were up to me, I'd probably slow it significantly. IE, reduce the speed to 10% - 20% of their current speed (making it take 5 to 10 times longer per growth cycle), but make the bone meal provide a speed boost of 150% to 200%. I'd also want to add an industrial fertilizer that boosted the speed even more.

I'm told the cloche can accept fertilizers from other mods. The only one I tried was blood potash from EvilCraft, but it doesn't work.

**Comment by Mike-T4** [comment]
@belathus I agree, after further testing I can see that my nerf suggestion of 15% is actually still WAY too small. Considering how balanced IE is in other areas, I think that _1/10_ of the current growth rate would indeed be better.
The 200% speed boost from bonemeal also seems fair.

**Comment by MalkContent** [comment]
I dunno, that seems like an excessive nerf to me. In my mind the cloche replaces considerably more than 1 block of a farm patch. Maybe a fourth of a traditional 9x9 farmland setup, so about 20 blocks. Then think about how other growing mechanisms speed up crop growth and suddenly the cloche doesn't seem so powerful anymore.

**Comment by Mike-T4** [comment]
@MalkContent Even when at 1/10th of the current speed, they still spit out a crop every ~70 seconds.
Perhaps that is a bit too much, but at least 1/5 seems fair to me.
Vanilla farming is _slow_. Wheat takes like 20 minutes to grow last time I checked.

And Immersive Engineering is not balanced around other mods.
Unless you meant Bonemeal, in which case I still disagree since that takes must be applied manually while the cloche's are fully automated and fairly easy to set up.

The best solution would probably be configurable growth speed, though that would be harder to implement.

**Comment by MalkContent** [comment]
Well then at 1/10th current speed the output of the cloche would be about that of a 4th of a 9x9 (aka 4x5) wheat field. Going that low would mean the benefit of the cloche is basically only the automated harvest.

I don't categorically oppose making the cloche slower, but I would probably balance it around fps impact more than anything :x no point in forcing the players spam cheap machines when the game becomes unplayable because of it.

**Comment by belathus** [comment]
The two cloches I have (one cactus, one sugarcane) vastly outperforms my more traditional EnderIO farms in both growth speed and ease of setup. And they use far, far less power.
