### ISSUE TITLE
[0.10-58] Redstone Ignoring Conveyor can't be crafted back into normal Conveyor

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#2074]
It would appear that crafting a single conveyor (regular or redstone ignoring) is a recipe for both kinds of conveyor (seen by NoMoreRecipeConflict mod), and the recipe for the redstone ignoring one wins out.
No idea why, from a quick look at the code, but there you are.

**Comment by BluSunrize** [comment]
Argh. Fiddlesticks.
Of course that would break.

The recipe ignores NBT data. Any conveyor will craft into a redstone-ignoring one.
I'll look into it, cheers for the report.
