### ISSUE TITLE
[1.11.2] Config

### ISSUE THREAD

**Issue by Terpo** [BluSunrize/ImmersiveEngineering#2075]
I could not resist checking the 1.11.2 branch out after AtomicBlom did all that hard work.

First small report for you:
It seems the config is not generating as expected -->

    machines {
    }

    ores {
    }

    tools {
    }

:)
Forge 2282, with IE source from 2017-05-10 16:00 MEZ

**Comment by malte0811** [comment]
I found 2 tiny 1.11 bugs as well, they don't really warant opening a new issue for themselves:
1. The LV wire relay item has the connector texture (just the item, not the block).
2. Redstone connectors don't seem to cause chunk updates when changing the channel or IO mode.

**Comment by BluSunrize** [comment]
Found the issue, nested configs musn't be initialized anymore.
