### ISSUE TITLE
Handbook Glitch

### ISSUE THREAD

**Issue by Bu1ldm4n** [BluSunrize/ImmersiveEngineering#2076]
Hello I am using the newest version of Immersive Engineering for 1.10
I am using the modpack Skyexchange with optifine and theoneprobe added for some reason when I try looking at most machinery a lot of blocks have the purple and black no texture sign.  Can someone help me?

**Comment by BluSunrize** [comment]
Please create a debug crash as instructed in the contribution guidelines

**Comment by Bu1ldm4n** [comment]
What is the contribution guidelines I didn't see anything about that

**Comment by Bu1ldm4n** [comment]
The handbook shows a lot of blocks to be purple and black
I did not try it on a server
I am using these mods (skyexchange modpack) [](https://pastebin.com/He5qZcgE) plus I added optifine and theoneprobe

**Comment by mindforger** [comment]
try without optifine to check if it's rendering changes

**Comment by BluSunrize** [comment]
Remove optifine, if it works then, it's their fault.
The contribution guidelines are [here](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/CONTRIBUTING.md), they show up when you create a new issue. You should read them, that's why they show up in a special yellow box above your text input >_>

**Comment by mindforger** [comment]
that yellow isn't alerting enough, it should be more vibrant in my opinion ;)

**Comment by Bu1ldm4n** [comment]
I got rid of optifine. It still has the glitch. :(

**Comment by Bu1ldm4n** [comment]
Here is a screenshot 
![2017-05-11_19 28 08](https://cloud.githubusercontent.com/assets/28607872/25976030/13d1874e-3680-11e7-857b-190d6090e0da.png)

**Comment by mindforger** [comment]
you still forgot to attach an forced crashlog (F3 + C > 6seconds)

**Comment by BluSunrize** [comment]
Yeah we need that debug crash, however, as an initial idea:
Try updating Chisel.

**Comment by Bu1ldm4n** [comment]
Crashlog: https://pastebin.com/mbJrDmVZ

**Comment by Bu1ldm4n** [comment]
Bump

**Comment by mindforger** [comment]
Like blu said, try updating chisel, its outdated, quiet a bit

**Comment by BluSunrize** [comment]
^ This. I specifically mentioned a possible fix which was then entirely disregarded.
