### ISSUE TITLE
tank won't work

### ISSUE THREAD

**Issue by SpankMaMemes** [BluSunrize/ImmersiveEngineering#2077]
Once I've built the tank I try to use my hammer on it but it won't change into the tank

**Comment by MinecraftArchive** [comment]
spam click the hammer all over it its a know bug

**Comment by mindforger** [comment]
not really a bug, you have to click the right block and as far as i remember it should eihter be the middle block of the lower tankwall-ring or the tank outlet

**Comment by malte0811** [comment]
From the code I would say it is the outlet/the single sheetmetal block in the bottom. If that doesn't work, please a) read the contributing guidelines and add the information requested there and b) post some screenshots of the structure you built, ideally layer by layer.

**Comment by BluSunrize** [comment]
You need to click the middle block on on eyelevel.
Also, yeah, read the guidelines, pictures of the structure are required, level by level.
