### ISSUE TITLE
Console spam when playing with GregTech

### ISSUE THREAD

**Issue by LuxusDarkangel** [BluSunrize/ImmersiveEngineering#208]
Example error: http://pastebin.com/Ab6nfHuw

PD: Hope the answer isn't "You're using GregTech, I dont support it"

**Comment by BluSunrize** [comment]
....are you running Gregtech 5 or 6?

**Comment by LuxusDarkangel** [comment]
I only report bugs when im using latest versions, so i forgot to post it xD

Immersive Engineering: 0.4.1
GregTech: 6.00.48
Forge: 10.13.4.1481

**Comment by BluSunrize** [comment]
Yeah, I worked with GT5, sorry .-.
Just disable gregtech support in the config, IE probably won't work with GT6 anyway.

**Comment by LuxusDarkangel** [comment]
Solved. Thank you so much, you're so quick attending issues :)
