### ISSUE TITLE
[0.10-57, 0.10-58] Floodlights have buggy transforms

### ISSUE THREAD

**Issue by ColonelClink** [BluSunrize/ImmersiveEngineering#2080]
- Using Modpack FTB Beyond Release 1.6.1
- Singleplayer (Multiplayer not tested)
- Versions tested: 0.10-57 & 0.10-58

Floodlights placed and then rotated on the horizontal axis will start to randomly reposition at various angles from the correct orientation when rotated on the vertical axis. If floodlight is powered in this state, it will usually show the correct orientation; however, turning it off will cause it to revert to the previous incorrect orientation.

To reproduce: place a floodlight on the ground, rotate it on the horizontal axis (aim at the base of the floodlight) until it is pointing in the opposite direction & down at the ground. Rotate floodlight (aim at the top) and the horizontal axis will start to randomly reposition 90° to original. See video: [https://youtu.be/nFPoTu8eXE4](https://youtu.be/nFPoTu8eXE4). This happens at various unpredictable points of rotation.

**Comment by BluSunrize** [comment]
Hmm, I suspect this to be the combination of the hammer adjusting the floodlight's yaw while at the same time changing its cardinal rotation.
I'll look into it, thank you for the report.
