### ISSUE TITLE
Shader Suggestion

### ISSUE THREAD

**Issue by robertmaxton42** [BluSunrize/ImmersiveEngineering#2081]
Since you have quite a few references in there already...

It seems a shame that IE has a Railgun, but no [Railgun](https://www.youtube.com/watch?v=NHSa6_n2JoA) shader. :p Maybe something like a "coinflip" appearance?

**Comment by BluSunrize** [comment]
Well for one, I have never seen that show, and two, how would I make a shader out of that? .-.

**Comment by robertmaxton42** [comment]
While I can't necessarily recommend the show itself, it does have some excellent railgun moments in it, so it seems appropriate. I'd suggest a short clip of a coin flipping in midair, supported by lightning bolts - it's a little weird that it then fires a graphite rod or whatever but enh, it's a shader, I dunno what the EVA-01 is doing shooting graphite rods either :V.

**Comment by BluSunrize** [comment]
Yeah but EVA Unit one had a definite colourscheme I could work with =P
Same with all the others. They always had a design or colourscheme that was clearly associated with them that I could draw from.
Also, most of the shaders are usually designed with the revolver in mind and then transposed on the other items.

**Comment by robertmaxton42** [comment]
Well, this one would definitely be a railgun-focused shader :P. 

Let's see. If you're open to the idea, I might be able to toss out a quick 3D sketch next weekend? The image I have in my head is basically the railgun "body" being animated bolts of lightning just hovering over the player arm, so there's no physical construct and the illusion of powering it with electrokinesis instead.

**Comment by BluSunrize** [comment]
That's probably not happening then.
That would require an entirely new texture, not to mention it being animated. Shaders work on a layered greyscale system, with me usually not introducing a new layer type unless I can find multiple use cases to apply it to.
