### ISSUE TITLE
[0.10-58]Covered Conveyor does not work properly when attached to item output

### ISSUE THREAD

**Issue by Mike-T4** [BluSunrize/ImmersiveEngineering#2085]
The point of covered conveyor belts is that you cannot pick up items that are on them.  
However, if you use a Hopper/Device to put items on a covered conveyor belt, then players will still pick up items that are supposed to be placed on the conveyor by that Hopper/Device.

**Comment by BluSunrize** [comment]
Could you provide pictures of your setup please?

**Comment by Mike-T4** [comment]
Here's an example:
![goawayslime](https://cloud.githubusercontent.com/assets/12882669/26111190/c1bdbd50-3a54-11e7-97d6-a01a31e2ed7a.png)

Throwing the item in the Hopper will return it to my inventory right away.

**Comment by BrisingrAerowing** [comment]
I noticed you only applied the fix to the 1.11 branch. I am seeing this in 1.10.2 as well. Just FYI.

**Comment by Mike-T4** [comment]
^ Can confirm.
