### ISSUE TITLE
[Request] Crates keep Inventory ->optional

### ISSUE THREAD

**Issue by ReTeYeZ** [BluSunrize/ImmersiveEngineering#2086]
I would really appreciate it if you could add a config option to disable the behaviour of crates keeping their inventory when picked up. I actually disabled the recipes for them myself but then I realized that they spawn in Villages. Hope this can be easily achieved.

**Comment by BluSunrize** [comment]
Well, the crates are specifically designed to *keep* their inventory. That's the whole point to them.
Otherwise, they'd just be a more expensive chest.
Why are you looking to disable this feature?

**Comment by KnightMiner** [comment]
Chance it is related to the shulker box, they are a similar concept from vanilla, but a bit more expensive/end game.

**Comment by ReTeYeZ** [comment]
It's just my opinion but I think this feature is op (especially with the mods I've thrown together). I dont like shulker boxes either but I dont have to worry about them for now since I'm on 1.10.

It takes away challenge that you'd otherwise have to find a creative solution for.

Disabling the crates completely would work for me as well but I'd miss them for decorative purpose.

**Comment by BluSunrize** [comment]
No, I won't be disabling this then.
The perception as OP is quite subjective in this case, I don't believe this feature needs a config.
Shulker boxes differ because they also break to pistons and place through dispensers making them a viable mass-item transport for vanilla.
