### ISSUE TITLE
[1.11.2] Heavy Engineering Block

### ISSUE THREAD

**Issue by Terpo** [BluSunrize/ImmersiveEngineering#2087]
Forge 2296
IE from source: 2017-05-13 | 10:00 MEZ

Seems the block model for the Heavy Engineering Block is not loading as expected. It renders normally in the inventory but in the Manual and when places on the ground its missing its texture.

![2017-05-13_11 24 00](https://cloud.githubusercontent.com/assets/4256058/26024279/af670b94-37ce-11e7-9396-a279b8581201.png)
![2017-05-13_11 24 48](https://cloud.githubusercontent.com/assets/4256058/26024283/c920532e-37ce-11e7-9f4d-5e70409f40c2.png)

With some experimenting it was possible to form the multiblock. Somehow the placement did not let me place the Heavy Engineering Block on the piston oO

**Comment by malte0811** [comment]
They worked for me yesterday, with the same version plus some fixes I was making (unrelated ones). What other mods do you have installed? Esp. Chisel?

**Comment by Terpo** [comment]
not only chisel ... xD
https://gist.github.com/Terpo/7b474351595daed3eb39473b82442243

**Comment by malte0811** [comment]
I'd guess that this is the connected textures, probably a missed reference to the old texture.

**Comment by Terpo** [comment]
Your guess is correct. Tested it with and without chisel in a seperate instance. Without chisel its showing up ;)

**Comment by BluSunrize** [comment]
found the reason ^^
