### ISSUE TITLE
[1.11.2][Suggestion] small balance change to rods (iron|alu|steel)

### ISSUE THREAD

**Issue by Terpo** [BluSunrize/ImmersiveEngineering#2088]
Just a small suggestion. Currently your Metal Press create for one ingot two rods. With the normal crafting recipe its the same amount because you use two ingots and got four rods. To encourage the use of your Metal Press you may should lower the output of the crafting recipes to two rods.

**Comment by Mike-T4** [comment]
The main benefit of the metal press is automation. It is also very easy to make, so I'm not sure if a buff is necessary.

**Comment by Terpo** [comment]
I know but automating a recipe with a hammer is also quite easy^^

**Comment by BluSunrize** [comment]
Hammers don't make rods?

**Comment by Terpo** [comment]
oh, woops, you are right.... you don't even need the hammer XD
Or is the recipe 2 Ingots => 4 Rods not an IE recipe?

**Comment by BluSunrize** [comment]
It is, but it doesn't take a hammer.
It's like making sticks out of planks.

**Comment by Terpo** [comment]
Yeah, my fault :). Head is broken today. But my main suggestion stays 2->2 not 2->4 because why would you need the metal press then?
