### ISSUE TITLE
Powered Latern wont work IE 0.10-57 and .58

### ISSUE THREAD

**Issue by LeSwede** [BluSunrize/ImmersiveEngineering#2089]
Yo,

I cant seem to get the Powered Lantern to work at all. Ive tried multiple power sources to no avail. 

Its on in the config:
        # How much Flux the powered lantern draws per tick
        I:lantern_energyDraw=1

        # How much Flux the powered lantern can hold (should be greater than the power draw)
        I:lantern_maximumStorage=10

        # Set this to false to disable the mob-spawn prevention of the Powered Lantern
        B:lantern_spawnPrevent=true

![dllhost_2017-05-13_14-07-30](https://cloud.githubusercontent.com/assets/28671801/26025336/8c364452-37e5-11e7-8202-59e78feae1d6.png)

Should be noted that Im playing FTB Beyond v1.5.3 (Tested in v1.6.1 and still doesnt work) Also manually updated IE to .58 and still broken. 

Please tell me if Im being stupid or if its actually broken :( This is driving me insane xD

**Comment by theunkn0wn1** [comment]
Have you tried LV wires yet? Your picture looks like MV

**Comment by LeSwede** [comment]
Yeah, those doesnt connect to the lantern. Im using LV in the picture.

**Comment by AEnterprise** [comment]
is it possible you used a relay instead of a connector?

**Comment by LeSwede** [comment]
AEnterprise, OMG FML I DID asghdjsafjgf. xD Thanks mate :D Im so retarded, Ive been using IE for ever and that mistake is such a noob move D:
