### ISSUE TITLE
creosote buckets and oredict

### ISSUE THREAD

**Issue by seebs** [BluSunrize/ImmersiveEngineering#209]
We added immersive engineering to an existing modpack (derived from Resonant Rise, loosely), and now everything that makes creosote oil makes the IE creosote oil, but nothing seems to think it's usable in other recipes. So there's liquid:creosote in oredict, and it works in that if I have IE creosote in a tank, Artifice or Railcraft creosote can be added... But it doesn't work for railcraft.

**Comment by BluSunrize** [comment]
"liquid:creosote" is 100% not in the OreDict, and you should look at existing issues:

https://github.com/BluSunrize/ImmersiveEngineering/issues/101

**Comment by seebs** [comment]
It somehow failed to occur to me to check *resolved* issues. Observed that actually the liquid works just fine, it's just the buckets not working. I think my player may not have known about using liquids through conduits or pipes. Sorry!

**Comment by BluSunrize** [comment]
That issue isn't resolved, it is very much open, and kinda upon Covert to fix, not me.

**Comment by seebs** [comment]
I think I need to stop using computers this weekend, as I am apparently unable to read.

Anyway, it turns out that I don't actually have a problem that I can't easily work around, I just have users who are a little unclear on tech mods.

(BTW, the waterwheels are *gorgeous*. I am really liking this mod's aesthetics.)
