### ISSUE TITLE
[1.11][minor] Machines are transparent

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#2092]
When any IE multi-block machine is formed (tested with coke oven and fermenter) they stop blocking light, just like glass. This is unexpected as the blocks that make up the structure are treated as solids that obscure light.

Steps to reproduce: 
1. Carve a 3x3 tunnel down from the surface, at least 5m deep
2a. Place the **Coke oven** blocks in the correct 3x3x3 structure within the tunnel bored
2b. Observe how the tunnel below the coke oven blocks is dark, as the structure blocks the sunlight
3. Use the **Engineers Hammer** to complete the Coke Oven MB
4. Observe how the region below the oven is now lit up, exposed to direct sunlight

Minecraft 1.11, IE built against 89890c61ca35ebd11366481d119d25f312b425d5

**Comment by BluSunrize** [comment]
Yeah problem is that if I made them solid, their render would be covered in shadows :/
