### ISSUE TITLE
[1.11.2] [59-93] Transformers on posts only face west

### ISSUE THREAD

**Issue by Rosethorns** [BluSunrize/ImmersiveEngineering#2093]
http://i.imgur.com/QbU70p8.png

**Comment by BluSunrize** [comment]
I can't entirely reproduce this, Rosie.
Are you sure you didn't just look too far to the side?

If you stare directly at the post, it should attach properly.

**Comment by Rosethorns** [comment]
That is infact what I did.

**Comment by BluSunrize** [comment]
Excellent, that makes for a far easier fix then =P
