### ISSUE TITLE
[1.11.2][59-53] Coal Coke does not appear to be 1:1 with steel anymore

### ISSUE THREAD

**Issue by Rosethorns** [BluSunrize/ImmersiveEngineering#2094]
http://i.imgur.com/DnZMoFj.png

As seen in the picture above 1 steel appears to take slightly more than 1 coal coke. This is consistent only when making multiple steel. And its not conclusive when it falls out of sync

**Comment by BluSunrize** [comment]
I've been not able to reproduce this yet.
Is it actually not finishing the process and stuck until you add more coke, or are you just noticing that the flame in the GUI is out?

**Comment by LiEyWe** [comment]
Had this problem in 1.10.2 v57 too. It was on a server. Sadly I don't have a picture or something alike

**Comment by Rosethorns** [comment]
its not finishing the process and stuck until I add more coke.

**Comment by malte0811** [comment]
What is the precise setup you are using? I see you have an advanced blast furnace with at least one preheater. Is that heater getting enough power? Is there a second heater? What did you put in? A stack of iron and 9 coke?

**Comment by laz2727** [comment]
Can confirm, same problem in SSP. It doesn't process unless one more is
inserted.

**Comment by malte0811** [comment]
With what precise setup (See my previous comment)? Because neither Blu nor me were able to replicate this issue which might be caused by us using different setups from yours.

**Comment by MalkContent** [comment]
that's an old problem , had that in 1.8.9, too
initially it works well enough, but eventually it gets that small offset.
maybe something to do with chunk saving/loading

**Comment by malte0811** [comment]
I have found a potential way to cause this, were you using preheaters and turned them on or off while the items where processing? I think that could lead to "wasted" fuel ticks.

**Comment by MalkContent** [comment]
Yes. i can't tell you if that happened without them, too, or not, tough. been a good while since then ^^

**Comment by MatthiasMann** [comment]
This is is still present with the crude blast furnace - seems like one tick is missing to finish the steel - I only tested with a block of coal coke and 10 iron - adding one charcoal instantly finishes the last steel ingot.

I haven't tested that yet with the improved blast furnace and the preheater.

**Comment by darthvader45** [comment]
Same here, with latest 1.12.2 version of IE, adding any fuel finishes the process, no idea why it wouldn't finish.  Checking the coal coke's blast fuel shows it at 1200, when it takes 1600 ticks to finish one steel ingot, hence why it takes an extra bit of fuel to finish.

**Comment by darthvader45** [comment]
I'm not using a modpack, simply downloaded IE from CurseForge, using default settings.  I highly doubt Immersive Tech or Immersive Petroleum would have any sway over the blast furnace.
