### ISSUE TITLE
[0.10-58] Jerrycan use action not cancled by block interaction

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#2098]
With the exception of using barrels, using a block with jerrycan containing fluid in hand will generally not use the block and instead place a fluid block. Generally the standard is that the item action is cancled upon interacting with a block unless you shift-use.

This also can cause fluids to be duped or destroyed when using the jerrycan with tanks.

Railcraft_1.10.2-10.1.2
OpenComputers-MC1.10.2-1.6.2.7
SuperCircuitMaker-1.0.4
chiselsandbits-12.12
jei_1.10.2-3.14.7.416
InventorySpam-1.10.2-0.0.5
AppleSkin-mc1.10.2-1.0.5
AppleCore-mc1.10.2-2.1.2
Baubles-1.10.2-1.3.9
NoMoreRecipeConflict-0.6(1.10.2)
MCMultiPart-1.4.0-universal

theoneprobe-1.1x-1.4.6
compatlayer-1.10-0.2.5

IE 0.10-58
forge x2281
MC1.10.2

**Comment by BluSunrize** [comment]
Could you give me a concrete example of a tank to try this with?

**Comment by MalkContent** [comment]
For duping:
Have an empty tank or a completely full jerrycan (so the jerrycan  inserts into the tank).
The Tank will then receive the contents of the jerrycan, the jerrycan will keep its original contents and subtract 1000mB for placing a fluidblock into the world.

For destroying:
Draw from a tank with a partially filled jerrycan. The tank will subtract the amount to "fill" the jerrycan, the jerrycan will once again, keep its original contents and then subtract the 1000mB to place the fluidblock.

**Comment by BluSunrize** [comment]
I'm failing to reproduce this on 1.11, haven't tried it on 1.10 yet.

**Comment by MalkContent** [comment]
adding mod list then like i should have to begin with :x

**Comment by MalkContent** [comment]
tried on 1.10.2, forge x2281, only IE 0.10-58
duping still works

**Comment by MalkContent** [comment]
this seems to be gone in 1.12.1
