### ISSUE TITLE
Memory leak in blusunrize.immersiveengineering.api.ImmersiveNetHandler.indirectConnections

### ISSUE THREAD

**Issue by sfPlayer1** [BluSunrize/ImmersiveEngineering#21]
From a FC2 heapdump I've observed 4.8GB of referenced data in said collection with 43200771 entries and 146 keys.

**Comment by BluSunrize** [comment]
Well yeah, that's the hashmap which stores all indirect connections, aka from entry point of the net to exit point of the net.
The other option would be running the A* algorithm every time you attempt to send power. I'd say this is more ideal.

**Comment by sfPlayer1** [comment]
The numbers along make me doubt that's working as intended. It's very unlikely that there aren't mostly duplicate nodes in the lists.

**Comment by BluSunrize** [comment]
Think I found the bug. Suddenly, the indirect connection list in my dev world shrunk from 22788 to 4.

GG.
Thanks for the heads up. I'd never have given it a second glance otherwise.

**Comment by sfPlayer1** [comment]
Seems to be fixed.
