### ISSUE TITLE
Core Sampler API

### ISSUE THREAD

**Issue by Kubuxu** [BluSunrize/ImmersiveEngineering#210]
It would be nice if core sampler was extending from interface allowing it to be interfaced directly by outside code not dependant directly on ImmersiveEngineering.
Following functions would be useful:
```java
float getSampleProgress();
boolean isSamplingFinished();
String getVein();
float getVeinIntegrity();
```

**Comment by BluSunrize** [comment]
And that'd be useful fooooor?

**Comment by Kubuxu** [comment]
OpenComputers integration.
