### ISSUE TITLE
[0.10-58] Mystical Agriculture Cloche support doesn't include Inferium seeds.

### ISSUE THREAD

**Issue by mallrat208** [BluSunrize/ImmersiveEngineering#2100]
Forge: 12.18.3.2281
Immersive Engineering: 0.10-58
Mystical Agriculture: 1.5.3

First  off, I just want to say the Cloche is awesome, really cool device.

I was trying to use some Mystical Agriculture seeds in the Cloche earlier and had a problem getting it to accept any of the Inferium seeds. They're one of the most basic/common ones you need to progress in the mod. Everything else worked fine however. I took a look at the module you have for Mystical Agriculture and at their  repo and I believe I know what the problem is, Inferium isn't in the CropType.Type enum.

The Crops and Items missing are:
mysticalagriculture:tier1_inferium_seeds
mysticalagriculture:tier1_inferium_crop

mysticalagriculture:tier2_inferium_seeds
mysticalagriculture:tier2_inferium_crop

mysticalagriculture:tier3_inferium_seeds
mysticalagriculture:tier3_inferium_crop

mysticalagriculture:tier4_inferium_seeds
mysticalagriculture:tier4_inferium_crop

mysticalagriculture:tier5_inferium_seeds
mysticalagriculture:tier5_inferium_crop

They all yield the same item, mysticalagriculture:inferium_essence, just at higher amounts per tier of the crop.

**Comment by SoftPoison** [comment]
I came up with _a_ solution -- it's nowhere near optimised, but it's a start. Rather than adding the fix as a PR, I'll drop the code here for @BluSunrize to add and refine manually as there is probably a prettier way to do this.

Also note that there is no config option to disable the different tiers of inferium crops so it's relatively safe to add the handlers without checking to see if they are enabled.

Change `postInit` to:
```java
@Override
public void postInit()
{
	try
	{
		Class c_Types = Class.forName("com.blakebr0.mysticalagriculture.lib.CropType$Type");
		Method m_isEnabled = c_Types.getMethod("isEnabled");
		if(c_Types!=null && m_isEnabled!=null)
			for(Object type : c_Types.getEnumConstants())
				if((Boolean)m_isEnabled.invoke(type))
				addType(((IStringSerializable)type).getName());

	}catch(Exception e){
		e.printStackTrace();
	}

	//Manual inferium crop addition
	try
	{
		addInferium(1);
		addInferium(2);
		addInferium(3);
		addInferium(4);
		addInferium(5);
	}catch(Exception e){
		e.printStackTrace();
	}
}
```
where `addInferium` is
```java
static void addInferium(int tier)
{
	String strTier = Integer.toString(tier);
	Item itemSeeds = Item.REGISTRY.getObject(new ResourceLocation("mysticalagriculture:tier"+strTier+"_inferium_seeds"));
	Item itemEssence = Item.REGISTRY.getObject(new ResourceLocation("mysticalagriculture:inferium_essence"));
	Block blockCrop = Block.REGISTRY.getObject(new ResourceLocation("mysticalagriculture:tier"+strTier+"_inferium_crop"));
	if(itemSeeds!=null && itemEssence!=null && blockCrop!=null)
		BelljarHandler.cropHandler.register(new ItemStack(itemSeeds), new ItemStack[]{new ItemStack(itemEssence, tier),new ItemStack(itemSeeds)}, new ItemStack(Blocks.DIRT), blockCrop.getDefaultState());
}
```

**Comment by BluSunrize** [comment]
Nah, tbh, that's already a pretty nice way of doing it =P
No point having the try{}catch though, is there? Shouldn't throw any exceptions.

I'll look into this soon-ish, thanks ^^

**Comment by SoftPoison** [comment]
No problemo 😄 
And yeah, now that I think of it the try/catch statement is useless as nothing there's really going to throw an error. Nice _catch_
