### ISSUE TITLE
Coke Oven Duping

### ISSUE THREAD

**Issue by TheGoldCrayon** [BluSunrize/ImmersiveEngineering#2102]
Whenever I break a block of the coke oven with items inside, it dupes them. I haven't tested it with anything other than coal blocks, but I was able to repeat it several times. I'm playing the Age of Engineering modpack, which includes the 0.10-58 release of this mod.

**Comment by malte0811** [comment]
I don't know why neither @BluSunrize nor I looked into this when you reported it, but we fixed a duplicate of this, #2171, in the latest release.
