### ISSUE TITLE
[1.11.2] [59-98_2] South facing fluid pipe end caps are rendering incorrectly.

### ISSUE THREAD

**Issue by Rosethorns** [BluSunrize/ImmersiveEngineering#2104]
http://i.imgur.com/Yzpq9WX.png

The above picture shows a south facing pipe end cap not rendering correctly. This does not occur on south facing bends.

**Comment by HappyPineapple** [comment]
well yours is beter than mine

**Comment by malte0811** [comment]
(Probably) Fixed for the next release.
