### ISSUE TITLE
Can't get Ingots from Blocks

### ISSUE THREAD

**Issue by Pihrra** [BluSunrize/ImmersiveEngineering#211]
Using IE 0.4.1 I don't seem to be able to craft my steel blocks back into ingots. The recipe shows up in NEI but it doesn't work (tried in a vanilla crafting table and in the inventory).

Edit: Later I wondered about other materials and I can confirm I have the same problem with copper, lead, etc., not just with steel.

**Comment by BluSunrize** [comment]
Cannot reproduce. Are you using Gregtech or any other mod that might interfere with such recipes?

**Comment by Pihrra** [comment]
I didn't think so but I tried removing one mod at a time until the problem was fixed and apparently it was Growthcraft. Super weird since it's supposed to just adds crops and a ways to make drinks with them.
Sorry for wasting you time.
