### ISSUE TITLE
[Suggestion] Add Chemical Thrower compatibility for Compact Machines

### ISSUE THREAD

**Issue by Lykrast** [BluSunrize/ImmersiveEngineering#2110]
[Compact Machines](https://minecraft.curseforge.com/projects/compact-machines) in its 1.10+ versions adds a miniaturizing fluid that shrink entities it touches (and used for its crafting but that's not important here).

It would be cool to have the Chemical Thrower have support for it, as in using that minaturization fluid as ammo would apply the shrinking effect to whatever it touches.

**Comment by BluSunrize** [comment]
That'd be something Compact Machines can add using IE's API.
