### ISSUE TITLE
Arc furnace Electrodes

### ISSUE THREAD

**Issue by OmenMachine** [BluSunrize/ImmersiveEngineering#2111]
The engineers handbook still indicates that it is possible to automate the insertion of electrodes, having read other issues involving this it seems as though that is not an intended functionality, if that is the case the handbook should reflect that (also it seems strange to me that you have added a means of automating the crafting of electrodes, but not a way to put them in a furnace). If it is supposed to be possible to automate electrode insertion that functionality seems to be broken.

**Comment by malte0811** [comment]
Blu removed the ability to insert electrodes using automation probably more than a year ago. I checked the manual entry in the latest 1.10 version of IE and can't find anything indicating that automated electrode replacement is possible. Which version of IE are you using?

**Comment by BluSunrize** [comment]
Closing this due to lack of response.
