### ISSUE TITLE
 [0.10-58] Electrician villagers don't sell HV wire coil, but 2 different MV wire coil

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#2112]
~~uninstalling right away until fixed >:C literally unplayable~~

**Comment by mindforger** [comment]
This is not reddit

**Comment by BluSunrize** [comment]
Eh, I can appreciate that sort of humor =P

Still. Screenshots? :V

**Comment by ArukaAlter** [comment]
The eletrician does appear to sell MV coils at levels 1 and 2

![](http://i.imgur.com/GoXhsvF.png)

![](http://i.imgur.com/gQi0HrO.png)

**Comment by MalkContent** [comment]
sorry, i guess i could have made the issue a bit more clear.
basically what @ArukaAlter shows in those screenshots. (what do you use to show the trades in the creative thingy, btw?)
I suspect the intent was to make them sell all 3 electric wire coils, instead they sell the MV Wire Coil in two different trades.

**Comment by ArukaAlter** [comment]
JEI has a trade tab that cycles through all the trades by level.
