### ISSUE TITLE
Ticking block entity at TileEntityTurret.getTarget

### ISSUE THREAD

**Issue by TheQuadShot** [BluSunrize/ImmersiveEngineering#2117]
I powered up a turret with armor piercing ammo and set to kill animals. I wanted to kill a pack of wolfs.
Minecraft 1.10.2
Forge-12.18.3.228
ImmersiveEngineering-0.10.57

CrashLog
https://pastebin.com/nHt219Ce

ModList
https://pastebin.com/T1dWmRCA

**Comment by malte0811** [comment]
Try updating to IE build 58. It contains a few fixes related to turrets, IIRC including one for this crash.

**Comment by BluSunrize** [comment]
Yeap. Wovles were broken, but I fixed them. Use 58

**Comment by TheQuadShot** [comment]
Sorry, Am I searching the db wrong? I do a search for 

is:issue <My issue>

But I didn't find anything, else I wouldn't have filed.

**Comment by BluSunrize** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues?utf8=%E2%9C%93&q=turret%20crash

That keyword worked for me. :V
Don't worry about it though. It's quick and easy to say something like "There is a new build, use that" =P
