### ISSUE TITLE
[1.11] Redstone connector have inconsistant I/O

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#2118]
Issue: Redstone connectors cannot accept direct RS input from levers directly attached to them. They also cannot accept RS input when attached to redstone wire that is not directly pointing at the connector whilst happily outputting Redstone signals under the same conditions. This lead to great confusion when trying to debug why a (somewhat) big build of pumps wasn't working, as it refuses to accept levers as a direct input something that really should work.

Expected behavior: Redstone Connectors, when correctly configured as inputs, would output a high RS signal to the network when placed against levers/ redstone wire in the world

--------------
Actual behavior: Redstone connectors ignore all RS input that is not provided directly, such as redstone wire pointing directly at the connector.

----------------
Pics:
![image](https://cloud.githubusercontent.com/assets/3110986/26384857/d0ceee4e-3ff0-11e7-9d4f-4b3dc7883687.png)
This does not work as the redstone wire isn't pointing at the connector
![image](https://cloud.githubusercontent.com/assets/3110986/26384869/e21dba7c-3ff0-11e7-9f77-c2d69536c839.png)
This does, even though the output wire is not pointing directly at the connector; inconsistent behavior
![image](https://cloud.githubusercontent.com/assets/3110986/26384973/83c6a230-3ff1-11e7-9930-66689343ed56.png)

Lever set in the `ON` position does not conduct Redstone signal

Minecraft 1.11.2, forge version 13.20.2296
IE built against 1.11.2 f8255b8df963fb99904a3ed4a4a1aaa54c56819d

**Comment by mindforger** [comment]
well, this is vanilla redstone behaviour in my opinion. you have to layout your redstone in a way that is points into a block to power that block!
As long as that block does not pretend to be redstone dust itself, it won't connect automatically with the redstone.

and to be honest ... allowing to place the connectors against non solid blocks kinda looks ugly when they are floating XD

Levers apply a strong redstone signal to the block they are attached to and no signal to the other sides, so placing a connector against a lever should only work if you would be able to place lever and connector at the same time facing each other (commandblocks for testing?)

i don't know Blu's intentions but i find it quiet consistent already, but i would also kind of prefere when they act as redstone extension when placed near a redstone component like RS dust, a lever or a button (the thigns you did)


(but maybe remove that placing against non solid block faces, it really looks odd but thats just my opinion)

**Comment by BluSunrize** [comment]
Placing them against non-solid blocks like that can't easily be disabled, because it's at the core of connectors. And stopping it would mean you can't put them on glass anymore. Or Glowstone. Or various other blocks.

Redstone behavior is finnicky at best, I've tried to get it as functional as possible without making it limiting for builds.
Oh and look at your third picture again. Your input connector is set to white, the output to orange. That would be why it's not transferring.

**Comment by mindforger** [comment]
i have honestly no idea besides that redstone stuff in 1.7.10 was checking against a hard coded list(one of the reasons why redstone wires from RedPower were so crappy in CPU performance), but can't you let the connectors act like redstone dust to let them connect with vanilla redstone stuff when placed nearby? I don't see any reasonable limitations you would induce, except for having 1 block space to the sides when routing redstone stuff that should not interact with the connector

**Comment by theunkn0wn1** [comment]
The third picture isn't rendering correctly, it is set to orange. Oh yeah, that's a proper bug I found with the connectors: they don't always update their render when the channel is changed, only when they get wire connected/io configuration changes. If you want I'll open a ticket for that later when I get home...

As for placing against non-solid faces, it's a pain to do for Redstone dust and, since I can't place the connector first, the only way I can point it at a lever is to make it appear to float.  Getting the Connectors to detect signals applied to blocks, such as the lever against stone and the connector attached to the same stone, was real hit and miss in my testing...


Many of these inconsistencies could be resolved by making the connector connect to Redstone wire. Not that I know how easy that works be too do :/

**Comment by malte0811** [comment]
Making redstone connect to the connectors is pretty trivial, I'll make them connect if @BluSunrize isn't opposed to it.

**Comment by BluSunrize** [comment]
Go right ahead!
