### ISSUE TITLE
Gun turrets loose ammo on chunk reload (TileEntity for the block is being invalidated server-side?)

### ISSUE THREAD

**Issue by TheQuadShot** [BluSunrize/ImmersiveEngineering#2120]
I had filled all of my turrets (24) with Homing Ammo, and tried again with Armor Piercing. On server restart or when I return to the dim they are empty.

Minecraft 1.10.2
Forge-12.18.3.228
ImmersiveEngineering-0.10.57

ModList
https://pastebin.com/T1dWmRCA

LatestLog (gun turret)
https://pastebin.com/C9ndM9Jt

**Comment by malte0811** [comment]
Update IE. I fixed this for build 58.
