### ISSUE TITLE
Tank transfer causes massive connection Drop

### ISSUE THREAD

**Issue by CrimsonGryph** [BluSunrize/ImmersiveEngineering#2121]
While playing on a server I randomly was unable to keep a steady connection and when I teleported away from our main base, I had a perfectly fine connection, thinking back to when the connection first started dropping we figured out that when an IE fluid tank is transfer into a fluid pipe, my connection and most likely others' drops, mine was more noticeable because I have a particularly slow connection to begin with, but when this happens I get disconnected within seconds of the transfer starting. this is with version 0.10-58 for minecraft 1.10.2

**Comment by theunkn0wn1** [comment]
Can we please get the following information:

- Minecraft, Forge, IE version.
- Any plug-ins such as Sponge, etc. the server is running
- A full list of mods (versions included) and/or a link to the public modpack the server is running

Does this occur in single-player or only on Dedicated servers?
Can we please get a copy of the client/server logs when a the Disconnect occurs?

**Comment by mindforger** [comment]
>A full list of mods (versions included) and/or a link to the public modpack the server is running
pressing F3 + C for several seconds will force a crash, this crashlog contains plenty of informations :) the easy way to modlist
also a screenshot of the setup eventually additional to the other informations

**Comment by BluSunrize** [comment]
Closing this due to lack of information.
