### ISSUE TITLE
Attained Drops 2 - Garden Cloche render issue

### ISSUE THREAD

**Issue by Shadows-of-Fire** [BluSunrize/ImmersiveEngineering#2123]
I think [something](https://i.imgur.com/KOfWflD.png) might be a bit off...  
`attaineddrops{2.2.2}`
`immersiveengineering{0.10-58}`
`Forge{12.18.3.2297}`
Also, the entire game crashed when i pulled out the soil while an Attained Plant was mid-growth.  While that may not have been the best idea, it should still be addressed.
https://gist.github.com/Shadows-of-Fire/658690c93d9ff365ab79bd4061342edd

**Comment by kragnoth** [comment]
I get the same rendering issue (couldn't quite figure out how to fix it in the code).  Also get the crash when removing the dirt before the seed.

**Comment by Shadows-of-Fire** [comment]
I should really go check if the AD2 support even still works, considering the whole thing was rewritten in 1.12

**Comment by Shadows-of-Fire** [comment]
This issue is probably invalid now, ad2 was completely rewritten and this was a 1.11 bug
