### ISSUE TITLE
[1.11.2][59-104] Assembler suffers from the same issue outlined in #2106

### ISSUE THREAD

**Issue by Rosethorns** [BluSunrize/ImmersiveEngineering#2124]
Due to the nature of the hammer being used on conveyor belts, the assembler doesn't form but appears formed on the client.

**Comment by mallrat208** [comment]
This also happens with the Bottling Machine

**Comment by malte0811** [comment]
Unless there are 2 bugs like this one: I fixed this in 725e8def6004ebcbe329df74b236a383463b3358, part of #2113, which hopefully will be pulled tomorrow (or soon, anyways).

**Comment by mallrat208** [comment]
Ah, yeah cool. I did something similar as a work around for my Wrench

**Comment by malte0811** [comment]
I am thinking about PR'ing a fix for this to forge (might actually do that this afternoon), but I suspect it would be a breaking change and therefore not pullable before 1.12.

**Comment by malte0811** [comment]
I have made the PR to forge: MinecraftForge/MinecraftForge#3951. I will ask Blu to not pull my PR until the Forge people decide whether they like my fix and whether they want it in 1.11 (so no breaking change) since if my Forge PR gets accepted the IE PR I made would break stuff.

**Comment by malte0811** [comment]
The fix for this is is in IE for now, we will have to see if/when the Forge fix will be accepted.
