### ISSUE TITLE
[1.11.2][59-104] Arc Furnace null pointer when filling out the primary input slots

### ISSUE THREAD

**Issue by Rosethorns** [BluSunrize/ImmersiveEngineering#2125]
Log
` Caused by: java.lang.NullPointerException
(08:07:42) FC1sm: at blusunrize.immersiveengineering.common.blocks.metal.TileEntityArcFurnace.additionalCanProcessCheck(TileEntityArcFurnace.java:396)`

Nickle grit used as input material

**Comment by theunkn0wn1** [comment]
Please attach the full crash log and not just that snippet. 
Do **NOT** copy paste, upload it to Gist or the sorts and provide the link.

**Comment by malte0811** [comment]
@theunkn0wn1 The line @Rosethorns posted is enough to fix this (I'll push the fix in a minute). I'd suggest you check whether additional info is needed before asking for it. I know not providing a full stacktrace is bad practice, but in this case it isn't an issue.

**Comment by theunkn0wn1** [comment]
Alright.. I jumped to the conclusion that incomplete crash logs generally result in a request for the full log and preemptively asked for it as to try and save some time. 
 I'll be more thorough next time this should come up.
