### ISSUE TITLE
Garden Cloche crash with Extra Utilities 2 Red Orchid

### ISSUE THREAD

**Issue by lparkjordan** [BluSunrize/ImmersiveEngineering#2126]
I tried putting a Red Orchid in a Garden Cloche on top of a redstone ore, and it caused a crash. [Here is a crash report](https://pastebin.com/C847RAD0).

The crash took place on a FTB Beyond multiplayer server, and happened again every time I reconnected. The blocks had to be deleted in order to prevent the crash.

**Comment by mallrat208** [comment]
Duplicate of #2071
