### ISSUE TITLE
[1.10.2][0.10-58][FTB Beyond 1.6.1-1.8.0] Hang on MC Loading Screen

### ISSUE THREAD

**Issue by tscs37** [BluSunrize/ImmersiveEngineering#2127]
During Startup on the Forge Loading Screen, Minecraft hangs indefinitely (waited for 120 minutes and longer to test this on FTB Beyond 1.6.1), while using 100% of a single CPU Core.

System is up-to-date Archlinux, AMD CPU, 32GB RAM, the FTB Launcher is set to 20GB of Maximum RAM and optimized parameters for fast computers, however, neither option has any effect on this issue (Tested with 32GB of Max Ram and 2GB of Max Ram with and without optimized parameters)

The last lines of the log are as follows:

```
[13:49:58] [Client thread/INFO] [immersiveengineering]: Stitching Revolver Textures!
[13:49:58] [Client thread/INFO] [FML]: Max texture size: 16384
[13:50:03] [Client thread/INFO]: Created: 4096x4096 textures-atlas
```

After that the MC Window no longer changes and eventually corrupts it's contents due to lack of responsiveness. Minecraft does not crash.

At this point MC cannot be closed normally and requires a SIGKILL to terminate.

Removing IE from the mod pack resolves the issue completely. Starting Minecraft on Windows using the same hardware resolves this issue completely.

**Comment by malte0811** [comment]
What version of java are you using? Both build and OpenJDK vs Oracle.

**Comment by tscs37** [comment]
I'm using the JRE8 OpenJDK in Version 8.u121-1,

`java -version` yields

```
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)
```

**Comment by malte0811** [comment]
I just tried using OpenJDK (on Debian stretch, openjdk version 131 since that is the current one, with IE, IC2 and IndustrialWires installed) and everything worked fine for me.
Does this happen with just IE installed? I probably won't be able to run Beyond since I have just 8GB of RAM, so a smaller test instance might help (I am the only person I know of that uses Linux and is familiar with IE code). If you have Oracle Java installed, try using that. I generally use Oracle Java and don't want to have to switch every time I test this issue.

**Comment by tscs37** [comment]
I've switched to Oracle Java, issue persists.

When removing all mods but IE then the client loads fine to start menu.

I've tried to replicate the issue by dropping mods but there doesn't seem to be any particular mod that is causing it. I isolated TConstruct and Steves Carts but after trying only those mods (which worked), they now aren't the problem anymore.

It might be related to some mod loading order but I can't exactly isolate the issue, sadly.

It still hangs on stitching the textures for IE though.

**Comment by tscs37** [comment]
The issue can be closed.

I've tried some various things and poked around the config files. After redownloading the entire modpack (again) the loading screen completes fine. /shrug

**Comment by mindforger** [comment]
the close button is right beside the Comment button :)

**Comment by HappyPineapple** [comment]
ther addres ing the mod auther
