### ISSUE TITLE
Fluid Pump

### ISSUE THREAD

**Issue by HappyPineapple** [BluSunrize/ImmersiveEngineering#2128]
Yer yer yer I know that we all redy have one, but why not one that can pump say water from say a pond
thanks regards HP

**Comment by malte0811** [comment]
This is a bit hard to read. You want the pump to be able to act like the ender-thermic pump or the Buildcraft pump? If that is the case: The pump can already do that, see pages 3-5 of the manual entry "Fluid Transport".

**Comment by BluSunrize** [comment]
Yeah, IE's fluid pump can already pick up fluids in the world.

**Comment by HappyPineapple** [comment]
Rely How ?

**Comment by HappyPineapple** [comment]
sorry for the bad spelling! :)

**Comment by BluSunrize** [comment]
Closing this then.

**Comment by HappyPineapple** [comment]
cool ok with me

**Comment by HappyPineapple** [comment]
ps dose it use an ifinate water sause

**Comment by BluSunrize** [comment]
Yes.

**Comment by HappyPineapple** [comment]
cool thanks again
