### ISSUE TITLE
[1.10.2][0.10-58]Tesla Crash

### ISSUE THREAD

**Issue by Lost-Ninja** [BluSunrize/ImmersiveEngineering#2130]
Cross posting from Darkosto's Invasion Modpack tracker, I saw the tweet that you'd finished up work on 1.10.2, so no idea if this is fixed (or caused by something else in the pack).

I have a mob trap killing Blazes/PigZombies/Skeles, while mostly I do the killing myself, when I'm unable to do so, I have a tesla from immersive engineering do it. However occasionally this happens:

https://pastebin.com/2PKxNkV2

Think this is the 2nd such crash in about 15 hours of play. So not exactly common.

**Comment by malte0811** [comment]
I probably fixed this in 1.11, closing this for now. If it happens again (on 1.11+) please post a comment here.
