### ISSUE TITLE
Thermoelectric Generators don't output power

### ISSUE THREAD

**Issue by IcepickJosh** [BluSunrize/ImmersiveEngineering#2133]
**What is the bug?**
Thermoelectric Generators don't generate power on latest: ImmersiveEngineering-0.10.58.jar

**What did you do to make it happen?**
I placed several different liquids and non-liquids on opposite sides of the Thermoelectric Generator and output the power to a IE machine for testing through the top of the generator.

Tried with:
Water / Lava
Packed Ice / Lava
Water / IE Uranium Block
Packed Ice / IE Uranium Block

To validate that it wasn't the machine set up, I attached a windmill to a kinetic generator. Power flows to the machine when using the windmill.

**Does it happen every time you do this? Does it happen if you do something else as well?**
Breaking and replacing the Thermoelectric Generator does not effect the results

**Did this happen on a dedicated server (multiplayer servers), in LAN multiplayer or in singleplayer?** 
I tested this on Single Player

**What other mods were installed when the bug happened?**
Tested with only IE

**Comment by TheGuyRunningSouth** [comment]
That's really odd. I've got a base set up (in a modpack) that 50% of my
power is from thermoelectric generators, so it might be an isolated issue.
I think pictures of the setup (if possible) would probably be helpful here.

**Comment by theunkn0wn1** [comment]
Have you tried connecting the Thermo to the machine in question via connectors and cabling?
What machine are you trying to power? i am unaware of any Ie machine that accepts IF input from below.
Can we please get pictures of your setup?

**Comment by BluSunrize** [comment]
I'm gonna close this, due to lack of pictures provided
