### ISSUE TITLE
[1.10.2] Conveyor belt not picking up items

### ISSUE THREAD

**Issue by Str4yFire** [BluSunrize/ImmersiveEngineering#2134]
Conveyor belt at the end of a water stream does not pick up items anymore. I made many hemp farms in the past and they have always worked for me until now.

**Comment by BluSunrize** [comment]
Could you please provide pictures of your setup?

**Comment by Str4yFire** [comment]
![conveyor belt water](https://cloud.githubusercontent.com/assets/29043575/26554416/3de24212-4490-11e7-90ba-0fe644e9015f.jpg)

**Comment by BluSunrize** [comment]
I see.
More or less intentional, actually. Conveyors have a boundign box so the items collide with the side.

You can get aroudn this pretty easily though, like this:
[!image](http://puu.sh/wdjq7/ed2034c772.jpg)
