### ISSUE TITLE
[1.10.2] Industrial Squeezer is not working

### ISSUE THREAD

**Issue by Str4yFire** [BluSunrize/ImmersiveEngineering#2137]
My squeezer does not process seeds put into it and does not grab items that are fed to it via conveyor belt.
![2017-05-30_03 04 15](https://cloud.githubusercontent.com/assets/29043575/26564735/309b52a6-44e5-11e7-872c-2a2a9378cf49.png)
![2017-05-30_03 05 39](https://cloud.githubusercontent.com/assets/29043575/26564736/309dc5ea-44e5-11e7-811b-5ce4d1bff42a.png)

**Comment by BluSunrize** [comment]
Is its redstone config changed to require an active signal perhaps?
Also, hemp fiber can't be squeezed.

**Comment by Str4yFire** [comment]
No, the redstone config is not changed. I tried changing it, no result. Also, the problem with the conveyor belt not inputting is caused by these steep ramps. If you put a flat belt as a last piece, then the machine is grabbing the items from the belt as intended. i have encountered several more bugs with the conveyor belts, but I think I will open a new issue, once I figured out what is causing these bugs.

As of now, my Industrial Squeezer is still not working. I am powering it with MV wires. Should I try to change it to HV?

**Comment by mindforger** [comment]
belts insert into the block they are pointed to (more precise the neighbour block of the space where the belt is) 
so technically a steep belt only would try to insert to the block at the same y level in transport direction and not the block above. This is in my opinion absolute loigcal and using a straight belt is the only logic option to insert something!

does the squeezer work when you remove the hemp? maybe it is blocking because of an invalid "recipe" as you can use the squeezer for recipes with more than one item

**Comment by Str4yFire** [comment]
Removing the hemp did not solve the problem. But rebuilding the machine has worked! I did not do anything different, but suddenly it works. I guess you can close this issue. Even tho I do not know what caused the problem.

**Comment by mindforger** [comment]
is it by chance possible that you had a single 1mB of any liquid (not beeing seed oil) in your squeezer left over? unfortunately by breaking it we have lost the chance to look if there was something in the output already .. how much mB does it require to have a visual inidcation in the tanklevel-bar?

**Comment by Str4yFire** [comment]
Hmm, what other liquid could have been in the squeezer? I thought it only processes seeds. My first screenshot says "Empty 0/24000mB".

**Comment by mindforger** [comment]
oh did Not notice that

**Comment by Lassecsgo** [comment]
Had the same issue, broke one block, rebuilt it and now it worked. I had a small amount of Seared Stone inside, but that should be an issue as that is the product of the process of making hop graphite ingots from coke dust of which i was trying to craft.
