### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by vrork** [BluSunrize/ImmersiveEngineering#2138]
https://gist.github.com/vrork/783a3ad02be8243ebbb8e542d96ccc6e

**Comment by mindforger** [comment]
looks like a broken recipe or recipe conflict
LandiaPlanks from landcraft causing this actually

**Comment by malte0811** [comment]
No, it is IE not handling the wildcard correctly. This came up before (#419), but in a different place and was fixed there. Don't report this to landiaPlanks.

**Comment by AEnterprise** [comment]
it is neighter handeling it well, while yes technically LandiaPlanks doesn't have to handle it, it's better if they do because there are other mods that might be parsing in that meta as well (and while non of them exist in 1.10+ anymore that i know of, some flat out refused to fix it on their end)

**Comment by vrork** [comment]
I reported to them too just to make sure since i saw their mod on the first lines of the error

**Comment by Landmaster** [comment]
@vrork I might make a pull request soon for this mod (Immersive Engineering) to correctly handle wildcards.

**Comment by vrork** [comment]
I posted there too. I saw both of the mods on the crash report and thought it wouldnt be a bad idea to make a post on both.

**Comment by Landmaster** [comment]
I've opened a pull request (#2144) to handle the wildcards and fix this issue.

**Comment by Landmaster** [comment]
@vrork @BluSunrize This has been fixed on my side (Land Craft), so this issue can be closed.
