### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by warriorsofcats** [BluSunrize/ImmersiveEngineering#214]
I though this rather odd, because I don't remember that I change anything, other than updating Extra utilities, CoFH core, Thermal expansion and project red.
 
It crash after the world load up.

here is the crash report: http://pastebin.com/FqmmaL9d
I am using 0.4.1 version of Immersive Engineeering

Let me know if you need anything else

**Comment by BluSunrize** [comment]
I have no idea which mod is ASMing TileRenders there, but phoee on them.
I'll look into the issue, looks like it's easily fixable.

**Comment by warriorsofcats** [comment]
Glad to hear that it is easily fixable. :)

**Comment by warriorsofcats** [comment]
uuuhhh....
I think i found out which mod is doing that, it is Thermal Expansion, more specifically the energy cell from that mod, the crash happen when I place the connector on the energy cell. Hope this help.

**Comment by warriorsofcats** [comment]
After creating a new modpack in curse and use only Thermal Expansion and Immersive Engineering, and testing it out. I was wrong. Look like I am adding mod one by one testing each out. see ya in hours or two :P

**Comment by BluSunrize** [comment]
It's ForgeRelocation/MCFrames. They are doing bytecode modification to TileRenders. However, other things might potentially result in this bug as well, so it's good that I'll just fix it in general.

**Comment by warriorsofcats** [comment]
ok, that could be it, however... I think game just like to crash, because I delete every mod in mod folder that I have but the Immersive eningeering and the game still crash to the same crash log...

**Comment by warriorsofcats** [comment]
I find out that if you delete ImmersiveEningeering data file in date folder in your save folder fixed the problem, but it delete all the IE wire... but if I Replace it all and restart the client, it still works.
