### ISSUE TITLE
Entering the world

### ISSUE THREAD

**Issue by forestbat** [BluSunrize/ImmersiveEngineering#2140]
IE version：0.10-58
forge version：2297
When I‘m entering the world，the save will loading for a long time，and it will probably stop on the last word in the log。
[fml-client-latest.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1040898/fml-client-latest.txt)

**Comment by BluSunrize** [comment]
I can't actually see any crash there...

**Comment by mindforger** [comment]
the server is shutting down (normally) itself, but there is no obvious error or reason indeed, is this single or multiplayer?

**Comment by malte0811** [comment]
1. I don't see where the server is shutting down. The last thing I see is the ServerStarted event (+arc recycling).
2. The OP is using Optifine, BetterFPS and FoamFix, even though I don't think that it is the cause.
3. The arc recycling calculations are taking multiple seconds. This indicates that the system is either about to run out of memory (5GB are reserved) or that some mod is adding an insane amount of recipes. The generated recipes are added to the real list in a server tick, if the new recipe list is really big or the system is nearly out of memory adding them could potentially be slow.
@forestbat try disabling arc recycling in the IE config and tell us whether that fixes it.

**Comment by forestbat** [comment]
I disabled arc recyling of IE。
http://fuzhizhantie.com/pastes/9291
It cost 16 minutes to enter the save，from 17:26 to 17:42.
@mindforger @malte0811

**Comment by BluSunrize** [comment]
If Arc Recycling is disabled, then chances are it's not IE's fault.
Have you tried completely removing IE to see if that changes it?

**Comment by forestbat** [comment]
No，I haven't。
I don't think removing IE will solve it，so I'll close the issue。
