### ISSUE TITLE
Scaffolding won't go onto fluid pipes

### ISSUE THREAD

**Issue by DoctorDitto** [BluSunrize/ImmersiveEngineering#2141]
IE version: 0.10-58
Forge version: 2185
I've tried right clicking pipes with scaffolding as the manual says, but the scaffolding won't go on.

**Comment by theunkn0wn1** [comment]
Can confirm, I guess the feature never got ported from 1.10

**Comment by malte0811** [comment]
It was ported, it says so in the changelog and I used the feature myself. I send the OP here from reddit, I think this is the first time someone actually made a report because of that

**Comment by tahg** [comment]
Saying it's because it never got ported from 1.10 doesn't make sense when he's using 1.10.  Either way, it doesn't work as of 0.11-59-104 either.  It has been confirmed to work in 57.  I can't find any relevant commits since the 1st of March that might affect this, but hopefully someone more familiar with the code can find the problem.

**Comment by malte0811** [comment]
What exactly do you mean by "the scaffolding won't go on"? Does it just not render or is the item not removed from your inventory (test in survival mode)? I can't test this right now since I am on mobile.

**Comment by tahg** [comment]
The scaffolding gets placed as a normal block against the side that you clicked.

**Comment by malte0811** [comment]
I think I know what is causing this, if I am right I should be able to fix this in a few minutes.

**Comment by malte0811** [comment]
Fixed. For some reason the TE class was being loaded before the blocks were registered, so the registered pipe covers had null/air items and therefore obviously didn't match the scaffoldings.

**Comment by DoctorDitto** [comment]
So how do I apply this fix to my game?

**Comment by malte0811** [comment]
You don't, unfortunately. I can't think of a way to fix this without using new builds of IE, which Blu does not like.

**Comment by BluSunrize** [comment]
just putting this out there:
I'm currently very bogged down with Uni work, with multiple, larger tasks being due to next Monday.
Before then I probably won't find any time to work on IE or release any builds. I apologize for the delays, but that's the way it is.
