### ISSUE TITLE
[Suggestion] Agricraft support for garden Cloche

### ISSUE THREAD

**Issue by TokkenGmr** [BluSunrize/ImmersiveEngineering#2143]
Was wondering if we could get support for agricraft seeds inside the garden cloche?

**Comment by Bitterholz** [comment]
Is that not the case allready? 🤔

**Comment by TokkenGmr** [comment]
I do not think that it is, none of the agricraft seeds will go into the cloche. I tried using cactus, carrot, all the "flower seeds" none seem to work.

**Comment by BluSunrize** [comment]
The reason I excluded Agricraft is because it uses cropsticks, and has growth values on its plants. It's an entirely different system and designed to be used on big fields, which is why I chose to not support it.
