### ISSUE TITLE
[0.11-59-104] Inputting fluids into the Cloche spams the log of nearby players until cloche is turned off

### ISSUE THREAD

**Issue by Febilian** [BluSunrize/ImmersiveEngineering#2146]
A player on a dedicated server I'm running tried using a cloche for the first time with Embers pipes as the input/output, and it resulted in me - a nearby player - having ridiculous framerate lag from when it started until it was turned off.

https://paste.ee/p/RHnVh

Basically, that was spammed in the log constantly, and I had massive FPS lag until the cloche was turned off by the player nearby who was using it. What's especially odd is that the player who initiated the cloche didn't notice any framerate drops at all - but I, a player who was within a few chunks of them, definitely did.

I was told this was probably an issue with IE rather than Embers fluid pipes, so I'm reporting it here first.

I cannot reproduce this in single player with only Embers, JEI, IE, and Baubles installed. I'd guess it's either a mod interaction of some kind, or simply a server-specific issue.

These mods are currently on the server(I tried to generate a crash via the guidelines but had issues getting it to work. I'll try again if this is not enough information):

aether_legacy-1.11.2-1.0.jar
AkashicTome-1.1-7.jar
antiqueatlas-1.11.2-4.3.0.jar
astralsorcery-1.4.2.jar
AutoRegLib-1.1-4.jar
Baubles-1.11-1.4.4.jar
BedBugs-1.11.2-1.1.7.jar
BetterBuildersWands-1.11-0.11.1.239+9162f74.jar
BetterFps-1.4.4.jar
BetterThanMending-1.1.0.jar
BloodMagic-1.11-2.1.10-79.jar
Bookshelf-1.11.2-1.5.0.371.jar
Botania r1.9-343.jar
Chameleon-1.11.2-3.1.0.jar
Chisel-MC1.11.2-0.0.10.14.jar
chiselsandbits-13.10.jar
compatlayer-1.11.2-0.2.9.jar
CosmeticArmorReworked-1.11.2-v1a.jar
CraftTweaker-1.11.2-3.0.25.jar
CrystalCaves-1.0.jar
DarkUtilities-1.11.2-1.2.0.126.jar
embers-0.215.jar
EnchantingTable-1.11-1.1.jar
extraalchemy-0.3.2-beta.jar
foamfix-0.6.3-anarchy.jar
Forgelin-1.4.2.jar
FriendlyFire-1.11.2-1.0.1.jar
GiacomosFishingNet-1.11.2-1.5.1.jar
Guide-API-1.11.2-2.1.1-52.jar
harvestables-1.11.2-1.1.jar
hopperducts-mc1.11.2-1.4.9.jar
Hwyla-1.8.13-B26_1.11.jar
iceandfire-1.1.0.jar
ImmersiveEngineering-0.11-59-104.jar
immersivepetroleum-1.11.2-1.0.3.jar
InitialInventory-2.0.2.jar
InventoryTweaks-1.62+beta.88.jar
ironchest-1.11.2-7.0.19.803.jar
itemscroller-1.11.2-0.11.0.jar
jei_1.11.2-4.3.6.280.jar
librarianlib-3.1.4.2.jar
llibrary-1.7.6-1.11.2.jar
LootTweaker-1.11.2-0.0.6.3.jar
MKNUtils-mc1.11.2-2.1.1.jar
modular-routers-1.11.2-2.1.1.jar
MTLib-2.0.1.jar
NaturalPledge-r2.0.jar
NaturesCompass-1.11.2-1.3.0.jar
netherchest-0.1.jar
NetherPortalFix_1.11-4.3.1.jar
NoMoreRecipeConflict-0.8(1.11).jar
Quark-r1.2-92.jar
QuickLeafDecay-MC1.11.2-1.2.3.jar
redstonepaste-mc1.11.2-1.7.4.jar
roots-2-0.019.jar
RubberDucky-1.1.jar
Ruins-1.11.2.jar
rustic-0.3.5.jar
simplytea-1.2.jar
SpartanShields-1.11.2-1.3a.jar
stg-1.11.2-1.1.1.jar
StorageDrawers-1.11.2-4.2.6.jar
TeamUp-1.1.3-1.11.0.jar
torchmaster_1.11.2-1.3.3.37.jar
vending-1.11.2-1.4.3.jar
Waddles-1.11.2-0.5.2.jar
WearableBackpacks-1.11.2-2.3.2.jar
weirdinggadget-1.11.2-1.0.1-universal.jar

The Forge version being used is 13.20.0.2310.

Please let me know if there is some other information I can provide. I can try to ask the player in question exactly what he did when possible if this is not reproducible.

**Comment by malte0811** [comment]
I'd blame this on Embers. From the stacktrace it looks like the pipes are inserting fluid on the client, which they aren't supposed to do. We could put in some checks into IE as well to prevent this from happening, but as I said, this is probably Embers' fault.

**Comment by Febilian** [comment]
Yeah, we just did some more tests - it only happens with Embers pipes into the cloche. Sorry about that.

**Comment by BluSunrize** [comment]
Closing this then, because unrelated I guess?
