### ISSUE TITLE
NBT-Based item textures mess up on F3 + T [MC 1.10.2, IE 0.10-58]

### ISSUE THREAD

**Issue by Winseven4lyf** [BluSunrize/ImmersiveEngineering#2148]
When I go to reload my textures using F3 + T, most of the items that render their item using NBT tags instead of metadata use different textures, namely:
- Shaders
- Revolver Cartridges
- Voltmeter

The game doesn't crash when this happens, so a crash log is inapplicable.

The only other mods that I have currently add no items, namely:
- FastLeafDeay v11
- InventoryTweaks 1.62 dev 66
- jei 3.14.7.419
- journeymap 5.4.6

Possibly related to #1830

Here is a screenshot of the second time this happened:
![Those shaders look crazy!](https://cloud.githubusercontent.com/assets/17957142/26752163/270dee50-488d-11e7-8840-6b899b89b76c.png)

**Comment by Winseven4lyf** [comment]
And going off that possible relation to #1830, I am using my own resource pack, which is why the planks in the background look different.

**Comment by BluSunrize** [comment]
Can you reproduce this without a resource pack active?

**Comment by malte0811** [comment]
I have seen similar things without using texture packs in the past (watermills with pipe textures), that time it was caused by uncleared model caches. I have added the item (and coresample) model caches to the cleared caches, which should fix this. If it doesn't please put a comment here.
