### ISSUE TITLE
Multibloc Structure doesn't work

### ISSUE THREAD

**Issue by MinoCraft** [BluSunrize/ImmersiveEngineering#2149]
Hello,

I play with the last version of Immersive Engineering (v 0.10-58)
On my server, the assembler multiblock structure doesn't work then in my single player world the structure work 
As you can see on the pictures, I made the correct structure and convoyors have the same direction

First Layer
![2017-06-03_10 57 46](https://cloud.githubusercontent.com/assets/4315922/26752341/eec3e052-484d-11e7-8447-726fee55e1cc.png)
Second Layer
![2017-06-03_10 58 14](https://cloud.githubusercontent.com/assets/4315922/26752351/0d64f064-484e-11e7-9bd2-e4223fc93e81.png)
Third Layer
![2017-06-03_10 59 30](https://cloud.githubusercontent.com/assets/4315922/26752353/190837be-484e-11e7-91b9-16ddcaab307e.png)
Input Side
![2017-06-03_10 59 40](https://cloud.githubusercontent.com/assets/4315922/26752379/c3b9eb62-484e-11e7-80db-800661f33335.png)
Output Side
![2017-06-03_10 59 53](https://cloud.githubusercontent.com/assets/4315922/26752381/cb66937e-484e-11e7-9781-c177e2d64270.png)

When I'm ready to right click on input convoyor, it just rotate =/

Thanks in Advance !

**Comment by MinoCraft** [comment]
Oh sorry ! I forgot this infos =/
I play with:
- MineCraft 1.10.2
- Forge 12.18.3.2281
- Better FPS 1.4.4-1.10
- FoamFix 0.6.3 anarchy

**Comment by malte0811** [comment]
Blu was asking about server software (better FPS doesn't sound like server software to me). If you are not an admin of the server, ask the owner whether they are using sponge or similar software.

**Comment by MinoCraft** [comment]
On server there is only Forge (12.18.3.2281) and FoamFix 0.6.3 lawful ;)

**Comment by lemonbarking** [comment]
Might be related to this #2109 
No multiblock forms when using the redstone ignoring conveyors in the structure.

**Comment by BluSunrize** [comment]
@lemonbarking 
Well yes, duh, you're using the wrong conveyor. Use normal ones. =P

**Comment by MinoCraft** [comment]
Seriouly ! =/  Oups ! =/ I'm stupid =) I'm very sorry about that and Thank you for the invested time ;)
