### ISSUE TITLE
[0.10-57] Scaffolding + fluid pipe texture issue

### ISSUE THREAD

**Issue by Rusticpockets** [BluSunrize/ImmersiveEngineering#2152]
Using the FTB Direwolf20 1.10 modpack on a server.
![2017-06-06_12 54 31](https://cloud.githubusercontent.com/assets/26099469/26811829/8b1c8b8c-4ab7-11e7-86aa-6b0e59f533e0.png)
![2017-06-06_12 54 39](https://cloud.githubusercontent.com/assets/26099469/26811830/8b1e4206-4ab7-11e7-9428-e71f7d348d0d.png)
![2017-06-06_12 54 51](https://cloud.githubusercontent.com/assets/26099469/26811941/2993f41c-4ab8-11e7-90cc-a63af060b1bf.png)
![2017-06-06_12 55 06](https://cloud.githubusercontent.com/assets/26099469/26811942/29975864-4ab8-11e7-89a0-8b15cb0d203c.png)

![2017-06-06_12 55 10](https://cloud.githubusercontent.com/assets/26099469/26811831/8b1e9f6c-4ab7-11e7-9241-b32ea516ac0f.png)

(only the corner Aluminium scaffolding block was changed during these screenshots)
The textures for Aluminium and Steel scaffolding change based on where scaffolding had previously been placed on a fluid pipe, and also change based on the connectivity of the pipe to nearby blocks.
Works on any version of metal scaffolding.
This does not seem to work on treated wood scaffolding

**Comment by malte0811** [comment]
Known and (will be) fixed in 32e19f87883435af984f7076c267cba7468a50e3 which is part of pull request #2113.
