### ISSUE TITLE
Random crash when visiting nether

### ISSUE THREAD

**Issue by BeastOTL** [BluSunrize/ImmersiveEngineering#2153]
I am playing the DW20 modpack for 1.10, this isn't the first time i got this crash but the third actually. I have the chunk in which the cloche is placed chunkloaded in the overworld if that makes a difference. Here is the latest crash report:

[crash-2017-06-05_16.49.43-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1055251/crash-2017-06-05_16.49.43-client.txt)

**Comment by malte0811** [comment]
I don't know how this would happen by visiting the nether, but the crash is fixed for the next release.

**Comment by BluSunrize** [comment]
This has been fixed, fix released with Build 60
