### ISSUE TITLE
Mystical Agriculture Garden Cloche

### ISSUE THREAD

**Issue by PureNature** [BluSunrize/ImmersiveEngineering#2154]
All the recource crops from Mystical Agriculture are working perfectly in the garden cloche but all the diffrent tiers of inferium seeds arent working. Is this intended?

**Comment by SanAndreasP** [comment]
I've made a PR for this: https://github.com/BluSunrize/ImmersiveEngineering/pull/2156

**Comment by Ricket** [comment]
Could you please pull this into the 1.11 branch and spin a new release? Would be really nice to have it in the ATM2 modpack.
