### ISSUE TITLE
1.11-104 Bottling Machine Bug

### ISSUE THREAD

**Issue by darkshadow543** [BluSunrize/ImmersiveEngineering#2155]
How to reproduce this bug,
1) build the bottling machine,
2) right-click on any part of the multiblock,
3) it turns into the original block.
Another note is that using The One Probe does not show the multiblock, just the block right there.

**Comment by malte0811** [comment]
Please try using the latest 1.11 build (made about half an hour ago). I fixed this in 725e8def6004ebcbe329df74b236a383463b3358. The fix/workaround will probably partially break with some future forge version, either on 1.11 or 1.12, but I think that won't happen too soon.
