### ISSUE TITLE
[1.11.2] IndexOutOfBoundsException checking BoP recipes

### ISSUE THREAD

**Issue by Eufranio** [BluSunrize/ImmersiveEngineering#2157]
This crash will prevent clients from loading the game: https://hastebin.com/imobexuduz.sql
If you need more info just let me know.

**Comment by Landmaster** [comment]
@Eufranio This is closely related to the crash in #2138.

**Comment by Eufranio** [comment]
I was waiting the PR to get merged to close this issue tho :P
