### ISSUE TITLE
Covered conveyor not working?

### ISSUE THREAD

**Issue by TristenCocking** [BluSunrize/ImmersiveEngineering#2158]
The player can pick up items from a covered conveyor before they get out into the chest. The covered conveyor is directly next to and feeding into the chest

**Comment by BluSunrize** [comment]
Could you please provide pictures of your setup?
I believe I know the source of this issue and I have fixed it, but I'd like to confirm.

**Comment by BrisingrAerowing** [comment]
I'm seeing this as well. Here's a screenshot of my setup.

![2017-06-08_17 51 19](https://user-images.githubusercontent.com/250409/26952359-2a356f60-4c73-11e7-8cc7-69fa712879a8.png)

That's an EnderLink chest from the MultiStorage mod, but it should work exactly the same.

**Comment by BluSunrize** [comment]
Yeah the problem is the little moment between putting stuff on the conveyor and the next tick.
I have fixed this, just not released the fix.
See #2085, closing this since it's a duplicate.
