### ISSUE TITLE
Redstone Orchid rendering issue (Cloche)

### ISSUE THREAD

**Issue by FattestXayahNA** [BluSunrize/ImmersiveEngineering#2159]
I have redstone and a redstone orchid in a cloche that is kicking me from my server. I have rendering issues. I am using Sky Factory 3 mod pack but I added XNet.

**Comment by malte0811** [comment]
Probably a duplicate of #2071, can't tell for certain as you haven't included a crashlog. Fixed on 1.11, the fix will probably be back-ported to 1.10 at some point after 1.11 is released.
Are you just disconnecting or does your client close/crash?

**Comment by FattestXayahNA** [comment]
My client fully closes. I saw that it was working on 1.11 so I assumed it
would work for 1.10 lol

**Comment by malte0811** [comment]
Yeah, 1.11 has a bunch of bugfixes 1.10 hasn't (as well as a bunch of new bugs). Closing this since it is a duplicate.
