### ISSUE TITLE
HarvestCraft/SimpleCorn compat for Fermenter

### ISSUE THREAD

**Issue by darthvader45** [BluSunrize/ImmersiveEngineering#2160]
I remember that corn was well known for being a major crop used for ethanol.  Considering it has a big use in making ethanol, it should be one of the biggest sources for it, as the only 'best source' is industrial hemp seeds for their oil.  Ethanol should have its own 'best source' for more efficient ethanol farms.

**Comment by cleverpanda** [comment]
I've made Simple Corn support for corn a while ago. 120mb by default.

**Comment by darthvader45** [comment]
Okay, thank you.
