### ISSUE TITLE
No experience awarded for mining IE ores

### ISSUE THREAD

**Issue by TheQuadShot** [BluSunrize/ImmersiveEngineering#2161]
Minecraft 1.10.2
Immersive Engineering 0.10-58

Players should get some mining experience for "your" ores

**Comment by KnightMiner** [comment]
Aren't all the ores in Immersive Engineering metals, meaning they need to be smelted in order to produce a resource? Vanilla metals do not give experience when broken, just when smelted.

**Comment by TheQuadShot** [comment]
Sorry, I wrote that very poorly, True I don't get exp for blocks that drop ores, but I don't get any mining exp for when I process the ore, even in a vanilla furnace. I hope that makes more/better sense.

**Comment by BluSunrize** [comment]
They *do* award XP.
It's just little, and the lower the amount awarded, the lower your chance.

Iron gives .7, Bauxite gives .3. The math on the furnace slots is pretty wonky, but in summary:
Bauxite has a 30% chance to give you experience on smelting.
Gold (or IE's Uranium for that matter) has a 100% chance to give XP.

So XP is definitely awarded. Just rarely.

**Comment by TheQuadShot** [comment]
Ok, My RNG just hates me, Thanks and sorry for the hassle.
