### ISSUE TITLE
[1.11.2 - 010-58] Charging Station texture missing underneath

### ISSUE THREAD

**Issue by VallenFrostweaver** [BluSunrize/ImmersiveEngineering#2162]
If you look under a charging station there is a small area missing a texture at the front of it under the electrodes. See image below.
![09-06-17 1-43-51 pm](https://user-images.githubusercontent.com/13642054/26976036-23f1d15a-4d1a-11e7-823e-9e260adeb1cc.png)

**Comment by HappyPineapple** [comment]
oh year I remember this ep

**Comment by HappyPineapple** [comment]
hey @BluSunrize can you make some indoor lights like these electrodes.

**Comment by BluSunrize** [comment]
@HappyPineapple if you reply to one more issue with an unrelated, and terribly formatted question, I will **ban** you from my repositories.
This is an issue tracker meant to discuss issues with the mod, not a fracking reddit thread. Behave accordingly, or leave.

@VallenFrostweaver Thanks for hte report bud', I'll look into it ^^

**Comment by HappyPineapple** [comment]
sorry just deleted
