### ISSUE TITLE
[IE 0.11-59-113] Metalpress does not form Multiblock 

### ISSUE THREAD

**Issue by teamMK** [BluSunrize/ImmersiveEngineering#2163]
Hey,

i tested the latest 1.11.2 build but the metalpress doesnt form. i clicked every pixel of each block, but i can only rotate some of the blocks.

**Comment by lemonbarking** [comment]
Check to see if the conveyors that you are using are the ones affected by redstone control or not. The ones that ignore redstone control cannot be used in the construction of any mutliblock structures.
