### ISSUE TITLE
[1.11.2] Jerrycan cannot input fluid into a Fluid Tank

### ISSUE THREAD

**Issue by primetoxinz** [BluSunrize/ImmersiveEngineering#2164]
I assume that the Jerrycan is not picking up the Fluid Capability for the multiblock structure on activated and simply skips to placing it in the world.

**Comment by HappyPineapple** [comment]
Witch multi block structure? tank?

**Comment by primetoxinz** [comment]
yes, the Fluid Tank

**Comment by HappyPineapple** [comment]
k caus i had simauler prob with the tank i had fementer or squeser i cant remember wich but it wouldn't in put i tryed pumps but that did nothing to help the promlem.
ps I like penguins

**Comment by HappyPineapple** [comment]
but now i realise it was on 1.10.2 hm ?

**Comment by primetoxinz** [comment]
Yes, I imagine it existed in 1.10.2 as well, but that version is on major fixes only

**Comment by HappyPineapple** [comment]
?

**Comment by HappyPineapple** [comment]
can you explan?

**Comment by primetoxinz** [comment]
IE for 1.10.2 will not be receiving any more updates, as far as I know

**Comment by HappyPineapple** [comment]
hang on I just up dated it like to day!

**Comment by HappyPineapple** [comment]
ps why would you whan to kiss a linikx penguin ?

**Comment by BluSunrize** [comment]
Messages were not contributing to the issue at all (and the spelling and grammar was horrendous) so they were removed.
Thanks for the issue primetoxinz, we'll look into it.

**Comment by HappyPineapple** [comment]
shure no prob ps I realise THIS will probaly be deleted

**Comment by malte0811** [comment]
Fixed.
