### ISSUE TITLE
Collaboration With Other Mod Authors

### ISSUE THREAD

**Issue by HappyPineapple** [BluSunrize/ImmersiveEngineering#2165]
So I have A Great Idea That Will probably be noped so here it is.

Have You heard Of Professor Flax Beard & and the mod Author for rail craft so you know how you said no to my idea for vehicles BUT WAIT you do not have to include trains the mod Author for rail craft will so now your wondering who is Professor Flax Beard is he is the creator of Professor Flax Beard's Steam Power so I know what your going to say  ImmersiveEngineering is not Steampunk .... (by BluSunrize) so why I am saying is Have a Pre Immersive Engineering type that is COMPATIBLE WITH Immersive Engineering ! ALL I ASK THANK YOU FOR READING AND HAVE A NICE DAY!
P.S. I Have a Modpack With Your Mod In It ill link it to you here vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
[
](https://minecraft.curseforge.com/projects/the-unofficial-immersive-engineering-modpack)

**Comment by HappyPineapple** [comment]
https://minecraft.curseforge.com/projects/the-unofficial-immersive-engineering-modpack

**Comment by HappyPineapple** [comment]
@BluSunrize

**Comment by HappyPineapple** [comment]
@

**Comment by BluSunrize** [comment]
Mate...come on. At least structure your post in *some* way. That's basically unreadable.
And yes, thanks, I know who Flax is. He's a pretty nice fella.

And no, I'm not making a "Pre-IE" mod.

**Comment by HappyPineapple** [comment]
no iment as in make compatibility

**Comment by HappyPineapple** [comment]
ps does this count as ''Noped''?

**Comment by HappyPineapple** [comment]
hey i'm like what how old am i again? oh year young under teenager just
