### ISSUE TITLE
[1.11.2] Crusher loses progress on chunk unload

### ISSUE THREAD

**Issue by Eufranio** [BluSunrize/ImmersiveEngineering#2169]
Put some stacks of ore to proccess, leave the game and join again. The crusher will be empty.

**Comment by BluSunrize** [comment]
Unable to reproduce this.
Is this single or multiplayer? Do you have a testcase of, say, 8 pieces of copper ore?
Also, which build was used?

**Comment by Eufranio** [comment]
I am using build 115, from Jenkins, and the [MTN - Concept](https://www.technicpack.net/modpack/magibeta-111.1024667/mods) modpack (on Technic Launcher). This error appears to be only on a server, I've reproduced many times putting like 6 stacks of ore to proccess, then reconnecting and they all are gone. If you're interested, you can join the server and test yourself.

**Comment by Dakedres** [comment]
Possibly getting a similar issue in 1.12
