### ISSUE TITLE
[1.11.2] Error on Core Sample tooltip

### ISSUE THREAD

**Issue by Eufranio** [BluSunrize/ImmersiveEngineering#2170]
![img](https://image.prntscr.com/image/XCOI9KnTRvahKXP6ntljaw.png)

This error is appearing in the tooltip of Core Samples. I just took a sample from a Core Sample Drill and it was what it gave me, and happens with **every sample** we take. 
It appears to be happening only on a server, in singleplayer it works just fine. The modpack I'm using is [MTN - Concept](https://www.technicpack.net/modpack/magibeta-111.1024667) (on Technic Launcher, I couldn't update the Curse pack because IE for 1.11 isn't released yet 😢 ).

**Comment by mindforger** [comment]
the image seems utterly broken

**Comment by Eufranio** [comment]
Hum?

**Comment by mindforger** [comment]
why i try to open it, i only get a download of a file with cryptic name and can not view it

**Comment by KnightMiner** [comment]
I see the image just fine. It shows `Format error: Sample Taken: %1$s ago` at the bottom of the tooltip.

**Comment by mindforger** [comment]
isn't webp designed to be viewed in a browser? none of my installed picture viewers can open it

**Comment by KnightMiner** [comment]
Try this then: [Screenshot](https://image.prntscr.com/image/XCOI9KnTRvahKXP6ntljaw.png). I pulled that from the HTML for the image, the main image source is probably some weird Github caching link.

**Comment by BluSunrize** [comment]
I'm failing to reproduce this, I need more info.
What System Language are you set to? Can you provide a debug crash with F3+C?

**Comment by malte0811** [comment]
This happens when the timestamp is missing, possibly in some other cases as well. I have no idea why it would be missing though, unless @Eufranio updated from some old (pre-timestamp) 1.10 version.

**Comment by Eufranio** [comment]
This world was created on 1.11 about three days ago (when I opened the issue about the wildcards crash). This error happens when the sample is taken on a server, I tested it in my server and got this error in the tooltip, in singleplayer it works fine.

**Comment by BluSunrize** [comment]
Yeah info like that "it's on a server" belongs in the original post.
That's why the contribution guidelines exist.
Which also ask for buildnumber, other mods, etc.

**Comment by Eufranio** [comment]
Want me to update the post with all info needed?

**Comment by BluSunrize** [comment]
Yes, that is indeed what my passive-aggressive post was aiming towards =P

**Comment by malte0811** [comment]
I have it working/non-working now, are you dealing with this or should I look into it? I feel like we are working on the same issues simultaneously.

**Comment by BluSunrize** [comment]
By all means, go for it ^^
I'll go back to modeling =P

**Comment by Eufranio** [comment]
Done :P

**Comment by malte0811** [comment]
Fixed to some degree. The client does not know about dimensions, it only knows the dimension it is in. I can't use the time from that dimension since the dimension the client is in and the dimension the sample was taken in weren't necessarily created at the same time. If the client doesn't know the dimension the sample is from it will now display a tooltip about the sample being from a different timezone, which IMO is a decent analogy.

**Comment by Eufranio** [comment]
Still
![img](https://image.prntscr.com/image/ID-SPH3EQgS-zjHkAFxRGQ.png)

**Comment by Eufranio** [comment]
Sorry, it's 1 build behind, it's fixed in latest 😄
