### ISSUE TITLE
[Bug 1.11.2] Redstone Wire Connector doesn't update color

### ISSUE THREAD

**Issue by Jomik** [BluSunrize/ImmersiveEngineering#2175]
When right clicking a Redstone Wire Connector on SMP, the color changes to orange, for output, and then never again, unless you quit the server and go back in. Making it seem like it actually does change mode (as seen by the text shown) but not updating the color.

The SHA1 of the commit I'm on is `b39b7a7472a5440535159f63808d8e9890a53067 `

**Comment by BluSunrize** [comment]
^ closed
