### ISSUE TITLE
[1.10.2 0.10-60] Formatting in Engineer's Manual broken

### ISSUE THREAD

**Issue by Overato** [BluSunrize/ImmersiveEngineering#2176]
When looking at the Engineer's Manual, I get text that looks like this:
![2017-06-14_17 15 01](https://user-images.githubusercontent.com/8131582/27160469-70e1223c-5129-11e7-9359-28f74bc1c28d.png)
![2017-06-14_17 15 18](https://user-images.githubusercontent.com/8131582/27160470-70e2305a-5129-11e7-8531-4311400b77f8.png)
![2017-06-14_17 14 50](https://user-images.githubusercontent.com/8131582/27160471-70e3651a-5129-11e7-8f72-1a067a429e7a.png)

Curiously, the entries provided by Immersive Petroleum work correctly, although I don't have pictures to showcase that.

**Comment by BluSunrize** [comment]
Could you please Hold F3+C to create a debug crash and link it here?

**Comment by Overato** [comment]
Hold F3+C does not force a crash, and cuts all keyboard input from Minecraft in my instance. I can still provide the latest crash report for a different bug, if it helps.
[crash-2017-06-15_01.14.32-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1079034/crash-2017-06-15_01.14.32-client.txt)

**Comment by BluSunrize** [comment]
What system language and game language are you set to?

**Comment by Overato** [comment]
English for both. Game is set to English US, tried switching to English CAN and still borked. English CAN for system

**Comment by malte0811** [comment]
I know what is causing that, even though I would be REALLY interested in what caused the cause: Something went wrong when cherry-picking ce7d78a43a15045bc9d61345c38cedde2437db80. The cherry-picked commit contains [this](https://github.com/BluSunrize/ImmersiveEngineering/commit/3c1c349a6f19b2fa711be934247b08a2c382deca#diff-5f481613904e64725ae03b2edaa59293) diff (You may have to click "Show").
@BluSunrize Fixing this shouldn't be hard (I'll do that right now), I'd be interested to know whether you did anything strange when cherry-picking this commit though. It looks like the file was read as ASCII (1 byte per char) when it is Unicode/UTF-8 (up to 4 bytes per char).

**Comment by malte0811** [comment]
Seems like this is a general problem with cherry-pick. I've fixed this now, I don't know if @BluSunrize will publish a new build though.

**Comment by BluSunrize** [comment]
Oh wonderful. I blame IntelliJ for that one >_>
Thanks for the fix Malte, I'll look into publishing a fix probably today, since a localisation error like that is pretty crucial.

**Comment by malte0811** [comment]
I don't think it's IntelliJ, I tried reverting your commit and re-cherry-picking from a shell, but that broke formatting as well.
If the IC2 jenkins/maven is still offline when you want to make a new build make sure to remove both IC2 and their maven from your local build script and build against some version from curseforge (in the libs folder). Otherwise it will keep trying to fetch the IC2 version list and fail after ~20 minutes (the latest IE jenkins build did that).

**Comment by BrisingrAerowing** [comment]
This is happening in 1.11.2-62 as well
@malte0811 @BluSunrize 

![2017-06-18_23 30 39](https://user-images.githubusercontent.com/250409/27268548-45c52ffa-547e-11e7-8694-011fa2d33e0f.png)
