### ISSUE TITLE
After connecting wire to Macerator (IC2) this crash happens

### ISSUE THREAD

**Issue by Snipe13051** [BluSunrize/ImmersiveEngineering#2177]
Link Crash log: https://pastebin.com/5AjvgrSt

After i connected lv wire to macerator my game crashed and i can't join my world back since the crash keeps going on. What i can do now? It's rly annyoing... 

If you need more informations please get in contact to me.

**Comment by malte0811** [comment]
I think this is a Minecraft Flux issue, tell them that `hasCapability` should not return true if `getCapability` is null.

**Comment by Snipe13051** [comment]
So what i have to do exactly? Something to change in AE2 config?

**Comment by malte0811** [comment]
How has AE2 anything to do with this? Or did you mean IC2? I haven't used Minecraft Flux, you could check whether they have a config option to disable EU/IC2 compat. That might fix the crash.
I think this is the first time I've had to deal with externally attached Capabilities. The concept is interesting, but it doesn't help with debugging at all.

**Comment by Snipe13051** [comment]
Disabled the compat for IC2 in immersiveengineering.cfg but the crash still there... :-/

**Comment by malte0811** [comment]
Not in the IE config, in the Minecraft Flux config!

**Comment by Snipe13051** [comment]
Hmm in MF there is just that:

# Configuration file

general {
    # Amount of MF when converted from 1 EU [default: 4; 1 ~ 400000]
    I:EUValue=4

    # Amount of MF when converted from 1 J (Makenism) [default: 1000; 1 ~ 1000000000]
    I:MKJValue=1000

    # Chunk Charger transfer (MF/t) [default: 2000000; 1 ~ 2147483647]
    I:chunkChargerTransfer=2000000

    # Energy Distributor transfer (MF/t) [default: 1000000; 1 ~ 2147483647]
    I:energyDistTransfer=1000000

    # Energy capacity for Vanilla Furnace [default: 50000; 1000 ~ 2147483647]
    I:furnaceCapacity=50000

    # Energy needed for Vanilla Monster Spawner to speed up [default: 500; 100 ~ 2147483647]
    I:mobSpawnerEnergyUse=500

    # Reports all capability-related crashes made by Minedraft-Flux online[default: true]
    B:onlineErrorReport=true

    # Checks if a newer Minecraft-Flux version is available[default: true]
    B:updateCheck=true

    # World Chunk Energy capacity [default: 20000000; 1 ~ 2147483647]
    I:worldChunkCapacity=20000000
}

**Comment by malte0811** [comment]
I have reported this to Minecraft Flux, I don't know when/if this will be fixed.
@Snipe13051 You could try using WorldEdit to set the block at (-995,67,167) to air. Minecraft Flux is telling IE that the macerator that it can interface with Forge Energy, but when IE asks for the actual FE handler, Minecraft Flux isn't giving us anything which breaks IE and most likely a lot of other mods.
