### ISSUE TITLE
Hemp seed issue

### ISSUE THREAD

**Issue by Victaria90** [BluSunrize/ImmersiveEngineering#218]
The hemp seeds don't seem to be part of 'listAllseed' dictionary this makes them unusable with mods like Agricraft.

**Comment by Auzze** [comment]
I have also been noticing that the farming station don't pickup the seeds or hemp

**Comment by BluSunrize** [comment]
@Victaria90 I hate those list entries. I think it's Pam's that introduced it
@Auzze You should report that to EIO, not me ^^

**Comment by hron84** [comment]
Also, hemp does not proivde an API to display growth percent in WAILA. And Agricraft support would be definitely good.

**Comment by Kubuxu** [comment]
Agricraft already supports it.

**Comment by hron84** [comment]
@kubuxu sounds good.

**Comment by hron84** [comment]
@Kubuxu it's really weird, since with IE 0.4.4 and AgriCraft 1.3.1 I cannot ever plant industrial hemp seed on crop sticks. Also, AgriCraft does not accept ImmersiveEngineering:seed as a mutation result. 

Could you tell me which version was good for you, and what part of the AgriCraft support worked?

**Comment by Kubuxu** [comment]
We are using AgriCraft 1.4. This might make a difference.

**Comment by hron84** [comment]
@Kubuxu ahh, i see. I did not guessed that because AC 1.4 is in alpha. But I will check it out.

**Comment by hron84** [comment]
@Kubuxu I checked AC 1.4 and I confirm it's working now. However, IE hemp planted on a farmland (vanilla way) still does not provide a growth information in WAILA. I would be very happy even if we can see a two-stage growth percent, one per occupied blocks.

**Comment by BluSunrize** [comment]
Woops didn't mean to close this

**Comment by hron84** [comment]
@BluSunrize thank you very much!
