### ISSUE TITLE
Redstone Wire Connector Render Bug

### ISSUE THREAD

**Issue by invisusira** [BluSunrize/ImmersiveEngineering#2181]
Switching from input to output and then back to input does not change the colour of the band. Seems to always happen. Multiplayer server with FTB Direwolf20 mod pack.

MC 1.10.2
Forge 12.18.3.2316
IE 0.10-58

![javaw_2017-06-16_09-34-16](https://user-images.githubusercontent.com/26560375/27228863-4f86572a-5277-11e7-85d7-5398c6a4802f.png)
![javaw_2017-06-16_09-34-28](https://user-images.githubusercontent.com/26560375/27228862-4f864dd4-5277-11e7-81aa-0b513462c3eb.png)
![javaw_2017-06-16_09-34-32](https://user-images.githubusercontent.com/26560375/27228864-4f8dec4c-5277-11e7-9517-8ef0adbe805e.png)

**Comment by malte0811** [comment]
I didn't know this affected 1.10 as well, I only ever noticed this on 1.11. I'll fix this one and look into fixing the other bug you reported, @BluSunrize said he wants to get a next last 1.10 release out soon.
