### ISSUE TITLE
Redstone Wire Connector does not work with Garden Cloche

### ISSUE THREAD

**Issue by invisusira** [BluSunrize/ImmersiveEngineering#2182]
As title says, Redstone Wire Connector does not appear to function with Garden Cloche. Multiplayer server with FTB Direwolf20 mod pack.

MC 1.10.2
Forge 12.18.3.2316
IE 0.10-58

![javaw_2017-06-16_09-30-05](https://user-images.githubusercontent.com/26560375/27229029-f9ba2122-5277-11e7-9285-d551a7576591.png)
![javaw_2017-06-16_09-30-20](https://user-images.githubusercontent.com/26560375/27229030-f9be23b2-5277-11e7-9277-4bdfc8eba6e1.png)
Garden Cloche functioning in both these screenshots (note test block with Redstone torch on the right).

![javaw_2017-06-16_09-32-59](https://user-images.githubusercontent.com/26560375/27229058-0cfbac92-5278-11e7-8ee8-6296888c29b4.png)
![javaw_2017-06-16_09-33-05](https://user-images.githubusercontent.com/26560375/27229059-0cfe4dee-5278-11e7-80c3-80f430a0d3b1.png)
![javaw_2017-06-16_09-33-10](https://user-images.githubusercontent.com/26560375/27229057-0cf54442-5278-11e7-96f8-7c4664186b86.png)
I/O chain

![javaw_2017-06-16_09-33-47](https://user-images.githubusercontent.com/26560375/27229067-14dc66cc-5278-11e7-98d0-2fcff99401f4.png)
Placing lever directly on the front of Garden Cloche works just fine, Cloche stops production here.

**Comment by malte0811** [comment]
Can you try build 60? There is a fix in that build that might fix this.
