### ISSUE TITLE
Treated Wood Scaffolding texture broken

### ISSUE THREAD

**Issue by angelnc1989** [BluSunrize/ImmersiveEngineering#2185]
Minecraft 1.10.2
Forge 12.18.3.2297
ImmersiveEngineering 0.10-60 and 0.10-61

[Picture](http://imgur.com/UDgfbQI)

I updated some mods in my 1.10.2 Modpack and now the texture for Treated Wood Scaffolding is kind of broken and other scaffolding placed on Fluid Pipes turns invisible.

I updated:

- Chisel
- ConnectedTexturesMod
-ElecCore
-ImmersivePetroleum

Yesterday I updated ImmersiveEngineering to the latest version and the issue persists. 
I guess this isn't your fault, but I thought you might have an idea what is causing this.

**Comment by BluSunrize** [comment]
Could you please produce a Debug Crash by holding F3+C?
After that just chuck it on pastebin or gist and link it here.

**Comment by angelnc1989** [comment]
Sure. 
[Debug Crash Log](https://pastebin.com/WYM5ZTKE)

Let me know if you need anything else.

**Comment by BluSunrize** [comment]
Well it's not Optifine, so that's good =P
I'd consider reverting Chisel, CTM and ElecCore, each of them individually, to check if any of them are responsible.
My bet would be on CTM, because I think they were changing stuff around...

**Comment by angelnc1989** [comment]
You were right. CTM was causing it. The newest version fixed it though.
