### ISSUE TITLE
Garden Cloche not working with conduits / transfer nodes?

### ISSUE THREAD

**Issue by lstanden** [BluSunrize/ImmersiveEngineering#2186]
Hi,

With the Garden Cloche now in SkyFactory 3.0.10, I went to use this with some EnderIO Item Conduits, and found that while the conduits connected, they couldn't retrieve items from the inventory.  I tend to avoid conveyor belts due to the interaction with item dislocator / magnets.

I also tried this with Extra Utilities item transfer nodes, and again they were unable to pull items from the inventory.

**Comment by malte0811** [comment]
Could you post pictures of your setup? The item output is the orange spot on the middle block of the cloche.

**Comment by KindarConrath** [comment]
Same result, connects to Cloche but can't pull out.

Minecraft: 1.10.2
Forge: 12.18.3.2316
Mods:
Immersive Engineering 0.10-61
Ender IO 3.1.193
JEI 3.14.7.420
EnderCore 0.4.1.66-beta
Forestry 5.2.17.376

**Comment by lstanden** [comment]
Sure, this is what I have in place right now.  I've tried many variations, but I understand this should work.

I've also updated to the latest version on Curse (0.10-61), which has the same issue

![2017-06-18_05 47 05](https://user-images.githubusercontent.com/1306326/27260799-bdaa3a78-53e9-11e7-9fe1-ef68c9ced04f.png)

**Comment by angelnc1989** [comment]
I noticed this too, but I thought it was intended since Conveyor Belts do work.

**Comment by BluSunrize** [comment]
Try putting the conduits on the bottom block and see if that helps

**Comment by lstanden** [comment]
I have tried the bottom block too to no avail.  The only place I haven't tried is underneath, but that's a rather inconvenient place to put a conduit.

**Comment by mindforger** [comment]
I noticed that pushing items into EIO item conduits generally does not work properly!
can you attach thermal dynamic itemspipes for testing? i suppose there is some inventory magic bihnd that issue for both ExU and EIO. Maybe the item is not presented in the output slot to be taken because it is beeing pushed at the same time (i could be utterly wrong but i noticed similar problems under similar circumstances with AE2 interfaces and item conduits)

**Comment by ToAsgaard** [comment]
Conduits on the bottom dont work either.  During testing I was able to get it to work with conduits briefly, and very randomly as it pumped items out into a chest.  Then it stopped working after I relogged.  Nothing changed so was just random that it pumped out around 5 melons to a chest.

**Comment by nhocchip** [comment]
Place an inventory (a chest) where the conveyor belts go and item conduit of that

**Comment by MokahTGS** [comment]
So you have to use conveyor belts to pipe items out of this?

**Comment by nhocchip** [comment]
Conduits don't work,where u place a converter place a chest and connect conduits to that

**Comment by BluSunrize** [comment]
@MokahTGS
I can't really *fix* the fact that EIO conduits don't have an inventory to push into. That's not on my side.

**Comment by lstanden** [comment]
Just to add to this, the Thermal Dynamics Itemducts do NOT work with the cloche either.  With and without servos, they fail to remove items.  Chests do still work, but obviously that's not an ideal solution.

**Comment by falizure** [comment]
mine worked fine with itemducts, im on mc 1.10 what version are you using?

**Comment by BluSunrize** [comment]
Ducts work fine for me in 1.12 too...

**Comment by ToAsgaard** [comment]
Same, they work np at all for me as well.  I'm betting you either have them
connected to the wrong spot, or have altered the output on the cloche using
a wrench/hammer if the ducts arent connecting to the cloche output.  If
they are connecting but arent moving the items out, then you are connected
to the wrong spot.  Should be the output on the middle layer of the block,
so head height.

**Comment by killmetohell** [comment]
Question do they work or not i haven't updated immersive engineering due i'm using a modpack the modpack is skyfactory 3 version 3.0.13 i planned to update immersive engineering due to i have same bug
but after reading this there seem to same for the bug for Immersive Engineering 0.10-61 so i don't know but should update it not because i don't know if updating it would fix it.

**Comment by BluSunrize** [comment]
It wouldn't fix this bug, there is no fix on 1.10
You should always run the latest IE available on that version regardless.

**Comment by killmetohell** [comment]
oh thanks

**Comment by AlthosSilver** [comment]
Recent update makes garden cloche only work once in every 20 tries and for maybe 5 minutes before its broken again

**Comment by AlthosSilver** [comment]
so far, the only mod that is worse than this is TechReborn, and that is because they are plagiarists and ignorant individuals to anything involving even basic programming.

**Comment by falizure** [comment]
you want to talk about bad, try extra utilities 2, we have are removing it from our 1.10.2 servers officially.

**Comment by BluSunrize** [comment]
@AlthosSilver if you're so happy to criticise this mod and others, why don't you submit a PR then to fix the issues?

**Comment by malte0811** [comment]
Or at least a proper bug report specifying which "recent update" you are talking about, what other mods you are using, minimal setup to replicate the issue, etc.
And if you are complaining about TechReborn because of their reaction to your bug report: Same thing applies, just saying "it's broken" doesn't give the devs any helpful info. Yes, they could have told you so, but depending on the amount of reports like your one they get their reaction I can understand them reacting like this.

**Comment by BluSunrize** [comment]
^ yeah what he said. He's the nice one after all.

If you have legit complaints, file a new issue following the contribution guidelines. But if you just come here to throw chairs around, save your breath.

**Comment by AlthosSilver** [comment]
I have submitted already once, some asshole on this fucking group deleted it and then sent me a fuck you message about it, even though i provided every available detail of information asked and more. So seriously. now you rank equal to Tech Reborn, which is fucking worthless and you should all just commit suicide and save the world the effort of having to deal with you.

**Comment by Squeegee** [comment]
Work Around:  Attach chest, and pipe from chest.  Conduit doesn't want to work directly connected to push output (regardless of active or passive), but attaching chest to push output, then piping from chest works fine.

**Comment by ThreeAxle** [comment]
Ironically, mini chests from Extra Util works for an output, for those looking for a more cosmetic solution than having a full size chest at eye level. And you guys need to give Blu less of a hard time about this. There isn't really anything he can do from his side. Loving this mod, it pleases me to have tech mod that's so pleasing to the eye.

**Comment by BluSunrize** [comment]
Plus, it's fixed in the latest 1.12 version, people are complaining about 1.10 here =P
