### ISSUE TITLE
[1.10.2] Toolbox gets "enchanted" glow when picked up

### ISSUE THREAD

**Issue by KindarConrath** [BluSunrize/ImmersiveEngineering#2188]
If you place an Engineer's Toolbox then pick it up by any means, it gets the enchanted glow.

Tested in Single Player

Minecraft: 1.10.2
Forge: 12.18.3.2316
Mods:
Immersive Engineering 0.10-61
Forestry 5.2.17.376
JEI 3.14.7.420
Ender IO 3.1.193
EnderCore 0.4.1.66-beta

**Comment by BluSunrize** [comment]
Hahahaha, guess that's my bad.
I made it so it would keep Enchantments (in case someone used Soulbound) and now it writes empty Enchantments to the item.
It's more funny than gamebreaking, I guess...

**Comment by Firedale** [comment]
Well, it IS a magical box... it can hold many things in the palm of your hand!

**Comment by drewcassidy** [comment]
Honestly its a huge distraction to have it glowing in the hot bar all the time, I would really like this fixed

**Comment by Carnaxus** [comment]
Also happens with the storage crates, I've got twelve not glowing and four glowing ones.
