### ISSUE TITLE
[1.11.2] Crash on right click of the capacitor bank when Inventroy Tweaks is installed

### ISSUE THREAD

**Issue by ParaMotor** [BluSunrize/ImmersiveEngineering#2189]
https://pastebin.com/PWzGFcbA

Without Inventory Tweak, there is no crash.
After the crash, the capacitor bank is on the chest armor slot (so it didn't disappeared).
Using:
forge-13.20.0.2315
ie-0.11-62
inventory tweaks 1.63+dev92

**Comment by mindforger** [comment]
https://pastebin.com/PWzGFcbA

**Comment by mindforger** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/2184#issuecomment-309264541
same issue different mod conflict

**Comment by malte0811** [comment]
Fixed for the next release. see https://github.com/BluSunrize/ImmersiveEngineering/issues/2184#issuecomment-309477222 for technical details.
