### ISSUE TITLE
Pipes

### ISSUE THREAD

**Issue by Doquekc** [BluSunrize/ImmersiveEngineering#219]
This is more of a request than an issue, but I'm new to this stuff, so please forgive my ignorance if this is not the appropriate place to make a request.  I would like to play minecraft using only your mod, but I would like to use pipes to help with automation, however, there are no fluid pipes within immersive engineering to allow for this, resulting in my having to use another mod that adds some sort of fluid transport.  Unfortunately, most of these other mods also add things that I don't like to play with and don't have config options to disable them, or the mod is too op (transporting fluids instantly), or aesthetically displeasing.  Anyway, I was just wondering if you could add some form of fluid pipes to immersive engineering, and maybe a tank, but if not, no worries.  Just a thought.  Thank you for all your hard work.  This is one of my favorite mods, and I am very glad to have the opportunity to use it.

**Comment by BluSunrize** [comment]
The request has been made a lot, but quite honestly, you can use IE just fine without any pipes.
The Fermenter/Squeezer/Refinery/DieselGen can all be placed directly against eachother, due to the fact that they auto-output their fluids.
And should you want to have them apart, you can always use hoppers, conveyor belts and glass bottles =P 
I don't intend on adding pipes for now, since various other solutions exist, but I'm leaving myself with the option.

**Comment by mindforger** [comment]
"thermal dynamics" add only pipes for items, fluids and energy, same goes for "buildcraft transport" module, another alternative "pressure pipes" there indeed are a load of other mods adding pipes without unwanted addon stuff :P you only need to search

**Comment by BluSunrize** [comment]
put a capacitor between them? xD

**Comment by Doquekc** [comment]
@BluSunrize
Thanks for your time and the quick response, I appreciate your consideration on the matter, and regardless of whether or not pipes are ever implemented I still thoroughly enjoy immersive engineering.

@mindforger
I am aware of all three of the mods you've mentioned, and more.  Trust me, I've looked.  Pressure Pipes was the mod I was referring to about being op and not aesthetically pleasing, and the other two add other aspects that I would rather do without for difficulty purposes.  I prefer a well balanced yet difficult mod pack.  However, thank you for your time and comment, as well.  I will probably utilize Buildcraft for the time being.

**Comment by Auzze** [comment]
I just use EnderIO fluid conduits for all my needs.

On Tue, Jul 14, 2015 at 4:14 AM, Doquekc <notifications@github.com> wrote:

> @BluSunrize <https://github.com/BluSunrize>
> Thanks for your time and the quick response, I appreciate your
> consideration on the matter, and regardless of whether or not pipes are
> ever implemented I still thoroughly enjoy immersive engineering.
>
> @mindforger <https://github.com/mindforger>
> I am aware of all three of the mods you've mentioned, and more. Trust me,
> I've looked. Pressure Pipes was the mod I was referring to about being op
> and not aesthetically pleasing, and the other two add other aspects that I
> would rather do without for difficulty purposes. I prefer a well balanced
> yet difficult mod pack. However, thank you for your time and comment, as
> well. I will probably utilize Buildcraft for the time being.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BluSunrize/ImmersiveEngineering/issues/219#issuecomment-121011269>
> .
>



-- 
Stuart (Auzze) Mitchell
Australia
