### ISSUE TITLE
[0.11-62] crashes dedicated server Forge 1.11.2 build 2315

### ISSUE THREAD

**Issue by kreezxil** [BluSunrize/ImmersiveEngineering#2190]
Notes:
     on startup, only when I add your mod

crash report:
https://gist.github.com/d218e0fc5b43af412632f7b394fb893d

fml server latest:
https://gist.github.com/e207cdc034c1363273d0559bd59e7a28

**Comment by mindforger** [comment]
is this a fresh world or added later, because it looks like a corupted world

**Comment by malte0811** [comment]
Does this happen without RedstonePlusPlus installed? From the log it seems like they are replacing some blocks with `null`. Did you change the RS++ config when you added IE?

**Comment by kreezxil** [comment]
Both rs++ and your mod were added to an existing world at the same time,
the config are default on both.

**Comment by malte0811** [comment]
I am pretty sure this is rs++ then, from the log it seems like they are doing some quite shady stuff. I don't know of any code in IE that could in any way cause this.

**Comment by InkDragon** [comment]
similar issue, pack is fine without IE add IE and crash
https://pastebin.com/uq2CNcA3

**Comment by malte0811** [comment]
@InkDragon: Fixed in HGP, see #2204
The original issue is probably RS++'s fault for substituting with null.
