### ISSUE TITLE
[1.10.2][0.10 -61]Silos don't want to play with RS and OC

### ISSUE THREAD

**Issue by maham** [BluSunrize/ImmersiveEngineering#2191]
When I connect a Silo to for example Refined Storage using it's external storage block, or Open Computers using it's Transposer block, I can only see 64 items (65 i RS) even if the silo stores a lot more items. I saw #1748 referencing this issue but nothing was said about a reason/solution. 
So the question is, will there be a solution to this or is this by design?

**Comment by malte0811** [comment]
For RS see raoulvdberge/refinedstorage#984.
Only one full stack is available for IO purposes, but we can add an OC method to check the total amount stored.

**Comment by maham** [comment]
Sounds fair. An OC method to check the amount would be nice. I'll close this issue now that I had my answer.

**Comment by malte0811** [comment]
And I'll reopen this issue so I have a reminder to actually add the method. If this remains closed I am pretty sure I will never add it.
