### ISSUE TITLE
[Mod Compat / Integration] Infinite Fluids Mod

### ISSUE THREAD

**Issue by BrisingrAerowing** [BluSunrize/ImmersiveEngineering#2192]
Could support for the [Infinite Fluids mod](https://minecraft.curseforge.com/projects/infinitefluids) be added to the fluid pump? I use it to make lava an infinite fluid in the Nether (because why not), and would like to use the IE pump to pump it, but that pump simply replaces lava with cobble when pumped. I currently use Mekanism's electric pump for this as a kind of workaround.

**Comment by Cyprex** [comment]
Try right clicking it with a hammer to make it not replace fluids with cobble
