### ISSUE TITLE
[1.11.2] 1.61 Manual format errors

### ISSUE THREAD

**Issue by LiEyWe** [BluSunrize/ImmersiveEngineering#2193]
As the title says, there are format errors in the manual with the page links.
Pic: http://imgur.com/a/0CBFS

**Comment by BluSunrize** [comment]
Yep. We know.
Closed by https://github.com/BluSunrize/ImmersiveEngineering/commit/a3b4093030acf1e078afd7c66e44d94fd2f43ca2
