### ISSUE TITLE
[1.10.2] Tesla coil hurts more instead of dealing no damage with the faraday armor

### ISSUE THREAD

**Issue by JAWSAWN** [BluSunrize/ImmersiveEngineering#2195]
Equipping Faraday armor damages you even more instead of reducing the damage.

Immersive Engineering Version: 0.10-61

**Comment by BluSunrize** [comment]
Is your Tesla coil configured to high output? Because yes, it will melt the armor to your skin and kill you real fast. That's why you switch it to low power mode.  =P

**Comment by JAWSAWN** [comment]
Oh that's horrendous xD

But isn't it scientificly accurate that faraday armor/chainmail should protect you on even the harmful arcs?

**Comment by JAWSAWN** [comment]
Also something is off, all the other

**Comment by JAWSAWN** [comment]
Didn't know it had high and low modes.

**Comment by BluSunrize** [comment]
Well that feature design was @malte0811 's call =P

As for knowing about the modes: That's what the manual is for. Tesla Coil, page 3&4.

**Comment by mindforger** [comment]
it is absolutely accurate imho, the ssuit is not made of superconductive material, so it will convert some of that electricity to thermal energy ... if there is enough energy flowing, it will melt!

just look up some videos of static charge dissipators on buildings and lightning absorbers, they all will melt down over their "use"

**Comment by malte0811** [comment]
To be honest it isn't accurate at all (it takes quite insane amounts of current to break a faraday suit, see [here](https://youtu.be/MOzNioSGf8U). A TC output has a couple of 10 A peak for big coils). I wanted to have a faraday suit, Blu wanted the TC to be useful as a weapon. So I suggested the compromise of adding a mode to the TC in which a Faraday suit works and one in which it harms the user. If you know how TC's work IRL, maybe imagine that in high-power mode the primary is somehow connected to the arc by a low impedance or something like that.

**Comment by JAWSAWN** [comment]
But if you think about survivial-ability, it does make sense to defend your base.

**Comment by BluSunrize** [comment]
All the more reason. This way, people can't sneak through your defenses with a Faraday suit. The suit only exists for cool light shows anyway =PAm 20.06.2017 09:52 schrieb JAWSAWN <notifications@github.com>:But if you think about survivial-ability, it does make sense to defend your base.

**Comment by malte0811** [comment]
Speaking of cool light shows, if anyone here lives near Recklinghausen (North-Rhine-Westphalia):
There will be big HV shows (hourly from 9pm to 1am) as part of the Extraschicht this saturday (24.) evening at the Umspannwerk Recklinghausen. I recommend going there. They have a 4.5m high Tesla coil, someone in a faraday suit, a faraday cage people from the audience can go into, a 800kV Marx/impulse generator, a 100kJ capacitor bank (discharged through a piece of wire in a very short time) and a lot more. Tickets for the Extraschicht are 14-17€ including bus costs (and access to a bunch of other shows that night).
