### ISSUE TITLE
Hempcrete and Hempcrete Tile

### ISSUE THREAD

**Issue by mallrat208** [BluSunrize/ImmersiveEngineering#2197]
Currently the Hempcrete block closely resembles the Concrete Tile block in that they both have a border and would probably be better named as Hempcrete Tile.

 It would also be awesome to have a version of Hempcrete that has no border just like the default version of Concrete does. I personally like the overall color of Hempcrete, just not the repeating border you get because of it's Tile texture.

**Comment by Ravalli03** [comment]
Yes, I agree with this request!

**Comment by darthvader45** [comment]
Also, hempcrete could have a barely noticeable greenish tinge to it, to show the hemp used in it.

**Comment by KaiIsCool** [comment]
ive noticed this too, but didnt think art-related requests should go here. anyway, i agree that it should be changed.
