### ISSUE TITLE
Severe lag with build 61

### ISSUE THREAD

**Issue by robertmaxton42** [BluSunrize/ImmersiveEngineering#2198]
I'm experiencing very heavy load with IE 0.10 - 61, both serverside and clientside. Serverside, my server that usually runs around 10ms/t jumps up to ~58ms/t when I upgrade IE from 58 to 61 - it's low enough that I don't notice but the console definitely does, popping up with "can't keep up!" messages every few seconds. Clientside, the lag doesn't appear in a void world *or*, oddly enough, in my IE factory room full of machines, but once I try to go outside, the world half-renders, reaches a certain (consistent) radius, and then freezes. Shortly afterwards, my entire computer freezes, and I have to hard reset it. All symptoms vanish when switching back down to 58.

At a *guess*, there's some block that IE recently modified in the world that isn't properly being rendered? I don't know why that would cause what's probably a memory leak, though. If it would help I could post a screenshot of the base from above next time I load, though I dunno how detailed it would be.

I don't have a crash log because, well, no crashes, but here's the System Details bit and the Coremods bit of a previous crashlog (I haven't changed the modlist since): https://pastebin.com/5aBnyYda

Currently experimenting with build 60; I'll update this when I get the results.

**Comment by robertmaxton42** [comment]
Build 60 is significantly improved, in that it doesn't crash my computer. Serverside lag is still present, however. Tomorrow I'll boot up 58 again and check to see if it really does go away as I thought it did.

**Comment by malte0811** [comment]
I just glanced over all new commits in build 61 and I can't see any obvious problems. Could you try using [sampler](http://files.player.to/sampler-1.71.jar)? Add it as a mod to the server, run the command "/sampler start", then wait a few minutes while it is lagging and run "/sampler stop" and "/sampler export IELag.nps" (the syntax may be slightly different, but the error messages should show what went wrong). This should generate a file in your server directory with profiling information (i.e. what is taking how much time). Please upload that file to DropBox etc and send a link here.

**Comment by robertmaxton42** [comment]
Err... that jar doesn't seem to work. https://pastebin.com/ZK1HSUhv

**Comment by malte0811** [comment]
Sorry, the link I send was for 1.11. I currently work on 1.11, so it was the "natural" choice for me. [This](http://files.player.to/sampler-1.69.2.jar) should be the 1.10 version.

**Comment by mindforger** [comment]
i think a freind of mine is experiencing the same issue, we just updated last evening and he complained about heavy lagging this morning, will hand in results from our side too if helpfull

**Comment by robertmaxton42** [comment]
Here you go:

https://www.dropbox.com/s/lfgzeai5fyyf8sa/IE.nps?dl=0

**Comment by mindforger** [comment]
we were not able to reproduce the heavy load situation again, probably something else that caused it
