### ISSUE TITLE
Rendering crash

### ISSUE THREAD

**Issue by CatDany** [BluSunrize/ImmersiveEngineering#22]
I crashed when right-clicked an MV Wire Connector with a Wirecutter. It had 2 connections. Maybe I accidentally double-clicked, I don't know for sure.

Built it myself, last commit when synced is 67766541ee92d2159eba359e77ab6e523be1bf4a
Crash log: http://pastebin.com/4sjK15zQ
Full log: http://pastebin.com/cRwfM1gA

**Comment by CatDany** [comment]
Apparently tried to render connections when there's none of them. Sync issue? I don't know.
https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/client/ClientUtils.java#L46

**Comment by BluSunrize** [comment]
closed for now, might be reopened in future
