### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: what it means?change it here?change to what?

### ISSUE THREAD

**Issue by VictorSPM** [BluSunrize/ImmersiveEngineering#2200]
}

potions {
    I:Conductive=74

    # The potion ID for the Flammable potion effect
    I:Flammable=72
    I:Slippery=73
    I:Sticky=75
}

**Comment by malte0811** [comment]
Please don't open new issues for questions regarding old ones. I have commented on the other issue, delete the potions section (the bit you posted) and let IE regenerate it on its own.

**Comment by VictorSPM** [comment]
thx
