### ISSUE TITLE
[Suggestion] Sawmill?

### ISSUE THREAD

**Issue by Nightcaste** [BluSunrize/ImmersiveEngineering#2201]
Considering the aesthetic of Immersive Engineering, I'm kind of surprised the mod doesn't contain a Sawmill type multiblock.  I am picturing something similar to the metal press, with a big disc blade where the actual press section is.  Maybe even two versions, one made with treated wood and iron blade, and an upgraded version using steel scaffold and steel blade.

**Comment by BluSunrize** [comment]
Yeah I have ideas and plans, just nothing fixed yet.
Definitely on the todo, maybe in the next month or two.
