### ISSUE TITLE
1.11.2-0.11-62 NullPointerException

### ISSUE THREAD

**Issue by TwitchtvCarbs** [BluSunrize/ImmersiveEngineering#2204]
Getting a null pointer when loading up the game as seen below:

https://pastebin.com/50ge3ufk

Forge 13.20.0.2315

It seems to be something conflicting with Horizontal Glass Panes causing the crash, I removed HGP temp and the pack loaded up.

Really excited to see this mod for 1.11 though! :D

**Comment by tobystrong** [comment]
Reading through this it actually seems to be on my end, I'll have a look into it

**Comment by tobystrong** [comment]
Fixed in the latest version of HGP, nothing wrong with IE as far as I can tell. :)
