### ISSUE TITLE
GArden cloche and redstone crash

### ISSUE THREAD

**Issue by Mikecolle** [BluSunrize/ImmersiveEngineering#2205]
upon putting redstone and a red orchid into a garden cloche it causes the game to crash

**Comment by BluSunrize** [comment]
You're probably running an outdated version of IE. Please look into updating first.

**Comment by Mikecolle** [comment]
also is crashing with endstone and enderlilly. ah direwolfs pack didnt update it yet makes sense

**Comment by BluSunrize** [comment]
Well you will need to update it manually then, but this issue has already been fixed.
Please check the contribution guidelines next time, as they tell you present version numbers and always make sure you test on latest.
