### ISSUE TITLE
[1.10.2 to 1.11.2 conversion - 0.11-62] Railgun only fires 2 shots now?

### ISSUE THREAD

**Issue by VallenFrostweaver** [BluSunrize/ImmersiveEngineering#2207]
I'm also having an issue where my Railgun since the conversion is now displaying less energy and once I remove any parts and replace it only stores a max of 1600 IF (2 shots worth). 
![railgun after](https://user-images.githubusercontent.com/13642054/27430286-e1724578-573f-11e7-8add-fcfc1d6abdfe.png)

**Comment by BluSunrize** [comment]
Intentional. You're supposed to use the Capacitor Backpack with it.

**Comment by VallenFrostweaver** [comment]
Ah jeez. *facepalm*
