### ISSUE TITLE
[1.11.2 and prior - 0.11-62] Charging station visual issues

### ISSUE THREAD

**Issue by VallenFrostweaver** [BluSunrize/ImmersiveEngineering#2208]
Rarely I get this texture for the charging station upon placing the rail gun inside. I have also had an issue where all transparent glass of the charging station dissapears as well. You can reproduce these if you have 2 railguns and swap them in a charging station repetitively - otherwise it may happen at random if you are just using it for normal use. I've seen this since 1.10.2 v0.58 and have only just now been able to reproduce it to report it.

No texture
![charging station](https://user-images.githubusercontent.com/13642054/27430594-0d574f5c-5741-11e7-8de3-2ddfe66f2bc8.png)

No glass
![charging station glassless](https://user-images.githubusercontent.com/13642054/27430682-5b12c29e-5741-11e7-8ced-c5d4671eb8d3.png)

Just fine
![charging station goody](https://user-images.githubusercontent.com/13642054/27430687-6087f69a-5741-11e7-9a32-03fba19756ca.png)

**Comment by malte0811** [comment]
I *think* I fixed this, I am not sure though. The new Jenkins build should be available in roughly 10 minutes (Build 158), could you try whether it happens for you with that build?

**Comment by VallenFrostweaver** [comment]
Sure thing
