### ISSUE TITLE
[1.10.2 to 1.11.2 conversion - 0.11-62] Tank cut in half for conversion on chunk boundary

### ISSUE THREAD

**Issue by VallenFrostweaver** [BluSunrize/ImmersiveEngineering#2209]
Converted to 1.11.2 and noticed a tank had a dark texture:
![dark fluid tank](https://user-images.githubusercontent.com/13642054/27431098-256a336e-5743-11e7-9b8c-6751d13b2e05.png)

So I broke a single block and replaced it. This is what I saw:
![tank broken](https://user-images.githubusercontent.com/13642054/27431113-36b784dc-5743-11e7-98e3-cd07122d9aa1.png)

Suspected it was a chunk border and it is:
![chunk boundaries](https://user-images.githubusercontent.com/13642054/27431125-421e56ca-5743-11e7-9fcc-0c0c66ea9662.png)

**Comment by BluSunrize** [comment]
The conversion system was a bit experimental, I think.
It works for *most* things, so I guess that's good? =P

**Comment by VallenFrostweaver** [comment]
Yes! It was VERY welcome. Thank you for that. Not sure if you even want to tackle this stuff so up to you to close or not.

**Comment by mindforger** [comment]
from the images it looks like the right hand back leg is inside a dirt block when compared to the last picture ... did the whole multiblock move a block ??? how could it have been formed prior?

**Comment by VallenFrostweaver** [comment]
I agree and not really sure.

**Comment by mindforger** [comment]
@BluSunrize did you use an "finite improbability drive" to convert the structures? :D

**Comment by BluSunrize** [comment]
I didn't convert nothing!
@malte0811 rewrote the universe! D:

**Comment by malte0811** [comment]
I'll try to fix this (or at least understand why this is happening) some time in the next few days, I am a bit busy right now.

**Comment by BluSunrize** [comment]
I'd almost say don't worry about it.
The conversion thing is rare usecase anyway.

**Comment by VallenFrostweaver** [comment]
I agree with Blu. Maybe at most put a "At your own risk" notice in there on the notes and move on. Save yourself the time/effort. It worked better than I had hoped tbh.

**Comment by mindforger** [comment]
@malte0811 if you rewrote the universe already, please hand out a guide to hitchhike it at least :P sorry for the bad puns though but i really could not resist 

this block shift is really funky, i will definately test this out
