### ISSUE TITLE
RF>EU conversion broken

### ISSUE THREAD

**Issue by nanakisan** [BluSunrize/ImmersiveEngineering#221]
https://imgur.com/a/Kj4BC

As shown Capacitor was a filled HV Capacitor. However upon attempt to convert into the empty MFSU the RF drains. But is not actually being stored into the block. Conversion from EU to RF works as expected and then some. Just not the other way around it seems.  
  
I'm not sure if this is on your part or on IC2-Classics side.

Mods affected
ImmersiveEngineering v0.4.1
IC2 Classic Version 1.0.9.10

Forge version 1448

**Comment by BluSunrize** [comment]
http://puu.sh/iYzt0/35f0e87ac0.jpg

Works fine for me. Might be because you're using Classic, I used Experimental to create IE.

**Comment by nanakisan** [comment]
Which is weird cause Classic uses the experimental API so it's compatible with addons.

**Comment by nanakisan** [comment]
Hmm seems to be a cross mod issue with your use of the API with IC2-Classics API. When I used Mekanism's universal cable the RF conversion was spot on. you can close this now if you wish. Seems to be on Speigers hands with how he used the API in his mod.
