### ISSUE TITLE
[1.10.2 to 1.11.2 conversion - 0.11-62] Improved Windmills kinda went derpy and broke

### ISSUE THREAD

**Issue by VallenFrostweaver** [BluSunrize/ImmersiveEngineering#2210]
Upon converting to 1.11.2 this happened:
![windmill derp](https://user-images.githubusercontent.com/13642054/27431212-99c5654e-5743-11e7-89e2-461627ac7c3d.png)

Upon breaking/replacing the Improved windmill will not change direction or start working regardless of what direction I am facing when placing or side I place it on.

Personal Note: Just wanted to say that I am VERY happy that you converted to 1.11.2 and I love the new textures and changes! I am not complaining at all about these reports I'm submitting. Just letting you know. <3

EDIT: Upon removing and adding the tier 1 windmill and upgrading as intended all is fine but the old windmill is still broken and trash. Plus the textures on it are not all pretty like the new ones are.

**Comment by BluSunrize** [comment]
Improved windmill was fully removed from the game. You may throw it away, it's not supported anymore because the normal windmill was changed to be upgradeable ^^

**Comment by Carnaxus** [comment]
Well here's a related question then: If it was fully removed, why didn't it just vanish when he upgraded the mod?

**Comment by BluSunrize** [comment]
Because players were given the choice of keeping their world between certain upgrades and fully removing a block would have fucked up the registry and meta distribution.

**Comment by Carnaxus** [comment]
Ah, that makes sense.
