### ISSUE TITLE
[1.11.2 - 0.11-62] Windmill collision

### ISSUE THREAD

**Issue by VallenFrostweaver** [BluSunrize/ImmersiveEngineering#2211]
The windmill collision detection as well as other windmills stacked detection seems spot on but when I stack them 90 degrees to each other there's no detection. If this is fine or working as intended then please close this issue. (was receiving 136 IF p/tick from these 4 together.
![windmill crash](https://user-images.githubusercontent.com/13642054/27432418-ee11826e-5747-11e7-8ec8-4a06e7589f79.png)

**Comment by PrincessRTFM** [comment]
I really hope that's not intended.
