### ISSUE TITLE
[1.11.2 - 0.11-62] RTFM text bug

### ISSUE THREAD

**Issue by VallenFrostweaver** [BluSunrize/ImmersiveEngineering#2212]
See text images below.
![manual](https://user-images.githubusercontent.com/13642054/27433416-8b3bcd98-574c-11e7-8550-02da5102924f.png)
![manual 2](https://user-images.githubusercontent.com/13642054/27433418-8ce36cf0-574c-11e7-9974-890cd6cbca32.png)

**Comment by BluSunrize** [comment]
Yup, known issue, IntelliJ decided to kill my formatting many a times. 
Fixed by this:
https://github.com/BluSunrize/ImmersiveEngineering/commit/28b7905c46b730057ef3bc912237cb75e1f97709

**Comment by VallenFrostweaver** [comment]
oops! forgot to check for closed. my bad
