### ISSUE TITLE
Metal Press won't form after new update. 

### ISSUE THREAD

**Issue by Ravalli03** [BluSunrize/ImmersiveEngineering#2215]
I can no longer get the metal Press to form as when hitting the piston with hammer causes piston to rotate, and won't form the multi block. I have tried everything from different angles, conveys facing the other way, etc. Playing on single player with twitch on 10.2

**Comment by BluSunrize** [comment]
Pictures, version numbers, modlist. Read the contibution guidelines.

**Comment by AtlantisRising** [comment]
I sadly don't have pictures at the moment but I do have some extra details where I was unable to get the Metal Press to form as well.  Using FTB Beyond 1.10.0 (MC version 1.10.2), mod list is a long one but visible at https://www.feed-the-beast.com/projects/ftb-beyond/relations/dependencies .  Immersive Engineering is on ImmersiveEngineering-0.10-61 in both Client and Server.

After placing the blocks in their appropriate locations, the manual instructs to right-click the Piston with the engineers hammer.  When hitting the piston with the hammer on a Multiplayer standalone server (not a Single Player "Opened to LAN"), the piston spins repeatedly.  However, the exact same setup in Single Player does correctly form the Metal Press, as long as both conveyors are facing the same direction, and the piston is facing downward.  I tried breaking and replacing the piston about a dozen times on Multi with no changes to the setup.  I can get pictures later if it will help with this, but knowing that it crafts in Single and not in Multiplayer my gut tells me it's not a mod conflict - Singleplayer and Multiplayer both have the same mods installed.

Also worth noting, in Single Player the orientation of the piston doesn't seem to matter, as once it spins to be facing down, the next right-click creates the Metal Press.  In Multi, it doesn't matter if it was facing down before ever right-clicking it, or if it was facing another way.  It just spins freely.

**Comment by BluSunrize** [comment]
Have you checked that you are using normal conveyors and not the redstone-ignoring ones?

**Comment by AtlantisRising** [comment]
Well now I feel like a true moron, didn't realize there actually _was_ redstone ignoring belts >_<  Works fine if you actually follow the instructions fully, sorry for wasting your time!
