### ISSUE TITLE
[1.11.2 - 0.11-62] Nesting a capacitor backpack in another eats the nested backpack

### ISSUE THREAD

**Issue by VallenFrostweaver** [BluSunrize/ImmersiveEngineering#2216]
crafting 2 capacitor backpacks together results in 1 capacitor backpack that will not uncraft to 2 like other armor sets effectively destroying 1. Perhaps turn that option off for capacitor backpack nesting if that's a thing?

**Comment by BluSunrize** [comment]
That shouldn't even have happened in the first place! D:
Is this on a server or singleplayer?

**Comment by darthvader45** [comment]
I know this isn't relevant, but how does one charge up a capacitor backpack?

**Comment by malte0811** [comment]
IE has a charging station. Right click on it with the pack to put it in there, right click again to get it out.

**Comment by darthvader45** [comment]
Huh, looked it up, didn't see it.  Using 1.11.2-build 62.

**Comment by VallenFrostweaver** [comment]
Single player. You can keep nestung them too, justnever het them back out.

**Comment by malte0811** [comment]
Fixed. Interestingly the bug you reported is NOT nesting the packs, it is *repairing* the packs with each other like you can do with half-damaged bows.
