### ISSUE TITLE
[Suggestion]  Mechanical power?

### ISSUE THREAD

**Issue by darthvader45** [BluSunrize/ImmersiveEngineering#2217]
@BluSunrize 
Perhaps a way of using windmills/water mills as a way of operating mechanical machines for grinding wheat into flour?  Might sound more medieval than dieselpunk but it might be interesting, as the process was revolutionized with fully-automatic mills in the 18th century, and were further optimized well into the dieselpunk era.  Strangely enough, stone mills are still in use today, as some people prefer the nutty taste and higher vitamin content of stone-ground flour.

**Comment by enzyme-a113-2** [comment]
Better With Mods is a mod that does just this (and has compatibility)

**Comment by darthvader45** [comment]
Yeah, but I'd rather keep the mods installed to a minimum.
