### ISSUE TITLE
Creosote Oil exist on single player client but NOT server

### ISSUE THREAD

**Issue by tekkz** [BluSunrize/ImmersiveEngineering#2219]
I can create creosote oil on single player but when I log into my server and try it doesn't work.

Black/pink textures when created by coke oven - will not go into bucket/bottle nor can it be pumped out
JEI shows black/pink textures
Creative mode shows nothing when searching for "creosote"

I have tried changing the config files to turn off compat for railcraft on both server and client.

**Comment by Boomflex** [comment]
Also happening on our Official All the Mods 2 server.

Cannot pull out of Coke Oven at all in SMP.

Immersive Engineering: v0.11-62
Forge: 2345

https://i.gyazo.com/adf7d8f272d46eaf68d5564849fdbf6c.png

**Comment by kreezxil** [comment]
Same issue in my World of Dragons server pack. same versions as @Boomflex

**Comment by BluSunrize** [comment]
Gonna take a wild guess here: the world was created before IE was added?

**Comment by kreezxil** [comment]
No. The world is loaded with your ores in every chunk.

**Comment by Boomflex** [comment]
No, the world was created for the introduction of IE.

**Comment by kreezxil** [comment]
@BluSunrize I don't know why adding IE after the fact would matter. But yeah, I wiped my server world and behaved a little better. I still can't put glass bottles in the coke oven in smp, but I can at least use the bucket to get the creosote out.

**Comment by kreezxil** [comment]
I also stand by statement that my world had IE in it from the beginning. What did change is that you updated your mod once since the creation of the pack.

**Comment by BluSunrize** [comment]
Well there are no Creosote Bottles in IE. That's just a thing. The option of other mod's bottles working is up to them. I use Forge's fluid hooks, as intended.

The Creosote Oil "missing" is odd, and an issue that used to appear when the fluid had been initiated by another mod and then IE was added in later, resulting in a mismatch.

A binary search might honestly be the best approach, disabling half the mods and then working your way through either half till the reason is found...

**Comment by Boomflex** [comment]
>  and then IE was added in later

Does this still apply when in a brand new world it still happens?

**Comment by kreezxil** [comment]
@BluSunrize I copied my "corrupted" world and did as you suggested, and every instance, the darn creosote in a bucket worked as intended.

I rm -rf world, the unzip the world on each instance to make sure nothing vanished when removing mods.

Then made sure client and server had the same mods.

Inside your mod I can see all of the fluids as squares.

And outside I can see them in buckets under the master id of forge:

screenshot of that lastbit:

![2017-06-26_12 17 20](https://user-images.githubusercontent.com/3880072/27551938-0ab7993c-5a6b-11e7-86cc-29677e15ffaa.png)

**Comment by kreezxil** [comment]
maybe it was the uprading of my forge from 2315 to 2345 that caused it.

**Comment by Boomflex** [comment]
We did go from 2315 to 2345 too?

So maybe the latest Forge & IE aren't friends?

**Comment by tekkz** [comment]
IE was added to my server after the world was created. Nothing I can do about it I guess.  I made a villager trader with treated wood for people who needed it. Great mod though, thanks for all the hard work :)

**Comment by Protheus** [comment]
I have a similar problem with Creosote on 1.10.2 with forge 2297
I created a coke oven and added blocks of Coal in it. It creates the creosote oil but i'm unable to bucket it;

- from  the coke over
- Pipe it in a Drum (ExU2) and use a bucket, not working
- Use fluid transposer from Thermal Expansion, also not working
- Even used a fluid tank from EiO and when the fluid is in it it is pink and black texture and you can't put it in a bucket

The texture is all weird.
![2017-06-26_22 29 02](https://user-images.githubusercontent.com/1455178/27559064-7f496740-5abf-11e7-8174-bc4503fb7942.png)
![2017-06-26_22 33 18](https://user-images.githubusercontent.com/1455178/27559065-7f522240-5abf-11e7-86da-e0665a676c76.png)

**Comment by mindforger** [comment]
@BluSunrize you know i have no clue on how all that is actually working, but how high are chances, another mod tries to register the same fluid and exposing a block version to the world (as in placeable fluid) causing your fluid to break in texture because creosote has no actual block texture in IE? 
please don't bother do explain why i am at fault it was just a guess when i looked up the log message from the other issue i just linked

**Comment by Protheus** [comment]
I had Immersive Petroleum, removed that one and after game loads, the texture is the same and issues persist. 

In railcraft config, I disabled all creosote reference... issues persist

**Comment by Protheus** [comment]
#2238

Deadsix27 noted:
@mindforger I have a better workaround that I used in the past, I know that mods get priority by A-Z order, so obv a mod named A0.jar would be allowed to register something first.
Renaming ImmersiveEngineering-0.10-61.jar to A0-ImmersiveEngineering-0.10-61.jar, gave IE the rights to register it first.
Making the Oil work, on the other hand some other fluid probably stopped working now.. but idk.. its a work-around for now.

This fixed my issue !.. all is working perfectly now

**Comment by kreezxil** [comment]
Didn't know the method for mod precedence. Nice info to have.might be able
to narrow stuff down now.

**Comment by BaneOfSerenity** [comment]
I'm running MC 1.12.2 with IE 0.12-70 and I don't see any other mods with Creosote registered but i'm definitely seeing this issue on my server.

**Comment by BluSunrize** [comment]
@BaneOfSerenity the Thermal mods add it.
Also, you're like 4 IE versions behind.

**Comment by BaneOfSerenity** [comment]
You are correct, i just updated a bunch of mods, i thought IE was one of them. I'm updated now. I see that ThermalDynamics (or one of) adds the florb for creosote so i assume it has to make an entry for it. What i find is odd that if when mods are loaded they are loaded in order by name. IE should be loaded before the Thermal mods. When I pull up JEI there is only one of each fluid type item and they all say that Creosote is added by IE http://prntscr.com/h1xpzr

**Comment by BluSunrize** [comment]
Grab an NBT editor, go into the level.dat, find Forge's default fluid list, delete the creosote entry.
That should fix the issue.

I'll also close this now, since it's a rather old issue.
