### ISSUE TITLE
Refinery custom Minetweaker recipe not using both tanks appropriately 

### ISSUE THREAD

**Issue by TheQuantumGeneral** [BluSunrize/ImmersiveEngineering#222]
Made this quick script to make Buildcraft oil work in the Refinery

mods.immersiveengineering.Refinery.addRecipe(<liquid:fuel> * 16, <liquid:oil> * 8, <liquid:oil> * 8);

However it only wants to utilize one tank or the other, causing one tank to drain at double speed, making it harder to keep filled as its emptying twice as fast.

Also once the tank its chosen to use gets empty, it won't allow any more to be piped in, it needs some oil in it to accept more oil, so I have to seed it with a bucket or tin of oil.

![2015-07-15_02 39 59](https://cloud.githubusercontent.com/assets/7843312/8678929/e55af866-2a9a-11e5-9156-662985ed8e83.png)

**Comment by BluSunrize** [comment]
Thats not a bug. the refinery is not meant to work with two same fluids .-.

**Comment by Yulife** [comment]
Maybe make it throw an error then if it's two same liquids?  ;3

**Comment by TheQuantumGeneral** [comment]
An error would be less than useful, anyway I ended up making it oil and water, but the water never gets consumed. Under the logic that somehow its refining the crude oil into gas and condensing it into fuel using the water to cool it. 

mods.immersiveengineering.Refinery.addRecipe(<liquid:fuel> * 1, <liquid:water> * 0, <liquid:oil> * 1);

**Comment by XFactHD** [comment]
@TheQuantumGeneral the refinery can't consume the water if the recipe tells it to use liquid:water * 0.

**Comment by TheQuantumGeneral** [comment]
Yeah, I don't want it to consume it, no point really.
