### ISSUE TITLE
[Suggestion/Request] Assembler Custom Recipes with Crafttweaker

### ISSUE THREAD

**Issue by barrett1733** [BluSunrize/ImmersiveEngineering#2220]
I need to limit modpack progression and I thought of using the Assembler to do that. Is it possible to add a feature where you can add Crafttweaker recipes to the Assembler without it being available in all other crafting tables?

**Comment by bookerthegeek** [comment]
That would be pretty sweet actually.

**Comment by BluSunrize** [comment]
Nope. Assembler handles vanilla recipes. It has no custom recipe system.

**Comment by bookerthegeek** [comment]
Oh great and merciful Blu (see what I did there, I spelt your name correctly, mostly.) would you so kind as to add an ability to add crafting recipes that can only be completed in the assembler? I understand that this feature, if accepted, would be of low priority, but it might come in use to modpack authors. You would not need to add any recipes yourself, and as such would not impact players outside of packs using this feature in any way.

**Comment by KnightMiner** [comment]
Thing is, if he adds custom recipes in the assembler he needs a custom JEI handler to view those recipes that pack makers add, otherwise they appear uncraftable or part of normal crafting recipes. There are some other machines to hook o to anyways.

**Comment by bookerthegeek** [comment]
Forgot about that.

**Comment by AEnterprise** [comment]
it won't help for 1.11 but in 1.12 it would be possible to use the json recipes and parsing to allow for recipes to be defined only for the assembler, having them in a seperate folder, make a registry and parse them for use in the assembler only

**Comment by Bihlbo** [comment]
barrett1733, a workaround: The limiting custom recipes require a bucket of a fluid that cannot be placed in a bucket. Now the recipe is available to you at any time, but you cannot make it at all. Give out the bucket with the fluid already in it as a quest reward (or something) so the recipe can be added to the assembler. Now pipe in the fluid to the assembler and go to town. Next, think up a way to get the recipe back if a creeper destroys that one assembler.
