### ISSUE TITLE
[CRASH] 1112 JEI Crashes when viewing Fluid Recipes

### ISSUE THREAD

**Issue by ProxyPlayerHD** [BluSunrize/ImmersiveEngineering#2222]
tried to loop up ways to make Plant Oil, JEI was like "nope" and Crashed, it ONLY happens with IE FLuids.
I un-Installed Optifine to see if it casued the crashes, it didn't.

[REPORT](https://pastebin.com/w4yePGRP)

**Comment by ProxyPlayerHD** [comment]
Also, Pipes have a lot of Rendering Issues... they just derp around.
![2017-06-24_18 42 10](https://user-images.githubusercontent.com/13576843/27510243-f449e57e-590c-11e7-8281-9b2e5d860460.png)

**Comment by ProxyPlayerHD** [comment]
nvm, ALL FLuid Recipes crash JEI, but it happens at random.
I am confused.

**Comment by BluSunrize** [comment]
Could you please upload a full crashlog to pastebin or a similar site and link it here?

**Comment by malte0811** [comment]
There is one in the original post? Labeled REPORT.

**Comment by BluSunrize** [comment]
Hahaha, I'm blind. Sorry about that.

**Comment by BluSunrize** [comment]
Try removing Advanced Rocketry and see if that fixes the issue

**Comment by ProxyPlayerHD** [comment]
well crap. Guess i gotta inform the Dev of Acvanced Rocketry, his Mod makes the game Crash when trying to view ANY Fluid Transposer Recipe.
