### ISSUE TITLE
[CRASH] [1.11.2 - 0.11-62] Crash when moving Capacitor Backpack in inventory

### ISSUE THREAD

**Issue by microcontroling1** [BluSunrize/ImmersiveEngineering#2223]
[crash-2017-06-25_00.43.18-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1100024/crash-2017-06-25_00.43.18-client.txt)

As said in the title: game just crashes when you try to move Backpack in to another slot.

**Comment by malte0811** [comment]
Duplicate of #2184, fixed for the next release.
