### ISSUE TITLE
[CRASH] [11.2 0.11-62] Assembler crashes when crafting melon seeds

### ISSUE THREAD

**Issue by Ryusabre** [BluSunrize/ImmersiveEngineering#2224]
The assembler crashes every time I try to turn melons into seeds. I haven't tried other recipes yet, so I don't know if it's the assembler in general, just shapeless recipes, or just melon seeds.

Crash report: https://pastebin.com/ENANF5Fs

Mods: Just IE and JEI

**Comment by malte0811** [comment]
Duplicate of #2196. Fixed for the next release.
