### ISSUE TITLE
[1.11.2] Powered Lanterns not blocking passive spawns

### ISSUE THREAD

**Issue by Emberwalker** [BluSunrize/ImmersiveEngineering#2226]
An odd request, as per the chat in FC's IRC - it'd be ideal if Powered Lanterns also blocked passive spawns, useful for biomes like Jungle and Sacred Springs (BOP) which spawn some passive creatures to excess (kittens!). Poke me on IRC if you need testers - my islands have a cat infestation that makes a great test bed.

FC version at the time of writing: 1.11-59-104

**Comment by aelfwyne** [comment]
Rather not (personally).... passive spawns I don't mind, it's those creepers that show up in the dark that bug me.

**Comment by PrincessRTFM** [comment]
IIRC, passive mobs don't get blocked by light in vanilla, so why would a thing that just makes extra light block them? Maybe some new block could do it somehow, though I'm not sure if it would fit in IE. That sounds a little magic-y, and IE's all about tech.

**Comment by Emberwalker** [comment]
After some pondering, and chat in IRC, I came up with an alternative for passive spawns. It'd involve a new machine instead - like a Thumper Turret. Basically a device to pound the ground, with the excuse "the shockwaves drive away passive creatures" or some such. The design I thought might work is Light Eng on top of Piston on top of Steel Scaffold, perhaps? Thoughts?

**Comment by BluSunrize** [comment]
I do like the idea, if just for the Mass Effect references I can make with that.
Not having bats around is going to be wonderful.

**Comment by TehStoneMan** [comment]
The first thing that came to mind for me was the thumpers in Half-Life 2.

**Comment by Bihlbo** [comment]
Yeah, I like the idea of a whole separate item just for wildlife. Ultrasonic wild animal repellers do exist in real life, and would be a fitting concept to use for this application.
