### ISSUE TITLE
cant find lead ore anywhere

### ISSUE THREAD

**Issue by LocoMinerDad** [BluSunrize/ImmersiveEngineering#2228]

**Comment by malte0811** [comment]
What modpack are you using, what version of IE and what version of MC? How did you search? Did you use something like a quarry or MCEdit to check a whole chunk or did you just mine for some time?

**Comment by BluSunrize** [comment]
You know what? I'm just gonna close this, because the contribution guidelines were disregarded in their entirety. Can't be bothered to put up with people's incapability to read every single time.
