### ISSUE TITLE
Cant find lead ore

### ISSUE THREAD

**Issue by LocoMinerDad** [BluSunrize/ImmersiveEngineering#2229]
Your last comment makes you sound like a real jerk.
MC 7.10
forge .1614
IE .7.7

No I did not make a core sample, no I didn't make a excavator.
I mined at level 10 and 14 for about an hour and found nothing.
I cant power anything unless I go into creative to make the capacitors.

**Comment by theunkn0wn1** [comment]
Please see #2012 , perhaps this is The same issue?
Also please note your MC version has been unsupported for over a year now and Blu is very unlikely to offer support; consider updating to 1.10

**Comment by mindforger** [comment]
i am willing to help you ... despite **you** acting like a jerk now because you are one of literally hundreds that ignore the contibution guidelines and cough their frustration into the bugtracker without handing infromations to pin down the issue actually 

go ahead and install the NotEnoughResources Mod (aside the NotEnoughItems Mod if not already present) and go look up what distribution it tells you for the IE lead ore. This way we can make sure you do not have an config issue or some strange miscalculation issue.

If you are able to reproduce this with every new world you create, you can upload a copy of a freshly generated world somewhere for us, we can have a look at the world design.
Also please provide ALL mods to check for this issue or one can not launch your world! To provide a more detailed info on your setup, join the world, press and **hold** F3 + C to force a crash and post a crashlog via pastebin or seomthing but please do not port a wall of text :)

**Comment by BluSunrize** [comment]
Yeah, I can be a jerk. 
But if people keep ignoring the massive yellow bar that tells them to "read this before posting", then I feel my frustration to be reasonable. 
What mindforger said is what you should do, and to add to that, please provide your IE config file.

**Comment by LocoMinerDad** [comment]
I will do what you guys ask. I dont recall seeing a big yellow bar.

**Comment by BluSunrize** [comment]
![image](http://puu.sh/wuGBV/c753d05cfe.png)

There is one, I can tell you that much =P

**Comment by LocoMinerDad** [comment]
Ok Guys heres a update for you.

I tried a core sample and it says it can't find anything.  Which I think is odd because I have found copper etc.
I deleted the config file and that didn't seem to help.
I can't copy the config file here.
I made another world and used a core sample and it found magnetite vein.
I am not sure how to copy worlds.
I tried the make a crash report f3+C but it is not working but I have a crash report from 2 days ago.
[crash-2017-06-24_17.53.07-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1103226/crash-2017-06-24_17.53.07-client.txt)

I hope you can do something with this. I played this mod a year ago and didnt have issue and went back to 7.10 because I was tired of issues with .12. I wanted something stable

**Comment by BluSunrize** [comment]
Okay, you will need to clarify here.
You said you weren't finding lead ore, and that you mined at level 10 and 14. That implies you didn't find Lead generated in the world.
Now you are talking about Core Samples. Those are something entirely different.

What are you looking for, lead ore generated in the world or a lead vein for the excavator? They're not the same thing.

**Comment by LocoMinerDad** [comment]
Lead generated in the world. 
Before the other guy closed my first ticket he asked if I used a core sample or excavator to find it. I am just trying to cover all the stuff you guys asked.

**Comment by BluSunrize** [comment]
In that case, please do upload your config file to pastebin.com or gist.github.com and link it here, to confirm worldgen isn't disabled.

Also as mindforger, try adding NotEnoughResources and see if it lists lead in NEI.

**Comment by LocoMinerDad** [comment]
https://gist.github.com/LocoMinerDad/35fdf6445719129f27f303e3633a5b8b

**Comment by BluSunrize** [comment]
That looks alright. On to using NER then.

**Comment by LocoMinerDad** [comment]
installed the ner and its not showing, none of the ie is just vanilia

**Comment by mindforger** [comment]
i see Mantle beeing installed but no other Mods actually requiring it (at least those that i know) and as far as i can remember Mantle can take over ore generation completely when configured so to prevent multiple versions of copper spawns for example ... or do i mix up something in my remembrain there?

**Comment by KnightMiner** [comment]
Mantle does nothing of the sort. You might be thinking of CoFHCore which had oregen control, but I don't think it ever disabled ores itself.

**Comment by LocoMinerDad** [comment]
I think mantle is for tinkers construct. I have both tinker andvie ore.

**Comment by mindforger** [comment]
yeah i messed that one up with COFH :D 

can you go ahead an slowly remove a bunch of mods and create new worlds and lookup NER until LEAD shows up?
