### ISSUE TITLE
1.10.2 garden cloche power input oddities

### ISSUE THREAD

**Issue by braddr** [BluSunrize/ImmersiveEngineering#2230]
Testing with FTB Beyond 1.9.0 which contains immersive engineering 0.10-60.

EIO energy pipes will connect to both of the bottom power taps, but won't transfer power.  They will connect and transfer power to the top.  I confirmed that IE LV power works to all three points, so it's not a general problem but seems more mod or power conversion related.

**Comment by braddr** [comment]
TE's flux ducts also work just fine to the side power inputs.

**Comment by BluSunrize** [comment]
Fixed in future 1.12 builds
