### ISSUE TITLE
[Enhancement] New Breaker Switch Sound

### ISSUE THREAD

**Issue by dragonshardz** [BluSunrize/ImmersiveEngineering#2231]
N/T. Please replace the current sound of the breaker switch (somebody saying eee-oo) with this: https://freesound.org/people/Alvinwhatup2/sounds/131599/

**Comment by BluSunrize** [comment]
I'm afraid I can't do that, Dave.
The Direwolf meme must be kept alive.


Also, that's not the sound a knifeswitch makes either. =P

**Comment by Soaryn** [comment]
The current sound is incredible accurate to what an ACTUAL switch sounds like. 
Trust me, for I am an Engineer.

In all seriousness, the current sound must never change. 😄

**Comment by Ambaire** [comment]
The current breaker sound is completely intolerable to the point where I'm just using vanilla levers instead. Please give us a config option to mute the breaker sound...

**Comment by Simbrine** [comment]
I love the direwolf switches personally, but I think a config option to use the normal sound would be nice for some people :P

**Comment by Ambaire** [comment]
Who is direwolf? (Rhetorical question, but I've never watched a single one of his videos so I don't get this meme thing at all.)

**Comment by Simbrine** [comment]
He has this 1.11 modded multiplayer series called Forgecraft, which has Immersive Engineering on it. At some point the devs here decided to replace the breaker switch sound with Dire saying "meep moop"

**Comment by Ambaire** [comment]
Ah, I see. I agree with you.. an option to revert to the normal sound would be nice.

**Comment by BluSunrize** [comment]
The sound stems from his Invasion series.
He made the sound and then explained that the (till then) lack of sound on the switch was immersion breaking.
I joked around with him a bit explaining that finding a proper sound for a knifeswitch is tricky (which it is, trust me, I tried) and then the suggestion of using his audio came up.

The feature was discussed publicly on twitter and implemented quite a while ago, with people having ample opportunity to complain about it, which noone did.
Given that the broad majority was for it, or at least didn't seem to mind, I don't find this to be a thing to fix, really...

**Comment by TheWhiteWolves** [comment]
As the evil individual who [suggested it](https://twitter.com/WhiteWolvesWS/status/861568387218116608), I like the sound, though I may be biased on that :stuck_out_tongue_closed_eyes:

**Comment by Ambaire** [comment]
I haven't played any modded minecraft in months and I don't keep up with twitter much. It was a bit of a rude surprise when I heard that awful sound. :(

**Comment by KnightMiner** [comment]
@Ambaire: don't edit the jar, resource packs exist for this reason.

**Comment by Ambaire** [comment]
Oh. You can put custom sounds in resource packs? If you don't mind, how would I do that for a sound in IE? All the tutorials I can find are for vanilla minecraft, and I'm not sure what folder structure I'd use for a mod.

**Comment by KnightMiner** [comment]
[I wrote an Minecraft wiki article about it](https://minecraft.gamepedia.com/Resource_pack#Sounds), but basically just place a new .ogg sound at the same location as the resource is in IE (in this case it should be in [`assets/immersiveengineering/sounds/direSwitch.ogg`](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/resources/assets/immersiveengineering/sounds/direSwitch.ogg)).

**Comment by dragonshardz** [comment]
Having a path for adding the sound to the resource pack is fine too, I guess.

**Comment by draeath** [comment]
I think it's time for this joke to die.

Can we get a normal sound by default, now?

**Comment by BluSunrize** [comment]
Nope, absolutely not. I love the current one far too much =P

**Comment by DisKorrupt** [comment]
https://youtu.be/TjwFBwO-yiE?t=25
I'm actually particularly keen on something like this for the sound, I like the idea of the large industrial switches having that heavy sound to them as opposed to the Vanilla click of a lightswitch

**Comment by BluSunrize** [comment]
Where you not reading? I'm not changing the sound.
Direwolf stays in the game.

**Comment by Devalut** [comment]
Dev's put in effort to place eastereggs such as textures or sounds on events or holidays, IE dev just slaps it in and there as a festering pustule despite requests

**Comment by BluSunrize** [comment]
IE also features a *plethora* of other eastereggs and references, from the manual entries, over advancements to the crates which change texture in December.

I know for a fact that the person from who the sound originated (Dire) still approves of it's use and the humorous context, given that he only recently had a good chuckle at it during an episode.

@Devalut if you want to insult my work, feel free to do it to my face, on Discord, and not an an issue that was closed 15 months ago, you disrespectful hack.
