### ISSUE TITLE
1.11.2 Assembler Crash

### ISSUE THREAD

**Issue by Supergohst** [BluSunrize/ImmersiveEngineering#2236]
I'm currently using the Twitch Minecraft launcher with Forge 13.20.0.2345, playing IE solo with the help of JEI (1.11.2-4.5.0.289). I have an Assembler set up to change Dark Oak logs into planks and turn those into treated wood planks using a creosote pipe inserting the liquid. In 1.10 this worked fine but now everytime I insert dark oak in the Assembler my game crashes and I have to load up an old save. I don't know how to see crash logs on Twitch unfortunately but I hope this might help

**Comment by malte0811** [comment]
Known and fixed. This is at least the 4. report of this bug.
