### ISSUE TITLE
[1.10.2] Creosote oil issues

### ISSUE THREAD

**Issue by DeadSix27** [BluSunrize/ImmersiveEngineering#2238]
Versions used: ImmersiveEngineering-0.10-61.jar, forge-1.10.2-12.18.3.2297-universal.jar

On my client (and server) I have issues wit the Creosote oil, it appears to have no texture and can not be used in any way (e.g I cant place it on the floor, the buckets can't be filled with it or emptied)

I checked the logs for any issues but all I could find is this:
```
[11:33:35] [Client thread/INFO]: [CHAT] Given [Creosote Oil Bucket] * 1 to *
[11:33:41] [Client thread/WARN]: Unable to resolve texture due to upward reference: #all in minecraft:models/block/cube_all
```
![image](https://user-images.githubusercontent.com/1492505/27581201-529226ec-5b2d-11e7-9dd2-a8861218c1bc.png)

Any clue what could cause this? A comparability issue? What's the easiest way to figure out if another mod causes this? I have like 300...too much to individually remove.. 
Could I add a debug line somewhere or something?

**Comment by mindforger** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/2219

**Comment by DeadSix27** [comment]
@mindforger thanks for pointing me there, figured it does actually exist on the server.. but I guess that's how it looks if it does not.
However that issue report seems to have no answer, as in how to fix it?

is that a known issue and something that's going to be fixed?

**Comment by mindforger** [comment]
well the other issue is worked on and the fact i linked to it could help probably and i have at least a slight guess

**Comment by DeadSix27** [comment]
@mindforger Well at long it gets attention I'm happy :P trying to track down what causes it too.. But I'm not a MC-coder, so all I can do is find out if another mod causes the issue.. slowly..

**Comment by mindforger** [comment]
workaround is using an NT editor and remove the oil registry entry ... but make sure to make a copy of the world first

**Comment by DeadSix27** [comment]
@mindforger I have a better workaround that I used in the past, I know that mods get priority by A-Z order, so obv a mod named A0.jar would be allowed to register something first.
Renaming ImmersiveEngineering-0.10-61.jar to A0-ImmersiveEngineering-0.10-61.jar, gave IE the rights to register it first.
Making the Oil work, on the other hand some other fluid probably stopped working now.. but idk.. its a work-around for now.
