### ISSUE TITLE
[1.11.2 - v0.11-62] Fluid Outlet still using closed sides.

### ISSUE THREAD

**Issue by VallenFrostweaver** [BluSunrize/ImmersiveEngineering#2240]
To reproduce:
1. Placed a pipe going from barrel to an input on a fluid outlet (in image I disconnected the pipe for a moment to illustrate the input of the outlet and reconnected the pipe after the image was taken).
![ie 1](https://user-images.githubusercontent.com/13642054/27600231-31d22570-5b63-11e7-802e-68d3706c0805.png)

2. Closed all sides of Fluid Outlet but for input on top (image only shows 3 of the 5 sides but all are closed).
![ie 2](https://user-images.githubusercontent.com/13642054/27600244-3ca8a000-5b63-11e7-82ce-ed19243d1186.png)

3. Poured 1 bucket of water into barrel. It went into the outlet as seen here.
![ie 3](https://user-images.githubusercontent.com/13642054/27600247-403d8dde-5b63-11e7-83d7-0c1bb9ad5279.png)

4. Clicked with hammer to open one side of the outlet and waited for water to appear.
![ie 4](https://user-images.githubusercontent.com/13642054/27600249-4307efe6-5b63-11e7-8bad-5df26fce047f.png)

5. Placed block to remove water source block. Closed outlet side (see image from 2) so all sides are closed again. Added another bucket of water to the barrel. Water block appears 1 space below previous water block location and all sides are closed but for input on outlet.
![ie 5](https://user-images.githubusercontent.com/13642054/27600253-468b3650-5b63-11e7-80a2-cbe2ed658516.png)

**Comment by BluSunrize** [comment]
I think this is actually caused by the fact that the outputs are established before you closed the sides.
I'll look into adding a reset of the outputmap to the side-toggling
