### ISSUE TITLE
[1.11.2 - v0.11-62] Assembler server crash

### ISSUE THREAD

**Issue by proudft** [BluSunrize/ImmersiveEngineering#2241]
I loaded up a 1.10.2 world in 1.11.2 and it basically immediately crashed, so I looked around in the crash log, disabled all other mods, and did some poking around.  The messages made it sound like it was an Assembler, so I broke all existing assemblers, hoping that re-multiblocking them would fix it, but no luck.

I load up the 1.10.2 world with un-multiblocked Assemblers, world loads fine.  
I re-click w/a wrench on an assembler to make it a multiblock, no crash. 
I break and reattach the power connection, no crash.  
I set a recipe (4 solid stone to make a stone brick), no crash.
I put 4 solid stone in the assembler's inventory, blammo.  Dedicated server crashes, client gets disconnected.  Can restart the server, but it immediately crashes whenever an player is close enough to the assembler for it to do stuff.

Crash log from server:
[crash-2017-06-27_09.59.21-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1106185/crash-2017-06-27_09.59.21-server.txt)

**Comment by malte0811** [comment]
Known and fixed. I think this is the fifth report of this bug, as searching for "assembler" would have shown.
