### ISSUE TITLE
[1.11.2][62] Assembler crashes when attempting to craft

### ISSUE THREAD

**Issue by Rosethorns** [BluSunrize/ImmersiveEngineering#2243]
My  player doesn't remember what they were trying to craft but apparently the Assembler is having none of it.

https://pastebin.com/BuzRC21E

This occurs when ever the chunks containing the assembler are reloaded.

**Comment by malte0811** [comment]
I think we are up to 6 reports of this issue now? Known and fixed for the next release, don't ask me when that will be.

**Comment by Rosethorns** [comment]
searching for assembler is open issues caused none of these 6 reports to show. And due to the update being an unknown time from being ready is it better to not have at least /one/ of them still open to indicate this?

**Comment by mindforger** [comment]
you should search closed ones too always, they refer to the first report almost always

**Comment by malte0811** [comment]
Quote from the contributing guidelines:
 > Please always search for both open and closed issues as issues are closed when the fix has been written, not when a release containing a fix is published.

This just makes it easier to see which issues still need to be worked on.
