### ISSUE TITLE
[1.11.2] Fluid Pipes render error

### ISSUE THREAD

**Issue by Eufranio** [BluSunrize/ImmersiveEngineering#2246]
They don't appear to connect correctly sometimes. Screenshots:

![img](https://image.prntscr.com/image/MWedSIo_T8_8F-T9OQT2ww.png)
![img](https://image.prntscr.com/image/GONTWp9nSjWoUxKpzrwsMw.png)
![img](https://image.prntscr.com/image/e5NUKbZcTKqo3m6J3ye0yg.png)

IE version: 0.11-62
Modpack: [MTN - Concept](https://www.technicpack.net/modpack/magibeta-111.1024667)
Mod list: [MTN - Concept (Mods)](https://www.technicpack.net/modpack/magibeta-111.1024667/mods)

**Comment by malte0811** [comment]
Did you look at some multiblock containing pipes in the manual before this happened? If that is the case: I fixed that bug yesterday.

**Comment by Eufranio** [comment]
"Before" in the game instance or in the world? The 3rd screenshot was taken on a singleplayer world, and I didn't open the manual there. The two other screenshots I took on a multiplayer world, and I opened the manual there.

**Comment by malte0811** [comment]
Game instance, unless you ran /cie resetrender in that instance in which case since the last run of that command.

**Comment by Eufranio** [comment]
They were taken in the same instance, so it might be fixed in latest builds. Do you have an ETA on when a new 1.11 build will be available on Curse/Curseforge?
