### ISSUE TITLE
Assembler Issues

### ISSUE THREAD

**Issue by Cazgem** [BluSunrize/ImmersiveEngineering#2248]
Using the Assembler multiblock, I attempted to automate treated wood planks. I hooked it up to creosote from a coke oven using IE fluid pumps and pipes, got it hooked up to power, set up the recipe just fine.
 As soon as I added the oak wood planks it started crashing in an infinite loop.

[crash-2017-06-29_09.47.06-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1112466/crash-2017-06-29_09.47.06-server.txt)
[crash-2017-06-29_09.50.50-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1112467/crash-2017-06-29_09.50.50-server.txt)
[crash-2017-06-29_09.58.34-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1112468/crash-2017-06-29_09.58.34-server.txt)

EDIT:

Have duplicated the problem twice now, on different world saves.

**Comment by BluSunrize** [comment]
Use the searchfunction please, this is a multiple times reported duplicate issue.
