### ISSUE TITLE
[1.11.2] Crash on hooking up iron pipes to Animania troughs

### ISSUE THREAD

**Issue by gchpaco** [BluSunrize/ImmersiveEngineering#2249]
Tried to attach an iron pipe to the bottom of an Animania trough, and boom.  Crashes with the same error every time I restart.

This is probably something Animania is doing wrong, but the NPE is in IE's block, and I can't fix it with removeErroringTileEntities.

[crash-2017-06-29_13.06.00-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1113113/crash-2017-06-29_13.06.00-client.txt)

**Comment by BluSunrize** [comment]
Animania is closed source. Fracking wonderful.
I'll try to look into it, but I can't guarantee anything.

**Comment by gchpaco** [comment]
Yeah, it's a headache.  At this point I would settle for "doesn't crash but doesn't work"; apparently they are advertising having the fluid handler capability in that direction, but when the object is requested they give `null` instead, which is pretty dumb.  That affects `getAvailableConnectionByte` and `getConnectionByte` both.

**Comment by BluSunrize** [comment]
Yup, totally on their side.
It's convention for the object of the capability to be returned to not be null if hasCapability returned true.

https://github.com/capnkirok/animania/issues/249

Moved to their tracker, not an IE issue.
