### ISSUE TITLE
[Suggestion] Automatically rotating conveyor belts

### ISSUE THREAD

**Issue by Eufranio** [BluSunrize/ImmersiveEngineering#2250]
I suggest you adding a new conveyor belt: the Rotating Conveyor Belt. You can right click it to define which site it should rotate to (or even define it with the hammer), and when receiving a redstone signal, different from other conveyors (that stops when powered), this one will rotate to the defined side.

**Comment by BluSunrize** [comment]
Look at the turntable ^^
