### ISSUE TITLE
[Request]

### ISSUE THREAD

**Issue by TristenCocking** [BluSunrize/ImmersiveEngineering#2251]
Since the idea of covered conveyors is that the player cannot pick-up the items on it is it possible to make the items on the conveyor be in an internal inventory and only render on the conveyor. Like what magneticraft did in their 1.7.10 release? The reason for this is it might reduce framerate issues. Having a lot of item entities causes framerate issues. Although having a lot of ticking tile entities does too. I’m not sure which one would be better. It’s just an idea.

**Comment by BluSunrize** [comment]
Nope, not doing that.
The inherent design concept behind conveyors was the fact that they simply move entities, nothing else.
The only "special" stuff they do for items is insert on collision and spawn in the world when piped into.
I'm not changing them to be internal transport+render.
