### ISSUE TITLE
Stack amount behind image

### ISSUE THREAD

**Issue by NicosaurusRex99** [BluSunrize/ImmersiveEngineering#2252]
Look at the hotbar and you will notice the 3 is behind the HV wires

http://imgur.com/a/0tvBV

**Comment by BluSunrize** [comment]
I doubt this is an IE issue. Look at the contribution guidelines again. Version number, mod list, all that jazz.

**Comment by NicosaurusRex99** [comment]
@BluSunrize sorry i wasnt aware of guidelines, version: 0.11-63
Modlist: https://minecraft.curseforge.com/projects/green-hectares/relations/dependencies

**Comment by BluSunrize** [comment]
Well I'd recommend doing binary search. Remove half of the mods, see if the issue persists. If it does, it's in the remaining, else in the other half. Split that one again, and so on and so forth until you find the mod whos removal causes this.

**Comment by NicosaurusRex99** [comment]
Gosh thats gonna take long, there is heaps of mods. #MustBeDoneAMIRITE

**Comment by BluSunrize** [comment]
Well, that's why I suggested binary search. Removing each mod seperately takes n tries, where n is the number of mods.
For binary search it's Log2(n) ^^
