### ISSUE TITLE
[Suggestion] Invert Dropping Conveyor Belts

### ISSUE THREAD

**Issue by Eufranio** [BluSunrize/ImmersiveEngineering#2254]
I wanted a way to invert the Dropping Conveyor Belts: actually, they try to drop and if the inventory is full (or there is no inventory) below it, they insert in the adjacent inventory. I wanted a way to invert this, so they would first try to insert in the adjacent inventory, and then try to insert below.

**Comment by Bihlbo** [comment]
That's pretty easily created by yourself, by simply engineering the conveyors differently. If you wanted the conveyor to insert into A before B, then A goes under the dropping conveyor, and B at the end of the conveyor's line. That's how I easily prevent items from building up on the conveyor when their intended destination is full.

**Comment by ldog** [comment]
It would be useful for machines that have only side inputs though - assembler, fermenter & squeezer for instance.
