### ISSUE TITLE
[1.11.2] Can't place water or lava with bucket

### ISSUE THREAD

**Issue by TheGeekPlays** [BluSunrize/ImmersiveEngineering#2256]
I can't place down water with a bucket! When I try, my game freezes and then crashes. I'm not sure if it's a conflict with my other mods, or just my computer, but it is really annoying. Here's a list of my mods:
Mr. Crayfish's Furniture Mod
CompatLayer
Just Enough Items
Custom NPCs
Decocraft 2
Bibliocraft
Vic's Modern Warfare Mod
Literal Ascention
Malis's Blocks
Malis's Doors
Malis's Core
McJty Lib
More Player Models
Optifine HD U C2
Toro Health
Wearable Backpacks
Worldedit Forge 1.11.2
Zombie Steaks
 And all Required Library and Core Mods

This was the message that popped up:
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Unexpected error

**Comment by ArukaAlter** [comment]
If it crashes, provide a proper crash log.

**Comment by TheGeekPlays** [comment]
Sorry, here it is:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  llibrary (llibrary-1.7.4-1.11.2.jar)
  GenderLoadingPlugin ([1.11.2]Gender-1.2.8.jar)
  ForgelinPlugin (Forgelin-1.3.1.jar)
  literalascension (literalascension-1.11.2-1.0.2.2.jar)
  CTMCorePlugin (CTM-MC1.11.2-0.1.1.6.jar)
  MalisisCorePlugin (malisiscore-1.11.2-5.1.1.jar)
Contact their authors BEFORE contacting forge

// Who set us up the TNT?

Time: 7/1/17 12:21 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.geforcemods.securitycraft.handlers.ForgeEventHandler.onBucketUsed(ForgeEventHandler.java:107)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_20_ForgeEventHandler_onBucketUsed_FillBucketEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.event.ForgeEventFactory.onBucketUse(ForgeEventFactory.java:392)
	at net.minecraft.item.ItemBucket.func_77659_a(ItemBucket.java:41)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:196)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:496)
	at PlayerControllerOF.func_187101_a(PlayerControllerOF.java:72)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1539)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2179)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1956)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1744)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.geforcemods.securitycraft.handlers.ForgeEventHandler.onBucketUsed(ForgeEventHandler.java:107)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_20_ForgeEventHandler_onBucketUsed_FillBucketEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.event.ForgeEventFactory.onBucketUse(ForgeEventFactory.java:392)
	at net.minecraft.item.ItemBucket.func_77659_a(ItemBucket.java:41)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:196)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:496)
	at PlayerControllerOF.func_187101_a(PlayerControllerOF.java:72)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1539)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2179)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1956)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['RMS1230MB'/5949, l='MpServer', x=-527.61, y=4.00, z=-217.04]]
	Chunk stats: MultiplayerChunkCache: 338, 338
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-540,4,-168), Chunk: (at 4,0,8 in -34,-11; contains blocks -544,0,-176 to -529,255,-161), Region: (-2,-1; contains chunks -64,-32 to -33,-1, blocks -1024,0,-512 to -513,255,-1)
	Level time: 46218 game time, 46218 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 45 total; [EntityPlayerSP['RMS1230MB'/5949, l='MpServer', x=-527.61, y=4.00, z=-217.04], EntitySpider['Spider'/6957807, l='MpServer', x=-456.50, y=4.00, z=-252.50], EntitySlime['Slime'/5985232, l='MpServer', x=-534.88, y=4.00, z=-230.10], EntityHorse['Horse'/84495, l='MpServer', x=-599.94, y=4.00, z=-234.14], EntityHorse['Horse'/84497, l='MpServer', x=-594.35, y=4.00, z=-238.47], EntityHorse['Horse'/84496, l='MpServer', x=-596.24, y=4.00, z=-233.70], EntityChicken['Chicken'/84499, l='MpServer', x=-599.50, y=4.00, z=-235.50], EntityHorse['Horse'/84498, l='MpServer', x=-594.62, y=4.00, z=-234.61], EntitySpider['Spider'/6870140, l='MpServer', x=-591.50, y=4.00, z=-221.50], EntityZombie['Zombie'/6957809, l='MpServer', x=-452.50, y=4.00, z=-259.50], EntityCow['Cow'/84509, l='MpServer', x=-525.45, y=4.00, z=-254.73], EntityCow['Cow'/84511, l='MpServer', x=-520.77, y=4.00, z=-260.69], EntityCow['Cow'/84510, l='MpServer', x=-521.99, y=4.00, z=-261.75], EntityCow['Cow'/84512, l='MpServer', x=-517.98, y=4.00, z=-260.30], EntityItemFrame['entity.ItemFrame.name'/2133255, l='MpServer', x=-451.97, y=7.50, z=-340.50], EntitySkeleton['Skeleton'/6870095, l='MpServer', x=-494.69, y=4.00, z=-197.62], EntitySheep['Sheep'/84523, l='MpServer', x=-479.47, y=4.00, z=-210.93], EntitySheep['Sheep'/84522, l='MpServer', x=-478.97, y=4.00, z=-209.51], EntityZombie['Zombie'/6957761, l='MpServer', x=-484.50, y=4.00, z=-164.50], EntityCow['Cow'/84525, l='MpServer', x=-475.86, y=4.00, z=-207.23], EntityCow['Cow'/84524, l='MpServer', x=-478.53, y=4.00, z=-210.82], EntitySkeleton['Skeleton'/6870109, l='MpServer', x=-477.50, y=4.00, z=-230.50], EntityZombie['Zombie'/6957779, l='MpServer', x=-488.24, y=4.00, z=-137.44], EntityWitch['Witch'/6774949, l='MpServer', x=-537.32, y=4.00, z=-198.21], EntityCreeper['Creeper'/6774956, l='MpServer', x=-505.15, y=4.00, z=-209.26], EntitySlime['Slime'/5816205, l='MpServer', x=-561.70, y=5.18, z=-207.38], EntitySkeleton['Skeleton'/6870079, l='MpServer', x=-451.50, y=4.00, z=-178.50], EntityHorse['Horse'/84441, l='MpServer', x=-445.50, y=4.00, z=-180.50], EntitySheep['Sheep'/84443, l='MpServer', x=-445.50, y=4.00, z=-176.50], EntityHorse['Horse'/84449, l='MpServer', x=-591.56, y=4.00, z=-271.81], EntityHorse['Horse'/84451, l='MpServer', x=-599.01, y=4.00, z=-276.04], EntityHorse['Horse'/84450, l='MpServer', x=-601.28, y=4.00, z=-284.99], EntityHorse['Horse'/84453, l='MpServer', x=-599.72, y=4.00, z=-285.58], EntityHorse['Horse'/84452, l='MpServer', x=-603.22, y=4.00, z=-280.80], EntityChicken['Chicken'/84455, l='MpServer', x=-473.51, y=4.00, z=-238.76], EntityHorse['Horse'/84454, l='MpServer', x=-602.23, y=4.00, z=-282.84], EntityChicken['Chicken'/84457, l='MpServer', x=-474.13, y=4.00, z=-242.03], EntityChicken['Chicken'/84456, l='MpServer', x=-473.24, y=4.00, z=-243.34], EntityCreeper['Creeper'/6774926, l='MpServer', x=-563.72, y=4.00, z=-151.14], EntitySheep['Sheep'/84458, l='MpServer', x=-475.21, y=4.00, z=-238.21], EntitySlime['Slime'/5033151, l='MpServer', x=-501.56, y=4.00, z=-209.30], EntityHorse['Horse'/84476, l='MpServer', x=-573.54, y=4.00, z=-136.45], EntitySlime['Slime'/4890807, l='MpServer', x=-508.92, y=4.75, z=-215.64], EntitySpider['Spider'/6957847, l='MpServer', x=-461.50, y=4.00, z=-235.50], EntityCreeper['Creeper'/6870167, l='MpServer', x=-468.50, y=4.00, z=-158.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:524)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:401)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1160836472 bytes (1107 MB) / 3411578880 bytes (3253 MB) up to 34346369024 bytes (32755 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx32G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.38 Powered by Forge 13.20.0.2285 Optifine OptiFine_1.11.2_HD_U_C2 30 mods loaded, 30 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAAAAAAA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJAAAAAAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAAAAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2285.jar) 
	UCHIJAAAAAAAAA	forge{13.20.0.2285} [Minecraft Forge] (forge-1.11.2-13.20.0.2285.jar) 
	UCHIJAAAAAAAAA	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.11.2.jar) 
	UCHIJAAAAAAAAA	securitycraft{v1.8.2.2-beta3} [SecurityCraft] ([1.11.2] SecurityCraft v1.8.2.2-beta3.jar) 
	UCHIJAAAAAAAAA	gender{1.2.8} [Gender] ([1.11.2]Gender-1.2.8.jar) 
	UCHIJAAAAAAAAA	bibliocraft{2.3.2} [BiblioCraft] (BiblioCraft[v2.3.2][MC1.11.2].jar) 
	UCHIJAAAAAAAAA	cdm{0.0.2} [MrCrayfish's Device Mod] (cdm-0.0.2-alpha-mc1.11 (1).jar) 
	UCHIJAAAAAAAAA	cfm{4.1.2} [MrCrayfish's Furniture Mod] (cfm-4.1.2-mc1.11.2 (1).jar) 
	UCHIJAAAAAAAAA	chisel{MC1.11.2-0.0.11.18} [Chisel] (Chisel-MC1.11.2-0.0.11.18.jar) 
	UCHIJAAAAAAAAA	ctm{MC1.11.2-0.1.1.6} [CTM] (CTM-MC1.11.2-0.1.1.6.jar) 
	UCHIJAAAAAAAAA	customnpcs{1.11.2} [CustomNPCs] (CustomNPCs_1.11.2_beta(17mar17).jar) 
	UCHIJAAAAAAAAA	cvmm{1.0} [MrCrayfish's Vending Machine Mod] (cvmm-1.0-mc1.11.2.jar) 
	UCHIJAAAAAAAAA	props{2.4.1} [Decocraft] (Decocraft-2.4.1_1.11.2.jar) 
	UCHIJAAAAAAAAA	forgelin{1.3.0} [Forgelin] (Forgelin-1.3.1.jar) 
	UCHIJAAAAAAAAA	jei{4.3.3.266} [Just Enough Items] (jei_1.11.2-4.3.3.266.jar) 
	UCHIJAAAAAAAAA	immersiveengineering{0.11-63} [Immersive Engineering] (ImmersiveEngineering-0.11-63.jar) 
	UCHIJAAAAAAAAA	llibrary{1.7.4} [LLibrary] (llibrary-1.7.4-1.11.2.jar) 
	UCHIJAAAAAAAAA	literalascension{1.11.2-1.0.2.2} [Literal Ascension] (literalascension-1.11.2-1.0.2.2.jar) 
	UCHIJAAAAAAAAA	malisiscore{1.11.2-5.1.1} [MalisisCore] (malisiscore-1.11.2-5.1.1.jar) 
	UCHIJAAAAAAAAA	malisisblocks{1.11.2-5.1.0} [Malisis Blocks] (malisisblocks-1.11.2-5.1.0.jar) 
	UCHIJAAAAAAAAA	malisisdoors{1.11.2-6.1.0} [MalisisDoors] (malisisdoors-1.11.2-6.1.0.jar) 
	UCHIJAAAAAAAAA	moreplayermodels{1.11.0} [MorePlayerModels] (MorePlayerModels_1.11.2(26jan17).jar) 
	UCHIJAAAAAAAAA	mw{1.10.3} [Modern Warfare] (mw-1.10.3_mc1.11.2.jar) 
	UCHIJAAAAAAAAA	rftools{6.10} [RFTools] (rftools-1.1x-6.10.jar) 
	UCHIJAAAAAAAAA	torohealthmod{1.11.2-11} [ToroHealth Damage Indicators] (torohealth-1.11.2-11.jar) 
	UCHIJAAAAAAAAA	wearablebackpacks{2.5.0} [Wearable Backpacks] (WearableBackpacks-1.11.2-2.5.0.jar) 
	UCHIJAAAAAAAAA	worldedit{6.1.6} [WorldEdit] (worldedit-forge-mc1.11-6.1.6-dist.jar) 
	UCHIJAAAAAAAAA	zombie_steak{1.11-1.1.3} [Zombie Steak] (zombie_steak-1.11-1.1.3.jar) 
	Loaded coremods (and transformers): 
llibrary (llibrary-1.7.4-1.11.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
GenderLoadingPlugin ([1.11.2]Gender-1.2.8.jar)
  com.github.ipixeli.gender.coremod.GenderClassTransformer
ForgelinPlugin (Forgelin-1.3.1.jar)
  
literalascension (literalascension-1.11.2-1.0.2.2.jar)
  com.jamieswhiteshirt.literalascension.core.patcher.LiteralAscensionRuntimePatcher
CTMCorePlugin (CTM-MC1.11.2-0.1.1.6.jar)
  team.chisel.ctm.client.asm.CTMTransformer
MalisisCorePlugin (malisiscore-1.11.2-5.1.1.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 376.53' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	Launched Version: 1.11.2-forge1.11.2-13.20.0.2285
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.5.0 NVIDIA 376.53, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD FX(tm)-8320 Eight-Core Processor 
	OptiFine Version: OptiFine_1.11.2_HD_U_C2
	Render Distance Chunks: 9
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.5.0 NVIDIA 376.53
	OpenGlRenderer: GeForce GTX 970/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by ArukaAlter** [comment]
It only points towards SecurityCraft, not IE.

**Comment by malte0811** [comment]
Also try removing Optifine, we don't support it unless we have far too much time which currently isn't the case for @BluSunrize (I believe) or me (I know).

**Comment by TheGeekPlays** [comment]
Cool, thanks guys!
