### ISSUE TITLE
1.7.10 "Potion" Crash

### ISSUE THREAD

**Issue by TheSpareAce** [BluSunrize/ImmersiveEngineering#2257]
https://pastebin.com/Ltw7aCg2

This crash report started coming up on startup, when I installed this mod. Why am I getting this?

**Comment by malte0811** [comment]
Without looking at the crash: Delete the "potions" section from your config file. If it isn't the crash I think it is: 1.7.10 isn't supported any more, even 1.10 isn't really supported any more.
