### ISSUE TITLE
Exposing diesel handler in MineTweaker

### ISSUE THREAD

**Issue by marcin212** [BluSunrize/ImmersiveEngineering#226]

**Comment by BluSunrize** [comment]
Seeing as there isn't even a description for this I'll have to guess what exactly you are requesting:
Adjusting the burn values of fluids. Not planned.

**Comment by Kubuxu** [comment]
No, we wanted to add different fluids to diesel and also as we have reduced burn output we wanted to increase burn time to reduce disparities of total energy per bucket on our pack.

Energy balance is siginificantly different in case of our modpack than elsewhere 4098RF/t was to much for us.
