### ISSUE TITLE
[1.11.2] Assembler will not create water bucket based recipes

### ISSUE THREAD

**Issue by ldog** [BluSunrize/ImmersiveEngineering#2260]
Assembler has power, water, materials.
Attempted TE clay recipe and AA slimeball (water and rice dough) neither work.
HC fresh water is created. Also pumping in creosote to make treated wood works as expected.

Also have a request, lava/water-obsidian.

**Comment by BluSunrize** [comment]
You need to specify a version and provide a crash log. Please read the contribution guidelines. Am 04.07.2017 02:45 schrieb ldog <notifications@github.com>:Assembler has power, water, materials.
Attempted TE clay recipe and AA slimeball (water and rice dough) neither work.
HC fresh water is created. Also pumping in creosote to make treated wood works as expected.
Also have a request, lava/water-obsidian.

**Comment by ldog** [comment]
IE version 0.11-63
What crash log? There's no crash. Please read the issue :P

**Comment by mindforger** [comment]
In the guidelines is deacribed how to force a crashlog, press and hold f3 + c while ingame until it crashes. It contains important infos

**Comment by ldog** [comment]
Here:
[crash-2017-07-05_17.43.59-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1126115/crash-2017-07-05_17.43.59-client.txt)
Clean new pack, left AA out, but the TE recipe still persists (it'd be a nice thing for you to add to IE anyway..clay is a pain when you need it in bulk) If you put an actual bucket of water in it will craft, but still never use the internal tank for it.

**Comment by mindforger** [comment]
Well you could add it yourself using crafttweaker. If AA uses non default buckets in their recipes they either do it on purpose or from ignorance, the assembler can only parse standard crafting recipes.

**Comment by ldog** [comment]
My last update were all Thermal Expansion recipes. So it's something wrong with the recipes themselves?

**Comment by mindforger** [comment]
it is well possible that they replace standard buckets and do not present them as fluid container (from my point of knowledge what i would have to guess) like i said either on purpose, ignorance or possibly a bug on their side, but i would let Blu give an way more educated guess on this :D

**Comment by ldog** [comment]
I'm pretty sure they are all standard forge, they're found under the bucket tab in creative, not even their own mod (I'll have to dblcheck the creosote bucket, but I'm at work atm). Fluidbased crafting has a lot of wierdness these days in general it seems, I guess that's why TE hasn't reimplemented the cyclic assembler either (you have to use the fluid transposer & buckets). Refined Storage it also seems hit or miss. I'm trying to do more in IE lately though, and bucket based crafting being the most tedious, are prime candidate for assembler so it would be nice to work the kinds out, be that by config/crafttweaker or actual fixes. I just don't know what I should expect it to be capable of or not.

**Comment by ldog** [comment]
Got around to assembler in 1.12, now it's doing the same thing for treated wood; works with a bucket of creosote inserted, will not use creosote from internal tank.

**Comment by Terpo** [comment]
Just tested on the newest versions for 1.11.2 with Destabilized Redstone from Thermal Foundation.
If a bucket is available the recipe works. The internal tank is not touched.

Forge 2386
CodeChickenLib-1.11.2-3.0.0.284-universal.jar
ThermalDynamics-1.11.2-2.2.6.13-universal.jar
ThermalExpansion-1.11.2-5.2.6.22-universal.jar
CoFHCore-1.11.2-4.2.7.15-universal.jar
ThermalFoundation-1.11.2-2.2.5.16-universal.jar
ImmersiveEngineering-0.11-63.jar
forestry_1.11.2-5.3.4.135.jar
jei_1.11.2-4.5.0.294.jar
