### ISSUE TITLE
[Suggestion] Mining Drill Animations?

### ISSUE THREAD

**Issue by Filvandrel** [BluSunrize/ImmersiveEngineering#2265]
Hi!

I remember that mining drill had animations on the 1.7.10 version of IE. And now while playing 1.11.2 I miss it very much. I've seen that you are working on revolver animations now, hence I wish to ask: are you planning to implement mining drill animations back one day in the future? Or it will most likely stay as is? It would be a really cool feature, especially with some sort of sound effect too.

Great mod anyway, always on my must have mod list. :) Minecraft would not be the same without it. Keep up the good work! :D

P.S.
Sorry if using issue tracker for suggestions isn't a good thing, I don't have any other mean of contacting you atm. And sorry for my chaotic english either. :d

**Comment by BluSunrize** [comment]
Nothing I can do about it.
New model system doesn't easily allow me to do animations for only parts of the model. Sorry.
