### ISSUE TITLE
[Suggestion] More mod compatibility with Garden Cloche

### ISSUE THREAD

**Issue by Vahtera** [BluSunrize/ImmersiveEngineering#2266]
I love this thing. Even if it didn't speed up crops without fertilizer, I'd still use it because it makes farming so compact and neat. That said, I'd LOVE to see the Garden Cloche work with more things, specifically Pam's Harvestcraft Trees don't work (the crops themselves do, but the trees that require special saplings and grow things on the underside of the leaves), and neither does vanilla cocoa beans.

**Comment by lstanden** [comment]
Well, vanilla trees don't work in the cloche either, last I checked.  I believe the idea was specifically to be for crops.

**Comment by Vahtera** [comment]
Vanilla trees don't produce "crops" though. I don't want/need the Cloche to cut down the trees, but specifically to harvest the produce FROM the tree (not the tree itself). I understand perfectly why it doesn't support tree farming, there's a zillion other things for that. 

That said, I understand if Cloches will not support trees (from a logical standpoint, the volume is too small for a tree to grow in there, although so it is for melons and pumpkins also..), but as said, it's just a suggestion :)

There's ways to automate vanilla cocoa, but there are little to no possibilities for automating Pam's trees, sadly. Cloche would've been my choice (as Immersive Engineering is one of my fav mods anyways).

**Comment by BluSunrize** [comment]
Yeah but rendering tiny trees in there would look terrible. >_>

I looked into cocoa beans originally, but they are also hard to render because they are supposed to attach to a log. There is no way to have them "stand up" properly.

**Comment by mindforger** [comment]
>Yeah but rendering tiny trees in there would look terrible. >_>

Bonzai !? :D 

well you could render a branch where the fruit is hanging down from ... maybe add an 1% chance of consuming the branch/sapling in the process reuqiring to craft new ones ... instead of getting more seeds/saplings you have to to a bit of extra work for those types of fruits ... and you could probably add a very slow gardencloche function that allows to plant regular saplings and not getting out wood or something but more saplings!

**Comment by BluSunrize** [comment]
Yeah and then I'd need to render a branch. Bear in mind that this stuff is supposed to work with normal crops, which are a simple block to render.
The Melon/Pumpkin render is already stretching it in complexity.

**Comment by Vahtera** [comment]
I don't want to complicate things more, since porting this thing forward with every point version of MC is work enough, I'd guess :) (On that note, I do appreciate you doing this in the first place.)

How about a completely different product then? A platform of some sorts (1 block or 3x3 multiblock? You seem to be as much a fan of multiblocks than I am... 😁 ) that allows one tree to grow on it and can "pick fruit" from it (Ideally picks vanilla cocoa, Pam's HarvestCraft Trees and the other mod's (which I forget) that had apples that you can right-click from a leaf block).

**Comment by BluSunrize** [comment]
See that's where we hit the "not for core IE" point again.
I generally refrain from adding anything that doesn't interact with IE or vanilla. The Garden cloche can farm hemp and vanilla crops, compat for other mods is an added benefit.
Vanilla doesn't really have "pickable" fruit however, with the possible exception of Cocoa beans, depending on your definition (apples are a random leaf drop, not really a proper growing fruit).
So, while yes, cocoa could possibly be used as an argument of "vanilla has farmable tree things" I counter with: "You never use cocoa, it's basically pointless except for rarely dyeing things" and that kinda makes a farming machine for it a lot of effort and time spent (on modeling and logic) for a thing that barely has any use.

Could be a thing for an addon, but it's highly unlikely to ever see implementation in IE

**Comment by mindforger** [comment]
well but if you already go the multiblock route, you could still render it vanilla ... you could use a simulated tree render but scaled down to fit the 3x3x5(5 height) 
even the growthstate of the hanging fruits would be "just" a scaled render of the modded(vanilla==cocoa bean) one

i don't know if that is as easy as it sounds but it would not require another IE specific render in that case

**Comment by Vahtera** [comment]
Good points. If you feel it's out of the scope of IE, then just don't do it :) It was a suggestion in the first place, not even a feature request. Anyway I much prefer it anyways if you keep a coherent vision for IE and don't needlessly "branch out" (as some other mods have gone, and have ballooned from something nice to something that has no direction). 

Except I need to point out that cocoa is used quite well, if you use Pam's :P

**Comment by Overato** [comment]
An alternative is Forestry, if that's on the version you're playing, although I haven't kept up with its updates.

**Comment by Vahtera** [comment]
Forestry is crap though (sorry whoever maintains it nowadays), compared to "modern" mods. MultiFarms are big, inefficient and they don't even work 100% of the time. And have other requirements on top of that (Fertilizer, inability to supply itself so you have to pump resources IN, in addition to pumping them out...)

I think I'll go in search of mod developers to bother :D

**Comment by PrincessRTFM** [comment]
One last idea for the multiblock tree fruit picker thing - what if you could give it a vanilla oak tree (the only kind that drops apples, IIRC), and it would _very slowly_ destroy one leaf block at a time for a guaranteed apple drop? Make it take real-life minutes between harvests, and only harvest one leaf block at a time, but always produce an apple. Don't handle the logs, though - make the player break those when the leaves are gone and replant the tree.

Alternatively, make it not destroy leaf blocks, just sporadically spawn a single apple in its inventory. By working so slowly, it just picks an apple when it's ready without breaking the leaves. Of course, you'd need to ensure that there's a real tree there, and you'd also have to handle massive oaks unless you spawned the tree yourself... Maybe cloche-style appearance, with the tree just being rendered inside a big dome, or even use real blocks but inside a big dome, and the multiblock won't form unless the dome is empty on creation?

Just bouncing ideas around, and after writing it out, it sounds decently complex to implement for only one or two vanilla uses.

**Comment by poutrosgit** [comment]
Maybe a tree shaker multiblock for fruit trees (like the oak tree in minecraft and other trees from other mods) and cocoa beans. The leaves and cocoas would not be harvested but the machine would produce them as long as the tree and the mature cocoa block was in range. The multiblock would surround the tree that produces fruits/the log with cocoa beans and slowly output them into an adjancent inventory.
