### ISSUE TITLE
[Suggestion] Hardcore Feature for Jerrycan and Fluid Outlet

### ISSUE THREAD

**Issue by Matikari** [BluSunrize/ImmersiveEngineering#2267]
Some modpack developers like to increase the difficulty by using the hardcore water feature so that water sources can't be placed easily. The jerrycan was still able to place water sources so the developer of our pack removed the ability to craft the jerrycan.

Also, It would be a neat config feature if a similar thing can be done with the fluid outlet, something like what the Screw pump with better with mods can do that maintains a partial water source as long as power and water are supplied.

**Comment by HappyPineapple** [comment]
I'lld say yes as long as this is a config option only.

**Comment by kane-thornwyrd** [comment]
Glad to read your insight on this @HappyPineapple, but, you talk like you'd have some power over the decision process.
Issue tickets are not forum thread, let Blu take his decisions.
