### ISSUE TITLE
[0.12  - 64] New gun holding positions leave skin's "sleeve" layer behind.

### ISSUE THREAD

**Issue by laserlemons** [BluSunrize/ImmersiveEngineering#2269]
![2017-07-08_18 32 10](https://user-images.githubusercontent.com/6501298/27990430-c88d9b1a-640b-11e7-8968-b615ac6e6c04.png)

(slightly unrelated, but what shaders do you get the gun flip animation? I feel like I've tried all of them without seeing it)

**Comment by BluSunrize** [comment]
It's not done by shaders, the changelog specifically said "skins". Those are different ^^
