### ISSUE TITLE
Speed Loaded rendering is not refreshing until you open it on SMP.

### ISSUE THREAD

**Issue by Kubuxu** [BluSunrize/ImmersiveEngineering#227]

**Comment by BluSunrize** [comment]
I know, can't fix without custom packets. It's just how Minecraft works, I can't send item updates like that.

**Comment by asiekierka** [comment]
Why not use custom packets? It's nowhere near as hard as one thinks, and lets you do a lot of things a lot more efficiently.

**Comment by BluSunrize** [comment]
So far I've gone packetless in IE. It's a sort of challenge I set myself for this project. Go without packets for as long as I can ^^
