### ISSUE TITLE
[1.12] Exception in server tick

### ISSUE THREAD

**Issue by whatthedrunk** [BluSunrize/ImmersiveEngineering#2270]
Works great in single player but get this when running on a test server. 
https://pastebin.com/MvKQNRG6

With only IE
https://pastebin.com/fZbxEZcN

**Comment by Morpheus1101** [comment]
Appears something form client running server side, but i also get this error

**Comment by BluSunrize** [comment]
Yeah turns out the side needs to be specified in the subscriber annotation. Fixed for next release.
