### ISSUE TITLE
[1.11.2 - 63] Garden Cloche support for Magical Agriculture's inferium seeds got borked

### ISSUE THREAD

**Issue by Simbrine** [BluSunrize/ImmersiveEngineering#2271]
The title says it; You no longer can put any tier of inferium seeds from Magical Agriculture in the cloche. Is the postInit patch that was used to fix that in the 1.10.2 releases incompatible with 1.11.2?

**Comment by falizure** [comment]
I am currently running a server with these mods as well and i was aware of the issue with extra seeds during testing, i disabled compatibility with mystical in the immersive configs but as i just learned now that did not disable the interaction at all and they can still be used just as they were before, please can i get help disabling the interaction or a fix otherwise i will be forced to disable the cloche for the sake of the server economy balance.

**Comment by BluSunrize** [comment]
If you set the boolean for Mystical Agriculture in the IE config to false on the server and restarted it, the compat module shouldn't even be able to load.

**Comment by falizure** [comment]
there is no such config in 1.10.

**Comment by BluSunrize** [comment]
```
compat {
    ...
    B:mysticalagriculture=true
    ...
}
```

There is.

**Comment by falizure** [comment]
it is set to false on the server, has been since before it was even opened 8 days ago, but you can still put all mystical seeds inside them and it works as expected, that is, extremely fast and overpowered for the host mods progress, i read in another reported issue this is also the case with pam's harvestcraft in 1.10.

**Comment by BluSunrize** [comment]
1.12 compat for MA no longer produces any seeds.
Closing this.

**Comment by tyler489** [comment]
From what version onward?

**Comment by BluSunrize** [comment]
1.12, build 68, which isn't released yet.

**Comment by falizure** [comment]
sorry i add more work but will this be repeated for older versions of mc as well? i would be extremely greatful.

**Comment by BluSunrize** [comment]
Not planned, no. Working basically just on 1.12 now.

**Comment by realdarnedninja** [comment]
Not sure where to post this as this is marked as closed, but I used the new 1.12 - 68 build, and I'm still unable to plant inferium seeds of any tier in the garden cloche. All other resource seeds seem to be working fine.

**Comment by tyler489** [comment]
its because of the TIER tab in the infernoum seeds.

**Comment by BluSunrize** [comment]
Okay so someone fill me in on this then. I've never used MA so I have zero idea how it's supposed to work.

**1) Inferium plants: Do they produce additional seeds & should they produce more seeds in the cloche?** Or would that be imbalanced like it was for resource seeds?

**2) Tiers on Inferium: What's the difference between the tiers on inferium seeds?** More essence? More seeds? Completely different plant?

**3) Tiers on Resource plants:** What do they do? More output?

If we could figure out a decent design document for this compat, then maybe it wouldn't be so terrible. But I know nothing of the mod so I need some community input here.

**Comment by Sixer601** [comment]
Hey, I was wondering what the final verdict was on compatibility between the inferium crops. Are they not going to be compatible? Are they going to be compatible, but in a later release? and Is there a way to fix them not being compatible currently? Thanks :)

**Comment by BluSunrize** [comment]
I mean, I did specifically ask for input on how to handle them. I'll gladly add compat if someone tells me how to make them work. I don't *know* the mod, never played with it, so I need community input xD

**Comment by Sixer601** [comment]
1) I believe with after playing with both mods, no seeds should be provided. This way there is no additional yields with the seed reprocessor. They do produce additional seeds upon harvesting, although the likelyhood is 5%.
2) The difference is the fact that they yield more inferium per harvest. Tier one makes one per harvest, tier two makes two, and tier 5 makes 5. This is also the case in the mods seed reprocessor
3) Tiers on Resource plants function similarly to that of the inferium crops, where as tier one yields one inferium, tier one resource crops yield one essence of that resource. And the same proportions are in both resource crops and inferium crops.
Hope this helps :)

**Comment by realdarnedninja** [comment]
@Sixer601 - I hadn't noticed that Resource plants have tiers. Is this definitely a thing? Inferium seeds have 5 distinct seeds in JEI, one for each tier, but I hadn't noticed anything similar for the resource crops.

@BluSunrize:
**1** - When planted normally, Inferium seeds produced an extra seed when harvested, at the percentage chance specified in the MA config (default: 5%). I don't think they should produce extra seeds in the Cloche though.

**2** - The tiers of Inferium seeds are distinct items in JEI, from tier 1 to tier 5. They each have a distinct recipe also. Each tier grows a bit faster than the last, and produces more essence when harvested.

**3** - To be honest, I'm not sure resource crops have tiers. I will have to check when I'm back home, but if they do, I assume they function similarly to the above.

**Comment by tyler489** [comment]
Resource crops have tiers but its only a marker of what kind of essence you need to craft them

**Comment by BluSunrize** [comment]
Ah right! I misunderstood that then I only browsed over them in JEI and saw tiers.

So in summary, for expanding MA compat:
- add Inferium Seeds to the cloche
- they don't produce seeds, just essence
- the amount of essence produced is equal to their tier (Tier 1 == 1 essence)
- their growth speed increases with tiers (anyone got an idea by how much? percentage possibly?)

**Comment by realdarnedninja** [comment]
Ah yes, @tyler489 is correct. The tier of the resource seeds is just an indicator of how expensive they are really. 

@BluSunrize: I imagine the Tier x = x essence is correct, but I can let you know the exact amount of essence produced when I get back home.

Re: The speed increases. I don't think this is documented anywhere, but I can spin up a test world and see if I can estimate it. I personally don't think it's super necessary to get this working though, as growth speed in the cloche is already amped up quite a bit. The benefit of the higher tier Inferium seeds is really the increased essence yield.

**Comment by tyler489** [comment]
Tier 1 produces 1 essence tier 5 produce 5...

**Comment by tyler489** [comment]
I agree dont worry about speed

**Comment by realdarnedninja** [comment]
Okay, did some testing. @tyler489 is correct, the tier of the seed is how much essence is producted. T1 = 1 essence, T2 = 2 essence, etc.

As for the growth speed, there seems to be no noticeable difference between tiers, so I may have just imagined that.

Hope this helps, @BluSunrize.

**Comment by Sixer601** [comment]
Same, sorry if my information was false.
