### ISSUE TITLE
[1.12] No Plate crafting recipe

### ISSUE THREAD

**Issue by EmosewaGamer** [BluSunrize/ImmersiveEngineering#2273]
In the 1.12 version there's simply no crafting recipe for plates. You can't make them with the hammer and appropriate ingot.

**Comment by BluSunrize** [comment]
Yeah recipes in generally are wonky. I'm looking into moving them all to JSON. Hopefully I'll get it done today.

**Comment by EmosewaGamer** [comment]
Nice! I guess that also explains the conveyor.

**Comment by Sparksolur** [comment]
I'm hoping this is related, since I found out I can't make the hammer or coke bricks.

**Comment by BluSunrize** [comment]
Yeah it's basically all recipes. I'm working on it, but it's a slow process to move them all to JSON.

**Comment by malte0811** [comment]
Blu, do you know about [this](https://gist.github.com/williewillus/a1a899ce5b0f0ba099078d46ae3dae6e)? Haven't used it yet, but if it works as intended it should make the process a lot faster.

**Comment by BluSunrize** [comment]
I didn't, instead I already wrote my own :V

I hope to get this done tonight, otherwise probably around noon tomorrow.

**Comment by BluSunrize** [comment]
Fixed!
