### ISSUE TITLE
Crash in 1.12 | 0.12 - 64 | Server-side only

### ISSUE THREAD

**Issue by ExDomino** [BluSunrize/ImmersiveEngineering#2274]
Minecraft : 1.12
Forge : 2405
ImmersiveEngineering : 0.12-64

Crash only server-side, doesn't crash client-side.

net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: blusunrize.immersiveengineering.client.ClientProxy

https://pastebin.com/U6D7A1vm

**Comment by malte0811** [comment]
Duplicate of #2270, fixed for the next release which will probably be released today.

**Comment by ExDomino** [comment]
Thanks. We're looking forward this next release.
