### ISSUE TITLE
[1.12] Server Crash

### ISSUE THREAD

**Issue by EmosewaGamer** [BluSunrize/ImmersiveEngineering#2277]
When loading up a server with the 1.12 version, it crashes:
 https://paste.ee/p/VE0Gn

**Comment by Kris1432** [comment]
Already been reported a few times, check the closed issues before reporting. #2275 #2272 #2270 #2274

**Comment by Levainen** [comment]
Same problem. Checked on a clean server. Server crashed
[crash-2017-07-09_20.11.30-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1133919/crash-2017-07-09_20.11.30-server.txt)

**Comment by malte0811** [comment]
As @Kris1432 said this is a duplicate. The next release with the fix will probably be published later today.
