### ISSUE TITLE
Needing the middle block for the coke oven is just trolling us

### ISSUE THREAD

**Issue by eslachance** [BluSunrize/ImmersiveEngineering#228]
What am I going to do with the 3 remaining Coke Oven blocks, man? It's not like I needed a diamond to make the oven, but still. Could have stayed with the Railcraft middle empty block to make a nice, round number :P

**Comment by BluSunrize** [comment]
As long as you make an even number of ovens, you won't have any leftovers ;3

**Comment by Kubuxu** [comment]
And one coal blocks and one wood ovens are perfect to run blast furnace all the time.
