### ISSUE TITLE
1.11.2

### ISSUE THREAD

**Issue by 0142929** [BluSunrize/ImmersiveEngineering#2280]
hello,
keep 1.11.2 please!
most must-have mods still stay on 1.11.2
anyway this mod is very cool )

**Comment by BluSunrize** [comment]
Nah, I'm moving ahead to 1.12.
I will not see IE get left behind again.

**Comment by 0142929** [comment]
minecraft's developers change versions like gloves, maybe we should wait a bit..

**Comment by KnightMiner** [comment]
People plan to wait on 1.12 for awhile, the goal is to avoid being divided on which version to wait on
