### ISSUE TITLE
[1.11.2 - 63] automated workbench & assembler

### ISSUE THREAD

**Issue by 0142929** [BluSunrize/ImmersiveEngineering#2282]
hello.
me have been trying to assemble a automated workbench and assembler for several hours,
but right click with the hammer give nothing.
are there any tricks when assembling these machines?
thank you.

**Comment by BluSunrize** [comment]
Pictures of your setup, version number, debug crash?
You know, all the things in the contribution guidelines that you didn't read?

**Comment by 0142929** [comment]
1.11.2 - ImmersiveEngineering-0.11-63.jar
no crash, no errors.

![2017-07-10_08 47 46](https://user-images.githubusercontent.com/896793/28004342-94894fc0-654c-11e7-891d-30af7c0653ec.png)

![2017-07-10_08 50 05](https://user-images.githubusercontent.com/896793/28004367-cb484584-654c-11e7-908a-f9c58958dc46.png)

**Comment by 0142929** [comment]
are the build recipes different from versions?

**Comment by BluSunrize** [comment]
They're not, no.
Are you by chance using the conveyors that ignore redstone rather than normal ones?

**Comment by 0142929** [comment]
yes, this is my fault, problem solved, thank you

**Comment by 0142929** [comment]
by the way, engineer's manual does not understand the difference conveyors )

**Comment by BrianEdmonds** [comment]
> Are you by chance using the conveyors that ignore redstone rather than
> normal ones?

@BluSunrize, any reason not to have the builds that require conveyor
belts accept either type? Seems reasonable to me, and avoids this
recurring confusion.

**Comment by BluSunrize** [comment]
Mostly due to the annoyance of doubling up on every if statement. I'll look into it.
