### ISSUE TITLE
Server Side Crash (1.12

### ISSUE THREAD

**Issue by XB1-Hexdecimal** [BluSunrize/ImmersiveEngineering#2283]
Added Immersive Engineering 0.12 - 64, to my modpack, works great client side, but on the server, it crashes with: net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: blusunrize.immersiveengineering.client.ClientProxy

Full Crash Log Here: https://pastebin.com/qaTkNccS

Modlist is here: http://modlister.com/server/Avernus

Running Forge 2004.

**Comment by BluSunrize** [comment]
Use the search function.
