### ISSUE TITLE
[1.11.2 - 63] small visual bug

### ISSUE THREAD

**Issue by 0142929** [BluSunrize/ImmersiveEngineering#2284]
small visual bug at engineer's workbench interface
![engineers_workbench](https://user-images.githubusercontent.com/896793/28004964-b17c7fd6-6550-11e7-83f3-ee71abe79481.jpg)

**Comment by BluSunrize** [comment]
The slots overlapping? Yeah, I know, pretty minor though. I fixed this for 1.12 but I won't be porting back to 1.11.2.

**Comment by 0142929** [comment]
i see,
thanks.
