### ISSUE TITLE
1.12 : Some recipes are not craftable

### ISSUE THREAD

**Issue by ExDomino** [BluSunrize/ImmersiveEngineering#2287]
Hello, like many of other mods, major of the recipes from your mod are not craftable. And liquid are not rendered correctly. The connectors for example, are not craftable. The transformers either. It's maybe about Froge that have had the good idea to change something in the crafting register system, because a lot of other mods have these problems, RF Tools and Deep Resonance, for example. Version 65 of the mod, Forge 2405. I think the broken recipes are those shapeless.

**Comment by Skillotic0703** [comment]
Fixed! Go on curseforge!

**Comment by ExDomino** [comment]
In the 66 version of the mod, transformers are craftable?

**Comment by BluSunrize** [comment]
Yes.

**Comment by ExDomino** [comment]
Fixed in 66. Confirmed!
