### ISSUE TITLE
[1.12] Conveyors random bug

### ISSUE THREAD

**Issue by Skillotic0703** [BluSunrize/ImmersiveEngineering#2289]
Forge 1.12 - 14.21.1.2406
Immersive Engineering 0.12 - 66
When you give yourself a conveyor belt (/give player immersiveengineering:conveyor) you get a buggy one that doesn't have a NBT Tag but that has a localization issue : 
![2017-07-11_00 22 06](https://user-images.githubusercontent.com/12701912/28042769-009adfbc-65cf-11e7-8682-b66175a0810e.png)

And sometimes for no reason, when you place not buggy conveyor belts, they seem to loose their NBT Tag. That's completely random and I'm pretty sure it's hard to reproduce. If you want more informations just tell me!

**Comment by BluSunrize** [comment]
Well yes, giving yourself one makes that happen. You're not supposed to use the give command like that.
If you want a proper conveyor: Crafting, creative mode or JEI.

When you say the NBT is lost on placement, could you please elaborate? When you place a conveyor, how does it look in world (screenshot) and what do you get when you pick it up again (also screenshot)?

**Comment by Skillotic0703** [comment]
![2017-07-11_13 42 48](https://user-images.githubusercontent.com/12701912/28066834-e4670120-663e-11e7-85e6-7cf4ca79e9fa.png)
I get the same thing when I pick it up again (what's on the first screenshot)

**Comment by BluSunrize** [comment]
Well that's a broken one you placed, no?

If you get a normal, correctly textured conveyor, and place it, is it broken?

**Comment by Skillotic0703** [comment]
No, it isn't but very rarely for no reason it breaks!

**Comment by Skillotic0703** [comment]
When I reported the bug, I knew it was unreproducable but I thought it would be useful anyway to report it.

**Comment by BluSunrize** [comment]
It's probably an interaction bug then. If you can reliably reproduce it, I'd consider it valid, but without that I don't have a testcase to work with.

I have not encountered this error once in my time of working on IE, and I can't fix what I can't find.

I'll close this for now, if you can reproduce this reliably in an instance with just IE, lemme know.

**Comment by mindforger** [comment]
is there the possibility of this beeing a coordinate thing in any way? i mean i can remember a efw few oddities with such in the past, just by chance :)

**Comment by Skillotic0703** [comment]
You were right that was a mod interaction with tools in CoFH mods which break several blocks at a time. I will tell King Lemming about that!

**Comment by KingLemming** [comment]
Right. Here's the thing. TE Machines also keep track of a rather large amount of NBT data, and they don't screw up.

So clearly there's an interaction here we need to figure out. We go pretty far out of our way to make our multi-block breaking as pure as possible, so I guess the question is why our method of breaking things seems to mess up conveyors (and AFAIK, literally only conveyors).

**Comment by BluSunrize** [comment]
I chose the required drop in
`harvestBlock(World world, EntityPlayer player, BlockPos pos, IBlockState state, TileEntity tile, ItemStack stack)`
and rely on the TileEntity not being null. That's all there is to it, really.

**Comment by KingLemming** [comment]
Does your onBlockDestroyedByPlayer intentionally wipe out the tile entity or something?

**Comment by BluSunrize** [comment]
Nope.
