### ISSUE TITLE
Invisible crusher

### ISSUE THREAD

**Issue by MtnDrew** [BluSunrize/ImmersiveEngineering#229]
I was looking through old issues and didn't see anything referencing this but I might have missed something. When I build the Crusher multiblock, and right click it with a hammer, the entire multiblock turns invisible. I am currently only using the mods Not Enough Items, Forge 1448, and Immersive Engineering 1.4.2.

**Comment by BluSunrize** [comment]
I'm aware of the bug. Will be fixed asap.

**Comment by Nathan1852** [comment]
This also happens with the excavator

**Comment by BluSunrize** [comment]
It happens with any TileRender that was supposed to have configureable render distance. Windmills+Watermills too.

**Comment by mindforger** [comment]
@BluSunrize this issue popped up again after updating a 0.5.4 world to 0.6.0, is it possible that existing multiblock may have meta data stored or the whole world probably that cause confusion?

Would it be possible to add a check for renderdistance in the meta(nbt) data on loading to check for sanity?

in our case we lost the rendering of an excavator ... even replacing it on another spot (didn't check the chunk boundarys) did not help! the moment it is formed it becomes invisible again.

i'll investigate the NBT of the world as we had also a strange "config regeneration" .. alsmost all of our setups reappeared after deleteing our config to provide a clean update .. only a few new and the increased power capacities showed up new, the rest looked like it was untouched
