### ISSUE TITLE
[0.12-66] Missing Hammer Recipes

### ISSUE THREAD

**Issue by BLOODAXED** [BluSunrize/ImmersiveEngineering#2290]
All plate recipes that do not use the metal press are unavailable in Single Player.  It appears to have affected all shapeless recipes using the hammer.  Log also specifically contains this output: 

> A broken ore dictionary registration with name crystalSlag has occurred. It adds an item (type: class blusunrize.immersiveengineering.common.items.ItemIEBase) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.

Current modlist: https://gist.github.com/BLOODAXED/2918f6b2ba36f532271a679ba874e0a9
Logfile: https://gist.github.com/BLOODAXED/dc3a564fda94d2965bc8443fdfacb950

**Comment by BluSunrize** [comment]
The actual fuck?
Very odd.

I'll be sure to look into this, but for now as a temporary fix, go disable Thermal Foundation compat in IE's config. That should circumvent the issue.

**Comment by BLOODAXED** [comment]
Disabling compat for thermal foundation has caused the aforementioned error to go away, however the recipes are still missing and uncraftable.

Updated Logfile: https://gist.github.com/BLOODAXED/89668e37e009e4556fbe6e771bb2f3d5

**Comment by BluSunrize** [comment]
Right, so it appears I just blatantly forgot to add recipes for plates. Woops.
