### ISSUE TITLE
[Question] Power consumption rates

### ISSUE THREAD

**Issue by ldog** [BluSunrize/ImmersiveEngineering#2293]
I've looked through the config files and I only see adjustments to whatever the base rate is, but not the base rate itself, and I know for a fact the values on the FTB wiki (which is about the only online doc) are pretty much all incorrect. I've been eyeballing and using the voltmeter. Is there a comprehensive list somewhere?

The squeezer and fermenter seem to be using 384if/t, or 48 per item (since it does 8) which seems a bit high. Automated engineering bench uses an awful lot, forget how much but takes an MV to keep up and as  slow as it is it seems like way too much compared to the assembler. (yes I know I can adjust settings, just making sure things are working as intended).

Arc furnace? Can it use more than 4096? It seems like if all 12 input slots are full it would since best I can reckon it seems to be 512 per item, so potentially 6144.

Again FTB wiki says about a lot of machines "speed depends on power input" but in reality it's machine will operate slower on less than required amount of power. Like the presses just pause if they don't have full power, but they will only use...32?

Not complaining, just trying to "rightsize"my wiring design, mainly on the off chance that you someday implement IC2 like consequences to overpowering. Right now designing an IE factory that uses every part of IE and only uses IE as much as possible.

**Comment by BluSunrize** [comment]
Eh.
I kinda enjoy not throwing numbers about (mostly because I can hardly remember them myself).
Think of it as a Botania-esque approach, I guess? :V

**Comment by ldog** [comment]
LOL, fair enough, I went looking through the source but I'm lost there. Not a big deal I guess, if I wanted to be efficient I'd do it with TE, trying to do it all with IE for the challenge and the coolness factor. 2 diesels seems enough to power an entire small complex if you don't go crazy placing turrets :)
