### ISSUE TITLE
[Bug] [Interaction With Other Mod] Saving and Reloading bugs out IE Connector and TD Fluxduct transfer

### ISSUE THREAD

**Issue by MonaMoonlight** [BluSunrize/ImmersiveEngineering#2294]
Saving and reloading makes it so IE connectors can no longer transfer RF to Thermal Dynamics Fluxducts, unless the connector is broken and replaced.

I tested on TE power cells too, and they still get charge from connectors, but it doesn't work with ducts.

Confirmed for 1.12 - 66

**Comment by malte0811** [comment]
Are the fluxducts visually connected to the connectors when they don't transfer energy any more?

**Comment by MonaMoonlight** [comment]
Yes, they are.

**Comment by Hundifan33** [comment]
I can confirm that this is also happening in 1.12 - 88 (In SMP).
It can also be seen in a youtube video with this id "oHhVDs1biu4" (time: 10:23, (not my video))

**Comment by hmshood** [comment]
I am also seeing this happen in IE 1.12-91 in SMP. It's been 100% reproducible if any HV/MV/LV connector is attached to a fluxduct as an "input" to that fluxduct, save and reload will fail to transfer power.  The duct and connector stay visually connected but no power transferred.

To reproduce:
Have some source of RF - e.g. TE power cell
Connect an IE connector to this source
Connect an IE connector to a fluxduct not attached to power cell
Join the two connectors
Save/exit and reload
Observe that the fluxduct no longer receives power
Power can be restored by destroying either connector and rejoining with wire

I also found that if using connector-relay-connector if the relay was attached to other devices, they still received power, but the fluxduct did not. This suggests to me that the powercell connection was working.
