### ISSUE TITLE
[Suggestion] Redstone signal output from machinery inventory

### ISSUE THREAD

**Issue by ldog** [BluSunrize/ImmersiveEngineering#2295]
Sorry, don't know if this is already in (can't seem to find any mention of it, neither wiki nor Valen's vids) but it would be great if the machines output redstone signals for inventory status on machines (fermenter and squeezer in particular). I've got a working shutoff for full conveyors from silos with redstone cables, but I'd love to do away with the comparator and hopper at the destination end.

**Comment by maham** [comment]
Oh, I would love a redstone connector with built-in comparator. That would solve some of this.

**Comment by ldog** [comment]
So I normally don't go to twitter (I still honestly don't understand it) but I see you are working on a comparator type connector, most awesome! Bonus points if it reads the squeezer and fermenter inputs!
An inverting connector and maybe an "uninsulated" redstone wire type (for 1 to many connections) and we'll be rockin it.

**Comment by BluSunrize** [comment]
Yeah I wanted to do this for a while, finally got around to it.
I am yet unsure on how to integrate it with the multiblocks.
What were you thinking for the Fermenter+Squeezer? What would determine signal strength?

Also, what'd you want the uninsulated wire to do? Not following your thought there

**Comment by ldog** [comment]
Considering your redstone cable doesn't care about signal strength, a signal on input area full would be the most useful thing (or empty if it can't be inverted) - that can be sent to a silo to tell it to drop/stop dropping on the conveyors feeding it as an example. I know trying to think of all the possible use cases it can get out of hand. The next guy will probably want it on the output tank.

Uninsulated wire, or more accurately connector, for combining signals. For example maybe you want a master kill switch but you also want individual on/off switches for something. Or maybe you want to turn on a conveyor if the fermenter is empty OR if you want to bake a potato.

**Comment by ldog** [comment]
Actually I rethought the inventory a bit. So here is how I do it right now (unless I'm lazy and I use TD itemducts/servos which works flawlessly, but trying to make an IE way)
![2017-07-15_09 28 17](https://user-images.githubusercontent.com/7410326/28239689-0f7e835c-6940-11e7-993b-bd211bd5be19.png)
So if there is anything in the hopper feeding the squeezer it sends a redstone signal to the hopper under the silo, which makes it stop dumping on the belt. So long as the squeezer isn't full the items pass through the hoppers fast enough to keep a constant flow without any backup. The minute the squeezer gets full, input stops, the input hopper takes whatever is on the belts. It works pretty well actually. 

So if the fermenter itself output signal strength according to how full it was, it would still work for this setup (because if it's processing items it will get empty quickly anyway), it would also work for more complicated things other people might want to do too.

**Comment by BluSunrize** [comment]
My wires do care about strength, they just don't lose any over distance.
However they will always get the maximum signal on a single colour, so if you have a input level of 3 and one of 15, the output will be 15.

Yeah a signal based on inventory filling is probably going to be the most sensible thing, for the majority of machines, aka: Squeezer, Fermenter, Arc Furnace, Mixer, Assembler, Auto-Workbench.

Other ideas would be having the Excavator output a signal based on how much ore is left in the vein and having the arc electrodes emit a comparator signal based on their health?

As for having inputs that can be set to "all frequencies", yeah I can look into that.

**Comment by ldog** [comment]
Oh, I thought they always output 15 no matter what the input is. Haven't experimented enough I guess.

The excavator and electrodes would be great too.

**Comment by ldog** [comment]
So they work. Of course I had to suffer another crash to read the manual lol.
It isn't the smoothest without the hopper input buffer, but it works. I send the signal to a redstone lamp next to the silos with redstone torches hanging off; inverter and indicator lamp in 1 (granted I can't see it when the walls go up).  Admittedly my redstone skillz are weak. I'll probably have to back to the input hopper, but it's still more compact and better looking without the comparator.

**Comment by ldog** [comment]
I see it is reading input and output inventories as well, which is not a bad thing but maybe invert the input if possible (so the seed area outputs 15 when empty, and downwards to 0 when full...wouldn't need to invert for silos then)?  I ran some HOP through squeezer (not setup to output it yet) and I noticed it also is triggering my redstone.

**Comment by BluSunrize** [comment]
I changed it so Arc Furnace, Fermenter + Squeezer only measure their input slots now.

**Comment by tolomea** [comment]
This is amazing, it will make life with conveyor belts so much nicer, any chance of a back port to 1.11?

We're currently on 1.10 but I want this so bad I did an audit of the mods on our server. Net result I could probably upgrade to 1.11 but 1.12 isn't happening. The bulk of our worldgen (ATG + UBC) seems to still be on 1.11.

**Comment by BluSunrize** [comment]
Nopes. Not porting anything back. 1.12 is my dev version now ^^

**Comment by ldog** [comment]
Sweet! If i can drag myself away from 7DTD (major update just dropped) I'll check it out.

**Comment by BluSunrize** [comment]
That major update fucked the server config files again I bet. Good times.

**Comment by PrincessRTFM** [comment]
@ldog

> It isn't the smoothest without the hopper input buffer

Sounds like a redstone latch would help. When the signal _X_ (say, 13), stop output. When the signal drops to _Y_ where _Y_ < _X_ (say, 7), start output again. I know you can make an RS-NOR latch in vanilla, in case you don't have a mod that adds RS utility blocks. That particular type has two outputs and two inputs. Input A turns on output 1 and off output 2, Input B does the opposite. It'd be a relatively simple matter from there to use vanilla comparators in subtraction mod.
