### ISSUE TITLE
Not able to craft with Engineer's Hammer

### ISSUE THREAD

**Issue by Builder1111** [BluSunrize/ImmersiveEngineering#2296]
I am currently not able to use any of the crafting recipes that use the engineer's hammer (Sheet metal and the powder versions of the metals).
I have just recently started this mod, so I am not aware of many of the features; so I don't if this is just simply something I am doing wrong, or if there is a bug in the mod coding.
I am using the 0.12-66 version for 1.12.

**Comment by BluSunrize** [comment]
The plate thing is known and fixed, the crushing recipes I will be fixing shortly.
