### ISSUE TITLE
[1.12] Invisible Player Model

### ISSUE THREAD

**Issue by Gawdin** [BluSunrize/ImmersiveEngineering#2298]
When running IE with Mo'Bends, the player model is invisible in third person and to other players.

MC 1.12
Forge: 2406
ImmEng: 0.12-66
Mo'Bends: 0.23.4

Changing settings in Mo'Bends does not make a difference, disabling either mod restores the player model (and if IE was disabled, Mo'bends functions normally).

**Comment by BluSunrize** [comment]
IE has a config option for the fancy rendering for exactly this case.
