### ISSUE TITLE
[IE Manual] not showing some full renders of multiblocks

### ISSUE THREAD

**Issue by FoxPlushie** [BluSunrize/ImmersiveEngineering#2299]
The IE Manual isn't showing full renders of multi-blocks, 
It seems to be affecting only the "Overview and Resources" Index page of the book. 
This is in Single player Mode [Unstable 1.12 vers 1.0.1]  IE Vers 66
Not been able to check in Multi player.

![2017-07-13_00 12 32](https://user-images.githubusercontent.com/30120784/28124334-82b76530-6762-11e7-8933-1a19ffb08520.png)
![2017-07-13_00 13 07](https://user-images.githubusercontent.com/30120784/28124343-8a14ab8a-6762-11e7-9d48-56072269b6bd.png)
![2017-07-13_00 13 31](https://user-images.githubusercontent.com/30120784/28124350-8f1de952-6762-11e7-830f-68743598ca33.png)

**Comment by BluSunrize** [comment]
Those multiblocks have never been able to render a complete structure...
