### ISSUE TITLE
Can't put Hempcrete into carpenters blocks

### ISSUE THREAD

**Issue by TheQuantumGeneral** [BluSunrize/ImmersiveEngineering#230]
![2015-07-18_20 34 47](https://cloud.githubusercontent.com/assets/7843312/8761285/8eb278fa-2d8c-11e5-8d0e-c6b87473e22b.png)

**Comment by BluSunrize** [comment]
Not a bug and not really fixable either.

**Comment by TheQuantumGeneral** [comment]
Intended behavior? Never seen any block that wasn't a machine that couldn't go into carpenters blocks. CTM stuff, transpartent, chisel stuff with fancy rendering like the Hex bricks, etc.

**Comment by BluSunrize** [comment]
I used a custom render ID, that's the issue. And that render ID is shared between all "stone blocks", including the semiconductive glass. That's why it's not working.
