### ISSUE TITLE
Redstone wire connectors broken?

### ISSUE THREAD

**Issue by cragrim** [BluSunrize/ImmersiveEngineering#2300]
I'm currently on Minecraft V1.11.2 with forge-1.11.2-13.20.1.2391 ImmersiveEngineering-0.11-63.jar and can't seem to get redstone wire connectors to send any Redstone signals. Is this a known issue?
Im not getting any errors otherwise. Any ideas or could it be some other issue?

Best Regards
Keep up the good work!
 
Screenshot:
![Image](http://i.imgur.com/TNzyCgG.png)

**Comment by malte0811** [comment]
Did you set the connectors to output mode (orange ring rather than blue)? Doesn't look like it on the connector on top of the lamp, can't see it for the other one.

**Comment by cragrim** [comment]
You are 100% correct sir. Close this issue. I am a giant dingus. Cheers

**Comment by ldog** [comment]
LOL, yeah, I do this all the time too.

**Comment by malte0811** [comment]
@cragrim you could close the issue yourself since you opened it :smile:
