### ISSUE TITLE
Can't craft items?

### ISSUE THREAD

**Issue by Shockingglitch3** [BluSunrize/ImmersiveEngineering#2301]
I'm in 1.12 and I'm not sure if you're not supposed to be able to create items yet? (Like the hammer treated wood etc) As of now it seems I'm unable to make those and a few other items.

**Comment by Drytchnath** [comment]
Similar issue in 1.12, IE build 66, Forge 2406. Using ATM3 pack, single player world. Can make things like coke furnaces, the engineer's hammer and sails for windmills. I cannot make metal plates of any kind with any ingot type. Tried in a creative world but same result. Not sure if a workaround is available since I need the plates to make wire.

**Comment by ManfranMike** [comment]
I am experiencing the same issue. All Engineer's Recipes seem to be disabled except for hammering Uranium into grit (disable Hammer Crushing is set to False in my config). It is the only use listed in JEI, as well.

**Comment by BrianEdmonds** [comment]
1.12 introduced a lot of churn in how recipes are done. Blu said the
hammer issues should be fixed in the next release.

**Comment by ldog** [comment]
Yeah, everything hammer borked.
Also anyone got steel blocks crafting into 8 electrum ingots, or is that just me?

**Comment by BluSunrize** [comment]
Yeah I fixed that too.

**Comment by ldog** [comment]
Engineer's workbench not consuming material, at least for steel components. Had to cheat in blueprints of course (no recipes, even with config). Not sure if you've got a punchlist going or not.

**Comment by BluSunrize** [comment]
Recipes in the workbench work fine for me, recipes to craft Blueprint have been fixed already.

**Comment by ldog** [comment]
In 12-66?
A little more on the bench, on more experimenting it seems like an off glitch, the whole crafting (and I mean vanilla) system in 1.12 seems a bit laggy. I just made some iron comps, material was still there, but when I clicked again it vanished, so maybe was just a 1 time thing.
