### ISSUE TITLE
Cannot hammer ingots into plates in 1.12

### ISSUE THREAD

**Issue by Error404-usernamenotfound** [BluSunrize/ImmersiveEngineering#2302]
Using the Immersive Engineering hammer next to an ingot (copper) doesn't output a crafting solution.
![20170713131636_1](https://user-images.githubusercontent.com/20631365/28178852-f29c5f2a-67cd-11e7-8e27-f6c615600318.jpg)
It does not seem to appear as one way of crafting it, apart from the metal press and sheet metal block.
![20170713131704_1](https://user-images.githubusercontent.com/20631365/28178886-164db2fc-67ce-11e7-9503-344870baa2a3.jpg)
I suppose the new crafting UI broke the recipe?

**Comment by BluSunrize** [comment]
Nah, I just plain forgot to add them.
Has already been fixed for the next release though ^^
