### ISSUE TITLE
Core sample drill does not work with spongeforge

### ISSUE THREAD

**Issue by JonoColwell** [BluSunrize/ImmersiveEngineering#2304]
Core sample drill will not produce a core sample when playing with spongeforge.

I think this is to do with the way that spongeforge handles itemdrop events.

**Comment by PrincessRTFM** [comment]
Didn't Blu say he wasn't going to support anything but plain Forge? I might be wrong about that, but I thought I read him saying that somewhere...

**Comment by BluSunrize** [comment]
Yeah, basically that. If Spongeforge messes with item drops, nothing I can do about it.
