### ISSUE TITLE
Block above connector makes connection obstructed

### ISSUE THREAD

**Issue by Kubuxu** [BluSunrize/ImmersiveEngineering#231]

**Comment by theunkn0wn1** [comment]
Yep, this bug(?) existed for quite a few versions ago, though may be a feature.
The issue: Stated in OP
Steps to reproduce:
 [1]Have an connector (of any voltage) placed on top of a block
[2] place second connector, connector 2, in any direction that has clear LOS to connector 1; preferably on the same x/z coordinate as connector 1
[3] place any block above connector 1
[4] attempt to connect connector 1 to connector 2.


bug-inducing:
![image](https://cloud.githubusercontent.com/assets/3110986/8762708/f115c6b6-2d35-11e5-9f9b-0fc3c96f8c5b.png)
bug-free:
![image](https://cloud.githubusercontent.com/assets/3110986/8762711/0a16ffc2-2d36-11e5-8d81-df22bb8f03e1.png)

**Comment by Kubuxu** [comment]
I don't think it is a feature. Its quite annoying for sure.

**Comment by theunkn0wn1** [comment]
It (from my understanding) is code that prevents the player from effectively wiring through walls by ray-tracing the connection. 
~~I propose an error has occurred with the implementation of Utils.canBlocksSeeOther and how the connection offset passed to it from ItemWireCoil.~~
It has to do with the wire connection offset, after testing varius connection types,
![image](https://cloud.githubusercontent.com/assets/3110986/8762936/20aae04a-2d3c-11e5-9648-92fc7539ffdc.png)
The above img shows the two connectors have LOS, thus *should* be able to see each other, they cannot as the block above the far connector is obstructing the ray trace and thus the connection. The only way this connection could be obstructed in this setup is if the connection offset was set *inside* the above block.
![image](https://cloud.githubusercontent.com/assets/3110986/8762964/9da6ff42-2d3d-11e5-83d3-bc0177e6ef86.png)
The two connectors are right next to each other, and again the blocks *above* them invalidate the connection.
![image](https://cloud.githubusercontent.com/assets/3110986/8762969/e27175f8-2d3d-11e5-8264-2d4700574068.png)
Funnily enough, this works


@BluSunrize 
correct me if I am wrong, I am not as skilled in Java as you are and you know your mod far better than I.

**Comment by BluSunrize** [comment]
I'll look into it.

**Comment by theunkn0wn1** [comment]
Here is a practical example of the bug:
![image](https://cloud.githubusercontent.com/assets/3110986/8767111/83af32c0-2e06-11e5-9df2-eca1bef4b376.png)

I was unable to connect the HV transformer to the HV relay while there was blocks (represented with redstone blocks for clarity) above the transformer and the relay (+1 Y)
