### ISSUE TITLE
Texture from any post

### ISSUE THREAD

**Issue by MrArnoEnCo** [BluSunrize/ImmersiveEngineering#2311]
Minecraft: 1.12
Forge: 2412
IE:0-12-66

![bug 2](https://user-images.githubusercontent.com/2693470/28246806-ccdee31e-6a22-11e7-860b-48550caeae2a.png)
![ie bug](https://user-images.githubusercontent.com/2693470/28246807-ccf5cf48-6a22-11e7-97cf-bb3bdb40357f.png)

**Comment by malte0811** [comment]
This is a well known issue, happens whenever the post goes past a y-coordinate divisible by 16.
I just had one of my crazy ideas: Improve #2307 and fix all such issues in IE by implementing a better chunk rendering system within IE: One VBO per render chunk (16^3) containing IE blocks with models larger than one block, created just like the vanilla ones but containing just IE's blocks. All of them would be rendered in the WorldRenderPost event (might not be the exact name). The render bounding boxes of the IE chunk VBO's would be expanded to match the total size of the blocks rendered in it. As I said, a bit crazy and quite complex for solving such a minor issue. No idea what performance would be like. Might be fun to implement though.

**Comment by marikc0** [comment]
I'm having the same issue.

**Comment by BluSunrize** [comment]
As Malte described above, go check if the issue persists if you just put it a block higher. We really can't too much on this .-.

**Comment by marikc0** [comment]
Seems Ok if placed a block higher.
