### ISSUE TITLE
Version 0.12-64 - current Coke Brick error

### ISSUE THREAD

**Issue by schnitzlein** [BluSunrize/ImmersiveEngineering#2312]
Like your work really much, cool mod!
There is a Bug (maybe in cooperation with other mods) with Coke Brick.
It is not displayed correctly and the crafting receipe won't load.
I can't craft it normaly so i have to cheat the bricks ...

maybe it collide ..?

**Comment by ldog** [comment]
12-66 is the latest. Coke brick recipe works. A lot of other still don't.

**Comment by BluSunrize** [comment]
^ that. =P
