### ISSUE TITLE
Cloches?

### ISSUE THREAD

**Issue by tyler489** [BluSunrize/ImmersiveEngineering#2313]
in The Newest version of IE for 1.12 it seems that Cloches are not interactable with Thermal Expansion pipes or Extra utilities transfernodes.

**Comment by zackeezy** [comment]
Are you using a servo?

**Comment by tyler489** [comment]
Yep

**Comment by zackeezy** [comment]
Try without it.

**Comment by tyler489** [comment]
also doesnt work. 
doesnt work with any pipe but will work with a chest

**Comment by BluSunrize** [comment]
Pictures. Of. Your. Setup.

Is it so hard to read the contribution guidelines? .-.

**Comment by tyler489** [comment]
https://gyazo.com/73b3992d796c428db1c04aa527d173d1

**Comment by tyler489** [comment]
Water will go in but power wont. tested with various Themal Explansion cables and generators. Also pipes wont pull out items and tranfernode wont either

**Comment by zackeezy** [comment]
Try placing the inventory right by the output slot

**Comment by BluSunrize** [comment]
![image](http://puu.sh/wM86t/0289c6536e.jpg)

Item output works fine for me, with IE release 67 and TD v2.3.2.9
Energy in the bottom is in fact somewhat bored, top should work fine though.
