### ISSUE TITLE
1.10.2 Core Sample Drill not functioning Forge Server

### ISSUE THREAD

**Issue by JonoColwell** [BluSunrize/ImmersiveEngineering#2314]
Attempting to use a core sample drill on a server does not produce a sample, drill does not output anything. Misdiagnosed this as a sponge issue earlier.

Immersive Engineering: ImmersiveEngineering-0.10-61.jar
Forge: forge-1.10.2-12.18.3.2316-universal.jar

No dialogue is output to any logs regarding this.

Actions taken
https://gfycat.com/HealthyBlueGibbon 

It does write to ImmersiveEngineering-SaveData.dat
[ImmersiveEngineering-SaveData.dat.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1151662/ImmersiveEngineering-SaveData.dat.txt)

When extracting the data from the .dat file and running it through Dinnerbone's calculator you get the coordinates of where the Core Sample drill and Excavator are placed

Dump of the core sample drill
http://i.imgur.com/XEIwSrN.png
http://i.imgur.com/rdUTlDp.png

**Comment by JonoColwell** [comment]
Mod list

- #
- --
- *
- /
- ^
- \|
- ‽
- ♫
- AbyssalCraft
- Actually Additions
- Advanced Generators
- Advanced Machines
- Advanced Rocketry
- Advanced Rocketry
- Advanced Solar Panels
- AE2 Stuff
- AI Improvements
- Akashic Tome
- Alternate Terrain Generation
- AnalyzeIO
- AngelRing 2 Bauble
- AnimationAPI
- Animus
- AppleCore
- AppleSkin
- Applied Energistics 2
- Applied Energistics 2 Core
- ArchitectureCraft
- ArmorPlus
- Ars Magica 2
- asielib
- Astral Sorcery
- AutoRegLib
- Bad Wither No Cookie!
- Bagginses
- Baubles
- BD Lib
- Bed Bugs
- Better Achievements
- Better Builder's Wands
- BiblioCraft
- Biomes O' Plenty
- Blood Arsenal
- Blood Magic: Alchemical Wizardry
- Bookshelf
- Botania
- Brandon's Core
- ccl-entityhook
- Chameleon
- ChickenChunks
- Chisel
- Chisels & Bits
- CodeChicken Core
- CodeChicken Lib
- CoFH ASM
- CoFH Core
- Compact Machines 2
- Compact Solar Arrays
- Computronics
- Cooking for Blockheads
- Correlated
- Crafting Tweaks
- CraftTweaker JEI Support
- Crossroads
- Cyberware
- Cyclic
- Dark Utilities
- Decocraft
- DeepResonance
- Draconic Evolution
- DrZhark's Mo'Creatures Mod
- Dynmap
- ElecCore
- Embers
- End Metals
- Ender IO
- Ender Zoo
- EnderBags
- EnderCore
- EnderStorage
- EnderTanks
- Enderthing
- Engineers Workshop
- Environmental Tech
- ET Lunar
- Extra Bit Manipulation
- Extra Rails
- Extra Utilities 2
- Extreme Reactors
- Fast Leaf Decay
- Fishing Net Mod
- Flat Colored Blocks
- FoamFix
- FoamFixCore
- Forestry
- Forge Microblocks
- Forge Mod Loader
- Forge Multipart CBE
- Forgelin
- FTBLib
- FTBUtilities
- Funky Locomotion
- GenDustry
- Grapple Hooks
- Gravitation Suite
- Guide-API
- Immersive Engineering
- Immersive Petroleum
- Impractical Storage
- IndustrialCraft 2
- Infernal Mobs
- Inventory Tweaks
- Iron Backpacks
- Iron Chest
- JEI Bees
- JourneyMap
- JurassiCraft
- Just Enough Calculation
- Just Enough Items
- KleeSlabs
- libVulpes
- LLibrary
- Login Shield
- LunatriusCore
- MachineMuse's Modular Powersuits
- MalisisCore
- MalisisDoors
- Mantle
- MCMultiPart
- Mekanism
- MekanismGenerators
- MekanismTools
- MFR Compat: Vanilla
- Minecraft Forge
- Minecraft Multipart Plugin
- MineFactory Reloaded
- MineTweaker 3
- MmmMmmMmmMmm
- Moar Tinkers
- Mob Totems
- Mod Tweaker
- Modular ForceField System
- More Bees
- MoreDefaultOptions
- Morpheus
- Morph-o-Tool
- MrTJPCore
- MTLib
- Mystical Agriculture
- Natura
- Nether Metals
- Nether Portal Fix
- No Mob Spawning on Trees
- NoMoreRecipeConflict
- Not Enough Wands
- NotEnoughIDs
- NuclearCraft
- Nucleus
- numina
- OpenComputers
- OpenComputers (Core)
- Ore Dictionary Converter
- Ore Spawn
- p455w0rd's Library
- Pam's HarvestCraft
- Platforms
- Practical Logistics 2
- Pressure Pipes
- Progressive Automation
- ProjectRed Core
- ProjectRed Expansion
- ProjectRed Illumination
- ProjectRed integration
- ProjectRed Transmission
- ProjectRed Transportation
- Psi
- PSIonic Upgrades
- PTRModelLib
- Quark
- Railcraft
- Random Things
- Ranged Pumps
- RebornCore
- reborncore-MCMultiPart
- RebornStorage
- Redstone Arsenal
- Refined Storage
- Reliquary
- RFTools
- RFTools Control
- RFTools Dimensions
- Roguelike Dungeons
- Roots
- Router Reborn
- RouterReborn Lib
- Sanguimancy
- Scannable
- ShadowMC
- ShetiPhian-Core
- Signals
- Simple Retrogen
- Simply Jetpacks 2
- Sleeping Bag
- SonarCore
- Soul Shards - The Old Ways
- Stackie
- Steve's Carts 2
- Storage Drawers
- Substratum
- Super Circuit Maker
- TechReborn
- TESLA
- Teslafied
- The One Probe
- The Spice of Life
- TheDragonLib
- Thermal Dynamics
- Thermal Expansion
- Thermal Foundation
- Thermal Smeltery
- TickProfiler
- Tinker I/O
- Tinkers' Addons
- Tinkers Alloying Addon
- Tinkers' Construct
- Tinkers Tool Leveling
- Tomb Many Graves
- TOP Addons
- Translocator
- UniDict
- Valkyrie Lib
- Vitality
- Waila
- WanionLib
- Water Strainer
- Wireless Crafting Grid
- Wireless Crafting Terminal 2
- Woot
- XNet
- Xtones
- Zero CORE

**Comment by mindforger** [comment]
please do not post suhc walls of text, drop it to pastebin or similar and post a link
do you have sponge installed?
Samples not dropping is a known issue with sponge present!

for the excavator, please check that the cavity the excavator digs under the wheel is closed from all sindes, sometimes faling gravel or a shallow cave will make the cavity leak and the excavator will not dig then

**Comment by JonoColwell** [comment]
1. Modlist moved to pastebin.

2. Sponge was present prior to this occurring,  I was the one that posted that bug a couple days ago, this time I had the same issue without sponge installed, completely removed sponge from the server and restarted, same issue.

3. I've placed some dirt in under the excavator, it's now extracting minerals, so I'll take that segment out as resolved due to user stupidity.

Issue with Core Sample drill remains.

**Comment by JonoColwell** [comment]
Also the command is /immersiveengineering:ie mineral get. This works, I'd just prefer if the core sample drill worked, those core samples are cool.

**Comment by mindforger** [comment]
you listed "Crafting Tweaks" but not "Crafttweaker" but you have Crafttweaker JEI Compat installed

if you have Crafttweaker, try to cheat in a core sample, put it in your hand and use /MT hand or /CT hand (command has probably changed to CT) maybe something is odd with he samples iteself?!

**Comment by JonoColwell** [comment]
/mt hand with the blank core sample in hand

![image](https://user-images.githubusercontent.com/8704304/28258171-2a30287a-6b13-11e7-8670-170f46513866.png)

**Comment by mindforger** [comment]
@BluSunrize is there the slight possibility that the interact call is ran twice for client and serverside? because you drop it only when (!world.isRemote) but you always clear the sample stored! Wouldn't it be better to only remove the sample when actually beeing dropped?

**Comment by JonoColwell** [comment]
@mindforger nah mate, it just sits there, doesn't drill again.

**Comment by mindforger** [comment]
the second click was not noticable in the gyfcat , that's why i asked

**Comment by JonoColwell** [comment]
yeah it doesn't make the clicking animation for some reason.

**Comment by BluSunrize** [comment]
Can you reproduce this with just IE installed and no other mods?

**Comment by JonoColwell** [comment]
Will check tonight.

**Comment by JonoColwell** [comment]
Sorry, was wrecked for a couple of days, can confirm that this does NOT work with only Immersive Engineering installed.

**Comment by JonoColwell** [comment]
I commented but in hindsight my comment was unclear.

This can be reproduced with only Immersive engineering installed on a forge server.

**Comment by JonoColwell** [comment]
@BluSunrize

**Comment by malte0811** [comment]
Blu is on vacation for the next two weeks, so he probably isn't going to fix this until he's back. I might try to fix this (though I have far more projects than time right now, so no promises). Are there any errors in the server log when you do this?

**Comment by malte0811** [comment]
I am unable to replicate this. I tried on my normal dev server and with all mods but IE disabled, worked perfectly both times. Could you upload a server log to gist?

**Comment by JonoColwell** [comment]
I mean, I can retest, but considering that there's been no update to the 1.10.2 branch I can't see this being something that a retest will result in a success unless forge has changed something

**Comment by mindforger** [comment]
hile ingame, press and hold f3+c until the client crashes and append the crashlog ... there maybe hints whats going on in there

**Comment by malte0811** [comment]
A debug crash log probably won't help here.
In the original post you posted some dumps of the sample drill. The second one (of the tile entity) is the one that could contain useful information. Unfortunately you dumped the middle block which does not contain any information at all (except for it being the middle block). The bottom block has all the relevant information, could you post dumps of that TE before and after the second right-click? BTW, what are you using to generate those dumps?

**Comment by JonoColwell** [comment]
Will test and try to remember the command I used to get that, it's been a couple of weeks I can't remember lol.

**Comment by JonoColwell** [comment]
I managed to get it to output an error log, turns out it was Immersive engineering but I had to enable Minetweaker writing some data to the log to get that, Updating Immersive Petroleum fixed this, I feel like an idiot.
