### ISSUE TITLE
MC 1.11.2 Floodlight bugs

### ISSUE THREAD

**Issue by winnetrie83** [BluSunrize/ImmersiveEngineering#2315]
-Sometimes when you switch off the floodlight and all the light goes out it still emits lights as if it were a torch or something. You can see his on screenshot 1. I waited 2 minutes after switching off just the give it time to turn off all the lights.

![2017-07-17_16 19 36](https://user-images.githubusercontent.com/29025144/28272598-4491d10c-6b0c-11e7-9154-28390784a2d4.png)

-If you place the floodlight down and connect the power etc and place a lever to give it a redstone signal, the floodlight will turn 90 degrees to the right (clockwise) when switching the lever to on position. The light emitting from the floodlight is in the direction like it was placed down. You see this in the next screenshot.

![2017-07-17_16 19 47](https://user-images.githubusercontent.com/29025144/28272721-a54e8670-6b0c-11e7-97c1-41f44194720b.png)

I did not tested this the 1.12 version.
I also think the floodlight is too laggy. Meaning it is too slow and doesn't go smooth and makes the FPS dropping if it updates(turning light on/off or turning the floodlight)

**Comment by BluSunrize** [comment]
The performance thing is quite easy to answer: It uses fake lightsources. Minecraft's light calculation is horrible. If your PC can't handle it, don't use it. Literally nothing I can do about it.

The rotation thing on lever flipping is odd. Can you reproduce that with just IE installed? Possibly on newer versions?

**Comment by winnetrie83** [comment]
I went to 1.12 with your newest release 67. The odd rotation thing when flipping the lever seems not to be present there. I also have the feeling that the lightning goes abit faster and smoother in 1.12.
I'm not if my pc isn't good enough anymore.
I have AMD FX(tm)-8350 Eight-core with 4.00Ghz processors.
8GB DDR3 RAM 1600Mhz
NVIDIA GeForce GTX 960
And ofc SSD drives (in raid0)

**Comment by BluSunrize** [comment]
Hah, right, nvm. Not a potato PC.
Yeah I dunno. Blame Mojang I guess :/
I'm trying to do it as best as possible, placing all the blocks and then firing the update.

**Comment by winnetrie83** [comment]
In the 1.12 version i was using optifine, in 1.11.2 not. Probably using it helps a bit too.
Yeah if you compare MC lightning with other games....well you know what i mean.

**Comment by AgentA1cr** [comment]
I'm experiencing a similar issue in 1.12.2. I've tried both with and without optifine. When being rotated, floodlights behave erratically, sometimes not rotating when clicked, sometimes rotating normally, and sometimes reversing direction, all seemingly at random. Also, shift-right-clicking on the base with a hammer does not seem to invert the redstone behavior.

**Comment by AgentA1cr** [comment]
To be clear, the lighting rotates normally. It's the floodlight model that's all over the place.

**Comment by Malgior** [comment]
I'm seeing a similar issue with what agentA1cr describes. I'm using the direwolf 20 modpack and when using the floodlights the positioning is almost impossible. rotating them with the hammer works up until a point and then it all of a sudden jumps to a completely different position. providing it with a redstone signal also makes it jump 90° but the light beam doesn't follow the positioning. Sometimes it stays where it was originally pointed sometimes it completely randomly reorients. Optifine isn't installed and the pack is useing IE 0.12-75.
