### ISSUE TITLE
WHAT

### ISSUE THREAD

**Issue by xNifYT** [BluSunrize/ImmersiveEngineering#2316]
![what](https://user-images.githubusercontent.com/22347786/28277577-b07d8eb6-6b1a-11e7-833b-97b7f2504b28.png)
Ummmm.... So what mod I need?

**Comment by BluSunrize** [comment]
Well if you read fracking contribution guidelines and submitted a modlist, I might have been able to answer that.

Vague guess: Update OneProbe. And next time learn to read.

**Comment by AEnterprise** [comment]
i've seen this before, most likely you have optifine or a similar mod that is messing with things and still needs to update to forge improving the error screens on startup

**Comment by xNifYT** [comment]
I thought that developer of his own mod knows what other mods you need do have using it but apparently not. And btw i have the newest version of OneProbe. And I still don't know what mod I need.

**Comment by PrincessRTFM** [comment]
You didn't tell Blu what mods you have, so how does he know what's missing from your loadout? He's a modder, not a mind reader.

**Comment by xNifYT** [comment]
Oh, I didn't think about that, sorry...
![mods](https://user-images.githubusercontent.com/22347786/28323730-ea9ef4ee-6bd9-11e7-8705-6880427a36f0.png)

**Comment by BluSunrize** [comment]
Well, for one, IE isn't in that list at all, and two you are wrong, your OneProbe is hilariously out of date.

**Comment by xNifYT** [comment]
IE isn't there cause I wanted to at least launch the game and if there's newer version of OneProbe tell me the number of it becuase on curseforge it's newest.

**Comment by malte0811** [comment]
It might be the last release exclusive to 1.10, but it isn't the last update compatible with 1.10. [This](https://minecraft.curseforge.com/projects/the-one-probe/files/2451902) is the version you should be using. You will need CompatLayer as well since this version supports both 1.10 and 1.11.

**Comment by xNifYT** [comment]
On curseforge it says that it's a mod for 1.11.2 but it works, thx.

**Comment by BluSunrize** [comment]
No, on CurseForge it explicitly states this:
![image](http://puu.sh/wMNnV/2705b76058.png)

It's for both versions. It also says "Note! This mod works on 1.10.2 *and* 1.11.2 with the same JAR!" in big red letters on the main page.
