### ISSUE TITLE
Bottler unable to fill water bottles

### ISSUE THREAD

**Issue by Lordi91** [BluSunrize/ImmersiveEngineering#2318]
When trying to fill glass bottles with water in the bottler it goes through the motion of filling it up but the bottle stays empty - Buckets work fine

Found the issue within Raxpack2 on server to rule out a change that was made for the pack, I loaded up a single player instance of just forge and IE

Minecraft - 1.11.2
On Server Forge - 13.20.1.2393
On Single Player Forge - 13.20.1.2414
Immersive Engineering - 0.11-63

**Comment by BluSunrize** [comment]
Yeah Forge got rid of the FluidContainer registry. Glass bottles aren't actualyl valid containers anymore :/
Someone should totally write a "Universal Bottles" mod to go along with Forge's Universal Bucket.

**Comment by Lordi91** [comment]
Ahh fairenough - I have put a mod tweaker recipe into my single player instance - now to try and twist roraxs arm to put in on the server also :D

**Comment by darkshadow543** [comment]
They also no longer work with potions, worked the first time around, but after that, they did not work.
Minecraft Version: 1.12.2
Forge Version: 14.23.0.2493
IE Version: 0.12-72
BTW, what is the IE core for, it threw Curse off when I tried to upload the pack I was working on?

**Comment by malte0811** [comment]
Regarding the core: see #2503. It's part of the "new" forge coremod policy, even though we are the only ones who actually do this rather than extract the core to a separate mod and CF project (as far as we know).

**Comment by Orbital-Vagabond** [comment]
@Lordi91 Do you have the fix you mentioned using ModTweaker available anywhere?
