### ISSUE TITLE
[Suggestion] more alloys for arc furnace

### ISSUE THREAD

**Issue by winnetrie83** [BluSunrize/ImmersiveEngineering#2319]
I'm testing on 1.11.2 and i builded the arc furnace in creative to test how it works.
It seems like there is support for some alloy's, but there are still missing some.
Like bronze cannot be made in the arcfurnace, but can be made in the alloy kiln.
Slimeknight(Tinker's construct) metal requires 3 types of resouces.
It would be nice if you could add more alloy recipes to the arc furnace.
Or maybe you could add in the config (or some other file) a way people could add new alloy recipes.

**Comment by winnetrie83** [comment]
Tested on 1.12. Can't make the alloy bronze in the arc furnnace.
I used the copper and tin from forestry.

**Comment by BluSunrize** [comment]
Could you provide a picture of the Arc Furnace GUI?
In my dev environment it works just fine...

**Comment by winnetrie83** [comment]
![2017-07-17_23 12 59](https://user-images.githubusercontent.com/29025144/28290155-8de249b6-6b45-11e7-8482-823ce28bfee3.png)

I tried both ore and ingots.
I only can put them in the left side of the GUI. Both copper and tin can't be placed on the right side (the 4 slots)

**Comment by BluSunrize** [comment]
Additives need to be dusts, JEI should show this ^^

**Comment by winnetrie83** [comment]
Oh i'm sorry. I didn't think of that. Btw i always found it strange you weren't using tin or bronze in your mod. What about other alloys like slimeknight from tinkersconstruct?

**Comment by BluSunrize** [comment]
Well, Knightslime is a thing that only exists in TCon and only has a use in it as well, as such it's not in the list of stuff IE handles.
And yeah, bronze is usually a pretty typical "techmod" alloy to use, but we don't have the tin in IE to even make it. I blame Hazard =P

**Comment by ldog** [comment]
I haven't gotten around to my Arcfurnace yet in 1.12, but TE bronze out of the kiln works fine for me, and this is with IE copper (because I like the darker IE colored metals better, even if I love me some TE) and TE tin. No problems making invar either. I ditched TC (I wish someone *cough* @KingLemming *cough* would add the machinists bench & cyclic assembler back to their mod)

**Comment by KingLemming** [comment]
Bear in mind that they were removed for a reason, @ldog.

The Assembler is coming back. I'm a little iffy on the Workbench, but it'll probably make a return too.

**Comment by BrianEdmonds** [comment]
I wanted to use this to pour a building, but when I tried there were too
many gaps in the resulting concrete.  I did, however, note the effect
that OP reported.  I ended up pillaring up a hundred blocks or so,
pouring one bucket, and mining it back down.  Got a large amount of
concrete, and manually constructed the building I wanted.

**Comment by ldog** [comment]
@KingLemming Yeah, I know. At least about the assembler. Those 2 and the hand fluid pump (and I used the shit out of that too) are the only things missing from the old days now I think. Of course there is so much more now.

Sorry for the hijack everyone.
