### ISSUE TITLE
[Small bug] MC 1.12 missing textures

### ISSUE THREAD

**Issue by winnetrie83** [BluSunrize/ImmersiveEngineering#2320]
![2017-07-17_23 24 12](https://user-images.githubusercontent.com/29025144/28290601-597f18dc-6b47-11e7-8273-2fc2abce4c23.png)
It isn't that important, but can't hurt to report it, right?

**Comment by BluSunrize** [comment]
Yeah honestly dunno what causes that.
The fluid blocks are fine in world, the fluids in buckets and GUI are fine as well.
It's just the item for fluid blocks that's doing it :/
