### ISSUE TITLE
12-67 crash, ImmersivePetro related

### ISSUE THREAD

**Issue by ldog** [BluSunrize/ImmersiveEngineering#2321]
Might be on Flaxbeard's end, but anyway here's a crashlog. Was just looking at the manual, not even IP page. 
[crash-2017-07-17_17.42.31-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1154087/crash-2017-07-17_17.42.31-client.txt)

And another, it happens when closing the manual actually, reproduceable though.
[crash-2017-07-17_17.42.31-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1154088/crash-2017-07-17_17.42.31-client.txt)

**Comment by BluSunrize** [comment]
Oh, damnit. Didn't realize this would cause crashes. Didn't think anyone used my manual stuff that much .-.

Sorry @Flaxbeard, a few methods went away from static to make the manual library better when multiple mods use it. Plus the new linking features. Apologies for breaking stuff on your end with that <3

**Comment by ldog** [comment]
Are you kidding? I use it all the time, I got a memory like a sieve!
And autocrafter still no makey treated wood without bucket of creosote, unless I need to pump that tank out and back again :(

**Comment by BluSunrize** [comment]
Nono, I meant I didn't expect anyone to use the codebase for the manual.
A few methods were static before (accessible from anywhere) and I made them non static (which should allow other, non-IE, mods to use the manual library without getting conflicts). However, it looks like IP relied on one of those methods, and therefor I just blew that up for Flax. 'pologies again.

I'll look into the assembler bug tomorrow. Probably on the assembler side, not the recipes. I have a vague idea what's causing it, but I'm too tired to check now.

**Comment by winnetrie83** [comment]
I just had a crash while closing the manual (i pressed ESC). Maybe something related to this?

The game crashed whilst updating screen events
Error: java.lang.IncompatibleClassChangeError: Expected static method blusunrize.lib.manual.gui.GuiManual.getSelectedEntry()Ljava/lang/String;

Take some rest, you need it :-)

**Comment by ldog** [comment]
@winnetrie83 
Do you have Immersive Petroleum installed as well? If not then the crashlog would prolly help Blu.

**Comment by BluSunrize** [comment]
Yeah, same thing, related to that, probably.
Can you get a full log of that crash on pastebin please?

**Comment by winnetrie83** [comment]
[https://pastebin.com/4EGhjajr](url)
@ldog Jup i have it installed too. I just looked in the crashlog myself. Looks like the same crash

**Comment by ldog** [comment]
Hemp to string is still missing too, unless that was intentional. Sorry cramming it all here, but then I don't have to upload more crashlogs :P

**Comment by BluSunrize** [comment]
@winnetrie83 Yeah same issue, Flax will have to fix that on his side.

@ldog Good to know, doesn't really warrant another issue xD
