### ISSUE TITLE
Alloy Kiln not respecting config

### ISSUE THREAD

**Issue by 3DLudi** [BluSunrize/ImmersiveEngineering#2323]
I recently found that the Alloy Kiln is not respecting the config setting for preferred Mod IDs.  Currently I have it set for Thermal Foundation.  All the other machines/ processes look fine but the Alloy Kiln is insistent on creating IE constantan ingots from copper and nickel dusts.

**Comment by BluSunrize** [comment]
Yeah, the Arc Furnace does that too. The config is for things that aren't from IE.
Where IE is available, I use it.

Plus IE constantantan looks way better anyway =P

**Comment by 3DLudi** [comment]
I agree it does look awesome.

The Arc Furnace is acting as I had hoped though.  I just checked and the only things it can process from IE is HOP Graphite and Uranium.  Everything else is Thermal Foundation.  Since you said it was not the config setting perhaps it was UniDict.

This is not surprising though.  Issues always crop up when multiple tech mods add similar ores/ metals.  I am actually surprised that with as many mods/ machines that I have only the Kiln is misbehaving.  I will close this off as I misunderstood the config and  I think I can solve it myself as I can make alloys with Tinkers and it should be trivial to disable the Kiln.

**Comment by bookerthegeek** [comment]
@3DLudi let the author of unidict know, so he can add the kiln.
