### ISSUE TITLE
Immersive Engineering Crash PART II

### ISSUE THREAD

**Issue by Amkdux** [BluSunrize/ImmersiveEngineering#2324]
Hey. So about half a month ago (maybe) I was having problems with SkyFactory not being able to load if I use Immersive Engineering. However, after many times using SkyFactory without Immersive Engineering I decided I would give Immersive Engineering a try again. **THIS WAS AFTER I CHANGED THE SPLASH.PROPERTIES TO FALSE** <<That was the only thing I changed (required for me to be able to even play SkyFactory)

Then BAM! It works. Literally nothing changed, but I don't even know what was the problem? Was it the Splash.properties messing with my INTEL HD Graphics? Anyways, thanks.

**Comment by Rambonata** [comment]
I've been having the same issue with a few different packs with IE. Thank you for finding a working workaround!
