### ISSUE TITLE
Crashing while loading

### ISSUE THREAD

**Issue by Chenjox** [BluSunrize/ImmersiveEngineering#2326]
Every time I try to load Minecraft with IE on, it freezes and get the "not responding" message.
It even happens when I load IE alone.
It freezes while loading "Item Renderer" or "Block Renderer"
It didn't generate a crashlog, so I copied latest.log

https://pastebin.com/BEB9yjSn

Thanking you in advance
Chen

**Comment by BluSunrize** [comment]
What operating sytem are you using? Could you provide the entire log please?

**Comment by Chenjox** [comment]
Windows 7 Ultimate,
Java 8
Latest Release of Forge.
Minecraft 1.12, IE latest version
This is the entire latest.log

**Comment by Amkdux** [comment]
Chen, could you try going to your **splash.properties** and change:

**enabled=true**
to
**enabled=false**

**Comment by Chenjox** [comment]
I tried it already. Without any success.
Does the mod conflict with anything? Like mercurius?
Thank you in advance

Chen

**Comment by BluSunrize** [comment]
Okay, so could you then provide a full log when loading just IE and nothing else?

**Comment by Chenjox** [comment]
Here you are:
https://pastebin.com/QCE0zR9e

Thank you for wrapping your head around this.
Chen

**Comment by BluSunrize** [comment]
There's...basically nothing in that log that indicates error. 
What's your system stats and how much memory are you allocating?

**Comment by Chenjox** [comment]
Thank you for your time.
I tried Amkdux method again. After 3 tries, i got it to work.

Thank you so much for your help.
Chen
