### ISSUE TITLE
MC 1.12 Assembler not working

### ISSUE THREAD

**Issue by purestone9** [BluSunrize/ImmersiveEngineering#2327]
I have the assembler assembled and powered, and its not crafting.
I also have conveyor belts going into the input and out of the out put.
Playing with the Skyblock Godless pack.

**Comment by BluSunrize** [comment]
Could you please provide pictures of your setup and the Assembler's GUI?

**Comment by purestone9** [comment]
![2017-07-19_16 20 39](https://user-images.githubusercontent.com/29181158/28392226-43599386-6c9e-11e7-98b0-476aea6e00a6.png)
![Uploading 2017-07-19_16.20.25.png…]()
![Uploading 2017-07-19_16.20.35.png…]()

**Comment by purestone9** [comment]
![2017-07-19_16 23 30](https://user-images.githubusercontent.com/29181158/28392315-9ffe00e0-6c9e-11e7-931b-269f77f22cb9.png)

**Comment by purestone9** [comment]
Its specifically not working with Mystical Agriculture

**Comment by BluSunrize** [comment]
Do other recipes work?

**Comment by purestone9** [comment]
Other recipes work, as long as they are not from mystical agriculture.
I think it might be that Mystical agriculture essences are separated by Code name and Unlocolized Name

**Comment by purestone9** [comment]
![2017-07-20_12 31 03](https://user-images.githubusercontent.com/29181158/28433041-8747f75a-6d47-11e7-8c11-957d6d3b26fb.png)

**Comment by purestone9** [comment]
![2017-07-20_12 31 05](https://user-images.githubusercontent.com/29181158/28433062-9a72132e-6d47-11e7-9e7c-4443cab05e88.png)

**Comment by BluSunrize** [comment]
It's probably more a problem with a custom IRecipe. I'll look into it.

**Comment by purestone9** [comment]
ok, thank you
