### ISSUE TITLE
Minecraft v1.12 immersive engineering v67 Refinery not converting fluids

### ISSUE THREAD

**Issue by ag47phoenix** [BluSunrize/ImmersiveEngineering#2328]
My setup is very simple 
![2017-07-19_18 32 11](https://user-images.githubusercontent.com/30286382/28358043-c56487c0-6cb0-11e7-94b3-d9ba8e206c8a.png) I'm not very sure what's going on but the refinery is not producing anything 
![2017-07-19_18 32 23](https://user-images.githubusercontent.com/30286382/28358094-e76f3978-6cb0-11e7-8f24-56d9811f55b6.png) There's power & plant oil but no production so i'm assuming this is a bug? I've checked that the redstone control is not inverted, i also can not put buckets in the refinery after there is plant oil in the refinery (can still use pipes)
Oh and heres the mods i am using atm
![capture](https://user-images.githubusercontent.com/30286382/28358447-3e9c4f14-6cb2-11e7-8e0f-a5bcb519bd73.PNG) hope someone can help

**Comment by BluSunrize** [comment]
There's no ethanol in your refinery. To make Biodiesel you need PlantOil *and* Ethanol.

**Comment by ag47phoenix** [comment]
Oh my god so i thought that plant oil turned into ethanol than ethanol into biodiesel i was wrong thanks :D
