### ISSUE TITLE
What would cuase the water wheel to be invisible?

### ISSUE THREAD

**Issue by eslachance** [BluSunrize/ImmersiveEngineering#233]
I don't know what tcould be causing this, I added IE and a couple other mods to the Direwolf20 pack on Curse. This is what I get when I add a water wheel to the world: 
![2015-07-18_15 17 10](https://cloud.githubusercontent.com/assets/643344/8763230/050feacc-2d61-11e5-84e8-842cf942cdae.png)

It's still there and I assume functional. The full bounding boxes show, too.

**Comment by BluSunrize** [comment]
Already fixed, get the latest version.

**Comment by eslachance** [comment]
Awww sorry when I added it in Curse it didn't get the latest automatically. Weird. Sorry!
