### ISSUE TITLE
0.11-63: Some crafting recipes use uncraftable vacuum tubes

### ISSUE THREAD

**Issue by Branjoman** [BluSunrize/ImmersiveEngineering#2330]
Some recipes, such as the garden cloche, apparently now use the reagent vacuum tubes, which have no crafting recipe (at least, none that is displayed by JEI)

**Comment by BluSunrize** [comment]
They...should have a recipe. They're made in the workbench.

**Comment by BluSunrize** [comment]
Closing this due to lack of further detail/proof
