### ISSUE TITLE
1.12 immersive engineering has broken recipys

### ISSUE THREAD

**Issue by tyler489** [BluSunrize/ImmersiveEngineering#2331]
For sure insulated glass for hv relays and wire plate moulds donot accept the recipy. I will look through the other plates in a bit will add pictures of recipys in a bit. Also crafting any plate with wire cutters seems to only produce copper wires..i will add version when i get home

**Comment by BluSunrize** [comment]
Closing this due to lack of version number, pictures and modlist. Will consider reopening if those are provided.

**Comment by tyler489** [comment]
https://gyazo.com/450341d4e00f9b0ab8c8415d30fb4322 
https://gyazo.com/1fd3a0de962b829ee3fa5720f3b9307c version 66 in 1.12 Modlist can be found here https://minecraft.curseforge.com/projects/beyond-the-new-frontier/files/2451325

https://gyazo.com/e3195f32824144ad92ca910302f93730
https://gyazo.com/d80fb17465505d22d7f0519f2064968b
sorry i was working and couldnt get this sooner @BluSunrize

**Comment by BluSunrize** [comment]
The copper wire thing is fixed (please test on v67)
I'll look into the mold and glass problems.

**Comment by BluSunrize** [comment]
Both the glass recipe and the mold are working fine for me.
@tyler489 please test this again on IE version 67 (or later if available) and Forge version 14.21.1.2404 or later.

**Comment by BluSunrize** [comment]
I'll close this due to lack of response.
Poke me if issue persists.
