### ISSUE TITLE
[1.10.2] Creosote Oil is pink, and I cant use it

### ISSUE THREAD

**Issue by NerdCraft** [BluSunrize/ImmersiveEngineering#2332]
![2017-07-19_21 07 14](https://user-images.githubusercontent.com/13489837/28395137-501f0d24-6cc8-11e7-9b74-32cd322ca0c3.png)
![2017-07-19_21 22 21](https://user-images.githubusercontent.com/13489837/28395142-5ed092ca-6cc8-11e7-8278-216a55faf24a.png)

forge: 1.10.2-12.18.3.2316
immersive: 0.10-61

maybe this is a conflict with railcraft?

**Comment by BluSunrize** [comment]
Somewhat. You had Railcraft in the world before installing, I presume.
To fix this, open the level.dat file with an NBT editor and delete the creosote entry from the default fluid list.

**Comment by NerdCraft** [comment]
It worked, thanks :-)
