### ISSUE TITLE
[1.12 - v0.12-67] Probe Connector rendering

### ISSUE THREAD

**Issue by VallenFrostweaver** [BluSunrize/ImmersiveEngineering#2333]
As shown below. when placing a Probe Connector and making connections it randomly disappears completely or the transparent glass texture does. Similar to the render issues of the charging station in the past.
![ie redstone probe connector](https://user-images.githubusercontent.com/13642054/28413003-e0ba2c36-6d3d-11e7-8c0f-a2a493af2b21.png)

**Comment by BluSunrize** [comment]
Yeah it's a stupid thing with some renderpasses not firing some time. I'm fairly convinced it's a Forge/Vanilla issue and I've never really found reason for its occurrence, so I found myself unable to guard against it.
Render should pop back in on the next chunk update though (placing a block or similar)

**Comment by ldog** [comment]
Oh, yeah I'm so used to this happening (especially with the tanks and silos) that I didn't even think to mention it.

**Comment by BluSunrize** [comment]
I'll close this, because like the charging station, not much I can do :/
