### ISSUE TITLE
[1.12 - v0.12-67] Faraday armor no longer following player movements with tools

### ISSUE THREAD

**Issue by VallenFrostweaver** [BluSunrize/ImmersiveEngineering#2334]
Here's 4 images of the arms sticking out of the faraday suit. Other items seem fine like swords/axes/picks, etc.
![ie armor render](https://user-images.githubusercontent.com/13642054/28413394-37493a1e-6d3f-11e7-8b15-bc94042274ba.png)

**Comment by BluSunrize** [comment]
Yep, I know.

It'd happen for vanilla armors anyway, and I have no way to fix it, so I didn't really think to do it for the Faraday one. I figured to keep it inline with vanilla I'd keep broken as well.

Problem with it is that the fancy stuff I do with player arms for revolver, etc. doesn't translate to armor and I have no way to make it except for either coremodding (which I don't want to) or introducing a sophisticated Arm-Positioning-System to Forge (which I lack expertise and time for).
I talked to fry about such a posing system being added to it eventually but currently it's not on schedule.
Sorry :/

**Comment by VallenFrostweaver** [comment]
Ah. I only just read your update notes from v0.12-65.  It seems Vazkii had this same issue for Botania if I recall. Really sucks for armor mods. :/

**Comment by BluSunrize** [comment]
It really bugs me as well, but I can't even get a Forge Environment set up to *attempt* to add a posing system.

I'll look abouts. Maybe I can sneak a fix in somehow, although I really don't want an IE core mod if I can avoid it.

Wonder how Vazkii does it....

**Comment by VallenFrostweaver** [comment]
He didn't last I knew. If you wear Botania armor and use a Quark emote you wave your arms about without armor movement. He said it was too much effort and closed the issue. :/

**Comment by BluSunrize** [comment]
I fixed this with very hacky ASM. Probably unhealthy.
Test build can be found here:
http://teamacronymcoders.com:8080/job/ImmersiveEngineering/188/
