### ISSUE TITLE
[1.12 - v0.12-67] Shader removes revolver handle texture

### ISSUE THREAD

**Issue by VallenFrostweaver** [BluSunrize/ImmersiveEngineering#2335]
Lusus Naturae shader to be exact:
![ie shader 1](https://user-images.githubusercontent.com/13642054/28416722-20aa1342-6d4d-11e7-8278-f189ff2e4346.png)
![ie shader 2](https://user-images.githubusercontent.com/13642054/28416724-21f5adf6-6d4d-11e7-9170-a10e425692a0.png)
EDIT: More shaders have this effect than the one listed here.

**Comment by BluSunrize** [comment]
And it's such a nice shader too...

Yeah, caused by me renaming a part of the model when I added the animations. Forgot to change the parts name in the shader. Pretty easy fix though.

**Comment by VallenFrostweaver** [comment]
In case you missed my end edit, it's more than the one shader sadly. Thanks!

**Comment by BluSunrize** [comment]
Yeha it's a general fix ^^
