### ISSUE TITLE
[1.12 - v0.12-67] Gunpowder made 2 ways but one 1 works?

### ISSUE THREAD

**Issue by VallenFrostweaver** [BluSunrize/ImmersiveEngineering#2336]
Using JEI I can see 2 recipes for making gunpowder as seen here. The cheaper recipe doesn't work at all but the more expensive one does. Perhaps an extra recipe needs removal?
![sulfur](https://user-images.githubusercontent.com/13642054/28417481-347614d6-6d50-11e7-97f1-12163f108b9b.png)

**Comment by BluSunrize** [comment]
I swear Vallen, you make for like 50% of my reported issues =P
That second recipe is supposed to use charcoal dust and disable itself if none exists. 
What's your modlist?

**Comment by VallenFrostweaver** [comment]
I can stop if you like but I figure you want to know this stuff rather than let it go. :P
List: IE, I.Petroleum, JEI, TOP, JourneyMap
