### ISSUE TITLE
[1.12 - v0.12-67] Heavy Plated Shield occupies 2 spots sometimes

### ISSUE THREAD

**Issue by VallenFrostweaver** [BluSunrize/ImmersiveEngineering#2337]
To reproduce, have 1 HPShield. Have it upgraded with the magnetic glove. Double tap 'S' to equip shield. Fill inventory with stuff (I used vanilla shields) and the slot that the HPShield was in will not fill unless you press 'F' to switch hands or unless you try to place something in the spot of your inventory where the HPShield was before equipping (then the HPShield will appear under your cursor like you are moving it).

**Comment by BluSunrize** [comment]
Hmm, quite possibly client desync...

**Comment by VallenFrostweaver** [comment]
Happens consistently and every time as an FYI,

**Comment by BluSunrize** [comment]
Yeah I already figured out why and fixed it, just not pushed.
