### ISSUE TITLE
Typo in Error logging for TileEntityImmersiveConnectable

### ISSUE THREAD

**Issue by CanisUnbounded** [BluSunrize/ImmersiveEngineering#2339]
Not a very important bug but thought I'd report it anyway. Please ignore if you don't care. 
Version 0.12-67 as of #2063 
Modlist: Not relevant. 

blusunrize.immersiveengineering.api.energy.wires.TileEntityImmersiveConnectable has a typo in the IELogger.error() at line 172. Should is misspelled as "shoudl" .

**Comment by BluSunrize** [comment]
Pfft, fair enough.
Tbh, I don't think I've ever seen that error message thrown anyway, but it's been there for a *loooong* time

**Comment by CanisUnbounded** [comment]
Looks like its been there since initial 1.8.9 commit from May 2016. So I'm guessing its not very important. Just found it when reading.
