### ISSUE TITLE
Industrial squeezer block creative issue

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#234]
Action: breaking an 'Industrial squeezer' block via punching while in creative mode
Expected result: Block destroyed, no residual item drops
Actual result: Block 'mined', dropping itself as item

When breaking an industrial squeezer block in creative mode, it drops itself as an item. This is unexpected as in creative mode it is expected the block is destroyed, not  mined.

So far i have not found other blocks from IE to show the same behavior unless breaking a formed multi-block.

**Comment by BluSunrize** [comment]
That would be because the squeezer blocks are already multiblock tiles, just not formed. and I cannot detect whether the player is in creative in the method used to break and drop the block. So: Not fixable.
Not like it's a big issue either.
