### ISSUE TITLE
[1.12 - v0.12-67] Heavy Plated Shield "flaps" while recharging extras & extras don't work on some entities.

### ISSUE THREAD

**Issue by VallenFrostweaver** [BluSunrize/ImmersiveEngineering#2340]
When being attacked by an entity in melee the shield will "flap" back and forth between the non-used spot on your arm to the in-use spot in front of you while blocking. To reproduce, equip shock emitters or flash bulb or both & be attacked by an entity in melee. 

Silverfish, SLimes, Endermites, Spiders, & Cave Spiders are not effected by the Flashbulb or Shock Emitters.

**Comment by BluSunrize** [comment]
There we go, that clears *some* stuff =P

I did forget about stuff not being affected, but I think I know why. All those creates have an attackstrength of under 3 which doesn't damage the shield and as such doesn't trigger retaliation.
What do you think, should it still trigger but not damage I guess?
