### ISSUE TITLE
Following links in manual can lock pages

### ISSUE THREAD

**Issue by longbeast** [BluSunrize/ImmersiveEngineering#2342]
Open a page in the manual with a recipe, e.g. the page for the mining drill. Click on one of the components to find the recipe for that, e.g. follow link to steel mechanical component, then try to return to the mining drill page.

The back button doesn't work to return to the first page, and if you hit escape to get to the main menu / contents page, clicking on the mining drill page just takes you to the page for mechanical components instead.

Following any link seems to leave you unable to visit the page you just left. Quitting the game entirely and restarting will reset the manual, but nothing else seems to unlock pages once you've done this.

**Comment by BluSunrize** [comment]
Try rightclicking to go back to the drill page.

Will look into the back button not working though, thanks for the report.

**Comment by longbeast** [comment]
Ah yes! Right clicking to go back does still work, and doing that unlocks whatever was preventing us from returning to the contents page and returning to the original page that way.

**Comment by trilexcom** [comment]
we are getting the same things on our pack here is the pastebin https://pastebin.com/7KnN0tXX

**Comment by BluSunrize** [comment]
And there's the fix.

Next release patches this, until then just use rightclick.
