### ISSUE TITLE
Immersive book / manual crashes from time to time [1.12]

### ISSUE THREAD

**Issue by DietmarKrause** [BluSunrize/ImmersiveEngineering#2343]
crashlog: https://pastebin.com/1GMLpQ1V
used in ATM3 pack. Opening at first wolks. It crashed twice , first i read the changelog and clicked on the little arroy in the ipper lift corner, Second time i read the text about the (chenged) windmill and tried to close the book by pressing escape.

**Comment by VallenFrostweaver** [comment]
This is not IE, this is Immersive Petroleum and has been resolved. Update your IPetroleum version to fix.  Please close the issue once you have resolved.

**Comment by BluSunrize** [comment]
Yeah I also already handled this before. Search function yo.
