### ISSUE TITLE
Config Request

### ISSUE THREAD

**Issue by Medusalem** [BluSunrize/ImmersiveEngineering#2345]
What i would like to see is a config option which allows me to alter the Amount of Rf needed per Tick by the garden cloche and/or how fast the Plants are growing.

This is mostly ment to be a config to be used in Modpacks to get the chance to make the Usefullness of Different ways of Automated Plant Harvesting the Same.

Many other Harvesting Methodes with the same Price are less efficent and i would like to get the Chance to make them Usefull in the same way.

Also a way to add in custom fertilizers to be used with the Garden Cloche would be a neat thing.
But that would be meant to give the garden cloche a way to stand up against different types of Growth accelerators.

**Comment by BluSunrize** [comment]
In the config, look for "belljar_consumption", that's the powerdraw of the cloche.
There's also options for amount of fluid required and duration of a fertilizer cycle.

That covers some of the issue I think?

Now on custom fertilizers: It's totally possible, I have an API for it. I don't have a config for it however, is that we don't have an easy way to deserialize maps (string -> float) in the config, so I'd have to parse it myself, and also the API allows that value to change, based on plants and stuff, so it wouldn't allow for any specific information.
What item specifically were you thinking of adding?

**Comment by bookerthegeek** [comment]
Off the top of my head (not on game, these might already work)
- IC2 fertilizer
- Forestry fertilizer
- Better with mods dung

**Comment by BluSunrize** [comment]
Forestry already works.

**Comment by charlesbevans** [comment]
Don't forget hatchery's chicken manure that can be made into liquid fertilizer.
Maybe a config list of allowed fertilizers?

**Comment by BluSunrize** [comment]
>_>

> I don't have a config for it however, is that we don't have an easy way to deserialize maps (string -> float) in the config, so I'd have to parse it myself, and also the API allows that value to change, based on plants and stuff, so it wouldn't allow for any specific information.

**Comment by charlesbevans** [comment]
Just a end-of-day pitch for the Hatchery fertilizer and my mind kept going. I got hung up thinking about what was getting mapped to what and forgot the second part.
