### ISSUE TITLE
[1.12] Closing engineer's manual causes CTD

### ISSUE THREAD

**Issue by Whiskey-Sunshine** [BluSunrize/ImmersiveEngineering#2346]
Updated from 0.12-66 to 0.12-67 to fix the missing hammer + ingot to metal plate recipes, and now closing the manual causes an immediate exception and crashes. Opening the manual causes no problems, nor does browsing through pages.

Here's the last portion of the error log starting shortly before the crash: https://pastebin.com/xZxABMUd

Forge version forge1.12-14.21.1.2415
[Modlist](https://pastebin.com/XTwRaDEN)

Edit: Wanted to make sure it wasn't Optifine again, as it has been a culprit more often than I would like. Removed Optifine from mod list, and the same crash occurred.

**Comment by BluSunrize** [comment]
Update Immersive Petroleum.

**Comment by Whiskey-Sunshine** [comment]
I feel dumb now. Thank you.
