### ISSUE TITLE
[1.11.2] Fluid Router - Loops of death

### ISSUE THREAD

**Issue by Terpo** [BluSunrize/ImmersiveEngineering#2347]
Great name for an issue, I know! 

1.11.2
Forge 2386
ImmersiveEngineering-0.11-63.jar

ok, just was playing on my server and did the DAU thing (german ITers should know that):
Three fluid routers next to each other with filters on top and bottom.

Crashlog: https://gist.github.com/Terpo/d70c3b7a324697c05b49925712bc372b 
got some more, but error was the same

How to loop to death: https://youtu.be/BQ59Gfv309k

After that crash the world is broken until you use the "remove TE thing" from the forge.cfg

Its a corner case problem and it is easy to solve for players when they know how routers work. Only plug one pipe and then route liquids from router to the next router. If you don't know about it, your world breaks^^.

**Comment by BluSunrize** [comment]
Why the fuck would you ever even try that?
Why intentionally create a feedback loop? That's a really dumb idea.

**Comment by Terpo** [comment]
I did it not intentional... That was just normal playing on the server and did not even think about creating a loop. My first ideas of what I did come after the world was broken :)

**Comment by BluSunrize** [comment]
Sorry for getting irritated at this one. I should have phrased that nicer. My bad, I apologize.
I've found a fix, funnily enough the same I used or the Item Router back in the day.
