### ISSUE TITLE
[1.12] IE and Tinker's Construct Bad Dependency

### ISSUE THREAD

**Issue by nightcipher** [BluSunrize/ImmersiveEngineering#2349]
Forge version: 14.12.1.2420
IE version: 0.12-68
Tinker's Construct version: 1.12-2.7.1.9 (latest)

Expected behavior: Loading a Forge pack with Immersive Engineering and Tinker's Construct will go to title screen.

Actual behavior: Partway through the mod loading process, Immersive Engineering throws an error that it needs tconstruct version 1.12-2.8 or above. No such version exists publicly. 

Log file: 
[latest.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1167728/latest.txt)

Downgrading to IE version 0.12-67 resolves the issue.

**Comment by JasonKillsUs** [comment]
yep...

**Comment by KnightMiner** [comment]
Yeah, sorry about this one. When first updating to 1.12 the version was set to 2.8.0, but it was not supposed to be 2.8.0 until a full release was ready so it got switched back to 2.7.1. Apparently a few builds still exist as 2.8.0.

All your code looks right for the latest build though, so it should just be the wrong dependency

**Comment by BluSunrize** [comment]
Yeah that ones on me too.
Someone told me the version number was reverted, and I forgot to update my dependeny :/

**Comment by cursinorock** [comment]
So sorry I'm noob, but what do I do? I just wait to get an update?

**Comment by nightcipher** [comment]
@cursinorock Issue is resolved as per Immersive Engineering version 0.12 - 69. Update IE.

**Comment by cursinorock** [comment]
<3
