### ISSUE TITLE
[1.12] Tessellation bug involving IE pipes.

### ISSUE THREAD

**Issue by elucent** [BluSunrize/ImmersiveEngineering#2350]
https://gist.github.com/elucent/cb61eaeee59ccc47cf7202036907ed2b

One of my users reported this. Using IE 0.12-0.67 for 1.12. They immediately crash whenever the pipe appears in the world.

**Comment by BluSunrize** [comment]
DO you know what it is connected to? Because whatever it is, it returns true on hasCapability and then null on getCapability. That's against Forge convention and thus I don't nullcheck it :V

**Comment by Paspartout** [comment]
It's a Rustic Brewing Barrel and the [getCapability](https://github.com/the-realest-stu/Rustic/blob/master/src/main/java/rustic/common/tileentity/TileEntityBrewingBarrel.java#L232) of it indeed looks wrong. May be related to this [issue](https://github.com/the-realest-stu/Rustic/issues/56).

**Comment by BluSunrize** [comment]
Yes quite so.
That capability handling is broken and needs to be fixed >_>

**Comment by BluSunrize** [comment]
Not related to that specific issue your linked though, since it's not dealign with capability stuff.

**Comment by BluSunrize** [comment]
I've filed an issue on their tracker:
https://github.com/the-realest-stu/Rustic/issues/61

Closing this one.
