### ISSUE TITLE
Garden Cloche Duping Mystical Agriculture seeds

### ISSUE THREAD

**Issue by Rustynator1** [BluSunrize/ImmersiveEngineering#2352]
hey when a myst agricraft seed is being harvested you recieve both essence and another seed, you should only get essence back otherwise this will be too op.

**Comment by BluSunrize** [comment]
Version numbers, mate? Read the contribution guidelines.

**Comment by Rustynator1** [comment]
sf3 3.0.13 immersive engineering 0.10-60

**Comment by BluSunrize** [comment]
Yeah it's fixed for new 1.12 versions, but I'm not gonna backport it.
Just disable MA compat in IE's config.
