### ISSUE TITLE
In version 1.12 immersive asks for a version of tinkers that has not been released yet

### ISSUE THREAD

**Issue by cursinorock** [BluSunrize/ImmersiveEngineering#2353]
In version 1.12 immersive asks for a version of tinkers that has not been released yet

**Comment by cursinorock** [comment]
![capturar](https://user-images.githubusercontent.com/24946430/28501460-7a74c536-6fb2-11e7-9e35-0f4ef233eb89.PNG)

**Comment by KnightMiner** [comment]
Duplicate of #2349.
