### ISSUE TITLE
[1.12] Assembler not auto-outputting crafts

### ISSUE THREAD

**Issue by Drytchnath** [BluSunrize/ImmersiveEngineering#2355]
Tested in creative and in my own ATM 3 world. Assembler will accept fluids, power and has a lever switched to On. Recipe for concrete and Treated Wood is valid but will not pull items from internal inventory. Acts like a normal crafting bench, if I put a bucket of creosote oil into the internal storage it makes 8 treated wood planks but I have to manually pull them out of the machine. If I put another bucket in it makes another 8 per the normal recipe but will not pull from the fluid tank or auto-output items.

Was thinking it may have had something to do with creosote being from Thermal Foundation in earlier versions but making a fresh assembler in creative produced the same results.

Same with the slag concrete recipe. Broke and reassembled multi-block but same results.

**Comment by BluSunrize** [comment]
Version Numbers missing.

**Comment by Drytchnath** [comment]
IE ver. 0.12-67, Forge 2420.
Modpack: ATM 3 v2.3

Tried updating IE manually to 12-68 but it broke other things in the modpack so rolled it back to 12-67.
Only IE add-on I'm using is Immersive Petroleum v. 1.12-1.0.12

I think that's all of it?

**Comment by Drytchnath** [comment]
Just realized 12-69 was released so I installed that and it resolved my issues. Sorry for the inconvenience.

**Comment by BluSunrize** [comment]
Yeah, that's why I need to ask for those numbers =P
