### ISSUE TITLE
[Suggestion] Milking machine

### ISSUE THREAD

**Issue by charlesbevans** [BluSunrize/ImmersiveEngineering#2357]
Any chance of getting a milking machine?
Maybe a 2x1 stall that the cow has to stand on or a small multiblock. Alternatively, a cloche/cow in a jar combo. Sometimes you just have to milk mooshrooms or moofluids.

**Comment by BluSunrize** [comment]
Except that neither Minecraft nor forge actually feature Milk or Mushroomsoup as a fluid.
So the milking machine would exist purely in compat to other mods that add that fluid...

**Comment by charlesbevans** [comment]
True, it could use buckets or bowls, but I think most people use mods together. I think that farm stuff (milking, shearing, logging, maybe feeding and an abattoir) are all that are missing from making IE a full service basic tech mod. Adding these features with another mod usually means another tech mod that overlaps IE or even makes it functionally redundant. (None of them top IE's cool factor.)

**Comment by BluSunrize** [comment]
I generally don't care much for overlap. I know plenty tech mods beat IE in efficiency, but I don't balance against them.
I don't however, add features that aren't used within IE itself. Everything in IE has a purpose in relation to the mod itself or vanilla. A milk fluid wouldn't really have application, I'd think it a bit our of place for IE, tbh. Farming is definitely something that could use work, I agree, currently the closest thing to farming is chucking cows in a crusher.
I'll keep it in the back of my mind for possible future implementations, but it's not an urgent feature.

**Comment by charlesbevans** [comment]
I understand. It's a fair assessment and I appreciate your taking the time to consider it. Maybe somebody will do an Immersive Farming addon. 😃
