### ISSUE TITLE
[1.12] Wires lose connection on Chunk-reload. (Thermal Dynamics issue?)

### ISSUE THREAD

**Issue by Sixer601** [BluSunrize/ImmersiveEngineering#2359]
Disclaimer: I understand this is still a shaky ride switching from 1.7.10 through 1.12, and I applaud everyone who has been working on this transition. As a player who has yet to take a hiatus in their 5th year playing (since 2012), it is very nice to see that people are working towards improving the experience. 
Now onto the issues:
My main issue that i've been having is the fact that my Low Voltage Wires going from my Water Wheel into various machines (thermal Dynamics conduits to the Thermal and Forestry Machines), and whenever a chunk gets Unloaded/Loaded/Reloaded, the connections are still visible, there are no dropped items, however the power ceases to go from point A to point B. It baffles me, and I tried using a breaker switch to reset the connections, but it hasn't been reliable enough. Next issue I have is the fact that I cannot place Infernium seeds (any teir) in garden Cloches. This causes an issue due to the fact that it is a very sought after resource for producing seeds of other crops. 

Thank you for reading/listening to my concerns. High Regards, Sixer601

**Comment by BluSunrize** [comment]
Please read the contribution guidelines and provide version numbers, mod list, etc. as requested there.

**Comment by Sixer601** [comment]
Where would I find those guidelines?

**Comment by BluSunrize** [comment]
*facepalm*
In the big yellow bar when you open a new issue >______<
![image](http://puu.sh/wSsTu/04a600749e.png)

Here, have a direct link:
https://github.com/BluSunrize/ImmersiveEngineering/blob/master/CONTRIBUTING.md

**Comment by Sixer601** [comment]
The mod list is (mod names on left, mod versions on the right):
Additional Banners AdditionalBanners-1.12-1.5.38
AppleSkin AppleSkin-mc1.12-1.0.7
Aroma1997Core Aroma1997Core-1.12-1.3.0.0.b94
Aroma1997s Dimensional World Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37
AutoRegLib AutoRegLib-1.3-13
BetterFps BetterFps-1.4.6
Block Armor BlockArmor-1.12-2.4.6
Chisel Chisel-MC1.12-0.0.13.14
Classic Combat ClassicCombat-1.12-1.0.0
Clay WorldGen ClayWorldGen-1.1.0-1.12.0
CodeChicken Lib 1.8.+ CodeChickenLib-1.12-3.1.1.288-universal
CoFH Core CoFHCore-1.12-1.0.0.6-universal
CoFH World CoFHWorld-1.12-1.0.0.6-universal
ConnectedTexturesMod CTM-MC1.12-0.2.0.3
CraftTweaker CraftTweaker2-1.12-4.0.1
Creeper Confetti creeperconfetti-1.4.1
Cucumber cucumber[1.12]-1.0.0
Customized Dungeon Loot Customized Dungeon Loot (v.1.0.1)
Ender Compass EnderCompass-1.12-1.2.6.1
Ender Storage 1.8.+ EnderStorage-1.12-2.4.0.119-universal
Exchangers Exchangers-1.12-2.2
Fancy Block Particles FancyBlockParticles-1.12-2.2.2
Flat Colored Blocks flatcoloredblocks-mc1.12-6.3
Forestry forestry_1.12-5.4.3.137
Hammer Core HammerCore-1.12-1.9.3.6
Hwyla Hwyla-1.8.19-B33_1.12
Immersive Engineering ImmersiveEngineering-0.1.12-69
Immersive Petroleum immersivepetroleum-1.12-1.0.12
Industrial Craft industrialcraft-2-2.8.7-ex112
Inventory Tweaks InventoryTweaks-1.63+beta.107
JourneyMap journeymap-1.12-5.4.9
Just a Few Fish JustAFewFish-1.7_for_1.12
JustEnoughItems(JEI) jei_1.12-4.7.2.77
Just Enough Resources (JER) JustEnoughResources-1.12-0.8.3.23
Mantle Mantle-1.12-1.3.0.15
Metamorph metamorph-1.1.3-1.12
Morph-o-Tool Morph-o-Tool-1.2-15
Morpheus Morpheus-1.12-3.3.2
Mouse Tweaks MouseTweaks-2.8-mc1.12
MTLib MTLib-3.0.0
Mystical Agriculture Mysticcalagriculture[1.12]-1.6.2
Natura Natura-1.12-4.3.0.10
OpenBlocks Elevator ElevatorMod-1.12-1.3.4
Pam's HarvestCraft Pam's HarvestCraft 1.12 Alpha - RECIPES ARE BROKEN
Quick Leaf Decay QuickLeafDecay-MC1.12-1.2.3
Rainbow Oak Trees RainbowOaks-1.12-1.0.4-beta2
Redstone Arsenal RedstoneArsenal-1.12-2.3.3.11-universal
Redstone Flux RedstoneFlux-1.12-2.0.1.2-universal
Refined Storage refinedstorage-1.5.13
Roguelike Dungeons RoguelikeDungeons-1.12-1.7.10
Simple Quarry SimpleQuarry-1.12-1.0.7
SimpleHarvest Harvest-1.12-1.2.4-16
Soul Shaards: The Old Ways SoulShards-TOW-1.12-2.7.3-52
Thermal Cultivation ThermalCultivation-1.12-0.1.0.5-universal
Thermal Dynamics ThermalDynamics-1.12-2.3.3.10-universal
Thermal Expansion ThermalExpansion-1.122-5.3.3.15-universal
Thermal Foundation ThermalFouundation-1.12-2.3.3.10-universal
Vanilla Builders Extension Vanilla Builders Extension-1.12-1.0.4
VE-FluidHandling  VE-FluidHandling-1.12-0.8.0b5
VeinMiner VeinMiner-1.12-0.37.0.628+765cb1f
VisibleRayGenerator VisibleRayGenerator-1.12-5.0.1-universal
Waila Harvestability WailaHarvestability-mc1.12-1.1.11
Wawla - What Are We Looking At Wawla-1.12-2.5.239
Wearable Backpacks WearableBackpacks-1.12-3.0.4
Sorry if there is misspelling, for I wrote this in order to not have you wait as long. Also, I was not looking at that during creation of this, for I am completely new to this interface. Sorry if I seem a little new to this stuff :/

**Comment by Sixer601** [comment]
Or the link https://gist.github.com/Sixer601/50c81fa1608ef6a5c49f7a7bb7139f9f . (I had just reread it and noticed that its harder to read like that. (sorry for posting a lot)

**Comment by BluSunrize** [comment]
Okay, so regarding the unload and power stopping.
You get that when having IE wires insert into TD ducts? Try recreating that without the ducts. Have IE feed into machines diretly. Should confirm whether it's my side or on TD.

Regarding the MA compat, there's multiple issues on this already, best to discuss that here:
https://github.com/BluSunrize/ImmersiveEngineering/issues/2271
I generally dislike compound issues. Everything should have a separate thread to be discussed.

**Comment by BluSunrize** [comment]
Also renamed this so one can actually have an idea what the issue is about.

**Comment by Sixer601** [comment]
I apologize for the compound issues being prevalent, and now know to fix this if there are any other issues. Same with the naming, I wasn't quite sure how to name it with the compound issues. Thank you for fixing it. To clarify the connections between wire relays are still there. There just is no power going through them until I break a relay and place it, as well as connect the fallen wires back in there respectful places as well.

**Comment by Sixer601** [comment]
(and I do have the proper LV Connector hooked up to both the Kinetic Dynamo as well as the Leadstone conduit.)

**Comment by BluSunrize** [comment]
Could you provide a picture of your setup? That might help with understanding

**Comment by Sixer601** [comment]
You my sir, know what you are talking about. The thermal dynamics were cut out of the equation and it works beautifully ( I both went out of the chunk loading area as well as both reloading the chunks and restarting the game). All I need to do now is look into the MA compatibility and make my wire situation look nicer. Thank you so much; its really appreciated. (if you still are interested in my setup (idk why you would be) Direct Message me on Reddit.) Thanks again :)

**Comment by Sixer601** [comment]
The Link you sent me for compatibility with cloches doesn't quite send the message directly across. Does this mean there is no compatibility between the two, or does that mean it will be implemented in a later release of IE?

**Comment by BluSunrize** [comment]
There is compat atm, but only for the resource seeds. I don't play with MA so I don't know what people actually want me to *do* for compat. Input from people who actually use the mod is what I'd need to come up with some proper compat outlines.

**Comment by Sixer601** [comment]
well, ive used it to some extent, so maybe I could help. What would you need to know from the mod to make those outlines?

**Comment by BluSunrize** [comment]
Look up dude, I phrased 3 specific questions for this .-.

**Comment by Sixer601** [comment]
I am really bad at this, because im not quite sure what you mean (still, im sorry).

**Comment by BluSunrize** [comment]
In the issue I linked (not this one, it's closed after all, stop commenting here =P) I phrased 3 reasonably specific questions regarding the compatability.. If someone actually fracking answered those we might get somewhere.

**Comment by Sixer601** [comment]
Alright, I will try. I only commented after it was closed because you replied to me. Sorry :/
