### ISSUE TITLE
[1.12] Creosote bucket not emptying when creating treated planks

### ISSUE THREAD

**Issue by Simage** [BluSunrize/ImmersiveEngineering#2360]
when crafting treated planks using a bucket of creosote the bucket is not emptied allowing you to craft an infinite number of planks using a single bucket. I have only observed this in multiplayer and have not yet tried on a multiplayer server though I would suspect the same issue exists.

Minecraft 1.12
Forge 14.21.1.2420
Mods

- ActuallyAdditions-1.12-r116.jar
- AppleSkin-mc1.12-1.0.7.jar
- BiomesOPlenty-1.12-7.0.0.2291-universal.jar
- Chameleon-1.12-4.1.3.jar
- gravestone-1.8.4.jar
- Harvest-1.12-1.2.4-16.jar
- hopperducts-mc1.12-1.5.jar
- ImmersiveEngineering-0.12-68.jar
- immersivepetroleum-1.12-1.0.12.jar
- InventoryTweaks-1.63+beta.107.jar
- jei_1.12-4.7.1.69.jar
- journeymap-1.12-5.4.9.jar
- JustEnoughResources-1.12-0.8.3.23.jar
- Mantle-1.12-1.3.0.15.jar
- mcjtylib-1.12-2.4.4.jar
- mods.lst
- QuickLeafDecay-MC1.12-1.2.3.jar
- rftools-1.12-6.12.jar
- StorageDrawers-1.12-5.2.9.jar
- TConstruct-1.12-2.7.1.9.jar
- theoneprobe-1.12-1.4.15.jar
- VeinMiner-1.12-0.36.0.623+cd640ee.jar

let me know if I can provide anything else

**Comment by BluSunrize** [comment]
Screenshots please, also test this on IE build 69, the latest one.

**Comment by Simage** [comment]
4 screenshots showing before and after with a single recipe and enough for multiples, if that makes sense, screenshots are from IE build 69, and same additional mods as before

![2017-07-25_09 57 50](https://user-images.githubusercontent.com/2246004/28581711-3644f754-7120-11e7-98ae-8308452939c8.png)
![2017-07-25_09 57 57](https://user-images.githubusercontent.com/2246004/28581713-36490d26-7120-11e7-9cbe-1c58eedd2884.png)
![2017-07-25_09 58 49](https://user-images.githubusercontent.com/2246004/28581712-36469366-7120-11e7-8136-6879263486ff.png)
![2017-07-25_09 58 54](https://user-images.githubusercontent.com/2246004/28581714-364c0fe4-7120-11e7-9155-298d34b7a7b0.png)

**Comment by BluSunrize** [comment]
Can you replicate this in a vanilla crafting table?

**Comment by Simage** [comment]
exact same behaviour

![2017-07-25_11 13 51](https://user-images.githubusercontent.com/2246004/28584674-c851ce6a-712a-11e7-9588-de5088719c72.png)
![2017-07-25_11 13 56](https://user-images.githubusercontent.com/2246004/28584675-c866d56c-712a-11e7-8886-0e6c0760a96f.png)
![2017-07-25_11 14 06](https://user-images.githubusercontent.com/2246004/28584676-c8724d70-712a-11e7-9545-17c80e55c3fb.png)
![2017-07-25_11 14 13](https://user-images.githubusercontent.com/2246004/28584677-c874807c-712a-11e7-92f8-6ef8cc9653c5.png)

**Comment by ConnCraft** [comment]
Can confirm this happens in FTB Unstable 1.0.6, IE version 69. This seems like a pretty bad bug, from a balance POV.

**Comment by winnetrie83** [comment]
I can confirm this bug too. I use a custom modpack.

**Comment by BluSunrize** [comment]
Yeah yeah I've reproduced it, I'll look into it.
