### ISSUE TITLE
[1.12][0.12-69] Blast Furnace Preheater Fan Not Spinning

### ISSUE THREAD

**Issue by Kris1432** [BluSunrize/ImmersiveEngineering#2361]
Forge: 2424
Version: 0.12-69

Image:
https://puu.sh/wSVwY.png

I hope this is valid and I haven't done anything wrong, the power is on the both of them and it appears to be faster in the actual furnace.

**Comment by BluSunrize** [comment]
Yeah it hasn't had an animation since 1.8

**Comment by Kris1432** [comment]
ahh fair enough, sorry for this.
