### ISSUE TITLE
[1.12 - 012-69] Vanilla Hopper ticking crash with Coal Coke oven and conveyor

### ISSUE THREAD

**Issue by VallenFrostweaver** [BluSunrize/ImmersiveEngineering#2363]
As set up in this video at this time stamp here, when I'm about 175-ish blocks away or more (after a period of time has gone by for the coke over to work) I experience a crash.
Crash pastebin: https://pastebin.com/ADVz4pdk
YouTube video of set up and timestamp: https://youtu.be/_AooRnKqros?t=6m47s

It also has a chunk border interaction as seen here:

![bug](https://user-images.githubusercontent.com/13642054/28634863-82e804be-7230-11e7-9eba-f26d4915d997.png)

**Comment by Terpo** [comment]
Thats quite interesting. I talked with Blu about something similiar via Twitter. My coke ovens don't touch the chunk borders but there is also a crash on chunk unload. (leaving server, changing dimensions, get out of loaded area). As my building is quite complex (multiple machines & 4 coke ovens) it was nearly impossible to reproduce the crash. 

I'm using the latest 1.11 release currently.

**Comment by malte0811** [comment]
The crash @VallenFrostweaver makes perfect sense, it happens when something tries to acess the oven when the central block isn't loaded. But it shouldn't happen when everything is in one chunk. Could you post your crashlog as well? I think I may have seen it on twitter, but I forgot the contents.

**Comment by Terpo** [comment]
https://gist.github.com/Terpo/770e7804b8dbeb9694c1786c085710a0
sry for creating so much noise around a bug which already got a workaround on TDs side, but finding the real cause could be helpful. :/

https://github.com/CoFH/Feedback/issues/364
https://github.com/jaquadro/StorageDrawers/issues/542
I will post the twitter link and will record a video of the building when I'm back home.

**Comment by malte0811** [comment]
Don't bother with the video. I guess this is the same bug as in the original crash with something like a race condition mixed in. I'll fix this once I am done with another small-ish project I am working on.
