### ISSUE TITLE
possible bug or mod conflict unsure would like info

### ISSUE THREAD

**Issue by Stormcruzerlore** [BluSunrize/ImmersiveEngineering#2365]
so i am playing on a  custom modpack and  i have immersive engineering installed i am usieng it to power some thermal expansion machines and   what happens is  it will start producing power like normal but after   ai put the machines under a load all at the same time or i use  one machine for a wile it stops making power and all of the cable lines say error i recheck all connections and after  replacing everything multiple time sit   only works 50 percent of the time  and im not sure what is up below is a link  to an imgur albums with pictures of my mods list in it

http://imgur.com/a/oCZc8

Update image of wiring setup below.. keep in mind i  have tried  swamping out the wire connectors  and wire relays and still had issues no matter which  way i had them

http://imgur.com/a/6mSsq

**Comment by BluSunrize** [comment]
pictures of your wire setup?

**Comment by Stormcruzerlore** [comment]
yea give me a bit the pack takes a wile to load

**Comment by Stormcruzerlore** [comment]
have you taken a look at the pictures of the wiring setup as of yet?

**Comment by BluSunrize** [comment]
You're using relays on generators and capacitors. Relays cannot in/output, they are only for the points in between.

**Comment by Stormcruzerlore** [comment]
yes and i have tried   wire connectors  as well and had the same issue it dosnet work weather i use relays or connectors

**Comment by Stormcruzerlore** [comment]
fixed it i swapted them over and it turnes out i  alwasy missed on wich cuasedit to all break now that i  found  the one i missed it  is good i  forgot about the one on the water weel  every time

**Comment by BluSunrize** [comment]
Yeah just for the record, "switching them for relays" will never ever work. They are specifically designed to not interact with power in and outputs in any way. They will *not* work =P
