### ISSUE TITLE
1.10.2 

### ISSUE THREAD

**Issue by X-Manas-X** [BluSunrize/ImmersiveEngineering#2366]
I have a texture problem when I connect to the server.
http://imgur.com/a/wpoqy
When the block is broken and its subsequent laying is all right. Another problem is in devices and connectors. What is connected to the connector and the cable has an incorrect texture or is not visible at all, whether machine, wire or connector. I'm very sorry for bad English, google is used.

**Comment by BluSunrize** [comment]
This is purely a render issue, a render refresh (F3+A) or placing blocks down usually fixes this.
Nothing else I can do about it I'm afraid.
