### ISSUE TITLE
crash using IE and Astral Sorcery

### ISSUE THREAD

**Issue by vivagabe** [BluSunrize/ImmersiveEngineering#2367]
https://paste.ee/p/sIOjz

My wife's computer is a bit old but we've run many mods on it before but never had this come up.  It would crash during the Forge loading phase.  I discovered (after disabling and reenabling mods) that it was astral sorcery and IE combination that was causing crash.  AS would work fine with the other 49 mods but not IE and IE would work fine with the other 49 mods but not AS.  What was strange was that this identical custom mod pack worked fine on my computer, just not on the wife's.  

SyrRockz helped me out a bit but unfortunately none of those remedies worked.

As I was about to give up, the wife suggest I disable our VPN (P.I.A. has a little green guy icon).  What the heck, right? Might as well try it! I turn off VPN and fire up MC with all the mods.  It works!  I honestly don't know if it was coincidental since her computer is old and temperamental or if there was something that the VPN was doing that was causing a crash.  Maybe someone with more knowledge can look at the log and tell.  She's just glad shes able to play again.

**Comment by BluSunrize** [comment]
There is nothing in that log that points to IE directly causing any problems...

**Comment by vivagabe** [comment]
Maybe was old computer being a pain. All i know is now its working.  Thanks for the great mod!
