### ISSUE TITLE
[1.12] Feature Request - Liquid Concrete for filling Quarry Holes

### ISSUE THREAD

**Issue by cyberpunkbln** [BluSunrize/ImmersiveEngineering#2368]
Hello,

is it possible to make an config that iam can use liquid concrete to fill quarry holes. I mean that one Source of Liquid Conrete are only ne hardened to one source of Concrete ore something like that that i can easy use Liquid Conrete do clean fill an quarry hole?

Config.liquid_conrete.onesource true/false
Config.liquid_conrete.amount amount of mB to create one block of concrete

when i use at the moment the drain and liquid concrete he not fill clean an hole.

thx

**Comment by BluSunrize** [comment]
Liquid Concrete is as good as it's going to get. The code us a mess, self-replicating fluids aren't all that great for codework and performance.
