### ISSUE TITLE
[Feature Request] Mineral vein commands

### ISSUE THREAD

**Issue by XFactHD** [BluSunrize/ImmersiveEngineering#237]
Please add commands to add or remove mineral veins from the chunk you are standing in. This could be useful if you build something in creative mode and don't want to search forever to find a mineral vein or want to build it in a specific chunk which doesn't have the mineral veins you need.

**Comment by BluSunrize** [comment]
There is no adding or removing, they randomize based on Chunk Coords and seeds.

**Comment by XFactHD** [comment]
I looked at the code that reads and writes the information for the mineral veins. Wouldn't it be possible to make the command add or remove a tag from the NBTTagList and then make the game reload the NBTTAGLIST?

**Comment by BluSunrize** [comment]
That would change the items in the type of vein (Which is already doable with the API and possibly LodeLaoder). But I can't easily influence where in the world it's found.
