### ISSUE TITLE
Suggestion: new texture for copperblock

### ISSUE THREAD

**Issue by winnetrie83** [BluSunrize/ImmersiveEngineering#2370]
I always wondered why you made the copper block green. I think you should make a texture that fits the copper theme. All other copper blocks/items have their normal copper color, except the copperblock and slab.
It's ofc not that important, but honestly it does looks weird :-)
I also want to solve this for you. So i decided to make a texture based on yours that fits better in the game ( in my opinion). It's basicly a recouloring. You can use it if you like it.
![storage_copper](https://user-images.githubusercontent.com/29025144/28740809-0267264a-740a-11e7-8387-4d74076388a1.png)

**Comment by winnetrie83** [comment]
I just made a texturepack only for this 1 block :-)
Looks like this in game
![2017-07-29_03 16 14](https://user-images.githubusercontent.com/29025144/28740942-6c61b4d2-740c-11e7-8e86-b867b322ee61.png)

**Comment by BluSunrize** [comment]
I didn't make it green, Hazard decided he wanted it to be oxidized copper, so we're sticking with that.
