### ISSUE TITLE
Coke Oven

### ISSUE THREAD

**Issue by TheSnowyChickens** [BluSunrize/ImmersiveEngineering#2371]
Hello

The Coke oven has wrong textures when dismantling.

Thx

![2017-07-29_05 05 53](https://user-images.githubusercontent.com/29357962/28741689-546d75fe-741c-11e7-80b5-333aafa967df.png)

MC 1.12
Immersive 69
Forge 2426

Oh and another thing that I found , the Treated Wood recipe dont use a bucket of Creosote Oil ?
I mean , I think its just 1 Bucket for 8 Planks and not for infinite. (Thats maybe bad English ,sry for that :D)

**Comment by exect3r** [comment]
Yes, the treated wood recipe doesn't 
consume the Creosote Oil bucket,
Also, I'm having issues with wires. I can only connect one wire to the connectors / relays.

![2017-07-29_12 32 41](https://user-images.githubusercontent.com/19252949/28744497-759c8e40-7462-11e7-804d-08e721e746c5.png)

**Comment by BluSunrize** [comment]
That's a connector, they only ever take one wire. RTFM.
Also, don't put issues in another issue. Make new ones were applicable.
The creosote thing is fixed, I'll take a look at the missing particles later.

**Comment by exect3r** [comment]
Yes sorry, just figured it out. I deleted my comment as it adds nothing to solving the issue.

**Comment by BluSunrize** [comment]
Can't do much about this texture thing btw. Don't really have influence over that, since it uses an invisible model for that and I can't do stuff about the texture afaik :/

**Comment by KnightMiner** [comment]
Any way you can set it to a default so it's at least not the missing texture? Maybe just always use the steel block for multiblocks or something

I do recall a Forge PR for blockstate sensitive particle textures which might help in the future otherwise.

**Comment by BluSunrize** [comment]
The problem is that the way multiblocks work, there is a master that renders it all, and the dummies have their model set to builtin/generated, which makes them invisible.

**Comment by KnightMiner** [comment]
Couldn't you just make a model with no elements and a particle texture and use that for multiblocks? Arguably builtin/generated does a bit more work anyways as it's designed to generate from a texture.

**Comment by BluSunrize** [comment]
Yeah tbf, I could (and probably should) do that.
I'll look into it.
