### ISSUE TITLE
Crash when trying to break down Crusher

### ISSUE THREAD

**Issue by mororo** [BluSunrize/ImmersiveEngineering#2374]
Hi, 
I apologize in advance for my English.
When I try to break the multiblock crusher, the server will crash.
While being damaged chunk :( 

My CrashLog : 
https://pastebin.com/VeKLcDFQ

I have found no answer anywhere :(
Thank you very much for the solution

**Comment by BluSunrize** [comment]
Not my fault, Stabilizer mod is doing weird things.
Also 1.7 isn't supported anymore.
