### ISSUE TITLE
[1.12] Thermoelectric generator not producing power

### ISSUE THREAD

**Issue by NillerMedDild** [BluSunrize/ImmersiveEngineering#2376]
Heya! 

It works fine with Lava + Packed Ice aswell as Water + Uranium Block, but not Uranium Block + Packed Ice.

![Picture of the setup](https://user-images.githubusercontent.com/21295394/28754790-2334ad5e-754d-11e7-8842-e1bf1d4c09fe.png)

Minecraft 1.12
Forge 1.12 14.21.1.2426
Immersive Engineering 0.12-69

**Comment by BluSunrize** [comment]
I presume you figured that one out yourself. =P

**Comment by NillerMedDild** [comment]
I didn't realize it was side specific, it works, my bad :p
