### ISSUE TITLE
[1.10.2] Seed Blacklist for mystical agriculture?

### ISSUE THREAD

**Issue by jwebba** [BluSunrize/ImmersiveEngineering#2378]
Hello, 

could you add a whitelist / blacklist that would allow a person to filter in what seeds could go into the Cloche? I have a current issue where the Cloche will take mystical agriculture even through the compat module is set to false. 

Thanks =)

**Comment by BluSunrize** [comment]
Even if I did, 1.10 isn't getting any more updates.
That issue with the mod compat failing disablement seems to be resolved in newer versions as well btw.
