### ISSUE TITLE
Add cloche support for mystical aggrications

### ISSUE THREAD

**Issue by tyler489** [BluSunrize/ImmersiveEngineering#2379]
Its an addon mod for mystical agriculture https://minecraft.curseforge.com/projects/mystical-agradditions it has 2 seeds nether star seed which should be grown on a nether star cruix block and awakened draconium seed that has the be grown on an awakened draconium cruix block. Also can u make magical fertilizer from mystical agriculture work in clockes.. it jntant grows the seed so maybe 100% boost

**Comment by tyler489** [comment]
Idealy these would just drop essence and not seeds just like magical crops do.

**Comment by BluSunrize** [comment]
I'm open to pull requests, but I'm not doing this one. Seems to be rather niche (and stupidly OP, if you can even say that in the context of Mystical Agriculture)

**Comment by tyler489** [comment]
What about allowing mystical agriculture fertilizers in cloches?

**Comment by BluSunrize** [comment]
The whole point of that one is that it instantly grows crops. I won't add that. THe cloche is already powerful enough.
