### ISSUE TITLE
Wire connectors receive power from all sides

### ISSUE THREAD

**Issue by magik6k** [BluSunrize/ImmersiveEngineering#238]
![power from all sides](http://i.gyazo.com/201174394b3218cdc460d88acb2dbd3c.png)
LV/MV/probably HV too connectors are receiving energy from all sides. this is probably related to no side check there: https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/blocks/metal/TileEntityConnectorLV.java#L164

**Comment by theunkn0wn1** [comment]
I can confirm this is occurring in latest build (0ff6cdf5532b81d19978adcdb6ede38a10694e7b)
![image](https://cloud.githubusercontent.com/assets/3110986/8832991/10840a7a-3061-11e5-98b2-eb231b06e70d.png)
The capacitor is receiving power even though the sender is not attached to the energy cell.
