### ISSUE TITLE
Diesel Generator not using up tank, making alternate fuel use impossible without breaking the generator

### ISSUE THREAD

**Issue by mindforger** [BluSunrize/ImmersiveEngineering#2381]
referring from
https://github.com/BluSunrize/ImmersiveEngineering/pull/2303

i checked up the code
https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/blocks/metal/TileEntityDieselGenerator.java#L132

the generator has a required minimum amount (relative to burn value) of fluid in the tank to process, making it impossible to empty the tank without breaking the generator

won't it be better in the else path to use up the remaining fuel and adjust the output packet instead of just plain stopping?

I had this in an early 1.7.10 build, where i used to process BC fuel as long as i got some and tried to inject biodiesel as a reserve, but it failed! But i finally build another setup with a second Generator instead, so i did not bother with this anymore and forgot to report.

PS: to prevent sound stuttering and animation errors or any lag, i would also suggest a minimum amount of fuel in the tank to process for at least a full second of operation. (same like you did with the internal powerstorage on several machines to prevent chunkupdates because of low power condition) ... 

and maybe a cooldown of a second after stopping. If you encounter saturated network condition, you should not start producing power again immediately, as this could lead to stuttering if you only take a few nergy units out of the network and start and stop every two ticks ... all this could be achived using your fan-animation delay i suppose

**Comment by BluSunrize** [comment]
No idea why you are referring to my response on the PR there, but alright.

Yeah the generator has a minimum amount, mostly due to my stubbornness of not wanting to adjust the output packet. It's supposed to always give a consistent 4096 flux/t, as it says on the label.
I supposed I could look into changing that though, to allow residue to be removed without breaking the thing.

However, you then suggest requiring a minimum amount to even start, because stuttering sounds? Wouldn't that defeat the first part of the request, being able to burn the tiyn slivers remaining in a tank? :V

**Comment by mindforger** [comment]
i can not make a PR right nopw but have a look at it and tell me your thoughts :D 

```
if((animation_fanFadeOut == 0) && (connected > 0))
{
	if(((!active) && (tanks[0].getFluidAmount() >= (fluidConsumed * 20))) || active){
		if(!active)
		{
			active = true;
			animation_fanFadeIn = 80;
		}
		float production = (tanks[0].getFluidAmount() >= fluidConsumed)?(1):(tanks[0].getFluidAmount() / fluidConsumed);
		tanks[0].drain(fluidConsumed*production, true);
		int splitOutput = (output*production) / connected;
		int leftover = (output*production) % connected;
		for(int i = 0; i < 3; i++)
			if(receivers[i] != null)
				EnergyHelper.insertFlux(receivers[i], EnumFacing.DOWN, splitOutput + (leftover-- > 0 ? 1 : 0), false);
	}
} else if(active)

```

**Comment by BluSunrize** [comment]
Yeah that could work...

**Comment by mindforger** [comment]
i know that what i am saying next is not gonna sound very comfortable but it may lead to a better overall portability and especially make your code less prone to missed C&P errors

but have you ever thought about a bit higher levels of code abstraction? 
I am seeing a LOT of minecraft and forge base code in nearly every machine you have and i also see quiet often copied code that is prone to be forgotten when there has been a correction in some way.

i mean you got everything already working and stuff, so no use to rewrite it from scratch, but with a little refactoring, i am sure one (or even me) could help you out to abtract such things like fluid extraction from containers, maintaining activity based on bufferlevel and consumption or even cooldown features on every machine the same way making porting a breeze because you only have to change the version depending code once in the abstraction ... this way you could easily backport bugfixes in internal derps

**Comment by BluSunrize** [comment]
All my stuff started out wonderfully abstracted, and then it stopped being so .-.

When I went into 1.8, I generalized the fuck out of IE's basic blocks&multiblocks, shifted loads of stuff like light, direction, etc. to interfaces.
And then the specialcasing started. xD

I should probably refactor again at some point, but it's so much effort, and I'm so terribly lazy.
