### ISSUE TITLE
[issue][1.12-70] cannot pull 4th item stack from garden cloche with shift+right click

### ISSUE THREAD

**Issue by winsrp** [BluSunrize/ImmersiveEngineering#2383]
So when you have your garden cloche fill up with gardened items (no auto extraction attached), and you happily shift+right click your items into your inventory, the 4th stack (from left to right, top to bottom) won't pull out.

**Comment by realdarnedninja** [comment]
Replicated similar behaviour on 1.12-69 and earlier. The 4th stack can be picked up and moved normally though.

**Comment by BluSunrize** [comment]
So it works normally, just not with shiftclick?
Fair enough, probably just a botched slotnumber.

I'll look into fixing this when I get back from vacation in 2 weeks.
