### ISSUE TITLE
1.12 Client Crash Colliding entity with block (Crusher)

### ISSUE THREAD

**Issue by LordRayuga** [BluSunrize/ImmersiveEngineering#2385]
Whenever i want to make Coke Dust this happens
[crash-2017-08-01_10.19.35-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1189957/crash-2017-08-01_10.19.35-server.txt)

**Comment by BluSunrize** [comment]
Show me your IE config, please

**Comment by LordRayuga** [comment]
[Config](https://gist.github.com/LordRayuga/bedef1745e9300d7e13c97b68650f16e)

**Comment by BluSunrize** [comment]
Time modifier on the crusher must be at *least* 0.02, preferably higher :V

**Comment by KnightMiner** [comment]
Does the config method you are using support setting ranges on the value? It might be good to explicitly disallow the value from being less than 0.1 or something (I know the `config.getFloat()` method supports it)
