### ISSUE TITLE
Can't put creosote oil in buckets

### ISSUE THREAD

**Issue by ottmiche** [BluSunrize/ImmersiveEngineering#2386]
Playing on MMC launcher with MC 1.10.2, IE 0.10-61
I can't put creosote oil into buckets, wether directly from the coke oven, nor out of any kind of tank. However extracting it into any kind of tank works. It doesn't have any textur either.

here's my mod list
![unbenannt](https://user-images.githubusercontent.com/11246154/28829105-0ba4eaa0-76d3-11e7-820d-3421d66d019a.PNG)

**Comment by BluSunrize** [comment]
Use an NBT editor to go into the level.dat of your world, find Forge's default fluid list and delete the Creosote entry.
