### ISSUE TITLE
Shift-clicking ammo to reload the Revolver doesn't work.

### ISSUE THREAD

**Issue by 4AM-Campfire** [BluSunrize/ImmersiveEngineering#2388]
Playing MC 1.12, IE version 70. Only IE installed.

Shift-clicking a stack of ammo in your inventory to reload an empty Revolver inside the Revolver GUI doesn't work, you need to place cartridges one by one (or click and drag). The Speed Loaders still work with shift clicking.

**Comment by malte0811** [comment]
This seems to be intentional, see [this](https://github.com/BluSunrize/ImmersiveEngineering/commit/7676cd5da6b542382330ea3a60c521c2fbdaea0a) commit note. It might be possible to enable shift-clicking for single revolvers only, but @BluSunrize will have to decide that.

**Comment by BluSunrize** [comment]
Yup, intentional. You can still click and drag over the slots though.
