### ISSUE TITLE
[suggestion] Mirror the Revolver model when in off-hand.

### ISSUE THREAD

**Issue by 4AM-Campfire** [BluSunrize/ImmersiveEngineering#2389]
When you have an Extended Magazine on an off-hand Revolver, the Magazine points in the same direction as the one in your main-hand. This looks off as you'd expect them to be opposites, so that they would both point toward the outside of the screen.

I know it doesn't make sense if you see it as a single gun being passed between hand, but if you have a pair then you'd expect to have  set them up differently for each hand. (But I'm not sure realism counts when you are already extending the magazine of a revolver gun^^.)

**Comment by BluSunrize** [comment]
I specifically chose not to mirror them for the exact reason you mentioned: the gun is just held in the other hand. 
Take a look at the last Wolfenstein games, for example, they don't mirror the models either.
