### ISSUE TITLE
Kinetic Dynamo config enhancement 

### ISSUE THREAD

**Issue by TheQuantumGeneral** [BluSunrize/ImmersiveEngineering#239]
Would it be possible to make the Kinetic dynamo config not require an integer, similar to the thermometric generator? 

The windmills and waterwheels are very visually appealing but I would like to nerf the power output further in my world. 

Eg:

    # The base RF that is output by the dynamo. This will be modified by the rotation modifier of the attached water- or windmill
    I:"Dynamo: Output"=1

    # Output modifier for the energy created by the Thermoelectric Generator
    D:"Thermoelectric: Output"=0.05

**Comment by BluSunrize** [comment]
Thare you go, added with the latest commit, to be in Version 0.5.0 =P

**Comment by TheQuantumGeneral** [comment]
Thanks :D
