### ISSUE TITLE
[Feature Request] - Torch recipe to use Creosote Oil + Wool + Sticks

### ISSUE THREAD

**Issue by Zebaoth** [BluSunrize/ImmersiveEngineering#2391]
On a sidenote, I'm absolutely blown away by this mod. This has turned minecraft into something different for me, all these huge multiblock machines, a dream come true.

Would be a neat addition if you could make torches from creosote oil bucket, wool and a stick.

As of now there's currently no recipe that's using creosote oil other than treated planks, unless I'm missing something?

This recipe could be a useful way to get rid of excess creosote oil which you'll have sooner or later.
Also after building the drill you're really in desperate need of torches since the drill increases the mining speed at least tenfold, so you'll burn through torches like a madman.

Suggested recipe:

XCX
XWX
XSX

C = Creosote Oil Bucket (1000mB)
W = Wool (1x)
S = Stick (1x)

to create 4x Torches.

Edit: Also please consider adding torches with the respective ore material as a base, so making steel/iron/gold/diamond torches for the extravagant engineer. Maybe some smaller interior lights to comlpement the lanterns would be great too.

Absolutely loving this mod, great work!
Can't wait for the nuclear update.

**Comment by mindforger** [comment]
this recipe was present in forestry before, just for info to prevent clashes :)

**Comment by BluSunrize** [comment]
Huh, that sounds like pretty neat idea, I'll look into that!

**Comment by xenxero1** [comment]
I could've sworn this was already a recipe. FTB Beyond has something like that in it, using creosote bottles instead and producing 6 torches.

**Comment by PrincessRTFM** [comment]
That's probably from Forestry.

**Comment by BluSunrize** [comment]
But I'm don't have bottles anymore so it'll have to be bucket s

**Comment by mindforger** [comment]
hence why i suggested the increase in resulting torches as a bucket is larger than a bottle

**Comment by xenxero1** [comment]
is there a way to oredict fluids/containers? Because it'd certainly make that part easy, even let you use fluid cells from other mods with minimal extra effort.
Also, bottles and buckets are both supposed to be 1000mb worth?

**Comment by KnightMiner** [comment]
See the treated wood planks recipe, works with any fluid container. It's not something done through oredict, it's a fluid handler thing.

**Comment by xenxero1** [comment]
seems to be the route Mojang pushed, but the modding community seems to has decided otherwise.

**Comment by KnightMiner** [comment]
I think the main reason for that is the modded community uses a base 10 system, so a bottle would be 333mb. But then three would be 999mb, where is the extra 1mb? As a result, 1000 made a bit more sense as its practical to work with, even if it adds minor issues with water duplication. I think most devs just don't use vanilla bottles for fluids instead these days

**Comment by mindforger** [comment]
@KnightMiner they way you talk makes me believe you did not yet build a bottler :D because this freaking 1mb is a pain XD

**Comment by HappyPineapple** [comment]
Also make it so when you walk around it light's the aria up super useful but make it have have  a limited burn time so as to balance it out. Also make them re-wool able so as to reuse a stick.

**Comment by BluSunrize** [comment]
No. I'm adding a recipe for torches, not a new torch. 
That's not the point of this request.
