### ISSUE TITLE
Slabs/Stairs Scaffolding Recipes don't work

### ISSUE THREAD

**Issue by Zebaoth** [BluSunrize/ImmersiveEngineering#2392]
Recipe doesn't work in creative or survival mode for any of the new slabs/stairs, Iron, Steel, Aluminium, no matter which.

Tested on minecraft 1.12,
forge 1.12 - 14.21.1.2443
IE 0.12-70

**Comment by BluSunrize** [comment]
Oh fiddlesticks. I think I just forgot to add any recipes. 

Sorry about that, I'll see to fixing it when I get back from vacation in 2 weeks
