### ISSUE TITLE
MC v1.12 / IE v0.12-70 - Multiblock Layers Not Rendering Properly During Placement

### ISSUE THREAD

**Issue by Nijoma69** [BluSunrize/ImmersiveEngineering#2395]
Hi, thanks for such a fantastic mod, long may it continue ...

Issue:

When placing the first layer of the Squeezer the Light Engineering block is not rendered and creates a transparent hole so that you can see deep into the world, subsequent placement of Steel Scaffolding also do not render but does not create further holes.

In the attached screenshot I've hovered over the 1st layer with a Tinkers hammer so that the bounding boxes of each block in the layer is visible.

![screenshot](https://user-images.githubusercontent.com/16520157/29002152-06b1aadc-7a94-11e7-8f3f-17c4ba86d41a.png)

Regards

Nick

**Comment by BluSunrize** [comment]
Modlist? 
Also, are you using a resource pack? 

Oh and I'm on holiday, so replies may be late.

**Comment by Nijoma69** [comment]
Hi,

Modlist is below: -

![modlist](https://user-images.githubusercontent.com/16520157/29002315-54875e3e-7a97-11e7-84ae-48d13abd6863.png)

No resource packs and no Optifine ... just plain old vanilla MC with Forge 14.21.1.2443 and a few mods.

No pressure, it's cosmetic not game breaking so enjoy your holiday

Regards

Nick

**Comment by malte0811** [comment]
Does this happen without CTM? Both the scaffolding and the engineer's block have CTM models.

**Comment by BluSunrize** [comment]
Go into IEs config, disable the compat for Chisel, that should do it.

**Comment by Nijoma69** [comment]
Client, server side or both?

**Comment by malte0811** [comment]
I'd say try in a single player world. Otherwise client side should be enough, but I haven't worked with CTM yet.

**Comment by BluSunrize** [comment]
Client. Known issue. Disable Chisel compat, I already know why this is happening.

**Comment by Nijoma69** [comment]
Compat for Chisel disabled on server via .cfg file (server restarted) and disabled in client mod options (client restarted) ... no change I'm afraid, possibly another mod in Compat?

**Comment by BluSunrize** [comment]
Mate, read what I said. Disable the Chisel compat in IEs config, on your client.

**Comment by Nijoma69** [comment]
Yeah, that fixed it.

Cheers, sorry for the confusion

**Comment by BluSunrize** [comment]
Called it =P
