### ISSUE TITLE
[1.12] NullPointerException

### ISSUE THREAD

**Issue by FiveEYZ** [BluSunrize/ImmersiveEngineering#2396]
**What is the bug?**

Error in console that told me to report to mod author
- https://gist.github.com/FiveEYZ/521764c8649855745102ae949ef11e88

**What did you do to make it happen?**

Modpack update, immersivepetroleum was one of the mods getting updated

**Does it happen every time you do this? Does it happen if you do something else as well?** 

Reported after i saw the error the first time.

**Did this happen on a dedicated server (multiplayer servers), in LAN multiplayer or in singleplayer?** 

dedicated server

**What other mods were installed when the bug happened?**

Modpack name is Preedcraft
here is a "Manually triggered debug crash":
- https://gist.github.com/FiveEYZ/f60d634633f3b79699e42cf32ad6ea9f

**Comment by malte0811** [comment]
Interesting, the world seems to be `null`. The stacktrace doesn't look quite normal (this is a sponge server and the ruins mod seems to be implicitely generating chunks), I'll look at the code involved later this evening.
