### ISSUE TITLE
Use capabilities instead of IInternalStorageItem

### ISSUE THREAD

**Issue by yaroslav4167** [BluSunrize/ImmersiveEngineering#2397]
Principe: If 2 players simultaneously throw 1 item off the workbench - the item can be duplicated.

**Comment by malte0811** [comment]
Please read the contributing guidelines and include the information requested there, especially the version of IE used and general setup information like modpack, server software, etc. It is not quite clear (at least to me) what you did to duplicate the items: Did 2 players open the GUI and then take out the item? How close does "simultaneous" have to be? Can both players actually use the items, drop them on the floor, pick them up again, etc?

**Comment by yaroslav4167** [comment]
I tested it on 1.11 (server on SpongeForge), but Dupe worked for 1.7 more. Players should almost simultaneously (within 0.2-0.5 seconds) throw the item from the inventory Engineer's Workbench.
At the end you get a fully working item. (Not fake)
Mods:
> (P)FastAsyncWorldEdit-sponge111-17.08.04-1186ca8-791-14.1.22.jar
> (P)griefprevention-1.11.2-3.1.1.294.jar
> (P)LuckPerms-Sponge-3.2.10.jar
> (P)NoXray.jar
> (P)Nucleus-1.0.1-LTS-1.11.2-1.12-S6.0-plugin.jar
> (P)SkyClaims-0.20.0-beta.jar
> (SPONGE)spongeforge-1.11.2-2393-6.1.0-BETA-2484.jar
> ActuallyAdditions-1.11.2-r110.jar
> applied-llamagistics-1.11.2-rv5-beta-4.jar
> BetterFps-1.4.5.jar
> Biome_Bundle-1.11.2-v5.1.jar
> Chisel-MC1.11.2-0.0.13.22.jar
> chiselsandbits-13.13.jar
> compatlayer-1.11.2-0.2.9.jar
> Cosmetic-Wings-1.11.2-0.5.4.jar
> DarkUtilities-1.11.2-1.2.0.147.jar
> denseores-1.11-1.0.2.jar
> DiscordIntegration-mc1.11.2-3.0.0.jar
> energyconverters_1.11.2-1.0.1.22.jar
> forestry_1.11.2-5.3.4.155.jar
> generators-0.9.20.6-mc1.11.2.jar
> OpenTerrainGenerator-1.11.2-v6.jar
> Pam's HarvestCraft 1.11.2h.jar
> theoneprobe-1.1x-1.4.14.jar
> UniDict-1.11.2-1.1b.jar
> [BuildCraft]buildcraft-7.99.6.jar
> [Core]Aroma1997Core-1.11.2-1.2.0.0.jar
> [Core]bdlib-1.13.2.7-mc1.11.2.jar
> [Core]Bookshelf-1.11.2-2.0.0.388.jar
> [Core]CodeChickenLib-1.11.2-3.0.0.284-universal.jar
> [Core]CTM-MC1.11.2-0.2.1.10.jar
> [Core]Forgelin-1.4.2.jar
> [Core]WanionLib-1.11.2-1.1.jar
> [Dungeons]DungeonTactics-1.11.2-0.12.5.jar
> [Dungeons]RoguelikeDungeons-1.11.2-1.6.6.jar
> [IC2]industrialcraft-2-2.7.81-ex111.jar
> [IC2]VisibleRayGenerator-1.11.2-5.0.1-universal.jar
> [IE]ImmersiveEngineering-0.11-63.jar
> [IE]immersivepetroleum-1.11.2-1.1.2.jar
> [IE]IndustrialWires-1.5-13.jar
> [JEI]blockdrops-1.11.2-1.2.3.jar
> [JEI]jehc-1.11.2-1.3.0.jar
> [JEI]jeibees-0.9.0.6-mc1.11.2.jar
> [JEI]jeiintegration_1.11.2-1.2.0.21.jar
> [JEI]jei_1.11.2-4.5.0.295.jar
> [JEI]jepb-1.11.2-1.2.jar
> [JEI]JustEnoughResources-1.11.2-0.6.6.12.jar
> [JEI]NotEnoughItems-1.11.2-2.3.0.227-universal.jar
> [Tweak]CraftTweaker-1.11.2-3.0.26.jar
> [Tweak]modtweaker-3.0.2.jar
> [Tweak]MTLib-2.0.3.jar

**Comment by malte0811** [comment]
Have you tried without spongeforge? I just saw some old reports of this happening with tinker's crafting stations, those were caused by spongeforge.

**Comment by malte0811** [comment]
Any update on this?

**Comment by yaroslav4167** [comment]
In a single player did not check.
On 1.7.10 servers (KCauldron, Thermos) the same bug.

**Comment by KnightMiner** [comment]
He means a normal Forge server. No sponge, no cauldron, etc.

**Comment by yaroslav4167** [comment]
SinglePlayer LAN-server not considered?
Checked, there is also duplication works.

**Comment by malte0811** [comment]
I'll take a look tomorrow. And I'll probably need to read up on macros or something to click fast enough...

**Comment by yaroslav4167** [comment]
https://youtu.be/gUwEACOjvtg?t=4m20s
Russian YouTuber showed how it works.

**Comment by malte0811** [comment]
I *think* I've fixed this...
I'll keep the issue open (and rename it) as a reminder to move `IInternalStorageItem` to Forge's item capabilities. I'll start working on that now, but I don't have an ETA since a) I don't know how much work this will be, b) the IW Marx generator is nearly done and c) IRL stuff.
@BluSunrize Do you know whether any addons use `IInternalStorageItem`?

**Comment by BluSunrize** [comment]
No idea.
We'll find out. Change it and if it breaks addons devs will fix it. x3

**Comment by malte0811** [comment]
There's the first commit. There are probably some bad bugs in there and it doesn't handle moving from the old system to the caps (I'll work on that tomorrow), but in general it seems to be working. If anyone is bored enough to test it, go ahead, but please don't put it into any world you don't want to break.

**Comment by malte0811** [comment]
Second commit done (0cd3a2e2db21f69c1a2042faf0b7bc3bea99784c), I'll do some work on IW now. With that commit speedloaders have the same GUI as revolvers (not just visually, in code as well ). This also means that speedloaders in the offhand can be filled in the same GUI as revolvers/speedloaders in the main hand. @BluSunrize, I assume that's ok?

**Comment by BluSunrize** [comment]
Yeah that's cool by me.
Does it also allow two speedloaders?

**Comment by malte0811** [comment]
I didn't test that case specifically, but it should work (Any 2 `IBulletContainer`'s should work).
I think I tested everything else I changed in those 2 commits, but I'd prefer to have someone else look over it before pushing it to master.

**Comment by malte0811** [comment]
I just pushed the changes to master, they should be in the next release.
