### ISSUE TITLE
[Suggestion] Mystical Fertilizer intigration

### ISSUE THREAD

**Issue by TheSnowyChickens** [BluSunrize/ImmersiveEngineering#2398]
Hello
Is it possible , that you can add the intigration for mystical fertilizer from mystical agriculture for the Garden Cloche ?
Maybe just a higher modifier value then bone meal : 1.50 or 1.75
![fertilizer](https://user-images.githubusercontent.com/29357962/29006417-d013b4a0-7aef-11e7-9deb-28f086cd35c5.png)

Thx :)

**Comment by BluSunrize** [comment]
That fertilizer exists solely to instantly grow magical crops, I don't think it behaves differently than bonemeal on normal ones, so there is little point to add this
