### ISSUE TITLE
Rendering bug 1.12 (immersive-engeering-0.12-70)

### ISSUE THREAD

**Issue by trilexcom** [BluSunrize/ImmersiveEngineering#2399]
Your bug report should contain answers to these questions (If adding screenshots makes answering one of these questions easier, add them):

Version : immersive-engeering-0.12-70
Forge Version: Forge-14-21-1.2443      
What is the bug? Rendering Bug with the block 
        What did you do to make it happen? i tried to build any of multiblock machine like crusher or metal press
        Does it happen every time you do this? yes
        Did this happen on a dedicated server (multiplayer servers) yes
        What other mods were installed when the bug happened?
        Crashlogs link : https://pastebin.com/UesniL2G
       Mode Pack : Trilex Pack
Screenshot link : http://imgur.com/a/xmuHU

Solution when i downgrade to version 69 its working fine

please let me know if its another mod causing issue i will report it to them thanks 

Mat

**Comment by BluSunrize** [comment]
It's a known issue. I'll fix it properly when I get back from holiday. 

For now, go into IEs config and disable the compat for Chisel, it borks with the newly introduced CTM compat.

**Comment by trilexcom** [comment]
thanks
