### ISSUE TITLE
Coal Coke Block gives you more creosote output?

### ISSUE THREAD

**Issue by CatDany** [BluSunrize/ImmersiveEngineering#24]
1 Coal => 1 Coal Coke + 500 mB of Creosote
1 Coal Block => 1 Coal Coke + 5000 mB of Creosote
but wait
9 Coal => 9 Coal Coke + 500*10 mB of Creosote
Why not 500*9? Is that intended or what?

https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/IEContent.java#L413

**Comment by BluSunrize** [comment]
Yes, that is intended. Just like a vanilla Coal Block burns for 10 times as long as coal.

**Comment by CatDany** [comment]
Thanks
