### ISSUE TITLE
Item Dupe

### ISSUE THREAD

**Issue by Darklymediaa** [BluSunrize/ImmersiveEngineering#240]
Hi!

I dont know its a Bloodmagic or an Immersive engineering problem.

Everytime i teleport the excavator via an teleposer (7x7x7) there will dupe 1x SteelBlock and 1x Heavy Engineering Block. Everytime i click the teleposer on each teleport side :/

**Comment by Darklymediaa** [comment]
hm okay i dont know how but this two blocks going invisible on the construct itself

**Comment by BluSunrize** [comment]
You're not /supposed/ to telepose it, you genius. It's a friggin multiblock. Those are not /meant/ to be moved. >_<

**Comment by Darklymediaa** [comment]
öhm kay but its work and to move this huge thing its not even bad its cool ^^

**Comment by BluSunrize** [comment]
It's very bad. Multiblocks are complex. Moving them is a fairly stupid idea.

**Comment by AEnterprise** [comment]
i know from experience with BCA that that that that won't stop them, they will never stop trying about it and always complain if it doesn't work

**Comment by BluSunrize** [comment]
Past the point. My Multiblocks are not designed to be moved and the next update will stop BM teleposers.
