### ISSUE TITLE
Mod does not follow coremod best practices

### ISSUE THREAD

**Issue by GGWarriorWP** [BluSunrize/ImmersiveEngineering#2400]
In 1.12, a coremod has been added to ImmersiveEngineering. However, as of 1.12, coremods should no longer be in the same jar as the mod and the should be signed. For more information please read http://www.minecraftforge.net/forum/topic/58706-regarding-minecraft-112-and-policy-changes/

**Comment by BluSunrize** [comment]
I dunno how to sign jars and I wasn't interested enough to look into it either. Also, the last few releases were a bit impromptu. 

Other devs don't adhere to this either and Forge doesn't yet enforce it, so I'm not too bothered.
