### ISSUE TITLE
[1.12] CTM-compatible blocks are invisible when CTM 0.2.1.5 is installed

### ISSUE THREAD

**Issue by the-realest-stu** [BluSunrize/ImmersiveEngineering#2401]
All blocks that are supposed to have connected textures when CTM is installed are invisible when using CTM 0.2.1.5. This is with Immersive Engineering 0.12-70.

Also, disabling chisel compat in the immersive engineering config allows all of the blocks to render correctly, with connected textures.

**Comment by mindforger** [comment]
will be dealt with when Blu is back from vacation

**Comment by BluSunrize** [comment]
As previously explained on two other issues. Please use the search function.

**Comment by the-realest-stu** [comment]
Oh, I made the mistake of only looking for open issues, since it didn't seem like it had been fixed. My bad, I guess I shouldn't have assumed that you would leave an issue open until it was solved.

**Comment by mindforger** [comment]
deactivate chisel compat until it is fixed and released

**Comment by BluSunrize** [comment]
Yeah, fair, I'll reopen this as a notifier. 
But most people don't check anyway... xD
