### ISSUE TITLE
[1.12 r70] Multiblock blocks missing model 

### ISSUE THREAD

**Issue by Sir1usBl4ck** [BluSunrize/ImmersiveEngineering#2402]
Light Eng / Redstone Eng / Steel scaffolding are missing blocks when placed to build multiblocks and are transparent

![2017-08-07_11 07 37](https://user-images.githubusercontent.com/30795274/29020711-40667152-7b63-11e7-9122-65ad7259e28a.png)

**Comment by mindforger** [comment]
please use the search first, has been reported already and will be dealt with when blu ends his vacation

**Comment by Sir1usBl4ck** [comment]
Didnt realize it was connected to the CTM issue I just read, Sorry

**Comment by mindforger** [comment]
disable chisel compat in the meantime

**Comment by malte0811** [comment]
I'll close this since @BluSunrize reopened #2401.
