### ISSUE TITLE
[suggestion] Make garden cloche grow mushrooms in podzol

### ISSUE THREAD

**Issue by winsrp** [BluSunrize/ImmersiveEngineering#2404]
As far as the vanilla minecraft goes, podzol has the same characteristics as mycelium for growing mushrooms, but it doesn't work on the cloche.

"Usage
Mushrooms can be planted and grown on blocks in light levels below 13 and not directly underneath the sky. If planted on **mycelium** or **podzol**, they can stay planted in any light level. Both brown and red mushrooms grow at the same rate regardless of light level"

*source <https://minecraft.gamepedia.com/Mushroom>

**Comment by BluSunrize** [comment]
Fair point, I guess. I'll look into it after my holiday.
