### ISSUE TITLE
[Suggestion] Craftable Oil Lamps using hemp fibers, plant oil, and your nifty metals.

### ISSUE THREAD

**Issue by Reiliegh** [BluSunrize/ImmersiveEngineering#2405]
I was just puttering around wondering what to do with extra plant oil and hemp fiber I had laying around and couldn't really spot a use aside from windmill parts and biodiesel. I thought mebbe a light source styled as an oil lamp would be nice, not to mention I'm pretty much the only person on my server willing to head into the nether for glow stone. Forgive me if this suggestion is in the inappropriate area. Thanks.

**Comment by HappyPineapple** [comment]
Great idea I thought of it but you beat me to it!
