### ISSUE TITLE
Immersive Engineering ftb skyfactory 3

### ISSUE THREAD

**Issue by BlueGameFilms** [BluSunrize/ImmersiveEngineering#2407]
I have been trying to play ftb skyfactory 3, but it just crashes when it gets to immersive engineering. can someone please guide me through what i have to do because im not that good with mods.

**Comment by BlueGameFilms** [comment]
I have been trying to play ftb skyfactory 3, but it just crashes when it gets to immersive engineering. can someone please guide me through what i have to do because im not that good with mods.

**Comment by BluSunrize** [comment]
First of all, you read the damn contribution guidelines, submit Version number, modlist, and crash log. 
And mind you'll use pastebin, because I don't want a full crash log in here.
