### ISSUE TITLE
[Suggestion] Use issue tags and crosslinking

### ISSUE THREAD

**Issue by ouroborus** [BluSunrize/ImmersiveEngineering#2409]
Using issue labels such as "Won't Fix", "Duplicate", "Fixed" as well as cross-linking duplicate or related items improves issue tracking.

**Comment by malte0811** [comment]
(I am not the main maintainer, but the only other person (that I know of) with push/collaborator permissions.)
First of all: Unless you were planning on helping with development, it isn't really relevant for you. We have gotten along quite well for 2 years as it is.
Labels: I'd use them if they were available on mobile. When I am using a PC I am generally busy working with code and don't want to spend more time dealing with issues. There are usually 1-2 reports per day (except right after major releases), that isn't too much to handle without labels.
Cross-linking duplicates: I (and most other people who deal with them) generally cross-reference the other issue in case of a duplicate (just search for "Duplicate" in all issues for proof). Yes, @BluSunrize didn't cross-reference in your other issue, but a) searching for the other issue isn't hard on PC and b) he is on vacation and probably just wanted to quickly deal with the duplicate. Searching for the old issue on mobile is a bit annoying though, which may explain why he didn't link the other one.

**Comment by BluSunrize** [comment]
And "won't fix" either doesn't happen (because we fix things) or of it does, it usually says so in my comment when closing the issue. As long as people actually use the search function and then proceed to *read* the issue, it should be apparent.

**Comment by AEnterprise** [comment]
well this sounds like a perfect issue to label "won't fix"

**Comment by HappyPineapple** [comment]
can we close this ?

**Comment by BluSunrize** [comment]
Can you maybe stop spamming every single issue on my tracker?
This one is probably the least concerning to you yet you ask for a close? Dafuq?
