### ISSUE TITLE
IE version mismatch

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#241]
@BluSunrize 
The changelog puts IE at version 0.5.0 yet build.gradle puts IE still at 0.4.4.
is this an error?

**Comment by BluSunrize** [comment]
If you look at the changelog in detail, version 0.4.4 has "BUILT" behind it. 0.5.0 doesn't. That should give you a hint. 0.5.0 is the version I'm working on atm, but it's not done.

**Comment by theunkn0wn1** [comment]
i see.. was under impression "BUILT" implied it was stable and pushed to curse. silly me; sorry :#

**Comment by BluSunrize** [comment]
Same thing. Built is built. Everything I build goes to curse.
