### ISSUE TITLE
[New addon]Immersive tech

### ISSUE THREAD

**Issue by ferro2000** [BluSunrize/ImmersiveEngineering#2410]
Immersive Tech is an addon for Immersive Engineering.
Basicaly, it adds a new method to produce energy (RF) using the sun.
It adds 4 multiblock structures:

Distiller, 3x3x3 machine which produces Distilled Water from normal Water.
Solar Tower, 3x7x3 machine which produce Steam from water distilled and normal (distilled is more efficient). The Solar Tower needs at least 1Solar Reflector to work.
Solar Reflector, 3x5x1 multiblock which reflects sunlight in the direction of the Solar Tower.
Steam Turbine, 3x4x12 massive machine which produces energy from steam.

 

I'm searching for a 3d artist for the next models of the mod

Link: https://minecraft.curseforge.com/projects/immersive-tech

**Comment by kane-thornwyrd** [comment]
lol 1.10.2

**Comment by malte0811** [comment]
This is an issue tracker. It is not intended for advertising (or looking for artists) but for bug reports and suggestions relevant to IE. You could try asking in the #bluSunrize IRC channel on esper.net. Aside from that I'd suggest you add some documentation to your mod, the manual and its API exist for a reason.
(@BluSunrize, if you disagree, I'm sorry for just closing this)

**Comment by BluSunrize** [comment]
Nah, legitimately closed. 
Also, not very interested in it myself. I find Solar Power boring, that's why I never added it ^^

**Comment by laz2727** [comment]
Solar's fun if you make it as weak as it is irl and use reflectors :P

**Comment by TheSnowyChickens** [comment]
@ferro2000 Update it please to 1.12 and all is fine :)
Your models looks very nice and the idea from the reflectors is good !
