### ISSUE TITLE
Garden Cloche won't take many mod seeds 1.11.2 -63

### ISSUE THREAD

**Issue by HammerDave** [BluSunrize/ImmersiveEngineering#2413]
Can't get mystical agriculture or natura seeds into garden cloche.
This is 1.11.2 using the 0.11-63 jar file.  We're on a server and the config settings are all set for compat on.
I see there are other issues which are closed.  The code level which should fix those is on.
Is there a particular forge level dependency?  Any other info you need for diagnosis?
Thanks!

**Comment by BluSunrize** [comment]
They are all hardcoded. If you actually gave examples, I might consider including them for the new 1.12 releases.

**Comment by HammerDave** [comment]
Ah, there might be a misunderstanding.
Previous issues have said that mystical agriculture seeds should work, in particular the inferium seeds but also resources.  I have the release that should fix them applied and they still don't work.  The players say that either the seed won't go in at all, or it pops out when we close the interface.  So the real question is, is there a forge or other dependency?  Some mods check that and complain if the required level isn't present...  And if it's not a dependency thing then maybe there is another bug?

But I understand what you're saying about hard coded support and needing examples.  I'll gather input from the players on the server.  Thanks!

**Comment by BluSunrize** [comment]
Oh. yeah no that's just on latest release. I didn't backport anything to 1.11.
Only 1.12 can handle Inferium seeds, sorry :V
