### ISSUE TITLE
[0.12-70] Coke Oven/Blast Furnace render glitch

### ISSUE THREAD

**Issue by Lukas45** [BluSunrize/ImmersiveEngineering#2414]
Coke Oven and Blast Furnace visually glitches out after ~~having been assembled for some time (often during/after being used)~~ going out of render range, and back in (Did some testing while writing the post). Other players will see them as glitched out as well when going to look at them
They are still fully functional.
![2017-08-10_01 07 49](https://user-images.githubusercontent.com/4707702/29248737-c259718a-801f-11e7-8a79-746ca341b76e.png)
![2017-08-13_11 45 39](https://user-images.githubusercontent.com/4707702/29248739-c6326f28-801f-11e7-8430-841cf29881fa.png)

I should maybe note that it's not the only things glitching out in the area. Storage Drawers in a specific subchunk, and Tinker's Drying Racks also glitches visually. And vanilla beds to an extent. Currently located in a Rainforest biome (Biomes O' Plenty), so don't know if its an error with BOP? I checked the Ovens of some other players who lives in a Shrubland biome (also BOP), which looks perfectly fine.

**Comment by BluSunrize** [comment]
Modlist, forced crash log?

**Comment by Lukas45** [comment]
Crashlog (forced):
https://pastebin.com/PYgvEjZJ

Modlist:
>     Actually Additions by Ellpeck
>     Actually Baubles by Jacky1356400
>     Additional Banners by darkh4x
>     Akashic Tome by Vazkii
>     Angel Ring To Bauble by Portablejim
>     Angel of Vengeance by Tamaized
>     AppleCore by squeek502
>     AppleSkin by squeek502
>     Applied Energistics 2 by AlgorithmX2 (Temporarily removed)
>     Applied Fluidics by Thiakill
>     Applied Llamagistics by Thiakill (Temporarily replacing Applied Energistics 2)
>     Architect by Sangar
>     Astral Sorcery by HellFirePvP
>     AutoRegLib by Vazkii
>     Bad Wither No Cookie by Kreezxil
>     Baubles by Azanor
>     Bed Bugs by gr8pefish
>     Better Builder's Wands by Portablejim
>     BetterFps by Guichaguri
>     BiblioCraft by Nuchaz
>     Binnie's Mods by Binnie567
>     Biomes O’ Plenty by Glitchfiend
>     Block Drops (JEI Addon) by MrRiegel
>     Blur by tterrag1098
>     Bookshelf by Darkhax
>     Brandon's Core by brandon3055
>     Chameleon by jaquadro
>     Chest Transporter by CubeX2
>     Chisel by tterrag1098
>     Chisels & Bits by AlgorithmX2
>     Clipboard by shadowfactsmc
>     CoFHCore by TeamCoFH
>     CoFHWorld by TeamCoFH
>     Cooking for Blockheads by BlayTheNinth
>     Computality by Dr_Codex
>     ConnectedTexturesMod by tterrag1098
>     Controlling by jaredllll08
>     Cosmetic Armor Reworked by ZLainSama
>     CraftTweaker by jaredlll08
>     Custom Backgrounds by Lumien
>     Custom Main Menu by Lumien
>     Cyclic by Lothrazar
>     Dark Utilities by Darkhax
>     Davincis Vessels by bk1325
>     Draconic Evolution by brandon3055
>     Embers by elucent
>     EnderStorage by chicken_bones
>     Energy Converters by xalcon
>     Environmental Tech by ValkyrieofNight
>     Exchangers by Jacky1356400
>     Extra Rails by shadowfactsmc
>     Extra Utilities by RWTema
>     Extreme Reactors by ZeroNoRyouki
>     Farming for Blockheads by BlayTheNinth
>     Flat Colored Blocks by AlgorithmX2
>     FoamFix by asie
>     Forestry by SirSengir
>     Garden Stuff by jaquadro
>     Gendustry by bdew
>     Grass Burner by not_loki
>     Guide-API by TehNut
>     Hwyla by TehNut
>     Industrial Craft by Player
>     Immersive Engineering by BluSunrize
>     Immersive Petroleum by Flaxbeard
>     Industrial Wires by malte0811
>     Inventory Tweaks by Kobata
>     Iron Chests by progwml6
>     IvToolkit by Ivorius
>     Journeymap by techbrew
>     Jukebox by SR2610
>     Just Enough Bees (JEB) by bdew
>     Just Enough HarvestCraft (JEHC) by mrAppleXZ
>     Just Enough Items (JEI) by mezz
>     Just Enough Pattern Banners (JEPB) by Lorexe
>     Just Enough Resources (JER) by Way2muchnoise
>     KleeSlabs by BlayTheNinth
>     Lapis Stays in the Enchanting Table by csb987
>     Level Up! by Beeto
>     Magical Map by Shadows_Of_Fire
>     MalisisCore by Ordinastie
>     MalisisDoors by Ordinastie
>     McJtyLib by McJty
>     MCMultipart by amadornes
>     Mekanism by aidencbrady
>     MekanismGenerators by aidencbrady
>     MekanismTools by aidencbrady
>     Minecolonies by Kostronor
>     Modular Routers by desht
>     ModTweaker by jaredlll08
>     More Overlays by feldim2425
>     Morpheus by Quetzi
>     Morph-o-Tool by Vazkii
>     MouseTweaks by YaLTeR97
>     MovingWorld by bk1325
>     MTLib by jaredlll08
>     Natura by mDiyo
>     Nature’s Compass by ChaosTheDude
>     Not Enough Wands by romelo333
>     No Mob Spawning On Trees by oldjunyi
>     OpenBlocks Elevator by VsnGamer
>     Pam's Harvestcraft by MatrexsVigil
>     PlusTiC by LandMaster
>     Psi by Vazkii
>     Quark by Vazkii
>     Quick Leaf Decay by Lumien
>     Rainbow Oak Trees by csb987
>     Ranged Pumps by raoulvdberge
>     ReAuth by TechnicianLP
>     RebornCore by modmuss50
>     Recurrent Complex by Ivorius
>     Redstone Arsenal by TeamCoFH
>     Redstone Flux by TeamCoFH
>     Resource Loader by Lumien
>     RFTools by McJty
>     RFTools Control by McJty
>     RFTools Dimensions by McJty
>     Roots by elucent
>     Rustic by mangoose
>     Scannable by Sangar
>     Shadowfacts' Forgelin by shadowfactsmc
>     ShadowMC by shadowfactsmc
>     Simple Sponge by Jacky13564000
>     Spice of Life by squeek502
>     Stackie by Lunatrius
>     Steve's Carts Reborn by modmuss50
>     Storage Drawers by jaqueadro
>     SwingThroughGrass by Exidex
>     TamModized by Tamaized
>     The Lost Cities by McJty
>     Thermal Cultivation by TeamCoFH
>     Thermal Expansion by TeamCoFH
>     Thermal Dynamics by TeamCoFH
>     Thermal Foundation by TeamCoFH
>     Tinkers' Construct by mDiyo
>     Tomb Many Graves by M4thG33k
>     TorchMaster by xalcon
>     ToroHealth Damage Indicators by ToroCraft
>     Villager Market by Face_of_Cat
>     VoidCraft by Tamaized
>     Wawla - What Are We Looking At by Darkhax
>     XNet by McJty
>     Xtones by TehNut
>     ZeroCore by ZeroNoRyouki

**Comment by BluSunrize** [comment]
Is the server running Sponge?

**Comment by Lukas45** [comment]
Nope, its a Forge server

**Comment by Lukas45** [comment]
Water Wheel is going well with this issue. (There are 5 moving Water Sheels in that picture)
![2017-08-13_22 56 10](https://user-images.githubusercontent.com/4707702/29253365-bd4cb110-807a-11e7-9b96-455631b32192.png)

**Comment by Lukas45** [comment]
Well, I found the culprit.
Had started to move all my stuff to a new location, and noticed that things stopped glitching as I had almost torn everything down.
Turns out that the Harvestcraft Presser and Apiary messes up many other renders in their area that they're placed in.
