### ISSUE TITLE
[1.12] Garden Cloche Visual issues

### ISSUE THREAD

**Issue by YOYOK9** [BluSunrize/ImmersiveEngineering#2415]
The garden cloche seems to be rendering blocks threw the glass weirdly compared to other blocks. 

ImmersiveEngineering-0.12-70
Forge - 14.21.1.2443

Garden Cloche:
https://puu.sh/x93Gq/f98324864c.jpg
Other Immersive block:
https://puu.sh/x93Fb/588998904b.jpg

**Comment by BluSunrize** [comment]
The renders on the charging station work quite different. 

I'll look at it in a week or so

**Comment by BluSunrize** [comment]
Can't replicate this.
Please provide a debug crash by holding F3+C and upload it to Pastebin, then link it here.
