### ISSUE TITLE
Railgun issue

### ISSUE THREAD

**Issue by KamiSami** [BluSunrize/ImmersiveEngineering#2417]
So, to put it simple... When i shoot with railgun, most of the time the rod goes through enemies and does not even damage them. I wish you could fix this issue. ^^; And it is not bad aim, i can clearly see where the rod travels, and end up seeing them going right behind the mobs aswell without dealing damage.

**Comment by malte0811** [comment]
What version of IE are you using?

**Comment by KamiSami** [comment]
ImmersiveEngineering-0.12-70

**Comment by BluSunrize** [comment]
Could have sworn we fixed that. Would have been a thingy of AABBs.

Try aiming for the mob's feet, that seemed to be one of the symptoms of the previous issue

**Comment by Zebaoth** [comment]
Projectiles fired from the Railgun also don't seem to damage the ender dragon.

**Comment by malte0811** [comment]
I'm looking into the Enderdragon issue, the dragon-healing-crystals are affected too.
