### ISSUE TITLE
last crash report

### ISSUE THREAD

**Issue by Kitty-Rea** [BluSunrize/ImmersiveEngineering#2418]
last i tried to load the game on 8-13-17 the game crashes. i checked the crash report and shows that there was a problem loading and rendering Immersive engineering. just wanted to bring this to attention. this is also for that latest update.

**Comment by mindforger** [comment]
>just wanted to bring this to attention

may i bring your attention to the missing crashreport(you mentioned it but now showing it to us) and to that contribution guidelines right above the window in which you typed your issue? :D

seriously now, please read the guidelines (you can find them in the base folder of the project) and update your bug report accordingly to give the devs the chance to solve this

**Comment by BluSunrize** [comment]
Closing this due to blatant disregard of how to do Crashreports.
