### ISSUE TITLE
GregTech power problem

### ISSUE THREAD

**Issue by fagnig** [BluSunrize/ImmersiveEngineering#242]
Using 4.1, GregTech 5 machines will infinitely discharge into wire connectors, even when there's nothing to fill on the other end
Is this something that could be fixed on your end, or will I have to find another workaround?

To reproduce, place two battery buffers, connect them with wire connectors, put a battery in the sending buffer and watch the battery plummet to zero.
Screenshot attached:
![2015-07-24_01 43 03](https://cloud.githubusercontent.com/assets/5938674/8864707/7ee82f92-31a5-11e5-8b15-6ec36cc508c2.png)

**Comment by BluSunrize** [comment]
I might have fixed this in IE 0.5.0 and higher. Gregtech is a bit tricky to work with, so I'm not sure if I can get it fully compatible .~.
