### ISSUE TITLE
Music

### ISSUE THREAD

**Issue by HappyPineapple** [BluSunrize/ImmersiveEngineering#2421]
I often turn off minecraft's defult music and would love an ie altertive so wdya say?

**Comment by kane-thornwyrd** [comment]
Do like me, make a modpack :)

**Comment by BluSunrize** [comment]
I mean... 
Here is one of my Spotify playlists I guess? 

https://open.spotify.com/user/blusunrize/playlist/6SOXmzjeVkcjnQ22CLTieD

That's *some* of the music I listen too, so I guess that'd be "IE music"? .-.

**Comment by mindforger** [comment]
is the ingame soundsystem capable of playing external streams in any way? like transcoding a livestream audiosource from the internet to something that the game could use to play ingame? an online radio to palce down and choose the audio source, definable via config

would make an awesome tool for streamers, they could let their songrequests and background music run over a local stream server, add it to the config and you can hear the music ingame over the radios and maybe some speakers with higher range

**Comment by BluSunrize** [comment]
Open Blocks used to have a radio that could hook into audio streams 

But what's the point? You can literally just open Spotify (or any other music app) in the background and use that.

**Comment by mindforger** [comment]
but tha immursionnnn :D

**Comment by HappyPineapple** [comment]
I agree with @mindforger , it would also be use full or servers.

**Comment by HappyPineapple** [comment]
@kane-thornwyrd How?

**Comment by mindforger** [comment]
@HappyPineapple what @kane-thornwyrd means, make yourself a resourcepack i think, you can change all music and textures via resourcepacks, but i fear there are limitations to the number of tracks ... hence why i asked for a stream input version :)
OpenFM Mod is available for 1.10 did not test yet but looks promising
(sorry @BluSunrize not ment as an advertisement but a valuable option imho)

**Comment by HappyPineapple** [comment]
thanks

**Comment by kane-thornwyrd** [comment]
The Ambiance mod is a good start

**Comment by XFactHD** [comment]
Vazkii also made a mod that plays MP3 files ingame but the sound is like any external MP3 player (no volume change with distance, etc.).

**Comment by HappyPineapple** [comment]
how about we make it a proximity alarm?

**Comment by BluSunrize** [comment]
Yeah we're off topic.

**Comment by HappyPineapple** [comment]
yep
