### ISSUE TITLE
better windmill power outputs

### ISSUE THREAD

**Issue by MX-wb** [BluSunrize/ImmersiveEngineering#2423]
Windmills in ie look really cool, but you never get to see them because they are above y200, and you just have giant poles going up to them and it looks really bad. I think power should be increased on lower y levels, because it ruins for people who like to make their bases decorative. Also, windmills irl are often placed in oceans, because there is lots of wind, so i think windmills in ie should have a bonus in ocean biomes.

My base is in mesa biome which is pretty high (y100), but to get the full potential of windmills, i have to make a giant pole going 100 blocks up :(

Also, i may be wrong, but windmills have a certain power gen value in different y ranges (eg 70-100 12rf, 101-150 15rf), surely it should gradually raise as you go higher, instead of being at a fixed rf/t no matter where you are in the range (like 71y 12rf, 99y 12rf). Im not sure if it already does this, but if not it should

**Comment by Zebaoth** [comment]
No idea when/how you tested this, but the windmill always puts out 10rf/t without sails and 34rf/t with full sails, no matter the altitude.
http://imgur.com/a/o0TNi

Tested with minecraft 1.12.1, forge 14.22.0.2452 and immersive engineering 0.12-70.

Anyway, you'd lose 50% of the windmills output when building them at 200+ going down to a level of ~70, using roughly 9 lv wire relays.

As far as windmills are currently:
Build a bit above ground
Build many
Upgrading to waterwheels/thermoelectric generators is just a few blaze kills away anyway
Just as it should be.

**Comment by malte0811** [comment]
@MX-wb seems to be using an fairly old version of IE, the height requirements was removed in a1be77b2e3e768b434d4efbf99f2041bcea5c581 (18th May, as part of the first 1.11 release). No, those changes will not be backported to 1.10 or below.
The power output will still be reduced if you have a lot of blocks (or, even worse, other windmills) in front of the windmill.
