### ISSUE TITLE
[Suggestion] Covered Vertical Conveyor Belt

### ISSUE THREAD

**Issue by Lukas45** [BluSunrize/ImmersiveEngineering#2427]
^Title.
Reasons:
You can still pick up items by accident if you have a tight area with Vertical Conveyor Belts.
It really breaks up the look/aesthetics if it goes from Covered Conveyor Belts to Vertical Conveyor Belts.

**Comment by HappyPineapple** [comment]
Yes definitely needed

**Comment by BrisingrAerowing** [comment]
This would be useful.

**Comment by BluSunrize** [comment]
Achieved by: https://github.com/BluSunrize/ImmersiveEngineering/commit/1a600c6496e87642decee215c7b0872f9e6b865a
