### ISSUE TITLE
Manual forgets it's place in 0.12-70 version

### ISSUE THREAD

**Issue by SummitSummit** [BluSunrize/ImmersiveEngineering#2429]
In version 0.10-61 the manual would remember the last page you were on when you closed it and reopened it.  This was exceptionally handy for getting together the parts, and then building the multiblock machines.  
In version 0.12-70 the manual always resets to the first page.  If this is configurable I couldn't find it in the in game configs nor the config file.

**Comment by BluSunrize** [comment]
Ahhh, right, yeah
I made the manual code less static fields, so that functionality probably got lost.
I'll look if I can find a way to bring that feature back ^^

**Comment by Lukas45** [comment]
It does remember where you last left (shown by NBT tags), it just doesn't re-open the page :)
Unless that was added by Immersive Petroleum to make it work with their Projector

**Comment by malte0811** [comment]
That's IP. https://github.com/Flaxbeard/ImmersivePetroleum/blob/master/src/main/java/flaxbeard/immersivepetroleum/common/network/CloseBookPacket.java
