### ISSUE TITLE
Bad texture sizing on some models; must be root of two for greater compatability

### ISSUE THREAD

**Issue by Ianaver** [BluSunrize/ImmersiveEngineering#243]
there are three items in this mod that don't show the texture, or atleast not the right texture; its all white! This issue is one where the GPU (texture MUST be a root of two to remain compatible with older PCs where the GPU buffer doesn't "fill" the image right on the model) see this comment by skyboy for more info:

https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/86#issuecomment-114513489

Edit: I looked through the texture files and you should also resize the machine textures too (multiblock)

Also here are screenshots of the three affected items:
![2015-07-23_19 05 36](https://cloud.githubusercontent.com/assets/8153290/8866296/8d9df912-316f-11e5-8561-3b9d90ba6a22.png)
![2015-07-23_19 05 34](https://cloud.githubusercontent.com/assets/8153290/8866298/8f6e3d4c-316f-11e5-8f3e-f01d7feb3dde.png)
![2015-07-23_19 05 32](https://cloud.githubusercontent.com/assets/8153290/8866299/90deae00-316f-11e5-8146-f33557a3bcbe.png)

**Comment by BluSunrize** [comment]
there you go, to be fixed in the next build

**Comment by Ianaver** [comment]
ok

**Comment by Ianaver** [comment]
well there's release 0.4.4 and no fix.... :(
