### ISSUE TITLE
[1.12] Rendering Issues

### ISSUE THREAD

**Issue by ProxyPlayerHD** [BluSunrize/ImmersiveEngineering#2430]
MC Version (in title)
IE Version: 0.12-70
No Resourcepack active
Tested with both Optifine and without. don#t have any other mods that effect Rendering

Some Textures are just invisible and some models are strangly dark on edges.
Invisible Textures are stuff like Scaffolding and Engineering Blocks, Example: [GIFV](https://i.gyazo.com/c7f275948e33e5eb5bdbcdfbf26a7578.mp4)

Dark Models are like Tanks or Silos, Example: [PNG](http://i.imgur.com/9BNhqtO.png)

**Comment by malte0811** [comment]
The first one is quite well known, see #2401. I've seen the second issue in my dev world, but never looked into it. It is probably caused by MC's renderer not expecting models greater than 1.5 blocks.

**Comment by BluSunrize** [comment]
Yeah search function would have found that :V

**Comment by ProxyPlayerHD** [comment]
i found nothing when searching...
