### ISSUE TITLE
Creosote Bucket Disappears

### ISSUE THREAD

**Issue by mgwerner** [BluSunrize/ImmersiveEngineering#2431]
1.12, Forge 2440, IE 0.12-70

Placing a bucket into the input of the coke oven results in the loss of the bucket, while the volume of fluid in the internal reservoir decreases as if a bucket were filled.

**Comment by BluSunrize** [comment]
modlist, forced crash?

**Comment by mgwerner** [comment]
No crash.

![image](https://user-images.githubusercontent.com/12369588/29485290-72a626ce-849d-11e7-8ffc-6fe144ae1656.png)

**Comment by BluSunrize** [comment]
Mate.
Read the contribution guidelines.
I *specifically* said debug crash. That means holding F3+C.

**Comment by mgwerner** [comment]
Glad to follow instructions, but have never seen guidelines.  I assumed forced crash was a question, as I do not know what that is.

**Comment by mgwerner** [comment]
When I hold F3+C nothing happens.

**Comment by BluSunrize** [comment]
![img](https://puu.sh/wSsTu/04a600749e.png)

>_>
<_<

**Comment by mindforger** [comment]
@mgwerner you have to be ingame not menu and press and **hold**

then the game will forcibly crash

**Comment by mgwerner** [comment]
OK, learn something new.  Here are the last two logs in my log folder, not sure which one you want.

No idea what screen you took the grab from, I have never seen that notice:

![image](https://user-images.githubusercontent.com/12369588/29486042-1287dedc-84ab-11e7-8c5d-2254fa0c736c.png)

![image](https://user-images.githubusercontent.com/12369588/29486043-1cb57b8a-84ab-11e7-8e1f-5818da121b7d.png)





[logs.zip](https://github.com/BluSunrize/ImmersiveEngineering/files/1236280/logs.zip)

**Comment by Lukas45** [comment]
Its from the New Issue screen
![8c8449330b9d3809b61b7d876e87bdd0 1](https://user-images.githubusercontent.com/4707702/29486109-b46425a2-84de-11e7-99a7-5c730d318a59.png)
Also can't replicate bug (Enigmatica 2 modpack)

**Comment by mgwerner** [comment]
It is not a modpack, but my own assemblage of mods.

I see the screen in question now.  Sorry about that, my screen was small and cut the top off when I opened it in tiles, to see the versions, etc. for the posting.

Here is the correct log:

[crash-2017-08-19_06.49.31-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1236289/crash-2017-08-19_06.49.31-client.txt)

**Comment by BluSunrize** [comment]
![img](http://puu.sh/xe10q/c136d9bae2.jpg)

I can't seem to replicate the issue, using a standard bucket.

**Comment by mgwerner** [comment]
What does that mean, binary search?

I also had the bug that was already reported of conveyors and trapdoors duplicating when making the dropping conveyor.  I thought they might be connected.

**Comment by mindforger** [comment]
just remove half the mods and Check if the bug disappear, so you always have half of no issue causing mods (0s) and a half which contains the issue cause (1s) hence the Name binary search. Continuo this with the malicious half until y ou find die culprit

**Comment by mgwerner** [comment]
OK, if I figure it out I will post back here.  Thanks for trying.

**Comment by mgwerner** [comment]
Well, stupid me.  I had placed hoppers under the coke furnaces, all of the filled buckets were there.

Sorry to have wasted your time.
