### ISSUE TITLE
Splitting Conveyor doesn't work at a specific case

### ISSUE THREAD

**Issue by Quarris** [BluSunrize/ImmersiveEngineering#2432]
MC: 1.12.1
Forge: 14.22.0.2455
IE: 0.12-70
Mod List: https://puu.sh/xfbJV/c5b84253d2.txt

I found a weird bug with splitting conveyors, and may happen to more of them. Everything works fine when placing the conveyors in the probably intended way like this.
http://prntscr.com/gaxttb
However if you attempt to place it on the side of a block it appears to be glitching out. May not be obvious at first but if you rotate it then it happens.
https://gyazo.com/33f46dc430f375365c609a89591715a3
Not entirely sure, but it appears as if it ignores the fact that it has been rotated.
I tried to do the same thing but after placing it I wouldn't rotate it, and instead made the same setup around the non rotated splitter and it was working fine.

**Comment by BluSunrize** [comment]
Valid issue, can replicate, will fix.
