### ISSUE TITLE
[1.12] Multiblock crash "exception in server tick loop at blusunrize.immersiveengineering.common.blocks.metal.TileEntityMultiblockMetal.isEnergyPos(TileEntityMultiblockMetal.java:135)"

### ISSUE THREAD

**Issue by Boundarybreaker** [BluSunrize/ImmersiveEngineering#2436]
I'm trying out the most recent version of Immersive Engineering today, and I added an addon called Immersive Tech. It has a few added multiblocks, and one of them was acting a bit funky.
![2017-08-23_23 04 19](https://user-images.githubusercontent.com/6722691/29651984-41964f96-8858-11e7-8e05-0a3f13d0bed5.png)

When I tried putting a Thermal Dynamics fluxduct on the power input (after I looked at the manual to see where on the multiblock's model the power input is), the game crashed. The crash log says it's a routine in Immersive Engineering with if isEnergyPos, so in case it's an issue on IE's side, I'm reporting it here. I've also reported it to the dev of Immersive Tech to see if it's their side. Here's the crash log.
[crash-2017-08-23_23.06.24-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1247900/crash-2017-08-23_23.06.24-server.txt)

**Comment by Boundarybreaker** [comment]
Important to note: all the blocks in the multiblock in question (the distiller) are base IE blocks. The tower right next to the mess of broken textures is a separate multiblock.

**Comment by mindforger** [comment]
link to the immersive tech reoprt would be nice, also you said "the most recent version of Immersive Engineering" ... please just simply write down the version used, as the "most recent" can be outdated the same day

no hard feelings, just a hint for future reports
:)

**Comment by Boundarybreaker** [comment]
[Here](https://github.com/FerroO2000/Immersive-Tech/issues/12) is the report for Immersive Tech (basically same as this one), and it's IE 0.12-71.

**Comment by malte0811** [comment]
This is on IT's side. The solar tower and possibly other MB's return null in getEnergyPos (as opposed to an empty array).

**Comment by BluSunrize** [comment]
>_>
