### ISSUE TITLE
Diesel Generator: can't attach lever + weird output behaviour

### ISSUE THREAD

**Issue by c727** [BluSunrize/ImmersiveEngineering#2437]
hi, thanks for this mod :)
2 things:
-I can't attach a lever to the bio diesel generator multiblock, other multiblocks are ok
-if I attach a HV wire to my generator I get 4k/t output, if I attach a HV and a LV I get 2k/t + 250/t. Imo the HV should have 4k-250 in this case

ImmersiveEngineering-0.12-71

**Comment by mindforger** [comment]
it's 4096 to be more precise!

**Comment by BluSunrize** [comment]
it will split it in half, that's just how it works.

**Comment by c727** [comment]
^lame
