### ISSUE TITLE
Items voided in crates and toolbox

### ISSUE THREAD

**Issue by CmdrFluffy** [BluSunrize/ImmersiveEngineering#2438]
I have noticed that recently items I leave in the toolbox or crates if left for longer than a few minutes they are voided, this has occurred since the latest update

**Comment by malte0811** [comment]
What version of IE are you using?

**Comment by Zebaoth** [comment]
Same here, opened toolbox (placed in hotbar) first time after updating to -71, put a few wires into it then when I needed to use those wires the entire toolbox was empty, everything gone. I'm mortified. :(

IE 0.12-71
Forge 1.12.1-14.22.0.2462
MC 1.12.1

**Comment by malte0811** [comment]
Confirmed for toolboxes, I'll look into fixing that right now. Crates seem to be fine though, @Zebaoth do they work for you? @CmdrFluffy There are a few maven builds where crates are broken, are you using a CurseForge build or one from Maven?

**Comment by CmdrFluffy** [comment]
I use the latest version from curse/twitch program

**Comment by CmdrFluffy** [comment]
I use the latest version from curse/twitch program

**Comment by CmdrFluffy** [comment]
And confirmed again, crates are doing the same as toolboxes, but only on crates that are harvested with items in it then re placed down,  the items then disappear shortly after, that I can tell

**Comment by malte0811** [comment]
I've fixed this, it was a really stupid mistake I made (I forgot that the default `getShareTag`-implementation returns a reference to the full item tag rather than a copy of it).

**Comment by CmdrFluffy** [comment]
when will the update be available for this fix?
