### ISSUE TITLE
[Tweak/Feature Request] Thermoelectric Generator Power Input

### ISSUE THREAD

**Issue by Zebaoth** [BluSunrize/ImmersiveEngineering#2439]
Could you please add a power input on the generators bottom side, so it will be possible to stack the generator?
As of now it takes quite some (horizontal) space if you want to have the same power output using lava and water to keep up with a triple watermill set up yielding 88rf/t.

It's a great source for RF and one tier below the diesel generator so it would be great if this item can be stacked for proper space usage.

Keeping the output limit at 256rf/t should be plenty so stacking more than 9 with water and lava as source would lead to a loss in rf produced.

**Comment by kane-thornwyrd** [comment]
Nice idea, my 2cts:
I'm using 5 TEG to power my whole base, including a refined storage network and a handful of garden cloches just by using uranium instead of lava, and packed ice asap.
When I require more power I build a diesel generator...

**Comment by Zebaoth** [comment]
Maybe diesel generator needs to be a bit more expensive since depending on how fast you grab ores you can build it within a few hours after getting the steel melting done and set up the needed squeezer/fermenter/refinery chain.
The recent garden cloche tweaks most likely help having to put in more effort to get the diesel generator going.

Regarding uranium and packed ice this also depends on the modpack or biome size you're running. Anything above biome size 5 makes it very unlikely that you'll ever run into ice spike biomes.

Packed ice isn't that big of a gain as you might think.

Gathering lava is a non issue since it's abundant in the nether, uranium does show up quite frequently and since it's currently not serving any other purpose it's replacing lava wherever I can.

That leaves you with lava/water for most TGs/at the beginning, putting out 29rf/tick for both sides.
Uranium/water is usually the next step increasing output with 2 sides to 39rf/t, quite significant.
Uranium/packed ice is only a minor increase with 2 sides generating 41rf/t.
Even with 20 TGs the difference is a mere 40rf/t between uranium/water and uranium/packed ice.

Might as well build 21 TGs with uranium/water.

**Comment by kane-thornwyrd** [comment]
My point was that you shouldn't need that many TEGs and if you require more power you simply have to invest in the diesel gen, which cover any need you could have, given your modpack is balanced.

**Comment by BluSunrize** [comment]
I'M not going to make the TEGs transmit power through eachother, I'm afraid you'll have to settle for singular hookups, at the cost of some floor space.

**Comment by BrianEdmonds** [comment]
> ... at the cost of some floor space.

Last time I built a TEG array it was in a wall. Quite attractive with
glass in front of the lava blocks. :)
