### ISSUE TITLE
[Suggestion] Config for Disabling Multiblocks

### ISSUE THREAD

**Issue by Voxel-Friend** [BluSunrize/ImmersiveEngineering#244]
Title says it all. Reason is to help modpack authors fine tune the way they want the progression to feel. Example: Using IE's RF generation and transmission, but using something like RC's crusher and disabling IE's.

**Comment by BluSunrize** [comment]
The mutliblocks are a core feature. That's like asking Thaumcraft to remove Aura Nodes.
If they really are that much of a bother, disable the recipes for its component blocks.
