### ISSUE TITLE
[1.7.10]NEI related crash for Metal Press Minetweaker Scripts - 2 

### ISSUE THREAD

**Issue by cheesealmighty** [BluSunrize/ImmersiveEngineering#2440]
Similar to #940

Client crashes on recipe lookup on NEI for tweaked metal press recipes. Only happens with recipes with ore dictionary entries.

Game ver: 1.7.10
Forge ver: 10.13.4.1614
IE ver: 0.7.7

Crashlog - Line 2854 for the crash - https://paste.ubuntu.com/25389049/

Related minetweaker script: https://paste.ubuntu.com/25389063/

Modlist: https://paste.ubuntu.com/25389076/

---------------------------------
Changing to this script works: https://paste.ubuntu.com/25389137/

**Comment by malte0811** [comment]
1.7.10 is not supported any more and it hasn't been since roughly May 2016. But I'd guess there's a typo in one of the ore names.
