### ISSUE TITLE
Arc Furnace Reicpe Generator

### ISSUE THREAD

**Issue by RainbowSaber** [BluSunrize/ImmersiveEngineering#2442]
IE generates an Arc Furnace recipe: ore:oreDiamond -> ore:ingotDiamond

ore:ingotDiamond is currently used by BetterWithMods, which features a more complex crafting recipe to transform minecraft:diamond into ore:ingotDiamond.

Diamond doubling, while bypassing a crafting step does not seem to be intended behaviour and should most likely be removed for that special case.

**Comment by BluSunrize** [comment]
tbf, who would expect someone to add a damn diamond ingot? Doesn't make much sense tbh. >_>

IE has crafttweaker compat for weird edgecases like this.

**Comment by KnightMiner** [comment]
I'd argue if Better With Mods adds a diamond ingot recipe which costs more than diamond ore, they should add a different oredict name as dynamic recipes like this are quite common.

**Comment by BluSunrize** [comment]
^ this :v
