### ISSUE TITLE
The Engineer's toolbox delets all the items

### ISSUE THREAD

**Issue by SupremeDracoI** [BluSunrize/ImmersiveEngineering#2444]
After the latest update,the toolbox isn't working anymore. This is one of the biggest and most annoying bugs.

**Comment by malte0811** [comment]
Duplicate of  #2438, fixed for the next release. Please read the contributing guidelines before your next bug report.

**Comment by mindforger** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/2438
... just use the search next time please ;) and don't forget it may already be closed and fixed .. just not yet compiled and post versions used next time like described in the contribution guidelines
