### ISSUE TITLE
[0.71|1.12.1] Strip Curtain Strong Power output gets (sort of) stuck at high

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#2445]
See this example:
![stuckpiston](https://user-images.githubusercontent.com/7753414/29779938-5d7ea00e-8c14-11e7-8554-755bdb0cac5e.png)

The grass block doesn't seem to inform the surrounding blocks that its power dropped to 0 again. When you update it by i.e. placing another block against the grass block, the power output gets correctly recognized as 0 again.
At least that's my best guess, I am too unfamiliar with the inner workings of redstone, but some kind of block update is missing.

IE 0.71
Forge x2463
MC 1.12.1

**Comment by BrisingrAerowing** [comment]
You are correct with the block updating issue, the strip curtain (likely unintentionally) creates a BUD switch.
