### ISSUE TITLE
Latest Immersive Engineering causing Texture Errors

### ISSUE THREAD

**Issue by mcfilmmakers** [BluSunrize/ImmersiveEngineering#2446]
No other mods installed, running forge 2463.

[https://pastebin.com/2QuxjSSq](https://pastebin.com/2QuxjSSq)

**Comment by mindforger** [comment]
"Latest" is always bad, why don't you simply write the version of IE used?
Latest can be a newer version already as we speak!

**Comment by mcfilmmakers** [comment]
Fair enough. Version 71.

**Comment by BluSunrize** [comment]
Ehh, none of those are crucial errors, it's just Forge being rather sensitive =P

**Comment by mcfilmmakers** [comment]
Eve wot out of 300 mods in 1.12.1, it only happens with yours and 5 others. It may not be a crucial Erie, but it is one nonetheless and a non textured block is a huge visual problem nonetheless.

**Comment by mcfilmmakers** [comment]
Ugh, damn autocorrect. Erie = error. Ignore the rest of the typos.

**Comment by BluSunrize** [comment]
Do you see any non-textured block in the game? >_>
These are errors for blockstates you can'T even access in the game. That's why I ignored them.

**Comment by mcfilmmakers** [comment]
Oh okay then. Hey figured it's best to report than to ignore is all.

**Comment by BluSunrize** [comment]
Nothing wrong with reports!
And if you find any actual ingame issues, please always let us know. But log spam is, while annoying, generally non-critical (unless it's OpenGL underflows. That's very critical. Never ignore those. x3)
