### ISSUE TITLE
IE crashes Graphics driver when paired with tinkers construct 

### ISSUE THREAD

**Issue by Miner94** [BluSunrize/ImmersiveEngineering#2447]
i can switch between either or but i cant play both at once this is the first time ive had this issue and i cant figure out whats causing it

**Comment by malte0811** [comment]
What exactly do you mean by "crashes graphics driver"? And what versions of IE, TiC and MC do you use?

**Comment by Miner94** [comment]
i mean my graphic card crashes and the computer has to restart it 
and im using IE version 0.10-61
Tinkers version 1.10.2-2.6.5
MC version 1.10.2

**Comment by Zebaoth** [comment]
Try updating your stuff.

**Comment by BluSunrize** [comment]
Hold F3+C and provide a debug crash.

**Comment by Miner94** [comment]
if and when i get it to generate where do i put it

**Comment by Miner94** [comment]
Never mind nothing is even happening

**Comment by BluSunrize** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/blob/master/CONTRIBUTING.md

Read. That.
And then do it *properly*.

**Comment by Miner94** [comment]
Well you see id gladly do that if the game was crashing 
but the game is not crashing and no crash report is generated

**Comment by Miner94** [comment]
it happens on texture and MipMap upload for the revolver

**Comment by BluSunrize** [comment]
Are you able to get Ingame? 
Also, system specs. If your GPU driver is crashing at least say what gpu you are using. 
You need to provide info if you want help, damnit

**Comment by Miner94** [comment]
NO im not able to get in game 
The GPU im using is AMD A10-5750 APU With Radeon HD Graphics

**Comment by BluSunrize** [comment]
So it's a laptop CPU with integrated graphics.
Yeah that sounds alright to crash then. Make sure to update your drivers to latest I guess? Otherwise I can't help you. If there is no actual GPU error logs you can provide, then there's nothing to even give us a hint of what to do.

**Comment by AEnterprise** [comment]
if you can't get into the game maybe try turning off the forge loading screen, that sometimes helps

**Comment by Miner94** [comment]
how do i turn off the forge loading screen

**Comment by AEnterprise** [comment]
set enabled to false in the splash.properties file in your config folder
