### ISSUE TITLE
Coke Oven filling <insert fluid container here> by a little amount only.

### ISSUE THREAD

**Issue by Lion4K** [BluSunrize/ImmersiveEngineering#2450]
In this Picture I've used IC2 Universal Fluid Cells, but the same happens with all other fluid storage solutions, including Pressure Pipes's Canisters, Ender-Utilities's Ender Bucket, and so on.

http://prntscr.com/ger3xj

**Comment by BluSunrize** [comment]
It uses anything in the tank. If there is only 500 in the tank, it will only put 500 in the cell.
If you use a bucket it works differently, because buckets only allow being filled by 1000 or more. But universal fluid cells accept *any* amount.

**Comment by Lion4K** [comment]
Still, when you have 1 cell in the slot it will be kept filled until it reaches 1B and then the cell falls to the output slot, or if you have a stack of empty cells, the tank will hold the fluid until there 1B, at least that how every other thing that uses fluids behaves.

**Comment by MalkContent** [comment]
I don't know how the cells work, but can't you reinsert them until you got them filled to the level you require?

I'll tag on that you can't manually (via gui) insert non-empty, non-full jerry cans with creosote oil into the input slot, but inserting them automatically (i.e. hoppers) works.

**Comment by Lion4K** [comment]
Yes, them cannot be re-inserted in the over via its GUI. Idk about hoppers thou.

**Comment by MalkContent** [comment]
give it a try then. when in doubt you can always pump the oil out of the oven and into a machine that is more qualified for filling liquid containers.

**Comment by Lion4K** [comment]
Gonna test with Pressure Pipes mod.

**Comment by Lion4K** [comment]
It works, I know can get all the oil straight to the Drum.

![image](https://user-images.githubusercontent.com/10391955/29876943-92c9c03e-8d74-11e7-8291-3b33ed6ca1f6.png)

**Comment by MalkContent** [comment]
And here i thought your goal was putting it into canisters ^^

**Comment by Lion4K** [comment]
It was, but you gave me the idea of using external pumps so i've figure i should extract to the drum already, since I would end up putting the surplus on said drum.

**Comment by BluSunrize** [comment]
I mean you can just IE's pipes. They absolutely work as well (and look better) :V

the reason partially-filled containers can't be reinserted is that I was checking for empty containers, but I guess I could change that?
I definitely can't "hold" them in the slot though, because if you put a full stack of empty containers in there, I need to single one of them out to fill.

**Comment by Lion4K** [comment]
Good Idea on the Native piping, thou I need to learn how to use them, unlike IC2 I couldn't find some "first steps" guide on how to get things going, so most of the assets on the mod I don't even know its there.
Y'know, if you don't know they exist you don't go looking for them. I mean, I sure see the pump, compared to IC2 they have a better pumping system, they usually pump out the whole column, but compared to Ranged Pumps, well, not so much.

**Comment by MalkContent** [comment]
@BluSunrize as far as i could tell you are only allowing empty/partially-filled containers to be inserted by non-gui. Just ~~copy~~ use that check I guess? :x
