### ISSUE TITLE
Graphical issue scaffold on pipes.

### ISSUE THREAD

**Issue by Wolfguard94** [BluSunrize/ImmersiveEngineering#2452]
I am currently running a custom modpack that uses IE version 0.12-71. Whenever I try to put put any scaffold onto a fluid pipe block, the scaffold does not display but the pipe does continue to display. I hope that that can you can fix that.

BTW great mod, I love it.

**Comment by Wolfguard94** [comment]
Also, it would be nice to have the HV Transformer be able to mount to the side of poles, but I can see why not to do so as this is an immersion mod and the HV Transformer would be too heavy to mount onto a pole. But just a thought.

**Comment by BluSunrize** [comment]
Pictures, crashlog. Read the debug guidelines. 
And HV transformers won't go on posts, that's a design decision.

**Comment by BluSunrize** [comment]
Any more input on this? I'd need to see pictures of the issue and modlist, as well as information on use of Optifine or a resource pack. Otherwise I'll close this on lack of info.

**Comment by darkshadow543** [comment]
No, it is not an optifine bug, but I can confirm.  Also, I was in creative and right clicking on the pipe removed it from my inventory.  I am playing with minecraft 1.12.1, IE Version: 0.12-71 Forge: 14.22.0.2474
![2017-09-09_12 15 35](https://user-images.githubusercontent.com/14943673/30241831-1155a44a-9559-11e7-890f-0db8e247871d.png)
![2017-09-09_12 15 37](https://user-images.githubusercontent.com/14943673/30241833-15b3c198-9559-11e7-84bf-dac1b17eaa42.png)

**Comment by Wolfguard94** [comment]
My modpack does not have optifine so let me get the modlist real fast

**Comment by BluSunrize** [comment]
![image](http://puu.sh/xvwJm/59f2320841.png)

I legitimately can't replicate it :V
And the CT integration is (partially) documented on the Minetweaker wiki.

**Comment by darkshadow543** [comment]
https://youtu.be/JUxYofemn9Q
I reproduced it for you on a video, tell me if you want to see the pack.

**Comment by Wolfguard94** [comment]
Abyssalcraft 1.12-1.9.4
Applied Energistics 2-rv5
Astral Sorcery 1.12-1.6.1
Better Builder's Wands 1.12-0.11.1.245+69d0d70
BetterFps 1.4.6
BiomesOPlenty-1.12-7.0.0.2291
Chameleon 1.12-4.1.3
Chicken Chunks 1.12-2.4.0.70
Chisel MC1.12-0.0.13
Chisel & Bits 14.6
CodeChicken Lib 1.12-3.1.2.297
ConnectedTexturesMod 1.12-0.2.2.7
Cucumber 1.12-1.0.0
Davincis Vessels 1.12-5.335
Ender Storage 1.12-2.4.0.122
Extra Utilities 2-1.12-1.6
Fast Leaf Decay v13
Gravestone 1.8.4
Immersive Engineering 0.12-71
Inventory Tweaks 1.63+beta.107
Iron Chests 1.12-7.0.31.818
JourneyMap 1.12-5.5.0b3
JEHC 1.12-1.3.0
JEI 1.12.1-4.7.8.92
MalisisCore 1.12-6.0.4
MalisisDoors 1.12-7.0.4
Mantle 1.12-1.3.1.21
Moving World 1.12-5.341
Natura 1.12-4.3.0.17
Pam's Harvestcraft 1.12.1b
Simple Biome Compass 0.1
Storage Drawers 1.12.1-5.3.0
Storage Drawers Extras 1.12-3.1.0
The One Probe 1.12-1.4.18
Tinkers Construct 1.12-2.7.2.19
Veinminer 1.12-0.38.1.639+134fb1e
Waystones 1.12-4.0.15

**Comment by Wolfguard94** [comment]
THe ones I could see confilcting the most would be better fps or the connected textures mod

**Comment by Wolfguard94** [comment]
[Wolfguard94 Minimalist-1.4.zip](https://github.com/BluSunrize/ImmersiveEngineering/files/1289928/Wolfguard94.Minimalist-1.4.zip)
And this the modpack I just listed for the Twitch Launcher

**Comment by darkshadow543** [comment]
Actually now that you mention it.  There was some weird shading with some of the blocks, I'm going to try deleting better FPS.

**Comment by Wolfguard94** [comment]
![2017-09-09_10 44 04](https://user-images.githubusercontent.com/31499871/30242022-d7c43154-954b-11e7-8275-0685e7f1668b.png)
Picture of pipes with each type of scaffold on them

**Comment by BluSunrize** [comment]
Oh, it could indeed be CTM...
Wooden scaffolds are the only ones not using it. I'll take a look.

**Comment by darkshadow543** [comment]
That could also explain the weird shading on engineering and other connected texture Blocks

**Comment by Wolfguard94** [comment]
I just checked by turning off CTM and that didn't fix it. I'm going to try with BetterFPS off now.
