### ISSUE TITLE
[1.10.2][Server][FTB Beyond] Diesel Generators seems not producing power when i log off.

### ISSUE THREAD

**Issue by cap1o** [BluSunrize/ImmersiveEngineering#2454]
Hi, 

I have a issue that i can't fix with the Diesel Generators. Every times i log off and let the chunkload in every zone should work without me, when i come back, RF ran out, diesel generator have to be off and on to work and produce again RF.
So all the production of diesel is with Thermal Expansion energy.
Diesel Barrels are empty every time i log on and fill up when i load my self the zone.
i don't understand where is the issue.
If someone can help me plz.
Or I will have to change and use another mod to produce RF.
Thank you.

PS :
_[ErderIO][Immersive Engineering] and [Flux Network] are use on the system RF produce.
They are Updated to last version.
No log is appearing.
The diesel Generators are on a different dimension than diesel produce._

**Comment by BluSunrize** [comment]
Pictures of the setup, modlist, forced crashlog.
Read the contribution guidelines please.

**Comment by cap1o** [comment]
I don't find out on logs any line about the problem.
I have read the contribution guidelines of course but it's hard to define the problem.

As you can see on pics, the Ender IO Energy Bank is empty when i log on, and receive RF energy with out troubles and get empty after i log off from the server.


**Overworld chunkloaded :**
Farming production : Immersive Engineering
Fuel Produce : Immersive Engineering

**Void World chunkloaded** 
RF Produce : Immersive Engineering
RF Storage and conduits : Ender IO
RF network distribution : Flux Network

Almost mods are updated to the last version for MC 1.10.2 :
[FTB BEYOND 1.10.2 Mod List](http://modlister.com/user/Quetzi/FTB%20Beyond)
**Immersive  Engineering** updated to 0.10.61
**Ender IO** updated to 1.5.2
**Flux Network** updated to 1.2.5

![2017-09-02_11 31 08](https://user-images.githubusercontent.com/29143461/29994664-1e0033ec-8fd5-11e7-9bbd-8577cd54bbf3.png)
![2017-09-02_11 32 42](https://user-images.githubusercontent.com/29143461/29994665-1e064b24-8fd5-11e7-8584-04dd5bde0dc9.png)
