### ISSUE TITLE
Breaking a block in the Alloy Kiln destroys its contents

### ISSUE THREAD

**Issue by The-Fireplace** [BluSunrize/ImmersiveEngineering#2455]
If you have an Alloy Kiln, and have items stored in it, breaking it doesn't drop its contents, it destroys them.
To reproduce:
1.) Build an Alloy Kiln
2.) Store items in the Alloy Kiln
3.) Break a block in the Alloy Kiln

Minecraft 1.12.1
IE 0.12-71
Forge 14.22.0.2467
Tested in singleplayer and on a dedicated server.

**Comment by raphydaphy** [comment]
Same happens for blast furnace in 0.10-61 (1.10)
