### ISSUE TITLE
Breaking a block in an Alloy Kiln drops the block in Creative

### ISSUE THREAD

**Issue by The-Fireplace** [BluSunrize/ImmersiveEngineering#2456]
If you have an Alloy Kiln, and break one of the blocks in Creative, that block drops.
To reproduce:
1.) Build an Alloy Kiln
2.) Be in Creative Mode
3.) Break a block in the Alloy Kiln

Minecraft 1.12.1
IE 0.12-71
Forge 14.22.0.2467
Tested in singleplayer.

**Comment by PrincessRTFM** [comment]
This happened with all IE multiblocks in 1.7.10. Is it now just the Alloy Kiln?

**Comment by The-Fireplace** [comment]
I haven't tested with any other multibloxk, so I couldn't tell you.

**Comment by BrisingrAerowing** [comment]
It does happen with all multiblocks. I often have to relocate machines to other places, so I get this quite a bit.

**Comment by BluSunrize** [comment]
It happens with all of them, but it only happens in creative so it really doesn't matter.
People who play normally are unaffected.

**Comment by The-Fireplace** [comment]
By that logic, you may as well remove your creative tab. After all, it
wouldn't affect people who play normally. Seriously, I feel like a simple
if(!player.isCreative()) put somewhere would fix this. Is it not that
simple?
