### ISSUE TITLE
The Alloy Kiln's burn time stops going down when it stops making alloys.

### ISSUE THREAD

**Issue by The-Fireplace** [BluSunrize/ImmersiveEngineering#2457]
If you have an Alloy Kiln, and make some alloys in it without using all of the currently burning fuel item, the item stops burning.
To reproduce:
1.) Build an Alloy Kiln
2.) Make an alloy in it using a larger fuel source than needed. Ex. Alloy 1 Gold + 1 Silver using a Coal Block as fuel
3.) After the alloying process completes, the fuel stops burning.

Minecraft 1.12.1
IE 0.12-71
Forge 14.22.0.2467
Tested in singleplayer and on a dedicated server.

**Comment by EvilCooky** [comment]
I think that's intended.
The Blast Furnace works the same way

**Comment by The-Fireplace** [comment]
If it is intended, it should be a config option. I would rather the fuels
burn away than what it currently does.

**Comment by mindforger** [comment]
i kind of think this would make sense for all burning apperatus as it is vanilla behaviour and you should check that you have enough stuff to burn through one piece of fuel efficiently
