### ISSUE TITLE
Immersive Engineering recipes cannot be removed with Crafttweaker.

### ISSUE THREAD

**Issue by LawfulGremlin** [BluSunrize/ImmersiveEngineering#2458]
Immersive Engineering registers its recipes after Crafttweaker. Because of this, Crafttweaker cannot remove recipes from Immersive Engineering (for example metal press recipes).

Issue is present with the following, relevant mods:
Forge-1.12.1-14.22.0.2460
CraftTweaker2-1.12-4.0.4
Modtweaker-4.0.1
ImmersiveEngineering-0.12-71

Possibly a duplicate of https://github.com/BluSunrize/ImmersiveEngineering/issues/2394.

(Specific case where it is not working: https://www.reddit.com/r/feedthebeast/comments/6xkje1/how_do_i_remove_recipes_from_immersive/ )
(Another Reddit thread mentioning the problem: https://www.reddit.com/r/feedthebeast/comments/6w50v1/unable_to_remove_recipe_from_ie_with_crafttweaker/)

**Comment by BluSunrize** [comment]
@jaredlll08 you wanted a ping to an issue report on this, didn't you?

I set up my recipes in Init, should I be using preInit instead?

**Comment by jaredlll08** [comment]
@BluSunrize well we remove recipes in postinit... but yea, you *should* be using the recipe event

**Comment by BluSunrize** [comment]
Oh there's an event?
>_>
<_<

**Comment by jaredlll08** [comment]
Yea >.>
```java
 @SubscribeEvent
    public void onRegistryRegister(RegistryEvent.Register<IRecipe> event) {
    }
```

**Comment by BluSunrize** [comment]
already on it =P

**Comment by BluSunrize** [comment]
[This](https://github.com/BluSunrize/ImmersiveEngineering/commit/7b5ec57ce78105b717aed63b549b1060c8caf2e2) commit might do the trick?

Please try this Jenkins build:
http://teamacronymcoders.com:8080/job/ImmersiveEngineering/233/
And see if it works with that.

**Comment by LawfulGremlin** [comment]
The commit works for metal press recipes, they can now be changed with Crafttweaker. I would assume this extends to all other recipes from the mod due to the nature of the fix.

The following two scripts have been tested separately to work with Crafttweaker:
mods.immersiveengineering.MetalPress.removeRecipe(<techreborn:plates:23>);
mods.immersiveengineering.MetalPress.removeRecipe(<techreborn:plates:0>);

Relevant mods that were used during the test:
Forge-1.12.1-14.22.0.2460
CraftTweaker2-1.12-4.0.4
Modtweaker-4.0.1
ImmersiveEngineering-0.12-71-233

**Comment by BluSunrize** [comment]
It should (in theory) work with all others.
I myself tried removing the crafting recipes for the molds, and that worked.

**Comment by LawfulGremlin** [comment]
If you would like a more extensive test before considering the issue closed, I would not mind testing recipes for the other machines, but I would assume that is not necessary because of the way the issue has been fixed.

Since there is no documentation about Immersive Engineering in the Crafttweaker documents, I have been going by the old MineTweaker 3 documentation. Forgive me for asking in this issue, but is support for recipe changes provided by Immersive Engineering? If yes, is there documentation for it somewhere? I have been unable to find any but the old MineTweaker 3 documentation.

**Comment by BluSunrize** [comment]
The methods have barely changed, I was able to port the majority of the MT module over.
The reason there is no updated documentation is because noone wrote any and I myself am entirely too lazy to do so =P

**Comment by LawfulGremlin** [comment]
Thank you for explaining that. I have one last question in that case. I would assume all Crafttweaker integration is located in "ImmersiveEngineering-master\src\main\java\blusunrize\immersiveengineering\common\util\compat\crafttweaker"? I might be able figure out how to use each handler for the different machines from this. Is there anything additional I have to keep in mind? :)

Having asked that, I think the 71-233 build solved both this issue and https://github.com/BluSunrize/ImmersiveEngineering/issues/2394.

**Comment by BluSunrize** [comment]
yep, all stuff is contained in that package, and the only things "relevant" to you is the methods that are marked as @ZenMethod as only they are available in MT/CT.
So with them, their names and their parameters, you should be able to figure out how stuff works (hopefully)

I'll close this issue as it's resolved now.
