### ISSUE TITLE
[Feature Request]Speedloaders

### ISSUE THREAD

**Issue by EvilCooky** [BluSunrize/ImmersiveEngineering#2459]
I would like to request a feature for the revolver speedloaders.

Each Speedloader can hold 8 bullets. That's exactly the number of slots you have in a crafting grid when when you put the speadloader in the middle.

It would be nice if you could simply put the bullets into the crafting grid with the loader and they would fill into the loader when crafting. This would enable us, to automatically fill speedloaders so the player only has to pick them up.

Also, a visiul indication on the item that tells us if bullets are inside of it or not would be nice.

**Comment by mindforger** [comment]
you could probably add this recipe yourself using crafttweaker ...  but i also like the idea to be present by defautl :)

**Comment by BluSunrize** [comment]
Not a bad idea tbh, I'll look into it.

**Comment by BluSunrize** [comment]
@malte0811 only vaguely related to this, the HUD display for the speedloader doesn't show its bullets.
I believe it's related to the NBT share tag thingy, but I wasn't able to fully debug it (I might just be too tired)
Got any spontaneous idea?

**Comment by malte0811** [comment]
Try replacing `ItemSpeedloader#isEmpty` with `ItemRevolver#isEmpty`. If that doesn't work I'll take a look either later today or tomorrow.
