### ISSUE TITLE
[1.12] Floodlights keep glowing after being turned off

### ISSUE THREAD

**Issue by ProxyPlayerHD** [BluSunrize/ImmersiveEngineering#2460]
Title says it.
Forge: 2443
IE: 0.12-71

it makes buildings look weird.
On, works fine.
![2017-09-02_16 31 26](https://user-images.githubusercontent.com/13576843/29996311-c6660ef4-8ffc-11e7-90f8-defdc0fa322b.png)
but when turning off it needs like 10 seconds to turn off and then the Floodlight block itself will stay glowing.
![2017-09-02_16 31 46](https://user-images.githubusercontent.com/13576843/29996319-ec792036-8ffc-11e7-8481-f3d91a11f239.png)

**Comment by BluSunrize** [comment]
I'm finding myself unable to replicate this.

Does it happen with floodlights on the ground pointing horizontally as well?

**Comment by ProxyPlayerHD** [comment]
i did not try it Horizontally, imma try it now.

yep, also happens with Horizontal.
![2017-09-05_19 07 42](https://user-images.githubusercontent.com/13576843/30073285-86e90a24-926d-11e7-8b11-4d477f2d97a6.png)

Relogging doesn't fix it either.

and removing Optifine also did not fix it.

uh, and while texting this happend
![2017-09-05_19 11 15](https://user-images.githubusercontent.com/13576843/30073425-08225d84-926e-11e7-80e1-7308b9051599.png)

**Comment by BluSunrize** [comment]
I mean, the fact that you had to even remove Optifine means you had it in the first place which kinda made this issue irrelevant.
Plus you know, no modlist, debug crash and stuff.

**Comment by ProxyPlayerHD** [comment]
why irrelevent if removing optifine did not remove the bug?

and heres the mod list [PNG](https://i.gyazo.com/b4125c8743ee89c124c645b802e101a3.png)

**Comment by BluSunrize** [comment]
Can you reliably reproduce this with just IE and Forge?

**Comment by ProxyPlayerHD** [comment]
with only forge and IE it doesn't happen. so it has to be another mod that causes this.

only one i could think of would be optifine, but as stated before, removing optifine didn't fix it either.
and i also had Optifine installed with only IE and Forge, and the bug was not there.

**Comment by Paul17041993** [comment]
(necro as a means of closure)
Was coloured lighting enabled in quark? if not does it still occur with quark installed?

**Comment by ProxyPlayerHD** [comment]
i didn't even know quark existed 2 years ago

just let it die

**Comment by Paul17041993** [comment]
it's in your modlist

but anyway @BluSunrize , can be closed as I don't think this is an issue any more from my experience.

**Comment by ProxyPlayerHD** [comment]
i don't really remember what was in my modlist so long ago.
