### ISSUE TITLE
Immersive Engineering BotaniaHelper NullPointerException

### ISSUE THREAD

**Issue by MinecraftPlaye** [BluSunrize/ImmersiveEngineering#2461]
I noticed the following log entry in my latest log using an dedicated server.
The log entry appeared before the world loads when the server is started.

> [22:18:59] [Immersive Engineering Contributors Name Finder Thread/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@710ba71d[id=48a16fc8-bc1f-4e72-84e9-7ec73b7d8ea1,name=<null>,properties={},legacy=false]
> com.mojang.authlib.exceptions.AuthenticationException: The server encountered an unexpected condition which prevented it from fulfilling the request
> 	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:79) ~[YggdrasilAuthenticationService.class:?]
> 	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:180) [YggdrasilMinecraftSessionService.class:?]
> 	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService$1.load(YggdrasilMinecraftSessionService.java:60) [YggdrasilMinecraftSessionService$1.class:?]
> 	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService$1.load(YggdrasilMinecraftSessionService.java:57) [YggdrasilMinecraftSessionService$1.class:?]
> 	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3524) [minecraft_server.1.11.2.jar:?]
> 	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2317) [minecraft_server.1.11.2.jar:?]
> 	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280) [minecraft_server.1.11.2.jar:?]
> 	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195) [minecraft_server.1.11.2.jar:?]
> 	at com.google.common.cache.LocalCache.get(LocalCache.java:3934) [minecraft_server.1.11.2.jar:?]
> 	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938) [minecraft_server.1.11.2.jar:?]
> 	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821) [minecraft_server.1.11.2.jar:?]
> 	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4827) [minecraft_server.1.11.2.jar:?]
> 	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:170) [YggdrasilMinecraftSessionService.class:?]
> 	at blusunrize.immersiveengineering.common.CommonProxy.getNameFromUUID(CommonProxy.java:193) [CommonProxy.class:?]
> 	at blusunrize.immersiveengineering.common.util.compat.BotaniaHelper$ThreadContributorToNameFormatter.run(BotaniaHelper.java:119) [BotaniaHelper$ThreadContributorToNameFormatter.class:?]
> [22:18:59] [Immersive Engineering Contributors Name Finder Thread/INFO]: [STDERR]: java.lang.NullPointerException
> [22:18:59] [Immersive Engineering Contributors Name Finder Thread/INFO]: [STDERR]: 	at blusunrize.immersiveengineering.common.util.compat.BotaniaHelper$ThreadContributorToNameFormatter.run(BotaniaHelper.java:119)

Minecraft 1.11.2
Forge Mod Loader version 13.20.1.2454
ImmersiveEngineering-0.11-63
Botania r1.9-345

**Comment by BluSunrize** [comment]
It doesn't actually crash, does it?
It runs in a separate thread so it shouldn't impact gameplay. Probably just means your tiny potatoes won't hold revolvers when you name them. I should disable that feature anyway.

**Comment by MinecraftPlaye** [comment]
> It doesn't actually crash, does it?
No, it doesn't crash. It just shows this message on server startup and after that everything runs normal so far.
