### ISSUE TITLE
Revolver Texture Bug

### ISSUE THREAD

**Issue by sirNacati** [BluSunrize/ImmersiveEngineering#2462]
The Revolver Bugs its awesome model if using Optifine and the shaders are enabled.. =/
![2017-09-03_00 59 30](https://user-images.githubusercontent.com/29883152/29999510-3a5a257a-9043-11e7-81bc-cf6bccf8d3cb.png)

**Comment by BluSunrize** [comment]
Optifine isn't supported, read the contribution guidelines.

**Comment by sirNacati** [comment]
Just read them now, didn't know sorry.. 

But small update, its not optifine that bugs the revolver its using any type of shaders.

**Comment by BluSunrize** [comment]
Doesn't make a difference to me. They are optifine based, as such I can't do anything about it.

**Comment by sirNacati** [comment]
Damn.. ohh well guess i'm playing without shaders xD
