### ISSUE TITLE
Not compatible with JEI

### ISSUE THREAD

**Issue by EliSauder** [BluSunrize/ImmersiveEngineering#2463]
I am creating a mod pack and I would like to use Immersive Engineering but i am unable to use it with JEI for (according to one of the issues on the JEI site) Immersive Engineering is coded so it says it should be loaded before JEI which creates a sorting cycle error. Please fix this problem I rly love this mod.

**Comment by malte0811** [comment]
IE is definitely compatible with JEI, just about any modpack proves that. Could you a) provide the information requested in the contributing guidelines (there's a link when you create a new issue) and b) post a link to the JEI issue?

**Comment by EliSauder** [comment]
https://github.com/mezz/JustEnoughItems/issues/659

**Comment by BluSunrize** [comment]
That's Minecraft 1.10 and the report is 9 months old.
It's also something I have not seen reported ever before.

Could you please provide a current screenshot of you experiencing this issue right now? Also please use the latest possible version of Forge, IE and JEI and provide a full and versioned modlist.

**Comment by EliSauder** [comment]
![screen shot 2017-09-03 at 10 13 03 am](https://user-images.githubusercontent.com/24995216/30005130-9013e792-9090-11e7-9f70-acde0751f0c7.png)

**Comment by EliSauder** [comment]
I am using Forge 1.10.2-12.18.3.2422

IE: 0.10-50
JEI: 1.10.2-3.14.7.419 (lemme work on the mod list)

**Comment by EliSauder** [comment]
These are the mods i currently have in, i am planning on adding more but I've been debugging so not all of them are included. (this list does not have IE or JEI since I gave the versions above)

industrialcraft-2-2.6.252-ex110
Bookshelf-1.10.2-1.4.4.347
ExtremeUraniumReactor-1.0
ExtremeReactors-1.10.2-0.4.5.30
Tesla-1.10.2-1.2.1.49
zerocore-1.10.2-0.1.0.6
Guide-API-1.10.2-2.0.3-46
BloodMagic-1.10.2-2.1.11-80
Bloodmoon-MC1.10.2-1.5.1
EnchantingPlus-1.10.2-4.1.0.115
forestry_1.10.2-5.2.17.387
InventoryTweaks-1.61-58
Levels 2-1.10.2-r1.2.8
OpenComputers-MC1.10.2-1.6.2.7
OreExcavation-1.2.102
refinedstorage-1.2.26
VillageNames-1.10.2-1.1a
Wither Skeleton Tweaks-1.10.2-1.7.2
Mantle-1.10.2-1.1.5
BiomesOPlenty-1.10.2-5.0.0.2290-universal
ElevatorMod[V.1.3.0][MC.1.10.2]
ExtraPlanets-0.6.7
Galacticraft-Planets-1.10.2-4.0.0.117
GalacticraftCore-1.10.2-4.0.0.117
MCMultiPart-1.4.0-universal
Mekanism-1.10.2-9.2.3.97
MekanismGenerators-1.10.2-9.2.3.97
MekanismTools-1.10.2-9.2.3.97
MicdoodleCore-1.10.2-4.0.0.117
Ruins-1.10.2
TConstruct-1.10.2-2.6.5
TinkerToolLeveling-1.10.2-1.0.1

**Comment by BluSunrize** [comment]
Mate the latest 1.10 version of IE is build 61. You are hilariously behind. Go update all your stuff.

**Comment by EliSauder** [comment]
I could have sworn I had downloaded the latest version....I guess not...that fixed it. I guess i should go through and check versions for the rest of the mods too just incase I made the same mistake. Thank you for your help even if it was a stupid problem 😄
