### ISSUE TITLE
[Feature Request] Canola Integration

### ISSUE THREAD

**Issue by Kudan7** [BluSunrize/ImmersiveEngineering#2464]
This is my first time on github so I hope I am posting this in the right section.

I would like the ability to make the crystallized and empowered oils inside the mixer, it will save in less lag cause the chunk wouldn't be constantly loading. maybe could be usable in the biodiseal generator as well, not sure how much power it would make though.

**Comment by PrincessRTFM** [comment]
I believe that Blu has already said that he doesn't want to add other mods' fuels to the biodiesel generator, because IRL, biodiesel generators need to be modified to work with biodiesel instead of regular fuel.

**Comment by Kudan7** [comment]
then at least the mixer?

**Comment by BluSunrize** [comment]
Empowering is a complex process in AA, I wouldn't want it possible with a machine as simple as the mixer.
I have however, allowed canola to be squeezed in IE's squeezer.
