### ISSUE TITLE
[suggestion] vanilla minecart integration

### ISSUE THREAD

**Issue by chrisbecke** [BluSunrize/ImmersiveEngineering#2465]
imo vanilla rail and minecarts really fit with the IE aesthetic, but it is difficult to unload and load minecarts using vanilla mechanics only. While there are other mods that add significant extensions to the vanilla rail mechanisim I believe that IE could benefit from including a small amount of minecart integration, restricted to as little as one block: A sensor block that can be programmed (by whacking it with an engineers hammer) to power - or depower - an adjacent powered rail depending on the state of inventory the minecart-with-chest on that piece of rail and the hopper/inventory that is inserting items into, or drawing items out of, the minecart.

Although I'm sure we would all prefer some kind of clever multiblock, incorporating the powered rail and hopper, into a integrated rail loader / unloader.

**Comment by mindforger** [comment]
a simple scale block that emits power depending on the fill level of the chest-cart ... i never tried but does an redstone comparator output any signal when a chest cart is passing behind it?

additional idea you can mount several scale blocks behind each other to get an combined signal of all chest carts in conctact with the scale blocks as a single signal

have you tried mounting dropping conveyors above the minecarts to insert stuff faster than with a normal hopper? 

something for faster and/or filtered unloading would really be nice imho ...i ahve not yet played that much with anything >1.7.10 but is there soemthing that can yet extract things from machines for example that could be used?

**Comment by BluSunrize** [comment]
All of this is very much @SkySom's problem.
He's working on an IE addon dealing with trains. Chuck those ideas at him, he'll be glad to see even more work on his plate, I'm sure =P

**Comment by chrisbecke** [comment]
I see that you don't feel inspired by the idea of adding this to your own mod and thats fair enough. However, in case there is any sliver of interest, I think there are some good reasons to consider it:

1. OpenTransport adds a lot of stuff that IE players don't necessarily want. There is something to be said for a simple integration that utilizes an existing vanilla mechanic without adding anything other than the integration point.
2. IE has a far greater chance of being included in modpacks than "OpenTransport". A simple integration ensures its always available even in packs that don't include OpenTransport for any particular reason.

At any rate, thanks for considering the idea and responding.

**Comment by BluSunrize** [comment]
I'm not talking about Open Transport, I'm talking about Vehicular Engineering:
![image](https://imgur.com/j6i1luG)

Sky's doing the code, Hazard does models. It'll have plenty chance to be included in modpacks when it's flagged as an official IE addon and *actually looks good*

**Comment by chrisbecke** [comment]
I will say, while that is a lot more than the simple loader I was hoping for, that looks bloody awesome.

**Comment by BluSunrize** [comment]
ikr.

**Comment by mindforger** [comment]
am i jsut too stupid to search or is this mod not yet published? i found the git so far but it's pretty ... steril ... with informations yet :P

**Comment by BluSunrize** [comment]
It's in dev. There is no release.

**Comment by chrisbecke** [comment]
I don't know that I can offer suggestions for either VE or OT as those mods - presumably have their own ways of loading/unloading. Railcraft was/is kind of the gold standard for a "rail&minecart" mod - which adds loaders and unloaders - but also whole bunch of stuff that competes with IE.

**Comment by Bihlbo** [comment]
That little locomotive looks really sweet. I can't wait!

**Comment by ldog** [comment]
Sweet! It's great to see more addons for IE coming out. 
Petroleum, solar power (tech), now trains. Good stuff!

**Comment by HappyPineapple** [comment]
@SkySom boats have all ready been implemented in immersive petroleum.
