### ISSUE TITLE
[Suggestion] Configurable Crusher speed

### ISSUE THREAD

**Issue by angelnc1989** [BluSunrize/ImmersiveEngineering#247]
The config options are really good so far, but I'd like to configure the time per operation for the crusher.
It would be nice if you would take it into consideration.

**Comment by Lord-Mimir** [comment]
The operation speed of the crusher can be changed in config file already, just need to change the RF per tick that it can consume.

    # The RF per tick consumed by the Crusher. Will also directly influence the speed.
    I:"Crusher: Consumed"=80

**Comment by angelnc1989** [comment]
Wow. I should read more carefully.
So if I double the RF/tick it will double the speed?

**Comment by Kubuxu** [comment]
Yes.

**Comment by angelnc1989** [comment]
Thanks,
