### ISSUE TITLE
[1.10.2] Thermal Expansion tanks disappear when used to craft treated wood

### ISSUE THREAD

**Issue by SHIuSH** [BluSunrize/ImmersiveEngineering#2470]

**Comment by PrincessRTFM** [comment]
I'm going to go ahead and say this before Blu needs to: please read the [Contributing Guidelines](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/CONTRIBUTING.md) to see how to _properly_ report bugs.

**Comment by BluSunrize** [comment]
Also this is fixed in 1.12 and I'm not porting the fix back.
