### ISSUE TITLE
[Feature Request] Whitelist for Engineer's Toolbox

### ISSUE THREAD

**Issue by joshbooth** [BluSunrize/ImmersiveEngineering#2471]
Not all mod food extends ItemFood, and almost no tools from other mods can be kept in the Toolbox. (Tinker's Construct is the one exception I've noticed.) It would be handy to have a whitelist in the config file for items that can go in the food section and another whitelist for items that can go in the tools section.

**Comment by BluSunrize** [comment]
Could you provide some examples of items taht should be going in but currently can't? I'd be interested to see if I can find a more generalized way to handle it.

**Comment by joshbooth** [comment]
Tools:
- Shears (not sure if this is intentional)
- Scrench from OpenComputers
- Crescent Hammer from Thermal Foundation
- Configurator from Mekanism
- Mana Blaster from Botania

Food:
- Human Heart from Vampirism

**Comment by joshbooth** [comment]
:D Sweet!
