### ISSUE TITLE
Engineer's toolbox destroys items

### ISSUE THREAD

**Issue by Koltanas** [BluSunrize/ImmersiveEngineering#2472]
I'm playing in 1.12.1 and the engineers toolbox destroys any items you put in it. Immediatly after closing the UI if carried and after some time when placed.

**Comment by BluSunrize** [comment]
Version Numbers.
Crashlog.
Read the blasted debug guidelines.

**Comment by Onexa02** [comment]
Happens to me, too, version 0.12 - 71. Happened on my custom singleplayer modpack, but I tested it and it happens even if IE is the only mod.

**Comment by malte0811** [comment]
In that case: duplicate of  #2438. It's fixed for the next release.
