### ISSUE TITLE
Sugguestion or Bug? But Florb Integration

### ISSUE THREAD

**Issue by darkshadow543** [BluSunrize/ImmersiveEngineering#2473]
Can you provide integration for florbs with the bottling machine, it seems it is not included already and when I give the bottling machine a florb, it does the animation, and spits out an empty florb.  Before you say just use the fluid transposer, I am taking it off the pack I am making, because it does not make sense to have such a machine in a 1 meter cube.

**Comment by BluSunrize** [comment]
I mean you did see the issue template right? The one that asks you to specify versions and stuff?
That would be really damn helpful.

**Comment by darkshadow543** [comment]
My Bad,  I'm sorry I forgot.  
IE: 0:12-71
TE: 5.3.5.19
CT: 4.0.6

One other bug I found with craft tweaker integration.  Basically, if you use the oredict in a blueprint recipe and add a number, it does not listen to the number.
CT script line:
mods.immersiveengineering.Blueprint.addRecipe("Thermal Expansion", <thermalexpansion:tank>, [<ore:ingotCopper>*3, <ore:blockGlassColorless>, <thermalfoundation:material:512>]);
Result: 
![2017-09-09_18 54 24](https://user-images.githubusercontent.com/14943673/30244695-66da4622-9591-11e7-99f4-a25587d24d7f.png)

**Comment by BluSunrize** [comment]
right so in order:

1) Florbs can't be filled because they don't actually have a capability for fluid storage. @KingLemming, is there a reason for this? Balance concerns?

2) OreDict incredients in Minetweaker have never officially supported amounts, as such, IE's compatability doesn't either.

**Comment by darkshadow543** [comment]
For Florbs, they do have a tag that gives them a fluid identity, much like a bucket, but there is no amount listed.  If there was an amount, would your machine fill it like any other container?

As for CT then its Jared's problem and he already knows, so that part is over.

**Comment by BluSunrize** [comment]
No it's actually in TE's implementation. All I do is use Forge's existing utility methods to fill a valid fluid container. An item is considered a valid fluid container if it returns a capability for fluid handling.
TE florbs don't have that capability, and I don't plan to specialcase them.

**Comment by KingLemming** [comment]
Yeah, it's intentional. I don't want them filled by simply right clicking on a tank or body of water.

Also, they don't hold *all* fluids, only those with block implementations. And we both know that Forge is kind of particular with that.

**Comment by BluSunrize** [comment]
Right fair enough, fluid blocks are admittedly iffy.
That clears that up then ^^

**Comment by KingLemming** [comment]
I'll let you know if I change that up a bit. I've considered their utility as "stackable buckets" but ehhh...
