### ISSUE TITLE
 [0.71 | 1.12.1] [balance] Cloches, pumpkins/melons, Biodiesel production

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#2475]
I finally set up cloches for biodiesel production for a diesel generator and came across this.
Note: cloches are only run with water, no additional fertilizers.

In order to keep the generator running continuously, I require 8 cloches producing sugar cane or potatoes (same growth speed, both with 2 items grown per cycle, same 80mB of ethanol per item) and just 2 cloches producing pumpkins.

Pumpkins (and melons) produce at double the speed of the regular crops, but only yield one item, resulting in the same itemrate. However pumpkins are able to be crafted into 4 seeds, effectively quadrupling the output in terms of plantoil per item grown (80mB per seed -> 320mB per item grown).

Even hempseeds with their 120mB plant oil per item are produced at the same itemrate as pumpkins, meaning that the plant which was probably thought to be the obvious source of plant oil is vastly outperformed by the mighty pumpkin.

My proposed solution to this would be to halve the speed at which pumpkins are grown and also halve the amount of plant oil gained.
I'd probably do the same for melons, too, since they are even more effective than pumpkins and can be used for both ethanol AND plantoil, provided you can find a way to turn them into slices (average of 5 slices from breaking a melon, average of 6 slices with fortune, in pocket edition you can even get 9 slices when using shears. just have some mod imitate the last one in a crafting recipe and you can run the diesel gen on just 2 melon cloches).

![Melon Lord](http://i0.kym-cdn.com/entries/icons/original/000/019/073/Melon_Lord.png)

**Comment by BluSunrize** [comment]
I halved growthspeed and reduced the seedoil outputs for pumpkins (to 30) and for melons (to 20, I feel like melons would have even less oil)

**Comment by MalkContent** [comment]
I'd maybe have left the pumpkin at 40 per seed, because that way you get a plantoil rate from pumpkin cloches that matches the ethanol rate of potatoe/sugar cane cloches. Since wheat changed to return just a single seed, there is no vanilla crop that offers that.
Y'know, for people that just like an even number of cloches to skip calculations or because easier symmetry for prettyness.

**Comment by Koltanas** [comment]
Isn't this only a proplem when you combine IE with another mod, that offers a cheap auto-workbench? Because without you would need a large Assembler in you production cycle.

**Comment by MalkContent** [comment]
One assembler costs the same or less space (no water piping required), less power (for this purpose) and (i think, didn't count) less ressources than 6 additional cloches.
And when you upscale the production you don't need any additional assemblers.
Also, assemblers are not terribly expensive :)

**Comment by BluSunrize** [comment]
so 40 for pumpkins works better because of the maths?
Do you think that'd be properly balanced then Malk? Would it make people use hemp seeds more or are pumpkins still superior? Because I'd honestly enjoy making my own crop superior x3

**Comment by MalkContent** [comment]
pumpkins growing at the same rate as hemp would yield 4 seeds * 40mB per cycle, hemp seeds yield 2*120mb per cycle, so hemp is the superior thing :)

**Comment by BluSunrize** [comment]
Well, it's out there, so give it a try now and see how you like it =P

**Comment by MalkContent** [comment]
<3
https://www.youtube.com/watch?v=Bn4gkwYc5g0&t=28s
