### ISSUE TITLE
[1.12,  0.12 - 71] Capacitors reset after picking up

### ISSUE THREAD

**Issue by Onexa02** [BluSunrize/ImmersiveEngineering#2476]
Forge 14.21.1.2443

I tested the issue with just IE and JEI, it happens in the same way it did in my singleplayer modpack. Picking up capacitors (I tested with HV) resets them to default (sides config gets reset, they become empty again).
It doesn't happen if I just place them, configure sides and then pick them up, but if I place a connector on them and then pick them up it happens every time. The amount of RF in them doesn't seem to matter.
I also noticed it happening on pumps as well, but didn't further test those.

**Comment by MalkContent** [comment]
i'm on forge x2475 and it doesn't happen to me. can you update and see if it's still the same?

**Comment by Onexa02** [comment]
Still happens on x2475.
Placed 4 HV capacitors, made right side input side on all of them, put connectors on top of two. When I picked them up, the two with the connectors went back into the stack.

**Comment by MalkContent** [comment]
my bad, didn't read well enough. with the connectors it happens to me, too

**Comment by malte0811** [comment]
This is probably caused by e930c898574873db7ec6db6487d263520bbe4838, the variables get reset when the connector breaks. They should probably be replaced by a Map that is cleared every tick.
