### ISSUE TITLE
[0.71 | 1.12.1] [minor, visual] inconsistent windmill spin direction

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#2478]
When you place down windmills facing in opposite directions, they also turn in opposite directions, which is probably powered by dark magic and my heart just can't deal with that ever since Azanor left :C

**Comment by BluSunrize** [comment]
Uh, they should always turn clockwise no?

**Comment by MalkContent** [comment]
Only if you imagine that the wind blows at them from the front. When they are facing the opposite direction, they should both turn in the same direction, from a spectators point of view, since the blades are angled the same. I'm pretty certain of this, but I am kinda brainmush, so I might just have been aesthetically irritated by building a "double windmill" and not both of them turning the same way :D

**Comment by BluSunrize** [comment]
Meh =P

**Comment by MalkContent** [comment]
So, kinda more rested now. I think it'd probably be a bit strange for players to look at the front that turns counterclockwise, because it's intuitive to think that the thing gets blown at from the front.

I had a more involved idea with turning wind (windmills are a non-constant powersupply anyways), so players could witness the windmills turning in different directions. Windmills would have a call to WindHelper.getWindStrength(x, y, z, facing). Turning speed and direction would be dependend on the value and on wether it is negative or not.
For starters getWindStrength could just return simple positive numbers independent of the parameters to mimic current behaviour, but it would be easily extendible to allow for global shifting wind or even local shifting wind.
For the latter one I have an idea to make wind direction biome and seed dependent, per chunk, depending on neighbors and most importantly deterministic, so you can just input current world tick count and get a value without having to keep track of the wind.
I don't have time right now (exams. I shouldn't even be on here, what am I doing D:), but I think I am gonna try and see if I can come up with a system during winter, for personal kicks, and maybe turn it into a PR if you like it.

Anyways. Silly inconsistent windmill spin direction, huh? ^^;
Close at will.

**Comment by BluSunrize** [comment]
I love the idea of actual wind, but alas that'd be a mechanic I'd put into IE and no other mod would ever respect it x3

So fixing their current rotational directions is probably better.

**Comment by BluSunrize** [comment]
There we go.
Based on the empirical evidence of where I live, wind usually comes from the west or the north, as such those are the directions it goes in Minecraft now =P

**Comment by MalkContent** [comment]
A perfect rule of (licked) thumb :D

(also I'm still doing it, i have ideas that need testing and there is nothing you can do to stop meeeee)
