### ISSUE TITLE
[1.12.1 | 71] Pumpkin and Melon seeds in hotbar turn into wheat seeds when opening Garden cloche gui

### ISSUE THREAD

**Issue by DrSquidMD** [BluSunrize/ImmersiveEngineering#2479]
forge-14.22.0.2474

Whenever I open the UI of the garden cloche, and pumpkin and melon seeds in my inventory, hotbar, or hand turn into regular wheat seeds.

**Comment by BluSunrize** [comment]
I'm not experiencing this issue.
Modlist? Can you replicate the issue in an instance with just IE?

**Comment by DrSquidMD** [comment]
With further testing, the effect happens whenever I open or close any inventory, so it's definitely not an IE issue.

**Comment by BluSunrize** [comment]
Excellent!
Good luck finding out what it is ^^
