### ISSUE TITLE
(Sugestion) The Crusher

### ISSUE THREAD

**Issue by ElliotBlack** [BluSunrize/ImmersiveEngineering#248]
First, I would like to praise the awesome mod you came up. the aestetic are pretty awesome and they have an unique feel. 

In regards the crusher, I reallly like the way you managed the ore multiplying, but seeing such a big structure, the output kinda seems low. 

I dont know the future planes you got for the mod, but there goes a sugestion:

Let the grinder be the first link in the chain, and have a second or even third structure that each one gives you a chance of bonus material.

akin to the way the excavator works you could set the crusher to:

a) Actual behavior (if no other structure in the chain is detected)
b) Actual behaviour+chance of a third ingot of material (crusher + second stage)
c) b + increase to the chance of third ingot, and increase the chace of secondary output

With each part for the structure having its power requirements.

**Comment by BluSunrize** [comment]
I currently don't intend for Ore trippling to be in IE.
