### ISSUE TITLE
Weird And Annoying Bug Please Fix!

### ISSUE THREAD

**Issue by Asais10** [BluSunrize/ImmersiveEngineering#2481]
It's in 1.12.1 I used version 0.12-71

When I Try to fill the chemical thrower using a filled barrel (Yes, it wasn't empty) The Water in the barrel disappears but the chemical thrower is empty (I can't use it) Sorry if i didn't describe good enough then

**Comment by malte0811** [comment]
Are you in creative mode? If you are there isn't much we can do about it, we use standard forge code for filling items from blocks IIRC. It should work in survival mode.

**Comment by Asais10** [comment]
malte0811 thank you, now i finally can use the chemical thrower
