### ISSUE TITLE
[0.71 | 1.12.1] Metal Press Plates missing Ingots in recipes

### ISSUE THREAD

**Issue by Jomeaga** [BluSunrize/ImmersiveEngineering#2485]
Forge-14.22.0.2474

The Metal Press Plate Mould is missing the ingots in it's recipes so I cannot create plates with the press (saw the ingots were missing in JEI). The materials missing are all the standard ones (iron, steel, copper, invar, electrum, etc) within IE, but not ones found in other mods such as Thermal Expansion (eg Mana Infused Ingot). I can still create wires and rods with the metal press. As well as creating plates using the hammer.

The only things I changed in the config files was disabling generation of most IE ores because I wanted to use the Embers ones.

Mod List here: https://pastebin.com/vU5uPzGG

EDIT: Just noticed gears also are having the same issue.
Materials with broken recipes for both plates and gears are Iron, Gold, Copper, Tin, Silver, Lead, Aluminum, Nickel, Platinum, Iridium, Steel, Electrum, Invar, Bronze, Constantan, and (Uranium for plates only).

**Comment by BluSunrize** [comment]
I'm not sure I'm fully understanding the issue. Is it the the recipe to *make* the plate mold that is bugged for you or is it the recipes using it in the press?

In either case I am finding myself unable to replicate this in my dev environment, I am able to make Iron plates with the press and I can use them to make the molds. So the issue might already be fixed by recent changes to the recipe registry code?

**Comment by Jomeaga** [comment]
It's the recipes using it in the press that are bugged, they're missing the ingot component. So in JEI when I looked at recipes using the plate mold, it shows the list of all the materials I can use to make plates, the ones I listed show a recipe with only an output of the correct kind of plate, but no ingot to use with the mold to make it.

Is there anything you know of that I could try and edit the recipes? Maybe it's an oredict bug considering the materials that aren't working are ones present in multiple mods?

**Comment by BluSunrize** [comment]
They look good in my dev environment, so I have to assume that the issue has been resolved by my recent changes to use the recipe event.
The next release (excepted i nteh next 3 days or so) should resolve this.

**Comment by Jomeaga** [comment]
Okay, I'll try to update you when that releases. Thank you for the assistance.

**Comment by calloatti** [comment]
This will fix the problem for me:

`mods.immersiveengineering.MetalPress.addRecipe(<immersiveengineering:metal:30>, <immersiveengineering:metal:0>, <immersiveengineering:mold>, 500);
mods.immersiveengineering.MetalPress.addRecipe(<immersiveengineering:metal:31>, <immersiveengineering:metal:1>, <immersiveengineering:mold>, 500);
mods.immersiveengineering.MetalPress.addRecipe(<immersiveengineering:metal:32>, <immersiveengineering:metal:2>, <immersiveengineering:mold>, 500);
mods.immersiveengineering.MetalPress.addRecipe(<immersiveengineering:metal:33>, <immersiveengineering:metal:3>, <immersiveengineering:mold>, 500);
mods.immersiveengineering.MetalPress.addRecipe(<immersiveengineering:metal:34>, <immersiveengineering:metal:4>, <immersiveengineering:mold>, 500);
mods.immersiveengineering.MetalPress.addRecipe(<immersiveengineering:metal:35>, <immersiveengineering:metal:5>, <immersiveengineering:mold>, 500);
mods.immersiveengineering.MetalPress.addRecipe(<immersiveengineering:metal:36>, <immersiveengineering:metal:6>, <immersiveengineering:mold>, 500);
mods.immersiveengineering.MetalPress.addRecipe(<immersiveengineering:metal:37>, <immersiveengineering:metal:7>, <immersiveengineering:mold>, 500);
mods.immersiveengineering.MetalPress.addRecipe(<immersiveengineering:metal:38>, <immersiveengineering:metal:8>, <immersiveengineering:mold>, 500);
mods.immersiveengineering.MetalPress.addRecipe(<immersiveengineering:metal:39>, <minecraft:iron_ingot>, <immersiveengineering:mold>, 500);
mods.immersiveengineering.MetalPress.addRecipe(<immersiveengineering:metal:40>, <minecraft:gold_ingot>, <immersiveengineering:mold>, 500);`

I have no idea what the RF cost of the plates is, just used 500

**Comment by Chenjox** [comment]
If you use UniDict in your modpack, try disableling ImmersiveEngineering Integration in /configs/UniDict/Integration.cfg
That solved it for me

Chen

**Comment by BluSunrize** [comment]
This is fixed now. Grab the new version of IE.
