### ISSUE TITLE
(Sugestion) More Weapons and turrets

### ISSUE THREAD

**Issue by Asais10** [BluSunrize/ImmersiveEngineering#2486]
(Rifle) pretty much like revolver, only longer range and slower reload  Attachments:Railgun Scope, ? (? means that i don't have an idea for that thing, in this case for second attachment) 
(Machine Gun) Rapid fire, can fire 30 bullets before reloading, reload speed is medium 1 bullet deals really low damage (Like a real life machine gun does) Attachments:something that increases clip size (From 30 to 45 bullets) and something else (?) 
(Machine Gun turret) Pretty much an machine gun turret (Fires rapidly)
(Rifle Turret) An turret with long range (Rifle attributes) 
(Auto-turrets) fire automatically when an hostile mob comes close enough
(Turret Upgrades) 1:upgrade turret can spin 360 (Works only for auto-turret) I don't have more ideas for turret upgrades, if you have some tell in the comments
P.s I don't want these guns and turrets look modern i want the guns (Machine Gun,Rifle) look like something from world war 2

**Comment by Asais10** [comment]
oh another thing when you make the auto-turret and you don't add the first upgrade (360 spinning thing)
The turret can only attack enemies in front of it (It doesn't turn)

**Comment by BluSunrize** [comment]
I'll preface this by saying: I have no current plans to add further weapons to IE. That said, I'll go through your suggestions one by one:

* Rifle: It'd do the exact same thing a revolver does. It's already high damage, slow reload.
* Machine Gun: Okay, so for future reference: "real life machine guns" do not do "low damage". They literally rip the limbs off of people. And adding something that fires the same cartridges faster than the revolver just makes the revolver pointless.
* Turrets: They already exist. They also shoot hostile mobs if they get too close. And they can turn 360 degrees.

**Comment by mindforger** [comment]
>"real life machine guns" do not do "low damage"

i think he confused SubMGs with regular MGs

he wants soemthing to "spray", something to "snipe" and the regular revolver

but there is already the railgun to "snipe"

only the "spray" gun is missing if you won't go for the chem-thrower but vanilla damage mechanics on mobs would render the fast shooting useless as mobs can only be hurt once or twice every second or soemthing like that as far as i know

**Comment by BluSunrize** [comment]
I mean, for one I can change that invulnerability timer, buckshot does that already.
Also, SMGs can hardly be described as low damage as well.

Point is, I'm not adding another gun. If it uses the same ammo it would just replace the revolver if it was better, or not replace it if it was worse.

**Comment by Asais10** [comment]
OK
