### ISSUE TITLE
[Suggestion] Add seperate texture for MV Connector

### ISSUE THREAD

**Issue by Slye-Fox** [BluSunrize/ImmersiveEngineering#249]
I was working on making a doku texture pack for IE, and just found out that the MV Connector uses the HV's texture. Which is a bit annoying when I was aiming to give each Connector a seperate texture based on their materials (copper for LV, Iron for MV & Aluminium for HV), but can't.

**Comment by BluSunrize** [comment]
I added this in https://github.com/BluSunrize/ImmersiveEngineering/commit/356e944c338a1446d44f19e2d61eb5739e6235b2, I juts forgot to reference this issue ^^
