### ISSUE TITLE
1.12 immersive enginnering mod version 0.12-71

### ISSUE THREAD

**Issue by CharCharthemonkey** [BluSunrize/ImmersiveEngineering#2490]
trying to make gears using the metal press with gear cast and it doesnt work but using the other casts do work and tried on multiple presses for gears and nothing but the same presses with plates pipes wires and shell molds work fine help plz

**Comment by Jomeaga** [comment]
I reported this issue earlier and @BluSunrize said they couldn't recreate the issue so it's probably fixed in the new version that will release in the next few days.

**Comment by CharCharthemonkey** [comment]
noted @Jomeaga

**Comment by BluSunrize** [comment]
This is fixed now. Grab the new version of IE.
