### ISSUE TITLE
issue in immersive enginnering for 1.12

### ISSUE THREAD

**Issue by CharCharthemonkey** [BluSunrize/ImmersiveEngineering#2491]
the garden closhes will not output items even with pipes or storages set on them to input into
![2017-09-13_17 15 07](https://user-images.githubusercontent.com/30783285/30404136-ae859db6-98aa-11e7-870c-1e5db4925395.png)

**Comment by BluSunrize** [comment]
Verisonnumbers, modlist.
There is an issue template and contribution guidelines.

Please follow them and provide the necessary information or I will be forced to close this.

**Comment by CharCharthemonkey** [comment]
0.12-71 immersive enginnering 1.12 
[Charlies Adventure Pack 4-1.0.zip](https://github.com/BluSunrize/ImmersiveEngineering/files/1303797/Charlies.Adventure.Pack.4-1.0.zip)
thats the modpack in question where the issue is happening

**Comment by BluSunrize** [comment]
I asked for a modlist, not a zipfile. Read the contribution guidelines and follow them.

**Comment by CharCharthemonkey** [comment]
this is the modlist also the latest version for IE in 1.12 is broken so yea
![2017-09-14_14 16 33](https://user-images.githubusercontent.com/30783285/30453949-3b8ed492-9960-11e7-93fe-7615c12bb887.png)

[modlist 1.12.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1304438/modlist.1.12.txt)

**Comment by CharCharthemonkey** [comment]
even in 1.12.1 closhes still dont output items for some reason and the gear cast is still broken in the latest update

**Comment by BluSunrize** [comment]
Right in short:
Mekanism pipes probably don't do item handling properly. Not my fault.
