### ISSUE TITLE
[1.10.2] Mixer cause crash: divide by zero

### ISSUE THREAD

**Issue by chengxinlun** [BluSunrize/ImmersiveEngineering#2492]
Attempt to use mixer to make awkward. Immediately after putting in the nether warts, the game crashes.

MC version: 1.10.2
Mod version: 0.10-61

Crash report: https://pastebin.com/hHQsGZfE

I could not provide a screenshot of the set up since I could not start my world without removing the mixer with mcedit. But basically an EIO reservoir provides the water, energy comes from a flux point, and no fluid container at output. When I put in the nether warts, the mixer is full of water.

**Comment by BluSunrize** [comment]
did you make any changes to the recipe? Because it seems to be crashing on its fluid amount, which shouldn't ever be 0.

**Comment by chengxinlun** [comment]
I am playing Craft of the Titans mod pack and there are changes to recipes. But I checked all the ```.zs``` file under the ```script``` folder but there is no change involving IE machine. Unless there is other way to change recipes.

**Comment by BluSunrize** [comment]
I'm honestly not sure then. It's not an issue that should arise with IE's default systems.
Your best way to salvage your world is to go into the forge config and turn on the setting that deletes erroring TileEntities. That might allow you to load back into the world and remove the remains of the squeezer.

**Comment by chengxinlun** [comment]
Thanks for the help. I managed to get the world running again, and also posted an issue to Boolyman asking him what he has changed about IE that might be related to this bug (https://minecraft.curseforge.com/projects/craft-of-the-titans/issues/248).

**Comment by BluSunrize** [comment]
*shrug*
Good luck with it!
