### ISSUE TITLE
[1.12.1] Adding Veins via CraftTweaker Not (Completely) Functional

### ISSUE THREAD

**Issue by MyNameIsKodos** [BluSunrize/ImmersiveEngineering#2493]
### Before reporting:
Please use the searchfuntion to make sure an issue hasn't been reported already. This avoids duplicates.<br />
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
Describe what happens, how it affects your game/gameplay and provide screenshots where possible.

 * After writing a zs file to add two custom veins, and loading into the game, I am [able to see](https://i.imgur.com/KoHLy24.png) both veins in the list provided via the command 'ie mineral list' however they aren't in the manual, and as far as I can tell with testing, they aren't actually generating within the chunks

### Crashlog:
If your Minecraft instance has crashed, a file will have been generated in the folder `crash-reports` of your minecraft folder. To understand what has happened, we need to know the content of that file. But please don't just put it directly in your report (that makes it hard to read), upload it to a site like [pastebin](http://pastebin.com) or [gist](http://gist.github.com) and put a link in the actuall bug report.

 * While not an actual crash, I am attaching the script that I've written, just in the event that it is user error on my part. The script can be found [here](https://pastebin.com/raw/ZsKpf8Wv). My CraftTweaker Log confirming that the mineral veins are being added can be found [here](https://pastebin.com/raw/JnKHQTsR) as well.

### Versions & Modlist
IE and Forge versions are mandatory. *Note that saying "latest" is **not** valid. Always give the proper version number* <br />
Other mods should be listed (with their versions) in a [pastebin](http://pastebin.com) or [gist](http://gist.github.com) upload. The easiest way to get these lists is a crashlog, you may force one with F3+C.<br />
If your game crashed (see above) you may omit the modlist, but IE and Forge version would still be nice.

I am using the following mods: 
 * IE Version 0.12-72-254 (This is a Jenkins build)
 * CraftTweaker 1.12-4.0.6

Also, please try testing an issue in a minimal instance, with just IE, Forge and maybe JEI. That makes elminating compat issues easier.

### Lastly (you may delete this from the report itself)
Please, for the love of all that is voxelbased, read the contribution guidelines. They are linked above in the yellow box.<br />
When reporting issues, these are crucial, and the team withholds the right to close an issue for the plain stupidity of not reading and adhering to them.

Thank you for reporting issues, without people reporting them, they wouldn't get fixed. You're helping contribute to this mod and that is much appreciated <3

**Comment by mindforger** [comment]
sorry if i may missed the change if it has changed ... but
don't you use the ore dict names of things to be inside the vein!? maybe the vein is empty because the contents could not be found and empty veins are not liste in the book then ?

**Comment by MyNameIsKodos** [comment]
I am attempting this now. I will post back and update this comment with results.
