### ISSUE TITLE
[1.11.2] Crash when tessellating balloon block

### ISSUE THREAD

**Issue by Chopter** [BluSunrize/ImmersiveEngineering#2494]
After a relogging into a world where ive placed ~ 5 balloon the game will crash after entering render distance to the balloons. they are being used to act as attachment points to LV relays

crashlog and mods: https://gist.github.com/Chopter/676cc8446af033a354ca56d1e2fac72c

**Comment by BluSunrize** [comment]
Are you using a resource pack?

**Comment by Chopter** [comment]
nope base textures, i forgot to mention that botania, waila/wawla and iron chest were added mid way through play but im not sure if that really correlates to anything.

**Comment by BluSunrize** [comment]
Weird.
No idea what's causing it tbh. However, 1.11 isn't officially supported anymore, I'd suggest upgrading tbh :V

**Comment by Chopter** [comment]
Guess ill just stop using balloons for that save, my test world can render them fine so it seems to just be the one save. and i will once some other mods im waiting on update :V 
closing this one
