### ISSUE TITLE
[1.12.1] botania API you ship causing crash 

### ISSUE THREAD

**Issue by b0bst3r** [BluSunrize/ImmersiveEngineering#2497]
### Description of the issue:

Crash on startup with a specific set of mods

Ok so the crash is caused by a combination of mods, in short

Botania + Better with Mods + Immersive Engineering = crash

Botania + Better with Mods = no crash
Botania + Immersive = no crash

Immersive Engineering does ship Botania API
Better with Mods as far as I can tell does not ship any API (besides it's own).

For this test only I opened Immersive Engineering's Jar file and deleted the botania API and the crash went away.

### Crashlog:
http://pastebin.ubuntu.com/25540683/

### Versions & Modlist
forge-1.12.1-14.22.1.2480 (occurs with any version supported by the mods)
ImmersiveEngineering-0.12-72
BetterWithMods-1.12-2.0.10
Botania-r1.10-347

### Suggested Fix
Update the botania API in IE

https://github.com/Vazkii/Botania/issues/2380

**Comment by b0bst3r** [comment]
As an addendum to this - the crash does not occur at all with all mods using Immersive Engineering-0.12-71

**Comment by BluSunrize** [comment]
https://github.com/Vazkii/Botania/blob/master/src/main/java/vazkii/botania/api/item/TinyPotatoRenderEvent.java
https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/vazkii/botania/api/item/TinyPotatoRenderEvent.java

The classes are basically the same, this shouldn't conflict :V

**Comment by malte0811** [comment]
This is somewhat my fault. The class from IE is signed by your key, the class from botania and all other classes in the package aren't signed. Java apparently doesn't like multiple classes in the same package being signed by different people (or some signed and some not).

**Comment by BluSunrize** [comment]
Huh. Weird that it doesn't do it with just IE and Botania though.

I guess we can just remove it? Not like that event is used for much...

**Comment by malte0811** [comment]
Where you testing in dev or in a normal instance? The classes won't be signed in dev AFAIK (except maybe with gradlew runClient) since they aren't in a jar file.

**Comment by BluSunrize** [comment]
I didn't test anything, I went purely off of the issue statement.

**Comment by armuell** [comment]
This bug is very frustrating, an eta on a fix?

**Comment by BluSunrize** [comment]
Whenever I get around to releasing the next build.

**Comment by b0bst3r** [comment]
ImmersiveEngineering-0.12-74 works fine so I take it this is no longer needed?
