### ISSUE TITLE
[0.7.7] [1.7.10] server crash when someone join, crusher/diesel generator related.

### ISSUE THREAD

**Issue by jujuztune** [BluSunrize/ImmersiveEngineering#2498]
Description of the issue and crashlog:

Hello, we have a private server. 
when we build crusher or diesel generator and someone join the server, the server crash with this log (for the crusher crash):

https://pastebin.com/UWAStAEv

Versions:

We use 0.7.7 IE and 10.13.4.1614  forge.
Modlist in the pastebin.

Possibly related (for the crusher) to:

https://github.com/BluSunrize/ImmersiveEngineering/blob/1.7.10/src/main/java/blusunrize/immersiveengineering/common/blocks/metal/TileEntityCrusher.java#L78

Thanks for the mod and all these nice multi-blocks. :)

**Comment by malte0811** [comment]
1.7.10 isn't supported any more. And hasn't been for ~1.5 years.
