### ISSUE TITLE
[0.12-72] [1.12.1] Crash with theoneprobe

### ISSUE THREAD

**Issue by antcig** [BluSunrize/ImmersiveEngineering#2499]
[crash-2017-09-15_19.31.44-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1307060/crash-2017-09-15_19.31.44-client.txt)
Crash happens when theoneprobe point to toolbox.
Did not happen with prev 71 version.

**Comment by malte0811** [comment]
Duplicate of #2496. Fixed for the next release ~20 minutes ago.
