### ISSUE TITLE
Connectors allow you to run cabled between them more than once

### ISSUE THREAD

**Issue by BarbasTheDog** [BluSunrize/ImmersiveEngineering#25]
You can run cable between the same connectors more than once. Tested with LV connectors, will test using MV and HV once I climb the tech tree a bit more :P

Reproduce by running cable between connectors ad infinitum. When you break one of the connectors, the correct number of coils, correspondent to the number of times you repeated the process, will drop.

**Comment by BluSunrize** [comment]
totally forgot to say. Fixed in .14 >_>
