### ISSUE TITLE
issue in 1.12.1 immersive enginnering version 0.12.72

### ISSUE THREAD

**Issue by CharCharthemonkey** [BluSunrize/ImmersiveEngineering#2500]
when trying to use the gear cast automated it will not auto drop ingots onto the conveyer belt for the gear mold but with other molds it will drop the ingots so is this a IE issue or something else? 
[modlist 1.12.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1307439/modlist.1.12.txt)
theres the modlist for 1.12.1 plz hopefully something can be figured out on this pretty please

**Comment by BluSunrize** [comment]
Pictures and stuff could probably help...

**Comment by CharCharthemonkey** [comment]
![2017-09-15_15 28 29](https://user-images.githubusercontent.com/30783285/30502409-b43df7f8-9a2b-11e7-8d94-6cbc6268199c.png)
![2017-09-15_15 28 51](https://user-images.githubusercontent.com/30783285/30502411-b4417c48-9a2b-11e7-97a8-4424f7248afc.png)
![2017-09-15_15 28 55](https://user-images.githubusercontent.com/30783285/30502413-b4489c26-9a2b-11e7-9357-569180c1bf4f.png)
![2017-09-15_15 29 30](https://user-images.githubusercontent.com/30783285/30502410-b43ff21a-9a2b-11e7-8d9c-793c0acc44c4.png)
![2017-09-15_15 29 41](https://user-images.githubusercontent.com/30783285/30502412-b441e73c-9a2b-11e7-9bde-8146adc4cde9.png)

heres the images and from start to finish goes from chest to hopper to nothing (doesnt output the ingots to the conveyer but dropping the ingots on the belt manually works fine tho its supposed to be automated to make gears

**Comment by MalkContent** [comment]
The conveyor you are trying to insert to is actually part of the press, so you are trying to input items into the press. The problem with that is, that the hopper only inserts a single item at a time, but for the gears recipe, the press requires 4 items, so it says "no" to the insert from the hopper.
If you want to use a hopper for this, put a real conveyor in front of the press, it will drop single items onto that one and the press will start once enough accumulated.
Item despan IS a problem here, so you'll have to come up with some sort of regulation to not overfeed the machine etc. Strip courtains and a redstone circuit could help you out for instance.

**Comment by CharCharthemonkey** [comment]
ok but wats really odd is all the other presses work from the packing/unpacking to the plate and rod ones and those require more then 1 per instantce but the gear one doesnt work at all

**Comment by MalkContent** [comment]
If you are inserting metal ingots for those, the packing press aside, they actually all only require a single item.
For me, packing press does not work with a hopper trying to insert metal ingots, so I have doubts it actually works for you :x You can correct me of course.

**Comment by CharCharthemonkey** [comment]
all the presses (except) the gear one allow for the hopper to work right next to the press but the gear one doesnt thats my issue

**Comment by MalkContent** [comment]
the <packing> press works with the hopper?

**Comment by MalkContent** [comment]
the packing press works with the hopper?
(rewrote this, formatting got screwed)

**Comment by CharCharthemonkey** [comment]
all presses BUT the gear one work with hoppers right next to the press

**Comment by CharCharthemonkey** [comment]
upon forther checking (tho idk how) the 3x3 press plate doesnt work either but the rest do which is very odd

**Comment by BluSunrize** [comment]
I'm gonna go ahead and say: the 2x2 also doesn't work, due to what Malk already explained.

**Comment by CharCharthemonkey** [comment]
nope it doesnt but wats really odd is in previous version of IE (not including the new presses) but all of the presses worked as stated above

**Comment by CharCharthemonkey** [comment]
also the 3x3 and 2x2 and unpacking presses dont even show recipes at all so idk if thats a bug or just not implimented yet

**Comment by MalkContent** [comment]
That's because none of the regular IE presses take more than 1 input item at a time, with the exception of the Rod Mold, when it's used to create Graphite Electrodes (which has the same issue with hoppers that you are having now).
And I can assure you that the Gear Mold also always had that issue :)

The (Un-)Packing Molds show no recipes in JEI, because there is actually no list of recipes, hardcoded or otherwise. Inputstacks are checked on the fly.

**Comment by CharCharthemonkey** [comment]
![2017-09-17_00 14 20](https://user-images.githubusercontent.com/30783285/30518241-9c6b0f40-9b3d-11e7-9c83-b69d58504f88.png)
![2017-09-17_00 14 33](https://user-images.githubusercontent.com/30783285/30518246-9c7ec526-9b3d-11e7-86a5-db5b2a75cc64.png)
![2017-09-17_00 14 35](https://user-images.githubusercontent.com/30783285/30518242-9c6fe42a-9b3d-11e7-8463-806ef90404b7.png)
![2017-09-17_00 14 41](https://user-images.githubusercontent.com/30783285/30518245-9c7511de-9b3d-11e7-9e65-915f8c09b627.png)
![2017-09-17_00 15 33](https://user-images.githubusercontent.com/30783285/30518243-9c70dcc2-9b3d-11e7-8676-12162c93d860.png)
![2017-09-17_00 15 35](https://user-images.githubusercontent.com/30783285/30518244-9c7321d0-9b3d-11e7-92a7-47a018fdd170.png)
MC version 1.7.10 forge version 1614 pack FTB crackpack and the hopper is clearly working with gear casts as stated above which are broken in 1.12.1

**Comment by BluSunrize** [comment]
That was a completely different and far hackier codebase.
Ever since the introduction of ItemHandler capabilities, it has worked like it does now.
This is *not* an issue, it's working as intended.
