### ISSUE TITLE
Crafttweaker support for IE 0.11 - 63 on MC 1.11.2

### ISSUE THREAD

**Issue by Malus-Lupo** [BluSunrize/ImmersiveEngineering#2501]
I am trying to use this script

mods.immersiveengineering.MetalPress.removeRecipeByMold(<ImmersiveEngineering:mold:1>);

mods.immersiveengineering.MetalPress.addRecipe(<buildcraftcore:gear_wood>, <shards:unpressed_wood_gear>, <ImmersiveEngineering:mold:1>, 500);

to remove all gear mold recipes and add a new one. I keep getting the error Could not resolve <ImmersiveEngineering:mold:1> even tho that is copy pasted right from the minetweaker wiki. Any help would be very appreciated.

**Comment by BluSunrize** [comment]
Try it lowercased.

**Comment by Malus-Lupo** [comment]
Ah seems to have fixed it, thanks, only thing is it still shows the old recipes in JEI but they seem to not work. So that is perfect, thanks again!
