### ISSUE TITLE
Suggustion: Ultra sonic wavelength emmiter for concrete messes generated by liquid concrete

### ISSUE THREAD

**Issue by darkshadow543** [BluSunrize/ImmersiveEngineering#2502]
It's a simple suggestion, but I do imagine this could turn out to be a nightmare in terms of code.  The problem is simple, people use liquid concrete, and it can be used to create a giant mess.  All I am asking is a simple tool that, for lore purposes and totally plausible, is an ultra sonic device that breaks down concrete sheets and panels, but cannot shatter larger slabs, chunks and blocks.  It can be a creative only item, I do not care, but it would be an interesting tool.  Just think of Botania's horn of the wild, but for concrete sheets and panels.  To be funny, but might be too much to ask, you could make it so that if a player in the radius is not wearing ear protection, it hurts them.

**Comment by BluSunrize** [comment]
I mean, that's kinda the calculated risk of using liquid concrete. You generally don't pour concrete IRL without having proper formwork, because it *will* get everywhere.

**Comment by darkshadow543** [comment]
That goes to one other thing, liquid concrete dries to quickly to be useful in building, even to make a building foundation with formwork.  You usually end up with slabs and chunks with a lot of panels everywhere.  The only real use is the Prey Reference you made.  Also, this item, when combined with florbs, has the potential to become the tool of trolls/griefers who can leave an enormous mess in minutes that can take hours for a person or admin to clean up.  This suggestion is just a tool to help ease the process of clearing a mess that can be caused.  If you need proof of these powers, here is a picture of me burying a village in concrete, that pile consists of mostly sheets and panels, not solid blocks. That is why I made the suggestion. https://imgur.com/p1OtchL

**Comment by BluSunrize** [comment]
If you have those griefers on your server, you should really chose your userbase better, tbh.
I've never done a feature for "grief protection" because, frankly, people not being assholes is the best protection there is.
