### ISSUE TITLE
[Question] Auto-Generated Coremod in .72

### ISSUE THREAD

**Issue by MainFreak** [BluSunrize/ImmersiveEngineering#2503]
I noticed that the newest update from IE automatically generates a mod that is called "IE-Core" or something similar. I was not able to find it on Curse and the Launcher also said that it is "unknown" so I was just curious if it is alright to ship this part of IE with everything else when uploading a modpack or if I have to delete it every time I want to do that. I will close this issue since it's just a unimportant question, but it would be nice to get an answer before I get rejected by Curse because of that.

**Comment by malte0811** [comment]
That is how coremods are supposed to be handled these days, according to Forge. See http://www.minecraftforge.net/forum/topic/58706-regarding-minecraft-112-and-policy-changes/ (Section "New policy on coremods", rule 1). We also follow the rest of the rules now, both jars are (should be) signed and it was open/visible source even before this release.
The normal IE jar contains the coremod jar, Forge will/should automatically extract it if you upload just the normal jar.

**Comment by MainFreak** [comment]
So I can just delete the Core when I want to upload the pack and everything will be happy?

**Comment by malte0811** [comment]
It should be, yes.

**Comment by MainFreak** [comment]
Alrighty, thank you!
