### ISSUE TITLE
[Feature Request] Toggleable animations for each item?

### ISSUE THREAD

**Issue by Akitori** [BluSunrize/ImmersiveEngineering#2504]
I really don't want to turn off all fancy item animations (because the revolver looks odd when turned off, as the barrel seems to lower itself away from the item or cease existing entirely) so could we have a feature/config option to turn on/off certain item animations instead of disable everything outright?

**Comment by BluSunrize** [comment]
The barrel, along with the cylinder folds forward while reloading. The config option should not be affecting that however, since that config is only for 3rd person view.

Which animations are you trying to disable, and why even?

**Comment by Akitori** [comment]
I want to disable specifically the drill's fancy animations as it makes a major impact on my fps when wielding one with a lot of accessories. So I disabled all animations in the config, however it glitched up the revolvers appearance when I did so

**Comment by BluSunrize** [comment]
Could you please provide the full modlist / debug crash as required by the issue template & contribution guidelines?

**Comment by Akitori** [comment]
The forge version I'm using is 14.22.0.2475 forge 1.12.1. The immersive engineering version is  0.12.72, along with core version 0.12.72. The only mods installed are immersive engineering and forge. 

As for proof of this oddness, here are some screenshots. 

https://imgur.com/a/g5ECv

**Comment by BluSunrize** [comment]
Yeah I found the issue, fix is in the works, next release will address this.

**Comment by BluSunrize** [comment]
I fixed the offsets with the option turned off.
It's not for each item individually but at least they don't look broken without animations.

Next release will include this.
