### ISSUE TITLE
Issues 0.12 - 72 Downloading a File

### ISSUE THREAD

**Issue by dh47** [BluSunrize/ImmersiveEngineering#2505]
ImmersiveEngineering-0.12-72-core.jar keeps being downloading by IE which is not on curseforges allowed outside list of jars, any reason why its grabbing this file?

**Comment by xKnightGamingx** [comment]
I am having the same prob

**Comment by BluSunrize** [comment]
It's not downloading anything. IEs integrated core mod was adjusted to fit Forge's new guidelines. It is now a nested jar inside the main IE jar. Forge unpacks it from there for whatever reason.

This is not an issue, but merely IE complying with Forge's new guidelines.

**Comment by dh47** [comment]
Then you need to add it to the CurseForge's allowed list.  Otherwise, alot of people will get this message.
![image](https://user-images.githubusercontent.com/909007/30518660-6f0a2590-9bd8-11e7-93dc-aab4c5d81d80.png)

**Comment by BluSunrize** [comment]
You delete it before you try to upload the pack. As I said it's *shipped within IE* >_>
