### ISSUE TITLE
[0.72 | 1.12.1] [minor, visual] Blocks in the Metal Press show through the press's piston head

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#2506]
As seen here:

![ie_press_block_visual](https://user-images.githubusercontent.com/7753414/30517152-3d3cff74-9b56-11e7-9003-196de3a0cbdc.png)

Maybe could be fixed by lowering the blocks together with the piston head, when it touches the block? I don't know if that would cause any new input stacks/old output stacks to bob, too.

**Comment by BluSunrize** [comment]
I could try making it go down with the piston, yeah. Will have to see how it affects the look of items.
