### ISSUE TITLE
immersive load freeze

### ISSUE THREAD

**Issue by mummi81** [BluSunrize/ImmersiveEngineering#2507]
Hi i have a problem im running forge 14.22.1.2481 and ie 0.12.72 on 3 pc. but 1 of them freeze in load loading minecraft engine 3/7,    rendering setup - loading item renderer  5/5   i have tryit 2 delete  minecraft,  forge, and ie nothing helps.

![20170917_125022](https://user-images.githubusercontent.com/32033401/30520165-8134c124-9ba8-11e7-9fc6-50cc3fdf8f2e.jpg)
![20170917_125055](https://user-images.githubusercontent.com/32033401/30520166-8135c10a-9ba8-11e7-8ba3-fceecc781b7c.jpg)
![20170917_125318](https://user-images.githubusercontent.com/32033401/30520167-813919fe-9ba8-11e7-9ce0-6d1d4dfe33f5.jpg)

**Comment by BluSunrize** [comment]
That's NOT how you do screenshots.
You are also missing the log file. And the modlist. And it's probably just because of a potato PC anyway since it's a singular issue.
And I'm closing this.
