### ISSUE TITLE
Garden Cloches not growing anything.

### ISSUE THREAD

**Issue by Kejern** [BluSunrize/ImmersiveEngineering#2508]
Sky factory 3- 3.0.13
Immersive Engineering 0.10-60
I cannot figure out how to update sky factory 3 with the .12-72 update, or master.

I have set up several garden cloches. I have provided plenty of power, water, fertilizer, etc... 
I have tried using dirt, fertilized dirt, sand, etc...
I have tried wheat seeds, sugar cane, potatoes, carrots, etc... 
Yet the cloches will not grow anything. 
the plants just sit there doing nothing. 

the void miners work, however...

pics of setup:

![image](https://user-images.githubusercontent.com/32043942/30525582-3a95ee1c-9bbe-11e7-89f5-b1ddd6e269e7.png)

![image](https://user-images.githubusercontent.com/32043942/30525589-581735c2-9bbe-11e7-9dbb-440504c8c1c8.png)

![image](https://user-images.githubusercontent.com/32043942/30525596-6dac046c-9bbe-11e7-9d98-82953b3f2833.png)

setup shows garden cloche, wooden barrel, fluid transfer node, fertilized dirt, inferium seed, bone meal.
power from generators in RF/T, transferring fine.
Help in understanding this would be nice, as the cloches currently don't do anything.

**Comment by BluSunrize** [comment]
So for one: You can't update to .12-72 because you're on Minecraft 1.10

Secondly: Fertilized Dirt doesn't work in the cloche.
