### ISSUE TITLE
[1.10.2] CoreSampleDrill OpenComputers Interaction (Missing function?)

### ISSUE THREAD

**Issue by Rikshy** [BluSunrize/ImmersiveEngineering#2510]
Hi!

First: i'm fairly new to OC so i might do sth wrong!

The modpack im using is FTB Beyond with following versions:
IE 0.10-61
OC 1.6.2.7

I tried to use OpenComputers with the CoreSampleDrill but some funktions error on calling.

functions working:
isSamplingFinished()
getSampleProgress()
getEnergyStored()
getVeinUnlocalizedName() - string is always empty

not working:
getVeinIntegrity()
getVeinLocalizedName()

all these methods are documented in the engineers manual.

Some screenshots with what i tested; https://imgur.com/a/sY0LK

I'm going to test the excavator next. but without the VeinIntegrity working i might aswell cancle my project :( 

Best Regards
Shyrik!

**Comment by malte0811** [comment]
`getVeinUnlocalizedName` should work as long as you wait for the sampling to finish before calling it (didn't test, just looked at the code).
Integrity and Localized Name seem to have gone lost in the 1.8 update. They are there in the code I wrote on 1.7.10 (the docs mostly weren't changed after that), but @BluSunrize either accidentally or intentionally removed them (he manually copied the code over from my 1.7 commits).
1.10 isn't getting any further updates, I'd like to keep this open anyways. I am working on updating the OC compat. It is quite buggy (probably even in older versions, if you know what to look for), I came across a bug in OC while trying to fix one of the problems. See MightyPirates/OpenComputers#2525
