### ISSUE TITLE
[Feature Request] Arc Furnace Round Robin

### ISSUE THREAD

**Issue by Branjoman** [BluSunrize/ImmersiveEngineering#2511]
Just wondering if having a toggle of some sort on the Arc Furnace to round robin items into the smelting slot is high on the priority list of features. Would be really nice for the Arc Furnace to be running at full tilt when autopumping in items. Possibly also for the Squeezer and Fermenter, since they seem to be able to process multiple items at once?

**Comment by BluSunrize** [comment]
I could have sworn that was a thing.
What version are you on?

**Comment by BluSunrize** [comment]
Closed due to lack of response
