### ISSUE TITLE
[Suggestion] Wire Drawing

### ISSUE THREAD

**Issue by discodancepant** [BluSunrize/ImmersiveEngineering#2513]
https://en.m.wikipedia.org/wiki/Drawing_(manufacturing)

Could you add a machine or two to make wire in a mechanical way, in place of wire cutters. A lower tier method could require hand-cranking. The higher tier would be an automated machine that only requires power. 

You could also make the hand machine only capable of crafting copper  as copper is much more easily manipulated than electrum or anything else would be.

The draw plate could be another way to create a tier system. ie: steel draw plate, diamond draw plate, obsidian draw plate, etc.

**Comment by kane-thornwyrd** [comment]
It's called the metal press with the wire mold... -_-'

**Comment by BluSunrize** [comment]
He's got a point there. The metal press automates the otherwise manual process of cutting them out of plates.

**Comment by laz2727** [comment]
Electrum is much softer than copper.

**Comment by discodancepant** [comment]
There are a few reasons I made this suggestion.
1. Realism: Wire is not made with wire cutters, presses, molds, etc.
2. Interesting/Unique Wire crafting: It'd be cool to use a very basic machine to make the lower tier wire. A more advanced machine that could be automated was just the next logical step.
3. It's just a suggestion that I felt was in-line with the aim of this mod's theme. 

@laz2727
True, Electrum is much softer, but I was attempting to stick with the tiered power tree. In reality, Electrum would be able to handle far less

**Comment by laz2727** [comment]
I'm not against wire drawing (Cut a plate into wires? Say what? Whose idea is it? It's so dumb and unrealistic it's not even funny). But I don't think separating copper from electrum is a good idea anyway, since they're not that far from each other on the tech tree.

**Comment by BluSunrize** [comment]
I mean, I never set out to make this the most realistic mod possible.
One of IE's inherent design principles however is that I generally don't add machines for a single recipe.
So having separate machines to craft different tier of wire is hilarious tedium. I'm not Greg.

**Comment by laz2727** [comment]
I understand that. While you can also move rods there, there's nothing else to draw in the mod, it's not RC :P

**Comment by discodancepant** [comment]
Then leave the higher tier for speed and automation while the lower tier requires right clicking. the lower tier is more tedious but gives a way for the user to create wire without advanced machines that need wire in their recipes. 

One of the cool things about this method of wire creation is that it is easy to understand why a single ingot could result in more wire than less efficient recipes. 

Yeah, it's a single machine for one purpose, but I think it's pretty cool having multiple heavy machines in an awesome looking industrial space, rather than crafting tables or applied energistics type automation.
