### ISSUE TITLE
[Question] Diesel Generator RF produced

### ISSUE THREAD

**Issue by cap1o** [BluSunrize/ImmersiveEngineering#2516]
Immersive Engineering 0.10-61 - Config files cheked.

Hello !

I have something i don't really understand with Diesel Generators RF producing.
When i connect 2 diesel generators to a IO Bank capacitor, it show 6143 RF/T product at maximum.
But as i checked on config files and wiki, normally i should get 4096*2= 8192RF/T.
I have only one connection to the IO bank per Diesel Generators so RF producing is not split with something else.

Someone can help me please ?
Thank you !

**Comment by mindforger** [comment]
you have losses on the wires, mybe your wiring is way too long

**Comment by malte0811** [comment]
Is this happening with the same setup as https://github.com/BluSunrize/ImmersiveEngineering/issues/2454#issuecomment-326735221? If not, screenshots would be helpful.

**Comment by cap1o** [comment]
it's same setup yes, i did change last comment the chunkloader and now after test i'm sure there is a trouble.
No losses from wires because it's enderIO and very short circuit.
May it's something i miss dunno ...

**Comment by mindforger** [comment]
aren't those EIO conduits limited in transfer per port? did you try to connect the battery on two points to the conduit?

**Comment by cap1o** [comment]
Actually the setup is already this. 2 different battery side connected for each diesel generators no worry I will connect it with xnet and back if it go on to have troubles

Envoyé de mon iPhone

Le 22 sept. 2017 à 07:06, mindforger <notifications@github.com<mailto:notifications@github.com>> a écrit :


aren't those EIO conduits limited in transfer per port? did you try to connect the battery on two points to the conduit?

**Comment by BluSunrize** [comment]
If you could at least provide the pictures that were asked for that'd be great
