### ISSUE TITLE
hey BlueSunrize regarding IE new recipe adding

### ISSUE THREAD

**Issue by trilexcom** [BluSunrize/ImmersiveEngineering#2518]
hey BlueSunrize

i like to add a recipe script to your alloy klin so i can get her to make a alloy or materiel from another mod 

do you have any examples please on how to make scripts for your api ? 

i am looking at this section https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/api/crafting/AlloyRecipe.java

i am looking at the above alloyrecipe.java file to learn something from it but i can't seem to figure out 

i know how to script using minetweaker or crafttweaker but i dont see any example on jareds wiki or minetweaker wiki i see a old one but that one doesn't work in 1.12.1

if you could please help me that would be wonderful of you i know your busy 

Thanks 

Mat (TrilexCom)

**Comment by BluSunrize** [comment]
There is a Minetweaker function for it:

https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/util/compat/crafttweaker/AlloySmelter.java#L19

**Comment by trilexcom** [comment]
you are so quick BluSunrize you can close this ticket i appreciate it 

Thanks again

**Comment by trilexcom** [comment]
hey BluSunrize

when i try this script 

mods.immersiveengineering.AlloySmelter.addRecipe(<ic2:cable>.withTag({type: 0 as byte, insulation: 1 as byte}), <ic2:cable>, <ic2:crafting>, 10);

i get a error from crafttweaker saying error parsing 

what do you think i am doing wrong please sorry to bother you so much

Mat

**Comment by BluSunrize** [comment]
No idea.
Try with other items, try without NBT tags, and don't forget the < and > around items
