### ISSUE TITLE
CTD issue

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#252]
compiled against commit 356e944c338a1446d44f19e2d61eb5739e6235b2
Upon placing the compiled IE jar into my FTB Infinity (1.9.0) install and launching it,
Minecraft Crashes To Desktop.
Logs here: http://paste.feed-the-beast.com/view/1ba32cbd

incompatibility with AOBD?

**Comment by BluSunrize** [comment]
Yes. Because you're a derp and built an inbetween version, with API changes which AOBD obviously hasn't accounted for since this version isn't released.
