### ISSUE TITLE
Problems with the texture of the crusher

### ISSUE THREAD

**Issue by seven23** [BluSunrize/ImmersiveEngineering#2520]
Problems with the texture of the crusher. I'm playing with Optifin. 
Version 1.12.1
![2017-09-22_20 41 44](https://user-images.githubusercontent.com/31816247/30757431-67390aa4-9fd7-11e7-90e8-b081aa6ef0c6.png)

**Comment by BluSunrize** [comment]
1) You fully disregarded the issue template and contribution guidelines.
2) You are using Optifine.

Could have figured that out yourself.
