### ISSUE TITLE
Miló shader name broken again

### ISSUE THREAD

**Issue by xbony2** [BluSunrize/ImmersiveEngineering#2521]
### Description of the issue:
![2017-09-23_10 35 19](https://user-images.githubusercontent.com/5623501/30774111-977f260c-a04b-11e7-8a54-8ca751d541df.png)

It's a throwback to #622

### Versions
* IE 0.12-72
* Forge 2452 (1.12.1)

**Comment by malte0811** [comment]
Are you on Linux (or Mac) or Windows? I was able to replicate this on Linux (Debian to be specific) with the official CF build (created on Windows), but not with either my own builds (Linux) or the maven builds (probably Linux too).

**Comment by xbony2** [comment]
macOS.
