### ISSUE TITLE
Can't get biodiesel out of Refinery

### ISSUE THREAD

**Issue by NicholasJohn16** [BluSunrize/ImmersiveEngineering#2526]
Sorry if this is the wrong place to ask for help, but I wasn't sure where else to ask.

### Description of the issue:
I opened the refinery UI and accidentally put a jerrycan filled with biodiesel into the top left most slot. This deposited all the biodiesel into the first tank. I can't seem to figure out a way to get the biodiesel back out.

### Crashlog:
No crashes.

### Versions & Modlist
Minecraft 1.10.2
Forge 1.10.2-12.18.3.2185
Immersive Engineering 0.10-57

Thank you for any help.

**Comment by BluSunrize** [comment]
Yeah there isn't any way. Break the machine, lose the fluid. No way around it.
