### ISSUE TITLE
[Accessibility] JEI autoplacer

### ISSUE THREAD

**Issue by SoniEx2** [BluSunrize/ImmersiveEngineering#2528]
JEI has the autocomplete feature. I'd like it to extend to multiblocks, which are little more than just a special form of in-world crafting.

While JEI's autocomplete was not made with accessibility in mind, it turns out to be a quite useful accessibility feature. I'm making this feature request specifically because someone I know has a disability which makes it hard for them to place blocks.

(I'd implement this myself but I think it's important to gather feedback first.)

**Comment by laz2727** [comment]
There is already a creative autoplacer iirc but I would love to see a
survival one.

**Comment by malte0811** [comment]
#789. The issue is 2+ years old, so Blu's opinion may have changed.
The placement in creative @laz2727 mentioned is from IP AFAIK, it is definitely not from IE though. And some IE blocks are not too well-behaved with autoplacement unless they are explicitly handeled (though they aren't used in IE's MBs a lot).

**Comment by laz2727** [comment]
Well, they're literally yours, you can explicitly handle them.

**Comment by BluSunrize** [comment]
I'm not adding creative placers, autoplacers or ghostblock systems.
I don't think they fit IE and there is already an addon providing them anyway.

**Comment by BluSunrize** [comment]
Then don't ask the developer of IE.

**Comment by SoniEx2** [comment]
IE adds the JEI integration that lets JEI do the accessibility. It feels like a native part of JEI even if the code is in IE.
