### ISSUE TITLE
openable chest when conveyor belt is on top of it.

### ISSUE THREAD

**Issue by japtic** [BluSunrize/ImmersiveEngineering#2532]
Could you possible to make it so that chests that are underneath (especially dropping conveyor belt) openable? storage drawers and stuff will have no problem with it but players who uses chest instead will have hard time due to the fact that they cannot open the chest. I am not sure previous versions allowed or not but its my first time to play IE but using 1.12.1 version. 
(immersiveengineering-1.12.1-0.12.72)

**Comment by EvilCooky** [comment]
It's logical that a chest will not open when there's something ontop if it.
Why not use a crate instead?

**Comment by mindforger** [comment]
besides logic, you can open them when a block is marked as non solid, like stairs and half slabs ... i think this would be an improvement to stay in-line with vanilla logic

except when the chest open thoruhg non-sold block thing is not a thing anymore :) ... haven't tried that one in ages

**Comment by BluSunrize** [comment]
Reason for this is that chests check if the block above has a solid side down.
Conveyors have that because that allows for levers and stuff to be placed on the down-face.

So what's more important to you: Opening chests or levers on the bottom? =P

**Comment by mindforger** [comment]
Levers no question ...

**Comment by ldog** [comment]
Levers!
Although if the dropping conveyor could be treated as a special case that would be the best of both worlds.
If not then yeah, levers.

**Comment by KnightMiner** [comment]
I would agree there is no point of placing a lever on the bottom of a dropping conveyor, as the reason you would want one is to drop into an inventory below. So maybe make the bottom solid for normal conveyors, and non-solid for dropping ones
