### ISSUE TITLE
so what is instead of making AA oil work in the diesle generator...

### ISSUE THREAD

**Issue by Umber0010** [BluSunrize/ImmersiveEngineering#2535]
... You added a config to edit what fluids could go into the diesel generator and how much they produce. So, for example I wanted to make a mudpack devoted to cross-mod play, I could edit the config to allow the various AA oils to make power, I could enable lava as a crude fuel source. I could enable TR oil. TE tree oil. all kinds of fuel

and while i'm no programmer (not yet at least) I think many would find it useful if you where to make it so that different fuels produced different types of power. Bio-diesel could generate RF while, say, Superheated coolant from IC2 could make EU instead

**Comment by BluSunrize** [comment]
I mean, for one, IE doesn't output EU anymore.
And two, there is a Minetweaker option for it.
