### ISSUE TITLE
Integration for mystical agradditions

### ISSUE THREAD

**Issue by forestbat** [BluSunrize/ImmersiveEngineering#2536]
@BluSunrize 
Nether star seeds and Awakened Draconium seeds in mystical agradditions need dirt and crux，so they can't put in garden cloche，do you want to add integration for them？

**Comment by malte0811** [comment]
See #2237 for Mystical Aggradditions in general. The reason the PR isn't getting merged is that the proposed implementation is quite "brittle" (it could easily break in any update). If @BlakeBr0 was to add it on his side it would be a lot cleaner and safer. I pinged him on the PR a few months ago, but he didn't respond.

**Comment by tyler489** [comment]
#2379 he denyied mine

**Comment by BlakeBr0** [comment]
The cloche already makes mystical agriculture way too busted for too cheap. Awakened draconium crops would just make that worse imo

**Comment by BluSunrize** [comment]
It's a config option  ¯\_(ツ)_/¯
(also presumably you're talking about the long outdated 1.10 compat)

Closing this, since it's clearly not happening.

**Comment by tyler489** [comment]
Its not mystical agiculture. Its mystical aggrigations
