### ISSUE TITLE
1.12.1 Chemthrower turret not working

### ISSUE THREAD

**Issue by Asais10** [BluSunrize/ImmersiveEngineering#2538]
Everything works fine, but there's an problem. I can't fill the chemthrower turret with any liquid. I put and fill an metal barrel, and put fluid pipes to connect the metal barrel to the turret's back (It has RF and it's turned on) and it simply don't fill (When i open the turret's UI it says that i don't have any liquid in it

**Comment by BluSunrize** [comment]
Pictures? >_>

**Comment by Asais10** [comment]
I literally only have JEI and the mod itself (including core) 
forge version: 14.22.1.2478

**Comment by malte0811** [comment]
![2017-10-02_17 57 29](https://user-images.githubusercontent.com/10406104/31086841-3ceeb3e0-a79b-11e7-8b37-e238c8d2b47c.png)
That setup works for me. Could you post a screenshot (or even more than one) of your setup?
Does the fluid leave the barrel? The GUI updating is a bit slow at times.

**Comment by Asais10** [comment]
oh! i actually put the fluid pipe on top of the barrel not under. Also my minecraft glitched, i think it's going to work today

**Comment by Asais10** [comment]
it works and i'm closing the issue
