### ISSUE TITLE
REVOLVER MODEL BROKEN (1.12.2)

### ISSUE THREAD

**Issue by IbramCain** [BluSunrize/ImmersiveEngineering#2539]
The revolver model aparently seems broken in the last version of the mod. 
Theres no more mods, just IE.
sshots:
https://ibb.co/fGtb3w
https://ibb.co/k089Ow

**Comment by IbramCain** [comment]
Dosnt matter, its optifine.

**Comment by BluSunrize** [comment]
hilarious how you went from "no more mods, just IE" to "it's optifine".
That one totally counts as a mod and is specifically listed for compatibility.
