### ISSUE TITLE
Mekanism Compatibility Issue

### ISSUE THREAD

**Issue by JDuskey** [BluSunrize/ImmersiveEngineering#254]
Wires cannot transfer energy from mekanism blocks.

**Comment by BluSunrize** [comment]
Works perfectly fine for me. Picture of your setup?

**Comment by Bunsan** [comment]
Do you have CofHCore in the instance? Although it isn't listed anywhere CofHCore is a dependency of Mek. It is unable to interact with other RF systems without it.

**Comment by BluSunrize** [comment]
Reopen if necessary
