### ISSUE TITLE
[1.11.2] Render textures (glitches)

### ISSUE THREAD

**Issue by KorDum** [BluSunrize/ImmersiveEngineering#2540]
![ljpz1wbnzke](https://user-images.githubusercontent.com/1331559/31288913-90c93fd0-aacf-11e7-95a1-b8495d31da4a.jpg)

![exffbnmmcqy](https://user-images.githubusercontent.com/1331559/31288925-99f5c574-aacf-11e7-9427-aa271e4cfe74.jpg)

Without and with Optifine.
[Modes](https://gist.github.com/KorDum/37c98094557b3d5e3d523ead6377be23)

**Comment by BluSunrize** [comment]
That's not a modlist, that's just a list of loaded APIs.
Also, 1.11 is generally not supported anymore.

**Comment by KorDum** [comment]
Too bad!
