### ISSUE TITLE
[0.12 - 73] Not working on 1.12.1

### ISSUE THREAD

**Issue by YOYOK9** [BluSunrize/ImmersiveEngineering#2541]
The latest version of IE doesn't work with minecraft version 1.12.1

Picture of minecraft client:
https://puu.sh/xSlEk/a73401b948.png

FML Log:
https://pastebin.com/F2hS05bW

------------------------------------------------------------------------------------

Minecraft Version: 1.12.1
Immersive Engineering: 0.12-73
Forge: 14.22.1.2485

**Comment by BluSunrize** [comment]
dafuq. I thought I specically made that work :V

**Comment by malte0811** [comment]
Apparently [ForgeGradle automatically sets the MC version in the @Mod annotation](https://github.com/MinecraftForge/ForgeGradle/blob/a228a836a2dc5ce546d2d53c48760f52f082d7ad/src/main/java/net/minecraftforge/gradle/user/patcherUser/forge/McVersionTransformer.java#L61-L66) if none is set.

**Comment by BluSunrize** [comment]
Yep, found that too. Working on a fix rn
