### ISSUE TITLE
Snow stops windmill

### ISSUE THREAD

**Issue by bob0bob** [BluSunrize/ImmersiveEngineering#2544]
When it snows,  the wind mill stops because a snow block shows up on the wind mill.

**Comment by BluSunrize** [comment]
LOL!
That is some of the best vanilla-introduced error I've ever heard about.

I'll look into it in the future ^^

**Comment by bob0bob** [comment]
I seemed to get around it by placing a torch on the dynamo unit for now.
![2017-10-08_14 10 18](https://user-images.githubusercontent.com/30982580/31319989-926b694e-ac32-11e7-84af-aa464afaa272.png)

**Comment by techbrew-mc** [comment]
Same. I've resorted to putting glowstone above the dynamo - keeps snow from accumulating.

**Comment by mindforger** [comment]
insert alternative heater block function suggestion here :D

**Comment by savebyj** [comment]
I added a steel scaffolding cover and it solved the issue.

**Comment by SirChamomile** [comment]
I feel like this might be a necropost, but sorry I didn't want to make a new topic. This is newly relevant with an installation of Serene Seasons. I think it would be cool if all *running* machines counted as heat sources for the purposes of snow and ice accumulation. Then if you had things sitting outside there would be a nice ring of melted snow around each machine. It would be more ... immersive.

**Comment by mindforger** [comment]
all of my yes ... but only for active machines or those who have an power consumption if possible :D

**Comment by Palingenae** [comment]
Sorry for necropost, but, this happenned today. 

Is that even fixable?

![image](https://user-images.githubusercontent.com/6728594/56591622-576c2000-65e9-11e9-9dea-5d119c6905e5.png)

**Comment by Shadows-of-Fire** [comment]
It should be fixable, the top of the windmill blocks just needs to be marked as non-solid.

**Comment by Mykosayyad** [comment]
I got the same issue but the torches didn't help fix it.
![image](https://user-images.githubusercontent.com/102385088/166157802-d3c4ee63-df7b-4a0c-bce5-f9b93fac63f6.png)

**Comment by BluSunrize** [comment]
Please don't comment on an issue that was closed 2 years ago.
Also, there literally isn't even any snow on your windmill.
