### ISSUE TITLE
[1.10.2] Tesselating block in world: IllegalArgumentException: Cannot set unlisted property net.minecraftforge.common.property.Properties$1@42546d09

### ISSUE THREAD

**Issue by max3001** [BluSunrize/ImmersiveEngineering#2545]
### Before reporting:
(There doesn't seem to be a duplicate, couldn't find anything scouring gitHub and the web.)

### Description of the issue:
Minecraft Launcher reports: "The game crashed whilst tesselating block in world".
This is a multiplayer server with the Age of Engineering modpack. I use Vivecraft and believe it's related because other players w/o Vivecraft don't have the issue. That said, it may be indirectly related, i.e., I disabled a lot of animation and tweak quality settings.

I initially had a similar issue related to an IE connector in a specific chunk. The world position mentioned in the "Block being tesselated" section of the crash report didn't contain the connector but I simply removed all connectors from that chunk. After doing this, I started getting crashes for various other IE blocks - the crash reports contain two different blocks.

The stack trace seems to point to a missing Properties.AnimationProperty on an IE block. I naively tried enabling all Animations in Video Settings, but crashes continue happening.  Since net.minecraftforge.common.property.ExtendedBlockState doesn't contain a "setProperty", it appears the object needs to be created with the AnimationProperty in the first place. I'm unclear where the ExtendedBlockState is created.

Note that while team.chisel.ctm.client.state.ChiselExtendedState.withProperty is called between IE and forge, I *believe* that call doesn't do anything dangerous per se and just results in a pass-through.

### Crashlog:
https://pastebin.com/Dqs7XS53
https://pastebin.com/8z51DbwX

### Versions & Modlist
ImmersiveEngineering-0.10-61.jar
Forge 12.18.3.2316 Optifine OptiFine_1.10.2_HD_U_E3 112 mods loaded, 112 mods active
(other mods listed in crash reports)

**Comment by malte0811** [comment]
I'd guess this is an incompatibility between Chisel and Optifine or maybe Vivecraft. We do not support Optifine and we (at least I) do not have access to a Vive to debug incompatibilities with ViveCraft (I honestly didn't expect IE to work with it at all).
And to add to that 1.10 isn't supported any more.

**Comment by max3001** [comment]
Vivecraft + Optifine has been working fine so far (been using it for a month) and I doubt it's related to chisel. I've had 20+ of these crashes and every time it's an IE block, never anything else. That said, I appreciate the quick response and I'll simply steer clear of IE for now. Thanks - Max

**Comment by max3001** [comment]
For posterity, I'm pretty sure the issue was related to lanterns. The game kept crashing and I kept removing IE stuff up to the point when I removed lanterns. It stopped crashing after that. Used to crash within 15 mins, got a solid 2 hours just now.
