### ISSUE TITLE
Immersive crash on server side with version 73 or 74

### ISSUE THREAD

**Issue by xKnightGamingx** [BluSunrize/ImmersiveEngineering#2546]
https://gist.github.com/xKnightGamingx/b886dde3f2cc982fda1ec0902484c992

**Comment by Rikshy** [comment]
This looks like an equal crash i get.
https://gist.github.com/Rikshy/83b041bb7818390b5d7bd48d7c10595b
just to provide some more evidence.

A description of the setup (if neccessary):
There are 2 garden cloches with the bottom block in the ground ontop of a magneticraft waterblock.
Energy input is a HV Connector on the top.

Befor the Server crashed i saw a wierd rendering of the cloches, where each the 2 bell blocks were a full cloche facing horizontally.
(sorry if that sounds wierd, i'm no native speaker :S)
