### ISSUE TITLE
Update for 1.12.2 invalidated 1.12

### ISSUE THREAD

**Issue by IamAlathe** [BluSunrize/ImmersiveEngineering#2547]
I just updated a few mods including IE.  Update log indicates the point of the update was to make it work in other 1.12 versions. 👍  However, upon attempting to load I received an error screen which indicated I need 1.12.2 not 1.12.   I'll roll back until a fix is done. 😸 

![screenshot 19](https://user-images.githubusercontent.com/23068703/31322219-0bfbd10e-ac51-11e7-9b0a-342f643786c6.png)

**Comment by BluSunrize** [comment]
Go update to 1.12.1 or 1.12.2
IE uses a version of Forge not available for 1.12

**Comment by IamAlathe** [comment]
Fair enough.  Thanks for the reply.  I'd rather know it was intentional that think it was a mistake. :)

**Comment by BluSunrize** [comment]
I'm also pretty sure I marked it as 1.12.1 and 1.12.2 only on CurseForge.
I tried getting it to work on 1.12 before release but couldn't run recomp tests on an older Forge version to check it, so I left that mandatory version in.
