### ISSUE TITLE
[1.10.2] Item Id Conflict with Thermal

### ISSUE THREAD

**Issue by jelaw21** [BluSunrize/ImmersiveEngineering#2550]
### Description of the issue:
Creosote not rendering and cannot remove from oven. 
![image](https://user-images.githubusercontent.com/21100827/31356596-9552622c-ad0c-11e7-953e-64377a745e75.png)

### Crashlog:
There is no crash log, but the DefaultFluidList does not show thermal's creosote as mentioned previously in issue reports as a workaround.

### Versions & Modlist
forge-1.10.2-12.18.3.2422
IE 0.10 - 61

[modlist.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1369722/modlist.txt)

**Comment by mindforger** [comment]
known issue, but 1.12 is the only supported version now, you can remove creosote from from registry (backup world first) and reload the world, that should fix it.

happens mostly when IE is added to a world with another creosote oil earlier registered
