### ISSUE TITLE
[SOLVED] [1.10.2] IE-61 Manual crashes with JourneyMap

### ISSUE THREAD

**Issue by Bob74** [BluSunrize/ImmersiveEngineering#2551]
### Description of the issue:
Game crashes when using the **Engineer's Manual**. No action needed, the page can stand still and it will still crash.
I've encountered the problem in single and multi-player.

The issue looks a lot like this one (seems like the same error as I can see): https://github.com/BluSunrize/ImmersiveEngineering/issues/1704

**To reproduce:**
- Create a new profile on **Twitch** using **Forge 12.18.3.2511 (1.10.2)**
- In the mod folder of the profile, paste the two mods (**IE** and **JourneyMap**)
- Start the game and create a new world in **Creative** mode
- Get the **Engineer's Manual**
- Open a page (ie: **Ore processing**), it seems to crash on any pages
- Wait ~2 to 5 minutes (no need to interact with the book) and Minecraft should crash (it does even if you interact with the book)

### Crashlog:
_hs_err_pid7852.log:_ https://pastebin.com/mCNdW4Yp
_replay_pid7852.log:_ https://pastebin.com/nPzrEWVZ (shorten a little bit due to 512kb pastebin limit)
_logs/latest.log:_ https://pastebin.com/RqP3i2QM

### Versions & Modlist
_Forge 12.18.3.2511 (1.10.2)
ImmersiveEngineering-0.10-61.jar
journeymap-1.10.2-5.5.0.jar_

Updated Java & Java 64 to 1.8.0_144.

**Comment by Larky2k** [comment]
what version of Java you running?

**Comment by mindforger** [comment]
>what version of Java you running?

>JRE version: Java(TM) SE Runtime Environment (8.0_25-b18) (build 1.8.0_25-b18)
(from his logs)

download a newer version of java and assign the launcher to use the installed java instead of the internal minecraft version of java runtime

**Comment by Bob74** [comment]
I already had updated Java to 1.8.0_144 but I didn't know Minecraft would use an internal and older version (that doesn't appear when I list Java versions on my computer)...
I forced it to use the installed (and updated) one and it seems to work!
The game isn't crashing anymore.

Thank you, I'm glad it's not a mod related issue!

**Comment by mindforger** [comment]
yeah ... i hope mojang will upgrade at some point ... the internal version is ridiculously old
