### ISSUE TITLE
[1.12.1] (IE 0.12-74) Fluid Outlets and Modded Liquids 

### ISSUE THREAD

**Issue by Vollauro** [BluSunrize/ImmersiveEngineering#2553]
### Description of the issue:

The Fluid Outlets don't function correctly if used with modded liquids such as Creosote Oil from Immersive Engineering. I also tried using liquids from other mods; Tinker's Construct, Thermal Expansion or Tech Reborn. On the other hand they function with both Water and Lava for the most part, missing the last few blocks when using Lava. 

Screenshot of some testing I did on a separate minimal install with liquids from IE and Vanilla.
![](https://i.imgur.com/4XM4rdl.png)

I tried it both with FTB Unstable 1.12.1, where I noticed the problem, and with a minimal install with Forge, IE and JEI, to make sure it wasn't an compatibility issue between mods, through the Curse/Twitch client.

### Versions & Modlist:
[The manual crashlog for the modlist on a minimal install.](https://gist.github.com/Vollauro/666200dc6187003d5e52a243a899c2b6)

**Comment by natedogith1** [comment]
I'm encountering a similar issue.  From looking at the code, I think the issue is that the code is asking "is this a full block of fluid" but a flowing downward block is a full block, but isn't a source block.
