### ISSUE TITLE
[1.12]Twitch Launcher downloads v73 and Client says it's for 1.12.2

### ISSUE THREAD

**Issue by Arkyo** [BluSunrize/ImmersiveEngineering#2554]
### Description of the issue:
v73 is for 1.12.1/2 in the curseforge release page,but is being downloaded by Twitch Launcher.

**Comment by malte0811** [comment]
Use build 74.

**Comment by Arkyo** [comment]
Build 74 isn't in Twitch Launcher @malte0811

**Comment by BluSunrize** [comment]
It is, just not for 1.12.
Go update to 1.12.1 or 1.12.2

**Comment by Arkyo** [comment]
But I am finding the build for 1.12.0 XD
I'll stay on 71 then
Thanks

**Comment by mindforger** [comment]
this has been a unfortunate one time misshap and fixing invlolves to beg curse for changing the stuff ... 

it's not that easy and maybe unneccesary to bother either dev or curse imho

**Comment by BluSunrize** [comment]
It's not an "unfortunate misshap"
IE was build on a Forge version for 1.12.1 or later. It's not available for 1.12.0

The majority of mods is compatible, go update.

**Comment by Arkyo** [comment]
Thank you, I understand everything that you've replied. BlueSunrize
But what I want is 1.12.0 not any later versions so
I said I'll stay on 71
