### ISSUE TITLE
Crash on SkyFactory: I can't start the server.

### ISSUE THREAD

**Issue by jariojose** [BluSunrize/ImmersiveEngineering#2555]
[Java Exception output](https://gist.github.com/jariojose/acdb252ed1c03adf21c3254d39e234bd)

**Comment by mindforger** [comment]
please edit the wall of text and move it to a pastebin link ir soemthing

a wall of text is not pleasing to read and the contribution guidelines clearly state you to spoiler it :)

To the actual issue: Nice infinite loop there, something with the config seems off! please also upload your IE config.

**Comment by jariojose** [comment]
Sorry lol!
All right!!
I am doing it now! ;)

**Comment by malte0811** [comment]
Do you by chance have a "normal-ish" JVM (OpenJDK or normal Oracle) on your server? I suspect that this is caused by the IBM JVM, though the bug may still be on our side.
IBM JVM doesn't require a licence any more, right?

**Comment by mindforger** [comment]
okay i am a little boggled 

>        I:ore_lead <
>            6
>            8
>            36
>            4
>            100
>         >

is there no commata required for entry separation in this file format when using linebreaks?

**Comment by jariojose** [comment]
I am using the default file in config.

**Comment by jariojose** [comment]
In my Desktop, the server works without problems. But, only IBM, it crashes.

**Comment by jariojose** [comment]
Here, the java -version

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 8.0.5.0 - pxz6480sr5-20170905_01(SR5))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux s390x-64 Compressed References 20170901_363591 (JIT enabled, AOT enabled)
J9VM - d56eb84
JIT  - tr.open_20170901_140853_d56eb84
OMR  - b033a01)
JCL - 20170823_01 based on Oracle jdk8u144-b01

**Comment by malte0811** [comment]
I'll see whether I can get their JVM/JDK working on my (linux) laptop, otherwise I'll need someone to run some code for me.

**Comment by jariojose** [comment]
malte0811, I can give you 1 instance for test. 
Do you want?

I need a e-mail to do this. Private msg. 


Do your github e-mail 'malte0811@web.de' works?

**Comment by malte0811** [comment]
Thanks for the offer, but I managed to get it working/crashing on my laptop.

**Comment by jariojose** [comment]
Nice, malte!! 

I am waiting here :+1: If you need help for something... :smile:

**Comment by jariojose** [comment]
When you have a solution, tell me, please. My server is working without IE at the moment.

Best!

**Comment by malte0811** [comment]
Intermediate results: The code that is crashing is somewhat stupid. It recursively calls itself for all fields with a type that has `Object` as the direct superclass. This is true for the sub-configs this is meant for, but also for arrays and strings. And IBM inserts a JIT helper in the string class that a) has a field containing itself and b) has `Object` as a direct superclass. I'll fix this later today (probably by annotating the sub-configs).
I haven't found a way to get rid of the JIT helper, which would be the only temporary workaround I can think of. I tried disabling JIT (-Xnojit) and setting it to interpreting only (-Xint), but I guess the helper is part of their String implementation.

**Comment by jariojose** [comment]
Nice, Malte!!! 

And me, I will continue waiting!!! NICEE!! *-*

**Comment by jariojose** [comment]
Malte, Thank you!!! Could you send me a release for 1.10 MC ?

**Comment by malte0811** [comment]
I would if I could. Blu owns the project and doesn't like people distributing custom builds. I am allowed to distribute builds for debugging purposes, but that isn't the case here.
If you know how to build and use git you can try using the 1.10 branch of IE, cherry-pick my commit into there and build that. You shouldn't distribute the build, but as long as you don't change the version number clients with the official build should be able to join. If you do this you should mention that you did it in any future bug reports (to IE and probably other mods as well).

**Comment by jariojose** [comment]
Thank you, for the support, Malte.

I am trying to build, but i am having errors to build with Waila.

I don't  know what to do... But, thank you! It is an error to SSL or HTTPS Protocol.

https://gist.github.com/jariojose/e1ca1cd6ffe1eb958aff0baf76398454

**Comment by jariojose** [comment]
Using the gradle from project, i having the following error: peer not authenticated

https://gist.github.com/jariojose/bc3cbcc13de2031bb9b3aaa53ee97393

**Comment by jariojose** [comment]
I am having problem with http://mobiusstrip.eu/maven Waila Maven Repo.
If you know other compatible repo... lol :+1:

**Comment by jariojose** [comment]
Fix: New Waila Repo: http://blay09.net:8081/artifactory/repo/

Thank for support, Malte!!!
