### ISSUE TITLE
[1.12.2] Missing texture on External Heaters

### ISSUE THREAD

**Issue by kwpugh** [BluSunrize/ImmersiveEngineering#2556]
After updating to v.74 all of the textures for External Heaters are missing on server.

Mod: ImmersiveEngineering-0.12-74.jar
Forge: forge-1.12.2-14.23.0.2512-installer.jar
SpongeForge: spongeforge-1.12.2-2503-7.0.0-BETA-2703.jar

See attached picture:  https://imgur.com/a/TmveZ

**Comment by malte0811** [comment]
#2552. Fixed for the next release. And SpongeForge is not supported.
