### ISSUE TITLE
[1.12.2] v0.12.74 Strip Curtain causes client crash from ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by the-ible** [BluSunrize/ImmersiveEngineering#2559]
Minecraft 1.12.2
Immersive Engineering 0.12.74
Java 8

While in creative mode, place a Strip Curtain.
Client immediately crashes.

**Crash log**  [https://gist.github.com/the-ible/7cd17d5759499919c57d37209c2c0fc1](https://gist.github.com/the-ible/7cd17d5759499919c57d37209c2c0fc1)

I am using a custom collection of mods. If you can't immediately reproduce this bug, let me know in the comments and I'll try removing mods until it stops happening.

**Comment by kulflame** [comment]
This is still an issue in ATM3 v4.3 (IE version 0.12.74).  One of my players placed a curtain and now he crashes at his base.  Is there a fix for this?

**Comment by malte0811** [comment]
You could try using the `/fill` command to replace the curtain (immersiveengineering:cloth_device) with air, you'd need to guess the rough location of the curtain though. If that doesn't work you'll have to wait for the next release.

**Comment by the-ible** [comment]
Have the crashing player reduce render distance to the minimum. Then get close enough to crash. Take the coordinates from the crash log and use the fill command similar to this
`/fill ~-32 ~-32 ~-32 ~32 ~32 ~32 minecraft:air 0 replace immersiveengineering:cloth_device 0`

**Comment by kulflame** [comment]
I used mcedit to remove them. 


Sent from Yahoo Mail for iPhone


On Sunday, October 22, 2017, 5:14 AM, malte0811 <notifications@github.com> wrote:


You could try using the /fill command to replace the curtain (immersiveengineering:cloth_device) with air, you'd need to guess the rough location of the curtain though. If that doesn't work you'll have to wait for the next release.
