### ISSUE TITLE
API to skip dropping items in invalidate()

### ISSUE THREAD

**Issue by planetguy32** [BluSunrize/ImmersiveEngineering#256]
See planetguy32/RemainInMotion#161

IE multiblocks' invalidate() method drops them as items. The calls that clean up TileEntities - World.removeTileEntity() and Chunk.removeTileEntity() - both call invalidate(). It looks like this would be very hard to fix without some help from Immersive Engineering. Would it be possible to get an API to suppress the drops on next invalidate() call or something similar?

**Comment by BluSunrize** [comment]
I only drops those as the multiblock gets broken, and only does that to the initial block you break. Why do you need to suppress it?

**Comment by planetguy32** [comment]
It turns out World has a built-in mechanism to suppress item drops that I can abuse, so no API is necessary. Thank you for your time, and sorry to bother you.
