### ISSUE TITLE
bucket wheel not aligning correctly with excavater?

### ISSUE THREAD

**Issue by RaymondIII** [BluSunrize/ImmersiveEngineering#2561]
![2017-10-14_14 40 34](https://user-images.githubusercontent.com/26178426/31579617-904da86e-b0ee-11e7-8b20-7e80cc25453a.png)
Yes, I built it on the inside of the excavator, yes I have tried logging out and in, this is the most recent version of IE. I have tried building both the wheel and excavator separate but both seem to end up with the wheel spawning like this, any ideas?
Minecraft version 1.12.2
IE version 0.12-74

**Comment by ThatGuy435** [comment]
Getting this same problem, Minecraft 1.12.2 with Forge 14.23.0.2515 - wheel seems to 'pop in' 90 degrees from the build orientation regardless of placement of excavator body.

**Comment by LazerusKI** [comment]
Same issue here, it even rotates on that axis.
![exca](https://user-images.githubusercontent.com/1797439/32527386-101131e0-c42e-11e7-8507-bef10b037002.png)
