### ISSUE TITLE
[1.12.2] "Compat module for tconstruct could not be preInitialized. Report this!"

### ISSUE THREAD

**Issue by ubergeek77** [BluSunrize/ImmersiveEngineering#2562]
### Description of the issue:
I'm in the process of setting up a new custom server modpack. Apparently, a module required for compatibility with Tinker's Construct fails to pre-initialize. When loading the server with IE and TConstruct, I can see this in the startup log:

`15.10 05:28:40 [Server] Server thread/ERROR [immersiveengineering]: Compat module for tconstruct could not be preInitialized. Report this!`

As instructed, I am reporting this. My server does not crash upon startup.

### Versions & Modlist
**Minecraft Version:** 1.12.2
**IE Version:** 0.12.74
**Tinkers' Construct version:** 2.7.4.34
**Forge Version:** 1.12.2-14.23.0.2515
**Java Version:** 1.8.0_151
**Modlist**: [Pastebin](https://pastebin.com/raw/HFQZZtfB)
**Server startup log:** [Pastebin](https://pastebin.com/raw/wUHfyuK1)

I tried loading the server with only Mantle, Tinker's Construct, and Immersive Engineering, and this issue _**did not**_ occur. There must be some incompatibility with IE and another mod.

I will be happy to help track this down in any way I can.

Thanks!

**Edit:** I just wanted to mention that Tinkers' Construct recently updated to version 2.7.4.34. In the above information, I was using version 2.7.3.30. However, this changes nothing, as the issue still occurs, and the logs are the same. I've updated the above information to include the version of Tinkers' Construct I am using.

**Comment by BluSunrize** [comment]
I'm unable to replicate this issue so far.
I'd recommend you do a binary search with the modlist, cutting it in half, and then halving that further with each iteration to find which mod causes the incompatability.

**Comment by ubergeek77** [comment]
Alright, I'll get to it. I think I'll start with all of my Coremods first,
due to their reputation for breaking things.

By the way, what in particular does this compatibility module do? I'm
curious about anything I can try that will make it clear that, "yeah, okay,
the compatibility module definitely isn't loaded."

**Comment by BluSunrize** [comment]
Well for one it allows creating constantan in the smeltery, from equal parts copper and nickel.
And the preInit bit also registers materials for TCon tools, allowing you to use Treated Wood and Constantan for tools and hempfiber for bowstrings.

As well as allowing TCon tools in the toolbox.

**Comment by ubergeek77** [comment]
Ok, thanks for the info. Definitely sounds like features I'll want to use.

I'll let you know as soon as I have any ideas on what's causing this.

**Comment by ubergeek77** [comment]
I have a bit more info for you, but it is a bit confusing.

Somehow, this issue is related to Thermal Foundation. After a long process of gradually adding mods until the issue occurred, then doing the same until the issue disappeared, I saw that the issue stopped occurring once Thermal Foundation was removed. Thermal Dynamics and Thermal Expansion don't seem to cause any problems, since the issue still occurred with both of those removed. Only when Thermal Foundation was removed from the rest of my mods did the issue with Immersive Engineering go away.

Here's the confusing part:
The issue doesn't happen when I load _only_ Immersive Engineering, Tinker's Construct, and Thermal Foundation, with their respective dependencies. Yet, when Thermal Foundation is removed from my long list of mods, the issue goes away.

This means there's at least one more mod that is causing an issue, but **_only_** when that mod is loaded alongside Thermal Foundation. Unfortunately, after spending a lot of time on this, I haven't been able to figure out which mod(s) that would be.

I know it would take you a long time to download every mod on my mod list, so if you want, I can upload a compressed archive for you with all the mods I have. Let me know if you'd like me to do that.

I hope this gives you enough information to get to the bottom of this!

**Comment by Gulduka** [comment]
Today after i Update Brandonscore and Draconic Evolution i run in the same problem like @ubergeek77 
But no Energy Generators work after the Update. Not from Immersive not from Thermal Foundation.
After i take down the Generators from Thermal Foundation and set it new there take up the work. The Kintec for the Windmill from Immersive still not working and store no energy in the cells from Thermal Foundation. If i start up my Server i got the same error message in logfile "Server thread/ERROR [immersiveengineering]: Compat module for tconstruct could not be preInitialized. Report this!" before i update Brandonscore and Draconic Evolution all works fine :-(

Help pls..

**Comment by royalcw** [comment]
I have a solution to this issue...was experiencing the exact same problem.  Go to the config folder cofh/thermalfoundation/common.cfg.  Go all the way to the bottom of the file and set:
B:"Tinkers' Construct"=false
This will stop all interference with all immersive engineering integration with TConstruct.

**Comment by derrickmehaffy** [comment]
Adding a link to the above issue: https://github.com/CoFH/Feedback/issues/636

**Comment by BluSunrize** [comment]
I believe this should be fixed on IE's side now, where possible.
