### ISSUE TITLE
Render Issues

### ISSUE THREAD

**Issue by darkshadow543** [BluSunrize/ImmersiveEngineering#2563]
The redering is acting funny, cannot screen shot it to easily, but it acts wierd
![2017-10-14_21 50 41](https://user-images.githubusercontent.com/14943673/31580882-30713956-b12a-11e7-9cfb-0600a70efb43.png)
It only appears to be the light and heavy engineering blocks which seem a bit shaky.
Pack: https://mods.curse.com/modpacks/minecraft/275535-naural-capitalism-revitalized
MC: 1.12.2
Forge: 14.23.0.2512
IE 12-74

**Comment by BluSunrize** [comment]
Forced crashlog, please?

**Comment by darkshadow543** [comment]
Ummm, how do I do a forced crashlog?

**Comment by Sandriell** [comment]
Hold down F3+C for a few seconds then release.

**Comment by darkshadow543** [comment]
Well, what ever was causing it, is now gone.
