### ISSUE TITLE
[Question] Uranium with Extremereactors & CoFH

### ISSUE THREAD

**Issue by ldog** [BluSunrize/ImmersiveEngineering#2564]
I'd prefer IE Uranium over Yellorium. Having a few issues getting it to behave properly.
For 1 thing I can't get it to generate, CoFH World is doing most of the oregen, but the Bauxite is being done from IE, yet no U. The config is proper. Realized it wasn't working and set retrogen. No go.

The other thing is I can't seem to find the right combo of settings for ER that makes all recipes produce IE U. Is it not registered in the Oredict? I disabled ER, loaded up and all recipes proper. Figured that would get it registered properly. Re-enabled ER and back to Yellorium dust and ingots.

**Comment by ldog** [comment]
So a bit more fooling around. I did get the Uranium gen from IE to work, just didn't take a large enough sample area I guess, but eventually stumbled on some. 

Never did get it to work from CoFH Worldgen, I thought it was immersiveengineering:ore:5 or something along those lines, but can't quite find it and it seems like the features to dump the internal configs from JEI is gone in 1.12.2. If anyone could give me the ID I'd appreciate it.

A bit of thinking and of course it is registered in the ore dict as uranium or there would be no mix with yellorium dust/ingots. I'm guessing it's on the Bigreactors end, and because it loads before IE it gets registered first. Since there is no Plutonium in IE (and I am not using IC2) it won't take the other override.

**Comment by BluSunrize** [comment]
IE's Uranium is oredicted and I don't do anything special with it. Not sure what causes the issue...

**Comment by bookerthegeek** [comment]
@ldog uwe mod tweaker to get the correct name
``` /mt hand```

As for the recipe output, you will need to either change the extream reactors config (if they even have that option) or use IMC (inter mod communication) to change the output again only if that mod supports it.

**Comment by ldog** [comment]
Thanks. Forgot about MT dump. Decided to quit fighting it, since it's mostly a cosmetic issue. It's likely whatever wierd way ER handles it, mostly designed to work beside IC2 uranium and fuck all else.
