### ISSUE TITLE
[1.10.2] CraftTweaker Support for Refinery; Error Adding Recipe

### ISSUE THREAD

**Issue by Sandriell** [BluSunrize/ImmersiveEngineering#2565]
### Description of the issue:
I am attempting to add a recipe to the Refinery to add support for using Forestry's Seed Oil in addition to Plant Oil.

I have tried the following:

`mods.immersiveengineering.Refinery.addRecipe(<liquid:biodiesel> * 8, <liquid:seed.oil> * 16, <liquid:ethanol> * 8);`

But I am getting the following error:

`[SERVER_ABOUT_TO_START][SERVER][ERROR] IE.zs:73 > a method available but none matches the parameters (minetweaker.liquid.ILiquidStack, minetweaker.liquid.ILiquidStack, minetweaker.liquid.ILiquidStack)
This is usually an error in your script, not in the mod
addRecipe(ZenTypeNative, ZenTypeNative, ZenTypeNative, ZenTypeInt )`

I verified with the "/minetweaker liquids" dump that the liquid names are correct.

`[SERVER_STARTED][SERVER]<liquid:biodiesel>, Biodiesel
[SERVER_STARTED][SERVER]<liquid:ethanol>, Ethanol
[SERVER_STARTED][SERVER]<liquid:seed.oil>, Seed Oil`

Issue or am I simply missing something obvious? Thanks.

### Versions & Modlist
IE: ImmersiveEngineering-0.10-61
Forge: forge-1.10.2-12.18.3.2488

Mod list: https://gist.github.com/Sandriell/0d011a66f70194143d13be1987776592

**Comment by malte0811** [comment]
You are missing the required energy as the last parameter.

**Comment by Sandriell** [comment]
Thanks! I assume that is just an integer for RF amount per recipe? 10 I think is the standard recipe.
