### ISSUE TITLE
[Feature Request] Fast graphics for transparent textures

### ISSUE THREAD

**Issue by TristenCocking** [BluSunrize/ImmersiveEngineering#2569]
As the title suggests, I feel like it would be a good idea to add fast graphics for transparent textures and switch them when the player switches to the 'fast' setting in video options. Much like what happens to leaves when switching from 'fast' to 'fancy'. I assume this would help frame rate issues for low end computers when Minecraft has to draw all these blocks clustered together (mainly scaffolding).

I know I can just make my own textures and load a resource pack but it would be nice to have this feature in the actual mod.

**Comment by BluSunrize** [comment]
Under normal conditions this would be possible, however, due the native integration with the ConnectedTexturesMod, using any renderpass but the CUTOUT_MIPPED one will result in invisible blocks.

@Drullkus would it be possible to add a flag to the texture's mcmeta files that allows an "override" renderpass when graphics are set to fast?

**Comment by Drullkus** [comment]
@tterrag1098
