### ISSUE TITLE
Using Agricraft seeds in the Industrial Squeezer.

### ISSUE THREAD

**Issue by jimmyh77** [BluSunrize/ImmersiveEngineering#257]
Is it possible to make agricraft seeds work in the squeezer, or is this some thing that needs to be coded?

Thanks

**Comment by TheQuantumGeneral** [comment]
Use the IE modtweaker support

You'll need Minetweaker 3 and Modtweaker 2 installed. 

eg:

//Squeezer
//OutputStack, OutputFluid, InputStack, Time in Ticks
mods.immersiveengineering.Squeezer.addRecipe(<minecraft:melon_seeds> * 4, <liquid:water> * 500, <minecraft:melon_block>, 240);

**Comment by mindforger** [comment]
is it me or won't the minecraft:melon_seeds and minecraft:melon_block need "<>"-brackets around their names ? well at least in my ftb-infinity script they only worked with brackets...

**Comment by TheQuantumGeneral** [comment]
Yeah they do, as comments on Github they're parsed differently as formatting. I did have them, they just disappeared.

**Comment by mindforger** [comment]
Github Markdown sometimes is a bit tricky, try to escape it via backslash and write it like \ \<mod:item>

**Comment by BluSunrize** [comment]
You don't need Modtweaker, my Minetweaker support is native in IE.
