### ISSUE TITLE
[1.7.10] Blue Power Alloys in Arc Furnace Bugged

### ISSUE THREAD

**Issue by thakyZ** [BluSunrize/ImmersiveEngineering#2570]
### Description of the issue:
When I smelt specific ore dusts in the Arc Furnace with Blue Power mod included in my instance of Minecraft, it doesn't correctly smelt the dust/ingots. For example, the silver dust/grit when placed in the Arc Furnace, they get automatically smelted into Blue Power's Blue Alloy Ingots without ever having Teslatite, in the modifier slot of the Arc Furnace

### Crashlog:
N/A

### Versions & Modlist
Immersive Engineering 0.7.5
Forge 10.13.4.1614

All other mods: https://pastebin.com/4EzV8jZU

**Comment by malte0811** [comment]
1. 1.7.10 isn't supported any more.
2. Are you seriously using an outdated version when the latest version for your MC version was published over a year ago?
