### ISSUE TITLE
Suggestion: Arc Furnace have auto-distribute option in GUI.

### ISSUE THREAD

**Issue by orionSquared** [BluSunrize/ImmersiveEngineering#2571]
Using version 0.12.74, the Arc Furnace does not have an option for auto-distribution to distribute all items across its 12 slots to take full advantage of the machine's multiple slots.This would be a fantastic feature that would be able to take full advantage of its power.

**Comment by Alex-hawks** [comment]
It will auto distribute if you are running Minecraft 1.12

**Comment by orionSquared** [comment]
I am running the 1.12 version, and it is not auto distributing. Will it only do this function if I pipe into the machine? That I haven't tried.

**Comment by BluSunrize** [comment]
It works when something is inserting into the furnace.
Hopper, etc. do the job properly.

Within the GUI, shiftclick doesn't work, but you can just drag the stack accross the slots? That distributes just fine and is a vanilla feature.

**Comment by EvilCooky** [comment]
I think orion suggests a auto stack splitting Button like in the Actually Additions Double Crusher or the Mekanism Factories
