### ISSUE TITLE
Draconic Magnet takes from Conveyor Belts

### ISSUE THREAD

**Issue by Lukas45** [BluSunrize/ImmersiveEngineering#2573]
### Description of the issue:
The Draconic magnet ((Advanced) Item Dislocator) is able to drag items from Conveyor Belts. As far as I understand, magnets should not be able to drag items away from Conveyor Belts.
I don't know if this is an error/oversight from IE or DE, so I put it here first.

### Versions & Modlist
Forge 14.23.0.2512
Replicated in a client with only:
Draconic Evolution 2.3.4.265
Immersive Engineering 0.12-74 (+ 74 core)
JEI 4.8.0.108

**Comment by BluSunrize** [comment]
Well, me and WayOfTime ages ago agreed on checking for the NBT tag "PreventRemoteMovement" on the Item Entity.
If @brandon3055 wants to check for that, that'd be rather cool.

**Comment by Lukas45** [comment]
Actually Additions magnet could use that treatment too!
@Ellpeck

**Comment by Ellpeck** [comment]
@Shadows-Of-Fire pls

**Comment by Shadows-of-Fire** [comment]
It is done

**Comment by brandon3055** [comment]
@BluSunrize Shouldn't be a problem. Will be in the next update. Just make sure you clear the tag from the stack properly so we dont end up with the issue where identical items dont stack because they have random nbt tags again.

**Comment by BluSunrize** [comment]
Cool stuff
