### ISSUE TITLE
[1.12.2] Fluid Pump does not preserve custom NBT

### ISSUE THREAD

**Issue by warlordjones** [BluSunrize/ImmersiveEngineering#2575]
### Description of the issue:
Because the Fluid Pump uses `FluidStack insertResource = new FluidStack(fs.getFluid(), amount)` instead of `FluidStack insertResource = fs.copy()` any NBT Tags on the extracted fluid are not preserved. Only if the fluid is pressurised is passed onto the resultant stack. This breaks not only other mods but the Potion fluid from IE (tested and confirmed).

### Versions & Modlist
Latest (I know you said that isn't valid but I'd say this is an exception since I confirmed the problematic line(s) still present in the current Github code :P)

**Comment by BluSunrize** [comment]
Huh, my bad there.
I'll look into that.
