### ISSUE TITLE
[1.12.2] Wooden Storage Crates

### ISSUE THREAD

**Issue by TheSnowyChickens** [BluSunrize/ImmersiveEngineering#2576]
Hello,
I have the bug , that some storage crates have one [ench:] tag, so they are not possible to stack.

![storage crates](https://user-images.githubusercontent.com/29357962/31868031-998af1a0-b799-11e7-89f3-ab172e13e174.png)

I think the picture say enough, if you need more info, ask me. :)

MC 1.12.2
Forge 2515
IE 74

**Comment by BluSunrize** [comment]
...How does this still happen :V

I'll give it a look, thanks
