### ISSUE TITLE
Metal press animation glitch

### ISSUE THREAD

**Issue by byrnane** [BluSunrize/ImmersiveEngineering#2578]
After 1-2 runs on the conveyor belt, the models of the ingot and the final product remains forever

![default](https://user-images.githubusercontent.com/12965194/31947638-f9e4991e-b8fe-11e7-83eb-30ff8020fe1f.png)
![default](https://user-images.githubusercontent.com/12965194/31947688-1f249972-b8ff-11e7-9477-d6178609afd0.png)

MC 1.12.2
Forge 14.23
IE 0.12-74
Optifine

**Comment by malte0811** [comment]
Try without Optifine. What other mods do you use?
