### ISSUE TITLE
[1.12.2] Metal Press doesn't show animation when it isn't powered

### ISSUE THREAD

**Issue by OneEyeMaker** [BluSunrize/ImmersiveEngineering#2579]
Hello.
Found this strange (I guess, client-side only) issue.
When Metal Press isn't powered *from external source* it doesn't shows animation (it doesn't push piston with mold down and up). But it's works perfectly.

Steps to reproduce:
- Build Metal Press
- Connect it to any source of energy (Capacitor/Wire Connector/etc.)
- Wait until it's fully charged
- Disconnect from energy source.
- Install mold into press (Gear Mold, for example).
- Toss some ingots onto conveyor belt to start processing.
Summary: Metal Press precesses ingots, plays sound, but doesn't show animation (of moving piston).

// MC 1.12.2, Forge build 2515, IE 0.12-74

**Comment by malte0811** [comment]
Is this on a dedicated server?
