### ISSUE TITLE
Crash Using Strip Curtain

### ISSUE THREAD

**Issue by BranTuna** [BluSunrize/ImmersiveEngineering#2581]
MC Version: 1.12.2
Forge Version: 14.23.0.2515
IE Version: 0.12-74
Crash Report: [Click Here](https://pastebin.com/tsi9hxem)
Description:

It don't seem to like it when placing down strip curtains. Was placing it on grass block next to snow.

**Comment by BranTuna** [comment]
Was looking at a completely different crash report, so I changed the title and updated pastebin link.

**Comment by malte0811** [comment]
Known and fixed. The next release should be out soon.
