### ISSUE TITLE
Suggestion: Arc-Launcher and Cattle Prod

### ISSUE THREAD

**Issue by LazerusKI** [BluSunrize/ImmersiveEngineering#2586]
Just some ideas i had that could maybe fit into the theme.

Arc-Launcher:
A tool that fires a lightning bolt which has uses as a tool and as a weapon.
Hitting a block with it emits a redstone signal, so you could toggle machines from the distance or activate secret redstone mechanisms.
Possible Upgrades:
High Voltage Module: Increases the radius to 3x3 around the impact, enabling it to hit multiple targets or trigger multiple redstone signals (cant be used with the HC Module)
High Current Module: Smelts blocks on hit and ignites enemies (cant be used with the HV Module)
Increased Capacitor: Increased Energy storage.

Cattle Prod:
Used to herd animals or shock enemies. one handed tool that can be used with the shield.
Hitting enemies with it stuns them for a short time. Animals follow the player when wielded.
Possible Upgrades:
Blades (Iron, Steel): Removes the animal-following from it and increases damage (cant be used with E.Regulators)
Energy Regulator: Removes the ability to damage entities. Hitting an animal lets them drop loot (leather, wool, feathers, eggs...) (cant be used with Blades)

**Comment by HappyPineapple** [comment]
Great Ideare love to see this in game!

**Comment by BluSunrize** [comment]
Currently no plans for additional weapons in IE.
