### ISSUE TITLE
No Advancements with UniDict and Thermal Foundation

### ISSUE THREAD

**Issue by chillar85** [BluSunrize/ImmersiveEngineering#2588]
### Description of the issue:
Using UniDict to only  have 1 type of ingots makes it so that if the ingot is not from IE you cant advance past "The Upgrade - Create a Steel Ignot" and therefore makes it impossible to advance any further.

### Versions & Modlist
Minecraft 1.12.2
Forge 14.23.0.2520
Immersive Engineering 0.12-74
UniDict 1.12-1.0
Thermal Foundation 1.12-2.3.6.16

**Comment by malte0811** [comment]
Does this still happen with UniDict 1.1?
@WanionCane Is this meant to be fixed in 1.1 as well?
(I'm asking both of you in case one of you doesn't answer)

**Comment by WanionCane** [comment]
it is probably fixed.

**Comment by malte0811** [comment]
I'll close this then.
