### ISSUE TITLE
Feature Suggestion: Naitive Pipes

### ISSUE THREAD

**Issue by Alex33212** [BluSunrize/ImmersiveEngineering#259]
First off, I'll just say that I love this mod. A lot. It's just so... immersive. And, as with many things I am interested in, I have a few ideas for expanding it. This is one of them; naitve (as in, included with the mod. as opposed to being that of another mod) pipes.

Now, the pipe system I envision would not be like the pipes of BC or TE. Instead, it would be a system that takes into account gravity, suction mechanics, etc, as well as allow diagonal piping, side-by-side pipelines, and other such things.

I'm still fleshing it out, and will edit this/post a comment detailing what I envision.

**Comment by AEnterprise** [comment]
sugestions like this have already been rejected in the past, you can use bottles and transport belts to achieve the same result

**Comment by BluSunrize** [comment]
What AEnterprise said.
