### ISSUE TITLE
[1.12] Block Duplication with elevators.

### ISSUE THREAD

**Issue by Thutmose** [BluSunrize/ImmersiveEngineering#2592]
### Description of the issue:
When attempting to make an elevator out of a tank (or I assume other multiblocks as well) it duplicates some of the blocks used.  In the case of the tank, it duplicates the iron sheet metals.  This shouldn't have happened as the TEs were marked as invalid before converting (chests don't drop their inventories, etc).

In an attempt to fix it on my end, I tried to set formed to false before removing any of the blocks, but it still dropped the blocks on conversion.

Here is a video of the bug in action: https://youtu.be/deHIEZl3EVg

I also noticed that on my elevator the windows in the tank were transparent, but not while rendering in world, is this a bug on my end, or a bug in the render for world?

### Versions & Modlist
```
	| State     | ID                   | Version      | Source                           | Signature                                |
	|:--------- |:-------------------- |:------------ |:-------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft            | 1.12.2       | minecraft.jar                    | None                                     |
	| UCHIJAAAA | mcp                  | 9.42         | minecraft.jar                    | None                                     |
	| UCHIJAAAA | FML                  | 8.0.99.99    | forge-1.12.2-14.23.0.2529.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                | 14.23.0.2529 | forge-1.12.2-14.23.0.2529.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | immersiveengineering | 0.12-74      | ImmersiveEngineering-0.12-74.jar | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJAAAA | thutcore             | 5.11.8       | thutcore-5.11.8.2.jar            | None                                     |
	| UCHIJAAAA | thuttech             | 6.0.8        | thuttech-6.0.8.jar               | None                                     |
```

**Comment by BluSunrize** [comment]
IE multiblocks do not support being moved or anything like that.
They don't support what Quark does to pistons, they don't support Framez or Funky Locomotion, and they don't support this.

If you have a way for me to flat out prevent them from working on it, I'll gladly use that, beyond that it's the user's common sense to not try to move an active multiblock.

**Comment by Thutmose** [comment]
Not supporting movement is fine, the issue here is that, even when the TE is marked as invalid (ie te.invalidate() was called, and isInvalid() returns true), it still drops its blocks, if it reverted back to the structure, that would be fine, if it didn't drop anything, that would also be fine, but a TE marked as invalid shouldn't drop anything when it is removed from the world.

there should probably be a check for invalidity here: https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/blocks/TileEntityMultiblockPart.java#L277

Is there any method I can call to invalidate the entire structure before attempting to move the blocks it was made from? Then the multiblock will need to be re-assembled with the hammer when it turns back to  blocks, but it will no longer mass duplicate blocks.

I can add in a tile entity handlers for dealing with the multiblock TEs, I can loop over the TEs which will be affected before removing their blocks, and can call whatever method is needed to invalidate the structure then.
