### ISSUE TITLE
[QUESTION] Excavator configuration

### ISSUE THREAD

**Issue by Mewr11** [BluSunrize/ImmersiveEngineering#2594]
Is there any way to add/remove ore vein types from the excavator? I'm making a modpack, and would like to be able to use the excavator for advanced/late game ores, and not have copper/tin/iron show up when you already have a couple thousand of each.

**Comment by OneEyeMaker** [comment]
Use CraftTweaker
Syntax:
https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/util/compat/crafttweaker/Excavator.java#L26
https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/util/compat/crafttweaker/Excavator.java#L76
https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/util/compat/crafttweaker/Excavator.java#L121

**Comment by Mewr11** [comment]
Thanks. Just a couple of questions:
* Most of the arguments are self-explanatory, but I can't figure out `mineralWeight` or `failChance`. What exactly do they mean / what are good default values for them?
* Should `chances` sum to `1` or `100`?
* Is `name` simply the name that shows up in the excavator's notebook page?

**Comment by malte0811** [comment]
> Most of the arguments are self-explanatory, but I can't figure out `mineralWeight` or `failChance`. What exactly do they mean / what are good default values for them?

`mineralWeight` is how common the mineral is. Iron has weight 25.
`FailChance` is the chance of the bucket being empty. Iron has 0.1 (10%).

> Should chances sum to 1 or 100?

It doesn't matter. There are some veins that can contain non-IE ores, so the chances are just relatice to the sum of the chances of all valid ores in the vein. IE's veins usually sum up to 1 if all ores are valid though.

> Is name simply the name that shows up in the excavator's notebook page?

The manual will try to find a localization entry, but if there isn't one (there generally won't be one if you add one using CT), it will use the name you give it.

**Comment by Mewr11** [comment]
> The manual will try to find a localization entry, but if there isn't one (there generally won't be one if you add one using CT), it will use the name you give it.

Is there a list of names for the default minerals and/or a way to get all current minerals within zenscript?

**Comment by malte0811** [comment]
[This](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/IEContent.java#L885-L909) should be all mineral veins IE might register (The first parameter is the name). I don't think there's a way to get all of them in Zenscript, but I may be wrong.

**Comment by malte0811** [comment]
Closing this since it isn't a bug and you seem to have no more questions.
