### ISSUE TITLE
1.12: Balloon Shaders - All Black

### ISSUE THREAD

**Issue by LazerusKI** [BluSunrize/ImmersiveEngineering#2598]
IE: 0.12-74
Forge: 2532

Description:
Just wanted to check out some shaders, but for some reason they are all black on Balloons.

![exca](https://user-images.githubusercontent.com/1797439/32613406-1fa89a74-c56b-11e7-8902-88ca5cc027ba.png)

**Comment by BluSunrize** [comment]
I'll close this, given that you fully ignored the issue template.

**Comment by LazerusKI** [comment]
Sorry but what exactly did i do wrong?
I listed the Minecraft version (1.12)
I listed the IE version (0.12-74)
I listed the Forge version (2532)
I couldnt find another open issue
I described the issue and provided a screenshot of it
Since there is no crashlog i couldnt provide that
And since the issue appears even in a minimal environment with just IE installed i didnt mention a modlist (granted, the screenshot has some other mods in it)

**Comment by BluSunrize** [comment]
I mean, if you actually *read* the guidelines/template you'd have seen how to generate a debug crash.
You also didn't mention if it was a minimal environment or not.

**Comment by LazerusKI** [comment]
Well, i actually read it, but thought it doesnt matter since its listed under "what other mods were installed". Granted, its my fault for not mentioning that.

Here is the crashlog then

https://pastebin.com/Ef3hzJfc
created right after placing a balloon and using a shader on it.

Happens in both single and multiplayer by the way.
