### ISSUE TITLE
[Request] Alloy Kiln modtweaker support

### ISSUE THREAD

**Issue by ldog** [BluSunrize/ImmersiveEngineering#2599]
Looking for modtweaker support for the alloy kiln, or if it exists, can someone tell me the handler?
I want to gate TE behind IE for a modpack I'm working on. The idea is to make the TE frames require steel plates and hardened glass. The steel is a done deal of course. The glass is a bit trickier since the only way to make it in 1.12.2 is with the Induction Furnace in TE. 

What I came up with for the glass is, obsidian gets made in TC smelter, pulverized in IE crusher and then made into glass in the alloy kiln. Arc furnace is too far advanced (not looking to make an "Expert" pack, just something a bit more integrated).

And when you gonna fix the blueprint crafting? You promised :P

**Comment by BluSunrize** [comment]
mods.immersiveengineering.AlloySmelter.addRecipe(ItemStack output, IIngredient first, IIngredient second, int time)

What did I promise about blueprints again? I forgot.

**Comment by mindforger** [comment]
i believe he referes to this https://github.com/BluSunrize/ImmersiveEngineering/issues/2567

**Comment by BluSunrize** [comment]
I fixed that! :V

It's just not released yet, I've been stupidly busy hte past weeks.

**Comment by ldog** [comment]
Awesomesauce!

Yes, 2567. I guess I could add those recipes with MT too, but I forgot what the are supposed to be. I guess I can fire up Infinity Evolved and see what they used to be.

**Comment by ldog** [comment]
mods.immersiveengineering.AlloySmelter.addRecipe(<thermalfoundation:glass:3> * 2, <ore:dustLead>, <ore:dustObsidian> * 4, 200);

Working like a champ!
