### ISSUE TITLE
[1.12.2] EntityChemthrowerShot causes ClassCastExceptions with non-living Entities

### ISSUE THREAD

**Issue by mallrat208** [BluSunrize/ImmersiveEngineering#2600]
Immersive Engineering version 0.12-74-281
Forge version 1.12.2-14.23.0.2528
Crash Report: https://gist.github.com/mallrat208/93bfbe1cfd1b16d73d677a3597ed5f4a 

When EntityChemthrowerShot impacts an Entity that is not an instance of EntityLivingBase, the game experiences a ticking entity crash due to a ClassCastException. Anything from an Arrow to a Fishing Lure that hits Chemthrower Particles can cause this crash to happen and it's fairly easy to trigger. The problem bit of code is [here](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/entities/EntityChemthrowerShot.java#L135
). Adding in a secondary check if the mop.entityHit an instanceof EntityLivingBase before actually casting it would be a super quick fix.

**Comment by BluSunrize** [comment]
@malte0811 possibly related to the fix that made Dragons and Crystals attackable?
