### ISSUE TITLE
Game Closes before entering Title Screen (1.7.10)

### ISSUE THREAD

**Issue by Roemmato** [BluSunrize/ImmersiveEngineering#2602]
### Description of the issue:
The game opens, Mojang screen shows, then close. No popups tell me something is wrong, or I am missing a file, just closes. Only happened when I dropped my IE mod into the mod folder when I removed it I could play again.

### Crashlog:

https://pastebin.com/e1Kh3KBg

### Versions & Modlist
IE 0.7.7 (1.7.10) and Forge Version is  v1.2.0.344. Forge 1.7.10 (Basing this off Tekkit Legends)

Mods: https://pastebin.com/eULuLQTT (Modified version of Tekkit Legends)
[crash-2017-11-09_21.22.57-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1461588/crash-2017-11-09_21.22.57-client.txt)

**Comment by malte0811** [comment]
1.7.10 isn't supported any more, but I think you need to update MinteTweaker to fix this.
