### ISSUE TITLE
[1.12.2] Mystical Agradditions Compatibility in Garden Cloche

### ISSUE THREAD

**Issue by MokahTGS** [BluSunrize/ImmersiveEngineering#2605]
### Description of the issue:
Seeds from the mod Mystical Agradditions (a Mystical Agriculture addon) are not compatible with the garden cloche.  They should be.

### Versions & Modlist
Mystical Agradditions 1.12.2.1.2.5
IE 0.12.74
Forge 2529

**Comment by malte0811** [comment]
Who says they should be? The author of the addon says they shouldn't, and aside from that adding compat on IE's side would be messy.
