### ISSUE TITLE
[1.12] crash while looking at the manual

### ISSUE THREAD

**Issue by beaussart** [BluSunrize/ImmersiveEngineering#2606]
### Description of the issue:
When I was looking at the manual, minecraft crached. But not a clasic minecraft crash, a java hs_err crash.

Another crash happends when I try to search somthing on the manual

### Crashlog:

There was no crash reppors but jvm dumps : 

* [hs_err file](https://gist.github.com/beaussart/8206c9cdcc99b4830080cae9579f07c0)
* [replay file](https://gist.github.com/beaussart/cba19b60bfcfa58d9d5bd89ac9238163)

### Versions & Modlist

| ID                        | Version                         | Source                                              |
|:------------------------- |:------------------------------- |:--------------------------------------------------- |
| minecraft                 | 1.12.2                          | minecraft.jar                                       |
| mcp                       | 9.42                            | minecraft.jar                                       |
| FML                       | 8.0.99.99                       | forge-1.12.2-14.23.0.2517.jar                       |
| forge                     | 14.23.0.2517                    | forge-1.12.2-14.23.0.2517.jar                       |
| immersiveengineering      | 0.12-74                         | ImmersiveEngineering-0.12-74.jar                    |

[Full modlist](https://gist.github.com/beaussart/4bff3c3e83543804c681f447edae0798)

**Comment by malte0811** [comment]
Update Java to the latest Java 8 (not 9) build. You are currently using the Java version the launcher ships with, which is 3 years old. You may need to manually set the Java version to use in the launcher. (We have no idea why this happens and we probably couldn't fix it if we did since it seems to be a bug in the JVM itself)

**Comment by beaussart** [comment]
I'll try, thanks :)

**Comment by Xiaminou** [comment]
You may want to leave this issue open for people who get this problem, my Java was (only) 1 year old but still had this issue.

**Comment by beaussart** [comment]
Good idea to put it in the guidelines!

The java version was the version bundled with the minecraft luncher, I didn't even know it was a thing!

**Comment by Xiaminou** [comment]
Hmm, you're talking about the other guy's version, I don't know which one mine used, but it still crashes after I updated JRE. I'm trying to update JDK, maybe that's what it's using.

**Comment by beaussart** [comment]
I had to manually set the minecraft luncher configuration to use my minecraft version instead of the embedded one, it's in the settings

**Comment by Xiaminou** [comment]
Wait really? Fucking hell Mojang! What the fuck is wrong with them.

**Comment by beaussart** [comment]
Yeah, and the embedded version is dating from a long time ago... Hence the crash :/
