### ISSUE TITLE
[Enhancement] Configurable item slots in Assemblers

### ISSUE THREAD

**Issue by dragonshardz** [BluSunrize/ImmersiveEngineering#2608]
Pretty much what it says on the tin - the ability to dedicate specific slots in the Assembler's buffer to only hold specific items would be very useful.

**Comment by BluSunrize** [comment]
I'm afraid that's not easily implemented or represented in the GUI.
Why exactly are you looking for this functionality?

**Comment by laz2727** [comment]
Probably just so it won't get jammed in dump-it-all item networks.

**Comment by dragonshardz** [comment]
Pretty much as @laz2727 says. Prevents jams in machinery systems that don't have "smart" autocrafting available from sources like RS.

**Comment by angelnc1989** [comment]
I thought a feature like that could be useful after setting up a lot of Assemblers.
Basically something similar to the RFTools Crafter where you can remember the current item configuration in the internal inventory.

**Comment by Terrapin47** [comment]
I'm finding that this would be a useful addition to the assembler, as well as to the arc furnace ( either just for "additional ingredients" or for both input inventories ).  When you're trying to make a factory with a bunch of different configurable inputs to a single arc furnace, it becomes hard to not clog it up.  Especially for the assembler, when you're trying to use all available materials to craft a three part recipe, it seems quite hard to manage in an automated way.

As far as representing it in the assembler's GUI, maybe look to EIO's Crafter for an example.  
![image](https://user-images.githubusercontent.com/13740412/42729270-30d3c3c6-87a0-11e8-9652-7904409792be.png)

The left side is representing the recipe and the output.  The right side is the actual inventory used by the machine which will only fill with the appropriate ingredients ( I only have 1 out of 3 cotton in the machine in this example ), and then the output.
