### ISSUE TITLE
Crash when search Blueprint recipe in NEI

### ISSUE THREAD

**Issue by bakaxyf** [BluSunrize/ImmersiveEngineering#261]
[log] (https://gist.github.com/bakaxyf/bdea479d8131738f4351) and [crash report] (https://gist.github.com/bakaxyf/dfdeb40f4f413de0c948)

**Comment by bakaxyf** [comment]
and the slag :P

**Comment by bakaxyf** [comment]
Problem solved when downgrade I Forestry version.
Sorry

**Comment by BluSunrize** [comment]
Would be helpful if I could still see the log

**Comment by bakaxyf** [comment]
https://github.com/ForestryMC/ForestryMC/issues/782
https://github.com/Tonius/NEI-Integration/issues/84

**Comment by BluSunrize** [comment]
ah good, I'm completely innocent x3
