### ISSUE TITLE
Shader Manual spawn command doesn't check if ingredients were consumed

### ISSUE THREAD

**Issue by gegy1000** [BluSunrize/ImmersiveEngineering#2614]
### Description of the issue:
At [MessageShaderManual#92](https://github.com/BluSunrize/ImmersiveEngineering/blob/495e2c5365235881285909cff65e087f945fdc1d/src/main/java/blusunrize/immersiveengineering/common/util/network/MessageShaderManual.java#L92), IE consumes the required player ingredients, and then gives the shader item. This relies on the client to have checked if the ingredients were present before sending the packet.
However, anyone with malicious intent could potentially send the packet without checking for ingredients, and the item would be given as normal, regardless of whether those ingredients were present.

**Comment by BluSunrize** [comment]
I'd consider this similar to #2615, as a non-detrimental issue.
I'll close this as further discussion can be handled on the other issue.
