### ISSUE TITLE
[Suggestion] Calculator compatibility?

### ISSUE THREAD

**Issue by AncientShotgun** [BluSunrize/ImmersiveEngineering#2617]
The Calculator Mod, authored by SonarSonic, adds non-tree crops.
It would be nice if you could add compatibility for the mod so people can grow Broccoli and other Calculator crops in their cloches.
Unless of course you've already done this and I'm blind.

**Comment by BluSunrize** [comment]
Could be something for Calculator to do on their side as well, I mean IE does have an API :V

**Comment by AncientShotgun** [comment]
As good a point as any. At any rate, I'm closing this.
