### ISSUE TITLE
Weird JVM crashes

### ISSUE THREAD

**Issue by mcenderdragon** [BluSunrize/ImmersiveEngineering#2618]
This always happens if I open  the Immaversive handguid. 
IE: 0.12-74
Forge: 14.23.0.2503
```
 # A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000074b831fa, pid=2372, tid=6292
#
# JRE version: Java(TM) SE Runtime Environment (8.0_25-b18) (build 1.8.0_25-b18)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.25-b02 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# V  [jvm.dll+0x4431fa]
 #
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
 # #\AppData\Roaming\.minecraft\1.12.1\hs_err_pid2372.log
#
# Compiler replay data is saved as:
# #\AppData\Roaming\.minecraft\1.12.1\replay_pid2372.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.sun.com/bugreport/crash.jsp
#
AL lib: (EE) alc_cleanup: 1 device not closed

```

**Comment by malte0811** [comment]
Read the contributing guidelines and set MC to use a newer Java 8 build.

**Comment by mcenderdragon** [comment]
So this is a know issue ? I am asking because this only happens with IE. And I know there no direct Crash but well everything is working fine except this and I can reproroduce it (it happend already 10 times)

**Comment by mindforger** [comment]
> # JRE version: Java(TM) SE Runtime Environment (8.0_25-b18) 

If you did change the used jre, you failed to choose the right one, because your log is proving you wrong

**Comment by mcenderdragon** [comment]
@mindforger, this log was before then, IF it happen again I will submid the new crash (most likely it will be the same)

**Comment by mindforger** [comment]
woha .. why did this end up so big? mobile posted, sorry for that

okay, noted, you post sounded like you have already tried it :) prior posting
