### ISSUE TITLE
Arc Furnace model issue

### ISSUE THREAD

**Issue by bakaxyf** [BluSunrize/ImmersiveEngineering#262]
![3 pz d91vd u k0h900 lc](https://cloud.githubusercontent.com/assets/10368307/9052503/bef4997e-3a9a-11e5-919e-70adc2c36ad1.png)
![y t6 gt9 u0_ur6w_k4_2c](https://cloud.githubusercontent.com/assets/10368307/9052507/c5ccd93c-3a9a-11e5-861c-71576fcef320.png)

**Comment by primetoxinz** [comment]
not an issue, you have to give it graphite electrodes

**Comment by bakaxyf** [comment]
I'm careless. but it only show two.
![6 keriy4_s b o 7 _0k9 y](https://cloud.githubusercontent.com/assets/10368307/9052785/63b1689a-3a9e-11e5-9ed1-6ec087129f99.png)
![image](https://cloud.githubusercontent.com/assets/10368307/9052770/3921582e-3a9e-11e5-9808-a5776891508c.png)

**Comment by bakaxyf** [comment]
![arc furnace](https://cloud.githubusercontent.com/assets/10368307/9053240/ec7c58a0-3aa4-11e5-954b-6aa1b520b090.gif)

**Comment by cobra** [comment]
There seems to be some desync between inventory and model when the furnace isn't powered. Give it some energy and it will display all electrodes.

**Comment by BluSunrize** [comment]
thanks for the input guys, all will be fixed in 5.1 =3
