### ISSUE TITLE
Garden cloche destroys excess seeds

### ISSUE THREAD

**Issue by Xiaminou** [BluSunrize/ImmersiveEngineering#2620]
### Description of the issue:
I apologize if this is intended.
Garden Cloche continues producing when its output has 3 stacks of seeds, it ends up destroying the excess seed.

### Versions & Modlist
Minecraft: 1.12.2
Forge: 2544
Immersive Engineering: 0.12-74
Mods: [list.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1483814/list.txt)

**Comment by BluSunrize** [comment]
Got a screenshot of the GUI for me?

**Comment by Xiaminou** [comment]
I'll do one better, here is a video of it happening: https://youtu.be/GHeg8oYdA4M

I forgot to say in the description it has to be 3 slots full of seeds and 1 empty slot. Once the last slot is filled it stops producing. This is a problem when you have it pulling out the produce but not the seeds.
