### ISSUE TITLE
Garden Cloche Balance issue

### ISSUE THREAD

**Issue by chrisbecke** [BluSunrize/ImmersiveEngineering#2622]
Forge: 12.18.3.2477
Immersive Engineering: 0.10-61
--
I presume the Garden Cloche was designed to be a low latency replacement for a "large" farm using real crop growth.

However, I feel that the balance point and mechanics of the Garden Cloche needs to be discussed, especially in the context of using Garden Cloches to power Diesel Generators:
 
* When harvesting melons, a Garden Cloche emits "Melons" not melon slices. Harvesting melons normally with an Axe emits 4+ melon slices - and other automatic farming solutions implement this.  Emitting whole melons could be regarded as an advantage except :- Melons cannot be crafted into slices, so none of the IE auto crafting solutions can turn melons back into slices that can be used (for example) in the Fermenter.

* One Garden Cloche easily out produces multiple Forestry Farms, or Calculator Farms, or IC2 Crop Harvesters. And this seems to have driven a level of power creep which makes Garden Cloches the only automatic farm solution that can possibly drive the production of Diesel to run Diesel Generators.

This, for example, is my test world in which I created Forestry Farms (with melons) in an attempt to provide Diesel to run 2 and then just 1 Diesel Generator(s) (The theoretical capacity of 1 Refinery).  All three Farms in the image were unable to produce sufficient seeds and melon slices to keep even 1 diesel with more than 50% uptime. Melons are being used as, per block of farmland, they appear to offer the highest output of materials for both the Squeezer and Fermenter. 

https://i.imgur.com/Y0Qm15t.png

Substituting all three farms with a single Garden Cloche provided an increase in Diesel Generator uptime. A mere 4 Garden Cloches brought 2 Diesels to 100% Uptime (using a Block Breaker/Block Placer to process the Melons)

https://i.imgur.com/qSNR9wH.png

**Comment by mindforger** [comment]
Update IE it had a balance pass and you are way behind

**Comment by Xenos13** [comment]
I needed at least 9 Garden Cloches with sugar canes and 6 ones with hemps to keep 1 Diesel 100% uptime.
IE 0.12-74

**Comment by mindforger** [comment]
oh he is using 1.10 sorry there won't be updates for 1.10 if i am not utterly wrong

**Comment by BluSunrize** [comment]
Correct, 1.10 is no longer supported!

**Comment by chrisbecke** [comment]
Just to clarify - Does the cloche produce melon slices in 1.12? Or is there an IE device that can un-melon melons?
