### ISSUE TITLE
[1.12] Book browsing crash

### ISSUE THREAD

**Issue by Night-Fire** [BluSunrize/ImmersiveEngineering#2623]
### Description of the issue:
While browsing the book, my game crashed twice.
The first time, it happened after several minutes and the second time, it happened just after i opened the book.

### Crashlog:
[Crash 1](https://pastebin.com/jg3mjVfn)
[Crash 2](https://pastebin.com/wnug7Lj0)

### Versions & Modlist
Minecraft version : 1.12.1
Forge : 14.22.1.2485
Immersive engineering : 12-74
Mod list : [List](https://minecraft.curseforge.com/projects/ragnamod-iv/relations/dependencies)

**Comment by malte0811** [comment]
Read the contributing guidelines, they contain a paragraph about this crash.

**Comment by Night-Fire** [comment]
Oh my bad. Thank you
