### ISSUE TITLE
garden cloche crash with multiple pipes 1.12.2

### ISSUE THREAD

**Issue by unstablecraft** [BluSunrize/ImmersiveEngineering#2627]
https://pastebin.com/YiFsqxSX
 forge: 2531
spongeforge: 1.12.2-2529-7.0.0-BETA-2736
modpack dire20 1.12.2
 discription crash with garden cloche when pipes placed on output results in crash-report in the pastebin

modlist: https://pastebin.com/NXt1xeiY

**Comment by unstablecraft** [comment]
https://pastebin.com/H2j0hLQs crash when with gardencloche and extrautils piping

**Comment by BluSunrize** [comment]
Known issue, fixed for next release.
You'll need to remove the belljar with MCEdit or something similar.
