### ISSUE TITLE
Magma Reservoirs

### ISSUE THREAD

**Issue by GoodBob** [BluSunrize/ImmersiveEngineering#2629]
Not sure if this is the right place for this. 

Core sample drills will sometimes show a chunk has a magma reservoir. How do you access this? The pumpjack afaik will only pump oil.

**Comment by lOmicronl** [comment]
This is from Immersive Petroleum, and addon, not from IE itself.

And since you say that you are "fairly sure" the pumpjack will not pump it... have you actually tried?

**Comment by BluSunrize** [comment]
Not my mod, not my problem =P

**Comment by GoodBob** [comment]
My bad. 

And yeah, i've tried lol
