### ISSUE TITLE
[Feature Request] lock chem thrower turret on, and/or excess fuel flare.

### ISSUE THREAD

**Issue by stresser1** [BluSunrize/ImmersiveEngineering#2631]
I'm building a private mod pack for a private server that features only multi block machines.

This pack obviously focuses on your mod as it's core. (Extreme reactors is the other main mod)

I would like some way to dispose of excess creosote. I built a chemical thrower turret and put it in front of a mob spawner, however, I'm producing it too fast. If the chemical thrower had some way to lock it "on" in suppression mode, it would be useful for an interesting functional display piece to get rid of creosote.

Alternately, if it could be piped to a flare to burn it off in large amounts at a time, that might be a fun addition, perhaps something to add to the refinery... if it runs out of space to store biodiesel or runs out of plant oil or ethanol, instead of stopping the draw of feed stock, it starts burning it off on the flare like a real refinery.

**Comment by BluSunrize** [comment]
Immersive Petroleum has a flarestack these days
