### ISSUE TITLE
[1.12.2] Bell-Jar Fertiliser Config Issue

### ISSUE THREAD

**Issue by AcidKat** [BluSunrize/ImmersiveEngineering#2634]
### Description of the issue:
When configuring Immersive Engineering to better suit my mod environment I discovered the "Belljar Fertiliser Base-Modifier":

>         # A base-modifier for all solid+fluid fertilizers in the belljar
>         D:belljar_fertilizer_mod=1.0

When set below a 0 value (e.g. 0.5) a strange behaviour occurs, it seems that the modifier actually causes the bell-jar to become _less_ efficient when running with a fertiliser present. I tried with the setting:

>         # A base-modifier for all solid+fluid fertilizers in the belljar
>         D:belljar_fertilizer_mod=0.5

And discovered these results:
Without Fertiliser: Growth Modifier: 0.5
With Bone-Meal: Growth Modifier: 0.31

I also tried this: 

>         # A base-modifier for all solid+fluid fertilizers in the belljar
>         D:belljar_fertilizer_mod=2.0

This returned:
Without Fertiliser: Growth Modifier: 2.0
With Bone-Meal: Growth Modifier: 5.0

Full Config:
https://pastebin.com/UY7xg18b

Latest.log
https://pastebin.com/NswkrUqi

### Versions & Modlist

**Only Tested in SP**.
**Tested again in a simplified environment (Fresh Forge 14-23-1-2554 install and IE 0.12-75) with config:**
https://pastebin.com/CNpF1rFb
Yields same results.

Minecraft Version: 1.12.2
Forge Version: 14-23-1-2554
IE Version: 0.12-75

Full Modlist (From a Forced-Crash Log):
https://pastebin.com/pKXSsvS6

**Comment by BluSunrize** [comment]
Known issue, fixed for future release
