### ISSUE TITLE
(1.12.2) Conveyor graphical bug

### ISSUE THREAD

**Issue by PsionicArchon** [BluSunrize/ImmersiveEngineering#2636]
Versions:
Forge: 14.23.1.2556
Immersive Engineering: 0.12-75

I and other players on my server are experiencing a bit of a graphical bug. 
Upon loading an area/joining the server certain conveyor belts will no longer be facing the correct direction.

This is purely graphical. Items will continue along the belts as if the orientation is still correct, often times floating directly through the belts.

Example: https://image.ibb.co/k93F7m/2017_11_27_23_48_47.png

The issue persists until the client is restarted, re-logging does not fix the issue.

**Comment by mindforger** [comment]
this maybe related to optifine, please test without to confirm the issue :)

also there is some issue with forge still loading chunk data multithreaded and not reliably returning the blockstates, which may can cause issues too but i think this is unrelated

**Comment by PsionicArchon** [comment]
Optifine is not installed. I can dump a mod list if it ends up being necessary.

**Comment by BluSunrize** [comment]
You were supposed to anyway, says so in the contribution guidelines.
Please try replicating the issue with just IE and Forge.

**Comment by malte0811** [comment]
Does running `/cie resetrender` and updating the chunks (F3+A) fix it? Does just updating the chunks fix it?

**Comment by PsionicArchon** [comment]
It's very difficult to reproduce because it seems to happen at complete random.

The server is vanilla with an average tps of 20 at 18.46ms

Modlist: https://pastebin.com/yNCVyNts

I'll let you know if the resetrender command works if/when the issue crops up again. Sorry I can't give you any more information at the moment as I cannot seem to deliberately create the issue.

**Comment by EternalPhane** [comment]
Same issue here, happens quite often in my case though.
Here's my modlist: https://pastebin.com/8UtzBc6n

Can be temporarily fixed by running `/cie resetrender` and updating the chunks.

**Comment by BluSunrize** [comment]
You have optifine installed, so that's invalid.

**Comment by malte0811** [comment]
I'm getting this in my dev instance, I'll look into it.
