### ISSUE TITLE
ImmersiveEngineering-0.12-75.jar  Core Sample Drill not working

### ISSUE THREAD

**Issue by Dohospody** [BluSunrize/ImmersiveEngineering#2637]
Direwolf 2.0 ( 1.12.2 )

Core sample drill not working with excavator. No information about veins under drill.

**Comment by mindforger** [comment]
@Dohospody PRETTY please .... read the contribution guidelines and rephrase your issue, it is rude to ignore them

**Comment by malte0811** [comment]
@Dohospody Did you connect power to the bottom block of the drill? It will play the animation even if it hasn't got power (That's a bug, yes). Is it playing the animation at all?

**Comment by BluSunrize** [comment]
Please provide the information requested in the contribution guidelines or I'll be forced to close this one.
Pictures of the setup, debug crash, Singleplayer/Server, etc.
