### ISSUE TITLE
No IE ores are generated

### ISSUE THREAD

**Issue by FlameTiJ** [BluSunrize/ImmersiveEngineering#2638]
Hello, as stated in the title, there won't spawn any IE ores in my world.
Using:
MC 1.12.2
Minecraft Coder Pack 9.42
Forge mod Loader 8.0.99.99
Minecraft Forge 14.23.0.2531
Modlist is here: [https://gist.github.com/FlameTiJ/590d01b54c7ec8e114eeab69a37ed7aa](url)
It's an Biomes O' Plenty world and only most of the thermal foundation's ores are being generated.
Already set the retrogen to 'true' for all ores but apparantly didn't do anything.
I am looking forward to your help :)
Sincerely Flame

**Comment by mindforger** [comment]
>only most of the thermal foundation's ores are being generated

thermal foundation has an config (at least in the past) to suppress other ores, check the configs

**Comment by FlameTiJ** [comment]
Ok, I will try that. Thanks for the idea :)

**Comment by FlameTiJ** [comment]
Ok, it was a problem with thermal foundation i.e. cofh. Had to add al the ores I wanted to the config files and make cofh retrogen.
Thanks again for your hint!
