### ISSUE TITLE
Game crash (no crash-report generated) several times while using IE manual.

### ISSUE THREAD

**Issue by Howsyomamanem** [BluSunrize/ImmersiveEngineering#2639]
I'm playing with IE in the new DW20 1.12 pack.  I have not altered the pack.  The crash is not generating a crash-report.  No exceptions in the log either.  The game just dies abruptly.  Every time it does, it's while I'm using the IE manual.

I do notice that the animation of the multi-block diagrams in the manual seem to be animating faster than I've seen in previous 1.10 packs.

I know I'm not giving you much to go on but this is all I have.

Is there an online version of the manual that I could reference instead of the in-game manual as a work-a-round?

Thanks so much.

**Comment by 1persON768** [comment]
Getting same thing, randomly crashing without crash log while browsing IE manual.

Versions:
Immersive Engineering : 0.12-75
Immersive Engineering core : 0.12-75-core

**Comment by mindforger** [comment]
>no crash-report generated

@Howsyomamanem if you would have read the contribution guidelines, you would know that you can press and hold F3 + C (while ingame, not start menu) for at least 6 seconds (better hold em until it crashes) to generate a debug crash report, you are also missing essential informations requested by said guidelines, please edit your post and update it with the required informations ;)

also you have a basic minecraft log file, that mosty probably contains a runtime exception either stating out of memory or memory access issues

a wild guess ito the blu (pun intended) you are running minecraft with stock Java Runtime which is decades old, please try again after downloading a proper newer version of the java runtime (download for 64bit, see "alternate versions" on the java home page, your browser will download 32bit most probably when hitting that default download button)

@1persON768 also please add a forced crash with F3 + C and check which runtime version your minecraft is working with

**Comment by Howsyomamanem** [comment]
Thx.  I’ll see if I can figure out those instructions…

Java version is pretty recent, though:

C:\>java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)

Thanks

Sent from Mail for Windows 10

**Comment by mindforger** [comment]
@Howsyomamanem are you sure your minecraft is using the system runtime? by default it uses it bundled build number 25 instead of the installed one ( i edited my post a bit for more and clearer details so you didn't know because email does not update :D)

**Comment by Howsyomamanem** [comment]
Wow… it didn’t occur to me that that new launcher had a bundled (2 y/o) version of java.  I’ve reverted to the older launcher and configured it to use my system version of Java.  The animations in the book look more normal now.  I’ll see how it goes. 

Thanks.

Sent from Mail for Windows 10

**Comment by mindforger** [comment]
your welcome, guess it can be closed then, you can do it but you would have to log into github or wait until blu or malte comes along :)

**Comment by 1persON768** [comment]
@mindforger I updated my Java and changed the workpath of Java from native launcher to match the new one, not the default from MC folder.

Been able to scroll through the manual for over 5minutes now so it seems to be fixed.

Thank you sir!

**Comment by mindforger** [comment]
@malte0811 did find the issue as far as i know (or Blu maybe?), so thanks to them, i just answered faster than him to help out :D
