### ISSUE TITLE
Disable-able OreDict Tooltips.

### ISSUE THREAD

**Issue by Fortist** [BluSunrize/ImmersiveEngineering#264]
While useful for some, I personally dont need it showing up, especially for every ingot and block without it being under a "Shift" key for sort, or just completely disabled.

**Comment by BluSunrize** [comment]
Yep, known issue. It's a debug feature of mine I forgot to remove (again >_>)

**Comment by Fortist** [comment]
Ah, no problem then. Some of us thought it was a feature. Thanks
