### ISSUE TITLE
[Suggestion] Current Transformer Redstone Output

### ISSUE THREAD

**Issue by AgentA1cr** [BluSunrize/ImmersiveEngineering#2643]
I would be useful if the current transformer could output an analog redstone signal based on the current flowing through it, perhaps directly connecting to redstone wires or maybe through the use of a comparator or probe connector.

**Comment by malte0811** [comment]
Have you actually tried using a comparator? It should work, the "problem" is that it shows current relative to the maximum the connected wires can carry, so 2048 for 15 with LV wires.

**Comment by AgentA1cr** [comment]
I'm currently testing with a comparator and a current transformer hooked to MV. On right click, the transformer indicates 2003 Flux/t (out of 8192 max, about 24%, 24% of 15 being about 3.6). The comparator is not outputting a signal. 
As it appears this may be turning into a bug report, I'm running Immersive Engineering 0.12-75 and Forge 14.23.1.2555. 
Here is a screenshot of my setup:
![2017-12-04_20 49 01](https://user-images.githubusercontent.com/18541327/33585896-aa8c7b92-d934-11e7-8ecc-3c7b5ebddd51.png)
If you'd like, I can try running it in a minimalist environment to see if the issue persists.

**Comment by malte0811** [comment]
I just tested it, only the upper block interacts with comparators right now. This is a bug, I'll fix it later today.
