### ISSUE TITLE
[1.12.2] Lag after put the Post on block

### ISSUE THREAD

**Issue by hectorwilde** [BluSunrize/ImmersiveEngineering#2644]
### Description of the issue:
After put the any type of POST i will have a mega lag i mean 0 FPS.

### Versions & Modlist
IE: 0.12 - 75
FORGE:  14.23.1.2558

**Comment by malte0811** [comment]
![2017-12-03_20 08 16](https://user-images.githubusercontent.com/10406104/33528748-d98748c0-d865-11e7-9323-ec3fd613d3a4.png)
It's working just fine for me. Are you using just IE or other mods as well? What else is in the area where you are trying to place the post?

**Comment by hectorwilde** [comment]
Here is my screenshot, i have these mods and if i put i have 1 fps. I don't know why.
![img-2017-12-03-20-37-15](https://user-images.githubusercontent.com/5221712/33528978-c84b3806-d869-11e7-8b98-d952bfb88f2f.png)

**Comment by BluSunrize** [comment]
Please provide a debug crashlog as requested by the contribution guidelines.

**Comment by hectorwilde** [comment]
Here is a log from FML. 
[fml-client-latest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/1525110/fml-client-latest.log)

**Comment by hectorwilde** [comment]
Hmm, i gived more XMX to minecraft and the issue is solved, idk why.

**Comment by BluSunrize** [comment]
Because you were trying to run modded Minecraft with "only" 2GB of RAM, and it definitely needs more these days.
