### ISSUE TITLE
Crash when in the manual 1.12.2 mod version 0.12.75

### ISSUE THREAD

**Issue by cole4114** [BluSunrize/ImmersiveEngineering#2645]
When inside the manual of the game it will work for a couple seconds then crash.

I get no crash log but i get a java error.

#JRE version: Java(TM) SE Runtime Environment (8.0_25-b18) (build 1.8.0_25-b18)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.25-b02 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# V  [jvm.dll+0x4431fa]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows

That is what the text file says. There is other issues like this for earlier versions of the mod in 1.10, but being this is a 1.12.2 thing I created a new post.

**Comment by BluSunrize** [comment]
Update Java, you're using the stupidly outdated one shipped by the Minecraft launcher.

**Comment by mindforger** [comment]
also make sure your launcher is using it, check your launcher profile settings

**Comment by aldra2012** [comment]
i have the same thing happening to me, running the latest of everything, i only crash when looking at the multi-block configuration inside the book. it also goes super fast to the point i cannot tell how many i need of such block to make it.

**Comment by mindforger** [comment]
>i have the same thing happening to me, running the latest of everything

i doubt that! but you can prove me wrong. present all required informations because "latest of everything is pointless" ... tomorrow it is not the latest anymore, so please take thos precious 5 minutes of your life and gather the numbers

go ingame press F3 + C until you forcibly crash and upload that crashlog to pastebin and link it here

**Comment by BluSunrize** [comment]
Closed issue is closed.
Also, putting my money on outdated Java here as well.

Due to lack of an actual log though, you won't be getting much help.

**Comment by mindforger** [comment]
yeah sure it is closed but why not still helping ... well at least sorry for filling your inbox with topic updates i guess :)

**Comment by BluSunrize** [comment]
wasn't targeting you, Mind =P

**Comment by aldra2012** [comment]
https://pastebin.com/Hn832SK4, just don't mind the long mod list

**Comment by malte0811** [comment]
Look at line 82. You may have up to date Java installed (~1.8_151), but MC is still using the Java version the launcher ships with. You need to explicitely set it to use the new version in the launcher. And threatening to remove IE from your own pack isn't going to do too much except make us less likely to help.

**Comment by mindforger** [comment]
>also make sure your launcher is using it, check your launcher profile settings

and now i feel ignored by him ... sad

i mean it was literally right above his own post ....

**Comment by aldra2012** [comment]
my apologize, i just fixed it
