### ISSUE TITLE
[Request, all versions] Add CraftTweaker Documentation

### ISSUE THREAD

**Issue by MainFreak** [BluSunrize/ImmersiveEngineering#2647]
Hello. I just wanted to ask if it could be possible to ask the CraftTweaker Team/Kindlich to add the Immersive Engineering support to the [new documentation page](https://crafttweaker.readthedocs.io/en/latest/).

I asked them earlier if it was possible to do that but they said that they will not add the documentation without a [PR](https://github.com/jaredlll08/CraftTweaker-Documentation/pulls) or at least a permission from @BluSunrize. 

I am sure a lot of modpack creators would support this.

**Comment by bookerthegeek** [comment]
@BluSunrize if you like I can update that for you after running it by you to make sure everything is correct. Just let me know.

**Comment by BluSunrize** [comment]
By all means go ahead, thanks ^_^

**Comment by bookerthegeek** [comment]
Sweet. I'll poke you here when it is up.

**Comment by MainFreak** [comment]
Uh... May I ask you if this is still worked on?

**Comment by kindlich** [comment]
Created a Stub, feel free to fill it with any actual information:
<http://crafttwaeker-docu.readthedocs.io/en/latest/#Mods/ImmersiveEngineering/ImmersiveEngineering/>

Documents can be found [here](https://github.com/kindlich/CraftTweaker-Documentation/tree/master/docs/Mods/ImmersiveEngineering), simply fork and PR or do anything similar...

**Comment by BluSunrize** [comment]
I'll close this, since it's up to the wiki team / user contribution now.
