### ISSUE TITLE
Immersive Enginnering has glitches with Optifine

### ISSUE THREAD

**Issue by LuxerTheGamer** [BluSunrize/ImmersiveEngineering#2648]
Hi! I found two bugs, when I was playing on immersive enginnering with optifine.

Version: 1.12.2
Mods:
ImmersiveEngineering-0.12-75 and older, on 1.12.2
Forge 14.23.0.2559 and older, on 1.12.2
Optifine C5/C6/C7 1.12.2

The first problem is a incorrect texture on crusher (multiblock construct), probably texture is enlarged.
Crusher with optifine:
https://imgur.com/a/BtiYx
Crusher without optifine:
https://imgur.com/a/2VAG8

The second problem is with revolver. Probably, the element of the weapon with optifine doesn't have a texture, or texture is transparent.
Revolver with optifine:
https://imgur.com/a/7e8Uf
Revolver without optifine:
https://imgur.com/a/tvw7n

Thanks for help, and sorry for my english.

**Comment by BluSunrize** [comment]
Yup!
And that's why Optifine is not supported =P

**Comment by bookerthegeek** [comment]
@LuxerTheGamer Report to Optifine
