### ISSUE TITLE
Redstone Wire Connectors Won't Change Channel

### ISSUE THREAD

**Issue by AgentA1cr** [BluSunrize/ImmersiveEngineering#2649]
### Description of the issue:
In one particular world, no redstone wire connectors will change their color channel when sneak-right-clicked with an engineer's hammer. This issue does not occur in the test world I created to check if the issue occurred across worlds, nor did it occur in the problem world until recently. I've tried breaking and replacing connectors, placing new connectors elsewhere, relaunched Minecraft multiple times, and tried testing far enough from my base to completely unload it, in case it was related to something in those chunks. I've attempted to test to see if the issue also occurs for fake players, but have been unable to do so as none of the current options I've been able to find will simulate sneak-clicking. The connectors respond normally to standard right-clicking, switching between input and output as expected.

### Versions & Modlist
IE: 0.12-75 
Forge: 1.12.2-Forge14.23.1.2555

Forced debug crashlog: https://gist.github.com/AgentA1cr/b059ad42735465ea94277dc6052c53fc

**Comment by BluSunrize** [comment]
I can only suspect this to be a crossmod or edgecase issue. Without a reproducable testcase, there isn't much to be done here, I'm afraid

**Comment by Zieg777** [comment]
At the risk of necromancy here, I found and think I solved the issue. 
I had an Embers "Tinker's Lens" in my offhand, and could not change the colors. I could only change the in/out mode. Removing it from the offhand seems to have resolved it, I can now change colors. 

I dont have any other thing that would normally be in my offhand to check against to know if it's just the offhand slot, or something particular to the Tinker's Lens.

Hope that helps

**Comment by dragondave** [comment]
Shields do the same for me - crouch rightclick raises the shield instead of changing the colour. Unequipping the shield fixes the problem.

**Comment by AgentA1cr** [comment]
You're probably on to something there. I don't have access to that world anymore to confirm it, (lost it in a hard drive crash), but if I recall correctly, I used Psi a fair bit, and generally carried a CAD in my offhand. That may well have been the source of my issue.

**Comment by dragondave** [comment]
It appears to be a common problem across mod packs: just had similar issues
with wrenches in Gregtech on FTB Interactions.
