### ISSUE TITLE
About the Garden Cloche

### ISSUE THREAD

**Issue by JimMoen** [BluSunrize/ImmersiveEngineering#2650]
I'm very sorry to send you this issue。
I added the Immersive Engineering in my private modpack (Minecraft version 1.11.2) and I can't plant tier1-tier5 inferium seeds in the Garden Cloche.
I saw a resolvent In [Issue #2156](https://github.com/BluSunrize/ImmersiveEngineering/pull/2156/files) to support the seeds.
I don't have any experience in making Mod and I don't know how to compile the src to jar file.
Could you help me to compile the modified mod or send me a compiled mod?
Thanks a lot.

**Comment by EvilCooky** [comment]
Mystical crops is not supported by the garden cloche, as far as I know.
But there should be third party mods out there that add compatibility.

**Comment by BluSunrize** [comment]
This isn't the place to ask about modding tutorials, I'm afraid.

I'd recommend checking out the work of McJty in that regard, he's got some solid advice.
