### ISSUE TITLE
Wire Length Configuration Not Changing Anything (that I notice)

### ISSUE THREAD

**Issue by deathneko11** [BluSunrize/ImmersiveEngineering#2651]
Edit: Using most recent version of both this mod and forge!  Just installed latest updates today!

I confess it, I'm annoyed at how short the distance is to string together components to get energy around.  I have built towers all over my village and to my fortress from multiple windmills on a low voltage setup for use of the powered lanterns, and it's working well.  The issue is that I want to drastically reduce the number of towers in my village by increasing the distance of the cables, but when I increase the wire length settings I see no change.  I have tried restarting the game after changing this setting as a troubleshooting step, and nope.  Nada.  Am I misunderstanding what this setting does?

Edit: I have this list of mods:
uncrafting table
horse carts
better fps
bibliocraft
biomes o plenty
carry on
customized dungeon loot
extra utilities
heartdrops
JEI
MCA (Minecraft Comes Alive)
moarores
natural nether portals
rustic
soletarie's Mo' Pickaxes
Spartan Shields
Switch Bow Mod
Wearable Backpacks
Xaeros Minimap
Xaeros World Map
Xplosives
Xray

Edit: sorry, forgot to put this in.  I'm playing solo, no server.  Just my own world.

Edit (again): I have tried changing the values three times upon launching the game now, and each time I exit the game the values reset back to default even though I click done when I edit the values. However, the values I set for the loss over distance (set them to 0 for convenience) has stayed.

**Comment by AgentA1cr** [comment]
Friendly tip: Don't forget Forge version and Immersive Engineering Version.

**Comment by malte0811** [comment]
It's working for me. You are changing "wireLength" in "general", right?  You do have to restart the game to apply the config changes, but you said you did that. There isn't be any code in IE to override changed values (as long as the config is still valid). Could you upload the config before and after your changes to https://gist.github.com? What launcher are you using (some launchers might override changed configs)?

**Comment by mindforger** [comment]
can you also make a forced crashlog by going ingame (not menu) and holding F3 + C pressed until it crashes? i  am just guessing here, but this sounds like a path issue due to the used charset or OS maybe

i had issues with configs being overwritten all the time in the past with nitrado servers because the mod wasn't seeing the config but was able to extract the file into the config, thus overwriting it always
