### ISSUE TITLE
Suggestion/Question?

### ISSUE THREAD

**Issue by LordKhaox** [BluSunrize/ImmersiveEngineering#2653]
Is there anyway, a command maybe to add a mineral deposit in the chunk the player is standing in ?
 Would be very need for custom map makers :) 

Greetings LordKhaox

**Comment by malte0811** [comment]
`/ie mineral set <name>` to set the vein.
`/ie mineral get` to print the vein in the current chunk to your chat.
`/ie mineral list` to list all available vein types.
