### ISSUE TITLE
1.12 assembler not working with fluids

### ISSUE THREAD

**Issue by redgoblin88** [BluSunrize/ImmersiveEngineering#2655]
### Description of the issue:
upon searching for a method to create dirt, i found that if i craft coarse dirt, i can then use that with a bucket of water to get mud, however upon putting in the recipe for the mud (1 coarse dirt with 1 bucket of water yields 1 mud) the assembler wont use its internal tank full of water.

upon thinking that each tank is for each grid, i put the first recipe to mud but the same issue occurs where it does not craft ( i have 1 coarse dirt left in there which it should be using... and ignore that pams fresh water...)

below are the screenshots of how im putting the water in (thermal fluiducts) and what the assembler looks like inside with both setups that ive tried.

![2017-12-07_20 56 16](https://user-images.githubusercontent.com/13396472/33738996-504f22a4-db93-11e7-82fe-da3b43806a83.png)
![2017-12-07_21 09 40](https://user-images.githubusercontent.com/13396472/33738997-50673f42-db93-11e7-94b7-b4421cc20aeb.png)
![2017-12-07_21 12 15](https://user-images.githubusercontent.com/13396472/33738999-507f5d0c-db93-11e7-889f-25810b86810c.png)

### Versions & Modlist

minecraft: 1.12.2
forge: 14.23.1.2555
Immersive engineering plus core:0.12-75

other mods? 
https://pastebin.com/Cz3160GE
or if you wish hp onto the direwolf20 pack which is what im currently playing on that has the issue

**Comment by Paul17041993** [comment]
I've come across this with build 82 as well, but with IE's own creosote...
<img width="240" alt="screenshot_182" src="https://user-images.githubusercontent.com/3912867/40286692-015f6d72-5cec-11e8-8c98-48073bde0705.png">

**Comment by mindforger** [comment]
well, as far as i see searching the closed issues with "assembler fluid" brought up 2 results, one seems to fix milk being an issue and the other sounds just like what you described

https://github.com/BluSunrize/ImmersiveEngineering/issues/2260

try first to replicate the issue with the latest released version (88 currently)

**Comment by Morketh** [comment]
Issue remains in Version 0.12-88 Trying to create Forestry fertilizer with 3 compost, 3 blocks of charcoal, 3 buckets quicksand fluid. Recipe works at a crafting table. no product output on assembler.
![image](https://user-images.githubusercontent.com/6291631/56072264-b95f9680-5d5a-11e9-8a82-ffe0d58f2be7.png)
