### ISSUE TITLE
Arc Furnace Animation

### ISSUE THREAD

**Issue by LordKhaox** [BluSunrize/ImmersiveEngineering#2656]
Isn't the arc furnace suppose to play a liquid metal pouring out animation when its finished smelting ores?I can remember it in the 1.7.10 version.. is it gone? It looked so cool :(

**Comment by malte0811** [comment]
Seems like that has been gone since 1.8.9. I agree that it would be nice to have it back, I'm currently checking how much work it would be to bring it back (and why it was removed in the first place).
