### ISSUE TITLE
[1.12.2] Excavator CraftTweaker Integration not removing "Default" minerals

### ISSUE THREAD

**Issue by justinrusso** [BluSunrize/ImmersiveEngineering#2657]
### Description of the issue:
I am trying to remove the default minerals included by the mod, but it appears to not do anything.
```
mods.immersiveengineering.Excavator.removeMineral("Bauxite");
mods.immersiveengineering.Excavator.removeMineral("Cassiterite");
mods.immersiveengineering.Excavator.removeMineral("Coal");
mods.immersiveengineering.Excavator.removeMineral("Copper");
mods.immersiveengineering.Excavator.removeMineral("Galena");
mods.immersiveengineering.Excavator.removeMineral("Gold");
mods.immersiveengineering.Excavator.removeMineral("Iron");
mods.immersiveengineering.Excavator.removeMineral("Lapis");
mods.immersiveengineering.Excavator.removeMineral("Lead");
mods.immersiveengineering.Excavator.removeMineral("Magnetite");
mods.immersiveengineering.Excavator.removeMineral("Nickel");
mods.immersiveengineering.Excavator.removeMineral("Platinum");
mods.immersiveengineering.Excavator.removeMineral("Pyrite");
mods.immersiveengineering.Excavator.removeMineral("Quarzite");
mods.immersiveengineering.Excavator.removeMineral("Silver");
mods.immersiveengineering.Excavator.removeMineral("Uranium");
```
CraftTweaker does log to the console that it removed them, but in game they are not removed when doing `/ie mineral list`. I am able to create new minerals, just not remove. I have not tested if it can remove a mineral I've created, to see if maybe its related to just the default minerals that cannot be removed.

![image](https://user-images.githubusercontent.com/25138621/33780613-6221effc-dc1f-11e7-9675-4de3ffbc60c5.png)

### Versions & Modlist
IE: 0.12-75
Forge: 14.23.1.2555
CraftTweaker: 1.12.4.0.11

Thank you for your time!

**Comment by HEHABUZTb** [comment]
y forgot import
import mods.immersiveengineering.Excavator;
