### ISSUE TITLE
Arc furnace will only render any 2 of the 3 electrodes

### ISSUE THREAD

**Issue by TheQuantumGeneral** [BluSunrize/ImmersiveEngineering#266]
Doesn't matter what two electrodes come first, but it will not render the last electrode you put in, regardless of slot. 

Using the only build that has the Arc furnace. 

![2015-08-05_00 49 02](https://cloud.githubusercontent.com/assets/7843312/9063683/0f623b98-3b0c-11e5-80e2-8ad9584b0254.png)
![2015-08-05_00 49 04](https://cloud.githubusercontent.com/assets/7843312/9063685/0f89b538-3b0c-11e5-84fa-9a879ae9e8cd.png)

**Comment by BluSunrize** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/262

Check the past issues.
