### ISSUE TITLE
[Suggestion]Grappling Bolt

### ISSUE THREAD

**Issue by HappyPineapple** [BluSunrize/ImmersiveEngineering#2660]
Hi me again filling your to do list and ideas could you have a wrist rod shooter that has 2 tier's. 1 tier being hemp fibre and tier 2 being steel cabling. So it would be crafted something like this, two hemp fibers, iron or steel rod steel mechanical component and a HV wire connector. Hemp fibre would last once and steel 1000 times. Would require capacitor backpack to function as it does not have an internal power storage.

**Comment by MalkContent** [comment]
In 1.10 there was a grappling hook kind of thing that got removed (3d maneuver gear from attack on titan) because it didn't fit with the rest of the mod, iirc.
So don't count on it :/

**Comment by BluSunrize** [comment]
Maneuver gear was removed because it was a lagfest and incredibly janky to control.

**Comment by HappyPineapple** [comment]
Mow well
