### ISSUE TITLE
[1.11.2] Rendering error in some chunks

### ISSUE THREAD

**Issue by Serikuser** [BluSunrize/ImmersiveEngineering#2661]
Hi there, i have some problems with render, i guess, on MC 1.11.2 version.  Its happens after unloading and only in some chunks. Does any ways to fix it? 
![ss 2017-12-10 at 10 07 47](https://user-images.githubusercontent.com/34411869/33802884-178cef3a-dd93-11e7-9e28-3191bd199f56.jpg)
![ss 2017-12-10 at 10 07 59](https://user-images.githubusercontent.com/34411869/33802885-17aa4c9c-dd93-11e7-8fe5-6ae235816278.jpg)

**Comment by AEnterprise** [comment]
i spy a pam's harvestcraft presser there, can you try removing all harvestcraft blocks from the area?

**Comment by Serikuser** [comment]
@AEnterprise WOW! i guess it's helped, will monitor it for a while. Thx a lot
