### ISSUE TITLE
Crash moments after opening in game manual.

### ISSUE THREAD

**Issue by mikeskey** [BluSunrize/ImmersiveEngineering#2662]
Every time I try to use the manual I get just a few pages in and actually start reading about something and a few moments later it crashes. I am using the latest version of IE as of the time of this post as well as the most recent version of forge. I have created my own modpack that I am using this mod in and it is a rather small pack with around 30 mods in total. These are all mods I have used in the past and have had no issues with any conflicts so I am going to assume at this point there are no conflicts with any other mods and it is an error in this mod.

**Comment by malte0811** [comment]
I'm going to close this for 2 reasons:
1. You either didn't read the [contributing guidelines](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/CONTRIBUTING.md) or you ignored them. They are linked at the top when you create an issue.
2. I'm 99% certain this is a known crash. Update Java to the latest Java 8 (not 9) release and SET THE LAUNCHER TO USE IT. The new MC launcher (don't remember whether the old one had that) comes with it's own version of Java that is very outdated and contains a lot of bugs (like what is probably causing the crash).

If it still crashes with the new Java version (update ~152) post a crashlog here. If there isn't a crashlog there might be a file called something like hs_err1234 in your MC folder, which is the equivalent of a crashlog for that sort of crash.

**Comment by AEnterprise** [comment]
@malte0811 the old launcher did not ship java and used whatever you had installed

**Comment by mindforger** [comment]
well you'd have to differ, there is an oldold which did not, then there was the newer one with profiles which did ship it at some point and the newest compact designed version which still ships an ancient version

**Comment by mikeskey** [comment]
Well Malte you just assumed I didn't know what I was doing. I have had Java update 151 installed since 11/30/17 which is before I had this issue with IE. Update 151 is the latest update I can find for java so there is apparently no 152 as you claim and I am using java 8 not 9.

I was unaware that minecraft launcher had come with its own version and I was also unaware that it could be set to use a specific version but that information did NOT need to be conveyed in a rude reply to my original post. Yes I read the guidelines but at the same time a developer of a mod knows exactly what is said when someone clearly states "I am using the latest version of IE as of the time of this post as well as the most recent version of forge."

Learn to get off your high horse and be civil, your rudeness is not warranted here nor will it be tollerated!

**Comment by BluSunrize** [comment]
@mikeskey The reason that you received the reply that you did is due to your blatant disregard for the contribution guidelines and the issue template. You evendentally did not search through previously reported isues at all and did not provide the requested crashlog.
If you don't make the effort to report an issue properly, I can see why a developer won't make the effort to give you a nicer phrased reply.
