### ISSUE TITLE
[1.12.2] [0.12-75] Slippery potion effect crashes game and duplicates held item.

### ISSUE THREAD

**Issue by deathaplenty** [BluSunrize/ImmersiveEngineering#2664]
### Description of the issue:
The slippery potion effect crashes the game and dupes your held item. I tested this by giving myself the slippery potion effect in creative, but I originally came across this bug while using Immersive Petroleum's lubricant.

### Crashlog:
https://pastebin.com/sULAU8CX

### Versions & Modlist
IE version: 0.12-75
Forge version: 14.23.0.2552

### How to reproduce
1. Hold a stack of items, to visualize duping.
2. Obtain the slippery potion effect via /effect or some other means.
3. Wait for a crash.

**Comment by BrisingrAerowing** [comment]
It appears Blu is passing null for an ItemStack there, where it should be ItemStack.EMPTY.

[Here is the problem line](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/util/IEPotions.java#L110)
