### ISSUE TITLE
[suggestion] Custom blueprints

### ISSUE THREAD

**Issue by Frontrider** [BluSunrize/ImmersiveEngineering#2665]
I see some possibilities in that system. In packs it could be used to gate technologies. (something like Age Of Engineering)
The UI could be based on the structure of the blueprints used to craft (presses, components).

Its just something I would throw into the box, if you don't feel like its something you should/could add, than dismiss it.

**Comment by BluSunrize** [comment]
There is full Craftweaker support to add custom bluepritns + recipes.
