### ISSUE TITLE
[CraftTweaker] Adding ores to an existing excavator vein causes a null-pointer exception

### ISSUE THREAD

**Issue by belathus** [BluSunrize/ImmersiveEngineering#2667]
### Description of the issue:
Adding ores to an existing vein causes a null-pointer exception. Not sure if something is wrong with my script, but I don't think so? I'm trying to use [this function](https://github.com/BluSunrize/ImmersiveEngineering/blob/495e2c5365235881285909cff65e087f945fdc1d/src/main/java/blusunrize/immersiveengineering/common/util/compat/crafttweaker/Excavator.java#L154).

### Crashlog:
N/A, but here is the CraftTweaker log: https://gist.github.com/belathus/2abec0de4fbbc9c213e8aee36ec2692d

And the line of the script that creates the exception: https://github.com/belathus/Wanderlust-Renewed/blob/master/scripts/immersiveengineering.zs#L57

### Versions & Modlist
IE: 0.12-75
Forge: 1.12.2 - 14.23.1.2565
CraftTweaker: 1.12 - 4.0.10

**Comment by BluSunrize** [comment]
Yeah, the changes in loading order have made this rather messy.

I'll need to poke Jared some time about having certain CT thigns load later or smth.
Sorry, can't do much about this one atm.

**Comment by BluSunrize** [comment]
I take it back, I found a somewhat satisfactory solution.

**Comment by BluSunrize** [comment]
^ fixed by this
