### ISSUE TITLE
[Request] Add compatabilty for Botania/Quark dispenser planting.

### ISSUE THREAD

**Issue by The-Arcanian** [BluSunrize/ImmersiveEngineering#2668]
All that seems to be required is registering a dispenser behavior for hemp seeds using ether Botania or Quark's BehaviourSeeds class when they are present.

**Comment by mindforger** [comment]
please add some version informations like requested from the contribution guidelines

**Comment by The-Arcanian** [comment]
I'm sorry, the guidelines seemed to be for bug reports, not compatibility requests. As such I am not exactly sure how to comply with the guidelines here.
From what I can tell Botania and Quark have had dispenser planting since they came out. But as of the latest version of Immersive Engineering, 0.12-75, hemp seeds are not plantable by dispensers when ether Botania or Quark are installed.

**Comment by mindforger** [comment]
errr ... okay this was not supposed to land here must have crossposted by accident ... sorry

**Comment by The-Arcanian** [comment]
Haha, no worries.

**Comment by BluSunrize** [comment]
Hmm, the planting thing is a quark feature I'm pretty sure, vanilla dispenser behavior just ejects seeds on the ground.
I don't have an easy way of checking Vazkii's configs for the activity of that feature, ideally they'd implement it on their side.

**Comment by The-Arcanian** [comment]
From what I can make out of Vazkii's code it handles the doing when the config is enabled. You just have to register it so it knows that it can.

(Sorry that I did not respond earlier, I was moving.)
