### ISSUE TITLE
Can't make steel nuggets and blocks

### ISSUE THREAD

**Issue by Pihrra** [BluSunrize/ImmersiveEngineering#267]
Hi,
There seem to be a problem with steel. I can't craft nuggets from ingots or block from ingots and nuggets into blocks or blocks into ingots.
I previously had a similar issue that was caused by another mod but it involved all metals. This time it's just steel (and I didn't re-add the mod).
I created 2 brand new worlds one with IE 0.4.4 + all my other mods and one with IE 0.5.0 + all the same other mods. In 0.4.4 I can make steel blocks (not the nuggets obviously since they didn't exist yet) in 0.5.0 I can't.

Here is a list of all the 28 mod files I have (+ IE of course) : http://pastebin.com/RczvMbu9

**Comment by cobra** [comment]
Found the bug (and fixed it locally to confirm). The recipe registration loop ends too early and misses steel: https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/IERecipes.java#L164

**Comment by BluSunrize** [comment]
Yep, I found that one too =P
to be fixed

**Comment by cobra** [comment]
btw, what about replacing some of these magic numbers with properly named constants to avoid future confusion?
Something like Meta_MetalCopper=0…Meta_MetalSteel=7 and Meta_MetalCount=8?

**Comment by BluSunrize** [comment]
constants are overrated
