### ISSUE TITLE
[1.12.2] Workbench recipes ignore NBT data

### ISSUE THREAD

**Issue by IcedReaper** [BluSunrize/ImmersiveEngineering#2671]
### Description of the issue:
I have created some custom workbench recipes using the CraftTweaker API and it seems that the NBT data is being ignored.
Custom recipes: https://pastebin.com/7pwJJ5Ck
The problem occurs everytime and I only tried it in a singleplayer environment.
Screenshot: https://imgur.com/7i4F4c8

### Crashlog:
No Crash

### Versions & Modlist
Immersive Engineering: 0.12-75
Forge: forge-14.23.1.2555

A list of all the installed mods: https://pastebin.com/qSTewHeJ

**Comment by mallrat208** [comment]
It's worth pointing out that in CraftTweaker withTag() is used for recipe outputs not for recipe ingredients. In that case you need to use onlyWithTag()

**Comment by IcedReaper** [comment]
@mallrat208 no, it's not. It's used for the ingredient, next to the IE hammer.
The order of the arguments was switched for most CraftTweaker methods, so I think it was done for IE too.
`public static void addRecipe(String category, IItemStack output, IIngredient[] inputs)`

I tried onlyWithTag() tho, but got an error that one parameter can't be null.

**Comment by justinrusso** [comment]
.withTag in inputs do not actual filter the item to that tag. They just "appear" as that item in the crafting recipe, but other nbt's of the same item still work.

**Comment by BluSunrize** [comment]
Yeah Blueprint recipes don't support NBT on ingredients. There was never a reason for them to do, so I didn't add that.

Probably won't make that change.

**Comment by IcedReaper** [comment]
Okay, thanks for the information.
