### ISSUE TITLE
[1.12.2] IE 0.12-75 Crashes while loading with Forge 14.23.1.2577

### ISSUE THREAD

**Issue by aetherknight** [BluSunrize/ImmersiveEngineering#2674]
### Description of the issue:

With Forge 1.12.2-14.23.1.2577 and Immersive Engineering 0.12-75, Minecraft crashes while loading mods (see the attached crashlog). If I roll back to Forge 1.12.2-14.23.1.2575 then Minecraft successfully reaches the title screen.

I'm filing the bug here because it looks like Forge build 2576 and later includes some changes  related to loading models (the crash report fails during model-related code): http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.1.2577/forge-1.12.2-14.23.1.2577-changelog.txt

I didn't have a chance to install and test against 2576 yet.

### Crashlog:

[crash-2017-12-17_15.38.38-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1566206/crash-2017-12-17_15.38.38-client.txt)

### Versions & Modlist

* Forge 1.12.2-14.23.1.2577
* Immersive Engineering 0.12-75

Reproducible without any other mods installed.

**Comment by bs2609** [comment]
#2672

**Comment by aetherknight** [comment]
Ah, already caught. Should've looked closer at the closed bugs list/recent commits. Thanks!
