### ISSUE TITLE
[1.10.2] [0.10-61] Random crash when picking up core samples

### ISSUE THREAD

**Issue by Carnaxus** [BluSunrize/ImmersiveEngineering#2675]
Hey there.  I'm playing on a private server which, among many other mods, has IE and Flaxbeard's Immersive Petroleum addon.  I've been taking core samples like mad trying to find a quartz vein (holy crap they're rare but that's another story), and the other day I looked at my map and realized that I'd made quite a mess.  Core samples all over the place, nothing orderly at all...so I decided to go back and straighten up a bit.  I started moving the samples to the bottom right corner of the chunk they related to.  Every fifth to fifteenth sample I broke to move, my game crashed; it's happened four times now, and I'm quite certain that if I keep going it'll keep happening.  I've also posted this to the [Immersive Petroleum](https://github.com/Flaxbeard/ImmersivePetroleum/issues/83) bug tracker.

Why give just one crashlog when I can be generous and give four?
[Yay, it bought me a teddy bear!](https://pastebin.com/dva0tnRL)
[And a cupcake!](https://pastebin.com/Sn5dRKGZ)
[Log 3](https://pastebin.com/Td7wqJ56)
[Log 4](https://pastebin.com/948TkvVh)

Forge 1.10.2-12.18.3.2511
IE 0.10-61
Immersive Petroleum 1.1.3

**Comment by BluSunrize** [comment]
Crash seems to stem from code called by IP.
I'll close this side, because it's either something Flax can fix, or it's not, in which case it doesn't matter because I don't plan on releasing any further 1.10 builds.
