### ISSUE TITLE
Instant Crash on startup

### ISSUE THREAD

**Issue by Dente222** [BluSunrize/ImmersiveEngineering#2679]
Soo I have bug that crashes my minecraft nearly instantly
here is Error Log: https://pastebin.com/8m07awqa
Its something about IE-Core 

Im using IE 0.12-75 but have same problem with 74 too 🌵

**Comment by IchigoGames** [comment]
i have the same crash i think its something that forged changed as it was crashing with no other mods changed only other thing i changed was forge 

Minecraft 1.12.2
Forge 2578
crash report https://pastebin.com/8m07awqa

**Comment by Firebarrage** [comment]
I'm getting this as well. 
Temporary fix: Revert to Forge 2555

**Comment by HorizonsMC** [comment]
Fixed in dev, stay on 2575 or below until the next update is released.
