### ISSUE TITLE
[1.12.2] Garden Cloche with Sugar Cane causes a  "Zero length vector" crash

### ISSUE THREAD

**Issue by locou** [BluSunrize/ImmersiveEngineering#2680]
**Immersive Engineering 0.12 - 75**
**1.12.2-forge1.12.2-14.23.1.2555**

The Game crashes as soon as I put Sugar Cane into the Garden Cloche. My Server is still running, but I'm unable to join it since the game crashes as soon as I connect to it. The first time I've encountered this crash on my server. I've also tested it in a singleplayer game. Same crash, same log.

Here's my crash-log: https://pastebin.com/vKZpTd1x

**Steps to reproduce:**
Place 1 Garden Cloche
Place 1 Sugar Cane into the top slot

**Comment by malte0811** [comment]
Interesting crash, seems like there is a quad in the sugar cane model that is a line or a dot. For now you can set `disableFancyTESR` to true in the config, that should stop the crash.

**Comment by locou** [comment]
I found the bug myself. It was my resource pack, which adds different random segments for reeds. It seems the Gardem Cloche can't deal with it and crashes. 
A quick fix is to remove the reeds.json (I think?) from the resource pack.

**Comment by KnightMiner** [comment]
It might be helpful if you link the file here since its a test case that causes the crash.

**Comment by locou** [comment]
I guess other resource packs are implementing a similiar file, but the one I use is [Pixel Perfection v3.6](http://www.minecraftforum.net/forums/mapping-and-modding-java-edition/resource-packs/1242533-pixel-perfection-now-with-polar-bears-1-11).
It is located in /Pixel Perfection V3.6/assets/minecraft/models/block/reeds.json

Deleting this file stops the crash.
