### ISSUE TITLE
[Suggestion] Split Logistics Off

### ISSUE THREAD

**Issue by Tetrajak** [BluSunrize/ImmersiveEngineering#2682]
Please consider splitting the logistical parts of IE (conveyors, wire & connectors, pump & pipes) off into their own mod. They're my favourite part of IE, but I'd really like to be able to use them in modpacks for which the IE machines would not fit, without having to load every part of the mod that has then been configured and tweaked away.

**Comment by BluSunrize** [comment]
That's a lot of effort and would requiring tearing a lot of IE's basic framework out of them mod.

Additionally, I've always been very irritated by mods splitting into modules, with Thermal Expansion being probably the worst possible example. I prefer to keep everything in one mod.
