### ISSUE TITLE
Garden Cloche Fertilizer

### ISSUE THREAD

**Issue by SimasISuppose** [BluSunrize/ImmersiveEngineering#2683]
Mod version: Immersive Engineering 0.10 - 61
Mc version: 1.10.2
Garden cloche wont accept any versions of Phyto-Gro from ThermalDynamics as fertilizer, the only thing it does accept as fertilizer is bonemeal. Is there any way to add support for this fertilizer?

**Comment by Neoxon4865** [comment]
I also have this same issue on project Ozone Lite

**Comment by BluSunrize** [comment]
That feature is not in .10 versions, but only in Minecraft 1.12.
