### ISSUE TITLE
[1.12.2] Faraday armor crashs on Tesla Coil high power

### ISSUE THREAD

**Issue by joselitosn** [BluSunrize/ImmersiveEngineering#2688]
If you get zapped enough by the Tesla Coil on High power, the armor should be destroyed but instead it crashes the game.

[Pastebin Crash Log](https://pastebin.com/0fDuWsKE)

It seems the bug is caused because the item slot is set to null on destruction.

https://github.com/BluSunrize/ImmersiveEngineering/blob/830c0ffa39b8ed7dc0c508559030819e8bceaddd/src/main/java/blusunrize/immersiveengineering/common/items/ItemFaradaySuit.java#L60

 Setting it to ItemStack.EMPTY fixed the problem for me.

```java
p.setItemStackToSlot(eqSlot, ItemStack.EMPTY);
```

Also as a suggestion, maybe the chain armor could have the same shield effect.

EDIT: Another suggestion, the Tesla Coil could target more enemies at the same time but do less damage as the more enemies it targets.

**Comment by mindforger** [comment]
>Another suggestion, the Tesla Coil could target more enemies at the same time but do less damage as the more enemies it targets

it could alternate between targets beeing at the same distance +/- a little bit (maybe a chance calculation to be hit when in range) but hitting multiple targets at the same time would be not logical, when a current path to a target is choosen there will be only one discharge, never multiple in parallel, only alternating paths are possible
