### ISSUE TITLE
cant join my server (1.12.2)

### ISSUE THREAD

**Issue by SDUBZ** [BluSunrize/ImmersiveEngineering#2689]
Forge:1.12.2-2575
IE: ImmersiveEngineering-0.12-75/core: ImmersiveEngineering-0.12-75-core
Chisel: Chisel-MC1.12-0.1.1.24

printout:
https://pastebin.com/cE8tq0hq

Thank you for reporting issues, without people reporting them, they wouldn't get fixed. You're helping contribute to this mod and that is much appreciated <3

**Comment by BluSunrize** [comment]
That error shouldn't actually prevent a join, however I have fixed the chisel compat for the next release, which is due later today or tomorrow.
