### ISSUE TITLE
Crash on startup - models issue?

### ISSUE THREAD

**Issue by estradus** [BluSunrize/ImmersiveEngineering#2691]
I've got a crash occuring when attempting to start minecraft with immersive engineering. It gets partway through stage 3, around baking models, and crashes.  I am running:
Minecraft 1.12.2 
Forge version 14.23.1.2581
IE version 0.12-75
I have no other mods installed beyond IE and IE core.
Here is the crashlog: https://pastebin.com/TgUm3eT0

**Comment by bookerthegeek** [comment]
Downgrade forge to 2575

**Comment by malte0811** [comment]
^That.
Duplicate of #2672 and a few others. Fixed for the next release, use forge 2575 for now.
