### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by SirWindfield** [BluSunrize/ImmersiveEngineering#2696]
I am currently writing a TOP support for the metal sheet tank. But every time I want to start the client, I get the following exception: https://pastebin.com/ALYY6kkb

I run `setupDecompWorkspace` beforehand. Looking into the maven repo, there doesn't seem to be any 4.0.11 version of ZenScript, the newest one being `4.0.10.310`. How do you guys compile the mod?

**Comment by malte0811** [comment]
I ran into that yesterday, it worked when I set gradle to use a specific (slightly older) version of CT. I generally use IntelliJ for launching though (the error looks like you used gradlew runClient), unless I'm working with models and don't need to see the code.

**Comment by SirWindfield** [comment]
I used the intellij task that got generated using `getIntellijRuns`. How do you start it?
How o I set the version to the older CT without changing the build.gradle file? There seems to be a reason why you guys updated the verison.

**Comment by malte0811** [comment]
1. Just change the file locally and don't commit it.
2. We have it set to use the latest version automatically, we didn't select the version manually.
