### ISSUE TITLE
HV Wire Connector

### ISSUE THREAD

**Issue by TheSnowyChickens** [BluSunrize/ImmersiveEngineering#2699]
### Description of the issue:
HV Wire connector change position after relog (or unload -> load the world)
Its not only a visual bug, the connector don't give any energy to the redstone furnace.
The position is y=+2 and x=+3 (y=65) blocks away from the chunk border.

### Crashlog:
![2017-12-28_02 50 37](https://user-images.githubusercontent.com/29357962/34397892-28560fd2-eb7a-11e7-9873-01df58ccd94b.png)

### Versions & Modlist
MC 1.12.2
ImmersiveEngineering-0.12-75
Forge 2575

**Comment by oitsjustjose** [comment]
I've been having a similar issue in several packs with several tiers:

FTB Revelations, using LV wire connectors:

- Wires work fine when bridged / updated / originally placed
- Wires stop working properly when re-loading Singleplayer world
- Wires and connectors all visually render correctly

Custom modpack ([modlist](https://gist.github.com/oitsjustjose/bc0a0bed250b3f7d452de6f5bf582fa1)) using MV (and now switched to LV) wire connectors

- Wires work fine when bridged / updated / originally placed
- Wires stop working properly when server is restarted
- Wires and connectors all visually render correctly


One thing in common for both cases (and the one originally posted) is that they are terminating in non-I.E. Machines. My connections terminate into Fluxducts from Thermal Dynamics, and it seems as though the original post is terminating in either a Thermal Expansion or Extra Utilities 2 machine.

Another is that all of my connections cross (several) chunks.

I'm going to try debugging this by first having them terminate into I.E. Capacitors, in hopes that that may fix something.

**Comment by malte0811** [comment]
Are there any errors in the log when this happens?

**Comment by oitsjustjose** [comment]
None on server-side. Sifting through my singleplayer FTB Revelation logs now looking for the same.

**Comment by oitsjustjose** [comment]
Nope, none in FTB Revelation client logs either.

**Comment by TheSnowyChickens** [comment]
Edit : last time, I joined in the world and all cables (HV Wires) was gone. The connection was still there ,but without an energy transfer.

**Comment by TheSnowyChickens** [comment]
Edit : I cant connect ANY kind of energy conduit (your LV/MV/HV connectors, Ender IO Energy conduits and Thermal dynamics resonant flux ducts) to this machine. :/
