### ISSUE TITLE
Lightning on Stairs

### ISSUE THREAD

**Issue by TheJulianJES** [BluSunrize/ImmersiveEngineering#27]
The lightning of stairs with smooth lightning 0% is bugged (http://gyazo.com/49ddce11662b41b54f71533aa2bd02d3). On Vanilla stairs this dosen't happen.
If you need more information, ask me :)
(They also make a stone breaking sound)

**Comment by BluSunrize** [comment]
My stairs use vanilla mechanic. Don't think this is my fault.
