### ISSUE TITLE
Can't craft Conveyor Belt "Ignores Redstone Control"

### ISSUE THREAD

**Issue by MatthiasMann** [BluSunrize/ImmersiveEngineering#2705]
I tried to craft a conveyor belt which ignores redstone control - according to JEI this should be doable by placing one in a crafting grid. I tried all 4 slots in the 2x2 grid and all 9 slots in the 3x3 grid - the resulting item always stacked with the default conveyor belts - eg no NBT tags or meta data change.

Modlist including versions:
[modlist.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1593038/modlist.txt)

**Comment by BluSunrize** [comment]
You probably have a mod that screws up NBT data on crafting.
Your best chance is binary search, chucking out half the mods to see if it fixes it, and then proceeding to take half of the side that caused it.
So on and so forth until you find which mod does it.

**Comment by SirWindfield** [comment]
@MatthiasMann I am having the same issues. 
[modlist.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1594868/modlist.txt)
This are the mods that I have installed. If you want to try it out, just test for these.

**Comment by MauveCloud** [comment]
I can reproduce this with _just_ IE 0.12-77 and Forge build 2611.  Workaround: install this mod: https://minecraft.curseforge.com/projects/stimmedcow-nomorerecipeconflict (then I can choose which of the two recipes to use)

However, I notice I apparently can't craft a covered redstone-ignoring conveyor belt, which complicates my plans a bit.
