### ISSUE TITLE
Arc furnace munches items

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#271]
Issue: upon breaking the Arc furnace multi-block structure, any and all items within it are destroyed.
Info: this destroys the graphite electrodes and any other item stored in the machine, regardless of how the MB was broken.

==============
Steps to reproduce:

[1] Make arc furnace MB structure and form it
[2] place any item within the Arc furnace GUI, including ore and electrodes
[3] break MB structure by any means

======================
Running FTB Infinity (1.9.0) with no other mods added/removed
IE version 0.5.0 built against 3bc2e46b5515b958c8ed53134faf715ee545431f

**Comment by BluSunrize** [comment]
Uuh, yeah, that's part of IE. You don't break machines while they are active. Your loss, buddy. xD
