### ISSUE TITLE
[Feature request] improvements for the new covered ladders

### ISSUE THREAD

**Issue by MatthiasMann** [BluSunrize/ImmersiveEngineering#2710]
I tested the new ladders (the aluminum version). They work great but there are some minor details:
The metal ladder can't be placed at the side of a silo or tank - but the covered one can. This means you can't use them to climb up to a silo as you can't enter the ladder.

So it would be nice to be able to place metal ladders at the side of a tank/silo - or have the option to open the front of a covered ladder using the hammer.

**Comment by Euphemios** [comment]
You also can't place metal ladders on vertical conveyor belts (covered version) which is a pain as if I wanted to put scaffolding there I wouldn't need the ladder

**Comment by thakyZ** [comment]
Yea I agree MatthiasMann, opening the *techinally* rear facing side of the covered ladders, so you could make an entryway to climb up would be a cool thing. I could've sworn this was a feature at one point, but I guess I am wrong about that.
