### ISSUE TITLE
Immersive Engineering Core ?

### ISSUE THREAD

**Issue by LokyLive** [BluSunrize/ImmersiveEngineering#2711]
Hello and happy new year !

I'm working on a new modpack, at the first launch "ImmersiveEngineering-0.12-76" generate an "ImmersiveEngineering-0.12-76-core" so i got 2 jar for Immersive Engineering. There is no crash or major problem with that but each time i publish a new version of my modpack if i forgot to delete the core file Curse refuse my update xD

Don't worry this not annoying it was just to report this ,p

**Comment by BluSunrize** [comment]
That is intentional. Forge's convention on coremods requires them to be packaged in a separate binary which is shipped with the main mod.
IE is just the onyl mod actually respecting that.

Read more here:
 http://www.minecraftforge.net/forum/topic/58706-regarding-minecraft-112-and-policy-changes/
