### ISSUE TITLE
[1.12.2] [Forge 14.23.1.2582] [IE 0.76] Railgun not firing anything

### ISSUE THREAD

**Issue by TechnoMysterio** [BluSunrize/ImmersiveEngineering#2714]
When firing the railgun, the sound plays, a steel/iron rod is taken from the inventory, but no projectile is actually fired. No damage is done to any mobs and the rod doesn't appear in the world. I've only tested this on single-player.

In IE 0.75 the railgun fires rods correctly. However, with 0.76, the railgun doesn't fire anything at all, with or without upgrades.

Forge and IE version are in the title, and the only other mod I tested this with was JEI 4.8.5.139.

**Comment by Thaumatarge** [comment]
Can confirm.
Railgun doesn't fire any rods, it only eats them.

**Comment by malte0811** [comment]
It's working for me on something based on 830c0ffa39b8ed7dc0c508559030819e8bceaddd (but no changes relevant to this), so either there are more conditions or it is caused by a commit later than that.

**Comment by orcdash** [comment]
Confirmed on 0.76 w/ forge 2582, nothing else added not even JEI. Additionally, chemthrower uses fuel and makes sound but does nothing on same build.

**Comment by Landstryder** [comment]
I can also confirm that the rail gun and the chem thrower are using resources but not firing any projectiles in 0.76 build
