### ISSUE TITLE
[1.12.2] [Forge 14.23.1.2582] [IE 0.75] Excavator Builds in the wrong direction

### ISSUE THREAD

**Issue by Aerosikth** [BluSunrize/ImmersiveEngineering#2715]
When completing construction of the Excavator it builds in with the wheel facing the wrong direction.

This happens no matter which direction I build the device.

![excavatorproblems](https://user-images.githubusercontent.com/35008948/34470415-1b7ed882-ef28-11e7-9be0-f4dcfc67cdca.png)

**Comment by malte0811** [comment]
Update to IE build 76.
