### ISSUE TITLE
[1.12.2] Crash while viewing IE manual

### ISSUE THREAD

**Issue by SciFiz** [BluSunrize/ImmersiveEngineering#2717]
My game is crashing when looking at the IE manual. I've caused it in two different worlds, at different locations in the manual, but all were in proximity to text that can be clicked on. It doesn't happen right away, it can take a minute - no sure why.

ImmersiveEngineering-0.12-75 & 0.12-76 (75 core was replaced too)
Forge 14.23.1.2566
Direwolf20 1.12 v1.4 (changed: environmentaltech-1.12.2-2.0.6b, OreExcavation-1.4.109,  NaturesCompass-1.12.2-1.5.0, ImmersiveEngineering-0.12-76)

0.12-75 1: https://pastebin.com/z04kaWpd
0.12-75 2: https://pastebin.com/xhHzqbqG
0.12-76: https://pastebin.com/ukkB2r4M

**Comment by BluSunrize** [comment]
You're using a java version that's about 2 years old. Go update.

**Comment by malte0811** [comment]
You also need to set the launcher to use the new Java version, see #2662.

**Comment by SciFiz** [comment]
The MC launcher is upto date. The Java version I installed is current as of 22nd October.
After several hours clearing out all installs of minecraft, twitch and curse it's come back as the launcher java setting - some idiot at Mojang (or Twitch) has it default to a bundled java version instead of checking for a registry entry for current java.

**Comment by BluSunrize** [comment]
Which is, in fact, a very common issue that has been posted on this tracker many a times.

**Comment by mindforger** [comment]
>checking for a registry entry for current java

i would like to see a working example to detect the installed default JRE on a system ... that is a major flaw of the JRE for ages :) ... 

you can check for PATH entrys and other peripheral entrys that could possibly exist (but can be missing for several reasons) but it would be tedious ... i don't get why java never makes an reguilar regedit entry for detection
