### ISSUE TITLE
[1.12] Crusher accepts items, but does not produce the result

### ISSUE THREAD

**Issue by KorDum** [BluSunrize/ImmersiveEngineering#2718]
### Description of the issue:
Crusher accepts items, but doesn't produce the result: ore cobblestone, gravel — no resultant items from output side. Discarded input items just disappear when you place them in a crusher. The crusher is full of energy.

https://d1u5p3l4wpay3k.cloudfront.net/minecraft_ru_gamepedia/4/41/%D0%92%D1%8B%D1%85%D0%BE%D0%B4_%D0%B4%D1%80%D0%BE%D0%B1%D0%B8%D1%82%D0%B5%D0%BB%D1%8F_%28Immersive_Engineering%29.png?version=0828d92c1df7cfc0a7be3f662ee6e811

### Versions & Modlist

Forge 1.12.2-14.23.1.2583
IE 0.12-76
Mods: https://gist.githubusercontent.com/KorDum/e523785e296e15afae8f0e539d04f2cd/raw/973c9fee7fd87693c1b3ffafe29a7f0e9a467e61/gistfile1.txt

**Comment by BluSunrize** [comment]
Can you provide a video or otherwise a specific example on how to reproduce this?
Also, can you reproduce this issue with just IE installed?

**Comment by KorDum** [comment]
Sorry, I can't create video, but I tested without any mods in singleplayer. Result in console:
https://gist.github.com/KorDum/edd2de9d014e2091a34d7f299001ebe7
Is this helped you?

**Comment by BluSunrize** [comment]
You changed the speedmodifier in the config to something too low, causing a divide by zero.
Change it back or it'll keep crashing.

**Comment by KorDum** [comment]
Oh, thanks!
