### ISSUE TITLE
[MC 1.12.2][IE 0.12 - 76] - Vertical Conveyor belt Recipe gives 1 instead of 3

### ISSUE THREAD

**Issue by Gariot** [BluSunrize/ImmersiveEngineering#2720]
Hello,

its probably a bug with the Recipe. You get only 1 Vertical Conveyor belt instead of 3. The recipe needs 3 normal Conveyor belts and gives you 1 Vertical back. I am pretty sure it was 3 a while back.

My Forge Version is 14.23.1.2555

**Comment by temp1011** [comment]
I have the same problem.
'{
  "type": "forge:ore_shaped",
  "group": "immersiveengineering:conveyor",
  "result": {
    "item": "immersiveengineering:conveyor",
    "nbt": {
      "conveyorType": "immersiveengineering:vertical"
    },
    "counter": 3
  },
  "pattern": [
    "CI",
    "C ",
    "CI"
  ],
  "key": {
    "C": {
      "item": "#baseConveyor"
    },
    "I": {
      "item": "#ingotIron"
    }
  }
}'
However, from what I can tell the recipe file has the output as 3 conveyors so I'm quite confused as to what is going on.

**Comment by BluSunrize** [comment]
Yeah I think I know what's causing this.
It should be "count" not "counter".

I'll look into fixing this some time today.
