### ISSUE TITLE
[1.11.2] Minecraft crashes when it tries to load "Initializing game"

### ISSUE THREAD

**Issue by AngrySammy** [BluSunrize/ImmersiveEngineering#2721]
Hello
Minecraft crashes when it tries to load
[ImmersiveEngineering-0.11-63]

https://gist.github.com/AngrySammy/00721243c783c08dbe898a535b7d89ae

thanks in advance
Sam

**Comment by BluSunrize** [comment]
1.11 is no longer supported, I'm afraid.
