### ISSUE TITLE
1.12.2- IE manual crash

### ISSUE THREAD

**Issue by Shannara78** [BluSunrize/ImmersiveEngineering#2725]
Halo guys. Sorry for my cheap english. 
Your mod is excelent, I play it at 1.7.10 without any bigger problems, but last time I try MC 1.12.2 and game crashed anytime when I open Engineers manual. 
[https://pastebin.com/e4gCSqay](url)
Thx for any idea how to fix this, is impossible create any multiblock without manual

**Comment by BluSunrize** [comment]
You are most likely using an outdated Java version. Update and make sure your launcher is configured to use it as well.

Next time, please use the search function because this question has been answered many times.

**Comment by Shannara78** [comment]
Have 1.8.0-151, when I click to search update apears - you have latest version....

**Comment by BluSunrize** [comment]
And that is why I said you need to set it in the launcher, because it literally says "build 1.8.0_25-b18" in your log. Use the search function >_>

**Comment by Shannara78** [comment]
I´ve try change it at launcher x-times and still when I starts game have this same version. Sorry that old lumberjack is dumper like your young generation. And sorry that I disturb, maybe is better live without game
