### ISSUE TITLE
[1.12] Drill heads cannot be installed

### ISSUE THREAD

**Issue by rgtexa** [BluSunrize/ImmersiveEngineering#2726]
### Description of the issue:
Drill Heads can be placed in the workbench with the Drill, but the Drill does not recognize that the Drill Head is installed. However, the Drill Head exists in the Drill's inventory and can be removed when the Drill is placed back in the workbench. This applies to both the Iron and Steel Drill Heads.

Does not appear to affect upgrades as it correctly recognizes, for example, the Large Tank and reports the increased capacity.

This happens in single player - I've not tested in multiplayer.

### Crashlog:
There is no crash associated with this.

### Versions & Modlist
Minecraft 1.12.2
IE 0.12-76
Forge 2571
in modpack [Automaton](https://minecraft.curseforge.com/projects/automaton) 1.0.1

**Comment by calloatti** [comment]
This happens with IE as the only mod, and on version 76.

A drill can be fixed by manually editing its NBT data, adding the missing data.

**Comment by Taliom** [comment]
And what I have to do? How I edit the NBT data? Can someone help me because I really want to use the drill

**Comment by malte0811** [comment]
#2709. Fixed for the next release.

**Comment by Taliom** [comment]
Oh okay thanks for answering

**Comment by Frontrider** [comment]
From which version this bug persists? The owner managed to update to this version, and I can no longer log into the server.

Its a problem which needs a hot fix.
