### ISSUE TITLE
[1.12.2] oreDict names for bauxite ore

### ISSUE THREAD

**Issue by Sanofus** [BluSunrize/ImmersiveEngineering#2728]
I do not know if this a bug. I use unification for my modpack. I regocnized that bauxite ore is not registered as oreBauxite or oreAluminum. I thought it was in the past because I have item fliters that uses oreDict and suddenly bauxite ore of IE has been stucked. 
So I checked this put with a Mekanism tool and it did not show up any registration for oreDict. 
I don not know if I am wrong, but if this is not a bug I would to request to register bauxite ore as oreAluminum and oreBauxite.

**Comment by BluSunrize** [comment]
It *should* be registered as oreAluminum. If it's not, that's an error, most likely related to other mods in your pack.
Could you please try to figure out what's causing it? Possibly by removing mods from the pack?

**Comment by JonasCiss** [comment]
I can try this. I also try to register it with UniDict as oreAluminum but that also failed too. I'm unsure which mod should do that and why.

**Comment by JonasCiss** [comment]
https://github.com/WanionCane/UniDict/issues/64

**Comment by JonasCiss** [comment]
Seems Thermal Foundation prevents registration. Bauxite is registered correctly if TF is not present.

**Comment by JonasCiss** [comment]
https://github.com/CoFH/Feedback/issues/833

**Comment by KingLemming** [comment]
TF in no way prevents anything from registering itself to the OreDict. That would be absolutely irresponsible.

**Comment by Sanofus** [comment]
Seems to be it was a  false configuration of UniDict.
