### ISSUE TITLE
[Suggestion] Gauges

### ISSUE THREAD

**Issue by gundrust** [BluSunrize/ImmersiveEngineering#2729]
Could it be possible to add functioning gauges to the multi block models? Maybe a different placeable block to which we could send the information through redstone/wires?

Is very jarring to see the beautifully modelled multi blocks machines be completely static in the world, with no sound, particles or moving parts to give any feedback of their state (except for the few exceptions, diesel and squeezer bois). Even worse is to see the gauges and levels on the textures and expect them to move just to be thoroughly disappointed in their lack of cooperation.

I even was sure there already was something like that, but after an eternity looking I realised I was thinking about the airship mod's gauges.

**Comment by themartin1** [comment]
I agree, this would be awesome. May i add that a way to show if a tank is being filled up og drained might be a useful thing to add, instead of bringing out a bucket and pointing at the tank.

**Comment by malte0811** [comment]
> Maybe a different placeable block to which we could send the information through redstone/wires?

You might like the control panels I added to [Industrial Wires](https://minecraft.curseforge.com/projects/industrial-wires) (IE addon, it doesn't require IC2 any more). They'll display any redstone signal, a lot of IE machines don't output their state as an RS signal though.
