### ISSUE TITLE
[Suggestion] Engineer's Manual Improvements, pictures of completed machines.

### ISSUE THREAD

**Issue by Xiaminou** [BluSunrize/ImmersiveEngineering#273]
The manual is a great guide to all the steps of Immersive Engineering, however I was surprised that there isn't any pictures of the machines in their fully completed state. When I built the machines for the first time I had to disassemble most of them to face them the right way.

I suggest adding a picture of each machine's completed state to give people an idea of what's where.

on a complementary note, I have recently played with botania's latest and got to test the new "blueprint" function from the book, where you can place a "ghost" image of the structure you want to build in the world.
Maybe you could talk to Vazkii about that, I think it would make a great addition to the book.

On a (not completely) unrelated note, I have discovered that energy loss with wires plays an important part in Immersive Engineer (when I built a network of HV I ended up having 500 RF/t instead of 4k). I However have not seen any mention or explanation of that mechanism and am a little confused by it.
I suggest adding a chapter on power loss in the book.

**Comment by theunkn0wn1** [comment]
a chapter dedicated to power loss should be added.
Power loss is poorly documented however documentation *does* exist...
![image](https://cloud.githubusercontent.com/assets/3110986/9075810/4013a56c-3ace-11e5-8ee6-867c3f58c13c.png)
that is the one and only reference i could find in the in-game book about the subject.

Also exactly **how** big is this HV network of yours? i have a fairly big one transferring over 5KiRf/T with minimal (~100->300 Rf/T avg.) loss

**Comment by Xiaminou** [comment]
I'd say about 20 HV Wire connectors all getting power from a diesel generator.
from what I've tried if I connect more than one HV Wire connector I get a significant power loss, we're talking 3kRF/t for 2 connectors, 2k for 4, these are approximations of course but you can see how that would be a problem.
The truth is, I (we?) don't know how the power is distributed, I do remember Direwolf saying that machines were getting powered from the closest to the farthest, which might explain some of it, but I would definitely like to see a chapter explaining how power works, with as much details as possible.

**Comment by theunkn0wn1** [comment]
Twenty HV wire connectors from *ONE* diesel  generator?! um.. i am totally missing the picture.....

My setup has two main power suppliers, a pair of desil generators with a total of 6 HV wire connectors using multiple stacks of relays to the main network.
my secondary power station produces  ~5KiRF/T with a peak transfer rate of ~10KiRF/T
that setup required the use of 12 HV wire connectors just to extract the power at a reasonable rate....

the power is consumed over 25 chunks away with negligible losses.

anyways.. if you want details on how the power is handled/distributed i went into some detail in #187

**Comment by BluSunrize** [comment]
Thing is that every multiblock render is different. They are all rendered by different blocks of the overall structure, all need different flags set to render right...those renders are only supposed to work on a correctly assembled structure.
I'll look into it.

**Comment by Xiaminou** [comment]
I didn't understand any of what you just said, and don't understand why putting a picture of the machines in their "working" state is so hard, but I'm gonna take your word for it.

**Comment by BluSunrize** [comment]
because I wasn't talking about a picture, I was talking about a render. Entirely different things.

**Comment by Xiaminou** [comment]
but does it have to be a render? or is it because you want it to be rotatable or something?

**Comment by theunkn0wn1** [comment]
It would be most efficient if @BluSunrize used renders as they would both be manipulable by users as well as more readily updated in case the structure changes in a future update.
With botania, the structures are fairly simple imho, and require few different types of blocks to form.
IE's MBs become significantly more complicated as the user goes up in tier.

@Xiaminou, With MBs the proccess of forming the blocks that comprise it into the single world entity requires a few pieces of logic:
@BluSunrize this is my understanding of MBs, correct me if i am wrong
[1] Is the MB valid? 
[1][a] are all the required blocks present?
[2]If [1] is OK then what orientation is the MB in?
[2][a] Which of the four forge directions am i in? (up/down not included)
[3] ok, now transition between the default and the working state
[3][a] Hide the precursor blocks (make them invisible to the user)
[3][b] retrieve GL model of working state, rotate it to match [2][a]'s output
[3][c] Display GL model of working state, bind it to the corners of the MB structure
[3][d] Enable 'working state' functions, such as the GUI, power inputs, etc....
[4] monitor MB structure for modification, do 'working state' stuff
[5] revert to [1] if structure modified/damaged

Its not exactly simple, and rendering can be just as difficult as checking the structure.

@Xiaminou, renders give significantly more information to the user than static images,
Renders that allow for user manipulation, such as rotation, grant the information to be much more understandable and accessible.

**Comment by Xiaminou** [comment]
Okay, that's what I thought.

**Comment by cobra** [comment]
I think this issue can be closed now, the manual will show the model in 0.6.

**Comment by BluSunrize** [comment]
True
