### ISSUE TITLE
[1.11.2] Incompatibility with new forge versions.

### ISSUE THREAD

**Issue by Diamond45123** [BluSunrize/ImmersiveEngineering#2739]
### Description of the issue:
The Game crashes after updating to forge 2579 or 2588. It crashes after loading everything and then crashes. I don't know if it's a problem with Immersive Engineering or what, but I found similar issues but with 1.12.2 so I believe its immersive engineering.

### Crashlog:
https://pastebin.com/j0z0nrFt

### Versions & Modlist
IE 0.11-63
Immersive Petroleum 1.1.3
Forge 2579 is used in the crash I believe.

**Comment by Diamond45123** [comment]
Just tested something to make sure it's Immersive Engineering's problem, and it is. 
Made a new modpack with the only two mods, and forge 2588. It crashed the same crash.
I updated Immersive Petroleum to its latest version 1.1.3 to make sure it didnt get fixed in the newest update and it still has the issue.
https://pastebin.com/KTKVBd7c

**Comment by malte0811** [comment]
1.11 is no longer supported. On 1.12 this crash is fixed in the latest release of IE.
