### ISSUE TITLE
Voltmeter dud

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#274]
Issue:
==================
item "Engineer's Voltmeter" when used as described in the book, does nothing.

Action:
-----------------------
Shift-Right-click(SRC) Connector one and SRC the second connector (wired together via Electrum wire)

Expected result:
------------------------
Voltmeter would output (via chat most likely) the power loss between the two points before returning to default state

Actual result:
-------------------
No return of any kind, Voltmeter returns to default state.

Steps to reproduce:
------------------
[1] set up two wire connectors of any kind, placing them in FOV of each other before wiring them together successfuly.
[2] use the "Engineer's Voltmeter" as described in the book on the two connectors.

Info:
-----------------------
Running FTB Infinity (1.9.0) with no mod additions/deletions other than IE
IE version 0.5.0 built against 3bc2e46b5515b958c8ed53134faf715ee545431f

**Comment by BluSunrize** [comment]
It only works on points that serve as actual power in-/outputs.
