### ISSUE TITLE
Immersive Engineering FIX

### ISSUE THREAD

**Issue by Edy12334** [BluSunrize/ImmersiveEngineering#2740]
When I install Immersive Engineering on forge 1.12.2 this happens:
https://imgur.com/tV682Lr
HELP PLS!!!

**Comment by malte0811** [comment]
Take a look at the contributing guidelines. There's a link to them when you create an issue. If you include the information requested there and a full client log we may be able to help you.

**Comment by Edy12334** [comment]
I'm new here and I'm not good at english.If u know what myb makes the issue I would appreciate your help

**Comment by malte0811** [comment]
What language are you better at? I do not know what causes the issue, because you didn't tell me enough about it. And please, try to use more complete english (e.g. please rather than pls). It makes the comments a lot harder to read and time isn't an issue.
