### ISSUE TITLE
[Feature Request] [Enhancement] Pump pulling from inventories

### ISSUE THREAD

**Issue by Silvrus** [BluSunrize/ImmersiveEngineering#2742]
Thanks for your hard work on such a great mod! I could've sworn this was a feature at some point, but I appear to be wrong. I don't know how difficult it would be to implement, but I was wondering if we could get the pump to be able to do inline extraction. For example, a bank of coke ovens with pipe attached to them, the pump placed down the pipeline with a side set to input, and be able to pull out of all the attached inventories, then output via another face. Could have it require more power the more inventories it is working with, and operate slower when it's not receiving enough power. I wouldn't want it to be able to handle more than 1 fluid at once though, to keep with the realism.

**Comment by malte0811** [comment]
Inventories are usually for items, but I guess you are talking about tanks/fluids. The pump should be able to do that in the current 1.12 version of IE as long as the side the tank is on is set to input (you can change the setting on the side opposite to the one you click by shift-clicking)

**Comment by Silvrus** [comment]
Yeah, I'm using inventory a bit broadly. Interesting though, I tried doing this and it didn't work. I had 2 coke ovens, 3 blocks apart. Placed down a pump 1 block away from each, set both sides near the ovens to input (blue), connected a pipe to each side, set another side to output (orange) connected to another pipe leading to a Mekanism tank and fully powered the pump. The creosote wasn't pumped out of either oven. Perhaps it was the Mekanism tank, I can try again when I get home tonight, I've since set up an IE tank and ran BC pipes from the ovens.

**Comment by Silvrus** [comment]
I just got done testing, using a couple different setups. [Pics](https://imgur.com/a/KdCrY) shows what I'm trying to accomplish.

**Comment by ktole1999** [comment]
the pump would not work as intended unless its connected to the oven. you would have to make the pipe extract and then input to the pump or have pump extract from the pipe. this can already be accomplished with enderio fluid conduit, tanks, transfer node, etc. why reinvent the wheel? unless i am missing your point in which case i apologize.

**Comment by Silvrus** [comment]
I realize this can be done with other mods. Currently I'm using BC fluid pipes to extract the creosote, I just thought it would be a cool feature for the IE pump to be able to extract using it's pipe connected to fluid tanks. I'm in the process of building an expert type pack which will have more "advanced" forms of fluid handling gated.
