### ISSUE TITLE
[1.12.2] Client crash when pumpkin place on connector

### ISSUE THREAD

**Issue by KorDum** [BluSunrize/ImmersiveEngineering#2743]
ImmersiveEngineering-0.12-77

### Description of the issue:
Client crash when pumpkin place on connector

### Crashlog:
https://gist.github.com/KorDum/8f83f2051064c13460244e72b41aa25e

**Comment by malte0811** [comment]
Try without Optifine.
If it doesn't happen without OF: I managed to get OF working in a dev environment recently (took 2 hours), so I might look into it if I have the time. In general issues that only occur with Optifine are not supported though.

**Comment by KorDum** [comment]
Yes, crash is and without Optifine
https://gist.githubusercontent.com/KorDum/6002a934dcb1a65cb0aa8776e95c5138/raw/404ea7b48ffc2854ef2fc0316f26358c18f134c7/gistfile1.txt

**Comment by malte0811** [comment]
Looks like a forge bug, I'm working on the fix now (the fix itself is easy, Forge developer workspaces aren't).

**Comment by malte0811** [comment]
I made the PR (linked above), the fix should be in Forge soon. I'm closing this since it isn't a bug in IE.
