### ISSUE TITLE
Tweak the bayonet as a attachable and removable dagger

### ISSUE THREAD

**Issue by HappyPineapple** [BluSunrize/ImmersiveEngineering#2746]
Add a dagger that has a 3D model and can be used as a removable dagger/bayonet

**Comment by EvilCooky** [comment]
there already is a knive attachment for the revolver

**Comment by HappyPineapple** [comment]
yes I know that but does it work as a weapon by it's self

**Comment by EvilCooky** [comment]
I don't think so, but why should it?
We still have swords for that.
