### ISSUE TITLE
Drill head won't equip[1.12.2]

### ISSUE THREAD

**Issue by Dovoski** [BluSunrize/ImmersiveEngineering#2747]
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
Drill head won't register when attached. The drill head technically still stays with the drill since even when the drill is removed an put back on the bench the drill head is there, but the drill doesn't change as a result of the head.

### Versions & Modlist
Forge 1.12.2
IE 1.12.2
JEI 1.12.2

**Comment by malte0811** [comment]
#2709. And "IE 1.12.2" is not a useful description of the IE version. There are ~13 versions of IE that fit the description. IE 0.12-76 would be moer helpful.
