### ISSUE TITLE
EE3 Values

### ISSUE THREAD

**Issue by Fortist** [BluSunrize/ImmersiveEngineering#275]
When I updated this (and subsequently AOBD), a lot of the EE3 values are removed for various items with innate support for it, and some added through EE3Helper or whatever mod is called.
My initial test merely just rolls back to 4.4 and the last AOBD that supports it (since the game crashes with an updated AOBD, due to the API changing in the 5.0 versions), and thus everything works as intended. Ill probably test AOBD by itself to see if that causes anything, as not to put all the blame on this mod.

**Comment by BluSunrize** [comment]
What version of EE3 are you using?

**Comment by Fortist** [comment]
You know, I didnt think about trying to update EE itself. Im using 0.3.507.
I should go check for updates for it.

**Comment by BluSunrize** [comment]
Yeah 507 is the latest, which is also what I am using. Weird. I'll go check it out.

**Comment by Fortist** [comment]
It may just be something I did, but anyway, Im just gonna get rid of EE3 for (the superior) ProjectE, since it handles values on its own without a second mod.
Just a FYI, the secondary mod I used was this http://minecraft.curseforge.com/mc-mods/231701-ee3-helper
I also was mucking about with EE3's configs for always checking values and the "only when mods change."
While also using ee3helper's regen command and additions. 

At this point, Im pretty sure it's a "me" problem.
You're welcome to check it out but I just say to not waste your time on it.

**Comment by cobra** [comment]
Now that we've got EMC values back, here's a list of items missing an EMC value as of e6bf7a3, despite all crafting ingredients having an EMC value:
- all wire coil blocks
- LV wire connector (all other connectors do have EMC)
- all capacitors
- Lantern
- radiator 
- wooden grip
- tough fabric
- iron, steel mechanical components
- all wire coils (items)
- engineer's hammer
- engineer's voltmeter
- bayonet
- blueprint for common projectiles
- graphite electrode

I did not list any item missing an EMC value with any of the ingredients also missing an EMC value (and, of course, items without a recipe).

**Comment by BluSunrize** [comment]
This is due to bugs existing with EE3 itself, and the fact that ore dictionary recipes only work if every entry of the ore item used has a value.

**Comment by cobra** [comment]
That's what I thought, just compiled a list of all this stuff for future reference.

But the graphite electrode shouldn't be affected by this, right?

**Comment by BluSunrize** [comment]
It's created using a Bluepritnt recipe, EE3 can't handle those. Also I don't want it to be craftable by EE either. Graphite is one of the few "hard" balances in IE atm.

**Comment by cobra** [comment]
…and now that's somewhat documented, so there shouldn't be any new tickets about this. Hopefully.

**Comment by BluSunrize** [comment]
hehehe
