### ISSUE TITLE
[1.11.2] Crashes on startup with mod installed, conflict with latest forge version

### ISSUE THREAD

**Issue by chaNcharge** [BluSunrize/ImmersiveEngineering#2750]
### Description of the issue:
When I have this mod installed, it crashes on the final stage of loading "Completing Minecraft initialization". I provided a screenshot of when it crashes, the crash report, and the fml-client-latest.log files. **This also reproduces with just IE and Forge installed.** My guess it's an issue with the latest version of Forge.

### Crashlog:
Crash: https://gist.github.com/chaNcharge/60f9b13c25117003e42992b26949c2fb
fml-client-latest.log file: https://gist.github.com/chaNcharge/6e717b5433c27f14a23c193c876b3a49
fml-client-latest.log file with just IE: https://gist.github.com/chaNcharge/056e9299a604d31cf393ccdb17eb2eca
Screenshot: 
![screen shot 2018-01-21 at 11 00 44 am](https://user-images.githubusercontent.com/11594018/35197925-f307a48c-fe9b-11e7-976d-d2d3e09d10c6.png)

### Versions & Modlist
Minecraft: 1.11.2
IE: 0.11-63
Forge: 1.11.2-13.20.1.2588

**Comment by malte0811** [comment]
Minecraft 1.11 isn't supported any more. You can prevent the crash by using an older Forge version.
