### ISSUE TITLE
Excavator defaults to broken texture when no block is possible

### ISSUE THREAD

**Issue by davqvist** [BluSunrize/ImmersiveEngineering#2755]
### Description of the issue:
I am making a modpack and edited with Crafttweaker which minerals can be gotten with the Excavator, mostly switching out ore blocks to dust versions. It all worked fine, but the Excavator now shovels broken textures out of the ground as no block texture is available to be shown. https://cdn.discordapp.com/attachments/362326885784354818/406387544419336192/2018-01-26_10.58.07.png
I wonder if a default texture like stone could be used in this case instead.

### Versions & Modlist
Forge 2599
IE 0.12.76

**Comment by BluSunrize** [comment]
Yeah, the excavator is meant to dig up blocks, not items. That would be why.

**Comment by malte0811** [comment]
Pyrite veins seem to have sulfur dust if there isn't any ore (from a quick look at the code).

**Comment by davqvist** [comment]
Exactly this. Sulfur Dust is supported by standard and I just added dusts myself without any ores.
