### ISSUE TITLE
[1.12] Wooden Storage Crate "Payload may not be larger than 32767 bytes"

### ISSUE THREAD

**Issue by Andvee** [BluSunrize/ImmersiveEngineering#2756]
### Description of the issue:
Crash when attempting to place specific items into a Wooden Storage Crate resulting in error "java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes".

Items placed inside prior to crashing include: Resonating Wand (Astral Sorcery), Ender Chest (Vanilla), Illumination Wand (Astral Sorcery), Pickaxe (Tinkers Construct), Excavator (Tinkers Construct), Iron Axe (Vanilla), Bucket * 4 (Vanilla), Apiarist's Backpack (With individual contents)(Forestry).

Crash will repeat whenever attempting to check contents.

Attempted to resolve crash by connecting a vanilla Hopper on top of a Conveyor Belt pulling items from the affected Wooden Storage Crate. This caused one additional crash however after reloading the world once more the items had safely been pulled from the Crate resolving the immediate problem.

https://gist.github.com/Andvee/e8da05bd70ace55d4aeb1baca4229ab8

### Versions & Modlist

architecturecraft-1.12-1.20
astralsorcery-1.12.2-1.8.5
AutoRegLib-1.3-15
Baubles-1.12-1.5.2
BetterBuildersWands-1.12-0.11.1.245+69d0d70
BetterFps-1.4.8
BiblioCraft[v2.4.3][MC1.12.0]
Botania r1.10-352
buildcraft-7.99.14
Ceramics-1.12-1.3.3b
Chameleon-1.12-4.1.3
Chisel-MC1.12-0.1.1.26
chiselsandbits-14.11
ComputerCraft1.80pr1
CTM-MC1.12-0.2.3.12
CyclopsCore-1.12.2-0.11.1
EvilCraft-1.12.2-0.10.45
FoamFix-1.12.2-0.8.3-Anarchy
forestry_1.12.2-5.7.0.238
ImmersiveEngineering-0.12-76
ImmersiveEngineering-0.12-76-core
InventoryTweaks-1.63
jei_1.12.2-4.8.5.138
journeymap-1.12.2-5.5.2
Mantle-1.12-1.3.1.21
MouseTweaks-2.8-mc1.12.1
OptiFine_1.12.2_HD_U_C8
Quark-r1.4-122
Reliquary-1.12.2-1.3.4.728
StorageDrawers-1.12.2-5.3.4
TConstruct 1.12.2-2.9.0.55
theoneprobe-1.12-1.4.19

**Comment by BluSunrize** [comment]
Probably the Apiarists' Backpack that did it. As far as I remember, the NBT data on bees is hillariously large...

@malte0811 did I remember correctly that you had looked into restricting items based on NBT size before?

**Comment by malte0811** [comment]
I have, and this is fixable. I made our items use share tags, but I didn't use share tags for the content items. I'll try to fix it today or tomorrow.

**Comment by malte0811** [comment]
Is this in singleplayer or on a server? The log looks like singleplayer to me, but in the past this was usually a server-only issue (IIRC).

**Comment by Andvee** [comment]
Single Player world.

**Comment by malte0811** [comment]
@Nedelosk you seem to be the most active Forestry dev right now. I'm pretty sure this is on your end, your items don't implement `getNBTShareTag` (the method relevant for this), just `getShareTag` (which just determines whether any NBT will be send, you set that to true).

**Comment by Nedelosk** [comment]
The hillariously large NBT data on bees is currently on my To-do-Liste for 1.13. We can't use `getNBTShareTag`, because of the changes in the internal structure would be a breaking change for all addons.

**Comment by flamablecharlie** [comment]
I can confirm that this bug is with Bibliocraft, and is NOT because of Forestry. It happens on my server as well, with Immersive Engineering. But ONLY when placing books from Bibliocraft in an IE Wooden Storage Crate.
