### ISSUE TITLE
please help me. Problems with immersive engineering (but it is not exactly)

### ISSUE THREAD

**Issue by VladCraft1** [BluSunrize/ImmersiveEngineering#2757]
https://pastebin.com/FXMfFwpU

**Comment by malte0811** [comment]
1. 1.7.10 isn't supported any more and hasn't been supported for close to 2 years.
2. That crash usually only happens with Optifine. You seem to be using BetterFPS, that might also cause the crash (even though I've never seen that happen before).

**Comment by VladCraft1** [comment]
removed BetterFPS, still crash
https://pastebin.com/m7GQrGqr

**Comment by malte0811** [comment]
Are you sure you aren't using Optifine? I think there are ways to install it that don't get mentioned in crashes. Other than that I can't help you, I haven't even got a 1.7.10 dev environment on this computer.

**Comment by VladCraft1** [comment]
Optifine did not even install.

**Comment by VladCraft1** [comment]
version Forge 1.7.10 - 10.13.4.1614
