### ISSUE TITLE
[1.12] Placing comparator out of Excavator causes crash.

### ISSUE THREAD

**Issue by IMarvinTPA** [BluSunrize/ImmersiveEngineering#2758]
### Description of the issue:
I placed a comparator reading an excavator attached to its redstone engineering block.
This was a single player world.
The world loads and it appears to work fine on reload.
However, I removed and placed it again and a second crash.

### Crashlog:
https://paste.ee/p/aUvKm
The key bit of the crash log:
java.lang.NullPointerException: Unexpected error
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityExcavator.getComparatorInputOverride(TileEntityExcavator.java:78)

### Versions & Modlist
Forge: 2594
IE: 0.12-76
IP: 1.1.6

**Comment by malte0811** [comment]
Is this in a chunk without an ore vein (specifically, is the middle of the wheel in such a chunk)? If it is, the crash makes sense. But why did you build an excavator in a chunk where it won't do anything useful?

**Comment by IMarvinTPA** [comment]
I put the entire machine within an Iron Ore chunk.  (The comparitor itself is in an empty chunk though.)  The chunk has 11k ore remaining.
