### ISSUE TITLE
[1.12.2][IE-76] Chemical thrower not outputing any liquid

### ISSUE THREAD

**Issue by Zahkriiven** [BluSunrize/ImmersiveEngineering#2759]
### Description of the issue:
Chemical thrower consumes liquid, the meter lowers and the sound works but it doesn't output any liquid.
It is not only visual, i tried using lava and biodiesel with fire mode against mobs and animals.
Tested it in a new world with IE alone.

### Versions & Modlist
ImmersiveEngineering-0.12-76
forge-14.23.1.2607

**Comment by malte0811** [comment]
Duplicate of #2736. Fixed for the next release.

**Comment by Zahkriiven** [comment]
Uh, sorry about that, i've searched "chemical" and those reports didn't contained it my bad.
