### ISSUE TITLE
[1.10.2] Powered lights not turning on

### ISSUE THREAD

**Issue by Wohlf-craft** [BluSunrize/ImmersiveEngineering#2763]
### Description of the issue:
I have a system when night time comes it turns the lights on. I have setup 2 of these and it still does not work. Sometimes flicking the switch does not work.

### Crashlog:
https://pastebin.com/kThfvpsr

### Versions & Modlist
Version 1.10.2 = 0.10 - 61
Forge: I don't remember. I made this modpack ages ago and still testing it.  
Wait wait found it: 1.10.2-forge1.10.2-12.18.3.2488 

## Other
No I can't test this without, the other mods being in it.

I dont know how to post screenshots so I am using imgur, sorry I rather not use my api page. (TUB - The ugly box aPis)
And I don't see an inset image button.
https://imgur.com/Sc3hYYM
Sorry, I don't really know github.

**Comment by laserlemons** [comment]
It looks like the lights in the back are working. Are you sure that the wires aren't running out of power?

**Comment by Wohlf-craft** [comment]
No I have the same setup on the other side. And the other side is not working.
