### ISSUE TITLE
Excavator not playing well with Geolosys ores

### ISSUE THREAD

**Issue by BigAl607** [BluSunrize/ImmersiveEngineering#2765]
Excavator not digging up Geolosys ores. I've tried adding the following 3 lines of code to the CraftTweaker recipes.zs file without success:

`mods.immersiveengineering.Excavator.addMineral("Coal Ore", 50, 0.005, ["geolosys.ore_vanilla.coal"], [50], [0]);`

``mods.immersiveengineering.Excavator.addMineral("Coal Ore", 50, 0.005, ["geolosys.ore_vanilla.0"], [50], [0]);``

``mods.immersiveengineering.Excavator.addMineral("Coal Ore", 50, 0.005, ["geolosys.ore_vanilla:0"], [50], [0]);``

I realize the excavator doesn't pull ores that are actually there, but how can I fix it so it will? The excavator would be rendered useless using Geolosys for ore gen if you can't get it to pull ore chunks is sitting right on top of.
![2018-02-03_21 43 41](https://user-images.githubusercontent.com/13182567/35773838-e8c5cd92-092b-11e8-9fd9-4cc533797a1c.png)
![2018-02-03_21 43 59](https://user-images.githubusercontent.com/13182567/35773839-e8d99138-092b-11e8-81b9-21dcdd8a1103.png)

**Comment by malte0811** [comment]
You can't "fix" it so it will use ores generated in the world. It isn't intended to work that way and it (probably) never will. The veins you added will generate randomly in the world, but without any relation to the ore blocks generated by geolosys. The idea is that the excavator digs up ores generated below bedrock, not accessible by normal methods.

**Comment by BigAl607** [comment]
So what you're saying is I need to remove the excavator from my pack. Thanks.

**Comment by BluSunrize** [comment]
What he's saying is that you fail to understand the point of the excavator. It's an infinite resource miner, which is fully independent from any blocks in the world. The 8 blocks it breaks at the start are solely for show.
If you want to add Geolosys ores to it's drop table, then you can do so via the Crafttweaker commands, but they require oredictionary names. Please refer to the Crafttweaker documentation website for further details.
