### ISSUE TITLE
[1.12.2] Duplicated renders

### ISSUE THREAD

**Issue by LiskoSlayer63** [BluSunrize/ImmersiveEngineering#2767]
Sometimes the multiblock structures are rendered twice and it causes some wierd looking things. This isn't affecting the actual gameplay but it's not very beautiful. This seems to happen also for addons of this mod, for example Solar Towers from Immersive Tech does the same thing. All of these bugs happen randomly when the chunk is loaded. I googled this and I think that OptiFine and/or FoamFix might affect to this so I tried without them, but the problem still occurs. I don't think that this is your fault, but I hope that you can say what's going on there.

**_There's three Tanks built in this screenshot:_**
![2018-02-05_04 54 45](https://user-images.githubusercontent.com/10125529/35786686-a814f1e0-0a31-11e8-83a3-f7dbe919a382.png)

**Immersive Engineering version:** 0.12-76
**OptiFine version:** 1.12.2_HD_U_C8
**FoamFix version:** 0.7.4 (newer versions cause huge lag)
**Forge version:** 14.23.1.2586
**Minecraft version:** 1.12.2

**Comment by BluSunrize** [comment]
Graphical issues due to optifine are invalid, as stated by the contribution guidelines.
