### ISSUE TITLE
[1.12.2] Tinkers Construct Scythe/Kama cannot reap Industrial Hemp

### ISSUE THREAD

**Issue by ChronosWS** [BluSunrize/ImmersiveEngineering#2768]
It appears the TC scythe/kama can only reap crops which extend BlockCrops, and it seems Industrial Hemp does not do this.  Seems like it probably should (if for no other reason than to generally behave like other crops in MC which presumably derive from this base class.

**Comment by KnightMiner** [comment]
We don't just do blockcrops, there is an event for less regular crops to tell the scythe something is a plant as well.

**Comment by ChronosWS** [comment]
Hmm, is this something that needs to be coded in as an integration?  Is it an issue with the Scythe (in which case I can take the issue to Tinkers)?  Or is it not intended to work in this case?

**Comment by Cyprex** [comment]
@ChronosWS I recommend abbreviating Tinker's Construct as TiCon as TC is a common abbreviation for Thaumcraft. I didn't realize until your later comment that you meant TiCon and not Thaumcraft.

**Comment by BluSunrize** [comment]
Bringing this back up front

See https://github.com/SlimeKnights/TinkersConstruct/issues/3381
