### ISSUE TITLE
Config option to change fluid tank capacity

### ISSUE THREAD

**Issue by PandaBoy444** [BluSunrize/ImmersiveEngineering#2769]
I would like a config option to change fluid tank capacity, I want to use Immersive engeneering for as many things as possible because its so cool. But when I can store 8 times as much with a fraction of the price its problematic

**Comment by BluSunrize** [comment]
Nah, it's fine.
IE isn't meant to incentivise people with better stuff but with better looks ^_^

**Comment by PandaBoy444** [comment]
Common, there are config options for everything but that.

**Comment by TheDeviantCrafter** [comment]
I'm currently building a modpack where Immersive Engineering is the best mod available for quite a few tasks. The crusher, arc furnace, and excavator are all end-game machines.

I'm not doing this by buffing IE, but by nerfing everything else so IE acts as a baseline. This works for the most part, but storage is one thing I can't really apply that approach to. Large scale storage is something any end game player will need. I'd like IE to be able to fit that role.
