### ISSUE TITLE
revolvers

### ISSUE THREAD

**Issue by liamjarvisman** [BluSunrize/ImmersiveEngineering#277]
with all the revolvers in immersive engineering how do you check to uuid and change the revolver types and is there a bit of code i can look at to see how to happens because i'm learning how to make a minecraft mod and this is something i want to have in my mod but with a different item.

**Comment by BluSunrize** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/items/ItemRevolver.java#L333-L334
this is where I grab the players UUID and check whether they are in the Multimap "specialRevolvers". If they are, various changes are made to the NBT data of the revolver, affecting its functionaility and render.

As to how that list is created:
https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/ImmersiveEngineering.java#L101
After the instance is fully loaded, I start the downloader thread,
https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/ImmersiveEngineering.java#L145-L184
Which grabs the information in form of a .json file from this github. It parses the json and adds all the special variations of revolvers to the respective player UUIDs.

**Comment by liamjarvisman** [comment]
if i downloaded the source code and i wanted to try out the other revolvers is there a way to change the uuid's to mine so i can see the other revolver?

**Comment by liamjarvisman** [comment]
i meant i did download the source code that was a spelling mistake

**Comment by BluSunrize** [comment]
The revolvers are exclusive to certain users and will remain so. Since no one else has push permissions to this repo, the only way you're getting in that JSON is if I add you to it.

You /could/ download+modify the source to see the others. But I will not instruct you on how to, because I do not /intend/ for others to have them.
