### ISSUE TITLE
[1.12.2] Mobs try to jump over IE fences

### ISSUE THREAD

**Issue by ViciousVinnyD** [BluSunrize/ImmersiveEngineering#2771]
Mobs keep trying to jump over IE fences, as if they were regular blocks that can be jumped over. This does not happen with vanilla fences.
Also, leads cannot be tied to IE fences.

ImmersiveEngineering-0.12-76
forge-1.12.2-14.23.1.2604 (36 mods installed)

**Comment by BluSunrize** [comment]
Can't be helped I'm afraid. Leads are very poorly done in code. I've tried fixing them before to no avail.

**Comment by malte0811** [comment]
Pathfinding should be fixable, similar to [this](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/test/java/net/minecraftforge/debug/BlockAiNodeTypeTest.java). There is a node type for fences, I assume that prevents mobs from trying to jump over it.

**Comment by ViciousVinnyD** [comment]
How come Binnie's Extra Trees, Forestry and Biomes O' Plenty fences all have lead and mob pathfinding compatability? Surely if all 3 of those mods can do it this mod can too, right?

**Comment by malte0811** [comment]
The pathfinding: yes, as I said above.
The leads: It would be possible, but it would break existing fences in the world (they are currently part of a different block, they would need to be separated out for lead compat). This might be a good thing to put on a to-do list for 1.13, which is something I should make.

**Comment by BluSunrize** [comment]
This feature is fixed on master, so I'll close this.
