### ISSUE TITLE
[1.12.2] Thermoelectric generator not creating power

### ISSUE THREAD

**Issue by DoomSquirter** [BluSunrize/ImmersiveEngineering#2775]
### Description of the issue:
Connect up a thermo using either solids (yellorium blocks and packed ice) or fluids (water/lava) and no power shows up in TOP nor if connected to lv capacitor, does any power get sent to cap.

### Versions & Modlist
forge: 14.23.2.2611
ImmersiveEngineering-0.12-76
ImmersiveEngineering-0.12-76-core

other IE related mods:
ImmersiveCables-1.12.2-1.2.0.1
immersivepetroleum-1.12.2-1.1.7
immersivetech-1.12-1.3.4

Playing in pack MSB 3 version 3.1.1.1
https://minecraft.curseforge.com/projects/modern-skyblock-3-departed

        # Output modifier for the energy created by the Thermoelectric Generator
        D:thermoelectric_output=1.0

if you know these work in stated version for a fact, then I'll post an issue on pack makers github and reference this issue there.  This is more or less just a verification request from your end that you know the thermos work in this version or not.  

Thanks alot

**Comment by BluSunrize** [comment]
Pictures of the setup please

**Comment by DoomSquirter** [comment]
sure.
https://imgur.com/zfGXwXd

**Comment by BluSunrize** [comment]
Yeah that's about what I figured. You're using LV Relays, not Connectors.
I'd recommend reading the manual again.

**Comment by DoomSquirter** [comment]
good god I'm an idiot.  lol so sorry haha

I thought there was a problem even before I connected since top didn't show any rf in the thermo.  I then went into no brain mode and made the wrong damn thing.  *facepalm*  a 1000 apologies.
