### ISSUE TITLE
[Suggestion] Melon -> Melon Slices

### ISSUE THREAD

**Issue by Yankas** [BluSunrize/ImmersiveEngineering#2777]
Unless I am missing something, there is currently no way to turn the Melon blocks from Garden Cloches into Melon Slices using just Immersive Engineering and Vanilla mechanics. This isn't a problem for most people since most mod packs will have some kind of block placing mechanic that can be used in conjunction with block breakers (or pistons) to turn them into slices, but nevertheless I think the option to do it within IE or Vanilla would be useful, after all what's the point of growing lots of melon if you can't use them.

**Possible Solutions:**
- Crafting Recipe (Block -> Slices)
- Crusher produces melon slices
- Fermenter also accepts melon blocks
- Garden Cloche outputs Melon Slices
- Adding a block placer

A crafting recipe would be the simplest and most intuitive solution, that way people can run melons through an assembler to turn them into melon slices; but if automation of the melon-breaking process is supposed to be part of the experience, then adding some additional tools to place them into the world would be required.

**Comment by mindforger** [comment]
>A crafting recipe would be the simplest and most intuitive solution, that way people can run melons through an assembler to turn them into melon slices; but if automation of the melon-breaking process is supposed to be part of the experience, then adding some additional tools to place them into the world would be required.

sounds like a perfect hammer recipe to me

**Comment by Voxel-Friend** [comment]
In my opinion, I would prefer a block placer and breaker native to IE. Just saying. Could be used in other automation shenanigans.

**Comment by EvilCooky** [comment]
That sounds like a perfect application for a saw multiblock.
Maybe we will see something like that in the future.
