### ISSUE TITLE
Details missing from Engineer's Manual

### ISSUE THREAD

**Issue by MauveCloud** [BluSunrize/ImmersiveEngineering#2778]
I'm still fairly new to the mod, playing in 1.12 and using build 0.12-76, but I've noticed some things that the manual doesn't cover well:
1. Relays can have more than just two wires attached.  I didn't realize that until I saw the picture linked in #2775, since the pictures on page 3 of "Basic Wiring" show at most two wires connected to a relay.
2. Asymmetric multiblocks such as the fermenter or industrial squeezer can apparently be constructed in mirror image and still work.  Admittedly, I'm not sure where this information could be added to the manual.
3. Most multiblock descriptions in the manual indicate which block to activate with the Engineer's Hammer to form the multiblock, but the Excavator has no such indication for either of the two pieces that comprise it.
Edit:
4. Only the diesel generator specifies the output in Flux/t in the manual (others have outdated details listed in the ftb wiki, such as https://ftb.gamepedia.com/Improved_Windmill which might be accurate for 1.7.10 builds, but in 0.12-76, I determined that a windmill with a full set of sails produces roughly 35 Flux/t in clear weather regardless of y level)
5. For the thermoelectric generator, a list of a few fluid temperatures would help for comparison (especially the vanilla fluids water and lava), since the only in-game way I've found so far in 1.12.2 to find the temperature of a fluid is to view it in the GUI of an IE machine such as a coke oven or assembler.  In 1.7.10 the mod "NEI Integration" has options to allow looking up fluid registry details, but I don't know of a mod for 1.12.2 that does that.
6. Only a few machines specify power consumption in the manual: External Heater, Tesla Coil, Blast Furnace Preheaters, and Excavator.  The description for the Crusher says "the machine's processing speed depends on the power supplied to it", but presumably there is a maximum power usage, and supplying more than that makes no difference to the speed.  There might also be a minimum power usage, below which the machine completely grinds to a halt.  (Edit 2: apparently not.  I tried powering an Excavator from a single windmill with no sails: the wheel only budged once every 18 seconds, and it took roughly 11 minutes 49 seconds between outputs, but it technically kept going)

**Comment by BluSunrize** [comment]
I'll preface this by saying: IE is not intended to be documented into every niche. I firmly believe that Minecraft mods should  bring some element of exploration within their mechanics, encouraging users to experiment to find all its wonderful features. I learned that for Azanor.

1. Literally the point of relays, trial & error is key here
2. Basically all users find this out subconciously by just doing it wrong and having it work anyway
3. Back center block. Trial and error strikes again.
4. Kinetic Generators have dynamic numbers based on flowspeed of the fluid or obstruction of the windmill. There is too many permutations. THe Wiki is not an offiicially endorsed source of information in any way.
5. There is too many fluids in modded MC to list them all alogn with their temperature.
6. Once again, I don't rely on IE work on hard numbers and information. I eyeballed most values and when playing myself I always just made sure that my generation powered my machines without the batteries draining. That's way simpler than requiring players to calculate it all =P

Sorry for the rather short replies, but there isn't anything in there that I consider worth changing.

**Comment by MauveCloud** [comment]
2. How many multiblocks can reasonably be "accidentally" constructed in mirror image?
3. That only applies to the outer part of the excavator, and the excavator is practically the only machine that doesn't specify which block(s) to click to form it.  Also, it takes more trial and error than other machines to discover that it works better to build the bucket wheel first despite it being listed second, since the outer part of the excavator blocks access to the block needed for forming the bucket wheel.
5. I didn't ask you to list all modded fluids, just vanilla fluids plus maybe 2 or 3 popular modded fluids (if present).  I looked up lava's temperature in the Forge source code, and I'm guessing that water is the same temperature as I see for creosote in the Assembler.  However, if you know of a mod that allows me to look up fluid temperatures via JEI, that would be an acceptable alternative.

**Comment by charlesbevans** [comment]
How about a thermometer to use on blocks? Maybe measure a machine's rf generation directly with the meter?
