### ISSUE TITLE
Can't craft bullets

### ISSUE THREAD

**Issue by Pihrra** [BluSunrize/ImmersiveEngineering#278]
Hi,

I just tried the new system to craft bullets for my revolver. I tried making amor piercing cartridge and the casull cartridge. After I put the blueprint in the table and put all the ingredients (exactly in the same position given by NEI if that's important) nothing happens. I'm using IE 0.5.1
I haven't had the chance to try other blueprints yet.

**Comment by BluSunrize** [comment]
Fixed with the last commit, just forgot to link this ^^

https://github.com/BluSunrize/ImmersiveEngineering/commit/4795abc3885e8cae4c9e4421ffda2987bf109485
