### ISSUE TITLE
[Suggestion] the size of the boxes 

### ISSUE THREAD

**Issue by seven23** [BluSunrize/ImmersiveEngineering#2780]
Why not add connections for boxes, for example 2-4 or 2-6
![2018-02-13_21 59 39](https://user-images.githubusercontent.com/31816247/36168511-63c3c2b6-110a-11e8-9c1b-1c19802f8bae.png)

**Comment by BluSunrize** [comment]
Because that's unecessary effort for a block that is supposed to be very simple.
