### ISSUE TITLE
[1.12.2] Crusher destroys ores when chunk is unloaded

### ISSUE THREAD

**Issue by LiskoSlayer63** [BluSunrize/ImmersiveEngineering#2782]
If I or someone else on my server uses the Crusher and stays close to it then it works like it should, but if you leave the area so the chunk gets unloaded the Crusher simply destroys every ore, there's no output at all. Seems that it isn't saving the ores that were put in.

**Immersive Engineering version:** 0.12-77
**Forge verson:** 14.23.1.2586
**Minecraft version:** 1.12.2

**Comment by malte0811** [comment]
Did you read what I told you about custom builds on your last issue? That you need to tell us what exactly you are using?
I assume this is a build of your master branch?

**Comment by LiskoSlayer63** [comment]
I tried with your master branch, so this is related to it. I need to specify things more clearly... And seems that this ins't a real issue, the player who reported this was just too quick with things. He assumed that the Crusher keeps working even the chunk is unloaded and when he returned back to it the output was empty. Bur after a little time when he stayed on the chunk the crusher started to output grit. So there really wasn't any issue, just false information from one of my players.
