### ISSUE TITLE
[1.12.2] Excavator rendering crash

### ISSUE THREAD

**Issue by LiskoSlayer63** [BluSunrize/ImmersiveEngineering#2783]
Client crashed when I was just walking near of the Excavator. There's no more information, just this and [the crashlog](https://pastebin.com/T1FMLr7j).

**Immersive Engineering version:** 0.12-77
**Forge verson:** 14.23.1.2586
**Minecraft version:** 1.12.2

**Comment by malte0811** [comment]
Does this happen without Optifine?

**Comment by LiskoSlayer63** [comment]
Can't test it without, OptiFine is forced by the modpack

**Comment by malte0811** [comment]
In that case I won't help you, and neither will @BluSunrize unless he suddenly changed his opinion on Optifine (or his opinion on using custom builds on servers, for that matter).
BTW, Optifine can't legally be distributed as part of a modpack. So I don't think your modpack can force you to use it.

**Comment by LiskoSlayer63** [comment]
Ok, so I don't anymore report any issues related to rendering. And I have a fully custom made launcher which handles all mods, it isn't using any universal modpack.

**Comment by ktole1999** [comment]
optifine is not forced by modpack. it is client only meaning you can remove/disable it.

**Comment by LiskoSlayer63** [comment]
If my launcher detects that there's one mod disabled it force enables it again, so everyone have exactly same version of the client.

**Comment by ktole1999** [comment]
then remove it from server
