### ISSUE TITLE
[1.12.2] [Question] How to remove compat recipes from Crusher?

### ISSUE THREAD

**Issue by KorDum** [BluSunrize/ImmersiveEngineering#2785]
### Description of the issue:
I have ImmersiveEngineering and ThermalExpansion (+Foundation of course). How can I remove recipes?
![image](https://user-images.githubusercontent.com/1331559/36339792-22e64742-13de-11e8-9769-603fffa4d75a.png)

I tryed
```
mods.immersiveengineering.Crusher.removeRecipe(<minecraft:redstone_ore>);
```
but nothing.

### Versions & Modlist
- Forge: 14.23.2.2611
- ImmersiveEngineering: 0.12 - 76
- Crafttweaker: 4.1.3
- Modtweaker: 4.0.7

**Comment by SatyrRex** [comment]
It seems I am also having Crafttweaker related issues. I'm trying to add Redstone to the Lapis Mineral Deposit, and according to the folks on the CT discord, all of my scripts are correct, but still no Redstone in my lapis vein.

Forge: 14.23.2.2611
IE: 0.12-76
CT: 4.1.2
MT: 4.0.6

**Comment by KorDum** [comment]
Oh, my bad:
`mods.immersiveengineering.Crusher.removeRecipe(IItemstack output);`
not input!
