### ISSUE TITLE
[1.12.2] Excavator Bug

### ISSUE THREAD

**Issue by Larky2k** [BluSunrize/ImmersiveEngineering#2786]
List of current mods (look to the right of the page)
http://www.insaneftb.com/

using Forge-14.23.1.2611
ImmersiveEngineering-0.12-76-core.jar,
ImmersiveEngineering-0.12-76.jar
with Java Version: 1.8.0_161
Found a weird bug with the Excavator it will consume more power than it should. Im using the standard way of making BioDiesel. Producing 8192Rf/t to run the Excavator and machines to power it all connected to a battery and the power goes down? 
![2018-02-18_12 49 50](https://user-images.githubusercontent.com/12121248/36352037-6209db74-14aa-11e8-8cfe-386e133206fe.png)
![2018-02-18_12 50 02](https://user-images.githubusercontent.com/12121248/36352038-66192774-14aa-11e8-9300-901e4c4e02e6.png)
![2018-02-18_12 50 09](https://user-images.githubusercontent.com/12121248/36352040-68353c64-14aa-11e8-96fa-96114ee63c7d.png)
![2018-02-18_12 50 11](https://user-images.githubusercontent.com/12121248/36352041-69ed3c5a-14aa-11e8-9be5-612f1f2150ea.png)

**Comment by BluSunrize** [comment]
Please use the issue template and provide pictures of your setup.

**Comment by Larky2k** [comment]
Ok found the issue but its a weird one. Ran all my power though 1 Relay and it worked then it bottlenecked my power then it worked again. Iv added a second relay to take the 2nd Generator and that's sorted out the power.
