### ISSUE TITLE
Suspected IE lag, wish to diagnose further

### ISSUE THREAD

**Issue by ChronosWS** [BluSunrize/ImmersiveEngineering#2788]
I have a small server running 0.12-76 on 1.12.2 in a multiplayer setting.  We've recently started to see significant persistent (not bursty) lag, and I am trying to narrow down the possibilities without altering the world too much.  In particular we are seeing server lag (not FPS lag) whenever someone is at the main base, which is where all of the IE power gen, lighting and machines are.  I believe I have ruled out Lycanites mobs (which was my first suspicion) as the lag didn't used to exist at all even though we had more spawns than we do now.  I also re-evaluated my lighting setup after seeing the other bug report related to improperly wired lighting systems - I now have two separate lighting grids, all sourced from appropriate capacitors, and all machines are on a separate grid. (By separate I mean there is a diesel generator which sends all output to an HV capacitor which then outputs to a) machines and b) an LV capacitor running lighting in the power generation station.  There is also an entirely unconnected network powered by windmills which has no machines attached.)

When I initially corrected the wiring the issue appeared fixed, but the longer I sit at the base, the words it gets (it started reporting at 2000ms lag per 20sec, and now after about 30 minutes it's averaging closer to 5000ms per 20 sec.)  If all players (there are three total) leave the base area such that the chunks need not be loaded, the lag disappears entirely, so we know its due to some effect here.  I've been aggressively building IE infrastructure today and in particular once I started building the fueling infrastructure needed for biodiesel (Cloches, associated refining machines, etc.) the lag became quite noticeable.

Is there any debugging I could enable which could tell me how much time is being spent every second in various parts of IE, to either confirm or deny its contribution?

NOTE: Mods that seem likely to matter most
Lycanites
Scaling Health
Tough As Nails
IE (with Immersive Petroleum, Immersive Tech and Immersive Railroading, though no constructs from those mods have yet been created.)
Storage Drawers
Tinker's Construct

Worst case I might just compile the mod myself and throw some debugging in there, but if there is already something I could enable that would be super cool.

Thanks!

**Comment by malte0811** [comment]
Please download [sampler](http://files.player.to/sampler-1.73.jar) and temporarily install it on your server. Then run `/sampler start`, wait a few minutes and run `/sampler stop` and `/sampler export IELag`. That should create a file called `IELag.nps` in your server directory. Please upload that file to something like dropbox or google drive and post a link here. It will contain better/more accurate profiling info than adding debug printouts would give.

**Comment by ChronosWS** [comment]
Collected about three minutes worth of data while idling at my base.  https://drive.google.com/open?id=1iHuapVaPpUSEPHOgx2k9sZWuCeFeC7bp

**Comment by ChronosWS** [comment]
Actually, if I am reading this correctly, it doesn't look like IE contributes much of anything to the overall time.  Lycanites appears to be spending a ton of time doing something...

**Comment by malte0811** [comment]
Looks like this is caused by lycanites mobs. Their mob ticking took 78340 ms, the worst IE method are connector updates, taking up 963 ms. I may be able to improve that a little bit, but not by much.

**Comment by ChronosWS** [comment]
Yeah, I'll give you a pass on that... for now... :)  Thanks for pointing me in the right direction!
