### ISSUE TITLE
[1.10.2] Wire burning because of energy stored in connectors on way to HV Transformer?

### ISSUE THREAD

**Issue by terribleperson** [BluSunrize/ImmersiveEngineering#2791]
I'm using ImmersiveEngineering-0.10-61 with forge version 12.18.3.2511 for Minecraft 1.10.2
modlist is here https://gist.github.com/terribleperson/6e2761fd283357018f565046b53acbe9

I have 32 thermoelectric generators with two uranium/ice pairs per generator, with LV connectors on the bottom. All 32 LV connectors are hooked to an LV relay in the middle of the setup.  That relay connects to another relay, which connects to another, which I want to then connect to an HV transformer connected to an HV connector on an input side of a capacitor. When I connect the final wire between the last relay and the transformer, the three LV wires up to the first relay burn. The continuous output of all 32 thermoelectric generators is less than the max capacity of an LV wire. I assumed this has to do with the IF stored in the LV Wire Connectors. 

I connected four HV capacitor inputs to the first relay with LV wire and connectors. I tried one, two, and three first, but it took four to get all the connectors to be empty according to WAILA tooltips. At the time there were only 28 connectors, I'd accidentally left four covered up. Then I connected the relay to the other relays to the HV transformer connected to an HV capacitor, and dismantled the four HV capacitors I was using to drain the connectors. The wire stayed intact and didn't burn until the HV capacitor connected to the transformer filled up.

With thermoelectric generators providing continuous output and nothing in the system that should be storing energy, it seems like I shouldn't be burning my wires. If it's because there's energy stored in the connectors, it isn't documented in the manual.

**Comment by BluSunrize** [comment]
1.10.2 is no longer supported.

**Comment by BrianEdmonds** [comment]
> 1.10.2 is no longer supported.

Which is the short way of saying, "If you can replicate this on 1.12.2,
you'll probably get an answer, and if it's (still) a bug it'll probably
be fixed there."
