### ISSUE TITLE
[1.12.2] Wire coil bug

### ISSUE THREAD

**Issue by wwwGeneral** [BluSunrize/ImmersiveEngineering#2792]
Hi, i'm a the administrator of a server which use sponge and your mod in Minecraft 1.12.2 ( the list of the different mods i use is below ).
The bug is that in a certain region of the world ( far away from the spawn ) a weird thing happen with any wire coil which are linked with any wire connector or wire relay.
I don't think this have a link with other mods.
We also use forge 14.23.1.2611 version.

I hope you can help us .
Sorry if i have a bad english ^^

Here is the picture i took of the bug
![2018-02-19_21 50 27](https://user-images.githubusercontent.com/36646472/36397305-870d3aba-15c2-11e8-8fee-cb19abfb6803.png)

List of mods players need to have in the server : 
- animania-1.12.2-1.4.5
- ImmersiveEngineering-0.12-76
- ImmersiveEngineering-0.12-76-core
- Draconic-Evolution-1.12-2.3.9.283-universal
- BiomesOPlenty-1.12.2-7.0.1.2314-universal
- Deadly+Monsters+1.71
- OptiFine_1.12.2_HD_U_C9
- ComputerCraft-SquidDev-CC-ComputerCraft-feature-minecraft-1.12.2-1.80pr0-build20
- fairylights-2.1.2-1.12.x
- ironchest-1.12.2-7.0.39.823
- BrandonsCore-1.12-2.4.0.152-universal
- RoguelikeDungeons-1.12.2-1.8.0
- CodeChickenLib-1.12.2-3.1.5.331-universal
- mutatedmobs-1.0.5
- StorageDrawers-1.12.2-5.3.4
- jei_1.12.2-4.8.5.157
- reptilemod-1.12.2-3.8.4-80
- ColoredWater-1.12.2-b35
- StorageDrawersExtras-1.12-3.1.0
- CarryOn+MC1.12.2+v1.7.2
- JustAFewFish-1.7_for_1.12
- Waddles-1.12.2-0.5.6
- wolfarmor-1.12.2-2.1.0.24-RELEASE
- corail_pillar-4.1.0-1.12
- Chameleon-1.12-4.1.3
- redstonepaste-mc1.12-1.7.5
- CraftStudio-1.0.0.93-mc1.12-alpha
- FoodExpansion1.3.2-1.12
- itorch-1.2.1
- SimpleCorn1.12-2.3.7
- creeperconfetti-1.4.2
- RedstoneFlux-1.12-2.0.1.2-universal
- corail_pillar_extension_biomesoplenty-4.0.1-1.12

**Comment by wwwGeneral** [comment]
Yes, nothing change without Optifine.
The bug don't appear every in the world. If that can help the bug appear for example at this coordinates :   
 X : 21477522   Y : 68   Z: 21473797

**Comment by malte0811** [comment]
Sorry, I missed the point about this happening far away from spawn. That makes sense (floating point rounding errors), I'll have a look to see whether I can fix it without breaking addons again. Why are you even that far out?!

**Comment by wwwGeneral** [comment]
I just don't want players to come to my base ,i know it's a bit excessive ^^

Thank you for helping me !

**Comment by malte0811** [comment]
Be careful out there, I just noticed that the wire raytracer (the code responsible for checking whether a connection is obstructed) can get stuck in an infinite loop for large coordinates in IE 77. I'm pretty sure the wires are not the only things that will have issues out there.
