### ISSUE TITLE
[1.12.2] Engineer Manual Crash

### ISSUE THREAD

**Issue by megamanzteam** [BluSunrize/ImmersiveEngineering#2794]
### Description of the issue:
When reading the manual Game crashes to desktop. This can happen if I read a page with a model displayed or not. I can either get about a minute to a second before the game crashes. This is on the Foregoing modpack by Themerlinglib. IE version ImmersiveEngineering-0.12-76.

I know this is most likely related to issue #2761, but it seemed to have detracted from the original post by focusing on connected textures. If you require additional info, please let me know.

### Crashlog:
https://gist.github.com/megamanzteam/5e24c467077b674fe9af7743b10ad9f6

### Versions & Modlist
Forge 14.23.1.2590
ImmersiveEngineering-0.12-76

**Comment by BluSunrize** [comment]
There is a plethora of closed issues discussing this, please use the search funtion and update your Java.

**Comment by mindforger** [comment]
>update your Java

to latest java8 not 9 and configure it in your launcher
