### ISSUE TITLE
[1.12] Vertically-aligned connectors unusable with wiring changes

### ISSUE THREAD

**Issue by MauveCloud** [BluSunrize/ImmersiveEngineering#2795]
### Description of the issue:
After updating to 0.12-77, connectors facing down (on the underside of a block) are no longer usable - I get "the connection is obstructed" even when the other connector is directly below with no other blocks near enough to get in the way.  Screenshot of the setup I tried below.

Edit: further experimentation reveals this is not so much "down-facing connectors" as "vertically-aligned" connectors. (i.e. with the same x and z coordinates, but different y coordinates)

### Versions & Modlist
forge-1.12.2-14.23.2.2611-universal.jar
jei_1.12.2-4.8.5.151.jar
ImmersiveEngineering-0.12-77.jar
InventoryTweaks-1.63.jar
MouseTweaks-2.8-mc1.12.1.jar

### Screenshot
![2018-02-19_17 14 44](https://user-images.githubusercontent.com/8942955/36403432-b629159a-1599-11e8-8f40-e5d4ee03ba67.png)

**Comment by malte0811** [comment]
It's weird. This bug makes sense, because I don't really handle vertical connections. But I can't replicate it at all...

**Comment by Voxel-Friend** [comment]
I can confirm this issue as well with 0.12-77
