### ISSUE TITLE
Multiblock destruction problem in bottling machine

### ISSUE THREAD

**Issue by Weisstrieb** [BluSunrize/ImmersiveEngineering#2796]
### Description of the issue:
 In multiblock structure of the bottling machine, fluid pump is not fully destroyed when the part of pump in bottling machine is broken.
and each part of pump block gives one fluid pump. dupe :(

### Screenshots
![2018-02-20_13_26_18](https://user-images.githubusercontent.com/16723572/36407749-d3ffb3c6-15f8-11e8-8609-08259bcb3dfc.png)
![2018-02-20_13_26_24](https://user-images.githubusercontent.com/16723572/36407752-d954758c-15f8-11e8-8f21-57e5a91d32ca.png)

### Associated Versions & Modlist
 - Forge 14.23.2.2618
 - Immersive Engineering 0.12-77

**Comment by mindforger** [comment]
optifine installed by chance?
spigot or sponge server used?
did you try other tools to break the blocks? (maybe caused by the pick in use)

**Comment by malte0811** [comment]
I don't think so, this looks like it could happen with the current multiblock code. It isn't really designed to have blocks with dummy-blocks in it.

**Comment by Estiv** [comment]
Optifine is not installed and current server is running on forge modded server, neither spigot nor sponge used.
