### ISSUE TITLE
Low FPS while Mining Drill is in inventory.

### ISSUE THREAD

**Issue by wBakunis** [BluSunrize/ImmersiveEngineering#2799]
Very low FPS while Mining Drill is in inventory. Usually get an average of 40 fps but while drill is in inventory, I get half that. 

**Mods:**
- FTB Revelations 1.5.0
- Immersive Engineering 0.12-77
- Alternating Flux (IE Addon) 0.12-3
- Industrial Wires (IE Addon) 1.6-25

![2018-02-20_12 54 37](https://user-images.githubusercontent.com/3248262/36440295-693c994c-163d-11e8-9120-2eed8d1f3a4b.png)
![2018-02-20_12 54 27](https://user-images.githubusercontent.com/3248262/36440293-6927c21a-163d-11e8-91b0-6fda4757a22a.png)

**Comment by malte0811** [comment]
That's probably because of the drill's animation. Does disabling `fancyItemAnimations` in the IE config fix this? I see you are using Optifine, does it happen without Optifine? OF doesn't work well with the animations, I'll have to look into that at some point.

**Comment by wBakunis** [comment]
I tried a couple things. I removed optifine and held the drill. Still had low FPS so I disabled `fancyItemAnimations` which help gain a couple fps. I re-added optifine. I'm back to an average of 40fps. Disabling animation definitely helps for now. 

**Looking straight up with drill is average 80fps.**
![2018-02-20_13 51 14](https://user-images.githubusercontent.com/3248262/36442992-86831db6-1645-11e8-9eb4-721c4b59da5d.png)
**Looking straight up with drill in inventory but not holding is average 120fps**
![2018-02-20_13 53 03](https://user-images.githubusercontent.com/3248262/36443040-a9435ffa-1645-11e8-885d-005d67a8ca1c.png)
**Looking straight up without drill in inventory is average 150fps**
![2018-02-20_13 52 20](https://user-images.githubusercontent.com/3248262/36443072-be52bd3c-1645-11e8-93db-65eaf7011841.png)

**Comment by BluSunrize** [comment]
Not a lot to be done about this, that's basically why those config options exist.
