### ISSUE TITLE
Wood renders weiredly

### ISSUE THREAD

**Issue by TheJulianJES** [BluSunrize/ImmersiveEngineering#28]
http://gyazo.com/9e129093a262f7c8971b426272c7f0c1
I think the method was renderAsNormalBlock -> true but it is false :)

**Comment by dmb1881** [comment]
Its not the wood, its the water animation, you just see that. It is a bug all in all though.

**Comment by TheJulianJES** [comment]
No, niemals Blocks render fine

**Comment by TheJulianJES** [comment]
normal*
