### ISSUE TITLE
Can place wire connectors on air

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#280]
Issue: Upon placing any type of wire connector on grass, it floats in air
================
![image](https://cloud.githubusercontent.com/assets/3110986/9092242/c9717196-3b59-11e5-8e35-5c9a2e8a81f1.png)
![image](https://cloud.githubusercontent.com/assets/3110986/9092333/749d34b0-3b5a-11e5-8757-a1b3decc0cb6.png)

Info:
-------------------
The Wire connector functions correctly but floats in the air without support.

Expected behavior:
------------------
Wire connector would fall off, as it is unsupported

Actual behavior:
-----------
Wire connector hovers in the air, acting as if it was supported by a block

Steps to reproduce:
------------------
[1] place wire connector on vanilla tall grass at an shallow angle

Version data:
===========
IE version 0.5.1 SHA 4074c1d586ec31809ca18349acc68eb2e0ac216a
FTB Infinity (1.9.0) no other modifications

**Comment by BluSunrize** [comment]
The thing about this one is: There are so many blocks that don't set their sides to solid, so checking for that severely limits IE's connectors in there placement. That's why it only checks that there is a block it's attached to, not if it actually makes sense to attach there.

**Comment by theunkn0wn1** [comment]
But by placing the connector at an angle onto a grass block, it replaces the grass block and does no further checks to verify it is attached to a block without a block update occurring.
This bug can be avoided(?) by checking to see if the connector is still attached to a block directly after placement.

**Comment by BluSunrize** [comment]
Interesting. I'd expect it to check that anyway, since the chunk was modified. Guess the on neighbouring happens before placement is finalized...

**Comment by theunkn0wn1** [comment]
It appears to do that check directly on placement, and on block update. from my understanding of how this follows:
[1] item right-clicked, triggers pre-placement checks
[2] pre-placement returns OK, goes a head with validating the block's placement using the opposite forge direction from the users cursor, checking for a blocks presence, grass is there thus returning true.
[3]Block is placed,grass is overridden, block update occurs
[4]Block placement completes, no further checks
[5] local event(block placed directly next to issue connector) triggers block update, connector falls off
