### ISSUE TITLE
[1.12.2] Connection obstructed logic problem 

### ISSUE THREAD

**Issue by wwwGeneral** [BluSunrize/ImmersiveEngineering#2800]
I don't know if it is a real problem but i notice that when i put a block between a wire the wire don't destroy itself ( in normal coordinates ).

Thanks for reading it !

![2018-02-20_12 10 51](https://user-images.githubusercontent.com/36646472/36445115-8e56cbcc-167d-11e8-9568-c069c235c686.png)

List of mods players need to have in the server :

forge 14.23.1.2611

- animania-1.12.2-1.4.5
- ImmersiveEngineering-0.12-76
- ImmersiveEngineering-0.12-76-core
- Draconic-Evolution-1.12-2.3.9.283-universal
- BiomesOPlenty-1.12.2-7.0.1.2314-universal
- Deadly+Monsters+1.71
- OptiFine_1.12.2_HD_U_C9
- ComputerCraft-SquidDev-CC-ComputerCraft-feature-minecraft-1.12.2-1.80pr0-build20
- fairylights-2.1.2-1.12.x
- ironchest-1.12.2-7.0.39.823
- BrandonsCore-1.12-2.4.0.152-universal
- RoguelikeDungeons-1.12.2-1.8.0
- CodeChickenLib-1.12.2-3.1.5.331-universal
- mutatedmobs-1.0.5
- StorageDrawers-1.12.2-5.3.4
- jei_1.12.2-4.8.5.157
- reptilemod-1.12.2-3.8.4-80
- ColoredWater-1.12.2-b35
- StorageDrawersExtras-1.12-3.1.0
- CarryOn+MC1.12.2+v1.7.2
- JustAFewFish-1.7_for_1.12
- Waddles-1.12.2-0.5.6
- wolfarmor-1.12.2-2.1.0.24-RELEASE
- corail_pillar-4.1.0-1.12
- Chameleon-1.12-4.1.3
- redstonepaste-mc1.12-1.7.5
- CraftStudio-1.0.0.93-mc1.12-alpha
- FoodExpansion1.3.2-1.12
- itorch-1.2.1
- SimpleCorn1.12-2.3.7
- creeperconfetti-1.4.2
- RedstoneFlux-1.12-2.0.1.2-universal
- corail_pillar_extension_biomesoplenty-4.0.1-1.12

**Comment by malte0811** [comment]
You are using IE 76, the wire breaking and the other new features were added in IE 77. So it obviously can't work in your version.
