### ISSUE TITLE
[1.12.2; CraftTweaker compat.] Mixer CraftTweaker recipes always transform liquids in 1:1 I/O ratio using output quantity, ignoring fluid input quantity

### ISSUE THREAD

**Issue by nihiltres** [BluSunrize/ImmersiveEngineering#2802]
### Description of the issue:
The mixer recipe support for CraftTweaker ignores input quantities defined in the CraftTweaker recipe defined in a script. Specifically, here's what I originally tried:

```
mods.immersiveengineering.Mixer.addRecipe(
    <liquid:lava> * 3000,
    <liquid:lava> * 1000,
    [<minecraft:magma>, <ore:blockCoal>] as IIngredient[],
    2000
);
```

Specifically, I was trying to allow the Mixer to produce 3000mB Lava using 1000mB Lava, 1 Magma block, and 1 Coal block (because generating lava is Fun™). To confirm the issue, I set up a minimal instance of Minecraft, with a creative world where I built a Mixer, input 4000mB of Lava, 1 Magma block, and 1 Coal block. The recipe operates, it shows up correctly in JEI (including the quantities *as defined*), but despite the blocks being consumed, the quantity of lava in the Mixer remains constant.

I investigated further by setting the output to 3000mB Water, reloading Minecraft completely, and trying again: in this case the Mixer produces 3000mB Water while consuming the blocks, but consumes 3000mB Lava to do so. That suggests the lava was being consumed and produced in a 1:1 ratio in the first test. Here's what I used for the second test:

```
mods.immersiveengineering.Mixer.addRecipe(
    <liquid:water> * 3000,
    <liquid:lava> * 1000,
    [<minecraft:magma>, <ore:blockCoal>] as IIngredient[],
    2000
);
```

This isn't normally an issue, because all of IE's default Mixer recipes (liquid concrete, potions) use 1:1 fluid ratios. That said, the expectation I have is that the Mixer should either a) respect input and output ratios or b) explicitly enforce a 1:1 input:output ratio and use a clearer CraftTweaker recipe format, e.g. by using `ILiquidDefinition`s instead of `ILiquidStack`s. Moreover, the JEI integration should reflect the recipe as it functions in practice. I'd obviously prefer (a), since it'll let me do what I originally wanted to do, but (b) would at least be consistent and is probably easier to implement.

Thanks for putting so much work into Immersive Engineering; it's a lot of fun.

### Versions & Modlist used to reproduce issue:
Confirmed in a *reasonably* minimal instance:
* Forge 14.23.2608
* Immersive Engineering 0.12-77

...Plus, a handful of mods that probably shouldn't interfere or are necessary for the issue:
* CraftTweaker2-1.12-4.1.0
* CTM-MC1.12-0.2.3.12
* JEI 1.12.2-4.8.5.138
* JEI Integration 1.12.2-1.5.1.36
* ModTweaker 4.0.6
* MTLib 3.0.1

**Comment by BluSunrize** [comment]
That's somewhat intentional. Mixer recipes are designed to be 1:1 in terms of fluids, I just never made the Crafttweaker integration enforce that. So while the recipe is registered to output more (and JEI shows that), the internals of the mixer only support a 1 to 1 conversion.
