### ISSUE TITLE
[1.12] [0.12-77] Blast Furnace consumes fuel without making progress

### ISSUE THREAD

**Issue by MauveCloud** [BluSunrize/ImmersiveEngineering#2803]
### Description of the issue:
In 0.12-76, the Blast Furnace used a hair over 1 coal coke per steel (1.0008333333333332 according to Malte0811), but in 0.12-77 it is more like _infinite_ coal coke per steel - with iron in the top slot, the coal coke (or charcoal) gets used up, but the progress arrow never budges, the outputs remain stubbornly empty, and the input iron stays at the same count, even after 20 coal coke has been used up.

### Versions & Modlist
Forge v14.23.2.2611
Immersive Engineering 0.12-77

**Comment by HanboyCN** [comment]
yeah,I also found this bug

**Comment by MauveCloud** [comment]
I did some experimentation with local test builds of IE, and narrowed it down to https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/blocks/stone/TileEntityBlastFurnace.java#L161 - if I revert that line to what it was before, the Blast Furnace functions as before (including using slightly more than 1 coal coke per steel 😠 ), but I cannot make sense of why that change would cause this effect.

**Comment by malte0811** [comment]
I think I know why this happens, and it's a stupid reason: Can you try replacing `=process` with `=recipe.time` one line below the one you linked? That should fix it. The blast furnace sees that the max process is not the one specified in the recipe, assumes that the recipe changed and resets every tick.

**Comment by MauveCloud** [comment]
Ah, the line 118 comparison.  I hadn't thought of that.  Standy by while I test your suggested change.

**Comment by MauveCloud** [comment]
Success!
