### ISSUE TITLE
Issue with "Warning" message in chat.

### ISSUE THREAD

**Issue by OCDiary** [BluSunrize/ImmersiveEngineering#2806]
I am using the following:

**Immersive Engineering**: 0.12-77
**Forge**: 14.23.2.2618
**Java**: 1.8.0_162 (64-bit)
**Compact Machines**: 1.12.2-3.0.7-b197

Immersive engineering keeps giving me a warning message everytime I change dimensions with Compact Machines. The message is:

> [CHAT] [Immersive Engineering] ǴWarning: ȲYour Java version is 1.8.0_25. This version causes crashes with the Engineer's manual. These crashes are close to impossible to fix for us. You can prevent the crashes by installing up-to-date Java (make sure to use Java 8, not Java 9) and forcing your launcher to use it.

I have made doubly and triply sure that Twitch Launcher is set to use Java 1.8.0_162 and it still states the message everytime I change dimensions. 

Thanks
OC

**Comment by malte0811** [comment]
What version does MC show in the debug screen (top right I believe)?

**Comment by CJBok** [comment]
If the Launch Method is set to Native Launcher (Check Twitch Settings) you have to make sure that in the Minecraft Launcher under Launch options the option "Java executable" is enabled. Else it will by default point to a java version which is bundled with the Minecraft installation, which in this case is version 1.8.0_25.

![image](https://user-images.githubusercontent.com/3213428/36496641-31a61038-1739-11e8-9ba3-7ddec891ea8d.png)

**Comment by Sharkske** [comment]
LMAO i guess its java fault u cant fix it LOL gg
