### ISSUE TITLE
[1.12-77] Crashed When Running With ImmersiveTech

### ISSUE THREAD

**Issue by kevin60667** [BluSunrize/ImmersiveEngineering#2807]
### Description of the issue:
I put ImmersiveEngineering and ImmersiveTech in "mods" folder.
When Minecraft is running,it crashes.

### Crashlog:
[https://pastebin.com/hVfqFtfF](https://pastebin.com/hVfqFtfF)

### Versions & Modlist
forge-1.12.2-14.23.1.2556
ImmersiveEngineering-0.12-77
immersivetech-1.12-1.3.4

**Comment by malte0811** [comment]
FerroO2000/Immersive-Tech#40
