### ISSUE TITLE
Redstone input and the Arc Furnace

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#281]
Issue: applying a redstone input to the arc furnace causes the addition/removal of Graphite electrodes does not change as expected
================== 
Info:
-----------------
When the Arc Furnace is receiving a redstone signal, the MB does not correctly render the addition/removal of Graphite Electrodes.

Action:
-------------------
Adding/removing Graphite Electrodes from functional Arc Furnace

Expected result:
---------------------
The world render of the Arc Furnace would correctly update the additon/removal of Graphite Electrodes

Actual result:
----------------
the world Render of the Arc Furnace does not update until the RS signal is removed

Steps to reproduce:
----------------------

[1] successfully build and activate the Arc Furnace MB
[2] apply redstone signal to designated RS port
[3] add/remove Graphite Electrodes

Picture of issue:
----------------
![image](https://cloud.githubusercontent.com/assets/3110986/9095596/f86d96f6-3b6c-11e5-8f67-0184c19a181c.png)

Version data:
---------------------------
IE version 0.5.1 SHA 4795abc3885e8cae4c9e4421ffda2987bf109485
-------------
FTB Horizons (1.9.0) no modifications other than IE

**Comment by theunkn0wn1** [comment]
@BluSunrize Issue still exists.....
===================
Version data:
----------------
IE Version 0.5.2 ebafdeb4a33abbda8b5a673e9277d3c3d81d04bb
===================================

**Comment by Kubuxu** [comment]
@theunkn0wn1 can you stop using big font. I feel like you think we are partially blind.

**Comment by theunkn0wn1** [comment]
Sorry.. still experimenting with separators, It is clear i was using them way to much in that above message....

**Comment by BluSunrize** [comment]
here we go, https://github.com/BluSunrize/ImmersiveEngineering/commit/cafb03f91b16e17b8e59ca62a9abbc3c634d1ae6 shoudl fix this =3

**Comment by theunkn0wn1** [comment]
Yep, this appears to have fixed it. :3
