### ISSUE TITLE
[1.12] Feature Request: wire connection visualization with obstructed sections highlighted

### ISSUE THREAD

**Issue by MauveCloud** [BluSunrize/ImmersiveEngineering#2810]
### Description of the issue:
Sometimes I get "the connection is obstructed" even though it looks like it shouldn't be - see screenshot below.  The wires are connected now, but when I had those Thermoelectric Generators one block to the left, the leftmost one wouldn't connect to the relay.  I am guessing that it was going by original block boundaries before the refinery was formed into a multiblock, but with the multiblock formed, it looks like the wire coil should have been able to connect.

I'm not sure how difficult this would be to code, but I'd like a way to get some sort of "phantom" connection, preferably with the sections considered obstructed highlighted (which would be visible if going through transparent blocks like glass or the effectively-air parts of a multiblock)

### Versions & Modlist
Forge 14.23.2.2611
Autofish_0.7.4_mc1.12.2
Immersive Engineering 0.12-77.1 (local build with one tiny change for the blast furnace issue)
InventoryTweaks-1.63
jei_1.12.2-4.8.5.151
MouseTweaks-2.8-mc1.12.1
OptiFine_1.12.2_HD_U_C9

### Screenshot
![2018-02-21_16 49 33](https://user-images.githubusercontent.com/8942955/36514207-3b3c24b8-1728-11e8-9286-f3a7cc03c028.png)

**Comment by malte0811** [comment]
![2018-02-23_21 24 33](https://user-images.githubusercontent.com/10406104/36615324-14e59a92-18e0-11e8-906e-9d28faa42d0f.png)
I implemented this, I'll push it to master once  #2805 is merged. It will only show one of the obstructing blocks (the raytracer stops when it hits one), and it won't necessarily show the first one along the wire, but that should be enough to figure out why it isn't working.
