### ISSUE TITLE
Sneak-right click can't pick up toolbox when shield is equipped

### ISSUE THREAD

**Issue by ChronosWS** [BluSunrize/ImmersiveEngineering#2811]
Version 0.12-76.

Sneak-right click will put down a toolbox when a shield is equipped, but cannot pick it back up.  Unequip the shield and it works fine.  Dedicated server if it matters.

**Comment by lgthibault** [comment]
Issue is not specific to shield. Toolbox also will stay on the ground if player has torch or sword in hand.

Reading the code suggests toolbox can only be picked up if hands are empty.
