### ISSUE TITLE
[1.12] [0.12-77] Excavator no longer clears area under it

### ISSUE THREAD

**Issue by MauveCloud** [BluSunrize/ImmersiveEngineering#2812]
### Description of the issue:
I started up an excavator with the wheel partially buried, figuring it would break and collect some dirt/grass and stone blocks before outputting ore blocks, but instead it started immediately with the ore blocks, and the bucket wheel kind of phases through the grass blocks as seen in the screenshot below.

### Versions & Modlist
Forge 14.23.2.2611
Autofish_0.7.4_mc1.12.2
Immersive Engineering 0.12-77.1 (local build with one tiny change for the blast furnace issue)
InventoryTweaks-1.63
jei_1.12.2-4.8.5.151
MouseTweaks-2.8-mc1.12.1
OptiFine_1.12.2_HD_U_C9

Edit: I confirmed this also happens with just the official 0.12-77 build from CurseForge, powering the excavator with a creative capacitor (since setting up a diesel engine etc. would take a while even in creative mode)

### Screenshot
![Imgur](https://i.imgur.com/Iyo3AeP.png)

**Comment by BluSunrize** [comment]
The machine is not designed to be built in the ground, it only digs the area *below* it, not the stuff your buried it in.

**Comment by MauveCloud** [comment]
> The machine is not designed to be built in the ground, it only digs the area below it, not the stuff your buried it in.

You mean it's designed to _hover in midair_, like this?
![2018-02-22_08 10 49](https://user-images.githubusercontent.com/8942955/36549607-0a01681a-17a8-11e8-9bce-07f26af74a41.png)

Also, I'm a little confused regarding which in-world blocks it will break - it seems that blocks with green or yellow backgrounds in the "Hand" column at https://minecraft.gamepedia.com/Breaking#Blocks_by_hardness are broken and collected as if with silk touch (except for tile entities like chests, which drop as items in place all at once), fluids are just eliminated, but blocks with a red background in the "Hand" column are left in place, even in those 11 positions below the excavator - it seems to me that the excavator should still break things like stone, sandstone, etc. in those positions (though maybe not collect them) and refuse to run if there's something like bedrock, end portal, etc. in those positions.
