### ISSUE TITLE
[1.12.2] Cannot form metal press

### ISSUE THREAD

**Issue by paultey** [BluSunrize/ImmersiveEngineering#2813]
when I try put connector on my Garden Cloche, keep open GUI for me to put dirt & seed. I tried top & bottom left & right all same. Please tell me why I will facing this issue. Thank you.

**Comment by BluSunrize** [comment]
Try sneaking.

**Comment by paultey** [comment]
Thanks. It is work. But now I facing issue on metal press, I put block as
show in engineer's manual then no matter I left click or right click piston
with engineer's hammer. It just change direction of piston. Never change
become metal press.

2018年2月22日 18:01，"BluSunrize" <notifications@github.com>写道：

**Comment by paultey** [comment]
Try sneaking on left click or right click piston also same

2018年2月25日 16:44，"Paul Tey" <paultey@gmail.com>写道：

**Comment by BluSunrize** [comment]
Chances are, you built it wrong. Please supply pictures.

**Comment by paultey** [comment]
2018年2月25日 20:33，"BluSunrize" <notifications@github.com>写道：

**Comment by paultey** [comment]
do I built it wrong?

Sincerely,

---
Paul Tey

2018-02-26 18:11 GMT+08:00 Paul Tey <paultey@gmail.com>:

**Comment by BluSunrize** [comment]
I can't *tell* you unless you provide pictures.

**Comment by paultey** [comment]
Here the picture, do I built it wrong?

Sincerely,

---
Paul Tey

2018-03-11 17:19 GMT+08:00 BluSunrize <notifications@github.com>:

**Comment by BluSunrize** [comment]
Paul, I don't quite know what you are doing but you're NOT providing pictures.
I presume you are trying to append them to your emails. That DOESN'T WORK. Upload them to imgur.com or similar and give us a link.

**Comment by BluSunrize** [comment]
Additionally, please make sure that you are running the latest version of IE and that you are using normal conveyor belts, not the redstone-ignoring ones.

**Comment by paultey** [comment]
thank you for reply. the problem solved as I do not using normal conveyor
belts because my normal conveyor belts icon is pink color so that make me
use another conveyor belts

Sincerely,

---
Paul Tey

2018-03-17 20:58 GMT+08:00 BluSunrize <notifications@github.com>:
