### ISSUE TITLE
[0.12-77] - wires don't reconnect until connectors are replaced

### ISSUE THREAD

**Issue by ChronosWS** [BluSunrize/ImmersiveEngineering#2814]
Moving from 0.12-76 to 0.12-77, many places in the world needed to be rewired.  There were two causes:
1) After booting the world, shutting it down and rebooting it, many wires were no longer connected.  Only happened on first reboot of the server after upgrading.
2) Upon attempting to reattach wires, I kept getting the message "cannot attach wire here", until I removed and replace the connector.  Also occurred with the HV transformer (haven't tested other transformer).  Does not affect relays

**Comment by malte0811** [comment]
I have no idea why this would happen. What other mods do you use/have installed? Were there any errors in the logs when you first started the world after the update?

**Comment by ghostshadow** [comment]
Observed this as well in 0.12-80.
Error reported:
https://pastebin.com/fQ4f4WvM

**Comment by ljfa-ag** [comment]
Bumping this because I just ran into that as well, in version 0.12-82. I can't tell you about any errors in the log since I only noticed this a few days after updating the pack.

I can't attach Steel Cables to old Structural Cable Connectors until I replace them. I don't think that I noticed vanishing wires at any point, but I might be wrong. Seems like this only affects Structural Cable Connectors for me, I was able to attach HV or MV wires to relays just fine.

It's problematic for me since I have long stretches of overhead wires over rails, I certainly don't want to replace everything.

**Comment by ljfa-ag** [comment]
I noticed that the connectors already become "corrupted" when simply leaving and reloading the world. There must be some issue with writing or reading NBT data.

**Comment by ljfa-ag** [comment]
Actually I tried it without other mods and it worked properly. But it broke when I added Immersive Tech. Something from there must be interfering.

Reported at FerroO2000/Immersive-Tech#67.

**Comment by Euphemios** [comment]
Same thing happened to me, sevtech mod pack, I could fix it by using engineers wirecutters on the connector and reconnecting everything

**Comment by duncanwebb** [comment]
I'm having this problem too and it also happens with LV and HV connectors. This happens after saving and reloading the same game without quitting Minecraft.

![cannot-attach-wire](https://user-images.githubusercontent.com/4198031/50238439-b7468600-03bf-11e9-8158-12b9ff98bce6.png)

Any ideas as a single change means replacing most of the cables?

ImmersiveEngineering-0.12-86
immersivepetroleum-1.12.2-1.1.9
immersivetech-1.12-1.3.10
IndustrialWires-1.7-33
forge-1.12.2-14.23.5.2768-universal

**Comment by duncanwebb** [comment]
In the pack I’m playing it has pollutions of the realm, that causes a block of emissions to float up, if it hits a cable the cable is knocked off and dropped on the floor, the carbon emissions cause plants and grass to grow, tall grass can also knock off cables. This means that the cables need to reattached from time to time in different gaming sessions and so this “cannot attach wire here” is seen more often.

**Comment by duncanwebb** [comment]
I should have read the whole report as the google drive version in the ljfa-ag's report at https://github.com/FerroO2000/Immersive-Tech/issues/67 fixed this and the industrial wires controller stopping to work after a reload.
