### ISSUE TITLE
【1.7.10】Arc Furnace melting product error

### ISSUE THREAD

**Issue by Heiofen** [BluSunrize/ImmersiveEngineering#2819]
Electric arc furnace smelting Structural Arm can get more products than Structural Arm synthetic materials
as the picture shows
**![image](http://bbs.mcmod.cn/data/attachment/album/201802/24/142617mzx0jydayy8joj0u.png)**
That should be 1.875  **![image](http://bbs.mcmod.cn/data/attachment/album/201802/24/143106flttlnt9lph9zln9.png)**

**Comment by malte0811** [comment]
1.7 is no longer supported. The last release was nearly 2 years ago.
