### ISSUE TITLE
[1.12-77] Blast furnace consumes fuel without making steel.

### ISSUE THREAD

**Issue by Flanks255** [BluSunrize/ImmersiveEngineering#2821]
In IE 77, in MC 1.12.2 with fore 14.23.2.2611
The blast furnace consumes fuel, without actually producing steel.
tried with multiple versions of forge, and a test pack with only IE
IE 76 works, IE 77 does not.

**Comment by malte0811** [comment]
Duplicate of #2803. Fixed for build 78.
