### ISSUE TITLE
[Feature Request]Water Wheel support for other fluids

### ISSUE THREAD

**Issue by charlesbevans** [BluSunrize/ImmersiveEngineering#2824]
Water wheels turned by blood, or by energized glowstone flowing upward. These are the things I keep wishing I could do. Maybe a slower turn for oozing slime. Fire resistant wheels turned by lava.... Anyway, just thought I'd throw that out there. Thanks for the fun mod.

**Comment by BluSunrize** [comment]
You should probably try things first before you suggest them.

**Comment by charlesbevans** [comment]
You are absolutely right. I apologize. I've seen other mods have inconsistent handling of fluids, and I recalled how you added crops to the cloche by hand rather than autogenerating them, and it led me to assume you hardcoded water. I will go play with gratitude. Thank you.
