### ISSUE TITLE
How to convert IF to RF?

### ISSUE THREAD

**Issue by Chimparzan** [BluSunrize/ImmersiveEngineering#2826]
I know, that this question is stupid and it is not a bug, but how to convert IF to RF? If im playing with IC2
Version of minecraft is 1.10.2

**Comment by malte0811** [comment]
It should work just the same, IF is compatible with FE/RF.

**Comment by MauveCloud** [comment]
Why do you want to convert to RF if you're using IC2 though?  IC2 uses EU, not RF.

**Comment by Chimparzan** [comment]
Sorry, how to convert IF toEU?

**Comment by malte0811** [comment]
Not at all with IE itself. I have an addon ([Industrial Wires](https://minecraft.curseforge.com/projects/industrial-wires)) that adds wires that transmit EU and lossy low-power converters, I am working on better converters. Using it isn't as trivial as IE's conversion in 1.7, but should still be easy.

**Comment by BluSunrize** [comment]
Internal conversion was removed after 1.7 because it was poorly implemented and a liability in balance. It's not coming back to core IE.
