### ISSUE TITLE
[Crash in v1.12.2 for ver.77]Crashes when it's loading the game.

### ISSUE THREAD

**Issue by Lazy-Rabbit-2001** [BluSunrize/ImmersiveEngineering#2827]
Crash Report Here:
https://github.com/Lazy-Rabbit-2001/Logs/issues/1

**Comment by malte0811** [comment]
What makes you think this is an IE crash? It looks more like IC2 to me. What other mods besides IE and Industrial Wires did you update before this crash happened?

**Comment by BluSunrize** [comment]
Nothing in there implicates IE, issue closed :V
