### ISSUE TITLE
Can't craft graphite eletrode

### ISSUE THREAD

**Issue by Auzze** [BluSunrize/ImmersiveEngineering#283]
Hi,

I made the workbench, crafted the HOP graphite ingots, searched for hours looking for the blueprint, add the blueprint to the workbench, added 4 ingots and nothing, I can't seam to craft them

Using 0.51 on my modpak/server

**Comment by theunkn0wn1** [comment]
can you please provide a picture of the workbench in the configuration that induces this issue please?
I am unable to reproduce this issue.

Steps taken to reproduce:
------------------------
[1]spawn the blueprint in question via NEI
[2] placed blueprint in workbench with 4 graphite ingots (the IE variant)
[3] attemtp to pull Electrodes out of the workbenches output 

result:Successful, no bug encountered
=================

are you sure you are using IE's graphite ingots and not another mods?  (such as Big Reactors)
Snips:
----------------
![image](https://cloud.githubusercontent.com/assets/3110986/9104786/39f609fc-3bc5-11e5-9fe6-d2adfcc8f411.png)
The above was with BigReactor's graphite ingots
![image](https://cloud.githubusercontent.com/assets/3110986/9104792/4c16282e-3bc5-11e5-9ccc-23c067ba8956.png)
and this one was with the GOP graphite ingots from IE

Version data:
========================
IE version 0.5.1 built against SHA: 2e3bd1930add6eb6e1da285732d7e610c7014e177
--------------------
FTB infinity (1.9.0) no modifications
-------------------------------

**Comment by Auzze** [comment]
Hi,

Yes using IE's graphite ingots, I don't have any mod using graphite ingots. (no Big Reactors)

![workbench](https://cloud.githubusercontent.com/assets/478323/9105185/aacc13d6-3c58-11e5-964c-74fc65cfaed2.png)

**Comment by BluSunrize** [comment]
Known issue, fixed already

**Comment by BluSunrize** [comment]
Oh, also, Big Reactors graphite and IE graphite are incompatible, because BR is WAY too cheap.
