### ISSUE TITLE
[1.12] Feedthrough Insulators do not transmit power when connectors are in a vertical orientation

### ISSUE THREAD

**Issue by Captainaviator** [BluSunrize/ImmersiveEngineering#2830]
Connecting wires vertically is now working, but Feedthrough Insulators are not passing power through, when the connectors are attached to the top and bottom of the block

**Comment by malte0811** [comment]
There is a bug when connecting the wires, but passing power should work perfectly fine once the wires are connected.
Are you using IE 77 or 78?
Did you connect the wire coil to one side before you formed the feedthrough multiblock?

**Comment by Captainaviator** [comment]
I got it working, thank you.  This issue can be closed.  The manual instructions weren't clear on how this forms into a multi-block structure.  I thought just placing the individual blocks were enough, but upon forming it with the engineers hammer, all becomes clear.
