### ISSUE TITLE
Sound does not exist

### ISSUE THREAD

**Issue by bookerthegeek** [BluSunrize/ImmersiveEngineering#2832]
### Description of the issue:
```
[main/WARN]: File immersiveengineering:sounds/revolver_fire_thump.ogg does not exist, cannot add it to event immersiveengineering:revolverfirethump
```
### Crashlog:
No crash

### Versions & Modlist
-  Minecraft 12.2
-  Forge 14.23.2.2618
-  Immersive Engineering 0.12-78

### Also
Thank you for the mod, and pardon for the sparse report.

**Comment by PhoenixRiver** [comment]
Confirmation of this report:

[main/WARN]: File immersiveengineering:sounds/revolver_fire_thump.ogg does not exist, cannot add it to event immersiveengineering:revolverfirethump

Versions & Modlist
Minecraft 1.12.2
Forge 14.23.2.2611
Immersive Engineering 0.12-78

**Comment by bookerthegeek** [comment]
@PhoenixRiver Update your forge

**Comment by PhoenixRiver** [comment]
Updated to the bleeding-edge (14.23.2.2624) rather than the recommended version of Forge... the error is still there:

`[main/WARN]: File immersiveengineering:sounds/revolver_fire_thump.ogg does not exist, cannot add it to event immersiveengineering:revolverfirethump`

Am reverting to the recommended version of Forge incase the bleeding edge breaks something else.

**Comment by MauveCloud** [comment]
@bookerthegeek please try looking in the actual jar file before jumping to conclusions about the Forge version mattering - 0.12-76 and 0.12-77 have the mentioned file there in assets/immersiveengineering/sounds, but 0.12-78 does not.  Looking in the code tab here on GitHub, I'm having trouble confirming that the file was ever actually committed.  I found the commit that added the event, and it doesn't include the addition of the sound file: https://github.com/BluSunrize/ImmersiveEngineering/commit/cf176732aa1be696119e3b91c623f384395aed33#diff-ba4eab13c8c4bbed78b701073f588f5b

**Comment by BluSunrize** [comment]
Problem here is most likely the fact that I didn't add the file to git, and thus it's not available on other devices.
I'll see to fixing this for future releases.

**Comment by PhoenixRiver** [comment]
Thank you :)

**Comment by bookerthegeek** [comment]
@MauveCloud I know that the issue is not in forge, but in IE. The commit was that he was using an older forge. Sorry that I did not make that more clear.

**Comment by PhoenixRiver** [comment]
> @MauveCloud I know that the issue is not in forge, but in IE. The commit was
> that he was using an older forge. Sorry that I did not make that more
> clear.

The _Recommended_ Forge... the one they think is a stable and current
enough build... I prefer stability of bleeding edge and most modders
prefer that too to save on using new features that don't make it to a
stable build.

Just my tu'pence - apologies for being entirely off topic.
