### ISSUE TITLE
[Request] CraftTweaker or Blacklist support for the Garden Cloche

### ISSUE THREAD

**Issue by An-Sar** [BluSunrize/ImmersiveEngineering#2833]
It would be very useful from a modpack stand point to be able to remove certain plants from use in the cloche. A specific example is a pack that uses NetherEX where special growth conditions are required for netherwart.

Minecraft 1.12.2
Minecraft Forge 14.23.2.2611
Immersive Engineering 0.12-78

**Comment by belathus** [comment]
Could we please get this?

**Comment by BluSunrize** [comment]
It's not that easy I'm afraid.
The cloche doesn't have a "recipe list", but instead a custom handler for basically every plant it handles. It's done on a code basis, rather than a recipe, so adding and removing isn't as simple.

**Comment by UnseenAcademical** [comment]
Would there be a way to make it call out to the config file to get the values it calls into ClocheRecipe.addRecipe? Iterate over the config file list to add all the plants?

**Comment by BluSunrize** [comment]
No.
Definitely not in 1.12, I've explained above why.

The Cloche already got completely remade in 1.14, and will be using JSON recipes in the neat future.

**Comment by UnseenAcademical** [comment]
Since I only am using 1.14 and have no intention of going back to earlier versions, that's perfect. Thank you for creating such an excellent mod, double thank you for redoing the code base.
