### ISSUE TITLE
ChiselsAndBits conflict

### ISSUE THREAD

**Issue by TechnicJelle** [BluSunrize/ImmersiveEngineering#2834]
In my serverlog it says "[chiselsandbits]: Unable to determine blocks eligibility for chiseling" for some of the blocks in the mod.
I read up on the error (https://github.com/AlgorithmX2/Chisels-and-Bits/issues/49) and it seems it can't be fixed by @AlgorithmX2.
These are the blocks:
blusunrize.immersiveengineering.common.blocks.cloth.BlockClothDevice attempted to load net/minecraft/client/util/ITooltipFlag
blusunrize.immersiveengineering.common.blocks.metal.BlockConveyor attempted to load net/minecraft/client/util/ITooltipFlag

**Comment by BluSunrize** [comment]
Well, you're definitely not supposed to chisel those two. I don't think that's a conflict, per se =P

**Comment by malte0811** [comment]
It looks more like a missing SideOnly to me. I guess C&B is trying to figure out whether they will work, but they threw an exception.

**Comment by ggblbl** [comment]
That is indeed what seems to happen, but those exceptions log about 20 times per exception and thus drastically slows down the startup.

**Comment by BrisingrAerowing** [comment]
It's actually a missing Optional annotation on some interfaces / methods (likely for WAILA). @mcjty had the same issue with RFTools.
