### ISSUE TITLE
[1.12.2 - 78] Insulated Wire Glitching

### ISSUE THREAD

**Issue by Yhuxz** [BluSunrize/ImmersiveEngineering#2835]
It revert back after I restart minecraft.

![2018-03-02_06 52 07](https://user-images.githubusercontent.com/36140746/36875031-36791572-1de9-11e8-9f8d-ebaffad66270.png)
Screenshot in different angle w/o Optifine

![2018-03-02_06 52 50](https://user-images.githubusercontent.com/36140746/36875047-4d16e110-1de9-11e8-958b-16e677b0094c.png)
Tried replacing it, doesn't work (at least the dark area in the pump is fixed with or without optifine)

I tested the same build in a different world but it works fine, dunno if the glitch is specific in this area the wires works in different area

**Comment by BluSunrize** [comment]
Read the contribution guidelines, you're missing out on key information such as modlist.
In this specific case, coordinates could be helpful too.

**Comment by Yhuxz** [comment]
I'm sorry I'm new to github and please bear with me I'm usually the player who ignores this bugs and just waits for new update, didn't know there's a lot to do

F3+C didn't crash my game. here's the debug screen tho.
![f3](https://user-images.githubusercontent.com/36140746/36877897-7f634a4c-1df7-11e8-8b9c-6be53d71cfc6.png)

And here are the mods I used (I just manually typed them the asterisk are Libraries and Cores if that helps)
https://gist.github.com/Yhuxz/9bb7d7c8a578275fe65b8b2780c97485

Forge Version
**1.12.2-forge1.12.2-14.23.2.2611**

Since I can't produce a crashlog here's the seed in case you need to recreate, its just a default world with cheats on/structures on/bonus chest on.
-745683473

**Comment by mindforger** [comment]
>Since I can't produce a crashlog

just for the future, while ingame and not only menu, press and hold F3 + C to create a forced crash

**Comment by BluSunrize** [comment]
That screenshot is with optifine instealled. Please provide one without it.

**Comment by Yhuxz** [comment]
Thanks for the tip.

https://gist.github.com/Yhuxz/1a2e78224147c4d26186b38534680bfb

**Comment by BluSunrize** [comment]
Well....that's not a screenshot?

**Comment by Yhuxz** [comment]
XD

No Optifine Right?
![2018-03-03_18 00 32](https://user-images.githubusercontent.com/36140746/36933039-9b824f2c-1f0d-11e8-950e-1b0864d5b0ca.png)

**Comment by BluSunrize** [comment]
Next step:
Can you reproduce this in a test environment? New world, only some connectors and cloches?
If not, it could be assumed that some of the blocks in the near vicinity are causing this glitch, for instance the Mekanism tube.

If you *can* reproduce it, please try limiting it down to cross mod interaction by performing a binary search through your modlist:
Remove half the mods, check if the problem persists. If it does, repeat the same process with that half, otherwise, do it with the other. Narrow it down to the mod that fixes the issue when you remove it.

**Comment by malte0811** [comment]
I'd say we move discussion on this to #2840 since that looks like a reproducible setup (haven't tested it yet, will try to fix it later today).

**Comment by Yhuxz** [comment]
I see Lorelando reproduced the issue then again here's my version of it. (the water pump still bugged even I placed a lantern beside it)
![2018-03-03_23 57 12](https://user-images.githubusercontent.com/36140746/36936532-c526ce28-1f41-11e8-8573-319148a375e4.png)

In this image I re-created the world and retrace the setup I made but the wires are fine
![2018-03-03_23 49 43](https://user-images.githubusercontent.com/36140746/36936746-26582e1a-1f44-11e8-9c74-26350a12987c.png)

**Comment by tyra314** [comment]
I'm on 0.12-80 and it got even worse. It's not only over chunk boundaries but also within one chunk.

![2018-03-29_19 45 55](https://user-images.githubusercontent.com/16997177/38104621-07f36368-338a-11e8-8b4f-3c2cebba901b.png)
![2018-03-29_19 46 19](https://user-images.githubusercontent.com/16997177/38104624-09211b22-338a-11e8-9b28-5d15c7cdaad8.png)
