### ISSUE TITLE
Suggestion for uninsulated wire (HV) protections

### ISSUE THREAD

**Issue by kragnoth** [BluSunrize/ImmersiveEngineering#2837]
Please make it so the faraday cage armor, or rubber boots from TCon, either reduce damage taken, or completely remove damage taken.

Thanks

**Comment by malte0811** [comment]
Making the faraday suit work for this is probably a good idea (that would make it less useless), I'll need to do some work to keep some amount of consistency though. I have an idea for that (there seem to be some techniques to make a tesla coil genuinely to dangerous to touch with a faraday suit), but I'll need to do some research and talk to Blu about it.

**Comment by CTH999** [comment]
_Surprisinly_ it works well with [This](https://github.com/BluSunrize/ImmersiveEngineering/issues/2888)
