### ISSUE TITLE
Electrical Posts not visually updating.

### ISSUE THREAD

**Issue by wBakunis** [BluSunrize/ImmersiveEngineering#2838]
Wooden, Aluminum, and Steel electric posts are not updating when using engineer's hammer. 

**Mods:** **(Not using optifine)**
- FTB Revelations 1.5.0
- Immersive Engineering 0.12-78
- Alternating Flux (IE Addon) 0.12-3
- Industrial Wires (IE Addon) 1.6-25

![2018-03-02_21 57 37](https://user-images.githubusercontent.com/3248262/36930048-c76c1f38-1e67-11e8-9c44-9d6aeecfd7e9.png)
![2018-03-02_22 15 23](https://user-images.githubusercontent.com/3248262/36930049-c781737e-1e67-11e8-9c31-b7b1f1bec28b.png)
![2018-03-02_22 16 15](https://user-images.githubusercontent.com/3248262/36930050-c7930940-1e67-11e8-8a20-9f1aaf97f4c9.png)

**Comment by Yhuxz** [comment]
I know for the fact that the first image really doesn't work, if you already attached two below the top can't be attached

**Comment by MauveCloud** [comment]
What is the y coordinate for the bottom of those posts?  This could be the same as #2311, where the posts are crossing the "render chunk" boundaries, and moving them up a little will allow them to display correctly.

**Comment by wBakunis** [comment]
Y coordinate is 63. I checked out #2311 and tried putting one of these posts at a lower position. The post updates correctly now. Ill close this issue as it's the same as #2311.
