### ISSUE TITLE
[Request] Include detailed descrition on forming Feedthrough Insulator multiblock in Engineers Manual / Cannot get Feedthrough Insulators to work

### ISSUE THREAD

**Issue by Lorelando** [BluSunrize/ImmersiveEngineering#2839]
I hope I'm not messing anything up, but closing this and opening a feature request for an update to the manual page to describe more accurately how to form the multiblock seems a little overkill.

Including the instruction about where to rightclick with a hammer in the manual page to form the Feedthrough Insulator might be helpful.

(This might be me, just not knowing how to do it, but I can't get Feedthrough Insulators to work.
The capacitor shown below is configured to output in all directions, the solid blocks used are white concrete.

I tried using other capacitors instead of powered lanterns, higher voltages and right-clicking connectors and blocks with a hammer.)

![2018-03-03_12 33 52](https://user-images.githubusercontent.com/19599163/36933889-e3be9796-1ee0-11e8-8d25-6c214ac9cee6.png)

Minecraft 1.12.2
Minecraft Forge 14.23.2.2611
Immersive Engineering 0.12-78

**Comment by BluSunrize** [comment]
if they are proper feedthrough insulators they will have that name, as they are a multiblock. If it still says "quartz block" or smth, then you haven't formed them.

You need to click the front face of one of the connectors, the "tip" if you will, to form the multiblock.

**Comment by malte0811** [comment]
You may have to disconnect the wires before forming the feedthrough connector, I can't remember whether I handle that.

**Comment by Lorelando** [comment]
Many thanks :)
Might that be worth a mention in the manual?

**Comment by malte0811** [comment]
Which tip helped, mine or Blu's? I might put Blu's tip in the manual if that was the problem, if it was the wires I'll see whether I can make it work with existing ones.

**Comment by Lorelando** [comment]
Kinda both, but especially Blu's tip.

**Comment by Lorelando** [comment]
Changed the title to more accurately describe why I didn't manage to form the multiblock.

**Comment by DoomRater** [comment]
Can feedthrough insulators be created through ceilings?  The example in the manual only shows side feedthrough insulators.

**Comment by Lorelando** [comment]
@DoomRater I just tried it, you can. The easiest way to find out is to take two connectors, a hammer and a solid block, but them in a vertical configuration and swing the hammer. It's what I did :P
The second easiest way is to look at the source code. Which I wouldn't recommend if you are a person like me and can't code.

**Comment by MattJE9601** [comment]
Can the feedthrough insulator be disassembled so we can reuse connectors with different blocks?  Also, the tip about where to use the hammer to form the multiblock did it for me, but it seems to differ from other multiblocks by remaining a multiblock when broke.  Originally seeing the item under NEI gave me the impression that it was craftable on a crafting table but showed no recipe.  When referring to the manual it did not reference being a multiblock, or how to form it... which led me here.  Thanks guys!

**Comment by winsrp** [comment]
had to look for this post in order to know how to make them work... blu's note was the trick, it doesn't say in the manual you need the hammer to make this work.

**Comment by BluSunrize** [comment]
It's a multiblock. You always need a hammer for those >_>

**Comment by BluSunrize** [comment]
I'm closing this btw., since assembly was greatly simplified to allow clicking the connector on any side.
