### ISSUE TITLE
Imcompatability with the Direwolf20 pack (1.6.1)

### ISSUE THREAD

**Issue by Slye-Fox** [BluSunrize/ImmersiveEngineering#284]
When adding Immersive Engineering (ether 0.5.0 which did works with DW20 1.5.0, or the new 1.5.1) to the Direwolf20 pack 1.6.1 on Feed the Beast, the game crashes during start up.

Here's the crash log: http://pastebin.com/sf6yqGth

**Comment by theunkn0wn1** [comment]
Simple fix: manually update AOBD

**Comment by Slye-Fox** [comment]
Just updated AOBD to 2.8.1, that seems to have fixed it. Thanks.

**Comment by theunkn0wn1** [comment]
No problem, i was in the exact same boat after 0.4.4 and that is why i recognized your crash. :smile:

**Comment by BluSunrize** [comment]
Yep, outdated AOBD. I frustrate Gany by repacking my API constantly. xD
