### ISSUE TITLE
[Bug] [Rendering] Wires not rendering on chunk borders under specific conditions

### ISSUE THREAD

**Issue by Lorelando** [BluSunrize/ImmersiveEngineering#2840]
Wires can stop rendering when hitting a chunk border under very specific conditions:
- the first connector has to be on the south or east side of the chunk, directly next to the border
- the seconds connector has to be in the next chunk, at least one block below the first one

![2018-03-03_13 07 45](https://user-images.githubusercontent.com/19599163/36934125-c2c201c8-1ee4-11e8-87b0-5444bcaf793e.png)

- this bug is new in build 78. I couldn't reproduce it with 77.

Minecraft 1.12.2
Minecraft Forge 14.23.2.2611
Immersive Engineering 0.12-78

**Comment by Yhuxz** [comment]
For the love of... I thought the rest of the image is not loading due to grey coloring, then again I saw the other images you reported you are using concrete, maybe use other blocks that can show an outline of the block, first thought how's that floating XD

**Comment by MauveCloud** [comment]
I have to agree - those relays (not connectors!) look like they're floating in fog in that image, even if they're technically on a wall of concrete or something.  For a couple of more specific suggestions, maybe stone bricks or polished granite as the backing?

**Comment by malte0811** [comment]
Fixed.
@Lorelando The background isn't ideal, but it isn't a major problem either (I actually didn't notice the weird background before @Yhuxz pointed it out). The rest of the report is great, tracking this bug down without a reproducible setup would probably have been very time-consuming!
