### ISSUE TITLE
[Request] Cutting wires by rightclicking them anywhere with Wirecutters

### ISSUE THREAD

**Issue by Lorelando** [BluSunrize/ImmersiveEngineering#2841]
As skyhooks are now able to attach at any point to a wire, would I be possible to cut one specific wire when right-clicking it?
That way you wouldn't have to search for and then reattach so many dropped wires anymore. And at the same time less unfortunate accidents would happen as you don't need to get as close to all those HV wires anymore.

Minecraft 1.12.2
Minecraft Forge 14.23.2.2611
Immersive Engineering 0.12-78

**Comment by malte0811** [comment]
Good point! Should be quite easy to do now.
