### ISSUE TITLE
[Bug] Feedthrough Insulator Multiblock crashes game when a Shaderpack is loaded

### ISSUE THREAD

**Issue by Lorelando** [BluSunrize/ImmersiveEngineering#2842]
Game crashed when trying to render a Feedthrough Insulator while a Shaderpack is loaded (tried Sildur's, Seus Renewed and OptiFine's internal shader).

> Description: Tesselating block model
> 
> com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: not enough data
> ...

https://pastebin.com/vv3YmXNY

Having a shader loaded also causes the engineers manual page on the Feedtrhough Insulator to go completely blank when trying to display the Multiblock inside the book.

Minecraft 1.12.2
Minecraft Forge 14.23.2.2611
Immersive Engineering 0.12-78
OptiFine HD U C9

**Comment by malte0811** [comment]
Optifine generally isn't supported, but I think I can fix this one and make the code nicer by doing so.

**Comment by Lorelando** [comment]
That would be really nice as there sadly seems to be no Forge compatible shader mod that isn't OptiFine.

Btw, is there a way do buy you guys a coffee? I really appreciate Immersive Engineering and your dedication to it's development.

**Comment by malte0811** [comment]
Blu has a patreon account. I don't have anything along those lines, I also usually don't drink coffee :smiley:. Thank you anyways!

**Comment by BluSunrize** [comment]
I drink tea, but both Damien and myself have Patreon accounts (which also get you some extra fancy revolver skins in IE!)

https://www.patreon.com/Hazard
https://www.patreon.com/BluSunrize

And yeah, Optifine isn't supported I'm afraid. If Malte can at least prevent the crash that's good, but note that you will probably still encounter some graphical weirdness.
