### ISSUE TITLE
[0.12-78] - Crash when placing metal ladder on multiblock

### ISSUE THREAD

**Issue by topster21** [BluSunrize/ImmersiveEngineering#2844]
### Description of the issue:
So as the title says, whenever I place a metal ladder (from IE) on a multiblock structure from IE (be it a metal tank, refinery or a crusher) it crashes the game. 

I have tested this in both singleplayer (0.12-78) and multiplayer (0.12-77, FTB Revelations) with both the same stack trace.

### How to reproduce 

Try to place a metal ladder on the side of a completed crusher, refinery (shift right-click) or tank multiblock structure. If it doesn't crash right away, keep trying different spots on the machine. Eventually it will crash the game.

### Crashlog:
[0.12-78 Single Player](https://gist.github.com/topster21/47469a6e5f786e08f0bf783e342d717d)
[0.12-77 Multi Player FTB Revelations](https://gist.github.com/topster21/a6674fec0ba24a9050d72be8b9f543d1)

### Versions & Modlist

`Java Version: 1.8.0_162, Oracle Corporation`

#### Single Player
```
| State     | ID                   | Version      | Source                           | Signature                                |
|:--------- |:-------------------- |:------------ |:-------------------------------- |:---------------------------------------- |
| UCHIJAAAA | minecraft            | 1.12.2       | minecraft.jar                    | None                                     |
| UCHIJAAAA | mcp                  | 9.42         | minecraft.jar                    | None                                     |
| UCHIJAAAA | FML                  | 8.0.99.99    | forge-1.12.2-14.23.2.2624.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| UCHIJAAAA | forge                | 14.23.2.2624 | forge-1.12.2-14.23.2.2624.jar    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| UCHIJAAAA | immersiveengineering | 0.12-78      | ImmersiveEngineering-0.12-78.jar | None                                     |

```

**Comment by wBakunis** [comment]
I just tried this on singleplayer. Game crashed while placing a metal ladder on the arc furnace. I'm using IE 0.1.2 - 78 with FTB Revelations 

> The game crashed whilst unexpected error
The game crashed whilst unexpected error
Error: java.lang.ClassCastException: blusunrize.immersiveengineering.common.blocks.metal.TileEntityArcFurnace cannot be cast to blusunrize.immersiveengineering.common.blocks.metal.TileEntityLadder

[Crashlog](https://drive.google.com/open?id=1VSmQ_-QehqiTIIMeFZuudby4DqUWe3Px)
