### ISSUE TITLE
[IE 0.12-78] Subtitle Localizations

### ISSUE THREAD

**Issue by Voxel-Friend** [BluSunrize/ImmersiveEngineering#2847]
The diesel generator's subtitle is broken and has been for many versions. Minor annoyance at best, but thought I'd give you guys a heads up. There might be others, but haven't found any. Maybe Tesla coil?

**Comment by BluSunrize** [comment]
Can you give more accurate description than "broken"?
Also, if it's been an issue for a while, begs the question why it wasn't reported sooner.

**Comment by Voxel-Friend** [comment]
Sorry, here is an image to clarify
![2018-03-08_07 03 12](https://user-images.githubusercontent.com/12395262/37152395-d0953438-229e-11e8-8aa2-f5c11ce5e7ee.png)
only installed mods are:
IE 0.12-78
IP 1.1.7
Forge 14.23.2.2624

**Comment by BluSunrize** [comment]
fixed by PR above
