### ISSUE TITLE
[1.12.2] Performance review requested for TileEntityBelljar

### ISSUE THREAD

**Issue by ProsperCraft** [BluSunrize/ImmersiveEngineering#2848]
### Description of the issue:
TileEntityBelljar - causes very poor performance.

Here is a screenshot from LagGoggles.
![2018-03-07_20 59 08](https://user-images.githubusercontent.com/4427684/37132507-3bfa62ec-224b-11e8-9491-8c278530aec6.png)
The green ones are switched off.  Even when off they take up 5-11 ms/t
![2018-03-07_20 59 49](https://user-images.githubusercontent.com/4427684/37132516-46677b7a-224b-11e8-9e2c-fb4de54d28cc.png)

Warmroast page - 
[warmroast.zip](https://github.com/BluSunrize/ImmersiveEngineering/files/1791789/warmroast.zip)

Sponge timings - https://timings.aikar.co/?id=8d9e0313c2dc4883959168bfb57ed875

Here is a sampler report for viewing in VisualVM
[belljar.zip](https://github.com/BluSunrize/ImmersiveEngineering/files/1791802/belljar.zip)

### Versions & Modlist
Mods - https://gist.github.com/ProsperCraft/e65ce778bf1e55a4e56be4d480a5287f

forge-1.12.2-14.23.2.2623-universal.jar
ImmersiveEngineering-0.12-78

**Comment by lgthibault** [comment]
Reading belljar.nps file... 

blusunrize.immersiveengineering.api.energy.wires.ImmersiveNetHandler.getIndirectEnergyConnections ()	2 318 ms. I find both notifyAvailableEnergy and transfertEnergy use getIndirectEnergyConnections(), which is an expensive call. I'm looking for a way to reuse result for a given tick.

Also looking at 
blusunrize.immersiveengineering.common.blocks.metal.TileEntityBelljar.func_73660_a () 888 ms. 

- blusunrize.immersiveengineering.common.blocks.metal.TileEntityBelljar.getCurrentPlantHandler () 100 ms. Most of which is spent doing blusunrize.immersiveengineering.api.tool.BelljarHandler$DefaultPlantHandler.isValid (). An idea for a fix would be avoiding the call to new ComparableHashSet().
- net.minecraft.world.World.func_175687_A () 270 ms. Not sure how that can be avoided.
- blusunrize.immersiveengineering.common.util.Utils.insertStackIntoInventory () 357 ms of which 303 ms are spent inside cofh.thermaldynamics.duct.item.DuctUnitItem.canRouteItem (). Perhaps follow-up with an issue with them.

**Comment by lgthibault** [comment]
@ProsperCraft would you describe how large your immersive energy network is? I'm working on some performance enhancements and I would like to run measurements against a network of similar size.

**Comment by ProsperCraft** [comment]
Its a large multiplayer server, so it changes based on the number of chunks loaded and who is on at the time.

Here is my base as an idea.

![2018-03-11_21 34 56](https://user-images.githubusercontent.com/4427684/37264626-1683c4fa-2574-11e8-9600-c06ad6f53a0b.png)
![2018-03-11_21 35 38](https://user-images.githubusercontent.com/4427684/37264781-08285d02-2575-11e8-9e6c-02ead7441fc8.png)
![2018-03-11_21 35 46](https://user-images.githubusercontent.com/4427684/37264783-0adc9d06-2575-11e8-849b-2b7956a7f66e.png)

Here is another base- 

![2018-03-11_21 43 30](https://user-images.githubusercontent.com/4427684/37264845-612b9158-2575-11e8-9b7e-4942ff49966a.png)
![2018-03-11_21 43 36](https://user-images.githubusercontent.com/4427684/37264848-62fbf446-2575-11e8-8e92-669840ea0047.png)

**Comment by malte0811** [comment]
The performance of the wire network is already fixed, see #2845.

**Comment by ProsperCraft** [comment]
Which fixes the TileEntityBelljar?

**Comment by malte0811** [comment]
I haven't gotten around to it yet. I don't know when I will, there were a lot of new bug reports yesterday, most of which are a higher priority (to me) than this.

**Comment by ProsperCraft** [comment]
I caught one acting REALLY bad!

![2018-04-09_11 18 10](https://user-images.githubusercontent.com/4427684/38512368-50ee5ad0-3be8-11e8-881a-1cffe10ba2bd.png)
![2018-04-09_11 18 48](https://user-images.githubusercontent.com/4427684/38512381-56969dc6-3be8-11e8-8a33-58edfa853cac.png)
![2018-04-09_11 17 40](https://user-images.githubusercontent.com/4427684/38512390-5a84827c-3be8-11e8-9aa7-e6101c2a629d.png)

It calmed down once I emptied its full output buffer.

Sampler nps for VisualVM-
[garden.zip](https://github.com/BluSunrize/ImmersiveEngineering/files/1890990/garden.zip)

**Comment by ProsperCraft** [comment]
ok, I thought the last one was really bad, but this one tops it off!

![2018-04-12_13 30 56](https://user-images.githubusercontent.com/4427684/38700255-b03fa27a-3e57-11e8-84ec-6bc062477dcf.png)

Output is full - it can't output hemp and seeds.
![2018-04-12_13 34 10](https://user-images.githubusercontent.com/4427684/38700263-b526a004-3e57-11e8-9343-06eb6ec23b27.png)

After clearing the output still ticking too high-
![2018-04-12_13 41 24](https://user-images.githubusercontent.com/4427684/38700291-ccb36c48-3e57-11e8-850e-8dc41c83c239.png)

**Comment by malte0811** [comment]
I had a look at the last NPS file. Are you using any sort of time acceleration (Watch of flowing time if that still exists in ProjectE, Torcherino, etc)?
 - The lag due to a full output is completely on Thermal Dynamics's side. This is about a third of the total cloche tick time, which is highly interesting as the output should only run every 8 ticks ([source](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/blocks/metal/TileEntityBelljar.java#L209)). TD is quite well optimized AFAIK, it shouldn't take this much tick time if it's only called every 8 ticks. Some of the time (about a quarter of the time spent in TD) is in Storage drawers, but most of it is still TD.
 - As in some other issue `ItemStack` initialization is a big time consumer. This is, as I said before, worse for your setup than most others because some mod actually does things on `ItemStack` initialization. It seems to be quite variable, the time taken varies by a factor >3. This is the part that can be optimized on our side.
