### ISSUE TITLE
Unable to locate blueprints in dungeons

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#285]
Issue: Blueprints do not appear in dungeon loot chests
==================
Info: after much searching manually into dungeon loot chests I have not been able to aquire **one** blueprint from that method. NEI states a 6.0% chance of getting one.......
![image](https://cloud.githubusercontent.com/assets/3110986/9104944/0307377a-3bc7-11e5-983e-6934908c58c2.png)

Steps to reproduce:
---------------------------
```java
while true {
   //player.search(string[] places, Item item);
   player.search(all_the_dungeons, blueprint);
}
```
or I also attempted to use that flower from Botania, the 'loonium' and after a full 30 mins of watching it spew dungeon loot items, got not one blueprint.
I will show you what i did get though... 5k+ of IC2/E tin... that has a 4.9% chance of occurrence according to NEI....

I can get the *craftable* blueprints from your villagers, but not the Arc furnace Electrodes one...\
How exactly is the users intended to obtain the Graphite electrode blueprint?

**Comment by Pihrra** [comment]
I don't know about the dungeon loot but I was able to buy the Arc furnace electrodes blueprint from a villager (I was lucky it was the first one I found too). I did not yet encounter the special bullets one. But they don't work yet in 0.5.1 apparently anyway.

**Comment by theunkn0wn1** [comment]
I tried for a full hour getting the blueprint from villagers... the kept offering me the craftable (Basic bullets) not never the Arc Furnace Electorodes.. Just my luck :-1:

**Comment by BluSunrize** [comment]
Yeah, has to be your luck. I spawned villagers and it worked for me =P

**Comment by theunkn0wn1** [comment]
it is not the villagers themselves.. btw their profession is not localized... I can successfully spawn IE villagers and trade with them, but they *never* offer the Electrode blueprints to me.
![image](https://cloud.githubusercontent.com/assets/3110986/9119219/683417fe-3c2a-11e5-8cf6-7712e189cef0.png)
this is the villager type i have been trading with, unless i am missing something neither he nor his kind offer me the blueprint.

**Comment by BluSunrize** [comment]
No, I'm saying that I spawned villagers and eventually got one selling the blueprint. They are available, just rare.

**Comment by theunkn0wn1** [comment]
Ok.. perhaps my sample size was too small. I will retry my experiment with a larger sample size and report the results....

Also, is the blueprint in question designed to appear in dungeon loot?

**Comment by BluSunrize** [comment]
It should, yeah. No idea what's going on there...

**Comment by theunkn0wn1** [comment]
@BluSunrize .... oh so you do have a sense of humor.....
================
![image](https://cloud.githubusercontent.com/assets/3110986/9123866/33e1b304-3c47-11e5-82dc-d4b5152027a4.png)
Only took me 24 iterations and over 100 villagers to get it though.


Anyways, my OP still stands
----------------------------

here is a list of everything my 'little' dungeon harvester has dug up... amongst a few small items it picked up from the air....

**Comment by BluSunrize** [comment]
That was AtomicBlom's idea... xD

**Comment by theunkn0wn1** [comment]
OK.. so if NEI lists The blueprint to be more likely in Dungeon loot than tin.... How exactly can i come up with over 14k tin and none of the blueprint? I call shenanigans

**Comment by theunkn0wn1** [comment]
OK... saw commit f1792e529db3a80253cf8fd0cc496f3f55cab796
I built IE to it, and reproduced the OP. Still not fixed :/

Running a Loonium farm (9x9) and have obtained 9k+ tin and no blueprints
Duration of test: 30 minutes and counting

**Comment by theunkn0wn1** [comment]
Sorry for the hassle, dumping the loot table reveals the blueprint spawns only in Strongold Libraries and blacksmith chests. not dungeons. This bug does not appear to exist as loonium is all about dungeons, not Strongholds. as it stands i do not have any definitive proof of the OP issues existence.
Sorry for the trouble.

**Comment by theunkn0wn1** [comment]
OK.. just verified the blueprints do indeed spawn in Stronghold libraries, however the only documentation i could find about exactly what kinds of chests the blueprints spawn in came from the source code of IE. :/

**Comment by BluSunrize** [comment]
True, I never really detailed that. I jsut figured that a library wouldbe the best place for that stuff to spawn, rather than a damp and mossy dungeon =P

**Comment by theunkn0wn1** [comment]
Yeah.. the average end user has absolutely no indicator of where exactly this blueprint spawns. The only way i found out was dumping the loot table and accessing the source code. Your reasoning is kinda eh imho, you are trading a damp and mossy dungeon for a damp and moldy stronghold. 
You are significantly increasing the rarity of the item by binding it to the stronghold library, as there is only 3 strongholds per world (iirc) and you are not %100 chance to even get one library per stronghold.
Also: what kind of ancient technology is this? I was unawares the Ancients had access to electricity.

**Comment by BluSunrize** [comment]
Oh for fucks sake, it's a minecraft mod .-.

**Comment by BluSunrize** [comment]
For the record, after just revisitng my own code, the blueprints spawn in village blacksmithies aswell.
