### ISSUE TITLE
Engineer's Manual possible crash

### ISSUE THREAD

**Issue by roulito** [BluSunrize/ImmersiveEngineering#2850]
![15ef05aaac347f945454ee6936210d9b](https://user-images.githubusercontent.com/8797474/37167617-b039b650-2302-11e8-93ca-9bbfd253ad4f.png)
![49484b543bd8b33c38b74b780b6552a1](https://user-images.githubusercontent.com/8797474/37167618-b05ba6f2-2302-11e8-90ec-fd667b29127b.png)
![f7b50dec50f82dcb56ce351994039483](https://user-images.githubusercontent.com/8797474/37167619-b076dde6-2302-11e8-98ce-5fb42c813842.png)
![java](https://user-images.githubusercontent.com/8797474/37167770-2abc8ae2-2303-11e8-8462-13bee86444ba.PNG)

No other java version

**Comment by malte0811** [comment]
The launcher has its own version. Check the F3 debug screen, top right corner IIRC. [Here](https://docs.google.com/document/d/e/2PACX-1vR5muyi1m7Zy_qSwrzeb9e3tbbRlksguNUb_Pvm3pn9eDpsIkUj5qQUq6WFPPdEoVWZq91WvvH57KzC/pub) are instructions on how to force the launcher to use up-to-date Java (Not mine, found them on the FTB subreddit).
