### ISSUE TITLE
*REQUEST* Since Wires can't pass through blocks anymore a option?

### ISSUE THREAD

**Issue by Mementh** [BluSunrize/ImmersiveEngineering#2851]
With the change to wires and there behavior of breaking if you place a block, can we get some way of having a pass through block or painting type block? like Ender IO has? 
It would be nice to have such a option

**Comment by malte0811** [comment]
There are feedthrough connectors now, those should be exactly what you want. Check the last page of the manual entry on basic wiring. The bookshelf can be replaced by any reasonably inert solid block.
