### ISSUE TITLE
OpenComputers API Not Active

### ISSUE THREAD

**Issue by Saklad5** [BluSunrize/ImmersiveEngineering#2852]
### Description of the issue:
The OpenComputers API for Immersive Engineering [appears to be commented out in the code](https://github.com/BluSunrize/ImmersiveEngineering/blob/495e2c5365235881285909cff65e087f945fdc1d/src/main/java/blusunrize/immersiveengineering/common/util/compat/IECompatModule.java#L54), and the relevant part of the manual does not show up. Furthermore, no Immersive Engineering devices seem to connect to computers, even with Adapters.

It seems like this has been forgotten, especially since there is no open issue about it. I was hoping to write a program that would automatically disable finished Excavators and ping me about it, so I’d appreciate it if this API was brought back.

### Versions & Modlist
Forge: 14.23.1.2601
Immersive Engineering: 0.12-76
Modpack: Direwolf20 1.12.2-1.8.0

**Comment by malte0811** [comment]
On the one hand, take a look at #2510 (The implementation is pretty bad, and OC has a bug that makes a better one semi-impossible). On the other hand @BluSunrize meant to re-enable compat in 0962488bace56a3200daccf54334bb6faef66b1d, but didn't actually comment out the line you linked.

**Comment by Saklad5** [comment]
Yeah, I was wondering about that commit.

**Comment by Saklad5** [comment]
All I really need is the ability to use getExpectedVeinYield() with Sample Drills.
