### ISSUE TITLE
Crude Blast Furnace not creating steel

### ISSUE THREAD

**Issue by g3arshift** [BluSunrize/ImmersiveEngineering#2854]
### Description of the issue:
Crude blast furnaces will consume fuel, but no progress will be made on producing steel and nothing is output.

### Versions & Modlist
IE version 0.12-76, Forge version 1.12.2 - 14.23.2.2611.
[Modlist](https://pastebin.com/8yc6KSRk)

**Comment by malte0811** [comment]
I doubt this is happening on IE 76. You are using IE 77. You should be using IE 78, it is fixed in that build.
BTW, you should delete the old core jar files. Wire damage will not work at all like this.
