### ISSUE TITLE
MoreChickens XP orb not inserting into StorageDrawers Drawer Controller

### ISSUE THREAD

**Issue by PhoenixRiver** [BluSunrize/ImmersiveEngineering#2856]
### Description of the issue:
I have a Chickens / MoreChickens / Hatchery setup with hens in Hatchery Nesting Pens with a dropper underneath that drops the things the hens lay onto an ImmersiveEngineering conveyor belt system that then tried to insert them into a StorageDrawers Drawer Controller. This all works perfectly (once I filter out the eggs) except for the MoreChickens XP Chicken's XP Orbs which travel along the conveyor belt system perfectly fine but then turn into actual Vanilla Minecraft xp spots at the point the XP Orbs are inserted into the Drawer Controller and then just sit on the last conveyor bumping into the controller. I should note that XP Orbs can be manually stored in StrorageDrawers Drawers by right clicking, it is only the Drawer Controller automated method that is a problem.

### Versions & Modlist:
Minecraft: 1.12.2
Forge: forge1.12.2-14.23.2.2611
Chickens: chickens-6.0.3
MoreChickens: morechickens-1.12.2-3.1.0
Hatchery: hatchery-1.12.2-2.1.2
StorageDrawers: StorageDrawers-1.12.2-5.3.4
ImmersiveEngineering: ImmersiveEngineering-0.12-76

P.S. I'm just updating to the latest versions of StorageDrawers and ImmersiveEngineering of these but none of them included anything in their change logs to say anything might have changed the above problem.

**Comment by BluSunrize** [comment]
Uhh, pictures?

I may be misunderstanding this, but Minecraft's XP Orbs aren't items, hence why a conveyor can't insert them...

**Comment by Lorelando** [comment]
So basically the mod adds an XP item, that can be picked up and stored like any other item?
And when the conveyor tries to insert the XP item into a drawer, it instead gets converted into an XP entity, that floats around and would increase your level when picked up?

Could you try following things:
- Can a hopper insert the XP item directly into a drawer?
- Can an IE conveyor insert the XP item into a vanilla chest?
- What happens when the XP item reaches the end of an IE conveyor that doesn't point into any inventory and just "drops" the XP item?

(At the IE devs, I hope it's ok when I drop in from time to time and comment like this on issues? I'm basically just typing out the steps I would take to test something in order to narrow down a bug.)

**Comment by PhoenixRiver** [comment]
Apologies, my bug report was erroneous... it seems the problem is not the XP item (from the MoreChickens mod) being inserted into the StorageDrawers Drawer Controller block.

1. The XP item can be put into a hopper and inserts correctly into a vanilla Minecraft Chest block.
2. The XP item can be right click inserted correctly into a StorageDrawers Drawer block.
3. The XP item can be put into a hopper and inserts correctly into a StorageDrawers Drawer block.
4. The XP item can NOT be put into a hopper and "inserted" correctly onto an ImmersiveEngineering Conveyor block. The vanilla Hopper block drops vanilla Minecraft XP "things"/orbs (not item or block) onto the Conveyor block which appears to correctly move them along to other Conveyor blocks (I'm impressed this works at all! Nice! :)

I can test more configurations if that would help but it appears that the problem for the MoreChickens XP item lies at the interface between the vanilla Minecraft Hopper block and the ImmersiveEngineering Conveyor block.

My suspicion is that, as suggested by @GenDeathrow (MoreChickens mod owner), the Hopper block is "throwing" the XP item at the Conveyor block except that this doesn't cause a problem with Chest or Drawer blocks so it seems to be an issue with the Conveyor block?

As I said, if there are any more tests I can perform that might be of help I'm happy to...

P.S. I've posted this to the bug reports made to all three of StorageDrawers, ImmersiveEngineering and MoreChickens as well as closing the one for StorageDrawers as it appears that is not the issue. I'll try to be more careful next time, apologies.

**Comment by PhoenixRiver** [comment]
jaquadro/StorageDrawers#633

**Comment by PhoenixRiver** [comment]
GenDeathrow/MoreChickens#46

**Comment by GenDeathrow** [comment]
If it helps to understand. When my solid exp becomes an entity item, It turns into an exp orb instead.  So outside of an inventory it converts back into an orb. I'm not sure if there is really anyway of fixing this outside of me changing how the solid exp works. Now I'm going to do some testing later tonight, just so I can see whats really happening.

**Comment by PhoenixRiver** [comment]
> So outside of an inventory it converts back into an orb.

This then might be the crux of the problem since IE Conveyor Belts
transport things as non-inventory entity items... I think? It
certainly looks like it...

**Comment by Lorelando** [comment]
What happens if you just press "q" to drop the item into the world? You might want to take a look at either pipes or Hopperducts in that case.

**Comment by PhoenixRiver** [comment]
Just checked now and if you drop the XP item using "q" or by moving it
out of the inventory screen to drop/throw it it turns into vanilla
Minecraft xp orbs.

**Comment by MalkContent** [comment]
@GenDeathrow, do the item entities have to tick to be converted to xp orbs? Cause if the item entities on the conveyor are allowed to tick, that could potentially cause issues with other mod items, too.
