### ISSUE TITLE
[MC 1.12.2, IE 0.12-78] Windmill Crash: "Unable to get Y-rotated facing of down"

### ISSUE THREAD

**Issue by seriallos** [BluSunrize/ImmersiveEngineering#2857]
### Description of the issue:

Player on the server was trying to set up windmills and got a block into a state that crashes the server whenever the chunk is loaded.

Description of events from the player: "I had put the windmill down a couple of times in rapid succession, trying to place it how I wanted it. right at the end, I had cleared out the supporting pillar below it and fell to the ground"

Server runs fine as long as that chunk is not loaded. Other windmills on the server seem OK.

### Crashlog:

https://pastebin.com/zv75DEnM

### Versions & Modlist

Forge-modified MC dedicated server running on Debian.

**Comment by lgthibault** [comment]
@seriallos I don`t have the offending world to test my fix. What are the chances you try these snapshot jars (https://drive.google.com/drive/folders/1n3lbwGxi3fUPJKA4YyVUCp1lvNxrcIOi?usp=sharing) ?

**Comment by BluSunrize** [comment]
It's not allowed to host custom built artifacts of IE without the express permission of its maintainers. Please don't do that.

**Comment by lgthibault** [comment]
woops, sorry! taken down. 

I'm opened to suggestions as to how letting @seriallos test the fix before making the fix official.

**Comment by malte0811** [comment]
@seriallos Any idea what your player means by "It fell to the ground"? As an item doesn't make sense with the crash, and I don't see any mods that make arbitrary blocks fall in your list.

**Comment by lgthibault** [comment]
Unfortunately that's a blind fix, as breaking the block below the windmill doesn`t trigger the issue in my test world (ie only).

**Comment by malte0811** [comment]
Yeah, I was wrong. It takes a few seconds for this to trigger (because the obstruction check doesn't run every tick). Your feet need to be higher than the bottom of the windmill while placing it and you need to place it against the top of a block.
Re: blind fix: This bug (at least the part you fixed) is quite obvious, the fix isn't the sort of thing that can break if two people agree it should work.
