### ISSUE TITLE
[Suggestion] Standardize Heat mechanics

### ISSUE THREAD

**Issue by pip69** [BluSunrize/ImmersiveEngineering#286]
Pneumatic Craft uses heat for it's refinery.  Having compatible mechanics for the same system would be nice.

**Comment by BluSunrize** [comment]
...There is no heat mechanic in IE O_o

**Comment by pip69** [comment]
Ok, but the External Heater does create the impression that there is. I guess it's just fancy way to use RF to power a regular furnace.  
Still, it would be nice if the concept of "heat" was cross-mod compatible, like the way RF is.

**Comment by BluSunrize** [comment]
MineMaarten's heat mechanic is very intricate. My furnace heater is as complex as the vanilla furnace itself, so compat would be very confusing.
