### ISSUE TITLE
Game will not launch, no idea on why this is, but the crash always comes on an IE file.

### ISSUE THREAD

**Issue by KumbitWumbit** [BluSunrize/ImmersiveEngineering#2860]
I don't know much more than I wrote above, so I'll just drop in the Pastebin.
https://pastebin.com/Dvf1er8p
--------------------------------------------
The mods used were:
+Integrated Dynamics
+Buildcraft
+Buildcraft Compat
+Forestry
+Thermal Foundation
+Thermal Expansion
+Thermal Dynamics
+UniDict
+NuclearCraft
+JourneyMap
+Just Enough Items
+Pam's HarvestCraft
+Pam's Cookables
+Immersive Engineering
+Immersive Petroleum
+Immersive Railroading
+Akashic Tome
+Waila
+Advanced Rocketry
+Rustic
+TreeCapitator
+Genetics Reborn
+Bionisation 3
+Open Glider
+Rockhounding Mod: Chemistry
+Butchercraft
+Hungry Animals
+Cyclops Core
+Common Capabilities
+CoFH Core
+ConnectedTexturesMod
+Track API
+Rockhounding Core
+LibVulpes
+CodeChickenLib
+AutoRegLib
+WanionLib
--------------------------------------------
IE version: 0.11-63
Forge version: 1.11.2 - 13.20.1.2588
--------------------------------------------
![ie crash screenshot](https://user-images.githubusercontent.com/26194208/37250440-a075910c-24ca-11e8-9925-267855aa7de5.png)

**Comment by malte0811** [comment]
Downgrade Forge by a few versions. 1.11 is unfortunately no longer supported.
