### ISSUE TITLE
Not a bug, wish to use in mod pack

### ISSUE THREAD

**Issue by Shovinus** [BluSunrize/ImmersiveEngineering#2861]
Sorry to be a pest, I am trying to create a mod pack called Simples whilst building the license file though and trying to link all used mods I have found you actually disallow redistribution of your mod without express permission.

Please therefore could I have permission to put your compiled mod within my mod pack?

I did look around for a way to message you privately on here but could not see one.

Kind regard

Shovinus

**Comment by Shovinus** [comment]
I am doing the pack.on github this is why, end game I will do on curse but I want people's input and allows me to make changes and access from multiple PC's, I don't intend to publish the final thing that way.

On 11 Mar 2018 09:22, BluSunrize <notifications@github.com> wrote:

Is it a pack on CurseForge? Because those are totally fine to use IE in.

I'm less happy with distribution on other sources (because with Curse, I uploaded it, and I guarantee for its safety and not being malware, etc), but I can't stop you so...

**Comment by bookerthegeek** [comment]
An easy solution to this is to build th pack in curse ( not as a public pack, but as a private custom instance) then export it and host that on github. This way you do not need to worry about redistribution unless the pack is not on curse.

**Comment by Shovinus** [comment]
Yeh I was wondering about this, curse doesn't deal with server versions though does it? How do people release them?


On 12 Mar 2018 05:34, BookerTheGeek <notifications@github.com> wrote:

An easy solution to this is to build th pack in curse ( not as a public pack, but as a private custom instance) then export it and host that on github. This way you do not need to worry about redistribution unless the pack is not on curse.

**Comment by mindforger** [comment]
>Yeh I was wondering about this, curse doesn't deal with server versions though does it? How do people release them?

they make either a similar pack with only the server side mods (PS you can also select the configs and everythign that maybe required from your minecraft folder during the export)

or they shove in the same pack on the server and remove the client only mods and settings

**Comment by BluSunrize** [comment]
Some hosting solutions (like Creeperhost) actually provide a service of installing client packs and automatically chucking out the client-only mods.
