### ISSUE TITLE
Graphical issues concerning wires (version 78)

### ISSUE THREAD

**Issue by Branjoman** [BluSunrize/ImmersiveEngineering#2866]
Found a few graphical issues when using wires:
1: An insulated LV wire connected between an LV connector and a powered lantern seems to fade out halfway along the connection.
[https://imgur.com/CmBJVr5](url)

2: When connecting a HV wire from a transformer to a HV connector (as part of a feedthrough block), a second phantom wire appears.
[https://imgur.com/h1x1J2F](url)

**Comment by malte0811** [comment]
#2840 for the first one (fixed for IE 79)
I'll look into the second one. Did you connect the wire before forming the multiblock or afterwards (or both)?

**Comment by Branjoman** [comment]
After forming the multiblock (I think you have to to get the feedthrough thing to form).

**Comment by Lorelando** [comment]
About number 2. Do you have OptiFine installed and was the transformer connected to something else before? (I found a weird thing with a wire that actually doesn't exist appearing again, but its only with OptiFine, so I didn't bother reporting it)

**Comment by glindsey** [comment]
Seconding Lorelando's comment -- I also see "phantom wires" reappear briefly when using OptiFine, but they vanish after a short period. I also see these phantom wires sometimes appear when placing a new connector/relay on a block after removing an old one (for example, replacing a LV relay with an MV one). Again, they disappear after a little while.

**Comment by PrincessRTFM** [comment]
Optifine is not supported. Optifine has never been supported. Optifine will probably never _be_ supported. Optifine mangles the base game code and doesn't even offer dev jars for testing - you need to use a third-party utility to make one. Blu (and basically every other modder out there) tells people "do not submit bug reports when optifine is installed". Remove OF and see if the issue persists. The contributing/bugreporting guidelines list four unsupported mods, and Optifine is at the top of that list.

**Comment by glindsey** [comment]
I’m aware of that. I was attempting to explain to him that others have seen this issue, not that it will be fixed. Drop the attitude.
