### ISSUE TITLE
Feedthrough insulator with redstone wires doesn't transmit current (0.78)

### ISSUE THREAD

**Issue by Branjoman** [BluSunrize/ImmersiveEngineering#2867]
I'm trying to use a feedthrough insulator to transmit redstone current through a block, but when everything is hooked up, the signal is not received on the other side of the block.

Example: https://imgur.com/h4iY0oz

Note that the connector on the side of the redstone lamp cannot be set into output mode (unable to toggle so while in multiblock mode, and if toggled before the feedthrough insulator is formed it reverts back to input mode).

On an unrelated note, how on earth do I unform the feedthrough insulator? Breaking it doens't work, nor does right clicking it with a hammer everywhere...

**Comment by Lorelando** [comment]
Actually, it looks like your "not working" redstone connector connected directly to the redstone lamp is configured as input, not output.

On the unrelated note, sadly, it seems you can't. I really hope it'll be brought more in line with other multiblocks.

**Comment by Branjoman** [comment]
Ah, I hadn't noticed that before. Unfortunately, changing it doens't fix the issue 
[https://imgur.com/wGUey7A](url)

**Comment by BluSunrize** [comment]
I've fixed your link. You either just post the URL itself, without doing that bracket stuff, or if you want to embed stuff, you format it like so:
`![Title of the image](URL)`

I'll need Malte's input on this, Feedthrough insulator is his toy, but tbh, I think it should have default multiblock behavior of breaking back into it pieces. I don't think the ability of picking it up is prominent enough to validate overriding core behavior.

**Comment by malte0811** [comment]
Picking it up is only possible because I started implementing it one way and then changed it to a multiblock halfway through. I agree that it should have the default behavior. I'm pretty sure I know why the redstone wires don't work, I'll check it later today.
