### ISSUE TITLE
[1.12.2] Server Crash - Ticking block entity (item sorter related, maybe!)

### ISSUE THREAD

**Issue by ruyanve** [BluSunrize/ImmersiveEngineering#2868]
Using IE 0.12-78 with Forge 2618

One of our players started automating pams harvestcraft and is using hoppers and item routers. I don't exactly know what he is trying to transfer, but our server crashes on startup with the following: https://hastebin.com/amiwixiran.pl

Any help would be greatly appreciated, the guys are going mental without their daily MC fix (and are letting me know every hour!) :-P

Cheers <3

**Comment by ruyanve** [comment]
So I'm guessing this means it has nothing to do with IE then?

Any recommendations what to do best now? Mcedit to get rid of the hopper?

Cheers

**Comment by malte0811** [comment]
No, that means it is an IE bug that is fixed for the next release ("closed this in <...>" vs just "closed this"). MCEditting out the hopper or the routers is probably the easiest solution. There are probably 4 routers in a square (with some very specific settings), those are the ones causing the crash.

**Comment by ruyanve** [comment]
Oops didn't see the commit :-)

Cheers, keep up the great work!
