### ISSUE TITLE
Major dupe bug with the engineers table

### ISSUE THREAD

**Issue by Adraxas** [BluSunrize/ImmersiveEngineering#287]
to reproduce, insert any blueprint, then make anything then close and reopen the GUI, the items you used to make the item will be back

**Comment by Pihrra** [comment]
I confirm this happens for me too.
Also when making electrodes they stack when I take them out of the table but if then shift click them in a chest that already contains brand new electrodes they don't stack as if electrodes from different crafting operation are different. However if I then stack them manually it sort of works but I end up with 1 not stacking with the others.
So for example if I have 4 electrodes that I try to manually stack with 4 other previously crafted non-used electrodes I end up with a stack of 7 and 1 that refuses to stack with the others.

**Comment by theunkn0wn1** [comment]
I can confirm this.

Issue: Workbench Dupe Bug

=====================
Info:
Any item crafted within the IE Workbench can be duplicated endlessly

Steps to reproduce:

================
[1] Place any blueprint into Workbench
[2] place required crafting components for blueprint into workbench
[3] Craft item
[4] close interface
[5] re-open workbench interface
[6] goto(3)

Version data:

-------------
IE version 0.5.2 ebafdeb4a33abbda8b5a673e9277d3c3d81d04bb

 Horizons (1.9.0) no modifications

**Comment by BluSunrize** [comment]
I'm on vacation.This will be tended to in two weeks.
