### ISSUE TITLE
Cables get broken by invisible light blocks from RF-Lux mod

### ISSUE THREAD

**Issue by calloatti** [BluSunrize/ImmersiveEngineering#2870]
https://minecraft.curseforge.com/projects/rf-lux

Has lights that create additional invisible sources of light. These blocks cannot be seen or interacted with.

These blocks break IE cables. So it's basically a nightmare to use the 2 mods together.

**Comment by malte0811** [comment]
I probably fixed this yesterday, I'll test it later today (unless you do so first).

**Comment by mindforger** [comment]
@malte0811how are wires behaving when you let water or other liquids flow over them? And think of "gas" blocks

**Comment by malte0811** [comment]
@calloatti I couldn't get the lights to work, from looking at the code it should work in IE 79 (when it is released).
@mindforger Water (and presumably other liquids) do not block the wires, at least on current master.

**Comment by mindforger** [comment]
kay :) was a little worried those might be forgotten :P
