### ISSUE TITLE
Can't find entry in Engineer's Manual for Metal Ladders.

### ISSUE THREAD

**Issue by AgentA1cr** [BluSunrize/ImmersiveEngineering#2871]
### Description of the issue:
There does not appear to be an entry for Metal Ladders in the Engineer's Manual. It would be useful to have an entry detailing any advantages they have over normal ladders. I haven't scoured every page of every entry, but I've read over the entry headings in every chapter and looked in all the places that seem logical. Metal Constructions seems like a good place to put them.

### Versions & Modlist
IE: 0.12-78
Forge: 14.23.2.2618
I don't think any other mods are relevant to this issue, but if you want a full mod list, I can get you one.

**Comment by BluSunrize** [comment]
They don't have an entry. Their advantage is that they look cool =P

**Comment by Lorelando** [comment]
This is I am having this image in my head:
The entry page about metal ladders, showing the recipe. Below the recipe a description:

> You can climb them.
> They also look cool.
> - Blu

;)

(Sorry for being completely off topic, irrelevant and maybe slightly mean, I couldn't quite help myself)

**Comment by PrincessRTFM** [comment]
Personally, I would just swap those.

> They look cool.
> Also, you can climb them.

**Comment by BluSunrize** [comment]
![image](https://i.imgur.com/PSV6jjo.png)

How's this? =P

**Comment by Lorelando** [comment]
I'd remove the "...well," part, makes you take a second longer to process the joke.

**Comment by BluSunrize** [comment]
That first sentence isn't a joke, it's a statement that questions its own necessity.

**Comment by lgthibault** [comment]
metal conducts electricity and could lead to all sorts of fun. when close to wires, etc.

or make the player climb faster

or accelerate/brake rail gun ammo
