### ISSUE TITLE
1.12.2 Minecraft Crashes when trying to open IE UI in Creative mode.

### ISSUE THREAD

**Issue by WygerBlitz** [BluSunrize/ImmersiveEngineering#2875]
Minecraft version: 1.12.2
Mod version: 0.12_78

Using it with IR (Immersive Railroad)

Steps: I go to singleplayer - Play - Open UI - Everything is normal until I choose tab with IE crafting tables in it - Start scrolling down or just sit in the menu and in 2-5sec game crashes.

https://pastebin.com/e180GJHp

**Comment by malte0811** [comment]
Caused by optifine, fixed for the next release (d9a79fddfd75bd4ad6f80c5989760b8c372568ef).

**Comment by WygerBlitz** [comment]
Is it fixeble by downloading a never/older Optifine?

**Comment by malte0811** [comment]
Probably not.
