### ISSUE TITLE
Suggestion add faraday upgrade to EIO Darksteel armour

### ISSUE THREAD

**Issue by tyler489** [BluSunrize/ImmersiveEngineering#2878]
I was wondering if you would consider adding the faraday suit to be an optional  upgrade to enderio's armor. I read that the suit might  block damage from your wires and would love to see that be added to enderios armor. When i spoke to the enderio devs they said it would be better compatibility from  your end. 

See /enderio-base/src/main/java/crazypants/enderio/api/upgrades/IDarkSteelUpgrade.java for enderio upgrade series . When i spoke to them they said ```I recommend to employ crazypants.enderio.base.handler.darksteel.AbstractUpgrade, or at least have a very good look at it``` and that it would be possible for wire damage to actuall charge darksteel if you wanted.

**Comment by BluSunrize** [comment]
No such plans, I'm afraid. I intend for that feature to stay in IE.
