### ISSUE TITLE
Client crash -  IESmartObjModel tries to create a list with NULL contents.

### ISSUE THREAD

**Issue by ProsperCraft** [BluSunrize/ImmersiveEngineering#2879]
### Description of the issue:
Client Crashes, optifine author points back here.

https://github.com/sp614x/optifine/issues/1290

**Comment by BluSunrize** [comment]
Optifine issues are invalid here.

**Comment by malte0811** [comment]
Would it be possible to change the Optifine policy from "not supported, issues are immidiately closed" to something like "very low priority, don't complain if this isn't ever fixed"? I have an OF version I can use in my dev environment (thanks to Barteks2x for helping with that!) and there's an OF discord with a channel specifically for mod compat, so fixing OF issues is a lot easier for me now than it was a year ago.

**Comment by ProsperCraft** [comment]
I am sorry did you actually look at the issue, he found a problem on your code, which is the only reason I posted it here.

**Comment by malte0811** [comment]
I looked at the issue.
1. The fix he suggested would result in watermills being invisible. It would fix the crash, the underlying bug wouldn't be affected. There are ways to fix it without direct rendering issues, but they would be very laggy if I'm interpreting the crash correctly.
2. I wasn't able to replicate the crash (IE, slightly outdated OF and a couple of other mods). Does it happen for you with just IE and OF?

**Comment by ProsperCraft** [comment]
Will have to set that up and test it.

Is this related my old issue https://github.com/BluSunrize/ImmersiveEngineering/issues/1677
