### ISSUE TITLE
Cant connect to HV wire relays

### ISSUE THREAD

**Issue by Adraxas** [BluSunrize/ImmersiveEngineering#288]
whenever i try to connect to an HV wire relay, i get the message "the connection is obstructed" even when it obviously isn't. also, trying to connect FROM a relay works

**Comment by cobra** [comment]
Found the bug and fixed it. The HV Relays are a bit longer than the HV Connectors, but this wasn't considered when checking the connection path, which led to a collision inside the first relay. I'll submit a pull request with the fix.

**Comment by BluSunrize** [comment]
I'm on vacation.This will be tended to in two weeks.
