### ISSUE TITLE
Question: Excavator Configs

### ISSUE THREAD

**Issue by TheCowKing-moo** [BluSunrize/ImmersiveEngineering#2880]
Making a modpack based around ores that only spawn in certain biomes. I'm trying to figure out a way to generate veins based on what biome they are in, but I cannot wrap my head around it. So far all I can find are dimension based white/black lists. 

Any help/advice would be appreciated.

**Comment by BluSunrize** [comment]
There is no such option in the system currently.
All veins are allowed to generate anywhere, the only filter is the dimension lists.

**Comment by TheCowKing-moo** [comment]
Thats too bad. Thank you.
