### ISSUE TITLE
[1.12.2] Weirdness with cloche / belljar

### ISSUE THREAD

**Issue by PhoenixRiver** [BluSunrize/ImmersiveEngineering#2882]
### Description of the issue:
I have a cloche set up next to a field of carrots. When I put a carrot in the cloche to try and grow it it doesn't work (maybe related to me also having Pam's Harvestcraft? There was a bug with -75 with that), in addition (I don't know if it is related yet) four carrots from the field closest to the cloche pop from the ground and are left as entities on the dirt?!? I can replant two of them and they stay there but the other two don't. But when the two I have replanted reach maturity they automatically pop from the ground!

Diagram:
```
CCZXXB    C = carrots    B = cloche
CCCZC       Z = carrots I can replant but pop when mature
CCCCC       X = carrots that can't be replanted
```
I should note this happened as soon as I placed the cloche, there was no power or water to it and no carrot or dirt in it.

NB: I have yet to exclude the possibility this is related to interaction with another mod e.g. Pam's Harvestcraft or Hatchery (the dirt in the farmland is fertilised dirt - though I've tried both fertilised dirt and vanilla dirt in the cloche and the carrot still doesn't grow - it definitely has water and power and the power and water don't decrease (though both are oversupplied so maybe I'd not see it?)).

### Versions & Modlist
Forge: forge1.12.2-14.23.2.2611
ImmersiveEngineering: 0.12-78
Pam'sHarvestCraft: 1.12.2q
hatchery: 1.12.2-2.1.2
CookingForBlockheads:1.12.1-6.3.17

(I can add a full mod list if that would be helpful but it's a relatively light modpack with nothing else related to food).

**Comment by BluSunrize** [comment]
The cloche has absolutely no effect on other blocks in its area, so I don't know how it would be causing this.

**Comment by mindforger** [comment]
missing soil moisture maybe? where is a water source in your setup?

**Comment by PhoenixRiver** [comment]
See below for an expanded diagram of the current setup. I moved the Cloche to see if that made a difference to the carrots... nope?!?!
The pump and cloche are both powered through LV connectors on their tops via LV wires coming from a capacitor that a (triple) waterwheel runs into - they are the only things that source power constantly from this source and only a press is hooked up that is in occasional use.

```
S = Stone
D = Dirt
W = Water
T = Fence
P = Pump
F = Fluid Pipe
C = Carrot
Z = Carrot I can plant but pops on maturity
X = Carrot that pops immediately
- = Air block

Full setup (underground layer):
SSSSSSSWWS
SWSSSSSWWS
SSDDDDDSSS
SSDDDDDSSS
SSDDDDDSSS
SSDDDDDSSS
SSDDDDDSSS
SSSSSSSSSS

(above ground layer):
------SSS
TTTTTTPFS
TCCZXX-B-
TCCCZC---
TCCCCC---
TCCCCC---
TCCCCC---
SSSSSS---

```

Doh!! I've just realised that it might be the pump? Might it be searching for liquid sources and causing block updates in surrounding blocks that is doing something odd with the fertilised dirt (from Hatchery) - there is a single water block near by that might be causing an issue (it was originally to moisturise the dirt before I added the water source for the pump and cloche setup (which is all new)?

It might be necessary for me to split this into a different bug if you prefer but I tried a bunch of other vegetables and seeds in the cloche and nothing seems to work (so maybe I've set it up wrong - I'll get screenshots next time I'm playing - though I've followed all the instructions primarily from the book and then from the FTB website and another site I found on how to get it to work - I should note that the water bar is full as is the power bar...)

**Comment by BluSunrize** [comment]
Yeah honestly, you should just provide screenshots.
Point stands, neither cloche nor pump in IE cause changes to farmland blocks or anything, so I don't think this is a valid issue until proven.

**Comment by PhoenixRiver** [comment]
![2018-03-18_09 44 57](https://user-images.githubusercontent.com/5155303/37564612-71c9d6c0-2a91-11e8-9f4a-4436df5a613c.png)
![2018-03-18_09 45 31](https://user-images.githubusercontent.com/5155303/37564614-77a29e10-2a91-11e8-917b-9a729453c342.png)

**Comment by PhoenixRiver** [comment]
Okay, I have tried to reproduce this and haven't got there yet... will keep going and report back if it's possible (also renamed issue to better reflect what this is breaking down to).

**Comment by CplPibald** [comment]
@PhoenixRiver I don't see any torches nearby in that screenshot.  Is it possible the crops are popping up in that corner because they don't have enough light?  This is the most common reason for crops to pop out.

**Comment by PhoenixRiver** [comment]
I'll check the light level but I there was before the belljar was
there so... *shrug* Will get back to you.
