### ISSUE TITLE
[1.12] Assembler won't craft Recipes added via CraftTweaker

### ISSUE THREAD

**Issue by p4di** [BluSunrize/ImmersiveEngineering#2885]
### Description of the issue:
I'm currently trying to add some crafting recipes to the game via CraftTweaker that I ultimately want the Assembler to craft. The dummy recipes I created work with a vanilla crafting table, however they aren't working with the Assembler. It recognizes the outcome of the recipe but won't craft it (greyed out) even though it has enough of all ingredients. I initially thought it had something to do with fluids, but a recipe involing only "normal" blocks didn't work either.

Screenshots:
https://imgur.com/a/Jp5oK

CraftTweaker recipes:

recipes.addShaped("liquid_liquid3",<minecraft:obsidian>,
 [[<minecraft:lava_bucket>,<minecraft:water_bucket>,null],
  [null,null,null],
  [null,null,null]]);
  
 recipes.addShaped("liquid_liquid4",<minecraft:obsidian>,
 [[<minecraft:stone>,<minecraft:cobblestone>,null],
  [null,null,null],
  [null,null,null]]);

### Crashlog:
forced crashlog: https://pastebin.com/zLirGgm2

### Versions & Modlist
MC: 1.12.2
Forge: 14.23.2.2627
IE:  0.12-78   
modlist: https://pastebin.com/pAf8Ug7D

**Comment by bookerthegeek** [comment]
Could you also post the `crafttweaker.log` to gist please.

**Comment by p4di** [comment]
CraftTweaker Log: https://gist.github.com/p4di/450f347adbbfe78cf9092792beee72a5

**Comment by bookerthegeek** [comment]
Odd, Please post the complete to gist:
- `liquid_liquid.zs`
- `log.zs`
- `anti_ice.zs`
- `c_zehn.zs`

**Comment by p4di** [comment]
**liquid_liquid.zs:** https://gist.github.com/p4di/94cc4e6d80811365c504665858677cd1
**log.zs:** https://gist.github.com/p4di/53d154517c2ce543a99adb74bcd3c3e4
**c_zehn:** https://gist.github.com/p4di/afdba84a64cfdeae21b3f59451f7b8a3
**anti_ice**: https://gist.github.com/p4di/ab3eff81039ca9022fb25d199e8850dd

I started using craftTweaker just yesterday,

**liquid_liquid:** was me trying to create a shapeless liquid-block recipe and when it didn't work with the Assembler, I tried a block block recipe. Both didn't work, then I made them comments and tried shped recipes instead, which didn't work either. Note that all recipes worked with a vanilla crafting table.
**log.zs** was basically the first script I tried out
**anti_ice** is a tutorial block from ContentTweaker - works in game
**c_zehn** is a test fluid I added - works in game, even worked with Immersive Petroleum Distilation Tower.

**Comment by bookerthegeek** [comment]
Very weird. I can confirm it is not working and it should be. Sorry I could not find a fix in your scripts. Time now to wait for the coders to resolve the issue. 

Also, a [Clean Script](https://gist.github.com/bookerthegeek/86f952b0179bbd9ab1b2917b5d098d5e) for them to test with if they like.

**Comment by p4di** [comment]
welp, thanks for your help though!

**Comment by BluSunrize** [comment]
While it doesn't work with input fluids, I have no problems getting it to work with items, as shown here:

![image](https://i.imgur.com/SdwxxCo.png)

The reason it doesn't work with fluids is because we moved to using fluid ingredients and your recipes are looking for the bucket items specifically, but with the items I'm able to get it working just fine.

**Comment by p4di** [comment]
strange, did you use the same script I did?

**Comment by BluSunrize** [comment]
Yep, I used the two respective bits that add the relevant recipes.
I chose to ignore changes to ice and the custom fluid, as they did not seem relevant to the issue.

**Comment by p4di** [comment]
okay, still isn't working for me. I guess IE is not the problem then

**Comment by bookerthegeek** [comment]
@BluSunrize would it be possible for you to post the script you used that worked, along with an example of fluids working please?

**Comment by BluSunrize** [comment]
`
recipes.addShaped("liquid_liquid3",<minecraft:obsidian>,
 [[<minecraft:lava_bucket>,<minecraft:water_bucket>,null],
  [null,null,null],
  [null,null,null]]);

recipes.addShaped("liquid_liquid4",<minecraft:obsidian>,
[[<minecraft:stone>,<minecraft:cobblestone>,null],
 [null,null,null],
 [null,null,null]]);
`
It's literally just this (and a crapload of commented out lines of me testing IE's internal craftweaker compat)

Recognizing items to be Fluid containers was actually partially bugged, I fixed that bit, but items worked fine for me before that.

**Comment by p4di** [comment]
I used the exact same script. still greyed out and won't work in the assembler. Is there something I (and probably @aaronhowser1 and @bookerthegeek too) are missing? Does something need to be imported at the start of the script?

I only used the 3 neccessary mods:
IE-core version 0.12-79
IE version 0.12-79
CraftTweaker2-1.12-4.1.6

Forge: 14.23.2.2629
Java Version: 1.8.0_162

full crash report: https://gist.github.com/p4di/33db930cabb7564317d8e27cb0bb7f48#file-crashlog

**Comment by BluSunrize** [comment]
Out of interest: Can you get other recipes to craft? Something simple like sticks?

Oh, also, break the assembler once and remake it, existing Multiblocks got derped up in Build 79

**Comment by p4di** [comment]
yes, I always tried out whether sticks would work and they did.

I just made a new world, only build the asssembler and it still didn't work :/
previously I usually broke one block of the assembler and remade the multiblock also.

**Comment by Paul17041993** [comment]
might there be a relation here with #2655 ?

**Comment by acook** [comment]
I have a CraftTweaker recipe which works fine with Tinkers' Construct crafting station and the vanilla crafting table but not with IE's Assembler. The recipe uses Mob Grinding Utilities XP Fluid (`xpjuice`) and I suspect that is the issue. I can create a modpack with configurations for IE and MGU with the CT script if it would help.

**Comment by tofof** [comment]
I'm still seeing this on:

ImmersiveEngineering-0.12-82
ImmersiveEngineering-0.12-82-core
CraftTweaker2-1.12-4.1.8
forge-1.12.2-14.23.4.2707
minecraft 1.12.2

**Comment by Golrith** [comment]
A player of my modpack is also seeing this issue. Any recipe I've added/adjusted via Crafttweaker, the assembler does not want to know. Any untouched recipe is fine. Recipes being tried do not involve fluids.

ImmersiveEngineering-0.12-87.jar
CraftTweaker2-1.12-4.1.13.jar
