### ISSUE TITLE
[Request] Assembler

### ISSUE THREAD

**Issue by bookerthegeek** [BluSunrize/ImmersiveEngineering#2886]
## Heyo ##
How are you fine peoples doing today?

### Description of the issue:
Since it seems that the code for the Assembler is going to be looked at soon... Is there any chance of being able to add CraftTweaker integration to it for recipes that are to be mechanically assembled only?

### Versions
This of course would be for Minecraft 1.12.2

**Comment by BluSunrize** [comment]
No, because that is not the point of the assembler. It's an autocrafting machine that is supposed to handle vanilla crafting recipe. It's not meant to feature exclusive recipes, as explained on previous occasions.
