### ISSUE TITLE
Client Crash - NPE Tesselating block model 	at com.google.common.base.Preconditions.checkNotNull

### ISSUE THREAD

**Issue by ProsperCraft** [BluSunrize/ImmersiveEngineering#2887]
### Description of the issue:
Walked through my base and BAM, crashed, I was not interacting with anything.

### Crashlog:
https://gist.github.com/ProsperCraft/d14261b7ec615de381682c9e29d61780

It would appear that I had the same issue in 1.10.2 and it was closed without comment.
https://github.com/BluSunrize/ImmersiveEngineering/issues/1677

### Versions & Modlist
ImmersiveEngineering-0.12-78
See crashlog for full list.

**Comment by BluSunrize** [comment]
Are those already in Malte or do you need to add them still? I'm in the process of wrapping up here

**Comment by malte0811** [comment]
Should be there in ~15 minutes (unless something gets in the way).

**Comment by ProsperCraft** [comment]
I do not have Optifine in my client.

I didn't have optifine in 1.10.2 either.

**Comment by malte0811** [comment]
I've implemented a workaround, the crash shouldn't happen in IE 79. However there may be significant lag in situations that would have crashed before, so this isn't ideal.
With IE 79, please enable the `enableDebug` config option (should be possible with the in-game GUI now). That should cause a crash at the same point as before, but with a lot more useful information. Once you have that crashlog please upload it here.
