### ISSUE TITLE
0.5.2 Arc Furnace

### ISSUE THREAD

**Issue by LazerusKI** [BluSunrize/ImmersiveEngineering#289]
The Shape was changed from 0.5.1 (two additional steel blocks), but now in 0.5.2 it wont form anymore.
tried it with both versions, in 0.5.1 it works (crashed me once because i forgot to remove the additional blocks), but in 0.5.2 neither of them forms.

**Comment by cobra** [comment]
Works perfectly fine for me. Please check again, layer by layer, if your block placement is correct. When in doubt, post screenshots.

**Comment by LazerusKI** [comment]
Just a few minutes, im uploading a video

**Comment by LazerusKI** [comment]
https://youtu.be/0V2OLXcv74k

**Comment by theunkn0wn1** [comment]
Unable to reproduce, tested with both building from source (ebafdeb4a33abbda8b5a673e9277d3c3d81d04bb) and the Curse upload.
I reproduced your steps shown in writing and video *exactly* and did not encounter the issue.
Video of my test: https://www.youtube.com/watch?v=aJahNzrXvOg

**Comment by LazerusKI** [comment]
Very weird...
could it be, that it is broken when you upgrade from 0.4 to 0.5.2? because thats what i did first.
after downgrading to 0.5.1, building it there, and then upgrading to 0.5.2 it works

**Comment by theunkn0wn1** [comment]
That is a possibility due to API changes made... I still have those old
binaries in archive, will test this hypothesis when I have the opportunity.
Though if that hypothesis is correct I do not see anything BluSunrize could
do about it...

**Comment by TheQuantumGeneral** [comment]
I am having the same issue, book says I need 25 steel blocks but the picture shows me needing 23.

**Comment by BluSunrize** [comment]
Version 0.5.2 should have fixed the ArcFurnace as far as I'm aware.

**Comment by jjjworley** [comment]
Will the Arc Furnace not form when Railcraft steel blocks are the default? If so, do you know how to make your steel blocks and steel slabs default? I'm using 0.5.3.2. Thanks for the mod. I absolutely love it!!

**Comment by BluSunrize** [comment]
it will work with other steel blocks, but not steel slabs, since they are not OreDicted, so I can't check against them...
