### ISSUE TITLE
[Bug] Multiblocks dropping themselves and the broken block

### ISSUE THREAD

**Issue by Lorelando** [BluSunrize/ImmersiveEngineering#2891]
When breaking (I think any) multiblock, it drops itself plus the broken block. I have tested this with a crusher, metals press, arc furnace, squeezer, mixer and diesel generator. (It also appears that you have to rebuild all powered multiblocks for them to work).

![2018-03-19_11 18 04](https://user-images.githubusercontent.com/19599163/37590157-b4041b1e-2b67-11e8-9d64-9e7f1cc47707.png)

The dropped multiblock can be placed again like this:

![2018-03-19_11 18 42](https://user-images.githubusercontent.com/19599163/37590159-b63790e6-2b67-11e8-84c1-3ddeb735d580.png)

Minecraft 1.12.2
Minecraft Forge 14.23.2.2611
Immersive Engineering 0.12-79
[Full Modlist](https://gist.github.com/Lorelando/21b906cdec00130db1eab14b1e015150)

**Comment by BluSunrize** [comment]
Do you have any other mods installed? If so, full modlist with versions please, and try to replicate this issue with just IE installed

**Comment by Lorelando** [comment]
This is done in a clean testing environment.

**Comment by malte0811** [comment]
Probably caused by e69809789a767f549a35e01a67778c3e5843e482.

**Comment by ProsperCraft** [comment]
This started right after this last update, ImmersiveEngineering-0.12-79

![2018-03-19_14 03 53](https://user-images.githubusercontent.com/4427684/37619391-f577f784-2b7e-11e8-8d40-d06669608996.png)
I got three from the bucket wheel I broke.
![2018-03-19_14 04 16](https://user-images.githubusercontent.com/4427684/37619413-0c98cd6c-2b7f-11e8-843c-a34bb937925f.png)

When you place them they are a single invisible block.

![2018-03-19_14 03 50](https://user-images.githubusercontent.com/4427684/37619404-062670ba-2b7f-11e8-8235-4e92f60fc00f.png)

**Comment by Wotzinator** [comment]
i dont know if it helps but i had a simliar problem the coke oven dropped itself and you could not extract the
creosote oil .

**Comment by BluSunrize** [comment]
The fix is released now
