### ISSUE TITLE
[Bug] Multiblocks build in older versions not working until they are rebuild

### ISSUE THREAD

**Issue by Lorelando** [BluSunrize/ImmersiveEngineering#2892]
All multiblocks that require power (eg. tanks are still working) and have been build in 0.12-78 will have to be broken (just breaking one block is enough) and rebuild for them to work.

(Mainly reporting this so the fix is known)

Minecraft 1.12.2
Minecraft Forge 14.23.2.2611
Immersive Engineering 0.12-79
[Full Modlist](https://gist.github.com/Lorelando/f9e9146074cbe1ce5076cee796b9a0cf)

**Comment by BluSunrize** [comment]
@malte0811 what's the chance the booleans for computer control did that? =P

**Comment by malte0811** [comment]
100%. Seems like I didn't think about backwards compatibility when I wrote that. Sorry.
