### ISSUE TITLE
Metal Scaffolding Missing In JEI

### ISSUE THREAD

**Issue by ilhamsitok** [BluSunrize/ImmersiveEngineering#2897]
I Couldn't Provide much information except this image
https://imgur.com/a/4QZ9I
and the midlist
https://pastebin.com/hPzRtHhJ

**Comment by BluSunrize** [comment]
You could have provided the debug crash like the contribution guidelines requested, or like, any description of the issue rather than a screenshot. Took me a few moments to even realize what the problem was.

**Comment by ilhamsitok** [comment]
my apologies, there was basically a problem that immersive engineering metal scaffolding is missing, it didn't crash just scaffolding is missing in jei. i try to remove optifine but that didn't fix it

**Comment by BluSunrize** [comment]
You still didn't provide the debug crash.

Also, I cannot reproduce this issue, so I'm suspecting cross mod interaction. Please attempt a binary search by removing half of your mods and seeing if the issue persists, then splitting that half further and further until you identify the mod that causes it.

**Comment by ilhamsitok** [comment]
whoops, chisel or ctm is the problem, sorry for disturbing you and thanks for the great mod
