### ISSUE TITLE
Blast Furnace broken

### ISSUE THREAD

**Issue by Moxiesan** [BluSunrize/ImmersiveEngineering#2898]
Forge version: 14.23.2.2624
IE version: 0.12 - 79

The blast furnace is not accepting iron buckets into it to withdraw oil. I am not sure about other fluid containers, but another member on the project page on curse mentioned other containers not working as well.

**Comment by BluSunrize** [comment]
That would be because the Blast Furnace doesn't produce oil...?

**Comment by Moxiesan** [comment]
Sorry, that was not the correct name. Blast Oven and Creosote Oil (there's 7000mb in it now)

**Comment by BluSunrize** [comment]
yeah, looking into it atm.

**Comment by Moxiesan** [comment]
Cool, thank you!
