### ISSUE TITLE
Connectors lose connections - on server restart?

### ISSUE THREAD

**Issue by BarbasTheDog** [BluSunrize/ImmersiveEngineering#29]
Happened twice already, both times with LV connections. Last time I assumed it was because we updated, but now it happened again without changing versions.

The area is a Mystcraft age and is loaded with a ChickenBones chunkloader. It -may- have to do with the server restarting. I can't prove it though, since I hadn't been on for a few days, and the server restarts once a day, so I didn't notice it immediately.

http://i.imgur.com/O5pYxd9.png

It's *not* just visual - power isn't transmitted and coils don't drop upon breaking the connections.

**Comment by BarbasTheDog** [comment]
We just forced a reboot, and that was it. Wires are gone.

**Comment by tjsd** [comment]
What is this "we" ? It is stated that if you can compile the mod you are allowed to test it, but this sounds like something running on a server with several people. I am pretty sure that goes against the wishes of BluSunrize.

**Comment by BluSunrize** [comment]
He's got a point. While Barbas does have my decompiled version (since he knows where to get it), running a server isn't really intended >_>

I can't reproduce this on an SSP client, I'll check it on a server later.

**Comment by BarbasTheDog** [comment]
Oh, I'm not putting it on the web or anything. >.>
I have a 3GB server I normally play SP or co-op with an IRL friend on (since my laptop isn't the greatest). "We" is because he's been playing with me and testing IE for the past few days.

About the bug: I suspect it has to do with Mystcraft. I had an overworld flat test-world before this one and it worked fine. And maybe it also has to do with the fact that ChickenChunks forces Mystcraft to load ages with chunkloaders on them upon the server starting.

**Comment by BluSunrize** [comment]
hmmm
Might be due to the MystAge getting loaded before the overworld .~.

**Comment by BluSunrize** [comment]
Yeah I think I found the bug and fixed it for Version 0.1.14
