### ISSUE TITLE
Arc Furnace Suggestion

### ISSUE THREAD

**Issue by LazerusKI** [BluSunrize/ImmersiveEngineering#290]
While automating one in the 0.5.1 version (since 0.5.2 wont form), i noticed that the furnace stacks ores automatically, even if there are empty slots left.

Sadly, this means that it can only smelt one item at a time from a whole stack, wasting a lot of potential.

So, would it be possible to let it check for "empty slots", for example you have one stack of Iron Ore in it and 12 empty slots, and when it detects them, it will use these 12 to smelt 12 additional Iron Ores instead?

Also: is it wanted that it cant smelt Dust/Grit?

**Comment by BluSunrize** [comment]
It does form in 0.5.2, the structure just changed. It needs 2 extra blocks. I'll look into equal processing
