### ISSUE TITLE
MC 1.12.2 IE Version 0.12-79 Capacitor Backpack Issues

### ISSUE THREAD

**Issue by Tedyhere** [BluSunrize/ImmersiveEngineering#2900]
MC 1.12.2
IE 0.12-79
Forge .2627

Unable to craft the Capacitor backpack with any Vanilla armor or with the Faraday Chestplate is this intended behavior now?

Using this on the FTB Continuum Alpha modpack

**Comment by Lorelando** [comment]
Duplicates  #2892.

**Comment by BluSunrize** [comment]
Works fine for me, can you reproduce it in an instance with just IE?

**Comment by BluSunrize** [comment]
Additionally, I can't find Continuum anywhere, so you know, modlist, debug crash, etc.
Possibly the Minetweaker scripts too, if you can get them.

**Comment by Tedyhere** [comment]
Modlist is big, it's still in Alpha.  I will get all relevant info for you today.  I will ask tfox if I can send you the scripts. I will also test in a IE only world.  Give me a few hours.

**Comment by Tedyhere** [comment]
Testing in a clean world with just IE mods, it works fine.  I will let tfox know and do more testing on what mod is causing the issue.  Sorry to take up your time on this.

**Comment by BluSunrize** [comment]
Good luck!

**Comment by Tedyhere** [comment]
I found the interaction that's causing the issue.  new mod from McJty that's not released yet that's the basis for crafting in the modpack. EFab, I've let him know about it and he's confused as to why it's causing an issue.  So if you want to get together with him to find out.  Now you know.  I'm closing this issue now.

**Comment by malte0811** [comment]
The source code for EFab seems to be available, so debugging should be doable. Did you try to craft the backpack in one of EFab's machines or in a normal crafting table (no clue how ftb continuum works)?

**Comment by Tedyhere** [comment]
I crafted the Backpack via normal crafting, it isn't in the efab crafting system.  The faraday armor was also not in the efab crafting system.  No armor works at all with the backpack.. it's very odd

**Comment by malte0811** [comment]
@McJty I guess this is caused by returning a completely different item in `getRecipeOutput` than in `getCraftingResult`. The EFab system (and its wrapper for standard recipes) doesn't seem to handle that situation very well ([this](https://github.com/McJty/EFab/blob/1.12/src/main/java/mcjty/efab/blocks/grid/GridCrafterHelper.java#L62) line probably causes issues in that case).
I don't know whether doing this (returning completely different items) is a bad idea in general, the only alternative here would be adding a whole lot of recipes in code as this has to work with close to any chestplate, modded or vanilla. 
I also don't know how either EFab or FTB Continuum work from an in-game perspective, is there any chance this crafting attempt is actually handled by your system rather than the vanilla one?

**Comment by McJty** [comment]
But how is this relevant if it is not being crafted in the efab? @Tedyhere mentioned simply having efab present prevents it from working even in the vanilla crafting table? Then my wrapper isn't used

**Comment by malte0811** [comment]
It doesn't happen for me with IE somewhere between build 79 and latest (414c36c6ab25d92c07af13e455f9e14a288951a5) and EFab built from the 1.12 branch (McJty/EFAB@96d7a620dd7131459afa056ef2b60b2531dec20e). The IE side shouldn't have any relevant changes AFAIK, is that the same EFab version as in FTB continuum?
@Tedyhere does it happen for you with just IE and EFab? If it does, post some screenshots (might be useless, might help).

**Comment by McJty** [comment]
yes that's the same EFab which is now in the pack

**Comment by malte0811** [comment]
You seem to have access to the pack. Could you try whether you can replicate the bug? It doesn't happen for me with the versions mentioned above.

**Comment by Tedyhere** [comment]
I'll check in a bit before I record an episode

**Comment by Tedyhere** [comment]
Ok with JUST EFab and no recipes modified using it.. Everything works as intended..

**Comment by Tedyhere** [comment]
It's not a recipe issue.. if I pull the items out via creative they still don't work as intended.  More testing is needed.

**Comment by Tedyhere** [comment]
It looks like it's possibly an issue with IE 79 and Current IP? Which unpacks IECore 78.. doing another test to be sure.

**Comment by helldragger** [comment]
Same problem here, still unable to combine any armor with the capacitor backpack

**Comment by malte0811** [comment]
This is on FTB's side (one of their CT scripts), see FTBTeam/FTB-Continuum#89.
