### ISSUE TITLE
[1.12.2] Unable to take creosote oil out of coke oven with buckets

### ISSUE THREAD

**Issue by Ash70** [BluSunrize/ImmersiveEngineering#2901]
### Description of the issue:
The bucket slot of the coke oven does not allow me to put in a bucket.

### Versions & Modlist
IE 0.12-79
Forge 2624
I tested this on a clean instance with just IE (and JEI 4.8.5.159)

**Comment by BluSunrize** [comment]
Has already been fixed for next release
