### ISSUE TITLE
[Bug]Barrels unable to extract the creosote oil from the coke oven

### ISSUE THREAD

**Issue by mickwok** [BluSunrize/ImmersiveEngineering#2903]
Description : 
Due to the bug that i can't put bucket in the coke oven , i tried to use the metal barrel to pull out the liquid , but it didn't work. The barrel remains empty.

Modlist: 
Immersive Engineering 0.12 - 79
Forge 14.23.2.2632

**Comment by BluSunrize** [comment]
Barrels can't pull.
Show pictures of your setup please.

**Comment by TheCowKing-moo** [comment]
Having the exact same issue as mickwok. 

[pictures](https://imgur.com/a/jMU6o)

The coke oven wont let me insert a bucket into the insert slot. Also clicking the bucket on the coke oven does not extract anything (cant remember if it was able to do that). 

Using any other tank/bottler seems to work fine.

IE:0.12-79
Forge: 14.23.2.2617

**Comment by bookerthegeek** [comment]
@TheCowKing-moo please when posting a mod list include the complete mod list and not just this mod.

**Comment by TheCowKing-moo** [comment]
Could not replicate the issue with IE and Forge only installed. 

Creosote bucket is not searchable in JEI. By pressing "u" on the creosote fluid (immersive engineering creosote) in JEI I can find a creosote bucket shown [here](https://imgur.com/a/zm2rk). Pressing "r" unfortunately shows me every fluid forge took over (sorry new to 1.12 not sure if that's whats supposed to happen). 

If I pump the creosote to a barrel I can click on the barrel with a empty bucket and get a bucket of creosote.  

[Modlist](https://pastebin.com/MGhAJfEw)

The fact that I can still get buckets of creo from the barrel is throwing me off and I'm not sure what to look for/what else to do. I did notice that even though I have all the thermal mods installed I don't see thermals creosote in JEI.

**Comment by mickwok** [comment]
It works fine now with pump , i am a noob , sorry about that.

**Comment by BluSunrize** [comment]
Plus, the bucket issue is fixed, go update IE.
