### ISSUE TITLE
Request: Ability to configure fertilizer options for Cloche

### ISSUE THREAD

**Issue by 666lumberjack** [BluSunrize/ImmersiveEngineering#2904]
### Description of the issue:
It would be really useful as a modpack developer to be able to configure which materials are able to be used as fertilizer in the Garden Cloche - for example if you're using a fairly niche mod that isn't natively supported, or you want to restrict the available options to only some relatively hard-to-manufacture option.

### Version
0.12-79

**Comment by BluSunrize** [comment]
Fertilizers technically aren't just entries of item->number, but Interface implementations, aka a more complex piece of code that allows for dynamic numbers on the fertilizer (to allow specific fertilizers to work better on certain things for instance). Replicating that for CraftTweaker is basically impossible.

I may look into a simple, number based system in the future, but atm it's not a priority.
