### ISSUE TITLE
Coke Oven and Buckets

### ISSUE THREAD

**Issue by TheCowKing-moo** [BluSunrize/ImmersiveEngineering#2905]
The coke oven wont let me insert a bucket into the insert slot. Also clicking the bucket on the coke oven does not extract anything (can't remember if it was able to do that).

[attempt at putting bucket in](https://imgur.com/a/jMU6o)

IE:0.12-79
Forge: 14.23.2.2617
[Modlist](https://pastebin.com/9GaZZ35t)

Could not replicate the issue with IE and Forge only installed.

Creosote bucket is not searchable in JEI. By pressing "u" on the creosote fluid (immersive engineering creosote) in JEI I can find a creosote bucket shown here. Pressing "r" unfortunately shows me every fluid forge took over (sorry new to 1.12 not sure if that's whats supposed to happen).

If I pump the creosote to a barrel I can click on the barrel with a empty bucket and get a bucket of creosote.

The fact that I can still get buckets of creo from the barrel is throwing me off and I'm not sure what to look for/what else to do. I did notice that even though I have all the thermal mods installed I don't see thermal's creosote in JEI.

Any input would be greatly appreciated!

**Comment by BluSunrize** [comment]
Update IE.

**Comment by TheCowKing-moo** [comment]
Works great now. Thanks!
