### ISSUE TITLE
Request: Change Crate GUI texture; poor legibility

### ISSUE THREAD

**Issue by darchitectlp** [BluSunrize/ImmersiveEngineering#2907]
Right now the crate texture uses your treated wood as a background for the GUI. It's incredibly difficult to read/see items against. I find myself avoiding what is actually a really useful block just because its interface makes it painful to use. I would respectfully suggest you explore a more reserved/neutral texture.

Thank you for a fantastic mod.

**Comment by Seegras** [comment]
The same applies to the kiln, the blast furnace and the coke furnace and so on. would suggest to completely abstain from custom textures for the GUI.
- It makes them badly readable and painful to use
- It breaks the immersion actually, with all the different GUI styles.

Please make it at least configurable, so we can turn it off.

**Comment by mallrat208** [comment]
You can turn it off. It's called a resource pack.

**Comment by BluSunrize** [comment]
I also didn't make that art. You'll have to take it up with the artist themselves :V

**Comment by darchitectlp** [comment]
Great, are you looking for a new artist? I'll gladly make you a new GUI background.

**Comment by darchitectlp** [comment]
Sorry, who is Hazard? Isn't this your repository? Regardless of who made the art first, it doesn't work from a legibility aspect. Hard to see items; hard to read text. If you can't be bothered, though, I totally understand. A resource pack can fix it, as mentioned. Just wanted to see a more thorough fix for it. Thanks!
