### ISSUE TITLE
(1.12.2) Potion Compatibility Issues With Mixer and Bottler

### ISSUE THREAD

**Issue by TechnoMysterio** [BluSunrize/ImmersiveEngineering#2908]
### Description of the issue:
After doing some testing with the Mixer and Bottler, I've noticed that Immersive Engineering tends not to get along with other mods' potions. Certain mods are fine, probably because they only add one or two simple potions, but mods such as CoFH Core and Extra Alchemy do not work well with the Mixer and Bottler. I'll give a quick rundown of what I've noticed:

The mixer can only make potions that use an awkward potion for their base. Potions that use a mundane or thick base can't be made with the mixer, and custom potion bases (such as Extra Alchemy's charged potion) do not seem to be available to be made or used. Splash and lingering potions may be problematic as well, but I didn't get the chance to test them, so that requires further information.

(Side note for the Mixer, I cannot seem to take items out of it unless I shift click them, normal clicking does nothing, even if the machine has stopped and is not processing anything)

The bottling machine is also troublesome in that it only bottles very specific potions, mainly vanilla and one or two other modded potions. CoFH Core and Extra Alchemy's potions cannot be bottled at all, even if they can be made with the mixer. Also of note is that water cannot be bottled for some reason (if it could, I imagine it'd create problems with mods like Tough as Nails and it's thirst and water filtering system anyway, so this doesn't matter so much).

Also, is the mixer supposed to make four potions per ingredient? I'm just wondering if this isn't an problem with each bottle taking 250mb instead of 333mb as it did previously, but I do actually think this works well, as a larger, more expensive machine should work as an upgrade to the normal brewing stand.

This is what I've noticed so far, but I'll make sure to let you know if there are any other problems. Here's some notable mods with potions in them:

Mods with potions that worked fairly well:
Cyclic
Random Things
Quark

Mods with potions that didn't work well:
CoFH Core
Extra Alchemy

Mods with potions that need further testing:
Inspirations
Tough as Nails
NetherEx

### Versions & Modlist
MC: 1.12.2
IE: 0.12-80
Forge: 14.23.2.2634

**Comment by winsrp** [comment]
I think this could be fixed with a config options that works the following way

We can specify, fluid, a container and a result.

So if we set fluid:water, container:empty bottle, result:dirty water bottle, then the bottler will just check if the condition is matched and it will return the bottle as we speak

So all normal fluids (and some compatibility fluids that you already have), could be set in this file as a working example, and if we need to add more we just add them to the config.

**Comment by mindforger** [comment]
@winsrp https://crafttweaker.readthedocs.io/en/latest/#Mods/Immersive_Engineering/CraftTweaker_Support/Mixer/

**Comment by winsrp** [comment]
@mindforger 
interesting, but wouldn't it be cool if that was like a standard feature?, I know sounds like the same thing but it is a 'little bit" more complicated to understand for the average user, and I don't want to think just in myself for this solution.

**Comment by mindforger** [comment]
Craftweaker is a mod supported by a lot of mods just because it would be a hell if you'd have to change every single mod

**Comment by winsrp** [comment]
Oh don't get me wrong I'm on my way to give it a try, but still, flexibility is nice right from the core.

**Comment by winsrp** [comment]
@mindforger worked wonders thanks.

As reference is someone needs the same thing, you need to add a script.zs file to the scripts folder with the following line for Tough As Nails mod

`mods.immersiveengineering.BottlingMachine.addRecipe(<toughasnails:water_bottle>, <minecraft:glass_bottle>, <liquid:water>);`

This will make the bottler make you a dirty water bottle from inputing water and a bottle to the machine.

**Comment by bookerthegeek** [comment]
For anybody having this issue, let me k ow the mods with the issue and ill post a script up on curse under the modifications settings for their potions.

**Comment by BluSunrize** [comment]
So the (totally unrelated) Tough as Nails thing aside:

@TechnoMysterio 
Yes, the choice of 250mB per potion was deliberate, both to make the mixer more attractive and to save the problem of having 1mB left over after filling.

Could you please provide examples of potions added by CoFH Core? I'm not familiar which ones they add, so I'll need mroe details to provide compatability.
Could you also please detail which kind of compatability is lacking for the respective potions, whether it's just bottling or mixing as well?

**Comment by TechnoMysterio** [comment]
Here's Team CoFH's wiki with a list of potions from CoFH Core: https://teamcofh.com/docs/cofh-core-potions/

And the recipes that make them from Thermal Foundation: https://teamcofh.com/docs/tf-potion-recipes/

CoFH Core also adds higher tier potions (up to level 5 or so), but those are irrelevant as they can only be made with a specific TE machine.

It varies a lot which potions can be made/bottled, but from what testing I've done:

- CoFH Core potions can be made but not bottled
- Extra Alchemy potions cannot be made at all (awkward base, mundane base, thick base, charged base, anything), and I don't think they can be bottled, as no recipe to bottle them shows up in JEI. Extra Alchemy does overhaul the brewing system, so I imagine it doesn't mesh well with IE
- NetherEx potions can be made but not bottled
- Quark, Cyclic and Random Things all work perfectly well
- Haven't been able to test TaN's temperature resist potions and Inspiration's potions

**Comment by TechnoMysterio** [comment]
Managed to test Tough as Nails' temperature resistance potions: they cannot be made or bottled. Not sure what the makes the difference with other mods' potions, but alternate brewing methods from other mods seem to work fine overall, like with Inspirations' cauldron brewing and Thermal Expansion's Alchemical Imbuer.

**Comment by TechnoMysterio** [comment]
Right, realised I probably should have tested Inspiration's potions some time ago, so I did some testing just now. It seems they can be made but not bottled. 

Now, I am aware that this thread has been somewhat buried underneath many others, and therefore has not been particularly active. As such I shall invoke the mystical 'at' symbol in attempt to summon someone to look over what I have found, ahem... @BluSunrize 

No idea if that did anything, but it's worth a shot.

**Comment by KnightMiner** [comment]
By the looks of things, IE is registering the recipes to fill potions using fluids before init, meaning some mods (like inspirstions)  have not even added their potions yet. As for the actual crafting, it seems that is a dynamic recipe using the potion helper, meaning some mods (like TAN) that use the forge brewing registry are skipped.

The way I handle potion recipes in inspirations is basically the opposite. My recipe to bottle a potion from a fluid is dynamic, detecting the fluid to fill the bottle. I have static recipes for the individual potions which I fill in post init from both the potion helper and the forge brewing registry.

**Comment by TechnoMysterio** [comment]
Right, seems this issue is very much buried, so I'll close it, and perhaps I'll open another.
