### ISSUE TITLE
[1.12 - 0.12-80] LV Wire/conection not transmiting power

### ISSUE THREAD

**Issue by Monty1991** [BluSunrize/ImmersiveEngineering#2909]
### Description of the issue:
LV wire conectors/wire not transmiting power

### Reproduction:
Make a waterwheel / thermo generator, conect to any power machine/ capacitor, using LV conections. They do not transmit power (waila and others reporting 0 voltage), and also, machines do not work. However, using a HV conection, everything works normal.
#Update: Also, MV conection works fine. The issue is entirely over the LV conection.

### Versions & Modlist
IE version: 0.12-80
Forge version: 14.23.2.2611

Complete Modlist:
  Aroma1997Core-1.12.2-2.0.0.0.b148
  AromaBackup-1.12.2-2.1.1.3.b94
  AutoRegLib-1.3-15
  BetterAdvancements-1.12.2-0.0.5.17
  BetterBedrockGenerator-1.12-6.1.1
  BetterFps-1.4.8
  blockdrops-1.12.2-1.4.0
  blocks2items-1.12-1.7
  Ceramics-1.12-1.3.3b
  ClientTweaks_1.12-3.1.2
  CodeChickenLib-1.12.2-3.1.6.339-universal
  CraftingEX_1.12-v1.2.0
  CraftTweaker2-1.12-4.1.6
  cttinycoal-1.12.2-1.0.2
  CTM-MC1.12-0.2.3.9
  easiervillagertrading-1.12-forge14.21.1.2387-1.2
  ExCompressum_1.12.2-3.0.20
  exnihilocreatio-1.12-0.1.7.63
  externaltweaker-1.12-0.3
  ExtremeReactors-1.12.2-0.4.5.46
  FlatBedrock-1.4.0_1.12
  flour-1.0.0
  GoGSkybox 1.1-3
  gigaherz.commons-1.12.1-0.6.4
  Guide-API-1.12-2.1.5-58
  Guidebook-1.12.2-2.0.1
  HammerCore-1.12.2-1.9.7.0
  Harvest-1.12-1.2.3-15
  harvestables-1.2.1
  ImmersiveEngineering-0.12-80
  immersivetech-1.12-1.3.6
  ImmersiveEngineering-0.12-80-core
  infinitefluids-1.11-1.2.0
  InventoryTweaks-1.64-dev
  jeivillagers-1.12-1.0.2
  justenoughbuttons-1.12.2-1.2.2-5
  justenoughdimensions-1.12.2-1.6.0-dev.20171225.032648
  jei_1.12.2-4.8.5.159
  jepb-1.12-1.2.1
  JustEnoughResources-1.12.2-0.8.7.41
  KleeSlabs_1.12-5.3.2
  EM3R50N-LogicalDrops-1.12-14.21.1.2387
  MCMultiPart-2.4.1
  MineTweakerRecipeMaker-1.12.2-1.2.2.30
  MiscTweaks-1.12-1.3.0
  modtweaker-4.0.9
  MouseTweaks-2.8-mc1.12.1
  MTLib-3.0.4
  NoMoreRecipeConflict-0.10(1.12.2)
  Pam's ClaySpawn 1.12a
  Pam's Get all the Seeds! 1.12a
  Pam's Llama Milking 1.12.2b
  Pam's Sheep Milking 1.12.2b
  Pam's Simple Recipes 1.12.2c
  Pam's Squid Milking 1.12.2a
  ReAuth-3.5.2
  RecipeManipulator-1.12-0.3.1.13
  RedstoneFlux-1.12-2.0.1.2-universal
  ResourceLoader-MC1.12.1-1.5.3
  [1.12] RPG-HUD-3.6.6.2
  SeedDrop-1.2.0-1.12
  soundreloader-1.2-1.12.2
  Tesla-1.12.2-1.0.63
  tinyprogressions-1.12.2-3.3.23-Release
  torohealth-1.12.2-11
  TrackAPI-1.0
  TUMAT-1.12.x-1.12.0
  TS2K16-1.2.8
  UnifiedItems-1.12.2-1.7.3-210
  voidislandcontrol-1.3.2
  Hwyla-1.8.24-B39_1.12
  WailaHarvestability-mc1.12-1.1.12
  WanionLib-1.12.2-1.5
  Wawla-1.12.2-2.5.251
  WIT-1.12-1.0.25-44
  YarrCuteMobModelsRemake-1.0.16-1.12.0
  YUNoMakeGoodMap-1.12-6.3.0.28
  zerocore-1.12-0.1.1.0

**Comment by malte0811** [comment]
Works just fine for me. Screenshots?

**Comment by Monty1991** [comment]
As you can see, the LV conection is "dead". Here are LV and MV in a simple waterwheel to LV capacitor.

![2018-03-25_21 33 56](https://user-images.githubusercontent.com/7476026/37881907-631e347a-3074-11e8-8160-951217b88fc7.png)
![2018-03-25_21 33 58](https://user-images.githubusercontent.com/7476026/37881908-634ca44a-3074-11e8-8f2a-c6f9fcdb9059.png)

I suspect it has to do with the mod Tesla. Is the only mod I have that mess around with energy.

**Comment by malte0811** [comment]
Use LV connectors. Relays won't accept or output power.
