### ISSUE TITLE
[1.12 - 0.12-80] Server Crash related to block collision

### ISSUE THREAD

**Issue by mathesoncd** [BluSunrize/ImmersiveEngineering#2910]
[crash-2018-03-26_00.49.24-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1846307/crash-2018-03-26_00.49.24-server.txt)
[crash-2018-03-26_00.53.42-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1846308/crash-2018-03-26_00.53.42-server.txt)

Server Crash happens only when Immersive Engineering is enabled, and only since updating to release 80.

Thank you for reporting issues, without people reporting them, they wouldn't get fixed. You're helping contribute to this mod and that is much appreciated <3

**Comment by malte0811** [comment]
You seem to have IE core installed, but not IE itself. Is the main IE 80 jar in your mods folder?
