### ISSUE TITLE
[Suggestion] Immersive Ore Processing

### ISSUE THREAD

**Issue by DonMegel** [BluSunrize/ImmersiveEngineering#2912]
I would really love to replace every mod in my mod pack with an Immersive something. First on my list the ability to multiply ore yields. Many methods of ore refinement came into use during the 19th century (time period I associate with IE) and would fit in well I think. The basic premise would be this:

- Ore goes into the Crusher and produces Rubble. 1 Rubble could be smelted to get 2 ingots.
- Rubble goes into the Milling Machine and produces Ore Gravel (Gold Gravel, Lead Gravel, etc). This cannot be smelted.![ballmill](https://user-images.githubusercontent.com/36775215/37929339-bbfc7342-310d-11e8-81ac-2ef6cc853ab2.jpg)
-  Ore Gravel is fed into a Spiral Dust Feeder to produce 3 dusts. Dusts, ofc, can be smelted. ![spiral_zinc_dust_feeder](https://user-images.githubusercontent.com/36775215/37929383-d913a0a4-310d-11e8-95e7-0b34f17915ac.png)
- Dust can then be submitted to the Froth Flotation process. Dust is combined with water and hydrochloric acid. Could possibly use the existing Mixer for this. Each dust produces 1 bucket of ore sludge. Ore sludge cannot be smelted.
-  2 buckets of sludge can be processed in a centrifuge to produce 1 ore powder. 1 ore powder can be smelted to get 3 ingots.
![huntington-mill](https://user-images.githubusercontent.com/36775215/37929781-dfda5170-310e-11e8-873b-a2dccd280dcd.png)

 OR/AND
- 1 bucket of sludge can be processed in an Electrolyzer to yield 1 ore plate. The Electrolyzer would need a great deal of electricity and Chloroauric Acid which is made from a mixture of Nitric Acid, Gold (nugget) and Hydrochloric acid. Each ore plate can be smelted to yield 2 ingots.
![modern_gold_electrolytic_cells](https://user-images.githubusercontent.com/36775215/37929712-b6a1c6c6-310e-11e8-9b32-c6f34f208403.png)

If you do the math then the Crusher turns 1 ore into 2 ingots, the Spiral Dust Feeder turns 1 ore into 3 ingots, the Centrifuge turns 1 ore into 4.5 ingots, and the Electrolyzer turns 1 ore into 6 ingots.

If you do your research you will know that I am combining the processing of multiple minerals into one chain. This is for simplicity as it would be rather cumbersome to have a separate machine and process for Lead and one for Gold, and one for Silver, etc.

I can make the models easily, I am just short on coding knowledge. What do you think? Would this be a worthwhile addition to the IE world?

**Comment by BluSunrize** [comment]
Nope. Not going beyond ore doubling.

**Comment by DonMegel** [comment]
That is, ofc, your call, but may I ask why?

**Comment by BluSunrize** [comment]
Because I think getting anything more than double out of your ore is imbalancing to modded Minecraft's core gameplay, and I've never been a fan of it in all my years of playing it.
It's a matter of personal preference, but I've always stuck to it throughout the many times that people have asked for more valueable ore processing from IE.

**Comment by PrincessRTFM** [comment]
Many times is right. Maybe there should be a list of suggestions _not_ to make somewhere...
