### ISSUE TITLE
[1.12.2] Handle Industrial Foregoing fertilizer type in cloche

### ISSUE THREAD

**Issue by unikmhz** [BluSunrize/ImmersiveEngineering#2913]
May I ask if it is possible to add support for Industrial Foregoing's fertilizer (```industrialforegoing:fertilizer:0```, oredicted ```dyeBrown``` and ```fertilizer```) in garden cloche? Currently when piped into cloche's bottom block, it is consumed at each fertilization cycle, but growth modifier stays at 1.00.

Alternatively, a CraftTweaker API to add various *fertilizer* → *modifier* pairs would be awesome.

### Versions
Minecraft 1.12.2
Forge 2611
Immersive Engineering 0.12-80
Industrial Foregoing 1.8.5-127

**Comment by unikmhz** [comment]
Sorry, dupe of #2904

**Comment by unikmhz** [comment]
Sorry again for spam ;)
CraftTweaker issue is a dupe (#2904), but adding direct IF support would be nice.

**Comment by BluSunrize** [comment]
I mean, IE has a pretty nifty API that the IF devs could use? =P

**Comment by JackyyTV** [comment]
I've just added the compat in Integration Foregoing.
https://github.com/JackyyTV/IntegrationForegoing/commit/14331d0#diff-b7bf10d119f1644d67dc28112c1512ed

**Comment by unikmhz** [comment]
Closing.
Big ups for all involved! ;)
