### ISSUE TITLE
Request: Configurable Item Capacity for Silo

### ISSUE THREAD

**Issue by 666lumberjack** [BluSunrize/ImmersiveEngineering#2914]
The Silo looks super cool, but its capacity is outstripped pretty quickly if you have any kind of barrel mod installed or one of several tech mods that add their own bulk storage solutions. I'd love to make them the premier option for extreme bulk storage in a pack, but right now it seems there's no way to give them a capacity of more than the default ~46,000 items.

**Comment by BluSunrize** [comment]
The silo's contents were set based on the amount that one could fit into 24 vanilla chests, as that seemed like a good amount of matters of scaling.
I have currently no plans for making it configurable.
