### ISSUE TITLE
Suggestion: API Jar for development

### ISSUE THREAD

**Issue by Lykrast** [BluSunrize/ImmersiveEngineering#2916]
It would be really helpful for mod compatibility development to have a downloadable, separate Jar containing only the API.

Currently, I need to put the entire mod Jar into my dev environment if I wish to use the API, which means it's harder to test the mod without IE (need to build the mod and make an instance outside the dev environment), and is also much heavier than what the API alone would be.

**Comment by BluSunrize** [comment]
Gradle is your friend here, it literally does it all for you:
```
repositories {
    maven {
        name "Base/IE"
        url "http://maven.blamejared.com"
    }
}
```

and 
```
dependencies {
    deobfCompile "blusunrize:ImmersiveEngineering:0.12-+"
}
```

**Comment by Lykrast** [comment]
Thanks, that makes updating it much easier. You should probably put that in the wiki or the readme for easier visibility.

Although that still means I have the whole mod loaded when I run with gradle, unless there's a way to launch it without IE without relying on building my mod and putting it in a "real" instance.

**Comment by malte0811** [comment]
Try using `compileOnly` instead of `deobfCompile`.

**Comment by Lykrast** [comment]
That sadly still leaves IE on gradle run.

**Comment by PrincessRTFM** [comment]
What I've done with other mods is to get their jar/source and delete everything outside the api package, then put THAT into my instance for development. When I want to test WITH the mod, I just drop the full dev jar into the dev mods folder. Mind, I last coded on 1.7.10, so I might be out of date. Also, not sure if IE's license lets you modify the jar like that.

**Comment by BluSunrize** [comment]
Closing this, since original issue was solved.
