### ISSUE TITLE
Illusional Wish

### ISSUE THREAD

**Issue by dawgermany** [BluSunrize/ImmersiveEngineering#2917]
I don't know exactly how the engineers manual is built so this might be just plain impossible but nevertheless i was wondering if it was possible to set up a version of the engineering manual that is accessible without Minecraft (a pdf, a GitHub page (pages.github.com), just some kind of the manual accessible independent from Minecraft). I think it would be useful.
If you don't care or don't think its necessary jus close this issue as i have read multiple answers to people requesting a proper wiki  referring to the in game manual

**Comment by BluSunrize** [comment]
There is an idea to implement this in the future, most likely when we move to Minecraft 1.13, as Malte suggested we redesign the manual for that. In doing so we would make it a file-based system that is then also accessible from a website.
