### ISSUE TITLE
Incorrect warning about java version

### ISSUE THREAD

**Issue by winnetrie83** [BluSunrize/ImmersiveEngineering#2918]
### Description of the issue: 
The mod displays a message that i run java version 1.8.0_25, while in fact my java version is 1.8.0_161
I have checked my java version in de cmd window with command java -version.

### Crashlog: 
No crash

### Versions & Modlist
ImmersiveEngineering-0.12-80
MC 1.12.2

**Comment by EvilDylan** [comment]
Minecraft has its own locally installed version of Java which it will run by default; This version is 1.8.0_25.
To switch to your own installation, go to launcher options, select your forge profile, edit, toggle the toggle where it says "Java Executable", then locate your own java installation (javaw.exe).

**Comment by malte0811** [comment]
^That.
If you don't believe the message, check the top right of the F3 debug screen.
