### ISSUE TITLE
Question about over 5 duplicate files created

### ISSUE THREAD

**Issue by Too-DAMN-Much** [BluSunrize/ImmersiveEngineering#2919]
i read the comment about the extra core jar file, this is a similar but not the same question.

in my mods folder i have jar core files for immersive engineering 73 through build number 80 duplicated, just wanting to be positive that that is intended, because it sounds more like there should be a core mod added, not multiple versions of it.

i use an automatic updating function from the twitch client to update mods in my instance so there shouldn't be any chance of user error here.

forge 2640, minecraft 1.12.2 immersive engineering 76 through 80 (core) and 80 standard.

full mod version number is 0.12 80.

edit: removed # signs as github doesn't like them and links to other issues.

**Comment by BluSunrize** [comment]
The Core Mod components are supposed to be packaged separately in all mods but as of yet IE is the only one that actually adheres to this forge convention.
You have to delete those extra files then you update the mod.
We can't do much about it automatically because Forge doesn't want us to delete it from our end and twitch doesn't offer any support for it because they're being weird. Sorry :/

**Comment by Too-DAMN-Much** [comment]
ah, so it is a forge bug report, well there's no chance lex will ever listen then.

i'll delete them manually next time i update then.

**Comment by malte0811** [comment]
Lex seems to be working on something related to this issue for 1.13, see https://mobile.twitter.com/LexManos/status/979638005412458496 and the replies.

**Comment by Too-DAMN-Much** [comment]
interesting, at any rate it's not the biggest issue as long as people are aware that it shouldn't be happening.

i'd honestly say that so long as this is something people are warned about in a very hard to miss spot so that they know to delete the extra files it's good enough to count as fixed for now anyway.
