### ISSUE TITLE
Question:  Upgrade from 0.5.1 to 0.5.2 without losing blocks in world

### ISSUE THREAD

**Issue by kwpugh** [BluSunrize/ImmersiveEngineering#292]
Is there a way to update to 0.5.2 without having my players lose all their in-game blocks?   I tested first and it forced a /fml config and much of the blocks were gone, not replaced.

Any help would be greatly appreciated.

By the way, folks love the mod, keep up the great work.

**Comment by Auzze** [comment]
I just updated with no loss

On Sat, Aug 8, 2015 at 8:01 AM, Kevin Pugh <notifications@github.com> wrote:

> Is there a way to update to 0.5.2 without having my players lose all their
> in-game blocks? I tested first and it forced a /fml config and much of the
> blocks were gone, not replaced.
>
> Any help would be greatly appreciated.
>
> By the way, folks love the mod, keep up the great work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BluSunrize/ImmersiveEngineering/issues/292>.
>



-- 
Stuart (Auzze) Mitchell
Australia
