### ISSUE TITLE
Tools 3D model - Issues with shaderpacks

### ISSUE THREAD

**Issue by Error404-usernamenotfound** [BluSunrize/ImmersiveEngineering#2921]
### Description of the issue:
I have noticed multiple issues regarding the use of IE tools in junction of a shaderpack. Some parts of their 3D model is either not loaded or it doesn't have the intended material. For exemple, the revolver's magazine is invisible when using shaders (shaders as in shadows and water refraction, etc.) Next, the heavy plated shield's window is completely opaque, again, only when using shaders. I've tried many shaderpacks, so I thought, of course, it was an issue with Immersive.

### Versions & Modlist
I am playing with **forge 1.12.2-14.23.0.2528** (I'm using an older version bc chests dont open above this version :/ )
**IE version is 0.12-80**
I doubt my mods are what causes the issues but here they are:

- BiomesOPlenty-1.12.2-7.0.1.2325
- gravestone-1.10.1
- Hwyla-1.8.23-B38_1.12
- ImmersiveEngineering-0.12-80 (and it's core, ofc)
- immersivepetroleum-1.12-1.1.9
- immersivetech-1.12-1.3.7
- inventorysorter-1.12.2-1.13.1+55
- journeymap-1.12.2-5.5.2
- Just-Enough-Items-Mod-1.12.2
- OpenComputers-MC1.12.2-1.7.2.67
- OptiFine_1.12.2_HD_U_C7
- Pam's+HarvestCraft+1.12.2t
- QuickLeafDecay-MC1.12.2-1.2.4
- StorageDrawers-1.12.2-5.3.6

**Without shaders:**
![2018-03-31_17 41 48](https://user-images.githubusercontent.com/20631365/38167830-e99d5518-350a-11e8-8f2c-544e8d98fbcf.png)

**With shaders:**
![2018-03-31_17 39 59](https://user-images.githubusercontent.com/20631365/38167829-e3dc2d66-350a-11e8-9661-d53cf7ef9c37.png)

**Also tested only with IE, jei and optifine** (Issue is with OptiFine and its shaderpacks, so testing without is totally fine)

### My Hypothesis:
I can only think of 3 reasons this is happening:

1. Shaders themselves;
2. Forge version (I did not test the latest forge version);
3. Immersive Engineering.

What do you suggest me doing to fix this? Or is it an issue for everyone?

**Comment by PrincessRTFM** [comment]
The first thing I notice is that you say you have Optifine installed. Blu does not support Optifine. Practically nobody "supports" Optifine. Many modders, Blu included, tell people "if you have Optifine installed, remove it _before_ submitting a bug report" because Optifine straight up replaces many base classes in the game code. Also:

> Issue is with OptiFine and its shaderpacks, so testing without is totally fine

If you're saying what I think you're saying - that the problem _doesn't occur_ without Optifine - then I will bet _folding money_ on Blu telling you that this won't be fixed on his end and then dropping this issue.

**Comment by Error404-usernamenotfound** [comment]
Understandable, but why can't it be supported? Why is this happening? I never saw any issues related to OptiFine.

**Comment by PrincessRTFM** [comment]
Read [CONTRIBUTING.md](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/CONTRIBUTING.md) in the base folder of the repo for details. Basically:

* Optifine changes a lot of Minceraft's rendering code
* It is not legally possible to check what those changes are
* There is no dev/deobf version of Optifine, which makes running itin a dev environment pretty much impossible

There's a third party tool that can deobfuscate code, but I think that's probably against Optifine's license, which is where the "illegal" part comes into play. Optifine does not play nice with other modders.
