### ISSUE TITLE
sheet metal tank turns invisible when you stand right next to it and look up

### ISSUE THREAD

**Issue by MatthiasMann** [BluSunrize/ImmersiveEngineering#2925]
The sheet metal tank turns invisible when you stand right next to it and look up - as soon the as the base center block (where the pipes connect) is no longer on screen - maybe too small rendering bounding box?

### Versions & Modlist
ImmersiveEngineering-0.12-80
Forge: 14.23.2.2638
Modpack: https://minecraft.curseforge.com/projects/modern-skyblock-3-departed/files/2546758

**Comment by malte0811** [comment]
I assume the base center block is on Y-level 63 (or anything like 16n-1)? If it is, see  #1984. If it isn't please put a comment here, that would be a new problem.
I have an idea for a potential "fix", but a. it wouldn't be a complete fix and b. I don't really have the time to implement it (adding each quad of the complete obj model to the model of the block closest to it).

**Comment by MatthiasMann** [comment]
The base is at 79 - so same as issue #1984
