### ISSUE TITLE
all the wires are gone

### ISSUE THREAD

**Issue by 0142929** [BluSunrize/ImmersiveEngineering#2927]
hello.
all the wires are gone in single player, after restarting minecraft.
exiting was normal.
there are no any wires in game,
but me can not connect to existing connectors to restore links.
it says: "you can not attach this wire here"
wires not just invisible, it is not hitting, and no any mashines working.

no any other global mods used.

1.12.2-forge1.12.2-14.23.2.2611
ImmersiveEngineering-0.12-80.jar

**Comment by malte0811** [comment]
Could you upload full logs of the first launch before and after the wires disappeared? Invisible wires on servers are known, this is new.

**Comment by 0142929** [comment]
early fml log is absent, me sorry about..
looks like there was problems with out of memory errors before.
perhaps this why wires saved incorrectly.

[_after_.zip](https://github.com/BluSunrize/ImmersiveEngineering/files/1886363/_after_.zip)
[_before_.zip](https://github.com/BluSunrize/ImmersiveEngineering/files/1886364/_before_.zip)

**Comment by 0142929** [comment]
[crash-2018-04-07_06.14.26-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1886408/crash-2018-04-07_06.14.26-server.txt)

me was wrong, it was not normal exit, minecraft crashed

**Comment by malte0811** [comment]
That was a crash while saving the world to disk, I'm pretty sure that's why the wires went missing. What caused the `OutOfMemoryError` is more complicated, especially since it looks like a native/OpenGL memory leak to me (OpenGL fails to allocate memory, which it wouldn't do if it was just the JVM heap that was full AFAIK).
