### ISSUE TITLE
1.12 Diesel generator not accepting thermal expansion fuels.

### ISSUE THREAD

**Issue by SirSpence99** [BluSunrize/ImmersiveEngineering#2928]
It appears that the thermal expansion compat does not handle fuels for the diesel generator.

**Comment by bookerthegeek** [comment]
https://teamcofh.com/docs/creosote-oil/
https://teamcofh.com/docs/liquifacted-coal/
https://teamcofh.com/docs/crude-oil/
https://teamcofh.com/docs/naphtha/
https://teamcofh.com/docs/refined-fuel/

**Comment by BluSunrize** [comment]
Creosote and Liquifacted coal make no sense in a DieselGen, neither does crude oil much.

Naphtha and Refined fuel may be worth the consideration. Suggestions on output, given that I don't know anything about TE's techtree are appreciated.

**Comment by KingLemming** [comment]
Naphtha is currently 1,000,000 RF, Refined Fuel is 1,500,000 RF (2,250,000 w/ Ignition Plugs).

Minor changes since above post, but it's otherwise very much correct.
