### ISSUE TITLE
Client crash - NullPointerException: Ticking block entity BlockWoodenDevice1.isSideSolid

### ISSUE THREAD

**Issue by ProsperCraft** [BluSunrize/ImmersiveEngineering#2931]
### Description of the issue:
Client to my server crashed as the client got disconnected for a server reboot.

### Crashlog:
https://pastebin.com/u56mRhgY

### Versions & Modlist
https://minecraft.curseforge.com/projects/towncraft

**Comment by BluSunrize** [comment]
Sorry for the delayed reply.
Have you been able to restart the server and log back in?

**Comment by ProsperCraft** [comment]
We have since wiped the server and started fresh, we have not had this issue on this playthrough yet.
