### ISSUE TITLE
Request: OreDict unification

### ISSUE THREAD

**Issue by BaseCrusher** [BluSunrize/ImmersiveEngineering#2932]
Hey there,

So I'm putting a modpack together and im trying to get rid of all dulicated items e.g. copper ingot.
Now I'm not sure if it is possible, but I suppose it should be to do a config file, where all OreDict entries are listed. Something like this:

Copper Ingot = immersiveengineering:metal@0;
Silver Ingot = immersiveengineering:metal@3;
Nickel Ingot = immersiveengineering:metal@4;

And by changeing the entry in this config, the input/output items will change ingame. 
For example:

Copper Ingot = thermalfoundation:material@128;

With a simple change in the config we should now get the Thermal Expansion copper ingot out of smelting Immersive Engineering copper ore. 

Even better, if it would be able to remove the unused copper inogt from the game to reduce loading time and increase FPS since there are less textures to load.

Again this is only a request and I'm not sure how easy it is to implement something like this. But i suppose the code uses variables and if it could go throu this config for setting those it would be nice.

I'd like to hear if it is possible to implement something like this.

Thanks in advance for your answer.
BaseCrusher

**Comment by BluSunrize** [comment]
I mean, possible, probably. I'm not doing it though.

You can do this yourself with Crafttweaker, but I'm not putting it as a feature in IE.

**Comment by BaseCrusher** [comment]
Well yes, it is possible to change the recipes with CraftTweaker.
But that would mean that you have to remove every recipe using that ingot and then implement the same recipe again.
As far as I know CraftTweaker doesnt have the option to change the complete OreDict entry.
Doing something like this for 1 or 2 recipes is fine but after all there are over 100 recipes for silver, copper, and all the other ore/ingots.
Rewrite every recipe for the purpose of unification is doing the same work twice, since the recipe already exists. And sadly the "/ct recipes hand" command of CraftTweaker can only output crafting table recipes you cant just copy over all the Arc Furnace, Blast Furnace and Crusher recipes.
So this solution could make it a lot easier.

Anyway, this was only a request. If you won't do it, then it's fine. was just a request. :D

**Comment by mindforger** [comment]
>As far as I know CraftTweaker doesnt have the option to change the complete OreDict entry.

that is wrong, i "oreDicted" a lot of common non ore blocks to stuff my excavator with crap instead of pulling an empty bucket
https://crafttweaker.readthedocs.io/en/latest/#Vanilla/OreDict/IOreDictEntry/

**Comment by BaseCrusher** [comment]
I have tried it my self several times. But this CraftTweaker method only merges OreDict entries of two diffrent entries. And it won't change the output, since the output is decided by the mod and not by the OreDict. So merging iron ingot into copper ingot won't output copper ingot instead of iron ingot. I just could craft a piston with a copper ingot instead of a iron ingot.

If I'm wrong I'd appreciate if you could post me an exempel script. :)
