### ISSUE TITLE
Can u help me?

### ISSUE THREAD

**Issue by HurtsAsHell** [BluSunrize/ImmersiveEngineering#2933]
I just need to know what I skipped, following the guide I do not understand what is missing;

mods.immersiveengineering.Excavator

//Exavetor addRecipe
//mods.immersiveengineering.Excavator.addMineral(String name, int mineralWeight, double failChance, String[] ores, double[] chances, @optional int[] dimensionWhitelist, @optional boolean blacklist);
mods.immersiveengineering.Excavator.addMineral("Iron Ore", 25, 0.5,["btt:deep_iron_ore"], [0.02]);

**Comment by BluSunrize** [comment]
You will need to specify your issue a bit more than that, I'm afraid. Version numbers, what you are trying to do, what errors you are getting, log files, all that stuff.

**Comment by HurtsAsHell** [comment]
I would like to add a mineral to the exavator;
added the string above, it does not happen except for a minetweaker error; I have the Immersive Engineering version 0.12 - 80

craftweaker
https://pastebin.com/qwA7YJ6d

fml
https://pastebin.com/FUC5beAV

**Comment by PrincessRTFM** [comment]
Line 83:

> [INITIALIZATION][CLIENT][ERROR] [crafttweaker | SIDE_CLIENT]: Error parsing Immersive_Eng.zs:5 -- ; expected

You're missing a semicolon around line five in `Immersive_Eng.zs` and it can't process the file.

**Comment by bookerthegeek** [comment]
The issue is the code is escaped.

**Comment by HurtsAsHell** [comment]
This is the file .zs [https://pastebin.com/NwTRN8C8](url)

**Comment by BluSunrize** [comment]
Ores should have OreDictionary names, not registry names.

**Comment by HurtsAsHell** [comment]
For example oreIron?

**Comment by HurtsAsHell** [comment]
do you have a guide that explains better than the wiki?

**Comment by BluSunrize** [comment]
Well I didn't write the wiki, so no =P

But yes, only OreDictionary names work (if I remember my own code here). So "oreIron", "nuggetGold", that sort of stuff. You can usually figure those out with the ```/mt hand``` command

**Comment by HurtsAsHell** [comment]
So I need to create one OreDictionary?

**Comment by BluSunrize** [comment]
No you need to use items that are already registered or use Minetweaker to register them (if that option still exists)

I'll be closing this for now, since it's a question of Minetweaker functionality.
