### ISSUE TITLE
[0.12-80] Skyhook client/server crash.

### ISSUE THREAD

**Issue by TheShelterProject** [BluSunrize/ImmersiveEngineering#2937]
Hi,

### Description of the issue:
On a dedicated server (Forge **14.23.3.2659**, Java 1.8.0_161, without SpongeForge), right-clicking on a hanging cable with a Skyhook crash the client and the server. Once the server restarted, the previously "disconnected" client is unable to connect (Y Coordinate is "NaN" and a lot of errors in the console).

### Crashlog:
**Server:** [crash-2018-04-12_22.11.28-server.txt](https://pastebin.com/raw/A1qc8DsF)
**Client:** No crash-reports folder/files.

Server's logs after trying to reconnect: [latest.log](https://pastebin.com/raw/Z43nt89Q)

### Versions & Modlist (server) 
forge-1.12.2-14.23.3.2659-universal.jar
ImmersiveEngineering-0.12-80.jar 

### Versions & Modlist (client)
forge-1.12.2-14.23.2.2627-universal.jar
ImmersiveEngineering-0.12-80.jar 
OptiFine_1.12.2_HD_U_D1.jar

**Comment by malte0811** [comment]
Fixed. There isn't much I can do about the broken player, you can either completely remove their file from the `playerdata` directory (this will reset everything, including their inventory) or use some sort of NBT editor (I used https://irath96.github.io/webNBT/ before) to fix the position (`Pos` key).

**Comment by TheShelterProject** [comment]
@malte0811 Thanks for the fix and the solution about the broken player ^^'

**Comment by TheShelterProject** [comment]
Tested with IE 0.12-81-365 and everything is now working.
