### ISSUE TITLE
Possible Request: Tin Grit

### ISSUE THREAD

**Issue by MtnDrew** [BluSunrize/ImmersiveEngineering#2938]
I used the search function for "tin grit"/"mod grit" and found an old thread in 2015 about adding grit to Immersive Engineering. AOBD was the suggestion but that mod is long dead. I also see that this mod does have forestry compatibility (the mod that is generating it), but no tin processing.

Is that something you would add as a compatibility feature? 

Or if not, does anyone who frequents this repository know of an AOBD alternative that doesn't also add a bunch of other tech or random stuff?

**Comment by MauveCloud** [comment]
> Or if not, does anyone who frequents this repository know of an AOBD alternative that doesn't also add a bunch of other tech or random stuff?

Try this:
https://minecraft.curseforge.com/projects/jaopca

**Comment by MtnDrew** [comment]
Didn't even know that existed. That's wonderful.
