### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by affangg** [BluSunrize/ImmersiveEngineering#2942]
the game crash i dont know why
[crash-2018-04-15_07.55.03-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1911516/crash-2018-04-15_07.55.03-client.txt)

**Comment by malte0811** [comment]
Try giving MC more memory. 1G is not all that much in 1.12.

**Comment by BluSunrize** [comment]
Closed due to lack of response
