### ISSUE TITLE
Splitting conveyor animation 'asynchronous'?

### ISSUE THREAD

**Issue by MatthiasMann** [BluSunrize/ImmersiveEngineering#2943]
### Description of the issue:
I have setup a splitting conveyor belt system (see screenshot) - but items appear to take the to path only to snap into the lower path as soon as they reach the edge of the splitting conveyor - same for the other way around.

### Versions & Modlist
ImmersiveEngineering-0.12-80
forge-1.12.2-14.23.3.2666
Mod pack: https://minecraft.curseforge.com/projects/modern-skyblock-3-departed/files/2551885
Singleplayer

**Comment by MatthiasMann** [comment]
![2018-04-15_10 01 02](https://user-images.githubusercontent.com/6777029/38776238-0a98e28e-4094-11e8-902d-e49b5364f0f9.png)
![2018-04-15_10 01 02_2](https://user-images.githubusercontent.com/6777029/38776239-0c174308-4094-11e8-8de7-92b478e60068.png)

The 2nd screen shot was taken directly after the first one

**Comment by BluSunrize** [comment]
It's a desync between server and client, where the client says go left, and server says go right. Because both of them alternate on each transfer, they remain out of sync until you break and replace, as you found out.
