### ISSUE TITLE
[0.12-80] [Request] Please remove Enchanted effect from Heavy Plated Shield

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#2944]
Enchanting the shield makes the whole thing an eyesore and probably dangerous to use for epileptics (only half-joking here).
Plus the shield displaying no enchating effect would keep in line with the vanilla shield - which also does not have it. Probably for similar reasons.

**Comment by Saklad5** [comment]
That’s not supposed to be enchantable? I sort of assumed that was intended behavior. I suppose it makes sense that it is an accident, if you designed it by extending the vanilla shield.

I’m a bit curious about the enchanted effect, if that is just unintended behavior. It really is quite flashy, to the point that I thought it was designed that way.
