### ISSUE TITLE
[0.12-80] [Request][Minor] Add Thermoelectric Generator compat for Magma Block

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#2945]
as title
maybe on par with lava just less flowy-getting-everywhere and without that pesky light that melts your ice
don't care really. just feels off that magma block doesn't come into play as a hot block :)

**Comment by MalkContent** [comment]
fair enough. I'm devil's-advocating for keeping the relative heat nerf symbolic though. Minor increase in safety being bought by being rarer AND worse probably quickly isn't worth it.

**Comment by BluSunrize** [comment]
Yeah, fair!
