### ISSUE TITLE
[Suggestion] Blueprints with limited time of usage

### ISSUE THREAD

**Issue by wormzjl** [BluSunrize/ImmersiveEngineering#2947]
It's really great to see the crafttwaker support for blueprints.
What I'm suggesting is adding possibilities to limit how many times a blueprint can be used, like blueprint copies in EVE online.
This will open up a lot of possibilities for modpack development.
Thank you!

**Comment by mindforger** [comment]
can you explain a scenario or two that are cooking in your mind?

**Comment by wormzjl** [comment]
Like some sort quests or other means  giving a blueprint for low-cost
production of certain items, but only for a limited times. This could ease
initial grinding while keeping the game balance.



mindforger <notifications@github.com> 于 2018年4月16日周一 12:04写道：
