### ISSUE TITLE
1.7.10 mineral set command can not deal with whitespaces

### ISSUE THREAD

**Issue by mindforger** [BluSunrize/ImmersiveEngineering#2949]
i know 1.7.10 is not supported anymore, but the mineral command has an issue when a minmeral vein has whitespaces in it's name, it is impossible to set a vein, because the ccommand is only reading the first word ... auto completion woorks great but is useless

can anybody please have a look if this is still present in the current versions ?

**Comment by malte0811** [comment]
Have you tried putting the mineral name in angle brackets, `<mineral name with spaces>`? I don't know whether that works on 1.7.10, it is how names with spaces are entered in 1.12 IIRC.

**Comment by BluSunrize** [comment]
They weren't designed to have a space in them, that would be why.

**Comment by mindforger** [comment]
at least it works :P

but vein names sometimes require spaces

maybe allow string encapsulation for the future or combine the words to form a single string, i mean you can "tab"-complete the name **with** spaces there but then not being recognized is kinda strange behaviour
