### ISSUE TITLE
Cannot sneak-right-click fluid pump with engineering hammer while using an offhand anything

### ISSUE THREAD

**Issue by Xetaxheb** [BluSunrize/ImmersiveEngineering#2952]
### Description of the issue:
If you have literally anything in the offhand, you cannot sneak-right-click a fluid pump with the engineering hammer to toggle the none->input->output->none on the opposite side.

### Versions & Modlist
IE 0.12-80
Forge 2645

**Comment by Paul17041993** [comment]
This also affects belts as I've recently discovered, in fact I'd assume it affects _all_ sneak+hammer operations. I'm not aware of any reasons for this to be the case on purpose, so an override on the hammer should be all that's needed.
