### ISSUE TITLE
[0.12-80] Metal Scaffolding Mining Speed Irregularities with Engineer's Hammer

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#2953]
There is an inconsistency in mining speed when mining any kind of metal scaffolding with the Engineer's Hammer (Pickaxe is always fine afaik). It has been bothering me since at least 1.10.2 and I've finally managed to find a way to reliably reproduce the issue.

Build a metal scaffold stack like so:
![scaffold-stack](https://user-images.githubusercontent.com/7753414/39076401-504ffac2-44fb-11e8-814f-916aeae9ba33.png)

Then mine them from the bottom going up. You should notice a considerably slower mining speed on some of the upper scaffolds. There is some inconsistency in which block is the first slow one.
The "rule" to this also isn't simply that scaffolds without other blocks below are affected by this. It can happen to scaffolds with blocks beneath and it also generally doesn't seem to happen to scaffold blocks that never had contact to other scaffold blocks, but the latter just might be me not experiencing it yet.
It's a weird issue.

I will also shamelessly plug this again: https://github.com/BluSunrize/ImmersiveEngineering/issues/1737
^^

**Comment by BluSunrize** [comment]
Okay, yeah I can reproduce it, but I have *zero* idea what's causing it.
In both cases the checks for hammer harvesting are called, so the difference in speed is really odd :/

**Comment by MalkContent** [comment]
It just occured to me to try that stacking method with hammerable blocks other than scaffolding. 
lo and behold other blocks are affected, too. I even found a rule: If the block is minable by hand, it is _not_ affected, if it just breaks when mined by hand, it is affected.
The best demonstrator probably are the barrels. Metal Barrel is affected, Wooden Barrel is fine.

Tested with:
Breakable by hand: Item/Fluid Router, Turn Table, Wooden Barrel, Wooden Scaffolding (though I think the hammer does not apply a bonus here, but I assume that is by design), Wooden and Metal Post
Requiring Hammer: Kinetic Dynamo, Conveyors, Metal Barrel, Metal Scaffolding, Fluid Pipe, Fluid Pump, Fluid Outlet

no outliers to the rule that i found

so while I'm not gonna go and say that it's the hammer, there at least seems to be something systematical going on
