### ISSUE TITLE
[Suggestion/Request] Modules for each feature in IE

### ISSUE THREAD

**Issue by Skillotic0703** [BluSunrize/ImmersiveEngineering#2955]
Immersive Engineering is a great mod but sometimes it doesn't really fit in your pack because there are a lot of overlapping features between IE and other tech mods but you actually want some crafting items from IE to use them in crafts or other very little features that are like 1% of the entire mod.
That's why I suggest that IE gets modules. There would be a cable module, a foundation module that would contain all IE's crafting items, an electric machines module and a base multiblocks module (Blast Furnace and Coke Oven) etc...

If that's not possible it would be great to at least have a mod that contains all IE's items just to use them with CraftTweaker.

I'm actually going to tell the same thing to other tech mod devs except for Thermal Expansion because it already has Thermal Foundation as a dependency.

**Comment by BluSunrize** [comment]
I hate Thermal Expansions idea of splitting everything into different mods with a passion actually, so I don't see this happening at any point ^^
