### ISSUE TITLE
Redstone probe connector supplies redstone to the tank

### ISSUE THREAD

**Issue by MatthiasMann** [BluSunrize/ImmersiveEngineering#2956]
### Description of the issue:
Attaching a redstone probe connector to the bottom of the multi block sheet metal tank (either side or from below) will supply a redstone signal to the tank itself when there is some fluid in the tank - which causes the tank to output that fluid (if possible via it's connected pipes etc).

It would make more sense if the redstone signal is only transfered over the redstone wire and not applied to the tank too.

### Versions & Modlist
forge-1.12.2-14.23.3.2668
ImmersiveEngineering-0.12-80
immersivepetroleum-1.12.2-1.1.9
immersivetech-1.12-1.3.7-SevTech-Ages

**Comment by MatthiasMann** [comment]
I think it is self feeding it's own redstone signal?

**Comment by BluSunrize** [comment]
Yes, it is sending itself its own signal, and that's on purpose.
If you hover over the connector with a hammer, you will see that it has two channels it operates on: "Channel Sending" and "Channel Receiving". You change them by (sneak-)rightclicking with a hammer.
If they are both the same, then yes, it will send itself its own signal. The point is that you can use the probe to both monitor the comparator output, as well as send a control signal.

Example for you tank:
You put sending to Light Blue and receiving to Magenta. You can then monitor the fill of you tank using the light blue channel, and by putting a signal on magenta, you can remotely trigger the output.

You can find hte information regarding this on page 4 of the entry "Redstone Wires" in the Engineer's Manual.

**Comment by MatthiasMann** [comment]
Thanks - that makes sense - and now that you explained it - I remember that part :D Somehow I forgot about that while playing yesterday :)
