### ISSUE TITLE
[Suggestion][Minor] Make Shift+Middle-Mouse-Button on a Connector/Relay give the corresponding Wire instead

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#2957]
I mostly use MMB in creative, but this should have survival use too. The issue with wires is that you can't click onto them, because they aren't a block. I think this shift+mmb onto Connectors/Relays thing could relieve some tedium during building. Probably should have a manual entry, too, though, otherwise I'll be the only user who knows about it :x

**Comment by BluSunrize** [comment]
I don't think there is a simple hook to do that. The function used in middle-click is ```getPickBlock``` but since it's not client only we can't just check for keyboard inputs there :/

**Comment by MalkContent** [comment]
rats. does the function provide the player and can you check if he's sneaking maybe?

**Comment by BluSunrize** [comment]
...i didn't even think of that.
Yeah that's probably doable then! I'll take a look soon.

**Comment by MalkContent** [comment]
:D hooray i am helpful
