### ISSUE TITLE
Issue when adding IE 0.7.7 to Modpack

### ISSUE THREAD

**Issue by Ehrenthomate** [BluSunrize/ImmersiveEngineering#2958]
Hey Guys,
I´m getting an Issue when loading IE 0.77 in my private Modpack.
Without IE it works completely, when I add the mod, Minecraft crashs.
I just don`t know where the issue comes from, in other Modpacks with the same Mods and some more, it always worked, so I don´t think it´s a compat issue.
I have no knowledge how to read Minecraft Crash Reports, so I hope someone can help me.
Here you can find the Crash-Report: 
[crash-2018-04-22_22.46.43-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1936108/crash-2018-04-22_22.46.43-client.txt)

Thanks for your help!

Greetings

ETH

**Comment by BluSunrize** [comment]
Go into the config, look for IE's potion IDs and just delete that segment, it'll regen.
Also, IE for 1.7 isn't officially supported anymore, just so you're aware.

**Comment by Ehrenthomate** [comment]
> isn’t officially supported anymore

Oh...didn’t know...
Nevertheless, thanks for your answer!
