### ISSUE TITLE
[1.12.2] Performance bug - Alloy Kiln

### ISSUE THREAD

**Issue by ProsperCraft** [BluSunrize/ImmersiveEngineering#2959]
### Description of the issue:
When the Alloy Kiln can't work it ticks very high.

This user has 4 Alloy Kilns, all ticking at different amounts due to what is inside them.

![2018-04-22_13 43 13](https://user-images.githubusercontent.com/4427684/39099256-bfb8acd0-4634-11e8-86f6-90b3935d9ad6.png)

The empty kiln is ticking at 2m/s

You can see the measurement behind in the red.
![2018-04-22_13 43 45](https://user-images.githubusercontent.com/4427684/39100666-7d84038a-464a-11e8-9342-a15a578d012a.png)
![2018-04-22_13 43 55](https://user-images.githubusercontent.com/4427684/39100668-883e05c8-464a-11e8-83d8-d84f425ef053.png)
![2018-04-22_13 44 00](https://user-images.githubusercontent.com/4427684/39100672-a06f5ef8-464a-11e8-9200-0778ca480901.png)
![2018-04-22_13 44 13](https://user-images.githubusercontent.com/4427684/39100675-a543b690-464a-11e8-8e42-f260cf88fce6.png)

This is the perfect testbed for this-

### Versions & Modlist
Mod list- https://minecraft.curseforge.com/projects/towncraft

ImmersiveEngineering-0.12-80.jar

**Comment by malte0811** [comment]
Those aren't milliseconds (ms), those are microseconds (sometimes us, usually μs). So the empty kiln is taking 0.002 ms, which is perfectly fine. If those were milliseconds every server tick would take at least one second.
The tick times all seem reasonable, if you still think something is wrong include proper profiling data (nps files).

**Comment by ProsperCraft** [comment]
You are right, that was a poor report, I will post a new one that more clearly communicates this issue.
