### ISSUE TITLE
Unable to open Biomes O' Plenty creative tab with Immersive Engineering installed

### ISSUE THREAD

**Issue by bonnyvonscotty** [BluSunrize/ImmersiveEngineering#2963]
Clicking on the Biomes O' Plenty creative tab crashes the game when installed with Immersive Engineering.  Issue tested in an instance containing ONLY Forge, IE, and BOP.

Versions: 
MC-------------------------------------------------1.12.2
Forge----------------------------------------------14.23.3.2673
Immersive Engineering---------------------------0.12-81
Biomes O' Plenty----------------------------------7.0.1.2381

Crash report: https://pastebin.com/mNLFL0yQ

**Comment by bonnyvonscotty** [comment]
Update: Nevermind, it was on the BOP end.  The 7.0.1.2382 update solved it.  

Sorry for the false alarm.  Had tested it with just BOP and it didn't crash, and a handful of other mods didn't cause it to crash, either.  Only IE, so I assumed it was a conflict, possibly on IE's end.

**Comment by BluSunrize** [comment]
Issue solved then
