### ISSUE TITLE
[1.12.2] Wire Cutters consumed when crafting wires.

### ISSUE THREAD

**Issue by munrune** [BluSunrize/ImmersiveEngineering#2966]
**Description of the issue:**
Crafting wires with the wire cutters consume the wire cutters. Crafting metal press molds works properly.

**Versions:**
Minecraft: 1.12.2
Forge: 14.23.3.2673
Immersive Engineering: 0.12-81

**Comment by BluSunrize** [comment]
I've already found a fix for this and applied it. I'll close this when I push.

**Comment by BluSunrize** [comment]
Fixed with this commit:
https://github.com/BluSunrize/ImmersiveEngineering/commit/ee4ba8422e9205883b7384dfcbbd1debb783b35e

**Comment by darthvader45** [comment]
So if the push has been made, how long til a version with the fix will be up?
