### ISSUE TITLE
IE to power AE?

### ISSUE THREAD

**Issue by MokahTGS** [BluSunrize/ImmersiveEngineering#297]
Can someone tell me how you can use IE to power an AE system?  I can't get any connections to work...

**Comment by ZiaAvenicia** [comment]
It should work the same as any other mod. Have a connection on an Energy Acceptor or a Controller.

**Comment by BluSunrize** [comment]
It's Redstone Flux, so you'll probably need an energy aceptor

**Comment by cloakable** [comment]
You can put RF into a Controller too and it'll act as an energy acceptor
