### ISSUE TITLE
[1.10.2] Conveyor Belt Bug

### ISSUE THREAD

**Issue by Neutora** [BluSunrize/ImmersiveEngineering#2970]
### Description of the issue:

After letting the game run a few hours conveyor belts randomly get buggy. I let the game run for 10 hours without leaving the chunk and 5 times a conveyor belt turned into that block:

![2018-04-27_20 58 53](https://user-images.githubusercontent.com/38799154/39389142-2671dae6-4a86-11e8-906a-10920ff85f45.png)

I tried it with the Redstone Ignoring Conveyor Belt and the Dropping Conveyor Belt and had the same problem with them.
I found a similar issue: [1.12] Conveyors random bug #2289, but in my case I crafted the conveyor belt in survival mode. 
If I break it and place it again, it stays bugged:

![2018-04-27_21 00 17](https://user-images.githubusercontent.com/38799154/39389143-26929812-4a86-11e8-8d26-5ea94fdbae5a.png)

Sometimes the texture does not change and the items seem to travel a few block and then disappear:

![2018-04-28_01 14 54](https://user-images.githubusercontent.com/38799154/39389145-2f205686-4a86-11e8-8bf5-06aa878d9bae.png)

After relogging, the texture changes and the items stop at the bugged block: 

![2018-04-28_01 16 56](https://user-images.githubusercontent.com/38799154/39389146-2f41657e-4a86-11e8-9851-f1ffd4ded0fd.png)

I am aware that 1.10.2 is an old version that probably will not be updated anymore, so does someone know of a fix for this issue or at least another way to reliably transport items from a garden cloche? Ender IO doesn't seem to work.

### Versions & Modlist

Immersive Engineering 0.10 - 61
Minecraft version 1.10.2 forge-12-18.3.2511
Modpack: Age of Engineering-1.1.2

**Comment by BluSunrize** [comment]
Provide a forced crashlog please.

**Comment by Rixxaw** [comment]
He has EnderIO pipes above his setup.  EnderIO is not in the Modpack.  Looks like EnderIO pipes are connecting to his conveyers as well so maybe its a problem with EnderIO?

**Comment by BluSunrize** [comment]
Closed due to lack of input and 1.10 no longer being officially supported.
