### ISSUE TITLE
Wire cutters being consumed when making wire.

### ISSUE THREAD

**Issue by warplord** [BluSunrize/ImmersiveEngineering#2972]
I am playing the revelations modpack (with changes) and noticed that the wire cutters were consumed when making LV copper wire. Shears work just fine (just lose a bit of durability). Might be a bug.

**Comment by KnightMiner** [comment]
Does this happen outside of the modpack? (or if you remove all crafttweaker scripts?) They may have incorrectly changed a recipe.

**Comment by BluSunrize** [comment]
Duplicate of #2966, use the search function please and read the issue guidelines next time.
