### ISSUE TITLE
[Server thread/ERROR] [immersiveengineering]

### ISSUE THREAD

**Issue by djdanby** [BluSunrize/ImmersiveEngineering#2977]
I found this in my Server Log.

[02:09:56] [Server thread/INFO] [nucleus]: Starting QuickStart Module Loader version 0.10.1 subsystem.
[02:09:58] [Server thread/ERROR] [immersiveengineering]: Compat module for tconstruct could not be preInitialized. Report this!
[02:09:58] [Immersive Engineering Contributors Thread/INFO] [immersiveengineering]: Attempting to download special revolvers from GitHub

> Report this!

Mission done :)

SpongeForge 1566 1.12.2
ImmersiveEngineering-0.12-81

**Comment by bookerthegeek** [comment]
Do you have thinkers in this instance?

**Comment by malte0811** [comment]
I just tested, this did not happen to me. I tried both Forge 2673 and recommended (2655). There has been a second "report" of this [on the IE CF page](https://minecraft.curseforge.com/projects/immersive-engineering?comment=2221). I used the same IE and TiC versions as specified in that comment, both downloaded from CF.
@djdanby Could you try without SpongeForge and upload a full mod list?

**Comment by Tyrant0x1** [comment]
I'm currently also having this issue. The notable side effect is a lack of IE materials as tinker's tool materials.
Here is a full modlist (just a dump of the files in my mods folder... if there's a better way to get a list, I'll be happy to do that): [list.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/1965142/list.txt)

As a bonus, here's a full log file containing the error djdanby posted:
[latest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/1965172/latest.log)

**Comment by djdanby** [comment]
No i do not use Tinkers. Here is a screen from my mods: [(https://picload.org/view/dodwlgpa/modlist.png.html)]
