### ISSUE TITLE
Revolver missing model

### ISSUE THREAD

**Issue by Caopr** [BluSunrize/ImmersiveEngineering#2979]
Revolver is invisible with no icon. still usable. upgrading it or applying a shader doesent help.

other tools are visible

[Most recent version]

**Comment by BluSunrize** [comment]
I'm closing this, since you blatantly ignored the issue template.

**Comment by Minecraftbegin2snow** [comment]
@Caopr ,I don't think your Optifine is the latest version.You can try to update Optifine to the latest version.[https://www.optifine.net/home](url)
