### ISSUE TITLE
[1.12.2] MV wire dupe

### ISSUE THREAD

**Issue by JackRuby1** [BluSunrize/ImmersiveEngineering#2980]
### Description of the issue:
I broke my transformer with it still connected to a relay via a MV wire, the wire glitched (visually until I relogged, but it's still there shocking when I touch it) and now if I right click it with a pair of cutters it dupes MV cables as much as I want.
https://gyazo.com/675fe7ce5641cd9bd7a354a36c9ad9b7

### Versions & Modlist
Sevtech modpack 3.0.6 version
Forge-14.23.2.2651
IE 0.12-80

**Comment by malte0811** [comment]
I wasn't able to replicate this in a quick test. Could you try to reproduce this bug again, and ideally see whether it happens in singleplayer? Updating IE might also be a good idea, I fixed some wire related bugs in build 81.

**Comment by JackRuby1** [comment]
It seems like it's fixed in 307 update of the modpack, I tried a couple different ways of getting it to happen and it didn't happen. I'll keep an eye out and if I notice it happen again, I'll let you know.
