### ISSUE TITLE
[1.12.2] Advanced Coke Oven Crash

### ISSUE THREAD

**Issue by jefferyrlc** [BluSunrize/ImmersiveEngineering#2983]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
Describe what happens, how it affects your game/gameplay and provide screenshots where possible.

When using the engineering hammer on a fully build advanced coke oven multiblock to complete the build the game crashes. Happened consistently upon retrying. Was performed in singleplayer, and has not been tested in a multiplayer environment.

### Crashlog:
If your Minecraft instance has crashed, a file will have been generated in the folder `crash-reports` of your minecraft folder. To understand what has happened, we need to know the content of that file. But please don't just put it directly in your report (that makes it hard to read), upload it to a site like [pastebin](http://pastebin.com) or [gist](http://gist.github.com) and put a link in the actuall bug report.

Link to crash report: https://paste.ee/p/RYkmf

### Versions & Modlist
IE and Forge versions are mandatory. *Note that saying "latest" is **not** valid. Always give the proper version number*
Other mods should be listed (with their versions) in a [pastebin](http://pastebin.com) or [gist](http://gist.github.com) upload. The easiest way to get these lists is a crashlog, you may force one with F3+C.
If your game crashed (see above) you may omit the modlist, but IE and Forge version would still be nice.

Also, please try testing an issue in a minimal instance, with just IE, Forge and maybe JEI. That makes elminating compat issues easier.

IE Version: 0.12-81
Forge Version: 14.23.3.2655

### Lastly (you may delete this from the report itself)
Please, for the love of all that is voxelbased, read the contribution guidelines. They are linked above in the yellow box.
When reporting issues, these are crucial, and the team withholds the right to close an issue for the plain stupidity of not reading and adhering to them.

Thank you for reporting issues, without people reporting them, they wouldn't get fixed. You're helping contribute to this mod and that is much appreciated <3

**Comment by malte0811** [comment]
The advanced coke oven is from Immersive Tech, not IE.
