### ISSUE TITLE
[Minetweaker] [Suggestion] Arc Furnace recipes with multiple output items

### ISSUE THREAD

**Issue by CelestialPhoenix** [BluSunrize/ImmersiveEngineering#2985]
Would it be possible for the Arc Furnace to output an array of [up to 6] items?

I was playing around with the ore processing chain, and though it'll be neat if the Arc Furnace could smelt ores into primary metal and the secondary byproducts;
```mods.immersiveengineering.ArcFurnace.addRecipe([output array], input, outputSlag, time, power);```
by example; magnetite ore yields iron, gold, and vanadium metals
```mods.immersiveengineering.ArcFurnace.addRecipe([ingotIron*3, ingotGold, nuggetVanadium*4], <ore:oreMagnetite>, slagRich, 2000, 2048);```

Might also be useful for recycling components/machines back into their base metals.

Modlist-https://docs.google.com/spreadsheets/d/1yTnDKD7qsu8KCYs17JFRDdhtQFbfn5lUK6M_49YW6SQ/edit?usp=sharing
Forge 14.23.2.2611

**Comment by BluSunrize** [comment]
Recycling recipes do this natively, but I currently don't have plans to extend this to Minetweaker because tbh, the Arc Furnace should just be smelting everything into a pulp >_>
It's not very sensible for it to be able to smelt ores into finely separated outputs.

**Comment by CelestialPhoenix** [comment]
I kinda agree about the pulp thing; diamond ore just gives slag and ashes. Redstone and Lapis were also planning to be fairly destructive. (basically anything non-metallic or volatile gets destroyed, leaving only the metals behind).
Getting a pile of separated metals out is a bit of an abstraction, but I think its one that 'fits' well with Minecraft. Similar to a stone furnace smelting whole ingots, or the Rock Crusher making neat piles of metal dust.
