### ISSUE TITLE
[1.12.2] Floodlight direction is not correct when placed on the wall

### ISSUE THREAD

**Issue by Blue-Beaker** [BluSunrize/ImmersiveEngineering#2986]
Forge 14.23.2.2651
IE 0.12-80
![2018-05-06_17 11 37](https://user-images.githubusercontent.com/17115547/39671732-a9e150a2-5150-11e8-89ca-b4c4a8596bca.png)
Floodlight always lights up in the back of the shown direction when placed on the wall.

**Comment by malte0811** [comment]
I haven't been able to replicate this. Please upload a full modlist, try updating IE to build 81 (I doubt that will fix it, but it's good practice to use the latest version for bug reports) and test whether this happens in a test world (something like a creative superflat world).
