### ISSUE TITLE
UV mapping errors

### ISSUE THREAD

**Issue by Slye-Fox** [BluSunrize/ImmersiveEngineering#299]
I've found some UV mapping errors on a couple of the models;
Since 0.5.1(maybe 0.5.0 too not sure) the work bench's UV has been shrunk so the textures are stretched out in-game.
On the Excavator's wheel, part of the side texture has the UV longer than it should be, so the textures don't mesh correctly: http://i.imgur.com/nCEFOwY.png

**Comment by bakaxyf** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/161#issuecomment-118054876
:P

**Comment by Slye-Fox** [comment]
Oh, so where should I send this info?

**Comment by bakaxyf** [comment]
[twitter](https://twitter.com/Damien_hazard)?

**Comment by BluSunrize** [comment]
Don't report the workbench to Damien. I made changes to it, I'll need to check.
