### ISSUE TITLE
OreDictionary: Alumuinum

### ISSUE THREAD

**Issue by rsandfield** [BluSunrize/ImmersiveEngineering#2992]
Forge 14.23.1.2601
IE 0.12-76
Dimensional Ores 1.0.1

Dimensional Ores aluminum does not work as Immersive Engineering aluminum.

**Comment by ProxyPlayerHD** [comment]
check if they are both in the OreDict under the same name. i know IE uses "ingotAluminum" (where i still don't understand why it uses the less common American written version, but whatever i guess). maybe the second mod you said uses "ingotAluminium"
