### ISSUE TITLE
"Compat module for tconstruct could not be preInitialized. Report this!"

### ISSUE THREAD

**Issue by zackeezy** [BluSunrize/ImmersiveEngineering#2993]
### Description of the issue:
I crashed and was looking through my log.  I don't think this is why it crashed, but I was told to report it, so I am.

### Crashlog:
[pastebin](https://pastebin.com/2AUyWYKu)

### Versions & Modlist
*IE:* 0.12-82
*Forge:* 14.23.3.2689
*Tinkers Construct:* 2.10.0.75

**Comment by malte0811** [comment]
Could you try using [this](https://ci.blamejared.com/job/Immersive%20Engineering/386/artifact/build/libs/ImmersiveEngineering-0.12-82-386.jar) build of IE? It will not fix the bug (at least I'd be very surprised if it did), but it will give useful log output rather than what it currently gives.

**Comment by zackeezy** [comment]
https://pastebin.com/FkrQmax6

https://pastebin.com/0ZqBhgPm

The first one is the full error log, and the second one I grep'd for immersiveengineering.  It loses some of the stack traces in the error messages but I figured it'd help isolate any problems.
