### ISSUE TITLE
Wire Cutters consumed in wire recipe

### ISSUE THREAD

**Issue by Mijithemidge** [BluSunrize/ImmersiveEngineering#2996]
I am not sure if this is a bug or supposed to happen, but instead of wearing down like the hammer does when used in a recipe, the wire cutters are just consumed. This is making me run through a lot of wire cutters for what should be a small project of a kinetic dynamo.

**Comment by Mijithemidge** [comment]
Shears are not consumed, strangely.

**Comment by HistoriaGamer** [comment]
I'm having the same issue.

**Comment by malte0811** [comment]
What version of IE are you using?

**Comment by HistoriaGamer** [comment]
the one for MC version 12.2

**Comment by HistoriaGamer** [comment]
I got around the issues by using the sheers

**Comment by malte0811** [comment]
There are about 20 versions of IE for Minecraft 1.12.2. One of these has the bug, one shouldn't have it and the others certainly don't have it.

**Comment by HistoriaGamer** [comment]
Well thanks for not telling Us what version it was.

**Comment by CorwinCZ** [comment]
@HistoriaGamer you can check the version you are using (forge is showing it to you) - then search for list of all versions of IE for MC 1.12.2, pick the newest one, install it and test again :)

**Comment by Mijithemidge** [comment]
The version I have is 0.12-81. Sorry for not sending this ASAP, I've misplaced my phone. It was the "latest" on curse under the 1.12 section.

**Comment by BluSunrize** [comment]
Build 82 was released two weeks ago, it fixed the issue. Go update.
