### ISSUE TITLE
[1.12.2 FTB Revelation] IE 0.12.80 Carrots and Rice take inordinately long in Garden Cloche

### ISSUE THREAD

**Issue by WebDragon** [BluSunrize/ImmersiveEngineering#2999]
Am running a set of Garden Cloches to make two separate Pam's Harvestcraft foods - Veggie Stirfry, and Roasted Root Veggie Medley. However, both carrots and rice lag *severely* behind the overall growth speed of all the other Pam's veggies. my spice leaf, turnips, eggplant, bell peppers, noo problem. But, carrots and rice are an absolute bottleneck, to the point where all the other cloches are full of their respective veggies, and the analog crafters are just waiting on the carrots (and/or rice) to complete the next food item. 

Using default FTB Revelation modpack, so ImmersiveEngineering-0.12-80-core.jar ImmersiveEngineering-0.12-80.jar are what is currently running.

**Comment by MalkContent** [comment]
can you check if that is controlled by a config/minetweaker edit?

**Comment by WebDragon** [comment]
It turns out the Rice I was using was the Actually Additions rice, not the
Pam's Harvestcraft rice -- after switching to that, the only bottleneck in
the series is now the carrots

Let me see if I can find any minetweaker settings that might be affecting
the carrots growth rate and I'll get back to you on that

**Comment by WebDragon** [comment]
I checked in the FTBRevelation/minecraft/tscripts/(00_recipe_changes|01_unification).zs files, but didn't find anything relevant to either carrots, or the garden cloche. BTW it's now CraftTweaker, as the official continuation of minetweaker 3. 

I have also since the original report, updated to Revelation 2.1.0 and started a brand new world (for the worldgen on thaumcraft, twilight forest, etc) and recently just set up a similar setup as before, and am still experiencing the problem wherein carrots take an extraordinarily longer time to grow than the rest of the harvestcraft plants. 

currently at ImmersiveEngineering-0.12-82.jar and Pam\'s\ HarvestCraft\ 1.12.2u.jar

I can include screenshots of the setup if desired.
