### ISSUE TITLE
[Compatibility Request] Material integration with Construct's Armory

### ISSUE THREAD

**Issue by Voxel-Friend** [BluSunrize/ImmersiveEngineering#3001]
A new add-on released recently for TiCon Called Construct's Armory! https://minecraft.curseforge.com/projects/constructs-armory . It looks really good! It only adds base tinker's materials, saying "All other add-ons will have to do integration on their end as I generally only want to include features that are in base Tinkers' Construct." As such, I request compatibility for this awesome mod!

**Comment by Voxel-Friend** [comment]
Also, he/she is quoted to have said "I'm definitely all about cross-mod integration, so if they needed anything from me to make that happen, I'd be quite cooperative." Here is the github page: https://github.com/TheIllusiveC4/ConstructsArmory

**Comment by TheDeviantCrafter** [comment]
I'd like to see this implemented as well.
