### ISSUE TITLE
[1.12.2]  Breaker switch not working properly

### ISSUE THREAD

**Issue by EvangelopoulosPanagiotis** [BluSunrize/ImmersiveEngineering#3002]
Greetings,

I'm using forge 14.23.3.2655 
and Immersive Engineering 0.12-82

I am using a breaker switch to control all the lights in my house. Using the switch does not affect the lights. It only changes its output when I restart the game. For example, I turn the switch to the off position  but the lights remain on. If I close the game and restart it, the lights are now off. Now if I try to turn them back on again, I'll have to restart the game once more.

Have a nice day

**Comment by MalkContent** [comment]
Do they stay on forever when you switch the power off, or do they turn off eventually?
And what happens when you kill the power by other means, say, by removing a vital relay?

**Comment by EvangelopoulosPanagiotis** [comment]
They do stay on forever. Same goes for the metal press that i have in the same grid. 
If I remove a relay then they shut off. They also flicker when I use the metal press that its on the same grid.

**Comment by Silver07** [comment]
This is most definitely an issue, One of the switches in my base fails to cut power as intended, unless I update the wiring network (removing/adding something) or restarting the server.
It appears most frequently on networks that have multiple branches.

**Comment by Silver07** [comment]
After some testing, Redstone breaker works as intended. Also, I have a computer from opencomputers, it also displays the same effect as the lights. Normal breaker fails to change its state properly until the wiring network is changed or the game is restarted. Flipping the breaker again results in everything not turning on, until (again) another update is made.

**Comment by malte0811** [comment]
I haven't ever managed to replicate this. If it happens again, it would be great if you could upload the world (or at least the relevant regions) somewhere as a test case for me.
