### ISSUE TITLE
[1.12.2] [Enhancement] Electric fences, and colored iron sheetmetal

### ISSUE THREAD

**Issue by darthvader45** [BluSunrize/ImmersiveEngineering#3004]
There are two things I think this mod may still be lacking, and those are electric fences and colored iron sheetmetal.  

**Colored Iron Sheetmetal**
I know I can just use electrum/constantan/lead/uranium/etc. sheetmetal as a replacement, but considering that uranium may become radioactive in the future (especially with a molten salt reactor in the plans), I don't want to have to deal with an irradiated hangar.

**Electric Fences**
Yes, I know, sounds modern/futuristic and against the dieselpunk aesthetic of this mod, but hear me out.  We have steel fences, and we have electricity.  Combine the two (by attaching a connector to a fencepost and running live wire to it, we effectively electrify the fence, making it quite dangerous to those who dare
cross it.  Sure, one can simply use low-hanging wires, but those aren't exactly like electric fences.

**Comment by BluSunrize** [comment]
First one is a pain to do. If you want full RGB dying that would make each sheetmetal a TileEntity, which is a nope, and even with just the 16 base colours, that's a lot of extra blocks.

The latter is already kinda in IE. You can electrify the razorwire to make it shock as well as stab.

**Comment by darthvader45** [comment]
Huh, didn't know that.  However, if the latter were also available, it'd
make steel fence more than just decorative or part of a multiblock.  Maybe
colored sheetmetal can be part of an addon?  Just simple 16 dye colors is
enough for me.  Immersive Decor, a nice addon name dontcha think?

Golden rule in Minecraft: Never dig straight down.
