### ISSUE TITLE
[1.12.2] items cant be extracted automatically frok garden cloches

### ISSUE THREAD

**Issue by Sanofus** [BluSunrize/ImmersiveEngineering#3008]
I was not able to extract items. I treid hoppers, Ender Conduits and Thermal Dynamics.
![2018-05-24_05 14 31](https://user-images.githubusercontent.com/26455012/40462780-ccd1409e-5f11-11e8-898d-57350c19c353.png)
![2018-05-24_05 14 06](https://user-images.githubusercontent.com/26455012/40462781-ccece9b6-5f11-11e8-9036-566dfc2f4f26.png)

Forge 2071
IE 82

**Comment by BluSunrize** [comment]
Try a block higher, where the actual output is.
