### ISSUE TITLE
[1.12.2] NullPointerException while looking at RFTools Sequencer

### ISSUE THREAD

**Issue by ofseaandstars** [BluSunrize/ImmersiveEngineering#3011]
### Description of the issue:
Looking at a sequencer from RFTools crashes the client. I was building an Endergenic generator setup from RFTools, and as soon as I placed the sequencer down, I received this crash. Once I logged back into the server, it crashes immediately. I had a friend visit my base, and as soon as he looked down at the sequencer the crash occured. 

I am unsure if this is an RFTools or Immersive Engineering issue, however, due to Immersive Engineering being mentioned in the crash log, I am posting here.

### Crashlog:
https://paste.dimdev.org/hepupanuqe.txt

### Versions & Modlist

Immersive Engineering: 0.12-82
RFTools: 1.12-7.33
Forge: 14.23.3.2698

**Comment by malte0811** [comment]
This crash should not happen IMO, and the context makes no sense at all. Some of the mods you have installed (CreativeCore and LittleTiles) make changes to MC's networking code, could you try without these mods?

**Comment by AshenGaming** [comment]
Can do, I'll test it asap and post my findings.
