### ISSUE TITLE
[1.12] Sample Drill Ticking Null Pointer

### ISSUE THREAD

**Issue by artdude543** [BluSunrize/ImmersiveEngineering#3013]
### Description of the issue:
Had a report posted on the SevTech Tracker: https://github.com/DarkPacks/SevTech-Ages/issues/2637

I don't have access to a game today to confirm myself but I've seen the crash before on a few streamers using the pack. So it's partially confirmed I guess? But this could already be fixed in later versions. Just wanted to put this up so your aware and if it's fixed then I can tag it as fixed in next update ^_^

### Crashlog:
https://gist.github.com/ChAyLom/36045162efd3d8d5c91c4143b72eae7f

### Versions & Modlist
I.E: 0.12-82
Forge: 14.23.3.2679

**Comment by malte0811** [comment]
Are there any ore veins in the nether (where this happened according to the SevTech issue) in SevTech?

**Comment by artdude543** [comment]
Sorry for the delay in responding a new report came in and made me re-look the issue.

OW Ores no. But nether quartz and standard TiCon generation are normal. Along with the Vanilla Nether Biomes (Which are rare use the normal generation) but most of the nether is generated but NEX. Which could be causing the issue. But that has it's own Nether Quartz handling/generation. So maybe?
