### ISSUE TITLE
[1.12][Suggestion] Ability to extend wooden posts

### ISSUE THREAD

**Issue by DrParanoia** [BluSunrize/ImmersiveEngineering#3014]
Hi there! First of all - LOVE THE MOD! Great work guys.

The thing is, that using HV Wires on 4 block tall posts is dangerous. Would be really nice if there was an ability to extend posts.

There was a mod called "Immersive Integration" that added Extended wooden posts to IE, but it's outdated. 

Thanks!

**Comment by CorwinCZ** [comment]
What about tall steel posts? Simillar to this:

![image](https://user-images.githubusercontent.com/2243025/40961654-7e66d9c8-68a3-11e8-8358-aa606361991e.png)

Would be easy to distinguish between LV/MV vire posts and dangerous HV posts (which are cause of 75% of my deaths on my server...)

**Comment by mindforger** [comment]
use scaffolds and structural arms to build your power towers :D

i do that at least to keep them wires away from my head

**Comment by DrParanoia** [comment]
Yeah, these metal ones look awesome! 

While you can use other stuff to build taller structures, they are not as functional :( You can't have a "mini" version of a transformer witout a post.
