### ISSUE TITLE
[1.1.12] Heavy Plated Shield "Crashes" Everyone Else

### ISSUE THREAD

**Issue by SyncStelar** [BluSunrize/ImmersiveEngineering#3015]
When player with Heavy Plated Shield is looked at, the game's frame rates drops to zero. When the shield is removed, the game's frame rates recover. This occurs every time we meet the sole player holding the shield.

Please note that Optifine was installed after the recent "crashing" to combat the issue but did not work. So, issue still occured whether Optifine was installed or not.

Since it doesn't exactly crashes the player, rather lagging the player really hard that they only can have zero frame rates, it didn't drop a crash log.

Modlist: https://pastebin.com/Lziq4CNd

**Comment by BluSunrize** [comment]
I have so far been unable to replicate this with two clients in my dev environment.
This may be a crossmod issue.

Can you replicate this with just IE?
