### ISSUE TITLE
[1.12.2] Breaker switch deletes wires atached to it when toggled.

### ISSUE THREAD

**Issue by Pixelmnkey** [BluSunrize/ImmersiveEngineering#3017]
Hello! I'm playing the latest sevtech modpack wich contains ImmersiveEngineering-0.12-80-core, trying to separate 2 wires with a breaker switch, they're mv insulated cables, when I toggle the switch all the wires back to my powergen just disapear, it's intended? It's a known issue? 

Thanks!

**Comment by malte0811** [comment]
Disappear or burn up (are there flame particles when they vanish, make sure you have particles turned on)? Also some screenshots would be great, ideally of all sections of the line (if this is still happening).

**Comment by Pixelmnkey** [comment]
Didn't see any particles, but I figured it was due to overconsumption, I though they would only burn if more energy were produced than the demanded, not the other way around.

**Comment by mindforger** [comment]
well, things have internal capacity, so most producing machines have an internal buffer that can empty out at very high rates, so when switching on machines that have an empty buffer the chances aree high for a heavy power surge

**Comment by Pixelmnkey** [comment]
I see, I just connected some heaters to the wires :/
