### ISSUE TITLE
(1.7.10) 0.7.7 crashes when i install highest ii can go is 0.5.4

### ISSUE THREAD

**Issue by Dwarfy-Dwarftins** [BluSunrize/ImmersiveEngineering#3019]
[crash-2018-05-28_00.31.43-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/2044115/crash-2018-05-28_00.31.43-client.txt)

**Comment by mindforger** [comment]
please post the actual crash to pastebin or similar and link it, it is incomplete and unreadable like this
also 1.7.10 is way old, but if you make it readable, we may figure that one out

**Comment by Dwarfy-Dwarftins** [comment]
i think that info might be helpful so going off assumption is there an add more id mod that can increase the amount of ids allowed?

**Comment by Dwarfy-Dwarftins** [comment]
of course and thank you for the help ill do that rn. Thank you for your patience  btw.

**Comment by Dwarfy-Dwarftins** [comment]
i hope this is the correct format to view if not let me know

**Comment by BluSunrize** [comment]
You're using an outdated version of Minetweaker, you will need to update it.

**Comment by mindforger** [comment]
to be precise you need the beta one, that ends on a "C" in it's Version if i remember right

**Comment by Dwarfy-Dwarftins** [comment]
lol was it really that simple hahah that never came up for my outdated mods,  Thank you soo sooo much. you have no idea how long ive been trying to make that work and it was just an outdated mod that never came up as outdated

**Comment by mindforger** [comment]
that is the restart which i talked about, dunno if it is compatible with IE, as IE went on in MC version at this point
