### ISSUE TITLE
[1.12] Engineer's Hammer repairing in crafting field duplication glitch

### ISSUE THREAD

**Issue by gradle22** [BluSunrize/ImmersiveEngineering#3026]
### Description of the issue:
When you are putting two Engineer's Hammers inside your crafting field, you can craft a brand new one, while the first two hammers stay there and lose one durability point per craft.

The same issue occurs when combining two wire cutters in a crafting field to create a Voltmeter! 

And when you combine two Voltmeters, it creates a weird item called "item.immersiveengineering.tool..name"

### Versions & Modlist
Forge Version: 14.23.4.2705
IE Version: 0.12 - 82

### Screenshots:

![2018-06-02_12 55 41](https://user-images.githubusercontent.com/36933273/40873630-5797a822-6664-11e8-8751-5a3929876648.png)
![2018-06-02_12 55 45](https://user-images.githubusercontent.com/36933273/40873631-57ade524-6664-11e8-91e3-bccdb6768b22.png)
![2018-06-02_12 55 49](https://user-images.githubusercontent.com/36933273/40873632-57c4ed64-6664-11e8-89c2-a00f07a72537.png)

![2018-06-02_13 04 27](https://user-images.githubusercontent.com/36933273/40873677-8b028e9c-6665-11e8-82b8-5516b0f9b444.png)
![2018-06-02_13 04 31](https://user-images.githubusercontent.com/36933273/40873678-8b195280-6665-11e8-8371-3c31a97362f3.png)
![2018-06-02_13 04 39](https://user-images.githubusercontent.com/36933273/40873679-8b2f7326-6665-11e8-9310-4b9761cf44f6.png)

**Comment by malte0811** [comment]
#2990. Fixed for the next release.
