### ISSUE TITLE
Recipes using immersiveengineering:ingredient_shaped match empty space if bigger than 3*3

### ISSUE THREAD

**Issue by GotoLink** [BluSunrize/ImmersiveEngineering#3027]
https://github.com/BluSunrize/ImmersiveEngineering/blob/4ae5e026edd5e698540cf2bb1596cd2125f72c9e/src/main/java/blusunrize/immersiveengineering/common/crafting/RecipeShapedIngredient.java#L162
Should be inv.getWidth() , and similar inv.getHeight() below.
Test Code:
```
InventoryCrafting inv = new InventoryCrafting(new Container(){
                    @Override
                    public boolean canInteractWith(EntityPlayer playerIn) {
                        return true;
                    }
                }, 9, 9);//Example big empty space
                IRecipe recipe = ForgeRegistries.RECIPES.getValue(new ResourceLocation("immersiveengineering:wooden_devices/reinforced_crate"));//One of the affected recipe
recipe.matches(inv, world)//Returns true
```
### List of impacted recipes:

- immersiveengineering:wooden_devices/reinforced_crate
- immersiveengineering:wooden_devices/item_router
- immersiveengineering:wooden_devices/fluid_router
- immersiveengineering:wirecoils/wirecoil_mv_ins
- immersiveengineering:treated_wood/treated_wood
- immersiveengineering:toolupgrades/drill_lube
- immersiveengineering:stone_decoration/insulating_glass
- immersiveengineering:stone_decoration/concrete2
- immersiveengineering:stone_decoration/concrete
- immersiveengineering:metal_decoration/redstone_engineering
- immersiveengineering:metal_decoration/radiator
- immersiveengineering:material/torch
- immersivepetroleum:tool/projector
- immersivepetroleum:stone_decoration/asphalt2
- immersivepetroleum:stone_decoration/asphalt
- immersivepetroleum:misc/drill_lube_alt

Related:
https://github.com/GotoLink/RecipeHandler/issues/15

### Setup:

- MinecraftForge 1.12.2-14.23.4.2705
- thedragonlib-1.12.2-5.2.0
- ArmorPlus-1.12.2-11.13.0.40
- ImmersiveEngineering-0.12-82
- ImmersivePetroleum-1.12.2-1.1.9
- NoMoreRecipeConflict-0.10(1.12.2)

**Comment by Morpheus1101** [comment]
Is this fix in 0.12-82 ?
