### ISSUE TITLE
[Suggestion] Special coils

### ISSUE THREAD

**Issue by A-new-Account** [BluSunrize/ImmersiveEngineering#3029]
May you can use an antiseptic wood stick and others to make a 'Empty Coil' and can craft with LV/MV/HV lines to get a 'LV/MV/HV Coil' with lore such as 'Contains 15m of LV line'.

And also , may each connection not needs A coil, try calculate how long is the distance and use this number of line.

LV Coil
- Contains 13.7m of LV line.
- Contains 12m of MV line

**Comment by A-new-Account** [comment]
Tip: My english is poor. Try ignore syntax error

**Comment by malte0811** [comment]
I think I know what you are talking about, and I already have the code for it in Industrial Wires. If @BluSunrize wants to have this in IE I'll copy it over. Might be something for the 1.13 update?

**Comment by BluSunrize** [comment]
Nah, I'm not fond of the idea.

With one coil per connection you know exactly how much you need.
With that change, you could instead have situation where you ned 13 meters of coil but only have 12.9 left. That seems really inconvenient and I don't want to do that to players.
