### ISSUE TITLE
[BUG]Engineer's workbench and Blueprints

### ISSUE THREAD

**Issue by CannonFotter** [BluSunrize/ImmersiveEngineering#303]
I think this picture can show the bug clearly.(Thanks to @bakaxyf )
![iebule](https://cloud.githubusercontent.com/assets/10368307/9172142/f736d866-3fa3-11e5-8a9b-2dcb8c29e2eb.gif)

**Comment by CannonFotter** [comment]
Another video : https://youtu.be/tzsJnUMRn9Q

**Comment by mindforger** [comment]
duplicate #287, please use search first before opening issues ... and close this one please

**Comment by CannonFotter** [comment]
Sorry...I's my mistake
