### ISSUE TITLE
[Suggestion] External Heater works for Alloy Kiln?

### ISSUE THREAD

**Issue by darthvader45** [BluSunrize/ImmersiveEngineering#3030]
@BluSunrize I was thinking about how best to improve the kiln's efficiency and a thought hit me: why not use the external heaters?  Could it be possible that they could be used to improve the kiln's speed similar to the furnace and the preheaters for the improved blast furnace?  If so, this would be a boon for the early-game alloy smelting enthusiast who needs tons of alloy for the wires needed to connect up machines.

**Comment by BluSunrize** [comment]
While an idea, it would look kinda ugly, because the Alloy Kiln is 2x2 :V

**Comment by darthvader45** [comment]
Hmm, then perhaps an increase to the alloy kiln's size is in order?  3x3
wouldn't look too bad.  Could get a new model too.

Golden rule in Minecraft: Never dig straight down.

**Comment by MalkContent** [comment]
may be prettier with the blast furnace preheaters:
![grafik](https://user-images.githubusercontent.com/7753414/41506358-a205de88-721c-11e8-9bf3-0dc166cd16bd.png)

**Comment by mindforger** [comment]
i must say here from an esthetic (hope that's spelled right) standpoint that not all machines have to look symetrical at all, slapping on a single 1x1x3 on to an qubic 2x2x2 machine doesn't look bad at all

also malk's interpretation looks cool to be honest

**Comment by BluSunrize** [comment]
I have no plans to implement this in the future
