### ISSUE TITLE
[Bug]Thermal Foundation and Immersive Engineering Coal Coke  disappears in Crusher

### ISSUE THREAD

**Issue by xILikepuddingx** [BluSunrize/ImmersiveEngineering#3031]
### Description of the issue:
https://files.ilikepudding.de/v8nuawuvhk.mp4
you use the crusher and throw in some coal coke (no matter which mod) and throw the coal coke of the other mod in directly, the coal coke disappears, which was thrown out last.

### Versions & Modlist
Modpack: Modern Skyblock 3
Immersive Engineering: 0.12-82
Forge: 2705

**Comment by ErdrickXLII** [comment]
I also had this happen to me, but with copper ore.  I threw three partial stacks of three different mods' copper ore into the crusher, and only the first one was processed.  The other two were just eaten.  (After refunding myself the deleted ore and just waiting for the crusher to finish each stack before putting in the next one, it worked just fine.)
