### ISSUE TITLE
Shaders on Shaders not working on anything besides Drill and Revolver

### ISSUE THREAD

**Issue by Drullkus** [BluSunrize/ImmersiveEngineering#3032]
Uploading to here so it's not forgotten. Am using latest build hot off the press (83-403)

<img width="605" alt="screen shot 2018-06-06 at 3 42 10 am" src="https://user-images.githubusercontent.com/5010174/41033489-a3c2bb18-693b-11e8-96b3-af7d856fb8e1.png">

<img width="706" alt="screen shot 2018-06-06 at 3 42 18 am" src="https://user-images.githubusercontent.com/5010174/41033501-ad5093d0-693b-11e8-8760-0734dfee921a.png">

**Comment by Drullkus** [comment]
Regular OpenGL stuff doesn't seem to be working on Shields, Railguns, and Chemthrowers either. Check out the Ancient Shader (Blue bits that should be pulsating isn't pulsating) and the IKELOS Shader (The Gold circuit should be pulsating, but it isn't).

**Comment by BluSunrize** [comment]
I fix
