### ISSUE TITLE
[1.12.2] Strange cable connexion (visual glitch)

### ISSUE THREAD

**Issue by freelancerleno** [BluSunrize/ImmersiveEngineering#3033]
### Description of the issue:
I wanted to do some tests on one of my dedicated profiles for this when I noticed a connection problem on Immersive Engineering cables. In both cases, I feel that the connections are really random and sometimes, they are done correctly. This bug is just visual, the energy circulation is functional.

### Versions & Modlist:
Forge version: 14.23.4.2707 (latest) (teste with 2705 also)
IE: 0.12-82
Other mods used (from forced crash report): https://gist.github.com/freelancerleno/0470199fc1d86c75fea93c67e72badee

Normally, I also use mods like Optifine but to discard these mods in possible conflicts, I removed them all for my tests.

**Tests with all mods listed in the gist:**
First wiring attempt:
https://prnt.sc/jroyql
Second wiring attempt:
https://prnt.sc/jrp03v
I also see that thing:
https://prnt.sc/jrp0o9

Of course, I tested with Forge and Immersive Engineering without any other mods:
https://prnt.sc/jrp1q6

Thanks!
(Sorry for my bad english)

**Comment by TheSnowyChickens** [comment]
I have sometimes the same visual glitch, if I destroy 1 relay or connector and replace him again at the same position, this little wire (from freelancerleno 3. picture) occures in relation to the old wire way to the connected relay / connector. 

(I hope you know, what I mean :D )

**Comment by MatthiasMann** [comment]
The issue is with the transformers attached to the poles - they somehow have wrong offsets/positions for their connectors. It helps if you put a MV relay directly next to the transformer and connect via that as it hides the bad connection inside the transformer.
![2018-09-11_23 48 16](https://user-images.githubusercontent.com/6777029/45389825-61727d00-b61d-11e8-9f08-24bd6cc6721f.png)

**Comment by Svish** [comment]
I'm getting a lot of these, with both the `Transformer` and the `HV Transformer`:

![2018-11-11_18 30 44](https://user-images.githubusercontent.com/142162/48316196-9d579d80-e5e0-11e8-9e1b-b056b159e8f3.jpg)

"Annoyingly" it doesn't always happen... seems to somehow depend on where things are and the distance between them... 🤔
