### ISSUE TITLE
[1.12] (Crash) immersiveengineering.common.items.ItemDrill.getHead

### ISSUE THREAD

**Issue by Havik0311** [BluSunrize/ImmersiveEngineering#3036]
### Description of the issue:
Crashes at startup of Minecraft

### Crashlog:
https://pastebin.com/0NuCCcbV

### Versions
ImmersiveEngineering-0.12-82
Forge-14.23.4.2707

###Edit
Might thing the crash is caused by base-1.12.2-3.8.0.jar

**Comment by BluSunrize** [comment]
Note an IE issue, report to BASE.
