### ISSUE TITLE
[1.12.2] Game crash from Solar Reflector

### ISSUE THREAD

**Issue by Sascha-Stelling** [BluSunrize/ImmersiveEngineering#3037]
My game crashes when looking directly at the Solar Reflector multiblock. Here's the [crash report](https://pastebin.com/FKSVsWPS). The first few times the whole game crashes, then I get kicked from the server with the error message "Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host" when trying to reconnect. For the first few seconds when the world is not completely rendered I was able to walk away from the Solar Reflector and after two server exceptions I was able to play again. Then I was able to cover the multiblock with cobblestone and no crashes. However, when I tried to break a block from the multiblock structure the game crashed again. 
I use Optifine, but other people on the server face the same issue without them using Optifine. 
I could observe that the multiblock seems so be two 3D models in one when looking at it. However, when I rejoined the server the multiblock looked just like it's supposed to look. 
We later wer able to break the multiblock using TNT and no crashes since then.

Since it only crashes when looking at it and not when covered behind other blocks I would guess this is a rendering issue (in the crash report it says somethin with sun rays which might be important as well).

**Comment by malte0811** [comment]
IE does not add a Solar Reflector.
