### ISSUE TITLE
1.12.2 java.lang.NullPointerException: Initializing game  (Item Drill)

### ISSUE THREAD

**Issue by jusitnboggs** [BluSunrize/ImmersiveEngineering#3038]
Game crashed on startup

Log
https://pastebin.com/x2kDiLXr

Forge: 14.23.4.2707
IE: 0.12-82

**Comment by The-Arcanian** [comment]
I have a similar crash, they diverge after "net.minecraft.item.ItemStack.<init>(ItemStack.java:98)"

https://gist.github.com/The-Arcanian/6d6b37d3e85a8204a09c6577dbace915

Only core mods in common are Immersive Engineering and Quark. So it is not Foamfix.

Forge: 14.23.4.2705
Immersive Engineering: 0.12-82

**Comment by The-Arcanian** [comment]
Still crashed when IE was backdated to 0.12-80 and quark is removed.

**Comment by Eggonomicon** [comment]
Did you update the B.A.S.E mod?

Try reverting it to base-1.12.2-3.7.2.jar, and it should work.

The BASE mod is the "com.teamacronymcoders.base.modules.tool.ToolModule.itemStackCaps" part.


~Eggonomicon

**Comment by The-Arcanian** [comment]
Backdating B.A.S.E. to 3.7.2 and it dependent Content Tweaker to 4.5.0 fixed it.

**Comment by BluSunrize** [comment]
Yeah it's a BASE issue. It's also been reported beforem, please use the search function next time.
