### ISSUE TITLE
1.12.2 Crash on start

### ISSUE THREAD

**Issue by CreeperBossVJ** [BluSunrize/ImmersiveEngineering#3040]
Forge-14.23.4.2705
ImmersiveEngineering-0.12-82
[crash-2018-06-08_15.25.35-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/2086387/crash-2018-06-08_15.25.35-client.txt)

I have tried different versions of the mod and forge.

**Comment by BluSunrize** [comment]
Use the search function, it's a BASE issue. Disable the tools feature in their config or downgrade.
