### ISSUE TITLE
Immersive Engineering fluid pipes causing CTD from tessellation.

### ISSUE THREAD

**Issue by Minalia** [BluSunrize/ImmersiveEngineering#3042]
Immersive Engineering fluid pipes causing CTD from tessellation.
OpenGL: ERROR RuntimeException: No OpenGL context found in the current thread.
Crash log: https://pastebin.com/mQ4sAK37

Game Version: 1.12.2
Running Forge 14.23.4.2707
Server Created on SevTech Version: 3.0.7
Modpack SevTech Version: 3.0.8
Java Version: 1.8.0_171
Launcher Used: 2.0.1049
Memory Allocated: 8GB
Server/LAN/Single Player: Server, connected internally 127.0.0.1
Optifine Installed: no
Shaders Enabled: no

**Comment by BluSunrize** [comment]
Can you reproduce this without better foliage?

**Comment by LastXsile** [comment]
Having this issue as well.

Crashlog: https://pastebin.com/dPziFhbB

Game Version: 1.12.2
Running Forge 14.23.4.2707
Server Created on All The Mods 3 5.9.6b
Modpack All The Mods 3 5.9.7b
Java Version: 1.8.0_171
Memory Allocated: 6GB
Optifine Installed: Yes and No, Tried both
Shaders Enabled: no

**Comment by mindforger** [comment]
the only similar i find outside of MC itself is in all three reports 
>at codechicken.lib.render.block.CCBlockRendererDispatcher.func_175018_a(CCBlockRendererDispatcher.java:64)

is this maybe some sorrt of connected texture thing ?

**Comment by LastXsile** [comment]
@mindforger There is some correlation to that theory. As Immersive engineering version do not change between me not crashing and then crashing after I update my pack.

Before update CodeChickenLib-1.12.2-3.1.8.341-universal.jar, after the update i crash on CodeChickenLib-1.12.2-3.1.9.344-universal.jar.

**Comment by malte0811** [comment]
@mindforger there are two different crashes here: one NPE directly in `getConnectionByte` and one somewhere in `getTileEntity`. The former is due to people implementing their capabilities incorrectly, the latter probably is a multithreading issue (both Blu and I learned about `getExtendedState` being allowed to be called from other threads just a few days ago).

**Comment by mindforger** [comment]
@malte0811 thx for clearing it up :)

**Comment by DiscipleOfUrza** [comment]
After removing all mods except for EnderIO, EnderCore, and Immersive Engineering, I was able to recreate this crash after first placing an Immersive Engineering pipe, then placing an EnderIO fluid conduit next to it.

[https://pastebin.com/b2tS7Q1s]

Game Version: 1.12.2
Running Forge 14.23.3.2655
Java Version: 1.8.0_171
Memory Allocated: 7GB
Optifine Installed: No
Shaders Enabled: No

This did not occur with any other mod's fluid pipes when attaching to an IE pipe, so I assume it has something to do with the EnderIO conduits specifically.

Will create a new ticket on the EnderIO issue tracker to see if they can resolve it.

**Comment by LastXsile** [comment]
Spotted this so I think this issue is mostly resolved.
https://github.com/SleepyTrousers/EnderIO/issues/4697

**Comment by Minalia** [comment]
Well, my original issue had nothing to do with EnderIO. The pipes causing the crashes were going vertically alongside a relay of IE MV cables that branch throughout the superstructure of my fortress. The only adjacent blocks, in this case, would have been Stone, Sarsen Stone, Jungle planks siding, Sakura planks, MV relays and MV insulated cables.
