### ISSUE TITLE
[1.12] [MP] Extracting conveyor drops a conveyor without NBT tags

### ISSUE THREAD

**Issue by usernameak** [BluSunrize/ImmersiveEngineering#3045]
### Description of the issue:
Extracting conveyor drops a conveyor without NBT tags, so when it is placed back it gets pink&black and not moving.

### Versions & Modlist
IE: git build b27934ed7cb4b6be4faa9f724691a31887cd5551
Forge: 14.23.4.2705

**Comment by BluSunrize** [comment]
Modlist, crashlog, pictures, tool used, instructions for reproduction?

Please read the contribution guidelines and provide these accordingly.

**Comment by usernameak** [comment]
> crashlog
it doesn't crash
> tool used
stone pickaxe
> modlist
look at the top
> instructions
craft the belt, place it, break it

**Comment by BluSunrize** [comment]
And that's why I told you to read the contributoin guidelines. Debug crashes are a thing.

**Comment by BluSunrize** [comment]
yeah, I can't reproduce this.

**Comment by BluSunrize** [comment]
Would you *please* provide the debug crash then?

**Comment by usernameak** [comment]
On the server or on client? And if on the server, how?

**Comment by BluSunrize** [comment]
Client would be a start

**Comment by usernameak** [comment]
https://gist.github.com/usernameak/11c785821b42a22fa3fdabd6ecdb3dd8
well, and i found some other problems with it. it doesn't seem to suck up items in multiplayer and when you place it and open the inventory, you get a duplicated belt under your mouse cursor. everything is okay in SP

**Comment by usernameak** [comment]
UPD: i have noticed some errors in the server log
https://gist.github.com/usernameak/8d8c90b5103dc5ff6c1ffa7d2be256df

**Comment by BluSunrize** [comment]
Could you fetch the latest log of the server as well?

**Comment by usernameak** [comment]
look at my prev comment

**Comment by BluSunrize** [comment]
See, when you provide logs, I actually get an idea what to do.
Try it again with a build that includes the commit above.

**Comment by usernameak** [comment]
now i get another error
https://gist.github.com/usernameak/ac78c718cd9c1120135348cce0474bf7

**Comment by BluSunrize** [comment]
Try again

**Comment by usernameak** [comment]
Works, closing...
