### ISSUE TITLE
Disable Garden Cloche?

### ISSUE THREAD

**Issue by ResqDiver1317** [BluSunrize/ImmersiveEngineering#3046]
We are running a new custom 1.12.2 modpack I built for our community. The theme of this pack is low tech, low automation and focuses on building. I added IE as a way for player to get some power to run lights and such and a little machinery as IE's multiblock machines look great in this pack. The issue I have is we do not want players to be able to automate things like farming so I am wondering if there is a way to disable the cloche in the configs?

**Comment by belathus** [comment]
You can disable crafting it with crafttweaker. Just create a script in the script folder with a name like "cloche.zs" and have it contain the following:

```
#modloaded immersiveengineering
recipes.remove(<immersiveengineering:metal_device1:13>);
```
