### ISSUE TITLE
Suggestion: vacuum tubes should be made with nickel instead of copper

### ISSUE THREAD

**Issue by belathus** [BluSunrize/ImmersiveEngineering#3048]
### Description of the issue:
For some reason I was reading about invar and learned that nickel is often used to make vacuum tubes. Since nickel generally has few uses in modded Minecraft, and it is added by IE, I thought that using it for something like vacuum tubes would be an ideal use for it.

Source: https://www.electronics-notes.com/articles/electronic_components/valves-tubes/electrodes-cathode-grid-anode.php. Just search for nickel. I found other sources, too, but they were all scanned pages or PDFs, and were almost all locked behind paywalls.

Here is what started my reading about this, and lead me to writing this issue (search for vacuum tubes): https://www.cartech.com/en/alloy-techzone/technical-information/technical-articles/after-100-years-the-uses-for-invar-continue-to-multiply

### Crashlog:
N/A

### Versions & Modlist
Forge: 14.23.3.2961
IE: 0.12-82

**Comment by BluSunrize** [comment]
I used copper wire for the sake "we already have it".
I'm generally not too big of a fan of making non-reusable components and something like a nickel-wire would be very limited in its one use.

Admittedly, it is underused in most tech mods, IE included. It's food for thought for sure, but only if someone points me to a way of doing it without then having a very single-use item.

**Comment by BluSunrize** [comment]
That could work actually.
Maybe one nickel plate and one copper wire, to repesent cathode and anode?

**Comment by Alaberti** [comment]
I am unreasonably excited about this
