### ISSUE TITLE
NullPointerException TileEntityFluidPipe.getConnectionByte

### ISSUE THREAD

**Issue by yaroslav4167** [BluSunrize/ImmersiveEngineering#3049]
### Before reporting:
Having removed the block, I disoriented from the crash. ([Replaced by dirt](http://bit.ly/2LFwz2o))
### Description of the issue:
I destroyed part of the multi-block structure and my game crashed.

### Crashlog:
[Log](https://paste.dimdev.org/oqegetofik.mccrash)

### Versions & Modlist
Forge: 14.23.4.2705
IE: 0.12-82
OtherMods: [img](http://bit.ly/2LGIkWn)

**Comment by SealabJaster** [comment]
I'm having this crash as well. It happened after placing an immersive engineering fluid pipe next to an Ender IO fluid conduit (which just so happens to also be in the OP's picture, where his dirt/pipe is next to one of these conduits).

# How to Reproduce
Placing a fluid conduit (EIO) and fluid pipe (IE) together triggers the crash. (tested in a fresh creative world)

# Crashlog
https://pastebin.com/nskMxG03

Modpack: Enigmatic 2 Expert Version 1.26c (MC 1.12.2, Forge-14.23.4.2705, IE 0.12-82)

**Comment by omnislash772** [comment]
Can confirm this happens, does not take down server but has put several people on my server into a crashloop

**Comment by Vitali8** [comment]
The same issue. Crashes only the client. Therefore, place IE's liquid pipes and any fluid conduit EnderIO's is bad idea. 
[Client crash](https://gist.github.com/Vitali8/6396b08e3dc403f74357e1e318080fe7).
![image](https://user-images.githubusercontent.com/34043968/41931223-20903d3c-7986-11e8-8b4e-ed9f86a77919.png)

**Comment by BluSunrize** [comment]
fixed for next release.
