### ISSUE TITLE
[1.12.2] Slab placing crash

### ISSUE THREAD

**Issue by darthvader45** [BluSunrize/ImmersiveEngineering#3050]
### Description of the issue:
Occasionally when placing slabs, the game says "internal server shutting down" and then crashes.

### Crashlog:
https://pastebin.com/y3NWkeM5

### Versions & Modlist
IE version 0.12-82
Forge 1.12.2-14.23.4.2705

**Comment by mindforger** [comment]
i could swear there is some optifine in the trace but i can't spot it in the list... PlayerOF was it?

**Comment by KnightMiner** [comment]
Lines 128, 227, and 228. Sometimes its not in the mod list but still installed, I just do Ctrl+F

**Comment by darthvader45** [comment]
Yeah, I don't think Optifine is hacky enough to interfere with block placement.  It merely does visual and optimization changes.

**Comment by darthvader45** [comment]
I'll try without Optifine, but since I'm not going to be placing slabs much, it won't be too big of a deal.  Besides, I'll be updating soon anyways.
