### ISSUE TITLE
Immersive Engineering Shaders

### ISSUE THREAD

**Issue by Drullkus** [BluSunrize/ImmersiveEngineering#3053]
Leaving this here not as a request, but as a reminder to self when I write some shaders for IE:

- [ ] Electro
  - Click for a bigger picture: <img width="50" alt="screen shot 2018-06-14 at 1 21 07 am" src="https://user-images.githubusercontent.com/5010174/41400182-41479e18-6f71-11e8-8180-382d158b303e.png">
  - Renders basically an electric field. Consider turbulent or fractal noise for this one.
- [ ] Quantum
  - See Slime Rancher's Quantum Slimes.
  - Dark Yellow, with Bright yellow animated swirl, billboarded so it's always facing the camera. Glitchy effects too with fragments and vertices.
- [ ] Ender
  - Ask TTFTCUTs if he's cool with using the End Portal shader. Possibly theme the gun like an End Portal frame as well.

**Comment by CTB33391** [comment]
Quantum Slime shader? Electrical field? Count me in
