### ISSUE TITLE
[1.7.10] Texture issue with 3D models

### ISSUE THREAD

**Issue by notsoup210** [BluSunrize/ImmersiveEngineering#3054]
Screenshot: https://image.prntscr.com/image/BrufAfqtTHao1PNYzG8LcQ.png

IE version: 0.7.7
Forge version : 1614

I have optifine (HD_U_D6) installed so it could be a bug on their part BUT it does not happen with other 3D models from any other mods, only IE's models.

**Comment by notsoup210** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/1007
This^ is somehow related since when I deleted optifine I got the same crash
And in the post, it mentioned Greg's SG craft which breaks some sort of texture stitching code.

I have GregTech installed and the main issue only started happening when I recently installed it in my pack
Hopefully I can get a fix without having to use optifine and looking at the ugly texture sheet mess on the beautiful IE models

**Comment by BluSunrize** [comment]
1.7 is no longer supported
