### ISSUE TITLE
[1.12.2] LV wire server crash

### ISSUE THREAD

**Issue by tinyzooseven** [BluSunrize/ImmersiveEngineering#3056]
I am not an admin for the server I play on but the server crashes sometimes when I place a LV cable between 2 connectors

**Comment by NillerMedDild** [comment]
I'll provide some more info, I'm not the server admin either, but the admin sent me the crashlog as I'm the pack dev.

Crashlog: https://gist.github.com/NillerMedDild/f344b238dbf03c19027cae8d334fe1c4

Minecraft 1.12.2
Forge 1.12.2-14.23.4.2705
ImmersiveEngineering-0.12-82

**Comment by mindforger** [comment]
oh wow that looks like an ancient error, it seems there are too many data stored in a specific chunk that was being updated and then sent to a player, overrunning the network buffer ... this may even have to do with the networkcode of sponge at some point

**Comment by BluSunrize** [comment]
Yeah that chunk is just overloaded. There is basically nothing we can do about that.
