### ISSUE TITLE
Crash from wire

### ISSUE THREAD

**Issue by kave777** [BluSunrize/ImmersiveEngineering#3057]
### Description of the issue:
When i am dying from a wire , i can't respawn and after a crash happens
### Crashlog:
here is the crash - https://paste.ee/p/WfjKP
### Versions & Modlist
minecraft version - 1.12.2
forge- 14.23.4.2708  
immersive engineering - 0.12-82

**Comment by BluSunrize** [comment]
Report to llibrary, they're in the stacktrace, not us.

**Comment by malte0811** [comment]
iLexiconn/LLibrary#81
