### ISSUE TITLE
[1.12.2] Dupe glith

### ISSUE THREAD

**Issue by bigenergy** [BluSunrize/ImmersiveEngineering#3059]
I put any object in the bag, throw it away and open the GUI at the same time, the female flies away and I take the resources, and so on, everything can be seen in the video - https://youtu.be/fe228l_tVT0
version - Release 82

**Comment by BluSunrize** [comment]
> the female flies away

I'm sorry what.
I mean, I can see what the issue is from the video, but please don't use google translate to file issues :'D
