### ISSUE TITLE
Garden Cloche rf/t Usage 1.12 All The Mods Lite

### ISSUE THREAD

**Issue by tcanfield123** [BluSunrize/ImmersiveEngineering#3061]
Hello,

I've never posted or reported issues here before, so forgive me if I break some conventions.  I read the "guidelines" and I searched for what I was looking for, but didn't find anything that seemed to be related.

Anyway, I'm playing All The Mods Lite and I noticed that the Garden Cloche seemed to be using a LOT more power than it usually does.  I wasn't sure how to measure rf/t with the mods that were in the mod pack, so I added Advanced Generators to the pack because it's GUI has native rf/t measurement.

Once I built the Advanced Generator, I hooked it up to one Garden Cloche (and only one Cloche) and the rf/t output from the Advanced Generator read 80 rf/t.  This is 10 times more than 8 rf/t.  

Was this a deliberate nerf? (People have been talking about nerfing the Cloche forever) Or is there a typo in a config file somewhere?

Thank you for your time.

**Comment by BluSunrize** [comment]
I can't tell you what the All the Mods devs do to the Cloche. I just set its default values, if they change them, that's on them, not me.

**Comment by tcanfield123** [comment]
Ok, so go talk to them.  Got it. Thank you for the quick response.
