### ISSUE TITLE
[1.11.2] Crash on startup

### ISSUE THREAD

**Issue by OmarWazzan** [BluSunrize/ImmersiveEngineering#3066]
### Description of the issue:
When both OpenModularTurrets and ImmersiveEngineering are enabled a crash occurs. When either one is disabled the game runs fine.

### Crashlog:
https://pastebin.com/gcH6hhKj

Complete Minecraft Log: https://paste.ee/p/kcQnG

### Versions & Modlist
IE: 0.11-63
Forge: 2588

**Comment by malte0811** [comment]
1.11.2 is not supported any more, but I'd be very surprised if this crash didn't happen with just IE. It should be "fixable" by downgrading Forge to 13.20.1.2563.
