### ISSUE TITLE
issue with  connecting HV wires to HV transformers

### ISSUE THREAD

**Issue by Stormcruzerlore** [BluSunrize/ImmersiveEngineering#3067]
hello their is no crash happening but I think I discovered a bug I have  the immersive engineering wires ran through my town on a private server and  when I connect the HV wires via transformer they   always disconnect themselves over time and I have to break the connector and both transformers and replace them and than rewire it it  is fine for about 15   minutes and than the wire pops off again and I have to do it all over again there are no trees  or blocks in the way I have cleared them all  and it  keeps happening I'm not sure if its a bug or if its a mod conflict I will post a mod list  and a screenshot

![2018-06-24_12 38 02](https://user-images.githubusercontent.com/30479692/41821809-97ac68fa-77ab-11e8-8136-0f3397fda16f.png)
![2018-06-24_12 38 24](https://user-images.githubusercontent.com/30479692/41821810-9bf2cc6a-77ab-11e8-9eb4-243bb32d46c5.png)

![2018-06-24_12 43 21](https://user-images.githubusercontent.com/30479692/41821843-35d4de0e-77ac-11e8-9fc1-99afc4ca331f.png)
![2018-06-24_12 43 04](https://user-images.githubusercontent.com/30479692/41821845-3771c664-77ac-11e8-878f-be1884377f4c.png)
![2018-06-24_12 42 56](https://user-images.githubusercontent.com/30479692/41821847-3930b938-77ac-11e8-9420-2f9796761f59.png)

    JourneyMap (by techbrew)
    Mantle (by mDiyo)
    Tinkers Construct (by mDiyo)
    Inventory Tweaks (by Kobata)
    Redstone Flux (by TeamCoFH)
    Ultimate Car Mod (by EuhDawson)
    ForgeEndertech (by EnderLanky)
    Advanced Chimneys (by EnderLanky)
    Mouse Tweaks (by YaLTeR97)
    BetterBedrockGen (by Gigabit1011)
    Netherending Ores (by ic_trab)
    Immersive Engineering (by BluSunrize)
    Immersive Petroleum (by theFlaxbeard)
    Immersive Tech (by ferroo2000)
    Immersive Tech OreDictionary (by LiskoSlayer)
    Biomes O' Plenty (by Glitchfiend)
    Chisels & Bits (by AlgorithmX2)
    Flat Colored Blocks (by AlgorithmX2)
    Dynamic Surroundings (by OreCruncher)
    Better Builder's Wands (by Portablejim)
    VeinMiner (by Portablejim)
    Techguns (by pWn3d_1337)
    Just Enough Items (JEI) (by mezz)
    Just Enough Buttons (by universaI)
    Extra Utilities (by RWTema)
    Baubles (by azanor)
    Ice and Fire: Dragons in a whole new light! (by alex1the1666)
    LLibrary (by iLexiconn)
    Dynamic Trees - Biomes O' Plenty Compat (by mangoose3039)
    Demonology (by DCatcher)
    Dynamic Trees (by ferreusveritas)
    EnderCore (by tterrag1098)
    Ender IO (by CrazyPants_MC)
    Mekanism (by aidancbrady)
    Mekanism Generators (by aidancbrady)
    CodeChicken Lib 1.8.+ (by covers1624)
    Ender Storage 1.8.+ (by covers1624)
    ShetiPhianCore (by ShetiPhian)
    EnderTanks (by ShetiPhian)
    Mekanism Tools (by aidancbrady)
    Chicken Chunks 1.8.+ (by covers1624)
    CoroUtil (by Corosus)
    Weather, Storms & Tornadoes (by Corosus)
    Refined Storage (by raoulvdberge)
    Refined Storage Addons (by raoulvdberge)
    Wings Horns & Hooves, the Ultimate Unicorn Mod (by KaneApollo)
    MalisisCore (by Ordinastie)
    MalisisDoors (by Ordinastie)
    CoFH Core (by TeamCoFH)
    CoFH World (by TeamCoFH)
    Thermal Foundation (by TeamCoFH)
    Thermal Expansion (by TeamCoFH)
    Thermal Dynamics (by TeamCoFH)
    Thermal Cultivation (by TeamCoFH)
    Thermal Innovation (by TeamCoFH)
    Thermal Conversion (by stuin)
    WanionLib (by WanionCane)
    UniDict (by WanionCane)
    Ender Zoo (by CrazyPants_MC)
    PneumaticCraft: Repressurized (by desht)
    JurassiCraft2 (by LordCazsius)
    BiblioCraft (by JDSinclair)
    MrCrayfish's Furniture Mod (by Mr_Crayfish)
    DecoCraft2 (by RazzleberryFox)
    Forge MultiPart CBE (by covers1624)
    CXLibrary (by CubeX2)

**Comment by malte0811** [comment]
This is known and should be fixed in the next release. By the way, HV transformers can step down to LV directly, you don't need to go via MV.
