### ISSUE TITLE
Suggestion: Metal Press use Covered Conveyor Belts to prevent misfeeding multiple machines.

### ISSUE THREAD

**Issue by HisBoySherman** [BluSunrize/ImmersiveEngineering#3068]
**Description of the issue:**

I have a pair of Metal Presses situated side-by-side. Currently one is set to produce metal plate and the other produces wire. Each press is fed by a Chest+Hopper+Covered Conveyor Belt and the output from each feeds into separate wooden crates. I'm using vanilla and trapped-chests in order to isolate the pair at the feed end.

If I feed more than ten Ingots into either Hopper, Ingots will jump to the adjacent Conveyor Belt and feed into the adjacent Press. I can't rely on a successful production run and end up spending more time managing the feed-end conveyor belts than I would if I used a crafting station, hammer and wire cutters.

Would incorporating Covered Conveyor Belts as the feed and / or output ends of the multi-block construction prevent this unwanted "belt-hopping"?

Here's a picture of the setup, focused on the problem area. The belt-hopping happens across the Metal Press input conveyor belts. 
https://imgur.com/a/NzdEiK5

**This issue does not cause a Crash.**

**Thanks for your time.** This is my first time opening an issue and I did my best to search for previous examples of this issue. Open and not-Open. If I missed something, I apologise for any hassle.

**Versions & Modlist**
Forge: 14.23.4.2705
IE: 0.12-82

**Comment by CorwinCZ** [comment]
You can feed the Metal Press directly from hopper - just move it one block down (and make it face the metal press). This will fix the issue - hopper is going to wait for Metal Press to have empty input slot.

Having covered conveyor belts wouldn't fix the issue - even then the items would pop up on contact with full Metal press.

Conveyor Belts are poping the items out when there is not enough space in target inventory - and metal press is processing intems with a slower rate then conveyor belt is moving them.

Disclaimer - I'm not a developer of this mod, just a fan :)

**Comment by HisBoySherman** [comment]
Corwin, thanks for your input. Unfortunately I can't get the Press to feed via a directly positioned Hopper. 

I tried this approach when first setting up the Presses and tried it again today with no change in behaviour. The Hopper inventory will not unload into the Press.

**Comment by HisBoySherman** [comment]
Sure, but that's a compromise. I have been trying to keep movement around the 'shop floor' efficient and the side-by-side placement works well in that regard. Looks good too.

More to the point, if a hopper feeds the press too quickly and causes inventory to spill, won't that still happen when I do a production run?

**Comment by BluSunrize** [comment]
Yeah hoopers can't insert into the metal press because it only accepts the exact quantity needed. If you have a gear that requires 4 ingots, you need to put in 4 ingots, but hoppers would only insert 1, so the press doesn't allow for that in order to avoid getting "stuck" on an incomplete recipe.
