### ISSUE TITLE
[Feature Request] Arc Furnace Mine Tweaker Support

### ISSUE THREAD

**Issue by angelnc1989** [BluSunrize/ImmersiveEngineering#307]
It would be cool to have Mod Tweaker support for the Arc Furnace.
Since you have support for all other machines this shouldn't be too hard to add.

**Comment by mindforger** [comment]
he is currently on vacation, and released 0.5.x for us to have fun with the furnace meanwhile, i am pretty sure he will add it later :P

**Comment by BluSunrize** [comment]
correct, MT support is tbd.

**Comment by angelnc1989** [comment]
Great to know.
I hope you have a nice vacation.
