### ISSUE TITLE
[1.12.2] ([main/ERROR]Texture error) preceeded by 13 lines of ([main/error][main/FATAL]) Exception loading model

### ISSUE THREAD

**Issue by alxcool** [BluSunrize/ImmersiveEngineering#3072]
#### Before reporting:
Search check, Issue name check

#### Description of the issue:
1.12.2 single player F2725 IEV82.
F) Note also that, when I use the Thermal series, I could read that mod's compatibility module could not be preinitialized, please contact mod author.
f1) So far, when I have a memory spike, I use to 	
tear apart both IE multiblocks and thermal setup, but this does'nt seem to help to reduce the slow down.

G) latest.log list many slabs as error, similar to issue #3050

#### Crashlog:
Lost my last one
[latest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/2150555/latest.log)

#### Versions & Modlist
Minimal Test check

A) Are my software up to date?
- 1.12.2 Single player using the old minecraft launcher.
forge-1.12.2-14.23.4.2725-installer-win
(suggested version 2705)
- ImmersiveEngineering-0.12-82
- CTM-MC1.12-0.3.0.15

#### Lastly 
Hi! This morning I have tried to solve a few of these warnings related to Immersive engineering, running only a minimum amount of mods. In this problem solving session, I'v asked myself a few questions which I would like to get some answers...

A) Are my software up to date?
- 1.12.2 Single player using the old minecraft launcher.
forge-1.12.2-14.23.4.2725-installer-win
(suggested version 2705)
- ImmersiveEngineering-0.12-82
- CTM-MC1.12-0.3.0.15
Aa) who created some worries

B) What about...
b1) Java? win7x64 Version 8 (build 1.8.0_171-b11)
b2) When my folder contain only 2 mods; IE-82, CTM-15, to be as stable as possible, do I need chisel?
- Chisel-MC1.12.2-0.2.0.31
b3) To be as stable... do I need at least 1 extra texture pack, like the one suggested on the CTM curseforge page?
- ctp_1.2_MCv3.zip
- https://minecraft.curseforge.com/projects/ctp/files/2457838
b4) Do I uncompress the software correctly?
- Minecraft/texturepack/ctp_1.2_MCv3 ;as uncompressed
b5) Since my Graphic chips on a toshiba satellite P850 (Intel Core i7 2.3Ghz 8MB RAM) can't run higher direct X than...
- DirectX 11. Does this mod or others parts was planned for a newer version than that one and then cause a slowdown?
b6) On github, MMD suggest either to use a different launcher for minecraft, like
- multiMC, should I use it?
b7) While reading latest.log, I've underline this : **"is missing a resource manager"**
- Should I install an additional mod who have this function, if so could someone give me suggestion, as I was not sure yet which one to use?
b8) Theses errors won't prevent minecraft to launch. Its possible to join a singleplayer game, but the processor run at his max without having any memory or graphic leaks.
- Note with the mod list previously tested, default memory use in-game is as a min 1523mb. Usually I use more than 120 mods so I need the best config possible to play as stable as possible. Is this working as planed?
b9) Should I use optifine or any lag reduction mods, if so, which ones?
- OptiFine 1.12.2 HD U E1
b10) Config folder have the option : **disable Fancy TESR**. Is there is others config option I should check about IE, to increase my computer's performance?

C) Is there is any forum, or chat I could use to ask these casual question, like a discord channel, as example? I did not find any.

D) What is the most stable version yet of both IE ± CTM?

E) Does IE staff plan to solve theses error, as it won't prevent the use of the mod?
e1) MMD suggest that "textures are not something we can fix", "the mod devs will do that and over time"
- https://github.com/MinecraftModDevelopment/New-MMD-Public-Pack/issues/54
e2) I have found more detailed topic who contain the same line in latest.log than me about **IE version76**, and now **IE is at version 82**. Does that mean mod dev don't care about theses lines?
e21) Same topic here. "**fixed a minor texture warning in the console**, closes #2640"
- Should we reopen issue #2640?
e22) on august 2017, about the same topic, Blusunrise comment : "none of those are crucial errors"
- https://github.com/BluSunrize/ImmersiveEngineering/issues/2446
e23) Sometime in-game I experiment a visual glitch, about the extremity of my Z-view, where texture is replaced by a gradient of blue. Its like if I had an extra blind-spot (angle from 80 to 90, using the middle of the screen as benchmark), usually by moving my Z, it fix by itself in a few sec, but could happen again and again.

Well good work yet, good luck with the rest and next time I'l make sure to take a screenshot about that blind spot event, or when a block swap for a missing texture, even just for a sec or two. Thk for reading all this . Let me know if you need more info!

Thank you for reporting issues, without people reporting them, they wouldn't get fixed. You're helping contribute to this mod and that is much appreciated <3

**Comment by Tingcat** [comment]
It might be something to do with Forge 14.23.4.2725 and CTM MC1.12-0.3.0.15 being incompatible [(Issue Here).](https://github.com/Chisel-Team/ConnectedTexturesMod/issues/63)
The solution they suggest is downgrading to Forge-14.23.4.2717 until CTM updates.

**Comment by alxcool** [comment]
These are comment lines that I read in latest.log. I've updated forge yesterday, previously I was using forge 2709 / 2705... The releases are too fast for me to keep up I guess :P.

As example, (sorry for the file compression, I know they are a pain to manipulate when your not used too.) If you read my shared log in my second msg, Forge version is at 2709.

I get the same comment lines using forge version 2709. but thk for your help I'l appreciate it! If I get a crash using a newer version than forge 2717, I may end up with the same crash file than you do.
At the same time, my motivation about asking that much question is because I hope this topic could help other players, at the least by giving some config or basic installation tip off. If you hae some, please let me know, then I'l update my first post!

**Comment by tterrag1098** [comment]
This is fixed in CTM 0.3.1
