### ISSUE TITLE
Kinetic dynamo not producing power from water wheel

### ISSUE THREAD

**Issue by Mase7139** [BluSunrize/ImmersiveEngineering#3075]
Place the dynamo and attached the waterwheel to it but it is not producing any power. Its all attached correctly just wont work

**Comment by mindforger** [comment]
no screens, no versions, no reading of the contribution guidelines highlighted on top of your title when creating your issue, no service? :)

**Comment by Mase7139** [comment]
Ive attached a MV connecter and conneted it to a RF energy storage but it is not outputting anything

**Comment by Mase7139** [comment]
![2018-07-02_20 52 51](https://user-images.githubusercontent.com/39789159/42154462-eadb7504-7e39-11e8-80ff-245afa3e8a1f.png)

**Comment by BluSunrize** [comment]
You've attached a relay to it. Not a connector.
Relays can't accept power.

**Comment by Mase7139** [comment]
it is a connector it says MV connector

**Comment by MrEfbiaye** [comment]
I have the same problem ... My kinetic dynamo doesn't product RF .... 

![Capture d’écran (9)](https://user-images.githubusercontent.com/34189504/63526738-27ce1580-c500-11e9-8476-f098e348a491.png)

**Comment by BluSunrize** [comment]
@MrEfbiaye 
1) Don't necropost on an issue that has been closed for over a year.
2) The dynamo doesn't have internal storage. Hook this up to a capacitor, and it'll work fine
3) Take screenshots during the daytime, it's really hard to see things otherwise.
