### ISSUE TITLE
[Request for Feature] Disable Balance-Protection for Crushing Ores wih the Hammer in the Config

### ISSUE THREAD

**Issue by ChaosNicro** [BluSunrize/ImmersiveEngineering#308]
I have found myself with a setup using thermal foundation and -dynamics without -expansion.
So -foundation adds the relative dusts but no way to make them, thus IE's balance-protection kicks in.

Problem is that I really need a way to make bronze out off copper and tin but without a way to get the dusts that is impossible.

**Comment by theunkn0wn1** [comment]
So.. if i understand your issue correctly: you do not have a method of obtaining the dusts required to make bronze? or can you not use the dusts to create bronze dust?

if the prior,
throw the tin and copper ingots/ore into the crusher, that will produce the dusts. use the dusts to craft bronze dust and use a smelter to obtain the ingots.

**Comment by ChaosNicro** [comment]
True but the game is set up with Iguana tinker tweaks meaning that bronze is a requirement for mining iron, so neither the crusher nor the TC smeltery can be used.

I could make bronze using the ingots, but I would prefer using the dusts.
I was using the aplied energistics grind stone before, but ae is supposed to be removed in a bit.

**Comment by Pihrra** [comment]
I was doing the same thing (having only Thermal Foundation and Dynamics) but I had to add Expansion otherwise it was impossible for me to start using IE (I don't want to add TC either). I would prefer if I could manually disable the balance protection and uninstall TE for this world.
Plus that way it makes it impossible to focus only on IE for managing my ore processing in the early game depending on what mods you use.

**Comment by theunkn0wn1** [comment]
OK.. i see, you want a config setting to disable how IE automatically disables ore crushing with its hammer?

**Comment by ChaosNicro** [comment]
Yes exactly, because in my case at least the crusher is the only method of obtaining dusts and the crushing mechanic was made for that exact case.

**Comment by ChaosNicro** [comment]
I don't need ore dubleing but ingots -> dust is needed
Pihrra on the other hand would like doubleing though, as I understand it.

**Comment by theunkn0wn1** [comment]
All right, this a [request for feature] thread then :P

I do agree with a need for this, as having Iguana Tweaks is not a rare scenario. Regardless of other mods that *may* or *may not* exist in a given modded MC installation, a mod that adds metals and dusts should not disable the early-game aquisition of its own items on other mods behalf without good reason, such as compatibility issues. Perhaps using the hammer to obtain dust from ore should yield the same as smelting the ore: you get one ingots worth of material out of it. This would promote building the MB structures while maintaining balance within the mod.

------------------
I recommend you modify the title of this thread to represent it is a [request for feature].

**Comment by ChaosNicro** [comment]
As said I am down with just turning an ingots into a single dust item, which should not bother balancing at all.
I am physically not able to build the crusher right now without getting 3 copper and one tin dust though.

**Comment by ChaosNicro** [comment]
It used to be a bug post because while there were dusts, there was no way to obtain them.
As I understand this the auto-disable should not have triggered here.

**Comment by theunkn0wn1** [comment]
Yeah, it kinda is a error on IE's side but you are also requesting a feature at the same time to resolve the issue. BluSunrise is currently on vacation, so don't expect any official fix for a few weeks.

**Comment by ChaosNicro** [comment]
That's ok, I just wanted to clarify what the problem is.
After all an issue tracker is supposed to track issues 
so that they can be resolved whenever he comes back.
Thanks for your help in this unknown one.

**Comment by theunkn0wn1** [comment]
No problem, the issue tracker for this mod *has* been used before for feature requests...
And this *is* an issue, and you are also providing a possible resolution for the problem so BluSunrise can more rapidly resolve the issue once he returns.

**Comment by mindforger** [comment]
does the hammer get damaged in this process? if not, why don't you use minetweaker to add an crafting recipe for the time beeing?

**Comment by ChaosNicro** [comment]
Of course I can, it's still a bug to report though.
