### ISSUE TITLE
crash by activating automated engineers workbench

### ISSUE THREAD

**Issue by Sani7** [BluSunrize/ImmersiveEngineering#3080]
When I was trying to activate the automated workbench, the game just crashed.
I play in minecraft version 1.12.2, forge version 1.12.2-14.23.4.2709 and version 82.
Crash report:
[mods.pdf](https://github.com/BluSunrize/ImmersiveEngineering/files/2164128/mods.pdf)
 look by latest version (1.1.9), 
[crash-2018-07-04_20.22.26-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/2164116/crash-2018-07-04_20.22.26-client.txt)

Thanks,
Sander Speetjens

**Comment by BluSunrize** [comment]
Closign this due to lack of response
