### ISSUE TITLE
[1.12] [Visual] Vertical conveyors don't visually connect to metal press outputs.

### ISSUE THREAD

**Issue by Shovinus** [BluSunrize/ImmersiveEngineering#3083]
### Description of the issue:
If you place a vertical conveyor directly after the metal press it does not treat the metal press's conveyor as an inputing conveyor and visually change (although the item does still go to the conveyor)

**Comment by BluSunrize** [comment]
Yeah it doesn't, and the current code setup doesn't allow for that.

I might consider it in future. In the meantime, just put another conveyor inbetween? :v

**Comment by Shovinus** [comment]
I did, it is just space saving and continuity
