### ISSUE TITLE
Structures doesn't get formed

### ISSUE THREAD

**Issue by JakobFynn** [BluSunrize/ImmersiveEngineering#3085]
Greetings there
I'm having issues with the Assembler - Minecraft version 1.12.2 as I'm building the Assembler - means when I'm right clicking on the conveyer with my hammer the conveyer rotates and the Assembler isn't build ...

The same happens when building the Bottling Machine, The Automated Workbench, The Metal Press and The Arc Furnace ...

It seems that I'm the only person with that problem momentarly - its not caused by Optifine I tested building the same structures and the rest of them once with Optifine and once without

**Comment by JakobFynn** [comment]
By the way the "bug" also happends when only the Mod Immersive Engineering (IE) is installed other mod wich I used while noticing - Applied Energistics 2 ( AE2 ), Chisle&Bits, Tinkers Construct ( TC ) and Mysticalagriculture as well as the Mods wich are needed for these Mods are not Causing any Problems

**Comment by mindforger** [comment]
check that you used the right conveyor, there are redstone versions looking the same but not working the same way

**Comment by JakobFynn** [comment]
Well then it seem that I'm unable to build since I have mistaken the3 choosen blocks 
you were right with those conyeyer belts 
The Arc Furace was just not biuld right I used Have Engeneering blocks where light Engeneering blocks should have placed sometimes and use engeniring block where I should have used Block of Steel

well then I'm a dum dum
thank you friend :D
