### ISSUE TITLE
1.12.2 Crash caused by immersive 

### ISSUE THREAD

**Issue by ZaosDaOne** [BluSunrize/ImmersiveEngineering#3086]
### Description of the issue:
Crashes Constantly

### Crashlog:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.177.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  SpongeCoremod (spongeforge-1.12.2-2705-7.1.0-BETA-3151.jar)
  Techguns Core (techguns-1.12.2-2.0.1.1.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  MovingWorldCore (movingworld-1.12-6.342-full.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy (1).jar)
  ShutdownPatcher (mcef-1.12.2-0.9-coremod.jar)
  HCASM (HammerCore-1.12.2-2.0.0.1.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.30.jar)
Contact their authors BEFORE contacting forge

// I just don't know what went wrong :(

Time: 7/6/18 10:15 AM
Description: Exception ticking world

java.lang.ArrayIndexOutOfBoundsException: 3
	at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:60)
	at net.minecraft.entity.passive.EntityVillager.func_175554_cu(EntityVillager.java:2268)
	at net.minecraft.entity.passive.EntityVillager.func_190672_a(EntityVillager.java:862)
	at net.minecraft.world.gen.structure.StructureVillagePieces$Village.func_74893_a(StructureVillagePieces.java:1791)
	at blusunrize.immersiveengineering.common.world.VillageEngineersHouse.func_74875_a(VillageEngineersHouse.java:213)
	at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:47)
	at net.minecraft.world.gen.structure.MapGenStructure.func_175794_a(MapGenStructure.java:603)
	at net.minecraft.world.gen.structure.MapGenVillage.populate(SourceFile:553)
	at org.spongepowered.common.interfaces.world.gen.IFlaggedPopulator.populate(IFlaggedPopulator.java:40)
	at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:244)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1017)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:997)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.redirect$onProvidePlayerChunk$bbb000(PlayerChunkMapEntry.java:1079)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.google.common.collect.RegularImmutableList.get(RegularImmutableList.java:60)
	at net.minecraft.entity.passive.EntityVillager.func_175554_cu(EntityVillager.java:2268)
	at net.minecraft.entity.passive.EntityVillager.func_190672_a(EntityVillager.java:862)
	at net.minecraft.world.gen.structure.StructureVillagePieces$Village.func_74893_a(StructureVillagePieces.java:1791)
	at blusunrize.immersiveengineering.common.world.VillageEngineersHouse.func_74875_a(VillageEngineersHouse.java:213)
	at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:47)
	at net.minecraft.world.gen.structure.MapGenStructure.func_175794_a(MapGenStructure.java:603)
	at net.minecraft.world.gen.structure.MapGenVillage.populate(SourceFile:553)
	at org.spongepowered.common.interfaces.world.gen.IFlaggedPopulator.populate(IFlaggedPopulator.java:40)
	at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:244)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1017)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:997)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
	at net.minecraft.server.management.PlayerChunkMapEntry.redirect$onProvidePlayerChunk$bbb000(PlayerChunkMapEntry.java:1079)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)

-- Affected level --
Details:
	Level name: world
	All players: 3 total; [GCEntityPlayerMP['Cucumbertronic'/1223, l='world', x=3623.35, y=151.87, z=27218.45], GCEntityPlayerMP['mgwerner'/6918, l='world', x=2219.50, y=66.00, z=21019.52], GCEntityPlayerMP['Zaos1'/44117, l='world', x=776.02, y=63.06, z=-20674.73]]
	Chunk stats: ServerChunkCache: 1994 Drop: 0
	Level seed: -3223147806106367487
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (43,121,190), Chunk: (at 11,7,14 in 2,11; contains blocks 32,0,176 to 47,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 52448109 game time, 53405905 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 160624 (now: false), thunder time: 110636 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false

-- Sponge PhaseTracker --
Details:
	Phase Stack: /*************************************************************************************************************/
/*   - Phase: GenerationPhase{}{TerrainGenerationState:TERRAIN_GENERATION}                                   */
/*     Context:                                                                                              */
/*     - World: WorldServer{Name=world, DimensionId=0, DimensionType=minecraft:overworld, DimensionTypeId=0} */
/*   - Phase: GenerationPhase{}{TerrainGenerationState:TERRAIN_GENERATION}                                   */
/*     Context:                                                                                              */
/*     - World: WorldServer{Name=world, DimensionId=0, DimensionType=minecraft:overworld, DimensionTypeId=0} */
/*************************************************************************************************************/

Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjg000(MinecraftServer.java:3997)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:889)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:370)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:554)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.8.13-xxxx-grs-ipv6-64
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1710645712 bytes (1631 MB) / 4139778048 bytes (3948 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -Xmx6144M -Xms1024M -XX:ParallelGCThreads=2 -XX:ThreadStackSize=512
	IntCache: cache: 12, tcache: 94, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2707 63 mods loaded, 63 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                                           | Version                     | Source                                         | Signature                                |
	|:--------- |:-------------------------------------------- |:--------------------------- |:---------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                                    | 1.12.2                      | minecraft.jar                                  | None                                     |
	| UCHIJAAAA | mcp                                          | 9.42                        | minecraft.jar                                  | None                                     |
	| UCHIJAAAA | FML                                          | 8.0.99.99                   | custom.jar                                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                                        | 14.23.4.2707                | custom.jar                                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | micdoodlecore                                |                             | minecraft.jar                                  | None                                     |
	| UCHIJAAAA | com.elytradev.movingworld.common.asm.coremod |                             | minecraft.jar                                  | None                                     |
	| UCHIJAAAA | spongeapi                                    | 7.1.0-SNAPSHOT-43d8496      | spongeforge-1.12.2-2705-7.1.0-BETA-3151.jar    | None                                     |
	| UCHIJAAAA | sponge                                       | 1.12.2-2705-7.1.0-BETA-3151 | spongeforge-1.12.2-2705-7.1.0-BETA-3151.jar    | 6729a677746f8cf63ef31881f913ed15d431b7f0 |
	| UCHIJAAAA | foamfixcore                                  | 7.7.4                       | minecraft.jar                                  | None                                     |
	| UCHIJAAAA | opencomputers|core                           | 1.7.2.67                    | minecraft.jar                                  | None                                     |
	| UCHIJAAAA | techguns_core                                | 1.12.2-1.0                  | minecraft.jar                                  | None                                     |
	| UCHIJAAAA | appliedenergistics2                          | rv5-stable-11               | appliedenergistics2-rv5-stable-11.jar          | None                                     |
	| UCHIJAAAA | bibliocraft                                  | 2.4.4                       | BiblioCraft[v2.4.4][MC1.12.2].jar              | None                                     |
	| UCHIJAAAA | codechickenlib                               | 3.1.8.341                   | CodeChickenLib-1.12.2-3.1.8.341-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | computercraft                                | 1.80pr1                     | ComputerCraft1.80pr1.jar                       | None                                     |
	| UCHIJAAAA | cosmeticarmorreworked                        | 1.12.2-v1                   | CosmeticArmorReworked-1.12.2-v1.jar            | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| UCHIJAAAA | movingworld                                  | 1.12-6.342                  | movingworld-1.12-6.342-full.jar                | None                                     |
	| UCHIJAAAA | davincisvessels                              | @DVESSELSVER@               | davincisvessels-1.12-6.340-full.jar            | None                                     |
	| UCHIJAAAA | eaglefactions                                | 0.9.16                      | EagleFactions-1.12.2-v0.9.16.jar               | None                                     |
	| UCHIJAAAA | endercore                                    | 1.12.2-0.5.30               | EnderCore-1.12.2-0.5.30.jar                    | None                                     |
	| UCHIJAAAA | jei                                          | 4.9.2.196                   | jei_1.12.2-4.9.2.196.jar                       | None                                     |
	| UCHIJAAAA | enderio                                      | 5.0.25                      | EnderIO-1.12.2-5.0.25.jar                      | None                                     |
	| UCHIJAAAA | enderiointegrationtic                        | 5.0.25                      | EnderIO-1.12.2-5.0.25.jar                      | None                                     |
	| UCHIJAAAA | enderiobase                                  | 5.0.25                      | EnderIO-1.12.2-5.0.25.jar                      | None                                     |
	| UCHIJAAAA | enderioconduits                              | 5.0.25                      | EnderIO-1.12.2-5.0.25.jar                      | None                                     |
	| UCHIJAAAA | enderioconduitsappliedenergistics            | 5.0.25                      | EnderIO-1.12.2-5.0.25.jar                      | None                                     |
	| UCHIJAAAA | enderioconduitsopencomputers                 | 5.0.25                      | EnderIO-1.12.2-5.0.25.jar                      | None                                     |
	| UCHIJAAAA | enderioconduitsrefinedstorage                | 5.0.25                      | EnderIO-1.12.2-5.0.25.jar                      | None                                     |
	| UCHIJAAAA | enderiointegrationforestry                   | 5.0.25                      | EnderIO-1.12.2-5.0.25.jar                      | None                                     |
	| UCHIJAAAA | enderiointegrationticlate                    | 5.0.25                      | EnderIO-1.12.2-5.0.25.jar                      | None                                     |
	| UCHIJAAAA | enderiomachines                              | 5.0.25                      | EnderIO-1.12.2-5.0.25.jar                      | None                                     |
	| UCHIJAAAA | enderiopowertools                            | 5.0.25                      | EnderIO-1.12.2-5.0.25.jar                      | None                                     |
	| UCHIJAAAA | extracells                                   | 1.12.2-2.5.0aNIGHTLY        | Extra-Cells-2-Mod-1.12.2.jar                   | None                                     |
	| UCHIJAAAA | ic2                                          | 2.8.16-ex112                | Industrial-Craft-2-Mod-Experimental-1.12.1.jar | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJAAAA | galacticraftcore                             | 4.0.1.177                   | GalacticraftCore-1.12.2-4.0.1.177.jar          | None                                     |
	| UCHIJAAAA | galacticraftplanets                          | 4.0.1.177                   | Galacticraft-Planets-1.12.2-4.0.1.177.jar      | None                                     |
	| UCHIJAAAA | mjrlegendslib                                | 1.12.2-1.1.4                | MJRLegendsLib-1.12.2-1.1.4.jar                 | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCHIJAAAA | extraplanets                                 | 1.12.2-0.3.8                | ExtraPlanets-1.12.2-0.3.8.jar                  | b02331787272ec3515ebe63ecdeea0d746653468 |
	| UCHIJAAAA | foamfix                                      | 0.9.9.1-1.12.2              | foamfix-0.9.9.1-1.12.2-anarchy (1).jar         | None                                     |
	| UCHIJAAAA | gravestone                                   | 1.0.12                      | Gravestone-Mod-1.12.jar                        | None                                     |
	| UCHIJAAAA | griefprevention                              | 1.12.2-4.3.0.598            | griefprevention-1.12.2-4.3.0.598.jar           | None                                     |
	| UCHIJAAAA | hammercore                                   | 2.0.0.1                     | HammerCore-1.12.2-2.0.0.1.jar                  | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| UCHIJAAAA | inventorytweaks                              | 1.63+release.109.220f184    | InventoryTweaks-1.63.jar                       | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | luckperms                                    | 4.2.17                      | LuckPerms-Sponge-4.2.17.jar                    | None                                     |
	| UCHIJAAAA | nucleus                                      | 1.4.0-S7.0                  | Nucleus-1.4.0-S7.0-MC1.12.2-plugin.jar         | None                                     |
	| UCHIJAAAA | magibridge                                   | 2.4.5.1                     | MagiBridge-API7-2.4.5.1.jar                    | None                                     |
	| UCHIJAAAA | mcef                                         | 0.9                         | mcef-1.12.2-0.9.jar                            | None                                     |
	| UCHIJAAAA | meem                                         | 1.0                         | MeeM-1.0.jar                                   | None                                     |
	| UCHIJAAAA | redstoneflux                                 | 2.0.2                       | RedstoneFlux-1.12-2.0.2.3-universal.jar        | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | mekanism                                     | 1.12.2-9.4.10.345           | Mekanism-1.12.2-9.4.10.345.jar                 | None                                     |
	| UCHIJAAAA | mekanismgenerators                           | 9.4.10                      | MekanismGenerators-1.12.2-9.4.10.345.jar       | None                                     |
	| UCHIJAAAA | mekanismtools                                | 9.4.10                      | MekanismTools-1.12.2-9.4.10.345.jar            | None                                     |
	| UCHIJAAAA | morpheus                                     | 1.12-3.3.2                  | Morpheus-1.12-3.3.2.jar                        | None                                     |
	| UCHIJAAAA | recipehandler                                | 0.10                        | NoMoreRecipeConflict-0.10(1.12.2).jar          | None                                     |
	| UCHIJAAAA | nei                                          | 2.4.1                       | NotEnoughItems-1.12.2-2.4.1.233-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | opencomputers                                | 1.7.2.67                    | OpenComputers-MC1.12.2-1.7.2.67.jar            | None                                     |
	| UCHIJAAAA | sgcraft                                      | 1.13.2                      | SGCraft-1.2-mc1.12.2.jar                       | None                                     |
	| UCHIJAAAA | solarfluxreborn                              | 3.60a                       | SolarFluxReborn_1.12.2-3.60a.jar               | None                                     |
	| UCHIJAAAA | techguns                                     | 2.0.1.1                     | techguns-1.12.2-2.0.1.1.jar                    | None                                     |
	| UCHIJAAAA | treechopper                                  | 1.2.4                       | TreeChopper-1.12.2-1.2.4.jar                   | None                                     |
	| UCHIJAAAA | webdisplays                                  | 1.0                         | webdisplays-1.12.2-1.0.jar                     | None                                     |
	| UCHIJAAAA | worldedit                                    | 6.1.8                       | worldedit-forge-mc1.12-6.1.8-dist.jar          | None                                     |
	| UCHIJAAAA | immersiveengineering                         | 0.12-82                     | ImmersiveEngineering-0.12-82.jar               | 4cb49fcde3b43048c9889e0a3d083225da926334 |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.177.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
IELoadingPlugin (ImmersiveEngineering-core-0.12-82.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
SpongeCoremod (spongeforge-1.12.2-2705-7.1.0-BETA-3151.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
Techguns Core (techguns-1.12.2-2.0.1.1.jar)
  techguns.core.TechgunsASMTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  li.cil.oc.common.asm.ClassTransformer
MovingWorldCore (movingworld-1.12-6.342-full.jar)
  
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.9.1-1.12.2-anarchy (1).jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
ShutdownPatcher (mcef-1.12.2-0.9-coremod.jar)
  net.montoyo.mcef.coremod.ShutdownPatcher
HCASM (HammerCore-1.12.2-2.0.0.1.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.30.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
	AE2 Version: stable rv5-stable-11 for Forge 14.23.1.2554
	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 1279 names; 966 stacks.
Configuration Info: IyBDb25maWd1cmF0aW9uIGZpbGUKCmNsaWVudCB7CiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSByZXBsYWNlIGVuY2hhbnRtZW50IGdsaW50IGNvbG9yIHdpdGggbW9yZSBtYXRjaGluZyBjb2xvcnMgZm9yIHNvbWUgdmFuaWxsYSBpdGVtcz8gW2RlZmF1bHQ6IHRydWVdCiAgICBCOiJDdXN0b20gRW5jaGFudG1lbnQgQ29sb3JzIGZvciBWYW5pbGxhIEl0ZW1zIj10cnVlCgogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgcG9ydGZvcndhcmQgeW91ciBsb2NhbCB3b3JsZCB3aGVuIHlvdSBzaGFyZSB3aXRoIGl0IHRvIExBTj8KICAgICMgVGhpcyBmZWF0dXJlIGRvZXNuJ3Qgd29yayBvbiBhbGwgY2xpZW50cywgeW91IGFyZSBnb2luZyB0byBnZXQgYSBtZXNzYWdlIGluIGNoYXQgaWYgaXQgd2FzIHN1Y2Nlc3NmdWwvdW5zdWNjZXNzZnVsIFtkZWZhdWx0OiB0cnVlXQogICAgQjoiTEFOIFVQblAiPXRydWUKCiAgICAjIFJlcGxhY2UgdmFuaWxsYSBmdXJuYWNlIGFuZCBicmV3aW5nIHN0YW5kIHByb2dyZXNzIGJhcnMgdG8gdXNlIHNtb290aCByZW5kZXJpbmc/IFtkZWZhdWx0OiB0cnVlXQogICAgQjoiU21vb3RoIFZhbmlsbGEgR3VpcyI9dHJ1ZQp9CgoKaXdyZW5jaCB7CiAgICAjIFdoYXQgaXMgdGhlIGNvbG9yIHdoZW4gdGhlIGhvdmVyZWQgYmxvY2sgaXMgd3JlbmNoYWJsZT8gKGNvbG9yIGVuY29kZWQgaW4gaGV4IGZvcm0gc3VjaCBhcyBSUkdHQkIpCiAgICBTOkdyZWVuPTIyRkYyMgoKICAgICMgV2hhdCBpcyB0aGUgY29sb3Igd2hlbiB0aGUgaG92ZXJlZCBibG9jayBpcyBOT1Qgd3JlbmNoYWJsZT8gKGNvbG9yIGVuY29kZWQgaW4gaGV4IGZvcm0gc3VjaCBhcyBSUkdHQkIpCiAgICBTOlJlZD1GRjIyMjIKfQoKCiJ2YW5pbGxhIGltcHJvdmVtZW50cyIgewogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgZm9yY2Utc3Bhd24gRW5kZXIgRHJhZ29uIEVnZyBvbiBFbmRlciBEcmFnb24gZGVhdGg/IFtkZWZhdWx0OiB0cnVlXQogICAgQjoiQWx3YXlzIFNwYXduIERyYWdvbiBFZ2ciPXRydWUKfQoKCg==
Pastebin Connection: Okay.
	Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                 An unsupported base software is installed: 'sponge'. This is NOT supported.
                 This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:OFF, Mekanism:ON, OpenComputers:ON, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Profiler Position: N/A (disabled)
	Player Count: 3 / 120; [GCEntityPlayerMP['Cucumbertronic'/1223, l='world', x=3623.35, y=151.87, z=27218.45], GCEntityPlayerMP['mgwerner'/6918, l='world', x=2219.50, y=66.00, z=21019.52], GCEntityPlayerMP['Zaos1'/44117, l='world', x=776.02, y=63.06, z=-20674.73]]
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

### Versions & Modlist
1.12.2

**Comment by BluSunrize** [comment]
Read the contribution guidelines and follow them, then I'll reopen this.
