### ISSUE TITLE
Crashing Apon Loading

### ISSUE THREAD

**Issue by Deegs4232** [BluSunrize/ImmersiveEngineering#309]
So I recently try to see if this mod works in any of the FTB modpacks. I first tried Direwolf20 pack version 1.7.0 for 1.7.10 and i got this message. (http://pastebin.com/zXsiqLN1). Idk if this is just a bug, a mod incompatibility, or the CrusherRecipe's not fully completed. I also have Pam's Harvestcraft added to the pack as well.

Thanks,

Deegs4232

**Comment by 55chevypickup** [comment]
You need to update ADOB. the API has changed

**Comment by Deegs4232** [comment]
It works. Thanks 55chevypickup.

**Comment by mindforger** [comment]
@Deegs4232 you know you can close an issue when it is resolved by yourself ? :)
