### ISSUE TITLE
updateMasterBlock performance issues

### ISSUE THREAD

**Issue by Sir-Will** [BluSunrize/ImmersiveEngineering#3090]
ImmersiveEngineering-0.12-82

![](https://i.imgur.com/OZNN5E6.jpg)
![](https://i.imgur.com/kngt1K3.jpg)

**Comment by BluSunrize** [comment]
No version numbers, no modlist, no debug crash, no test setup.

I'll just close this then, since you ignored the contribution guidelines in their entirety.

**Comment by Sir-Will** [comment]
Oh yea because it's not clear that markDirty is causing the performance issues.

**Comment by Sir-Will** [comment]
It's on a server so there are like thousands of immersive engineering tile entities scattered around the map. There is no simple way to reproduce this issue.

Just because it's a vanilla function doesn't mean it will not cause performance issue. All I'm asking is if you can take a look at your code and see if you can reduce the amount of markDirty calls. Right now it looks like it does call markDirty every time it receives energy and on update, this can probably be changed to only call markDirty if there is a big data difference
