### ISSUE TITLE
[1.12.2] [0.12-83] World loading crash with JEI compatibility

### ISSUE THREAD

**Issue by Axieum** [BluSunrize/ImmersiveEngineering#3094]
### Description of the issue:
Created a new world, explored for a little bit, saved and exit to main menu, went to load the world immediately again (without restarting game), and the game freezes.

### Crashlog:
[Hastebin](https://hastebin.com/apecefibow.log)

### Versions & Modlist
**Minecraft**: 1.12.2
**Immersive Engineering**: 0.12-83
**Immersive Petroleum**: 1.12.2-1.1.9
**Immersive Tech**: 1.12-1.3.10
**Just Enough Items**: 1.12.2-4.11.0.202
**Just Enough Petroleum**: 0.1

**Comment by BluSunrize** [comment]
Yeah, known issue. I'll try to get it fixed today or tomorrow.
