### ISSUE TITLE
LV Connectors refuse more than one wire.

### ISSUE THREAD

**Issue by Shiphty** [BluSunrize/ImmersiveEngineering#3097]
I love Immersive Engineering and add it to every modpack I play.  I've connected LV wires to connectors before and had no problem in the past.  I haven't played minecraft for a while and I come back and cannot connect them.  Pretty frustrating.  How am I supposed to get power?

I can connect one wire to a connector but if I try to connect a second I'm told the connection is invalid.  "You cannot attach this wire here."

I was using the latest version (0.12 - 83) and even tried downgrading to 0.12 - 82 but with no avail.

I'm using forge-14.23.4.2717 because any more recent version apparently causes my game to crash if I attempt to open the Engineer's Handbook or look at certain recipes.

I've tried reduplicating the issue in a game with only Immersive Engineering and still cannot get more than LV wire attached to an LV connector.  I can link two connectors with one wire but I cannot link a third connector to that chain with an additional wire.

If there's some major game mechanic change it's either not listed in the book or I've missed it.

Any help would be appreciated since I love your mod and would hate to have to stop using it.

**Comment by CorwinCZ** [comment]
You are missing the [relays](https://ftb.gamepedia.com/LV_Wire_Relay) - each tier has them and they are capable of connecting multiple wires. I'm pretty sure they are in manual too, same page as connectors are :)

**Comment by BluSunrize** [comment]
Yeaaaah so that mechanics change happened months ago. And it's been documented in changelog, and in the manual.

Relays and connectors are different. They have been for a while. God read up on them ;)

**Comment by Shiphty** [comment]
ARGH!

Well, there's egg on my face.

Thank you so much for your help!

**Comment by Shiphty** [comment]
Can we just pretend that I had an actual issue and you guys fixed it and no one was an idiot?

Feeling pretty dumb about now.

Anyway, thank you for your quick response.

**Comment by Shiphty** [comment]
BluSunrize, did you miss the part where I said I was getting back into
minecraft?
