### ISSUE TITLE
[1.12] Extraction Belt and Splitting Belt interaction error

### ISSUE THREAD

**Issue by Golrith** [BluSunrize/ImmersiveEngineering#3098]
### Description of the issue:
When an extraction belt feeds direct onto a splitting belt, all items are sent in one direction, but if you put a normal belt in between, the items are split correctly.

### Versions & Modlist
ImmersiveEngineering-0.12-83
Forge 14.23.4.2725

**Comment by BluSunrize** [comment]
The splitting conveyor is working fine actually, it's just a matter of tickrate and item spread.
So the reason this happens is that items group together when they are close enough:
1) The first item for instance goes right
2) The second one goes left briefly but is then grouped with the one that went right
3) The third item comes along and goes right again
4) The fourth as the same problem as the second.

The reason it works fine when you place one conveyor inbetween is that two items each stack on the straight conveyor beforehand, So you have groups of two items going correctly left and right.

You can alleviate the issue by using your wirecutter to changing the tickrate of the extracting conveyor to once every 20 ticks for instance. You'll see it working fine then.
