### ISSUE TITLE
Capacitor side sync issue thingy?

### ISSUE THREAD

**Issue by CatDany** [BluSunrize/ImmersiveEngineering#31]
Maybe put { world.markBlockForUpdate(x, y, z); } into https://github.com/BluSunrize/ImmersiveEngineering/blob/3766c1e46d90f00b6872c83fdbadf0a2227d34ae/src/main/java/blusunrize/immersiveengineering/common/blocks/metal/BlockMetalDevices.java#L217 because markDirty() won't forcefully sync it with the client.

**Comment by BluSunrize** [comment]
you're way late for that one.

**Comment by CatDany** [comment]
oops
