### ISSUE TITLE
[1.12] JEI Assert Fail on second Server Start

### ISSUE THREAD

**Issue by mjdg** [BluSunrize/ImmersiveEngineering#3100]
With the latest released version (0.12-83) Minecraft hangs if you attempt to load a single-player world for a second time, without restarting the client in-between.  The log (see [this pastebin](https://pastebin.com/i3uYAupf)) shows that an exception is being thrown when Immersive Engineering calls some JEI methods during the server start event.

This happens in an instance with only forge, JEI and Immersive Engineering installed.

**Comment by BluSunrize** [comment]
Was fixed already for next release, see #3094 

Please use the search function next time ^_^
