### ISSUE TITLE
[1.12.2 IE 0.12-84] Crash Upon Loading Regarding ItemStacks

### ISSUE THREAD

**Issue by cybercat5555** [BluSunrize/ImmersiveEngineering#3105]
### Description of the issue:
Crashed while loading game (around post-initialization), involves ItemStacks. IE -.12-83 does not have this crash even with the same mods.

### Crashlog:
https://pastebin.com/xqQpQtFx

### Versions & Modlist
Forge .2732
ImmEng 0.12-84
for the rest of the mods: https://pastebin.com/kWB1PHfF

**Comment by BluSunrize** [comment]
I suspect this is due to some mod shipping an outdated version of IE's API.
Please remove all addons to IE and try again.

**Comment by cybercat5555** [comment]
I've removed all Immersive Engineering-based addons, with just ImmEng and the other mods themselves, modlist- https://pastebin.com/P0DFxVEU

Though I still get the same crash-https://pastebin.com/cHTYF6fA
ImmEng .84
Forge .2732

**Comment by BluSunrize** [comment]
I'm afraid you'll have to resort to binary search then.
Remove half the mods (excluding IE) and see if it crashes. If it does, keep repeating it with that half. If it doens't the faulty mod is in the other half.
Keep splitting them until you figure out which mod is causing the crash.

**Comment by cybercat5555** [comment]
hm, it seems the bug went away on its own after an update to the latest forge version, thanks for your help though!

**Comment by cybercat5555** [comment]
Sorry to re-open this, but I've found the conflict: IE .84 conflicts with Gaspunk 1.4.5

**Comment by BluSunrize** [comment]
You didn't reopen it. In fact you can't.

Go file a new issue with proper version number and crashlogs.
