### ISSUE TITLE
Suggest:Assembler

### ISSUE THREAD

**Issue by HeavCruiserTakao** [BluSunrize/ImmersiveEngineering#3111]
I want to suggest Assembler can use Engineer's Hammer to increase one or two Output port on both sides of the machine because some synthetic formula like obsidian need to barreled magma and water but the machine even if connected  pipe to transmission water and lava in to the machine but the machine didn't work so I hope can make machine to make obsidian

**Comment by BluSunrize** [comment]
You can easily pipe in both liquids through the same pipe. IE's pipes are perfectly capable of this.

**Comment by HeavCruiserTakao** [comment]
That is, both liquids are already in the machine but cannot be synthesized. This is my problem.

**Comment by BluSunrize** [comment]
Provide version info and pictures of the assembler's GUI.
Please follow the contribution guidelines next time, so that your issue is more apparent.

**Comment by BluSunrize** [comment]
Works fine for me on IE 84. Please make sure to use the latest version when reporting issues.

**Comment by BluSunrize** [comment]
Closed due to lack of response
