### ISSUE TITLE
[Suggestion] A multi block computer for interacting with redstone connectors

### ISSUE THREAD

**Issue by Euphemios** [BluSunrize/ImmersiveEngineering#3112]
My idea was to create something like a difference machine (a mechanical calculator designed in 1819) as it would fit with the theme and also allow interaction with the redstone wire system to make it so you don't have massive banks of comparitors comparing various signals to control your factory but instead a single machine that you could connect a few redstone inputs and has a few redstone outputs to process the signals. If something is created that is a calculation core it could change the turret recipe to have the calculation core instead of/as well as the scope to make a bit more sense.

**Comment by BluSunrize** [comment]
Yeah somethign like that has been on my ToDO/Idea list for about a year. Haven't gotten around to it yet.

**Comment by Euphemios** [comment]
Closing due to being answered and already on todo list.
