### ISSUE TITLE
Sugestion for power storage

### ISSUE THREAD

**Issue by sugy87** [BluSunrize/ImmersiveEngineering#3115]
Hello. First omg amazing mod love it.

BUT there is a missin multiblock. A giant battery  mid-end game (like a giant car battery or somesort). Because you gave us all nice looking multiblocks like the crusher etc... 
But for power store is like.:meeh here have 1x1 block that stores huge amount off power.

The multiblock would be 3x3x3 or 5x5x5 etc.... And would have like cupplings on top like a car battery where you could attach the wires.

**Comment by Euphemios** [comment]
This has been suggested many times and hasn't been accepted yet, #1011 explains the reason behind it. Along with that you can just chain capacitors, AFAIK there is nothing that requires more power than you can produce reasonably anyway, unless you are using a modpack in which case a large scale power storage solution will be in there somewhere anyway. And you can use a comparitor and a capacitor to pulse an engine anyway if you are having generator problems, I suggest a signal of 14 going into the side as that means a HV capacitor will not really go below ~3,750,000 without a major power draw it also means you won't waste power as it is generated by filling a full capacitor.
