### ISSUE TITLE
Server crash on continuum 1.4.1

### ISSUE THREAD

**Issue by SimplyLime** [BluSunrize/ImmersiveEngineering#3116]
I updated my server to the latest version of continuum (1.4.1 release) and i've been getting this error on startup. Any help would be greatly appreciated!

https://gist.github.com/SimplyLime/93ecd73c78651531cab1b1db7d503202

**Comment by TheSnowyChickens** [comment]
Hello, little question.

Is this:
java.lang.ArrayIndexOutOfBoundsException: 0
    at blusunrize.immersiveengineering.common.blocks.TileEntityMultiblockPart.isDummy(TileEntityMultiblockPart.java:284)
    at blusunrize.immersiveengineering.common.blocks.metal.TileEntityMetalPress.func_73660_a(TileEntityMetalPress.java:63)
maybe a kind of the same crash?

(1.12.2/Forge 2739/IE 84)

**Comment by Ewallee** [comment]
I have a similar error:
https://gist.github.com/Ewallee/9bb85259570288e091ccc67757e8b593

**Comment by mindforger** [comment]
all three crashes do not have anything in common as far as i can see

please open separate issues for them and follow the contribution guidelines which can be found to the right of the issue creation window

@Ewallee your's has some optifine code in it, maybe try to reproduce without it an thanks for posting a full crashlog spoilered via gist :)
