### ISSUE TITLE
[Suggestion] Add something to Speedloaders to tell you if they have bullets in

### ISSUE THREAD

**Issue by Euphemios** [BluSunrize/ImmersiveEngineering#3118]
If it is possible I would like a way of seeing if a speedloader has bullets in while it is in my inventory without having to put it on my hotbar and selecting it.

**Comment by BluSunrize** [comment]
Yeah, will do. 
Should be in the tooltip tbh.

I'll look into it.

**Comment by PrincessRTFM** [comment]
Question: will it show:

- whether there are any bullets in it
- whether it is full or if there is empty space / spent bullets
- which bullets are in it

or some combination of the above? Or will that be a config option?

**Comment by BluSunrize** [comment]
![image](https://i.imgur.com/wTsHalc.png)


How's this then? =P

**Comment by PrincessRTFM** [comment]
Holy shit, I didn't know it was even possible to do graphical renders in tooltips. As a coder, I _really_ want to know how you're doing that; as a player, I just want to know what the _control for advanced info_ thing is about.

**Comment by Euphemios** [comment]
@PrincessRTFM It looks like its from actually addons, it gives you the Code name, OreDict name, metadata and the Unloacalised meta name

**Comment by BluSunrize** [comment]
It is indeed Actually Additions. It shows up when you have advanced tooltips enabled (F3+H).

The way that render is done is pretty simple: There is a Tooltip Rendering Event. I hook into it. I know my revolver GUI is 74px high, I render at half scale, so 37, and each line in a tooltip is 10px, so if I add 4 blank lines (or in this case, containing some placeholder text), I can find those later on in the render event and just draw on top of them.

**Comment by BluSunrize** [comment]
right, this is a thing for next release.
