### ISSUE TITLE
Russian Translation

### ISSUE THREAD

**Issue by AngryMark** [BluSunrize/ImmersiveEngineering#3119]
I was playing a lot on version 0.12-82 and there is a good, but not full translation to Russian language.

Now when i updated to the latest version with hope of really complete translation, i found that now Engineers Book is all English and doesn't have a translation at all. Don't get me wrong - i can read English text well, but i play with my friends and they can't.

When there will be translation again and why old one was removed from 0.12-83 update?

**Comment by BluSunrize** [comment]
I couldn't tell you.
I don't write the translations, they are brought in as pullrequests. I also don't know the Russian language at all, so I can't vouch for the quality of its implementation in IE.
