### ISSUE TITLE
[Request for Feature]Delineate Mod Ore type produced by Excavator

### ISSUE THREAD

**Issue by Bunsan** [BluSunrize/ImmersiveEngineering#312]
I would like to request the ability to delineate which mod ore the excavator produces. Frequently modpack makers and server admins want to reduce redundancy in ores in world. Tweaking worldgen to ensure only 1 version of each ore type. This is particularly desirable in my instance as I am making a mod pack base on Terrafirmacraft world and so I would like the veins to produce terrafirmacraft ores and minerals. I can compensate for what the excavator currently outputs but would appreciate the ability to maintain the theme and feel of the modpack.

**Comment by mindforger** [comment]
you could use Minetweaker scripts to do so, IE is supporting it

**Comment by Bunsan** [comment]
I'm aware of the Minetweaker support and am using it already. However there is no module for the Excavator.

**Comment by BluSunrize** [comment]
Because the excavator works differently. It has "minerals", meaning a collection of ore names, so multiple different minerals may contain the same ore. You can, however, use LodeLoader to add your own minerals.

**Comment by Bunsan** [comment]
I'm not wishing to change the veins of minerals. Just the mod item that are produced. If there is not a Vanilla or IE variety it chooses an ore via the ore dictionary. For example in my pack it is producing Forestry Tin. However I have purposely disabled forestry worldgen as I am building off TFC, which is a total conversion mod. I would like to be able to tell it to output for example TFC lapis or sulfur instead of vanilla and railcraft.

**Comment by primetoxinz** [comment]
you could simply remove all unwanted ores from the oredictionary

**Comment by Bunsan** [comment]
I have already tried that, but it seems that when IE registers which mods ores to use is before Minetweaker modifies the ore dictionary. For example despite removing minecraft:iron_ore (may have unlocalized name backwards) it still produces vanilla iron blocks, despite there being another item registered in the ore dictionary under ore:oreIron.

**Comment by BluSunrize** [comment]
Yeah, I think I can do that. Expect it in one of the coming commits.

**Comment by Bunsan** [comment]
Thank you.

**Comment by BluSunrize** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/e6edf0d059da1e803e9b59be44fb80184c32e2f3

Should have done the trick. To be in any IE beyond .5.3 =P
