### ISSUE TITLE
[1.12.2] Workbench not applying upgrades

### ISSUE THREAD

**Issue by Euphemios** [BluSunrize/ImmersiveEngineering#3121]
When you open and close a workbench with upgrades in a heavy shield the upgrades are saved when you close the workbench but disappear when you open it again, the items are visible in the workbench but not on the model and they are not applied to the shield when you take it out, they are still in the shield if you put the shield back.

Making any changes will allow the shield to get its upgrades back, including taking an item out and putting it back in.

After further testing this applies to all types of tool you can add upgrades to.

Mods: Just IE 0.12-84

**Comment by BluSunrize** [comment]
This seems to only happen on the first time applying upgrades.

I am able to reproduce it, but unsure as to why it happens. After taking the item out once with its upgrades applied, I am unable to reproduce the issue with that same item.

@malte0811 you got any idea on this one? :/
