### ISSUE TITLE
[1.12.2] Multiblock Structures oreDict conflicts.

### ISSUE THREAD

**Issue by UnPure** [BluSunrize/ImmersiveEngineering#3124]
### Description of the issue:
I'm currently testing some tweaks in a modpack that i'm working on. I removed the IE Steel Block from the oreDict and left only the Steel Block from Thermal Foundation active. Forming the multiblock is working fine as long as different steel blocks have the correct oreDict entry. If you destroy a block from the multiblock and force it to become its normal block form again, all steel blocks are changing to the IE versions. After that, you cant form the multiblock again because the steel blocks are not part of the oreDict. To solve problems like that it would be good if IE either checks the oreDict and is using blocks from that on "deforming" if the IE version isnt available, or if the Multiblocks are checking against IE blocks together with the oreDict and not only the oreDict alone.

### Versions & Modlist
IE: 0.12 - 84
Forge: 14.23.4.2739

**Comment by BluSunrize** [comment]
Or you could just *not* remove our blocks from the OreDict. The whole point of hte OreDict is to mark all those blocks as being equal. As such when I disassemble structures, I can rightfully rely on the blocks used being correct.
Removing entries from the dict is a really bad idea, don't do that.

This won't be "fixed" until Multiblocks get rewritten (which may or may not happen in 1.13) but even then, the fact remains that IE blocks should remain valid steel blocks.

**Comment by PrincessRTFM** [comment]
If you're trying to limit the number of different-but-equal blocks/ingots/nuggets that players get, the usual (and accepted) way is to rewrite the recipe outputs, disable the ores that provide the wrong stuff, and tweak worldgen if you want to have the same amount as when everyone was adding their own. The ore dictionary is, to my knowledge, _not_ used to determine any kind of recipe output. I suppose a modder _could_ by pulling an entry from the list (CraftTweaker lets you get the "first" entry in the list to use as output if you want it) but that's extra effort and I don't think any modder is going to. As Blu said, you're not supposed to remove things from the ore dictionary. They're in there for a reason.
