### ISSUE TITLE
Garden Cloche automatically refills fertilizer

### ISSUE THREAD

**Issue by andrewminer** [BluSunrize/ImmersiveEngineering#3125]
### Description of the issue:

I have a pair of garden cloches which are supplied with water via pipes, and power via a LV connection.  Both seem to automatically refill their supply of fertilizer each time it runs out.  This makes for an absurdly over-powered cloche.

![2018-07-21_09 52 18](https://user-images.githubusercontent.com/445000/43037627-62453436-8ccc-11e8-9cff-35bfb05eab16.png)
![2018-07-21_09 52 29](https://user-images.githubusercontent.com/445000/43037628-6257d5dc-8ccc-11e8-981f-b4f5352c276d.png)

### Versions & Modlist

Minecraft: 1.12.2
Forge: 1.12.2-14.23.3.2655
IE: 0.12-80
[Full modpack](https://github.com/andrewminer/brunel)

**Comment by Euphemios** [comment]
The fertiliser is a 1x speed modifier, as far as I can tell. That makes it no faster, add bonemeal and it gets better leave it alone and its at its default speed

**Comment by andrewminer** [comment]
So... it’s normal to see the green gauge wind down and the fill itself up again?   I was expecting that it was a meter of how much bonemeal was remaining, and I’ve never actually added any bonemeal.

**Comment by BluSunrize** [comment]
Yes it is. That bar shows the resources in use. That resource is the combination of a unit of fluid and a unit of fertilizer. It's normal.
