### ISSUE TITLE
[1.12.2] Wooden Storage Crates stacking and getting emptied

### ISSUE THREAD

**Issue by chaos234** [BluSunrize/ImmersiveEngineering#3132]
Hey Blue,

the wodden storage crates are stacking even with different content. NBT-Value is always 0, nut sure if this is intended but better to mention it as not to mention it.

Well, while they are stacked they are getting truncated (there contents) which happened to me while I did a re-log which is not rly funny after all.

Forge: 2739
IE: 0.12-84.jar

Full modlist (some mods maybe out of date while reporting this): https://hastebin.com/qurovowuta.md

EDIT

New full modlist/libraries (some mods maybe out of date while this list was generated): https://pastebin.com/63WCbJfP (this time over pastebin because hastebin has either deleted the old past or it can't be loaded, whyever) - Bug/Problem still exists with the all the listed content there

Hope that this isn't a hard to fix one :)

Here are some images from my player dat file after the last backup: https://i.imgur.com/JavxJXO.png
And here is one from a backup arround 45 minutes ago: https://i.imgur.com/mCmx3RA.png

As you can see, they have gotten truncated how- and whyever.

EDIT: Not sure why, but it seems that Inventory Tweaks may cause this happen. Did not looked closely enough but it seems that IT stacks them, while using it's sorting key and if you then do a re-login all data is vanished.

Not sure if this is then only on ITs end or if it's on both ends *thinking* - Ok, with SHIFT + Klick they are stacking to, is this an IT feature?

**Comment by BluSunrize** [comment]
If the NBT Value is null, then they probably didn't save their contents in the first place.
If you pick one up and put it down, does it still have its inventory?

Also, it's Blu. No e. I'm particular on that =P

**Comment by chaos234** [comment]
Sry for that ^^

Well, I don't get it, whey the contents are getting deleted but now there content was deleted after picking them up (with content), putting them into the Tinkers Knapsack which is attached to may Construct's Armory Chestplate and after still playing for over 45+ min I turned bacj to my base with /home home command and placed down all crates an again three of them where compleatly emptied ... exactly those three, which I manually moved into the knapsack.

There was no InvTweaks involved this time, nor did I any reconnect so it seem that smth. must have deleted the item over time but I am not sure what caused the deletion :(

If you have a version with deeper debugging functionality I could maybe get smth. out more.

**Comment by BluSunrize** [comment]
Feel free to try a newer Forge. I've so far been unable to reproduce the issue.

Also, what tool are you using to break them?

**Comment by chaos234** [comment]
Sometimes empty hand but mostly any kind of axe/lumber axe

**Comment by CmdrFluffy** [comment]
Ive noticed this being an issue with this mod for a long time now, I had to stop using this mod, because of this error, I reported it awhile back, but no fix every came from it.

**Comment by Wolf-Valecos** [comment]
Hey Blu,

Seeing the same issue on 
Forge forge-1.12.2-14.23.4.2759-universal
IE ImmersiveEngineering-0.12-85

Seems to occur after a period of time of the crate being in the player inventory.

**Comment by 008nothing** [comment]
Same problem i made some tests and it seems to occur after 4-5 minutes of the player having them in his inventory .Pls fix it it makes the mod really unreliable.

**Comment by malte0811** [comment]
I just tested with my standard IE testing instance and was unable to reproduce the issue. Details are in the last paragraph if anyone is interested in them.
@008nothing @Wolf-Valecos (answers from both of you (and anyone else experiencing this) would be great):
1. Did this happen in singleplayer or on a dedicated server (or on a LAN server)? If it's a dedicated server, is it a plain Forge server or something like Sponge (if you know)?
2. What gamemode were you in during the 5 minutes before the contents vanished?
3. What did you do during those 5 minutes?
4. What other mods were installed?

Loaded mods were `minecraft, mcp, FML, forge, albedo, immersiveengineering, immersivetech, nbtedit, weirdinggadget` (IT left over from testing a different bug). Clean singleplayer world (superflat, just a bedrock layer). Added 64 TNT to a crate, switched from creative mode to survival, broke it (using a diamond axe), stood around with the crate in my inventory (in the inventory and chat GUI's) for 10 minutes and placed the crates afterwards, content was 64 TNT as expected.

**Comment by chaos234** [comment]
This is to less to reproduce it I think. You need a lot more mods or at last a Modpack, where IE is included.

Testing only with a small standard instance is not failsafe and testing only in SP is also no secure failsafe test.
It must also be tested then in MP (not over SP, over a real minecraft server).

After all it depends on what Blu is/will/can do after all but my personal opinion is, that you should test your own
Mod against many other mods to kill mod-incompatibality by default and I think, that we have smth. like this, otherwise you wouldn't have failed to reproduce it.
Am 11.09.2018 16:38:33 schrieb malte0811 <notifications@github.com>:
I just tested with my standard IE testing instance and was unable to reproduce the issue. Details are in the last paragraph if anyone is interested in them.
@008nothing [https://github.com/008nothing] @Wolf-Valecos [https://github.com/Wolf-Valecos] (answers from both of you (and anyone else experiencing this) would be great):
* Did this happen in singleplayer or on a dedicated server (or on a LAN server)? If it's a dedicated server, is it a plain Forge server or something like Sponge (if you know)?
* What gamemode were you in during the 5 minutes before the contents vanished?
* What did you do during those 5 minutes?
* What other mods were installed?
Loaded mods were minecraft, mcp, FML, forge, albedo, immersiveengineering, immersivetech, nbtedit, weirdinggadget (IT left over from testing a different bug). Clean singleplayer world (superflat, just a bedrock layer). Added 64 TNT to a crate, switched from creative mode to survival, broke it (using a diamond axe), stood around with the crate in my inventory (in the inventory and chat GUI's) for 10 minutes and placed the crates afterwards, content was 64 TNT as expected.

**Comment by chaos234** [comment]
Calm down! I simply wrote down my opinion/meaning and nothing else. If you can't read and understand it and take it personally, then you have choosen the wrong place and if you haven't noticed it yet ... I do the replays over mail and not over github, like I usually doing it, so I don't see who is maintainer/contributor/etc.

And if you think I know nothing then you are totaly false but what should I think from a person which is crying like a baby because it's brain is smaller then a bean because it is only interested in it's own stuff and doesn't takes care about the opinion/meaning from others and thinks, that this baby is all the time rigth ... think about it and don't talk back to me until you understand it, or I'll report you to github directly! FYI back, my little baby :)
Am 11.09.2018 17:19:56 schrieb malte0811 <notifications@github.com>:
Just FYI, I am also an author/dev of IE, and Blu is on vacation right now. How about you answer my questions rather than just rant about thing you evidently know nothing about?

**Comment by erindalc** [comment]
> This is to less to reproduce it I think. You need a lot more mods or at last a Modpack, where IE is included. Testing only with a small standard instance is not failsafe and testing only in SP is also no secure failsafe test. It must also be tested then in MP (not over SP, over a real minecraft server). After all it depends on what Blu is/will/can do after all but my personal opinion is, that you should test your own Mod against many other mods to kill mod-incompatibality by default and I think, that we have smth. like this, otherwise you wouldn't have failed to reproduce it. 

This is exactly why he's asking his list of questions, because sometimes bugs are weird and hard to solve, but instead of helping to solve the bug you've reported you're acting like a child.

**Comment by chaos234** [comment]
*thinking* ... No, definitly not.

It is true that debuging is hell for any developer on this world but if a bug is reported and the reporter also has added his environment, then the developer should never ever use his default environment as it will work 99%.

Means that the developer should also try to reproduce the reported bug with the same environment, like that one from the reporting user and this is, what I do on my project (even if not all are listed here on github).

Well, each dev has it's own style of debuging but as long as the environment doesn't fit into that one from the user, every debuging related to it is useless and each dev should now about this important fact!

Am 11.09.2018 17:57:09 schrieb erindalc <notifications@github.com>:
This is to less to reproduce it I think. You need a lot more mods or at last a Modpack, where IE is included. Testing only with a small standard instance is not failsafe and testing only in SP is also no secure failsafe test. It must also be tested then in MP (not over SP, over a real minecraft server). After all it depends on what Blu is/will/can do after all but my personal opinion is, that you should test your own Mod against many other mods to kill mod-incompatibality by default and I think, that we have smth. like this, otherwise you wouldn't have failed to reproduce it.
This is exactly why he's asking his list of questions, because sometimes bugs are weird and hard to solve, but instead of helping to solve the bug you've reported you're acting like a child.

**Comment by 008nothing** [comment]
1.It happened on a dedicated server and it runs plain forge the recomended
version.If you want you can join to check.
2.The first time i switched throught all gamemodes many times the second i
was in survival.
3.The first time i was teleporting to different locations. The second i was
moving my items in survival traveling with boat about 1000 blocks.
4.This is a rar file with all the mods (
http://www.mediafire.com/file/7lburvbx98oayzd/1.12.2.rar/file) *immersive
engineering is not in the rar file.And this is the list of them:Flan's
Mod,iron chest, jei, lootable bodies mod, mantle ,mw(modern warface),
optifine, tconstruct, tinker tool leveling, vein miner, immerrsive
engineering.Also the flan's mod content packs:apocalypse, mecha parts,
modern warfare, nerf, simple parts, titan, ww2, Ye olde, zompie.
Thanks in advance and i hope i helped to solve this annoying bug.

Στις Τρί, 11 Σεπ 2018 στις 5:38 μ.μ., ο/η malte0811 <
notifications@github.com> έγραψε:

**Comment by erindalc** [comment]
Is the solution Latvian listed possible? It sounds like it requires a rewrite though.

**Comment by malte0811** [comment]
It wasn't ever possible, see my comment below his. This only happens because we don't send all data (to prevent the typical crashes when filling a crate with bees/backpacks of bees). His solution would require sending all data to the client to be able to restore it from that data, so it isn't an option here (nor in most other cases where this happens).

**Comment by Wolf-Valecos** [comment]
I can respond with more detail if you'd like tomorrow as I saw this late tonight. However yes it has only happened to me since I updated to latest with switching modes, Survival and Creative. So like you said seems to be a creative issue. This is also on a multiplayer instance.
