### ISSUE TITLE
Game seems to crash for no reason [1.12.2]

### ISSUE THREAD

**Issue by leifen1** [BluSunrize/ImmersiveEngineering#3133]
IE version 0.12-84.
I do not know why the game crashed, but here is the crashlog: https://pastebin.com/nvvqe1yM
The crash occured in singleplayer. When the crash occured i was standing still.

**Comment by mindforger** [comment]
some IE conveyor tried to pull an item from an COFH machine and the machine crashed actually, you should maybe post it on both tracker

**Comment by BluSunrize** [comment]
Yeah, report that to CoFH. Their machine is throwing an IndexOutOfBounds despite me quering their slot numbers beforehand. As far as I'm concerned, not an IE issue.

Also, would be good to know what machine that was.

**Comment by leifen1** [comment]
It was one of the machines from the virtual machines mod
