### ISSUE TITLE
[suggestion] Underground wiring

### ISSUE THREAD

**Issue by viveleroi** [BluSunrize/ImmersiveEngineering#3135]
I love IE but routinely finding myself in situations where I want to bury wiring, say for outdoor lights, apiaries, etc. Sometimes cables hanging from the ceiling just doesn't look good. Unfortunately IE has no underground wiring so I resort to hooking up an HV connector to another mod, like EnderIO's conduits. That works, but visually isn't ideal.

I would highly suggest adding such a feature. Thanks!

**Comment by PrincessRTFM** [comment]
Can I take a quick tangent here? What's this about _feedthrough connectors_? I haven't seen that in my game, with 0.12-84, which is currently the latest file available on CF. Have I just completely missed what sounds like an awesome and useful thing, or is that from something else?

**Comment by mindforger** [comment]
it's a multiblock not a single item if you are looking for that

**Comment by Euphemios** [comment]
PrincessRTFM they allow you to move power through a solid block, you just need two connectors on opposite sides of a block hit them with your hammer and now power can flow through

**Comment by BluSunrize** [comment]
Answering the tangent: They are in the manual, go look there =P

Answering the original post: Yeah I don't see the point in underground wiring because it's the antithesis to what IE is at its core.
Hazard started IE because he wanted free hanging wires. That was the original pitch. I wouldn't want to undermine that (no pun intended) with underground wiring.

**Comment by viveleroi** [comment]
@PrincessRTFM I had never heard of them until recently as well, they're the last item described in the "wiring" section I believe. They've really helped me out - no more wires hanging through holes in my houses.

@BluSunrize I understand, and assumed that was the case if they didn't exist this late in the game. I personally disagree, having to use other mod packs to fill in a perceived gap in functionality at least for me breaks the "immersion". I love hanging cables, I love power poles, but I dislike having dozens of "wire fans" in areas where I have a lot of machines, it just looks bad. In some places like my industrial apiaries it's difficult to place, because of how many trees and growing items I need.

**Comment by BluSunrize** [comment]
Doesn't change the fact that it's not the aesthetic we're going for.

Plus, it'd need a pretty major adjustment of the energy transfer system (or writing a fully separate one).

I don't plan to implement block-based wiring.
