### ISSUE TITLE
What license is this repo issued under?

### ISSUE THREAD

**Issue by AnodeCathode** [BluSunrize/ImmersiveEngineering#314]
Just curious, couldn't find one in repo.

**Comment by Kubuxu** [comment]
No license so it means: All rights reserved.

**Comment by BluSunrize** [comment]
Basically it's the "You ask me before you do stuff with my code" license ;)

**Comment by AnodeCathode** [comment]
Heh, gotcha. Really was just curious as most have some license attached. Not planning on using your code to operate nuclear facilities, aircraft navigation or communication systems, air traffic control, direct life support machines, or weapons systems.

**Comment by TheLoneWolfling** [comment]
I would prefer if there was *some* license attached. Even if said license is a `LICENSE` simply stating "all rights reserved, copyright <person>", it makes it explicit.

(Also, how do pull requests work, exactly? There does not seem to be any CLA or equivalent signed, so one would have to assume that currently the copyright is assigned to everyone who ever made a pull request, which seems unworkable...)

It's an enjoyable mod, and you seem decent enough, but without something along the lines of "you won't retroactively remove permissions" I'm not going to add it to my server, at least. We all prefer to only have mods that we are allowed to fix ourselves, if/when they break or the creator is hit by a bus.
