### ISSUE TITLE
[Feature Request] Excavator config - different amounts per ore

### ISSUE THREAD

**Issue by Terrapin47** [BluSunrize/ImmersiveEngineering#3140]
I'm wondering if it would be possible to be able to specify the amount per ore that the excavator can mine up.  I'm finding it really hard to balance the excavator in my modpack, and realizing it's mainly because I want people to be able to mine up a large amount of gold/iron/etc, but not lapis/uranium and such.  So having to balance the number around the rarer ores is difficult.

Also, if it would be possible to include a range, so that the amount is random, that would be pretty cool too.

Thanks!

**Comment by mindforger** [comment]
Just make a few oredict variables for stuff like sand, dirt and stone and stuff the veins with high weight

**Comment by PrincessRTFM** [comment]
Also, the Minetweaker/Crafttweaker API lets you do custom ore veins, and you need to specify a chance for each entry. Just set the `oreGold`, `oreIron`, etc to a high chance and the rare ones to `0.05` or less. At `0.01` you have a 1% chance of that coming up, so (roughly) one in every hundred will be the thing.

**Comment by Terrapin47** [comment]
I understand the rarity of them occurring can be changed, but I'm already doing that and would rather have both things - if someone gets lucky and finds a rare vein I still don't want them getting huge amounts of it.

**Comment by PrincessRTFM** [comment]
What I mean is that you can make a single vein that contains a lot of different types of ore. I have a vein called "Precious Metals" that contains every metal (ingots I mean) in my game, and I can set the relative chance for each type to come up in each bucket. This is in 1.12.2, but the feature was around back in 1.7.10. Look into the MT/CT Excavator docs and you'll find that you pass two arrays - one has strings naming oredict entries, the others is the chance for the linked entry to be produced in any given bucket load of this vein. So if you make a vein that turns up, say, and oredict entry containing rock/dirt at a chance of `0.99` and `oreDiamond` at `0.01` then roughly every one bucket in a hundred will be a diamond ore. And you can make the numbers smaller I believe, it just has to add up to `1` total.

**Comment by BluSunrize** [comment]
Closing this, because I don't intend to have a veinsize option in the forseeable future.
