### ISSUE TITLE
[1.12.2] Crash with Gaspunk

### ISSUE THREAD

**Issue by cybercat5555** [BluSunrize/ImmersiveEngineering#3142]
### Description of the issue:
When loading the game with Immersive Engineering .84 and Gaspunk, the game crashes around the post-initialized stage of loading. I have reported the issue to the Gaspunk git as well, and they said the crash was likely on ImmEng's end. Removing either Gaspunk or Immersive from the game resolves the crash. Immersive .83 and earlier did not have this crash.

### Crashlog:
https://pastebin.com/8u3BR4Qi

### Versions & Modlist
Immersive Engineering .84
Gaspunk 1.4.5
Ladylib 2.0 (Gaspunk dependency)
Forge .2732

**Comment by BluSunrize** [comment]
Looks to me like they ship an old version of IE's api. They should probably stop doing that.

Report to them.
