### ISSUE TITLE
Weird crashes when searching for kinetic dynamo recipe

### ISSUE THREAD

**Issue by Koltanas** [BluSunrize/ImmersiveEngineering#3148]
When searching for the kinetic dynamo in creative mode the game crashes:
https://gist.github.com/Koltanas/fc3df2e831d321f449ee4579508ebd0d
It also misses in the list of IE Items from JEI:
![grafik](https://user-images.githubusercontent.com/31799364/43655961-0503b02e-9751-11e8-938b-77c73a141811.png)
Or crashes the games whe looking for the recipes possible with i.e. the copper-coil-block:
https://gist.github.com/Koltanas/cf169e028e97c642b6108d188d26f762
I already tried removing all the mods I have installed since Immersive Engineering worked.

**Comment by BluSunrize** [comment]
It crashes on chisel, not on IE. Try removing that. See if there is updated versions, or try downgrading it.

**Comment by Koltanas** [comment]
OK, weird.
