### ISSUE TITLE
[1.12] Block layering graphical bug

### ISSUE THREAD

**Issue by Rsslone** [BluSunrize/ImmersiveEngineering#3149]
### Description of the issue:
https://i.imgur.com/WbJqAaL.gifv There seems to be a graphical bug with layering or something, im not entirely sure.

### Crashlog:
N/A Client does not crash.

### Versions & Modlist
forge-1.12.2-14.23.4.2705-universal.jar
ImmersiveEngineering-0.12-84.jar

`Mods (165): Minecraft, Minecraft Coder Pack, Forge Mod Loader, Minecraft Forge, SpongeAPI, SpongeForge, /dank/null, Advanced Rocketry, Akashic Tome, Alternating Flux, Animania, Antique Atlas, AppleCore, Applied Energistics 2, Aquaculture, AutoRegLib, Automated Redstone, Avaritia, Bad Wither No Cookie! Reloaded, Baubles, Better Builder's Wands, Better Records, BiblioCraft, Binnie Core, Binnie's Botany, Binnie's Design, Binnie's Extra Bees, Binnie's Extra Trees, Binnie's Genetics, Biomes O' Plenty, Bonsai Trees, Bookshelf, Brandon's Core, CD4017BE_lib, Car Mod, CedKilleur's End Cake, Ceramics, Chameleon, Chisel, Chisels & Bits, CodeChicken Lib, Compact Solar Arrays, Construct's Armory, Cooking for Blockheads, CosmeticArmorReworked, CosmeticArmorReworked Integration for TombManyGraves2, CraftStudio API, CraftTweaker JEI Support, CraftTweaker2, CreativeCore, CreativeCoreDummy, Despawning Spawners, Diet Hopper, Doomlike Dungeons, Draconic Evolution, Dynamic Surroundings, Example Mod, Extra Cells 2, Extra Utilities 2, FTB Guides, FTB Utilities, FTBLib, FastWorkbench, FoamFix, FoamFixCore, Forestry, Good Ol' Currency Mod, Gravestone Mod, Hunger Overhaul, Immersive Engineering, Immersive Petroleum, Immersive Tech, InControl, InGameConfigManager, Industrial Foregoing, Industrial Wires, IndustrialCraft 2, InitialInventory, Integration Foregoing, Inventory Tweaks, Iron Backpacks, Iron Chest, JAOPCA, JAOPCASingularities, JEI Bees, Just Enough Items, LagGoggles, MTLib, MagicBees, Magneticraft, Malisis Switches, MalisisCore, MalisisDoors, Mantle, McJtyLib, Mekanism, MekanismTools, MineTweakerRecipeMaker, Mod Tweaker, ModelLoader, Morpheus, MrCrayfish's Furniture Mod, Multi-Storage, Natura, NetherPortalFix, Networks Manager, NuclearCraft, Nutrition, OpenBlocks, OpenComputers, OpenComputers (Core), OpenModsLib, OpenModsLib Core, OpticManager, OreDictInit, Pam's Cookables, Pam's HarvestCraft, Placebo, Platforms, PneumaticCraft: Repressurized, Power Adapters, Progressive Bosses, Quick Leaf Decay, RandomPatches, Ranged Pumps, Reborn Core, Redstone Flux, Roots 2, Shadowfacts' Forgelin, ShetiPhian-Core, Shield Parrying, Signpost, Spartan Shields, Steve's Carts 2, Storage Drawers, Super Sound Muffler, TESLA, TOP Addons, Tea: The Story, Tesla Core Lib, Tesla Core Lib Registries, Thaumcraft, The One Probe, The Twilight Forest, Thirsty Bottles, Tinkers' Complement, Tinkers' Construct, Totemic, Tree Chopper, UniDict, VanillaFix, Vulpes library, Waddles, WanionLib, Water Control Extreme, Water Strainer, Waystones, Wireless Crafting Terminal 2, Wither Skeleton Tweaks, WrapUp, XNet, Zetta Industries, magma_monsters, mob_grinding_utils, p455w0rd's Library`

**Comment by PrincessRTFM** [comment]
Use (I believe) F3+C and hold for ten seconds to force a crash.

**Comment by Rsslone** [comment]
Why would I force a crash? Its just a graphical bug.

**Comment by mindforger** [comment]
because you listed the mods from the Server while speaking of a visual bug that happens in the client, why so you ask why to do sth instead of doing it AND asking?

**Comment by mindforger** [comment]
can you test without optifine and what is this optics mod thingy?

**Comment by Rsslone** [comment]
I'll test that out and get back to you when I can. Optics is a mod that allows extended days and changing light levels. https://minecraft.curseforge.com/projects/opticmanager

**Comment by mindforger** [comment]
I just added to the other posting that you should update your gfx driver, it may Not help here but build 36 sounds heavily out dated where build 89 is current

**Comment by Rsslone** [comment]
Its only a month old. But yes I will update just to be sure.

**Comment by Rsslone** [comment]
Okay so the problem stopped. I guess it might have been Twilight Forest. I am not sure how but that's the only thing that makes sense from the changes I made in my modpack update.

https://www.technicpack.net/modpack/tommytek-1122.1228216/changelog/867202

**Comment by BluSunrize** [comment]
I wouldn't think it to be a TwilightForest problem, I'd rather think that Chisel or Optifine are causign it.

Please try removing each of them and see if the issue persists.

**Comment by PrincessRTFM** [comment]
I have a modpack with the currently-latest IE (build 84) and no optifine, I do not get this issue. My computer is easily half a decade old, too. I _do_ have CTM though. Not sure if that'll help diagnose things, but I figured I'd throw in my two cents.
