### ISSUE TITLE
Glistering Melon never be consume in potions recipes

### ISSUE THREAD

**Issue by Fireztonez** [BluSunrize/ImmersiveEngineering#3151]
I just made other report, but I think this is a different problem, so I decide to made in 2 different Issue, but for informations, you can see https://github.com/BluSunrize/ImmersiveEngineering/issues/3150

So, The probleme I found here, is using a Glistering Melon, but possibly it appen with other things I didn't try all potions or all recipes from the mixer ;)... When I add to the Awkward potion fluid, Glistering Melon, the Melon never been consume, so I can make unlimited Healing potion with only one melon and take back the melon after all that, with a Shift-Click :)... So, free Healing Potion, that's nice, but, I don't think this is Intended Feature ;)

I don't think this issues came from my Potions Mixer Recipes scripts I made, but, you can see all informations for that in my other issue... 

Here 2 capture, both with the same melon :
![mixer_unlimitedused_melon](https://user-images.githubusercontent.com/19277301/43710357-68a4721a-993d-11e8-9b64-3124ca2263cf.png)
![mixer_unlimitedused_melon-2](https://user-images.githubusercontent.com/19277301/43710358-68b5bb56-993d-11e8-9fe4-33f35d3ddd71.png)

### Crashlog:
This is not a crash, but an issue with the mod I think, so, I'm not sure if you need logs files, but if needed, I will provide-it.

### Versions & Modlist
Immersive Engineering: 0.12-84
Immersive Petroleum: 1.1.9
Immersive Tech: 1.3.10

CraftTweaker2: 4.1.9
Forge: 14.23.4.2705
Minecraft: 1.12.2

Java : 1.8.0_171 (64 bits)

FireZtoneZ

**Comment by malte0811** [comment]
Thanks for the report, I found this a few days ago and fixed it in a93f4c77ba193b6dcf09e9b95e9a9b02f47579bb.

**Comment by Fireztonez** [comment]
Ok nice!
