### ISSUE TITLE
Intermitent problem with Bottler, use fluid but doesn't fill bottle with the potion...

### ISSUE THREAD

**Issue by Fireztonez** [BluSunrize/ImmersiveEngineering#3153]
I get an issue yesterday at the end of my Live, with the Bottling Machine. The machine still have a good amount of Potion of Healing in it, but the bottle goes out is still empty, but the machine still consume the fluid.

I don't really know what can be the caused of this issue, but I try with a bucket and the bucket have been fill by Healing Potion, so the machine still work for fill thing's just doesn't always fill bottle...

When I have get Awkward Potion in the machine and it fill the bottle from Awkward potion, so this is not really consistent and not with all potions.

I think the best way to show the problem is with the part of my Live, where you can see the issue...
For information, this issue happen when I play in my private server and I can't replicate for now in my creative world in local (But, replicate Intermittent issue is always hard)...  I have try to broke the machine and reassemble, for see if this fix the issue, and I get the exact same issue.

https://www.twitch.tv/videos/293932950

### Crashlog:
I don't really know if the console logs have any usefull infromation for that issue. If you have any idea what part I can try to find, related to that issue.

### Versions & Modlist
Immersive Engineering: 0.12-84
Immersive Petroleum: 1.1.9
Immersive Tech: 1.3.10

CraftTweaker2: 4.1.9
Forge: 14.23.4.2705
Minecraft: 1.12.2

Java : 1.8.0_171 (64 bits)

Fireztonez

**Comment by BluSunrize** [comment]
Timestamp would have been nice, given that it's a 20 minute video.
Saw the issue, unsure of what caused it. I've so far been unable to replicate it however.

**Comment by Fireztonez** [comment]
ok, I think you can close the issue now, If I get back a similar issue, I will let you know...
