### ISSUE TITLE
acceleration wand works on cloche

### ISSUE THREAD

**Issue by Swantsy** [BluSunrize/ImmersiveEngineering#3154]
Hej Blu, 
Found out that the Acceleration Wand from not enough wands works on a cloche.
it was a great way of getting a bunch of sugar cane quickly though.
-Swants

**Comment by BluSunrize** [comment]
Unfortunately I don't think there is an easy way to prevent it from doing that. Unless I timestamp every tick :/

**Comment by mindforger** [comment]
i dunno if EnderIO can help you there, they seem to have a working system, maybe it is easily adaptable ?! 

i did not look at ANY code yet, but from my PoV i would probably route "onTick" for every of my blocks through a gateway that does exactly what you say :) 

with a little refactoring you could handle this probably in a breeze ... unless we get to have a breeze here .. it's so frfeaking hot today

**Comment by Alaberti** [comment]
It believe it would make more sense to have the not enough wands dev implement a blacklist if there isn't one already.

**Comment by mindforger** [comment]
sure it would, until some one else does multiticking, i thought about preventing it before complaining afterwards :) 

Like isolating blank wires before someone hurts him.... Wait... Nevermind :p
