### ISSUE TITLE
3d renders

### ISSUE THREAD

**Issue by liamjarvisman** [BluSunrize/ImmersiveEngineering#316]
How do you make the revolvers render 3d in your inventory and in hand?

**Comment by Steelsoul30** [comment]
That doesn't sound like an issue/bug but something that should go on a discussion forum.
Up to the mod author, though.

**Comment by BluSunrize** [comment]
Yeah, this isn't an issue and there is plenty of tutorials.
The short version: I use a model and a custom IItemRenderer. Check my code.
