### ISSUE TITLE
[1.12.2+][Suggestion]Diverting Conveyor

### ISSUE THREAD

**Issue by teldon** [BluSunrize/ImmersiveEngineering#3160]
I think I may have suggested something similar and more convoluted a while back, but I don't think it ended up going anywhere. Basically, all it would do is when a redstone signal is applied it would send items to the left or the right depending on how you've got the "output" set. And when the redstone signal is off it acts like a normal conveyor belt. Would be very useful in setting up multiple metal presses on a single conveyor line and not have a separate line for each metal press stamp.

**Comment by Xenoamor** [comment]
Even better yet just have this change effect the already made conveyor splitter

**Comment by BluSunrize** [comment]
Splitter & Turntable can accomplish this to an adequate degree.
