### ISSUE TITLE
[1.12.2] Skyhook crash when trying to hook downwards

### ISSUE THREAD

**Issue by Efimero** [BluSunrize/ImmersiveEngineering#3165]
### Description of the issue:
Hooking up a rope/wire works fine, but the opposite direction crashes the game with index out of bounds exception

### Crashlog:
https://gist.github.com/Efimero/70064e7e9d2ba4c83bd758069b197a76

### Versions & Modlist
IE: 0.12.48 (and 46)
Minecraft: 1.12.2
Forge: 2708
Pack: Enigmatica 2 skyblock

***CANNOT REPRODUCE ON VANILLA SETUP***
sorry, it's something with the pack, but the error comes from IE

**Comment by malte0811** [comment]
Known and fixed for the next build of IE.
