### ISSUE TITLE
CTD when attempting to craft Steel Scaffolding

### ISSUE THREAD

**Issue by mgwerner** [BluSunrize/ImmersiveEngineering#3166]
### Before reporting:
not seen
### Description of the issue:
As stated, CTD when placing rods and ingots into crafting grid

Also CTD when typing Scaffold into manual search, or clicking several times inside manual

No recipe for Steel Scaffolding in NEI/JEI

### Crashlog:
Attached
[crash-2018-08-13_19.32.37-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/2285050/crash-2018-08-13_19.32.37-client.txt)

### Versions & Modlist
ImmersiveEngineering-0.12-84
Forge 14.23.4.2746

**Comment by PrincessRTFM** [comment]
Stacktrace shows that CodeChickenLib is throwing the exception while trying to render the item. Are you using an old version of CCL? Did this happen after you updated it (or the modpack, if you're using one)?

**Comment by BluSunrize** [comment]
You're using IE version 82, please update and see if you can reproduce this crash.

**Comment by mgwerner** [comment]
Updated CCL to latest, still happening.

Using 84, BluSunrise, as indicated in report

Crashes when clicking the back button on the last page of Metal Construction in the manual.  Also no recipe being displayed in JEI/NEI for metal scaffolding, only treated wood

**Comment by mgwerner** [comment]
[crash-2018-08-14_07.01.38-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/2286627/crash-2018-08-14_07.01.38-client.txt)

**Comment by mindforger** [comment]
well this time there is factcraft in the list and some team-chisel-ctm try updating them too

maybe your modpack needs an all around update?

but you could also try turning on the recovery feature of CCL and see what happens in your world then (make a backup first)

**Comment by BluSunrize** [comment]
Yeah your CTM is way outdated.
Maybe try reproducing this in an instance with just IE, CTM and CCL first, and on latest version? See if its reproducable there, otherwise use a binary search to figure out crossmod issues.

**Comment by mgwerner** [comment]
Updating CTM fixed all issues.  

Chisel had not updated since FEB, I had not checked dependency.

Thanks for the rapid assist!
