### ISSUE TITLE
[Question] Can't get Immersive Engineering to use RF from Ancient Warefare 2

### ISSUE THREAD

**Issue by demfels** [BluSunrize/ImmersiveEngineering#3168]
I have a modpack on curese that using both IE and AW2 mods.  These are pretty much the only technology mods in the game since it is a fantasy based modpack.  

See here: https://minecraft.curseforge.com/projects/fantasy-evolved-ii/relations/dependencies

The issue I'm having is getting the power to work between IE and AW2.  I've installed Redstone Flux API and COFH Core mod, these should provide the necessary things to bring RF into the modpack and both of these mods do support RF.  

When I look at the IE connector attached to the AW2 powersource (flywheel/windmill) I see wayla says 'IF' not 'RF'.  This leads me to believe IE is not detecting that we have RF in the modpack and is defaulting to its native IF power type.  Any suggestions would be greatly appreciated!

Thanks

**Comment by BluSunrize** [comment]
IE always uses IF internally, this doesn't change even with RF mods installed.

Please provide pictures of the setup.

**Comment by BluSunrize** [comment]
Actually, followup on that, RF compat is kinda phased out since everythign uses ForgeEnergy now. I fear AW2 may not support this.
Still, pictures should help debug if it's a setup error.

**Comment by demfels** [comment]
@BluSunrize 
Here is a picture: https://drive.google.com/file/d/1LGuBbrVj1jcBa9ASTwxNpyihRsmlQOty/view

**Comment by BluSunrize** [comment]
Right, that confirms that. I also took a look at the AW2 code, and can confirm: They *only* support RF. IE uses Forge Energy to interact with other mods now, which is (in my opinion) a lot better than relying on an external API like RF.

So I can't really help you there, but maybe give the AW2 devs a poke about supporting Forge Energy?
