### ISSUE TITLE
[1.12.2] cartographer testificate interaction (OF)

### ISSUE THREAD

**Issue by Yoghurt4C** [BluSunrize/ImmersiveEngineering#3169]
### Description of the issue:
clicking/trading with a cartographer villager sometimes locks that specific villager into a core sample(?) NPE limbo on opening trade again, _seems to be a conflict with optifine_ as removing it makes the trading window work again

### Crashlog:
[log](http://pastebin.com/aRRc4AZV)

### Versions & Modlist
ImmersiveEngineering-0.12-84
forge 14.23.4.2750
_OptiFine_1.12.2_HD_U_E1_

**Comment by PrincessRTFM** [comment]
Optifine is not supported and never has been. If the issue doesn't occur without OF, Blu isn't going to do anything because OF doesn't even try to play nice with others.

**Comment by Yoghurt4C** [comment]
a config option to prevent just the maps from populating the librarian/engineer trade table would be nice, at the very least
