### ISSUE TITLE
[1.12.2] [suggestion] vaccum tube computer

### ISSUE THREAD

**Issue by blacknight7890** [BluSunrize/ImmersiveEngineering#3171]
While I am sure that the devs have seen my ramblings in their discord, I have decided to make an official suggestion for something they were probably going to add anyway at some point. The vaccum tube computer would allow a much greater amount of automation available to players without changeing much of the existing content in IE and might allow better automation of other mods. 

The basics are this, you place the parts of/build a multiblock of a machine that uses vaccum tubes to do complex computational things. The computer acts as a hub for info processing, the more you have in one mainframe, the better computing you can do, (also would take more power). Of course, without instructions, it cant do much. To access the computer, you need a computer terminal connected via a data wire (its like the redstone wire but used by the computer). The terminal is small and can be put in your house/around your base with ease, unlike the actual computer which is large and likely needs its own dedicated room/space. 

The monitor (looking like an old CRT monitor, or something from fallout) would be two blocks tall and would take both power and a data connection, input via the top on 2 diffrent connecters like the transformer. Accessing the terminal would open up a command line like screen (probobly in green, though white works too). This screen would allow you to access the computer and tell it to do things, get information on connected systems, or use other programs. You would be able to connect machines to the computer via a special data connecter onto the machine you want's redstone port. Via the terminal, you could give the computer instructions that it will try to follow. Basically codeing, but much simpler.

The idea for the "codeing" is simple, if/then operation. You can tell it to look for information on the data network or ehatever else, and *if* that data be there (or not be there or whatever), *then* it will do the following action, whether that be telling a machine to turn on/off, record/send info to other machines/programs, and or just take note of it for later review.

If possible, the data connecter could be used to scan containers for items and list them in addition to what connector (and by extension the container) that they came from. Would be usefull for keeping track of inventory, or a particularly savvy engineer could make an item requesting and storeing system. Another use for this would be preventing one type of item filling up an assembler/auto workbench, preventing them from getting the other items they need to actualy craft stuff. Or it could tell a machine to turn on to fill a buffer in your storage, like having a stack or two of rods, plates, bullets, food, or whatever, but not more than that. If it could tell extractors what to extract (likely by interfacing with an item filter) you really could do the item requesting system mentioned before.

There is likely alot more that could be done with this, maybe have some machines require a connection with a computer to function, due to them needing the computing power. Though that feels a little shoehorned. Could also give it some easter egg commands for the lol's.

But yah, an idea thats been rolleing around in my head for a while and I think it could work. Also had the idea of using punch cards to program the computer, or you could use them to insert data/programs into them, maybe ones from another computer, could work. Now I just need to think up the logistics of golem mech suit's. Another day, maybe.

**Comment by Euphemios** [comment]
Its already on BluSunrize's todo list, as shown in #3112.

**Comment by blacknight7890** [comment]
I knew that blu wanted to do computers for a long while, hence the opening comment. This is merely my interpritation on how it could work. While the redstone part in the post you linked has its uses, I think haveing more abstract things being able to be computed, rather than just redstone and logic gates, would be more useful overall. Like what item is where or allowing statistics of things to be shown via the command panel. Logic and such is usefull, and it can get you quite far if you know what you are doing, but I think more could be done with it than just being calculator. Also, I just like to think up neat ideas and share them, even if others have given their own ideas before, its fun.

**Comment by BluSunrize** [comment]
Closing this, my concepts for redstone-based automation have changed.
