### ISSUE TITLE
Game freezes after switching between single player world

### ISSUE THREAD

**Issue by Alan19** [BluSunrize/ImmersiveEngineering#3173]
### Description of the issue:
When I try to open or create a singleplayer world after opening a singleplayer world, the game freezes and the log outputs the crash messages without a crash log or closing the window
### Crashlog:
https://pastebin.com/aAAR11FN
### Versions & Modlist
Forge version: 14.23.4.2739
ImmersiveEngineering-0.12-82

https://pastebin.com/ZB03yd55

I will test with the latest verions soon but this has been occuring for quite some time

**Comment by Alan19** [comment]
Removing IE fixes the issue

**Comment by malte0811** [comment]
How about updating IE? I'm pretty sure that will fix it as well.

**Comment by Alan19** [comment]
The update fixes the issue. Thanks!
