### ISSUE TITLE
Incompatibility with CodeChickenLib 3.2.1.349 and higher.

### ISSUE THREAD

**Issue by Bulldog83** [BluSunrize/ImmersiveEngineering#3175]
### Description of the issue:
When I try to place some IE blocks or look at the schemes of the multi-block machines, the blocks are not rendered, and the following errors are generated in the logs:

https://gist.github.com/Bulldog83/a7d8656c36dc26a00142b090951f9cd8

### Versions & Modlist
Minecraft: 1.12.2
Forge: 14.23.4.2739
ImmersiveEngineering: 0.12-84
CodeChickenLib: 3.2.1.351

Modlist: https://gist.github.com/Bulldog83/82bab025e93f562dfba0608c71a2feb2

**Comment by malte0811** [comment]
Chisel-Team/ConnectedTexturesMod#72
Update CTM.
