### ISSUE TITLE
1.12 IE84 skyhook crash

### ISSUE THREAD

**Issue by redgoblin88** [BluSunrize/ImmersiveEngineering#3178]
note: yes this has been reported but was for an older version of immersive engineering

### Description of the issue:

i had a cool base idea of a bunch of floating islands connected with immersive engineering cables where the main method of transportation between them was by skyhok so before i started work i decided to give my idea a try!

upon finding a suitable location for my test, i placed a coupple of posts with a steel cable spanning parallel and level (not leaning either way) and quickly right clicked with the skyhook but odd... nothing happened... so i consulted the manual which said i need to HOLD the right click button, so going back  to a post , standing above, i jumped down through the cable and held right click as soon as i passrted it but then.... crash

### Crashlog:

https://pastebin.com/TrSdd2zE

### Versions & Modlist

Immersive: 0.12-84
Forge: 14.23.4.2705

(note that this was on a modpack called "Mech and Magic" if you would like to try and replicate)

**Comment by malte0811** [comment]
I said this was fixed for the next release after IE 84 was released. So IE 85.
