### ISSUE TITLE
[1.12.2] Crash while placing a LV connector/relay

### ISSUE THREAD

**Issue by Davoleo** [BluSunrize/ImmersiveEngineering#3179]
### Description of the issue:
The game crashes while placing a connector on the kinetic dynamo,
with consequent world corruption
Modpack issue reference: https://minecraft.curseforge.com/projects/immersivecraft-mk/issues/14

### Crashlog:
Crash Report: https://minecraft.curseforge.com/linkout?remoteUrl=https%253a%252f%252fpastebin.com%252fyWy0KJW5
latest log: https://minecraft.curseforge.com/linkout?remoteUrl=https%253a%252f%252fpastebin.com%252f6UfvXxTN

### Versions & Modlist
Immersive engineering: 0.12 - 82 
(**I know this is not the latest version, I can't update it since Immersive Hempcraft is also installed in this modpack and it's not updated for the last version of IE see this issue: https://minecraft.curseforge.com/projects/immersive-hempcraft/issues/1 **)
Forge: 14.23.4.2747
modlist: https://minecraft.curseforge.com/projects/immersivecraft-mk/relations/dependencies

**Comment by PrincessRTFM** [comment]
I... think there's something missing from someone's understanding here. You reported an error on an old version, saying you couldn't update it any further. Assuming the error is in IE itself and hasn't been fixed yet, an update to fix it will require that you update your installed version. Which you can't do.

**Comment by BluSunrize** [comment]
For one ^ That.
If it's not on latest, the report isn't valid.

However, that's irrelevant because this isn't an IE crash. Update chisel/ctm.

**Comment by Davoleo** [comment]
reading  the crash log I thought about IE, and I suppose I read it wrong... 
Sorry for the trouble and the useless issue
