### ISSUE TITLE
[1.12.2] Mystcraft's Black Ink Doesn't Bottle in Bottling Machines

### ISSUE THREAD

**Issue by TheFloydman** [BluSunrize/ImmersiveEngineering#3180]
IE recognizes that Black Ink Blocks from Mystcraft are fluids, and it fills the machine with a gray fluid, but it in incapable of putting the ink into bottles. (They go through the machine, but they come out empty.) I don't know if this is a Mystcraft bug or an IE bug, so I am posting about it in each mod's issue tracker.

Mystcraft issue here: https://github.com/XCompWiz/Mystcraft-Issues/issues/305

Here is a screenshot: https://imgur.com/a/JCJr7MJ

**Comment by TheFloydman** [comment]
https://imgur.com/a/JCJr7MJ

**Comment by BluSunrize** [comment]
Would need a specific recipe because there is no universal "bottling" recipe/registry.
Should be easily added with crafttweaker.

As for the fluid being grey, no clue on that, IE uses the Fluid's colours, so maybe Mystcraft is doing something odd with it?

**Comment by TheFloydman** [comment]
Thank you for the clarification. Is there a method to add recipes from Mystcraft itself? Like blusunrize.immersiveengineering.common.util.compat.crafttweaker.BottlingMachine.addRecipe but without the need to go through CraftTweaker?

**Comment by BluSunrize** [comment]
I mean, yeah, IE has an API for its recipes. They're free to make use of it.

**Comment by TheFloydman** [comment]
Ah, found it. Thank you for your help.
