### ISSUE TITLE
[1.12] Redstone objects don't connect downwards to Project Red cabling

### ISSUE THREAD

**Issue by LiaungYip** [BluSunrize/ImmersiveEngineering#3181]
When placing Redstone Probe Connectors, they appear to connect to Project Red cabling located above or beside the Redstone Probe Connector, but not to Project Red cabling **below** the Redstone Probe Connector.

Screenshot 1: Downwards connection works with Vanilla Redstone Dust.

![image](https://user-images.githubusercontent.com/2173684/44532328-38557f80-a736-11e8-813e-9c1838866244.png)

Screenshot 2: Downwards connection doesn't work with Red Alloy Wire.

![image](https://user-images.githubusercontent.com/2173684/44532518-9c784380-a736-11e8-80d2-2cfc2bb95224.png)

Screenshot 3: Downwards connection doesn't work with Framed Red Alloy  Wire.

![image](https://user-images.githubusercontent.com/2173684/44532600-cf223c00-a736-11e8-88d3-e3763380a7ec.png)

----

Reproduced in a minimal environment with only Immersive Engineering and Project Red (Integration) installed. Modlist as per crash log (manually crashed using F3+C.)

[crash-2018-08-24_00.45.07-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/2314969/crash-2018-08-24_00.45.07-client.txt)

Forge: forge-14.23.4.2757
IE: 0.12-82
Project Red: 1.12-4.9.1.92

**Comment by LiaungYip** [comment]
On further inspection, this appears to be Immersive Engineering objects in general, not just the Redstone Probe Connector.

![image](https://user-images.githubusercontent.com/2173684/44533438-dfd3b180-a738-11e8-8591-874736364040.png)

![image](https://user-images.githubusercontent.com/2173684/44533549-1a3d4e80-a739-11e8-9864-3e22801e498f.png)

Red Alloy Wiring does connect downwards from Vanilla redstone devices.

![image](https://user-images.githubusercontent.com/2173684/44533309-a307ba80-a738-11e8-9147-2049fb6d4cd7.png)

**Comment by malte0811** [comment]
I'll close this then.
