### ISSUE TITLE
Wooden Post Bug

### ISSUE THREAD

**Issue by Mugiwaxar** [BluSunrize/ImmersiveEngineering#3188]
Sometime, the wooden post disappear when I look at it,
and I can't modify it with the Engineer's Hammer, nothing happen when I click.
Or others stranges things happen like that:
![iebug](https://user-images.githubusercontent.com/4124999/44637812-afe41280-a9b3-11e8-9e00-1e012572256d.png)

Modpack: FTB Revelation
Immersive Engineering version: 0.12-84

**Comment by BluSunrize** [comment]
They glitch out like that when put at y-level 63/64.
Just put them a bit higher.

Can't help it, vanilla bug.

**Comment by PrincessRTFM** [comment]
Can I ask what the hell vanilla is doing that this happens?
