### ISSUE TITLE
[1.12.2] Arc Furnace Distribution bug 

### ISSUE THREAD

**Issue by Squ1zzl3** [BluSunrize/ImmersiveEngineering#3189]
Description of the issue:
While using any transport pipes from Ender I/O, or AE2 if the arc furnace receives a recipe on the main Metal side of the input the arc furnace auto distributes it to the alloy side as well. For reference in the latest Enigmatica 2 Skyblock expert 1.4 while inputting hundreds of Ardite Ore Dust. The Ardite gets automatically distributed to the incorrect side of the Arc Furnace. So if I input 200 ardite dust. 100 goes on the right of the arc furnace and 100 on the left. There is a simple work around which involves using the much slower Vanilla hopper. Since the hopper is slow enough and doesn't export more than one item at a time the arc furnace doesn't have time to auto distribute the items. The issue with the ardite on the alloy side of the furnace is it will never get processes it sits on that side until it is manually removed.

Versions & Modlist
IE - 0.12-84
forge-14-23-4-2750
Ender I/O 5.0.31
Applied Energistics 2 rev5-stable-11

**Comment by BluSunrize** [comment]
Unable to reproduce this. Pictures of the setup please?

**Comment by Squ1zzl3** [comment]
![screenshot_4](https://user-images.githubusercontent.com/36269188/44676828-56ef9b00-aa02-11e8-8943-510b655659e7.png)
![screenshot_5](https://user-images.githubusercontent.com/36269188/44676829-56ef9b00-aa02-11e8-8afc-10853b690a02.png)
![screenshot_6](https://user-images.githubusercontent.com/36269188/44676830-56ef9b00-aa02-11e8-997f-4b96b6995107.png)
![screenshot_7](https://user-images.githubusercontent.com/36269188/44676831-56ef9b00-aa02-11e8-9c2d-6851325da881.png)
![screenshot_8](https://user-images.githubusercontent.com/36269188/44676886-7981b400-aa02-11e8-931a-0a80d411a7dc.png)

**Comment by BluSunrize** [comment]
Yup, that's what I expected to be the problem.
The input on the top right is for additives. The one on the left is for the main inventory.

Says so in the manual, Arc Furnace, page 5, take a look.

**Comment by Squ1zzl3** [comment]
This has been closed because the arc furnace does not limit inputs via the port but only via the gui. Any and all items can be inserted to the arc furnace. This is as intended as BluSunrize said in discord.
