### ISSUE TITLE
[0.5.2] Coke oven container fill slot accepting coal via automation

### ISSUE THREAD

**Issue by xenoflot** [BluSunrize/ImmersiveEngineering#319]
Howdy,

With EnderIO conduits pumping coal (not blocks) into the coke oven, the main processing input slot fills and any additional coal gets dropped into the blue-dot slot reserved for filling containers with creosote. It does not spool back out so is just stuck there. Perhaps add some whitelisting for valid containers?

While I'm here, if I may add a suggestion, upgrade slots that permit a larger creosote buffer. Perhaps also the option to add an RF-powered blower module (or attach one to the side of the multiblock!) that speeds the coking process.

Cheers

**Comment by BluSunrize** [comment]
Such whitelisting exist. I feel like EIO is ignoring it.
RF powered blowr won't happen, Coke Oven has this speed on purpose, neither will upgrade slots. It's supposed to be a rough equivalent to RC Furnaces. Giving it those powers would make Railcraft useless, and I don't intend on that.

**Comment by XFactHD** [comment]
@xenoflot If you really need a faster coke oven, install immersive integration, it has an industrial coke oven.
