### ISSUE TITLE
[1.12] Crash when using hammer to build distiller and cannot load world until backup restored

### ISSUE THREAD

**Issue by gh0st31337** [BluSunrize/ImmersiveEngineering#3191]
I built a distillation tower and was completing the multiblock with the hammer and it crashed my world.  I tried this once before on version 0.12-84 of the mod and it did the same thing.  I tried removing the offending block with World Edit, but it messed up all my block IDs and I just had to restore a backup.  I figured I would try again with the latest build, but it crashes too.

Here is the crash log of my 0.12-85 crash
[crash-2018-08-28_20.41.32-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/2330298/crash-2018-08-28_20.41.32-client.txt)

Here is the crash log from 0.12-84
[crash-2018-08-08_21.51.16-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/2330311/crash-2018-08-08_21.51.16-client.txt)

**Comment by malte0811** [comment]
IE does not add a distillation tower. The distillation tower is added by Immersive Petroleum, however the crash is my fault in Industrial Wires. It should be fixed in newer builds (28 or 29).
