### ISSUE TITLE
[1.12.2] A crash about manual reading

### ISSUE THREAD

**Issue by Siigaal** [BluSunrize/ImmersiveEngineering#3192]
//I am not an English speaker so forgive me for my poor English please, thanks! :)

My game crashed when I read the page "revolver bullet" in the manual. I feel puzzled about it because this action seems to be a easy one that shouldn't have led to a crash. It's seems that IE but not other mods caused this problem.
I'd appreciate it if you could you fix this problem in the future or tell me which mod made this problem, thank you!
the crash report and all of the visions are here (IE, CTM and Forge are the latest) :  [](https://paste.ubuntu.com/p/v4Yjsdzznp/)

**Comment by Siigaal** [comment]
https://paste.ubuntu.com/p/v4Yjsdzznp/

**Comment by malte0811** [comment]
I think I know what's causing this, does it happen without the resource pack? It's likely that there's a typo in the resource pack's version of the manual entry, though the crash should be fixed in IE.

**Comment by BluSunrize** [comment]
@dave75vgnut
You posted on an unrelated issue. Your crash is in no way related to the one above and you also posted it raw instead of putting it on pastebin.
Update CTM, your version is 9 months old.
