### ISSUE TITLE
[1.12.2] Sound muffler does not work with crusher

### ISSUE THREAD

**Issue by K-4U** [BluSunrize/ImmersiveEngineering#3195]
### Description of the issue:
Sound muffler (exutils 2) does not muffle sounds of the crusher

### Crashlog:
No crash

### Versions & Modlist
https://p.k-4u.eu/view/ac3f546f 

Most importantly:
IE 0.12-84
extrautils2-1.12-1.8.1
Forge 14.23.4.2739

**Comment by malte0811** [comment]
rwtema/extrautilities_old_issues#280
