### ISSUE TITLE
TileEntityAlloySmelter causing DW20 Server to crash on startup [1.12.2]

### ISSUE THREAD

**Issue by Dr1899** [BluSunrize/ImmersiveEngineering#3196]
I am attempting to create a Direwolf20 Modpack server. When the server is starting I get an error message that seems to involve the AlloySmelter. I am using forge version 1.12.2 forge-12.23.4.2739 and IE version is ImmersiveEngineering-0.12-84 (If needed modpack version is 2.2.0) Here is the crash report.

https://pastebin.com/UDEnSMpx

**Comment by mindforger** [comment]
>Caused by: java.lang.OutOfMemoryError: Java heap space

Just assert more RAM

>-Xmx512m -XX:PermSize= -XX:+Use...

You need at very least 1G and you forgot to define a size for permsize, ditch it or do it properly :)

**Comment by malte0811** [comment]
^ That. I'd say even 1 GB would be too little for ~150 mods in 1.12, maybe try 2 or 4 GB.

**Comment by CorwinCZ** [comment]
@Dr1899 For my DW20 servers I was usually using 6GB of RAM. Having less that this resulted in lags when multiple users were connected and using some chunk loaders / quarries etc...

**Comment by mindforger** [comment]
i use a command line of about 100 letters length to optimize the garbage collector (that is the main sorce of lag)
