### ISSUE TITLE
[1.12.2] Dynamic(?) arc furnace recycling recipes have incorrect output count (in JEI at least)

### ISSUE THREAD

**Issue by BrisingrAerowing** [BluSunrize/ImmersiveEngineering#3197]
### Description of the issue:
Arc furnace recycling recipes that are dynamically added (e.g. for Copper armor) always show output stack sizes of 1 in JEI, no matter what the input item is.

I haven't built an arc furnace yet, so I'll go ahead and see if this is just an issue in JEI or if the recipes are actually wrong.

EDIT: The recipes are incorrect as well. A copper chestplate (crafted with 8 ingots) gave only 1 ingot back.

### Versions & Modlist
IE: 0.12-85
Forge: 2759

[Modlist](https://gist.github.com/BrisingrAerowing/f67c509fe75681da097cc39d49c51e1e)

**Comment by malte0811** [comment]
I'm unable to reproduce this. Does this only happen to copper armor? If yes, what mod adds this armor? If no, what other items (preferably vanilla or IE) produce the wrong output?
I tested iron and gold chestplates, they produced the expected output (8 ingots).

**Comment by BrisingrAerowing** [comment]
Base Metals.
