### ISSUE TITLE
[Suggestion] Corroded Copper and Rusted Iron Sheetmetal Blocks

### ISSUE THREAD

**Issue by cybercat5555** [BluSunrize/ImmersiveEngineering#3198]
Exactly as it says. How about an option for patina'd copper and rusted iron sheetmetal blocks? Purely aesthetic, possibly created by running a copper/iron sheetmetal block through a bottling machine with water, or possibly the mixer with water. Perhaps random textures or CTM for both? Though an easier option may be a random overlay, similar to the TBA mud dungeons from Betweenlands (as it has normal blocks but with mud overlays randomly applied to blocks.

Examples of the mud dungeon blocks
[1](https://cdn.discordapp.com/attachments/294615613232513034/448941708311527425/decayroof2.png)
[2](https://cdn.discordapp.com/attachments/294615613232513034/448941781669773322/roots1.png)
[3](https://cdn.discordapp.com/attachments/294615613232513034/448941773474103316/decayroof4.png)
[normal blocks](https://cdn.discordapp.com/attachments/294615613232513034/448941784274567168/door_test_1.png)

**Comment by Xenoamor** [comment]
Why not have exposure to running water cause it and then you have to combine sand + paper to create sandpaper to remove it

**Comment by BluSunrize** [comment]
Vanilla has corrosion for copper, and I'm not adding it for iron.

Too little value for the effort involved.
