### ISSUE TITLE
ClientUtils.drawConnection performance

### ISSUE THREAD

**Issue by sfPlayer1** [BluSunrize/ImmersiveEngineering#32]
The method mentioned in the subject doesn't perform well, mostly due to Tessellator drawing.

You don't want to use Tessellator only for a single quad, initialize it once, add the vertices for all quads and then do a single draw call. It's most likely also faster to draw all faces twice, once in reverse vertex order, than changing GL_CULL_FACE.

If the rendered primitive is sufficiently static and doesn't require gl state changes use the world renderer instead of TESRs.

**Comment by BluSunrize** [comment]
Yeah you're way late for that one. It all renders in one call now, that version just isn't on Forgecraft yet. Overall rendering has been optimized in 0.1.14

**Comment by sfPlayer1** [comment]
I looked at your github master sources..

**Comment by BluSunrize** [comment]
but I don't push to github currently ;)
