### ISSUE TITLE
game crash after placing fluid pipe on top of fluid conduit form ender io

### ISSUE THREAD

**Issue by TylAshke** [BluSunrize/ImmersiveEngineering#3205]
crash report https://pastebin.com/H8RQwNa

IE version 0.12.82
ender io version 1.12-5.0.29

playing on a server using the foolcraft 3 modpack version1.4.5 I placed one of your fluid pipes on top of a facade containing a fluid conduit and the game crashed. Also, it crashed when doing it the other way around. placing a fluid conduit next to a fluid pipe. There is a report on the ender io site about this already, saying that it is fixed.........

**Comment by malte0811** [comment]
Update IE.
