### ISSUE TITLE
Question: Custom made blue prints in CT

### ISSUE THREAD

**Issue by Ezoteric** [BluSunrize/ImmersiveEngineering#3208]
I would like to know how to add my own made blueprints into chest loot but i dont know how the blueprints are listed.

Could you give me a hand with that ? :)

I have:
mods.immersiveengineering.Blueprint.addRecipe("Rocket Tier1", 
and they do work and showup, its just i dont know what they are called :)

Thnx in advance

**Comment by BluSunrize** [comment]
This reply is probably entirely too late, but Blueprints are all the same item, `immersiveengineering:blueprint` and they use NBT data to differentiate themselves, specifically the key `blueprint`.
So your blueprint would have the NBT entry `blueprint`: `Rocket Tier1`

**Comment by Ezoteric** [comment]
Still not too late and still havent got it fixed.

Could you be so kind to provide me with the right line of code by any chance ? cause i figured out it had to do with nbt just cant seem to get it work :(
