### ISSUE TITLE
Cables Disconnecting after Relogging 

### ISSUE THREAD

**Issue by allbliss0215** [BluSunrize/ImmersiveEngineering#321]
Hey, devs. First of all, awesome mod. Love everything about it. Thanks for all the hard work that you guys put into making this amazing mod.

By the way, I noticed a problem with the cables. I'm pretty sure this has been reported already, but the cables are disconnecting after re-logging into the client, like they'd be gone. I'm not sure if it's because of my base being in a different dimension (in this case, I use RFTools) in the middle of the void, or some incompatibility bug or rendering issue or whatnot. 

Is there a fix to this? Kinda sucks having to reconnect all the wires after loading my world every single time.

EDIT: For further info, I used HV and MV cables to power IC2 machines. Haven't tested it with RF-Powered machines yet. Just FYI.

 More power, dudes.

**Comment by BluSunrize** [comment]
Old issue:
https://github.com/BluSunrize/ImmersiveEngineering/issues/160
