### ISSUE TITLE
[1.12.2] Cannot open Engineer's Manual

### ISSUE THREAD

**Issue by NLBlacky** [BluSunrize/ImmersiveEngineering#3215]
First of all before I start I would like to say that this is the same issue #3210 has but since it lacks proper information, and since I don't want to take someone else his post I decided to make my own.

I'm a server owner from a Modern Skyblock 3 server. On this server several players have reported that they were unable to open the Engineer's Manual. Since they cannot open it, I don't have a screenshot of it. This issue however is not for everyone (incl me) as it works fine for us.

We're trying to find out what is causing this issue since it stops players from reading valueable information that they need for progression in this skyblock modpack. (Yes they can use wiki, but the manual gives much better and faster information with usefull build guides). Since we can't seem to find out what the issue is, I've decided to come to this site and give all the needed information to hopefully solve the issue.

The players that reported this issue are not using any mods like Optifine.
I've tried disabling CTM on the server since it was suggested in #3210 but that didn't effect anything.

Some information about the server and mods:
Modpack: Modern Skyblock 3 v3.4.2
ImmersiveCables-1.12.2-1.3.2.jar
ImmersiveEngineering-0.12-84.jar
immersivepetroleum-1.12.2-1.1.9.jar
immersivetech-1.12-1.3.10.jar

As you might be able to see, we do not have the latest version of Immersive Engineering. We cannot change that since we want to keep the modpack original. I however don't think it has something to do with the version though since not everyone has this issue, only a few players. 

I hope I've provided enough information. I hope someone has a clue why some players cannot open the book and what could be the issue. Thanks for reading and I'm looking forward to replies :)

**Comment by PrincessRTFM** [comment]
A server log would probably help diagnose the issue, can you upload one to pastebin?

**Comment by NLBlacky** [comment]
Below you will find a link with the entire server log while we tested it. I myself saw no message appear in the console when he was opening the book. You can search for "#3215" to find the conversation.
Maybe you find something else (maybe during startup?) that could explain why some people have issues with it. I couldn't use Pastebin or other sites to share this since the size was too big. So I'll link you a link to my google drive with the file. I'll be removing this file in a week or so.

https://drive.google.com/file/d/13s13FTcMV-GDNix-Z0ebZTJDUPah8mxb/view?usp=sharing

**Comment by NLBlacky** [comment]
The players do not experience this in singleplayer. A full list of mods in the modpack can be found here:  https://minecraft.curseforge.com/projects/modern-skyblock-3-departed/relations/dependencies

**Comment by Pistondart** [comment]
I'm also having this issue.  I'm also running modern skybock 3.  The manual would open when we first started doing the immersive engineering quests, but as we started moving through all of the multi-block machines, the manual stopped working.  It does work in single player.  I was considering deleting certain immersive engineering files (ImmersiveEngineering-SaveData.dat and immersiveengineering.cfg) in hopes that they would get recreated and fix the issue.  But I wanted to check to see if others were having the same issue before I tried it.

**Comment by finalfxtidus** [comment]
I run a Modern Skyblock 3: Departed server. I also experience an issue where I can't open the Engineers Manual. I also have someone on my server who reports that their "amadron tablet" doesn't work. I'm wondering if the issues might be connected. Hope there is a fix that doesn't require a loss of progress :/

**Comment by BluSunrize** [comment]
Are you using the Akashik Tome, or a normal freshly crafted Engineer's Manual? Could you try with a completely new book and see if that alleviates the issue?

**Comment by finalfxtidus** [comment]
Just crafted a fresh Engineer's manual and still have the issue. Something else that I notice with this server is that I get inventory issues occasionally. I think that is related to the ender bag thats built into the inventory though.

**Comment by PhoenixMage** [comment]
I am also experiencing this issue on my Modern Skyblock 3: Departed server. The save game was converted from a single player and plays fine except for this issue. If I convert the game back to SP the manual can once again be opened. The manual is freshly crafted.

When I attempt to open the manual literally nothng appears to happen. Nothing in the debug.log of either client or server.

**Comment by xenoxsis** [comment]
Same problem here... New book - nothing happens when I open it

**Comment by PhoenixMage** [comment]
@xenoxsis Upgrade your versions of GameStages and ItemStages. Turns out thats where the bug is.

This case can probably be closed.

**Comment by Immaculala** [comment]
28th July 2019 Singleplayer - won't open for me either.
Running only a few basic mods like JEI, WAILA etc.

I read above about  "Updating gamestates and itemstages" but I don't have a clue what that means or if it is releavnt to me - not running Skyblock etc.
