### ISSUE TITLE
Toolbox inventory voiding with bibliocraft shelf

### ISSUE THREAD

**Issue by JollyHyena** [BluSunrize/ImmersiveEngineering#3216]
Hello

 Engineer's toolbox seems to void when placed in a bibliocraft shelf and then right clicked to pop out. Does not happen when the GUI of the shelf is opened and retrieved from there, only when popped out by right clicking.

 Thought it might be a nestled inventory thing, but could not replicate it with a treated wood crate or a nestled inventory bag from another mod. Issue was not present when the box was put in a chest or other inventories, just on the shelf and then only when right clicked to pop out

IM version 0.12-82
modpack - All The Mods 3

Cheers

**Comment by PrincessRTFM** [comment]
Assuming IM means Immersive Engineering, that's three versions behind and should be updated.

**Comment by malte0811** [comment]
I was able to replicate this with the latest versions of IE and Bibliocraft (0.12-85 and 2.4.5).
@Nuchaz I'm pretty sure this is on your end. The toolbox stores its inventory in the Forge cap NBT part of the itemstack, I'd guess that part of the stack is removed somehow at some point when the item is put onto the shelf.
