### ISSUE TITLE
1.12 Chemical Thrower - Issue/Disconnect

### ISSUE THREAD

**Issue by Keaton1188** [BluSunrize/ImmersiveEngineering#3217]
### Description of the issue: Chemical Thrower - Disconnect 
When using the Chemical Thrower on our 1.12 server, you will get disconnected with the error msg

"Internal Exception: io.netty.handler.codec.DecoderException: Badly compressed packet - size of 2815114 is larger than protocol maxium of 2097152" 

This error will occur when you even try to get near the area where the chemical thrower was used, for this reason we have had to ban the item on all our servers just to prevent this from causing more issues.

### Versions & Modlist: FTB Continuum/other 1.12's
IE Version: ImmersiveEngineering-0.12-83.jar
Forge Version: 14.23.4.2730
SpongeForge Version: 1.12.2-2705-7.1.0-BETA-3442

**Comment by PrincessRTFM** [comment]
You're on an old IE version. Step one is always to update. Also, does Blu support anything beyond pure Forge? Because I see SpongeForge on there and I'm not sure he deals with that.

**Comment by Keaton1188** [comment]
I won't manually update the mod as this would cause mod issues when other users go to join the server, I'll wait for a pack update.
