### ISSUE TITLE
Override drill (head) mining level

### ISSUE THREAD

**Issue by tyra314** [BluSunrize/ImmersiveEngineering#3219]
Hey, I'm just looking into [this issue](https://github.com/tyra314/ToolProgression/issues/42) for my mod. Basically, I'd like to change the mining level of the drill and in particular the mining level you get by combining a head with a drill.

If I read the code correctly, the levels are hardcoded: 
https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/items/ItemDrillhead.java#L47

Is there a way to achive such an override?

### Versions & Modlist
Minecraft: 1.12.2
Forge: 14.23.4.2703
IE:  0.12 - 85
ToolProgression: 1.5.4

**Comment by BluSunrize** [comment]
Nope, there isn't since I never saw it as necessary.
