### ISSUE TITLE
Suggestion: Chutes (for downward item transport)

### ISSUE THREAD

**Issue by littlebeast** [BluSunrize/ImmersiveEngineering#3222]
Because yeah, hoppers exist, but let's face it: there's no way to chain hoppers together and make it look good.

### Possible description

The way I'm seeing them, chutes would appear as a block with four sides but no top or bottom.  You could drop things in the top, or (more usefully) machines and conveyor belts could insert into them.  They would probably use a texture similar to scaffolding, just so you could see items dropping through them.  Stretch goal: have them connect at an angle to another chute beside them?
Unlike conveyors, they don't insert into anything - they just drop (and prevent picking up items).  But they are sized nicely to collect in a hopper, or to drop on a (covered) conveyor belt.

Easy enough, right? And it would increase immersion.  Which is the name of the mod, after all ;)

**Comment by erindalc** [comment]
Here: https://minecraft.curseforge.com/projects/chutes
