### ISSUE TITLE
[1.12]FeedThrough Insulator not working as it said

### ISSUE THREAD

**Issue by lordfriend** [BluSunrize/ImmersiveEngineering#3224]
Minecraft 1.12.2
Forge version is 14.23.4.2760.
Immersive Engineering   0.12-85
Mod List:
```
Chisel                MC1.12.2-0.2.1.34
CodeChiken Lib 3.2.1.351
CoFH Core         4.5.3.20
CTM                   MC1.12.2-0.3.2.18
FTB Utilities       5.3.0.49
FTBLib               5.3.0.50
Immersive Engineering   0.12-85
Immersive Petroleum     1.1.9
IvTookit                           1.3.3-1.12
JouneryMap                    4.11.0.212
Minecraft Transport Simulator
Mo'Village                       1.5.2
Redstone Flux                  2.0.2.3
Recurrent Complex          1.4.7
Techguns                          1.12.2-2.0.1.1
WordEdit                           6.1.8
```
Other mods are client only, should not affect this issue.

You can see I use a nether brick it cannot pass the power.
![2018-09-21_00 18 35](https://user-images.githubusercontent.com/1235614/45832367-4813b400-bd34-11e8-9f92-f596460cb81d.png)

I also test stone.  This happens both on my server and local creative mode.

I also test in a minimal mods config, only requires IE for the server side ( but include CodeChiken Lib, CoFH Core, Redstone Flux, NEI, JEI for convenience, but these mods should be the client mod), The result is the same.

**Comment by malte0811** [comment]
Did you form the multiblock by right-clicking one of the connectors with an engineer's hammer (yes, it will be explicitely stated in the manual in the next build)? You currently need to do that before the wires are connected, in IE build 86+ it will be possible to attach the wires first.

**Comment by lordfriend** [comment]
Oh no, I didn't try that. But I think I've read the manual carefully. but it doesn't say that.
I will try again tomorrow.
Thank you for your help.

**Comment by lordfriend** [comment]
It works like a charm, I think the only issue is update the manual
