### ISSUE TITLE
[1.12]Wooden Post affect by vines

### ISSUE THREAD

**Issue by lordfriend** [BluSunrize/ImmersiveEngineering#3225]
![2018-09-21_11 52 20](https://user-images.githubusercontent.com/1235614/45859481-28f93e80-bd95-11e8-9941-c3fa4bf9d23d.png)
![2018-09-21_11 52 24](https://user-images.githubusercontent.com/1235614/45859483-28f93e80-bd95-11e8-8d06-cc0764c9df9a.png)
You can see two images show that the vines reach side mount of the wooden post it changes the direction of the side mount. but after I remove the vines, the side mount revert back to the right direction.

Minecraft 1.12.2
Forge version is 14.23.4.2760.
Immersive Engineering 0.12-85
Mod List:
```
Chisel                MC1.12.2-0.2.1.34
CodeChiken Lib 3.2.1.351
CoFH Core         4.5.3.20
CTM                   MC1.12.2-0.3.2.18
FTB Utilities       5.3.0.49
FTBLib               5.3.0.50
Immersive Engineering   0.12-85
Immersive Petroleum     1.1.9
IvTookit                           1.3.3-1.12
JouneryMap                    4.11.0.212
Minecraft Transport Simulator
Mo'Village                       1.5.2
Redstone Flux                  2.0.2.3
Recurrent Complex          1.4.7
Techguns                          1.12.2-2.0.1.1
WordEdit                           6.1.8
```

**Comment by mindforger** [comment]
well ... in the past you'd have two arms, one going up and one going down, having a bit of a z-fighting in their texture ... i think this is just normal and better than z-fighting textures

**Comment by KnightMiner** [comment]
Maybe make going up the default if both are detected instead of down? Otherwise maybe limit which blocks can connect somehow

**Comment by andrewminer** [comment]
Perhaps a kind of "priority" system could be used to determine which way is preferred.  Or, perhaps having a style of arm which has a mount point on both sides.

**Comment by BluSunrize** [comment]
This is actually pretty funny and I must have totally missed this issue before.
Sorry, I'll take a look =P
