### ISSUE TITLE
[1.12.2] Immersive Engineering X  EnderIO

### ISSUE THREAD

**Issue by GamingJason** [BluSunrize/ImmersiveEngineering#3226]
### Description of the issue:

Immersive Engineering and EnderIO crashes game.
Crashes the whole game but not the server.
If anyone came to my base/chunk they will also crash and no possible way of leaving.

1.Place Immersive Engineering Fluid Pipe
2.Place EnderIO Pressured Fluid Conduit beside the Fluid Pipe
3.Crashed.
4.Happened twice.

### Crashlog:

https://pastebin.com/Pkxuy1ve

### Versions & Modlist

IE: 0.12-82
Forge: Not Sure
https://pastebin.com/pNKPksij

**Comment by mindforger** [comment]
Update EIO and IE

https://github.com/SleepyTrousers/EnderIO/issues/4878

**Comment by malte0811** [comment]
^That. The bug has been fixed/worked around on both sides (IE and EIO).
