### ISSUE TITLE
Is there a way to dump unused liquid?

### ISSUE THREAD

**Issue by lordfriend** [BluSunrize/ImmersiveEngineering#3227]
I only found a block called Fluid Outlet. But this thing looks like designed to create a fluid source in the world. when the fluid level reaches the outlet, it stops drain the tank. And this is a very quick process.

I know many has other tech mod installed which maybe have some item can handle the waste liquid, but I already start a world with only Immersive Engineering, Immersive Petroleum, Techguns.

**Comment by PrincessRTFM** [comment]
Haven't tried this, but does a sticky piston pushing a solid block into liquid "overwrite" the liquid and delete it? Because if so, you could make a small(ish) chamber to dump fluid into and have pistons clear it. Not exactly immersive, I know, but just until something is found/added.

**Comment by lordfriend** [comment]
Yes, I use the sticky piston to do this, then I need to make some complex red stone device to automatically activate the piston then deactivate.

**Comment by PrincessRTFM** [comment]
Oh definitely! It'd be more immersive too. In fact...

What about something _like_ the outlet that only places a single block of fluid in front of its output face (or faces, configured with the hammer?) and then voids all incoming fluid once the output faces are occupied? You could put it next to an ocean and pretend to be dumping waste there for a gritty and environmentally uncaring factory, or you could shut off all the output faces or cover them and have a "normal" fluid void.

**Comment by lordfriend** [comment]
Really? If I cover all 5 faces of the outlet, can it still dump waste? if it's true, that would be wonderful.
I will try the methods you suggested.

**Comment by mindforger** [comment]
@PrincessRTFM if you already add an outlet (block), why not making it configurable to dump the liquid or add an void upgrade to it while implementing it in the first place?

i know pipe valves have been discussed a few times already but this would be an oppertunity to make it greater even more ... 

valves crafted being closed by default (important, explained later)
when used inline with pipes would stop the flow of liquids between the connected segments/tanks
but when one side is hammered open and not connected to any liquid interface, THEN when opened it would void the liquid from the input side (maybe add some fancy fluid animation like with the arc furnace)

**Comment by ChaoGirDja** [comment]
In early Version of IE, Tanks had autovoided excess Fluids (and Silos Items).
Maybe... just an reintroducing of this feature will do the Trick?
Can be make like the "Fluid to Cobbel"-Swap-Funktion of the Pumps. Hit with an Hammer to toggel on ore of.

**Comment by BluSunrize** [comment]
@ChaoGirDja 
IE's Silos and Tanks never voided anything. If they did, that would have been a bug. I wouldn't have a deletion feature without it being an optional enable.

**Comment by ChaoGirDja** [comment]
Hum... Well, it was an usfull Bug then.
And yes, should be an toggel....
