### ISSUE TITLE
Arc furnace and item outputs

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#323]
Issue: 
--------------------
Arc furnace outputs not acting as valid containers(?)
Incompatibility with Thermal Dynamics?

Action:
-----------
Placing itemducts directly onto item outputs

Expected result:
----------------
Itemducts would attach to the outputs like they would on the inputs, seeing the outputs as valid containers (?)

Actual result:
--------------
Itemduct ignores the output slot, not connecting to it, and not accepting items from it

Version data:
=================
IE Version 0.5.3 build 8a9b2a445cba11c254f47c32e88c91cd6541734a
This issue also appears to occur on older builds.

-----------
FTB Infinity (1.9.0). Modified botania

**Comment by BluSunrize** [comment]
I might not have set it up to allow extracting. Will need to check that.
But I can't "insert" into ducts because they are not valid inventories. I blame Tema.

**Comment by theunkn0wn1** [comment]
If you cannot 'insert' into itemducts, then how does TE do it with the auto-ejection of items from its machinery?

**Comment by BluSunrize** [comment]
It specialcases their own ducts. But I refuse to =P

**Comment by theunkn0wn1** [comment]
fair enough. I can verify the fix works, and i can live with putting a servo on the duct for extraction. 
However... IDK if this is a bug or...

Should the player be allowed to pump the graphite electrodes into the Arc Furnace?

**Comment by BluSunrize** [comment]
For now, yeah. I might change that though.
