### ISSUE TITLE
Diesel generator not accepting TE fuel

### ISSUE THREAD

**Issue by Crowfooted** [BluSunrize/ImmersiveEngineering#3230]
The diesel generator won't accept TE "Refined Fuel" piped into its fuel inputs via TE Fluiducts. Verified that fuel was not entering the generator by breaking the generator and re-creating the multiblock and checking if any more fuel had been drawn from my TE fuel tanks. Verified via book, wiki and other players' screenshots that fuel was being piped into the correct place on the multiblock.

IE: 0.12-84
Forge: 2760

**Comment by EvilCooky** [comment]
The diesel generator is not supposed to take refined fuel, as far as I know.
it runs only on diesel (either biodiesel or the diesel made with Immersive Petrolium)
Refined Fuel is more like gasoline.
You don't drive your diesel car with gasoline, do you?

**Comment by mindforger** [comment]
@EvilCooky there are many engines around the world that can use both :p

https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/util/compat/crafttweaker/DieselHelper.java

use Crafttweaker

DieselHelper.addFuel(liquidstack,burntime)

**Comment by Crowfooted** [comment]
@EvilCooky Only reason I raised it as an issue is that the diesel generator took TE/BC fuel in earlier versions and outdated wikis reflect this, so I expected it to still be the case in this version, since TE fuel still exists.

@mindforger I actually already went ahead and did this for my personal use but I figured it would be useful (and simple) for it to be included in the mod.
