### ISSUE TITLE
Iron nugget unnecessary in 1.12.2

### ISSUE THREAD

**Issue by Boundarybreaker** [BluSunrize/ImmersiveEngineering#3234]
IE 0.12-85, Forge N/A
![](https://cdn.discordapp.com/attachments/214574167192764416/494949170394693653/unknown.png)
Immersive Engineering 1.12.2 still contains its own iron nugget, even though there's now one in vanilla. It's no longer necessary and just causes oredict frustration; it should be removed.

**Comment by BluSunrize** [comment]
The one in vanilla is ugly. Ours looks better.

And the oredict makes all of them equal for recipes, so I don't think there should be any reason for frustration.

**Comment by Robijnvogel** [comment]
@BluSunrize I don't disagree that yours looks better. But if it's just the texture you want to change, then why don't you just... change the texture?

**Comment by jaredlll08** [comment]
As Robin said, Blu you have no reason to add a completely new item to replace a single texture.
