### ISSUE TITLE
Multiple thermoelectric generators don't seem to adding their output power together

### ISSUE THREAD

**Issue by duncanwebb** [BluSunrize/ImmersiveEngineering#3235]
### Description of the issue:
Multiple thermoelectric generators don't seem to adding their output power together, it is quite possible that this is my failure or a possible bug in automated redstone.
This shows an energy valve displaying the IF/t of 42 when connected to a thermoelectric generator surrounded by packed ice and uranium blocks.
![direct-connection](https://user-images.githubusercontent.com/4198031/46170958-7dbe1d00-c29f-11e8-9514-270f97b592b6.png)

This image shows an energy valve displaying the IF/t of 42 when connected to a MV relay connecting two thermoelectric generators surrounded by packed ice and uranium blocks.
![through-mv-relay](https://user-images.githubusercontent.com/4198031/46170963-80b90d80-c29f-11e8-9a58-9ec0a05fb435.png)

I would expect to see a value of 84 IE/t, Is there a way to verify the throughput of energy in a connector?

### Versions & Modlist

Forge version is 14.23.4.2760
ImmersiveEngineering-0.12-85
AutomatedRedstone-1.12.2-6.1.3

RealTech_1.12.2-2.0.3\minecraft\mods>dir /b *.jar
AdChimneys-1.12.2-3.3.7.1-build.0161.jar
AdPother-1.12.2-0.8.0.1-build.0162.jar
AkashicTome-1.2-10.jar
AppleSkin-mc1.12-1.0.9.jar
aquamunda-1.12-0.4.0-beta.jar
architecturecraft-1.12-2.68.jar
AutomatedRedstone-1.12.2-6.1.3.jar
AutoRegLib-1.3-20.jar
Baubles-1.12-1.5.2.jar
Better-Railroads-1.0.0.jar
BetterFoliage-MC1.12-2.1.10.jar
BetterFps-1.4.8.jar
BetterQuesting-3.5.263.jar
BiblioCraft[v2.4.5][MC1.12.2].jar
BiomesOPlenty-1.12.2-7.0.1.2399-universal.jar
BuildingGadgets-1.6.2.jar
car-1.2.11.jar
CD4017BE_lib-1.12.2-6.2.4.jar
cfb-1.0.jar
Chameleon-1.12-4.1.3.jar
ChickenChunks-1.12.2-2.4.1.73-universal.jar
Chisel-MC1.12.2-0.2.0.31.jar
chiselsandbits-14.22.jar
ClocheCall-1.1.1.jar
CodeChickenLib-1.12.2-3.2.1.351-universal.jar
ColossalChests-1.12.2-1.6.11.jar
comforts-1.12.2-1.2.0.jar
conarm-1.12.2-1.0.2.jar
Controlling-3.0.6.jar
CookingForBlockheads_1.12.2-6.4.44.jar
CraftTweaker2-1.12-4.1.9.jar
CTM-MC1.12.2-0.3.2.18.jar
CustomNPCs_1.12.2(09jul18).jar
CyclopsCore-1.12.2-0.11.9.jar
Decocraft-2.6.1_1.12.2.jar
diethopper-1.1.jar
Ding-1.12.1-1.0.1.jar
DynamicSurroundings-1.12.2-3.4.9.14.jar
EnchantingTable-1.12-1.1.3.jar
engineersdoors-0.7.2.jar
entityspring-2.0.0.jar
ExtraRails-1.12-1.3.0.jar
FamiliarFauna-1.12.2-1.0.10.jar
Farseek-1.12-2.3.1.jar
FastLeafDecay-v14.jar
Ferdinand's Flowers-1.10.1b-1.12.jar
flatcoloredblocks-mc1.12-6.6.jar
foamfix-0.10.1-1.12.2.jar
forestry_1.12.2-5.8.1.339.jar
ForgeEndertech-1.12.2-4.3.20.1-build.0163.jar
Forgelin-1.7.4.jar
Geolosys-1.12.2-2.1.2.jar
gravestone-1.10.1.jar
HardcoreDarkness-MC1.12.2-2.0.jar
hopperducts-mc1.12-1.5.jar
IGW-Mod-1.12.2-1.4.4-15-universal.jar
immcraft-1.12-1.5.0.jar
ImmersiveEngineering-0.12-85.jar
immersivepetroleum-1.12.2-1.1.9.jar
immersivetech-1.12-1.3.10.jar
IndustrialWires-1.7-29.jar
InitialInventory-3.0.0.jar
inventorysorter-1.12.2-1.13.3+57.jar
InventoryTweaks-1.63.jar
ironchest-1.12.2-7.0.46.831.jar
ItemPhysic Lite 1.3.7 mc1.12.2.jar
JEHC-1.12.2-1.6.1.0.jar
jeibees-0.9.0.5-mc1.12.2.jar
jei_1.12.2-4.12.0.215.jar
journeymap-1.12.2-5.5.2.jar
JustAFewFish-1.7_for_1.12.jar
JustEnoughResources-1.12.2-0.8.9.48.jar
LLOverlayReloaded-1.1.6-mc1.12.2.jar
Magneticraft_1.12-2.4.4-dev.jar
malisiscore-1.12.2-6.4.0.jar
malisisdoors-1.12.2-7.3.0.jar
Mantle-1.12-1.3.2.24.jar
mcjtylib-1.12-3.0.4.jar
minecolonies-1.12.2-0.9.1-RELEASE-universal.jar
Minecraft Transport Simulator-1.12.2-10.1.2.jar
missing_pieces-1.12.2-4.3.0.jar
MmmMmmMmmMmm-1.12-1.14.jar
moarboats-1.12.2-2.1.0.2.jar
MobGrindingUtils-0.3.11.jar
modelloader-1.1.2.jar
modnametooltip_1.12.2-1.10.0.jar
moreoverlays-1.14-mc1.12.2.jar
Morph-o-Tool-1.2-16.jar
MouseTweaks-2.8-mc1.12.1.jar
MTLib-3.0.5.jar
MTS_Offical_Pack_V04.jar
natura-1.12.2-4.3.2.62.jar
NetherPortalFix_1.12.1-5.3.13.jar
notenoughwands-1.12-1.7.0.jar
NPCIntegration-3.4.25.jar
Nutrition-1.12.2-3.2.0.jar
OpenGlider-1.12.1-1.1.0.jar
p455w0rdslib-1.12-2.0.32.jar
PackingTape-1.12.2-0.7.6.jar
Pam's HarvestCraft 1.12.2y.jar
platforms-1.12.0-1.4.5.jar
pneumaticcraft-repressurized-1.12.2-0.7.7-255.jar
PTRLib-1.0.2.jar
Quark-r1.5-127.jar
reauth-3.6.0.jar
RebornCore-1.12.2-3.10.0.332-universal.jar
RedstoneFlux-1.12-2.0.2.3-universal.jar
redstonepaste-mc1.12-1.7.5.jar
roughTweaks0.2.4-1.12.2.jar
rustic-1.0.8.jar
SereneSeasons-1.12.2-1.2.6-universal.jar
ShadowMC-1.12-3.8.0.jar
shetiphiancore-1.12.0-3.5.7.jar
Signals-1.12.2-1.3.12-23-universal.jar
simplefluidtanks-1.12.2-1.7.1.1.jar
SoundFilters-0.10_for_1.12.jar
StandardExpansion-3.4.145.jar
StevesCarts-1.12.2-2.4.22.109.jar
stg-1.12.2-1.2.3.jar
StorageDrawers-1.12.2-5.3.7.jar
Streams-1.12-0.4.4.jar
TConstruct-1.12.2-2.10.1.87.jar
theoneprobe-1.12-1.4.23.jar
thutcore-1.12.2-5.19.7.jar
thuttech-1.12.2-6.1.4.jar
Tinkers' Addons-1.12.1-1.0.7.jar
ToughAsNails-1.12.2-3.1.0.128-universal.jar
ToughExpansion-1.12-3.4.24.jar
ViesCraft-1.12.2-5.9.13.jar
VillageNames-1.12.2-2.0.jar
WearableBackpacks-1.12.2-3.1.3.jar

**Comment by duncanwebb** [comment]
The developer of redstone automation says that the energy valve represents itself as a capacitor storing zero RF. Would this confuse the relay logic?

**Comment by malte0811** [comment]
Finally got around to testing this, the problem isn't the energy valve or anything on the input side, it's a minor bug in the code for the connector on the output of the valve. The connectors insert into the network (and therefore the valve) separately, the valve tries to pass on these separate "bursts", but the connector refuses to accept any but the first "burst". Shouldn't be hard to fix.

**Comment by duncanwebb** [comment]
Thank you very much and for the mod, truly excellent.
