### ISSUE TITLE
Crusher don´t work

### ISSUE THREAD

**Issue by WilhelmGER1313** [BluSunrize/ImmersiveEngineering#3236]
Hello, i have a Problem with the Crusher. He don´t crush anything.Not Ores or Dust, but i need Coke Coal Dust. Please help to fix the Problem at the Server. 

i play with Ftb Continuum 1.5.2 

The Error: https://vimeo.com/292367597

**Comment by BluSunrize** [comment]
It looks like your crusher is stuck processing an item. Did you switch its redstone control to require an active signal?

**Comment by WilhelmGER1313** [comment]
Crusher funktioniert an bestimmten Stellen. Hab aus verlässlichen Quellen gehört das es sich dabei auch um die Config Einstellung vom Server handeln kann.Aber was muss ich da einstellen das ich jede Maschine in jedem Chunk hinstellen kann damit gewährleistet ist das diese auch dort funktioniert ?

**Comment by WilhelmGER1313** [comment]
Keine Hilfe ?
No help for me ?

**Comment by BluSunrize** [comment]
Ich hab jetzt schon mehrfach erklärt das debug crash und modliste von Nöten sind.
Des weiteren können wir nichts dafür wenn der server z.B. unter SpongeForge läuft und es deswegen zu Problemen kommt.

**Comment by WilhelmGER1313** [comment]
[debug.log](https://github.com/BluSunrize/ImmersiveEngineering/files/2431763/debug.log)

Modpack: 
FtB  Continuum 
+ ExtendedDays-1.12-0.2.5-22
iChun-Util-Mod-1.12.2
Roguelike-Dungeons-Mod-1.12.2
SilentLib-1.12-2.2.18-100
Twilight-Forest-Mod-1.12.2
BuildCraft-Mod-1.12.2

**Comment by Radical-One** [comment]
I find Continuum doesn't load well a lot of the time (even though my computer has 2x the power of Alienware :man_facepalming: ) so you might want to run all the mods separately using forge instead of using a modpack. If that doesn't work, I have no idea what to do... :confused:

**Comment by WilhelmGER1313** [comment]
Ich kann das Video nochmal hochladen. Da sieht man das dort nix passiert wenn man etwas reinwirft aber wenn ich mich reinstelle bekomme ich Schaden. Ich hatte den Tipp von BluSunrize befolgt und ihn an verschiedenen Orten aufgestellt. Nach dem 9ten Versuch hat es geklappt, warum auch immer. Am Chunk hat es nicht gelegen da der Crusher komplett im Chunk war

**Comment by WilhelmGER1313** [comment]
*push
