### ISSUE TITLE
[Suggestion] Extendable posts, or double height posts

### ISSUE THREAD

**Issue by Rodg88** [BluSunrize/ImmersiveEngineering#3237]
I'd love a return of the extendable wooden posts, where you could stack fences on the top of a post to make it taller. Another option would also just be double height posts as separate items.

**Comment by Alex33212** [comment]
I second this. Imo, the best way to do this would be allowing post extension with fences (treated wood, steel, & aluminum) instead of just a double-height version, as the former allows users to create the pole height that best suits their needs.
