### ISSUE TITLE
[1.12.2] [0.12-85] Bug: Arc furnace won't smelt damaged items.

### ISSUE THREAD

**Issue by blacknight7890** [BluSunrize/ImmersiveEngineering#3240]
A user noticed that the arc furnace wouldn't refund their iron sword, I looked into it and found that while the arc furnace _will_ resmelt metal tools as intended, it will only do so when they are at full durability, it will not smelt the tools/armor at all if they have taken any damage, which goes against the entire point of the feature.
![image](https://user-images.githubusercontent.com/30190786/46390466-feb55400-c6a5-11e8-890a-97fc293e5012.png)
Picture shows that while the damaged tools will not smelt, the undamaged ones will.

I also checked to see if it was due to an inability to calculate for losing one point of durability, but it seems to not matter.
![image](https://user-images.githubusercontent.com/30190786/46390631-c2362800-c6a6-11e8-9dcb-8192c7f4017f.png)

Another issue to note is that damaged tools cannot be manually placed into the arc furnace and must be inputed via the input, likely because it doesn't register as a recipe due to the issue above.

Running Forge 1.12.2-14.23.4.2730. I had uninstalled mods mid testing, but the issue still persisted while I only had IE installed. (second picture is after uninstalling). Modlist **_before_** I uninstalled them:
![image](https://user-images.githubusercontent.com/30190786/46390818-b7c85e00-c6a7-11e8-8faf-84d81a68c53c.png)

**Comment by mindforger** [comment]
If i remeber right, you never could smelt damaged equipment

**Comment by BluSunrize** [comment]
Yeah you could, and it *should* work.
Dunno what changed to break it, I'll take a look
