### ISSUE TITLE
Crash when Minecraft is setting up.

### ISSUE THREAD

**Issue by DragonmasterDJ** [BluSunrize/ImmersiveEngineering#3242]
### Description of the issue:.

Whenever I start up my pack with immersive engineering it gives me a crash. saying Immersive Engineering was to blame. This happens during the second last phase where it loads up the mods. whenever it goes past Immersive Engineering it stops and brings me back to the launcher.

### Crashlog:
https://pastebin.com/hpKnZnhU

### Versions & Modlist
MC 1.12.2
forge 14.23.5.2768

**Comment by PrincessRTFM** [comment]
That is not your modlist. I know that because it doesn't list IE, which you say you have installed. A modlist is _all_ of the mods you have. MC version, Forge version, and all installed mods with their versions.

**Comment by malte0811** [comment]
1. There's a modlist in the crashlog.
2. Temporarily downgrade forge, they made a breaking change and put it into a release build with no warnings.
