### ISSUE TITLE
Crash on Post-Initialisation: java.lang.NoSuchFieldError: field_185200_c

### ISSUE THREAD

**Issue by ssnd292** [BluSunrize/ImmersiveEngineering#3249]
Hello,

I created a small modpack for myself, but the game crashes when IE is about to be Post-Initialised. I tried older versions up until 82, but neither of them worked. I will receive a different error, so I guess it's some sort of mod conflict? The Crash Report isnt of much help either in this case.

Pastebin here:
https://pastebin.com/mt6YbrDT

Short Error:
`net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Immersive Engineering (immersiveengineering)
Caused by: java.lang.NoSuchFieldError: field_185200_c`

Cheers

**Comment by BluSunrize** [comment]
Has been reported many times now, please use the search function.

Downgrade your Forge version for a temporary fix.

**Comment by ssnd292** [comment]
Oh well, I did search before but nothing came up. Thanks for the hint anyway.
