### ISSUE TITLE
Stuck on Mojang Screen

### ISSUE THREAD

**Issue by MajorMinge** [BluSunrize/ImmersiveEngineering#325]
When adding this mod to a custom modpack, I get stuck on Phase 2 of Mod Loading Immersive Engineering, on the "Stitching" Load bar. This is the fml dump:

http://pastebin.com/YMr1Ntw0

Do let me know if there is something I am doing wrong, or need to update a dependency or something. Am using recommended forge version. Have tried multiple versions of IE, always the same error.

Kind Regards,

Major

**Comment by theunkn0wn1** [comment]
OK, added Rekia's Reactorcraft and its dependents to my IE install (FTB Infinity 1.9.0 modified Botania, removed whichery, no other modifications) and launched successfully without crash.

Can you please try without any of Rekia's mods?

**Comment by MajorMinge** [comment]
Still froze at the same place. Here is the fml : http://pastebin.com/DbCvAVQ9

Screenshot of the freeze screen.


<img width="692" alt="screen shot 2015-08-18 at 12 47 37 am" src="https://cloud.githubusercontent.com/assets/13840155/9318313/ce3f03c6-4542-11e5-9867-56a86c2c5592.png">

**Comment by theunkn0wn1** [comment]
OK, just wanted to eliminate that possibility, i see you are using BevosTechPack? are you using a custom modification of that or Using an unmodified version of that pack?

**Comment by MajorMinge** [comment]
Custom version. Updated some of the mods, added a few (namely yours and Reika's). Also updated COFH's mods to the recent recommended and Forge (as stated previously). No other additions besides that.

**Comment by BluSunrize** [comment]
Are you quite sure that it's really stuck? Because texture stitching can take some time.

**Comment by theunkn0wn1** [comment]
OK, working on reproducing your environment, encountering similar issue. debugging....

Same issue, but with 'Enchancedportals' being the culprit. IDK....

i am suspecting its not IE or EP's fault...

Will reply once i arrive to a scientific conclusion

**Comment by MajorMinge** [comment]
I also believe it is not IE's fault. I have left it to stitch for about 10 minutes but no luck. Will leave it longer! Will let you know if there is any progress on my side.

**Comment by theunkn0wn1** [comment]
OK... its not IE's fault. you have run outa RAM.

I am using the Stock FULL version of the mentioned modpack, and updated only what was neccessary to get IE to run without crashing the pack.


Result: default value (4GB) of RAM is not sufficient to run this pack with IE installed. I ended up allocating over 6 GB of ram, half of what my PC has to offer, and it still managed to crash-out.

Conclusion: Not IE's fault, pack is too large (lol)
==================

How i came to this conclusion:
------------
[1] retrieved latest version of AtLauncher
[2] retrived latest version of the modpack in question
[3] modified bare-minimum to get IE to work
[3][a] updated FORGE
[3][b] updated AOBD
[3][c] mounted latest IE built from source (0.5.3 SHA  1c045f51230bffe5ab0bc15da099e0031ebb05f7)
[4] upped max RAM setting in ATLauncher to 6 (Read: Six) GB
[5] attempted to launch pack, monitoring RAM usage.

Result: Crash: out of RAM
=================
![image](https://cloud.githubusercontent.com/assets/3110986/9318823/76e63932-44fc-11e5-96ee-1b3a3183ba60.png)

**Comment by MajorMinge** [comment]
Shit. Well then this sounds like a memory leak of some sort as I have run much larger packs before. Just because the system runs out of ram does not mean that it is unrelated to IE as adding IE is what causes this issue. 

If I leave it to stitch away it crashes to desktop with this fml : http://pastebin.com/8hgC59T3

**Comment by theunkn0wn1** [comment]
still not IE... the exact error is
'java.lang.OutOfMemoryError: Java heap space'

**Comment by BluSunrize** [comment]
And /that/ is why I hate Kitchen Sink packs.

Thanks for clearign it up unknown ^^

**Comment by MajorMinge** [comment]
Thank you for your support.

**Comment by theunkn0wn1** [comment]
@BluSunrize Aye, NP. 

@MajorMinge this issue is the insightly amount of RAM you need to even run the pack, i just ran a control experiment.

Control experiment
=====================
Retrieved the AtLauncher
retrieved modpack in question
ran modpack as-is
![image](https://cloud.githubusercontent.com/assets/3110986/9318964/09590744-44fe-11e5-99d4-9d69cd85a5e2.png)
The peak in Private Bytes is the beginning of stitching FYI
Result: Same Crash, same behaviour
===============

@MajorMinge I would suggest you use a more modest pack, such as one of the bigger packs on the FTB launcher.

**Comment by MajorMinge** [comment]
Right, thank you for the visualization. Will attempt to slim this one, see if I get anywhere.

**Comment by theunkn0wn1** [comment]
No problem, you did manage to spark my interest =3
I do suspect the giant mash of mods that is there (not as big as the pack i run) is conflicting with itself, specially since FORGE was way out-of-date i can only imagine in horror how out-of-date every mod present must be. :scream:

**Comment by cobra** [comment]
I ran into a similar problem some days ago, but with a much, much smaller set of mods. The last thing it logged was loading the revolver textures. I tried reproducing it, but didn't succeed, disabling and up/downgrading mods yielded pseudo-random results. I also had optifine, which might have done some weird stuff regarding textures. Maybe IE has a bug, maybe it's triggering a bug, maybe these were just weird glitches.
Simply rebuilding the pack with the current versions in several steps worked fine, even with optifine.

**Comment by BluSunrize** [comment]
I blame optifine. It breaks so many things that I really wouldn't wanan take credit. To be fair though, I AM doing custom texture sheets for the revolvers. It's not a thing many modders do so who knows...

**Comment by XFactHD** [comment]
As an information in the background: As long as the anvil on the loading screen doesn't stop hammering, the hasn't completely hung up.

**Comment by theunkn0wn1** [comment]
@XFactHD 
the entire JAVAW.exe went non-responsive for a prolonged period of time before crashing, the hammer was frozen in place. MC became completely hung up during my tests, shown by the flat line on the 'Private Bytes' graphs at the end, as Java was trying to grab more memory than it was allocated leading to the crashes.

**Comment by MajorMinge** [comment]
The problem was an incompatibility with the version of fast craft being used. Removed it and then updated it and the problem was fixed. I was without internet for a few days sorry I didn't contribute earlier. Now the pack runs with plenty of memory to spare.

M

**Comment by theunkn0wn1** [comment]
FastCraft? what version exactly?

**Comment by MajorMinge** [comment]
Can no longer remember the version that I was using, but am currently using the latest version and all is well.

M

**Comment by theunkn0wn1** [comment]
Yeah... was not getting any form of incompatibility with the current release (v1.21)
Just wanted to make sure a detail was not missed
