### ISSUE TITLE
Forge 2768 Crash

### ISSUE THREAD

**Issue by Colton-Slayden** [BluSunrize/ImmersiveEngineering#3250]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
Describe what happens, how it affects your game/gameplay and provide screenshots where possible.
Crash On Start up 

### Crashlog:
If your Minecraft instance has crashed, a file will have been generated in the folder `crash-reports` of your minecraft folder. To understand what has happened, we need to know the content of that file. But please don't just put it directly in your report (that makes it hard to read), upload it to a site like [pastebin](http://pastebin.com) or [gist](http://gist.github.com) and put a link in the actuall bug report.
https://pastebin.com/0TGZFsJX

### Versions & Modlist
IE and Forge versions are mandatory. *Note that saying "latest" is **not** valid. Always give the proper version number*
Other mods should be listed (with their versions) in a [pastebin](http://pastebin.com) or [gist](http://gist.github.com) upload. The easiest way to get these lists is a crashlog, you may force one with F3+C.
If your game crashed (see above) you may omit the modlist, but IE and Forge version would still be nice.
forge-14.23.5.2768
IE-0.12-85

Also, please try testing an issue in a minimal instance, with just IE, Forge and maybe JEI. That makes elminating compat issues easier.
https://pastebin.com/h7w6yRKD
Just IE and JEI to show i tried with just them.

**Comment by malte0811** [comment]
> Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.

Looks like you didn't, the last ~10 bug reports have been about just this. Downgrade Forge for now, they changed things in a way that breaks IE and at least 2 other big mods without any warning.

**Comment by Colton-Slayden** [comment]
Well when you just close them and don't leave them open how should we know obviously you didn't think about that. When i opened my issue there was non of the errors in the OPEN tickets so maybe manage your issues instead of saying look for duplicates

**Comment by BluSunrize** [comment]
There's a search function mate. It searches all issues, including closed ones.

**Comment by JoeIzzard** [comment]
The Search function by default searches open tickets. You have to remove is:open from the search to see the closed tickets. However the suggestion bar should suggest closed tickets too, but it can be easy to miss similar items depending on how you word the issue.
