### ISSUE TITLE
[Suggestions] Multiple items!

### ISSUE THREAD

**Issue by FireheartIndustries** [BluSunrize/ImmersiveEngineering#3258]
I have since removed the posts from the Curseforge page, as this is a more appropriate place for this. My bad.

Keep in mind, a lot of these suggestions may involve features from Immersive Engineering (IE), Immersive Petroleum (IP), and/or Immersive Tech (IT). This is just a general ideas suggestion page where I can get all my ideas down for consideration in one place.

===Functionality===

1. Geothermal Energy: Use the Core Sample Drill to locate lava reservoirs (I think it's Immersive Petroleum that adds these alongside the oil ones) and "pump" water down into the ground, collect heat energy, converting it to steam, and then utilizing the steam in turbines to generate electricity. (Maybe have the lava reservoir deplete slowly, decreasing the steam production, and outputting obsidian/cobble as a byproduct?) This may need to be a separate mod since it kinda requires features from all 3 mods (IE, IP, IT) to function in this state, but I figured I would put it out there as a possible feature.

2. Nuclear Energy: This one is rumored to be planned for the 1.13 version of IE, but I just wanted to put it out there. I've been using IE/IT alongside various steam producing reactor mods to make power plants for a while now, and it's really fun because IE adds in a great aesthetic along with proper factories rather than 4 blocks in a line which isn't very...well...Immersive.

3. Toggle-able pipes: the ability to use redstone signals to toggle pipes, so we can disable throughput of fluids for specific pipes. Maybe even valve pipes with a lever or other visual element to indicate the pipes state. This would come in handy when you want to control what fluid is going through which pipe. (Example: Read level in "buffer barrel" so that when level starts to get low, send a signal to disable output of pipe, so Lubricant doesn't try to go into my Diesel Generator and cut off power production because the barrel emptied at some point)

===Decoration===

1. Railings: A decorative/safety item much like fences, but that connect to the sides of blocks below them to make better looking catwalks, avoiding the "Floating Fence" look. Maybe add inclined ones for stairs?

2. Leaded Glass: Another decorative element, literally add lead to glass panes to add a nice detail to your factories. Just do a google image search for Leaded Glass Windows to see what I mean.

3. Caution signs: Decorative signs indicating various hazards such as high voltage, crushing machines, radiation (If radiation will be added with nuclear power?), etc.

I know there's more that I had in mind, but I can't remember them right now. Love the mod, and I really wish I had some modding know-how so that I could try and do it myself. If you have any suggestions for what programming languages/programs I would need to learn to use, I'd be glad to know.

**Comment by Wotzinator** [comment]
i(personaly) would say that adding things that addons already did is not a bad thing i mean other big mods already did such things and also they probably wont just copy and paste everything in if they take things from addons.

**Comment by mindforger** [comment]
1. this would be an awesome project between immersive tech and immersive petroleum!

2. ... well plans, i guess ... :)

3. has been discussed a few times already but i don't know where the very last statement is to find

For the Decorative Stuff:

1. this has already been declined, the advice was to use a steel block with chisel&bits

2. do you mean lead framed glass?! chisle would be my advice :)

3. all of my yes! especially the dangerous voltage sign is an requirement imho since you can get shocks from cable and "new" players are maybe not aware

**Comment by madmurloc** [comment]
Love the idea about warning signs! +1
