### ISSUE TITLE
[1.12.2] Assembler won't craft recipes added via crafttweaker

### ISSUE THREAD

**Issue by SomeLoserThatCantPickOriginalUsernames** [BluSunrize/ImmersiveEngineering#3260]
My complete mod list:
Immersive Engineering 0.12-86
CTM 0.3.2.18
Crafttweaker 4.1.11

I created a custom recipe via crafttweaker, using the following script:
```
import crafttweaker.oredict.IOreDictEntry;
 
val iron = <minecraft:iron_ingot>;
val ironplate = <ore:plateIron>;
val copperwire = <ore:wireCopper>;
 
recipes.addShapeless("simplecircuit",iron,
[ironplate,copperwire,copperwire,copperwire]);
 
recipes.addShapeless("a bucket",<minecraft:iron_ingot>*3,
[<minecraft:bucket>]);
```
When I put the ingredients of the recipes inside one of the assembler's crafting tables, the output shows up in the output slot, but when the ingredients are put inside the assembler's inventory, no crafting occurs. There are no errors when crafting using the custom recipes when using a standard crafting table, and the assembler crafts vanilla and standard Immersive Engineering recipes normally.

**Comment by Raghalin** [comment]
Somewhat the same.  Using IE 0.12-89 and Railcraft Beta-5.  Assembler 'knows' railcraft recepies and will build the item, but will not use internal fluid (ex creosote oil to make Wooden Tie) but will make if manually adding in bucket or glass bottle of creosote oil
