### ISSUE TITLE
Problem with Russian translation of Engineer's Manual

### ISSUE THREAD

**Issue by StarterCraft** [BluSunrize/ImmersiveEngineering#3263]
**Hi,**
I'm using the MC 1.12.2, IE 0.12-85. And I'm playing with Russian language.

And I saw a big problem: the items, blocks, tiles, etc translated to Russian sucsessfully, but the Engineer's Manual text is not tranlslated. I know English well, but I would you fix the problem because it's pleasantly to fully use your good mod with my language.

**Comment by BluSunrize** [comment]
Hi!

Feel free to submit your addition to the lang files as a pullrequest ^_^
