### ISSUE TITLE
Error Message: Null WorldInfo on building Cartographer trade

### ISSUE THREAD

**Issue by realTIMematrix** [BluSunrize/ImmersiveEngineering#3265]
### Description of the issue:
Receive lots of error messages within minecraft game output after starting modpack. 
Don't know how important this error is. This error happens only in combination with JER (this needs JEI).
IE with JEI only does not show this mass of errors :-)
Did not found any similar issues on the interweb or this issue forum

### Logfile:
[https://pastebin.com/raw/Srp3UviV](url)

### Versions & Modlist
minecraft@1.12.2
forge@14.23.5.2768
immersiveengineering@0.12-86
jei@4.12.1.217
jeresources@0.8.5.27

**Comment by BluSunrize** [comment]
It's mostly just a warning that a client world was passed for generating a vein.
It's not crashing and won't cause problems ingame, it's just a debug/warning blurb that I put in.

I'll look into cancelling remote worlds earlier to stop this from spamming the log.
