### ISSUE TITLE
[Suggestion] Pipe Markings

### ISSUE THREAD

**Issue by Alex33212** [BluSunrize/ImmersiveEngineering#3267]
I was making a build with multiple IE pipelines for different fluids, and I realized that it would be really useful to be able to put markings on the pipes in order to differentiate them. So, I'm proposing just that: the ability to put markings on pipes.

The most basic form would be right-clicking on a pipe with a dye to put a band of that color on that piece of pipe, and with some item (sandpaper, perhaps?) to remove any existing band. While this only gives 16 types of markings, this should be plenty for most purposes in the current versions of IE (even including the additions of IP & IT). An alternate option would be to color the whole pipe, preferably changing the texture to a smooth painted look instead of bare metal.

A more advanced system would be a two-color system, with a base stripe and a accent stripe 1/3 the width of the base (similar to the ISO 14726 standard; https://www.wayout.com.au/wp-content/uploads/2017/11/product_p_i_pipemarkers.jpg is an example); the center band would be set by coloring an already-colored pipe. This would give a total of 256 different marking possibilities, albeit with several that are too similar to be differentiated in meaning.

An interesting, though largely unnecessary, addition would be a flow direction indicator; while potentially useful in future builds of IE & Co. with drastically more complex processes, current use would be very limited.

**Comment by malte0811** [comment]
![2018-09-14_17 49 32](https://user-images.githubusercontent.com/10406104/46938010-f294a380-d062-11e8-86d0-e89cecde9a16.png)
Something like what you suggested exists in the latest IE build, as shown in the screenshot.

**Comment by Alex33212** [comment]
Thank you for pointing out this feature!
