### ISSUE TITLE
Arc furnace NPE

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#327]
Issue: NPE with IE's Arc-furnace.
====================
An NPE condition exists with the Arc furnace that when copper\non-iron (?) dusts are placed into the Arc furnace leading to a NPE Crash

(Possible) Steps to reproduce:
=================
[1]construct a valid Arc-furnace
[2] provide it with the required electrodes and power
[3] place copper dust/grit into the PROCESSING inventory of the GUI
[4] wait for item to finish proccessing

//Second crash
[1] re-open world from induced first crash

Version data:
===========
IE version 0.5.3.2 built against e80a703752b01a2817b70d6ef562872288b1dfdb
FTB Infinity version 1.9.0 Modified botania, removed whichery.

Aux.
--------------
Crash log http://paste.feed-the-beast.com/view/79e5b7d1 // crash on world reload, world is now un- 
// usable :{

Appears to be the exact same crash as the above steps

Edit: Removed wierd link... Github markup is confusing....

**Comment by BluSunrize** [comment]
Didn't consider that slag could be null^^
