### ISSUE TITLE
[Suggestion] Ground running cables

### ISSUE THREAD

**Issue by Link2o1o** [BluSunrize/ImmersiveEngineering#3271]
Having a ground hub that functions similar to connectors but can, when placed beside current connectors, connect to connectors and transfer energy to the machines they are attached to.  Essentially a smaller more compact connector to make machine connecting and interior wiring look nicer.  Then have each ground cable connector be able to connect to each other based on energy output ex. LV, MV, and HV.

Possible recipe:
_ _ _
BBB
I I I

**Comment by ktole1999** [comment]
so basically pipes since wires on the ground would sag into the ground texture and look weird. i like the old skool wire look from above.

**Comment by BluSunrize** [comment]
I may be misunderstanding, but you want a block that can just transfer power through floors and walls to any other of that same block?

If so, the answer is no. IE has fancy hanging wires. That's it's whole jig, one of its unique key features.

**Comment by KnightMiner** [comment]
So like project red wires, but power I assume?

**Comment by Link2o1o** [comment]
Yes and no.  The connectors would look/work like that when next to machine connect points or powerable machines.  But you'd wire between the connectors just as it is already done with the hanging wires.

**Comment by Alaberti** [comment]
That sounds really cool, having the wires react to the bounding boxes of other blocks, but also like a huge technical nightmare. Might be something for an add-on dev to play with?

**Comment by BluSunrize** [comment]
Yeah I'm gonna nope that, because trying to render a wire on the ground seems like even more nightmare than the current rendering of catenaries.

Plus it would offer basically no benefit except from a different visual style?
