### ISSUE TITLE
[1.12.2] Crash TileEntityMultiblockPart﻿ & T﻿il﻿eEn﻿﻿ti﻿tyM﻿e﻿talPre﻿s﻿s﻿﻿

### ISSUE THREAD

**Issue by bigenergy** [BluSunrize/ImmersiveEngineering#3272]
### Description of the issue:
Crash

### Crashlog:
[pastebin](https://pastebin.com/gfPND0M9) 

### Versions & Modlist
IE: Immersive Engineering 0.12 - 86
Forge: 14.23.5.2772

**Comment by bigenergy** [comment]
> How did this crash come to pass? Do you have any instructions on how to reproduce it?

Randomly, I just teleported around the world and there was this crash. Then I was no longer able to log on to the server.

**Comment by mindforger** [comment]
@BluSunrize 

ForgeData:{SpongeData:{} ... i suppose sponge things :)

**Comment by BluSunrize** [comment]
Could try using the console to remove that block. Coordinates are in the crashlog.

**Comment by bigenergy** [comment]
how to do it?

**Comment by BluSunrize** [comment]
https://minecraft.gamepedia.com/Commands/setblock

**Comment by bigenergy** [comment]
Thanks, I'll let you know if I can reproduce this crash.
