### ISSUE TITLE
[1.12.2] loading game crash 

### ISSUE THREAD

**Issue by fireair** [BluSunrize/ImmersiveEngineering#3275]
### Description of the issue:
loading the client
### Crashlog:
https://pastebin.com/G8KJnADs
### Versions & Modlist
IE - version 1.12.2.86 forge -1.12.2 14.23.5.2772

**Comment by malte0811** [comment]
That crash report shows IE version 0.12-84. The crash is fixed in more recent builds (specifically 0.12-86).
