### ISSUE TITLE
[1.12.2] [Bug] Pulling through Item Router with Extracting Conveyor voids items

### ISSUE THREAD

**Issue by OmniAesthetic** [BluSunrize/ImmersiveEngineering#3276]
If you place an Item Router next to an inventory, and an Extracting Conveyor opposite that, the items extracted will be properly filtered and extracted, but all other items in the container will be voided one by one in the process. I have tried filtering only the output, only the input, and both, and it happens in all cases.

Here's a short gif of it in action: https://imgur.com/kDUQUC7

It's unfortunate because it would be nice to have some kind of filtered extraction option in Immersive Engineering itself, instead of having to install an entirely separate mod, or use a huge vanilla filtered hopper system. Also, I'm not sure that being able to pull items from a container through a router using the extraction conveyor is intended behavior in the first place (but I hope it is).

Immersive Engineering version: 0.12-86
Forge version: 14.23.5.2772
Mod list: https://pastebin.com/Sya5aWdH

EDIT: Found out that if the item being extracted is in the very first slot of the inventory being extracted from, this bug does not occur. But any other slot and the bug occurs.

EDIT2: Just tried to use a vanilla hopper instead of the extraction conveyor attached to the item router. And the same bug occurs. So the problem must be with the item router, not the extraction conveyor.

Thanks in advance for having a look at this.

**Comment by BluSunrize** [comment]
Fixed for future release, thanks for the report ^_^
