### ISSUE TITLE
Structural Arms do not Wrap Around Corners

### ISSUE THREAD

**Issue by Voxel-Friend** [BluSunrize/ImmersiveEngineering#3282]
![2018-11-05_11 31 48](https://user-images.githubusercontent.com/12395262/48015371-a03d2480-e0ee-11e8-9b60-fa2302bb13b2.png)
![2018-11-05_11 32 11](https://user-images.githubusercontent.com/12395262/48015372-a03d2480-e0ee-11e8-84b5-175adf767ac9.png)
![2018-11-05_11 32 15](https://user-images.githubusercontent.com/12395262/48015373-a03d2480-e0ee-11e8-8740-ce5a0252fcea.png)

**Comment by malte0811** [comment]
Are they meant to? I didn't use them much in 1.7, I just implemented the part I remembered.

**Comment by Voxel-Friend** [comment]
I remember them having that functionality in 1.7.10. Plus it was assumed functionality, as they use the stairs hitbox.

**Comment by Voxel-Friend** [comment]
Aesthetically it would be nice too.
