### ISSUE TITLE
Industrial Hemp growing at a very slow rate

### ISSUE THREAD

**Issue by BladeVanZ** [BluSunrize/ImmersiveEngineering#3288]
Description:
Industrial Hemp Seeds seem to be growing at a slower rate compared to other crops. Initially thought that hemp was not growing at all over time or with using bonemeal and watering can to assist with growing. However, after a very long while, hemp do eventually grow, although still took very long to reach fully grown. When fully grown, the top bit was broken leaving the bottom as per the usual, however, it was still very slow to regrow its top (tested AFKing for about 15mins). 

Is this intended or clearly a bug?

![2018-11-13_05 03 43](https://user-images.githubusercontent.com/44985391/48379144-b6a63a00-e705-11e8-889c-c41a5b32c441.png)

Using:
Immersive Engineering 0.12 - 86
Forge 1.12.2 - 14.23.5.2772

**Comment by MauveCloud** [comment]
Since nobody more official has responded, perhaps I can help.  I notice in your image that you're growing the industrial hemp in a cave.  I've seen in a few other closed issues that industrial hemp grows much better when it can see the sky.  If building your farm open to the sky is impractical for you for some reason, maybe you could look into building a Garden Cloche.

**Comment by mindforger** [comment]
@MauveCloud nailed it down, let it grow under open air or glass if i remember correct

**Comment by BladeVanZ** [comment]
Thanks! I'll give it a try. Garden Cloche was eventually gonna overtake it but early on vanilla style farming is the only option available. However, I find it strange that industrial hemp actually checks if it's below open sky or glass and that all factors into its random growth tick.

**Comment by mindforger** [comment]
> I find it strange that industrial hemp actually checks if it's below open sky or glass and that all factors into its random growth tick.

a lot of mods do this kind of stuff and it is quite an task to manage the environment to match optimal operation of sth. but beyond 1.7.10 most mods did skip those checks and some are relicts ... but i miss em ... a game should be at least a little bit difficult

**Comment by MauveCloud** [comment]
> However, I find it strange that industrial hemp actually checks if it's below open sky or glass and that all factors into its random growth tick.

That's actually a pretty simple check compared to what some mods do.  I think IndustrialCraft 2 crops might hold the record for the most factors influencing growth speed.

**Comment by laz2727** [comment]
To be fair, IC2 crops are also overpowered as heck. The massive growth
resource drain is one of limits placed on high-stat ore plants.

**Comment by mindforger** [comment]
Well, it is „industrial“ scaled ;)

**Comment by BluSunrize** [comment]
Yeah what everyone above said basically. Hemp wants to see the sky to grow at a reasonable rate. Cloches are always an option for underground setups however.
