### ISSUE TITLE
MineTweaker Script for Squeezer and Fermenter require both Output and Fluid

### ISSUE THREAD

**Issue by Bunsan** [BluSunrize/ImmersiveEngineering#329]
I believe there is an error in the minetweaker code for both the squeezer and fermenter (starts on line 27 in both) where the intention is that either the output or the fluid output can be null, but you can't have both be null.  However neither can be null. I believe that you intended it to be AND and not OR. If so then the code should be.
`		//Either output or fluid must not be null. 
		if(MTHelper.toStack(output)==null && (MTHelper.toFluidStack(fluid)==null||MTHelper.toFluidStack(fluid).getFluid()==null))
			return;`

**Comment by BluSunrize** [comment]
mmh, true. Will be fixed
