### ISSUE TITLE
 Server crash problem with Immersive Engineering in 1.10.2

### ISSUE THREAD

**Issue by 16zni** [BluSunrize/ImmersiveEngineering#3290]
So I have a crash problem with Immersive Engineering in 1.10.2.
Excuse me if I do not speak English well but as I am French I do my best to translate.
When I launch my server it crash directly giving me this crash report. I tried to find solutions to these problems but I could not find solutions that worked.

Here is the crash report: https://gist.github.com/16zni/f85706eeb7d94005f724e362018d1160
You will also find at the end of the crash report the list of mods, and the forge version and the: forge_1.10.2 - 12.18.3.2511
Also be aware that the version of Immersive is not the last of the 1.10.2, but I nevertheless try several versions without success.

**Comment by malte0811** [comment]
1.10 is no longer supported. The crash is fixed in 1.12.

**Comment by 16zni** [comment]
I know but my modpack and 1.10.2, so I ask for help for version 1.10.2.

**Comment by CorwinCZ** [comment]
There is no help for version 1.10.2 - you must upgrade your mod-pack or IE.

**Comment by mindforger** [comment]
@CorwinCZ there are people willing to help with 1.10 issues here still, but @16zni  i don't think anybody here is willing to backport the change that fixed this issue

maybe @malte0811 can give a hint which issue it was that got fixed and @16zni or anybody else that is willing to help can backport it to 1.10

**Comment by BluSunrize** [comment]
Yeah 1.10 has not been supported for over a year at this point.
I will not be backporting or releasing any fixes, I instead strongly recommend moving to 1.12 due to a plethora of introduced fixes, balance changes and added features.
