### ISSUE TITLE
[1.12.2] 'fieldSize is too long! Length is #####, but maximum is 44'

### ISSUE THREAD

**Issue by SalmonSays** [BluSunrize/ImmersiveEngineering#3292]
### Description of the issue:
The server fairly frequently kicks players, I've been able to recreate this while idling and not interacting with the world. It's not global in that not all players are kicked simultaneously, and when players are kicked they receive the message "A fatal error has occurred, this connection is terminated"

### Crashlog:
There is no crashlog, but I snagged the error from a running/live log as I was disconnected and that's available here:

https://hastebin.com/higubunexo.shell

I came here because IE is mentioned by name multiple times while no other mod is. The first occurrence is line 67:

[B#397]  \tab at blusunrize.immersiveengineering.common.util.IEFluid$1.read(IEFluid.java:125) ~[IEFluid$1.class:?]\par

### Versions & Modlist
This was produced against "Forge-1.12.2-14.23.4.2768" and "ImmersiveEngineering-0.12-86" alongside a fair few other mods- the thing to note is that v86 was used in a stable manner *before* a handful of other mods updated and the kicks began happening. Here are the mods that updated which appear to have resulted in this weird (possibly compat) issue:

![p2t5eai](https://user-images.githubusercontent.com/11697389/48453305-70d68980-e778-11e8-91a4-9651dd39e40d.png)

My suspicions immediately lie with Forestry due to a roughly similar issue appearing in a previous report:

https://github.com/ForestryMC/ForestryMC/issues/1912

Though it's also worth noting that the issue clearly had Forestry listed in the log in the same way IE is now clearly listed on mine.

I'm going to try rolling back Forestry and testing to see if it stops, but all the same I figured it was worth opening a ticket.

**Comment by SalmonSays** [comment]
Update No. The Next: After idling for upwards of 2 hours with no crash, it looks like it might be narrowed down to RandomPatches 1.7.0.0. I'll let it run overnight to feel extra confident, and then I'll make a new ticket on their mod page to link back to here.

**Comment by SalmonSays** [comment]
Update No. the Next: I've unquestionably confirmed that it's not happening before those mods updated, and have narrowed it down to either Astral Sorcery, Betweenlands, or Simply Jetpacks 2- though my money is on Astral Sorcery after digging through their issue page and noticing something kind of similar:

https://github.com/HellFirePvP/AstralSorcery/issues/904

The main difference is that this kick happens seemingly randomly instead of only when messing with constellations from AS.

**Comment by BluSunrize** [comment]
This is/was a hard one to debug, since it's a packet issue. To my knowledge however, nothing in IE should be sending absurd packets, so let's hope it's indeed the Astral Sorcery issue.

I'll close this, give a shout if the issue persists and more stuff points to IE.
