### ISSUE TITLE
Graphical glitches for multiple objects (1.12.2)

### ISSUE THREAD

**Issue by Dande1231** [BluSunrize/ImmersiveEngineering#3293]
![2018-11-14_20 54 46](https://user-images.githubusercontent.com/45054419/48524768-a601db00-e84f-11e8-8a8e-0f5f23e413ee.png)

Things like transformers, capacitors, relays, barrels and fluid pumps and many other things, and wires don't show up. Anyone know a fix? Not using Optifine btw.

**Comment by malte0811** [comment]
I don't think I've seen this issue before. Could you post a full modlist? Also, since this seems to have started in the middle of a playthrough: what did you change that caused this?

**Comment by BluSunrize** [comment]
Yeah, full debug crash please.

**Comment by Dande1231** [comment]
Mod list ( in mods folder):
CreaticeCore
CTM-MC1.12.2-0.3.2.20
Custom-NPCs-Mod-1.12.2
ImmersiveEngineering-0.12-75
ImmersiveEngineering-0.12-75-core
LittleTiles-Mod-1.12.2
MalisisBlocks-Mod-1.12.2
MalisisCore-1.12.2
MalisisDoors-Mod-1.12.2
Trapcraft-1.12-v2.4.3a-universal
WorldEdit-1.12
I also have some mods in my Flan folder, but Flan's mod itself isn't active.

Debug crash:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CreativePatchingLoader (CreativeCore.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-75-core.jar)
  MalisisCorePlugin (MalisisCore-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.2.20.jar)
  LittlePatchingLoader (LittleTiles-Mod-1.12.2.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 11/15/18 4:22 PM
Description: Manually triggered debug crash

java.lang.Throwable
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1923)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1806)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1923)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['VasiliskGaming'/405, l='MpServer', x=239.02, y=80.60, z=210.24]]
	Chunk stats: MultiplayerChunkCache: 121, 121
	Level seed: 0
	Level generator: ID 04 - customized, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (232,64,236), Chunk: (at 8,4,12 in 14,14; contains blocks 224,0,224 to 239,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 166789 game time, 171268 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 53 total; [EntityWolf['Wolf'/256, l='MpServer', x=240.74, y=71.00, z=230.63], EntityBat['Bat'/1159, l='MpServer', x=263.46, y=38.23, z=272.96], EntityChicken['Chicken'/264, l='MpServer', x=287.10, y=71.00, z=171.09], EntityZombie['Zombie'/2312, l='MpServer', x=300.50, y=55.00, z=262.50], EntityChicken['Chicken'/265, l='MpServer', x=274.84, y=71.00, z=162.51], EntitySkeleton['Skeleton'/1802, l='MpServer', x=219.50, y=38.00, z=231.50], EntityChicken['Chicken'/266, l='MpServer', x=286.40, y=69.00, z=160.84], EntityCreeper['Creeper'/1803, l='MpServer', x=215.50, y=38.00, z=229.50], EntityWolf['Wolf'/267, l='MpServer', x=285.79, y=70.00, z=164.74], EntityCreeper['Creeper'/1804, l='MpServer', x=207.60, y=38.00, z=229.85], EntityChicken['Chicken'/268, l='MpServer', x=276.57, y=70.00, z=169.21], EntityWolf['Wolf'/141, l='MpServer', x=174.55, y=68.00, z=156.27], EntityCreeper['Creeper'/1678, l='MpServer', x=244.50, y=35.00, z=246.50], EntityItem['item.item.egg'/270, l='MpServer', x=283.92, y=70.00, z=165.88], EntityItem['item.item.egg'/271, l='MpServer', x=276.90, y=70.00, z=165.69], EntityWolf['Wolf'/272, l='MpServer', x=285.65, y=69.00, z=265.53], EntityPlayerSP['VasiliskGaming'/405, l='MpServer', x=239.02, y=80.60, z=210.24], EntityWolf['Wolf'/283, l='MpServer', x=290.90, y=70.00, z=179.29], EntitySkeleton['Skeleton'/1692, l='MpServer', x=286.50, y=50.00, z=252.50], EntityWolf['Wolf'/284, l='MpServer', x=295.43, y=70.00, z=180.39], EntityChicken['Chicken'/285, l='MpServer', x=301.51, y=72.00, z=188.21], EntityWolf['Wolf'/286, l='MpServer', x=290.79, y=70.00, z=179.95], EntityWolf['Wolf'/287, l='MpServer', x=290.19, y=70.00, z=179.28], EntityWolf['Wolf'/288, l='MpServer', x=293.08, y=70.00, z=181.02], EntityWolf['Wolf'/289, l='MpServer', x=293.45, y=70.00, z=175.70], EntityChicken['Chicken'/290, l='MpServer', x=292.79, y=70.00, z=186.50], EntityItem['item.item.egg'/291, l='MpServer', x=299.88, y=71.00, z=187.26], EntityCow['Cow'/177, l='MpServer', x=191.87, y=70.00, z=156.83], EntityCreeper['Creeper'/1330, l='MpServer', x=197.50, y=36.00, z=250.50], EntityCreeper['Creeper'/1331, l='MpServer', x=197.50, y=36.00, z=247.50], EntityZombie['Zombie'/1715, l='MpServer', x=263.50, y=57.00, z=243.50], EntityBat['Bat'/1718, l='MpServer', x=178.38, y=37.10, z=265.88], EntitySkeleton['Skeleton'/1470, l='MpServer', x=239.50, y=39.00, z=273.50], EntityCreeper['Creeper'/2371, l='MpServer', x=199.50, y=42.00, z=226.50], EntityCreeper['Creeper'/2372, l='MpServer', x=202.50, y=42.00, z=232.50], EntityWolf['Wolf'/197, l='MpServer', x=204.49, y=71.00, z=171.67], EntityPig['Pig'/199, l='MpServer', x=207.74, y=67.00, z=223.25], EntitySkeleton['Skeleton'/2375, l='MpServer', x=205.50, y=42.00, z=231.50], EntityCow['Cow'/212, l='MpServer', x=220.68, y=71.00, z=189.80], EntityCow['Cow'/213, l='MpServer', x=218.25, y=70.00, z=200.62], EntityPig['Pig'/214, l='MpServer', x=212.60, y=69.00, z=237.27], EntityWolf['Wolf'/236, l='MpServer', x=226.41, y=69.34, z=255.30], EntitySkeleton['Skeleton'/2414, l='MpServer', x=236.50, y=36.00, z=258.50], EntitySkeleton['Skeleton'/880, l='MpServer', x=204.50, y=55.00, z=273.50], EntitySkeleton['Skeleton'/2416, l='MpServer', x=197.50, y=46.00, z=250.50], EntityZombie['Zombie'/1778, l='MpServer', x=197.30, y=38.00, z=237.30], EntityPig['Pig'/245, l='MpServer', x=237.70, y=70.00, z=242.49], EntityPig['Pig'/246, l='MpServer', x=239.75, y=70.00, z=247.51], EntityCow['Cow'/251, l='MpServer', x=257.23, y=72.00, z=149.51], EntityWolf['Wolf'/252, l='MpServer', x=263.88, y=69.00, z=246.42], EntityWolf['Wolf'/253, l='MpServer', x=260.30, y=69.00, z=238.30], EntityWolf['Wolf'/254, l='MpServer', x=260.30, y=69.00, z=239.00], EntityCow['Cow'/255, l='MpServer', x=264.71, y=69.00, z=232.37]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1268020792 bytes (1209 MB) / 1811939328 bytes (1728 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.2.2611 17 mods loaded, 17 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                   | Version           | Source                               | Signature                                |
	|:--------- |:-------------------- |:----------------- |:------------------------------------ |:---------------------------------------- |
	| UCHIJAAAA | minecraft            | 1.12.2            | minecraft.jar                        | None                                     |
	| UCHIJAAAA | mcp                  | 9.42              | minecraft.jar                        | None                                     |
	| UCHIJAAAA | FML                  | 8.0.99.99         | forge-1.12.2-14.23.2.2611.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                | 14.23.2.2611      | forge-1.12.2-14.23.2.2611.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | creativecoredummy    | 1.0.0             | minecraft.jar                        | None                                     |
	| UCHIJAAAA | littletilescore      | 1.0.0             | minecraft.jar                        | None                                     |
	| UCHIJAAAA | mercurius_updater    | 1.0               | MercuriusUpdater-1.12.2.jar          | None                                     |
	| UCHIJAAAA | creativecore         | 1.9.9             | CreativeCore.jar                     | None                                     |
	| UCHIJAAAA | ctm                  | MC1.12.2-0.3.2.20 | CTM-MC1.12.2-0.3.2.20.jar            | None                                     |
	| UCHIJAAAA | customnpcs           | 1.12              | Custom-NPCs-Mod-1.12.2.jar           | None                                     |
	| UCHIJAAAA | immersiveengineering | 0.12-75           | ImmersiveEngineering-0.12-75.jar     | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJAAAA | littletiles          | 1.5.0             | LittleTiles-Mod-1.12.2.jar           | None                                     |
	| UCHIJAAAA | malisiscore          | 1.12.2-6.4.0      | MalisisCore-1.12.2.jar               | None                                     |
	| UCHIJAAAA | malisisblocks        | 1.12.2-6.1.0      | MalisisBlocks-Mod-1.12.2.jar         | None                                     |
	| UCHIJAAAA | malisisdoors         | 1.12.2-7.3.0      | MalisisDoors-Mod-1.12.2.jar          | None                                     |
	| UCHIJAAAA | trapcraft            | v2.4.3a           | Trapcraft-1.12-v2.4.3a-universal.jar | None                                     |
	| UCHIJAAAA | worldedit            | 6.1.8             | WorldEdit-1.12.jar                   | None                                     |

	Loaded coremods (and transformers): 
CreativePatchingLoader (CreativeCore.jar)
  
IELoadingPlugin (ImmersiveEngineering-0.12-75-core.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
MalisisCorePlugin (MalisisCore-1.12.2.jar)
  
CTMCorePlugin (CTM-MC1.12.2-0.3.2.20.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LittlePatchingLoader (LittleTiles-Mod-1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13399 Compatibility Profile Context 15.200.1065.0' Renderer: 'AMD Radeon(TM) R5 Graphics'
	Launched Version: 1.12.2-forge1.12.2-14.23.2.2611
	LWJGL: 2.9.4
	OpenGL: AMD Radeon(TM) R5 Graphics GL version 4.5.13399 Compatibility Profile Context 15.200.1065.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD A8-7410 APU with AMD Radeon R5 Graphics

**Comment by BluSunrize** [comment]
**please** move that to Pastebin or Gist.

Also, remove MalisisDoors and see if that helps.

**Comment by Dande1231** [comment]
Ok, I'll try it.

**Comment by Dande1231** [comment]
Didn't work, still glitched. I tried removing MalisisBlocks and MalisisCore too, but that didn't work.

**Comment by Dande1231** [comment]
I also tried removing the other mods, still broken

**Comment by Dande1231** [comment]
> I don't think I've seen this issue before. Could you post a full modlist? Also, since this seems to have started in the middle of a playthrough: what did you change that caused this?

This didn't happen in the middle of a playthrough, it looked like that from the start.

**Comment by Dande1231** [comment]
Any more suggestions?

**Comment by BluSunrize** [comment]
Have you been able to produce this issue in an instance with just IE?

**Comment by BluSunrize** [comment]
Then I have no idea.
Grab a full game log (startup, login, look at the things, then shutdown) maybe, chuck it on pastebin and link it here. Might be warnings in there to look at.

**Comment by Dande1231** [comment]
OK, I'll try it and give you the log.

**Comment by Dande1231** [comment]
https://pastebin.com/87nVxnas

**Comment by mindforger** [comment]
if i remember right, pastebin has an limitation but you could use https://hastebin.com/ or https://gist.github.com/

**Comment by Dande1231** [comment]
Alright, made a gist, hopefully it should be complete now.
https://gist.github.com/Dande1231/4c3bad73e68d246334f7ff1dcd37dfeb

**Comment by malte0811** [comment]
> ImmersiveEngineering-0.12-75

I didn't notice this before (sorry), but you're using a quite old version of IE (build 75, current if 86). Build 75 was roughly a year old when you opened the report, could you try updating?

**Comment by Dande1231** [comment]
In order to use the newer versions, I have to download a newer version of Forge, but the thing is all of the forge installers I have tried to download have had some sort malicious file, with Windows Defender and Virus total saying it was harmful. So there's that roadblock. Anything else you could try suggesting?

**Comment by BluSunrize** [comment]
I would recommend using the twitch launcher or MultiMC
Both of those are able to install Forge for you and are guaranteed to use the official forge sources for their download.

**Comment by Jaseac** [comment]
I am having the same issues on a daily basis. I lay down a row on conveyor belts, they are all fine till I log in the next day, then they are all a pink chess board again. Let me know If I can do anything to help
![2019-03-01_17 43 28](https://user-images.githubusercontent.com/6056299/53672796-b9438580-3c49-11e9-9932-0668740499de.png)

**Comment by Jaseac** [comment]
And it happened again. Those were vertical belts. This is getting really annoying.
![2019-03-02_01 46 29](https://user-images.githubusercontent.com/6056299/53679081-38a67880-3c8d-11e9-9e17-6e28c3218726.png)

**Comment by mindforger** [comment]
@Jaseac can you also include modlist with versions and versions of forge used? (also just as a general hint, try it again without optifine or other "optimizing" mods and check if the issue persists)

**Comment by Jaseac** [comment]
I just removed about 6 mods, And I wish I had a list of what I removed as when I logged back in the latest ones that went bad were fixed and working again.

**Comment by Jaseac** [comment]
You guys need a discord server!!

**Comment by BluSunrize** [comment]
We have one, I have it linked on my twitter >_>
https://discordapp.com/invite/KGYqfNe

**Comment by Dande1231** [comment]
Sorry for the late (a bit of an understatement at this point) reply. I downloaded forge from minecraftforge.net, which I assume should be safe but VirusTotal thinks differently. I can't find any other sites to download forge, so could someone just link a trusted site to me?

**Comment by TeamSpen210** [comment]
That's the official site.

**Comment by Dande1231** [comment]
I know it is, but apparently it has malware or something. Is there any other way to download forge?

**Comment by PrincessRTFM** [comment]
Try different AV, because it's probably a false positive. Ensure you're using a secure connection to [files.minecraftforge.net](https://files.minecraftforge.net/). Don't use IE/Edge. That is the official site, and is therefore the safest place to download from.

**Comment by mindforger** [comment]
>but VirusTotal thinks differently

since the service VirusTotal to my knowledge is an online service, can you link the result page please? this sounds very strange ... also sorry for going kinda off topic here with a forge/website issue on the IE tracker :P

**Comment by Dande1231** [comment]
It has gone a bit off topic, but it might solve the problem. Anyways, Virustotal says it's clean when I try to scan it now, but I still feel a bit iffy about downloading it.

**Comment by mindforger** [comment]
>This may be what I was looking at

that is why i wanted the result page, to check if th input site is some malformed url that you stepped on
(for future cases, always keep the result link to support the claim you are doing, this is like a crashlog very helpful to know)

**Comment by Dande1231** [comment]
I got newer forge and mod, still broken. Anything else I should try?

**Comment by mindforger** [comment]
since the conveyors bug out after continuing a savegame, my next guess would be the blockdata getting corrupted somehow

can you extract the blockdata from a placed down conveyor and after it bugged out?
>Stand on top of the block, and type: /blockdata ~ ~-1 ~ {} into the chat. All the data will appear on the chat.

i found this trick on reddit, hope it has sufficient data to debug

**Comment by Dande1231** [comment]
Sure, get back to you when I try it.

**Comment by Dande1231** [comment]
Input the command, it said, "Data tag did not change", followed by a bunch of things that I'm too lazy to copy onto here (but I'll post the things if you really need to see them).
