### ISSUE TITLE
Revolver has mystically *disappeared*

### ISSUE THREAD

**Issue by Gammaboy45** [BluSunrize/ImmersiveEngineering#3294]
I have encountered a graphical issue that, thus far, I can only see in the Revolver.
The revolver, both in inventory and in hand, does not render. At all. Shooting bullets from my hands seems pretty cool, but I think it'd be more fitting to have firearms to go with 'em.

In case your curiosity is overwhelming, it looks a bit like this: https://imgur.com/a/0lY3lvs

I will attempt to find which mod may be interfering. If I cannot find a definitive answer, I will provide a full list of mods. For now, I can say I have Optifine(most likely culprit) and Jei.

**Comment by Gammaboy45** [comment]
Well, it was optifine. (as per usual). I'm using version 86 in 1.12.2.

**Comment by PrincessRTFM** [comment]
If you have optifine installed, don't even make a bug report until you reproduce the issue _without_ it. Nobody supports optifine. Nobody has ever supported optifine. Barring a complete change in the optifine license, I suspect nobody ever _will_ support optifine. Optifine works by completely replacing large swaths of rendering code, and it is closed source so that no modder can legally see what it actually _does_. Nobody supports optifine because doing so would be akin to making comprehensible edits to a book you aren't allowed to read.

**Comment by mindforger** [comment]
>Nobody supports optifine. Nobody has ever supported optifine. Barring a complete change in the optifine license, I suspect nobody ever will support optifine.

>edits to a book you aren't allowed to read.

please don't get so upset about optifines policies to handle things and claim such ridiculous things

you seem kinda triggered right now so i won't try to argue with you there, but keep in mind there are other mindsets out there that do indeed tie in optifine into their mods to see if everything workls fine, as you technically can deobfuscate and analyze any bugs with it, it is just kinda annoying to do with this clusterfuck of versions over there :)  ... main reason why the acceptance is pretty low from most of the mod devs i guess?

**Comment by BluSunrize** [comment]
Well as per usual, Optifine is unsupported. Glad you found the source of hte problem quickly however ^_^

**Comment by PrincessRTFM** [comment]
> > Nobody supports optifine. Nobody has ever supported optifine. Barring a complete change in the optifine license, I suspect nobody ever will support optifine.
> 
> > edits to a book you aren't allowed to read.
> 
> please don't get so upset about optifines policies to handle things and claim such ridiculous things
> 
> you seem kinda triggered right now so i won't try to argue with you there, but keep in mind there are other mindsets out there that do indeed tie in optifine into their mods to see if everything workls fine, as you technically can deobfuscate and analyze any bugs with it, it is just kinda annoying to do with this clusterfuck of versions over there :) ... main reason why the acceptance is pretty low from most of the mod devs i guess?

The last time I looked into optifine, it seemed to be just straight up illegal to decompile/deobfuscate it, which means that - at the time, at least - it would have been a lot more effort than anyone I found at the time was willing to go to. This _was_ several years ago though, so I shouldn't be surprised that things have changed. I retract my statements, although I maintain that Blu has declared that optifine is unsupported and so it should be removed before posting a report on IE, and I'll keep that in mind for the future, thank you!
