### ISSUE TITLE
[Suggestion] Chemical backpack tank

### ISSUE THREAD

**Issue by madmurloc** [BluSunrize/ImmersiveEngineering#3299]
I just love the Chemical thrower and the liquid concrete is so fun to play with BUT... all fun stuff ends so fast so how about a backpack tank? just like the Capacitor backpack but for lets say +12 buckets of "fun fuel" or if possible when the chem-thrower has the multi-tank mod equipped two tanks with +6 buckets each. (or for balance purpose +8 buckets single and +4x2 with multitank) #needtosatisfymyneedforfire #burndowntheworld #forallmycookingneeds *maniacal  laughter* ;)

p.s now this is gonna be out there but what if you have the multi-tank and 2 tanks so you can swap between 4 liquids? utility much?

**Comment by BluSunrize** [comment]
No plans to implement this.
