### ISSUE TITLE
Crusher emits weird particles when near bedrock

### ISSUE THREAD

**Issue by CatDany** [BluSunrize/ImmersiveEngineering#33]
http://i.imgur.com/PSey2UY.png

**Comment by BluSunrize** [comment]
Are you sure that that's because of the crusher? .~.
What version of IE?

**Comment by BarbasTheDog** [comment]
I think he's referring to #11 

It manifests in that way because it's messing up with the void particles, but it has the same effect on any particle fx.

**Comment by BluSunrize** [comment]
Oh, that. Yeah that's been fixed. It overrides other particles sheets, but it should be fine now.
