### ISSUE TITLE
[Suggestion] Railgun Quiver

### ISSUE THREAD

**Issue by Cry0dex** [BluSunrize/ImmersiveEngineering#3300]
If i may. I suggest a quiver that would reduce the inventory space used, but have it cap at 3 stacks of a single ammo type, and also have a UI next to the charge meter to indicate the ammo count. If however the ammo limit is not to be touched maybe the ammo count,indicating a simple number of all total items that count as ammo, can be added to the railguns "zoomed" feature?

I am a big fan of the railgun and would to see a little more love for it.

**Comment by BluSunrize** [comment]
No plans for this. The current state of the railgun after it's massive rework feels pretty solid.

Vanilla also doesn't have quivers =P
