### ISSUE TITLE
[Suggestion] Chute for guiding dropped items, made by hitting a scaffolding with an Engineer's Hammer

### ISSUE THREAD

**Issue by chexo3** [BluSunrize/ImmersiveEngineering#3304]
Hollows out the interior of the block and allows IE machines and conveyor belts to drop items into it. The main thing it does is prevent pickup from outside the block, guide the item to keep it within a block, and keep it from despawning, like conveyor belts do. There is no animation, it just falls.  If you right click a scaffolding with an engineer's hammer, it turns into a chute. Shift right-click, and it will turn all the scaffolding above and below that chute into chutes, except for scaffolding that was already a chute, which just adds a note that it was affected by the hammer, rather than turning into a chute again. Shift right click again, and all the chutes without that note (stored somewhere in NBT or memory) turn into scaffolding. When a scaffold or chute switches to or from being a chute, it shows a fading animation, it's texture gets lighter for a moment, then fades back. This animation continues until the server confirms with the client that the blocks have changed into chutes. This is when the model and block ID actually change, clientside. To avoid lagging the client, the client will start this information on blocks it knows it has affected, and the server will tell the other clients to use this animation as well. Then the normal block changing packets are sent, and a particle effect and sound are played, as confirmation. This is all very quick. Unless there is an extremely long ping time, or severe server side lag, clients will see the change to chutes go through the chute system as the update occurs, as quickly as practical. Most of the time, the blocks will get brighter then change their model.  If a conveyor belt leads into a chute, it will open a hole in the side of the chute to drop it's items in. If a downwards conveyor belt leads into the side of a chute, it's model might change for aesthetic purposes. If a downwards conveyor belt leads to the top edge of a chute, it does not open a hole. It will open a hole if there is a dropping conveyor belt though, which you should be able to see the bottom of that dropper through the side of the chute.

**Comment by 777-Scorpion-777** [comment]
I fully support this suggestion. The game has long been lacking pipes on which it would be possible to drop items down. Instead I have to use covered ladders. But I think it should be not a scaffolding but a standalone block.
(Sorry about my English)
