### ISSUE TITLE
[1.12.2]I can’t turn the powered lantern on 

### ISSUE THREAD

**Issue by hawk51173** [BluSunrize/ImmersiveEngineering#3305]
Why I can’t turn my powered lantern on through the LV capacitor (RF is max) but i can turn it on through directly connect the transformer and another hv transformer connect to the diesel generator

**Comment by BluSunrize** [comment]
Pictures of your setup, please.

**Comment by hawk51173** [comment]
> Pictures of your setup, please.

[https://imgur.com/a/njjUPS1](url)

**Comment by BluSunrize** [comment]
Your capacitor isn't set to output on the side you put the connector on.
Use the Engineer's Hammer.

**Comment by hawk51173** [comment]
Thanks I’m so stupid that I didn’t realize this simple problem
