### ISSUE TITLE
Game crashes while initializating

### ISSUE THREAD

**Issue by MATEUS45games** [BluSunrize/ImmersiveEngineering#3307]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
Describe what happens, how it affects your game/gameplay and provide screenshots where possible.

### Crashlog:
If your Minecraft instance has crashed, a file will have been generated in the folder `crash-reports` of your minecraft folder. To understand what has happened, we need to know the content of that file. But please don't just put it directly in your report (that makes it hard to read), upload it to a site like [pastebin](http://pastebin.com) or [gist](http://gist.github.com) and put a link in the actuall bug report.

### Versions & Modlist
IE and Forge versions are mandatory. *Note that saying "latest" is **not** valid. Always give the proper version number*
Other mods should be listed (with their versions) in a [pastebin](http://pastebin.com) or [gist](http://gist.github.com) upload. The easiest way to get these lists is a crashlog, you may force one with F3+C.
If your game crashed (see above) you may omit the modlist, but IE and Forge version would still be nice.

Also, please try testing an issue in a minimal instance, with just IE, Forge and maybe JEI. That makes elminating compat issues easier.

### Lastly (you may delete this from the report itself)
Please, for the love of all that is voxelbased, **read the contribution guidelines. They are linked to the right in the message box.**
When reporting issues, these are crucial, and the team withholds the right to close an issue for the plain stupidity of not reading and adhering to them.

Thank you for reporting issues, without people reporting them, they wouldn't get fixed. You're helping contribute to this mod and that is much appreciated <3

**Comment by MATEUS45games** [comment]
This is my crash report https://pastebin.com/TUHncYBL

**Comment by PrincessRTFM** [comment]
When opening an issue, generally you take the guidelines and edit in the relevant/requested information, not post them verbatim, then make a second post with a crashlog.

Anyway, I see in the crashlog that you're on IE 0.12-85, but the current latest according to this repo's releases tab is 0.12-86. Does the problem still occur if you update?

**Comment by Pultex** [comment]
This happened to me only after updating to the newest Forge did you do that, it worked fine on the older version.

**Comment by BluSunrize** [comment]
yeah outdated version of IE.
