### ISSUE TITLE
JEI/IE bug FPS drop

### ISSUE THREAD

**Issue by ospis12** [BluSunrize/ImmersiveEngineering#3309]
### Description of the issue:
When searching for Immersive Engineering stuff in JEI fps drops like nobody business.
From over 70 FPS to mid 20s.

### Crashlog:
It doesn't produce crash.

### Versions & Modlist
IE : 0.12-86
Forge : 14.23.5.2768
JEI : 4.13.1.255

### System spec:
Lenovo y700
i7-6700hq
( Maybe common issue with JEI?
  https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3813 ,
caching helped with that problem)

**Comment by ospis12** [comment]
Here goes crash report + profiler data
[crash-2018-12-06_15.51.23-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/2653500/crash-2018-12-06_15.51.23-client.txt)
[profile-results-2018-12-06_15.49.42.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/2653504/profile-results-2018-12-06_15.49.42.txt)

**Comment by BluSunrize** [comment]
I meant an actual external profiler, not the integrated one. Something that can actually give detailed data on what is taking up memory and do method runtime profiling.

Also, is this issue reproducable with just IE and JEI?

**Comment by ospis12** [comment]
Only JEI and IE, FPS still happened. What profiler should I use?

**Comment by BluSunrize** [comment]
I use VisualVM myself, I haven't worked with other ones, so I can't speak for them.

**Comment by malte0811** [comment]
I have done some work on this, see the commits above. They reduce the amount of *rendered* quads on a lot of the "big" models by a factor of 7 and reduce the amount of quads rendered for each shader item from 500 something to 3 (only in the GUI).
It would be nice if you could check whether this fixes the lag (and if it doesn't, by how much it reduces the lag), there's a maven build with those commits available [here](https://ci.blamejared.com/job/Immersive%20Engineering/497/).

**Comment by ospis12** [comment]
Tested, results are, how to say it, promising. FPS is most of the time over 30, but I don't know why those quads are so slow to render
