### ISSUE TITLE
Dupe bug with Blast Furnace and Coke Oven

### ISSUE THREAD

**Issue by tlovetech** [BluSunrize/ImmersiveEngineering#331]
When you construct a coke oven or a blast furnace, then break it.. you will get an extra block. 
I use tinker hammers and picks when breaking it.

**Comment by BluSunrize** [comment]
fixed with commit https://github.com/BluSunrize/ImmersiveEngineering/commit/9200be056b205f7680314b9a0c9504c0cfd505f3
