### ISSUE TITLE
[Suggestion] Reworked Logo Text.

### ISSUE THREAD

**Issue by SirChamomile** [BluSunrize/ImmersiveEngineering#3312]
Issue: 

There are just a few flaws in the current logo. 

Solution:

I've redone the text and centered it a bit better, and added back the bottom of the frame. Here are the two to compare:

Old
![ie logo](https://user-images.githubusercontent.com/23204608/49692391-a411fb80-fb1f-11e8-9139-3d35aef53f94.png)

New
![immersive engineering logo](https://user-images.githubusercontent.com/23204608/49692447-e12abd80-fb20-11e8-9bb7-a2d51d01a2a4.png)

Hopefully this is more of a favor than an annoyance. Just thought you might appreciate it.

**Comment by BluSunrize** [comment]
I dunno. I quite like our current logo. The slightly off-center text and grittier, higher contrast plaque is pretty neat, I find.

**Comment by SirChamomile** [comment]
No worries. I just thought it was an oversight.
