### ISSUE TITLE
[Suggestion] Railgun List of Proyectiles

### ISSUE THREAD

**Issue by danikk14g** [BluSunrize/ImmersiveEngineering#3313]
Hello, can we have a whitelist of railgun proyectiles followed by base damage in the same fashion as S:toolbox_tools? in my tech pack there are almost 100 types of rods and also 9 rounds, would be great to have them available as proyectiles, in particular NIB, Neutronium, Naquadah Alloy and Tungsten Carbide.  A railgun cant be defeated by a Draconic Bow. 

Thanks.

**Comment by BluSunrize** [comment]
I have plans to rework the railgun in the future, it will be addressed then
