### ISSUE TITLE
1.12.2 LV wire conenctor crash

### ISSUE THREAD

**Issue by DemonfangArun** [BluSunrize/ImmersiveEngineering#3316]
### Description of the issue:
Placing a LV wire connector on the top of the pump causes the server to crash and the client to lockup and need to be forcibly killed.

### Crashlog:
https://hastebin.com/uvopuvebad.pl

### Versions & Modlist
Forge: 2768
IE: 0.12-86

Also, please try testing an issue in a minimal instance, with just IE, Forge and maybe JEI. That makes eliminating comparability issues easier.
-It doesn't crash if it's just IE in a test instance

**Comment by mindforger** [comment]
>-It doesn't crash if it's just IE in a test instance

Then do a binary search, by removing half of the mods and retest, removing again half of the mods until the problem goes away, return the half that got removed and remove the other half until you are left with a handfull of mods, your pack is waaaaaaaay to big to reproduce

**Comment by DemonfangArun** [comment]
I know it's a big pack :D

Anyway, I have narrowed it down to a defective configuration file.
https://hastebin.com/ujosopoxug.coffeescript

I gave it a moderate once-over and don't see anything blatantly broken.

**Comment by mindforger** [comment]
Either hastebin is mocking me or the links are gone

**Comment by DemonfangArun** [comment]
It's not just you. I thought this was some preferred site for putting pastes, I guess it's actually crap. I'll just stuff the config file here.

[immersiveengineering.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/2666153/immersiveengineering.txt)

**Comment by BluSunrize** [comment]
Could I see the actual crash maybe, so I know what to look for? Because that link is dead.

**Comment by DemonfangArun** [comment]
Here you go

[crash-2018-12-10_16.45.07-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/2668322/crash-2018-12-10_16.45.07-server.txt)

**Comment by BluSunrize** [comment]
Someone decided to put decimal points in all of IE's energy numbers.
Wire Connector Input for instance is set as such:
```
I:wireConnectorInput <
            25.6
            102.4
            409.6
         >
```

Those are integer values, as denoted by the "I" infront. They aren't allowed to have decimal points.
I'd consider running with IE's standard config because someone has clearly messed this one up...

**Comment by DemonfangArun** [comment]
That would be me. I was trying to cut energy usage to 1/10 and putting a decimal was the easiest method. I'll just do an imprecise cut.

I tend to ignore datatype specifications as some mod devs put random letters in that have no correlation to what's being specified.
