### ISSUE TITLE
Crash opening toolbox since last update

### ISSUE THREAD

**Issue by cjser** [BluSunrize/ImmersiveEngineering#3319]
Try to open toolbox after update Immersive Engineering 0.12 - 87 and crashes everytime. Works fine with previous one. Error says be related with mouse tweaks mod (not changed).
[crash-2018-12-10_19.13.11-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/2668344/crash-2018-12-10_19.13.11-client.txt)

**Comment by LotuxPunk** [comment]
Same on server : https://pastebin.com/CBt17wAR

**Comment by mahilo3550** [comment]
I crash every time I try to right click on the toolbox or revolver so far. It's not all GUIs because the workbench is fine.

**Comment by SirAron111** [comment]
Same one  all guis running on the recomended forge version14.23.5.2768.
https://pastebin.com/ZsJpQYdi

**Comment by Echsenkoenig** [comment]
I had this same issue when trying to open a revolver speedloader. Haven't tried other openable, hand held items.

[crash-2018-12-13_22.10.46-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/2678024/crash-2018-12-13_22.10.46-server.txt)

**Comment by DragonmasterDJ** [comment]
Is there a fix for this? I have the same problem.
