### ISSUE TITLE
Arc furnace only accepts iron and won't smelt it!

### ISSUE THREAD

**Issue by eslachance** [BluSunrize/ImmersiveEngineering#332]
So, the book doesn't cover what I'm having issues with (I've looked back and forth, nothing). Essentially, I can only insert Iron Grit in the Arc Furnace, no other grit can be inserted into the 12 slots on the left (manually or through shift+click). Furthermore, even placing iron grit in the Arc Furnace won't even work. It just sits there, no progress. However, the furnace IS sucking power from the system, and it remains at 64kRF/64kRF until that energy runs out (if I remove the connections somewhere).

For a second I thought only accepting iron might have been normal - after all, arc furnaces in other games actually only accept iron and, like, nickel... but the book clearly states that it's good at "smelting *ores*" and that the left slots are for "metals and *ores*".

So... what am I missing?

**Comment by eslachance** [comment]
Oh, additionally... even when it's empty it keeps pulling power... even if the lever is on in the front, it keeps pulling power... I mean, basically right now my fancy Arc Furnace that required around 40 blocks of steel is just a huge power void pipe...

**Comment by LazerusKI** [comment]
Do you have the Graphite Electrodes in the top 3 slots?
Also when i tested it the last time, i could only smelt normal ores, no dust/grit (could have been changed in the newest version)

**Comment by BluSunrize** [comment]
It's been changed to smelt dusts in the lastest version, but throws an NPE currently. TO be fixed in 0.5.4.
It will smelt Ores into ingots+slag and will smelt Iron Ingots/Dust together with Coke Dust in the additive slots into steel.
