### ISSUE TITLE
Crash on having arc furnace

### ISSUE THREAD

**Issue by runescapejon** [BluSunrize/ImmersiveEngineering#3320]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
Describe what happens, how it affects your game/gameplay and provide screenshots where possible.
I'm not really sure what happen here but a player of mine was reporting to me that he was crashing because of arc furnace when he attempt to login to the server he crashes I ask him if he knew how to reproduce the crash he said he didn't know how.  I will upload the crash log here below on to a pastebin. Please let me know if you need anything else many thanks.
### Crashlog:
If your Minecraft instance has crashed, a file will have been generated in the folder `crash-reports` of your minecraft folder. To understand what has happened, we need to know the content of that file. But please don't just put it directly in your report (that makes it hard to read), upload it to a site like [pastebin](http://pastebin.com) or [gist](http://gist.github.com) and put a link in the actuall bug report.
https://pastebin.com/raw/jsxaq4Sp
### Versions & Modlist
IE and Forge versions are mandatory. *Note that saying "latest" is **not** valid. Always give the proper version number*
Other mods should be listed (with their versions) in a [pastebin](http://pastebin.com) or [gist](http://gist.github.com) upload. The easiest way to get these lists is a crashlog, you may force one with F3+C.
If your game crashed (see above) you may omit the modlist, but IE and Forge version would still be nice.

Also, please try testing an issue in a minimal instance, with just IE, Forge and maybe JEI. That makes elminating compat issues easier.
Verison that i use is 
Forge: 14.23.5.2784 
Immersive Engineering:  0.12-86 
### Lastly (you may delete this from the report itself)
Please, for the love of all that is voxelbased, **read the contribution guidelines. They are linked to the right in the message box.**
When reporting issues, these are crucial, and the team withholds the right to close an issue for the plain stupidity of not reading and adhering to them.

Thank you for reporting issues, without people reporting them, they wouldn't get fixed. You're helping contribute to this mod and that is much appreciated <3

**Comment by JoeSGT** [comment]
I am having the same issue here it i do not know what causing it.

@JoeSGT - just tagging myself to keep track of my issues

**Comment by BluSunrize** [comment]
Have you tried breaking the Arc Furnace and remaking it?

(also, usually the explaining text of the issue you delete, leaving just the headlines =P)

**Comment by JoeSGT** [comment]
@BluSunrize  do you have any idea on what went wrong? so it can give me a clue as to recreate it?

**Comment by DragonmasterDJ** [comment]
Not too sure how it would of happened, maybe a clash between chunks if you built it between two of them. that's why I try to keep my multiblocks within the same chunk.

**Comment by BluSunrize** [comment]
Yeah I can't tell you what caused it. Potentially chunkloading/corruption problems.

Glad you got it fixed though!
