### ISSUE TITLE
Crash before game starts

### ISSUE THREAD

**Issue by SyntaxError73** [BluSunrize/ImmersiveEngineering#3321]
https://pastebin.com/AYhrR8mP

I am using Forge 1.12.2-14.23.5.2796 along with Immersive Engineering 0.12-87, and the Class for the Faraday Suit Item is not defined. It is definitely not another mod causing this crash as far as I can tell.

Upgrading and downgrading the mod and versions of Forge did not help whatsoever. Deleting the configs had no effect either.

**Comment by BluSunrize** [comment]
I would recommend trying to remove mods then to figure out which one is causing it.

Binary Search is your best option here, taking out half the mods seing if that fixes it. If so, the issue is in that half, otherwise in the other half. Just keep splitting until you figure out the incompatability.

**Comment by mindforger** [comment]
>Caused by: java.lang.SecurityException: class "blusunrize.immersiveengineering.api.tool.IElectricEquipment"'s signer information does not match signer information of other classes in the same package

That looks like a broken file
