### ISSUE TITLE
severe problem crash 12/15/18

### ISSUE THREAD

**Issue by zues3000** [BluSunrize/ImmersiveEngineering#3322]
im having a problem loading minecraft only with the mod Immersive Engineering

[crash-2018-12-15_20.19.35-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/2683192/crash-2018-12-15_20.19.35-client.txt)

### Versions & Modlist
Forge versions  forge-1.12.2-14.23.5.2768-installer-win

**Comment by malte0811** [comment]
Update IE. You're on version 85, the current one is 87.

**Comment by zues3000** [comment]
thank you i now working
