### ISSUE TITLE
Game crashes when reloading revolver

### ISSUE THREAD

**Issue by Elfinlocks** [BluSunrize/ImmersiveEngineering#3326]
Currently running a server on 1.12.2 with forge .2768. When using the latest edition of Immersive Engineering (0.12-87), the game and server simultaneously crash when attempting to reload a revolver, in the right or left hand.

**Comment by Elfinlocks** [comment]
That's the .log.gz file from when it ran into the issue right?

**Comment by BluSunrize** [comment]
It shouldn't be a gz file, no. There should be a "latest.log" file in the log folder. Of course if you restarted the server since, it's probably best if you reproduce the issue first and then fetch the log.

**Comment by Elfinlocks** [comment]
Unfortunately I did restart it since then. I'll reproduce the issue and get that to you ASAP.

**Comment by Elfinlocks** [comment]
Here's the log from the crash when it occurred. I'll try and keep an eye on this thread in case you require any more info. Thanks for your help!

[2018-12-18-2.log](https://github.com/BluSunrize/ImmersiveEngineering/files/2692454/2018-12-18-2.log)

**Comment by BluSunrize** [comment]
Same error as #3319

Fixed for next release already.
