### ISSUE TITLE
[1.12-87]Snow blocks vertical conveyor belt.

### ISSUE THREAD

**Issue by lordfriend** [BluSunrize/ImmersiveEngineering#3331]
![2018-12-24_14 31 58](https://user-images.githubusercontent.com/1235614/50392421-402b3c00-0789-11e9-8d26-aeff6230a4c4.png)
As the screenshot shows, snow can accumulate at the output of the vertical conveyor belt, make it be blocked. I don't know whether it is possible but I think the best way to prevent this from happening is to disable snow accumulation on the conveyor belt totally. It is also realistic since the conveyor belt is not static

**Comment by PrincessRTFM** [comment]
I feel like it would be _more_ immersive to have _all_ conveyors blocked by any snow on them, as snow on conveyors IRL would be a problem. I don't know about _implementing_ that, but it'd make you need covered conveyors (or at least a larger tunnel of blocks to keep the snow off) when you're going through snowy biomes. You could Chisel&Bits a cover for the corners like this, assuming that IE doesn't end up with some kind of hollow scaffolding for this purpose (and given that C&B has a chisel mode to take off a whole plane of bits at once, I'd call that feature a dogwash personally) and then you'd also get to see snow on top of your conveyor tunnels, which I think could look nice.
