### ISSUE TITLE
Suggestion: New offensive Tinkers material that apply the stunning effect on mobs using RF

### ISSUE THREAD

**Issue by mser7** [BluSunrize/ImmersiveEngineering#3332]
If you attack a mob using the tool with this trait, it will electric the mob for a short time, by applying the "stun" effect, but it also require RF for it to work, so you will have to recharge it using a Charging Station.

**Comment by BluSunrize** [comment]
Electrum in TCon already has a very similar effect to this. It builds up charge as you walk around.
