### ISSUE TITLE
[Suggestion] Clay extraction and Redstone deposit 

### ISSUE THREAD

**Issue by MisterGlerk** [BluSunrize/ImmersiveEngineering#3336]
I've noticed out of all the mineral deposits for the extractor in IE, there's nothing for redstone, which is a must-have resource for any technology mod. Also, with the silt deposits, there should be a way to process clay automatically from the block form, preferably in a crusher.

**Comment by mindforger** [comment]
You can define your own deposit variants, i made a set which does not include empty buckets, but loads of dirt, sand and clayblocks to keep the collector busy or get creative
