### ISSUE TITLE
[1.12] Placing Blueprint on Workbench causes the game freeze forever

### ISSUE THREAD

**Issue by danikk14g** [BluSunrize/ImmersiveEngineering#3337]
### Description of the issue:
When i place a "components" blueprint the minecraft instance becomes unresponsive, only solution i found is to kill the javac process. But when i restart the game it wont let me load the world anymore. Apparently the reason of this issue is that i have many custom recipes added with CT to the Workbench "components", i think there are almost 30.
The rest of the blueprints dont give this problem, all of them have very few recipes, "molds" is the only one with one custom recipe added.

Version 0.12-87 started causing this issue, which is not happening with 0.12-86,  the version i am currently using for my pack.

### Versions & Modlist
Forge version: 1.12.2-14.23.5.2796
IE version: ImmersiveEngineering-0.12-88
CT version: CraftTweaker2-1.12-4.1.13

Thanks

**Comment by BluSunrize** [comment]
Could you please provide a log file? That would help considerably.

**Comment by danikk14g** [comment]
Sorry for the delay in the response, 
[latest log](https://drive.google.com/open?id=1vLEaPEPwuUs2KjmsDGdlYw8juAliFWIj)
[debug log](https://drive.google.com/open?id=1GqPYvk8LnK_mkWelU6l6VlJFqIKDJctP)

**Comment by BluSunrize** [comment]
Hmm, I can't see any actual error messages in there, however, the blueprints aren't really designed for those amounts of recipes.
All GUIs and handling are laid out for maximum 9 recipes per blueprint.

**Comment by danikk14g** [comment]
i had the same amount of recipes for nearly 4 months when i released the pack, before 0.12-87 it never gave me this problem.

Still if it cant be solved r i will try to reduce it to less and see if its ok.

Thanks.

**Comment by danikk14g** [comment]
So i was able to reduce the number of recipes using the "components" blueprint from 37 to 24, but here is the resulting render: https://imgur.com/a/TPTOEBp

A config option to disable the new blueprint rendering on the workbench would be apreciated

Thanks again.

**Comment by BluSunrize** [comment]
Like I said, it's very much not intended for that sort of setup. The GUI of the workbench should be looking equally messy, as should the one of the Auto Workbench multiblock.

I would strongly recommend adding multiple blueprints instead of cramming everything into one.

**Comment by danikk14g** [comment]
oh i didnt know that could be done, thank you for your help.
