### ISSUE TITLE
[IE 0.12-88] Blast Furnace Preheater rendering

### ISSUE THREAD

**Issue by jcarrete5** [BluSunrize/ImmersiveEngineering#3338]
The blast furnace preheater has some interesting shading on it when using OptiFine. This doesn't occur when not using OptiFine. Not sure if this is a bug with OptiFine or IE.

When using OptiFine, the blast furnace preheater looks like this:
![2018-12-29_18 42 35](https://user-images.githubusercontent.com/6133706/50543081-5dea0e00-0b9a-11e9-99ea-a626f87d889e.png)

Without OptiFine, the preheater looks like this:
![2018-12-29_18 41 16](https://user-images.githubusercontent.com/6133706/50543082-693d3980-0b9a-11e9-9e5a-ce78cb247b67.png)

### Versions & Modlist
MC: 1.12.2
Forge: 14.23.5.2768
IE: 0.12-88
OptiFine: 1.12.2_HD_U_E3
CTM: 0.3.3.22

**Comment by BluSunrize** [comment]
Optifine is not supported. Says so quite clearly in the contibution guidelines.
