### ISSUE TITLE
Crash when TerraFirmaCraft is installed with 0.5.3.2

### ISSUE THREAD

**Issue by Gideonseymour** [BluSunrize/ImmersiveEngineering#334]
http://paste.feed-the-beast.com/view/276a0877

**Comment by BluSunrize** [comment]
Feels like TFC isn't registering their items right. This isn't really my fault, I'm using perfectly ordinary methods. I must assume that they are messing with the registry

**Comment by mindforger** [comment]
i am having the same issue with another mod and trying to figure out, but it seems somewhat common that the registry crashes with this particular call, maybe you can get some inspiration for a workaround  here https://github.com/MineMaarten/IGW-mod/issues/26

**Comment by BluSunrize** [comment]
I attempted a fix similar to Maarten's, testing this might be hard for you, since this is part of my 0.6 transition. If you build IE from git now, don't use any addons.
