### ISSUE TITLE
[Suggestion] Some more lights

### ISSUE THREAD

**Issue by cybercat5555** [BluSunrize/ImmersiveEngineering#3347]
As nice as Immersive Engineering is, one thing it lacks is many lighting options. Sure we have the 2 lanterns and the floodlight, but they're better suited for large outside builds, why not some ones more fitting for inside use? And so there can be more uses for power and for more aesthetics as well. Some specific styles i'm thinking of would be a [singular caged light bulb](https://skinflint.s3.amazonaws.com/images/products/thumbs/700x700_cv_13-1754-caged-polish-industrial-lights-b.jpg) (but smaller than the old ProjectRed cage lights, more like the size of a flowerpot, perhaps a bit bigger), a [hanging funnel-shaped light](https://i.pinimg.com/originals/6e/ce/61/6ece6114a7d488d2c9af635881543186.jpg), and a [larger framed florescent light](https://www.prolighting.com/media/catalog/category/highbays.png), but more industrial and with a single tube instead of the modern looking white plastic and LED tube one in that link. Maybe the large frame light could also act like the floodlight? Possibly these new lights could be created with a new blueprint? I'd assume all could act as power relays themselves much like the powered lanterns.

**Comment by vladimir264** [comment]
I too would like to see more lighting options
Im currently looking around for an add-on that might do just this.
