### ISSUE TITLE
no generation of bauxite ore 

### ISSUE THREAD

**Issue by ROCKERTROLL** [BluSunrize/ImmersiveEngineering#3348]
Hello, is been a week that i made a modpack, and i don't found any bauxite ore in the world, i try to take a look at the configurations, but is everything ok, and i don't know what to do to solve this

**Comment by BluSunrize** [comment]
You need to offer a lot more information.
I need to know what versions you run and what other mods are involved. There is contribution guidelines [here](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/CONTRIBUTING.md), please read them and follow them when reporting an issue.

**Comment by ROCKERTROLL** [comment]
Hi, the version is (0.12-88; on twich app)
The list of all mod is:
 Ai improvements
Apple skin
Applied Energistics 2
Backpacks
Baubles
Better builder's wands
Better fps
Botania
Carry on
Chamaleon
Clumps
CodeChikenlib
Colytra
Commom Capabilities
Connected Textures
Construct's armory
Cosmetic Armor reworked
Craft tweker
Cyclops core
Ender IO
Ender storage
Ender core
Extra utilities
Foamfix
Forestry
Horse Tweaks
Hwyla
Immersive engineering
Immersive petroleum
Industrial Foregoing
Inventory tweaks 
Iron backpacks
Iron chests 
JEI bees
Jei villagers
journey map
Just enough Harvastcraft
JEI
Just enough petroleum
Magic bees
Mantle
Mcjtylib
More overlays
Mouse tweaks
Neat
No Mob Spawning on trees
Not enough wands
Openblocks
Openmodslib
Ore excavation
Pam´s Harvestcraft 
Placebo
Plustic
Quickleafdecay[
Shadowfacts'forgelin
Storage Drawers 
Swing Through grass
Tesla core Lib
Thaumcraft
Thaumic inventory scanning 
Thaumic JEI
Tinker's JEI
Tinker's construct
Tinker's tool leveling
toast controal
Tomb many graves2
tomb many graves2 api
Tomb many plugins
torchmaster 
Toro health damage indicators
Unidict
waninLib
Wawla

**Comment by BluSunrize** [comment]
If Bauxite is not disabled in IE's config, it should generate. Unless there is concrete evidence to a failure on our end, I'm closing this one.
