### ISSUE TITLE
1.12 engineer's toolbox inventory lost when changing to Creative mode

### ISSUE THREAD

**Issue by Gunner76th** [BluSunrize/ImmersiveEngineering#3349]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
Describe what happens, how it affects your game/gameplay and provide screenshots where possible.

While carrying the Engineer's Toolbox that contains items, and entering creative mode, all items in the toolbox are lost. This is similar to the bug with the Golden Bag of Holding in Extra Utilities 2 https://github.com/rwtema/extrautilities_old_issues/issues/1366

Whether the mechanics and reasoning are the same for the Engineer's Toolbox losing its inventory is the same as the Golden Bag of Holder or not I can not say, but from the user's perspective it is a very similar issue. 

Steps to repeat: 
Startup and run FTB Presents StoneBlock 2
Craft the Engineer's Toolbox
Open the toolbox and put various items into it for storage
Enter creative mode then return to survival mode (opening or moving the engineer's toolbox does not seem to matter)
Once back in survival mode reopen the toolbox and observe its contents are gone. 

### Crashlog:
If your Minecraft instance has crashed, a file will have been generated in the folder `crash-reports` of your minecraft folder. To understand what has happened, we need to know the content of that file. But please don't just put it directly in your report (that makes it hard to read), upload it to a site like [pastebin](http://pastebin.com) or [gist](http://gist.github.com) and put a link in the actuall bug report.

N/A

### Versions & Modlist
IE and Forge versions are mandatory. *Note that saying "latest" is **not** valid. Always give the proper version number*
Other mods should be listed (with their versions) in a [pastebin](http://pastebin.com) or [gist](http://gist.github.com) upload. The easiest way to get these lists is a crashlog, you may force one with F3+C.
If your game crashed (see above) you may omit the modlist, but IE and Forge version would still be nice.

Also, please try testing an issue in a minimal instance, with just IE, Forge and maybe JEI. That makes eliminating compat issues easier.

IE: 0.12.88
Forge: 14.23.5.2796
ModPack: FTB Presents Stone Block 2

### Lastly (you may delete this from the report itself)
Please, for the love of all that is voxelbased, **read the contribution guidelines. They are linked to the right in the message box.**
When reporting issues, these are crucial, and the team withholds the right to close an issue for the plain stupidity of not reading and adhering to them.

Thank you for reporting issues, without people reporting them, they wouldn't get fixed. You're helping contribute to this mod and that is much appreciated <3

**Comment by ViciousVinnyD** [comment]
Bump, same issue, custom built pack using latest version of IE (0.12-88)

**Comment by mindforger** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/2737 ...

**Comment by malte0811** [comment]
^That. And, as I said in the other issue, this is a Forge bug. No clue when/if it will be fixed/fix itself in some MC update.
