### ISSUE TITLE
Industrial Squeezer has input grid set as output inventory rather than the output slot

### ISSUE THREAD

**Issue by TacoMage** [BluSunrize/ImmersiveEngineering#335]
This is with IM version 0.5.3.2

If you hook something up to an industrial squeezer that extracts items, such as an itemduct with a servo on it or a BC wood pipe with a redstone engine, the conduit will pull from the 3x3 input grid rather than the output slot.

Easiest way to reproduce is to rig an industrial squeezer with an import and an export chest.  Toss some coke dust in the import chest and the coke will flow into the squeezer and then be ejected into the export chest before it has a chance to be turned into graphite.  If you let the graphite be created then activate the export, the graphite will never be extracted into the export chest.

Liquid exports correctly.

**Comment by theunkn0wn1** [comment]
I can confirm this, and add to it.

Issue: Output block for the Squeezer acts as the interface to the input slots
========================
Items can be both inserted and extracted from the 'output' blocks int he Squeezer MB structure

Steps to reproduce:
----------------------
[1] correctly build Industrial Squeezer MB
[2] hook any automation device that allows for extraction to the 'output' blocks of the structure
[3] place input items into squeezer, regardless of power
[4] enable item extraction on device established in [2]

[5] pump items extracted **back into** the squeezer via any of the 'output' slots


Aux.
---------------
![image](https://cloud.githubusercontent.com/assets/3110986/9374155/97f29614-46a7-11e5-8567-5513f5644838.png)


Version data:
------------
IE version [0.5.3](https://github.com/BluSunrize/ImmersiveEngineering/commit/9200be056b205f7680314b9a0c9504c0cfd505f3)

FTB Infinity (1.9.0) modified botania, removed whichery

**Comment by TacoMage** [comment]
This bit is not accurate:

"Expected result:

Nothing, no known output for the Squeezer results in output items, only fluids"

Coke powder results in an item of Graphite Powder in the industrial squeezer.  Expected result is that graphite powder should be extracted from the output.

**Comment by theunkn0wn1** [comment]
ah, i had not known of that recipe, was under impression that only seed oil could be made in the machine, my error, will correct

**Comment by TacoMage** [comment]
This issue still somewhat persists.  The input slot is now functioning properly, but the output slot still cannot have the contents extracted.

Liquids still function properly.
