### ISSUE TITLE
[1.12.2] [v 0.12-86] Revolver auto-aggro's ALL mobs upon firing

### ISSUE THREAD

**Issue by Poojawa** [BluSunrize/ImmersiveEngineering#3350]
### Description of the issue:
Upon firing the revolver, Hostile mobs from a long range were automatically aggressed and immediately started moving in to smash my face in without looking at them or being normally close to their locations.

### Versions & Modlist
FTB Revelation v 2.6.0
IE v 0.12-86

Discovered in multiplayer, Confirmed in single player. Initially was wondering why Endermen were teleporting in to wreck my face in, despite not having looked at them. Then ended up getting their stare spooky noise then they were already smacking me around.

**Comment by BluSunrize** [comment]
This is not a bug, it's a feature and was explicitely mentioned in the changelog for release 84:
```
- Added a "Noise" component to the revolver, which will make it attract nearby mobs when fired (BluSunrize)
    - Adding a bit of a stealth/survival aspect
```

**Comment by Poojawa** [comment]
Could projectile speed/damage get a significant buff to account for the sheer masses this pulls in? There's almost no reason to use the revolver except as a gun turret prerequisite
