### ISSUE TITLE
[1.12.2] Enderio recipes

### ISSUE THREAD

**Issue by Mikotochan** [BluSunrize/ImmersiveEngineering#3351]
### Description of the issue:
When changing the recipe of an EnderIO material (such as making the dark steel ingot require steel rather than iron) in EnderIO's XML recipe files (config/enderio/recipes/user) the arc furnace still uses the old recipes. I think that it would be desirable rather than having a few hard-coded recipes (in https://github.com/BluSunrize/ImmersiveEngineering/blob/0a3f6ca345114779dd04ea24c4ca3640c9afd6f9/src/main/java/blusunrize/immersiveengineering/common/util/compat/EnderIOHelper.java#L42-L53) to automatically detect any recipes for such items.

**Comment by mindforger** [comment]
>When changing the recipe of an EnderIO material

in which way?

to my knowledge you can modify all arcfurnace recipes using crafttweaker (what is it called yet?)

**Comment by BluSunrize** [comment]
Basing it on their recipes loaded from their xml would require actively tying into EIO and making use of API (if they provide recipes in there) or reflecting into it.
I don't feel like doing either.

IE's current implementation of their recipes is fully oredictionary based (and would for instance work if another mod added DarkSteel) and I like to keep it that way.

As mindforger said, changing IE's recipes with CraftTweaker is probably your best option.
