### ISSUE TITLE
[Suggestion] Alternate bigger windmill models

### ISSUE THREAD

**Issue by jbengtson** [BluSunrize/ImmersiveEngineering#3357]
Would it be possible to get a much larger version of the windmill in order to make a proper post mill? The current windmill model is, for lack of a better word, puny.

https://i.imgur.com/v7VOSOo.png

I pulled the model from the .jar file and did a simple x2.0 scale on it in Blender, it would need some work that I don't know how to do in order to make it look as good as it does normally, but this is about the size I was thinking:

https://i.imgur.com/7IuDV1W.png

Bigger would work too, a 9 or 11-wide building would be awesome to house some machinery. :)

**Comment by TeamSpen210** [comment]
Logically this would be perhaps an upgraded windmill, with a crafting tree requiring double or quadruple the resources.

**Comment by TeamSpen210** [comment]
Logically this would be perhaps an upgraded windmill, with a crafting tree requiring double or quadruple the resources.

**Comment by jbengtson** [comment]
I don't particularly care about the power output or the crafting recipe, but I don't see this as an "upgraded" windmill, merely an alternate model. Windmills come in all shapes and sizes and I imagine the benefit of a larger one would be more torque rather than outright speed, so having it make more power without, say, a gearbox block or whatever, wouldn't really make sense to me.

Regardless, the request isn't for additional "progression", it's for an alternate model.

**Comment by mindforger** [comment]
but make it rotate way slower and add a gearbox to make use of all that additional torque, doesn't the dynamo care about rpm for power? :D
