### ISSUE TITLE
[Suggestion] Pollution of the Realms integration

### ISSUE THREAD

**Issue by Shandoo94** [BluSunrize/ImmersiveEngineering#3358]
I am currently creating configs for the Pollution of the Realms mod to add integration with a few machines. To do that correctly for IE machines a nbt tag is required to know when the machine is active so that the mod can then generate pollution.
The coke oven already has such a tag for example. The arc furnace and the crusher are lacking such a tag. The active tag of the excravator wheel doesn't change its value in the newes version of IE.

**Comment by trygve55** [comment]
Hey @BluSunrize, I can try to implement this for you if you're interested. I'm also interested making it compartible with the Pollution of the Realms mod.

**Comment by BluSunrize** [comment]
Pretty sure that Pollution of the Realms is only on 1.12, and we do not support that version anymore.

**Comment by Seth0067** [comment]
Hey guys - Seth here from the Pollution team - we are on 1.16 now, and when I pinged Ender Lanky, he indicated this is still relevant enough to be addressed.  Might I appeal to you to have another look?
