### ISSUE TITLE
 [1.12] Seethrough chests after adding blueprint to engineer's table

### ISSUE THREAD

**Issue by Nerosro** [BluSunrize/ImmersiveEngineering#3361]
### Description of the issue:
Chests become seetrough as soon as the engineer's table receives a blueprint
![afbeelding](https://user-images.githubusercontent.com/5601152/51389612-26350d00-1b2d-11e9-905e-061f51ed3c06.png)
![afbeelding](https://user-images.githubusercontent.com/5601152/51389617-29c89400-1b2d-11e9-9cd5-0fa400b6cec6.png)

### Versions & Modlist
Forge-14.23.5.2781
IE version: 0.12-88
Modlist: Enigmatica 2 Expert modpack

**Comment by Nerosro** [comment]
Addition: Adding extra items to the workbench while it has a blueprint in it causes the seethrough to disappear as well
![afbeelding](https://user-images.githubusercontent.com/5601152/51432145-30413380-1c33-11e9-9567-db565766bf7e.png)
![afbeelding](https://user-images.githubusercontent.com/5601152/51432167-86ae7200-1c33-11e9-8474-e902a9e836fe.png)

**Comment by darkrider0** [comment]
I have the same problem.

**Comment by mindforger** [comment]
just by chance, can you test this without optifine or confirm you are not using optifine?

**Comment by Nerosro** [comment]
Optifine is not in the modpack.
I also didn't add it to the pack manually

**Comment by BluSunrize** [comment]
I remain unable to reproduce this unfortunately.

I recognize it to be a visual glitch quite likely caused by the Blueprints, but I can't reproduce it to work on a fix.
Do you have a reliable, reproducable setup for this, Nero?

**Comment by wuhkuh** [comment]
I have a backup of a world where this is happening (FTB Revelation world, version 2.7.0). Can confirm it is caused by blueprints; after removing it, I can't seem to reproduce the visual bug. I could send you the world file if you're interested.

**Comment by cridenour** [comment]
I've also seen this happen in Enigmatica 2: Expert. Was recently reminded of it watching a playthrough: https://youtu.be/9vAu76EAG5Y?t=1569

**Comment by Lanse505** [comment]
@Nerosro @darkrider0 @wuhkuh 
Do any/all of you have Bonsai Trees in your packs?

Also, I've been able to at least sporadically reproduce this using just two mods, Bonsai Trees and Immersive Engineering in a normal work using Forge: 14.23.5.2838.
The exact parameters of how to reproduce this bug are still unknown, be it some "magic angle" or secret button combo and blood sacrifice, I don't know.

The hunt continues, Excelsior!

**Comment by Lanse505** [comment]
Been able to reproduce it using a set-up like this:
![image](https://user-images.githubusercontent.com/1495068/58590417-51aacf80-8264-11e9-90b2-2073a0ef90fa.png)

**Comment by Lanse505** [comment]
But once again it's not a reliable thing, like if I move or change something about how I'm looking it might intermittently not work.

**Comment by Lanse505** [comment]
Works without the Bonsai Pot as well apparently 💭 
![image](https://user-images.githubusercontent.com/1495068/58590536-93d41100-8264-11e9-8e7b-a0499f86abd1.png)

**Comment by Lanse505** [comment]
Muahaha, caught it on video!
Still super hard to reproduce but it occurs with a simple chest + Engineers table setup.
https://streamable.com/w1im5

**Comment by Lanse505** [comment]
For Reference:
This is using:
- Forge: 14.23.5.2838
- Bonsai Trees: 1.1.2-b144
- Immersive Engineering: 0.12-89
- World Type: Default
- Video Settings:![image](https://user-images.githubusercontent.com/1495068/58591224-19a48c00-8266-11e9-9242-293fa0c3353e.png)

**Comment by Lanse505** [comment]
Also happens during night in dark situations if that makes any difference :P
![image](https://user-images.githubusercontent.com/1495068/58591461-9fc0d280-8266-11e9-9f39-95385b15949c.png)

**Comment by Lanse505** [comment]
Just noticed this detail, 
![image](https://user-images.githubusercontent.com/1495068/58591489-b2d3a280-8266-11e9-9968-94889ffe0221.png)

For some reason whenever the chest is see-through, the icons placed by the blueprint is also glowing?
