### ISSUE TITLE
[1.12.2] Engineer's skyhook crash 

### ISSUE THREAD

**Issue by VladoCC** [BluSunrize/ImmersiveEngineering#3364]
Game crashes everytime I try to use skyhook.

Forge 14.23.5.2808
IE 0.12-88

https://pastebin.com/azZfJXXU

**Comment by mindforger** [comment]
ookay concurrentmodification inside the sound system ... that's odd ... can you try without optifine for test?

**Comment by VladoCC** [comment]
Seems that it happenes only with optifine

**Comment by esotericist** [comment]
I experienced this today as well (and similarly was taken aback by the concurrent modification in the sound subsystem), but unlike the original submitter of this issue, I do not have optifine.

https://gist.github.com/esotericist/03c2e132982d0ce735da634e81d4b17c

**Comment by mindforger** [comment]
in your case i would suggest a test without foamfix and randompatches, but only on a fresh world. Maybe foamfix does something similar with the sound system and i could not find out what randompatches is but it patches quite a few classes
