### ISSUE TITLE
[1.12.2] unable to remove some mod compat recipes through CT

### ISSUE THREAD

**Issue by Yoghurt4C** [BluSunrize/ImmersiveEngineering#3365]
### Description of the issue:
Immersive Engineering insists on keeping its compat recipes for other mods; for example, you're unable to remove some https://github.com/SlimeKnights/TinkersConstruct alloying recipes (Aluminium Brass and Manyullyn) from the IE Arc Furnace, and molten IE Constantan from the ticon Smeltery
![image](https://user-images.githubusercontent.com/11313954/51644633-d5387500-1f81-11e9-9752-57a162912d17.png)
![image](https://user-images.githubusercontent.com/11313954/51644639-dbc6ec80-1f81-11e9-8094-158ecd35174e.png)
![image](https://user-images.githubusercontent.com/11313954/51644643-e5505480-1f81-11e9-9139-a7310218463e.png)
![image](https://user-images.githubusercontent.com/11313954/51644658-04e77d00-1f82-11e9-8bc0-9964c34dc19b.png)

### Versions & Modlist
ie: 0.12-88
ct: 4.1.14
mt: 4.0.15
forge: 2807

**Comment by codewarrior0** [comment]
Brief investigation shows that CT scripts run during the `registerRecipes` event, which is fired immediately before the FMLInitializationEvent (`onInit()`). The IECompat module for TConstruct adds this arc furnace recipe during `onInit()`.

**Comment by BluSunrize** [comment]
I've got a fix for this stuff in the pipeline, but I will point out that the alloying recipe shown there is from TCon/Thermal Foundation. That's their Constantan, not ours =P
