### ISSUE TITLE
[Request] Pass unprocessable items

### ISSUE THREAD

**Issue by DemonfangArun** [BluSunrize/ImmersiveEngineering#3368]
I would like to request a config option whereby if a machine (crusher, arc furnace, etc...) cannot process an item, it simply forwards it to the output instead of destroying it (crusher) or getting jammed (arc furnace).

**Comment by PrincessRTFM** [comment]
I'd like to request a configuration option to instead set a "default output" of sorts, such that throwing an item into a crusher that has no recipe can be made to produce a generic scrap item, for instance. Such an item needn't be added by IE, but being able to specify that any item for which no recipe exists will instead result in some pre-defined item found in game could be useful and nicely immersive.
