### ISSUE TITLE
[Minor bug] NaN on infinite electrodes

### ISSUE THREAD

**Issue by DemonfangArun** [BluSunrize/ImmersiveEngineering#3369]
### Description of the issue:
When electrode durability is set to 0 (infinite) the electrodes display "Integrity NaN%". I assume this is because there is no code to handle this as it's a non-recommended configuration. In this instance it would be better to display "Infinite Integrity" or "Unbreakable" or something similar.

Everything functions fine otherwise, this is mainly nitpicky.

### Versions & Modlist
Forge: 2800
IE: 0.12-88

**Comment by malte0811** [comment]
Setting durability to 0 isn't meant to give them infinite durability. There isn't any code in IE to do this, MC just treats items with max. damage of 0 or less as not damageable.

**Comment by DemonfangArun** [comment]
While that fixes the original issue, now they cannot be set to have infinite durability, so a new setting is needed.
