### ISSUE TITLE
[1.12.2] External Heater not updating active status

### ISSUE THREAD

**Issue by serialtasted** [BluSunrize/ImmersiveEngineering#3370]
When giving an External Heater a redstone signal it's NBT data value for "active" doesn't change to "1". It only updates the block if a furnace is on top. But if you keep the block on with a redstone signal and remove the furnace it'll stay on (the NBT value "active") and show in game as active. Once you turn the redstone signal off it'll go "active" "0".

It would be useful if the heater gets active with a redstone signal either with a furnace on top or not. This would give the possibility for compatibility with other mods as a source block of heat.

IE Version: ImmersiveEngineering-0.12-88

**Comment by BluSunrize** [comment]
The "active" flag in NBT refers directly to the internal workings of the Heater. It's not designed to be monitored by other mods.
Instead, if a mod wants to make use of the heater and its API, it can do so by implementing the interface `IExternalHeatable` or registering a `HeatableAdapter` as per this API method: https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/api/tool/ExternalHeaterHandler.java#L70
