### ISSUE TITLE
Workbench eats items inside including Blueprint if you break the right side of the bench instead of the left side.

### ISSUE THREAD

**Issue by KaneHart** [BluSunrize/ImmersiveEngineering#3371]
Workbench eats items inside including Blueprint if you break the right side of the bench instead of the left side.

Pretty much you need to break it on the left (the main block) or you lose both contents and blueprints. 

Version:
ImmersiveEngineering-0.12-88

**Comment by BluSunrize** [comment]
Yeah, persistent issue that I still haven't gotten around to fixing.

It's on the list, but probably won't be in the next update.
