### ISSUE TITLE
Crusher does not work with Geolosys Ores

### ISSUE THREAD

**Issue by duncanwebb** [BluSunrize/ImmersiveEngineering#3372]
### Feature request:
Would it be possible to add the Geolosys ores to allow the crusher to process them? 

Only the excavator can mine the Geolosys block ores, for example oreBlockHematite. Using a pick will give oreIron either as a Geolosys cluster or with silk touch vanilla iron ore. There are two special ores that drop multiple ores when mined, Limonite gives iron and nickel clusters and Galena gives lead and silver clusters.

I reckon the crusher would be the best machine for this task. Currently the only option is to manually mine the block ores (no block breaker in the pack I'm playing)

### Versions & Modlist
IE 0.12-88
Forge 14.23.5.2768.

**Comment by TeamSpen210** [comment]
As an interim solution, you can use CraftTweaker to add anything to the Crusher. From your description though it sounds like what should happen is the Excavator should blacklist thpse ores since you're not supposed to have them in your inventory.

**Comment by bookerthegeek** [comment]
A better option would be to chanhe the veins to drop the drops from the ores instead of the ores themself.

Is this a pack you built yourself or one on curse? The script should be pretty easy to make either way you go with either chanhing the excavator output or adding it to the crusher, or both.

**Comment by bookerthegeek** [comment]
https://gist.github.com/bookerthegeek/4091d7893751f49a527035fc2c92a359

**Comment by dannydjdk** [comment]
Thank you @bookerthegeek !!! This saves me much time.

**Comment by dannydjdk** [comment]
There is one small adjustment, @bookerthegeek . The chance of the secondary output should be one or less, so 0.2 and 0.8 rather than 20 and 80 (which make the chances 2000% and 8000%). Otherwise, it works beautifully!

**Comment by duncanwebb** [comment]
Thank you all very much.
