### ISSUE TITLE
[1.12]Suggestion: Alternative floodlight powering methods

### ISSUE THREAD

**Issue by fluid-uu-matter** [BluSunrize/ImmersiveEngineering#3374]
Floodlights in this mod are awesome(to use with other mods), but it can only be powered by linking a wire to it directly, so I have to use the wire connection even if there are ducts from other mods everywhere. and wire can disappear after a PC force-reboot.
So could you add a method to power floodlights without wire?(e.g. a wireless light controller that can accept energy from other mods' ducts as well as connectors from this mod?)

**Comment by BluSunrize** [comment]
Nope. I have no incentive to support ducts, after all it's in my best interest to make people use IE's wires =P
