### ISSUE TITLE
[1.12.2] Suggestion: Make the gun turret better

### ISSUE THREAD

**Issue by NanoCats** [BluSunrize/ImmersiveEngineering#3376]
For one, the "Blacklist" option seems to be counter intuitive, If I click "Blacklist" I'd assume it shoots the people on the list? wrong, and I guess you can't have it not attack typical mobs? the only other checklist options are "Animals" and "Neutrals", which doesn't include an option for targeting hostile mobs or not.  What I would suggest is a more sensible UI like OMT's (See reference [Here](http://puu.sh/CGY4e/90efa98f74.jpg))

Also the range is pretty pitiful, no way to upgrade or modify it after the fact in any way, there's no real reason to use it. Especially because the sentry gun will ALSO do some really stupid things like... waste all its ammunition trying to shoot at things through a wall, which it does for some reason.

I can never be sure if it's configured correctly.

**Comment by BluSunrize** [comment]
You can absolutely just use creature names for the turret. You can write "pig" in there and it will stop shooting pigs (if you are set to "Blacklist" mode)
