### ISSUE TITLE
[Suggestion]Vein map

### ISSUE THREAD

**Issue by Blue-Beaker** [BluSunrize/ImmersiveEngineering#3378]
I'm tired of checking extracted core samples in the world, could you please add a vein map?
The vein map shows nothing but chunk borders when created and you can right click placed core samples with it to display the vein on its chunk. Expected yield will also show on the chunk. When you hover on a chunk that has a discovered vein, it will show the information of the vein like you hover on the core sample. If right clicked the vein when its chunk already have a record on its chunk, the information on the map will be overwrited.

**Comment by BluSunrize** [comment]
That's the reason you can
1) use a normal map on a sample to set a marker
and
2) place core samples in the world as blocks, so you can keep a reference of the stuff you found in an archive/museum

**Comment by fluid-uu-matter** [comment]
> That's the reason you can
> 
> 1. use a normal map on a sample to set a marker
>    and
> 2. place core samples in the world as blocks, so you can keep a reference of the stuff you found in an archive/museum

1.Markers on normal map doesn't show up vein information
2.placed core samples is not convenient to use

**Comment by MalkContent** [comment]
for now, if you are using opencomputers, you can give this here a try:
https://gist.github.com/MalkContent/9895d615f0765255d2a4ad99a5a3fb21

**Comment by BluSunrize** [comment]
If you hang a map in a frame, it will show you the name of the vein now, on hovering over.
