### ISSUE TITLE
Squeezer crash (NPE)

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#338]
Issue: Squeezer crash, NPE
----
Steps to reproduce:
--------
Possible steps below:
[1] correctly build a squeezer
[2] open squeezer interface
[3] attempt to spawn items (Via NEI(?)) with a full inventory

Aux
-------
[crashlog](http://paste.feed-the-beast.com/view/7faa884b)

Version data:
------------
IE version [0.5.3](https://github.com/BluSunrize/ImmersiveEngineering/commit/9200be056b205f7680314b9a0c9504c0cfd505f3)

FTB Infinity (1.9.0) custom botania, removed whichery

**Comment by BluSunrize** [comment]
That's a NEI error, not an IE error.

**Comment by theunkn0wn1** [comment]
This NEI error only occurs when an IE inventory is open. Shall i go and report this to NEI's author instead?

**Comment by AEnterprise** [comment]
it's an NEI issue, i've had this heapen with both vanilla and modded gui's

**Comment by theunkn0wn1** [comment]
OK, i will leave it at that then.
