### ISSUE TITLE
Unable to remove recipes of Alloy Kiln

### ISSUE THREAD

**Issue by RenanVieira88** [BluSunrize/ImmersiveEngineering#3381]
### Description of the issue:
Unable to remove recipes of Alloy Kiln
In crafttweaker log its appear to be done 
"[INITIALIZATION][SERVER][INFO] Removing Alloy Smelter Recipe for item.meta_item.name"
But in-game still there

### Script/Log:
Script: https://pastebin.com/jVM9BEGV
CraftTweaker log: https://pastebin.com/GcdGJ1S9

### Versions & Modlist
forge-1.12.2-14.23.5.2810
ImmersiveEngineering-0.12-88
CraftTweaker2-1.12-4.1.11
gregtech-1.12.2-1.5.17.167

**Comment by BluSunrize** [comment]
I don't add Compat for GregTech, so I'm not sure what that recipe even is.

What is the GT item it is outputting?

**Comment by RenanVieira88** [comment]
was bronze, what happened was that I was using UniDict to unify the ores, for some reason it was working normally, but after I update IE I had to remove the UniDict to get the original outputs and remove the recipe for those

**Comment by BluSunrize** [comment]
Hmm, well, I've moved a bunch of compat recipes to the respective registration phase now.
Bronze was always handled properly however, so I can't speak for that one specifically.

If this is an issue cropping up with UniDict, I have to assume that they are modifying the recipe at a point after Crafttweaker runs. So you may need to find out what that recipe originally output and try to remove it based on that.

In either case, that's not really an IE issue.

**Comment by RenanVieira88** [comment]
Yes, I solve this removing unidict, change recipes with original IE recipes and then add unidict again, btw tnks for attention
