### ISSUE TITLE
Albedo maven is down

### ISSUE THREAD

**Issue by LiskoSlayer63** [BluSunrize/ImmersiveEngineering#3385]
I merged your project with mine and tried to setup the gradle, but the Elucent's Albedo maven repository seems to down. I can't build your repository because I can't find that 2.0-SNAPSHOT version of Albedo. 

EDIT: I managed to remove all the Albedo related features and build the mod.

**Comment by BluSunrize** [comment]
Fixed by:
https://github.com/BluSunrize/ImmersiveEngineering/commit/90a01d1c1dcaf8f5d6fbce5c9a601c122373e942
