### ISSUE TITLE
"The upgrade" The upgrade advancement isn't triggering

### ISSUE THREAD

**Issue by monstersquishy** [BluSunrize/ImmersiveEngineering#3387]
I'm running a feed the beast server. Mine craft 1.12.2. 
Some of my players and I are having a small issue with this mod. 
The Advancement 'The Upgrade' isn't triggering on our server.
When we make a Steel Ingot in the Crude Blast Furnace. 
We have the previous Advancement in the tree that leads to 'The Upgrade' so we don't think that is the reason. 
We've tried making multiple ingots but none of them trigger.

**Comment by BluSunrize** [comment]
Is it an IE steel ingot you are getting or a steel ingot from another mod?

**Comment by monstersquishy** [comment]
Im told that the crude blast furnace is generating Thermal Foundation steel ingots instead of ImmersiveEngineering steel ingots which is causing the upgrade to not trigger

**Comment by BluSunrize** [comment]
Yup, that is exactly why it's happening. Someone changed the output for the Blast Furnace's recipe without changing the required item for the advancement.

**Comment by monstersquishy** [comment]
ok so how do we fix it?
