### ISSUE TITLE
He caused my server to crash

### ISSUE THREAD

**Issue by 3269199948** [BluSunrize/ImmersiveEngineering#3388]
[crash-2019-02-17_18.55.40-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/2872888/crash-2019-02-17_18.55.40-server.txt)

sponge version: 1.12.2 2768

mod version : 0.12-88

**Comment by mindforger** [comment]
>Caused by: com.google.common.util.concurrent.ExecutionError: com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: Lio/github/flibio/economylite/bstats/Metrics;

>| UEE   | economylite          | 2.15.1             | [plugin][经济]EconomyLite-7.1.0-2.15.1.jar                   | None                                     |

what makes you believe IE is causing this crash when the report says otherwise??

or is this some sort of API clashing?

**Comment by 3269199948** [comment]
I have checked my plugin . I'm sorry to bother you .
