### ISSUE TITLE
[Request/1.12.2 Bug?] "Live" config edits

### ISSUE THREAD

**Issue by PrincessRTFM** [BluSunrize/ImmersiveEngineering#3392]
The in-world "Mod Options" menu allows changing setting without reloading the game, or even the world, but apparently at least _some_ of the settings don't take immediate effect on changes. I am using this feature to add tool items from other mods into the Engineer's Toolbox, but it doesn't take effect when I save and close the menu, returning directly to the game. Is this possible to implement, or is there a bug in my instance that needs a full report on?

This is on IE version 88, by the way.

**Comment by BluSunrize** [comment]
I wasn't even aware we enabled live config edits. I sure didn't consciously do that.
@malte0811 did you ever add support for that, or does Forge just default to allowing it now?

**Comment by malte0811** [comment]
I did add support for it, and it works for most things. The problem is that a lot of config options are "cached" somewhere else, I probably missed some of those (I need to manually copy over the config value after the config is changed in-game).
