### ISSUE TITLE
steel wont die

### ISSUE THREAD

**Issue by TheNimbleNinja** [BluSunrize/ImmersiveEngineering#3393]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
im trying to remove the steel recipe from all immersive craft machines and its refuseign to die and i dont know why
### Versions & Modlist
forge-14.23.5.2810 and immersive enginnerring-0.12-89

Also, please try testing an issue in a minimal instance, with just IE, Forge and maybe JEI. That makes elminating compat issues easier.

**Comment by BluSunrize** [comment]
Okay, you might have to get a bit more precise with that.
What are you doing to remove the recipes?

**Comment by TheNimbleNinja** [comment]
im using the syntaxs to remove the steel recipes and they wont get removed. the alloy smelter did get removed but the blast furnace and the arc furnace refuse to remove the recipes. and sorry it took me months to respond

**Comment by TheNimbleNinja** [comment]
import mods.immersiveengineering.BlastFurnace;
import mods.immersiveengineering.ArcFurnace;
import mods.immersiveengineering.AlloySmelter;
import mods.immersiveengineering.MetalPress;
//remove

mods.immersiveengineering.AlloySmelter.removeRecipe(<thermalfoundation:material:160>);
mods.immersiveengineering.BlastFurnace.removeRecipe(<thermalfoundation:material:160>);
mods.immersiveengineering.ArcFurnace.removeRecipe(<thermalfoundation:material:160>);


these are what im putting

**Comment by malte0811** [comment]
Try `immersiveengineering:metal:8`. I don't know which steel the machines will produce in your pack, it depends on the config.

**Comment by BluSunrize** [comment]
Try putting it in arrow signs. It's `<minecraft:melon>`, not `minecraft:melon`

**Comment by TheNimbleNinja** [comment]
using <immersiveengineering:metal:8> removed the steel from those 2 machines thanks malte
