### ISSUE TITLE
[Suggestion] Manual revolver cylinder rotation

### ISSUE THREAD

**Issue by DaveArndt** [BluSunrize/ImmersiveEngineering#3394]
The ability to rotate the revolver's cylinder with sneak+scroll, switching the next chamber to be fired.

Fights using the revolver usually only last a couple of shots. Considering the variety of ammunition types, it would be helpful to be able to load multiple types into different chambers, switching as needed to adapt to different situations. For example, I might walk around with buckshot in the current chamber in case I run into a close-range threat and need to panic fire, but switch to other chambers with Casull cartridges for long-range threats. I could also carry a selection of potions in phial cartridges, rapidly switching between debuffing enemies and healing allies.

**Comment by mindforger** [comment]
>Considering the variety of ammunition types, it would be helpful to be able to load multiple types into different chambers, switching as needed to adapt to different situations

sounds just like Triple X, loving the idea :D

**Comment by BluSunrize** [comment]
I've considered it, it just means a mess of sending packets in order to make those client controls actually take hold on the server side.

I might mess around with it, but it's a hard maybe.

**Comment by DaveArndt** [comment]
I might remember how to do it. I did something similar in 1.7.10, but it was a little messy and I haven't touched the game since. Time to re-learn Forge, I guess.

**Comment by BluSunrize** [comment]
Oh I absolutely know how to do it, I've done plenty client-based controls before, and IE has an existing packet system. It's 100% doable, I just need to actually look into it and make it not exceedingly messy =P

Also, I'm on holiday until March.

**Comment by DaveArndt** [comment]
Mind if I take a stab at it? It sounds like you have more important things to work on, and I already started. A lot of the code is almost identical to switching chemthrower tank, so it should be hard to mess up.
