### ISSUE TITLE
[QUESTION] Mo' Creatures and CustomMobSpawner

### ISSUE THREAD

**Issue by LiskoSlayer63** [BluSunrize/ImmersiveEngineering#3395]
So I have some questions related to Mo' Creatures and CustomMobSpawner. I want to build a village with powered lanterns to get rid off random mobs which can spawn at night, so

**1. Does Powered Lanterns disable mob spawning when using Mo' Creatures and CustomMobSpawner?**
**1.1 Does it affect only for vanilla mobs or all mobs including Mo' Creatures?**

Also the Werewolf from Mo' Creatures needs a Silver Sword to damage it, so

**2. Is it possible to get Silver Cartridges to damage the werewolves added by Mo' Creatures?**

**Comment by BluSunrize** [comment]
1) Powered Lanterns prevent hostile mob spawns. If the creatures in question are considered hostile in code it will be prevented.

2) That would mean adding explicit compat for them, and if they do it on basis of a custom damage source, then no, that won't happen. I've done that hacky workaround once for Witchery and it wasn't pretty, I don't see myself doing it again.

**Comment by DoomRater** [comment]
According to Mo' Creatures changelog, what's required for a weapon to hurt their werewolves is that the weapon has silver in its localized name. I took a look at the entity projectile, but I didn't see anything with a silver name in it.
