### ISSUE TITLE
[1.12.2] World loading crash with exception in server tick loop

### ISSUE THREAD

**Issue by theProdigy246** [BluSunrize/ImmersiveEngineering#3398]
since I have updated my forge version to 1.12.2 - 12.23.5.2799, the game always crashes at world loading.
tried IE versions 0.12.86; 0.12.88 and 0.12.89

https://pastebin.com/CSiFmWBP

**Comment by Redimio** [comment]
I am having this same problem, I have tried forge versions 1.12.2 - 14.23.5.2768 and 1.12.2 - 14.23.5.2814 but I keep getting the same error when loading a world.

https://pastebin.com/QQ5XcpMd

**Comment by CastielAngelow** [comment]
Are you able reproduce it without Foam Fix and your weird JVM args...? 📦

**Comment by mindforger** [comment]
Is the current git code broken somehow?

i see an "RenderMinecart.class" but i can't find any references anywhere?!

**Comment by theProdigy246** [comment]
With older forge versions it worked, but i need the newer one for railcraft, this also could be the reason for the changed renderminecart class

**Comment by mindforger** [comment]
the JVM arguments are fine imho, nothing that does not belong there or does strange things

the g1heapsize=32M is a bit on the large size and may cause very few but longer lasting lags over time and with heavy world gen but everything is fine so far, just some garbage collector options to reduce lag overall

**Comment by theProdigy246** [comment]
fixed the problem by deactivating the solid minecart rendering of RC. Thanks for the help
