### ISSUE TITLE
[Suggestion] Make BreakerSwitch more useable

### ISSUE THREAD

**Issue by mindforger** [BluSunrize/ImmersiveEngineering#340]
I like the Design of the BreakerSwitch, but there are 2 things that dissapoint me a bit:
- The Cableconnection design
- The limited use cases

The Design on how to connect cables make the switch look a bit ugly, as unwrapped blank (probably HV) cables are hooked directly on the breaker, only a few cm/inces from the actual handlever (looking somewhat dangerous)... and the cable always are hanging towards the user, as i can not connect them backwards because of the raytracing

i always wished for a breakerbox or something that needed either a Redstone(RS) signal or a Breakerswitch(BS) attached, so the BS only acts as inverted RS signal (incative=RS on but no effective RS signal output, just an API or something):

Something like a 1x1 block with up to 2(or more) connectors for the 5 sides and a side where either an RS signal or the BS can be applied to (the position of connectors and the rotation can be adjusted by the IE Hammer, like the pole)

Additionally, the code used for the BS to control the breakerbox can be reused for all machines, so the BS can be used instead of an ugly Vanilla Lever to control the machines!

And as a Bonus, everybody else using your API could make use of that BS

**Comment by theunkn0wn1** [comment]
Yeah, +1 for the RS breaker idea. It would be really useful to be able to remotely cut off parts of my network. Power Utility companies, at least in the USA, have the ability to remotely shut off parts of the power grid they control for maintenance.

I also agree the existing breaker in IE just breaks immersion, with HV lines within close proximity the the players hand, i feel like i should be converted into fried chicken if i dared approach one of these breakers in survival

**Comment by BluSunrize** [comment]
Poke Damien. I cobbled that thing together in less than an hour. I wanan do more with it and spoilers, it will be used more once I get into RF-powered lights, but yeah...

**Comment by cobra** [comment]
I don't know yet how to realize this properly, but one idea to get this more realistic would be to use multiple parts: a handle (the current model is quite nice for this, alternatively just a vanilla lever for redstone control), some linkage to cover the safety distance and the actual switch with two connectors. The switch could be either a block with a larger model (fake multiblock) consisting of two connectors or it could simply connect or tilt away to disconnect from an adjacent connector in the direction it's facing.
This is how real world switch pylons work, see [this example](https://upload.wikimedia.org/wikipedia/commons/f/f7/Masttrenner.jpg).

Maybe use this for the dangerous MV/HV stuff and a simple one block directly operated switch like the current solution for LV.

**Comment by mindforger** [comment]
@BluSunrize what is the most efficient way to poke Damien? he seems never to react to my tweets ... i want to poke him right into the eye :P

**Comment by BluSunrize** [comment]
Most effective way to poke him is IRC. He never comes around my channel though, so try #Kihira =P
Also, Breaker Switches got changed in the last commit, they now emit redstone signals, that (with an upcomign comit) will be invertable.
I /do/ like the fact that HV wires go on them though, controlling high voltage with a massive lever gives me a nice "mad scientist"-feel x3

**Comment by cobra** [comment]
but but but what about EVEN BIGGER LEVERS? *scnr*

**Comment by mindforger** [comment]
>I /do/ like the fact that HV wires go on them though, controlling high voltage with a massive lever gives me a nice "mad scientist"-feel x3

i do not complain about HV bein attachable, but i am complaining about the "how" :P blank wires closer than the spark gap to my hand and the switch-contacts also is somewhat breaking the immersion, that was the reason to ask for a bereaker box with connector poles and the switch in front
https://upload.wikimedia.org/wikipedia/commons/c/c2/Oil_circuit_breaker_MKP-110_Toliatti_Russia.jpg

**Comment by XFactHD** [comment]
@mindforger Look on Damien's twitter page, there is a new model.

**Comment by cobra** [comment]
it's in the repo as well, see 945d07b. Looks really nice.

**Comment by mindforger** [comment]
well i'll leave it open, as my issue still partially persists 

the RS function is nive to have yet and that makes me happy, but still the immersion for me is broken by HV cables beeing way to close to the switching gear, which is way to small to safely break medium and high voltages ... as i linked in the image there needs to be at least a 2 block space solution including the lever imho to ensure a "safe" look and feel

i do not know what Blu and Damien discussed about that but i still want to have at least an adequate answer to the "why not" or a simple close with "will not change" .. i would accept both

**Comment by BluSunrize** [comment]
Yeah, I was being entirely honest. I like the idea of flicking a massive switch for high voltage. Ever seen Young Frankenstein? xD
It's not worksafe, it's not realistic, and I'm sorry that bugs you, but I like it a lot ^^

**Comment by cobra** [comment]
The good thing is that IE is open source and has an API, so it shouldn't be too hard to put some alternative larger switches into addon. Mod the mods!

**Comment by mindforger** [comment]
meh i am unskilled at things like rendering, i could never pull up such a thing like Damien and Blu :p

**Comment by UnwrittenFun** [comment]
if only we knew somebody who has made an IE addon.. hmm.. nope I can't think of anyone
