### ISSUE TITLE
Redstone wire connection bug?

### ISSUE THREAD

**Issue by sbtaku11** [BluSunrize/ImmersiveEngineering#3400]
After the restart, I can't attach redstone wire to redstone wire connector attached before the restart.

**Comment by malte0811** [comment]
What version of IE and, in this case even more importantly, what other mods are you using?

**Comment by sbtaku11** [comment]
ImmersiveEngineering-0.12-89

Baubles-1.12-1.5.2.jar
BetterFps-1.4.8.jar
BiomesOPlenty-1.12.2-7.0.1.2425-universal.jar
CTM-MC1.12.2-0.3.3.22.jar
Chameleon-1.12-4.1.3.jar
Chisel-MC1.12.2-0.2.1.35.jar
CoFHCore-1.12.2-4.6.2.25-universal.jar
CoFHWorld-1.12.2-1.3.0.6-universal.jar
CodeChickenLib-1.12.2-3.2.2.353-universal.jar
ComputerCraft1.80pr1.jar
ExpandedEquivalence-1.12.2-11b.jar
FTBLib-5.4.1.84.jar
FTBUtilities-5.3.0.81.jar
FastLeafDecay-v14.jar
Forgelin-1.8.2.jar
HammerCore-1.12.2-2.0.4.2.jar
Hwyla-1.8.26-B41_1.12.2.jar
immersivetech-1.12-1.3.10.jar
InventoryTweaks-1.64+dev.146.jar
IronBackpacks-1.12.2-3.0.8-12.jar
JustEnoughResources-1.12.2-0.8.9.48.jar
Mantle-1.12-1.3.3.39.jar
Mekanism-1.12.2-9.4.13.349.jar
MekanismGenerators-1.12.2-9.4.13.349.jar
MouseTweaks-2.9-mc1.12.2.jar
MrTJPCore-1.12.2-2.1.3.35-universal.jar
NotEnoughItems-1.12.2-2.4.2.240-universal.jar
OptiFine_1.12.2_HD_U_E3.jar
ProjectE-1.12.2-PE1.4.0.jar
RedstoneFlux-1.12-2.1.0.6-universal.jar
SimplyJetpacks2-1.12.2-2.2.10.63.jar
StorageDrawers-1.12.2-5.3.8.jar
TConstruct-1.12.2-2.12.0.115.jar
Thaumcraft-1.12.2-6.1.BETA26.jar
ThaumicJEI-1.12.2-1.5.5-23.jar
ThermalCultivation-1.12.2-0.3.2.11-universal.jar
ThermalDynamics-1.12.2-2.5.4.18-universal.jar
ThermalExpansion-1.12.2-5.5.3.41-universal.jar
ThermalFoundation-1.12.2-2.6.2.26-universal.jar
ThermalInnovation-1.12.2-0.3.2.11-universal.jar
TinkerToolLeveling-1.12.2-1.1.0.jar
TinkersComplement-1.12.2-0.3.0.jar
UniDict-1.12.2-2.9.2.jar
VeinMiner-1.12-0.38.2.647+b31535a.jar
WanionLib-1.12.2-2.2.jar
Wawla-1.12.2-2.5.269.jar
ancientwarfare-1.12.2-2.7.0.574.jar
bdlib-1.14.3.12-mc1.12.2.jar
buildcraft-all-7.99.21.jar
exnihilocreatio-1.12.2-0.3.7.jar
extrautils2-1.12-1.9.8.jar
forestry_1.12.2-5.8.2.382.jar
generators-0.9.20.12-mc1.12.2.jar
gravestone-1.10.2.jar
ironchest-1.12.2-7.0.59.842.jar
jei_1.12.2-4.14.4.264.jar
jeibees-0.9.0.5-mc1.12.2.jar
jeiintegration_1.12.2-1.5.1.36.jar
railcraft
railcraft-12.0.0-beta-4.jar
refinedstorage-1.6.12.jar
torchmaster_1.12.2-1.7.1.74.jar

**Comment by bookerthegeek** [comment]
Is this a visual only bug, as in is it still connected but just not visually so?

Have you tried with optifine?

**Comment by malte0811** [comment]
1. That should probably be "without Optifine", not "with Optifine".
2. My guess would be Immersive Tech, they caused a problem like this before and while the bug is fixed on GitHub, the last version on CurseForge that I know of still has the bug.

**Comment by sbtaku11** [comment]
When I uninstall Immersive Tech, I can attach redstone wire.
Thank you!
