### ISSUE TITLE
Diagonal Downward Conveyor Insertion

### ISSUE THREAD

**Issue by TeamSpen210** [BluSunrize/ImmersiveEngineering#3403]
### Description of the issue:
Diagonal conveyors only occupy the block they're in, so devices that should logically be able to insert onto them from diagonally above cannot, whilst adjacent devices are able to insert items "through" the surface of the conveyor. This doesn't affect upward conveyors since they can detect and insert into diagonal blocks. This affects IE machines as well, though they could be special-cased of course.

![conv_bug](https://user-images.githubusercontent.com/8453732/53689677-8cf14b80-3da6-11e9-8f2e-c3ad724f6daf.png)

My suggested fix is to make these downward conveyors spawn a air-like proxy block above themselves if the space is clear, which relays the `insertItem()` call down to the conveyor below. If a block is placed above, the conveyor would effectively be blocked by that. Direct insertion would then be disallowed on the side of the actual conveyor block. If this seems reasonable I'll be submitting a PR to implement this.

### Versions & Modlist
IE: 89 / 011c70c8929dc965645dd073df451ea58d29ae60
Forge: 14.23.5.2768

**Comment by TeamSpen210** [comment]
The second problem seems to stem from the fact that conveyors ignore facing when allowing inputs.

**Comment by BluSunrize** [comment]
Nope. I'm not gonna have them have a fake block above.
The idea came up years ago during their initial implementation, but I decided against it then because it made them a lot more needlessly complex than they need to be.
