### ISSUE TITLE
Garden Cloche / Cardboard Box Disappearing

### ISSUE THREAD

**Issue by ke5hxf** [BluSunrize/ImmersiveEngineering#3406]
### Before reporting:

**### SEARCH: revealed nothing comparative**

### Description of the issue:

**### Enigmatica2:Expert(latest(yeah, i read on down and I can hear you cringing at the read of 'latest' but you come up with something better than twitch and we will talk)) Placed Garden Cloche in world. Supplied with all items: (dirt, potato, power, water and bone meal.) Placed Cardboard Box over Cloche, everything went missing(box, cloche, and mats)**

### Crashlog:
If your Minecraft instance has crashed, a file will have been generated in the folder `crash-reports` of your minecraft folder. To understand what has happened, we need to know the content of that file. But please don't just put it directly in your report (that makes it hard to read), upload it to a site like [pastebin](http://pastebin.com) or [gist](http://gist.github.com) and put a link in the actuall bug report.

### Lastly (you may delete this from the report itself)
Please, for the love of all that is voxelbased, **read the contribution guidelines. They are linked to the right in the message box.**

### **My voxelbased love inspired me to actually read that guideline. Done.**

Thank you for reporting issues, without people reporting them, they wouldn't get fixed. You're helping contribute to this mod and that is much appreciated <3

### **Lovin the hard work, keep it the hell up!!!**

**Comment by ke5hxf** [comment]
Sorry, forgot to mention, this issue has been also reported to Mekanism.

**Comment by BluSunrize** [comment]
Yep. And that is why moving TileEntities is a bad idea and shouldn't be a thing in Minecraft.

It's a multiblock. You can't just move it. Don't try it, it just breaks. This is not a bug on our side, nor is it really on Mekanism unless you want to count the fact that they allow moving Tiles in the first place.

**Comment by thiakil** [comment]
@BluSunrize do you happen to have a list of your blocks' ResourceLocations that do (or may) contain a multiblock TE?

I intend on adding them to the [blacklist](https://github.com/aidancbrady/Mekanism/blob/0315f347c1b3a207c75e796192ebe8fc3ff029b7/src/main/java/mekanism/common/Mekanism.java#L907)

**Comment by BluSunrize** [comment]
No, I don't have such a list, but off the top of my head:
`
immersiveengineering:wooden_device0
immersiveengineering:wooden_device1
immersiveengineering:connector
immersiveengineering:metal_device0
immersiveengineering:metal_device1
immersiveengineering:metal_multiblock
`

Apart from the `metal_multiblock`, some of them only have certain metadatas contain multiblocks, but I don't know those by heart.

**Comment by thiakil** [comment]
Awesome, thanks! I'll just use a wildcard on all of them for now, if someone complains they can find us the list of meta.
