### ISSUE TITLE
Arc Furnace Recycling / Metal Press allow duplication of metals

### ISSUE THREAD

**Issue by SiliconEnt** [BluSunrize/ImmersiveEngineering#3407]
### Description of the issue:
Recycling many items in the Arc Furnace allows the duplication of base materials. This affects all recyclable items that have raw wires or wire coils anywhere in their production chain.

The output from the Arc Furnace recycling recipes seems to be based on the crafting recipe: one wire per ingot/plate. However, the Metal Press produces two wires per ingot. This allows resource duplication as Arc Furnace recycling produces twice the metal used to create a wire. 

I am aware of issue #3281; that issue only affected the insulated coils. This issue affects all wire coils and other wire products that can be recycled.

This is the basic pathway for duplication. Other paths exist, depending on what is recycled and which metal(s) are produced, but they simply add more steps to this one.

* Metal Press: 2 ingots become 4 wires.
* Assembler: 4 wires plus 1 stick become 4 coils.
* Arc Furnace Recycling: 4 coils become 4 ingots.

Through the whole process, two ingots become 4. The exact amounts vary when recycling HV or Redstone wire coils, as producing half a nugget is impossible, but duplication still occurs.

Variants on the process exist to duplicate:
* Copper, through the LV Wire Coil, Insulated LV Wire Coil, Copper Coil Block, and *any recyclable item* that uses Copper Wire *anywhere* in its production chain.
* Electrum, through the MV Wire Coil, Insulated MV Wire Coil, Electrum Coil Block, and *any recyclable item* that uses Electrum Wire *anywhere* in its production chain.
* Steel, through the Steel Cable Coil, HV Wire Coil, HV Coil Block, and *any recyclable item* that uses Steel Wire *anywhere* in its production chain.
* Aluminum, through the Redstone Wire Coil HV Wire Coil, HV Coil Block, and *any recyclable item* that uses Steel Wire *anywhere* in its production chain.

### Crashlog:
No crash occurs.

### Versions & Modlist
Forge 14.23.5.2815
Immersive Engineering 0.12 - 89
JEI 4.15.0.268

No other mods were installed.

**Comment by TeamSpen210** [comment]
Logically the recyling should just return half an ingot per wire, since that's the amount of metal there. Presumably the wirecutter approach wastes half of it when doing it that way.

**Comment by SiliconEnt** [comment]
Precisely! The cost of a wire drops to half an ingot long before you have an Arc Furnace, so the Arc Furnace should reflect that cost. 

In my new pack, I've decided to disable Arc Furnace recycling in the config and add other recycling methods using the same numbers you suggest. The dynamic armor recycling is an acceptable loss. It's kind of a shame the Crafttweaker integration doesn't allow for multiple outputs; I'd add recycling with that. I understand why it doesn't, though – patching this issue would be the only use case!
