### ISSUE TITLE
[Suggestion] Revolver mob attraction improvements

### ISSUE THREAD

**Issue by Uub112** [BluSunrize/ImmersiveEngineering#3412]
I've been having quite some fun messing with the revolver noise mechanic so far, and I have some thoughts I'd like to share about it:

1: While it's quite nice for drawing aggro from other people and reminding you to not bite off more than you can chew, it is a little tiring to shoot in a cave and have a random enderman that you angered from another nearby cave teleport onto you with little warning, never mind trying to use the revolver in the nether or the end, where you'll end up with a overwhelming mass of speedy hard-hitters on you in seconds.
A blacklist for mob aggression might be nice, so that mobs like endermen (which you can't even hit) won't make it more dangerous to use than to be used on.

2: As for the sound mechanic itself, instead of directly making the mob target the shooter, maybe it could make mobs move toward the shooter's location, like the way spiders move toward the direction of a projectile that hits them outside of their detection range? It would be interesting tactics-wise, so that it still discourages shooting and staying in the same location, but maybe could be used to misdirect mobs if you can escape before being detected.

By the way, thanks for developing and upkeeping this great mod, hope to see it stay around for a long time!

**Comment by GalacticRuler** [comment]
months late but holy hell. THIS.

went to the end. Shot the gun, not knowing it did this.


...I regretted that. Ender-swarm aside, it's also paired with an ear-rape of about 20 of them all doing the same sound effect which is....grating, to say the least.
