### ISSUE TITLE
MC 1.12.2 Assembler not working with Mystical Agriculture PO3

### ISSUE THREAD

**Issue by Artemis-E** [BluSunrize/ImmersiveEngineering#3413]
Putting Mystical agriculture recipe in show properly in crafting grid including the output. However I cannot get it to craft.  
I've seen a similar report from Nov 2017, but it was closed so I made a new thread.

Forge 14.23.5.2808
IE 0.12-88
Mystical Agriculture 1.12.2-1.7.1
Mystical Agradditions 1.12.2-1.3.1
Mystical Agriculture tiered crystals matc-1.0.1-hotfix

![image](https://user-images.githubusercontent.com/18541534/54080376-28f5e800-42bc-11e9-9a9f-c70e4fb1784e.png)

**Comment by CharCharthemonkey** [comment]
turn on recursive crafting @Artemis-E
