### ISSUE TITLE
Wooden Storage Crate & Reinforced Crate Dissapearing Content

### ISSUE THREAD

**Issue by CastielAngelow** [BluSunrize/ImmersiveEngineering#3415]
### Description of the issue:
Wooden Storage Crate & Reinforced Storage Crate too
Filling storage crate and breaking it in survival, then changing gamemode will result in vaporizing of Storage Crate's contents. It happens when you are having Crate in inventory while changing gamemodes and also while breaking Crate in survival, advanced item informations showing zero NBT Data so its basically behaving like "empty" though there shall be contents.

### Crashlog:
No Crashlog generated but got this inside .log file:
https://pastebin.com/FYfu6hD5

### Versions & Modlist
Forge 1.12.2. - .2768; Immersive Engineering 0.12.89.jar
Also using SpongeForge latest build

**Comment by frakier** [comment]
Seen that problem twice. Went and checked the change log but did not have the leak problems errors.
forge-1.12.2-14.23.5.2808
ImmersiveEngineering-0.12-89
I'll experiment and report back

**Comment by mindforger** [comment]
That is an issue of forge, nothing that can be done much. If i remember right, it is an issue with updating inventorys.

**Comment by bookerthegeek** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/4580

Thats the issue.
