### ISSUE TITLE
Render boundaries are off

### ISSUE THREAD

**Issue by K-4U** [BluSunrize/ImmersiveEngineering#342]
As mentioned in title. I just had an entire waterwheel disappear on me:

http://ss.k-4u.nl/2015-08-20_14-52-29
Looking down a little:
http://ss.k-4u.nl/2015-08-20_14-52-32

**Comment by mindforger** [comment]
http://bt.industrial-craft.net/view.php?id=1401 i think this is a rendering issue that can not be resolved easily, even thunderdark mentioned it as "won't fix" :)

**Comment by K-4U** [comment]
It's quite easy to fix, i did it in Hydraulicraft too ;)

**Comment by BluSunrize** [comment]
Then tell me how? I'm too lazy to search your entire source xD

**Comment by BluSunrize** [comment]
closed because this is a frustrum error not a RenderBoundingBox thing.
