### ISSUE TITLE
[1.12.2][0.12-89]CraftTweaker removing one bullet recipe from a blueprint results all bullets removed

### ISSUE THREAD

**Issue by lordfriend** [BluSunrize/ImmersiveEngineering#3422]
I'm using CraftTweaker to change the recipe for DragonsBreath with the following lines of code.

```
// remove DragonBreath Bullet recipe
var  dragonsbreath = <immersiveengineering:bullet:2>.withTag({bullet: "dragonsbreath"});
mods.immersiveengineering.Blueprint.removeRecipe(dragonsbreath);
// add new recipe for DragonBreath Bullet
mods.immersiveengineering.Blueprint.addRecipe("specialBullet", <immersiveengineering:bullet:2>.withTag({bullet: "dragonsbreath"}), [
    <immersiveengineering:bullet:1>, <grimoireofgaia:misc_soul_fire>*64, <grimoireofgaia:misc_soul_fiery>*32, <ore:dustAluminum>*64
]);
```

This results all bullets being removed and only the new Dragonsbreath left. 

I find all bullets are the same id differentiated with NBT tag. but this IItemStack in removeRecipe function seems to ignore NBT tag. so it's unable to remove specific bullet recipe without touch others.

**Comment by BluSunrize** [comment]
Oh whoops. No NBT specific comparisson. My bad.
Will be fixed for next release.
