### ISSUE TITLE
[Suggestion] [1.12.2] Bottling Machine (water bottles?)

### ISSUE THREAD

**Issue by FireheartIndustries** [BluSunrize/ImmersiveEngineering#3424]
Either I'm doing something very wrong, or something changed along the way, and I missed it.

Why does the bottling machine fill a glass bottle with every single vanilla potion, but wont fill one with plain old, simple, water? It used to work with water, and I read in one of the other issues that the FluidContainerRegistry is no longer a thing. That makes sense for why it wouldn't be easy for a lot of mod fluids, but was it just an oversight, or was it a choice to not have the bottling machine fill water bottles?

**Comment by gooseapple5** [comment]
Yeah, I have this same issue, I'm trying to make an automatic purified water system for tough as nails, but it won't fill a water bottle with water. Which is weird because the name of the machine is bottler and it can fill a water bucket though not a bottle. Would be a good addition.

**Comment by mindforger** [comment]
Because bottle being generic containers was removed by forge and patching them to be it again is a pain.
Isn't there a crafttweaker integration?

**Comment by FireheartIndustries** [comment]
There _might_ be a crafttweaker integration, but I don't know. I've been trying to figure that out, but nobdy else seems to be trying to do this for some reason.

I was trying to do the same exact thing that gooseapple5 was trying to do. Fill bottles with water, run them through a furnace, and have purified water bottles from Tough as Nails. The one issue I was running into was the "Bottling Machine" wasn't "Bottling" water.

I have no experience adding recipes with crafttweaker, so if anyone knows how, can we get some help here?

**Comment by mindforger** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/api/crafting/BottlingMachineRecipe.java#L47

this looks promising, ty to drop that into the .zs

**Comment by BluSunrize** [comment]
Even better, take a look at the Craft Tweaker documentation.
There is an entire wiki, which also documents all the IE machines:

https://crafttweaker.readthedocs.io/en/latest/#Mods/Immersive_Engineering/CraftTweaker_Support/Bottling_Machine/

**Comment by mindforger** [comment]
i was not entirely sure if it is kept up to date so i switched over to check your api instead :P
