### ISSUE TITLE
[1.12.2] Crash with Forge 2815

### ISSUE THREAD

**Issue by Tiviacz1337** [BluSunrize/ImmersiveEngineering#3425]
### Description of the issue:
Game crashes

### Crashlog:
https://pastebin.com/ue9H7H9y

### Versions & Modlist
IE: ImmersiveEngineering 0.12 - 89
Forge: 14.23.5.2815

**Comment by malte0811** [comment]
When and from where did you download IE? The original file uploaded to CurseForge as 0.12-89 had this issue, but it was replaced with a working file within a few hours IIRC.

**Comment by Tiviacz1337** [comment]
I always download mods from CurseForge and I really like updates. Probably I have downloaded file too early and that's why it didn't work. I have re-downloaded file and now it works as it should! Thanks for info :)
