### ISSUE TITLE
[1.12] Cannot put potions in fluid router

### ISSUE THREAD

**Issue by Alex33212** [BluSunrize/ImmersiveEngineering#3429]
Forge: 14.23.5.2814
IE: 0.12-89

I can't seem to put potions via bottle in the fluid router. Buckets of fluid work fine, but potion bottles simply refuse to work.

**Comment by BluSunrize** [comment]
Bottles aren't fluid containers, which is why the router doesn't recognize them. Not a whole lot we can do about that, except for hardcoding the router to explicitely recognize potions. Bucket is a lot better approach.
