### ISSUE TITLE
NPE with Arc Furnace

### ISSUE THREAD

**Issue by angelnc1989** [BluSunrize/ImmersiveEngineering#343]
http://pastebin.com/vgZaSWdH

I put some Constantan Grit into the Arc Furnace. A few seconds later the server crashed.
I had no problem creating Steel in the Arc Furnace.

**Comment by theunkn0wn1** [comment]
known issue. #327

**Comment by angelnc1989** [comment]
Oh. I was only looking in open issues. My bad.

**Comment by theunkn0wn1** [comment]
no problem, next time check freshly closed tickets before posting a new issue, as you might not be the only one with that particular issue.

Happy hunting!
