### ISSUE TITLE
[Suggestion] Circuit breaker/fuse box (Avoid wire burnout)

### ISSUE THREAD

**Issue by FireheartIndustries** [BluSunrize/ImmersiveEngineering#3432]
Sitting here playing around with supplying power to a bunch of machines, and constantly burning wires out when demands suddenly jump is getting to be annoying since I'm losing wires frequently, and I just thought of something to help people save wires.

A circuit breaker like we have in houses. Something with a lever similar to the switch that shuts itself off right before the burnout threshold is reached so you don't have to completely rewire your system just because you tried to pull too much power.

Alternatively, a fuse box with a similar functionality, except you need to replace burnt out fuses that you would have to craft as well. This still results in having to replace a lost component, but at least this would be in a single place instead of having to search for the gap in your power line, especially if they are hidden behind walls.

**Comment by Paul17041993** [comment]
You can technically do a similar thing with the current transformer, a comparator circuit and a relay, the CT's emit level 15 when you're at the limit of that wire.

But I definitely agree that we should have a simplified circuit protector of sorts, a breaker being the most suitable and, mechanically, only consists of a simple coil (for that tier) and spring-held iron. Once the current (and respected magnetic force) hits a certain power, it overcomes the spring lock and breaks the circuit.

**Comment by BluSunrize** [comment]
Not doing circuit breakers, because that negates the concept of wire burnout too much.
Having fuses that are consumed is better, but the overall aspect of dealing with the wirenetwork again on that level makes me not want to do it.
