### ISSUE TITLE
[suggestion] config option for the silo

### ISSUE THREAD

**Issue by WarlordWossman** [BluSunrize/ImmersiveEngineering#3433]
Would be great to have a config option for the silo, with shulkerboxes / crates a single chest can hold 46656 items which is already more than the silo multiblock.
In general a config for the amount of items it can hold would help a lot when it comes to modpack developement!

**Comment by thewho333** [comment]
+1 It would also be nice it you could right klick input/output items like barrels

**Comment by PrincessRTFM** [comment]
I'd love more storage in it, but I feel like it shouldn't allow manual interaction. I don't make a silo to let myself stash a lot of cobble or whatever, I make it to act as a buffer for automated work lines. I don't ever try to pull things out of them by hand, although being able to put things _in_ by hand (at the top, of course) might be nice in case I end up with some of whatever it is in my inventory that I'd like to drop into the line buffer.
