### ISSUE TITLE
[ Question ] Craftweaker

### ISSUE THREAD

**Issue by HurtsAsHell** [BluSunrize/ImmersiveEngineering#3434]
#### Fermenter
I found this code `mods.immersiveengineering.Fermenter.addRecipe(IItemStack output, ILiquidStack fluid, IIngredient input, int energy);` but i want to add only a liquid output. 
I tried to use `<minecraft:air>` but the game told me that i can't use a null output.
How can i add a crafting like the original crafting of Fermenter ? [ Sugar = Ethanol (without item output) ]

**Comment by BluSunrize** [comment]
Try using `null` instead of `<minecraft:air>` and see if that works.

**Comment by HurtsAsHell** [comment]
okay, i try now

**Comment by HurtsAsHell** [comment]
THANKS, it works but i suggest to add this info to the Craftweaker wiki.

**Comment by BluSunrize** [comment]
I don't maintain that wiki, you should approach whoever does =P
