### ISSUE TITLE
[suggestion] conveyor belt

### ISSUE THREAD

**Issue by Flexz9** [BluSunrize/ImmersiveEngineering#3435]
Conveyor belts will overflow any inventory and I'm not finding to good of a use for them.
It would be a lot more helpful and I also think friendly on a server to use a Fortresscraft style of conveyer belts, render the items on the belt, not move the entity on top (while you could still allow this mechanic for player/mobs standing on top, and taking items that fall on the belt inside and render the item)

For items you would pass each item trough to the next block, making a queue for each belt you place of 1 size. Belts will stop moving if it can not put the item into the next belt/inventory. stopping to overlow any items and making them a lot more usefull as I do love the looks of them!

**Comment by BluSunrize** [comment]
Nah. IE's conveyors work fine as they do. I'm not changing the entire damn system of them =)

**Comment by PrincessRTFM** [comment]
It's part of the challenge and the fun!
