### ISSUE TITLE
[1.12.2] Enigmatica2 crash

### ISSUE THREAD

**Issue by j13li78** [BluSunrize/ImmersiveEngineering#3436]
I was just searching in my me system and then i randomly crashed in the crash report i saw different entries with immersive engineering so i assume that it is due to immersive engineering.
https://hastebin.com/sefizaqiye.makefile my minercaft just crashed randomly

Version: ImmersiveEngineering-0.12-89.jar ImmersiveEngineering-core-0.12-89.jar

**Comment by BluSunrize** [comment]
Update your Java. You are outdated by 3 1/2 years.
