### ISSUE TITLE
[suggestion] enable IE metal blocks to serve as beacon bases

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#3438]
as title. :)
Currently they don't work as beacon bases, and arguably they should to keep in line with the general consensus that metal/gem blocks can serve as beacon bases.
Idk what to say here. A little fun fact: Fourteen new species of dancing frogs were discovered in 2014, raising the global number of known dancing-frog species to 24.

**Comment by FreneticScribbler** [comment]
Can we get this updated for https://github.com/MinecraftForge/MinecraftForge/pull/6948 please? :)

EDIT: Damn I thought that was for 1.15 not 1.16...point stands for 1.16, but looks like I might be SOL in 1.15. Three versions at once sure is confusing!

**Comment by Shados** [comment]
The 1.15 change that broke this is actually MinecraftForge/MinecraftForge#6438.

**Comment by BluSunrize** [comment]
I was aware this was broken again? Sorry I generally don't look at closed issues. If Beacons currently don't work with IE blocks, please open a new issue!
