### ISSUE TITLE
[1.12.2] harming potion and phial cartridge

### ISSUE THREAD

**Issue by Waytyx** [BluSunrize/ImmersiveEngineering#3439]
Hi i have 2 problems.

First i think that Mixer recipes for making harming potion I and II are broken, because i can't make harming potion from any kind of poison even if there is recipe for it. Only way to make harming potion is from healing potion I or II. The fermented eye which is needed for making harming potion will just have that progression bar and nothing will happens.

My second problem isnt that far away. Its about phial cartridge i dont know if it is wanted feature or bug. When i want combine empty phial cartrige and harming or poison potion(i didnt test others) i can do it only by me that means only way to crafted them is crafting one by one in crafting table and for every cartridge you have to put there another potion, you can't automate this in assembler. When you try it, it will just show what it will output of recipe but nothing will be crafted, even with other autocrafters from others mods can't make it. i think it can't be crafted automatically because there isnt visible recipe in JEI for these filled phial cartridges.

I hope you understand my weird explanation.
 
Minecraft: 1.12.2
IE: 0.12-88
Forge:1.12.2-14.23.5.2768
jei_1.12.2-4.13.1.225

everything was tested on clear forge IE and JEI

**Comment by TeamSpen210** [comment]
It'd make more sense to be able to do this in the bottling machine I think. Or potentially make the bullet item a fluid container, so any device can "fill" them with potion liquid.
