### ISSUE TITLE
Graphite Electrode not craftable

### ISSUE THREAD

**Issue by pingwel** [BluSunrize/ImmersiveEngineering#344]
Hey there for some reason im not able to craft the Electrodes ? I have the blueprint for it, i have the 4 HOP Graphite Ingots i need but still nothing comes out of that ? am i doing something wrong here ?

**Comment by theunkn0wn1** [comment]
Can we get a screenshot of the workbench please?
Also IE version helps

=========
Attempted to reproduce with [IE version 0.5.3](https://github.com/BluSunrize/ImmersiveEngineering/commit/5f393fbc533608af004833125e3a27df3a18e581)
Issue did not occur

Steps taken to reproduce:
[1] placed workbench
[2] placed graphite electrode blueprint in workbench
[3] placed (4x) HOP graphite in crafting slot 1
[4] removed output electrode
result: no error found, graphite electrode crafted successfully

**Comment by pingwel** [comment]
Playing on FTB Infinity
Its version ImmersiveEngineering-0.5.1

Sceenshot:
http://imgur.com/mY9XrXA

**Comment by theunkn0wn1** [comment]
OK, i am also running FTB Infinity (version 1.9.0 with a custom botania build)
Wierd, it looks like you have it correct, got the right type of graphite and all. 

Not seeing an obvious error here. 
![image](https://cloud.githubusercontent.com/assets/3110986/9394309/940f61ae-473c-11e5-862a-e7b9544a6692.png)
The above is my setup
Can you try updating to IE 0.5.3 and try again?

**Comment by pingwel** [comment]
no sry its on a server im playing (not my own)

**Comment by theunkn0wn1** [comment]
ok, can you repo this in singleplayer?

**Comment by pingwel** [comment]
i already trying in a singleplayer. still not working

**Comment by theunkn0wn1** [comment]
IE 0.5.2 has 'fixed broken Blueprint crafting'
Please update your IE install

**Comment by pingwel** [comment]
am i able to update my version without updating the servers IE ? because im pretty sure i cant play on the server then ?

**Comment by theunkn0wn1** [comment]
Highly unlikely, As i understand the server needs updating too. Poke a server admin and explain that the build of IE on the server (and the backs default) contains a mod-breaking bug. The issue you are encountering can only be 'fixed' if the server has the update. the client will need the update too as of other changes implemented.

**Comment by pingwel** [comment]
cant really update the server its a public one and kinda hard to update when there are so many people on it all the time. and if they all have to update the game also their gonna leave

**Comment by theunkn0wn1** [comment]
I understand, but it is simply beyond BluSunrise's (the mod author) control. This issue has long been resolved and i am afraid it is a duplicate. It is beyond our ability to influence exactly which version of IE any given server, excluding Forgecraft, is running. That is down to the server operators.

If you can, contact an Op on the server and use the manual workaround. you know, give the crafting ingredients to the Op whom destroys them and returns you the electrode output.

**Comment by pingwel** [comment]
okay :) but thanks for the really quick reply really glad that i got respond so fast

**Comment by theunkn0wn1** [comment]
No problem. Happy (to attempt) to be of service =3

**Comment by BluSunrize** [comment]
Closed, thanks for hte support unknown ^^

**Comment by theunkn0wn1** [comment]
All in due course. I know how you hate duplicates.... :walking:
