### ISSUE TITLE
[1.12] Fluid Pipe Visual Bug

### ISSUE THREAD

**Issue by JakeOTwitch** [BluSunrize/ImmersiveEngineering#3443]
### Description of the issue:

Visual bug regarding the Fluid Pipe. When right clicking the pipe with a hammer to disable an input the pipe still shows as visibly connected.

### Versions & Modlist

Version 0.12-89

**Comment by JakeOTwitch** [comment]
Upon further testing, it appears the texture updates when the chunks are unloaded and reloaded.

**Comment by Paul17041993** [comment]
Can confirm this as well, while pipe-pipe separation works normally, pipe-tank and pipe-machine does not. It seems to be a very specific client render desync (the collider however does visually update).
