### ISSUE TITLE
[1.12][0.12-89] EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by FenixFyreX** [BluSunrize/ImmersiveEngineering#3448]
### Description of the issue:
Has happened four times thus far; I'm playing as normal and go to search in an AE2 terminal (or JEI), and the game crashes. Usually using the `@` symbol. The latest time I tried to search for `@chemical` and when I typed the first half of that, the game just closed out immediately.

I should mention, every time, this 'problematic frame' has been the same. It always 'points' to the immersive engineering addQuadsForGroup() shader stuff.

### Crashlog:
[gist of crash.log](https://gist.github.com/FenixFyreX/34c63d20240260d5ac32ae44f0e522fd)

### Versions & Modlist
IE: 0.12-89
Forge: 14.23.5.2781
Modpack is Enigmatica 2: Expert with a couple extra mods installed, listed in the crash log.

**Comment by malte0811** [comment]
Could you upload `MultiMC\instances\Enigmatica2E\minecraft\hs_err_pid11140.log`? That file should contain a lot of useful information on the crash, which is even more important than usual since this isn't a standard MC crash.

**Comment by FenixFyreX** [comment]
[link to hs_err_pid11140.log](https://gist.github.com/FenixFyreX/78a7d547a818a726db758d512b26414e)

**Comment by mindforger** [comment]
Don't know if actually relevant, but there are a ton of circular model references, this looks like a massively broken resource pack.

**Comment by FenixFyreX** [comment]
I am not using any resource or data packs.

**Comment by T0MSSM0T** [comment]
I have had a similar problem, maybe the exact same. typing in jei no AE system and I get this:
[hs_err_pid5008.log](https://github.com/BluSunrize/ImmersiveEngineering/files/3096225/hs_err_pid5008.log)

**Comment by adrianpavone** [comment]
Same issue, crashed twice so far with the exact same method call of addQuadsForGroup. Playing Enigmatica 2: Expert modpack, crash happened both with and without a resource pack (BDCraft) being active.

Both hs_err logs attached.

[hs_err_pid19444.log](https://github.com/BluSunrize/ImmersiveEngineering/files/3098069/hs_err_pid19444.log)
[hs_err_pid5044.log](https://github.com/BluSunrize/ImmersiveEngineering/files/3098070/hs_err_pid5044.log)

**Comment by pennyvise1** [comment]
Same, happens when i open the AE2 terminal

[hs_err_pid6368.log](https://github.com/BluSunrize/ImmersiveEngineering/files/3104349/hs_err_pid6368.log)
[hs_err_pid12508.log](https://github.com/BluSunrize/ImmersiveEngineering/files/3104350/hs_err_pid12508.log)
[hs_err_pid20464.log](https://github.com/BluSunrize/ImmersiveEngineering/files/3104351/hs_err_pid20464.log)
[hs_err_pid4176.log](https://github.com/BluSunrize/ImmersiveEngineering/files/3104352/hs_err_pid4176.log)

seems to have started with the latest java update

**Comment by themadjem** [comment]
I had this happen a few days ago while searching "@mm" in JEI, and just now when the IE workbench came into my view.

[hs_err_pid10440.log](https://github.com/BluSunrize/ImmersiveEngineering/files/3114556/hs_err_pid10440.log)

Enigmatica 2: Expert v1.62
IE 0.12-89
Forge 14.23.5.2781

**Comment by Antagonistic** [comment]
If it helps, let me add mine to the pile
[hs_err_pid22560.log](https://github.com/BluSunrize/ImmersiveEngineering/files/3126573/hs_err_pid22560.log)

**Comment by Antagonistic** [comment]
It may or may not be related, but I'm also getting a situation where my chisel blocks are invisible until I put down or pick up a torch, and enderio similiarily doesn't update changes till lighting changes.

**Comment by mindforger** [comment]
i am spotting foamfix in every trace here as far as i see, try removing it and come back if the issuue is gone

**Comment by Diggsey** [comment]
I have the same issue.
[hs_err_pid8840.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4396435/hs_err_pid8840.txt)
