### ISSUE TITLE
Breaker switch base glows in the dark

### ISSUE THREAD

**Issue by cobra** [BluSunrize/ImmersiveEngineering#345]
The base of the breaker switch seems to ignore light levels and stays lit during the night, resulting in a glow-in-the-dark effect without emitting light itself. Fast/fany graphics and smooth lighting settings don't affect this. Happens outside and in fully enclosed spaces. [Example screenshot](http://i.imgur.com/3M4w3eY.png).
No optifine, no fastcraft, occurs in my dev environment as well as the official 0.5.3.2 version.

**Comment by BluSunrize** [comment]
Yeah, I know. It's supposed to get a new model anyway. Renderign will be fixed when it does. But the texture isn't finished yet, so I'm waiting on that.

**Comment by BluSunrize** [comment]
Should be fixed now
