### ISSUE TITLE
[0.11-63] Redstone Breaker Causing Extreme Performance Issues

### ISSUE THREAD

**Issue by starfoth** [BluSunrize/ImmersiveEngineering#3450]
Unexpectedly, redstone breakers will cause extreme performance issues when placed in some areas. All powered items will flicker on and off and the framerate will drop to less than one usually forcing a task manager exit from the game as the game is unable to process inputs such as breaking the problematic breaker [or sometimes even reaching it as placing a redstone breaker will not always cause issues immediately]. No problems occur when not using any redstone breakers.
Specifically, I was wiring up a village with electricity. On the outside, I would place a daylight sensor above a redstone breaker for the outside lights, a redstone breaker with a breaker switch to shut off power to the building entirely, and a redstone breaker with a breaker switch to shut off lighting inside the building. Sometimes when this issue occurs, I am able to break the redstone breaker because I made a habit of placing those in last so I am nearby to break them and the issue stops so I know that it is them causing it. 
**I have a save available with a problematic redstone breaker. I can load into the save with only immersive engineering running and the problem still persists. I cannot break it due to the lag.**
I have an extensive modlist but have not used any of the mods and am just experimenting with immersive engineering in a superflat world with a nearby village.

IE: ImmersiveEngineering-0.11-63.jar
Forge: forge-13.20.1.2414
Modlist; https://pastebin.com/aPFAXWzR **DISABLING ALL MODS AND ONLY RUNNING IMMERSIVE ENGINEERING STILL CAUSES THE ISSUE**
Note that the only mod content accessed is a single house furnished with Bibliocraft and MrCrayfish's furniture mod. Even with the other 2 mod's objects removed the problem persists.

**Comment by starfoth** [comment]
[New World - Copy.zip](https://github.com/BluSunrize/ImmersiveEngineering/files/3109951/New.World.-.Copy.zip)
Here is a copy of the world loaded after all mods besides immersive engineering were disabled. Lag still persists and the redstone breaker that is causing the issue is nearby and I cannot break it. This issue occurred several times before but I was able to break the redstone breaker or find them with enough effort.

**Comment by BluSunrize** [comment]
Version 1.11 hasn't been supported for a while now.
