### ISSUE TITLE
Feedthrough Insulators should use Relays, not Connectors.

### ISSUE THREAD

**Issue by calloatti** [BluSunrize/ImmersiveEngineering#3452]
### Description of the issue:

Feedthrough Insulators can only be built with connectors. Feedthrough Insulators should also use Relays, not just Connectors.

From the IE manual:

> Feedthrough Insulators allow connecting wiring from one side of a wall to wiring on the other side without a hole.
> 
> All common types of connectors can be used to create feedthrough insulators
> 
> Connectors serve as in- and outputs to the IE Energy-Net. You can place them on capacitors or other Flux handlers
> 
> Relays will still accept wires but can't in- or output, they serve as connection points between wires.

Since the random block used to create the Feedthrough Insulator is not actually a "Flux handler", using connectors to create a Feedthrough Insulator goes against the principles established by the mod itself in the User Manual.

Feedthrough Insulators  "serve as connection points between wires", so they should really use Relays and not Connectors.

Since changing the Feedthrough Insulators to use Relays instead of Connectors would break saved games, Relays should be a valid alternative to Connectors when creating a Feedthrough Insulator.

### Why?

Current Feedthrough Insulators only allow ONE wire to be connected to them. In most use cases, at least two wires are needed on the "output" side (left/right, up/down). The only way around it right now is to add a relay below/above/left right of the output connector of the  Feedthrough Insulator.

![2019-04-26_08 29 26](https://user-images.githubusercontent.com/12817862/56804886-9b377300-67fd-11e9-9fa6-6ee20fbfde88.png)

With Relays in Feedthrough Insulators

![2019-04-26_08 29 52](https://user-images.githubusercontent.com/12817862/56804892-a094bd80-67fd-11e9-9b37-274b05dc0589.png)

With Redstone Connectors, since there are no Redstone Relays, it is already possible to connect more than one wire to a Redstone Feedthrough Insulator.

### Crashlog:

Game is not crashing.

### Versions & Modlist

ImmersiveEngineering-0.12-90-525
Forge Mod Loader version 14.23.5.2836 for Minecraft 1.12.2

**Comment by johnhargrove** [comment]
It is also worth mentioning that the lack of relay support for feedthrough places major limitations on the throughput of lines that are passing through walls. The connector becomes a very narrow bottleneck.

**Comment by johnhargrove** [comment]
Actually it looks like the connectors allow more than their advertised rate through the feedthrough. Interesting. I agree that the connector being the item and not the relay seems inconsistent with the rest of the mod, though. Awesome work on this feature. I love it!

**Comment by PrincessOfEvil** [comment]
It's a connector because a connector has an actual connection to the block below and a relay is just an insulator not connected to anything and with barely a stub for some wire connections.
