### ISSUE TITLE
Refinery Won't Accept Fluid Inputs

### ISSUE THREAD

**Issue by radstah689** [BluSunrize/ImmersiveEngineering#3455]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
Describe what happens, how it affects your game/gameplay and provide screenshots where possible.

### Crashlog:
If your Minecraft instance has crashed, a file will have been generated in the folder `crash-reports` of your minecraft folder. To understand what has happened, we need to know the content of that file. But please don't just put it directly in your report (that makes it hard to read), upload it to a site like [pastebin](http://pastebin.com) or [gist](http://gist.github.com) and put a link in the actuall bug report.

### Versions & Modlist
IE and Forge versions are mandatory. *Note that saying "latest" is **not** valid. Always give the proper version number*
Other mods should be listed (with their versions) in a [pastebin](http://pastebin.com) or [gist](http://gist.github.com) upload. The easiest way to get these lists is a crashlog, you may force one with F3+C.
If your game crashed (see above) you may omit the modlist, but IE and Forge version would still be nice.

Also, please try testing an issue in a minimal instance, with just IE, Forge and maybe JEI. That makes elminating compat issues easier.

### Lastly (you may delete this from the report itself)
Please, for the love of all that is voxelbased, **read the contribution guidelines. They are linked to the right in the message box.**
When reporting issues, these are crucial, and the team withholds the right to close an issue for the plain stupidity of not reading and adhering to them.

Thank you for reporting issues, without people reporting them, they wouldn't get fixed. You're helping contribute to this mod and that is much appreciated <3

**Comment by radstah689** [comment]
Playing single player local version FTB Infinity Lite 1.10 with IE 10.57 included.

Neither side of the Refinery will accept plant oil or ethanol input from fluid pipes, even with a powered fluid pump. It will accept fluid manually input through buckets. Doesn't crash anything.

I have seen the previous issues and the changelog where they were fixed but both are from before 10.57 so I do not know if this is the same issue. I have no experience with computers beyond the average American so some help would be appreciated. Even if it can't be fixed IE is still the coolest mod I've seen so far. Thank you,

Mods in FTB Infinity Lite:
AppleSkin	squeek502	AppleSkin-mc1.10.2-1.0.5.jar
Aroma1997Core	Aroma1997	Aroma1997Core-1.9.4-1.1.1.2.jar
Aroma1997s Dimensional World	Aroma1997	Aroma1997s-Dimensional-World-1.9.4-1.2.0.6.jar
Bagginses	lorddusk	Bagginses-1.10.2-3.0.4g.jar
Baubles	azanor	Baubles-1.10.2-1.3.9.jar
BdLib	bdew	bdlib-1.12.4.24-mc1.10.2.jar
Better Builder's Wands	Portablejim	BetterBuildersWands-1.10.2-0.11.1.220+f8232fe.jar
BetterBedrockGen	Gigabit1011	BBG-1.9.4-5.0.0.jar
Biomes O' Plenty	Glitchfiend	BiomesOPlenty-1.10.2-5.0.0.2155-universal.jar
Blood Magic	WayofTime	BloodMagic-1.10.2-2.1.9-78.jar
Bookshelf	Darkhax	Bookshelf-1.10.2-1.4.4.347.jar
Botania	Vazkii	Botania r1.9-341.jar
Brandon's Core	brandon3055	BrandonsCore-1.10.2-2.1.5.97-universal.jar
Chameleon	jaquadro	Chameleon-1.10-2.2.2.jar
Charset (1.10.x)	asiekierka	Charset-0.3.0-pre15.jar
Chest Transporter	CubeX2	ChestTransporter-1.10.2-2.5.12.jar
Chisel	tterrag1098	Chisel-MC1.10.2-0.0.9.15.jar
Chisels & Bits	AlgorithmX2	chiselsandbits-12.12.jar
CodeChicken Lib 1.8.+	covers1624	CodeChickenLib-1.10.2-2.5.7.241-universal.jar
Compact Solars	progwml6	CompactSolars-1.10.2-5.0.8.331-universal.jar
CompatLayer	McJty	compatlayer-1.10-0.2.5.jar
Cooking for Blockheads	BlayTheNinth	CookingForBlockheads_1.10.2-4.2.39.jar
CraftTweaker	jaredlll08	CraftTweaker-1.10.2-3.0.24.jar
Custom Main Menu	lumien231	CustomMainMenu-MC1.10.2-2.0.2.jar
Dark Utilities	Darkhax	DarkUtilities-1.10.2-1.1.7.111.jar
Deep Resonance	McJty	deepresonance-1.1x-1.4.6.jar
Default Options	BlayTheNinth	DefaultOptions_1.10.2-6.1.5.jar
Draconic Evolution	brandon3055	Draconic-Evolution-1.10.2-2.0.9.192-universal.jar
ElecCore	Elec332	ElecCore-1.10.2-1.7.409.jar
Ender IO	CrazyPants_MC	EnderIO-1.10.2-3.1.156.jar
EnderCore	tterrag1098	EnderCore-1.10.2-0.4.1.65-beta.jar
EnderTanks	ShetiPhian	endertanks-1.10.0-1.4.11.jar
Extra Utilities	RWTema	extrautils2-1.10.2-1.3.3.jar
Extreme Reactors	ZeroNoRyouki	ExtremeReactors-1.10.2-0.4.5.27.jar
Flat Colored Blocks	AlgorithmX2	flatcoloredblocks-mc1.10-v4.4.jar
Forestry	SirSengir	forestry_1.10.2-5.2.17.368.jar
FTB Library	FTB	FTBLib-1.10.2-3.4.5.jar
FTB Utilities	FTB	FTBUtilities-1.10.2-3.4.4.jar
Gendustry	bdew	gendustry-1.6.5.30-mc1.10.2.jar
GraveStone Mod	EuhDawson	GraveStone Mod 1.5.12.jar
Guide-API	TehNut	Guide-API-1.10.2-2.0.3-46.jar
Hammer (Lib) Core	Zeitheron	HammerCore_1.10.2-1.4.8.jar
Immersive Engineering	BluSunrize	ImmersiveEngineering-0.10-57.jar
Industrial Craft	Player	industrialcraft-2-2.6.188-ex110.jar
Inventory Tweaks	Kobata	InventoryTweaks-1.61-58.jar
Iron Chests	progwml6	ironchest-1.10.2-7.0.11.797.jar
Item Scroller	masa_	itemscroller-1.10.2-0.11.0.jar
JEI Bees	bdew	jeibees-0.9.0.5-mc1.10.2.jar
JourneyMap	techbrew	journeymap-1.10.2-5.4.6.jar
Just Enough Items (JEI)	mezz	jei_1.10.2-3.14.7.416.jar
Just Enough Resources (JER)	Way2muchnoise	JustEnoughResources-1.10.2-0.5.8.98.jar
KleeSlabs	BlayTheNinth	KleeSlabs_1.10.2-3.3.5.jar
Mantle	mDiyo	Mantle-1.10.2-1.1.5.jar
McJtyLib	McJty	mcjtylib-1.1x-2.3.11.jar
Mekanism	aidancbrady	Mekanism-1.10.2-9.2.2.301.jar
Mekanism Generators	aidancbrady	MekanismGenerators-1.10.2-9.2.2.301.jar
Mekanism Tools	aidancbrady	MekanismTools-1.10.2-9.2.2.301.jar
Mercurius	TamasHenning	Mercurius-1.10.2-1.0.3.jar
Missing Pieces	sboy205	missing_pieces-1.10.2-4.1.3.jar
MMD OreSpawn	jriwanek	OreSpawn_1.10.2-1.1.0.jar
MmmMmmMmmMmm	bonusboni	MmmMmmMmmMmm-1.11.jar
Mod Name Tooltip	mezz	modnametooltip_1.10.2-1.6.0.jar
Morpheus	Quetzi	Morpheus-1.10.2-3.1.13.jar
Mouse Tweaks	YaLTeR97	MouseTweaks-2.8-mc1.10.2.jar
MultiStorage	ShetiPhian	multistorage-1.10.0-1.2.16.jar
Natura	mDiyo	natura-1.10.2-4.1.0.34.jar
NetherPortalFix	BlayTheNinth	netherportalfix-mc1.9.4-4.0.1.jar
OpenBlocks Elevator	VsnGamer	ElevatorMod[V.1.3.0][MC.1.10.2].jar
OpenComputers	SangarWasTaken	OpenComputers-MC1.10.2-1.6.2.7.jar
Pam's HarvestCraft	MatrexsVigil	Pam's HarvestCraft 1.9.4-1.10.2h.jar
Platforms	ShetiPhian	platforms-1.10.0-1.2.9.jar
QuantumStorage	Gigabit1011	QuantumStorage-1.10.2-3.3.2.jar
Railcraft	CovertJaguar	Railcraft_1.10.2-10.0.1.jar
Ranged Pumps	raoulvdberge	rangedpumps-0.3.jar
Reborn Core	modmuss50	RebornCore-1.10.2-2.13.5.136-universal.jar
Refined Relocation 2	BlayTheNinth	RefinedRelocation-mc1.10.2-2.1.23.jar
Refined Storage	raoulvdberge	refinedstorage-1.2.25.jar
Reliquary v1.3	P3pp3rF1y	Reliquary-1.10.2-1.3.3.639.jar
Resource Loader	lumien231	ResourceLoader-MC1.9.4-1.5.1.jar
RFTools	McJty	rftools-1.1x-5.91.jar
RFTools Control	McJty	rftoolsctrl-1.1x-1.6.6.jar
Roots	epicsquid319	roots-0.208.jar
Shadowfacts' Forgelin	shadowfactsmc	Forgelin-1.4.1.jar
ShadowMC	shadowfactsmc	ShadowMC-1.10.2-3.6.1.jar
ShetiPhianCore	ShetiPhian	shetiphiancore-1.10.0-3.3.8.jar
Signals	MineMaarten	Signals-1.10.2-0.5.1-universal.jar
Simple Barrels	workshopcraft	simplebarrels-1.26e.jar
Simple Covers	bdew	covers-0.4.1.17-mc1.10.2.jar
Simple Generators	ValkyrieofNight	simplegenerators-1.10.2-0.10.6a.jar
Simpleretrogen	cpw11	simpleretrogen-1.10-4.0.1+8.jar
Sleeping Bag	shadowfactsmc	SleepingBag-1.10.2-1.4.0.jar
Solar Flux Reborn	Zeitheron	SolarFluxReborn_1.10.2-2.16r.jar
Soul Shards: The Old Ways	SgtPunishment	SoulShards-TOW-1.10.2-2.6.7-48.jar
StacksOnStacks	Madxmike856	StacksOnStacks2-1.1.4.jar
Storage Drawers	jaquadro	StorageDrawers-1.10.2-3.6.2.jar
Super Crafting Frame	Edgar_Allen	supercraftingframe-1.10.2-1.2.1.88.jar
The One Probe	McJty	theoneprobe-1.1x-1.4.5.jar
Tinkers Construct	mDiyo	TConstruct-1.10.2-2.6.3.jar
Useful Nullifiers	Bartz24	usefulnullifiers-1.3.4.jar
ValkyrieLib	ValkyrieofNight	valkyrielib-1.10.2-0.10.6.jar
ZeroCore	ZeroNoRyouki	zerocore-1.10.2-0.1.0.4.jar

**Comment by BluSunrize** [comment]
1.10 hasn't been supported in a long while, but let's try to debug this anyway.

Pictures of your setup please? Because I recon it's just wrong piping.

**Comment by radstah689** [comment]
![image](https://user-images.githubusercontent.com/50058216/56855694-8a7c1f80-6919-11e9-9961-ff0542dd2a97.png)
Just a basic connection from tank to refinery. There is fluid in the tank, just not a lot. FTB Infinity Lite doesn't have cloches so I'm limping along with a smaller EnderIO automated farmer. 

Thank you for replying so fast. If FTB Infinity Lite 1.10 isn't supported, is there a recommended FTB pack (easiest because through Twitch, but I can try some other pack/service?) that has a supported version of IE? If there is, the easiest solution is to switch to something that is more current.

**Comment by BluSunrize** [comment]
Well we only work on Minecraft version 1.12 now, and there is plenty 1.12 packs.

Regarding your issue: Tanks need a redstone signal on the bottom block in order to automatically output. Without a signal, you won't get any fluids into your pipes, and thus none into the refinrery.

**Comment by radstah689** [comment]
That fixed it, thank you. Even the old IE versions are sweet, and I really appreciate how quickly you helped me.
