### ISSUE TITLE
Assembler Doesn't Assemble Wooden Ties from Railcraft

### ISSUE THREAD

**Issue by GamerbyDesign** [BluSunrize/ImmersiveEngineering#3456]
The Assembler is fully powered, shows the correct recipe, and is full of Creosote Oil  I believe the issue might be related to thermal foundation as it show the bucket of Creosote Oil from that mod and not the one from Immersive Engineering.

**Comment by mindforger** [comment]
You should have read the prepared text ans contribution guidelines

This issue is like writing an anonymous letter to your doctor saying i feel pain when i move, whats wrong :)

**Comment by GamerbyDesign** [comment]
Where is the prepared text ans contribution guidelines?  Guess I forgot to say Immersive Engineering 0.12-89, MC 1.12.2 , Railcraft 12.0.0, and Thermal Foundation 2.6.2.26.

**Comment by mindforger** [comment]
thy :)

**Comment by fredredbuilder** [comment]
I am having a similar issue. Running 1.12.2, Forge 14.23.5.2838 IE .12-89, Railcraft 12.0.0, Crafttweaker 2.0.2
Before updating to 1.12.2, had assembly machine that took vanilla oak planks, converted to slabs, then combined with creosote oil in second recipe to make RC wooden ties. See CT recipes below. 

import crafttweaker.liquid.ILiquidStack;
import crafttweaker.item.IIngredient;
val CreoBucket=<forge:bucketfilled>.withTag({FluidName: "creosote", Amount: 1000});
recipes.addShaped("1pcw_tie", <railcraft:tie>, [[null,null,null],[CreoBucket,CreoBucket, null], [<ore:slabWood>, <ore:slabWood>, <ore:slabWood>]]);

Now with 1.12.2, assembly machine will make slabs but not wooden ties, Assembly machine recognizes recipes but will not create ties. Have tried many variations to try and debug but not been successful. Open to any ideas...
