### ISSUE TITLE
[Request] Compatibility for Thermal Dynamics "Redstone Relay" and garden cloches? 

### ISSUE THREAD

**Issue by STOKE-STER** [BluSunrize/ImmersiveEngineering#3461]
Hey, big fan of the modpack :)

As I understand it cloches are designed to stop producing when they receive a redstone signal. Could you perhaps add support for the redstone relay from Thermal Dynamics? It attaches to the fluxduct at the top of the cloche and can be used to receive a redstone signal and then pass it on to the cloche, making it stop producing. Currently (Unless I've set it up wrong) the redstone relay doesn't stop the cloche producing. 

Thankyou.

**Comment by BluSunrize** [comment]
The cloche only accepts redstone signal control on the bottom block currently.
I can look into changing that however.

**Comment by BluSunrize** [comment]
Okay, nevermind.
It's not possible with those anyhow. Thermal's Redstone Relays only output "weak" (indirect) redstone signals, and our cloche only accepts "strong" (direct) ones.

May I suggest using IE's very own Redstone Wires instead? Because I know for a fact that they work.
