### ISSUE TITLE
[suggestion]custom deposits

### ISSUE THREAD

**Issue by fireair** [BluSunrize/ImmersiveEngineering#3462]
So I was playing yesterday and thought "Man, it would be so cool if i could add custom veins in the config." My question is can you already do this or if not would you be interested in add this?

Also Thank you for continually updating the mod I really appreciate it :) .

**Comment by malte0811** [comment]
You can already add custom veins/deposit types using CraftTweaker.

**Comment by fireair** [comment]
sweet thanks

**Comment by fireair** [comment]
@malte0811 could you please tell me whats wrong with my script?

import mods.immersiveengineering.Excavator;

mods.immersiveengineering.Excavator.addMineral("Africite", 50, 0.0005, ["ore:orevibranium", "ore:oreDiamond","ore:orepalladium","ore:oreTitanium"], [35, 15, 25, 25]);

**Comment by BluSunrize** [comment]
Could you maybe elaborate what about your script isn't working?

**Comment by fireair** [comment]
i fuigured it out I had to take out the ore: of each name and captilize the "p" in palladium and "v" vibraium
