### ISSUE TITLE
Crash on world load [1.12.2, Forge 2836]

### ISSUE THREAD

**Issue by JackRaidenPH** [BluSunrize/ImmersiveEngineering#3463]
https://pastebin.com/dFcnYSeP

**Comment by BluSunrize** [comment]
Can you reproduce this with just IE?

**Comment by JackRaidenPH** [comment]
With only IE it's fine. Firstly i thought that it conflicts with Railcraft, but without it nothing changes.

**Comment by BluSunrize** [comment]
Well, time for a binary search. Remove half the mods (excluding IE), see if the issue persists. If so, halve the list again. If not, do so with the other half.
Do that log2(n) times to figure out what mod causes it.

**Comment by JackRaidenPH** [comment]
Another interesting moment is that there are two references: First is pointing to ClientProxy line 1438, that is just curly bracket, the second is pointing to commented text in EventHandler line 132.

**Comment by JackRaidenPH** [comment]
The problem has been found. It was port of DivineRPG that registered a null in entityRenderMap
