### ISSUE TITLE
Growthcraft Radiation Crash?

### ISSUE THREAD

**Issue by EightBlade** [BluSunrize/ImmersiveEngineering#3465]
I have no idea what causes this. https://pastebin.com/btmfk9j9

**Comment by mindforger** [comment]
>growthcraft.rice.common.block.BlockRiceCrop.getDrops(BlockRiceCrop.java:138)

i can't see IE anywhere in that trace

**Comment by EightBlade** [comment]
You sure? It's the only thing in my modded set up that adds Uranium, so I'm not sure what else could cause the radiation.

**Comment by mindforger** [comment]
>growthcraft.rice.common.block.BlockRiceCrop.getDrops(BlockRiceCrop.java:138) is crashing, which means something int BlockRiceCrop.java from greothcraft want to access a property "is_radiation" on a block (primal:mud) that has no such property ... nothing here is called from IE, so they are having an issue not IE

**Comment by EightBlade** [comment]
Thanks, then. Sorry about the mix up, I'll toss it to them!

**Comment by mindforger** [comment]
please drop in more informations when creating a bug report, the crashlog was enough in this case but mostly this kind of reports will be ignored due to missing details like versions of forge and other mods involved or what you did or when it happened
