### ISSUE TITLE
[Question] [1.7.10] IDrillHead beforeBlockbreak event

### ISSUE THREAD

**Issue by Shurgent** [BluSunrize/ImmersiveEngineering#3466]
Hi! I'm trying to add my own drill heads, and I need to limit which blocks I can destroy and which ones I can't. I think so I need to use event "beforeBlockbreak", but I do not see the argument of type Block or something like that. Can I determine which block I am trying to destroy, in order to decide whether to destroy it or not?
Thanks!

**Comment by BluSunrize** [comment]
The parameter in question doesn't exist. You can potentially extrapolate the blocks targeted from the player and their view angles, but that'll be tedious. There is also method that returns the blocks that are to be dug, allowing you to specify the pattern it digs in, but that method was not in existence in 1.7.10.

1.7 is not supported anymore and was phased out over 3 years ago. The API will not see any updates there.
