### ISSUE TITLE
Cables of IE are disconnecting.

### ISSUE THREAD

**Issue by Frisoko03** [BluSunrize/ImmersiveEngineering#3468]
The cables of IE are disconnecting every hour that logs in the world, the high and medium voltage.
Version Mod: ImmersiveEngineering-0.12-89
Minecraft: 1.12.2

**Comment by PrincessRTFM** [comment]
Please provide your forge version (number, do not simply say "latest"), a full modlist, and preferably a crashlog. You can force a crash by holding F3 and C in-game for ten seconds. Please do not paste these directly into this issue, as they are very long; use a site like [Pastebin](http://pastebin.com/) or [Gist](http://gist.github.com/) and provide the link instead. This is all in accordance with Blu's [issue reporting guidelines](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/ISSUE_TEMPLATE.md), which should also have been pre-loaded into the report form when you went to open this issue.

**Comment by Frisoko03** [comment]
Hello.
Crashlog: https://pastebin.com/A9i6Nx9K
Version Mod: ImmersiveEngineering-0.12-89
Version Forge: 14.23.5.2768 and tested withs forge 14.23.5.2780, the error continued.
Minecraft: 1.12.2

**Comment by mindforger** [comment]
that is a full log, the crash log is located in the crashlogs folder and MUCH more readable, can you please paste that instead?

**Comment by Frisoko03** [comment]
Ok.
Here's the new Crashlog.
https://pastebin.com/cnQfvbqq
I hope it's correct now.

**Comment by Frisoko03** [comment]
Any word on the error?

**Comment by mindforger** [comment]
Some more details on the setup are required. Do you know wires burn out when overloaded, there can probably be peak currents because of chunkloading when leaving or returning to the area. Hard to tell, maybe add some screenshot

**Comment by Frisoko03** [comment]
I set up this simple system.
It was working, but by disconnecting from the minecraft and logging in again, the energy it stopped flowing through the wire.
Discarded burning wire.

Before logout the world:
https://uploaddeimagens.com.br/imagens/screenshot_6-png-685f8f53-6760-4d88-87cb-e920e3d3bde1

After login to the world:
 https://uploaddeimagens.com.br/imagens/screenshot_5-png-deda4cbc-88ff-4ad3-bb00-12814b3a0380

**Comment by Frisoko03** [comment]
I set up this simple system.
It was working, but by disconnecting from the minecraft and logging in again, the energy it stopped flowing through the wire.
Discarded burning wire.

Before logout the world:
https://uploaddeimagens.com.br/imagens/screenshot_6-png-685f8f53-6760-4d88-87cb-e920e3d3bde1

After login to the world:
https://uploaddeimagens.com.br/imagens/screenshot_5-png-deda4cbc-88ff-4ad3-bb00-12814b3a0380

**Comment by mindforger** [comment]
Oh, so the power stopped flowing but the wires are still there. Sounded different in your first post. I THINK the issue may be the mekanism cables but i would have tot test it myself, as i never use mekanism

**Comment by Frisoko03** [comment]
I used the cable of the mekanism only to show that it was not passing energy.
If I do the system only with IE, the error also occurs.

**Comment by Frisoko03** [comment]
I used cable Mekanism to show that I was not passing energy.
The same system mounted only with IE, this error also occurs on the wire.

**Comment by hmshood** [comment]
I believe this is the same issue as https://github.com/BluSunrize/ImmersiveEngineering/issues/2294
I see in the screenshot you're using Fluxducts as the 'destination' for power from the IE connector
