### ISSUE TITLE
Out of Control computer Lag

### ISSUE THREAD

**Issue by Useydess** [BluSunrize/ImmersiveEngineering#3469]
hello when i try and play Immersive Engineering 1.12.2 the game lags out of control. iIs almost unplayable thanks to this lag and i really can't do anything about it. i am using Immersive Railroading because i need the creative capaitors to power the machines plus and track API which is just a systems so the mod works properly

**Comment by PrincessRTFM** [comment]
Please provide your forge version, IE version (number, do not simply say "latest"), a full modlist, and preferably a crashlog. You can force a crash by holding F3 and C in-game for ten seconds. Please do not paste these directly into this issue, as they are very long; use a site like [Pastebin](http://pastebin.com/) or [Gist](http://gist.github.com/) and provide the link instead. This is all in accordance with Blu's [issue reporting guidelines](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/ISSUE_TEMPLATE.md), which should also have been pre-loaded into the report form when you went to open this issue.
