### ISSUE TITLE
Log warns refering to IE, game crashes after opening recipe book and crafting modded items

### ISSUE THREAD

**Issue by syi666** [BluSunrize/ImmersiveEngineering#3470]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
after opening recipe book game will crash after crafting modded items such as seeds from pam's or other small 1:1 crafts

### Crashlog:
https://paste.ee/p/vQRcZ

### Versions & Modlist
Aether Legacy
AstralSorcery
Baubles
Bewitchment
BiblioCraft
Biomes O' Plenty
Botania
ChickenChunks
Chisel
CodeChicken Lib
CoFH Core
CoFH World
Cooking for Blockheads
CosmeticArmorReworked
CTM
Decocraft
Ice and Fire
Immersive Engineering 0.12-89
LLibrary
Mantle
Pam's HarvestCraft
Patchouli
PTRLib
Redstone Flux
Reliquary
Thermal Expansion
Thermal Foundation
Tinkers' Contruct
Waystones
Plustic
Tinkers armory
FML 14.23.5.2837

### Lastly (you may delete this from the report itself)
Please, for the love of all that is voxelbased, **read the contribution guidelines. They are linked to the right in the message box.**
When reporting issues, these are crucial, and the team withholds the right to close an issue for the plain stupidity of not reading and adhering to them.

Thank you for reporting issues, without people reporting them, they wouldn't get fixed. You're helping contribute to this mod and that is much appreciated <3

**Comment by PrincessRTFM** [comment]
I admit, I'm confused. I don't see where the log refers to IE except to include it in the list of loaded mods. The crash looks like it's coming from the Minecraft recipe book render code (trace line 1 reports it being at` net.minecraft.client.gui.recipebook.GuiRecipeBook.func_191861_a`), but it's _definitely_ being reported as a render crash (`java.lang.NullPointerException: Rendering screen`) and IE isn't showing up in the stack trace for it. You're using NVIDIA, are you on the latest drivers? Did this only start after updating _to_ the latest drivers?

**Comment by syi666** [comment]
This happened on both the new and updated drivers. I’ve tried phosphor,
foamfix, optifine and better for to remedy the issue. I've also tried no
recipe book and it still crashes

**Comment by BluSunrize** [comment]
Well nothing in that points to IE being the sourve of it. Plus, you said that it happened when crafting Pam's items.
Closing this.
