### ISSUE TITLE
Immediate Crash to Desktop

### ISSUE THREAD

**Issue by marikc0** [BluSunrize/ImmersiveEngineering#3472]
### Description of the issue:
Just playing. Both times this happened I was using RailCraft, TE and EIO to convert fluids. Not doing much with IE at all, but the crash is pointing to it. I only have basically two windmills and one water. That's the only thing I'm using IE for.

### Crashlog:
https://pastebin.com/mNAZJwem
https://pastebin.com/ZPK31TQt

### Versions & Modlist
IE 0.12-89
MC 1.12.2
Forge 14.23.5.2822

Mod list: https://i.imgur.com/DKg3sBP.jpg

**Comment by marikc0** [comment]
Update: I removed a water wheel that was being powered by lava. The CTD seems to have stopped. This appears to be what was causing it.

**Comment by BluSunrize** [comment]
Memory Access Violations are a rarity in Java, and nothing in that particular part of IE's code hints towards why this would happen. There is no reflection, no weird memory access in there.
I've got not the slightest idea...

**Comment by mindforger** [comment]
i've seen this one before somewhere with the exact same report

try removing foamfix for a test please

**Comment by malte0811** [comment]
Also try removing VanillaFix and Phosphor. VF does a lot of very strange things, many of which can cause issues with other mods. I'm not sure how much Phosphor does, but it's definitely in the category of "mods that make strange changes to internal things".

**Comment by marikc0** [comment]
> ### Description of the issue:
> Just playing. Both times this happened I was using RailCraft, TE and EIO to convert fluids. Not doing much with IE at all, but the crash is pointing to it. I only have basically two windmills and one water. That's the only thing I'm using IE for.
> 
> ### Crashlog:
> https://pastebin.com/mNAZJwem
> https://pastebin.com/ZPK31TQt
> 
> ### Versions & Modlist
> IE 0.12-89
> MC 1.12.2
> Forge 14.23.5.2822
> 
> Mod list: https://i.imgur.com/DKg3sBP.jpg

**Comment by mindforger** [comment]
@marikc0 did it actually help? which one caused it?

**Comment by marikc0** [comment]
It's difficult to test. I would have to remove one by one and play for some hours without each mod to wait for a crash. I wish I could do it more easily. The crash was a bit random and wouldn't happen for a few hours sometimes. Just got lucky and remember that it started after using lava on the water wheel and when I removed it the crash stopped. Sorry, wish I could be more help than that. But this is here at least as an advisory if people encounter the same problem and they can remove lava if they were using it.
