### ISSUE TITLE
[1.12.2] Client stuck in loop trying to render custom blueprint

### ISSUE THREAD

**Issue by xElementzx** [BluSunrize/ImmersiveEngineering#3474]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
Describe what happens, how it affects your game/gameplay and provide screenshots where possible.
When creating a custom blueprint with Modtweaker/CraftTweaker and using a block as the output the client will get stuck in a loop processing getBlueprintDrawable 

VisualVM Sample here https://i.imgur.com/BYXYIIy.png

Custom line for adding Diamond Block with CraftTweaker script
```mods.immersiveengineering.Blueprint.addRecipe("components", <minecraft:diamond_block>, [<ore:logWood>, <minecraft:dirt>]);```

### Versions & Modlist
Forge 1.12.2 - 2836
Immersive Engineering 0.12-89
MTLib 3.0.6
modtweaker 4.0.17
CraftTweaker2 4.1.17

Thank you for reporting issues, without people reporting them, they wouldn't get fixed. You're helping contribute to this mod and that is much appreciated <3

**Comment by LXGaming** [comment]
There is an infinite loop here, If the blueprint is null (Which is the case here) `l` never gets incremented https://github.com/BluSunrize/ImmersiveEngineering/blob/f2334410de60bc8e8d65ad2921f58e9fe37e784c/src/main/java/blusunrize/immersiveengineering/client/render/TileRenderWorkbench.java#L61-L86
