### ISSUE TITLE
 [1.12.2] Engineer´s Workbench create a render bug for chests

### ISSUE THREAD

**Issue by Realever** [BluSunrize/ImmersiveEngineering#3476]
### Description of the issue:
Hi,
i have a wired render bug when i put something into the Engineer´s Workbench that cause that original minecraft  chests are from the rendering like invisible.I have createt 3 sceenshots where you can see whats happen.The only two ways to fix this is like the first and the last screenshot.But when there is only the blueprint inside then comes the render bug.It´s happen when i´m out of the workbench too.I play minecraft 1.12.2 and the ImmersiveEngineering is 0.12-89. Sorry for my bad english
![2019-05-21_01 42 24](https://user-images.githubusercontent.com/21349241/58058911-31478a80-7b6b-11e9-855e-3647081130ea.png)
![2019-05-21_01 42 33](https://user-images.githubusercontent.com/21349241/58058912-31478a80-7b6b-11e9-9cb3-ffc26c95c5eb.png)
![2019-05-21_01 42 40](https://user-images.githubusercontent.com/21349241/58058914-31478a80-7b6b-11e9-9863-dd721b1c96e4.png)

### Versions & Modlist
I play minecraft 1.12.2 the forge version is 14.23.5.2836  and the ImmersiveEngineering is 0.12-89. 
The modlist: https://gist.github.com/Realever/28b045d2aae238ae57b86ef986eaa8b5

**Comment by mindforger** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/3361
