### ISSUE TITLE
[Crash] 1.12 Java Access Violation

### ISSUE THREAD

**Issue by xGarionx** [BluSunrize/ImmersiveEngineering#3478]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
Accessed AE2 and searched for iron ...since the issue is IE & render related i suspect there was a mouse over one of IE Items (its entirely possible that the actual cause is something else).

Notes:
Happened on Multiplayer (Dedicated Server)
Not reliable reproduceable works ~20% of the time for now apparent reason
Not sure about the Server System (pretty certain its not spongeforge)

### Crashlog:
https://pastebin.com/5trdNsDY

### Versions & Modlist
IE and Forge versions are mandatory. *Note that saying "latest" is **not** valid. Always give the proper version number*
Forge Version : 14.23.52837
IE Version : 0.12.89
Other Mods: https://minecraft.curseforge.com/projects/the-ancient-cake/relations/dependencies

Other mods should be listed (with their versions) in a [pastebin](http://pastebin.com) or [gist](http://gist.github.com) upload. The easiest way to get these lists is a crashlog, you may force one with F3+C.
If your game crashed (see above) you may omit the modlist, but IE and Forge version would still be nice.

Also, please try testing an issue in a minimal instance, with just IE, Forge and maybe JEI. That makes elminating compat issues easier.

---> since this happend in an AE2 system its likely that there is a mod interaction at work with different mods.

### Lastly (you may delete this from the report itself)
Please, for the love of all that is voxelbased, **read the contribution guidelines. They are linked to the right in the message box.**
When reporting issues, these are crucial, and the team withholds the right to close an issue for the plain stupidity of not reading and adhering to them.

i actually have read them .

Thank you for reporting issues, without people reporting them, they wouldn't get fixed. You're helping contribute to this mod and that is much appreciated <3

**Comment by mindforger** [comment]
aaaand another one

https://github.com/BluSunrize/ImmersiveEngineering/issues/3448

can you please try removing foamfix and see if the issue comes up again?

also to quote malte
>Also try removing VanillaFix and Phosphor. VF does a lot of very strange things, many of which can cause issues with other mods. I'm not sure how much Phosphor does, but it's definitely in the category of "mods that make strange changes to internal things".

and call back if it happens again and also if it didnt happen again ... try without the named mods at a time, so this issue can be redirected (i am planning to report this to foamfix soon just in case)

**Comment by xGarionx** [comment]
Here lies an issue i havnt had this problem occuring to myself it was reported to me by one of the player from this modpack (i made) i personally didnt encounter the issue and didnt with just AE2+ addons and immersive with our without foamfix +/- vanillafix. 
However i can see why foamfix & vanillafix might be the culprit as they generally fix core system of MInecraft and maybe even some functions both alter (i notice that when optifine gets in the mix too all three of them kinda struggle together).
So i don't know how much of further assitance i can be here sorry :(

**Comment by xGarionx** [comment]
https://pastebin.com/5trdNsDY maybe this helps further

**Comment by BluSunrize** [comment]
If I only happens with Foamfix, there's not a whole lot I can do *shrug*
