### ISSUE TITLE
[1.10.2-1.12.2] Not able to Run

### ISSUE THREAD

**Issue by BiggetyBounceman** [BluSunrize/ImmersiveEngineering#3479]
When Using version 1.10.2-1.12.2 using Immersive Engineering or any Immersive mod it crashes, without an report. if there is a way you can help out thank you. 
EDIT: I only used the IE mod no other mod from other publishers and It was working before then it just stopped.

**Comment by BluSunrize** [comment]
There is always a crash report. Check the logs folder.

**Comment by BiggetyBounceman** [comment]
Nvm I figured it out I just had a coremod that was not compatible in there. I don't know how but thanks for the help anyway

**Comment by BiggetyBounceman** [comment]
OK I will have to do it later but thanks though

**Comment by BiggetyBounceman** [comment]
Here you Go: https://pastebin.com/bsJpD21Q

**Comment by BiggetyBounceman** [comment]
please help

**Comment by BluSunrize** [comment]
That's not a crashlog. There is nothing in that.
Run the game until it crashes, then grab the *latest* log.

**Comment by BiggetyBounceman** [comment]
This is the only one I can find the crash starts when I lauch it crashes on the loading screen

**Comment by BiggetyBounceman** [comment]
if you cant help you don't have to waste your time

**Comment by BiggetyBounceman** [comment]
nope still crashing
