### ISSUE TITLE
[1.12] Boiler Duplication Bug

### ISSUE THREAD

**Issue by ldyte3** [BluSunrize/ImmersiveEngineering#3482]
### Description of the issue:
Boiler does a weird duplication. Hammer's fine then few seconds later this happens. See picture. Machine doesn't seem to work / accept water or diesel.

### Crashlog:
None

### Versions & Modlist
Forge: 14.23.4.2707 IE:0.12-82

Playing Sevtech mod pack. 3.0.8.

![2019-05-29_21 42 22](https://user-images.githubusercontent.com/6298218/58589851-c547df00-825a-11e9-8130-07924cbafc8b.png)
![2019-05-29_21 42 33](https://user-images.githubusercontent.com/6298218/58589857-c711a280-825a-11e9-9353-37712c4a503c.png)

**Comment by BluSunrize** [comment]
That machine isn't from Immersive Engineering.

**Comment by ldyte3** [comment]
> That machine isn't from Immersive Engineering.

*facepalm* how didn't i notice. Sorry.
