### ISSUE TITLE
[1.12.2] [Request] Copper Ingot respecting Unidict

### ISSUE THREAD

**Issue by CritFlaw** [BluSunrize/ImmersiveEngineering#3483]
### Description of the issue:
The villager trade with the structural engineer for a deposit map uses the default IE copper ingot, regardless of unidict config. In my pack, I use the thermal copper ingot, but IE will not allow that for the deposit.

### Crashlog:
N/A

### Versions & Modlist
Minecraft 1.12.2
Forge 2836
Mod 89

**Comment by BluSunrize** [comment]
IE offers no compat for Unidict and all our trades and recipes are designed for IE items.
If villager trades are unaffected, that's not on us. Obviously, this mod is designed to use the items it adds, rather than others.

**Comment by CritFlaw** [comment]
Would a simple solution not be to have the villager use the oredict entry instead of the specific IE ingot version of the copper ingot?

**Comment by BluSunrize** [comment]
Nope, because villager recipes don't work like that.
They require item stacks and have no overridable predicate functions, as far as I'm aware.
