### ISSUE TITLE
Unable to get Y-rotated facing of down

### ISSUE THREAD

**Issue by mistek131995** [BluSunrize/ImmersiveEngineering#3484]
Version mod: Immersive Engineering 0.12 - 89
Version forge: 1.12.2 - 14.23.5.2838
Description: Player placed block and have this crash on client.

[log.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/3261219/log.txt)

**Comment by malte0811** [comment]
What block did the player place? If they somehow got the excavator block itself (only possible using cheats/`/give`), then it is (in my opinion) their own fault for cheating in blocks they don't understand. Also, what launcher are you using?

**Comment by mistek131995** [comment]
> What block did the player place? If they somehow got the excavator block itself (only possible using cheats/`/give`), then it is (in my opinion) their own fault for cheating in blocks they don't understand. Also, what launcher are you using?

He building excavator and activated his after he get crash client.

**Comment by BluSunrize** [comment]
I'm unsure how to reproduce or safeguard this.
If you can't provide a reliable test case in an environment with just IE, I'm afraid there's nothing to do.
