### ISSUE TITLE
[1.12.2] CraftTweaker Blueprint Causes Freeze

### ISSUE THREAD

**Issue by hacatu** [BluSunrize/ImmersiveEngineering#3485]
This appears to be similar to #3337 and #3474 but based on the fact that my Blueprint only has one output and my visualvm sampling results show a different stack I believe it is different.

I have a custom blueprint I made using the CraftTweaker integration to turn a blank tinker's construct pattern into a bow string pattern: `mods.immersiveengineering.Blueprint.addRecipe("Patterns", <item:tconstruct:pattern>.withTag({PartType: "tconstruct:bow_string"}), [<item:tconstruct:pattern>]);`.  Having this in any `.zs` file in the scripts folder should cause this error.  If JEI is installed, it will verify that this recipe is added correctly, plus it shows up in the tooltip of the "Patterns" blueprint if I take it from the creative menu and hold shift.  However, if I open the engineer's workbench and shift click or place it into the blueprint slot, the game instantly freezes with no crash and there are no messages in the log or the crafttweaker log which mention any problem.

[Here](https://drive.google.com/open?id=18kbP0XBchXFVbsTFJJmSq9OyNxTXC9U2) is the VisualVM sampling result data.

I have CraftTweaker2-1.12-4.1.18, ImmersiveEngineering-0.12-89, Mantle-1.12-1.3.3.55, and TConstruct-1.12.2-2.12.0.135 on Minecraft 1.12.2 and Forge1.12.2-14.23.5.2838.

**Comment by rs3vans** [comment]
Just curious why this issue was closed? I came here looking for just this issue, as I'm experiencing it too.
