### ISSUE TITLE
[12.2.2][Request] Coordinates on Core Sample

### ISSUE THREAD

**Issue by Greatone123** [BluSunrize/ImmersiveEngineering#3489]
It probably isn't a very popular thing to do, but I was wondering if it would be possible to toggle  the coordinates on the core sample on/off?

I'm trying to give a lost, can't figure out where I am kind of modpack, and the core sample is the only thing that could give players an idea of where they are.

I know it's impossible to prevent some determined people, but I would like to at least do what I can to slow it down.

Thank you for your time.

**Comment by BluSunrize** [comment]
That's a very specific usecase, and does kind of defeat the point of the core samples.

**Comment by Greatone123** [comment]
I thought the point was to know what's in the chunk? I usually drill and then place the core sample on the ground or in the chunk I drilled. I'm not asking for the ability to remove that, it's just the XYZ part of it.

My only other option would be to disable the core sample drill all together, and that would make gameplay very unpleasant.

**Comment by BluSunrize** [comment]
Well teh XYZ helps players actually find the chunk again...

**Comment by mindforger** [comment]
so you want a modpacke that obscures the playerlocation all together ... seems you have a long way before you then, as there are a lot of mods giving location hints more or less obvious (also can you omit F3 at all?)

or do you want to force the player to use specific items?!

**Comment by Greatone123** [comment]
> Well teh XYZ helps players actually find the chunk again...

Yeah, I get it, normally it would be helpful especially if you are drilling a lot etc etc. It's just I wanted to make them responsible for remembering. I figured it wouldn't hurt to ask, I didn't know if it's doable or not. This is the only tech mod I make sure to have in every pack I try to make because of the immersion. Unless there is plans for launching a GPS satellite to allow a player to see em lol (btw that sounds like a cool idea...). 



> so you want to make an modpack that obscures the playerlocation all together ... seems you have a long way before you then, as there are a lot of mods giving location hints more or less obvious (also can you omit F3 at all?)
> or do you want to force the player to use specific items?!

I've attempted to remove everything I can that can tell them where they are, the F3 menu can be disabled with a gamerule. I've removed/config'd all my other mods so far to not have things like death compass, and my minimap is provided by antique atlas so it's primitive. I'm currently working on getting a mod that randomizes player spawn, you won't know where you are, or where anyone else is, it will make finding each other that much more exciting if it happens. I realize it's not 100% but I want to at least say I did what I could.

**Comment by mindforger** [comment]
sounds kinky but has a nice taste to it (and quite a challenge for your modpack)

@BluSunrize if this isn't too much of a thing to implement i would support this, just for the sake of his idea ;) ... 

i know this is nothing that has directly to do with IE for this suggestion, but having an option to omit all coordinates (and i mean everywhere) would allow for a more dedicated gaming experience if you have to work up the techtree to some sort of beacons (reminds me of satisfactory to be honest :D) to be remotly able to find your own location and the location of others (but still easily cheatable, as one can not omit installing client-side-only mods)
