### ISSUE TITLE
MineTweaker Null Error

### ISSUE THREAD

**Issue by berinhardt** [BluSunrize/ImmersiveEngineering#349]
on ImmersiveEngineering-0.5.4

mods.immersiveengineering.Squeezer.removeFluidRecipe(<liquid:plantoil>);

fails with:

java.lang.NullPointerException
	at blusunrize.immersiveengineering.common.util.compat.minetweaker.Squeezer$RemoveFluid.apply(Squeezer.java:99)

**Comment by malte0811** [comment]
I am pretty sure that crash is because of  the coke dust to hop graphite recipe, it has a null fluid as output. That line should be `if(r.fluid!=null&&r.fluid.isFluidEqual(output))`. This is probably necessary for the fermenter as well.

**Comment by BluSunrize** [comment]
Ah, nice spotting, ty ^^

**Comment by BluSunrize** [comment]
Fixed with this:
https://github.com/BluSunrize/ImmersiveEngineering/commit/e27d71db76214d7985baa9801a4a2385bd4a3028
