### ISSUE TITLE
Assembler does not craft planks

### ISSUE THREAD

**Issue by gollariel** [BluSunrize/ImmersiveEngineering#3490]
### Description of the issue:
The assembler does not craft planks from oak wood but working well with another type of wood:
https://youtu.be/2uy6Ej6RRfI

### Crashlog:
It`s not crash 

### Versions & Modlist
Forge version: 1.12.2-14.23.5.2768
Immersive Engineering version: 0.12-89

Mods: https://gist.github.com/gollariel/9e9f3ec8713c6a8011e9f3ecedce63a5
For take all mods and configs, use serversync and host espin.pro

**Comment by mindforger** [comment]
looks like an elaborated modpack, does it have altered recipes (seeing crafttweaker there means probably the recipes have been messed with) 

maybe the pack-maker simply removed it by accident or forgot to put it back

**Comment by gollariel** [comment]
oh. okay. Thanks a lot!

**Comment by BluSunrize** [comment]
No, this is most likely related to existing assembler issues, which malte has fixed. The next release should fix this.

**Comment by mindforger** [comment]
sure, if modpacks change items and recipes after a certain point or way (meaning no how it is meant to be done) immersive engineering can not adapt and you may have to add the recipe back yourself ... but i just noticed in the video, that the recipe seems to be detected properly but is not executed properly ... is this a client on server situation or pure singleplayer?
