### ISSUE TITLE
Enhancement Request: better tool ID system

### ISSUE THREAD

**Issue by SirAron111** [BluSunrize/ImmersiveEngineering#3491]
Hi I would like to request a little change if its possible. Regarding the “immersiveengineering:tool” ID system many tools from the voltmeter to the hammer to the pliers to the manual use the same  ID just other metadata this make sit really hard to use them for commands or for quests in questing packs as they sometimes randomly give the wrong tool or the manual instead and some mods that need to work with such ids for black and with lists etc can sometimes bug out on them and randomly change the for example the manual inside a book storage to a tool making it impossible to get the tool out of there etc. 
So here is my request would it be too much to ask to make these items into something like immersiveengineering:toolhammer
immersiveengineering:toolvoltmeter
immersiveengineering:manual
etc.
This would help fix a lot of random stuff and incompatibilities

**Comment by malte0811** [comment]
This is going to be changed in 1.13+ (due to the removal of metadata), but it will stay as it is in 1.12. Metadata sensitivity is (IMO) a quite basic requirement for any filtering system, you should ask the mods that don't allow filtering by metadata to add that functionality.
