### ISSUE TITLE
Strange bug with enchantments

### ISSUE THREAD

**Issue by ZombiePwner1** [BluSunrize/ImmersiveEngineering#3492]
Whenever I have immersive engineering along with immersive railroads enabled there seems to be a really strange bug with enchantment overlays.

![2019-06-13_07 09 17](https://user-images.githubusercontent.com/18079316/59392486-6fbb1880-8daa-11e9-80ee-746698e9edec.png)

You can clearly see the enchantment overlay is a giant square which is not supposed to be like that.

This affects all tools/weapons.
Does anyone know what causes this strange bug?

**Comment by BluSunrize** [comment]
This bug does not appear in my dev environment. I believe it may be a case of various mods interacting. Can you confirm that this happens in an instance that only contains IE?

**Comment by ZombiePwner1** [comment]
Tested it again with only Immersive engineering + railroading along with track API and this still happens.

My version of railroading 1.6.1_1.12-1138
Engineering mod version 0.12-89

**Comment by BluSunrize** [comment]
Have you tested it *without* Railroading?

**Comment by ZombiePwner1** [comment]
Tested it without railroading and the bug is gone. It's definitely an issue with railroading.

**Comment by KnightMiner** [comment]
Does it happen with just Railroading and not Immersive Engineering? Last I checked its a standalone mod

**Comment by ZombiePwner1** [comment]
It's only when railroading is installed.

**Comment by BluSunrize** [comment]
Cool, not our issue then! :D
