### ISSUE TITLE
Issue: [1.12.2] Feedthrough Insulators Integration Bug 

### ISSUE THREAD

**Issue by jmc529** [BluSunrize/ImmersiveEngineering#3494]
The feedthrough insulators don't want to connect to paper walls from quark for some reason, here is a screenshot. If it matters, the wood is twilight oak wood from twilight forest.

![Quark says no](https://user-images.githubusercontent.com/9061382/59736338-314cb000-9227-11e9-9327-668d78481496.png)

**Comment by BluSunrize** [comment]
I'm unable to reproduce this.
Can you try it with normal oak wood and Quark's paper walls please?
