### ISSUE TITLE
Allow mineral veins to be biome restricted.

### ISSUE THREAD

**Issue by BrisingrAerowing** [BluSunrize/ImmersiveEngineering#3495]
### Description of the issue
I would like to be able to restrict mineral veins to certain biomes for a pack I’m working on. This pack is intended to force long distance transport of materials from a mine in one biome to a processing plant somewhere else.

### Versions & Modlist
MC 1.12.2, others unknown (posting from mobile)

**Comment by winnetrie83** [comment]
Sounds as a very nice feature to me. I Like it! Let's hope they want to add that

**Comment by CrashHermit** [comment]
Same I would love for this feature to be added. I've been working on a modpack that this would be perfect for.

**Comment by mindforger** [comment]
for a next major version i would seriously support this!

i did talk over and over how i made veins more realisitic in digging up crap depending on the mineral ... digging up crap related to the biome it is in would make it even more relaistic ... 

does one know how to properly select biomes when using worldgens with more than the vanilla biomes?! is there a biome dictionary?

**Comment by BluSunrize** [comment]
I plan to look into this anyhow, because the excavator needs some re-writing.

Biome selection will be part of the new features I add to it.

**Comment by critchards** [comment]
Adding some weight to this. Im doing something similar to @BrisingrAerowing, but its for private use only.  For some reason I scanned over crafttweaker and thought it could do biome restrictions on mineral deposits... I was wrong. :( Then I noticed immersive petroleum has this directly in the config and my heart soared once more. Then I found this issue and realized its not implemented in IE, I am sad again. Its been a rollercoaster my friends.

**Comment by PrincessRTFM** [comment]
@mindforger 
> i get the slight feeling that saying "crap" is wrong ... is "junk" better or is there some other word i don't know for the stuff around the minerals you want?
I usually say "cruft" for "useless stuff that I don't want and can't use". Like, my dirt/clay/sand/etc storage is my cruft chests.

**Comment by Kiyaku** [comment]
I'm guessing the rewrite is for 1.14+, but i was wondering if you guys would accept pull requests with a biome restriction for 1.12.2 as well?

**Comment by BluSunrize** [comment]
This is in 1.14 now
