### ISSUE TITLE
[1.12] cannot be cast with thermaldynamics.duct.tiles.TileGrid

### ISSUE THREAD

**Issue by runescapejon** [BluSunrize/ImmersiveEngineering#3499]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
Describe what happens, how it affects your game/gameplay and provide screenshots where possible.
I really don't know how to reproduce and i don't have much information but i do have an error whenever this player of mine login. He haven't came back to me for more information but once i do i will be updating this to contain more information. Sorry but this is the best i can do to just provide the error 

EDIT: from the look of it he had put the leadstone fluxduct (from thermaldynamics) with fluid pump that cause it 
### Crashlog:
If your Minecraft instance has crashed, a file will have been generated in the folder `crash-reports` of your minecraft folder. To understand what has happened, we need to know the content of that file. But please don't just put it directly in your report (that makes it hard to read), upload it to a site like [pastebin](http://pastebin.com) or [gist](http://gist.github.com) and put a link in the actuall bug report.
https://pastebin.com/raw/fuuaUYCP
### Versions & Modlist
IE and Forge versions are mandatory. *Note that saying "latest" is **not** valid. Always give the proper version number*
Other mods should be listed (with their versions) in a [pastebin](http://pastebin.com) or [gist](http://gist.github.com) upload. The easiest way to get these lists is a crashlog, you may force one with F3+C.
If your game crashed (see above) you may omit the modlist, but IE and Forge version would still be nice.

Also, please try testing an issue in a minimal instance, with just IE, Forge and maybe JEI. That makes elminating compat issues easier.

### Lastly (you may delete this from the report itself)
Please, for the love of all that is voxelbased, **read the contribution guidelines. They are linked to the right in the message box.**
When reporting issues, these are crucial, and the team withholds the right to close an issue for the plain stupidity of not reading and adhering to them.

Thank you for reporting issues, without people reporting them, they wouldn't get fixed. You're helping contribute to this mod and that is much appreciated <3

**Comment by BluSunrize** [comment]
Feel free to, uhh, actually remove the template text next time. Really just gotta keep the healines =p

Have you tried using a command to remove the block in question? That could help fix this.

**Comment by runescapejon** [comment]
So, what had happen was i had update the version i was originally at thermal dynamics - 2.5.4.18 when i update it to version 1.12.2-2.5.5.21 the issue only happen once and it fix itself I check the changelog for Thermal Dynamics and this is what they said `Some mods are really stupid. This hopefully makes them less stupid.` i don't know if what they did had fix the issue but here is their changelog Some mods are really stupid. This hopefully makes them less stupid.https://github.com/CoFH/Version/blob/master/thermaldynamics_changelog.txt 

Oh and sorry my bad on the template i assume once i submit it would go away and leave what i had written.

**Comment by runescapejon** [comment]
I'm going to close this as i don't see this as an issue anymore. It seem that updating Thermal Dynamics update might have fix the issue.
