### ISSUE TITLE
Buckshot Cartridge dupe

### ISSUE THREAD

**Issue by LordIconMC** [BluSunrize/ImmersiveEngineering#350]
Version: 0.5.1
Pack FTB Infinity 1.10.0
Place items in the engineers workbench and they never get used up. see video for example. 

Vid of the dupe
https://youtu.be/dSfLvkV9XQc

I have tested with each common and same results

**Comment by BluSunrize** [comment]
You're using an outdated IE. I fixed this one days ago.
