### ISSUE TITLE
[Suggestion] Covered rail track

### ISSUE THREAD

**Issue by winsrp** [BluSunrize/ImmersiveEngineering#3500]
well... its just a rail track surrounded by scaffolding, why... so baby zombies and other small animals stop getting into train stations, yeah you can build an ugly redstone contraption but its ugly... you are awesome with your awesome mod, so a little bit more awesomeness could come out of it. XD.

**Comment by TeamSpen210** [comment]
A minecart is slightly bigger than a block, so this will look wrong. You can just build fences or other walls around your track...

**Comment by BluSunrize** [comment]
It's not very fitting for IE, given that we do nothing with Minecarts.

I happily hand this over to @SkySom to maybe put in Transport.

**Comment by SkySom** [comment]
Minecarts are bigger than a single block size? So no.
