### ISSUE TITLE
Rework villager trading

### ISSUE THREAD

**Issue by KokSaker** [BluSunrize/ImmersiveEngineering#3501]
### Description of the issue:
Some villager trades accept Immersive Engineering copper ingots as a payment and cannot be substituted for equivalent from another mod. Large modpacks tend to have a lot of mods that add copper ingots and usually the one that has the most variants is favorited above the others for consistency. Usually it's TE or base metals etc, not the IE. So the trades are essentially locked forever.

As a possible solution to this problem, the IE copper ingot could be substituted for an item unique to Immersive Engineering but not a part of ore dictionary, like IE Air Balloons.

**Comment by Krutontar** [comment]
Same issue.  Mechanic wants copper and aluminum but wont take forge tagged equivalents.
