### ISSUE TITLE
[Suggestion] Mini Maintainace cart

### ISSUE THREAD

**Issue by tobymaxgames** [BluSunrize/ImmersiveEngineering#3503]
So IE doesn't seem to play well with railcraft, so i was thinking of a more stripped-down, simpler little maintenance cart that could move around on vanilla rails, still draw other carts behind it, and be far more controllable than them furnace cart can ever be expected to be. a small cart that consumes gasoline and in controlled like the half-life 1 railway carts from the level "On a Rail". with each tap of the forward/backward button changing the current speed of the cart, 4 "steps" of moving forward in the cart and 2 backward steps, with one between them that is simply stopped. visually the carts of HL1 are also pretty good
![Railway engine source](https://user-images.githubusercontent.com/20491804/60387305-09531d00-9a6f-11e9-9eef-8c10d36c4371.PNG)
the hl1 source engine
![railway engine](https://user-images.githubusercontent.com/20491804/60387311-14a64880-9a6f-11e9-8408-0a58fd0c3f79.PNG)
the much better Black Mesa remake of the game's version.
from what i know about coding, getting other carts to follow it part might be the hardest, but its strictly not necessary since other mods exist that can do it, so if that part can't work, it can be left out. 

edit: also i know the immersive railroading mod adds this kind of thing but those trains are a bit big for my needs

**Comment by BluSunrize** [comment]
IE doesn't do anything with rails or trains, and I have no plans to add any content in that direction.
