### ISSUE TITLE
Drill head constantly stuck on drills

### ISSUE THREAD

**Issue by baronjutter** [BluSunrize/ImmersiveEngineering#3506]
We have a problem where after some time drills will always stop displaying their add-ons in the workbench and removing the drill bit instantly makes a duplicate appear back on the drill.  It makes it impossible to replace heads once they reach the negatives for durability or even swap out addons like the extra cutting heads or air tanks (yet the graphics for them remain on the drill model)

**Comment by BluSunrize** [comment]
Can you reliably reproduce this in a way that we can test?
Also, please use the issue template next time.
