### ISSUE TITLE
floodlights dont work correctly below y = 0

### ISSUE THREAD

**Issue by 1971chevycamaro** [BluSunrize/ImmersiveEngineering#3508]
if cubic chunks is installed, the floodlights dont function below y = 0 nothing crashes the block just emits light in a weird 5 source pattern?
![2019-07-08_01 01 15](https://user-images.githubusercontent.com/22800439/60786412-19789580-a11c-11e9-8d0d-0fe00bf9cd5c.png)

**Comment by BluSunrize** [comment]
Well, usually in Minecraft, the y axis doesn't go into the negative.
So that'd be why.

**Comment by mindforger** [comment]
>WARNING: This mod WILL break many other mods in hard to predict ways. Most of the incompatibilities cannot be fixed without changes to other mods. Incompatibility list on CurseForge only contains known mods that appear to work flawlessly but are likely to corrupt your world!
Currently Cubic Chunks breaks both NEID and JEID. It WILL eventually corrupt your world, without any way to recover it.
