### ISSUE TITLE
looks like the mod is not compatible with mekanism

### ISSUE THREAD

**Issue by Sailren** [BluSunrize/ImmersiveEngineering#351]
connected a lv coil to creative mekanism cell and the other lv coil to a gregtech basic alloy smelter, this is the crash that happened: 

http://paste.ubuntu.com/12186745/

@unpairedbracket

@aidancbrady

i turned off gt and ic2 compat in this pic, thats why it is not crashing right now:

http://abload.de/img/2015-08-24_21.17.38crqnh.png

**Comment by mindforger** [comment]
is onUpdate in sync with the tick thread? this yould probably be another issue related to NetHandlers Connection MultiMap not having synchronized access! I forked 0.5.3 with spammy debug messages, could you probably test again with this version? (do not craft anything, unless you want a complete list of all debug outputs, i did not manage to hook into the crash report yet so i abused the onCrafting for that)

**Comment by Sailren** [comment]
im testing stuff in creative, im not really playing like direwolf does, just something here, something there, but sure, lemme get the debug version and i will test

**Comment by mindforger** [comment]
mindforger/ImmersiveEngineering but you need to build it yourself or wait until i get home

**Comment by Sailren** [comment]
then i will wait, or do u have a script included? the maintainer for additional buildcraft objects used a build script for the mod before he forked it

**Comment by mindforger** [comment]
shoot i totally forgot about this issue, i'll provide a link to test with this evening (CET/MEZ). Can we meet in IRC probably? nick: "mind"

**Comment by Sailren** [comment]
which one?

**Comment by mindforger** [comment]
EsperNet #mincraftforge
