### ISSUE TITLE
[1.12.2] Water Wheel Rendering Crash

### ISSUE THREAD

**Issue by Questwizard** [BluSunrize/ImmersiveEngineering#3512]
### Description of the issue:
Water wheels occasionally render a duplicate of themselves in an incorrect spot, or sometimes just go invisible. Occasionally, the game will just start rendering other tile entites, like those from AE or TE, incorrectly. Eventually the game will just randomly crash. This crash was while connected to a dedicated server. There were no errors on the server console other than the usual forcibly closed by remote host thing from netty that always happens when someone crashes.

### Crashlog:
https://gist.github.com/Questwizard/87da9e4c52810e9c527957e8e46dd35e

### Versions & Modlist
IE: 0.12-89
Forge: 1.12.2-14.23.5.2838

**Comment by BluSunrize** [comment]
Without a reproducable test case, I don't see a lot of ways to fix this.
The crash happens within Mojang's own chunk code...
