### ISSUE TITLE
[1.12.2] cannot place core sample

### ISSUE THREAD

**Issue by Arkerthan** [BluSunrize/ImmersiveEngineering#3513]
### Description of the issue:
I cannot place the sample core I obtain from the core sample drill. Also while holding the sample I do not see the chunk borders like when I am holding/looking at the drill.  I remember being able to do this before(1.11 I think) and found nothing in the changelog about removing these features.

I have no other mods installed.

### Versions & Modlist
IE: 0.12-89
Forge: 14.23.5.2838

**Comment by BluSunrize** [comment]
Could you please detail your issue in placing it down?
Are you sneaking? Because you gotta be sneaking to place it.

**Comment by Arkerthan** [comment]
Now I feel dumb. Also found that the engineers manual actually says it so I was just blind.
