### ISSUE TITLE
1.12.2 server-side server-initialisation crash

### ISSUE THREAD

**Issue by bobodoustaud** [BluSunrize/ImmersiveEngineering#3516]
hello,
my personal server crashes at the initialisation.

here is the crash report : https://pastebin.com/raw/W16jnLZG

here are the mods list : 

[1.12.2]+VersionChecker-1.4.0.jar
[1.12]UncraftingTable-1.8-beta6.jar 
alternatingflux-0.12.2-2.jar
antiqueatlas-1.12.2-4.5.1.jar
appliedenergistics2-rv6-stable-6.jar
Baubles-1.12-1.5.2.jar 
BetterFps-1.4.8.jar
Biome_Bundle-1.12.2-v6.1.jar
Botania+r1.10-361.jar 
ChickenChunks-1.12.2-2.4.1.73-universal.jar 
chiselsandbits-14.33.jar 
ChunkAnimator-MC1.12-1.2.jar 
Chunk+Pregenerator+V1.12-2.1.jar 
CoFHCore-1.12.2-4.6.3.27-universal.jar 
CoFHWorld-1.12.2-1.3.1.7-universal.jar 
CodeChickenLib-1.12.2-3.2.2.353-universal.jar 
CraftTweaker2-1.12-4.1.18.jar 
CustomNPCs_1.12.2(30Jan19).jar 
DynamicSurroundings-1.12.2-3.5.4.3.jar 
EnderStorage-1.12.2-2.4.5.135-universal.jar 
environmentaltech-1.12.2-2.0.20.1.jar 
ExtraPlanets-1.12.2-0.5.3.jar 
extrautils2-1.12-1.9.9.jar 
FancyBlockParticles-1.12.x-2.4.1.jar 
foamfix-0.10.5-1.12.2.jar 
ForgeMultipart-1.12.2-2.6.1.81-universal.jar 
GalacticraftCore-1.12.2-4.0.2.211.jar 
Galacticraft-Planets-1.12.2-4.0.2.211.jar 
griefprevention-1.12.2-4.3.0.692.jar 
HammerCore-1.12.2-2.0.4.7.jar
Hats-1.12.2-7.0.2.jar 
Hwyla-1.8.26-B41_1.12.2.jar 
iChunUtil-1.12.2-7.2.1.jar 
IGW-Mod-1.12.2-1.4.4-15-universal.jar 
ImmersiveEngineering-0.12-89.jar 
ImmersiveRailroading-1.6.1_1.12-1138.jar 
immersivepetroleum-1.12.2-1.1.9.jar
immersivetech-1.12-1.3.10.jar
immersivetech-1.12-1.3.10.jar
journeymap-1.12.2-5.5.4.jar 
JustEnoughResources-1.12.2-0.9.2.58.jar 
Lockette.jar 
LuckPerms-Sponge-4.4.27.jar 
Mantle-1.12-1.3.3.55.jar 
Mekanism-1.12.2-9.7.9.380.jar
MicdoodleCore-1.12.2-4.0.2.211.jar 
MJRLegendsLib-1.12.2-1.1.8.jar 
mobends-0.24_for_MC-1.12.jar 
mod_chatBubbles-1.0.1_for_1.12.2.litemod
MrTJPCore-1.12.2-2.1.3.35-universal.jar 
NoMoreRecipeConflict-0.13(1.12.2).jar 
ocdevices-snapshot_20190121.jar 
OpenBlocks-1.12.2-1.8.1.jar 
OpenComputers-MC1.12.2-1.7.4.153.jar 
OpenModsLib-1.12.2-0.12.2.jar 
OpenPrinter-1.12.2-0.1.0.2.jar 
OpenTerrainGenerator-1.12.2+-+v6.jar 
OreLib-1.12.2-3.5.2.2.jar 
ProjectRed-1.12.2-4.9.1.92-Base.jar
ProjectRed-1.12.2-4.9.1.92-integration.jar 
ProjectRed-1.12.2-4.9.1.92-lighting.jar
ProjectRed-1.12.2-4.9.1.92-world.jar 
ProportionalDestructionParticles-1.12.2-1.2.4.jar 
RandomThings-MC1.12.2-4.2.7.1.jar 
RedstoneFlux-1.12-2.1.0.6-universal.jar 
SoulShardsRespawn-1.12.2-1.1.1-13.jar 
spongeforge-1.12.2-2825-7.1.6.jar 
Tails-1.12-1.10.0.jar 
ThermalDynamics-1.12.2-2.5.5.21-universal.jar 
ThermalExpansion-1.12.2-5.5.4.43-universal.jar 
ThermalFoundation-1.12.2-2.6.3.27-universal.jar 
TrackAPI-1.1_1.12.jar 
valkyrielib-1.12.2-2.0.20.1.jar 
Visuals-1.12.2-6r.jar
WailaHarvestability-mc1.12-1.1.12.jar
worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar 
WR-CBE-1.12.2-2.3.1.30-universal.jar 

forge version : 14.23.5.2838

**Comment by BluSunrize** [comment]
Can you try it without Sponge and see if the issue persists?

**Comment by bobodoustaud** [comment]
Ok, it still crash.

https://pastebin.com/SSsMGia4

**Comment by BluSunrize** [comment]
It's a completely different issue now. See the message:
```
OTG has detected that you are loading an OTG world that has been used without OTG installed. OTG has fixed and saved the world data, you can now restart the game and enter the world.
```

Relaunch the game and load the world again. Looks like OTG forcefully crashed you once.
