### ISSUE TITLE
EnderTech Conflict

### ISSUE THREAD

**Issue by Zandorum** [BluSunrize/ImmersiveEngineering#352]
Ever since version 5.4 (Making note that 5.3 does not have this issue) I have had messed up textures on EnderTech machines while this is installed. Here is a screenshot of what I mean: http://i.imgur.com/eIknYgQ.jpg

Edit: I have just tried this with only the required mod's for EnderTech (I included Waila however), This is confirmed to have issue. Here is a log http://paste.atlauncher.com/view/59c102d9

**Comment by BluSunrize** [comment]
https://github.com/carrotengineer/EnderTech/issues/54

Related to this, up to Ender Tech to fix.

**Comment by carrotengineer** [comment]
Fixed in build 391 and above. It'll go up to Curse tonight, thanks for the fix :)

**Comment by BluSunrize** [comment]
No prob =P
Should I close this one then?
