### ISSUE TITLE
IE 0.12-89 crash

### ISSUE THREAD

**Issue by Minecraft2p0** [BluSunrize/ImmersiveEngineering#3520]
The game breaks off during the loading process. Here is the crash report:

[https://pastebin.com/u/Minecraft2p0](url)

**Comment by Minecraft2p0** [comment]
https://pastebin.com/u/Minecraft2p0

**Comment by mindforger** [comment]
Both links are empty

**Comment by PrincessRTFM** [comment]
I believe they meant to post https://pastebin.com/YjT1iMLG instead.

**Comment by malte0811** [comment]
Update SimpleFluidTanks, you're 2 (minor) versions behind the latest one available on CF. As far as I can see this was fixed in the build just after the one you're using.
