### ISSUE TITLE
[Suggestion] Add option for cloche to give MA seeds

### ISSUE THREAD

**Issue by Lord-Raiden** [BluSunrize/ImmersiveEngineering#3521]
Version(s) of Forge and mods in question:
ImmersiveEngineering-0.12-89
MysticalAgriculture-1.12.2-1.7.5
MysticalAgradditions-1.12.2-1.3.2
Forge-14.23.5.2824

Before I begin, I am aware that you have already decided to remove this feature from the cloche's functionality, however I would like to make a case in favor of the other, completely unrepresented, side of the issue.

The garden cloche, when used in conjunction with the Mystical Agriculture and Mystical Agradditions, is undeniably a powerful tool. The rate at which it produces essence for the mystical crops is already considered by most to be completely overpowered, and thus not allowed, in competitive environments. However, that is not the issue at question, although it does call into question your previous judgement of it being too overpowered when seeds are being yielded. 

The main issue is that judgement in itself, and -- to a lesser extent -- a player's choice in progression. 

Your core argument, and those of the people who requested the change in question, relied upon the fact that the seeds being included would mean an increase in the essence yield due to the replanting or reprocessing of seeds, which while true, is a gross oversimplification.

To properly achieve this yield in production would mean a massive investment of resources, time, and space. For example, previously the cloche would yield 1 seed and 1 essence per harvest (resource crops, not inferium crops) at approximately twice the speed the seed reprocessor could process the seeds. So, to properly use the seeds, a player would have to build two seed reprocessors, effectively tripling the cost of growing per cloche (the seed reprocessors are actually, in my opinion, more expensive than a cloche, requiring many more rare materials to produce, so it's at least triple the cost of a cloche to achieve optimal efficiency). With such an investment players should be rewarded, even if the outcome is something overpowered being *slightly* more overpowered. 

It is worth noting, the current method of expansion and optimization of a cloche farm to that level is just building more cloches (two more to be exact), and considering that you cannot mass produce seeds to do so, players must repeat a very tedious process repeatedly (seed crafting) to reach the same result. A truly underwhelming experience in itself. This, when coupled with the fact that the decision only hurts players early game, merely makes the cloche a significantly less valuable tool for all but the extremely late game players.

It is also worth noting that most modpack creators that include both mods in their work know that this is a possibility and do nothing to prevent it, showing that they do not believe that the previous method was in any way interfering with the experience (e.g. Sky Factory 3).

Whether or not you agree, the player/host should be the one deciding on this issue, and thus should not be forced to comply to one strict form of expansion. I would recommend adding an option with 3 states called "Mystical Agriculture Cloche Seeds". The options would be as such: "None", cloches give no seeds, pretty self explanatory; "Default", yields at a rate equivalent to planting in the ground, so about 5% of the time it would give a seed; and finally "Always", a cloche will always yield a seed.

Anyway, that's my suggestion, do with it what you will. If any of my logic is faulty, you would like to ask questions regarding my reasoning, or if I have not provided the information required by your guidelines (I believe that I have), I will be checking back at somewhat regular intervals. 

By the way, love the mod and all of the work you've put into it, this is one of the only, if not the only issue I have with it. Sorry if I come of as a little aggressive, that was not my intent.

**Comment by BluSunrize** [comment]
Countless people bitched about the the brokenness of returning seeds, so I disabled it. I'm not brining it back. And no, not as a config option either.

IE's mod compat is intentionally streamlined and *not* heavily configurable. This is a feature to request from an addon mod. I'm pretty sure there is mods that deal with IE and MA already. Check around there.
