### ISSUE TITLE
crashes during startup 1.12.2

### ISSUE THREAD

**Issue by Acelee2006** [BluSunrize/ImmersiveEngineering#3522]
Whenever I load the game during initializing mods Phase 1 it stops at immersive engineering and says    Java(TM) Platform SE binary has stopped working.

### Crashlog:
https://gist.github.com/Acelee2006/ccec7b090d9f752f9c9409be5996a735

### Versions & Modlist
ImmersiveEngineering-0.12-89
1.12.2-forge1.12.2-14.23.5.2838

**Comment by BluSunrize** [comment]
Chances are, you are not allocating enough memory. You are giving it only 2 gig, modded Minecraft should ideally have 4.

**Comment by Acelee2006** [comment]
Ok I tried it with more ram but it still doesn’t get past the initializing phase 1 mods during the forge load up. Do you think it could be with my forge or computer?

**Comment by BluSunrize** [comment]
I'll try to answer that question if if you provide more logs.

**Comment by Acelee2006** [comment]
Here is another newer log
https://pastebin.com/iDN7K5Eu

Here is the debug
https://pastebin.com/gzsNtmAC

Crash report
https://pastebin.com/WPiuTHP1

**Comment by malte0811** [comment]
Try setting `stencilBufferEnabled` to `false` in the IE config.

**Comment by malte0811** [comment]
Try setting `stencilBufferEnabled` to `false` in the IE config.

**Comment by Acelee2006** [comment]
Thank you so much this was needed by so many modpacks and i have been having this issue with other mods. So now they all work thanks
