### ISSUE TITLE
Gun Turret Power Drain

### ISSUE THREAD

**Issue by hotluck** [BluSunrize/ImmersiveEngineering#3523]
Version 0.12-89

I don't know whether this is a bug or not, but I am in the process of setting up powered lanterns and some gun turrets around my colony. I have 2 windmills (covered in tough fabric) and 3 waterwheels (together) which I am getting my power from. I have an LV capacitor attached to each and then insulated LV wires connected to the lanterns and gun turrets. If I have the gun turrets switched on, they are constantly draining power until there is none left so when it comes to night time, they can't fire anything. Am I doing something wrong/missing something or is this a bug because it surely shouldn't drain power until it is actually being fired?

**Comment by BluSunrize** [comment]
Yeah, they drain power constantly, because they are on. Turrets don't just need power to shoot, after all they need to monitor the environment for hostiles. That costs power too.

**Comment by hotluck** [comment]
Seems a little excessive a drain for just monitoring. Firing, yes I could understand such a quick drain, but not monitoring. Oh well, thank you for answering my question. I will have to scrap that idea of using gun turrets in my colony.

**Comment by BluSunrize** [comment]
The value is configurable, tbf. You can always turn it down if you want to make it more reasonable...
