### ISSUE TITLE
(Suggestion/Idea):Complete Drill rework

### ISSUE THREAD

**Issue by Wotzinator** [BluSunrize/ImmersiveEngineering#3524]
i have a few suggestions to rework the drill from wich i am aware that they are probably impossible or just not good but ill still post them here in case a few of them are good.

my idea would be firstly to change the drill in the way that it itself becomes more of a chassis that can be customized to suit the current needs of the user (wich would go very good with the addition of the portable engineering table(i forgot its real name)).

in that case there would be 2 new custumiseable slots to it that firstly define wich type of tool it will be and how it will be powered and wich upgrades can be applied.

the first slot would be the head one wich would be able to contain an item that defines the task wich this tool will than fulfill;this head should have a durability and (if its a blockbreaking tool) a harvestlevel also itl change the appearence of the drill in the way that its head changes(for example take a buzzsaw).

the second slot would contain the motor wich could also render in the chassis this part will slightly affect the speed of the tool and also define on wich fuel it will run and also have a few distinct upgrades to each type of engine.for a example there could be the diesel combustion engine wich would mean the drill will get an internal tank and will consume diesel ,then there could be an electric engine consume electricity but it will consume very much off it wich would mean you would need to recharge it very often wich would make it a more "in base use" tool 

those slots coul also have an api wich would allow addon makers to add stuff like lets say steam engines or something like that.

**Comment by LucasQRS** [comment]
this actually is something i wanted to suggest to, but he beat me to it.

anyways the thing i was going to suggest was a chainsaw (or Buzzsaw) that can be placed in the drill slot, like said before, but i believe adding a sweep effect (like swords) would make it an effective killing weapons as well, maybe slower so both drill and saw have the same combat capabilities but in different usages (fast attacks vs area attacks).
