### ISSUE TITLE
[Suggestion]: - Another Set of Ideas

### ISSUE THREAD

**Issue by willvette** [BluSunrize/ImmersiveEngineering#3525]
My Prometheus flame is burning again, with another round of ideas plus ironing out previous ones...
**Pipes**
* Painted Pipes – mostly self-explanatory, they normally behave like RedPower’s insulated wiring, colored pipes can’t normally interact with each other unless overridden by an Engineer’s Hammer.  Unpainted pipes will connect with all colors.  The recipe is like colored wool with 1 or 8 pipes and/around a dye, while a water bucket in place of dye will “wash” any colored pipe(s) clean.
* Pipe Valve – a simple redstone controlled valve facing on one side of the pipe with the remaining sides connectable unless colored.  The control is flat against the block boundary allowing for attachments like a lever, redstone connector, or (if you’re willing to add) a valve handle.  It is made with 2 pipes on either side of an Iron Mechanical Component below Copper Wire on either side of an Iron Rod, producing 2 per recipe.
* Glassed Pipes – similar shape to the Pipe Valve but with a glass face allowing the player to see what’s in a pipe at that moment. It is made with 2 pipes on either side of a Glass Pane, producing 2 per recipe.

**Conveyors** 
I’ve experimented in game and found only scaffolding and glass is accepted material for conveyer belt cover.  So, my suggestion is to allow any block, as defined by a config text, to be used as a cover. Allowing players to hide conveyers in/though walls/floors.
* Strip Curtains – Strip Curtains gain a GUI for mob/item sorting/counting based off mob drops, example: Bone and/or Bow will tell it to send a signal every time a skeleton pass though the Strip Curtains.

**Energy**
* Fuel Generator – IT RUNS ON ETHANOL!  This has been suggested before, including in one of my earlier posts, but a MV generator would make a nice steppingstone between LV kinetic and HV diesel generators.  One fermenter equals enough Ethanol for two Fuel Generators, but Fuel Generators only produce 3/5th the energy needed to keep the Fermenter and Garden Cloches running.  It’ll also run off Gasoline from Immersive Petroleum, more efficiently then the Portable-Generator.
_The Fuel Generator uses Sparkplugs to ignite the Ethanol, which wear out over time with the average being about (IRL) 2 to 3 hours. It creates a headache for the player when the generator scales up in number or is left unattended especially when chunkloading on a server, costing resources to replace each failing plug.  Plug replacement cannot be automated in anyway posable (chest like gui, but no inport/export port), fortunately used plugs can be recycled for a small fraction of investment. The only external indicator of a failed plug is a drop of energy output of 1/8th per failed plug.  
By charging the player an external cost of time and resources, they’ll be inclined toward the completely automatable, and spark plug free, Diesel Generator.  The best way to use the generator is to stockpile the Ethanol using kinetic generators and activate a fuel generator only when more power is needed, like refining ores after a mining trip or getting the intel plant oil production ahead of upgrading to a more long-term power supply._

**Production**
* Stamp-Mill – an early ore yield improver running from LV and a supply of water, as it converts a block of ore into 1 grit and either another grit 45% or sand 15%.  But it often requires stampers to be replaced, costing stone and iron on an Engineer's Workbench.  It’s also loud, obnoxious and hazardous from stone shrapnel, Ear Defenders and armor are a must when near this thing. (obsidian is too hard and neitherrack is too explosive (due to high sulfur content) when stamped)
* Saw-Mill – converts 1 log to 6 planks and 1 sawdust, circular saw often needs replacing.
* Power Loom – the textile industry benefited early in the Industrial Revolution. The Power Loom converts: 6 Hemp Fibers into Tough Fabric, 2 Fibers into String, or 8 Fibers into wool.  It far more efficient at weaving fabric than human fingers.  Yet it can also work other textile recipes found in vanilla minecraft like carpets and banners or added by other mods.

**Armor**
* Clothing – dyeable clothing made from tough fabric and leather, it offers some insulation from electrocutions but not as much as the faraday suit (Clothing removes damage from LV and slightly reduces MV).  Though made of Hemp, it has the appearance of shoes, jeans, button-up shirt, and Fedora. It’s slightly better than iron armor for enchanting.

**Comment by Wotzinator** [comment]
cool ideas

**Comment by Wotzinator** [comment]
but also how about wool spinning in the power loom.so you could make something like a tophat ;i think that would fit better with IE´s style

**Comment by BluSunrize** [comment]
**Painted Pipes:** You can already colour pipes by rightclicking them with dye. Adding special painted pipes would make distinguishing the two too difficult for user convenience. Also it would complicate routing logic.

**Pipe Valve:** Use the search function please.

**Glass Pipes:** Pipes have no internal storage. There is never anything in them.

**Strip Curtains:** They are far too basic to have that level of logic. It should fall to another device to do this sort of sorting, but that is actually on my idea list. Give it time.

**Fuel Generator:** I DON'T GIVE A SHIT IF IT RUNS ON ETHANOL. Stop trying to highlight that every time. I said no.

**Stamp Mill:** No. Ore multiplication is intentionally mid-game. Crusher is a goal to aspire to.

**Saw Mill:** Use the search function or check discord.

**Loom:** I can sorta see it, but with the very limited use of those materials, I'm not sure if it's reason for a full machine. Could be a cool thing for an addon though.

**Clothing:** If I added a fedora, reddit would have a field day. Absolutely not.
