### ISSUE TITLE
[Item Deletion]Time in a Bottle on a External Heater powered FastFurnace deletes items.

### ISSUE THREAD

**Issue by Moleculor** [BluSunrize/ImmersiveEngineering#3526]
**Modpack version**
Enigmatica 2: Expert v1.65d

**Can the issue be reproduced?**
Yes

**Logs**
I reproduced the bug multiple times in the last five minutes, but the logs for the last two hours are just server backups, so nothing about this shows up in the logs.

**Issue**
Apply a [Random Things v4.2.7.1] Time In A Bottle item to a [FastFurnace v1.3.1] Furnace (the one that looks like a vanilla furnace) while that Furnace is heated by an [Immersive Engineering v0.12-89] External Heater.

The furnace will eventually 'blink' off (sometimes rapidly like it's in a rave), deleting input and output contents of the furnace. 

Two applications of the bottle *risk* creating this issue. Three applications almost guarantee it. Four applications of the bottle definitely guarantee it. 

I'm providing links to the issues I've opened in the respective mods just to help everyone out. 

[Enigmatica 2: Expert](https://github.com/NillerMedDild/Enigmatica2Expert/issues/1286)
[Random Things](https://github.com/lumien231/Random-Things/issues/432)
[FastFurnace](https://github.com/Shadows-of-Fire/FastFurnace/issues/13)
[Immersive Engineering](https://github.com/BluSunrize/ImmersiveEngineering/issues/3526)

**Comment by BluSunrize** [comment]
I'm understanding this correctly, time in a bottle makes a TileEntity take multiple ticks, correct?

**Comment by Moleculor** [comment]
¯\_(ツ)_/¯

I'm just an innocent bystander who has never made any Minecraft mod of any type. I know some C++ and a few other languages, but in this, I'm just a user reporting an issue.

You'd likely have to ask over here: https://github.com/lumien231/Random-Things/issues/432

**Comment by BluSunrize** [comment]
Okay, I'll ask again from a users perspective:
Does it make machines go faster?

Because if it does, that's not something the game really intends for, and as such something we don't safeguard against. Also, kinda can't do something about it if it breaks on vanilla-extending furnace. General rule of thumb: Be happy with how fast stuff goes, don't try to accelerate it with some other mods functions.
