### ISSUE TITLE
Crash: when placing Blueprint into the IE Crafting table (1.12.2)

### ISSUE THREAD

**Issue by SirAron111** [BluSunrize/ImmersiveEngineering#3527]
Crash: when placing Blueprint into the IE Crafting table
Sadly didn’t make a crash log but it shows the error in the log at the very bottom never seen thishappen before.
If it actually generates a crash log next time I will add that as well.

### Crashlog:
https://pastebin.com/QPanZSrp

### Versions & Modlist
Forge 14.23.5.2838
Immersive Engineering 0.12 - 89

**Comment by malte0811** [comment]
Update Java to the latest Java 8 build and set the launcher to use it. You're currently using the build included in the vanilla launcher which, while it isn't as old as it used to be, is still a version released in July 2015.
