### ISSUE TITLE
[Suggestion] About cables

### ISSUE THREAD

**Issue by silverwolf1793** [BluSunrize/ImmersiveEngineering#3528]
Many of the people who dislike cables its not because of the zapping thing or the sometimes buggy management of power, its mostly because you cannot use them aesthetically in any interior build, realistically speaking, no one has a bunch of cables hanging out of their walls, maybe you could implement some sort of cable pipes, like those ones in construction while also creating outlets of some kind, that would be in deed cool and realistic, also they are sometimes buggy in the sense that for whatever reason some times plugin nodes loop energy, ie:

I attach 4 generators, then 2 will work but the other 2 will start "charging" because the first two started before the other 2, that would be easily fixed by having an input node, and an output node.

**Comment by BluSunrize** [comment]
No.
Use the search function.

IE will never have power pipes.
