### ISSUE TITLE
Arc Furnace | >Graphite Electrode<

### ISSUE THREAD

**Issue by SunmiCho** [BluSunrize/ImmersiveEngineering#353]
Hi^^
i have a problem, or im just dumb.. 

 i try to craft  >Graphite Electrode< (in multi- and single player) but it won't work :( the output slot is allways gray ._. but Ammo work's ^^

Mod-pack: FTB Infinity 1.7 (v1.10.1)
IE version: 0.5.1

**Comment by BluSunrize** [comment]
There's been another report of this I never really heard from again, so first off, please try updating to the latest IE (0.5.4) and report back if the issue persists? =3

**Comment by SunmiCho** [comment]
okay it works now in Singleplayer ^^ bad thing i have to wait for the next infinity pack update include the new IE version ^^

Thanks for your Help :3 keep the good work ^^
