### ISSUE TITLE
[1.12.2, Forge 2838] Crash on world load

### ISSUE THREAD

**Issue by JackRaidenPH** [BluSunrize/ImmersiveEngineering#3530]
Whenever I try to launch any world(no difference whether it is just or already created) Minecraft crashes: https://pastebin.com/zqghSRc4

Immersive Engineering 0.12-89

**Comment by mindforger** [comment]
There is optifine in that trace, try zu reproduce without

**Comment by JackRaidenPH** [comment]
https://pastebin.com/d91JkDK3 Nothing has changed

**Comment by malte0811** [comment]
Just FYI, we get notifications for all issues, so posting a comment on your old issue #3463 would have worked just as well as closing that one and intentionally creating a duplicate.
