### ISSUE TITLE
World dont load in MC 1.7.10

### ISSUE THREAD

**Issue by Traincrafter111** [BluSunrize/ImmersiveEngineering#3531]
Hi im in MC 1.7.10 and my modpack was fine but I dont know what mod I added that its incompatible with IE and makes my MC stay in Loading world screen and the only thing I can do I close it with Task Manager here is my modpack:

https://pastebin.com/MUNgR3LT

**Comment by BluSunrize** [comment]
Provide a log.

**Comment by Traincrafter111** [comment]
https://www.dropbox.com/home?preview=2019-08-02-3.log.gz

**Comment by BluSunrize** [comment]
That's not how you link other people to your dropbox, for one.
But also, for the convenience of me not having to download and unzip anything, please just put it on pastebin.

All of this is covered in the contribution guidelines, please read them the next time you file an issue.

**Comment by Traincrafter111** [comment]
I tried to paste it on pastebin but it tells me its to big for it

**Comment by BluSunrize** [comment]
How big is the .log file?

**Comment by Traincrafter111** [comment]
3,427,513 bytes

**Comment by BluSunrize** [comment]
Just from launching the game and loading the world? Jesus flipping pancakes.
Grab the first 5000 lines into one pastebin and the last 500 into another. That should work.

**Comment by Traincrafter111** [comment]
nope not even the first 5000 line let me add them

**Comment by Traincrafter111** [comment]
I found a page that supports all the log
https://www.miblocdenotas.com/215936

**Comment by Traincrafter111** [comment]
not wait is not all Ill send u the second part

**Comment by Traincrafter111** [comment]
forget it I cant find a way to send u the log

**Comment by Traincrafter111** [comment]
Thank you anyway I found that IE is incompatible with halocraft but thanks for help
