### ISSUE TITLE
[1.12.2] Excavator crash

### ISSUE THREAD

**Issue by bigenergy** [BluSunrize/ImmersiveEngineering#3532]
### Description of the issue:
Paste excavator and crash client
### Crashlog:
https://pastebin.com/sW5eeVts

### Versions & Modlist
ImmersiveEngineering-0.12-89
Forge 1.12.2 - 14.23.5.2838

**Comment by mindforger** [comment]
does this happen with the standard launcher? (anything besides the vanilla launcher is hardly supported here)
I think i saw this issue earlier but without any additional data or response to questions
so please tell when and how you fixed your issue for future reports!

to put two things to test, remove optifine and foamfix, one by one and try to reproduce the issue and see if it got fixed

it may also be possible that this world got corrupted by the launcher, so it may be required to reproduce this with a new world

last chance would be to delete the block/machine causing the crash (coordinates are in the log) using save game editors like mcedit or if the world loads, with a game command

**Comment by BluSunrize** [comment]
You'll need to give a more detailed description on how this came to be. What where you doing, when did the crash occur, etc.

**Comment by bigenergy** [comment]
I tried to disable optifin, foamfix and other mods
I built an excavator, activated it with a key and can no longer go in

**Comment by BluSunrize** [comment]
Key? IE has no key... unless you are talking about the Engineering Hammer.

One thing you can try is to go into the forge config file (config/forge.cfg) and changing `removeErroringTileEntities` to true. Then launch the world. It might remove that part of the exacavator.

**Comment by bigenergy** [comment]
removeErroringTileEntities already enabled

**Comment by BluSunrize** [comment]
Then you'll need to remove the block with MCEdit, or something similar. The coordinates are in the crashlog, `1335, 71, 713`

**Comment by bigenergy** [comment]
This happens again, my players just collect the excavator and the client crashes
https://paste.dimdev.org/arijevoqel.mccrash

**Comment by bigenergy** [comment]
@BluSunrize If the excavator is at the intersection of two chunks, I get this crash.

**Comment by bigenergy** [comment]
@BluSunrize any ideas?

**Comment by BluSunrize** [comment]
Sponge isn't supported and the log does not feature a stacktrace, so I can't help you there.

**Comment by BluSunrize** [comment]
Also this issue is months old and closed.

**Comment by bigenergy** [comment]
@BluSunrize I told you six months ago that if you assemble a multiblock at the intersection of two chunks it will crash, you just closed the report.  wipe chunk every time is not a solution

**Comment by BluSunrize** [comment]
Yeah, you put it on an issue that was closed for a month back then. I didn't care much.
Our guidelines say that sponge isn't supported.
Reproduce the issue without sponge or it's invalid.
