### ISSUE TITLE
[Suggestion] Scale up fluids/clean up unused slots in JEI

### ISSUE THREAD

**Issue by DaedalusGame** [BluSunrize/ImmersiveEngineering#3537]
Fluids for IE machines are barely visible in JEI right now, I think it would be better if they scaled up to a certain minimum. It would make JEI recipes much more readable. Example, if something produces only 8 mb of seed oil, and the tank in JEI shows a maximum of 16000 mb, it should render atleast 800 mb. Another idea might be to scale it off the highest amount produced by a recipe, so if there's 3 recipes, one produces 80 mb, one 40 mb and one 20 mb, it will show a full tank, a half tank and a quarter tank for those in JEI. 

Additionally it would be good if the unused slots could be removed from the texture in JEI. Maybe the energy bar could actually show much energy will be used by a recipe but that's none of my business.

Pic related:
![javaw_8EIFfMaesh](https://user-images.githubusercontent.com/9559216/63052428-9814df80-bedf-11e9-8b9a-e7e64eef11a9.png)
![javaw_HhMxSdIAEs](https://user-images.githubusercontent.com/9559216/63052436-9cd99380-bedf-11e9-8746-346ccce6551f.png)
![javaw_0IR3JebBJw](https://user-images.githubusercontent.com/9559216/63052441-9fd48400-bedf-11e9-9c6a-718e75047643.png)

Bonus points: these recipes don't fit their allocated boxes in JEI:
![javaw_frevt8RSlC](https://user-images.githubusercontent.com/9559216/63052548-e32ef280-bedf-11e9-969a-a38848992e70.png)
![javaw_nY6qZoS7x2](https://user-images.githubusercontent.com/9559216/63052557-e6c27980-bedf-11e9-8dc5-bc05a76de8e4.png)

**Comment by PrincessRTFM** [comment]
I don't know about removing unused slots from the texture - I feel like barring the inclusion of an image editing library, that'd require a separate texture for everything - but I do like the other ideas!

**Comment by DaedalusGame** [comment]
Yeah, seperate texture is the way to go, other mods already do that kind of stuff.
![squeezer](https://user-images.githubusercontent.com/9559216/63093718-90e4e480-bf66-11e9-9367-2714de81e074.png)
![fermenter](https://user-images.githubusercontent.com/9559216/63093720-90e4e480-bf66-11e9-8823-8e6f82558275.png)
![refinery](https://user-images.githubusercontent.com/9559216/63093721-90e4e480-bf66-11e9-90ac-f09b35b9ce08.png)

**Comment by mindforger** [comment]
as a compromise, how about putting some funnel shaped icons beneath each tank indicator, fully coloring with the liquid inside the tank, this way the actual indicator would still be up to scale and the small funnel would be an adequate content indicator

**Comment by BluSunrize** [comment]
I don't super like the idea of doing separate textures, I think I'll stay with the current ones, becaues it also associates the ingame GUI and JEI display a bit more.
The slots for the Arc Furnace are intentional, because complex recycling recipes may output a bunch of different items, and I dislike the idea of having the slots based on the number of outputs. That would make the JEI display not uniform.
I can definitely look into scaling up the tanks however, and I'll do that for the next release!

**Comment by DaedalusGame** [comment]
> The slots for the Arc Furnace are intentional, because complex recycling recipes may output a bunch of different items, and I dislike the idea of having the slots based on the number of outputs. That would make the JEI display not uniform.

I'm talking about the text and the bottom bit of the slots overlapping the JEI boundary. Just adding a little bit more size to the arc furnace real estate and making the coke oven fuel one fill the entire horizontal strip would fix this

**Comment by TeamSpen210** [comment]
There's another reason to use multiple textures - resource pack support. If you want to change the appearance of JEI's GUI, then you can't alter these to match. In 1.14 for example the 3 different furnaces Mojang added use different GUI textures, even though they're identical.

**Comment by DaedalusGame** [comment]
yeah, multiple textures would also make IE JEI handlers more internally consistent tbh, because the arc smelter and fuel handlers use a different look entirely

**Comment by BluSunrize** [comment]
That is because the Arc Furnace and the Blast Fuel ones don't use textures at all. They just use some slots, which are drawn in code, because fitting the Arc Furnace GUI in there is impossible.

**Comment by BluSunrize** [comment]
^ this commit fixes all the "out of area" issues for the Arc Furnace and Blast fuel. It also changed tick-based measurement to show up in Seconds instead, since that is more user friendly.

Tank sizes have been adjusted, most of them are now automatically generated as "4 times the amount produced". This results in all amounts looking the same. It's not idea either, but at least the fluid is visible now. And there's no real other way to do it.
