### ISSUE TITLE
[1.12.2] Engineering Manual is missing recipes

### ISSUE THREAD

**Issue by Dogsteeves** [BluSunrize/ImmersiveEngineering#3542]
I am trying to play a one mod series no JEI none of the quality of life mods. I am just your Immersive engineering mod. Well playing your mod I got stuck on Copper Coil Block they aren't found anywhere in the Engineering Manual.  I had to go into the FTB wiki just to find out how to construct it.

**Comment by mindforger** [comment]
press f3 + c until your game forcibly crashes and then pastenbin the crashlog to get an idea of your setup please :) .. works only when ingame not in titel

**Comment by malte0811** [comment]
I'm not sure what you want a crashlog for @mindforger. As far as I can see in the code we simply don't add that recipe to the manual, so surely the setup is totally irrelevant? Or did you interprete the issue as "all recipes are missing from the manual"?

@Dogsteeves the vanilla recipe book should work as a replacement for JEI, at least for crafting recipes, without you needing to look up recipes online.

**Comment by mindforger** [comment]
>all recipes are missing from the manual

kindof, but now i realize i misread the "one mod series" for a "series of mods"

**Comment by BluSunrize** [comment]
Yeah I'm gonna go with Malte here, vanilla has a recipe display system. JEI is way nicer, but vanilla provides you a far more immersive option than looking it up online.
