### ISSUE TITLE
[1.12.2] Pipes stop pumping fluid after chunks unload

### ISSUE THREAD

**Issue by DoomRater** [BluSunrize/ImmersiveEngineering#3545]
### Description of the issue:
When I unload the chunks that pipes sit in, all flow of water stops.  I am attempting to pipe in water to Ex Nihilo Creatio barrels so that I can turn dust into clay, turn concrete powder into concrete.  However, both of the following setups stop working when the chunks unload:
Setup 1: a Fluid pump keeps a fluid tank full, and a constant redstone signal then pumps water into the barrels in a diagonal chunk over.
Setup 2: Mostly the same as setup 1, with an added cache of Treated Wood Barrels full of water in between the pipeline from the tank outside, and the pipeline that leads to the Ex Nihilo barrels.  However, when the chunk is unloaded this time, the pipes leading the wooden barrels into the pipeline to the Ex Nihilo barrels stop working, and it becomes an even bigger pain to update them so they realize they're actually connected to something and start filling up with water.
 The last available workaround I can come up with is updating them with a redstone signal, which hopefully provides a temporary fix for the automation setup.

### Versions & Modlist
Forge: 14.23.5.2838
IE: 0.12-89
Ex Nihilo Creatio: 1.12.2-0.4.5

**Comment by mindforger** [comment]
Well that is the purpose of unloading chunks, they are not being processed to reduce load. You should use chunkloaders to keep chunks loaded that you want stuff to be working in. I am not sure what you are expecting else

**Comment by DoomRater** [comment]
Perhaps I was not clear.  The behavior persists after the chunks are loaded
again by a player.  They appear to be connected but will not move fluid.

**Comment by mindforger** [comment]
ah okay that wasn't clear for me, thank you ^^

**Comment by BluSunrize** [comment]
So the way I understand this (a few pictures would have been helpful), it is always the pipe that leads into the ExNihilo barrel that breaks?  
Either you have a direct pipe into the ExNihilo barrel - that breaks  
Or you have two pipes, using an IE barrel in between - only the side leading into ExNihilo breaks

Concluding from that, it could quite possibly be an issue with ExNihilo? Because afaik, the setups described should work fine with other recipients (such an as IE machine, or another mod's)

**Comment by mindforger** [comment]
additional question, single player or server and which kind of server (spigot, plain forge, sponge?)

**Comment by DoomRater** [comment]
I was tired last night and didn't think to take screenshots of the setup.  This is on a forge server with no additional plugins.  Additionally, I can test the world in a singleplayer instance and see if I can cause the setup to fail to work by leaving the chunks, saving and quitting, then coming back.  Pics coming soon.

**Comment by DoomRater** [comment]
https://imgur.com/a/P3jAfEq

The only seeming connection between the setups that work and the setups that don't is that the setups that don't have pipes covered in scaffolding.

**Comment by malte0811** [comment]
You say that cycling the redstone signal on the tank fixes the issue? What is providing the signal? A vanilla lever or something else? If the pipes were the issue I don't see how cycling the tank's signal could fix them.

**Comment by DoomRater** [comment]
In the first setup I described that worked.  The first setup does not have the wooden barrels (the pipes simply ran into the Ex Nihilo Barrels).  I added the wooden barrels to the pipeline thinking it was the tank or possibly a chunk border issue, and afterwards cycling the redstone signal on the tank did NOT fix the issue anymore.

**Comment by swhitsonpmc** [comment]
FYI, I've also experienced the same issue in 1.12.2. Engineering hammer on any of the pipes in the chain will resolve the issue. I even found that simply applying or even removing a redstone signal next to the pipes will fix the issue.
