### ISSUE TITLE
Concrete Doors make a different sound when opened by redstone signal

### ISSUE THREAD

**Issue by DoomRater** [BluSunrize/ImmersiveEngineering#3546]
### Description of the issue:
When opening a Concrete Door, it makes a stone like sound.  But when a redstone signal opens it, it sounds wooden.

### Versions & Modlist
IE 0.12-89

**Comment by malte0811** [comment]
As far as I know we don't add any concrete doors. You should probably report this to [Engineer's Doors](https://www.curseforge.com/minecraft/mc-mods/engineers-doors/issues).
