### ISSUE TITLE
[1.12] Redstone wire issue when server is restarted

### ISSUE THREAD

**Issue by ikemann61** [BluSunrize/ImmersiveEngineering#3547]
I am having an issue with redstone wires and connectors. Everything works normally when I wire things together, however when the server is restarted I get a message that I can not place wires down on connectors and no signal passes through the wires. The regular power wires work just fine. 

This doesn't cause crashes or the game to be unstable I just have to rewire everything  every time the server is restarted.

![redstone wire issue](https://user-images.githubusercontent.com/54785389/64086895-94f75d00-ccef-11e9-9eca-304bfe00eb7e.png)

I am running the mod pack All the Mods 3 version 5.12.1

**Comment by malte0811** [comment]
This is most likely caused by Immersive Tech. I've added a workaround for the root cause of this and quite a few other issues for the next build of IE.
