### ISSUE TITLE
Conveyor belt not working while going up

### ISSUE THREAD

**Issue by Someweb** [BluSunrize/ImmersiveEngineering#355]
I'm having issues with the conveyor belt not working properly when moving up 1 or more blocks.
The block seems to get stuck on the edge and just sort of float there.

Removing the block under the belt allows for the entity to fall through the conveyor belt to the underlying block.

**Comment by theunkn0wn1** [comment]
Was unable to reproduce with [IE version 0.5.4](3a084127af659be57a02a9cdba9169ff44f2e749)
![image](https://cloud.githubusercontent.com/assets/3110986/9504747/19152414-4bf3-11e5-9e37-8f6ff252a970.png)
============
Can we get a screanshot of your setup and IE version?

**Comment by Someweb** [comment]
![2015-08-27_20 17 45](https://cloud.githubusercontent.com/assets/4448375/9529116/d3bfb940-4cf8-11e5-9c67-8c5e6d625ee5.png)
![2015-08-27_20 18 39](https://cloud.githubusercontent.com/assets/4448375/9529117/d3d908fa-4cf8-11e5-856a-aed9fc5e6e26.png)

This is a quick test setup and also using IE 0.5.4 (latest version)

**Comment by theunkn0wn1** [comment]
Still unable to reproduce :confounded: 
![image](https://cloud.githubusercontent.com/assets/3110986/9529790/1d12a758-4cb1-11e5-800f-45738f5066d0.png)
Freshly built IE Version 0.5.4 from source SHA c4981642ac320ae8181aae3d147a9c3a4836a01e

Not sure shats going on there

**Comment by BluSunrize** [comment]
Tried all for directions with the exact setup pictured. Couldn't reproduce either.

**Comment by Someweb** [comment]
As soon as I get the time I'll try find out what mod combination is causing this. Any advice on how to go through ~150 mods

**Comment by cobra** [comment]
Well, the most simple method is a binary search. Disable half of them (respecting dependencies and keeping IE, of course) and test again. Does it still happen? It's one of those 75 mods, disable half of those, test again. Doesn't it happen? Must be one of the other 75; disable your enabled one, enable the disabled ones, test again (just to be sure that it's not a combination of a disabled and enabled mod), then disable half of those. Repeat.

**Comment by BluSunrize** [comment]
unreproduceable, hence closed.
