### ISSUE TITLE
[1.12.2] SkyHook Breaking Game

### ISSUE THREAD

**Issue by DDX5** [BluSunrize/ImmersiveEngineering#3552]
description of the issue. The moment that I go to use the skyhook it triggers a concurrentmodification exception. Just to help there are 2 mods active Optifine HD_U_E3 and immersive engineering. running version 0.12-91, forge version: 1.12.2-14.23.5.2838-universal

Crash report link: https://gist.github.com/DDX5/73dc2354356c734145168198ed31f5c6

**Comment by malte0811** [comment]
We usually don't support OF, but I think I know what causes this issue and how to fix it. ([Note to self](https://github.com/BluSunrize/ImmersiveEngineering/blob/08fef206c7b9deef736b8fab5daafcf190411f67/src/main/java/blusunrize/immersiveengineering/common/entities/EntitySkylineHook.java#L128))

**Comment by DDX5** [comment]
Ok that's great sorry for not being on for a couple of days my network card is playing up
