### ISSUE TITLE
Missing Crafting Recipe for Engineer's Blueprint Arc Furnace Electrodes

### ISSUE THREAD

**Issue by GamerbyDesign** [BluSunrize/ImmersiveEngineering#3555]
The Engineers Blueprint Arc Furnace Electrodes does show up in JEI, however when you click on it the only Engineer's Blueprints that show up are for the Metal Molds, Crafting Components, & Common Projectiles.

MC 1.12.2
Forge 14.23.5.2845
IE 0.12-91
JEI 4.15.0.289

**Comment by TeamSpen210** [comment]
There's a good reason for that - those cannot be crafted. The only way to obtain those (and Specialised Projectiles) is to trade with Villagers.

**Comment by gellis12** [comment]
There's already a config option for this (arcfurnace_electrodeCrafting), and it's disabled by default.

**Comment by BluSunrize** [comment]
Issue should be answered
