### ISSUE TITLE
startup crash 1.12.2 forge 

### ISSUE THREAD

**Issue by LauraDarkez** [BluSunrize/ImmersiveEngineering#3558]
### Description of the issue:
using forge 1.12.2 14.23.5.2768, it crashes on startup. bringing up this crashlog

### Crashlog:
<script src="https://gist.github.com/LauraDarkez/7c0c4a378624f7e845ef618b0720b44b.js"></script>

### Versions & Modlist
ie  0.12-91 and forge 1.12.2-14.23.5.2768

**Comment by wamc2017** [comment]
Hmm, looks like IE was built with forge 14.23.5.2838.
https://github.com/BluSunrize/ImmersiveEngineering/blob/08fef206c7b9deef736b8fab5daafcf190411f67/build.gradle#L30

Try updating to this version and see if it still crashes...

**Comment by malte0811** [comment]
^That. Anything above Forge 2820 should work.

**Comment by Strichcode92** [comment]
Mute this thread please
 

Gesendet: Dienstag, 10. September 2019 um 07:31 Uhr
Von: "malte0811" <notifications@github.com>
An: BluSunrize/ImmersiveEngineering <ImmersiveEngineering@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [BluSunrize/ImmersiveEngineering] startup crash 1.12.2 forge (#3558)


Closed #3558.

**Comment by mindforger** [comment]
@Strichcode92 you have to unsub or mute yourself
