### ISSUE TITLE
Wire render issue

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#356]
Issue: Wires do not render
====================
When using wires between two points, at any slope (or the lack thereof) the wires are invisable
The connection is still valid, conducting power between the points

Steps to reproduce
---------------------
[1] Load any world
[2] place two wire connectors\relays apart, but within LOS of one another
[3] create valid connection between connectors

Aux.
------------------
![image](https://cloud.githubusercontent.com/assets/3110986/9505013/b383d148-4bf4-11e5-9f35-e8c06725b80a.png)

Version Data:
===========
0.5.4 3a084127af659be57a02a9cdba9169ff44f2e749
FTB Infinity 1.10.1 no modifications

**Comment by BluSunrize** [comment]
Try LV. I think Github still hasn't got the change where I added ISRBH renderinh for the other connectors. x3

**Comment by theunkn0wn1** [comment]
LV works correctly. MV and HV encounter the above error

**Comment by BluSunrize** [comment]
Yeah, all fixed, await the next commit
