### ISSUE TITLE
[REQUEST] Steel Armor (As per discord)

### ISSUE THREAD

**Issue by Voxel-Friend** [BluSunrize/ImmersiveEngineering#3563]
Posting issue here to remind Blu, as he requested on discord.
```But to be honest, as generic and uninspired as it may be, the biggest thing I would want would be just plain steel armor. I really just run IE, it's addons, and some qol mods and that's it, so an in-mod, non vanilla,  combat-viable armor is really my biggest want. ```

**Comment by BluSunrize** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/cb6bd26cc397abebff90fa0fce4af7ff72324f2a

Done
