### ISSUE TITLE
[Bug][1.12.2] HV wire still kill after breaking relay and obtained HV wire item

### ISSUE THREAD

**Issue by alpha8196** [BluSunrize/ImmersiveEngineering#3565]
As title, there was this connected and powered HV wire, after I broke one of the connector and
all the expected items (a connector and two wires) are dropped, I walked in a space where it once was and died instantly
I've tried putting a block and break it, but still got killed, I also got killed in one hit instead of two (as it should only deal 7 heart/hit)

Version: 
IE: 0.12-89
Forge: 1.12.2-14.23.5.2818

**Comment by malte0811** [comment]
Try updating IE to build 91. There's a chance a fix I added in 90 will apply to this situation as well as to many others.
