### ISSUE TITLE
Fire Rate Modifiers don't add up correctly

### ISSUE THREAD

**Issue by ChrisEntropy** [BluSunrize/ImmersiveEngineering#3566]
I created a revolver with special components bought from a villager. I had a Drum with 53% fire rate improvement, a Barrel with 73% fire rate improvement and a hammer with 66% fire rate improvement. The resulting revolver only has a fire rate bonus of 96%. 
Meanwhile the luck mali correctly add up, in this case to 522%. Is there something in the calculation, that I am not getting? Shouldn't the fire rate also add up, in this case to a total of 192%?

**Comment by BluSunrize** [comment]
Nope.
They value combination for each perk is different. Luck is additive, Firerate and noise and multiplicative.
This is intentional.
