### ISSUE TITLE
[1.12.2] mod version [0.12-91] Forge version [14.23.5.2838] item desync with tools on dedicated server

### ISSUE THREAD

**Issue by Lucidcream** [BluSunrize/ImmersiveEngineering#3567]
Forced crash for mod list and versions:
[https://paste.dimdev.org/etekawahob.mccrash](url)

Severe item desync with tools such as the railgun and the revolver. I'm able to place shaders and upgrades unto weapons but after taking the tool out of the workbench and using it, the tools do not apply the intended the effects of the upgrades. When placing the tools back in the workbench the upgrades, but not the shaders, are gone, I've tried to pull the upgrades out but they seem to be gone forever. 
Specifically with the revolver, I am able to dupe the first cartridges I placed in the revolver by firing once and taking them out. 
The railgun shows the zoom hud but will not zoom even when it has the upgrade to do so, attempting to change the zoom level does not work.
Other tools may also have unexpected behaviour but I have not tested the chemical thrower or the mining drill.

Link to railgun zoom bug and revolver ammo duping.
[https://giphy.com/gifs/U6SDFMkLdaTRyCuJbd](url)

**Comment by BluSunrize** [comment]
Are you running Sponge on the server?

**Comment by Lucidcream** [comment]
I had installed it but removed it later

**Comment by bobodoustaud** [comment]
So it’s a sponge error?
