### ISSUE TITLE
Arc Furnace missing blocks in book/Excavator Not being able to build

### ISSUE THREAD

**Issue by OldGreg213** [BluSunrize/ImmersiveEngineering#357]
![0ac4c08d277e034ec647bfd4c4b0e8d4](https://cloud.githubusercontent.com/assets/13990470/9510416/6b5c2c22-4c39-11e5-99e2-786c05b7abcb.gif)

As seen above its missing two blocks of steel, I tried making it for hours until I watched how its actually made in a LP.

https://gyazo.com/b389c839da9aeb5c6cd9b145d35554f0

The gif above said it was too big to upload :(

I built it exactly how it is in the book.

I'm using Infinity 1.10.1

IE Version 0.5.1

**Comment by theunkn0wn1** [comment]
Please update to the latest versions, 0.5.2 and above use a modified the ARC Furnace structure. This issue is a duplicate.

**Comment by BluSunrize** [comment]
Yeah, fixed ages ago, update your IE.
