### ISSUE TITLE
[1.12.2] Suggestion: Thermoelectric Generator is less powerful at high altitude

### ISSUE THREAD

**Issue by ExDomino** [BluSunrize/ImmersiveEngineering#3574]
Hello,

My idea is to make that the Thermoelectric Generator generate only its maximum of RF/t at the height of the bedrock and generate less energy when placed above.

For example, it could generate full power at bedrock (around y=5) and generate no power at all at high altitude (round 60 or 100).

Because this generator is really too powerful at this moment.
Thank you in advance!

**Comment by jrwizzard** [comment]
How does your idea work in the nether, ya know, cause bedrock is up and not down there...?

**Comment by PrincessRTFM** [comment]
The nether has bedrock above and below, but more importantly they specified Y levels as well. I think a better question is how should it work in a literal hell dimension where water can't even exist in liquid form.

**Comment by ExDomino** [comment]
The generator could work at maximum everywhere in the nether because it's already hard to bring cold liquid here.

**Comment by BluSunrize** [comment]
The generator is perfectly fine the way it is right now, I see no reason to nerf it. It's no more egregious than various other methods of power generation available in modded Minecraft. Also, it's output is adjustable in the config anyhow.
