### ISSUE TITLE
Floodlight Stops working after The update before the Newest update

### ISSUE THREAD

**Issue by win10Device** [BluSunrize/ImmersiveEngineering#3579]
After I updated to the newest update the game would not start due to missing villager file
(My mod set can't add the file) so what I did is downgrade to the update just before the Newest update and I wanted to add floodlights to my space station but it didn't work so I went to the overworld to test it to see if it would work but it didn't
I did a recorded me trying to get it to work
https://drive.google.com/file/d/1-0aTX5FNxyXg0iPGtYJJXgKxx4zQXHcx/view?usp=sharing

**Comment by BluSunrize** [comment]
You need to tell us exactly what verison this is. Saying "the last one" isn't good enough.
Please read the contribution guidelines, and produce a debug crashlog. Put that on pastebin and link it here.

Also, see if you can replicate this with just Immersive Engineering and no other mods installed.

**Comment by win10Device** [comment]
Sorry for been Late to replay, But you have Fix the Bug Anyway, Thanks!
