### ISSUE TITLE
Blocks and wires don't update with sponge forge

### ISSUE THREAD

**Issue by Platipucat** [BluSunrize/ImmersiveEngineering#3586]
I'm using sponge forge on my server and a lot of the blocks from this mod don't function correctly or at all with sponge installed for example wires don't deploy until there is block update nearby and the powered lantern don't produce light at all..
I'm not sure if you are aware of those issues

**Comment by BluSunrize** [comment]
Oh yes, we are very aware of the issues, and so would you be, if you had read the contribution guidelines, rather than just ignoring the issue template.

https://github.com/BluSunrize/ImmersiveEngineering/blob/master/CONTRIBUTING.md#other-mods
