### ISSUE TITLE
[1.12.2] Graphical glitch with posts and Optifine

### ISSUE THREAD

**Issue by Federsavo** [BluSunrize/ImmersiveEngineering#3587]
Using smooth lightning level at 100% cause strange shadows on posts. If i lower it to 40% it goes away.

![2019-10-20_14 13 50](https://user-images.githubusercontent.com/29519894/67159371-e57c5580-f343-11e9-9141-68931b423055.png)

I used a fresh instance with:
ImmersiveEngineering-0.12-92
jei_1.12.2-4.15.0.291
Optifine_1.12.2_HD_U_E3

Forge-14.23.5.2847

**Comment by BluSunrize** [comment]
Optifine is not supported, as detailed in the contribution guidelines

https://github.com/BluSunrize/ImmersiveEngineering/blob/master/CONTRIBUTING.md#other-mods

**Comment by Federsavo** [comment]
Sorry for the bothering
