### ISSUE TITLE
[Suggestion] charging station lights

### ISSUE THREAD

**Issue by LucasQRS** [BluSunrize/ImmersiveEngineering#3588]
a very small suggestion

i observed the charging station has 3 lights that all light up and change from red to green as the item is charged, but i thought it was kind of redundant (not because of design but functionality), so i had the idea of separating them like so:

1st: turns green when connected to wires and receiving energy
2nd: turns red when there's an item charging and only turns green when fully charged (maybe emitting a redstone signal)
3rd: behaves normally like the ones now

**Comment by BluSunrize** [comment]
No, the lights are fine as is. Plus, we can't easily detect "connected to wires and receiving energy", because as soon as the buffer is full, it's no longer receiving energy.
