### ISSUE TITLE
[Suggestion] Chemical Thrower liquid that kills leaves/trees

### ISSUE THREAD

**Issue by MartinFNV** [BluSunrize/ImmersiveEngineering#3589]
Me: "what if the chemical thrower removed leaves off trees when using a certain liquid? :thinking emoji: "
Enheldor:  "agent orange when?"
BluSunrize: "A deforestation agent is a fucking wild idea and I love it. Someone throw that on the issue tracker, because I'm at work right now and can't."

**Comment by MalkContent** [comment]
(make it turn sapling drops into slime instead)

**Comment by BluSunrize** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/6790a4f5749cbc5b25e6428965f488f99b16a9f3
