### ISSUE TITLE
Getting stuck in chutes with a bend at the bottom.

### ISSUE THREAD

**Issue by TwistedGate** [BluSunrize/ImmersiveEngineering#3590]
### Description of the issue:
Falling into chutes with the "bendy" piece at the bottom causes one to get stuck without being able to get out, character starts twitching around giving no chance of breaking any blocks.

When teleporting out of it i died because i "fell from a high place". Suggesting that you're literaly falling infinitely.

### Crashlog:
/

### Versions & Modlist
IE 0.12-92
Forge 1.12.2 14.23.5.2847

Edit by @malte0811: Server version of IE was d375409039af1b0163e7dbad8a137c0fa010127d

**Comment by TwistedGate** [comment]
Image of the chutes setup i got stuck in. If that helps.
![2019-10-27_20 28 44](https://user-images.githubusercontent.com/31029668/67640338-4f739c80-f8fa-11e9-857b-3aee07b97746.png)

**Comment by Meserion** [comment]
I didn't even know you could fall in, maybe you should be able to set the 2nd block from the bottom to be open like the bendy bit so its a 2-high space.

**Comment by Pultex** [comment]
funny you can fall in them
