### ISSUE TITLE
[Suggestion] Chemical Thrower fill in creative

### ISSUE THREAD

**Issue by DarkEyeDragon** [BluSunrize/ImmersiveEngineering#3594]
I noticed that you can't actually fill the Chemical Thrower by right clicking tanks while in creative. It drains the tanks but doesnt fill it.

So my suggestion: Make the Chemical Thower fill even in creative and maybe make its actual fuel infinite.

![Behavior](https://i.imgur.com/tpMJKVa.gif)

**Comment by BluSunrize** [comment]
That's default behavior for fluid containers in creative mode. It also affects buckets and everything else.
Working around it is more effort than it's worth. Just switch out of creative =p
