### ISSUE TITLE
[Request] Add a "scarcity oriented" mode for the garden cloche

### ISSUE THREAD

**Issue by 0UtK4st** [BluSunrize/ImmersiveEngineering#3596]
First of all, thank you for your wonderful mod.
So, I'm a fan of the garden cloche, but it seems to me that it completely devoids the gameplay of any need to actually worry about food. Mods such as Harvestcraft really don't mix well with IE because there is no incentive to try and be creative with your meals due to how easy it is to keep Steve well-fed, even with mods as hunger overhaul. Sure, not starving in the base game was not hard at all, but the cloche seems to simply do a lot for how cheap it is. I mean... even now that it is not as fast as it once was, a single one can easily keep a player fed, and it even harvests automatically.
As such, I ask you to please place an option in a config file to make it more balanced. Namely, in perfect conditions, a crop usually takes ~31 minutes to grow in Vanilla MC. If the cloche halved that time, it would already be absolutely viable and, in my opinion, would also work better in the way of immersion.
Best regards

**Comment by CelestialPhoenix** [comment]
There are some config options for it- its called 'belljar' rather than 'cloche'

```       
 # A modifier to apply to the belljars total growing speed
        # Min: 0.001
        # Max: 1.7976931348623157E308
        D:belljar_growth_mod=1.0

**Comment by 0UtK4st** [comment]
Thanks a lot! Sorry, I hadn't quite made the connection.
