### ISSUE TITLE
[1.12] Metal Press ZenScript ignores NBT for inputs

### ISSUE THREAD

**Issue by SimonMeskens** [BluSunrize/ImmersiveEngineering#3597]
Forge version: 14.23.5.2847
IE version: 0.12-92

As per title. I have several items that differ only in NBT and I want them to be processed differently, but it seems like NBT is not used for Metal Press recipes for inputs. Contrived example:

```cs
mods.immersiveengineering.MetalPress.addRecipe(<minecraft:diamond>, <minecraft:diamond_sword>.withTag({display:{Name:"Sword of Power"}}), <immersiveengineering:mold:7>, 2400, 1);
mods.immersiveengineering.MetalPress.addRecipe(<minecraft:emerald>, <minecraft:diamond_sword>.withTag({display:{Name:"Sword of Weakness"}}), <immersiveengineering:mold:7>, 2400, 1);
```

Both of these output a diamond

**Comment by jonthemoron** [comment]
Seconded

**Comment by Sindarin** [comment]
I, too, would like this to be implemented. It allows for better integration with other mods that have items with NBT.
