### ISSUE TITLE
[1.12.2] Dedicated server crashing on load

### ISSUE THREAD

**Issue by Lyokanthrope** [BluSunrize/ImmersiveEngineering#3598]
Server's crashing on load as soon as it starts ticking blocks.
Forge version: forge-1.12.2-14.23.5.2847-universal
IE version: 0.12-92

Server was (mostly) fine until now, not entirely sure if it might be a compatibility issue or elsewise.

Last thing I heard from one of my players was this:
"For the record, the last thing I did was shift right click on a high voltage capacitor with a engineers hammer equipped while at the space station which is uh, odd thing to do a crash but yeah" 

Crash log: https://paste.ubuntu.com/p/NV2gJWZKPP/

**Comment by malte0811** [comment]
Can you try to figure out what's next to the capacitor (the capacitor is at -1,68,0)? It looks like that block isn't implementing energy capabilities correctly. For now I recommend using some external program to delete the crashing capacitor. Forge has an option to remove "erroring tile entities" as well, but I don't know whether that would apply here.
