### ISSUE TITLE
Not sure if this is Immersive Engineering or not

### ISSUE THREAD

**Issue by DoughnutDev** [BluSunrize/ImmersiveEngineering#36]
http://pastebin.com/HSbUKAL7 Happens when I load my base.

**Comment by BluSunrize** [comment]
With the clusterfuck of mods in there: No idea.

**Comment by DoughnutDev** [comment]
http://pastebin.com/0KpW6JEr sent the wrong crash report sorry.

**Comment by DoughnutDev** [comment]
It has something to do with MV wire connectors
