### ISSUE TITLE
Wooden post render issue

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#360]
Issue: wooden posts do not render correctly
================
The aux. arms of the wooden posts do not render at all

Steps to reproduce:
---------------------
[1] place wooden post
[2] use hammer (right click) onto one side of the wooden post

Aux.
------------------
![image](https://cloud.githubusercontent.com/assets/3110986/9529392/d9d0bdf6-4cae-11e5-86be-d872c48a467c.png)

Version info
---------------
IE version 0.5.4 c4981642ac320ae8181aae3d147a9c3a4836a01e

**Comment by BluSunrize** [comment]
Can't reproduce that one .-.

**Comment by theunkn0wn1** [comment]
Am able reproduce it, trying to figure out what i am doing in exact terms to induce this... will update once i figure that out

**Comment by theunkn0wn1** [comment]
OK, issue is readily reproducible at y level 111 on a fresh world.
The above steps are valid, i'm doing nothing fancy here
