### ISSUE TITLE
Metal Press Conveyor Issue

### ISSUE THREAD

**Issue by aikainnet** [BluSunrize/ImmersiveEngineering#3604]
Playing Dungeons Dragons and Space Shuttles version 6.3
Forge version 14.23.5.2836
Immersive Engineering version 0.12-92

Upon breaking the Metal Press multiblock, the conveyor belts change into tile.immersiveengineering.conveyor..name and no longer function as conveyor belts at all. They also will not allow me to remake the metal press by reusing them. I have to use a new pair of conveyor belts.

F3+C = https://paste.dimdev.org/ixavinamer.mccrash
Image: https://imgur.com/a/JxAFLHl

**Comment by mindforger** [comment]
>Other mods should be listed (with their versions) in a pastebin or gist upload. The easiest way to get these lists is a crashlog, you may force one with F3+C.
If your game crashed (see above) you may omit the modlist, but IE and Forge version would still be nice.
Also, please try testing an issue in a minimal instance, with just IE, Forge and maybe JEI. That makes elminating compat issues easier.

**Comment by aikainnet** [comment]
I had added a crashlog with the first posting, along with an image.

**Comment by mindforger** [comment]
what tool did you use to break the machine? Did the conveyor drop like that or did they just vconvert to those placed blocks?

**Comment by aikainnet** [comment]
Pickaxe and it just converted like that.

**Comment by bigenergy** [comment]
Will there be a fix? I am experiencing the same problem

**Comment by BluSunrize** [comment]
The issue isn't reproducable on my end, and I have yet to see it happen in an instance with just IE. Currently the suspicion is cross-mod interaction, which we can do farely little about.

**Comment by forresthopkinsa** [comment]
Reproducible with Astral Sorcery *and* SpongeForge installed. Will find more info and report back.

**Comment by BluSunrize** [comment]
Don't bother unless you are reproducing it in 1.16, we are no longer offering support for versions below that.

**Comment by forresthopkinsa** [comment]
In my case, I was able to work around the problem by breaking the metal press from anywhere except the center block.

**Comment by osirisgothra** [comment]
confirmed Project Ozone 3: Mythic Mode, even if this is not the latest and greatest version, code authors should at the very least have some sort of backport.  This was also confirmed a bigger problem in Multiblock Madness, as the conveyors not only changed, but were then frozen and could not be broken at all, forcing player to move to a new place and having to build a house around the ugly checkered belt that sticks out like a sore thumb (I tried every modded exchanger, mover, pickaxe, breaker, etc. none work) ; ) - If I had to guess, I would think the belt was recreated after breaking but didn't get its data to identify it, kind of like an empty struct of sorts.  This happens even if you use the engineer's hammer to break the machine, so it is definitely _not a tool-specific problem_.

**Comment by mindforger** [comment]
the issue is 2 years old, make a new one, make sure to follow the guidelines and link this issue in the new issue

**Comment by BluSunrize** [comment]
> code authors should at the very least have some sort of backport. 

No, we shouldn't. That's why we stop support for old versions, so that we explicitely do not have to maintain them anymore.
This is my fucking hobby, not my job. You don't to demand anything from me.
