### ISSUE TITLE
[1.12-92] Fluid Pipes render issue

### ISSUE THREAD

**Issue by raymondbh** [BluSunrize/ImmersiveEngineering#3606]
Fluid pipes looks unconnected between chunks when restarting server/world.
Pipes works as they should, but it does not look good...

https://imgur.com/a/NRlyK1h

Tested with Forge 14.23.5.2846 and just IE 1.12-92

**Comment by Pultex** [comment]
seems the render issue I have with lighting is effecting all graphical render with the mod, maybe FORGE changed something and is making render wrong.

**Comment by stfwi** [comment]
Subscribe, same effect and version. The log does not show anything suspicious in that matter.
[2019-12-21-gamelog.zip](https://github.com/BluSunrize/ImmersiveEngineering/files/3991390/2019-12-21-gamelog.zip)
![2019-12-21_12 53 03](https://user-images.githubusercontent.com/28822525/71308088-34a03e80-23f8-11ea-8bbb-386fef3deae9.png)

**Comment by stfwi** [comment]
I can't get the 1.12 project to build, but made some experiments to provide some more data: 
- The locations are very repeatable, but not 100%, rarely it renders correctly.
- The missing pipe pieces appear only to be in x+ or z+ direction (as shown in the screen shot).
- Does not happen when resource reloading, only on quit->reload.

![2019-12-test-piperender](https://user-images.githubusercontent.com/28822525/71312163-089cb180-2428-11ea-9f61-f50faa6372c1.png)
