### ISSUE TITLE
Server launch crash with newer DANKnull and p455w0rdslib

### ISSUE THREAD

**Issue by Pultex** [BluSunrize/ImmersiveEngineering#3608]
### Description of the issue:
Crashes with use of p455w0rdslib-1.12.2-2.2.156 and newer 
part of DANKnull

### Crashlog:
https://gist.github.com/Pultex/c9bf1c2e3279a315392765a06b1ba211

### Versions & Modlist
Minecraft 1.12.2
Forge 1.12.2-forge1.12.2-14.23.5.2847

Immersive Engineering 0.12 - 92
p455w0rdslib-1.12.2-2.3.159
DankNull-1.12.2-1.7.84.jar

modlist in crash log?

maybe a work around as it seems to be shader light based in the log

**Comment by BluSunrize** [comment]
Not an IE issue. Happens due to p455w0rdslib ASMing into the render code.
Not on out end.
