### ISSUE TITLE
[1.12] Immersive Engineering Crates Delete Items upon Holiday Season

### ISSUE THREAD

**Issue by thakyZ** [BluSunrize/ImmersiveEngineering#3609]
### Description of the issue:
When the built in season timer changes to the holiday season (Christmas) and the storage crates are supposed to change texture, it clears all items from them and changes texture.

### Crashlog:
No crash upon this happening

### Versions & Modlist
Minecraft Forge: `14.23.5.2847`
Immersive Engineering: `0.12-92`
Mod Pack: `Dungeons, Dragons & Space Shuttles`
Mods List: [crash report with F3+C](https://paste.dimdev.org/wezimorasu.mccrash)

**Comment by BluSunrize** [comment]
The textures have zero impact on their functionality, so these two things shouldn't be related.
Can you reproduce this reliably by changing your system time?

**Comment by thakyZ** [comment]
Sure I will test to see if it does it.

**Comment by thakyZ** [comment]
Nevermind it was probably something else.
