### ISSUE TITLE
1.12.2 Immersive Engineering 0.12 - 92 memory access violation from shaders

### ISSUE THREAD

**Issue by Pultex** [BluSunrize/ImmersiveEngineering#3610]
### Before reporting:
The issue is some what random as it happens some times not others with all the same mods running
may not even happen on chunk load but several seconds after

### Description of the issue:
on entering an area with Immersive Engineering lamps render causes a shader based memory access violation
the game freezes and will not continue requires forced server shutdown/restart
### Crashlog:
the log did not save

### Versions & Modlist

look at Enigmatica 2: Expert

Question:
could there be a way to turn off the light render changes from the mod so it could just be avoided

**Comment by BluSunrize** [comment]
If "the log didn't save", you have to reproduce the issue and make it save.
I'm not gonna install a modpack to debug this.

**Comment by Pultex** [comment]
I have the error this is all it says

 A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000000f48412e, pid=3808, tid=0x0000000000000bbc
#
# JRE version: Java(TM) SE Runtime Environment (8.0_231-b11) (build 1.8.0_231-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.231-b11 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# J 88397% C2 blusunrize.immersiveengineering.client.models.IESmartObjModel.addQuadsForGroup(Lblusunrize/immersiveengineering/client/models/IOBJModelCallback;Ljava/lang/Object;Ljava/lang/String;Lblusunrize/immersiveengineering/api/shader/ShaderCase;Lnet/minecraft/item/ItemStack;)Ljava/util/List; (1239 bytes) @ 0x000000000f48412e [0x000000000f483d20+0x40e]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#

not sure why it says that as I got a log from another mod that crashed

**Comment by Pultex** [comment]
okay that was weird the text was HUGE try again

Also using

Forge Mod Loader version 14.23.5.2847
ImmersiveEngineering-core-0.12-92.jar

with the other mods in the list

here is the error I get it is from 

hs_err_pid5336.log

https://hastebin.com/usavavowas.makefile

not sure if it is just me or others have this
maybe another mod is doing it 
not sure what mods change lighting and shaders

mod list from other file as it does not create a normal crash log file

https://hastebin.com/kuxatowumo.rb

the server freeze and the client too
the server closes itself and creates that log file had 4 
did not know not in crash log folder
in base minecraft folder with .curseclient files

**Comment by Pultex** [comment]
I found out it was not part of IE 

Dank null was causing the problem

through

DankNull-1.12.2-1.7.89
p455w0rdslib-1.12.2-2.3.161
AE2WTLib-1.12.2-1.0.34
WirelessCraftingTerminal-1.12.2-3.12.97

after update of them from older versions

just so others know if they have the problem
