### ISSUE TITLE
[1.12.2] Chute still errored

### ISSUE THREAD

**Issue by RenanVieira88** [BluSunrize/ImmersiveEngineering#3611]
Description of the issue:
When placing a chute on the server, items appear to fall through, but actually don't.
Furthermore, destroying the chute drops as a conveyor named "tile.immersiveengineering.conveyor..name"
This ONLY happens on the server. It doesn't happen in a singleplayer game.

Crashlog:
There was no crash log

Versions & Modlist
forge-14.23.5.2838
IE - 0.12 - 92

**Comment by garrowson** [comment]
Same here

Reconnecting to the server also replaces the chutes with the mentioned conveyors.

Crashlog from server:
[https://pastebin.com/3iUmY0Mt](url)

Versions:
Forge 14.23.5.2847
IE 0.12 - 92

**Comment by Lgmrszd** [comment]
Same thing happened.
Server owner reports that server error is the same as above.

Versions:
Forge 14.23.5.2838
IE 0.12 - 92

**Comment by DoomRater** [comment]
Dang, no updates on 1.12.2, but it's in a fairly broken state.

**Comment by HorribleNerd** [comment]
Can confirm for servers
Forge 14.23.5.2847
IE 0.12 - 92
