### ISSUE TITLE
[Suggestion] Rifle

### ISSUE THREAD

**Issue by OmegaPaladin** [BluSunrize/ImmersiveEngineering#3612]
IE has the varied ammo types and weapon effects with rapid fire in the revolver, and a precision-fire railgun.  My suggestion is a middle-ground weapon - a bolt-action rifle.  This fits with the aesthetic of this mod, and does not make any current weapon useless.

The Rifle would need to be cycled after each shot, slowing the fire rate.  It would use revolver bullets, and load them from the inventory one at a time like arrows into a bow.  Accuracy would be better than a revolver, but not quite as crazy as the railgun.

Rifle vs. Revolver
-slower fire rate
=same damage / ammo
+more accurate / aimable
+does not need speedloaders 

Rifle vs. Railgun
-less accurate
-ammo is more complicated to make
+more ammo types
+no need for a backpack

**Comment by BluSunrize** [comment]
No, IE is not getting any more guns.
