### ISSUE TITLE
external heater may delete items when use it on server

### ISSUE THREAD

**Issue by 3094300238** [BluSunrize/ImmersiveEngineering#3619]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"
[1.12.2] External Heater Bug

### Description of the issue:
Describe what happens, how it affects your game/gameplay and provide screenshots where possible.
when i use it in a catserver server,when i put the heater and furnace correctly and full of RF energy,then i want to put some items into the furnaces that i want to cook,but the minute i put this item, the furnace and heater just flash a second ,then all the items i put disappeared.

### Crashlog:
If your Minecraft instance has crashed, a file will have been generated in the folder `crash-reports` of your minecraft folder. To understand what has happened, we need to know the content of that file. But please don't just put it directly in your report (that makes it hard to read), upload it to a site like [pastebin](http://pastebin.com) or [gist](http://gist.github.com) and put a link in the actuall bug report.
No crashlog

### Versions & Modlist
IE and Forge versions are mandatory. *Note that saying "latest" is **not** valid. Always give the proper version number*
Other mods should be listed (with their versions) in a [pastebin](http://pastebin.com) or [gist](http://gist.github.com) upload. The easiest way to get these lists is a crashlog, you may force one with F3+C.
If your game crashed (see above) you may omit the modlist, but IE and Forge version would still be nice.
1.12.2 Latest version of IE
works fine in singleplayer ,but bugs in multiplayer(Catserver).
Also, please try testing an issue in a minimal instance, with just IE, Forge and maybe JEI. That makes elminating compat issues easier.

### Lastly (you may delete this from the report itself)
Please, for the love of all that is voxelbased, **read the contribution guidelines. They are linked to the right in the message box.**
When reporting issues, these are crucial, and the team withholds the right to close an issue for the plain stupidity of not reading and adhering to them.

Thank you for reporting issues, without people reporting them, they wouldn't get fixed. You're helping contribute to this mod and that is much appreciated <3

**Comment by BluSunrize** [comment]
You should be *deleting* the instructions in the template when you file a report >_<

Also you didn't provide a modlist, or a forced crash. And I have no idea wht Catserver is, so please clarify that.

**Comment by malte0811** [comment]
CatServer is most likely [this](https://github.com/Luohuayu/CatServer) (from both previous issues by the OP and google results), another bukkit+forge project. Which means it isn't supported by IE.

**Comment by AgentCPU0** [comment]
Have this happening on my server. It makes no sense. How are we expected to properly use the heater? This absolutely NEEDFS to be bumped up and fixed, it's ridiculous. Why bother including that block if you don't plan to let us actually use it the right way? Either fix the bug, or remove the block from the mod
