### ISSUE TITLE
[Suggestion] Colored rope coils

### ISSUE THREAD

**Issue by in-tension** [BluSunrize/ImmersiveEngineering#3621]
I was thinking it'd be really cool to have decorative colored rope coils - you could do things like mark several crossing paths in cave systems and stuff.

One way to do it would be to make it possible to dye hemp rope coils. Or another way could be to make a new type of decorative rope coils from wool (dyed before and/or after crafting) and possibly wooden structural connectors so you could make paths without using all your steel.

**Comment by BluSunrize** [comment]
I'm not planning to implement this in the future
