### ISSUE TITLE
[1.12.2] Chain of wires seemingly randomly disappearing

### ISSUE THREAD

**Issue by in-tension** [BluSunrize/ImmersiveEngineering#3622]
[MC: 1.12.2][IE: 0.12-92][F: 14.23.5.2831]

So I have a pretty basic wire system set up with a waterwheel, a windmill, 2 capacitors and some machines. I can run everything fine and then seemingly randomly a group of wires will disappear. As far as I can tell, when a group of wires disappears it's along a single set of relays, if there's a connector (in this case usually attached to a capacitor) the group won't extend beyond it.

I know that if you try to pump too much rf through a wire it can burn up. But I only have 2 inputting (lv) wire connectors, each attached to a kinetic dynamo. Then they both connect to the same capacitor and when a group of wires disappears it usually one of those groups. So it can't be overloaded and burning up, right?

I do have a number of [mods installed](https://pastebin.com/mxzB8aLv). I tried to recreate it in creative but was not successful, but I don't know what triggers it so...

Also I've been hooking up connectors to galacticraft energy storage.

I really like IE's wiring but it's been happening enough that until I can find a fix I think I'm gonna have to use a different mod's wiring system. So any help would be greatly appreciated.

**Comment by bigenergy** [comment]
I experience the same problem sometimes

**Comment by mindforger** [comment]
you will sometimes experience surges, i do not know exactly how you hooked them up, so it is hard to say, but as far as i know waterwheels can discharge at very high rates if they buffered power (also this info may be outdated)

can you tell us a bit mor (probably with pictures) how your setup looks like

**Comment by bigenergy** [comment]
Wires can disappear even if they have no voltage

**Comment by mindforger** [comment]
is this also true for @in-tension ? 
because he described "a few" wires getting lost

lines disapearing without power usually means ALL wires are gone and stem from a different issue
