### ISSUE TITLE
Missing details in the manual

### ISSUE THREAD

**Issue by malte0811** [BluSunrize/ImmersiveEngineering#3624]
- The diesel gen entry currently does not mention that the generator won't run without an output, which can cause confusion (see #immersive-engineering on Discord, roughly when this issue was created).
 - Faraday suit entry should mention it also works for wires

**Comment by APCBoston** [comment]
FTB wiki compounds the confusion here -- it says *both* that the generator won't run without somewhere for the IF to go, and that it will run even if the consumer machine/capacacitor/network/foo is full and cannot accept any more IF.  It's really unclear from the docs are actually self-contradictory, or whether it's trying to say "it won't run if it isn't hooked up, but if it is hooked up it will run even if that extra IF is just dissipated to heat for lack of useful work to do."

**Comment by APCBoston** [comment]
That said, I find incomplete documentation and the need to do experiments to figure out how stuff works as part of the charm of this mod (to an extent).
