### ISSUE TITLE
Metal Press not forming [IE 0.12-92] [MC 1.12.2]

### ISSUE THREAD

**Issue by RhoneRC** [BluSunrize/ImmersiveEngineering#3628]
Hi all.

I know this issue has been raised many times previously and has come down to a few simple mistakes, I don't think that this is the case here.

So issue is simple enough, trying to create the metal press and its just not creating it.

- put everything in the correct locations (as signified by the green outline around the structure)
- right click with the hammer
> piston rotates and outline goes red due to rotated piston
- check to make sure conveyor belts are the correct ones
> they are correct
- rotate the conveyor belts to face the opposite direction
> outline goes red
- place everything back how it is meant to go
>outline goes green again
- Try again to build the structure
> piston rotates and outline goes red to signify incorrect position of piston

**List and version numbers of the immersive engineering mod and its add ons**
<a href="https://imgur.com/2WV7T8o"><img src="https://i.imgur.com/2WV7T8o.png" title="source: imgur.com" /></a>
[https://imgur.com/2WV7T8o](url)

**Completed structure with green outline**
<a href="https://imgur.com/qPiFQ19"><img src="https://i.imgur.com/qPiFQ19.png" title="source: imgur.com" /></a>
[https://imgur.com/qPiFQ19](url)

**Conveyor belt is indeed the plain version**
<a href="https://imgur.com/b7JOUyv"><img src="https://i.imgur.com/b7JOUyv.png" title="source: imgur.com" /></a>
[https://imgur.com/b7JOUyv](url)

**Right clicking with the hammer rotates block and shows red outline to signify that the orientation is now wrong**
<a href="https://imgur.com/MPFkqJK"><img src="https://i.imgur.com/MPFkqJK.png" title="source: imgur.com" /></a>
[https://imgur.com/MPFkqJK](url)

**Link to crash log (forced crash to get the log for details, game does not crash as part of issue**
[https://paste.dimdev.org/afoniwehah.mccrash](url)

Hoping that I've just something stupid here so if anyone can point it out, it would be amazing.

Forge Version: 14.23.5.2847
Game type: Single player
Open to lan: No
Modpack: Engineers Life
Tested with just the IE mods installed: attempted to but the modpack would start with full list of mods regardless of creating a duplicate pack with the other mods deleted from the folder.

Let me know if there is any other information you might need.

**Comment by malte0811** [comment]
Why are you using a sticky piston? It should be a non-sticky one.

**Comment by RhoneRC** [comment]
Hi! Sorry delayed response. 
I thought it was weird that a sticky piston would be required in this build. 
The quest book in this pack actually lists the stocky piston as the one required.. Not a fault of yours, i understand, but it led to the confusion. Also the fact that the outline showed green when a sticky piston was used didn't help.
Swapping it out with a regular piston indeed fixed this issue though. 

Thank you for your assistance!

<a href="https://imgur.com/bcviHSf"><img src="https://i.imgur.com/bcviHSf.png" title="source: imgur.com" /></a>
