### ISSUE TITLE
Excavator Collision issue

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#363]
well then... 
![image](https://cloud.githubusercontent.com/assets/3110986/9533914/fa2d9374-4cc9-11e5-850b-8504350e2f37.png)
 IE version 0.5.4 SHA 945d07be03fd7b4f0071bbf25e11d17bebb4af8a

Built the Excavator correctly and formed it. machine is currently running....

**Comment by BluSunrize** [comment]
Dynamic colision? No thanks.
