### ISSUE TITLE
About permission checking

### ISSUE THREAD

**Issue by mcqwy** [BluSunrize/ImmersiveEngineering#3630]
Hello, I have a spike server
In use the command is displayed without permission
After reading your source code, I found that the instruction passed the op level detection
Instead of detecting specified permissions
For example: ie.mineral.list

**Comment by BluSunrize** [comment]
Sorry, could you please rephrase this issue and provide the information requested by the issue template?

**Comment by mcqwy** [comment]
example:
CommandMineral
ICommandSender sender;
Under the execute() method
`if (sender.canUseCommand(4, "ie.mineral.list")) `
I am now writing the Sponge plug-in to call your command class methods directly
My time is tight
This may be a wrong example, you need to try it yourself.
If you are not in a hurry
I can write a code test tomorrow

**Comment by BluSunrize** [comment]
IE offers no support for Sponge.
