### ISSUE TITLE
Assemble ship cause multiblock structure duplication(mod ValkyrienSkies)

### ISSUE THREAD

**Issue by pawIka** [BluSunrize/ImmersiveEngineering#3631]
Hi, sorry my english :c

Multiblock structure placed on platform is drop if click button "Assemble Ship"

https://youtu.be/7aRJ8iDLBcw

link on reply from ValkyrienSkies:
https://github.com/ValkyrienSkies/Valkyrien-Skies/issues/364#issuecomment-570624345

Minecraft: 1.12.2
Forge: 14.23.5.2847
ValkyrienSkies: 1.0-alpha-1
ImmersiveEngineering: 0.12-92

mods:
![изображение](https://user-images.githubusercontent.com/57269692/71740770-b2038e80-2e8f-11ea-9108-d329e45f7972.png)

**Comment by mindforger** [comment]
IE multiblocks are not intended to be moved

**Comment by SSKirillSS** [comment]
So why not make them to be like that (movable)? TC4, AS, Mekanism and other perfectly cope with a similar task.

**Comment by BluSunrize** [comment]
Because frankly it's a fucking mess if we were to make ours movable and I'm not rewriting the entire system.
Plus, you can't move wire connectors because of how they save their data, so all your machines would just disconnect anyway.
