### ISSUE TITLE
[Suggestion] Pumps pulling from above

### ISSUE THREAD

**Issue by DoomRater** [BluSunrize/ImmersiveEngineering#3632]
It's been two years and Astral Sorcery's lightwells still cannot be automated with Immersive Engineering because it has no way to pull fluids from above.  I suspect AS is not interested in adding sided pulls from the lightwell.

Either a pump we can lay on its side, upside down, or a pump that can pull from a pipe that's connected to it would be appreciated.

I'm likely going to be stuck on 1.12.2 for some time however. I have no idea if 1.12.2 is still being updated or not.

**Comment by BluSunrize** [comment]
If we were to implement this feature, it would not come to 1.12, because development efforts are being focused on 1.14

**Comment by DoomRater** [comment]
I'll live!  There are enough edge cases where this feature could really come in handy.

**Comment by z64555** [comment]
Having the pump able to suck fluids from a fluid pipe or connected fluid inventory would probably be the best approach, and maybe also have the outlet block have the ability to be an inlet for such pumps.  This would allow a pump to suck water from the outlet/inlet from a remote location.

**Comment by BluSunrize** [comment]
Pumps can now pull through pipes, so this is irrelevant
