### ISSUE TITLE
[Suggestion] Crate PushReaction as destroy?

### ISSUE THREAD

**Issue by Nemerensis** [BluSunrize/ImmersiveEngineering#3635]
Would setting crate push reaction to destroy be within the design/theme of the mod?
The idea/purpose is that when pushed by pistons, crates will drop themselves while holding onto their inventories

**Comment by BluSunrize** [comment]
Hmm, I dunno. I realize that Shulker Boxes work like this in vanilla, but I feel like adding that feature to IE's crates would invalidate those boxes a little. Currently they are the only things with that behavior, which may make them attractive to certain setups. If IE's crates did that, Shulker boxes would be entirely useless (minues decorative purposes)
