### ISSUE TITLE
[1.12] Assembler only crafts single item recipes (planks->wood, crafting table->crafting station etc)

### ISSUE THREAD

**Issue by GhaladronOG** [BluSunrize/ImmersiveEngineering#3636]
### Description of the issue:
Using the Assembler Multiblock, only recipes where a single item goes into the crafting UI are working. e.g. putting a log to make four planks or turning a vanilla crafting table into a tinkers crafting station. I've done some testing with other mods' recipes, such as natura logs and Pam's Fresh Milk.

In every test, the assembler reads as fully powered. I have tested with and without redstone signals and with or without inverted redstone control

Just noticed it won't craft an Akashic Tome from a piece of dirt. This may be an unrelated problem as it doesn't match any of my other testing.

### Versions & Modlist
IE: 0.12-89
Forge Mod Loader: 8.0.99.99
Minecraft Forge: 14.23.5.2838
Modlist: ATM 3 5.12.2, https://rawgit.com/AllTheMods/ATM-3/master/modlist.html (This issue does *not* persist in an IE-only instance)

**Comment by BluSunrize** [comment]
You're not using the latest version of IE. Try it with that.

**Comment by GhaladronOG** [comment]
Ah looks like my bad for assuming ATM 3 had everything up to date. More recipes work sadly the ones I needed it for still don't. I'm trying to autocraft Pam's recipes but I assume there is an ongoing issue with the pam's tools?

**Comment by DoomRater** [comment]
I also had an issue with CraftTweaker recipes not working in IE 0.12-89 and I keep forgetting to update to 92, where I swore I saw something in the changelog that might actually address my issues. I should try that as well.

**Comment by DoomRater** [comment]
I have retried my particular issue with a recipe that didn't work in .89 and it works on .92.  I only tried locally but if I can confirm working on a server I have nothing worth keeping the issue open for.
