### ISSUE TITLE
[1.12] Fermenter Power Usage

### ISSUE THREAD

**Issue by Banjomann** [BluSunrize/ImmersiveEngineering#3637]
The fermenter uses ~256 RF/t, where the squeezer uses ~8 RF/t. In the ImmersiveEngineering.cfg file, both the energy and speed modifiers are set to 1.0 (default). Running on Engineer's Life 1.7 (for sake of not including a massive mod list), which is forge 14.23.5.2847 and IE 0.12-92.

I used a vibrant capacitor to measure the I/O individually for a single squeezer operating on Better with Mods hemp seeds to get a result of 8 RF/t. Similarly, I used a vibrant capacitor for a single fermenter with vanilla melon slices to get a result of 256 RF/t.

Once I modified the energy modifier to 0.015, the resulting energy consumption reduced to 8 RF/t as expected. Output amounts are correct (melon = 80 mB ethanol, hemp seed = 120 mB seed oil), and the operation speeds are on point.

If requested I can provide screenshots of my setup, but it's simply capacitor -> LV connector -> LV wire -> LV connector -> machine input.

**Comment by BluSunrize** [comment]
Can you try with IE's hemp seeds please?

**Comment by Banjomann** [comment]
Hm. Looks like it blasts through the RF for IE hemp seeds. Same rate 256 RF/t.

**Comment by BluSunrize** [comment]
And can you reproduce this in an instance with only IE (and EIO for measuring) ?

**Comment by Banjomann** [comment]
I haven't tried yet. I'll get back to you on that.
