### ISSUE TITLE
Excavator rendering issue(s)

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#364]
Overview: The excavator bucket wheel and main structure do not render on screen as expected
----------------
Upon forming the excavator+bucket wheel correctly, the bucket wheel has a few graphical errors that become self evident.

~~Issue 1~~
-------------
~~I expected the vertical supports that connect the outer buckets to the inner wheel to be centered, ~~they are not.~~

Issue 2
------------------------
The central wheel itself is colliding over 2 cm into the excavator structure one one side, and correctly set on the other.
Issue 3
----------------------
The excavators bins drop the material through its solid structure, onto the central shaft. Thats gotta increase wear on the device dramatically

Aux.
--------------
![image](https://cloud.githubusercontent.com/assets/3110986/9534098/31548082-4ccb-11e5-86b7-5014ddea3381.png)
![image](https://cloud.githubusercontent.com/assets/3110986/9534111/4426d444-4ccb-11e5-82f9-3a01e90aba3f.png)
![image](https://cloud.githubusercontent.com/assets/3110986/9534246/e8ceb4bc-4ccb-11e5-8159-a592a1fdb490.png)

Version data:
-------------
IE version 0.5.4 SHA 945d07be03fd7b4f0071bbf25e11d17bebb4af8a

**Comment by BluSunrize** [comment]
Blame the guy who modelled it. Seriously, though, this is not an actual issue.
