### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by planyte** [BluSunrize/ImmersiveEngineering#3642]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
Describe what happens, how it affects your game/gameplay and provide screenshots where possible.

### Crashlog:
If your Minecraft instance has crashed, a file will have been generated in the folder `crash-reports` of your minecraft folder. To understand what has happened, we need to know the content of that file. But please don't just put it directly in your report (that makes it hard to read), upload it to a site like [pastebin](http://pastebin.com) or [gist](http://gist.github.com) and put a link in the actuall bug report.

### Versions & Modlist
IE and Forge versions are mandatory. *Note that saying "latest" is **not** valid. Always give the proper version number*
Other mods should be listed (with their versions) in a [pastebin](http://pastebin.com) or [gist](http://gist.github.com) upload. The easiest way to get these lists is a crashlog, you may force one with F3+C.
If your game crashed (see above) you may omit the modlist, but IE and Forge version would still be nice.

Also, please try testing an issue in a minimal instance, with just IE, Forge and maybe JEI. That makes elminating compat issues easier.

### Lastly (you may delete this from the report itself)
Please, for the love of all that is voxelbased, **read the contribution guidelines. They are linked to the right in the message box.**
When reporting issues, these are crucial, and the team withholds the right to close an issue for the plain stupidity of not reading and adhering to them.

Thank you for reporting issues, without people reporting them, they wouldn't get fixed. You're helping contribute to this mod and that is much appreciated <3
https://yadi.sk/d/PYuEBdvJOJVtiw 
[crash-2020-01-28_20.19.20-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4128590/crash-2020-01-28_20.19.20-server.txt)
[crash-2020-01-28_19.56.17-server.txt](https://github.com/BluSunrize/Immersive
Engineering/files/4128591/crash-2020-01-28_19.56.17-server.txt)

I think that your mod conflicts with the player weight mod
The server console displays an error when the player dies

**Comment by BluSunrize** [comment]
Follow the contribution guidelines and reformat your post.
Use pastebin or gist for the logs.

Put a reply when your post conforms to the issue template, and we'll be abpply to assist you.

**Comment by planyte** [comment]
https://pastebin.com/fAVEnKTS

**Comment by BluSunrize** [comment]
Nothing in that log indicates that this is an error with IE. PlayerWeight is the only mod involved in the stacktrace, report to them.

Also, when I asked for you to reformat your post, I mean removing all the default text and instead structuring your report accordingly instead of just tacking two lines of text onto the end of the template.

**Comment by mindforger** [comment]
also bukkit server and as it looks like A LOT async stuff and therefore A LOT of concurrentmodification exceptions in this log

there is a very high potential for several mods bugging out in this environment
