### ISSUE TITLE
[1.12] Frequent hard crashes in Enigmatica 2 Expert

### ISSUE THREAD

**Issue by JaPaBu** [BluSunrize/ImmersiveEngineering#3643]
### Description of the issue:
The game sometimes crashes instantly to the desktop when rendering items.

### Crashlog:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x000000000e6ab289, pid=9860, tid=0x00000000000023a8
#
# JRE version: Java(TM) SE Runtime Environment (8.0_231-b11) (build 1.8.0_231-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.231-b11 mixed mode windows-amd64 compressed oops)
# Problematic frame:
# J 73481% C2 blusunrize.immersiveengineering.client.models.IESmartObjModel.addQuadsForGroup(Lblusunrize/immersiveengineering/client/models/IOBJModelCallback;Ljava/lang/Object;Ljava/lang/String;Lblusunrize/immersiveengineering/api/shader/ShaderCase;Lnet/minecraft/item/ItemStack;)Ljava/util/List; (1239 bytes) @ 0x000000000e6ab289 [0x000000000e6aae80+0x409]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Users\Jan\Desktop\MultiMC\instances\Enigmatica2Expert\minecraft\hs_err_pid9860.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code 1.
```

### Versions & Modlist
Enigmatica 2 Expert 1.76a
Immersive Engineering 0.12-92

I know you probably dont like to investigate this since this is a modpack but i chose to post it here anyways :P

[Edit] Btw i saw that somebody already complained about a similiar issue though it was marked as an error with FoamFix which was not loaded when this crash happened.

[hs_err_pid9860.log](https://github.com/BluSunrize/ImmersiveEngineering/files/4155667/hs_err_pid9860.log)

**Comment by FenixFyreX** [comment]
I will say that this has happened again to me today, in MC Eternal. It's happened twice now on this modpack, once with and once without FoamFix. Both times I was typing 'i' in an AE2 wireless terminal GUI, with JEI auto sync enabled. This time was a SIGSEGV in `J 106389% C2 blusunrize.immersiveengineering.client.models.IESmartObjModel.addQuadsForGroup(Lblusunrize/immersiveengineering/client/models/IOBJModelCallback;Ljava/lang/Object;Ljava/lang/String;Lblusunrize/immersiveengineering/api/shader/ShaderCase;Lnet/minecraft/item/ItemStack;)Ljava/util/List; (1239 bytes) @ 0x00007fb2fb064646 [0x00007fb2fb064260+0x3e6]`

**Comment by NillerMedDild** [comment]
This particular crash is a java crash - Could you please update, or downgrade if no update is available? :)

**Comment by FenixFyreX** [comment]
It seems to only happen (to me, at least) when searching JEI synced with AE2 terminals. My java is the latest, also tested with previous version (Java 8 u242, u232). Tested on Windows 10 / ArchLinux 64bit both.

Just happened again today on MC Eternal making it an almost daily thing.. Regardless of severity or type of crash, it only happens when ImmEng is installed. FoamFix (or any of the 'performance' mods, really) is not a requirement for this issue to occur as far as I've seen.

**Comment by NillerMedDild** [comment]
Ah I see, my mistake :) I hope one of the IE guys can help.

**Comment by BluSunrize** [comment]
No, we can't. That's a Java internal crash with zero indication to its cause. We can't replicate it, we can't diagnose it, we can't fix it.

**Comment by BluSunrize** [comment]
Beyond using a recent version of Java, there's nothing I can feasably recommend.

**Comment by FenixFyreX** [comment]
There is possible indication of a dereference of a null that isn't being caught, resulting in a SIGSEGV. Trapping and producing a NullPointerError is usually what happens, but in this case for some reason it isn't. Perhaps looking around or on line 409 of `IESmartObjModel` 1.12 source will help with fixing the issue? Looking for a dereference (line 410 seems probable, although it could be in that entire loop).

**Comment by atopian** [comment]
Sorry to necro this one, but newer versions of java may be the cause.   Running 8.0_261-b12 causes this to occur for me randomly, every few hours or so.   However another member of my server with the same settings did not have this issue.  The only difference ended up being that he was running an older Java, so I reverted to 8.0_112-b15 and have been able to play unimpeded.

Mostly adding this note for posterity, should anyone else run across the issue.

**Comment by 0xpr03** [comment]
Had this also today randomly, in case other people are doubting their RAM correctness
[crash report](https://gist.github.com/0xpr03/0fc60dbfb41c655a49c86ab6b0df0f3e)

**Comment by BluSunrize** [comment]
1.12 has been out of support for over a year
