### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment

### ISSUE THREAD

**Issue by TheJaysH** [BluSunrize/ImmersiveEngineering#3645]
Playing Enigmatica 2 and right clicked a double chest with leather in my main hand resulted in a hard java crash. seems your mod what the cause.

I have attached the log.  ---> [hs_err_pid11460.log](https://github.com/BluSunrize/ImmersiveEngineering/files/4165602/hs_err_pid11460.log)

but this was the line in question: 

```
J 111752% C2 blusunrize.immersiveengineering.client.models.IESmartObjModel.addQuadsForGroup(Lblusunrize/immersiveengineering/client/models/IOBJModelCallback;Ljava/lang/Object;Ljava/lang/String;Lblusunrize/immersiveengineering/api/shader/ShaderCase;Lnet/minecraft/item/ItemStack;)Ljava/util/List; (1239 bytes) @ 0x0000000005280f98 [0x0000000005280ba0+0x3f8]
```

**Comment by metaknight1992** [comment]
Same modpack, same issue, except I triggered it by typing 'hi' into JEI's search bar.

Error log:
[hs_err_pid6676.log](https://github.com/BluSunrize/ImmersiveEngineering/files/4505060/hs_err_pid6676.log)

**Comment by Hard-Biter** [comment]
same problem with ftb revelation, triggered by sorting my inventory with inventorytweaks
error log:
[hs_err_pid4020.log](https://github.com/BluSunrize/ImmersiveEngineering/files/4735576/hs_err_pid4020.log)

**Comment by mpavkovic** [comment]
Same issue as above, in Enigmatica 2 Expert Skyblock modpack, mod version is 0.12-92

Happened when I right-clicked a diamond chest with a stick in my hand.

**Comment by malte0811** [comment]
1.12 is no longer supported. If anyone is experiencing this crash on supported versions of MC (currently 1.16.4) please open a new issue.
