### ISSUE TITLE
Immersive Engineering Teselating Block Model Crash Error on Minecraft Forge 1.12.2

### ISSUE THREAD

**Issue by Squintman45** [BluSunrize/ImmersiveEngineering#3646]
https://pastebin.com/Y9BuUkt0

Above is the link to Pastebin.

The problem is with the Mod - ImmersiveEngineering-core-0.12-92.jar.  I went to place a "Floodlight" in my world on Minecraft playing with Minecraft Forge 1.12.2 and using other mods including Immersive Railroading and when I placed the "Floodlight", the game "bluescreened" and crashed.  I then got the "crash report" saying it was a "Teselating Block Model" error with ImmersiveEngineering-core-0.12-92.jar.  Could you PLEASE help?  It would be greatly appreciated.

**Comment by BluSunrize** [comment]
Can you reproduce this error with just IE installed?
