### ISSUE TITLE
[1.12] Redstone connectors are comparator-readable, but always return value 0

### ISSUE THREAD

**Issue by TheRealWormbo** [BluSunrize/ImmersiveEngineering#3647]
### Description of the issue:
The setup is as follows: There is a solid block and an adjacent "vanilla" redstone comparator facing away from it. On the opposite side of that block, an IE redstone connector in output mode is attached to the block and receives a signal greater than 0 through a wire. The redstone connector itself will have that redstone signal strength and the block will be powered by that signal strength. However, the redstone comparator still outputs signal strength zero. Only if the block is powered from a different side and either that signal has strength 15 (a vanilla mechanic that overrides the comparator's "reading feature") or there is no connector on the opposite side of the block, then the comparator will output the block's signal strength.

Observed behavior: The connector appears to present it self as a comparator-readable block that always presents the value zero, thereby making the comparator output signal strength zero, unless another source applies a signal of strength 15 to the block inbetween.

Expected behavior: The comparator will always output the block's signal strength, regardless whether there is a redstone connector on the opposite side. A redstone connector should not be considered comparator-readable, but instead just act as a source of redstone signal.

### Versions & Modlist
* Forge version: 14.23.5.2847
* IE version: 0.12-92

It's hopefully not a compatibility issue, but this was found running out-of-the-box [SergeCraft 2.1.1](https://www.curseforge.com/minecraft/modpacks/sergecraft2/files/2870098). Mod list: https://pastebin.com/PF4R9CXC

**Comment by DoomRater** [comment]
Fun thing about comparators: they are supposed to be able to read signals through a solid block.  If you put down a chest, then a solid block, then a comparator facing away from the block, the comparator gets the value of the chest on the opposite side rather than the block.  I'm not sure if this vanilla behavior has anything to do with the weirdness you're experiencing.

As a workaround, have the block power a redstone dust and read the comparator value of that.

**Comment by TheRealWormbo** [comment]
I know that vanilla behavior, and mentioned it in the initial issue description. My point is, redstone wire connectors should not create a special comparator output that is different from their redstone signal strength. Being redstone-transmitting components, they should probably not create a special comparator output at all.
