### ISSUE TITLE
Arc furnace CT removal not actually implementing removal

### ISSUE THREAD

**Issue by Gebcrafter** [BluSunrize/ImmersiveEngineering#3648]
_**The issue: crafttweaker script is not erroring, and the crafttweaker log reports that the recipe was successfully removed, but the recipe persists.**_

Trying to remove the steel ingot recipe in the Arc Furnace:
**mods.immersiveengineering.ArcFurnace.removeRecipe(<thermalfoundation:material:160>);**
I have talked with the developer of crafttweaker and he directed me here, since IE adds its own crafttweaker support

https://pastebin.com/ZDAvMV23 line 22 of crafttweaker.log should prove that the recipe is not erroring, though I am still able to craft the ingot using the arc furnace

**Comment by BluSunrize** [comment]
Could you maybe actually read the contribution guidelines and provide the information we ask for? Thanks =)

**Comment by Gebcrafter** [comment]
Haha ok ok ok I apologize I was desperate. I actually talked to another developer and figured it out. Apparently, even though - what I'm assuming was unidict's doing - the recipe produced a thermal steel ingot, the removal still needed to specify the IE steel ingot, which worked.
