### ISSUE TITLE
Question: How do I add hot and cold blocks to the Thermoelectric generator?

### ISSUE THREAD

**Issue by Winddbourne** [BluSunrize/ImmersiveEngineering#3649]
I'm sure I'm just missing something obvious but there doesn't seem to be any way to add hot or cold blocks so they work with the Thermo-Electric Generator. 

For example I back port blue ice and that definitely should be a cold block at least on par with packed ice. 

I've also got Railcraft and the Firestone Ore sets everything around it on fire, If my players place the generator next to it, or mine it up with a silk touch tool they should have a very powerful (and rare) hot block for their generator. 

I was expecting to find an array in the main Immersive engineering Config file but the only reference I can even find to the generator is something to do with the output modifier.  If this was a less polished and popular mod I'd think there wasn't a method yet . . . and ask for one; as it is I'm assuming the problem is on my end.

**Comment by mindforger** [comment]
you can at least use crafttweaker :)

https://github.com/BluSunrize/ImmersiveEngineering/blob/0a3f6ca345114779dd04ea24c4ca3640c9afd6f9/src/main/java/blusunrize/immersiveengineering/common/util/compat/crafttweaker/Thermoelectric.java

**Comment by Winddbourne** [comment]
Thanks for the link, I'm going to try that. I'm still hoping there is an easy way in the mod itself that I'm missing but if not at least I have a method now!

**Comment by Winddbourne** [comment]
I got it working and uncovered a different problem . . . not one that will hugely impact my pack but:

![2020-02-10_19 19 02](https://user-images.githubusercontent.com/24589533/74202408-5c629480-4c3a-11ea-9ea7-83063115ac88.png)

I went all out and added all of the permafrost blocks from Quark at 500 . . . you can find them randomly in certain cave systems. . . the result should have been multiple pages or a scroll bar, but it just goes right off the page and it looks like it would go off screen if I wanted to add any more blocks. lol
