### ISSUE TITLE
Minecraft Crash 1.12.2 Immersive Cannot Set PropertyDirection

### ISSUE THREAD

**Issue by 1DONit1** [BluSunrize/ImmersiveEngineering#3653]
Hello everyone! I playing minecraft with my friends on server. My friend like immersive engineering , but he got a minecraft crash. I wanted to help him, but when I has come to him home in minecraft, I got a minecraft crash too. We tried to downgrade version forge, codechicken, immersive engineering 
but it did not help.
[crash-2020-02-13_12.52.31-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4197667/crash-2020-02-13_12.52.31-client.txt)

**Comment by mindforger** [comment]
please use pastebin or similar and do not upload files

but the crash looks funky, do you use any non forge stuff on this client? the minecraft classes seem broken

**Comment by 1DONit1** [comment]
> please use pastebin or similar and do not upload files
> 
> but the crash looks funky, do you use any non forge stuff on this client? the minecraft classes seem broken
> 
> Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} to down on block immersiveengineering:stone_device, it is not an allowed value
> 
> why does the enum has no up or down, that seems very broken
> 
> or is there a mixup in orientation enums, one for geographical facing and one for blockfacing ?

non forge stuff? For example? What should I do?

**Comment by mindforger** [comment]
i have seen pepole using alternate mod loaders in the past few weeks a lot and this is looking like either some core mod changes the minecraft classes or there seem to be a mixup of the facing class used in "someones" code ... i can not pinpoint this without looking deeper into the code but that i can not do yet, maybe later

**Comment by BluSunrize** [comment]
This issue is basically impossible to reproduce. 
You can try to use MCEdit to remove the erroring block.
Also, try loading the world without OptiFine and see if you can load the world then. You're also using a very outdated version of IE. Consider updating,

Please read the contribution guidelines more carefully next time.
