### ISSUE TITLE
[Question]  How to use Immersive Engineering API.

### ISSUE THREAD

**Issue by thiago1255** [BluSunrize/ImmersiveEngineering#3655]
Hello, I'm developing a mod, I would like to know how to use the API, more specifically energy.
And my doubt is which of these files (https://github.com/BluSunrize/ImmersiveEngineering/tree/master/src/main/java/blusunrize/immersiveengineering/api/energy ) should I use to make a block that I can control the amount of energy that can pass, and that I could directly connect the wires to the block.

Thanks.

**Comment by BluSunrize** [comment]
I mean.... have you actually tried looking at the code? Have you had a look at how IE implements its own API? That should give you a pretty solid idea of how it works.

**Comment by thiago1255** [comment]
Yes, i understand it now. thx for mod !
