### ISSUE TITLE
[1.12.2] suggestion: Combining revolver part traits

### ISSUE THREAD

**Issue by SanjivanM** [BluSunrize/ImmersiveEngineering#3657]
I have a suggestion: Say I have 2 revolver components, be it a drum, hammer or whatever that I found in a village Engineer's house loot.  Can there be a feature to craft the two components and combine the traits?

EX: Barrel (luck -45% firerate +20%) and a Barrel (luck +2%) when crafted would yield Barrel (luck -43% firerate +20%)

**If this already exists, but in another way, i.e. using another IE machine/block/whatever to do the combining, sorry!  I tried crafting them, which seemed to be the most logical step I could think of :P

**Comment by BluSunrize** [comment]
No! :D
You're supposed to *find* the cool ones, not *make* them

**Comment by SanjivanM** [comment]
but you're missing the point of the game! Mine*craft* :P

**Comment by BluSunrize** [comment]
Yeah, you use that stuff to craft revolvers. You don't craft itself into itself.

This is a concious choice of gamedesign which I'm sticking to.

**Comment by SanjivanM** [comment]
so it's not possible to use commands ans get parts? I wanted a high firerate revolver for my creative world...
