### ISSUE TITLE
Cfg for Industrial squeeze Recipe output?

### ISSUE THREAD

**Issue by pablo46** [BluSunrize/ImmersiveEngineering#3659]
Hi, im trying to find the cfg to change the seed oil output amount from the industrial squeeza, i tryed here;
config\immersiveengineering.cfg
config\immersivepetroleum.cfg
but didn't found nothing, only the flux and speed, but not the recipes and the output,
where can i find them?
Love u all ;)

**Comment by BluSunrize** [comment]
It's not in the configs. All machines have Craftweaker support.
