### ISSUE TITLE
Electric Lantern Lighting Range?

### ISSUE THREAD

**Issue by Vercalos** [BluSunrize/ImmersiveEngineering#3660]
Less of an actual issue and more of a feature request.  I don't suppose we could get Electric Lanterns that actually light up a wider range than Torches?  I know this mod isn't Ender IO(whose Electric Lights actually have a wider range than other light sources), but I would imagine since the Electric lanterns prevent hostile mob spawns within 32 blocks of the lamp that it should have a similar extended light range.

**Comment by mindforger** [comment]
Did flood lights got removed?

**Comment by BluSunrize** [comment]
Making light "a wider ranger" requires placing fake, invisible lightsources, as shown by the floodlight.

IE's lanterns don't do that, because it's a performance hit.

**Comment by Vercalos** [comment]
> 
> 
> Did flood lights got (get) removed?

No, flood lights didn't get removed, but this is a combination of aesthetics(Flood Lights do not LOOK good as street lights), and function(Flood Lights are monodirectional, as opposed to the omnidirectional Electric Lantern).

**Comment by z64555** [comment]
Maybe have the lantern spawn a fake light source at the base of the pole its on?  This will make the area on the ground lighter.

**Comment by BluSunrize** [comment]
No, the electric lantern is designed to *not* place fake lightsources, for performance sake. That's what the floodlight is for.
