### ISSUE TITLE
Not Able to Run IE 1.12.2

### ISSUE THREAD

**Issue by BiggetyBounceman** [BluSunrize/ImmersiveEngineering#3661]
### Before reporting:
1.12.2 Launch Crash
When I load IE 1.12.2 0.92 I either get a black screen or just an ordinary crash, I only use the IE mod and Forge 1.12.2-14.23.5.2847.
I really want to play this mod and cant use any addons. 
Please Help.

Crashlog from _latest_ log file
https://pastebin.com/MFQMN1M8

Versions & Modlist
IE- 1.12.2-0.92
ForgeModLoader- 1.12.2-14.23.5.2847

**Comment by BiggetyBounceman** [comment]
Forgot to delete the **_Before Reporting_** part

**Comment by mindforger** [comment]
This is just an incomplete logfile, no crash report. Is there no file in the crash log folder?

**Comment by malte0811** [comment]
Try setting `

**Comment by BiggetyBounceman** [comment]
Sorry for the late response but I can't find a crash file unless I overlooked but no I can't find one

**Comment by BiggetyBounceman** [comment]
I'll try the stencilbufferenabled  when I get back home

**Comment by BiggetyBounceman** [comment]
**THANK YOU SOME MUCH!!!** My Minecraft loaded perfectly but a little laggy tho, ill get back to you if I have any problems
