### ISSUE TITLE
[1.12.2] Server crash on boot

### ISSUE THREAD

**Issue by rakoze** [BluSunrize/ImmersiveEngineering#3663]
Hi !

I'm trying to boot a MC Eternal server but I keep having the same crash. I've never successfully boot the server once, so the worlds aren't even created.

I think it's link to this mod precisely from what I've read in the logs : 
<a href="https://pastebin.com/KmntvwQJ"> 
Crash-Report
<a>

Could you please help me and tell me what I am missing ?

Thanks for your help !

**Comment by Compegen** [comment]
Try disabling the actuallyadditions compat in the config, and see if that works.
In the config, look for `compat { B:actuallyadditions=true ` and make that false
