### ISSUE TITLE
Mystical Agriculture seeds won't go into a Garden Cloche

### ISSUE THREAD

**Issue by llloyd4** [BluSunrize/ImmersiveEngineering#3664]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:

I created a blaze seed, go to put it into a Garden Cloche and no go. I tried it on dirt, on nether rack, on nether brick, etc and nothing. It just won't accept the blaze seed. Tried an essence seed as well and same result, it won't accept any MA seeds as far as I can tell. 

### Crashlog:

N/A Not crashing

### Versions & Modlist

https://pastebin.com/t6APKS9Q

**Comment by EvilCooky** [comment]
I think mystical agriculture is not supposed to work with the garden cloche.
There might be settings for that in the config file.

Alternatively you can look for a companion mod that will make mystical agriculture crops available for the cloche.

**Comment by llloyd4** [comment]
Oh? As I was doing that in 1.10.2. Didn't see a setting but I could have missed it. What companion mod would you recommend?

**Comment by EvilCooky** [comment]
I'm not totally sure if there is a setting, there might not be.

But In the past if have seen mods who add Mystical agriculture support.
A quick search lead me to this mod:
https://www.curseforge.com/minecraft/mc-mods/ie-cloche-compat
But the author says it's broken? Maybe you can find another mod that does the same.

**Comment by llloyd4** [comment]
Hmm... There is also MystAgrad Cloche Compat but it says your mod supersede it, that doesn't help. Hmm... That and yours are the only two Curse Forge pages I see on page 1 of Google, the rest are people asking for comparability to be added. That's disappointing. TF supports it with Phydo Grow but Phydo Grow is a pain in the neck, I have to route all my ore processing though the much slower Induction Smelter with sand to get the rich slag needed for it. Sand isn't a problem, it's the speed, >,< Well, turn this into a feature request then, add Mystical Agriculture support to the garden cloches.

**Comment by mindforger** [comment]
You know you can search closed issues too? If not, you are welcome :)
https://github.com/BluSunrize/ImmersiveEngineering/issues/3521
Would be your answer then ;)

**Comment by llloyd4** [comment]
@mindforger Well, that asks for the cloche to *give* MA seeds, not *use* MA seeds. Don't get seeds from right clicking on them as they grow in world so I wouldn't expect the cloche to give them neither. But it can't even grow MA crops in a cloche. Not just MA, but also flax seeds from Actually Additions neither. So far it's 2 strikes. >.<

**Comment by mindforger** [comment]
well it was kind of an example for you, there is a very high probability that your request has already been dealt with in a similar fasion ... 


soooo did you check that before you tried to counter argument me? 

sorry if that reads a bit salty, but your response did too, so no hard feelings

**Comment by llloyd4** [comment]
Apologies. Let me see...

My issue
The issue on giving seeds
Issue on the Assembler, not Cloche
Issue on phantom items using diamond seeds.

I stopped after that issue since the Original Poster (OP) is using diamond seeds but it's producing phantom items so I know it was, at least for his version of 1.12.2, possible to do what I can't do. That's when I posted here my issue.

**Comment by BluSunrize** [comment]
Point is, it doesn't give seeds because of how much people complained. See the issue that @mindforger linked.
Closed.

**Comment by llloyd4** [comment]
@BluSunrize That's not the issue, I can't even put a seed *into* a cloche to grow it.

**Comment by llloyd4** [comment]
And MA has tossed the ball into your court on integrating their seeds. >.< 

https://github.com/BlakeBr0/MysticalAgriculture/issues/281

**Comment by llloyd4** [comment]
My issue is I can *not* do what Direwolf20 did in this video.

https://www.youtube.com/watch?v=HVMFzQK35p4&t=27m5s

I right click in dirt, check, right click in seed, fail. Drop seed in, fail. Seed refuses to go into the cloche, period. I can *not* grow MA seeds in a cloche.
