### ISSUE TITLE
[Request/Mod Interaction] Gunpowder barrel to fire ExplosionEvent.Detonate and BlockEvent.BreakEvent

### ISSUE THREAD

**Issue by CelestialPhoenix** [BluSunrize/ImmersiveEngineering#3666]
Description of the issue:
So I'm adding in drops for when blocks are destroyed by explosions, however the drops don't occur with Immersive Engineering as the Gunpowder Barrel doesn't fire the `ExplosionEvent.Detonate` and `BlockEvent.BreakEvent` (Ref https://github.com/codetaylor/dropt/issues/68).
Would it be possible to add this functionality to the Barrel?

Versions & Modlist
Minecraft: 1.12.2
Forge: 14.23.5.2838
CraftTweaker: 4.1.20
Dropt: 1.17.0
Immersive Engineering: 0.12.-92

**Comment by BluSunrize** [comment]
`BlockEvent.BreakEvent` is fired when a player breaks it. Not an explosion.

`ExplosionEvent.Detonate` is dispatched by `ForgeEventFactory.onExplosionDetonate()`, which IE calls. That event is used for the *entities* targted by an explosion, not the blocks.

Neither of these events does what you want it to.
