### ISSUE TITLE
Crash on launch [1.12.2]

### ISSUE THREAD

**Issue by wanou067** [BluSunrize/ImmersiveEngineering#3667]
### Description of the issue:
The game is crashing during the first step of forge initialisation, when it loads IE
The crash logs shows a problem with IE like a missing coremod.

### Crashlog:
Crash report: 
[see on pastebin](https://pastebin.com/YJ85qFgM)

### Versions & Modlist
My version and modlist are visible in the crash report, I use the last version of 1.12.2 but if you need more informations, you can ask.

**Comment by DoomRater** [comment]
Immersive engineering 12-89 is out of date...

**Comment by wanou067** [comment]
Yes, i know, but it's the last on 1.12.2

**Comment by DoomRater** [comment]
No it's not.  12.92 is available for 1.12.2 on CurseForge: https://www.curseforge.com/minecraft/mc-mods/immersive-engineering/files/2799143
