### ISSUE TITLE
[1.12.2] Possibly interferring with other mods worldgen?

### ISSUE THREAD

**Issue by BlackJar72** [BluSunrize/ImmersiveEngineering#3671]
### Description of the issue:
It has been reported that Doomlike Dungeons will not generate if this mod is installed.  I don't know why, but a player has narrowed the problem down to occurring if and only Immersive Engineering is installed.  

>     Quote from [SirPhoenixBlood](https://www.curseforge.com/minecraft/mc-mods/project-74246) >>
> 
>     In reply to JaredBGreat: i removed all the ones i added and made test worlds with small 
> batchs of mods that i added till i fig out it has to do with the following mods
> 
>     Immersive Engineering (its this mod) ver. 0.12-92
> 
>     Addon mods:
>     Engineers doors
>     Engineers decor
>     Immersive Railroading
>     Immersive tech
> 
>  PS. i tryed working my way down the ver. of IE and got all the way to 85 without crashing but it 
> was still not making any dungeons at all but on ver. 85 it crashed so at least we know that much 
> so far

Is there something in this that effects world gen in general?  Any idea what would cause this and how it could be fixed?  Maybe even something I could do to fix it?

**Comment by BluSunrize** [comment]
The reason it crashes on versio 85 is because you gotta update Forge.

And no, I am not aware of any worldgen conflicts, nor do I know why we would ever cause these.
Can you reproduce the issue with the *latest* version of IE and Doomlike Dungeons, in a clean instance that contains nothing else?

**Comment by BlackJar72** [comment]
OK, I can confirm it's not this, sorry to bother you.  That will teach me to take some random guy's word for it -- though I was never given a full mod list and frankly don't want to test every combo one by one.
