### ISSUE TITLE
[1.14.4] Bucket in Coke oven not going down to the output slot once filled

### ISSUE THREAD

**Issue by MartinFNV** [BluSunrize/ImmersiveEngineering#3675]
The Bucket in the Coke Oven doesn't go down to the output slot once it's filled (turned to "Bucket of Creosote Oil").
The bucket turns to the correct filled bucket but stays on the top slot (input for buckets).

![2020-03-20_19 13 11](https://user-images.githubusercontent.com/32233776/77210282-5e443100-6adf-11ea-9240-05219a631310.png)

![2020-03-20_19 16 50](https://user-images.githubusercontent.com/32233776/77210286-5f755e00-6adf-11ea-9f33-52c10283b266.png)

**Comment by cryptearth** [comment]
How did you even got a stack bigger than 64 in the input slot in the first place?
