### ISSUE TITLE
[1.14.4] Garden Cloche crashes game when I put a hemp seed in it

### ISSUE THREAD

**Issue by MartinFNV** [BluSunrize/ImmersiveEngineering#3677]
### Description of the issue:
When I put a hemp seed in the Garden Cloche, the game instantly crashes.

### Crashlog:
[pastebin](https://pastebin.com/4avNY7Sj) 

### Versions & Modlist
IE: 1.14.4 Alpha ImmersiveEngineering-0.14-93
Forge: 1.14.4-28.2.3

**Comment by BluSunrize** [comment]
fixed in dev
