### ISSUE TITLE
[1.14] Minecart With Chest Render Crash Upon World Load

### ISSUE THREAD

**Issue by elder-sign** [BluSunrize/ImmersiveEngineering#3678]
### Description of the issue:
Created a new world with the 1.14 alpha, crash occurs when looking in the direction of the minecart with chest causes immediate black screen and crash to desktop.

Tried both with and without resource packs, made no difference.

### Crashlog:
https://gist.github.com/elder-sign/a11e787a9824c7cbb4d93ed2a2114407

First crash log is with ~70 mods, second crash log is with just IE.

### Versions & Modlist
forge-1.14.4-28.2.3
IE 0.14-93

**Comment by MartinFNV** [comment]
Happened to me too with only IE and JEI.

Same symptoms. (there wasn't a minecart in view, I assume it was one in a mineshaft under my world?)

Forge 1.14.4 28.2.3
IE 0.14-93

crash log: https://pastebin.com/tR109hTF

**Comment by BluSunrize** [comment]
fixed in dev
