### ISSUE TITLE
Crusher particles contain wrong data

### ISSUE THREAD

**Issue by GotoLink** [BluSunrize/ImmersiveEngineering#368]
When processing, the IE crusher tries to spawn particles as an item.
The data which it base those particles on have a really big chance of being inaccurate, especially in mod packs.
Detected this issue from [this issue](https://github.com/shadowmage45/AncientWarfare2/issues/380#issuecomment-136023378), where Tinkers Construct ingots (server side) would trigger Ancient Warfare engineering station icons (client side).

**Comment by cobra** [comment]
The crusher has some other issues with client/server syncing, looks like it needs some larger changes than just a few small fixes. See: #346.

**Comment by theunkn0wn1** [comment]
I am going to point out that i can only reproduce this bug when AW2 is installed in my testing environment....

**Comment by cobra** [comment]
cannot reproduce (any more?), all TConstruct ingots either disappear (no recipe) or produce the correct particles. Did this happen in singleplayer or is this a multiplayer-only issue?

Mods: AW2 2.4.112, TConstruct 1.8.7 (+mantle 0.3.2a), IE 0.6-pre (e6bf7a3), CoFH core (3.0.3), thermal foundation/expansion/dynamics (1.2.0, 4.0.3B1, 1.1.0), Extra Utilities (1.2.11), ProjectE (1.7.10-PE1.9.2) (left over from testing other stuff).

**Comment by GotoLink** [comment]
The incriminated line [here](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/blocks/metal/TileEntityCrusher.java#L215) hasn't been changed. 
The vanilla packet S24PacketBlockAction can not handle ids above the byte range. Which is the case for any number of modded blocks/items, as long as enough mods are installed.

**Comment by cobra** [comment]
ah right, that was the too-many-mods-issue, not anything mod-specific. I forgot about that, sorry. So this still needs to be solved somehow, then. Ideally without touching any S24PacketBlockAction packets, I guess.

**Comment by cobra** [comment]
I've poked around a bit and removed the whole BlockEvent code. IE is already sending a packet around when it's updating the particles, so I just used that instead to update the particleStack. Works beautifully, shouldn't ever get into any size issues like the these above and saves a whole network packet. I'll do some more testing and push my changes when I'm confident enough about not breaking anything with that.

**Comment by cobra** [comment]
The Excavator (wheel) has the same problem, somewhat even worse because of stuffing two values into an int ultimately being read as a byte: `Block.getIdFromBlock(Block.getBlockFromItem(ore.getItem())) + (ore.getItemDamage() << 12)`
This simply ignores the metadata when running in multiplayer.

**Comment by cobra** [comment]
@BluSunrize just a heads-up, I'm piggybacking this branch to add the mineral overrides to world save data. I'm using these overrides for debugging and testing the excavator BlockEvent issue from above and having to type the same stuff over and over again was annoying me. I'm hoping to finish the excavator sync today or tomorrow.

**Comment by BluSunrize** [comment]
Fine by me, thanks =)

**Comment by cobra** [comment]
(ignore that weird reference above, I rebased and force-pushed to my branch. I'm evil, I know.)

**Comment by cobra** [comment]
That wheel is really tough to get working properly. I noticed some desyncs (buckets rendered as filled after the drop-off point and empty when coming upwards until "magically" filling at an arbitrary point) before I even started changing anything. Now that I'm updating the wheel more frequently, it's stuttering rather often.
I've already considered fixing the original problem by adding a custom update packet, but I don't really know whether that would be a good idea.

**Comment by kane-thornwyrd** [comment]
If you're on Ubuntu, or any distrib with netem bundled in the kernel, you can [use ```tc```](http://mark.koli.ch/slowdown-throttle-bandwidth-linux-network-interface), [here a better example straight from the linux foundation](http://www.linuxfoundation.org/collaborate/workgroups/networking/netem).
Or even [try wondershaper](http://jwalanta.blogspot.fr/2009/04/easy-bandwidth-shaping-in-linux.html).

**Comment by BluSunrize** [comment]
I set myself a little challenge in keeping IE free of custom packets. It's not necessarily smart, but I thought it'd be fun to try. So far it has worked.

**Comment by BluSunrize** [comment]
@cobra sorry this happens so late, but I have actually bowed to custom packets now, since I couldn't avoid it any longer. If you are still working on this, the last commit might make your life easier.

**Comment by cobra** [comment]
I am, I just didn't have enough time the last days. I have a solution, but haven't tested (aside from a quick singleplayer test) and polished it yet. I'll look into it, I guess I might do two alternatives.

**Comment by cobra** [comment]
@BluSunrize offtopic: You didn't test what happens when manually setting a mineral override, did you? That doesn't work at all now (yes, I tested on master, not my branch) and the command handler for it doesn't make too much sense for me - getting the info and then modifying it locally without handing it back.
I'm looking into that now, your changes broke the world save data for minerals I added, so I have to rework that anyway. Yay for git.

**Comment by cobra** [comment]
Tested everything, looks good to me. A side effect of syncing the whole wheel data is that the wheel won't get completely out of sync with the ore buckets being in the wrong position like this:
![](https://cloud.githubusercontent.com/assets/163331/10527560/64c57092-7391-11e5-90e8-b06781ae015a.png)
The downside of correcting this is a slight jerking when it gets back into sync. I set the maximum allowed difference between client and sync packet to ±5, this could need some increase, depending on how ugly the packet delays can get.

The branch above is the version without any custom packets, using those would still get the wheel completely out of sync unless also syncing the rotation, but then that's not much different to doing a complete sync while increasing the potential for bugs.
I also cleaned up a bit and removed the unused `process` and `lastPowerInput` fields entirely.

What do you think about this? Use this approach or use the old way of doing a delta-sync with custom packets being able to carry more data than a byte?

**Comment by GotoLink** [comment]
Note you could keep the vanilla packets by splitting the id with bit masks over multiple packets on server side, and merging on client side.
You may be safe using as few as two 'byte' packets per block/item id.

**Comment by cobra** [comment]
And how do you assemble them again without creating a mess? They might arrive in any order and at any time.

**Comment by BluSunrize** [comment]
@cobra To me, the commands look like they work? "get" returns the override with priority to the normal mineral found, "set" sets the override and it persists after exiting and restarting the instance, and "setDepletion" saves as well, from what I've seen.

**Comment by cobra** [comment]
It didn't do that for me. Strange.

**Comment by cobra** [comment]
![2015-10-16_09 26 23](https://cloud.githubusercontent.com/assets/163331/10536012/025d945a-73e8-11e5-9d84-d2ddde442cf7.png)

**Comment by BluSunrize** [comment]
When you get the chance, try against my latest two commits, which made commands fancier in general and added some markDirty() for the save data

**Comment by cobra** [comment]
This seems to be working - for the command version. The Sampe Drill is still telling me the same, but that should be the necessary change for the ExcavatorHandler: https://github.com/cobra/ImmersiveEngineering/commit/558b3080b5a06c01357ff5ad1eadfc0c57fe5a49
Do you want to "steal" it manually from there and commit it yourself or should I PR this whole branch (minus the changes to CommandMineral)? I'm just replaying that stuff anyway because of your latest changes.

Also, what do you think about my excavator changes related to this issue? I'll do a PR if you want them, but I'd make the anti-stutter threshold depend on the configured speed before submitting.

**Comment by BluSunrize** [comment]
PR your thing, I'm lazy x3

**Comment by cobra** [comment]
will do, just wait a few minutes unless you're too lazy for that :D

**Comment by cobra** [comment]
There you go. Just tested it once again, works perfectly.
