### ISSUE TITLE
[1.14.4 Alpha] Blast Furnace Preheater renders incorectly

### ISSUE THREAD

**Issue by TooManyKitKats** [BluSunrize/ImmersiveEngineering#3682]
Description of the issue:
The Blast Furnace Preheater does not render the top panel of the first layer, leaving it seethru and able to see into walls. When some objects (such as the turret) are placed next to it their opacity decreases.

Crashlog:
No crashlog this is purely a visual issue

Versions & Modlist
The only mods are IE version: ImmersiveEngineering-0.14-93
and Forge-28.2.3
![IE 1 14 4 Alpha Blast Furnace Preheater Render](https://user-images.githubusercontent.com/62522289/77332385-66c38400-6cf8-11ea-8f12-0ed12b7ca5c4.png)
![IE 1 14 4 Alpha Blast Furnace Preheater Wall](https://user-images.githubusercontent.com/62522289/77332387-675c1a80-6cf8-11ea-8571-cc621f8c42ea.png)
![IE 1 14 4 Alpha Turret](https://user-images.githubusercontent.com/62522289/77332390-67f4b100-6cf8-11ea-9993-36be1a93abf6.png)

**Comment by BluSunrize** [comment]
Fixed by
https://github.com/BluSunrize/ImmersiveEngineering/commit/db2147a06eea56f1a062ce3586a7137614328419
