### ISSUE TITLE
Mod Pack Issue 

### ISSUE THREAD

**Issue by schminus** [BluSunrize/ImmersiveEngineering#3688]
Im Playing with friends on a Mod pack Server. But Immersive Engineering dont work like it should. Only a few Items are listed on Just Enough Items, but in Creative Mode i can use the missing items but i cant craft them in Survival mode. Could it be a Problem with the Modpack?

**Comment by BluSunrize** [comment]
Sounds a lot like a problem with the modpack.
Use the issue template that you so rudely ignored and provide more info, or else we won't be able to help you.

**Comment by schminus** [comment]
![2020-03-23_19 40 32](https://user-images.githubusercontent.com/62566653/77352055-dd837000-6d3e-11ea-95ba-d70d3a87cf7a.png)
![2020-03-23_19 41 28](https://user-images.githubusercontent.com/62566653/77352062-dfe5ca00-6d3e-11ea-94f6-bf58a748b362.png)

**Comment by BluSunrize** [comment]
Well, I guess the issue is closed ¯\_(ツ)_/¯
