### ISSUE TITLE
Skyhook allows you to skyline into multiblocks

### ISSUE THREAD

**Issue by ZiaAvenicia** [BluSunrize/ImmersiveEngineering#369]
I know the sky lines are still a work in progress, but I think this may be a bug. . . http://i.imgur.com/7Cr6ONL.gif

**Comment by BluSunrize** [comment]
Funky! Will look into it, thanks!

In other news: That looks like a skyblock map! Is there a skyblock that actually does stuff with IE then? :D

**Comment by ZiaAvenicia** [comment]
It's a modpack I threw together that mixes Botania - Garden of Glass and IE. I might look into publishing it in the future, once I make a few tweaks here and there.

**Comment by BluSunrize** [comment]
Sounds cool! =3

**Comment by theunkn0wn1** [comment]
Sorry for breathing life into this dead thread but this issue is still occuring today (12/07/2015) against build cc3c69e202664f6abdf5

**Comment by BluSunrize** [comment]
And it will keep existing. Deal with it.
