### ISSUE TITLE
[1.14.4] Chest minecart crash

### ISSUE THREAD

**Issue by basilserpent** [BluSunrize/ImmersiveEngineering#3696]
[crash-2020-03-25_22.28.39-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4383621/crash-2020-03-25_22.28.39-client.txt)
Game crashes to desktop after loading in a chestminecart. Issue only persists with IE version 0.14-93 on Forge 28.2.3

**Comment by BluSunrize** [comment]
Duplicate of #3678

Please check for similar issues and follow the template and guidelines.
