### ISSUE TITLE
[1.12.2 Immersive Engineering. Cant transfer IF to any other types of energy. Please, help!]

### ISSUE THREAD

**Issue by gogi47** [BluSunrize/ImmersiveEngineering#3698]
Can u please help me. I really dont understand how to transfer IF energy to EU. Tried  so many thing, but didnt get results. If it will be easier for u, i need to connect my IF to IC2 Furnace, that wants EU.

**Comment by BluSunrize** [comment]
You can't. That conversion was removed, IE does not not provide such a feature.
There are other mods that can do this, such as Industrial Wires.

Also, follow the issue template next time, or your issue will be closed without comment.

**Comment by cryptearth** [comment]
Just out of curiosity: Was it IE dropped that support - or IC2?

**Comment by BluSunrize** [comment]
It was IE. A balance decision made after a detailed discussion with player, the developer of IC2.
