### ISSUE TITLE
Minecart problem [1.14, forge 28.2.4]

### ISSUE THREAD

**Issue by ribs498** [BluSunrize/ImmersiveEngineering#3699]
Minecarts with, hoppers, chests, furnaces will immediatly crash the game. only mod active is Immersive engineering 0.14-93, 1.14
crash report: https://pastebin.com/XKWmQvNb

**Comment by Rexxios** [comment]
crash report: https://pastebin.com/U4HCB8zt

I second this, IE 0.14-93, MC 1.14.4

**Comment by malte0811** [comment]
Duplicate of #3678
