### ISSUE TITLE
Several Issues

### ISSUE THREAD

**Issue by Thorinori** [BluSunrize/ImmersiveEngineering#37]
These may have been solved but not in the current code on Git, but Crusher doesn't use its energy buffer, and I have not been able to crush ores with the hammer like the in-game documentation says. Otherwise, great mod! Loving it all so far, especially the crusher!

**Comment by jte132** [comment]
The github is no longer being updated by the author.

**Comment by Thorinori** [comment]
Ah I wasn't aware he stopped updating github, especially since he mentioned on reddit that compiling it from  here was basically the only way to test the mod

**Comment by BluSunrize** [comment]
Yeah the version on here will be terribly updated till I go into public beta and start pushing again.
The energy buffer thing is long since fixed and the hammer crushing is only enabled if no other mod adds pulverizers
