### ISSUE TITLE
[1.14.4 Alpha] LV Wire render incorrectly (likely other wires)

### ISSUE THREAD

**Issue by TooManyKitKats** [BluSunrize/ImmersiveEngineering#3701]
Description of the issue:
when making a wire run strait down it render incorectly, it fades in and out from opaque to transparent
Crashlog:
purely visual
Versions & Modlist
ImmersiveEngineering-0.14-93-db2147a0.jar
and Forge 28.2.3
and JEI
![image](https://user-images.githubusercontent.com/62522289/77601393-06436b00-6ee1-11ea-8322-6abd2fb6dc5f.png)
![image](https://user-images.githubusercontent.com/62522289/77601404-08a5c500-6ee1-11ea-9bfa-d4623b3f573c.png)

**Comment by TooManyKitKats** [comment]
![image](https://user-images.githubusercontent.com/62522289/77601556-73570080-6ee1-11ea-8767-72767385cbe3.png)
It gets worse (idk if this helps)

**Comment by malte0811** [comment]
The original issue was an easy fix (I'll push it in a few minutes), the "it gets worse" *is* worse. I've had that happen once while porting, but never managed to reproduce the issue properly. Is this setup causing the issue reliably? Is this on the IE server (and if so, where)?

**Comment by TooManyKitKats** [comment]
![image](https://user-images.githubusercontent.com/62522289/77761822-ff1a7b00-700e-11ea-9f83-b3cd799f99cd.png)
From what I can tell it doesn't actually effect the transport of power at all, this is in this server ^coordinates above

**Comment by malte0811** [comment]
It looks alright now, at least for me. Please put a comment here if this happens again.
