### ISSUE TITLE
[1.14.4-93 alpha] lot's of issues

### ISSUE THREAD

**Issue by cryptearth** [BluSunrize/ImmersiveEngineering#3702]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

- Did so - and found a lot of issues already fixed - hence the reason for this one - as I don't see any other way of asking this ...

### Description of the issue:
Describe what happens, how it affects your game/gameplay and provide screenshots where possible.

- Short and simple: Did you even tried it yourself before pushing it to the public? Ok, not encounter any chest-minecarts may can happen if you get unlucky or just try without generating structures at all - but, I mean, c'mon - the first someone does with this new alpha: download forge (btw: as forge did the mistake again and did a pretty major change hidden behind just a minor build update - (28.2.1 -> 28.2.2) a explicit note about the correct version this is built against would had been helpful) - put together a small test world - and hop into - so chances are high that at least by chance someone encounter a mineshaft in the spawn chunks. This render issue many others reported should had been triggered just by chance while testing.

### Crashlog:
If your Minecraft instance has crashed, a file will have been generated in the folder `crash-reports` of your minecraft folder. To understand what has happened, we need to know the content of that file. But please don't just put it directly in your report (that makes it hard to read), upload it to a site like [pastebin](http://pastebin.com) or [gist](http://gist.github.com) and put a link in the actuall bug report.

- Doesn't apply here ...

### Versions & Modlist
IE and Forge versions are mandatory. *Note that saying "latest" is **not** valid. Always give the proper version number*
Other mods should be listed (with their versions) in a [pastebin](http://pastebin.com) or [gist](http://gist.github.com) upload. The easiest way to get these lists is a crashlog, you may force one with F3+C.
If your game crashed (see above) you may omit the modlist, but IE and Forge version would still be nice.

Also, please try testing an issue in a minimal instance, with just IE, Forge and maybe JEI. That makes elminating compat issues easier.

- Did so - Java13 > crash, Java12 > crash, Java11 > crash, Java10 > able to launch the game > create world > crash ... tried going down to Java8 > same. Then tested lower Forge version (already mentioned above) > ClassCastException (uhm yea - not your fault but of Forge - happend in the past the same way - those people over there ...)

### Lastly (you may delete this from the report itself)
Please, for the love of all that is voxelbased, **read the contribution guidelines. They are linked to the right in the message box.**
When reporting issues, these are crucial, and the team withholds the right to close an issue for the plain stupidity of not reading and adhering to them.

Thank you for reporting issues, without people reporting them, they wouldn't get fixed. You're helping contribute to this mod and that is much appreciated <3

- "without people reporting them, they wouldn't get fixed" - Hate to say it - but: With proper self testing before release to public there weren't no issues needed to be reported ... just sayin
Feel free to do what about anyone else does: rant about me and lock it down without me having a chance to may reply to your reply - well, just don't do it or you'll get my reply in just another issue - and just like google a repo doesn't forget ...

**Comment by BluSunrize** [comment]
> Did you even tried it yourself before pushing it to the public? 
I sure did. And I installed latest Forge, using the twitch launcher, as always. Worked perfectly fine. Also, it's "did you even try". You doubled up on your past tense there.

> Java13 > crash, Java12 > crash, Java11 > crash, Java10 ...
Curseforge *clearly* states that this mod is inteded for use with Java 8 *only*:
![curseforge](https://i.imgur.com/cJga42t.png)
If you didn't bother reading that, that's on you.

> well, just don't do it or you'll get my reply in just another issue - and just like google a repo doesn't forget
Cute of you to threaten us like that. Weren't it for the fact that I can absolutely delete issues from this repo.

Also, if you already know that "everybody rants about you", have you considered that the problem is you, not them?
