### ISSUE TITLE
just an improvement idea for the template

### ISSUE THREAD

**Issue by mindforger** [BluSunrize/ImmersiveEngineering#3703]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already **(also check already CLOSED issues!)**. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

...

**Comment by cryptearth** [comment]
This is more of a fault of how the issue search works in itself - as the "default" adds this "isClosed" - wich many don't even know what it means or how it works. But good idea to explicit note about checking also the closed ones (but I doubt many will do so).

**Comment by BluSunrize** [comment]
Given that people just *delete the fucking template* I doubt this'd help.
