### ISSUE TITLE
[1.14.4] world gen glitches

### ISSUE THREAD

**Issue by cryptearth** [BluSunrize/ImmersiveEngineering#3704]
>>Did you even tried it yourself before pushing it to the public?

>I sure did. And I installed latest Forge, using the twitch launcher, as always. Worked perfectly fine. Also, it's "did you even try". You doubled up on your past tense there.

So you got lucky upon not encountering any auto-generated ChestMinecart in a mineshaft below you - but as some rendering was overridden it should had been tested if it doesn't affect any vanilla. Also: I'm not an english native and always struggled about tense at school - so I just don't care if I get it right or wrong.

>>Java13 > crash, Java12 > crash, Java11 > crash, Java10 ...

>Curseforge *clearly* states that this mod is inteded for use with Java 8 *only*:
![curseforge](https://i.imgur.com/cJga42t.png)
If you didn't bother reading that, that's on you.

Well - joke's on you at this point - it's adviced throughout the Java community to use at least version 11. In fact, Java 14 was released just last week. It's all this bytecode-low-level-ASM-crap Forge requires that the whole modding community is stuck at such old Java versions - but hey - what do I expect from someone preceeding interfaces with a capital I - and by this "violating" Java coding conventions? All that fancy behind-the-scenes magic can't be much better than bad source style ...

>>well, just don't do it or you'll get my reply in just another issue - and just like google a repo doesn't forget

>Cute of you to threaten us like that. Weren't it for the fact that I can absolutely delete issues from this repo.

You again completely missed the point on it - it's not me anybody threatening - it's just sayin: "well - close it cause you don't wanna talk about it? k - I'll use the spamming way then by just open another issue" - and sure, may you can make it not showing up public anymore - but do you really think just because you hit "delete repo" it's really deleted with all its contents from the backup drives?

>Also, if you already know that "everybody rants about you", have you considered that the problem is you, not them?

Well, I'm someone not hiding behind the non-exisiting anonymity of the internet (in fact - there'Re so many traces it would be hard even try to hide my identity) - but I shout out loud what I think - and the main issue is that many just either don't care or don't want a public argue about what they messed up - and the only way they see is just blocking me of instead of at least try to argue - just like you. And my reaction to this ignorance is anger - so, think for yourself - what would had been the smarter choice: blocking someone off and by this action show your "IDGAF" attitude - or act professional no matter the tone you were spoken to and still try to give a shot at least once?

**Comment by BluSunrize** [comment]
This is not the Java community. This is the Minecraft Modding and Forge community. You were told this in regards to codestyle and convention when you tried to rant about Forge on naming their interfaces.

My "IDGAF" attitude stems from years of dealing with people trying to tell me how to run this project. A project that Malte, me and the other contributors develop as a hobby. In our free time. For free.

If this were my job and you were a customer, I'd be courteous, professional, responsive - and escalate you to my superior upon threat of spamming this repo.

But here? I **am** the superior. So I just get remove you from this repo. Have nice day.
