### ISSUE TITLE
[1.14.4][0.14-93] Conflicting with Minecart with Chest

### ISSUE THREAD

**Issue by DamondSword2247** [BluSunrize/ImmersiveEngineering#3708]
The mod causes an entity rendering crash with the vanilla minecart with chest.

Steps for crash (that assuming your client doesn't crash as soon as you load into a world)

1. Place Minecart Chest into world

[crash-2020-03-26_08.50.39-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4387234/crash-2020-03-26_08.50.39-client.txt)

IE version: 0.14-93
Forge version: forge-28.2.3

**Comment by BluSunrize** [comment]
Duplicate.
Use the search function.

**Comment by DamondSword2247** [comment]
How is it a duplicate?

**Comment by BluSunrize** [comment]
Because it's been reported multiple times, and you didn't check in advance like hte issue template told you to.
#3699
#3678
