### ISSUE TITLE
1.14.4 Game wont start

### ISSUE THREAD

**Issue by nukelerman** [BluSunrize/ImmersiveEngineering#3709]
When the game is launched it just crashes and says;
The game crashed whilst initializing game
Error: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

https://pastebin.com/SEghHiSk

### Versions & Modlist
IE - 0.14. - 93
Forge - 1.14.4 - 28.2.0
Mod list - https://imgur.com/a/oMaCzXi

I tried it with just IE and it still crashed

This might just be me being stupid, but I was wondering if there was anything I could do to fix this?

Thanks

**Comment by malte0811** [comment]
Update Forge to 28.2.3.
