### ISSUE TITLE
[1.14] ChestMinecartEntity client side crash

### ISSUE THREAD

**Issue by anqingchen** [BluSunrize/ImmersiveEngineering#3712]
### Description of the issue:
Join the game, world gen has ChestMinecart, client crashes soon after. Server remains live.

### Crashlog:
[pastebin](https://pastebin.com/6iiKmF10)

### Versions & Modlist
ImmersiveEngineering-0.14-93
Playing in the Enigmatica 4 0.5 Modpack

**Comment by anqingchen** [comment]
nvm, just realized it's fixed in #3678

**Comment by Frogwisard1984** [comment]
im still having this problem

**Comment by BluSunrize** [comment]
**because there is no new version yet** >_>
