### ISSUE TITLE
Enigmatica 4 crashes after latest update. 

### ISSUE THREAD

**Issue by Frogwisard1984** [BluSunrize/ImmersiveEngineering#3718]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
Describe what happens, how it affects your game/gameplay and provide screenshots where possible.

### Crashlog:
https://gist.github.com/Frogwisard1984/b1208f146bf93c1cb042be9d2fcb5589

**Comment by malte0811** [comment]
Duplicate of #3678
