### ISSUE TITLE
[1.14.4] Warning when launching server with immersive

### ISSUE THREAD

**Issue by uiytt** [BluSunrize/ImmersiveEngineering#3724]
### Description of the issue:
I got this when I launched my server...
I know it only happen the first time but still not cool to have that when trying to debug :/

### Not crashlog:
[pastebin](https://pastebin.com/yPw9VXG0) 

### Versions & Modlist
Forge 28.2.3
Minecraft 1.14.4
ImmersiveEnginering : 0.14-93
Mod : None other than this one

### Lastly
Thank you for your amazing work !!!!
It's really so good to play with this mod :D

**Comment by BluSunrize** [comment]
Is this a fresh server with a newly created world, or did you try to update from 1.12?

**Comment by uiytt** [comment]
Fresh new world on a fresh new server

**Comment by BluSunrize** [comment]
Interestingly enough, I'm not seeing any of those messages when trying it on my server.

Could you give it another test with the new IE version (1.14-94) and provide your entire logfile?

**Comment by uiytt** [comment]
It doesn't change anything (I'm on linux btw)
https://pastebin.com/ExqLh7Zx

**Comment by malte0811** [comment]
Linux shouldn't be a problem, I've done all my porting on Linux. The datafixer warnings are normal, as no one has figured out how to hook mods into the new type-theory datafixers. The config errors aren't normal, could you upload `~/Téléchargements/serv/config/immersiveengineering-common.toml`?

**Comment by uiytt** [comment]
Here it is : https://pastebin.com/wH1fhShN 
(I didn't change anything)

**Comment by malte0811** [comment]
Can you try deleting it and having Forge generate a new one? For some reason that file contains 2 full IE configs, one starting at line 1, one at line 447. I have no idea why this happened (automatically generating configs works just fine for me), and the Forge config seems to have the same problem in your logs. If it happens again, please upload the full log (`~/Téléchargements/serv/logs/debug.log`) for the first run where it fails.

**Comment by uiytt** [comment]
Still happening : https://pastebin.com/Aa7DVNJa
But at least the config does not contain two configs... : https://pastebin.com/m97AwUQ0

**Comment by malte0811** [comment]
Try correcting the Forge/fml config as well, I'm not sure whether it's even looking at the IE config file once it fails to load the Forge one.

**Comment by uiytt** [comment]
Both were deleted

**Comment by BluSunrize** [comment]
What's the status of this?

**Comment by uiytt** [comment]
Well, I don't have a server anymore.
I guess you can close that if no one else has this error
