### ISSUE TITLE
[1.14.4] Crash relating to minecart chests

### ISSUE THREAD

**Issue by cybercat5555** [BluSunrize/ImmersiveEngineering#3726]
### Description of the issue:
When generating a new world and exploring out, a crash occurs relating to minecart chests, and IE seems to be the source 

### Crashlog:
[crash-2020-03-28_17.01.08-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4397902/crash-2020-03-28_17.01.08-client.txt)

### Versions & Modlist
Forge 28.2.3
IE 0.14-93
Other mods: 
[list.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4397906/list.txt)

**Comment by BluSunrize** [comment]
This is the 8th duplicate or so.
Use the search function for goodness sake.
