### ISSUE TITLE
[1.14.4] Crash on launch 

### ISSUE THREAD

**Issue by Squirrel-7** [BluSunrize/ImmersiveEngineering#3728]
Description of the issue: When launching  ImmersiveEngineering-0.14-93 the game crashes saying, "The game crashed whilst initializing game
Error: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException"
Crashlog: https://pastebin.com/rwqcixAG

**Version: I'm using forge 28.2.0 and ImmersiveEngineering-0.14-93 because the server I plan to use it on cannot use forge 28.2.3**(I looked at a comment with the same issue, but I can't use it because of the server, could you please fix it?)

I already tested IE on its own, it had the same result

**Comment by Squirrel-7** [comment]
If you can't, that's ok too. What could be better is if you know another forge version that works! Thank you anyways!

**Comment by ASRSProjects** [comment]
The mod launches with 28.2.3 for me.

**Comment by Squirrel-7** [comment]
I know it works, but the server platform we're using doesn't allow it as an option

**Comment by BluSunrize** [comment]
I can't "fix" an old version.
Immersive Engineering 1.14.4-94 is the latest release which may include a solution for this issue.
If you won't use that, I can't help you.

That said, I see no reason that a server *couldn't* use forge 28.2.3, it's literally as easy as dragging the file on there.
