### ISSUE TITLE
Looking up Arc Furnace recipes thru NEI crashes game after minetweaker script

### ISSUE THREAD

**Issue by blade1981m** [BluSunrize/ImmersiveEngineering#373]
I am working on replacing the Arc Furnace recipes to use the Thermal Foundation slag instead and so have the following minetweaker script:-
```
import mods.immersiveengineering.ArcFurnace;
val slag = <ThermalExpansion:material:514>;
mods.immersiveengineering.ArcFurnace.removeRecipe(<ImmersiveEngineering:metal:7>);
mods.immersiveengineering.ArcFurnace.addRecipe(<ImmersiveEngineering:metal:7>, <ore:ironIngot>, slag, 400,  512, [<ore:cokeDust>]);
mods.immersiveengineering.ArcFurnace.addRecipe(<ImmersiveEngineering:metal:7>, <ore:ironDust>, slag, 400,  512, [<ore:cokeDust>]);
```

After relaunching the game trying to look up the Arc Furnace recipes in NEI causes the game to crash with the following stack trace:-

```
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Unknown Source)
	at net.minecraft.client.Minecraft.func_99999_d(Unknown Source)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

If I look up Arc Furnace recipes that do not include the new ones I created it does not crash so if I look up all recipes for the IE Slag the remaining Arc Furnace recipes do show ok.

**Comment by BluSunrize** [comment]
full log to pastebin or something similar please, that stacktrace looks incomplete.

**Comment by AEnterprise** [comment]
the latest fml log would be needed i guess, the provided stacktrace shows a crash while adding world info to the crash report

**Comment by blade1981m** [comment]
Apologies, I thought the stacktrace was the main piece that was needed.

[Crash Log](http://pastebin.com/rERMSAAu)

Having issues uploading the latest FML log to pastebin due to size, let me know if there is a specific part of it you need. It looks like a large portion of it is the same as the crash log.

**Comment by AEnterprise** [comment]
crash log sais it crashed while generating a crashlog, i sugest trying gist for the log, if that doesn't accept it due to its size then try if you can provide the part starting afther the spam of forge MC patches

**Comment by BluSunrize** [comment]
Yeah, I can't trace that :/

**Comment by blade1981m** [comment]
Ok, not sure which part you mean by the forge MC patch spam, but turns out gist let me upload the whole thing anyway:-

[FML Latest Client Log](https://gist.githubusercontent.com/blade1981m/c70736a477655597f50b/raw/147bb54d9a60eea85f20d26d561325204f10e456/gistfile1.txt)

**Comment by mindforger** [comment]
hmm ... is this the right log file ?? 
>[21:30:31] [Client thread/DEBUG] [INpureCullingEngine/]: override called. Params: MineFactoryReloaded, tile.mfr.stainedglass.block, 0
>[21:30:31] [Client thread/DEBUG] [INpureCullingEngine/]: hide called. Params: MineFactoryReloaded:fluid.mfr.liquid.milk.still, 0
>[21:30:31] [Client thread/DEBUG] [INpureCullingEngine/]: override called. Params: MineFactoryReloaded, tile.mfr.stainedglass.pane, 0
>[21:30:31] [Client thread/DEBUG] [INpureCullingEngine/]: override called. Params: MineFactoryReloaded, tile.mfr.conveyor, 0
>[21:30:31] [Netty Client IO #0/INFO] [THAUMCRAFT/]: Restoring client configs.
>[21:30:31] [Netty Client IO #0/INFO] [mcjty.varia.Logging/]: Disconnect from server: Unregistering RFTools dimensions
>[21:30:31] [Netty Client IO #0/INFO] [simplyjetpacks/]: Loading configuration files
>[21:30:31] [Client thread/INFO] [journeymap/]: Mapping halted in C:\Users\Colin\Minecraft\Instances\Y.A.K.S. Pack\journeymap\data\sp\New World\DIM0
>[21:30:31] [Netty Client IO #0/DEBUG] [OpenMods/]: openmods.network.IdSyncManager.onDisconnect(IdSyncManager.java:124): Disconnected, restoring local data

i can't see any crash at all ... this more looks like you started the game and ended it right after it loaded !?!?

**Comment by BluSunrize** [comment]
Yeah sorry, with that clusterf- of a kitchen sink pack, there's not much I can do to help you.

**Comment by AEnterprise** [comment]
can you delete the log files and then re-create the crash to make sure you have the right file?

**Comment by blade1981m** [comment]
Ok, I decided to make a simple modpack to test, just to verify it isn't something to do with the mass amount of mods in the pack I am working on. This one just has IE, NEI and MineTweaker in it and the error still happened. This time though, the error log seems to be a little more useful.

[Crash Log] (https://gist.github.com/blade1981m/97271699bbf491b21b19)

**Comment by blade1981m** [comment]
Seeing as the other script was to try and replace IE slag with Thermal slag and this test pack does not have any COFH stuff in it, I substituted the slag for gunpowder. Here is the minetweaker script I used for this pack:-

````
import mods.immersiveengineering.ArcFurnace;
mods.immersiveengineering.ArcFurnace.removeRecipe(<ImmersiveEngineering:metal:7>);
mods.immersiveengineering.ArcFurnace.addRecipe(<ImmersiveEngineering:metal:7>, <ore:ironIngot>, <minecraft:gunpowder>, 400,  512, [<ore:cokeDust>]);
mods.immersiveengineering.ArcFurnace.addRecipe(<ImmersiveEngineering:metal:7>, <ore:ironDust>, <minecraft:gunpowder>, 400,  512, [<ore:cokeDust>]);
````

**Comment by BluSunrize** [comment]
I have fixed the issue, none the less, the issue is that your are using a wrong MT script. OreDictionary entries are usually always formatted type+ore, so "ingotIron" and "dustIron", not "ironDust"

**Comment by blade1981m** [comment]
:pensive: My apologies. I am usually much better at double-checking my scripts when something goes wrong. 

Thank you for adding in a fix anyways.
