### ISSUE TITLE
[14.4] WorldGen lag and Crash

### ISSUE THREAD

**Issue by Kuiki86** [BluSunrize/ImmersiveEngineering#3730]
Hi,

Today i added immersive engineering to my private server on host-unlimited (Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz, 16GB Ram, Java 8, 232)

After adding it to the mods that were already running, everytime the server has to generate new chunks it starts to lag and i got the console message: "move to quick". Dont know if its caused by IE alone or in combination with all the mods.

The Crashlog I get the first time is uploaded:

https://filehorst.de/d/ddunovql

### Versions & Modlist

	FML: 28.2
	Forge: net.minecraftforge:28.2.3
	FML Language Providers: 
		javafml@28.2
		minecraft@1
		kotlinfml@1.4.0	

> Mod List: 

		inventorysorter-1.14.4-16.2.0.jar Simple Inventory Sorter {inventorysorter@16.2.0 DONE}
		Cucumber-1.14.4-2.0.6.jar Cucumber Library {cucumber@2.0.6 DONE}
		NetherPortalFix_1.14.4-7.0.0.jar NetherPortalFix {netherportalfix@7.0.0 DONE}
		pamhc2trees-1.14.4-1.0.0.jar Pam's HarvestCraft 2 Fruit Trees {pamhc2trees@version DONE}
		craftingstation-2.1.6.jar Crafting Station {craftingstation@2.1.6 DONE}
		jei-1.14.4-6.0.0.27.jar Just Enough Items {jei@6.0.0.27 DONE}
		Druidcraft-1.14-0.3.1.jar Druidcraft {druidcraft@0.3.1 DONE}
		AttributeFix-1.14.4-3.0.3.jar AttributeFix {attributefix@3.0.3 DONE}
		justenoughbuttons-1.14.4-1.0b.jar Just Enough Buttons {justenoughbuttons@1.14.4-1.0 DONE}
		Upgrade-Aquatic-1.14.4-v1.4.10.jar Upgrade Aquatic {upgrade_aquatic@1.4.9 DONE}
		IronJetpacks-1.14.4-2.0.3.jar Iron Jetpacks {ironjetpacks@2.0.3 DONE}
		create-mc1.14.4_v0.2.2a.jar Create {create@mc1.14-0.2.2a DONE}
		Waystones_1.14.4-5.1.1.jar Waystones {waystones@5.1.1 DONE}
		ForgeEndertech-1.14.4-5.2.1.0-build.0076.jar Forge Endertech {forgeendertech@5.2.1.0 DONE}
		Clumps-4.0.1.jar Clumps {clumps@4.0.1 DONE}
		journeymap-1.14.4-5.7.0b1.jar Journeymap {journeymap@1.14.4-5.7.0b1 DONE}
		Placebo-1.14.4-2.3.5.jar Placebo {placebo@2.3.5 DONE}
		comforts-FORGE-1.14.4-2.0-beta6.jar Comforts {comforts@FORGE-1.14.4-2.0-beta6 DONE}
		citadel-1.0.4-1.14.4.jar Citadel {citadel@1.0.4 DONE}
		tumbleweed-1.14-0.4.7.jar Tumbleweed {tumbleweed@1.14-0.4.7 DONE}
		SimpleStorageNetwork-1.14.4-0.2.0.jar Simple Storage Network {storagenetwork@1.14.4-0.2.0 DONE}
		SereneSeasons-1.14.4-2.0.0.40-universal.jar Serene Seasons {sereneseasons@1.14.4-2.0.0.40 DONE}
		NetehrOverhaul1.14.4Ver1.7.jar NetherUpdate {netherupdate@1.0.0 DONE}
		betteranimalsplus-1.14.4-8.2.1.jar Better Animals Plus {betteranimalsplus@8.2.1 DONE}
		FarmingForBlockheads_1.14.4-5.3.2.jar Farming for Blockheads {farmingforblockheads@5.3.2 DONE}
		Bookshelf-1.14.4-4.4.71.jar Bookshelf {bookshelf@4.4.71 DONE}
		BotanyPots-1.14.4-1.0.10.jar BotanyPots {botanypots@1.0.10 DONE}
		The-Endergetic-Expansion-1.14.4-v1.2.0.jar The Endergetic Expansion {endergetic@1.2.0 DONE}
		buildinggadgets-3.1.1b.jar Building Gadgets {buildinggadgets@3.1.1b DONE}
		mcjtylib-1.14-3.5.17-alpha.jar McJtyLib {mcjtylib@1.14-3.5.17-alpha DONE}
		rftoolsbase-1.14-0.0.12-alpha.jar RFToolsBase {rftoolsbase@1.14-0.0.12-alpha DONE}
		Morpheus-1.14.4-4.2.44.jar Morpheus {morpheus@version DONE}
		WaterStrainer-1.14.4-7.0.2.jar Water Strainer {waterstrainer@1.14.4-7.0.2 DONE}
		walljump-1.14.4-1.3.1.jar Wall-Jump! {walljump@1.14.4-1.3.1 DONE}
		PackingTape-1.14.4-0.9.2.jar Packing Tape {packingtape@0.9.2 DONE}
		mininggadgets-1.2.3.jar Mining Gadgets {mininggadgets@1.2.3 DONE}
		JustEnoughResources-1.14.4-0.10.1.76.jar Just Enough Resources {jeresources@0.10.1.76 DONE}
		CraftTweaker-1.14.4-5.0.1.165.jar CraftTweaker {crafttweaker@5.0.1.165 DONE}
		rftoolspower-1.14-1.2.12-alpha.jar RFToolsPower {rftoolspower@1.14-1.2.12-alpha DONE}
		extradisks-1.14.4-1.1.jar Extra Disks {extradisks@1.14.4-1.1 DONE}
		swampexpansion-1.4.9.jar Swamp Expansion {swampexpansion@NONE DONE}
		forge-1.14.4-28.2.3-universal.jar Forge {forge@28.2.3 DONE}
		RefreshedNether v.1.9 (1.14.4).jar Refreshed Nether {refreshed_nether@1.9.0 DONE}
		refinedstorage-1.7.3.jar Refined Storage {refinedstorage@1.7.3 DONE}
		ironchest-1.14.4-9.1.5.jar Iron Chests {ironchest@1.14.3-9.0.3 DONE}
		forge-1.14.4-28.2.3-server.jar Minecraft {minecraft@1.14.4 DONE}
		industrial-foregoing-1.14.4-2.1.2-582ea8b.jar Industrial Foregoing {industrialforegoing@2.1.2 DONE}
		rftoolsutility-1.14-1.2.14-alpha.jar RFToolsUtility {rftoolsutility@1.14-1.2.14-alpha DONE}
		theoneprobe-1.14-1.4.37.jar The One Probe {theoneprobe@NONE DONE}
		swingthroughgrass-1.14.4-1.3.2.jar SwingThroughGrass {swingthroughgrass@1.14.4-1.3.2 DONE}
		titanium-1.14.4-2.2.10.jar Titanium {titanium@2.2.10 DONE}
		stonecatalysts-1.14.4-1.2.0.jar StoneCatalysts {stonecatalysts@1.14.4-1.2.0 DONE}
		ImmersiveEngineering-0.14-94.jar Immersive Engineering {immersiveengineering@0.14-94 DONE}
		BiomesOPlenty-1.14.4-9.0.0.262-universal.jar Biomes O' Plenty {biomesoplenty@1.14.4-9.0.0.259 DONE}
		baubles-1.6.1-1.14.4.jar Baubles {baubles@1.6.1 DONE}
		pamhc2crops-1.14.4-1.0.3.jar Pam's HarvestCraft 2 Crops {pamhc2crops@version DONE}
		AdLods-1.14.4-2.0.0.1-build.0078.jar Large Ore Deposits {adlods@2.0.0.1 DONE}
		packedup-1.0.5-mc1.14.jar PackedUp {packedup@1.0 DONE}
		atmospheric-1.14.4-1.1.2.jar Atmospheric {atmospheric@1.1.2 DONE}
		simplybackpacks-1.14.4-1.4.3.jar Simply Backpacks {simplybackpacks@1.14.4-1.4.3 DONE}
		Bountiful-1.14.4-3.1.0.jar Bountiful {bountiful@1.14.4-3.1.0 DONE}
		rftoolsbuilder-1.14-1.2.12-alpha.jar RFToolsBuilder {rftoolsbuilder@1.14-1.2.12-alpha DONE}
		curios-FORGE-1.14.4-1.0.6.1.jar Curios API {curios@FORGE-1.14.4-1.0.6.1 DONE}
		Botania r1.11-378.jar Botania {botania@r1.11-378 DONE}
		Patchouli-1.14.4-1.1-26.jar Patchouli {patchouli@1.14.4-1.1-25 DONE}
		AutoRegLib-1.4-35.jar AutoRegLib {arl@1.4-35 DONE}
		rftoolsstorage-1.14-0.0.7-alpha.jar RFToolsStorage {rftoolsstorage@1.14-0.0.7-alpha DONE}
		rats-4.0.2-1.14.4.jar Rats {rats@4.0.2 DONE}
		FastWorkbench-1.14.4-2.1.4.jar FastWorkbench {fastbench@2.1.4 DONE}
		ClothConfig2-1.4.1.jar Cloth Config Forge v2 API {cloth-config2@1.4.1 DONE}
		autumnity-1.0.0-1.14.4.jar Autumnity {autumnity@1.0.0 DONE}
		StorageDrawers-1.14.4-6.0.7.jar Storage Drawers {storagedrawers@1.14.4-6.0.6 DONE}
		betteranimals-1.14.4-5.3.0.jar Cyber's Better Animal Models {betteranimals@5.3.0 DONE}
		themidnight-0.4.6.jar The Midnight {midnight@0.4.6 DONE}
		lostcities-1.14-2.0.28-alpha.jar LostCities {lostcities@1.14-2.0.28-alpha DONE}
		libnonymous-1.14.4-1.0.4.25.jar Libnonymous {libnonymous@1.0.4.25 DONE}
		BonsaiTrees-2.0.2.35.jar Bonsai Trees 2 {bonsaitrees2@2.0.2.35 DONE}
		tombstone-4.3.1-1.14.4.jar Corail Tombstone {tombstone@4.3.1 DONE}
		Quark-r2.0-212.jar Quark {quark@r2.0-212 DONE}
		Vampirism-1.14.4-1.6.0-beta.6.jar Vampirism {vampirism@1.6.0-beta.6 DONE, teamlapenlib@1.6.0-beta.6 DONE}
		engineersdecor-1.14.4-1.0.20-b2.jar Engineer's Decor {engineersdecor@1.0.20-b2 DONE}
		AI-Improvements-1.14.4-0.3.0.jar AI-Improvements {aiimprovements@0.2.2 DONE}
		Aquaculture-1.14.4-2.0.7.jar Aquaculture 2 {aquaculture@1.14.4-2.0.7 DONE}
		refinedstorageaddons-0.5.jar Refined Storage Addons {refinedstorageaddons@0.5 DONE}
		instantunify-1.14.4-1.0.3.jar InstantUnify {instantunify@1.0.3 DONE}
		FastLeafDecay-v17.jar FastLeafDecay {fastleafdecay@v17 DONE}
		PrettyBeaches_1.14.4-3.0.7.jar Pretty Beaches {prettybeaches@3.0.7 DONE}

### Lastly (you may delete this from the report itself)
Please, for the love of all that is voxelbased, **read the contribution guidelines. They are linked to the right in the message box.**
When reporting issues, these are crucial, and the team withholds the right to close an issue for the plain stupidity of not reading and adhering to them.

Thank you for reporting issues, without people reporting them, they wouldn't get fixed. You're helping contribute to this mod and that is much appreciated <3

**Comment by BluSunrize** [comment]
Put the crashlog on pastebin please, I'm not downloading anything from that website.

**Comment by Kuiki86** [comment]
https://pastebin.com/eFczkvfH

**Comment by Kuiki86** [comment]
Malte said on discord, that he maybe fixed it ;-)
