### ISSUE TITLE
[1.14.4] Crusher and Press Recipes missing

### ISSUE THREAD

**Issue by TooManyKitKats** [BluSunrize/ImmersiveEngineering#3731]
### Description of the issue:
The crusher is incapable of crushing all ores except redstone, lapiz, and nether quartz. The press is also lacking recipes as far as I can tell as the wire mold does not appear to be usable.
Versions & Modlist
I used Forge 28.2.3
JEI 6.0.0.27
and build #592 on jenkins as well as the most recent curse release for 1.14,
I have no related images as I am unsure on how I would display this

**Comment by malte0811** [comment]
cc5ea7d5d8f7b865347571ce07b08a60cf081af0 (forgot the hash in the commit message)
