### ISSUE TITLE
[1.14.4] conveyor belts crashes server 

### ISSUE THREAD

**Issue by NoNameBob** [BluSunrize/ImmersiveEngineering#3733]
**Description of the issue:**
Whenever something is placed on the conveyor belts, the server crashes. Doesn't matter what is placed, tried iron ore, copper ore and other conveyor belt. Tried it in single player and it works but not for multiplayer. I know it's in Alpha but any help would be great, thanks.

**Crashlog:**

https://pastebin.com/7wnPgAUA

 **Versions & Modlist**

Forge 28.2.3
ImmersiveEngineering-0.14-94

**Comment by BluSunrize** [comment]
Moving discussion to Issue #3734, because it's far more detailed =p
