### ISSUE TITLE
[1.14.4] Missing Zombie Villager Texture

### ISSUE THREAD

**Issue by logansommerhoff** [BluSunrize/ImmersiveEngineering#3735]
### Description of the issue:
Fairly pedestrian issue I encountered during testing for a server and later isolated to IE; the `immersiveengineering:engineer` zombie is missing its texture (or you've taken a distinctly avante garde approach with the mob). 

### Screenshots:
Zombie villager:
![2020-03-30_02 36 10](https://user-images.githubusercontent.com/41183314/77884118-77ad5180-7232-11ea-9583-61de14aef68b.png)
![2020-03-30_02 36 41](https://user-images.githubusercontent.com/41183314/77884238-ac210d80-7232-11ea-88cd-de7e4a2778f1.png)
![2020-03-30_02 36 49](https://user-images.githubusercontent.com/41183314/77884245-af1bfe00-7232-11ea-9fb7-eedd54071c86.png)

After being cured (no issue):
![2020-03-30_02 56 32](https://user-images.githubusercontent.com/41183314/77884184-94e22000-7232-11ea-935a-baf665e1ac67.png)

### Versions & Modlist
- forge-28.2.3
- ImmersiveEngineering-0.14-94

Happy to contribute to a mod I've loved for so many years, thanks for all the work you do!

**Comment by BluSunrize** [comment]
All of the vilager integration is WIP.
The villager textures is something I started working on tonight even.
