### ISSUE TITLE
[1.14.4] Ores from the mod almost never spawn

### ISSUE THREAD

**Issue by MCmamont** [BluSunrize/ImmersiveEngineering#3741]
### Description of the issue:
As in exploring the world and in mining, оres from the mod appear one vein per chunk or less.
Maybe I'm just terribly unlucky. Or I don’t understand something. But earlier, the 1.12 version of the resources was much larger.
Checked both on the world of Biomes OP, and on the usual generation of the world.

### Versions & Modlist
forge-28.2.3
ImmersiveEngineering-0.14-94
BiomesOPlenty-1.14.4-9.0.0.262-universal
ruins-1.14.4.6

**Comment by logansommerhoff** [comment]
This issue's already been fixed pending the next update, see the original issue #3740 for more info
