### ISSUE TITLE
[1.14] No Ore Spawn in WorldGen

### ISSUE THREAD

**Issue by BenHartweg** [BluSunrize/ImmersiveEngineering#3742]
**Description of the issue:**

Yesterday we set up a new server (a), but unfortunately no IE ores are spawning. We searched on all levels, also in single player, but there´s no chance to find e.g. copper (just plain vanilla ores). 
I already checked the config file, oregen is enabled and it all looks reasonable. I also tried (b) without any other mods installed (just Forge,  IE and latest CTM), again no ore spawn.

**Versions & Modlist**

Forge 28.2.3
Minecraft 1.14.4
ImmersiveEnginering : 0.14-94

a) Biomes of Plenty, Gravestone, Botania, Quark 
(worldgen of all other mods seems to work just fine)
b) No specific modpackage / no other mods installed

Thank you very much for your help! :)

**Lastly**

Thank you for your amazing work! It was incredible fun to play IE in 1.12 and the support for 1.14 is so good!! Take care!

**Comment by BluSunrize** [comment]
Duplicate. Please look at recent issues.
