### ISSUE TITLE
[1.14.4] Crashes when there is any other mod other than IE

### ISSUE THREAD

**Issue by simonsaysmaybe** [BluSunrize/ImmersiveEngineering#3744]
### Description of the issue:
The crashes everytime IE is with other mods. When IE is by itself, it loads perfectly. I tried with a lot of other mods. I think it is a rendering issue?

### Crashlog:
https://pastebin.com/8fm8x6aq

(For this one I just dumped IE onto the mods folder, but it happens even with a few and even one more mod.)

### Versions & Modlist
IE 0.14.94
Forge 28.2.3
Modlist in the crash log.

*Sorry for my terrible english

**Comment by malte0811** [comment]
Can you upload a full log (logs/debug.log) from your test with "one more mod"? The crash report doesn't seem to be related to IE, but apparently it's a common crash when another mod had issues before the "final" crash.
