### ISSUE TITLE
minecraft 1.14.4 modpack crashes when joining newly created world after i have added immerzive engineering

### ISSUE THREAD

**Issue by phueyflame** [BluSunrize/ImmersiveEngineering#3747]
As title says when loading a newly created world I get through all the generation loading then joining and then saving game comes up then the game crashes and tells me this:

The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: net.minecraftforge.fluids.FluidStack.getFluid()Lnet/minecraftforge/fluids/Fluid;

paste bin for crash report:

https://pastebin.com/0subi51M

I am using IE version 0.14-94 and forge version 28.2.3

to my understanding based on the instructions to post the modlist should also be in the crash report. Also to make sure I am clear before adding IE this was not happening and IE is the only mod I have added/change I have made since this issue began.

Thanks

**Comment by BluSunrize** [comment]
closed due to lack of feedback
