### ISSUE TITLE
[1.12.2] Betweenlands Swamp Water stuck in Boiler

### ISSUE THREAD

**Issue by Ffisher0** [BluSunrize/ImmersiveEngineering#3749]
I accidentally added Swamp Water from The Betweenlands mod (3.4.6) into the water input in my boiler. The boiler will not use the swamp water to make steam. 

![image](https://user-images.githubusercontent.com/63047731/78247624-119b2580-74e3-11ea-8ba8-3080fcd9de15.png)

Is there a way to remove the Swamp Water or recover the diesel, rather than just breaking the boiler?
I appreciate it's a small amount of diesel in the grand scheme of things, but I'd prefer not to waste it at this stage of my game.

MC version: 1.12.2
IE version: 0.12-89
IP version: 1.1.9
Forge version: 14.23.5.2838
Betweenlands version: 3.4.6

**Comment by BluSunrize** [comment]
Immersive Engineering does not add a boiler.
