### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by liamjarvisman** [BluSunrize/ImmersiveEngineering#375]
When i try and compile Immersive Engineering I comes up with errors to do with nei

**Comment by GirafiStudios** [comment]
You probablyy don't have NEI in the libs folder, or something like that..

**Comment by liamjarvisman** [comment]
How would i do that i'm only starting to make minecraft mods and i'm not that advanced?

**Comment by radcom** [comment]
If you don't know how to compile mods then you probably shouldn't compile IE as the people who need help compiling it are often the ones who provide useless error reports as these builds are often buggy, and can be prone to crashes, and unless you know how to fill out bug reports telling the devs it doesn't work then posting the error isn't helpful . and another problem with providing help to these people is it all take valuable time detracts from time available to actually write the mod. But if you really want to compile it your self then the best thing to do is to learn how to do it i.e. by watching Pahimar's Lets Mod Reboot (which gives a good introduction to the concepts you need to know before you can compile it then googling the errors ). FYI it took me 3+ hours to compile IE the first time it did. Ff you still can't figure it out then just wait for the release in about a week Blu is usually quite quick.

**Comment by liamjarvisman** [comment]
Well i can compile mods and fix bugs but nei and waila aren't my strong points so could you just tell me how to do it i can wait 3 hours i'm sick and i have nothing else to do @radcom please?

**Comment by radcom** [comment]
These are the libs needed: AquaTweaks-1.7.10-1.0.jar, CodeChickenCore-1.7.10-1.0.7.47-dev.jar, CodeChickenLib-1.7.10-1.1.3.140-dev.jar, CoFHCore-[1.7.10]3.0.3-303.jar, EquivalentExchange3-1.7.10-0.3.507.jar, industrialcraft-2-2.2.720-experimental-dev.jar, MineFactoryReloaded-[1.7.10]2.8.0-104.jar, MineTweaker3-Dev-1.7.10-3.0.9C.jar, NotEnoughItems-1.7.10-1.0.5.111-dev.jar, Waila-1.5.10_1.7.10.jar just reference them in your compiler then you should be good to go if you do get it to compile then that is as far as I got.

**Comment by liamjarvisman** [comment]
thx i ask you if i get stuck

**Comment by BluSunrize** [comment]
This github does not give assistance in compiling IE. Developers should be able to figure out libraries themselves.
