### ISSUE TITLE
[1.14.4] External heater won't accept power if acceptor face is on top

### ISSUE THREAD

**Issue by NerdimusPrime** [BluSunrize/ImmersiveEngineering#3750]
### Description of the issue:
When putting down an external heater, if the power acceptor face is on top, the block will not draw power. If the acceptor face is rotated to any of the sides, it works normally.

Screenshots are from custom modpack, but issue is the same when using a clean instance containing only forge and IE.

### Versions & Modlist
Forge 28.2.3
IE 0.14-94

![ext-heater-top](https://user-images.githubusercontent.com/1558951/78267888-7c456480-74d5-11ea-925b-d3a44f1bd637.png)
![ext-heater-side](https://user-images.githubusercontent.com/1558951/78267912-823b4580-74d5-11ea-8534-29981ca4a8fc.png)

**Comment by malte0811** [comment]
Fixed for the next build. This is actually just a visual issue, when the heater looks like it's facing up it's actually facing down. So you can power it just fine from the bottom, or place it such that it looks like it's facing down and power it from above.
