### ISSUE TITLE
(1.14) Garden Cloche Incompatible with Mystical Agriculture

### ISSUE THREAD

**Issue by lolzeland** [BluSunrize/ImmersiveEngineering#3751]
No crash report here. Just noticed that, when I place mystical agriculture crops into the garden cloche, there is no growth or production of drops. All the compatibility mods are made for 1.12.2, and there is no config option to allow modded crops to work in the cloche.

Is there any word on a fix or compatibility patch for this issue?

**Comment by mindforger** [comment]
when you search issues, always include "closed" issues in your search :)

https://github.com/BluSunrize/ImmersiveEngineering/issues/3664
