### ISSUE TITLE
[1.12.2] Invisible wooden post issue

### ISSUE THREAD

**Issue by CritFlaw** [BluSunrize/ImmersiveEngineering#3752]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
As you can see by the attached video, when holding the engineer's hammer, the wooden posts will sometimes go invisible. The main issue though, is when trying to configure the pole to have a downwards facing support, which as you can see is invisible, and when placing a lamp below the invisible extension that appears, the post support is facing up.
https://imgur.com/7WR8AgA

### Crashlog:
N/A

### Versions & Modlist:
IE: ImmersiveEngineering-0.12-92.jar
Forge: 2847
Modpack: https://www.curseforge.com/minecraft/modpacks/capital-is-key
[Modlist](https://pastebin.com/SvXVmsYd)

**Comment by CritFlaw** [comment]
The crash log with the mod list - https://pastebin.com/NuZESUYE

**Comment by BluSunrize** [comment]
Cool.
Have you tried it with only IE installed?

Could you try it without foamfix?
