### ISSUE TITLE
[1.14.4] Metal Press will not accept gear or wire molds

### ISSUE THREAD

**Issue by NerdimusPrime** [BluSunrize/ImmersiveEngineering#3754]
### Description of the issue:
When installing molds in the metal press, it will not accept the gear or wire molds. It will accept all other molds.

### Versions & Modlist
IE version 0.14-94
Forge 28.2.3

**Comment by malte0811** [comment]
For the gear mold it's expected, there aren't any gears (and therefore no recipes for gears) in IE. For the wires it's a bug, I'll push the fix in a minute.
