### ISSUE TITLE
[1.14.4] [Suggestion] Support for Forge version 28.2.1-

### ISSUE THREAD

**Issue by aprusik** [BluSunrize/ImmersiveEngineering#3755]
Hello,

At the moment ImmersiveEngineerig seems to be one of the few 1.14.4 mods which require forge 28.2.3+.   Optifine's last supported forge version is 28.2.0 and the last one it still seems to function in is 28.2.1.  This essentially makes ImmersiveEngineering 1.14 and Optifine incompatible.

Since Optifine and Forge seem to not get along in these situations, I was wondering if there was a simple solution on this end.

I realize that Optifine is not generally supported by other mod authors, over time the ecosystem will probably evolve to require these later versions as well, and often there are important forge features that are necessary to get things working.  If this is the case, you can disregard this request.  I understand that a modder's time is a precious resource.

However, if there is a simple workaround for the usage of an earlier version, I would love to play with your ImmersiveEngineering and Optifine together in 1.14 as in 1.12.

Best of luck bringing IE to 1.14.  It's one of my favorite mods and I look forward to its future.

Thanks

**Comment by aprusik** [comment]
Just noticed this from the CurseForge page:

> Quote from BluSunrize >>
> In reply to algudaodoce69:
> 
>  Nope.
> 
> We depend on that Forge version.
> 
> Optifine is not supported by IE anyway.

**Comment by malte0811** [comment]
If it helps, you wouldn't have had much fun with Optifine and IE anyways. Some early testers tried to use OF (when we didn't need 28.2.3 yet) and the results are in the screenshots at https://github.com/sp614x/optifine/issues/3548.
