### ISSUE TITLE
[1.14.4] Crusher won't accept most ores

### ISSUE THREAD

**Issue by NerdimusPrime** [BluSunrize/ImmersiveEngineering#3758]
### Description of the issue:
Crusher will only run when either lapis or redstone ore, or quartz blocks, are tossed in. No other ore in either vanilla or IE will work.

### Versions & Modlist
IE 0.14-94
Forge 28.2.3

**Comment by BluSunrize** [comment]
Duplicate of #3731, fixed for next release.

Please use the search function next time.

**Comment by NerdimusPrime** [comment]
Sorry, I only searched for crusher in open issues. Next time I'll search in all issues.
