### ISSUE TITLE
[1.14] Nonstandard Drill Head Damage NBT Tag

### ISSUE THREAD

**Issue by Flaxbeard** [BluSunrize/ImmersiveEngineering#3759]
### Description of the issue:
`DrillheadItem` uses the NBT tag `headDamage` to store its damage value. This does not match the vanilla standard of using `Damage`, which for example makes it difficult to obtain a damaged drill head with `\give`. Not a big deal, if there are other reasons to use `headDamage` then I think it's fine to keep it that way.

### Versions & Modlist
IE 0.14-95-e47805cd
Forge 1.14.4-28.2.3

**Comment by malte0811** [comment]
Some of the code using `headDamage` is from the original 1.8 porting commit, so I doubt there's any good reason for not using `Damage` other than me missing it in the 1.13/1.14 port.

**Comment by malte0811** [comment]
Fixed in 8560c7729b064b8f760554b9baf7e48db369592a (forgot to add the issue number to the commit).
