### ISSUE TITLE
Poke - A wild modpack appeared, it use your amazing work, it's super effective !

### ISSUE THREAD

**Issue by kane-thornwyrd** [BluSunrize/ImmersiveEngineering#376]
Hello guys,

Thank you a lot for all the effort you put into this Mod, I greatly appreciate it !
It is very nice looking and functionality-wise very fun !

Here's a modpack I'm working on nowadays, I thought you would like to be informed about it:
[Stranded Strained](http://minecraft.curseforge.com/modpacks/233775-stranded-strained)
My design goal is to make it tough but rewarding, with an increasing number of ways to achieve goals with the tiers you're conquering.

And all that with graphically pleasing mods :wink: .

I'm not yet at the tier I hope for ImmersiveEngineering, but I'm open to any suggestion you could make toward the use of mine/modtweaker and tabula rasa and the inter-mods smoothing I try to attain.

I.E.: The acid ritual for Zetta Industries is "fun", but I find it lacking a bit of meaning; I mean, why lightning up a block of sulfur/gunpowder in a 3×3 pond of water when you can melt sulfur (Oredic) into its liquid form(MineChem), using a Smeltery (TConstruct), then add 8 times its volume of water while boiling to make sulfurous acid (Zetta industries) for battery (Zetta industries) ?

**Comment by BluSunrize** [comment]
Thanks for the heads up I guess, not really an issue though.
