### ISSUE TITLE
[1.14.4] Alloy Smelter doesn't follow preferredOres config

### ISSUE THREAD

**Issue by NillerMedDild** [BluSunrize/ImmersiveEngineering#3762]
### Description of the issue:
The Alloy Smelter's recipes' outputs do not change based on the preferredOres config, like the Crusher's recipes do. The config is set to 
`preferredOres = ["minecraft", "kubejs", "silents_mechanisms", "immersiveengineering", "bluepower", "botania", "mysticalworld", "tmechworks", "industrialforegoing"]`
which works for the Crusher, which outputs silents_mechanisms copper dust from copper ore, for example.

Given the comment above the config, I'm not sure this is an actual bug, but I thought I would report it just in case.

I found the issue by checking JEI recipes for the Alloy Smelter.

This happens in single player, but I'm fairly sure it also happens in a server environment.

This issue happens in the modpack [Enigmatica 4 version 0.5.1](https://www.curseforge.com/minecraft/modpacks/enigmatica4/files/2915589)

### Versions & Modlist
- ImmersiveEngineering-0.14-94
- Forge-1.14.4-28.2.3

Edit: Thank you for updating Immersive Engineering :)

**Comment by NillerMedDild** [comment]
Thanks!

**Comment by NillerMedDild** [comment]
This issue is still present in `ImmersiveEngineering-0.14-95`.

**Comment by BluSunrize** [comment]
Irrelevant, JSON recipes will be implemented for 96

**Comment by NillerMedDild** [comment]
Ah I see, nice!
