### ISSUE TITLE
[1.14.4] Crash with MouseDragg Event and Mouse with more than 3 buttons.

### ISSUE THREAD

**Issue by TwistedGate** [BluSunrize/ImmersiveEngineering#3763]
### Description of the issue:
Hovering over a link in the manual, pressing any extra buttons (beyond the standard 3 buttons) on my mouse and dragging causes a crash.

### Crashlog:
https://gist.github.com/TwistedGate/d306c83cf8a6e456b943b9c245e01183
(Contains Full log and the important crash causing exception already filtered out)

### Versions & Modlist
0.14-95-7e669037

**Comment by alexstratford** [comment]
I can't replicate this on 0.14-95-190fba3c, does it still happen for you?

**Comment by TwistedGate** [comment]
Yes, if it doesnt for you still. Try a page with a crafting recipe and trying drag one of the displayed items. That'll cause it too i've figured out just now.
Both, what i get for links and the item dragging cause the exact same crash.

**Comment by alexstratford** [comment]
Hmmm, I just got it too. I had to click the extra buttons a few times but it did crash in the end.
https://gist.github.com/alexstratford/f59968f451a7d0f06f48d19c1f016766#file-relevant-part
0.14-95-190fba3c
