### ISSUE TITLE
[1.14.4] Manual entry for Excavator has null values

### ISSUE THREAD

**Issue by alexstratford** [BluSunrize/ImmersiveEngineering#3765]
### Description of the issue:
The RF/tick and time to mine a vein of ore are both null for the excavator

### Versions & Modlist
1.14.4
Forge 28.2.3
IE 0.14.94
Tested in a pure IE instance

**Comment by WebDragon** [comment]
I also spotted this 'null' in the excavator manual in 1.15.2 with ImmersiveEngineering-0.15-108.jar and forge-31.2.31

![2020-07-21_01 44 44](https://user-images.githubusercontent.com/1612570/88104398-60db9380-cb70-11ea-988f-7a356222edb5.png)
