### ISSUE TITLE
[0.14-95-c839561][request] Hemp recipe for Hammer?

### ISSUE THREAD

**Issue by iammeeper** [BluSunrize/ImmersiveEngineering#3769]
I searched through the issues - but as my search with only "hammer" without any other filter returnd 233 results I didn't looked through all of them - so if this is a duplicate it's not intential - just laziness not to search through 200+ issues.

TLDR: I started a new world with 0.14-95-c839561 and just got the idea: Hey, wasn't there a way to get String from Hemp or to craft the Hammer with Hemp directly? Well, guess this was some tweaks by some modpacks back in 1.12.2. So, I guess crafting String from Hemp is maybe too overkill how about a recipe about crafting the Hammer with Hemp in addition (or maybe instead of) to the current recipe with String?

**Comment by iammeeper** [comment]
So, as I look through `Recipes.java` to come up with my own pull request I figured that Hemp Seeds no longer can be found by harvesting tall grass but only by craft a seed with a string, wich brings me back round to my initial issue: You have to somehow get a String to start IE, or two that is: one for the Hammer and one for the initial Hemp Seed. So, as we already talking about re-adding a way to craft String from Hemp Fiber and also the Hammer with Hemp Fiber how about also re-add the "getting Hemp Seed from harvesting tall grass"?
//also cross-posted in pull request #3771

**Comment by gyroplast** [comment]
> You have to somehow get a String to start IE, or two that is: one for the Hammer and one for the initial Hemp Seed.

With the "3 hemp fiber -> 1 string" recipe added back in that was plain missing, we're back to needing to obtain exactly one string right now, to craft the hemp seed. This can be cultivated and turned into arbitrary amounts of additional string. Making a new recipe just for crafting the hammer with hemp fiber seems a bit misdirected, in my opinion.

I, too, hate having to fight spiders or spelunk through an abandoned mineshaft just to get this first piece of string, so having the seeds drop from tall grass as in the past is preferable. Commit a547abb5 hints at this being somehow troublesome with Forge currently, though.

**Comment by BluSunrize** [comment]
Yeah we literally can't add drops to tall grass atm.
The string + seed recipe is a temporary solution to make hemp accessible to users until Forge fixes this.

**Comment by iammeeper** [comment]
I agree with you that with the Hemp Fiber > String recipe merged my initial idea about adding a recipe for crafting the Hammer with Hemp Fiber is redundant. But I'm glad to see where it led to in the end.
About the "temporal" solution: Well, I guess it's just a matter of getting used to it. As 28.2.3 seems to be the final build for 1.14.4 I guess we can't expect a fix for this Tall Grass issue to happen. So, for 1.14.4 at least I guess we all have to live with it. And hey, hunting down some Spiders after you got a bit of basic gear like Iron Armor shouldn't be that much of a pain, although it makes a peaceful only start a bit harder as one has to find some String in loot chests or by breaking Cobwebs in a Mineshaft, but it's not impossible to pull that off. And if you take the requirements for the Blast Furnace into account it fits the theme, although one also can find Blaze Rods in loot chests in Nether Fortresses too.
Many thanks to all who were involved make this request a final merge, to @gyroplast especially for doing the coding work.
