### ISSUE TITLE
[1.14.4] Invalid Player Move while using skyhook means the player cannot rejoin

### ISSUE THREAD

**Issue by alexstratford** [BluSunrize/ImmersiveEngineering#3776]
### Description of the issue:
While using a skyhook I was going along some rope that was suspended from balloons, I came to a junction where the balloons were tied to the ground and the next balloon along and then was kicked, when trying to rejoin I get the "Internal Server Error Message"

### Crashlog:
No crash, but here are the server logs: https://gist.github.com/alexstratford/6550d37e79aee9ae0c020ebf77632eb9

### Versions & Modlist
0.14-95-233a2986
Forge 28.2.3
https://gist.github.com/alexstratford/ba352c7b85b860e8f8da4bf71b02694e

**Comment by malte0811** [comment]
I'll look into fixing this, it would be great if you could send some screenshots of a similar setup (I'm not sure I'm understanding your description correctly). For the rejoining issue, what I said [here](https://github.com/BluSunrize/ImmersiveEngineering/issues/2937#issuecomment-383213589) is still valid as far as I know.

**Comment by alexstratford** [comment]
![2020-04-10_18 01 24](https://user-images.githubusercontent.com/58825136/79008508-74309900-7b55-11ea-9c4d-dda7b9f5213e.png)

Thats a quick mockup of the setup, you get on at one end and I think if you aren't very clear about the direction you are looking it get confused. Another issue that may be related is the direction used to speed up on the keyboard is flipped at some points for a reason I cannot work out. (So if facing forwards and pressing W to go faster you cross a connection and start slowing down and going backwards, necessitating you to press S to go forwards now.)

**Comment by alexstratford** [comment]
And thanks, the solution and website worked perfectly.
