### ISSUE TITLE
[1.14.4] external heater does not work with the new smoker or vanilla blast furnace

### ISSUE THREAD

**Issue by gyroplast** [BluSunrize/ImmersiveEngineering#3777]
### Description of the issue:
The external heater block does not work with the smoker or vanilla blast furnace. No crash, simply no heating up or any power consumption visible after placing correct smeltable items into the appropriate top slot of either furnace variant.
Normal furnaces are working as expected in conjunction with the external heater.

### Versions & Modlist
- 0.14-95-233a2986
- Forge 28.2.3

**Comment by BluSunrize** [comment]
That's intentional. It's not supposed to work with them.
