### ISSUE TITLE
[14.4.4] Wooden Post causing severe FPS drops when placed in world

### ISSUE THREAD

**Issue by mako-kz** [BluSunrize/ImmersiveEngineering#3779]
### Description of the issue:
When placing the wooden post item into the world, it causes the game to not freeze, but drop to 0 FPS. This was tested both on singleplayer and on a multiplayer server, where some people encountered the issue but not all. FPS returned to normal after all posts were broken.
Video: [https://youtu.be/36OwoHx2J-s](https://youtu.be/36OwoHx2J-s)

Strangely enough, I can't reproduce this in singleplayer today (this issue happened last night). Placing a pole of any type causes a momentary hang, but then things go on as normal.

### Crashlog:
N/A

### Versions & Modlist
IE 0.14.94
Forge 28.2.3
Kreation modpack, version 0.4.1. [Mod list](https://pastebin.com/hxMNTY6s) generated via forced crash log

**Comment by BluSunrize** [comment]
Can't replicate this at all, I'm afraid. Even with multiple posts, I'm running at a comfortable 60fps
