### ISSUE TITLE
(Suggestion/Request)  A way for mapmakers to set mineral deposits

### ISSUE THREAD

**Issue by aurumvorax** [BluSunrize/ImmersiveEngineering#378]
Title pretty much says it all, maybe something as simple as a config option to list chunks and deposit types?  I found getRandomMineral() so I see that it uses the seed and chunk, which doesn't make this easy.  Maybe adding something akin to the "depleted" tag?  I'm not sure how hard that would be to implement, I'm at the limits of my Java knowledge just interpreting this code.

**Comment by BluSunrize** [comment]
I guess it would be helpful for custom maps... I'll look into it.

**Comment by aurumvorax** [comment]
Sweet, thank you

**Comment by BluSunrize** [comment]
There you go, multiple commands related to minerals have been added for 0.6
'/ie mineral list' will give you a list of all registered mineral names
'/ie mineral get' will tell you what mineral is to be harvested in the chunk you are in
'/ie mineral set <mineral>' will allow you to set an override for the chunk you are in, replacing the mineral in there (or nothing, if the chunk is empty) with the specified mineral. Specifying no mineral will clear the override
'/ie mineral setDepletion <number>' will allow you to adjust the depletion of the chunk. Setting the depletion to -1 will make the mineral infinite.

**Comment by aurumvorax** [comment]
That is awesome, thank you!

**Comment by RevMilang** [comment]
@BluSunrize Sorry, you can give the command to remove the ore from the chunk. I figured out how to put ore in a chunk and how to remove it.
