### ISSUE TITLE
[1.14.4] Crusher doesn't have some recipes still

### ISSUE THREAD

**Issue by alexstratford** [BluSunrize/ImmersiveEngineering#3781]
### Description of the issue:
There is no recipe for the crusher to turn:
coal ore to coal
Aluminium Ore to Aluminium Grit (Aluminium Ingot recipe is duplicated)
Copper Ingot -> Grit recipe is duplicated
Nickel Ingot -> Grit recipe is duplicated
Iron Ingot -> Grit recipe is duplicated

### Crashlog:
No Crash

### Versions & Modlist
0.14-95-233a2986
Forge 28.2.3

**Comment by gyroplast** [comment]
Can confirm. There is also no crusher recipe for diamond ore or emerald ore. No idea how it integrates with other mod's ores, yet.
