### ISSUE TITLE
[1.14.4] Tools lose stored upgrades and items

### ISSUE THREAD

**Issue by alexstratford** [BluSunrize/ImmersiveEngineering#3783]
### Description of the issue:
Occasionally the Pistol deletes all the cartridges inside it, the Drill its head and upgrades and the Buzzsaw its saw and upgrades, the items don't appear to lose functionality, but there is no way to use them (The pistol can't be fired due to no bullets, the Drill/Buzzsaw both however function)

### Crashlog:
No Crash

### Versions & Modlist
0.14-95-233a2986
Forge 28.2.3

**Comment by malte0811** [comment]
Is this happening on a dedicated server in creative mode?

**Comment by alexstratford** [comment]
It happens on a dedicated server in survival, however there is also a bug that if you have an engineers toolbox, open it and put some items in, go to creative mode and place it the items all disappear from both the one in your hand and the one on the ground.

**Comment by alexstratford** [comment]
Have added the toolbox problem as a separate issue #3790

**Comment by BluSunrize** [comment]
Have not seen reports of this on recent versions. Closing this, as 1.14 is no longer receiving updates.
