### ISSUE TITLE
[1.14.4-95] visual glitch: coke oven tank level not updated on draining

### ISSUE THREAD

**Issue by iammeeper** [BluSunrize/ImmersiveEngineering#3786]
### Description of the issue:
Don't know if already reported, search didn't got useful results: Tank of Coke Oven doesn't get drained = infinite Creosote Oil.

### Versions & Modlist
1.14.4 commit 17afaa4

**Comment by gyroplast** [comment]
Happened to me twice, too, not always, but it does not _seem_ to be duping, only the _update of the  internal creosote tank display is delayed_. Just retried it. Put three pieces of coal into a coke oven, and when they were done I could fill one bucket successfully, tank display remained at 1500mB, but the second bucket would _not_ fill. Upon placing a new coal item into the input, the tank immediately updated to 500mB.

I've been using cove ovens with pump and tank regularly, without issue, so there's hope it's only a display glitch. :)

**Comment by malte0811** [comment]
It works just fine for me (slightly newer commit, but no relevant changes). The update is always instant as well. Can you post some details (dedicated server or singleplayer, other mods, etc)?

**Comment by iammeeper** [comment]
Well, I guess I should had tested it more before reporting. I thrown in 2 blocks of Coal so I got 10.000mB worth of Creosote Oil and I already wrote this issue before I drained all of it.
After a bit more testing I can confirm that it seems to be a visual glitch only wich updates as soon as a new Coal input is placed into the item input.
Also I only tested it in SSP and use some additional "helper" mods like JEI, JourneyMap, FastLeafDecay, Inventory-/MouseTweaks and TheOneProbe. But the only gameplay mod is IE. Will re-try it with IE only and also SMP.

**Comment by iammeeper** [comment]
I could be wrong, but I don't see and update to the GUI in blusunrize.immersiveengineering.common.blocks.stone.CokeOvenTileEntity to its GUI when a fluid container is filled from the internal tank, may this could be the cause for this issue?

**Comment by iammeeper** [comment]
Didn't seen any work on it, but thought I give it a try with current commit 13d1915
Also upgraded to Forge 28.2.4 and also tried on SSP and SMP this time.
Also also tested with pump - seem not to happen when the tank get's suckt external - so looks like somewhere where the bucket (or other container) is filled and moved to the the output slot as I mentioned earlier.

**Comment by iammeeper** [comment]
So, sadly still exists in currently release 95, but for anyone here're some "solutions":
1. using a pump as this causes a costant update of the cokeoven
2. always have some input currently processing - also causes constant update of the cokeoven
3. don't care about it and if you wonder why an empty container not filling up in SMP just relogg to see the tank is empty
Guess this will fixed when there's time for it and someone found the cause of the issue.
