### ISSUE TITLE
[1.12.2] Gun Turrets not targeting Ender Dragon

### ISSUE THREAD

**Issue by theLadyStardust** [BluSunrize/ImmersiveEngineering#3787]
I've been playing Stoneblock on 1.12.2, and while trying to make an Ender Dragon farm, I used the IE gun turrets. They have power, and a redstone signal, and will shoot at other hostile mobs, but won't target the Ender Dragon. I tried updating to the most recent version on curseforge (0.12-92), no dice.

**Comment by BluSunrize** [comment]
The turrets have a maximum range. My guess is that the dragon is too far away.

**Comment by theLadyStardust** [comment]
I'm pretty sure it's not that... I'm attaching some images of what I have set up, including the turrets' internal UIs. They were targeting endermen and me when I was doing some testing in the middle, and I couldn't find a well-defined range for them anywhere online or in the engineer's handbook, but I don't think it's a range issue. 
![image](https://user-images.githubusercontent.com/63514508/79070698-245ce980-7c9d-11ea-8fcc-5770eaebbb81.png)
![image](https://user-images.githubusercontent.com/63514508/79070723-39397d00-7c9d-11ea-9360-102880c3528c.png)

**Comment by BluSunrize** [comment]
So if you have an enderman in the same spot as the dragon, do the turrets target it?

**Comment by theLadyStardust** [comment]
I don't currently have them set up to shoot neutral entities, but if they were, yes.

**Comment by BluSunrize** [comment]
Endermen aren't neutral. They're hostile mobs.
Get yourself a zombie or something to test with. With as advanced your setup is there, you probably have a way to capture and transfer mobs.

All that said, turrets probably wouldn't be designed to shoot the dragon anyway. What you've set up there is waaay beyond IE's scope in the first place.
The dragon is pretty vastly different from normal entities in code, which probably contributes to the turrets not shooting it.

Also, we are focusing all our development efforts on 1.14.4 now.
