### ISSUE TITLE
1.12.2 power generation machines not working

### ISSUE THREAD

**Issue by therealbdld** [BluSunrize/ImmersiveEngineering#3788]
I have tried to make the windmill,diesel generator work but for some reason when I connect the the fluid pipe with bio diesel in it the diesel generator won't turn on. and the levers won't even attach to the machine. i have tried building this in survival and creative. on version 1.12.2 and 1.14 and they didn't work on both. I'm not sure I'm doing something wrong i have followed what the manual said but still no luck.

**Comment by BluSunrize** [comment]
You completely ignored the guidelines for reporting issues.

The least you could do is provide pictures of your setup
