### ISSUE TITLE
[1.14.4 - 6790a4f5] Engineers Toolbox deletes inventory

### ISSUE THREAD

**Issue by alexstratford** [BluSunrize/ImmersiveEngineering#3790]
### Description of the issue:
Sometimes the Engineers Toolbox will delete its inventory, I have noticed this behaviour happens especially if you transition from Survival to Creative mode either with it in your inventory or if you open it while in Creative mode after changing your gamemode.

### Crashlog:
No crashlog, and nothing happened in the server logs, 

### Versions & Modlist
https://gist.github.com/alexstratford/ba352c7b85b860e8f8da4bf71b02694e
(Haven't tested in local IE only instance as I am not entirely sure how it happens.)

**Comment by pckuijper** [comment]
I've just had this happen on 1.12.2 with the enigmatica 2 modpack.
Steps to reproduce:
- Insert item into toolbox
- Place toolbox inside enchanting table
- Remove without enchanting (can't be enchanted)
- Items are missing

**Comment by BluSunrize** [comment]
Have not seen reports of this on recent versions. Closing this, as 1.14 is no longer receiving updates.
