### ISSUE TITLE
[1.14.4 - c66eb015] Server Crashes With Ticking World Exception

### ISSUE THREAD

**Issue by alexstratford** [BluSunrize/ImmersiveEngineering#3792]
### Description of the issue:
Just after leaving a dedicated server it crashed with a Ticking World Exception.
It appears to be a problem with the redstone wire system when it unloads.

### Crashlog:
Crashlog: https://gist.github.com/alexstratford/dbfa192ec67274f91e7eab8c5cb5eeea
Server Logs: https://gist.github.com/alexstratford/eac537e2a5de7122444074368964cb3c

### Versions & Modlist
IE 0.14.-c66eb015
Forge 28.2.3
https://gist.github.com/alexstratford/a05db19f37f40a9b274b9100db084069

**Comment by alexstratford** [comment]
https://gist.github.com/alexstratford/1b7e51f47bffbff4648f865fe48740bc

**Comment by alexstratford** [comment]
https://drive.google.com/file/d/1_L_880A-B9J3oRAiML7qVkMifCzUop1v/view?usp=sharing
Log and crash file with verbose wire logging turned on.

**Comment by malte0811** [comment]
I'll close this for now. I've never managed to reproduce the crash, but have added a few more safeguards to prevent this sort of issue. Use #4013 for future discussion on this type of crash.
