### ISSUE TITLE
[1.14.4 - 7537da53] Breaking a Current Transformer Crashes the Client

### ISSUE THREAD

**Issue by alexstratford** [BluSunrize/ImmersiveEngineering#3794]
### Description of the issue:
Breaking a Current Transformer causes a local client crash

### Crashlog:
https://gist.github.com/alexstratford/b8a0f41c01f3b10c649327719a23d731

### Versions & Modlist
0.14-95-7537da53
Forge 28.2.3

**Comment by BluSunrize** [comment]
My bad.
