### ISSUE TITLE
[1.14.4 - 9c393a00] Dyeing a conveyor belt causes a client crash

### ISSUE THREAD

**Issue by alexstratford** [BluSunrize/ImmersiveEngineering#3795]
### Description of the issue:
When you dye a conveyor belt you get a crash, the stacktrace appears to be similar to #3793 

### Crashlog:
https://gist.github.com/alexstratford/c87fc1313a771c2bedae6f75979c8f3b

### Versions & Modlist
IE: 0.14-95-9c393a00
Forge 28.2.3

**Comment by alexstratford** [comment]
There is a workaround for the issue, which is to use the setblock command from the server console to replace the error causing block as someone is spawning in as the chunk needs to be loaded.

**Comment by BluSunrize** [comment]
I'll look into this, since I'm working on conveyors right now anyway
