### ISSUE TITLE
[1.12.2] Lag spikes placing the ore sampling drill.

### ISSUE THREAD

**Issue by Chenjox** [BluSunrize/ImmersiveEngineering#3800]
### Description of the issue:

In a new world, upon placing the ore sampling drill, the games FPS drop to 0. Upon breaking the drill it returns to normal.
There is no increase in usage of RAM.

### Versions & Modlist

Forge: 1.12.2-14.23.5.2847
IE: 0.12-92
Java Version build: 1.8.0_241-b07

If you tell me what to do, I'll try my best to do it.

**Comment by BluSunrize** [comment]
Could you please provide a debug crashlog, by holding down F3+C for about 10 seconds?
