### ISSUE TITLE
[1.10.2] Server Crash

### ISSUE THREAD

**Issue by OneBakaBoi** [BluSunrize/ImmersiveEngineering#3801]
Description of the issue:
I am trying to run a Craft of The Titans modpack on my server, but I can't start it up properly becuase IE crashes.
The server runs fine, if I delete the mod but it is a crucial part of the modpack.

I know it is an older version, I just want to ask if there is some solution, because i've seen servers run this modpack without deleting IE.

Thank you! 

Crashlog:
https://pastebin.com/iLXgVpbU

Versions & Modlist:

IE: ImmersiveEngineers-0.10-61
Forge:  forge-1.10.2-12.18.3.2511
Full modlist: https://pastebin.com/q7YnbSYz

**Comment by malte0811** [comment]
Try using a different JVM (not OpenJ9), this is a bug in IE that has been fixed on more recent versions of MC.
