### ISSUE TITLE
[1.12.2] Capacitor Backpack (Bauble) Blinking render.

### ISSUE THREAD

**Issue by alpharou** [BluSunrize/ImmersiveEngineering#3803]
### Description of the issue:
Basically, the capacitor backpack equipped in the respective Baubles slot blinks.

It works as intended, the bug is just visual.

I also tried with different versions of IE and forge.

### Versions & Modlist
forge-14.23.5.2847
Immersive Engineering 0.12 - 92
Baubles-1.12-1.5.2

**Comment by BluSunrize** [comment]
Does it work fine when you use it as something else than a bauble?

**Comment by alpharou** [comment]
Yes. It looks totally fine. Also, it works fine in the baubles slot, and the gauge updates accordingly, it just strobes.

**Comment by BluSunrize** [comment]
Then I'm afraid this is a very minor issue in a version we no longer actively support, and as such I will close this.

I would recommend attaching the backpack to a piece of armor instead. That should prevent the flickering effect.
