### ISSUE TITLE
[1.14.4 - 4fc655a9] Server crashes on startup

### ISSUE THREAD

**Issue by alexstratford** [BluSunrize/ImmersiveEngineering#3805]
### Description of the issue:
When starting the server an instance of Immersive Engineering cannot be created

### Crashlog:
https://gist.github.com/alexstratford/ec796f910b0dcf7ca3b1fcbe318a8664

### Versions & Modlist
IE 0.14-4fc655a9
Forge 28.2.3

**Comment by BluSunrize** [comment]
Do you have the full log?

**Comment by alexstratford** [comment]
https://gist.github.com/alexstratford/baebf566aec0ec0046bb093b919fd024
Full log for the version

**Comment by BluSunrize** [comment]
Clientside error, use of ISprite on server.
Working on it.
