### ISSUE TITLE
[1.14.4] Engineer's Crafting Table & Cloche do not drop contained Items when breaking.

### ISSUE THREAD

**Issue by TwistedGate** [BluSunrize/ImmersiveEngineering#3807]
### Description of the issue:
Engineers crafting table and Cloche dont drop the items that were left inside of it.
Basicly voiding them.

### Crashlog:
None.

### Versions & Modlist
0.14-95 (Localy compiled at time of commit 69ad58af0a7bf0a316ecf2e41c71cdc70d1ef62a)

**Comment by BluSunrize** [comment]
Crafting Table has not been registered for block drops. Easy fix.

@malte0811 
The rest of this issue affects any of our blocks that have dummies. Workbench, Cloche, Turrets, etc. will not drop their inventory unless their master block is broken.
I see two possible solutions and want your input on a fix:
1) We pull `master()` from `MultiblockPartTileEntity` up to `IGeneralMultiblock` and check for that in `DropInventoryLootEntry`
2) We override `IIEInventory.getDroppedItems()` for all of those Tiles

**Comment by malte0811** [comment]
I would go with the first solution, I'm a bit surprised that we haven't had a reason to pull it up there before.

**Comment by BluSunrize** [comment]
Oh great. I forgot the absolute pain in the butt this is.
When the master tile is already removed, we don't have an inventory to drop.

**Comment by pedr69** [comment]
guess this fix never did make it to 1.12
>minecraft 1.12 is six years old

damn...
