### ISSUE TITLE
HV Wire Disappearing

### ISSUE THREAD

**Issue by yepidoodles** [BluSunrize/ImmersiveEngineering#381]
A member of my community posted this in my forum today:

'the hv wire disappears from the hv connectors and relays. This has happened 3 times now(was trying to pinpoint what had to happen to make them disappear), I have logged right back on after a restart and they are still there and fine. But when I log out and come back the following day, they are missing.

Strange thing is when I go to replace it, it prompts me that" I can't place a wire there" on the hv connector. If I break the connector and replace it, then it works just fine. While the wire disappears on the hv relays as well, I can place new wire on them without having to break and replace.'

Hope you can help,
- Alice
  DragonTechMC

**Comment by bakaxyf** [comment]
#160

**Comment by XFactHD** [comment]
@yepidoodles the message that the wire cannot be placed their appears because the wire is actually still there.

**Comment by nmarshall23** [comment]
The wires are still there, something odd is happening to their entities. I've had HV wire turn into MV wire, it's still hooked up. Not sure if powering thought. 

Are you using a mod to backup your game? These seem to trigger this bug. I've found that if I exit out of Minecraft and start it up again that seems to reset the wire's entity.
