### ISSUE TITLE
Disabling multi-block models when building mechanisms.

### ISSUE THREAD

**Issue by MrLador** [BluSunrize/ImmersiveEngineering#3810]
I would like to have a way to disable models of prefabricated cars in the mod so that they remain in the block structure as in an unassembled form. This is very useful for correct display on DynMap for the server.
Minecraft 1.12.2

**Comment by BluSunrize** [comment]
This mod has no cars, I have no idea what your are talking about.

If you have an issue with Immersive Engineering, please phrase a detailed issue report, following our issue template.
