### ISSUE TITLE
[1.14] Expand usability of IE on Peaceful difficulty

### ISSUE THREAD

**Issue by iammeeper** [BluSunrize/ImmersiveEngineering#3813]
So, my recent topic about crafting the Hammer with Hemp Fiber led to get String from Hemp Fiber. And another merge made it possible to get Hemp Seeds dropped from Tall Grass again (although due to backport in Forge 28.2.4 this may could take another look at). So, obtain renewable String in peaceful mode became lot easier (again) (in vanilla Strings only became renewable as junk from fishing as late as 1.7.2 - and as even junk is luck based you could end up in using up all String for your very last Fishing Rod without getting enough back to craft a new one). This led me to: How about get the required Resource (Blaze Rod > Blaze Powder) for Blast Furnace and by this: Steel in peaceful? Same as Strings are only really renewable when you play with at least easy, same is true for Blaze Rods, or at least Blaze Powder for that.
So, don't get me wrong: I don't want to make this mod to easy or break its current balancing. I'm fine with playing on easy (usually I play on normal) and get to the Nether pretty early on, but some of my friends prefer a peaceful only from time to time.
Although I thought about using Gunpowder in the Mixer (and by this still require at least a way to obtain Gunpowder) how about try to make at least Blaze Powder a renewable resource even in peaceful? Blaze Rods then maybe could be "compressed" in the Squeezer or the Press if this isn't too much of breaking the current balancing.

Any thoughts about that topic? Or would this be too breaking the balancing? Thanks for any reply in advance.

**Comment by BluSunrize** [comment]
While I recognize the issue, this is currently not a priority to me.

Also, making blazerods would definitely be a metal press thing, because it literally has a rod mold.

**Comment by BluSunrize** [comment]
Also, you "tagging" of the issue is a real mess =P

**Comment by iammeeper** [comment]
I'm very sorry for the inconvenience and mess, but I couldn't came up with any more useful (I had in mind to make it come up when someone else search for it in the title - as I did a search and lot of results where either bug reports or had mentioned Blast Furnace or Steel in a very different context), feel free to clean it up.
Thanks for the information about it's a known "thing" but at least not on high priority now. This at least gives me the information that, if there will be any change to it, it may comes when times allows it and that other things are more important right now.
I'm also fine with your suggestion about using the Press instead of the Squeezer so it reuse the Rod mold, but isn't it called Metal Press? Hence I thought as one "compresses" the Blaze Powder to a Blaze Rod it would fit better in the Squeezer, like "compressing" Coke Dust into HOP Ingot. Sure, one could say "Let's add a Blaze Ingot to copy the Electrode recipe.", but just adding the Blaze Ingot just for the sake of add some more realistic processing without it have any other use? Maybe also add a Block of Blaze as yet another material for a Beacon? Would be cool by me, but is all that worth it just cause someone would like to see a way to play this mod in peaceful only?
I guess this may could be closed for now as it's base idea "make IE possible in peaceful" is known but not a priority right now. Would clean up the issues by at least one. Thanks anyways.

**Comment by BluSunrize** [comment]
I think Quark or Botania alraedy have a blaze block, so I'm not adding that.

And yeah, the squeezer makes an ingot from dust, but we also don't have an ingot mold for the press. We *do* however have a rod mold, so that is the appropriate one to use.

**Comment by iammeeper** [comment]
Guess the new title fits it, even if someone searches for Steel, Flast Furnace or Blaze Powder as GitHub will also find full in text references, thank you.
Also nice to see some responsibility by not poluting with blocks added again wich already exist in other mods. I understand now how you think about using the Rod mold for the Press and skip the intermediate step with the Blaze Ingot as it would require such to be added wich may already exists in other mods.
Oh, and although off-topic: Nice to see release of 95.

**Comment by iammeeper** [comment]
So as JEI integration currently doesn't work for the multiblocks (guess that's already been worked on) I had to dig through source to find that Saltpeter and Sulfur are a thing and how to get them and what to use them for, but they both require you already have access to steel to build a Crusher and Mixer. So, even if one would figure out a way to implement recipes to somehow get to the Blaze Powder it's only possible after the initial Blast Furnace was build or one finds enough Steel by hunting for villages. Quite some hunt one would had to do if a rcipe is added to somehow craft Blaze Powder. Maybe "getting some ideas" from other mods for this one?

**Comment by BluSunrize** [comment]
I have no knowledge of JEI integration not working. Please report this in detail in another issue.

**Comment by iammeeper** [comment]
As I was writing Creators-of-Create/Create#280 I checked https://minecraft.gamepedia.com/Tutorials/Gathering_resources_on_peaceful_difficulty#Blaze_Rods and learned that obtain Blaze Rods in peaceful is actually impossible - which would make any progression in IE basically impossible as one can not aquire Steel.

**Comment by BluSunrize** [comment]
Yes, I know. You've said this multiple times now.
I've already said that I'm aware of the issues regarding IE on peaeful.
