### ISSUE TITLE
Client block entity render crash ArrayIndexOutOfBoundsException: 28

### ISSUE THREAD

**Issue by RisingInIris2017** [BluSunrize/ImmersiveEngineering#3814]
### Description of the issue:
Game crashed suddenly, and the cause is not so obvious.

### Crashlog:
https://paste.dimdev.org/ibijanumuz.mccrash
https://paste.dimdev.org/ayotapogat.mccrash

### Versions & Modlist
Attached in the crashlogs above.

This issue is quite weird and I cannot find the cause of it by myself,
so I think it is good to report this to your devs.
I do need some help, and I appreciate your help in advance.
Thanks for your warm heart!

**Comment by BluSunrize** [comment]
Remove optifine and try to reproduce the issue.
