### ISSUE TITLE
[1.12.2] Thaumic Additions' Seeds not accepted by garden cloche

### ISSUE THREAD

**Issue by KasKatto** [BluSunrize/ImmersiveEngineering#3816]
### Description of the issue:
The essentia seeds provided by thaumic additions [(Link)](https://www.curseforge.com/minecraft/mc-mods/thaumic-additions) cannot be grown inside the garden cloche. They can be put inside the bottom slot (the soil slot) but not in the seed slot.
![Annotation 2020-04-20 003536](https://user-images.githubusercontent.com/48245049/79702757-0ac03100-829f-11ea-8b98-57cc77626a17.png)

### Crashlog: 
N/A

### Versions & Modlist
[https://pastebin.com/8MRWJtyH](https://pastebin.com/8MRWJtyH)
(From forced crash report with a minimalist game- only IE + thaumcraft + additions)

**Comment by BluSunrize** [comment]
I have no plans to add compat from our side.

**Comment by BluSunrize** [comment]
Given that the Garden Cloche has an API however, Thaumic Additions or any other mod could facilitate this compatability.

**Comment by KasKatto** [comment]
Alight thank you, will report it on their side.
