### ISSUE TITLE
[1.12] Advancements not triggering, A way to find the actual advancement names?

### ISSUE THREAD

**Issue by GeorgeTheCyborg** [BluSunrize/ImmersiveEngineering#3818]
So i know the cause of this is due to other mods and the ore dictionary. but as a way around it i was hoping to find the names for the advancements so i could use cheat commands to trigger them. is it possible to get the trigger names for the advancements as names such as "The Upgrade" doesn't work. And after looking into the advancements config it appears the names dont really coincide with the actual advancements anyway, so can i get a list or is there a way to find these names?

**Comment by BluSunrize** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/tree/master/src/main/resources/assets/immersiveengineering/advancements/main

That's the folder of advancements. The file names are the internal names.

To trigger them, try `immersiveengineering:connect_wire` or `immersiveengineering:main/connect_wire`. One of those should work.
