### ISSUE TITLE
[1.14.4] Crash when opening an inventory that has a shader

### ISSUE THREAD

**Issue by cybercat5555** [BluSunrize/ImmersiveEngineering#3819]
### Description of the issue:
When opening an inventory that happens to have a tool shader, be it though pressing E or something else that shows inv (such as opening a chest), the game crashes. However clearing the inv fixes it.

### Crashlog:
[crash-2020-04-20_15.39.04-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4505934/crash-2020-04-20_15.39.04-client.txt)

### Versions & Modlist
IE 0.14-95
Forge 28.2.3 
Other mods: 
[list.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4505941/list.txt)

**Comment by BluSunrize** [comment]
Is this a 1.12 world that you loaded in 1.14?

**Comment by cybercat5555** [comment]
I -think- it might have been, was porting some structures across versions so I may have opened a 1.12.2 world in 1.14

**Comment by BluSunrize** [comment]
1.12 and 1.14 are not compatible.
In 1.12, IE's shaders used a different way of storing their data which leads to conflicts in 1.14.
