### ISSUE TITLE
[1.14] Shears consumed after single use

### ISSUE THREAD

**Issue by WazWaz** [BluSunrize/ImmersiveEngineering#3820]
### Description of the issue:
Wire cutters work fine, but shears are consumed in a single use when making wire.

### Versions & Modlist
IE 0.14-95
Forge 1.14.4-28.2.4

**Comment by McKitten** [comment]
I can confirm this applies for forge 28.2.3 also.

**Comment by BluSunrize** [comment]
Resolved by not letting shears be used anymore.
