### ISSUE TITLE
[1.12.2] The ability to disable the "metal Executive office chair tilt mechanism" for Dynmap.

### ISSUE THREAD

**Issue by MrLador** [BluSunrize/ImmersiveEngineering#3823]
**Description of the proposal:**
Here is an example of the "excavator" model.
Online map Dynmap does not support .obj, they become invisible. Presented in the screenshot, on the left is the unassembled excavator, and on the right is the assembled and turned into a .obj model.
Please add the ability to disable the display of the assembled model in .obj to the mod config, so that it remains as unassembled for the server part. This will be enough for the excavator server and similar machines on the server to be displayed in the online Dynmap map.
<a href="https://imgur.com/G2r9SyX"><img src="https://i.imgur.com/G2r9SyX.png?1" title="source: imgur.com" /></a>

**Comment by BluSunrize** [comment]
I have zero idea how dynamp grabs its models, but we can not just "disable" the obj display "for the server". That's not how the system works.
