### ISSUE TITLE
[1.12.2] Compatibility for IndustrialCraft 2 Classic

### ISSUE THREAD

**Issue by DAmNRelentless** [BluSunrize/ImmersiveEngineering#3825]
### Description of the issue:
It would be nice to have integreation with IndustrialCraft 2 Classic since I'd like to use the power conversion with ImmersiveEngineering cables/wires. However this does not work with the classic version of IC2.

### Versions & Modlist
Minecraft: 1.12.2
Forge: 14.23.5.2847
ImmersiveEngineering: 0.12-92

**Comment by BluSunrize** [comment]
IC2 power conversion has been removed from all IE versions after Minecraft 1.7.10.
You're a few years late.
