### ISSUE TITLE
[0.12-92] Crash - Ticking block entity - Crusher

### ISSUE THREAD

**Issue by jonathanbrooke** [BluSunrize/ImmersiveEngineering#3826]
**### Description of the issue:**
- Whenever an ore is tossed into the Crusher, the server immediately crashes.
- Cobblestone is accepted and works.

**### Crashlog:**
https://gist.github.com/jonathanbrooke/fe7ff84f6a9cd765952e7d3d8e1153be

**### Versions & Modlist**
IE Version = ImmersiveEngineering-0.12-92.jar   
Forge Version = 14.23.5.2847 

**###Other**
Mod is running on a Server & Client using Technic Launcher Deployment:
- Minecraft Version: 1.12.2
- Operating System: Linux (amd64) version 4.19-ovh-xxxx-std-ipv6-64
- Java Version: 1.8.0_211, Oracle Corporation
- Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
- Memory: 3295136736 bytes (3142 MB) / 8239710208 bytes (7858 MB) up to 8589934592 bytes (8192 MB)

Happens every time conditions above are met

Let me know if you need more information.

Thanks!

**Comment by BluSunrize** [comment]
Please provide your config file for Immersive Engineering.

**Comment by jonathanbrooke** [comment]
IE Config Server - https://gist.github.com/jonathanbrooke/432a3145efc554598c31fa65a68b5a63
IE Config Client - https://gist.github.com/jonathanbrooke/4fba082369e4d7af567d875ba0a33ebc

**Comment by jonathanbrooke** [comment]
To clarify, user on my server said this error is with the Crusher not the Pulverizer. I will edit accordingly, apologies!

**Comment by BluSunrize** [comment]
Do you use Craftweaker to load custom recipes?

**Comment by BluSunrize** [comment]
Nvm, you don't, I should have checked your modlist

**Comment by BluSunrize** [comment]
Honestly, absolutely no idea what's happening there.
Can the player reproduce this issue in singleplayer?

**Comment by jonathanbrooke** [comment]
@BluSunrize I've contacted the player who reported it to recreate in Singleplayer for you, ill revert when I've had confirmation he has done this.
Are there any further logs I can provide to assist?

**Comment by jonathanbrooke** [comment]
@BluSunrize 
Single Player Crash Video from the user who reported it - https://youtu.be/hnZ5tpUJuAE
His CFG File - https://gist.github.com/jonathanbrooke/7577f4777b09a6565eacf36143483089
Hid Crash Report - https://gist.github.com/jonathanbrooke/d9812177d65dc528ae1f8dc828be3616

**Comment by BluSunrize** [comment]
I'm genuinely unsure about what's causing this. The config file looks fine, and you don't have Crafttweaker to change any recipes.

Check if this issue happens with *just* Immersive Engineering installed. If it doesn't, then there is a cross-mod interaction problem. The best way to debug that is:
1) Throw out half the mods. Check if the issue persists
2a) If it does, halve your modlist again
2b) If it doesn't keep working with the other half
3) Keep making halves of the problematic mods until you find out which one does it.

It's tedious work, but it has a complexity of log(n), so it's basically the fastest way to do it.

**Comment by Cazadorsniper** [comment]
@BluSunrize There seems to be a weird interaction between IE and Netherending Ores, I threw some obsidian and gold ore in the crusher and the crusher kept running but nothing would come out the output until I disabled Netherending Ores.

**Comment by Cazadorsniper** [comment]
Okay, It is Netherending Ores I believe, since I managed to make the crusher crash, crusher works fine without Netherending Ores.

**Comment by jonathanbrooke** [comment]
Thanks for looking into this, ill disable Netherending Ores for now until a fix is published, ill stay subscribed to this thread for updated.

Thanks all!

**Comment by scott-j-johnson** [comment]
Hi, I believe this is related to IE's calculation of recipe energy usage per tick at TileEntityMultiblockMetal.java:479:
`this.energyPerTick = this.recipe.getTotalProcessEnergy()/this.maxTicks;`
...where both factors and the result are integers. As such, if a recipe's max ticks are greater than its energy requirement (and therefore its energy per tick is less than one), energyPerTick is zero, which causes the later division by zero at line 563. The same issue might exist in other machines; I didn't check.

Netherending Ores applies a recipe time multiplier to its Crusher recipes, encountering this issue.

The author of Netherending Ores offered a workaround here: [https://github.com/ICannt/Netherending-Ores/issues/24#issuecomment-628560794](https://github.com/ICannt/Netherending-Ores/issues/24#issuecomment-628560794)

I've never done any Minecraft modding so I apologise if I got something wrong.
