### ISSUE TITLE
1.14.4 infinite creosote oil

### ISSUE THREAD

**Issue by Hoskja** [BluSunrize/ImmersiveEngineering#3827]
Issue description: after reaching full, sometimes the coke oven oil supply will not drain even though buckets are filling with creosote oil when put in the slots.

crashlog: https://pastebin.com/M7GTJ2wW

version: 1.14.4

mods: 
immersive engineering alpha 0.14-95
Reliquary- 1.14.4-1.3.4.947
Xaero's Minimap 20.7.1 Forge 1.14.4
forge version 28.2.3

**Comment by iammeeper** [comment]
Please look at #3786 and #3817 - it's just the gui not correctly updating.
