### ISSUE TITLE
[1.14.4] Blast Furnace Preheater doesn't work

### ISSUE THREAD

**Issue by ftheriachab** [BluSunrize/ImmersiveEngineering#3828]
### Description of the issue:
Cannot get Blast Furnace Preheater to work in ImmersiveEngineering-0.14-95 when connected to power source.

### Versions & Modlist
Version: ImmersiveEngineering-0.14-95
Modlist: Testing to reproduce issue with only Forge 28.2.5 and IE 0.14-95

![2020-04-23_12 52 07](https://user-images.githubusercontent.com/11477148/80133210-830a4900-8562-11ea-8232-7137eb369977.png)

**Comment by BluSunrize** [comment]
How are you determining it to "not work"?

**Comment by ftheriachab** [comment]
The fan isn't turning and the crude blast furnace runs faster

**Comment by ftheriachab** [comment]
Okay, so it seems to work faster for ingots but not blocks.

**Comment by BluSunrize** [comment]
Well if it runs faster, then it works.

The fan is purely visual, and it hasn't been spinning since 1.8 =)
