### ISSUE TITLE
[1.14] Crash relating to fluid pipe collision box

### ISSUE THREAD

**Issue by cybercat5555** [BluSunrize/ImmersiveEngineering#3829]
### Description of the issue:
I was placing a variety of bare pipes, scaffolding-covered pipes, as well as small fluid collectors from Engineer's Decor, when the game suddenly crashed. However I was later able to re-join the world safely and continue on as normal.

### Crashlog:
[crash-2020-04-23_22.53.01-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4526366/crash-2020-04-23_22.53.01-client.txt)

### Versions & Modlist
IE 0.14-95
Forge 28.2.3
Other mods:
[list.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4526369/list.txt)

**Comment by BluSunrize** [comment]
Have you been able to reproduce this recently

**Comment by cybercat5555** [comment]
Unfortunately no, even by placing the same blocks in the same location, I can't seem to trigger it
