### ISSUE TITLE
Version 0.5.4 Issue with graphite electrodes

### ISSUE THREAD

**Issue by MaximilianZ2** [BluSunrize/ImmersiveEngineering#383]
The damage bar goes down to ~70% then the damage bar vanishes and the integrity goes back to 100%. This time it doen't go down for around 10min, after that the damage bar comes back and the integrity starts to drop. When it is around 70% again the electrode gets destroyed.

http://puu.sh/jXSjy/520beb2475.jpg

**Comment by BluSunrize** [comment]
Did you use the config to change their maximum damage?

**Comment by BluSunrize** [comment]
Actually, never mind, I know what this is about.
