### ISSUE TITLE
1.14.4 Multiblock structures not solid

### ISSUE THREAD

**Issue by Pixelmnkey** [BluSunrize/ImmersiveEngineering#3831]
### Description of the issue:
Most of the multiestructures such as fermenter or refinery aren't solid, so you can't place connectors or levers on 'em.

### Versions & Modlist
Forge : 28.2.4
IE; 0.14-95
[crash-2020-04-16_00.54.47-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4534446/crash-2020-04-16_00.54.47-client.txt)

If your game crashed (see above) you may omit the modlist, but IE and Forge version would still be nice.

Also, please try testing an issue in a minimal instance, with just IE, Forge and maybe JEI. That makes elminating compat issues easier.

### Lastly (you may delete this from the report itself)
Please, for the love of all that is voxelbased, **read the contribution guidelines. They are linked to the right in the message box.**
When reporting issues, these are crucial, and the team withholds the right to close an issue for the plain stupidity of not reading and adhering to them.

Thank you for reporting issues, without people reporting them, they wouldn't get fixed. You're helping contribute to this mod and that is much appreciated <3

**Comment by Dylan404** [comment]
i have the same problem

Forge : 28.2.5
IE; 0.14-95

the block are not solide.

**Comment by Spy426-IW16** [comment]
As a heads up me and others on my server have found a work around for this by placing the power connections for cable first then assembling the multi-block with the hammer. The ports work fine as far as we can tell you just cant place on them.

**Comment by malte0811** [comment]
Are they completely missing their bounding boxes (so you can just walk through them)? If that's the case (and it only happens for some parts of the multiblock), #3838 should fix that.

**Comment by Spy426-IW16** [comment]
In the case of our problems the bounding box was wrong thus we could walk right through them. The ports still work if something is setup to them we just cant place on them after they are formed.

**Comment by rjrelander** [comment]
It seems to be the outer layer of blocks of the multiblock that are not solid. I think the center ones are solid. You can walk into the machines but not all the way through. You also have to click on the solid center blocks to open GUIs and pick at them to break the multiblock. I was also seeing weird things with breaking the squeezer. I was losing the wooden barrel in the center.

**Comment by BluSunrize** [comment]
This should be resolved by Malte's recent commits.
The next release (96) will fix this.
