### ISSUE TITLE
[1.14]中文汉化问题（zh_cn Localization problem）

### ISSUE THREAD

**Issue by QuinHai** [BluSunrize/ImmersiveEngineering#3832]
1.14版本汉化由于mod作者修改了很多物品的id,导致很多汉化名称没有生效
老版本：item.immersiveengineering.tool.manual => 新版本：item.immersiveengineering.manual
希望能够修复~

The zh_cn.json in 1.14 version does not work well because the items name changed.
old_version：item.immersiveengineering.tool.manual => new_version：item.immersiveengineering.manual
Hope to fix that.

**Comment by BluSunrize** [comment]
Feel free to make a pullrequest that fixes it.
