### ISSUE TITLE
[0.14-95] Existing Blueprints turned into a useless blueprint, craftable ones also useless

### ISSUE THREAD

**Issue by AceologyGaming** [BluSunrize/ImmersiveEngineering#3833]
### Description of the issue:
Blueprints that were existing in 0.14-94, and the result of the crafting recipes now show a blank blueprint, that has no craftables from it in the engineer's workbench.

![image](https://user-images.githubusercontent.com/25800778/80306275-21441c00-87ba-11ea-8e77-cb036ed05fd3.png)

### Versions & Modlist
IE 0.14-95
Forge 28.2.3
Modlist as per https://www.curseforge.com/minecraft/modpacks/kreation/relations/dependencies

**Comment by AceologyGaming** [comment]
Update; Blueprint as purchased from the Gunsmith villager also is blank.

**Comment by UnseenAcademical** [comment]
Also having this issue. Blueprint item does not appear in JEI either.

**Comment by spylor** [comment]
I'm having the same issue.
Forge 1.14.4-28.2.4
other mods:
appleskin
autoreglib
botania
create
curious-forge
gravestone
hwyla
jei
jrftl
lycanitemobs
mcjtylib
minecolonies
mixinbootstrap
netherportalfix
patchouli
planttech2
quark
rftoolbase
structurize
themidnight
u_team_core
useful_railroads
valhelsia_structures
xaeros_minimap
xnet

**Comment by spylor** [comment]
Same with only IE installed.

**Comment by BluSunrize** [comment]
Issue will be resolved by the next release, which completely moves all recipes to JSON format.

Unfortunately, I'm not quite done with that yet.
