### ISSUE TITLE
[1.14.4] No animations on multiblocks?

### ISSUE THREAD

**Issue by Pixelmnkey** [BluSunrize/ImmersiveEngineering#3834]
### Description of the issue:
Multiblocks such as the crusher lacks animations, it processes the ore just fine but it dosn't move at all.

### Versions & Modlist
Using v95
[crash-2020-04-16_00.54.47-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4535398/crash-2020-04-16_00.54.47-client.txt)

**Comment by UnseenAcademical** [comment]
Same issue here, same version

**Comment by malte0811** [comment]
It works fine for me, can you post some more info? E.g.: Is this on a server or in singleplayer? Is it just the crusher or have you noticed it on other machines as well (and if so, which ones)? And maybe a modlist/debug crash that isn't so outdated it doesn't even have IE in it?

**Comment by BluSunrize** [comment]
Closed due to lack of response
