### ISSUE TITLE
Duplicate ingot Arc Furnace

### ISSUE THREAD

**Issue by Maycke25** [BluSunrize/ImmersiveEngineering#3835]
minecraft 1.12.2
mod pack Sevtech ages
Arc furnace

can duplicate ingots

my english is bad, I made a video
https://youtu.be/Yd3ZxU9HuOs

**Comment by BluSunrize** [comment]
What version of IE is SevTech using?

**Comment by Maycke25** [comment]
immcraft-1.12-1.6.0
ImmersiveEngineering-0.12-89
immersivepetroleum-1.12.2-1.1.9
immersivetech-1.12-1.3.10
^all this immersive on mod folder
sorry, no crash, then no debug/log crash

**Comment by BluSunrize** [comment]
Once again: Read the issue template and contribution guidelines. It *tells* you how to produce a debug crash.

The latest version of IE for 1.12 is build 92. SevTech is 3 versions behind.
Closed.
