### ISSUE TITLE
[1.14] .14-95 Vacuum Tube Not Appearing in Give command, not craftable

### ISSUE THREAD

**Issue by UnseenAcademical** [BluSunrize/ImmersiveEngineering#3836]
### Description of the issue:
Using JEI, Cloche and other machines require vacuum tubes to craft. Vacuum tubes are uncraftable, which may be related to the blueprint issue in this version.

Attempting to use the /give command shows that the vacuum tube does not appear in the list of items.

Tested in both multiplayer on a server with lots of other mods, and with only MC, Forge, and IE in a singleplayer world.

### Versions & Modlist
Immersive Engineering .14-95
Force 28.3
Minecraft 1.14

**Comment by BluSunrize** [comment]
...what give command did you try?

**Comment by UnseenAcademical** [comment]
Ah. Was looking for "vacuum tube" not "electron tube"

Closing.
