### ISSUE TITLE
[1.14.4] Crash caused by "LocalWireNetwork.removeHandlersFor"

### ISSUE THREAD

**Issue by TwistedGate** [BluSunrize/ImmersiveEngineering#3837]
### Description of the issue:
I am unsure as to why it crashed, but this is the second time and it dumping the exact same stacktrace.
It happend while i was just walking around, and away from my base, i assume due to my low render distance (6 Chunks)

If more details are needed i'll try my best.

### Crashlog:
[Crash (Gist)](https://gist.github.com/TwistedGate/4d6c5a77cf3c4995ed95d590c1f455d6#file-crash-2020-04-28_07-00-19-client-txt)

### Versions & Modlist
IE: 0.14-95
Forge: 1.14.4-28.2.3
[ModList (Gist)](https://gist.github.com/TwistedGate/4d6c5a77cf3c4995ed95d590c1f455d6#file-mod-list)

**Comment by malte0811** [comment]
1. Is this crash reproducible? I've seen similar stacktraces before (even in my own test worlds), but I've never managed to figure out why it happened.
2. Try enabling `sanitizeConnections` in the config and loading all relevant wires once (walk along them or something like that). I don't know whether it will help, but it should get the network into a state that's close to the state I'd expect.
3. If it's reproducible, try this (after step 2): set `enableWireLogger` to true in the config, load the world and trigger the crash. That might produce enough debug info in the log for me to figure out what happened. Turn the option back off afterwards, it causes lag and log spam.

**Comment by TwistedGate** [comment]
> Is this crash reproducible?

Sadly i have yet to find a way to repoduce it consistently, it sometimes happens (randomly) when i go away or get close to my base.

I will however still try the `sanitizeConnections` option, time will tell what will happen after. i'll report back if and when it happens again!

**Comment by berinhardt** [comment]
In my server on 1.14 it crashes always that another player die, I will try with enabling sanitizeConnections

https://gist.github.com/berinhardt/0f612e7a7d194a2ccdf044b99e78ead3

**Comment by BluSunrize** [comment]
closing this due to lack of feedback
