### ISSUE TITLE
NEI GUI "Recipes"

### ISSUE THREAD

**Issue by WolfieWaffle** [BluSunrize/ImmersiveEngineering#384]
In most GUIs, with NEI, a certain area says "Recipes" when you hover over it, letting you see all the recipes of that GUI. This is missing with the arc furnace, which even though it basically has the same recipes as a regular furnace, would still be nice. It might also be missing on some other GUIs as well.

**Comment by BluSunrize** [comment]
Oh I did this ages ago btw. Just forgot to close it. xD
