### ISSUE TITLE
[1.14.4] Automated Workbench cannot be constructed

### ISSUE THREAD

**Issue by MarioKart7z** [BluSunrize/ImmersiveEngineering#3841]
I'm pretty sure i built it correctly.

(screenshots)
https://i.imgur.com/x2wlBi8.png
https://i.imgur.com/K3nkQuA.png

But clicking with the hammer does nothing, no matter where i do it. I tried clicking everywhere, including the scaffoldings and belts, nothing. There's no crash or anything, it just doesn't work.

Game version: 1.14.4
Mod version: 0.14-95
Forge version: 28.2.3
Other mods installed: https://i.imgur.com/yx5qnfC.png

**Comment by BluSunrize** [comment]
https://i.imgur.com/jJHiGGW.jpg

You gotta have the back-middle conveyor pointing towards the wooden slabs.

@malte0811 conveyor rendering in the manual is borked. Got any idea why that would be the case? The blockstate should be correct, no?
