### ISSUE TITLE
[1.12] MV Wires burning up even with limited throughput

### ISSUE THREAD

**Issue by zackpollard** [BluSunrize/ImmersiveEngineering#3843]
### Description of the issue:
I've been trying multiple different ways to stop my MV cables burning up, before now it seemed fine but with increased load on the system it seems that this method has stopped working. I'm trying to limit throughput in two ways to avoid MV cables burning up. Firstly, using HV passthrough connectors before going into the HV transformer to limit the downstream of the network to 8192RF/tick. Secondly, using capacitors (or in some cases MV passthrough connectors) to limit to 7 MV connectors, therefore that should limit the power draw to a maximum of 7168RF/tick. Now I might be going mad, but in my mind this should be possible and make it impossible for the cables to burn up. You can see an example of the setup here, with the missing MV cable that keeps burning up. The power draw on the other side of these blocks isn't even higher than 8192RF/tick, but keeps burning up the cable due to the buffers needing to fill up. This is why I have this setup with the capacitors in order to limit the potential throughput at any one time.

An image of the described setup is available here: https://imgur.com/a/nDllEaH

### Versions & Modlist
Immersive engineering version 0.12-89.
Immersive Tech version 1.3.10
Immersive petroleum version 1.1.9
Forge version 14.23.5.2838

Modpack is Sevtech: Ages Version 3.1.2 Hotfix 1
Playing in multiplayer on a small personal server with only a couple of people online at one time.

**Comment by zackpollard** [comment]
Can I ask why this was closed without any comment?

**Comment by BluSunrize** [comment]
For one: Because we are discontinueing 1.12 support this weekend.
But also, you never followed the contribution guidelines on this issue, namely, using the latest version to test; and reproducing the issue in an environment with only IE.
