### ISSUE TITLE
[1.14.4] Arc Furnace doesn't accept coke dust for steel recipe

### ISSUE THREAD

**Issue by dwattttt** [BluSunrize/ImmersiveEngineering#3847]
### Before reporting:
No related issues found

### Description of the issue:
The arc furnace isn't accepting coke dust for producing steel from an iron ingot. Attempting to place coke dust in the additive box does not place the item.

JEI shows the arc furnace recipe for steel as no longer requiring coke dust (only requiring an iron ingot, and only producing slag), but placing only iron does not cause the arc furnace to work.

Reproduced multiple times on dedicated server & single player.

### Crashlog:
Manually triggered crashdump: https://gist.github.com/dwattttt/234b35ee73159520c9303e48059f2c91

### Versions & Modlist
Reproduced with only IE installed

IE: 0.14-95
Forge: 28.2.10

**Comment by BluSunrize** [comment]
Will be fixed with the next release, because we are moving everything to JSON recipes
