### ISSUE TITLE
[Suggestion] Blaze rods are valid Railgun ammo

### ISSUE THREAD

**Issue by cybercat5555** [BluSunrize/ImmersiveEngineering#3851]
A small, more for fun idea than anything, but Blaze Rods would be able to be used by Railguns as ammo. Perhaps they could have the power of Iron Rods, but have a high chance of burning the target as well.

**Comment by TeamSpen210** [comment]
A railgun operates using electromagnetism, so the projectile needs to be magnetic. I’m not sure if Blazes are metallic or not...

**Comment by mindforger** [comment]
sulfur contamination (assuming sulfur being main part of blaze rods) distorts magnetic properties of metal, though it is only described as impact on permamagnetic properties and i could not find any source on the effect regarding electromagnetism i would say technically @TeamSpen210 is right

but having blaze rods as fiery infused projectiles would be nice, though i would make it's break chance 100% as they are fragile by nature (can be crafted by hand into dust)

**Comment by BluSunrize** [comment]
Friendly reminder that IE's railgun is technically a linear induction catapult, which uses a sled on which the projectile rests. The projectile itself doesn't need to be magnetic.

And yes, I'll consider blaze rods when I finally get around to reworking the railgun.

**Comment by BluSunrize** [comment]
Oh right, this is implemented now.
