### ISSUE TITLE
Loading World Bug

### ISSUE THREAD

**Issue by Blizzor** [BluSunrize/ImmersiveEngineering#386]
There is a big problem with the Worldloading. If we Place the Wire Connectors in a world, the world is permanent loaded. If we break the connectors, the bug isn't going away.

For more Information:
I work on a Infinity Modpack Server from myftb.de. We have a worldmanagment so everyone gets a world and if the player isn't on, the world is unloaded. But since Immersive Engineering is added, the worlds are loaded. We can't handle the server because of that.

I hope you can fix the problem

**Comment by mindforger** [comment]
how about giving some details, to get a better view and to reproduce the issue?

**Comment by Blizzor** [comment]
It's hard to explain. We only know, the world is loading permanent, since something from ImmersiveEngineering is placed there. And after removing it, the bug is not going away.
I'm not sure, if it's only when the wire connectors where placed in the world

**Comment by mindforger** [comment]
are you running on the latest version ?

**Comment by Blizzor** [comment]
We are using Infinity 1.10.1 so we use ImmersiveEngineering 0.5.1

**Comment by mindforger** [comment]
this MAY be more related to https://github.com/SleepyTrousers/EnderIO/issues/2673 as i discovered an similar problem, can you try updating ender io on a copy of that world to check if the issue persist, as i can not see besides a "markDirty" in onUnload, which could probably cause this!

**Comment by Blizzor** [comment]
The information is great!
I hope we can fix the problem with this information. 
So... I'm sorry. We will test the next days, if it is because of EnderIO.
After that, I contact you again, if EnderIO is the problem or not.
Thanks for your help!

**Comment by BluSunrize** [comment]
Yeah I have no idea how this could be me, I don't do any chunkloading, do I? .~.

**Comment by malte0811** [comment]
Apparently you do!
It seems like `world.getTileEntity(x, y, z)` loads chunks if the chunk the coords are in is not loadded. When transferring energy you call `ImmersiveNetHandler.getIndirectEnergyConnections`, which calls `toIIC` on a lot of nodes in the network, which calls getTileEntity if the parameter is a `ChunkCoordinate`. If you add `world.blockExists(x, y, z)` as a condition before `getTileEntity`, the chunk loading stops. i don' t know how that affects transfer through unloaded chunks, so don't just copy that :)

**Comment by mindforger** [comment]
uh that means the energy net will act as a chunkloader-extension .. thats maybe an even greater issue

**Comment by BluSunrize** [comment]
Oookay, yeah that does seem like a bad idea. Let me fix that very quickly.
