### ISSUE TITLE
[1.12]New config option for Excavators

### ISSUE THREAD

**Issue by Dr-Mic** [BluSunrize/ImmersiveEngineering#3861]
[Suggestion] Would it be possible to add a config option to restrict excavators to only one per chunk?
I was playing a pack where mineral deposits were infinite but you had to explore to find the ones you want or more of the ones you had. I realized i could put multiple excavators in one chunk and it removed much of the exploration. Thank you for your time.

**Comment by BluSunrize** [comment]
No, not easily realizable. Also, we are no longer adding features to 1.12
