### ISSUE TITLE
[Suggestion] Redstone Transmitting Conveyor Variants

### ISSUE THREAD

**Issue by z64555** [BluSunrize/ImmersiveEngineering#3863]
As title says, these variants of conveyor belts transmit redstone signals in addition to their normal ability of halting their movement.  By chaining several of these together, it would be possible to halt the entire conveyor line up to their beginning, thereby allowing the "backstuffing" behavior such as seen in Factorio.

The redstone transmission would be lossless, and weakly powered to non-conveyor belts.  Things such as hoppers and Extraction belts will halt insertion onto the belt line, but they won't transmit the redstone signal past them.  A suggested recipe would be a conveyor/elevated conveyor + redstone wire.

Additionally, the conveyors should emit a redstone signal if they cannot insert an item into an inventory, or if they're trying to insert into a non-inventory block.  The items will be carried up to the point where they reach the edge of the block and then trigger the redstone signal to stop the line.  ...This might be better off as an insertion variant, in which case its recipe could be a conveyor/elevating conveyor + redstone probe.

**Comment by BluSunrize** [comment]
No. Has already been suggested before.
Won't be happened. Vanilla redstone is an utter mechanical mess, I'm not digging into that.

Also, normal conveyors completely ignore redstone in 1.14 anyway.

**Comment by z64555** [comment]
Well rip that idea.  Thanks for the feedback.
