### ISSUE TITLE
[1.12.2] Tank crashes when right clicked with Engineer's hammer to form the multiblock

### ISSUE THREAD

**Issue by SanjivanM** [BluSunrize/ImmersiveEngineering#3868]
So I built a tank, followed all the placements, etc, but when I clicked the bottom center of a side (not on the fence layer), the game froze, then crashed after a few seconds.  Restarting Minecraft then re-opening the world crashes the game.  I had to use UniversalMC to edit the world and remove instances of immersiveengineering:tank TE's to make the world load in.  After loading the world in, the area of the tank looked wacky.  Seems like each *block* of the multiblock had turned into a multiblock.

Initial Crash: [crash-2020-05-17_17.22.14-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4645699/crash-2020-05-17_17.22.14-client.txt)

TE's that had to be removed from UniversalMC: 
![image](https://user-images.githubusercontent.com/33943333/82244339-f0a55d00-98f5-11ea-8e99-4c962c12fb88.png)

Screenshot in the world after removing TE's: ![2020-05-18_10 57 11](https://user-images.githubusercontent.com/33943333/82245339-a1f8c280-98f7-11ea-9037-793aa6ff733b.png)

**Comment by malte0811** [comment]
Does this happen outside of a dev environment? The field missing in the crash should exist, but I don't trust Forge's runtime deobfuscation 100% and it seems like the most likely cause for this crash.

**Comment by SanjivanM** [comment]
No, also, in the dev environment, seems that the tanks are transparent, you can basically walk through them...

**Comment by BluSunrize** [comment]
If this is a dev only crash, we're not gonna dig into it further
