### ISSUE TITLE
Industrial Squeezer Output Failure

### ISSUE THREAD

**Issue by xWTyrone** [BluSunrize/ImmersiveEngineering#387]
Running:
IE Beta 0.5.1 integrated in FTB Infinity

Issue with:
Multiblock structure Industrial Squeezer non-player inventory interaction not working as expected.

Further explanation:
The Industrial Squeezer has only one recipe that yields an item. 8x Coke Dust yield 8x Graphite Dust (simplifying). While I'm able to pipe in items to the machine, when piping out, nothing happens.

Expected behaviour:
Items in the output slot should be able toexit the machine automatically.

Notes:
Pics not available.

Any fix for this?

**Comment by AEnterprise** [comment]
did you try the extracting from the holes in the botom center sides of it?

**Comment by xWTyrone** [comment]
Those were my first attempt. Not working...

**Comment by mindforger** [comment]
what type of pipes did you use? there was an issue that the inventory was not properly available, so pulling did not work! try 0.5.4 or use a proper inventory as buffer

**Comment by xWTyrone** [comment]
Outputting to chests doesn't work. I checked that issue but after the closing, there's a comment talking about such things ocurring... I need to restart Minecraft and check it all out.

**Comment by BluSunrize** [comment]
Should be an error that was fixed for 0.5.4 already, reopen if problem persists.

**Comment by xWTyrone** [comment]
Still same error with new version.
