### ISSUE TITLE
[1.12.2] Biodiesel generator doesn't seem to be accepting fuel/outputting power

### ISSUE THREAD

**Issue by SanjivanM** [BluSunrize/ImmersiveEngineering#3870]
Here's my setup:
![2020-05-18_15 15 18](https://user-images.githubusercontent.com/33943333/82265054-f8c3c380-991a-11ea-8deb-da51eaeb63fc.png)
And here's the tank with Biodiesel in it:
![2020-05-18_15 14 56](https://user-images.githubusercontent.com/33943333/82265076-037e5880-991b-11ea-88ef-938fbce7ff88.png)

The generator output is connected to a series of HV capacitors, one of which  is connected to a HV transformer stepping the power to MV, which is then relayed to an active Arc Furnace.

Mod list: 
![image](https://user-images.githubusercontent.com/33943333/82265206-4b9d7b00-991b-11ea-9f57-5cab2ee5c61f.png)

I've also tested fluid output with IC2 and Extrautils fluid pipes, none of which seem to feed fuel into the generator, although it looks like 200mB of fluid was taken by one of the pipes.

Am I missing a connection or a component in the network? I suspect that it has to do with one of the fluid handling multiblocks in my setup...

**Comment by BluSunrize** [comment]
What's the energy level of your capacitors?

Did you invert redstone control on the diesel gen?

**Comment by SanjivanM** [comment]
Energy level was 0 on all capacitors in the network, I did have a lever attached to the generator, but I toggled it on/off, but it still didn't work.

Also quick suggestion (don't have enough time to make an issue now): config for generator fuels? I want to use IC2 biogas as fuel...

**Comment by BluSunrize** [comment]
If your capacitors don't have power, then your generator isn't generating.

Are they actually set to accept an input from the top? Please take some close up pictures of the components of the system.

**Comment by SanjivanM** [comment]
Input from Biodiesel generator to HV capacitors
![2020-05-19_10 50 00](https://user-images.githubusercontent.com/33943333/82361154-5578ba00-99bf-11ea-800a-52b549144b7f.png)

Out of the capacitors to the Transformer
![2020-05-19_10 50 33](https://user-images.githubusercontent.com/33943333/82361257-73461f00-99bf-11ea-851d-2ed841ad9118.png)

Transformer setup
![2020-05-19_10 50 47](https://user-images.githubusercontent.com/33943333/82361318-8eb12a00-99bf-11ea-938e-7cf4e63ea772.png)

MV Input from transformer
![2020-05-19_10 50 56](https://user-images.githubusercontent.com/33943333/82361358-9a045580-99bf-11ea-8ecd-741c83b966ff.png)

**Comment by BluSunrize** [comment]
Is your tank actually outputting? Do you have a redstone signal on it?

**Comment by SanjivanM** [comment]
Oh... Yeah, a redstone signal fixed it.  Seems like I missed that part of the tank setup.  Oops!
