### ISSUE TITLE
[Suggestion] High-explosive cartridge change

### ISSUE THREAD

**Issue by thingymajig90** [BluSunrize/ImmersiveEngineering#3872]
I've been using IE recently on the most recent 1.14.alpha build and found the HE rounds had been changed to now break tiles and cause a large explosion would it be possible to add a config option to change it back to how It was before as I feel like it takes away from how much use you can get out of it or have the option to craft less explosive rounds that dont break blocks, thank you

**Comment by BluSunrize** [comment]
Fixed for next release
