### ISSUE TITLE
[1.14.4] Batch crafting Treated Wood consumes Tank

### ISSUE THREAD

**Issue by NillerMedDild** [BluSunrize/ImmersiveEngineering#3873]
### Description of the issue:
When using a Tank from the FluidTank mod, that holds multiple buckets of Creosote Oil to craft Treated Wood, the Tank is immediately consumed. The intended behaviour, as I see it, is for the bucket to be drained of 1000mb of Creosote Oil per craft, untill it's empty.

### Versions & Modlist
- ImmersiveEngineering-0.14-95
- Forge 1.14.4-28.2.16
- LargeFluidTank-14.9.7

Modpack is Enigmatica 4 version 0.5.5 (unreleased)

**Comment by BluSunrize** [comment]
I think the FluidTanks mod would need to implement getContainerItem for its tanks then.
We simply use a vanilla recipe, with a custom ingredient, so we can't affect what item remains after crafting. That's up to the mod.

**Comment by NillerMedDild** [comment]
Cool, I'll inform the mod author, thank you :)
