### ISSUE TITLE
[1.14] The Silo has wrong VoxelShape

### ISSUE THREAD

**Issue by FledgeXu** [BluSunrize/ImmersiveEngineering#3875]
### Description of the issue:
The Silo has wrong VoxelShape.

### Crashlog:
![image](https://user-images.githubusercontent.com/16664654/82754323-af81e100-9dfe-11ea-90dc-41de664d619a.png)

### Versions & Modlist
![image](https://user-images.githubusercontent.com/16664654/82754330-bf012a00-9dfe-11ea-8b8d-ca1884fc5a9c.png)

**Comment by BluSunrize** [comment]
Should be already fixed for the upcoming release.
