### ISSUE TITLE
[1.14.4] [0.14-96] Crash with Quark's Automatic Recipe Unlock

### ISSUE THREAD

**Issue by vectorwing** [BluSunrize/ImmersiveEngineering#3876]
### Description of the issue:
When entering a world with IE and Quark, and Quark's **Automatic Recipe Unlock** setting is enabled, the game crashes with a "Ticking memory connection". Disabling the setting prevents crashing, but enabling it again crashes every time.

The crash happens in a minimal instance as well.

### Crashlog:
Main Modpack (43 mods):
https://gist.github.com/vectorwing/2d10b652302a13d1502a0312522f51d3

Minimal Instance:
https://gist.github.com/vectorwing/189b5bab3b04e48e3eca73ccd0337b3b

### Versions & Modlist
forge-1.14.4-28.2.16-client
forge-1.14.4-28.2.16-universal
ImmersiveEngineering-0.14-96
AutoRegLib-1.4-35
Quark-r2.0-212
jei-1.14.4-6.0.0.27

**Comment by BluSunrize** [comment]
I haven't yet gone ahead to reproduce this, it's merely a suspicion from reading code, but it looks like `MultiblockRecipe.outputList` might be null. Easiest fix would probably be to initialize it upon declaration. An empty list shouldn't be too detrimental on memory, since most recipes will reinitailize it anyway.

**Comment by detecjack** [comment]
i think i have same issue as yours

https://pastebin.com/neqX0BPZ

**Comment by BluSunrize** [comment]
This should be fixed for future releases. If anyone would like to verify my fix, try this development build:

https://ci.blamejared.com/job/Immersive%20Engineering/679/

**Comment by detecjack** [comment]
> This should be fixed for future releases. If anyone would like to verify my fix, try this development build:
> 
> https://ci.blamejared.com/job/Immersive%20Engineering/679/

can confirm this fixed the issue of quark crash
