### ISSUE TITLE
[1.12.2] Steel advancement doesn't use oredict

### ISSUE THREAD

**Issue by Speak2Erase** [BluSunrize/ImmersiveEngineering#3879]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
Describe what happens, how it affects your game/gameplay and provide screenshots where possible.
This is more of an annoying bug. In the pack I'm playing, the IE steel is replaced with TF's oredict steel. It's fine for crafting recipes but means my advancements tab is stuck.

### Versions & Modlist
IE and Forge versions are mandatory. *Note that saying "latest" is **not** valid. Always give the proper version number*
https://github.com/wistlyr/Realistic-Unreality
IE:0.12-92
Forge:14.23.5.2847

**Comment by BluSunrize** [comment]
Just use a command to give yourself the advancement. Not our fault that the pack maker didn't replace the advacement with a differently triggered one. That's what datapacks are for.
