### ISSUE TITLE
[1.14.4] Manual font rendering issue when using resource packs

### ISSUE THREAD

**Issue by ReconCubed** [BluSunrize/ImmersiveEngineering#3880]
### Description of the issue:
When using Faithful 32x, the font used for the manual renders as a box ( [] ). This makes the manual unreadable until turning off resource packs.

![issue](https://i.imgur.com/ReoziL6.png)

### Versions & Modlist
Forge: 28.2.3
IE: 0.14-95
Faithful 1.14

**Comment by Hubry** [comment]
Common issue with Faithful, see Vazkii/Patchouli#236. It's on their side (maybe FaithfulTeam/Faithful#57 will fix it, but it doesn't seem to be out on CurseForge yet). Try to delete the files listed as deleted in that PR, and if that fails, the entire font folder.
