### ISSUE TITLE
[1.12.2] Engineers Hammer and Wirecutters don't show durability or use Mending

### ISSUE THREAD

**Issue by SanjivanM** [BluSunrize/ImmersiveEngineering#3881]
Yes, I have checked that Advanced Tooltips are enabled.
Tested with IE 0.12.92 and JEI 4.15.0.293

![2020-05-26_10 25 01](https://user-images.githubusercontent.com/33943333/82931383-b2362080-9f3b-11ea-98aa-2a14e04833b6.png)
![2020-05-26_10 26 51](https://user-images.githubusercontent.com/33943333/82932051-b3b41880-9f3c-11ea-81f2-d835acf73ad3.png)

After smashing a stack of ore, the hammer's durability is at ~50%, but shows no durability number.  It also doesn't mend if held in the off-hand while gaining XP.
Also the same case with the Wirecutters:
![2020-05-26_10 34 16](https://user-images.githubusercontent.com/33943333/82932076-bdd61700-9f3c-11ea-94fc-836f7f77f345.png)
![2020-05-26_10 34 24](https://user-images.githubusercontent.com/33943333/82932082-c0387100-9f3c-11ea-82b3-5be85778e07c.png)
![2020-05-26_10 35 33](https://user-images.githubusercontent.com/33943333/82932107-c595bb80-9f3c-11ea-86df-5e6d1f864a3f.png)

**Comment by BluSunrize** [comment]
They're not designed to use mending. This is intentional.

**Comment by SanjivanM** [comment]
ok, Minecraft did allow me to put Mending on them, so I assumed they'd mend.  That's 2 emeralds I lost :P
