### ISSUE TITLE
No IE ore generated in multiplayer world

### ISSUE THREAD

**Issue by jbreving** [BluSunrize/ImmersiveEngineering#3883]
### Description of the issue:
No ores from Immersive Engineering appear in the world on multiplayer server (single player works fine).
I encountered this originally with more mods on a server I'm trying to set up for my son. I tried removing some mods that affected world generation and tested on the server. No IE ores. I checked single player. I found the IE ores! I added some back, still found IE ores in single player. I added the last one back and found IE ores... That was confusing. I tried running the server after that with the world folder renamed. Log in and no IE ores... So I tried just IE on the server and in single player. No IE ores on the server. Yes IE ores in single player. So here I am. I'm going to figure out how to pregenerate a world in single player and set a world border for the server to work around this problem, but I thought you should know, especially since I see there's a poorly written similar issue.

### Versions & Modlist
Server runs:
forge 1.14.4-28.2.0
immersive engineering 0.14-96
and no other mods

(yes, I updated to 96 and tested again)

**Comment by malte0811** [comment]
It's working fine for me. Is this happening in a vanilla biome or a modded one? Does it happen with just IE (and no other mods at all, other than Forge)?

**Comment by BluSunrize** [comment]
closing this due to lack of feedback
