### ISSUE TITLE
[1.14.4] Newest Version incompatible with Cooking for Blockheads

### ISSUE THREAD

**Issue by Jason-m858** [BluSunrize/ImmersiveEngineering#3884]
Hello,
i have just updated to the latest version of immersive engineering and now i get a crash every time i enter a world. In the previous version I did not have this problem. The problem disappears when I remove either ImmersiveEngineering or Cooking for Blockheads. But since it worked before that and Cooking for Blockheads didn't get an update I guess the problem is with ImmersiveEngineering.
[latest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/4698388/latest.log)
[crash-2020-05-28_23.31.07-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4698390/crash-2020-05-28_23.31.07-server.txt)

**Comment by DanNetwalker** [comment]
I'm having the same issue. When cooking for blockheads tries to call net.blay09.mods.cookingforblockheads.registry.CookingRegistry.initFoodRegistry, something explodes at blusunrize.immersiveengineering.api.crafting.MultiblockRecipe.func_77571_b(MultiblockRecipe.java:34). Problem disappears when downgrading IE to 0.14-95 or removing cooking for blockheads

**Comment by Kai-Kramer** [comment]
Crash log for above issue, I can recreate--when creating a new world, generation reaches 100% and MC either stalls or crashes outright. Cooking for Blockheads is latest 1.14.4 release.

https://pastebin.com/LsjFV7CL

**Comment by Kai-Kramer** [comment]
This issue seems to be fixed with the dev build mentioned in the following:

>This should be fixed for future releases. If anyone would like to verify my fix, try this development build:
>
>https://ci.blamejared.com/job/Immersive%20Engineering/679/

_Originally posted by @BluSunrize in https://github.com/BluSunrize/ImmersiveEngineering/issues/3876#issuecomment-633495392_

Tested with Cooking for Blockheads as well as about 80 other mods.

**Comment by Jason-m858** [comment]
It is working with the Dev Version of the Mod
