### ISSUE TITLE
[1.14.4] [0.14-96] Steel tools don't render like tools on player model and off-hand

### ISSUE THREAD

**Issue by vectorwing** [BluSunrize/ImmersiveEngineering#3886]
### Description of the issue:
When holding a Steel tool of any kind, it displays as a normal item on the player model, instead of held by its handle.

![Tool render](https://user-images.githubusercontent.com/5566692/83299580-d6f4f700-a1cc-11ea-8bb1-0cbfafd307de.png)

In first-person, the problem only happens when held in the off-hand. Normal hotbar selection looks correct.

![off-hand](https://user-images.githubusercontent.com/5566692/83300091-bf6a3e00-a1cd-11ea-8ba6-12744cf65e31.png)

### Versions & Modlist
Forge 28.2.16
ImmersiveEngineering-0.14-96
jei-1.14.4-6.0.0.27

**Comment by TeamSpen210** [comment]
They're using the `item/generated` parent, but they should be using `item/handheld` which has the correct orientations.
