### ISSUE TITLE
[1.14.4] [0.14-96] removing Buzzsaw quiver keeps blades in quiver attached to Buzzsaw item

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#3890]
The blades in the (hidden) quiver slots are unusable without a Blade Quiver upgrade attached, but can be reaccessed when reattaching a Blade Quiver upgrade to the buzzsaw

Suggestion: Attach the blades in the quiver slots to the Blade Quiver upgrade item upon removal and show it in the Blade Quiver's hover text
Sidetracking: A similar approach could be used for excess fuel when removing a Large Tank upgrade. Instead of just deleting the excess fuel, attach it to the tank.

**Comment by BluSunrize** [comment]
Unfortunately, there is no easy way to implement storing those values on the removed item. We don't have easily available hooks to handle that.
Tanks currently void the fluid when they are removed. I will look into dropping the sawblades instead of keeping them in the buzzsaw.

**Comment by MalkContent** [comment]
couldn't the quivered items just be stored in the quiver inventory from the getgo?
similarly for the tanks.
and then access the upgrade-item's inventory when drawing from the quiver/from the tank

**Comment by BluSunrize** [comment]
No, not easily. Any item that provides that storage uses capabilities.
1) Upgrade items don't have those, and adding them would require specialcasing them into separate classes
2) The respective capabilities of Buzzsaw and Drill would then need to somehow "nest" the capabilities of their upgrades.

That'd require a pretty massive overhaul of the entire system. I can look into it for sure, and estimate the effort, but I'm not sure if it's viable.
