### ISSUE TITLE
[Suggestion]Change the Kinetic Dynamo texture to inform more connector possibilities.

### ISSUE THREAD

**Issue by Codified-Vexing** [BluSunrize/ImmersiveEngineering#3898]
The Kinetic Dynamo has a yellow dot on top that suggests the location where electrical connectors can placed there. Nonetheless, the connectors will still work even if placed on other faces of the Dynamo, but this isn't obvious or intuitive. I suggest to have the yellow on the other faces of the Dynamo too.

**Comment by BluSunrize** [comment]
Wouldn't really look good on the sides, given there's the coil texture there. Plus, nothing in the manual say you can only draw from the top =P

**Comment by Codified-Vexing** [comment]
It'd be good enough if the dot was only on the grey face, I feel. The coil face would be easily implied.
