### ISSUE TITLE
[Suggestion] Improvements to the splitting conveyor belt.

### ISSUE THREAD

**Issue by Codified-Vexing** [BluSunrize/ImmersiveEngineering#3899]
The Conveyor Belt could be configurable to work as a round robin, with outputs to all sides and even downwards (like the trapdoor belt), that can be enabled or disabled with the hammer.
Other feature I'm missing from the splitting conveyor belt is a scaffold version of it. All other belt types have it, so why not this one?

**Comment by BluSunrize** [comment]
Scaffold version is implemented. I'm not doing an "all sides" one, because fuck texturing that =p
