### ISSUE TITLE
map becoming iresponsive

### ISSUE THREAD

**Issue by bigpodgurc** [BluSunrize/ImmersiveEngineering#39]
after some time you play a map it just becomes iresponive you cant do anything actaly even but game haveing 130 fps  but after i deleted the mod my map is again responsive

**Comment by bigpodgurc** [comment]
and please if i can get more newer coppy of mod

**Comment by BluSunrize** [comment]
1) I'd need a bit more detail, btu I get the feelign I know what caused it and I've fixed it long since.

**Comment by bigpodgurc** [comment]
1) its like this after playing the map for i belive 20 hours or so map itself started being iresponsive it gives the same idea as if the game was lagging (guis not opening blocknot droping on break but not puting them back like in lag times) and im on singleplayer with 130 fps and there was no line,abou sistem time changing or whatever you know what i mean so that shouldnt be a problem after exiting and windows saying minecraft not responding while shuting down internal server it started working fir few mins thats it. When i deleted immersive engeeniring. map didnt become iresponsive and i played for xouple of hours shreight

I also tried adding more ram actaly tried with 10 GB BUT didnt help


2) i know how you feel and bla bla bla
i have 2 different prospectives on this mod first is my programmer (trying to mod to unsuccesfuly still learning) side yea i understand you are trying to protect it so no kid can get hand on it while is so buggy. And you do not wanna have some jerk give those kids a bad mod. But because of this programmer side i also like to play with buggy mods of course not game breaking but ok. It makes game even more interesting.
second side is player side who doest understand why dont you at least fix game breaking bugs will give us who like your mod to at least have something.


Mod is great i hope i have been a help and sorry for bad grammer im not from english speaking country. Its ok however you decide but do it so its in the best interest of u and the final product


BYE BIGPODGURC

**Comment by BluSunrize** [comment]
That error is caused by you using the old build which has a memory leak that is long since fixed

**Comment by bigpodgurc** [comment]
Ok thanks and i hope mod is done quickly because i love how thinks are done in it specialy the wires and watermills thats even why i compiled and put it into my mods folder so i realy hope is done quicly but with good quality or that i get version that fixes this memory leak or at least where it is so i can fix it myself but im just asking and if you do not want to give me its your call

Thanks anyway
