### ISSUE TITLE
Bug: disappearing Wires

### ISSUE THREAD

**Issue by Ramog** [BluSunrize/ImmersiveEngineering#390]
Sometimes when I load my world the wires disappear. I think that only happens when I restart my minecraft before.
I hope you can fix this, because I'am a big fan of your mod. But it is very annoying that the wires disappear.

**Comment by GirafiStudios** [comment]
I think this is a known, that it can happen.
But anyways, what version of Immersive Engineering are you using?

**Comment by cobra** [comment]
see #160. Which version are you running?

**Comment by Ramog** [comment]
I run v0.5.3 of immersive engineering I downgraded it because I hoped that it can fix this

**Comment by Ramog** [comment]
looks like deleting RFtools fixed it for me
but still thanks for the help
