### ISSUE TITLE
[1.12.2] Server crash - CME - ConcurrentModificationException at blusunrize.immersiveengineering.common.blocks.metal.TileEntityFluidPipe.onLoad(TileEntityFluidPipe.java:184)

### ISSUE THREAD

**Issue by ProsperCraft** [BluSunrize/ImmersiveEngineering#3905]
### Description of the issue:
We started having CME crashes after the update of our pack from 5.2 to 5.3 of TownCraft - CME issues are super hard to track down, we just had a crash with IE listed in the stacktrace for the first time, the player logged in twice and crashed the server twice, we removed IE and its two addons 
she was able to log in with the crash.  I know this doesn't mean IE is the only cause because of the nature of CME's.    Just hoping you can find something on your side.

### Crashlog:
We were having a lot of these-
https://gist.github.com/ProsperCraft/a7994e66dabe1bf9f3b273cce977daa3

Then today we got several of these-
https://gist.github.com/ProsperCraft/5d5508159b468a8a6414ff05be4406b2

Here is a server log with IE
[CME with IE.log](https://github.com/BluSunrize/ImmersiveEngineering/files/4740713/CME.with.IE.log)

Here is a server log without IE
[debug.log](https://github.com/BluSunrize/ImmersiveEngineering/files/4740714/debug.log)

Here are all of the crashes-
[crash-2020-05-30_02.41.15-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4740681/crash-2020-05-30_02.41.15-server.txt)
[crash-2020-05-30_02.53.16-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4740682/crash-2020-05-30_02.53.16-server.txt)
[crash-2020-05-30_03.03.49-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4740683/crash-2020-05-30_03.03.49-server.txt)
[crash-2020-05-30_03.24.56-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4740684/crash-2020-05-30_03.24.56-server.txt)
[crash-2020-05-30_03.40.11-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4740685/crash-2020-05-30_03.40.11-server.txt)
[crash-2020-05-30_03.46.21-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4740686/crash-2020-05-30_03.46.21-server.txt)
[crash-2020-05-30_03.53.53-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4740687/crash-2020-05-30_03.53.53-server.txt)
[crash-2020-05-30_04.00.43-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4740688/crash-2020-05-30_04.00.43-server.txt)
[crash-2020-05-30_04.06.59-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4740689/crash-2020-05-30_04.06.59-server.txt)
[crash-2020-05-30_04.13.22-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4740690/crash-2020-05-30_04.13.22-server.txt)
[crash-2020-05-30_04.19.19-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4740691/crash-2020-05-30_04.19.19-server.txt)
[crash-2020-05-30_04.27.37-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4740692/crash-2020-05-30_04.27.37-server.txt)
[crash-2020-05-30_04.57.32-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4740693/crash-2020-05-30_04.57.32-server.txt)
[crash-2020-06-05_04.23.00-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4740694/crash-2020-06-05_04.23.00-server.txt)
[crash-2020-06-05_04.28.19-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4740695/crash-2020-06-05_04.28.19-server.txt)
[crash-2020-06-05_04.39.36-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4740696/crash-2020-06-05_04.39.36-server.txt)
[crash-2020-06-05_05.20.40-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4740697/crash-2020-06-05_05.20.40-server.txt)
[crash-2020-06-05_05.24.56-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4740698/crash-2020-06-05_05.24.56-server.txt)
[crash-2020-06-05_06.07.54-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4740699/crash-2020-06-05_06.07.54-server.txt)
[crash-2020-06-06_00.57.22-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4740700/crash-2020-06-06_00.57.22-server.txt)
[crash-2020-06-06_04.38.50-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4740701/crash-2020-06-06_04.38.50-server.txt)
[crash-2020-06-06_15.05.34-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4740702/crash-2020-06-06_15.05.34-server.txt)
[crash-2020-06-06_15.11.07-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4740703/crash-2020-06-06_15.11.07-server.txt)
[crash-2020-06-06_15.23.38-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4740704/crash-2020-06-06_15.23.38-server.txt)
[crash-2020-05-29_17.06.07-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4740705/crash-2020-05-29_17.06.07-server.txt)
[crash-2020-05-29_17.12.54-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4740706/crash-2020-05-29_17.12.54-server.txt)
[crash-2020-05-29_17.24.43-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4740707/crash-2020-05-29_17.24.43-server.txt)
[crash-2020-05-29_23.54.23-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4740708/crash-2020-05-29_23.54.23-server.txt)
[crash-2020-05-30_00.00.41-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4740709/crash-2020-05-30_00.00.41-server.txt)
[crash-2020-05-30_01.47.03-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4740710/crash-2020-05-30_01.47.03-server.txt)
[crash-2020-05-30_01.53.27-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4740711/crash-2020-05-30_01.53.27-server.txt)
[crash-2020-05-30_02.34.32-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4740712/crash-2020-05-30_02.34.32-server.txt)

### Versions & Modlist

ImmersiveEngineering-0.12-92

Modlist- https://www.curseforge.com/minecraft/modpacks/towncraft

**Comment by BluSunrize** [comment]
The actual crash happens within vanilla code. It doesn't look like IE is the cause of this, it's merely in the stacktrace due to execution

**Comment by ProsperCraft** [comment]
after re-enabling IE the players played for hours, then someone that had not logged in for a while logged in and the server crashed multiple times, 

https://gist.github.com/ProsperCraft/8e9e378c15a82aaaaec95349525f4efa
[With IE - latest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/4741422/With.IE.-.latest.log)


Then I disabled Immersive Tech - still crashed when the player logged in
[Without ImmersiveTech-latest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/4741424/Without.ImmersiveTech-latest.log)
[crash-2020-06-07_00.10.02-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4741426/crash-2020-06-07_00.10.02-server.txt)

Then I disabled Immersive Petroleum still crashed when the player logged in-
[Without Immersive Petroliumlatest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/4741427/Without.Immersive.Petroliumlatest.log)
[crash-2020-06-07_00.24.12-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4741428/crash-2020-06-07_00.24.12-server.txt)

Then I disabled IE and the player was able to log in without the CME crash-

[WithoutIE-Nocrash-latest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/4741429/WithoutIE-Nocrash-latest.log)

**Comment by ProsperCraft** [comment]
Re-enabled IE, and had another player logging in crashing the server so I did these troubleshooting steps-

I disabled Immersive Vehicles- still crashed.
[Without IV-crash-2020-06-07_05.43.30-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4741468/Without.IV-crash-2020-06-07_05.43.30-server.txt)


I disabled Mohist, and ran with Forge only- Still crashed-
[CrashwithForge-no Mohistlatest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/4741469/CrashwithForge-no.Mohistlatest.log)
[ForgeOnly-crash-2020-06-07_06.02.36-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4741470/ForgeOnly-crash-2020-06-07_06.02.36-server.txt)


I disabled IE and it did not crash-

**Comment by BluSunrize** [comment]
Have you tried with the new IE version, Build 98?

**Comment by ProsperCraft** [comment]
With 98

https://gist.github.com/ProsperCraft/2bf51af7fe8b33373428bab749f178a3

https://gist.github.com/ProsperCraft/6b77cee9cabfa6224f7430712e330d83

**Comment by ProsperCraft** [comment]
https://gist.github.com/ProsperCraft/063598f2027cd8fa8147231cb487ae34

**Comment by Kurtchekov** [comment]
@ProsperCraft have you tried adding MCT Immersive Technology to your modpack? By default, it replaces IE's pipes with its own and should have that specific bug fixed.

**Comment by ProsperCraft** [comment]
Yes, we have Immersive tech in the modpack, it crashed with it installed, then as a diagnostic test, I disabled Immersive Tech and it still crashed.



> after re-enabling IE the players played for hours, then someone that had not logged in for a while logged in and the server crashed multiple times,
> 
> https://gist.github.com/ProsperCraft/8e9e378c15a82aaaaec95349525f4efa
> [With IE - latest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/4741422/With.IE.-.latest.log)
> 
> Then I disabled Immersive Tech - still crashed when the player logged in
> [Without ImmersiveTech-latest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/4741424/Without.ImmersiveTech-latest.log)
> [crash-2020-06-07_00.10.02-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4741426/crash-2020-06-07_00.10.02-server.txt)
> 
> Then I disabled Immersive Petroleum still crashed when the player logged in-
> [Without Immersive Petroliumlatest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/4741427/Without.Immersive.Petroliumlatest.log)
> [crash-2020-06-07_00.24.12-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4741428/crash-2020-06-07_00.24.12-server.txt)
> 
> Then I disabled IE and the player was able to log in without the CME crash-
> 
> [WithoutIE-Nocrash-latest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/4741429/WithoutIE-Nocrash-latest.log)

**Comment by Kurtchekov** [comment]
@ProsperCraft That's the original Immersive Tech, the one I mean is this one https://www.curseforge.com/minecraft/mc-mods/mct-immersive-technology it's a continuation of the original one.

**Comment by ProsperCraft** [comment]
Well how about that! I will swap it out immediately and let you know.

**Comment by ProsperCraft** [comment]
Turns out that did not fix the issue at all, updated everything, changed Immersive Technology out, and it didn't help, I paired it down to no IR addons, only IR and still get a CME crash every single time, remove IR, no crashes at all since we disabled IE on the 4th 8 days ago.

https://gist.github.com/ProsperCraft/4523253cfbf2694504d530f5a465285d

[crash-2020-08-04_20.10.48-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5064671/crash-2020-08-04_20.10.48-server.txt)
[crash-2020-08-04_20.26.52-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5064672/crash-2020-08-04_20.26.52-server.txt)
[crash-2020-08-04_20.43.39-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5064673/crash-2020-08-04_20.43.39-server.txt)
[crash-2020-08-04_20.54.13-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5064674/crash-2020-08-04_20.54.13-server.txt)
[crash-2020-08-04_21.04.39-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5064675/crash-2020-08-04_21.04.39-server.txt)
[crash-2020-08-04_21.19.17-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5064676/crash-2020-08-04_21.19.17-server.txt)
[crash-2020-08-04_19.40.36-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5064677/crash-2020-08-04_19.40.36-server.txt)
[crash-2020-08-04_19.46.43-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5064678/crash-2020-08-04_19.46.43-server.txt)

**Comment by BluSunrize** [comment]
IE is not longer receiving any 1.12 support
