### ISSUE TITLE
Startup crash

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#3906]
Immersive engineering 1.15.2 shows the following error on launch even when launched my itself
![Screenshot (27)](https://user-images.githubusercontent.com/47836751/83955126-aab92600-a81d-11ea-9dd4-3269f21336fc.png)

**Comment by malte0811** [comment]
Please upload the complete crashlog to https://gist.github.com, https://pastebin.com or a similar site. The crashlog should be in you minecraft folder in the `crash-reports` subdirectory.

**Comment by Arbiter13961** [comment]
Good Day. 
The above isn`t actually a crash but an issue that is picked up by the mod within the launcher. 
I have Attached the latest  Log that is given unfortunately there is no Crash report. 

[latest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/4752633/latest.log)

**Comment by malte0811** [comment]
Try updating Forge to the recommended version.

**Comment by Arbiter13961** [comment]
Evening I have done. 3.1.88 and one above 3.1.89.Neither of them work it gives me the same error. What else could I try? 
    On Tuesday, June 9, 2020, 04:42:15 PM GMT+2, malte0811 <notifications@github.com> wrote:  
 
 


Try updating Forge to the recommended version.

**Comment by Arbiter13961** [comment]
Oh sorry.
Rude of me. 
Thank you or your response.
