### ISSUE TITLE
[1.15] breaker switch visual and rotation

### ISSUE THREAD

**Issue by Swantsy** [BluSunrize/ImmersiveEngineering#3907]
### Description of the issue:
placing down a breaker switch if not standing close and aiming for bottom or top of the block, the visual of the breaker switch will shift over one block to the south east. it is also locked into the north/south or south/north rotation, no east-west.

### Versions & Modlist
forge 31.8.2
ImmersiveEngineering-0.15-99

log list, including modlist
https://paste.ee/p/naD0y

**Comment by malte0811** [comment]
Fixed in e99dca6
