### ISSUE TITLE
[1.15] WorkBench crashes when putting Blueprint in slot

### ISSUE THREAD

**Issue by SkySom** [BluSunrize/ImmersiveEngineering#3908]
### Description of the issue:
When placing a Blueprint in the input slot, the client crashes.

### Crashlog:
https://gist.github.com/SkySom/2a5f6f0e8c919aaaadbb280eaed2a507

### Versions & Modlist
Forge: 31.2.8
IE: 0.15-99

**Comment by malte0811** [comment]
Fixed in 736084b

**Comment by WebDragon** [comment]
Any thoughts on a release for this patch? I can't even re-enter my game now, as I am staring right at the affected workbench -- I relog, and boom, crash right back out again.

**Comment by WebDragon** [comment]
> Any thoughts on a release for this patch? I can't even re-enter my game now, as I am staring right at the affected workbench -- I relog, and boom, crash right back out again.

wait, is this in alpha -103 ? I tried adding that one instead of -99 and it appears to be fixed -- I can get back into the game. 👍
