### ISSUE TITLE
[1.15] Buzzsaw blade transparent in Workbench

### ISSUE THREAD

**Issue by SkySom** [BluSunrize/ImmersiveEngineering#3909]
### Description of the issue:
When the Buzzsaw is rendering in the Workbench's model, the outline of the blade is normal, but the rest of the blade is transparent.

https://imgur.com/a/VbAWqi9

### Versions & Modlist
Forge: 31.2.8
IE: 0.15-99

**Comment by malte0811** [comment]
Fixed in 94466bf
