### ISSUE TITLE
crusher crash ArrayIndexOutOfBoundsException during crusher creation

### ISSUE THREAD

**Issue by rahangar** [BluSunrize/ImmersiveEngineering#391]
This issue is very reproducible.  When I create a crusher, the last step is to right click with an engineer's hammer.  When I do that, I see a crash.  This is my first report, so apologize in advance if the format is wrong.

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 9/4/15 6:32 PM
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: -1

	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityCrusher.getOriginalBlock(TileEntityCrusher.java:63)

	at blusunrize.immersiveengineering.common.blocks.metal.BlockMetalMultiblocks.getOriginalBlock(BlockMetalMultiblocks.java:157)

	at blusunrize.immersiveengineering.common.blocks.metal.BlockMetalMultiblocks.getPickBlock(BlockMetalMultiblocks.java:151)

	at codechicken.nei.api.ItemInfo.getIdentifierItems(ItemInfo.java:486)

	at codechicken.nei.HUDRenderer.renderOverlay(HUDRenderer.java:42)

	at codechicken.nei.ClientHandler.tickEvent(ClientHandler.java:163)

	at cpw.mods.fml.common.eventhandler.ASMEventHandler_66_ClientHandler_tickEvent_RenderTickEvent.invoke(.dynamic)

	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)

	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)

	at cpw.mods.fml.common.FMLCommonHandler.onRenderTickEnd(FMLCommonHandler.java:340)

	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1003)

	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)

	at net.minecraft.client.main.Main.main(SourceFile:148)

	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

	at java.lang.reflect.Method.invoke(Method.java:483)

	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)

	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityCrusher.getOriginalBlock(TileEntityCrusher.java:63)
	at blusunrize.immersiveengineering.common.blocks.metal.BlockMetalMultiblocks.getOriginalBlock(BlockMetalMultiblocks.java:157)
	at blusunrize.immersiveengineering.common.blocks.metal.BlockMetalMultiblocks.getPickBlock(BlockMetalMultiblocks.java:151)
	at codechicken.nei.api.ItemInfo.getIdentifierItems(ItemInfo.java:486)
	at codechicken.nei.HUDRenderer.renderOverlay(HUDRenderer.java:42)
	at codechicken.nei.ClientHandler.tickEvent(ClientHandler.java:163)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_66_ClientHandler_tickEvent_RenderTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['zuul4242'/4, l='MpServer', x=441.62, y=69.62, z=315.38]]
	Chunk stats: MultiplayerChunkCache: 1076, 1076
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,64,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1783536 game time, 12229 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 34 total; [EntityClientPlayerMP['zuul4242'/4, l='MpServer', x=441.62, y=69.62, z=315.38], EntityBat['Bat'/33793556, l='MpServer', x=422.50, y=48.10, z=324.75], EntityCow['Cow'/21544, l='MpServer', x=519.50, y=63.00, z=277.03], EntityBat['Bat'/33797735, l='MpServer', x=461.75, y=52.10, z=323.25], EntityCaveSpider['Cave Spider'/425071, l='MpServer', x=-43.95, y=-0.05, z=2.48], EntityBat['Bat'/33797767, l='MpServer', x=450.92, y=23.00, z=376.25], EntityBat['Bat'/33797771, l='MpServer', x=456.08, y=25.00, z=377.69], EntityBat['Bat'/33797770, l='MpServer', x=455.16, y=24.85, z=381.75], EntityBat['Bat'/33797773, l='MpServer', x=440.33, y=42.00, z=351.65], EntityBat['Bat'/33797777, l='MpServer', x=430.60, y=34.55, z=350.25], EntityCow['Cow'/665871, l='MpServer', x=387.53, y=65.00, z=352.78], EntityChicken['Chicken'/665868, l='MpServer', x=379.47, y=64.00, z=391.47], EntityCow['Cow'/665874, l='MpServer', x=378.34, y=63.00, z=343.72], EntityCow['Cow'/665872, l='MpServer', x=370.63, y=63.00, z=327.78], EntityCow['Cow'/665873, l='MpServer', x=382.16, y=64.00, z=345.97], EntityCow['Cow'/20986, l='MpServer', x=498.53, y=65.00, z=319.53], EntityCow['Cow'/20987, l='MpServer', x=502.69, y=64.00, z=319.53], EntityCow['Cow'/20988, l='MpServer', x=501.53, y=65.00, z=317.50], EntityCow['Cow'/20989, l='MpServer', x=501.59, y=64.00, z=321.63], EntityCow['Cow'/663042, l='MpServer', x=421.25, y=64.00, z=377.50], EntityCow['Cow'/663043, l='MpServer', x=431.41, y=73.00, z=373.69], EntityCow['Cow'/663040, l='MpServer', x=428.63, y=71.00, z=376.75], EntityCow['Cow'/663041, l='MpServer', x=426.34, y=68.00, z=374.41], EntityChicken['Chicken'/665095, l='MpServer', x=374.75, y=63.00, z=364.38], EntityCow['Cow'/21038, l='MpServer', x=519.50, y=64.00, z=297.38], EntityCow['Cow'/21039, l='MpServer', x=520.69, y=64.00, z=299.44], EntityCow['Cow'/21040, l='MpServer', x=517.97, y=64.00, z=297.78], EntityCow['Cow'/21041, l='MpServer', x=516.41, y=64.00, z=299.09], EntityItem['item.item.egg'/33797192, l='MpServer', x=378.66, y=63.13, z=362.06], EntityBat['Bat'/33797250, l='MpServer', x=458.25, y=51.10, z=323.25], EntityBat['Bat'/33798283, l='MpServer', x=429.88, y=36.10, z=393.59], EntityBat['Bat'/33798281, l='MpServer', x=446.60, y=33.01, z=312.52], EntityBat['Bat'/33798361, l='MpServer', x=423.56, y=49.10, z=324.75], EntityBat['Bat'/33798365, l='MpServer', x=414.33, y=20.40, z=300.73]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 29367008 bytes (28 MB) / 551026688 bytes (525 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 21 mods loaded, 21 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.110} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.110-universal.jar) 
	UCHIJAAAA	OpenModsCore{0.8} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJAAAA	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJAAAA	compactstorage{v2.0.0a} [CompactStorage] (compactstorage-1.7.10-release-2.0.0.13-universal.jar) 
	UCHIJAAAA	ComputerCraft{1.74} [ComputerCraft] (ComputerCraft1.74.jar) 
	UCHIJAAAA	ComputerCraftEdu{1.74} [ComputerCraftEdu] (ComputerCraftEdu1.74.jar) 
	UCHIJAAAA	ImmersiveEngineering{0.5.4} [Immersive Engineering] (ImmersiveEngineering-0.5.4.jar) 
	UCHIJAAAA	journeymap{@JMVERSION@} [JourneyMap] (journeymap-1.7.10-5.1.0-unlimited.jar) 
	UCHIJAAAA	OpenMods{0.8} [OpenMods] (OpenModsLib-1.7.10-0.8.jar) 
	UCHIJAAAA	OpenPeripheralCore{1.2} [OpenPeripheralCore] (OpenPeripheral-1.7.10-AIO-5.jar) 
	UCHIJAAAA	OpenPeripheral{0.4} [OpenPeripheralAddons] (OpenPeripheral-1.7.10-AIO-5.jar) 
	UCHIJAAAA	OpenPeripheralIntegration{0.3} [OpenPeripheralIntegration] (OpenPeripheral-1.7.10-AIO-5.jar) 
	UCHIJAAAA	RefinedRelocation{1.0.8b} [Refined Relocation] (RefinedRelocation-1.7.10-1.0.8b.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 347.88' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.0.3-303
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:OFF, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: 1.7.10-Forge10.13.4.1448-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.5.0 NVIDIA 347.88, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [Faithful_4]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by GirafiStudios** [comment]
Please use pastebin for the crashlog, instead of posting the whole thing directly in the issue. Makes it more readable too ^^

**Comment by rahangar** [comment]
Thank you.  Is it possible to get a pre-release version so I can test it?  My game can't move forward without this fix.

**Comment by BluSunrize** [comment]
Uh, yeah, you can compile this off of git, if you know how.

**Comment by AEnterprise** [comment]
you can also go intro the forge config and enable the option to remove crashing TE's, enter the world, break the multiblock, close game and turn the config off again

**Comment by rahangar** [comment]
Thanks for the tip.  But I have no problem breaking the multiblock.  

The problem I have is that I can never create the crusher without crashing.  But since I don't use any other mods that provide automated ore crushing, in order for me to advance in the game I need a working IE crusher.

After the crash, when I restart, the crusher is there and in one case I actually got it started and working, but I'm guessing that there is still some corruption/issue in that the crusher never stops running.   So 

I'll try to download and compile from your source on github.  

I do most of my programming on the Mac (Swift, Objective-C for IOS), so I'm a bit new to Java and the environment on PC.  So if you have any instructions/tips on dev env I need to compile the mod, I would much appreciate it.

Regards,
Ramin

**Comment by cobra** [comment]
It's only the crusher animation and sound, but not the processing, which aren't stopping. We already fixed that. 
If you want to compile it yourself: look at how to setup forge for a dev environment. Gradle will do almost everything for you except getting the required deobfuscated versions of the mods IE adds support for and doesn't include the API files.

**Comment by rahangar** [comment]
Awesome.  Thanks again.  I think that should get me started.
