### ISSUE TITLE
[1.14] Pipes not visually connecting to the Refinery outputs.

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#3917]
### Description of the issue:
A pipe leading from the output of a refinery won't display as if it is connected, even though biodiesel comes through the pipe. In some seemingly random places pipes will also not connect to each other and I don't know if it might be a related issue.

### Versions & Modlist
MC Version 1.14.4
Forge Version 28.2.16
IE Version 0.14.97

![2020-06-07_09 01 55](https://user-images.githubusercontent.com/52493793/83963417-f1e6fb80-a89d-11ea-8c9c-c6d98f5de5e2.png)
![2020-06-07_07 55 22](https://user-images.githubusercontent.com/52493793/83963422-f6131900-a89d-11ea-82ef-27bc2231a94f.png)

**Comment by BluSunrize** [comment]
Use the issue template.

**Comment by ghost** [comment]
Are the pipes crossing chunk borders? I recall that causing pipes to disconnect like that back in 1.12.

**Comment by BluSunrize** [comment]
Looking into this now
