### ISSUE TITLE
[1.14] Levers aren't attaching to generator redstone inputs.

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#3918]
### Description of the issue:
You simply can't place a lever on the red dot of a generator.

### Versions & Modlist
MC Version 1.14.4
Forge Version 28.2.16
IE Version 0.14.97

**Comment by BluSunrize** [comment]
Use the issue template.

**Comment by BluSunrize** [comment]
Doesn't look like we can do much about that. Mojang has completely removed our ability to define side solidity, it's entirely based on bounding boxes, so it's between
1. Have good looking bounding boxes, don't place levers.
or
2. Have a full cube bounding box and place levers.

@malte0811 That about sums it up, correct?

**Comment by malte0811** [comment]
We could use the same hack as we do for scaffolding, pretend to have a full AABB (or at least one with a solid side) for blocks and the correct one for entities.

**Comment by BluSunrize** [comment]
I thought we couldn't do that properly on scaffolding, or am I misremembering?

**Comment by malte0811** [comment]
I'm quite sure I got it working correctly in the end. I'll look into this when I have the time.
