### ISSUE TITLE
[1.14] Extractor Conveyor Belts forget which direction they extract from.

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#3919]
### Description of the issue:
After configuring an extractor conveyor, it will not persist between game sessions. Upon leaving the game and reloading the world, these extractor will reset to the initial configuration.

### Versions & Modlist
MC Version 1.14.4
Forge Version 28.2.16
IE Version 0.14.97

**Comment by SkySom** [comment]
MC Version? Forge Version? IE Version? We need more info.

**Comment by BluSunrize** [comment]
Use the issue template.

**Comment by BluSunrize** [comment]
working on this now
