### ISSUE TITLE
[1.15.2] Buzzsaw crashing game when breaking tree

### ISSUE THREAD

**Issue by notadevtho** [BluSunrize/ImmersiveEngineering#3923]
### Description of the issue:

When I use the Buzzsaw to chop a tree, I crash as soon as the first block plays the animation of breaking.
"java.lang.IllegalStateException: Already building!"

### Crashlog:

https://pastebin.com/W7ZHBqM6

### Versions & Modlist
(already in the pastebin link)

forge-1.15.2-31.2.8
ImmersiveEngineering-0.15-99
jei-1.15.2-6.0.0.4

**Comment by malte0811** [comment]
Fixed in 3226ec1
