### ISSUE TITLE
[1.14] The mirrored Bottling machine has the conveyors facing the wrong direction

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#3925]
### Description of the issue:
When building the bottling machine, you have to place the conveyors in the direction from input to output of the formed multiblock. But...
One would expect to place the conveyors like in the following picture where the arrows indicate direction of motion of the conveyors:
![2020-06-07_21 43 17](https://user-images.githubusercontent.com/52493793/83995323-033d1000-a951-11ea-8dfd-359139af6ab1.png)
Except that the right-hand mirror won't form when hammered.
The following set up does form, though:
![2020-06-07_21 42 59](https://user-images.githubusercontent.com/52493793/83995394-341d4500-a951-11ea-8205-8e56b5ff01b8.png)
Yet in the final multiblock, the inputs and outputs move as you'd first expect, counter-intuively:
![2020-06-07_21 43 35](https://user-images.githubusercontent.com/52493793/83995436-544d0400-a951-11ea-86de-0361533189c6.png)

### Versions & Modlist
MC Version 1.14.4
Forge Version 28.2.16
IE Version 0.14.97

**Comment by malte0811** [comment]
Fixed in 525e8a956c4ea024abc92171a2f5537d87a96b63. The same will happen for any other multiblock using conveyors, and is fixed for all of them by that commit.
