### ISSUE TITLE
[1.14] Fluids aren't imparting special state effects to the player.

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#3926]
### Description of the issue:
Do you know when getting dowsed by creosote makes the player flammable or if ethanol makes the player drunken? Well, that isn't happening in this version of Immersive Engineering.
This might also affect "concrete feet", but haven't tested.

### Versions & Modlist
MC Version 1.14.4
Forge Version 28.2.16
IE Version 0.14.97

**Comment by BluSunrize** [comment]
Concrete feet is only applied by concrete drying (either from chemthrower or naturally drying). It should not be applied when standing in the fluid.
