### ISSUE TITLE
Issue when going down in creative UI of immersive ingeenering section

### ISSUE THREAD

**Issue by dDevTech** [BluSunrize/ImmersiveEngineering#3928]
-- Head --
Thread: Render thread
Stacktrace:
	at blusunrize.immersiveengineering.client.render.IEOBJItemRenderer.addQuadWithAlpha(IEOBJItemRenderer.java:157)
	at blusunrize.immersiveengineering.client.render.IEOBJItemRenderer.renderQuadsForGroups(IEOBJItemRenderer.java:125)
	at blusunrize.immersiveengineering.client.render.IEOBJItemRenderer.func_228364_a_(IEOBJItemRenderer.java:92)
	at net.minecraft.client.renderer.ItemRenderer.func_229111_a_(ItemRenderer.java:204)
	at net.minecraft.client.renderer.ItemRenderer.func_191962_a(ItemRenderer.java:336)

-- Item being rendered --
Details:
	Item Type: drill
	Registry Name: immersiveengineering:drill
	Item Damage: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.ItemRenderer.func_184391_a(ItemRenderer.java:366)
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_146977_a(ContainerScreen.java:220)
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.render(ContainerScreen.java:91)
	at net.minecraft.client.gui.DisplayEffectsScreen.render(DisplayEffectsScreen.java:45)
	at net.minecraft.client.gui.screen.inventory.CreativeScreen.render(CreativeScreen.java:605)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368)
	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:742)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.screen.inventory.CreativeScreen
	Mouse location: Scaled: (333, 174). Absolute: (1000.000000, 522.000000)
	Screen size: Scaled: (640, 349). Absolute: (1920, 1046). Scale factor of 3.000000

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['pinkidiego'/222, l='MpServer', x=-184.58, y=64.00, z=17.92]]
	Chunk stats: Client Chunks (ImmPtl) 121
	Level dimension: minecraft:overworld
	Level name: MpServer
	Level seed: -8160083078598026153
	Level generator: ID 07 - biomesoplenty, ver 0. Features enabled: false
	Level generator options: {}
	Level spawn location: World: (-192,69,80), Chunk: (at 0,4,0 in -12,5; contains blocks -192,0,80 to -177,255,95), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 1295 game time, 1295 day time
	Known server brands: 
	Level was modded: false
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:611)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:1763)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:567)
	at net.minecraft.client.main.Main.main(SourceFile:204)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5647568288 bytes (5385 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.5.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.5.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.5.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.5.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.15.2_HD_U_G1_pre22.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.5.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.3.jar mixin PLUGINSERVICE 
		/MixinBootstrap-1.0.3.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.5
	FML Language Providers: 
		javafml@31.2
		minecraft@1
		kotlinfml@1.5.2
	Mod List: 
		Kiwi-1.15.2-2.6.5.jar Kiwi {kiwi@2.6.5 DONE}
		HarvestCraft-Mod-Trees-1.15.2.jar Pam's HarvestCraft 2 Fruit Trees {pamhc2trees@version DONE}
		damage_indicator-0.1.0.jar Ama's Damage Indicator {damage_indicator@0.0.9 DONE}
		mining-helmet-1.15.2-1.0.8.jar Mining Helmet {mining_helmet@1.0.8 DONE}
		vanillaexcavators-1.15.1-1.0.jar Vanilla Excavators {vanillaexcavators@1.15.1-1.0 DONE}
		jei-1.15.2-6.0.0.4.jar Just Enough Items {jei@6.0.0.4 DONE}
		Abnormals-Core-1.15.2-v1.0.5.jar Abnormals Core {abnormals_core@1.0.5 DONE}
		extrabows-v1.15.2+b2.jar Extra Bows {extrabows@v1.15.2 b2 DONE}
		Mekanism-1.15.2-9.10.7.420.jar Mekanism {mekanism@9.10.7 DONE}
		Upgrade-Aquatic-1.15.2-v1.6.1.jar Upgrade Aquatic {upgrade_aquatic@1.6.1 DONE}
		music_player-1.15.2-2.0.8.52.jar Music Player {musicplayer@2.0.8.52 DONE}
		invtweaks-1.15.2-1.0.1.jar Inventory Tweaks Reborn {invtweaks@1.15.2-1.0.1 DONE}
		Neat+1.6-22.jar Neat {neat@1.6-22 DONE}
		essentials-1.15.2-2.7.1.jar Essentials {essentials@1.15.2-2.7.1 DONE}
		BetterCaves-1.15.2-1.0.jar YUNG's Better Caves {bettercaves@1.15.2-1.0 DONE}
		TerraForged-1.15.2-0.0.14.jar TerraForged {terraforged@0.0.14 DONE}
		journeymap-1.15.2-5.7.0beta1.jar Journeymap {journeymap@1.15.2-5.7.0beta1 DONE}
		EnhancedVisuals_v1.3.14_mc1.15.2.jar EnhancedVisuals {enhancedvisuals@1.3.0 DONE}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 DONE}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 DONE}
		betteranimalsplus-1.15.2-8.2.1.96.jar Better Animals Plus {betteranimalsplus@8.2.1.96 DONE}
		Bookshelf-1.15.2-5.6.40.jar Bookshelf {bookshelf@5.6.40 DONE}
		u_team_core-1.15.2-2.11.0.156.jar U Team Core {uteamcore@2.11.0.156 DONE}
		Aquatic+Armors-1.1.jar Aquatic Armors {aquaticarmors@1.1 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		WaterStrainer-1.15.2-9.0.0.jar Water Strainer {waterstrainer@1.15.2-9.0.0 DONE}
		immersive-portals-0.20(forMc1.15withForge).jar Immersive Portals {immersive_portals@0.20 DONE}
		gemsplusplus-1.15.2-1.7.2.jar GemsPlusPlus {gemsplusplus@V1.6 DONE}
		forge-1.15.2-31.2.5-universal.jar Forge {forge@31.2.5 DONE}
		graffiti-1.2.1.jar Graffiti {graffiti@1.2.1 DONE}
		forge-1.15.2-31.2.5-client.jar Minecraft {minecraft@1.15.2 DONE}
		useful_backpacks-1.15.2-1.9.0.52.jar Useful Backpacks {usefulbackpacks@1.9.0.52 DONE}
		EnchantmentDescriptions-1.15.2-2.0.8.jar EnchantmentDescriptions {enchdesc@2.0.8 DONE}
		pandoras_creatures-1.15.2-1.0.0.jar Pandoras Creatures {pandoras_creatures@1.15.2-1.0.0 DONE}
		AmbientSounds_v3.0.20_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		ImmersiveEngineering-0.15-99.jar Immersive Engineering {immersiveengineering@0.15-99 DONE}
		BiomesOPlenty-1.15.2-10.0.0.363-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.363 DONE}
		phosphor-forge-mc1.15.2-0.5.2.jar Phosphor {phosphor@0.5.2+build.4 DONE}
		Blur-1.1.0-1.jar Blur {blur@1.1.0-1 DONE}
		HarvestCraft-Mod-Crops-1.15.2.jar Pam's HarvestCraft 2 Crops {pamhc2crops@version DONE}
		CreativeCore_v2.0.5_mc1.15.2.jar CreativeCore {creativecore@2.0.0 DONE}
		simplylight-1.15.2-0.9.0.jar Simply Light {simplylight@1.15.2-0.9.0 DONE}
		Simply+Platinum+-+MC+1.15.2+(1.9.1).jar Simply Platinum {simplyplatinum@1.9.1 DONE}
		GeneticAnimals-0_5_2.jar Genetic Animals {eanimod@0_5_2 DONE}
		usefultools-0.2.0.jar Useful Tools {usefultools@mc1.15.2 v1.0 DONE}
		HarvestCraft-Mod-Food-Core-1.15.2.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
		camera-1.6.9.jar Camera Mod {camera@1.6.9 DONE}
		extlights-2.0.jar Extended Lights {extlights@2.0 DONE}
		[1.15.2]+SecurityCraft+v1.8.18.1.jar SecurityCraft {securitycraft@v1.8.18.1 DONE}
		OreExcavation-1.7.149.jar Ore Excavation {oreexcavation@NONE DONE}
		Performant-Mod-1.15.2.jar Performant {performant@1.7 DONE}
		themidnight-0.5.7-3.jar The Midnight {midnight@0.5.7-3 DONE}
		Hardcore-Revival-Mod-1.15.2.jar Hardcore Revival {hardcorerevival@4.0.0 DONE}
		moarboats-1.15.2-7.0.0.0.jar Moar Boats {moarboats@1.15.2-7.0.0.0 DONE}
		InventoryHud_1.15.1-1.15.2.forge-2.6.1.jar Inventory HUD+(Forge edition) {inventoryhud@2.6.1 DONE}
		tombstone-4.2.0-1.15.1.jar Corail Tombstone {tombstone@4.2.0 DONE}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 DONE}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		engineersdecor-1.15.2-1.0.19-b2.jar Engineer's Decor {engineersdecor@1.0.19-b2 DONE}
		ItemPhysic-Mod-Full-1.15.2.jar ItemPhysic {itemphysic@1.6.0 DONE}
		Aquaculture-1.15.2-2.0.9.jar Aquaculture 2 {aquaculture@1.15.2-2.0.9 DONE}
		incubation-1.0.4-1.15.2.jar Incubation {incubation@1.0.4 DONE}
		SuperTools-1.1_1.15.2.jar Super Tools {supertools@1.1 DONE}
		TrinityWeapons-1.15.2-1.4.1.jar TrinityWeapons {trinity@1.4.1 DONE}
	Kiwi Modules: 
		kiwi:contributors
	Launched Version: 1.15.2-forge-31.2.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.87, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Resource Packs: vanilla, mod_resources, file/dark-modern-guis-16x-1-0-2.zip, file/roboto-bold.zip, file/stratum-128x.zip (incompatible)
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre22
	OptiFine Build: 20200606-224145
	Render Distance Chunks: 5
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: SEUS-Renewed-v1.0.1.zip
	OpenGlVersion: 4.6.0 NVIDIA 445.87
	OpenGlRenderer: GeForce GTX 1070/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by BluSunrize** [comment]
Use the issue template
