### ISSUE TITLE
[1.15.2] When I click my name in the UI of FlameThrower the game crash

### ISSUE THREAD

**Issue by dDevTech** [BluSunrize/ImmersiveEngineering#3930]
### Description of the issue:
When I click my name in the UI of FlameThrower the game crashcloses
### Crashlog:
https://pastebin.com/3vjRp6SB

### Versions & Modlist
	kotlinfml@1.5.2
	Mod List: 
		Kiwi-1.15.2-2.6.5.jar Kiwi {kiwi@2.6.5 DONE}
		HarvestCraft-Mod-Trees-1.15.2.jar Pam's HarvestCraft 2 Fruit Trees {pamhc2trees@version DONE}
		damage_indicator-0.1.0.jar Ama's Damage Indicator {damage_indicator@0.0.9 DONE}
		mining-helmet-1.15.2-1.0.8.jar Mining Helmet {mining_helmet@1.0.8 DONE}
		vanillaexcavators-1.15.1-1.0.jar Vanilla Excavators {vanillaexcavators@1.15.1-1.0 DONE}
		jei-1.15.2-6.0.0.4.jar Just Enough Items {jei@6.0.0.4 DONE}
		Abnormals-Core-1.15.2-v1.0.5.jar Abnormals Core {abnormals_core@1.0.5 DONE}
		extrabows-v1.15.2+b2.jar Extra Bows {extrabows@v1.15.2 b2 DONE}
		Mekanism-1.15.2-9.10.7.420.jar Mekanism {mekanism@9.10.7 DONE}
		Upgrade-Aquatic-1.15.2-v1.6.1.jar Upgrade Aquatic {upgrade_aquatic@1.6.1 DONE}
		music_player-1.15.2-2.0.8.52.jar Music Player {musicplayer@2.0.8.52 DONE}
		invtweaks-1.15.2-1.0.1.jar Inventory Tweaks Reborn {invtweaks@1.15.2-1.0.1 DONE}
		Neat+1.6-22.jar Neat {neat@1.6-22 DONE}
		essentials-1.15.2-2.7.1.jar Essentials {essentials@1.15.2-2.7.1 DONE}
		BetterCaves-1.15.2-1.0.jar YUNG's Better Caves {bettercaves@1.15.2-1.0 DONE}
		TerraForged-1.15.2-0.0.14.jar TerraForged {terraforged@0.0.14 DONE}
		journeymap-1.15.2-5.7.0beta1.jar Journeymap {journeymap@1.15.2-5.7.0beta1 DONE}
		EnhancedVisuals_v1.3.14_mc1.15.2.jar EnhancedVisuals {enhancedvisuals@1.3.0 DONE}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 DONE}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 DONE}
		betteranimalsplus-1.15.2-8.2.1.96.jar Better Animals Plus {betteranimalsplus@8.2.1.96 DONE}
		Bookshelf-1.15.2-5.6.40.jar Bookshelf {bookshelf@5.6.40 DONE}
		u_team_core-1.15.2-2.11.0.156.jar U Team Core {uteamcore@2.11.0.156 DONE}
		Aquatic+Armors-1.1.jar Aquatic Armors {aquaticarmors@1.1 DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		WaterStrainer-1.15.2-9.0.0.jar Water Strainer {waterstrainer@1.15.2-9.0.0 DONE}
		immersive-portals-0.20(forMc1.15withForge).jar Immersive Portals {immersive_portals@0.20 DONE}
		gemsplusplus-1.15.2-1.7.2.jar GemsPlusPlus {gemsplusplus@V1.6 DONE}
		forge-1.15.2-31.2.5-universal.jar Forge {forge@31.2.5 DONE}
		graffiti-1.2.1.jar Graffiti {graffiti@1.2.1 DONE}
		forge-1.15.2-31.2.5-client.jar Minecraft {minecraft@1.15.2 DONE}
		useful_backpacks-1.15.2-1.9.0.52.jar Useful Backpacks {usefulbackpacks@1.9.0.52 DONE}
		EnchantmentDescriptions-1.15.2-2.0.8.jar EnchantmentDescriptions {enchdesc@2.0.8 DONE}
		pandoras_creatures-1.15.2-1.0.0.jar Pandoras Creatures {pandoras_creatures@1.15.2-1.0.0 DONE}
		AmbientSounds_v3.0.20_mc1.15.2.jar Ambient Sounds {ambientsounds@3.0.3 DONE}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		ImmersiveEngineering-0.15-99.jar Immersive Engineering {immersiveengineering@0.15-99 DONE}
		BiomesOPlenty-1.15.2-10.0.0.363-universal.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.363 DONE}
		phosphor-forge-mc1.15.2-0.5.2.jar Phosphor {phosphor@0.5.2+build.4 DONE}
		Blur-1.1.0-1.jar Blur {blur@1.1.0-1 DONE}
		HarvestCraft-Mod-Crops-1.15.2.jar Pam's HarvestCraft 2 Crops {pamhc2crops@version DONE}
		CreativeCore_v2.0.5_mc1.15.2.jar CreativeCore {creativecore@2.0.0 DONE}
		simplylight-1.15.2-0.9.0.jar Simply Light {simplylight@1.15.2-0.9.0 DONE}
		Simply+Platinum+-+MC+1.15.2+(1.9.1).jar Simply Platinum {simplyplatinum@1.9.1 DONE}
		GeneticAnimals-0_5_2.jar Genetic Animals {eanimod@0_5_2 DONE}
		usefultools-0.2.0.jar Useful Tools {usefultools@mc1.15.2 v1.0 DONE}
		HarvestCraft-Mod-Food-Core-1.15.2.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
		camera-1.6.9.jar Camera Mod {camera@1.6.9 DONE}
		extlights-2.0.jar Extended Lights {extlights@2.0 DONE}
		[1.15.2]+SecurityCraft+v1.8.18.1.jar SecurityCraft {securitycraft@v1.8.18.1 DONE}
		OreExcavation-1.7.149.jar Ore Excavation {oreexcavation@NONE DONE}
		Performant-Mod-1.15.2.jar Performant {performant@1.7 DONE}
		themidnight-0.5.7-3.jar The Midnight {midnight@0.5.7-3 DONE}
		Hardcore-Revival-Mod-1.15.2.jar Hardcore Revival {hardcorerevival@4.0.0 DONE}
		moarboats-1.15.2-7.0.0.0.jar Moar Boats {moarboats@1.15.2-7.0.0.0 DONE}
		InventoryHud_1.15.1-1.15.2.forge-2.6.1.jar Inventory HUD+(Forge edition) {inventoryhud@2.6.1 DONE}
		tombstone-4.2.0-1.15.1.jar Corail Tombstone {tombstone@4.2.0 DONE}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 DONE}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 DONE}
		AppleSkin-mc1.15.2-forge-1.0.13.jar AppleSkin {appleskin@1.0.13 DONE}
		engineersdecor-1.15.2-1.0.19-b2.jar Engineer's Decor {engineersdecor@1.0.19-b2 DONE}
		ItemPhysic-Mod-Full-1.15.2.jar ItemPhysic {itemphysic@1.6.0 DONE}
		Aquaculture-1.15.2-2.0.9.jar Aquaculture 2 {aquaculture@1.15.2-2.0.9 DONE}
		incubation-1.0.4-1.15.2.jar Incubation {incubation@1.0.4 DONE}
		SuperTools-1.1_1.15.2.jar Super Tools {supertools@1.1 DONE}
		TrinityWeapons-1.15.2-1.4.1.jar TrinityWeapons {trinity@1.4.1 DONE}

**Comment by BluSunrize** [comment]
Should be fixed by https://github.com/BluSunrize/ImmersiveEngineering/commit/74b3c765d5758bf22dc47931c68361fd7abe0c19
