### ISSUE TITLE
[1.15.2] Adding blueprint to engineer's Workbench causes crash that stops world loading

### ISSUE THREAD

**Issue by StephenNorris** [BluSunrize/ImmersiveEngineering#3931]
### Description of the issue:
I added a blueprint to the workbench and was kicked. Now the world will not load any more.

### Crashlog:
https://gist.github.com/StephenNorris/9b2c35d91b79305614b388047ad5db6e

### Versions & Modlist
See crash log.

I can't reload the world to test without other mods.

**Comment by malte0811** [comment]
Duplicate of #3908
