### ISSUE TITLE
[1.15.2] Failed to load registry, closing connection.

### ISSUE THREAD

**Issue by Goatle** [BluSunrize/ImmersiveEngineering#3939]
### Description of the issue:
One of my friends receive an error when attempting to connect to my server. "Failed to load registry, closing connection" (from the log) .  Myself and another friend do not. It prevents him from loading in. The easiest way resolve this was remove the mod itself for the time being. Playing All the Mods 5 with some additions.

### Crashlog:
No crash, but relevant portion of my friend's client log can be found [here](https://gist.github.com/Goatle/592c706a8d6d8cc871c69ba6399d8aa0).

The server did not contain any additional information.

### Versions & Modlist
Forge: 31.2.9

Immersive Engineering: 0.12-98

[Modlist](https://gist.github.com/Goatle/d6cf9e32d7a55756a6b85548cd71d16c)

Did not do any compat. tests for the issue as I am not able to replicate it.

### Additional Comments

All configs between the client and server are the same. All three of us installed the exact same way. I'm a little dumbfounded.

Listed this as an issue in the ATM5 Github as well. [Issue #152](https://github.com/AllTheMods/ATM-5/issues/152)

**Comment by mindforger** [comment]
You say it has been installed in an similar fashion (how? Twitch? Technic? Manually?) But it still looks like different mod versions

**Comment by malte0811** [comment]
This looks like the issue I described in https://github.com/BluSunrize/ImmersiveEngineering/issues/3878#issuecomment-633566975. It would be great if you could open an issue with Industrial Foregoing for that, with a link to my comment (otherwise I'll do it when I get around to it).

I still think we should change how we register the shader bags though. Maybe have an API method to request a bag for a given rarity during mod construction? Opinions @BluSunrize?

**Comment by Goatle** [comment]
> You say it has been installed in an similar fashion (how? Twitch? Technic? Manually?) But it still looks like different mod versions

Apologies. I manually zipped the config, global_data_pack, mods, and scripts folder and sent it over to my two friends. I am able to connect with the files. One of the other people is able to connect with the files, but the other is not. I am going to confirm with him once I am able to reach out that he is fully deleting the files and replacing with my copies. ( I believe this to be the case.)

Going to look through my logs to get one matching the one he sent me and I will upload those as well.



> This looks like the issue I described in [#3878 (comment)](https://github.com/BluSunrize/ImmersiveEngineering/issues/3878#issuecomment-633566975). It would be great if you could open an issue with Industrial Foregoing for that, with a link to my comment (otherwise I'll do it when I get around to it).
> 
> I still think we should change how we register the shader bags though. Maybe have an API method to request a bag for a given rarity during mod construction? Opinions @BluSunrize?


I would but I don't see anything super relevant to them that I could advise them with in my logs.

**Comment by Goatle** [comment]
[Server Log](https://gist.github.com/Goatle/988e4b5a0b350fb109b7d4858ba39ad9)

[Client Log](https://gist.github.com/Goatle/8d4ed51531665b313fae0d1f3a0a9ed5)

Edit: When I uploaded these last night originally I had duplicated the server log. This is now fixed.

**Comment by brucethemoose** [comment]
I have this issue as well: https://paste.ee/p/TUzM4
