### ISSUE TITLE
[1.12] CPU spikes caused by Assembler in a 9 chunk radius. 

### ISSUE THREAD

**Issue by PeterBaker644** [BluSunrize/ImmersiveEngineering#3941]
[1.12] CPU spikes caused by Assembler in a 9 chunk radius. 

### Description of the issue:
Issue occurs in a e2e server instance. Travelling into a border 9 chunks in radius around the assembler multiblock causes the game to seize for a second. After breaking the multiblock structure the lag spike goes away. 

### Versions & Modlist
ImmersiveEngineering-0.12-92.jar
forge-14.23.5.2847
Enigmatica 2 Expert 1.80

![2020-06-09 screenshot](https://user-images.githubusercontent.com/61387901/84176816-9b1d2580-aa47-11ea-8bc5-566c2d51ed9a.png)

**Comment by BluSunrize** [comment]
Support for 1.12 has ceased, we are no longer maintaining that version.
