### ISSUE TITLE
[1.15] Crash when putting Blueprint into Engineer's workbench.

### ISSUE THREAD

**Issue by Keb911** [BluSunrize/ImmersiveEngineering#3942]
I've seen that this was already reported and fixed a few days ago, but I'm still crashing when I put the crafting components blueprint into the engineer's workbench. 

Crashlog:
https://pastebin.com/P1r1KdsQ

Versions & Modlist
IE Version: ImmersiveEngineering-0.15-99
Forge Version: 31.2.9
JEI 6.0.0.4
Tested in new world, with only jei and ie, still crashes.

**Comment by BluSunrize** [comment]
If you already knew it was reported and fixed, then you needn't have opened a new issue. The new version isn't out yet, so *obviously* you are still going to experience the crash.
Opening more issues does not increase the speed at which we release.
