### ISSUE TITLE
[1.12.2] Wire connections stop working after chunk unload

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [BluSunrize/ImmersiveEngineering#3943]
### Description of the issue:
I am using this mod on my server and one of players reported to me that after updating from 0.12-92 to 0.12-98 wire connections stopped transferring power and needed to be created again to work again. Same when unloading chunks and loading them again.

### Versions & Modlist
Forge version: 14.23.5.2854
IE version: 0.12-98
[Full mod list](https://pastebin.com/fxEPcHrQ)

**Comment by ErnestoPeroPezzi** [comment]
I am having this same issue for 1.12

**Comment by BluSunrize** [comment]
1.12 is no longer supported
