### ISSUE TITLE
[1.15.2] Garden Cloche does not interact with Mystical Agriculture as per expectation

### ISSUE THREAD

**Issue by Sagesheep** [BluSunrize/ImmersiveEngineering#3944]
# Description of the issue:
MA Seed does not grow as per expectation in garden cloche

How to reproduce
1. Insert MA seed into garden cloche

### Versions & Modlist
IE 0.15-99
Forge 31.2.9
Atm5 5.2

**Comment by BluSunrize** [comment]
Okay, add your own recipes? Everything is JSON based.

**Comment by j4n3k2212** [comment]
the question here is, why isnt it a added recipe in general. i have no idea how to add a recipe and where to put it for the cloche to work with MA seeds. doesnt really make sense in my mind, maybe i dont see any issue or something that u found, pls let me know :) problem for me is i love to play modpacks but i dont see the point in investing 5 hours to change every setting and recipe before playing, does make me just wanna stop playing tbh

**Comment by mindforger** [comment]
What would you pay if i wrote it for you?

**Comment by j4n3k2212** [comment]
pff xD surely paying for that, ill rather look into it myself or find another way. if u have any good tutorials for it tho hmu
