### ISSUE TITLE
[1.15.2] Redstone Probe and Interface Connectors Not Rendering

### ISSUE THREAD

**Issue by DeadlySwede** [BluSunrize/ImmersiveEngineering#3945]
Possibly a duplicate of what Skyboy444 was trying to report. No crashes here though. Also not using Optifine. Just noticed that a couple items are not rendering, specifically the redstone probe connector and the redstone interface connector. 

Linked screenshots shows items rendered in beta 0.14-97 and not rendered in alpha 0.15-99.

[Rendered - beta 0.14-97](https://imgur.com/zR3clb8)
[Not Rendered - alpha 0.15-99](https://imgur.com/zjLGwmI)

Minecraft 1.15.2
Forge 31.2.9
Immersive Engineering 0.15-99

**Comment by DeadlySwede** [comment]
Also tried reloading world and placing blocks to force chunk update. Still won't render. Added link to contents of "latest.log" file but nothing that looks of any interest.

[latest.log](https://pastebin.com/cBgRLvbv)

**Comment by malte0811** [comment]
Fixed in cdec6d0
