### ISSUE TITLE
[1.15.2] Crashed when typing b into jei

### ISSUE THREAD

**Issue by IchigoGames** [BluSunrize/ImmersiveEngineering#3947]
### Description of the issue:
i type b in jei was trying to make rftools builder and crashed looked at crash report and saw it was from ImmersiveEngineering

### Crashlog:
https://pastebin.com/0ErpkjZm edit posted wrong crash report before this is the one i meant to post

### Versions & Modlist
ImmersiveEngineering-0.15-99
jei-1.15.2-6.0.0.4
Minecraft 1.15.2
Forge 31.2.0
https://www.curseforge.com/minecraft/modpacks/the-endless-frontier 3.5

**Comment by malte0811** [comment]
> looked at crash report and saw it was from ImmersiveEngineering

Is it possible that you uploaded the wrong crash report? This one may be caused by IE, I have no idea, but there isn't anything in there to suggest it's IE's fault any more than it's e.g. SimpleStorageNetwork's fault. IE only appears in the mod list part of the crash.

**Comment by IchigoGames** [comment]
your  right i did sorry about that ^ fixed now

**Comment by malte0811** [comment]
Now I get
> This page is no longer available. It has either expired, been removed by its creator, or removed by one of the Pastebin staff.

when trying to access the crashlog.

**Comment by IchigoGames** [comment]
https://pastebin.com/c9yW7jB6

**Comment by malte0811** [comment]
This was fixed for the next release in #3938. For now the only workaround is removing OF, or (I may be wrong here) disabling shaders in OF.
