### ISSUE TITLE
[1.14.4] Crash "Invalid mineral mix: Pyrite" more i do not know

### ISSUE THREAD

**Issue by TwistedGate** [BluSunrize/ImmersiveEngineering#3950]
### Description of the issue:
Went from IE-95 to IE-97, loaded my world and got an insta-crash.

### Crashlog:
[Gist](https://gist.github.com/TwistedGate/ab480997205e4a3d94847f14a7955064)

### Versions & Modlist
**Copy Paste from Crash above!**
forge-1.14.4-28.2.18-client.jar Minecraft {minecraft@1.14.4 DONE}
theoneprobe-1.14-1.4.37.jar The One Probe {theoneprobe@NONE DONE}
MouseTweaks-2.13-mc1.14.4.jar Mouse Tweaks {mousetweaks@2.13 DONE}
ImmersiveEngineering-0.14-97.jar Immersive Engineering {immersiveengineering@0.14-97 DONE}
engineersdecor-1.14.4-1.0.20-b4.jar Engineer's Decor {engineersdecor@1.0.20-b4 DONE}
moreoverlays-1.16.1.jar More Overlays {moreoverlays@1.16.1 DONE}
jei-1.14.4-6.0.0.27.jar Just Enough Items {jei@6.0.0.27 DONE}
forge-1.14.4-28.2.18-universal.jar Forge {forge@28.2.18 DONE}
rsgauges-1.14.4-1.2.2.jar Gauges and Switches {rsgauges@1.2.2 DONE}
FastLeafDecay-v17.jar FastLeafDecay {fastleafdecay@v17 DONE}
create-mc1.14.4_v0.2.2b.jar Create {create@mc1.14-0.2.2b DONE}
immersiveposts-1.14.4-1.1.0.jar Immersive Posts {immersiveposts@1.1.0 DONE}
journeymap-1.14.4-5.7.0b1.jar Journeymap {journeymap@1.14.4-5.7.0b1 DONE}
minecoprocessors-1.14.4-1.0.5.jar Minecoprocessors {minecoprocessors@1.0.5 DONE}
OreExcavation-1.6.147.jar Ore Excavation {oreexcavation@NONE DONE}

**Comment by BluSunrize** [comment]
hmm, yeah, mineral veins changed.

**Comment by BluSunrize** [comment]
we might need a safeguard on that rendering

**Comment by TwistedGate** [comment]
Guess i'll nuke the placed samples around my base, or do you think that wouldnt make no difference

**Comment by TwistedGate** [comment]
Would it make sense if i uploaded my world for you guys to play around with? Because of it crashing the game when trying to load it.

**Comment by malte0811** [comment]
Not really. It's quite clear what's crashing, and we know why (vein names changed, and while existing veins just get removed the core samples have more trouble), we just haven't gotten around to fixing it.

**Comment by TwistedGate** [comment]
Okay, just making sure :)
