### ISSUE TITLE
[1.15.2] Industrial Hemp Seeds doesn't appear to drop from grass at all.

### ISSUE THREAD

**Issue by Gbergz** [BluSunrize/ImmersiveEngineering#3953]
### Description of the issue:
As the title says, Industrial Hemp Seeds doesn't appear to drop from grass/tallgrass at all.

### Versions
IE: 0.15-99
Forge: 31.2.9
MC: 1.15.2

Modlist: https://gist.github.com/Gbergz/6e5b42e461a548df8c8b57ab775c76af

Hope it can get fixed. :)

**Comment by malte0811** [comment]
It works fine for me. Does this happen with just IE? If it doesn't, try using a binary search to find the mod causing issues:
1. Remove half of your mods (not IE, try to not break dependencies)
2. Test if it works without that half
2.1. If it works, try again with the other half to make sure it's just one mod causing issues and not a larger conflict
3. Repeat from step 1 with the half of the mods that still had the issue

That should give you a result relatively quickly (roughly 8 iterations for your set of mods).

**Comment by Gbergz** [comment]
Appears this was an issue with an existing world that didn't have IE beforehand.
Created a new world and it dropped the seed again.

**Comment by Gnomeknows** [comment]
In all my worlds in 15.2 I find it impossible to find hemp naturally.  Strangely though, after I cheated in a single seed, I then started to find hemp from grass prolifically.  I am spending some time now to prune my mod list carefully and find out if there is actually one conflicting but I don't think this issue belongs closed right now.  I'm on forge 32.2.30, IE .15.103.

**Comment by BluSunrize** [comment]
The issue is closed, and you are using an outdated version of IE.
