### ISSUE TITLE
[1.15.2] Hemp plant textures completely opaque

### ISSUE THREAD

**Issue by Zekrom64** [BluSunrize/ImmersiveEngineering#3955]
### Description of the issue:
Hemp plants render with opaque textures, with white areas where transparency should be.
![2020-06-11_18 16 08](https://user-images.githubusercontent.com/13003285/84449306-a1abc880-ac12-11ea-90fb-7bc4dc577d23.jpg)

### Crashlog:
N/A

### Versions & Modlist
Forge: 31.2.9
IE: 0.15-99

**Comment by BluSunrize** [comment]
Please produce a debug crash by holding F3+C, put it on pastebin and link it here.

**Comment by malte0811** [comment]
Fixed in cf5dc1b
