### ISSUE TITLE
[1.15.2] Feedthrough Insulators not Rendering

### ISSUE THREAD

**Issue by calasmo** [BluSunrize/ImmersiveEngineering#3958]
### Description of the issue:
Placing a connector on either side of a block should create a feedthrough insulator as described in the documentation. While a feedthrough insulator is effectively created after right-clicking, the models for the connectors vanish and the wires originally connected to them hover in the air.

Below is this bug demonstrated on LV, MW, and HV feedthrough setups recreated after being experienced on a server world with a few extra mods running.

![2020-06-11_19 40 51](https://user-images.githubusercontent.com/66807603/84456154-85148e00-ac1c-11ea-8cb2-9f7e1db78be5.png)

This recreation was made on a creative, singleplayer world without additional mods.

### Versions & Modlist
IE Version: 0.15-99
Forge Version: 1.15.2-forge-31.2.0

**Comment by calasmo** [comment]
Possibly a duplicate of #3945 -- I did not see feedthroughs mentioned there.

**Comment by malte0811** [comment]
Fixed in 5425861
