### ISSUE TITLE
[1.15] mining drill render crash when attempting to mine

### ISSUE THREAD

**Issue by coalman321** [BluSunrize/ImmersiveEngineering#3959]
### Description of the issue:
When attempting to use the mining drill on stone materials the client viewing the block being damaged will crash. Currently only known to occur on ~~smooth stone and regular andesite~~ 
 underground blocks. this bug does not effect the server instance as the issue seems rendering based. This behavior was observed with the steel drill head.

### Crashlog:
https://gist.github.com/coalman321/ec32fe86f3532513aefd2cddd19e5553

### Versions & Modlist
                forge-1.15.2-31.2.8-client.jar Minecraft {minecraft@1.15.2 DONE}
		tombstone-4.4.0-1.15.2.jar Corail Tombstone {tombstone@4.4.0 DONE}
		ImmersiveEngineering-0.15-99.jar Immersive Engineering {immersiveengineering@0.15-99 DONE}
		buildinggadgets-3.3.5.jar Building Gadgets {buildinggadgets@3.3.5 DONE}
		refinedpipes-0.4.2.jar Refined Pipes {refinedpipes@0.4.2 DONE}
		jei-1.15.2-6.0.0.4.jar Just Enough Items {jei@6.0.0.4 DONE}
		forge-1.15.2-31.2.8-universal.jar Forge {forge@31.2.8 DONE}
		Psi r1.2-82.jar Psi {psi@r1.2-80 DONE}
		FastLeafDecay-v22.jar FastLeafDecay {fastleafdecay@v22 DONE}
		curios-FORGE-1.15.2-2.0.2.4.jar Curios API {curios@FORGE-1.15.2-2.0.2.4 DONE}
		Botania-r1.15-384.jar Botania {botania@r1.15-384 DONE}
		Patchouli-1.15.2-1.2-33.jar Patchouli {patchouli@1.15.2-1.2-33 DONE}
		create-mc1.15.2_v0.2.4a.jar Create {create@mc1.15.2_v0.2.4a+custom DONE}
		refinedstorage-1.8.4.jar Refined Storage {refinedstorage@1.8.4 DONE}
		journeymap-1.15.2-5.7.0b2.jar Journeymap {journeymap@5.7.0b2 DONE}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 DONE}
		CookingForBlockheads_1.15.2-8.0.2.jar Cooking for Blockheads {cookingforblockheads@8.0.2 DONE}

**Comment by malte0811** [comment]
Fixed in dc6cac1
