### ISSUE TITLE
[1.14] Turrets are broken when they don't cause a crash

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#3963]
## Description of the issue:
The Turrets (both gun and chemical) don't seem to work at all. Upon opening the GUI, it's possible to charge them with energy and ammunition, but they won't aim or shoot target. Not when they are selected in the checkboxes, nor when added to the targeting list. Tested with the player, chickens, llamas, bears, sheep, zombies, skeletons and slime monsters. (possibly fixed at the time of this post?)

Also, when adding a name to the targeting list it isn't possible to remove or edit it, as it will crash Minecraft.
### Crashlog:
[gist](https://gist.github.com/Codified-Vexing/bf4f9af008824be23fcf79836613d5a4)

### Versions & Modlist
MC Version 1.14.4
Forge Version 28.2.16
IE Version 0.14.97

**Comment by BluSunrize** [comment]
I literally told you you only needed to report the crash because I already fixed the lack of functionality .-.
