### ISSUE TITLE
[Suggestion] Make Razor Wire electrification more obvious

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#3965]
It's kinda hard to tell if the Razor Wire is electrified. I suggest that some "spark" particle effect be added, and that touching it causes "stunned" effect.

**Comment by BluSunrize** [comment]
Unable to reproduce this, razor wires are absolutely being eletrified. They do more damage and have a different death message.

**Comment by ethanhile** [comment]
Maybe you could give the Razor wire an enchanted glow.
