### ISSUE TITLE
Concrete Recipe Consumes the Bucket

### ISSUE THREAD

**Issue by TooManyKitKats** [BluSunrize/ImmersiveEngineering#3969]
### Before reporting:
I checked for any other duplicates of this issue, I didn't see any so apologies if I missed it.
### Description of the issue:
When crafting concrete in the latest jenkins build ( this is on the community server) the bucket is consumed.
### Versions & Modlist

ImmersiveEngineering-0.15-101-54258617
Quark
Transport
Titanium
Autoreglib
JEI

**Comment by BluSunrize** [comment]
Reproducable in 1.14, working on this now
