### ISSUE TITLE
Phial Cartridge's texture (or recipe) issue

### ISSUE THREAD

**Issue by bakaxyf** [BluSunrize/ImmersiveEngineering#397]
![h5f2 i1 rx c3mxwdnikj](https://cloud.githubusercontent.com/assets/10368307/9697683/c2b378b2-53c9-11e5-8de2-cc94fd5c5a72.png)
![8tjdnz74 uy57nnj yx c](https://cloud.githubusercontent.com/assets/10368307/9697684/c527d99e-53c9-11e5-9898-1fe4f9fa9893.png)

**Comment by theunkn0wn1** [comment]
hah. that sure is an inconsistency. The crafting output shows it as a bullet that goes in the revolver though it is crafted with a shotgun shell.

**Comment by BluSunrize** [comment]
Well, shotgun shells also go into the revolver. IF you look at Wolfpack, it's neither shell or casing. The texture is not a 100% indication for the items used, but in this case you are correct, I intended it to be casing rather than shell.
