### ISSUE TITLE
1.15.2 Compiling Trouble

### ISSUE THREAD

**Issue by PyroFlareX** [BluSunrize/ImmersiveEngineering#3970]
How to compile the mod? I tried to do so with ```gradlew build``` and with IntelliJ, but errors keep popping up. This is for 1.15.2 by the way. The complete log is below, but this part stood out to me:
```
Error:(15, 30) java: cannot find symbol
  symbol:   class SpecialManualElement
  location: class blusunrize.lib.manual.TextSplitterTest
```
I am a sufferer of the already documented Engineers Table Rendering crash, and saw on the issues that it had been fixed, and wanted to get the fix as it has not been released as an update on CurseForge yet.

(Apologies, IDK how to do spoilers).

Log:

> Information:java: Errors occurred while compiling module 'ImmersiveEngineering.test'
Information:javac 1.8.0_212 was used to compile java sources
Information:Modules "ImmersiveEngineering.main", "ImmersiveEngineering.test" were fully rebuilt due to project configuration/dependencies changes
Information:6/12/2020 11:55 PM - Build completed with 100 errors and 0 warnings in 7 s 442 ms
B:\ProgrammingProj\ImmersiveEngineering\src\test\java\blusunrize\lib\manual\TextSplitterTest.java
Error:(3, 33) java: package blusunrize.lib.manual.gui does not exist
Error:(4, 46) java: package net.minecraft.client.gui.widget.button does not exist
Error:(15, 30) java: cannot find symbol
  symbol:   class SpecialManualElement
  location: class blusunrize.lib.manual.TextSplitterTest
Error:(16, 30) java: cannot find symbol
  symbol:   class SpecialManualElement
  location: class blusunrize.lib.manual.TextSplitterTest
Error:(17, 17) java: cannot find symbol
  symbol:   class TextSplitter
  location: class blusunrize.lib.manual.TextSplitterTest
Error:(39, 48) java: cannot find symbol
  symbol:   class SpecialManualElement
  location: class blusunrize.lib.manual.TextSplitterTest
Error:(112, 51) java: cannot find symbol
  symbol:   class SpecialManualElement
  location: class blusunrize.lib.manual.TextSplitterTest
Error:(128, 38) java: cannot find symbol
  symbol:   class ManualScreen
  location: class blusunrize.lib.manual.TextSplitterTest.DummyElement
Error:(128, 75) java: cannot find symbol
  symbol:   class Button
  location: class blusunrize.lib.manual.TextSplitterTest.DummyElement
Error:(133, 36) java: cannot find symbol
  symbol:   class ManualScreen
  location: class blusunrize.lib.manual.TextSplitterTest.DummyElement
Error:(22, 32) java: cannot find symbol
  symbol:   class TextSplitter
  location: class blusunrize.lib.manual.TextSplitterTest
Error:(121, 17) java: method does not override or implement a method from a supertype
Error:(127, 17) java: method does not override or implement a method from a supertype
Error:(132, 17) java: method does not override or implement a method from a supertype
Error:(137, 17) java: method does not override or implement a method from a supertype
Error:(142, 17) java: method does not override or implement a method from a supertype
Error:(148, 17) java: method does not override or implement a method from a supertype
B:\ProgrammingProj\ImmersiveEngineering\src\test\java\blusunrize\immersiveengineering\api\wires\utils\CatenaryTracerTest.java
Error:(11, 43) java: cannot find symbol
  symbol:   class ApiUtils
  location: package blusunrize.immersiveengineering.api
Error:(12, 49) java: cannot find symbol
  symbol:   class Connection
  location: package blusunrize.immersiveengineering.api.wires
Error:(13, 49) java: cannot find symbol
  symbol:   class ConnectionPoint
  location: package blusunrize.immersiveengineering.api.wires
Error:(14, 49) java: cannot find symbol
  symbol:   class WireType
  location: package blusunrize.immersiveengineering.api.wires
Error:(15, 33) java: package com.google.common.collect does not exist
Error:(16, 33) java: package com.google.common.collect does not exist
Error:(17, 37) java: package it.unimi.dsi.fastutil.doubles does not exist
Error:(18, 37) java: package it.unimi.dsi.fastutil.objects does not exist
Error:(19, 37) java: package it.unimi.dsi.fastutil.objects does not exist
Error:(20, 45) java: package net.minecraft.client.renderer.texture does not exist
Error:(21, 26) java: package net.minecraft.item does not exist
Error:(22, 31) java: package net.minecraft.util.math does not exist
Error:(23, 31) java: package net.minecraft.util.math does not exist
Error:(24, 31) java: package net.minecraft.util.math does not exist
Error:(37, 30) java: cannot find symbol
  symbol:   class BlockPos
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(39, 47) java: cannot find symbol
  symbol:   class Vec3d
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(39, 60) java: cannot find symbol
  symbol:   class Vec3d
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(120, 44) java: cannot find symbol
  symbol:   class Vec3d
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(120, 74) java: cannot find symbol
  symbol:   class BlockPos
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(148, 39) java: cannot find symbol
  symbol:   class Vec3d
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(148, 52) java: cannot find symbol
  symbol:   class Vec3d
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(148, 17) java: cannot find symbol
  symbol:   class CatenaryTracer
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(159, 51) java: cannot find symbol
  symbol:   class WireType
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(175, 38) java: cannot find symbol
  symbol:   class Connection
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest.TestWiretype
Error:(187, 51) java: cannot find symbol
  symbol:   class Connection
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest.TestWiretype
Error:(187, 24) java: cannot find symbol
  symbol:   class TextureAtlasSprite
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest.TestWiretype
Error:(199, 46) java: cannot find symbol
  symbol:   class Connection
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest.TestWiretype
Error:(199, 24) java: cannot find symbol
  symbol:   class ItemStack
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest.TestWiretype
Error:(37, 52) java: cannot find symbol
  symbol:   class BlockPos
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(41, 17) java: cannot find symbol
  symbol:   class CatenaryTracer
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(43, 34) java: cannot find symbol
  symbol:   class DoubleAVLTreeSet
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(49, 46) java: cannot find symbol
  symbol:   class Vec3d
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(49, 70) java: cannot find symbol
  symbol:   class Vec3d
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(51, 46) java: cannot find symbol
  symbol:   class Vec3d
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(51, 71) java: cannot find symbol
  symbol:   class Vec3d
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(53, 46) java: cannot find symbol
  symbol:   class Vec3d
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(53, 73) java: cannot find symbol
  symbol:   class Vec3d
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(55, 17) java: cannot find symbol
  symbol:   class CatenaryTracer
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(55, 48) java: cannot find symbol
  symbol:   class Vec3d
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(55, 75) java: cannot find symbol
  symbol:   class Vec3d
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(67, 41) java: cannot find symbol
  symbol:   class Vec3d
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(67, 73) java: cannot find symbol
  symbol:   class Vec3d
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(80, 25) java: cannot find symbol
  symbol:   class CatenaryTracer
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(80, 56) java: cannot find symbol
  symbol:   class Vec3d
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(80, 85) java: cannot find symbol
  symbol:   class Vec3d
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(84, 51) java: cannot find symbol
  symbol:   class Vec3d
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(84, 37) java: cannot find symbol
  symbol:   class Vec3d
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(89, 62) java: cannot find symbol
  symbol:   variable ApiUtils
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(90, 69) java: cannot find symbol
  symbol:   variable MathHelper
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(100, 25) java: cannot find symbol
  symbol:   class Object2IntMap
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(100, 39) java: cannot find symbol
  symbol:   class BlockPos
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(100, 64) java: cannot find symbol
  symbol:   class Object2IntOpenHashMap
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(101, 25) java: cannot find symbol
  symbol:   class CatenaryTracer
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(101, 56) java: cannot find symbol
  symbol:   class Vec3d
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(101, 82) java: cannot find symbol
  symbol:   class Vec3d
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(104, 35) java: illegal start of type
Error:(107, 29) java: cannot find symbol
  symbol:   class BlockPos
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(108, 41) java: cannot find symbol
  symbol:   variable BlockPos
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(109, 45) java: cannot find symbol
  symbol:   class BlockPos
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(110, 45) java: cannot find symbol
  symbol:   class BlockPos
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(111, 45) java: cannot find symbol
  symbol:   class BlockPos
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(107, 63) java: cannot find symbol
  symbol:   variable ImmutableMap
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(113, 25) java: cannot find symbol
  symbol:   class Object2IntMap
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(113, 39) java: cannot find symbol
  symbol:   class BlockPos
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(113, 64) java: cannot find symbol
  symbol:   class Object2IntOpenHashMap
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(114, 35) java: cannot find symbol
  symbol:   class BlockPos
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(122, 17) java: cannot find symbol
  symbol:   class CatenaryTracer
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(122, 44) java: cannot find symbol
  symbol:   variable Vec3d
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(122, 60) java: cannot find symbol
  symbol:   class Vec3d
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(123, 21) java: cannot find symbol
  symbol:   class BlockPos
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(131, 21) java: cannot find symbol
  symbol:   class BlockPos
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(131, 56) java: cannot find symbol
  symbol:   variable BlockPos
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(131, 40) java: cannot find symbol
  symbol:   variable ImmutableSet
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(132, 21) java: cannot find symbol
  symbol:   class BlockPos
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(136, 55) java: cannot find symbol
  symbol:   class BlockPos
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(137, 21) java: cannot find symbol
  symbol:   class BlockPos
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(141, 55) java: cannot find symbol
  symbol:   class BlockPos
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(142, 43) java: cannot find symbol
  symbol:   class Vec3d
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(143, 39) java: cannot find symbol
  symbol:   variable Vec3d
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(144, 43) java: cannot find symbol
  symbol:   class Vec3d
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(145, 43) java: cannot find symbol
  symbol:   class Vec3d
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(150, 17) java: cannot find symbol
  symbol:   class WireType
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest
Error:(151, 17) java: cannot find symbol
  symbol:   class Connection
  location: class blusunrize.immersiveengineering.api.wires.utils.CatenaryTracerTest

**Comment by BluSunrize** [comment]
I'm afraid we do not offer assistance in compiling the mod yourself.

**Comment by PyroFlareX** [comment]
When will a new version for CurseForge be released then that includes the fix?

**Comment by BluSunrize** [comment]
Whenever I get around to it.

**Comment by PyroFlareX** [comment]
Much appreciated. Thank you.
