### ISSUE TITLE
[1.15.2] Engineer's Blueprint crashes game

### ISSUE THREAD

**Issue by plucactus1** [BluSunrize/ImmersiveEngineering#3971]
I am playing with other mods and when I put Engineer's blueprint in Engineer's workbench game crashes

https://pastebin.com/6F7J6TD1 (pastebin link crash report)

https://pastebin.com/Ax6t9Z1k (modlist) (forge version = 31.2.9)

**Comment by malte0811** [comment]
Duplicate of #3908
