### ISSUE TITLE
[1.15.2] [0.15-101] Fluid meters don't show mouse-over tooltips on any UI

### ISSUE THREAD

**Issue by vectorwing** [BluSunrize/ImmersiveEngineering#3975]
### Description of the issue:
When opening an interface that displays a stored fluid meter (e.g. Coke Oven, Assembler, Fermenter etc), the meter does not show a tooltip with the type and quantity of fluid when hovering with the cursor.

![image](https://user-images.githubusercontent.com/5566692/84573967-18170a80-ad7a-11ea-8db2-efb88138962e.png)

### Versions & Modlist

forge-1.15.2-31.2.9
ImmersiveEngineering-0.15-101-8b4c2e95
jei-1.15.2-6.0.0.4

**Comment by vectorwing** [comment]
Update: it seems the Engineer's Workbench is also lacking mouse-over tooltips to inspect a recipe's ingredients.

**Comment by malte0811** [comment]
Fixed in dedc6c1
