### ISSUE TITLE
IE crashes game with JEI

### ISSUE THREAD

**Issue by plucactus1** [BluSunrize/ImmersiveEngineering#3976]
When I type to JEI  "bl , la or he" game crashes . I looked to crash report , it says "ImmersiveEngineering" so I am writing this to here . I dont know anything about programming.

https://pastebin.com/BzqtiUmm (pastebin link crash report)

https://pastebin.com/zF3XuzYG (pastebin link mod list) (forge version 31.2.9)

**Comment by BluSunrize** [comment]
Duplicate, caused by Optifine.
Already fixed for next release.
Please use the search function next time.

**Comment by plucactus1** [comment]
> Duplicate, caused by Optifine.
> Already fixed for next release.
> Please use the search function next time.

Ok , thank you I searched but I cant find.
