### ISSUE TITLE
[1.14] Not all connectors will break and drop when they lose support.

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#3978]
### Description of the issue:
The following screenshot shows the connectors that won't drop once their supporting blocks are broken. These are the cable connector, the Redstone Probe, and all the other Redstone connectors.
![2020-06-14_08 20 27](https://user-images.githubusercontent.com/52493793/84587761-f79e8d00-ae19-11ea-836a-202b952f1210.png)

### Versions & Modlist
MC Version 1.14.4
Forge Version 28.2.16
IE Version 0.14.97

**Comment by BluSunrize** [comment]
Intentional.
Structural connectors are decorative, having them break when you start remodeling would be really frustrating.
Redstone connectors may need to be placed against a block, then have that block replaced with things that interact with redstone.
