### ISSUE TITLE
LV , MV and HV relays and connectors are invisible [1.15.2]

### ISSUE THREAD

**Issue by plucactus1** [BluSunrize/ImmersiveEngineering#3979]
LV , MV and HV relays and connectors are invisible but wires not.

![2020-06-14_21 53 31](https://user-images.githubusercontent.com/66688465/84601532-8e566280-ae89-11ea-8408-c080f2f64b12.png)

IE version : 0.15-101 Forge Version : 31.2.9

**Comment by malte0811** [comment]
Are you using Optifine?

**Comment by plucactus1** [comment]
> Are you using Optifine?

Yes

**Comment by plucactus1** [comment]
> Are you using Optifine?

Okay I did I removed Optifine

**Comment by BluSunrize** [comment]
And are they visible now?

**Comment by Loneflint** [comment]
so i am having the same issue. i updated to optifine 1.15.2 pre 26 and the connectors AND the lanterns were invisible.

I removed optifine and i can see them now

**Comment by malte0811** [comment]
Fixed in 492e4a5

**Comment by Loneflint** [comment]
damn that was fast

**Comment by drewbit** [comment]
Sorry to reopen. Having the same issue even now.

![image](https://user-images.githubusercontent.com/17441782/86080425-1c1c7b00-ba50-11ea-9339-c97cdc100069.png)


IE Version: 0.15.-103
Optifine Version: OptiFine_1.15.2_HD_U_G1_pre30
Forge Version: 31.2.27
