### ISSUE TITLE
Mod is not loading upon game startup

### ISSUE THREAD

**Issue by kmdm4** [BluSunrize/ImmersiveEngineering#3981]
I have no issues loading other mods. It is only Immersive Engineering that fails to load.

I am thinking it's because I am using a 1.12.2 mod loader but it may be another issue,

**Comment by malte0811** [comment]
1. 1.12 is no longer supported.
2. Which version of IE are you trying to load?

**Comment by kmdm4** [comment]
I found the issue and it was because of the game version. Thanks.
