### ISSUE TITLE
[1.15.2] Wires don't transfer power

### ISSUE THREAD

**Issue by krischey** [BluSunrize/ImmersiveEngineering#3982]
IE-Version: 0.15-101
Forge-Version: 31.2.9

First noticed this when I manually updated IE in the All The Mods 5 Modpack and my machines were not powered anymore. Tried replacing the wires with no difference. I created a Modpack with only IE installed, still no power transfer via wires. I tested this with a minimal setup, just a kinetic dynamo with a windmill powering a garden cloche with a direct connection.![IE-Bug](https://user-images.githubusercontent.com/41529822/84609699-4864c300-aeb8-11ea-9f0e-fdf1ebdb2ded.jpg) It doesn't matter if LV, MV or HV-wires - normal or isolated - are used.

**Comment by malte0811** [comment]
Fixed in build 103 (uploaded a few hours after 101, just for this bug).

**Comment by bloche1871** [comment]
I still have this issue in 103

**Comment by malte0811** [comment]
Open a new issue for it, with all the details requested in the contributing guidelines. The original issue was a simple bug caused by me making last-minute changes to wiring-related code, but that's definitely fixed in 103.

**Comment by bloche1871** [comment]
Just tested in an environment with only IE and wasn't able to reproduce, so my guess is it was probably some other mod causing it. Sorry for the false report.
