### ISSUE TITLE
[1.15.2] pass through connector rendering glitch and crash

### ISSUE THREAD

**Issue by coalman321** [BluSunrize/ImmersiveEngineering#3983]
### Description of the issue:
When converting connectors to pass through a block, the connector models become invisible. If a client then attempts to break the invisible connector, It will crash with a null pointer on tessellating the pass through model. 

### Crashlog:
https://gist.github.com/coalman321/4b59870148711e693baded29bd60dac8

### Versions & Modlist
forge-1.15.2-31.2.8-client.jar Minecraft {minecraft@1.15.2 DONE}
		tombstone-4.4.0-1.15.2.jar Corail Tombstone {tombstone@4.4.0 DONE}
		ImmersiveEngineering-0.15-99.jar Immersive Engineering {immersiveengineering@0.15-99 DONE}
		pamhc2trees-1.15.2-1.0.5.jar Pam's HarvestCraft 2 Fruit Trees {pamhc2trees@version DONE}
		buildinggadgets-3.3.5.jar Building Gadgets {buildinggadgets@3.3.5 DONE}
		pamhc2crops-1.15.2-1.0.5.jar Pam's HarvestCraft 2 Crops {pamhc2crops@version DONE}
		refinedpipes-0.4.2.jar Refined Pipes {refinedpipes@0.4.2 DONE}
		jei-1.15.2-6.0.0.4.jar Just Enough Items {jei@6.0.0.4 DONE}
		forge-1.15.2-31.2.8-universal.jar Forge {forge@31.2.8 DONE}
		Psi r1.2-82.jar Psi {psi@r1.2-80 DONE}
		FastLeafDecay-v22.jar FastLeafDecay {fastleafdecay@v22 DONE}
		curios-FORGE-1.15.2-2.0.2.4.jar Curios API {curios@FORGE-1.15.2-2.0.2.4 DONE}
		Botania-r1.15-384.jar Botania {botania@r1.15-384 DONE}
		Patchouli-1.15.2-1.2-33.jar Patchouli {patchouli@1.15.2-1.2-33 DONE}
		create-mc1.15.2_v0.2.4a.jar Create {create@mc1.15.2_v0.2.4a+custom DONE}
		refinedstorage-1.8.4.jar Refined Storage {refinedstorage@1.8.4 DONE}
		pamhc2foodcore-1.15.2-1.0.3.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
		journeymap-1.15.2-5.7.0b2.jar Journeymap {journeymap@5.7.0b2 DONE}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 DONE}
		CookingForBlockheads_1.15.2-8.0.2.jar Cooking for Blockheads {cookingforblockheads@8.0.2 DONE}

**Comment by malte0811** [comment]
The invisible connectors are fixed in build 101/103, I'll have to check whether the crash is gone as well.

**Comment by malte0811** [comment]
Breaking the connectors works in 103. I'd recommend disassembling like that for the moment, the middle block currently does not drop correctly (already fixed for the next build).
