### ISSUE TITLE
[Suggestion] Chem thrower with water could turn concrete powder to concrete

### ISSUE THREAD

**Issue by notadevtho** [BluSunrize/ImmersiveEngineering#3985]
Since manually turning concrete powder to concrete in vanilla is super tedious, I think it'd be very nice if the Chemthrower could turn concrete powder into concrete (all vanilla) when you spray it with water.

**Comment by vectorwing** [comment]
This would be incredible to have. I build with vanilla concrete a lot, and either watering/mining it all before use or placing buckets to wash placed powder gets annoying fast.
