### ISSUE TITLE
[1.15.2] Unable to open Engineer's Toolbox when placed in the world

### ISSUE THREAD

**Issue by notadevtho** [BluSunrize/ImmersiveEngineering#3986]
### Description of the issue:
~~Issue 1:
The Engineer's Toolbox GUI shows the "name" of each slot if you hover over them, but it's not showing the "item" texture (like where the hammer goes, wirecutters, etc)
pic: https://imgur.com/a/pwFoISO~~

Issue 2: IIRC you can open the Engineer's Toolbox when placed in the world, this is not possible right now. It works correctly when holding it on your hand though.

### Crashlog:
No crash

### Versions & Modlist
Minecraft 1.15.2
Forge 31.2.19
ImmersiveEngineering-0.15-103-40a7f41c (#7 in jenkins)
jei-1.15.2-6.0.0.4

**Comment by notadevtho** [comment]
I forgot to mention, when placed in the world, I'm almost 100% sure that it's placed facing the opposite direction.

**Comment by malte0811** [comment]
I'm not sure what you mean in the first issue. There isn't any specific slot for the hammer, the wirecutters etc., they can go anywhere in the "tools" section. And I don't really see any difference between your screenshot and what I see in my 1.12 workspace.

**Comment by malte0811** [comment]
For the second issue: Does this only happen on dedicated servers? It works fine for me in singleplayer.

**Comment by notadevtho** [comment]
AFAIK it only happened in the IE server! So I assume it's a server thing (happened to the other players too)
Regarding the first thinjg about the GUI just ignore it, I was sure it was a thing. Perhaps an addon changed the GUI? I'll do some testing later.

**Comment by notadevtho** [comment]
It happens in SP for me also, and I made a new clean instance with only IE and still can't open it when placed in the world

**Comment by malte0811** [comment]
Fixed in e933197
