### ISSUE TITLE
[1.15.2] [0.15-103 #7] Metal Ladders have rendering issues

### ISSUE THREAD

**Issue by vectorwing** [BluSunrize/ImmersiveEngineering#3992]
### Description of the issue:
I found a few rendering problems with Metal Ladders:

- Placed in the world, it's opaque, and its sides cause x-ray through its supporting block;
- On the player's hand, both first-person and third-person use the "shield" render.

![image](https://user-images.githubusercontent.com/5566692/84795149-7e479b80-afcd-11ea-8990-fc943e4f0574.png)

### Versions & Modlist

forge-1.15.2-31.2.9
ImmersiveEngineering-0.15-103-40a7f41c
jei-1.15.2-6.0.0.4

**Comment by malte0811** [comment]
Fixed in 43d530c and bd93677
