### ISSUE TITLE
[1.15.2] [0.15-104 #8] Combining Hammers/Cutters in a crafting grid duplicates the item

### ISSUE THREAD

**Issue by vectorwing** [BluSunrize/ImmersiveEngineering#3994]
### Description of the issue:
Repairing the Engineer's Hammer or the Wire Cutters on a crafting grid leaves the previous tool in the grid, **duplicating** the item. Steel tools and other durability equipment do not suffer this issue.

### Versions & Modlist
forge-1.15.2-31.2.9
ImmersiveEngineering-0.15-104-492e4a5a
jei-1.15.2-6.0.0.4

**Comment by drmorgmd** [comment]
I can confirm this issue it also happens in the refined storage grid.
