### ISSUE TITLE
[1.15.2] [0.15-103] Mekanism's steel block cannot craft Steel Slab

### ISSUE THREAD

**Issue by magic0whi** [BluSunrize/ImmersiveEngineering#3995]
**Description of the issue**
The steel block of the IE is replaced by the steel block of Mekanism,
but I cannot craft the Steel Slab by using Mekanism's steel block.
![Annotation 2020-06-17 201707](https://user-images.githubusercontent.com/28147340/84897063-9d325480-b0d7-11ea-8745-d11c38609a82.png)

**Versions & Modlist**
Minecraft 1.15.2
Forge 31.2.20
ImmersiveEngineering-0.15-103
Mekanism-1.15.2-9.10.7.420
MekanismGenerators-1.15.2-9.10.7.420
MekanismTools-1.15.2-9.10.7.420

**Comment by BluSunrize** [comment]
This is intentional.
IE's metal slabs are crafted only with IE's metal blocks and do not use tags. The reason for that is that I expect other mods to add slabs, and I wouldn't want to override their recipes with mine.

Either get your hands on IE steel blocks (crafted from IE steel ingots) or tell Mekanism to add slabs.

**Comment by magic0whi** [comment]
> This is intentional.
> IE's metal slabs are crafted only with IE's metal blocks and do not use tags. The reason for that is that I expect other mods to add slabs, and I wouldn't want to override their recipes with mine.
> 
> Either get your hands on IE steel blocks (crafted from IE steel ingots) or tell Mekanism to add slabs.

I can't craft IE steel blocks with IE steel ingots, the output is still Mekanism's steel block.
On the other hand, since there is no way to get Block of Steel except the `\give` command, even the Arc Furnace is Impossible to build if Mekanism is enabled.

![Annotation 2020-06-18 071835](https://user-images.githubusercontent.com/28147340/84960355-f7f99980-b133-11ea-9569-b4e83ac1da2f.png)

**Comment by BluSunrize** [comment]
> I can't craft IE steel blocks with IE steel ingots, the output is still Mekanism's steel block.

Well maybe mekanism shouldn't craft their steel block with tags then?! They should make *their* metal blocks use *their* ingots, instead of just overriding all other mods.
That's still on their side to fix, not ours.
