### ISSUE TITLE
[1.14] Conveyors can't insert into Covered Vertical Conveyors.

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#3998]
### Description of the issue:
At least for the Covered Vertical Conveyor, it can't be inserted into by other conveyors from the sides. But it works with hoppers.

Evidence:
![2020-06-18_09 12 13](https://user-images.githubusercontent.com/52493793/84996079-b4f3f200-b144-11ea-8e48-e1924dcd415d.png)

### Versions & Modlist
MC Version 1.14.4
Forge Version 28.2.16
IE Version 0.14.102

**Comment by BluSunrize** [comment]
Title is misleading. Normal vertical conveyors are fine.
