### ISSUE TITLE
[Suggestion] Rotate Redstone gates with the hammer

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#4000]
Make it possible to change the orientation of blocks like Repeaters and Comparators by using the Hammer. This is particularly convenient when placing a Comparator under a Silo and you can't make it point the right way because the Silo is in the way.

**Comment by BluSunrize** [comment]
This would require having the hammer handle its rotating of blocks in `onItemUseFirst`

@malte0811 can you think of any immediate issues with that change? I myself can't, but I'd like your input before I try implementing it.
