### ISSUE TITLE
[1.15.2] [0.15-103] The sound of Treatened Fences, Stairs and Scafolding has a stone sound

### ISSUE THREAD

**Issue by Fakeowo** [BluSunrize/ImmersiveEngineering#4002]
Description of the issue:
The sound of Treatened Fences, Stairs and Scafolding has a stone sound, instead of wood sound when placing or walking on them. 

Screenshot:
https://imgur.com/a/GcqcrTk

Versions & Modlist
forge-1.15.2-31.2.20
ImmersiveEngineering-0.15-103

**Comment by BluSunrize** [comment]
Whoops, this ain't an issue in 1.14
