### ISSUE TITLE
[Suggestion] Alternative recipe for conveyor belts.

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#4007]
Because farming animals like cows can't be automated, it become tricky to gather enough leather to craft conveyor belts. I suggest that instead of leather, the recipe could use Tough Fabric. Maybe even also require creosote impregnation in some way, just so that it's a little more resource intensive and adds another use for creosote.

**Comment by IcedForge** [comment]
Possibility of doing something with rotten flesh perhaps ?

**Comment by BluSunrize** [comment]
Not everything needs to be automatable ^^
IE has faired pretty well without an alternate conveyor recipe for 5 years, and I personally don't like the idea of using hemp fabric for it.
