### ISSUE TITLE
[1.14] Garden Cloche doesn't accept Bone Meal in the fertilizer slot.

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#4010]
### Description of the issue:
According to the Engineer's Manual, the left slot in the Garden Cloche GUI, under the water level indicator, should accept a fertilizer, but Bone Meal won't be accepted in the slot. Using a hopper to introduce Bone Meal into the items input of the Cloche doesn't work either.

### Versions & Modlist
MC Version 1.14.4
Forge Version 28.2.16
IE Version 0.14.102

**Comment by malte0811** [comment]
It looks like this was simply missed when recipes were moved to JSON. I'll assign this issue to @BluSunrize since he has actually thought about this stuff, and I have no idea what the best approach would be.

**Comment by BluSunrize** [comment]
Yeah, I'm aware of this. It's on my list of stuff to fix. Just haven't had time or motivation on the weekend.

**Comment by BluSunrize** [comment]
Fixed by https://github.com/BluSunrize/ImmersiveEngineering/commit/10ca334d73910c645a5f677b9d1a200d6ace14e5
