### ISSUE TITLE
[1.15.2] [0.15-105 #9] Rendering issues when looking at turntable sides with a hammer

### ISSUE THREAD

**Issue by vectorwing** [BluSunrize/ImmersiveEngineering#4012]
### Description of the issue:
When holding the Engineer's Hammer, and looking at a Turntable's sides to see the orientation settings, transparent objects suffer rendering issues, moving them far from the player's view.

Here's an example demonstrating some transparent blocks and the Garden Cloche:

**Looking away**
![image](https://user-images.githubusercontent.com/5566692/85168328-98d57b00-b240-11ea-8469-09e363dda360.png)

**Looking at Turntable's side**
![image](https://user-images.githubusercontent.com/5566692/85168377-ac80e180-b240-11ea-8b4c-75330706cedc.png)

### Versions & Modlist
forge-1.15.2-31.2.9
ImmersiveEngineering-0.15-105-e51d080a
jei-1.15.2-6.0.0.4

**Comment by malte0811** [comment]
Fixed in 05b438f
