### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Pannoniae** [BluSunrize/ImmersiveEngineering#4013]
### Description of the issue:
A server crash.

### Crashlog:
https://gist.github.com/Pannoniae/343e95ef48085cc465e1c85aca20e745

### Versions & Modlist
IE 0.15-103
Forge 31.2.9

**Comment by AndrewTaboada-dev** [comment]
I am having a similar crash issue. I get the issue when a place IE wires in a specific region and unload the chunk (by logging off or going to the nether). The server has gone through a few modpacks iterations so something might have been corrupted at some point. I'm running on 1.14.4 and the attached crash report has all the mods listed.

[crash-2020-07-25_03.01.10-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4975059/crash-2020-07-25_03.01.10-server.txt)
