### ISSUE TITLE
[1.15.2] [0.15-105 #9] Improved Blast Furnace's hopper does not catch items

### ISSUE THREAD

**Issue by vectorwing** [BluSunrize/ImmersiveEngineering#4014]
### Description of the issue:
When moving a valid item to the Improved Blast Furnace's "hopper" input, it does not catch the item. I'm assuming it should do so from the manual's description, but I'm not sure; please correct me if I'm wrong.

![image](https://user-images.githubusercontent.com/5566692/85189102-0d7cd980-b282-11ea-9f11-7e48e39a586e.png)

The "hopper" block still works as a valid input for insertion via other Hoppers, Dropping Conveyor Belts, and so on.

### Versions & Modlist
forge-1.15.2-31.2.9
ImmersiveEngineering-0.15-105-e51d080a
jei-1.15.2-6.0.0.4

**Comment by BluSunrize** [comment]
It has never done that in all the years it has been in this mod, and nothing in the manual says that it does.
