### ISSUE TITLE
[MC 1.15.2] Custom recipes not loading from datapack

### ISSUE THREAD

**Issue by winnetrie83** [BluSunrize/ImmersiveEngineering#4016]
Hi, i tried making a datapack to add custom recipes to the garden gloche.
I'm pretty sure i have done everything correctly, but it isn't working.
However, overriding existing recipes with a datapack works just fine.
I tried adding tomato seeds from simple farming to the garden cloche.

EDIT: After testing more stuff, it seems this is the case for all machines. All custom recipes from a datapack that actually adds something to IE are not loaded at all. Custom recipes that overrides existing IE recipes are loaded and work properly. Therefor i changed the title of this issue.

**### Crashlog:**
No crashlog.

**### Versions & Modlist**
Minecraft 1.15.2
forge-31.2.21
ImmersiveEngineering-0.15-103.jar

I tested this in a clean and fresh world with only IE and simple farming installed

**Comment by ZAKsPop** [comment]
I'm able to make custom recipes for the fermenter, squeezer, and press.
Forge 31.2.19
ImmersiveEngineering-0.15-103.jar

**Comment by winnetrie83** [comment]
It appears to work just fine. apparently most of the crop blocks needs a "_crop" after the name
