### ISSUE TITLE
[1.14] [1.15.2] [0.15-105 #10] Breaker switch Inverting/Rotating

### ISSUE THREAD

**Issue by IcedForge** [BluSunrize/ImmersiveEngineering#4017]
### Description of the issue:
Breaker Switch does not accept any type of tool manipulation it only reacts to turn function on/off, no alternative function ( inverting ) or rotating

### Versions & Modlist
ImmersiveEngineering 1.14-102
Jei 1.14.4-6.0.0.27

And 1.15
ImmersiveEngineering 0.15-105-a2b2b71a
jei-1.15.2-6.0.0.4

**Comment by malte0811** [comment]
Fixed in fda2902, I referenced #2017 rather than #4017 by accident.
