### ISSUE TITLE
Energy Net randomly stops delivering power [1.7.10]

### ISSUE THREAD

**Issue by PyroRider** [BluSunrize/ImmersiveEngineering#4019]
### Description of the issue:
I build a power network running 3 HV wires in parallel, now none of my generators work at all, the HV connectors dont give power to the mekanism cables, at all the energy net is a total desaster. Use 3 capacitors as Input, it would empty one after another, this happens with ALL power sources, therefore making it impossible to push 32kRF through a HV wire, because its impossible to get more than 4krf into it. And as I wrote, now the power network is not doing anything at all, it just stopped when I connected my HV connector to an elite universal cable. (Yes, I tried connecting it to other things as well, no, it did not change anything)
Please help, this bug/whatever drives me crazy...
(Built a "2x 3 Phase" power network looks nice, does not work too, neither with one generator and 6 hv transformers, as with 6 generators and 6 hv transformers, also not with 6 generators and plain old style just the hv connectors.)
*sad IE-Fan noises*

### Versions & Modlist
IE Version 0.7.7
IE Integration Version 0.6.8
Forge Version 1.7.10/10.13.4.1614

**Comment by IcedForge** [comment]
The connectors only accept 4krf per unit, not sure how you arent getting 32krf on the grid 8x connectors connected to 1 relay = 32k rf, battery banks capacitors only draw power and there isnt really any good "balancing" system as far as i  know.

Second this is a 1.7.10 potential mek compat issue and is NOT supported so im guessing this is gonna get canned.

**Comment by malte0811** [comment]
1.7.10 has been out of support for over 4 years.
