### ISSUE TITLE
Crash a Few Seconds After Placing Wire

### ISSUE THREAD

**Issue by Kolatra** [BluSunrize/ImmersiveEngineering#402]
http://pastebin.com/XVjJsrrU

This is on the latest source code from the repo, I loaded my world, and everything seemed fine. So I started placing wires, after the first few, the game crashed with this.

**Comment by GirafiStudios** [comment]
Try removing Optifine and Fastcraft and see if this sitll happens.

**Comment by Kolatra** [comment]
This does indeed still happen without having Optifine or Fastcraft present. It also seems to happen every single time I try to connect two wires to one node.

**Comment by GirafiStudios** [comment]
Most likely caused by this commit : https://github.com/BluSunrize/ImmersiveEngineering/commit/3cfb0e5a7f760397b369fb73d7d2b1a89ba0fe15 . Sorry can't help you with that, that would be a job for @BluSunrize  ^^

**Comment by mindforger** [comment]
wow, this one is odd, can you try renaming your config to regenerate a new ?

**Comment by BluSunrize** [comment]
Hmm, yeah that is a funny one. Implies that some connections lack a wiretype. Weeeeird.
I'm gonna add a nullcheck, but that really only "silences" the problem.

**Comment by Kolatra** [comment]
Alright. But the fact that is silences the problem can be concerning.

**Comment by mindforger** [comment]
@BluSunrize i did not check the new code yet, but did you probably somewhere use a list-function that automatically inserts an Connection by default Constructor or some implicit malicious Constructor which can result in a missing wiretype?

**Comment by mindforger** [comment]
@BluSunrize this maybe a racing condition and a result of the fix(for good)!

for example, you set the wiretype in your removeCable to null, but the same time the same connection may be used in another thread, not aware of this change!

in the past this would have resulted in a CME! now you'll have to probably add an field to your connections to mark them invalid (invalidate), but i did not found yet any code that would explain it clearly, maybe check whereever you set null to the wiretype property

**Comment by BluSunrize** [comment]
the variable "cableType" is never set except for in the constructor though :/

**Comment by mindforger** [comment]
i'd build in some additional debug options to most of the sanity checks you added lately, just to discover who the F is messing with your stuff :P just throw a few stacktraces into the log when in verbose mode whenever a sanity check fails

**Comment by mindforger** [comment]
@BluSunrize in IESave you should probably guard against malicious NBT Entrys with null for Cable Type probably, either in IESave directly 
>	Connection con = Connection.readFromNBT(conTag);
>      if(con!=null && con.WireType!=null)
>		ImmersiveNetHandler.INSTANCE.addConnection(world, con.start, con);

of better in your Connection Class in "readfromNBT"!!!!
>		WireType type = ApiUtils.getWireTypeFromNBT(tag, "cableType");
>			if(start!=null && end!=null && type!=null)
>				return new Connection(start,end, type, tag.getInteger("length"));

and in ItemWireCoil you also use an unguarded addConnection in "onItemUseFirst", where you should probably either guard your type from "getWireType(Stack)" or probably guard directly in "addConnection"

same unguarded situation goes for onDataPacket in your TileEntityConnectable, where you probably can receive a malicious NBT Tag

probably best solution is to guard your NBT Functions + your addConnection Methode for this particular case, and let a few debug messages fly into the logs for this case to get a better feedback why it is happening :)

**Comment by Kolatra** [comment]
Seems to be fixed.
