### ISSUE TITLE
[1.15.2] [0.15-105 #10] Wonky Heavy Plated Shield blocking animation while holding it in offhand in 3rd person view

### ISSUE THREAD

**Issue by loleq2105** [BluSunrize/ImmersiveEngineering#4020]
The blocking animation of the heavy plated shield is broken in third person view when blocking with it in offhand.
![2020-06-21_17 31 15](https://user-images.githubusercontent.com/52840858/85285350-1099e480-b491-11ea-838e-c020a8df8b9a.png)
The blocking animation of the heavy plated shield is, however, fine in first person view when blocking with it it in offhand.
![2020-06-22_14 16 37](https://user-images.githubusercontent.com/52840858/85286566-28726800-b493-11ea-86be-aa105e5db476.png)
The blocking animation of the heavy plated shield is fine in both view modes when blocking with it in the main hand. 
![2020-06-22_14 16 56](https://user-images.githubusercontent.com/52840858/85286644-4b048100-b493-11ea-8d66-fb97697ac6c8.png)
![2020-06-22_14 17 01](https://user-images.githubusercontent.com/52840858/85286652-4dff7180-b493-11ea-9353-b285e9150873.png)
Discovered on a server, replicated in singleplayer.

**Comment by BluSunrize** [comment]
Can reproduce, issue only exists in 1.15, not in 1.14
