### ISSUE TITLE
[1.15] IE Test Server crash

### ISSUE THREAD

**Issue by BluSunrize** [BluSunrize/ImmersiveEngineering#4022]
Happened on our test server today.

https://gist.github.com/BluSunrize/381a6f49a542573602ff9f6e5206567b

Seems to be related to earmuffs, potentially a client-side-method exception.

Using IE 105, commit a2b2b71a.

**Comment by Fakeowo** [comment]
The crash was caused by placing ear defenders with a dye in the engineering crafting table.

Screenshot:
https://imgur.com/a/TR4Lnyz

**Comment by BluSunrize** [comment]
There is a better fix for this, following the pattern of dyeable armor in vanilla.
