### ISSUE TITLE
[1.15.2] [0.15-105] Fluid Router Interaction Crash

### ISSUE THREAD

**Issue by PieKing1215** [BluSunrize/ImmersiveEngineering#4023]
### Description of the issue:
Right clicking a fluid router instantly crashes the client.
To reproduce: generate a fresh world -> place fluid router -> right click -> game crash

### Crashlog:
[pastebin](https://pastebin.com/CdrZSy6G)

### Versions & Modlist
IE-0.15-105-a2b2b71a
Forge 31.2.22
No other mods

**Comment by malte0811** [comment]
Fixed in 3e326ab
