### ISSUE TITLE
[1.15.2] [0.15-105 #10] Opening a engieneer's carfting table with items in it causes test server crash

### ISSUE THREAD

**Issue by Arathorne** [BluSunrize/ImmersiveEngineering#4025]
### Description of the issue:
Interacting with someone else engieneer's crafting table with items causes test server crash.
### Crashlog:
crashlog will be provided from the test server owner
### Versions & Modlist
forge 31.2.9 , IE [1.15.2] [0.15-105 #10] and basic, not modified modlist of the server

**Comment by BluSunrize** [comment]
Please follow the issue template. You are on the test server, you should know better.

**Comment by malte0811** [comment]
The seems to be a duplicate of #4022, we don't have any other crashlogs on the server.
