### ISSUE TITLE
[1.15.2] [0.15-105] Floodlight model incorrect offset & rotation

### ISSUE THREAD

**Issue by PieKing1215** [BluSunrize/ImmersiveEngineering#4026]
### Description of the issue:
The model for a placed floodlight rotates about the wrong point, causing its model to be offset from the hitbox.

![IE_1](https://user-images.githubusercontent.com/13819558/85434990-d42fbc80-b554-11ea-809f-b37ac31e600c.gif)
![IE_2](https://user-images.githubusercontent.com/13819558/85435006-d8f47080-b554-11ea-8d25-2eceb415ba46.gif)

Additionally, depending on the orientation it was placed, the base of the model is offset:
![image](https://user-images.githubusercontent.com/13819558/85435911-2de4b680-b556-11ea-995c-4efe866bd3a2.png)

### Crashlog:
N/A

### Versions & Modlist
IE-0.15-105-a2b2b71a
Forge 31.2.22
No other mods

**Comment by malte0811** [comment]
Fixed in 8d1ca5d
