### ISSUE TITLE
[1.14.4] Shown amount of creosote oil in the coke oven is not updating while inactive

### ISSUE THREAD

**Issue by Eneong** [BluSunrize/ImmersiveEngineering#4027]
There were already issues about this problem but they were closed without any result.

### Description of the issue:
If you drain the coke oven oil tank with a bucket, while coal is not being processed in it, the display amount of the tank will not change, although the actual amount is supposedly correct. But once you start the processing, the value immediately decreases to the correct amount. Restart also helps. Closing and opening of oven UI does not help. And it does not give you infinite amount of creosote oil.

![изображение](https://user-images.githubusercontent.com/10401070/85432561-2e9c3d80-b594-11ea-90ef-3802ac5dc22a.png)
![изображение](https://user-images.githubusercontent.com/10401070/85432589-3c51c300-b594-11ea-977a-568b2142d55a.png)
![изображение](https://user-images.githubusercontent.com/10401070/85432626-483d8500-b594-11ea-97d4-bb5e237f7510.png)

#### Crashlog:
No crashlog

### Versions & Modlist
forge 1.14.4 - 28.2.19
ImmersiveEngineering-0.14-102

**Comment by DeadlySwede** [comment]
Duplicated in Jenkins Build 10 on test server.
