### ISSUE TITLE
[1.15.2] [0.15-105 #10] Duplicating Items with Engieneering's workbench.

### ISSUE THREAD

**Issue by Arathorne** [BluSunrize/ImmersiveEngineering#4028]
### Description of the issue:
Requirements:
-Revolver and/or buzzsaw (3d weapon)
-Engieneering workbench
Tutorial how to duplicate:
1.Get desired items to copy:
![desired items](https://user-images.githubusercontent.com/60345302/85435834-5ab1c180-b588-11ea-93ea-e5c89886a14a.PNG)
2. enter the workbench & put weapon in editing window
![entering](https://user-images.githubusercontent.com/60345302/85435826-584f6780-b588-11ea-9838-be9f4903463f.PNG)
3. quit the workbench 
![quit](https://user-images.githubusercontent.com/60345302/85435830-59809480-b588-11ea-9822-830f11fdf6c1.PNG)
4.re-enter it & take the weapon with shift
![shift](https://user-images.githubusercontent.com/60345302/85435832-5ab1c180-b588-11ea-9f09-285f52b3e830.PNG)
5. Quit the workbench again
![quit](https://user-images.githubusercontent.com/60345302/85435830-59809480-b588-11ea-9822-830f11fdf6c1.PNG)
IMPORTANT 6. open your inventory to accept duplicated items
![duplicated xDD](https://user-images.githubusercontent.com/60345302/85435835-5b4a5800-b588-11ea-8780-117dfa0960a2.PNG)
End. (Tested on creative mode& survival mode[works:xd:])
This glitch only occurs on singleplayer and the tool is without any modification
On multiplayer this glitch doesn't work

### Versions & Modlist
forge 31.2.9 , IE [1.15.2] [0.15-105 #10] and basic, not modified modlist of the server

**Comment by Fakeowo** [comment]
Crashlog after duplicating too much items  and throwing them on the ground:
https://pastebin.com/7wNViTfd

**Comment by PieKing1215** [comment]
I tested this (in singleplayer) and I could only actually dupe items in creative.
In survival it just gives me ghost items that go away when you click/relog/etc.
Were you testing in multiplayer?

Interestingly, the game crashes if you stop after step 4 and shift click a bunch of these ghost items in/out of the table:
https://pastebin.com/JxyCb2M8
Edit: this crash is the same as #4029

**Comment by Arathorne** [comment]
Tried it on test server and it ghots items
