### ISSUE TITLE
Crash Upon Startup

### ISSUE THREAD

**Issue by BionicDoug** [BluSunrize/ImmersiveEngineering#403]
Hello, I'm having difficulties adding IE into my game (a further modified version of DW20). Forge gets to post-initialization and then crashes. I'm not familiar with the intricacies of getting mods to work/cooperate or reading crash reports, but this section stood out to me: 
There was a severe problem during mod loading that has caused the game to fail
cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: blusunrize/immersiveengineering/api/CrusherRecipe
Any idea what may be causing this? Is it fixable? I can provide more of the report or my mod list if needed. Thanks!

**Comment by GirafiStudios** [comment]
Please post the crash report.

**Comment by BionicDoug** [comment]
http://pastebin.com/Rhkq2Qck

**Comment by GirafiStudios** [comment]
Looks like a issue with AOBD and IE. Not quite sure what to do to fix it. Do you have the latest version of AOBD?

**Comment by BionicDoug** [comment]
I don't. I'll update it and let you know if that works. Thanks!

**Comment by BionicDoug** [comment]
Yep, that was it. Thank you sir!
