### ISSUE TITLE
[1.12] Multiblock still drop items while in creative

### ISSUE THREAD

**Issue by LemADEC** [BluSunrize/ImmersiveEngineering#4030]
### Description of the issue:
As a creative player, when breaking a multiblock part items are still dropping while they should not.
This is systematic.
It's reproduced on all Poles, Coke oven, Blast furnace, Advanced furnace and Fluid tank.
Single item multiblocks like the Fluid pump and Blast furnace pre-heater don't reproduce the issue.
Other multiblocks like Crusher, Metal Press, etc. were not tested.

### Crashlog:
not applicable

### Versions & Modlist
ImmersiveEngineering-0.12-98
forge-14.23.5.2854

**Comment by malte0811** [comment]
1.12 is no longer supported, especially not for minor bugs like this.
