### ISSUE TITLE
[1.15.2] Server Crash on World Gen

### ISSUE THREAD

**Issue by QuarianHips** [BluSunrize/ImmersiveEngineering#4031]
When setting up a dedicated multiplayer server and generating a new world, the server will crash, referencing an issue with advancements that mentions IE. When IE is removed, the world will generate normally.

Crashlog: https://gist.github.com/QuarianHips/3c55f1e1ee54c899dec8c206ca83ff6d

Minecraft Version 1.15.2
Forge Version 31.2.9
IE Version 0.15-103

**Comment by QuarianHips** [comment]
Here's the link to the mc log: https://gist.github.com/QuarianHips/74057fd7cc64bb024f90dd5d94aa6b71

**Comment by BluSunrize** [comment]
Resolved in Discord, not an IE issue.
