### ISSUE TITLE
[1.15.2] [0.15-105 #15] Squeezer's piston has rendering issues on its mirrored form

### ISSUE THREAD

**Issue by vectorwing** [BluSunrize/ImmersiveEngineering#4035]
### Description of the issue:
When assembling a Squeezer with the barrels at the left side, the inner piston head has a few rendering issues. This does not occur when the barrels are on the right side. This is purely visual; hitboxes are normal on both mirrors.

![Reversed Squeezer Glitch](https://user-images.githubusercontent.com/5566692/85956596-33c70700-b95d-11ea-8040-e29e0e939f0e.png)

### Versions & Modlist
forge-1.15.2-31.2.9
ImmersiveEngineering-0.15-105-8f2d7b4d
jei-1.15.2-6.0.0.4

**Comment by malte0811** [comment]
Fixed in 140f70c45c274bdda32bdb2aa1f7492ac803ad34
