### ISSUE TITLE
oregen section of config file should be updated

### ISSUE THREAD

**Issue by meradz** [BluSunrize/ImmersiveEngineering#404]
From the config file in "oregen" section:
Parameters: Blocks per vein, lowest possible Y, highest possible Y, veins per chunk, chance for vein to spawn (out of 100). Set vein size to 0 to disable the generation

This should be reworded since "vein size" is not one of the parameters listed.

**Comment by Barhandar** [comment]
If someone is unable to make mental connection between "vein size" and "blocks per vein", is it worth accomodating for them?

**Comment by BluSunrize** [comment]
While that is a bit rude, @Barhandar, I do agree. It's fairly obvious.
