### ISSUE TITLE
[1.15.2] Hemp seeds not dropping w/Forge 31.2.30 

### ISSUE THREAD

**Issue by NickGrease** [BluSunrize/ImmersiveEngineering#4046]
### Description of the issue:
Hemp seeds from **tall grass** do not appear to drop with later versions of Forge. Tests below were in fresh worlds, with no other mods installed. Latest log included even though there was no crash, in case the information in it is relevant.

MC: 1.15.2
Mods: No other mods installed
- Forge 31.2.30
  - ImmersiveEngineering-0.15-99 - No hemp seeds drop
  - ImmersiveEngineering-0.15-103 - No hemp seeds drop
- Forge 31.2.20
  - ImmersiveEngineering-0.15-99 - Hemp seeds drop
  - ImmersiveEngineering-0.15-103 - Hemp seeds drop

### Crashlog:
No crash but a few WARN/STDERR, I'm including for brevity. 
[latest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/4866459/latest.log)

### Additional Notes:
I believe this started prior to Forge 31.2.30 maybe .27 but I can't be 100% sure.

### Edits:
It occurred to me after creating this issue that you might only be building off the release version of Forge, and not (yet) concerned about the 'latest' builds. If that's the case, my apologies, I'll understand if this is closed.

**Comment by malte0811** [comment]
It looks like the `LootTableLoadEvent` which we currently use to add the hemp seeds only fires for loottables loaded from the "default" resource pack. And apparently Forge decided that it's a good idea to completely [replace the grass loot table](https://github.com/MinecraftForge/MinecraftForge/blob/1.15.x/src/generated/resources/data/minecraft/loot_tables/blocks/tall_grass.json) for better shear handling. I guess this needs to be switched to global loot modifiers now.

I'll add the "1.14" label to this despite the fact that it doesn't affect 1.14 yet, there's an open Forge PR to backport the relevant changes to 1.14.

**Comment by MaxWasUnavailable** [comment]
This seems to be a problem again in the latest version of IE. Possible a conflict with Pam's or another food mod that adds seed drops to tall grass / ferns / etc..?

IE: 1.16.5-5.0.3-138

**Comment by BluSunrize** [comment]
Please open a new issue with full details.
