### ISSUE TITLE
[Suggestion] Better integration of the External Heater

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#4047]
There's two parts in this suggestion. For starters, I think it would be fair to expect the External Heater to also work on the vanilla blast furnace and smoker. Maybe have the three vanilla furnaces require different power levels to work. The smoker using the same power we are used to, the normal furnace use a little more power than what it already does and the blaster use even more power than that.
Another satisfying use for the External Heater would be if it could be used to make an Improved Coke Oven, which is electrically powered and has much higher throughput.

**Comment by BluSunrize** [comment]
See #3777
