### ISSUE TITLE
Feature request: ore generation blacklist/whitelist toggle

### ISSUE THREAD

**Issue by LocalBoomer** [BluSunrize/ImmersiveEngineering#4048]
Would it be possible to add the option to make the dimension blacklist for ore generation a whitelist? 

I'm trying to streamline ore generation to a single ore enabled from a single mod so I don't have 12 different copper ores spawn and I was looking through the IE configs and though the spawn rate has amazing customisation there is no 'one stop shop' method for turning it off. I was wondering if you could make the blacklist option toggle-able into a whitelist so I can have it as an empty list to disable all ore gen.

Thanks in advance!

**Comment by BluSunrize** [comment]
Look at the `vein_size` Property of every ore.
"The maximum size of a vein. Set to 0 to disable generation"

So just put that to 0 for the 6 ores that we add, and you're good.

**Comment by LocalBoomer** [comment]
I appreciate the ability to do this is there I was just wondering if you could add more flexibility/a QoL upgrade 😃
