### ISSUE TITLE
[1.15.2] Hemp block not displaying / rendering properly

### ISSUE THREAD

**Issue by JakeMoe** [BluSunrize/ImmersiveEngineering#4050]
### Description of the issue:
Made a row of water, with a row of farmland on either side.  Planted hemp seeds on farmland.  All crops are rending with white 2D squares in a hash pattern (when viewed from above): https://imgur.com/a/LWrnq6C

Have attempted both relog, and complete reload of the pack.

### Crashlog:
Not applicable - no crash

### Versions & Modlist
Minecraft: 1.15.2
Forge: 31.2.29
Immersive Engineering: 0.15-99
Modlist: https://gist.github.com/JakeMoe/6361ed33e53907c474e3f403be6e2e2d

Created a minimal instance in MultiMC using only Minecraft 1.15.2, Forge 31.2.9, and Immersive Engineering 0.15-99, no other mods, and got the same result.

**Comment by NickGrease** [comment]
I had the same issue with earlier versions of Forge and/or IE. With Forge 31.2.30 and IE 0.15-103 the issue seems to be solved. However it introduces #4046, so pick your poison 😄

**Comment by JakeMoe** [comment]
Hadn't realized there was an update, I missed that, cheers.  I'm not worried about the hemp seeds not dropping at the moment, as I already have a fair few.

However, when I upgrade my pack from 015-99 to 0.15-103, I'm now getting a warning that there are 4 missing items: shader_bag_pity, _advanced, _supreme, _simple.  Not sure if that's intended?

On the plus side, it did indeed fix my rendering issue.  :-)

**Comment by NickGrease** [comment]
Sorry, I don't have a clue what those missing items are. I went from .99 to .103 in the same world and didn't get that warning, but at that time I hadn't even started using anything from IE besides the hemp plants. Glad it fixed the rendering issue though!

**Comment by malte0811** [comment]
> However, when I upgrade my pack from 015-99 to 0.15-103, I'm now getting a warning that there are 4 missing items: shader_bag_pity, _advanced, _supreme, _simple. Not sure if that's intended?

That's normal. In 99 we added shader bags for rarity grades that didn't need them, which caused issues with Industrial Foregoing (which adds these rarities). Now we only add them when they are needed, which isn't the case for those rarities.

 > On the plus side, it did indeed fix my rendering issue. :-)

That's good to hear, I'll close this issue then.
