### ISSUE TITLE
[1.14.4] Engineer's Manual Displaying []'s where text should be. 

### ISSUE THREAD

**Issue by Cl0ud92** [BluSunrize/ImmersiveEngineering#4051]
The engineer's manual text is broken it just looks like a bunch of "[]" wherever text should be. It's just a bunch of rectangular symbols wherever the text would be located.

Screenshot: https://imgur.com/gallery/JWHHGqc

IE: 0.14-102
Forge: 28.2.21
Mod List: https://pastebin.com/2PHqUeDR

**Comment by malte0811** [comment]
Does this happen without the texture pack? It's a known issue with Faithful.

**Comment by Cl0ud92** [comment]
> Does this happen without the texture pack? It's a known issue with Faithful.

Oh crap! I didn't even think of that! Turning off Faithful fixes it completely.
