### ISSUE TITLE
[1.15.2] Crash when attempting to dual wield revolver

### ISSUE THREAD

**Issue by Profilename1** [BluSunrize/ImmersiveEngineering#4053]
### Description of the issue:
Minecraft crashes when you attempt to hold a revolver in your off-hand slot as well as your main hand. Not much more to be said.

### Crashlog:
https://hastebin.com/ayoxefepen.rb

### Versions & Modlist
Forge: 31.2.19
IE: 0.15-103
Issue occurs even with only IE installed

**Comment by malte0811** [comment]
Fixed in ca8d28c
