### ISSUE TITLE
[1.15.2] Two Pages with Tables in Manual causes "ghost" page between them.

### ISSUE THREAD

**Issue by TwistedGate** [BluSunrize/ImmersiveEngineering#4054]
### Description of the issue:
Having two pages which contain a table each back-to-back causes an empty page to apear between them, no matter the tables content/size

![1](https://user-images.githubusercontent.com/31029668/86527899-93646b80-bea3-11ea-9c36-af73a195a89b.png)
![2](https://user-images.githubusercontent.com/31029668/86527901-93fd0200-bea3-11ea-8cc2-93a627042255.png)
![3](https://user-images.githubusercontent.com/31029668/86527902-94959880-bea3-11ea-8f40-850947c9c7e9.png)

### Versions & Modlist
0.15-103-40a7f41c
(Dev enviroment)

**Comment by malte0811** [comment]
Resolved on discord: user error combined with bugs in the old text splitter implementation.
