### ISSUE TITLE
[1.15.2] Industrial Hemp Seeds doesn't appear to drop from grass at all.

### ISSUE THREAD

**Issue by SCP0429Teemo** [BluSunrize/ImmersiveEngineering#4059]
Description of the issue:
As the title says, Industrial Hemp Seeds doesn't appear to drop from grass/tallgrass at all.

Versions
IE: 0.15-103
Forge: 31.2.30
MC: 1.15.2
mods: IE
Hope it can get fixed. :)

**Comment by mindforger** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/4046

always check closed issues too ;)

**Comment by malte0811** [comment]
As noted by @mindforger, this is a duplicate of #4046. Fixed for the next IE release.
