### ISSUE TITLE
Blast Furnace, piping in fuel...

### ISSUE THREAD

**Issue by therealericbj** [BluSunrize/ImmersiveEngineering#406]
Before version 0.5.4, I was piping steel ingots out the side and iron ingots and coal coke blocks in the side.

Since updating to 0.5.4 the piping in of coal coke blocks no longer works.

I checked the book to see if there was any information regarding piping things in and out of the Blast Furnace, couldn't find anything.

Is this change an error or by design?

Could you please point out what I am doing wrong?

Thanks.

**Comment by BluSunrize** [comment]
It works in my current local environment, so whatever the bug is, it's probably fixed for 0.6 ^^
