### ISSUE TITLE
[1.15.2] [0.15-105 #12] Feedthough Insulators Not Being Created

### ISSUE THREAD

**Issue by DeadlySwede** [BluSunrize/ImmersiveEngineering#4060]
First noticed this with redstone wire connectors but tried it with wire connectors and they didn't create a feedthrough insulators either. As a test, I tried creating feedthrough insulators using redstone, LV, and MV wire connectors on both sides of wood plank and stone blocks. 

Redstone wire connectors "kind of" work if you set one to output and one to input since the block gets redstone signal from the output connector which is picked up by the input connector on the other side but you only get one color and one direction doing it that way.

Test Server Jenkins Build 12

Minecraft 1.15.2
Forge 31.2.9
Titanium 2.4.1
Immersive Engineering 0.15-105-ccc47249
Transport 1.15.2-2.3.0
AutoRegLib 1.5-40
Quark r2.1-244
Just Enough Items 6.0.0.4

VoxelMap 1.9.20

**Comment by malte0811** [comment]
It works fine for me. I assume you right-clicked on the connectors with a hammer to form the multiblock?

**Comment by DeadlySwede** [comment]
Never mind. :-)
Yes, they work so you can close this one. Had never thought of using them them before (usually just punch a hole) and I tried "r-ing tfm" but it didn't mention anything about multiblock or hammers. Although the animation should have given it away.

**Comment by DeadlySwede** [comment]
Closing as not an issue.
