### ISSUE TITLE
[1.14.4] Possible oddball RedstoneConnectorScreen crash. (NullPointerException)

### ISSUE THREAD

**Issue by TwistedGate** [BluSunrize/ImmersiveEngineering#4063]
### Description of the issue:
Making a redstone contraption using IE wires, went on one of the RW connectors with a screwdriver to change it's channel and suddenly the game crashed.

I've tried to reproduce it just with IE but couldnt get it to trigger again, thus i don't know if it just an oddball crash or if it can be caused consistently.

I did have slight up-left mouse movement while rightclicking the connector with the screwdriver.

### Crashlog:
[Gist](https://gist.github.com/TwistedGate/f015e48420cb86072c9ee2bb459b2079)

### Versions & Modlist
`Forge: 28.2.18`
`IE: 0.14-102`

**Comment by adrianodidi** [comment]
my biodiesel generator does not turn on because the lever can not connect on it so I can turn it on I'm in the latest version of immersive-engineering on 1.15.2 and i've tried several things and not one was

**Comment by TwistedGate** [comment]
> 
> 
> my biodiesel generator does not turn on because the lever can not connect on it so I can turn it on I'm in the latest version of immersive-engineering on 1.15.2 and i've tried several things and not one was

Make your own issue lol Yours is completely unrelated to this one.

**Comment by TwistedGate** [comment]
> my biodiesel generator does not turn on because the lever can not connect on it so I can turn it on I'm in the latest version of immersive-engineering on 1.15.2 and i've tried several things and not one was

That is completely unrelated to this issue, please make a new one and don't just comment on other peoples issues.

**Comment by TwistedGate** [comment]
Closing this myself, unable to cause it again.
