### ISSUE TITLE
[1.12.2] Assembler Throws NullPointerException

### ISSUE THREAD

**Issue by sadlyalive** [BluSunrize/ImmersiveEngineering#4064]
After the assembler was finalized in a server (BisectHosting), upon rejoining the console began listing the following:

- [Server] Server thread/ERROR Failed to load data for block entity immersiveengineering:assembler
- [Server] INFO java.lang.NullPointerException: null
- [Server] Server thread/ERROR A TileEntity immersiveengineering:assembler(blusunrize.immersiveengineering.common.blocks.metal.TileEntityAssembler) has thrown an exception during loading, its state cannot be restored. Report this to the mod author

The assembler's blocks (each block appears as an individual, correctly sized standalone assembler) can be broken but do not drop corresponding blocks used to create the multi-block structure. It appears as the following image:

![image](https://user-images.githubusercontent.com/44485528/87215664-a85b5780-c306-11ea-9d5e-79b090e9efa7.png)

The issue persists in singleplayer, where the assembler begins to appear corrupted after interacted upon and reloading the world. Note that the assembler appears functional prior to reloading the world, but a small freeze/lag spike is experienced every time the assembler's interface is accessed. If the assembler's interface was never opened, reloading the world reverts the assembler's multiblock model into the "unhammered" multi-block structure.

The assembler functions optimally and as intended when no other mods are present. (Could the assembler conflict with CraftTweak due to custom recipes? It seems the assembler is the only structure that experienced such an issue thus far, though there are people who have used both simultaneously with little confliction)

The server uses the latest/recommended 1.12.2 Forge (14.23.5.2854) and 1.12.2 Immersive Engineering (0.12-98).
Additional information (including other mods and their versions): https://pastebin.com/acLtEFWV

Brief thanks to the developers and contributors of this Github and mod; it's very enjoyable and detailed!

**Comment by sadlyalive** [comment]
After hours of testing different combinations of mods, I've come to the conclusion that this issue is caused by Forgotten Items (along with its Tschipplib dependency). I'm not sure exactly why this is, but I will continue to try different versions of Forgotten Items and Tschipplib to see if the issue resolves itself.

**Comment by BluSunrize** [comment]
Good luck with that!

1.12 is no longer being supported.

**Comment by sadlyalive** [comment]
That's a shame. If anyone else comes across this issue, simply update your Forgotten Items and Tschipplib to the latest version. The assembler functions correctly but the small lag spike is still present. It's a very minor inconvenience worth having for the coexistence of both mods.
