### ISSUE TITLE
[mc 1.15.2] minecraft bees are confused by wooden posts

### ISSUE THREAD

**Issue by WebDragon** [BluSunrize/ImmersiveEngineering#4065]
### Description of the issue:
Every single wooden post I have, just about, has a bee flying straight into it, that is very difficult to dislodge from its intent to fly straight at the post -- shuffle them to the side and they continue flying straight at the post from the west instead of the north, etc, _even if you poke them and they get angry_.

### Versions & Modlist
Forge 31.2.31
ImmersiveEngineering 0.15-103

additional mods https://pastebin.com/9PfnDGp1 . couldn't seem to get F3+C to generate a crashlog so I took this list from the most recent. Forge has been updated since then to the above mentioned version.

Personally I preferred the Forestry bees -- these new bees the size of a small terrier, are themselves terrifying. :D

**Comment by WebDragon** [comment]
![2020-07-11_12 30 09](https://user-images.githubusercontent.com/1612570/87229396-a1b7f900-c375-11ea-85c5-b3f2935280bf.png)
![2020-07-11_12 30 19](https://user-images.githubusercontent.com/1612570/87229397-a2508f80-c375-11ea-8b4a-36e0c6fa903b.png)
two shots of an angry bee still heading straight at the post instead of attacking me

**Comment by malte0811** [comment]
Fixed in fa42f2b
