### ISSUE TITLE
[1.16.1] random generation crash

### ISSUE THREAD

**Issue by ArmelClo** [BluSunrize/ImmersiveEngineering#4067]
i play in my world but every 5 min my games crash
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 7/12/20 7:59 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at blusunrize.immersiveengineering.api.excavator.MineralVein.writeToNBT(MineralVein.java:85) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.common.IESaveData.func_189551_b(IESaveData.java:108) ~[?:?] {re:classloading}
	at net.minecraft.world.storage.WorldSavedData.func_215158_a(WorldSavedData.java:44) ~[?:?] {re:classloading}
	at net.minecraft.world.storage.DimensionSavedDataManager.func_212775_b(DimensionSavedDataManager.java:125) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerWorld.func_73042_a(ServerWorld.java:700) ~[?:?] {re:classloading,xf:fml:immersiveengineering:IE block update callback}
	at net.minecraft.world.server.ServerWorld.func_217445_a(ServerWorld.java:685) ~[?:?] {re:classloading,xf:fml:immersiveengineering:IE block update callback}
	at net.minecraft.server.MinecraftServer.func_213211_a(MinecraftServer.java:533) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:76) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$8389/1452039461.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1448266872 bytes (1381 MB) / 4077912064 bytes (3889 MB) up to 8112832512 bytes (7737 MB)
	CPUs: 12
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8704m -Xms256m -XX:PermSize=256m
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.63.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.63.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.3-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.63.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.63.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.16.1-32.0.63.jar fml TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.63
	FML Language Providers: 
		javafml@32.0
		minecraft@1
	Mod List: 
		forge-1.16.1-32.0.63-client.jar Minecraft {minecraft@1.16.1 DONE}
		Ma-Enchants-1.16.1-3.2.1.jar Ma Enchants {ma-enchants@1.16.1-3.2.1 DONE}
		ImmersiveEngineering-0.16-106.jar Immersive Engineering {immersiveengineering@0.16-106 DONE}
		BiomesOPlenty-1.16.1-11.0.0.373-universal.jar Biomes O' Plenty {biomesoplenty@1.16.1-11.0.0.373 DONE}
		valhelsia_structures-16.0.1.jar Valhelsia Structures {valhelsia_structures@16.0.1 DONE}
		dungeons-plus-1.16.1-1.0.2.jar Dungeons Plus {dungeons_plus@1.0.2 DONE}
		jei-1.16.1-7.0.0.6.jar Just Enough Items {jei@7.0.0.6 DONE}
		Mekanism-1.16.1-10.0.0.423.jar Mekanism {mekanism@10.0.0 DONE}
		BetterCaves-1.16.1-1.0.jar YUNG's Better Caves {bettercaves@1.16.1-1.0 DONE}
		CTM-MC1.16.1-1.1.0.1.jar ConnectedTexturesMod {ctm@MC1.16.1-1.1.0.1 DONE}
		CookingForBlockheads_1.16.1-9.0.0.jar Cooking for Blockheads {cookingforblockheads@9.0.0 DONE}
		citadel-1.2.0.jar Citadel {citadel@1.2.0 DONE}
		rats-6.0.3-1.16.1.jar Rats {rats@6.0.3 DONE}
		StorageDrawers-1.16.1-8.0.0.jar Storage Drawers {storagedrawers@1.16.1-8.0.0 DONE}
		elevatorid-1.16.1-1.7.2.jar Elevator Mod {elevatorid@1.16.1-1.7.2 DONE}
		randompatches-1.16.1-1.21.2.1.jar RandomPatches {randompatches@1.16.1-1.21.2.1 DONE}
		MekanismTools-1.16.1-10.0.0.423.jar Mekanism: Tools {mekanismtools@10.0.0 DONE}
		simpleplanes-1.16.1-2.0.3.0.jar Simple Planes {simpleplanes@2.0.3.0 DONE}
		MekanismGenerators-1.16.1-10.0.0.423.jar Mekanism: Generators {mekanismgenerators@10.0.0 DONE}
		CraftTweaker-1.16.1-7.0.0.3.jar CraftTweaker {crafttweaker@7.0.0.3 DONE}
		forge-1.16.1-32.0.63-universal.jar Forge {forge@32.0.63 DONE}
		Waddles-1.16.1-0.8.7.jar Waddles {waddles@1.16.1-0.8.7 DONE}
		AppleSkin-mc1.16.1-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
		FastLeafDecay-v23.jar FastLeafDecay {fastleafdecay@v23 DONE}
		structure-gel-api-1.16.1-1.1.1.jar Structure Gel API {structure_gel@1.1.1 DONE}
		ironchest-1.16.1-11.0.1.jar Iron Chests {ironchest@1.16.1-11.0.1 DONE}
	Player Count: 1 / 8; [ServerPlayerEntity['Zolkenn'/324, l='ServerLevel[New World]', x=162.02, y=67.80, z=-280.58]]

**Comment by BluSunrize** [comment]
Please follow the issue template and put your crashlog on pastebin.

**Comment by oPopcandyo** [comment]
Oh man I'm actually having the same issue, I just made an account to report it. Similar if not same Exception in server tick loop error.

**Comment by Gbergz** [comment]
Same issue here.
**Crash-Report:** https://hastebin.com/liduroxule.rb

**What's happening:** Just walked around my world and randomly this crash happened.

**MC-Version:** 1.16.1
**IE Version:** 0.16-106
**Forge Version:** 32.0.63
**Modlist:** https://github.com/The-Nexus-Project/Limitless-3/blob/master/modlist

**Comment by BluSunrize** [comment]
I was wondering if there should be a sanity check there, and I decided against it.
Guess I'll look into it after all.

**Comment by winnetrie83** [comment]
For what it's worth. I just tested IE for 1.16.1 too and i get the same crash.
I have the feeling it isn't completely random. As far as i know it only happens when i discover new chunks. Also most of the time the crash happens when i press the "ESC" key (to open the menu) while i'm exloring new chunks.
The also makes the game not saving anything and all progress you made untill the crash is lost and that's really sad lol!

**Comment by Kataiser9** [comment]
Workaround for now: set "excavator_chance" to 1.0 to make mineral veins not generate in new chunks. Of course I assume this means those chunks will be permanently vein-less, but figured it would be worth sharing.

**Comment by winnetrie83** [comment]
> Workaround for now: set "excavator_chance" to 1.0 to make mineral veins not generate in new chunks. Of course I assume this means those chunks will be permanently vein-less, but figured it would be worth sharing.

I thought mineral veins are only created once you probe for them.

**Comment by BluSunrize** [comment]
> I thought mineral veins are only created once you probe for them.

Nope, not anymore. The new mineral system runs at worldgen

**Comment by BluSunrize** [comment]
Issue fixed by
https://github.com/BluSunrize/ImmersiveEngineering/commit/5bdb77fefbf58c4145c9d89698adf083ff9ae905

Next release will resolve this.
