### ISSUE TITLE
[1.15.2] Connected textures not working

### ISSUE THREAD

**Issue by hampus074** [BluSunrize/ImmersiveEngineering#4068]
Like the title says no connected textures work. I do not know if this is an optifine issue or an IE issue but i suspect IE since the blocks from vanilla minecraft have connected textures. I know it doesn't really affect gameplay in any way but i just remember how nice it looked in earlier versions. 

[Forge] 1.15.2 - 31.2.31
[IE] 0.15-105
[Optifine] 1.15.2_HD_U_G1_pre30

**Comment by BluSunrize** [comment]
IE has no connected textures.
