### ISSUE TITLE
Crash upon opening Power Generation tab in Engineers' manual

### ISSUE THREAD

**Issue by huntzilla360c** [BluSunrize/ImmersiveEngineering#4069]
1: open Engineers manual
2: click power generation
3: *STOPS*

### Crashlog:
https://pastebin.com/TrK1is9E

### Versions & Modlist
Minecraft 1.16.1
Forge: 32.0.63
MODPACK:   https://www.curseforge.com/minecraft/modpacks/tnp-limitless-3/relations/dependencies

**Comment by huntzilla360c** [comment]
[crash-2020-07-12_18.55.31-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4909796/crash-2020-07-12_18.55.31-client.txt)

crashed upon opening a different tab

**Comment by bombbad** [comment]
I can attest it is the same on most tabs. and if it allows you to cycle through it, it will crash at some point pretty quick, but will NOT crash the server or boot anyone else, it seems to be client side only.

**Comment by bombbad** [comment]
here is my crash report on a different tab
[crash-2020-07-12_18.57.25-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4910037/crash-2020-07-12_18.57.25-client.txt)

**Comment by malte0811** [comment]
"Fixed" in c590a80a6509e85bacef82802b603c0035173328. I think this is actually a Forge bug, I'll open an issue on their repo later today.
