### ISSUE TITLE
Game crash on Reading Book

### ISSUE THREAD

**Issue by Tyheam** [BluSunrize/ImmersiveEngineering#4070]
I've searched through the hub to see if this had been reported, but i couldn't find any results.

I booted the mod up with a list of mods and it was working well until i created and read the book.
I was advised on the discord to try it with just JUI and even on it's own and i still got the same error
I've llinked the Crash Report that used just the IE Mod, https://pastebin.com/cVpKj4Na

I'm playing on 1.16.1 with Forge version 32.0.63

**Comment by BluSunrize** [comment]
You clearly didn't search, given that the issue reported immediately before yours is the same =P

Duplicate of #4069
