### ISSUE TITLE
[1.15.2] Excavator multi-block does not form.

### ISSUE THREAD

**Issue by Nialith20** [BluSunrize/ImmersiveEngineering#4071]
### Description of the issue:
On multiple creative and survival worlds, on multiple packs (including custom pack with just IE and JEI), I am unable to get the excavator multi-block to form when hitting the heavy engineering block in center front. 

If the center steel block of the bucket wheel is clicked, the bucket wheel does form. I am currently testing other multi blocks
I have made hundreds of these (in 1.12) and it is correctly constructed. 

![2020-07-13_13 58 07](https://user-images.githubusercontent.com/64575056/87263356-f80d6f00-c510-11ea-8be5-f78f862d11b0.png)

![2020-07-13_13 58 13](https://user-images.githubusercontent.com/64575056/87263361-fa6fc900-c510-11ea-9be3-4ca89538fa4a.png)

![2020-07-13_13 58 16](https://user-images.githubusercontent.com/64575056/87263362-fb085f80-c510-11ea-8874-b5827170c141.png)

### Versions & Modlist
Minecraft Version: 1.15.2
forge-31.2.31.
Immersive engineering - -0.15-105. (initially found on 103 updated to see if that resolved) 
JEI - 6.0.212

**Comment by BluSunrize** [comment]
Yeah you built it wrong. RTFM. =P

There is only one heavy engineering block at the back and it's in the center. The one you put in the top left corner needs to be sheemetal.

**Comment by Nialith20** [comment]
OMG! Sorry to waste your time! Thanks so much. I didn't see the recipe had changed.
