### ISSUE TITLE
[1.16.1] Coke oven not working on servers

### ISSUE THREAD

**Issue by darkphan** [BluSunrize/ImmersiveEngineering#4073]
### Description of the issue:
When putting coal/logs into the coke oven there is an error thrown server side

### Crashlog:
This is a snippet of the server log when the error happens [gist][https://gist.github.com/darkphan/1fd9f8d790cf73de06798b1547bfd384]

### Versions & Modlist

IE: ImmersiveEngineering-0.16-106
Forge: 32.0.63

This occurs even when only having IE installed.

**Comment by Maja-dev** [comment]
I can confirm this is also happening on my server to both the oven and furnace.

Happens on both 32.0.63 and 32.0.66

Snippet of the server log using the oven
https://gist.github.com/Maja-dev/376a719519f457a80dacea50d04c25ae

Snippet of the log when using the blast furnace
https://gist.github.com/Maja-dev/f7b838c02daaf5ac59109e247ba5620a

**Comment by BluSunrize** [comment]
Yeah, I reproduced it.
Loading order has changed.
I'm looking into it.

**Comment by LittleCircles** [comment]
Should note that when hoppering in items it crashes server. Not sure if I should make a new post for this or not.

Also put server into crash loop: 

Time: 7/15/20 10:18 PM
Description: Watching Server

java.lang.Error: ServerHangWatchdog detected that a single server tick took 60.00 seconds (should be max 0.05)
	at net.minecraft.server.dedicated.ServerHangWatchdog.run(ServerHangWatchdog.java:39) [?:?] {re:classloading}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251] {}

**Comment by BluSunrize** [comment]
Fixed for next release
