### ISSUE TITLE
[1.12.2] Server Crash - Loading chunk with Excavator running. NPE with getFakePlayer

### ISSUE THREAD

**Issue by AnodeCathode** [BluSunrize/ImmersiveEngineering#4074]
### Description of the issue:
Player has a running excavator powered and operating normally. If the chunk is unloaded (either logoff or moves far enough away), server crashes on reload. NPE on getFakePlayer.

### Crashlog:
https://pastebin.com/LTLmmZzi

### Versions & Modlist
Forge: forge-1.12.2-14.23.5.2847
IE: ImmersiveEngineering-0.12-98

Complete Server Modlist: https://pastebin.com/wkp2M7nL

**Comment by BluSunrize** [comment]
1.12 is no longer receiving any support.
