### ISSUE TITLE
New graphics glitch

### ISSUE THREAD

**Issue by ZAKsPop** [BluSunrize/ImmersiveEngineering#4078]
After updating to the latest 1.15.2 version I started having this issue.
![2020-07-12_22 47 40](https://user-images.githubusercontent.com/62826396/87498436-62abd100-c61d-11ea-9a5a-cff6bb8472e7.png)

**Comment by BluSunrize** [comment]
Reformat your issue with respect to the issue template, or you won't receive any assistance.

**Comment by ZAKsPop** [comment]
I don't care. Fix it if you want to, don't fix it if you don't.  Better yet. Let someone who has a better attitude than you take over the mod. Ever since I have been posting on this and Discord about this mod you have been a total ass.

**Comment by BluSunrize** [comment]
Hey, we literally have an issue template. It explains in detail what info we need from you. You deleted it without following any of its instruction. It's not that difficult and it greatly improves our ability to investigate stuff.

**Comment by BluSunrize** [comment]
I've been unable to reproduce this issue so far.

@ZAKsPop can you reproduce this in a creative test world?

**Comment by ZAKsPop** [comment]
That's OK. I can't either. I installed the 0.15.108 update today and rebuilt the tank but no glitch. Looks fine. Thanks
