### ISSUE TITLE
[1.12.2] Arc Furnace OpenComputers control help?

### ISSUE THREAD

**Issue by SanjivanM** [BluSunrize/ImmersiveEngineering#4079]
I know I can do `var = component.ie_arc_furnace.getElectrode(3).damage` to get the damage of the 3rd electrode, but every time I use that in a lua script, I get this error: 
![image](https://user-images.githubusercontent.com/33943333/87505815-ace18200-c61e-11ea-9f0c-3630fbdfa118.png)

Here's my lua script, the lines prefixed with "--" are commented out, I didn't have an IDE on my test world :P

![image](https://user-images.githubusercontent.com/33943333/87505855-c8e52380-c61e-11ea-9de7-36b613cfb4d0.png)

**Comment by BluSunrize** [comment]
It's crashing when you try to access "component", indicating that "component" is null. That doesn't appear to be an error stemming from IE.
But I also didn't write this integration, so I can't say more on it.
Plus, 1.12 is no longer being supported.
