### ISSUE TITLE
Suggestion: When Using Hammer For Crushing Ores Have It Stay in Crafting Grid Not Got To Your Inventory 

### ISSUE THREAD

**Issue by RoloEdits** [BluSunrize/ImmersiveEngineering#408]
When you use the hammer for making dust from ores can you change it so it stays in the crafting grid instead of returning to the inventory? This causes you to repeatedly to have to place it in there over and over for each operation.

**Comment by BluSunrize** [comment]
Already did that =P

**Comment by RoloEdits** [comment]
I am using version ImmersiveEngineering-0.5.4 but it still does return to my inventory after every operation.

**Comment by BluSunrize** [comment]
Because it's not in 0.5.4, it will be in 0.6 =)

**Comment by RoloEdits** [comment]
OK, thanks, I will wait patiently until then :)
