### ISSUE TITLE
[1.16.1] Crash to desktop well On server

### ISSUE THREAD

**Issue by BedrockLegends** [BluSunrize/ImmersiveEngineering#4080]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
Describe what happens, how it affects your game/gameplay and provide screenshots where possible.
Was flying around on a server and all of sudden it crashed me straight to desktop

### Crashlog:
If your Minecraft instance has crashed, a file will have been generated in the folder `crash-reports` of your minecraft folder. To understand what has happened, we need to know the content of that file. But please don't just put it directly in your report (that makes it hard to read), upload it to a site like [pastebin](http://pastebin.com) or [gist](http://gist.github.com) and put a link in the actuall bug report.
[crash-2020-07-15_14.16.00-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4927488/crash-2020-07-15_14.16.00-client.txt)

[latest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/4927498/latest.log)

[debug.log](https://github.com/BluSunrize/ImmersiveEngineering/files/4927500/debug.log)

### Versions & Modlist
IE and Forge versions are mandatory. *Note that saying "latest" is **not** valid. Always give the proper version number*
Other mods should be listed (with their versions) in a [pastebin](http://pastebin.com) or [gist](http://gist.github.com) upload. The easiest way to get these lists is a crashlog, you may force one with F3+C.
If your game crashed (see above) you may omit the modlist, but IE and Forge version would still be nice.

Forge - 32.0.66
Minecraft 1.16.1

**Comment by BluSunrize** [comment]
Can you reproduce this issue reliably?

Also, can you please edit your post and make it a bit more reable? You left a lot of the explanatory texts in.

**Comment by BedrockLegends** [comment]
Idk if I can reproduce this issue Reliably, I just was flying around a players base and it dump me to desktop

**Comment by BluSunrize** [comment]
Okay, can you maybe still edit your original post? You literally left the paragraph about putting your logs on Pastebin in, and then *didn't put your logs on Pastebin* >_>
