### ISSUE TITLE
cosmic shader bug

### ISSUE THREAD

**Issue by xtrux** [BluSunrize/ImmersiveEngineering#4081]
the cosmic shader in infinity evolved, is bugged out and red, the same issue happens with the sword of the cosmos in any pack for me 
![image](https://user-images.githubusercontent.com/37349120/87595225-372bf380-c6bc-11ea-9f32-b0228e1b9dc5.png)

**Comment by BluSunrize** [comment]
1) You didn't read the contribution guidelines
2) We have not been supporting 1.7.10 for years
3) This is likely a conflict with another mod
