### ISSUE TITLE
[1.15.2] Game Crash on launch, problem with "Render Overlay"?

### ISSUE THREAD

**Issue by maeglin0** [BluSunrize/ImmersiveEngineering#4082]
### Description of the issue:
Game crashes during initial startup, even with only Forge and IE. Game starts just fine without IE. Not sure what exactly the issue is, as minecraft doesn't even properly start before crashing.  Happens consistently, every time I launch the game. 

### Crashlog:
https://pastebin.com/XDvmD3XT

### Versions & Modlist
     Forge:   forge-1.15.2-31.2.31   
     IE: ImmersiveEngineering-0.15-105

**Comment by BluSunrize** [comment]
You are only giving your Java 1GB of memory. Modded Minecraft can't run on that little. You need *at least* 2GB and it may still break with bigger modpacks. Ideally you'll wanna give it 4GB.
