### ISSUE TITLE
[1.16.1] Crash upon creating or loading world

### ISSUE THREAD

**Issue by IronPiston** [BluSunrize/ImmersiveEngineering#4083]
### Description of the issue:
With only IE installed, the game crashes upon loading a world. Creating a world without IE installed, then loading that world still crashes the game. Specifically, the in-game loading bar reaches 100% before crashing to the desktop.

### Crashlog:
[Crashlog](https://paste.ee/p/vlcoo)

### Versions & Modlist
IE: 0.16-106
Forge: 32.0.67

**Comment by BluSunrize** [comment]
Forge version .67 removed the old way to load commands.
The fix from our side is to use hte new event in .67 and raise the minimum Forge version. That'll happen for the next release.


For now, you can temporarily fix this by using Forge version .66

**Comment by BluSunrize** [comment]
Fixed for next release
