### ISSUE TITLE
[1.16.1] Hoppering(with hopper) into coke oven courrpts the world

### ISSUE THREAD

**Issue by LittleCircles** [BluSunrize/ImmersiveEngineering#4084]
Original comment I made about problem: https://github.com/BluSunrize/ImmersiveEngineering/issues/4073#issuecomment-659148147

### Description of the issue:
Hoppering(with hopper) into coke oven courrpts the world

### Crashlog:
First crash [gist](https://gist.github.com/LittleCircles/22dfc13885b8a2c2c42c80c547a61af9)
Last Crash [gist](https://gist.github.com/LittleCircles/3f5e8a5cd42a2d6537d24e7cb340fb32)

### Versions & Modlist
ImmersiveEngineering-0.16-106.jar

Modlist: [gist](https://gist.github.com/LittleCircles/35ac25fa8dc477e50b744648bd2695ea)

**Comment by BluSunrize** [comment]
Same error as #4073, fixed by the same commit
