### ISSUE TITLE
[1.16.1] Crash in engineering workbench

### ISSUE THREAD

**Issue by XITVJ** [BluSunrize/ImmersiveEngineering#4085]
### Description of the issue:
Client crash on hoovering over revolver in engineering workbench, after attaching bayonet. 100% repeatable.

### Crashlog:
https://pastebin.com/fzNgVTU4

### Versions & Modlist
Forge: 32.00.66 (Server and Client)
IE: 0.16-106
Optifine, other Mods and Resourcepack disabled

**Comment by BluSunrize** [comment]
Attribute maps are immutable now, apparently, so we'll have to move over to the map builder here.

I'll look into this.

**Comment by BluSunrize** [comment]
Fixed for next release
