### ISSUE TITLE
Engineer's manual causes a crash

### ISSUE THREAD

**Issue by MinerTomotomo** [BluSunrize/ImmersiveEngineering#4086]
Forge version: 32.0.66
Mod version: 0.16-106

It crashes when I look at the minerals list in the Engineer's Manual.

**Comment by malte0811** [comment]
Presumably a duplicate of #4069. However, as you didn't include *any* useful information I can't actually be certain.  
Still closing this, as "either duplicate or too bad to tell what the actual issue is".
