### ISSUE TITLE
Up up and Away

### ISSUE THREAD

**Issue by Haeschenharakiri** [BluSunrize/ImmersiveEngineering#409]
So today i was Skyhooking up a Wire and at the End it did not stop i just climbed higher and higher.
Than my server kicked me, and when i rejoind i was falling to dead.

I do not have a crash log, and play it in the FTB Infinity modpack.

**Comment by cobra** [comment]
Do you have any further information about this? Can you reproduce it? Which wire did you ride and how was it running? Do you have a screenshot of this particular spot?

**Comment by cobra** [comment]
Cannot reproduce myself, at least not without any further information.
