### ISSUE TITLE
1.16.1 Crash on forge 67 +

### ISSUE THREAD

**Issue by BedrockLegends** [BluSunrize/ImmersiveEngineering#4094]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
Describe what happens, how it affects your game/gameplay and provide screenshots where possible.

Crash as soon as I launch the game

### Crashlog:
If your Minecraft instance has crashed, a file will have been generated in the folder `crash-reports` of your minecraft folder. To understand what has happened, we need to know the content of that file. But please don't just put it directly in your report (that makes it hard to read), upload it to a site like [pastebin](http://pastebin.com) or [gist](http://gist.github.com) and put a link in the actuall bug report.

https://hastebin.com/newizuyopa.rb

### Versions & Modlist
IE and Forge versions are mandatory. *Note that saying "latest" is **not** valid. Always give the proper version number*
Other mods should be listed (with their versions) in a [pastebin](http://pastebin.com) or [gist](http://gist.github.com) upload. The easiest way to get these lists is a crashlog, you may force one with F3+C.
If your game crashed (see above) you may omit the modlist, but IE and Forge version would still be nice.

Forge 32.0.67 +
1.16.1

**Comment by barkerm1031** [comment]
World doesn't even load up, just crashes without warning.

[crash-2020-07-17_11.37.14-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4938972/crash-2020-07-17_11.37.14-server.txt)

**Comment by BedrockLegends** [comment]
Yea the new forge version did a game breaking change with commands

**Comment by barkerm1031** [comment]
so in other words its not supported 100% with most recent forge? lol ill try it on .66 instead lol

It does work on .66

**Comment by BluSunrize** [comment]
Yeah, and this is a duplicate. Please search next time
