### ISSUE TITLE
[1.15.2] Dupe with banner, infinity shaders

### ISSUE THREAD

**Issue by Serega007RU** [BluSunrize/ImmersiveEngineering#4095]
### Description of the issue:
Everything is very simple, you just need to click the RMB (Right Mouse Button) Shader on the banner and you will have infinite shaders and if you click very fast, you can cause server lags

### Crashlog:
There is no crash in this problem

### Versions & Modlist
Forge 1.15.2 - 31.2.31
Immersive Engineering 0.12-98

### Note:
In this video you can see this problem, sorry that it is not in English
https://youtu.be/aMOEDGJSdcw?t=155

**Comment by BluSunrize** [comment]
File a proper report.

**Comment by Serega007RU** [comment]
Please unlock my the previous issue, if you have any other comments on the design, please tell us

**Comment by BluSunrize** [comment]
1.12 is no longer supported

**Comment by Serega007RU** [comment]
That's where we should have started...

**Comment by BluSunrize** [comment]
That would have required you filing an issue with actual detail in it, like a version number, instead of a video in russian ;)

**Comment by Serega007RU** [comment]
If I wrote 1.12.2, it doesn't mean that it doesn't work on other versions.
I edited the issuse header, please check it

Once again, unlock the previous issue, it also belongs to 1.15.2 and works, I will make it out correctly

I am sure that this can work on 1.16.1, unfortunately I can't test it, minecraft crashes as soon as I enter the world. Yes I saw that already other people send issue about this crash
