### ISSUE TITLE
[1.12.2] Dupe with Fluid Pump, infinity iron

### ISSUE THREAD

**Issue by Serega007RU** [BluSunrize/ImmersiveEngineering#4096]
https://youtu.be/2-dZhAXabhE?t=135

**Comment by BluSunrize** [comment]
File a proper report.

**Comment by Serega007RU** [comment]
What difference does it make to you? Isn't it your job to fix bugs in your mod? If you don't want to fix it that's your problem!

**Comment by BluSunrize** [comment]
No, it's not my job. I don't get paid to do this. Malte and me do this for free, in our spare time. The least we can expect from people is that they don't just blatantly ignore the issue template and link me a video in a language I don't understand without any explanation.
