### ISSUE TITLE
New Coke Oven Texture is broken

### ISSUE THREAD

**Issue by DoughnutDev** [BluSunrize/ImmersiveEngineering#41]
It looks like there are two textures over lapping each other http://puu.sh/i92UK/42a0208cd7.png

**Comment by mallrat208** [comment]
It seems to be related to the side of the structure you attempt to form it from.

If on the East or West side it makes a 3 tall, 3 wide, and 5 long structure like in the screenshot there.

If on the North or South it makes the standard 3x3x3 Coke Oven that was in before, just with a new texture.

**Comment by DoughnutDev** [comment]
It is just a code error that can be fixed I am sure blu knows how to fix it.

**Comment by BluSunrize** [comment]
Yeah, I know how to fix that. That's what I get for not checking all permutations ^^"
