### ISSUE TITLE
[suggestion] Improvements to long-distance energy transport using transformers as range boosters

### ISSUE THREAD

**Issue by beckNeard** [BluSunrize/ImmersiveEngineering#410]
This is related to the suggestions in #362 so I apologize if it was more appropriate to post there but I didn't want to potentially derail.

The way I see it, from my limited experience playing a private modpack that uses IE(0.5.4) and Ender IO as core tech mods, there are two main problems with the energy system:
1) transformers are essentially useless;
2) power lines can only go a limited distance before energy loss renders them inoperable.

Now, I like the IE power system, I like energy loss, but I would also like to run absurdly long power lines through my world and get some RF on the other end. So this idea involves having my cake and eating it too.

What if HV transformers, in addition to their "conversion" function (which is easily sidestepped to begin with) also gained the function of a kind of range booster for HV wires? There could be several ways to do this:
1) any HV power lines originating from a transformer are treated as X length shorter - essentially complete energy loss negation with enough properly spaced transformers;
2) HV lines from transformers suffer only a fraction of normal energy loss for the entire trip;
3) a combination of the above - HV lines from transformers suffer reduced energy loss for X length of wire, then energy loss continues normally, so properly spaced transformers would be required on a very long line.

I'm suggesting this as an alternative to the wire burnout feature. I feel like energy loss already presents itself as an obstacle - one that presently has no solution aside from using some RF teleportation method from a different mod - so adding another obstacle that is then "solved" with the use of transformers feels unattractive to me. However, I see no reason why both features can't coexist and if this extra function seems inappropriate for transformers, perhaps it could be done by an entirely new block?

**Comment by BluSunrize** [comment]
Yeah this should have gone in the original thread, since we discussed a lot of that already.
Also transformers aren't useless anymore, since i have already added wire burning and overload. I just haven't rebalanced transferrates.
