### ISSUE TITLE
ticking block

### ISSUE THREAD

**Issue by sgreen75** [BluSunrize/ImmersiveEngineering#4100]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
Crashes game on load singleplayer

### Crashlog:
If your Minecraft instance has crashed, a file will have been generated in the folder `crash-reports` of your minecraft folder. To understand what has happened, we need to know the content of that file. But please don't just put it directly in your report (that makes it hard to read), upload it to a site like [pastebin](http://pastebin.com) or [gist](http://gist.github.com) and put a link in the actuall bug repor
[crash-2020-07-18_10.15.28-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4941867/crash-2020-07-18_10.15.28-server.txt)
[crash-2020-07-18_09.09.18-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4941868/crash-2020-07-18_09.09.18-server.txt)
[crash-2020-07-18_10.03.41-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4941869/crash-2020-07-18_10.03.41-server.txt)

t.

### Versions & Modlist
atm6 0.15b forge 32.0.66

### Lastly (you may delete this from the report itself)
Please, for the love of all that is voxelbased, **read the contribution guidelines. They are linked to the right in the message box.**
When reporting issues, these are crucial, and the team withholds the right to close an issue for the plain stupidity of not reading and adhering to them.

Thank you for reporting issues, without people reporting them, they wouldn't get fixed. You're helping contribute to this mod and that is much appreciated <3

**Comment by BluSunrize** [comment]
You're using an outdated version of IE.
