### ISSUE TITLE
1.16 Fabulous Graphics allow seeing through the world

### ISSUE THREAD

**Issue by pupnewfster** [BluSunrize/ImmersiveEngineering#4102]
### Description of the issue:
In 1.16 when setting graphics to fabulous, having Immersive Engineering installed causes water and ice (and maybe other blocks as well) to allow you to see through the world.
![2020-07-18_14 15 28](https://user-images.githubusercontent.com/1203288/87859228-8adb4e80-c901-11ea-9caa-42207d77b2ec.png)
![2020-07-18_14 16 58](https://user-images.githubusercontent.com/1203288/87859230-8ca51200-c901-11ea-9a2e-8b388e9b58f9.png)

### Crashlog:
There is no crash but my latest log is spammed with:
`[net.minecraft.client.renderer.GlDebugTextUtils/]: OpenGL debug message, id=1282, source=API, type=ERROR, severity=HIGH, message=GL_INVALID_OPERATION error generated. Depth formats do not match.`

I trimmed a lot of the spam out of my latest log as gist was having issues uploading it and here is what is left https://gist.github.com/pupnewfster/fa906b7bc5ac3308a809bf2cfe522e3a

### Versions & Modlist
MC: 1.16.1
Forge: 32.0.69
IE: 0.16-109
No other mods installed

**Comment by malte0811** [comment]
Forge issue, see https://github.com/MinecraftForge/MinecraftForge/issues/6995. Disable `stencilBufferEnabled` in the IE config for now if you want to use IE with fabulous graphics. This may cause rendering issues with the bottling machine, but shouldn't affect anything else.
