### ISSUE TITLE
[1.16] Two crashes I've noticed so far

### ISSUE THREAD

**Issue by Awesomespore** [BluSunrize/ImmersiveEngineering#4103]
### Description of the issue:
I'm hoping to help out with the 1.16 version by pointing out two different crash conditions that I have encountered in said version. The two crashes seem to be caused by loading recipes for the coke oven, and something to do with loading an ore deposit somewhere.

### Crashlog:
I can't provide a crash log, since it'll be buried somewhere in the logs folder and I'm not sure what one it is, but I know that in the two crashes I've encountered, the crash log mentions:
1. loading recipes for the coke oven (the game would crash immediately upon joining the world)
2. something about an ore deposit (this was while I was in the nether dimension, and the game would crash after a certain amount of time, rolling back the world to as it was when I last joined the world)

### Versions & Modlist
Mod version:   ImmersiveEngineering-0.16-106
Forge version: _unsure_
Mod list:
![image](https://user-images.githubusercontent.com/59407684/87863857-4d83c900-c9b4-11ea-8b06-37ad957b428f.png)
(Also OptiFine)

**Comment by Awesomespore** [comment]
I am yet to see if I encounter similar issues in the latest update (ImmersiveEngineering-0.16-109)

**Comment by Awesomespore** [comment]
So far so good, I haven't gotten any crashes thus far.

**Comment by malte0811** [comment]
Both crashes are fixed in build 109.

**Comment by Awesomespore** [comment]
Yep, seems to be the case!
