### ISSUE TITLE
Railgun attempted use causes crash (1.16.1)

### ISSUE THREAD

**Issue by aridhol** [BluSunrize/ImmersiveEngineering#4104]
### Before reporting:
I saw a very old, similar report, but it was from an old version, so its a new issue (though it could be an old issue reborn, as these things happen..)

### Description of the issue:
I attempt to charge the railgun, only ammo in my inventory is steel rods, as soon as its charged and I release: it crashes immediately. When I load back in, the gun has not fired, the steel rods are all accounted for. 

### Crashlog:
https://pastebin.com/DLgesgbC

### Versions & Modlist
IE version: ImmersiveEngineering-0.16-109.jar
Forge: forge-32.0.69
Full modlist: https://pastebin.com/Qrcvdexg

**Comment by BluSunrize** [comment]
Bug reproduced on 1.16.
Seems to not be present in 1.14 or 1.15.

**Comment by BluSunrize** [comment]
Found the reason. Our data attribute for the shooter wasn't being registered.

I fixed this, I'm just holding off on pushing it, because we may be making changes to our versioning structure.

**Comment by aridhol** [comment]
I think that the Chem thrower might have the same problem? Or it could be different?

Same conditions, here's the paste...
https://pastebin.com/8cQ3a9N2

**Comment by BluSunrize** [comment]
same issue, same fix!
