### ISSUE TITLE
[1.16.1] loading into a world I get send back to main menu

### ISSUE THREAD

**Issue by benedictWolf** [BluSunrize/ImmersiveEngineering#4106]
On Version .106 of IE everything worked fine. But after updating to .109 I get send back to the main menu when trying to load in a world, it doesn’t matter if it’s a new one or a pre-existing. I tried using different forge versions : .67; .68; .69; the issue is still the same. 
Modlist:
Colytra 
Caelus API
JEI
Curious API
IE
Engineers Decor
Curious Shulker Boxes

**Comment by BluSunrize** [comment]
Please provide your latest.log file from this incident. It should have relevant information.

Upload it to gist or pastebin and link it here.

**Comment by benedictWolf** [comment]
> Please provide your latest.log file from this incident. [...]

I think the curious API causes the crash. I tried replicating it without it and I had no crash.

**Comment by BluSunrize** [comment]
That's good intel, but I personally would still appreciate looking at the log, to maybe give some extra info that you can then report to the Curious devs =)

**Comment by AcaliaDesu** [comment]
Sorry for the delay, log included. LMK if there's anything else you could use.
[latest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/4944199/latest.log)

**Comment by BluSunrize** [comment]
Clsoed, probably irrelevant
