### ISSUE TITLE
[1.16.1] Potential crash, might be from mod conflicts though

### ISSUE THREAD

**Issue by AcaliaDesu** [BluSunrize/ImmersiveEngineering#4108]
So to start, I'm playing with the "All the Mods 6" modpack, so it could very well be a mod conflict. But I figured i'd post it all here just in case.

Here's what happened, I just crafted the Alloy Kiln thing (the 2x2x2 alloy forge thingy). Put in some Silver Ingots, some Gold Ingots (was trying to make the Electrum Ingots), but I didn't have any coal/fuel in at all yet... Server crashed the moment i put in the second ingot type. If I load that chunk now the server crashes instantly. Server runs fine if that chunk doesn't load up (so my friends can at least play if i don't log on).

If there's anything I can do to fix this in the mean time please let me know. 

Crash log:
[crash-2020-07-19_11.56.19-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/4944041/crash-2020-07-19_11.56.19-server.txt)

**Comment by malte0811** [comment]
Update IE, this is fixed in build 109.
