### ISSUE TITLE
[1.16.1] Fluid pipe crash when trying to slurp liquid

### ISSUE THREAD

**Issue by Glitchster00** [BluSunrize/ImmersiveEngineering#4110]
placing a pipe connected to a powered pump with a Redstone signal the pipe was next to a water source block and as soon as the pipe was placed the game crashed any time the chunk is loaded the game crashes 

### Crashlog:
Initial crash:
https://pastebin.com/pDXcDY1C
Subsequent crashes:
https://pastebin.com/hDd6aD7E
https://pastebin.com/surfWeGm

### Versions & Modlist
https://pastebin.com/xbAk1GdJ

**Comment by BluSunrize** [comment]
This error is likely to be present in all versions (though I haven't tested yet).
The code in question does not account for an empty list of connected fluid handlers.
I'll look into this.
