### ISSUE TITLE
Garden Cloche: Lose items if break with pickaxe [1.12.2]

### ISSUE THREAD

**Issue by jvsdr** [BluSunrize/ImmersiveEngineering#4112]
### Description of the issue:
I'm losing my items (dirt, seed and fertilizer) if I break the Garden Cloche with a pickaxe (normal diamond pickaxe).

I've uploaded a video on YouTube to proof the bug: [https://www.youtube.com/watch?v=t2SkI2SDGtk](url)

### Crashlog:
No crashlog.

### Versions & Modlist
ActuallyAdditions-1.12.2-r151-2.jar
ae2stuff-0.7.0.4-mc1.12.2.jar
angelRingToBauble-1.12-0.3.1.50+d4e654e.jar
AppleSkin-mc1.12-1.0.14.jar
appliedenergistics2-rv6-stable-7.jar
armoryexpansion-2.0.0-alpha.jar
Aroma1997Core-1.12.2-2.0.0.2.b167.jar
Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.b97.jar
AromaBackup-1.12.2-3.0.0.0.b134.jar
autopackager-1.12.jar
Avaritia's Complement-1.12.2-1.4.jar
Avaritia-1.12.2-3.3.0.33-universal.jar
Avaritiaddons-1.12.2-1.1.jar
avaritiaio-1.4.jar
Baubles-1.12-1.5.2.jar
baubley-heart-canisters-1.12.2-2.0.3.jar
bdlib-1.14.3.12-mc1.12.2.jar
BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar
BetterFps-1.4.8.jar
BiblioCraft[v2.4.5][MC1.12.2].jar
BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar
Bookshelf-1.12.2-2.3.590.jar
Botania r1.10-363.jar
BrandonsCore-1.12.2-2.4.18.210-universal.jar
buildcraft-all-7.99.24.6.jar
Chameleon-1.12-4.1.3.jar
ChestTransporter-1.12.2-2.8.8.jar
ChickenChunks-1.12.2-2.4.2.74-universal.jar
chickens-6.1.0.jar
Chisel-MC1.12.2-1.0.2.45.jar
Clumps-3.1.2.jar
CodeChickenLib-1.12.2-3.2.3.358-universal.jar
CoFHCore-1.12.2-4.6.6.1-universal.jar
CoFHWorld-1.12.2-1.4.0.1-universal.jar
conarm-1.12.2-1.2.5.9.jar
Controlling-3.0.9.jar
CookingForBlockheads_1.12.2-6.5.0.jar
CraftTweaker2-1.12-4.1.20.581.jar
CTM-MC1.12.2-1.0.2.31.jar
Cucumber-1.12.2-1.1.3.jar
CustomMainMenu-MC1.12.2-2.0.9.1.jar
DarkUtils-1.12.2-1.8.230.jar
Decocraft-2.6.3_1.12.2.jar
dimcakerblt-1.12.2-1.0.jar
Draconic-Evolution-1.12.2-2.3.25.351-universal.jar
EnchantingTable-1.12-1.1.3.jar
EnderCore-1.12.2-0.5.76.jar
EnderIO-1.12.2-5.2.59.jar
EnderStorage-1.12.2-2.4.6.137-universal.jar
endertanks-1.12.0-1.6.8.jar
energyconverters_1.12.2-1.3.7.30.jar
environmentaltech-1.12.2-2.0.20.1.jar
ExtraCells-1.12.2-2.6.5.jar
extrautils2-1.12-1.9.9.jar
ExtremeReactors-1.12.2-0.4.5.67.jar
FarmingForBlockheads_1.12.2-3.1.28.jar
FastLeafDecay-v14.jar
fluxnetworks-1.12.2-4.0.15-32.jar
foamfix-0.10.10-1.12.2.jar
Forgelin-1.8.4.jar
ForgeMultipart-1.12.2-2.6.2.83-universal.jar
FTBLib-5.4.7.2.jar
FTBUtilities-5.4.1.129.jar
Galacticraft-Planets-1.12.2-4.0.2.280.jar
GalacticraftCore-1.12.2-4.0.2.280.jar
GunpowderLib-1.12.2-1.0.jar
hatchery-1.12.2-2.2.2.jar
Headcrumbs-1.12.2-2.0.5.17.jar
Hwyla-1.8.26-B41_1.12.2.jar
ieclochecompat-2.1.7-dev.454.jar
**ImmersiveCables-1.12.2-1.3.2.jar**
**ImmersiveEngineering-0.12-98.jar**
**immersivepetroleum-1.12.2-1.1.9.jar**
industrialforegoing-1.12.2-1.12.13-237.jar
InGameInfoXML-1.12.2-2.8.2.94-universal.jar
IntegrationForegoing-1.12.2-1.10.jar
InventoryTweaks-1.64+dev.151.jar
IronBackpacks-1.12.2-3.0.8-12.jar
ironchest-1.12.2-7.0.72.847.jar
jei_1.12.2-4.15.0.297.jar
journeymap-1.12.2-5.7.1.jar
just-enough-harvestcraft-1.12.2-1.7.2.jar
JustEnoughEnergistics-1.12.2-1.0.8.jar
JustEnoughReactors-1.12.2-1.1.3.61.jar
JustEnoughResources-1.12.2-0.9.2.60.jar
LootBags-1.12.2-2.5.8.5.jar
LunatriusCore-1.12.2-1.2.0.42-universal.jar
Mantle-1.12-1.3.3.55.jar
matc-1.0.1-hotfix.jar
mcjtylib-1.12-3.5.4.jar
MicdoodleCore-1.12.2-4.0.2.280.jar
minicoal-1.12.2-1.0.jar
MmmMmmMmmMmm-1.12-1.14.jar
MobGrindingUtils-0.3.13.jar
modtweaker-4.0.18.jar
More-Planets-1.12.2-2.1.12-GC251.jar
morechickens-1.12.2-3.2.0.jar
moreoverlays-1.15.1-mc1.12.2.jar
Morpheus-1.12.2-3.5.106.jar
MouseTweaks-2.10-mc1.12.2.jar
MTLib-3.0.6.jar
mystagradcompat-1.2.jar
mystcraft-1.12.2-0.13.7.06.jar
MysticalAgradditions-1.12.2-1.3.2.jar
MysticalAgriculture-1.12.2-1.7.5.jar
Neat 1.4-17.jar
NetherPortalFix_1.12.1-5.3.17.jar
noRecipeBook_v1.2.2formc1.12.2.jar
OpenBlocks-1.12.2-1.8.1.jar
OpenModsLib-1.12.2-0.12.2.jar
OptiFine_1.12.2_HD_U_F5.jar
Pam's HarvestCraft 1.12.2zg.jar
Patchouli-1.0-21.jar
Placebo-1.12.2-1.6.0.jar
PTRLib-1.0.4.jar
QuantumStorage-1.12-4.7.0.jar
rangedpumps-0.5.jar
reauth-3.6.0.jar.disabled
RebornCore-1.12.2-3.19.4.529-universal.jar
RebornStorage-1.12.2-3.3.4.1.jar
RedstoneArsenal-1.12.2-2.6.6.1-universal.jar
RedstoneFlux-1.12-2.1.1.1-universal.jar
refinedstorage-1.6.16.jar
refinedstorageaddons-0.4.5.jar
refined_avaritia-1.12.2-2.6.jar
rftools-1.12-7.73.jar
rftoolsdim-1.12-5.71.jar
shetiphiancore-1.12.0-3.5.9.jar
Simple-Void-World-1.12-1.2.0.9-universal.jar
simplelogin-1.2.4-beta+build127.jar
SimplyJetpacks2-1.12.2-2.2.14.67.jar
Snad-1.12.1-1.7.09.16a.jar
SolarFluxReborn_1.12.2-12.3.8.jar
SteveKunG's-Lib-1.12.2-1.1.6.jar
stg-1.12.2-1.2.3.jar
StorageDrawers-1.12.2-5.4.2.jar
TConstruct-1.12.2-2.13.0.183.jar
tesla-core-lib-1.12.2-1.0.17.jar
ThermalCultivation-1.12.2-0.3.6.1-universal.jar
ThermalDynamics-1.12.2-2.5.6.1-universal.jar
ThermalExpansion-1.12.2-5.5.7.1-universal.jar
ThermalFoundation-1.12.2-2.6.7.1-universal.jar
tinkersjei-1.2.jar
TinkerToolLeveling-1.12.2-1.1.0.jar
tinyprogressions-1.12.2-3.3.34-Release.jar
Toast Control-1.12.2-1.8.1.jar
torchmaster_1.12.2-1.8.1.81.jar
twilightforest-1.12.2-3.10.1013-universal.jar
UniDict-1.12.2-2.9.6.jar
valkyrielib-1.12.2-2.0.20.1.jar
WailaHarvestability-mc1.12-1.1.12.jar
WanionLib-1.12.2-2.4.jar
Wawla-1.12.2-2.6.275.jar
witherCrumbs-1.12.2-0.11.jar
WR-CBE-1.12.2-2.3.2.33-universal.jar
YABBA-1.1.2.54.jar
zerocore-1.12.2-0.1.2.8.jar

**Comment by BluSunrize** [comment]
1.12 is no longer being supported
