### ISSUE TITLE
Suggestion-Adding better power generation and other upgrades.

### ISSUE THREAD

**Issue by Mech178** [BluSunrize/ImmersiveEngineering#4113]
Creating an improved power generation for later on in the game, such as a steam turbine and boiler unit.  Would still keep with the feel of the mod and allow for a different way to create power besides creating multiple diesel generators.  Also an improved coke oven similar to the improved blast furnace would be welcomed.  While both can be added by immersive tech mod, it seems as it would be a good addition to the mod baseline.

**Comment by BluSunrize** [comment]
IE is never adding steam boilers. I've said this so many times. It's boring.
