### ISSUE TITLE
[1.16] Crash when holding buzzsaw with enchanted sawblade

### ISSUE THREAD

**Issue by Awesomespore** [BluSunrize/ImmersiveEngineering#4115]
### Description of the issue:
After enchanting a sawblade via use of an anvil (I applied unbreaking III and mending) and applying the sawblade to the buzzsaw, once I shift clicked the buzzsaw out of the workbench the game crashed. Right before I put on the blade I had even thought to myself "Hmm, I wonder if this will crash..." and sure enough, it did. Note that the crash did not occur until the buzzsaw was actually in my inventory, not as soon as I added the blade.

### Crashlog:
https://pastebin.com/HHf0Qpeh

### Versions & Modlist
Forge version: unsure
IE version: ImmersiveEngineering-0.16-109

**Comment by BluSunrize** [comment]
Can you reproduce that crash without optifine, please?

**Comment by Awesomespore** [comment]
Yes. The game crashes even without optifine. (it seemed like it didn't crash until I attempted to scroll to the slot that had the buzzsaw in it)

Crashlog:
https://pastebin.com/d5WaeB9g
