### ISSUE TITLE
[1.15.2] Windmills stopped by snow

### ISSUE THREAD

**Issue by Alsett** [BluSunrize/ImmersiveEngineering#4116]
### Description of the issue:
Windmills at high altitude (mountains biome in this case) can get stuck due to snow gathering on top of the windmill block itself. The snow also gives off the weird purple-and-black break particles when breaking it. 

### Crashlog:
N/A

### Versions & Modlist
Forge version 31.2.31
IE version 0.15-108

**Comment by BluSunrize** [comment]
Snow buildup appears to be determined by ` Block.doesSideFillSquare()` over the collision box of the targeted block.

Once again, vanilla's decision to determine side solidity based on collision boxes is biting us in the ass.
Most straightforward fix is probably giving the windmill a smaller, column-shaped box.
