### ISSUE TITLE
[1.16.1] Structural Cable Connectors don't rotate properly

### ISSUE THREAD

**Issue by dierks-m** [BluSunrize/ImmersiveEngineering#4118]
### Description of the issue:
Rotating a Structural Cable Connector with an Engineer's Hammer rotates the model around the wrong axis

![grafik](https://user-images.githubusercontent.com/6273249/88078652-fda42e00-cb7c-11ea-8656-c199b5b66d15.png)
Model before rotating

![grafik](https://user-images.githubusercontent.com/6273249/88078713-11e82b00-cb7d-11ea-8a44-2cccb4956b49.png)
Right-click

![grafik](https://user-images.githubusercontent.com/6273249/88078775-21677400-cb7d-11ea-9755-74b512814a2c.png)
Shift + right-click

It seems to rotate around the south-west corner. Placing it on the side of a block makes it rotate around the bottom-right corner

### Versions & Modlist
MC 1.16.1 running Forge 32.0.69 and IE 0.16-109

**Comment by BluSunrize** [comment]
Reproduced in 1.15 and 1.16

**Comment by BluSunrize** [comment]
Fixed for upcoming releases
