### ISSUE TITLE
1.16 Excavator not forming from multiblock

### ISSUE THREAD

**Issue by Smrtby999** [BluSunrize/ImmersiveEngineering#4121]
### Description of the issue:
When I build the first part of the excavator and hit the middle back block wit the hammer, it does nothing. I follow the instructions in the engineers manual to the note, and double and triple check. I can build the rest of the multiblocks, but this is the only one that does not work. 
### Versions & Modlist
I am playing 1.16 forge beta, with jei-1.16.1-7.0.0.6, preview_optifine_1.16.1_HD_U_G2_pre4 , and IE 0.16-109

**Comment by malte0811** [comment]
It works fine for me. Can you post some screenshots of the structure? You can also test if removing Optifine fixes it (it's not really supported), but I doubt this is related to OF.

**Comment by Awesomespore** [comment]
Try clicking every other block with the hammer, see if that works

**Comment by BluSunrize** [comment]
@Awesomespore It won't. There is one single block that works, and it's the central one in the back.

@Smrtby999 most likely built it wrong. If we get pictures, then we can identify what exactly they did wrong.

**Comment by Awesomespore** [comment]
Oh! Try digging out some space around the bucket wheel and then try it.

**Comment by BluSunrize** [comment]
@Awesomespore you're not helping.

We need pictures of the setup to diagnose the issue.

**Comment by billybricker** [comment]
It's not forming for me either. The wheel forms fine but the machine part won't.

https://imgur.com/a/6KyzsPv

Custom modpack 1.16.1

Forge: 32.0.75
Immersive Engineering: 0.16-109

Modlist: https://hastebin.com/ajijafatud.css

**Comment by Arkolis** [comment]
If using FTB wiki, the recipe for this is out of date. The Heavy engineering block on the top row of the machine was replaced with a steel sheet metal block. That is probably what went wrong, anyone not building the engineers manual inside 1.16.1 won't see the difference.

**Comment by BluSunrize** [comment]
Maybe people should stop using third party wikis and actually use the ingame documentation that the developers write...

Closing this due to lack of response by the original poster.
