### ISSUE TITLE
[1.16] Consistent crash with wires

### ISSUE THREAD

**Issue by Awesomespore** [BluSunrize/ImmersiveEngineering#4122]
### Description of the issue:
When loading chunks that contain wires (after going far enough away to unload the chunks containing said wires), the game crashes. It happens every single time I unload and reload those chunks.

### Crashlog:
https://pastebin.com/Du5WnNAQ
(No OptiFine): https://pastebin.com/UhZhNR1g (still crashes)

### Versions & Modlist
Forge version: unsure
IE version: ImmersiveEngineering-0.16-109

**Comment by Awesomespore** [comment]
I'm gonna try using the /forceload command to keep the chunks loaded

**Comment by Glitchster00** [comment]
This looks very similar to an issue I opened, this might duplicate check here https://github.com/BluSunrize/ImmersiveEngineering/issues/4111

**Comment by Awesomespore** [comment]
Ah, I DID check if it was already mentioned somewhere, but I didn't see that one.
Yeah, that does seem to be the same issue as what I've described here. Though I will say that using the /forceload command DOES prevent the game from crashing since it prevents those chunks from unloading.

**Comment by malte0811** [comment]
I think my fix for #4111 should also fix this. If it happens again with the new release (once that's out) please put a comment here with the new crash.
