### ISSUE TITLE
[1.16] Engineer's Workbench item model rotation issues

### ISSUE THREAD

**Issue by IronPiston** [BluSunrize/ImmersiveEngineering#4123]
### Description of the issue:
The IE workbench item model seems to have multiple problems with the orientation:
- The left and right hand model don't mirror each other in 1st person
- The left and right hand model don't mirror each other in 3rd person
- The item is at a strange angle in item frames/on the ground

This *seems* to be the only item model with this behavior, as everything else correctly flips in 1st/3rd person and isn't tilted. 

### Versions & Modlist
Forge: 32.0.75
IE: 0.16-109

![2020-07-21_23 57 48](https://user-images.githubusercontent.com/11603684/88136126-3e686b00-cbae-11ea-8957-f124d57b4072.png)

![image](https://user-images.githubusercontent.com/11603684/88136612-3957eb80-cbaf-11ea-8fdb-6f5bcd8d00d9.png)

![2020-07-22_00 04 33](https://user-images.githubusercontent.com/11603684/88136547-1a595980-cbaf-11ea-9813-8aef10403a3a.png)

![2020-07-22_00 04 48](https://user-images.githubusercontent.com/11603684/88136565-21806780-cbaf-11ea-9c99-74b23f53d9ab.png)

**Comment by IronPiston** [comment]
Forge: `35.0.18`
IE: `1.16.4-4.1.1-128`

I did some more testing, and it seems to include other models as well. Cheating in the blocks for the multiblocks like the crusher and crude blast furnace, they exhibit the same behavior.

![2020-11-20_01 11 45](https://user-images.githubusercontent.com/11603684/99770692-800e1180-2acd-11eb-9601-e2028b81b628.png)
![2020-11-20_01 12 42](https://user-images.githubusercontent.com/11603684/99770695-83090200-2acd-11eb-8c87-cdd4f97f701d.png)

**Comment by BluSunrize** [comment]
**you literally had to cheat them in**
You're not supposed to have multiblocks in your hand, which is why only their inventory render is adjusted appropriately.
