### ISSUE TITLE
[1.15] Server Crash: ConcurrentModificationException

### ISSUE THREAD

**Issue by RelativeProgramming** [BluSunrize/ImmersiveEngineering#4125]
### Description of the issue:
Shortly after starting a dedicated server with the mod, the server crashes, without any player interaction. Note that this happens with a new world, where no machines have been built. This error occured every restart.

### Crashlog:
https://gist.github.com/RelativeProgramming/21b33c0b5a33604fd46418f88f4ec1f6

### Versions & Modlist
(Valhelsia Origins Modpack Version 1.0.2)
IE: 0.15-108
Forge: 31.2.31

**Comment by mindforger** [comment]
> This crash report has been saved to: D:\Games\Minecraft\Server\Valhelsia Origins\.\crash-reports\crash-2020-07-22_19.13.53-server.txt

This one would be a bit more comprehensive, just as hint for future reports

**Comment by BluSunrize** [comment]
Interesting, a concurrency error when saving Mineral veins. I didn't realize worldgen could happen at the same time as saving data.

@malte0811 what's your recommendation here? Just throw a `sychronized` around it?

**Comment by malte0811** [comment]
> @malte0811 what's your recommendation here? Just throw a `sychronized` around it?

Probably. Worldgen was made (partially?) multithreaded in 1.14 (?), I didn't think about it too much because we don't do much worldgen-related stuff.
