### ISSUE TITLE
(1.14.4) Inventory dupe with engineer workbench?

### ISSUE THREAD

**Issue by Meowzers3846** [BluSunrize/ImmersiveEngineering#4127]
I am using a modpack (Enigmatica 4), and I cannot use the engineer’s workbench with a blueprint. Whenever I use a blueprint (specifically the metal press molds) it duplicates every item in my inventory (and sometimes gets rid of some items) and won’t show me and different U.I. If I click on one of the duplicates items once I leave the workbenches menu, my inventory goes back to normal. Is there a permanent fix for this?

**Comment by BluSunrize** [comment]
Could you please provide the information requested by the issue template, aka the full modlist with version info?

**Comment by BluSunrize** [comment]
Closed due to lack of response
