### ISSUE TITLE
[1.16] Blast Bricks craft into Lead Ingots & can't craft Reinforced Blast Bricks

### ISSUE THREAD

**Issue by ThousandFields** [BluSunrize/ImmersiveEngineering#4130]
### Description of the issue:

Blast Bricks craft into 9 Lead Ingots, as if they were a Block of Lead, and this recipe doesn't appear on JEI. Attempting to craft Reinforced Blast Bricks (tested with inventory grid and Engineer's Crafting Table) also won't work, although it appears on JEI and the move items button in JEI also shows that the recipe is correct.

### Versions & Modlist

Forge 32.0.75
Immersive Engineering 0.16-109

Full modlist: https://pastebin.com/MAy7Tn6T

Both issues were on a LAN server. Both of them also _don't_ happen in a singleplayer world with only IE (and Forge) enabled. Mod conflict?

**Comment by BluSunrize** [comment]
Yeah that sounds a lot like a cross mod issue.
Do the issues happen in a Singleplayer world *with* all those mods installed? Because if it does, the LAN server is probably irrelevant to the issue.

**Comment by ThousandFields** [comment]
Tried it on a singleplayer world with all the mods. The Blast Brick doesn't craft into Lead Ingots _but_ I still can't craft Reinforced Blast Bricks. Another issue, in SP, all IE compressed metal blocks won't craft into ingots. Last night when I was playing with my friend, the Mekanism Steel Block couldn't be crafted into Ingots, but this issue doesn't occur in SP.

**Comment by BluSunrize** [comment]
Please perform a binary search on your modlist:
Remove half the mods, see if the issue persists. If it does, half the current set, if it doesn't use the other half.
Keep doing that until your find the compatability issue.

**Comment by ThousandFields** [comment]
Seems like it's a conflict between the Placebo dependency and The One Probe. My friend reported that all modded compressed blocks had issues, so I removed IE and used only Mekanism with the conflicting mods and tested using a Mekanism block, and the issue was still there.

**Comment by BluSunrize** [comment]
Alright, that probably needs to be reported there then. Thanks for checking =)
