### ISSUE TITLE
1.16.1 Crash when placing crate

### ISSUE THREAD

**Issue by Ibirtem** [BluSunrize/ImmersiveEngineering#4133]
Put the blocks for create arc furnace in crate and put crate in world cause crash... Maybe? It's just random crash which can't be repeated the first time.
https://gist.github.com/Ibirtem/f07484ca08eca734dd1aa5d663f9c55c

**Comment by BluSunrize** [comment]
I can not replicate this issue.
Have you had it happen again, or was this a one time thing?

**Comment by Ibirtem** [comment]
No. Just one-two times. The only thing I can say is that the box had a different hitbox when the parts of furnace were put in it.
