### ISSUE TITLE
[1.16.1] Crash on loading multiblock I think

### ISSUE THREAD

**Issue by Arkolis** [BluSunrize/ImmersiveEngineering#4135]
### Description of the issue:
Crash on loading multiblock machines.

### Crashlog:
Pastebin was having errors so I just made a personal repository for it.
https://github.com/Arkolis/CrashReports/blob/master/crash-2020-07-26_09.55.56-client.txt

### Versions & Modlist
IE 0.16-109
Additional_lights-1.16.1-2.1.0
AutoRegLib-1.6-42
Bookshelf-1.16.1-6.1.11
BotanyPots-1.16.1-3.0.4
corpse-1.16.1-1.0.7
Craftable saddles 1.3
Culinaryconstruct 3
Doublebladeaxemod 1.2.1
Extra boats 1.4.0
Happy Trails 0.7.2
Incubation 1.1.0
JEI 7.0.0.6
Luckyblock 
Lumberjack 2.1.2
MA Enchants 3.2.1
Mekanism / Additions / Generators / Tools - 10.0.3.426
MouseTweaks 2.13
Optifine Beta U G2 Pre 9 - Probably the culprit, if so Sorry.
Quark Oddities 1.15.2
Quark r2.2-255
Waystones 7.0.2

This mostly seems to happen when away from the chunk with a multi block machine and then return to it loading the chunk back in. Again if this is an optifine error please let me know. Thank you in advance.

**Comment by malte0811** [comment]
Known issue, see #4111. Should be fixed for the next release.
