### ISSUE TITLE
1.16.1 Crash after a few seconds after entering in existing world

### ISSUE THREAD

**Issue by Ibirtem** [BluSunrize/ImmersiveEngineering#4138]
Uh... New issues with new crash...
Now i just cant entering in world. After a few seconds get crash and idk causes this Immersive ot not. Sorry if not
Befor this install Quark and Bamboo Blocks

Crash: https://gist.github.com/Ibirtem/1df991152f77d081a92cad1462238278
Log: https://gist.github.com/Ibirtem/19d8796153de8c492279fc44eb657063

**Comment by Ibirtem** [comment]
And oh i think this issue is replay https://github.com/BluSunrize/ImmersiveEngineering/issues/4136

**Comment by BluSunrize** [comment]
Duplicate.
