### ISSUE TITLE
[1.16.1] Crash when unloading chunk with active wires

### ISSUE THREAD

**Issue by kingofrunes** [BluSunrize/ImmersiveEngineering#4139]
**Description of the issue:**
While riding my horse away from my base that had some wires powered, I crashed. Attached is the log that it generated. Looks like it's something to do with checkState when unloading the connectors

**Crashlog:**
https://gist.github.com/kingofrunes/a148bb64db748993c99fe77f96762848

**Versions & Modlist**
Minecraft: 1.16.1
Forge: 32.0.75
Immersive Engineering: 0.16.109

**Comment by Mowmaster** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/4111
