### ISSUE TITLE
[Suggestion] Add map for core samples.

### ISSUE THREAD

**Issue by Craftypiston** [BluSunrize/ImmersiveEngineering#414]
First off, i really like the mod and the way you handle mining :+1: . There are lot's of way too keep track of what chuck has what deposits but it would be neat to have some kind of map or way to keep track of it. I feel like this play's very well into the feeling of the mod. Perhaps you can do something with this, otherwise i am sorry to have wasted your time :)

Maybe you will need to make some 'sturdy paper' with hemp and have to insert that paper into the core sample drill in order to keep track? You might have an better idea on how to implement something like this..

**Comment by VermillionX** [comment]
Might I add to this suggestion?
Rather than using a map for it, I suggest that when you check a Core Sample Drill (the first time) when it's completed it gives the drilled core as an item, as one would in real life, with the x, y, z location of the drill and the composition of the core (e.g. Pyrite) attached to the tooltip. In-game maps are simply useless.

**Comment by cobra** [comment]
I like this idea of actual samples.

This could even enable an additional step: get a sample as item and then put that into either an analyser block to get the contents of it (and maybe catalogue all the analysed samples) or into a furnace to get a nugget or dust of the contents (could need multiple trips for samples with more than one material in it). I'm not quite sure on that, maybe this process would be too complex.

**Comment by XFactHD** [comment]
@cobra I would make an analyzer block or something like a microscope were you go into a GUI and when you hover over the different colored/textured parts of the sample, you get the name of the corresponding ore vein.
