### ISSUE TITLE
[1.15.2 IE v0.15-108/Forge 1.15.2-31.2.0] Tank rendering bug when placed on slabs/stairs

### ISSUE THREAD

**Issue by OneEyedOthinus** [BluSunrize/ImmersiveEngineering#4142]
### Before reporting:
looked for "tank", nothing about the tank came up.
### Description of the issue:
When i'm building a tank, there is some manner of rendering bug when it is placed on a ring of stairs/slabs with a hole in the middle. The tank does not fully render, with some sections being invisible/seethrough.

### Crashlog:
[regular](https://pastebin.com/jJ6m5BMe)
[minimal instance (Forge+IE)](https://pastebin.com/p18aVf6X)
![2020-07-28_11 57 25](https://user-images.githubusercontent.com/68514274/88694389-78fe6600-d0ce-11ea-86ad-845f11271511.png)
![2020-07-28_12 01 39](https://user-images.githubusercontent.com/68514274/88694396-7ac82980-d0ce-11ea-91d8-2363396be8b3.png)
![2020-07-28_12 17 46](https://user-images.githubusercontent.com/68514274/88694403-7c91ed00-d0ce-11ea-9fa7-c5ecef43454b.png)
![2020-07-28_11 46 04](https://user-images.githubusercontent.com/68514274/88694409-7dc31a00-d0ce-11ea-9bf3-7434f2ec1673.png)
![2020-07-28_11 54 37](https://user-images.githubusercontent.com/68514274/88694411-7ef44700-d0ce-11ea-8b6e-4c657426d0a7.png)

**Comment by malte0811** [comment]
I am unable to replicate this, and have absolutely no idea how this can happen. Can you try updating Forge to the latest build and see if that fixes it? Are you using any nonstandard graphics settings in Forge or MC?

**Comment by BluSunrize** [comment]
Closed due to lack of response
