### ISSUE TITLE
[1.16.1] Game fails to load using Forge 32.0.90+

### ISSUE THREAD

**Issue by 04Slash** [BluSunrize/ImmersiveEngineering#4143]
### Description of the issue:
[The game fails to load while using forge 32.0.93](https://imgur.com/MFJK5Ok). I presume this is due to forge changing some things internally since 2 other mods (Quark and Simple Farming) are also broken using this version of forge, however those issues seem to be different. I am not a coder, so don't take my word for that. 

### Crashlog:
No crash log is being generated. [Latest.log](https://pastebin.com/cQsCD0ZD)

### Versions & Modlist
Forge: 32.0.93
IE: ImmersiveEngineering-0.16-109.jar
No other mods are present.

The game will load just fine with forge 32.0.86-88. I did get one crash with 88, but can't replicate it. [Crash report](https://pastebin.com/HeWysGW4). [Latest.log](https://pastebin.com/hDdkyck7).
Using forge 32.0.90-92 will cause the game to instantly close. No useful information in the latest.log, and no crash report.
Using the previous version of IE (106) will have the same results with the above forge versions.

If you need anymore information from me let me know and I'll gladly supply it.

I'm going to leave this here because it may help people using google for this issue, so just ignore this.
Failed to create mod instance. ModID: immersiveengineering, class blusunrize.immersiveengineering.ImmersiveEngineering
java.lang.IllegalArgumentException: Method public void blusunrize.immersiveengineering.common.world.IEWorldGen.chunkDataLoad(net.minecraftforge.event.world.ChunkDataEvent$Load) has @SubscribeEvent annotation, but takes an argument that is not a subtype of the base type interface net.minecraftforge.fml.event.lifecycle.IModBusEvent: class net.minecraftforge.event.world.ChunkDataEvent$Load

Update: While searching for other mods, this seems to be an issue with forge and not your mod.
Update 2: Jumped the gun a little too soon. This mod is still broken with forge 32.0.96. I will leave this open for now seeing as it's still an issue. You can feel free to close if you desire, seeing as this (probably) isn't an issue with your mod.
**If anyone has this issue, downgrading forge to 32.0.88 will fix this.**

**Comment by malte0811** [comment]
Known issue, fixed in c9a0852.

**Comment by ProsperCraft** [comment]
Came to report but I see it has already been fixed, will test once pushed to curseforge.
