### ISSUE TITLE
[1.15.2] Shift+Clicking power tools into enchanting table deletes toolhead.

### ISSUE THREAD

**Issue by LogicEngineer** [BluSunrize/ImmersiveEngineering#4146]
### Description of the issue:
Shift+Clicking power tools into enchanting table occasionally/always? deletes the toolhead. Durability doesn't seem to make a difference but in my testing I had a few instances where the bug did not happen. Short video of problem. https://youtu.be/rtYNxTKSe9s

First discovered while playing Valhelsia 2 version 2.2.5a but went ahead and tested in a minimal instance.

### Crashlog:
No crash.

### Versions & Modlist - Minimal Instance
Forge-31.2.33
IE-0.15-108

**Comment by BluSunrize** [comment]
They shouldn't go there in the first place, they can't be enchanted...

**Comment by iggydus** [comment]
I noticed a similar issue to this when loading a bucket with a jerrycan of bio-diesel

**Comment by iggydus** [comment]
I have noticed a similar issue when using a jerrycan of creosote to fill a bucket. The jerrycan completely disappears when shift+click on the bucket of creosote. Only noticed it on the inventory 2x2 craft screen when the jerrycan is in the top left. 
Noticed it with biodiesel as well (same positioning) but for biodiesel it shows an empty bucket as the output.

**Comment by BluSunrize** [comment]
How's that a similar issue? That's a completely different issue. "Crafting a jerrycan with a bucket" is wildly different from "putting a tool into the enchanting table".
Please file a separate report for the jerrycan thing.
