### ISSUE TITLE
I have created my water wheel and it isn't producing any power, why? (picture in description)

### ISSUE THREAD

**Issue by Papasalt** [BluSunrize/ImmersiveEngineering#4149]
Playing on Enigmatica 2 Expert (1.77)

I have set up my water wheel correctly, and have a kinetic dynamo connected to it, a LV Connector connected to that and that LV Connector is connected to a LV Capacitor, I believe that it should work fine but instead produces no power at all.

Here is my setup:
![2020-07-29_22 34 35](https://user-images.githubusercontent.com/31567870/88856776-fc15de00-d1ec-11ea-94bb-cf8fb7390488.png)

I can confirm that I am using LV Connectors and not relays, and the wires are also LV, as well as the capacitor, I have tested outputting the power with fluxducts from Thermal Expansion and inputting it into a Energy Cube from Mekanism and Battery from cyclic, neither worked, so I believe it is a problem with the kinetic dynamo directly, I don't know what to try at this point, please help.

**Comment by BluSunrize** [comment]
My guess would be that you put the waterwheel down facing the opposite direction. Place it *against* the generator you want it to power, and it should work.

**Comment by Papasalt** [comment]
> My guess would be that you put the waterwheel down facing the opposite direction. Place it _against_ the generator you want it to power, and it should work.

Thanks so much :), it worked
