### ISSUE TITLE
Arc Furnace

### ISSUE THREAD

**Issue by MajorMinge** [BluSunrize/ImmersiveEngineering#415]
Dear All,

Me again. After several weeks of playing your mod alongside a few others without problem, I have encountered an issue where I am not able to create the arc furnace. I have built the structure (several times, to ensure I have not made a mistake) but right clicking it with the hammer does not create the multi block. I noticed that when I placed down the cauldron Waila told me it belongs to Dragon API. Might this be a problem? I have Rotary, Reactor and Electricraft installed.

Regards,

M

**Comment by MajorMinge** [comment]
Problem was the rail craft slabs. Fixed.

**Comment by theunkn0wn1** [comment]
Yep, structure will not form if railcraft slabs are used in the structure.Not a major issue, it is implied that IE structures require IE blocks. However, if you used Railcraft steel blocks in place of the IE ones, the structure will form... leading to a different minor issue....

**Comment by ReikaKalseki** [comment]
> I noticed that when I placed down the cauldron Waila told me it belongs to Dragon API.

Update your copies of my mods.

**Comment by Barhandar** [comment]
>Yep, structure will not form if railcraft slabs are used in the structure.Not a major issue, it is implied that IE structures require IE blocks. However, if you used Railcraft steel blocks in place of the IE ones, the structure will form... leading to a different minor issue....

The issue is that Railcraft's slabs, unlike RC's steel blocks or pretty much any other slab that is not a multipart, are tile entities, and thus obviously incompatble with multiblocks.

**Comment by BluSunrize** [comment]
No @Barhandar that is not the issue at all. The problem is that slabs are not registered to the OreDictionary, but steel blocks are. I can check the dictionary for steel blocks, so RC steel will work, but slabs aren't registered so I can't check that.
