### ISSUE TITLE
[1.16.1] Server crash from setting off gunpowder barrel 

### ISSUE THREAD

**Issue by Glitchster00** [BluSunrize/ImmersiveEngineering#4150]
### Description of the issue:
Player set off Gunpowder Barrel with a lever, gunpowder barrel pulsed several times and the server crashed. after booting up the server 

### Crashlog:

https://pastebin.com/BcBhuwtZ

### Versions & Modlist

IE: 0.16-109
Forge:32.0.75
https://pastebin.com/Btwgz5kC

**Comment by malte0811** [comment]
Fixed in a93b123
