### ISSUE TITLE
[1.16.1] Game crashing at launch

### ISSUE THREAD

**Issue by Draco26** [BluSunrize/ImmersiveEngineering#4154]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
Describe what happens, how it affects your game/gameplay and provide screenshots where possible.

I didn't find any similar problem with this version of the game, sorry if it's the case ! So, simple, when i launch the game, it says to me : " Immersive Engineering (immersiveengineering) has failed to load correctly     Method public void "
You can see it better here : https://postimg.cc/rKzx8RJr
### Crashlog:
If your Minecraft instance has crashed, a file will have been generated in the folder `crash-reports` of your minecraft folder. To understand what has happened, we need to know the content of that file. But please don't just put it directly in your report (that makes it hard to read), upload it to a site like [pastebin](http://pastebin.com) or [gist](http://gist.github.com) and put a link in the actuall bug report.

Actually, i don't have any crash report with this problem (maybe because the game doesn't really crash, it just doesn't continue to the main menu)

### Versions & Modlist
IE and Forge versions are mandatory. *Note that saying "latest" is **not** valid. Always give the proper version number*
Other mods should be listed (with their versions) in a [pastebin](http://pastebin.com) or [gist](http://gist.github.com) upload. The easiest way to get these lists is a crashlog, you may force one with F3+C.
If your game crashed (see above) you may omit the modlist, but IE and Forge version would still be nice.

Also, please try testing an issue in a minimal instance, with just IE, Forge and maybe JEI. That makes elminating compat issues easier.

My mods folder : https://postimg.cc/phD56DRw
I'm using the very last 1.16.1 forge version ! (32.0.98)

Thanks a lot ! And sorry if it's a duplicate of an existing post !

**Comment by BluSunrize** [comment]
It is a duplicate. One of many. Please actually search next time.
Also, you're supposed to delete the explanatory stuff in the template, so we can actually read things.

Downgrade to Forge version 88 until the next IE release.
