### ISSUE TITLE
[Bug] Chemical Thrower crashes game upon firing.

### ISSUE THREAD

**Issue by verSTANdig** [BluSunrize/ImmersiveEngineering#4155]
### Description of the issue:
On the multiplayer I play with friends, I made the Chemical thrower and filled it with **Creosote Oil**. **I have the Multi-tank upgrade installed, every tank was filled with Creosote oil.** When firing it (doesnt matter which mode), your game freezes and crashes. Multiple people all with different pc specs have experienced this issue.

### Crashlog:
https://pastebin.com/6MujLM8K
                

### Versions & Modlist
We are running the  Valhelsia 3 version 3.0.9 (Full mod List: https://www.curseforge.com/minecraft/modpacks/valhelsia-3/files/3019909) Forge version:  32.0.70

**Comment by ICanBarelyCode** [comment]
I'm having the same problem. Also happens with the railgun in my game.

**Comment by BluSunrize** [comment]
Duplicate. Use the search function.
