### ISSUE TITLE
[1.15.2] Bottling machine crashes when filling some potions

### ISSUE THREAD

**Issue by Alsett** [BluSunrize/ImmersiveEngineering#4156]
### Description of the issue:
When filling a bottle with a healing potion at the bottling machine, the game crashes right before the filling animation can happen.
I got this issue with healing potion, speed potion, and leaping potion, but NOT with awkward/thickness potion. Also filling a bucket with water/etc. works fine.
After loading up the world again, the potion that caused the crash is sitting on the ground as you'd expect. 
Screenshot of the moment before disaster:
https://imgur.com/a/nXjglx1

ALSO, I'm not sure if this is part of the same issue, but when trying to fill a bottle with water, it just spits out the empty bottle. Even though filling a bucket with water works fine. 

### Crashlog:
https://pastebin.com/benzWVAr

### Versions & Modlist
Forge 31.2.33
ImmersiveEngineering-1.15.2-3.1-2ec924fe
also tried ImmersiveEngineering-0.15-108

**Comment by BentoGambin** [comment]
Happened to me too when atempting to fill a weakness potion. 
ImmersiveEngineering-0.16-109 and forge .88
[crash-2020-08-03_14.49.01-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5017490/crash-2020-08-03_14.49.01-client.txt)

**Comment by malte0811** [comment]
Fixed in d034c69
