### ISSUE TITLE
incombitable with newest forge

### ISSUE THREAD

**Issue by ZEROX7** [BluSunrize/ImmersiveEngineering#4158]
cant load on newest forge

### Crashlog:
https://1drv.ms/u/s!AoGi5ELkm7SZoVK4KmkYYYWFBDQg?e=fJhNOR
### Versions & Modlist
0.16-106 IE VERSION
32.0.98 FORGE

**Comment by iggydus** [comment]
They are aware. Until they release the update you have to use a lower version. I don't remember the highest supported version but its in previous reports. I think it may be 32.0.88

**Comment by BluSunrize** [comment]
Please actually look at recent issues before posting issues...
