### ISSUE TITLE
Revolvers...

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#416]
With NEI or the creative window, one currently has access to Soaryn's exclusive nerf revolver as well as the other exclusives.

Steps to reproduce:
[1]open world
[2]Enable creavive mode (if you don't have it)
[3]Search for the desired revolver
[4]spawn and enjoy!

From my understanding these revolvers are designed to be locked to the UUID of a specific player.
@BluSunrize, was this change intentional?

IE version [0.6.0-pre](41cf1bb8ffa37765a8bcfdb81d4487725689cd98)

**Comment by BluSunrize** [comment]
No, you're just building a friggin dev version of the mod, and I have to test things >_>
