### ISSUE TITLE
[1.16.1] Immersive engineering has failed to load correctly

### ISSUE THREAD

**Issue by ZeWolfTah** [BluSunrize/ImmersiveEngineering#4160]
Forge version: forge-1.16.1-32.0.98
Immersive Engineering version: ImmersiveEngineering-0.16-109

Mod list:
-ImmersiveEngineering-0.16-109

Description: While loading, Immersive Engineering will fail to load and give the error shown in the picture (https://gyazo.com/63458bd1f7826e059ae1a610b15481fd). It occurs using any of the recent forge versions above version 88. That leads me to believe that this error is caused by the changes made in forge version 90. I have attached my latest log just in case it's useful.

[latest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/5012848/latest.log)

Edit: A crash log is not generated from this, otherwise I would have included that too.

**Comment by BluSunrize** [comment]
Yeah, look at recent issues. No need to report duplicates.
Use Forge version 88 until the next IE version is out.

**Comment by ZeWolfTah** [comment]
My apologies, I had only checked open issues and didn't consider checking closed issues. I'll make sure to check both in the future.
