### ISSUE TITLE
[1.15] Heavy Plated Shield UI is mangled

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#4161]
### Description of the issue:
As you can see in the screenshot, the status graphics for the Heavy Shield make no sense.
![2020-08-03_09 39 24](https://user-images.githubusercontent.com/52493793/89163844-25789600-d56e-11ea-8d59-d21be8692b3f.png)

### Versions & Modlist:
MC Version: 1.15.2
Forge Version: 31.2.30
IE Version: 0.15-108

Other mods:
JEI
Immersive-Posts
Abnormals-Core
AutoRegLib
Bamboo-Blocks
Buzzier-Bees
Create
Extraboats
Pamhc2foodcore
Quark
Swamp-Expansion
The-Loader
Upgrade-Aquatic

**Comment by BluSunrize** [comment]
Try with just IE and see if you can reproduce that.

**Comment by ghost** [comment]
Yes I can.
