### ISSUE TITLE
1.16.1 Valhelsia 2 constant crash

### ISSUE THREAD

**Issue by coffeeordeath** [BluSunrize/ImmersiveEngineering#4162]
### Description of the issue:
just walking around. Seems to be when i leave my base, but i cant be sure. There arent any chunkloaders in this pack, so i cant keep the chunks loaded. 

### Crashlog:
https://pastebin.com/e6QktKFL

### Versions & Modlist
forge-1.16.1-32.0.70
IE - ImmersiveEngineering-0.16-109

The only EXTRA mod added is: Ma-Essentials-1.16.1-3.2.3

**Comment by malte0811** [comment]
Known issue, fixed for the next release. See #4111.
