### ISSUE TITLE
[1.16.1] Client crash upon placing wire between connectors (lamps)

### ISSUE THREAD

**Issue by Filipsi** [BluSunrize/ImmersiveEngineering#4164]
### Before reporting:
Seems related to #4152 and #4111.

### Description of the issue:
Upon connecting two lamps using a wire, the other client connected to the server crashed after a few seconds.
Dedicated server and the client that placed the wire continued running without experiencing the issue.

### Crashlog:
[crash-2020-08-03_18.23.48-client.txt](https://pastebin.com/raw/b9geMLhV)

### Versions & Modlist
IE 0.16-109 on commit c82e0e2
Forge 32.0.75

**Comment by Filipsi** [comment]
I have not expirienced random crashes from chunk loading (as descibed in #4111) since the changes made in c82e0e2.
But after modifing existing network (adding new wires and connectors), the client crashed again, same as above.
The area where the last wire was placed can no longer be loaded wihout crashing.

Since I have been able to replicate the issue, here is a client [debug log](https://gist.githubusercontent.com/Filipsi/15f48e00a60a60d54461627db56df32d/raw/4baa728ce153fb919cc6ea73dda1f739499c0cde/debug.log) with `enableWireLogger` setting enabled.

**Comment by malte0811** [comment]
Should be fixed in 674cefd. Simple error, just a method having slightly different behavior from what I thought it had. Your second comment was very helpful BTW, you answered multiple questions I would have asked otherwise.
