### ISSUE TITLE
[1.16.1] Crash

### ISSUE THREAD

**Issue by MAYBEVI4ER** [BluSunrize/ImmersiveEngineering#4165]
Crashing. This is what in logs: 
[modloading-worker-12/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: immersiveengineering, class blusunrize.immersiveengineering.ImmersiveEngineering
java.lang.IllegalArgumentException: Method public void blusunrize.immersiveengineering.common.world.IEWorldGen.chunkDataSave(net.minecraftforge.event.world.ChunkDataEvent$Save) has @SubscribeEvent annotation, but takes an argument that is not a subtype of the base type interface net.minecraftforge.fml.event.lifecycle.IModBusEvent: class net.minecraftforge.event.world.ChunkDataEvent$Save

What does it mean? Is it mod conflict or not?

**Comment by BluSunrize** [comment]
With a terrible error report like this, I can't tell you.

I'd recommend downgrading to Forge version 88. If that doesn't work, file a *proper* report that doesn't *completely ignore* the issue template.
