### ISSUE TITLE
[1.12.2/0.12-98]Wooden storage crates, Engineer's toolbox , etc. deleting contents in creative mode

### ISSUE THREAD

**Issue by susautw** [BluSunrize/ImmersiveEngineering#4166]
Steps to Reproduce:
1. open both server and client
2. get a container including items. (container: wooden storage crate, engineer's toolbox,...)
3. switch to creative mode
4. open inventory(press E)
5. click on the container to take it, and then click once again to put it back to inventory
6. open the container. items have been deleted.

#### wooden storage crate
    - switch to survival mode
    - place a wooden storage crate, and then open it.
    - put some item in, and then break it
    - pick up it
#### engineer's toolbox
    - hold and right click on engineer's toolbox
    - put some item in

#### wooden storage crate
    - place it, and then open it
#### engineer's toolbox
    - right click on it

### ps
I use NBTExplorer to find the container in player inventory.
after step 5, the NBT tags are deleted.

**Comment by BluSunrize** [comment]
1.12 is no longer receiving any support.
