### ISSUE TITLE
[1.16.1-3.1 #18] Posts Not Rendering Correctly If Placed Below Y=64

### ISSUE THREAD

**Issue by DeadlySwede** [BluSunrize/ImmersiveEngineering#4167]
### Description of the issue:

If you place a post below Y=64, the rendering of the arms disappears and if you hover your crosshair on the hitbox toward the center of the post, the entire post disappears. Anything greater than or equal to Y=64 seems fine. In the linked screenshot, the post on the left is at Y=63 and the post on the right is at Y=64.

[Post Rendering](https://imgur.com/lnBambz)

### Crashlog:

None.

### Versions & Modlist

_Latest Test Server Mods_

- Minecraft 1.16.1
- Forge 32.0.75
- Immersive Engineering 0.16-3.1-e36e9a91 (build 18)
- AutoRegLib 1.6-42
- Quark r2.2-255
- Just Enough Items 7.0.0.6

_Additional Client Mods_

- Xaero's Minimap 20.15.3
- Xaero's World Map 1.7.3

**Comment by DeadlySwede** [comment]
I also built a silo at Y=63 and it disappeared whenever the crosshair was toward the middle of the silo. Behaved normally when I moved it up to Y=64. Looks like it might be a general issue not specific to posts. Not sure what "below Y=64 has to do with it. Workaround seems to be "don't do that."

**Comment by elreden** [comment]
I've noticed the same problem
