### ISSUE TITLE
[1.16.1] scaffolding in water

### ISSUE THREAD

**Issue by Tylon3T** [BluSunrize/ImmersiveEngineering#4168]
Only a visual issue which might have been here since the beginning but most of the scaffolding blocks look like this:

![2020-08-04_17 45 58](https://user-images.githubusercontent.com/69208677/89315008-a0c76e00-d67a-11ea-841a-23f4dbbd8be6.png)

Some scaffolding blocks like the stairs and slabs don't have this.
I have checked if optifine had something to do with it but it is just part of the mod.

**Comment by TeamSpen210** [comment]
That's because those aren't waterloggable, whereas stairs/slabs are.

**Comment by BluSunrize** [comment]
Interestingly, glass blocks are not waterloggable, and do not suffer from this issue.

This is definitely something wonky with rendering, but I'm not quite sure what. I'm open to any input

**Comment by TeamSpen210** [comment]
Done some digging, as of 1.15+, Forge added the `Block.shouldDisplayFluidOverlay()` hook for controlling this:
MinecraftForge/MinecraftForge#6493
Though scaffolds probably should be waterloggable?

**Comment by BluSunrize** [comment]
Scaffolding is now waterloggable :D
Along with various other blocks
