### ISSUE TITLE
1.15.2 Client - Random crash on startup

### ISSUE THREAD

**Issue by Jergeric** [BluSunrize/ImmersiveEngineering#4169]
Aloha, we play on 1.15.2 with Forge version 31.2.36 and we have made the experience that our modpack sometimes crashes on startup, always with the same message. I have the logs in the appendix, if you need anything else, please contact me.

### Crashlog:
https://gist.github.com/Jergeric/80f24a24cebf1a3651d8fbe46752d6f9#file-crash-2020-08-04_21-13-13-client-txt

### Versions & Modlist
see crashlog

**Comment by BluSunrize** [comment]
@malte0811 Crashes upon texture stitching, with the textures from our requested models.

*can* we synchonize here? Would it even help? Won't we run into an issue of stitching before all requests are handled?
