### ISSUE TITLE
[feature request] Stackable Silos

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#417]
so i have a setup shown below
![image](https://cloud.githubusercontent.com/assets/3110986/9834843/94ff16b0-5982-11e5-8fe8-de86aecab811.png)
The silos do not automatically eject downward :disappointed: 

**My request is that we can stack silos, as shown above, having the top silo gravity feed into the lower one(s).**

Railcraft tanks have this ability, yet this mod is more eye-candy.

**Comment by BluSunrize** [comment]
Silos do eject, if you provide them with a redstone signal on the bottom block, and I'm fairly sure the manual states that =P

**Comment by theunkn0wn1** [comment]
@BluSunrize
They do not eject downward, regardless of rs signal into other silos. Also
the direct stacking or silos as shown in my op is ugly. The problem with
auto eject is stated in #418 and that is not the issue I am reporting here.
I am asking for the ability to stack silos vertically, perhaps with a
connected texture of sorts for the legs, as to increase storage density per
chunk while maintaining IE's eye candy.

**Comment by BluSunrize** [comment]
I don't really like that idea, mostly because: Seriously, 41472 items in one should be pretty good.
also, even with extended legs, it'd still look pretty stupid

**Comment by theunkn0wn1** [comment]
fair enough.
