### ISSUE TITLE
[1.16.1/109] IE Manual Blueprints Page Crash (Russian Localization Version)

### ISSUE THREAD

**Issue by Agory7000** [BluSunrize/ImmersiveEngineering#4170]
### Description of the issue:
Game crashes while trying to view the second page of Blueprints Section of IE Manual (Link from Overview And Resources -> Workbench & Blueprints, page 1). RUSSIAN LOCALIZATION ISSUE, UK version is OK. So it may be just the translation issue, but still.

### Crashlog:
https://gist.github.com/Agory7000/3f65b7302aca2b40afde76912e4cb5ee

### Versions & Modlist
IE Version: 0.16-109
Minecraft Version: 1.16.1
Minecraft Version ID: 1.16.1
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_51, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation

Modlist:
forge-1.16.1-32.0.88-client.jar Minecraft {minecraft@1.16.1 DONE}
Powah-1.16.1-2.1.3.jar Powah {powah@2.1.3 DONE}
MouseTweaks_2.13_mc1.16.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
ImmersiveEngineering_0.16_109.jar Immersive Engineering {immersiveengineering@0.16-109 DONE}
durability101_1.16_0.0.3.jar Durability101 {durability101@0.0.3 DONE}
Lollipop-1.16.1-2.1.3.jar Lollipop {lollipop@2.1.3 DONE}
engineersdecor_1.16.1_1.1.1_b5.jar Engineer's Decor {engineersdecor@1.1.1-b5 DONE}
Hwyla_forge_1.10.10_B77_1.16.1.jar Waila {waila@1.10.10-B77_1.16.1 DONE}
jei_1.16.1_7.0.0.6.jar Just Enough Items {jei@7.0.0.6 DONE}
forge-1.16.1-32.0.88-universal.jar Forge {forge@32.0.88 DONE}
Xaeros_Minimap_20.16.0.1_Forge_1.16.1.jar Xaero's Minimap {xaerominimap@20.16.0 DONE}
refinedstorage_1.16.1_1.9.2.jar Refined Storage {refinedstorage@1.9.2 DONE}
gravestone_1.16.1_1.0.5.jar Gravestone Mod {gravestone@1.16.1-1.0.5 DONE}
ironchest_1.16.1_11.0.1.jar Iron Chests {ironchest@1.16.1-11.0.1 DONE}
NaturesCompass_1.16.1_1.8.5.jar Nature's Compass {naturescompass@1.16.1-1.8.5 DONE}

**Comment by BluSunrize** [comment]
Yeah, the link in the russian translation of the manual is poorly formatted.

We can fix the link, but it might be reasonable to catch this in the future.
Your opinion @malte0811 ?

**Comment by malte0811** [comment]
Fixed in 848f1899c36eca5b62c487b80ff65c4162cf6e97, along with early warning mechanisms for similar errors and many other fixes/improvements.
