### ISSUE TITLE
Client Crashes when chunks update

### ISSUE THREAD

**Issue by Chavus306** [BluSunrize/ImmersiveEngineering#4171]
Client was working fine until I started searching for mineral deposits. Now, when a lag spike happens it crashes the client.
[Debug log.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5026560/Debug.log.txt)

Forge: 32.0.88
Game: 1.16.1
Mods: 
backpacked 1.4.4
builders additions 20200729
Oh the Biome's You'll go 1.0.14
cooking for blockheads 9.0.0
dungeons plus 1.0.2
falling tree 2.2.1
Mr Crayfish furniture mod 7.0.0 pre17
gravestone 1.0.3
IE 0.16-109
jet 7.0.1.9
ma essentials 3.2.4
Optifine H_D_U_G2
Patchouli 1.16-39
structure gel api 1.1.1
Xaero's minimap 20.18.0.1

Confirmed that Optifine doesn't cause the issue.

**Comment by malte0811** [comment]
Known issue, fixed for the next release. See #4111.
