### ISSUE TITLE
[1.15] Texture issuue with the mirrored bucket wheel

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#4175]
### Description of the issue:
![2020-08-05_17 42 17](https://user-images.githubusercontent.com/52493793/89441664-6a0a5a00-d745-11ea-8314-adb7de7ef006.png)
![2020-08-05_17 42 23](https://user-images.githubusercontent.com/52493793/89441671-6b3b8700-d745-11ea-97f0-772c6a35094a.png)
![2020-08-05_17 42 36](https://user-images.githubusercontent.com/52493793/89441676-6d054a80-d745-11ea-9008-86697c868019.png)

### Versions & Modlist
MC Version: 1.15.2
Forge Version: 31.2.30
IE Version: 1.15.2-3.1-111

**Comment by malte0811** [comment]
For reference: Yes, this does not fullfill the contributing guidelines. I said it was ok since I already know what's going on and just wanted a reminder that I need to fix it.

**Comment by malte0811** [comment]
Fixed in 9d7e70f
