### ISSUE TITLE
[1.15.2] revolver texture bug 

### ISSUE THREAD

**Issue by Firezone87** [BluSunrize/ImmersiveEngineering#4176]
https://imgur.com/hpqyU4g I'm using the lastest version of OF and IE (for 1.15), if I remove the shaders the revolver fixes himself but I need them on my world. I tried using other shaders like Kuda, Seus, Sildurs, TME (now I'm using chocapic) and I changed almost all the settings but it didn't work.
(the mining drill and buzzsaw are bugged too)

**Comment by BluSunrize** [comment]
*shrug*
Optifine is not supported.
