### ISSUE TITLE
Texture glitch

### ISSUE THREAD

**Issue by ScratchyHamster** [BluSunrize/ImmersiveEngineering#4177]
![texture glitch](https://user-images.githubusercontent.com/69278573/89470066-7b049c80-d740-11ea-97e9-8dbf811956c0.png)
I have encountered this glitch while playing Seablock: Rustic waters. I made 6 immersive engineering metal presses and attached them to wires to power them with the thermoeletric generators. I didn't use them for 4 hours and came back to this glitch. It made 3 unusable and they had to be taken down.

**Comment by BluSunrize** [comment]
1.12 is no longer supported.
