### ISSUE TITLE
[1.16.1][IE-1.16.1-3.1-112] Mining Drill CTD

### ISSUE THREAD

**Issue by CaptnMorgn** [BluSunrize/ImmersiveEngineering#4179]
**Preface Info:** I was running `ImmersiveEngineering-0.16-109.jar` on my Apex server since August 2nd (with other mods too). The forge version at the time was `forge-1.16.1-32.0.88`, due to the dependency. Things work fine until a few hours ago today (August 5th). The only things _I believe_ changed since things were fairly stable was the establishment of bio-diesel generators and acquiring mining drills. At some point after these implementations, we were crashing every minute or so (locally, not the server). We saw there was an update to IE and I decided that upgrading may fix our issues.

**The Current Issue:** I updated the server (`forge-1.16.1-32.0.106`), swapped out the IE mod ([old] -> `ImmersiveEngineering-1.16.1-3.1-112`) and kept the world. After restarts and finalizing the upgrade procedure. I successfully load in, but only for 5 seconds. Try again, 2 seconds. Subsequent attempts don't even let me in the server (visually, console shows I join but throws errors then kicks me). My brother trying the server in parallel is fine... for 10 minutes or so. He soon experiences the same login blockade. What did we both have equipped? Mining drills :(

**Narrowing things down:** We then tried different scenarios to pinpoint things. Could we log into a new world? Yes, both of us. Does equipping a drill (with steel head) via creative mode cause problems, not immediately anyways. Using it seemed fine too. Note, nothing else is in the inventory other than the engineer's workbench (to put the head on the drill). However, attacking a wild skeleton immediately crashed Minecraft. This was then found to be reproducible.

**Forge, IE, what is it?!:** With Forge versions `32.0.99`, `32.0.105`, and `32.0.106`, we both independently found in local world's this 'mining drill + skeleton' bug to be reproducible. This tells me it's likely something wrong with Forge versions 99 through 106 (the dependency range), or Immersive Engineering. [Here is the crash-log of my latest attempt for reference.](https://gist.github.com/CaptnMorgn/6169790287756f4e5f7cefeaf67819d5) All other mods you see other than Immersive Engineering did not change. I.e. the mods shown are the same since August 2nd (the server's creation for version 1.16.1). The only things that have changed are Forge and Immersive Engineering.

Sorry if this was wordy. I wanted to encapsulate the whole occurrence as there might be an indication of the issue's source somewhere that I don't have the expertise to notice. I would've posted the other crash-logs too, but I forgot which is which. I imagine they're all very similar anyways. Please let me know how I can assist! Thanks!

**Comment by BluSunrize** [comment]
This is a client crash. It has nothing to do with it being on a Server. Also, while this issue is well structured, I still wish you actually used the template that we provide.

Can you please remove optifine and see if the issue persists?

**Comment by CaptnMorgn** [comment]
Sorry about the template! I ran through the preloaded text when starting the issue submission, but must've glazed over this :(. I will try to do better in the future.

I tried removing optifine when getting in the server. I had no success. I  forgot to mention this! I haven't tried locally. I'll check it out in the morning. I'll likely try more things like only having IE and get back to you. Great mod btw!

**Comment by BluSunrize** [comment]
Sorry, I wrote the post above when I was still half asleep. It has nothing to do with being on a *server*. It's absolutely an IE crash xD

So if you try it without optifine, do you still have this crash?

**Comment by CaptnMorgn** [comment]
I'll try it out on a local new world without optifine once I wake up and get back to you. I only tried the no-optifine-case when attempting to log into the server.

**Comment by CaptnMorgn** [comment]
I started a new creative local world without optifine. I then gave my self the drill, steel head, workbench, and skeleton egg. I equipped the head onto the drill and attacked a skeleton I spawned. [Here's the crash-log](https://gist.github.com/CaptnMorgn/38f75d8096e73ebc9628da2014788aa3).

I'll be back to try more things once I get back from my dentist appointment (~3 hour?).

**Comment by CaptnMorgn** [comment]
[Here's another crack at it](https://gist.github.com/CaptnMorgn/4f45a8c95806c90b66616260568359f9) with **only** Immersive engineering. I started a new local world in creative, like last time too. I forgot to mention that in the [the last one (with no optifine)](https://gist.github.com/CaptnMorgn/38f75d8096e73ebc9628da2014788aa3) I was using `forge-1.16.1-32.0.105`. I'm using the same one here. Further, I attacked a zombie this time around. The behavior is identical.

**Edit/Addition:** Going to try and just slap edits onto posts as updates. Hopefully things will read better rather than me just making 50 posts while testing things. I just restored all of my original (12) mods. Made a new world and tried the buzzsaw thinking maybe it was more of categorical issue towards IE tools. The buzzsaw hasn't given me any issues so far. Seems like it's something specifically tied to the mining drill.

**Edit 2:** Just tried the iron drill head instead of steel. Same results. [Here's the crash-log.](https://gist.github.com/CaptnMorgn/cfdbc355728f69d6e7fcd48684c900a0)

**Comment by iggydus** [comment]
I am having this issue as well both on dedicated server and on local saves. 
I crash on servers by just having the drill in my inventory and walking around.
In local world i can move around and it crashes when i hit a mob with the drill, then it crashes if i try to load back that world save. Tried with different drill heads (both iron and steel) and upgrades/no upgrades, different versions of forge and same results. 
If i log into the server without moving around i am fine but as soon as i start moving i crash within a few seconds. 

Update: Also can't log into the server now either. Crashing as soon as it starts to join. 
This happened after crashing on local world. I had to downgrade mod and forge to get in and remove the drill from my inventory, then i could rejoin with the updated mod and forge.

**Comment by DasMazl** [comment]
I want to add something into this thread. Ive found this by searching for this issue which I also run into with the mining drill. As soon as I equip it in the inventory the game crashed. I tried the same thing with the buzzsaw and it also crashed. So I dont think it has something todo with the mining drill itself. I hope this issue can be solved asap :) Its a really great mod and I would love to use it with its complete glory :)

**Comment by CaptnMorgn** [comment]
@DasMazl Under what conditions were you able to get the buzzsaw to do this?

**Comment by ghost** [comment]
I also have this issue on 1.16 with forge 32.0.106 -  I'm able to replicate it by using a fully upgraded mining drill with a steel bit on a stone wall. Apologies if this isn't the proper way to report issues, first time using Github.

**Comment by DasMazl** [comment]
@CaptnMorgn Well basically we have the basic buzzsaw, it was in a chest, I got it out of the chest to test it out (The mining drill remained in the chest) and as soon as I scrolled over to the buzzsaw in my hotbar my client crashed. Maybe the crash happend because I had the buzzsaw in my inventory in general and it just took a few seconds to crash but it was pretty perfect timed when I was about to scroll onto it tho.

**Comment by malte0811** [comment]
Fixed in 01c38a6

**Comment by CaptnMorgn** [comment]
@malte0811 Awesome! When I go to [CurseForge's IE page](https://www.curseforge.com/minecraft/mc-mods/immersive-engineering), the download says it was last updated 3 days ago and still gives me `ImmersiveEngineering-1.16.1-3.1-112`. Is this irrelevant and the committed changes are still nonetheless included? If not, is there a way to download the compiled(?) mod from the [GitHub](https://github.com/BluSunrize/ImmersiveEngineering)?

**Addition:** I see in the Discord that @BluSunrize mentioned in `#general` that, "correct, latest build for MC 1.16 is 3.1-112". I suppose that despite the similar version(?) name on the download, the CurseForge download is likely tied to the GitHub such that the download is always up to date. I will try testing with said download soon, and post if there's a problem. I foresee this not happening, and will hence not post if everything's alright. P.S. Thanks for the wonderful mod :)

**Comment by BluSunrize** [comment]
This fix will be included in the next *release* which hasn't happened yet.
And no, it is not possible to download a compiled build from github.
