### ISSUE TITLE
Silo Automatic output issue

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#418]
The book states that if one applies an RS signal to the bottom solo interface, it will auto-output. This works when outputing to a chest, it will not export to another silo's top interface.

Steps to reproduce
`------------------`
[1] build two silos one atop the other.
[2] form both silos
[3] insert items into the upper silo
[4] apply RS signal to the lower interface of the upper silo
[5] observe

Setup tested with is shown bellow:
![image](https://cloud.githubusercontent.com/assets/3110986/9835413/9d2b489c-599e-11e5-9212-b18f63247c44.png)

----------------
IE version 0.6.0-pre SHA 41cf1bb8ffa37765a8bcfdb81d4487725689cd98

-----------------
Also... the silo outputs one item per second... that is unrealisticialy slow and painful to users without proper means of extracting items.. @BluSunrize can you please buff the output rates?

**Comment by BluSunrize** [comment]
I'll look into it.

**Comment by cobra** [comment]
It also doesn't output to conveyor belts as far as I know.

**Comment by BluSunrize** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/190f17797ba4cbe46a53009e4f2dceec23a17b64
here we go, fixed outputting to conveyors and downwards, also, the transferrate on is not 1 item per second it's 1 every 8 ticks, which is pretty good I'd say.

**Comment by theunkn0wn1** [comment]
@BluSunrize, Um... So the silos work as expected now, though the fluid Tank has this issue too!
![image](https://cloud.githubusercontent.com/assets/3110986/9868718/1cf8865a-5b31-11e5-8442-8f87357d30c1.png)

**Comment by BluSunrize** [comment]
Lol. Same code. Sorry 'bout that. x3

**Comment by BluSunrize** [comment]
Oh, wait nevermind.
The fluid tank doesn't have any output function like that anyway. I never added it.
To be done.
