### ISSUE TITLE
[1.15.2] 'Exception in server tick loop'

### ISSUE THREAD

**Issue by atoldiago** [BluSunrize/ImmersiveEngineering#4181]
### Description of the issue:
As of right now, no one can login to the server. As I have stated in a previous post, I am not the smartest when it comes to looking through mods, and crash logs. Our server host, when it notified us of the crash, labeled 'refinedstorage-1.8.8.jar' as the culprit of an Exception in server tick loop, but looking through the crash logs generated, IE shows all over. I have already posted this error on their issue tracker, and they redirected me to you for reporting.

### Crashlog:
If you need the ones from previous, similar crashes, let me know:
[crash-2020-08-07_21.37.03-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5043918/crash-2020-08-07_21.37.03-server.txt)

### Versions & Modlist
Minecraft: 1.15.2
Forge: 31.2.33
IE: 3.1-111
Modlist: 
[modlist_thelandfill.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5043994/modlist_thelandfill.txt)

**Comment by BluSunrize** [comment]
Should be fixed on new versions
