### ISSUE TITLE
[1.16.1 Forge] Conveyor belt extractors now extract ores and fuel from furnaces instead of just the products.

### ISSUE THREAD

**Issue by atlas1205** [BluSunrize/ImmersiveEngineering#4186]
I'm unsure if I'm doing anything wrong. But in the 1.12.1 version, the extractors only extract end products from all furnaces and machines (any mods that work with belts).
Now in 1.16.1, belts extract ores and fuel as well. This renders the whole belt system unusable.
Tested with both vanilla furnaces and Industrial Reborn. Same result.

**Comment by BluSunrize** [comment]
Vanilla furnaces have their output on the bottom. Use a hopper.
