### ISSUE TITLE
[1.16.1] excavator wheel not forming

### ISSUE THREAD

**Issue by Pollothomas** [BluSunrize/ImmersiveEngineering#4187]
I'm not really sure if the new updates changed something, but after 3 times rebuilding the excavator, i think that this is a bug or something.
Every time I right-click the excavator, only the engine part forms but the wheel doesn't and the excavator won't start.
I already updated to the latest version of IE and Forge
![2020-08-08_21 54 09](https://user-images.githubusercontent.com/69411490/89725212-fc1e9680-d9c1-11ea-8c9f-f92611b35892.png)
![2020-08-08_21 54 19](https://user-images.githubusercontent.com/69411490/89725215-ff198700-d9c1-11ea-89c9-0638735d7ec2.png)

**Comment by Pollothomas** [comment]
I don't know if it's relevant but still, i'm playing in a macbook

**Comment by malte0811** [comment]
It currently only works with IE steel blocks. I'll look into fixing that.

**Comment by mattieboy079** [comment]
Hi, this issue is currently also a problem in version 1.12.2, except here it does NOT work with IE steel blocks but it does work with Thermal Foundation steel blocks.

**Comment by BluSunrize** [comment]
1.12 is no longer supported and you are commenting on an issue closed months ago.
