### ISSUE TITLE
IndexOutOfBoundsException in Engineer's Manual displaying item recipe

### ISSUE THREAD

**Issue by Ricket** [BluSunrize/ImmersiveEngineering#419]
Crash report: http://pastebin.com/D0QibQ03

I am playing FTB Horizons: Daybreaker. I encountered this crash, and then I did these mod upgrades and it still crashed:

* AOBD 2.7.1 -> 2.8.4
* AOBDBB 1.0.4 -> 1.0.5
* Chisel 2 2.4.1.40 -> 2.5.1.44
* Chisel Tones 1.0-1 -> 1.0-3
* Immersive Engineering 0.4.4 -> 0.5.4
* Immersive Integration 0.4.1 -> 0.5.4

Those are of course the latest versions of the mods at this moment.

Procedure to reproduce:

* Open Engineer's Manual.
* Navigate to Overview and Resources, then Treated Wood, then next page.
* Crash within a couple seconds

It's trying to display some ingredient of making a treated wood item, but failing. If I go view recipes of any treated wood item in NEI, no crash occurs.

**Comment by BluSunrize** [comment]
report that to the author of Dendrology, @ScottKillen

**Comment by ScottKillen** [comment]
NEI doesn't crash because ChickenBones properly catches the exception. I will make changes to Ancient Trees to protect against those who do not.

**Comment by ScottKillen** [comment]
@Ricket  This has been fixed in version 1.6.3 of Ancient Trees. Thank you for this superb report.

**Comment by BluSunrize** [comment]
Way to be rude about it. Check if your index fits the array, don't expect others to try-catch your oversights.

**Comment by ScottKillen** [comment]
@BluSunrize I was not trying to be rude, I am sorry if you are offended. I was only pointing out that there is a better way to handle things in code...

The code was not an oversight. Your code requested an icon for a subBlock that does not exist, nor could it exist (It is not possible for a block to have 32,000+ subBlocks)...were I writing the same code, I would expect an exception...garbage in, garbage out... one line of code to fix and no crashes.

I thought @Ricket did a great job writing up the problem and this allowed me opportunity to revisited some other smaller issues in Ancient Trees, so I was grateful you kicked it to me. Thank you.

Again, sorry if my coding style offends...

**Comment by cobra** [comment]
FYI: 32767 just so happens to be the value Forge (and Minecraft) uses as [`OreDictionary.WILDCARD_VALUE`](https://github.com/MinecraftForge/MinecraftForge/blob/1.7.10/src/main/java/net/minecraftforge/oredict/OreDictionary.java#L47). I didn't look into this any further, but I guess this is why this "ridiculous" value showed up.

**Comment by ScottKillen** [comment]
Yes.

The wildcard value is used to specify all sub-blocks of a given block to the OreDictionary and is recognizable to the OreDictionary and probably some recipe handlers but is not intended to be used to request icons from a block. I would consider this a mistake, but even so, the Ancient Trees code is now more robust and won't choke on it. Good code does not choke on unexpected data. :grinning:

**Comment by BluSunrize** [comment]
Yeah sorry about getting grumpy about it. But I feel like try{}catch-ing that would impact performance a lot :/

**Comment by ScottKillen** [comment]
No worries!

**Comment by Ricket** [comment]
Thank you both. I'll download Ancient Trees 1.6.3 tonight and try it out.

**Comment by ScottKillen** [comment]
:+1:

**Comment by BluSunrize** [comment]
I improved my handling on the matter as well. Sorry <3
