### ISSUE TITLE
NPE in JEI plugin

### ISSUE THREAD

**Issue by malte0811** [BluSunrize/ImmersiveEngineering#4190]
<https://gist.github.com/malte0811/00260bb4ce89f9b42d43fd98d2209c84>   
While joining a dedicated server. `ImmersiveEngineering-1.16.1-3.1-c1074723.jar`

**Comment by malte0811** [comment]
Still happens on 1.16 as discussed on Discord

**Comment by malte0811** [comment]
Fixed again in 4ad3a9b

**Comment by BluSunrize** [comment]
Will Arc Recycling recipes show up in JEI still?

**Comment by malte0811** [comment]
No. I can probably throw another `if (singleplayer)` in there somewhere, but that would obviously only work in singleplayer. For dedicated servers I think the only option is to sync the recipes.
