### ISSUE TITLE
[1.15.2] Revolver doesn't function

### ISSUE THREAD

**Issue by PenguinChoi5** [BluSunrize/ImmersiveEngineering#4194]
# Description of the issue:
The revolver simply doesn't work when I try to use it for some reason, it simply acts like a regular item. No matter how I get the revolver, through crafting it from scratch or using creative, at the end of the day I wont be able to fire it

Example below, I am clicking using both buttons but nothing is happening.
![2020-08-10_16 42 59](https://user-images.githubusercontent.com/63481905/89841725-96005380-db28-11ea-8389-ae8e71950fc8.png)

### Versions & Modlist
Immersive Engineering Version: 1.15.2-3.1-111
Forge: 31.2.33

Modpack is Valhesia 2-2.2.6
Modlist is here:
Waddles-1.15.2-0.8.6.jar"
WailaHarvestability-mc1.15.2-1.1.12.jar"
WAWLA-1.15.2-3.0.4.jar"
Waystones_1.15.2-6.0.2.jar"
Xaeros_Minimap_20.17.0_Forge_1.15.2.jar"
XaerosWorldMap_1.7.4_Forge_1.15.2.jar"
xnet-1.15-2.1.7-beta.jar"
Abnormals-Core-1.15.2-1.0.6.jar"
absentbydesign-1.15.2-1.1.0.jar"
AI-Improvements-1.15.2-0.3.0.jar"
aiotbotania-1.15.2-1.2.3.jar"
AkashicTome-1.3-13.jar"
AmbientSounds_v3.0.20_mc1.15.2.jar"
Apotheosis-1.15.2-3.2.4.jar"
AppleSkin-mc1.15.2-forge-1.0.14.jar"
Aquaculture-1.15.2-2.0.16.jar"
archers_paradox-1.15.2-0.4.0b.jar"
Atmospheric-1.15.2-1.4.1.jar"
AttributeFix-1.15.2-7.0.2.jar"
Atum-1.15.2-2.1.4.jar"
AutoRegLib-1.5-40.jar"
autumnity-1.3.3-1.15.2.jar"
BetterAdvancements-1.15.2-0.1.0.99.jar"
BetterBurning-1.15.2-1.3.4.jar"
BetterMineshaftsForge-1.15.2-1.3.jar"
BetterTitleScreen-1.15.2-1.9.jar"
BiomesOPlenty-1.15.2-10.0.0.366-universal.jar"
BonsaiTrees-2.1.2.6.jar"
Bookshelf-1.15.2-5.6.40.jar"
Botania-r1.15-387.jar"
BotanyPots-1.15.2-2.0.27.jar"
Buzzier-Bees-1.15.2-1.5.2.jar"
caelus-FORGE-1.15.2-2.0-beta3.jar"
cc-tweaked-1.15.2-1.90.2.jar"
cherishedworlds-FORGE-1.15.2-3.0.0.1.jar"
Clumps-5.0.2.4.jar"
CodeChickenLib-1.15.2-3.3.1.379-universal.jar"
cofh_core-1.15.2-0.4.0b.jar"
comforts-FORGE-1.15.2-2.0.0.3.jar"
config-2-3.0.jar"
Controlling-6.1.5.6.jar"
CookingForBlockheads_1.15.2-8.0.3.jar"
CosmeticArmorReworked-1.15.2-v3a.jar"
CraftingTweaks_1.15.2-11.0.1.jar"
CraftTweaker-1.15.2-6.0.0.37.jar"
create-mc1.15.2_v0.2.4d.jar"
curioofundying-FORGE-1.15.2-3.0.jar"
curios-FORGE-1.15.2-2.0.2.4.jar"
curiouselytra-FORGE-1.15.2-2.0.jar"
DarkUtilities-1.15.2-3.1.8.jar"
decorative_blocks-6d.jar"
DefaultOptions_1.15.2-11.0.1.jar"
DoubleSlabs-1.15-2.9.0.jar"
Druidcraft-1.15-0.4.21.jar"
elevatorid-1.15.2-1.7.1.jar"
embellishcraft-1.15.2-2.2.1.0.jar"
EnderStorage-1.15.2-2.5.0.149-universal.jar"
engineersdecor-1.15.2-1.1.1-b1.jar"
Enhanced-Mushrooms-1.15.2-v1.2.2.jar"
ensorcellation-1.15.2-0.4.1b.jar"
EquipmentTooltips-1.15.2-1.4.3+14.jar"
essentials-1.15.2-2.7.3.jar"
extlights-2.1.jar"
extradisks-1.15.2-1.2.2.jar"
fairylights-3.0.7-1.15.2.jar"
FastFurnace-1.15.1-3.0.0.jar"
FastLeafDecay-v22.jar"
FastWorkbench-1.15.2-3.1.1.jar"
FluxNetworks-1.15.2-5.0.3-4.jar"
forbidden_arcanus-1.15.2-1.4.jar"
FruitTrees-1.15.2-1.5.2.jar"
ftb-backups-2.1.0.1.jar"
furniture-7.0.0-pre16-1.15.1.jar"
Hwyla-forge-1.10.8-B72_1.15.2.jar"
ImmersiveEngineering-1.15.2-3.1-111.jar"
incubation-1.0.4-1.15.2.jar"
industrial-foregoing-1.15.2-2.3.3-e356e61.jar"
InventoryHud_1.15.2.forge-3.0.1.jar"
inventorysorter-1.15.2-17.0.0.jar"
ironchest-1.15.2-10.0.3.jar"
JAOPCA-1.15.2-3.2.0.14.jar"
jei-1.15.2-6.0.2.12.jar"
JEIEnchantmentInfo-1.16.1-1.1.0.jar"
jeiintegration_1.15.2-3.1.0.1.jar"
JEITweaker-1.15.2-1.0.1.3.jar"
JustEnoughResources-1.15.2-0.10.1.77.jar"
Kiwi-1.15.2-2.7.2.jar"
Kottle-1.5.2.jar"
leavesdecayonotherleaves-1.1.jar"
libnonymous-1.15.2-1.1.1.5.jar"
lightestlamp-3.4.3.jar"
light-overlay-4.7.0.jar"
Lollipop-1.15.2-1.0.15.jar"
mapperbase-1.15.2-1.1.1.0.jar"
mcjtylib-1.15-4.1.3-beta.jar"
mcw-bridges-1.0.4fix-mc1.15.2.jar"
mcw-doors-1.0.0-mc1.15.2.jar"
mcw-furniture-1.0.1-mc1.15.1 1.15.2.jar"
mcw-roofs-1.0.2-mc1.15.2_1.15.1.jar"
mcws-win-1.15.2-v1.0.2.jar"
Mekanism-1.15.2-9.10.9.422.jar"
MekanismAdditions-1.15.2-9.10.9.422.jar"
MekanismGenerators-1.15.2-9.10.9.422.jar"
MekanismTools-1.15.2-9.10.9.422.jar"
minecolonies-0.13.78-ALPHA-universal.jar"
mininggadgets-1.3.5.jar"
mining-helmet-1.15.2-1.0.8.jar"
MixinBootstrap-1.0.3.jar"
MouseTweaks-2.13-mc1.15.1.jar"
mysticallib-1.15.2-2.0.1.jar"
mysticalworld-1.15.2-2.0.5.jar"
NaturesCompass-1.15.2-1.8.5.jar"
Neat 1.6-22.jar"
NetherPortalFix_1.15.2-6.0.2.jar"
OldJavaWarning-1.15.2-3.0.2.jar"
OpenLoader-1.15.2-4.0.5.jar"
overloadedarmorbar-4.0.0.jar"
PackMenu-1.15.2-1.2.7.jar"
paintings-1.15.2-7.0.0.0.jar"
Patchouli-1.15.2-1.2-35.jar"
PersistentBits-1.15.2-2.0.3.jar"
phosphor-forge-mc1.15.2-0.5.2+build.4.jar"
Placebo-1.15.2-3.1.0.jar"
polymorph-FORGE-1.15.2-0.9.jar"
Powah-1.15.2-1.1.14.jar"
ProgressiveBosses-2.1.5-mc1.15.2.jar"
Psi r1.2-82.jar"
QuarkOddities-1.15.2.jar"
Quark-r2.1-245.jar"
randompatches-1.15.2-1.22.1.1.jar"
ReAuth-1.14-1.15-3.8.1.jar"
refinedpipes-0.4.2.jar"
refinedstorage-1.8.8.jar"
refinedstorageaddons-0.6.3.jar"
rftoolsbase-1.15-1.1.3-beta.jar"
rftoolsbuilder-1.15-2.1.5-beta.jar"
rftoolscontrol-1.15-3.0.4-beta.jar"
rftoolspower-1.15-2.2.0-beta.jar"
rftoolsstorage-1.15-1.1.6-beta.jar"
rftoolsutility-1.15-2.1.5-beta.jar"
Savage-and-Ravage-1.15.2-1.1.4.jar"
scenic-1.15.2-1.0.2.jar"
serverconfigupdater-1.1.jar"
ServerTabInfo-1.15.2-1.2.7.jar"
SilentGear-1.15.2-1.11.0+147.jar"
SilentLib-1.15.2-4.6.6+59.jar"
SilentMechanisms-1.15.2-0.8.0+59.jar"
simplefarming-1.15.2-1.3.0.jar"
SimpleStorageNetwork-1.15.2-1.0.1.jar"
snowundertrees-1.15.2-v1.1.1.jar"
SolarFluxReborn-1.15.2-15.2.3.jar"
StorageDrawers-1.15.2-7.0.2.jar"
structure-gel-api-1.15.2-1.1.0.jar"
structurize-0.13.31-RELEASE.jar"
Swamp-Expansion-1.15.2-1.7.3.jar"
swingthroughgrass-1.15.2-1.4.0.jar"
TerraForged-1.15.2-0.0.15.jar"
the-conjurer-1.15.2-1.0.6.jar"
The-Endergetic-Expansion-1.15.2-v1.3.2.jar"
themidnight-0.5.9.jar"
titanium-1.15.2-2.4.2.jar"
ToastControl-1.15.2-3.0.1.jar"
ToolBelt-1.15.2-1.14.1.jar"
torchmaster-2.2.1.jar"
torchslabmod-1.15.2_v1.7.0.jar"
toughnessbar-5.0.jar"
trash-1.15.2-0.2.0.jar"
TrashSlot_1.15.2-11.0.0.jar"
u_team_core-1.15.2-3.0.1.164.jar"
Upgrade-Aquatic-1.15.2-1.7.1.jar"
useful_backpacks-1.15.2-1.10.1.70.jar"
valhelsia_structures-15.0.3a.jar"

IMPORTANT NOTE: Revolver works fine on it's own without any of the other mods, meaning that this is probably a compatibility issue.

**Comment by PenguinChoi5** [comment]
SECOND NOTE: The cartridges don't move whenever I click, meaning that it isn't simply a misunderstanding of the tool.

**Comment by BluSunrize** [comment]
Okay, so if it works fine with just IE, and this is a suspected compat issue, please perform a binary search to figure out which one:

Remove half the mods, check if it works, if it does, the error is in the removed set of mods, if it still doesn't, it's in the remaining. Keep halving your modlist until you figure out which mod is causing the incompatability.

**Comment by PenguinChoi5** [comment]
alright thanks, gonna try that when i have the time!

Gonna close this issue once I figure out which mod is causing the incompatibility, then I'll tell you guys about it and you can go fix it.

**Comment by BluSunrize** [comment]
Don't close the issue, we can close it when it's resolved. Just gather the info so we can investigate further.

**Comment by Beer1976** [comment]
I had this issue too with a much smaller pack - remove TheMidnight.  That fixed the issue with our pack.

**Comment by BluSunrize** [comment]
Closed due to lack of feedback from the original reporter
