### ISSUE TITLE
Mining Drill + Steel Tank

### ISSUE THREAD

**Issue by Thorinori** [BluSunrize/ImmersiveEngineering#42]
Hello! This issue is in version 0.1.16. I placed my Mining Drill that had the water and speed upgrades inside a Railcraft Steel Tank to attempt to put some Bio-Diesel into it. As soon as the drill landed in the tanks inventory, the server crashed, and would not reopen until I went into the world using MCEdit to break the tank. After removing some blocks from ontop of the tank then attempting to put the tank back together, immediate crash again, with the drill still inside. The server crash log is the pastebin link below.

http://pastebin.com/11aKxJ4B

Two other smaller bugs I found on the same version: The industrial Squeezer's RF Storage doesn't update with Waila, and when trying to pump liquid into a Refinery from both a Fermenter and an Industrial Squeezer, only one of them is going in. The liquid went into the first tank even though it was the tank opposite the side of the input.
The setup I have looks like:
[Squeezer] -> [Refinery] <- [Fermenter]
                             |
                        [Tank]
Edit: The tank is in front of the refinery, Github formatted it so it looks like the tank is in front of the Squeezer
Edit 2: Found the issue for the lack of piping on the squeezer! For some reason, EnderIO's Fluid Conduits don't like Plant Oil, but are fine for Ethanol

**Comment by BluSunrize** [comment]
couldn't replicate, possibly fixed.
