### ISSUE TITLE
[Suggestion] Add config options to disable content.

### ISSUE THREAD

**Issue by OneEyeMaker** [BluSunrize/ImmersiveEngineering#420]
Please, add config options to enable/disable ANY component of this mod.
For example, I'm creating tech modpack. And I want to disable wires from IE (because these wires are very cheaty on my modpack; I want to use 'GT-style' wires).
I can remove its' recipes by Mine- and ModTweaker. But using of these mods is additional burden (add recipes to HashMap, then find them and remove). On big modpacks it does matter.
And else, make recipes of capacitors more harder (or add config option for that).

P. S. Thank you for this VERY COOL mod!
P. P. S. Sorry for my English, I'm from Russia.

**Comment by Barhandar** [comment]
>On big modpacks it does matter.

Quite the contrary. If you have GregTech, this means the load times are already in the vicinity of "over 6 minutes", and MT adding a dozen or two seconds to that won't be noticed.

**Comment by BluSunrize** [comment]
No. Wires are a core function of IE and will /never/ get a config option to be disabled.
This is called game design. Not everything /has/ to be configureable; Some things are meant to be how they are.

**Comment by OneEyeMaker** [comment]
@BluSunrize 
OK. May be add option to make recipes of wires (and other components of mod) more harder?

**Comment by BluSunrize** [comment]
No. As I said. This is game design. You can always use Minetweaker, but I don't believe in overloading with config options.

**Comment by XFactHD** [comment]
@OneEyeMaster you could just configure the wires to have 0 throughput.
