### ISSUE TITLE
[1.15.2] Engineer's Manual crashes when `badEyeSight` config option is on.

### ISSUE THREAD

**Issue by Kai-Kramer** [BluSunrize/ImmersiveEngineering#4200]
### Description of the issue:
Game immediately crashes when trying to open the Engineer's Manual, if the `badEyeSight` config option is set to `true`.
I have recorded a video of the entire process, from start to finish. [Youtube](https://www.youtube.com/watch?v=PrBJRBhDrS0)

The first time I encountered this crash, I let MineCraft sit for a couple minutes before exiting, received exit code `-805306369`.

### Crashlog:
Crashlog not generated.

### Versions & Modlist
**Forge version:** 31.2.31
**Immersive Engineering version:** `1.15.2-3.1-111` (Latest release on curseforge)

**Comment by BluSunrize** [comment]
I mean, if it crashed, there is a crashlog.
Please put your latest.log on pastebin and link it here.

**Comment by Kai-Kramer** [comment]
[Here is the log.](https://pastebin.com/yCEYDjfj)

It doesn't outright crash. It just hangs. All I get is "`Can't keep up! Is the server overloaded? Running ... ms or ... ticks behind`" If you look at the task manager displayed in the video above, you can see that memory usage just keeps climbing.

[Here is another log with a longer wait time](https://pastebin.com/fFuaJDP7) (got to ~180,000 ms of stalled time before I killed it)

**Comment by malte0811** [comment]
Probably another infinite loop in the text splitter. I'll look into it.

What confused Blu (and me as well) is that "crash" is quite well defined for us, and anything we consider a crash will produce some sort of log. If you had described it as a "hang" it would have been clear that there probably isn't any log.

**Comment by malte0811** [comment]
Can you test whether it still happens with [this](https://ci.blamejared.com/job/Immersive%20Engineering/job/1.15/44/) build of IE? I never got an infinite loop while testing, but I fixed a bunch of other issues with the `badEyesight` option.

**Comment by Kai-Kramer** [comment]
Tested with `badEyeSight = true` a full [modlist](https://pastebin.com/UnEEbHj9), no issues when opening book or when reading entries--All entries have been checked.
