### ISSUE TITLE
[1.16.1] Railgun energy capacity is bugged after installing the Additional Capacitor

### ISSUE THREAD

**Issue by Alex34fggh** [BluSunrize/ImmersiveEngineering#4202]
The railgun energy capacity is bugged in the release 1.16.1-3.1-112,that is,when I put the railgun in the Engineer's Workbench and I attach the Additional Capacitors upgrade,it seems to remain at the same maximum energy limit it had before the capacitors were fitted (Before the capacitors were fitted,it had a maximum capacity of 1600 Flux and it remained the same maximum capacity of 1600 Flux)

The mods used were:
AdditionalEnchantedMiner-1.16.1-16.0.7
car-1.16.1-1.0.11
ImmersiveEngineering-1.16.1-3.1-112
Mekanism-1.16.1-10.0.8.431
ScalableCatsForce-2.13.2-build-2-with-library

**Comment by BluSunrize** [comment]
Lol yes.
That would be because those capacitors don't increase storage, they reduce the railguns chargeup time.

Read the Manual.
