### ISSUE TITLE
[1.16.1-3.1.1-pre.35] Assembler Multiblock Won't Form (Conveyor Rotates)

### ISSUE THREAD

**Issue by DeadlySwede** [BluSunrize/ImmersiveEngineering#4205]
### Description of the issue:
Clicking on conveyor belt is supposed to form assembler multiblock but all it does is rotate the conveyor. It was working in the previous test server version (maven build 18?) so it may have something to do with fix for #4201. It would make sense that the conveyor would rotate if it was not detected as a trigger.

### Crashlog:
None,

### Versions & Modlist

Test Server Mods:

- Forge 32.0.108
- ImmersiveEngineering-1.16.1-3.1.1-pre.35 (Maven Build 25)
- Quark-r2.2-260
- AutoRegLib-1.6-43
- jei-1.16.1-7.0.0.6

Optional Mods:

- XaerosWorldMap_1.10.0_Forge_1.16.1
- Xaeros_Minimap_20.20.0_Forge_1.16.1

**Comment by malte0811** [comment]
Try clicking on the side of the conveyor, I forgot to account for clicking on the top face while looking in the correct direction in the new trigger code.
