### ISSUE TITLE
Immersive engineering connectors crashing the server

### ISSUE THREAD

**Issue by Gallaf** [BluSunrize/ImmersiveEngineering#4208]
During my Valhesia 3 (1.16.1) server daily restart forge crashes and provides the crash log attached: 
[crash-2020-08-13_17.31.06-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5071371/crash-2020-08-13_17.31.06-server.txt)

**Comment by BluSunrize** [comment]
Duplicate of #4181, didn't abide the issue template, didn't read the contribution guidelines.
Closed.
