### ISSUE TITLE
Uranium &  Quarzite,  Very rare or not Generating?

### ISSUE THREAD

**Issue by Elvarion** [BluSunrize/ImmersiveEngineering#421]
ImmersiveEngineering-0.5.4

Ive used the Core sampler on 80 valid locations now and have yet to find a single Uranium or Quarzite Vein. They are listed in the Engineer's Manual, so they should exist i assume.

The book doesnt say anything about some veins being in the Nether, but since Quarzite contains nether quartz they might be only found in there? Havent sampled the nether really..

We have BigReactors and in the config Yellorium is registered as Uranium (We dont have IC2)

**Comment by BluSunrize** [comment]
1) You just got unlucky, the definitely generate. They just have a lower chance.
2) Mineral distribution is to change drastically in Version 0.6. Maybe you'll be luckier then ^^

**Comment by Elvarion** [comment]
1) Ok, Im always unlucky =p
2) Sounds great ^^, In the meantime guess ill spelunker more and see if I can find the elusive Uranium Vein =D

**Comment by happysmash27** [comment]
I've personally found at least two uranium veins, but am still looking for quarzite.

**Comment by happysmash27** [comment]
Looking at IEContent.java, it appears that Quarzite is half as likely to appear as Uranium.
