### ISSUE TITLE
[1.16.1] The Vacuum Tube crafting animation of Automated Workbench bug

### ISSUE THREAD

**Issue by KhanhPham05** [BluSunrize/ImmersiveEngineering#4211]
Game Version+ IE version + Forge version:
[1.16.1] - [3.1-112] - [32.0.108]

Bug description
 
Vacuum Tube during crafting have wrong animation, recipe needs glass, redstone, Nickel plate, copper wire but when it crafting the animation shown 4 glasses instead of the ingredients needs

Step to see the glitch 
`Step 1:` Form the Automated Workbench multiblock and give it some power
`Step 2:` Give it the required ingredients for the vacuum tube
`Step 3:` Watch the animation.

![90255818-0253bd80-de6f-11ea-9787-8534d09358e4](https://user-images.githubusercontent.com/68932626/90256468-fe746b00-de6f-11ea-9469-fc1a115b415c.png)

**Comment by BluSunrize** [comment]
I'm unable to reproduce this. Please provide pictures.

**Comment by KhanhPham05** [comment]
> I'm unable to reproduce this. Please provide pictures.

here you go !!
![2020-08-14_19 42 31](https://user-images.githubusercontent.com/68932626/90255818-0253bd80-de6f-11ea-9787-8534d09358e4.png)

**Comment by BluSunrize** [comment]
1. Is this on a server or in a singleplayer world?

2. Can you reproduce this in an instance with just IE?

**Comment by KhanhPham05** [comment]
> 1. Is this on a server or in a singleplayer world?
> 2. Can you reproduce this in an instance with just IE?

This is just a single player and that my own Instance

**Comment by BluSunrize** [comment]
So please try it with just IE and see if the issue persists. It says so in the issue template, which you blatantly ignored.

**Comment by KhanhPham05** [comment]
It's still there 
![2020-08-15_08 10 34](https://user-images.githubusercontent.com/68932626/90302302-6ad28700-decf-11ea-9048-6dbe597ce901.png)

**Comment by KhanhPham05** [comment]
But it still happened
![2020-08-15_08 10 34](https://user-images.githubusercontent.com/68932626/90302325-a0777000-decf-11ea-9ecc-7d81edb3aa85.png)

**Comment by BluSunrize** [comment]
Like I said, please try it in an instance with *just IE* and no other mods!

**Comment by KhanhPham05** [comment]
> Like I said, please try it in an instance with _just IE_ and no other mods!
here is the image in another profile with NO OTHER MOD
![2020-08-16_14 45 14](https://user-images.githubusercontent.com/68932626/90329493-8a50d900-dfcf-11ea-9012-126b8ae126a9.png)

**Comment by BluSunrize** [comment]
Please try this again in a new instance using the IE release that came out today, **1.16.1-3.2.0-115**

**Comment by BluSunrize** [comment]
Confirmed this in a recent instance myself.
@SkySom broke it:

https://github.com/BluSunrize/ImmersiveEngineering/commit/f693505764a4a1743792e26cb1aa92fc67d4bf34#diff-fcb18ac86c36c026f3a83ffd2fffce06L291-R291

**Comment by BluSunrize** [comment]
Fixed for future releases
