### ISSUE TITLE
[1.16.1] - Crashed when trying to mine with mining drill

### ISSUE THREAD

**Issue by ChronHD** [BluSunrize/ImmersiveEngineering#4212]
I was on a server and when i mined with the drill with 3 speed upgrades, steel head and oxi tank, i crashed instantly after the blocks broke and now cant log back in. I had no oil in my drill. Error is "Already building".

**Comment by BluSunrize** [comment]
Likely to be a duplicate, hard to say given how no log or requested info was provided.

Please search recent issues next time. Fixed for upcoming releases.
