### ISSUE TITLE
[1.16] Feature Request: Rotated Vertical Treated Wood Planks

### ISSUE THREAD

**Issue by shartte** [BluSunrize/ImmersiveEngineering#4213]
This is short. While building my base with immersive engineering blocks, I ran into this:

![image](https://user-images.githubusercontent.com/1261399/90279331-522f8600-de69-11ea-9a5a-20d41dcb86d7.png)

I don't think (at least I could not find them) there are rotated variants of the vertical treated wood planks, which I hereby would like to request :-)

**Comment by BluSunrize** [comment]
Not worth the effort tbh. Vanilla doesn't do this for any planks either, it would just cause confusion.

**Comment by shartte** [comment]
Awwwwwwwww but the aesthetics :-(
