### ISSUE TITLE
[1.16.1] No net handler found

### ISSUE THREAD

**Issue by hxck** [BluSunrize/ImmersiveEngineering#4214]
**Description**: I just built a water wheel and when I put an LV Connector on the Kinetic Dynamo I crashed instantly. IE was added today in an existing world with other mods already present. World is Single Player open to LAN.

Creating a test world and running it on the same Forge and IE versions with no other mods present doesn't crash.

**Crashlog**: Full log [here](https://paste2.org/H8JIO9Gc).

**Versions and Modlist**: Modlist in the crashlog. Forge is **32.0.99** and IE is **ImmersiveEngineering-1.16.1-3.1-112**.

**Comment by malte0811** [comment]
This is a known issue with Optifine. Someone reported that updating OF fixes it, I haven't tested this myself.

**Comment by hxck** [comment]
Can confirm. Issue was present in **OptiFine_1.16.1_HD_U_G2_pre13_MOD** but after an update to **OptiFine_1.16.1_HD_U_G2_MOD** (non-preview build) the crash stopped.

Thanks.
