### ISSUE TITLE
[Multiple] Issues wih the Assembler

### ISSUE THREAD

**Issue by BluSunrize** [BluSunrize/ImmersiveEngineering#4216]
Found on Forgecraft. The assembler does not seem to properly handle which positions can have a pipe attached. This pipe *can* input.

![image](https://i.imgur.com/QW1h96p.png)

**Comment by BluSunrize** [comment]
Additionally, JEI integration appears to be borked, it's showing the message of "All pattern slots are filled" even though they are all empty.

![image](https://i.imgur.com/h4Ibfal.png)

**Comment by BluSunrize** [comment]
And it doesn't craft concrete. Probably an issue with the fluid ingredients.

![image](https://i.imgur.com/165zpRj.png)

**Comment by malte0811** [comment]
This looks like a mod interaction of some sort to me, none of the 3 issues is present in either my 1.14 or my 1.16 dev environment.

**Comment by BluSunrize** [comment]
That makes it worse. With the size of the FC pack, this will be a nightmare to debug.
