### ISSUE TITLE
[1.15.2] - modloading-worker-[STDERR/]: blusunrize.DynamicModelLoader:

### ISSUE THREAD

**Issue by SirOaken** [BluSunrize/ImmersiveEngineering#4217]
### Description of the issue:
Not sure how it affects gameplay. Is somthing I noticed in my logs and wanted to report the error.

### Crashlog:
-V- Error starts @ line 529 -V-
Full Log(Fully Modded)- https://paste.ee/p/k5zlT
-V-Error starts @ line 117 -V-
Full Log(Only IE/Forge)- https://paste.ee/p/wx2gs

### Versions & Modlist
Heavly modded list- https://paste.ee/p/wzLRo

**Comment by BluSunrize** [comment]
Logs have expired, issue unclear.

Mutliple updates since.
