### ISSUE TITLE
Automated Workbench form issue

### ISSUE THREAD

**Issue by KhanhPham05** [BluSunrize/ImmersiveEngineering#4218]
When i build the Automated Workbench with vertical or packed treated wood slab i can not form but the horizontal (normal) treated wood can !
As you can see in the picture, the right one is correct but the left (use other type of treated wood slab) can not
![2020-08-16_14 44 03](https://user-images.githubusercontent.com/68932626/90329533-dc91fa00-dfcf-11ea-8468-323556678731.png)

**Comment by malte0811** [comment]
Already fixed in 081e6207ac3175345f5cadb207c1e6b3e1ada99b
