### ISSUE TITLE
[1.15.2] Conveyor Belt Rubberbanding - Forge 31.2.33 - IE v1.15.2-3.1-111

### ISSUE THREAD

**Issue by Shtreudel** [BluSunrize/ImmersiveEngineering#4221]
I'm currently troubleshooting various issues revolving around Immersive Engineering. My largest concern is that items on conveyor belts are rubberbanding when I am on a server. They eventually make their way into the chest/assembler/etc but it takes significantly longer than it should under normal conditions.

pastebin of mods currently being used- https://pastebin.com/AcMFHwuk

I have tested conveyors that are not connected to any structures and the result is the same. I've also tested a large number of items and they also produce the same result. If I place my character on the belt, I move normally.

I created a new instance of forge minecraft (same version) and only installed immersive engineering (same version). I spawned a local world and tested conveyor belts. They worked normally.

Next I spawned a local world for the instance I'm using with all of my mods (same as the server's list). I tested the conveyor belts and they worked fine.

So...
local_no_extra_mods = success
local_all_mods = success
online_all_mods = buggy

So they are only acting buggy when I am connected to an online server. It's a local server I have at my house over a LAN connection. I've checked the server vitals and logs and neither indicate the server is struggling to keep up. My ticks are a constant 20, it never yells that it's falling behind, and the server has not crashed once yet. 

Looking through my logs the only out of the ordinary reference to IE is when I am connecting to the server. Not sure what this is.

**[16Aug2020 20:58:15.731] [Netty Epoll Server IO #6/ERROR] [net.minecraft.command.arguments.ArgumentTypes/]: Could not serialize blusunrize.immersiveengineering.common.util.commands.CommandMineral$MineralArgument@4a44a702 (class blusunrize.immersiveengineering.common.util.commands.CommandMineral$MineralArgument) - will not be sent to client!**

I'd hate to think it's simply a network issue.
It is a relatively large list of mods but I have used conveyor belts in the past on servers with very large lists before. Notably MC Eternal on 1.12.2 - in fact I had an entire factory setup with conveyor belts with MC Eternal on a server and it all worked fine, even with the occasional "Can't keep up! Is the server overloaded?" alert. So definitely confused why they aren't keeping up now. Any help you could shed would be very much appreciated.

Thanks,
Shtreudel

**Comment by malte0811** [comment]
"Performant" and specifically its "fast item" option are known to cause this. Does it still happen when you disable that option on the server?

**Comment by Shtreudel** [comment]
@malte0811 
That did the trick! Thank you.

Tested various lengths, items, and machines and conveyor belts seem to be working fine after disabling "fast items" from performant.

**Comment by BluSunrize** [comment]
Excellent. Issue resolved.
