### ISSUE TITLE
[Suggestion] Better Silo RS/AE2

### ISSUE THREAD

**Issue by AdrenalineKick** [BluSunrize/ImmersiveEngineering#4223]
This is somewhat more of a cross-mod suggestion, but good nonetheless. The silo is a good multiblock structure that can store a good amount of items, but as far as i have noticed, it has a flaw regarding RS or/and AE2.

When linking the bottom of the silo to an external storage or a ME storage bus, it will only ''show'' the first stack of the whole silo in the storage system, which may suggest that the bottom block only stores 64 of one item, instead of the whole silo inventory.

It could also be a Refined Storage and AE2 issue, but my suggestion is therefore that the entirety of the silo storage is stored in the bottom.

**Comment by AdrenalineKick** [comment]
Also, the stack that is connected to the silo is not allowed to be pulled out of the silo through the Storage system

**Comment by BluSunrize** [comment]
I've not been able to improve it much further than I did with that commit.

For further improvements, I'd need someone who knows their way around RS more.
