### ISSUE TITLE
[1.16.1] Coke oven crash

### ISSUE THREAD

**Issue by drakosoldier298** [BluSunrize/ImmersiveEngineering#4226]
When trying to put anything into a coke oven it crashes, making it impossible to make coke coal. i even tried seeing what happens if i put something that doesnt belong like a torch, still crashes doesnt say i cant do it just crashes.
I first noticed this on a server i host, but recently tested it and foudn it happens in singleplayer as well
https://gist.github.com/drakosoldier298/e081ebb60b43072579a74e6c5ab03bee

 version 
ImmersiveEngineering-1.16.1-3.2.0-115
Forge 32.0.106
Mod list: This is pulled directly from the crash report.
https://gist.github.com/drakosoldier298/c6d5fe5265c382cc1e537c36924898dc

**Comment by BluSunrize** [comment]
Please be so kind to start your instance and log into your world, then grab the debug.log file from the instance's "logs" folder and put it on gist and link it here.
Something must have gone wrong when building the recipe lists.

**Comment by drakosoldier298** [comment]
https://gist.github.com/drakosoldier298/59dfe634501b9a5417f46818595d4eb7

**Comment by BluSunrize** [comment]
Can you try removing MoBlocks and see if that fixes the issue?

**Comment by BluSunrize** [comment]
Closed due to lack of response
