### ISSUE TITLE
1.16.1 crash on joining lan game because garden cloche?

### ISSUE THREAD

**Issue by Krutontar** [BluSunrize/ImmersiveEngineering#4227]
Forge 32.0.108
Mod ver 3.2.0.115

To reproduce?  Try to join a Open to LAN game.
As the host, I am having no issues.  I do have several cloches in my base and they work fine.

[crash-2020-08-17_22.29.16-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5087826/crash-2020-08-17_22.29.16-client.txt)

**Comment by BluSunrize** [comment]
@malte0811 can you get two instances to launch from IntelliJ? I'm getting issues with JVM binding, so I'm unsure how to debug this properly...

**Comment by malte0811** [comment]
I'm not sure what you mean by "JVM binding", but in general it should be possible. You'll need different user names in both instances, so I would start by duplicating the `runClient` run config and adding something like `--username Dev2`. After that it should just work (or at least did the last time I tried this, definitely pre-FG3).

**Comment by Krutontar** [comment]
The mod that was making the server blow up on boot got updated and I was finally able to get one loaded and when I try to join myself in proper server mode the same thing happens to me with the same error.  In case that helps that LAN mode isn't needed for debugging.
[crash-2020-08-20_18.29.11-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5105785/crash-2020-08-20_18.29.11-client.txt)
Here is the latest crash report if it helps.

**Comment by BluSunrize** [comment]
So the crash happens with a dedicated server? That's a relief, that at least means that LAN isn't a third special case for us to anticipate.

**Comment by BluSunrize** [comment]
Can you please provide the debug.log files from your client and the server?

**Comment by Krutontar** [comment]
[debug.log](https://github.com/BluSunrize/ImmersiveEngineering/files/5111304/debug.log)
[2020-08-20-1.log.gz](https://github.com/BluSunrize/ImmersiveEngineering/files/5111311/2020-08-20-1.log.gz)
[latest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/5111312/latest.log)
There wasn't a "debug.log" in the client folder so I attached what was there.

**Comment by Krutontar** [comment]
Seems to have been fixed in the latest version.  I can join via server mode and my friend could join via lan.

**Comment by BluSunrize** [comment]
Excellent!
