### ISSUE TITLE
Post texture not rendering when hit with hammer.

### ISSUE THREAD

**Issue by chyper111** [BluSunrize/ImmersiveEngineering#4228]
### Description of the issue:
When hitting the post with the hammer it doesn't render the extra arms even when adding connectors at y 62. it will render at other level but not that one for some reason.

### Versions & Modlist
1.15.2

**Comment by BluSunrize** [comment]
That's not a modlist.
Produce a debug crash.

**Comment by chyper111** [comment]
There was no crash this is a texture issue. Also what does the mod list have to do with this? Its Immersive Engineering that has the texture issue.

**Comment by BluSunrize** [comment]
And you clearly didn't read either the contribution guidelines, or the last message I sent.

A **debug** crash means holding down F3+C for 10 seconds. Do that, put the crashlog on https://pastebin.com, then link it here.

**Comment by BluSunrize** [comment]
Closed due to lack of response
