### ISSUE TITLE
1.16.1 IE crashing in the nether

### ISSUE THREAD

**Issue by giveashift** [BluSunrize/ImmersiveEngineering#4229]
I was in the nether, while looking in a certain direction the game crashes. When I loaded the save back up the last few minutes hadn't been saved. So i went to redo what was lost and it crashed again. So I loaded up, left the nether, saved, deleted the nether thinking maybe it was a corrupted block or chunk, did it again. Here's two crash reports.

https://pastebin.com/raw/QCsT1WjB
https://pastebin.com/raw/PSyGzJHG

This is ATM6 modpack, I also let them know but figured you'd want to know too.

**Comment by giveashift** [comment]
It's not just a specific chunk or block. I loaded up the save and flew many blocks in the opposite direction and it crashed again. The logs look pretty much identical.

**Comment by BluSunrize** [comment]
Can you please update IE and see if that resolves the issue?

**Comment by xTrildXx** [comment]
how do i update the IE because im having the same issue with the same crash report from the top

**Comment by CivilNikolas** [comment]
I think i encountered the same problem
[https://pastebin.com/62x3cYPW](https://pastebin.com/62x3cYPW)

**Comment by BluSunrize** [comment]
Closing this, the issue should be resolved.
