### ISSUE TITLE
[Decorative]Hemp-/ Concrete Slabs and Stairs

### ISSUE THREAD

**Issue by Bitterholz** [BluSunrize/ImmersiveEngineering#423]
Could we have some ples? :)

**Comment by Bitterholz** [comment]
Also just noticed you can't place Vanilla Doors on Hempcrete

**Comment by VermillionX** [comment]
Hempcrete and afaik, Concrete tiles as well are treated as transparent blocks. Light goes right through them and like glass, nothing can be attached to them.

**Comment by BluSunrize** [comment]
That is incorrect. You are probably still using the deprecated versions of those blocks, before they were shifted to their own block ID. Holding them in your inventory updates them.

http://puu.sh/kbUFz/ac5ff7c560.jpg

Proof that you can place stuff on them.

**Comment by VermillionX** [comment]
Indeed, you can place objects on them (0.5.4) however they are still treated as transparent blocks and light passes right through them.

http://i60.tinypic.com/33eiu1k.png

Proof that light passes through concrete, concrete tiles, hempcrete and treated planks. Alongside normal cobblestone for comparison (Ignore the pipes).

**Comment by Bitterholz** [comment]
I still cant Place doors or Pressure Plates on hempcrete XD (Didnt test Concrete)
and im using 0.5.4!

**Comment by James-T-Oudvoure** [comment]
I'm having this problem as well. Even Treated Wood Planks don't block light.
