### ISSUE TITLE
[1.12] Crusher Ignoring Ores If Muliple Mods Are Crushed At Once

### ISSUE THREAD

**Issue by Nijiru** [BluSunrize/ImmersiveEngineering#4230]
### Description of the issue:
When grinding ores from multiple mods, the Crusher seems to ignore the second and latter ores added if multiple are thrown in at once.  The grinder must be finished grinding before adding ores from a different mod.

All thrown in the top of a Creative Capacitor-powered Crusher outputting directly into a Wooden Storage Crate.  Ignoring the incidental grit (gold grit when grinding copper, etc)
All Copper: 1 stack Forestry, 1 stack IE, 1 stack Mystical World, 1 stack Techguns --> 2 stacks Copper Grit.
All Copper: 4 stacks Techguns --> 8 stacks Copper Grit.
All Copper: 8 Forestry, 8 IE, 8 Mystical World, 8 Techguns, 8 Forestry, 8 IE, 8 Mystical World, 8 Techguns --> 32 Copper Grit.
All Silver: 4 IE, 4 Mystical World --> 8 Silver Grit.
All Uranium: 4 Techguns, 4 IE --> 8 Uranium Grit.

### Versions & Modlist
IE: 0.12-98
Forestry: 3.10.1013
Mystical World: 1.12.2-1.8.4
Techguns: 1.12.2-2.0.2.0
Forge: 14.23.5.2854

**Comment by BluSunrize** [comment]
1.12 is no longer receiving any support.
