### ISSUE TITLE
[1.15] Allow use of blue ice with thermoelectric generator

### ISSUE THREAD

**Issue by djmattyg007** [BluSunrize/ImmersiveEngineering#4231]
It would be great if blue ice was supported with the thermoelectric generator. Blue ice is a vanilla minecraft block that can be crafted from 9 packed ice blocks, so it would make sense that its temperature is even lower than `200`.

### Versions & Modlist
Forge: 1.15.2-31.2.36
IE: 1.15.2-3.2.0-114

**Comment by BluSunrize** [comment]
Closed by https://github.com/BluSunrize/ImmersiveEngineering/commit/622621820a7492be30fd4d6bcdae87a0d4d0d027
