### ISSUE TITLE
[1.16.1] Wooden Post Major Lag

### ISSUE THREAD

**Issue by lewd-est** [BluSunrize/ImmersiveEngineering#4232]
Whenever i place down a wooden post, it lags significantly, to the point where i cannot move my character for like 5 seconds, i will add that pressing F1 will clear up the lag, however because of the lag i am unable to use them, I have yet to test if other posts are affected by this lag.

I am using Forge 32.0.108, Immersive Engineering 3.2.0-115

Modlist: https://pastebin.com/iK7t7JJs

**Comment by BluSunrize** [comment]
Please provide a debug crash.

Also, it would be great if you could collect actual profiling data with VisualVM.

**Comment by lewd-est** [comment]
whats a debug crash? how do i do that? is that the f3+c? i tried that and it didnt work sadly

**Comment by lewd-est** [comment]
nevermind i found out how to do it, it was ctrl + f3 + c, didnt show a crash report in the crash reports folder sadly

**Comment by BluSunrize** [comment]
You gotta hold it for 10 seconds. It will crash, and it will generate a log.

**Comment by malte0811** [comment]
Profiling data would be very useful. Install [sampler](http://files.player.to/sampler-1.95-1.16.1-forge.jar) on your client, run `/csampler start` (the chat GUI will tell you that the command doesn't exist when you type it, but it actually works), place a post and run `/csampler stop` when the lag is done. Then run `/csampler export` to generate the .nps file with the profiling data and post that here. The less time you have between `start` and placing the post/the end of the lag and `stop` the better.

**Comment by lewd-est** [comment]
i found the issue, it was a problem with a minimap mod not knowing what to color in the posts on the map, (or something to do with textures, either way deleting the mod solved the issue) thanks to everyone who helped solve it

**Comment by BluSunrize** [comment]
@lewd-est can you tell us which minimap mod that was, so we know for future reference?

**Comment by migueliux100** [comment]
I had the same problem, it was voxel map. Thx so much for saving me time.
