### ISSUE TITLE
Bees don't speed up hemp's growth (1.16.1)

### ISSUE THREAD

**Issue by PersuGames** [BluSunrize/ImmersiveEngineering#4235]
As all plantable crops in Minecraft get sped up by bees flying over them with nectar on their butts I think hemp should do so too. Please let me know if this is somehow intentional or just an oversight to be fixed :)

**Comment by BluSunrize** [comment]
Bees are hardcoded to work on instances of `CropsBlock`
IE's hemp isn't one of those, nor does it grow like normal crops. IE's hemp grows to a heigh of two and uses custom logic to accomplish that.

Hence, bees can't work on it, because there is no hooks in Forge to make that happen.
