### ISSUE TITLE
Add support for Pam's HarvestCraft 2

### ISSUE THREAD

**Issue by djmattyg007** [BluSunrize/ImmersiveEngineering#4238]
### Description of the issue:
It doesn't appear to be possible to grow crops added by Pam's HarvestCraft 2 - Crops in the Garden Cloche:

https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-crops

### Crashlog:
No crashlog

### Versions & Modlist
Forge:  1.15.2-31.2.36
IE: 1.15.2-3.2.0-114
pamhc2crops: 1.15.2-1.0.5

**Comment by BluSunrize** [comment]
You're correct, it's not possible. Feel free to contribute that.

**Comment by BluSunrize** [comment]
Closed due to lack of response.

Currently no plans to support Harvestcraft natively. Datapacks can accomplish this.
