### ISSUE TITLE
[1.16.1] Manual Shader section bug

### ISSUE THREAD

**Issue by KhanhPham05** [BluSunrize/ImmersiveEngineering#4240]
This is the Instance with **ONLY IE** 
Played in singleplayer 
### Description
This is a manual page bug which all the page text, images are glitched out of the book.
Shader receiving pages

![2020-08-21_16 28 10](https://user-images.githubusercontent.com/68932626/90892254-3a1ab200-e3e7-11ea-9f1e-d5296fa584e8.png)

**Comment by BluSunrize** [comment]
Please actually use the issue template. Pretty sure you've been told so before.


Issue has been reproduced on 1.16, other versions are fine.

**Comment by BluSunrize** [comment]
Fixed for future release
