### ISSUE TITLE
[1.12.2]Game crashes when trying to make a Fermenter

### ISSUE THREAD

**Issue by Eric-Li-7** [BluSunrize/ImmersiveEngineering#4243]
I was making alot of machines today but when I used the engineer's hammer on the completed fermenter structure the game lagged and then it crashed. Here is the crash report:

[crash-2020-08-24_10.19.53-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5115621/crash-2020-08-24_10.19.53-client.txt)

**Comment by Eric-Li-7** [comment]
and also I can't figure out how to put fluids into mixer

**Comment by mindforger** [comment]
did you have something in your off-hand?
can you reeanact this whole thing without optifine?

i see optifine in your log and something that seems to have to do with off-hand code

**Comment by Eric-Li-7** [comment]
> did you have something in your off-hand?
> can you reeanact this whole thing without optifine?
> 
> i see optifine in your log and something that seems to have to do with off-hand code
ok i'll try

**Comment by Eric-Li-7** [comment]
> did you have something in your off-hand?
> can you reeanact this whole thing without optifine?
> 
> i see optifine in your log and something that seems to have to do with off-hand code

ok I'll try

**Comment by BluSunrize** [comment]
Closed due to lack of feedback
