### ISSUE TITLE
immersive crashinering 

### ISSUE THREAD

**Issue by MustTitan** [BluSunrize/ImmersiveEngineering#4244]
I left some Garden cloche running during the night on a server and when I went in this morning the game crash when I loaded the Garden chunks (1.16.1)

Link do crash report ----> https://pastebin.com/iEaEGYXF

[crash-2020-08-24_10.13.10-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5118506/crash-2020-08-24_10.13.10-client.txt)

**Comment by mindforger** [comment]
isn't xaeros minimap a client only plugin?

**Comment by BluSunrize** [comment]
Yeah, the crash is a client crash, not a server crash, Mind.

Is this crash reproducible? Does it keep happening?

**Comment by BluSunrize** [comment]
Closed due to lack of response.
