### ISSUE TITLE
Not using config?

### ISSUE THREAD

**Issue by budgej** [BluSunrize/ImmersiveEngineering#4249]
### Description of the issue:

Immersive Engineering config does not appear to be loading.  Changes are not reflected in game.  I have been modifying configs/immersiveengineering-common.toml.  Wires are not damaging even though config has enableWireDamage = true, custom wire transfer rates are not loading, etc.

### Versions & Modlist
MC 1.15.2
Forge 31.2.31
IE-1.15.2-3.2.0-114
Mods:  https://pastebin.com/VCk6eZRy

**Comment by BluSunrize** [comment]
Wires will only damage you if power is going through. If the point your wires are leading to is full on energy, they will not do damage.

**Comment by malte0811** [comment]
> Wires will only damage you if power is going through. If the point your wires are leading to is full on energy, they will not do damage.

That should not be the case. My usual test case for wire damage is a wire attached to a creative cap and ending in a single relay. No sinks at all on that net, and certainly no "power going through the wire", but it should be able to kill you just fine.

**Comment by BluSunrize** [comment]
Hmm, I may have misremembered then.
Pictures of the setup might help!

**Comment by Devostar** [comment]
Hey I've got something similar, running a 1.15.2 server as well and changing the crusher time modifier as described in crusher_timeModifier = 1.0 to something like 0.5 or 0.25 or 0.1 does not change the recipe time at all, its always the same speed in game.

**Comment by BluSunrize** [comment]
Fixed by Malte

**Comment by WolfBullet** [comment]
i turned off wire dmg and had a lot of lag on game load and the wires still do dmg. Could this be the same issue I'm on one of the latest version (where can I see the version)

**Comment by BluSunrize** [comment]
File a new issue with extensive details. This one was closed 3 years ago.
