### ISSUE TITLE
[1.15.2] Core sample drill/Excavator chunk vein incompatibility with world painter maps

### ISSUE THREAD

**Issue by AllyJamy** [BluSunrize/ImmersiveEngineering#4250]
When using the core sample drill or excavator to dig up veins on terrain made in world painter, it will only dig up vein samples with no ores. This is due to the way mojang changed the way the world generation works in 1.14, where there is no longer a populate layer. In the generation for maps made in worldpainter post 1.14 it is no longer possible to use the populate layer. (All modded or vanilla plants, ores and trees have to be added manually). So this seems to not generate the vein chunk data the core sample drill uses for locating ores.

When exporting with worldpainter you can also generate vanilla terrain outside the area of the main map. So when doing that I can see while playing on the same map, in the normal vanilla terrain; IE ore vein chunks generate as they should. (When probing the terrain with the core drill). However when walking over into worldpainter terrain and doing the same there are no ore veins in any of the chunks.

I don't know how the generation of ore vein chunks is done in immersive engineering, but possibly it could be changed to support generation in chunks that are already ready made in the world folder?

Immersive Engineering version: **ImmersiveEngineering-1.15.2-3.1-111**
Forge version: **Forge 31.2.33**
WorldPainter - **version 2.7.17**

**Comment by BluSunrize** [comment]
I mean, if world painter doesn't have worldgen run normally, there's nothing we can do.

If you are using it to curate your terrain, you can always use IE's `mineral` command to curate your mineral veins too, by placing them manually.

**Comment by AllyJamy** [comment]
How do I use this command? and is there a list of all IE's commands somewhere?

Edit: Figured out the command

**Comment by BluSunrize** [comment]
I'll close this then, if you got it working
