### ISSUE TITLE
(Visual) Got the whole Immersive series, and now tanks with fluids in them display the purple and black texture.

### ISSUE THREAD

**Issue by Unusual-Danger** [BluSunrize/ImmersiveEngineering#4251]
### Description of the issue:
I decided to play MC today and also installed all the other immersive mods. I don't think its the other mods since the tanks looked fine yesterday and now give a bugged texture.
![2020-08-26_10 34 23](https://user-images.githubusercontent.com/69125944/91358900-7f086500-e7a8-11ea-91da-e004389d3930.png)

**Comment by BluSunrize** [comment]
1.12 is no longer supported. Looks like whatever fluid is in that tank failed to load its texture.
