### ISSUE TITLE
[1.14.4] Holding Revolver/Railgun drops FPS, especially with shaders

### ISSUE THREAD

**Issue by Koku0** [BluSunrize/ImmersiveEngineering#4253]
### Description of the issue:

Whenever I hold a railgun or revolver, my FPS drops. This issue gets worse as I add shaders and attachments. With Vsync on, the game becomes very stuttery and borderline unplayable. Without Vsync, the FPS still drops, but it's not as stuttery.

[Here is an Imgur gallery depicting the FPS drops.](https://imgur.com/a/QnKFgPy)

### Versions & Modlist:
**IE Version:** 3.2.0-113
**Forge Version:** 28.2.23
**Modlist:**
AI Improvements
AmbientSounds 3
AppleSkin
Aquaculture 2 
AstikorCarts
AutoRegLib
Better Advancements
Bookshelf
Botania
Clumps
Comforts
Create
Curios API (Forge)
Engineer's Decor
Falling Tree
Fast Leaf Decay
FastFurnace
FastWorkbench
Forbidden and Arcanus
Gauges and Switches
GraveStone Mod
Guard Villagers
Hwyla
Immersive Engineering
Immersive Posts
Immersive Railroading
JourneyMap
Just Enough Items (JEI)
Just Enough Resources (JER)
LibraryEx
Macaw's Bridges
Macaw's Doors
Macaw's Roofs
mGui
MixinBootstrap
Morpheus
Mouse Tweaks
MrCrayfish's Furniture Mod
MysticalLib
NetherEx
NetherPortalFix
OpenBlocks Elevator
OptiForge
Patchouli
Persistent Bits
Placebo
Quark
Redstone Gates
Regrowth
Simple Farming
Spice of Life: Carrot Edition
Storage Drawers
Storage Drawers Unlimited
Swamp Expansion
Tetra
The Endergetic Expansion
Thut Essentials
Track API
Traverse: Legacy Continued
Upgrade Aquatic
Voyage
Waila Harvestability
Wawla
YUNG's Better Caves

**Comment by BluSunrize** [comment]
I believe Malte has done some optimization. IE's weapons have complex models. We can't really reduce their complexity easily.
