### ISSUE TITLE
[1.15.2] Scaffolding variants are not climbable.

### ISSUE THREAD

**Issue by Kai-Kramer** [BluSunrize/ImmersiveEngineering#4254]
### Description of the issue:
Slabs and stairs for all three variants of each of Steel and Aluminum scaffolding cannot be climbed.
If I want to have scaffolding to climb up to a 0.5-height platform, I cannot cap the scaffolding with slabs because if I do, the scaffolding cannot be climbed to the top. The same goes for stairs capping off a length of scaffolding. If I wanted to climb up the backside of a staircase, I cannot climb to the top. In addition to this, faces are not culled when full scaffolding, slabs, and stairs are used together.

Less important, Covered ladders and conveyors also cannot be climbed (on the outside) and covered ladders are a little janky as well. Climbing scaffolding does not transition well onto covered ladders, and ladders cannot be placed on any faces of scaffolding, meaning that in order to climb up the inside of covered ladders, a non-scaffolding block has to be used to place ladders on.

### Crashlog:
This does not cause a crash.

### Versions & Modlist
Forge 31.2.36
Immersive Engineering 3.2.0-114
HWYLA 1.10.8-B72

**Comment by BluSunrize** [comment]
That's intentional. They match vanilla slabs and stairs in their behavior.
Covered conveyors and ladders are also not meant to be climbable.
