### ISSUE TITLE
Wire damage not occurring 

### ISSUE THREAD

**Issue by WingmanDraws** [BluSunrize/ImmersiveEngineering#4255]
It seems that even though the damage is enabled on a server and client (by default) the wires do not seem to damage players when powered. This is on the latest update of Valhelsia 2.

**Comment by malte0811** [comment]
Please try uninstalling "Performant" and see if that fixes the issue. Lithium would be another candidate, but I mostly suspect Performant.

**Comment by BluSunrize** [comment]
Closed due to lack of response
