### ISSUE TITLE
Concurrent Modification crash with SaveData

### ISSUE THREAD

**Issue by Darkere** [BluSunrize/ImmersiveEngineering#4256]
### Description of the issue:
Crashed. Not sure what exactly. Will try to ask the player that was online. But considering the crash I don't think its going to help. 

### Crashlog:
https://gist.github.com/Darkere/61dbbd75dd033a0852060b67621d9c1b

### Versions & Modlist
forge-1.16.1-32.0.108
ImmersiveEngineering-1.16.1-3.2.0-115

Pack: Enigmatica 6 0.2.14

**Comment by BluSunrize** [comment]
what the actual...
That call is in a `synchronized` bracket. That shouldn't be able to hit a CME.

@malte0811 do you have an idea what's happening here?

**Comment by malte0811** [comment]
Blu, *that* access is synchronized. All other accesses (e.g. [here](https://github.com/BluSunrize/ImmersiveEngineering/blob/27525b558bf3281b09b5f271c2112824b285bc16/src/main/java/blusunrize/immersiveengineering/api/excavator/ExcavatorHandler.java#L154), that one is probably causing the issue) are non-synchronized. So the synchronization only means that we can't ever have two threads simultaneously writing world save data.

**Comment by BluSunrize** [comment]
But wouldn't it crash on the other accesses then?

**Comment by malte0811** [comment]
No, why would it? All `synchronized` does is ensure that no two threads are in a `synchronized` section for the same object at the same time (the "later" thread has to wait until the"earlier" thread is out of that section). If you have one thread doing world gen and one saving data, the `synchronized` block in `IESaveData` might just as well not be there.
