### ISSUE TITLE
[1.16.1] Redstone Wire Connector

### ISSUE THREAD

**Issue by Wlnfr** [BluSunrize/ImmersiveEngineering#4257]
### Description of the issue:
I can't change redstone wire connector's mode from input to output. Tried screwdriver, hammer and even empty hand, right clicking/shift+right clicking, the only thing I can change is color by right clicking with a screwdriver.
### Crashlog:
No crash.

### Versions & Modlist
Minecraft 1.16.1 Forge 32.0.108
ImmersiveEngineering-1.16.1-3.2.0-115
Tested in a clean instance

**Comment by BluSunrize** [comment]
I can't replicate the issue.
I'm using the screwdriver and it opens the GUI, giving me access to the colours, as well as the big input/output button up top. Works just fine.

**Comment by Wlnfr** [comment]
Found the problem, it was my texture pack with dark GUI, it made the button almost invisible. Though I don't understand how. Sorry for wasting time.
