### ISSUE TITLE
[1.16.1] Crash

### ISSUE THREAD

**Issue by Wlnfr** [BluSunrize/ImmersiveEngineering#4259]
### Description of the issue:
Tried placing engineer's crafting table near a villager, after a few minutes of replacing it and making the villager recognize it as a valid workstation the game crashed, when I tried entering the world after reloading minecraft it crashed immediately.
From what I see in crashlogs it might have something to do with wires, so if needed I can list all placed wire connectors, relays  and machines in my world.
### Crashlog:
First crashlog(after villager workstation): https://pastebin.com/kLJGCkAY
Second crashlog(after trying to enter the world): https://pastebin.com/ir23vs9z
Log: https://pastebin.com/RLxyDctE
### Versions & Modlist
Minecraft 1.16.1 Forge 32.0.108
Mod list & versions: https://pastebin.com/42wSfZN3

Edit 1: Loaded the world after another 2 tries, will try to replicate the problem for more information.

**Comment by BluSunrize** [comment]
Should be resolved
