### ISSUE TITLE
[Request] Mechanical power tier.

### ISSUE THREAD

**Issue by raymondbh** [BluSunrize/ImmersiveEngineering#426]
First: Love the mod, love the artwork! Thank you!

However: The leap to electricity seems a little fast for this mod. A realistic mod like this should have a tier more before getting to electricity, maybe two... Mechanical power, like the one in RotaryCraft. And then maybe steam power before ending up at electricity...

Anyway, the mod is awesome, this is just an idea (that would make it even more awesome.... :P ).

**Comment by BluSunrize** [comment]
Nope. That's just not what this mod is about =)

**Comment by raymondbh** [comment]
Ohhh, that's pitty.
