### ISSUE TITLE
[Inconsistency] Alloy furnace vs grit not the same output

### ISSUE THREAD

**Issue by Rosethorns** [BluSunrize/ImmersiveEngineering#4260]
### Description of the issue:
The alloy furnace and arc furnace produce 2 ingots per electrum/constantan recipe. However mixing grit only provides 1 grit as output. Therefore making alloys via grit is half as effective as using the alloy furnace/arc furnace

### Versions & Modlist
IE: ImmersiveEngineering-1.16.1-4.0.0-pre.28
Forge: 1.16.1-32.0.108

**Comment by Protected** [comment]
You get two grit per ore from the crusher, though...

**Comment by Rosethorns** [comment]
1 silver ingot + 1 gold ingot in an alloy furnace = 2 electrum ingots
1 silver ingot in the crusher = 1 silver grit
1 gold ingot in the crusher = 1 gold grit
1 silver grit = 1 silver ingot
1 gold grit = 1 gold ingot
1 silver grit + 1 gold grit = 1 electrum grit.

Inconsistent. But thanks for your observation @Protected
