### ISSUE TITLE
Immersive engineering crash due to wire?

### ISSUE THREAD

**Issue by WingmanDraws** [BluSunrize/ImmersiveEngineering#4262]
It seems that a wire placed within my world has begun crashing the server. This is with no players on. LagWatchdog catches it and shuts down the server before I can even get on. The server remains stable when the wire/connectors have been broken!

**Comment by malte0811** [comment]
Closing as the template/contributing guidelines have been completely ignored and, even ignoring them, absolutely no useful information has been provided.
