### ISSUE TITLE
Varied errors. Some on startup. 1.16.1 no crash.

### ISSUE THREAD

**Issue by gsvfuture20** [BluSunrize/ImmersiveEngineering#4263]
### Description of the issue:
Standalone Mod log:
[https://pastebin.com/1jLNuTPp](url)

Log with only mentions toward IE in custom pack:
[https://pastebin.com/Z4aGa7CY](url)

Full log of custom pack.
[https://pastebin.com/F0AkuwHj](url)

### Versions & Modlist

Standalone:

![Screenshot_117](https://user-images.githubusercontent.com/56543836/91647569-ce0cff00-ea21-11ea-952a-d34537ffb53b.png)

Custom pack:
![Screenshot_118](https://user-images.githubusercontent.com/56543836/91647609-38be3a80-ea22-11ea-9a47-23f447467b4e.png)

![Screenshot_119](https://user-images.githubusercontent.com/56543836/91647608-3825a400-ea22-11ea-9fdb-97ce782752a2.png)

**Comment by mindforger** [comment]
your links seem broken

**Comment by gsvfuture20** [comment]
these work
https://pastebin.com/F0AkuwHj
https://pastebin.com/Z4aGa7CY
https://pastebin.com/1jLNuTPp

**Comment by BluSunrize** [comment]
What issues are you experiencing? Nothing in your logs indicates any crashes or errors. What's the problem here?

**Comment by BluSunrize** [comment]
Closed due to lack of response.
