### ISSUE TITLE
Quark conflict with engineers workbench. I need the line that would exclude it from quark config please.

### ISSUE THREAD

**Issue by chyper111** [BluSunrize/ImmersiveEngineering#4265]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
Sorry I don't have a crashlog I just need a line of code that will excluded your workbench from quarks sort buttons options.
it will look like this.

"com.tiviacz.travelersbackpack.client.gui.TravelersBackpackScreen"

This is just another code for travelers backpack I had to use for the same reason but the person that gave it to me didn't explain how or where to get it so I don't know how to find yours so as not to bug you about it. Thanks for any help you could give.

### Crashlog:
It didn't crash just need help with one line of code. Sorry...

### Versions & Modlist
Mod Version:0.15-108
Forge:31.2.36

**Comment by malte0811** [comment]
`blusunrize.immersiveengineering.client.gui.CraftingTableScreen`

You can find the name by setting `Print Screen Classnames` to true in the quark config, I expect that will either log the names to the log or to chat.

**Comment by chyper111** [comment]
Thanks
