### ISSUE TITLE
1.16.1 Powered Lantern Bugged

### ISSUE THREAD

**Issue by VonHelson** [BluSunrize/ImmersiveEngineering#4266]
Powered lantern doesn't want to work. When you connect LV wire via the LV capacitor, it'll turn on but not emit any light. I fixed this by removing Optiforge & Optifine and re-loading the game. I then removed and replaced the lantern but the same thing happened. Additionally, once the lantern was removed, the light source remained. This also happened when I re-installed Optiforge & Optifine.

**Comment by BluSunrize** [comment]
You should have followed the issue template.
Provide a debug crash and screenshots please.

**Comment by BluSunrize** [comment]
Closed due to lack of response.
