### ISSUE TITLE
[1.15.2] Metal press and refinery models not rendering correctly

### ISSUE THREAD

**Issue by Alsett** [BluSunrize/ImmersiveEngineering#4267]
### Description of the issue:
Metal press and refinery look weird and glitchy. Some of my metal presses look fine so not sure what the determining factor is.
https://imgur.com/a/1Xh2Ow4

### Versions & Modlist
Forge 31.2.33
ImmersiveEngineering-1.15.2-4.0.0-117.3
Quark-r2.1-245
AutoRegLib-1.5-40
engineersdecor-1.15.2-1.1.1-b1

**Comment by TwistedGate** [comment]
I've collected some screenshots during day.
**And with Minimal Setup**

**`Forge: 31.2.0`
`IE: ImmersiveEngineering-1.15.2-4.0.0-117` (From CF)**

![2020-09-02_00 40 12](https://user-images.githubusercontent.com/31029668/91913219-65d64b80-ecb5-11ea-9f0c-433f367f29d1.png)

![2020-09-02_00 40 20](https://user-images.githubusercontent.com/31029668/91913223-666ee200-ecb5-11ea-9eae-0ce0d7097f22.png)

![2020-09-02_00 40 40](https://user-images.githubusercontent.com/31029668/91913225-67077880-ecb5-11ea-9044-380d04351418.png)

![2020-09-02_00 42 04](https://user-images.githubusercontent.com/31029668/91913227-67a00f00-ecb5-11ea-8b0f-2f3a53bdff94.png)

Same as above but flipped
![2020-09-02_00 42 34](https://user-images.githubusercontent.com/31029668/91913228-67a00f00-ecb5-11ea-8f3c-bd11b5dc4c88.png)

**Comment by malte0811** [comment]
Fixed in 837a08a
