### ISSUE TITLE
Immersive Engineering Squeezer Recipe is broken! 1.10.2 Harvest Festival Compatibility

### ISSUE THREAD

**Issue by Vyxniir** [BluSunrize/ImmersiveEngineering#4269]
I am playing the twitch modpack for Harvest festival lite, immersive engineering is included by default in this mod pack but it seems there is a broken recipe that was never noticed or never fixed, I would happily fix it myself but i haven't the slightest clue how to do so.

Long story short after screwing with it all night this was what I was able to learn:
Since harvest festival uses its own seeds for everything all of the "traditional" seeds are MIA from the game and only accessible through the creative menu. As a result of this getting plant oil from the squeezer is practically impossible, or so i originally thought, Upon further investigation i discovered that a recipe for the IM Squeezer to use the Harvest Festival seed Bags exists, however it is a broken recipe. Rather than allowing you to use any of the seed bags from harvest festival as you might think it instead forces you to use a nonexistent item known as "any seeds" and as a result doesn't actually work with any of the various harvest festival seed bags because they aren't literally called "any seeds". 

I haven't got a clue how to fix the recipe or alter the Industrial Hemp plant to allow dropping hemp seeds upon harvesting with a sickle.

please save me

**Comment by Vyxniir** [comment]
@BluSunrize

**Comment by BluSunrize** [comment]
1) You don't need to ping me, this is my repo, I see everything.
2) You provided *zero* information on the versions you use. You just deleted the issue template and gave me a wall of text that tells me *nothing*.

So no. I can't help you, unless you give me the infomation I need. Read the contribution guidelines, read the issue template, and provide what we ask for.

**Comment by Vyxniir** [comment]
sorry I don't normally post on these forums....

Minecraft Version 1.10.2
Harvest-Festival-1.10.2-0.5.27
ImmersiveEngineering-0.10-61
forge-12.18.3.2511

**Comment by BluSunrize** [comment]
Cool, all support for versions below 1.14 has ceased.

We haven't supported 1.10 in *years*

**Comment by Vyxniir** [comment]
really just no help at all? I'm not asking for a massive amount of help here just how to re-enable the hemp seed drops upon farming or to fix the broken recipe for the squeezer. I literally cannot get bio-diesel without seeds to make plant oil

This is literally the top 3 featured mod packs on twitch and a game breaking broken recipe like this is completely disregarded just because its an older version?

You are my last ditched effort ive been digging through the files with winrar all day and most of last night and im at a complete loss of what to do to fix this, ive googled everything i can think of as well. 
If i could just find where this elusive "any seeds" Squeezer Recipe code is at i might be able to alter it to work for the various seed bags like it should by just copying the code and altering its item names for the different seed bags

**Comment by Vyxniir** [comment]
http://minetweaker3.powerofbytes.com/wiki/Mods:Immersive_Engineering_Support

i found this on the minetweaker talking about the squeezer and how to create recipes for it but i cant find where in the world that file is even located to see its recipes and alter the "any seeds" recipe thats broken

**Comment by BluSunrize** [comment]
Yeah you need to learn how to use Minetweaker. Read yourself through their documentation thoroughly and learn how it works. Then you can use the IE compatability for it to fix your issue.

And yes, that is all the support we offer, because you are playing with a version that is outdated by multiple years, and we refuse of offer any further support for that. We don't have a team of people to handle this. We do this in our free time, and it's already a struggle to just keep up with Mojang, let alone offer legacy support for 1.10, a version we last released an update for in January of 2017, over three years ago.
