### ISSUE TITLE
[1.15.2] The player can swim through the sides of covered conveyor belts

### ISSUE THREAD

**Issue by 00-Steven** [BluSunrize/ImmersiveEngineering#4270]
### Description of the issue:
When forcing yourself into the 1 block high swimming/crawling stance using a trapdoor, you can fit into covered conveyor belts. You can, however, also _swim through the sides of the covered conveyor belt_. 

### Versions & Modlist
IE: ImmersiveEngineering-1.15.2-4.0.0-117
Forge: 31.2.26

**Comment by BluSunrize** [comment]
I don't see this as an issue. This shouldn't have any negative effect on your game.
