### ISSUE TITLE
[1.12.2] Client Crash on login with Pumpjack and Arc Furnace 

### ISSUE THREAD

**Issue by ChibiVampz** [BluSunrize/ImmersiveEngineering#4273]
Heyo, I'm playing Sevtech 3.1.6, So I apologize if its in the wrong spot, or if this issue is only related to Sevtech. Anyways whenever I load in, I crash from my Arc furnace, I had this issue in the past with the Pumpjack as well as other players(I am on a server), So just to make sure you have light on the bugs, here's my crash report.
https://pastebin.pl/view/9bc477d2
Ill also post the Pumpjack one if you need it
https://pastebin.pl/view/c952c87b
Thanks!

**Comment by malte0811** [comment]
1.12.2 is no longer supported.
