### ISSUE TITLE
Handheld ammeter item suggestion

### ISSUE THREAD

**Issue by jcarrete5** [BluSunrize/ImmersiveEngineering#4274]
A voltmeter item already exists and can measure average loss and stored energy. I propose that a handheld ammeter also be added that acts like a current transformer but can be used as an item rather than having to be placed in the world. I suppose it would work by sneak-right-clicking a connector like you would with a voltmeter and would tell you all the RF flowing into and out of the connector

**Comment by BluSunrize** [comment]
That's not viable to implement.
The current transformer keeps a log of power going through it. Other connectors don't, and shouldn't, due to the unnecessary amount of data collected.
