### ISSUE TITLE
Can not right-click with hammer to create coke oven :(

### ISSUE THREAD

**Issue by dtoxftw** [BluSunrize/ImmersiveEngineering#4275]
R.A.D. modpack 1.12.2

3x3 (filled) coke brinks but right clicking with an engineer's hammer doesn't do anything. The hammer doesn't even swing. 

ImmersiveEngineering-0.12-89

![Minecraft 1 12 2 9_5_2020 7_54_22 AM](https://user-images.githubusercontent.com/57923837/92307762-84567400-ef4d-11ea-917d-eb00645a3e41.png)

**Comment by BluSunrize** [comment]
1.12 is no longer supported.
