### ISSUE TITLE
[1.15] Top of Garden Cloche can be rotated independently

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#4278]
### Description of the issue:
Using the hammer on a Cloche's top half rotates it, but not the bottom half and viceversa. This might also be causing a related issue with placing it in Creative mode, where Sneak+clicking the top of the cloche to get a copy of it and placing will cause a glitched version to be placed.

### Versions & Modlist
MC Version: 1.15.2
Forge Version: 31.2.30
IE Version: 1.15.2-3.1-117

**Comment by malte0811** [comment]
I've fixed the "main" issue, will push the fix later. I don't fully understand what you're saying in the second issue (when did sneak-click become pick-clock?), but you should make a separate issue for that.
