### ISSUE TITLE
[1.15] Blast Furnace Pre-Heaters don't animate

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#4281]
### Description of the issue:
The pre-heaters seem to consume energy while iron is being turned into steel, but they don't glow red, nor the fan inside spins.

### Versions & Modlist
MC Version: 1.15.2
Forge Version: 31.2.30
IE Version: 1.15.2-3.1-117

**Comment by BluSunrize** [comment]
They never have since 1.8
