### ISSUE TITLE
[1.15] Garden Cloche doesn't display soil inside

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#4282]
### Description of the issue:
The soil texture doesn't render on the inside of the cloche model.
![2020-09-06_16 50 50](https://user-images.githubusercontent.com/52493793/92329723-45b1de00-f061-11ea-9997-c7e64ad43fe3.png)

### Versions & Modlist
MC Version: 1.15.2
Forge Version: 31.2.30
IE Version: 1.15.2-3.1-117

**Comment by malte0811** [comment]
Fixed in 5ec6b29739c0820c3ac627ebd1435e283d97a4a2
