### ISSUE TITLE
[1.16.1] Wire Connection Crash

### ISSUE THREAD

**Issue by TimGoll** [BluSunrize/ImmersiveEngineering#4284]
### Description of the issue:
I did not find any duplicate of this, so here we go. This crash seems to happen on serverstart if no player is on the server. I guess the chunks are unloaded again? At least the crash does not happen while playing in the close area of the wire connection.
![image](https://user-images.githubusercontent.com/13639408/92486259-285d4b00-f1ec-11ea-919d-9cb004be5f22.png)
This simple connection is the one causing the issue (maybe other connection would cause it as well)

### Crashlog:
[Crashlog on Gist](https://gist.github.com/TimGoll/4ea6c269a8228600f561276ca1e0a628)

### Versions & Modlist
Minecraft 1.16.1
Forge 32.0.108
IE 4.0.0-118

The modlist can be found in the crashreport

**Comment by TimGoll** [comment]
I investigated this a bit further.
Yesterday we played for hours without any crash. But as soon as we left the server started crashing again. Additionally the same thing happened as soon as we all went into the nether.
So I guess it really has something todo with chunkunloading.

**Comment by BluSunrize** [comment]
This should be fixed in recent releases.
