### ISSUE TITLE
[1.15] Structural Arms do not match hitboxes

### ISSUE THREAD

**Issue by cybercat5555** [BluSunrize/ImmersiveEngineering#4286]
### Description of the issue:
When placing a Structural Arm their model does not match the hitbox, the model always faces east. However the hitbox is correct and respects the direction it was placed.
![2020-09-09_00 05 50](https://user-images.githubusercontent.com/17956808/92558461-8e71be80-f23c-11ea-9d66-84ac51ccc857.png)
![2020-09-09_00 06 04](https://user-images.githubusercontent.com/17956808/92558469-93cf0900-f23c-11ea-9e65-c4579418b8d6.png)

### Crashlog:
N/A

### Versions & Modlist
Forge 31.2.36
IE 1.15.2-4.0.0-117

Other Mods: 
Abnormals-Core-1.15.2-1.0.6.jar
Atmospheric-1.15.2-1.4.1.jar
autumnity-1.3.3-1.15.2.jar
betteranimals-1.15.2-5.0.3.2.jar
betteranimalsplus-1.15.2-8.2.1.96.jar
Bloomful-1.15.2-1.4.1.jar
corpse-1.15.2-1.0.6.jar
CTM-MC1.15.2-1.1.1.13.jar
engineersdecor-1.15.2-1.1.1.jar
fairylights-3.0.10-1.15.2.jar
goprone-1.15.x-1.3.0.jar
Hwyla-forge-1.10.8-B72_1.15.2.jar
jei-1.15.2-6.0.2.12.jar
journeymap-1.15.2-5.7.0b3.jar
NaturesCompass-1.15.2-1.8.5.jar
portality-1.15.2-2.1.2-aaa257f.jar
scuba-gear-1.15.2-1.0.1.jar
sit-1.15.1-v1.3.jar
titanium-1.15.2-2.4.2.jar
Upgrade-Aquatic-1.15.2-1.7.1.jar
worldedit-forge-mc1.15.2-7.1.0.jar

**Comment by BluSunrize** [comment]
They are not limited to east-facing for me.
Can you reproduce this in an instance with *just* IE installed?

**Comment by cybercat5555** [comment]
Seems with just IE (and minor client mods) the arms function correctly, so it seems to be some conflict, I'll do more testing to try to pinpoint it

**Comment by cybercat5555** [comment]
Found the culprit: CTM
Though not sure if it needs to be fixed on their or IE's end
