### ISSUE TITLE
[Request] A way for addons to add a custom ore display to the Coresample. Without creating a Vein.

### ISSUE THREAD

**Issue by TwistedGate** [BluSunrize/ImmersiveEngineering#4288]
Would it be possible to have the Coresample be able to display a custom "ore" on it, without creating a vein and the excavator pulling that "ore" up or would i have to do some hacky stuff to be able to make that a thing?

**Comment by TwistedGate** [comment]
On second thought, this may be too nishe of a thing. So i should probably just do the hacky way

**Comment by BluSunrize** [comment]
Make a pullrequest, you can code!

**Comment by TwistedGate** [comment]
I can't even make sense of that thing in the first place Lol
