### ISSUE TITLE
RC/IE Creosote

### ISSUE THREAD

**Issue by 016Nojr** [BluSunrize/ImmersiveEngineering#429]
Could it be possible to make the creosote bottles from IE compatible with the crafting recipes for RC creosote bottles? Mainly because tracks being unavailable

**Comment by mindforger** [comment]
please use search first before filing an issue

duplicate https://github.com/BluSunrize/ImmersiveEngineering/issues/101

not IE's fault

**Comment by XFactHD** [comment]
@016Nojr That's on railcraft to fix, they are registering their recipes to early.

**Comment by VermillionX** [comment]
If you have Forestry installed, you can still make track ties with the carpenter as a way around the problem.

**Comment by mindforger** [comment]
or you just use the proper tools to make it working again https://github.com/BluSunrize/ImmersiveEngineering/issues/101

**Comment by BluSunrize** [comment]
Yes, MInetweaker is  temporary solution. But Covert doing his code right would be far superior.
