### ISSUE TITLE
[1.15] Can't change the Tesla Coil between High and Low mode

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#4290]
### Description of the issue:
Right clicking with an empty hand does nothing even if the coil is turned off with Redstone

### Versions & Modlist
MC Version: 1.15.2
Forge Version: 31.2.30
IE Version: 1.15.2-3.1-117

**Comment by BluSunrize** [comment]
You need to use the screwdriver, not your empty hand.

That said, the interaction in general is broken, because the Screwdriver doesn't propagate sneak+click to the block below it.

This issue probably exists in 1.14 as well.
