### ISSUE TITLE
[1.14.4] Coresamples from befor the Mineral Rework don't display their translation correctly when looking at them in-world.

### ISSUE THREAD

**Issue by TwistedGate** [BluSunrize/ImmersiveEngineering#4292]
### Description of the issue:
Updated from IE 102 to 1.14.4-4.0.0-116, with Some coresamples still from the "102-era".
And looking at them shows only the translation key. But not the actual translation
![2020-09-11_22 59 52](https://user-images.githubusercontent.com/31029668/92972923-69bb5800-f483-11ea-9105-190ff65ea548.png)

### Crashlog:
None.

### Versions & Modlist
Forge: `1.14.4 28.2.18`
IE: `1.14.4 4.0.0-116`

**Comment by BluSunrize** [comment]
Hrmpf. Legitimate issue, though tbf, the translation key gets the point across.

Definitely not doing a new 1.14 release for this.

**Comment by TwistedGate** [comment]
> Definitely not doing a new 1.14 release for this.

Not expected anyway, such a minor thing anyway
