### ISSUE TITLE
[1.16.1] Workbench rendering glitch in version 118

### ISSUE THREAD

**Issue by ozBillo** [BluSunrize/ImmersiveEngineering#4293]
### Description of the issue:
The vice on the engineer's workbench has a rendering glitch. Parts of the model are invisible.

![2020-09-12_11 37 07](https://user-images.githubusercontent.com/1471834/92984535-25b16d00-f4ee-11ea-9d16-6e50aca2d9a4.png)

### Crashlog:
n/a

### Versions & Modlist
Minecraft 1.16.1
Forge 32.0.108
IE 4.0.0-118
No other mods

**Comment by malte0811** [comment]
This has already been fixed in 837a08a7d6f283c6d5afc3fcf285c6a6da035b29
