### ISSUE TITLE
[1.16.1] Textures on square multiblocks reversed in version 118

### ISSUE THREAD

**Issue by ozBillo** [BluSunrize/ImmersiveEngineering#4294]
### Description of the issue:
The textures are reversed right-to-left on the 2x2 and 3x3 multiblock models (Coke Oven, Crude Blast Furnace, Alloy Kiln).
![2020-09-12_18 01 50](https://user-images.githubusercontent.com/1471834/92991140-f4a05f00-f524-11ea-9ba3-4f11bc90db9d.png)
This wasn't happening with prior versions.

### Crashlog:
n/a

### Versions & Modlist
Minecraft 1.16.1
Forge 32.0.108
IE 4.0.0-118
No other mods

**Comment by BluSunrize** [comment]
Giving this to Malte, likely related to the change to obj models.

I'll take this over if you want me to, @malte0811, I'm currently assuming the UV mapping is just mirrored.
