### ISSUE TITLE
[1.16.1] Floodlight will not turn on at all

### ISSUE THREAD

**Issue by Camreyn** [BluSunrize/ImmersiveEngineering#4298]
### Description of the issue:
When I try to make a floodlight and power it, I am unable to get it to turn on.  I have used a screw driver to turn off the redstone dependency but it still seems to not work.   Even with the redstone dependency and a switch added, it will not turn on. 

### Versions & Modlist
ImmersiveEngineering-1.116.1-4.0.0-118
Forge 1.16.1-forge-32.0.108

Mekanism-1.16.1-10.0.9.432
Waystones_1.16.1-7.1.1
decorative_blocks-1.16-0.2
XaerosWorldMap_1.7.3_Forge_1.16.1
TrashSlot_1.16.1-12.0.0
Uppers-.0.3.0
Xaeros_Minimap_20.15.3_Forge_1.16.1
tubesreloaded-1.16.1-1.4.0.0
mcw-bridges-1.0.4-mc1.16.1
gravestone-1.16.1-1.0.2
jei-1.16.1-7.0.0.6

Hopefully I read the instructions correctly and I will be diligent in correcting any mistakes I may have made.  
Thank you all.

**Comment by BluSunrize** [comment]
Can you provide screenshots of your setup please?
Preferably using a lever to give a redstone signal to the light?

**Comment by Camreyn** [comment]
Yes sir, here you go. https://imgur.com/a/48loYlE

**Comment by BluSunrize** [comment]
Can you reproduce this issue an instance with just IE?

**Comment by Camreyn** [comment]
Just made a copy of the server with only IE active and yes I can confirm It still is running into the same issue

**Comment by BluSunrize** [comment]
I remain unable to reproduce this issue. Can you show me where you placed the lever to turn on your floodlight?

**Comment by BluSunrize** [comment]
Closing this due to lack of response
