### ISSUE TITLE
Can't form the excevator multiblock

### ISSUE THREAD

**Issue by FuckFaceBecauseSomeoneStoleMyUserhandle** [BluSunrize/ImmersiveEngineering#4299]
I created the multiblock exactly the way it said to in the engineers book, however when I go to click with the engineers hammer on the center heavy engineering block seen in picture two it does nothing. Why and how do I get this to work.
![Excavator not working 1](https://user-images.githubusercontent.com/39790565/93045502-5fd15a80-f625-11ea-8c48-b727503bc9a6.png)
![Excavator not working 2](https://user-images.githubusercontent.com/39790565/93045507-6364e180-f625-11ea-801f-8fe3a73cae6d.png)
![Excavator not working 3](https://user-images.githubusercontent.com/39790565/93045510-652ea500-f625-11ea-8ea2-2380f7c9f2be.png)

I am playing single player on the current version of Feed The Beast Infinity Evolved modpack (version: 3.1.0) minecraft (version: 1.7.10) Immersive Engineering (version: 0.7.7) and Immersive Integration (version: 0.6.8) 

I was able to create a metal press and a crusher, however not this, is there something I'm doing wrong? Someone please explain why this is not working. I've tried just making the engine by itself and still no luck, I've tried clicking with the hammer on every inch of the multiblock, I've even tried save&quit, then reload the world multiple times to see if that would work with no luck.

**Comment by malte0811** [comment]
1.7.10 is not supported any more, and hasn't been since 2016.

**Comment by FuckFaceBecauseSomeoneStoleMyUserhandle** [comment]
Just because it isn't supported doesn't mean that you should just upright ignore my issue... You should know exactly why this is happening and how to fix it. I'm assuming it has to do with the placement of the blocks, when I crated the crusher I had to swap around one of the engineering blocks in order to make it form with the hammer. So tell me what blocks to mess with to get it to work. AND it is absurdly asinine to stop supporting the most popular and most used version of minecraft for a vast majority of modpacks. (do to the fact that most of the good mods haven't updated to a newer version of the game. Some do to abandonment of the mod by the creator.)

**Comment by FuckFaceBecauseSomeoneStoleMyUserhandle** [comment]
@malte0811

**Comment by BluSunrize** [comment]
The fix is: Read the manual and look at how the structure is built there. Pretty sure it still uses steel blocks instead of sheetmetal. If that's not it, you probably did something else wrong. I sure ain't opening a 1.7 environment to check.

You are using a version that is outdated by **4 years**. We do not offer support, we have come out publicly to say so, years ago, so stop bothering us about it.

**Comment by FuckFaceBecauseSomeoneStoleMyUserhandle** [comment]
> 
> 
> The fix is: Read the manual and look at how the structure is built there. Pretty sure it still uses steel blocks instead of sheetmetal. If that's not it, you probably did something else wrong. I sure ain't opening a 1.7 environment to check.
> 
> You are using a version that is outdated by **4 years**. We do not offer support, we have come out publicly to say so, years ago, so stop bothering us about it.

Thanks, I took a look at the book again and all of the steel sheet metal blocks needed to be replaced with steel blocks. I was able to create the excavator. This is the kind of support I was looking for instead of the outright dismissal I received from malte0811. I apologies for the re-upload but I felt that if I hadn't then I would have been ignored. I will refrain from any further re-uploads.

**Comment by BluSunrize** [comment]
You should really read the manual *before* you open an issue.

And malte did everything right. He told you exactly what I would have. 1.7.10 is no longer supported. You will receive no further assistance.
