### ISSUE TITLE
Odd Coke Oven Rendering after updating FTB Infinity and rebuilding the oven.

### ISSUE THREAD

**Issue by Thorinori** [BluSunrize/ImmersiveEngineering#43]
So I had a Coke Oven setup before the update, I then updated and had to rebuild the oven. This happened... IE is on version 0.1.16

![2015-06-03_12 08 50](https://cloud.githubusercontent.com/assets/8883561/7967778/977da476-09e9-11e5-9b7f-ff0d0745d33d.png)
![2015-06-03_12 09 00](https://cloud.githubusercontent.com/assets/8883561/7967777/977c9a04-09e9-11e5-99dc-6d94f6253969.png)

**Comment by BluSunrize** [comment]
1) Known issue and fixed for future versions
2) since when is IE in Infinity? O_o

**Comment by Thorinori** [comment]
It isn't normally on Infinity, I added it manually. It isn't being distributed by FTB or Curse as far as I know.

**Comment by dh47** [comment]
Yep I'm getting this too lets hope for a fix.  It still works tho.

**Comment by BluSunrize** [comment]
It is fixed already, sooo, yeah
