### ISSUE TITLE
Hemp crop height bug

### ISSUE THREAD

**Issue by zerotheliger** [BluSunrize/ImmersiveEngineering#430]
http://pastebin.com/3fYUfHGN < Mod List

http://i.imgur.com/1yLpiWp.png < Overview of issue.

http://i.imgur.com/TNFtF51.jpg < Showing every 10 blocks normal hemp crop growing for 2 blocks.

Hemp crops growing without limit when using project e's Harvest Goddess Band in player inventory, as long as player stays within range of the top of the crop it will continue to grow.

After 10 blocks of missing textures it will grow 2 normal textured crops and continue again with missing texture, this happens every 10 blocks.

How to reproduce: Equip the Band, Stand near the crop, Staying level with the top of the crop, Crop will continue to grow.

**Comment by cobra** [comment]
Reproduced and fixed. Looks like Project E doesn't check whether a plant is bonemeal-able and just calls the appropriate function, which doesn't prevent such misuse in IE. I changed the metadata check for this.
