### ISSUE TITLE
Can't form the excavator multiblock (reupload to do original being wrongfully closed without a satisfying answer)

### ISSUE THREAD

**Issue by FuckFaceBecauseSomeoneStoleMyUserhandle** [BluSunrize/ImmersiveEngineering#4300]
I created the multiblock exactly the way it said to in the engineers book, however when I go to click with the engineers hammer on the center heavy engineering block seen in picture two it does nothing. Why and how do I get this to work.
![Excavator not working 1](https://user-images.githubusercontent.com/39790565/93047607-e2a8e400-f62a-11ea-8770-a8596ff950e4.png)
![Excavator not working 2](https://user-images.githubusercontent.com/39790565/93047614-e472a780-f62a-11ea-9a86-bf907b7a0d15.png)
![Excavator not working 3](https://user-images.githubusercontent.com/39790565/93047618-e63c6b00-f62a-11ea-8f43-40a1a6219740.png)

I am playing single player on the current version of Feed The Beast Infinity Evolved modpack (version: 3.1.0) minecraft (version: 1.7.10) Immersive Engineering (version: 0.7.7) and Immersive Integration (version: 0.6.8)

I was able to create a metal press and a crusher, however not this, is there something I'm doing wrong? Someone please explain why this is not working. I've tried just making the engine by itself and still no luck, I've tried clicking with the hammer on every inch of the multiblock, I've even tried save&quit, then reload the world multiple times to see if that would work with no luck.

@malte0811
> 1.7.10 is not supported any more, and hasn't been since 2016.

Just because it isn't supported doesn't mean that you should just upright ignore my issue... You should know exactly why this is happening and how to fix it. I'm assuming it has to do with the placement of the blocks, when I crated the crusher I had to swap around one of the engineering blocks in order to make it form with the hammer. So tell me what blocks to mess with to get it to work. AND it is absurdly asinine to stop supporting the most popular and most used version of minecraft for a vast majority of modpacks. (do to the fact that most of the good mods haven't updated to a newer version of the game. Some do to abandonment of the mod by the creator.)

**Comment by BluSunrize** [comment]
If you open another duplicate issue, you're getting blocked.
