### ISSUE TITLE
[1.16.1] Can't drain ingredient liquids from the refinery using buckets

### ISSUE THREAD

**Issue by Protected** [BluSunrize/ImmersiveEngineering#4301]
### Description of the issue:

If I pick up an empty bucket and place it in the rightmost input slot of the refinery's inventory interface, the bucket will successfully be filled with a portion of the biodiesel stored in the refinery (if any) and moved to the output slot below it.

However, I can't do this with the input slots for either plant oil or ethanol. Even if there is plant oil or ethanol in the refinery, this interface will refuse to "place" the bucket in either of these slots. Clicking the slot will have no effect, and the bucket will remain "held" by the mouse pointer. No liquid is drained. I can place the empty bucket back in my player inventory if I like.

I noticed weeks ago but keep forgetting to report this. I hope there isn't a fix yet (I don't see it reported or fixed, apologies if I missed it).

No crashes or errors are associated with this issue.

### Versions & Modlist

(Same as in previous recent tickets.)
This is a dedicated server + client setup (online multiplayer).

ImmersiveEngineering-1.16.1-4.0.0-pre.27
Forge: 32.0.108

All client-side mods: https://gist.github.com/Protected/c558a84c055d98383ddf25f9cf0e5bd1

OS: Windows 10
Client-side Java: 1.8.0_251 64bit w/ 4GB maximum heap size

**Comment by BluSunrize** [comment]
No that's just how that's worked, since forever. You can't take inputs back out of the refinery. That's just how it is ^^

**Comment by Protected** [comment]
If you're serious, I do wonder why those slots exist in the interface in the first place, but feel free to close!

**Comment by BluSunrize** [comment]
...to put fluid in.
You put a filled bucket there to put its fluid into the refinery.

Seriously though, this behavior of slots has been the same since IE released for the first time, over 4 years ago.

**Comment by Protected** [comment]
I did not know that, sorry
