### ISSUE TITLE
[1.16.1] Powered Lantern emit no light

### ISSUE THREAD

**Issue by Totomio** [BluSunrize/ImmersiveEngineering#4303]
forge 32.0.108, IE 4.0.0-118, optifine 1.16.1 HD U G2 (no other mods installed)

The powered lantern emit no light. 
When connected the texture slightly change but there are no light effect

Thanks for this awsome mod ! Hope i can help.

![2020-09-15_08 08 30](https://user-images.githubusercontent.com/71310604/93173842-621edc00-f72d-11ea-915f-def77dd0df2e.png)
![2020-09-15_08 26 37](https://user-images.githubusercontent.com/71310604/93173860-68ad5380-f72d-11ea-8a2a-802e4c126042.png)

**Comment by BluSunrize** [comment]
Can you reproduce this issue without optifine?

**Comment by Totomio** [comment]
Without optifine the powered lantern work fine. 

Just to say: with optifine the basic Lantern and the flood light (except for the light texture missing see screenshot below) work fine

![2020-09-15_09 58 27](https://user-images.githubusercontent.com/71310604/93182645-3bb36d80-f73a-11ea-9c3f-683b1e079919.png)

**Comment by BluSunrize** [comment]
Sounds like an optifine issue then, and Optifine is unsupported, as detailed in our contribution guidelines =)
