### ISSUE TITLE
Client crashes on forge server 1.12.2

### ISSUE THREAD

**Issue by bobb3ll1** [BluSunrize/ImmersiveEngineering#4304]
Hello, im trying to get in a forge server with alot of immersive mods and my client crashes and the crash report mentions immersive mods. the problem started yesterday.
Below is the crash report.
[crash-2020-09-15_13.13.18-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5224214/crash-2020-09-15_13.13.18-client.txt)
Any help would be greatly appericiated.

**Comment by malte0811** [comment]
That looks like Immersive Railroading, which is not related to Immersive Engineering. In any case we do not support 1.12 any more.
