### ISSUE TITLE
[1.15] Steel tools missing forge tags

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#4305]
### Description of the issue:
IE tools like the axe and the shovel don't have corresponding forge tags like "forge:tools" and "forge:tools/axe", for example. This leads to some compatibility issues with other mods, like Farmer's Delight

### Versions & Modlist:
MC Version: 1.15.2
Forge Version: 31.2.30
IE Version: 1.15.2-3.1-117

**Comment by BluSunrize** [comment]
Those aren't Forge tags, actually! Those are tags that @vectorwing made up for Farmer's Delight :D

They are not in Forge, they are done manually (I don't even think FD has a data generator for it). So while we could do it, we'd be probably the only mod? =P

**Comment by ghost** [comment]
oh oh

**Comment by vectorwing** [comment]
Yes, I mostly made them up for use with the Cutting Board while trying to stick to the naming convention, as there were none. However, despite tags being customizable, they're also labor-intensive in this case, as I haven't added modded tools to the tag myself (I feel weird tagging external items without a dev's consent), and the modpack maker would end up holding that burden.

Right now I'm studying support for `ToolType` in the recipe, which would encompass all modded pickaxes, axes and shovels, alongside item/tag ingredient. I also need to establish more datagen on the mod, so thanks for the reminder! 👍 

Finally, I believe @BluSunrize also wanted to bring further the topic of an official Forge Tag for tools, and I haven't yet looked into what it would take to propose/open that PR. Like he said on Discord, it would greatly help adoption and standardization (as I'm pretty sure my syntax might not be the ideal one).

**Comment by BluSunrize** [comment]
I'm closing this one for now. If we get standardized tags, I'll happily adopt them!
