### ISSUE TITLE
[1.16.1] Assembler crafts firework recipe without reagents

### ISSUE THREAD

**Issue by Tethik** [BluSunrize/ImmersiveEngineering#4307]
### Description of the issue:
When crafting fireworks in the Assembler, it ignores reagents. Testing with other recipes it's fine, but I noticed also that the fireworks recipe does not show up in the minecraft recipe book. So perhaps it's related to that?

![fireworks-dupe](https://user-images.githubusercontent.com/298627/93533710-cc10ce80-f943-11ea-9dd8-0fe225bda7a0.gif)
![recipe](https://user-images.githubusercontent.com/298627/93533708-cadfa180-f943-11ea-8a58-a496de2a8ec0.png)

Happens both in singleplayer and on multiplayer. I tested it also standalone with only forge and IE installed.

### Versions & Modlist
ImmersiveEngineering-1.16.1-4.0.0-118.jar
forge-32.0.108

**Comment by XFactHD** [comment]
I see nothing wrong with that, that is a valid recipe according to https://minecraft.gamepedia.com/Firework_Rocket.

**Comment by Tethik** [comment]
Yes, the recipe is valid. But it's creating the rockets without any materials.
