### ISSUE TITLE
Crash: java.lang.NullPointerException: Exception in server tick loop

### ISSUE THREAD

**Issue by Ridanisaurus** [BluSunrize/ImmersiveEngineering#4309]
### Description of the issue:
Game crashes with `java.lang.NullPointerException: Exception in server tick loop` when pressing ESC (WorldSavedData).
I tested this with both `immersiveengineering@1.15.2-4.0.0-117` and `immersiveengineering@1.15.2-4.0.1-119`

### Crashlog:
4.0.0-117: https://pastebin.com/hJbUa5Hf
4.0.1-119: https://pastebin.com/dS3e5BMT

### Versions & Modlist
Minecraft: 1.15.2
Forge: 31.2.36
IE: immersiveengineering@1.15.2-4.0.0-117 | immersiveengineering@1.15.2-4.0.1-119
Modlist: Inside the crashlog

**Comment by BluSunrize** [comment]
Can you reproduce this with just IE?

**Comment by Darkere** [comment]
It doesn't happen with just IE. We noticed that we did not actually update IE in the pack update that brought up this issue. 

The crash still happens pretty deep into your MineralVein Code... Any idea what could cause it?

**Comment by BluSunrize** [comment]
Uh, sorry, I don't know what I was thinking there. I somehow *missed* the IE class in the stacktrace there. I thought it was a vanilla exception!

The thing that crashes is the mineral of the vein somehow being null, which theoretically shouldn't happen, unless you removed a vein from a datapack?

**Comment by NielsPilgaard** [comment]
We didn't remove any veins, stock IE datapack, but some other mod could be adding to it I suppose.
