### ISSUE TITLE
IE Pipes enhancement/.continuity

### ISSUE THREAD

**Issue by TooManyKitKats** [BluSunrize/ImmersiveEngineering#4314]
#3817 # Description of the issue:
Not an issue but a suggestion to make IE pipes match the color scheme of the newly added colored sheet metal, currently the pipes are super high contrast and don't match the rest of the aesthetic.

### Versions & Modlist
1.14.4 , 1.15.2 , 1.16.3

**Comment by BluSunrize** [comment]
That'd be because the two things work differently.
Pipes are a colour "multiplier" added to the default texture.
Sheetmetal had specific textures done for each block.

Getting them to line up would probably mean hardcoding the colour-tone of all 16 dyes for pipes. Not worth the effort.
