### ISSUE TITLE
[Request][minor] add a vertically mirrored sloped chute version that has the slope on top instead of the bottom

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#4318]
Just for prettiness purposes. Don't know if it's easily possible because of block states, but having the bottom-sloped versions go into the side of a chute that is open to the top kind of looks off, unless you're dropping something in there, too

**Comment by BluSunrize** [comment]
No plans to implement this. Purely decorational, but would be a bit of a mess to detect when to use it. Adding *even more* conditional rendering is not on my list of things to do atm.
