### ISSUE TITLE
[MC1.16.3|IE121] [minor] Bottling Machine glass tank does not render

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#4321]
as title. Last I found it working is in 1.12, IE92 . As far as I can tell, it stopped being rendered in 1.14, IE93

![grafik](https://user-images.githubusercontent.com/7753414/93992919-6fbc0d80-fd8e-11ea-8c71-8682f62dfd94.png)

**Comment by BluSunrize** [comment]
This won't be a fix I backport to 1.14, but I will address it while I'm also overhauling the machine's texture sheet.
