### ISSUE TITLE
Crash when trying to view Core Sample from Core Sample Drill

### ISSUE THREAD

**Issue by kman3107** [BluSunrize/ImmersiveEngineering#4325]
### Description of the issue:
NB! This only happens when running the forge server install!
Normal forge client works just fine.

Drill for Core Sample, get Core Sample but it has no texture aside the Stone like.
Crash is when hovering the mouse over the Core Sample in the inventory.
Crash when looking at a placed Core Sample in the world

Happened several times during my live stream.
This is a highlight of the first time I crashed https://www.twitch.tv/videos/751380402

### Crashlog:
https://pastebin.com/46vNRdNC - This is a crash when looking at a placed Core Sample in the world. (Enigmatica 6)
https://pastebin.com/SE1X0btK - This is a crash when hovering the mouse over the Core Sample in the inventory. (Enigmatica 6)
https://pastebin.com/2NFVnGzk - This crash is when hovering the mouse over the Core Sample in the inventory. (Only 3 mods+forge)

### Versions & Modlist
Forge Server: 1.16.1-32.0.108
IE: 1.16.1-4.0.0-118
Productive Bees: 1.16.1-0.3.3 and 0.3.5
JEI: 1.16.1-7.0.1.10

I spent a LOT of time just to figure out what was causing my crashes. I can say with 100% that IE, Productive Bees and Forge Server with the versions mentioned above are not going to work together . Tried on 2 different pcs. (Client on same pc, but server on 2 different servers). Honestly I don't know if this is an issue with IE, Productive Bees, or Forge.

**Comment by BluSunrize** [comment]
Does the issue persist if you remove Productive Bees?

**Comment by kman3107** [comment]
The issue only persist if you have those exact 3 things together with those exact versions.
So, no. If I remove Productive Bees there are no more problems.
Same with Forge Server. If I play on the forge client it works fine with both IE and Productive Bees.

Honestly I'm pretty sure the fault lies somewhere between Productive Bees and Forge.
I only came here to tell you, so you know about it.

**Comment by BluSunrize** [comment]
Found the source of the issue.
Productive Bees has a packet, that after it is handled, triggers a recipe reload:

https://github.com/JDKDigital/productive-bees/blob/master/src/main/java/cy/jdkdigital/productivebees/network/packets/Messages.java#L45

It triggers that reload with a completely empty recipe list, and as a result of that, IE loses all its recipes. Including mineral veins.
That then causes a nullpointer when trying to access the respective mineral later on.
