### ISSUE TITLE
[1.15.2] Crash with Productive Bees

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#4328]
### Description of the issue:
After creating a new world with both Immersive Engineering and Productive Bees after a few minutes of playing the game will crash to desktop. Removing Productive Bees solves the crash.

### Crashlog:
https://pastebin.com/93bnkVjy

### Versions & Modlist
Minecraft 1.15.2
Forge 31.2.41
Immersive Engineering 1.15.2-4.0.1-119
Productive Bees 1.15.2-0.3.5
Full system info and modlist: https://pastebin.com/fZ8DPQdb

This appears to be similar to #4325, but I have created a separate issue since I am running a different version of Minecraft and am getting a different crash. Will also be opening an issue on Productive Bees repo also.

**Comment by ghost** [comment]
https://github.com/JDKDigital/productive-bees/issues/87

**Comment by BluSunrize** [comment]
Update productive bees
