### ISSUE TITLE
[1.15.2] Transformer transfer rates aren't restricted by the weakest wire

### ISSUE THREAD

**Issue by Shados** [BluSunrize/ImmersiveEngineering#4330]
### Description of the issue:
The engineer's manual claims of transformers that "the weakest wire restricts the transfer rate", but in practice, transformers can burn out the weaker connected wire under some circumstances.

Specifically, here is an example setup, done with default configs:
![Minimal transformer wire burn setup](https://shados.net/files/ss/ie_transformer_burn.png)

Placing a final MV wire between the transformer and the relay next to it *immediately* causes the placed wire to burn out. If the transformer's transfer rate were *actually* limited to that of the weakest wire, this obviously couldn't happen.

Some notes:
- This doesn't appear to happen with only a single MV capacitor hooked up to the relay, it needs at least 2 to trigger the behaviour.
- It's not at all obvious why merely 2 connected devices would cause it to burn out, given that should only result in a draw rate of *at most* 2\*1024, and the default limit for MV wires is 8092...

### Versions & Modlist
The screenshot above is from testing in a minimal setup with only Forge, IE, and JEI:
- ImmersiveEngineering-1.15.2-4.0.1-119.jar
- jei-1.15.2-6.0.3.15.jar
- Forge 1.15.2-31.2.37

**Comment by Protected** [comment]
Just an anecdote: I think I experienced this recently in my grid (MV fed from HV to MV transformers among other things). I didn't have time to do the math and check so I just plopped single MV capacitors between each transformer and the grid and it "solved" the problem in practice.
