### ISSUE TITLE
[1.16.1] Revolver Crash When Fired Straight Down

### ISSUE THREAD

**Issue by MtgSaber** [BluSunrize/ImmersiveEngineering#4332]
Description:
Loaded a phial cartridge of Instant Damage II, aimed straight down to test splash damage (if any), and fired. Upon clicking M1 my game crashed.

Crashlog:
https://pastebin.com/9zx95a6S
Relevant section involves raycasting.

Forge Version:
1.16.1-forge-32.0.108

Mods:
ImmersiveEngineering-1.16.1-4.0.1-120
jei-1.16.1-7.0.1.10
JustEnoughResources-1.16.1-0.11.1.98

**Comment by BluSunrize** [comment]
Oh that was dumb of me. I pushed that to the wrong branch :'D

**Comment by BluSunrize** [comment]
There we go. The next releases will resolve this.
