### ISSUE TITLE
[MC 1.15.2 | IE dev (1bdbb6c)] Covered Conveyors with red glass is opague, all other glass covers work fine

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#4336]
see picture:
![grafik](https://user-images.githubusercontent.com/7753414/94376227-8f01c480-0119-11eb-9b19-c7ebfdcdd39d.png)

**Comment by BluSunrize** [comment]
Blame vanilla, red stained glass has an alpha value of 128, which is the cutoff point for opaqueness on renderpasses that don't support translucency.

**Comment by MalkContent** [comment]
(turn it into an easter-egg by adding a hidden advancement  **Unlimited Power!** "this one's for Eloraam" or something, that triggers when adding a red glass cover x)  )
