### ISSUE TITLE
[Suggestion] Make covered conveyors open their top to chutes

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#4337]
as title
making chutes able to directly insert into covered conveyors would also be an option, but then you couldn't transport chickens :C

**Comment by BluSunrize** [comment]
You should be able to insert into the back of the conveyor?

The reason I don't have covered ones open to the top is that it's *another* special case to deal with :V

**Comment by MalkContent** [comment]
hmm. Could you make them open to chutes to the side like they do for other conveyors then?
also, am contemplating to allow chutes to drop into covered conveyors (currently ignoring all conveyors for insert-into-inventory in the chute PR), because dropping conveyors are able to
