### ISSUE TITLE
Many Issues, Audio, Slabs, Visual, Uncreatable Items [1.16.1]

### ISSUE THREAD

**Issue by Unusual-Danger** [BluSunrize/ImmersiveEngineering#4338]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue: Issues I have found along the way are,
Arc Furnace electrodes don't render.
Deiseal Generator doesn't make noise.
Steel grit is unobtainable for buckshot rounds.
(Big Bug) Slabs of the same material when placed on top of each other to make a full block. When trying to get the slabs back, it only gives 1 slab back instead of 2.(Any slab with the mod)
 
Describe what happens, how it affects your game/gameplay and provide screenshots where possible.

### Versions & Modlist
IE and Forge versions are mandatory. *Note that saying "latest" is **not** valid. Always give the proper version number* Forge Version: 32.0.108 IE Version: 1.16.1-3.2.0-115
Mod list:
IE
JEI
Optifine
Xaero's Minimap and Worldmap
Iron Chest
Advanced Chimneys
Waila
Engineer's Decor

**Comment by BluSunrize** [comment]
You're using an outdated version of IE.
Feel free to test on the latest version and open a properly formatted issue.

Steel grit is fixed for upcoming releases.
