### ISSUE TITLE
crash on start (1.16.1)

### ISSUE THREAD

**Issue by bendavidson16** [BluSunrize/ImmersiveEngineering#4339]
MultiMC, latest Forge version, no other mods: https://paste.ee/p/lFiiS
Anyone understand the crash report? Is this just a me issue, something with MultiMC?

**Comment by BluSunrize** [comment]
Try putting a file called `.vote2020_marker` in your instance's folder. That should hopefully get around this until we have a more permanent solution.

**Comment by bendavidson16** [comment]
@BluSunrize No success with that so far; tried Atom and TextEdit. Am I missing something about the file type?

**Comment by BluSunrize** [comment]
No, there isn't any filetype. It's just a file called `.vote2020_marker` that you place in your instance's folder, where the "mods", "saves" and "logs" folders are also located

**Comment by BluSunrize** [comment]
This is fixed for future releases by this:

https://github.com/BluSunrize/ImmersiveEngineering/commit/35ff8fecb63621857ee3dd1a45d68605b5868cc3

**Comment by mindforger** [comment]
side note on windows, the known file extensions are disbaled by default so mybe it still is named ".vote2020_marker.txt"

also putting a . in front of the filename may hide it by default (at least folders do behave so)

**Comment by BluSunrize** [comment]
They are on Mac, not Windows. That's the entire reason this crashed.

**Comment by bendavidson16** [comment]
@BluSunrize My mistake guys! Somehow took me 24 hours to notice I typed “voter” instead of “vote.” Thanks for clearing this up! In the meantime I’ll be voting and enjoying this excellent mod.
