### ISSUE TITLE
[1.16.1] Crash on Startup - Immersive Engineering has failed to load correctly [Forge 32.0.108]

### ISSUE THREAD

**Issue by Afollo** [BluSunrize/ImmersiveEngineering#4340]
When the game is started on forge 32.0.108 I am met with the error "Immersive Engineering has failed to load correctly: null"
However, when trying to use forge 32.0.88 (as suggested before) I am met with "Immersive Engineering requires forge 32.0.108"?
(ImmersiveEngineering ver. ImmersiveEngineering-1.16.1-4.0.1-120)
Everyone else in the server can play fine however I am having issues.

**Comment by BluSunrize** [comment]
Are you encountering this issue with just IE installed and no other mods?

Could you please launch the game, then grab the debug.log file and upload it on gist or pastebin?

**Comment by BluSunrize** [comment]
Closed due to lack of response
