### ISSUE TITLE
[1.12] Generated 0% modifier on gun parts break translation

### ISSUE THREAD

**Issue by Water-Moon** [BluSunrize/ImmersiveEngineering#4341]
### Description of the issue:
![image](https://user-images.githubusercontent.com/43123946/94475586-47bd1780-019d-11eb-9199-e84057389834.png)
There is (although very very small) chance that a modifier of ~0 would be generated, potentially due to float precision, etc. This break the translation, at least for zh_cn, other language not tested.

### Versions & Modlist
IE 0.12-98, Forge 2847, nothing else.

**Comment by BluSunrize** [comment]
We are not longer offering any support for 1.12
