### ISSUE TITLE
[1.16.3] Gunpowder Barrel Crash

### ISSUE THREAD

**Issue by prc94** [BluSunrize/ImmersiveEngineering#4344]
Minecraft Version 1.16.3
Forge Version 34.1.0
IE Version 1.16.3-4.0.1-121
Any other mods are disabled for experiment purity
Occasion: Attempting to detonate gunpowder barrel, crash occurs at explosion moment
Crash Report https://paste.ee/p/axL41

**Comment by BluSunrize** [comment]
Looks like parameters changed in 1.16.3.

I'll look into this, specifically by testing 1.16.1 as well, since that has *both* parameters.

**Comment by prc94** [comment]
> Looks like parameters changed in 1.16.3.
> 
> I'll look into this, specifically by testing 1.16.1 as well, since that has _both_ parameters.

Well, i've found pretty simple solution for this
`.withParameter(LootParameters.field_237457_g_, Vector3d.copy(pos))`
i'm not sure if this is any kind of proper solution, but it working now, despite no explosion animation or sound is played, game is not crashing any further and explosion can now damage the world

**Comment by prc94** [comment]
> > Looks like parameters changed in 1.16.3.
> > I'll look into this, specifically by testing 1.16.1 as well, since that has _both_ parameters.
> 
> Well, i've found pretty simple solution for this
> `.withParameter(LootParameters.field_237457_g_, Vector3d.copy(pos))`
> i'm not sure if this is any kind of proper solution, but it working now, despite no explosion animation or sound is played, game is not crashing any further and explosion can now damage the world

https://github.com/prc94/ImmersiveEngineering/blob/1.16.3/src/main/java/blusunrize/immersiveengineering/common/util/IEExplosion.java#L106

**Comment by BluSunrize** [comment]
I mean, yes, I know exactly how to fix it, lmao.
But on 1.16.1 we have both position and origin parameters, and I wanna verify if this should be a 1.16 change or just 1.16.3 ;)
