### ISSUE TITLE
[1.15.2] Server tick loop related to IE veins 

### ISSUE THREAD

**Issue by xAlicatt** [BluSunrize/ImmersiveEngineering#4349]
### Description of the issue:
I've run into a situation where I keep getting this crash randomly. I haven't been able to tell that there is any common thread that is causing the issue. I'm just in my mines and sometimes when I break a block it will happen, but it's also happened when I'm just walking/swimming around doing nothing in particular.

### Crashlog:
https://paste.ee/p/93tt0#3Fm0DXXTpGT2WF9aAJx0vy3S9nTM3IEX

### Versions & Modlist
ImmersiveEngineering-1.15.2-4.0.1-119.jar
forge-1.15.2-31.2.43-server.jar

https://paste.ee/p/JtTSV#W6pmtyGu7lCiEP5BkqVM2cTlLSUiJ7aB

**Comment by BluSunrize** [comment]
Should be fixed in version 4.1.0-122. Please try an update to that.
