### ISSUE TITLE
1.15.2 Kinetic dynamos don't produce power

### ISSUE THREAD

**Issue by Fade-Alchemist** [BluSunrize/ImmersiveEngineering#4352]
I searched issues and did not see this there. 

### Description of the issue:
Unable to draw power from kinetic dynamos. Tried with water wheels and windmills. Made sure to have a capacitor connected. Used lv wire and made sure I was using connecters and not relays. This issue was originally found in a custom mod pack I made, however, I did test it with a world only using JEI and Immersive engineering. The problem still persists. 

### Crashlog:
Not Applicable

### Versions & Modlist
IE version: 1.15.2-4.1.0-122.jar
Forge Version: forge-31.2.44

**Comment by BluSunrize** [comment]
Please provide pictures of your setup.

**Comment by Fade-Alchemist** [comment]
Update: I double-checked my set up, it *is* making power.  However, the GUI does not update while you are looking at it. For example, I was testing using a Cloche as it is a single block and has an energy bar. I was in the GUI staring at the bar and it did not move. If I back out of the GUI and go back in, it updates and then shows power.  The one probe also does not show energy filling capacitors and the like (that may be on their side). As far as dynamos not producing power through, that issue is closed.


AE Cell showing power in top left display
![AE Cell Showing power (top left)](https://user-images.githubusercontent.com/29619427/95153193-7fefc780-0754-11eb-9630-8b4775c74ca9.png)

IE Capacitor not showing power in top left display
![IE Capacitor Not Showing power](https://user-images.githubusercontent.com/29619427/95153198-82eab800-0754-11eb-9c24-18980959e756.png)

 Even when Dynamo is producing power, no way to see it (Display shows 0 power, top left)
![2020-10-05_21 50 40](https://user-images.githubusercontent.com/29619427/95153398-f4c30180-0754-11eb-8214-8c46d310b9e9.png)

**Comment by BluSunrize** [comment]
The Dynamo doesn't store power.
We have no WAILA integration atm, which is why the capacitor shows none.
And AE2 is not a mod we make.

If you use an Engineer's Voltmeter, you'll be able to get the energy storage of the capacitor.
