### ISSUE TITLE
[1.15.2|122] Gunpowder Barrels behave funky (model off center, less drops)

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#4353]
When ignited the barrel entities position seems off. In this picture, it is not currently "jumping" after being ignited, and the shadow, and I assume "center" of the entity is way closer to where it was before igniting.
Additionally it now somehow drops less items than before. Exploding these 11 blocks only gave me 2 granite (got 3 cause first is from placing).
I'm also gonna link this here https://github.com/BluSunrize/ImmersiveEngineering/issues/3692 because if it's gonna be touched, maybe there's an opportunity to fiddle with it at the same time.
![grafik](https://user-images.githubusercontent.com/7753414/95106772-3cd42b00-0739-11eb-9854-1947c1880dc4.png)
![grafik](https://user-images.githubusercontent.com/7753414/95106932-7efd6c80-0739-11eb-8816-1152509a7b83.png)

**Comment by BluSunrize** [comment]
Yeah, I want to handle this in combination with #3692

My current idea would be to increase the explosion strength (since it uses more gunpowder) and fix the lost drops, effectively making these barrels more powerful and more expensive TNT.

**Comment by MalkContent** [comment]
they use the same amount of gunpowder as tnt, no?

**Comment by BluSunrize** [comment]
Ah shit, they do, don't they...

Well they still are more expensive than TNT, that's for sure.

**Comment by MalkContent** [comment]
true ^^ could also always add more powder into the recipe
