### ISSUE TITLE
1.15.2-4.1.0-122 and Optifine sudden invisible water wheel/ windmill etc

### ISSUE THREAD

**Issue by Reidlos65** [BluSunrize/ImmersiveEngineering#4355]
### Description of the issue:
I feel like this worked in general but I wiped my mod pack and fresh installed and when playing again noticed the wheel was invisible.  I checked a few things and was only able to get it to show up for a second if really close but at any range it would disappear.  After all is said and done, what I concluded is , for w/e reason since I think it was fine just the other week,  with the new version 1.15.2-4.1.0-122 of Immersive Engineering with the current latest version of 1.15 Optinfine : preview_OptiFine_1.15.2_HD_U_G1_pre30 the wheel/windmill and maybe more things but didn't test everything go invisible.  
Version 1.15.2-4.0.1-119 of IE works fine.

### Versions & Modlist
IE 1.15.2-4.1.0-122 IE
Forge - 31.2.37

Other mods: 
https://pastebin.com/wqwk4xaW

I understand Optifine isnt your responsibility but if there is something basic I can do or if somthing can be rolled into the next update thats little effort on the mods end to fix, Id appreciate it

**Comment by malte0811** [comment]
Try disabling VBOs in the IE config. They make windmill and waterwheel rendering a *lot* more efficient (I can render 1024 windmills at 40-60 FPS now, 0-1 FPS before), but are most likely incompatible with Optifine.

**Comment by Reidlos65** [comment]
That worked.  Thanks
Shame, hopefully Optinfine for 1.15 eventually gets caught up again :(

**Comment by lima-limon-inc** [comment]
> Try disabling VBOs in the IE config. They make windmill and waterwheel rendering a _lot_ more efficient (I can render 1024 windmills at 40-60 FPS now, 0-1 FPS before), but are most likely incompatible with Optifine.

Where can I find the IE config?

**Comment by BluSunrize** [comment]
In the config folder, where you find literally every other mod's configs.

**Comment by SirWalkerCZ** [comment]
For other people looking at this, this also fixes the bug if you are using any variations of sodium (embedium, rubidium etc.), but it creates another mayor issue, the game crashes when you put a blueprint in the engineers workbench. Howover turning VBO back on seems to fix the issue, but the water wheels stop rendering again lmao
