### ISSUE TITLE
[1.16.3] how to completely disable ore gen ?

### ISSUE THREAD

**Issue by Switch-Back18** [BluSunrize/ImmersiveEngineering#4356]
Would it be possible to add the option to disable ore generation ? (1.16.3)

Because we had no choice to choose just one ores from one mod

Thanks in advance!

**Comment by BluSunrize** [comment]
There is config options. Did you even bother looking?

**Comment by Switch-Back18** [comment]
I seen but we can't disable it

**Comment by Switch-Back18** [comment]
preferredOres = ["silents_mechanisms"]

But that not works.

**Comment by malte0811** [comment]
The options you want are in the server config, not the common config. I don't have time right now to explain how to set that at world creation, but you can probably ask about it in some modded MC discord.

**Comment by BluSunrize** [comment]
preferredOres is the wrong option, as its comment says:

> A list of preferred Mod IDs that results of IE processes should stem from, aka which mod you want the copper to come from.
> This affects the ores dug by the excavator, as well as those crushing recipes

This doesn't affect ore generation in any way, it's for IE's machines.

You are looking for the options set in your world config, which is found in `<world name>/serverconfig/immersiveengineering-server.toml`. In that file is the `[ores]` section, and each ore listed in it has the `vein_size` option, the comment for which says:
> The maximum size of a vein. Set to 0 to disable generation
