### ISSUE TITLE
1.16.1: Massive framerate staggering when jumping

### ISSUE THREAD

**Issue by BenjiFrank1776** [BluSunrize/ImmersiveEngineering#4357]
I downloaded the mod today onto my modpack and I haven't had these kind of issues until today. I broke everything I had set up (i.e waterwheel, light posts and windmill) and it still stuttered. I reloaded the world and then it started working fine, so I tried to set up the stuff again and It was working fine and then randomly I dropped in frames again. I'm not talking like from 120 down to 60 or anything simple. Instead it drops me from 120 down to around 12 when ever I jump or move around within the same chunk. I really wanna keep this mod but I don't know what to do and how to fix it

**Comment by malte0811** [comment]
Does it happen with just IE installed? I currently don't see how IE would cause this.

**Comment by BluSunrize** [comment]
Closed due to lack of response
