### ISSUE TITLE
bad AO

### ISSUE THREAD

**Issue by FierceManul** [BluSunrize/ImmersiveEngineering#4359]
this AO looks bad, Can it be fix?
![屏幕截图(139)](https://user-images.githubusercontent.com/64459019/95475619-fc82e000-09b8-11eb-9193-4abc99c1cf4a.png)

**Comment by BluSunrize** [comment]
No idea. Do you know how to fix it?

**Comment by FierceManul** [comment]
I only know that this AO follows the model rotation, it shouldn't be.

**Comment by TeamSpen210** [comment]
I can't find the original, but I think I saw a similar problem on a Forge issue, which revealed the issue is that the order of the vertexes matters for retrieving AO. So when rotating all the quads need their vertexes cycled appropriately :/

**Comment by malte0811** [comment]
At least for me this is only happening with `experimentalForgeLightPipelineEnabled = false` in `forge-client.toml`. Even though it says "experimental", it isn't really experimental at this point, you should enable it.
