### ISSUE TITLE
Crashes at start

### ISSUE THREAD

**Issue by yannic312** [BluSunrize/ImmersiveEngineering#436]
when I start minecraft, it crashes and gives me this Report: http://pastebin.com/p6Xj0hFW

**Comment by cobra** [comment]
You're using Forge 1.7.10-10.13.2.1291, which is quite old. IE is currently being built against Forge 1.7.10-10.13.4.1448.

Please update your forge version.

**Comment by BluSunrize** [comment]
What @cobra said.
Outdated Forge, with outdated OreDict methods.
