### ISSUE TITLE
[1.16.3]   hard crashes the reload listener thus making it impossible for other mods to use the listener

### ISSUE THREAD

**Issue by raziel23x** [BluSunrize/ImmersiveEngineering#4364]
### Description of the issue:
basically immersive engineering is returning they have a container item when they don't currently have
thus causing it to hard crashes the reload listener and causing other mods like ProjectE to not be able to fire the reload listener so their recipe fails it seems

### Crashlog:
Here is the complete Latest log
https://gist.github.com/raziel23x/883dd529ee67b16550774a592aceeb62

main part in question
java.lang.NullPointerException
     at java.util.Objects.requireNonNull(Objects.java:203)
     at blusunrize.immersiveengineering.common.config.CachedConfig$ConfigValue.get(CachedConfig.java:58)
     at blusunrize.immersiveengineering.common.items.HammerItem.getMaxDamage(HammerItem.java:71)
     at net.minecraft.item.ItemStack.func_77958_k(ItemStack.java:265)
     at net.minecraft.item.ItemStack.func_96631_a(ItemStack.java:294)
     at blusunrize.immersiveengineering.common.items.HammerItem.getContainerItem(HammerItem.java:210)
     at moze_intel.projecte.emc.mappers.recipe.BaseRecipeTypeMapper.handleRecipe(BaseRecipeTypeMapper.java:35)

### Versions & Modlist
Forge 34.1.15

Complete list of mods
https://gist.github.com/raziel23x/09a088f74cfb0dc0d42495b1eabaa525

**Comment by BluSunrize** [comment]
I don't think this has anything to do with container items at all.

@malte0811 this looks like the config value was not loaded. Any idea for why? Should we be using `getOrDefault` here?

**Comment by raziel23x** [comment]
shadows of fire had to revamp how his tags was being loaded by the listener with this api app https://github.com/Shadows-of-Fire/Placebo/commit/d211b1a693e239e6ba7d2dc3c9c21a72b49ee18d to fix the issues with the reload listeners issues

**Comment by malte0811** [comment]
> this looks like the config value was not loaded. Any idea for why? Should we be using `getOrDefault` here?

Recipe loading, and presumably also the EMC calculations, run before the server config is loaded (that's why I removed the ore crushing option). I would consider this a bug in either Forge or ProjectE, but using `getOrDefault` (with a comment refering to this issue) would be the easier fix as it does not involve arguing with two different projects.

**Comment by BluSunrize** [comment]
Yeah good luck arguing with either, lmao.

I'll throw in the default check then

**Comment by BluSunrize** [comment]
Fixed for future releases

**Comment by raziel23x** [comment]
I tested the latest git release as of this https://github.com/BluSunrize/ImmersiveEngineering/commit/47db0fb63a33c090db117cc1d6e5a45102437064

and still have to run the /reload command to get emc values for vanilla crafting items IE the Diamond chest plate did not have a emc value until i simply typed /reload then after the reload EMC values of the chest plate is now present when the mod is not enabled this problem is not present

here is the latest log
https://gist.github.com/raziel23x/b2edb4185aecde4ada8a7bd7b9adb03f

Forge 34.1.33

Latest List of mods
https://gist.github.com/raziel23x/cc6ef2af649793e8923ee98272a2a49a
