### ISSUE TITLE
1.16.1 Opening redstone connector's GUI while in Lan opens that same GUI for host of the Lan world also

### ISSUE THREAD

**Issue by Stevo154** [BluSunrize/ImmersiveEngineering#4366]
### Description of the issue:
While I'am in a Lan world playing as user (not host) and when I right click with screwdriver on redstone connector to edit it GUI opens but it opens for the host as well and he is able to edit it as well no matter how long he is from me or that connector. This happens every time I open any redstone connector.

### Crashlog:
No crash.

### Versions & Modlist
Forge 32.0.108
IE 1.16.1-4.1.0-123

**Comment by BluSunrize** [comment]
I've finally been able to reproduce this.
Will look into finding a fix.
