### ISSUE TITLE
arc furnace not forming, excavator wheel invisivble

### ISSUE THREAD

**Issue by scoutbraveheart** [BluSunrize/ImmersiveEngineering#4367]
ive triple checked the block placement, but when i right click the cauldron with the engineers hammer it doesnt form. any ideas?

also the excavator wheel is invisible no matter whatn i do.

**Comment by BluSunrize** [comment]
Read the contribution guidelines next time, and respect the issue template. We write it for a reason.

I have no idea what version you are on, so I'm gonna make some guesses:

**Arc Furnace** - you probably built it wrong. Provide pictures. 

**Excavator Wheel** - you're probably using optifine. Either remove that, or go into Immersive Engineering's client config and set `enableVBO` to false.

**Comment by BluSunrize** [comment]
Closed due to lack of response.
