### ISSUE TITLE
Wooden posts drop as item in creative mode

### ISSUE THREAD

**Issue by cobra** [BluSunrize/ImmersiveEngineering#437]
It's not possible to destroy a wooden post in creative mode without having it drop as an item, no matter which position (except the arms) is left-clicked.

**Comment by BluSunrize** [comment]
Yeah, due to how drops are handled. Not easily avoidable, same happens to multiblocks. Not really a serious issue, so wont fix

**Comment by AEnterprise** [comment]
it is pretty easy to avoid, just a check if the player is in creative will fix it

**Comment by cobra** [comment]
And how do you detect that in `breakBlock(World world, int x, int y, int z, Block par5, int par6)`? I couldn't find a way to get the player responsible for breaking this block.

**Comment by Tim020** [comment]
I would imagine that subscribing to the break block event would be an idea... But that seems a little long winded for something that isn't really that big of an issue

**Comment by AEnterprise** [comment]
iirc there is another method that does give the player

**Comment by BluSunrize** [comment]
As I said: Not a serious issue. Waste of code, wont fix.

**Comment by Tim020** [comment]
I agree, not really a 'dupe bug' as such as it shouldn't affect normal gameplay! Loving the mod by the way, keep up the good work :)
