### ISSUE TITLE
1.15.2 Garden Cloche not planting Mystical Agriculture seeds

### ISSUE THREAD

**Issue by rasielisking** [BluSunrize/ImmersiveEngineering#4374]
Immersive engineering version is ImmersiveEngineering-1.15.2-4.1.0-122
MysticalAgriculture version is MysticalAgriculture-1.15.2-3.0.10

How to fix it?

**Comment by BluSunrize** [comment]
We're not doing support for Mystical Agriculture. You can do it yourself, our recipes are JSON based.
