### ISSUE TITLE
[Feature request] Way to load / unload the minecart with a metal barrel in it

### ISSUE THREAD

**Issue by diigits** [BluSunrize/ImmersiveEngineering#4377]
I have a minecart with metal barrel and I was so disappointed to see that there's no way to load / unload it with IE. I tried putting a pump over it and setting the bottom to in / out fruitlessly. Can we get something to do this?

Thanks.

**Comment by BluSunrize** [comment]
IE currently has no ways to load barrel minecarts automatically.
I don't have any immediate plans for this, but I'll leave this open as a suggestion.

**Comment by mindforger** [comment]
water tower, like the one for old steam trains
2 versions
- a small one plus a drain block that can optionally be placed beneath rails
- and a big multiblock one with immersive railroading in mind which comes with drain by default (direction toggled via RS)

the second is just pure optics
