### ISSUE TITLE
[1.16.3] Mixer settings not working and fluid router doesn't route potions

### ISSUE THREAD

**Issue by karlschmidt66** [BluSunrize/ImmersiveEngineering#4380]
There is currently no registry on 1.16.3 for potions as fluids so the router does not accept them. I tried to leave the side I want the potion to go out blank but it simply doesn't even pipe potions. I really don't want my mixers to put water into the next mixer as I'm trying to automate a potion of harming for my chemical thrower. Problem is that the mixer options don't seem to output the bottom fluid only when I have that selected. It always outputs all fluids no matter what setting I have. So I tried the fluid router to sort water from awkward potion and it will sort the water but the awkward potion won't move. I'm stuck because I really want a chain of mixers to automate potions but if I don't have a constant flow of spider eyes all my mixers just fill with awkward potion. 

No crash log (doesn't crash)
Modlist
JEI 
Immersive engineering

**Comment by BluSunrize** [comment]
So, fluid routers are a little broken atm, which makes this awkward (fix for that is coming).

But you *can* use a Fluid Router to make this happen none the less. If you place the router on the output of the mixer, and let only the potion you want output, then the mixer can not output any other fluid.
You can use a Jerrycan to pick a potion fluid up from a barrel, and then use that to set a filter in the router. Using that methodology, you can make sure only the finished potion is output through the router.
