### ISSUE TITLE
[1.12.2] Getting a crash whenever I log on

### ISSUE THREAD

**Issue by Cmrboy26** [BluSunrize/ImmersiveEngineering#4381]
My server crashes whenever I log on because of (I think) Davincis Vessels. Please help.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  MovingWorldCore (movingworld-1.12-6.353-full.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 10/15/20 8:40 AM
Description: Ticking block entity

java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
	at blusunrize.immersiveengineering.common.blocks.stone.TileEntityCokeOven.isDummy(TileEntityCokeOven.java:98)
	at blusunrize.immersiveengineering.common.blocks.TileEntityMultiblockPart.isLogicDummy(TileEntityMultiblockPart.java:290)
	at blusunrize.immersiveengineering.api.ApiUtils.checkForNeedlessTicking(ApiUtils.java:941)
	at blusunrize.immersiveengineering.common.blocks.stone.TileEntityCokeOven.func_73660_a(TileEntityCokeOven.java:104)
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:823)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at blusunrize.immersiveengineering.common.blocks.stone.TileEntityCokeOven.isDummy(TileEntityCokeOven.java:98)
	at blusunrize.immersiveengineering.common.blocks.TileEntityMultiblockPart.isLogicDummy(TileEntityMultiblockPart.java:290)
	at blusunrize.immersiveengineering.api.ApiUtils.checkForNeedlessTicking(ApiUtils.java:941)
	at blusunrize.immersiveengineering.common.blocks.stone.TileEntityCokeOven.func_73660_a(TileEntityCokeOven.java:104)

-- Block entity being ticked --
Details:
	Name: immersiveengineering:cokeoven // blusunrize.immersiveengineering.common.blocks.stone.TileEntityCokeOven
	Block type: ID #737 (tile.immersiveengineering.stone_device // blusunrize.immersiveengineering.common.blocks.stone.BlockStoneDevice // immersiveengineering:stone_device)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-4915,99,1171), Chunk: (at 13,6,3 in -308,73; contains blocks -4928,0,1168 to -4913,255,1183), Region: (-10,2; contains chunks -320,64 to -289,95, blocks -5120,0,1024 to -4609,255,1535)
	Actual block type: ID #737 (tile.immersiveengineering.stone_device // blusunrize.immersiveengineering.common.blocks.stone.BlockStoneDevice // immersiveengineering:stone_device)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1838)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['Cmrboy26'/192, l='world', x=-4913.14, y=134.60, z=1040.02]]
	Chunk stats: ServerChunkCache: 521 Drop: 0
	Level seed: -8372374351716642424
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (212,64,252), Chunk: (at 4,4,12 in 13,15; contains blocks 208,0,240 to 223,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 15227357 game time, 15606171 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 110073 (now: false), thunder time: 96964 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:823)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_265, Eclipse OpenJ9
	Java VM Version: Eclipse OpenJ9 VM (JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20200728_776 (JIT enabled, AOT enabled)
OpenJ9   - 34cf4c075
OMR      - 113e54219
JCL      - c82ff0c20f based on jdk8u265-b01), Eclipse OpenJ9
	Memory: 1654152712 bytes (1577 MB) / 2147483648 bytes (2048 MB) up to 15032385536 bytes (14336 MB)
	JVM Flags: 5 total; -Xoptionsfile=C:\Program Files\AdoptOpenJDK\jdk-8.0.265.01-openj9\jre\bin\compressedrefs\options.default -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple -Xjcl:jclse29 -Xmx14G -Xms2G
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 17 mods loaded, 17 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                                           | Version           | Source                              | Signature                                |
	|:------ |:-------------------------------------------- |:----------------- |:----------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                                    | 1.12.2            | minecraft.jar                       | None                                     |
	| LCHIJA | mcp                                          | 9.42              | minecraft.jar                       | None                                     |
	| LCHIJA | FML                                          | 8.0.99.99         | forge.jar                           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                                        | 14.23.5.2854      | forge.jar                           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | com.elytradev.movingworld.common.asm.coremod |                   | minecraft.jar                       | None                                     |
	| LCHIJA | gorecore                                     | 1.12.2-0.4.5      | avatarmod-1.5.17-alpha.jar          | None                                     |
	| LCHIJA | avatarmod                                    | 1.5.17-alpha      | avatarmod-1.5.17-alpha.jar          | None                                     |
	| LCHIJA | jei                                          | 4.15.0.296        | jei_1.12.2-4.15.0.296.jar           | None                                     |
	| LCHIJA | chisel                                       | MC1.12.2-1.0.2.45 | Chisel-MC1.12.2-1.0.2.45.jar        | None                                     |
	| LCHIJA | movingworld                                  | 1.12-6.353        | movingworld-1.12-6.353-full.jar     | None                                     |
	| LCHIJA | davincisvessels                              | @DVESSELSVER@     | davincisvessels-1.12-6.340-full.jar | None                                     |
	| LCHIJA | elderarsenal                                 | 1.6.1             | ElderArsenal-1.12.2-1.6.1.jar       | None                                     |
	| LCHIJA | cfm                                          | 6.3.1             | furniture-6.3.1-1.12.2.jar          | None                                     |
	| LCHIJA | immersiveengineering                         | 0.12-89           | ImmersiveEngineering-0.12-89.jar    | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LCHIJA | immersivepetroleum                           | 1.1.9             | immersivepetroleum-1.12.2-1.1.9.jar | None                                     |
	| LCHIJA | orespawn                                     | 3.3.1             | OreSpawn-1.12-3.3.1.179.jar         | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | densemetals                                  | 2.0.0             | DenseMetals-1.12.2-2.0.0.30.jar     | d476d1b22b218a10d845928d1665d45fce301b27 |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
MovingWorldCore (movingworld-1.12-6.353-full.jar)
  
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	Profiler Position: N/A (disabled)
	Player Count: 1 / 69; [EntityPlayerMP['Cmrboy26'/192, l='world', x=-4913.14, y=134.60, z=1040.02]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

Mod list in the crash report, forge 1.12.2-14.23.5.2838
Please help because this is urgent!

**Comment by BluSunrize** [comment]
1.12 is no longer supported.

**Comment by Cmrboy26** [comment]
oh.
