### ISSUE TITLE
Can't find when to access proper config file to change vein size of ores

### ISSUE THREAD

**Issue by Troy1108** [BluSunrize/ImmersiveEngineering#4382]
I currently have a forge 1.16.3 server hosted by Apex
I have Immersive Engineering Mod downloaded, version 1.16.3 and everything works fine except the ores do not spawn. So I am trying to access the config file to change the vein size of all the ores. The only problem is that I cannot find access the the proper file. 

When I go to 
User>AppData>Roaming>.minecraft>config>
I have 2 options for IE which are immersiveengineering-client.toml and immersiveengineering-common.toml
neither have the option to increase vein size

The other mods I have on the server are iron chest, pandoras creatures, and jei

**Comment by BluSunrize** [comment]
Ores are configured in the world config!
You gotta go into the save folder of the world and find the IE config in there.
