### ISSUE TITLE
[1.15.2] java.lang.IllegalStateException: Not filled all elements of the vertex

### ISSUE THREAD

**Issue by MatthiasMann** [BluSunrize/ImmersiveEngineering#4383]
### Description of the issue:
I was just walking towards my engineering work bench when the crash happened.

This is the first time I have seen that crash - have been playing with this version of the mod many hours and used and walk past the work bench many times.

### Crashlog:
https://gist.github.com/MatthiasMann/65420b2b7e4c283aebc4492b7199ec31

### Versions & Modlist
Singleplayer
Forge: 1.15.2-forge-31.2.36
IE: ImmersiveEngineering-1.15.2-4.1.0-122
engineersdecor-1.15.2-1.1.3

I'm NOT using Optifine.

**Comment by BluSunrize** [comment]
Is this issue reproducable or did it happen only once?

**Comment by MatthiasMann** [comment]
Hasn't happened since then - so far only this one crash. And I used the work bench heavily - switched between different blue prints etc.

**Comment by BluSunrize** [comment]
I'm going to close this then, as a one off. If it happens more frequently in the future, let us know.
