### ISSUE TITLE
[1.16.3] Steel Hoe has incorrect attack speed/damage values

### ISSUE THREAD

**Issue by Mike-U5** [BluSunrize/ImmersiveEngineering#4386]
All vanilla hoes deal 1 damage when attacking and have and attack speed of 2/3/4 depending on the tier.

However, the Steel Hoe has 4 attack damage and 3.5 damage, which makes it much stronger than the Netherite Hoe. In fact, it has more DPS than the Netherite Sword. 😮

I suspect it was supposed to have 1 damage and 3.5 attack speed as that would place it between the Iron Hoe and the Diamond Hoe in terms of stats.

**Comment by BluSunrize** [comment]
Fixed for future release

**Comment by Mike-U5** [comment]
Just wondering, why does this fix also have to buff the damage values of all steel items to diamond? I think you could just keep it at 3.5F and it'd work fine.

**Comment by BluSunrize** [comment]
Right so, Vanilla has a parameter of the "damage bonus" of a hoe. They use that to write the negative value of the material's damage bonus in there (-3 for Diamond, for instance). That bonus is then added to the hoe's damage, cancelling out the value that it gets from its tool material.

Unfortunately, Vanilla decided to make that parameter an Integer. Integers can not have decimal points. I can't write -2.5 in there, only -2 or -3, which means you would end up with a hoe that either does +1.5 damage or +0.5, but not the +1 that it should. So to remedy that, I buffed the damage of all steel tools to match the level of diamond and used -3 as the modifier for the hoe.
