### ISSUE TITLE
Cannot access IE config files to edit ores spawns

### ISSUE THREAD

**Issue by Troy1108** [BluSunrize/ImmersiveEngineering#4388]
Hi sorry this is my second post on here and Im very very new to modding in minecraft. I cannot seem to find where I can access in IE config files to adjust the ore spawns. My server is hosted by apex. When I go into FTP client > File List > config. All I see is for IE is immersiveengineering-common.toml which only code is 

#A list of preferred Mod IDs that results of IE processes should stem from, aka which mod you want the copper to come from.
#This affects the ores dug by the excavator, as well as those crushing recipes that don't have associated IE items. This list is in oreder of priority.
preferredOres = ["immersiveengineering"]

[debug]
	#A config setting to enable debug features. These features may vary between releases, may cause crashes, and are unsupported. Do not enable unless asked to by a developer of IE.
	enableDebug = false

	[debug.wires]
		#Run sanity checks on the wire network after every interaction. This will cause a decent amount of lag and a lot of log spam if the wire network isn't fully intact. Only enable when asked to by an IE developer.
		validateNets = false
		#Enable detailed logging for the wire network. This can be useful for developers to track down issues related to wires.
		enableWireLogger = false

Sorry but Im very new to modding so some help would be greatly appreciated

**Comment by BluSunrize** [comment]
Ores are configured in the world config. On a server that's in `world/serverconfig/immersiveengineering-server.toml`. For a singleplayer game it's in `saves/<world name>/serverconfig/immersiveengineering-server.toml`

**Comment by auddie2015** [comment]
I just asked this on Curse... Should have come here first. Thanks for your great mod!
