### ISSUE TITLE
Mirrored Generator redstone control is not solid. 

### ISSUE THREAD

**Issue by JLBShecky** [BluSunrize/ImmersiveEngineering#439]
When the diesel generator is mirrored it does not make the block that is the controller on the opposite side solid so you can't place a lever on it like you can with the default side. Also the block where the redstone control was on the original side doesn't stop being solid after the switch. I am not sure if I have described the issue well enough so here is picture of generator that has been mirrored with a lever sitting where the redstone control is in the generator's normal state.

![image](https://cloud.githubusercontent.com/assets/842813/9978486/d6aa5aca-5eff-11e5-9f0c-e2fc561d8374.png)

Step to reproduce:
Build generator multiblock in any orientation. (North/South/East/West)
Turn the multiblock into machine using hammer.
Then mirror the generator by click on the front.
Try placing a torch on the redstone control.

**Comment by cobra** [comment]
Yep, `isSideSolid` doesn't check whether the generator is mirrored. That's simple.
But somehow the `mirrored` field isn't updated properly, requiring more work than this additional check.

**Comment by BluSunrize** [comment]
I could fix it myself, but sure, go ahead cobra. Make it a combined one

**Comment by cobra** [comment]
Will do. It's a lot easier for me now that you've merged #435. Praise git stash!
