### ISSUE TITLE
[1.16.3] Crash with JEI Integration

### ISSUE THREAD

**Issue by BluSunrize** [BluSunrize/ImmersiveEngineering#4391]
Found by LatvianModder on ~~Forgecraft~~ correction: Not Forgecraft. But reported in that Discord.

https://mcmc.dev/crashes/client/LqI5dTs2GLsu

Creosote tag is used in the burn time event, which is called by JEI Integration to put the burn time in the tooltip. If the tag isn't populated yet, this explodes.

The ideal solution would of course be for JEI Integration to not check that early, but we can look into adding a safeguard into IE.

**Comment by IchigoGames** [comment]
https://pastebin.com/Z4wjTLTx i think i just had the same crash

**Comment by BunCat09** [comment]
Yeah. It is happenning to me as well: https://pastebin.com/69ZWcuEZ .(client crash log)
About Creosote oil being mentioned before it was registered or something. But it is weird that the crash happens when i try to apply a resourcepack. 

Edit: I am running 1.16.4 not 1.16.3.

**Comment by GordonHollow** [comment]
Had the same issue. I found a way to enable resourcepack or shaders - disable IE, enable all you need, restart game, enable IE
