### ISSUE TITLE
Crash While Turning Shaders On/off with optifine

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#4395]
Description of the issue:
When I try to turn shaders on or off it crashes and gives me an error report saying IE, I cant read them, but I uploaded it, Im using Sildur's Vibrant Shaders [v1.281]
[crash-2020-10-18_15.22.32-client.txt} I replicated the same thing with just optifine and no IE, didnt crash.
Also, I cant load worlds made with IE once IE is taken out of mods
https://github.com/BluSunrize/ImmersiveEngineering/files/5398142/crash-2020-10-18_15.22.32-client.txt
### Versions & Modlist
Forge: 1.16.3 - 34.1.23
Immersive Engineering: 1.16.3-4.1.0-0124
Optifine: Preview 1.16.3_HD_U_G4
 Mod list 
Imersive Enginering and Optifine

**Comment by BluSunrize** [comment]
Optifine is not supported, see our contribution guidelines.
