### ISSUE TITLE
[1.16.3] Client Crash - java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 , blusunrize.immersiveengineering.common.blocks.IETileProviderBlock.func_176211_b

### ISSUE THREAD

**Issue by ProsperCraft** [BluSunrize/ImmersiveEngineering#4396]
### Description of the issue:
Client crashed.

### Crashlog:
https://gist.github.com/ProsperCraft/5f506c649480e3375d8f9f2b17715f6d
Latest log- https://gist.githubusercontent.com/ProsperCraft/1dcfaad61b55ddabd6c036c59cb7a110/raw/13788a0a20274197338de17a65f69a7f0aae1ca5/gistfile1.txt

### Versions & Modlist
ImmersiveEngineering-1.16.3-4.1.0-124
forge-1.16.3-34.1.23
Modpack- TownCraft TWO

**Comment by BluSunrize** [comment]
Can you provide a bit more info? Has this happeend multiple times? Can you reproduce it somehow?

**Comment by ProsperCraft** [comment]
I think it happened once before, I thought I had reported it but couldn't find the issue.

I don't know how to reproduce it.

It seemed to have happened when I was opening my voxelmap world map.

**Comment by BluSunrize** [comment]
Yeah I am puzzled as to how this would happen. The crash happens within vanilla code.

I'm closing this for now, if you manage to produce a frequently reproducible test case, we may be able to investigate this further.
