### ISSUE TITLE
Feature request - "crouch allows STOP on scaffold" 1.16.3

### ISSUE THREAD

**Issue by 1234Eldo** [BluSunrize/ImmersiveEngineering#4397]
NOT A BUG

Pressing the "crouch" button allows the player to stop movement while on Minecraft vanilla ladders.  Ever consider allowing this on the IE scaffolding?  This would make attaching cables and many other tasks MUCH easier!  Currently, pressing the "crouch" button simply slows the player movement on the scaffold, but does not allow one to stop, as it does with vanilla ladders.

**Comment by BluSunrize** [comment]
We can't. Vanilla handles ladders in it's own way and we don't have an easy hook there to make it happen. We've tried that before.
