### ISSUE TITLE
Water wheel and Windmill invisible

### ISSUE THREAD

**Issue by pajakkox** [BluSunrize/ImmersiveEngineering#4399]
### Description of the issue:
Water wheel and Windmill invisible when placed, but hitboxes are visible.

### Crashlog:
No crashes.

### Versions & Modlist
Forge version: 1.16.1-32.0.108
Modlist: 
Abnormals-core 1.16.1-2.0.3
backpacked-1.5.1-1.16.1 
BiomesOPlenty-1.16.1-11.0.0.395-universal
buildersaddition-1.16.1-20200911a
car-1.16.1-1.0.11
constructionwand-1.16.1-1.4
corgis-1.0.5-1.16.1
DeathCounter-1.16.1-1.2.1
EndReborn+[0.7.5]
Flamingo-oh-oh-oh-1.0.1-MC1.16.1
foodexpansion-1.6.0
frogs-1.16.1-1.0.0
GentleFawn-1.1.1-MC1.16.1
gravestone-1.16.1-1.0.6
ImmersiveEngineering-1.16.1-4.1.0-123
Incubation-1.16.1-1.1.0
jei-1.16.1-7.0.1.10
KiwiBirds+1.3+1.16.1
lanterncolors-1.16.1-2.0.0
livingthings-1.16.1-1.0.3
mcw-bridges-1.0.4-mc1.16.1
mining-helmet-1.16.1-1.0.8
moblocks-v0.7.1c
MutantBeasts-1.16.1-1.1.1
OfflineSkins-1.16.1-v1a
Ping-1.16.1-1.6.5
ServerTabInfo-1.16.1-1.3.1
simplefarming-1.16.1-1.3.2
simpleplanes-1.16.1-2.0.5.3
spiders-2.0-1.16.1-1.0.1
StorageDrawers-1.16.1-8.0.0
supertools-1.16.1-2.
ToolBelt-1.16.1-1.14.1
torohealth-1.16.1-forge-2
u_team_core-1.16.1-3.1.4.182
Upgraded+Netherite+1.16.1+-+1.5.1
Waddles-1.16.1-0.8.7

https://imgur.com/a/EfnYDwJ

**Comment by BluSunrize** [comment]
You're using optifine, which is not supported. You probably didn't read the contribution guidelines.

You also didn't bother searching for previous issues.

Either remove Optifine, or go into IE's client config and set `enableVBO` to false.
