### ISSUE TITLE
Weird glitch

### ISSUE THREAD

**Issue by ImperialWizard** [BluSunrize/ImmersiveEngineering#44]
So basically I'm using IE on my own little server (2 person at max time) and for some reason whenever I restart the server all my wires disappears ! I don't know if there is anything else I can add except that my build are in a Rftools dimension and that I run on 0.1.15

**Comment by ImperialWizard** [comment]
By the way sorry if my English is bad !

**Comment by BluSunrize** [comment]
Yeah, there was a bug with other dimensions, but I think I fixed it...just don't remember in which version ^^

**Comment by ImperialWizard** [comment]
Oh Ok ! Well BTW I can't find any version after 0.1.15 on your Dropbox !

**Comment by ImperialWizard** [comment]
Nervermind found it !
