### ISSUE TITLE
Inconsistent cable config entries

### ISSUE THREAD

**Issue by cobra** [BluSunrize/ImmersiveEngineering#440]
WTH is going on with the cable section of the config file?
- transfer rate: text: 5 types, default values: 6 types, fix for old/broken config: 5 types
- cable loss: text: 5 types, default values: 6 types, fix for old/broken config: 5 types
- colour: no text, default values: 5 types,  fix for old/broken config: 6 types
- length: text: 5 types, default values: 6 types, fix for old/broken config: 5 types

Is the sixth entry something that shouldn't be there or is this intended as some sort of default value for addons?

**Comment by BluSunrize** [comment]
Lol, no idea.
Will investigate
