### ISSUE TITLE
[1.16.3] IE's banner patterns have no transparency

### ISSUE THREAD

**Issue by Kasran** [BluSunrize/ImmersiveEngineering#4400]
### Description of the issue:
Every banner pattern added by IE has no transparency. The banner appears completely black with just the pattern on top, no matter what was already on the banner before applying the pattern. It looks that way both in the loom:
![malfunctioning banner in the loom](https://user-images.githubusercontent.com/3673421/97099496-06b30880-1660-11eb-9a7c-0fcce3b2f6de.png)

...and in the world:
![malfunctioning banner in the world](https://user-images.githubusercontent.com/3673421/97099506-19c5d880-1660-11eb-945b-f27260a88a97.png)

### Crashlog:
N/A

### Versions & Modlist
- Minecraft 1.16.3
- Forge 34.1.25

The screencaps above were taken on an instance using only the following mods:
- Immersive Engineering 1.16.3-4.1.0-124
- JEI 1.16.3-7.6.0.49

**Comment by BluSunrize** [comment]
Fixed for future releases.
