### ISSUE TITLE
[1.16.3] Crash on startup, probably due to Forge 1.16.3-34.1.28

### ISSUE THREAD

**Issue by Dunkmania101** [BluSunrize/ImmersiveEngineering#4401]
Hello!

I recently updated to forge 1.16.3-34.1.28 and got a crash. The report, linked below, said it was something to do with a particle called "immersiveengineering:fluid_splash". I hadn't gotten this until now and, as of writing this on Oct. 26, 2020, IE hasn't been updated since Oct. 4, 2020, so I suspect it's something to do with that version of Forge. The last Forge version I'd used before this happened was 34.1.25, where no issues of this sort occurred.

[Crash Log](https://gist.github.com/Dunkmania101/d5b8a540a3841b457a8d58c1dcf8849e)

I tested this again with nothing but IE installed and the same issue occurred. That minimalist run was the origin of the linked report.

In both runs, the latest IE, 1.16.3-4.1.0-124, was used.

Thanks!

**Comment by BluSunrize** [comment]
Uhh, okay, looks like a forge bug then. Needs investigation.
