### ISSUE TITLE
[1.16.3] Enabling Retrogen crashes minecraft when loading a old save

### ISSUE THREAD

**Issue by odorousrex** [BluSunrize/ImmersiveEngineering#4403]
IE Version: 1.16.3-4.1.0-124
Forge Version: 34.1.25

The crash-report pastebin is here: [https://pastebin.com/uBTjnuSx](https://pastebin.com/uBTjnuSx)

The basic gist 
java.lang.NullPointerException: Exception in server tick loop
	at blusunrize.immersiveengineering.common.world.IEWorldGen.generateOres(IEWorldGen.java:109) ~[?:?] {re:classloading}
	at blusunrize.immersiveengineering.common.world.IEWorldGen.serverWorldTick(IEWorldGen.java:175) ~[?:?] {re:classloading}

In my immersiveengineering-server.toml I changed the retrogen key to "TEST" and enabled it for all ores, and get the above crash every time.

**Comment by BluSunrize** [comment]
Crash confirmed in 1.16.3
Crash not existent in 1.16.1

Seems to result from the use of `OCEAN_FLOOR_WG` instead of `OCEAN_FLOOR`. Mekanism had similar issues, was fixed by a custom Ore Feature.

**Comment by BluSunrize** [comment]
Fixed for future release
