### ISSUE TITLE
[1.16.3] Crash at Startup 

### ISSUE THREAD

**Issue by ALoveOverall** [BluSunrize/ImmersiveEngineering#4404]
Game does not load past Forge loading process and crashes back to launcher. I updated Forge to the latest version to support the latest Quark version. I have been able to reproduce the crash with just IE and Forge.
 
Forge: 1.16.3 - 34.1.33
IE: 1.16.3 - 4.1.0-124

Crashlog: https://pastebin.com/Er205WsA

**Comment by malte0811** [comment]
This is a known issue and has been fixed for the next release. For now you should downgrade Forge to version 34.1.25.
