### ISSUE TITLE
Game crashing when applying Resource pack

### ISSUE THREAD

**Issue by jharvey00** [BluSunrize/ImmersiveEngineering#4407]
When I apply the Sphax 1.16 128x resource pack the game loads the pack, then subsequently goes back and loads again; and then proceeds to crash with the message: 

The game crashed whilst rendering overlay
Error: java.lang.IllegalStateException: Tag forge:creosote used before it was bound
Exit Code: -1

This seems to happen with other Resource packs as well
Crash Report: https://pastebin.com/JFMKGJbD

**Comment by BluSunrize** [comment]
This appears to be a duplicate of #4391
