### ISSUE TITLE
Game crashing when standing on certain blocks 1.16.3

### ISSUE THREAD

**Issue by SergioGymm** [BluSunrize/ImmersiveEngineering#4408]
Hi,
I have recently updated to minecraft version 1.16.3 and have installed this mod. I have tried multiple version of forge (34.1.35, 34.1.25, 34.2.20 and 34.1.30) but having a problem in which standing on certain blocks from this mod freezes my game and causes a crash. Here is the crash report https://pastebin.com/3Nmjbn5E. hope to hear back from you soon. 

Thanks

### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
Describe what happens, how it affects your game/gameplay and provide screenshots where possible.

### Crashlog:
If your Minecraft instance has crashed, a file will have been generated in the folder `crash-reports` of your minecraft folder. To understand what has happened, we need to know the content of that file. But please don't just put it directly in your report (that makes it hard to read), upload it to a site like [pastebin](http://pastebin.com) or [gist](http://gist.github.com) and put a link in the actuall bug report.

### Versions & Modlist
IE and Forge versions are mandatory. *Note that saying "latest" is **not** valid. Always give the proper version number*
Other mods should be listed (with their versions) in a [pastebin](http://pastebin.com) or [gist](http://gist.github.com) upload. The easiest way to get these lists is a crashlog, you may force one with F3+C.
If your game crashed (see above) you may omit the modlist, but IE and Forge version would still be nice.

Also, please try testing an issue in a minimal instance, with just IE, Forge and maybe JEI. That makes elminating compat issues easier.

### Lastly (you may delete this from the report itself)
Please, for the love of all that is voxelbased, **read the contribution guidelines. They are linked to the right in the message box.**
When reporting issues, these are crucial, and the team withholds the right to close an issue for the plain stupidity of not reading and adhering to them.

Thank you for reporting issues, without people reporting them, they wouldn't get fixed. You're helping contribute to this mod and that is much appreciated <3

**Comment by BluSunrize** [comment]
Remove Baritone and see if that fixes the issue.

**Comment by BluSunrize** [comment]
Also, that's now how you use an issue template.

**Comment by ViRb3** [comment]
Getting same problem by standing on top of Conveyor Belt, Pneumatic Craft receives a null Block#getCollisionShape(). More info: https://github.com/TeamPneumatic/pnc-repressurized/issues/649

**Comment by BluSunrize** [comment]
Yeah, and you also didn't remove Baritone. Which overall seems to be designed as a cheating software.

So, uh, fuck all of that. No support from our end.
