### ISSUE TITLE
[1.16.3] Arc Furnace not reducing Electrode integrity during use

### ISSUE THREAD

**Issue by zimboptoo** [BluSunrize/ImmersiveEngineering#4409]
### Issue Description ###
I created 3 Arc Furnace Electrodes with the inefficient crafting recipe (since I didn't have the blueprint yet).  The tooltip showed that they were at 50% integrity.  However, after being used to smelt hundreds of ingots, from both dust and ore, the integrity has not gone down at all on any of the electrodes.  

### Versions & Modlist ###
Minecraft Version: 1.16.3
IE Version: 1.16.3-4.1.0-124
Forge Version: 34.1.0, 34.1.14

Modlist:
https://gist.github.com/zimboptoo/9907748f47d2dabd66f305d5558b7e48

**Comment by BluSunrize** [comment]
Confirmed on 1.16.3. Issue is not found on 1.15 or 1.16.1

**Comment by BluSunrize** [comment]
Fixed for future releases
