### ISSUE TITLE
[1.16.3] When used with Forge 1.16.3-34.1.27+ causes crash when also loading mods that register custom particles

### ISSUE THREAD

**Issue by bmwalter68** [BluSunrize/ImmersiveEngineering#4410]
### Description of the issue:
Installing IE along with any mod that registers custom particles (example: SimplyJetpacks 2, Powah) game crashes with the following error:

java.lang.IllegalStateException: Failed to load description for particle simplyjetpacks:rainbow

This can be reproduced by creating a 34.1.27+ instance and adding IE and SimplyJetpacks 2, Powah or really any mod that registers custom particles.

### Crashlog:
https://pastebin.com/xZhQ5aSa

### Versions & Modlist
Forge 34.1.35
ImmersiveEngineering-1.16.3-4.1.0-124.jar
SimplyJetpacks2-1.16.3-2.6.3.0.jar

**Comment by Inpaladin** [comment]
Seconding this, this is a super major bug.

**Comment by 755437985** [comment]
got the same crash

**Comment by BluSunrize** [comment]
Yeah, we know. Forge decided to pull a breaking change.
Downgrade to 34.1.25 for now. The next release will fix this.

**Comment by BedrockLegends** [comment]
Yep same issue, I just removed the mod till its fixed as some mods I use now require the new forge version

**Comment by adriantomaszewski** [comment]
Just IE also crashes. Same issue.
