### ISSUE TITLE
[1.12.2] Adding new recipes with CraftTweaker leaks text in the Engineer's Manual

### ISSUE THREAD

**Issue by Atricos** [BluSunrize/ImmersiveEngineering#4411]
Minecraft version: 1.12.2
Forge version: 14.23.5.2854
IE version: 0.12-98
CraftTweaker2 version: 1.12-4.1.20.586

I have added many custom recipes to the Fermenter and the Industrial Squeezer with CraftTwealer:
```
mods.immersiveengineering.Fermenter.addRecipe(null, <liquid:ethanol> * 80, <minecraft:pumpkin>, 6400);
mods.immersiveengineering.Fermenter.addRecipe(null, <liquid:ethanol> * 80, <minecraft:wheat>, 6400);
mods.immersiveengineering.Fermenter.addRecipe(null, <liquid:ethanol> * 80, <minecraft:carrot>, 6400);
mods.immersiveengineering.Fermenter.addRecipe(null, <liquid:ethanol> * 80, <minecraft:beetroot>, 6400);
# etc. ....
```

```
mods.immersiveengineering.Squeezer.addRecipe(null, <liquid:plantoil> * 80, <actuallyadditions:item_rice_seed>, 6400);
mods.immersiveengineering.Squeezer.addRecipe(null, <liquid:plantoil> * 80, <actuallyadditions:item_canola_seed>, 6400);
mods.immersiveengineering.Squeezer.addRecipe(null, <liquid:plantoil> * 20, <actuallyadditions:item_flax_seed>, 6400);
# etc. ...
```

Once they were successfully added to the game, I have opened the Engineer's Manual to see the changes, and the the text leaked out of the given pages:
![image](https://user-images.githubusercontent.com/24854267/97712807-3ed2a500-1abf-11eb-9beb-e04d74b5937e.png)
![image](https://user-images.githubusercontent.com/24854267/97712831-46924980-1abf-11eb-913f-dce15b8d13ac.png)

Potential fix: Break the text into parts and automatically add new pages when this text doesn't fit. (Which I know, is probably easier said than done.)

**Comment by BluSunrize** [comment]
1.12 is no longer receiving any support
