### ISSUE TITLE
[1.16.3] Cannot find configuration options to adjust/disable ore generation in worldgen

### ISSUE THREAD

**Issue by bmwalter68** [BluSunrize/ImmersiveEngineering#4415]
### Description of the issue:
Ore generation during the worldgen phase does not seem to have options in the immersiveengineering-common.toml file and as a result cannot be disabled or adjusted.  From looking through the code, it seems there is a 'server' config class alongside 'client' and 'common' which has wire and oregen configuration, but I cannot seem to find the resulting file in the config directory nor are any of the options in the -common config file.

### Versions & Modlist
Forge: 34.1.25
ImmersiveEngineering-1.16.3-4.1.0-124.jar

**Comment by malte0811** [comment]
The server configs are per world, you can find them in the config folder inside each world. To control the settings for new worlds you can place the config you want to use in `defaultconfigs`.
