### ISSUE TITLE
weird interaction with ender io conduits which caused water wheel and coke oven models to duplicate

### ISSUE THREAD

**Issue by sev7ves** [BluSunrize/ImmersiveEngineering#4417]
### Description of the issue:
As the title said when I was placing down ender IO conduits one of them turned transparent and the water wheel and coke oven near to it duplicated (I was dumb and didn't take the screenshot with the broken conduit as I broke it before I thought of taking the picture). all other blocks were left untouched by the glitch. I had played for a while before getting the glitch and my memory was pretty full and I kept getting lag spikes which could have been the cause but I can't be sure.

![huh](https://user-images.githubusercontent.com/58966116/97792665-77ee4080-1bb7-11eb-96ce-d40b2dfaccce.png)

### Versions & Modlist
modpack:FTB university
IE :0.12-98
ender IO:1.12.2-5.2.59
forge:1.12.2-14.23.5.2847

**Comment by BluSunrize** [comment]
1.12 is no longer supported.
