### ISSUE TITLE
Redstone connectors do not turn off signal when redstone signal is removed. 

### ISSUE THREAD

**Issue by elkillo** [BluSunrize/ImmersiveEngineering#4419]
version 124 with forge 34.1.24

when using Redstone connectors a signal can be given to the connector and it will activate the object (piston in my case) but when the signal is removed (happens with buttons, Redstone torches, and levers) the connectors will continue to send a signal even though one is not being supplied. 

troubleshooting step to recreate is the following

1: place block with level
2: connect up the block with a connector to a another block requiring a signal. 
3: set out put ends and ensure they are the same color channel
4: flip lever on and then off

signal will stay even with lever turned off full mod list can be supplied upon request (tho this build is mostly vanilla with immersive engineering as the one mod cus its cool)

**Comment by malte0811** [comment]
A modlist and some screenshots of the exact setup would be great, it's working correctly for me.

**Comment by elkillo** [comment]
My apologizes, i was testing it and it appears the issue is no longer present. I was going through the log and ended up removing titanium ( the lib mod) and the issue is resolved. feel free to close and disregard. thanks for the mod!
