### ISSUE TITLE
[Suggestion] Automatically disable VBOs if Optifine is installed

### ISSUE THREAD

**Issue by ViciousVinnyD** [BluSunrize/ImmersiveEngineering#4420]
With VBOs disabled windmills work fine with Optifine installed and the two mods can be used together without much consequence.

Alternatively you can add a comment to the config so people know and stop reposting this issue.

**Comment by BluSunrize** [comment]
Alternative: Stop using Optifine. It's not our job to account for their bullshit.

But thankfully, Malte is nicer than me.
