### ISSUE TITLE
Uncraftable items always show as craftable in minecraft default recipe guide.

### ISSUE THREAD

**Issue by TheQKnight** [BluSunrize/ImmersiveEngineering#4421]
### Description of the issue:
In survival, some items from immersive engineering show as always craftable in the default minecraft guide. An invalid item even shows up as craftable with the name item.immersiveengineering.bullet..name.

I know that lots of people end up removing the default minecraft recipe book, so this wouldn't be an issue, but when playing in vr with Vivecraft or just playing modded with newbie players, the default guide book can be super useful for quickly crafting things.

### Versions & Modlist
forge-14.23.5.2854
Minecraft 1.12.2
ImmersiveEngineering-0.12-98

**Comment by BluSunrize** [comment]
1.12 is no longer supported.
