### ISSUE TITLE
[1.16.3] Crash while using forge versions past 34.1.25

### ISSUE THREAD

**Issue by thomaspara** [BluSunrize/ImmersiveEngineering#4422]
### Description of the issue:
Crash occurs while loading the game with IE version 1.16.3-4.1.0-124. This crash does not occur when using Forge version 34.1.25. When using various versions past that, the following Crashlogs are generated:

### Crashlog:
Forge 34.1.27 : https://pastebin.com/hMRbR24M
Forge 34.1.35, this one just closed Minecraft with no error screen : https://pastebin.com/RnttmiJD
Forge 34.1.41 : https://pastebin.com/ezZ7H2r5

**Comment by Blindside33** [comment]
I'm having the exact same problem with Immersive Engineering-1.16.3-4.1.0-124 on forge Forge 34.1.41

**Crashlog:**
Forge 34.1.41 : https://pastebin.com/ezTeZY70

**Comment by BluSunrize** [comment]
Yeah we know. It's literally pinned at the top of the issue list. Use 25 for now.
