### ISSUE TITLE
Crash on startup load_registries

### ISSUE THREAD

**Issue by SirEndii** [BluSunrize/ImmersiveEngineering#4423]
### Description of the issue:
I want to start my game and it crashes.

### Crashlog:
Crash-report: https://hasteb.in/oselitec.rb
Log: https://hasteb.in/fucutiro.sql

### Versions & Modlist
Modlist: https://hasteb.in/azipibil.cs
IE-Version: 4.1.0-124
Forge-Version: 34.1.42

It also happens when i only have IE in my mods folder.

Thank you for reporting issues, without people reporting them, they wouldn't get fixed. You're helping contribute to this mod and that is much appreciated <3 <3 <3

Sorry for my english if it's bad, it's not my native language.

**Comment by BluSunrize** [comment]
User Forge version 34.1.25 until the next IE release comes out.

**Comment by SirEndii** [comment]
Okay 👍🏿
