### ISSUE TITLE
Minecraft Crashes on startup. 1.16.3 - Forge 34.1.35

### ISSUE THREAD

**Issue by philmousseau** [BluSunrize/ImmersiveEngineering#4426]
The game crashed whilst rendering overlay
Error: java.lang.IllegalStateException: Failed to load description for particle immersiveengineering:fluid_splash
Exit Code: -1

Is what I get. Here is the crash log, 
[crash-2020-11-02_20.16.44-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5478827/crash-2020-11-02_20.16.44-client.txt)

**Comment by BluSunrize** [comment]
Downgrade to 34.1.25, and search recent issues next time.
