### ISSUE TITLE
[1.16.3] Mod Fails To Load on Startup

### ISSUE THREAD

**Issue by Nerdy98** [BluSunrize/ImmersiveEngineering#4427]
My game keeps crashing during startup, and Immersive Engineering is apparently causing it. I've attached a screenshot and the crashlog. Any idea what's causing this? I think it might be a mod conflict, but i'm not sure.
[crash-2020-11-03_15.04.40-fml.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5484344/crash-2020-11-03_15.04.40-fml.txt)
![crash-2020-11-03_15 04 40-fml](https://user-images.githubusercontent.com/5460782/98046132-db11ea00-1de6-11eb-9bf0-89a6943eb739.png)

**Comment by BluSunrize** [comment]
New version of IE just released. Should be processed on Curseforge in half an hour. Update to that when it's available.
