### ISSUE TITLE
[1.16.3] Error With Loading Registries

### ISSUE THREAD

**Issue by adriantomaszewski** [BluSunrize/ImmersiveEngineering#4428]
Error when loading in using newest version of Forge(forge-34.1.42), MC(1.16.3), and IE versions
(ImmersiveEngineering-1.16.3-4.1.1-127, ImmersiveEngineering-1.16.3-4.1.0-124, and ImmersiveEngineering-1.16.3-4.0.1-121). Immersive Engineering encountered an error during the load-registries event phase. Error occurs both with and without Optifine. Error also occurs with just Immersive Engineering with same Forge, MC, and IE Versions.

Here is the log: https://pastebin.com/Q2Su5Skg

Sorry if this report is poorly written, its my first time using GitHub.

**Comment by adriantomaszewski** [comment]
Sorry for not looking at closed issues, will downgrade for now.

**Comment by BluSunrize** [comment]
Your crashlog is of you using IE 4.1.0-124.

Can you reproducce this issue on 4.4.1-127, and if so, can you please provide a log?

**Comment by adriantomaszewski** [comment]
Yeah, it is working now on the 127 version, the Instance of MC probably just didn't update because of buggy Twitch Launcher. Sorry for wasting your time, your mod is amazing and I wish you the best.

**Comment by BluSunrize** [comment]
Glad to hear it's working! Have a nice day =)
