### ISSUE TITLE
Problems with the windmill and water wheel

### ISSUE THREAD

**Issue by ExodusR** [BluSunrize/ImmersiveEngineering#4429]
Hello !

I install this mod and many others on the server of my friends, and we have a problems with the windmill and the water wheel, i explain : When i put many windmill/water wheel we just saw the first and the other are completely invisible, they work but it wasn't really practical or petty

The server running in 1.16.3 with forge 34.1.25

If you know how to solve this problem, we are takers, thanking you

![2020-11-04_17 26 09](https://user-images.githubusercontent.com/73955899/98138144-14b82300-1ec3-11eb-9c4e-0eb6a1ca8d78.png)

**Comment by malte0811** [comment]
You seem to be using Optifine. Either remove that, update IE or disable VBOs in the IE client config.
