### ISSUE TITLE
[Suggestion] Multiblock Wire Connector/"Power Strip"

### ISSUE THREAD

**Issue by Barhandar** [BluSunrize/ImmersiveEngineering#443]
To facilitate using multiple wires in parallel, how about a wire connector that can take one or multiple inputs, and then spread them over one or multiple outputs? Possibly with integrated transformer(s) as part of the multiblock.

Would be interesting if said multiblock could be dynamically extensible and could be broken piece by piece, with power being shared across it, so it can support (theoretically) any number of connections.

**Comment by BluSunrize** [comment]
LV and MV connectors as well as HV relays can already take multiple wires and will split power accordingly, why would we need something else?

**Comment by DanNetwalker** [comment]
I can only see one use. Integrated power surge protection (circuit breakers). If you implement wire fusing if too much power is drawn from it, this piece could be a safety measure. Even further, having a more compact way of putting several circuit breakers.

But then again, it's more a cosmetic nuisanse than a necesity. And I personally rather have a wall of circuit breakers with wires going down into the "tecnical floor" on the room.
