### ISSUE TITLE
[1.16.3] JEI GUI not appearing with IE installed

### ISSUE THREAD

**Issue by Ordenkeim93499** [BluSunrize/ImmersiveEngineering#4430]
If you join a multiplayer server directly after minecraft has loaded, the JEI GUI does not appear.
If you start minecraft fresh, join a singleplayer world first and then a multiplayer server the GUI appears and works normal.

Pretty sure the cause is IE. 
I just put the newest IE version in my mods folder and the problem appeared right at that moment. 

Forge Version:  1.16.3-forge-34.1.42
IE Version:         ImmersiveEngineering-1.16.3-4.1.1-127.jar
JEI Version:        jei-1.16.3-7.6.0.49.jar
JEI Integration:  jeiintegration_1.16.3-6.0.0.8.jar

Full modlist:
[modlist.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5490018/modlist.txt)

**Comment by BluSunrize** [comment]
Please provide us with your debug log file

**Comment by Ordenkeim93499** [comment]
Hy I attached both debug logs. 
One where I joint mulitplayer directly without JEI loading and one where I first join SP to get JEI working and than MP.
I'am sry I didn't know exactly what you need to debug it. If you need more please let me know. :) 

THX for your effort! 

[debug_direct_join_to_multiplayer.log](https://github.com/BluSunrize/ImmersiveEngineering/files/5492584/debug_direct_join_to_multiplayer.log)
[debug_first_SP_than_MP.log](https://github.com/BluSunrize/ImmersiveEngineering/files/5492587/debug_first_SP_than_MP.log)

**Comment by Ordenkeim93499** [comment]
So in the 1.16.4 Version of IE it seems like this Glitch/Bug is not existent anymore. 
Think this issue is closed cause of this. :)
