### ISSUE TITLE
[1.16.2] Is there a way to get this to work on 1.16.2?

### ISSUE THREAD

**Issue by DrBretto** [BluSunrize/ImmersiveEngineering#4432]
Big fan of this mod and no worries if this can't be easily done. 

### Description of the issue:
Many 1.16.1 and 1.16.3 mods work well enough on 1.16.2. I was wondering if it was as simple as removing a basic version check to let the 1.16.3 version work on 1.16.2? My server is stuck on this version because of another mod and I can't upgrade it. 

###
No crash report. The game loads normally then gives a message that it needs minecraft version 1.16.3 (1.16.1 if I try that version)

### Versions & Modlist
Minecraft 1.16.2
Forge ending in 61

**Comment by malte0811** [comment]
No, we use features added to Forge in 1.16.3 to implement ore generation. Running IE for 1.16.3 on 1.16.2 in some way would most likely crash very early. Also distributing modified builds of IE without permission from @BluSunrize would be a license violation (and you would need to do that unless you want every player on your server to make the edits themselves).
