### ISSUE TITLE
[1.16.3 feature request] Add way to disable ore generation

### ISSUE THREAD

**Issue by Goldenlion5648** [BluSunrize/ImmersiveEngineering#4434]
### Description of the issue:
There is no config option for disabling each of the ores generated by the mod

No crash log

### Versions & Modlist
ImmersiveEngineering-1.16.3-4.1.1-127
forge-34.1.42
Other mods don't affect this feature

**Comment by BluSunrize** [comment]
Yes, there is. Ores are configured on a per world basis.

Refer to this tweet for further information:

https://twitter.com/BluSunrize/status/1324466404276510722

**Comment by Goldenlion5648** [comment]
Awesome, thanks. Maybe link that tweet (or mention that) in the config? I was used to the 1.12 version, and I'm guessing other people will be confused as well
