### ISSUE TITLE
[1.12.2] Crusher is extremely slow

### ISSUE THREAD

**Issue by NielsPilgaard** [BluSunrize/ImmersiveEngineering#4435]
### Description of the issue:
The crusher still shows it's animation, emits noise and drains power but it takes up to around 10 minutes to actually finish processing just one ore.

We have the config set to `crusher_timeModifier=0.1`, which used to make it very fast, but now it doesn't seem like changing the config has any effect.

### Versions & Modlist & Config
ImmersiveEngineering-0.12-98
https://gist.github.com/NillerMedDild/2249a7f6972638b24120e591dbb9a391
[immersiveengineering.cfg](https://gist.github.com/NillerMedDild/a5481792b42f84b24286e99300a8837c)

**Comment by mindforger** [comment]
by looking at the recipe system i see two things:

1st) the crusher does not seem to use the time modifier at all only an energy modifier
2nd) there seems to be something wrong in the calculation
>CrusherRecipe r = new CrusherRecipe(out, denseOre, (int)(recipe.getTotalProcessEnergy()/CrusherRecipe.energyModifier)*2);

isn't the modifier to be used as a product instead of an division?!

**Comment by malte0811** [comment]
1.12.2 is no longer supported.
