### ISSUE TITLE
Translation into Russian

### ISSUE THREAD

**Issue by GiovanniMIS** [BluSunrize/ImmersiveEngineering#4440]
Hi, I decided to translate the mod into Russian, as part of the mod is not translated. Below is the text that is not translated, and in parentheses is the translation of this text.

The name of the items
White Sheetmetal  (Белый листовой металл)
White Sheetmetal Slab  (Белай плита листового металла)
Orange Sheetmetal  (Оранжевый листовой металл)
Orange Sheetmetal Slab  (Оранжевая плита листового металла)
Magenta Sheetmetal  (Пурпурный листовой металл)
Magenta Sheetmetal Slab  (Пурпурная плита листового металла)
Light Blue Sheetmetal  (Голубой листовой металл)
Light Blue Sheetmetal Slab  (Голубая плита листового металла)
Yellow Sheetmetal  (Жёлтый листовой металл)
Yellow Sheetmetal Slab  (Желтая плита листового металла)
Lime Sheetmetal  (Лаймовый листовой металл)
Lime Sheetmetal Slab (Лаймовая плита листового металла)
Pink Sheetmetal  (Розовый листовой металл)
Pink Sheetmetal Slab (Розовая плита листового металла)
Gray Sheetmetal  (Серый листовой металл)
Gray Sheetmetal Slab (Серая плита листового металла)
Light Gray Sheetmetal  (Светло-серый листовой металл)
Light Gray Sheetmetal Slab (Светло-серая плита листового металла
Cyan Sheetmetal  (Бирюзовый листовой металл)
Cyan Sheetmetal Slab (Бирюзовая плита листового металла)
Purple Sheetmetal  (Фиолетовый листовой металл)
Purple Sheetmetal Slab (Фиолетовая плита листового металла)
Blue Sheetmetal  (Синий листовой металл)
Blue Sheetmetal Slab (Синяя плита листового металла)
Brown Sheetmetal  (Коричневый листовой металл)
Brown Sheetmetal Slab (Коричневая плита листового металла)
Green Sheetmetal  (Зелёный листовой металл)
Green Sheetmetal Slab (Зелёная плита листового металла)
Red Sheetmetal  (Красный листовой металл)
Red Sheetmetal Slab (Красная плита листового металла)
Black Sheetmetal  (Чёрный листовой металл)
Black Sheetmetal Slab (Чёрная плита листового металла)

immersiveengineering:chute_aluminum | Unnecessary S at the beginning of the name

Engineer's Screwdriver (Инженерная отвертка)
Windmill Sail (Парус ветряной мельницы)
Sawdust (Опилки)
Mineral Survey Tools (Инструменты для разведки полезных ископаемых)
Banner Pattern "Hammer"  (Узор флага "Молот")
Banner Pattern "Plating"  (Узор флага "Обшивка")
Banner Pattern "Ornate Frame"  (Узор флага "Украшенная рама")
Banner Pattern "Wooden Paneling"  (Узор флага "Деревянные панели")
Banner Pattern "Windmill"  (Узор флага "Ветреная мельница")
Banner Pattern "Wolf (right)"  (Узор флага "Волк (право)")
Banner Pattern "Wolf (left)"  (Узор флага "Волк (лево)")
Banner Pattern "Wolf"  (Узор флага "Волк")

**Further translation of the Engineer's Manual**

Introduction
Getting into Engineering
  Greeting, fellow engineer, and welcome to Immersive Engineering. This journal shall serve as your guide for setting up all the new machines and functions this mod has to offer. Let's start with the basics first: Immersive Engineering is build around the concept of retrofuturistic generation and tranfer of energy. The energy used is this mod is Forge Energy, a trait shared with many other mods currently available.
  Energy is transmitted between connectors by the use of wires. Wires can only bridge a limited distance of block, so you will need to use more connectors as **relays** between the wires.
  You have the choice between three different types of wire, which differ in transfer rates, 2048, 8192, 32768 Flux/tick. To switch between different types of wire, you will need to use **transformers**.

Вступление
Попадание в инженерное дело
  Приветствую вас, товарищ инженер, и добро пожаловать в иммерсивную инженерию. Этот журнал будет служить вам руководством по настройке всех новых машин и функций, которые может предложить этот мод. Давайте начнем с основ: иммерсивная инженерия строится вокруг концепции ретрофутуристической генерации и передачи энергии.
  Энергия, используемая в этом моде, - это энергия Forge, общая со многими другими модами, доступными в настоящее время.
Энергия передается между **коннекторами** с помощью **проводов**. **Провода** могут соединять только ограниченное расстояние блока, поэтому вам нужно будет использовать больше разъемов в качестве **реле** между проводами.
  У вас есть выбор между тремя различными типами проводов, которые отличаются скоростью передачи, 2048, 8192, 32768 Flux/tick. Чтобы переключаться между различными типами проводов, вам нужно будет использовать **трансформаторы**.

The Engineer's Hammer is the most important tool at your disposal. Is willing be used to form multiblock like the Coke Oven and Blast Furnace, crushing ores into dust or configuring blocks like Wooden Posts.

Инженерный молоток - самый важный инструмент в вашем распоряжении. Он готов к использованию для формирования мультиблоков, таких как Коксовая печь и Доменная печь, дробления руды в пыль или настройки блоков, таких как Деревянные столбы.

The Engineer's Screwdriver is another common item is your toolbox, which you'll need to do precise configuration on certain pieces of machinery.

Отвертка инженера-это еще один распространенный предмет вашего набора инструментов, который вам понадобится для точной настройки на отдельных частей оборудования.

Industrial Hemp is a remarkable plant! Not only are its seeds useful for the creation of _Biodiesel_, the hemp fibers are also used for the creation of Tough Fabric.
The sedds can be obtained by breaking tall grass.

Промышленная конопля-замечательное растение! Мало того, что его семена полезны для создания _Биодизеля_, волокна конопли также используются для создания Жесткой ткани.
Семена можно получить, ломая высокую траву.

Tough Fabric is a resilient weave made from hemp fiber. It's used to create **Improved Windmills** as well as **Balloons** and **Jump Cushions**.

Жесткая ткань-это эластичное плетение из конопляного волокна. Он используется для создания **Улучшенных ветряных** мельниц, а также **Воздушных шаров** и **Подушек для прыжков**.

Jump Cushions are simple blocks created from tough fabric and inflates with air. They are capable of absorbing impacts and prevent falldamage when landed upon, but, unlike slime blocks, will not bounce you back up.

Подушки для прыжков-это простые блоки, созданные из жесткой ткани и наполненные воздухом. Они способны поглощать колебания и предотвращать урон от падения, но в отличие от блоков слизи, не будут отталкивать вас обратно.

Strip Curtains are pieces of fabric that are mounted to doorframes or other openings to serve in blocking the view. When an entity passes through them, they will emit a redstone signal. Rightclick them with the hammer to enable strong signals.

Ленточные шторы - это куски ткани, которые крепятся к дверным косякам или другим отверстиям, чтобы служить для блокирования обзора. Когда сущность проходит через них, они испускают сигнал красного камня. Щелкните по ним ПКМ с помощью отвертки, чтобы переключить сигнал.

They can be dyed in the same way leather armor can.

Они могут быть окрашены так же, как и кожаные доспехи.

Ores
Diggy diggy hole

Руды
Diggy diggy hole 

**Copper Ore** is found in the world between layers 40 and 72 and requires a Stone Pickaxe to harvest.
The ore will smelt into copper ingots, which are used in crafting basic copper wires, coils, and other integral parts of the IE architecture.

**Медная руда** находится в мире между слоями 40 и 72 и требует каменной кирки для её сбора.
Руда будет выплавляться в медные слитки, которые используются для изготовления основных медных проводов, катушек и других неотъемлемых частей IE архитектуры.

**Bauxite Ore** is found in the world between layers 40 and 85, and requires a Stone Pickaxe to harvest.
The ore will smelt into aluminium ingots, which, together with steel, are used to create high-voltage wires.

**Бокситовая руд**а встречается в мире между слоями 40 и 85, и для ее добычи требуется Каменная Кирка.
Руда будет выплавляться в алюминиевые слитки, которые вместе со cталью используются для создания высоковольтных проводов.

**Lead Ore** is found in the world between layers 8 and 36, and requires an Iron Pickaxe to harvest.
The ore will smelt into lead ingots, which are used in creating capacitors.

**Свинцовая руда** находится в мире между слоями 8 и 36, и для ее добычи требуется Железная Кирка.
Руда будет выплавляться в свинцовые слитки, которые используются при создании конденсаторов.

**Silver Ore** is found in the world between layers 8 and 40, and requires an Iron Pickaxe to harvest.
the ore will smelt into silver ingots, which alloy with gold to create electrum, a far more effective conductor.

**Серебряная руда** находится в мире между слоями 8 и 40, и для ее добычи требуется Железная Кирка.
Руда будет плавиться в серебряные слитки, которые сплавляются с золотом, чтобы создать Электрум, гораздо более эффективный проводник.

**Nickel Ore** is found in the world between layers 8 and 24, and requires an Iron Pickaxe to harvest.
The ore will smelt into nickel ingots, which alloy with copper to create constantan, a heat resistant conductor used in the creation of _Thermoelectric Generators._

**Никелевая руда** находится в мире между слоями 8 и 24, и для ее добычи требуется Железная Кирка.
Руда будет выплавляться в слитки никеля, которые сплавляются с медью для создания константана, термостойкого проводника, используемого при создании Термоэлектрических генераторов.

**Uranium Ore** is found in the world between layers 8 and 24, and requires an Iron Pickaxe to harvest.
The ore will smelt into uranium ingots, but there are currently not many uses for the metal. A uranium block can serve as a heatsource for the _Thermoelectric Generator_ and the metal will be used in future andeavours.

**Урановая руда** находится в мире между слоями 8 и 24, и для ее добычи требуется Железная Кирка.
Руда будет плавиться в слитки урана, но в настоящее время существует не так много применений для этого материала. Урановый блок может служить источником тепла для _Термоэлектрического генератора_, и этот металл будет использоваться в будущем.

Mineral Deposits
Oresome

Месторождение Полезных Ископаемых
Oresome

The deposits of Ore found around your world are nothing new to you. What you have so far left out of consideration though are mineral veins, which contain a mix of different ores.
Due to their wide and thin spread, the average miner can't find them, but a _special machine_ might be able to assist with that.

Залежи руды, найденные вокруг вашего мира, не являются для вас чем-то новым. Однако то, что вы до сих пор оставили без внимания - это минеральные жилы, которые содержат смесь различных руд.
Из-за их широкого и тонкого распространения, среднестатистический Шахтер не может их найти, но _специальная машина_ может помочь в этом.

To begin looking for mineral veins, you'll want to craft some **Survey Tools**. By venturing out and using these tools on various blocks of natural soil, you can identify veins and find their approximate positions.

Each sample you take of the same vein gets you a more accurate read on what it contains and where it originates. Note that veins can overlap, so you may find traces of different veins quite close to each other.

Чтобы начать искать минеральные жилы, вам необходимо изготовить **Инструменты исследования**. Применяя и используя эти инструменты на различных блоках естественной почвы, вы можете идентифицировать жилы и найти их приблизительное положение.

Каждый образец, взятый из одной и той же жилы, дает вам более точное представление о том, что в ней содержится и откуда она берется. Обратите внимание, что жилы могут перекрываться, поэтому вы можете найти следы разных жил довольно близко друг к другу.

After narrowing down the type and position of the vein, use a Core Sample Drill to get a precise read on what veins are found at an exact position. 
Supply the machine with power and rightclick it or use redstone to active it. The drill consumes 40 Flux/t to then extract a core sample at its location which provides detailed information on the the mineral vein.

После уменьшения размера и положения жилы, используйте сверло для отбора образца, чтобы получить точное считывание того, какие жилы находятся в этом месте.
Обеспечьте машину питанием и щелкните на нее ПКМ или используйте Редстоун для ее активации. Сверло потребляет 40 Flux/t, чтобы затем извлечь образец в данном местоположении, который предоставляет подробную информацию о минеральной жиле.

The sample will not only tell you exactly what minerals are found there, including their relative presence, but also their individual saturation. A higher saturation means a higher chance for an excavator ti fill its bucket wheel.

Sneak + rightclick a core sample to place is in the world, allowing you to read its position and information.

Образец не только скажет вам точно, какие минералы там находятся, включая их относительное присутствие, но и их индивидуальную насыщенность. Более высокая насыщенность означает более высокий шанс для экскаватора заполнить свое хранилище.

Присесть + ПКМ разместит образец в верхнем мире, что позволяет вам видеть его положение и информацию.

Additionally, when placed, you can rightclick it with a map in order to mark its original position on there.

The following pages list every type of vein and the ores that can be retrieved from them.

Кроме того, при размещении вы можете щелкнуть на него ПКМ с помощью карты, чтобы отметить его исходное положение на ней.

На следующих страницах перечислены все типы жил и руд, которые могут быть извлечены из них.

Then only half of it is translated. I'll write untranslated words.

It состоит из (Need to clean everywhere "It")
Nether (Нижний мир)
Overworld (Верхний мир)
Archaic Digsite (Архаичные раскопки)

Metal Plates
Flat as a flounder

Металлическая пластина
Плоская как камбала

Metal Plates are a crafting material required for the creation of some machines or blocks. They are made by hammering an ingot with an Engineer's Hammer or in a _Metal Press_.

Металлические пластины-это крафтовый материал, необходимый для создания некоторых машин или блоков. Они изготавливаются путем обрабатывания слитка инженерным молотом или в _Металлическом прессе_.

Workbench & Blueprints
Always cluttered

Верстак и Чертежи
Всегда захламленный

The Engineer's Workbench is a professional worktable for the educated engineer. It is widely used to construct the item described is _Engineer's Blueprints_.
A wide variety of blueprints can be crafted, as detailed in the respective manual entry, whereas a few select ones can only be discovered in the world or purchased from villagers. To use a blueprint in the Workbench, put it in the slot on the left of the GUI and the necessary ingredients in the six slots in the middle. The resulting item can then be retrieved from the right side. Hovering your mouse over these output slots will inform you exactly which materials are needed for each item.

Верстак инженера-это профессиональный рабочий стол для продвинутого инженера. Он широко используется для построения изображенного элемента, они называются _Чертежи инженера_.
Большое разнообразие чертежей может быть создано, как описано в соответствующей записи, в то время как несколько избранных чертежей могут быть обнаружены только в мире или приобретены у жителей в деревни. Чтобы использовать чертеж на верстаке, поместите его в слот слева от графического интерфейса, а необходимые ингредиенты в шесть слотов посередине. Затем полученный элемент можно извлечь с правой стороны. Наведение указателя мыши на эти выходные слоты точно сообщит вам, какие материалы необходимы для каждого элемента.

A secondary function of the Workbench is the modification and configuration of more complex tools and gadgets. The _Mining Drill_, _Heavy Plated Shield_ or _Revolver_ ae examples of such item. When placed in the main slot of the workbench, it's use become that of modifying these tools by inserting applicable upgrades into the new slots that appear.

Вторичной функцией верстака является модификация и настройка более сложных инструментов и приспособлений. _Шахтерский бур_, _Тяжелый покрытый металлом щит_ или _Револьвер_-примеры таких предметов. При размещении в главном слоте верстака открывает панель модификации этих инструментов путем вставки соответствующих модификаций в нужные слоты.

**Comment by BluSunrize** [comment]
Please create a fork of the repo, adjust the lang file, and open a Pullrequest. That's the only correct way to contribute a translation.
