### ISSUE TITLE
[1.16.3] Diamonds Missing from Mineral Deposites

### ISSUE THREAD

**Issue by hotdog95** [BluSunrize/ImmersiveEngineering#4442]
### Description of the issue:
I am not sure if this is intended, I have tried searching for anything on this, anything related to this change to no luck. But I have noticed in the engineers manual that the coal mineral deposite does not contain diamonds anymore. Is this an intended feature, if so is there a plan on adding one? Is there a config option that has disabled diamond ore that I am unable to find?

There is no instance of diamond anywhere, and yet you are able to mine netherite, a far more rare resource

### Versions
Modpack: Valhelsia 3 - pre4-3.1.0

**Comment by BluSunrize** [comment]
Absolutely intended. IE has no diamond veins, because it has barely any need for diamonds.
