### ISSUE TITLE
[1.16.3] Generated config only contains debug options

### ISSUE THREAD

**Issue by Shandoo94** [BluSunrize/ImmersiveEngineering#4447]
### Description of the issue:
The newest version of IE for 1.16.3 generates a common.toml config file that only contains the debug options and no options for machines, ore gen etc.

### Versions & Modlist
Forge 34.1.40
IE 4.1.1-127

**Comment by BluSunrize** [comment]
All of these things are now configured on a per world basis.

Refer to this tweet for further information:

https://twitter.com/BluSunrize/status/1324466404276510722
