### ISSUE TITLE
Mekanism's tank is not treated as a "bucket" when completing the crafting of treated wood

### ISSUE THREAD

**Issue by Algester** [BluSunrize/ImmersiveEngineering#4449]
### Description of the issue:
mekanism's tank is not being treated as a returned empty bucket on making treated wood with Creosote Oil, I'll relay this info on Mekanism's git if someone thinks this is on mekanism's end

### Versions & Modlist
IE: 1.16.3-4.1.1-127
Forge: 34.1.42
Mekanism: 1.16.4-10.0.17.444

**Comment by BluSunrize** [comment]
As far as I can tell, Mekanism's tank items do not implement getContainerItem.

https://github.com/mekanism/Mekanism/blob/1.16.x/src/main/java/mekanism/common/item/block/machine/ItemBlockFluidTank.java

They should totally do that, and reduce their stored fluid by `BUCKET_VOLUME`. Report to Mekanism please.

**Comment by NielsPilgaard** [comment]
This issue was closed without a solution on the Mekanism issue tracker, could you perhaps have another look? 
Or perhaps block the Tank from Mekanism from being used at all for your fluid recipes? Having high tier tanks full of creosote voided isn't a great user experience :)

**Comment by BluSunrize** [comment]
Yeah, I'm aware that Mekanism has declared this not their problem. We'll fix this at some point, probably. Just use a bucket for now.

**Comment by NielsPilgaard** [comment]
Thank you! :)
