### ISSUE TITLE
Crusher stopped running, even when power is given, no redstone signal present.

### ISSUE THREAD

**Issue by darthvader45** [BluSunrize/ImmersiveEngineering#445]
I was running the crusher just normally, and tossed in several stacks of iron ore, as well as some stacks of galacticraft copper, tin and aluminum.  It processed the iron, copper and aluminum, but would just stop right away.  I put the stack back in, and it would try to process it, but stop a split second after.  Why did this happen?  No redstone signal was being inputted, nor was power being cut off.  Even breaking and replacing the entire machine didn't work, neither did relogging.  Wonder why.

**Comment by darthvader45** [comment]
Never mind, turns out the crusher doesn't process tin.  Tin should be added to the crusher's list of processable ores.  Don't see why tin can't be ground up.

**Comment by BluSunrize** [comment]
Tin /is/ processable. IE searches the OreDictionary for every ore that has a dust.

**Comment by darthvader45** [comment]
Weird, it wasn't processing for me.  I'll check the newest version.

On Mon, Sep 21, 2015 at 3:44 PM, BluSunrize <notifications@github.com>
wrote:

> Tin /is/ processable. IE searches the OreDictionary for every ore that has
> a dust.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BluSunrize/ImmersiveEngineering/issues/445#issuecomment-142088640>
> .
>



-- 
Golden rule in Minecraft: Never dig straight down.
