### ISSUE TITLE
[1.16.4] Crash when loading a shader

### ISSUE THREAD

**Issue by Reael** [BluSunrize/ImmersiveEngineering#4450]
### Before reporting:
I found [this](https://github.com/BluSunrize/ImmersiveEngineering/issues/4441) but it sounds like they couldn't run MC at all with Shaders AND Resourcepack. Which is really similar, but doesn't seem to be the same. Especially because it was for 1.16.3 and maybe you guys have changed something about it in 1.16.4

### Description of the issue:
I KNOW OptiFine is not officially supported and some issues can't be avoided but maybe there is a setting in OptiFine I can test or it's a known problem with an existing workaround so I'm trying it anyway, but I'm fine with this getting closed. It's not a game-breaking bug.
Basically what happens, when loading a Shader the game crashes giving an error about IE crashing during some phase (I forgot the wording but I got the log). When I restart the game the shader is active, though the resourcepacks got disabled as well which I can just enable again without problems. I have no problem switching from one shader to another and no problem changing resourcepacks. But once I disable any shader the game crashes again with the same message. So it only happens when no shader is enabled and a shader gets loaded in, or when a shader is active but gets disabled, switching Shaders once I restarted the game works fine.

### Crashlog:
https://pastebin.com/6k8QhXH7

### Versions & Modlist
Minecraft 1.16.4
forge-1.16.4-35.0.15-installer
ImmersiveEngineering-1.16.4-4.1.1-128
OptiFine_1.16.4_HD_U_G5
Singleplayer
Full Mod list https://docs.google.com/spreadsheets/d/1XMpJEEpEV_TKDJ-wIbp0olfUg2zuYUU8wD5-m9JnO10/edit?usp=sharing
I did not try to go through every mod manually just to see which one is the issue, I know it might be that another mod causes the issue and IE just happens to get stuck at it.

**Comment by 0xlsca** [comment]
`[21:58:41] [Render thread/WARN] [minecraft/ModelBakery]: Unable to bake model: 'immersiveengineering:steel_wallmount#facing=south,orientation=side_up,waterlogged=true': java.lang.ArrayIndexOutOfBoundsException: 6`
`[21:58:41] [Render thread/INFO] [STDERR/]: [net.minecraft.client.renderer.model.ModelBakery:lambda$uploadTextures$12:289]: java.lang.ArrayIndexOutOfBoundsException`

This seems to happen for every model.

**Comment by stromseng** [comment]
I am also having this same issue

**Comment by BluSunrize** [comment]
Optifine remains unsupported.
