### ISSUE TITLE
[Suggestion] Refill tools with jerrycan

### ISSUE THREAD

**Issue by Zahkriiven** [BluSunrize/ImmersiveEngineering#4456]
If i'm not mistaken the only way to refill the drill and buzzsaw is to right click some kind of fluid container like a barrel or a tank as if it was a bucket. I suggest that when having a jerrycan or the tool in the offhand you can refill them by right clicking into the air or something like that. I feel this gives more purpose to the jerrycan than to be a big bucket.

~ Zahkriiven

**Comment by BluSunrize** [comment]
Put a jerrycan in a crafting grid with the buzzsaw and see what happens.

**Comment by Zahkriiven** [comment]
Ok, my bad. I didn't remember that. In my defense i'd say holding both items at the same time looks good for refilling.
![image](https://user-images.githubusercontent.com/25531677/99886422-a69e8a80-2c3c-11eb-8839-053865374081.png)

Thanks anyway!

**Comment by Jonius7** [comment]
putting Jerrycan with Buzzjaw crafting recipe does not seem to be working in Valhesia 3 modpack.
