### ISSUE TITLE
[Feature Request] ComputerCraft Bundled cable support

### ISSUE THREAD

**Issue by MrDj200** [BluSunrize/ImmersiveEngineering#4458]
[ComputerCraft](https://github.com/SquidDev-CC/CC-Tweaked) has a bundled redstone API ([Some docs for that](https://tweaked.cc/module/redstone.html#v:setBundledOutput)) and since IE has the Redstone Interface Connector, I think it would be cool if those two could work together.

This is similar to #3005, but on Discord it was suggested I'd make a new request to get it marked to 1.16.

Love the mod, thanks for keeping us supplied with cool tech even in the new versions of Minecraft :)

**Comment by malte0811** [comment]
This should be quite easy to implement, see [here](https://github.com/SquidDev-CC/CC-Tweaked/blob/mc-1.15.x/src/main/java/dan200/computercraft/api/redstone/IBundledRedstoneProvider.java). I'll look into it when I have a bit of time.

**Comment by ArsiTheFox** [comment]
When will we expect a build with this implemented?

**Comment by malte0811** [comment]
It is already implemented in the [latest build](https://www.curseforge.com/minecraft/mc-mods/immersive-engineering/files/3141693), apparently I missed that commit when I wrote the changelog. I'm keeping this issue open as I still want to implement computers outputting to interface connectors, I didn't get around to that yet.

**Comment by mj-sakellaropoulos** [comment]
Can't get the read-only functionality working in the latest dw20 pack.

This code always returns 0 and true no matter the redstone states:
![image](https://user-images.githubusercontent.com/36081545/103318467-7c3eaa80-49fc-11eb-8e23-167f6457d334.png)
The interface connector is on the back of the computer:
![image](https://user-images.githubusercontent.com/36081545/103319032-5b775480-49fe-11eb-9180-ba76dafec1c6.png)

Mod versions:
cc-tweaked-1.16.4-1.94.0.jar
ImmersiveEngineering-1.16.4-4.1.2-129.jar (latest)

**Comment by ArsiTheFox** [comment]
Still unable to read input from colored redstone wire
Version: 1.16.4-4.1.2-129
![javaw-10-59-46 PM](https://user-images.githubusercontent.com/24835664/103331115-06513800-4a2a-11eb-816f-90f0898158f4.png)
![2020-12-29_22 59 33](https://user-images.githubusercontent.com/24835664/103331127-110bcd00-4a2a-11eb-984c-4de2f11ab2b0.png)

I tried everything but it always outputs 0

**Comment by ArsiTheFox** [comment]
colors.test is a fluke

**Comment by ArsiTheFox** [comment]
> Can't get the read-only functionality working in the latest dw20 pack.
> 
> This code always returns 0 and true no matter the redstone states:
> ![image](https://user-images.githubusercontent.com/36081545/103318467-7c3eaa80-49fc-11eb-8e23-167f6457d334.png)
> The interface connector is on the back of the computer:
> ![image](https://user-images.githubusercontent.com/36081545/103319032-5b775480-49fe-11eb-9180-ba76dafec1c6.png)
> 
> Mod versions:
> cc-tweaked-1.16.4-1.94.0.jar
> ImmersiveEngineering-1.16.4-4.1.2-129.jar (latest)

Yay, I'm not the only one!!

**Comment by malte0811** [comment]
`getBundledInput` was broken in my tests as well, but not just with IE wires. It also didn't work when placing two computers next to each other and having one of them emit a bundled signal. `testBundledInput` worked for me (both with wires and with two computers next to each other), and is probably what you'd want to use in most cases anyway.

**Comment by mj-sakellaropoulos** [comment]
Can confirm ```testBundledInput``` seems to be working, thanks!

**Comment by ArsiTheFox** [comment]
Why does getBundledInput not work though?

**Comment by mindforger** [comment]
> Why does getBundledInput not work though?

Wrong issue tracker to ask i guess :)
Try computercraft and crosslink this issue
