### ISSUE TITLE
Wrong IC2 API Usage

### ISSUE THREAD

**Issue by Speiger** [BluSunrize/ImmersiveEngineering#446]
https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/util/compat/IC2Helper.java#L39

Always check if the Machine says the truth!
If you simply assume the machines says: ok i need 50 EU per tick and simply say ok i give it to you,
then you do something wrong.
Always use the number that the function inject energy use...
No wonder why IE has problems with IC2...

Also IC2 needs no Simulating either A you do it yourself without simulating or B you simply add it to the Enet and let it do their thing... The enet is there for a reason...
Also a thing: IE does not support fake TileEntities. So things like the RC Turbine will never work with IE...
Fix that.

**Comment by BluSunrize** [comment]
You're joking, right?
You DO realize that I need a sort of simulation function because RedstoneFlux has simulation, right? Because in case you hadn't noticed, IE uses RF internally.

Also, the reason that my IC2 support is so shoddy, is because there is no tutorial at all on how to use IC2s API. Take that up with their devs.

Lastly: Never, EVER, end an issue report with "Fix that", you ungrateful, self-entitled, douchebag.

**Comment by Speiger** [comment]
First: My own Mod. Supports IC2 Power and RF Power... It also Converts it to a Main Power... So i do...
Second: No Documentation... Did you even open the API jar of IC2? In the Energy Folder is a file called: Usage. Which totally Explain you how the Enet works. And yeah i checkt it in the latest version too...
So its your own fault that you did not see it.... my first rule when i use an API which i want to support: read everything of that API (even if it is only the section which i support) but gather Information is important...
To the last part... xD If you want to call me like that fine, but then fix your stuff when someone tells you you are using something wrong...

**Comment by BluSunrize** [comment]
No. Because you don't tell me what to do. It's my mod and you have no right to tell me how to handle it. Doing so only marks you as another of the idiots over at reddit who are under the impression that developers are to obey the whims of the users.

**Comment by Speiger** [comment]
Well then Accept that people yell at you when IE does not work with EU properly and causes problem but do not throw the Issue at ic2 like you (or one of the other Devs) did before...

**Comment by BluSunrize** [comment]
I have never thrown any issue at IC2.

**Comment by Speiger** [comment]
ForgeCraft 2: Whenever used IE cables on it they wasted power... Even if that machine was full.
The Server after that server it was posted (the current one) prove that the problem did not lay at the IC2 side...

**Comment by BluSunrize** [comment]
I know that. I'm /on/ ForgeCraft. I discussed that issue with Soaryn personally. And I told him that IC2 support in IE is shoddy and tbf whenever I get the time and feel like it.

**Comment by Speiger** [comment]
Anyway simply let IC2 do the Enet Sending.
Simply Implement IEnergySink and IEnergySource to your Receiving/Sending part of the Energy Transport and return the functions it needs.
Also before a rotation you need to unregister it rotate it then and rerigsiter it. Has something todo with the path building...
There you have explaining.
