### ISSUE TITLE
Phantom Improved Blast Furnace Crashing glitch

### ISSUE THREAD

**Issue by Superc80** [BluSunrize/ImmersiveEngineering#4461]
The glitch happened when I made an improved blast furnace, it made the multiblock, but also spawned a phantom multiblock with one of the reinforced bricks of my improved blast furnace being the center of and being around that specific brick with no other blocks to it, I destroyed the improved blast furnace with ore excavate to try to fix it and have the phantom improved blast furnace disappear, when I did so the phantom improved blast furnace stayed and when I tried to hit the use button on it, it only did something on the block that it was formed around, which when inside the phantom improved blast furnace looked like a transparent fence block (I saw the block outline) and when I right clicked on it, it crashed me, I have tried left clicking as well and it crashes as well, in the oneprobe popup at the top of my screen it said that the block I was looking at was a reinforced blast bricks and it had 0 IE,
the immersive engineering jar is ImmersiveEngineering-0.12-98.jar
the Forge version is forge-14.23.5.2854
the url of the github gist page https://gist.github.com/Superc80/f65ed149178c77f4de6b13e569891608

**Comment by Superc80** [comment]
I hope that this follows the contribution guidelines, because I have no idea where the messages window is, please let me know if this broke any of them and please tell me where I can find them.

**Comment by BluSunrize** [comment]
1.12 is no longer supported
