### ISSUE TITLE
Copper ingot from nuggets recipe has a missing item tag.

### ISSUE THREAD

**Issue by Edulml** [BluSunrize/ImmersiveEngineering#4463]
### Description of the issue
In the copper ingot recipe, only 8 of the nuggets accepts any forge:nuggets/copper , the center one must be an Immersive 
Engineering copper nugget and it always creates Immersive Engineering copper ingots. It makes using JEI to craft copper ingots a bit uncomfortable since it may choose this recipe when I only have copper from another mod in my inventory (I'm using Create).

![image](https://user-images.githubusercontent.com/26638760/100383227-e4fcc680-2ffb-11eb-8268-6c62ddccffab.png)

### Versions & Modlist
Forge version 35.0.14
Immersive Engineering version 1.16.4-4.1.1-128

**Comment by TeamSpen210** [comment]
This is intentional, it's a convention several mods have adopted which allows you to pick which mod's ingot you get, or convert others to IE.

**Comment by Edulml** [comment]
Oh, good to know then.
