### ISSUE TITLE
[1.16.4] Graphic bug

### ISSUE THREAD

**Issue by Xenri** [BluSunrize/ImmersiveEngineering#4466]
There is a graphic bug that allows to see water streams underground if you stay in water
![2020-11-29_13 02 01](https://user-images.githubusercontent.com/75205931/100541283-1fa47000-3243-11eb-99de-ca8242600a91.png)

I tested it on 1.16.4 forge 35.0.0 with only this mod loaded

**Comment by malte0811** [comment]
Are you using Fabulous graphics? If you do, switching to them should have shown a warning telling you that you should disable stencil in the IE config.

Also: "with only this mod" is very vague. What version of "this mod"?

**Comment by BluSunrize** [comment]
Please provide a debug crash, as as requested in the issue template, which you *blatantly ignored*

**Comment by Xenri** [comment]
The Fabulous graphic was the problem.
And i didn't put the mod version in because there is only one version for 1.16.4 but i didn't think of next updates.
(I didn't put in crash log because i don't know how to do it)

**Comment by mindforger** [comment]
>(I didn't put in crash log because i don't know how to do it)

Hold F3+C while ingame until it crashes
