### ISSUE TITLE
[1.16.4] core sample bug

### ISSUE THREAD

**Issue by MasterSloth1** [BluSunrize/ImmersiveEngineering#4468]
forge -35.1.4
IE - 4.1.1-128
ImmersivePetroleum - 1.16.3-3.0.0
[message.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5617354/message.txt)
the file above is the nbt tag for the item i had to copy it from jei bookmarks.
i couldnt actually paste it into pastebin.com soo sorry you get the file :/

I placed the core sample drill at my house, it completed its processing, once i noticed the core stop rotating i right clicked it to receive the sample, then my game just lagged out to 1 fps looking around in my inventory i noticed the sample was invisible and it had a nbt tag soooo long im surprised i didnt crash

**Comment by malte0811** [comment]
I think I see what's going on... Are there generated chunks a long distance from you (over roughly 65k blocks)?

**Comment by malte0811** [comment]
Fixed in 62288c7. I've been able to reproduce this, so I'm quite sure my guess was correct (65k was the wrong number though).

**Comment by MasterSloth1** [comment]
sorry for the late reply yea we pre genned the server but thanks for the quick fix 😄
