### ISSUE TITLE
[1.16.4] Crash when opening Engineer's Manual

### ISSUE THREAD

**Issue by Jayx20** [BluSunrize/ImmersiveEngineering#4475]
Hi,
I consistently have my game immediately crash when I open the Engineer's Manual. I looked this issue up and found a lot of other issues, but they were all related to an old Java JRE version. I tried installing the latest version and setting my forge profile to launch it, but I still get the crash.
I get a log in the crash-reports folder, which I have uploaded here:
https://pastebin.com/gSS9JCdx

The mod version is 1.16.4 - 4.4.1. Forge version 35.1.7. I have a bunch of other random mods for a custom modpack.
This could be a duplicate issue or some known conflict but I couldn't find information about it. I tried removing OptiFine specifically but that still didn't fix the issue. I really just want to be able to open the manual so thanks for taking a look.

**Comment by BluSunrize** [comment]
Can you please provide your debug log file?

**Comment by Jayx20** [comment]
This has both crash log and debug.log:
https://gist.github.com/Jayx20/304c2db5fcdf4c76e1b1b45c4a2fe616

**Comment by Peca21** [comment]
I am getting the same crash on ImmersiveEngineering-1.16.4-4.1.2-129.

**Comment by mindforger** [comment]
@XxZajoZzO can you also provide a crashlog and logfile?

by the way i spot optifine in the first report, try if it happens without optifine

**Comment by Peca21** [comment]
Crash Report - https://pastebin.com/dPLFd3WU 
Full Log - https://www.dropbox.com/s/3e93yarsdhapapz/latest.log?dl=0

I dont have optifine

Edit:
java.lang.RuntimeException: Exception while refreshing manual entry immersivepetroleum:projector for manual Engineer's Manual
Caused by: java.lang.IllegalArgumentException: character to be escaped is missing
at java.lang.String.replaceFirst(String.java:2166)

**Comment by Peca21** [comment]
FOUND THE PROBLEM
replaceFirst in IEManualInstance throws exception when trying to print a keybind from projector.txt from immersive petroleum
Pressing §0§l<keybind;key.immersivepetroleum.projector.flip>§r will flip the structure, and sneaking while scrolling will rotate it.) 
if you have set BACKSLASH as a keybind.

**Comment by Peca21** [comment]
#4550
