### ISSUE TITLE
[1.8.9]Excavator Not Working

### ISSUE THREAD

**Issue by KmantheAWESOME** [BluSunrize/ImmersiveEngineering#4479]
Basically, I setup my excavator in a bauxite chunk. I needed aluminium. But so far from letting it run for quite a while, its only made 11 dirt. Im not sure what the problem is, The entire machine is in the chunk with bauxite ore deposits

Forge 1.8.9 11.15.1.2318
Fullbright 1.0 by nivyox
gravestone+mod+1.1.7
jei 1.8.9 2.28.18.187
moder-warfare-mod-1.8.9
optifine 1.8.9 hd u l5
Immersive engineering mod 1.8.9

**Comment by malte0811** [comment]
1.8.9 is no longer supported (and hasn't been since some time in 2016). Optifine also isn't supported, and "Immersive Engineering mod 1.8.9" as anything but a useful version specification.

**Comment by KmantheAWESOME** [comment]
Alright, I didnt think optifine would affect the excavator, and i looked at the file and all it said was "immersive engineering mod 1.8.9" i guess ill have to try and figure it out by myself for a while.

**Comment by BluSunrize** [comment]
No, it defintiely says more than that, because we have actual version numbers.
But as Malte said, we do not cater to a version that we last released **4 friggin years ago**.

Go update.
