### ISSUE TITLE
Increased Tile Render Distance No Effect

### ISSUE THREAD

**Issue by RustyJP** [BluSunrize/ImmersiveEngineering#448]
"Increased Tile Renderdistance" in the config seems to have no effect on the render range of Tile Entities such as Windmills. Tested with different number modifiers (1 - 10) and different server view distances (10-15) with no change

**Comment by mindforger** [comment]
i assume the calculation went up in smopke during the render conversion, i can not see any code referring to getMaxRenderDistanceSquared anymore

**Comment by BluSunrize** [comment]
was the config only changed on the server then? Because obviously, it only has effect on the clients.

**Comment by Poppycocks** [comment]
h-uh, configs? I came to ask about this, but I was about to simply suggest it being tied to render distance.
