### ISSUE TITLE
Unbreaking should not work on Drillheads and Sawblades

### ISSUE THREAD

**Issue by BluSunrize** [BluSunrize/ImmersiveEngineering#4480]
Title says it all. Fuck knows why Mojang allows applying that to *anything* in an anvil, but it's definitely not intended for IE, so we should look into preventing it.

**Comment by VariableVixen** [comment]
Out of curiosity: is it allowed for _anything_ or just for anything with durability?

**Comment by Algester** [comment]
ANYTHING... technically speaking you can even get an unbreaking stick
