### ISSUE TITLE
Can't change world generation in immersiveengineering-commom.toml

### ISSUE THREAD

**Issue by Edulml** [BluSunrize/ImmersiveEngineering#4485]
### Description of the issue:
I want to tweak ore generation, but the config file that changes it is in the serverconfig folder inside the world. Which means that to tweak it I must generate a world first, defeating the purpose of changing world generation, at least for the spawn area.

### Versions & Modlist
Forge version 35.1.7
Immersive engineering version 4.1.1-128

**Comment by BluSunrize** [comment]
Put that file in the folder `<instance>/defaultconfig`
