### ISSUE TITLE
[suggestion] filling the "upward conveyor into side conveyor missing block" 

### ISSUE THREAD

**Issue by Biviho** [BluSunrize/ImmersiveEngineering#4486]
This suggestion was made on 1.12.2, i don't know if on newer version is already a feature, but in both cases, i hope it could be backported or backported after been developed if you are interested.

So, currently, if someone want to make an upward covered conveyor belt that feed into a side conveyor, will find itself with an ugly missing piece between the two.

what i suggest is to add the ability for chute to open not only for conveyor directed into it, but for conveyor directed out from it, and if possibe, to add also a curved version of it that go from an upward conveyor to a side conveyor when placed above an upward conveyor.

some images:

(**The ugly**)

![2020-12-07_00 24 38](https://user-images.githubusercontent.com/57569917/101296618-a8fc0980-3824-11eb-8fca-d64bc68b31ea.png)

(**The ugly brother that is a bit better but still ugly**)

![2020-12-07_00 26 17](https://user-images.githubusercontent.com/57569917/101296713-38092180-3825-11eb-9cb7-ed7c5d0e0a0b.png)

(**The solution** imagine the conveyor going outward)

![2020-12-07_00 25 27](https://user-images.githubusercontent.com/57569917/101296734-5ec75800-3825-11eb-8b31-65b502677c32.png)

(**The even better solution** going from down to the side (rotated))

![2020-12-07_00 25 05](https://user-images.githubusercontent.com/57569917/101296764-91715080-3825-11eb-8373-791ca2816c69.png)

**Comment by BluSunrize** [comment]
The solution was actively denied last time.
Also we are not doing any backport. 1.12 is dead.
