### ISSUE TITLE
[Suggestion] Sawmill - Comparator Output

### ISSUE THREAD

**Issue by Algester** [BluSunrize/ImmersiveEngineering#4487]
Have the a redstone comparator integration that would "shutdown" the machine so that the player can have the option either to automate the sawmill crafting and insertion should the sawmill run out of durability to avoid the stripped log spillage.

**Comment by mindforger** [comment]
couldn't you change the redstone behaviour by right clicking the redsone receiver(-block) with the hammer? or did i mix up this with another mod?

**Comment by BluSunrize** [comment]
No, the point here is that the sawmill currently doesn't output a signal based on saw integrity. That's the actual requested feature. The explanation was just bad.

Once that actual comparator functionality is in, turning it off based on that is super easy.

**Comment by mindforger** [comment]
oh ah sorry i goofed, i misread the question :P
