### ISSUE TITLE
Chemical Thrower doesn't create fire

### ISSUE THREAD

**Issue by BOTZachary** [BluSunrize/ImmersiveEngineering#4488]
I've been testing out the chemical thrower with several of the flammable fluids and it does not light blocks on fire, and I can find zero information online about if it even is supposed to. I would assume that it would create fire but it doesn't. Is there something I'm missing in configs or something or does it just not set blocks on fire?

**Comment by BluSunrize** [comment]
That's on purpose. Large fires are real bad for server performance, and I'd rather people not accidentally burn their house down.
