### ISSUE TITLE
[1.16] Storage Crate won't open when OptiForge installed

### ISSUE THREAD

**Issue by bcrotty** [BluSunrize/ImmersiveEngineering#4489]
### Description of the issue:
Right clicking on a Storage Crate does nothing when OptiForge is installed as well. I'm using the pack Valhelsia 3 and added OptiForge. Removing OptiForge makes the Storage Crate behave normally again.

I'll crosspost this bug for Valhelsia.

### Versions & Modlist
ImmersiveEngineering-1.16.4-4.1.1-128
Forge 35.1.4
Minecraft 1.16.4
Valhelsia 3 - pre7-3.1.0
[Full Mod List](https://pastebin.com/ypAk40YC)

**Comment by BluSunrize** [comment]
Optifine and Optiforge are not supported.
