### ISSUE TITLE
[Suggestion] Wooden Post Climb/Extension

### ISSUE THREAD

**Issue by RustyJP** [BluSunrize/ImmersiveEngineering#449]
This is a small thing, but the ability to extend wooden posts in height and/or the ability to climb up multiple wooden posts would be convenient . At the moment you can climb up a singular post but then are blocked, by the stone base of the second post, from climbing further up (if two or more posts are stacked)

**Comment by XFactHD** [comment]
ImmersiveIntegration has wooden post extensions, but you won't be able to climb them until @BluSunrize decides to keep this feature (That's what @UnwrittenFun said in an issue on his tracker).

**Comment by RustyJP** [comment]
Ah okay, will just have to wait and see then!

**Comment by UnwrittenFun** [comment]
You can as of 0.5.0 (or around then) https://github.com/UnwrittenFun/ImmersiveIntegration/commit/0a5eb990b1f7eb2c5618c475c05758478aa5ff43

**Comment by XFactHD** [comment]
Ah, ok, didn't know that.

**Comment by BluSunrize** [comment]
Yeah, and stacking wooden posts without the extension looks really stupid, so eh, won't fix.
