### ISSUE TITLE
[1.16.4] Standing on IE models crash

### ISSUE THREAD

**Issue by MatthewNeri** [BluSunrize/ImmersiveEngineering#4490]
IE version 4.1.1-128
Forge version 35.1.4
Connected to dedicated server
Standing on certain IE blocks (mainly ones with custom models) the game will crash with a null pointer exception (see attached crash log).
currently only tested with engineers table and charger, happens to everybody on the server so its not my game (could be a mod incompatibility though)
[crash-2020-12-09_22.06.24-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5670069/crash-2020-12-09_22.06.24-client.txt)

**Comment by BluSunrize** [comment]
Remove Baritone
