### ISSUE TITLE
[1.16.4] Crash tracing to MineralVein.writeToNBT

### ISSUE THREAD

**Issue by kkjdroid** [BluSunrize/ImmersiveEngineering#4500]
### Description of the issue:
Periodic crashes for no apparent reason

### Crashlog:
https://pastebin.com/pfAx45V0

### Versions & Modlist
Mods: All The Mods 6 v1.3.3
Forge: 1.16.4-35.0.18
IE: 1.16.4-4.1.1-128

This seems to be the same problem as #4067, but that issue was supposedly fixed.

**Comment by BluSunrize** [comment]
Update IE to its new version, that issue has been fixed.
