### ISSUE TITLE
[1.16.4] ATM6 issue with forming the squeezer

### ISSUE THREAD

**Issue by rynarok** [BluSunrize/ImmersiveEngineering#4502]
### Description of the issue:
As the title states,Industrial Squeezer will not form no matter what. Tried in both inverse and non-inverse format, but will not form after hitting middle barrel with hammer images here : https://imgur.com/a/myKa1V5
### Versions & Modlist
Not sure but its the one most updated for ATM6
If your game crashed (see above) you may omit the modlist, but IE and Forge version would still be nice.

Also, please try testing an issue in a minimal instance, with just IE, Forge and maybe JEI. That makes elminating compat issues easier.

### Lastly (you may delete this from the report itself)
Please, for the love of all that is voxelbased, **read the contribution guidelines. They are linked to the right in the message box.**
When reporting issues, these are crucial, and the team withholds the right to close an issue for the plain stupidity of not reading and adhering to them.

Thank you for reporting issues, without people reporting them, they wouldn't get fixed. You're helping contribute to this mod and that is much appreciated <3

**Comment by BluSunrize** [comment]
Please make sure that you are clicking the barrel between the light and redstone engineering blocks:

![squeezer](https://i.imgur.com/YjSNT3Z.png)

Also it needs to be a normal piston, not a sticky one.

**Comment by fblaese** [comment]
We have had the same issue. After some experimenting we realized that steel fence items are merged by some other mod, so crafting steel fences always results in items from another mod. These don't seem work when building multiblock structures.

**Comment by EPostill** [comment]
we are also having the same issue, although we do not have any other mods with steel fences. This is the only multiblock so far that has not worked. we are also using the projector to be sure.

**Comment by BluSunrize** [comment]
Using the projector does not guarantee anything. We don't make the projector. Rely on the manual for accuracy.

**Comment by BluSunrize** [comment]
Also, closing this due to lack of feedback from the original poster

**Comment by Gasteria1** [comment]
I am having same issue but my steel fence is of immersive engineering? What was the fix, nobody came to talk about a fix

**Comment by MatheusPese** [comment]
This should not have been closed, it was closed because the #4809 was using normal barrels, but this is using the correct barrels, making it not the same issue.

**Comment by MatheusPese** [comment]
I am having the same issue.
