### ISSUE TITLE
[1.16.4] Valhelsia 3 pre7-3.1.0  Crusher is not crushing ores

### ISSUE THREAD

**Issue by Fusselz** [BluSunrize/ImmersiveEngineering#4504]
Description of the issue:
Hey guys, I just foun the issue of the crusher not crushing any type of ore, however it does crush Ingots and other Items not related to being an ore. 

1.16.4
Valhelsia 3 pre7-3.1.0
ImmersiveEngineering-1.16.4-4.1.1-128

**Comment by BluSunrize** [comment]
This is an incomplete issue report. We require a modlist, most easily delivered by you as a debug crash.

Also, please check JEI to see if the recipes for crushing ore are actually there.

**Comment by Fusselz** [comment]
I´m sorry. 

There is a list of all installed modpacks: https://pastebin.com/xNj2c3Sm
There is a recipe for the crusher, only with ingot -> Dust. However there is a recipe for the Mekanism Enrichment Chamber for turning ores into Dust.

**Comment by BluSunrize** [comment]
Sounds like the recipes didn't load then.
Raise this to the Valhesia devs. Sounds like Datapack loading got broken. If I had to make a guess from the modlist, it's due to KubeJS. That mod has previously broken recipe loading.

This is not an IE issue, as far as I can tell.
