### ISSUE TITLE
[1.16.4] Powered lantern does not work with Optifine

### ISSUE THREAD

**Issue by fantaser0** [BluSunrize/ImmersiveEngineering#4510]
I found a problem with the work of IE and Optifine, powered lantern with Optifine installed does not illuminate the territory, but all other light sources from IE work as it should.
With Optifine
![2020-12-19_16 22 01](https://user-images.githubusercontent.com/76245288/102686340-94067980-4219-11eb-8235-0f9c09b9b72f.png)
Without Optifine
![2020-12-19_16 29 55](https://user-images.githubusercontent.com/76245288/102686351-aa143a00-4219-11eb-98b9-5c54b8e8d316.png)

**Comment by BluSunrize** [comment]
Yep. That's why optifine is not supported, which you'd know if you read the contribution guidelines.
