### ISSUE TITLE
Add a clarifying statement about world configs to the common config

### ISSUE THREAD

**Issue by BluSunrize** [BluSunrize/ImmersiveEngineering#4511]
Because people just don't get it, and Forge doesn't explain it. So I guess we have to.

Inside out common config, we should have a really big comment block that explains (nicely) that machines & ores are now configured on a per world basis. We should instruct people where in their world saves they can find this (including a mention of how it works on servers) and we should explain the `defaultconfigs` folder.

That should hopefully cut down on being asked about it every week on discord.

**Comment by Pentasis** [comment]
Having to change certain config-values for each world is rather tedious, esp. when doing lots of testing and creating lots of test-worlds. E.g. ore spawning. Is there a way to disable/change ore spawning before the world generates? Seems odd to have ores generate around spawn only to remove them again.
Perhaps some options should/could have a global default in the common config?

**Comment by BluSunrize** [comment]
No, they are per world on purpose and that is exactly what the `defaultconfigs` folder is for. This isn't a suggestion, it's a ToDo/Reminder.

**Comment by Pentasis** [comment]
Ah, TIL there is a defaultconfigs folder. Thank you.
