### ISSUE TITLE
Crash when loading world after updating IE to 1.16.4-4.1.2-129

### ISSUE THREAD

**Issue by Limewood** [BluSunrize/ImmersiveEngineering#4512]
### Description of the issue:
The client crashes on loading the world (looks like a specific chunk, since the game loads the nearest ca 5 blocks in the view direction before it crashes.

### Crashlog:
https://pastebin.com/7BdTCidh

### Versions & Modlist
IE 1.16.4-4.1.2-129
Forge 35.1.4

Tested with new world using the same mods, adding a diesel generator with HV connectors on it, connected with HV wire to an HV relay on a post, as well as some other connections, such as passthrough connectors and insulated MV connections.
This produced no issues. Downgrading to the IE and IP versions just before allowed the affected world to load again.

**Comment by someaddons** [comment]
https://gist.github.com/someaddons/b4bba7772fc46587a7838f7aa690e3a9 same issue for me

**Comment by malte0811** [comment]
I have no idea why this would start happening *now*, I managed to reproduce the crash yesterday, but did not see any recent changes to the relevant code.

As a temporary fix you can fully disable "smooth lighting", break the problematic posts and enable it again afterwards. A proper fix will probably require a lot of changes to the post code: Posts assume that when a bounding box is requested, they can look at neighboring blocks. AO/smooth lighting assumes that it can ask for bounding boxes of neighbors of the blocks it is rendering. So in total we would like to see 2 blocks beyond the rendered blocks. `ChunkRenderCache`s only save one block beyond the rendered area, causing the crash.

**Comment by DrakenXI** [comment]
Same issue: https://pastebin.com/BCEfgvAw

**Comment by Thadoy** [comment]
Same issue in All the Mods 6 https://pastebin.com/Mkc8nbRF

The block in question is a garden cloche with supremium farmland as soil an dirt seeds, both from Mystical Agriculture.

**Comment by boneskull** [comment]
I can confirm the workaround--disable smooth lighting--works to avoid the crash.
