### ISSUE TITLE
[1.16] No crash, all multiblocks and posts not working correctly

### ISSUE THREAD

**Issue by horse9** [BluSunrize/ImmersiveEngineering#4513]
Just updated everything before downloading the newest IE version (from 3 days ago, 1.16). IE is the only mod. I’m not new to IE, but this laptop is- shouldn’t be relevant.

-No multiblocks work, in the sense that the hammer does not interact with anything in them to activate them (except for, say, rotating a piston or changing an input to output on a barrel, etc). But the red highlighted activation spot does not provide any interaction with the hammer, sneak clicking or not, for any multiblock. I made sure that I had only the correct types and quantity of blocks as per the checklist in the EM in my inventory, and nothing else to avoid unlikely confusion. I even rebuilt all of them in the specific order each block was laid, and avoided doing anything else before attempting activation. There is no angle that works. While picking my brain, I tried hammering every block and all that, before rebuilding and trying again. I’ve followed two different tutorial videos block-per-block, and everything works in them, but not the activation step for me. The hammer doesn’t have any interaction with it. 

-Everything attached to posts just “floats” next to it (no supporting arms appear for relays/lamps, etc). Not a huge issue, they function fine- but maybe an indicator of one?

-again, no crashes, everything else including minerals/ores, workbenches, Simple machines, wiring and red stone seems to work flawlessly. Villagers and inventories updated flawlessly. Multiblocks just stay as a pile of blocks and everything attached to posts just floats.

**Comment by BluSunrize** [comment]
Please provide screenshots of the multiblocks you were trying to build, as well as the modlist. You should really have followed the issue template, instead of ignoring it.

**Comment by horse9** [comment]
I stated there is one mod active, IE 1.16 is the only mod. 

The lack of screenshots standalone does not indicate a total ignorance of the template. Why was “if available” included in the rhetoric? 

I’ll seek help elsewhere. I apologize for completely ignoring everything.
