### ISSUE TITLE
[1.14.4] Problem with IE ores generation

### ISSUE THREAD

**Issue by exe93-dev** [BluSunrize/ImmersiveEngineering#4514]
Hello,
After installation of the Immersive Engineering mod, for a long time I could not find any ores from Immersive Engineering such as copper, lead, uranium, silver etc.
To check if the ores were generated I installed Advanced XRay mod. The first deposit was found around 2000 blocks from my house.
They probably appeared on an undiscovered chunks.
What can I do to make the ores appear on the discovered chunks?
This causes a problem because my excavator will not find any deposits near the house.

**Modlist:**
Forge 28.2.23
IE 1.14.4-3.1-107
Refined Storage 1.7.3
Waila
Waila Harvestability 1.1.12
JEI 6.0.0.18

**Comment by BluSunrize** [comment]
if you installed IE into a world that already existed, that's just what happens.

You can use the retrogen options in the config to generate ores in chunks you have previously visited. See the config's comments for details.

As for the excavator, it does not have retrogen. Sorry about that, nothing to be done there.
