### ISSUE TITLE
Crash on use of Engineer's Hammer with multiblockInterdiction tag

### ISSUE THREAD

**Issue by KevinHuang8** [BluSunrize/ImmersiveEngineering#4515]
### Description of the issue:
When right clicking with an Engineer's hammer with the NBT tag `multiblockInterdiction` with a value of `["IE:Crusher"]` (specifically, given by the command `/give @p immersiveengineering:hammer{multiblockInterdiction:["IE:Crusher"]}` ), the game crashes. I might've gotten the tag usage wrong, but the syntax seems right to me.

### Crashlog:
https://gist.github.com/KevinHuang8/5f65cc460e5091985ef7510e9a9580dc

### Versions & Modlist
IE 1.16.4-4.1.1-128
Forge 35.1.4

**Comment by SkySom** [comment]
That would be because you set invalid data on the item. Machine names are Resource locations which are all lower case. (Make sure you have valid names)

**Comment by SkySom** [comment]
If you're looking for the crusher I believe the string you want is 'immersiveengineering:multiblock/crusher'

**Comment by KevinHuang8** [comment]
In 1.12, I thought the string to pass to `multiblockInterdiction` was the one returned by `getUniqueName` for `MultiblockCrusher`, which is still `"IE:Crusher"`. Indeed, if you have the NBT tag `{multiblockInterdiction:["IE:Crusher"]`, the tooltip for the hammer correctly states that it should forbid the crusher, suggesting "IE:Crusher" is the right tag. Not sure what else to pass in ("immersiveengineering:multiblock/crusher" does not work, and the tooltip doesn't have proper localization).

Is the problem that `getUniqueName` no longer returns a valid resource location?

**Comment by KevinHuang8** [comment]
Ah, nevermind, I was looking at the wrong branch lol no wonder. 

The location was "immersiveengineering:multiblocks/crusher"

**Comment by malte0811** [comment]
I'll reopen this, IMO setting wrong data there should not cause crashes. It should either do nothing at all or notify the player in chat that the NBT data is wrong.
