### ISSUE TITLE
Weird Â characters around bold words on Mineral Deposit pages.

### ISSUE THREAD

**Issue by Moleculor** [BluSunrize/ImmersiveEngineering#4517]
### Description of the issue:
![image](https://user-images.githubusercontent.com/3865976/102794699-5b79b380-4371-11eb-86cc-6818d2c913b9.png)
![image](https://user-images.githubusercontent.com/3865976/102794763-72b8a100-4371-11eb-8eeb-4ed3d9fa0fd2.png)

It's on every bolded name within *just* the Mineral Deposits. I can't find it on other pages, but I haven't done an exhaustive search. So, to clarify, it seems like other bolded words are 'fine'. 

![image](https://user-images.githubusercontent.com/3865976/102794864-97147d80-4371-11eb-897d-2d08d8a032ee.png)

My first (possibly bad) guess is that it's related to the green text in the same section, perhaps?

![image](https://user-images.githubusercontent.com/3865976/102795635-b1029000-4372-11eb-847c-ecf39839fb99.png)

### Versions & Modlist

Hey! I figured out how to generate a crash report!

```Mod List: 
		forge-1.16.4-35.1.13-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.13-universal.jar                |Forge                         |forge                         |35.1.13             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		ImmersiveEngineering-1.16.4-4.1.2-129.jar         |Immersive Engineering         |immersiveengineering          |1.16.4-4.1.2-129    |DONE      |44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		jei-1.16.4-7.6.0.62.jar                           |Just Enough Items             |jei                           |7.6.0.62            |DONE      |NOSIGNATURE```

**Comment by Moleculor** [comment]
Maybe this is related, maybe I should open a new issue for this, but in a pack running those mods plus others (haven't confirmed it with the limited number of mods) I also have this:

![image](https://user-images.githubusercontent.com/3865976/102886035-f9c15400-4419-11eb-8062-3020cc58edf4.png)
![image](https://user-images.githubusercontent.com/3865976/102886064-09409d00-441a-11eb-9265-687f022c3a34.png)

**Comment by ocram9** [comment]
Same for the "hold shift" when hovering over blueprints. Tested this in a new world with just JEI and immersive engineering installed.

![Screenshot_13](https://user-images.githubusercontent.com/49008532/103182808-881c5680-48ae-11eb-8d3c-9da55ca1ca9e.png)
