### ISSUE TITLE
15.2 CTD when placing blueprint on engineers workbench

### ISSUE THREAD

**Issue by ticviking** [BluSunrize/ImmersiveEngineering#4519]
### Description of the issue:
CTD when placing a blueprint on Engineers Workbench. 

### Crashlog:
[gist](https://gist.github.com/ticviking/e5ffb589a2c7af3318c6c96aa319b085) 

### Versions & Modlist
	Mod List: 
		forge-1.15.2-31.2.47-client.jar Minecraft {minecraft@1.15.2 DONE}
		MouseTweaks-2.13-mc1.15.1.jar Mouse Tweaks {mousetweaks@2.13 DONE}
		ImmersiveEngineering-1.15.2-4.1.1-125.jar Immersive Engineering {immersiveengineering@1.15.2-4.1.1-125 DONE}
		Morpheus-1.15.2-4.2.50.jar Morpheus {morpheus@version DONE}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version DONE}
		jei-1.15.2-6.0.3.15.jar Just Enough Items {jei@6.0.3.15 DONE}
		traverse-1.15.2-3.2.0.jar Traverse {traverse@1.15.2-3.2.0 DONE}
		Mekanism-1.15.2-9.10.9.422.jar Mekanism {mekanism@9.10.9 DONE}
		forge-1.15.2-31.2.47-universal.jar Forge {forge@31.2.47 DONE}
		mysticallib-1.15.2-2.0.1.jar Mystical Lib {mysticallib@1.15.2-2.0.1 DONE}
		curios-FORGE-1.15.2-2.0.2.6.jar Curios API {curios@FORGE-1.15.2-2.0.2.6 DONE}
		Botania-r1.15-388.jar Botania {botania@r1.15-388 DONE}
		Patchouli-1.15.2-1.2-35.jar Patchouli {patchouli@1.15.2-1.2-35 DONE}
		journeymap-1.15.2-5.7.0b3.jar Journeymap {journeymap@5.7.0b3 DONE}
		StorageDrawers-1.15.2-7.0.3.jar Storage Drawers {storagedrawers@1.15.2-7.0.3 DONE}

**Comment by BluSunrize** [comment]
Sorry, 1.15.2 is no longer receiving any updates.
