### ISSUE TITLE
[1.16.4] Server crashed after approaching my base with diesel generator

### ISSUE THREAD

**Issue by Siknas** [BluSunrize/ImmersiveEngineering#4521]
### Description of the issue:
After crafting a diesel generator, my server would crash from time to time as I approached the chunks that housed the generator. After deconstructing it, the issue went away.

### Crashlog:
https://pastebin.com/mQYQb1BL

### Versions & Modlist
Forge 35.1.13
Immersive Engineering 1.16.4-4.1.2-129
Valhelsia 3 3.1.1 Modpack (See crashlog for list)

**Comment by DrZindy** [comment]
I'm having the same issue, with a near-identical crashlog: https://pastebin.com/2i2RNTbN
I'm on a different modpack, though we have a few mods in common that might elucidate the issue

**Comment by malte0811** [comment]
@Siknas: Since you apparently managed to break the generator and are able to use the world again, can you get me a screenshot of the (deconstructed) generator with chunk borders (F3+G) enabled?

**Comment by Siknas** [comment]
@malte0811 First, I need to apologize. I mistakenly said this was on ImmersiveEngineering-1.16.4-4.1.2-129. It was actually on ImmersiveEngineering-1.16.4-4.1.1-128. I'd forgotten that Valhelsia had updated from 3.1.0 to 3.1.1 overnight.

Secondly, unfortunately I took apart the machinery for use in other projects. However, I was able to recreate the exact location and general shape out of planks so that you could see the Diesel Generator in relation to pipes, chunk borders, other machinery etc, Imagine the birch planks are the generator. The tank behind it is about half full with biodiesel with its output line plugged into the generator's right input. Chunks should be visible in game as well as on the Xaero's minimap on the top right.

https://imgur.com/a/4nJGomG

I hope this still helps.

**Comment by malte0811** [comment]
I should have checked the report for the version… Both of the reports in this issue are on build 128. In 128 there was an issue that would cause this crash when flying around with a voltmeter (more specifically being in empty chunk sections with a voltmeter). That part was fixed in 129. If this crash in general is still an issue on 129 I would like to have a crashlog from that version.

**Comment by BluSunrize** [comment]
Closing this, due to lack of responses with an updated version
