### ISSUE TITLE
[Issue/Problem] [1.16] Multiplayer Crash when using the Immersive Engineering Tools (Buzzsaw, Drill, Chemical Thrower, etc.)

### ISSUE THREAD

**Issue by Hidekiranier** [BluSunrize/ImmersiveEngineering#4522]
Hi BluSunrize,

when i use a Drill or a Buzzsaw on a Multiplayer Server the people around me get kicked off the server/crash the game. It only occurs on other people, but not for myself.
We tested out different reasons for the crashes and found out that the game always crashes when using any of the Immersive Engineering Tools. It does not occur when using the regular tools(Engineer's Hammer, Steel Tools, etc.)

Minecraft Version: 1.16.4

Forge Version: 35.1.5

Modlist:

AI-Improvements-1.16.2-0.3.0

AppleSkin-mc1.16.2-forge-1.0.14

BetterCaves-1.16.3-1.0.6

BetterMineshafts-Forge-1.16.3-1.1

chiselsandbits-0.2.8-RELEASE

Clay WorldGen-1.16.4-1.2.0

Clumps-6.0.0.13

Controlling-7.0.0.11

create-mc1.16.3_v0.3a

FastFurnace-1.16.3-4.3.0

FastWorkbench-1.16.3-4.4.1

ftb-backups-2.1.1.6

Hwyla-forge-1.10.11-B78_1.16.2

ImmersiveEngineering-1.16.4-4.1.2-129

ImmersivePetroleum-1.16.4-3.1.0-2

jei-1.16.4-7.6.0.62

mightyarchitect-mc1.16.3_v0.5

MouseTweaks-2.13-mc1.16.2

NetherPortalFix_1.16.3-7.2.1

Placebo-1.16.3-4.3.3

ReAuth-1.16-Forge-3.9.3

StorageDrawers-1.16.3-8.2.1

TerraForged-1.16.4-0.2.0-ALPHA-3

XaerosWorldMap_1.11.4_Forge_1.16.4

**Comment by BluSunrize** [comment]
Provide crashlogs

**Comment by Polsaker** [comment]
Same thing's been happening to me. This is the D/C message (no stack trace appears on the log)

```
[01.01 22:09:10] [Server] [Netty Epoll Server IO #24/ERROR] [minecraft/NettyPacketEncoder]: java.lang.IllegalStateException: LazyOptional is empty or otherwise returned null from getValue() unexpectedly
[01.01 22:09:10] [Disconnect] Polsaker has disconnected, reasonInternal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalStateException: LazyOptional is empty or otherwise returned null from getValue() unexpectedly
[01.01 22:09:10] [Server] [Server thread/INFO] [minecraft/DedicatedServer]: Polsaker left the game
```

(this happened when somebody else started using the drill)

**Comment by BluSunrize** [comment]
Closing this in favor of the (slightly) better reported #4547
