### ISSUE TITLE
[1.16] Crude Blast Furnace flame not going out when cooking

### ISSUE THREAD

**Issue by darthvader45** [BluSunrize/ImmersiveEngineering#4523]
### Description of the issue:
When I put iron in as well as coal coke and close the gui, the iron cooks as normal into steel, but when I come back the flame in the GUI is still lit as if cooking something/fuel still being used.  I tested with 1 iron ingot and 1 coal coke (which should leave no flame in the GUI after it's done, as it's an even 1:1 ratio).

### Versions & Modlist
Forge 1.16.4 - 35.1.13
ImmersiveEngineering-1.16.4-4.1.1-128

**Comment by malte0811** [comment]
No clue why GH did not close this… Fixed in 1394ac9a15c40f2ad51864a31879cbea7728310f, close to 6 months ago.
