### ISSUE TITLE
[1.16.4] Planting industrial hemp doesn't make A seedy place advancement

### ISSUE THREAD

**Issue by Rafii2198** [BluSunrize/ImmersiveEngineering#4525]
### Description of the issue:
The title describes it clearly.
Planting any seed-based crop from vanilla (i.e wheat, pumpkin, etc.) would award this Advancement but immersive's Industrial Hemp doesn't do that but it should as it is a seed-based.

### Versions & Modlist
Minecraft: 1.16.4
Modpack: FTB Direwolf20 1.16
IE version: 1.16.4-4.1.2-129

**Comment by BluSunrize** [comment]
Vanilla has that condition hardcoded.
