### ISSUE TITLE
SheetMetalTank Tileentities taking excessive tick time.

### ISSUE THREAD

**Issue by Raycoms** [BluSunrize/ImmersiveEngineering#4526]
### Description of the issue:

We've noticed that the SheetMetalTanks were taking up over 5% of the total server tick time.

![image](https://user-images.githubusercontent.com/6438347/103035150-9856cd80-455e-11eb-8794-0423427612ca.png)

### Versions & Modlist

IE: 1.16.4-4.1.2-129
Forge: 35.1.13
Minecraft: 1.16.4

Modpack:
https://www.curseforge.com/minecraft/modpacks/minecolonies-testpack

**Comment by malte0811** [comment]
I would strongly prefer to have the full data. Ideally an nps file, alternatively a link to that spark recording.

**Comment by Raycoms** [comment]
https://spark.lucko.me/#Qh6vtQ2EDH

**Comment by malte0811** [comment]
Those two commits should fix the issues I could see in that profiling data.

**Comment by Raycoms** [comment]
Oh, awesome, ty
