### ISSUE TITLE
1.16.4 Tesselating block in world, java.lang.NullPointerException

### ISSUE THREAD

**Issue by InkDragon** [BluSunrize/ImmersiveEngineering#4529]
### Description of the issue:
Game Crashes upon attempting to enter the server. I'm the only player that experiences this. My friend who is hosting the server has no issues. We're previously worked around the issue by breaking most/all IE machines

### Crashlog:
https://pastebin.com/rShh6c85

### Versions & Modlist
forge-1.16.4-35.1.10-client.jar
QuarkOddities-1.16.3.jar
improved-stations-2.0.1.jar
ImmersiveEngineering-1.16.4-4.1.1-128.jar
Jade-1.16.3-2.2.1.jar
jei-1.16.4-7.6.0.62.jar
Corail-Recycler-NE-1.16.4-350.jar 
easy_villagers-1.16.4-1.0.4.jar 
rsgauges-1.16.4-1.2.6-b2.jar
Neat 1.7-24.jar
Waystones_1.16.3-7.3.1.jar
itemcollectors-1.0.6-mc1.16.4.jar
comforts-forge-1.16.4-4.0.0.2.jar
AutoRegLib-1.6-47.jar
StorageDrawers-1.16.3-8.2.1.jar
ftb-gui-library-1604.1.1.26.jar
elevatorid-1.16.4-1.7.8.jar
cagedmobs-1.16.4-1.2.6.jar
engineerstools-1.16.4-1.1.2.jar
Bookshelf-1.16.4-9.3.18.jar
WAWLA-1.16.4-7.0.2.jar
BotanyPots-1.16.4-6.0.7.jar
BotanyTrees-1.16.4-2.0.4.jar
engineersdecor-1.16.4-1.1.4.jar 
globalxp-1.16.3-v1.4.15.jar
ImmersivePetroleum-1.16.3-3.1.0.jar
ftb-chunks-1604.2.2.52.jar
forge-1.16.4-35.1.10-universal.jar
Quark-r2.4-279.jar
AppleSkin-mc1.16.2-forge-1.0.14.jar
[1.16.X-1.0.10] Dragon Mounts Legacy.jar
easy_piglins-1.16.4-1.0.4.jar 
WailaHarvestability-mc1.16.2-forge-1.1.13.jar

**Comment by malte0811** [comment]
Update IE, this is fixed in build 129.
