### ISSUE TITLE
[Suggestion] Conveyor Autocrafter

### ISSUE THREAD

**Issue by VermillionX** [BluSunrize/ImmersiveEngineering#453]
Simple enough suggestion: A 3x3x3 or so powered Autocrafting machine for use in a Conveyor Belt array.
The player would set up the crafting recipe like an ordinary crafting table; when the machine has 2 of every item in the recipe, it crafts it and outputs it on the conveyor belt that runs through the middle of the multiblock. Items that aren't on the list or those it cannot hold more of pass through unmolested.
Perhaps give it a piston-like stamping animation when it crafts an item.

Something like this image... in appearance.
![2015-09-25_03 08 44](https://cloud.githubusercontent.com/assets/10645298/10077343/fed447c6-6333-11e5-9c86-d4546d80356c.png)
It's probably on your to-do list anyway.

**Comment by BluSunrize** [comment]
Oh my, that is a really fancy looking build! And No, I did not have that on my todo, but your amazing factory might just persuade me to do it :D

**Comment by Cypher121** [comment]
Hey, is that our RF alternator I'm spying there?

**Comment by VermillionX** [comment]
Busted.
Yep, there's quite a few Magneticraft things in there, simply because they look awesome.

**Comment by krc4267** [comment]
+1, sounds amazing

**Comment by cobra** [comment]
aaand now it's a thing. Thanks for the awesomeness, @VermillionX and @BluSunrize!

**Comment by BluSunrize** [comment]
shoutout to @VermillionX =P

**Comment by Cypher121** [comment]
any screenshots?

**Comment by cobra** [comment]
https://twitter.com/BluSunrize/status/653210968403652608
