### ISSUE TITLE
[Feature Request] Capacitor backpack as a Curio

### ISSUE THREAD

**Issue by Jason-c-o** [BluSunrize/ImmersiveEngineering#4532]
Minecraft 1.16.4

As per this old request: https://github.com/BluSunrize/ImmersiveEngineering/issues/3162

But for CuriosAPI instead of Baubles.

I've tried assigning it the the 'back' curio slot with a datapack, but functionality (and equipped player model) is not maintained.

**Comment by BluSunrize** [comment]
Meh, low priority.
If Curios is Capability, I'll consider it, otherwise it's a hard no.

**Comment by TeamSpen210** [comment]
It uses tags to specify which slots an item is placeable in, and has a capability yes.
