### ISSUE TITLE
Assembler Fluid Crafting Treated wood Valhelsia 3 Modpack 

### ISSUE THREAD

**Issue by scone32** [BluSunrize/ImmersiveEngineering#4533]
### Description of the issue:
Assembler accepts Creosote oil from an IE fluid pipe but won't craft treated wood from the reservoir. Will craft if bucket full of the liquid is placed in the assembler's inventory. All IE components used in the system. 

### Versions & Modlist 
Minecraft 1.16.4 
Valhelsia modpack 3-3.1.1
Immersive Engineering 4.1.1-126

**Comment by malte0811** [comment]
Please test if this still happens with IE build 129. The relevant code has changed at least once since 126.

**Comment by scone32** [comment]
Apologies, the pack is running build 129, the update log in the in game book said 126.

I went into a single player creative world and tested it again using a coke oven, fluid pump, fluid pipe and assembler. The fluid gets pumped into the assembler which then doesn't use the internal fluid to craft treated wood.

**Comment by ThePhantomOTO** [comment]
Is there any fix on this? I too am running Valhelsia 3 with this pack and it isn't working. ImmersiveEngineering-1.16.5-4.2.1-131 is what is in the version I have which is Valhelsia 3 v3.1.8a

**Comment by BluSunrize** [comment]
I just booted up Valhesia v3.1.9 and I can not reproduce this issue.
