### ISSUE TITLE
Issues placing water wheel

### ISSUE THREAD

**Issue by Sunekaer** [BluSunrize/ImmersiveEngineering#4538]
### Description of the issue:
Cant place water wheel on north/south-facing kinetic dynamo when being above the dynamo, works fine on east/west-facing
https://s1.sunekaer.com/i/28-12-2020_15-11-20_%25pn.gif

### Crashlog:
No crashlog and no error in log.

### Versions & Modlist
Forge: 35.1.15
ImmersiveEngineering-1.16.4-4.1.2-129.jar

Happens with only IE so not gonna list the rest of the mods in the pack, if you wanna know the rest its the new DW20 pack or let me know and ill make you a list.

**Comment by BluSunrize** [comment]
Are you maybe just in the collision space of that wheel? See if it works if you move back a bit?

**Comment by Sunekaer** [comment]
moving back didnt help
