### ISSUE TITLE
[Suggestion] Steam Engine

### ISSUE THREAD

**Issue by XFactHD** [BluSunrize/ImmersiveEngineering#454]
It would be awesome if you'd add a steam engine multiblock, please. It should have a a giant rotating flywheel and, if possible, the multiblock should contain a kinetic generator. I think this would be a nice use for coal coke and some fancy piping for the water supply.

**Comment by BluSunrize** [comment]
IE currently has no steam, nor do I want to add boilers. I keep saying this, IE is not steampunk. Steam may or may not happen whenever we do nukes, but that is far off.

**Comment by XFactHD** [comment]
I knew that I would get this answer, that's why I wrote that the multiblock should contain a kinetic generator. It should burn coal/coal coke and thereby use water and generate electricity directly.

**Comment by BluSunrize** [comment]
I don't like coal->power. Whether it's stirling generator steamboiler or whatever. It feels overdone and boring to me xD

**Comment by XFactHD** [comment]
I accept your opinion on that, after all, it still is your mod.
I would love to do it myself but I don't have the time to do it and I don't even have the knowledge to create a simple FluidTank :(
