### ISSUE TITLE
[1.16.4] Crusher "clogged" with ores

### ISSUE THREAD

**Issue by jusjudge** [BluSunrize/ImmersiveEngineering#4541]
### Before reporting:
Did not notice any previous reports similar to mine

### Description of the issue:
I built the crusher. It was crushing coal, and then osmium from Mekanism right after perfectly fine. I was using an extracting conveyor belt connected to a vanilla chest. That led to several conveyor belts dragging the ores to the top of the crusher. I then decided to toss all the iron/gold I had from my inventory. It was full stacks of 64 and my entire inventory was full (All 27 slots). The iron/gold were vanilla ores (overworld/nether), and from a mod called The Undergarden. Some iron processed (2 stacks) but then it eventually stopped completely. I tried flipping the lever (Connected directly to the redstone port on the machine) and nothing. I broke the machine, placed the block back, and right clicked it with the hammer and nothing happened. Since I broke the multiblock and rebuilt it, I was able to save and quit and that's when it started working ago. I seem to have lost all my ores though. :(

### Crashlog:
No crash

### Versions & Modlist
Immersive Engineering 1.16.4-4.1.2-129
Forge 35.1.15
Modlist: https://pastebin.com/RvieCRKW

**Comment by BluSunrize** [comment]
Yeah when you break the machine, you lose the contents. That's how the crusher has worked for the past 4+ years. Sorry about that.

If you can actually create a reproducible test case (which verifies that the crusher outputs less than you put in), we'll consider this a valid issue. But if it happened once on a server and you have no data to back it up with, nor instructions to reliably reproduce, we can't help you.

**Comment by Jwguy** [comment]
For the record, this issue still occurs in 1.12.2, version 0.12-98. Throwing a full stack of ores seems to cause the Crusher to malfunction, and leads to a gigantic loss in resources i.e. It ceases to produce anything.

I had it happen with Vanilla Iron ore.

As it is, given that this issue has remained in the mod for so long, it should be noted that the Crusher is unreliable and should not be used at the current time. It's a shame. I usually consider Immersive Engineering's machines in much higher esteem.

**Comment by BluSunrize** [comment]
For the record, support for 1.12 was dropped 16 months ago.
