### ISSUE TITLE
Rendering overlay crash when using any resource pack shader. Valhelsia 3 - 3.1.2

### ISSUE THREAD

**Issue by Taeleus** [BluSunrize/ImmersiveEngineering#4548]
Description of the issue:
When enabling a resource pack or  shader it crashes the entire game. I've identified it's ImmersiveEngineering because I took the mod out and enabled a pack & shader and it worked just fine. When I put it back in, it crashes.

The game didnt give me a crashlog, just this error 
"The game crashed whilst rendering overlay
Error: net.minecraftforge.fml.ModLoadingException: Immersive Engineering (immersiveengineering) encountered an error during the done event phase
Exit Code: -1"

Playing on Valhelsia 3 - 3.1.2 on version 1.16.4 using forge 35.1.28 as seen in the link below. I have not tweaked the modlist at all with the exception of adding optifine. Game crashes if I load the shaders from main menu, in single player or multiplayer. I have allocated 8gb of RAM to the curseforge launcher as well. Running OptiFine_1.16.4_HD_U_G5. Tried using SEUS-Renewed-v1.0.1 shaders or BSL_v7.2.01pre1. Deleted everything and freshly installed everything and still running into same issue.

Sorry if this seems like a similar issue and I mimicked another post but I was instructed in said other post my issue was unrelated and to post up a new issue. Similar post linked below.

Valhelsia link  - https://www.curseforge.com/minecraft/modpacks/valhelsia-3
Other github issue - https://github.com/BluSunrize/ImmersiveEngineering/issues/4508

Any help/ideas will be greatly appreciated and thank you for your time.

**Comment by Taeleus** [comment]
Just wanted to state that this crash happens only when trying to load in a shader. I can play the game. But if I try to load in the shader from the main menu, in single player, or multiplayer it crashes. Working on trying to locate a proper crash report but the client just closes out and then spits out ""The game crashed whilst rendering overlay
Error: net.minecraftforge.fml.ModLoadingException: Immersive Engineering (immersiveengineering) encountered an error during the done event phase
Exit Code: -1"" with no actual crash report.

**Comment by XFactHD** [comment]
There is always a crash report. In the vanilla launcher click on the "Installations" tab, hover the entry that is set on the left of the play button in the "Play" tab and click the folder icon. This will take you to the game directory. There you will found a folder called crash-reports. In that folder you will find all crash-reports. Please upload the latest one to gist.github.com and post the link here.

**Comment by Taeleus** [comment]
For some reason there was no crash-reports folder to be seen. I had to delete the game, reinstall it, retry the shader and then it populated the folder. Sorry for the miscommunication. Here is the link.

https://gist.github.com/Taeleus/ac574c42cfbde77a7aeb778f1c660628

Thanks for your time on this.

**Comment by Taeleus** [comment]
After going through this one thing stuck out more than others as Ive seen it before once. 
line 465
"GPU Warnings: renderer: Stencil enabled in Immersive Engineering config"

Could that be something I can toggle in Immersive Engineering to try and help?

**Comment by XFactHD** [comment]
Yes, please try disabling that to see if it fixes this. To do that go to the folder you found the crash-reports folder in, go into the config folder, search for the immersiveengineering-client.toml, open it in a text editor and change the stencil setting.

**Comment by Taeleus** [comment]
Same crash same error. Heres the link. https://gist.github.com/Taeleus/e52dab10d0d714297e73280fd998e5d0

Even tried it again disabling this option.
"#Use VBOs to render certain blocks. This is significantly faster than the usual rendering,
#but may not work correctly with visual effects from other mods
enableVBO = true"
Set that to false and it still crashed when trying to apply shaders.
seeing as I have a 2080ti its not old but I figured it was a logical debug step.

**Comment by XFactHD** [comment]
I would need a debug.log now to check if it gives any more info but the CurseForge client (which I assume you used to install the modpack) disables that log.
To get that log, you need to download the Forge installer from files.minecraftforge.net, run it, create a new profile in the Vanilla launcher with the new Forge version as the game version and the game directory set to the folder that opens when going into the modpack's profile in the CurseForge client, clicking the three dots on the right and clicking "Open Folder". Then you start the newly created profile in the Vanilla launcher, reproduce the crash and post the "debug.log" (make sure it is a text file, it might only be called "debug" if you have not instructed Windows to show file extensions) from the logs folder here.

**Comment by Taeleus** [comment]
Ill get on that for you right now. One moment.

**Comment by Taeleus** [comment]
I believe I was able to set it all up properly and reproduce the crash using the vanilla client, with the forge client added to it and then running it all from the vanilla launcher pointed at the vahelsia folder. Here is the link

https://gist.github.com/Taeleus/3874b4d7b5d2f98b436c158288ae2e12

I loaded in to the main menu, hit options, shaders, and clicked the shader to apply, it tried to load it all like it normally does and then when it finished the screen when half-see thru from the loading menu, text popped up saying saving world. it hung here for a sec, and then all closed and the same error as before popped up. So textbook crash as far as my crashes go.

**Comment by XFactHD** [comment]
Unfortunately the debug log is also very undescriptive and doesn't give me any useable info. Can't help you any further here. Maybe Blu or malte has an idea what might be happening.

**Comment by Zothen1973** [comment]
I can confirm this error with Minecraft 1.16.4, Forge 36.1.28 + ImmersiveEngineering-1.16.4-4.1.2-129.jar

![2021-01-05 14_28_14-Window](https://user-images.githubusercontent.com/77007295/103651737-55372a00-4f62-11eb-899b-560a3dccb11b.jpg)

[crash-2021-01-05_14.26.44-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5770365/crash-2021-01-05_14.26.44-client.txt)

**Comment by malte0811** [comment]
The original issue seems to be related to OptiFine, which is not supported. If you manage to reproduce it without OF please open a new issue.

@Zothen1973: That's a completely different issue. Your `immersiveengineering-common.toml` for some reason has `FALSE` in capital letters. Try deleting the config, it will automatically be recreated with "good" values when you launch the game.

**Comment by Zothen1973** [comment]
Taeleus used OptiFine, so did I, ergo it IS the same issue.

**Comment by Taeleus** [comment]
You had a different error than I did. Trust me, if you make a new issue they will do their best to help.

**Comment by Taeleus** [comment]
yours failed somewhere loading the config file. mine got all the way thru the loading process and failed rendering at the done event phase. Sorry to say it but your have a different crash than I do. Best bet is new ticket and upload your crash log file. Also yes. I used optifine. Several other friends running the valhelsia mod used optifine as well, the pack creator said optifine is supported as well. That being said, the individual mod support for optifine may vary. ergo, your mileage may vary by a large amount of variables.

**Comment by Taeleus** [comment]
> Unfortunately the debug log is also very undescriptive and doesn't give me any useable info. Can't help you any further here. Maybe Blu or malte has an idea what might be happening.

Sorry I forgot to reply. Even tho issue wasnt resolved I wanted to thank you for taking your time to look into this issue. Learning to deal with just not using shaders around immersive engineering. Still curious why 3 of my other friends running the same modpack, java version, everything, on the same minecraft server im hosting, can use shaders and its just me who cant. theyre running optifine and the SEUS shaders on the valhelsia modpack on my valhelsia server. Deleting everything and reinstalling several times leads me to believe there is some kind of issue with my hardware specs and the mods/shaders. i9-9900k and a 2080ti tho. doesnt seem to oddball to me but eh, thats computers for you C:  

Thanks again!
