### ISSUE TITLE
[Suggestion[ Add DenseOres support for Arc Furnace.

### ISSUE THREAD

**Issue by OneEyeMaker** [BluSunrize/ImmersiveEngineering#455]
Title says it all.
Your great awesome furnace doesn't know how to melt these 'strange' ores...

**Comment by BluSunrize** [comment]
Well someone is salty. I'll look into it.

**Comment by BluSunrize** [comment]
Was fixed by this commit:
https://github.com/BluSunrize/ImmersiveEngineering/commit/6d07b51ada27a839468146d0f67cb33ae2fb352b
