### ISSUE TITLE
Engineer's manuel crash

### ISSUE THREAD

**Issue by Flexz9** [BluSunrize/ImmersiveEngineering#4550]
### Description of the issue:
Opening engineer's manuel isgiving me this error. Not the first time. Never successfully opened the manuel and also spawned in another copy from creative to confirm since we did move from 1.15.2.

### Crashlog:
https://pastebin.com/1Z8YKvE4

### Versions & Modlist
ImmersiveEngineering-1.16.4-4.1.1-128.jar         |Immersive Engineering         |immersiveengineering          |1.16.4-4.1.1-128
Launched Version: 1.16.4-forge-35.1.13

**Comment by malte0811** [comment]
1. Please update IE to build 129. I don't expect it to fix the issue, but it's good practice in general.
2. Could you upload your debug.log (`logs/debug.log` in your MC folder) as well? That log will have details on *why* one entry failed to load, rather than just saying that it did.

**Comment by Flexz9** [comment]
1. We update every 2 weeks. So today or tomorrow we are updating anyway.
2. https://pastebin.com/iHaSTKT9 Here you go!

**Comment by malte0811** [comment]
Thank you, I'll push a fix in a bit. It looks like you've bound some keybind from IP to `$`, that and `\` currently cause the crash.
