### ISSUE TITLE
Valhalsia 3 - ImmersiveEngineering-1.16.4-4.1.2-129 storage crates disappeared

### ISSUE THREAD

**Issue by TaricOfLegend** [BluSunrize/ImmersiveEngineering#4551]
### Description of the issue:
alright unfortunatley there is no way to screenshot the issue, i was playing on a private just me and my friends server That my friend hosts on her pc (no we dont do pranks or steal each others stuff before asking if someone else just came along and picked em up) i had spent several hours going through dungeons and desert temples gathering artifacts and loot placing it all into wooden storage crates to free up my inventory. when i finnaly got home and placed down the wooden storage crates it all seemed good opened one saw my items said hey im home ill organize this mess later so i play on the server for another 10 mins or so then my friend says they wanna shutdown for the night so she saves the serverworld and shutsdown. this afternoon as we go back on i log into my house and notice something very crucial missing, the 5 storage crates i had placed down still full of loot, completley missing. the place i had put them down is completley empty the crates vanished without a trace just poof gone.

Valhalsia 3 -3.12 is the modpack version and ImmersiveEngineering-1.16.4-4.1.2-129 is the mod in questions version

this is the first time and only time ive seen the storage crates just vanish upon reloading a server. hell my other crates i had in my home before placing the 5 that disapeared with less stuff in them were still there when i logged in just the five filled with odds and ends were gone, stuff like minecolonies spawn items (lootship , supply crate stuff) , runes from quark, Special items from the Artifacts mod as well, regular ores and bars, i cant remember if there were any other modded items inside the crates off hand i was playing at 2am (my friends keep me up late XD ) and was just happy to be done adventuring sorry that i cant remember any other modded items specificly but the ones mentioned before were the majority of items i had in them all.

**Comment by mindforger** [comment]
this should be reproducible, can you cheat in items in question via console? Do not use creative mode, since this can lead to other issues (at least in the past switching between modes did stuff)

Just fill a number of crates with items and mark them with signs and restart the server. Also try to make it quick and make a copy of the latest  logfile after shutting down, there might be hints at shutdown or in restart

**Comment by TaricOfLegend** [comment]
i can try to attempt the next time im on btw ik the swapping modes thing you were referring too XD, ill try to place modded items into them as well similar to what i had originally had

    On Saturday, January 2, 2021, 04:07:12 p.m. EST, mindforger <notifications@github.com> wrote:  
 
 


this should be reproducible, can you cheat in items in question via console? Do not use creative mode, since this can lead to other issues (at least in the past switching between modes did stuff)

Just fill a number of crates with items and mark them with signs and restart the server. Also try to make it quick and have a good of the latest logfile after shutting down, there might be gibt's at shutdown or in restart

**Comment by BluSunrize** [comment]
Closed due to lack of feedback
