### ISSUE TITLE
[1.16.4] IE is not showing correct information for OneProbe

### ISSUE THREAD

**Issue by RobustProgram** [BluSunrize/ImmersiveEngineering#4552]
### Description of the issue:
Immersive Engineering is not connecting with TheOneProbe, thus we are unable to see the following information using TheOneProbe
- Capacitor capacity
- Metal Tank capacity
- Connector type
- Progress for smelting
- Potentially more missed out by me ...

### Crashlog:
Not Needed

### Versions & Modlist
Immersive Engineering: 1.16.4-4.1.2-129
Forge: 1.16.4-forge-35.1.13

**Comment by Lawiel** [comment]
I'm very far off coding, can you please explain how can I install or where can I download that compat for One Probe?

**Comment by RobustProgram** [comment]
It is included in the latest file download on CurseForge
