### ISSUE TITLE
[1.16] Wiring turning invisible after re-loading

### ISSUE THREAD

**Issue by baronjutter** [BluSunrize/ImmersiveEngineering#4555]
### Description of the issue:
Wiring can be placed as usual and shows up as usual, but after re-logging on to minecraft all previously placed wires are now invisible.  Everything is perfectly functional, just dangerously and confusingly invisible.

I attempted to load this exact mod set in single player to try to process of elimination figure out if there's a mod conflict, but even with the exact mod list I can't reproduce the problem in single player.  But every single wire I place in multiplayer turns invisible on my next reload.

### Versions & Modlist
Forge 1.16.4 - 35.1.4
ImmersiveEngineering-1.16.4-4.1.2-129

Just Enough Resources (JER) (by way2muchnoise)
Create (by simibubi)
Shear Madness (by AtomicBlom)
Bad Wither No Cookie - Reloaded (by Kreezxil)
Collective (by Serilum)
Glassential (by Lykrast)
Morpheus (by Quetzi)
Bigger Reactors (by RogueLogix)
Immersive Portals (for Forge) (by qouteall)
Ender Storage 1.8.+ (by covers1624)
Finite Water & Infinite Lava (by tfarecnim)
Extended Mushrooms (by thecech12)
Comforts (by TheIllusiveC4)
Useful Railroads (by HyCraftHD)
Placebo (by Shadows_of_Fire)
The One Probe (by McJty)
Eroding Stone Entities (by Serilum)
Reliquary v1.3 (by P3pp3rF1y)
Spatial Harvesters [FORGE] (by Dunkmania101)
Trample Stopper (by UnRealDinnerbone)
GraveStone Mod (by henkelmax)
Better Than Mending (by legobmw99)
Global XP (by bl4ckscor3)
Trash Cans (by SuperMartijn642)
Ranged Pumps (by raoulvdberge)
Building Gadgets (by Direwolf20)
RFTools Base (by McJty)
Waterworks (by Terpo)
Dungeons Gear (by the_infamous_1)
Essentials (by Technomancer_isTaken)
JEI Integration (by SnowShock35)
'Dustrial Decor (by BlueDuckYT)
Curios API (Forge) (by TheIllusiveC4)
XNet (by McJty)
Dungeon Crawl (by XIROC1337)
CraftTweaker (by Jaredlll08)
YUNG's Better Caves (Forge) (by YUNGNICKYOUNG)
U Team Core (by HyCraftHD)
Charm (by svenhjol)
Quark (by Vazkii)
AutoRegLib (by Vazkii)
Engineer's Decor (by wilechaote)
Torchmaster (by xalcon)
McJtyLib (by McJty)
Infinite Trading (by Serilum)
Extended Lights (by Polyvalord)
Vine Collector (by AlexProgrammer)
Biomes O' Plenty (by Forstride)
Blood Magic (by WayofTime)
YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)
Immersive Petroleum (by Flaxbeard)
AppleSkin (by squeek502)
Flat Bedrock (by Sunekaer)
Phosphophyllite (by RogueLogix)
Scaffolding behavior (by Lothrazar)
Apotheosis (by Shadows_of_Fire)
Just Enough Items (JEI) (by mezz)
Macaw's Windows (by sketch_macaw)
Fallout Inspired Power Amor (by joseph86753091)
Moving Elevators (by SuperMartijn642)
ReAuth (by TechnicianLP)
Patchouli (by Vazkii)
Artifacts (by ochotonida)
Bamboo 2: Modded Boogaloo (by callmeschmille)
Macaw's Doors (by sketch_macaw)
Performant (by someaddon)
Macaw's Trapdoors (by sketch_macaw)
ObserverLib (by HellFirePvP)
Extra Golems (by skyjay1)
Mouse Tweaks (by YaLTeR)
Charmonium (by svenhjol)
Clumps (by Jaredlll08)
Xaero's Minimap (by xaero96)
CodeChicken Lib 1.8.+ (by covers1624)
Nature's Compass (by Chaosyr)
Neat (by Vazkii)
Astral Sorcery (by HellFirePvP)
JEITweaker (by Jaredlll08)
The Lost Cities (by McJty)

Also, please try testing an issue in a minimal instance, with just IE, Forge and maybe JEI. That makes elminating compat issues easier.

**Comment by Recaiden** [comment]
Immersive Portals causes this issue.

**Comment by Edel-Lilies** [comment]
I also have the same problem. After restarting the server, all the connections will disappear, but the machine will operate as usual
ImmersiveEngineering-1.16.5-4.2.0-130

**Comment by mindforger** [comment]
Did you care to read the answer? Also „me2“-ing is far from helpfull with only the modversion

**Comment by BluSunrize** [comment]
If anyone can reproduce this *without* Immersive Portals, we'll happily investigate it further.

**Comment by DriftinFool** [comment]
> If anyone can reproduce this _without_ Immersive Portals, we'll happily investigate it further.

I stumbled on this thread because all my wires were invisible today. I am playing Engineer's Life 2 in single player, and it does not have immersive portals. The modpack sends you to the nether using Yung's Better Portals. The wires disappeared when I came back from the nether. After closing minecraft and reloading, they were visible again. Didn't know if this info would be useful to you or not, but figured I'd share based on your comment.

**Comment by altanov** [comment]
> > If anyone can reproduce this _without_ Immersive Portals, we'll happily investigate it further.
> 
> I stumbled on this thread because all my wires were invisible today. I am playing Engineer's Life 2 in single player, and it does not have immersive portals. The modpack sends you to the nether using Yung's Better Portals. The wires disappeared when I came back from the nether. After closing minecraft and reloading, they were visible again. Didn't know if this info would be useful to you or not, but figured I'd share based on your comment.


same happened for me, theres no immersive portals yet wires still disappear after visiting nether, yet the newly placed wires do not turn invisible until next visit

**Comment by BluSunrize** [comment]
1.16 is long out of support, there will be no further work on this.
