### ISSUE TITLE
[1.12.2] question

### ISSUE THREAD

**Issue by Gandalf360one** [BluSunrize/ImmersiveEngineering#4557]
First of all I know that the 1.12.2 verion is no longer supported but I hope that I will maybe get an answer

I want to disable some multiblock structures and I already read how to disable them. Is there a config or something like that to automatically add the nbt tag to the hammer?
For the crafting I can use crafttweaker but how can I add this tag to the hammer when I find it in a crate or take it out of the frame?

**Comment by BluSunrize** [comment]
Nope, there is no config for it. Replacing the recipe with crafttweaker is your best bet.
