### ISSUE TITLE
[1.16.4] Assembler Ignoring Internal Tank

### ISSUE THREAD

**Issue by VaelophisNyx** [BluSunrize/ImmersiveEngineering#4559]
### Description of the issue:
As with #4533, #2655, #2412, and #2260, recipes that call for a bucket of fluid (in this case, Water) do work with a bucket of the fluid in the inventory. However, they will not use fluids added to the internal tank. 

### Versions & Modlist
https://pastebin.com/bxi33jLk

Yes I am aware that both Forge and IE (and IP) are a version or two behind. Unfortunately, updating Forge or mod files is a last result, if that's the issue, given that this is a dedicated server that would need to be shut down for an extended time to do so.

**Comment by VaelophisNyx** [comment]
That said, knowing the next version up still seems to have this issue, I'd just chalk this down as a notification of an issue, rather than support being needed. Personally, I've used a bottler to get around the issue for the time being.

**Comment by 6TELOIV** [comment]
This issue appears to persist with the most recent version as well.

**Comment by BluSunrize** [comment]
Then file a proper report.
