### ISSUE TITLE
CoFH Hammer API missing

### ISSUE THREAD

**Issue by cobra** [BluSunrize/ImmersiveEngineering#456]
Here we go again, another missing class when launching MC with IE without a third-party mod.

Crashes on startup with 
````
java.lang.NoClassDefFoundError: blusunrize/immersiveengineering/common/items/ItemIETool
	at blusunrize.immersiveengineering.ImmersiveEngineering.preInit(ImmersiveEngineering.java:65) ~[ImmersiveEngineering.class:?]
````
Built with CoFHLib-[1.7.10]1.0.3-175-dev.jar, launched in MultiMC with only CodeChickenCore and NEI, deliberately missing any CoFH mods. Obviously, not a big surprise.
Most people will have CoFHCore, so they won't run into this problem, but I think this should be resolved - I just don't know which way you want to do this. I'd add the item package into the sources just like you did with the energy package. Also I don't have that (internal, not file name) version 1.0.10 (oh CoFH, you and your weird versioning), so maybe just update to the latest one, shouldn't change anything used in IE.

IE version: 0fbca858e93005bc304e171d902488e6279007ca

**Comment by Cypher121** [comment]
From what I see, it has nothing to do with CoFH. Perhaps you will provide a full crash log?

**Comment by BluSunrize** [comment]
Cobra knows what he's ding. Problem is that Lemming apparently doesn't. I'm using optional so it should strip the interface when no CoFHAPI is found, and he told me himself to use "CoFHAPI"

**Comment by cobra** [comment]
Oh, that comment about it not being a big surprise wasn't that correct, I read the compile error a little bit too fast when making it.
The `@optional` annotations reference the whole `CoFHAPI` package (which is present due to the included files) instead of (currently missing) `CoFHAPI|item` subpackage. I've fixed that, but it still leaves an unresolved compile-time dependency. I'm also wondering whether we should remove the top level package-info when not including all subpackages.

@Cypher121 it is, no need to post more than that. IE tries to instantiate an `ItemIETool`, which is implementing an undefined interface:
`public class ItemIETool extends ItemIEBase implements cofh.api.item.IToolHammer`
@BluSunrize nope, sorry, that is your fault - there are multiple package-info files, which is quite neat actually :p But I also fell for that at first, so I can't really blame you.

**Comment by BluSunrize** [comment]
So I'll remove the top level info file and use the correct CPI sub, huh?

**Comment by cobra** [comment]
I'm not sure, that's why I kept it for now. I guess there should only be the subpackages' package-infos. I couldn't find any reference to CoFHAPI (in my branch now), so it shouldn't break anything.

**Comment by cobra** [comment]
Split it into three commits so you can pick what you want or test them individually.
