### ISSUE TITLE
[1.15] Server Hang on Shutdown with "Exception in thread "Immersive Engineering Registry Iteration Thread""

### ISSUE THREAD

**Issue by dragonshardz** [BluSunrize/ImmersiveEngineering#4560]
### Description of the issue:
When I shut down the server I am running, instead of shutting down, the server seems to hang and when I kill the process, it spams the log with _Exception in thread "Immersive Engineering Registry Iteration Thread"_

As suggested in #1921, I have arc furnace recycling turned off, but still have this issue.

### Logs
[debug.log](https://gist.githubusercontent.com/dragonshardz/0a6ae768bef420a922055856da368cc0/raw/2ee5396fe2c215bfb265477971b55f6202b86ace/debug.log)
[latest.log](https://gist.githubusercontent.com/dragonshardz/0a6ae768bef420a922055856da368cc0/raw/2ee5396fe2c215bfb265477971b55f6202b86ace/latest.log)

### Versions & Modlist
[modlist_202010108.txt](https://gist.githubusercontent.com/dragonshardz/0a6ae768bef420a922055856da368cc0/raw/2ee5396fe2c215bfb265477971b55f6202b86ace/modlist_202010108.txt)

**Comment by BluSunrize** [comment]
1.15 is no longer receiving any updates

**Comment by dragonshardz** [comment]
Then why is it still available to download if it has a bug you won't fix?

**Comment by mindforger** [comment]
Because minecraft does not wait for mods to mature, people are still playing 1.7.10 and find new bugs, what do you expect?

**Comment by dragonshardz** [comment]
> Because minecraft does not wait for mods to mature, people are still playing 1.7.10 and find new bugs, what do you expect?

A bug that makes a server hang when it's stopped is, to me, serious enough to either fix or pull the affected mod version from distribution.

**Comment by BluSunrize** [comment]
It's available to download still because it's been downloaded 311,000 times, and you are the first person to report that issue. And you are reporting it for the first time after we have ceased support on that version.

It's still available, because I don't believe in destroying legacy like that. It remains online for the people that want it.
