### ISSUE TITLE
[1.16.4] External Heater does not work with the vanilla Blast Furnace and vanilla Smoker

### ISSUE THREAD

**Issue by dan96kid** [BluSunrize/ImmersiveEngineering#4564]
Forge version: 35.1.11
Mods:
- Advanced Chimneys
- Applied Energistics 2
- Astral Sorcery
- AutoRegLib
- Bamboo Everything
- Bookshelf
- Botania
- Chisels and Bits
- Create
- Curios Forge
- Enchantability
- Engineer's Decor
- GeckoLib
- Endertech
- Glassentials
- Immersive Engineering
- Immersive Petroleum
- Immersive Posts
- Immersive Railroading
- Just Enough Items
- Mana and Artifice
- Macaw's Furniture
- Mekanism
- More Red
- Nature's Aura
- ObserverLib
- Patchouli
- Path Under Gates
- Platforms
- Psi
- ShetiPhanCore
- Storage Drawers
- The One Probe
- TrackAPI
- UniversalModCore

What I expect: When I power an External Heater placed directly next to a vanilla Blast Furnace or vanilla Smoker, the vanilla Blast Furnace or vanilla Smoker should light up just like a vanilla furnace.

What really happens and how to reproduce: When powered, the External Heater does not light the vanilla Blast Furnace or vanilla Smoker
![image](https://user-images.githubusercontent.com/14021093/104136787-ed1b8600-535d-11eb-8d2e-57d46e2b34df.png)
![image](https://user-images.githubusercontent.com/14021093/104136801-07556400-535e-11eb-8b7a-1ccaf6784adf.png)
![image](https://user-images.githubusercontent.com/14021093/104136813-163c1680-535e-11eb-8604-0b675370588f.png)

**Comment by TeamSpen210** [comment]
This is intentional behaviour, it only heats the standard furnace since those two already have a speed increase.

**Comment by malte0811** [comment]
That^
