### ISSUE TITLE
1.16 Redstone connectors not behaving

### ISSUE THREAD

**Issue by csuarezmtz** [BluSunrize/ImmersiveEngineering#4565]
Using redstone to control dynamos for energy production.
When connecting the redstone connectors to provide ON/OFF signal for the dynamos (comparator to leadstone cell into redstone dust - 13 blocks for fullness signal) the outgoing connectors retain the last redstone state - for example: 

1. If using a repeater, once the signal at the end of the control line is 1, repeater inputs 15 into the redstone connector which is relayed into the dynamos. But when the signal falls to 0, even though the repeater is shut down, connector at the dynamo side remain at 15
2. If no repeater is used, the signal is relayed to the dynamo side (1 strength signal) and said strength is retained (dynamo side stays at 1).

This behavior is not seen if using levers - connecter 1 connector to a lever and into another connector, end signal follows lever state.

**Comment by BluSunrize** [comment]
Provide pictures of your setup please, I can not visualize this from description alone.

**Comment by csuarezmtz** [comment]
Here's a post with the pics. Let me know if I can provide more info. https://imgur.com/a/59qYtnn

**Comment by arhote** [comment]
I can verify I'm having the exact same bug happen in my connectors. Specifically in the Velhelsia 3 pack if that context makes a difference.

**Comment by BluSunrize** [comment]
Sorry, I never followed up on this.

The connectors are too close to eachother. The outputting connectors are powering the input, creating an infinite state. We are currently in talks on how to address this, going forward.

**Comment by csuarezmtz** [comment]
I appreciate it, hope me reporting it was useful.
