### ISSUE TITLE
[1.16.4] Diamond ore aren't produced by extractor in coal veins

### ISSUE THREAD

**Issue by gabryjust04** [BluSunrize/ImmersiveEngineering#4569]
Wiki says that diamond also comes out in the veins of coal, but it isnt true. Is it a bug or a feature? https://ftb.gamepedia.com/Mineral_Deposits

**Comment by BluSunrize** [comment]
The wiki is wrong. Diamonds were removed from mineral veins from 1.14 onwards.

Don't use the wiki, read our ingame Engineer's Manual.
