### ISSUE TITLE
[feature request] Fuse box

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#457]
Request for feature: could you please add Fuse Boxes and fuses

 fuse box would have one input, power from the mains
*The fuse box would have multiple outputs, each their own 'circuit'
  *Each circuit would be limited in max transfer rate by the output voltage, which would be regulated by           the fuse installed in the appropriate slot in the fuse box
     *the fuse would be a disposable item, being consumed if the circuit draws too much current.
     *the fuse would also protect the circuit from power surges caused by abnormal fluctuations on the power grid

..Or however you see it fit to implement them

**Comment by XFactHD** [comment]
There should be one fuse box for a single input and a single output and one fuse box for one input and multiple outputs.

**Comment by Voxel-Friend** [comment]
Perhaps a different tiered fuse for each level of voltage...
