### ISSUE TITLE
[1.16.4] Alloy Kiln Does Not seem to affect fuel

### ISSUE THREAD

**Issue by RubGoose** [BluSunrize/ImmersiveEngineering#4570]
### Description of the issue:
I've been hosting a modded server for me and my friends. I've reached the stage where I'm ready to move on to the Alloy stage. Although, upon constructing the alloy kiln, I found out, that the alloy kiln itself would not accept any fuel, thus i cannot make the alloys that i need to progress. It's very frustrating and i hope it can be fixed or if there is a hotfix.

### Versions & Modlist
We're all using Forge version 1.16.4 - 35.1.36 
and
IE version 1.16.4-4.1.2-129.
https://pastebin.com/qPcfLkfV

**Comment by malte0811** [comment]
I'm unable to reproduce this. Does it happen with just IE? What fuels did you try to put in (using the GUI I assume)?

**Comment by RubGoose** [comment]
Yes, it only happens with IE. I've tried every coal (Coal, block of coal, and coke coal).

Also along the way, i've found a way to bypass the alloy kiln. 

btw, i've stumbled upon more issues;
The powered lamp doesn't light up when powered and the animation speed is really slow when multiple items are in queue on the conveyer

**Comment by RubGoose** [comment]
Quick note;
The light issue got fixed by rejoining the server

**Comment by BluSunrize** [comment]
Are you able to reproduce this issue in a singleplayer game with *just* IE installed?
If so, please do, and then produce a debug crashlog (by holding F3+C) and upload that crash as well as your `latest.log` file to https://pastebin.com and link it here, thanks.

**Comment by IvanTC95** [comment]
Same bug here. I have the mod updated to the last version compatible with 1.16.4

**Comment by BluSunrize** [comment]
1.16.4 is no longer supported. Update to 1.16.5.
If you can reproduce the bug then, open a new issue.
