### ISSUE TITLE
crash on world create

### ISSUE THREAD

**Issue by FearAK** [BluSunrize/ImmersiveEngineering#4573]
crash on world create

https://paste.ubuntu.com/p/c6phzpsw8H/

**Comment by BluSunrize** [comment]
Please provide your config files used for IE, specifically the defaultconfig / the config of that specific world.

**Comment by FearAK** [comment]
Seems like it was due to my java, updated it and it fixed it

**Comment by BluSunrize** [comment]
Next time, please follow the contribution guidelines and issue template, thanks.
