### ISSUE TITLE
[1.16.4][DedicatedServer] Powered Lantern not blocking modded spawn

### ISSUE THREAD

**Issue by drakray** [BluSunrize/ImmersiveEngineering#4576]
### Description of the issue:
The Powered Lantern doesn't prevent Vampire from Vampirism, not Trolls from Ice&Fire, at least, on dedicated server.
A good solution might be to have a black/white/add-listing for the powered lantern?

### Crashlog:
N/A

### Versions & Modlist
MC 1.16.4
Forge 35.1.36
ImmersiveEngineering 4.1.2.129
<details>

<summary>Full Modlist</summary>

aawitherskull-1.1.jar
ab-abnormalscore-3.0.5.jar
ab-atmospheric-3.0.0.jar
ab-autumnity-2.0.0.jar
ab-buzzier_bees-3.0.0.jar
ab-endergetic-3.0.0.jar
ab-neapolitan-2.0.0.jar
ab-savageandravage-3.0.0.jar
ab-upgrade_aquatic-3.0.0.jar
additionallights-2.1.3.jar
alllootdrops-2.0.jar
angelring-1.3.3.jar
appleskin-1.0.14.jar
aquaculture-2.1.11.jar
arsnouveau-1.10.4.jar
assortedcore-1.0.3.jar
assorteddecor-2.0.7.jar
assortedstorage-2.1.2.jar
assortedtools-2.2.6.jar
autoreglib-1.6-47.jar
azuredoomchunkloader-1.0.0.jar
basaltblocks-1.0.0.jar
betteradvancements-0.1.0.103.jar
betterbedrockgenerator-0.1.2.jar
betterdefaultbiomes-a2.5.1.jar
biomesoplenty-13.0.0.426-universal.jar
bloodmagic-3.0.3-8.jar
bookshelf-9.3.18.jar
botania-410.jar
botanypots-6.0.13.jar
botanytrees-2.0.7.jar
bountifulbaubles-0.0.2.jar
bowinfinityfix-9.1.jar
buildersaddition-20201220b.jar
byg-1.1.5.jar
caelus-2.1.0.0.jar
carmoury-1.1.0.jar
carrierbees-0.0.2.2.jar
cc-00-cyclopscore-1.9.4.jar
cc-01-commoncapabilities-2.5.5.jar
cc-02-evilcraft-1.0.4.jar
cc-02-integrateddynamics-1.1.22.jar
cc-03-integratedcrafting-1.0.10.jar
cc-03-integratedterminals-1.1.0.jar
cc-03-integratedtunnels-1.6.14.jar
ceramics-1.6.0.jar
ceramicshears-1.3.2.jar
charm-2.1.9.jar
chocolate-1.2.0-.jar
chunkloaders-1.1.3.jar
citadel-1.5.3.jar
clib-1.5.0.jar
collective-1.53.jar
configurableextramobdrops-1.1.jar
cookingforblockheads-9.2.2.jar
cosmeticarmorreworked-1.jar
crafttweaker-7.0.0.63.jar
crockpot-1.3.0.jar
curioofundying-5.1.0.0.jar
curios-4.0.3.0.jar
curiouselytra-4.0.0.1.jar
delogger-1.0.6-.jar
doggytalents-2.0.1.2.jar
dropthemeat-1.1.jar
dungeoncrawl-2.2.3.jar
dungeonsplus-1.1.0.jar
durabilityviewer-1.10.jar
earthmobsmod-0.2.1.jar
eidolon-0.2.5.jar
enchantmentdescriptions-6.0.2.jar
enigmaticlegacy-2.10.1.jar
envirocore-3.0.6.0.jar
enviromats-2.0.6.0.jar
envirotech-3.0.6.1.jar
extraarmor-1.1.5.jar
extragolems-11.2.0.jar
extremereactors2-2.0.18.jar
farlanders-1.3.6.jar
farmersdelight-0.2.4b.jar
farmingforblockheads-7.2.1.jar
fastleafdecay-25.jar
fastworkbench-4.4.1.jar
forge-1.16.4-35.1.36-server.jar
forge-1.16.4-35.1.36-universal.jar
fruittrees-2.2.0.jar
ftb-gui-library-1604.1.1.26.jar
fxcontrol-2.0.2.jar
geckolib-3.0.0.jar
gemsnjewels-0.19.0.jar
glazedsymmetry-1.0.jar
guardvillagers-1.1.8.jar
guide-api-vp-2.2.0.jar
healingcf-3.1.jar
hwyla-1.10.11-b78.jar
iceandfire-2.1.4.jar
ie-00-trackapi-1.2.1.jar
ie-00-universalmodcore-1.0.1.jar
ie-01-immersiveengineering-4.1.2-129.jar
ie-02-engineersdecor-1.1.6-b2.jar
ie-02-immersivepetroleum-3.1.0-2.jar
ie-02-immersiveposts-3.0.0.jar
ie-02-immersiverailroading-1.8.0.1.jar
ie-02-rsgauges-1.2.7-b1.jar
incontrol-5.0.3.jar
infinitetrading-1.2.jar
initialinventory-5.0.1.11.jar
inventorytotem-1.1.jar
invtweaks-1.0.1.jar
jei-7.6.1.63.jar
jeiintegration-6.1.1.11.jar
jeitweaker-1.0.1.5.jar
justenoughbeacons-3.1.jar
justenoughresources-0.12.0.103.jar
kingvillager-1.6.1.jar
kiwi-3.4.1.jar
livingthings-1.2.3.jar
lumberjack-2.1.4.jar
manaandartifice-1.2.1.6.jar
mantle-1.6.52.jar
masonry-0.3.6.jar
mcw-bridges-1.0.4.jar
mcw-doors-1.0.1.jar
mcw-furniture-2.0.0.jar
mcw-roofs-2.0.0.jar
mcw-trapdors-1.0.0.jar
mcw-windows-1.0.2.jar
moreoverlays-1.18.11.jar
morevanillalib-1.3.9.jar
mousetweaks-2.13.jar
mysticalchemy-0.0.7.jar
mysticalworld-0.3.1.4.jar
netherenhanced-0.3.jar
netherportalfix-7.2.1.jar
neverneededorwanted-1.0.5.jar
nhacampfire-3.0.jar
observerlib-1.4.3.jar
overloadedarmorbar-5.1.0.jar
paintings-7.0.0.1.jar
pamhc2crops-1.0.1.jar
pamhc2foodcore-1.0.0.jar
pamhc2foodextended-1.0.0.jar
pamhc2trees-1.0.0.jar
pandorascreatures-2.0.1.jar
patchouli-48.jar
placebo-4.3.3.jar
polymorph-0.22.jar
potionofbees-1.1.0.2.jar
productivebees-0.5.2.5.jar
quark-2.4.286.jar
quarkoddities.jar
ratlantis-1.0.0.jar
rats-7.0.3.jar
reauth-3.9.3.jar
regrowth-1.35.0.18.jar
reliquary-1.3.4.1061.jar
repurposedstructures-2.3.3.jar
sc-00-shetiphiancore-3.8.4.jar
sc-01-enderchests-1.7.5.jar
sc-01-endertanks-1.9.3.jar
solcarrot-1.9.8.jar
solpotato-1.0.4.jar
spawnerfix-1.0.0.1.jar
storagedrawers-8.2.1.jar
storageoverhaul-1.0.1.jar
structuregelapi-1.7.2.jar
supplementaries-0.9.17.jar
swingthroughgrass-1.5.3.jar
theundergarden-0.4.1.jar
tinycoal-1.0.0.jar
toughnessbar-6.1.jar
usefulbackpacks-1.11.6.86.jar
uteamcore-3.1.17.191.jar
valhelsiastructures-16.0.5.jar
valkyrielib-3.0.6.1.jar
vampirism-1.7.1.jar
vanillacookbook-1.10.jar
vanillaexcavators-2.2.0.jar
vanillahammers-2.2.0.jar
wailaharvestability-1.1.13.jar
wawla-7.0.2.jar
waystones-7.3.1.jar
woot-1.0.3.0.jar
worldnamerandomizer-1.1.1.jar
worldpregenerator-1.0.0.jar
wyrmroost-1.2.10.jar
xaerosminimap-20.30.1.jar
xlpackets-1.1.jar
yungbettercaves-1.0.6.jar
yungbettermineshafts-1.1.1.jar
zerocore2-2.0.17.jar

</details>

**Comment by BluSunrize** [comment]
Sounds to me like those two mods are not applying `EntityClassification.MONSTER` to their respective entities. Should probably report that on the issue trackers of those mods.
As far as I am concerned, a Vampire should be considered a hostile monster for the purposes of game logic.

**Comment by drakray** [comment]
Thanks, I'll forward the info :)
Do you think it would be possible to still have a addList, if for example I want to prevent stuff not from ```EntityClassification.MONSTER``` like animals or ambient creature?

**Comment by BluSunrize** [comment]
Late reply but no, no such plans for a list like that. The lantern is targeted at hostile creatures, that's by design. I don't believe this needs to be configurable.
