### ISSUE TITLE
 No function of electronics 

### ISSUE THREAD

**Issue by Niki118** [BluSunrize/ImmersiveEngineering#4580]
hello everyone my problem is that the power generation does not work, just like the use of stome devices. All other things work like oven, revolver, ...
Maybe one of you knows how to fix that

v. 1.16.4 -4.1.2-129

**Comment by BluSunrize** [comment]
Not when you give that poor of a description.

1. What have you tried to do?
2. How do you determine it not working?
3. Can you provide pictures of your setup?

**Comment by Niki118** [comment]
Ich habe alle Versionen des Mods für die 1.16.4 probiert und die beiden letzten Forge Versionen für 1.16.4

Die Maschinen geben keinen Strom ab an die Speicher und andere Geräte .Auch der Vollgeladener Speicher (gamemode 1) gibt seinen Strom nicht ab. (Auch mit der Einstellung des Hammers)

![image](https://user-images.githubusercontent.com/77553061/104956989-8df8e980-59cd-11eb-86b1-db6c1b99c107.png) 

Brauch ich noch einen zusätzlichen mod außer diesen, oder etwas anderes?

**Comment by BluSunrize** [comment]
You're using relays, not connectors. Relays can't insert or extract power.
Read the manual
