### ISSUE TITLE
[1.12] Glass panes connect to engineer's workbench

### ISSUE THREAD

**Issue by sigmareaver** [BluSunrize/ImmersiveEngineering#4581]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
Glass panes connect to Engineer's Workbench which doesn't look right/good on a piece of furniture. Would expect behavior similar to vanilla chests.

### Versions & Modlist
Forge: 14.23.5.2847
IE: 0.12-98

**Comment by BluSunrize** [comment]
1.12 is no longer supported.
