### ISSUE TITLE
[Feature Request] More compatibility for the Revolver, Railgun, and Chemical Thrower, plus an idea to extend the farming aspects of the mod

### ISSUE THREAD

**Issue by Corvus20** [BluSunrize/ImmersiveEngineering#4584]
-Compatibility with mods that introduce quivers or similar ammo storage. Allowing for easier carrying of iron rods or revolver cartridges.

-Compatibility with Guard Villagers so they can use revolvers and railguns instead of bows and crossbows if they want to. If there is some way to make villagers (and perhaps pillagers) use these, it could be a fun challenge for modpacks to use, and would also give the guard villagers more of a chance against modded enemies.

-More chemical thrower chemical effects. Steam from Mekanism could steam clean the color out of wool, blast the moss off of mossy block variants, or remove the color from concrete powder. Additionally could deal damage to enemies with the scalding heat. Making it so water sprayed from a Chemical thrower could hydrate farmland, harden concrete, etc. 

-Liquid Fertilizer can be crafted with bone meal, dirt, leaves, and any plant (saplings, flowers, etc.) in a fermenter. This can be used in the garden cloches instead of water, or be put into a chemical thrower to fertilize crops/spawn tall grass like bonemeal would.

-Sprinkler: A peaceful version of the turret. when powered (and optionally has a redstone signal), it will turn its "head" around in a circle and sprinkle the surrounding crops with water or liquid fertilizer. Nice for more fancy looking builds if people don't want to just use garden cloches or other normal farm setups.

**Comment by mindforger** [comment]
modular turret, has to be equipped with a weapon/tool and acts accordingly

**Comment by BluSunrize** [comment]
> 
> -Compatibility with mods that introduce quivers or similar ammo storage. Allowing for easier carrying of iron rods or revolver cartridges.

Nope.

> -Compatibility with Guard Villagers so they can use revolvers and railguns instead of bows and crossbows if they want to. If there is some way to make villagers (and perhaps pillagers) use these, it could be a fun challenge for modpacks to use, and would also give the guard villagers more of a chance against modded enemies.

That's beyond the scope of mod compatability I am interested in

> -More chemical thrower chemical effects. Steam from Mekanism could steam clean the color out of wool, blast the moss off of mossy block variants, or remove the color from concrete powder. Additionally could deal damage to enemies with the scalding heat. Making it so water sprayed from a Chemical thrower could hydrate farmland, harden concrete, etc.

Steam does not undye a fabric O_o
Also, it already does damage. All fluids do, depending on their temperature. Water already extinguishes fire. Hydrating farmland is mostly pointless, since it'll lose that effect if there is no water source nearby.

 > -Liquid Fertilizer can be crafted with bone meal, dirt, leaves, and any plant (saplings, flowers, etc.) in a fermenter. This can be used in the garden cloches instead of water, or be put into a chemical thrower to fertilize crops/spawn tall grass like bonemeal would.

No. Support for fluid fertilizers was removed from the cloche. The feature existed in 1.12 and noone ever used it, so I took it out.

> -Sprinkler: A peaceful version of the turret. when powered (and optionally has a redstone signal), it will turn its "head" around in a circle and sprinkle the surrounding crops with water or liquid fertilizer. Nice for more fancy looking builds if people don't want to just use garden cloches or other normal farm setups.

Cloches exist for a reason. I see no reason to offer an alternative form of farming when the cloche is expressly designed for this.

> modular turret, has to be equipped with a weapon/tool and acts accordingly

Absolutely not, that sounds like an API nightmare. =P

**Comment by mindforger** [comment]
>Absolutely not, that sounds like an API nightmare. =P 

*roflemoji

yes it does, but i would be awesome

PS: damn github markdown XD
