### ISSUE TITLE
[1.16.5] Crash when installed on rails [Server]

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#4585]
### Description of the issue:

https://user-images.githubusercontent.com/71688822/105105520-e5c24e00-5abc-11eb-8f0f-ba72f616c5de.mp4

### Crashlog:
[crash-2021-01-19_18.01.22-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5839129/crash-2021-01-19_18.01.22-server.txt)

### Versions & Modlist
forgeVersion, 36.0.1. Use Mohist 1.16.5 buid #312
Mode list: 
![image](https://user-images.githubusercontent.com/71688822/105105916-bd871f00-5abd-11eb-9500-9f621105a3e5.png)

**Comment by BluSunrize** [comment]
That's a Bukkit error, nothing we can do about that.
