### ISSUE TITLE
Deadlock with light calculation

### ISSUE THREAD

**Issue by Darkere** [BluSunrize/ImmersiveEngineering#4586]
### Description of the issue:
Deadlock

### Crashlog:

See worker (main) thread.
https://spark.lucko.me/#qeAXiPCPBb

### Versions & Modlist

EDIT: Correction this might have been an earlier version. Will update if issue also appears on this version and will update versions shortly. 
ImmersiveEngineering-1.16.4-4.1.2-129
forge-1.16.4-35.1.37
Pack: Enigmatica 6 v0.3.7

**Comment by malte0811** [comment]
This should be fixed by 771abbeb35ead6263ff1b297d13a5ac687ad7c3e (in additional to the AO crash). I'll close this issue for now, please comment if it happens again on either a dev build with that commit or the next release build (no ETA).
