### ISSUE TITLE
[Suggestion] Allow the Bottler to fill Wooden/Metal Barrels

### ISSUE THREAD

**Issue by smoothuk** [BluSunrize/ImmersiveEngineering#4589]
Simple suggestion, hopefully a simple implementation.  I figured this would be one of the main uses for the Bottler.  Alas, it would appear it doesn't work like that.

**Comment by BluSunrize** [comment]
The items of our barrels do not have fluid handlers, and I don't want them to. I've seen the chaos that other mod's fluid tanks cause.
