### ISSUE TITLE
[Suggestion] Make redstone connectors and probe GUI able to be closed with "E"

### ISSUE THREAD

**Issue by LeoBeliik** [BluSunrize/ImmersiveEngineering#4590]
### Description of the issue:
Using the default open/close inventory key (E) in order to close Redstone connectors and probe connector GUI makes it more natural and ergonomic than reaching ESC every time, especially when editing multiple connectors.

### Versions & Modlist
IE: 1.16.4-4.1.2-129
Forge: 35.1.37

**Comment by VariableVixen** [comment]
Perhaps use the _configured_ inventory key instead of the _default_ one? Personally, I use tab for inventory in most of my games.

**Comment by BluSunrize** [comment]
Yeah I'd use the keybinding for it, because I have my Inventory bound to Q.
