### ISSUE TITLE
Purely Broken Wiring.

### ISSUE THREAD

**Issue by SodaTapper** [BluSunrize/ImmersiveEngineering#4591]
Minecraft version 1.16.4 
Mod version 4.1.2-129

I set up a power station and wired Hv to a Hv transformer. I then used insulated Mv wires from the transformer all the way across power lines to my house. Set up a regular transformer and wired the Lv to my lanterns on the inside. All was fine until I started adding more the grid. I have 4 HV capacitors though and nowhere near using that much power. My house stayed lit until i changed the wiring from the passthrough connector to the lantern to a passthrough connector to a relay that then relayed to multiple areas. I had to completely redo the wiring in order to fix it. Now its just broken and the lights arent turning on and my machines arent recieving power even tho they were 10 seconds prior to me practically just breaking and replacing the same thing. I dont know what this bug really is but it needs to be reported. It would be easier to explain through a discord screen share or over a call so i appologize if it seems a little jumbled here.

**Comment by ItsElmo** [comment]
Maybe provide pictures or video
