### ISSUE TITLE
Crusher stopped functioning after putting a stack of Iron Ore inside

### ISSUE THREAD

**Issue by Lizzy7474** [BluSunrize/ImmersiveEngineering#4592]
I got my Crusher hooked up and running, but then after putting a stack in it stopped spitting out the contents. I destroyed the multiblock and replaced it, i turned the lever back on and only put in one ore, the crusher ate it, but did not make any sounds or extract the dust from the one ore, I tried flipping the lever multiple times, I tried replacing the multiblock multiple times, putting one new ore in at a time, the crusher was inactive and just didnt work after that, at all. No Sound, no extractions, just eating the ores. I also tried to jump in it and interact with it in creative a few times too to see if it helped the issue, and it was unsuccessful.

**Comment by BluSunrize** [comment]
A lever turns the machine off.

Also, you have not provided any of the information requested in the issue template.
