### ISSUE TITLE
[1.16.4][sporia modpack] Wooden post renders with all possible attachment points.

### ISSUE THREAD

**Issue by detsuo04** [BluSunrize/ImmersiveEngineering#4594]
![2021-01-23_05 56 35](https://user-images.githubusercontent.com/77883366/105577538-e74f7880-5d3f-11eb-8ba5-ef7b40dbc6a5.png)

Electrical posts are rendered with all possible attachment points and these points are not affected by the engineers hammer.
placement is at altitude of 72 and appears this way regardless of attachments.

**Comment by BluSunrize** [comment]
Follow the issue template or you will not receive any assistance.

**Comment by BluSunrize** [comment]
I'll reopen this if you fix your post and provide us with the requested information

**Comment by detsuo04** [comment]
alright fuck you then

**Comment by BluSunrize** [comment]
Have a nice day =)
