### ISSUE TITLE
[1.12] Fine-grained comparators not updated as fluid tanks fill

### ISSUE THREAD

**Issue by Hawk777** [BluSunrize/ImmersiveEngineering#4598]
### Description of the issue:
While filling a multiblock metal fluid tank, comparators reading the fine-grained tank level (connected to the higher layers) do not update their output. They update to the proper values if they are updated due to other neighbouring blocks changing. They also work fine if the tank is draining via a pipe at the bottom. However, if the tank is only filling but not draining (either via fluid flowing in through a pipe or being filled by buckets), the fine-grained comparators do not update. The coarse-grained comparator at the bottom updates fine in this situation; only the fine-grained comparators that should cover the four individual levels fail to update.

This happens with vanilla comparators because they only change their output when they are “updated” in the block update sense. Immersive Engineering probes appear to be unaffected because they continuously poll their connected blocks for new values, even when no block update occurs.

I tried to find a specific place in code to point at, but the latest tag for 0.12 seems to be 0.12-89, there is no tag for 0.12-98 so I don’t know how to find the same code that was released, and 0.12-89 looks to have some other bugs that don’t actually occur so I assume they have since been fixed.

### Versions & Modlist
* Minecraft 1.12.2
* Minecraft Coder Pack 9.42
* Forge Mod Loader 8.0.99.99
* Minecraft Forge 14.23.5.2854
* Waila (HWYLA) 1.8.26
* Just Enough Items 4.16.1.301
* Immersive Engineering 0.12-98

**Comment by BluSunrize** [comment]
1.12 is no longer supported.
