### ISSUE TITLE
Placing/breaking a dirt in/near a redstone wire causes client crash.

### ISSUE THREAD

**Issue by isNaN** [BluSunrize/ImmersiveEngineering#4599]
### Description of the issue:
Me and a friend were building a mobfarm, I was outlaying some design, placing/removing dirt. When I got near a wire, we were both kicked, client crashed with "Error: Tesselating block model" and neither can join the server again. 

### Crashlog:
https://pastebin.com/Jr4biW6S

### Versions & Modlist
Forge: forge-35.1.29
IE: ImmersiveEngineering-1.16.4-4.1.2-129

**Comment by malte0811** [comment]
This is not actually related to the RS wires, it's caused by woorden posts. To fix it you can either update to build 130 (released around the time when you made this issue) or, if that's not easily possible, disable smooth lighting (should stop the crash) and break the posts you're using.
