### ISSUE TITLE
Missing Herbicide Manual entry

### ISSUE THREAD

**Issue by tavanuka** [BluSunrize/ImmersiveEngineering#4602]
### Description of the issue:
no issue. just add the Herbicide Manual entry so you dont forget!

**Comment by UnseenAcademical** [comment]
Is it still possible to make herbicide? Checking in JEI it doesn't seem to have a recipe.

**Comment by BluSunrize** [comment]
Yep, the recipe got lost in transition to JSON recipes. This is fixed for future releases, but until then, you can use this datapack created by a community member to restore the recipe:

https://cdn.discordapp.com/attachments/270295745230405643/803190358572924938/Herbicide.zip
