### ISSUE TITLE
Crash with create deployer 

### ISSUE THREAD

**Issue by benbenlaw** [BluSunrize/ImmersiveEngineering#4604]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
after placing a create deployer 

### Crashlog:
https://pastebin.com/5Urg3E0z

### Versions & Modlist
minecraft: 1.16.5
forge: 36.0.1
Immersive: 4.2.0-130
create: 1.16.3_v0.3b

Thank you for reporting issues, without people reporting them, they wouldn't get fixed. You're helping contribute to this mod and that is much appreciated <3

**Comment by ClaudiusMinimus** [comment]
I see the issue is closed, but where is the fix?
Thank you,
CM

**Comment by ClaudiusMinimus** [comment]
My bad, I see you have patched it. Thanks!

**Comment by BluSunrize** [comment]
For anyone else looking:
Grab the new version from CurseForge.
