### ISSUE TITLE
bad math on updateComparatorValues() for EnergyMeterTileEntity

### ISSUE THREAD

**Issue by Bucky420** [BluSunrize/ImmersiveEngineering#4606]
on line https://github.com/BluSunrize/ImmersiveEngineering/blob/d5a87afba87b49ed97bdbaaf46edd6fd8e0ffb8b/src/main/java/blusunrize/immersiveengineering/common/blocks/metal/EnergyMeterTileEntity.java#L310

if i put the power down to just below 16 for hv cables witch can do 32 the Comparator outputs 14 but any thing above 16k and the redstone signal is just fully on due to the math deviding by 2 for unknown reasons.

**Comment by BluSunrize** [comment]
...what?
Do you have a test setup or smth?

**Comment by malte0811** [comment]
I would be interested in a broken setup as well. That line is correct as far as I can tell: If you're using all wires at full capacity, the amount of power going through the "shunt" connection in the current transformer is half of the sum of the total wire capacities. Any "single FE" that enters through some wire uses two FE of wire capacity in total: 1 on the wire it enters the CT through, 1 on the wire it leaves through.

**Comment by Bucky420** [comment]
you can test for your self it is fully 15 redstone singal at 16k fe/t
im on atm6 atm working on my massave power setup so im still on going a test im making a current devider with connectors splitting 16k for each transformer ill post pics soon

**Comment by malte0811** [comment]
I see the problem, I did not update the code when I added the concept of "connection points".

**Comment by BluSunrize** [comment]
I still think that hte description in the original post is dreadful, and I'd ask that you use the issue template next time and provide pictures. Be better.

**Comment by Bucky420** [comment]
if i make a twitch vod can i skip the templet?  i can make a vod of this soon :) if u need version info or stuff like that i didnt know you would need it for this issue. if u cant fix it with out that let me know

**Comment by BluSunrize** [comment]
No, the template exists to be filled out, that's why I wrote it.

Also, don't close an issue that's still being investigated and has a developer assigned, thanks. I'll let Malte deal with resolving the issue.
