### ISSUE TITLE
Crusher stopped functioning after putting a stack of Ores inside

### ISSUE THREAD

**Issue by ViJeitTi** [BluSunrize/ImmersiveEngineering#4607]
on the 4.2.0-130, after updating my survival from the 4.1.2-129, I manually dropped a stack of coal ore in the crusher, it broke 12 blocks and it stopped working, I threw myself to recover the ones that did not break and threw them again, but also only broke about 12 more blocks.

I apologize for my bad english
translated in google translator

**Comment by Nachtflame** [comment]
Also experiencing this issue when manually dropping items in.  Have noticed that feeding them in by Hopper seems to work fine.
Issue persists even after breaking/reforming the machine.

**Comment by Theoretical-Enday** [comment]
I also have the same problem. After restarting the server, all the connections will disappear, but the machine will operate as usual
ImmersiveEngineering-1.16.5-4.2.0-130

**Comment by Murph2** [comment]
experiencing this exact same issue, i found a solution with a dropper with a redstone timer
