### ISSUE TITLE
[1.12] Cables won't transmit power (?)

### ISSUE THREAD

**Issue by Theworldofaffe** [BluSunrize/ImmersiveEngineering#4609]
### Description of the issue:
For some reason some of the cables in my world have stopped transmitting power. I have no idea why, but I doubt it has to do with lack of energy, because I have connected 2 diesel generators, and they won't fix the problem (It's only a couple of medium-sized multiblocks and around 3 000 IF/t for the big machines). Not all my machines are without power (In specific, my pumpjack and distillation tower still works), only my newest machines won't charge. The connectors that transmit power from my generators have power, but no others, not even the ones connected to the machines that actually get power and actively use it (Does it make a difference that my power grid looks like a spider web?). This really destroys my experience, and I think most people get why.

### Versions & Modlist

- Forge V. 14.23.5.2847
- Immersive engineering V. 0.12-98
- Immersive Petroleum V. 1.1.9
- Immersive Intelligence V. 0.1.1
- Immersive Posts V. 0.2.1
- Immersive Railroading V. 1.8.0
- Immersive Tech V. 1.3.10
- Better Builder's Wands V. 0.13.2.271+599751...
- Chisel V. 1.0.2.45
- CTM V. 1.0.2.31
- JourneyMap V. 5.7.1
- JEI V. 4.16.1.301
- Pam's HarvestCraft V. zg (?)
- Questionably Immersive V. 0.1.0
- Railstuff V. 0.2.5
- Track API V. 1.2
- Universal Mod Core V. 1.0.1

**Comment by BluSunrize** [comment]
1.12 is no longer supported.

**Comment by Theworldofaffe** [comment]
Awww
