### ISSUE TITLE
[world save corruption] Switching between single player worlds deletes wire connections

### ISSUE THREAD

**Issue by cobra** [BluSunrize/ImmersiveEngineering#461]
This is a very serious bug, DELETING all connections in a world.

Switching between two worlds causes the saved connections to not get loaded in some cases, which in turn deletes all these connections forever.
The current master branch as of 3732c6c05279b9b7b0995bd7abfdb83523a5a12f and earlier, even back to 0.2.3, is broken for sure **and should not be used with two different singleplayer worlds without relaunching minecraft before switching.**

How to reproduce:
1. create a world ("A"). Log: 
````
[Server thread/INFO] [ImmersiveEngineering]: WorldData loading
[Server thread/INFO] [ImmersiveEngineering]: WorldData not found
````
2. add connectors, wire them.
3. pause, save and quit to title.
4. create another world ("B"). Log doesn't show anything related to IE's WorldData.
5. add connectors, wire them.
6. pause, save and quit to title.
7. load world A. Log doesn't show anything related to IE's WorldData. Wires are present.
8. pause, save and quit to title.
9. load World B. Log doesn't show anything related to IE's WorldData. Wires are present.
10. pause, save and quit to title.
11. quit game.
12. launch MC again.
13. load world A. Log:
````
[Server thread/INFO] [ImmersiveEngineering]: WorldData loading
[Server thread/INFO] [ImmersiveEngineering]: WorldData retrieved
````
Wire are present.
14. pause, save and quit to title.
15. load World B. Log doesn't show anything related to IE's WorldData. Wires are MISSING.
16. pause, save and quit to title.
17. load World A. Log doesn't show anything related to IE's WorldData. Wires are present.
18. pause, save and quit to title.
19. quit game.
20. launch MC again.
21. load world B. Log:
````
[Server thread/INFO] [ImmersiveEngineering]: WorldData loading
[Server thread/INFO] [ImmersiveEngineering]: WorldData not found
````
Wires are still missing. Who would've thought.
22. Swear and shake fist.

Version used for testing this: current master branch, 3732c6c05279b9b7b0995bd7abfdb83523a5a12f. Minimal mod setup: CodeChickenCore, NEI, IE, nothing else. Launched by multiMC.

**Comment by theunkn0wn1** [comment]
Having difficulty reproducing, it appears that 0fbca858e93005bc304e171d902488e6279007ca and earlier are unaffected.

Steps taken to reproduce:
[1]Created two new worlds
[2]in the first world placed two wire conenctors upon a stone platform, and connected them
[3]loaded second world and repeated step 2
[4]reloaded initial world, and observed wire connectivity

It may be something you did @cobra, based ton you where the last person to make any commits since 0fbca858e93005bc304e171d902488e6279007ca that changed anything.

**Comment by cobra** [comment]
@theunkn0wn1 you wrote your reply before I published my repro setup, didn't you? (just to be sure.) Also, I can't really have broken anything with these commits, I didn't touch any code related to this, it was just CoFH API stuff.

**Comment by theunkn0wn1** [comment]
yep, before you pushed your repo setup. Also, I crossed out my finger pointing as i did not intend for that part to be part of my initial reply  (sorry).

**Comment by cobra** [comment]
Tested again. 0fbca85 is broken. Going further back.

**Comment by theunkn0wn1** [comment]
OK, 3de3b44 has this bug testing with @cobra's steps.

**Comment by cobra** [comment]
Committed and pushed a fix for this - I couldn't find any need for this field, so I deleted it and all usages. I'll PR that later unless someone finds an issue with this solution.
