### ISSUE TITLE
[1.16.5] [1.16.5-4.2.0-130] Config option to disable Industrial Hemp Seed drops from Tall Grass

### ISSUE THREAD

**Issue by Calendis** [BluSunrize/ImmersiveEngineering#4611]
### Description of the issue:
There is no config option to disable hemp seeds dropping from breaking grass.

### Versions & Modlist
Minecraft: 1.16.5
IE Version: 1.16.5-4.2.0-130
Forge version: 36.0.0

IE is the only mod present

**Comment by BluSunrize** [comment]
Why is such a config required? Hemp is a key part to IE's infrastructure, I see no reason to remove it.

**Comment by mindforger** [comment]
alternate obtain path for modpacks I'd guess?

**Comment by Calendis** [comment]
> Why is such a config required? Hemp is a key part to IE's infrastructure, I see no reason to remove it.

I understand your logic that having this config option when playing with only IE would break the mod. The other commenter is correct that I'm setting up a modpack. Understandable if you would rather not add this option. Do you know of a third-party mod that controls grass drops, or do you know if it is possible for me write a mod that overrides grass drops?

**Comment by BluSunrize** [comment]
I investigated a config option to add this. As far as I can tell it's not possible, because configs load *after* the grass drop modification.
Forge has a certain order in which these things are done, so I'm afraid this doesn't look viable.

**Comment by Milkdrop** [comment]
@Calendis @BluSunrize I'm sorry for necro-ing this, but I just wanted to leave this solution here in case anyone else is still looking to do this: You can just use the CraftTweaker mod, simply create a script containing:

`loot.modifiers.removeByName("immersiveengineering:hemp_from_grass");
loot.modifiers.removeByName("immersiveengineering:hemp_from_tall_grass");`

And grass should no longer drop industrial hemp 😊 This is for version 1.20, it should work for any other versions but the syntax might need some tweaking depending on how CraftTweaker wants things to be written
