### ISSUE TITLE
1.16.4 [Request] Applied Energistics 2 certus quartz in Core Sample veins

### ISSUE THREAD

**Issue by chef-boyarcheeze** [BluSunrize/ImmersiveEngineering#4612]
### Description of the issue:
In at least minecraft 1.12.2 versions of IE, quartz veins dug up by the excavator would also contain Certus quartz, as well as Nether quartz. As of IE versions in minecraft 1.16.4 this is no longer the case.

### Versions & Modlist
minecraft 1.12.2: 
IE version: 1.12.2-0.12-92
Forge version: 1.12.2-14.23.5.2854
minecraft 1.16.4:
IE version: 1.16.4-4.1.2-129
Forge version: 1.16.4-35.1.37

**Comment by BluSunrize** [comment]
You can add these things via a Datapack. All IE veins are datapack driven.

The reason I didn't put it in by default is because the vein is named "Mephitic Quarzite" and only exists in the nether, where certus quarz usually isn't found.
