### ISSUE TITLE
[1.16.4] No light from Floodlights or powered lanterns

### ISSUE THREAD

**Issue by optmisticnihilist** [BluSunrize/ImmersiveEngineering#4613]
Troubleshooting done:
Had Redstone signal on floodlight (trying both inverted and noninverted with screwdriver) and lantern.
Using LV cable directly connecting to floodlight and lantern.
Verified nonpowered IE lanterns worked. 
Not using Optifine.
Tested with TotalDarkness disabled.

Modlist
Architectury API (Forge) architectury-1.3.81-forge.jar
Ars Nouveau ars_nouveau-1.16.4-1.10.6.jar
Better Advancements BetterAdvancements-1.16.4-0.1.0.103.jar
Better Badlands Better-Badlands-1.16.4-2.0.0.jar
Blame (Forge) blame-1.8.1.jar
Blood Magic BloodMagic-1.16.3-3.0.5-10.jar
Botany Pots BotanyPots-1.16.4-6.0.7.jar
Botany Trees BotanyTrees-1.16.4-2.0.4.jar
Caelus API (Forge) caelus-forge-1.16.4-2.1.0.2.jar
CodeChicken Lib 1.8.+ CodeChickenLib-1.16.4-3.5.0.401-universal.jar
Corail Backpack Corail-Backpack-1.16.4-030.jar
Corail Tombstone tombstone-1.16-6.2.3.jar
Create Plus createplus-1.16.4_v0.3.jar
Curios API (Forge) curios-forge-1.16.4-4.0.3.3.jar
Curious Elytra (Forge) curiouselytra-forge-1.16.3-4.0.0.1.jar
Cursed Blade cursedblade-1.3.jar
Cyclops Core CyclopsCore-1.16.4-1.9.5.jar
Dark Utilities DarkUtilities-1.16.4-7.0.3.jar
DataPack Anvil dpanvil-1.16.3-1.0.3.jar
Elemental Craft elementalcraft-1.16.4-2.5.0.jar
End Remastered EndRemastered-R34.jar
Ender Storage 1.8.+ EnderStorage-1.16.4-2.7.0.161-universal.jar
Engineer's Decor engineersdecor-1.16.4-1.1.5.jar
EvilCraft EvilCraft-1.16.4-1.0.5.jar
ForgeEndertech ForgeEndertech-1.16.4-7.0.9.0-build.0032.jar
FTB Chunks ftb-chunks-1604.2.2.57.jar
FTB GUI Library ftb-gui-library-1604.1.1.26.jar
FTB Teams ftb-teams-1604.1.0.13.jar
GeckoLib forge-1.16.4-geckolib-3.0.0.jar
Item Collectors itemcollectors-1.0.9-mc1.16.4.jar
Item Filters item-filters-1604.2.2.19.jar
Just Enough Resources (JER)JustEnoughResources-1.16.4-0.12.0.103.jar
Linking Bookslinkingbooks-1.16.4-forge-0.1.0.1.jar
Mahou Tsukai mahoutsukai-1.16.4-v1.27.1.jar
Mystical Adaptations MysticalAdaptations-1.16.4-1.0.jar
Pam's HarvestCraft 2 - Food Core pamhc2foodcore-1.16.3-1.0.0.jar
Placebo Placebo-1.16.3-4.3.3.jar
Repurposed Structures (Forge) repurposed_structures-1.16.4-2.3.3.jar
Ring of Attraction [FORGE] RingOfAttraction-1.16.4-1.2.11.jar
Ring of Growth [FORGE] RingOfGrowth-1.16.4-1.2.6.jar
Ring of Repair [FORGE] RingOfRepair-1.16.4-1.2.10.jar
Runelic Runelic-1.16.4-6.0.2.jar
Slime Golem SlimeGolems-1.16.4_04.jar
Spice of Life: Carrot Edition solcarrot-1.16.3-1.9.8.jar
Storage Drawers StorageDrawers-1.16.3-8.2.1.jar
Swords of the End 1.2.1 Swords of the End-1.2.0.jar
Theurgy theurgy-1.0.5.jar
Trash Cans trashcans-1.0.6-mc1.16.4.jar
Abnormals Core abnormals_core-1.16.4-3.0.6.jar
Advanced Hook Launchers AdHooks-1.16.4-6.1.2.0-build.0027.jar
Akashic Tome AkashicTome-1.4-15.jar
Apotheosis Apotheosis-1.16.3-4.4.1.jar
AppleSkin AppleSkin-mc1.16.2-forge-1.0.14.jar
Astral Sorcery astralsorcery-1.16.4-1.13.9.jar
Auto Dropper AutoDropper-1.16.3-7.0.0.jar
Automatic Doors automaticdoors_1.16.4-1.4.jar
AutoRegLib AutoRegLib-1.6-47.jar
Bamboo 2: Modded Boogaloo bamboo2-1.16.4_0.3.jar
Bamboo Spreads bamboospreads_1.16.4-1.1.jar
Basic Nether Ores [Forge/Fabric] BasicNetherOres-1.16.4-5.4.0.jar
Baubles - Reborn? baubles-1.8.5-1.16.4.jar
Better Animal Models betteranimals-1.16.4-5.4.1.jar
Better Animals Plus betteranimalsplus-1.16.4-10.1.0.jar
Better Blast Furnace BetterBlast.jar
Better Muffling Better Muffling-1.16.3-1.0.2.jar
BetterEnd (Forge) betterendforge-1.16.4-1.4.0.jar
Bookshelf Bookshelf-1.16.4-9.3.24.jar
Caged Mobs cagedmobs-1.16.4-1.2.6.jar
Carry On carryon-1.16.3-1.15.1.7.jar
Clay Conversion clayconversion-1.16.x-v1.5.jar
CleanCut cleancut-mc1.16-2.2-forge.jar
Cloth Config API (Forge) cloth-config-forge-4.1.3.jar
Clumps Clumps-6.0.0.13.jar
Collective collective-1.16.4-1.53.jar
Construction Wand constructionwand-1.16.2-1.7.jar
Controlling Controlling-7.0.0.11.jar
Cooking for Blockheads CookingForBlockheads_1.16.3-9.2.2.jar
Crafting Station craftingstation-4.1.1.jar
Create create-mc1.16.3_v0.3e.jar
Cucumber Library Cucumber-1.16.4-4.1.5.jar
Cycle Paintings cyclepaintings_1.16.4-1.4.jar
Darker Loading Screen darkerloadingscreen-2.2.jar
Demagnetize demagnetize-forge-1.16.2-1.2.2.jar
Drawers Tooltip DrawersTooltip-1.16.2-2.1.0.jar
Eidolon eidolon-0.2.7.jar
Elements of Power ElementsOfPower-1.16.3-0.10.15-alpha.jar
EnderChests enderchests-1.16-1.7.5.jar
EnderTanks endertanks-1.16-1.9.3.jar
Extra Golems extragolems-11.2.0.jar
Farming for Blockheads FarmingForBlockheads_1.16.3-7.2.1.jar
Flat Bedrock flatbedrock-1.16.4-1.1.6.jar
Forbidden and Arcanus forbidden_arcanus-1.16.4-1.0.0.jar
FTB Backups ftb-backups-2.1.1.6.jar
FTB Quests ftb-quests-1604.1.1.21.jar
Game Menu Mod Option GameMenuModOption-1.16.4-1.4.jar
Guard Villagers guardvillagers-1.16.4-1.1.8.jar
Guide-API Village and Pillage Guide-API-VP-1.16.4-2.2.1.jar
HarvestWithDispenser HarvestWithDispenser-B3.0.0.jar
Health Overlay HealthOverlay-1.16.4-2.1.7.jar
Hwyla Hwyla-forge-1.10.11-B78_1.16.2.jar
Immersive Engineering ImmersiveEngineering-1.16.4-4.1.2-129.jar
Inventory Tweaks Renewed invtweaks-1.16.4-1.0.1.jar
Iron Chests ironchest-1.16.4-11.2.10.jar
Iron Shulker Boxes ironshulkerboxes-1.16.4-5.1.11.jar
JEI Enchantment Info JEIEnchantmentInfo-1.16.4-1.2.1.jar
JEI Integration jeiintegration_1.16.4-6.1.1.11.jar
JEI Professions jei-professions-1.0.0-1.16.4.jar
Jump Over Fences [Forge] jumpoverfences-1.16.4-1.0.1.jar
Just Enough Items (JEI) jei-1.16.4-7.6.1.65.jar
Light Overlay (Rift/Forge/Fabric) light-overlay-5.6.1.jar
Lootr lootr-1.16.4-0.0.4.12.jar
Mana and Artifice mana-and-artifice-1.2.1.9.jar
More Dragon Eggs moredragoneggs-1.4.jar
Mouse Tweaks MouseTweaks-2.13-mc1.16.2.jar
Mystical Agradditions MysticalAgradditions-1.16.4-4.1.3.jar
Mystical Agriculture MysticalAgriculture-1.16.4-4.1.4.jar
Mystical Customization MysticalCustomization-1.16.4-2.1.2.jar
Nature's Compass NaturesCompass-1.16.4-1.8.6.jar
No Increasing Repair Cost NoIncreasingRepairCost-1.16.4-1.0.0.jar
ObserverLib observerlib-1.16.4-1.5.1.jar
Overworld Two (Forge) overworld_two-1.0-Forge-1.16.4.jar
Pam's HarvestCraft 2 - Crops pamhc2crops-1.16.3-1.0.1.jar
Pam's HarvestCraft 2 - Food Extended pamhc2foodextended-1.16.3-1.0.0.jar
Pam's HarvestCraft 2 - Trees pamhc2trees-1.16.3-1.0.0.jar
Patchouli Patchouli-1.16.4-48.jar
Quick Harvest Quick Harvest-1.16.4-1.1.3.jar
Reap Mod reap-1.16.4-1.0.3.jar
Refined Pipes refinedpipes-0.5.jar
Regrowth Regrowth-1.16.4-1.16.4-1.35.0.18.jar
ShetiPhianCore shetiphiancore-1.16-3.8.4.jar
Slimy Chunks (Forge) SlimyChunks(1.16.4)-1.0.3.jar
Smaller Nether Portals smallernp_1.16.4-1.4.jar
Stack Refill stackrefill_1.16.4-1.1.jar
Straw Golem Reborn strawgolem-1.16-1.9.jar
SwingThroughGrass swingthroughgrass-1.16.4-1.5.3.jar
The Abyss: Legacy TheAbyss 2.0.0 1.16.4.jar
The Magic Doorknob MagicDoorknob-1.16.4-0.1.3.459.jar
The Magic Mirror MagicMirror-1.16.4-0.0.8.458.jar
Tome of Blood tomeofblood-1.16.4-1.0.3.jar
Tool Leveling+ toolleveling-1.16.2-1.1.1.jar
ToroHealth Damage Indicators torohealth-1.16.4-forge-4.jar
Total Darkness totaldarkness-1.2-1.16.3.jar
Tree Harvester treeharvester_1.16.4-2.0.jar
Upstream upstream-1.0.jar
Vampires Need Umbrellas VampiresNeedUmbrellas-1.16.4-1.1.jar
Vampirism - Become a vampire! Vampirism-1.16.4-1.7.3.jar
Vampirism Integrations VampirismIntegrations-1.16.4-1.5.0.jar
Vein Mining (Forge) veinmining-forge-1.16.4-0.6.jar
Vine Collector vinecollector-1.16.4-1.0.jar
Waila Harvestability WailaHarvestability-mc1.16.2-forge-1.1.13.jar
Wall-Jump! [FORGE] walljump-forge-1.16.4-1.3.6.jar
Waystones Waystones_1.16.3-7.3.1.jar
Whisperwoods whisperwoods-1.16.4-2.0.0.jar
YUNG's API (Forge) YungsApi-1.16.4-Forge-3.jar
YUNG's Better Caves (Forge) BetterCaves-Forge-1.16.4-1.1.1.jar
YUNG's Better Mineshafts (Forge) BetterMineshafts-Forge-1.16.4-2.0.1.jar

![2021-01-28_08 29 16](https://user-images.githubusercontent.com/78157254/106172974-08a5cf80-6159-11eb-9461-ffc6894ee6b4.png)

**Comment by BluSunrize** [comment]
Those are LV relays. They can not accept energy from a capacitor. You want connectors. Please read the manual entry on wiring.

**Comment by optmisticnihilist** [comment]
Yup that was the issue. I have used the mod before but was overlooking the connector type while testing the pack. Thank you.
