### ISSUE TITLE
[1.16.5] Magnets and Conveyor Belts

### ISSUE THREAD

**Issue by thaelina** [BluSunrize/ImmersiveEngineering#4614]
### Description of the issue:
When using SimpleMagnet, and a couple other magnet mods on 1.16 that I tried, they work as intended while items are on conveyor belts but the moment when the item touches the block where it's being input the magnet picks it up instead of inputting the item.

### Versions & Modlist
These are the only mods installed

minecraft-1.16.5
forge-1.16.5-36.0.1
ImmersiveEngineering-1.16.4-4.1.2-129
simplemagnets-1.0.12-mc1.16.5
supermartijn642configlib-1.0.1a-mc1.16 (simplemagnet lib)

Edit 1:
Just saw there was an update for 1.16.5 for IE and swapping to ImmersiveEngineering-1.16.5-4.2.0-130 the same issue exists.

I also tested using the covered conveyors and the item enters the target block just fine, presumably since the covering stops the item from being pulled away. It would be nice if the non covered belts worked as well but for now I have a workaround.

Edit 2:
To add things on, when I toss an item onto the conveyor, the covered belt on the end stops the magnet from picking up the item. However when my cloche outputs onto the belt, when the items reach the end of the conveyor, the magnet picks up the items when they hit the chest on the end, covered or not.

**Comment by thaelina** [comment]
Just saw there was an update for 1.16.5 for IE and swapping to ImmersiveEngineering-1.16.5-4.2.0-130 the same issue exists.

**Comment by BluSunrize** [comment]
Please report this to SimpleMagnets and inform them that we apply a specific NBT tag to the item entities to prevent them from being moved: "PreventRemoteMovement"

The code snippet for that looks something like this:
```java
CompoundNBT data = entity.getPersistentData();
if(!data.getBoolean("PreventRemoteMovement"))
	data.putBoolean("PreventRemoteMovement", true);
```

Please relay this to the developer of SimpleMagnets, and inform them that this is the NBT key that multiple other mod devs have agreed on to use, to prevent movement by magnets. Blood Magic, EnderIO and Botania all have a check for this, and SimpleMagnets should implement it too.
