### ISSUE TITLE
[1.16.5]The toggle shader crashes occasionally

### ISSUE THREAD

**Issue by EnterFor** [BluSunrize/ImmersiveEngineering#4617]
### Description of the issue:
After switching the shader, there will be a bar reading process, which will eventually crash.
It doesn't happen 100 percent, it happens occasionally, but it bothers me....

### Crashlog:
https://paste.ubuntu.com/p/SZGRCqFb9H/

### Versions & Modlist
IE: 1.16.5-4.2.0-130
Forge: 36.0.9
The Mod list:
Included in the Crashlog

**Comment by malte0811** [comment]
Optifine is not supported.
