### ISSUE TITLE
[1.16.5] Manual has incorrect information on outputting from tanks

### ISSUE THREAD

**Issue by PeanutbutterWarrior** [BluSunrize/ImmersiveEngineering#4618]
### Description of the issue:
In the Engineer's Manual, under the tank section in construction it says 'Applying a redstone signal to the bottom centre block will make the tank output automatically'. This is not the behaviour seen in game, applying a redstone signal stops the tank outputting. The tank also seems to require a signal for other tanks to input into it, which is undocumented in the manual.

### Versions & Modlist
ImmersiveEngineering 1.16.5-4.2.0-130
Forge 1.16.5 - 36.0.13

**Comment by BluSunrize** [comment]
I can reproduce the first bit. Tanks are indeed automatically outputting, currentl, and so are silos. I will fix this momentarily, but this fix will only apply to Silos and Tanks newly created, after installing the fixed version.
Basically, they should have inverted redstone control by default, and they remember that state, so you have to:
1) Make a new tank
2) Use a screwdriver on the bottom block

**Comment by BluSunrize** [comment]
I am however unable to reproduce the second part of this issue:

> The tank also seems to require a signal for other tanks to input into it, which is undocumented in the manual.

Can you produce a test setup of this, with some screenshots? Inputting works perfectly fine for me.
