### ISSUE TITLE
[1.16.5] Crash due to right click event

### ISSUE THREAD

**Issue by WhitePhant0m** [BluSunrize/ImmersiveEngineering#4619]
### Description of the issue:
Server/Client crashes due to right click event coming from [Modular Routers](https://www.curseforge.com/minecraft/mc-mods/modular-routers) activator module.
Crash does not happen in IE version 4.1.2-129

### Versions: Forge - 36.0.13 | IE - 4.2.0-130

**Comment by malte0811** [comment]
Duplicate (kind of, at least fixed by the same fix) of #4604

**Comment by WhitePhant0m** [comment]
Oh, sorry, didn't see that one, I only searched open issues
