### ISSUE TITLE
[1.16.4-1.16.5] Powered Lantern doesn't work with Optifine

### ISSUE THREAD

**Issue by Tortyash** [BluSunrize/ImmersiveEngineering#4621]
IE version: 1.16.4-4.1.2-129 and 1.16.5-4.2.0-130
Optifine version: 1.16.5_HD_U_G6 and 1.16.5_HD_U_G7_pre4
Forge version: 35.1.37 and 36.0.1
![2021-01-29_20 42 57](https://user-images.githubusercontent.com/45497877/106365395-00f35000-633e-11eb-9d77-a85541b5ac8c.png)

**Comment by Tortyash** [comment]
For comparison - Floodlight works but Powered Lantern does not
![2021-01-30_21 26 30](https://user-images.githubusercontent.com/45497877/106366025-e28f5380-6341-11eb-8dc5-57621624e839.png)

**Comment by BluSunrize** [comment]
Optifine is not supported.

**Comment by oddsoul** [comment]
will this change at any point?

**Comment by oddsoul** [comment]
> Optifine is not supported.

will this change?

**Comment by BluSunrize** [comment]
No.

**Comment by oddsoul** [comment]
> No.

Yeah it's a real shame that have make it closed source
