### ISSUE TITLE
[1.16.5] Unable to obtain an Outfitter Villager

### ISSUE THREAD

**Issue by MuteTiefling** [BluSunrize/ImmersiveEngineering#4627]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
Outfitter Villagers appear to be unobtainable. None of the banners currently in game are accepted as a POI by a villager without a profession.

I've tried the following Banner Patterns: 

- Hammer
- Plating
- Ornate Frame
- Wooden Paneling
- Windmill
- Wolf (left, right, center)

The villagers will claim other POIs without issue, but a banner, either placed on the ground or on the wall, is not accepted. 

I had thought that there was another banner pattern that uses a shader, but I cannot find any way to create these. They don't show in the Engineer's Workbench with the Banner Pattern Blueprint, and they don't appear to craft with the vanilla shapeless recipe of 1 paper and 1 shader. 

### Crashlog:
No crash

### Versions & Modlist
MC: 1.16.5
Forge: 36.0.13
Mods:

- create-mc1.16.3_v0.3e
- createaddition-1.16.4-20210202a
- ImmersiveEngineering-1.16.5-4.2.1-131
- jei-1.16.4-7.6.1.66
- Mekanism-1.16.4-10.0.19.446
- MekanismGenerators-1.16.4-10.0.19.446

**Comment by BluSunrize** [comment]
You need to use a shader banner, not a normal banner.

**Comment by MuteTiefling** [comment]
Alright, well for anyone else that comes looking, apparently Shader Banners are crafted by right clicking a banner with a shader, unlike other banners which are made with the Loom.

**Comment by BluSunrize** [comment]
Yes, and it says that you can do that in the Manual, on the page about shaders. All you gotta do is read ;)
