### ISSUE TITLE
Dedicated sever crash when breaking grinder multiblock.

### ISSUE THREAD

**Issue by Deckee** [BluSunrize/ImmersiveEngineering#463]
http://pastebin.com/7PfVcJeK
When the multiblock is broken the sever crashes and all clients are kicked.
Fastcraft is true

**Comment by cobra** [comment]
Can you reproduce this? Maybe try it in a singleplayer world to keep your server running. Do you have more details on the circumstances?

**Comment by Deckee** [comment]
This crash only works on a Dedicated Server and only crashes when muilti block is powered.

**Comment by Deckee** [comment]
I know that ie has gregtech compat but i think that's for gt 5.07.x not the community ports 5.08 and 9

**Comment by Deckee** [comment]
My severs has crashed 6 or 7 times, one sever machine is running win and the other one is Linux

**Comment by Deckee** [comment]
it now crashes in single player
log file: http://paste.ee/p/KPHox
no crash report was written.

**Comment by cobra** [comment]
You can disable GregTech compatibility in the config file as a workaround, I *think* this should avoid these crashes completely. Obviously, you'll lose IE's GT compatibility.
I don't know anything about GT's api and the differences between 5.07 and 5.08/9, so I can't help you with the cause itself. I also don't know which GT version is targeted by IE, as there's no version information. But thank you for the information so far!

**Comment by cobra** [comment]
That looks like the same crash as #370, btw.

**Comment by Deckee** [comment]
I talked with my sever members and they said that they wouldn't use the multiblock grinder. That should do for now.
