### ISSUE TITLE
Hopperhocks can suck items from conveyor belts

### ISSUE THREAD

**Issue by LeoBeliik** [BluSunrize/ImmersiveEngineering#4631]
### Description of the issue:
Hopperhocks from Botania can suck items from normal or covered conveyor belts.

### Versions & Modlist
Forge: 36.0.13
IE: 1.16.5-4.2.1-131
Botania: 1.16.4-411

**Comment by malte0811** [comment]
Report that to Botania, there doesn't seem to be any way of stopping the hopperhock from picking up an item entity in its range. I would suggest using the same mechanism as for the magnet ring (`PreventRemoteMovement` NBT tag).
