### ISSUE TITLE
[1.16] Tungsten from Bluepower gets Multiplied too much

### ISSUE THREAD

**Issue by Flexico** [BluSunrize/ImmersiveEngineering#4633]
When smelted normally, Tungsten Ore from the Bluepower mod becomes a nugget -- but when smelted in an Arc Furnace it becomes two INGOTS, which is a multiplier of x18 instead of x2. You'll probably want to make an exception for this particular ore to make nuggets instead!

**Comment by BluSunrize** [comment]
Maybe Bluepower shouldn't comletely disregard the convention of "1 ore -> 1 ingot" then. They could easily acomplish this by having their tungsten ore *not* tagged as `ores/tungsten` but instead `nugget_ores/tungsten`.

In fact, why don't you go redirect them to this marvelous spreadsheet that KnightMiner, SkySom, myself and the Mekanism team worked out, naming conventions & recipe outputs for metals:

![](https://i.imgur.com/NB6KbaP.png)

**Comment by Flexico** [comment]
Ah cool, I'll pass on this info!
