### ISSUE TITLE
[1.16.5][Compat] CC:T getBundledInput does not work

### ISSUE THREAD

**Issue by dierks-m** [BluSunrize/ImmersiveEngineering#4634]
### Description of the issue:
`rs.getBundledInput()` does not properly return the sum of all color values, but instead always `0`.
`rs.testBundledInput()` does work and indicates there is a signal for the color lightBlue (8), as seen here:
![grafik](https://user-images.githubusercontent.com/6273249/107060300-156c9800-67d7-11eb-8e08-1a88799b9920.png)

### Versions & Modlist
ImmersiveEngineering 1.16.5-4.2.1-131 running on Forge 36.0.13

**Comment by malte0811** [comment]
This is on CCs side: `getBundlednput` is actually a second `getBundledOutput`. Use `testBundledInput` for now.

Edit: Ah, you discovered the workaround already. Reading issues *before* replying to them would be smart.
