### ISSUE TITLE
[1.16.5] charging station and pipes go dark

### ISSUE THREAD

**Issue by Parciwal** [BluSunrize/ImmersiveEngineering#4635]
The problem is, that the charging station and a few pipes are dark (light level 0) for no apperend reason, placing them new has no effect. The problem temporarily disappears if you put a block or fluid next to the block (or waterlog it). But if the chunk is loaded new, the problem comes back. This is the only instance that happend to me and i can't  in­ten­ti­o­nal recreate it, so i can't test it with no other mods. It doesn't really affect any functionalities of the objects, it's just ugly.
By the third screenshot you can see in the subtitles that i just updated the lighting with water.

Screenshots:
![2021-02-05_20 33 47](https://user-images.githubusercontent.com/78496745/107086503-65a92180-67fa-11eb-9b82-847bf2b4b962.png)
![2021-02-05_20 33 53](https://user-images.githubusercontent.com/78496745/107086507-66da4e80-67fa-11eb-866b-7d6742d53bff.png)
![2021-02-05_20 34 05](https://user-images.githubusercontent.com/78496745/107086510-680b7b80-67fa-11eb-9520-3038f5858646.png)

Created crash for modlist:
[crash-2021-02-05_21.42.00-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5935219/crash-2021-02-05_21.42.00-client.txt)

**Comment by Ranniv-M** [comment]
This is happening for me too on the Valhelsia 3 modpack, pipes (with and without scaffolding) seem to have some weird lighting issues with huge spikes in lag when you place items that update the lighting in the chunk.

Crash report was from something else but it has the mod list:
[crash-2021-02-03_10.46.20-fml.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/5938289/crash-2021-02-03_10.46.20-fml.txt)

**Comment by BluSunrize** [comment]
I can only assume this to be a cross-mod interaction issue, but I have no idea what it is.

Unless you can produce a testcase, I don't know if we can debug this any further.

**Comment by sarim** [comment]
I'm also using Valhelsia 3, pipes didn't give me any trouble. But charging station's icon is transparent for some reason. It works/renders correctly when placed in world, but in item form both in world and in inventory / JEI its transparent so I can't see it.
I wonder if that is related to this issue :/

**Comment by moonheart08** [comment]
@BluSunrize After some testing of my own, in a custom pack, the source of the issue appears to be Create. Note I'm not 100% certain of this, but removing create TEs from affected chunks fixed the issue for me. Which is unfortunate as my build was half-create, half-IE.

**Comment by moonheart08** [comment]
I can provide a full mod list and save if needed, which exhibits the behavior simply by placing any full block next to pipes in select chunks.

**Comment by moonheart08** [comment]
Issue still present with the following mod list
```
CodeChickenLib-1.16.5-4.0.2.429-universal.jar
create-mc1.16.5_v0.3.2c.jar
EnderStorage-1.16.5-2.8.0.168-universal.jar
engineersdecor-1.16.4-1.1.14.jar
flywheel-1.16-0.2.0.jar
ImmersiveEngineering-1.16.5-5.0.2-137.jar
ImmersivePetroleum-1.16.5-3.3.0-5.jar
immersiveposts-1.16.5-4.1.1.jar
jei-1.16.5-7.7.1.115.jar
redstonepen-1.16.5-1.0.6.jar
rsgauges-1.16.4-1.2.11.jar
StorageDrawers-1.16.3-8.2.2.jar
theoneprobe-1.16-3.1.4.jar
```

Seems most frequent in chunks where create and IE meet, but chunks containing only IE blocks also exhibit the problem.

**Comment by moonheart08** [comment]
For some of these blocks, forcing a light update by placing near or over them does not solve the issue, and instead the broken lighting spreads across pipes.

**Comment by DigitalWendigo** [comment]
Same issue here, last update to IE for 1.16.5.
Pipes seem to be the main blocks that are affected by this. 
Not using flywheel. 
I am however using Optifine, which is known to cause tons of issues in and of itself. 
Placing a block (dirt, stone, whatever else) above the 'glitched' out pipe will update the lighting and fix it. 
Enabling smooth lighting will somewhat decrease the glitch's visibility but it will still be noticable. 
Disabling smooth lighting will turn the glitched out pipe completely black.

**Comment by DigitalWendigo** [comment]
Still extensively testing this, switching out mods and messing with several settings. 
It's usually a cross mod incompatability, and in my case the top culprits on the list are the ones most people claim cause overall issues with rendering/lighting when custom tile entities and custom models get involved. 
The main performance mods that are used are:
Optifine. 
Performant. 
Radon.
Better fps render distance. 
Ferrite Core. 

I'll report back on any changes I find when I get a bit more time available for testing.

**Comment by BluSunrize** [comment]
Optifine is not supported.
Neither are most other "performance" mods.

And 1.16.5 is out of support.
