### ISSUE TITLE
[1.16.5] Crusher not operating through full stacks of items

### ISSUE THREAD

**Issue by VictorSohier** [BluSunrize/ImmersiveEngineering#4640]
### Description of the issue:
Upon tossing a stack of more than just a couple processable items into a crusher of the same type, the crusher operates on a few of them and then ceases to function on the stack thrown into it. This too happens when you throw too many single items in at once of the same type. I have a feeling this is in part to do with minecraft's stack clumping mechanic because I can throw many different kinds of processable items into the crusher in rapid succession and it processes through all of them just fine. By the looks of it, orientation does not matter. This was performed on a singleplayer instance of minecraft

### Versions & Modlist
FTB Presents Direwolf20 1.16 version 1.6.1
Forge version 36.0.14
IE version 4.2.1-131
(Also confirmed in a clean install with just Forge and IE)

**Comment by PrincessOfEvil** [comment]
b90620e57c2819b04ebe0dc44f26e2326c12b7e1
Might be fixed in the next version already.

**Comment by ViJeitTi** [comment]
fill the crusher through a hopper, you can make a conveyor belts system.
that will bypass the problem

**Comment by BluSunrize** [comment]
Closing this, since Malte already fixed it for future releases
