### ISSUE TITLE
[1.12.2] java.lang.NullPointerException while connecting ImmersiveEngineering fluid pipes and IndustrialCraft2 fluid pipes

### ISSUE THREAD

**Issue by KodYazanDruid** [BluSunrize/ImmersiveEngineering#4641]
### Description of the issue:
I connected ie fluid pipe with ic2 big steel pipe and game crashed. I can join my world but it crashed immediately.

### Crashlog:
 [Crash Report](https://pastebin.com/sGNqbyg0)

### Versions & Modlist
Minecraft Version: 1.12.2
Immersive Engineering Version: 0.12-98
Industrialcraft Version: 2.8.164-ex112

**Comment by mindforger** [comment]
that is a known problem with ic2 but 1.12 is way out of support

**Comment by BluSunrize** [comment]
1.12 went out of support 8 months ago.
