### ISSUE TITLE
[1.16.5] Jerrycan vanishes from Crafting Window

### ISSUE THREAD

**Issue by Zatorg** [BluSunrize/ImmersiveEngineering#4644]
### Description:
If put my Mining Drill and a Jerrycan in my Player Crafting Window and I put the Jerrycan left and the Drill right, the Jerrycan vanishes when I craft. If I put it on the right it doesn't.

Vanishes:
JD | J=Jerrycan D=Drill
XX | X= empty

Doesn't vanish
DJ
XX

### Versions & Modlist
[1.16.5]

- Forge 36.0.13
- IE 1.16.5-4.2.1-131

**Comment by BluSunrize** [comment]
Should be fixed for next release.
