### ISSUE TITLE
[1.16.5] Missing particle texture for Dynamo and Turrets

### ISSUE THREAD

**Issue by GeorgeOrwell1** [BluSunrize/ImmersiveEngineering#4650]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
Describe what happens, how it affects your game/gameplay and provide screenshots where possible.
When I place and then break the kinetic dynamo, the breaking particles are missing textures. Respectively, if I break the _top part_ of the gun turret or chemthrower turret the breaking particles are black and purple, as seen in the screenshots:
![2021-02-13_15 51 46](https://user-images.githubusercontent.com/72312697/107852969-dad8b000-6e13-11eb-9fe1-48c6862b7a4f.png)
![2021-02-13_15 51 14](https://user-images.githubusercontent.com/72312697/107852983-e9bf6280-6e13-11eb-8d05-dd93350d596c.png)
_Breaking the top block/part of the turrets_
![2021-02-13_15 56 53](https://user-images.githubusercontent.com/72312697/107853035-1d01f180-6e14-11eb-9877-407df285deb2.png)
_Breaking the kinetic dynamo_

### Crashlog:
If your Minecraft instance has crashed, a file will have been generated in the folder `crash-reports` of your minecraft folder. To understand what has happened, we need to know the content of that file. But please don't just put it directly in your report (that makes it hard to read), upload it to a site like [pastebin](http://pastebin.com) or [gist](http://gist.github.com) and put a link in the actual bug report.
No crashlog, but [log](https://pastebin.com/J7BDaThK).

### Versions & Modlist
IE and Forge versions are mandatory. *Note that saying "latest" is **not** valid. Always give the proper version number*
Other mods should be listed (with their versions) in a [pastebin](http://pastebin.com) or [gist](http://gist.github.com) upload. The easiest way to get these lists is a crashlog, you may force one with F3+C.
If your game crashed (see above) you may omit the modlist, but IE and Forge version would still be nice.
In a creative test world with only Forge and Immersive Engineering installed:
ImmersiveEngineering-1.16.5-4.2.1-131
1.16.5 Forge 36.0.22

**Comment by BluSunrize** [comment]
I changed the title to something more readable.
