### ISSUE TITLE
[1.16.5] Garden Cloche glass texture solid

### ISSUE THREAD

**Issue by DavidGodinho** [BluSunrize/ImmersiveEngineering#4652]
### Description of the issue:
The glass of the Garden Cloche is solid making it impossible to see inside. 
![image](https://user-images.githubusercontent.com/23292973/107879767-c4455e00-6ed2-11eb-8991-6599f94fe16d.png)

### Versions & Modlist
IE: ImmersiveEngineering-1.16.5-4.2.1-131
Forge: 36.0.13
Modlist:  [Modlist 1.16.5 pastebin](https://pastebin.com/0eYJYwjE)

Also thanks for the hours of fun with your mod.

**Comment by DavidGodinho** [comment]
Tried loading only forge and Immersive engineering, issue persited.

**Comment by malte0811** [comment]
Known issue, fixed for the next release. For now you can use [this](https://cdn.discordapp.com/attachments/339127815666532352/806076518450855997/IE_fix.zip) resource pack to fix it.
