### ISSUE TITLE
[1.16.5] Crash when placing Redstone Controlled Fluid Valve from Engineer's Decor next to an IE pipe

### ISSUE THREAD

**Issue by maham** [BluSunrize/ImmersiveEngineering#4656]
### Before reporting:
Couldn't find any applicable open or closed issue. ~Duplicating this issue on Engineer's Decor issue page. [link](https://github.com/stfwi/engineers-decor/issues/161)~

### Description of the issue:
Crash to desktop when placing a Redstone Controlled Fluid Valve from Engineer's Decor between an IE Fluid Pipe and a Refinery output. After reconnecting to the server everything seems all right and the valve is still connected.
Update:
I have had this crash once again and this time after placing a pump beside an existing, but not connected, fluid pipe. I rule out Engineers Decor as the source of the issue. Note, still the same version of Forge so the race condition mentioned below is still applicable/possible.
Both crashes occurred when playing on a server.

### Crashlog:
https://pastebin.com/vnsmVUHY

### Versions & Modlist
MC: 1.16.5
Forge: 36.0.13
IE: 4.2.1-131
Engineer's Decor: 1.1.7

**Comment by malte0811** [comment]
Please try updating Forge, there was a race condition in `LazyOptional` that *could* cause this.

**Comment by maham** [comment]
Still waiting for forge update. But as I had the same crash when placing an IE pump next to an IE pipe I rule out Engineer's Decor. Adding this here not to forget it.

**Comment by BluSunrize** [comment]
Why do you need to wait for a Forge update? You should be able to just update on your own and try to reproduce this.

**Comment by maham** [comment]
Well, the problem is that the crash is rather uncommon. I have tried to recreate it at length without success. Both in MP and SP. So far it has happened twice. Both times mentioned above. But I'll update the description to reflect this and we will just have to see if it happens again after an eventual future update of forge at the server where I'm playing.
