### ISSUE TITLE
[1.16.5] Bucket of Potion deletes itself

### ISSUE THREAD

**Issue by ThousandFields** [BluSunrize/ImmersiveEngineering#4657]
When trying to use a Bucket to pick up any potion fluid, the Bucket and 1000mB potion are both deleted. This is on a server, but the same will happen in a singleplayer world with no mods other than IE. This will also continue to happen on the latest (1.16.5-4.2.1-131) version of IE.

Forge version: 36.0.19
IE version: 1.16.5-4.2.0-130
Modlist: https://pastebin.com/j8Cvsyz0

**Comment by malte0811** [comment]
This is actually a Forge issue: our potion fluid can't be filled into buckets, a case that isn't handled correctly in Forge (see linked issue).
