### ISSUE TITLE
[Not Fatal] Floating Hemp

### ISSUE THREAD

**Issue by kd8lvt** [BluSunrize/ImmersiveEngineering#466]
If you trample the farm land under a fully grown Hemp crop, this happens:
https://gyazo.com/1f270b71876ab25636ad73acbfbdaf20
(I'm playing on Modsauce2 v. 2.2.3.0)

**Comment by cobra** [comment]
I can confirm this on 0.5.4, but not on the upcoming 0.6. It has been fixed already.
