### ISSUE TITLE
No fluid-player interaction 

### ISSUE THREAD

**Issue by jamesipod** [BluSunrize/ImmersiveEngineering#4664]
I can run through any IE fluids as if they were not there. They still give the proper potion effects, but there's no swimming/fluid slowdown. 
Using Minecraft 1.16.5, Forge 36.0.42 and IE 1.16.5-4.2.1-131 
Here is a video of it for you:
https://streamable.com/0hv7gm

**Comment by malte0811** [comment]
This is a well-know Forge issue: to make a fluid push players around etc it has to be marked as water. But if we mark our fluids as water you'd be able to use them as water in all recipes, to get water bottles from them, etc. Someone is working on fixing this on the Forge side, but don't expect results from that too soon.
