### ISSUE TITLE
[1.16.5] Metal press not accepting power

### ISSUE THREAD

**Issue by MatthiasMann** [BluSunrize/ImmersiveEngineering#4665]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
I made a metal press (with the plate press installed) and tried to give it power.
First I tried Mekanism advanced energy cables - they didn't connect to the top of the metal press.
Then I put LV wire connectors on the metal press and on a Mekanism basic energy cube (set to output) - the LV wire connector on the cube shows 256 IF, the one on the press shows 0 IF (as does the metal press itself). I used a insulated LV wire coil to connect both.

![2021-02-21_20 04 36](https://user-images.githubusercontent.com/6777029/108635724-34c71e80-7481-11eb-998b-66163cfe81a6.png)
(the steel ingot on the conveyor is not moving because the press has no power, in the background you can see the working cloches).

I also used the following IE blocks/wires without issues:
- a kinetic generator with a wind mill and insulated LV wire coils to deliver power to one of my Mekanism basic energy cubes
- some insulated MV wire coils transffering power from Mekanism solar panels to another energy cube
- 2 cloches making food - both directly powered from Mekanism advanced energy cables

I think this broke either with build 130 or 131 as I had another world with 129 where the metal press was working.

### Crashlog:
No crash.

### Versions & Modlist
ImmersiveEngineering-1.16.5-4.2.1-131
ImmersivePetroleum-1.16.4-3.1.0-2
forge-1.16.5-36.0.40
Mekanism-1.16.5-10.0.21.448

### Lastly (you may delete this from the report itself)
Please, for the love of all that is voxelbased, **read the contribution guidelines. They are linked to the right in the message box.**
When reporting issues, these are crucial, and the team withholds the right to close an issue for the plain stupidity of not reading and adhering to them.

Thank you for reporting issues, without people reporting them, they wouldn't get fixed. You're helping contribute to this mod and that is much appreciated <3

**Comment by BluSunrize** [comment]
I mean, the connector you have on there doesn't have a wire, from the looks of it...

**Comment by MatthiasMann** [comment]
They both have wires - it just a bit hidden behind the TOP display. I placed 4 LV connectores (not relays) and connected 2 wires.
Also the 2nd metal press also has no power - and that one clearly has a wire visible in that screen shot.

**Comment by BluSunrize** [comment]
Is your energy cell outputting that way? Have you tried an IE capacitor instead?

**Comment by MatthiasMann** [comment]
Yes, I double checked that cell settings several time - and the LV wire connector gets filled up once I place it on the energy cube.
I haven't tried a battery yet.

**Comment by MatthiasMann** [comment]
I did the exact same setup but with an LV capacitor and now it worked :/
Then I reverted it back to using the energy cube - and that works now too.
The only difference to before was that I closed the game after writing this issue report and just started it again.

**Comment by BluSunrize** [comment]
Definitely sounds like an issue with that energy cube then.

Resolved.
