### ISSUE TITLE
[1.16.5] Arc Furnace + Ancient Debris crash

### ISSUE THREAD

**Issue by 3FeetHigh** [BluSunrize/ImmersiveEngineering#4666]
In a SMP world I tried to burn ancient debris in an arc furnace, which caused a client side crash (the server kept running) that did not allow players to enter the server, and crashed their game on attempt. Copying the world however into singleplayer, the crash was not replicated. I am using version immersive engineering version 4.2.1 - 131 and using forge 36.0.42

[crash-2021-02-20_23.02.30-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/6018803/crash-2021-02-20_23.02.30-client.txt)

modlist:
[modlist.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/6018807/modlist.txt)

**Comment by BluSunrize** [comment]
Should be fixed for future releases by this commit:
https://github.com/BluSunrize/ImmersiveEngineering/commit/069102a8f3570248d3235c4a541ae6c58e35a171
