### ISSUE TITLE
[1.16.4] Server crash after placing redstone wire connector on RFTools dimensional cell

### ISSUE THREAD

**Issue by Water-Cat1** [BluSunrize/ImmersiveEngineering#4667]
### Description of the issue:
Player on a dedicated server erroneously placed a redstone wire connector onto an RFTools dimensional cell. Server proceeded to crash, and crashed whenever the area was loaded again. 

Admin deleted the TileEntity, but still crashed until the area was rolled back to the last backup (although this could be Forge behaviour)

### Crashlog:
[IE crash with RFTools.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/6019544/IE.crash.with.RFTools.txt)

### Versions & Modlist
Minecraft: 1.16.4
Forge: 35.1.37
IE: 1.16.4-4.1.2-129
RFTools: 1.16-2.0.10

**Comment by BluSunrize** [comment]
Please try updating to version 131 of IE to see if this issue persists. As far as I can tell, it should be resolved already in newer releases.

**Comment by malte0811** [comment]
You can ignore Blu's comment, this is not related to the changes he was talking about. I've got a fix and will push it in a bit.
