### ISSUE TITLE
Client crashing after joining world

### ISSUE THREAD

**Issue by philhk** [BluSunrize/ImmersiveEngineering#4668]
### Description of the issue:
When I join the server, my game crashes after a second. The server is not affected

### Crashlog:
https://pastebin.com/gFFy3SEa

### Versions & Modlist
ImmersiveEngineering-0.12-98.jar
Forge 14.23.5.2854
Modpack: SevTechAgesOfTheSky

Some more Info:

I placed my pump jack near a tree that teleports you to the betweenlands and after I did a right click on the machine my game crashed and now everytime I join the Server it will crash again my friends are having the same issue

**Comment by BluSunrize** [comment]
1.12 is no longer supported.
