### ISSUE TITLE
[1.16.5] Server crash at startup due to AbstractFluidAwareRecipe.getRemainingItems

### ISSUE THREAD

**Issue by cobalamin** [BluSunrize/ImmersiveEngineering#4670]
### Description of the issue:
Our Valhelsia 3.1.8a server will not start up, but crash with fatal errors during the "Preparing spawn area" phase. This happens predictably every time with the same errors. One common source I can identify is a failing null-check precondition in `blusunrize.immersiveengineering.common.crafting.fluidaware.AbstractFluidAwareRecipe.getRemainingItems(AbstractFluidAwareRecipe.java:94`, see pastebin below.

### Crashlog:
https://pastebin.com/3LJ52zdE

### Versions & Modlist
Forge: forge-1.16.5-36.0.15.jar
IE: ImmersiveEngineering-1.16.5-4.2.1-131.jar
Mods: https://pastebin.com/u0sLiUdJ -- this is exactly (without additions, deletions or replacements) the modlist included in Valhelsia 3.1.8a, see https://www.curseforge.com/minecraftmodpacks/valhelsia-3/files/3198587

**Comment by BluSunrize** [comment]
Can you update your Forge to 36.0.27 or younger and see if that resolves the issue?

**Comment by cobalamin** [comment]
After upgrading to Forge 36.0.40 and replacing all incompatible mods with newer version, I end up with the same stacktrace as before: https://pastebin.com/be2rEdSk -- so it doesn't seem to resolve or help anything, sadly.

**Comment by BluSunrize** [comment]
@malte0811 we have a todo on `Utils.getExistingTileEntity` to make it use SafeChunkUtils. Do you think that could be a fix for this issue?
