### ISSUE TITLE
[Request] Have extracting conveyor belts put directly onto the belt, rather than simply drop into the world

### ISSUE THREAD

**Issue by xenoflot** [BluSunrize/ImmersiveEngineering#4671]
Items floating on the belt, waiting for a spot on the belt, get pulled away if there's any kind of item collector or magnet nearby. Also, if the belt jams up for some reason (e.g. your power is unreliable) then it seems items can be lost to de-spawning.

I feel it would be better if the extractor placed the items on the belt as space becomes available. If you'd like to leave the current extractor as is, perhaps you'd consider adding an Advanced Extracting Conveyor that operates in this manner.

Thanks for your consideration!

**Comment by BluSunrize** [comment]
IE belts *always* use entities. They have no internal storage or a way of checking if there is "space".

If you are using SimpleMagnets, that's a known issue, it's on their side to respect the NBT tag we put on items.
Apart from that, extracting conveyors are working as intended.
