### ISSUE TITLE
Korean Is broken [1.16.5]

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#4673]
Can't Show Korean In this version.
I Think this is unicode error

**Comment by BluSunrize** [comment]
You need to provide more information. "Can't show Korean" is not enough.

If translations are missing, please provide information on which. If you are seeing errors, please provide *those errors*
You didn't even use the issue template. This is not enough to help you with.

**Comment by ghost** [comment]
**"item.immersiveengineering.shield":"\uc911\ud615 \ubc29\ud328"**

This is part of the Korean translation file. As you can see, there is something that seems to be an error in Unicode. I have already modified it arbitrarily, but it is still show up English.

**Comment by BluSunrize** [comment]
Where are you seeing these issues *ingame*? That's what I am asking for.

If you set your game to Korean, what problems do you see? Please provide screenshots and more helpful explanations. Because you are not delivering any worthwhile info right now.

**Comment by ghost** [comment]
I set it up in Korean. Only some items in Immersive Engineering mod are displayed in Korean and others in English.
![1](https://user-images.githubusercontent.com/61474387/109330341-ea89d700-789e-11eb-9595-cd0b80e2a464.png)
![2](https://user-images.githubusercontent.com/61474387/109330345-ec539a80-789e-11eb-90f0-280b3121cecb.png)
![3](https://user-images.githubusercontent.com/61474387/109330348-ecec3100-789e-11eb-837d-ada32b5ffb45.png)



I'm sorry. I'm so clumsy.

**Comment by BluSunrize** [comment]
Yeah because the translation is incomplete. We rely on people submitting translations. I don't know Korean, I can't write it.

You are free to contribute an updated translation in the form of a pullrequest, we'd be happy to merge it.

**Comment by lunavell** [comment]
Thank you for your reply. Thank you for the good mod. It was a pleasure to meet you. Have a nice one sir
