### ISSUE TITLE
No Power Kinetic dynamo

### ISSUE THREAD

**Issue by Ptituf** [BluSunrize/ImmersiveEngineering#4676]
### Description of the issue:

![SoFun](https://user-images.githubusercontent.com/28937889/109396072-1b661c80-7930-11eb-8eb2-151af98d4999.PNG)

### Versions & Modlist
Modpack Slightly Cinnamon 1.0.0
ImmersiveEngineering-1.16.4-4.1.2-129

**Comment by Ptituf** [comment]
And Pump wont work without RF (same modpack , same versions)

**Comment by BluSunrize** [comment]
make sure you place the waterwheel *against* the dynamo

**Comment by Ptituf** [comment]
![against](https://user-images.githubusercontent.com/28937889/109397639-f7a6d480-7937-11eb-9863-062e1d45c947.PNG)

same as the picture

**Comment by Ptituf** [comment]
Ok it work after breaking and re put the wheel against the dynamo
