### ISSUE TITLE
Create ore support

### ISSUE THREAD

**Issue by ZEROX7** [BluSunrize/ImmersiveEngineering#4677]
hey there just a question would it be possible to add a way to get zinc trough the excevator?

**Comment by BluSunrize** [comment]
Excavator has full support for JSON recipes and crafttweaker! You can add it yourself. :D

That said, if you have a suggestion for a Zinc based vein (that maybe also has some other things in it), I'd love to hear it.

**Comment by ZEROX7** [comment]
well about the zinc based vein zinc is in reallife a "byproduct" you get it mostly in galena or sphelerite and waht do you mean json support? is there some documentation? and crafttweaker doesnt rly work atm not even the example works they have

**Comment by BluSunrize** [comment]
...what version of the game are you even playing on?

**Comment by ZEROX7** [comment]
before 1.16.4 but updated to 1.16.5 and now everthing works XD

**Comment by BluSunrize** [comment]
Yeah Crafttweaker compat is only in 1.16.5.

Closing this, since it's resolved.
