### ISSUE TITLE
Enable UI resizing on the Engineer's Manual

### ISSUE THREAD

**Issue by torincb** [BluSunrize/ImmersiveEngineering#4678]
(This is a feature suggestion, not a bug report.)

Is it possible to add support for resizing the Engineer's Manual UI? I can of course change the whole game's UI scale, but it would be nice to change it for the book specifically, as its font size at global GUI scale 3 is difficult to read, but scale 3 is perfect for the rest of the UI on my setup.

As an example, the Botania Lexicon of the Botania mod supports this with a button on the book's landing page.

EDIT: If pointed in the right direction I'm happy to implement it myself!

**Comment by BluSunrize** [comment]
We actually had the manual scaling properly once upon a time, but it seems like that broke.
So I've reworked all that and implemented this for next release! Took a leaf out of Patchouli to see how Vazkii did it there ^^
