### ISSUE TITLE
garden cloche texture (bug?) :/

### ISSUE THREAD

**Issue by MrV0DkAa** [BluSunrize/ImmersiveEngineering#4679]
Hello! First of all I want to apologize you for this question, cause I hope that is not a really issue (I guess this is texture)
I'm playing ATM6 with ImmersiveEngineering-1.16.5-4.2.1-131 and I was putting garden cloche  and, as usual, the garden cloche is not translucid... It is white like the picture bellow.. Can you tell me if it's a texture bug, a problem of this mod or... any other thing else...

 Thanks a lot for help!

![image](https://user-images.githubusercontent.com/79458926/109426791-511a0c80-79e7-11eb-8d24-34e3817aa20c.png)

**Comment by BluSunrize** [comment]
Already fixed for future release.
