### ISSUE TITLE
[1.16.5] Crusher crushes 4 items then stops

### ISSUE THREAD

**Issue by aajuggernaut** [BluSunrize/ImmersiveEngineering#4680]
### Description of the issue:
I was attempting to use the Crusher to crush the ores into their respective dusts. However, the crusher would stop processing items after it had processed 4. If I let it stop and then threw in more ores, it would process 4 of the newly thrown in ores, but would ignore the ones already in there until I climbed in to grab them and threw them back in. 

### Crashlog:
The game is not crashing.

### Versions & Modlist
Modlist is the All The Mods 6 pack version 1.5.2, which uses IE 1.16.5-4.2.1-131 and Forge 36.0.21
This is on an online multiplayer server.

**Comment by BluSunrize** [comment]
Fixed already for upcoming releases.
