### ISSUE TITLE
[1.16.5] 6 entries fail to load 

### ISSUE THREAD

**Issue by IndefiniteCalculus** [BluSunrize/ImmersiveEngineering#4684]
Couldn't open the engineer's manual when I try to right-click it, and I got a prompt like: "6 entries failed to load! Please report this as an issue with your log file!". Here is my log file
[latest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/6081036/latest.log)

**Comment by BluSunrize** [comment]
Please remove Immersive Petroleum and try again.

And next time, use the issue template, or you will not receive assistance.

**Comment by BluSunrize** [comment]
Also, please inform us what language your game is set to, and try to reproduce this issue with the game set to English.

**Comment by IndefiniteCalculus** [comment]
> Also, please inform us what language your game is set to, and try to reproduce this issue with the game set to English.

Sorry, I will use the template next time. The language I am using in the game is Simplified Chinese. I change to English(US) and the problem solved ( I haven't removed Immersive Petroleum yet ).

**Comment by IndefiniteCalculus** [comment]
> > Also, please inform us what language your game is set to, and try to reproduce this issue with the game set to English.
> 
> Sorry, I will use the template next time. The language I am using in the game is Simplified Chinese. I change to English(US) and the problem solved ( I haven't removed Immersive Petroleum yet ).

the Simplified Chinese in the language options is "简体中文（中国）"

![屏幕截图 2021-03-04 170316](https://user-images.githubusercontent.com/55014395/109938994-943bee80-7d0b-11eb-8318-4504904cad51.png)

**Comment by frank89722** [comment]
This has already been fixed in latest release.

**Comment by siteonfly** [comment]
I have same issue but with russian language. With IP and without it. Switching to english fixes it.

UPD:
Forge 36.0.46
IE version 4.2.2-132
[latest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/6098190/latest.log)

modlist:
https://pastebin.com/TwLJczpB

UPD2:
I think errors are in these files 
ImmersiveEngineering/src/main/resources/assets/immersiveengineering/manual/ru_ru/graphite.txt 
<config;b;machines.arcfurnace_electrodeCrafting; создать,>
There is no such text in  ImmersiveEngineering/src/main/resources/assets/immersiveengineering/manual/en_us/graphite.txt 

ImmersiveEngineering/src/main/resources/assets/immersiveengineering/manual/ru_ru/minerals.txt 
 <config;i;machines.coredrill_consumption>
But other text in  ImmersiveEngineering/src/main/resources/assets/immersiveengineering/manual/en_us/minerals.txt 
<config;i;machines.coredrill.consumption>
