### ISSUE TITLE
132 is unable to load. - Failed to load datapacks

### ISSUE THREAD

**Issue by IchigoGames** [BluSunrize/ImmersiveEngineering#4685]
### Description of the issue:
![image](https://user-images.githubusercontent.com/11888162/109918094-12e94b00-7c7c-11eb-9237-2e7b306044e6.png)
after updating IE i get this msg when trying to create a new world 

### Crashlog:
not a crash but here is logs https://www.dropbox.com/s/yxw1a2xzxfsl58e/latest.log?dl=0

### Versions & Modlist
Minecraft 1.16.5 
Forge 36.0.43-45
ImmersiveEngineering-1.16.5-4.2.2-132 
Frontier craft modpack

**Comment by IchigoGames** [comment]
with version ImmersiveEngineering-1.16.5-4.2.1-131 its able to create new world like normal

**Comment by ProsperCraft** [comment]
Yes.132 is broken, I get the same on a dedicated server with an existing world, so the topic needs to be chanted to .132 is unable to load. - Failed to load datapacks

Dedicated server stacktraces-
https://gist.github.com/ProsperCraft/5842c1a6ea53fa12d82a0417c0c0c829

**Comment by Gregorius-MC** [comment]
I have the same error. And I found out that this problem occurs only when the modpack has SilentGear. If you delete it, everything works fine. (Forge 36.0.44, SilentGear-1.16.3-2.6.6+226)

**Comment by BluSunrize** [comment]
Thanks for actually providing a detailed testcase Gregorious. Figuring out which other mod was involved in this made debugging this much faster and easier.
