### ISSUE TITLE
[1.16.5] Config for disabling Hammer crushing doesn't work

### ISSUE THREAD

**Issue by Wxrlds** [BluSunrize/ImmersiveEngineering#4686]
### Description of the issue:
When setting ``disable_hammer_crushing = true`` in the config, the hammer is still able to crush ores into dusts.
![grafik](https://user-images.githubusercontent.com/42120270/109987505-f9d9ac00-7d06-11eb-878c-5289fa0d5f78.png)

### Versions & Modlist
Minecraft 1.16.5
Forge 36.0.43
ImmersiveEngineering-1.16.5-4.2.2-132
jei-1.16.4-7.6.1.71

**Comment by BluSunrize** [comment]
Yeah, configs can't easily influence recipe loading anymore. You will need to use a datapack to disable the following recipes:

![image](https://i.imgur.com/3EH6Xfg.png)

I will be removing the option from the config for the next release.
