### ISSUE TITLE
[Request] Shorten Item ID ( Server compability )

### ISSUE THREAD

**Issue by HonzaVinCZ** [BluSunrize/ImmersiveEngineering#4689]
Hello, I'd like to ask you if there is any way how to shorten the items ID. The problem comes in when you're on the server and it uses sign based chest shop. Plugin then complains the item ID is too long ( longer than 15 characters ). Because your mod uses immersiveengineering in all items ID, sign can't pass in any item from your mod. In my opinion the ID could be shortened like IC2 has ( ieng for example ). But I got no idea what it is like to make such a change.

**Comment by BluSunrize** [comment]
...lol, no.
"immersiveengineering" is the mod id. It's the internal, unique, distinguishing name of the project. That will never get changed.

Also, the fact that there is still sign-based plugin logic in the age of command blocks is ridiculous.
