### ISSUE TITLE
[1.16.5] Broken datapack

### ISSUE THREAD

**Issue by CanBoy67** [BluSunrize/ImmersiveEngineering#4692]
You have a broken datapack in version 4.2.2-132 of your mod which happens when Silent's is installed both logs reference this mod this is on forge 36.0.45. To circumvent this issue I downgraded to 4.2.1-131. Please take a look at aforementioned datapack

-https://gist.github.com/CanBoy67/eadf970dfb133e0d585de311a079e965 (debug.log)
-https://gist.github.com/CanBoy67/631d3f7e98060c25ea34a66c3f4ec0c2 (latest.log)

**Comment by BluSunrize** [comment]
It's already fixed for future releases.
