### ISSUE TITLE
[1.16.5] Interacting with jerrycan crashes game.

### ISSUE THREAD

**Issue by RillingDev** [BluSunrize/ImmersiveEngineering#4696]
### Description of the issue:
When right-clicking on a fluid placed in the world with a jerrycan equiped, the game crashes.

### Crashlog:
https://pastebin.com/ZFJFcyTb

### Versions & Modlist

MC: 1.16.5
IE: ImmersiveEngineering-1.16.5-4.2.1-131
Forge: 36.0.46

No other mods present

**Comment by BluSunrize** [comment]
Already fixed, you are using an outdated version.

**Comment by RillingDev** [comment]
Woops, Sorry! did not see the new release.
