### ISSUE TITLE
1.16.5 Cannot climb metal ladder

### ISSUE THREAD

**Issue by mnsnownutt** [BluSunrize/ImmersiveEngineering#4697]
### Description of the issue:
Cannot climb a metal ladder (IE version)

### Versions & Modlist
Forge 36.0.46

EDIT- I believe it is an issue with Forge and IE.  I downgraded my Forge version to 36.0.41 and the ladder works again.  Video below is with 36.0.46.

IE version 4.2.2-132
Modlist:  https://pastebin.com/T9kCmE4h

https://user-images.githubusercontent.com/31514693/110246498-6fbf5c80-7f2d-11eb-9b14-cdecb419ff33.mp4

**Comment by BluSunrize** [comment]
This is the direct result of a change in Forge:

https://github.com/MinecraftForge/MinecraftForge/pull/7535

Apparently vanilla has a Tag for climbable stuff, so I guess we gotta use that...
