### ISSUE TITLE
1.16.5 Metal Press Stops Working

### ISSUE THREAD

**Issue by mnsnownutt** [BluSunrize/ImmersiveEngineering#4698]
Description of the issue:
Everytime I log out and back on, the metal press stops working.  The item gets stuck on the belt and I have to break and reform the press and it deletes the item that was on the belt.  It has happened ever since I have played 1.16.4 and 1.16.5.  I was at Forge version 36.0.41 and was hopeful that updating to 36.0.46 may help, but issue still exists.  Also, does not matter what pattern is put on the press, happens with wire, rods, plate, etc.

https://user-images.githubusercontent.com/31514693/110246762-7e5a4380-7f2e-11eb-9901-3df141026e6c.mp4

Versions & Modlist

Forge 36.0.46
IE version 4.2.2-132
Modlist: https://pastebin.com/T9kCmE4h

**Comment by BluSunrize** [comment]
I have been unable to reproduce this.

Is this single- or multiplayer? If it is multiplayer, are you able to replicate this in singleplayer?

**Comment by mnsnownutt** [comment]
This is a singleplayer world.  Happened from the very beginning when I first created the metal press over a month ago in this world and not sure what is causing it.  And it only happens when relogging.  Once you break it and reform it, you can use it, switch out molds, no problems at all.  Log in and log out and this happens.

**Comment by BluSunrize** [comment]
Please try replicating this with just IE installed.

**Comment by mnsnownutt** [comment]
Cannot replicate with just IE installed.  Works fine, so must be an interaction with another mod.

**Comment by BluSunrize** [comment]
Excellent. Now I'd love if you can find out which one. Split your modlist in half, see if the issue persists. If it does, halve that group again. If it doesn't, the issue is in the other half. It shouldn't take too long to find the culprit that way.

**Comment by mnsnownutt** [comment]
I will let you know what I find out.

**Comment by BluSunrize** [comment]
Closed due to lack of feedback.
