### ISSUE TITLE
Chemthrower turret wasting fuel

### ISSUE THREAD

**Issue by NeutronJohn** [BluSunrize/ImmersiveEngineering#4699]
Immersive engineering version: 1.16.5-4.2.1-131
Forge version: 1.16.5 36.0.42

Mod list:
![image](https://user-images.githubusercontent.com/77425239/110392515-a92bc100-802e-11eb-9165-3c607126a3ca.png)
![image](https://user-images.githubusercontent.com/77425239/110392540-b5b01980-802e-11eb-8e61-9fa4bbf7d169.png)
![image](https://user-images.githubusercontent.com/77425239/110392562-bf398180-802e-11eb-960c-733ac36de5f5.png)

The glitch: Chemthrower turrets try to shoot through blocks, causing particle lag, and wasting fuel.

**Comment by BluSunrize** [comment]
I can't reproduce this. I see the chemthrower turret *aiming* but it does not shoot:

![image](https://i.imgur.com/kkYGdBN.png)

Please provide some pictures of your testcase.

**Comment by NeutronJohn** [comment]
![2021-03-08_16 34 16](https://user-images.githubusercontent.com/77425239/110508980-3cb0d080-80c7-11eb-8846-6613c374a38f.png)
Try using walls?

**Comment by NeutronJohn** [comment]
It might have something to do with how that specific area is set up. It does not reproduce with just walls
