### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by ImperialWizard** [BluSunrize/ImmersiveEngineering#47]
Hi ! I still have the issue I had in 0.1.15 with the wires dissapearing in a rftools dimension after a restart of the game. I tried to update to 0.1.16 to see if that helped
 And also is that normal that we can't use hempcrete with the carpenters block ?

**Comment by BluSunrize** [comment]
no idea how RFtools stores their stuff, sorry.
And yes, custom rendertype. Can't really change that.
