### ISSUE TITLE
1.16.5 Engineer's book does not open.

### ISSUE THREAD

**Issue by GnomTocha** [BluSunrize/ImmersiveEngineering#4701]
1) Engineer's book does not open. 
When you open a book, the chat displays the message "2 entries failed to load! Please report this as an issue with
your log file!".
forge-1.16.5-36.0.46.
minecraft 1.16.5
ImmersiveEngineering-1.16.5-4.2.2-132
![2021-03-09_16 31 04](https://user-images.githubusercontent.com/75666317/110488315-6dacf780-80ff-11eb-8922-3a9c551c0598.png)
[latest.log](https://gist.github.com/GnomTocha/e59a6f42bfd87af0c06d94b26a53681b)
[[debug.log]](https://gist.github.com/GnomTocha/e5633a503818b93bf4a2933d109871ea)
[Mod of list](https://gist.github.com/GnomTocha/3e69e61e6e45266d2ffe52f4a0dec346)

2) Also I tested the new version ImmersiveEngineering-1.16.5-4.2.2-132 without any external modifications. The same problem.
There is only a minor change in the text message "1 entries failed to load! Please report this as an issue with
your log file!".
![2021-03-09_17 17 40](https://user-images.githubusercontent.com/75666317/110494650-dba7ed80-8104-11eb-8e71-be61670b5723.png)

**Comment by GnomTocha** [comment]
> 1. Книга инженера не открывается. 
>    Когда вы открываете книгу, в чате отображается сообщение «Не удалось загрузить 2 записи! Сообщите об этом как о проблеме с 
>    вашим файлом журнала!». 
>    кузница-1.16.5-36.0.46. 
>    minecraft 1.16.5 
>    ImmersiveEngineering-1.16.5-4.2.2-132 [latest.log ](https://gist.github.com/GnomTocha/e59a6f42bfd87af0c06d94b26a53681b)[[debug.log] ](https://gist.github.com/GnomTocha/e5633a503818b93bf4a2933d109871ea)[Мод списка](https://gist.github.com/GnomTocha/3e69e61e6e45266d2ffe52f4a0dec346)
>    ![2021-03-09_16 31 04](https://user-images.githubusercontent.com/75666317/110488315-6dacf780-80ff-11eb-8922-3a9c551c0598.png)
>    [](https://gist.github.com/GnomTocha/e59a6f42bfd87af0c06d94b26a53681b)
>    [](https://gist.github.com/GnomTocha/e5633a503818b93bf4a2933d109871ea)
>    [](https://gist.github.com/GnomTocha/3e69e61e6e45266d2ffe52f4a0dec346)
> 2. Также я протестировал новую версию ImmersiveEngineering-1.16.5-4.2.2-132 без каких-либо внешних модификаций. Та же проблема. 
>    В текстовом сообщении "Не удалось загрузить 1 запись! Сообщите об этом как о проблеме с 
>    вашим файлом журнала!".
>    ![2021-03-09_17 17 40](https://user-images.githubusercontent.com/75666317/110494650-dba7ed80-8104-11eb-8e71-be61670b5723.png)

Forgot to add that the problem is present on both the client and the server.

**Comment by GnomTocha** [comment]
Forgot to add that the problem is present on both the client and the server.

**Comment by BluSunrize** [comment]
The first log file indicates issues with Immersive Petroleum.

For the second one you have not provided a log file. But assuming that you have your language set to Russian, this is an error that was fixed n Build 133, which released yesterday. Please update and see if that resolves it.

**Comment by GnomTocha** [comment]
> Первый файл журнала указывает на проблемы с Immersive Petroleum.
> 
> Для второго вы не предоставили файл журнала. Но если у вас установлен русский язык, это ошибка, которая была исправлена ​​в сборке 133, выпущенной вчера. Пожалуйста, обновите и посмотрите, решит ли это проблему.

I was wrong in point 2. The ImmersiveEngineering version is 1.16.5-4.2.3-133. I'll send the logs now.

**Comment by GnomTocha** [comment]
[latest.log](https://gist.github.com/GnomTocha/9c999e5c187782aa53a2d073bf3aa9c3)
[debug.log](https://gist.github.com/GnomTocha/3466460ba1089f0846a6d49b30e97dff)
