### ISSUE TITLE
[1.16.5] (4.2.3-133) Error at using Engineer's Manual

### ISSUE THREAD

**Issue by Timmmy001** [BluSunrize/ImmersiveEngineering#4702]
### Description of the issue:
After update to new version from IE (133), i get a error "1 entries failed to load! Please report this as an issue with your log file!" at try to using it. The manual will not be shown.
With using previous version (132) it will work without problems.

### Crashlog:
[Log from error](https://gist.github.com/Timmmy001/df47e7534eb6d921a98da8e7e85af2af)

### Versions & Modlist
forge-36.046
ImmersiveEngineering-1.16.5-4.2.3-133.jar
aiotbotania-1.16.4-1.7.2.jar
architectury-1.8.131-forge.jar
BetterCaves-Forge-1.16.4-1.1.1.jar
BetterMineshafts-Forge-1.16.4-2.0.2.jar
BetterShieldsMC1.16.3-1.1.4.jar
biggerreactors-1.16.4-0.4.3.jar
BiomesOPlenty-1.16.4-13.0.0.431-universal.jar
Bookshelf-1.16.5-10.0.1.jar
Botania-1.16.4-413.jar
BotaniaAdditionsMC1.16.4-1.0.4.jar
Ceramics-1.16.5-1.6.1.jar
chiselsandbits-0.3.3-RELEASE.jar
chunkloaders-1.1.6-mc1.16.5.jar
Clay WorldGen-1.16.4-1.2.0.jar
cloth-config-4.11.14-forge.jar
collective-1.16.5-2.11.jar
connectedglass-1.0.6a-mc1.16.4.jar
Corail-Adventurer-Spawners-1.16.4-015.jar
corpse-1.16.5-1.0.1.jar
curios-forge-1.16.5-4.0.5.0.jar
cyclepaintings_1.16.5-1.5.jar
dismountentity_1.16.5-1.4.jar
doubledoors_1.16.5-2.3.jar
EditSign-Forge-1.16.5-2.2.0.jar
extendedslabs-1.16.4-1.4.0.jar
findme-1.16.3-2.1.0.0.jar
forgemod_VoxelMap-1.10.12_for_1.16.5.jar
ftb-gui-library-1605.2.1.40-forge.jar
GameMenuModOption-1.16.4-1.4.jar
gardenofglass-1.7.jar
harvest-1.16.3-1.0.3.jar
Hwyla-forge-1.10.11-B78_1.16.2.jar
ImmersivePetroleum-1.16.4-3.1.0-2.jar
industrial-foregoing-1.16.5-3.2.10.1-decb7ae.jar
jei-1.16.4-7.6.1.71.jar
LibX-1.16.3-1.0.17.jar
Mantle-1.16.5-1.6.79.jar
modnametooltip_1.16.2-1.15.0.jar
morevanillalib-1.16.4-1.3.10.jar
MouseTweaks-2.14-mc1.16.2.jar
OptiFine_1.16.5_HD_U_G6.jar
PackingTape-1.16.3-0.10.0.jar
Patchouli-1.16.4-50.jar
phosphophyllite-1.16.4-0.4.5.jar
polymorph-forge-1.16.5-0.24.jar
RedstoneExtras-1.16.2-1.0.0.6.jar
Regrowth-1.16.4-1.16.4-1.35.0.18.jar
repurposed_structures-1.16.5-2.4.7.jar
simple_sorter-1.16.4-0.0.1.jar
SlimyBoyos-3.1.0.10.jar
stackrefill_1.16.5-1.7.jar
StorageDrawers-1.16.3-8.2.2.jar
structurize-0.13.149-ALPHA-universal.jar
supermartijn642configlib-1.0.5a-mc1.16.jar
titanium-1.16.5-3.2.8.jar
TravelAnchors-2.3.jar
TreePlant-1.16.x-0.3.0.jar
useful_backpacks-1.16.4-1.11.6.87.jar
u_team_core-1.16.4-3.1.17.192.jar
vanillaexcavators-1.16.4-2.2.0.jar
vanillahammers-1.16.4-2.2.0.jar
VillagersRespawn-1.16.5-1.36.0.3.jar
WailaHarvestability-mc1.16.x-forge-1.1.14.jar
WaterDripSound-1.16.3-0.1.3.jar
WAWLA-1.16.5-8.0.1.jar
WoodenBuckets-1.16.5-1.2.jar
YungsApi-1.16.4-Forge-4.jar

**Comment by malte0811** [comment]
Update IE to build 134, that build was released just for this issue.
