### ISSUE TITLE
[Suggestion] 1.12.2 - Add silo config option

### ISSUE THREAD

**Issue by KaktuszSok** [BluSunrize/ImmersiveEngineering#4703]
### Description of the issue:
Since most modpacks come with mods like storagedrawers the IE silos have little reason to be used. It would be very useful if modpack makers could adjust the maximum amount of items stored in a silo to whatever value they see fit.

### Versions & Modlist
Forge 14.23.5.2854
IE 0.12-98
Storage Drawers 1.12.2-5.4.2

**Comment by BluSunrize** [comment]
Support for 1.12 was ceased 9 months ago.
