### ISSUE TITLE
[1.12.2] Arc furnace breaks Gregtech progression

### ISSUE THREAD

**Issue by KaktuszSok** [BluSunrize/ImmersiveEngineering#4704]
### Description of the issue:
The arc furnace automatically registers all gregtech ingots to be smeltable in 5 seconds from their respective dust (or ore). This skips the need to build gregtech machines such as the vacuum freezer and severely throws off balance. It would make more sense to check if the dust/ore to ingot recipe exists as a vanilla furnace recipe before allowing it to be done in the arc furnace. If this is an intended feature, it should be configurable.

### Versions & Modlist
Forge v2854
Immersive Engineering 0.12-98
Gregtech CE 1.11.1.632
JEI 4.16.1.301

**Comment by BluSunrize** [comment]
Support for 1.12 was ceased 9 months ago.
