### ISSUE TITLE
Crashing when placing fluid tanks in distiliation tower

### ISSUE THREAD

**Issue by benbenlaw** [BluSunrize/ImmersiveEngineering#4705]
### Before reporting:
crashing when placing tanks of fluids from cyclic into distilation tower

### Description of the issue:
crashing when placing tanks of fluids from cyclic into distilation tower

### Crashlog:
[crash-2021-03-11_08.39.41-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/6121993/crash-2021-03-11_08.39.41-server.txt)

### Versions & Modlist
cyclic: 2.2.9
immersive: 4.2.4-134
forge: 36.0.46
minecraft:1.16.5

Thank you for reporting issues, without people reporting them, they wouldn't get fixed. You're helping contribute to this mod and that is much appreciated <3

**Comment by BluSunrize** [comment]
The Distillation Tower is from Immersive Petroleum, not Immersive Engineering. Please report this to them, not us.
