### ISSUE TITLE
[1.16] Veins do not generate when at for out coordinates

### ISSUE THREAD

**Issue by jaypitti** [BluSunrize/ImmersiveEngineering#4707]
Im playing on an FTB Valhelsia 3 server and my base is at 291938, 64, -811268, when searching for veins there are none that appear to generate (checked a 50x50 chunk area with core sample drill and mineral survey tools). If I travel back to 0,0 and search from there I immediately find veins everywhere. I believe there is an issue with vein generation at far our coordinates though I have no idea what the cut off point is

**Comment by Shyzle** [comment]
Also getting this issue on Direwolf20, but i've added some mods not from the pack, but i'm at -76500 -38000 and minerals cannot be found but can be found around world spawn

**Comment by mindforger** [comment]
@Shyzle please make a new issue and follow the template to make an usefull bug report and the OP should update his issue according to the issue template
