### ISSUE TITLE
Excavator not finding ores that core drill shows 

### ISSUE THREAD

**Issue by SadHorizion77210** [BluSunrize/ImmersiveEngineering#4708]
### Before reporting:
This issue not seen
### Description of the issue:
After the resent upgrade to V133 the excavator has stopped seeing an ore it was mining before upgrade the ore in question is Beryl. I then did a new core sample in a chunk 2 down from where the excavator was and it showed Bitumous Coal 75%  and Beryl 25% when i moved said excavator it found the coal ok  but no beryl so think it is now not picking up this ore in the table
### Crashlog:
No crash
### Versions & Modlist
IE 1.16.5 - 4.2.3- 133 and Forge 36.0.46 am using the Minecolonies Official 1.16.5 v1.5 modpack
### Lastly (you may delete this from the report itself)

Thank you for reporting issues, without people reporting them, they wouldn't get fixed. You're helping contribute to this mod and that is much appreciated <3

**Comment by BluSunrize** [comment]
Can you please provide some screenshots of your setup, the core sample tooltips and the positions your took them at? I'm finding it difficult to understand the issue from the description alone.

**Comment by SadHorizion77210** [comment]
Here are some screenshots
![2021-03-12_17 45 46](https://user-images.githubusercontent.com/59647108/110926232-186f2100-835f-11eb-9d56-40f4ae53ceb0.png)
![2021-03-12_17 36 42](https://user-images.githubusercontent.com/59647108/110926251-202ec580-835f-11eb-91cc-b34e5feb91df.png)
![2021-03-12_17 35 09](https://user-images.githubusercontent.com/59647108/110926277-245ae300-835f-11eb-8414-2a18c184dd85.png)

**Comment by SadHorizion77210** [comment]
here are three screenshots as you can see the bucket is coming up with coal  but you will notice that it also comes up with an empty bucket which should be the beryl

**Comment by BluSunrize** [comment]
No, empty buckets are completely normal. Every vein has a chance to dig up nothing.
Can you please create a new core sample directly below the wheel, and show me the tooltip in your inventory?

**Comment by SadHorizion77210** [comment]
That core sample was taken at the point the bottom steel block goe's  to
make the wheel

**Comment by BluSunrize** [comment]
And I want the item tooltip. Which you haven't shown me yet. I need to see that it was taken recently, and I need to see the vein integrity. Please just comply with the instructions or I can't help you debug this.

**Comment by SadHorizion77210** [comment]
the core sample was taken at the location the bottom steel blocks go'es for  the wheel so was slap bang where the core sample was taken, i have another excavator mining uranium ,lead , gravel sand and clay working still with no problem it's only the beryl ore that is the problem it can't mine it for some reason even when a core sample shows it is there i also tried in another place which should 100% beryl  but when the excavator was put there it found nothing

**Comment by BluSunrize** [comment]
Just *get me a screenshot of the item tooltip*. That's literally what I have asked for in the past three messages. Just get me the info I have requested, I'm trying to help you here >_<

**Comment by SadHorizion77210** [comment]
Looking at it again looks like i did not read the print that said no ores , my misstake for not reading it correctly
