### ISSUE TITLE
Minecraft GL info: ~~ERROR~~ 1.12.2

### ISSUE THREAD

**Issue by KleeJeS** [BluSunrize/ImmersiveEngineering#4710]
Hi, I get this error some time after playing in the minecraft world. If you remove all the mods, everything is OK - the world comes in. Also, do not re-enter the world after an error, it immediately crashes with such a report. Version 1.12.2

---- Minecraft Crash Report ----
// Why did you do that?

Time: 3/12/21 6:45 PM
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$ValueIterator.next(HashMap.java:1458)
	at net.minecraft.world.World.func_147448_a(World.java:1949)
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:856)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:109)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:728)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 654371192 bytes (624 MB) / 1409286144 bytes (1344 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 4, tallocated: 105
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 35 mods loaded, 35 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                | Version              | Source                                        | Signature                                |
	|:------ |:----------------- |:-------------------- |:--------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft         | 1.12.2               | minecraft.jar                                 | None                                     |
	| LCHIJA | mcp               | 9.42                 | minecraft.jar                                 | None                                     |
	| LCHIJA | FML               | 8.0.99.99            | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge             | 14.23.5.2854         | forge-1.12.2-14.23.5.2854.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | bspkrscore        | 8.0.0                | 1.12.2bspkrscore_universal_8.0.1.jar          | None                                     |
	| LCHIJA | treecapitator     | 1.43.0               | 1.12TreeCapitator_client_1.43.0.jar           | None                                     |
	| LCHIJA | wumpleutil        | 2.12.7               | wumpleutil-1.12.2-2.12.7.jar                  | None                                     |
	| LCHIJA | foodfunk          | 4.9.6                | foodfunk-1.12.2-4.9.6.jar                     | None                                     |
	| LCHIJA | aquaculture       | 1.6.8                | Aquaculture_1.12.2_1.6.8.jar                  | None                                     |
	| LCHIJA | autoplant         | 1.12-1.0.0           | autoplant-mod-1_12_2.jar                      | None                                     |
	| LCHIJA | biomesoplenty     | 7.0.1.2444           | BiomesOPlenty_1.12.2_7.0.1.2444_universal.jar | None                                     |
	| LCHIJA | codechickenlib    | 3.2.3.358            | CodeChickenLib_1.12.2_3.2.3.358_universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | chickenchunks     | 2.4.0.70             | ChickenChunks_1.12_2.4.0.70_universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | craftingex        | 1.2.0                | craftingex_1.12-v1.2.0.jar                    | None                                     |
	| LCHIJA | cfm               | 6.3.0                | furniture_6.3.0_1.12.2.jar                    | None                                     |
	| LCHIJA | hungryanimals     | 1.12.2-5.5.1         | hungryanimals_1.12.2_5.5.1.2.jar              | None                                     |
	| LCHIJA | ichunutil         | 7.2.2                | ichun-util-mod-1_12_2.jar                     | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LCHIJA | jei               | 4.16.1.301           | jei_1.12.2_4.16.1.301.jar                     | None                                     |
	| LCHIJA | lightningtweaks   | 1.12.2-1.2.1.0-beta1 | lightningtweaks_1.12.2_1.2.1.0_beta1.jar      | None                                     |
	| LCHIJA | mobamputation     | 7.0.0                | MobAmputation_1.12.2_7.0.1.jar                | None                                     |
	| LCHIJA | gachashroom       | 1.0.0                | MushroomQuest1.12.2_v1.7.jar                  | None                                     |
	| LCHIJA | nei               | 2.4.3                | NotEnoughItems_1.12.2_2.4.3.245_universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | ping              | 1.4.4                | Ping_1.12.2_1.4.4.jar                         | None                                     |
	| LCHIJA | pointing-mod      | 1.0                  | Pointing_Mod_1.12.2.jar                       | None                                     |
	| LCHIJA | portable_lighting | 1.0.0e               | portable-lighting-mod-1_12_2.jar              | None                                     |
	| LCHIJA | puddles           | 1.1                  | Puddles_1.12.2_1.1.jar                        | None                                     |
	| LCHIJA | fa                | 2.0                  | RealisticUlities2.0_1.12.2.jar                | None                                     |
	| LCHIJA | soundfilters      | 0.12.1_for_1.12      | SoundFilters_0.12.1_for_1.12.jar              | None                                     |
	| LCHIJA | thutcore          | 5.19.8               | thutcore-1.12.2-5.19.8.jar                    | None                                     |
	| LCHIJA | thutcore_compat   | 1.0                  | thutcore-1.12.2-5.19.8.jar                    | None                                     |
	| LCHIJA | thuttech          | 6.1.5                | thuttech-1.12.2-6.1.5.jar                     | None                                     |
	| LCHIJA | twilightforest    | 3.11.1021            | twilightforest_1.12.2_3.11.1021_universal.jar | None                                     |
	| LCHIJA | gvc               | 1.2.0                | VoiceChatReloaded_1.12.2_1.2.4.jar            | None                                     |
	| LCHIJA | xlfoodmod         | 1.12.2-1.3.0         | XL Food Mod-1.12.2-1.3.0.jar                  | None                                     |
	| LCHIJA | orelib            | 3.6.0.1              | OreLib-1.12.2-3.6.0.1.jar                     | 7a2128d395ad96ceb9d9030fbd41d035b435753a |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['KleeJe'/367, l='лук', x=-111.92, y=67.10, z=193.17]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'****

**Comment by BluSunrize** [comment]
1.12 has not been supported for 9 months.
