### ISSUE TITLE
[1.12]Metal Press crash

### ISSUE THREAD

**Issue by winterSteve25** [BluSunrize/ImmersiveEngineering#4712]
### Description of the issue:
Client crash when using metal press plate recipe (custom plate recipe added by crafttweaker)

### Crashlog:
https://pastebin.com/j6dt7G4k

### Versions & Modlist
IE version:0.12-98
Forge version: 14.23.5.2854
Modlist: https://github.com/W1nter-isHere/FC-Atomic-Space/blob/main/ModList

Thanks!

**Comment by BluSunrize** [comment]
Support for 1.12 was ended 9 months ago.
