### ISSUE TITLE
1.16 Distillation tower on chunk border causes block place/break latency

### ISSUE THREAD

**Issue by sk1tt1sh** [BluSunrize/ImmersiveEngineering#4713]
### Description of the issue:
The distillation tower, when put on a chunk border causes the chunk where the redstone engineering block is to be very laggy when placing/destroying any blocks.
Destroying or breaking the multiblock does NOT resolve the latency and requires a server restart.

### Versions & Modlist
Valhelsia 3.1.9 (Server & Client)

**Comment by BluSunrize** [comment]
Distillation Tower is from Immersive Petroleum, not Immersive Engineering.

Also, use the issue template properly, or the IP devs won't help you either.
