### ISSUE TITLE
[ver. 133+] Removed recipe: nether wart + lava bucket -> blaze powder

### ISSUE THREAD

**Issue by IceflowRE** [BluSunrize/ImmersiveEngineering#4714]
### Description of the issue:
The garden cloche could produce a blaze powder from a nether wart and a lava bucket.
```
{"type":"immersiveengineering:cloche","results":[{"item":"minecraft:blaze_powder"}],"input":{"item":"minecraft:nether_wart"},"soil":{"item":"minecraft:lava_bucket"},"time":560,"render":{"type":"crop","block":"minecraft:nether_wart"}}
```

Either the recipe was removed accidentally or it is missing in the change log.

### Versions & Modlist
IE 132 had it 133 and 134 do not have it.

**Comment by BluSunrize** [comment]
Yeah that was a mistake. That was a test recipe I had left in, so I removed it again. =P
