### ISSUE TITLE
radiator block has no crafting recipe due to mod compatibility issue 1.16.5

### ISSUE THREAD

**Issue by IchigoGames** [BluSunrize/ImmersiveEngineering#4715]
### Description of the issue:
immersive engineering radiator block has no crafting recipe add the mods listed and try to craft radiator block.

### Crashlog:
not a crash so n/a

### Versions & Modlist
Minecraft 1.16.5
Forge 36.0.58
ImmersiveEngineering-1.16.5-4.2.4-134
jei-1.16.4-7.6.1.71
Space-Bosstools-1.16.4-4.6

Debug log not generated

[latest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/6143155/latest.log)

edit nvm after doing more testing that i should of done before this does not happen with only this mod and jei installed so it most be a mod compatibility issue. will do more testing on my side to find the reason.

[latest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/6144195/latest.log) Updated log

**Comment by BluSunrize** [comment]
Edit your post to follow the issue template and provide the required debug crashlog.

Reply here once that is done, and I'll reopen the issue.

**Comment by IchigoGames** [comment]
done

**Comment by BluSunrize** [comment]
Some mod in that pack is breaking those recipes. I can't tell you which one it is. Binary search is your best option here. Halving the mods in the pack until you find out which one it is.

**Comment by IchigoGames** [comment]
its Space-Bosstools-1.16.4-4.6

**Comment by IchigoGames** [comment]
is this something i should report to them ?

**Comment by BluSunrize** [comment]
Probably!

**Comment by IchigoGames** [comment]
btw it seems like the crafting recipe used for radiator block does not call for a specific type of bucket used in jei it was switching from water to lava to chocolate from create this may be part of the issue. making sure it only uses water bucket in crafting recipe may fix this.

**Comment by BluSunrize** [comment]
It uses the "water" tag for fluids. However, a bunch of mods have decided to tag their fluids as "water", because having that tag makes the fluid push people and have all the other physics.

This is a known issue in Forge, where the fluid physics are dependent on the water tag. And since Forge doesn't provide a fix/workaround, a bunch of mod devs just decided to use the "water" tag for fluids that *aren't* water.
Not our fault.

**Comment by IchigoGames** [comment]
ok

**Comment by IchigoGames** [comment]
wish i could find a workaround for this dont want to remove either mod

**Comment by IchigoGames** [comment]
using CraftTweaker i was able to fix the issue by Removing the Crafting Recipe for the radiator and re adding it

**Comment by IchigoGames** [comment]
[general.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/6174133/general.txt) does not support zs file type so i changed it to txt
