### ISSUE TITLE
The engineer's manual doesn't work in 1.16.5

### ISSUE THREAD

**Issue by Fiks75** [BluSunrize/ImmersiveEngineering#4717]
The engineer's manual doesn't work in 1.16.5
Filename: ImmersiveEngineering-1.16.5-4.2.4-134.jar

Error log: https://pastebin.com/7cgSKkLr

**Comment by BluSunrize** [comment]
Looks like an Immersive Petroleum error to me. Make sure you are using the latest version of that.
Also, use the issue template next time.
