### ISSUE TITLE
Unable to charge Capacitor backpack attached to Armor

### ISSUE THREAD

**Issue by Baumbs** [BluSunrize/ImmersiveEngineering#4719]
Once a capacitor backpack is combined with any armor chestplate, it becomes impossible to charge it. Right clicking on any charging station with the chestplate  just results in putting the chestplate on, so once its depleted, you cant use it anymore. this is a serious problem when you want to use the capacitor backpack on strong armor you want to keep on.

**Comment by BluSunrize** [comment]
Take it off the armor, charge it, then put it back on.

Or install Curios and place it into your back slot instead of combining it with armor.
