### ISSUE TITLE
Metal press recipe serializer uses stack instead of ingredient for molds

### ISSUE THREAD

**Issue by ochotonida** [BluSunrize/ImmersiveEngineering#4723]
### Description of the issue:
The recipe serializer for metal press recipes currently uses a stack instead of an ingredient for the mold, which prevents the usage of tags and other custom ingredient serializers.

### Versions
Immersive Engineering: 1.16.5-4.2.4-134

**Comment by BluSunrize** [comment]
Yep that's intentional. We use molds for caching and access recipes quicker. Ingredients are not hashable nor comparable, making them useless as a map key.
