### ISSUE TITLE
[1.16.4]Diesel Generator Model

### ISSUE THREAD

**Issue by Gwolfski** [BluSunrize/ImmersiveEngineering#4725]
### Description of the issue:
The model of the diesel generator appears to be a five-cylinder but the manifolds are only four-cylinder cylinder. However, there is an empty space where the missing connection would go. This location is partly obscured by the exhaust and the air filter, but is noticeable. This is purely an aesthetics issue, but it's been bugging me ever since I first made a diesel gen, and it seems (I think so) as any easy fix, I think the images can explain better than I can in words

### Versions & Modlist
All versions since at least 1.12

from the intake and exhaust manifolds:
![12341](https://user-images.githubusercontent.com/16372976/111551524-4b0e8480-8778-11eb-8923-b9e69ca0c231.png)
![1234](https://user-images.githubusercontent.com/16372976/111551345-e6ebc080-8777-11eb-8f6f-6859a288252a.png)

view of the cylinder heads
![12342](https://user-images.githubusercontent.com/16372976/111551398-01be3500-8778-11eb-8a5d-26bdee1c1dc5.png)

**Comment by BluSunrize** [comment]
This issue is invalid. If you have issues with the model, you can always replace it with a resource pack.
