### ISSUE TITLE
1.16.5-4.2.3-133 Engineer's Manual will not open

### ISSUE THREAD

**Issue by 4angrybadgers** [BluSunrize/ImmersiveEngineering#4726]
### Description of the issue:
When I hold the Engineer's Manual in my hand and right-click to open, it does not open, and prints a chat message stating "1 entries failed to load! Please report this as an issue with your log file!". This initially occurred in my SMP server, but I have replicated it in a fresh single player world with only Immersive Engineering added.
(This issue did not occur in 1.16.4-4.1.2-129, it only appeared after upgrading to 1.16.5-4.2.3-133.)

![Engineer's Manual cannot open](https://user-images.githubusercontent.com/80850556/111662733-31078d00-87de-11eb-9a56-f9ffbc8aa024.png)

### Crashlog:
https://gist.github.com/4angrybadgers/13ddfe1d330cb8bc79842afdf8f9b4e4

### Versions & Modlist
Forge: 1.16.5 36.0.46
IE: ImmersiveEngineering-1.16.5-4.2.3-133

**Comment by malte0811** [comment]
Update IE to build 134.

**Comment by 4angrybadgers** [comment]
I apologize, I had this issue drafted for a week before submitting, and just now realized the new version. Thanks.
