### ISSUE TITLE
Ore Configuration

### ISSUE THREAD

**Issue by SirEndii** [BluSunrize/ImmersiveEngineering#4727]
### Description of the Feature:
Move the ore configuration of the server config to the common config.

### Versions & Modlist
IE-Version: 1.16.5-4.2.4-134
Forge Version: 36.1.1

Modpack creators are not able to deactivate/modify the ore generation, if the config for it is in the individual worlds folders.

**Comment by BluSunrize** [comment]
No.

**Comment by SirEndii** [comment]
And why, "no"? A reason would be friendly, not just "no".

**Comment by BluSunrize** [comment]
Well, the most obvious reason would be that you didn't bother to read the giant disclaimer at the top of the `immersiveengineering-common.toml` file. The one that starts with `#IMPORTANT NOTICE:` and explains *exactly* what modpack makers need to do.
