### ISSUE TITLE
buckets of creosote oil

### ISSUE THREAD

**Issue by bear989** [BluSunrize/ImmersiveEngineering#473]
Im using IE v0.5.4 and added railcraft after the world was started. that's the only two things different from my old world where this worked fine. Unable to get buckets to fill from BC tanks or straight from the coke oven.
![2015-09-29_15 29 43](https://cloud.githubusercontent.com/assets/8433695/10175988/0b6209bc-66c0-11e5-8dfd-ca9a3b051b7a.png)

![2015-09-29_15 29 51](https://cloud.githubusercontent.com/assets/8433695/10175990/136af7ae-66c0-11e5-8964-139c6a360d77.png)

**Comment by mindforger** [comment]
there is an issue with railcraft not properly registering its recipes, wait for both IE and RC to update, as IE had a bug with the coke oven and RC derping with the creosote as a whole
in the meantime try using bottles and the minetweaker script from https://github.com/BluSunrize/ImmersiveEngineering/issues/101 (which is related to your issue) to get wooden tiles

**Comment by bear989** [comment]
I have tried cells and bottles, neither one works. Only I have found was yo open the world with a NBT editor and delete the entry for creosote oil. As soon as I did this, RC took over and everything worked fine.

**Comment by mindforger** [comment]
sounds odd in first place, but nice hint, this could be usefeull to @BluSunrize

**Comment by XFactHD** [comment]
@mindforger by deleting this specific NBT tag @bear989 just forced Forge to recalculate the default fluid for creosote oil (the default fluid is stored per world, not for the whole MC instance).

**Comment by BluSunrize** [comment]
I didn't even know Forge saved the fluids...
That being said though: I check for existing creosote before I register mine and from what it looks like, Railcraft doesn't. So that is Covert's error, I guess?

**Comment by mindforger** [comment]
... the more you know ... <insert jingle here> scnr ;P

**Comment by AEnterprise** [comment]
@BluSunrize there is no need to check if there is already creosote registered, forge saves the fluid per world to use and if the same fluid is registered twice only 1 will be used

**Comment by BluSunrize** [comment]
Well then why is Railcraft not working? .-.

**Comment by AEnterprise** [comment]
cause when railcraft is added you don't register your fluid anymore but forge is trying to use the IE fluid cause that's the one that is saved intro the world to be used

**Comment by mindforger** [comment]
that would partially explain why railcraft recipes do work when IE is loaded after RC ... or was it the other way around?

**Comment by AEnterprise** [comment]
basicly if everyone always registers his fluid, doesn't use the fluid object itself but the fluid string used to register it and checks for all fluid containers containing that fluid using the string there shouldn't be any problems, not sure on what side (or both sides) the cause is in this case though
