### ISSUE TITLE
[1.16.5] mystical agriculture support issue

### ISSUE THREAD

**Issue by bubblegam** [BluSunrize/ImmersiveEngineering#4730]
Using mystical agriculture in garden cloches dosent fully work, nothing grows currently.
you can but the farmland and seeds in, but nothing grows, all default type crops work.

**Comment by bubblegam** [comment]
i have given it power and water already, if you wondered that

**Comment by BluSunrize** [comment]
Yeah uh
...
there is no recipes. If you check JEI, you can see that we add no recipes for Mystical Agriculture. There is no official support for it.
This isn't an issue. It's intentional.
