### ISSUE TITLE
Tools that use fuel not saying they're full

### ISSUE THREAD

**Issue by KrimsonTangent** [BluSunrize/ImmersiveEngineering#4734]
Currently on a custom multiplayer server, whenever I fill up a tool that requires fuel aside from the chem thrower (drill and buzzsaw) the fuel gauge reads empty and the tooltip when you mouse over it says its empty, but when I put them in the engineers workbench it says they're full.

**Comment by BluSunrize** [comment]
Closing this, because you completetly ignored the issue template and I'm not in the mood to ask you for details.

Make sure you're using the latest version of IE.
