### ISSUE TITLE
OpenGL debug message with high severity

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#4735]
### Description of the issue:
After loading a world, the same message chocks up the log which causes occasional frame drops, significant with other mods. Logs probably shouldn't be this messy.

### ~Crash~log:
```...
[HH:MM:SS] [Render thread/INFO] [minecraft/GlDebugTextUtils]: OpenGL debug message, id=2, source=API, type=ERROR, severity=HIGH, message=GL_INVALID_OPERATION in glBlitFramebuffer(depth attachment format mismatch)
[HH:MM:SS] [Render thread/INFO] [minecraft/GlDebugTextUtils]: OpenGL debug message, id=2, source=API, type=ERROR, severity=HIGH, message=GL_INVALID_OPERATION in glBlitFramebuffer(depth attachment format mismatch)
[HH:MM:SS] [Render thread/INFO] [minecraft/GlDebugTextUtils]: OpenGL debug message, id=2, source=API, type=ERROR, severity=HIGH, message=GL_INVALID_OPERATION in glBlitFramebuffer(depth attachment format mismatch)
...
```

### Versions & Modlist
Forge - 36.1.2 (also tried 36.1.0)
IE - 4.2.4-134

**Comment by BluSunrize** [comment]
Full logfile, please. And a debug crash.

**Comment by ghost** [comment]
[logfile](https://paste.ee/p/wp7PB)

Initially MultiMC didn't allow me to upload because it had 17 MB... so i trimmed lines that contained multiples of this:
```[HH:MM:SS] [Render thread/INFO] [net.minecraft.client.renderer.GlDebugTextUtils/]: OpenGL debug message, id=2, source=API, type=ERROR, severity=HIGH, message=GL_INVALID_OPERATION in glBlitFramebuffer(depth attachment format mismatch)```
with:
``` ...```

**Comment by ghost** [comment]
Found a solution from Valhesia 3 Discord server - in ```configs/immersiveengineering-client.toml```, edit ```stencilBufferEnabled``` to ```false```
