### ISSUE TITLE
[1.16.5 | Dev Build] Steel slopes don't change their facing state

### ISSUE THREAD

**Issue by TwistedGate** [BluSunrize/ImmersiveEngineering#4736]
### Description of the issue:
As the title suggests, steel slopes' `facing` state always stays at `north` no matter which direction you face while placing it.

Part of reason im making this issue is because the coker mb from IP does not get recognized as valid unless the structure itself is rotated and built in such a way that the slopes in the structure file are set to `north` aswell.

### Crashlog:
[Crashlog for Modlist](https://gist.github.com/TwistedGate/e35b6636eea414614a7f1799adf72023)

### Versions & Modlist
Forge: `1.16.5-36.1.1`  
IE: `ImmersiveEngineering-1.16.5-4.2.4-134.18`

**Comment by malte0811** [comment]
c8888ac80f3911d0cbf112fbfd3148ef00f33bdd, the property will only be used for slopes placed after that commit.
