### ISSUE TITLE
Game deadlocks with power poles, 1.16.4  ImmersiveEngineering-1.16.4-4.1.2-129.jar

### ISSUE THREAD

**Issue by Matusz27** [BluSunrize/ImmersiveEngineering#4737]
So, I was running Immersive engineering +lots other mods, but I isolated the problem to immersive, I even run the map on a separate modpack with only immersive and the problem is still there while removing it from the other fixed the issue.

Well, the problem is that the game just thread deadlocks and is stuck in one tick, when I try to load a chunk where there should be only a hemp connected power pole, I'll try to remove it via command, but at the same time, it has been there for forever, I can supply the world download, and try be more descriptive, but in the end, it seems a power pole is deadlocking a thread for some reason

**Comment by BluSunrize** [comment]
Update IE, you are far behind.

**Comment by Matusz27** [comment]
The new version is for 1.16.5 and I am using 1.16.4 so it's not compatible, at least is marked as not compatible

**Comment by Matusz27** [comment]
I am fine even with duct taping the new versions to new ones somehow, just well, I kind of unable to switch to 1.16.5. IS there a way of fixing it for 1.16.4 outside trashing the mod out of the pack ?

**Comment by BluSunrize** [comment]
Given that you deleted two posts (I still got the mails):
Just about every 1.16.4 mod can be used on 1.16.5. Forge will load them. Update to .5, update IE, update any mod you can, and use the .4 versions of the ones you can't.

**Comment by Matusz27** [comment]
Yea, I noticed that I can do that, reason I removed the posts, cuz it was no longer valid point, as I found out that I can do that
