### ISSUE TITLE
Visual glitch on multiblock strutures [1.12.2]

### ISSUE THREAD

**Issue by HassaFelipe** [BluSunrize/ImmersiveEngineering#4739]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
Describe what happens, how it affects your game/gameplay and provide screenshots where possible.
I'm have a kind of shadow on multiblock strutures, I know that problem is caused by optifine, but in the most relecent versions as 1.16.5 this problem don't exist. I'm reporting it because i don't know who is the responsible for the problem, i am just searching for help.
![light glitch](https://user-images.githubusercontent.com/60225353/112328363-0497b900-8c95-11eb-9532-bf1fc0570502.png)

![light glitch2](https://user-images.githubusercontent.com/60225353/112328424-14af9880-8c95-11eb-9d49-1feb859591f4.png)

### Crashlog:
If your Minecraft instance has crashed, a file will have been generated in the folder `crash-reports` of your minecraft folder. To understand what has happened, we need to know the content of that file. But please don't just put it directly in your report (that makes it hard to read), upload it to a site like [pastebin](http://pastebin.com) or [gist](http://gist.github.com) and put a link in the actuall bug report.

### Versions & Modlist
IE and Forge versions are mandatory. *Note that saying "latest" is **not** valid. Always give the proper version number*
Other mods should be listed (with their versions) in a [pastebin](http://pastebin.com) or [gist](http://gist.github.com) upload. The easiest way to get these lists is a crashlog, you may force one with F3+C.
If your game crashed (see above) you may omit the modlist, but IE and Forge version would still be nice.

I'm using only using three mods:
IE v0.12-98
Forge v14.23.5.2855
Optifine_1.12.2_HD_U_G5

Also, please try testing an issue in a minimal instance, with just IE, Forge and maybe JEI. That makes elminating compat issues easier.

### Lastly (you may delete this from the report itself)
Please, for the love of all that is voxelbased, **read the contribution guidelines. They are linked to the right in the message box.**
When reporting issues, these are crucial, and the team withholds the right to close an issue for the plain stupidity of not reading and adhering to them.

Thank you for reporting issues, without people reporting them, they wouldn't get fixed. You're helping contribute to this mod and that is much appreciated <3

**Comment by BluSunrize** [comment]
1) Optifine is not supported
2) Support for 1.12 of IE was ceased 9 months ago.
