### ISSUE TITLE
Coke Oven/Blast Furnace don't render properly as blocks.

### ISSUE THREAD

**Issue by Cypher121** [BluSunrize/ImmersiveEngineering#474]
This includes rendering in wrong layer (in front of food particles), not showing block edges on mouse-over and not blocking some rendering (JourneyMap waypoint bean and TC Nitor come to mind). Refinery, for example, does that perfectly, so I assume it can be fixed.

**Comment by cobra** [comment]
What version is this? Are you using optifine or fastcraft?

**Comment by Cypher121** [comment]
0.5.4 and fastcraft

**Comment by BluSunrize** [comment]
No, this is a known bug. It's a vanilla issue though. Water does the same thing. Coke Ovens and Blast Furnaces render on pass 1 because of the insulating glass using coloured transparency.

**Comment by Cypher121** [comment]
You lost me at insulating glass. What does it have to do with these 2 structures?

**Comment by BluSunrize** [comment]
Same block ID, and therefore same ISRBH.

**Comment by Cypher121** [comment]
Doesn't meta get passed to renderer? You can adjust render based on it then.

**Comment by BluSunrize** [comment]
Renderpasses != render. Pass 1 renders infront of particles.

**Comment by Cypher121** [comment]
When I said "adjust render" I meant change renderPass and whatever else needs changing.
[That's the renderer we're talking about?](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/client/render/BlockRenderStoneDevices.java)

**Comment by BluSunrize** [comment]
Yes it is. The problem is that while it's possible to do a block rendered on both passes, it's kinda ugly. I had it before, as that commented code showed, I might just renenable it.

**Comment by cobra** [comment]
What is the point against splitting these blocks into multiple individual blocks?

**Comment by BluSunrize** [comment]
Effort, and me liking to keep block IDs at minimum

**Comment by Kubuxu** [comment]
You can do dual pass rendering and render in pass 0 and pass 1 via one TESR.

**Comment by BluSunrize** [comment]
I can do dual pass rendering /without/ a TESR. Which is preferable since TESRs are laggy rendering.

**Comment by Kubuxu** [comment]
Sorry I meant ISBR, you can do dual pass in ISBR.

**Comment by BluSunrize** [comment]
As my code shows: I've already done it. It's just commented out, because I figured that people wouldn't care that much. It's just a few particles after all. Boy was I wrong.

**Comment by Cypher121** [comment]
Well, if it was just a few particles, I wouldn't care. But when I realized
that thing doesn't render through warded jar EntityItem, that was the last
of like 10 straws I had set away for Coke Oven
