### ISSUE TITLE
[1.16.3] Excavator wheel not forming 

### ISSUE THREAD

**Issue by ExodusR** [BluSunrize/ImmersiveEngineering#4740]
Hello, first thanks for this amazing mods !

I have a little problem with the excavator, the wheel does not form, no matter what i do.. I have use the IE Blocks of steel, we don't have other mods with steel

Thanks for helping me, i attach a screen 
![2021-03-24_20 41 21](https://user-images.githubusercontent.com/73955899/112374615-9bd72d80-8ce2-11eb-96fb-74dda9621764.png)

**Comment by BluSunrize** [comment]
You placed a sheetmetal there, below that dirt block. That should be a steel block.
