### ISSUE TITLE
Hide Wiring Inside Walls Without Adding a lot of Width?

### ISSUE THREAD

**Issue by GalGreenfield** [BluSunrize/ImmersiveEngineering#4743]
### Description of the issue:
I recently made a 3-bedroom house scaffold in Minecraft, and surrounded each wall with a 1-block-wide space + 1-block-wide wall to create hollow walls for feeding wires in the internal space to be able to hide wires.
However it made each wall 2 blocks wider, and when having two such walls attached, I had to add _another_ 1-block-wide wall to insulate/separate the two wiring spaces, so instead of having a wall of a thickness of 1 block between each room, the width is now 5 blocks - just to connect two rooms and hide the wiring.

Is there a mod or any way to do that without adding so much thickness to the walls? I plan to use Immersive Engineering regardless but I don't think it'd be able to solve this issue since it doesn't support wires through blocks anymore. Or can I enable it in a setting?
 Is there anything I can do or is it a tradeoff that I have to make?

### Versions & Modlist:
Not using IE yet, but MC is vanilla

**Comment by BluSunrize** [comment]
Pretty sure there is a config option to allow wires through walls.
Don't fully remember, feel free to check the configs and see if you can find it.

If you can't; tough luck, really. IE's wires were never meant to be hidden inside walls.

**Comment by GalGreenfield** [comment]
> Pretty sure there is a config option to allow wires through walls.
> Don't fully remember, feel free to check the configs and see if you can find it.
> 
> If you can't; tough luck, really. IE's wires were never meant to be hidden inside walls.

Okay, thanks. I haven't tested this yet and will update if there is such option with IE and if it solved my problem.
