### ISSUE TITLE
[MC 1.16.5][Immersive 4.2.4]Garden cloche not outputting any items regardless of output method

### ISSUE THREAD

**Issue by WilCodeBoer** [BluSunrize/ImmersiveEngineering#4748]
### Description of the issue:
I am playing TNP limitless 3 with a friend. We have reached the point where we really want to automate mystical aggriculture using garden cloches because this would seem to be the most optimal way in regards to how much space we can use. 

Apart from one issue the garden cloches work fine but that one issue is really killing it sadly.

We have not been able to use any method to automate the output of the cloches. We have tried several different methods. Using a convyerbelt. Using an exctraction conveyer belt, connection a vanilla chest directly, and multiple item cables. Nothing works sadly. 

![image](https://user-images.githubusercontent.com/17564900/112708378-f70b4a80-8eb1-11eb-9466-e6a5d0724cdf.png)

Cable wreng for cyclic was also used to transform the cable into an extraction cable, this also did not work.

None of these are outputting anything sadly

### Crashlog:
Game didn't crash so no need for this one.

### Versions & Modlist
Immersive Engineering 4.2.4
Forge version 36.1.2 "Not entirely sure if that is the one you mean, if not please let me know"

https://pastebin.com/TmJFfEBi

**Comment by mindforger** [comment]
a forced crash is still better than a directory listing

**Comment by WilCodeBoer** [comment]
I tried to do that but it seems I did it incorrect. I just pressed F3 + C instead of holding it.

Here's the crash report.

https://pastebin.com/Pr1tpJYz

**Comment by BluSunrize** [comment]
The output is the hatch in the glass, with the orange dot on it.
