### ISSUE TITLE
mouseclick event Crash on entering world selection menu. UNKNOWN CAUSE

### ISSUE THREAD

**Issue by HoovySimulator2** [BluSunrize/ImmersiveEngineering#4749]
This is more of a attempt to understand what actually happened. I believe this isn't caused by Immersive Engineering, but the crash report does mention it like below.

{re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:imm_ptl_mixins.json:client.MixinMinecraftClient,pl:mixin:APP:imm_ptl_mixins.json:client.block_manipulation.MixinMinecraftClient_B,pl:mixin:A,pl:runtimedistcleaner:A}

I tried removing Immersive Engineering afterwards (or rather used the "Disable" function of CurseForge Desktop), but the problem still occurred. Hence why I don't believe the problem is caused by this mod. I still want to know what is the cause and that is why I post this here.

### Crashlog:
https://pastebin.com/DfG8YjVX

### Versions & Modlist
Version info is in crash log above. Minecraft is 1.16.5 and Forge forge-36.1.2

**Comment by HoovySimulator2** [comment]
Edit: Corrected stupid spelling mistake...

**Comment by BluSunrize** [comment]
```
-- Affected screen --
Details:
	Screen name: com.github.alexthe666.iceandfire.client.gui.IceAndFireMainMenu
```

I would recommend reporting this to Ice and Fire.

**Comment by HoovySimulator2** [comment]
Ah, ok thanks! As I said, this was the purpose why I posted this, to know what actually happened. Thanks again!
