### ISSUE TITLE
request

### ISSUE THREAD

**Issue by benbenlaw** [BluSunrize/ImmersiveEngineering#4750]
please add back disabling recycler recipes its really annoying to disable otherwise and not useful for mod makers

**Comment by BluSunrize** [comment]
No. It's not coming back. Datapacks exist.

Read the config where that option used to be. It tells you exactly what you have to do.

**Comment by benbenlaw** [comment]
i cant seem to get the datapack to work

**Comment by BluSunrize** [comment]
Then you are doing datapacks wrong. Feel free to join the discord to discuss this in detail, but it is not an IE issue.

https://discord.com/invite/SnUp97WUrN
