### ISSUE TITLE
[1.16.5] Feedthrough not working

### ISSUE THREAD

**Issue by Timmmy001** [BluSunrize/ImmersiveEngineering#4752]
The feedthrough between wire connectors and solid blocks, described in Engineer's Manual, not working.
No rf is transmitted through the block.
The behavior shows in creative and survival.

[Direct](https://github.com/Timmmy001/Fehler_Repo/blob/main/Direct.png)
[Not Feedthrough](https://github.com/Timmmy001/Fehler_Repo/blob/main/Not_Feed%20through.png)

Versions & Modlist:
Forge-36.1.0
ImmersiveEngineering-1.16.5-4.2.4-134

**Comment by BluSunrize** [comment]
Did you actually form the multiblock, or did you just stick connectors on the block and expect it to work?

**Comment by Timmmy001** [comment]
of course stick to it and must run...
Thank you for quick answer sorry for the Sunday disturbance!
