### ISSUE TITLE
[Suggestion] Redstone Equalizer

### ISSUE THREAD

**Issue by vaqxai** [BluSunrize/ImmersiveEngineering#4753]
It would be a block similiar to redstone connector, but when you right click it with a screwdriver, you can set its threshold. It works so that it outputs a full strength redstone signal if a signal of [threshold] strength is input into it. otherwise it doesn't output anything. The behaviour is similiar to rounding in math. It would be benficial to have e.g. chest that triggers something when its full. Basically replacing a 15-block long redstone trail, or comparator mess.

**Comment by BluSunrize** [comment]
Treshold exists these days
