### ISSUE TITLE
[Suggestion] Non-mineral excavator mining/digging

### ISSUE THREAD

**Issue by vaqxai** [BluSunrize/ImmersiveEngineering#4754]
It's a way to dig (perhaps with a toggle, a hammer configuration etc) non-mineral blocks, such as cobblestone, andesite, diorite, blackstone, netherrack, clay with the Excavator. Blocks that are useful for building but not for smelting. Ofc it would have to be placed appropriately (cobblestone,andesite,diorite will be mined if the machine is placed on stone (e.g. in a quarry-type mine), clay near rivers, blackstone on lower y-levels in the nether, etc etc)

P.S. I know that all rock is mineral, but you get what i mean.

**Comment by BluSunrize** [comment]
We already have a few mineral veins in IE that cover this:

- "Igneous Rock", a vein which contains granite, diorite, andesite and obsidian.
- "Silt", a vein which contains clay, sand and gravel.
- "Archaic Digsite", a vein which contains gravel and ancient debris (nether only)

Any further ones you require can easily add yourself via a datapack. I dislike the idea of just making an excavator "special case" for a certain material by placing it "on a block". Veins exist in IE that can do this, but their distribution is random, and I want to encourage exploration.
