### ISSUE TITLE
[1.16.5] Log stays in the sawmill conveyor beginning after processing

### ISSUE THREAD

**Issue by whitebear60** [BluSunrize/ImmersiveEngineering#4756]
### Description of the issue:
After sawmill has finished processing the wood, it stays visually in the beginning of the conveyor belt.

### Versions & Modlist
Forge 36.1.3
IE 4.2.4-134
Manually triggered crash report [here](https://github.com/BluSunrize/ImmersiveEngineering/files/6237125/crash-2021-03-31_16.58.41-client.txt)

### Reproducing the Bug
Video demonstration is avialable [here](https://youtu.be/xXdSvyfroPs)

**Comment by whitebear60** [comment]
Maybe this log need to move through the conveyor...

**Comment by BluSunrize** [comment]
Can't reproduce this on my end.
Can you create this issue with just IE installed, without other mods?

**Comment by whitebear60** [comment]
The animation plays correctly on my end too, will close this as it seems no longer occur.
