### ISSUE TITLE
[1.16.5] Sawblade disappears on sawmill multiblock break

### ISSUE THREAD

**Issue by whitebear60** [BluSunrize/ImmersiveEngineering#4757]
### Description of the issue:
Sawblade disappears after breaking Sawmill multiblock instead of throwing as item or dropping into player inventory.

### Versions & Modlist
Forge 36.1.3
IE 4.2.4-134
Manually triggered crash report [here](https://github.com/BluSunrize/ImmersiveEngineering/files/6237125/crash-2021-03-31_16.58.41-client.txt)

### Video reproduce
Video reproducing the bug is avialable [here](https://youtu.be/Gahrj8KyJXM)

**Comment by malte0811** [comment]
While it not dropping in creative mode (as show in the video) is expected, it also isn't dropping in survival mode. Should be easy to fix.
