### ISSUE TITLE
1.16.5 Radiator Block recipe is missing

### ISSUE THREAD

**Issue by SolsStuff** [BluSunrize/ImmersiveEngineering#4760]
[debug.log](https://github.com/BluSunrize/ImmersiveEngineering/files/6243045/debug.log)
Mod list: SecurityCraft, Abnormals_Core, Apotheosis, AppleTreesRev(forge), ars_nouveau, Artifacts, astral sorcery, atmospheric, AutoRegLib, autumnity, Bag of Yurting, Better End(forge), Better Mineshafts(forge), BloodMagic, Bookshelf, BotanyPots, Bountiful, Buzzier Bees, Caelus(forge), Caged Mobs, Carry on, CodeChickenLib, cofh_core, Corpse Complex(forge), Craftable Elytras, Craftable Saddles, CraftTweaker, Create-mc, Cucumber, Curios(forge), Cyclic, CyclopsCore, dpanvil, Druidcraft, Dungeon Crawl, Dynamic Surroundings, Eidolon, Elementalcraft, Enchantment Descriptions, Endergetic, EnderStorage, Environmental, EvilCraft, Farmers Delight, forbidden_arcanus, geckolib(forge), Globalxp, GreaterEye(forge), hole_filler, Immersive Engineering, Immersive Petroleum, Immersive Portals, infernal expansion(forge), Ironchest, Iron shulker boxes, jei, kotlinforforge, Mekanism, Mekanism Generators, Minecolonies, Mystical Agradditions, Mystical Agriculture, Natures Compass, observerlib, occultism, Omni, Optifine, OuterEnd, Patchouli, Placebo, Platforms, ProjectE, Quark, Relics, Reliquary, Savage and Ravage, shetiphiancore, SilentGear, SilentGems, SilentLib, solcarrot, SpawnerFix, Structurize, Switchbow, The Abyss 2, theoneprobe, Thermal Expansion, Thermal Foundation, Token Enchanter, Tombstone, Toolleveling, Towers of the Wild, Travelers Backpack, Turtlemancy, Uncrafted, upgrade aquatic, valhelsia structures, Waystones, Xaeros Minimap, Xaeros World Map, YungsApi

**Comment by BluSunrize** [comment]
At least one of the mods you use is registrering an empty item as a water bucket.
Your only option here really is to figure out which one.

Easiest way to do that is binary search. Remove half the mods, check if the issue persists. If it does, remove halve of what remains. Otherwise continue with the other half.

Once you figure out which mod did it, feel free to report back.

**Comment by SolsStuff** [comment]
i tested the proper recipe instead of the old one with the full modpack and it worked. however i would like to point out that having the engineering, generator, and radiator blocks not documented in the manual a touch odd due to how important and not self evident the recipes are. If they were the whole situation would have been averted.
