### ISSUE TITLE
1.16.5 Game crashing drill

### ISSUE THREAD

**Issue by Murr88** [BluSunrize/ImmersiveEngineering#4762]
### Description of the issue:
Game crashing when opening the drill tab in the immersive engineer book, also when searching for it in the creative menu.

### Crashlog:
https://gist.github.com/Murr88/8ee403ed8ca818692e062a1fc89e7119

### Versions & Modlist
forge-1.16.5-36.1.0
ImmersiveEngineering-1.16.4-4.1.2-129

**Comment by BluSunrize** [comment]
Update IE, you are way out of date.
