### ISSUE TITLE
Game crashing when drill item is held

### ISSUE THREAD

**Issue by TomSchlessinger** [BluSunrize/ImmersiveEngineering#4763]
Basically, I crafted a drill so I could mine more easily in a 330 mod private modpack I created, the second I added attachments to it and took it out of the engineer's table, my game crashed. Whenever I try loading up my games, the same thing happens again and again.

IE version 1.3.4 forge version 36.0.46

modslist: [mods.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/6247644/mods.txt)

Crashlog: crash-2021-04-02_00.04.18-client - Copy.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/6247654/crash-2021-04-02_00.04.18-client.-.Copy.txt)

Edit: if you find out if its an external mod can you please tell me since I have no idea how to read crash reports

**Comment by BluSunrize** [comment]
Report to modular powersuits please.
