### ISSUE TITLE
[1.16.5] Block of Uranium Recipe

### ISSUE THREAD

**Issue by InLoveWithCocoa** [BluSunrize/ImmersiveEngineering#4764]
The block of uranium recipe only accepts IE uranium in the middle slot

**Comment by BluSunrize** [comment]
Yup, that's intentional, all our metal blocks do that.
This is a joint strategy on recipe behavior followed by Mekanism and TCon among others. It allows users to craft the specific blocks from a mod by making the central ingot the "deciding" one, while all the other ones are tag based.
