### ISSUE TITLE
issue with forming the squeezer

### ISSUE THREAD

**Issue by neoguyvery** [BluSunrize/ImmersiveEngineering#4766]
Hi all!

I trie to form the squeezer , i see some post with the same bug i cant form the squeezer i'm on immersive engineering 1.16.5-4.2.4-134.
I use normal piston and i click on the good barrel but its just open this one...

Anyone know what i should try? Should i desactivate something or  else?

**Comment by BluSunrize** [comment]
Provide pictures, or we can't help you.

**Comment by neoguyvery** [comment]
![2021-04-03_11 09 43](https://user-images.githubusercontent.com/81835868/113474011-6a422d00-946d-11eb-9fea-653d00047740.png)
![2021-04-03_11 10 10](https://user-images.githubusercontent.com/81835868/113474012-6c0bf080-946d-11eb-9a6a-da4156bf2175.png)
![2021-04-03_11 11 35](https://user-images.githubusercontent.com/81835868/113474014-6e6e4a80-946d-11eb-90df-bed5775100d8.png)

ok i upload some view

**Comment by BluSunrize** [comment]
Those are not barrels from, Immersive Engineering. You are using vanilla barrels, they are completely different.

**Comment by neoguyvery** [comment]
Thanks for all, i thought they was good because they check the guide when i have them in the inventory.... Oups no they didnt check this guide.... im so BAD!! Sorry XD
