### ISSUE TITLE
Engineer's Voltmeter

### ISSUE THREAD

**Issue by betacyth** [BluSunrize/ImmersiveEngineering#477]
I have a problem going through open doors while holding the voltmeter.

**Comment by cobra** [comment]
Sounds very bizarre, but I can confirm this for doors I opened with the voltmeter. I can walk through doors opened by a bare hand without any problem while holding the voltmeter. When it happens, my viewing/head angle and position get reset quite often, I can't look up or down while trying to walk through the door. WTF?
version: current master branch, 3a3ba83

**Comment by liamjarvisman** [comment]
what version of IE are you using?

**Comment by betacyth** [comment]
0.5.4

**Comment by liamjarvisman** [comment]
are you using your own modpack or a public one?

**Comment by cobra** [comment]
That's completely irrelevant when I'm able to reproduce it with the current development version and a minimal set of mods, you can stop this version/mods stuff, it's not helping -.-
I just don't have an idea where to start looking for the cause.

**Comment by liamjarvisman** [comment]
I wanted to know because it might be another mod causing the problem.
Are you using a vanilla door or a modded one?

**Comment by betacyth** [comment]
I've been using MC doors. Nothing fancy just wood. I'm running 0.5.4 and I have well over 100 mods.

**Comment by betacyth** [comment]
The solution to getting through the door is to close it and deselect the voltmeter slot and then open the door and go through it.

**Comment by BluSunrize** [comment]
Sounds like desync, doesn't it, @cobra?
Open the door with the voltmeter then break or place a block next to the door. if it closes, it's desync.

**Comment by cobra** [comment]
nah, it's totally weird, not like the door is closed, more like the space of it got filled by weird bouncy stuff.  Neighbouring block changes do not change it. Have you tried it yourself? Right-click a normal door with the voltmeter, then try to walk through and keep w pressed - bouncy bouncyness ensues, even when not holding the voltmeter.
Also - IE desyncing vanilla doors? What is this, Witchery? \*scnr\*
I'm really confused about this, but I also haven't gotten to some in-depth debugging, possibly involving a dive into vanilla. IE code seems fine to me after a cursory look over the relevant IETool code.

**Comment by cobra** [comment]
Heh, it's really a desync - between client and server. The client has different metadata than the server and after relogging the pseudo-open door is closed. Placing blocks all around the door does not fix it, only reloading everything does. That explains the movement reset as well.

Cause: the voltmeter always returns true in `onItemUseFirst`, even when it's not doing anything. Didn't notice at first glance.
Fixed and pushed to https://github.com/cobra/ImmersiveEngineering/commit/e27ca5b4d6b6240ea03a46242c6c34585fc2b891

**Comment by BluSunrize** [comment]
I'll just fix this locally, no need for a PR ^^
