### ISSUE TITLE
[1.16.5] Charcoal Pit and Immersive Engineering conflict

### ISSUE THREAD

**Issue by Cynix32** [BluSunrize/ImmersiveEngineering#4770]
### Description of the issue:
This is the same issue as EnderiumSmith/CharcoalPit2#1. The dev told me to post the issue here.

When Charcoal Pit is installed along with Immersive Engineering, Concrete becomes uncraftable. The recipe for the mixer is gone, and so is the crafting table recipe that includes water. This makes concrete unobtainable. EnderiumSmith mentioned that this may have to do with fluid crafting recipes.

### Crashlog:
No crashlog, but console spits this out when loading a world:
pastebin.com/wQm9gz4J

### Versions & Modlist

CharcoalPit[1.16.5]-2.9.jar
ImmersivePetroleum-1.16.5-3.2.0-3.jar
*I also tested this bug without immersive petroleum installed, it still persists.
ImmersiveEngineering-1.16.5-4.2.3-133.jar
jei-1.16.5-7.6.1.75.jar

GraalVM Java 8
MC 1.16.5
Forge 36.1.3 & 36.1.4

**Comment by malte0811** [comment]
Known issue, fixed in 339e46f44a66b2cc923e239fe3db97e74497110b. It's still good to know which mod was the other side of that interaction, even though the bug was 100% on our side.
