### ISSUE TITLE
Il Motore Diesel prima funzionava e ora non più.. Parte e si ferma subito.. Aiutatemi perfavore 

### ISSUE THREAD

**Issue by Fr0s7L1n3** [BluSunrize/ImmersiveEngineering#4771]
![16176448304934710802439385874193](https://user-images.githubusercontent.com/81985439/113606110-d7111f00-9647-11eb-8334-823ef9b7cb85.jpg)

**Comment by BluSunrize** [comment]
1) English only
2) Use the issue template
