### ISSUE TITLE
[1.16.5-5.0.0-pre 36] Razor Wire has black areas where it should be transparent

### ISSUE THREAD

**Issue by Paprika1234** [BluSunrize/ImmersiveEngineering#4772]
### Description of the issue:
When the razor wire is placed, the model shows black where it should be transparent. Screenshot included. 

### Crashlog:
https://pastebin.com/kZ6nH068 Manual Crash that Blu told me to do

### Versions & Modlist
forge-1.16.5-36.1.1-client.jar   
FarmersDelight-1.16.3-0.4.0.jar              
ImmersivePetroleum-1.16.5-3.2.0-3_DEV-6.jar  
forge-1.16.5-36.1.1-universal.jar       
titanium-1.16.5-3.2.8.jar     
Patchouli-1.16.4-50.jar             
Transport-1.16.5-3.5.0.jar            
immersiveposts-1.16.5-4.1.0_DEV-1.jar  
ImmersiveEngineering-1.16.5-5.0.0-pre.36.jar
AutoRegLib-1.6-47.jar   
Quark-r2.4-308.jar 
jei-1.16.4-7.6.1.73.jar

![2021-04-06_15 14 40](https://user-images.githubusercontent.com/81446515/113780406-6a039500-96ec-11eb-88d7-30fc730dbe98.png)
![2021-04-06_15 14 36](https://user-images.githubusercontent.com/81446515/113780426-6ec84900-96ec-11eb-8e06-b068e89e5958.png)

**Comment by XFactHD** [comment]
Try enabling `forgeLightPipelineEnabled` and `experimentalForgeLightPipelineEnabled` in the forge-client.toml config file.
