### ISSUE TITLE
[1.16.4] Bundled Cables and CC:T

### ISSUE THREAD

**Issue by FloppyCDdrive** [BluSunrize/ImmersiveEngineering#4775]
Dear Devs, 
Moin Malte

Would it be possible to also Implement the Bundled cables output support via Computers of CC / CC Tweaks for Mincraft 1.16.4?
Since a lot of mods are still on 1.16.4, it would be awsome if you have time for this :)

MFG
Floppy

**Comment by BluSunrize** [comment]
We are not updating 1.16.4 anymore. Go update to 1.16.5, just about every .4 mod will work on it, because Forge force-loads them.
