### ISSUE TITLE
liquid concrete is blue

### ISSUE THREAD

**Issue by lordi-erez** [BluSunrize/ImmersiveEngineering#4776]
![image](https://user-images.githubusercontent.com/44799224/114134251-15d8fa80-9910-11eb-9100-a01c2786d304.png)

i tried it with version 4.2.4-134
both with other mods, and in an empty instance

**Comment by malte0811** [comment]
![2021-04-09_09 31 41](https://user-images.githubusercontent.com/10406104/114145277-84b95200-9916-11eb-91de-39f9a0c27a3a.png)

I'm unable to reproduce this. Can you post a screenshot that at least doesn't *obviously* have other mods installed?

**Comment by BluSunrize** [comment]
Addendum to what Malte said:

Try it without any other mods, then produce a debug crashlog by holding F3+C for 10 seconds. Upload that crashlog to https://gist.github.com and link it here.

**Comment by lordi-erez** [comment]
ok, just a minute

**Comment by lordi-erez** [comment]
![image](https://user-images.githubusercontent.com/44799224/114180383-cb27a480-9948-11eb-8b00-a3d44c39903d.png)
https://gist.github.com/iJustBuildUE4FromSource/c08681dac6a9e3cf775565adc3edb47f

**Comment by BluSunrize** [comment]
And now do it again, without Optifine.

**Comment by lordi-erez** [comment]
ohhhh, maybe that's the problem
