### ISSUE TITLE
[ImmersiveEngineering-1.16.5-4.2.4-134] Copper Ore spawn being set to 0 by modpack

### ISSUE THREAD

**Issue by jbeeve** [BluSunrize/ImmersiveEngineering#4778]
### Description of the issue:
Copper ore is not spawning when creating a world. When checking the "immersiveengineering-server.toml" file, vein_size is set to 0. Have tried setting vein_size to 16 and retrogen_enable to true but no change happens. Have also deleted all config files to try and reset but the modpack forces the vein_size to 0

### Versions & Modlist
[ImmersiveEngineering-1.16.5-4.2.4-134] 
[Forge 1.16.5-36.0.42]
[Automation Nation! 1.3.0]

Modlist

AppleSkin-mc1.16.2-forge-1.0.14
AppleTreesRev-Forge-1.16.5-v1.0
architectury-1.8.131-forge
automaticdoors_1.16.5-1.8
AutoRegLib-1.6-47
CalemiUtils-1.16.4-1.0.6
carryon-1.16.5-1.15.3.13
chunkloaders-1.1.6-mc1.16.5
cloth-config-4.11.15-forge
Clumps-6.0.0.17
collective-1.16.5-2.25
controllable-0.11.0-1.16.3
Controlling-7.0.0.14
CraftableSlimeBalls
CraftTweaker-1.16.5-7.1.0.148
createaddition-1.16.4-20210303a
create-mc1.16.3_v0.3e
CreateTweaker-1.0.0.9
CustomStartingGear-1.16.4-2.0.2.1-universal
dankstorage-3.16
easy_villagers-1.16.5-1.0.7
EasyPaxel(1.16.4) - 1.0.10
engineersdecor-1.16.4-1.1.9
fancymenu_2.0.1_MC_1.16.2-1.16.5
FarmersDelight-1.16.3-0.3.2
FastLeafDecay-v25
forgeautofish-2.0.3-1.16.x
ftb-gui-library-1605.2.1.41-forge
ftb-quests-1605.2.0-build.33-forge
ftb-ultimine-1605.2.0-build.25-forge
fullbrightnesstoggle_1.16.5-1.2
globalxp-1.16.5-v1.7.1
growthcontrols-1.16.5-1.0.2
ImmersiveEngineering-1.16.5-4.2.4-134
ImmersivePetroleum-1.16.5-3.2.0-3
ImmersiveRailroading-1.16.4-forge-1.8.0.1
industrial-foregoing-1.16.5-3.2.10.1-decb7ae
InventoryHud_[1.16.2-1.16.5].forge-3.2.2
inventorypets-2.0.12
invtweaks-1.16.4-1.0.1
ironchest-1.16.4-11.2.10
ironfurnaces-1.16.5-2.6.5
item-filters-1605.2.4-build.30-forge
ItemPhysicLite_v1.4.7_mc1.16.4
jei-1.16.4-7.6.1.71
JEITweaker-1.16.5-1.0.1.14
jev-1.16.3-2.0.1
konkrete_1.1.4_MC_1.16.2-1.16.5
MinersAdvantage-1.16.5-1.9.1.180
MixinBootstrap-1.0.5
moreminecarts-1.02
morevanillalib-1.16.4-1.4.0
MouseTweaks-2.14-mc1.16.2
movingelevators-1.2.33-mc1.16.5
notenoughcrashes-3.1.8-forge
obfuscate-0.6.0-1.16.3
OpenLoader-1.16.5-9.0.2
OverpoweredMending-Forge-1.16.5-2.2.2
Patchouli-1.16.4-50
Placebo-1.16.4-4.4.1
prefab-1.6.5.0
QuarkOddities-1.16.3
Quark-r2.4-308
simplybackpacks-1.16.3-1.4.13
solpotato-1.16.X-1.1.0
sophisticatedbackpacks-1.16.4-2.2.8.240
StorageDrawers-1.16.3-8.2.2
supermartijn642configlib-1.0.5a-mc1.16
supplementaries-1.16.5-0.10.3b
tanknull-2.3-1.16.4
theoneprobe-1.16-3.0.7
titanium-1.16.5-3.2.8
Toast-Control-1.16.4-4.3.1
tombstone-1.16-6.3.3
torchmaster-2.3.6
Torchplacer-1.16.4-v1.0.0
TrackAPI-1.16.4-forge-1.2.1
UniversalModCore-1.16.4-forge-1.0.1
vanillahammers-1.16.4-2.2.0
vehicle-mod-0.45.2-1.16.3
Waystones_1.16.5-7.4.0
WorldEdit-CUI-FE3-1.16.5-3.0.9
worldedit-mod-7.2.4
Xaeros_Minimap_21.5.0_Forge_1.16.5
XaerosWorldMap_1.13.1_Forge_1.16.5

**Comment by BluSunrize** [comment]
Take it up with the modpack then? If they set those configs, they probably have a reason...
