### ISSUE TITLE
Immersive Engineering - Exception generating new chunk when joining

### ISSUE THREAD

**Issue by 8kyro** [BluSunrize/ImmersiveEngineering#4779]
### Description of the issue:
My server crashed as soon as I (or a friend) joins my server. I play Valhelsia 3 with my friends at 5gb ram allocated on the server and 5gb whilst playing. I have 16gb on my pc but 100% is used when I used 10gb. I dont have anything else in the background so I dont know why but thats besides the point just thought i'd share that.

Problem - Server crashes when I or a friend joins the server with the error "Exception generating new chunk" or something like that.

Everything worked with the server until my friend and I went to explore and we both crashed at the same time. Something with a chunk?

### Crashlog:
https://pastebin.com/fJrF0QDW

### Versions & Modlist
IE - 4.2.4-134
Forge Version - 1.16.5 - 36.1.3
Modlist should be in the crashlog. If it's not here is the modpacks modlist: https://www.modpackindex.com/modpack/21671/valhelsia-3-1165

**Comment by ghost** [comment]
Same issue here on Valhelsia3 (modpack version 3.3.1 | Same version of IE | Forge 36.1.13)
