### ISSUE TITLE
finding config

### ISSUE THREAD

**Issue by jackyboy1992** [BluSunrize/ImmersiveEngineering#4780]
### Description of the issue:
ok so not actually an issue but ive been searching for this for 2 days im trying to add a recipe to the garden cloche or change one to get an output but cant seem to find the config to change it how easy is it also to change a recipe output.
im playing Enigmatica 6  so it uses kubejs if that changes anything

**Comment by BluSunrize** [comment]
Recipes are done with datapacks, not config files.

Please read the vanilla wiki on datapacks to understand how recipes are loaded. After that, you can figure out how to add a recipe specifically for IE.

For future questions, please visit the discord, this issue tracker is a poor format to answer questions about custom recipes on:
https://discord.com/invite/SnUp97WUrN
