### ISSUE TITLE
[1.16] Rockcutter Crash

### ISSUE THREAD

**Issue by thedeerirty** [BluSunrize/ImmersiveEngineering#4782]
### Description of the issue:
Using a workbench to upgrade a buzzsaw into a rock cutter in a workbench causes a crash client side, and to whoever then loads the chunk. I'm no coder, but I believe this (as the crash report points out) is caused by a rendering error on the workbench itself.

### Crashlog:
[crash-2021-04-12_15.59.43-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/6297990/crash-2021-04-12_15.59.43-client.txt)

### Versions & Modlist
IE version: 1.16.4-4.1.2-129
Forge: 36.1.0

Haven't tried with just immersive, but will do as much shortly.

**Comment by BluSunrize** [comment]
You're playing an entirely outdated version.

If you can reproduce this on 1.16.5-134, please reply here again and I'll happily reopen the issue.
