### ISSUE TITLE
i got client crash after i added immersive petroleum

### ISSUE THREAD

**Issue by danielkanjo** [BluSunrize/ImmersiveEngineering#4784]
[crash-2021-04-13_23.43.06-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/6309299/crash-2021-04-13_23.43.06-client.txt)

when i open the Engineer's Manual and open the  Multiblčock Projector then just freezes the game and i got that crash log
i don't know what to do i'm playing minecraft 1.12.2

**Comment by BluSunrize** [comment]
Support for 1.12 was ceased 10 months ago.
