### ISSUE TITLE
Coke Ovens not working on servers (again)

### ISSUE THREAD

**Issue by Dandeliusz** [BluSunrize/ImmersiveEngineering#4785]
I have read the previous thread (#4073) which reported coke ovens not working on multiplayers servers, and it was said it has since been fixed. However I am now having the exact same problem where the Coke Oven does work in my singleplayer world, but not in a multiplayer server.
I can build the oven using 27 coke bricks, then i use my engineering hammer on it which creates the oven and I can open it, put a bucket in it and some coal, but whenever I exit the oven it just drops my items, neither does the little flame turn orange.
I am using the 'all the mods 6' modpack, but I have seen that the updated version of ImmersiveEngineering that they use is: 'ImmersiveEngineering-1.16.5-4.2.4-134' so this is not an outdated version and the fix should've been applied.
Is it possible that this bug has occurred again?

**Comment by BluSunrize** [comment]
Yeah it's ATM's fault. They know about it, they will fix it.

Not an IE issue.
