### ISSUE TITLE
[1.16.5] add tags to items

### ISSUE THREAD

**Issue by Pdiddy973** [BluSunrize/ImmersiveEngineering#4789]
add forge:treated:wood tag to:
treated wood slab
treated wood stairs
and vertical and packaged variants 

and add immersiveengineering:scaffoldings/aluminum /steel
to all aluminum/steel scaffoling blocks

**Comment by BluSunrize** [comment]
Closing this due to blatant disregard for contribution guidelines and any lack of tact.
