### ISSUE TITLE
[suggestion] Wall mounts should transfer energy

### ISSUE THREAD

**Issue by hubertnnn** [BluSunrize/ImmersiveEngineering#479]
Making wall mounts transfer energy will allow for more realistic and better looking builds using your wiring. In real world a cable is connected to wall mount and than goes into the wall. With this change you could place a hidden wire from other mod (eg. kinesis pipe from buildcraft with a facade, or fluxduct with a cover) then a wall mount and connector on that wall mount, It will look better than connector directly on wall.

**Comment by XFactHD** [comment]
Should be a special version of the existing wall mounts because making the existing ones transfer energy could theoretically destroy existing builds.

**Comment by mindforger** [comment]
"Making wall mounts transfer energy will allow for more realistic and better looking builds" 
in real world, either the cables get insulated and are wired through the wall directly (only low voltage rates)
or they are indeed passed through the wall by a special insulated metal bar with typical insulated power connectors on both sides!

The current look and feel with a mount on a (facade hidden, other mod) power conduit is absolutely correct imho ... 

but still, there is a need of some sort of short range, non wire, full block hideable powerbar when you do not have any other power conduits available

**Comment by BluSunrize** [comment]
Nah. I like IE's freestanding wires. Also, adding a second type of connection system, which uses blocks instead of cables kinda undermines anything IE stands for =P
