### ISSUE TITLE
[Suggestion] make steel blocks blast proof like obsidian

### ISSUE THREAD

**Issue by lordi-erez** [BluSunrize/ImmersiveEngineering#4793]
think about it, it's a cubic meter of solid steel, it probably could withstand explosions

**Comment by mindforger** [comment]
if you might ask all the other modmakers out there too that use steel in their mods and all of them agree, this might be possible :D

**Comment by BluSunrize** [comment]
Mindforger kinda nailed it. There are a lot of mods that add steel blocks, having a drastic difference in behavior in those would be a bit odd.

That said, IE already has "Leaded Concrete" which features increased resistance. I don't believe it's as strong as obsidian, but it still withstands explosions, afaik.
