### ISSUE TITLE
IE: Chemical Bath

### ISSUE THREAD

**Issue by OviDiuSSwe** [BluSunrize/ImmersiveEngineering#4797]
Chemical Bath - Multi Block Construction : Works

Chemical Bath - Out lay on Ports When Accessing Outlay : Does not correlate with ports out side outlay.

Current status of working condition : Unknown

Ok i have built a Chemical Bath on a server. It works to build and it looks cool as a chemical Bath. So far looking good och looking cool. But for the life of me i cant make it work. Ports on outside does not correlate with ports in Outlay menu when i access the chemical bath. There are colors on Ports in menu but not on all of them on the machine its self.

So i started looking for information on how to use it. And in my search i could not find any information on the chemical bath. Even the in game manual is rather short on info on chemical bath. No reference to in and out going or item in or item out.

Here are some pics on the machine so we have reference pictures. Front left is a Blue port that i believe is for incoming Chemicals to be placed in the tub. And a Orange/red Port for outgoing Chemicals. And then there is a Square Port on the back side. With a Red Marker above it. And both of them i have no clue what they do. On both left and right sides looks like chute for ether items or some thing else.

[Outlay Menu](https://i.imgur.com/tImIrWr.png)
[Front](https://i.imgur.com/XG0ZKLK.png)
[Back](https://i.imgur.com/nPtWq90.png)
[Left](https://i.imgur.com/Vps7TWq.png)
[Right](https://i.imgur.com/OG601fw.png)

So is this machine operable or is it still in dev stage ? Or am i looking at the problem in a wrong way ? Any info would be great.

**Comment by BluSunrize** [comment]
I have no idea what that machine is.
Immersive Engineering does not add a chemical bath. You must have some addon installed that adds it. I genuinely can't tell you what that thing is or what it does.

Also, this is a terrible issue report, given that you completely ignored the template, and thus omitted any information I could even try to use to help you.
