### ISSUE TITLE
Creative Tab

### ISSUE THREAD

**Issue by Thorinori** [BluSunrize/ImmersiveEngineering#48]
NOTE: This is only an assumption currently

So I was in Creative Mode, tabbing through mods. As soon as I attempted to tab into the page that IE SHOULD be on, my client crashed. I can only assume IE is on that page, since the last mod of the previous page was Harvestcraft. Client Crash log is posted below.

http://pastebin.com/0cPyp4cu

**Comment by AtomicBlom** [comment]
The crash log suggests it's actually an issue with Headcrumbs

**Comment by DoughnutDev** [comment]
You need codechickencore, because of his code.

**Comment by Thorinori** [comment]
I do have codechickencore, and it seems AtomicBlom is right. My bad, probably should have gone through the log more thoroughly. Closing this since it wasn't IE,
