### ISSUE TITLE
[suggestion] post arms should not obstruct the cable

### ISSUE THREAD

**Issue by hubertnnn** [BluSunrize/ImmersiveEngineering#480]
In real life you almost always move energy from wooden post to the ground vertically. Currently that is impossible, cause post arms will obstruct the connection. A solution will be making them an exception for the obstruction calculation.

**Comment by XFactHD** [comment]
I would rather suggest doing the same thing as #479.

**Comment by cobra** [comment]
That would almost certainly need a complete re-implementation of the raytracing function, as the one minecraft (and IE) uses aborts its raytracing at the first block it hits - including the one it's starting from. I fixed the latter problem and you can now (not really, it's just the current development version, not released one) wire a lot more configuration which weren't possible in 0.5.4.
Example: 
![2015-10-02_15 44 45](https://cloud.githubusercontent.com/assets/163331/10247996/098dd56c-691d-11e5-896a-7e3d80f694ca.png)
You can also place the connectors on the underside of the arms which will automatically flip:
![2015-10-02_15 45 56](https://cloud.githubusercontent.com/assets/163331/10248011/1f0ac346-691d-11e5-8b87-f81200d5b957.png)

**Comment by BluSunrize** [comment]
Yep. And I won't make a custom tracer for this.
