### ISSUE TITLE
[1.16] Item Router uses the terms "OreDictionary" and "damage value" even though neither exist in 1.16

### ISSUE THREAD

**Issue by aaronhowser1** [BluSunrize/ImmersiveEngineering#4800]
### Description of the issue:
Describe what happens, how it affects your game/gameplay and provide screenshots where possible.
![image](https://user-images.githubusercontent.com/15698722/116656440-4d0c5b80-a952-11eb-990d-3bea66fa61ad.png)
![image](https://user-images.githubusercontent.com/15698722/116656449-50074c00-a952-11eb-8979-1585b13e2363.png)

### Versions & Modlist
Forge: 36.1.4
IE: ImmersiveEngineering-1.16.5-4.2.4-134

**Comment by BluSunrize** [comment]
Yeah, that's a valid complaint. I need to rework that thing.
