### ISSUE TITLE
[1.16.5 | pre.66] Pipes visually "disconnect" upon reloading world

### ISSUE THREAD

**Issue by TwistedGate** [BluSunrize/ImmersiveEngineering#4807]
### Description of the issue:
As the title suggests they just stop looking like they're connected visualy, but functionaly didnt change (they still move fluid from A to B regardless)

Did some before and after screenshots
![Before](https://user-images.githubusercontent.com/31029668/117125708-3030b780-ad9a-11eb-8d28-a100430861c5.png)
![After](https://user-images.githubusercontent.com/31029668/117125713-30c94e00-ad9a-11eb-9ae1-8e733a34deb4.png)

### Versions & Modlist
Forge: `1.16.5-36.1.0`
IE: `1.16.5-5.0.0-pre.66`

**Comment by malte0811** [comment]
1. Is this on a server (the server?) or in singleplayer?
2. Does F3+A/other types of chunk update fix it?
3. Does `/ie resetrenders` and then a chunk update fix it?

**Comment by TwistedGate** [comment]
1. Singleplayer
2. Not realy, it does sort of fix itself when hammering one of the sides
3. Nope `/ie resetrender` does not fix it

**Comment by TwistedGate** [comment]
Regarding `2`: It does sort of fix itself when hammering one of the sides

**Comment by malte0811** [comment]
Apparently my fix did not (fully) work…
