### ISSUE TITLE
Server halts due to Ticking Entity.

### ISSUE THREAD

**Issue by thakyZ** [BluSunrize/ImmersiveEngineering#4808]
A friend's Minecraft server has been crashing due to a ticking entity and this line of code is possibly to blame.
https://github.com/BluSunrize/ImmersiveEngineering/blob/1ba426ccd089247a7954cd50edcafe66bd63d1ce/src/main/java/blusunrize/immersiveengineering/common/util/SpawnInterdictionHandler.java#L48

Not sure what else may be the reason.
Here is the full crash report if you need it.
https://gist.github.com/thakyZ/5c794771b9b69409b80fb53309cb47d4

**Comment by malte0811** [comment]
I'll close this, if it happens again with a version including the commit above please comment on this issue.
