### ISSUE TITLE
[Direwolf20 1.16 1.9.0]  Industrial Squeezer not assembling

### ISSUE THREAD

**Issue by Mass1milian0** [BluSunrize/ImmersiveEngineering#4809]
### Description of the issue:
so i'm playing direwolf20 1.16.4 1.9.0 solo, and i wanted to set up a industrial sqeezer to make some HOP graphite, however no matter what i try, i cannot make it assemble it, similar to issue [#4502](https://github.com/BluSunrize/ImmersiveEngineering/issues/4502), screenshot of the build here: https://imgur.com/a/DGlVcqy

also a video of what happens when i try to click it with the hammer: https://imgur.com/a/3Lo4S2X

modlist of direwolf20 1.16: https://pastebin.com/SL66KiKV

**Comment by LeoBeliik** [comment]
you're using vanilla barrels instead of IE wooden barrels

**Comment by Mass1milian0** [comment]
> you're using vanilla barrels instead of IE wooden barrels

Humm ill check, however they marked as good (green check) in the engineer book

**Comment by Mass1milian0** [comment]
> you're using vanilla barrels instead of IE wooden barrels

ok that was the issue, sorry for opening a stupid issue, also my bad on the book check thing, i remembered wrong
