### ISSUE TITLE
[feature request] Steel posts posts

### ISSUE THREAD

**Issue by hubertnnn** [BluSunrize/ImmersiveEngineering#481]
If you connect the high voltage relays under the arm of wooden post it will go very close to the ground, two blocks below a low/medium voltage wire that you almost always connect to top of the post.
We need a new post (made of steel) that will be 3 blocks higher, so that hv wires will go above mv.

**Comment by BluSunrize** [comment]
That is what structural arms and steel scaffolding are for. Build some pylons! :D

**Comment by XFactHD** [comment]
That's what I built some time ago: https://cloud.githubusercontent.com/assets/11262040/9443141/c579af6a-4a7f-11e5-8e0f-ead33d73aa40.png.
