### ISSUE TITLE
(Suggestion/Question) Mineral Deposits (1.12.2)

### ISSUE THREAD

**Issue by TimyIsCool** [BluSunrize/ImmersiveEngineering#4812]
Is There Away To Get Custom Ore Veins For The Excavator ? If Not Is The A 1.12.2 Mod For It? I Would Like Veins Of other Stuff. 

(Sorry if this doesn't meet a template or anything, just tell me that)

**Comment by BluSunrize** [comment]
There is full documentation on the Craftweaker wiki.
