### ISSUE TITLE
[1.16.5] Wires/Cables Not Saved by Structure Blocks

### ISSUE THREAD

**Issue by SapphiCat** [BluSunrize/ImmersiveEngineering#4813]
### Description of the issue:

Cables are not saved by structure blocks.

To duplicate:

1. Use a structure block to save an area containing linked cable anchors or wire connectors
2. Use another structure block to load that structure in a new location (or in the same one, in which case the old cable pops off)

"Include entities" setting in the structure block GUI does not change the results.

![2021-05-09_06 55 23](https://user-images.githubusercontent.com/15374656/117563843-723d5000-b05d-11eb-9075-755f0c52a4c9.png)

Given the nature of cables in IE this is more of a feature request than a bug report, especially since this isn't something a survival player should ever encounter. Still, if it's reasonable it would be very useful to the (unfortunately small) group of people who want to include the awesome IE cables in custom generated structures for modpacks. 

### Versions & Modlist

 Minecraft 1.16.5
 Immersive Engineering 4.2.4-134
 Forge 36.1.16

Launched using MultiMC

**Comment by malte0811** [comment]
For the moment this is "working as intended" (as in, I've just accepted the limitation so far), but I agree that it would be a nice feature to have. I'm not sure how feasible it is without some changes in Forge, I'll look into it when I have some time.
