### ISSUE TITLE
[1.16.5 Maven #105] Toolbox GUI Texture Corrupted

### ISSUE THREAD

**Issue by DeadlySwede** [BluSunrize/ImmersiveEngineering#4816]
### Description of the issue:

The texture on the toolbox GUI is corrupted when you open the toolbox. Not white noise though. Looks like it's displaying some other texture of some sort. Texture displayed seems to depend on what mods are loaded but is never correct. Toolbox works fine as long as you can guess where to click on things.

[Screen Shots](https://imgur.com/a/BhBI9oE)

### Crashlog:

None

### Versions & Modlist

- Minecraft 1.16.5
- Forge 36.1.1
- ImmersiveEngineering-1.16.5-5.0.0-pre.73

Note: Also happens with latest modlist on IE test server.

**Comment by TwistedGate** [comment]
Does this for me aswell
![grafik](https://user-images.githubusercontent.com/31029668/118615913-80a80c00-b7c1-11eb-9140-732f220fb65a.png)
