### ISSUE TITLE
Arc Furnace black texture when with Optifine Shaders

### ISSUE THREAD

**Issue by Crond-Fx** [BluSunrize/ImmersiveEngineering#4819]
### Description of the issue:
When Arc Furnace melts something, the pouring metal texture is black if I have Optifine Shaders enabled. 
Screenshot: [http://dl3.joxi.net/drive/2021/05/14/0033/0910/2184078/78/3372cac732.png](http://dl3.joxi.net/drive/2021/05/14/0033/0910/2184078/78/3372cac732.png)

### Crashlog:
No, it's not crashed

### Versions & Modlist
Optifine version: OptiFine HD U G8 pre14
Game version: 1.16.5
Forge version: 36.1.0
IE version: 4.2.4-134
Shader: [Complementary Shaders v3.13](https://www.curseforge.com/minecraft/customization/complementary-shaders)

**Comment by BluSunrize** [comment]
Optifine continues to be unsupported.
