### ISSUE TITLE
IE Completely breaks using railcraft

### ISSUE THREAD

**Issue by krc4267** [BluSunrize/ImmersiveEngineering#482]
Playing around with IE in a modpack I threw together and tried to make a train. Found out that IE's Creosote overwrites Railcraft's creosote and IE's creosote can't be used by railcraft.

However, Railcraft's creosote can be used with IE but there is no way to get it without cheats. If there was a way to disable IE's creosote that would fix it. Yes I looked in the config, and if I missed it... well sorry! I used the find function to look for it but it wasn't there. Thanks!

-KRC

**Comment by mmermerkaya** [comment]
See #101 for a minetweaker solution.

**Comment by cobra** [comment]
It's a Railcraft problem, but this has been fixed by now - we just need to wait for a new railcraft update. See https://github.com/CovertJaguar/Railcraft/issues/662.
This issue can be closed.

**Comment by BluSunrize** [comment]
Correct. And it was never my fault to begin with, just to clarify. I don't override, in fact, if IE loads after RC, I use Covert's fluid >_>

**Comment by krc4267** [comment]
Excuse my ignorance please! Thank you for the help.
