### ISSUE TITLE
[1.16.5] IE Crash from EnergyMeterTE in Shipwreck feature during chunk gen

### ISSUE THREAD

**Issue by ZornTaov** [BluSunrize/ImmersiveEngineering#4821]
### Description of the issue:
When players go near a certain chunk that is trying to generate a Shipwreck Feature, the server crashes because of a NPE from an EnergyMeterTileEntity trying to get it's block bounds during chunk generation. Starting the server back up runs fine, but when that user logs in the server crashes again trying to generate that chunk. For now I've moved that user back to spawn using NBTExplorer.

### Crashlog:
https://pastebin.com/QwMUgnuK

### Versions & Modlist
Forge: 36.1.16
ImmersiveEngineering: 1.16.5-4.2.4-134
rest of mods in crashlog above.

**Comment by malte0811** [comment]
Fixed by 4517cbd2a39af487df8e66c8ef4873ca7d278d9a, I completely forgot I'd already fixed this.
