### ISSUE TITLE
[1.16.3] Excavator digging but no minerals output

### ISSUE THREAD

**Issue by ExodusR** [BluSunrize/ImmersiveEngineering#4823]
Hello,

As i said in the title my excavator dig but i have no minerals, i explain :

I run the excavator on a chunk and all was good, he finish digging and the next day i move him on the chunk beside, but when i launch him he dig the hole below him and no minerals are output.. I move him on the chunk still nearby and it's the same..
I check if my Diesel generator provided enough power and it's good, i very don't know why :/
Please help me if someone have an idea  
![2021-05-17_19 54 16](https://user-images.githubusercontent.com/73955899/118691777-b2dd5c00-b809-11eb-8982-21a51fce10ea.png)
![2021-05-17_19 54 15](https://user-images.githubusercontent.com/73955899/118691814-ba9d0080-b809-11eb-924b-d90905c945e8.png)
![2021-05-17_19 54 15](https://user-images.githubusercontent.com/73955899/118691911-d4d6de80-b809-11eb-9f04-66148cafa71b.png)

**Comment by BluSunrize** [comment]
Excavators are not chunk based in 1.16.
You need to use the survey tools and core sample drill to look for mineral veins.

All of this is documented in the manual, please read it.
