### ISSUE TITLE
[Suggestion] Provide config option to turn off village layout manipulation

### ISSUE THREAD

**Issue by FiammaVerde** [BluSunrize/ImmersiveEngineering#4824]
Minecraft: 1.16.5
Seed: -8836811803329303795
Village Bell Coordinates: x=-4; z=-354; y=65

Java: AdoptOpenJDK (jre-11.0.11.9-hotspot)
Forge: 36.1.23

Immersive Engineering: 4.2.4-134

On a new world on a fresh install (only Forge) vs on the same regenerated world with IE added, the same village looks different.

I couldn't find any documentation on what exactly IE changes on worldgen or a config option to turn this behaviour off.

I do like the single brick house with the IE-specific villager that sometimes spawns (not pictured) and I was wondering if only that house could be added without changing the basic village layout (again, optimally as a toggable config option).

Just a suggestion, thanks for the nice mod!

Without IE:

![Forge Village](https://user-images.githubusercontent.com/60235666/118803134-457e0980-b8a3-11eb-9c85-783a683375d3.png)

With IE:

![IE Village](https://user-images.githubusercontent.com/60235666/118803171-529af880-b8a3-11eb-8b16-6baa5600988b.png)

**Comment by BluSunrize** [comment]
The layout is based on all the possible houses that can generate. We have no influence over this. It's vanilla code.

**Comment by FiammaVerde** [comment]
So if I understand this correctly, the moment IE or another mod adds it`s house to the village structure pool it randomises the village layout? That would explain a lot.

Sorry, I`m still testing 1.16 mods before leaving my 1.12 world behind and am unfamiliar with the Village & Pillage Jigsaw stuff.

**Comment by BluSunrize** [comment]
Sorta, yeah. There is no "proper" hooks to actually add custom village stuff. Forge doesn't provide any.

So we insert our villager houses into the vanilla lists, and my assumption is that this affects the random seeding of villages. I don't understand the entire generation code in vanilla myself, and it has never been important either. We got our houses to generate, and that's all I care about :'D

**Comment by FiammaVerde** [comment]
Yeah that makes sense, thank for the explanation! :D
