### ISSUE TITLE
Advancement Recipe Unlocks Incorrect

### ISSUE THREAD

**Issue by Electrocutor** [BluSunrize/ImmersiveEngineering#4826]
### Before reporting:
Did not find any duplicate issues

### Description of the issue:
When you gain the materials needed to craft items in IE, it does not unlock/add-to-recipebook the recipe for making those items. The current advancement recipes are set to only unlock after the item is already made. In the case of GameRule doLimitedCrafting, this makes IE unplayable in survival mode without using cheats.

### Crashlog:
No crash

### Versions & Modlist
Forge: 36.1.23
IE: 4.2.4-134

### Suggestion
Recipe advancements can be easily automated by reading the components from json in the recipes folder.

If you want to make them more interesting, like how Vanilla Minecraft only unlocks the boat recipe after you enter water, it would take more time. You could in fact build a story-progression into advancements that helps guide people through learning IE through various triggers, conditions, rewards (recipe unlocks), etc. You could create your own IE-specific triggers/conditions/functions as well if you so chose.

Relevant Links:
https://minecraft.fandom.com/wiki/Advancement/JSON_format
https://sourceblock.net/beta/guides/fundamentals/data-packs/advancements

**Comment by BluSunrize** [comment]
Do you have specific examples of these issues?

Because in my testing just now, I find that I unlock the recipe for Kiln Bricks (for the alloy smelter) after acquiring brick.

If you have a list of recipes that do *not* follow these conventions or are missing an unlock condition, I'll happily amend them.

**Comment by MechaStalinTron** [comment]
I've got this same issue in 1.18.1. The Kiln Bricks are fine, But I can't unlock the coke oven bricks... Ive built thedynamo for the windmill and the 8 sails.. but it hasnt unlocked the ability to build the windmill

**Comment by MechaStalinTron** [comment]
Just did a run to the nether to get nether brick to unlock coke oven in case that was needed. but it doesnt unlock anything either. Hope we can get a fix soon

**Comment by BluSunrize** [comment]
I think I know what the issue here is now. Definite messup in our recipe setups. I'll give this another look over today and see if I can get it fixed for the immediate release.
