### ISSUE TITLE
Workbench dupe and block voiding 

### ISSUE THREAD

**Issue by RoxasLamprunge** [BluSunrize/ImmersiveEngineering#4827]
### Description of the issue:
if the workbench is placed inside a 1 block gap it will void the block to the left no matter what it is including bedrock.
right clicking the bench or breaking it with an axe yields 2 

Video : https://youtu.be/7CC7-cINGxw

### Versions & Modlist
Forge 36.1.0
IE 1.16.5-4.2.4-134

**Comment by jinkhya** [comment]
Hello sorry about bumping this old-ish thread but it appears this exact issue is back. I tested it in 1.0.3-138.
Thanks in advance,
Jin
