### ISSUE TITLE
Loading error-crash after updating IE

### ISSUE THREAD

**Issue by IchigoGames** [BluSunrize/ImmersiveEngineering#4831]
### Description of the issue:
crash on startup from loading error of mod i think its due to updated version of ImmersiveEngineering-1.16.5-5.0.0-135

### Crashlog: 
https://pastebin.com/4V8UncJq

### Versions & Modlist
ImmersivePetroleum-1.16.5-3.2.0-3.jar
ImmersiveEngineering-1.16.5-5.0.0-135
Forge 36.1.24
Minecraft 1.16.5

**Comment by BluSunrize** [comment]
You didn't read the changelog.
