### ISSUE TITLE
Question about crafttweaker and disabling recipes

### ISSUE THREAD

**Issue by Exzept1on** [BluSunrize/ImmersiveEngineering#4832]
I wanted to find out if there is any universal command to remove all recipes from any multiblock. For example, I want to delete all recipes from MetallPress. Or some other way to do it quickly.

Version 1.12.2

**Comment by BluSunrize** [comment]
If there is, you find it in the official Craftweaker documentation.

Support for 1.12.2 was stopped 10 months ago.

**Comment by Exzept1on** [comment]
> If there is, you find it in the official Craftweaker documentation.
> 
> Support for 1.12.2 was stopped 10 months ago.

There's nothing there. So I asked you if there might be any workarounds.

**Comment by BluSunrize** [comment]
There is a `removeAll` function. If it's not in Craftweaker docs, then I guess noone bothered to add it.

**Comment by Exzept1on** [comment]
> There is a `removeAll` function. If it's not in Craftweaker docs, then I guess noone bothered to add it.

Okay, I get it. In a nutshell, how it works. For example if I want to delete all recipes from MetallPress
