### ISSUE TITLE
[1.16.5] Dedicated server- player kicked and unable to log in after jumping over a Conveyer Dropper - net.minecraft.crash.ReportedException: Colliding entity with block

### ISSUE THREAD

**Issue by ProsperCraft** [BluSunrize/ImmersiveEngineering#4833]
### Description of the issue:
Player jumped over a conveyer dropper and now unable to log in - 
[net.minecraft.network.NetworkSystem/]: Failed to handle packet for /73.28.181.171:64848
net.minecraft.crash.ReportedException: Colliding entity with block

### Crashlog:
Debug log- see the end of the log where he tries to log in several times for stacktrace.
https://gist.githubusercontent.com/ProsperCraft/79f5824406d1c7f2c41da7bf0de926cf/raw/63a322f7620b03a624832e237f6177d8f4d0c53b/gistfile1.txt

### Versions & Modlist
forge-1.16.5-36.1.24
ImmersiveEngineering-1.16.5-5.0.0-135
Modlist- [TownCraft TWO](https://www.curseforge.com/minecraft/modpacks/towncraft) modpack for 1.16.5

**Comment by BluSunrize** [comment]
@malte0811 this seems to be an access issue with the `ConnectionAccess` mixin

**Comment by malte0811** [comment]
This appears to be a Mixin conflict with Tetra, easy to fix on their side. I've already DMd the author about it.

**Comment by malte0811** [comment]
Fixed in the [latest Tetra build](https://www.curseforge.com/minecraft/mc-mods/tetra/files/3354314).
