### ISSUE TITLE
[1.12] - increase extracting conveyor max tick speed to 40 ticks or 60 ticks vs 20 ticks (currently)

### ISSUE THREAD

**Issue by DoomSquirter** [BluSunrize/ImmersiveEngineering#4836]
### Description of the issue:
currently, you can use the wire cutter to change the extraction rate up to 20 ticks (one second).  I've found it to be too fast for the couple of IE multi's I've used it on (crusher, metal press, etc).  it'd be great if that max could be increased to 2 or 3 seconds.

### Versions & Modlist
ImmersiveEngineering-0.12-98
forge 14.23.5.2854

**Comment by BluSunrize** [comment]
Support for 1.12 was stopped 10 months ago.

**Comment by DoomSquirter** [comment]
so, if the same situation exists in 1.16, can it be implemented there?

**Comment by BluSunrize** [comment]
Sure, file a new issue following the template please.
