### ISSUE TITLE
[1.16.5] Crash when I mouse over the Twilit twilight shader bag from twilight forest

### ISSUE THREAD

**Issue by gwydion0917** [BluSunrize/ImmersiveEngineering#4837]
Crash on any Twilit Shader. Since Immersive adds the shader it is not a Twilight Problem. 

https://pastebin.com/6nPX7K9K

Please add a config to also be able to disable shaders.

**Comment by mindforger** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/4835

simliar crash

**Comment by malte0811** [comment]
This is purely a TF bug. They're calling internal IE code, which can change at any time without warnings and in this case did change.

Edit: for future reference, this was fixed in https://github.com/TeamTwilight/twilightforest/commit/ea4748a487b52e339265af07d96b033dae9605d7

**Comment by mindforger** [comment]
thanks for explaining the actual bug :) the other issue got cut short without a proper explanation
