### ISSUE TITLE
[0.6-pre] some blocks get rendered absolutely black

### ISSUE THREAD

**Issue by cobra** [BluSunrize/ImmersiveEngineering#484]
During testing I noticed that the sides of a pump rendered completely black and I couldn't do anything about it - hammering it to change the side configuration, breaking/replacing, placing/breaking a block next to it, logging out/in again, even restarting didn't help. Only placing it somewhere else did. That was on version 3a3ba83.

Today, using version daa8378 to start looking at the door issue #477, the vanilla(!) door I placed was rendered the same way. Pumps are also doing the same. This seems to affect the whole chunk, but not every block position.
![](https://cloud.githubusercontent.com/assets/163331/10268186/4b229e1e-6ab1-11e5-9637-c1c48711ccbd.png)
There are several affected chunks in this world, some seem like they aren't affected. I can't see any obvious pattern in the blackness.

Another example:
![](https://cloud.githubusercontent.com/assets/163331/10268191/67312620-6ab1-11e5-8dc4-91c2d011b186.png)
Placing a block at this specific position causes this change, other positions affect other door/pump blocks or none at all (at least what I can see, maybe they affect blocks which are currently air). I couldn't yet figure out which position affect which blocks.
![](https://cloud.githubusercontent.com/assets/163331/10268113/9d7ccd4a-6aae-11e5-8482-862df4031c98.png)

After enabling smooth lighting (both minimum and maximum do the same), I get some green overlay:
![](https://cloud.githubusercontent.com/assets/163331/10268289/3e714d7a-6ab4-11e5-9749-625f040c4c4b.png)

Sadly, this is my test world with nearly everything from IE in it, so I can't really blame a specific block or multiblock.

Mod list: Code Chicken Core, CoFH Core, NEI, WAILA, IE, Thermal Foundation/Expansion/Dynamics - NO Aquatweaks, but adding it to the runtime classpath didn't change the blackness.

**Comment by BluSunrize** [comment]
What the fudgenuggets?

remove the multiblocks (Arc furnace and Crusher) from the chunk and try again. This may be related to multiblocks using ISRBH now.

**Comment by cobra** [comment]
Your reaction is similar to what I thought when I saw and examined it as well. Combine that with my confusion about the bouncy doors.
I somehow suspected something of your rendering changes, but I also had an affected chunk without a multiblock in it.

It doesn't seem to be the multiblocks, even though killing the arc furnace changed some blocks.
It's the presence of conveyor belts. Some belts affected a whole lot of blocks, for example the one feeding into the right hopper on top of the arc furnace (first picture) blackens the two top rows of pumps. That's reproducible. Removing all conveyor belts fixes the entire chunk, adding a single one corrupts a few blocks. Adding more affects more blocks, but as I wrote above it doesn't look predictable to me.

**Comment by BluSunrize** [comment]
interesting. I'll need to investigate my conveyor code.

**Comment by cobra** [comment]
I can test stuff for you if you want, just tell me where or what to look/breakpoint/watch/evaluate/whatever, I've loaded that world with more broken chunks in a debugging instance anyway.

**Comment by cobra** [comment]
Lighting for the conveyors seems to be buggy as well, I'm just experimenting a bit. When placing them in a hole, they look very dark. Placing them on the same level as door affects all door top blocks (x*,y+1,z*) in the chunk and all door bottom blocks (x*,y,z+1,2,3…) in positive z direction of the conveyor (x,y,z), * indicating all values inside the chunk.

**Comment by cobra** [comment]
I'll leave that for you as I haven't done anything render-related before, but have this teaser what one additional line is doing to this ;)
![](https://cloud.githubusercontent.com/assets/163331/10270136/3eaae8fc-6ae9-11e5-822b-0f1ee4e91f04.png)

**Comment by BluSunrize** [comment]
Yeah, that was really stupid mistake on my part. xD

**Comment by cobra** [comment]
At least it was a somewhat interesting and fun bug hunt.
