### ISSUE TITLE
[1.16.5] Visual bug looking through the surface of water

### ISSUE THREAD

**Issue by ShortCircuit908** [BluSunrize/ImmersiveEngineering#4840]
Occluded terrain (caves, underground lakes, etc.) become visible when looking through the top surface of water. The visual bug disappears once the player's vision is under the water. This occurs in every body of water in a singleplayer world regardless of location or biome.

### Versions & Modlist
Forge version: 1.16.5 - 36.1.24
IE version: 1.16.5-5.0.0-135
Other mods: None (world generated with other mods present, all mods other than IE removed for troubleshooting)

![2021-06-01_16 19 10](https://user-images.githubusercontent.com/6269218/120390156-5e52da00-c2fb-11eb-851a-d342918c47bb.png)

**Comment by BluSunrize** [comment]
> Are you using Fabulous graphics? If you do, switching to them should have shown a warning telling you that you should disable stencil in the IE config.

See #4466

**Comment by ShortCircuit908** [comment]
I was indeed using Fabulous graphics, so that would be the issue. I added Immersive Engineering to an already-existing instance that was in Fabulous graphics mode, so the mod did not show the warning.
