### ISSUE TITLE
Crash with twilight forest & applied energistics

### ISSUE THREAD

**Issue by FlashFyreMods** [BluSunrize/ImmersiveEngineering#4841]
Crash log:

https://pastebin.com/QQGQud9u

Not quite sure if immersive engineering t is the culprit of this, but I'll send it here anyway just in case. Crash happens when I type in the search bar in the applied energistics pc.

Versions: Happened on both 36.1.4 and 36.1.24, crashes client when on a server.

Sorry for wasting your time if one of the other mods I mentioned is the root cause of this.

**Comment by BluSunrize** [comment]
Twilight Forest is accessing an internal method of IE. That's on them to fix, not us. We can change our internal code whenever we want to. =p

**Comment by FlashFyreMods** [comment]
Cool, thanks for the quick response!
