### ISSUE TITLE
Minecraft crashes,i think this is because of epicfight mod,can u help me?

### ISSUE THREAD

**Issue by CptToxic** [BluSunrize/ImmersiveEngineering#4845]
I don't know at what exact moment the crash occurs.Usually occurs in multiplayer,here.     
[latest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/6609058/latest.log)
 is a list of mods and crash log Version is 1.12.2
bspkrscore_universal
Damage Indicators
armom status hud
Angels of vengence
baubles
betterfps
biomes o'plenty
blood magic
Bookshelf
Chocolate quest 
Code chiken core
Cofh core
Cofh world
crosshair mod
cyberwave
double slabs
enchanting plus
epic fight mod
exnihilocreatio
forgelin
voxel map
guide api
hwyla
inventory tweaks
Jei
mantle
mekanism
mowziesmobs
music player
Mutant beasts mod
NEI
Optifine
Patchouli
real first person 2
redstone flux
shoulder surfing
Tam modized
The betweenlands
Twilight forest
u_team core
useful backpacks
XRay mod
and some libraries for these mods

**Comment by mindforger** [comment]
1.12 isn't supported anymore, also immersive engineering is not even on the modlist, so completely wrong issue tracker my friend ...

but to tell you the offending mod: it is the llibrary_1.7.19_1.12.2.jar, try removing it, i can not see which of your mods may rely on it but the mod is outdated and the code badly broken when it throws an exception for an website that can not beloaded because it has been deleted!

**Comment by CptToxic** [comment]
> 1.12 isn't supported anymore, also immersive engineering is not even on the modlist, so completely wrong issue tracker my friend ...
> 
> but to tell you the offending mod: it is the llibrary_1.7.19_1.12.2.jar, try removing it, i can not see which of your mods may rely on it but the mod is outdated and the code badly broken when it throws an exception for an website that can not beloaded because it has been deleted!

I apologize, I did not pay attention to the section when I wrote, I'll try right now, thanks in advance

**Comment by BluSunrize** [comment]
Mindforger nailed it.

Support for 1.12 was canned over 10 months ago, you don't even have IE installed.

And also you full on ignored issue template and contribution guidelines. Closed.
