### ISSUE TITLE
Crusher does not stop working in SMP

### ISSUE THREAD

**Issue by cyres** [BluSunrize/ImmersiveEngineering#485]
After the Crusher has finished working he continues to run. A redstone signal does not help, only relog helps.

**Comment by BluSunrize** [comment]
Should be fixed by upcoming releases, had a lot of PRs related to that, @cobra can confirm

**Comment by cobra** [comment]
Yep, definitely fixed.

**Comment by BluSunrize** [comment]
Excellent. Closed.

**Comment by cyres** [comment]
Thanks!

**Comment by b0bst3r** [comment]
@cobra does this fix the diesel gen noise not turning off when you turn off the gen?  The animation stops (fan spinning) but the noise carries on until you leave the area.

**Comment by cobra** [comment]
No, the orphaned sound effects are a different topic, but I'm currently debugging this stuff. Relogging helps in the meantime.
