### ISSUE TITLE
Incompatibility with item in Twilight Forest Mod

### ISSUE THREAD

**Issue by Jey-Jay** [BluSunrize/ImmersiveEngineering#4851]
I report on this page because the crash report has the name of this mod in it. Anyways, whenever this suitcase like item from the Twilight Forest forest mod that contain certain bosses crashes my game whenever it appears in an inventory slot on my screen so staring at the item while it is on the ground is fine but if it is in my inventory and I open my inventory the game will crash and when viewing it in a a creative inventory section.

This is the crash report:
The game crashed whilst rendering screen
Error: java.lang.NoSuchMethodError: blusunrize.immersiveengineering.client.ClientUtils.applyFormat(Lnet/minecraft/util/text/ITextComponent;[Lnet/minecraft/util/text/TextFormatting;)Lnet/minecraft/util/text/IFormattableTextComponent;
Exit Code: -1

**Comment by mindforger** [comment]
Please follow the template when creating issues, your report is pretty much useless in this state, uploade (copy) the whole crashlog to a site like pastebin and post the created Link here! Also add an minimal description WHEN the crash happend or what you were doing, so one can attempt to reproduce the issue. Your report is as precise es calling a mechanic telling him „my car does not work“ and then hanging up the phone

**Comment by BluSunrize** [comment]
That's Twilight Forest's issue to fix. They are accessing internal methods that they shouldn't be.

**Comment by Jey-Jay** [comment]
Thank you for your email, have great day!

**Comment by Jey-Jay** [comment]
Also, I am sorry for wasting your time.
