### ISSUE TITLE
[1.16.15-4.2.4-134] Revolver causes crash when used on Ars Nouvea Wilden Creatures

### ISSUE THREAD

**Issue by Commandore32** [BluSunrize/ImmersiveEngineering#4854]
Version numbers:
--------------------------------------
Minecraft: 1.16.5
Forge:36.1.23
Immersive engineering: 4.2.4-134
Ars Nouveau version: 1.16.2
-------------------------------------

Modpack: Direwolf 20 1.16.5 Version: 1.10.1

--------------------------------------------------
Crash Report: https://pastebin.com/tVPnkPtQ
--------------------------------------------------
I Shot a Wilden Hunter from Ars Nouveau with a Revolver using High explosive cartridges. This happens every time. Curiously, when the crash above happened, the game continued to run for 3-5 seconds after the shot was fired, then froze and crashed. This is the first time I've seen this happen out of the 3-4 crashes I've had so far. I was in a sandstone super flat world (my creative test world).

**Comment by BluSunrize** [comment]
I am not seeing any reference to IE in the stacktrace. This seems to be originating in the mob's AI code called by Ars Nouveau. Please report this on their tracker instead.

**Comment by Commandore32** [comment]
Thank you for such a rapid response. I am sorry for such a late reply. Sorry for the distraction. Crash reports are very cryptic for me, as I do not have any programming expertise.
