### ISSUE TITLE
[1.10.2] (Age of Engineering) No creosote texture

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#4856]
Alright so basically I added thermal foundation and expansion to age of engineering and I saw a different thread about creosote textures missing. In JEI there is no texture and even from my fluid tank I cannot bucket out any fluids. If I open the GUI for the fluid tank it says that there are 9000mB of creosote but there is nothing there to see. I saw the other thread about this issue and I opened NBTExplorer and opened level.dat. In it, under forge, and the fluid directory the response said to look for something called thermalexpansion:creosote but I can't find it in my level.dat file anywhere. I have checked multiple times. Should I cheat in the creosote or is there another way I can fix this issue?

**Comment by BluSunrize** [comment]
1.10.2 went out of support a very very very long time ago.

**Comment by ghost** [comment]
i just wanted to know what i can or should do smh

**Comment by BluSunrize** [comment]
You should upgrade to a new version of Minecraft, because we don't support this one anymore, which is why this issue is invalid.
