### ISSUE TITLE
External heater does not work with witch's oven (witchery) or thaumcraft cauldron IE 0.5.4

### ISSUE THREAD

**Issue by MFernflower** [BluSunrize/ImmersiveEngineering#486]
Is this intentional or not?? - id really like to use the external heater for those applications but it does not seem to work...

**Comment by liamjarvisman** [comment]
I believe thats intentional because I think that might be a tad op but thats what I think not sure about what @BluSunrize thinks.

**Comment by cobra** [comment]
Technically, those aren't furnaces but completely unrelated blocks, so IE would need explicit support for accessing them. It should work with everything extending the vanilla furnace, but I don't know if there's a mod doing that.

**Comment by BluSunrize** [comment]
Yeah, how the fudge was I even supposed to make that work?
I can access Vanilla tiles, but those from other mods have a completely different code structure.
