### ISSUE TITLE
[Minecraft 1.16.5] crash when player lands on conveyor

### ISSUE THREAD

**Issue by heatcrash** [BluSunrize/ImmersiveEngineering#4860]
### Description of the issue:
I run a Minecraft server with a group of friends and had a major issue with conveyor belts. Every time a player jumps on or falls on a conveyor they crash, this issue is repeatable 100% of the time, this issue also only crashes the client. While my server runs performant and optifine I tested it without them and still had this issue. I Tested with just IE installed and did not have this issue so I apologize if I shouldn't be reporting this here as it may be a problem with another mod. 

### Crashlog:
Crashlog with performant + optifine https://gist.github.com/heatcrash/192ca0f6fbe872a4af86396516b4df43

Crashlog without performant + optifine https://gist.github.com/heatcrash/0c5cafb4f328616287881b3c7c48a832

### Versions & Modlist
Forge  1.16.5  36.1.25
IE  5.0.0 135

### Personal thoughts
I am deeply sorry if this issue is unrelated to IE in any way, while reading the crash report nothing stood out to me other than the conveyor itself.

**Comment by BluSunrize** [comment]
Update Tetra
