### ISSUE TITLE
Standing on a conveyor belt results in game crash

### ISSUE THREAD

**Issue by SanyikaHUN04** [BluSunrize/ImmersiveEngineering#4861]
I was playing the latest version of Valhelsia 3 (3.3.3 release (IE version 1.16.5-5.0.0-135)) and I was trying to set up my garden cloches. I was using extractor conveyor belts to get the items out, and while placing those down I stood on one of them which crashed my game (every time I was trying to join my world). First crash report attached. All I could do is to restore a backup from a few hours ago. Otherwise it's a perfect mod, hope you can fix this issue soon ; )
[crash-2021-06-20_13.19.52-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/6682233/crash-2021-06-20_13.19.52-server.txt)

**Comment by malte0811** [comment]
Update Tetra.
