### ISSUE TITLE
[Suggestion] Wireless Redstone transmitters/receivers

### ISSUE THREAD

**Issue by RobynBrossard42** [BluSunrize/ImmersiveEngineering#4864]
I think some antennas and/or dishes that use rf and use an interface connector could fit right into the immersive engineering style. Maybe as machine blocks, or multiblock structures. Maybe with different ranges depending on power usage, or simply the relative cost of crafting ingredients.

**Comment by BluSunrize** [comment]
We literally have redstone wires for this.

**Comment by RobynBrossard42** [comment]
Fair enough.

Thanks for hearing me out though, I know you get a lot of suggestions.

Might have to get back into java programming to make my dreams of a long distance radio station a reality.
