### ISSUE TITLE
[Suggestion, 1.16.5-4.2.4-134] Wire cutters remove one wire at a time

### ISSUE THREAD

**Issue by JavaRogers** [BluSunrize/ImmersiveEngineering#4869]
The current function of wire cutters (when working with in-world wiring) is you right-click on a piece of equipment, and all its wires disconnect. This is the same as breaking the equipment and placing it down again. In the example (below), removing the undesired middle wire means having to reconnect 5 other wires.

Suggestion? Wire cutters should remove one wire at a time. The engineer would clip two ends of a wire for it to disconnect. The cutters would become a tool for precision wire removal, which does a finer job than the ham-handed pickaxe.

Hoping you consider it ^.^

![image](https://user-images.githubusercontent.com/40445970/123475781-bc987300-d5b0-11eb-9e2e-32b173d78dc8.png)

**Comment by BluSunrize** [comment]
Try just aiming your wirecutters at a wire in midair...

**Comment by JavaRogers** [comment]
I couldn't get that to work, but I just figured it out! It looks like air needs to be behind the wire when you do it, eh? Almost all of my factory wires are up against a wall or ceiling, so I figured this wasn't already a feature.

This is amazing 😄 Cheers!
