### ISSUE TITLE
Guidebook/Manual Text Render in Small UI Mode

### ISSUE THREAD

**Issue by MokahTGS** [BluSunrize/ImmersiveEngineering#487]
I'm having a hard time reading the text of the manual when in UI settings of small.  It's not that its too small, its that the text is cutoff on various parts of words.  Something with the UI scaling is off.

**Comment by liamjarvisman** [comment]
then make your ui large

**Comment by BluSunrize** [comment]
I made it force the gui scale to normal while the book is open. It will reset to your chosen scale when you close the book again.
It's not a pretty solution, but it's the only one I could come up with. xD

**Comment by MeatShackles** [comment]
Well, that works for most monitors i'll admit but it kinda doesn't work to well on anything bigger such as a TV (I know i should get a monitor but then i'd need to get a new desk too and blah blah) The only gui scalling that isn't small on this TV is auto mode. 
![tiny book](https://cloud.githubusercontent.com/assets/9204844/10428703/4b220a06-70c1-11e5-9f48-68a1a2e69bf5.png)
