### ISSUE TITLE
the diesel generator does not accept any fuel

### ISSUE THREAD

**Issue by Pe4enkiSMolokom** [BluSunrize/ImmersiveEngineering#4871]
The diesel generator does not accept any fuel
not gasoline, not diesel, not biodiesel
Forge-36.1.4
ImmersiveEngineering-1.16.5-5.0.0-135
ImmersivePetroleum-1.16.5-3.3.0-4.jar

**Comment by BluSunrize** [comment]
This issue report does not provide the necessary information asked for in the template.

Without pictures there is literally no way for us to help you. Please remedy this within the next 24 hours, or I will close this.
