### ISSUE TITLE
Unhandled exception when player collides with belt

### ISSUE THREAD

**Issue by APCBoston** [BluSunrize/ImmersiveEngineering#4872]
### Description of the issue:
Whenever the player comes into contact with an IE conveyor belt, the game throws an unhandled exception, resulting in the player being dumped from the server.  Player is unable to rejoin the server until the playerdata NBT is manually edited to move the player away from the belt.  (I have not tried having another player come on and remove the belt, but I surmise that might work too).

### Crashlog:
https://pastebin.com/JQWEEjHt

### Versions & Modlist
IE version 1.16.5-5.0.0-135
Forge 36.1.25
Valhelsia3 3.3.3 modpack.

**Comment by mindforger** [comment]
probably linked with https://github.com/BluSunrize/ImmersiveEngineering/issues/4833
and fixed then

**Comment by BluSunrize** [comment]
Yeah. Update Tetra.

**Comment by APCBoston** [comment]
Ah, apologies for the dupe, and thanks for the quick response!
