### ISSUE TITLE
[1.16.5] The drill crash

### ISSUE THREAD

**Issue by LordLizard02** [BluSunrize/ImmersiveEngineering#4875]
### Before reporting:
I didn't found anything about it so I post it here.

### Description of the issue:
If I pick an empty (no fuel inside) mining drill in hand with a head on it I get crash with the error "ticking entity"

### Crashlog:
https://we.tl/t-jXzyGFuJYD

### Versions & Modlist
IE: 1.16.4-4.1.2-129
Forge: 36.0.26

Modlist:
https://we.tl/t-vsYVzEeJr6

**Comment by BluSunrize** [comment]
Please try to replicate this issue with IE release 5.0.2-137. You are 8 versions behind.

**Comment by LordLizard02** [comment]
Looks like it works fine in the newest version, not a crash.
