### ISSUE TITLE
Connection through blocks

### ISSUE THREAD

**Issue by Whisker72** [BluSunrize/ImmersiveEngineering#4877]
I really like your mod, but there's a feature your mod definitely needs: either a dedicated wall-through block with either wire conductors or relays on opposite sides to conduct power through walls or floors/roofs, or the possibility to conduct power through a block by just putting conductors or relays on blocks on 2+ sides.

**Comment by PrincessOfEvil** [comment]
You can already do that.

**Comment by BluSunrize** [comment]
You should read "Basic Wiring" in the manual again. It provides a sollution for this, in the form of "Feedthrough Insulators".

**Comment by Whisker72** [comment]
Oh, _now_ it's clear where I went wrong!

I used relays instead of connectors, and I didn't think of tapping one of the connectors with the Engineer's Hammer.
(Didn't realise the latter until I read the page about the Feedthrough Insulator again just now and saw the animation, which gave me the clue about trying the Engineer's Hammer.)

Kudos for pointing me into right direction!
