### ISSUE TITLE
[1.16.5] Feedthrough Insulator causes crash when mined

### ISSUE THREAD

**Issue by SgerbwdGwyn** [BluSunrize/ImmersiveEngineering#4879]
Upon attempting to mine a feedthrough insulator made of a steel block, the block produces purple-black particles (missing texture) and crashes to desktop with the error message "The game crashed whilst tesselating block model, Error: java.lang.NullPointerException: Tesselating block model, Exit Code: -1"

Crashlog with Mod List: https://gist.github.com/Big-Crab/126108f7cd127d30e472314702e84dfd
Resource packs: Just an audio resource pack that changes the breaker noise.

Forge version: 36.1.0
IE version: 1.16.5-5.0.2-137

**Comment by SgerbwdGwyn** [comment]
Worth noting that this kind of makes the game unplayable without access to creative mode or worldedit and is a death sentence for anyone trying to run an IE server.

**Comment by NielsPilgaard** [comment]
I'm afraid this still happens, but only when the player is in survival mode.

**Logs**
https://pastebin.com/ZQgvWsXj

**Screenshots**
https://streamable.com/y5f2md

**Comment by BluSunrize** [comment]
Yeah because no fixed version has been released. The issue is closed because malte pushed the commit to fix it, but we have not released a build since then.

**Comment by the-engineers-balls** [comment]
any word on when an updated build might release? this is pretty big for anyone wanting to redo wiring

**Comment by charliegreen** [comment]
Uncertain if this is relevant to the existing fix or not, but I'd just like to add for completeness that this happens for me with a feedthrough going through oak planks and through cobblestone, not just through a steel block.

**Comment by sarkubocael** [comment]
Yeah doesn't matter what type of block you use, once you make an feedthrough insulator you cant collect it, as soon as something touches it game crashes, i tried direct, i tried TNT, i tried a 9x9 tinkers hammer by mining blocks around it, as soon as you touch the feedthrough insulator game is gone. They still function as intended tho, so if you know you will not move it until its fixed you can use them.

**Comment by peregrine-developments** [comment]
so it's been like a month since last release, when can we expect to see a new one?

**Comment by BluSunrize** [comment]
When I have the time to deal with it. Don't ask for ETAs.
