### ISSUE TITLE
[FIXED] Excavator not working.

### ISSUE THREAD

**Issue by Ayrrow** [BluSunrize/ImmersiveEngineering#488]
In my test world - creative/superflat. Build excavator multiblock. correctly forms. Bucket doesn't spin and ores do not generate even with power and in chunk.

Using immersive engineering version 0.54. Replaced dirt as suggested in issue #188 

![2015-10-07_23 11 38](https://cloud.githubusercontent.com/assets/7918443/10337301/934793f2-6d4a-11e5-90a9-7735dac9235f.png)
![2015-10-07_23 11 43](https://cloud.githubusercontent.com/assets/7918443/10337302/934a7fcc-6d4a-11e5-9c74-1f3284b0da71.png)

**Comment by cobra** [comment]
Your wheel is placed incorrectly, one block too high. Go look at the manual again, its center block needs to be in the middle of the excavator multiblock.

**Comment by Ayrrow** [comment]
thanks, I feel like such an idiot.

**Comment by cobra** [comment]
You can close this ticket all by yourself ;)

**Comment by twome** [comment]
Might be good to prevent the excavator housing from consuming power if it's switched on without the bucket-wheel properly attacked. It took me ages to diagnose that I'd made the same mistake here because the fact that the excavator was consuming power made me think it was working just fine.
