### ISSUE TITLE
[1.16] Conveyer Belt Crash

### ISSUE THREAD

**Issue by Ninjayatsu** [BluSunrize/ImmersiveEngineering#4880]
### Description of the issue:
When the player entity steps on a conveyer, the game crashes instantly. No screenshots available because when rejoined the world doesn't have enough time to load for the player to be pushed off the conveyer belt and it crashes instantaneously.

### Crashlog:
https://gist.github.com/Ninjayatsu/96994fb98711b71636c5b552bfd4b541

### Versions & Modlist
Forge 36.1.0 - Immersive Engineering 5.0.0 originally, updated the world to 5.0.2 but the crash remained.

Definitly a mod compat issue just unsure what, tried removing create but nothing.

**Comment by malte0811** [comment]
Update Tetra.

**Comment by Ninjayatsu** [comment]
oh wow its tetra? I wouldn't have guessed that. didn't think tetra changed entity collision.  Thank you though.
