### ISSUE TITLE
I Have a Question

### ISSUE THREAD

**Issue by Nicon4454** [BluSunrize/ImmersiveEngineering#4885]
I have a question and i do not see a forum to ask and could not find a discord server to ask.

in the config file there is this 
`#The Flux per tick that the Diesel Generator will output. The burn time of the fuel determines the total output `
`#Range: > 0`
`dieselGen_output = 4096`

how can i change the fuel burn time in 1.16.5? using either kubJS or craft/mod tweaker 

again i know this is not the right place to ask for help but i could not find the right place.

**Comment by BluSunrize** [comment]
The discord is literally linked on the CurseForge page.

And you can't change the burn times with those mods. You would need to make an addon that uses our `DieselHandler` API.

**Comment by Nicon4454** [comment]
ok thank you

and i am sorry i did not see the link i can not believe i missed it
