### ISSUE TITLE
Copper storage block can't be used in Unpacking metal press

### ISSUE THREAD

**Issue by SgerbwdGwyn** [BluSunrize/ImmersiveEngineering#4886]
When passing a copper block (9x9 ingots -> storage block) through a press with the Unpacking mold, the machine doesn't accept the item.
Other storage blocks do work.

Version: 1.16.5 / 5.0.2-137

**Comment by BluSunrize** [comment]
Can't reproduce this issue.

Please verify this in an instance with only IE installed.
