### ISSUE TITLE
Ingots cannot be made into nuggets using the Unpacking mold

### ISSUE THREAD

**Issue by SgerbwdGwyn** [BluSunrize/ImmersiveEngineering#4887]
Not sure if this is intentional, but ingots (in my mind) should count as a storage block of some kind, and thus should be able to be turned into nuggets using the unpacking mold. Currently, ingots are not accepted into the press.

Version: 1.16.5 / 5.0.2-137

**Comment by BluSunrize** [comment]
![image](https://i.imgur.com/gLW2THg.png)

Works fine on my machine. Might be an issue with the recipes in your modpack.

Please test this in an instance with just IE installed.
