### ISSUE TITLE
Chemical thrower crash [1.12.2]

### ISSUE THREAD

**Issue by TheJellobro** [BluSunrize/ImmersiveEngineering#4888]
I've encountered a crash while playing with a bunch of mods, and I looked at all the chemical thrower crashes and they are all 1.16, this is a 1.12.2 crash. Game will crash upon trying to fire a chemical thrower, doesn't matter what fluid I use. I looked at the crash report, and from what I can comprehend, it seems to be some sort of dynamic lighting bug, maybe from the albedo mod? I couldn't find a fix, and I don't want to remove albedo so I am posting the bug report.
[crash-2021-07-19_02.09.06-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/6839173/crash-2021-07-19_02.09.06-client.txt)

**Comment by BluSunrize** [comment]
We no longer support 1.12. All support for that version was stopped over a year ago.
