### ISSUE TITLE
Developing with Immersive

### ISSUE THREAD

**Issue by GlacierPark19** [BluSunrize/ImmersiveEngineering#4889]
Hello,

I am working on developing an addon for Immersive 1.16.5. Is there a guide anywhere for doing this? I am specifically looking at adding a large multiblock... or 12

**Comment by BluSunrize** [comment]
No, there is no guide. You'll need to just look at the API, read the code and figure it out.

I would recommend that you have some experience in modding first before you tackle multblocks, because they are quite a bit more advanced than normal blocks, items and recipes.

**Comment by GlacierPark19** [comment]
Okay thanks
