### ISSUE TITLE
[1.16] Conveyor belt player colliding interaction crash

### ISSUE THREAD

**Issue by yuesha-yc** [BluSunrize/ImmersiveEngineering#4890]
### Description of the issue:
When a player walks on a conveyor belt, server crashes. 

### Crashlog:
https://paste.ubuntu.com/p/WYkfXDtNm8/

### Versions & Modlist
Forge: 36.1.32
IE: 1.16.5-5.0.0-135
Modlist: https://paste.ubuntu.com/p/wn7t6VSjjd/

**Comment by malte0811** [comment]
Update Tetra.
