### ISSUE TITLE
Transformer - Imprecise connection behavior

### ISSUE THREAD

**Issue by BluSunrize** [BluSunrize/ImmersiveEngineering#4891]
Originally reported on Discord by `Emu#8698`.

# Expected behavior
Connect wires to the transformer, having them attach based on their wiretype

# Actual behavior
When connecting wires to the (HV) transformer, the second one seems to only be attachable if the transformer is clicked on the side that the connector is located.

# Version
Current state of 1.16.5 branch:
https://github.com/BluSunrize/ImmersiveEngineering/commit/a6b538d9f57f84b05eac4a28a7bf25bbcc34d735

**Comment by ruiluth** [comment]
I've noticed this for all wire types on all transformers, they want you to click the side that the correct connector is on, any side will not work.
