### ISSUE TITLE
[1.16.5] Crash during Feedthrough connectors breaking

### ISSUE THREAD

**Issue by ZigTheHedge** [BluSunrize/ImmersiveEngineering#4892]
Game crashes when trying to remove feed-though connection multiblock.

MC: 1.16.5
Forge: 36.1.32
IE: 5.0.2-137

Crashlog: https://pastebin.com/eBncV3bz

Happens when starting to break the multiblock in survival (works fine in creative though).

**Comment by malte0811** [comment]
Duplicate of #4879
