### ISSUE TITLE
[1.16.5] Post-Transformer can be placed on top of a Post of any Type

### ISSUE THREAD

**Issue by TwistedGate** [BluSunrize/ImmersiveEngineering#4894]
### Description of the issue:
It'll stay there until a block update happens nearby, then it pops into its item.
![grafik](https://user-images.githubusercontent.com/31029668/126878369-da30569e-e925-4c14-9212-9fb4d8bf1b3f.png)

Noticed this after having the same issue on my IPo Posts, perhaps a way to tell from which side the transformer has been clicked on could be added to the `canConnectTransformer` method?

### Versions & Modlist
Forge: `36.1.0`
IE: `1.16.5-5.0.2-137`
ImmersivePosts DevEnv

**Comment by BluSunrize** [comment]
Closing this because support for 1.16.5 has ended
