### ISSUE TITLE
[1.16] Assembler doesn't properly update comparators

### ISSUE THREAD

**Issue by ruiluth** [BluSunrize/ImmersiveEngineering#4896]
### Description of the issue:
When a comparator is placed to read the redstone block of the assembler multiblock, it does not update when the contents of the ingredient inventory changes. Breaking and replacing any block adjacent to the comparator corrects its output value. Tested in single player.

### Crashlog:
N/A

### Versions & Modlist
Immersive Engineering 1.16.5-5.0.2-137
Forge version: 1.16.5-forge-36.1.32
Tested and verified with no other mods installed.

**Comment by BluSunrize** [comment]
This seems to affect *all* of IE's multiblocks. I have successfully reproduced this with:

- Assembler
- Crusher
- Arc Furnace

@malte0811 we should think about a universal solution here which covers all of our multblocks.
