### ISSUE TITLE
Crash 1.15.2 Dedicated LAN multiplayer server.

### ISSUE THREAD

**Issue by Zarandolph01** [BluSunrize/ImmersiveEngineering#4897]
Forge: 1.15.2-31.2.47 (not the issue)
Minecraft version: 1.15.2
Crash log: https://pastebin.com/qcEjbHEG
FORGE SERVER.
I did check closed and opened tickets, none were about 1.15.2. Presumed new issue. 
This happens when I try joining my locally hosted server. It almost instantly crashes because of the incredibly infamous "Bounding boxes" issue that still has not been fixed in 1.15.2. (Which irks me). This happens every single time.

Does not happen in single player. (I don't have any coils placed). 

I do remember being shown a "Diy Patch". Apparently, I can fix it myself. (Again, shouldn't have to)

NO, I will not upgrade to 1.16 unless you want to spend the time to help me migrate my current save into a new server. Any "solution" offering that will be swiftly ignored. Please workaround that with me. You WILL be ignored otherwise. Telling me to upgrade to 1.16 is not being helpful, you will instead be wasting my time and yours.

(I Read Contribution Guidelines).

**Comment by malte0811** [comment]
1.15.2 is no longer supported. If updating to a supported version is not an acceptable solution to you, you'll have to live with the crashes. Be aware that distributing custom builds of IE would be a violation of IEs license.

**Comment by mindforger** [comment]
>NO, I will not upgrade to 1.16 unless you want to spend the time to help me migrate my current save into a new server

wow ... this is just WOW .... did you, in your selfcentered world spent JUST A CENT on how the devs are doing this mod FOR FREE?

they choose to not support anything below 1.16 because they do not have enough free time to work on multiple versions at once

**Comment by Zarandolph01** [comment]
> > NO, I will not upgrade to 1.16 unless you want to spend the time to help me migrate my current save into a new server
> 
> wow ... this is just WOW .... did you, in your selfcentered world spent JUST A CENT on how the devs are doing this mod FOR FREE?
> 
> they choose to not support anything below 1.16 because they do not have enough free time to work on multiple versions at once

Look, to start off, I will say I was steamed, and still sorta am. What I was trying to avoid (albeit hostile, and I apologize for that behavior) is people sending me a solution of upgrading only for me to tell them I can't do that out of fear of losing my server's save. Considering I had a bad time even upgrading forge versions. I lost over 60% of my progress because of a mistake I made. It would make me feel all excited that someone sent a reply, only to find out it was the one "solution" I did not want to be brought forward.

It was not aimed directly at the developers. And I do, contrary to YOUR belief, appreciate what the devs do. No, I am not self-centered. You are more sounding so. I was angry, and have admitted that fact. I have said some things that I DO regret. They were a heat of the moment thing.

**Comment by Zarandolph01** [comment]
> 1.15.2 is no longer supported. If updating to a supported version is not an acceptable solution to you, you'll have to live with the crashes. Be aware that distributing custom builds of IE would be a violation of IEs license.

It would not be distributed. I just have this faint memory of a Github or some other project site having a patch I could apply myself.

**Comment by BluSunrize** [comment]
@mindforger Please do not yell at people after Malte has already closed the issue. We have a handle on our own tracker, and if someone does the yelling I prefer it to be me.

@Zarandolph01 You were a douche. Don't write issues when you're angry, that's not an excuse at all. You knew exactly what response you were going to get, and you got it. 1.15 is not longer supported. Upgrade or be stuck with the issue.
If you know how to code and can fix the issue, feel free to make a private version that fixes it. As Malte said, distribution is a license violation and will be followed up with a takedown notice.

Good day.

**Comment by BluSunrize** [comment]
Oh also, if you "lose a save" by upgrading, you clearly didn't do a backup beforehand. You should make backups.
