### ISSUE TITLE
Structurak arm on one position locked

### ISSUE THREAD

**Issue by Avishy7** [BluSunrize/ImmersiveEngineering#4898]
### Description of the issue:
Structural arm, these block. When it putted somewhere, it can be place only one position rotation apparently. But I don't understand, when my mouse's on the block, Minecraft show the ghost block in right position. You need to see it. It -'s usefull to make roofs or ways. ;)

### Crashlog:
The game doesn't crash or show error. 

### Versions & Modlist
Minecraft 1.15.2 
mod used : Forge 31.2.0
                    Immersive engineering 1.15.2-3.2.0-114

Watch closely these pictures, it explain all. The outline, watch it ! The structural is wrong turned ! It don't want to be putted other side. With shift, it doesn't change something. Please help !
![2021-07-26_11 10 28](https://user-images.githubusercontent.com/88185390/127625954-802c9ac6-2526-4f24-82e5-2bc0cb5d2482.png)
![2021-07-26_11 10 30](https://user-images.githubusercontent.com/88185390/127625975-24b567e7-e22a-4ed5-8e22-86ea4e948ee1.png)

Thanks for support !
I hope someone find how to fix it ;).

**Comment by BluSunrize** [comment]
Support for 1.15.2 has ended. Please update to 1.16.5, as it is the only version we currently support.
