### ISSUE TITLE
Redstone wire?

### ISSUE THREAD

**Issue by dh47** [BluSunrize/ImmersiveEngineering#49]
How about Redstone wire?  :D

**Comment by BluSunrize** [comment]
Thought about it, scrapped it. Quite the challenge in code.

**Comment by dh47** [comment]
Okay.   :(


Sent by Outlook for Android





On Sun, Jun 7, 2015 at 1:34 PM -0700, "BluSunrize" <notifications@github.com> wrote:
Thought about it, scrapped it. Quite the challenge in code.

---
