### ISSUE TITLE
[Suggestion] Add HarvestCraft support.

### ISSUE THREAD

**Issue by OneEyeMaker** [BluSunrize/ImmersiveEngineering#490]
Hello.
Please, add support for HarvestCraft: add recipes for plant oil and ethanol for items from this mod.

Like so: http://pastebin.com/jLc5Qu1C
Or so: https://github.com/ForestryMC/ForestryMC/blob/dev/src/main/java/forestry/plugins/PluginHarvestCraft.java (but there's one wrong recipe: https://github.com/ForestryMC/ForestryMC/issues/876)

**Comment by mindforger** [comment]
be aware the ethanol of IE is incompatible with the ethanol of forestry for a reason! ethanol of IE is only a component but not desired to be used as fuel, where ethanol of forestry is probably oredicted with biodiesel from IE!

**Comment by BluSunrize** [comment]
Do not use "OreDictionary" when talking about Fluids. Totally different things. And no, Forestry Ethanol and IE Biodiesel are not interchangeable.

To the original topic: I'll add some support, but I wont just copy-paste the scripts given.

**Comment by OneEyeMaker** [comment]
@BluSunrize 
I added that script as example. Also I added link to show you, how it made in Forestry with seedoil and biomass/bioethanol. (But code of Forestry contains one wrong recipe - link above, in first message).
