### ISSUE TITLE
[1.16] The mod doesn't load.

### ISSUE THREAD

**Issue by huhridge** [BluSunrize/ImmersiveEngineering#4901]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
Describe what happens, how it affects your game/gameplay and provide screenshots where possible.

### Crashlog:
If your Minecraft instance has crashed, a file will have been generated in the folder `crash-reports` of your minecraft folder. To understand what has happened, we need to know the content of that file. But please don't just put it directly in your report (that makes it hard to read), upload it to a site like [pastebin](http://pastebin.com) or [gist](http://gist.github.com) and put a link in the actuall bug report.

### Versions & Modlist
IE and Forge versions are mandatory. *Note that saying "latest" is **not** valid. Always give the proper version number*
Other mods should be listed (with their versions) in a [pastebin](http://pastebin.com) or [gist](http://gist.github.com) upload. The easiest way to get these lists is a crashlog, you may force one with F3+C.
If your game crashed (see above) you may omit the modlist, but IE and Forge version would still be nice.

Also, please try testing an issue in a minimal instance, with just IE, Forge and maybe JEI. That makes elminating compat issues easier.

### Lastly (you may delete this from the report itself)
Please, for the love of all that is voxelbased, **read the contribution guidelines. They are linked to the right in the message box.**
When reporting issues, these are crucial, and the team withholds the right to close an issue for the plain stupidity of not reading and adhering to them.

Thank you for reporting issues, without people reporting them, they wouldn't get fixed. You're helping contribute to this mod and that is much appreciated <3

Using curseforge to load a modpack using this mod on the M1 MacBook Air, the mod refuses to load.
The java version is 1.8.0_74 and forge version is 34.1.42.
The IE version is 4.1.1-127.
The error log is: https://gist.github.com/oharij/a198755e953961059a445504f4b1e60d

**Comment by BluSunrize** [comment]
1.16.3 is no longer supported, please update to 1.16.5.

**Comment by huhridge** [comment]
> 1.16.3 is no longer supported, please update to 1.16.5.

But the modpack is launching on a windows machine.

**Comment by BluSunrize** [comment]
Then consider that it's not the fault of the mods, but the fault of the operating system?

And that also doesn't change anything about the fact that we do not maintain that version anymore...
