### ISSUE TITLE
Compatibility issue with IE and FBP (Fancy Block Particles) 1.12.2

### ISSUE THREAD

**Issue by isakurs** [BluSunrize/ImmersiveEngineering#4902]
This issue causes every block from IE placed to be oriented North until a game reset and makes it unplayable. My modlist is ~200 mods, but I already found the culprit. [https://youtu.be/xLlJGNi9VuM](url)

**Comment by BluSunrize** [comment]
Excellent, if you know the culprit, remove that mod to fix it.

Also, we have not supported 1.12 for well over a year.
