### ISSUE TITLE
[1.12.2] Can't interact with anything (chests, bed, furnaces...), animals are frozen like if they're ai haven't loaded and chunks also don't load

### ISSUE THREAD

**Issue by Sellineth** [BluSunrize/ImmersiveEngineering#4905]
Like I said on title, after i installed this mod i can't interact with anything except doors, animals hostile and friendly are just frozen in place, I can't attack them or anything, and chunks only load while I'm entering the world, I'm using the latest 1.12.2 version of the mod (ImmersiveEngineering-0.12-98).
Mod list attached 
[modlist.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/6912213/modlist.txt)

**Comment by BluSunrize** [comment]
1.12 has not been supported for over a year.
