### ISSUE TITLE
[1.16.5] Additional information is not displayed in Hwyla

### ISSUE THREAD

**Issue by BADtochka** [BluSunrize/ImmersiveEngineering#4906]
Hi, I noticed that on the new version of the game, things like the number of "IF" on any block/mechanism have stopped being displayed.
Maybe I did something wrong?
I apologize if I should have written to support Hwyla, but I wrote here.

1.12.2:
![image](https://user-images.githubusercontent.com/75701093/127771500-7c8d224f-d30b-46db-8b92-752c3942e1a5.png)

1.16.5:
![image](https://user-images.githubusercontent.com/75701093/127771588-403c27a7-6ea4-471d-8c38-8f551af47413.png)

**Comment by BluSunrize** [comment]
We just...don't have HWYLA support currently. It never got ported over to 1.14+

One Probe can provide you with the information you need. But I'll leave this open as a reminder.
