### ISSUE TITLE
Immersive Engineering, cant form a Coker

### ISSUE THREAD

**Issue by G1BB3RISH** [BluSunrize/ImmersiveEngineering#4908]
in immersive engineering I cant form a Coker with the engineeres Hammer. I built it in creative and right clicked the block which stood in the book, but nothing happens. PLaying on a solo world.

**Comment by BluSunrize** [comment]
Why did you ignore the issue template? We describe in so much detail what info we need from you and you provided *none* of it.

Pictures, version numbers, debug crash log please. Or else we can't help you.
