### ISSUE TITLE
[1.16.5] Engineer manual required materials for bottling machine : 2 fluid pumps listed but only 1 is required

### ISSUE THREAD

**Issue by norm1000100** [BluSunrize/ImmersiveEngineering#4909]
Description of the issue:

When looking at the required materials for the bottling machine in the engineers manual, it lists 2 fluid pumps being required but in reality, only one is needed.

Crashlog:

N/A

Versions & Modlist : 

Forge Version : 36.2.0
IE Version : 1.16.5-5.0.2-137

Modlist : 
https://pastebin.com/KVKcnxnX

**Comment by BluSunrize** [comment]
Please actually use the issue template to provide us with the information we request, such as version numbers.

**Comment by norm1000100** [comment]
I've updated my issue. I hope that's clear enough

**Comment by IonNight** [comment]
Hi, Im flaying FTB Oceanblock 1.3.0 

This is still an issue on 1.16.5-5.0.4-139

I havent tried 1.16.5-5.0.5-140 bc its in version 1.5.0 beta of the pack.

https://imgur.com/a/pPOkhik

**Comment by asoshinsky** [comment]
Hey! Playing Oceanblock 1.11.0

The issue still persists. Not sure if you guys look at this post often but wanted to point it out.

The version of the IE in the modpack is ImmersiveEngineering-1.16.5-5.0.5-140

![Screenshot 2022-01-16 170251](https://user-images.githubusercontent.com/60367873/149670197-21e0e274-0266-4c84-930e-800bd755bc92.png)

**Comment by BluSunrize** [comment]
See issue for current version: #5304
