### ISSUE TITLE
is it possible to empty items from industrial squeezer with pipes?

### ISSUE THREAD

**Issue by kotoroshinoto** [BluSunrize/ImmersiveEngineering#491]
as in the title, is it possible to empty items from industrial squeezer with pipes?

the blocks that look like they have holes appear to be fluid outputs what do I do with byproducts?

**Comment by BluSunrize** [comment]
It's currently not working in IE 0.5.4, but it has already been fixed and will be in the new release =)

**Comment by kotoroshinoto** [comment]
Do you have a jenkins and are the jenkins builds stable enough for testing?

**Comment by BluSunrize** [comment]
No and no.

**Comment by James-T-Oudvoure** [comment]
What are "jenkins"?

**Comment by BluSunrize** [comment]
It's a service to provide up to date builds directly from the source. But I don't have one, so it doesn't matter.
