### ISSUE TITLE
[1.16.5] Client Crash on breaking Feedthrough Insulator

### ISSUE THREAD

**Issue by Neonit** [BluSunrize/ImmersiveEngineering#4911]
### Description of the issue:
When breaking a Feedthrough Insulator, shortly before it breaks, the client crashes.

### Crashlog:
[View GIST](https://gist.github.com/Neonit/758ec513addaeac241130fbd36c7781a)

### Versions & Modlist
- Minecraft: 1.16.5
- Forge: 36.2.1
- Immersive Engineering: 5.0.2-137

**Comment by smbarbour** [comment]
This was fixed nearly a month ago in the code, but they haven't released a new build with the fix yet.

**Comment by BluSunrize** [comment]
Correct.

Duplicate issue, please use the search next time.

**Comment by Neonit** [comment]
Oh, sorry. I did use the search, but I didn't search for closed issues, because it searches for open by default.

**Comment by Auriel1** [comment]
Same here, please close the issue posts when its resolved by update in game
