### ISSUE TITLE
[1.16.5] Game crash when trying to remove feed-through connectors

### ISSUE THREAD

**Issue by tkohnyo** [BluSunrize/ImmersiveEngineering#4915]
Good evening,

I encountered a bug in IE:
Setup: Make ANY feed-through connector
Issue: Every time trying to damage/remove it in survival, game will crash. Works without issues in creative, since it doesn't render the breaking animations.
Bug happens when playing multiplayer and singleplayer. It only affects the client, since the stacktrace points out a rendering exception (java.lang.NullPointerException: Tesselating block model)
Tested with modpack and single
I asked a friend of mine to test this issue, he encountered the same problems.

Game Info:
Minecraft 1.6.15
Forge 36.2.0
Immersive Engineering 5.0.2-137

Links:
Modlist: https://pastebin.com/0DVGJnUb
Crashlog: https://pastebin.com/RswUGpFk

**Comment by BluSunrize** [comment]
Duplicate issue, fixed for next release.

Please use the search function next time =)
