### ISSUE TITLE
[1.12.2] Metal Press not working

### ISSUE THREAD

**Issue by Dallen123** [BluSunrize/ImmersiveEngineering#4919]
Hello, I am playing Project Ozone 3 modpack currently and I found an issue with the metal press where it is not accepting inputs.

I have checked for everything (Direction of Conveyor Belt/Using "Ingore redstone control" conveyor belts"/ Using a hopper to input/ Making sure there is a cast)

Is anywhere anything I am doing wrong. Attached a picture for reference as well.

![Untitled](https://user-images.githubusercontent.com/49614096/129137688-b99a72d5-baa8-48bc-8e06-fd7fbddb0f99.png)

**Comment by BluSunrize** [comment]
Support for 1.12 ended over a year ago.
