### ISSUE TITLE
[1.16.5] Break a feedthrough insulator cause crash

### ISSUE THREAD

**Issue by Auriel1** [BluSunrize/ImmersiveEngineering#4920]
### Description of the issue:
I made a Feedthrough Insulator that works, but when i want to break it, my game crash as soon as i click on it. And it's the same if I click on the connector or on the central block

### Crashlog:
https://pastebin.com/TGnPVVpH

### Versions & Modlist
forge-1.16.5-36.1.0.jar
ImmersiveEngineering-1.16.5-5.0.2-137.jar
Detailled modlist with versions is in the crashlog

**Comment by BluSunrize** [comment]
Duplicate issue, please use the search function next time.
