### ISSUE TITLE
[1.16.5] Mixer Show Recipe overwrites content

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#4922]
The Show Recipetext overwrites  the content tex, that you can't read it.

![Mixer](https://user-images.githubusercontent.com/61501114/130040420-8fee8698-3c9c-4b40-b39a-3b135615d948.png)

**Comment by Steintigermaus** [comment]
i have the same problem with  "JEI" "Recipe Click Area". did you solve it?
