### ISSUE TITLE
Mixer JEI "click area" issue

### ISSUE THREAD

**Issue by Steintigermaus** [BluSunrize/ImmersiveEngineering#4923]
2 tooltips in Mixer, can I deactivate "show recipe"?

![130118638-39f78500-36a3-4428-962c-6d5770152ef7](https://user-images.githubusercontent.com/89216894/130141329-f3ab1e41-4835-4f13-825d-6c977966af9c.png)

**Comment by BluSunrize** [comment]
Fixed now in Immersive Engineering 1.16.5-5.0.7-143
