### ISSUE TITLE
coke oven bug 1.16.5

### ISSUE THREAD

**Issue by YellowShiba65** [BluSunrize/ImmersiveEngineering#4924]
when i try to make the coke oven multiblock i am unable to interact with it and the textures are bugged making it mostlly invisible it seems that the textures get rotated

### Crashlog:
no crash log

### Versions & Modlist
forge 35.2.0
https://pastebin.com/VR04c5rQ
i used the curse forge app to install the mods if that makes any difrence
![2021-08-20_00 06 15](https://user-images.githubusercontent.com/89227517/130155410-4e311d12-3cf3-49da-9466-f325b3361222.png)
![2021-08-20_00 06 20](https://user-images.githubusercontent.com/89227517/130155417-6b5e8b33-00a2-41b5-a905-0cebe1412797.png)
![2021-08-20_00 06 03](https://user-images.githubusercontent.com/89227517/130155426-cce0a391-9eeb-47e3-a750-10ecb2222023.png)

**Comment by BluSunrize** [comment]
Please create a debug crash by holding down F3 and C for 10 seconds, then put it on Pastebin and link it here.

**Comment by BluSunrize** [comment]
Closing this because support for 1.16.5 has ended
