### ISSUE TITLE
[1.16.5] Arc Furnace recipe does not use additives correctly 

### ISSUE THREAD

**Issue by Pdiddy973** [BluSunrize/ImmersiveEngineering#4926]
### Description of the issue:
when making a recipe for the arc furnaces, it does not use all of the additives when smelting multiple items at once or when additives are stacked

Single input, with additives separate:
![Animation2](https://user-images.githubusercontent.com/68764896/130312623-ce91d1a3-5626-462e-acf1-73bbafd3e4c4.gif)

Single input, with additives stacked:
![Animation3](https://user-images.githubusercontent.com/68764896/130312673-96fdcd97-fa6a-42ba-bd9f-a94d5921bd4e.gif)

Multiple Inputs with additives separate:
![Animation4](https://user-images.githubusercontent.com/68764896/130312738-493805ca-93f8-4336-a4d7-0c8373b64c9a.gif)

Multiple inputs with additives stacked:
![Animation](https://user-images.githubusercontent.com/68764896/130312566-44c37cf0-fcdc-4847-9b50-25937e2b3980.gif)

### Versions & Modlist
IE: 5.0.3-138
Forge: 36.2.2

**Comment by BluSunrize** [comment]
Could you please also tell me what the designed inputs of that recipe are? I can't really identify any of those blocks.

**Comment by Pdiddy973** [comment]
compressed iron block + 2 compressed coal blocks, makes 1 compressed steel block

**Comment by Pdiddy973** [comment]
here is the [example recipe](https://github.com/Pdiddy973/AllTheCompressed/blob/1.16/src/main/resources/data/imersiveengineering/recipes/arc_furnace/allthecompressed/iron/1x_to_1x_steel.json) I'm trying to do

**Comment by Pdiddy973** [comment]
Any update on this?

**Comment by BluSunrize** [comment]
Closing this because support for 1.16.5 has ended
