### ISSUE TITLE
[1.16] Arc Furnace recycling, Kube_js doesn't delete the recipe

### ISSUE THREAD

**Issue by Inverseder** [BluSunrize/ImmersiveEngineering#4929]
Hey I'm using KubeJs to make custom recipe and I want to delete the recycling recipe of copper wire and edit other recipe. It's working with all immersive recipes but not with recycling recipes. It's a problem or i have made something wrong.
Here my code:
`events.listen('recipes', function (e) {e.remove({id: 'immersiveengineering:recycling/wire_copper'})})`
Thanks for helping

**Comment by BluSunrize** [comment]
Recycling recipes can not be removed separately.
Please use a datapack to override `immersiveengineering:arc_recycling_list`
