### ISSUE TITLE
Feature Request: Add Regex item name filtering to Item Router aka SorterTileEntity

### ISSUE THREAD

**Issue by JTinkers** [BluSunrize/ImmersiveEngineering#4930]
Hello,

Since adding filtering to item router is limited to 8 blocks and it's rather tedious to set multiple routers to filter more than just 8 blocks - I would like to request feature where you could put a Book and Quill with written Regex pattern in it.
E.g.: 
"cobble.* - would match all cobble items, including cobblestone stairs, cobblestone, cobblestone slab et cetera.
"(granite.*|diorite.*|andesite.*)" - would match virtually anything made of granite, diorite, or andesite.

I would add it myself, but Java isn't my forte - thank you in advance!

**Comment by BluSunrize** [comment]
Too involved. I don't want the sorter to be that complex, as I have explained on previous issues dealing with OreDict/Tags
