### ISSUE TITLE
[1.16.5]Metal press cannot be put into the mold

### ISSUE THREAD

**Issue by Biaogo** [BluSunrize/ImmersiveEngineering#4932]
Forge: 36.2.2
![1](https://user-images.githubusercontent.com/56547184/130632344-7c1c0b1c-90c8-4113-a408-c0a876ab075a.png)
![2](https://user-images.githubusercontent.com/56547184/130632372-32f5b8e5-8845-4a69-859e-e8b744461042.png)
![3](https://user-images.githubusercontent.com/56547184/130632392-6e954b97-390e-4907-9ca0-2f03f8422658.png)
I can't put mold in metal press
![4](https://user-images.githubusercontent.com/56547184/130634178-97cec484-a7e5-445c-bce9-336e4526e415.png)

**Comment by BluSunrize** [comment]
Have you checked if there are recipes?

Also, which part of "use the issue template" did you not understand?
