### ISSUE TITLE
[1.16.5] Vertical Covered Conveyor crashes and corrupts save in Create mod contraptions

### ISSUE THREAD

**Issue by abovearth** [BluSunrize/ImmersiveEngineering#4933]
### Description of the issue:
When I create a Create mod contraption, and use a Vertical Covered Conveyor, the moment I tell the game to make the contraption a moving part, the game crashes. I have tested it with all other conveyors, covered and non-covered, including the vertical non-covered conveyor, and those don't crash the game. When I try to reopen the world, the game crashes again.

Minimal work to reproduce the issue: Start a new creative minecraft world. Stack a Create:Creative Motor, a Create:Mechanical Bearing and a IE:Vertical Covered Conveyor. Click the Mechanical Bearing to turn the blocks into a Create Contraption. Your game crashes. Screenshot precrash https://imgur.com/a/uh5vTRj

What I think happens, based on my interpretation of the crashlog, when I click the bearing, Create tries to render a simplified version of the connected blocks. The Vertical Covered Conveyor for some reason is not able to do that. And that causes the game to crash. When I re-open the world, the contraption tries to render again, and the game crashes again. That's why I assume that my save is corrupted.

Furthermore all conveyors of all types are rendered as the most basic conveyor. But that's okay for me, because the moving contraptions are static renders anyway.

### Crashlog:
https://gist.github.com/abovearth/ab84d1e37b0c40ae0900dde646265f74

### Versions & Modlist
Minecraft 1.16.5 
Forge 36.2.0 
Immersive Engineering 1.16.5-5.0.3-138 
create-mc1.16.5_v0.3.2
flywheel-1.16-0.2.3

flywheel is a Create dependency

### Link to the issue on the Create Repo
https://github.com/Creators-of-Create/Create/issues/2150

**Comment by abovearth** [comment]
I just had another crash involving the fluid pipe. I have updated the gist with new crash reports.

**Comment by abovearth** [comment]
I have now tested all non solid blocks of IE. The only other non-expected behavior was the balloon Which causes the contraption to not render, but does not crash the game. Funnily enough, because it does not render, the crashes caused by the other 2 bugged blocks do not happen.

**Comment by abovearth** [comment]
https://github.com/Creators-of-Create/Create/issues/2150#issuecomment-905076543

**Comment by BluSunrize** [comment]
Closing this because support for 1.16.5 has ended
