### ISSUE TITLE
Texture Problems

### ISSUE THREAD

**Issue by Syrade** [BluSunrize/ImmersiveEngineering#4936]
after i installed the mod, launched the game and joined a singleplayer world this happened
![Screen Shot 2021-08-29 at 10 40 52 AM](https://user-images.githubusercontent.com/89738145/131254398-d94e5dc2-3798-427c-b6c7-6ff6517804c9.png) this is on 1.16.5. i was using sodium for forge.

**Comment by BluSunrize** [comment]
Please read the damn issue template and contribution guidelines. This issue contains no useful information.

1) remove sodium and see if you still have the issue
2) if you do, provide a debug crash log by holding F3 and C for 10 seconds. Then put that on gist or Pastebin and link it here.
