### ISSUE TITLE
[1.17.1] visual error with engineer's toolbox

### ISSUE THREAD

**Issue by Sheenus** [BluSunrize/ImmersiveEngineering#4937]
### Description of the issue:
Opening the engineer's toolbox gives the following (see below picture). Note the position of the player inventory label.

![label in wrong spot](https://cdn.discordapp.com/attachments/826497495491280957/881856678251872256/2021-08-30_21.02.31.png
)

### Crashlog:
No crashlog, as this issue did not force a crash.

### Versions & Modlist
Minecraft 1.17.1
Forge 37.0.44
IE 1.17.1-5.0.2-pre.127
_MixinBootstrap-1.1.0
JEI 8.0.0.14
Journeymap 5.7.3rc3

**Comment by malte0811** [comment]
Fixed in 5e80714015e3644ce670ca747523239289e8f7e3
