### ISSUE TITLE
[1.17.1] Axes appear to break treated wood as if by hand

### ISSUE THREAD

**Issue by Sheenus** [BluSunrize/ImmersiveEngineering#4938]
### Description of the issue:
When breaking treated wood placed in the world, it appears to take as much time to break with any type of axe as it does to break it by hand. Don't have any documentation showing, but can make later if needed.

### Crashlog:
This issue didn't force a crash. 

### Versions & Modlist
Minecraft 1.17.1
Forge 37.0.44
_MixinBootstrap-1.1.0
ImmersiveEngineering-1.17.1-5.0.2-pre.127
jei-1.17.1-8.0.0.14
journeymap-1.17.1-5.7.3rc3

**Comment by malte0811** [comment]
Fixed by 398012dc970f0b68b0b5f95c67db33b09fc6ec67
