### ISSUE TITLE
HV wires and BigReactors...

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#494]
IE does not play nicely with BigReactors.. or is it the other way round...

Issue: IE HV wires burn if the RF source was BigReactors

Steps to reproduce:
[1] build a BigReactors turbine , or a BigReactors reactor... haven't tested the reactor itself. 
[2] activate turbine, and allow it to fill its buffer, or until the buffer is above 4096 RF
[3] connect one HV wire connector from the power tap to any consumer.
[4] observe.

IE version 0.6.0_pre Built against commit f0a24da

**Comment by malte0811** [comment]
This is basically the same problem as we experienced with the cryo-stabilized fluxducts: `transferEnergy` is getting called more than once per tick, [here](https://github.com/erogenousbeef/BigReactors/blob/master/src/main/java/erogenousbeef/bigreactors/common/multiblock/MultiblockReactor.java#L371) and [here](https://github.com/erogenousbeef/BigReactors/blob/master/src/main/java/erogenousbeef/bigreactors/common/multiblock/MultiblockReactor.java#L380).

**Comment by theunkn0wn1** [comment]
Wonderful.. And based on how Blu responded to that one... This is not going
to be fixed is it?

**Comment by cobra** [comment]
You should be able to avoid this by adding more power taps (with connectors or something else accepting energy) to the reactor. If it's outputting less than 16384 RF/t 4 taps with connectors should be enough to keep the wires from frying.
I guess this should be added to the manual then. The cryo-stabilized fluxducts were a rather senseless corner case, but BigReactors are a lot more common.

This could also be a use case for a EHV/UHV/whatever tier. (I secretly want really long connectors and a multiblock transformer for that)

**Comment by BluSunrize** [comment]
Or: Just place an HV capacitor between it. Those will only output once per tick >_>

**Comment by theunkn0wn1** [comment]
@cobra the problem is i cannot add the consumers to the end of the line without frying the line to begin with. Why can't the Connector itself only accept 4096 RF in a single tick? That would solve the problem wouldn't it? My setup as Eight RF power taps with eight separate power lines (all HV) to draw off the power, there is no way to prevent the reactor from outputting, that i know of, its power until i can get consumers on the other end. Also, in true builds one would rarely reach the max consumption until late game, making it really difficult to use IE's power system to directly interface with BigReactors. Yeah we could add capacitors to the powertaps before relaying the RF, as @BluSunrize states, but that would be an extra layer of complexity that can make builds more confusing then they have to be imo. The capacitors are just a band-aid, not a complete solution.

Here are a few pictures of my build.
![image](https://cloud.githubusercontent.com/assets/3110986/10412115/8a947b2a-6f30-11e5-9599-433ad085310a.png)
![image](https://cloud.githubusercontent.com/assets/3110986/10412290/23c73a9e-6f36-11e5-804b-7f008d81dd19.png)




@BluSunrize , the build I made that induced this bug is not hard for end users to come across, I have just prettied it up, and i doubt that I am going to be the last person to come across this. The way I have setup my power plant just does not grant room for adding a HV capacitor on top the taps before sending out the power without rebuilding the whole darn thing. I could find no documentation, besides what you have stated in this thread, that there would be a problem with how i have setup my plant. But hey, I *am* playing with pre-releases... :3 It just seems illogical if the lines can only carry the current given to them by one RF input to be fried by that input. I have been under the impression that the connector should only be able to accept or push RF at a fixed rate per tick. (4096 RF/t)

You should not expect that other RF mods to play nicely to the way you have set things up, especially with those whom deal with high energy transfer. With the TE Cryo-fluxducts i can respect your reasoning, trying to funnel infinite power into a finite point should not end well; but BR is not infinite, it is still producing and transferring at a finite rate. I am quite sure that other mods, besides TE and BR are doing the exact same thing with RF, this issue is just going to keep popping up until it gets fixed.

**Comment by theunkn0wn1** [comment]
I have 8 HV connectors, total of 10 taps (two being used to power the plant itself, using TE fluxducts)
It is not quite feasible to get consumers onto the end of each of those 8 output lines without them being  fried, i don't have a strong desire to shut down the turbine+reactor every time I want to expand. Also, even in late game it can be dificult to consume 20+KiRF/t unless one is really trying to. I like having network saturation so I have power to spare, so I always build my power systems with expansion in mind, i am sure other end-users have the same mentality.

 The issue here is how IE handles RF, and workarounds are for temporary use until the issue they revolve around gets resolved. HV capacitors are a band-aid type workaround imo. This issue is less of that odd-kid-in-the-corner thing like the Cryo-fluxducts. @BluSunrize you cannot igore this forever, would it be do difficult to cap the RF input per connector per tick?

**Comment by cobra** [comment]
The problem is that there is no direct way of limiting the RF input per tick at the connector. All (RF API) limits are per transfer and these calls are not "ticked" like the updateEntity method. If we want to limit that, we have to check whether the connector already accepted some power in this tick by saving the tick time for all transfers and checking it (and possibly the amount of RF already accepted for this tick and connector). I already tested something like this (limit to the first transfer per tick) for #385 and it worked as far as I could see.

I haven't decided what I think about this problem yet. BigReactors is a lot more common than the rather weird setup of #385, on the other hand simply placing something else limiting the RF flow between tap and connector isn't that bad.

**Comment by theunkn0wn1** [comment]
@cobra sure, I will go test other methods, though the RF mods that i know of is a quite small list. Il update this with what i find

**Comment by BluSunrize** [comment]
Yes, I could cap the amoutn input per tick. Either I store that internally on the tile, requirig me to make it tick (I'm very happy that they currently don't) Or I save it in a map and reset it golbally liek I do for wire burn. And with the amount of bitching that I get, I might as well. The biggest issue here is the clash of design ideals. I like keeping my power production on a the minimum, jsut as much as I use. I don't use vast, unnecessary, AE systems so I do not have any need for Big Reactors or CryoStabilized bullshit. I guess I just have to come to terms with the fact that big parts of the community are powercreeps.

It's not Vazkii level yet, but people are already yelling at me for decisions that I make on my mod which I consider /game design/ and /intended/.

**Comment by malte0811** [comment]
ANY "transparent" energy transfer method (Zetta Industries energy meter, AE2's P2P tunnels, ...), combined with only IE, allows to reproduce this issue: 
![2015-10-10_20 04 58](https://cloud.githubusercontent.com/assets/10406104/10412580/61818a2a-6f8a-11e5-960d-fecff389387e.png)
This setup causes any wire connecting the two connectors on the left to burn (The right P2P feeds into the left one). Unless you consider IE (or any transparent energy transfer) to be powercreep, this has nothing to do with powercreep.
If you add a map storing the energy that entered the net through a connector, please also add a map storing the energy that has left the network through a connector and limit the output per connector to the transferrate of the corresponding wire.

**Comment by cobra** [comment]
Sadly, I don't have this code I tested back then any more, but AFAIR I just added a field to TileEntityConnectorLV, stored and checked the current absolute time for each transferEnergy call. No need for ticking tileEntities or new maps.

**Comment by malte0811** [comment]
@cobra that will not work quite as well as a map would, since there are worlds (e.g. my IE test world) which have the gamerule `doDaylightCycle` (or something like that) disabled, therefore the world time (which I asume is what you mean with "absolute time") is never increased (unless /time is used). A map is probably the best solution

**Comment by cobra** [comment]
@malte0811 I'm doing the same for my worlds, it's not the daytime, it's the absolute world time, as in a tick counter. Fiddling with the /time didn't break anything.

**Comment by BluSunrize** [comment]
correct. world.getTotalWorldTime() works independently of day/night cycle

**Comment by BluSunrize** [comment]
There we go, that commit adds a timestamp, @cobra was that your general idea?

**Comment by cobra** [comment]
Yep, that's very similar to what I did (you even have the same variable name) and remember from back then, but I added this to receiveEnergy, as that's the method being called to often. I was still debugging that as my limiter triggered too often, e.g. with normal fluxducts. I even used the server's tickCounter, but it was still the same. I'll test yours.

**Comment by cobra** [comment]
Oh fuck, turns out I've been a complete idiot yesterday evening and had it working on the first try with the same logic you implemented, but had forgotten about a connector. Should've looked at the coordinates of the one triggering it. Remember: don't hurry and debug! m(
Scratch everything I wrote above (except the part about me modifying receiveEnergy instead of transferEnergy).

Still, I'm able to wire up this thing:
![](https://cloud.githubusercontent.com/assets/163331/10417675/0b884cec-7045-11e5-8d8c-7f0989f62417.png)
Using two connectors on the resonant fluxduct (instead of one and the other one on the cryo duct) burns the wire every time, the setup above does this only directly after connecting the second input. Rewiring the middle and last (output) segment after they went up in flames gives me this stable setup transferring 4096 RF/t.
This happens both with your solution and the one I implemented, but not with ff7460a (all 3 wires between the cryo ducts burn up - no surprise)

**Comment by BluSunrize** [comment]
Yeah that is bound to burn. It wont after I rebalance the max values. Because the in and outputs on HV will still be 4096 but wires will allow more that 4096 per tick
I just haven't adjusted the config yet

**Comment by theunkn0wn1** [comment]
OK, this issue thread has run its course. As far as I can test, the original issue of mine has been resolved. The rebalance appears to be complete for now, and my BigReactor setup no longer kills my HV wires without due reason. Going to close this now
