### ISSUE TITLE
[1.17.1] Wires break on server disconnect/reconnect

### ISSUE THREAD

**Issue by JStocke12** [BluSunrize/ImmersiveEngineering#4940]
When I leave and rejoin the IE dev server, all of my wires break, and I can recreate this consistently. Right now I only have LV wires, so I cannot test with other wire types. My wires all break regardless of whether they are between a connector and a relay or a connector and a connector. I cannot recreate this on a single player world. I haven't asked, but it seems like other players don't recreate the issue either. A picture of my setup is shown below. 

![2021-08-30_17 35 12](https://user-images.githubusercontent.com/56052177/131408897-4e6658e1-1f21-4678-a8fd-668dd4343e88.png)

I forced a crash with F3+C, here is the log: [Crashlog](https://gist.github.com/JStocke12/4f1961962b78ed46284106807796baec)

I'm running the server mod list with dev build #4, ImmersiveEngineering-1.17.1-5.0.2-pre.127.jar

**Comment by JStocke12** [comment]
I added a capacitor to the line, and it stopped breaking.

![2021-08-30_21 48 25](https://user-images.githubusercontent.com/56052177/131428483-0de81c2d-4b74-44dc-aec2-8b524edcbd87.png)

However, other lines still break.

**Comment by Sheenus** [comment]
Also having this problem; appears to happen on chunk load? Tried setting up wires inside a chunk (not across chunk lines) and same thing happened.
