### ISSUE TITLE
1.17.1 Crusher Recipe needs fixing 

### ISSUE THREAD

**Issue by Holli-Git** [BluSunrize/ImmersiveEngineering#4941]
### Description of the issue:

Copper ore, when mined, gives 2-3 raw copper. However, crushing a full block in the crusher only yields 2 dust, when it should yield 4-5. 
### Versions & Modlist

Forge 37.0.44
ImmersiveEngineering-1.17.1-5.0.2-pre.131
MixinBootstrap-1.1.0
jei-1.17.1-8.0.0.14

**Comment by malte0811** [comment]
1. You're supposed to delete most of the template, leaving just the section headers and the stuff you added.
2. This is really a question for @BluSunrize (I'll assign it to him), but I believe the general consensus was to treat copper the same as everything else when this was discussed between a bunch of modders. I could easily be misremembering that though.

**Comment by BluSunrize** [comment]
I'll attend this after my vacation.

**Comment by Sheenus** [comment]
Not sure if it's related, but it's still to do with crusher recipes; there aren't any recipes for any of the deepslate ores either (e.g. deepslate copper ore, deepslate iron ore, deepslate diamond, etc). Was going to submit a new issue, but figured I'd mention it here first.

**Comment by malte0811** [comment]
That is an unrelated problem, Forge hasn't updated tag content to the 1.17 changes yet. I'll temporarily handle deepslate ores on IEs side, there's a decent amount of code that has a `TODO Forge#7891` on it already.

**Comment by Holli-Git** [comment]
Ah, sorry Malte! Still trying to figure out Github
