### ISSUE TITLE
Floodlight not working.

### ISSUE THREAD

**Issue by skylergamingca** [BluSunrize/ImmersiveEngineering#4942]
When I use a floodlight. I power it correctly, I hook it up to the wires correctly. But no matter how hard I try, that floodlight emits no light at all. I have tried to get this floodlight to work in many servers, I have tried to get it to work on another Minecraft installation. Still, I have no response of light from the floodlight.
![2021-08-31_18 29 55](https://user-images.githubusercontent.com/39119888/131469602-9df4468d-af6a-4c31-9738-b06aa8a1730d.png)

**Comment by BluSunrize** [comment]
And you also ignored the issue template.

Without version info and a debug crash, there is basically no way to help you. So please hold down F3 and C for 10 seconds, take that crashlog, put it on pastebin and link it here.
Thank you.

**Comment by BluSunrize** [comment]
Oh also, there doesn't appear to be a redstone signal on that floodlight. It might be helpful if you took some screenshots of a test setup outside, so we can actually see what you are doing.
