### ISSUE TITLE
automatic lubricator unit bug (bucket/milibucket)

### ISSUE THREAD

**Issue by RichardSabol** [BluSunrize/ImmersiveEngineering#4943]
FTB continuum, minecraft version 1.12.2. Immersive Engineering version 0.12-88.
Automatic lubricator has set wrong input units. Instead of inserting buckets of lubricator, milibuckets are inserted.

**Comment by BluSunrize** [comment]
1. The lubricator is from Immersive Petroleum
2. We stopped supporting 1.12 well over a year ago. Go update.
