### ISSUE TITLE
[1.17.1] crash upon rendering Feedthrough Insulator (?)

### ISSUE THREAD

**Issue by Sheenus** [BluSunrize/ImmersiveEngineering#4944]
### Description of the issue:
Client crash upon creation of an MV Feedthrough Insulator (one of the RF connector elements that has MV connectors on both sides of a solid block).

### Crashlog:
can be found here: https://pastebin.com/f6ZUBDbt

### Versions & Modlist
Minecraft 1.17.1
Forge 37.0.44
_MixinBootstrap-1.1.0
ImmersiveEngineering-1.17.1-5.0.2-pre.133
jei-1.17.1-8.0.0.14
journeymap-1.17.1-5.7.3rc3

let me know if you need the game log as well.

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/7c98f9d4a9ab19acd16c112fbaf8df7ce26ed3fb
