### ISSUE TITLE
[1.17.1] Shift-Click Not Triggering Max Upgrade Achievements

### ISSUE THREAD

**Issue by DeadlySwede** [BluSunrize/ImmersiveEngineering#4945]
### Description of the issue:

If you shift-click from workbench to inventory on a maxed-out mining drill or buzz saw, the max upgrade achievement does not trigger. You have to manually drag the maxed-out tool from the workbench to your inventory.

First noticed on multiplayer IE 1.17 test server. Duplicated in single player. May have been that way from the beginning, don't recall having to drag it manually.

### Crashlog:

None.

### Versions & Modlist

Minecraft 1.17.1
Forge 37.0.44
Immersive Engineering 1.17.1-5.0.2-pre.133
Journeymap 5.7.3rc3
Just Enough Items 8.0.0.14

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/55c2302b03bcdbd3d494559af7d54006d2ff1842
