### ISSUE TITLE
[1.17.1] Broken Item Batcher GUI

### ISSUE THREAD

**Issue by JStocke12** [BluSunrize/ImmersiveEngineering#4946]
When opening the Item Batcher GUI on IE 1.17.1 dev build #8, a large white rectangle covers a significant portion of the GUI.

![2021-09-01_12 53 22](https://user-images.githubusercontent.com/56052177/131712455-4249a57d-08a4-4d7d-9755-a358f9a9fd02.png)

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/1ae81309ab59d1af99f20aec1cd78c856242b5e7
