### ISSUE TITLE
[1.17.1] Offset in Mirrored Automated Workbench Model

### ISSUE THREAD

**Issue by JStocke12** [BluSunrize/ImmersiveEngineering#4948]
In 1.17.1 dev build 12, part of the mirrored model for the automated workbench is offset outside the bounds of the multiblock.

![2021-09-02_18 14 15](https://user-images.githubusercontent.com/56052177/131923273-84ed46ea-3e31-4436-975e-d59ec5fc62de.png)

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/32d20274d1d1802c71aad780932c7437b25e4ff2
