### ISSUE TITLE
[1.17.1] Automated Workbench Output Issue

### ISSUE THREAD

**Issue by JStocke12** [BluSunrize/ImmersiveEngineering#4949]
In 1.17 dev build 12, the automated workbench outputs items at the center of the multiblock rather than the end of the conveyor belt. This causes the items to get stuck.

![2021-09-02_18 28 05](https://user-images.githubusercontent.com/56052177/131924264-81514dc9-039e-49fe-91c3-374982014b88.png)

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/40b68096f263e26319491ef693dff19998d34402
