### ISSUE TITLE
[1.17.1] using JEI to set filters on Item Routers crashes client

### ISSUE THREAD

**Issue by Sheenus** [BluSunrize/ImmersiveEngineering#4950]
### Description of the issue:
Pretty much what it says on the tin; attempting to drag'n'drop items from JEI into the filter GUI for an item router, in order to set the router's directional item filters, crashes the client.

### Crashlog:
no crashlog was generated; here's the session log: [Pastebin](https://pastebin.com/Y0ubidD6)

### Versions & Modlist
MC 1.17.1
Forge 37.0.44
ImmersiveEngineering-1.17.1-5.0.2-pre.138
MixinBootstrap-1.1.0
jei-1.17.1-8.0.0.14
journeymap-1.17.1-5.7.3rc3

**Comment by malte0811** [comment]
Should be fixed by mezz/JustEnoughItems#2469 once that's merged.
