### ISSUE TITLE
[1.16.5] Manual not opening ("1 entries failed to load")

### ISSUE THREAD

**Issue by Nezraddin** [BluSunrize/ImmersiveEngineering#4951]
### Before reporting:
Done, only found closed issues from march.

### Description of the issue:
When I try to open the manual it just gives me an error message "1 entries failed to load" and tells me that I should put this issue up for you to read.
Done some testing and it seems the combination of "immersive petroleum" and "immersive posts" create the error. Using one or the other works, using both creates the error.
So not sure if this issue would better go to them (because their way of writing their information into your mods manual gone wrong/crash together) or here (because the manual is part of IE).

### Crashlog:
Not crashed.

### Versions & Modlist
IE-Version: ImmersiveEngineering-1.16.5-5.0.3-138
Forge Version: 36.2.0

Modlist:
https://pastebin.com/i7yDC9rP

latest.log: 
https://gist.github.com/Nezraddin/b2a78c056ab4a4863ef4fcd09cd66270
Timestamp for issue: [15:33:29], line 24567

### Lastly (you may delete this from the report itself)
Thank you for reporting issues, without people reporting them, they wouldn't get fixed. You're helping contribute to this mod and that is much appreciated <3

-> Hope I did follow the guideline correctly, my first issue-report I do here. :)

**Comment by ghost** [comment]
Immersive Posts dev is aware: https://github.com/TwistedGate/ImmersivePosts/issues/34

**Comment by BluSunrize** [comment]
IP issue, closing this one

Well reported tho!
