### ISSUE TITLE
[1.17.1] Strange fluid behaviour, including crash when picked up with bucket

### ISSUE THREAD

**Issue by Sheenus** [BluSunrize/ImmersiveEngineering#4952]
### Description of the issue:
Observed strange behaviours when attempting to interact with IE-introduced fluids:
 - Placing fluids into the world from an item, like a bucket or jerrycan, appears to not render properly until a second unit of fluid is placed within the same voxel. 
 - at the first placing of a fluid in the world, the fluid will affect entities (e.g. creosote applying flammable, ethanol applying nausea etc.) but simply not appear to render.
 - at either point, when a fluid is attempted to be retrieved from the world to an empty fluid container-item (e.g. a bucket), the game crashes (tested in Singleplayer Creative; not sure if this will cause a server crash)
 - while attempting to gather screenshots for clarity, simply observing the fluid in-world caused a game crash.

### Crashlog:
the third incident produced a crash log, which can be viewed [here](https://pastebin.com/EJNKnwDF).
the fourth incident's crash log is [here](https://pastebin.com/qA9DfHd2).

### Versions & Modlist
MC 1.17.1
Forge 37.0.44
ImmersiveEngineering-1.17.1-5.0.2-pre.138
MixinBootstrap-1.1.0
jei-1.17.1-8.0.0.14
journeymap-1.17.1-5.7.3rc3

**Comment by JStocke12** [comment]
Additionally, if you block update the fluid the game crashes.

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/5b5755d6bcecb490e0b6ef765b0eadcf27cdfd54 and https://github.com/BluSunrize/ImmersiveEngineering/commit/8f5ab38ed9293f4641b2eae674ec59722726b828 should fix a lot of fluid-related bugs, if any pop up after the next server update please open a new issue.
