### ISSUE TITLE
[1.17.1] Jerrycan refill recipe not working

### ISSUE THREAD

**Issue by Sheenus** [BluSunrize/ImmersiveEngineering#4953]
### Description of the issue:
In a dedicated server environment, the jerrycan refill recipe (as described in the Engineer's Manual, whereby tools requiring fuel can be refilled by the appropriately filled jerrycan via the crafting menu) does not appear to give a refilled tool; no recipe result is generated.

### Crashlog:
This issue does not generate a crash report.

### Versions & Modlist
MC 1.17.1
Forge 37.0.44
ImmersiveEngineering-1.17.1-5.0.2-pre.138
MixinBootstrap-1.1.0
jei-1.17.1-8.0.0.14
journeymap-1.17.1-5.7.3rc3

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/e4ee1add30cc2bc682f85212bf2998576936a2de
