### ISSUE TITLE
[1.16.5] Unable to view HOP Graphite dust recipe with JEI 7.7.1.121

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#4954]
### Before reporting:
Done. Checked for duplicates and did not see any.

### Description of the issue:
Trying to view the HOP Graphite dust recipe using JEI 7.7.1.121 shows up blank. Downgrading to JEI 7.7.1.118 fixes the problem.
![132050730-f51d157c-6273-484a-bafa-724ea1826c2d](https://user-images.githubusercontent.com/51542538/132100062-d8ac8423-5657-49d0-9a57-82442f542095.png)

### Crashlog:
Not a crash, but here is the relevant info found in the latest.log: https://pastebin.com/rtN0R4t5

### Versions & Modlist
Clean instance with only the following:
Minecraft 1.16.5
Forge 36.2.4
JEI 7.7.1.121
Immersive Engineering 5.0.3-138

I have also reported this on the JEI GitHub here: https://github.com/mezz/JustEnoughItems/issues/2482. My apologies if this is not an IE issue, but whatever changed in JEI after version 118 also appears to have affected some other mods, and based on [this comment by mezz](https://github.com/mezz/JustEnoughItems/issues/2468#issuecomment-910248086) I am reporting this here as well just in case it is something that needs fixed on this end.

**Comment by zululul** [comment]
When I try to click for the recipe for that item my game crashes.
