### ISSUE TITLE
[1.17.1] Forming multiblocks causes adjacent block transparency

### ISSUE THREAD

**Issue by JStocke12** [BluSunrize/ImmersiveEngineering#4959]
For multiblocks where full blocks turn into partial blocks, when they form, adjacent blocks remain transparent.

![2021-09-06_15 11 25](https://user-images.githubusercontent.com/56052177/132255110-4d7c905d-9cf8-47c3-b71d-5cb5bec4fac4.png)

**Comment by malte0811** [comment]
I'm unable to reproduce this. Have you tried in a singleplayer world? Do you have any additional mods installed (compared to what's in the gist)?

**Comment by Sheenus** [comment]
I can reproduce this, but only at one section of my base: this metal press up against this wall. (Also on the 1.17 test server)
![2021-09-10_20 39 27](https://user-images.githubusercontent.com/2409029/132841636-09745cc4-cb31-4f71-95cf-afc35dca30bb.png)

Only extra mod I have from the gist is "journeymap-1.17.1-5.7.3rc3". haven't tried to replicate in a singleplaye world, but will give it a crack when I have some spare time.

**Comment by DeadlySwede** [comment]
Here's an example from single player. Create a tank and surround the top row with stone blocks.

- Minecraft 1.17.1
- Forge 37.0.59
- Immersive Engineering  1.17.1-5.0.2-pre.119
- Journeymap 5.7.3rc3
- Just Enough Items 8.0.0.14

![2021-09-14_20 50 39](https://user-images.githubusercontent.com/2657769/133357504-8c40235d-e0a8-4452-ac05-b9b827f57c16.png)
![2021-09-14_20 51 27](https://user-images.githubusercontent.com/2657769/133357527-8167a523-7700-4cb3-a404-a0d944720cea.png)

**Comment by MalkContent** [comment]
just got this and I'm confused, but it may help reproducing
done in superflat
the generators' orientation lengthwise is east to west, the generators with transparency are having their Generator Blocks facing east
![grafik](https://user-images.githubusercontent.com/7753414/133414189-070b04ec-edc3-4e6d-87ed-2ff178e414d1.png)
note that mirroring the Diesel Generator did not affect transparency in this instance

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/f2d8c11455f5c14a9d526996b9e8ffab766ac9fd
