### ISSUE TITLE
1.16.5 excavator not working

### ISSUE THREAD

**Issue by zululul** [BluSunrize/ImmersiveEngineering#4960]
So I made this excavator and my server crashed when I R-clicked with the hammer. The wheel works but the machine is not working. So I went to the Forge cfg file and changed the "removeErroringTileEntities = false to true and it worked to R-click the machine but the problem is the machine is not working the block you R-click with the hammer is becoming a ghost block wich makes the Excavator, not functioning.

Here is an image of the excavator: 
![image1](https://user-images.githubusercontent.com/33579344/132394805-472d7b1c-4329-467f-a77a-4fc994671731.jpg)
![image2](https://user-images.githubusercontent.com/33579344/132394817-d6280b0a-0cc9-411c-92cd-952c9bbe2e2f.png)
![image3](https://user-images.githubusercontent.com/33579344/132394821-5f4a9f84-0dd0-467e-8ad3-48dea5ddc68b.png)

**Comment by BluSunrize** [comment]
It would help if you actually provided us the crashlog. That Forge config option will literally just remove that Tile from the world, which - surprise - will obviously not make the excavator work.

**Comment by zululul** [comment]
Sorry for the late response, but yes. I am aware of the forge config but then my server is gonna crash if I don't enable it. Here is the crash log from the server: 
[crash-2021-09-07_20.15.52-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/7137671/crash-2021-09-07_20.15.52-server.txt)

**Comment by BluSunrize** [comment]
Did you change the size of mineral veins in the server config? Because you are getting a divide by zero for the size of the vein...

**Comment by zululul** [comment]
I didn't touch anything on the config besides enabling that forge thing I was talking about and what does that mean? and Do you know how to fix it? Thanks for the response btw.

**Comment by zululul** [comment]
Another issue I found is that I can't click on the recipe for HOP graphite dust so I'm unable to use the arc furnace to make the rods.

**Comment by zululul** [comment]
Why is it closed?

**Comment by malte0811** [comment]
Because it's fixed for the next build. No ETA on that though.

**Comment by zululul** [comment]
Ok thank you
