### ISSUE TITLE
[1.17.1] Loading connectors crashes client

### ISSUE THREAD

**Issue by Sheenus** [BluSunrize/ImmersiveEngineering#4962]
### Description of the issue:
Was walking towards my diesel generator powering my excavator (which is set up a considerable distance from the generator), and all of a sudden my client crashed with the below crash report.

### Crashlog:
[crash-2021-09-08_22.05.32-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/7128728/crash-2021-09-08_22.05.32-client.txt)

### Versions & Modlist
Minecraft 1.17.1
Forge 37.0.53
MixinBootstrap-1.1.0
ImmersiveEngineering-1.17.1-5.0.2-pre.145
jei-1.17.1-8.0.0.14
journeymap-1.17.1-5.7.3rc3

**Comment by BluSunrize** [comment]
Should have been addressed by now, 1.17 was only in beta anyway
