### ISSUE TITLE
Possible cloche crash on FTB ATM

### ISSUE THREAD

**Issue by accusitive** [BluSunrize/ImmersiveEngineering#4963]
### Description of the issue:
The server crashes upon the first player joining (and presumably loading a certain chunk)
I had a cloche setup to output to a crusher, this worked fine.
But now every time I join with immersive engineering installed, the game crashes with this crash log.
Removing immersive engineering fixes the issue. (But removes crusher being able to use biofuel)

### Crash log:
[Crash Log](https://gist.github.com/accusitive/dfb0eca6582804736d8f040baf4980b4)

### Versions & Modlist
All the mods 6-17.11
Plus a mod named car, and a mod named plane but the same thing happens without them.

**Comment by accusitive** [comment]
Does not occur on 137.

**Comment by BluSunrize** [comment]
Closing this because support for 1.16.5 has ended
