### ISSUE TITLE
[1.17.1] Client Crash on firing revolver

### ISSUE THREAD

**Issue by Sheenus** [BluSunrize/ImmersiveEngineering#4964]
### Description of the issue:
Attempted to fire revolver using casull cartridges, and upon doing so the client session crashed.

### Crashlog:
[crash-2021-09-10_00.06.38-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/7137263/crash-2021-09-10_00.06.38-client.txt)

### Versions & Modlist
Minecraft 1.17.1
Forge 37.0.53
MixinBootstrap-1.1.0
ImmersiveEngineering-1.17.1-5.0.2-pre.145
jei-1.17.1-8.0.0.14
journeymap-1.17.1-5.7.3rc3

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/0046f69c2d33e03f347b70f423a1c957557c7dc5
