### ISSUE TITLE
[1.17.1] Incorrect display for loaded revolver GUI

### ISSUE THREAD

**Issue by Sheenus** [BluSunrize/ImmersiveEngineering#4965]
### Description of the issue:
a loaded revolver does not display any ammunition in it's regular GUI, when held and loaded.
![2021-09-10_20 36 53](https://user-images.githubusercontent.com/2409029/132842037-b95bf485-0f60-4b76-9288-3d02c1b48a5d.png)
![2021-09-10_20 36 50](https://user-images.githubusercontent.com/2409029/132842042-9b82b088-d628-4d71-b1e5-20125833c2d4.png)

### Crashlog:
This issue did not generate a crash report.

### Versions & Modlist
Minecraft 1.17.1
Forge 37.0.53
_MixinBootstrap-1.1.0
ImmersiveEngineering-1.17.1-5.0.2-pre.153
jei-1.17.1-8.0.0.14
journeymap-1.17.1-5.7.3rc3

**Comment by Sheenus** [comment]
Related: buff/debuff GUI display somewhat incorrectly when the revolver is held, both in main hand and off-hand.

![2021-09-12_18 21 30](https://user-images.githubusercontent.com/2409029/133027683-1a4380ee-29c7-47ec-80a2-3de4e5217e4d.png)
![2021-09-12_18 21 34](https://user-images.githubusercontent.com/2409029/133027721-0bfc8e3d-8c9b-444e-b921-9aa6d0c3a089.png)
![2021-09-12_18 21 42](https://user-images.githubusercontent.com/2409029/133027728-8ed9d82f-427a-40f6-9d15-493224400d51.png)

Wasn't sure if I should create a seperate issue for it, but can if necessary.

**Comment by lordi-erez** [comment]
thats also in 1.16

**Comment by BluSunrize** [comment]
Please file a separate, detailed report for 1.16 issues

**Comment by malte0811** [comment]
Fixed by https://github.com/BluSunrize/ImmersiveEngineering/commit/b708b820d0321ad92492c890b29a81a6412d2626
