### ISSUE TITLE
Can't open book, it said to bring my logs here, so I brought them here

### ISSUE THREAD

**Issue by MrTubzy456** [BluSunrize/ImmersiveEngineering#4966]
I tried opening my immersive engineering book and something failed to load and it asked to bring my logs here. So here I am with my logs: https://mega.nz/file/w1lkXYoB#6ZUgWIBEUiUNv1z7oPrUaVFVC5U98yBwkYUFOAqQRQ8

I'm going to post on the immersive petroleum issues git because they're mentioned in the logs as well.

**Comment by BluSunrize** [comment]
Update Immersive Posts, the issue is on their end.
