### ISSUE TITLE
[1.16.5] breaking bottling machine looses pump

### ISSUE THREAD

**Issue by MatthiasMann** [BluSunrize/ImmersiveEngineering#4967]
### Description of the issue:
When I break the bottling / filling machine the pump is lost - the space where it was is just empty. I did use a pick axe on one of the outer conveyor belts (I think the right one when standing in front) to break the machine after it was assembled.

### Versions & Modlist
forge-1.16.5-36.2.2
ImmersiveEngineering-1.16.5-5.0.3-138
ImmersivePetroleum-1.16.5-3.3.0-6

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/52f77db6849677c0cb6ab224d33839389e8dda64 fixes this on 1.17.1, the fix will be backported in the next 1.16.5 build.
