### ISSUE TITLE
Issue with Fluid Tank

### ISSUE THREAD

**Issue by MehVahdJukaar** [BluSunrize/ImmersiveEngineering#4968]
So I've noticed that `MultiblockPartTileEntity.drain ` function updates the master block even when it's given a FluidAction.SIMULATE, which it shouldn't do since no content would have changed then. This causes issues for blocks that react to block updates and assume that said drain function wouldn't affect the fluid tank state. I've come across this issue after investigating https://github.com/MehVahdJukaar/Supplementaries/issues/99.
I didn't make a PR because I wasn't exactly sure if this was indeed the case but if it is I think it's just a matter to change a single line in that function to  `this.multiblock.updateMasterBlock((BlockState)null, doDrain != FluidAction.SIMULATE);`

**Comment by BluSunrize** [comment]
Fixed by commits above
