### ISSUE TITLE
[1.17.1] Client crash when rendering the chemical turret

### ISSUE THREAD

**Issue by devBob027** [BluSunrize/ImmersiveEngineering#4969]
The error is: java.lang.IllegalStateException: Not filled all elements of the vertex. It happened the second i placed the chemical turret, before i could see it. Only texturepack i was using was the built in programmer art texturepack

Here is the crash report download from [dropbox](https://www.dropbox.com/s/hrengqqbb6es9k5/crash-2021-09-12_00.12.00-client.txt?dl=0)

**Comment by malte0811** [comment]
Fixed in https://github.com/BluSunrize/ImmersiveEngineering/commit/cdd8676002fa0ae22069a1b0dc18790cfe0f0ee7. For future issues I'd prefer https://gist.github.com or https://pastebin.com (or some other dedicated paste site) over dropbox.
