### ISSUE TITLE
[1.17.1 | #15] Engineer's Hammer does not get consumed when crafting Mineral Survey Tools

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#4971]
as title.
Instead of being consumed, the hammer is damaged.
The texture of the item suggests that the Engineer's Hammer is part of the tools and should be consumed and note returned by the crafting recipe.
Probably caused by container item mechanics used for crafting metal plates and ore dust.

**Edit:
An analogous issue exists for the Maintenance Kit and Wire Cutters**

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/c594ef91a46ca4d317a42a0df1881f20f95e74b7
