### ISSUE TITLE
[1.17.1] covered vertical conveyors don't have solid enclosure

### ISSUE THREAD

**Issue by Sheenus** [BluSunrize/ImmersiveEngineering#4973]
### Description of the issue:
Unlike their counterparts, the covered vertical conveyor belts don't have a solid enclosure.

![2021-09-17_19 14 13](https://user-images.githubusercontent.com/2409029/133768231-874b1daf-3420-4a3e-973b-d98e443a90ae.png)

![VerticalConveyorBug](https://user-images.githubusercontent.com/2409029/133759530-7da5c1ec-d57c-497b-b524-8e6e93562848.gif)

### Crashlog:
This issue does not generate a crash log.

### Versions & Modlist
Minecraft 1.17.1
Forge 37.0.59
ImmersiveEngineering-1.17.1-5.0.2-pre.165
jei-1.17.1-8.0.0.14
journeymap-1.17.1-5.7.3rc3

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/e1b194dd9b24c538cae792faae1ee586a5395b65
