### ISSUE TITLE
[1.17.1] harvesting covered conveyers drops uncovered conveyers

### ISSUE THREAD

**Issue by Sheenus** [BluSunrize/ImmersiveEngineering#4974]
### Description of the issue:
What it says on the tin: harvesting any sort of covered conveyor block drops the uncovered version.

### Crashlog:
This issue does not generate a crash log.

### Versions & Modlist
Minecraft 1.17.1
Forge 37.0.59
ImmersiveEngineering-1.17.1-5.0.2-pre.165
jei-1.17.1-8.0.0.14
journeymap-1.17.1-5.7.3rc3

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/8a5a34e7ce11ada4f39fedb4f8e1c8276cd9b679
