### ISSUE TITLE
Bottling Machine does not fill bottles with water/purified water [1.12.2]

### ISSUE THREAD

**Issue by Finnyboi26** [BluSunrize/ImmersiveEngineering#4978]
So I am playing on 1.12.2 with version 0.12-98 

Me and my friends try to use the bottling machine but it just doesn't work when trying to fill empty bottles with water or other liquids! We tried buckets and it seems to work properly with no issue, but with empty bottles it just does the animation but leaves the bottle empty. It doesn't drain any water from the tank either so I'm sure this isn't an animation or rendering issue. At first I thought it was incompatible with the "Tough as Nails" mod, hence it not being able to bottle purified water, but it's the same thing for vanilla water! Is there a way to fix this?

**Comment by BluSunrize** [comment]
Support for 1.12 ended well over a year ago.

**Comment by mindforger** [comment]
If i remember right, some other mod modifying bottles may break the bottling machine, but you can „probably“ workaround using craft/modtweaker modifying the machine recipes
