### ISSUE TITLE
[1.17.1 | #17] Cloche redstone/redstone wire client performance lag

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#4979]
Sadly, I can't claim that I have a good idea of what's going on, but:

If you have a bunch of Cloches nearby, continuously toggling redstone circuits creates very noticable lag in the client. this is also noticably worse when such a toggling signal is sent over wire
also, it drags down FPS below monitor refreshrate when VSync is on, even when the FPS without VSync is considerably higher
(in this instance drop from ~600fps to ~350fps turned into from ~165 to ~90)*
*: this included toggling signal going through redstone wire

The performance lag/drop goes much less unfelt when you don't look at the cloches while the redstone toggle stuff happens.
As I said, I can't claim that I have a good idea of what's going on, maybe it's just a case of "pc weak" (and graphics card aside, I do have a very modern system these days). But the drop from "basically no performance impact" even with all the cloches present to "rubberbanding simulator" from just a single redstone circuit is suspicious to me.

to recreate:
Place down a good bunch of cloches, 6x6 was enough for me, then do a good old self toggling repeater loop. Repeaters on max delay, no need to get fancy. Then behold the performance drop.

![grafik](https://user-images.githubusercontent.com/7753414/133994408-5606dfc4-ce2a-44aa-ac48-13fac6d4eb9d.png)

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/49e49b94c8c262b0649e374708fec1a451ebbba4
