### ISSUE TITLE
[Suggestion] Industrial Fan

### ISSUE THREAD

**Issue by VermillionX** [BluSunrize/ImmersiveEngineering#498]
Should be a simple machine suggestion: A fan. Its purpose? To move entities similar to the Thaumcraft Arcane Levitator.
Placed like a wooden log and rotatable (so it can be placed sideways) with the Engineer's Hammer; Turns off if a redstone signal is applied; Consumes say... 5 RF/t and can transfer power to adjacent fans. The upper side pushes a player/mob/item 8 meters, while the under side pulls any entity within 4 meters. Items can pass through the fan and be propelled out the other side, allowing items to be dropped onto/pulled off a conveyor belt and transferred vertically (if you care to spend the power). Mobs/players simply bump into the fan and cannot pass through, nor take damage.
Useful for propelling players up onto roofs, parkour, security systems, up to skyhookable cables, etc...

Example:
![2015-10-12_14 37 57](https://cloud.githubusercontent.com/assets/10645298/10420481/98561de6-70f1-11e5-97c1-41c1b60da6c0.png)

**Comment by mindforger** [comment]
now the last thing that is missing is a larger version 3x3 with rotating blades, a version with grate where you can stand on but still see the rotor and a version without, that hurts you when standing "inside" :) this would make an awesome look for facilities

**Comment by BluSunrize** [comment]
Sounds interesting, I'll talk to hazard about it ^^

**Comment by mindforger** [comment]
okay additional thoughts therefor:

unpowered, no Redstone Signal = rotating
powered, no Redstone Signal = blower mode (moves items, bouncy effect when jumped on or whatever Vermillion noticed :D )
Redstone Signal on = shutdown

can be 1x1 with power connector placed at the middle
or 3x3 with power connected on any edge or the middle

both either horizontal or vertical

**Comment by kane-thornwyrd** [comment]
Would be an alternative to Rotarycraft's one, in the style of Immersive Engineering: that can't be bad ! :D

**Comment by cobra** [comment]
I like it. The strength (range, acceleration) could be somewhat proportional to the size of the multiblock if built as such (2x2, 3x3, maybe even 4x4… or 9x9 - go big or go^Wget blown home)

I suggest "blows your mind… and everything else away" as a slogan.

**Comment by VermillionX** [comment]
9x9... I'm seeing SHIELD Helicarriers and Airships everywhere.
Hmm... For each size it goes up, power consumption doubles (5, 10, 20, 40, 80 RF/t), as does the range (8m, 16, 32, 64, 128, etc). You probably wouldn't need to go above 5x5 to get from the ground to say... an airship/floating city.

**Comment by PrincessRTFM** [comment]
Might want to clamp the range when it's pushing horizontally, so you don't get blown across half a dozen chunks, but otherwise, I like this idea!
