### ISSUE TITLE
[1.16.5] Is there any way of checking to see what temperature any fluid or block has? 

### ISSUE THREAD

**Issue by GekiroPlays** [BluSunrize/ImmersiveEngineering#4982]
I am trying to work out how the Thermoelectric Generator works and struggle to find any certain values for fluids/blocks in general apart from those listed in the immersive engineering book which are very limited

**Comment by BluSunrize** [comment]
Fluids we can't easily list (because there is a theoretically infinite number) and any of the solid blocks we support are already listed!
