### ISSUE TITLE
[1.17.1 | #17] Feedthrough Connector bounding box is on the wrong side in the block

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#4984]
Includes collision, walking on the regular connector leaves you lower than on the feedthrough one
![grafik](https://user-images.githubusercontent.com/7753414/134568089-df0278f2-2abd-4f12-bacc-1e7a8ef685d7.png)

PS: I still think these should use relays ;P

**Comment by BluSunrize** [comment]
Wouldn't be much of a feedthrough *connector* if it used *relays*.

Also, relays can't in/output. Connectors are used because they transfer power through the block they are attached to (flavor wise)

**Comment by MalkContent** [comment]
well it would be a feedthrough relay then, wouldn't it :D
imo they work like relays, which is why I think that. I will never truly let this go but I respect the decision enough to only nag about it every ~9 months or so ^^

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/10a1c1fdb08fe8a711a88928eae9b265afd2c468
