### ISSUE TITLE
[1.17.1 | #21] Redstone Connector can't directly drive Comparator main input

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#4985]
The Redstone Connector CAN drive the Repeater input and the Comparator side inputs, so it falls out of the pattern.
If anything the Comparator side inputs should be the ones that don't take in a signal from the redstone connector directly, seeing how they also don't take in a signal from powered blocks or powering blocks, besides Repeaters/Comparators
![grafik](https://user-images.githubusercontent.com/7753414/134724439-1cf0a953-71a0-463d-9468-f4f5785904e8.png)

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/f25f79be55e1a9cbc77e92590a6dc258b5b83f3d
