### ISSUE TITLE
[1.17.1 | #21] Arc furnace client crash

### ISSUE THREAD

**Issue by JStocke12** [BluSunrize/ImmersiveEngineering#4988]
**Description:**
The game crashes when the arc furnace finishes a process.

**Crashlog:**
[crash-2021-09-24_17.18.53-client.txt](https://gist.github.com/JStocke12/39c443e63a8866013b7f9c252854a407)

**Versions & Modlist:**
Minecraft 1.17.1
Forge 37.0.59
ImmersiveEngineering-1.17.1-5.0.2-pre.172
jei-1.17.1-8.0.0.16

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/f22b198ffbd4c40ea54744c424a76f23b014e44c
