### ISSUE TITLE
HV transformer graphical glitches

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#499]
Pictures shows the glitches
![image](https://cloud.githubusercontent.com/assets/3110986/10420496/1c8a2b46-704a-11e5-9107-9f6958f4371c.png)
![image](https://cloud.githubusercontent.com/assets/3110986/10420505/3563904e-704a-11e5-9d56-b24b30381041.png)
Edit... found another.
HV transformer -> transformer do not render regardless of connection type or elevation
![image](https://cloud.githubusercontent.com/assets/3110986/10420523/bc8ea6ee-704a-11e5-84d1-653d64ba052c.png)

IE build 660c444

**Comment by cobra** [comment]
Looks like the transformer's `limitType` and `secondCable` fields are always null, thus breaking the whole code depending on them o.O

**Comment by BluSunrize** [comment]
are you doing this via PR @cobra? If so I'll leave it to you.

**Comment by cobra** [comment]
Yep, I'm at it. Looks like I found not one, but two or three separate issues.

**Comment by cobra** [comment]
After lots and lots of testing and trying to break transformer-related stuff in all ways I could imagine, I think there aren't any bugs left now.
In the end it was one misplaced curly brace leaving the `limitType` and `secondCable` fields as null and breaking everything depending on these. Breaking and replacing any "glitched" transformers in the world with the patch active might be needed, but I don't think this will affect too many instances (my guess: 1).
The second problem was that transformers didn't trigger wire rendering on their own.
Pushing and PR'ing the fixes now.

**Comment by BluSunrize** [comment]
\o/

**Comment by cobra** [comment]
There you go. Had to rebase a little after committing to the wrong branch m)
