### ISSUE TITLE
[1.17.1 | #21] Redstone Probe Connector does not detect tank contents in multiplayer

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#4992]
as title
It's a weird issue, because it works in single player. I've been having some weird issues around my setup anyways (diesel disappearing, pump not pumping), so it might be related to that. Other than the other weird issues, this one doesn't seem to fix itself, though, at least thus far.
This was crosschecked (though not super thoroughly) by another player on the beta server.
If this can't be replicated easily, then I'll try and dig deeper, but for now I can't think of any specific reason.

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/8e2478910360302f1d0de1b7d4d3bdf142cc8303
