### ISSUE TITLE
[1.17.1 | #21] Strip Curtain not updating Redstone signals correctly

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#4995]
Number 1 and 2 seemingly ONLY affects the Strong Redstone Signal. For these Weak Signal appears to work fine, even with the Strong Signal enabled.

Number 3 affects both settings.

1: only powers Redstone on block it is placed against correctly
![grafik](https://user-images.githubusercontent.com/7753414/134932053-6ac9601a-c485-410d-a2aa-854896a1bf95.png)
![grafik](https://user-images.githubusercontent.com/7753414/134932878-24807322-e659-4829-a519-86d4a75a02d7.png)

2: will power blocks on the side if they receive block updates(?) in this instance the outer redstone of the left side was broken and replaced
![grafik](https://user-images.githubusercontent.com/7753414/134933409-ce27ec5d-d8aa-44f3-9ec8-5848e1b34738.png)

3: Does not correctly (de-)power after dis-/enabling Redstone Signal while detecting (no pictures for Weak Signal, but same story)
![grafik](https://user-images.githubusercontent.com/7753414/134932510-bab3cb15-d135-4e16-a9c2-aac0f2c84cda.png)
![grafik](https://user-images.githubusercontent.com/7753414/134933970-d03e7570-dab5-4262-8908-cd87b3d513ac.png)

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/5efa14cb1f271e04ecec74bf886117c2d3a42225
