### ISSUE TITLE
[1.17.1 | #21] Assembler building instructions animation in Manual bugged

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#4996]
The animation of the building instruction "stops" at the displayed frame. It kind of keeps building and goes through all the blocks and cycles successfully, but all it seems to add is more shadow before it cycles.
![grafik](https://user-images.githubusercontent.com/7753414/134939449-929f1960-8ef9-446a-8b8d-4cdfb9f4595c.png)

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/e5d35e65a3de22b1f32ce7cf5778661436b9ac27
