### ISSUE TITLE
[1.12.2]There is a problem about filling liquid medicine with Bottling Machine

### ISSUE THREAD

**Issue by cpcwansui** [BluSunrize/ImmersiveEngineering#4998]
Description of the issue:
    Four empty bottles are input and the chest receives the products. Then take the potions out of the chest, then there are four slots in the inventory of a bottle of potion. Close the chest and there are four bottles left in the inventory. But when I press E, all I see is a potion, and all the other potions disappear.
    After that, the Bottling Machine can't fill the liquid. Input the empty bottle to produce the empty bottle, and consume 250mB of liquid.
    At present, in my tests, I have found that this problem only occurs when the chest receives the potion.

Versions & Modlist:
- Minecraft 1.12.2
- Forge 14.23.5.2855
- OptiFine_G5-natives
-  jei_1.12.2-4.16.1.301
- ImmersiveEngineering-0.12-98

Vedio:
[Minecraft 1.12.2 .zip](https://github.com/BluSunrize/ImmersiveEngineering/files/7240805/Minecraft.1.12.2.zip)

**Comment by BluSunrize** [comment]
Support for 1.12 was ended well over a year ago.

**Comment by cpcwansui** [comment]
Ok
