### ISSUE TITLE
[1.10.2] Missing texture - Creosote Oil (low priority)

### ISSUE THREAD

**Issue by SrHusky** [BluSunrize/ImmersiveEngineering#4999]
Forge version: **12.18.3.2511**
ImmersiveEngineering version: **0.10-61**

Client log:

IE CokeOven Interface
![Screenshot_21](https://user-images.githubusercontent.com/14131357/135031159-426b0d11-9c8d-48c1-bd4a-6980f958141b.png)

also is happening with buckets and Forestry/IC² cells

![Screenshot_22](https://user-images.githubusercontent.com/14131357/135034142-827e1f01-5ae9-4219-a585-1e52ec514e47.png)

![Screenshot_23](https://user-images.githubusercontent.com/14131357/135034170-a0eb6588-3d2b-42cc-8e92-37a1023af3b8.png)

![Screenshot_24](https://user-images.githubusercontent.com/14131357/135034191-45634490-91e6-4b80-8ffe-537b3d6c34fb.png)

I do not know if this error is happening by IE fault, but if it won't, would you guys know how fixing that? I will be pleasure with your help 

Comments: The texture of IE creosote block isn't missing.

![Screenshot_25](https://user-images.githubusercontent.com/14131357/135035146-b9fd1bbb-05bf-439b-a494-47a6033b59cb.png)

Client log without EnderIO: https://paste.ee/p/1qia0

**Comment by SrHusky** [comment]
I think that is occurring by EnderIO fault, https://github.com/Railcraft/Railcraft/issues/1799

**Comment by BluSunrize** [comment]
1.10 has not been updated for years.
