### ISSUE TITLE
Crash Creating Diesel Generator on SMP

### ISSUE THREAD

**Issue by Towsty** [BluSunrize/ImmersiveEngineering#5]
Server Crashed when right-clicking the diesel generator with the Engineer's wrench. Client remained open and this error does not seem to exist on the client.

Crash Report:
https://gist.github.com/Towsty/730204b1666ecae754dd#file-iedieselgencrash

Log
https://gist.github.com/Towsty/7989e4cf4c9c87dd5ea1#file-iedieselgencrashlog

**Comment by BluSunrize** [comment]
Known and fixed with next build
