### ISSUE TITLE
Book issue

### ISSUE THREAD

**Issue by DoughnutDev** [BluSunrize/ImmersiveEngineering#50]
http://puu.sh/idETl/43d41814f3.png - When looking at Item Router it cycles through two recipes and the second one is just error texture. This might be a work in progress so sorry if I am bugging you about it.

**Comment by BluSunrize** [comment]
and what are the items called that it's trying to render? If you hover your mouse over them, it should show a tooltip.

**Comment by DoughnutDev** [comment]
So the book issue has to do with Rekias mod it is making it Nether Redstone and Nether Iron and it cycles through it because they are both the same name in the oredict
