### ISSUE TITLE
[Probably Fixed beyond 0.5.4] Diesel Generator Redstone Port does not Mirror

### ISSUE THREAD

**Issue by mindforger** [BluSunrize/ImmersiveEngineering#500]
i just read the latest commit and remembered we had an issue on the server where you can not place an lever on the mirrored redstone port, but the redstone behaviour is working fine, also framed red alloy wire is connecting fine, only the block hardness or whatever is not mirroring over, the lever stucks on the other side but does not work anymore

i also remember in one commit something about something regarding the block hardness but github won't let me search the commits -.-

**Comment by cobra** [comment]
already fixed: #439

**Comment by mindforger** [comment]
what the heck ??? github search is bugging me -.- sorry
