### ISSUE TITLE
[Minor][1.17.1 | #24] Logic Unit does not instantly update visually when adding/removing Logic Circuits

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#5004]
When adding/removing Logic Circuits via the GUI, the logic unit does not update visually.
It does update eventually, but seemingly this has to happen by block update. I'm unsure about it.

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/f5daf58e5bdc3e56cdcac7c9a154d62fac00ccdf
