### ISSUE TITLE
[1.17.1 | #24] Changing Logic Circuits in a does not update the Logic Unit's outputs

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#5005]
Adding or removing Logic Circuits does not immediately affect the Logic Unit's outputs. Other than the visual issue in #5004 this does not appear to self correct on block update.

The Logic Unit's outputs only seem to change when a change of input in a Redstone Interface Connector occurs. It does not seem to matter which Redstone Interface Connector or which color, even if the color does not play a part in any Logic Circuit.

Additionally, removing all Logic Circuits also does not update the outputs. BUT in this case changing inputs into the Logic Unit does not update the Logic Unit sending obsolete signals.

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/f5daf58e5bdc3e56cdcac7c9a154d62fac00ccdf
