### ISSUE TITLE
Garden Cloche lagging game tps A LOT

### ISSUE THREAD

**Issue by NuggetBoio** [BluSunrize/ImmersiveEngineering#5006]
I have been playing sky factory 3 for some time now and I have been using the garden cloche for my mystical agriculture farming. But, I have so many garden cloches that the animation from the plants growing is lagging out my game a lot (My fps doesn't drop at all its the game itself not being able to keep up with all the animations) so I was wondering if there could be an option added so that I can disable those animations? That would be very helpful. Thank you!

**Comment by BluSunrize** [comment]
No, they can't be disabled.

And SkyFactory 3 is running a severely outdated version of Minecraft that we have dropped support for long ago.

**Comment by NuggetBoio** [comment]
Oh, that's too bad. Well, thank you anyways.
