### ISSUE TITLE
[1.16.5] Immersive Engineering machines and devices that work with redstone don't respond to signals from Project Red wires.

### ISSUE THREAD

**Issue by dan96kid** [BluSunrize/ImmersiveEngineering#5008]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
Immersive Engineering things that can be controlled with a redstone signal, such as the external heater and redstone breaker, don't seem to work properly with signals from Project Red's wires. As Project Red wires carry redstone signals, I expect them to work with anything in Immersive Engineering that is controllable with redstone.
What's happening is that when a red allow wire on or directly next to a redstone controllable thing from Immersive Engineering switches to either a powered or unpowered state, the Immersive Engineering thing does not update to reflect the change, such as a redstone breaker not switching off when the red alloy wire pointed at it is powered.

Image demonstrating this bug:
![image](https://user-images.githubusercontent.com/14021093/136061861-389d7333-e921-4ad2-9ff8-3bb3fedcc90b.png)
What's happening in the image is that the External Heater is still on despite the Project Red wire not being powered and there being no items in the furnace.
As per intended IE behavior, the External Heater will normally only turn on when a smeltable item is put into the furnace, but can be forced to turn on with a redstone signal.
This behavior is broken when using red alloy wires from Project Red. As seen in the image, the red alloy wire is unpowered, but the External Heater is still on. Strangely enough, triggering a block update by say, placing or removing something next to the External Heater, causes it to turn off.
The same problem arises when trying to turn on the External Heater, as seen in the following image:
![image](https://user-images.githubusercontent.com/14021093/136064061-faac53c2-5992-4b58-a4b7-6d6f43b6acc6.png)

The following images show how the External Heater is supposed to work when using redstone:
![image](https://user-images.githubusercontent.com/14021093/136064578-78d477c8-212e-4a9a-b4c4-5a8cfe350f7a.png)
![image](https://user-images.githubusercontent.com/14021093/136064612-40f72e5d-a2d4-4821-b170-74c808e9e37c.png)

I tested this in a Minecraft 1.16.5 instance with only Immersive Engineering and Project Red installed and can confirm that this is not a modpack-specific issue... I think. The first time I performed this test this bug did not occur. I did a total of 4 tests using two different launchers.
The first test was done with Multimc and All The Mods 6 version 1.8.3. I cloned the modpack instance and stripped everything except Immersive Engineering, Project Red, and JEI out. This is the only test where this bug did not occur.
The second and third tests were done on GDLauncher and with All The Mods version 1.8.5. The first of those two tests involved me cloning the modpack instance and stripping out everything except Immersive Engineering, Project Red, and JEI. The second one involved creating a new instance from scratch and installing Forge version 36.2.8, Immersive Engineering version 1.16.5-5.0.3-138, Project Red version 1.16.5-4.10.0, and JEI version 1.16.5-7.7.1.122. Two runs of this test was done: One with JEI enabled, and one with JEI disabled.
The fourth and final test was a repeat of the first test, and was done to see if repeating it would have the same result as the last time.

### Versions & Modlist
IE Versions affected:
1.16.5-5.0.3-138
1.16.5-5.0.4-139

Forge Version: 36.2.6

Modpack is All The Mods 6 version 1.8.5
Modlist:
XP Tome(bl4ckscor3)
Chocolate Fix(AlcatrazEscapee)
Configurable Extra Mob Drops (Forge)(Serilum)
Curious Elytra (Forge)(TheIllusiveC4)
Akashic Tome(Vazkii)
Global XP(bl4ckscor3)
Simple Magnets(SuperMartijn642)
Iron Jetpacks(BlakeBr0)
Ensorcellation(TeamCoFH)
DimStorage(3divad99)
Mekanism Tools(bradyaidanc)
ShetiPhianCore(ShetiPhian)
SuperMartijn642's Core Lib(SuperMartijn642)
Fast Furnace minus Replacement(tfarecnim)
Farming for Blockheads(BlayTheNinth)
Inventory Tweaks Renewed(David1544)
Overloaded Armor Bar(tfarecnim)
Extra Disks(MelanX)
Caelus API (Forge)(TheIllusiveC4)
TrashSlot(BlayTheNinth)
Ding(ohaiiChun)
Nature's Compass(Chaosyr)
Integrated NBT(scleox)
Mystical Customization(BlakeBr0)
YUNG's Better Mineshafts (Forge)(YUNGNICKYOUNG)
AttributeFix(DarkhaxDev)
Bag of Yurting(Commoble)
Compact Machines(davenonymous)
Mana Gear(Partonetrain)
Trash Cans(SuperMartijn642)
Mekanism Generators(bradyaidanc)
Babel(thenatekirby)
Wither Skeleton Tweaks(Shadows_of_Fire)
Cosmetic Armor Reworked(LainMI)
Thermal Innovation(TeamCoFH)
Mining Gadgets(Direwolf20)
Macaw's Bridges(sketch_macaw)
Water Strainer(Ruuubi)
Portality(Buuz135)
Dank Storage(tfarecnim)
ATO - All the Ores(ATMTeam)
Solar Flux Reborn(Zeitheron)
The Mighty Architect(simibubi)
Storage Drawers(Texelsaur)
U Team Core(HyCraftHD)
Toast Control(Shadows_of_Fire)
McJtyLib(McJty)
Shutup Experimental Settings!(Corgi_Taco)
Balanced Enchanting(tfarecnim)
GunpowderLib(Jackyy)
OpenBlocks Elevator(vsngarcia)
Compact Crafting(RobotGryphon)
RFTools Control(McJty)
Fast Leaf Decay(olafskiii)
Woot(Ipsis)
Useful Railroads(HyCraftHD)
Scuba Gear(ModdingLegacy)
Restrictions(McJty)
AppleSkin(squeek502)
Integrated Crafting(kroeser)
Macaw's Doors(sketch_macaw)
LibX(noeppinoeppi)
Macaw's Trapdoors(sketch_macaw)
Light Overlay (Rift/Forge/Fabric)(shedaniel)
TOP Addons(DrManganese)
Building Gadgets(Direwolf20)
Potions Master(thevortexFoxTopia)
/tank/null(tfarecnim)
Eidolon(elucent_)
CleanCut(Rongmario)
Platforms(ShetiPhian)
Just Enough Piglin Bartering(thenatekirby)
Crafting Tweaks(BlayTheNinth)
Item Filters (Forge)(LatvianModder)
RFTools Storage(McJty)
JEI Professions(pau101)
YUNG's API (Forge)(YUNGNICKYOUNG)
NoMoWanderer(TheJDill)
FastWorkbench(Shadows_of_Fire)
Angel Ring(DenisMasterHerobrine)
Ropes Mod!(TheGoldCrayon)
Spawner Bug Fix(MacTso)
Iron Chests(ProgWML6)
Tool Belt(gigaherz)
Curio of Undying (Forge)(TheIllusiveC4)
Construction Wand(ThetaDev)
Starter Kit (Forge)(Serilum)
Useful Backpacks(HyCraftHD)
Drawers Tooltip(Snownee_)
Mekanism Additions(bradyaidanc)
Dark Utilities(DarkhaxDev)
Macaw's Roofs(sketch_macaw)
The One Probe(McJty)
Entangled(SuperMartijn642)
Dynamic View(someaddon)
Shrink.(GigaBit101)
Pam's HarvestCraft 2 - Food Core(pamharvestcraft)
Pam's HarvestCraft 2 - Crops(pamharvestcraft)
Phosphophyllite(RogueLogix)
Pedestals(Mowmaster)
Cat Jammies(Buuz135)
Mod Name Tooltip(mezz)
Morph-o-Tool(Vazkii)
Refined Storage Addons(raoulvdberge)
FTB Ultimine (Forge)(FTB)
Creative Wireless Transmitter(UItramega)
Engineer's Decor(wilechaote)
Crash Utilities(Darkere)
Lollipop(owmii)
Runelic(DarkhaxDev)
Glassential(Lykrast)
Oh My Gourd(TeamCoFH)
ObserverLib(HellFirePvP)
Default Options(BlayTheNinth)
FlickerFix(MutantGumdrop)
Thermal Cultivation(TeamCoFH)
No Villager Death Messages(MutantGumdrop)
FTB Backups (Forge)(FTB)
Demagnetize(comp500)
Client Tweaks(BlayTheNinth)
Travel Anchors(CastCrafter)
Polymorph (Forge)(TheIllusiveC4)
AutoRegLib(Vazkii)
EnderChests(ShetiPhian)
ConnectedTexturesMod(tterrag1098)
Ranged Pumps(raoulvdberge)
RFTools Base(McJty)
Better Advancements(way2muchnoise)
Cucumber Library(BlakeBr0)
NetherPortalFix(BlayTheNinth)
Save My Stronghold! (Forge)(YUNGNICKYOUNG)
Jumbo Furnace(Commoble)
Pam's HarvestCraft 2 - Trees(pamharvestcraft)
Psi(Vazkii)
Cartographer(thevortexFoxTopia)
Thermal Locomotion(TeamCoFH)
Archer's Paradox(TeamCoFH)
RandomPatches (Forge)(TheRandomLabs)
Culinary Construct(TheIllusiveC4)
Bigger Reactors(RogueLogix)
RFTools Power(McJty)
KubeJS Create(LatvianModder)
LazierAE2(DamnRelentless)
Windowlogging(mc_Grimmauld)
Sound Device Options(ichttt)
RSInfinityBooster(hexeptiondev)
Engineer's Tools(wilechaote)
Powah!(owmii)
XNet(McJty)
Bad Wither No Cookie - Reloaded(Kreezxil)
Absent by Design(Lothrazar)
SuperMartijn642's Config Lib(SuperMartijn642)
Spice of Life: Carrot Edition(lordcazsius)
EnderTanks(ShetiPhian)
Tinkers' Mechworks(mDiyo)
Mouse Tweaks(YaLTeR)
Upgrade Aquatic(TeamAbnormals)
Forbidden and Arcanus(cesar_zorak)
Connectivity(someaddon)
Torchmaster(xalcon)
Environmental Materials(ValkyrieofNight)
Compressium(DinnerBeef)
JEI Integration(SnowShock35)
Explorer's Compass(Chaosyr)
RFTools Builder(McJty)
ZYCraft(nikita488)
Gauges and Switches(wilechaote)
Dungeon Crawl(xiroc_)
ValkyrieLib(ValkyrieofNight)
Flat Bedrock(Sunekaer)
Lazy DataFixerUpper(LazyDFU) [FORGE](Corgi_Taco)
Refined Storage: Requestify(Buuz135)
Cloth Config API (Forge)(shedaniel)
Metal Barrels(tfarecnim)
Comforts (Forge)(TheIllusiveC4)
Exchangers(Jackyy)
Flux Networks(sonar_sonic)
Thermal Expansion(TeamCoFH)
Placebo(Shadows_of_Fire)
Enchantment Descriptions(DarkhaxDev)
XNet Gases(Terrails)
FerriteCore (Forge)(malte0811)
Additional Enchanted Miner(Kotori316)
More Minecarts and Rails(goldey3)
Framed Compacting Drawers(Eutropium)
Tome of Blood(ToxicMintTea)
AIOT Botania(MelanX)
Environmental Tech(ValkyrieofNight)
Waystones(BlayTheNinth)
Just Enough Resources (JER)(way2muchnoise)
ExtraStorage(3divad99)
Simply Light(Flanks255)
Modular Routers(desht_08)
KubeJS Thermal(LatvianModder)
Builders Crafts & Additions (Forge)(MRHminer)
Trample Stopper(UnRealDinnerbone)
Citadel(alex_khaan)
Mantle(mDiyo)
MrCrayfish's Furniture Mod(MrCrayfish)
In Control!(McJty)
ExpandAbility(florensie)
KubeJS Blood Magic(LatvianModder)
YUNG's Better Strongholds (Forge)(YUNGNICKYOUNG)
Cooking for Blockheads(BlayTheNinth)
Just Enough Items (JEI)(mezz)
Integrated Tunnels(kroeser)
Collective (Forge)(Serilum)
Creative Apiary(UItramega)
Mob Grinding Utils(vadis365)
Advanced Chimneys(EnderLanky)
RFTools Utility(McJty)
The Lost Cities(McJty)
Pam's HarvestCraft 2 - Food Extended(pamharvestcraft)
Apotheosis(Shadows_of_Fire)
FTB Essentials (Forge)(FTB)
spark(Iucko)
DataPack Anvil(Sirttas)
FramedBlocks(XFactHD)
Titanium(Buuz135)
Advanced Peripherals(srrendi)
Curios API (Forge)(TheIllusiveC4)
Refined Storage(raoulvdberge)
RFTools Dimensions(McJty)
Reliquary v1.3(P3pp3rF1y)
CC: Tweaked(SquidDev)
Botanical Machinery(MelanX)
Immersive Posts(TwistedGate)
AE2 Extras(tfarecnim)
CodeChicken Lib 1.8.+(covers1624)
FTB Ranks (Forge)(FTB)
Macaw's Windows(sketch_macaw)
Sophisticated Backpacks(P3pp3rF1y)
Brandon's Core(brandon3055)
Silent Lib (silentlib)(SilentChaos512)
Botany Trees(DarkhaxDev)
Aquaculture 2(Shadowclaimer)
Crafting Station(tfarecnim)
CoFH Core(TeamCoFH)
Immersive Petroleum(Flaxbeard)
KubeJS Mekanism(LatvianModder)
Abnormals Core(TeamAbnormals)
Centrifuge Tiers(UItramega)
Architectury API (Forge)(shedaniel)
Silent Gear(SilentChaos512)
Corail Woodcutter(Corail_31)
Thermal Foundation(TeamCoFH)
GeckoLib(ThanosGecko)
Industrial Foregoing(Buuz135)
Biomes O' Plenty(Forstride)
All The Tweaks(thevortexFoxTopia)
CB Multipart(covers1624)
Environmental Core(ValkyrieofNight)
Login Protection(someaddon)
Flywheel(jozufozu)
KubeJS Immersive Engineering(LatvianModder)
FTB Teams (Forge)(FTB)
Lighting Wand 🌟(Snownee_)
Chipped(grimbop)
Elemental Craft(Sirttas)
FTB Chunks (Forge)(FTB)
ForgeEndertech(EnderLanky)
Patchouli(Vazkii)
Scorge(illyohs)
Iron Furnaces [FORGE](XenoMustache)
Kotlin for Forge(thedarkcolour)
Project Red - Exploration(MrTJP)
Creative Crafter(UItramega)
Chisel(tterrag1098)
Mystical Agriculture(BlakeBr0)
Project Red - Core(MrTJP)
Project Red - Illumination(MrTJP)
Quark(Vazkii)
ATM: Additions(ATMTeam)
Corail Tombstone(Corail_31)
Small Ships(talhanation)
AllTheCompressed(Pdiddy973)
Mekanism(bradyaidanc)
FindMe(Buuz135)
TerraForged(won_ton_)
Tiny Redstone(Danny_and_Son)
Immersive Engineering(BluSunrize)
MythicBotany(noeppinoeppi)
Observable(tasgon)
Oh The Biomes You'll Go(AOCAWOL)
Tinkers Construct(mDiyo)
FTB Quests (Forge)(FTB)
Draconic Evolution(brandon3055)
Allthemodium(ATMTeam)
Create(simibubi)
Ars Nouveau(baileyholl2)
Bookshelf(DarkhaxDev)
Artifacts(ochotonida)
Cyclic(Lothrazar)
Extreme sound muffler (Forge)(LeoBeliik)
Common Capabilities(kroeser)
MmmMmmMmmMmm(MehVahdJukaar)
Integrated Terminals(kroeser)
Cyclops Core(kroeser)
Macaw's Fences and Walls(sketch_macaw)
PackMenu(Shadows_of_Fire)
Pipez(henkelmax)
Nature's Aura(Ellpeck)
YUNG's Better Dungeons (Forge)(YUNGNICKYOUNG)
Rhino(LatvianModder)
Cable Tiers(UItramega)
FTB Library (Forge)(FTB)
Valhelsia Core(ValhelsiaTeam)
Botania(Vazkii)
Repurposed Structures (Forge)(telepathicgrunt)
KubeJS (Forge)(LatvianModder)
Scalable Cat's Force(Kotori316)
Legendary Tooltips(Grend_G)
Mahou Tsukai(stepcros)
Iceberg(Grend_G)
PonderJS(kotakotik22)
PneumaticCraft: Repressurized(desht_08)
Perpetual Durability(TheLexxie)
Project Red - Transmission(MrTJP)
Create Crafts & Additions(MRHminer)
Equipment Compare(Grend_G)
Project Red - Integration(MrTJP)
Advancement Plaques(Grend_G)
Mystical Agradditions(BlakeBr0)
Pickle Tweaks(BlakeBr0)
Botany Pots(DarkhaxDev)
Applied Energistics 2 Wireless Terminals Forge(tfarecnim)
Selene Lib(MehVahdJukaar)
Mana and Artifice(AWildCanadianEh)
Structurize(H3lay)
Blood Magic (WayofTime)
Supplementaries(MehVahdJukaar)
Integrated Dynamics(kroeser)
Astral Sorcery(HellFirePvP)
The Twilight Forest(Benimatic)
Ice and Fire: Dragons(alex_khaan)
Clumps(Jaredlll08)
Applied Energistics 2(AlgorithmX2)
Lootr(Noobanidus)
Pylons(MutantGumdrop)
Controlling(Jaredlll08)
MineColonies(H3lay)
Resourceful Bees(epic_oreo)
Environmental Energy(ValkyrieofNight)

**Comment by BluSunrize** [comment]
Closing this because support for 1.16.5 has ended
