### ISSUE TITLE
Suggestion (if not a bug).

### ISSUE THREAD

**Issue by SGZ-Creations** [BluSunrize/ImmersiveEngineering#5009]
Hey. would it be possible to have some item-pipe connection to the alloy kiln since currently no pipe mod work on that behaviour.

MC: 1.16.5
mod pack in case: ATM6

**Comment by BluSunrize** [comment]
No, the Alloy Kiln not being automatable is an intentional design choice.

**Comment by SGZ-Creations** [comment]
Way may i ask since it is quit annoying. Being need to stay & watch it being done. to not get full or that it can't smelt more than 16 of any item. since it end up being multiplied. Tho is there possible to make it and option in some configs ??? Please

**Comment by BluSunrize** [comment]
No this is an intentional design choice, as I said.

The Arc Furnace can be automated. Making the alloy furnace slower and more manual is an incentive to progress through IE's architecture.

**Comment by SGZ-Creations** [comment]
Sorry to bother forgot about that last machine.
