### ISSUE TITLE
[1.17.1 | #31] Structural Arms Not Rendering Correctly

### ISSUE THREAD

**Issue by DeadlySwede** [BluSunrize/ImmersiveEngineering#5011]
### Description of the issue:
The "ramped" hit boxes on individual pieces of formed arms seem okay. Pieces always display as "unramped" single blocks with the pointed end facing south (flat end facing north). Applies to both existing blocks and newly placed blocks. Also appears to be an odd x-ray effect going on where pieces attach to other blocks. 

First noticed on multiplayer IE 1.17 test server. Duplicated in single player.

![2021-10-06_08 37 17](https://user-images.githubusercontent.com/2657769/136216432-ecf7280a-6473-4ba6-acaf-8febd27de19a.png)

![2021-10-06_08 37 19](https://user-images.githubusercontent.com/2657769/136216457-fc4dd3d5-e582-4a2f-825b-72a2cc11bc89.png)

### Crashlog:
None.

### Versions & Modlist
Minecraft 1.17.1
Forge 37.0.73
Immersive Engineering 1.17.1-5.0.2-pre.200 (Build 31)
Journeymap 5.7.3rc3
Just Enough Items 8.0.0.19

**Comment by DeadlySwede** [comment]
### Update: Steel Structural Arms

**Steel** structural arms are acting wonky **before** they are placed. Work fine when placed

![2021-10-07_19 57 12](https://user-images.githubusercontent.com/2657769/136482097-8e305d6e-c5df-4b8b-aa41-2c28796d681c.png)

![2021-10-07_19 57 47](https://user-images.githubusercontent.com/2657769/136482100-a9ad51b2-45d4-4220-972a-1ef2b4d16562.png)

![2021-10-07_19 58 10](https://user-images.githubusercontent.com/2657769/136482108-f6823791-05f7-441f-a8b5-c343b86f55da.png)
.

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/d0f5d295577520c6ec0e01724189d9a34cfec78e
