### ISSUE TITLE
[1.17.1 | #31] Outputting Redstone Connectors don't properly update the strong power sent into the block they're attached to

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#5012]
As title. The correct redstone value gets detected by blocks when they're placed against the connector-powered block, or when already attached blocks get prompted to update (by say, a neighboring block update)
This works for both powering and depowering

This is also related to the cloche issue from the server-discussion channel

to recreate, create structure  shown in picture, flip the lever as last course of action. The piston powered through the Grass block can be forced to update i.e. by placing a block next to it

![grafik](https://user-images.githubusercontent.com/7753414/136215883-9eaac826-7c9d-49e3-a258-226882bf756c.png)

**Comment by MalkContent** [comment]
Update:
This bug was introduced in build # 24
The same setup still works without issue in build # 23

Edit:
specifically this line change:
[extra special link because stupid # parses](https://github.com/BluSunrize/ImmersiveEngineering/compare/398fe1d7ae75...f25f79be55e1#diff-e43696fc16d84148368dff24fc658ca44328267ff660e43287a61888a1a126e2L121-R121)

**Comment by malte0811** [comment]
f960c3e5ff545f249ab44342e4b7b46991e0bf31
