### ISSUE TITLE
[Visual only][1.17.1 | #31] Plants inside cloche invisible under certain angles/conditions

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#5013]
as title

regular display:
![grafik](https://user-images.githubusercontent.com/7753414/136217461-8db4afe4-0a66-4d4a-814b-34ebc8942b38.png)

when looking down a bit:
![grafik](https://user-images.githubusercontent.com/7753414/136217557-7676ae68-b8cc-4111-9e4d-d91ddd88cfe0.png)

also, when hitting F1, for some reason (would still display correctly without F1 under this angle):
![grafik](https://user-images.githubusercontent.com/7753414/136217897-2e302868-ad86-4a21-8515-a99c991e5e99.png)

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/6c129e715dc29d2561081ac67ecff0ffe54ad7f8
