### ISSUE TITLE
[Minor][1.17.1 | #31] Chutes open side to sloped conveyors

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#5015]
Chuts open to conveyors that are leading at them, even when they are sloped.
Idk how reasonable it is to make a case for opening chutes for sloped conveyors that come from one block below, but it'd be a related issue, I guess.

![grafik](https://user-images.githubusercontent.com/7753414/136352885-fab0fc32-cb25-418a-86bc-6e310c94274c.png)

(in case you are wondering why there's a chute there, and if I'm just building bs to break the game now: The conveyor above it was replaced by a dropping conveyor and the thing leads into a cactus, for disposal of excess hemp fiber)

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/33902c4b535c341bf0ad3a9aff24658156e57604
