### ISSUE TITLE
Sloped Conveyors not dyeing properly

### ISSUE THREAD

**Issue by MyNameIsKodos** [BluSunrize/ImmersiveEngineering#5017]
At the request of Malte, I'm reporting this conveyor dyeing issue.

Version 138 of IE

![2021-10-07_11 27 51](https://user-images.githubusercontent.com/4199846/136428076-5df417ee-4635-4f78-99dd-be6e45a93861.png)

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/c86c4e5377f8dbbdcfb6177eceefe772277a0b76
