### ISSUE TITLE
[suggestion] Fruit juice in industrial squeezer

### ISSUE THREAD

**Issue by kotoroshinoto** [BluSunrize/ImmersiveEngineering#502]
would be nice to be able to crush things such as apples, strawberries, blueberries, grapefruit, oranges etc.

**Comment by mindforger** [comment]
apples do work, what mod are those berrys from? i don't believe they are vanilla :p
harvestcraft support has been added recently, but if you dig only a tiny little bit into minetweaker youself, and investigate the IE Minetweaker Support, you can achive this easily in 0.5.4

**Comment by kotoroshinoto** [comment]
I wasn't having luck with apples, but I was looking mostly at harvestcraft and forestry

**Comment by mindforger** [comment]
yeah my fault it were potatoes that were used in 0.5.4 and melons but not apples ... well ... but still in the current dev there are all fruits and seeds bound by "dictionary" or "wildcard" for seedoil and ethanol ... saying oreDict is wrong i know :P

**Comment by BluSunrize** [comment]
Apples currently only work in the fermenter, in order to create ethanol. It does not have a squeezer recipe.
I'll look into it.

**Comment by kotoroshinoto** [comment]
it shouldn't be too difficult to add in recipes. The only thing that is a bit of a pain in the neck is trying to assign the correct juice output to everything ;p

**Comment by mindforger** [comment]
try using Excel or OpenOffice Calculation
| mods.immersiveengineering.Squeezer.addRecipe( < | **mod** | : | **outputitem** | : | **dmgVal** | > * | **count** | , < | **mod** | : | **outputfluid** | > * | **mBuckets** | , < | **mod** | : | **inputItem** | : | **dmgVal** | > * | **count** | , | **ticks** | ) |
something like that an then export it to an txt file with whitespaces

**Comment by kotoroshinoto** [comment]
i already have modtweaker, been using it for recipe conflicts or missing pulverizer/enrichment recipes etc. TY for the heads up though.
