### ISSUE TITLE
[Visual only][1.17.1 | #31] LV Wire leading to Razor Wire is invisible

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#5021]
as title.
Affects both Insulated and regular LV Wire.
The Razor Wire does receive the damage buff from being electrified and placing a block in between the Razor Wire and the other point the LV Wire is connected to pops off the wire, so it seems to be purely visual.

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/b6eb877e8f34b53803fbc4aa13f0ff901d0d4bfd
