### ISSUE TITLE
(suggestion) add diesel - powered minecarts for vanilla tracks and couplings similar to Create

### ISSUE THREAD

**Issue by Fluffton** [BluSunrize/ImmersiveEngineering#5023]
so, you know how theres minecarts with storage crates and barrels right?
what if there was a way to make those move, other than a furnace minecart or powered rails?
and also what if there was a coupling system that comes with IE so you dont have to download Create?
So, hear me out

(bio)Diesel Locomotive
Crafting recipe
Blank | Blank| Steel Mechanical Component (for control stand)
Radiator block (for cooling off engine) | Heavy Engineering Block (for engine) | Kinetic Dynamo or Generator Block(for powering the 4 minecart wheels)
Blank | Minecart (for the chassis of the locomotive)| Blank

The locomotive would be power-able for a long time off of a full Jerrycan of biodiesel.
The locomotive can not be ridden on but if you connect a minecart behind the locomotive or in front of it and get in the minecart you can press a key bind such as [R] then there will be a GUI on the top of your hot bar that shows the status of the locomotive and you can now drive it using [W] and [S]. Also, i think it would be cool to have a horn for the locomotive! like, if you hold [H] it will play a small horn sound for as long as you hold the button.
The locomotive can be able to pull around 50 minecarts , all with full inventories
It would be nice if you could hook together 2 or 3 locomotives for combined power!

Chain Coupler 
Crafting recipe
Steel or Iron Ingot | Steel or Iron Rod |Steel or Iron Ingot

The couplings will work the exact same way as Create couplings.

Thats about all i have to suggest. Also, I'm new to GitHub so yeah

also, how do i add a label such as Suggestion??

**Comment by Fluffton** [comment]
also, yes i know this is very similar to Railcraft but i really would love to see a Railcraft type approach from Immersive Engineering

**Comment by Fluffton** [comment]
also, i dont know how to make this a suggestion instead of an issue please help!!!

**Comment by malte0811** [comment]
This has been said before, IE is not going to get advanced minecarts of any kind. You may be interested in some of the things @SkySom has been doing though.

**Comment by Fluffton** [comment]
> This has been said before, IE is not going to get advanced minecarts of any kind. You may be interested in some of the things @SkySom has been doing though.

Aww, okay. Where does it say that you wont be adding advanced minecarts?

**Comment by Fluffton** [comment]
https://github.com/BrassGoggledCoders/Transport
also, where in the world do i download this fucking mod?///??//?

**Comment by BluSunrize** [comment]
On curseforge, where you find every other mod.
