### ISSUE TITLE
Unable to use redstone connectors Forge Server 1.16.5

### ISSUE THREAD

**Issue by Sublime204** [BluSunrize/ImmersiveEngineering#5024]
I don't get any crashes or errors but when I place down a rs connector and right click to change from input to output with the engineer's hammer nothing happens also holding shift and right clicking to change the color nothing happens either.

I looked to see if there were any other issues reported but couldn't find anything pertaining to this specific issue, also checked the config file to see if something was disabled but don't see anything there.

Any guidance would be much appreciated.

**Comment by BluSunrize** [comment]
Use a screwdriver. Says so in the manual.

**Comment by Sublime204** [comment]
I'll give that a try, sorry about that I didn't notice it in the manual just watching a few yt videos on it and they used the hammer as most other immersive things use it I didn't even think twice.
