### ISSUE TITLE
Wire cutters dont work after 1 durability is taken (or one use)

### ISSUE THREAD

**Issue by SethXB** [BluSunrize/ImmersiveEngineering#5025]
Version 5.0.3

I managed to recreate it on a server, and in singleplayer

**Comment by BluSunrize** [comment]
"Don't work"?

What's that mean? Do you have pictures? Modlists?

Have you tried it in 5.0.4?

**Comment by SethXB** [comment]
No its easily recreatable, just try making some wire from metal plates, it only makes 1. And i did not try that newer version. I would but I dont need more wire anytime soon. I tried the zipline and its too glitchy to use. I can't seem to ever hop on the wire. When it does its not a good experience xD. If you care to fix go ahead, but personally i dont mind unless zipline is fixed.

**Comment by Dannyftm** [comment]
I'm also having the same problem on my server with crafting plates or wires. After the hammer is used once to craft, or the wire cutters are used once, they no longer allow you to craft with it.

**Comment by BluSunrize** [comment]
That sounds like an issue with whatever modpack you are playing.

If you can reproduce his in an instance that only has IE installed, feel free to open a new issue, and **provide a detailed report**.
