### ISSUE TITLE
[Suggestion] Put pipes being colorizable into the manual

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#5028]
Apparently it's an easteregg/hidden feature, but it's pretty useful for placing pipelines that aren't supposed to ever hook up and for telling them apart visually, too.
Conveyors being colorizable is in the manual, too. That one got added later, so maybe this one just fell off the radar?

**Comment by BluSunrize** [comment]
Assigning this to myself, since it's a gameplay/ingame documentation topic, and also not a bad thing to put in 1.16 as well.
