### ISSUE TITLE
[1.17.1 | #33] Waterwheels dummy BEs are ticking on client and server

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#5031]
as title
`if(isDummy()) System.out.println("this")` puts out a bunch of dummy and generally there are much more waterwheel entities ticking than the 3 for the main block of the 3 wheels I've placed
I didn't investigatebeyond this, too tired and to unfamiliar with the "how it should be"
happened to me coding against rev 6c129e715dc29d2561081ac67ecff0ffe54ad7f8

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/63d348cf3f1e6c70b5f497187bfbc266f905b5bb
