### ISSUE TITLE
Engineer's Hammer - No craft after durability loss

### ISSUE THREAD

**Issue by leonardostorrespro** [BluSunrize/ImmersiveEngineering#5033]
### Before reporting:
- checked

### Description of the issue:
Cannot craft any more items with Engineer's Hammer after it's durability is lowered by one point.

### Crashlog:
No crashes.

### Versions & Modlist
Valhelsia 3 - 3.4.3 Minecraft 16.5 Forge 36.2.6

Tested the issue in a singleplayer and multiplayer environment. Removed crafting tweaks to make sure it wasn't it.

![Crafting Player inventory](https://user-images.githubusercontent.com/85841138/136988960-c6522be5-f17c-4afb-8c75-6546cf63cb27.png)
![Crafting Table No](https://user-images.githubusercontent.com/85841138/136988962-c873da9e-dda8-4f12-92c1-c73bd6d7e913.png)
![Crafting Table Yes](https://user-images.githubusercontent.com/85841138/136988964-32f3df21-8177-49c8-9144-bcc37d29e806.png)
![Not crafting Player inventory](https://user-images.githubusercontent.com/85841138/136988968-3bdf7175-2225-4e74-9dfb-8c806c94886a.png)

**Comment by BluSunrize** [comment]
Can you reproduce this in an instance with just IE, instead of in a modpack?

**Comment by leonardostorrespro** [comment]
Hey there. 

Thank you for suggesting that. I just finished testing it and can confirm that Immersive Engineering is working and the problem lies with **Creator**'s mod as the plates obtained are different from the ones with Creator mod ON.

![NEW PLATES](https://user-images.githubusercontent.com/85841138/137347985-50e15775-8e85-4cfa-b95c-b4d4b4e9693c.png)

**Comment by BluSunrize** [comment]
I would just assume for now that the issue lies with the modpack. So please report this to the devs of Valhesia, so they can take a look at it.
