### ISSUE TITLE
[Feature Request] Redstone output for Breaker Switch

### ISSUE THREAD

**Issue by HiddenKn** [BluSunrize/ImmersiveEngineering#504]
I really love the model of the breaker switch.
Would it be possible to make it output a redstone signal on the block behind it?
It would look really awesome.

**Comment by theunkn0wn1** [comment]
It does emit redstone signal to all adjacent blocks last I checked... By default it only emits when current is passing through it, you can invert it by right-clicking with the hammer.

**Comment by HiddenKn** [comment]
Oh, cool! Thank you for letting me know that.

**Comment by theunkn0wn1** [comment]
No problem, oh and pro tip: there is a achievement called 'RTFM', you should get it...

**Comment by HiddenKn** [comment]
I actually looked online before I made this issue, no need to be a douche.

**Comment by mindforger** [comment]
@HiddenKn he is not a douche, he is dead serious ... but the humorous part was kinda dry :P
#ACHIEVEMENTS
achievement.immersiveengineering.openManual=RTFM
achievement.immersiveengineering.openManual.desc=Open the Engineer's Manual

**Comment by HiddenKn** [comment]
Oh, I see, hah! There really is an achievement called RTFM.
I thought he meant I didn't put any time into trying to solve the issue myself :P
I wasn't aware of the ingame manual. Thanks for letting me know about that. :)

**Comment by BluSunrize** [comment]
Achievements are only in 0.6,  @mindforger, so he might not have those.
As for not knowing about the Engineers Manual: shame on you. xD

**Comment by theunkn0wn1** [comment]
For the record,
@HiddenKn I am sorry, The joke I was attempting to make was poorly executed and made half-asleep ;(  
 I was not intending to be a douche, I was attempting to gently nudge at the 0.6 achievement that in itself is kinda dry.
