### ISSUE TITLE
Durability of hammer goes to 99/100

### ISSUE THREAD

**Issue by bowenje** [BluSunrize/ImmersiveEngineering#5040]
When I make sheetmetal durability of hammer goes to 99/100.   I can't make a second one.  There does not seem to be a way to repair it back to 100 so I have to make a hammer for each sheetmetal I want.

**Comment by BluSunrize** [comment]
Your issue report is terrible, and does not contain any information that we could actually use to help you.

Luckily for you, you're not the first person to report something like this, so I will make an educated guess that you are playing a modpack (possibly Valhesia 3?) and that you did **not** try to reproduce this in an instance without IE.

Report this to the modpack makers.
