### ISSUE TITLE
Engineer's wiRe cutters problem

### ISSUE THREAD

**Issue by shaneyap99** [BluSunrize/ImmersiveEngineering#5041]
I am playing immersive engineering from engimatica 6. I realize that the wire cutter can only cut one copper plate when the cutter is full. If there is damage to the cutter, it cannot cut anymore wire unless I put two wire cutter to make it without damage. I believe it is a bug. I hope it is fix for it. Thank you

**Comment by BluSunrize** [comment]
Report that to the modpack makers, it's not an IE issue.

Please actually follow the issue template and contribution guidelines next time.
