### ISSUE TITLE
[1.16.5] Survey Tools not counted as tools in Engineers Toolbox

### ISSUE THREAD

**Issue by IcedForge** [BluSunrize/ImmersiveEngineering#5045]
### Description of the issue:
Survey tools are not accepted in the tool slots of the Engineers toolbox

### Versions & Modlist
(If you need me to retry it in pure IE let me know but since its an IE to IE things i would suspect that its just a classification miss )
Immersive Engineering 1.16.5-5.0.4-139
Forge 36.2.1
![Screenshot_36](https://user-images.githubusercontent.com/24981362/137592893-a2025bb1-ef8e-4e67-821b-a47d3606868d.jpg)

**Comment by BluSunrize** [comment]
Closing this because support for 1.16.5 has ended
