### ISSUE TITLE
Excavator Ticking Block Entity Crash

### ISSUE THREAD

**Issue by SteelBaron** [BluSunrize/ImmersiveEngineering#5049]
When an excavator is fully built the game causes this crash. It only happens when both parts are built, not when either is built separatel
[crash-2021-10-19_20.48.11-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/7377640/crash-2021-10-19_20.48.11-server.txt)

**Comment by malte0811** [comment]
Update IE, this is fixed in build 139.
