### ISSUE TITLE
[1.16.5] Crash on teleport

### ISSUE THREAD

**Issue by ianwijma** [BluSunrize/ImmersiveEngineering#5051]
### Before reporting:

I've check and was unable to find any related issues.

### Description of the issue:

ref: https://github.com/NillerMedDild/Enigmatica6/issues/3509.

On teleport to a loaded, but out of render area with wires it sometimes seem to crash, This does not happen all the time. But happens more often when on a server.

This only crashes the client, not the server. In single player both obvious crash.

### Crashlog:

- paste.ee/p/o157i
- paste.ee/p/qAW4s

### Versions & Modlist

Mod: ImmersiveEngineering-1.16.5-5.0.3-138.jar
Forge: net.minecraftforge:36.2.4
Modpack: Enigmatica6-0.5.16
Mod list: https://paste.ee/p/qAW4s#s=0&l=29809
Other details: https://paste.ee/p/qAW4s#s=0&l=29780

**Comment by BluSunrize** [comment]
Closing this because support for 1.16.5 has ended
