### ISSUE TITLE
Hammer only works once when crafting copper ingots

### ISSUE THREAD

**Issue by yasiralamriki** [BluSunrize/ImmersiveEngineering#5057]
### Description of the issue:
When you make a copper ingot your hammer gets its durability decreased by 1 as it should, but its now 249/250 and then you cant use it again, you have to make a new one. This is annoying because I don't even think I have to explain

* Does it happen every time you do this? Does it happen if you do something else as well? E.g. "The game crashes with a similar crash whenever an item that can not be processed in the crusher is thrown into one.".

*  Yes.

* Did this happen on a dedicated server (multiplayer servers), in LAN multiplayer or in singleplayer? E.g. "I first noticed this on a server, but it happens in singleplayer as well".

* Yes, I haven't tested it in singleplayer.

### Versions & Modlist
* LWJGL 3: 3.2.2
* Minecraft: 1.16.5
* Forge: 36.2.4
* Immersive Engineering: 1.16.5-5.0.3-138
* I don't know how to get a full list

**Comment by BluSunrize** [comment]
This is a modpack issue. Report it to the modpack makers. It would work fine if you tested it with only IE.

And for future reference, if you provide us with a debug crash (by holding F3 and C for 10 seconds) that log would contain a full modlist.

**Comment by yasiralamriki** [comment]
ty, also apparently its fixed in the newest version of the modpack
