### ISSUE TITLE
Texture pack and Shaders Crash

### ISSUE THREAD

**Issue by diegomejia21** [BluSunrize/ImmersiveEngineering#5058]
On version 1.16.5

The game crashed whilst rendering overlay
Error: net.minecraftforge.fml.ModLoadingException: Immersive Engineering (immersiveengineering) encountered an error during the done event phase
Exit Code: -1

Saw another thread but no solution was provided.

Crash-log: https://pastebin.com/kYJxDMZF

**Comment by BluSunrize** [comment]
Optifine is not supported.

**Comment by diegomejia21** [comment]
Its not only shaders, its also texture packs so I do believe it is more than just optifine?
