### ISSUE TITLE
Crates disappearing with their contents when broken by non axe type tools (incompatability with Yanny's Stone Age)

### ISSUE THREAD

**Issue by spunkiethefirst** [BluSunrize/ImmersiveEngineering#5061]
The crates will take their contents with them and go poof if broken with a non axe tool such as by hand or using the mining drill.
This happens consistently.  Chests do not suffer the same issue.
Only tested in single-player.

Video of behavior:
https://youtu.be/i9jYiEHu-7Q

### Versions & Modlist
Minecraft ver 1.16.5
Forge 36.2.0
ImmersiveEngineering-1.16.5-5.0.5-140
stone-age-1.16.5-1.3.2
ages-api-1.16.5-1.2.0

I will also post this in the Stone Age mod issue as well.
Thanks for your time

**Comment by BluSunrize** [comment]
Closing this because support for 1.16.5 has ended
