### ISSUE TITLE
[1.16.5 Feature Request] Datapack driven fuel values

### ISSUE THREAD

**Issue by MuteTiefling** [BluSunrize/ImmersiveEngineering#5062]
Tossing out the template as this is not a crash/bug.

### Description of the request:

Per discussion on Discord with Malte, it would be lovely if registering fuels and burn times could be handled through Datapacks rather than strictly through the API. Ideally both for the Diesel Gen and Drill. Thermogen could be a nice candidate too for adding custom hot/cold blocks.

**Comment by malte0811** [comment]
Implemented on 1.17 in 41f8674eb59ff785fe6ce292174248590771dc29, 4e12b8da1a455e626972bb218baf2fcccc5bb048 and 830c24d5abb3a787b79caa88684a25d692fa91fe. I'm not entirely sure whether I'll backport it to 1.16 yet, I'd need to make sure the old API keeps working (which I didn't need to worry about on 1.17).

**Comment by MuteTiefling** [comment]
If not possible to do in 1.16, would it at least be possible to have a way to override existing values via the API? I have a functional script for adding fuel values, but I can't seem to touch the base diesel values at all.

**Comment by malte0811** [comment]
I've backported the drill- and generator fuel changes (54af8804e68e7619ac3705a245958e580277902a and 987a23dd39913ea0a2e2bc8f515cacf015dccb90); the thermoelectric generator would be a lot harder for annoyingly technical reasons, so I won't backport that.

**Comment by MuteTiefling** [comment]
Lovely, thanks!
