### ISSUE TITLE
[1.16.5] Logic unit resets registers after cycling through logic circuits

### ISSUE THREAD

**Issue by Rossander47** [BluSunrize/ImmersiveEngineering#5063]
### Before reporting:
It does not seem like other people have reported this issue yet.

### Description of the issue:
After updating to version 1.16.5-5.0.5-140 I found that logic units no longer retain the state of a register after cycling through their 10 logic operations. That broke most of my systems using logic units since they relied on latches made from NAND gates.

### Versions & Modlist
ImmersiveEngineering-1.16.5-5.0.5-140
Forge-36.2.0

**Comment by malte0811** [comment]
This is actually intended, @BluSunrize never meant them to keep their state. Even before the state was reset every time the chunk unloaded. I'm sorry it broke your existing setups, but Blu insisted that the fix should be backported to 1.16.

**Comment by Rossander47** [comment]
Yeah I was afraid that was the case. Thanks for the quick reply though
