### ISSUE TITLE
Shield, Hammer, and Other items Can't be enchanted at anvil. (Weld Station?)

### ISSUE THREAD

**Issue by HeavyDeception** [BluSunrize/ImmersiveEngineering#5064]
### Description of the issue:
You can enchant them at the table but not place a book on them at an anvil.

### Crashlog:
No crash.

### Versions & Modlist
IE: 1.16.5-5.0.4-139
Forge: 36.2.4

Mod Pack: Enigmatica 6 0.5.17
Have tried it with just IE and still dose the same thing.

**Comment by HeavyDeception** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/2944#issuecomment-381422660

I saw this after looking for if the drill and saw were on a black list but didn't think the shield was.
If this could be an option because some mods like Apotheosis add some enchants for shields plus vanilla allows mending on a shield but you can never get it on an IE shield as you only find it in book form.

If this is working as intended may I suggest adding a line in the book saying that the shield can't be enchanted at an anvil and something about why it can be at an enchanting table in the book?

**Comment by HeavyDeception** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/1905#issuecomment-280837740

As I'm looking at other things that have to do with "magic" I kind of get the feeling you going for and I would like to make a suggestion. For the Drill, Saw, Shield and, Other Tools. As someone who works with metal, it would be great if you have a repair station/Welding station this could be for the tools where they could be repaired and worked on. Like the saw blade in this station, you could add carabid teeth to it allowing it to use less power and work faster, or diamond dust to the drill allowing it to use even less durability.

I kind of imagine this station as a welding or blacksmithing station with no automation.
Needs
-Power.
-Bio-Diesel or Ethanol to run the torch. if you didn't want to add gas like Acetylene.
-Rod of the same material as what you are repairing or modifying.
-Oil to Cool the tools that you weld on.
-Welding gloves and a face shield.

What this is looking to fix is the XP cost. The bonuses for using this station as things could be repaired cheaper at this than a normal anvil.

Upgrade like Case Harding Powder this is a metal Harding compound to Case harden Steel and Iron this adds Durability.
Drill. Dimond dust coating has better efficiency and durability.
Saw. Carabid Teeth same as the Dimond dust but for the saw.

This is getting really long so I will stop here if I and wait for what you have to say.

**Comment by BluSunrize** [comment]
I'm not adding a "tech enchanting" system.
