### ISSUE TITLE
[1.16.5] Silo crashes on item insert

### ISSUE THREAD

**Issue by ephys** [BluSunrize/ImmersiveEngineering#5067]
### Description of the issue:

I have a silo that crashes when an item is inserted in it (tried with pipez & refined pipes), it crashes with the following report: https://gist.github.com/ephys/065e23b60c5b931c97a5e808e2e40a2e

It's difficult to replicate, I don't know why this silo crashes and not others.

### Versions & Modlist

Forge: 36.2.4
IE: 5.0.5-140

**Comment by BluSunrize** [comment]
Closing this because support for 1.16.5 has ended
