### ISSUE TITLE
[1.16.5] Workbench gui bug

### ISSUE THREAD

**Issue by Gorbiel** [BluSunrize/ImmersiveEngineering#5068]
### Description of the issue:
Whenever I insert a blueprint, nothing shows up (when I hover over a slot I can read what's supposed to be there) and when I click it I can't see the ingredients. Also there is a weird slot in the top left corner that does nothing.
Screenshot: https://imgur.com/a/nvZHMsP

### Versions & Modlist
Forge: 36.2.8
IE: 5.0.5-140
Modlist: https://pastebin.com/jYCxdBWL

**Comment by Bob74** [comment]
Same issue here. It started happening after updating my mods (including Immersive Engineering to 140) and adding new ones.
I am using Optifine G8.

https://i.imgur.com/jkhXUoF.png

### Versions & Modlist

Forge: 36.2.4
IE: 5.0.5-140
Full modlist: https://pastebin.com/HjWuz78q
What has been updated/added before having the issue: https://pastebin.com/g3zPLaT4

**Comment by N445** [comment]
Same issue here

but i don't have the interface on the right

https://imgur.com/a/ipKT7SY
