### ISSUE TITLE
[1.16.5] Posts appearing weird after current update

### ISSUE THREAD

**Issue by Aaron1248** [BluSunrize/ImmersiveEngineering#5069]
The issue started the minute I downloaded the new update and hasn't gone away. Everything else appeared fine its just the posts having this issue.

Modlist: 
[Aaron1248's Minecraft 1.16.5 Mod List.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/7499629/Aaron1248.s.Minecraft.1.16.5.Mod.List.txt)
Screenshot of Issue:
![2021-11-07_22 59 05](https://user-images.githubusercontent.com/37682580/140806700-2342d0ee-be8a-4a54-99cd-4cee0c2ed97e.png)

**Comment by mounderfod** [comment]
Reproducible, the mods we have in common are
```
- Macaw's Bridges
- Xaero's Minimap
- Xaero's Worldmap
```
