### ISSUE TITLE
[1.16.5] Degraded FPS when crushers are being overloaded with items

### ISSUE THREAD

**Issue by ianwijma** [BluSunrize/ImmersiveEngineering#5077]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:

I run my world on a local server, running Enigmatica 6 - 0.5.20, which runs ImmersiveEngineering-1.16.5-5.0.5-140.

I often leave my server running over night if I need to collect allot of resources for a big project. So one day I wanted to join my server. Where upon joining the world, my CPU goes to 100% and run usage goes to high, it exceeds the amount of RAM it has and crashes.

After TPing myself outside render distance of my base I stop crashing and manage to join the server. Where after getting close to my base, I start to notice ALLOT of lag again. I do manage to walk though my base when I set my render distance to the lowest. But its not a fun experience. (~3 seconds per frame)

After chatting with some people in the Enigmatica discord, they recommend running spark. Which I done twice, once outside my base and once when I come closer:

Outside: https://spark.lucko.me/qwJnY4bRgr
Inside: https://spark.lucko.me/AG3CO1RcjK

Where you can see some multi block construction is causing issues, so I decided to break my 8 crushers. Right after I've broken 4 crushers the FPS gets loads better.

Once all broken, the FPS returns to normal.

I've tried also joining the world with a clean client, that does not has optifine installed, which resulted in the same issue,

If wanted, you can download the FTB backup of the world. https://www.dropbox.com/s/638h2bcpm8m81d3/2021-11-16-17-43-24.zip?dl=0

### Crashlog:
https://spark.lucko.me/AG3CO1RcjK

### Versions & Modlist
Modpack: Enigmatica 6 - 0.5.20
Mod version: ImmersiveEngineering-1.16.5-5.0.5-140
Mod list: https://www.curseforge.com/minecraft/modpacks/enigmatica6/relations/dependencies

**Comment by malte0811** [comment]
![screenshot](https://user-images.githubusercontent.com/10406104/142168795-067b53cf-7620-4af0-b017-f4bcb5a48f23.png)

The problem seems to be that we're syncing the recipe queue (which we *really* shouldn't on the crusher), and apparently far too often as well. I'll try to look into it over the weekend.
