### ISSUE TITLE
[1.12] Add Comp for Growable Storage Cells for Garden Cloche please?

### ISSUE THREAD

**Issue by Kaya85** [BluSunrize/ImmersiveEngineering#5078]
So yeah I've been using Growable Storage Cells for my private Modpack since I'm pretty tired of all the microcrafting stuff especially when I have to restart a map a lot of times when I change something in my pack xD 

And it's just a small thing but if I could grown those Seeds in the Garden Cloche it would be a lot less space consuming (also things growing faster would make a big difference for early Storage)

So yeah, I'd really appreciate if you could add those Seeds in :3

Not sure if I still need to include Versions but Forge is 14.23.5.2854 and Growable Storage Cells is 1.12.2-3.1.0

**Comment by BluSunrize** [comment]
Support for 1.12 was cancelled 17 months ago.
