### ISSUE TITLE
Error stiching

### ISSUE THREAD

**Issue by miuirussia** [BluSunrize/ImmersiveEngineering#508]
After compiling latest version, I get error when minecraft starting:
http://pastebin.com/60NZ9kbL

**Comment by BluSunrize** [comment]
Are you using a texture pack?

**Comment by miuirussia** [comment]
No, using standard texturepack

**Comment by miuirussia** [comment]
More info, maybe it help: 
https://gist.github.com/miuirussia/2ba0404c6613b88e83c6

**Comment by BluSunrize** [comment]
Try it without Immersive Integration. That mod isn't updated to the newest IE api yet.

**Comment by miuirussia** [comment]
Working without Immersive Integration. Thanks!
