### ISSUE TITLE
[1.17.1 | #52] Can't shift-click items into the last slot of Wooden Storage Crates

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#5083]
As title.
I'll try to fix this, because it's probably a simple slot range issue.

Can't shift-click into last slot:
![grafik](https://user-images.githubusercontent.com/7753414/143366149-941636e9-d557-4d7b-8dff-ba7b2ae620b6.png)

CAN shift click into other slots:
![grafik](https://user-images.githubusercontent.com/7753414/143366192-9d1279cb-2201-41e4-a817-a374e49f2701.png)

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/aa2e33f2487d7f0fa52f7417de520844d23f0d91
