### ISSUE TITLE
[1.17.1 | #52] Energy consumers add energy to capacitors instead of subtracting it

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#5084]
As title.
For this to work, the capacitor need a little bit of energy to start with, presumably because the consumers won't try to "take" (give to) energy from the capacitors, if there is no energy to begin with. (bad wording, if the energy system is push based, but point still stands)
The energy stored in the capacitors can also go above the usual limit of the capacitors.
I don't know if this behavior is exclusive to capacitors. Maybe, since IF is push based, iirc?

Tested with LV and HV capacitors and excavators and external heaters:
![grafik](https://user-images.githubusercontent.com/7753414/143452890-2b6bd7f4-8bef-410e-af6d-bc395a2ab35c.png)
![grafik](https://user-images.githubusercontent.com/7753414/143452969-1d1db0c4-636e-4ce6-9c7a-1909c25a2602.png)

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/4925d521921ace7def7170fe478c29f8c65db56c
