### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by Boolyman** [BluSunrize/ImmersiveEngineering#5085]
Forge: 36.2.8 
Immersive Engineering:  1.16.5-5.0.5-140

I'm getting a crash on load occasionally.  It doesn't seem to happen every time I load, but intermittently.  Below is the crash report:

https://paste.gg/p/anonymous/bc82019479394ac3969e0dcdc883d36c

**Comment by malte0811** [comment]
I'm not sure why you think this particular crash is caused by IE, but it looks like `RenderType#create` is not actually thread-safe on 1.16.5. I'm not convinced that IE ever calls it off-thread, but we call it during static init, which doesn't really have threading guarantees.

**Comment by Boolyman** [comment]
Are you saying that this could be related to the Create mod?  If not, do you have any idea of what mod is causing it?
