### ISSUE TITLE
[1.17.1 | #52] [Visual Only] Wires occasionally aren't fully drawn, depending on angle

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#5086]
as title.
It's an old issue and didn't really matter much. But nowadays these things could kill you and I guess that makes them more important to see ^^
![grafik](https://user-images.githubusercontent.com/7753414/143479456-c72cc104-5747-470b-86a3-e577660005a3.png)

**Comment by malte0811** [comment]
This is just the standard chunk culling being unhappy about our massive block models, right? Then it's something to put on the list of "when I have more time and energy than sense".

**Comment by malte0811** [comment]
Fixed in #5162
