### ISSUE TITLE
[1.16.5] [5.0.5-140] Engineer's Crafting Table occasionally eats items.

### ISSUE THREAD

**Issue by Anomorphous** [BluSunrize/ImmersiveEngineering#5088]
### Description of the issue:
With an almost-full (one slot open, for example) inventory in the Engineer's Crafting Table's storage and a full player inventory, crafting an item that has multiple outputs (glass panes, metal nuggets, etc) will drop excess on the ground. This is normal and expected. However, with the crafting recipe still in place in the crafting area, shift-clicking the output (the nuggets, panes, etc) in the table's storage area will delete a large portion of the stack. Then, the remainder will be placed into the crafting area as an additional item.

 As far as I can tell, for a single frame the OUTPUT of the crafting jumps to a full stack, meaning the output window is read as a valid place to put items, and instead of crafting as it would with a left click while holding a stack in the cursor, it deletes the items put in into the output slot and then shows the correct output number again. The items are not dropped on the ground, nor does the console give any output when this happens.

[Here's a short video showing what it looks like.](https://www.dropbox.com/s/vncjgb107lvbjfj/immersive%20engineering%20crafting%20bug.mp4?dl=0)

### Versions & Modlist
IE Version: 1.16.5-5.0.5-140
Forge Version: 36.2.0
Modlist; happens on an instance with only Forge and IE installed

**Comment by BluSunrize** [comment]
Potentially fixed in #5217
