### ISSUE TITLE
[1.17] Bottling machine animation is broken

### ISSUE THREAD

**Issue by Zahkriiven** [BluSunrize/ImmersiveEngineering#5098]
### Description of the issue:
The bottling machine animation doesn't work at all, it would just render the bottle static, sometimes doubled if the bottle is thrown closer to the nozzle. Everything else works.
![image](https://user-images.githubusercontent.com/25531677/144483256-43964101-009d-486d-9322-1a45ee4fce6d.png)

### Versions & Modlist
ImmersiveEngineering-1.17.1-5.0.2-pre.306

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/4b3cb2d815583a5a19fa2ed915c8c66ba1531b5f
