### ISSUE TITLE
Only info I have is StackOverFlow - Happened on Server

### ISSUE THREAD

**Issue by DoughnutDev** [BluSunrize/ImmersiveEngineering#51]
http://pastebin.com/jwpwajms

**Comment by DoughnutDev** [comment]
So how I think this happened is that I had a hopper connected to a frementer and a open crate on the top of that hopper and that is when it happened it also rolled back the server about 10 mins

**Comment by BluSunrize** [comment]
Nope, not your fault, mine. But I fixed that already. Are you sure this was on latest?

**Comment by DoughnutDev** [comment]
No because I didn't know if that Coke Oven rendering would screw up my world so I am still on 0.1.15
