### ISSUE TITLE
[1.16.5] game crashed when enable or disable a shaderpack

### ISSUE THREAD

**Issue by asougi855** [BluSunrize/ImmersiveEngineering#5101]
When I enabled or disabled a shaderpack using optifine,the game crashed with an ArrayIndexOutOfBoundsException.

Mod version: ImmersiveEngineering-1.16.5-5.0.5-140
Forge version: 1.16.5-forge-36.2.0

crashlog and modlist: https://pastebin.com/A3dKEFr0

**Comment by malte0811** [comment]
Optfine is not supported. And just for reference, I looked into this once and it's fully Optifine's fault.
