### ISSUE TITLE
[1.17] Mineral survey tools cannot be placed in the toolbox tools section

### ISSUE THREAD

**Issue by Zahkriiven** [BluSunrize/ImmersiveEngineering#5102]
### Description of the issue:
As title, the mineral survery tools won't go into the tools section of the engineers toolbox. Neither by placing normally or shift clicking, this places it on the anything section.

### Versions & Modlist
ImmersiveEngineering-1.17.1-5.0.2-pre.306

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/275a55e7b3759a4f0dc721773afc971e21f2056d
