### ISSUE TITLE
[1.18] Raw Ore Recipes

### ISSUE THREAD

**Issue by TooManyKitKats** [BluSunrize/ImmersiveEngineering#5104]
### Description of the issue:
Recipe for IE raw ores in furnace do not exist, do exist for arc furnace.
### Versions & Modlist
![image](https://user-images.githubusercontent.com/62522289/144770075-bdf9c05b-906f-4886-a4e1-7cac5e4da48c.png)

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/96a6b63c13acf0ec24af92a74cabacad7f83a82d
