### ISSUE TITLE
[1.18] Manual Multiblocl Rendering

### ISSUE THREAD

**Issue by TooManyKitKats** [BluSunrize/ImmersiveEngineering#5105]
### Description of the issue:
Multiblocks do not render in the IE manual.
![image](https://user-images.githubusercontent.com/62522289/144778740-95612124-abc0-479f-9f51-ade2defae7f4.png)

### Versions & Modlist
![image](https://user-images.githubusercontent.com/62522289/144778756-b04484a3-6191-4ad9-a86d-2a9fbdad0d5d.png)

**Comment by malte0811** [comment]
![2021-12-06_10 16 24](https://user-images.githubusercontent.com/10406104/144819985-39aee2d5-c820-40d7-ba82-6afe612bb0f9.png)
It's working for me, even on a dedicated server. Does it work without the additional mods? Are there any errors in the log?

**Comment by malte0811** [comment]
Issue is only present with "fabulous" graphics, but reproducable once that's enabled.

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/c23f424a840af5f7d40d560fb3d1967abed546e6
