### ISSUE TITLE
[1.18] Coke oven fluid tank not updated properly when not full

### ISSUE THREAD

**Issue by Zahkriiven** [BluSunrize/ImmersiveEngineering#5106]
### Description of the issue:
The creosote tank won't update if the tank is not full. It will work and extract the creosote but visually the fluid amount will not change. In my experience it works correctly when the tank is full. I'm using a jerrycan but a normal bucket acts the same.

![image](https://user-images.githubusercontent.com/25531677/145018322-10cb34ec-db84-4008-8063-594bb8f5e7ed.png)
Here, no fluid in the tank but still visually shows 3 buckets worth

### Versions & Modlist
ImmersiveEngineering-1.18-5.0.2-pre.348

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/7e7cc94021cc0af7a01e408c5cdcb2a5f4348ef4
