### ISSUE TITLE
[1.18] Multiblock damages player on contact

### ISSUE THREAD

**Issue by Zahkriiven** [BluSunrize/ImmersiveEngineering#5108]
### Description of the issue:
At least crusher and advanced blast furnace damages the player on contact on only on some blocks, so far on the edge of the bottom blocks. 
Blast furnace
![image](https://user-images.githubusercontent.com/25531677/145094563-c7216edf-c791-4ba1-9e49-d5507ee230b0.png)
Crusher
![image](https://user-images.githubusercontent.com/25531677/145094597-37c4d798-b145-4dc7-8b2f-a21d844b10fe.png)

### Versions & Modlist
ImmersiveEngineering-1.18-5.0.2-pre.348

**Comment by MalkContent** [comment]
seems to be suffication damage from standing in the "opaque full blocks" that the model replaces.
here's me dieing to a corner of the arc furnace:
![grafik](https://user-images.githubusercontent.com/7753414/145102856-ccd9c6ff-f8d0-4094-9c8d-1e1bc085e24f.png)

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/3c7299c3c52f9961b43d42bed9abd7f81decb9dc, and further improved by https://github.com/BluSunrize/ImmersiveEngineering/commit/5362ead73ff9270f8f6b589359e1e80a7383c8c7
