### ISSUE TITLE
[1.18] Bottling machine animation looks like deleting the bottle when there is no fluid

### ISSUE THREAD

**Issue by Zahkriiven** [BluSunrize/ImmersiveEngineering#5110]
### Description of the issue:
When there is no fluid left,the animation looks like it's deleting the bottle.
![image](https://user-images.githubusercontent.com/25531677/145281745-14fa3d65-9709-43ef-bfd8-261befe5b2b2.png)

### Versions & Modlist
ImmersiveEngineering-1.18-5.0.2-pre.348

**Comment by RRyyas** [comment]
Has similar issues with the Metal Press if it's not powered

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/64eb7d115933cf201cac1aa91d93034d918cc940
