### ISSUE TITLE
[1.18] Fluorescent displays plated shield when in toolbar or offhand

### ISSUE THREAD

**Issue by Zahkriiven** [BluSunrize/ImmersiveEngineering#5111]
### Description of the issue:
It seems to only happen with the steel plated shield. Multiple fluorescent will be affected. When removed from the toolbar or offhand they will remain the same until one of the is broken and updates the others.
![image](https://user-images.githubusercontent.com/25531677/145315424-54f8be4b-f193-4a01-9d9c-305c2c2e59d4.png)

### Versions & Modlist
ImmersiveEngineering-1.18-5.0.2-pre.348

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/e85f7fe1abe5ec6d351712a8e2dd7fea3970157a
