### ISSUE TITLE
[1.18] Crash looking at a fluorecent tube while holding a buzzsaw

### ISSUE THREAD

**Issue by Zahkriiven** [BluSunrize/ImmersiveEngineering#5112]
### Description of the issue:
Steps to reproduce
1. Place a fluorescent tube
2. Hold a heavy plated shield in toolbar/offhand
3. Hold a buzzsaw

Related issue with the fluorescent tube and heavy plated shield https://github.com/BluSunrize/ImmersiveEngineering/issues/5111
### Crashlog:
https://pastebin.com/FV77U2tu

### Versions & Modlist
ImmersiveEngineering-1.18-5.0.2-pre.352

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/e85f7fe1abe5ec6d351712a8e2dd7fea3970157a
