### ISSUE TITLE
[1.18] Some blocks have no collision

### ISSUE THREAD

**Issue by Zahkriiven** [BluSunrize/ImmersiveEngineering#5113]
### Description of the issue:
Some of the inventory blocks have no collision. Tried storage crates, workbench and engineers crafting table.
![image](https://user-images.githubusercontent.com/25531677/145422314-fdd909df-e093-42df-b515-0726070bda13.png)

### Versions & Modlist
ImmersiveEngineering-1.18-5.0.2-pre.352

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/5362ead73ff9270f8f6b589359e1e80a7383c8c7, hopefully the right mix of "not suffocating people" and "not allowing people to walk through blocks" now.
