### ISSUE TITLE
[1.18] Workbench and soldering table cannot be placed without 2 blocks of space above them

### ISSUE THREAD

**Issue by Zahkriiven** [BluSunrize/ImmersiveEngineering#5114]
### Description of the issue:
It needs at least 2 blocks of air to be placed, even 1.5 still does not work.

![image](https://user-images.githubusercontent.com/25531677/145423720-a3bf3106-c46b-4275-aa6c-836bcc0093c6.png)

### Versions & Modlist
ImmersiveEngineering-1.18-5.0.2-pre.352

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/7338872060facfd3d367da651977f236927fbb29
