### ISSUE TITLE
[1.18] 3D-model of the normal sawblade on the buzzsaw missing

### ISSUE THREAD

**Issue by RRyyas** [BluSunrize/ImmersiveEngineering#5115]
### Description of the issue:
The normal sawblade seems to be invisible in the GUI and in-game, regardless if you put a blade quiver on the buzzsaw or not. Also the durability bar is missing in the bottom right-hand side GUI (shows as zero durability). Reproducing this issue is pretty straightforward, just put a 'normal' sawblade in the buzzsaw in the workbench.

Screenshot: https://i.imgur.com/R2ZIFrs.png

### Versions & Modlist
Forge 1.18-38.0.17
ImmersiveEngineering-1.18-5.0.2-pre.362 (Build no. 12)

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/f33b19293b9ad98195e73591483874bf99b38b3d
