### ISSUE TITLE
[1.18.1] Performance drops with railgun rendering either in hotbar or by holding it

### ISSUE THREAD

**Issue by RRyyas** [BluSunrize/ImmersiveEngineering#5117]
### Description of the issue:
When the railgun is in the hotbar or looking in your inventory, the FPS drops by about 50%. When you are actually holding it, it drops further. And if you had put a shader on the railgun the FPS could drop down to 15% the original rate. Reproducing is pretty straightforward, using an Nvidia GPU in my case.

Screenshots: https://imgur.com/a/KfJ3Z7v

### Versions & Modlist
Forge 39.0.0
ImmersiveEngineering-1.18.1-5.0.2-pre.377 (build no. 4)

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/1a06a01612175b47edf755833ce2e9c26f676c65
