### ISSUE TITLE
[Enhancement] Crusher Should output string Instead of Destroying Wool

### ISSUE THREAD

**Issue by mikeloeven** [BluSunrize/ImmersiveEngineering#512]
Generally putting wool through an ore processing block outputs string the crusher simply destroys the blocks yielding no string

**Comment by James-T-Oudvoure** [comment]
I think this should be a feature request rather than a issue report.

**Comment by liamjarvisman** [comment]
yeah this isn't an issue

**Comment by James-T-Oudvoure** [comment]
I actually think a machine that breaks wool blocks down into string would be pretty interesting. I don't think it should be the crusher though, if you fed wool into a machine that turns metal ore into grit, it would come out like when they fed fiberglass insulation into the Muffin Monster.

**Comment by mikeloeven** [comment]
I mostly suggested this because its a well known recipe for the Pulverizer and Macerator as well as the enderio sag mill

**Comment by BluSunrize** [comment]
Done
