### ISSUE TITLE
 [1.18.1 | #7] [Minor] Engineer's Hammer enchantability consistency

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#5120]
Engineer's Hammers are enchantable with the enchanting table, but not with the anvil, which seems inconsistent and unwanted.

iirc them being enchantable was deliberate in order to allow them to compete with Pickaxe mining speed when mining Scaffolding (which they currently can't do, which might be deliberate) by allowing them to get Efficiency

**Comment by unilock** [comment]
The same problem exists with Engineer's Wire Cutters, as of version 1.19.2-9.2.2-16 / 1.19.4-9.4.0-166.

Also, sawblades aren't enchantable at all, but I think they used to be? (in reference to #4115)
