### ISSUE TITLE
[1.18.1] Fluorescent tube rendering blinking almost invisible

### ISSUE THREAD

**Issue by Zahkriiven** [BluSunrize/ImmersiveEngineering#5121]
### Description of the issue:
Something happened to the rendering of the fluorescent tube as it was good after the fix for https://github.com/BluSunrize/ImmersiveEngineering/issues/5111
![image](https://user-images.githubusercontent.com/25531677/146456676-0f67cadc-3254-4fc2-b12e-1918eb64fe0b.png)
![image](https://user-images.githubusercontent.com/25531677/146456733-e5de4cc9-d8fd-470c-a213-26f693052dd0.png)

### Versions & Modlist
ImmersiveEngineering-1.18.1-5.0.2-pre.383

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/9ef14f1d3b609b7dcbc7b661134503e87fe02eaa
