### ISSUE TITLE
Recipes not showing in the engineers workbench.

### ISSUE THREAD

**Issue by kbro89** [BluSunrize/ImmersiveEngineering#5122]
Hi all,

When I put my blueprints into my engineer's workbench, no items are showing to be crafted. I have tried a couple different blueprints and nothing. Is there something that i am missing?

**Comment by Vaelzan** [comment]
This looks like the same issue as here: https://github.com/BluSunrize/ImmersiveEngineering/issues/5068, but for some reason the fixed version was never uploaded to CurseForge.

**Comment by BluSunrize** [comment]
No we just literally have not done a 1.16.5 release since.
The issue is fixed, we just haven't put a new version out. Be patient.
