### ISSUE TITLE
[1.16] Mixer Recipe Does Not Respect Input Fluid Amount Json

### ISSUE THREAD

**Issue by khjxiaogu** [BluSunrize/ImmersiveEngineering#5123]
### Description of the issue:
I'm tring to modify several mixer recipe but I found out that mixer recipe ignores input fluid amount defined in json.
For example, I modified the concrete recipe and increased water cost in json, and this does not take effect.
### Versions & Modlist
Forge 36.2.4
IE 1.16.5-5.0.5

**Comment by BluSunrize** [comment]
How did you "modify" it? Datapack? If so, please provide a full diagram of your filestructure, and the file itself.

Also, a log file would help.

**Comment by khjxiaogu** [comment]
> How did you "modify" it? Datapack? If so, please provide a full diagram of your filestructure, and the file itself.
> 
> Also, a log file would help.

By some datapack, I did not realy modifier original IE recipe. But add my own one like
```
{
  "type": "immersiveengineering:mixer",
  "inputs": [
    {
      "count": 2,
      "base_ingredient": {
        "tag": "forge:sand"
      }
    },
    {
      "item": "minecraft:dirt"
    }
  ],
  "result": {
    "fluid": "immersiveengineering:concrete",
    "amount": 500
  },
  "fluid": {
    "tag": "minecraft:water",
    "amount": 2000
  },
  "energy": 3200
}
```
And I got everything right in jei:
![$YNZAZ7AGGADP2X](https://user-images.githubusercontent.com/54445543/146582622-4286fb31-d3fc-4685-bb84-d032775cbf6c.png)   
But when I insert 2 buckets of water, 2 sand and a dirt, I got this in mixer(1500mbs of water and 500 mbs of concrete):
![F5X@6UMU6 0 `SRJ60LL5L3](https://user-images.githubusercontent.com/54445543/146583078-c3d88266-6e1d-44e2-8d8f-a40e6e1264fa.png)
This is not expected.
Logs show everything fine and clear.

**Comment by BluSunrize** [comment]
Ah, yes, that is more or less intended.

The mixer is designed to have its in- and output amounts of fluid be the same. It does not support having them differ, and it takes output as its measure.

**Comment by khjxiaogu** [comment]
This cause confuse because there's "amount" in mod data file and JEI show that value correctly.
