### ISSUE TITLE
Updating to latest ImmersiveEngineering-1.16.5-5.0.6-141 version causes twilight forest to crash

### ISSUE THREAD

**Issue by Jordan231111** [BluSunrize/ImmersiveEngineering#5126]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
Describe what happens, how it affects your game/gameplay and provide screenshots where possible.
Game crashed when launching latest 1.16.5 IE version (ImmersiveEngineering-1.16.5-5.0.6-141) with latest 1.16.5 twilight forest (Twilight Forest - MC 1.16.5 - 4.0.546) installed
### Crashlog:
If your Minecraft instance has crashed, a file will have been generated in the folder `crash-reports` of your minecraft folder. To understand what has happened, we need to know the content of that file. But please don't just put it directly in your report (that makes it hard to read), upload it to a site like [pastebin](http://pastebin.com) or [gist](http://gist.github.com) and put a link in the actuall bug report.
**https://pastebin.com/jd2LEB6M**

### Versions & Modlist
IE and Forge versions are mandatory. *Note that saying "latest" is **not** valid. Always give the proper version number*
Other mods should be listed (with their versions) in a [pastebin](http://pastebin.com) or [gist](http://gist.github.com) upload. The easiest way to get these lists is a crashlog, you may force one with F3+C.
If your game crashed (see above) you may omit the modlist, but IE and Forge version would still be nice.
latest forge and IE as of now
Also, please try testing an issue in a minimal instance, with just IE, Forge and maybe JEI. That makes elminating compat issues easier.

**Comment by Shibva** [comment]
Please Re-open this issue, I can confirm the same issue as well and you might have closed it by accident

**Comment by Jordan231111** [comment]
I have been told that there will be a fix from a twilight forest dev and not to bother IE

**Comment by Shibva** [comment]
ah, hope it gets released soon

**Comment by Jordan231111** [comment]
you can downgrade IE a version for now that fixes it

**Comment by ModernGamingWorld** [comment]
Update from one of the devs has been posted here, if they cant fix it that @BluSunrize may have to look into this
https://github.com/TeamTwilight/twilightforest/issues/1420

**Comment by BluSunrize** [comment]
*shrug*

Not our fault if Twilight Forest accesses an internal field. If it's not in the API, it's fair game for us to change it whenever we want to.
