### ISSUE TITLE
[1.18] Crash on opening Manual on Lectern

### ISSUE THREAD

**Issue by TeamSpen210** [BluSunrize/ImmersiveEngineering#5127]
### Description of the issue:
Placing a manual on a lectern works perfectly fine, but if you try right clicking it the manual GUI appears briefly, then the game crashes. This is reproduced in a minimal test world, in my real one JEI also ends up in the trace. Doing some digging, it looks like `openManual()` is being called serverside: 
https://github.com/BluSunrize/ImmersiveEngineering/blob/e632e679e8a579f695eafc75fe83aaddbc3246da/src/main/java/blusunrize/immersiveengineering/common/EventHandler.java#L356-L370

### Crashlog:
<https://gist.github.com/TeamSpen210/d0b3dbfa9a56e5a07e6ea508d6da1964>
I included both the crash report and game log because they have different tracebacks.

### Versions & Modlist
* MC: `1.18.1`
* Forge: `39.0.5`
* IE: `7.0.0-142`

**Comment by BluSunrize** [comment]
"Fixed" by https://github.com/BluSunrize/ImmersiveEngineering/commit/6fd2dfbff379a63347fc8c343fdf72f0cb1e40e6

But now the lectern just doesn't work with the manual. You can place it down, but not open it, because the item stored is not synced to the client.
