### ISSUE TITLE
[1.16.5] [5.0.5-140] No mineral deposits found with any tool

### ISSUE THREAD

**Issue by Fredric** [BluSunrize/ImmersiveEngineering#5129]
I have tried using the Survey tools and the Drill sampler but have not been able to find any minerals with either. Tested on approx 100 chunks spread out in different bioms.  Im running FTB Ultimate Anniversary version 1.16.5

**Comment by BluSunrize** [comment]
Did you add IE after the world was generated?
Because there is no retrogen for deposits.

Oh also, deposits do not use chunks. They are a point with a radius.

**Comment by Fredric** [comment]
The world was created after fresh install of ftb (using the FTBApp). So IE was in place when the world was generated.

**Comment by BluSunrize** [comment]
![image](https://i.imgur.com/BtyU231.png)

Survey tools work fine for me on Version 5.0.5-140.

Please try to narrow down your issue by testing in an instance with only IE installed.

**Comment by Fredric** [comment]
How would i go about testing this best?  Would there be/not be traces on different blocks within the same chunk? Is it evenly spread around the world? 

Also. Can i force regen of deposit in existing world?  I spent hundreds of hours in this survival game world. 😬

**Comment by BluSunrize** [comment]
Nope, there is no retro-gen for mineral deposits.

Steps you can try are:
1) Create a new world in that modpack, put yourself in creative mode, see if you can find some traces with the survey tools
If that *doesn't* work, then something in that modpack is breaking it.
2) Check that it works with just IE and no other mods enabled (it should that's what I tried)
3) Do a binary search:
  - Disable half the mods, create a world, see if the veins generated.
  - If they did, then the issue is caused by something in the disabled half.
  - If they didn't the issue is in the active half.
  - Keep halving until you find the mod conflict.

**Comment by Fredric** [comment]
Thanks.  I will test this. The only way to disable mods is to move them out from the mods folder so ill do that. 

What did you mean with point 3. Binary search?

Could you advice on how to quickly know if the deposits are there?  How many survey tools actions is typically needed to know if they are rendered or not?

EDIT. Nevermind.  Having only IE as mod instantly showed with the survey tool.  Will get back with details on what ia breaking it.

**Comment by Fredric** [comment]
It boils down to this `kubejs-forge-1605.3.19-build.229.jar`  file.

When this is in the mods folder it does'nt render deposits when creating the world. 

One other observation when having this mod included is a warning when creating a new world about "experimental" mode. 

![8F47C13B-B810-48C6-A511-1684956716FF_1_105_c](https://user-images.githubusercontent.com/437287/147118288-d6e4e30f-be1c-4f35-b3fa-736f87b1608b.jpeg)

**Comment by BluSunrize** [comment]
Binary search is exactly what I described btw.: You keep halving your modlist until you find it. Takes log2(n) attempts, where n is the number of mods in your list.

And of fucking course it is KubeJS *again*. That mod has broken recipe & datapack loading like 20 times now. I don't understand why people still use it, tbh.

**Comment by Fredric** [comment]
Ok. Thanks for the explanation. I'm a bit confused about if this should be reported to the FTB entity. Seems like they would have some interest in the coexistence of packades since they are packaged together in their release.

**Comment by BluSunrize** [comment]
Oh yeah, you should definitely tell them about this. They should try to find a version of KubeJS that doesn't break stuff...

**Comment by Fredric** [comment]
It is reported now
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/495

**Comment by LatvianModder** [comment]
> And of fucking course it is KubeJS again. That mod has broken recipe & datapack loading like 20 times now. I don't understand why people still use it, tbh.

Thank you for the useful feedback, as always, Blu 😛

**Comment by BluSunrize** [comment]
> > And of fucking course it is KubeJS again. That mod has broken recipe & datapack loading like 20 times now. I don't understand why people still use it, tbh.
> 
> Thank you for the useful feedback, as always, Blu 😛

I'd be nicer if this hadn't happened so many times and people kept blaming me for it ;)

**Comment by MaxNeedsSnacks** [comment]
I've nailed down the specific issue for this case, someone added the mineral veins to removed features for whatever reason (so this wasn't even a KubeJS issue, but a layer 8 issue :p)
