### ISSUE TITLE
[1.18.1] [Suggestion] Add option for reconfiguring or recycling Logic Circuits

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#5130]
Currently Logic Circuits quickly become garbage when changing up logic or making an error in defining the IO colors.
Because of the amount of possible combinations, reusing an old circuit is a very rare possibility and keeping and looking through the accumulated old hardware makes it more trouble than it is worth.
So, an option to either reconfigure the IO colors or recycling the whole circuit would be a nice thing to have over just throwing them out.

**Comment by BluSunrize** [comment]
Added in build 144 =)
