### ISSUE TITLE
[1.16.5] [Visual bug] Preheater rendering bug when better biome blend is installed

### ISSUE THREAD

**Issue by Vapaman** [BluSunrize/ImmersiveEngineering#5131]
### Description of the issue:
When better biomeblend is installed, the preheaters fan is rendered as mining drills
![2021-12-21_21 30 51](https://user-images.githubusercontent.com/77460466/146987101-1da801b9-6683-4dda-8c1b-3375f96ea74f.png)
Before the update in version 5.0.4 the fans rendered fine. This is obviously related to the implementation of the spinning animation.
### Versions & Modlist
forge-1.16.5-36.2.22-universal.jar
ImmersiveEngineering-1.16.5-5.0.6-141.jar
betterbiomeblend-1.16.4-1.2.9-forge.jar

**Comment by BluSunrize** [comment]
Okay, that's actually pretty funny.
