### ISSUE TITLE
[1.16.5] NBT tags don't work

### ISSUE THREAD

**Issue by BazZziliuS** [BluSunrize/ImmersiveEngineering#5132]
NBT tags don't work
It either prohibits all multistructures or allows all multistructures
You cannot prohibit a specific structure

**Here's what I use**
- <item:immersiveengineering:hammer>.withTag({multiblockInterdiction: ["IE:Excavator", "IE:ExcavatorDemo"]})
- <item:immersiveengineering:hammer>.withTag({multiblockPermission:["IE:Excavator", "IE:ExcavatorDemo"]})

ImmersiveEngineering-1.16.5-5.0.5-140
Forge 36.2.8

**Full list of mods**
https://pastebin.com/QaeYhzpS

In general, I should be prohibited from making an excavator
Help

_An incorrect translation of the RU text is used there_

**Comment by malte0811** [comment]
You're using the wrong names for the multiblocks, for the excavator you need `{multiblockInterdiction: ["immersiveengineering:multiblocks/excavator"]}`
