### ISSUE TITLE
[1.18.1] [Suggestion] Make the Blast Furnace Fuel amount in JEI show the number of items smelted instead of the duration

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#5136]
This would be in line with the regular fuel display
![grafik](https://user-images.githubusercontent.com/7753414/147040076-8e1c449a-058a-49ee-9747-6fe489950ce4.png)
![grafik](https://user-images.githubusercontent.com/7753414/147040088-f8970dbb-fca1-4a96-b326-7012cfe1b354.png)

**Comment by BluSunrize** [comment]
Yeah because the vanilla furnace smelts everything in 10 seconds. IE's blast furnace has variable times. A block of steel takes 9 times as long as a single ingot.

**Comment by MalkContent** [comment]
Ah crud. Forgot about that. My bad!

**Comment by MalkContent** [comment]
reopening this because I have an alternative suggestion:
make the blast furnace recipes display their duration
that way the time display would be more informative
