### ISSUE TITLE
[1.18.1] Revolver renders darker in hand than expected

### ISSUE THREAD

**Issue by BluSunrize** [BluSunrize/ImmersiveEngineering#5138]
Maybe it's just my eyes deceiving me, but it definitely looks darker:

![image](https://i.imgur.com/fKYi7uY.png)

Railgun looks fine on the other hand, so maybe it's something to do with the tris/quads fix you had to do?

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/647c5af8a02827b6289445b4dae3b2fe0de06d4e
