### ISSUE TITLE
Assembler issues

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#514]
I have been playing around with the assemblers and have come across a few issues. 

1. Players can stack Assemblers
 * If several Assemblers are placed one after another without spaces inbetween, all available crafting opperations along that chain will execute simultaneously
 * Not sure if this is a feature or a glitch, @BluSunrize?

Example: I have a setup with three assemblers, each take the input of the previous to craft with:
![image](https://cloud.githubusercontent.com/assets/3110986/10560924/2fdd236e-74ce-11e5-9337-e0bb286fa542.png)
First and third assemblers
![image](https://cloud.githubusercontent.com/assets/3110986/10560930/487c3982-74ce-11e5-8ce8-3da33bc994d2.png)
second assembler
![image](https://cloud.githubusercontent.com/assets/3110986/10560934/5a785cb0-74ce-11e5-88b2-7d3a11b11b6e.png)
If I provide one enderium ingot to the first one, the enderium nuggets immediately output from the third assembler. I expected at least a noticeable delay as the output of the first Assembler must be transferred to the second, then that to the third. the transfer should be quicker than it currently is.

 [2] It appears the assemblers are munching on items.
  * With the same setup as above, i provided 63 Enderium nuggets to the first assembler and let it loop a few times. After several itterations, I lost enderium nuggets. To be exact, one itteration I lost one nugget. (total of 62 recovered) And no, its not on the ground or stuck in one of the machines, its just lost. After a second iteration two nuggets were lost. and the total nuggets lost appears to rise with every iteration :/
  * This also occurs with vanilla ingots\nuggets

IE 0.6.0_pre build 1f5d0aa

PS, can we please get an option to disable redundant crafting within one assembler (like I am doing above)?

**Comment by BluSunrize** [comment]
1: The only reason it appears instant to you is because you managed to stack their ticks. The three internal recipes of an assembler are supposed to happen after eachother and then the output is moved to a valid inventory. Another Aseembler is a valid inventory and if it ticks immediately after the first one, it'll appear instant to you.

2: I'll need to look into that one, no idea what would cause that.

**Comment by theunkn0wn1** [comment]
for my first issue, could you please change it to the items move over their output conveyor rather to the valid inventory directly outside the output? It would be really cool to see items flowing from one assembler over they conveyors to the next one without magically jumping a half of a meter before rendering.
If i were to place two conveyors (non-MB structure ones) between assemblers I would only see the item half-way though the first conveyor, appearing out of thin air. perhaps spawn the item onto the output conveyor of the Assembler's structure would improve immersion?

**Comment by malte0811** [comment]
The second issue (items disapearing) is not caused by the assembler, it is caused by the conveyor belts. I have been able to reproduce it using a TD itemduct+servo set to extract 9 items at a time in place of an assembler. Quick debugging shows that `setInventorySlotContents` is getting called on the conveyor as expected, I am looking into this now.

**Comment by BluSunrize** [comment]
Found the issue. All it needed was a clientside check.

**Comment by malte0811** [comment]
Yes, but not there. Conveyors are voiding items when inserting into chests as well, but not with my commit referenced above. With your commit transferring 9 stacks with an TD servo with extraction rate of 9 via a conveyor belt into a chest loses about 1 stack of items, with my commit, no items are lost

**Comment by BluSunrize** [comment]
well I did not see your commit until now. Feel free to PR.
