### ISSUE TITLE
[Backport to 1.16.5] Processing JEI Pages Animations

### ISSUE THREAD

**Issue by khjxiaogu** [BluSunrize/ImmersiveEngineering#5142]
### Description of the issue:
JEI pages of machines such as Alloy Klin, Coke Oven and Blast Furnace have no fire animation and processing animation. Adding these animations would make JEI pages look much better and more vivid. Also indicates that fuel is required to do operation.

**Comment by khjxiaogu** [comment]
Maybe also implement this in 1.16.5?

**Comment by BluSunrize** [comment]
Hmm, fair enough.
