### ISSUE TITLE
 water wheel is not working! what is problem !! sorry for not good grammar !!!! ))

### ISSUE THREAD

**Issue by TTjohnTT1234** [BluSunrize/ImmersiveEngineering#5143]
The internal structure of the hydroelectric generator was perfectly used like YouTube or tutorial, and we kept checking and reassembling it. It does not flow with the message "0 flux electricity flows" as shown below. I don't know why this doesn't have electricity. (There's no problem with the internal structure)
![1](https://user-images.githubusercontent.com/96602588/147305253-8e6cd531-8c66-496d-8aec-1b304c2ce6e2.png)
![2](https://user-images.githubusercontent.com/96602588/147305258-3c2eedf3-35f4-4128-9fb9-524b292a2211.png)
![3](https://user-images.githubusercontent.com/96602588/147305259-d9dd65eb-a620-4afd-8ede-06873c23e02b.png)

Here's the blueprint for my hydroelectric turbine (it was built without mistakes, but it's been inspected several times).
![4](https://user-images.githubusercontent.com/96602588/147305506-da8e2cc5-0b13-4404-b337-ddd695fde47a.png)
!When I go into the electric cord, I wear sparks and electric shock damage.

**Comment by TeamSpen210** [comment]
How much power's in the capacitor? It could have filled up completely. Otherwise you might need to check those blocks inside the waterwheel region, make them slabs or the like so they're not fully solid.

**Comment by mindforger** [comment]
Also make sure to attach the wheel to the dynamo, not the dynamo to the wheel. Place the dynamo first

**Comment by BluSunrize** [comment]
Also maybe actually follow the issue template and tell us which version this is...?
