### ISSUE TITLE
[1.18.1] Building a Lightning Rod crashes the game

### ISSUE THREAD

**Issue by C1ffisme** [BluSunrize/ImmersiveEngineering#5144]
### Description of the issue:

Upon building the Lightning Rod, the game freezes and then crashes.

### Crashlog:

https://pastebin.com/LHB4wTeA

### Versions & Modlist

ImmersiveEngineering-1.18.1-7.0.1-144.jar
Forge 39.0.8

Other mods can be found in the crash report. However, upon testing with no mods but IE and JEI, the crash still occurs. The crash will also occur upon loading up the world after a crash, rendering a world unplayable.

**Comment by BluSunrize** [comment]
Oh dear!
Well best not to use a Lightning Rod until we get that fixed!
