### ISSUE TITLE
Banner Pattern Crash (1.18.1)

### ISSUE THREAD

**Issue by Hikcs** [BluSunrize/ImmersiveEngineering#5146]
Hello,

So, my game froze when i attempted to see how the "Wolf Banner Patter" design would look like. I just put the banner and when i put the pattern, the game froze and subsequently crashed.

I use Forge 39.0.8 and Minecraft 1.18.1.

I use few others mods too. They are world edit, Create and MrCrayFish Furniture & Gun-mod. I think it can be compatibality problem because of IE & create being similar, not sure.

Here is the copy of crash report: https://pastebin.com/QEHRxW5V

Thank You!

**Edit:** It crashes when using any banner pattern from IE mod.

**Comment by mindforger** [comment]
that is not the actual crash, try 
C:\Users\MANO-DILIP-NIK-RAM\AppData\Roaming\.minecraft\crash-reports\crash-2021-12-27_11.10.27-client.txt
Also try without optifine

**Comment by BluSunrize** [comment]
Yeah what Mindforger said. That's not a proper crash report, it tells us nothing.

Also please remove Optifine *first* to see if that resolve the issue. Because Optifine is not supported and we won't attempt to fix issues caused by it.

**Comment by Hikcs** [comment]
Hmm. Okay, I'll remove optifine & try tomorrow. I'll also send crash report asap. 
Thank You!

**Comment by Hikcs** [comment]
Crash Report: https://pastebin.com/qsJtVPsS

**Comment by BluSunrize** [comment]
That crash is with optifine. Please try and reproduce this without it.

**Comment by Hikcs** [comment]
It crashes without optifine also.

Crash Report: https://pastebin.com/NYrRYUg4
