### ISSUE TITLE
[1.18.1] Engineer's Manual: Wrong Spelling in Russian Language

### ISSUE THREAD

**Issue by Foraminiferatrv** [BluSunrize/ImmersiveEngineering#5150]
## Description:
When playing in Russian language I spotted a wrong spelled word in article about the Lightning Rod.

❌ In the book it's: "Гроотвод"
✅ It should be: "Громоотвод"

![image](https://user-images.githubusercontent.com/48618083/147654374-e0d59bfc-8161-4903-ba1e-cbf5b1fdf058.png)

p.s. I'm not sure if such a minor issue is worth a post but here it is. Sorry)

**Comment by BluSunrize** [comment]
Well I don't know a single word of Russian, so if you want this fixed, you have to submit a pullrequest.

All of IE's translations are maintained by community members that submit PRs.

**Comment by Foraminiferatrv** [comment]
Thanks for the info.
