### ISSUE TITLE
java.lang.NullPointerException: Feature placement (crash on chunk loading)

### ISSUE THREAD

**Issue by TOminerTV** [BluSunrize/ImmersiveEngineering#5153]
The game crashes everytime im in the near of a specific cunk. I dont know which block or item exactly causes the crash. I tried to remove 
ImmersiveEngineering and the chunks in the near of the crash location loaded without any error.

Here is a crash report with ImmersiveEngineering installed:
https://pastebin.com/jmDuvD0h

**Comment by BluSunrize** [comment]
Sorry, 1.15.2 is no longer supported.
