### ISSUE TITLE
[1.18.1] Sawmill visual bug it when finished processing

### ISSUE THREAD

**Issue by Zahkriiven** [BluSunrize/ImmersiveEngineering#5154]
### Description of the issue:
The sawmill animation is frozen when it finishes processing, leaving ghost logs behind.
Updating it like removing the sawblade would make them dissapear
![GIF 30-12-2021 14-47-03](https://user-images.githubusercontent.com/25531677/147757592-476b7501-945a-4362-9506-25fed235654c.gif)

### Versions & Modlist
ImmersiveEngineering-1.18.1-7.0.2-pre.35

**Comment by BluSunrize** [comment]
Clarification: The status of the process is not updated on the client at all.

A single log gets stuck at the start. Throwing a second one updates the first one to its serverside position.
