### ISSUE TITLE
1.16.5 Modded Server crash on startup

### ISSUE THREAD

**Issue by bulkasmakom1** [BluSunrize/ImmersiveEngineering#5155]
Server crashes on startup as title says. I`m playing on my server and started literally yesterday. Then i left the game and stopped server. Next day server just restarted again and again

IE version - 1.16.5-5.0.6-141
Forge - 36.2.22
Modlist in crash file or link below, because there are just too many 
https://www.curseforge.com/minecraft/modpacks/ragnamod-vi 
[crash-2021-12-30_03.03.49-fml.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/7794229/crash-2021-12-30_03.03.49-fml.txt)

**Comment by BluSunrize** [comment]
Does this happen on every launch, only occasionally?

**Comment by bulkasmakom1** [comment]
Every launch 
currently was trying to reinstall modpack, but didn`t help

**Comment by bulkasmakom1** [comment]
Maybe logs from server before restart can help? https://gist.github.com/bulkasmakom1/91276429eee405eba71d846e96de3e89

**Comment by bulkasmakom1** [comment]
after a couple of tries another mod became problem on server startup 
probably mod loader issues and not exactly IE
i guess i`ll look into that tomorrow
