### ISSUE TITLE
[Backport 1.16.5] Buzzsaw quiver does not display the stored blades.

### ISSUE THREAD

**Issue by Zahkriiven** [BluSunrize/ImmersiveEngineering#5158]
### Description of the issue:
The buzzsaw quiver does not display the stored blades.
![image](https://user-images.githubusercontent.com/25531677/147825981-5d4f8f53-4003-447f-be57-0a7c19a97ce8.png)
![image](https://user-images.githubusercontent.com/25531677/147825969-8fe5c2c0-e872-4333-aad4-2cd81d2f813c.png)
Bonus bug: Durability is not corretly displayed on the UI (kinda already mentioned here https://github.com/BluSunrize/ImmersiveEngineering/issues/5115)
![image](https://user-images.githubusercontent.com/25531677/147826001-756182c8-cfd7-4b7d-81fa-0ac44f856b12.png)

### Versions & Modlist
ImmersiveEngineering-1.18.1-7.0.2-pre.35

**Comment by BluSunrize** [comment]
![image](https://i.imgur.com/R1nI7uM.png)

Interesting, the quiver blades do render for me (though their one side is oriented the wrong way)

Also a shader seems to be breaking the render of the "rope":

![image](https://i.imgur.com/otbsS1g.png)

There's definitely work to be done here, but I can't reproduce your specific issue. Can you try this between singleplayer and server and see if there is an edgecase here?

**Comment by Zahkriiven** [comment]
Huh, indeed I get the same result as you in single player. The images above are from the test server.
I just noticed the first time you put the buzzsaw in and leave it be on the table, they are displayed. Reopening the table would make them disappear.
![image](https://user-images.githubusercontent.com/25531677/147841184-e0c1986b-e339-4751-9235-9342fae08b6a.png)
Bonus bug: 
![GIF 01-01-2022 0-41-51](https://user-images.githubusercontent.com/25531677/147841150-594100ae-26ec-45fd-9d17-28fd833d4716.gif)

**Comment by BluSunrize** [comment]
Leaving this open, because some of these fixes need to be backported

**Comment by BluSunrize** [comment]
Backport done
