### ISSUE TITLE
Thermopiles and TFC liquids

### ISSUE THREAD

**Issue by dexman545** [BluSunrize/ImmersiveEngineering#516]
IE's thermal generators do not seem to recognize TFC lava, nor TFC water (both the hot, fresh, and salt variants) for power generation. Could support be added for these liquids, or a config to allow modpack makers to configure them to work properly?

**Comment by BluSunrize** [comment]
My THermopile is supposed to work with any valid Forge Fluid. If TFC does not use those, I feel like you should take that up with its developer(s)

**Comment by 3TUSK** [comment]
Seems like it's on TFC end. TFcraft use thier own [`FluidBaseTFC`](https://github.com/Deadrik/TFCraft/blob/master/src/API/com/bioxx/tfc/api/TFCFluids.java) which is inherit from forge's `Fluid`, but by default [they do not change the `temperature`](https://github.com/Deadrik/TFCraft/blob/master/src/Common/com/bioxx/tfc/Core/FluidBaseTFC.java#L12-L14); however, IE's thermal generator will use that temperature value anyway.

**Comment by dexman545** [comment]
Just did a test with the latest TFC build, seems this issue is fixed.
