### ISSUE TITLE
[Backport 1.16.5] Manual does not fully update when changing language

### ISSUE THREAD

**Issue by malte0811** [BluSunrize/ImmersiveEngineering#5160]
Some entries stay in the language used before switching (even though translations exist). Seems to be "entries opened before switching", maybe with an addition of "partially code-defined entries".

**Comment by BluSunrize** [comment]
@malte0811 I was unsuccesful in picking this to 1.16.5
I need you to transfer this one.

**Comment by malte0811** [comment]
That would be because the bug isn't actually there on 1.16.5!
