### ISSUE TITLE
[Backport 1.16.5] Engineer's Circuit table does not drop its contents 

### ISSUE THREAD

**Issue by Zahkriiven** [BluSunrize/ImmersiveEngineering#5163]
### Description of the issue:
When the engineer's circuit table is broken its contents (backplanes, vacuum tubes and wires) don't drop and get voided.

### Versions & Modlist
ImmersiveEngineering-1.18.1-7.1.1-pre.4

**Comment by BluSunrize** [comment]
Fixed for 1.18, will need to check if this issue exists in 1.16

**Comment by BluSunrize** [comment]
Issue does not exist in 1.16.5
