### ISSUE TITLE
[Backport 1.16.5] Concrete Chunk Has Mismatched Collision

### ISSUE THREAD

**Issue by Alex33212** [BluSunrize/ImmersiveEngineering#5164]
**Description:**

Pretty simple: the Concrete Chunk block has a collison box that matches that of the Panel, rather than the visual volume of the Chunk block itself.

**Versions & Modlist:**

Forge 39.0.8
IE 1.18.1-7.1.0-145

Other mods:
AutoRegLib-1.7-52
ears-forge-1.18-1.4.3
furniture-7.0.0-pre27-1.18.1 (MrCrayfish's furniture mod)
jei-1.18.1-9.1.1.48
mcw-doors-1.0.5-mc1.18.1
mcw-paintings-1.0.2-mc1.18.1
mcw-windows-2.0.2-mc1.18.1
OptiFine_1.18.1_HD_U_H4_MOD
Quark-3.0-334
worldedit-mod-7.2.8
Xaeros_Minimap_21.22.6_Forge_1.18
XaerosWorldMap_1.18.9_Forge_1.18

**Comment by BluSunrize** [comment]
Fixed for 1.18, will need to check if this issue exists in 1.16

**Comment by BluSunrize** [comment]
Issue does not exist in 1.16.5
