### ISSUE TITLE
[1.12.2] Metal press not consuming items visually

### ISSUE THREAD

**Issue by splyfof** [BluSunrize/ImmersiveEngineering#5166]
### Description of the issue:
When you throw 2 or more items onto the metal press it will take them as it should but it looks like the whole stack still is there

### Versions & Modlist
![java_xwwdHnIWkS](https://user-images.githubusercontent.com/83120236/148088359-454d69b7-2853-4080-9092-78b4e2b2572d.png)
should be default divine journey 2 mods but heres a list anyways https://pastebin.com/0tstVHYq

i tried to upload a vid but couldnt cause to big so heres the yt link https://youtu.be/cAKrny4jw7I

**Comment by BluSunrize** [comment]
1.12 went out of support 19 months ago.
