### ISSUE TITLE
[1.18.1] Faraday suit cannot be enchanted in the enchanting table but accepts books in an anvil

### ISSUE THREAD

**Issue by Zahkriiven** [BluSunrize/ImmersiveEngineering#5167]
### Description of the issue:
To me this looks like an inconsistency. It should not be enchantable at all or it should be enchantable in the enchanting table.

![image](https://user-images.githubusercontent.com/25531677/148238267-65082bb0-3035-4d72-a007-58511b84985e.png)
![image](https://user-images.githubusercontent.com/25531677/148238472-3481fc59-22fd-4b04-87eb-d3c72455fa71.png)
![image](https://user-images.githubusercontent.com/25531677/148238303-b6974b72-ed64-4d23-9bfc-70ab7b1c8b4d.png)

### Versions & Modlist
ImmersiveEngineering-1.18.1-7.1.1-pre.19

**Comment by voidsong-dragonfly** [comment]
Are you in creative or survival @Zahkriiven ? Creative bypasses a lot of random restrictions and that may be the cause of the anvil working here.

**Comment by Zahkriiven** [comment]
Survival, that's the test server.

**Comment by voidsong-dragonfly** [comment]
Cool, good to know. Been a fair few "hey this can be enchanted" -> "wait only in creative" things that have happened, so just wanted to check.
