### ISSUE TITLE
[1.12.2] Disabling animation crusher

### ISSUE THREAD

**Issue by Quincklyen** [BluSunrize/ImmersiveEngineering#5168]
Hello everyone, the question is that when the crusher is working for me, that is, the animation is activated, then the FPS starts to drop dramatically, and when I turn it off, everything returns to normal, how can I turn off the animation of the crusher, if possible?

**Comment by BluSunrize** [comment]
Nope, you can't, sorry.

Support for 1.12 was ended 19 months ago.
