### ISSUE TITLE
[1.16] Mekanism transporters unable to feed a silo

### ISSUE THREAD

**Issue by Kowagirl** [BluSunrize/ImmersiveEngineering#5174]
### Description of the issue:
Connecting a Mekanism logistical transporter to the top of a silo does not feed items into it. Connecting the same transporter to  a hopper above the silo, works as expected (transporter fees hopper, hopper feeds silo).

### Versions & Modlist
Forge 36.2.22
IE 1.16.5-5.0.7-143
Mekanism 10.1.0

Running on Valhelsia 1.16.5 - 3.4.8

**Comment by BluSunrize** [comment]
Sounds to me like a mekanism issue, if it works just fine with vanilla methods and IE's own conveyors...

**Comment by malte0811** [comment]
Nah, this is actually a bug in IE. Forge's contract for `isItemValid` is a bit weird, and I think Mek may be relying on people actually following that contract (at least pup shouted at someone else about this recently). Can you check if this is only a problem for empty silos and not when attaching a logistical transporter to a partially filled silo?

**Comment by Kowagirl** [comment]
> Can you check if this is only a problem for empty silos and not when attaching a logistical transporter to a partially filled silo?

Yes, I tried with both an empty silo, as well as a silo with one of the item in it.

**Comment by BluSunrize** [comment]
Closing this because support for 1.16.5 has ended
