### ISSUE TITLE
[1.18.1] Charging Station Max Output Capped At 257 Flux/t

### ISSUE THREAD

**Issue by Rarvey** [BluSunrize/ImmersiveEngineering#5175]
The wiki says the charging station can output 4000 Flux/t, but even when I directly connect an HV capacitor to the station with HV connectors and wires, it never charges items above the rate of 257 Flux/t.

IE Ver: 1.18.1-7.0.0-142
Forge Ver:  1.18.1-39.0.5

Thank you.

**Comment by BluSunrize** [comment]
The wiki is absolutely wrong then. Which makes sense, because IE has no official wiki. So whoever wrote that is spreading misinformation.

The Charging Station is configured to charge at a rate of 256 FE/t.
