### ISSUE TITLE
[1.18.1] no minerals on pre-discovered chunks before adding the mod

### ISSUE THREAD

**Issue by Sh4itan** [BluSunrize/ImmersiveEngineering#5177]
### Description of the issue:
i've added IE after launching my server, for i discovered there was no possibility to get power in my current modpack. now i do not find any mineral deposits in my chunks that were generated before i added the mod to the server. is there any way to get those chunks to like... re-generate just the deposits? or am i just super unlucky and don't find any mineral deposits as they should be there?

### Crashlog:
no crashes, just no mineral deposits in old chunks.

### Versions & Modlist
IE: 1.18-7.1.0-145
forge: 39.0.9
modpack: Create on a Potato

**Comment by BluSunrize** [comment]
Nope, that's how it is.
There is no retrogen for mineral deposits.
