### ISSUE TITLE
[1.18.1] Mixin apply failed

### ISSUE THREAD

**Issue by akayumeru** [BluSunrize/ImmersiveEngineering#5178]
Hello! I have a problem with adding Immersive Engineering as a dependency. Stacktrace: https://pastebin.com/i03jvvfZ

I manually found `public int getRemainingFireTicks()` at `net.minecraft.world.Entity`, but Minecraft does not see it.

Used version of IE and JEI:
```groovy
implementation fg.deobf("blusunrize.immersiveengineering:ImmersiveEngineering:1.18.1-7.1.0-145")
implementation fg.deobf("blusunrize.immersiveengineering:ImmersiveEngineering:1.18.1-7.1.0-145:datagen")
compileOnly fg.deobf("mezz.jei:jei-1.18.1:9.2.1.69:api")
runtimeOnly fg.deobf("mezz.jei:jei-1.18.1:9.2.1.69")
```

**Comment by malte0811** [comment]
I can't access the paste, at a guess: You're missing [these](https://github.com/BluSunrize/ImmersiveEngineering/blob/064b3469e0c3e0953c8f335c9576d0cb576bb78e/build.gradle#L111-L112) lines in your `build.gradle` (after you add them you need to regenerate the run configs for your IDE). If that isn't the issue, please upload the stacktrace to https://gist.github.com or try to figure out why pastebin thinks your original paste "is a private paste or is pending moderation".

**Comment by akayumeru** [comment]
Sorry, misclicked, pastebin is public now. Tried to add these lines, it doesn't help.

**Comment by malte0811** [comment]
Can you test with `ImmersiveEngineering-1.18.1-7.1.1-pre.41`? That accessor Mixin wasn't even necessary any more, so I just removed it.

**Comment by akayumeru** [comment]
That time same error, but with ServerWorldMixin. [Pastebin](https://pastebin.com/aEwq9AwJ)

**Comment by XFactHD** [comment]
Can you pastebin your build.gradle? My guess is that the error is in there

**Comment by akayumeru** [comment]
Made my mod`s repo public [here](https://github.com/LazyTechwork/nuclearengineering/blob/master/build.gradle)

**Comment by XFactHD** [comment]
You are missing these two lines in your build.gradle: https://github.com/BluSunrize/ImmersiveEngineering/blob/064b3469e0c3e0953c8f335c9576d0cb576bb78e/build.gradle#L111-L112.
They are needed to counteract the refmap in the built JARs and rename the method and field names used in the mixins back to the readable names used in your dev environment. You need to regenerate the runs after adding these lines

**Comment by akayumeru** [comment]
Not helped. I tried this several comments ago.

**Comment by XFactHD** [comment]
I just cloned your repo and set up the environment and I can't reproduce the issue with these two lines added to the build.gradle. If I remove those two lines, it crashes as expected.
Going to reiterate on this: You must reload the gradle project (IDEA shows you a button for that in the editor after modifying the build.gradle, no idea how this is done in Eclipse), then regenerate the run configs for your IDE and make sure to use those generated IDE run configs and not the `run<Thing>` gradle tasks.

**Comment by akayumeru** [comment]
Well, I cleaned project and built again and it ... works, thanks a lot!

**Comment by HalfP1e** [comment]
Thank you so much! That **two lines** actually fixed the problem for which I have been searching the whole afternoon. Now I am happy and relaxed to have my dinner!

**Comment by MC-Mods-Pete** [comment]
Same here, thank you so much for those two lines :)
