### ISSUE TITLE
Pre 1.17 (1.16.5) Raw ores from mods won't process

### ISSUE THREAD

**Issue by MsVella** [BluSunrize/ImmersiveEngineering#5179]
### Before reporting:
[Only 1.17 reports]

### Description of the issue:
Raw Ores from mods like 'OreClumps' and 'All of Deepslate' have no ability to be processed with IE machines such as the crusher or arc furnace.

### Crashlog:
[None]

### Versions & Modlist
Game Version: 1.16.5
Forge Version: v36.2.22
IE Version: 5.0.7-143
Full Modlist in Crash Format: https://gist.github.com/MsVella/c924397e7476472ba68ef9e69412fdcc

**Comment by BluSunrize** [comment]
Yeah because vanilla minecraft didn't add raw ore in 1.16.5, so we didn't add support for it, and I see no reason to either.

The concept was added in 1.17, which is when we added it to IE as well.
