### ISSUE TITLE
Client crash after attempting to Create Multi-block structure with Engineering Hammer 1.18.1

### ISSUE THREAD

**Issue by figori** [BluSunrize/ImmersiveEngineering#5180]
Whenever attempting to finalize a multi-block structure, the client will crash.  This was on a server running All The Mods 7 v0.2.25 (MC 1.18.1)

See crash log below.

Thank you.

https://pastebin.com/5042ZFvL

https://github.com/AllTheMods/ATM-7/issues/266

**Comment by figori** [comment]
ATM 7 updated, and still having the same issue.

https://pastebin.com/fN2zm0eL

**Comment by BluSunrize** [comment]
> java.lang.NullPointerException: Cannot read field "scriptManager" because "dev.latvian.mods.kubejs.server.ServerScriptManager.instance" is null

Report to KubeJS, like so many other things...
