### ISSUE TITLE
[1.16.5] Garden cloche ignores/breaks after using other than vanilla redstone

### ISSUE THREAD

**Issue by Bellwar** [BluSunrize/ImmersiveEngineering#5181]
### Description of the issue:
Lever disables it fine. Xnet connector is ignored all together. Red alloy wire connected as a lever and applying signal breaks the machine. The particles on top get stuck as if it is turned off. The GUI stops updating while being open (closing opening updates the numbers). Items still drop. After playing with it I got it to a point where even after turning the redstone off the crops were still growing yet after harvesting it dropped nothing. Had to destroy and place again the whole cloche.

Edit: In both clean instance and ATM instances Xnet connector can't stop the rendering and updating at all. Everything looks like it's growing and harvesting but it doesn't drop anything after harvesting. So it actually stops the process and disables the machine. 

![image](https://user-images.githubusercontent.com/9407653/149502455-ad33c8bb-3053-4cee-8155-40cbd16ab464.png)

### Versions & Modlist
IE: 1.16.5-5.0.7-143 
Forge: 36.2.22
All the mods 6 (version 1.8.17)

Tested on an instance: IE, Forge, Xnet, Project red... Works fine. It means there is something destroying the events or handling of blocks... :( Any idea for a fix? I don't have time for big debugging and you neither... But maybe if you can pick me a mod or two that might be doing it? (from the ATM 6 modlist) Tested it even with FTB Chunks. Force loading from that doesn't do it.

**Comment by BluSunrize** [comment]
Closing this because support for 1.16.5 has ended
