### ISSUE TITLE
[1.16.5] Custom Engineer's Workbench Blueprint?

### ISSUE THREAD

**Issue by drago87** [BluSunrize/ImmersiveEngineering#5182]
Is there a way to create a custom blueprint for the Engineer's Workbench?
I tried the datapack way bu making a json file in the `\data\immersiveengineering\recipes\blueprint` named silicon.json

and the content of the file

`{
  "type": "immersiveengineering:blueprint",
  "inputs": [
    {
      "item": "kubejs:silicon_compound"
    },
    {
      "item": "kubejs:ice_charge"
    }
  ],
  "category": "silicon",
  "result": {
    "item": "appliedenergistics2:silicon"
  }
}`

also tried with vanilla items aif there is some problem with kubejs created items.

or is it possible to do with kubejs or crafttweaker?
### Versions & Modlist
ImmersiveEngineering-1.16.5-5.0.7-143

**Comment by BluSunrize** [comment]
@malte0811 might have to correct me on this, but last I remember it is currently not possible to add custom categories of blueprints.
You can only add or remove recipes from the existing blueprints added by IE.

**Comment by EddwardR** [comment]
Could this be something to be added in the future? Would give tons more flexibility to modpack authors when it comes to integration. Could be handled via datapacks or even leaving a hook in the API for something like KubeJS or CraftTweaker to do IMC messages.

**Comment by BluSunrize** [comment]
Not really, because items are added at mod construction. Datapacks are loaded with the world (or when joining the server), at which point items can't be added anymore.

**Comment by LilJagty** [comment]
Is this still the case? I'd love to add my own blueprint and category.

**Comment by BluSunrize** [comment]
I think it's possible again in 1.19, but not before that.
Please ask this question on discord next time, instead of posting on a closed issue.
