### ISSUE TITLE
question about the industrial squeezer and fermenter

### ISSUE THREAD

**Issue by ytrugibrejhnklhath** [BluSunrize/ImmersiveEngineering#5184]
I was playing Sevtech ages the other day and I realized that the squeezer and fermenter from immersive engineering have a slot at the bottom left of their gui and I was wondering if it had a purpose, because if it was some speed modifier that goes in there it would save me making two more machines to automate enough biodiesel for 3 engines

![2022-01-15_19 00 17](https://user-images.githubusercontent.com/97813159/149642083-4902cba8-0fb8-4c3a-b6e3-31d803a2aabc.png)
it is the slot above the buckets and the iron casing

**Comment by TeamSpen210** [comment]
No, Immersive Engineering doesn't have speed upgrades or that sort of thing (aside from the upgrades on tools). That's an item output slot used in certain recipes. It's used for the HOP Graphite Ingot recipe, for graphite electrodes - doesn't seem to be any default fermenter recipes, but that could be added by datapack.

To increase speed, the intended method is building more machines.

**Comment by BluSunrize** [comment]
Yep, what Spen said!

**Comment by ytrugibrejhnklhath** [comment]
> No, Immersive Engineering doesn't have speed upgrades or that sort of thing (aside from the upgrades on tools). That's an item output slot used in certain recipes. It's used for the HOP Graphite Ingot recipe, for graphite electrodes - doesn't seem to be any default fermenter recipes, but that could be added by datapack.
> 
> To increase speed, the intended method is building more machines.

thx for responding so fast, I'm just very unfamiliar w this mod and had no idea what its purpose was
