### ISSUE TITLE
[1.16.5+] Suggestion: Shader Toolboxes

### ISSUE THREAD

**Issue by Shibva** [BluSunrize/ImmersiveEngineering#5185]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:

as it should be a bit obvious by now, there is no issue, but just a feature suggestion, I mean, shaders are neat and can be added to other things that you make through this mod, but why not the toolbox, I mean it would make sense for the user to give some personal flair to their lil toolbox, and why not give it some things you can add to it as upgrades like if you put the maintenance kit inside of it on the main workbench, you could use it to adjust things within the toolbox just by opening up a GUI inside of its toolbox gui

### Versions & Modlist
IE and Forge versions are mandatory. *Note that saying "latest" is **not** valid. Always give the proper version number*
None really, well not necessary for this report anyway but I will for the sake of it
IE; ver 1.16.5 - 5.0.7-143

**Comment by BluSunrize** [comment]
Not doing this simply because of the amount of effort required to create all those textures for the toolbox.
