### ISSUE TITLE
[1.18.1] Wires disappear after getting killed

### ISSUE THREAD

**Issue by Zahkriiven** [BluSunrize/ImmersiveEngineering#5186]
### Description of the issue:
Wires disappear after getting killed. Reloading the chunk will make them show again
Reproduced only in the server, not in single player.

### Versions & Modlist
ImmersiveEngineering-1.18.1-7.1.1-pre.45

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/5dba0864d4b6014e14e486a881ab11f0faf83f55
