### ISSUE TITLE
[1.18.1] HV transformers automatically mirror when hv wires are attached 

### ISSUE THREAD

**Issue by EvergreenSystems** [BluSunrize/ImmersiveEngineering#5188]
### Description of the issue:
When a HV wire is connected first to a HV relay and then to a HV transformer, it causes the transformer to orient to its mirrored orientation. This does not happen if the wire is first connected to the transformer and then to the relay, nor does it happen with other wires (MV or LV).

https://user-images.githubusercontent.com/23658767/150393113-531d3289-afd5-431f-8eb8-0c5ab9300fde.mp4

### Crashlog:
N/A

### Versions & Modlist
Forge version: 39.0.9
IE version: 1.18.1-7.1.0-145

Modlist: https://gist.github.com/Shedao-Shai/d86e56d3d5d1bbd6c93594aed4e5dab4

Tested with IE on its own, issue does persist so it is not a conflict with another mod.

IE is awesome, and y'all are awesome

**Comment by EvergreenSystems** [comment]
Upon a bit of further testing the mirror can still happen if the hv wire is attached transformer -> relay, but it will not happen period if another wire (mv/lv) is already attached to the transformer.

**Comment by voidsong-dragonfly** [comment]
This ONLY happens for me with transformers with the `north` facing. Can you confirm @Shedao-Shai ? As well, it only happens if the player is NOT facing EAST and perfectly in-line with the connector (head at connector level, basically perfect east)
