### ISSUE TITLE
[Enhancement] Support For Forestry Ethanol In Refinary

### ISSUE THREAD

**Issue by mikeloeven** [BluSunrize/ImmersiveEngineering#519]
Can you add support for Forestry Ethanol generally speaking when it comes to fuels and liquids there seems to be alot of duplication and no fluid oredict as of yet

**Comment by mindforger** [comment]
this has already been discussed and revoked 
https://github.com/BluSunrize/ImmersiveEngineering/issues/199
you can use the github search to check ahead :)

**Comment by JRgames** [comment]
What about just using forestry-ethanol in the diesel generator?

**Comment by mindforger** [comment]
i see the DieselHandler is part of the API but i do not find any hints it's MineTweakable in any means!? 
@BluSunrize can you make it MineTweakable ?

**Comment by BluSunrize** [comment]
I don't want to, really. Kinda tired of minetweaker. Gimme a week to recover or so .-.

**Comment by mindforger** [comment]
sure, just fair :D
