### ISSUE TITLE
[1.16] Mixer using 100% of thread

### ISSUE THREAD

**Issue by Magi1053** [BluSunrize/ImmersiveEngineering#5190]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
Just to test the mixer I built one and turned it on, using the recipe redstone and water. I didn't immediately notice an issue, but after leaving it on overnight and coming back to it in the morning I noticed that the server thread was at 100% and the TPS was at ~10/20. Turning the mixer off with redstone immediately fixed the issue, and turning the mixer back on again resulted in the same issue

### Report:
https://spark.lucko.me/2MmyjpGqLN)

### Versions & Modlist
forge-1.16.5-36.2.23-installer.jar
AEInfinityBooster-1.16.5-1.0.0+4.jar
AI-Improvements-1.16.5-0.4.0.jar
AdditionalEnchantedMiner-1.16.5-16.1.11.jar
Aquaculture-1.16.5-2.1.21.jar
Architects-Palette-1.16.4-1.1.4.jar
AxesAreWeapons-1.5.1-forge-1.16.5.jar
Better+Muffling-1.16.3-1.0.4.jar
BetterAdvancements-1.16.5-0.1.1.115.jar
BetterBurning-1.16.5-6.0.7.jar
BetterFurnacesReforged-1.16.5-1.7.3.jar
Botania-1.16.5-420.2.jar
CBMultipart-1.16.5-3.0.4.123-universal.jar
Chargers-1.16.5-3.1.2.9.jar
Chisel-MC1.16.5-2.0.1-alpha.4.jar
ChunkNoGoByeBye-1.16.5-1.3.0.jar
Cinderscapes-Reforged-1.0.3.jar
Clumps-6.0.0.27.jar
CodeChickenLib-1.16.5-4.0.6.443-universal.jar
Desolation+1.1.2+1.16.5.jar
DungeonCrawl-1.16.5-2.3.5.jar
Dynmap-3.2.1-forge-1.16.5.jar
EnderStorage-1.16.5-2.8.0.168-universal.jar
Exchangers-1.16.5-3.0.2.jar
ExtremeReactors2-1.16.5-2.0.38.jar
FabricBiomeApiReforged-1.0.5.jar
FarmersDelight-1.16.5-0.5.4.jar
FastLeafDecay-v25.2.jar
FastWorkbench-1.16.5-4.6.1.jar
GunpowderLib-1.16.5-1.2.2.jar
ImmersiveEngineering-1.16.5-5.0.7-143.jar
ImmersiveIndustry-1.16.5-0.1.6b.jar
ImmersivePetroleum-1.16.5-3.3.0-11.jar
JustEnoughResources-1.16.5-0.12.1.133.jar
Mantle-1.16.5-1.6.152.jar
MoreObservers-1.4.1-MC1.16-Forge.jar
Morpheus-1.16.5-4.2.70.jar
NaturesCompass-1.16.5-1.9.1-forge.jar
NetherPortalFix_1.16.3-7.2.1.jar
OpenLoader-1.16.5-9.0.3.jar
OreTweaker-1.16.5-2.6.0.jar
Patchouli-1.16.4-53.2.jar
PathToDirt-1.2.0-mc1.16.x.jar
Placebo-1.16.5-4.6.1.jar
PrettyPipes-1.9.5.jar
ProjectRed-1.16.5-4.11.0-beta-6-core.jar
ProjectRed-1.16.5-4.11.0-beta-6-illumination.jar
ProjectRed-1.16.5-4.11.0-beta-6-integration.jar
ProjectRed-1.16.5-4.11.0-beta-6-transmission.jar
RealisticTorches-1.16.5-3.1.2.jar
Rubber_Duck-1.16.5-2.0.0-beta.jar
ScalableCatsForce-2.13.5-build-2-with-library.jar
Scorge-3.1.3.jar
SimplyJetpacks2-1.16.5-2.6.11.2.jar
Space-BossTools-1.16.5-5.5e.jar
Space-BossTools_Giselle_Addon-1.16.5-1.9.jar
SpawnerFix-1.16.2-1.0.0.2.jar
StorageDrawers-1.16.3-8.5.1.jar
TConstruct-1.16.5-3.3.2.324.jar
Terrestria-Reforged-1.0.2.jar
TravelersBackpack-1.16.5-5.4.6.jar
WaterStrainer-1.16.3-10.0.0.jar
Waystones_1.16.5-7.6.4.jar
ZeroCore2-1.16.5-2.1.9.jar
abnormals_core-1.16.5-3.3.1.jar
ae2extras-1.3.1-1.16.5.jar
appleskin-forge-mc1.16.x-2.2.0.jar
appliedenergistics2-8.4.7.jar
archers_paradox-1.16.5-1.4.0.1.jar
architectury-1.28.48.jar
betterendforge-1.16.5-2.5.jar
betternether_reforged-1.2.jar
bwncr-1.16.5-3.10.16.jar
cavebiomeapi-1.16.5-1.4.2.jar
cc-tweaked-1.16.5-1.100.2.jar
cfm-7.0.0pre22-1.16.3.jar
chiselsandbits-1.0.63.jar
cloth-config-4.13.49-forge.jar
cobblegenrandomizer-1.16-5.1.2.jar
cofh_core-1.16.5-1.4.1.8.jar
collective-1.16.5-3.8.jar
configured-1.5.1-1.16.5.jar
connectivity-2.4-1.16.5.jar
constructionwand-1.16.5-2.6.jar
cookiecore-1.16.5-3.3.1-9c789ef.jar
crashutilities-3.13.jar
create-mc1.16.5_v0.3.2g.jar
createaddition-1.16.5-20211215b.jar
createplus-1.16.4_v0.3.2.1.jar
culinaryconstruct-forge-1.16.5-4.0.0.6.jar
curios-forge-1.16.5-4.0.8.0.jar
darkerdepths-1.16.5-1.1.4.jar
decorative_blocks-1.16.4-1.7.2.jar
decorative_blocks_abnormals-1.2.jar
deuf-1.16.4-1.1.jar
doubledoors_1.16.5-3.1.jar
effortlessbuilding-1.16.3-2.29.jar
elevatorid-1.16.5-1.7.13.jar
emobile-1.0.3-SNAPSHOT.jar
enchantedbookredesign-3.3-1.16.4.jar
endergetic-1.16.4-3.0.0.jar
envirocore-1.16.5-3.0.9.3.jar
envirotech-1.16.5-3.0.9.4.jar
extcaves-2.4.jar
fairylights-4.0.5-1.16.5.jar
fastfurnaceminusreplacement-1.1-1.16.3.jar
ferritecore-2.1.0-forge.jar
flatbedrock-1.2.0-build.2+mc1.16.5.jar
flywheel-1.16-0.2.5.jar
forbidden_arcanus-16.2.2.jar
forgery-1.16-2.3.0-exp2.jar
ftb-backups-2.1.2.2.jar
ftb-chunks-forge-1605.3.2-build.115.jar
ftb-library-forge-1605.3.4-build.90.jar
ftb-quests-forge-1605.3.6-build.76.jar
ftb-teams-forge-1605.2.3-build.40.jar
geckolib-forge-1.16.5-3.0.61.jar
glasscutter-1.1.1-1.16.5.jar
gravestone-1.16.5-1.0.7.jar
iChunUtil-1.16.5-10.5.1.jar
ilikewood-1.16.5-6.3.0.0.jar
ilikewoodximmersiveengineering-1.16.5-6.3.0.0.jar
immersivecooking-1.0.1.jar
immersiveposts-1.16.5-4.2.2.jar
industrial-foregoing-1.16.5-3.2.14.7-16.jar
ironchest-1.16.5-11.2.21.jar
item-filters-forge-1605.2.5-build.9.jar
jei-1.16.5-7.7.1.145.jar
journeymap-1.16.5-5.8.0beta10.jar
kotlinforforge-1.16.0-obf.jar
kubejs-create-1605.1.4-build.12.jar
kubejs-forge-1605.3.19-build.258.jar
kubejs-immersive-engineering-1605.1.2-build.28.jar
kubejs-thermal-1605.1.4-build.4.jar
lootr-1.16.5-0.1.11.36.jar
magicfeather-1.16.2-3.2.0.jar
metalbarrels-1.16.2-3.3b.jar
moreminecarts-1.3.13.jar
nolakes-0.1-1.16.4.jar
norecipeadvancements-1.0.1.jar
observable-0.2.1-forge.jar
occultism-1.16.5-1.24.1.jar
orcinusscaves-1.3.jar
paintings-1.16.4-7.0.0.1.jar
performant-1.16.2-5-3.82m.jar
pipez-1.16.5-1.2.15.jar
pitg-1.16.5-2.0.1.jar
polymorph-forge-1.16.5-0.39.jar
ponderjs-1.16.5-1.0.3d.jar
portable_stonecutter-1.16.5-1.3.5.jar
portality-1.16.5-3.2.5.jar
randomium-1.16.5-1.7.jar
randompatches-2.4.4-forge.jar
ravencoffee-1.16.5-beta_01.jar
recipebuffers-2.1.jar
reliquary-1.16.5-1.3.5.1104.jar
repurposed_structures_forge-3.4.7+1.16.5.jar
rhino-forge-1605.1.5-build.75.jar
selene-1.16.5-1.9.0.jar
spark-forge.jar
steampowered-1.16.5-1.1.12.jar
strawgolem-1.16-1.9.jar
structurescompass-1.16.5-1.3.0.jar
sulfuric-1.1.jar
supplementaries-1.16.5-0.18.0.jar
swingthroughgrass-1.16.4-1.5.3.jar
terraform-1.0.2.jar
theoneprobe-1.16-3.1.4.jar
thermal_cultivation-1.16.5-1.4.1.3.jar
thermal_expansion-1.16.5-1.4.2.4.jar
thermal_foundation-1.16.5-1.4.2.9.jar
thermal_innovation-1.16.5-1.4.1.3.jar
thermal_locomotion-1.16.5-1.4.1.2.jar
titanium-1.16.5-3.2.8.7-22.jar
traverse-1.16.4-0.4.3.8.jar
valhelsia_core-16.0.15.jar
valkyrielib-1.16.5-3.0.9.5.jar
worldedit-mod-7.2.5-dist.jar
worldshape-1.0.jar
xkdeco_0.2.4.jar

**Comment by malte0811** [comment]
I'm unable to reproduce this, but I'm also not going to download all those mods manually. The most likely reason for this is that some mod is adding a lot of potion recipes, which the Mixer currently does not handle well. I can (probably) fix that, but I need to know which mod is adding all the recipes first (so I can actually test my fix). Can you check the mixer recipes in JEI (look at the recipe for e.g. concrete and then click on the "Mixer" label at the top) and tell me a) how many pages there are and b) click through them a bit to see if one mod is obviously "responsible" for a lot of the potion recipes?

**Comment by Magi1053** [comment]
This is a tricky issue for sure. I myself am unable to replicate the issue again under the exact same circumstances. There are 63 recipes (16 pages), and it looks like all of the outputs are all Immersive Engineering potions.

**Comment by mindforger** [comment]
Not sure if spark is available, make a profile with ticks only above 100 and use the gc monitor, to me it sounds like a potential memory leak or fragmentation

**Comment by Magi1053** [comment]
I for sure will if it happens again
