### ISSUE TITLE
[1.16] The heck is "solder"?

### ISSUE THREAD

**Issue by electrovoyage** [BluSunrize/ImmersiveEngineering#5191]
### Description of the issue:
So i figured all of components out on the electronics workbench or whatever it's called but the heck is "solder"? Just wanna ask.
### Crashlog:
There's no crash but this kinda affects my gameplay.

### Versions & Modlist
If your game crashed (see above) you may omit the modlist, but IE and Forge version would still be nice.
1.16, x32 Faithful resourcepack, lots of mods like "Create", this is just a modified ready modpack, after all.

**Comment by electrovoyage** [comment]
Also i couldn't find ANY info about "solder" on wiki so plz?

**Comment by TeamSpen210** [comment]
It's anything tagged with `immersiveengineering:circuits/solder`, which is just either copper or lead wire (raw, not coils).

**Comment by BluSunrize** [comment]
![image](https://i.imgur.com/nMY0ibB.png)

I literally can not spell it out anymore. It says it *right there*.
"lead or copper wires"

Please just read the fucking manual and stop trusting some stupid wiki. There *is no official wiki for IE*. And the third party ones are always out of date.

**Comment by electrovoyage** [comment]
Thanks!

вс, 23 янв. 2022 г., 0:26 Spencer Brown ***@***.***>:
