### ISSUE TITLE
[Sugesstion] Choose what colors are connected by the redstone interface connector

### ISSUE THREAD

**Issue by devBob027** [BluSunrize/ImmersiveEngineering#5196]
By right clicking the redstone interface connector with a screwdriver access a menu to change what connections the block can access. Unconnected connections show a signal strenght of 0.

**Comment by BluSunrize** [comment]
What's the usecase?

**Comment by devBob027** [comment]
Connecting multiple logic units together while still having some channels which are seperate. sometimes 6 sides just aren't enough for connecting individual channels.

**Comment by BluSunrize** [comment]
A logic unit can *at most* output to 10 different colors. A single connector is enough for that.
