### ISSUE TITLE
[1.16.5] Forming squeezer crashed singleplayer

### ISSUE THREAD

**Issue by theArhar** [BluSunrize/ImmersiveEngineering#5197]
### Description of the issue:
Tryed to right click middle barrel after construction, got crash

### Crashlog:
https://pastebin.com/r2FHgHLK

### Versions & Modlist
Minecraft version: 1.16.5
Mod version: 5.0.7-143
Minecraft Forge version: 36.2.22
Mod Pack: TNP Limitless 3 1.11.8

**Comment by malte0811** [comment]
Does this happen reliably or was it a one-off thing? This is sort of an MC bug, not a whole lot that can be done about it. Note that I'm partially guessing here, CME crashes (usually) have two threads involved in them, and the one in the crashlog is the less interesting one.

**Comment by mindforger** [comment]
i spotted this line

>RoadRunner != Lithium: This instance was launched using RoadRunner, which is an *unofficial* Lithium fork! Please **do not** report bugs to them!

maaaybe one could remove those rendering optimiziing mods and see if the issue goes away

**Comment by malte0811** [comment]
As a dev of both RoadRunner and IE: No, I'm quite sure I know what's racing here and it's not related to RR (also: RR is not rendering, it's primarly server-side optimization). And maybe don't talk about "see if the issue goes away" while we don't even know whether it's reproducible?

**Comment by theArhar** [comment]
> Does this happen reliably or was it a one-off thing? This is sort of an MC bug, not a whole lot that can be done about it. Note that I'm partially guessing here, CME crashes (usually) have two threads involved in them, and the one in the crashlog is the less interesting one.

No, not reproducable
