### ISSUE TITLE
1.18.1 crach

### ISSUE THREAD

**Issue by mr-cat-s** [BluSunrize/ImmersiveEngineering#5199]
[crash-2022-01-25_14.46.59-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/7938244/crash-2022-01-25_14.46.59-client.txt)
[crash-2022-01-25_15.35.31-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/7938245/crash-2022-01-25_15.35.31-client.txt)

**Comment by malte0811** [comment]
Optifine is not supported, this is a known issue with it.
