### ISSUE TITLE
JerryCans

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#520]
The documentation stating what these things are/do is nonexistent, so the below is speculation based on my interpretation of the item, please correct me if I am wrong. 

The jerrycan is used to transfer one buckets worth of fluid from one IE tank (the MB silos) to another, yet they cannot be used on any of IE's machines or any other valid fluid tank other than the stated. Is this proper functionality @BluSunrize?

**Comment by BluSunrize** [comment]
Nope, not in the slightest. I wrote those on stream yesterday, they are to carry up to 10 buckets of fluid with you to refill your drill or other items on the go.
Documentation has not been written yet.

**Comment by mindforger** [comment]
i hope this is not a liquid version of the enderIO capacitor ... this could possibly ruin our server balance if you can extend the range of an liquid fuled jetpack with that

we would probably need a way to blacklist it from "charging" defined items

**Comment by BluSunrize** [comment]
It's not automatic. You craft it with another fluid container (like a drill, or even another jerry can) and it fills it.

**Comment by cobra** [comment]
Hijacking this issue: should the jerrycan work as fluid container for any fluid in any machine? For example: transporting seed oil from the squeezer to a refinery or getting creosote oil out of a coke oven.

Also, how about rightclicking a diesel generator with a jerrycan to refuel it? I think at least this should be possible.

I'm a bit unsure about the amounts transferred to containers like the barrel (or, if implemented, the generator). 10 buckets at once feels a bit high, maybe 1 bucket? But that would need some logic to decide about the direction of the transfer (maybe rightclick to empty the jerrycan, shift-rightclick to fill unless either the targeted tank or the jerrycan are empty).
