### ISSUE TITLE
[1.12.2] Crash When Viewing Block in AE2 Terminal Search

### ISSUE THREAD

**Issue by ByThePowerOfScience** [BluSunrize/ImmersiveEngineering#5200]
### Description of the issue:
I have six instances of this happening.  I'll be playing normally, open an AE2 terminal, search something like "servo", and the moment I press the "e" key the game crashes to desktop.  This bypasses VanillaFix's crash handler, as it appears to crash the JVM itself.

However, the issue itself is not consistent.  It is always triggered by a search in a ME Terminal (of any kind, AE2 or otherwise), but not all searches trigger this.  I will record what I was typing when it next crashes, as it could be a rendering error in combination with something else.

### Crashlog:
[Crash 1](https://pastebin.com/BK4qULhu)
[Crash 2](https://pastebin.com/n4ECub6Z)
[Crash 3](https://pastebin.com/TasLe4UT)
[Crash 4](https://pastebin.com/FcQSJnnn)
[Crash 5](https://pastebin.com/CkALhsWA)
[Crash 6](https://pastebin.com/hgFEVzyV)

### Versions & Modlist
Minecraft: 1.12.2
IE: 0.12-98
Forge Mod Loader: 8.0.99.99
Minecraft Forge: 14.23.5.2858
Applied Energistics 2 Trousers Edition: rv6-stable-7 omni-fixes-v47

This issue occurred while playing the Divine Journey 2 (v2.9.1) modpack.

**Comment by mindforger** [comment]
The pastebin links are private or blocked

**Comment by BluSunrize** [comment]
1.12 is no longer supported

**Comment by ByThePowerOfScience** [comment]
Someone reported my pastes for abuse for some bizarre reason.  I'm working on getting them up right now.

**Comment by ByThePowerOfScience** [comment]
@BluSunrize In regards to your other reply, since you blocked me from responding:

You don't have to fix it yourself, just make it easier on people who want to maintain older versions.  Thousands of people love your mod, but the bugs make using some machines not worth the risk.  One of those people might want to fix that.  You allow pull requests for a reason.

Anyway that's my last comment on the matter.  I really appreciate the work you've put into this project.  You don't have to be the only one supporting it.

**Comment by BluSunrize** [comment]
There is noone else maintaining old versions of this project.
There will be no more releases for 1.12.

**Comment by ByThePowerOfScience** [comment]
Not even @mindforger?  They seemed pretty interested.

Anyway I said I wasn't going to continue this, sorry. I've said what I wanted to say.
