### ISSUE TITLE
[1.12.2] Multiblock Issues When Breaking - Metal Press Conveyors and Assembler Unbreakable Iron Slab

### ISSUE THREAD

**Issue by ByThePowerOfScience** [BluSunrize/ImmersiveEngineering#5201]
### Description of the issue:
When breaking the Metal Press multiblock, the conveyor belt blocks will have missing textures and be a different conveyor belt item.  Given that you can craft these glitched conveyor belts back into regular ones, I assume you know about this issue, and have added the crafting recipe as a band-aid fix for it.  Given that it doesn't cause any harm, I'm totally fine with that solution.

However, this second one is much worse, and is easily reproducible.  Simply build the Assembler multiblock, activate it with the Engineer's Hammer, then break a piece to trigger it to return to single blocks.  The iron slab on the back right corner (when facing the input) will no longer be breakable, and will crash the server if vein-mined.

More specifically, you can break the slab, but it immediately comes back as though it had never been broken.  It cannot be moved with one of Mekanism's "Cardboard Box" items, and acts somewhat like a client-side "ghost block", but it can only be removed from the world by replacing the block with air via command.  Breaking the iron slab while the Assembler is still in multiblock form will allow it to be broken and drop as normal. 

Glitch Showcase: https://youtu.be/Tl3vSlK0k5A
Messing with the Ghost Slab: https://youtu.be/_i20SRrxwzI

This issue is consistent on my home server, MineYourMind, happening 9/10 times that I have tested.  I was unable to replicate the  issues on singleplayer, nor was I able to replicate the other multiblock issues I have experienced, meaning these issues are likely specific to server play.

I will also ask the MineYourMind staff to link the IE config settings they use in this thread.

### Versions & Modlist
Minecraft: 1.12.2
Immersive Engineering: 0.12-98
Minecraft Forge: 14.23.5.2858
Forge Mod Loader: 8.0.99.99

This issue occurred while playing the Divine Journey 2 modpack.

**Comment by BluSunrize** [comment]
1.12 is no longer supported

**Comment by ByThePowerOfScience** [comment]
Look, while I understand where you're coming from, it probably isn't a good idea to close tickets just because they're on older Minecraft versions?  A Minecraft version isn't like a mod version; it's going to see extended use because there's physically no way for modpack players to update.  Because of compatibility issues, it should probably be treated as a discrete project, not just an older version of your code.  It's like if half of the programs you use say "we don't support Windows 11" and half of them say "we're no longer patching common fatal errors on Windows 10", you're going to be left in a bit of a bind, yeah?

Plus this is an open-source project, y'know?  Some unhappy player like me might decide to maintain the versions for older Minecraft, so being able to see which tickets have actually been solved and which haven't might be useful.

Anyway this is your project, not mine.  It just sucks to feel like you're being ignored due to no fault of your own.

**Comment by BluSunrize** [comment]
It's not an open source project. It's a visible source project.
Distribution of compiled product is explicitely disallowed by the license.

And the reason we don't support old version of Minecraft is because this is a hobby. I have a 40 hour dayjob in programming, I do Minecraft on the side. I already get barely any time to work on this, let alone try to support it for versions that are *years out of date*.
