### ISSUE TITLE
1.17.1 Crash

### ISSUE THREAD

**Issue by XxneonisawesomexX** [BluSunrize/ImmersiveEngineering#5202]
When I Started Up Minecraft On Forge 1.17.1 With The Immersive Engineering Mod The Game INSTANTLY Crashes! (Probably Because There's No 1.17.1 Download)

**Comment by BluSunrize** [comment]
Yeah. 1.17 is not supported. We never released a version for it. IE is only available for 1.16.5 and 1.18.1.

If you somehow got a 1.17 file, you probably downloaded malware. You should get rid of that.
