### ISSUE TITLE
[1.16.5] Random crash during startup

### ISSUE THREAD

**Issue by Magi1053** [BluSunrize/ImmersiveEngineering#5204]
### Description of the issue:
Randomly when I startup my modpack it will crash during the startup phase with the following crash report. It doesnt happen frequently but often enough for it to be annoying.

### Crashlog:
https://pastebin.com/raw/GE03mhzc

### Versions & Modlist
forge-1.16.5-36.2.23
ImmersiveEngineering-1.16.5-5.0.7-143

**Comment by BluSunrize** [comment]
Closing this because support for 1.16.5 has ended
