### ISSUE TITLE
[1.18] Chemthrower, Mining Drill and Buzzsaw have flipped faces when held in left hand

### ISSUE THREAD

**Issue by TeamSpen210** [BluSunrize/ImmersiveEngineering#5207]
### Description of the issue:
When holding these three tools in the left hand (via left handed mode in the main hand, or via offhand) they render wrongly (both first and third person). It appears the normals/faces got flipped during the horizontal flip, since this doesn't affect the Railgun or Revolver (which don't have to flip). Also, (though probably unrelated), it seems like Buzzsaw blades don't have a bottom face.

### Crashlog:
If your Minecraft instance has crashed, a file will have been generated in the folder `crash-reports` of your minecraft folder. To understand what has happened, we need to know the content of that file. But please don't just put it directly in your report (that makes it hard to read), upload it to a site like [pastebin](http://pastebin.com) or [gist](http://gist.github.com) and put a link in the actuall bug report.

### Versions & Modlist
* Forge: 39.0.17
* IE: 1.18.1-7.1.0-145

![Drill in Left Hand](https://user-images.githubusercontent.com/8453732/151653575-aba7a68c-3fa2-47ff-bd2e-c2d9d988442f.png)

**Comment by BluSunrize** [comment]
@malte0811 I need your help on this. I've been unable to work this out. I tried not flipping the normals, but was unsuccesful.

Need some insight from your end here, since you revamped the OBJ systems.

**Comment by moon-st0ne** [comment]
still getting this issue, in 8.0.2-149

![image](https://user-images.githubusercontent.com/29065768/175766155-0396dde7-d872-4645-912a-8c6e34f3e2cd.png)
