### ISSUE TITLE
1.16.5 World Gen Stallout

### ISSUE THREAD

**Issue by EightBlade** [BluSunrize/ImmersiveEngineering#5214]
I'm running a custom 1.16.5 modpack, and when I add immersive engineering it stalls out the world gen. I've tried it with terraforged, with vanilla worlds, tried switch forge versions, switching IE versions; yet nothing works. I'm not sure what's causing the problem.

### Crashlog:
No crash, but have a log of what happens when I try generating the world. I've tried it without bettercaves and it doesn't help, only IE causes this.

[runninglog1.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/8007938/runninglog1.txt)

Here's my modlist: https://pastebin.com/yxWMJESS

**Comment by EightBlade** [comment]
Forget to include: I've tried using [1.16.5-5.0.7-143] and down, tried switching multiple times. That's the most recent log above.

**Comment by BluSunrize** [comment]
Closing this because support for 1.16.5 has ended
