### ISSUE TITLE
[1.18.1] Turrets always look north

### ISSUE THREAD

**Issue by Zahkriiven** [BluSunrize/ImmersiveEngineering#5218]
### Description of the issue:
Both turrets always look north regardless of base orientation. They probably should match the base as its default orientation.
![2022-02-10_21 22 50](https://user-images.githubusercontent.com/25531677/153490497-0b14d22d-e776-4cc7-903b-a8fabd965ee5.png)

### Versions & Modlist
ImmersiveEngineering-1.18.1-7.1.1-pre.45

**Comment by BluSunrize** [comment]
Oh right, this one was open for backporting.

**Comment by BluSunrize** [comment]
Oh right, this one was open for backporting.

**Comment by BluSunrize** [comment]
This issue isn't present in 1.16.5

Confusing use of labels.
