### ISSUE TITLE
Coke oven MB does not render

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#522]
A correctly formed IE coke oven does not render as expected.

Action: Forming a IE Coke Oven Multi-block structure

expected result: The Coke oven will form and display some form of rendering

actual result: the coke oven blocks that make its structure do not render, as expected, though the 'formed' MB does not render, just greeted by empty air. Images below.
![image](https://cloud.githubusercontent.com/assets/3110986/10627725/f363c68a-7771-11e5-803b-481685e07fdd.png)
![image](https://cloud.githubusercontent.com/assets/3110986/10627726/fc8516ce-7771-11e5-90d4-19de7e723c5d.png)
![image](https://cloud.githubusercontent.com/assets/3110986/10627730/035649fa-7772-11e5-80dc-860c3810d41f.png)

IE version 0,6,0_pre build  73552ec
MC 1.7.10 running with bare-minimum mod install:
 * Forge
 * TE and prereqs
 * IE and prereqs
 * NEI

**Comment by cobra** [comment]
I can confirm this for 18137cd as well. I'll try bisecting and update this post.
