### ISSUE TITLE
[1.18.1] IE raw ores are missing #forge:raw_materials tags

### ISSUE THREAD

**Issue by TJT01** [BluSunrize/ImmersiveEngineering#5221]
### Description of the issue:
IE's raw ores are missing the `#forge:raw_materials` and `#forge:raw_materials/___` tags, leading to incompatibility with other mods, like Tinker's Construct.
![2022-02-12_21 41 15](https://user-images.githubusercontent.com/87955906/153736164-c13ec72d-0b3b-4f78-99da-184debb658bb.png)
![2022-02-12_21 41 21](https://user-images.githubusercontent.com/87955906/153736174-5d4ac0e3-254e-4552-9a95-a46143052459.png)

### Versions & Modlist
* Forge: 39.0.66
* IE: 1.18.1-7.1.0-145

**Comment by malte0811** [comment]
This is already fixed in dev: 35d157785d, there just hasn't been a release since it was fixed. And "fixed" means "changed to match Forge conventions once they actually *had* conventions for this", when the last release was made Forge just didn't have tags for raw ores.
