### ISSUE TITLE
[1.18.1] Structural Arm Placement Issues

### ISSUE THREAD

**Issue by Alex33212** [BluSunrize/ImmersiveEngineering#5222]
**Description:**
When trying to place structural arm blocks, placing off the side of a block results in a fixed vertical orientation regardless of whether the top or bottom half of the block side is targeted; expected behavior is that of stair blocks (where top half targeted = inverted/upside-down). In an install with multiple other mods, structural arms are always upright; in an IE-only install, they're always inverted.

**Versions & Modlist:**
IE 1.18.1-7.1.0-145
Forge 39.0.8

**Comment by BluSunrize** [comment]
Reopening because backport

**Comment by BluSunrize** [comment]
And closing it again, because this issue doesn't even exist in 1.16.5

By attempting to fix it, I have instead broken it in my dev environment, lmao.
