### ISSUE TITLE
[FEATURE] Add External Heater support for Iron Furnaces

### ISSUE THREAD

**Issue by booskahmed** [BluSunrize/ImmersiveEngineering#5226]
I'm playing on 1.16.5 with IE and[ Iron Furnaces mod](https://www.curseforge.com/minecraft/mc-mods/iron-furnaces)
my external heater works fine when I put it next to a vanilla furnace, but modded ones don't seem to work, I have checked configs... but nowhere to see if this is supported or an intentional choice
![Screenshot_1](https://user-images.githubusercontent.com/62657220/156205108-d4f66479-0744-49e3-86e4-772b2e2ac736.png)
.
image : external heater powered with energy (powah creative cell) next to a diamond furnace, the same setup works for a vanilla furnace

**Comment by BluSunrize** [comment]
IE's external heater is designed to speed up furnaces in addition to powering them.

Iron Furnaces are already faster, so I wouldn't want them to be buffed by our heater. This is an intentional lack of compatability.
