### ISSUE TITLE
IE crashlog

### ISSUE THREAD

**Issue by mlg2020** [BluSunrize/ImmersiveEngineering#5227]
crashes when i load up a world in game

1.16.5 forge 36.2.20
IE version [1.16.5-5.0.7-143]

i have tested this mod on its own with performance mods i have and it kept crashing!

https://pastebin.com/xuGUk49U

**Comment by mindforger** [comment]
>have tested this mod on its own with performance mods i have and it kept crashing

maybe add those crash logs too?

**Comment by BluSunrize** [comment]
Closing this due to lack of feedback.
