### ISSUE TITLE
[Suggestion] high tension power lines

### ISSUE THREAD

**Issue by pigs-fly** [BluSunrize/ImmersiveEngineering#5229]
### Description of the issue:
Would love to see some sort of power tier above HV but only suitable for long range transmission and requiring transformers (no capacitors). Possibly multiblock transformers to give a bit more of a substation feel?
May need bigger power poles however and an insta-death for touching the wire.

### Crashlog:
No crash here, just lots of fun.

### Versions & Modlist
MC - 1.16.5
Forge - 36.2.5

### Lastly
Thank you very much for your effort for what is a great/essential mod.

**Comment by BluSunrize** [comment]
Pretty sure we already had this discussion on discord and the answer remains no.

**Comment by pigs-fly** [comment]
Well simple solution at least.
Thank you for your time.
