### ISSUE TITLE
Pipes crash server when receiving fluid

### ISSUE THREAD

**Issue by cobra** [BluSunrize/ImmersiveEngineering#523]
I don't know whether #513 is really fixed due to a lack of reproducibility, but at least the attempted fix for this does something¹ every time and very reproducibly. Also, it's much more effective by crashing the server instead of the client and making worlds unusable. How to enjoy this new feature:
- Load world with tanks connected to pipes: instant crash on server start. World cannot be opened.

or:
- Create new world
- build IE tank, fill with some liquid. Alternative: be lazy and use a TE portable tank set to output.
- connect IE pipe(s)
- apply redstone to bottom tank block
- crash, world cannot be opened again.

version: current master, 73552ec
````
java.lang.ClassCastException: blusunrize.immersiveengineering.common.blocks.metal.TileEntityFluidPipe$DirectionalFluidOutput cannot be cast to java.lang.Comparable
	at java.util.concurrent.ConcurrentSkipListMap.cpr(ConcurrentSkipListMap.java:655)
	at java.util.concurrent.ConcurrentSkipListMap.doPut(ConcurrentSkipListMap.java:835)
	at java.util.concurrent.ConcurrentSkipListMap.putIfAbsent(ConcurrentSkipListMap.java:1962)
	at java.util.concurrent.ConcurrentSkipListSet.add(ConcurrentSkipListSet.java:241)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityFluidPipe.getConnectedFluidHandlers(TileEntityFluidPipe.java:71)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntityFluidPipe.fill(TileEntityFluidPipe.java:122)
	at blusunrize.immersiveengineering.common.blocks.metal.TileEntitySheetmetalTank.updateEntity(TileEntitySheetmetalTank.java:76)
	at net.minecraft.world.World.updateEntities(World.java:2160)
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:515)
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:703)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:614)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:118)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:485)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:752)
````

¹not really what was intended, I guess. Still, the client-side CME is definitely gone at the moment… with the rest of the game.

**Comment by mindforger** [comment]
naah this nasty comparable thing again XD .. always this rat tails during conversions

**Comment by malte0811** [comment]
Semi-raleted question: Why are we using `ConcurrentSkipListSet` at all? I know that it is thread safe, but it is also sorted, meaning that the access time is at least `O(n*log(n))`, but also meaning that classes that usually don't need to implement `Comparable` have to do so. Using a `ConcurrentHashMap` and calling `Collection.newSetFromMap` ([Documentation](http://docs.oracle.com/javase/6/docs/api/java/util/Collections.html#newSetFromMap%28java.util.Map%29)) would result in constant (or linear?) access time and no need for implementing `Comparable`. Is there any disadvantage of this method that I am not aware of?

**Comment by BluSunrize** [comment]
Well it apparently wasn't thread safe, was it? It crashed on cobra, here: #513

**Comment by malte0811** [comment]
You were not using the solution I described above, you were using an `ArrayListMultimap`, which does not state anywhere that it was thread safe. My solution is afaik thread safe.
My question was not why the collection was changed, I would like to know why @mindforger chose `ConcurrentSkipListSet`

**Comment by BluSunrize** [comment]
He didn't. I fixed the CME on the pipes. I took those lists from the ImmersiveNetHandler

**Comment by malte0811** [comment]
I know, I was referring to mindforger@d7b052087943fd6ae30dba507b7cbf7f33cfe34d and 441e78b65a802eba7ccf4d8055eef1b98708b89a. I don't think that either the energy net or the pipes need sorting, I referenced him since using these sets was originally his idea and therefore he would probably know best why they were used

**Comment by malte0811** [comment]
I have changed both the energy net and the pipes to use the set i suggested. I am pretty sure that it all works. I am just waiting for @mindforger to confirm that this sollution is ok, then I will PR it.

**Comment by mindforger** [comment]
i was using those, as they are also implementing the "copy when write" (the sorting was an unwanted but not removable sidefeature) to suppress concurrent access. 
These Sets are backlinked to the ConcurrentHashMaps, so changeing the CSLS also changes the Map Entry, how does your Set achive this?

**Comment by BluSunrize** [comment]
Or we just make DirectionalFluidOutput comparable, shouldn't that fix it? .~.

**Comment by malte0811** [comment]
@BluSunrize It would fix the crash @cobra reported, but it would not fix the problem I mentioned above (access time).
@mindforger I don't know how the `ConcurrentHashMap` works, but I have tried a few cases (like write access while iterating) and I never experienced any CMEs. If you can explain a bit more precise what your concern is I will test that, but I don't really understand what your problem with my sollution is.

**Comment by mindforger** [comment]
@malte0811 make a hasmap, fill it with data, now make an iterator, start iterating and stop at some point to remove an entry from that list (!!!not using that iterator!!! to simulate concurrent access from ASM interaction for example), now iterate further, baaam! CME

the ConcurrentHashMap ensures all iterators are using a copy on write and update their backlinks when possible ... you can reinvent the wheel and try to ensure yourself to only update changes when you are 100% sure no iterator is using your map or use existing maps, lists and sets ... the skiplist is the only thing i cam up with on my research, i'd be happy to find a concurrent safe version without filtering to make it faster!

**Comment by malte0811** [comment]
So this https://gist.github.com/malte0811/d628d12e932ec0cd256c? It did not throw any Exceptions when I tested it. Also: I was talking about sets, not lists.

**Comment by mindforger** [comment]
@malte0811 those SkipListSets are behaving like an list and not (only) like an set, modifying them also prevents the used iterators to CME when modified, therefore they are used as replacement for a List<T> in the first place and not only as a set!

Your example is incomplete, you are creatin the set from an empty map, the map we are using already contains something and the changes made to the set need to be updated, i'll comment over in this example to explain what i mean, but still this example looks promising

**Comment by malte0811** [comment]
`Collections.newSetFromMap` will crash if the parameter map is not empty, so i don't think that i am doing such a call anywhere. I am also not keeping any references to the maps used to create the sets, so it would not matter if they did not get written to the map immedeatly.

**Comment by mindforger** [comment]
well i tested your approach and it works fine, see my comments to your snippet, i did not recognize you are backing the sets from freshly created ConcurrentHashMaps, but this is okay imho!
Your PR looks valid so far and where ever there are `SkipListSet<T>`, they can be refactored to ordinary `Set<T>` and the ConstructorCall to the Lists has to be replaced by `Collections.newSetFromMap(new ConcurrentHashMap<T, Boolean>());`
