### ISSUE TITLE
[1.12.2] Arc Furnace comparator signal for the electrodes does not update properly

### ISSUE THREAD

**Issue by Sheenus** [BluSunrize/ImmersiveEngineering#5231]
### Description of the issue:
The redstone comparator signal, for when a comparator is connected to the blockspace where the graphite electrodes sit, outputs a signal depending on the current sum durability of all three electrodes in the top of the Arc Furnace, however it does not update properly when electrodes are removed or added manually.

### Versions & Modlist
Minecraft 1.12.2
MCForge 14.23.5.2855
IE 0.12-98

Modlist (from forced debug crash):
| State    | ID                          | Version      | Source                                  | Signature                                |
|:------    |:-------------------- |:------------ |:--------------------------------------- |:---------------------------------------- |
| LCHIJA | minecraft            | 1.12.2       | minecraft.jar                           | None                                     |
| LCHIJA | mcp                  | 9.42         | minecraft.jar                           | None                                     |
| LCHIJA | FML                  | 8.0.99.99    | forge-1.12.2-14.23.5.2855-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| LCHIJA | forge                | 14.23.5.2855 | forge-1.12.2-14.23.5.2855-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
| LCHIJA | waila                | 1.8.26       | Hwyla-1.8.26-B41_1.12.2.jar             | None                                     |
| LCHIJA | jei                  | 4.16.1.301   | jei_1.12.2-4.16.1.301.jar               | None                                     |
| LCHIJA | immersiveengineering | 0.12-98      | ImmersiveEngineering-0.12-98.jar        | None                                     |

P.S. I get that this version of Immersive Engineering is depreciated, however I still think reporting these bugs is a good idea, just in case someone *does* decide for whatever reason to pick it up and update 1.12.2 again, so that they have a handy to-do list just by looking at open 1.12 issues. Up to you guys whether you agree.

**Comment by BluSunrize** [comment]
Support for 1.12 was ended almost two years ago.

It will not be picked up again.
