### ISSUE TITLE
[1.16.5] Silo Comparator/Redstone Probe interactions

### ISSUE THREAD

**Issue by kingchills** [BluSunrize/ImmersiveEngineering#5232]
### Description of the issue:
Silo is not currently outputting comparator based redstone signal from the various heights of the silo as the manual describes.  Attempted with Comparator and Redstone Probe.  Comparator attached to bottom center block still shows overall fill level as described.

### Versions & Modlist
IE Version: 1.16.5-5.0.7-143
Forge Version: 36.2.8
JEI Version: 1.16.5-7.7.1.150
The One Probe Version: 1.16-3.1.5
No other mods installed.

![2022-03-07_14 19 16](https://user-images.githubusercontent.com/1569290/157102936-70dcb43f-44b5-46d8-a75f-020d79766c15.png)

**Comment by BluSunrize** [comment]
Closing this because support for 1.16.5 has ended
