### ISSUE TITLE
Feedthrough Insulators Transparent

### ISSUE THREAD

**Issue by HenryMaxler** [BluSunrize/ImmersiveEngineering#5233]
### Description of the issue:
Feedthrough Insulators are transparent, letting light in and/or making the block look strange when in medium light scenarios.

### Versions & Modlist
IE: 1.16.5-5.0.7-143
Forge: 36.2.29
<img width="802" alt="feedthrough insulator" src="https://user-images.githubusercontent.com/75149748/157614854-abbd0766-568d-438d-9d7f-12bc91f77ca4.png">

**Comment by BluSunrize** [comment]
Closing this because support for 1.16.5 has ended.
