### ISSUE TITLE
1.12.2 invalid Java Runtime configuration. 

### ISSUE THREAD

**Issue by poter1402** [BluSunrize/ImmersiveEngineering#5234]
### Description of the issue:
when i run minecraft i get this screen
![Nowy obraz mapy bitowej](https://user-images.githubusercontent.com/99959187/157846493-b72b2259-5cfa-49f3-89dc-d16b786fc0c1.jpg)

[### Crashlog:
https://pastebin.com/4YnZPwzC](https://pastebin.com/WxNRVfhB)

### Versions & Modlist
ImmersiveEngineering-0.12-73
jei_1.12.2-4.16.1.302
OptiFine_1.12_HD_U_G5
tlskincape_1.12.2-1.4

**Comment by malte0811** [comment]
1. IE 0.12-73 is massively outdated, even on 1.12. This is fixed in more recent IE builds.
2. 1.12 is no longer supported.
3. Optifine is not supported.
