### ISSUE TITLE
[Suggestion] Redstone filter, only pass signal if above user specified threshold

### ISSUE THREAD

**Issue by toastonrye** [BluSunrize/ImmersiveEngineering#5237]
Hi, I have a suggestion/request to consider for Redstone, I didn't see it posted before.

Add Redstone filter/relay that only passes the Redstone signal if it is above or below a certain threshold?

For instance, I am using a probe connector to read a tank level, and I want it to activate a Redstone connector output only if the signal is above a 7.

**Comment by BluSunrize** [comment]
This is now covered.
See #4980
