### ISSUE TITLE
[1.18.1] Invisible blocks

### ISSUE THREAD

**Issue by auracreepey** [BluSunrize/ImmersiveEngineering#5240]
### Description of the issue:
Hi. While connecting to a private server, I noticed that the IE blocks have become invisible (They are still there, but they are transparent)
The cables remain visible

<img width="708" alt="image" src="https://user-images.githubusercontent.com/77360773/159471436-3c11c459-9b0c-4050-855e-bfabe0a8de94.png">

### Versions & Modlist
IE : 1.18.1-7.1.0-145
Forge : 1.18.1 - 39.1.0
Create : 1.18.1_v0.4d
flywheel : 1.18-0.6.0
radium : 0.7.7g
rubidium : 0.5.0

**Comment by malte0811** [comment]
Does this also happen without rubidium?

**Comment by CanadianBaconBoi** [comment]
Also experiencing this, only happens with Rubidium.
Related issues can be found here:
[Asek3/Rubidium#31](https://github.com/Asek3/Rubidium/issues/31), [Asek3/Rubidium#54](https://github.com/Asek3/Rubidium/issues/54)
