### ISSUE TITLE
please help me fix my world [1.16.5]

### ISSUE THREAD

**Issue by GondorsbaneJr** [BluSunrize/ImmersiveEngineering#5241]
yo so i downloaded your 1.16.5 mods all the immersive mods posts ports all of them and decided to play on my main modded world which is not backedup soo i play it i didnt do anything with your mods didnt even touch them so i exited because my fps dropped harder then my dad left soo i deleted all the mods and i go to play it again and it gives me this please tell me how to fix it i need my modded world back please just help me
![Help](https://user-images.githubusercontent.com/102195812/159599511-7fb8fb3c-295e-4871-86f8-cd8f0f3c5eca.PNG)

**Comment by BluSunrize** [comment]
If you don't make backups, that's not our fault, nor is it something we can fix (or are obligated to).

Modding a game is *always* a risk, make backups, or you regret it.
