### ISSUE TITLE
Transformers not placing visually on wooden posts

### ISSUE THREAD

**Issue by alexstratford** [BluSunrize/ImmersiveEngineering#5243]
### Description of the issue:
Transformers are not placed correctly on wooden posts
![image](https://user-images.githubusercontent.com/58825136/160668380-13b81cdd-7ee0-476d-92bc-bf45a74fb514.png)
Wires and collision are however correct.
![image](https://user-images.githubusercontent.com/58825136/160669013-0fe1d417-47a5-4bf9-9c9a-f01d9529194d.png)

### Versions & Modlist
1.18.2
Forge 40.0.32
IE
CE
Configured
JEI

**Comment by BluSunrize** [comment]
Fixed by malte, see related issue.
