### ISSUE TITLE
Minecolonies incompatibility

### ISSUE THREAD

**Issue by emanuele246gi** [BluSunrize/ImmersiveEngineering#5244]
### Description of the issue:
I noticed that there are some rotation issues with Minecolonies and customized buildings, they keep facing the original schematic direction instead of following this specific rotation of the building:

![2022-03-29_18 50 34](https://user-images.githubusercontent.com/61762317/160675706-6b21dc27-e9b1-4aa2-b1d5-66e25f5dfd47.png)

### Versions & Modlist
Immersive Engineering: 5.0.7-143
Forge: 36.2.33
Modlist: https://pastebin.com/cHXsGNpw

**Comment by BluSunrize** [comment]
Didn't you say you wanted to link the other issues here, that you had opened for... Engineer's Decor?

**Comment by emanuele246gi** [comment]
Oh I did it on Discord, I don't remember which mod was but I thought it was enough

**Comment by BluSunrize** [comment]
No, talk on discord gets swallowed very quickly, which is why I specifically asked you to open an issue >_>

**Comment by emanuele246gi** [comment]
Ok ok, fine... https://github.com/stfwi/engineers-decor/issues/201

**Comment by BluSunrize** [comment]
Fixed by malte in the commit above.
