### ISSUE TITLE
IE Crash with Optifine when login to the world [1.18.2]

### ISSUE THREAD

**Issue by lays24mc** [BluSunrize/ImmersiveEngineering#5245]
The client crashes as soon as you enter the world. It was tested with and without Optifine. Result: Without Optifine there are no problems. 

According to Optifine developer, however, nothing that hecan fix: [https://github.com/sp614x/optifine/issues/6724]()

The Crashlog: [https://pastebin.com/SzVemWHu]()

Installed is:

Forge - 1.18.2 - 40.0.32
Immersive Engineering - 1.18.2-8.0.0-146
Optifine HD U H6 / Optifine HD U H7 pre2 (both version tested)

If you can fix it good, if not, I have to live with it ;). I hope the description is enough, and I apologize for my bad English.

**Comment by BluSunrize** [comment]
Optifine continues to not be supported.
