### ISSUE TITLE
Client crash connecting to server

### ISSUE THREAD

**Issue by lebanni** [BluSunrize/ImmersiveEngineering#5246]
Versions :
Minecraft 1.18.2
forge 40.0.36
ImmersiveEngineering 8.0.0-146

crash report :
https://gist.github.com/lebanni/b5eaa9c281873d96a7d8cdfaf936a86f

**Comment by Eleiyas** [comment]
Sorry for creating a duplicate thread then.
I'll mention it here:

The issue seems to be linked to an incompatibility with OptiFine.

**Comment by BluSunrize** [comment]
Yeah. We know. We've literally closed multiple issues relating to this, and Optifine is very much *not supported*.

Says so in the contribution guidelines. Luckily, Malte has found a way to make it at least not crash, which will be included in the next version. Until then, play without Optifine.
