### ISSUE TITLE
[1.18.2] Mixin Error on world load when OptiFine is installed

### ISSUE THREAD

**Issue by Jerome226** [BluSunrize/ImmersiveEngineering#5249]
### Description of the issue:
When OptiFine is installed alongside IE, the game crash on world load due to something related to mixin.

This crash does not happens in a fresh install with only IE.

### Crashlog:
No crash log was generated, but here is the latest.log:
[latest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/8453489/latest.log)

### Versions & Modlist
Modlist: https://www.toptal.com/developers/hastebin/pubotilaye.apache

**Comment by mindforger** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/5247

**Comment by Jerome226** [comment]
Oops, didn't saw it was already reported. Closing as duplicate.
