### ISSUE TITLE
[Concept] Gearbox

### ISSUE THREAD

**Issue by VermillionX** [BluSunrize/ImmersiveEngineering#525]
This isn't so much a suggestion as a possible unique and immersive concept that could be incorporated into the mechanical aspect of the Kinetic Dynamo, Diesel Generator and other heavily motorized machines: **The Gearbox**.
I originally had the idea while thinking of a unique upgrade system in regards to the speed upgrade request for the crusher that someone else posted and grew it from there. Though in this iteration i'm posting here, it's less of an upgrade and more of a mechanical customization system and a resource sink for the less useful materials available.

**The Gearbox:**
To sum up the purpose of the Gearbox, it's a power regulation attachment for some machines. Rather than a machine that's incorporated into the energy network, it's incorporated into the machines similar to an upgrade module with a dynamic GUI for optimizing dynamo power output and machine power input.
The Gearbox itself is a single block that can replace a selected block on certain Multiblock machines or be placed directly against the back of a Kinetic Dynamo. Right-clicking the gearbox opens the GUI, where there are normally 4 slots for the insertion of gears, and in the case of a Dynamo: an extra slot for a Coil.

Gears are inserted into the gearbox in order of size (Relative to their purpose). Different gear materials and sizes determine the outward effect. Heavier metal gears for example boast high durability (Excluding Lead and Gold) but reduce energy efficiency. A balance between weight and durability is key (e.g. Steel and Aluminium).
Inserting gears in order from Largest to Smallest in a Kinetic Dynamo's gearbox equipped with Waterwheels for example gives a Mechanical Advantage, changing the slow-turning input of the waterwheel into much higher RPM of the dynamo (2 RF/t per wheel -> 6 RF/t as a realistic example).
Of course, if there's too much speed, it'll increase the damage that gears take and ruin a Dynamo's coil, so on a High-altitude/Storm Windmill it's also possible to reverse the order and bring the speed down so's not to damage the gearbox while still getting better power with an Electrum Coil to compensate.

Note: Gears are made in the Engineer's Workbench using Blueprints, 4 Iron Nuggets and 4 Ingots.

Example Gearbox GUI Image:
![gearbox2](https://cloud.githubusercontent.com/assets/10645298/10665573/a44e4cb0-7928-11e5-93b2-2dc3bd647dd5.png)

There's also a simpilified version of the gearbox system that's not quite as realistic, but less complicated:
The gearbox is either incorporated into the dynamos/multiblocks by default, or attached like a cover. It houses a single gear and the gear's tooltip readily identifies what each gear's effect is. Gears wear out like normal, but you don't need to worry about checking weight and such. Basically, the gears become a form of slow-burning fuel for the machines, lasting from 20 minutes to 4 hours depending on the material.
Stats are less realistic, like putting in conductive gears into a dynamo can get you an extra 1-3 RF/t; or sticking a heavier gear into a crusher speed it up by 1-5% and increases power consumption.

If you don't like either concept @BluSunrize, feel free to close/delete the thread. It was just another annoying idea I had stuck in my head I had to get out.
_(Another idea included a Shipping Container as a multiblock chest in the same way a silo is like a multiblock barrel. Someone here wanted a multiblock chest but couldn't think of how it would work.)_

**Comment by James-T-Oudvoure** [comment]
This is a really interesting idea, but about the shipping container: while this does sound like a good idea now that we have sheet metal, the silo isn't the multiblock version of the barrel, it's the multiblock version of the crate. What you were thinking of was the metal tank. A shipping container's a good idea nonetheless, we just need something to significantly seperate it from the silo.

**Comment by BluSunrize** [comment]
wait what? The silo is for massive single item storage. The wooden crate is a chest that keeps inventory.
And shipping containers are a nope, because crates can do the same thing. Silos where non-existent in IE till then, but shipping containers would just be a lot of crates clustered together, which I'd find boring.

As for gearboxes: I said I don't want upgrades on my mutliblocks so this is a very low priority maybe.

**Comment by James-T-Oudvoure** [comment]
Why exactly are you so vehemently against any kind of upgrading mechanic, even if it's much more involved and complicated than "right click upgrade on machine"?

**Comment by VermillionX** [comment]
@James-T-Oudvoure Gearbox recipe would be something like... 4 Iron Mechanical Components, 4 Iron Ingots and 1 Iron Gear.

@BluSunrize It's not so much an upgrade for multiblocks as an (educational) adjuster for the Dynamos.
At present, if you stick a Waterwheel into a Kinetic Dynamo it produces massive RF (More than any fuelled generator) despite the fact that it's turning at a fraction of the speed that a Windmill-equipped Dynamo does. It just magically converts torque without any player input.
At the opposite end, a Windmill that turns at the rate that an Advanced Windmill does would destroy it's blades and shear the teeth off it's gears (not that it does here).
The gearbox is an immersive means of correcting the dynamo's output. Also it effectively turns free-energy generators into semi-fuelled generators, using gears as fuel (without requiring constant tending of course).
(E.g. a cheap Treated Wooden Gear for example would last 10 minutes of constant use, Stone: 15, Lead: 20, Gold: 25, Copper: 35, Tin: 40, Electrum: 50, Silver: 45, Iron: 50, Aluminium: 60, Constantan: 70, Steel: 90, Diamond: 120, etc...)
