### ISSUE TITLE
[1.18.1] Machinist Missing Trade item

### ISSUE THREAD

**Issue by ffuentesm** [BluSunrize/ImmersiveEngineering#5252]
In the current version: ImmersiveEngineering-1.18.1-7.1.0-145.jar

The machinist is missing his first trade item.
![image](https://user-images.githubusercontent.com/44974827/162599839-d428347d-0474-4415-8ef4-ae3f4b5ddfd1.png)

**Comment by BluSunrize** [comment]
I can't reproduce this in 1.18.2.

1.18.1 is not being maintained any more.
