### ISSUE TITLE
[1.12.2] multiblock structures destroy conveyor belts when broken on servers

### ISSUE THREAD

**Issue by Bantoo1231** [BluSunrize/ImmersiveEngineering#5254]
I'm running a modpack with Immersive Engineering version 0.12-98 as the main tech mod and in singleplayer it works perfectly fine but for some reason on my server we're testing it with when ever a multi-block structure like an assembler or press is broken the conveyor belts used to make it become unusable purple and black tiles. The 'block' cannot be broken and JEI labels them as "tile.immersiveengineering.conveyor..name". Although this issue does not crash my game or the server it does consume items and sometimes leaves entities as unbreakable without commands to fill the space with air blocks. It is important to note though that these tiles aren't always unbreakable. Sometimes they can be broken and you get an item with the name listed above and sometimes they can be broken but become ghost blocks which reappear when trying to place a different block in its spot. The server was running with.

![2022-04-12_20 46 47](https://user-images.githubusercontent.com/49454307/163144958-a094e8b9-31de-43ea-9ad6-a888c1faf110.png)
![2022-04-08_17 46 12](https://user-images.githubusercontent.com/49454307/163145003-773faa89-5ae4-4d95-8ec7-3f05dd318fa4.png)

Versions & Modlist
This happened while playing a server with my custom modpack on curseforge (Paleocraft) an extended list provided bellow.
I/E 0.12-98
Forge - 14.23.5.2860
[Bantoos server mod list.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/8479861/Bantoos.server.mod.list.txt)
Looking at the contributing page I can see I/E doesn't really like SpongeForge but the server runs so I'm hoping there may be a different reason for this.

**Comment by malte0811** [comment]
1.12 is no longer supported.
