### ISSUE TITLE
Chests, Fluids, and Particles vanishing, Squid bodies on heads.

### ISSUE THREAD

**Issue by Azanorashit** [BluSunrize/ImmersiveEngineering#526]
So yeah, on some spots of worlds chests, outlines showing what your targetting, the crosshair, fluids, boats, railcarts, and particles just stop being rendered. In addition to that, in other spots of worlds, squid bodies will spawn on top of player heads as well as mob heads and bodies, depending on the mob. All this happened after removing IE 0.4.40 and adding 0.6.0. Since an oral explanation doesn't always get through, heres a visual example.

http://webm.host/d6621/

**Comment by BluSunrize** [comment]
Looks like a GL translation is not being reset. Not sure if IE is to blame here though, noone else has reported an issue like this.

**Comment by Azanorashit** [comment]
The only other thing I think could cause it is fastcraft, and I pulle dit out to test and it still happened, just not as often, or at least in the same spots. Dunno what else to say.

**Comment by BluSunrize** [comment]
Okay, what you need to find out is which blocks are coming into view as you rotate. If there is an IE block coming into view it's IE's fault. Otherwise, it's not.

**Comment by cobra** [comment]
Looks very funny, but I didn't notice anything like this either and I've got a test world filled with nearly everything from IE and some other mod stuff. How large is your mod pack? Just in case this is some weird inter-mod issue.

**Comment by Azanorashit** [comment]
only 75 mods, give or take.

**Comment by cobra** [comment]
Did you have any success finding what block could be causing this? If not, could you try bisecting your mod list with a **copy(!!)** of this world to check for a inter-mod issue?
(Disable half of your mods, keeping IE, and test if it still happens. Test the other half as well. If this doesn't change anything, it's not a mod combination causing this. In case only one half of your mods triggers this glitch, disable all mods but half of this half and continue doing this until you have a single culprit. But use a fresh copy of your world for each run, forge will complain about and **delete** missing blocks and items from it. You'll need about 7 steps for this in total.)
You could also disable all mods but IE to find out if some other mod is involved - IE can run as a standalone mod.

**Comment by theunkn0wn1** [comment]
I don't think it is Fastcraft, unable to reproduce this on my modpack (182 mods on the client, modified version of FTB infinity + IE build a9694921e66b996c47bb0548bf296c2d6e6f9599)

Is it a custom modpack or is it something like a FTB pack?

**Comment by Azanorashit** [comment]
>Cobra
I could only get it to work with a combination of mods together, going with without one of hte three doesnt cause it. LMM, Signalum+, and Easy Crafting Table.

>theunkown
Kitchen sink pack, i'm creative enough to build my own packs instead of relying on others to tell me what they think is fun.

**Comment by BluSunrize** [comment]
Okay, so you reproduce this bug with LMM, Signalum+ and Easy Crafting table? I've never heard or used any of them, but how exactly is this an IE issue then?

**Comment by cobra** [comment]
LMM - [LittleMaidMob](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287042-1-7-10-littlemaidmob-report-any-bugs-to-github), adds a maid mob. Uses custom models, I see a lot of potential for nasty renderer bugs.
Can't find anything for signalum+ on google. WTF?
Easy Crafting Table - is it [EasyCrafting](http://www.curse.com/mc-mods/minecraft/224295-easycrafting)? I'd be surprised to find anything related to rendering in this one.

**Comment by BluSunrize** [comment]
Oh LittleMaids. Yeah I remember mDiyo using that xD

**Comment by Azanorashit** [comment]
Because it only happens when IE 0.6.0 is added along with them, without IE it dpesnt happen, and without on of the other three it doesnt happen.

**Comment by Barhandar** [comment]
Given I've never seen this happen with IE by itself, but seen it happen with other mods, the only thing IE can do to it is allow the bug to surface.
