### ISSUE TITLE
[1.18.2] Manual Page Layout Issues

### ISSUE THREAD

**Issue by voidsong-dragonfly** [BluSunrize/ImmersiveEngineering#5260]
## Description of the issue:
Under en_US (dunno about other languages) there's some blank pages in parts of the manual, as well as some formatted very badly
Happening on all GUI scales, and what is shown here are only the most egregious
![image](https://user-images.githubusercontent.com/40431605/163688706-93864bd9-8cf4-4f97-8167-bfc9a919e205.png)
For below, there are two (2) words on the next page, which could be fixed by removing the weird enter at the top
![image](https://user-images.githubusercontent.com/40431605/163688844-6b73149d-8975-405c-91f8-5f99c812c2c9.png)
There's only two on page 9 of the below entry as well, but I didn't want to take up too much space
![image](https://user-images.githubusercontent.com/40431605/163689078-74d38387-3056-400f-8a2a-e3d0fd6f68ce.png)
![image](https://user-images.githubusercontent.com/40431605/163689157-ab00ead9-de3e-47ac-8131-082329b74026.png)
![image](https://user-images.githubusercontent.com/40431605/163689203-d3a067ca-a8aa-4b24-9075-c10507b057b8.png)
For below, these should be spaced out to the pages with the upgrades, right? The other tools do that. The whole thing with overflow here makes everything nonfunctional
![image](https://user-images.githubusercontent.com/40431605/163689254-d3fb9bc8-8c6f-4eab-8ddf-931674e61caa.png)
![image](https://user-images.githubusercontent.com/40431605/163689359-3d314845-18db-4739-bc12-d96f517aefde.png)
![image](https://user-images.githubusercontent.com/40431605/163689373-1aaad8e6-7108-4192-af0b-3bc1deac05aa.png)

## Versions & Modlist
  Forge: 40.0.49
  [✔️] balm-3.0.2+0
  [✔️] cloth-config-6.2.57-forge
  [✔️] engineersdecor-1.18.2-1.1.22-b2
  [✔️] entityculling-forge-mc1.18-1.5.0
  [✔️] FastLeafDecay-28
  [✔️] feature_nbt_deadlock_be_gone_forge-2.0.0+1.18.2
  [✔️] ferritecore-4.2.0-forge
  [✔️] ImmersiveEngineering-1.18.2-8.0.0-147
  [✔️] inventoryessentials-forge-1.18-4.0.1
  [✔️] jei-1.18.2-9.7.0.180
  [✔️] JER-Integration-3.2.1
  [✔️] JustEnoughProfessions-1.18.2-1.2.2
  [✔️] JustEnoughResources-1.18.2-0.14.1.160
  [✔️] Placebo-1.18.2-6.2.1

**Comment by BluSunrize** [comment]
Any further ones you find, just throw in here, I'll get to them at some point.
