### ISSUE TITLE
[1.18.2 | #12] Assembler can't draw full bucket worth of liquid from multiple tanks

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#5263]
The Assembler can't craft a recipe containing a bucket of liquid using liquids from all tanks combined. In other words: It requires 1000mB to be in one of the tanks, and it can't be distributed over multiple ones.

Feels similar to https://github.com/BluSunrize/ImmersiveEngineering/issues/5118, but probably is unrelated.

![grafik](https://user-images.githubusercontent.com/7753414/163839789-6cb627d8-a4e5-4663-9206-276cefeca4dc.png)

**Comment by BluSunrize** [comment]
It would add an reasonable level of complexity to the code to account for this.

This feature never existed before, and I don't value its QoL highly enough to invest development time into it.

**Comment by MalkContent** [comment]
The consequence of this issue is that the liquid gets stuck in there/ends up blocking the slot.
A part of the issue is that when liquid gets added to the tanks, it always uses the first available one instead of checking for tanks that already hold liquid of the to-be-added type.
Would you mind me trying to fix the secondary issue? I don't think this would add an unreasonable amount of complexity.
