### ISSUE TITLE
[1.16.5] Player not able to join

### ISSUE THREAD

**Issue by DemonSlayerKami** [BluSunrize/ImmersiveEngineering#5264]
### Before reporting:
Please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
Also, please give this issue a descriptive name that contains the game version in the title, eg.: "[1.12] Capacitor Interaction Crash"

### Description of the issue:
I run the server but everytime someone tries to join it fails and it keeps saying Internal Exeption: java.io.IOException: An existing connection was forcibly closed by the remote host

### Crashlog:
https://pastebin.com/zTa25TnH

### Versions & Modlist
ImmersiveEngineering-1.16.5-5.0.7-143.jar
on the Crazy Craft Updated 0.7.8 server pack

**Comment by BluSunrize** [comment]
That crashlog is from mod loading, it doesn't tell us anything about issues on joining.

Gonna close this, since issue and log are seemingly unconnected.
