### ISSUE TITLE
IE Villager house too common

### ISSUE THREAD

**Issue by freopt** [BluSunrize/ImmersiveEngineering#5265]
### Description of the issue:
IMO the Immersive Engineering village houses are far too common, I found a village that had four, three in this screenshot alone:
![image](https://user-images.githubusercontent.com/45438411/163896615-ed318e13-4710-4953-aa49-e0f024c5655d.png)

I didn't find a way to configure this either, if there is my bad
### Versions & Modlist
Minecraft 1.18.2
Forge 40.0.54
Immersive Engineering 8.0.1-147

**Comment by freopt** [comment]
Five 
![image](https://user-images.githubusercontent.com/45438411/163898956-319bdc65-a18c-4908-a60b-ba8dcdeccc63.png)

**Comment by malte0811** [comment]
The problem is that each of IEs 5 professions now has its own building (at least in code), and each of those has the same spawn-chance as the combined building had before.

**Comment by BluSunrize** [comment]
I definitely did not consider that when I changed the buildings to be separate, hahaha.

That's on me, I'll look into it!
