### ISSUE TITLE
[1.18.2] Immersive Engineering recipe types aren't registering properly when KubeJS is present

### ISSUE THREAD

**Issue by mosharky** [BluSunrize/ImmersiveEngineering#5266]
### Description of the issue:
Immersive Engineering recipes that use its own data driven recipe type, like `immersiveengineering:blueprint`, do not load properly into the game, or just aren't registering. No custom recipes aside from ones that use the vanilla crafting table work. This is only present when using version `1.18.2-8.0.1-147`, everything is fine with `1.18.2-8.0.0-146`

Trying to add a simple recipe with KubeJS gives me a very strange error almost immediately. This is the script I'd try to run: 
```js
onEvent('recipes', event => {
    event.recipes.immersiveengineeringCrusher('minecraft:diamond', 'minecraft:iron_ingot')
})
```
[This is the KubeJS log when trying to run that script](https://pastebin.com/YUfGfBAT).

This has been tested with just the modlist below, and no KubeJS scripts, with the exact same result. The issue is completely isolated to version 1.18.2-8.0.1-147 of IE when KubeJS is present.

### Crashlog:
[latest.log](https://pastebin.com/BQxKEYmB), no error as far as I can see

### Versions & Modlist
Minecraft: 1.18.2
Architectury v4.2.50
Rhino v1801.1.9-build.135
KubeJS v1802.5.1-build.342
JEI v9.7.0.193
Immersive Engineering v1.18.2-8.0.1-147

**Comment by MaxNeedsSnacks** [comment]
Please do not report this to the Immersive Engineering developers. This is an issue with KubeJS on the latest version of Forge, as our default implementation of RecipeJS.createRecipe does not respect Forge's patched-in IContext and Immersive refuses to parse recipes without a context object

**Comment by MaxNeedsSnacks** [comment]
See also https://github.com/KubeJS-Mods/KubeJS-Immersive-Engineering/issues/5

**Comment by mosharky** [comment]
Ah ok, I thought this would be an issue with Immersive Engineering since downgrading the version had fixed the issue for me

**Comment by BluSunrize** [comment]
Well we don't actually do anything to interact with KubeJS. Any compat is on their side. Literally nothing we can do about it.
