### ISSUE TITLE
Cannot properly obtained a outfitter villager

### ISSUE THREAD

**Issue by kingdom84521** [BluSunrize/ImmersiveEngineering#5267]
### Description of the issue:
![image](https://user-images.githubusercontent.com/26183887/164047374-589ebac9-6909-4887-bcba-6ae8a6e58a8d.png)
Having problem when I want to obtain a outfitter villager. Please note that **my steps are all corect**( place a white banner and use a shader on it by right clicking ), but the career still cannot properly pop out. 

Also, I have been tried the same actions on a minimal instance, it worked normally. So it may be some mod conflict problems since I am playing on a modpack now, named Enigimatica 6: Expert, you can find the modpack by using the link below.
[Curseforge](https://www.curseforge.com/minecraft/modpacks/enigmatica6expert)

### Versions & Modlist
Minecraft version: 1.16.5
Forge version: 1.16.5-36.2.29
IE version: 1.16.5-5.0.7-143

(Modlist will be provide using several images)
![image](https://user-images.githubusercontent.com/26183887/164049078-464add55-2248-408d-bf00-0068647475a4.png)
![image](https://user-images.githubusercontent.com/26183887/164049146-ac925bda-f02f-47be-af5f-12736546efdf.png)
![image](https://user-images.githubusercontent.com/26183887/164049232-e79764b5-2dda-496d-bbaf-7d2d021191c5.png)
![image](https://user-images.githubusercontent.com/26183887/164049317-49bbdd9c-95b3-4661-97e3-ef3daceab1ee.png)
![image](https://user-images.githubusercontent.com/26183887/164049386-d208fe2c-ecff-43f8-be1e-1b40c9d5b08d.png)
![image](https://user-images.githubusercontent.com/26183887/164049448-a3fcfdcb-a82f-4fd8-b8e7-f64d306de7e6.png)
![image](https://user-images.githubusercontent.com/26183887/164049539-b1cd6116-8eb0-41d3-a76d-66231b99e15e.png)
![image](https://user-images.githubusercontent.com/26183887/164049642-9200cc4b-9f00-43f4-97b2-f62e9c1e08f6.png)
![image](https://user-images.githubusercontent.com/26183887/164049731-05675341-6f77-43d6-9824-98a70a382f18.png)
![image](https://user-images.githubusercontent.com/26183887/164049780-508bd2e7-940e-4631-b488-2de69fbb5a03.png)

**Comment by kingdom84521** [comment]
Turns out if you let the villager stay in a narrow place with the specific block, sometime it will not obtain a career. I place the banner at a bigger place and it work.

**Comment by AWDoBaun** [comment]
Actually I think the issue is the villager cannot use a wall mounted banner as a POI, only one that is placed on the floor. I think this should be re-opened as either needing better documentation, or a fix to allow wallmounted banners.
