### ISSUE TITLE
[1.18.2] Add Missing Forge and Vanilla tags to items

### ISSUE THREAD

**Issue by ffuentesm** [BluSunrize/ImmersiveEngineering#5268]
### Description of the issue:
I notice that some blocks have missing tags, both Minecraft and forge ones, this affect some compatibility with crafting recipes, meaning that IE items can't be used on them. 

Here some examples

Stairs: 
![image](https://user-images.githubusercontent.com/44974827/163891173-46463ed4-165f-414e-b665-4d1f54dfa6fb.png)
![image](https://user-images.githubusercontent.com/44974827/163891185-3660433d-38a5-4751-a229-7abe0e15a0da.png)
![image](https://user-images.githubusercontent.com/44974827/163891250-71cba01c-7d70-4693-a999-82ac34577aa1.png)
![image](https://user-images.githubusercontent.com/44974827/163891267-c4db0f17-30e8-4320-9ee8-88757e274448.png)

Slabs:
![image](https://user-images.githubusercontent.com/44974827/163891404-5612ec11-9a67-41af-90e6-8c608799f424.png)
![image](https://user-images.githubusercontent.com/44974827/163891423-a25da0e9-2e22-4bb4-9efd-5693b7e96439.png)
![image](https://user-images.githubusercontent.com/44974827/163891480-6d85e3de-0ea5-4f15-a0d0-e3df208e7290.png)
![image](https://user-images.githubusercontent.com/44974827/163891496-06b51225-2e19-4292-98e1-ff3cb8920bd5.png)

Tools:
![image](https://user-images.githubusercontent.com/44974827/163892953-7dfa8c8e-9716-482f-8f8c-a37cc750489a.png)
![image](https://user-images.githubusercontent.com/44974827/163893071-914629f2-b1f1-4d51-b4a1-26666faef1ba.png)
![image](https://user-images.githubusercontent.com/44974827/163892833-8750e5c1-be9b-4f2f-ac9f-46da510f147e.png)
![image](https://user-images.githubusercontent.com/44974827/163892875-5df4311a-0e8b-464f-b670-1a68d96da946.png)

### Versions & Modlist
ImmersiveEngineering-1.18.2-8.0.1-147.jar
![image](https://user-images.githubusercontent.com/44974827/163893298-9660bb65-8853-4590-9b80-3a7b9f28782f.png)

**Comment by ChloeDawn** [comment]
The (wooden) slabs tags have only been registered to the blocks and not the items, so still do not work in recipes.

![In-game screenshot of an unsuccessful crafting recipe](https://user-images.githubusercontent.com/9869940/182056080-4b92ba36-3bb8-4411-b568-eac7f6652011.png)

```json
{
  "type": "minecraft:crafting_shaped",
  "pattern": [
    "SSS",
    "SCS",
    "SSS"
  ],
  "key": {
    "S": {
      "tag": "minecraft:wooden_slabs"
    },
    "C": {
      "item": "create:large_cogwheel"
    }
  },
  "result": {
    "item": "create:water_wheel"
  }
}
```

**Comment by BluSunrize** [comment]
Kind of a waste to use treated wood there, but valid complaint. =P

**Comment by saltyseadoggo** [comment]
The steel and faraday armor pieces are also missing from `#forge:helmets`, `#forge:chestplates`, `#forge:leggings` & `#forge:boots`. This prevents them from being compatible with other mods' features that use these tags, such as Twilight Forest's armor recrafting function.

**Comment by BluSunrize** [comment]
This issue was closed months ago. Open a new one.

**Comment by saltyseadoggo** [comment]
It was, but you reopened it august of last year and haven't closed it since
![image](https://user-images.githubusercontent.com/69029346/236558846-3e19deb5-387f-4e5c-bf1b-70eecdbc9ab0.png)![image](https://user-images.githubusercontent.com/69029346/236558870-1197b9ff-5570-4a0f-ac27-d8393b495550.png)
