### ISSUE TITLE
Crash upon loading singleplayer and / or multiplayer

### ISSUE THREAD

**Issue by theogjbo** [BluSunrize/ImmersiveEngineering#5269]
### Description of the issue:
As soon as you want to create a singleplayer world it crashes. As soons as you want to join a server with the mod installed, it crashes.
We tried the first 1.18.2 version (Version: "ImmersiveEngineering-1.18.2-8.0.0-146.jar") for forge (curseforge was used for the installation) and the newer version (Version: "ImmersiveEngineering-1.18.2-8.0.1-147.jar").

### Crashlog:
https://gist.github.com/theogjbo/2691db0070f7926a25a4bdfd46f906e2

### Versions & Modlist
FORGE MODLOADER - Version 40.0.48

List of mods:
https://gist.github.com/theogjbo/4dc7bd3ead51ab77c53ae08d8f859ac9

### Lastly (you may delete this from the report itself)
Please, for the love of all that is voxelbased, **read the contribution guidelines. They are linked to the right in the message box.**
When reporting issues, these are crucial, and the team withholds the right to close an issue for the plain stupidity of not reading and adhering to them.

Thank you for reporting issues, without people reporting them, they wouldn't get fixed. You're helping contribute to this mod and that is much appreciated <3

**Comment by malte0811** [comment]
Try either removing or updating Optifine (not 100% sure H7 has the necessary change, but I think so).
