### ISSUE TITLE
[1.18.2] recipe issues with arc furnace and coke oven

### ISSUE THREAD

**Issue by Esseit** [BluSunrize/ImmersiveEngineering#5270]
### Description of the issue:
Newest release seems to break the coke oven and arc furnace recipes, removing both multiblocks full recipe lists. Confirmed they can be added back if using KubeJS however.

### Versions & Modlist
Forge: all version from 40.0.47 to 40.1.0
IE: 1.18.2-8.0.0.-146

Issue persists when IE is all that is loaded and switching the version backwards to 147 solves the issue even on worlds created in 147.

**Comment by malte0811** [comment]
This sounds like #5266, which is a KubeJS bug.
