### ISSUE TITLE
[1.18.2] Wire and Gear Molds won't insert into Metal Press

### ISSUE THREAD

**Issue by Tarsaril** [BluSunrize/ImmersiveEngineering#5271]
### Description of the issue:
When trying to put the Wire Mold and Gear Mold into Metal Presses, neither one gets put into the machine, so we simply can't use metal presses to make either Wires or Gears. This happened on a server initially but is the same in singleplayer, although the issue doesn't happen in an instance of just Forge and IE. It also doesn't happen with Beyond Earth and Applied Energistics 2 added to that base profile, so I don't believe it to be a compatibility issue with those two mods.

### Crashlog:
It doesn't crash, and there are no errors thrown in the server logs at all.

### Versions & Modlist
Forge Version: 40.0.42
IE Version: 8.0.1-147

Complete Mods List from Manual Crash: https://pastebin.com/j7b23fcB

**Comment by BluSunrize** [comment]
It has to be some mod interaction, which means you need to do a binary search:
1. Remove half the mods
2. Check if the issue persists
3. If yes, halve that modlist again; if no, use the other half.

**Comment by malte0811** [comment]
You say you're using IE 8.0.1-147, but the crashlog has 1.18.2-8.0.0-146. Make sure you don't have both IE versions in the mods folder, Forge's mod loading completely breaks when that happens and loads some Frankenstein mix of both versions. I'm closing this for now, if it still happens with 147 please put a comment here and I'll reopen it.
