### ISSUE TITLE
[1.18.2] Crafting grit with the hammer works only once, then the recipe becomes disabled.

### ISSUE THREAD

**Issue by MonaMoonlight** [BluSunrize/ImmersiveEngineering#5275]
Description of the issue:
Crafting a single grit, or attempting to craft multiple grits from raw ore or ore blocks with the hammer results in getting one grit, and then the recipe no longer works after the crafting action, until the save is reloaded.

I first noticed the issue while playing with other mods (listed below), but testing with just Forge and IE revealed the issue still happened with them disabled.

Screengrabs:
Before crafting: ![image](https://user-images.githubusercontent.com/18103381/164878646-65e150e0-3fc6-4959-ae9b-468b384467b9.png)
After crafting: ![image](https://user-images.githubusercontent.com/18103381/164878666-6c923e37-52f4-4bb8-bdda-9e932f2637d2.png)
Showing the same thing happening with raw gold ore: ![image](https://user-images.githubusercontent.com/18103381/164878691-95ce49a4-d61f-4909-9a6e-a018d5568b9c.png)
Showing the same thing happening with an iron ore block, after disabling the other mods: ![image](https://user-images.githubusercontent.com/18103381/164879004-7aab8cd4-cb0d-4465-a7a0-01b1bad20c85.png)
Same thing with a gold ore block: ![image](https://user-images.githubusercontent.com/18103381/164879057-47d1aa4d-a157-4815-bd47-6a69073b2a80.png)

Before attempting to craft a stack of silver grit from raw ore all in one go: ![image](https://user-images.githubusercontent.com/18103381/164879146-d68a6d2c-5af5-4467-b8f6-e2753ae4c2d3.png)

After: ![image](https://user-images.githubusercontent.com/18103381/164879152-157ae8ad-c25a-4200-83f5-10f3e033301c.png)

Versions & Modlist:
Forge - 1.18.2-forge-40.1.0
IE - 1.18.2-8.0.1-147
Farmer's Delight - 1.18.2-1.0.4
JEI - 1.18.2-9.5.5.174
ProjectE - 1.18.2-PE1.0.1

**Comment by BluSunrize** [comment]
And I'm pretty sure I know why that happens:

https://github.com/BluSunrize/ImmersiveEngineering/blob/1.18.2/src/main/java/blusunrize/immersiveengineering/common/crafting/LazyShapelessRecipe.java#L47

This line should be *copying* the ItemStack, because vanilla does just use it from there on without another copy. So as it gets decremented in the slot, it gets decremented in the recipe, thus "using it up".

**Comment by shinji257** [comment]
This is also resulting in duplication issues when interacting with Tom's Simple Storage, Tinker's Construct Crafting Workbench, and Refined Storage.  Rapid clicking (before the recipe gets disabled) gives exponentially increasing numbers until a full stack.
