### ISSUE TITLE
[Port to 1.18] Manual Shader List Info Not Unlocking

### ISSUE THREAD

**Issue by Awesomespore** [BluSunrize/ImmersiveEngineering#5279]
### Description of the issue:
So, I'm actually astonished that this has never been reported, but for a very long time, there has been an issue with the shader list section of the engineer's manual where a lot of the time, the shaders refuse to unlock despite the player having obtained them.
For example, right now in my survival world I own 4 shaders: Phoenix, Qrow, Sponsor and WAAAGH!. In the shader list, WAAAGH! is not unlocked, and seemingly refuses to unlock no matter what.
I've been encountering this same issue for a long time (at least 2 years I think...)
The gameplay detriment this introduces is that the shader list allows unlocked shaders to be created by providing some metal dust, and if the shader doesn't unlock, well, you can't create them that way.

### Crashlog:
Issue does not involve a crash.

### Versions & Modlist
Mod version: 1.16.5-5.0.7-143
Forge version: 36.2.33
Other mods (I'm almost certain this issue is NOT caused by other mods in any way, but I'll still provide the list): https://pastebin.com/jcmvF9SL

**Comment by BluSunrize** [comment]
>  I'm actually astonished that this has never been reported, but for a very long time, there has been an issue

So you knew of this for a "very long time"? Why didn't you report it!? Why wait until 1.16.5 is being dropped?

I'll look into this one

**Comment by Awesomespore** [comment]
I honestly don't know why I never reported it... guess I never thought to until just recently being reminded of it.

**Comment by BluSunrize** [comment]
As soon as the new version is released, that there is the fix for it.

You'll have to throw the shaders that aren't unlocked on the floor and pick them back up to unlock them.

**Comment by BluSunrize** [comment]
Reopening so I remember to port this

**Comment by BluSunrize** [comment]
Ported to 1.18
