### ISSUE TITLE
Unable to add Crusher recipe with MineTweaker

### ISSUE THREAD

**Issue by mdfntr** [BluSunrize/ImmersiveEngineering#528]
I am creating a personal modpack and would like to prefer the Thermal Foundation ingots/dusts/etc. for everything. As a result, I've had to minetweak some of the Crusher recipes:

    mods.immersiveengineering.Crusher.removeRecipe(<ImmersiveEngineering:metal:16>);
    mods.immersiveengineering.Crusher.addRecipe(<ThermalFoundation:material:39>, <ore:ingotElectrum>, 3600);

This unfortunately does not work:

    ERROR: > a method available but none matches the parameters (minetweaker.item.IItemStack, minetweaker.oredict.IOreDictEntry, int)

Looking in IE's Minetweaker compat code, I see that the signature of the Crusher's add recipe is:

    addRecipe(IItemStack output, IIngredient input, int energy, @Optional IItemStack secondaryOutput, @Optional double secondaryChance)

So, I tried casting the `IOreDictEntry` to an `IIngredient`:

    val oreIngotElectrum = <ore:ingotElectrum> as minetweaker.item.IIngredient;
    mods.immersiveengineering.Crusher.addRecipe(<ThermalFoundation:material:39>, oreIngotElectrum, 3600);

Which results in:

    ERROR: > a method available but none matches the parameters (minetweaker.item.IItemStack, minetweaker.item.IIngredient, int)

But that's the signature of the method! What's up with this? Am I doing something silly/wrong? I saw on [Reddit](https://www.reddit.com/r/feedthebeast/comments/3b2qlq/immersive_engineerings_minetweaker_support_has/csi8qvb) that the Crusher compatibility wasn't quite working, but that was 3 months ago.

Also, does anyone have enough Minetweaker expertise: do I have to cast in a value/variable statement or is it possible to cast the `IOreDictEntry` directly in the function call? Are there methods on an IOreDictEntry? I've read a lot of code tonight and am getting frustrated with ZenScript's lack of proper documentation.

**Comment by Barhandar** [comment]
Maybe `IIngredient` requires an actual, singular item instead of an array. In that case, if you somehow figure how to apply all elements of OD entry to a recipe without excess copypasta (i.e. in a loop), tell?

**Comment by mdfntr** [comment]
Taking this advice, I tried the following modification:

    val oreIngotElectrum = <ore:ingotElectrum> as minetweaker.item.IIngredient;
    val arraryElectrum = oreIngotElectrum.items as minetweaker.item.IIngredient[];
    for i in arrayElectrum {
        mods.immersiveengineering.Crusher.addRecipe(<ThermalFoundation:material:39>, i, 3600);
    }

This returns this error:

    ERROR: Error executing scripts.zs: Not yet implemented

I'm confused: why do I get a useful error message when using an `IIngredient` that only contains an item stack, when `IIngredient`s are supposed to be able to hold ore dictionary entries? I'm also disappointed--this doesn't seem *that* hard to implement in three months...it's just one API call!

**Comment by mdfntr** [comment]
Update: it seems that either `.items` method is not yet implemented or some sort of casting is not implemented on MineTweaker's end--this last error is not ImmersiveEngineering's fault.

Trying anew, with a hand-coded array:

    val arrayElectrum = [<ThermalFoundation:material:71>, <ImmersiveEngineering:metal:6>] as minetweaker.item.IIngredient[];
    for i in arrayElectrum {
        mods.immersiveengineering.Crusher.addRecipe(<ThermalFoundation:material:39>, i, 3600);
    }

This still give the old `a method available but none matches the parameters (minetweaker.item.IItemStack, minetweaker.item.IIngredient, int)` error.

**Comment by mdfntr** [comment]
AH-HA!

The commit 067c69e added the `@Optional` annotation to several of the MineTweaker compat methods. This commit was made on September 1, 2015, which is later than the most recent released version of ImmersiveEngineering available on CurseForge, which is from August 20. Thus, the `Crusher.addRecipe` method that exists in source is different in the version I am currently running! The actual signature of the method is `IItemStack output, IIngredient input, int energy, IItemStack secondaryOutput, double secondaryChance`. This script works properly:

    mods.immersiveengineering.Crusher.addRecipe(<ThermalFoundation:material:39>, <ore:ingotElectrum>, 3600, null, 0);

Closed.
