### ISSUE TITLE
[1.18.2]game flash exit without crash report after 100% of loading chunks.

### ISSUE THREAD

**Issue by rtxyd** [BluSunrize/ImmersiveEngineering#5280]
### Description of the issue:
Game normally entered title screen, flash exit entering any save. And no crashreport because game exist background in details of windows taskmanager.

### Crashlog:
https://gist.github.com/rtxyd/400dbf82c3b57e649591c47b350f221d
I think most important part is below
> Mixin apply failed immersiveengineering.mixins.json:accessors.client.CompiledChunkAccess -> net.minecraft.client.renderer.chunk.ChunkRenderDispatcher$CompiledChunk: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException No candidates were found matching f_112749_:Ljava/util/Set; in net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$CompiledChunk for immersiveengineering.mixins.json:accessors.client.CompiledChunkAccess->@Accessor[FIELD_GETTER]::getHasBlocks()Ljava/util/Set; [INJECT Applicator Phase -> immersiveengineering.mixins.json:accessors.client.CompiledChunkAccess -> Apply Accessors ->  -> Locate -> immersiveengineering.mixins.json:accessors.client.CompiledChunkAccess->@Accessor[FIELD_GETTER]::getHasBlocks()Ljava/util/Set;]
org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching f_112749_:Ljava/util/Set; in net/minecraft/client/renderer/chunk/ChunkRenderDispatcher$CompiledChunk for immersiveengineering.mixins.json:accessors.client.CompiledChunkAccess->@Accessor[FIELD_GETTER]::getHasBlocks()Ljava/util/Set; [INJECT Applicator Phase -> immersiveengineering.mixins.json:accessors.client.CompiledChunkAccess -> Apply Accessors ->  -> Locate -> immersiveengineering.mixins.json:accessors.client.CompiledChunkAccess->@Accessor[FIELD_GETTER]::getHasBlocks()Ljava/util/Set;]

### Versions & Modlist
ImmersiveEngineering-1.18.2-8.0.1-147
1.18.2-forge-40.1.0
modlist:
(https://gist.github.com/rtxyd/768dfc021c83587397e45a503337f8e1)

with only IE it's no problem.

**Comment by rtxyd** [comment]
I think I add too many mods, I don't want make your team bothered but if this is a potential bug, maybe helpful. If not, I'd like to find incompatibile mod myself

**Comment by malte0811** [comment]
Remove or update Optifine. This is fixed in H7 (together with some changes in IE 147, which you're already using), but generally Optifine is not supported and most things that aren't a straight crash won't get fixed.

**Comment by rtxyd** [comment]
It seems I post a stupid issue. Which I should have noticed. Sorry.
