### ISSUE TITLE
[1.18.2] Coke Oven and Crude Blast Furnace produce "Empty Tag: forge:coal_coke" & "Empty Tag: forge:ingots/steel" rather than the correct items.

### ISSUE THREAD

**Issue by slayster** [BluSunrize/ImmersiveEngineering#5284]
Just started a new custom modpack, modlist here: https://pastebin.com/x39SCh8m
Forge: 4.1.0
IE: 1.18.2-8.0.1-147

When putting coal in the coke oven I get an "Empty Tag: forge:coal_coke" item instead of the actual item.
![2022-05-01_16 52 15](https://user-images.githubusercontent.com/637763/166154821-c8d9a9df-4f38-4bce-8acd-d2a06030e6a6.png)

In the Crude Blast Furnace it won't accept the empty tag item as an input and it I use regular charcoal I get the item "Empty Tag: forge:ingots/steel" instead of a Steel Ingot.
![2022-05-01_16 53 22](https://user-images.githubusercontent.com/637763/166154886-a526a9ee-1f8a-412b-8a48-a75be1e7e521.png)

Seems like I'm unable to proceed in the mod because of this and not sure where to start debugging this.

**Comment by malte0811** [comment]
Try updating Cooking For Blockheads and Balm.

**Comment by slayster** [comment]
Thanks that sorted it! Sorry for the bother about an issue which technically wasn't from this mod.
