### ISSUE TITLE
Where's the texture of the wire？

### ISSUE THREAD

**Issue by xuwuwudi** [BluSunrize/ImmersiveEngineering#5286]
### Description of the issue:

The wire texture disappeared

### Versions & Modlist
1.18.2 forge40.1.0 OptFineH7
![2W2{1PPM5B6`G@@KT~V4N92](https://user-images.githubusercontent.com/84704462/166627540-4455e0ff-315e-4cdf-b1b1-8b456bff3df3.png)
![BE3 {DG$)H2YR_$CRU~XNBL](https://user-images.githubusercontent.com/84704462/166627545-af1ffc17-2116-48aa-82a3-c9ab952f8279.png)

**Comment by malte0811** [comment]
Unable to reproduce, even with OF. Are you using the latest build of IE (1.18.2-8.0.1-147)?

**Comment by xuwuwudi** [comment]
> Unable to reproduce, even with OF. Are you using the latest build of IE (1.18.2-8.0.1-147)?

Yes, and then I'll give you my mods list
![image](https://user-images.githubusercontent.com/84704462/166628918-8c6bf499-9337-4d10-ac99-74ea124d36ab.png)

**Comment by xuwuwudi** [comment]
> > Unable to reproduce, even with OF. Are you using the latest build of IE (1.18.2-8.0.1-147)?
> 
> Yes, and then I'll give you my mods list ![image](https://user-images.githubusercontent.com/84704462/166628918-8c6bf499-9337-4d10-ac99-74ea124d36ab.png)


I removed opt and the texture reappeared...
![image](https://user-images.githubusercontent.com/84704462/166629244-2854a93f-a7b5-4c06-adeb-e707fffc4c89.png)


I know the problem
This is a problem with render regions in opt
When OFF, the texture reappeared
![image](https://user-images.githubusercontent.com/84704462/166630067-777745c7-9727-40c8-a851-69e339d08515.png)

**Comment by BluSunrize** [comment]
Well issue resolved then.

Optifine is not supported.
