### ISSUE TITLE
[1.16.5] Seeds from Mystical Agriculture won't grow in a Garden Cloche

### ISSUE THREAD

**Issue by Quintiliu5** [BluSunrize/ImmersiveEngineering#5289]
Is there a way to fix a problem, where you can't grow Mystical Agriculture Seeds in a Garden Cloche?

**Comment by BluSunrize** [comment]
Yes, install a datapack that has those recipes. There are multiple of them on CurseForge, go look.

IE has no native support for Mystical Agriculture. We removed it ages ago, because it was entirely too powerful.
