### ISSUE TITLE
Broken wire and/or pole transformer rendering

### ISSUE THREAD

**Issue by cobra** [BluSunrize/ImmersiveEngineering#529]
Having wires and transformers attached to poles in the same chunk causes a wire-coloured overlay.
LV (and MV, just a different shade of brown):
![](https://cloud.githubusercontent.com/assets/163331/10695997/1e0eace2-79a7-11e5-950e-dbb0d786eb94.png)
HV:
![](https://cloud.githubusercontent.com/assets/163331/10696245/2ef64e16-79a7-11e5-8911-68874d28d98f.png)
Hemp rope and steel cable are also doing this.

Looks like stuff doesn't get reset after rendering.

Minor, but might be related to this: lighting glitches with disabled smooth lighting. The pattern looks like something doesn't get reset after rendering the block, just like above and #484. Also, shouldn't all of them be bright like the top ones? If I remove the big transformer, they all turn dark again, the big transformer seems to repair the lighting for all following blocks. This only works when the transformer is facing west/east (1/3), north/south (2/0) doesn't do anything. Placing a creative energy cell with f=0,2 makes them brighter, f=1,3 makes them render even darker.
![](https://cloud.githubusercontent.com/assets/163331/10695084/129c56b6-79a2-11e5-981a-52718e9279a1.png)
Putting a connector on top of either the transformer or the energy cell resets the lighting:
![](https://cloud.githubusercontent.com/assets/163331/10695763/cac01fae-79a5-11e5-8341-e63f6a04173a.png)
btw: placing a connector there shouldn't be possible, I guess.

There is some strange lighting without smooth lighting also happening with conveyors, but does only affect neighbouring conveyors, not all of them in the same chunk. See #530.

**Comment by malte0811** [comment]
Changing the `offsetLighting` parameter to 1 instead of -1 [here](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/client/render/TileRenderTransformer.java#L64) fixes this, but I am not sure what said parameter does, changing it may break other stuff.

**Comment by cobra** [comment]
That doesn't sound like the expected place for this bug, more like a trigger for an "accidental" fix. My guess: `Tessellator.draw()`  isn't called for the wire alone but instead by something else, combing the settings. Javadoc for `draw()`:
>Draws the data set up in this tessellator and resets the state to prepare for new drawing.

The unused `renderAllIEConnections` method does call it, but I couldn't find such a call in the current rendering chain for the wires - but maybe I didn't look at the right places. As I said earlier, I'm not familiar with the whole rendering stuff and just taking guesses here.

**Comment by BluSunrize** [comment]
I can't call draw(). Wire's are rendered in ISRBH. IF you call draw in there it you'd have to restart the Tessellator, which defeats the entire purpose of using the static rendering. This looks more like a colouring issue.

**Comment by cobra** [comment]
I just looked over the `offsetLighting`stuff: it's definitely strange that the pole transformer is the only case in which this argument is -1. The only other value besides 0 and 1 is a 2 when called by a pump return null for getWorldObj.

**Comment by BluSunrize** [comment]
The reason it's 2 there is because Unwritten wrote that renderer. 0 is default lighting, 1 is vertex based lighting anything else (I use -1 he use 2 for whatever reason) is no lighting.

**Comment by BluSunrize** [comment]
^ try it with that commit @cobra and tell me if the transformers still have weird discolouration

**Comment by cobra** [comment]
well…
![2015-10-26_21 32 22](https://cloud.githubusercontent.com/assets/163331/10741668/38bc09e8-7c29-11e5-902c-bde746f83088.png)
that's exactly what I got when I tried resetting the colour.

Also, placing blocks (to trigger a render update) causes this (the scaffolding is a complete tower from the ground):
![2015-10-26_21 33 04](https://cloud.githubusercontent.com/assets/163331/10741706/6f9fea7e-7c29-11e5-95ce-cef44f2acf1b.png)

Adding @malte0811's fix (offsetLighting -1 → 1) gets me this:
![2015-10-26_21 36 25](https://cloud.githubusercontent.com/assets/163331/10741778/b7588b1e-7c29-11e5-8a93-6f36ce293b85.png)

**Comment by BluSunrize** [comment]
And if you change -1 to 0? Transformer at default lighting?
Because 0 is preferable where possible.

**Comment by cobra** [comment]
I can't see any difference after setting this to 0 instead of 1. So I guess 0 it is then?

**Comment by BluSunrize** [comment]
Yes please. If it gets iffy with blocks placed aroudn it later, we can try 1.

**Comment by cobra** [comment]
I'll just try placing blocks all around such a "transformer tree" to see what's breaking. Does anyone want to bet how many more lighting issues I can find? :P

**Comment by BluSunrize** [comment]
A lot. because ISRBH lighting sucks butt ._.

**Comment by cobra** [comment]
Nothing too crazy. Done with 0.
![2015-10-26_21 48 56](https://cloud.githubusercontent.com/assets/163331/10742051/5fb45e86-7c2b-11e5-85c0-087a85247f1d.png)
And again using 1 (and replacing a block):
![2015-10-26_21 50 03](https://cloud.githubusercontent.com/assets/163331/10742088/8f18b41a-7c2b-11e5-9c7e-8e70c7b830a5.png)

**Comment by BluSunrize** [comment]
ah, I think that black stuff was why I used -1 in the first place. Oh well. Some renderderps will always exist, we'll just leave it as is. You wanna PR the 0 @cobra? I mean it's a 1 minute thing in my local ^^"

**Comment by cobra** [comment]
I can do that, I've got some other small stuff in my pipeline as well. I'll just do another collection PR later if that's okay for you.

**Comment by BluSunrize** [comment]
What did you break about it? (since it's not fully done yet anyway it might not be a break >_>)

**Comment by BluSunrize** [comment]
Oh and I hope to finish 0.6 up within this week if possible

**Comment by cobra** [comment]
one: it doesn't accept items when mirrored (fixed, trivial)
two: the tap is offset AND not over the bottle while filling it, it's lagging behind. I think I'll leave this for you, I couldn't see anything obvious yet, that whole code moving stuff around isn't very easy to scan through (not surprising when looking at what it does). Removing `GL11.glTranslated(shift/2,0,0);` does fix the tap being offset to the left (non-mirrored version), but it's still lagging behind.

**Comment by BluSunrize** [comment]
It's supposed to be offset. It starts at the position where it'd meet the item. As for lagging behind, I'll need a picture of that.

**Comment by cobra** [comment]
offset - this did look better in your preview video. It also doesn't move to the right side of the "block" it's attached to but stops in the middle of it.
![](https://cloud.githubusercontent.com/assets/163331/10743187/ca589fda-7c31-11e5-87a2-bad0f2407d8f.png)

Lagging behind:
![](https://cloud.githubusercontent.com/assets/163331/10743194/d093302c-7c31-11e5-884c-6d60acb71607.png)

**Comment by BluSunrize** [comment]
Oh nevermidn, yeah
tat was me doing stuff with the obj model and then exportign it again. Will fix.

**Comment by cobra** [comment]
Hah! I thought it was the model being broken at first, but that looked fine in blender, but that explains it.

**Comment by BluSunrize** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/3c9524ecc9baeeac5c02b9c9e9c49cbcb751ffde

Fixed!

**Comment by cobra** [comment]
Looks perfect. I've noticed that very rarely few bottles don't seem to get inserted, I'm just trying hard to reproduce and debug this.
Unless I find some other minor stuff, that's what I'll PR later: https://github.com/BluSunrize/ImmersiveEngineering/compare/master...cobra:fixes1?expand=1 and unless you commit stuff I have to test combined with this, I won't rebase this branch again.

**Comment by BluSunrize** [comment]
bottles are only accepted every 24 ticks
So there there's always 20% of processing space in order to not confuse the tap.

**Comment by cobra** [comment]
Yep, I know. They were just hanging out and bouncing around with the bottling machine sitting there idling without processing a single one.

**Comment by BluSunrize** [comment]
that might be a collision thing then. If the item not really on the conveyor anymore or something...

**Comment by cobra** [comment]
yep, that's what I suspect. It didn't happen again but I mangaged (again, only once and I didn't get the breakpoint set fast enough, damn!) to have two bottles ride the internal conveyor together. wtf.

**Comment by cobra** [comment]
![](https://cloud.githubusercontent.com/assets/163331/10745434/119d93d6-7c42-11e5-9b4b-c03a251b843b.png)
WTF?!
`inventory` looks fine, 5 itemStacks with stackSize=1
`process` is 44 12 108 76 36.

**Comment by cobra** [comment]
Found the problem for this one. `getNextProcessID()` is broken and checking the wrong slots. Testing…

**Comment by BluSunrize** [comment]
@cobra the "pos" values for the bottling machine where off. They didn't mirror correctly on structure formation, that's why the input block was screwed up. I fixed this with https://github.com/BluSunrize/ImmersiveEngineering/commit/f359555bc1621a0f0b7422b8d163d930f8bde855
I'm sorry that this makes your fix invalid, but this is the actual way it should work, since pos values need to be fixed like this ^^'

**Comment by malte0811** [comment]
@cobra is right, there are cases in which `getProcessID()` returns a slot instead of -1. Example:
- insert 5 bottles
  - process is: `12345` (The bottle with index 0 will be the first to finish since it has the lowest number, etc.)
- Insert another 4 bottles, they will get inserted once the first 4 bottles have finished processing
  - process is: `67895`
- **Wait** until 2 bottles have processed, **afterwards** insert 2 bottles:
  - process is:
  - after waiting: `X789X` (X means no bottle)
  - after inserting the first bottle: `A789X` (I am using hexadecimal numbers) (9 was used as the previous bottle)
  - after inserting the second bottle directly afterwards: `A789B` (**9 was used as the previous bottle instead of A**).

I have an idea for a fix (changing the array to be used kind of like a static size stack), which I will implement and PR this afternoon (unless @BluSunrize implements some fix before that)

**Comment by cobra** [comment]
I'm testing a much simpler solution for this: find the next empty slot the same way as it is now and then check that every other slot's process is >24.

**Comment by cobra** [comment]
My solution for this: https://github.com/cobra/ImmersiveEngineering/commit/617eee87295dc6964aa7ee60133cfb7136654870
I tested this quite a lot and couldn't break it.

But now the whole changes @BluSunrize did while I was working on this broke everything and I need to fix this patch again. Also, I can't seem to form the bottling machine in its mirrored form.

**Comment by cobra** [comment]
Updated and force-pushed the commit above, works again and is independent of the -1/0 as "nothing" process change (which I still think needs to be changed, either by initializing to -1 or resetting to 0).
I'm looking into the not-working-with-an-energy-cell issue.
I also noticed that TD's itemducts sometimes disconnect from the input and don't reconnect again, but that's not really reproducible. The output doesn't connect at all, so TD isn't ideal for interfacing with the bottling machine. Not sure what to do about the input issue.

**Comment by BluSunrize** [comment]
Thermal mods are also stupid in caching. You need to break and replace energy cells after forming a multiblocks because they check where they can output to once and then cache that and never check again or something >_>

**Comment by cobra** [comment]
It's a block update thing. Placing any block adjacent to cells or ducts fixes this.

One last thing: the internal tank is 8000 mb and filling is only done once in a single operation, so the bottling machine can't completely fill a jerrycan without re-inserting it. Should we do something about this? What? How? The worst case would be inserting a bedrockium drum from ExU with a capacity of 65536000 mb, so this isn't going to happen while the tap moves.
*I somehow feel we should have moved this whole thread to a different issue a while ago. Whoops.*

**Comment by cobra** [comment]
@malte0811 do you still want to try your idea or should we just use my solution? I'll just PR this one, but could remove or change that commit if you guys want a different solution.
I decided against aborting early when finding an item with process<24 to limit the work done in the inner loop. The cost of adding another check there could outweigh the benefits in my opinion.
