### ISSUE TITLE
[1.12.2] Engineering Blocks Rendering Incorrectly - Causing Multiblocks to Break

### ISSUE THREAD

**Issue by Blueberrypie255** [BluSunrize/ImmersiveEngineering#5292]
[Minecraft Glitched Mods.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/8692222/Minecraft.Glitched.Mods.txt)
Hi! I am having a large bug with that modpack that make it unplayable. 

Mods:
ImmersiveEngineering - 0.12-98.jar
Immersiveintelligence - 0.2.1.jar
Immersivepetroleum - 1.12.2-1.1.10.jar
Immersiveposts - 0.2.1.jar
ImmersiveRailroading - 1.12.2-forge-1.9.1.jar
TrackAPI - 1.1
UniversalModCore - 1.12.2-forge-1.1.4-2b81e7.jar

With only these mods, the game works fine. However, after adding them into a modpack, the game does not work. The textures for the engineering blocks (redstone, light, and heavy) are bugged. I do not believe that other blocks are bugged. I am attaching the mod list that I have to this post. I just need to know which mods to remove. 

Thank you!

**Comment by Blueberrypie255** [comment]
Also, the biggest issue is that the multiblock isn't fully finished. By that, I mean that (with WAILA or a sifferent mod that shows the item), only 1/2 of the blocks appear to be the crusher. The rest appear to be "light engineering, steel scaffolding, and the redstone engineering block." It seems that these blocks will not become part of the multiblock. However, the shape and textures changed, and the "hitboxes" also moved. Plus, the multiblock fills with power, and shows the "crushing" animation plus the sound. The Tile Class is "class bluesinrize:immersiveengineering.commin.blocks.metal.TileEntityCrusher".
The Tile ID is "immersiveengineering:crusher".

Also, I attached a video of me showing the different tags and IDs.
![Capture](https://user-images.githubusercontent.com/96138089/168411672-86783ce6-56f6-4758-8dd4-a09fb715facd.PNG)
This is the video:
https://www.youtube.com/watch?v=McUT9bGmgkM


This is really just an edit to the above post.

**Comment by malte0811** [comment]
1.12 is no longer supported.
