### ISSUE TITLE
Wires deleting themselves (No its not due to overcharging)

### ISSUE THREAD

**Issue by S6464** [BluSunrize/ImmersiveEngineering#5293]
### Description of the issue:
I have rigged up a minecraft village with MV wired power poles with transformers that step down to LV to power the powered lanterns, (some of the power poles are immersive posts) the problem is that the LV wires keep deleting themselves, before anyone says its because they are overloading, idk how because the total RF demand of the town doesn't exceed the maximum rated RF of an LV connector.   

![BugMaybe](https://user-images.githubusercontent.com/61964346/168594877-ddad029f-8cbc-4669-911c-08314a9d54e2.PNG)

### Versions & Modlist

MC Version: 1.16.5
Forge Version: 36.2.35
IE Version: 1.16.5-5.0.7-143
Modlist: https://pastebin.com/kVAqyiRh

**Comment by BluSunrize** [comment]
Remove optifine and see if the issue persists.

**Comment by S6464** [comment]
> Remove optifine and see if the issue persists.

I'll run it for a bit without optifine and get back to you.

**Comment by S6464** [comment]
So it wasn't optifine, the Iron Golems were earthing out the wires

**Comment by BluSunrize** [comment]
That'd do it.
