### ISSUE TITLE
[Feature Request] Allow Bottling Machine to wait until container is filled

### ISSUE THREAD

**Issue by cheri-song** [BluSunrize/ImmersiveEngineering#5294]
### Description

I was told to post this as an issue on the discord, so here it is.

As far as I know, there is no good way to automate jerrycan filling with IE's Bottling Machine. Because the internal fluid buffer of the Bottling Machine is smaller than the capacity of the jerrycan, putting jerrycans on a Bottling Machine line will just give you a bunch of partially filled jerrycans.

There is probably some way for the user to resolve this with complicated redstone mechanisms, but this is unsatisfying and it feels like there should be a better way to automate it using only IE machines.

### Suggestion

Give Bottling Machines a new functionality that can be toggled with the screwdriver. Instead of filling the container with whatever's in the buffer and then moving to the next one, it should wait until the container is fully filled before outputting it.

### Alternatives

* Allow the Bottling Machine to be upgraded with a larger tank or more pumps for more throughput.
* Add a new Hose Pump machine specifically for filling jerrycans (lol)

**Comment by BluSunrize** [comment]
I had a look into this, it's not as easy as I hoped it would be, so I'll postpone it for a future release.

I want it to come with a proper option for the machine to switch between "keep item until full" and all that stuff, which is not a quick change. As a release of fixes is necessary atm, this will be pushed back to the release after that.
