### ISSUE TITLE
1.16.5 minecraft is crashing after loading, with java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by 7H40** [BluSunrize/ImmersiveEngineering#5296]
Details:
	Mod File: ImmersiveEngineering-1.16.5-5.0.7-143.jar
	Failu
re message: Immersive Engineering (immersiveengineering) encountered an error during the load_registries event phase
		java.lang.NullPointerException: null
[latestlog.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/8708122/latestlog.txt)

**Comment by BluSunrize** [comment]
1. Use the issue template
2. Put your logs on pastebin or gist, I don't want to download your files
3. Reproduce this with only IE installed. If you can't it's a cross-mod issue, so check the other mods that you have installed to find the conflict.

**Comment by mindforger** [comment]
just for the giggles ... He is using a launcher that runs java mc in android ... This makes the question of testing without other mods all more important ... This includes ANY optimisation mod like optifine, betterfpsdist and not enough crashes ... Last one is personal opinion...

And lastly for your conveniance in future reports ... Copied from your (not crash- but latest-) log ...
Crash report saved to /storage/emulated/0/games/PojavLauncher/.minecraft/crash-reports/crash-2022-05-17_07.29.58-fml.txt

**Comment by BluSunrize** [comment]
@mindforger There was literally zero reason for you to add anything to this issue. I had already responded to it, received no reply and then closed it.
If one of the devs is already on the ball, you don't need to add to it.
