### ISSUE TITLE
Crafting Table ingredients visually duplicate exponentially as they're used

### ISSUE THREAD

**Issue by aaronhowser1** [BluSunrize/ImmersiveEngineering#5297]
### Description of the issue:

https://user-images.githubusercontent.com/15698722/168993176-2e6ea39e-f50a-4696-8cdb-b2a321a32d19.mp4

This is fixed upon closing and reopening the GUI

### Versions & Modlist
ImmersiveEngineering-1.16.5-5.0.7-143
Forge 36.2.35
Minecraft 1.16.5

**Comment by BluSunrize** [comment]
Can't reproduce this. Likely a cross-mod interaction.

I'd recommend a binary search here, though any of the mods hooking into inventories (such as a sorting mod) would be my immediate suspects.

And with no detailed mod list given here, I'm gonna close this one.
