### ISSUE TITLE
where i download it

### ISSUE THREAD

**Issue by carlobon** [BluSunrize/ImmersiveEngineering#53]

**Comment by GirafiStudios** [comment]
No where, it's not released yet..

**Comment by Iomega0318** [comment]
You have to compile it yourself, I would like to know if there is a more updated version however since this version is actually quite outdated and according to OpenEye there is a newer version.

http://openeye.openmods.info/mod/immersiveengineering

**Comment by carlobon** [comment]
how can i compile it

**Comment by PawnedSauce** [comment]
You don't deserve to compile it if you don't know how

**Comment by carlobon** [comment]
But when is it going to be released?

**Comment by BluSunrize** [comment]
When it's done. And this page is for issues with the mod. And yes, the updated versions exist, because ForgeCraft has them.

**Comment by Flexico** [comment]
Is there a mailing list I can sign up for that will let me know when it's released?

**Comment by BluSunrize** [comment]
Yep. It's called Twitter.

**Comment by Flexico** [comment]
Oh, I wasn't aware there was a twitter feed about it! Thanks.
