### ISSUE TITLE
Lighting calculation broken when smooth lighting is disabled

### ISSUE THREAD

**Issue by cobra** [BluSunrize/ImmersiveEngineering#530]
Smooth lighting on maximum:
![](https://cloud.githubusercontent.com/assets/163331/10698083/6f0d5a50-79af-11e5-8e97-1d32db8a2947.png)

Smooth lighting on minimum:
![](https://cloud.githubusercontent.com/assets/163331/10698100/834f3bfa-79af-11e5-9555-1dc3bad30b4d.png)

Smooth lighting disabled:
![](https://cloud.githubusercontent.com/assets/163331/10698106/8cd4a728-79af-11e5-98a0-850cfb06843d.png)

All screenshots above were taken facing west (f=1).

**Comment by BluSunrize** [comment]
due to how conveyors are rendered when horizontal this isn't really avoidable, and a minor issue. I tinkered with the lighting on these for ages, and this was the best I could do.

**Comment by cobra** [comment]
Is this somewhat related or is it another problem? Look at the brightness of the back.
![2015-10-26_20 13 11](https://cloud.githubusercontent.com/assets/163331/10739674/1cb11726-7c1e-11e5-9d30-7d82a3c53eba.png)
![2015-10-26_20 13 13](https://cloud.githubusercontent.com/assets/163331/10739676/21a9028e-7c1e-11e5-8afd-50e509d2c0cf.png)
Doesn't matter wether smooth lighting is on max or off.

**Comment by BluSunrize** [comment]
Probably because the block with the fluid port renders the whole thing as an ISRBH .~.

**Comment by cobra** [comment]
It's only this position triggering a brightness change - and the one to the right of the grass block. Placing a solid block there will make the right side (not visible in these screenshots) of the bottling machine a bit brighter. All other positions around it didn't seem to affect it as far as I could tell.

It's definitely not a major problem worth spending a lot of time on. The enormous `calculateBlockLighting` method doesn't look like much fun could be had in there debugging this. Still, maybe someone could find out what's going on here.
