### ISSUE TITLE
"hemp rope coil invisible and no hitbox" 

### ISSUE THREAD

**Issue by KirbyBrasse** [BluSunrize/ImmersiveEngineering#5300]
### Description of the issue:
I put hemp rope coil on two structural cable connector game say they are connected, and it disappeared from my hand but there is nothing visible and no hitbox.
I dont use optifine i use Iris. 

### Versions & Modlist
1.18.2-8.0.1-147

**Comment by BluSunrize** [comment]
That's not a modlist.

Try it without Iris

**Comment by KirbyBrasse** [comment]
ok i found the problem "Rubidium" was to blame

**Comment by Br00t4L17y** [comment]
I was seeing this as well with all wires and ropes from IE in version 1.18.2. It was caused by Optifine, because I had the Options > Video Settings > Performance > Render Regions set to ON. Changing this setting to OFF fixed my issue, I can see wires and ropes now.

**Comment by Dr-WeiAL** [comment]
Are there plans to be compatible with Rubidium? I also had issues with cables not being visible

**Comment by malte0811** [comment]
No, Rubidium requires even more hacks than OptiFine in this case. I've implemented them as a separate mod [here](https://github.com/malte0811/rubie) ~~([build](https://cdn.discordapp.com/attachments/536644558403141692/974606314271539280/rubie-0.0.jar))~~, but they will not be added to IE itself. Wires should work with that, but I don't know how much is still broken.

Edit: Builds are now done via GH releases, [this](https://github.com/malte0811/rubie/releases/latest) link should always point to the latest one.

**Comment by Dr-WeiAL** [comment]
> No, Rubidium requires even more hacks than OptiFine in this case. I've implemented them as a separate mod [here](https://github.com/malte0811/rubie) ([build](https://cdn.discordapp.com/attachments/536644558403141692/974606314271539280/rubie-0.0.jar)), but they will not be added to IE itself. Wires should work with that, but I don't know how much is still broken.

Thanks! This did fix the issue with the cables not being visible

**Comment by Jasu** [comment]
> No, Rubidium requires even more hacks than OptiFine in this case. I've implemented them as a separate mod [here](https://github.com/malte0811/rubie) ([build](https://cdn.discordapp.com/attachments/536644558403141692/974606314271539280/rubie-0.0.jar)), but they will not be added to IE itself. Wires should work with that, but I don't know how much is still broken.

Thanks! That definitely fixed it, though the code was not as hacky as promised - I was expecting an endless spaghetti jungle of mixins and rewritten copies of Sodium's guts. Glad to be disappointed :+1:
