### ISSUE TITLE
Minecraft 1.12.2(Forge 14.23.5.2860) Possible conflict between IE and Immersive Intelligence resulting in a fatal error when closing the engineer's manual server side only.

### ISSUE THREAD

**Issue by phirebird27** [BluSunrize/ImmersiveEngineering#5301]
Currently running a server with the attached mod list thorough the CurseForge Launcher.  A strange phenomena is occurring that only when closing a (crafted in this case) Engineer's Manual a fatal error occurs and you are disconnected from the server. The issue cannot be replicated in a single player instance and effects all players who try to use the book. Unfortunately our server and clients do not produce crash reports as a result to this error and the closest thing I can find is the server's "latest" log.
The most recent error before being forcefully disconnected is a follows (found near the bottom of the log);
"[Netty Epoll Server IO #2/ERROR] [FML]: There was a critical exception handling a packet on channel immersiveintelli
java.lang.NoClassDefFoundError: net/minecraft/client/Minecraft...." 

[latest (3).log](https://github.com/BluSunrize/ImmersiveEngineering/files/8748167/latest.3.log)
[Parasite_Survival.zip](https://github.com/BluSunrize/ImmersiveEngineering/files/8748168/Parasite_Survival.zip)

**Comment by malte0811** [comment]
1.12 is no longer supported.
