### ISSUE TITLE
[1.18.2] /im mineral put autocomplete crashes game

### ISSUE THREAD

**Issue by TobiasDeBruijn** [BluSunrize/ImmersiveEngineering#5302]
### Description of the issue:
When entering `/im mineral put` in the chat, the game will crash

### Crashlog:
https://pastebin.com/3EecbTb5

### Versions & Modlist
https://pastebin.com/sSJ5vydf
Forge: `1.18.2-40.1.20`

**Comment by malte0811** [comment]
Fixed in 86211504ad15b866e6df4685eb16c239cd6f16bb
