### ISSUE TITLE
[1.16] Disable Engineer Hammer's villager trade

### ISSUE THREAD

**Issue by Z4RM** [BluSunrize/ImmersiveEngineering#5303]
**Hello!**

I would like to disable the Engineer Hammer's villager trade, but it's neither in the config nor in the data folder. Is there a way to do this?

**Versions**
IE : 5.0.7-143
Forge : 36.2.35

Thank you very much by advance,
**Z4RM**

**Comment by BluSunrize** [comment]
Nope, not possibly. Vanilla trades are a very messy system, and there is no particularly clean way to make them configurable.
