### ISSUE TITLE
[Direwolf20 1.18.2] Server gets stuck loading world during RetroGeneration

### ISSUE THREAD

**Issue by Infinituum17** [BluSunrize/ImmersiveEngineering#5305]
My server (hosted on my pc, I'm playing with my friends in Multiplayer) keeps getting stuck when it tries to load the world, and the last message is always about Immersive Engineering's retrogen.

I don't have screenshot but I had to delete the file "chunks.dat" in the "world" folder to play again.

Neither Minecraft nor the server crashed. Only the server got stuck. I only tried to start it after I closed it yesterday.
It happens everytime I start the server without deleting "chunks.dat".

Versions:
Forge 40.1.20 - 1.18.2
IE 8.0.1-147

The modlist is included in Direwolf20's latest pack (v. 1.2.0) on FTB launcher.

**Comment by radonn24** [comment]
I am having the same issue ... DW20 1.18 v 1.2.0

EDIT ... I was unable to solve this issue with 1.2.0 version of the DW20 pack ... but, I simply downloaded, and setup the 1.3.1 version of the DW20 pack, and moved my unmodified `world` folder over ... all working now!

**Comment by BluSunrize** [comment]
So I'll treat this as fixed by a new release of the DW pack then.
