### ISSUE TITLE
[1.16.5] Adding a fluid as a biodiesel generator fuel?

### ISSUE THREAD

**Issue by SanjivanM** [BluSunrize/ImmersiveEngineering#5306]
Is there a way to add a fluid, eg. minecraft:lava as a fuel for the Biodiesel generator? I've looked through the scripts and data folders but can't seem to find a datapack/ CraftTweaker script/ API usage "template" to use.  I see that common/IERecipes.java has a "generator_fuel" recipe type, but I can't seem to find where/ how that's implemented

**Comment by SanjivanM** [comment]
wait... nevermind... looks like I found the datapack format while browsing through the commit changes here (https://github.com/BluSunrize/ImmersiveEngineering/commit/987a23dd39913ea0a2e2bc8f515cacf015dccb90)

**Comment by SanjivanM** [comment]
Well, I thought I had it, and closed this too soon lol.  The following code does not seem to be working, and instead, logs an error in latest.log

ethanol.json: (placed in myDataPack\data\immersiveengineering\recipes\generator_fuel
(yes, the data pack was zipped before I added it into my world)
`{"type":"immersiveengineering:generator_fuel","fluidTag":"forge:ethanol","burnTime":500}`

The error logged:
`com.google.gson.JsonSyntaxException: Invalid or unsupported recipe type 'immersiveengineering:generator_fuel'
`
Latest.log file, error is at around line 100090
[latest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/8790085/latest.log)

**Comment by BluSunrize** [comment]
You're using an outdated version of IE.
