### ISSUE TITLE
[1.18.2] Rendering bug with Radium Reforged

### ISSUE THREAD

**Issue by jal21** [BluSunrize/ImmersiveEngineering#5307]
yes i know that this is a port of Lithium to forge but.
you cant see wires when placed and also you cant see multi block recipes from the book.
Mods:
   1.18.2-betteramethyst-1.0.1
   3dskinlayers-forge-1.4.5-mc1.18.2
   adaptive_performance_tweaks_1.18.2-3.4.0
   adaptive_performance_tweaks_core_1.18.2-3.5.2
   adaptive_performance_tweaks_gamerules_1.18.2-3.5.1
   adaptive_performance_tweaks_items_1.18.2-3.5.1
   adaptive_performance_tweaks_mods_1.18.2-3.7.3
   adaptive_performance_tweaks_player_1.18.2-3.5.1
   adaptive_performance_tweaks_spawn_1.18.2-3.5.2
   AdvancementPlaques-1.18.2-1.4.3
   AI-Improvements-1.18.2-0.5.0
   alexsdelight-1.18.2-1.2.3
   alexsmobs-1.18.3
   alloyed-1.18.2-v1.3c
   AmbientSounds_FORGE_v5.0.16_mc1.18.2
   Amplified_Nether_v1.1.1
   angelring-1.18-1.5.0
   Apotheosis-1.18.2-5.3.5
   appleskin-forge-mc1.18-2.4.0
   Applied-Botanics-1.0.1
   appliedenergistics2-11.0.0
   architectury-4.4.65
   ars_elemental-1.18.2-0.4.0
   ars_nouveau-1.18.2-2.4.2
   arsarsenal-1.1-1.18.2
   artifacts-1.18.2-4.0.7
   AttributeFix-Forge-1.18.2-14.0.2
   AutoRegLib-1.7-53
   balm-3.0.3+0
   BetterAdvancements-1.18.2-0.2.0.129
   BetterCompatibilityChecker-1.1.14-build.26+mc1.18.2
   BetterF3-1.2.5-Forge-1.18.2
   betterfpsdist-1.18.2-1.5
   betterinvisibility-1.18.1-1.0.3
   BetterModsButton-v3.2.2-1.18.2-Forge
   biomemakeover-FORGE-1.18.2-1.4.21
   BiomesOPlenty-1.18.2-16.0.0.109-universal
   blue_skies-1.18.2-1.3.12
   blueprint-1.18.2-5.3.2
   Bookshelf-Forge-1.18.2-13.0.13
   Botania-1.18.2-432
   brass_armory-1.18.2-1.0.1-beta
   bucolicorigins-3.2[FORGE-CHOOSE-COMPATIBLE]
   bygonenether-1.1.2-1.18.2
   caelus-forge-1.18.1-3.0.0.2
   camera-1.18.2-1.0.2
   castle_in_the_sky-1.18.2-0.4.1
   Cataclysm-0.18 -congfig fix
   catalogue-1.6.2-1.18.2
   cfm-7.0.0-pre29-1.18.2
   chickensshed-1.18.1-1.3.1-forge
   Chunky-1.2.164
   citadel-1.11.3-1.18.2
   clickadv-1.18.2-2.5
   clienttweaks-forge-1.18.1-7.1.0
   cloth-config-6.2.62-forge
   Clumps-forge-1.18.2-8.0.0+8
   cofh_core-1.18.2-1.6.3.19
   collective-1.18.2-4.25
   ColossalChests-1.18.2-1.8.3
   comforts-forge-1.18.2-5.0.0.4
   Companion-1.18.2-forge-2.0.1
   Compat-O-Plenty-1.18.2-1.5.1
   configured-1.5.3-1.18.2
   connectivity-1.18.2-2.9
   Controlling-forge-1.18.2-9.0+19
   corail_woodcutter_extension_byg-1.0.1
   corail_woodcutter-1.18.2-2.3.3
   CosmeticArmorReworked-1.18.2-v2
   crashutilities-4.0
   createaddition-1.18.2-20220517a
   createcafe-1.4-1.18.2
   create-confectionery1.18.2_v1.0.8
   create-mc1.18.2_v0.4.1
   createplus-1.18.2_v0.4.0.0
   create-stuff-additions1.18.2_v1.1.6
   CreativeCore_FORGE_v2.6.9_mc1.18.2
   curios-forge-1.18.2-5.0.7.0
   cursery-1.18.2-2.9
   CyclopsCore-1.18.2-1.13.6
   DarkPaintings-Forge-1.18.2-10.0.3
   dcintegration-forge-2.4.2-1.18.2
   Decorative Blocks-forge-1.18.2-2.1.0
   defaultoptions-forge-1.18.1-14.1.0
   dimdungeons-160-forge-1.18.2
   Ding-1.18-1.3.0
   domesticationinnovation-1.4.1-1.18.2
   DungeonsArise-1.18.2-2.1.50d-beta
   dynamic_asset_generator-forge-1.18.2-0.6.0
   eccentrictome-1.18.2-1.2.1
   ecologics-FORGE-1.18.2-1.6.7
   EnchantmentDescriptions-Forge-1.18.2-10.0.3
   enderchests-1.18-1.9.5
   endercrop-1.18.2-1.7.0-beta
   endertanks-1.18-1.11.6
   EnigmaticLegacy-2.21.1
   Enlightened End BB V1.1
   entityculling-forge-mc1.18-1.5.1
   excavated_variants-forge-1.18.2-0.6.2
   expandability-6.0.0
   ExplorersCompass-1.18.2-1.2.1-forge
   fancymenu_forge_2.7.2_MC_1.18.2
   FarmersDelight-1.18.2-1.1.1
   FarmersRespite-1.18.2-1.2.0
   farsight-1.18.2-1.8
   FastFurnace-1.18.2-6.0.3
   FastLeafDecay-28
   FastSuite-1.18.2-3.0.2
   FastWorkbench-1.18.2-6.0.2
   feature_nbt_deadlock_be_gone_forge-2.0.0+1.18.2
   ferritecore-4.2.1-forge
   flywheel-forge-1.18-0.6.2
   forgivingvoid-forge-1.18.1-6.0.1
   FpsReducer2-forge-1.18.2-2.0
   ftbbackups2-forge-1.18.2-1.0.9
   ftb-library-forge-1802.3.6-build.119
   ftb-quests-forge-1802.3.8-build.101
   ftb-teams-forge-1802.2.6-build.51
   geckolib-1.18-forge-3.0.18
   Gem Crabs undergarden v.1.0.1
   GemCrabs Gobber v.1.0.2
   GemCrabs v.1.0.7
   global_packs-forge-1.18.2-1.12.2
   Gobber2-Forge-1.18.2-2.6.26
   grappling_hook_mod-1.18.2-v13
   hexcasting-1.18.2-0.8.3
   hexerei-0.1.19
   honeyexpansion-1.1.1
   hourglass-1.18.2-1.2.1.0
   Iceberg-1.18.2-1.0.44
   idas_forge-1.1.6+1.18.2
   immersive_armors-1.3.3
   ImmersiveEngineering-1.18.2-8.0.1-147
   IntoTheVoid-1.18.2_V1.0.3
   inventorysorter-1.18-19.0.0
   item-filters-forge-1802.2.7-build.27
   jei-1.18.2-9.7.0.195
   JEIEnchantmentInfo-1.17.1-2.0.0
   journeymap-1.18.2-5.8.4-forge
   JustEnoughResources-1.18.2-0.14.1.167
   Kiwi-1.18.2-forge-6.1.0
   konkrete_forge_1.3.3_MC_1.18-1.18.1
   kotlinforforge-3.3.2-obf
   lazydfu-1.0-1.18+
   LibX-1.18.2-3.2.15
   loadmyresources_1.0.1_MC_1.18
   lootintegrations-1.18.2-1.4
   macawsbridgesbop-1.18.2-1.1
   macawsbridgesbyg-1.18.2-1.1
   malum-1.18.2-1.3.6
   Mantle-1.18.2-1.9.20
   mcw-bridges-2.0.3-mc1.18.2
   mcw-doors-1.0.6-mc1.18.2
   mcw-fences-1.0.4-mc1.18.2
   mcwfencesbop-1.18.2-1.1
   mcwfencesbyg-1.18.2-1.0
   mcw-lights-1.0.3-mc1.18.2
   mcw-trapdoors-1.0.5-mc1.18.2
   mcw-windows-2.0.3-mc1.18.2
   Mekanism-1.18.2-10.2.0.459
   MekanismAdditions-1.18.2-10.2.0.459
   MekanismGenerators-1.18.2-10.2.0.459
   MekanismTools-1.18.2-10.2.0.459
   minecraft-comes-alive-7.2.1+1.18.2-forge
   mmlib-1.0.2-1.18.2
   ModernUI-1.18.2-3.4.5.106-universal
   modnametooltip-1.18.1-1.18.0
   moreoverlays-1.20.5-mc1.18.1
   MouseTweaks-forge-mc1.18-2.21
   Mushlings-1.18.2-1.0.0
   MythicBotany-1.18.2-2.1.4
   Natural Decoration v.1.0.7
   NaturesAura-36.1
   NaturesCompass-1.18.2-1.9.5-forge
   NekosEnchantedBooks-1.18.2-1.7.0
   NethersDelight-1.18.2-2.2.0
   Nimble-1.18-forge-2.2.1
   notenoughanimations-forge-1.6.0-mc1.18.2
   occultism-1.18.2-1.33.3
   oculus-mc1.18.2-1.2.4
   Oh_The_Biomes_You'll_Go-forge-1.18.2-1.4-RC-21
   omgourd-1.18.2-1.6.0.4
   Origins-1.18.2-1.4.1.1-unified
   origins-classes-forge-1.1.3
   ortus-1.18.2-1.0
   otyacraftengine-forge-1.18.2-2.14
   PackingTape-1.18.2-0.12.5
   Patchouli-1.18.2-67
   paucal-1.18.2-0.3.4
   Pehkui-3.3.1+1.18.2-forge
   Placebo-1.18.2-6.4.0
   PlayerRevive_FORGE_v2.0.1_mc1.18.2
   pneumaticcraft-repressurized-1.18.2-3.2.3-84
   polymorph-forge-1.18.2-0.44
   PuzzlesLib-v3.3.5-1.18.2-Forge
   Quark-3.2-357
   questsadditions-1.18.2-1.3.1
   radium-0.7.10
   repurposed_structures_forge-5.1.9+1.18.2
   RingsOfAscension-1.18.2-1.0.1
   RootsClassic-1.18.2-1.1.23
   rubidium_extras-1.18.2_v1.3.1
   rubidium-0.5.2a
   SBM-Jukebox-1.18-1.0.4
   selene-1.18.2-1.16.2
   Serene Seasons-1.18.2-7.0.0.13
   ServerTabInfo-1.18.2-1.3.5
   shetiphiancore-1.18-3.10.9
   SimpleBackups-1.18.2-1.1.8
   SlimyBoyos-forge-1.18.2-4.0.0.7
   slimydrops-1.0.0-release-1.18.2
   smoothchunk-1.18.2-1.9
   SneakyCurses-v3.0.0-1.18.2-Forge
   SnowRealMagic-1.18.2-forge-4.0.0
   snowundertrees-1.18.2-1.2.1
   sophisticatedbackpacks-1.18.2-3.16.4.584
   sophisticatedcore-1.18.2-0.1.0.19
   spark-1.9.1-forge
   stalwart-dungeons-1.18.2-1.2.2
   starlight-1.0.2+forge.546ae87
   structure_gel-1.18.2-2.3.0
   supermartijn642corelib-1.0.18-forge-mc1.18
   supplementaries-1.18.2-1.4.0
   TConstruct-1.18.2-3.5.0.17
   TelePass-1.18-1.1.2
   TerraBlender-forge-1.18.2-1.1.0.101
   Terralith_v2.2.1a
   the_bumblezone_forge-5.0.11+1.18.2
   The_Undergarden-1.18.2-0.7.0
   The_Wild_Update_Mod_V1.3_Minecraft_1.18
   theoneprobe-1.18-5.1.0
   thermal_cultivation-1.18.2-1.6.1.9
   thermal_expansion-1.18.2-1.6.1.11
   thermal_foundation-1.18.2-1.6.2.27
   thermal_innovation-1.18.2-1.6.1.10
   thermal_locomotion-1.18.2-1.6.0.6
   ThisRocks-1.18.2-1.0.2
   tombstone-7.4.6-1.18.2
   toms_storage-1.18.2-1.3.1
   trashcans-1.0.15-forge-mc1.18
   trashslot-forge-1.18.1-11.0.2
   TravelersTitles-1.18.2-Forge-2.1.1
   UniversalBoneMeal-v3.0.5-1.18.2-Forge
   villagernames_1.18.2-3.5
   wandering-bag-1.18.2-1.0.3
   waystones-forge-1.18.2-10.0.0
   worldedit-mod-7.2.10
   YungsApi-1.18.2-Forge-2.0.8
   YungsBetterDungeons-1.18.2-Forge-2.1.0
   YungsBetterMineshafts-1.18.2-Forge-2.1.3
   YungsBetterStrongholds-1.18.2-Forge-2.1.1
   YungsBridges-1.18.2-Forge-2.1.0
   YungsExtras-1.18.2-Forge-2.1.0
   zmedievalmusic-1.18.2-1.4

**Comment by jal21** [comment]
I am still getting the Rendering bug with Radium Reforged excluded from the pack and the pack owner doesn't know what else could of course, so. Is there any other know mods that could cause this.
The pack that i am playing is Homebacked pack on curse forge.

**Comment by malte0811** [comment]
The two issues you describe are completely unrelated:
1. The multiblock preview in the manual is an interaction with Radium/lithium, this will be fixed in the next 1.18.2 build (by commit 912dc73afda60a110857fc6e71541b3d11fbd256).
2. The wire issue is an interaction with Rubidium, and will not be fixed in IE since that requires some very hacky code. See https://github.com/BluSunrize/ImmersiveEngineering/issues/5300#issuecomment-1139724675 for a workaround.
