### ISSUE TITLE
Wire Vanish in 1.18.2 no mod pack 

### ISSUE THREAD

**Issue by Pandacore420** [BluSunrize/ImmersiveEngineering#5308]
### Introduction

Hello fellas! 

I'm pretty new to IE but I think I'm working my way through. I love the mod so far! 

### The Issue

My only problem or bug so far is when I use the wires. I've watched tutorials and read some entry's about wire problems but none seem to fit my exact problem. I'm running on Single-player with some other mods (I will list them further down). When I place any wire it just vanishes. I can still interact with it or disconnect it using the wire cutters but I just can't see it. It is transferring RF but it isn't visible. This happens with every wire type and connector type. 

### Crashlog 
Well there is none! My game runs smooth and didn't crash at any times. 

### Versions & Modlist
Minecraft 1.18.2
Forge 40.1.0

IE 1.18.2-8.0.1-147
Chunk Loaders 1.1.12
Simple Inventory Sorter 19.0.0
SuperMartijn642's Config Lib 1.0.9
SuperMartijn642's Core Lib 1.0.18
MrCrayfish's Furniture Mod 7.0.0-pre29
Journeymap 5.8.0beta18
Just Enough Items 9.5.5.174
Falling Leaves 1.3.2

### Testing 
I found it a bit funny to post a bug report here for this kind of problem so I did some testing before. The issue is not related to other mods. It is still occurring even with IE running alone. What I have to mention is that I'm not on super great system. I'm usually running with 60fps and that's enough for me. I had a couple of driver problems lately, it took me hours to find the right updates to run games smoothly again. That's why I'm not sure if it's just a graphics card issue but I'm too scared to try because it's running all right for now. 
If you need my hardware specs too I will post them if you request. 

### Lastly 

Thank you for the great work! I've heard of IE back in the days of Tekkit or FTB in 2015/16. I was very happy to see that this mod is still on track. I hope that I reported this right considering this is my first bug report ever. 
Keep up the good work!

**Comment by Br00t4L17y** [comment]
Do you have any performance mods installed like Optifine or Rubidium? I have personally had issues with Optifine causing wires and ropes from IE to not show up. #5300

**Comment by BluSunrize** [comment]
Optifine or Rubidium are the likely suspects.

A full modlist / debug crash is required here.

**Comment by Pandacore420** [comment]
So one simple test and you guys were instantly right. I forgot to mention Optifine (Optifine1.18.2-HD-H7) and im really sorry for that. Removed optifine and was able to see the cables. Just one problem without OptifineHD im unable to play the game in any way. I get like 10 to 20 fps constantly (cause this game is still trash). Is there a workaround for this? A different version of optifine maybe?
Ive found a crash report that should work for you, although i think this report was generated when i was experimenting with some other mods and different versions cause the game never crashed because of the invisible cables. 
[crash-2022-05-29_23.00.59-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/8797837/crash-2022-05-29_23.00.59-client.txt)
 I will do some trial and error in the meantime and big thanks for the fast help!

**Comment by Br00t4L17y** [comment]
I would first check the setting Options > Video Settings > Performance > Render Regions and make sure that is set to OFF. That is what caused the issue for me.

**Comment by Pandacore420** [comment]
You were totally right, turning Render Regions Off was the right thing. And i can keep Optifine since there are no other problems with OF and IE, thanks a lot! Since my Problem is now fixed im going to close the thread here. Again thanks for the great help!
