### ISSUE TITLE
Arc furnace texture change broken

### ISSUE THREAD

**Issue by cobra** [BluSunrize/ImmersiveEngineering#531]
Switching the Arc Furnace on or off does not update the texture without a block update in the same chunk.

As far as I understand it, doing a texture switch with a ISBRH isn't really possible without more or less running into the infamous TinkersConstruct chunk rerender problem, especially considering how the Arc Furnace switches to inactive and back to active when finishing an item when processing a single stack.
I'm not that familiar with the whole rendering stuff, so I don't really have a clue on how to solve this the most elegant way.

**Comment by BluSunrize** [comment]
Well, by running a chunk update, obviously. Which is doable, it's what a vanilla furnace does too.

**Comment by Barhandar** [comment]
Vanilla furnace isn't the most elegant, or the most well-coded, block in the game.

**Comment by BluSunrize** [comment]
I didn't say it was. But it's (afaik) the only way to update textures on an ISRBH.

**Comment by cobra** [comment]
That's what I wanted to point out by "the most elegant way". I know it can be done, but maybe someone else has a different, more elegant way of doing this whole texture update.
Could moving the glowing texture effects to `renderDynamic` help or does this create more problems than it could solve? (Z-fighting?)

Going the chunk update wouldn't be that horrible like in TCon - it's not triggered that often and could be reduced further by reworking the processing logic of the arc furnace a bit to avoid doing too many updates by flickering off and on again while still having resources to process.

**Comment by BluSunrize** [comment]
*grmbl*

I'll look into doing it in the TESR without having to move the entire render back there
