### ISSUE TITLE
[1.16.5] Not able to change Recycling Recipes

### ISSUE THREAD

**Issue by Saphirius** [BluSunrize/ImmersiveEngineering#5310]
Dont know if this is the right place, but the guidelines dont prohibit these kind of issues, so here goes:

### Description of the issue:
Neither with KubeJS nor with CraftTweaker im able to change recycling recipes. In the Changelog from 1.16.5-4.2.2-132 it is said that theres documentation on how to change it via datapacks, but i cant seem to find the documentation.

### Versions & Modlist
Forge 1.16.5-5.0.7-143

**Comment by BluSunrize** [comment]
Yep, that can't be done anymore because of how and when they are generated.

Sorry!
