### ISSUE TITLE
Crashing On Launch

### ISSUE THREAD

**Issue by xxdeadshotz** [BluSunrize/ImmersiveEngineering#5312]
https://pastebin.com/7Vrxq3Q1

**Comment by ItsHarvey** [comment]
Currently incompatible with Twilight Forest, if you disable or remove it, should start fine

**Comment by xxdeadshotz** [comment]
Wait then why can I play on the server but she can’t

**Comment by malte0811** [comment]
Known and fixed for the next release in 78b65f01b0c1e799156a5ff8b6686d9709da6b0c.
