### ISSUE TITLE
[1.18.2] More IE Tool Anvil Repair

### ISSUE THREAD

**Issue by voidsong-dragonfly** [BluSunrize/ImmersiveEngineering#5314]
### Description of the issue:
IE tools cannot be repaired with what items it would make sense to repair them with.

The tools missing what I think are natural repair materials are below:
 - [x] Engineer's Hammer
 - [x] Engineer's Wirecutters
 - [x] Faraday Suit
 - ~~Steel Sawblade~~
 - ~~Possibly (?) Rockcutting Sawblade~~
 - [ ] Mineral Survey Tools (I'll explain below)

What I think the tools should use:
 - [x] Iron: Engineer's Hammer, Engineer's Wirecutters
 - [x] Aluminium: Faraday Suit
 - ~~Steel: Steel Sawblade~~
 - ~~Diamond: Rockcutting Sawblade~~
 - [ ] Written Book **or** Paper : Mineral Survey Tool

The mineral survey tools use a book/paper because I imagine the tools being used up as the data book being filled, so it makes sense to grab a new book or more paper right before you finish out the last one - the paper exists if repair must be four items

### Versions & Modlist
Forge: 40.0.49
  [✔️] balm-3.0.2+0
  [✔️] cloth-config-6.2.57-forge
  [✔️] engineersdecor-1.18.2-1.1.22-b2
  [✔️] entityculling-forge-mc1.18-1.5.0
  [✔️] FastLeafDecay-28
  [✔️] feature_nbt_deadlock_be_gone_forge-2.0.0+1.18.2
  [✔️] ferritecore-4.2.0-forge
  [✔️] ImmersiveEngineering-1.18.2-8.0.1-147
  [✔️] inventoryessentials-forge-1.18-4.0.1
  [✔️] jei-1.18.2-9.7.0.180
  [✔️] JER-Integration-3.2.1
  [✔️] JustEnoughProfessions-1.18.2-1.2.2
  [✔️] JustEnoughResources-1.18.2-0.14.1.160
  [✔️] Placebo-1.18.2-6.2.1
  [✔️] spark-1.8.14-forge

**Comment by BluSunrize** [comment]
I dislike the sawblades being repairable, I think I prefer people to craft new ones.
However, making them recycleable sounds like a good alternative!

**Comment by voidsong-dragonfly** [comment]
Drill heads are repairable. but that does make some sense!
