### ISSUE TITLE
[1.18.2] Coal Coke Should Be In #minecraft:coals

### ISSUE THREAD

**Issue by voidsong-dragonfly** [BluSunrize/ImmersiveEngineering#5315]
### Description of the issue:
Coal Coke cannot currently be used as a stand-in for any high-carbon fuel source, though by rights it should be able to be.
Functionally bituminous coal coke is very close to _anthracite_, is a coal with almost 100% carbon. Coke should be usable as coal.

Solution: add coal coke to `#minecraft:coals`, shown below for its use in torches
![image](https://user-images.githubusercontent.com/40431605/171904473-80b1e9c6-fc10-4e52-ac72-1d9d16df5448.png)

### Versions & Modlist
Forge: 40.0.49
  [✔️] balm-3.0.2+0
  [✔️] cloth-config-6.2.57-forge
  [✔️] engineersdecor-1.18.2-1.1.22-b2
  [✔️] entityculling-forge-mc1.18-1.5.0
  [✔️] FastLeafDecay-28
  [✔️] feature_nbt_deadlock_be_gone_forge-2.0.0+1.18.2
  [✔️] ferritecore-4.2.0-forge
  [✔️] ImmersiveEngineering-1.18.2-8.0.1-147
  [✔️] inventoryessentials-forge-1.18-4.0.1
  [✔️] jei-1.18.2-9.7.0.180
  [✔️] JER-Integration-3.2.1
  [✔️] JustEnoughProfessions-1.18.2-1.2.2
  [✔️] JustEnoughResources-1.18.2-0.14.1.160
  [✔️] Placebo-1.18.2-6.2.1
  [✔️] spark-1.8.14-forge

**Comment by BluSunrize** [comment]
So fun fact? The vanilla torch recipe does not use that tag, lmao:
```json
"X": [
  {
    "item": "minecraft:coal"
  },
  {
    "item": "minecraft:charcoal"
  }
]
```

It specifically allows coal and charcoal.
But the tag *is* used by campfires. So I guess that's nice. :'D

**Comment by voidsong-dragonfly** [comment]
That's... I guess some mod of mine there is replacing it then XD
