### ISSUE TITLE
[1.18.2] Greater Variety of Slag Uses

### ISSUE THREAD

**Issue by voidsong-dragonfly** [BluSunrize/ImmersiveEngineering#5316]
### Description of the issue:
Currently, slag is mostly worthless in IE. You can use it for concrete, but an excavator on a silt vein produces more sand than you need for concrete. You'll use it before that, but it gets pushed out of there in the endgame, and even then, not everyone uses concrete. You can grind it to sand, but sand already comes from the excavator. It's usable in a fertilizer that's okay in the short-term but uses an uncommon material, where a bone farm is free.

Though I cannot suggest common uses, I can suggest a _variety_, which may be more useful here:
 - [x] Slag should be smeltable into "Slag Glass". Slag Glass is red-brown and mostly opaque (think insulating glass but clearer)
     - [x] Slag Glass should be usable to craft Insulating Glass without the iron, as it already has iron inside of it (waste)
     - [ ] Slag Glass should be usable to craft _tinted glass_ with amethyst and make **3**, just like the 1.5x on vanilla for concrete
     - [ ] Slag Glass could also be used as a way to make terracotta cheaper, or to make _brick_ cheaper, as it is ceramic
 - [x] Slag should grind to gravel, not sand. This means you can make _all_ of vanilla concrete and some other nice things with it
     - [x] Possibly make slag a storage block that's a sort of gravel, and make coral fans grow well on it [source](https://www.ispatguru.com/properties-and-uses-of-steelmaking-slag/)  

  

Plausible Slag Glass recipes:
![image](https://user-images.githubusercontent.com/40431605/171907613-2a2edb7d-906b-43c0-b5eb-c641ef7849f1.png)
Brick block there is a kiln from another mod, just FYI

### Versions & Modlist
Forge: 40.0.49
  [✔️] balm-3.0.2+0
  [✔️] cloth-config-6.2.57-forge
  [✔️] engineersdecor-1.18.2-1.1.22-b2
  [✔️] entityculling-forge-mc1.18-1.5.0
  [✔️] FastLeafDecay-28
  [✔️] feature_nbt_deadlock_be_gone_forge-2.0.0+1.18.2
  [✔️] ferritecore-4.2.0-forge
  [✔️] ImmersiveEngineering-1.18.2-8.0.1-147
  [✔️] inventoryessentials-forge-1.18-4.0.1
  [✔️] jei-1.18.2-9.7.0.180
  [✔️] JER-Integration-3.2.1
  [✔️] JustEnoughProfessions-1.18.2-1.2.2
  [✔️] JustEnoughResources-1.18.2-0.14.1.160
  [✔️] Placebo-1.18.2-6.2.1
  [✔️] spark-1.8.14-forge

**Comment by lordi-erez** [comment]
>  Maybe also have it suck up creosote? Unsure on the use but this might be a fun one

make it lava, and it'll be awesome

when mining deep underground or in the nether, you end up with these tiny lava pools, these things suck

**Comment by voidsong-dragonfly** [comment]
That's not how it works, it's not a sponge....? It sucks up creosote because that is the _binder_, not because slagwool works like a sponge. Lava would either be so cooled and sticky the slagwool would turn into cobblestone, or it'd be hot enough to melt/deform the slag wool into a useless shape - lava is slow-moving when under about 1800C, and slagwool is quite close to rock - blown rock into insulation, but rock.

**Comment by lordi-erez** [comment]
nice to know

**Comment by voidsong-dragonfly** [comment]
Issue completed to satisfaction with build 151 & 9491ea29eb782d43af17659e1bc002131fb17252
