### ISSUE TITLE
[1.18.1] Broken redstone acid Create compat recipe (DUPE BUG)

### ISSUE THREAD

**Issue by LilJagty** [BluSunrize/ImmersiveEngineering#5320]
### Description of the issue:
With Create installed, IE automatically adds a Mixer recipe for redstone acid that uses a water bucket and 4 redstone dust in the mixer and outputs a redstone acid bucket. However, Create's mixer recipes automatically output an empty bucket if a liquid bucket is used in crafting. **Therefore, this recipe duplicates the bucket every time it's used.** To fix this issue, mix redstone dust with liquid water in the mixer, not a water bucket.

### Versions & Modlist
Minecraft 1.18.1
Forge 39.1.2
Create v0.4f
ImmersiveEngineering-1.18.1-7.1.0-145

**Comment by malte0811** [comment]
@simibubi The crafting recipe uses a custom implementation of `getRemainingItems` to make sure this does not happen in standard crafting. Is there any way for us to indicate to Create that it should either ignore the recipe entirely or not return a bucket from it?

**Comment by BluSunrize** [comment]
Yeah this is not an IE issue per se. Create adds the recipes for its mixer automatically from all shapeless crafting recipes. We have no hand in this.

**Comment by simibubi** [comment]
Hi! 
An easy way out would be to suffix the recipe's id with "_manual_only". This has been our way to communicate to create not to consider a recipe valid for automated compatibility.

**Comment by BluSunrize** [comment]
That seems rather unreliable. May I ask why the Create Mixer doesn't just handle `getRemainingItems` properly?

**Comment by malte0811** [comment]
If that is impossible for whatever reason, you could reflectively check if a recipe overrides `getRemainingItems` and prevent those recipes from being used in a mixer.

**Comment by simibubi** [comment]
Righto- I'll see what I can do
My apologies
