### ISSUE TITLE
[Feature Request] Allow changing windmill strength depending on biome

### ISSUE THREAD

**Issue by enimog** [BluSunrize/ImmersiveEngineering#5321]
Right now, the windmill strength is the same everywhere and only depend on weather. I think the default behavior should stay that way. But I would like a way to override that value by either using a datapack or a config option in the config file for specific dimensions / biomes. The value would be a multiplier (1 = default, 0 = windmill disabled, 1.50 = windmill is 50% faster in that biome, could be capped at a reasonable value)

My reasoning is that not all environment have the same wind strength and it would be nice to allow it to be more realistic.

Use case : Compatibility with Beyond Earth. I think it make no sense to be able to power my space station with windmills in space

**Comment by BluSunrize** [comment]
Yknow, this is a pretty solid idea.

I'm undecided on config vs datapack, but I almost prefer datapacks?
I'll mull it over!

**Comment by BluSunrize** [comment]
Implemented, will be in the next release.
As an example implementation, I have increased windmill speed by 15% in ocean biomes =)
