### ISSUE TITLE
Client crash after joining server (ATM 7)

### ISSUE THREAD

**Issue by iperuranio** [BluSunrize/ImmersiveEngineering#5323]
Paste: https://pastebin.com/NYPygVQL
Forge version: 40.1.31

It crashed after I joined for the first time an ATM 7 (1.18.2) server.
I am the only one facing this issue. I tried logging with default minecraft settings.

Thank you.

**Comment by mindforger** [comment]
that is optifine, try updating it and keep render regions off ... If i remember right

**Comment by malte0811** [comment]
^That.
