### ISSUE TITLE
[1.18.2] Null pointer while shift left click on blue print in me

### ISSUE THREAD

**Issue by efinder2** [BluSunrize/ImmersiveEngineering#5324]
### Description of the issue:
In a minimal ME system (Crafting Terminal + cable + Drive with 1k storage cell) press shift on a single engineers blue print to get the full stack (in this case there is only one item). This happend in local lan game. this evening ill test it in complete single player

### Crashlog:
https://pastebin.com/j97aw2Ch

### Versions & Modlist
This issue occured in All the Mods 7 v0.4.5:
- IE 1.18.2-8.0.1-147
- Forge 40.1.25
- AE 2 - 11.0.0

**Comment by malte0811** [comment]
Fixed in d70961fc16cd94cc7b89fc2b667f7f50b14c9014, alongside a similar issue with core samples.
