### ISSUE TITLE
 [1.18.2] Angle Grinder Sawblade 

### ISSUE THREAD

**Issue by voidsong-dragonfly** [BluSunrize/ImmersiveEngineering#5325]
### Description of the issue:
The saw currently has two blades, and that leaves another "slot" in the blade quiver.
I suggest an _angle-grinder_ blade that functions as a tier-up of the hammer break function.
It uses biodiesel (saw, of course) and functions in this capacity to give the player a way to not break a minor tool constantly, and does it maybe a little faster than the hammer.
  
You had discussed it slightly in the Discord [here](https://discord.com/channels/270295681829306369/539145317547900938/982764080987246593) but without a use, so I propose 'letting the saw break hammer blocks quickly, possibly moreso than the drill' as a good use. Drill is good for non-precision work, saw is good for precision work.

### Versions & Modlist
Forge: 40.0.49
  [✔️] balm-3.0.2+0
  [✔️] cloth-config-6.2.57-forge
  [✔️] engineersdecor-1.18.2-1.1.22-b2
  [✔️] entityculling-forge-mc1.18-1.5.0
  [✔️] FastLeafDecay-28
  [✔️] feature_nbt_deadlock_be_gone_forge-2.0.0+1.18.2
  [✔️] ferritecore-4.2.0-forge
  [✔️] ImmersiveEngineering-1.18.2-8.0.1-147
  [✔️] inventoryessentials-forge-1.18-4.0.1
  [✔️] jei-1.18.2-9.7.0.180
  [✔️] JER-Integration-3.2.1
  [✔️] JustEnoughProfessions-1.18.2-1.2.2
  [✔️] JustEnoughResources-1.18.2-0.14.1.160
  [✔️] Placebo-1.18.2-6.2.1
  [✔️] spark-1.8.14-forge

**Comment by BluSunrize** [comment]
This is a "Plastic Update" feature, because anglegrinder blades are made from abbrasive in resin.

**Comment by BluSunrize** [comment]
Implemented!
