### ISSUE TITLE
Hard for addon devs to add custom upgradeable tools

### ISSUE THREAD

**Issue by frederick-the-nameless** [BluSunrize/ImmersiveEngineering#533]
This is due to the fact that upgradetype is an enum, which can't be expanded or added to. Also, the workbench can only accept things that extend ItemUpgradeableTool, which is really annoying when you have to extend something else, but still want your item to be upgradeable.

These could be fixed pretty easily, just don't use an enum for upgradetype, and replace it with a list, or a string identifier in every IUpgrade, and then add an IUpgradeableTool interface and allow things that implement that to be placed in the workbench.

**Comment by BluSunrize** [comment]
Not a bad idea, truth be told. I'll look into it.
