### ISSUE TITLE
[1.12.2] Crash as soon as loading into world

### ISSUE THREAD

**Issue by powderedd** [BluSunrize/ImmersiveEngineering#5331]
Errorlog: https://pastebin.com/JapxscwS

Modlist: https://pastebin.com/pimx1TMf

I don't even know if the root cause is immersive enginnering, but the world loads without it, but without immersive engineering the ids are jumbled up making the world not work

Sorry if i didnt format properly, this is my first error

**Comment by powderedd** [comment]
extra info:
im on windows 10, and im playing singleplayer

**Comment by malte0811** [comment]
1. 1.12 is no longer supported (and hasn't been for 2 years or so).
2. Do not cut up the crashlog, always post the full log. In this case you've removed enough that even if 1.12 was still supported, we wouldn't have had enough information to fix it.

**Comment by powderedd** [comment]
oh ):
