### ISSUE TITLE
[1.16.5] Engineers Workbench Duplication Glitch

### ISSUE THREAD

**Issue by queeratkent** [BluSunrize/ImmersiveEngineering#5335]
Very minor issue, but when using a mod like Quark that allows moving of Tile Entities with Pistons, the Workbench will be broken and drop two of the item instead of the singular one expected. Testing and duplication can be done by loading IE and Quark together and attempting to push the workbench with a piston. 
I experimented with this on Singleplayer where the issue persisted after being discovered on a dedicated server, and it also happens with other two-block tile entity objects like the Circuit Table. 

Forge Version is 36.2.23, IE is 1.16.5-5.0.7-143, running as a part of the Vault Hunters Modpack, a specific version of which I am unsure but I do believe it's being caused specifically by Quark & IE together and not another mod, as nothing else offers Tile Entity movement. 

I saw a similar bug report but it was from a year ago, for an older version of the game, and lacked any information to fit the contribution guidelines. This is an extremely minor issue but I just wanted to ensure it was known!

**Comment by BluSunrize** [comment]
Sorry, support for 1.16.5 has ceased, it wil receive no more updates
