### ISSUE TITLE
Feature Request: Fuses and CT Redstone.

### ISSUE THREAD

**Issue by tgibbscase501x** [BluSunrize/ImmersiveEngineering#5338]
-Drop out fuses with varying sizes for hv/mv to stop the wires from burning up (Overload), also could be used to control how much power a customer (multiplayer) can have maximum and for easy isolation of hv without red stone and normal fuses for low voltage.

-Redstone output from current transformers proportional to current flowing through them.

**Comment by malte0811** [comment]
> Redstone output from current transformers proportional to current flowing through them

This is already possible by attaching a comparator to the CT. It should probably be documented in the manual though.

> Drop out fuses with varying sizes for hv/mv to stop the wires from burning up

I think this would require a much more detailed model of wire overload to make it useful in practice without making the mechanic obsolete. Currently you could either make fuses always save wires, then you just put in a fuse rated for `[wire capacity] - 1` and don't have to worry about burning ever again without seriously derating the wire. Or you could make fuses burn independently of wires, but then you're not protected against very short overloads (which I think are the main issue in practice). With some rough model of wire temperature (I²R with some heat decay factor) it might be possible to design something that solves these issues, but it would make it much harder to communicate the conditions for wire burning to the player.

**Comment by tgibbscase501x** [comment]
The CT Redstone output is very slow and thus is not useful for making circuit breakers with Redstone breakers and a computer.

**Comment by BluSunrize** [comment]
The redstone output is slow because it's not designed to give you protection against overloading your wires. Also constant block updates (specifically redstone) are bad for performance.

Having "fuses" in IE just shifts the issue from burning wires to burning fuses. It just changes what you have to replace. And you'll end up burning fuses the same as wires if your setup is such that it puts too much power in too small of a wire.

Both suggestions have little use in IE.

**Comment by tgibbscase501x** [comment]
Id rather be replacing fuses than long spans of wire when you make a mistake. Maybe you should stop being so rude and listen to user suggestions "Both suggestions have little use in IE." I wouldn't have put a request in if I from experience playing the modpack and running it on my server didn't think it would have a use.
