### ISSUE TITLE
[Bug] Duplication of Hammers

### ISSUE THREAD

**Issue by TheonlyTazz** [BluSunrize/ImmersiveEngineering#5341]
### Description of the issue:
2 Immersive Engineerers Hammers can be duped into nearly infinite hammer when combining them in a crafting table.
The 2 original Hammers use up durability and create a new one.
This has been Tested on an Instance with just IE

### Versions & Modlist
IE Version: ImmersiveEngineering-1.18.2-8.0.2-149.jar
Forge: 40.1.52
![image](https://user-images.githubusercontent.com/3908847/175513916-81535ff0-a39c-46f0-beb5-58f21fdb3cfa.png)

![image](https://user-images.githubusercontent.com/3908847/175514007-640ac544-a6ef-4c82-aa15-0b84746a646a.png)

**Additional Information**

This has been reported to the FTB Modpack Issue tracker:
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1004

**Comment by malte0811** [comment]
@BluSunrize do you remember where `isRepairable` came from in 990c06e2ab3ba6600882e85e72be59b79f6260c9? From a quick search that's only used by the vanilla repair recipe (which is what causes this issue) and the grindstone, while your commit was about the anvil. We have our own impl of repair recipes that doesn't have this issue, but with that method implemented on the hammer the vanilla reicpe also matches and it's essentially random (hash map iteration order, I think) which one is used.

**Comment by BluSunrize** [comment]
Probably just an oversight on my part, feel free to toss it
