### ISSUE TITLE
Game crash during common_setup

### ISSUE THREAD

**Issue by ImNot64GG** [BluSunrize/ImmersiveEngineering#5345]
### Minecraft Version

1.18

### Immersive Engineering Version

ImmersiveEngineering-1.18.2-8.0.1-147

### How did it happen?

Started the game and it gave me a error
Im using a modpack (Valhelsia Volatile 1.18)

error code: Immersive Engineering (immersiveengineering) encountered an error during the common_setup event phase
		java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5

### Crash Log

https://pastebin.com/zsGf0pff

**Comment by malte0811** [comment]
Update IE, this is fixed in build 149.
