### ISSUE TITLE
[1.19] Garden cloche does not update properly

### ISSUE THREAD

**Issue by Zahkriiven** [BluSunrize/ImmersiveEngineering#5346]
### Minecraft Version

1.19

### Immersive Engineering Version

8.0.2-149.49

### Expected Behavior

The garthen cloche visually updates when its contents are changed.

### Actual Behavior

The garthen cloche does not visually display its contents until it is updated, for example, by rotating it. It does not update at all when it is empty.

### Steps to reproduce

![GIF 24-04-2022 20-08-24](https://user-images.githubusercontent.com/25531677/176914758-745c8514-fe83-4ed4-994f-493c8c0b1ee8.gif)

### Debug Crash Log

https://pastebin.com/i0iUGzxy

**Comment by Zahkriiven** [comment]
Revisited this in 1.19.3 test server 9.2.0-16.0.59 , fixed for the plant, not for the soil

**Comment by voidsong-dragonfly** [comment]
The soil issue seems to be in the callback improperly caching/not updating the soil texture until external actors force a rerender somehow, but I'm also not the best at looking at this system so I'd like help here if people can.

Adding on to this, any time either the cloche render in the chunk is reset (cloche is rotated) OR a block is placed to force a chunk rebuild, the cloche updates the soil.
