### ISSUE TITLE
[Suggestion] Right-click in inventory to add items to Engineer's Toolbox

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#5347]
### Explain your idea

This is a QoL suggestion: the mod "Sophisticated Backpacks" allows a player to pick up an inventory item, and then right-click over a backpack in the inventory to add the item to the backpack. I've gotten really used to this functionality, and it would be wonderful if one could do the same with the Engineer's Toolbox.

I realize this might be a little difficult given that the toolbox has a few "categories" of items versus the general inventory of a backpack, but I think some simple logic could be used to determine the best place to try and put an item.

**Comment by BluSunrize** [comment]
Cool idea, I'll look into this!
