### ISSUE TITLE
Sugestion: Fireworks as Railgun Ammo

### ISSUE THREAD

**Issue by Caldoric** [BluSunrize/ImmersiveEngineering#5350]
Pretty much exactly what it says in the title: I think it'd be cool to be able to have fireworks available as a kind of railgun ammo, just like how crossbows work, but with greater range as afforded by the speed that railguns can impart on their projectiles. Perhaps we could even have specialized metallic firework rockets designed specifically for use with the railgun, if the normal ones aren't cool enough, or add the option to add firework rockets/stars to existing rod-type ammo. Pretty much anything that'd let us fling low-grade explosives at a target with extreme prejudice (because asking for TNT is obviously stupid, and is never going to happen!)

**Comment by BluSunrize** [comment]
We already have firework bullets in the revolver, I don't see a point in adding them to the railgun too.

**Comment by Caldoric** [comment]
I wasn't aware that was even a thing... Haven't played with IE in a while.

**Comment by Caldoric** [comment]
Uh, not seeing anything about these supposed firework bullets on the wiki, and no-one shows them on YouTube. Which version are these in, and do they function like fireworks do on a crossbow when fired from the revolver? Or do they just operate as flares?

**Comment by BluSunrize** [comment]
Firework cartridges were added in Version 0.14-95, which you can quite easily read up on in our Changelog.
IE *has* no wiki, you are likely relying on some FTB third-party wiki page which is going to be grossly out of date and not written by any of us developers.

If you look up "Firework Cartridge" in JEI, you'll easily find them, being crafted from 1 firework and 1 emty shell.
As for how they behave: Try it ;)
