### ISSUE TITLE
Wires NOT showing up when placed down between Lantern etc

### ISSUE THREAD

**Issue by f0kx** [BluSunrize/ImmersiveEngineering#5351]
### Minecraft Version

1.18

### Immersive Engineering Version

8.0.2-149

### Expected Behavior

When i place a wire it whould be visible!

### Actual Behavior

Its invisible

https://imgur.com/a/i4uLm9P

Picture is showing a cable of create craft& additions and in the back there should be a immersive cable but there isnt one its connected but invisible!

### Steps to reproduce

1. Place a LV Accu
2. Place a LV  Wire Relay and a Post with a lantern
3. Connect all together

### Debug Crash Log

https://pastebin.com/JthU1EJs

**Comment by f0kx** [comment]
i dont use Optifine btw

**Comment by malte0811** [comment]
This is a known issue with Rubidium. See https://github.com/BluSunrize/ImmersiveEngineering/issues/5300#issuecomment-1139724675 for a workaround.
