### ISSUE TITLE
Wires not transferring power

### ISSUE THREAD

**Issue by LittleMC** [BluSunrize/ImmersiveEngineering#5357]
### Minecraft Version

1.18

### Immersive Engineering Version

1.18.2-8.0.2-149

### Expected Behavior

Hi! I want to transfer power but its not transferring what i do?

### Actual Behavior

![2022-07-13_09 41 09](https://user-images.githubusercontent.com/109086895/178678773-9b8160e1-6a53-4317-ac67-96ae1fab43a0.png)

### Steps to reproduce

1. I placed generators and connected them to a accumulator
2. The top of the accumulator i placed a mv connector
3. The mv connector has power
4. Wires not transferring

### Debug Crash Log

https://pastebin.com/iX13EDgJ

**Comment by mindforger** [comment]
just correct me if i am wrong but they look like MV relays not connectors, also there is no consumer, how did you check they don't transfer any power?

**Comment by BluSunrize** [comment]
There is nowhere for the power to go.
Power doesn't flow unless it has something to do on the other end.

**Comment by LittleMC** [comment]
thanks
it works now

**Comment by LittleMC** [comment]
hi
not working

**Comment by LittleMC** [comment]
accumulator stucks on 6,9 kFE

**Comment by BluSunrize** [comment]
Please provide pictures of your issue.

**Comment by LittleMC** [comment]
ok

**Comment by LittleMC** [comment]
how can i close

**Comment by LittleMC** [comment]
its working
