### ISSUE TITLE
Floodlight does not get signal from redstone wire connector while under scaffolding

### ISSUE THREAD

**Issue by Tchastik** [BluSunrize/ImmersiveEngineering#5361]
### Minecraft Version

1.18

### Immersive Engineering Version

1.18.2-8.0.2-149

### Expected Behavior

Floodlight should accept signal from redstone wire connector and turn on.

### Actual Behavior

While being placed under steel/aluminum/treated wood scaffolding the floodlight fails to turn on upon the signal from redstone wire. Under any other block the floodlights work as expected.

### Steps to reproduce

1. Place a steel/aluminum/treated wood scaffolding.
2. Place a floodlight under the scaffolding.
3. Connect power input to the floodlight.
4. Put one redstone wire connector on the scaffolding that holds the floodlight, and another one a few blocks away with a lever near it. Link both connectors using redstone wire coil.
5. Set the first connector to "Output" mode and another connector to "Input" mode with a screwdriver. Both connectors are the same channel/color.
6. Pull the lever at the Input connector
![2022-07-17_18 17 45](https://user-images.githubusercontent.com/41586511/179405426-810ed402-326b-467c-8918-7cde1c0dd665.png)
.

### Debug Crash Log

The game doesn't crash

**Comment by BluSunrize** [comment]
This is not a bug, this is vanilla redstone mechanics.

Only solid blocks conduct signals. You'd see the same result if you used glass.
