### ISSUE TITLE
[1.19] Placing a tool in the workbench or trying to sleep while holding the tool crashes

### ISSUE THREAD

**Issue by Zahkriiven** [BluSunrize/ImmersiveEngineering#5363]
### Minecraft Version

1.19

### Immersive Engineering Version

8.1.0-pre.65

### How did it happen?

Placing a tool in the workbench
Sleeping while holding the tool
(tested drill, metal shield)

### Crash Log

https://pastebin.com/KGDixVRa

**Comment by malte0811** [comment]
Fixed in 6740967cc28981594851e10e755cc97dab99d14b
