### ISSUE TITLE
[1.18.2] Missing Wire Mold recipes

### ISSUE THREAD

**Issue by TwistedGate** [BluSunrize/ImmersiveEngineering#5365]
### Minecraft Version

1.18

### Immersive Engineering Version

1.18.2-8.0.0-146

### Expected Behavior

I expect to be able to insert the Wire Mold into the press and also be able to make wires that way.

### Actual Behavior

Only plates, casul, unpacking and rod molds have *some* recipes, the rest is completely missing.
Wire Mold can't even be inserted into the Metal Press.

As can be seen here: https://www.youtube.com/watch?v=IoPBkAJmjYM

### Steps to reproduce

- Build Metal Press
- Grab `Wire Mold`
- Try inserting into Metal Press
- Nothing happens.

### Debug Crash Log

https://gist.github.com/TwistedGate/44da43f2b58cb319926cfcabb31fb7ed

**Comment by TwistedGate** [comment]
The files for the wire mold recipes *are* there.. just not being loaded for some reason.

![grafik](https://user-images.githubusercontent.com/31029668/180064899-b6126dca-5562-453c-b8ec-2b3b63f92d2f.png)
(JSON has been formatted using a npp plugin)

**Comment by TwistedGate** [comment]
Having switched forge version `40.1.68` i can say: No, that did not do it.

And results in ![this](https://cdn.discordapp.com/attachments/270295745230405643/999396360560320622/unknown.png) either way

**Comment by TwistedGate** [comment]
Having updated IE to `1.18.2-8.0.2-149` and Forge to `40.1.68` resulted in a completely different, but related problem.
I cannot load my world anymore at all..

I've put the whole Log file **+** the debug crash in [THIS](https://gist.github.com/TwistedGate/f6d5343c738a69e219559d8cdb676ed8) gist.
Inside the log file scroll to near the bottom.

**Comment by malte0811** [comment]
> Having updated IE to 1.18.2-8.0.2-149 and Forge to 40.1.68 resulted in a completely different, but related problem.

Did you delete the old IE build from `mods/`? The Forge code to handle multiple versions of the same mod has been broken for a while now. That crash does not make any amount of sense on IE 149.

**Comment by TwistedGate** [comment]
It's the F3 Crash... the primary thing (in the log file) is above that https://gist.github.com/TwistedGate/f6d5343c738a69e219559d8cdb676ed8#file-latest-log-L404
I just added the F3 Crash to show that im actualy using `1.18.2-8.0.2-149`
