### ISSUE TITLE
[1.19] Sprinting over a feedthrough block crashes the game

### ISSUE THREAD

**Issue by RRyyas** [BluSunrize/ImmersiveEngineering#5372]
### Minecraft Version

1.19

### Immersive Engineering Version

1.19-8.1.0-pre.67

### How did it happen?

When you sprint over a feedthrough block, the game instantly crashes. Reproduced the bug without resource packs also.

### Crash Log

https://pastebin.com/M9RwepRh

**Comment by malte0811** [comment]
Fixed by 54574134a99a914afdb3207218c8ddb561dcee34
