### ISSUE TITLE
[1.19] Assembler fluid meter overflows the GUI

### ISSUE THREAD

**Issue by Zahkriiven** [BluSunrize/ImmersiveEngineering#5373]
### Minecraft Version

1.19

### Immersive Engineering Version

8.1.0-pre.68

### Expected Behavior

Assembler's fluid meter matches the GUI.

### Actual Behavior

![Screenshot](https://cdn.discordapp.com/attachments/826497495491280957/1000434621051318302/unknown.png)

### Steps to reproduce

1. Build an assembler
2. Fill it with water

### Debug Crash Log

https://pastebin.com/FMU4UVfM

Edit by @malte0811: Fix image link

**Comment by malte0811** [comment]
Fixed by f4eadca080698f2058903f391a2e313fc429357d
