### ISSUE TITLE
[1.19] Steel fences invisible in Crusher manual entry

### ISSUE THREAD

**Issue by RRyyas** [BluSunrize/ImmersiveEngineering#5378]
### Minecraft Version

1.19

### Immersive Engineering Version

1.19-8.1.0-pre.68

### Expected Behavior

Steel fences should be visible in the crusher block preview in the manual

### Actual Behavior

Steel fences are completely invisible in the crusher block preview in the manual https://prnt.sc/ZYTgJbJJVOfM

### Steps to reproduce

1. Create a new world
2. Open the IE manual
3. Go to the Crusher manual entry
4. View the second layer for the Crusher

### Debug Crash Log

https://gist.github.com/RRyyas/cd4597e903f9d5ad748b67f6f6fd3a56/ede6732a2dab74a37ab99cd9327127f1a0dd867a

**Comment by RRyyas** [comment]
Pastebin is deleting my log (Not Found (#404)), so i have to upload it as a txt file on Dropbox https://www.dropbox.com/s/t6nh7gok9kczybi/2022-07-25-1.log?dl=0

**Comment by BluSunrize** [comment]
This is why we suggest gist =P

**Comment by RRyyas** [comment]
I changed the link to a gist one. Instead of uploading a debug crash report i decided to upload the log file for the session, because it contains a few critical lines at line 894. I only had two mods installed, JEI and Immersive Engineering.

**Comment by malte0811** [comment]
1bf19987f02f31b5b71868ba1cc6f4512b0ed984

Note that this only fixes the rendering; the weird OpenGL error stays for now. I'll need to look into that, but it doesn't seem to have any effect for now
