### ISSUE TITLE
[1.19] Blast furnace's item model not being transformed properly

### ISSUE THREAD

**Issue by Zahkriiven** [BluSunrize/ImmersiveEngineering#5380]
### Minecraft Version

1.19

### Immersive Engineering Version

8.1.0-pre.68

### Expected Behavior

Blast furnace shows correctly in advancements and JEI.

### Actual Behavior

![image](https://user-images.githubusercontent.com/25531677/181104767-ca3737a0-024e-44f7-bc87-8363b15d7252.png)

### Steps to reproduce

1. Open IE advancements

### Debug Crash Log

https://pastebin.com/NpfFNSbx

**Comment by malte0811** [comment]
9e5f902e589ed990841a2cf08876c43d44ae7ce1
