### ISSUE TITLE
[Suggestion] Configurable projectile speed/accuracy

### ISSUE THREAD

**Issue by MrHazMat** [BluSunrize/ImmersiveEngineering#5381]
### Explain your idea

Right now, both revolver and railgun fires projectile at the speed of a flying arrow. Some projectile (ie wolfpack cartridge, saw) do makes sense in having slow flight speed but others are just too slow.

I understand the issue with making projectile faster is it being rendered incorrectly.

So, I wondered if it is possible to have the projectile be invisible or instantaneous/hit-scan?

I also like if the spread of shells be more narrowed and railgun projectile more accurate.

 Maybe have them configurable?

**Comment by BluSunrize** [comment]
I don't want hitscan projectiles, easy as that.

Accuracy of the railgun is already 100%, it goes where you aim it. There is no deviation, except for the fact that gravity will pull it down over distance.

**Comment by MrHazMat** [comment]
That's weird, I've tested the railgun a few times and it still deviates left and right, like firing an arrow

**Comment by MrHazMat** [comment]
Tested it a couple dozen times, and it seems to deviate in all 4 direction, up down left and right. I thought it might be just a graphical glitch but testing on target block also give different redstone charge.
