### ISSUE TITLE
[1.18+] Redstone acid recipe in Assembler produces buckets from just redstone and water

### ISSUE THREAD

**Issue by RRyyas** [BluSunrize/ImmersiveEngineering#5382]
### Minecraft Version

1.19

### Immersive Engineering Version

1.19-8.1.0-pre.68

### Expected Behavior

Assembler should not produce buckets of redstone acid from just redstone and water, or should not produce empty buckets if running recursive mode with accumulator recipe

### Actual Behavior

Assembler makes buckets of redstone acid with no iron input, therefore it makes buckets seemingly out of thin air

### Steps to reproduce

1. Create an assembler multiblock
2. Create an infinite water source with a pump and a small water pond
3. Create a power source for the assembler and the pump
4. Pump the water to the assembler
5. Add the redstone acid recipe to the assembler
6. Add redstone
7. Watch it produce (buckets) of redstone acid

### Debug Crash Log

https://gist.github.com/RRyyas/ce0851b4b73b2f8871a0641ee7132fa0

**Comment by BluSunrize** [comment]
Issue exists in 1.18 as well
