### ISSUE TITLE
[Suggestion] Add oil configuration to mod config

### ISSUE THREAD

**Issue by MiniRaptor** [BluSunrize/ImmersiveEngineering#5386]
### Explain your idea

My idea is very simple and useful for some kind of people. 

Explaining: When i used immersive engineering pump on oil source from galactic craft, pump worked and pumped out oil. But I was confused that the oil from the source ends, literally the oil turns into a cobblestone, and eventually disappears. Therefore, my request is to add an option to the mod config that will be responsible for pumping out oil, and will make it inexhaustible. I know that there is already an option that makes water sources infinite, but this option does not work on oil. 

I also believe that it is not galactic craft that is to blame for the disappearance of oil. Because I play with several tech mods, and maybe one of them makes oil disappear when it is pumped out. Tech mods which with i play: GregTech, HBM Nuclear Tech, Galactic Craft. 

I hope my request will not complicate the developer, and will not cause problems. Otherwise, I want to say thanks for the awesome mod that you created.

P.S: I played on 1.12.2.

**Comment by BluSunrize** [comment]
1) 1.12 is not getting any more updates
2) If Galacticraft oil is supposed to be infinite, then it should be regenerating as it flows back into itself, much like vanilla water. If that is the case, you can sneak+rightclick the pump with a hammer to disable the cobblestone filling. That should then allow the oil to flow back and regenerate.

We are not adding a config option to make some random fluid infinite when that fluid isn't even part of our mod.

**Comment by MiniRaptor** [comment]
Ok, thank for response.
