### ISSUE TITLE
[1.19] Heavy plated shield is rotated 90º when blocking with the offhand.

### ISSUE THREAD

**Issue by Zahkriiven** [BluSunrize/ImmersiveEngineering#5387]
### Minecraft Version

1.19

### Immersive Engineering Version

1.19-8.1.0-pre.68

### Expected Behavior

The shield should be correctly positioned when blocking.

### Actual Behavior

![image](https://user-images.githubusercontent.com/25531677/181925752-a993b3b9-fd7b-46bb-89b5-6edadfd911ce.png)

### Steps to reproduce

1. Place shield in the offhand
2. Block with it

### Debug Crash Log

https://pastebin.com/rQ10MFvc

**Comment by FDMan12** [comment]
Same issue in 1.19.2, mod version is 1.19.2-9.1.2-159.

**Comment by malte0811** [comment]
63404a0fcc51aa1b350aa51f5ffe184fd0d38999
