### ISSUE TITLE
[1.18.2] IE Buzzsaw Treecapitaties DynamicTrees Trees

### ISSUE THREAD

**Issue by voidsong-dragonfly** [BluSunrize/ImmersiveEngineering#5388]
### Minecraft Version

1.18

### Immersive Engineering Version

8.1.0-150

### Expected Behavior

IE's Buzzsaw should not treecapitate DynamicTrees trees, as it leads to random parts of non-connected trees being broken when the base of one tree is cut - DynamicTrees trees already take the entire tree down on their own, without the need for the buzzsaw to break them. The Buzzsaw should work just like an axe.

### Actual Behavior

IE's Buzzsaw breaks multiple parts of other trees and not just the single tree that was broken, sometimes causing issues with the other trees when things are broken in strange orders.

### Steps to reproduce

Break a DynamicTrees tree with the Buzzsaw.

### Debug Crash Log

https://gist.github.com/Silfryi/dadfa7912e6b0f5b7c00f2c835919ec0

**Comment by BluSunrize** [comment]
How would I know if the tree is a dynamic tree?! =P

**Comment by voidsong-dragonfly** [comment]
They're trees from the DynamicTrees mod, they've special blocks and trunks, it should be glaringly obvious as they use no vanilla blocks.

Below is what happens when the Buzzsaw overgenerously breaks DT trees - parts of other trees are removed:
![dt_break_1](https://user-images.githubusercontent.com/40431605/182022315-a579039c-ccac-4dd8-8500-501c2de7840c.png)
![dt_break_2](https://user-images.githubusercontent.com/40431605/182022319-87cfc9b2-714a-49af-b893-c9acd3145c13.png)

We talked about it on Discord, but basically traversing here makes the Buzzsaw over-vigorously cut. DynamicTrees blocks can be found quite simply via tag with `#dynamictrees:branches` and `#dynamictrees:leaves`, as you asked about in the Discord
