### ISSUE TITLE
IE's tooltips render behind NEI items

### ISSUE THREAD

**Issue by cobra** [BluSunrize/ImmersiveEngineering#539]
All custom tooltips rendered by `blusunrize.immersiveengineering.client.ClientUtils#drawHoveringText` are displayed behind NEI's item panel.

Examples:
Workbench with ghost item
![](https://cloud.githubusercontent.com/assets/163331/10798694/34ffcaca-7da9-11e5-8c35-db99248d6042.png)
Workbench with real item
![](https://cloud.githubusercontent.com/assets/163331/10798711/427bfcbe-7da9-11e5-8820-2a548e95544d.png)
Arc Furnace RF bar
![](https://cloud.githubusercontent.com/assets/163331/10798739/5da590a4-7da9-11e5-96a8-61fb67e8bbdf.png)

I already tried without success:
- changing the z level in GuiModWorkbench#drawGuiContainerForegroundLayer before calling `drawHoveringText` by `this.zLevel = 300.0F; itemRender.zLevel = 300.0F;` and resetting afterwards
- changing the z level in `drawHoveringText` itself by `GL11.glTranslated(0, 0, 300);` before drawing and resetting afterwards
- using ChickenBones' `GuiDraw.drawMultilineTip` instead

what the…

**Comment by BluSunrize** [comment]
I know, I have no idea why, I've tried a lot of things and I don't care to fix it. xD

**Comment by XFactHD** [comment]
Almost every tooltip from any mod has this problem. The only exception are the tooltips you get when hovering over existing (non-ghost) items.
