### ISSUE TITLE
[Suggestion] Allow Tightening of Steel/Hemp rope

### ISSUE THREAD

**Issue by Holli-Git** [BluSunrize/ImmersiveEngineering#5390]
### Explain your idea

Pretty much what it says. Allow rope/cable to be tightened or loosened by right clicking the connector with a screwdriver or similar. Rope/cable in engineering tends to be under stress, as the tension gives the strength. Having structures in IE be able to look supported would go a long way with people who like to make things look nice. Loosening would also be nice, allowing for some more creativity. Would also open up some more possibilities to the very niche niche of cable rollercoasters. 

Apologies if this has been suggested before, I did a quick look on the discord and github and didn't find anything.

**Comment by BluSunrize** [comment]
Just like the past 3 times it's been suggested, not planning to add that, because it's more data to track and would need work on the wire render code.

**Comment by Holli-Git** [comment]
> Just like the past 3 times it's been suggested, not planning to add that, because it's more data to track and would need work on the wire render code.

Alright, understood! Sorry I missed the earlier times its been suggested
