### ISSUE TITLE
Crash with the fluid tank.

### ISSUE THREAD

**Issue by wardmatt1** [BluSunrize/ImmersiveEngineering#5391]
### Minecraft Version

1.18

### Immersive Engineering Version

ImmersiveEngineering-1.18.2-8.1.0-150

### How did it happen?

Crash to desktop when trying to fill a bucket from the fluid tank.

### Crash Log

https://pastebin.com/BdfgdXUa

**Comment by BluSunrize** [comment]
Report this to the Wildfire mod please, the crash is caused by their event handler:

https://github.com/WildfireRomeo/WildfireFemaleGenderMod
