### ISSUE TITLE
Decorative Shaders Not Working On Certain Items in 1.18.2 Modpack

### ISSUE THREAD

**Issue by NotDracon** [BluSunrize/ImmersiveEngineering#5392]
### Minecraft Version

1.18

### Immersive Engineering Version

1.18.2-8.0.2-149

### Expected Behavior

I put the shader on a minecart, railgun or chemical thrower and it shows the shader on the item.

### Actual Behavior

Placing any shader on the railgun or chemthrower causes them to render with a "gray" texture. The minecart will display its vanilla texture regardless of shader applied to it. The balloon, banner, revolver, etc will all display the shader correctly, by the way. The issue is only with those three items.
![2022-08-03_11 20 39](https://user-images.githubusercontent.com/79013726/182649408-eae8d63a-10da-4c85-b832-ed9c123cc160.png)

### Steps to reproduce

1. Start a singleplayer world or connect to a server.
2. Spawn in or craft engineer's workbench, a minecart/chemthrower/railgun, and any shader.
3. Attempt to apply shader to the item.
4. Gaze upon its gray appearance.

### Debug Crash Log

https://gist.github.com/NotDracon/0f94aaefd135fd28bcdc8b16f41eb804

**Comment by NotDracon** [comment]
NOTE: I'm aware IE has no support for "shader" mods but I don't know if this modpack includes any shader mods in it.

**Comment by malte0811** [comment]
Please test without Rubidium and Rubidium Extras.

**Comment by NotDracon** [comment]
Yeah, those were the shader mods that were causing the issue. Thanks for pointing those out, wouldn't have found the cause otherwise.

**Comment by Shibva** [comment]
so it is rubidium

this is a bit odd as it dosent affect all thing; the revolver for example is working without issue

why is that the case?

**Comment by BluSunrize** [comment]
There's a reason shader mods are not supported.

Please don't necropost, thanks.
