### ISSUE TITLE
1.18.2 Windmill sails disappear when loading a world

### ISSUE THREAD

**Issue by PaulerLeOne** [BluSunrize/ImmersiveEngineering#5393]
### Minecraft Version

1.18

### Immersive Engineering Version

8.0.2-150

### Expected Behavior

The number of sails put in a windmill should remain after logging out of a world and re-entering.

### Actual Behavior

When exiting and loading a world, the number of sails a windmill has sometimes is changed, as far as I've seen, to lesser. 
This only happens to certain windmills, and the number of sails that is reduced to after the reload, is always the same to that windmill.

### Steps to reproduce

This only happened to certain seamingly random windmills.  I would place a series of windmills in different places and orientations, put then a certain number of sails, press Save and Quit to Title in the pause menu, join the world and some of the windmills will have missing sails if not all of them.

### Debug Crash Log

https://paste.gg/p/anonymous/dc75010cf22449c2bd3c4b3db577f687

**Comment by BluSunrize** [comment]
Are the sails only visually missing or does this also come with a reduced power output?

If you try to place more sails on the mill again, does it let you do so?

**Comment by PaulerLeOne** [comment]
It's not visual, it will let me place them again.

**Comment by baranelitez** [comment]
I can confirm this. Sails disappear on world reload
