### ISSUE TITLE
Server crashing after adding immersive engineering

### ISSUE THREAD

**Issue by zygerr** [BluSunrize/ImmersiveEngineering#5395]
### Minecraft Version

1.18

### Immersive Engineering Version

ImmersiveEngineering-1.18.2-8.0.2-150

### How did it happen?

Basically, i have been playing the Skyopolis 5 pack, adding mods and decided to add IE.
Once i added the server started crashing, not even starting.

### Crash Log

https://pastebin.com/iZzhPHAY

**Comment by BluSunrize** [comment]
Conflict with Cooking For Blockheads. You'll have to pick if you want to use that mod or IE.
