### ISSUE TITLE
Spootlight for Spanish people?

### ISSUE THREAD

**Issue by apos76** [BluSunrize/ImmersiveEngineering#54]
I beg leave to make a little spootlight for spanish people on my yt channel?

**Comment by DoughnutDev** [comment]
You will not be able to make spotlights tell the mod is released blu has
asked for people to not stream or record any version tell it is released to
the public.

**Comment by BluSunrize** [comment]
What Donut said. Thanks

**Comment by apos76** [comment]
ok thanks, I'll be waiting. Congratulations, the mod is very, very, very, very, nice
