### ISSUE TITLE
Invisible Assembler inventory

### ISSUE THREAD

**Issue by cobra** [BluSunrize/ImmersiveEngineering#540]
The internal 18-slot inventory doesn't display any items in the GUI. Clicking on a slot will pull out an itemstack, but it will disappear again after putting it back.

**Comment by BluSunrize** [comment]
Fixed by https://github.com/BluSunrize/ImmersiveEngineering/commit/aaf922f6c716a4c434ecf9e4e8d04f6986162b1a
