### ISSUE TITLE
[1.19] Railgun scope extreme zoom level

### ISSUE THREAD

**Issue by RRyyas** [BluSunrize/ImmersiveEngineering#5406]
### Minecraft Version

1.19

### Immersive Engineering Version

1.19-8.1.0-pre.68

### Expected Behavior

Scope for the railgun should be zooming the correct level shown (1.6x for lowest level)

### Actual Behavior

Scope zooms in alot further, probably 50-100x (Screenshots provided)

### Steps to reproduce

1. Create a new world with creative mode
2. Spawn a railgun and the Precision Scope
3. Put on the scope attachment using the engineer's workbench
4. Use the scope with the middle mouse button

### Debug Crash Log

https://imgur.com/a/kgcXIKB

**Comment by malte0811** [comment]
b1376c547d03c2558651339b5066518649e4557d
