### ISSUE TITLE
[1.18.2] Sawblade have silk touch effect on leaves when chopping a tree

### ISSUE THREAD

**Issue by Zahkriiven** [BluSunrize/ImmersiveEngineering#5412]
### Minecraft Version

1.18

### Immersive Engineering Version

8.2.0-151

### Expected Behavior

The sawblade should not have silk touch and break leaves.

### Actual Behavior

![GIF 16-08-2022 21-26-48](https://user-images.githubusercontent.com/25531677/184969079-9802b399-ae48-4265-8ab5-9f7e33504a71.gif)

### Steps to reproduce

1. Have a sawblade in a fueled buzzsaw.
2. Use the buzzsaw on a tree.
3. Leaves are dropped as block

### Debug Crash Log

https://pastebin.com/ZhXzDf3t

**Comment by malte0811** [comment]
The buzzsaw with the standard sawblade can perform `ToolActions.SHEARS_DIG` (among others), which is one of the triggers for dropping leaves instead of sapplings. @BluSunrize: What was the idea behind allowing it to perform that action?

**Comment by BluSunrize** [comment]
Not it wasn't, but I see why that happens!

I'll look into fixing it.
