### ISSUE TITLE
Golems dropping shaders.

### ISSUE THREAD

**Issue by Panikking** [BluSunrize/ImmersiveEngineering#5413]
### Minecraft Version

1.18

### Immersive Engineering Version

1.18.2-8.2.0-151

### Expected Behavior

Iron golems dropping poppies and iron

### Actual Behavior

iron golems dropping poppies, iron and epic shader grab-bags

I believe it's a bug because blu said so =p

### Steps to reproduce

1. Find or create an iron golem (this can be done by locating a village or placing 4 iron blocks in a T-shape and a pumpkin on top)
2. Murder it, any weapon works (tested with: tridents (thrown and swung), crossbows, revolvers, railguns (using iron rods), bows, netherite swords, and stone axes, my assumption is it works with any item)
3. use your eyes

### Debug Crash Log

https://pastebin.com/gRE4awGJ

**Comment by BluSunrize** [comment]
Yeah apparently Iron Golems have 100 health, which is my criteria for "boss enemy".
Whoops!

**Comment by mindforger** [comment]
just as an idea, an nbt based "regular expression" like when using vanilla commands as an config option to define the criteria, so mod- and modpack-makers can adapt the definition of bosses and allow usage of tags if they see fit

**Comment by BluSunrize** [comment]
We literally have tags for this @mindforger.
Base your suggestions on what's in the mod maybe ;)

**Comment by mindforger** [comment]
well i rarely have a look in the configs, i like playing my mods as they are designed to be played :P

**Comment by BluSunrize** [comment]
All you gotta do is read the changelog, where this was documented.
