### ISSUE TITLE
[Suggestion] config for railgun damage multiplier

### ISSUE THREAD

**Issue by Snakich** [BluSunrize/ImmersiveEngineering#5414]
### Explain your idea

A config option for damage multipliers.

This is mostly about railgun-projectiles, but other possibilities would be shock-damage from wires, revolver-damage, drill-damage, ect.

I find it very hard to believe a simple bow can deal more damage than a railgun shooting out a big metal rod at very high speeds. Hence my idea to make the damage changeable via config.

I saw the damage numbers being hardcoded inside the [RailgunProjectiles class](https://github.com/BluSunrize/ImmersiveEngineering/blob/e869c55e4a95a6f3cb2c137f67006ca8891cfd83/src/main/java/blusunrize/immersiveengineering/common/items/RailgunProjectiles.java#L40) and I'm too stoopid to do anything about it 😄 as I've never coded anything java- and minecraft-related.

**Comment by BluSunrize** [comment]
You could at least have actually checked the config.

It's called `damage_modifier` in the category `tools.railgun`, it's existed for 2 years.
