### ISSUE TITLE
Diesel generator has no sound

### ISSUE THREAD

**Issue by chdominguez** [BluSunrize/ImmersiveEngineering#5418]
### Minecraft Version

1.19

### Immersive Engineering Version

1.19.2-8.2.1-pre.81

### Expected Behavior

The Diesel generator plays a loud noise when producing energy.

### Actual Behavior

The Diesel generator is silent when producing energy.

### Steps to reproduce

1. Build a Diesel generator
2. Give it fuel
3. Produce energy without sound

### Debug Crash Log

https://paste.ee/p/KBDsT

**Comment by Trevil1337** [comment]
I have the same issue, with some additional stuff:
-> Running Diesel Generator fan does not move
-> Running Diesel Generator does not emit smoke
-> Diesel Generator runs **forever** on single bucket of Biodiesel

Minecraft version:
1.18.2

IE version:
1.18.2-8.2.0-151

Other mods running:
JEI

No performance enhancing stuff installed.

Maybe for extra clarification: Crusher does work, is both loud and has spinning bits.

**Comment by BluSunrize** [comment]
Fixed for upcoming releases
