### ISSUE TITLE
[Minetweaker Issue/Suggestion/Question]: Input Size Vs Output

### ISSUE THREAD

**Issue by Lanse505** [BluSunrize/ImmersiveEngineering#542]
Hello, Wasn't sure what to name this post so that's it.

The thing at hand:
I'm currently building a pretty big "overhaul" mod pack and We're looking at implementing custom recipes for our own ores into the Crusher. Our Ore system uses Chunks (which are gotten from mining an ore, essentially chipping away at it). 

In our processing progression the IE Crusher would be 3x efficient Ore processing system (1x being our own grindstone and 2x being Grindstone + Sifter).

So it'd look something like this;
1x: 9 Chunks = 1 Dust
2x: 8 Chunks = 1 Dust
3x: 7 Chunks = 1 Dust
4x: 6 Chunks = 1 Dust
5x: 5 Chunks = 1 Dust

The issue we've run into and I'm not sure how the Crusher works to begin with (internally) is that We're trying to add a recipe that'd require 7 Chunks that would output 1 Dust. 

I've run a test script to see if this would be possible with your minetweaker support;
mods.immersiveengineering.Crusher.addRecipe(<minecraft:iron_ingot>, <minecraft:melon_block> * 32, 8000, <minecraft:iron_ingot>, 0.0);

(Aka 32 Melon Blocks = 1 Iron Ingot (Stupid Recipe but It's just for testing purposes)

This Minetweaker Script does add a Recipe of 32 Melons > 1 Iron Ingot
Pic: http://puu.sh/l2eLh/96d795882b.png

However This also produces wierd invisible recipes for 31 Melons = 1 Ingot, 30 Melons = 1 Ingot. Etc.
Aka anything Below the Set amount = 1 ingot. Not sure if bug or not but I'm gonna post this here.

(Talked about it on IRC, Posting for Reminder).

**Comment by BluSunrize** [comment]
Will be fixed in the next commit

**Comment by Lanse505** [comment]
Okey Thanks man :)

**Comment by Lanse505** [comment]
Noticed the same issue pops up with the Arc Furnace and the Additive Array

You can specify 1 tin block + Array: 1 copper block + 1 copper block + 1 copper block
but not: 1 tin block + Array: 3 copper blocks

IE:
 mods.immersiveengineering.ArcFurnace.addRecipe(<Forestry:ingotBronze>, <ore:ingotTin>, <ThermalExpansion:material:514>, 200,  100, [<ore:ingotCopper>, <ore:ingotCopper>, <ore:ingotCopper>]); 

Works but not:

mods.immersiveengineering.ArcFurnace.addRecipe(<Forestry:ingotBronze>, <ore:ingotTin>, <ThermalExpansion:material:514>, 200,  100, [<ore:ingotCopper> * 3]);

**Comment by BluSunrize** [comment]
Intentional, more or less. Wontfix

**Comment by Lanse505** [comment]
Okey good to know :) thanks for all the help either way <3
