### ISSUE TITLE
CraftTweaker 1.18.2 support not updated

### ISSUE THREAD

**Issue by 435THz** [BluSunrize/ImmersiveEngineering#5420]
### Minecraft Version

1.18

### Immersive Engineering Version

8.2.2-154

### Expected Behavior

Crafttweaker 1.18.2 support adding a new IE recipe

### Actual Behavior

Crafttweaker 1.18.2 support did nothing

### Steps to reproduce

1: install IE and CraftTweaker 1.18.2
2: write a script following the example files guide
3: load a world/reload crafttweaker scripts
4: the recipe will NOT be added

### Debug Crash Log

https://pastebin.com/B3s0xMmp

**Comment by BluSunrize** [comment]
Can you actually show the craftweaker script you used, and the craftweaker log? Those would help immensly.

**Comment by 435THz** [comment]
I can't right now but i think i'll be able to upload them within the next 24 hours

**Comment by 435THz** [comment]
Okay, i don't... seem to be able to replicate it. I'm sure it didn't work last time i did it, but when i had the issue it gave me no errors so i'm not even sure what happened. I'll close this and come back to you with more complete documentation if it ever happens again, i guess. Sorry for the trouble.
