### ISSUE TITLE
1.19 Wires not rendering 

### ISSUE THREAD

**Issue by trechetican** [BluSunrize/ImmersiveEngineering#5424]
### Minecraft Version

1.19

### Immersive Engineering Version

1.19.2-9.0.0-153

### Expected Behavior

Can see Wires 

### Actual Behavior

Cannot see wires 

### Steps to reproduce

1.i place wire
2.shock my self 
3. puzzled expression as no wires are there 
4. profit 

### Debug Crash Log

https://pastebin.com/mQKqCpjh

**Comment by BluSunrize** [comment]
Closing this, since Rubidium is the reason, as established on Discord.
