### ISSUE TITLE
[1.19.2] OptiFine + some shader causes texture anomalies.

### ISSUE THREAD

**Issue by h-holon** [BluSunrize/ImmersiveEngineering#5427]
### Minecraft Version

1.19

### Immersive Engineering Version

1.19.2-9.0.0-153

### Expected Behavior

OptiFine + some shader should render the texture correctly.

### Actual Behavior

It crashes when started with OptiFine + some shader.
When I start with OptiFine+no shader, it starts without problems and displays the textures correctly.
However, if I activate any shader (BSL, continuum, or any other) on OptiFine, it takes a while and then shows up with a purple and black checkerboard texture.

### Steps to reproduce

1. add mod ImmersiveEngineering 1.19.2-9.0.0, OptiFine HD U H9(1.19.2) and some shader(BSL, continuum, etc...)
2. If I disable the shaders and start the system, it will start correctly. Crashes when enabled.
3. After starting with shaders disabled, go to the settings screen and enable shaders (BSL, continuum, etc...) After a short time, Immsersive Engineering's coke oven is displayed in a purple and black checkerboard pattern.
4. After the purple and black checkerboard pattern state, the texture remains purple and black even after the shaders are disabled.

### Debug Crash Log

https://gist.github.com/h-holon/ff949d2d3b752451fe3a856651a50648

**Comment by h-holon** [comment]
No shader->
![2022-09-07_00 58 04](https://user-images.githubusercontent.com/4555752/188689815-062bdedb-1973-40fb-87c3-c2c201cc290c.png)
after OptiFine shader enabled->
![2022-09-07_01 00 55](https://user-images.githubusercontent.com/4555752/188689829-751e92c2-b758-4525-a548-1be5140a2010.png)

**Comment by BluSunrize** [comment]
Optifine is not supported.
