### ISSUE TITLE
garden cloche does not accept mystical agriculture seeds

### ISSUE THREAD

**Issue by minecrafterseppe** [BluSunrize/ImmersiveEngineering#5428]
### Minecraft Version

1.19

### Immersive Engineering Version

1.19.2-9.0.0-153

### Expected Behavior

dropping and dragging the seeds in does not work
it wont accept it

### Actual Behavior

seeds should go in and be able to grow inside of it

### Steps to reproduce

right clicked the seeds in it

### Debug Crash Log

https://pastebin.com/VrL90gv2

**Comment by TeamSpen210** [comment]
There's intentionally no compatibility for MA's plants due to it being very overpowered.

**Comment by BluSunrize** [comment]
Yep, what Spen said.

MA compat was removed after 1.7.10 and will not be returning. If you want it, you will need to make a datapack (or find one that does it already.)
