### ISSUE TITLE
[Suggestion] Add config option to change inventory size for storage crates

### ISSUE THREAD

**Issue by damien5314** [BluSunrize/ImmersiveEngineering#5430]
### Explain your idea

raising new issue as requested in https://github.com/BluSunrize/ImmersiveEngineering/issues/2748

As stated; a config option that applies to storage crates to change their capacity. This would be useful for those wanting to tweak the size for game balance or other reasons.

**Comment by BluSunrize** [comment]
I didn't request a new issue really, I just told you off for necroposting.

And this is not a feature I'm interested in adding, sorry.
