### ISSUE TITLE
Problems with local server host

### ISSUE THREAD

**Issue by illuxel** [BluSunrize/ImmersiveEngineering#5431]
### Minecraft Version

1.19

### Immersive Engineering Version

ImmersiveEngineering-1.19.2-9.0.0-153

### Expected Behavior

Mod won't start with localhost server. Error code: java.lang.IndexOutOfBoundsException: readerIndex(5).

### Actual Behavior

I tried to delete all mods and setuped just immersive. We tested this mod with my friend and every time 

### Steps to reproduce

1. Download the mod;
2. Start local server;
3. Invite friend.

### Debug Crash Log

java.lang.IndexOutOfBoundsException: readerIndex(5)

**Comment by mindforger** [comment]
Please add the full crashlog file using pastebin, this singular line helps nobody

**Comment by BluSunrize** [comment]
As mindforger already said (though mind, seriously, we can moderate our own issue tracker, thanks):

Provide a full log. It literally says so in the issue template, you completely ignored it.

**Comment by wiphand** [comment]
Have same problem. issue is the logs really don't have anything much at all. Host side its completely empty:

> [23:22:43] [Render thread/INFO]: [System] [CHAT] Local game hosted on port 49952
> [23:22:43] [Sound engine/ERROR]: Creating buffer: Invalid parameter parameter value.
> [23:22:52] [User Authenticator #1/INFO]: UUID of player Wispyrose is xxx
> [23:22:56] [Server thread/INFO]: Using new advancement loading for net.minecraft.server.PlayerAdvancements@33add052
> [23:22:56] [Server thread/INFO]: Wispyrose[/[xxx]:58667] logged in with entity id 779 at (-1171.8033293580868, 68.0, -238.69999998807907)
> [23:22:56] [Server thread/INFO]: Wispyrose joined the game
> [23:22:56] [Render thread/INFO]: [System] [CHAT] Wispyrose joined the game
> [23:22:57] [Server thread/INFO]: Syncing config to Wispyrose (xxx)
> [23:23:01] [Server thread/INFO]: Wispyrose lost connection: Disconnected
> [23:23:01] [Server thread/INFO]: Wispyrose left the game
> [23:23:01] [Render thread/INFO]: [System] [CHAT] Wispyrose left the game

and then joining side

> [13:03:43] [Render thread/WARN]: java.lang.Throwable: Can't get entityTexture for translation{key='entity.minecraft.creeper', args=[]}
> [13:03:47] [Netty Client IO #3/ERROR]: Received empty payload on channel immersiveengineering:main
> [13:05:40] [Netty Client IO #3/WARN]: Packet not registered: ClientboundDisconnectPacket
> [13:05:40] [Render thread/INFO]: JEI StartEventObserver received class net.minecraftforge.client.event.ClientPlayerNetworkEvent$LoggingOut
> [13:05:40] [Render thread/INFO]: JEI StartEventObserver transitioning state from JEI_STARTED to DISABLED
> [13:05:40] [Render thread/INFO]: Stopping JEI
> [13:05:40] [Render thread/INFO]: Removed all colony views
> [13:05:40] [Render thread/INFO]: Mapping halted in: xxxx
> [13:05:42] [Render thread/WARN]: Client logged off. Resetting Pack Meta and Reloading State

**Comment by BluSunrize** [comment]
I mean, if you're not gonna give me a crash log, I might as well close this.

I'll happily reopen the issue once full log files have been provided.

**Comment by wiphand** [comment]
there is no crash log unless the crash folder is supposed to be in a different folder from this. the snippets i sent are from latest logs. i don;t know if i can send the entire thing as there are idenfiable infos there that i'd have to go through hundreds of spam lines to remove
![unknown](https://user-images.githubusercontent.com/7291720/189534183-6de5008a-1270-48d1-83e5-92afdfde0d3c.png)

**Comment by BluSunrize** [comment]
And the issue template literally tells you to generate a debug crash log.

**Comment by wiphand** [comment]
The bug template tells you how to make and to make a debug crash log. A crash issue template tells me to get a crash log that does not exist for the issue. A natural categorization for this occurrence is a crash imo. Not to mention this is not my issue so i never saw the templates. 
https://bytebin.lucko.me/5cBa7P9ZDc
Debug crash.
I get the index out of bounds sometimes directly on world join sometimes after multiple 10 of minutes of play sometimes 3 times in a couple minutes. 

The ops force crash would have been more useful given that he tried it with just your mod if i understand it correctly. I'm playing with a significant amount.

**Comment by BluSunrize** [comment]
This was *literally opened with the bug template*.
And then that template was *fully ignored*.

And I am **talking to the OP** most of all. I want their friggin log, since they reported the issue. But thank you for your contribution.
