### ISSUE TITLE
#5071 doesn't work

### ISSUE THREAD

**Issue by ElBowa** [BluSunrize/ImmersiveEngineering#5436]
### Minecraft Version

1.18

### Immersive Engineering Version

1.18.2-8.2.2-154

### Expected Behavior

The transaltion #5071 should translate the game

### Actual Behavior

the file #5071 is named with capital letters "it_IT.json", the game recognize "it_it.json", simply changing the name should make it work

### Steps to reproduce

try to play the game in italian

### Debug Crash Log

there was no crash, it doesn't work but this field is mandatory

**Comment by BluSunrize** [comment]
Has since been resolved
