### ISSUE TITLE
Cardboard Boxes

### ISSUE THREAD

**Issue by Thepigcat76** [BluSunrize/ImmersiveEngineering#5438]
### Explain your idea

A new use for Fiberboard, Cardboard boxes!

Perhaps it could be crafted with 1 slime ball or 1 slag and 8 Fiberboard.

It would allow you to carry blocks with nbts (chests, furnaces etc...), maybe you could even use it to carry small mobs (chickens, bees, baby animals, silverfish and endermites .

**Comment by BluSunrize** [comment]
Absolutely not!
Blocks were not meant to move like that.
