### ISSUE TITLE
Rendering issue with the Bottler

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#544]
Action: Sending a single, or a stack, of items through the Bottler

~~The machine accepts only one bucket at a time, one per second from what I can tell. This is OK, however this seems to lead to a weird rendering glitch. Regardless if the itemstack was depleted or not, a singular bucket materializes and disappears in the same place as the waiting buckets.~~
EDIT:
When the machine outputs an item, regardless of if it fills it or not it displays the item at the input end as shown in the video for a short yet noticeable moment

This is a little hard to show with words, I have recorded a demonstration of this bug [here] (https://youtu.be/YyzfcXxB4RM)

IE build 2d98f88

**Comment by cobra** [comment]
How did I manage to miss this issue? I've noticed this and PR'd a fix for that, which has been merged now.
