### ISSUE TITLE
Diesel generator noise and particles continue even if no power is being put out as long as it is not turned off manually

### ISSUE THREAD

**Issue by Glugax** [BluSunrize/ImmersiveEngineering#5440]
### Minecraft Version

1.18

### Immersive Engineering Version

1.18.2-8.2.2-154

### Expected Behavior

- connect fuel supply and power consumer to generator
- generator turns on and runs until no power is being consumed
- generator stops, no fuel consumption, no noise, no particles until it can output power again

### Actual Behavior

- connect fuel supply and power consumer to generator
- generator turns on 
- consumer stops drawing power
- noise and particles continue, no fuel is being used
- this continues until the generator is turned off via redstone signal at the terminal

### Steps to reproduce

- connect accumulator and sufficient fuel source to generator
- generator turns on and starts to fill up the acc.
- generator keeps making noise and producing particles even after the acc. is full as long as it hast fuel (it won't consume the fuel though)
- if the generator runs out of fuel befor the acc. is full it will fully stop as it is supposed to 

### Debug Crash Log

https://pastebin.com/4DxZBvHk

**Comment by pespinho** [comment]
I am also experiencing this problem.
