### ISSUE TITLE
Mystical Agriculture seeds not working 

### ISSUE THREAD

**Issue by Alfatossa** [BluSunrize/ImmersiveEngineering#5441]
### Minecraft Version

1.18

### Immersive Engineering Version

1.18.2-8.2.2-154

### Expected Behavior

Mystical Agriculture seeds should work in the garden Cloche

### Actual Behavior

any seed from mystical agriculture wont work with the garden cloche (not growing)

### Steps to reproduce

1. Place a Garden Cloche
2. Connect Everything (Power, Water, Item output)
3. Put Mystical Seed and farmland in the cloche

### Debug Crash Log

https://pastebin.com/4qWj1AMH

**Comment by BluSunrize** [comment]
Mystical Agriculture compat was removed years ago. It will not be readded as part of IE.
If you want those recipes, you'll need to use a datapack.
