### ISSUE TITLE
Optifine mixins crash dev environments

### ISSUE THREAD

**Issue by rlnt** [BluSunrize/ImmersiveEngineering#5442]
### Minecraft Version

1.18

### Immersive Engineering Version

8.2.1-152

### How did it happen?

When loading Immersive Engineering in a dev environment, it will always crash your game upon loading the world.

Doesn't matter if you implement it with a `flatDir` dependency, with CurseMaven or with your official artifacts from the BlameJared maven. It always crashes when loaded into the runtime.

Seems to be caused by the Optifine mixin targetted by `RebuildTaskMixin`.
```
[22:55:01] [Render thread/WARN] (mixin) Error loading class: net/optifine/override/ChunkCacheOF (java.lang.ClassNotFoundException: net.optifine.override.ChunkCacheOF)
```

### Crash Log

https://pastebin.com/XZCBDesG

**Comment by malte0811** [comment]
This is with arch-loom, right? I'm pretty sure it works fine under ForgeGradle (various people including myself have done addon dev on 1.18), so I'd consider it a bug in arch.

**Comment by rlnt** [comment]
Is is but wouldn't it make sense to make this a conditional mixin if the target mod is actually found? We use a MixinPlugin for that in our mods which works pretty well.
