### ISSUE TITLE
Equiping a drill loaded with any type of drill crashes when equiped

### ISSUE THREAD

**Issue by remuluson2** [BluSunrize/ImmersiveEngineering#5443]
### Minecraft Version

1.18

### Immersive Engineering Version

1.18.1-7.1.0-145

### How did it happen?

After finally creating mining drill I equipped it with steel drill and durability upgrade.
When I loaded it will fuel from refinery it would crash whenever I try to equip the drill.
Removing upgrade didn't fix the problem.

As long as drill doesn't have any type of head equipped it doesn't crash but that's a not very useful drill, isnt it?

### Crash Log

https://pastebin.com/Ugi7TTEh

**Comment by remuluson2** [comment]
Hold on. I just tried removing the drill and it didnt crash as long as it doesnt have a drill. I will check if using iron drill fixes it.

**Comment by malte0811** [comment]
1.18.1 is no longer supported, please update to 1.18.2. If you can reproduce the crash on 1.18.2, please post the new crashlog here together with a full client log. You can comment on closed issues, I'll reopen this if it happens on 1.18.2.
