### ISSUE TITLE
Crash when i sift+click to created 'Railgun' pattern, to move it to inventory

### ISSUE THREAD

**Issue by gisellevonbingen** [BluSunrize/ImmersiveEngineering#5444]
### Minecraft Version

1.18

### Immersive Engineering Version

8.2.2-154

### How did it happen?

I'm playing Atm7 Sky 1.0.8
When i create 'Railgun' pattern, and move it to my inventory as shift+click,
Minecraft was crash
It can still reproduce.

I was recode gif file about occurring crash
![Crash](https://user-images.githubusercontent.com/44163945/192134685-500f38b5-4f6e-477b-8281-0e3b71c5093b.gif)

### Crash Log

https://gist.github.com/gisellevonbingen/e6be5f963b998081af282fec8953bdcc

**Comment by malte0811** [comment]
IMO this is on AE2's end. They are skipping the `bakedmodel.getOverrides().resolve(…)` call on the railgun item model, which I don't think is valid. Can you open a report on their issue tracker as well? I'll close this for the time being, if the AE2 devs think it should be changed on IE's end as well they can comment here or ping me and I'll reopen the issue.

**Comment by shartte** [comment]
I'll take a look at it

**Comment by shartte** [comment]
Switching to net.minecraft.client.renderer.entity.ItemRenderer#getModel fixed this problem.
