### ISSUE TITLE
1.19.2 Game load crash.

### ISSUE THREAD

**Issue by TheRTGGaming** [BluSunrize/ImmersiveEngineering#5445]
### Minecraft Version

1.19

### Immersive Engineering Version

1.19.2-9.0.0-153

### How did it happen?

Loading my mod pack with set mods will crash minecraft. on start up/

### Crash Log

https://gist.github.com/TheaRTGGaming/0d717d7d683cd3a5d05c8416265931da

**Comment by BluSunrize** [comment]
Optifine is not supported =)
