### ISSUE TITLE
Could it be a Optifine crash???

### ISSUE THREAD

**Issue by TheRTGGaming** [BluSunrize/ImmersiveEngineering#5446]
### Minecraft Version

1.19

### Immersive Engineering Version

1.19.2-9.0.0-153

### How did it happen?

as of writing this. this version of Immersive Engineering is the latest version. digging deeper, the impact might not be optifine. i have downgreaded the versions of "Applied Energistics 2" "Corail Tombstone" and "Project MMO" I do not know why the crash report was implying that immersive Engineering would be the cause. but lets figure this out. First i am going to launch minecraft with all accounted mods updated. then launch the mods together with them down graded to the version that works.

### Crash Log

https://gist.github.com/TheaRTGGaming/37bcff85f351e0e629fd9ed1d004963d

**Comment by TheRTGGaming** [comment]
the working version is listed as below.

forge - 43.1.17

appliedenergistics2-12.5.0-beta

tombstone-8.1.3-1.19.2

pmmo-1.19-0.4.0

**Comment by TheRTGGaming** [comment]
Here is the log for the working version the the mod pack i have been using. loaded up fine and no crashes.

https://gist.github.com/TheaRTGGaming/d99a517da2e26020e632f6cbbab6dc0e

**Comment by malte0811** [comment]
This is on Optifine to fix. Any mod using OBJ models will cause this crash on Forge 43.1.24 and above with Optifine.
