### ISSUE TITLE
invisible wire ImmersiveEngineering

### ISSUE THREAD

**Issue by avnm322** [BluSunrize/ImmersiveEngineering#5447]
### Minecraft Version

1.18

### Immersive Engineering Version

1.18.2-8.22-154

### Actual Behavior

No one on my server can see the wire
Actually he is connected
![image](https://user-images.githubusercontent.com/72611436/192901256-0160712a-e640-4f3a-b31e-6bc541b1c2ea.png)

### Debug Crash Log

https://pastebin.com/DVyQLqbH

**Comment by BluSunrize** [comment]
Optifine is not supported
