### ISSUE TITLE
Revolver modifiers from the Hammer and Barrel aren't applied.

### ISSUE THREAD

**Issue by Darkally33** [BluSunrize/ImmersiveEngineering#5452]
### Minecraft Version

1.19

### Immersive Engineering Version

1.19.2-9.0.0-153

### Expected Behavior

Crafting a Revolver with with modifiers on the Revolver Drum, Revolver Hammer, and Revolver Barrel should result in a Revolver with the modifiers of the three parts combined.

### Actual Behavior

Only the modifiers on the Revolver Drum are applied to the resulting Revolver.
Swapping out the Hammer or Barrel for parts with different modifiers has no effect on the crafting result.

To test if this was just a tooltip issue, I tested the below Revolver against one with no modifiers, and there appeared to be no difference in fire rate.
![2022-10-02_14 29 19](https://user-images.githubusercontent.com/78669103/193477835-285e0bb2-9f66-40be-8c2a-0e08e2a5503d.png)
![2022-10-02_14 29 22](https://user-images.githubusercontent.com/78669103/193477841-e7857d18-88e4-4c2f-b460-db328adf31c3.png)
![2022-10-02_14 29 24](https://user-images.githubusercontent.com/78669103/193477843-cbf913de-6761-4ed1-b48a-47d4ea5066cd.png)
![2022-10-02_14 29 28](https://user-images.githubusercontent.com/78669103/193477846-aa4da94e-cfba-4fb9-8607-787dde2129db.png)

### Steps to reproduce

1. Spawn in and level up a bunch of Gunsmith villagers to get a selection of Revolver parts with modifiers.
2. Craft a Revolver using said parts, paying attention to what modifier each part has.
3. The resulting Revolver will only have the modifiers from the Drum.

### Debug Crash Log

https://pastebin.com/gMK7FQEp

**Comment by gorberto** [comment]
This bug also exists in version 1.18.2, I've opened PRs against both versions to fix it.

**Comment by BluSunrize** [comment]
Closed by merged PR, will be resolved by next release
