### ISSUE TITLE
ImmersiveEngineering-1.19.2-9.0.0-153 crash

### ISSUE THREAD

**Issue by sez76** [BluSunrize/ImmersiveEngineering#5455]
### Minecraft Version

1.19

### Immersive Engineering Version

crash 1.19 

### How did it happen?

Hello,

I have my server start normally with ImmersiveEngineering-1.19.2-9.0.0-153, but if I start Minecraft, is crashed.

I have this error message:
`The game crashed whilst rendering overlay
Error: java.lang.NoSuchMethodError: 'void net.minecraft.client.renderer.block.model.BakedQuad.<init>(int[], int, net.minecraft.core.Direction, net.minecraft.client.renderer.texture.TextureAtlasSprite, boolean, boolean)'`

Do you have a solution to resolve this problem ?

Many thanks

### Crash Log

https://gist.github.com/sez76/ccd1d2105c813d7024846a7cf6048ee3

**Comment by XFactHD** [comment]
This crash is caused by OptiFine and there is nothing the ImmersiveEngineering devs can do about it. Complain to OptiFine about breaking on every minor Forge update.

**Comment by sez76** [comment]
Hi @XFactHD 

Thank you for your help :D
