### ISSUE TITLE
Ammo/fuel is consumed in Creative Mode

### ISSUE THREAD

**Issue by Toastr125** [BluSunrize/ImmersiveEngineering#5461]
### Minecraft Version

1.19

### Immersive Engineering Version

9.0.0-153

### Expected Behavior

Ammo and fuel for tools would not be consumed in creative mode, much like how arrows are not consumed when firing a bow

### Actual Behavior

When used in creative mode...
1. Railgun uses up projectiles out of the inventory
2. Revolver uses up cartridges
3. Chemthrower uses up stored chemicals
4. Mining drill uses up fuel and drill head durability (note: this only happens when using it as a weapon, it does not use either when mining)
5. Buzzsaw uses up fuel when attacking (does not use sawblade durability though)

### Steps to reproduce

1. Go into creative mode
2. Use any of the tools listed above (with the conditions listed for the last 2)

### Debug Crash Log

https://pastebin.com/0peMi8L1

**Comment by Toastr125** [comment]
Oh, and the railgun consumes power when fired in creative mode too

**Comment by BluSunrize** [comment]
Not an issue. Intentional behavior.
I do most of my testing in creative mode, I want to be able to verify that all consumption mechanics still work then.
