### ISSUE TITLE
IE crash with optifine HD U H9

### ISSUE THREAD

**Issue by Nickana** [BluSunrize/ImmersiveEngineering#5467]
### Minecraft Version

1.19

### Immersive Engineering Version

ImmersiveEngineering-1.19.2-9.0.0-153

### How did it happen?

Crash when game lounch, i didnt use nothing besides IE, forge 43.1.43 and optifine HD U H9
How can these two mods coflict at all, and how to fix it?

### Crash Log

https://pastebin.com/mCSxNG3f

**Comment by malte0811** [comment]
See sp614x/optifine#7127
