### ISSUE TITLE
[1.18.2] Forge Server crashes on first launch with v154, fixed by installing v152 and then updating

### ISSUE THREAD

**Issue by zacmanthedamned** [BluSunrize/ImmersiveEngineering#5468]
### Minecraft Version

1.18

### Immersive Engineering Version

1.18.2-8.2.2-154

### How did it happen?

During first launch of a newly-setup Forge Server (1.18.2, Forge v40.1.84), server crashed during initialization. Through process of elimination, confirmed Immersive Engineering was the culprit. The following failed to resolve the issue:
-Launching the server with only IE installed
-downgrading from JDK 19 to 17

As a last resort before taking more drastic measures (purging configs, asking for help, etc.), downgraded IE to v152. Server launched without issue running just 152. After removing 152 and installing 154 again (because I was too lazy to install winrar on the server machine to get at the logs), the server launched without any issue.

### Crash Log

https://gist.github.com/zacmanthedamned/be0d2a26fb97cb86a81f71e4058a8314#file-2022-10-19-3-log

**Comment by BluSunrize** [comment]
Don't think there's much we can do about this, so closing it.
