### ISSUE TITLE
Fermenter and Squeezer recipes not viewable in JEI with update to version 10.*

### ISSUE THREAD

**Issue by DelviousCrafts** [BluSunrize/ImmersiveEngineering#5475]
### Minecraft Version

1.18

### Immersive Engineering Version

8.2.2-154

### Expected Behavior

Updating to the latest version of JEI (10.2.1.278) to still display recipes for the industrial squeezer and industrial fermenter. 

### Actual Behavior

Building a squeezer and or fermenter and clicking on the option in the GUI to show recipes will display multiple blank templates. The only recipe that actually shows up is the HOP graphite recipe in the industrial squeezer. May be an issue with drawing fluids in JEI. 

These multi-blocks still function as expected by creating appropriate fluids for given inputs, however, what those valid inputs are can not be seen in the JEI GUI.

This has been an issue for a while, however, JEI version 10+ was still in alpha and I was hoping this issue would be resolved in dev. As they just released version 10+ as a beta today, this appears to be an issue that needs to be reported to the mod dev responsible for drawing to JEI.

### Steps to reproduce

1. Install the latest version of JEI (10.*)
2. Build an industrial squeezer or industrial fermenter
3. Click the section in the GUI to Show Recipes.
4. See many empty recipe slots and tanks in JEI.

### Debug Crash Log

https://gist.github.com/DelviousCrafts/1adc307890c310499173a045ae55018d

**Comment by Filostorm** [comment]
Also having this issue

**Comment by Gitcrafter** [comment]
its not just the sqeezer and the fermenter, the bottler, coke oven, mixer and refinery are affected too

**Comment by malte0811** [comment]
Fixed by 0d0adb0cc4540ccbdf09c76829c7f0bd866abb33, but I forgot to add the issue number to the commit message.
