### ISSUE TITLE
1.19.2 Server Crashing with Registry Object not present: immersiveengineering:shader

### ISSUE THREAD

**Issue by TobiDoes** [BluSunrize/ImmersiveEngineering#5476]
### Minecraft Version

1.19

### Immersive Engineering Version

1.19.2-9.00-153

### How did it happen?

as i was starting up a test server (to see if things would run) it crashed pushing a Registry Object not present: immersiveengineering:shader along with a few other mods erroring out i will most a pastebin at the bottem interesting part is that the modpack loads up just fine in a non server way I will contact the other Mod Creators that have a Report URL available 

### Crash Log

https://pastebin.com/1mCicg0h

**Comment by malte0811** [comment]
As in the issues you posted for Occultism and Sophisticated Backpacks, this is unlikely to be an IE bug since multiple mods are running into similar exceptions. Most likely something went wrong earlier during the launch and Forge continued to load in some highly broken state.
