### ISSUE TITLE
Crash: Invalid item: minecraft:air

### ISSUE THREAD

**Issue by CrusaderRabbit** [BluSunrize/ImmersiveEngineering#5477]
### Minecraft Version

1.18

### Immersive Engineering Version

ImmersiveEngineering-1.18.2-8.2.2-154

### How did it happen?

Using kubejs, removed tags from copper/gold/iron plates. Crashed twice now.

### Crash Log

https://pastebin.com/0iSBP12f

**Comment by malte0811** [comment]
This is probably because some of our recipes still output those plates, with the output specified by a tag. And since IE is adding those items to the tag, the recipe does not have a check to make sure the tag isn't empty. I guess we could change that, but why would you remove them from the tag in the first place?

**Comment by BluSunrize** [comment]
Stop removing tags from things if you don't know what you're doing, lmao.

**Comment by CrusaderRabbit** [comment]
Firstly, thank you for the quite rude response. I was only sharing the crash report but I am remiss and will not share reports for this mod anymore. I am not using those plates because I already have iron/gold/copper plates and the tag ISN'T empty. I have not seen the crash again.

Edit:
I realize I didn't explain the situation well. I removed the tags ONLY from IE gold/copper/iron plates.  Create Sheets of those metal types are still in the tags. It only crashed when reloading. After the first reload it never happened again.

**Comment by BluSunrize** [comment]
The point of tags is to unify items. Taking things out of them goes directly against what they are supposed to be used for.
If you don't want IE machines to output IE items, then we have a config option for that, or you can replace the recipes themselves.

Removing items from their tag is the wrong approach to your problem.

**Comment by CrusaderRabbit** [comment]
The recipes in the IE machines were all removed, all outputs and inputs for those plates were all replaced prior to removing them from the tag with create plates of those metal types. Again, not asking for anything to be done, found a crash and shared it.
