### ISSUE TITLE
[Suggestion] Refinery Missing Slot for Automatic Catalyst Input

### ISSUE THREAD

**Issue by StephenLeeY** [BluSunrize/ImmersiveEngineering#5484]
### Explain your idea

 _Refinery_ lacks input slot on multiblock to automatically pipe in **items** to catalyst slot. This is relevant when, for example, creating _Acetaldehyde_ and _silver plate_ is needed in catalyst slot, but cannot be automated as there is no slot to pipe in items.

Similar to the _Fermenter_, the _Refinery_ should have a slot in the front or back that accepts item input for the catalyst slot via item pipes or conveyor belts.

**Comment by BluSunrize** [comment]
Catalysts are not consumed. They do not need to be automated.
