### ISSUE TITLE
Chemical Thrower causes players to disconnect.

### ISSUE THREAD

**Issue by leledragon1354** [BluSunrize/ImmersiveEngineering#5488]
### Minecraft Version

1.18

### Immersive Engineering Version

1.18.2-8.2.2-154

### Expected Behavior

When firing anything from the chemical thrower the expected behaviour is to not get kicked from the server.

### Actual Behavior

Equipping and firing any liquid from a chemical thrower, with or without the pilot light, on a server will cause this error and disconnect the player:

Connection Lost
io.netty.handler.codec.DecoderException: Unknown serializer type 108

### Steps to reproduce

1. Join a multiplayer server.
2. Load the chemical thrower with any liquid.
3. Fire the chemical thrower.

The modpack used is: https://www.feed-the-beast.com/modpacks/100-ftb-stoneblock-3 version 1.3.0

### Debug Crash Log

https://gist.github.com/leledragon1354/37138c91818f96e94870dae9a8eca938
https://gist.github.com/leledragon1354/3246455b60b9db39a6c91454a620f73d

**Comment by BluSunrize** [comment]
Can you check if this issue happens without Bloodmagic installed?

**Comment by leledragon1354** [comment]
Unfortunately while I could get the logs I don't really have a server of my own to test this out with, sorry.

**Comment by BluSunrize** [comment]
Closing this as assumed to be fixed. We haven't had reports since Malte worked on this in November.
