### ISSUE TITLE
Progress bar or other visual in garden cloche GUI

### ISSUE THREAD

**Issue by turtlecat77** [BluSunrize/ImmersiveEngineering#5489]
### Explain your idea

Since cloches can be slow sometimes, it can be hard to tell if a cloche is actually functioning and the ingredients are correct (growing magic crops can be finnicky). The particle effects around the lights don't seem to necessarily correspond to the cloche actually being active necessarily. 

A lot of tech mods (e.g. Applied Energistics) use a small yellow to orange progress bar to show users how far along the machine has processed. In cloche's case it would be how far until 1 item (such as wheat) or essence (magical crops) has been produced. This would also indicate if the machine is turned on or off.

**Comment by BluSunrize** [comment]
I mean, magical crops aren't even supported by IE natively.
All the plants we support in the Cloche have distinct visual growth as well...
