### ISSUE TITLE
Bottler only forms in one direction

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#549]
Issue: The bottler MB will only form if it is built so its 'front' face , the face with the most conveyors, is pointing to the East. No other direction works. See attached

![image](https://cloud.githubusercontent.com/assets/3110986/10864919/ae2e3154-7fb9-11e5-9d5c-3341307c6214.png)

Bare-minimum MC instance, 
Ie build 2d98f88

**Comment by cobra** [comment]
wtf? I built them in all eight possible directions (N/S/E/W, mirrored/not mirrored). Are you sure your conveyors are facing the right way? There are some invalid orientations in that screenshot.

**Comment by theunkn0wn1** [comment]
The orientation of the conveyors I found though testing made no difference.
I have attempted with the valid orientations and it made no difference.

**Comment by cobra** [comment]
![2015-10-31_18 44 51](https://cloud.githubusercontent.com/assets/163331/10865036/8983b7b6-7fff-11e5-845e-fe96ba42bc31.png)
![2015-10-31_18 45 14](https://cloud.githubusercontent.com/assets/163331/10865037/8fe1ca94-7fff-11e5-945f-4fd225a0e370.png)

**Comment by cobra** [comment]
Also, read the book, the machine has proper documentation now.

**Comment by theunkn0wn1** [comment]
Discregard all... its just really difficult to form correctly...
