### ISSUE TITLE
Crash with Optifine in `BakedQuadBuilder`

### ISSUE THREAD

**Issue by FryThread** [BluSunrize/ImmersiveEngineering#5492]
### Minecraft Version

1.19

### Immersive Engineering Version

ImmersiveEngineering-1.19.2-9.0.0-153

### How did it happen?

Stacktrace:
	at com.google.common.base.Preconditions.checkState(Preconditions.java:486) ~[guava-31.0.1-jre.jar%23115!/:?] {}
	at blusunrize.immersiveengineering.client.utils.BakedQuadBuilder.putVertexData(BakedQuadBuilder.java:49) ~[ImmersiveEngineering-1.19.2-9.0.0-153.jar%23159!/:?] {re:classloading}
-- Block model being tesselated --
Details:
	Block: Block{immersiveengineering:circuit_table}[facing=east,multiblockslave=false,waterlogged=false]
	Block location: World: (14 02,105,1351), Section: (at 10,9,7 in 87,6,84; chunk contains blocks 1392,-64,1344 to 1407,319,1359), Region: (2,2; contains chunks 64,64 to 95,95, blocks 1024,-64,1024 to 1535,319,1535)
	Using AO: true
[crash-2022-11-27_03.02.10-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/10097326/crash-2022-11-27_03.02.10-client.txt)

### Crash Log

https://gist.github.com/FryThread/da156c555f5ad06365f1d00d4345f7e4

**Comment by malte0811** [comment]
Fixed by 9aac40731d732d1e84eac426ecd12e5435b33f5a
