### ISSUE TITLE
wires 

### ISSUE THREAD

**Issue by vojtazsa** [BluSunrize/ImmersiveEngineering#5495]
### Minecraft Version

1.18

### Immersive Engineering Version

1.18.2-8.2.2-154

### Expected Behavior

when I connect comectors and other devices to each other, a connection should be made between them using wires

### Actual Behavior

when connecting the cables to the connectors and below, the given things do not connect and I do not even see the connection between them 

### Steps to reproduce

I put it on the dynamo and connected the LV conector to it and stretched the wire from it to the relay and the connection did not happen
![2022-12-02_21 21 56](https://user-images.githubusercontent.com/119702769/205380383-bfb64bca-9d86-4fde-8f1a-b2315faa2a57.png)
![2022-12-02_21 22 04](https://user-images.githubusercontent.com/119702769/205380393-d2f2d80b-4aba-4919-9fc9-73b5896c2f2a.png)
![2022-12-02_21 22 18](https://user-images.githubusercontent.com/119702769/205380396-3ae3f202-7c47-46be-9c8a-3dd019b0f897.png)
![2022-12-02_21 22 20](https://user-images.githubusercontent.com/119702769/205380399-fad98308-3e8c-47f6-a1c8-6688609ae295.png)
![2022-12-02_21 22 25](https://user-images.githubusercontent.com/119702769/205380403-b0dc834a-8890-491f-be2f-d24da998e971.png)

### Debug Crash Log

https://pastebin.com/JJ4zzWG6

**Comment by BluSunrize** [comment]
Your debug crashlog is not longer accessible, please provide a new one.

**Comment by BluSunrize** [comment]
Closing this due to lack of response
