### ISSUE TITLE
[1.18.2] semi consistent crash on loading into a server relating to wires

### ISSUE THREAD

**Issue by xemnes** [BluSunrize/ImmersiveEngineering#5499]
### Minecraft Version

1.18

### Immersive Engineering Version

8.2.2-154

### How did it happen?

i joined my server, it spent a couple of seconds to get into the game, i see the world for a split second and then i crash.
the crash doesnt always happen, only sometimes, about 70% of the time. my friends who use the same modpack and same mods, including optifine, have yet to crash for the same reason, just me.

### Crash Log

https://pastebin.com/p7sGCqjB

**Comment by malte0811** [comment]
Optifine is not supported in general, and this is a very "impossible" crash that would probably be a lot of work to track down even without Optifine making things more difficult. I'll close this issue for now. If you run into the crash without Optifine please post a new crashlog and the full client log on this issue, I'll reopen it then.

**Comment by xemnes** [comment]
alright, thats a pitty. thanks for responding though. sadly im stuck using optifine because i use conquest reforged which requires optifines ctm features. if there was an alternative, i would use it.
