### ISSUE TITLE
V0.1.9 - Biodiesel production hangs the game - in SSP/SMP

### ISSUE THREAD

**Issue by mbhalo** [BluSunrize/ImmersiveEngineering#55]
Running Industrial Squeezer, Fermenter and Refinery causes freezing after running for a few minutes - tested in SSP/SMP. No errors in the logs.

Here is the screenshot of the setup - http://i.imgur.com/KIDENdD.png

List of mods installed: 

AdditionalPipes-4.5.1.jar
AdvancedMachines-59.0.2.jar
AdvancedRepulsionSystems-59.0.3.jar
AdvancedSolarPanel-1.7.10-3.5.1.jar
AE2Stuff-0.3.0.30-mc1.7.10.jar
AncientWarfare-2.4.83-beta-MC1.7.10.jar
AOBD-2.6.2.jar
AppleCore-mc1.7.10-1.1.0.jar
AppleMilkTea2-1.7.10_2.6d.jar
AppliedEnergistics2-rv2-stable-3.jar
ArmorStatusHUD-client-1.7.10-1.28.jar
Aroma1997Core-1.7.10-1.0.2.13.jar
AromaBackup-1.7.10-0.0.0.5.jar
ATG-1.7.10-0.12.0.jar
Atum-1.7.10-0.6.60.jar
AutoPackager-1.5.3.jar
Bagginses-2.1.1.jar
Baubles-1.7.10-1.0.1.10.jar
BDlib-1.8.0.86-mc1.7.10.jar
BiblioCraft[v1.10.4][MC1.7.10].jar
BiblioWoods[BiomesOPlenty][v1.9].jar
BiblioWoods[Natura][v1.5].jar
BigReactors-0.4.3A.jar
BiomesOPlenty-1.7.10-2.1.0.1067-universal.jar
BloodMagic-1.7.10-1.3.2-1.jar
BluePower-1.7.10-0.2.938-universal.jar
Botania r1.6-190.jar
bspkrsCore-universal-6.15.jar
Buildcraft-7.0.4.jar
Buildcraft-Compat-7.0.2.jar
BuildcraftAdditions-1.7.10-2.1.4.jar
Carpenter's Blocks v3.3.6 - MC 1.7.10.jar
carpentersblocks
ChickenChunks-1.7.10-1.3.4.19-universal.jar
Chisel2-2.3.10.37.jar
ChiselFacades-1.7.10-2.10-cricket.jar
ChiselTones-1.7.10-1.0-1.jar
CloudMaster_1.7.10-1.3.jar
CodeChickenCore-1.7.10-1.0.6.43-universal.jar
CodeChickenLib-1.7.10-1.1.3.136-universal.jar
CoFHCore-[1.7.10]3.0.2-262.jar
CoFHLib-[1.7.10]1.0.2-160.jar
CompactMachines-1.7.10-1.19b.jar
CompactStorage-1.7.10-release-2.0.0.9-universal.jar
DarkMenagerie-1.7.10-beta-3.1a.jar
Decocraft-2.0.1_1.7.10.jar
Enchiridion-1.7.X-1.2b.jar
EnderIO-1.7.10-2.2.8.381.jar
EnderStorage-1.7.10-1.4.7.33-universal.jar
EnderTech-1.7.10-0.3.2.388.jar
EnderZoo-1.7.10-1.0.11.28.jar
EquivalentExchange3-1.7.10-0.3.507.jar
Eureka-1.7.10-3.0.2.jar
ExtraCells-1.7.10-2.2.70b119.jar
ExtraFixes-1.7.10-1.2.4b.jar
ExtraTiC-1.7.10-1.4.5.jar
ExtraUtilities-1.2.5.jar
FastLeafDecay-1.7.10-1.0.jar
FlaxbeardsSteamPower-1.7.10-0.28.7.jar
Forge-1.7.10-10.13.3.1407-1.7.10.jar
ForgeMultipart-1.7.10-1.1.2.331-universal.jar
FossilsArcheologyRevival-1.7.10_Build-7.1.jar
FunkyLocomotion-1.7.10-beta-5c.jar
FuturisticDecor-1.1.jar
GardenStuff-1.7.10-1.6.2.jar
Generators-0.9.13.72-mc1.7.10.jar
GraviSuite-1.7.10-2.0.3.jar
GrowthCraft-Apples-1.7.10-2.1.0.jar
GrowthCraft-Bamboo-1.7.10-2.1.0.jar
GrowthCraft-Bees-1.7.10-2.1.0.jar
GrowthCraft-Cellar-1.7.10-2.1.0a.jar
GrowthCraft-Core-1.7.10-2.1.0a.jar
GrowthCraft-Fishtrap-1.7.10-2.1.0a.jar
GrowthCraft-Grapes-1.7.10-2.1.0.jar
GrowthCraft-Hops-1.7.10-2.1.0.jar
GrowthCraft-Rice-1.7.10-2.1.0a.jar
HarvestCraft 1.7.10h.jar
Hats-4.0.1.jar
HungerOverhaul-1.7.10-1.0.0.jar
IC2NuclearControl-2.2.5a.jar
iChunUtil-4.2.2.jar
IguanaTinkerTweaks-1.7.10-2.1.5.jar
ImmersiveEngineering-0.1.9.jar
ImmibisCore-59.1.1.jar
IndustrialCraft-2-2.2.726-Experimental.jar
InventoryTweaks-1.58-147.jar
IvToolkit-1.2.jar
Jabba-1.2.1a_1.7.10.jar
KitchenCraft-MC1.7.10-0.0.1-59-combo.jar
LibSandstone-1.0.0.jar
liteloader-1.7.10.jar
MalisisCore-1.7.10-0.12.2.jar
MalisisDoors-1.7.10-1.8.1.jar
Mantle-1.7.10-0.3.2.jar
Mariculture-Deluxe-1.7.10-1.2.4.2a.jar
MineFactoryReloaded-[1.7.10]2.8.0-104.jar
MmmMmmMmmMmm-1.6.jar
MobiusCore-1.2.5_1.7.10.jar
MoCreatures-v6.3.1.zip
mod_voxelMap_1.5.13_for_1.7.10.litemod
Morpheus-1.7.10-1.6.4.jar
Natura-1.7.10-2.2.0.1.jar
NEIAddons-1.12.8.29-mc1.7.10.jar
NEIIntegration-MC1.7.10-1.0.9.jar
NotEnoughItems-1.7.10-1.0.4.107-universal.jar
NotEnoughKeys-1.7.10-1.0.0b29.jar
NotEnoughResources-1.7.10-0.1.0.95.jar
ObsidiPlates-1.7.10-universal-3.0.0.18.jar
OpenBlocks-1.7.10-1.4.3.jar
OpenComputers-MC1.7.10-1.5.11.25-universal.jar
OpenModsLib-1.7.10-0.7.3.jar
OpenModularTurrets-1.7.10-1.3.8-35.jar
OpenPeripheral-1.7.10-AIO-4.jar
PotionExtension-1.7.10-1.0.4.jar
PlantMegaPack-4.20-1.7.10-1291.jar
ProgressiveAutomation-1.7.10-1.6.16.jar
QmunityLib-1.7.10-0.1.109-universal.jar
Railcraft-1.7.10-9.6.1.0.jar
RecurrentComplex-0.9.6.2.jar
RedstoneArsenal-[1.7.10]1.1.0-80.jar
Reliquary-1.2.jar
RFDrills-1.7.10-1.3.1.jar
RFTools-2.91.jar
RFWindmill-1.7.10-0.6.jar
RouterReborn-1.7.10-1.1.52-universal.jar
Ruins-1.7.10.jar
SimplyJetpacks-MC1.7.10-1.5.1.jar
SolarFlux-1.7.10-0.5b.jar
SoulShardsReborn-rc3.jar
SpecialMobs-1.7.10-3.1.1.jar
SpiceOfLife-mc1.7.10-1.2.3.jar
StatusEffectHUD-client-1.7.10-1.27.jar
StevesAddons-1.7.10-0.10.12.jar
StevesCarts2.0.0.b18.jar
StevesFactoryManagerA93.jar
StevesWorkshop-0.5.1.jar
StorageDrawers-1.7.10-1.5.1.jar
StorageDrawers-BiomesOPlenty-1.7.10-1.0.0.jar
StorageDrawers-Natura-1.7.10-1.0.1.jar
Sync-4.0.0.jar
TCNodeTracker-1.7.10-1.1.1.jar
TConstruct-1.7.10-1.8.5.jar
Thaumcraft-1.7.10-4.2.3.5.jar
ThaumcraftNEIPlugin-1.7.10-1.7.jar
ThaumicExploration-1.7.10-1.1-37.jar
ThaumicTinkerer-2.5-1.7.10-164.jar
ThermalDynamics-[1.7.10]1.0.0-122.jar
ThermalExpansion-[1.7.10]4.0.1-182.jar
ThermalFoundation-[1.7.10]1.0.0-81.jar
ThermalSmeltery-1.7.10-1.2.1.jar
TiCTooltips-mc1.7.10-1.2.4.jar
TMechworks-1.7.10-0.2.14.100.jar
Translocator-1.7.10-1.1.1.14-universal.jar
TravellersGear-1.7.10-1.16.4.jar
TTCore-MC1.7.10-0.1.0-67.jar
Waila-1.5.10_1.7.10.jar
WailaHarvestability-mc1.7.x-1.1.2.jar
WailaPlugins-MC1.7.10-0.0.1-15.jar
WaterPower-1.7.10-0.3j.jar
Wawla-1.2.1_1.7.10.jar
Witchery-1.7.10-0.24.1.jar
WitchingGadgets-1.7.10-1.1.8.jar
WR-CBE-1.7.10-1.4.1.9-universal.jar
ZTones-1.7.10-2.2.1.jar

**Comment by DoughnutDev** [comment]
This is already fixed in New versions.

**Comment by BluSunrize** [comment]
Correct
