### ISSUE TITLE
[Crash] Crash when Shift-clicking a chemthrower on a engineer's workbench

### ISSUE THREAD

**Issue by Catomax262** [BluSunrize/ImmersiveEngineering#5501]
### Minecraft Version

1.18

### Immersive Engineering Version

1.18.2-822-154

### How did it happen?

For some reason, when shift-clicking a chemthrower in an engineer's workbench (to fast-place it on the left slot of the workbench)

### Crash Log

https://crashy.net/6W5VGJSiklyToQe4sQIz

**Comment by malte0811** [comment]
There is probably some other mod involved in this. Is the crash reproducible (i.e. does it happen every time)?
> to fast-place it on the left slot of the workbench

That is not an IE feature. Do you know which mod might be adding it?

**Comment by BluSunrize** [comment]
Closing this due to lack of response
