### ISSUE TITLE
Scrolling anywhere past the builders goggles in the creative menu

### ISSUE THREAD

**Issue by Rotary0** [BluSunrize/ImmersiveEngineering#5502]
### Minecraft Version

1.19

### Immersive Engineering Version

ImmersiveEngineering-1.19.2-9.0.0-153.jar

### How did it happen?

Whenever I scroll down past a certain point in the creative inventory menu, which is the bar that has the steel tools and the multimeter, even in the JEI menu my game crashes. I think it may have something to do with rendering the inventory image for a specific item? or maybe a missing texture? "The game crashed whilst rendering item
Error: java.lang.IllegalStateException: null"  is the error. 

### Crash Log

The game crashed whilst rendering item Error: java.lang.IllegalStateException: null - error code: -1

**Comment by CaptainGlac1er** [comment]
I am also having the issue. It appears to be the railgun item.

**Comment by AechPro** [comment]
Bump. I encountered this crash as well. To reproduce just search "@immersive" in JEI and the game will crash before the search is complete. Unsure if there is more than one object in immersive engineering that triggers this error.

**Comment by mindforger** [comment]
Counter-Bump ... neither one of you presented a crashlog yet

**Comment by AechPro** [comment]
https://pastebin.com/em7J28KY

**Comment by mindforger** [comment]
does this happen without optifine ? (a new crashlog without OF would be nice)

**Comment by AechPro** [comment]
The crash does not occur without optifine.

**Comment by malte0811** [comment]
Duplicate of #5492. Fixed for the next build by 9aac40731d732d1e84eac426ecd12e5435b33f5a.
