### ISSUE TITLE
Mod conflict with SophisticatedBackpacks

### ISSUE THREAD

**Issue by DakaraMCE** [BluSunrize/ImmersiveEngineering#5512]
### Minecraft Version

1.19

### Immersive Engineering Version

mmersiveEngineering-1.19.2-9.1.0-156.jar

### Expected Behavior

Using the crafting grid, it should let me craft stuff and keep items in the grid and let me reopen my backpack later.

### Actual Behavior

I placed a latex bucket in the crafting grid in the backpack and when I closed the backpack, it caused me to be unable to open it.

I had to downgrade to the older version of IE for it to work again.  I talked to the modpack author this was the convo:
https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/671

He also included the fix in the thread too. When I downgraded to ImmersiveEngineering-1.19.2-9.0.0-153.jar, it worked again.

### Steps to reproduce

1. Opened backpack
2. Went to the crafting grid attachment
3. placed a latex bucket in the crafting grid
4. closed backpack
5. tried to reopen but couldn't

### Debug Crash Log

13:13:08.032 net.minecraft.network.protocol.PacketUtils Server thread Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemPacket@65cf3409, suppressing error java.lang.NullPointerException: Cannot invoke "blusunrize.immersiveengineering.common.register.IEItems$ItemRegObject.m_5456_()" because the return value of "java.util.Map.get(Object)" is null at TRANSFORMER/immersiveengineering@1.19.2-9.1.0-156/blusunrize.immersiveengineering.common.crafting.ShaderBagRecipe.matches(ShaderBagRecipe.java:45) at TRANSFORMER/immersiveengineering@1.19.2-9.1.0-156/blusunrize.immersiveengineering.common.crafting.ShaderBagRecipe.m_5818_(ShaderBagRecipe.java:26) at TRANSFORMER/fastsuite@4.0.0/shadows.fastsuite.AuxRecipeManager$RecipeNode.matches(AuxRecipeManager.java:190) at TRANSFORMER/fastsuite@4.0.0/shadows.fastsuite.AuxRecipeManager$LinkedRecipeList.findFirstMatch(AuxRecipeManager.java:160) at TRANSFORMER/fastsuite@4.0.0/shadows.fastsuite.AuxRecipeManager.m_44015_(AuxRecipeManager.java:64) at TRANSFORMER/sophisticatedcore@1.19.2-0.5.34.190/net.p3pp3rf1y.sophisticatedcore.upgrades.crafting.CraftingUpgradeContainer.updateCraftingResult(CraftingUpgradeContainer.java:112) at TRANSFORMER/sophisticatedcore@1.19.2-0.5.34.190/net.p3pp3rf1y.sophisticatedcore.upgrades.crafting.CraftingUpgradeContainer.onCraftMatrixChanged(CraftingUpgradeContainer.java:101) at TRANSFORMER/sophisticatedcore@1.19.2-0.5.34.190/net.p3pp3rf1y.sophisticatedcore.upgrades.crafting.CraftingUpgradeContainer.onInit(CraftingUpgradeContainer.java:97) at TRANSFORMER/sophisticatedcore@1.19.2-0.5.34.190/net.p3pp3rf1y.sophisticatedcore.common.gui.StorageContainerMenuBase.addUpgradeSettingsContainers(StorageContainerMenuBase.java:125) at TRANSFORMER/sophisticatedcore@1.19.2-0.5.34.190/net.p3pp3rf1y.sophisticatedcore.common.gui.StorageContainerMenuBase.initSlotsAndContainers(StorageContainerMenuBase.java:111) at TRANSFORMER/sophisticatedcore@1.19.2-0.5.34.190/net.p3pp3rf1y.sophisticatedcore.common.gui.StorageContainerMenuBase.(StorageContainerMenuBase.java:102) at TRANSFORMER/sophisticatedbackpacks@1.19.2-3.18.37.762/net.p3pp3rf1y.sophisticatedbackpacks.common.gui.BackpackContainer.(BackpackContainer.java:36) at TRANSFORMER/sophisticatedbackpacks@1.19.2-3.18.37.762/net.p3pp3rf1y.sophisticatedbackpacks.backpack.BackpackItem.lambda$use$9(BackpackItem.java:287) at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.SimpleMenuProvider.m_7208_(SimpleMenuProvider.java:25) at TRANSFORMER/forge@43.2.1/net.minecraftforge.network.NetworkHooks.openScreen(NetworkHooks.java:201) at TRANSFORMER/sophisticatedbackpacks@1.19.2-3.18.37.762/net.p3pp3rf1y.sophisticatedbackpacks.backpack.BackpackItem.m_7203_(BackpackItem.java:287) at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.item.ItemStack.m_41682_(ItemStack.java:266) at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerPlayerGameMode.m_6261_(ServerPlayerGameMode.java:286) at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.network.ServerGamePacketListenerImpl.m_5760_(ServerGamePacketListenerImpl.java:1089) at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:29) at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.game.ServerboundUseItemPacket.m_5797_(ServerboundUseItemPacket.java:7) at TRANSFORMER/minecraft@1.19.2/net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.TickTask.run(TickTask.java:18) at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763) at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:157) at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746) at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740) at TRANSFORMER/minecraft@1.19.2/net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:726) at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658) at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by P3pp3rF1y** [comment]
The additional information that's important here is that the bucket seems to use custom item rarity.

**Comment by malte0811** [comment]
Already fixed by d9e7aacba15601623649fe84385eba28d0e76161 for the next build.
