### ISSUE TITLE
Metal Press + Extracting Conveyer Belt Bug

### ISSUE THREAD

**Issue by zig13** [BluSunrize/ImmersiveEngineering#5517]
### Minecraft Version

1.18

### Immersive Engineering Version

1.18.2-8.3.0-155

### Expected Behavior

Extracting Conveyer pulls blaze powder from chest and pushes onto the conveyer integrated into the Metal Press. The Blaze Powders stack up until there are four at which point they are stamped into a Blaze Rod.

### Actual Behavior

Extracting Conveyer pulls blaze powder from chest and pushes onto the conveyer integrated into the Metal Press. The Blaze Powders usually then just stay there and the Metal Press usually does not react to their presence. Sometimes one Blaze Rod is successfully made but no more.
Here is a video demonstration: https://youtu.be/7Lhn8VUJ4Sc

### Steps to reproduce

1. Setup Chest->Extracting Conveyer->Metal Press*
2. Put more than four Blaze Powder into the chest
3. Blaze Powder piles up on the Metal Press and isn't processed OR One lot of 4 is processed then no more

Here is a video demonstration:
https://youtu.be/7Lhn8VUJ4Sc

### Debug Crash Log

https://gist.github.com/zig13/42522a95d0e58c51efdb51fe3893e465

**Comment by zig13** [comment]
Same behaviour can also be seen with a hopper over a conveyer belt.
This time I caught it doing the thing where it works once:
https://youtu.be/wCnjOsFd2LY

**Comment by zig13** [comment]
Same behaviour can also be seen with Iron Ingot->Iron Gears.
https://youtu.be/qCSpGSHe5Vk

**Comment by zig13** [comment]
Dropping conveyer also not working to feed the Metal Press:
https://youtu.be/rHo3Qvncpf0
I am out of ideas for how to automate Metal Press recipes that require more than 1 ingredient.

**Comment by TeamSpen210** [comment]
You can use an Item Batcher to collect items and then only send them once the correct amount has accumulated, but the metal press should probably do this for single items?

**Comment by zig13** [comment]
Oh cool - that should solve my problem! Wasn't aware that block existed.
What makes me think it is a bug is that if the player throws a whole load of items onto a conveyer, then it works.
But if they are removed from a container by an extracting conveyer or funnel it doesn't.
It's also strange how sometimes one will get made while the rest stack up.

**Comment by tiphilou17** [comment]
but improved blast furnace not extracting steel and slag, with any chest or conveyor no work too.

**Comment by BluSunrize** [comment]
@tiphilou17 you are commenting something likely entirely unrelated. If you are having problems with IE, please open a new issue and document it properly.

@zig13 I can't reproduce your issue. In your video, the items are not stacking together, which is why the press does not see them as valid inputs.
In my dev environment, they stack just fine after  being dropped onto the press by a dropping conveyor.

The chance is very high that this is a compatability issue with another mod that you have installed. Unless you can reproduce this with just IE installed, there's no investigation to be done here.

**Comment by zig13** [comment]
It was an extracting conveyer that I used.
I haven't tried a dropping conveyer.
But ultimately Item Batcher solves the problem so I am not too bothered.
A combination extractor+batcher would be very useful for feeding a press compactly.

**Comment by BluSunrize** [comment]
You absolutely used a dropping conveyor. I see it in the video above.

My point is, the items should stack and the fact that yours don't has me assume a cross-mod issue.
