### ISSUE TITLE
OptiFine

### ISSUE THREAD

**Issue by Fear59** [BluSunrize/ImmersiveEngineering#5518]
### Minecraft Version

1.19

### Immersive Engineering Version

 ImmersiveEngineering-1.19.2-9.1.0-156

### How did it happen?

when going through the items the game crashes. this is a OptiFine Related crash when removing OptiFine it das not crash 

The game crashed whilst rendering item
Error: java.lang.NoSuchMethodError: 'void com.mojang.blaze3d.vertex.PoseStack.pushTransformation(com.mojang.math.Transformation)'

OptiFine version that im using is ( preview_OptiFine_1.19.2_HD_U_I1_pre4)

[crash-2023-01-02_21.21.37-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/10333239/crash-2023-01-02_21.21.37-client.txt)

### Crash Log

<script src="https://gist.github.com/Fear59/4e7c94809dc2fa02eb1523c58b195b2d.js"></script>

**Comment by malte0811** [comment]
Optifine is not supported, and in this case the crash is purely their fault.

**Comment by Fear59** [comment]
okay I see  thank you for replying and i just have to say this is a great mod and you guys are doing a awesome job.
is there a alternative to use that works like  OptiFine that you can suggest

**Comment by AnasterianSunstrider** [comment]
> okay I see thank you for replying and i just have to say this is a great mod and you guys are doing a awesome job. is there a alternative to use that works like OptiFine that you can suggest

you can try rubidium altough it didnt work for me personally last time ive tried
