### ISSUE TITLE
Missing translation

### ISSUE THREAD

**Issue by Ch1216** [BluSunrize/ImmersiveEngineering#5519]
### Minecraft Version

1.18

### Immersive Engineering Version

8.3.0-155

### Expected Behavior

death.attack.ie.Crushed.player and entity.immersiveenginnering.fluorescent_tube dont appear in game (you need to use a waila like mod to see the second one, gets punched and die in the crusher for the first one)

### Actual Behavior

death.attack.ie.Crushed.player and entity.immersiveenginnering.fluorescent_tube appear in gam

### Steps to reproduce

1. Get punched into a running crusher/Place fluorescent tube
2. Die/See with waila like mod
3. See untranslated message

### Debug Crash Log

https://pastebin.com/CFq0QTTD

**Comment by LiskoSlayer63** [comment]
Also when looking at `Industrial Hemp` with `Jade`, the tooltip shows `tooltip.waila.crop_growthtooltip.waila.crop_mature`. That one seems just have combined two translation keys, but still.

**Comment by BluSunrize** [comment]
Fixed for future 1.19 releases
