### ISSUE TITLE
[Suggestion] ... Modification of the vanilla world for a normal game with Immersive Engineering on the server.

### ISSUE THREAD

**Issue by Nikogrelis** [BluSunrize/ImmersiveEngineering#5520]
Minecraft 1.18.2

At the moment I am developing a military-political Minecraft server with mods in the style of the Victorian era with a map of the real world.
And if the impossibility of digging ores in the ground can still be re-realized, then the lack of veins of ores and oil completely destroys most of the mechanics.
Is it possible to generate new ore veins, or at least install them yourself?

**Comment by BluSunrize** [comment]
I don't understand this question.
Can you try to explain this again?

**Comment by mindforger** [comment]
he want to regenerate or autogenerate new ore veins

**Comment by BluSunrize** [comment]
Mineral veins are created at world creation. Just like ores would be.

You can add additional veins to the world by using the `/ie mineral set` command.
