### ISSUE TITLE
Freezing on server boot up

### ISSUE THREAD

**Issue by Kdaug83** [BluSunrize/ImmersiveEngineering#5521]
### Minecraft Version

1.18

### Immersive Engineering Version

ImmersiveEngineering-1.19.2-9.1.0-156

### How did it happen?

I am running my own little modpack on my server.
Every thing works fine in single player but when I add this to my server it freezes up.
I originally asked if any one might know of known mods that might conflict with Immersive Engineering when running it on a server.
Sadly no one seems to have heard of this issue before.

And since it's a freeze and not a crash i don't a crash log so kinda hard for me to narrow down the issue.
I have 200+ mods in my modpack and Immersive Engineering is the only one i can't get to work.

### Crash Log

Their is no crashlog

**Comment by malte0811** [comment]
Why did you close this? Did you figure out what was causing the freeze? And if so, what was it?

**Comment by Kdaug83** [comment]
I closed it because it was for version 1.19.2 and not 1.18

I did some further work and found that create jetpack mod didn’t work with it and there seems to be more that make it freeze.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
