### ISSUE TITLE
fluorescent_tube render issue in JEI 

### ISSUE THREAD

**Issue by galenecole** [BluSunrize/ImmersiveEngineering#5522]
### Minecraft Version

1.19

### Immersive Engineering Version

9.1.0-156

### How did it happen?

Going around in the JEI Menu:

-- Item being rendered --
(1) Details:
	Item Type: fluorescent_tube
	Item Damage: 0
	Item NBT: null
	Item Foil: false
-- Ingredient being rendered --
(2) 	Mod Name: Immersive Engineering
	Registry Name: immersiveengineering:fluorescent_tube
	Display Name: Fluorescent Tube
	String Name: 1 fluorescent_tube

To reproduce I started by typing "fl" in the search bar of JEI in my inventory and it crashes with the same error, I don't know if this is a JEI problem or something, but it doesn't seem I can prevent the recipe from attempted being loaded. 

### Crash Log

https://gist.github.com/ToSauced/5a16a5b003181c3a0484360a04782b7d

**Comment by mindforger** [comment]
pretty sure this is optifine related, can you test without?

**Comment by galenecole** [comment]
Indeed it is optifine's fault

**Comment by mindforger** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/5518
for reference

**Comment by malte0811** [comment]
Yes, this is purely Optifine's fault.
