### ISSUE TITLE
Issue with shader rendering

### ISSUE THREAD

**Issue by dabluecaboose** [BluSunrize/ImmersiveEngineering#5524]
### Minecraft Version

1.19

### Immersive Engineering Version

1.19.2-9.0.0-153

### Expected Behavior

Shaders should render properly on items

### Actual Behavior

Shaders are rendering either black or with some parts transparent or missing

### Steps to reproduce

1. Build mining drill
2. Add upgrades
3. Add mass fusion or omni-tool shader
4. The attachments are now floating instead of rendering the tubes that attach them to the item.  Alternatively the shader renders black with missing parts, as with the revolver pictured.

![2023-01-10_14 40 22](https://user-images.githubusercontent.com/25807182/211668354-ff0ed8b9-ffb8-42f8-b1a9-9e865d18ad58.png)

![2023-01-10_14 40 37](https://user-images.githubusercontent.com/25807182/211668334-5506bddd-ff74-4af8-98bd-1676369815cd.png)

![2023-01-10_14 40 44](https://user-images.githubusercontent.com/25807182/211668315-7bab6afe-7cb1-498a-b1b8-80df8172573f.png)

![2023-01-10_14 40 51](https://user-images.githubusercontent.com/25807182/211668301-3b59b7dd-7879-454e-95b0-37c131ff5540.png)

![2023-01-10_14 40 22](https://user-images.githubusercontent.com/25807182/211668185-2e165a0e-f7b2-4569-8b9f-3945d173ae8c.png)

### Debug Crash Log

https://pastebin.com/zUcEKZt9

**Comment by BluSunrize** [comment]
Can you reproduce that issue with just IE installed?

**Comment by dabluecaboose** [comment]
Yes, attached are screenshots with all other mods disabled.

![2023-01-24_18 06 27](https://user-images.githubusercontent.com/25807182/214457014-aa0cd79d-8783-41d4-84c8-7ee66ebd0340.png)
![2023-01-24_18 05 18](https://user-images.githubusercontent.com/25807182/214457017-6786b113-f937-40d5-9528-1f0dbc309976.png)
![2023-01-24_18 05 58](https://user-images.githubusercontent.com/25807182/214457018-7b624bbe-b306-4d81-8545-1802f43d45e6.png)
![2023-01-24_18 06 12](https://user-images.githubusercontent.com/25807182/214457021-bb778131-d2f7-4020-8ec6-6824e39479f5.png)

**Comment by BluSunrize** [comment]
Yep, I actually discovered what causes this last night. Fix is in the works ^_^
