### ISSUE TITLE
Error with AE2 Wireless Crafting Terminal

### ISSUE THREAD

**Issue by TomasGnG** [BluSunrize/ImmersiveEngineering#5527]
### Minecraft Version

1.19

### Immersive Engineering Version

1.19.2-9.1.0-156

### Expected Behavior

No errors with rendering.
The wireless terminal should open.

### Actual Behavior

Error with rendering.
The wireless terminal doesn't open

### Steps to reproduce

1. Crafted the Block Placer by Industrial Foregoing
2. Closed the inventory
3. The wireless terminal broke

Playing on ATM8 1.0.8 server.

### Debug Crash Log

https://mclo.gs/bwQGYRW

**Comment by malte0811** [comment]
Already fixed in d9e7aacba15601623649fe84385eba28d0e76161

**Comment by Mitchell5200** [comment]
> Already fixed in [d9e7aac](https://github.com/BluSunrize/ImmersiveEngineering/commit/d9e7aacba15601623649fe84385eba28d0e76161)

looking at that commit for 1.19, that was committed after the current latest 1.19 release (1.19.2-9.1.0-156, on Dec18), any chance we could get a new release soon to address this bug?
