### ISSUE TITLE
Incompatibility with Biomancy (Causes loss of items)

### ISSUE THREAD

**Issue by ArchieBeepBoop** [BluSunrize/ImmersiveEngineering#5528]
### Minecraft Version

1.19.2

### Immersive Engineering Version

9.1.0-156.jar

### Expected Behavior

The ability to put the Sharp Fang item in the crafting grid.

### Actual Behavior

Placing the sharp fang always causes the craft to fail and the items involved to be lost, with a java.lang.NullPointerException that points to IE's blusunrize.immersiveengineering.common.register.IEItems$ItemRegObject method. (Details in the included log, look at line 250)

This can also lead to behaviors such as bricking chests and backpacks among other items that have embedded crafting grids in them, making it so they are unusable.

### Steps to reproduce

1. Run a 1.19.2 modpack with the latest version of Immersive Engineering and Biomancy. For convenience, grab JEI.
2. Spawn Sharp Fangs from Biomancy and try to put them in a crafting grid, following the pattern for an item like the Primordial Cradle for example.
3. Observe as the crafting process crashes.

### Debug Crash Log

https://hastebin.com/quturokelu.yaml

### Notes

Cross referencing this with https://github.com/Elenterius/Biomancy/issues/77

**Comment by malte0811** [comment]
Already fixed in d9e7aacba15601623649fe84385eba28d0e76161

**Comment by Crazybushman** [comment]
> Already fixed in [d9e7aac](https://github.com/BluSunrize/ImmersiveEngineering/commit/d9e7aacba15601623649fe84385eba28d0e76161)

While this issue has been fixed for the 1.19.2 version of the mod, is there any chance that the fix could also be made for 1.18.2, or if not, would you have any reccomendations as to how to approach fixing it for a slightly older version?
