### ISSUE TITLE
Crash when using JEI+Optifine+IE

### ISSUE THREAD

**Issue by Reikona** [BluSunrize/ImmersiveEngineering#5529]
### Minecraft Version

1.19

### Immersive Engineering Version

9.0.0-153

### How did it happen?

Crash when using JEI+Optifine. On a newer version of the mod, the same thing happens. When trying to upload a list of items to the JEI, it immediately fails.

### Crash Log

https://pastebin.com/S8PvycHm

**Comment by malte0811** [comment]
Optifine is not supported, and this particular crash is purely their fault.
