### ISSUE TITLE
Open to Lan Crash from Crafting Fluid Extractor

### ISSUE THREAD

**Issue by KPaXz** [BluSunrize/ImmersiveEngineering#5534]
### Minecraft Version

1.19

### Immersive Engineering Version

ImmersiveEngineering-1.19.2-9.1.0-156

### How did it happen?

been playing on a open to lan world for about a week now, decided it was time to create a fluid extractor for extracting latex in logs. the world is hosted from my computer and a local account joined while i was afk, they created a fluid extractor and after a few moments the server crashed with this in the crash reports

### Crash Log

https://gist.github.com/KPaXz/c1f491f8346abe6d27ade057be131e54

**Comment by malte0811** [comment]
Already fixed by d9e7aacba15601623649fe84385eba28d0e76161
