### ISSUE TITLE
Add Pride Shaders 

### ISSUE THREAD

**Issue by Holli-Git** [BluSunrize/ImmersiveEngineering#5535]
### Explain your idea

1. More shader variety, and collecting all of the pride shaders could be a neat challenge (if multiple are added). Also adds pride flags to the game via banners.
2. IE is kinda gay ngl. 
3. Pride flags all look very cool.
4. Probably? I have never made shaders so I do not know.

**Comment by ghost** [comment]
Please, don't do that. You really don't need to bring your sexuality into Minecraft. There are already so many mods with very visible pride stuff, it really doesn't need any more.
I'm not saying there's anything wrong with it, I'm just saying not everyone wants to see pride stuff everywhere, especially not in Minecraft, or in a mod for it. You can already make rainbow banners or build flags, if you want. Don't you think that's enough?

**Comment by BluSunrize** [comment]
Ah here's the fun thing. The fact that you don't want me to add it makes me want to add it **more**.

And it's not just sexuality, it's gender too! I'm definitely doing it now, because it'll piss off a bunch of tories :D

**Comment by Holli-Git** [comment]
How to avoid the pride shaders:
Don't use em. Easy as that

**Comment by ghost** [comment]
It's just annoying to see it in your face everywhere you go, even in Minecraft. In items shown in JEI, in menus, etc. I'm not talking about a credits page with some pride-related visual touches, that's perfectly fine. But when an entire menu has a pride flag as a background, or an item just has the texture of one, it just looks out of place.
And I'm not talking about it in singleplayer necessarily, I mean other people using them on multiplayer for example, sometimes even just to be annoying.

**Comment by Arctaisia** [comment]
Noone uses it to be annoying unless they're transphobic/homophobic/etc., people use them to display their identity and give others of these persecuted groups courage and hope.

 If you're sad about one of the most queer devteams I've seen in minecraft adding a lil bit of color and representation, maybe you should watch less PragerU and go meet some of these people,,, They're human too, y'know

**Comment by ghost** [comment]
Well, first off, I fully agree with you that people to use them to display their identity and give others hope as you said, when used like that it's great, especially if it's done tastefully and doesn't look out of place. What I meant by people using them to be annoying isn't only people who are transphobic/homophobic, there's also plenty of queer people I have met who are really pushy about their beliefs, and if others don't agree with them, they get really annoyed and start pushing pride-related stuff in their face everywhere they go, so maybe I've just met some of worse people. Also, I have no idea who PragerU is and I know basically nothing about the devteam of IE, so I apologise.

**Comment by Holli-Git** [comment]
> Well, first off, I fully agree with you that people to use them to display their identity and give others hope as you said, when used like that it's great, especially if it's done tastefully and doesn't look out of place. What I meant by people using them to be annoying isn't only people who are transphobic/homophobic, there's also plenty of queer people I have met who are really pushy about their beliefs, and if others don't agree with them, they get really annoyed and start pushing pride-related stuff in their face everywhere they go, so maybe I've just met some of worse people. Also, I have no idea who PragerU is and I know basically nothing about the devteam of IE, so I apologise.

The thing this being LGBT isn't some belief, it's fact. If someone's spreading false information about the earth being flat and people correct them, that's not "globists forcing their beliefs on people" that's people correcting others.

**Comment by Holli-Git** [comment]
> GamingGuy1999

If seeing a few small items in JEI from time to time counts as "in your face" I think you're just overreacting

**Comment by Arctaisia** [comment]
> > GamingGuy1999
> 
> If seeing a few small items in JEI from time to time counts as "in your face" I think you're just overreacting 

this tbh

**Comment by BluSunrize** [comment]
If you find the inclusion of pride shaders to be pushing some kind of agenda, then frankly...stop playing this mod, lmfao.
I have no tolerance for queerphobes in the community.

Discussion locked.
