### ISSUE TITLE
Incompatibility with Quark 3.4-386

### ISSUE THREAD

**Issue by Gronglegrowth** [BluSunrize/ImmersiveEngineering#5536]
### Minecraft Version

1.19

### Immersive Engineering Version

9.1.0-156

### Expected Behavior

If I craft an engineer's hammer with raw iron ore, I should get IE iron grit regardless of whether Quark is present. Likewise for every dust type.

### Actual Behavior

When I craft an engineer's hammer with raw iron ore (or any other), I receive a minecraft barrier renamed to "Empty tag: forge:dusts/iron" (or other tag for the dust I wish to craft). However, the tag isn't actually empty. Somehow Quark is breaking these recipe outputs

### Steps to reproduce

1. Install IE and Quark
2. Attempt to craft a metal dust
3. Receive an empty tag barrier instead

### Debug Crash Log

https://mclo.gs/1FfQAa9

**Comment by Gronglegrowth** [comment]
Additional clarification: This happens only if Quark's datapack is loaded *before* IE's, so there is a way to manually fix it by reordering the packs in a world

**Comment by malte0811** [comment]
This is on Quark's end, they query recipe outputs too early (before tags are available):
![](https://cdn.discordapp.com/attachments/824375091939901453/1065912327251177533/image.png)
