### ISSUE TITLE
[1.18.2] Right click on the sawmill causes the player to take damage

### ISSUE THREAD

**Issue by Zahkriiven** [BluSunrize/ImmersiveEngineering#5537]
### Minecraft Version

1.18

### Immersive Engineering Version

8.3.0-155

### Expected Behavior

Don't take damage.
When sneak + right clicking on the saw blade it is extracted from the sawmill into my hand.

### Actual Behavior

Right clicking anywhere on the sawmill multiblock causes the player to take damage

### Steps to reproduce

1. Form the sawmill multiblock
2. Give it a saw blade and power
3. Right click anywhere

### Debug Crash Log

https://pastebin.com/arYArCdc

**Comment by malte0811** [comment]
That seems to be one of the changes from #5486, you need to disable the sawmill with redstone before removing the blade. While it makes sense (grabbing that spinning blade would hurt), it feels a bit weird for IE and I'm not sure why it was in the sound PR. I didn't pay much attention to those PRs, it definitely needs to be documented in the manual.

**Comment by Zahkriiven** [comment]
That make sense, though could it be possible that it needs to right click on the block the blade is on? Or once it is a multiblock everywhere behaves the same? Placing a block against the sawmill damages the player for example. Even if I'm not trying to get the blade out.

**Comment by voidsong-dragonfly** [comment]
Intentional for the sawblade block only. I'll deal with this, as this is my mess-up.
The reason it was in the sound PR was along with the lock to make sure, back when spin-up/spin-down sounds were implemented, I only needed to do that on redstone, instead of on blade interact.

**Comment by BluSunrize** [comment]
Partially fixed by Silf's PR. Behavior is less accidental and documented in the manual now.

Closing this.
