### ISSUE TITLE
Immersive Engineering breaking drops from certain modded entities

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#5538]
### Minecraft Version

1.18

### Immersive Engineering Version

8.3.0-155

### Expected Behavior

When you kill a boss from L_Ender's Cataclysm, it should drop it's specified drops as well as a shader grabbag from Immersive Engineering.

### Actual Behavior

When you kill a boss from L_Ender's Cataclysm, it only drops a shader grabbag from IE instead of dropping it's loot as well as a grabbag. This might be an issue with Cataclysm, not IE; if that is the case, then I apologize for wasting your time, feel free to close this issue. I am simply reporting it here in case it is caused by IE and it could be breaking drops from entities from other mods as well.

### Steps to reproduce

1. Kill a boss from L_Ender's Cataclysm (I'm using 0.51-hotfix)
2. After it plays it's death animation, it only drops a shader grabbag, instead of dropping any loot, including the unique weapon that it drops, which is supposed to drop from a few blocks up and have the glowing effect until you pick it up. I did test this with all of my other mods except for IE activated, and the loot dropped correctly with IE disabled.

### Debug Crash Log

It wasn't a crash.

**Comment by BluSunrize** [comment]
Hrm. I'm unaware of any reason we should be affecting this. We *add* to the drops, we don't replace them.

You can however try to use the tag that we add for blacklisting entities. If you make a datapack and add those bosses to the tag `immersiveengineering:shaderbag/blacklist`, that should be a test and potential fix.

**Comment by ghost** [comment]
Update: I am now even more confused. I also tested Mowzies Mobs bosses such as Barako and the Frostmaw, and they only dropped shader grabbags as well. After iterating upon my modpack a couple times (adding and removing some minor mods) and testing Cataclysm and Mowzies Mobs bosses again, all bosses seem to drop their normal drops as well as shader grabbags... None of the mods I removed/added should have messed with drops of mobs from any other mod. They were all mods that just added decoration blocks and some other light stuff, they definitely weren't game-changing.
Well, either way, thanks for the suggestion, it seems to have been caused by some other mod... somehow... It seems to be all fixed now!
