### ISSUE TITLE
[Bug] Item Batcher buffer and filter appear to be switched. Item dupe possible by setting filter and breaking Item Batcher.

### ISSUE THREAD

**Issue by QuickBASIC** [BluSunrize/ImmersiveEngineering#5539]
### Minecraft Version

1.19

### Immersive Engineering Version

9.1.0-156

### Expected Behavior

Filters should be set on the top slot labeled "Filter" in the GUI interface and items that are inserted into the machine and being buffered until they meet the filter criteria should be inserted into the bottom slots labeled "Buffer" in the GUI interface. Breaking the machine should drop the Item Batcher and any items in the buffer slots.

### Actual Behavior

Filters can be set on the top slot labeled "Filter" in the GUI interface  but items are not inserted into the machine and being buffered.

Inserting items into the bottom slots labeled "Buffer" causes the machine to accept input as if those slots were a filter. Items appear to be inserted into and extracted from the top slots labeled "Filter".

Breaking the machine drops the Item Batcher and  items that are set in the filter. The items in the slots labeled "Buffer" do not drop.

 [Related Discord conversation](https://discord.com/channels/270295681829306369/339127815666532352/1066764448917880934)

Video Repro:
https://youtu.be/6PLzCBE1Tr0
https://youtu.be/zc5BeQcicTo

*NOTE: Sorry for the method of capture. My teenage son "borrowed" my capture card and OBS is fickle on SteamDeck.*

EDIT: [Test world created using PrismLauncher v6.1](https://drive.google.com/file/d/1tZTY9syGme659jjzOv4-S4R_aeoVPGnd/view?usp=share_link)

### Steps to reproduce

Behavior 1:

1. Create a new test word in an instance of Minecraft with only Immersive Engineering installed.
2. Place Item Batcher in World with appropriate conveyors routing to and from it and insert filter items in top slots. *Filter does not appear to work*
3.  Instead, insert filter items in bottom slots labeled "Buffer". *Filter appears to work*.

Behavior 2: 

1. Create a new test word in an instance of Minecraft with only Immersive Engineering installed.
2. Place Item Batcher in world. Set filter using item from inventory or JEI (not used in this test)
3. Break Item Batcher with appropriate tool. *Item Batcher and items set to filter drop.*

### Debug Crash Log

https://mclo.gs/QnMJCS7

**Comment by BluSunrize** [comment]
Not reproducble in 1.18.2 as far as I can tell.
Will do more testing when I'm working on 1.19

**Comment by malte0811** [comment]
Fixed in c34270b8196b93fc928800b0fca6946442b84524
