### ISSUE TITLE
[Suggestion] Custom tiers with craft tweaker

### ISSUE THREAD

**Issue by 2002354** [BluSunrize/ImmersiveEngineering#5540]
### Explain your idea

Expose an api so modpack creators can create custom tiers either with a mod api or with craft tweaker.

**Comment by voidsong-dragonfly** [comment]
I am baffled as to what you mean by this. Custom tiers? Why does the current API not suffice for that? What kind of tiers? Why should they exist? You'll need to explain more before this item is actually resolvable.

**Comment by mindforger** [comment]
i suspect he means something like the sevtech: ages mod, where you need to progress to be able to build certain things and change recipes and item drops depending on what age you are in

**Comment by 2002354** [comment]
By tiers, I am talking about LV, MV and HV (the default tiers). I would like to create a custom tier (like UHV) either through a mod or crafttweaker.

**Comment by BluSunrize** [comment]
No.
