### ISSUE TITLE
Crashing in JEI

### ISSUE THREAD

**Issue by DJEscHGL** [BluSunrize/ImmersiveEngineering#5541]
### Minecraft Version

1.19

### Immersive Engineering Version

9.1.0-156

### How did it happen?

When opening inventory and searching or scrolling to mod page the game crashes. 

### Crash Log

https://gist.github.com/DJEscHGL/dd10b560cbe16715601d059af32ddce9

**Comment by malte0811** [comment]
This is a known issue with Optifine, and on their end to fix.
