### ISSUE TITLE
Tons of lag when a blueprint is in the Engineer's Workbench

### ISSUE THREAD

**Issue by Benny-Boo** [BluSunrize/ImmersiveEngineering#5545]
### Minecraft Version

1.18

### Immersive Engineering Version

ImmersiveEngineering-1.18.2-8.3.0-155

### Expected Behavior

I'd expect to not go down to 6fps when I put a blueprint in the workbench

### Actual Behavior

When I add a blueprint (Crafting Components) to the workbench, I got from ~30fps to 6fps. I'm in a modpack called Crazy Factory (https://www.curseforge.com/minecraft/modpacks/crazy-factory), and they do add custom items from KubeJS to the blueprint. I'm not sure if it would contribute but I do have Rubidium installed

### Steps to reproduce

1. Put blueprint in engineer's workbench
2. ???
3. 6fps
![image](https://user-images.githubusercontent.com/24782877/214785077-ce4d94d6-af23-4e7c-b514-0c4527dbe06f.png)

### Debug Crash Log

It didn't generate it :shrug:

**Comment by BluSunrize** [comment]
Holding down F3+C for 10 seconds will absolutely generate a crash log. So go find that and provide it please.

**Comment by Benny-Boo** [comment]
When I crash the game just stops responding and I have to close it through task manager, I'd assume that's why it didn't generate a crash log properly
