### ISSUE TITLE
Uranium Block Unobtainable - Add uranium ingot to forge:ingots/uranium tag

### ISSUE THREAD

**Issue by Christofmeg** [BluSunrize/ImmersiveEngineering#5546]
### Minecraft Version

1.19

### Immersive Engineering Version

9.1.0-156

### Expected Behavior

Block of Uranium being craftable.
Uranium Ingot being added to forge:ingots/uranium

![image](https://user-images.githubusercontent.com/4357405/214929353-1e2f7208-eb2c-4e55-8b4c-dd8ca11af661.png)

### Actual Behavior

Block of Uranium uses 8 forge:ingots/uranium and 1 Uranium Ingot, but the tag is empty.

immersiveengineering:ingot_uranium has not been added to forge:ingots/uranium

### Steps to reproduce

Install Immersive Engineering 1.19.2 9.1.0-156 

### Debug Crash Log

https://bytebin.lucko.me/dMpsb3Qrsr

**Comment by BluSunrize** [comment]
We *do* add ingots to that tag. It works perfectly fine in my 1.19.2 test word:

![grafik](https://user-images.githubusercontent.com/4106382/215050404-9ffc378f-63a5-4b51-8ec4-0cd8a399588e.png)

Something in your modlist is breaking it. You will need to figure out the conflict.

**Comment by Christofmeg** [comment]
Found the perpetrator, was a mod trying an item that didn't exist to forge:ingots/uranium
