### ISSUE TITLE
Potential ideas for accumulator backpack upgrades?

### ISSUE THREAD

**Issue by Arctaisia** [BluSunrize/ImmersiveEngineering#5547]
### Explain your idea

I've come along with a handful of ideas for upgrades to the accumulator backpack, if possible! I'm unsure on it's feasibility, but it's an idea none the less!

I have a few upgrades in mind! 
 >- Sulfur-ion accumulators! Just some additional FE/RF storage space, maybe multiple can be added to a backpack in one slot, like augers, or multiple slots. Using some kind of accumulator, some sulfur, and other blocks or items for crafting, mostly came up with it for another use for sulfur, other than gunpowder. Unsure if this is too futuristic rather than retro-futuristic, though!
>- Portable Tesla coil? Something perhaps activated with a hotkey, discharging energy to damage all mobs (and the player, if they have no faraday armour) in a small radius, smaller than the existing tesla coil ranges! Unsure of how possible or easy this'd be. Plus, seeing a massive tesla coil on some nerd's back would be cool!
>- Storage slots! Just some simple storage, accessed via hotkey or right clicking with the item!
>-Banners! An odd one, but perhaps we could add banners to give the backpacks some flair with a hanging flag? Either on a pole to the side, or from the bottom, etc! Then we can fly those super pretty pride banners everywhere we go :3 
>- Fluid storage? A little on the odd side, but perhaps it could fill items in the user's inventory in it's filter with a stored fluid, at the cost of sone RF each time. 

As for implementation viability, I have a feeling it could be a little hard, given it's differences to a normal upgradable tool. Though the main plan was mostly to give the backpack some additional, fancy uses to keep it a little fresher throughout playthroughs, while offering some extra customisation!

Hope this'll at least get some ideas flowing, even if it doesn't quite fit/isn't that feasible! Thank you for coming to my ted talk,,,

**Comment by voidsong-dragonfly** [comment]
Maybe have the 'central head item' (like the drillhead for the drill) be the accumulator? So it's a frame where you can swap out accumulators for greater storage.

**Comment by Arctaisia** [comment]
Oh that's a good idea!! I wonder how that'd play with the sulfur-ion accumulators though

**Comment by voidsong-dragonfly** [comment]
Likely it'd remove the need. Another upgrade I'd suggest is to be able to upgrade the transfer rate to MV: 1024IF/t for some MV wires and connectors.

**Comment by BluSunrize** [comment]
Closing this, since there is upgrades for the pack now =)
