### ISSUE TITLE
Crash: java.lang.AbstractMethodError: blusunrize.immersiveengineering.client.models.ModelIEObj.getBlockIcon(Ljava/lang/String;)Lnet/minecraft/util/IIcon;

### ISSUE THREAD

**Issue by BBoldt** [BluSunrize/ImmersiveEngineering#555]
https://gist.github.com/d29e99f337c4cfd42f0f

* ImmersiveEngineering-0.6.0
* Forge 1492

Full modlist: https://gist.github.com/f56db34443ab577a121d

**Comment by cobra** [comment]
Try removing any IE addons, they are probably broken at the moment. Take care when opening old worlds, you will lose their items and blocks (forge will warn you about that).

**Comment by cobra** [comment]
I can confirm that Immersive Integration 0.5.4 is causing this crash.

**Comment by BBoldt** [comment]
Oh.

I should have suspected those first really.
