### ISSUE TITLE
Buzzsaw: whenever i search for this item in jei Minecraft will crash

### ISSUE THREAD

**Issue by Vinionss** [BluSunrize/ImmersiveEngineering#5551]
### Minecraft Version

1.19

### Immersive Engineering Version

156

### How did it happen?

Buzzsaw: whenever i search for this item in jei Minecraft will crash

### Crash Log

[crash-2023-01-31_03.51.23-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/10566217/crash-2023-01-31_03.51.23-client.txt)

**Comment by malte0811** [comment]
This is a known issue with Optifine, and has to be fixed on their end.
