### ISSUE TITLE
Garden Cloche does not alow output

### ISSUE THREAD

**Issue by IC-SubiX** [BluSunrize/ImmersiveEngineering#5552]
### Minecraft Version

1.18

### Immersive Engineering Version

1.18.2-8.3.1-157

### Expected Behavior

The output should be able to get extracetd with blocks: Hopper, Improter(AE2/RS), Belts(IE), Funnels(Create)...

### Actual Behavior

There is no way to extract any Items.

### Steps to reproduce

Set up a Garden Cloche. (water, power, soil, plant)
Try to extract the Output.

### Debug Crash Log

https://pastebin.com/JayvBniy

**Comment by BluSunrize** [comment]
Can you provide some pictures of your setup please?

**Comment by IC-SubiX** [comment]
Edit: I now noticed my bug report was poorly worded, im sorry for the confusion!

What i meant is: 
You can't output from the lowest block (of the 3 block high Hitbox).
I dont expect the Garden Cloche try to push the items into an attached inventory, but i expected to be able to extract from the base. (since it also has orange dots on the side (=export))


![2023-02-02_19 50 36](https://user-images.githubusercontent.com/49319663/216423240-dda0b629-7ecf-48c8-ae19-4806b4bcb078.png)

**Comment by BluSunrize** [comment]
No, the output is on the glass. =p

**Comment by IC-SubiX** [comment]
So it is intended the base can only accept water/fertilizer? If so, would you consider add extraction cabability for the seeds/soil/products from the base?

**Comment by BluSunrize** [comment]
Well seed and soil can't (and shouldn't be) extracted anyway. You place those in manually.

And no, I don't really see a reason to do so, since the current setup makes the cloche very easy and clean to automate with conveyors, while also looking quite nice =)
