### ISSUE TITLE
Steel block 

### ISSUE THREAD

**Issue by Shmeade69** [BluSunrize/ImmersiveEngineering#5553]
### Minecraft Version

1.19

### Immersive Engineering Version

1.19.2-9.1.2-159

### Expected Behavior

Using all the mods 8 version 1.0.10 trying to build arc furnace. 

### Actual Behavior

Block of steel has been replaced with steel block by alltheores mod. Arc furnace will not build with this block.

### Steps to reproduce

Built with instructions according to manual
Contacted all the mods 8 about the substitution problem
Tried the substitution of using steel block instead of block of steel
Machine will not build

### Debug Crash Log

<script src="https://gist.github.com/Shmeade69/82d041c5682b5b1e7bd85b47c6b522dc.js"></script>

**Comment by BluSunrize** [comment]
*shrug*

Stop trying to replace blocks. Not my fault when the pack fucks it up.

**Comment by malte0811** [comment]
To elaborate on that a bit: Replacing steel blocks with steel blocks from other mods *is* supported. However, it works perfectly fine with just IE and AllTheOres. So it's either a mod interaction or one of the KJS scripts of ATM8 breaking things. If it's a mod interaction, we'll look into it once we have a reasonably small set of mods to look at, not all of ATM8. If it's one of the scripts, it's most likely on the ATM8 team to fix this.
