### ISSUE TITLE
Item Sorter And Dedicated Server

### ISSUE THREAD

**Issue by Proxwian** [BluSunrize/ImmersiveEngineering#5554]
### Minecraft Version

1.18

### Immersive Engineering Version

ImmersiveEngineering-1.18.2-8.3.1-157

### Expected Behavior

Item sorter works as expected on Dedicated server

### Actual Behavior

Item Sorter destroying items, does not output anything

### Steps to reproduce

1. Install mod on Dedicated server
2. Put Item Sorter
3. Put some conveyors in and from Sorter
4. Put items on conveyors
5. Items disappears inside Sorter

### Debug Crash Log

-

**Comment by BluSunrize** [comment]
Please provide a debug crash of your instance.

**Comment by Proxwian** [comment]
There’s no crash or debug, item just disappears

**Comment by BluSunrize** [comment]
Which is why I have asked for a debug crash.
The issue template on this website specifically instructs you to create one by holding down F3 and C for 10 seconds.
So go do that, upload the log to gist and link it here.

**Comment by Proxwian** [comment]
[crash-2023-02-09_16.19.13-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/10695485/crash-2023-02-09_16.19.13-client.txt)

**Comment by BluSunrize** [comment]
That mod list is massive. Please try to reproduce this issue with just IE installed.

**Comment by Proxwian** [comment]
Looks like issue with Adaptive Perfomance Tweaks. Removing it soolves the problem. Sorry for inconvenience.
