### ISSUE TITLE
Undergarden forgotten metal causing null pointer crash when crafting

### ISSUE THREAD

**Issue by MiriamAlter** [BluSunrize/ImmersiveEngineering#5566]
### Minecraft Version

1.19

### Immersive Engineering Version

9.1.0-156

### Expected Behavior

The Undergarden mod's forgotten guardian minibosses drop forgotten nuggets, which can be crafted into ingots and blocks of forgotten metal using any vanilla or modded crafting methods. When Immersive Engineering is installed, these minibosses also drop epic shader grabbags, which otherwise have no effect on forgotten metal.

### Actual Behavior

Attempting to craft a forgotten ingot out of nuggets using a vanilla crafting table, either by using JEI or placing them manually, results in them teleporting back into the player's inventory instead.
Attempting to use a modded crafting or compacting method (I tried both AE2's crafting terminal and Functional Storage's compacting drawers) causes a client-side crash. The crash report shows IE as the immediate cause, with a null variable related to shader grabbags.
This occurred in the TNP Limitless 6 modpack.

### Steps to reproduce

1. Install IE, AE2, and Undergarden. Other mods can be included as well.
2. Establish an AE2 storage system with at least one disk and a crafting terminal.
3. Obtain at least 9 forgotten nuggets by killing one or more forgotten guardians.
4. Use the crafting terminal to craft a forgotten ingot out of 9 forgotten nuggets.

### Debug Crash Log

https://pastebin.com/QcH3WMNZ

**Comment by malte0811** [comment]
Update IE, this has been fixed in build 158. You should use 159 instead though, 158 breaks villagers.
