### ISSUE TITLE
The game closes when going to the IE section in inventory.

### ISSUE THREAD

**Issue by Donhappy** [BluSunrize/ImmersiveEngineering#5567]
### Minecraft Version

1.19

### Immersive Engineering Version

9.1.2

### How did it happen?

The game starts correctly, the world starts correctly, but when I go to the section where the IE mod is located in jei the game crashes, the same thing happens when I go to the IE section in creative, the game closes.
I left my crash log here:

### Crash Log

https://pastebin.com/kEUAm0WN

**Comment by beeginey** [comment]
Same issue here. Only on certain pages of the menu, I think it's just the 2nd page for me.

**Comment by malte0811** [comment]
This is a bug in Optifine.
