### ISSUE TITLE
[1.19.2] External heater broken

### ISSUE THREAD

**Issue by starskyC** [BluSunrize/ImmersiveEngineering#5569]
### Minecraft Version

1.19

### Immersive Engineering Version

1.19.2-9.1.2-159

### Expected Behavior

Given energy, the external heater should provide heat for adjacent furnace.

### Actual Behavior

The external heater is not working properly. It doesn't detect the vanilla furnace adjacent to it, and I tried every single face still not working. I even tried giving it a redstone signal and still not right
![e98fc2a613e882346b6e95e4db136a0](https://user-images.githubusercontent.com/72022037/217989233-b773e66b-e212-4878-9d67-99eb5272f62c.png)

![173de9e4f3143c5f23b11a517777c21](https://user-images.githubusercontent.com/72022037/217989940-f9874cc2-9d17-4fc6-8323-e21738d03b84.png)

I even tried putting different "burnable" items into the furnace. The heater just won't start working.

### Steps to reproduce

1. Create a new worl in Creative mode
2. Grab the heater, furnace, and battery out of inventory. place the furnace adjacent to the heater
3. Use hammer and coils stuff to connect the battery and heater, make sure the heater is charged correctly.
4. Give the furnace something to burn.

### Debug Crash Log

https://pastebin.com/5sH2kSfE

**Comment by BluSunrize** [comment]
Works perfectly fine on my end:

![grafik](https://user-images.githubusercontent.com/4106382/218066686-20ac54e6-218e-49ad-8e0a-91d3153ae549.png)
![grafik](https://user-images.githubusercontent.com/4106382/218066774-b6748cae-1348-4cc2-8564-8af5f16a8de8.png)

It's possible that you are dealing with a cross-mod conflict. Please try testing with just IE installed to confirm that the issue persists.

**Comment by starskyC** [comment]
Yet another bug with optifine :(
The version I used is l1 with forge 43.1.52. Every other mods in my list are fine.
Maybe IE just don't work well with OF like many other tech mods? Or is it compatible with lower version of OF?

**Comment by BluSunrize** [comment]
Optifine is *a terrible piece of code*. Stop using it.
If you must use some "performance optimizer", use Rubidium. That breaks a lot less than Optifine does.
