### ISSUE TITLE
Problem with the in-game documentation

### ISSUE THREAD

**Issue by 1skandar** [BluSunrize/ImmersiveEngineering#557]
This is easiest shown over describing:
![2015-11-01_19 56 16](https://cloud.githubusercontent.com/assets/4127779/10872570/ca15c462-80d2-11e5-9b28-877330951dae.png)
![2015-11-01_19 56 20](https://cloud.githubusercontent.com/assets/4127779/10872571/ca20085a-80d2-11e5-9a90-87ce1df60687.png)

Apparently opening the book resets the GUI to normal scale until you close the book again.

**Comment by cobra** [comment]
that's the fix for #487. Well. Back to square one then.

**Comment by 1skandar** [comment]
Yeah, may I suggest having a button there to toggle the size?

**Comment by BluSunrize** [comment]
Yeah that is kinda intentional, and no, I don't see a point for the button. Especially since it sets the scale back to your configured one as soon as you close the book =P

**Comment by 1skandar** [comment]
The point of the button would be for people, like me, who don't need nor want the fix can turn it off so it doesn't reset their large scale gui to normal and make the book tiny and hard to read on a 17" 1440p monitor.
