### ISSUE TITLE
Creative Tab Crash

### ISSUE THREAD

**Issue by DigitalRavenVII** [BluSunrize/ImmersiveEngineering#5572]
### Minecraft Version

1.19

### Immersive Engineering Version

ImmersiveEngineering-1.19.2-9.1.2-159

### How did it happen?

Playing in creative, when switching to immersive engineering tab, and scrolling down a past the zinc ore, the game crashes. I also crash when typing 'sc' in either JEI or the search section of the creative menu. Removed JEI, still crash. 

### Crash Log

https://gist.github.com/DigitalRavenVII/9da9d3a7635a159d0fd5d3e536906f7b

**Comment by DigitalRavenVII** [comment]
Issue resolved after removing optifine. Looks like a compatatibility problem.

**Comment by malte0811** [comment]
Yes, this is a known bug in Optifine. We can't do anything about it.
