### ISSUE TITLE
Some rendering issues with shaders [Rubidium]

### ISSUE THREAD

**Issue by Shibva** [BluSunrize/ImmersiveEngineering#5573]
### Minecraft Version

1.18

### Immersive Engineering Version

ImmersiveEngineering-1.18.2-8.3.1-157.jar

### Expected Behavior

IM aware after looking though that other shader mods are not supported but Rubidium is more of a render optimization than a shader mod (that would be oculus that adds shaders). When applying a shader on some items they render as gray

### Actual Behavior

as mentioned above they render as grey and they should all be doing that: HOWEVER, things like the revolver, drill, buzzsaw, and ballons and banners  do work and show up as they should while the only ones that don't work (Afaik) are Chemthrower, Shield, minecart?, and railgun

while this is not bound to be fixed depending on how this goes it's a bit odd that it does work for some and not the others

List of Renders that work when shaders are applied: Drill, Buzzsaw, Revolver, banners, Balloon
                       Those that don't (af as I have found): Railgun, Shield, Chemthrower
                       
In this image you see the greying out of one of the items with Rubidium:
![image](https://user-images.githubusercontent.com/38770780/218289907-687bad8b-dfc7-4f83-b8f6-f06ef6f7639e.png)
(Note: it seems that some of the rendering does show up still)

However, in the same instance with no changes made, the shaders on the drill work just fine:
![image](https://user-images.githubusercontent.com/38770780/218289869-5ad1b042-5106-4bb7-85c4-60589d0d0c5a.png)

The same with the Buzzsaw (z-fighting is not shown in this shot but it shows that the shader is working)
![image](https://user-images.githubusercontent.com/38770780/218289902-03e9c5a3-5510-4212-9d50-731097ecf299.png)

### Steps to reproduce

1. install just Rubiudium
2. should be self-explanatory (apply shaders to the various items that can have them applied)
3. notice that while some of them don't work that some of the others do work (Ie, drill, revolver, buzzsaw)

List o

### Debug Crash Log

https://gist.github.com/Shibva/0c0b4175f46f496937f62dbef1bb9071

**Comment by BluSunrize** [comment]
Rubidium, much like Optifine, is not supported.

**Comment by Shibva** [comment]
im usure why this is the case though. is there a reason why its working on some and don't all

More so curious

**Comment by BluSunrize** [comment]
Yeah there's probably a reason. I don't know it and I don't care to investigate.

**Comment by Shibva** [comment]
yeah. Though If I have to take a wild guess something between the broken renders and the ones that work may be coded differently or have something altered between how each of their models were added

if anyone would want to try and fix this id recommend starting there to look for any differences.

I don't know anything about coding mods but I may take a look into this to see if I can find anything standing out


@BluSunrize all I ask is for links to whatever handles the special rendering of a shield and Drill or revolver along with anything todo with rendering shaders on models. IK its unlikely but I might find something and then in turn to try and fix it

**Comment by Shibva** [comment]
the bright side is that while its somewhat broken that part of them are working so I wont be going in blind lel

**Comment by Vaelzan** [comment]
FYI - the bug you're encountering is an issue in Rubidium. The same thing happens in other mods such as the Blackboards from Supplementaries (which lose their colour when Rubidium is installed). It's something that the Rubidium dev needs to fix on their end, and should be reported to them.

**Comment by Shibva** [comment]
well someome beat me to the punch

thankyou @malte0811, kind stranger
and thank you @Vaelzan for saying that

I tip my hat to za

**Comment by Shibva** [comment]
@BluSunrize GOOD NEWS!

The fix was applied in-dev. this issue has been patched and it seems to have fixed some other mods performance with Rubidium in the process.

@malte0811 thanks again man 👍

**Comment by jpeaglesandkatz** [comment]
> Yeah there's probably a reason. I don't know it and I don't care to investigate.

Looking at your comments you don't seem to care about a lot of things... I would personally like that my mod works. And since a huge number of people these days are actually using their GPU for minecraft instead of just vanilla (because you know, might come as a surprise to you, hardware has evolved), it would be nice if mods would actually work as intened with a render that more than half the players use.
