### ISSUE TITLE
Transformer burning wires

### ISSUE THREAD

**Issue by WillDTN** [BluSunrize/ImmersiveEngineering#5574]
### Minecraft Version

1.19

### Immersive Engineering Version

1.19.2-9.1.2-159

### Expected Behavior

![image](https://user-images.githubusercontent.com/82644880/218293930-bb8dd10a-52f0-4c39-af4d-7cbd339a7ad4.png)

Insulated LV wire connected to 8 devices(garden cloches in this example), drawing the max a single wire can handle but not above, wire connected to relay and transformer shouldn't burn and power should flow to the devices.

### Actual Behavior

Wire connecting LV relay to HV transformer burns instantly with a 256 flux being transfered to each device. This also occurs with a MV circuit in place of the LV or id you replace the HV transformer with a MV transformer and replace HC circuit with MV.

### Steps to reproduce

1) Creative Accumulator(or other power sources)
2) Connect 4 HV Connectors to Creative Accumulator
3) Wire HV Connectors to HV Relay
4) Wire HV Relay to Redstone Breaker
5) Wire Redstone Breaker to HV Transformer
6) Place 8 LV Connectors on 8 Garden Cloches
7) Wire LV to LV Relay with LV Insulated Wire Coils
8) Wire LV Relay to HV transformer
9)Cry as the wire burns

This happens on Multiplayer Server, LAN and Singleplayer worlds.
I am running about 50 additional mods listed in the pastebin below, none were listed in the contributing guidelines and to my knowledge don't modify with IE but i am welcome to be told off if i did a bad.
Mods List - https://pastebin.com/ehHtNz9R

### Debug Crash Log

https://pastebin.com/hCV96TuT

**Comment by jojo2357** [comment]
Make the transformer power an accumulator which powers the circuit. This puts a bottleneck in the system, preventing burning.
