### ISSUE TITLE
[Suggestion] Extended Support for Railgun Viable Projectiles

### ISSUE THREAD

**Issue by Shibva** [BluSunrize/ImmersiveEngineering#5576]
### Explain your idea

The trident launch is useful though it seems that its also a bit limited; What I pose is a possible method to extend this towards a mod called Tetra

Tetra is a module tool mod that in summary is an alternate take on the well-known TInkers Construct. There are a few tools that can be tossed being the Modified Trident, a Javin (made from a shovel) and a Throwing Blade

While the third is unlikely I do feel that the modified Trident and Javlin should have some sort of support

The bright side is they appear to work just like a trident would (including Loyaly compatibility)

The overall suggestion is to implement compatibility with these 2 tools [Do note though that while its presumed easy to add the way the tools work is based on internal NBT data]

I believe adding this would expand upon the usefulness on the railgun with lobbing projectiles

ON a semi-relivent note: there's even an option in the mod that makes a possible spear that breaks block on impact. Whether you add special behavior to this is up to you :)

**Comment by BluSunrize** [comment]
This is a matter for an addon or for Tetra to do from their side, I'm not super interested in making cross mod support for this.
