### ISSUE TITLE
Waterwheel bugging out in 1.19.3

### ISSUE THREAD

**Issue by mindforger** [BluSunrize/ImmersiveEngineering#5577]
### Minecraft Version

1.19

### Immersive Engineering Version

9.2.0-160

### Expected Behavior

Waterwheels to be oriented correct and rotating, thus producing power when attached to dynamo

### Actual Behavior

Oriented strangely, not rotating and not producing power after multiple iterations of build order, in case i messed up

last time used i have to attach the first to the dynamo hole and the other two on the frist wheel

feel free to correct my if i missed out at some change, but i found nothing so far in the engineers manual

### Steps to reproduce

build a waterwheel, attach it anywhere, preferably on a dynano and let water flow over it
![2023-02-15_11 52 18](https://user-images.githubusercontent.com/2683555/219009297-1d1585dd-8ca4-48e4-98b0-d47d9597caf6.png)
![2023-02-15_11 52 41](https://user-images.githubusercontent.com/2683555/219009307-fd8bc21d-e16a-44cb-9665-5b48661646cc.png)

### Debug Crash Log

https://pastebin.com/YBpkUTBY

**Comment by mindforger** [comment]
one small correction, the DO turn when completely free standing, this seems to include diagonal spacing too :D

on a second edit, i forgot they need slabs in the open edge blocks XD they rotate now but they look awkward

**Comment by malte0811** [comment]
3ea6e8dc96f8c0635be7fd521fcfa727e3f5748e

**Comment by ZARD00001** [comment]
How to use the 3ea6e8d fix correctly? What are the steps? This is my first contact. Please advise me.

**Comment by mindforger** [comment]
you will have to wait for a new release or make one yourself ... The issue is purely cosmetic though, no real need to rush

**Comment by ZARD00001** [comment]
Have you solved the problem? Could you tell me exactly how it was resolved? In order to solve this problem, I have been looking for information for a whole day, but finally failed to find a good way, so I can only come here to consult you.

**Comment by mindforger** [comment]
Just be patient and wait for a new release if unable to make a release yourself, the issue is only cosmetic the wheels still work fine, i only made a mistake and placed a full block in one of the corners that blocked the wheel,. If your wheel does not spin, check your clearance and make sure to only use slab in the cornner if needed but dont respond to this closed issue please .. If you have any other issue, make a new report and refere to this one instead
