### ISSUE TITLE
advanced blast furnace crash when teleporting away in 1.19.3

### ISSUE THREAD

**Issue by mindforger** [BluSunrize/ImmersiveEngineering#5578]
### Minecraft Version

1.19

### Immersive Engineering Version

9.2.0-160

### Expected Behavior

not crashing when teleporting

### Actual Behavior

when i teleport away from an active blast furnace, i get a crash ... seems some racing condition where an unloaded block is attempted to be ticked .. edit: nope loading it did not help

### Steps to reproduce

place an advanced blast furnace, power it, feed some stuff and teleport away

### Debug Crash Log

https://pastebin.com/44iHPPum

**Comment by malte0811** [comment]
cad1912fbae7ff1ad187e2ccfc6babc29334e800
