### ISSUE TITLE
[Bug]: Rendering issue on improved blast furnace from immersive engineering caused by 8-way mod compatibility issue

### ISSUE THREAD

**Issue by math8742** [BluSunrize/ImmersiveEngineering#5579]
### Minecraft Version

1.19

### Immersive Engineering Version

ImmersiveEngineering-1.19.2-9.1.2-159.jar

### Expected Behavior

No Rendering issue.

### Actual Behavior

Rendering issue as seen in the following screenshot. Turning VBO off or on does no difference:
<img width="505" alt="bug" src="https://user-images.githubusercontent.com/125552946/219386428-30a76c7b-06e8-4b36-b548-446fdeff20fd.png">

### Steps to reproduce

 1.  Install these mods and their requirements for minecraft 1.19.2 and forge 43.2.4:
    Ad Astra 1.12.3
    Rubidium 0.6.2
    Connected glass 1.1.6
    Create 0.5.0.i
    PneumaticCraft: Repressurized 4.3.1-20
    ChemLib 2.0.16
    Mekanism 10.3.8.477
    Immersive engineering 9.1.2-159

   2. Make a new world

   3. Build the improved blast furnace from immersive engineering.

   4. You now have the rendering issue seen in the screenshot above.

### Debug Crash Log

https://pastebin.com/jaxnLccu

**Comment by math8742** [comment]
You can use 7 of the 8 mods at the same time without issue. It does not matter which mod you remove.

**Comment by malte0811** [comment]
This is a known bug in Rubidium, the other mods are just required because they add textures and cause the blast furnace texture to end up at the right location in the atlas. Asek3/Rubidium#407 fixes this on 1.18, but hasn't been released yet. I assume it will be fixed on 1.19 as well.
