### ISSUE TITLE
Hydraulicraft farm trolley compat

### ISSUE THREAD

**Issue by 1skandar** [BluSunrize/ImmersiveEngineering#558]
I see that you added an IE Hemp trolley for the Hydraulicraft Harvester in the latest update which is super useful. i also see it lacks a recipe...which makes it quite a bit less useful. Hydraulicraft compatibility is true in the configs, so I'm not sure if this is a bug or an oversight or what.

**Comment by BluSunrize** [comment]
total oversight on my part .~.
Will fix soon.
