### ISSUE TITLE
Can't change I/O color in circuit table

### ISSUE THREAD

**Issue by johalun** [BluSunrize/ImmersiveEngineering#5580]
### Minecraft Version

1.19

### Immersive Engineering Version

9.1.2-159

### Expected Behavior

Click on input or output in the circuit table to change color or register. It should change from white to something else.

### Actual Behavior

The color remains white. LMB click trigger a sound, but nothing changes. RMB, MMB, scroll wheel, none of them do anything.

### Steps to reproduce

Open circuit table
Place components
Select logic gate
Click I/O slots to change color

On Valhelsia 5.0.14a mod pack with rubidium and oculus added. 

### Debug Crash Log

N/A

**Comment by johalun** [comment]
I found one way that works. When hovering over a I/O slot, I can press a number X for register RX and a pressing a character will cycle through the colors that start with that character.

**Comment by malte0811** [comment]
70a3e9e787def90732f8a358bbec16daa00f1091
