### ISSUE TITLE
Fermenter recipes added with crafttweaker do not respect config changes in serverconfig

### ISSUE THREAD

**Issue by AubriTheHuman** [BluSunrize/ImmersiveEngineering#5583]
### Minecraft Version

1.18

### Immersive Engineering Version

ImmersiveEngineering-1.18.2-8.3.1-157

### Expected Behavior

Changing the time and energy consumption config option in the serverconfig for the fermenter file should modify crafttweaker recipies' craft time and energy consumption as well. Not just json recipes.

### Actual Behavior

Crafttweaker recipes added to the fermenter always run at full speed, whilst JSON recipes added to it run at the expected reduced speed. 

This isnt game breaking, but is mildly annoying as JSONs are harder to make than crafttweaker scripts. I also do not know if this effects other machines.

**Crafttweaker version:** CraftTweaker-forge-1.18.2-9.1.205
This also occurs in version: ImmersiveEngineering-1.16.5-5.1.0-148

### Steps to reproduce

1. Add a recipe with craftweaker to the fermenter such as this:
`<recipetype:immersiveengineering:fermenter>.addRecipe("xp_bottle_from_water", <item:minecraft:dragon_breath>, 6400, <item:minecraft:experience_bottle>, <fluid:minecraft:water> * 50);`
2. Add a recipe with a json to the fermenter such as this:
`{"type":"immersiveengineering:fermenter","fluid":{"fluid":"minecraft:water","amount":50},"result": "item":"minecraft:experience_bottle"},"input":{"item":"minecraft:honey_bottle"},"energy":6400}`

3. Change the serverconfig options (either in defaultconfigs folder or in the world file itself) to:
```
[machines.fermenter]
	#A modifier to apply to the energy costs of every fermenter recipe
	#Range: 0.001 ~ 1000.0
	energyModifier = 0.2
	#A modifier to apply to the time of every fermenter recipe
	#Range: 0.001 ~ 1000.0
	timeModifier = 5
```

4. Upon doing the two recipes, the crafttweaker recipe will run at normal speed, however the json recipe will run at 1/5th speed. I dont really have an easy way to check energy consumption however.
This also occurs whether or not an item output is declared in either recipe type.

### Debug Crash Log

https://pastebin.com/0kNmRkPG

**Comment by BluSunrize** [comment]
Fixed for future releases
