### ISSUE TITLE
[18.2] Quark Quick Attribute overall clashing with barrel UI 

### ISSUE THREAD

**Issue by Shibva** [BluSunrize/ImmersiveEngineering#5584]
### Minecraft Version

1.18

### Immersive Engineering Version

ImmersiveEngineering-1.18.2-8.3.1-157.jar

### Expected Behavior

when using special parts and applying a bayonet I expected the overlay to be in working over (sorry if this sounds its coming from an ass; describing what was expected sometimes can sound this way unintentionally >n<)

### Actual Behavior

![image](https://user-images.githubusercontent.com/38770780/220267703-adf6ac3f-cd2f-405d-aba2-8ba2fb16525d.png)

specific rendering overlays are fighting

### Steps to reproduce

Should be mostly self explanitory but the following should be noted:

The Revolver needs to have some custom attributes on it; ones that can be acquired from trades

attach a bayonet and it should do the trick

NOTE: WHILE RUBIDIUM IS PRESENT this issue in particular does not play a role in the bug; this is an issue just between Quark and IE

### Debug Crash Log

https://gist.github.com/Shibva/0c0b4175f46f496937f62dbef1bb9071

**Comment by BluSunrize** [comment]
This seems to be caused by poor design on Quark's part.
It does not play nice with an item that can have different effects when used in different slots, it results in doubling up the tooltip.
I'll investigate a fix from our end, but I can't guarantee that it's possible.

**Comment by BluSunrize** [comment]
I was unable to find a workaround from our end. This is on Quark to fix I'm afraid.

As a workaround, you can hold down **Shift** in order to display the attributes the way vanilla Minecraft does.
