### ISSUE TITLE
Rendering Block Entity Crash

### ISSUE THREAD

**Issue by littlepianist** [BluSunrize/ImmersiveEngineering#5585]
### Minecraft Version

1.19

### Immersive Engineering Version

1.19.2-9.1.2-159

### How did it happen?

Crashed when joining a server. Not using any block or item.

### Crash Log

https://pastebin.com/8kE4Wq8N

**Comment by littlepianist** [comment]
![1676983638798](https://user-images.githubusercontent.com/75674050/220348697-ee9c8b7e-30bd-45ea-95ff-176c710a7fa0.jpg)
![1676983644465](https://user-images.githubusercontent.com/75674050/220348724-b2824f38-c515-4e06-99f1-5bdb4f2631c3.jpg)
other stuff that might be useful

**Comment by BluSunrize** [comment]
```
"net.minecraftforge.client.model.data.ModelData.get(net.minecraftforge.client.model.data.ModelProperty)" because "data" is null
	at ic2.core.platform.rendering.models.BaseModel.getParticleIcon(BaseModel.java:76)
```

Looks a lot like IC2 Classic fails when grabbing their particle icon...

**Comment by BluSunrize** [comment]
Given that @Speiger seems to have chosen to not make IC2 Classic's code visible source, I couldn't even tell you why it is throwing an exception there.

**Comment by malte0811** [comment]
As (I assume) Speiger noted in the screenshotted comment, we're passing `null` to `getParticleIcon` even though the parameter is marked non-null: https://github.com/MinecraftForge/MinecraftForge/blob/b63dc48e19d31d1a469827a828046bbef0976300/src/main/java/net/minecraftforge/client/extensions/IForgeBakedModel.java#L65. Should be easy to fix, just replace `null` with the empty model data instance.

**Comment by Speiger** [comment]
@BluSunrize you just need to use ModelData.EMPTY instead of null for ModelData parameters.
And about open source:
I am legally obligated to have the project closed source otherwise player will sue me to pluto and back.

**Comment by Meduris** [comment]
Hey, thank you for the quick fix. Just checked the commit and noticed that you fixed this on your 1.18 branch.

I am not sure about how exactly you handle your git branches etc, but I just wanted to mention that this also affects the 1.19.2 branch (which is the version with which that crash happened).

Also I think with 1.19 thats the case where Speiger mentioned the ``EmptyModelData.INSTANCE`` being replaced with ``ModelData.EMPTY``

**Comment by malte0811** [comment]
> I am not sure about how exactly you handle your git branches etc

Older version branches get merged into newer versions every so often (and always before releases). So 1.19.2 will get it in the next release, and the `EmptyModelData.INSTANCE` vs `ModelData.EMPTY` will come up during the merge.

**Comment by Meduris** [comment]
> Older version branches get merged into newer versions every so often (and always before releases). So 1.19.2 will get it in the next release, and the EmptyModelData.INSTANCE vs ModelData.EMPTY will come up during the merge.

Oh ok, thanks for the clarification.
