### ISSUE TITLE
Rendering item Drill crash

### ISSUE THREAD

**Issue by nokia6303i** [BluSunrize/ImmersiveEngineering#5588]
### Minecraft Version

1.19

### Immersive Engineering Version

ImmersiveEngineering-1.19.2-9.1.2-159

### How did it happen?

I have problem with rendering with item Drill, game crash every time when i trying just to see drill in JEI, Creative mode, or when i enter in section drill in IE Book

### Crash Log

https://pastebin.com/CDVsRRqV

**Comment by nokia6303i** [comment]
and additional crashlogs from book and creative mode 
https://pastebin.com/j9geNMJA
https://pastebin.com/T9kFsMgM

**Comment by malte0811** [comment]
Known bug in Optifine. They need to fix that, nothing we can do about it.

**Comment by nokia6303i** [comment]
Ok, thanks, I think I'll try to change the version Optifine. Maybe its help
