### ISSUE TITLE
Couldn't even launch. (1.19.3)

### ISSUE THREAD

**Issue by Zarandolph01** [BluSunrize/ImmersiveEngineering#5589]
### Minecraft Version

1.19

### Immersive Engineering Version

9.2.0-160 FORGE

### How did it happen?

Was attempting to launch Minecraft, crashy errored, and in logs, it points at Immersive Engineering conflicting with Forge's rendering. 
[latest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/10819465/latest.log)
[debug.log](https://github.com/BluSunrize/ImmersiveEngineering/files/10819466/debug.log)

### Crash Log

https://pastebin.com/WvTbx2VB

**Comment by mindforger** [comment]
what makes you believe this is an IE issue? 

>java.lang.IllegalArgumentException: No model for layer midnight-hats:witch_hat#main
	at net.minecraft.client.model.geom.EntityModelSet.m_171103_(EntityModelSet.java:17) ~[client-1.19.3-20221207.122022-srg.jar%231010!/:?] {re:classloading,re:mixin}

The crashlog is not even listing IE anywhere, the modlist looks incomplete

Please check your crashlog folder if that is even the right log and consider reinstalling you modded instance as the log even looks like it is broken somewhere else

**Comment by malte0811** [comment]
From the logs this is the actual issue:
> Mod uteamcore requires forge 44.1.17 or above

Forge continues loading after this error, Mixins get applied, but nothing else does, so everything breaks down.
