### ISSUE TITLE
Crash with forgecraft the modpack with 0.6.0

### ISSUE THREAD

**Issue by liamjarvisman** [BluSunrize/ImmersiveEngineering#559]
http://pastebin.com/AbeXCtNS

**Comment by Kolatra** [comment]
Looks like you're using Forestry 3, which is most likely unsupported.

**Comment by liamjarvisman** [comment]
no i just updated to forestry 4 and still crashed

**Comment by liamjarvisman** [comment]
new crash log: http://pastebin.com/4MxDRwpa

**Comment by theunkn0wn1** [comment]
Not IE. Bdews mods are nnot yet working with forestry.

**Comment by liamjarvisman** [comment]
it's not bdews mods because i just removed all of them

**Comment by liamjarvisman** [comment]
I'll try removing forest because me latest crash log mention forestry

**Comment by theunkn0wn1** [comment]
Error is with gendustry, among other Forestry addons. Just reviewed your
crashlog

**Comment by liamjarvisman** [comment]
I removed all of the forestry addons just then i'll see if that works

**Comment by liamjarvisman** [comment]
thanks guys. It was all the forestry addons
