### ISSUE TITLE
JEI Item rendering crash: fluorescent tube

### ISSUE THREAD

**Issue by TheRTGGaming** [BluSunrize/ImmersiveEngineering#5591]
### Minecraft Version

1.19

### Immersive Engineering Version

1.19.2-9.1.2-159

### How did it happen?

When scrolling through the list with JEI and entering the List for immersive engineering it would freeze then crash the game.

### Crash Log

https://gist.github.com/TheaRTGGaming/51de3462f9db5e8edf74a1e11f9f5c36

**Comment by mindforger** [comment]
Remove or try update optifine, issue is well known now already ;)

**Comment by BluSunrize** [comment]
Optifine is not supported
