### ISSUE TITLE
Crusher rendering glitch

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#56]
Source pulled and compiled on 6/4/2015 aganst version 0.1.9
output SHA1: 
10d276915509170be2f10e98c3fd704c71f5201c *ImmersiveEngineering-0.1.9.jar

Libs built against (SHA1, lib name)
cffeaa68718a71f948a16579d954153e22b90f9c : CodeChickenCore-1.7.10-1.0.4.29-dev.jar

2dd3b058db77eac637b638aa076e0968b203e75e *CodeChickenLib-1.7.10-1.1.3.138-dev.jar

5bec02eb13f462acb1868b6826ae667719296c9d *industrialcraft-2-2.2.729-experimental-dev.jar

41b6648b6941cce32f311681ee358c6a4980a936 *MineTweaker3-Dev-1.7.10-3.0.9C.jar

bc8a47a2f68ac3f28b34af992481b1257431f105 *NotEnoughItems-1.7.10-1.0.5.110-dev.jar

Using FTB: Horizons (Manually included IE) Version 1.6.2

when crusher processes any item it supports, such as cobblestone -> sand, All other rendered textures in view glitch out as seen below.
![2015-06-07_12 50 46](https://cloud.githubusercontent.com/assets/3110986/8025741/d01c7dfa-0d15-11e5-8bbe-2b387e402f47.png)
![2015-06-07_12 50 56](https://cloud.githubusercontent.com/assets/3110986/8025742/d01f110a-0d15-11e5-97b0-41133df24855.png)
![2015-06-07_12 50 57](https://cloud.githubusercontent.com/assets/3110986/8025743/d021ea74-0d15-11e5-864c-fe5571fec2ea.png)

Log: http://paste.feed-the-beast.com/view/3d7b70b4

**Comment by BluSunrize** [comment]
Known bug, long fixed
