### ISSUE TITLE
[Suggestion] Config option to disable automatic output on all machines

### ISSUE THREAD

**Issue by xieve** [BluSunrize/ImmersiveEngineering#5600]
### Explain your idea

I'm currently building a small modpack where I'll try to integrate the Create mod with Immersive Engineering. For this, I'd like to disable the automatic output of items on all machines via a config options, so the players would have to use funnels on all the machines. I'd be willing to implement this in a PR, if there is interest in merging it.

**Comment by BluSunrize** [comment]
Nope, not interested in having this as a feature, sorry.

I'm perfectly happy with out automatic output features. They lend themselves to IE's native automation via conveyors and I don't find them a balance concern.

Additionally, they are documented in the manual. Having a config that changes the behavior in such a way would either make the manual incorrect or rely on us phrasing a lot of stuff with the config-based switches in manual text. Neither of which I am a fan of.
