### ISSUE TITLE
Gunpowder Barrel + TnT Crash

### ISSUE THREAD

**Issue by blacknight7890** [BluSunrize/ImmersiveEngineering#5601]
### Minecraft Version

1.19

### Immersive Engineering Version

1.19.3-9.3.0-163

### How did it happen?

Got it somehow by blowing up 25 gunpowder barrels with a secondary explosion via a vanilla tnt, there was a second tnt ignited as well in the explosion. When they went off, the game froze up and crashed. Probably just too much happened at once which caused it to crash, but figured It couldn't hurt to post the crash here.

### Crash Log

https://pastebin.com/ms2fvX0J

**Comment by LeoBeliik** [comment]
This has happen to me too, but with only 1 barrel, it's sporadic and dunno what exactly causes it.
I have tried to reproduce this with only IE but it doesn't seem to crash in that case, but again it could be just coincidence. 

Crash: https://gist.github.com/LeoBeliik/84f05ecf8ec53327888ffde36325934e
IE: 9.2.1-164
Forge: 43.2.8

**Comment by mindforger** [comment]
@LeoBeliik try removing rubidium and post a new crashlog please

**Comment by malte0811** [comment]
This is not related to rubidium, we'e simply accessing the set from both client- and server-threads without any synchronization.
