### ISSUE TITLE
1.9.3 crash when placing a blueprint into the engineers workbench interface

### ISSUE THREAD

**Issue by MuesLee91** [BluSunrize/ImmersiveEngineering#5605]
### Minecraft Version

1.19

### Immersive Engineering Version

ImmersiveEngineering-1.19.3-9.3.0-163

### How did it happen?

I made a blueprint for the first time and tried to put it into the designated window in the engineers workbench.
At that moment, the view collapses and the game crashed.
When trying to restart the world, one can only see the sky box, everything else is not visible and it crashes instantly in that view.
I created a creative world and tried it there too.
With the exact same result.

### Crash Log

https://pastebin.com/493Zr48g

**Comment by BluSunrize** [comment]
Optifine is not supported
