### ISSUE TITLE
creative Multiblock autobuilder.

### ISSUE THREAD

**Issue by Developer2704** [BluSunrize/ImmersiveEngineering#5610]
### Explain your idea

I think that there should be a creative multiblock autobuilder. I also can not figure out how to build the excavator because it shows the engine and bucket wheel seperately so i can not figure out where to attach the two so i think the entry should be updated.

**Comment by TeamSpen210** [comment]
This does already exist. All multiblocks are vanilla structure files, so you can just give yourself a vanilla structure block, then load `immersiveengineering:multiblocks/crusher` for example. Perhaps to make it easier to find there could be a `/command` added which gives a list of multiblocks, then gives you a structure block with NBT preset for loading.

**Comment by Developer2704** [comment]
o wait i just discovered it in /place

**Comment by Developer2704** [comment]
but there should be a command for the list of multiblocks

**Comment by Developer2704** [comment]
can a command be added for the list of multiblocks

**Comment by SkyTheCodeMaster** [comment]
As a side note, this functionality *does* exist in the `Projector` from Immersive Petroleum. That is an extra mod though, which is probably not a preferable option, and the `Projector` also doesn't quite fit the theme of Immersive Engineering in my opinion.

**Comment by BluSunrize** [comment]
I see no reason in adding this, since structure blocks cover this.
The structure files in turn are found on this very github.

**Comment by Developer2704** [comment]
where are they i am new to this github

**Comment by BluSunrize** [comment]
Here: <https://github.com/BluSunrize/ImmersiveEngineering/tree/1.19.2/src/main/resources/data/immersiveengineering/structures/multiblocks>

Also, vanilla Minecraft has **autocompletion** on its place command. It's genuinely this easy:

![grafik](https://user-images.githubusercontent.com/4106382/226345878-7f72645b-828d-4640-af76-bcbc6dd55665.png)

**Comment by Developer2704** [comment]
thx
