### ISSUE TITLE
Improved blast furnace won't output slag and steel

### ISSUE THREAD

**Issue by tio-jo** [BluSunrize/ImmersiveEngineering#5611]
### Minecraft Version

1.19

### Immersive Engineering Version

1.19.3-9.3.0-163

### Expected Behavior

Improved blast furnace should output slag and steel to adjacent inventories.

### Actual Behavior

Improved blast furnace won't output slag and steel to adjacent inventories.

### Steps to reproduce

build it and connect inventories

### Debug Crash Log

https://pastebin.com/ELeYcaJN

**Comment by malte0811** [comment]
5c145f413bf39708b16a9870a22e365caf95ae8a
