### ISSUE TITLE
Squeezer won't output redstone signal at all

### ISSUE THREAD

**Issue by tio-jo** [BluSunrize/ImmersiveEngineering#5612]
### Minecraft Version

1.19

### Immersive Engineering Version

1.19.3-9.3.0-163

### Expected Behavior

The squeezer should output a redstone signal depending on it's fill level 

### Actual Behavior

The squeezer doesn't output a redstone signal at all both when using Redstone Probe or Comparator

### Steps to reproduce

fill the mixer and connect a probe or a comparator and it won't have a redstone signal

### Debug Crash Log

https://pastebin.com/ELeYcaJN

**Comment by malte0811** [comment]
f94dbc2550bc8df90a9544124fb38b6aa3a82815
