### ISSUE TITLE
Sheetmetal Chute Texture Bug

### ISSUE THREAD

**Issue by GermanCheetah** [BluSunrize/ImmersiveEngineering#5614]
### Minecraft Version

1.18

### Immersive Engineering Version

8.4.0-161

### Expected Behavior

The placed blocks should have textures as shown in the inventory.

### Actual Behavior

![2023-03-14_04 49 53](https://user-images.githubusercontent.com/93001900/224888941-05d1c157-f94e-430a-805f-ba1c110575af.png)
One of the chutes texture seems broken.

### Steps to reproduce

1. place one of each of the 4 chutes found in the creative inventory (it is not required to place all of the chutes, i only say to place all of them since they all have the same name)
2. one of them will have a broken texture

### Debug Crash Log

https://pastebin.com/ZP2eL9kU

**Comment by malte0811** [comment]
This is a known bug in Rubidium, fixed in https://github.com/Asek3/Rubidium/pull/407. That will be in the next Rubidium build, whenever that happens.
