### ISSUE TITLE
[Suggestion] More useful Structural Engineer map trades

### ISSUE THREAD

**Issue by QuickBASIC** [BluSunrize/ImmersiveEngineering#5618]
### Explain your idea

Currently Structural Engineer villagers only sell maps for veins near them and only one type which means that they're not very reusable. Given that the map trades are set when the trade is added, you can't move the villager for different trades.

Possible fixes:
* Find a way for villagers to sell maps to deposits near them after they've been moved to a new location.
* Generate maps to only rarer deposit types at a larger radius.
* Change the trade to sell a pre-drilled core sample for a specific type of vein in a larger radius (to get around limitations of generating maps.)
* Have the engineer sell a "sealed map" version that can be opened at any location and use that location to create the map in that area to the closest vein of that type.

Related conversation:
https://discord.com/channels/270295681829306369/339127815666532352/1086339967179034674

**Comment by BluSunrize** [comment]
Doing things like "moving the villager" doesn't really work, unfortunately. We do not have the capability to easily manipulate their trades after their have been generated.
The idea of "sealed maps" didn't appeal to me, so instead I opted to improve the experience of rare veins:

https://github.com/BluSunrize/ImmersiveEngineering/commit/ce9a57f896a9dcd5b04ef6090d0eabf554405fde

It now finds the rarest veins in a 16 chunk radius and picks randomly out of the top 10.
And the villager can have two maps, if you get lucky!
