### ISSUE TITLE
[1.19.2] Right click actions rises the heavy plated shield when it shoudn't

### ISSUE THREAD

**Issue by Zahkriiven** [BluSunrize/ImmersiveEngineering#5621]
### Minecraft Version

1.19.2

### Immersive Engineering Version

9.2.0-162.12

### Expected Behavior

The same way regular shields act, when doing actions like eating or charging the railgun the shield shoudn't be risen up.

### Actual Behavior

![image](https://user-images.githubusercontent.com/25531677/226125967-46737b03-5b0e-4c2d-907a-69fcdabdbea3.png)
Shield is rised up, clipping with the food

### Steps to reproduce

1. Equip heavy plated shield in offhand
2. Try to eat food

### Debug Crash Log

https://pastebin.com/9Y1Efcw1

**Comment by Zahkriiven** [comment]
I just noticed this was fixed for 1.19.3 in 647dccb248049598cc1a9a5f17fdb85db80bdd32

**Comment by BluSunrize** [comment]
I ported that fix back to 1.19.2
