### ISSUE TITLE
[Suggestion] Change HempBlock to extend CropBlock

### ISSUE THREAD

**Issue by Crystal-Spider** [BluSunrize/ImmersiveEngineering#5623]
### Explain your idea

Rather than extending `BushBlock` and having and `EnumProperty` for the age of the crop, `HempBlock` could extend `CropBlock` and override the parts regarding the age property. To distinguish the top from the bottom a `BlockState` property could be added, like it's done for Thermal Cultivation.  
This change will allow better compatibility with mods that expect cultivable crops to extends `CropBlock`. For instance, [Harvest with ease](https://www.curseforge.com/minecraft/mc-mods/harvest-with-ease) does not work with hemp crops currently (right-clicking does not harvest).

**Comment by BluSunrize** [comment]
We can't do that midway through a version, because Crop blocks have completely different properties.

**Comment by Crystal-Spider** [comment]
I understand, meanwhile I thank you for considering my suggestion and I hope that in a future release it will be added!  
Thanks again!
