### ISSUE TITLE
[Suggestion] ... All terracotta colour variants valid for connectors

### ISSUE THREAD

**Issue by Jevnaker** [BluSunrize/ImmersiveEngineering#5628]
### Explain your idea

Hi it would be a great quality of life improvement if the wire relay and connector stuff that use terracotta would be able to just auto use all the colour variations of terracotta.

**Comment by BluSunrize** [comment]
It already does so:

![grafik](https://user-images.githubusercontent.com/4106382/229630018-3e9cdfe1-daef-4024-8ced-03d07ae60eae.png)


Please make sure you aren't playing a very old version or playing a modpack which has changed the recipes.
