### ISSUE TITLE
Crash with newest Rubidium and Oculus update on 1.18.2

### ISSUE THREAD

**Issue by spader1302** [BluSunrize/ImmersiveEngineering#5629]
### Minecraft Version

1.18.2

### Immersive Engineering Version

1.18.2-8.4.0-161

### How did it happen?

With the new Rubidium and Oculus update, I get this weird chunk loading issue and crash a few seconds after I load into a new world. Only happens with Immersive Engineering enabled.

Minecraft: 1.18.2
Forge: 40.2.1
Rubidium: 0.5.5
Oculus: 1.5.2
Immersive Engineering: 1.18.2-8.4.0-161

![2023-03-23_18 49 34](https://user-images.githubusercontent.com/76409510/227303354-53af9810-6729-4bc5-9a0f-68fb76888d93.png)

### Crash Log

https://mclo.gs/3r5PTGL

**Comment by Shibva** [comment]
This issue is related to Rubidium; this issue is on Rubidum's end.

Please don't pester the IE devs about this

**Comment by BluSunrize** [comment]
^ this
