### ISSUE TITLE
java.lang.IllegalStateException: Already tesselating!

### ISSUE THREAD

**Issue by Tsyklop** [BluSunrize/ImmersiveEngineering#563]
Crash. Connected MV wire Resonant energy cell and Floodlights

http://pastebin.com/sBnsgN66

**Comment by theunkn0wn1** [comment]
Unable to reproduce with just IE and its dependents.

the floodlight will only accept LV current btw.

Preliminary review of your crashlog indicates you are using a weather mod, have you tried disabling that?

**Comment by Tsyklop** [comment]
Hmm. There are such departures. I tried again to connect - all right.
