### ISSUE TITLE
Engineering Bench crash

### ISSUE THREAD

**Issue by Chiseris** [BluSunrize/ImmersiveEngineering#5630]
### Minecraft Version

1.18.2

### Immersive Engineering Version

ImmersiveEngineering-1.18.2-8.4.0-161.jar

### How did it happen?

Using the engineering bench to make common projectiles, as long as the bench is in the world and placed down I'm not able to rejoin the world and instant crashes on joining the server. I have tried without optifine installed, without shaders on, even tried wiping and reinstalling all files and config from the mod, trying it in singleplayer, nothing fixes the crash.

### Crash Log

https://pastebin.com/4tCfqnPH

**Comment by mindforger** [comment]
> I have tried without optifine installed

Can you link a crashlog without optifine then please?

**Comment by malte0811** [comment]
This *can* happen without Optifine, if you set `enableVBO` to `false` in the IE client config. The crash will be fixed in the next build; for now make sure to a) not use Optifine and b) to set `enableVBO` to `true` (the default value).

**Comment by Chiseris** [comment]
> This _can_ happen without Optifine, if you set `enableVBO` to `false` in the IE client config. The crash will be fixed in the next build; for now make sure to a) not use Optifine and b) to set `enableVBO` to `true` (the default value).

I never messed with any client or server configs for the mod so anything that was turned on by default stayed that way, enableVBO included, and I tried without optifine installed but the crash still happened. Is there an eta for the fix to be implemented because right now we've disabled the mod from our server until then.

**Comment by BluSunrize** [comment]
Can you then please provide a crashlog _without_ optifine and *with* `enableVBO` set to true?

**Comment by Chiseris** [comment]
> Can you then please provide a crashlog _without_ optifine and _with_ `enableVBO` set to true?

I tried to replicate the crash but had no luck in doing so without optifine, so for now, I'll play without optifine installed and wait for the crash fix in the next build!
