### ISSUE TITLE
Texture bug with conveyor belts

### ISSUE THREAD

**Issue by KazuMurako** [BluSunrize/ImmersiveEngineering#5631]
### Minecraft Version

1.18.2

### Immersive Engineering Version

ImmersiveEngineering-1.18.2-8.4.0-161.jar

### Expected Behavior

![conveyor_belt](https://user-images.githubusercontent.com/75145296/227798489-e24ebd7a-d34c-41f1-8ebe-3fb96cdcd9c3.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/75145296/227798296-67cd3005-6d0a-4030-87dc-d584114e06cb.png)

### Steps to reproduce

While developing a modpack I updated the mods to newer versions.
Modpack version where it last worked: https://www.curseforge.com/minecraft/modpacks/resource-formula/files/4351358
Modpack version where it broke: https://www.curseforge.com/minecraft/modpacks/resource-formula/files/4422478

### Debug Crash Log

https://pastebin.com/QGkJmFNX

**Comment by mindforger** [comment]
That looks a lot like the bug with wrapping around the texture atlas that rubidium supposed to have fixed with 0.5.4 which you actually have installed, can you try without?

**Comment by KazuMurako** [comment]
Removing Rubidium does solve the issue, however installing only IE Rubidium and Forge and they look normal, so there's another mod causing an issue somewhere. Updating to Rubidium 0.5.5 crashes my game.

**Comment by BluSunrize** [comment]
Not an IE issue then.
