### ISSUE TITLE
[1.18.2] Engineers workbench crashes game when inserting blueprint

### ISSUE THREAD

**Issue by AggressivelyMeows** [BluSunrize/ImmersiveEngineering#5633]
### Minecraft Version

1.18.2

### Immersive Engineering Version

8.4.0-161

### Expected Behavior

Expected behaviour is that the bench shouldnt crash when attempting a blueprint.

### Actual Behavior

Game crashes with error: `Error: java.lang.IllegalStateException: Not filled all elements of the vertex`

### Steps to reproduce

Create workbench
Place workbench
Insert blueprint, engineers
[Potentially shift click blueprint into workbench(?)]
Game should crash

### Debug Crash Log

https://gist.github.com/AggressivelyMeows/81fb34009d03b51e1cbaa05cc7be48db

**Comment by mindforger** [comment]
>{re:mixin,pl:accesstransformer:B,**_xf:OptiFine_**:default,re:classloading,

does this happen without optifine?

add a new crashlog if yes

**Comment by Datsun-Drift** [comment]
I have the same error. Also using optifine.
Going to test with it disabled and removed to see if it's the cause.
Will provide update here.

**Comment by Datsun-Drift** [comment]
No crash with OptiFine removed.
(preview_OptiFine_1.18.2_HD_U_H9_pre2)

**Comment by BluSunrize** [comment]
Optifine is not supported.
