### ISSUE TITLE
Revolver 1.12.2 infinite ammo when empty?

### ISSUE THREAD

**Issue by MasaruIsamu** [BluSunrize/ImmersiveEngineering#5634]
### Minecraft Version

1.12.2

### Immersive Engineering Version

ImmersiveEngineering-0.12-98

### Expected Behavior

click apon empty revolver no ammo added  as i have no speed loaders

### Actual Behavior

Each time i click with the revolver being empty the weapon Loads its self with ammo..no animations play for it at all and i have no ammo in my inventory at the start no speed loaders it just gives its self ammo out of thin air

### Steps to reproduce

1. i crafted the gun on my server..
2. loaded some ammo to test fire which worked fine..
3. put gun in my backpack for a while because i needed space
4. went to use the gun but had no ammo..but the firearm got loaded with ammo when i had none

### Debug Crash Log

no crash log strangely enough

**Comment by BluSunrize** [comment]
Support for 1.12 was ended nearly 3 years ago.
