### ISSUE TITLE
[1.19.2] Shift Clicking into Engineer's Workbench CTD

### ISSUE THREAD

**Issue by Smallbomb78v** [BluSunrize/ImmersiveEngineering#5636]
### Minecraft Version

1.18.2

### Immersive Engineering Version

ImmersiveEngineering-1.19.2-9.2.0-162

### How did it happen?

Set enableVBO to false, then grab an IE blueprint (mine was for components) and Shift Left Click it into an Engineers Workbench (not the circuit one) and the game should immediately freeze and crash.

Also whenever you spawn back into the world, immediately CTD. And can be fixed if you set enableVBO to true.

Other mods: https://pastebin.com/Zc6sTLGK

### Crash Log

https://pastebin.com/xQbYjpMV

**Comment by BluSunrize** [comment]
> And can be fixed if you set enableVBO to true.

There's your fix!
A more permanent solution is coming with the next release
