### ISSUE TITLE
Texture errors and Breaker Switch bug

### ISSUE THREAD

**Issue by Tsyklop** [BluSunrize/ImmersiveEngineering#564]
Texture Error:

![2015-11-02_09 58 39](https://cloud.githubusercontent.com/assets/6783568/10876896/c611a1ac-8149-11e5-90ca-f0ba7cc850c5.png)
![2015-11-02_09 58 42](https://cloud.githubusercontent.com/assets/6783568/10876899/c615c99e-8149-11e5-9b55-5a9805f32714.png)
![2015-11-02_10 07 03](https://cloud.githubusercontent.com/assets/6783568/10876897/c611c506-8149-11e5-8b97-4535ff678599.png)
![2015-11-02_10 07 16](https://cloud.githubusercontent.com/assets/6783568/10876898/c613badc-8149-11e5-89f0-68245b4e9f86.png)

Breaker Switch bug: He did not Dropped the destruction of the block.

![2015-11-02_10 07 56](https://cloud.githubusercontent.com/assets/6783568/10876895/c6117eac-8149-11e5-988a-647c34b03164.png) 

Mod List: http://pastebin.com/JYKMeAc6

**Comment by cobra** [comment]
What texture pack are you using and which resolution is this?

**Comment by Tsyklop** [comment]
@cobra defscape + faitful x32 for mods. 1280x1024

**Comment by cobra** [comment]
I meant the texturepack resolution. That's 64x64 for defscape, right?
What version of faithful is this? If it includes IE textures, it's outdated.

**Comment by Tsyklop** [comment]
Yes? right. I download faitful from http://f32.me/

I have laset versions textures Faitful

**Comment by cobra** [comment]
Yeah, that's broken there.

**Comment by cobra** [comment]
For the large buckets: are you using optifine or mcpatcher?

**Comment by Tsyklop** [comment]
@cobra Optifine.

**Comment by ststeppat** [comment]
The some Problem for me, it destroys the textures from Lava and Water. I use Optifine und BDcraft 64x Textures. With the last Version was not this problem.

**Comment by BluSunrize** [comment]
Breaker switch got a new model, Optifine breaks all the things.
