### ISSUE TITLE
doing /reload causes a "fail"

### ISSUE THREAD

**Issue by redgoblin88** [BluSunrize/ImmersiveEngineering#5641]
### Minecraft Version

1.19.2

### Immersive Engineering Version

- immersive engineering: 9.2.0-162

### Expected Behavior

to reload datapacks/recipes that were added in my actual instance (this bug report is for a "narrowed down" issue as ive located where the issue roughly is to try and help reduce debugging time)

### Actual Behavior

upon doing the /reload command, i get a "fail" error and recipes/datapacks are "reverted"

### Steps to reproduce

upon having the listed mods below downloaded (no more, no less), start the game, make (or join) a world and type /reload, this should reload all the datapacks/recipes however it "fails" and reverts back to old data
however, note that if you have added something via datapack (for example, adding/changing something VIA kubejs such as "dirt to diamond" recipe added) and then close the game and re-launch it, the "failed" recipe from last test is now working and loaded up (until you use the command again)

mods used...
- forge: 43.2.8
- elementalcraft: 5.5.10
- DataPack Anvil: 4.3.1
- immersive engineering: 9.2.0-162
logs: https://pastebin.com/PSU9PhBw

### Debug Crash Log

https://pastebin.com/1NHTsyRc

**Comment by BluSunrize** [comment]
Can you please test if this issue occurs without Elementalcraft?

**Comment by redgoblin88** [comment]
it does, im not sure if the issue is a problem with immersive or elemental because this does not occur if im only running immersive OR elemental, only when both are present

[edit]
whoops, just re-read what you said and i mean it does not happen without elementalcraft
and nor does it happen if i have elementalcraft without immersive, its when i have both this occurs

**Comment by BluSunrize** [comment]
@malte0811 I'd need your help on this. Not high priority, because it seems to only trigger on reload. 

Can we be sure whether or not this is because ElementalCraft does something "too early", or are we missing a safety somewhere?

**Comment by malte0811** [comment]
Fixed in ElementalCraft 5.6.0 according to https://github.com/Sirttas/ElementalCraft/issues/133#issuecomment-1500954021.

Edit: As the crash involves EC using non-API IE classes, I'd argue that it's on them to fix.
