### ISSUE TITLE
Recipe issue with Primal Magick

### ISSUE THREAD

**Issue by border999** [BluSunrize/ImmersiveEngineering#5642]
### Minecraft Version

1.18.2

### Immersive Engineering Version

ImmersiveEngineering-1.18.2-8.4.0-161

### Expected Behavior

be able to see item affinities for Immerive engineering items.

### Actual Behavior

error

### Steps to reproduce

have both in a modpack together.

### Debug Crash Log

https://gist.github.com/border999/184c15d14cbbdc4e8fc0d7bc8a8047c8

**Comment by BluSunrize** [comment]
Yeah Primal Magick does exactly what it says in the error there:
> an inventory that does not match the recipe

https://github.com/daedalus4096/PrimalMagick/blob/master/src/main/java/com/verdantartifice/primalmagick/common/affinities/AffinityManager.java#L336

They don't respect the width and height of the recipe, so there's not much we can do from our end.
