### ISSUE TITLE
Eww... Chunk rendering goes... Strange

### ISSUE THREAD

**Issue by Ynty** [BluSunrize/ImmersiveEngineering#5644]
### Minecraft Version

1.18.2

### Immersive Engineering Version

1.18.2-8.4.0-161

### How did it happen?

So, i created a new world. and first ia have seen was that what you can look at screenshot, so, after a few seconds. game has crashed
![image](https://user-images.githubusercontent.com/48620418/230095071-b782cea1-14d6-4561-aa41-35e565f4d04e.png)

[latest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/11159280/latest.log)

### Crash Log

[latest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/11159280/latest.log)

**Comment by Zydesian** [comment]
I'm also having this issue when I have the mod loaded. Though mine seems to look a little more extreme.
[crash-2023-04-04_21.40.52-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/11161416/crash-2023-04-04_21.40.52-client.txt)
![2023-04-04_21 34 13](https://user-images.githubusercontent.com/67185259/230155290-5ff44943-6f45-4bc6-a605-80fb6ab674d1.png)
![2023-04-04_21 29 38](https://user-images.githubusercontent.com/67185259/230155300-0bb3bb7e-ba76-4e5e-a710-2ce0c123ff0e.png)

**Comment by BluSunrize** [comment]
Rubidium, Oculus and Optifine are all not supported.
