### ISSUE TITLE
Uhhh

### ISSUE THREAD

**Issue by Acat1234** [BluSunrize/ImmersiveEngineering#5648]
### Minecraft Version

1.19.2

### Immersive Engineering Version

9.2.1-164

### Expected Behavior

Something for the emerald

### Actual Behavior

![2023-04-08_16 05 25](https://user-images.githubusercontent.com/126712560/230746096-6a2474ee-06d6-4bb2-bbba-21bf299e9b96.png)
Air for an emerald?

### Steps to reproduce

1 Find a village.
2 Find a villager with that job
3 Air for emerald?

### Debug Crash Log

its not a crash

**Comment by TeamSpen210** [comment]
As mentioned in the template, hold down F3 + C for 10 seconds, which will force the game to crash. That way we have your full mod list, computer info, etc. It might also be good to run `/data get entity @e[type=minecraft:villager, sort=nearest, limit=1]`, to dump the closest villager's NBT data to the log so we can see the actual trade data.

**Comment by BluSunrize** [comment]
Likely you have a mod that is breaking Tags in some manner.

Can you reproduce this in a world with just IE installed?

**Comment by Acat1234** [comment]
Probably not idk

**Comment by BluSunrize** [comment]
Well if you can't be bothered to help debug this, then I see no reason to keep this issue open.
