### ISSUE TITLE
Assemblers and Item Routers not accepting items via conveyor belts

### ISSUE THREAD

**Issue by Ayrrow** [BluSunrize/ImmersiveEngineering#565]
**This issue is also present in the item router**

tried multiple items, both those in recipes and those without. Had a functioning output. Items just bounce back (see third image)

![2015-11-02_23 59 45](https://cloud.githubusercontent.com/assets/7918443/10882514/85706f04-81bf-11e5-94ec-7ac3891e4919.png)

![2015-11-02_23 59 47](https://cloud.githubusercontent.com/assets/7918443/10882513/856fd2c4-81bf-11e5-985b-4fd1d4272b5d.png)

![2015-11-03_00 00 45](https://cloud.githubusercontent.com/assets/7918443/10882527/99615dfc-81bf-11e5-909e-e9e1ce7d273c.png)

![2015-11-03_11 16 22](https://cloud.githubusercontent.com/assets/7918443/10898218/68e5c750-821c-11e5-8c64-ad9441dd1e3c.png)

**Comment by Ayrrow** [comment]
Breaking and replacing the connecting conveyor belt seems to fix this issue.

**Comment by nigraforce** [comment]
I experience problems with Assemblers too. However, I managed to fix(by breaking & replacing conveyor belts) the Assembler that did not take iron ingots. BUT, I could not fix the cobblestone compressing one. Moreover, it started taking items from the back!(you can see the orange dot)
Maybe it has something to do with the fact that I built that one using BuildCraft? HOWEVER, I broke it many times and rearranged & replaced conveyor belts, so I dunno.
![2015-11-02_18 07 17](https://cloud.githubusercontent.com/assets/9677869/10886461/f9d4f764-81a3-11e5-8206-0c8383389f96.png)
![2015-11-02_18 07 57](https://cloud.githubusercontent.com/assets/9677869/10886463/f9f3a966-81a3-11e5-8310-b1790ed30d73.png)
![2015-11-02_18 08 04](https://cloud.githubusercontent.com/assets/9677869/10886464/fa061344-81a3-11e5-8e79-228bef82819b.png)
![2015-11-02_20 51 09](https://cloud.githubusercontent.com/assets/9677869/10886465/fa071492-81a3-11e5-991c-88922381d3e9.png)
![2015-11-02_20 51 10](https://cloud.githubusercontent.com/assets/9677869/10886466/fa0c222a-81a3-11e5-8d90-c8a1e5c3b6b6.png)

**Comment by nigraforce** [comment]
Well, somehow, after some resets, the second assembler started taking items in.
