### ISSUE TITLE
Client and Server Crash while Industrial Hemp Seed entity floats in water.

### ISSUE THREAD

**Issue by AbandonedPlayer** [BluSunrize/ImmersiveEngineering#5650]
### Minecraft Version

1.19.2

### Immersive Engineering Version

ImmersiveEngineering-1.19.2-9.2.0-162

### How did it happen?

While using a bonemeal farm the industrial hemp seeds spawn after using bonemeal on stone, when stone turns into moss and gets crush there's a chance that "industrial Hemp Seeds" spawn and get pushed by flowing water into hoppers. When this happens it crashes both the server and client side.
What can be done:
Add a way to remove the chance of industrial hemp seeds to spawn when using bonemeal on stone, grass or dirt. Make a recipe to turn wheat seeds into hemp seeds with Creosote Oil.

Client Log:
https://gist.github.com/AbandonedPlayer/f07ea3de35e53d49249985c6eedd19ac
Server Log:
https://gist.github.com/AbandonedPlayer/1336fbd1f2854e313916c965f8ddce3d

### Crash Log

Crash Logs in description

**Comment by BluSunrize** [comment]
Update IE, this should be fixed in the newest 1.19.2 release.
