### ISSUE TITLE
Some type of armor for this mod that the tinkering table can modify

### ISSUE THREAD

**Issue by Acat1234** [BluSunrize/ImmersiveEngineering#5652]
### Explain your idea

1. It would be nice if there is armor for immersive engineering that can be modified with the tinkering station.
2. Can it be like the mekasuit in ways like you won't take damage if its charged and its add-ons with the station would make it neat.
3. The armors added from the mod can't be modified with the tinkering station.
Please?

**Comment by BluSunrize** [comment]
If I had a model for a power armor, I would have added it a long time ago.

But I don't, and modeling good looking 3d armor for Minecraft is extremely difficult, so I mostly gave up on it.
