### ISSUE TITLE
[Suggestion] Ideas for new shaders

### ISSUE THREAD

**Issue by ColonelGerdauf** [BluSunrize/ImmersiveEngineering#5655]
### Explain your idea

Here are some concepts I have in mind:

- Crocea Mors - white with gold/bronze accents - based on the like weapon worn by Jaune Arc in RWBY
- Hush - white with brown and pink accents - based on the character Neopolitan from RWBY
- Frostbite - white with cyan/periwinkle accents - based on common fictional depictions of settings and characters themed around the deep tundra
- Unstable - random colours all over the place without gradient transitions - basically the depiction of glitch art
- [name TBD] - black with gold accents - based on many things, but in particular the classic impression of the rich and posh

**Comment by BluSunrize** [comment]
- Not doing any more RWBY.
- Frostbite feels like it doesn't add a whole lot, plus we already have an ice-themed shader
- Unstable is a nightmare to implement, shaders aren't designed to "change" colours

Sorry, IE's Shaders are very much a passion project for me, none of those wow me.

**Comment by ColonelGerdauf** [comment]
Fair enough. I am at least pleased to offer suggestions.
