### ISSUE TITLE
Just Enough Item crash with Immersive Enginneering. ( Minecraft : Forge 1.19.2 fml 43.2.xx)

### ISSUE THREAD

**Issue by Le-noirrateur** [BluSunrize/ImmersiveEngineering#5657]
### Minecraft Version

1.19.2

### Immersive Engineering Version

Version : 9.2.1-164

### How did it happen?

Hello,

I am here to report a crash from immersive Engineering ( it's been a lot of time that crash ), so when i search item or scroll on the JEI menu, some time ( only if there a item of IE[Immersive Engineering] i think ), **the game crash.**

I have a mod that protect the game from closing if crash but if **IE** crash, **that cause a new problem**.
That a little annoying because i need to restart the game if IE crash and there 234 mods so it's take a lot of time.

Thanks you for reading.

### Client Informations : 

- Version : Forge 1.19.2 fml 43.2.8
- Mods who crash : Immersive Engineering, Just Enough Advancements, Just Enough Item, Mekanism. **_( before adding JEA, only IE was crashing. )_**
- Crash Reason : Rendering item.
- RAM allocated : 12288

### Crash Log

https://pastebin.com/ws4chcE4

**Comment by Le-noirrateur** [comment]
Me again,
I think **Optifine** help to make crash IE ( i checked the logs ).

**Comment by malte0811** [comment]
Known issue, fully on Optifine's side.
