### ISSUE TITLE
Pump not pulling fluids from Railcraft Steel Tank

### ISSUE THREAD

**Issue by Ayrrow** [BluSunrize/ImmersiveEngineering#566]
As per title. Pump does not have issues pulling from an Automagy Thirsty Tank. 

![2015-11-03_00 20 48](https://cloud.githubusercontent.com/assets/7918443/10882688/e65f7b2e-81c0-11e5-9dd6-082ee81907b1.png)

![2015-11-03_00 20 50](https://cloud.githubusercontent.com/assets/7918443/10882689/e662e728-81c0-11e5-9ef8-eb0b91e00f9f.png)

![2015-11-03_00 21 04](https://cloud.githubusercontent.com/assets/7918443/10882690/e664082e-81c0-11e5-97ec-6f43db8c6d0d.png)

Pump is set to blue on the same side as the tank.

**Comment by cobra** [comment]
It's neither the pump nor the railcraft tanks which cause this. It's the same pipe bug causing all kinds of brokenness - will be fixed by PR #556.

**Comment by BluSunrize** [comment]
Shoudl be fixed
