### ISSUE TITLE
[Suggestion] Iris and Oculus flywheel Comapct: compatibilities with the IE

### ISSUE THREAD

**Issue by T0matoKing** [BluSunrize/ImmersiveEngineering#5662]
### Explain your idea

It could be fun if the IE and Iris had a compatibility so it could make it much more beautiful and realistic lighting. example so like having windmills doesn't disappear, but instead u can see it and it has a shadow when its mowing around generating power.

**Comment by BluSunrize** [comment]
No, I have no interest in supporting any of the shader mods because they tend to break a lot of rendering!
