### ISSUE TITLE
Sawblade/drill head disappearing

### ISSUE THREAD

**Issue by Acat1234** [BluSunrize/ImmersiveEngineering#5663]
### Minecraft Version

1.19.2

### Immersive Engineering Version

9.2.1-164

### Expected Behavior

For it to not disappear.

### Actual Behavior

It disappeared.

### Steps to reproduce

1. I Put the drill head/sawblade on their tools.
2. (Only happens in creative mode so enters creative mode)
3. Opens Inventory
4. Where did the drill go? (Sawblade included)
5. The other addons like saw quiver and stuff will disappear however the item looks like it has them still on it.

### Debug Crash Log

I don't know how ok.

**Comment by BluSunrize** [comment]
Yep. Forge issue with creative mode. Nothing we can do about it.

Also, the issue template gives you a precise instruction for how to generate a debug crash, please read it next time.

**Comment by SteelTigerV2** [comment]
this happens to some times when logging into my server
also happens with engineers toolbox

**Comment by mindforger** [comment]
„Me too“ messages on a answered, closed, incomplete, unresolveable issues wont help anybody. Only if you have any real new information or a solution. If you think this happens outside of the described situation, make a new issue and follow the template and add a link to this issue please
