### ISSUE TITLE
Crash when opening inventory after viewing survey result [1.18.2]

### ISSUE THREAD

**Issue by MaxWasUnavailable** [BluSunrize/ImmersiveEngineering#5665]
### Minecraft Version

1.18.2

### Immersive Engineering Version

1.18.2-8.4.0-161

### How did it happen?

Have seismic result. Select it on hotbar to view it. Open inventory. Crash.

Quite likely to be an incompatibility with another mod, though not the faintest clue as to which one it could be. Hoping the logs mean more to you.

### Crash Log

https://gist.github.com/MaxWasUnavailable/69a9269b0e1e1c2ded1dc7c178e0ad8d

**Comment by BluSunrize** [comment]
We don't support Rubidium.

You can try and update it to see if that fixes it.
