### ISSUE TITLE
accumulator backpack banner not showing  

### ISSUE THREAD

**Issue by mocinnno** [BluSunrize/ImmersiveEngineering#5668]
### Minecraft Version

1.19.2

### Immersive Engineering Version

9.2.1

### Expected Behavior

banner would show up on the backpack as a flag of some sort

### Actual Behavior

it doesnt show up when equipped 

### Steps to reproduce

1 put backpack in engineers table
2 put banner on backpack
3 put it on

### Debug Crash Log

https://bytebin.lucko.me/RaA3gievvH

**Comment by BluSunrize** [comment]
Can you reproduce this issue without Rubidium?

**Comment by mocinnno** [comment]
> Can you reproduce this issue without Rubidium?

omg yes that was the problem okay i will talk to my admin and see if he can disable it

**Comment by mocinnno** [comment]
wait do i have to disable it or is there a setting he can turn off

**Comment by BluSunrize** [comment]
No idea! Talk to the Rubdium people about it.
You probably will have to just disable it.
