### ISSUE TITLE
Crashing after placing engineer's blueprint inside engineer's workbench.

### ISSUE THREAD

**Issue by Kiri321** [BluSunrize/ImmersiveEngineering#5669]
### Minecraft Version

1.18.2

### Immersive Engineering Version

ImmersiveEngineering-1.18.2-8.4.0-161

### How did it happen?

When I placed engineer's blueprint inside engineer's workbench game instantly crashed, with crash report and console.
After rejoining world crashes.

### Crash Log

https://pastebin.com/fSgG1QD7

**Comment by HunterBecomeMonke** [comment]
I'm having this exact same issue, posted it on the forum for the modpack i'm running but nobody has responded yet.

**Comment by HunterBecomeMonke** [comment]
If you are using shaders, and have VBO set to false in the config, that is what is probably causing it. I was having the same issue, set VBO to true and it fixed itself. It is very annoying however since windmills & waterwheels are invisible with shaders and w/o VBO on

**Comment by BluSunrize** [comment]
Optifine is not supported.
