### ISSUE TITLE
Crash on mob spawn

### ISSUE THREAD

**Issue by nigraforce** [BluSunrize/ImmersiveEngineering#567]
I load the world, and seconds later game crashes. 

http://pastebin.com/iKLXx1Qj

**Comment by mindforger** [comment]
either synchronize and guard the fakelight calls to `interdictionTiles` or make it CME safe with youknowwhat :D  .. but this can cause superstrage light updates this time, i would not recommend it!

better you take care of the iteration process beeing paused while you are adding and removing stuff from that list!

**Comment by BluSunrize** [comment]
can someone please tell me why the fuck we keep getting CMEs in a singlethreaded videogame ._______.

**Comment by AEnterprise** [comment]
mc itself is singlethreaded yes, but there are mods like fastcraft (and plenty of others) that use another thread to minimize impact on tps

**Comment by mindforger** [comment]
you should've seen me rage when i did my "practical semester" (praxis-semster) when physical dual cores were rising and i had to deal with real multithreading :D

**Comment by mindforger** [comment]
this should help, but i still would prefere a set of public funtions and remove the public visible inderdictionTiles to prevent malicious access in the future!

but still be aware, the use of synchronized inside the event methode is prone to lockups to your other update methodes and also can cause a bit load, this should be monitored with some other mod spawners around (prefereably spawners on steroids, ... no this is not a mod... i meant heavily buffed spawnrates and preferably with extra utils "cursed earth"

**Comment by XFactHD** [comment]
@mindforger you could use a vanilla spawner and edit the NBT data with InGameNBTEdit.

**Comment by mindforger** [comment]
i am pretty sure they are synchronised already, it's more the interoperability with other mod spawners, especially those like extra utils cursed earth, where is no actual single spawner tile entity present, every dirt block is a spawner there

**Comment by XFactHD** [comment]
You can change almost everything on vanilla spawners.
