### ISSUE TITLE
Game crashes when coming near Engineers Workbench with Blueprint inside.

### ISSUE THREAD

**Issue by Ennardbear** [BluSunrize/ImmersiveEngineering#5671]
### Minecraft Version

1.18.2

### Immersive Engineering Version

8.4.0-161

### How did it happen?

A friend and myself played on a Server with Immersive Engineering, when he tried putting the specialized projectiles Blueprint into the Engineers Workbench the game crashed, when i came near the workbench my game crashed as well, this doesnt crash the server tho. Now if we try to get back into the Server our games crash all the time, even after removing all my options and restarting the server the issue was not resolved.

Thanks to anyone who is willing to help us.

### Crash Log

https://pastebin.com/G8ufKRGJ

**Comment by mindforger** [comment]
remove optifine, it is not supported, this issue should be well known by now please check closed issues next time :)

**Comment by malte0811** [comment]
Exactly that^.
