### ISSUE TITLE
[Suggestion] ... Add config to revert Crusher Recipe for Raw materials to be pre 1.17 (with ore-doubling)

### ISSUE THREAD

**Issue by paulbevz** [BluSunrize/ImmersiveEngineering#5672]
### Explain your idea

Or a way to configure the probability of the chance of doubling the ore would be great, the mod is like ridiculously underpowered now and there isn't a clear way of setting the RF used per ore for CraftTweaker

**Comment by BluSunrize** [comment]
You can do this yourself with a datapack.

Config options for recipes are extremely messy due to the order in which things are loaded, so we don't do them.

**Comment by paulbevz** [comment]
How do I go about doing this? Sorry for the trouble

**Comment by paulbevz** [comment]
Thank you for your response

**Comment by BluSunrize** [comment]
https://minecraft.fandom.com/wiki/Data_pack
