### ISSUE TITLE
Dropping Conveyor Belt flinging items out 

### ISSUE THREAD

**Issue by Qhn-bncyqy** [BluSunrize/ImmersiveEngineering#5673]
### Minecraft Version

1.19.2

### Immersive Engineering Version

9.2.1-164

### Expected Behavior

Basically, I was trying to automate steel production in the Improved Blast Furnace using a Dropping Conveyor Belt, if it had a slot, it would drop, if it was full, it would continue the Conveyor Belt chain in a loop

### Actual Behavior

What _actually_ happens is that the item gets flung out when the Furnace is full
https://user-images.githubusercontent.com/45434552/236036026-5aa1438a-dba4-41da-a7ce-00cfe19026e5.mp4

I have tried different containers, it works with a chest, but does the same thing with a hopper

I'm using this as a workaround, for those who might run into the same problem:
![image](https://user-images.githubusercontent.com/45434552/236037431-68a057ec-7cfc-4c03-a357-40c5c9942a0a.png)

### Steps to reproduce

1. Build Improved Blast Furnace (Or Hopper)
2. Put the Dropping Conveyor Belt on top of it
3. Fill the Blast Furnace or Hopper with items so as the Iron and Coal Coke can't get in
4. Connect a stream of Iron and/or Coal Coke to it

### Debug Crash Log

https://paste.ee/p/GcgjP

**Comment by BluSunrize** [comment]
I can reproduce this and will try to figure out the cause and fix
