### ISSUE TITLE
Crash When Placing Item Transporter on Conveyor Belt

### ISSUE THREAD

**Issue by 0xhayleydev** [BluSunrize/ImmersiveEngineering#5675]
### Minecraft Version

1.19.2

### Immersive Engineering Version

9.2.1-164

### How did it happen?

Steps to reproduce:
1. Place conveyor belt headed into a chest
2. Place an Item Transporter onto the chest
3. Game crash

Notes:
- Playing ATM8
- Using MultiMC
- Playing on a multiplayer server

Video for reference:
https://youtu.be/2qFR-2BJF9I

### Crash Log

https://paste.ee/p/Ing6m

**Comment by 0xhayleydev** [comment]
I just realised that this is not right mod. Oops. Sorry

**Comment by mindforger** [comment]
please paste ONLY the crashlog not the whole logfile when creating the issue, spare our scroll wheels ;p
