### ISSUE TITLE
[1.19.2] Entity Ticking Crash Mixer/HV Network

### ISSUE THREAD

**Issue by therealpro101** [BluSunrize/ImmersiveEngineering#5679]
### Minecraft Version

1.19.2

### Immersive Engineering Version

1.19.2-9.2.1-164

### How did it happen?

I used a thermal generator with uranium and blue ice, then hooked up a mixer to the power network using a hv wire and a pump, now everytime i boot the world it makes me crash, i believe its a entity ticking crash. Feel free to confirm, how would one go about me fixing this or avoiding it.

### Crash Log

https://pastebin.com/CG2T0z4i

**Comment by therealpro101** [comment]
Just say something in earlier post so i tried removing rubidium and still no luck. (I understand its not a model issue but figured i give it a shot)

**Comment by BluSunrize** [comment]
Please provide the contents of the `serverconfig/immersiveengineering-server.toml` file in your world folder

**Comment by therealpro101** [comment]
Understood, here you go. https://pastebin.com/ywdXpGsi

**Comment by BluSunrize** [comment]
Can you try reducing the `timeModifier` in `machines.mixer` to 1 and see if that fixes it?

**Comment by therealpro101** [comment]
I did the fix you recomended it still crashed when loading the world, it did get farther in loading (could hear game sound for a bit). Here is the crash log for post-fix https://pastebin.com/cbZnMKit

**Comment by therealpro101** [comment]
Edit, im a dummy i changed the one for the game default not the world itself, thanks so much for the help. I hope you have a good day! Thanks for deving the mod and your time.
