### ISSUE TITLE
Texture Error

### ISSUE THREAD

**Issue by 63502** [BluSunrize/ImmersiveEngineering#568]
I found a few texture errors with v0.6.0.
These are just some examples, all of the glitched items can be found in NEI.

![2015-11-02_12 39 37](https://cloud.githubusercontent.com/assets/15267053/10889314/4ea9f310-815f-11e5-85c3-9dfa19a67ed3.png)
![2015-11-02_12 40 09](https://cloud.githubusercontent.com/assets/15267053/10889316/50670634-815f-11e5-9826-0c346bf7e397.png)

**Comment by cobra** [comment]
optifine? fastcraft?

**Comment by 63502** [comment]
fastcraft-1.21 and OptiFine_1.7.10_HD_U_C1

**Comment by cobra** [comment]
remove/deactivate them, and test again please. Can't debug anything with that stuff.

**Comment by 63502** [comment]
Removed Optifine and fastcraft, ran minecraft, got crash.

---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 11/2/15 12:58 PM
Description: Registering texture

java.lang.AbstractMethodError: blusunrize.immersiveengineering.client.models.ModelIEObj.getBlockIcon(Ljava/lang/String;)Lnet/minecraft/util/IIcon;
	at blusunrize.immersiveengineering.client.ClientEventHandler.rebindUVsToIcon(ClientEventHandler.java:139)
	at blusunrize.immersiveengineering.client.ClientEventHandler.textureStich(ClientEventHandler.java:113)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_428_ClientEventHandler_textureStich_Post.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.client.ForgeHooksClient.onTextureStitchedPost(ForgeHooksClient.java:276)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:303)
	at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:90)
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(SourceFile:72)
	at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(SourceFile:136)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:143)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:617)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:327)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at blusunrize.immersiveengineering.client.ClientEventHandler.rebindUVsToIcon(ClientEventHandler.java:139)
	at blusunrize.immersiveengineering.client.ClientEventHandler.textureStich(ClientEventHandler.java:113)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_428_ClientEventHandler_textureStich_Post.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.client.ForgeHooksClient.onTextureStitchedPost(ForgeHooksClient.java:276)
	at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:303)
	at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:90)

-- Resource location being registered --
Details:
	Resource location: minecraft:textures/atlas/blocks.png
	Texture object class: net.minecraft.client.renderer.texture.TextureMap
Stacktrace:
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(SourceFile:72)
	at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(SourceFile:136)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SimpleReloadableResourceManager.java:143)
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SimpleReloadableResourceManager.java:121)
	at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:617)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:327)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 243656552 bytes (232 MB) / 891813888 bytes (850 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 127 mods loaded, 127 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHIJA	technomCore{0.12.0A} [Technomancy Core] (minecraft.jar) 
	UCHIJA	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UCHIJA	WitchingGadgetsCore{1.1.10} [Witching Gadgets Core] (minecraft.jar) 
	UCHIJA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJA	ExpandedIndustry{10.17.0a} [Expanded Industry] (1.7.10-ExpandedIndustry-10.17.0a.jar) 
	UCHIJA	DamageIndicatorsMod{3.2.3} [Damage Indicators] ([1.7.10]DamageIndicatorsMod-3.2.3.jar) 
	UCHIJA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJA	bdlib{1.9.3.107} [BD Lib] (bdlib-1.9.3.107-mc1.7.10.jar) 
	UCHIJA	ae2stuff{0.3.1.33} [AE2 Stuff] (ae2stuff-0.3.1.33-mc1.7.10.jar) 
	UCHIJA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJA	AppleCore{1.1.0} [AppleCore] (AppleCore-mc1.7.10-1.1.0.jar) 
	UCHIJA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJA	ImmersiveEngineering{0.6.0} [Immersive Engineering] (ImmersiveEngineering-0.6.0.jar) 
	UCHIJA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJA	arcane_engineering{0.1.1} [Arcane Engineering] (arcane_engineering-0.1.1.jar) 
	UCHIJA	arcanearteries{5} [Arcane Arteries] (ArcaneArteries0.7.2.jar) 
	UCHIJA	armoroverlay{2.0} [Armor Overlay] (Armor Overlay 2.0.jar) 
	UCHIJA	ATG{0.10.0} [Alternate Terrain Generation] (ATG-1.7.10-0.12.0.jar) 
	UCHIJA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJA	Automagy{0.26.3} [Automagy] (Automagy-1.7.10-0.26.3.jar) 
	UCHIJA	hud{1.1a} [Better HUD] (Better HUD by NukeDuck [1.7.10][1.1a].zip) 
	UCHIJA	betterstorage{0.13.1.126} [BetterStorage] (BetterStorage-1.7.10-0.13.1.126.jar) 
	UCHIJA	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-17.jar) 
	UCHIJA	Botania{r1.7-228} [Botania] (Botania r1.7-228.jar) 
	UCHIJA	IC2{2.2.791-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.791-experimental.jar) 
	UCHIJA	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-511.jar) 
	UCHIJA	ForbiddenMagic{1.7.10-0.57} [Forbidden Magic] (Forbidden Magic-1.7.10-0.57.jar) 
	UCHIJA	guideapi{1.7.10-1.0.1-20} [Guide-API] (Guide-API-1.7.10-1.0.1-20.jar) 
	UCHIJA	BloodArsenal{1.2-3} [Blood Arsenal] (BloodArsenal-1.7.10-1.2-3.jar) 
	UCHIJA	ChestTransporter{2.0.2} [Chest Transporter] (ChestTransporter-2.0.2-MC1.7.10.jar) 
	UCHIJA	ChickenChunks{1.3.4.16} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.16-universal.jar) 
	UCHIJA	DummyCore{1.13} [DummyCore] (DummyCore1.13.jar) 
	UCHIJA	DynamicLights{1.3.7} [Dynamic Lights] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_dropItems{1.0.7} [Dynamic Lights EntityItem Module] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_mobEquipment{1.0.7} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_floodLights{1.0.1} [Dynamic Lights Flood Light] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_otherPlayers{1.0.7} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJA	DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJA	EMT{1.2.2} [Electro-Magic Tools] (ElectroMagicTools-1.2.2[1.7.10].jar) 
	UCHIJA	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UCHIJA	Enchiridion{1.1} [Enchiridion] (Enchiridion-1.7.X-1.2b.jar) 
	UCHIJA	weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar) 
	UCHIJA	exparmory{1.3.4} [Expanded Armory] (ExpandedArmory-1.7.10-1.3.4.jar) 
	UCHIJA	extracells{2.2.73} [Extra Cells 2] (ExtraCells-1.7.10-2.2.73b129.jar) 
	UCHIJA	farseek{1.0.9} [Farseek] (Farseek-1.0.9.jar) 
	UCHIJA	fastleafdecay{1.3} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.3.jar) 
	UCHIJA	gadomancy{1.0.2} [Gadomancy] (gadomancy-1.7.10-1.0.2.jar) 
	UCHIJA	ganysend{1.11.1} [Gany's End] (Ganys End-1.11.1.jar) 
	UCHIJA	ganysnether{1.8.1} [Gany's Nether] (Ganys Nether-1.8.1.jar) 
	UCHIJA	ganyssurface{1.12.6} [Gany's Surface] (Ganys Surface-1.12.6.jar) 
	UCHIJA	haggismod{1.3.6-mc1.7.10} [AWH Haggis Mod!] (haggismod-1.3.6-mc1.7.10.jar) 
	UCHIJA	HardcoreDarkness{1.7} [Hardcore Darkness] (HardcoreDarkness-MC1.7.10-1.7.jar) 
	UCHIJA	HopperDuctMod{1.3.2} [Hopper Ducts] (hopperductmod-1.7.10-1.3.2.jar) 
	UCHIJA	Ic2Nei{1.0} [IC2 Nei Plugin] (IC2 Nei Plugin Version 1.0.7.jar) 
	UCHIJA	ImLookingAtBlood{1.1} [I'm Looking At Blood] (ImLookingAtBlood-1.7.2-1.1a.jar) 
	UCHIJA	immersiveintegration{0.5.4} [Immersive Integration] (immersiveintegration-0.5.4.jar) 
	UCHIJA	inventorytweaks{1.59-dev-156-af3bc68} [Inventory Tweaks] (InventoryTweaks-1.59-dev-156.jar) 
	UCHIJA	lodeloader{1.1} [Lode Loader] (lodeloader-1.1.jar) 
	UCHIJA	MagiaNaturalis{0.1.1} [§2Magia Naturalis] (MagiaNaturalis-1.7.10-0.1.2c.jar) 
	UCHIJA	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UCHIJA	Mariculture{1.7.10-1.2.4.2a} [Mariculture] (Mariculture-Deluxe-1.7.10-1.2.4.2a.jar) 
	UCHIJA	MariTech{1.0} [Marine Technlogy] (Mariculture-Deluxe-1.7.10-1.2.4.2a.jar) 
	UCHIJA	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
	UCHIJA	MTRM{1.0} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.7.10-1.1.0.11.jar) 
	UCHIJA	morehealth{6.0} [More Health Forge] (More Health Enchanted-1.7.10-6.0.zip) 
	UCHIJA	MultiPageChest{1.3.4} [Multi Page Chest] (MultiPageChest-1.3.4-MC1.7.10.jar) 
	UCHIJA	MutantCreatures{1.4.9} [Mutant Creatures] (MutantCreatures-1.7.10-1.4.9.jar) 
	UCHIJA	NEIAddons{1.12.13.38} [NEI Addons] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJA	NEIAddons|Developer{1.12.13.38} [NEI Addons: Developer Tools] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJA	NEIAddons|AppEng{1.12.13.38} [NEI Addons: Applied Energistics 2] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJA	NEIAddons|Botany{1.12.13.38} [NEI Addons: Botany] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJA	NEIAddons|Forestry{1.12.13.38} [NEI Addons: Forestry] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJA	NEIAddons|CraftingTables{1.12.13.38} [NEI Addons: Crafting Tables] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJA	NEIAddons|ExNihilo{1.12.13.38} [NEI Addons: Ex Nihilo] (neiaddons-1.12.13.38-mc1.7.10.jar) 
	UCHIJA	neiintegration{1.0.12} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.12.jar) 
	UCHIJA	NodalMechanics{1.7.10R1.0} [NodalMechanics] (NodalMechanics-1.7-1.0-7.jar) 
	UCHIJA	recipehandler{0.2} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.2(1.7.10).jar) 
	UCHIJA	notenoughkeys{@MOD_VERSION@} [NotEnoughKeys] (NotEnoughKeys-1.7.10-3.0.0b42-universal.jar) 
	UCHIJA	neresources{0.1.0.106} [Not Enough Resources] (NotEnoughResources-1.7.10-0.1.0.106.jar) 
	UCHIJA	NOVA{2015-10-09} [NOVA] (NOVA-2015-10-09-universal.jar) 
	UCHIJA	clayspawn{1.7.10a} [Pam's Clay Spawn] (Pam's Clay Spawn 1.7.10a.jar) 
	UCHIJA	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
	UCHIJA	PowerConverters3{1.7.10-2.10} [Power Converters 3] (PowerConverters-1.7.10-2.10.jar) 
	UCHIJA	libsandstone{1.0.0} [libsandstone] (LibSandstone-1.0.0-Release.jar) 
	UCHIJA	xreliquary{1.2} [Reliquary] (Reliquary-1.2-Release.jar) 
	UCHIJA	rftools{4.00} [RFTools] (rftools-4.00.jar) 
	UCHIJA	rope{${version}} [Rope Exploration Pack Mod] (Rope Exploration Pack v1.1.2.jar) 
	UCHIJA	SaltMod{1.4.a} [Salty Mod] (SaltyMod-1.7.10-1.4.a.jar) 
	UCHIJA	Sanguimancy{1.7.10-1.1.9-31} [Sanguimancy] (Sanguimancy-1.7.10-1.1.9-31.jar) 
	UCHIJA	Scenter{1.7.10-3.2.0} [Scenter] (scenter-1.7.10-3.2.0.jar) 
	UCHIJA	DP_SimpleFlight{0.8} [Simple Flight] (simpleflight-0.8.jar) 
	UCHIJA	soundfilters{0.8_for_1.7.X} [Sound Filters] (SoundFilters-0.8_for_1.7.X.jar) 
	UCHIJA	SparksHammers{1.7.10-1.2.1} [Spark's Hammers] (SparksHammers-1.7.10-1.2.1.jar) 
	UCHIJA	StorageDrawers{1.7.10-1.6.2} [Storage Drawers] (StorageDrawers-1.7.10-1.6.2.jar) 
	UCHIJA	StorageDrawersMisc{1.7.10-1.0.1} [Storage Drawers: Misc Pack] (StorageDrawers-Misc-1.7.10-1.0.1.jar) 
	UCHIJA	streams{0.1.5} [Streams] (Streams-0.1.5.jar) 
	UCHIJA	TaintedMagic{1.1.5.7} [Tainted Magic] (TaintedMagic-1.1.5.7.jar) 
	UCHIJA	tcnodetracker{1.1.2} [TC Node Tracker] (tcnodetracker-1.7.10-1.1.2.jar) 
	UCHIJA	ThaumcraftMobAspects{1.7.2-2A} [Thaumcraft Mob Aspects] (ThaumcraftMobAspects-1.7.2-2A.jar) 
	UCHIJA	thaumicbases{1.3.1710.2} [Thaumic Bases] (ThaumicBases-1.3.1710.4.jar) 
	UCHIJA	thaumicenergistics{0.8.10.10} [Thaumic Energistics] (thaumicenergistics-0.8.10.10.jar) 
	UCHIJA	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-53.jar) 
	UCHIJA	ThaumicHorizons{1.1.5} [Thaumic Horizons] (thaumichorizons-1.7.10-1.1.6.jar) 
	UCHIJA	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
	UCHIJA	TML{4.0.1} [TooMuchLoot] (TooMuchLoot-1.7.10-4.0.1.B0.jar) 
	UCHIJA	TravellersGear{1.16.6} [Traveller's Gear] (TravellersGear-1.7.10-1.16.6.jar) 
	UCHIJA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCHIJA	VeinMiner{0.30.0_build.unknown} [Vein Miner] (VeinMiner-1.7.10_0.30.0.unknown.jar) 
	UCHIJA	VeinMinerModSupport{0.30.0_build.unknown} [Mod Support] (VeinMiner-1.7.10_0.30.0.unknown.jar) 
	UCHIJA	wawla{1.3.2} [What Are We Looking At] (Wawla-1.3.2-1.7.10.jar) 
	UCHIJA	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCHIJA	WitchingGadgets{1.1.10} [Witching Gadgets] (WitchingGadgets-1.7.10-1.1.10.jar) 
	UCHIJA	zoom{1.0.0} [Zoom] (Zoom-MC1.7.10-1.0.0.jar) 
	UCHIJA	technom{0.12.0A} [Technomancy] (Technomancy - 0.12.1C - 1.7.10.jar) 
	UCHIJA	recycling{1.0.3.6} [Thermal Recycling] (ThermalRecycling-1.7.10-1.0.3.6.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.2.0 - Build 10.18.10.3316' Renderer: 'Intel(R) HD Graphics 4400'
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.0.3-303
	ThermalFoundation: -[1.7.10]1.2.0-102
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	ThermalDynamics: -[1.7.10]1.1.0-161
	List of loaded APIs: 
		* API_NEK (1.2.0) from NotEnoughKeys-1.7.10-3.0.0b42-universal.jar
		* AppleCoreAPI (1.1.0) from AppleCore-mc1.7.10-1.1.0.jar
		* appliedenergistics2|API (rv2) from appliedenergistics2-rv2-stable-10.jar
		* Baubles|API (1.0.1.10) from Baubles-1.7.10-1.0.1.10.jar
		* BloodMagicAPI (1.3.3-13) from BloodMagic-1.7.10-1.3.3-17.jar
		* BotaniaAPI (66) from Botania r1.7-228.jar
		* CoFHAPI (1.7.10R1.0.13B2) from CoFHLib-[1.7.10]1.0.3-175.jar
		* CoFHAPI|block (1.7.10R1.0.13B2) from CoFHLib-[1.7.10]1.0.3-175.jar
		* CoFHAPI|core (1.7.10R1.0.13B2) from CoFHLib-[1.7.10]1.0.3-175.jar
		* CoFHAPI|energy (1.7.10R1.0.13B2) from CoFHLib-[1.7.10]1.0.3-175.jar
		* CoFHAPI|fluid (1.7.10R1.0.13B2) from CoFHLib-[1.7.10]1.0.3-175.jar
		* CoFHAPI|inventory (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|item (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|modhelpers (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHAPI|tileentity (1.7.10R1.0.13B2) from CoFHLib-[1.7.10]1.0.3-175.jar
		* CoFHAPI|transport (1.7.10R1.0.13B2) from CoFHLib-[1.7.10]1.0.3-175.jar
		* CoFHAPI|world (1.7.10R1.0.13B2) from CoFHLib-[1.7.10]1.0.3-175.jar
		* CoFHLib (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.0.3-175.jar
		* CoFHLib|audio (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.0.3-175.jar
		* CoFHLib|gui (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|container (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.0.3-175.jar
		* CoFHLib|gui|element (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|element|listbox (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|gui|slot (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|inventory (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.0.3-175.jar
		* CoFHLib|render (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|render|particle (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|util (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|util|helpers (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.0.3-175.jar
		* CoFHLib|util|position (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|world (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* CoFHLib|world|feature (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
		* com.epm.rope.api.RopeAPI (1.0.0) from Rope Exploration Pack v1.1.2.jar
		* Guide-API|API (1.7.10-1.0.1-20) from Guide-API-1.7.10-1.0.1-20.jar
		* IC2API (1.0) from industrialcraft-2-2.2.791-experimental.jar
		* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.6.0.jar
		* McJtyLib (1.7.0) from mcjtylib-1.7.0.jar
		* neresources|API (1.0) from NotEnoughResources-1.7.10-0.1.0.106.jar
		* RailcraftAPI|crafting (1.0.0) from ImmersiveEngineering-0.6.0.jar
		* Sanguimancy|API (@VERSION@) from Sanguimancy-1.7.10-1.1.9-31.jar
		* StorageDrawersAPI (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.6.2.jar
		* StorageDrawersAPI|config (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.6.2.jar
		* StorageDrawersAPI|event (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.6.2.jar
		* StorageDrawersAPI|inventory (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.6.2.jar
		* StorageDrawersAPI|pack (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.6.2.jar
		* StorageDrawersAPI|registry (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.6.2.jar
		* StorageDrawersAPI|render (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.6.2.jar
		* StorageDrawersAPI|storage (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.6.2.jar
		* StorageDrawersAPI|storage-attribute (1.7.10-1.2.0) from StorageDrawers-1.7.10-1.6.2.jar
		* Thaumcraft|API (4.2.2.0) from Thaumcraft-1.7.10-4.2.3.5.jar
		* TravellersGear|API (1.0) from TravellersGear-1.7.10-1.16.6.jar
		* VeinMinerApi (0.1) from VeinMiner-1.7.10_0.30.0.unknown.jar
		* WailaAPI (1.0) from ImLookingAtBlood-1.7.2-1.1a.jar
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:OFF, BC:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:ON
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4400 GL version 4.2.0 - Build 10.18.10.3316, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [Custom Skin.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by theunkn0wn1** [comment]
Immersive Integration is incompatible with IE 0.6. That is what is causing that particular crash. Known issue... see #555 

Also. Please DO NOT paste the crash log here... pastebin it or something
=============================

**Comment by 63502** [comment]
Sorry about that, I'm not a regular user of github.....or pastebin.......   :\

**Comment by theunkn0wn1** [comment]
Its ok, for future reference, avoid pasting huge walls of text here. It makes the Issue thread harder to read and upsets BluSunrize.

**Comment by 63502** [comment]
Thanks. :)

**Comment by BluSunrize** [comment]
Yeah, what Unknown said. Never do that. Not on github, nor on curseforge, nor in the Minecraft or FTB forums. Crashlogs should ALWAYS be a pastebin/pastee/gist.

Immersive Integration is in the process of being updated, and optifine is a terrible mod that breaks everything.
Issue solved.

**Comment by SHIuSH** [comment]
still get 63502's error even with II 0.6.0(which must support IE0.6.0)
