### ISSUE TITLE
[Suggestion] Stretchy cables or a reel cable. 

### ISSUE THREAD

**Issue by LordRelentless** [BluSunrize/ImmersiveEngineering#5680]
### Explain your idea

I've built a moving contraption by combining Immersive Engineering and Create using a Create addon mod that has an EF/IE compatible electric motor. The problem is when the contraption moves the wire and connector break. This is 1.19.2 current available version. Is it possible to get either a stretchy line set that doesn't break, or a reel system for extensible wires?

**Comment by BluSunrize** [comment]
IE's blocks are not designed to be moved by Create.

**Comment by LordRelentless** [comment]
I'm aware, but that's also the problem, and a simple solution would be to have reel wire that can move without breaking, or a wireless IE energy transmitter and receiver.

**Comment by BluSunrize** [comment]
You can't just "have a wire that moves without breaking". Don't tell me about a "simple solution" when you obviously have *zero* idea of our codebase.

Blocks were **not meant to move**. (Yes, blah blah, vanilla pistons. They can't move BlockEntities, and there's good reason for that).
Create does incredibly hacky shit to make it happen, and the effort for us to be compatible with that is not worth it.

**Comment by LordRelentless** [comment]
So won't even consider adding a wireless FE transmitter, akin to the wireless redstone emitters?

**Comment by BluSunrize** [comment]
No absolutely not.
I'm locking this conversation at this point.
