### ISSUE TITLE
modded mc crash. 1.19.2

### ISSUE THREAD

**Issue by Jasonkami** [BluSunrize/ImmersiveEngineering#5681]
### Minecraft Version

1.19.2

### Immersive Engineering Version

ImmersiveEngineering-1.19.2-9.2.1-164

### How did it happen?

I try to load the game and it says that it failed loading.

### Crash Log

https://gist.github.com/stegi382/5eb0a69cc975c0a09c35ccac7b963464

**Comment by mindforger** [comment]
remove optifine, if the crash persists, please add new crashlog

**Comment by Jasonkami** [comment]
It works now, is there any way to play it with optifine? Because I really like to use shaders.

**Comment by BluSunrize** [comment]
No, optifine is not supported
