### ISSUE TITLE
Server crash with improved blast furnace

### ISSUE THREAD

**Issue by Liiw** [BluSunrize/ImmersiveEngineering#5682]
### Minecraft Version

1.19.2

### Immersive Engineering Version

4.3.0-6

### How did it happen?

Hello!

I am using sparkedhost for my server currently. My friend assembled an "improved blast furnace" and while the multiblock formed and GUI was functional, it was malformed (some blocks were rendering in regular block form inside the multiblock). I inserted iron into the furnace and after inserting fuel, the server crashed. After the crash, we managed to boot the server up and disassemble the furnace. 

I am also attaching a debug log which might help share some more information. I noticed a bunch of text on the server console when the multiblock was formed. 

[debug-1.log.gz](https://github.com/BluSunrize/ImmersiveEngineering/files/11445508/debug-1.log.gz)

forge version is 43.2.10

### Crash Log

https://paste.sparked.host/pisomoqase

**Comment by mindforger** [comment]
canary mod seems to be yet another optimizer mod that causes issues by the first look

**Comment by BluSunrize** [comment]
Please try to reproduce this without Canary

**Comment by Liiw** [comment]
Hello again. After encountering multiple crasher unrelated to the blast furnace issue, I noticed Canary being present in the crash logs often. I have removed Canary from the server and tried the blast furnace again. It worked okay. Assembled without issue and processed the iron. Thank you for your insight! This issue is resolved.
