### ISSUE TITLE
[1.18.2][Suggestion] Railgun Projectile Whitelist Implemented?

### ISSUE THREAD

**Issue by chemlzh** [BluSunrize/ImmersiveEngineering#5683]
### Explain your idea

Recently I have been playing modpack featuring TerraFirmaCraft and TFC + IE crossover, which have a variety of metal rods (copper rods, nickel rods, etc.). In addition, I know thers's a mod called TFC Metallum U (https://github.com/Mrthomas20121-Mods/TFC-Metallum), which implements more metal rods (tungsten rods, tungsten steel rods, uranium rods) that can be used as railgun ammo. 
However, I couldn't find the IE option for adding an item as a new railgun ammo. Therefore I searched the issue of IE, and found a closed issue which has a similar suggestion (https://github.com/BluSunrize/ImmersiveEngineering/issues/3313). It showed that the issue was completed, with no branches or pull requests. So could you tell me whether the railgun projectile whitelist is implemented? If so, how should I do to use this feature?
Thanks.

**Comment by BluSunrize** [comment]
There is an API for the Railgun's projectiles. Any mod developer can add support for their own metal rods.

There will not be a config option, because it's too much variable data to handle with a config.
