### ISSUE TITLE
1.19.2 charging station not accepting items

### ISSUE THREAD

**Issue by MrFidly** [BluSunrize/ImmersiveEngineering#5686]
### Minecraft Version

1.19.2

### Immersive Engineering Version

Major

### Expected Behavior

You should be able to right click with the appropriate item like the buzz saw or mining drill into the charging station and it should be charging if properly powered either via the top or back.

### Actual Behavior

The charging station does hold power and it charges effectively off of a water wheel however when I go to put my mining drill or buzz saw in it to charge up the device I am unable to put it in the charging station and this works also with the battery backpack sorry I didn't get the last terminology right but you know what I mean.

### Steps to reproduce

There are other mods in the pack and I tried this with those mods installed alongside immersive engineering then I disabled all mods but jei and the issue persists. 

### Debug Crash Log

https://pastebin.com/NqXW6RPe

**Comment by BluSunrize** [comment]
The buzzsaw and the drill require biodiesel. They do no t run off of electricity.
As such, you can not charge them in the charging station. This is working as intended.
