### ISSUE TITLE
[Suggestion] Support for Pam's HarvestCraft 2 - Crops in Garden Cloche

### ISSUE THREAD

**Issue by ghost** [BluSunrize/ImmersiveEngineering#5688]
Hello, would it be possible to add support for "Pam's HarvestCraft 2 - Crops" for 1.19.2 in Garden Cloche please ?

**Comment by BluSunrize** [comment]
You can do that yourself with a datapack. Fairly sure there is one on Curseforge already. We're not offering native support.
