### ISSUE TITLE
Assorted Fluid pipe issues

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#569]
Issue[1]
If a IE fluid pipe separates the pump and the source tank, the pump refuses to extract the fluid. If the source tank is directly attached to the pump it extracts just fine, regardless if pipes stand between it and the target tank.

the below does not function as expected (bug inducing)
![image](https://cloud.githubusercontent.com/assets/3110986/10890526/386f25f0-814d-11e5-84b9-e43e857f6fbf.png)
Yet this does work:
![image](https://cloud.githubusercontent.com/assets/3110986/10890535/47eea618-814d-11e5-8825-e4359a06fb7a.png)

====================
Issue[2] Assembler will not accept fluids from IE's pipes. Even if the assembler was configured to execute fluid crafting, it will not accept any input from the pipes.
The below is broken:
![image](https://cloud.githubusercontent.com/assets/3110986/10890839/454b77a4-814f-11e5-8146-d99a35a8d82f.png)

And this works:
![image](https://cloud.githubusercontent.com/assets/3110986/10890826/2d10aa4c-814f-11e5-974b-91e3528e548d.png)

Also: I can verify the pipes will insert into valid tanks, the below test setup has two TE tanks, the top one started full and was set to OUTPUT into the loop below. The lower tank started empty and set to INPUT.
![image](https://cloud.githubusercontent.com/assets/3110986/10890918/ee1b525a-814f-11e5-8491-4d93e8421fc8.png)

=================

Issue[3] Pipes refuse to remain disconnected within scaffolding

If two pipelines are adjacent to one another, but manually disconnected via the hammer, they will revert as one pipeline if a single scaffolding block is placed on the line. Also, even after manually disconnecting the two lines, the pipe embedded within the scaffolding will always render as connected. [video demonstration] (https://youtu.be/FR7DvUc6STY)

===========================
IE build 585f29b
Bare-minimum modded instance.

**Comment by BluSunrize** [comment]
1) Why would a pump be able to pull from the pipe system? At what point did I convey they they could do that? Pumps draw from directly adjacent blocks, nothing more. They are not FluidRetrievalNodes from XU.
2) UUuh...no idea, will check
3) Yeah, placign a scaffold causes a block update. If a fluid handler next to the pipe is changed, it reevaluates its connections. That is semi-intentional and not really fixable, sicne I can't add scaffolding without triggering the update.

**Comment by theunkn0wn1** [comment]
Simple answer, because the below setup, which *should* be modified by the pump, is not.
![image](https://cloud.githubusercontent.com/assets/3110986/10892547/e86924fa-8158-11e5-8bb2-60b1f8ec2e1e.png)
``They can ... insert into pipes at hight pressure, to transfer fluids much faster...``(Fluid Transport,3)
Yet this is not the case, as the fluid in the left tank enters the right tank at the same rate regardless of the pumps presence. Obviously this is because the pump is input limited, it should be able to extract from the left tank over the 3m of piping to expedite the transfer at the cost of more power.



I interpreted the wording ``Pumps can also be used to extract from tanks and other fluid containers...``(4) To include remote fluid containers, such as tanks only meters from the pump itself.

Given the size of the pump, and basic knowledge of what a pump is, it is expected it can retrieve fluids that are exactly 1m away from its input port. due to the vacuum affect pumps apply to function As pumps

imho, IE pumps should act similarly to retrieval nodes from XU because of both their size and asthetic appeal. Other mods, such as TE/TD have the single block pump covered, a multi-block pump just isn't needed for the same functionality. The pipes need not duplicate, but the current functionality does not justify its usage if TE/D are installed

**Comment by theunkn0wn1** [comment]
Also, found a sub-bug of [3].

If two piplelines are placed adjacent, but manually disconnected, and there is scaffolding along the adjacent face, upon world reload the entire adjacent face has reconnected joining the two pipelines together. They loose memory of their connection status.

Setup:

![image](https://cloud.githubusercontent.com/assets/3110986/10893155/27ab2e62-815c-11e5-9331-5afbc0cc4873.png)

Result on world reload:
![image](https://cloud.githubusercontent.com/assets/3110986/10893163/316347c8-815c-11e5-8481-a8d241ea0f86.png)

**Comment by BluSunrize** [comment]
I fixed #2, I'll look at #3 tomorrow.

**Comment by BluSunrize** [comment]
I've taken another look at that fluid tank setup of yours, and yes the pump there is irrelevant, because the pipe at the start limits the throughput. The pump needs to be the one inserting into the system, otherwise it has no effect.

**Comment by theunkn0wn1** [comment]
How the heck do I attach the pump to the silo then? The darn thing is too
tall and it can't bridge a one meter pipe!

**Comment by BluSunrize** [comment]
I made a change in that pipes now use the upper transferlimit (1000), when /inserting/ into pumps. That should make your tank hookhup viable, @theunkn0wn1 =)

**Comment by theunkn0wn1** [comment]
Just tested with 06a63cf,Thank you, this makes the tank setup much more viable. Might I suggest that the pump needs to be powered to utilize the upper transfer rate? otherwise it kinda defeats the purpose if the pump can be unpowered to get the boost the powered pump is designed to provide...

**Comment by BluSunrize** [comment]
See I was unsure of that myself, I'd have to settle on a decent "cost" that isn't too high. After all who wants a designated power setup just to transfer fluids? .~.

**Comment by mindforger** [comment]
doesn't the tank output on itself when given a redstone signal on the lower port ? ... sure i see the visual benefit but hey if it should be visual and immerse, it needs power :D

**Comment by theunkn0wn1** [comment]
*raises hand* I would not mind, after all the pump is a powered device...
Why have the device consume power to extract from tanks itself if the silo,
a tank, can dump at max date just because the input is an unpowered pump?
It is simply inconsistent. IMO it needs to consume power.

**Comment by mindforger** [comment]
*singed

**Comment by BluSunrize** [comment]
There we go, that commit makes hte pump consume power when outputting with pressure =3

cc @theunkn0wn1 @mindforger

**Comment by theunkn0wn1** [comment]
@BluSunrize thanks. 

Of topic: what version of GT are you targeting? I can't get the latest GT dev or src to make IE build since you changed it last, it's as if you are calling to a GT API that does not exist.

**Comment by cobra** [comment]
GT 5 it is.

**Comment by theunkn0wn1** [comment]
Ah, that explains all the things . Thanks cobra.

As for the thread, all my issues (except [1]) have been resolved. No need to keep this open now

**Comment by BluSunrize** [comment]
GregTech 5 unofficial. The dev has a OneDrive with dev versions.
