### ISSUE TITLE
[1.19.4] Breaking a blast furnace deletes the first block broken

### ISSUE THREAD

**Issue by EvergreenSystems** [BluSunrize/ImmersiveEngineering#5691]
### Minecraft Version

1.19.4

### Immersive Engineering Version

1.19.4-9.4.0-186

### Expected Behavior

Breaking a lesser blast furnace should drop all 27 blast brick blocks

### Actual Behavior

Breaking the first block (thus destroying the multiblock) deletes the first blast brick drop, resulting in only 26 blocks being dropped

### Steps to reproduce

1. Form a lesser blast furnace
2. Break one block

### Debug Crash Log

https://gist.github.com/Shedao-Shai/41610f5d6ffd3d3bc591b1df00792cab

**Comment by malte0811** [comment]
It works fine for me. What are you using to break the first block? Does it happen if only IE is installed?
