### ISSUE TITLE
[1.19.4] wires, windmill and waterwheel are broken with rubidium/oculus again

### ISSUE THREAD

**Issue by EvergreenSystems** [BluSunrize/ImmersiveEngineering#5692]
### Minecraft Version

1.19.4

### Immersive Engineering Version

1.19.4-9.4.0-166

### Expected Behavior

In earlier versions windmills (and I believe waterwheels as well) were invisible with rubidium/oculus, however wires were fixed and were still visible.,

### Actual Behavior

This fix has broken again, wires are now invisible when using rubidium and oculus

### Steps to reproduce

1. Load an instance with IE, Rubidium, and Oculus
2. String some wires, and/or place a waterwheel/windmill

### Debug Crash Log

https://gist.github.com/Shedao-Shai/1e0acc82a253e62f78e45b3898a79c86

**Comment by BluSunrize** [comment]
Rubidium and Oculus are not supported.
