### ISSUE TITLE
[Suggestion] Automatic Breakers / Disconnector Switches

### ISSUE THREAD

**Issue by Geocube101** [BluSunrize/ImmersiveEngineering#5693]
### Explain your idea

Three blocks or multiblocks for for each voltage level that can automatically disconnect wires if the transfer exceeds a customizable amount or when a redstone signal is applied. The high voltage variant could be akin to a [substation disconnector switch](https://www.youtube.com/watch?v=C-UTYzfNjKM).

This would save resources during shorts as massive parts of the network won't have to be replaced, as well as adding the ability to programmatically switch parts of the grid on and off.

**Comment by BluSunrize** [comment]
No, wires burning is an intentional mechanic. Trivilaizing it with a breaker would be boring.

As for switching parts of the network off: Redstone Breaker does this already.
