### ISSUE TITLE
[Suggestion] Conductive effect tweaks and fluid/gas grenades

### ISSUE THREAD

**Issue by RandomDovah** [BluSunrize/ImmersiveEngineering#5696]
### Explain your idea

Hello. Recently I've seen that redstone acid provides effect that increases electrical damage which could be useful for dealing damage to your enemies yet I think it needs some tweaks. There are few things that I want to suggest to bring more variability in a fight and make this system work more comfortable:
1. Revolver and shield with electric upgrades also should make stronger damage if enemy is affected by redstone acid. Right now it seems to work only with tesla coil and miniature tesla coil upgrade for capacitor backpack which reduces the value of this effect.
2. Blueprint-crafted reusable fluid/gas grenades which can be filled with various fluids. Player wouldn't need to fill chemical thrower with redstone acid instead of biodiesel or make a multitank instead of large tank upgrade and pull out chem thrower to apply this effect every time.
3. Magnetic ring or bandolier accessory which allows to throw grenades by pressing button instead of taking it in the hand.

**Comment by BluSunrize** [comment]
I'm not adding grenades.

**Comment by RandomDovah** [comment]
I see. Can I know the reason?

**Comment by BluSunrize** [comment]
I don't want to add any more weapons to IE.

**Comment by RandomDovah** [comment]
That's sad to read but alright then
