### ISSUE TITLE
Liquid Transfer Node on a Fermenter

### ISSUE THREAD

**Issue by DoughnutDev** [BluSunrize/ImmersiveEngineering#57]
I get this crash when putting stuff inside the fermenter http://pastebin.com/CQRKDeCW I am using 0.1.16 of IE

**Comment by DoughnutDev** [comment]
http://puu.sh/ihbJ5/21360d77fe.png

**Comment by tjsd** [comment]
how do people get build 0.1.16? There is only build 0.1.9 available.

**Comment by DoughnutDev** [comment]
I have access to the dropbox...

**Comment by DoughnutDev** [comment]
Technically 0.1.9 is not available it is for Blu and Hazard.
