### ISSUE TITLE
[minor] Pipes and Scaffolding...

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#570]
When scaffolding of either type is placed over a fluid pipe, it looses both its collision and its properties. 

This is unexpected, as the scaffolding is a solid 1m cube block, and I expected it to retain the function as a structural ladder. Guess one does not simply climb on piping. :3 

![image](https://cloud.githubusercontent.com/assets/3110986/10891044/8c4b934a-8150-11e5-81ed-979b1c4aaf6f.png)

vs
![image](https://cloud.githubusercontent.com/assets/3110986/10891086/ce57ada0-8150-11e5-98b6-978a29915113.png)

------------------------
IE build 585f29b

**Comment by BluSunrize** [comment]
Fixed this btw. They are climbable now ^^

**Comment by theunkn0wn1** [comment]
Request to reopen this issue, the fix produced a new directly related to the original.

Issue: place a scaffold on a pipe you (the player) is currently standing on. 
Result: Player falls through the pipe and scaffold.

IE 06a63cf

**Comment by BluSunrize** [comment]
Can't help that. That's how Minecraft's updating boundingboxes work.The only remedy would be forcefully shifting the player's position upwards upon placement, which feels very gimicky.
