### ISSUE TITLE
[Suggestion] Adding a way to throttle input to Metal Press?

### ISSUE THREAD

**Issue by toastonrye** [BluSunrize/ImmersiveEngineering#5701]
### Explain your idea

I looked through the book, it seems I could maybe use the item batcher, but I was wondering if there is a more compact way as I'm tight for space.

If I have an extracting conveyor on a chest, to make iron gears at the press, the conveyor will pull all the iron out if I asked for like 500 gears. So most of the iron ingots would despawn. I'd like to be able to "read" a redstone signal from the input of the metal press, to say it's input buffer is full, to disable the extracting conveyor.

**Comment by BluSunrize** [comment]
The Item Batcher exists for this very reason =p
