### ISSUE TITLE
Engineers workbench crashes game when inserting blueprint

### ISSUE THREAD

**Issue by 256noname256** [BluSunrize/ImmersiveEngineering#5702]
### Minecraft Version

1.18.2

### Immersive Engineering Version

8.4.0-161

### Description
There is already a similar case on issues, but there is a reason in the optifine, and there are no graphic mods here .
### Steps to reproduce

1. Create workbench
2. Place workbench
3. Insert blueprint, engineers
4. [Potentially shift click blueprint into workbench(?)]
5. Game should crash

### Crash Log

https://pastebin.com/xPkHsbJQ

**Comment by BluSunrize** [comment]
I see no reason to believe this to be an issue with Immersive Engineering.

The stacktrace mentions Immersive FX, maybe try their issue tracker instead.

**Comment by 256noname256** [comment]
My bad there is another crashlog.
Heres a valid https://pastebin.com/H1T3VgPz

**Comment by mindforger** [comment]
is flywheel something like optifine? it kinda looks like the same crash with optifine

**Comment by XFactHD** [comment]
Flywheel is Create's rendering library. It's not an optimization mod in the sense that OptiFine is (or at least wants to be).
