### ISSUE TITLE
1.19.2 Bucket wheel not displayed, but excavator working

### ISSUE THREAD

**Issue by JordaneD** [BluSunrize/ImmersiveEngineering#5706]
### Minecraft Version

1.19.2

### Immersive Engineering Version

9.2.1-164

### Expected Behavior

Classic excavator

### Actual Behavior

Not displayed correctly
https://prnt.sc/anAKknD5zBiz

### Steps to reproduce

Create the structure

### Debug Crash Log

no crash

**Comment by mindforger** [comment]
Please follow the template and provide a debug crashlog, there could be a couple of possible reasons that can cause this
