### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by SugarDaddii** [BluSunrize/ImmersiveEngineering#571]
http://paste.ee/p/FiCRN

**Comment by malte0811** [comment]
Duplicate of #559

**Comment by SugarDaddii** [comment]
okay i see it so to fix it uninstall all ADDONS or update to forestry 4 (what not possible because of binnie mod not supporting this)

**Comment by malte0811** [comment]
disabling forestry compat in the config may also fix this, but i have not tried that yet

**Comment by BluSunrize** [comment]
It does fix it, others have done that.

**Comment by SugarDaddii** [comment]
what do you mean with disable forestry combat? do you mean Compatibility? and all to false or what do you mean?

**Comment by theunkn0wn1** [comment]
In the ``ImmersiveEngineering.config`` file, change
 ```
    # Set this to false to disable IE's built in compatability with Forestry
    B:"Enable Compatmodule: Forestry"=true
```
on line 17 to
```
    # Set this to false to disable IE's built in compatability with Forestry
    B:"Enable Compatmodule: Forestry"=false
```

**Comment by SugarDaddii** [comment]
you guys are very helpfull thx you very much!
