### ISSUE TITLE
config option for grunt birthday party headshot [Suggestion] ... 

### ISSUE THREAD

**Issue by SonicTheHedgehog58987276** [BluSunrize/ImmersiveEngineering#5712]
### Explain your idea

i want to turn off grunt birthday party headshots, but there is no config option.

**Comment by BluSunrize** [comment]
And there won't be.
There's a secret advancement linked to those, and I think they're funny, so I'm not adding a config for that.

**Comment by SonicTheHedgehog58987276** [comment]
> And there won't be. There's a secret advancement linked to those, and I think they're funny, so I'm not adding a config for that.

what if its too violent?!

**Comment by BluSunrize** [comment]
It's not my job to keep players away from violent video games. That's a job of their parents and education system.

Immersive Engineering is a mod that contains guns and other weaponry. Parents of young children should probably not let them play it.
