### ISSUE TITLE
crash when placing wires slightly longer than 64 blocks

### ISSUE THREAD

**Issue by poly-1810** [BluSunrize/ImmersiveEngineering#5713]
### Minecraft Version

1.18.2

### Immersive Engineering Version

8.4.0-161

### How did it happen?

i set the HV wire's max range to 128 blocks in the serverconfig, and when i set up a post that is exactly 128 blocks away from the starting position, linking a wire between the two relays causes a crash. did the same thing at 96 blocks length, also crashes, and it occasionally crashes at 64 blocks length, with some chunk rendering issues
![image](https://github.com/BluSunrize/ImmersiveEngineering/assets/105131270/f94b5421-6cc2-4654-bd99-2e93db394753)

### Crash Log

https://pastebin.com/G8TK1HAN

**Comment by BluSunrize** [comment]
Sorry, 1.18.2 is no longer supported.
You can try removing Sodium and see if that fixes the error.
