### ISSUE TITLE
[Suggestion] ... More reasonable language file structure and simplified Chinese translation

### ISSUE THREAD

**Issue by shenyx110** [BluSunrize/ImmersiveEngineering#5714]
### Explain your idea

[Immersive Engineering.zip](https://github.com/BluSunrize/ImmersiveEngineering/files/11755918/Immersive.Engineering.zip)
More reasonable language file structure and simplified Chinese translation
union code is not good for some computer ！

**Comment by BluSunrize** [comment]
If you want to submit a different translation, please open a Pullrequest.
