### ISSUE TITLE
Crash java 1.19.4 supplying power with integrated dynamics pipes

### ISSUE THREAD

**Issue by TNWanderer** [BluSunrize/ImmersiveEngineering#5716]
### Minecraft Version

1.19.4

### Immersive Engineering Version

1.19.4-9.4.0-166

### How did it happen?

Instead of running power using lines and connectors from immersive engineering used pipes from integrated dynamics.  I attached the power as designed to crusher and worked excellently without hiccup or pause.  Went to apply power to an excavator and Minecraft immediately crashed.  power had not even been applied just the connector to the pipe apparatus used to route energy

### Crash Log

https://gist.github.com/TNWanderer/608ad47055a28114a94354b12927f7fa

**Comment by BluSunrize** [comment]
Looks to be an issue on Integrated Dynamics side - or at least I don't see how we'd be causing this.
Please report this to them

**Comment by malte0811** [comment]
We're missing a check for the right cap here: https://github.com/BluSunrize/ImmersiveEngineering/blob/8643c3b4a530909e1e4b37443bbf5e5c1c7dfa31/src/main/java/blusunrize/immersiveengineering/common/blocks/multiblocks/logic/ExcavatorLogic.java#L316

**Comment by TNWanderer** [comment]
it is definitely IE issue,  found a bunch of blocks placed at that location will cause a crash.  stone being one of them.

**Comment by TNWanderer** [comment]
sorry clicked close instead of continue
