### ISSUE TITLE
Sawmill cannot cut stripped wood blocks

### ISSUE THREAD

**Issue by saltyseadoggo** [BluSunrize/ImmersiveEngineering#5717]
### Minecraft Version

1.19.2

### Immersive Engineering Version

9.2.2-165

### Expected Behavior

Just like how you can turn stripped logs into planks with the sawmill, you'd be able to turn stripped wood blocks into planks as well.

### Actual Behavior

You cannot turn stripped wood blocks into planks with the sawmill.

### Steps to reproduce

1. Start the game with IE and JEI loaded.
2. Enter a world
3. Hover over any stripped wood/hyphae block from vanilla Minecraft, such as `minecraft:stripepd_oak_wood`, and press U to view uses
4. Observe how JEI does not show a sawmill usage for the stripped wood block.

### Debug Crash Log

N/A, recipe issue

**Comment by BluSunrize** [comment]
This necessitates an API change, so will only be addressed in 1.20
