### ISSUE TITLE
IE & Optifine workbench blueprint crash issue (1.19.3)

### ISSUE THREAD

**Issue by RoboticGoddess** [BluSunrize/ImmersiveEngineering#5718]
### Minecraft Version

1.19.3

### Immersive Engineering Version

1.19.3-9.3.0-163

### How did it happen?

When placing the a blueprint into the engineering table the game will freeze and crash, stating the issue that it was attempting to render 4 light sources & that it had a "Rendering Block Entity" error (Crash log below)

### Crash Log

https://gist.github.com/RoboticGoddess/d1c77dddae732d92990e06f80d3e639a

**Comment by mindforger** [comment]
Please check existing issues (including closed), optifine is not supported

**Comment by BluSunrize** [comment]
Correct, optifine is indeed not supported.
I can manage these issues myself @mindforger, thank you very much.
