### ISSUE TITLE
Crash when launcher start

### ISSUE THREAD

**Issue by 828bkg** [BluSunrize/ImmersiveEngineering#572]
when I put this mod in mods folder,and I launch the game,my game crash!!!! (sorry for my english but this isn't my main language) please help me,I love this mod!

http://pastebin.com/d1v7ZQah

**Comment by malte0811** [comment]
I cant view the pastebin link, it says it is a private paste

**Comment by 828bkg** [comment]
Ops,sorry.....now is pubblic http://pastebin.com/d1v7ZQah

**Comment by malte0811** [comment]
Update forge

**Comment by 828bkg** [comment]
If I update forge my game crash even without mod :(

**Comment by 828bkg** [comment]
what's the minimum version required?

**Comment by malte0811** [comment]
10.13.4.1448

**Comment by AlexPlus117** [comment]
I have the same problem, but with Forestry: http://pastebin.com/qruYZqMD

**Comment by theunkn0wn1** [comment]
@828bkg, please try downloading Immersive Engineering 0.6
The fragment of the crashlog shows you are attempting to use 0.5.4

@AlexPlus117, disable forestry compat or update to Forestry 4. IE is incompatible with Forestry 3.x

**Comment by 828bkg** [comment]
when I uptade forge the game doesn't start,this is my console report


http://pastebin.com/rgWMAeGF

**Comment by 828bkg** [comment]
@theunkn0wn1 

@malte0811

**Comment by theunkn0wn1** [comment]
Hmm.. I am seeing an awful lot of 403 errors, how exactly did you update
forge? Are you using a 3rd party launcher such as FTB? Also, you can edit
your posts fyi ;)

**Comment by 828bkg** [comment]
No,i delete the old forge from the versione folder,and I install forge 10.13.4.1448 and latest manually,but the game don't start please help me :(
The crash with immersive engineering 0.6 is the same of 5.4

**Comment by mindforger** [comment]
duplicate issue, disable forestry compat module in the IE cofig, IE is using forestry 4 not 3.6!

**Comment by theunkn0wn1** [comment]
@mindforger , we are past the duplicate issues. Right now it appears our friend did not install forge correctly. If you look at his crashlog, he had just IE and forge(out of date). I do not have time today to guide him in updating his Forge install, could you help him please? He appears to be running from the vanilla launcher

**Comment by mindforger** [comment]
oh yeah i just had seen the crash logs, the logfile i have overseen!

download the forge client installer (preferably the normal one without .exe)
run it and just hit "install client" (make sure the launcher is closed)

copy your profile in your minecraft launcher(profile editor tab) then edit the profile
hit the checkbox on your "Game Directory" and change it to a new one
make sure you use the correct forge version in the "Version Selection"
save the profile, run it once

my suggestion, always make a new profile + new game directory this way ... 
you can now drop your mods/configs/scripts in the new folder by pressing "open game dir" in your profile editor

**Comment by 828bkg** [comment]
I already do this!!!
But if I update forge my game doesn't start!!   This is the console log

      http://pastebin.com/rgWMAeGF

**Comment by BluSunrize** [comment]
This is not an IE crash. This is Forge not downloading because of a 403 error.

Don't report this to me, report it to Forge.
