### ISSUE TITLE
Unknown Item

### ISSUE THREAD

**Issue by videogamesrcool** [BluSunrize/ImmersiveEngineering#5721]
### Minecraft Version

1.19.2

### Immersive Engineering Version

9.2.2-165

### How did it happen?

Crashed while trying to load world. See crash report

### Crash Log

https://pastebin.com/mLHRviLH

**Comment by BluSunrize** [comment]
Try removing Cooking for Blockheads and see if that fixes it

**Comment by brisingraerowing** [comment]
IME, Crashes like this are caused by an error during initial mod loading, which doesn't crash until the next loading stage. It's probably not C4B. A full log from this error would show what happened.
