### ISSUE TITLE
Missing Items: All Engineering Blocks for the Arc Furnace

### ISSUE THREAD

**Issue by EmderBeast** [BluSunrize/ImmersiveEngineering#5724]
### Minecraft Version

1.19.4

### Immersive Engineering Version

0.12-98

### Expected Behavior

Normaly i would just Build it but its just missing completly and i cant build the arc furnace so i cant produce many items.

### Actual Behavior

Normaly it should pop up in the crafting list or i should be able to craft it with the recepie online but it just doesnt work.

### Steps to reproduce

i was playing FTB Ultimate Reloaded with the ATLauncher and when i startet building my systems i saw that there are items missing

### Debug Crash Log

https://paste.atlauncher.com/view/bed6850f-33a4-4260-84d4-d1e6c5eacc41

**Comment by BluSunrize** [comment]
1) 1.12 is no longer supported and hasn't been for 3 years
2) Instructions for how to build the Arc Furnace is found in the Engineer's Manual. That is the only valid source of information.
