### ISSUE TITLE
Requirements 

### ISSUE THREAD

**Issue by CosmosFury13** [BluSunrize/ImmersiveEngineering#5725]
### Minecraft Version

1.19.2

### Immersive Engineering Version

9.2.2 165

### Expected Behavior

Loading my mod pack

### Actual Behavior

I tried to remove immersive engineering and it said a mod called tmted required it but I have no clue what mod that is

### Steps to reproduce

Removed immersive

### Debug Crash Log

Sorry don’t have one

**Comment by Marksman-hub** [comment]
I am getting the same error in 1.20.1, the thing is, I didn't add Immersive Engineering to the pack.

Here is the log:
[latest.log](https://github.com/BluSunrize/ImmersiveEngineering/files/14673176/latest.log)
