### ISSUE TITLE
Concrete 

### ISSUE THREAD

**Issue by CosmosFury13** [BluSunrize/ImmersiveEngineering#5726]
### Minecraft Version

1.19.2

### Immersive Engineering Version

9.2.2 165

### Expected Behavior

Craftaboe concrete

### Actual Behavior

I am not able to craft concrete at all my height says I don’t need water but that doesn’t become concrete in a crafting table and if I use a water bucket it’s still not craftable, even in the mixer concrete won’t craft

### Steps to reproduce

Use my mod pack
Try and craft concrete

### Debug Crash Log

Don’t have one

**Comment by mindforger** [comment]
>Debug Crash Log
Don’t have one

The template told you how to make one, it is required to know your modpack setup

**Comment by CosmosFury13** [comment]
here is the debug crash log

https://pastebin.com/X3AUPN7j

**Comment by BluSunrize** [comment]
I haven't fully understood your description, sorry.
Can you provide some screenshots of what you are trying to do?
