### ISSUE TITLE
Engineer's Workbench causes game to crash when VBO is disabled

### ISSUE THREAD

**Issue by ojmaster** [BluSunrize/ImmersiveEngineering#5728]
### Minecraft Version

1.18.2

### Immersive Engineering Version

8.4.0-161

### How did it happen?

I am using the ATM7 To the Sky modpack.
So I had initially disabled VBO because I was using shaders (Astralex by LexBoost) with Rubidium/Oculus and water wheels and windmills were showing up as invisible when I do have a shader on. But when I started using the Engineer's Workbench I noticed that if I put a blueprint in it my game would completely crash with the error and would crash me again anytime i even looked in the direction of the workbench, this forced me to have another player come in and destroy the bench for me:
`java.lang.IllegalStateException: Not filled all elements of the vertex`

After enabling VBOs my game no longer crashes when i use the workbench but now I can't see the water wheels or windmills with my shaders. I know I can just disable shaders but I like having it and was wondering if there is another solution for this?

### Crash Log

https://pastebin.com/n7CQ6n44

**Comment by BluSunrize** [comment]
The solution is to have VBO enabled, and not use shaders. They are not supported.
