### ISSUE TITLE
[Suggestion] [1.19.2] Let cables run through blocks without the cable going away?

### ISSUE THREAD

**Issue by JohnDeereLiebhaber** [BluSunrize/ImmersiveEngineering#5729]
Hello, 
let cables run through blocks without the cable going away is there a possibility for the MC version 1.19.2

Thanks in advance

**Comment by Daryl1299** [comment]
Hello! I believe that what you are looking for can actually already be found within the configurations folder.

Go into your .minecraft folder, (Windows Key +R at the same time, click on .minecraft,)
then enter your saves folder,
locate a save file that has had immersive engineering run on it, 
open serverconfig
then go into immersiveengineering-common,
finally, you shouldnt have to scroll at all, you locate the "blocksBreakWires" block, and set the value to False.

If you want this to apply to all worlds you generate, copy the "immersiveengineering-common" file, and paste into the defaultconfig folder. 


Dont be afraid to ask for more clarification if need be!

**Comment by JohnDeereLiebhaber** [comment]
Hello,
I've found everything and also set "blocksBreakWires" to false, but if wires are supposed to go through blocks, the connection is obstructed

And how can you set it up on a Forge server so that the wires go through blocks?

Thanks in advance

**Comment by BluSunrize** [comment]
The option allows you to place a block *afterwards* in the wire without breaking it. You still have to place the wire in a free area first.

If you are playing on a server, you have to change the configs on the server. Your hosting provider can assist you with that, if you don't know how to do this yourself.

Issue is resolved.
