### ISSUE TITLE
Coke Oven not work correctly and bugged with rendering!

### ISSUE THREAD

**Issue by SugarDaddii** [BluSunrize/ImmersiveEngineering#573]
Hey my coke oven not renders correctly and when i feed it with coal it disappears! 
Also not starting to work!

Renderprob.:
http://abload.de/image.php?img=cokeovenrenderingv3y5g.jpg
Coal Issue.:
http://abload.de/image.php?img=coaltheredxuwo.jpg
http://abload.de/image.php?img=coaldisapearqouut.jpg

EDIT.: OKAY its a render bug since update 0.6 maybe optifine or fastcraft!

**Comment by theunkn0wn1** [comment]
Can you attempt to reproduce your render problem without the texture pack or Optifine please?

Unable to reproduce issue with just IE and its dependants

World of advice: Optifine breaks all the things, if you are experiencing rendering issues please attempt to reproduce them without Optifine installed.

**Comment by SugarDaddii** [comment]
i download the newest F32.me texture pack and it was fixed!

**Comment by BluSunrize** [comment]
Closed then?
