### ISSUE TITLE
Recipe bug

### ISSUE THREAD

**Issue by Orion2852** [BluSunrize/ImmersiveEngineering#5732]
### Minecraft Version

1.19.2

### Immersive Engineering Version

9.2.2.165

### Expected Behavior

The steel block from the immersive engineering mod must be produced with a single type of steel ingot. However, it wants the steel block from 2 different mods.

### Actual Behavior

There are mekanism(version is 10.3.9.13)  and immersive engineering mods in the pack I prepared for myself. When I try to produce the steel block of the immersive engineering mod, I am faced with a recipe that forces me to use the steel ingots in both mods. There is no way to produce this block using only the steel ingots from the immersive engineering or mekanism mod.

### Steps to reproduce

the above explanations are clear enough.

### Debug Crash Log

No.

**Comment by BluSunrize** [comment]
9 ingots of Immersive Engineering steel ingots should make an IE steel block.

Please provide a screenshot of them not doing so.

Also, please test this in an instance with just IE installed.

**Comment by Orion2852** [comment]
I can't spare time for the game right now, but I'll send you a screenshot as soon as possible. Also, I didn't change recipy of any mod in the mod pack I made. I just added the mods and I'm playing.

**Comment by Orion2852** [comment]
![Uploading 20230802_170620.jpg…]()

As you mentioned, it can be done with 9 steel ingots of immersive engineering, but I can't do it only with the steel ingots of the mekanism mod.
