### ISSUE TITLE
Game crashes when placing a blueprint on the Engineer's workbench

### ISSUE THREAD

**Issue by AxilesSparangus** [BluSunrize/ImmersiveEngineering#5733]
### Minecraft Version

1.18.2

### Immersive Engineering Version

8.4.0

### How did it happen?

While I was crafting a revolver, I had, obviously, no ammo, so I took a blueprint, placed on the table and... it crashed. Here's what it said:
"The game crashed whilst rendering block entity
Error: java.lang.IllegalStateException: Not filled all elements of the vertex"
This was extremely infuriating, because I was very advanced, and my world was now hardstuck. Everytime i tried going back in the world, it crashed again. 
(Image transaltion: "ERROR. The game stopped working [...] Error code: -1")
![error](https://github.com/BluSunrize/ImmersiveEngineering/assets/140620843/5aad9d07-a07b-4628-942f-edd1715f8c1c)

### Crash Log

https://gist.github.com/AxilesSparangus/6bbb868c1d89c6e283dc316f4ec3b7fd

**Comment by AxilesSparangus** [comment]
For now, in my world I will avoid using blueprints at all costs. It happens with every blueprint as I tested, so I would thank anyone for their help.

**Comment by mindforger** [comment]
you can also remove optifine, i am not 100% sure if this is valid for 1.18 but it is currently not supported due to it's closed source

**Comment by AxilesSparangus** [comment]
> you can also remove optifine, i am not 100% sure if this is valid for 1.18 but it is currently not supported due to it's closed source

although i will miss the shaders, i prefer enjoying the mod at its fullest. i will test it out

**Comment by AxilesSparangus** [comment]
> you can also remove optifine, i am not 100% sure if this is valid for 1.18 but it is currently not supported due to it's closed source

It worked! thank you for your help.
