### ISSUE TITLE
[1.16.5]error

### ISSUE THREAD

**Issue by yuankun1** [BluSunrize/ImmersiveEngineering#5734]
### Minecraft Version

1.18.2

### Immersive Engineering Version

ImmersiveEngineering-1.16.5-5.1.0-148

### Expected Behavior

I don't know

### Actual Behavior

He reported an error in the background

### Steps to reproduce

Start the catserver server

### Debug Crash Log

https://paste.ubuntu.com/p/YySF6yYhf4/

**Comment by mindforger** [comment]
>If your version does not show up here, support for it has been ended.

you did not even include a modlist to start with helping, but from the log i would say the NPC mod "noppes.npcs" uses client side calls/objects from immerisve engineering it should not touch when running on the server, try their issue tracker first, maybe they can fix it or come up with a solution

but 1.16.5 is not supported and might get closed here soon

**Comment by malte0811** [comment]
As @mindforger said, 1.16.5 is long out of support.
