### ISSUE TITLE
Game crashes when putting a Blueprint into an Engineer's Workbench

### ISSUE THREAD

**Issue by Schnittchen1423** [BluSunrize/ImmersiveEngineering#5735]
### Minecraft Version

1.18.2

### Immersive Engineering Version

8.4.0-161

### How did it happen?

The game crashes when putting a Blueprint of any kind into an Engineer's Workbench. This problem was reported by another person on the server and tested on both the server and in singleplayer worlds by both of us, resulting in a crash every time.

**List of the mods in the modpack:**
- AutoRegLib
- Biomes O' Plenty
- Champions
- CoFH Core
- Curios API (Forge)
- Dungeons Enhanced
- Iceberg [Forge]
- Immersive Engineering
- Immersive Petroleum
- Iron Chests
- Just Enough Items (JEI)
- Mantle
- Ore Excavation
- Quark
- Refined Pipes
- Sophisticated Backpacks
- Sophisticated Core
- Storage Drawers
- Structure Gel API
- TerraBlender (Forge)
- Thermal Cultivation
- Thermal Expansion
- Thermal Foundation
- Thermal Integration
- Tinkers Construct
- TslatEntityStatus (TES) (Fabric/Forge)
- Xaero's Minimap
- Xaero's World Map

The Forge version is 40.2.0

### Crash Log

https://gist.github.com/Schnittchen1423/7c900f02e7f0c3e743fabd4168999f73

**Comment by mindforger** [comment]
you forgot optifine in your modlist, now guess the reason ;)

**Comment by BluSunrize** [comment]
As indicated by mindforger:

Please reproduce this without optifine.

**Comment by Schnittchen1423** [comment]
Still crashes, according to the friend. (I didn‘t have time to test it yet but I‘ll come back to this once I have)

**Comment by Schnittchen1423** [comment]
Oh right that fixed it

**Comment by Schnittchen1423** [comment]
Thanks!
