### ISSUE TITLE
Toolbox becomes empty when placed on grass

### ISSUE THREAD

**Issue by PaulerLeOne** [BluSunrize/ImmersiveEngineering#5736]
### Minecraft Version

1.19.2

### Immersive Engineering Version

9.2.2-165

### Expected Behavior

Toolbox should loose its content

### Actual Behavior

When shift+right clicking on grass (not to be confused with a grass block) with a toolbox, the toolbox will be place replacing the grass and toolbox will be empty.

### Steps to reproduce

1. Grab a toolbox and put anything inside
2. Shift and right-click on a grass plant with the toolbox on hand
3. Open the toolbox

**Comment by mindforger** [comment]
>my internet provider isn't letting me access 
pastebin.com so ¯_(ツ)_/¯

I suspect gist.github.com like mentioned in the template also isnt an option? Seriously, an sincere apology should never end in a shrug

**Comment by PaulerLeOne** [comment]
dude, calm down, I was just being a little silly, no need to be outraged about it

**Comment by BluSunrize** [comment]
For the record, Mindforger does not speak for the maintainers of this project. They just self-insert themselves into every single issue on this tracker for no reason.

But yes, a full crashlog would be very helpful =)
