### ISSUE TITLE
Bottling Machine sometimes refuses to accept fluids

### ISSUE THREAD

**Issue by aaronhowser1** [BluSunrize/ImmersiveEngineering#5738]
### Minecraft Version

1.19.2

### Immersive Engineering Version

ImmersiveEngineering-1.19.2-9.2.2-165

### Expected Behavior

The Bottling Machine should allow me to insert fluid.

### Actual Behavior

![image](https://github.com/BluSunrize/ImmersiveEngineering/assets/15698722/a2abbf8b-ad92-45ae-bfd0-98b3a95456ea)
I was using that middle tank to make sure that the pipes are working, since they don't have a visual indicator.

When that didn't work, I moved to Mekanism's pipes, which also refused to enter.
![image](https://github.com/BluSunrize/ImmersiveEngineering/assets/15698722/3a98f244-7448-4ee4-b7b1-eea9bef0b8cf)

After tearing it down and rebuilding it
![image](https://github.com/BluSunrize/ImmersiveEngineering/assets/15698722/bc30616d-3f37-4e6b-8258-52fe189ab685)

A player reported this to me and the first one I built actually did work. Then I broke one block and placed it back and then hammered it, and it didn't work.

Wait. While typing this, I think I figured it out.

If it has a Pipe touching its input at the time of construction (that is, when you hammer it), it refuses to accept fluid input. 

https://github.com/BluSunrize/ImmersiveEngineering/assets/15698722/f0c45f80-fb04-43b2-8c0d-287ed594930b

The player that reported this to me says that they didn't place down pipes until after hammering it, but 

### Steps to reproduce

Video above

### Debug Crash Log

https://gist.github.com/aaronhowser1/4703647d8c5c800bf638ff9cf027a6a5

**Comment by BluSunrize** [comment]
Can you reproduce this while using IE barrels instead of Mekanism Tanks?

**Comment by aaronhowser1** [comment]
I'll try, but that really shouldn't matter should it? The pipes *are* working, I put a tank next to the Bottling Machine and it filled up.

**Comment by aaronhowser1** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/assets/15698722/ca365c5d-7268-4e14-acdf-0d4ee16fa094
