### ISSUE TITLE
1.19.2 Crash randomly

### ISSUE THREAD

**Issue by wiktormalyska** [BluSunrize/ImmersiveEngineering#5739]
### Minecraft Version

1.19.2

### Immersive Engineering Version

1.19.2-9.2.2-165

### How did it happen?

By just walking around and playing

### Crash Log

https://gist.github.com/wiktormalyska/3e2df1405da6dfbd88416991d9b75a0b

**Comment by malte0811** [comment]
Layers-of-Railways/Railway#238
