### ISSUE TITLE
[1.18.2] World is now inaccessible due to this bug

### ISSUE THREAD

**Issue by Melkinator** [BluSunrize/ImmersiveEngineering#5746]
### Minecraft Version

1.18.2

### Immersive Engineering Version

8.4.0-161

### How did it happen?

Placing a blueprint for metal molds into an engineer's workbench instantly crashes and will continue crashing if you try to log on the world again. 

### Crash Log

https://pastebin.com/ewgGqmeN

**Comment by mindforger** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/5735

**Comment by BluSunrize** [comment]
Optifine is not supported
