### ISSUE TITLE
[Suggestion] Upload to modrinth

### ISSUE THREAD

**Issue by PolyframeX** [BluSunrize/ImmersiveEngineering#5750]
### Explain your idea

I feel like this mod should be uploaded to modrinth, it would allow for more availability. And it would help a ton with some modpacks! Monetization is available too if your interested!

**Comment by malte0811** [comment]
We already do that: https://modrinth.com/mod/immersiveengineering

**Comment by BluSunrize** [comment]
Modrinth does have a search function and IE does show up there.
Should have probably tried that first =p
