### ISSUE TITLE
[Suggestion] Add hammer functionality to hammer's from other mods

### ISSUE THREAD

**Issue by Correlander** [BluSunrize/ImmersiveEngineering#5752]
### Explain your idea

Make it so other mod hammers or anything with forge:hammer tag can be used as an engineer's hammer, similar to how most mods do it with wrenches, adding a tag called forge:tools/wrench. 

This would mainly help integration into a modpack.

**Comment by BluSunrize** [comment]
We have a tag for marking other things as hammers =)
