### ISSUE TITLE
[Suggestion] [1.20.1] Change the text color on Engineer's Crafting Table

### ISSUE THREAD

**Issue by TelepathicGrunt** [BluSunrize/ImmersiveEngineering#5754]
### Explain your idea

Currently, the text on the Engineer's Crafting Table is black on a dark colored background which makes it very difficult to read it. Try turning the text color to white or lighten the background around where the text is. This appears to also impact Wooden Storage Crate so be sure to go through all UIs and make sure the contrast between the text and background is good for reading.
![image](https://github.com/BluSunrize/ImmersiveEngineering/assets/40846040/12414096-bd52-4c3f-9c96-0eac504bcaef)

**Comment by ffuentesm** [comment]
Yeah, I would suggest something white or light grey.

**Comment by BluSunrize** [comment]
Good point, I'll look into it in the future, thanks =)
