### ISSUE TITLE
Floodlight anomalies

### ISSUE THREAD

**Issue by James-T-Oudvoure** [BluSunrize/ImmersiveEngineering#576]
During some of my testing, I found that it is impossible to connect a high-voltage connector to a floodlight no matter what.
![2015-11-02_20 16 29](https://cloud.githubusercontent.com/assets/14304823/10899943/9609e432-819f-11e5-82f8-3546f0672e70.png)

![2015-11-02_20 16 39](https://cloud.githubusercontent.com/assets/14304823/10899956/b2c45a8a-819f-11e5-9b28-d1999245e066.png)

![2015-11-02_20 17 08](https://cloud.githubusercontent.com/assets/14304823/10899967/d2eab570-819f-11e5-8b92-8ec850f7270e.png).

However, I have found no similar difficulties with low-voltage connectors:
![2015-11-02_20 20 57](https://cloud.githubusercontent.com/assets/14304823/10900072/e39458d0-81a0-11e5-95d6-832ba20a0961.png)

![2015-11-02_20 38 45](https://cloud.githubusercontent.com/assets/14304823/10900137/c8eabfaa-81a1-11e5-9a7a-d6dc9c4e294a.png)

![2015-11-02_20 30 50](https://cloud.githubusercontent.com/assets/14304823/10900077/fbce6c9c-81a0-11e5-9b73-a14493ce028a.png)

No such luck with medium-voltage connectors however:
![2015-11-02_20 31 56](https://cloud.githubusercontent.com/assets/14304823/10900085/0fd718f6-81a1-11e5-92e6-88150f1aad88.png)

![2015-11-02_20 32 13](https://cloud.githubusercontent.com/assets/14304823/10900086/151b0a84-81a1-11e5-9f8b-8c0c874a6b62.png)

![2015-11-02_20 32 17](https://cloud.githubusercontent.com/assets/14304823/10900088/1901c8ea-81a1-11e5-9aae-b7f7c3a82afa.png)

Also, I've noticed that under some very nebulous conditions, the floodlights simply stopped emitting light. I'm not sure why, it's not daylight, it's not lack of power, I have absolutely no clue of what causes it.

**Comment by theunkn0wn1** [comment]
Floodlights are LV appliances, they will not accept anything else. Floodlights can sometimes take up to 30 seconds to update, have you tried waiting?

**Comment by James-T-Oudvoure** [comment]
Yes, I've connected a floodlight to a capacitor and it activated. A few seconds later, it shut off and didn't turn back on until I broke the wire and reconnected it.

Also, if the floodlight is only intended for low-voltage, shouldn't this be stated in the manual to prevent issue reports like mine from occuring?

**Comment by theunkn0wn1** [comment]
​It's voltage is implied by ```Floodlights are strong lightsources. While they require more power than a simple Powered Lantern``` though it never stated it was MV.

For the issue at hand, I was partially able to reproduce. Due to how long the darn thing can take to update, as lighting calc is expensive, it is set to take a really long time (if at all) to update. I find that sometimes I need to hit the floodlight with the hammer to make it update.
