### ISSUE TITLE
[bug] setting up weapons and items in gamemode creative.

### ISSUE THREAD

**Issue by VioSoCo** [BluSunrize/ImmersiveEngineering#5761]
### Minecraft Version

1.20.1

### Immersive Engineering Version

ImmersiveEngineering-1.20.1-10.0.0-169.jar

### Expected Behavior

The drill head from the drill, as well as modifiers of weapons and other items, did not disappear in creative mode

### Actual Behavior

When installing the drill head in the drill, then after a while the drill head disappears without a trace. It's the same with other weapons and items. (in creative mode)

### Steps to reproduce

I'm going to the creative
I take a drill and a drill head
I install the drill head in the drill
I use
After a while, the modifier (drill head) disappears

### Debug Crash Log

.

**Comment by BluSunrize** [comment]
That's a vanilla/forge bug, not much we can do about it.
