### ISSUE TITLE
[bug] condenser backpack.

### ISSUE THREAD

**Issue by VioSoCo** [BluSunrize/ImmersiveEngineering#5762]
### Minecraft Version

1.20.1

### Immersive Engineering Version

ImmersiveEngineering-1.20.1-10.0.0-169.jar

### Expected Behavior

When putting the condenser backpack on the armor, "IF" was written not equal to zero. Also to charge.

### Actual Behavior

When putting on a condenser backpack, the charge "0/0 IF" is written on the armor. Thus, it does not charge in any way.

### Steps to reproduce

I'm putting on my armor
I'm putting on a condenser backpack
The backpack shows "0/0 IF"
Charging is not happening

### Debug Crash Log

.

**Comment by BluSunrize** [comment]
Read the manual, you need to put an accumulator in it.
