### ISSUE TITLE
[bug] there is no emergency filter in the turret.

### ISSUE THREAD

**Issue by VioSoCo** [BluSunrize/ImmersiveEngineering#5764]
### Minecraft Version

1.20.1

### Immersive Engineering Version

ImmersiveEngineering-1.20.1-10.0.0-169.jar

### Expected Behavior

In the turret, you can add players to the blacklist, thereby the turret does not attack them.

### Actual Behavior

There is no way to add a person to the attack blacklist at the turret. The turret attacks everyone.

### Steps to reproduce

I'm putting up a turret
I replenish it with cartridges or chemical.
The turret attacks everyone

### Debug Crash Log

.

**Comment by Luviam** [comment]
Same issue here, can't add player names to the filter list thingy.

**Comment by BluSunrize** [comment]
Fixed for next release
