### ISSUE TITLE
[bug] armor-piercing cartridges + turret + mekasuit

### ISSUE THREAD

**Issue by VioSoCo** [BluSunrize/ImmersiveEngineering#5765]
### Minecraft Version

1.20.1

### Immersive Engineering Version

ImmersiveEngineering-1.20.1-10.0.0-169.jar

### Expected Behavior

armor-piercing cartridges in the turret are obliged not to ignore the mekasuit

### Actual Behavior

armor-piercing rounds in the turret completely ignore the mekasuit

### Steps to reproduce

I'm putting up a turret
Replenishing with armor-piercing bullets
I dress mekasuit
The turret takes out as if I'm not wearing armor

### Debug Crash Log

.

**Comment by BluSunrize** [comment]
They are armor piercing. They do what it says on the label, they pierce armor =)
