### ISSUE TITLE
[bug] broken armor names

### ISSUE THREAD

**Issue by VioSoCo** [BluSunrize/ImmersiveEngineering#5766]
### Minecraft Version

1.20.1

### Immersive Engineering Version

ImmersiveEngineering-1.20.1-10.0.0-169.jar

### Expected Behavior

Faraday armor and steel armor should have their own names.

### Actual Behavior

![image](https://github.com/BluSunrize/ImmersiveEngineering/assets/147322426/b0d06c8a-3ef0-418d-978c-86be2fb7acc4)
Faraday armor and steel armor do not have their own names.

### Steps to reproduce

I take Faraday armor or steel
armor and see a beautiful unfinished name of these armor.

### Debug Crash Log

.

**Comment by Luviam** [comment]
Same issue here.

**Comment by Elmer-Glue** [comment]
Somewhere between 1.19.2 and 1.20.1 Mojang changed part of the id names for armor:
head - helmet
chest - chestplate
legs - leggings
feet - boots

To fix this you would need to make rename the 8 pieces of armor like so:
item.immersiveengineering.armor_steel_head - item.immersiveengineering.armor_steel_helmet
And so on.

**Comment by D0CTOR-ZED** [comment]
There is a similar issue with the Engineer's Toolbox in the same version.  The block is called block.immersiveengineering.toolbox_block where the language files have it as block.immersiveengineering.toolbox.  I came here to report the armor and the toolbox.  Hope adding this here is ok.

**Comment by BluSunrize** [comment]
Malte already fixed the armors in a previous commit.
I've now also fixed the toolbox.

Next release will see this resolved.
