### ISSUE TITLE
[bug] the electronic amplifier does not cause additional damage

### ISSUE THREAD

**Issue by VioSoCo** [BluSunrize/ImmersiveEngineering#5768]
### Minecraft Version

1.20.1

### Immersive Engineering Version

ImmersiveEngineering-1.20.1-10.0.0-169.jar

### Expected Behavior

the electronic amplifier must and must apply additional damage

### Actual Behavior

the electronic amplifier does not cause additional damage

### Steps to reproduce

I use an electronic amplifier
I don't see any additional damage

### Debug Crash Log

.

**Comment by BluSunrize** [comment]
It doesn't do additional damage, and we never claimed that it would.
