### ISSUE TITLE
[bug] tesla coil

### ISSUE THREAD

**Issue by VioSoCo** [BluSunrize/ImmersiveEngineering#5769]
### Minecraft Version

1.20.1

### Immersive Engineering Version

ImmersiveEngineering-1.20.1-10.0.0-169.jar

### Expected Behavior

the tesla coil should not interact in the region (worldguard), and also should not penetrate the mekasuit

### Actual Behavior

tesla coil kills in the region (worldguard), as well as punches mekasuit

### Steps to reproduce

I put a Tesla coil, in the region (worldguard) where the pvp is turned off
Plugging it in
It kills me and other people
Also, if I wear a mekasuit, then the armor does not protect from the coil in any way.

### Debug Crash Log

.

**Comment by BluSunrize** [comment]
It's a tesla coil. Normal armor does not protect against it. This is working as intended.
