### ISSUE TITLE
Spawn issue between lights and Just Another Spawner 

### ISSUE THREAD

**Issue by Potsukin** [BluSunrize/ImmersiveEngineering#577]
Looks like Electric Lantern and Floodlight makes a battle with JAS(Just Another Spawner). 
It was fixed after I removed lanterns, floodlight by MCEdit.

---- Minecraft Crash Report ----
// Don't do that.

Time: 15/11/03 12:56
Description: Exception in server tick loop

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:859)
	at java.util.ArrayList$Itr.next(ArrayList.java:831)
	at blusunrize.immersiveengineering.common.EventHandler.onEntitySpawnCheck(EventHandler.java:205)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_418_EventHandler_onEntitySpawnCheck_CheckSpawn.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraftforge.event.ForgeEventFactory.canEntitySpawn(ForgeEventFactory.java:112)
	at jas.spawner.modern.spawner.creature.handler.LivingHandler.getCanSpawnHere(LivingHandler.java:118)
	at jas.spawner.modern.spawner.CustomSpawner.spawnCreaturesInChunks(CustomSpawner.java:140)
	at jas.spawner.modern.spawner.SpawnerTicker.performSpawningInWorld(SpawnerTicker.java:73)
	at jas.spawner.modern.spawner.SpawnerTicker.serverTick(SpawnerTicker.java:42)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_494_SpawnerTicker_serverTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at cpw.mods.fml.common.FMLCommonHandler.onPreServerTick(FMLCommonHandler.java:260)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:536)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Mac OS X (x86_64) version 10.10.5
	Java Version: 1.7.0_75, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2958973904 bytes (2821 MB) / 5149556736 bytes (4911 MB) up to 5149556736 bytes (4911 MB)
	JVM Flags: 4 total; -Xms5G -Xmx5G -XX:PermSize=512M -XX:MaxPermSize=512M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 96
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 Optifine OptiFine_1.7.10_HD_U_C1 58 mods loaded, 58 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.118} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.118-universal.jar) 
	UCHIJAAAA	OpenEye{0.6} [OpenEye] (OpenEye-0.6-1.7.10.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	AncientWarfare{2.4.113-beta-MC1.7.10} [Ancient Warfare Core] (ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.0.4B1} [CoFH Core] (CoFHCore-[1.7.10]3.0.4B1-308.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.12} [BuildCraft] (buildcraft-7.1.12.jar) 
	UCHIJAAAA	AncientWarfareAutomation{2.4.113-beta-MC1.7.10} [Ancient Warfare Automation] (ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	AncientWarfareNEIPlugin{2.4.113-beta-MC1.7.10} [Ancient Warfare NEI Plugin] (ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	AncientWarfareNpc{2.4.113-beta-MC1.7.10} [Ancient Warfare NPCs] (ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	AncientWarfareStructure{2.4.113-beta-MC1.7.10} [Ancient Warfare Structures] (ancientwarfare-2.4.113-beta-MC1.7.10-FULL.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	BiblioCraft{1.11.4} [BiblioCraft] (BiblioCraft[v1.11.4][MC1.7.10].jar) 
	UCHIJAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1396-universal.jar) 
	UCHIJAAAA	Botania{r1.7-228} [Botania] (Botania r1.7-228.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.12} [BC Builders] (buildcraft-7.1.12.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.12} [BC Transport] (buildcraft-7.1.12.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.12} [BC Energy] (buildcraft-7.1.12.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.12} [BC Silicon] (buildcraft-7.1.12.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.12} [BC Robotics] (buildcraft-7.1.12.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.12} [BC Factory] (buildcraft-7.1.12.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
	UCHIJAAAA	BuildCraft|Compat{7.1.2} [BuildCraft Compat] (buildcraft-compat-7.1.2.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
	UCHIJAAAA	BuildMod{v1.0} [Build Mod] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJAAAA	CoroPets{v1.0} [CoroPets] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJAAAA	CoroAI{v1.0} [CoroAI] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJAAAA	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJAAAA	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.1.3 for MC v1.7.10.jar) 
	UCHIJAAAA	customnpcs{1.7.10d} [CustomNpcs] (CustomNPCs_1.7.10d.jar) 
	UCHIJAAAA	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) 
	UCHIJAAAA	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UCHIJAAAA	flansmod{4.10.0} [Flan's Mod] (Flans Mod-1.7.10-4.10.0.jar) 
	UCHIJAAAA	GregsLighting{1.11.2} [Greg's Lighting] (GregsLighting-1.11.2-mc1.7.10.jar) 
	UCHIJAAAA	HelperToolsID{1.1.5M} [HelperTools] (HelperTools-1.7.10-1.1.5M.jar) 
	UCHIJAAAA	idChecker{1.7.10} [ID Checker] (IDChecker-1.7.10d.jar) 
	UCHIJAAAA	IGWMod{1.1.11-32} [In-Game wiki Mod] (IGW-Mod-1.7.10-1.1.11-32-universal.jar) 
	UCHIJAAAA	ImmersiveEngineering{0.6.0} [Immersive Engineering] (ImmersiveEngineering-0.6.0.jar) 
	UCHIJAAAA	immersiveintegration{0.6.0} [Immersive Integration] (immersiveintegration-0.6.0.jar) 
	UCHIJAAAA	journeymap{5.1.1b9} [JourneyMap] (journeymap-1.7.10-5.1.1b9-unlimited.jar) 
	UCHIJAAAA	JASCompatability{1.2.0} [Just Another Spawner Compatibility Addon] (JustAnotherSpawnerCompatibilityAddon-1.2.0.jar) 
	UCHIJAAAA	llor{1.0.2} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.0.2-mc1.7.10.jar) 
	UCHIJAAAA	metacycler{1.0} [metacycler] (MetaCycler.jar) 
	UCHIJAAAA	NGTLib{1.7.10.17} [NGTLib] (NGTLib1.7.10.17_Forge10.13.2.1230.zip) 
	UCHIJAAAA	planetguyLib{1.9} [planetguyLib] (PlanetguyLib-1.9.1.jar) 
	UCHIJAAAA	PneumaticCraft{1.11.18-140} [PneumaticCraft] (PneumaticCraft-1.7.10-1.11.18-140-universal.jar) 
	UCHIJAAAA	ProjectZulu|Core{1.7.10-1.4c2} [Project Zulu] (ProjectZulu-1.7.10-1.4c2.jar) 
	UCHIJAAAA	JAKJ_RedstoneInMotion{2.8.8} [Remain In Motion] (RemainInMotion-2.8.8.jar) 
	UCHIJAAAA	RTM{1.7.10.24} [RealTrainMod] (RTM1.7.10.24_Forge10.13.2.1230.zip) 
	UCHIJAAAA	ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics] (ThermalDynamics-[1.7.10]1.1.0-161.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	weather2{v2.3.10} [Localized Weather & Storms] (weather2-2.3.10 for MC v1.7.10.jar) 
	UCHIJAAAA	worldedit{6.0-beta-01} [WorldEdit] (worldedit-forge-mc1.7.10-6.0-beta-01.jar) 
	UCHIJAAAA	JustAnotherSpawner{0.17.6} [Just Another Spawner] (JustAnotherSpawner-0.17.6.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	CoFHCore: -[1.7.10]3.0.4B1-308
	ThermalFoundation: -[1.7.10]1.2.0-102
	ThermalExpansion: -[1.7.10]4.0.3B1-218
	ThermalDynamics: -[1.7.10]1.1.0-161
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMPFlying['Potsukin'/3070, l='NewPotsu', x=-1607.47, y=68.29, z=1876.71]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by malte0811** [comment]
Your spawner mod is innocent, it is just pretty random. I hava fixed this and will probably pr the fix today (ask for it to be added to the official version)

**Comment by Potsukin** [comment]
Thank you, I am waiting for a update.
