### ISSUE TITLE
[bug-question] it is unclear how the flash lamp works.

### ISSUE THREAD

**Issue by VioSoCo** [BluSunrize/ImmersiveEngineering#5770]
### Minecraft Version

1.20.1

### Immersive Engineering Version

ImmersiveEngineering-1.20.1-10.0.0-169.jar

### Expected Behavior

the flash lamp hanging on the shield should work (illuminate)

### Actual Behavior

the flash lamp hanging on the shield does not work (does not illuminate)

### Steps to reproduce

I hung it on the shield and it doesn't work

### Debug Crash Log

.

**Comment by BluSunrize** [comment]
Read the manual, it's not a lightsource.
