### ISSUE TITLE
[bug-question] it is unclear how the turntable works.

### ISSUE THREAD

**Issue by VioSoCo** [BluSunrize/ImmersiveEngineering#5771]
### Minecraft Version

1.20.1

### Immersive Engineering Version

ImmersiveEngineering-1.20.1-10.0.0-169.jar

### Expected Behavior

The turntable has to do something

### Actual Behavior

The turntable does nothing

### Steps to reproduce

I put a turntable and I can't do anything

### Debug Crash Log

.

**Comment by BluSunrize** [comment]
Closing this because you've provided zero information on your issue. Without knowing what you are trying to do, we can't help you.
Given what most of your other issues are like, you probably didn't read the manual.
