### ISSUE TITLE
[Bug] [1.20.1] IE village house structures have air block around them.

### ISSUE THREAD

**Issue by ffuentesm** [BluSunrize/ImmersiveEngineering#5772]
### Minecraft Version

1.20.1

### Immersive Engineering Version

ImmersiveEngineering-1.20.1-10.0.0-169

### Expected Behavior

There should be no air blocks around the house.

### Actual Behavior

There is a line of air blocks around the structure.
![image](https://github.com/BluSunrize/ImmersiveEngineering/assets/44974827/547bc88b-3bef-4fef-86b4-221779875261)

**Comment by Luviam** [comment]
Same issue here, although it seems some of the variants of this structure don't have the air blocks, and some do.

**Comment by BluSunrize** [comment]
I've been unable to reproduce this in my test world.

Can you please provide:
- A seed
- A location in that world
- And a debug crashlog

That way I *may* be able to test this out properly.

**Comment by ffuentesm** [comment]
It's always on the Taiga Village. This is a world I just created. 
Seed: 331991551071426394
Location: /execute in minecraft:overworld run tp @s 1681.51 79.68 1905.81 -13.65 33.00
![image](https://github.com/BluSunrize/ImmersiveEngineering/assets/44974827/f3f46f95-f600-449b-be1e-6ee08275493a)
Crashlog: 
[crash-2024-01-01_16.01.37-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/13805995/crash-2024-01-01_16.01.37-client.txt)

**Comment by BluSunrize** [comment]
I didn't have a village at that position in my seed, but I did in fact find a taige one with the same error.

That makes it reproducible for us and we can look into it. Thank you for helping diagnose this =)

**Comment by BluSunrize** [comment]
Fixed for the next release =)
