### ISSUE TITLE
server 1.20.1 In foreign regions, you can kill mobs with a chemical spray.

### ISSUE THREAD

**Issue by BloodInAs** [BluSunrize/ImmersiveEngineering#5775]
### Minecraft Version

1.20.1

### Immersive Engineering Version

ImmersiveEngineering-1.20.1-10.0.0-169

### Expected Behavior

 In foreign regions, you can kill mobs with a chemical spray.

### Actual Behavior

in foreign regions the spray should not kill peaceful mobs

### Steps to reproduce

-

### Debug Crash Log

-

**Comment by BluSunrize** [comment]
What regions are you referring to? Please provide more detail.

**Comment by BloodInAs** [comment]
There is an online server where players set up private regions to prevent other players from breaking them at home. They turn on the flag to disable pvp, and despite the flag, the damage continues. worldguard-bukkit-7.0.9-dist.jar

**Comment by BluSunrize** [comment]
Bukkit is not supported.
