### ISSUE TITLE
Silo and tank

### ISSUE THREAD

**Issue by number117** [BluSunrize/ImmersiveEngineering#5776]
### Minecraft Version

1.20.1

### Immersive Engineering Version

10.0.0,169

### Expected Behavior

When constructing a silo or tank i expect the construction to finish by right clicking with the engineer's hammer.

I did it 3 days ago with the same setup, no problem

### Actual Behavior

Nothing happens

### Steps to reproduce

Build a tank or silo as explained in the engineer's manual.

Right clicked on the lower middle block

Nothing happens
[crash-2023-10-12_11.59.54-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/12880076/crash-2023-10-12_11.59.54-client.txt)

### Debug Crash Log

[crash-2023-10-12_11.59.54-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/12880076/crash-2023-10-12_11.59.54-client.txt)

**Comment by BluSunrize** [comment]
Please provide pictures of your setup, likely the multiblock was not built correctly

**Comment by Luviam** [comment]
Skill issue imo, works fine for me, even in Regular forge and not NeoForge.

**Comment by number117** [comment]
Yes it was.

I don’t know what happened . One day i could, the Next day i couldn’t.

When I try to right click, i lift the shield. Hammer doesn’t move.

The other machines I have build are working.
![2023-10-12_22 55 45](https://github.com/BluSunrize/ImmersiveEngineering/assets/80627858/bd447688-48e2-4143-b824-471a91ab8378)
![2023-10-12_22 56 02](https://github.com/BluSunrize/ImmersiveEngineering/assets/80627858/8acdb130-9fd4-42dc-a049-393e324e5986)

**Comment by BluSunrize** [comment]
Have you tried unequipping the shield? ^^

**Comment by number117** [comment]
Yes. 
But it seem i am the only one with that problem. It is only the tank and silo, so far.
So now i am using a mix of your mod and Create.
