### ISSUE TITLE
crash after generating chunk with mod object 

### ISSUE THREAD

**Issue by BigBeatProphet** [BluSunrize/ImmersiveEngineering#5777]
### Minecraft Version

1.20.1

### Immersive Engineering Version

1.20.1-10.0.0-169

### How did it happen?

while exploring world, only addon for IE - CTOV patch

### Crash Log

https://pastebin.com/KtKTMETF

**Comment by BigBeatProphet** [comment]
update, crash might be caused by patch for CTOV that is way older that the mod v 1.20.1-10.0.0-169 by refrencing some broken/deled stuff 
modrinth patch link - https://modrinth.com/datapack/ctov-immersive-engineering-compat/version/2.0+mod

**Comment by BluSunrize** [comment]
Can you reproduce this in a NeoForge instance instead of a Forge one?

**Comment by BigBeatProphet** [comment]
if i recall it well crash was on neoforge, but it's never happend again after removing CTOV patch for IE, at this point im not sure if i still have that modpack
