### ISSUE TITLE
Forge Version Causing a Crash 1.20.1

### ISSUE THREAD

**Issue by Devilswarchild** [BluSunrize/ImmersiveEngineering#5779]
### Minecraft Version

1.20.1

### Immersive Engineering Version

ImmersiveEngineering-1.20.1-10.0.0-169.jar

### How did it happen?

Says it requires 47.1.54 or above and I also noticed your changelog says supports neoforge but the neoforge devs all told us to stay on 47.1.3 for compat reasons specifically for neoforge.

can we please get this fixed?

### Crash Log

https://mclo.gs/Nzm9o6T

**Comment by Daihok41** [comment]
Have you found a fix for this i cant get it to work on forge server at all. Guess has to be Neoforge? Not sure.

**Comment by Devilswarchild** [comment]
> Have you found a fix for this i cant get it to work on forge server at all. Guess has to be Neoforge? Not sure.

so far i've managed to get it working with 47.2.1

**Comment by BonaireDreams** [comment]
Are you manually adding it to your mods folder as I don't seem to find it via Curse Mod loader.

**Comment by Devilswarchild** [comment]
> Are you manually adding it to your mods folder as I don't seem to find it via Curse Mod loader.

I had grabbed it while it was very briefly available via the website

**Comment by BluSunrize** [comment]
We built for NeoForge only.
We don't offer support for the old Forge anymore.

**Comment by Devilswarchild** [comment]
well the funny thing is 1.20.2 is where neoforge hard split from old forge. on 1.20.1 neoforge works with old forge mods and vice versa. and if you dont believe me you can ask everyone in the neoforge discord.

**Comment by BluSunrize** [comment]
Yeah and I'm saying we don't support issues on 1.20.1 if they aren't using NeoForge because that's the thing we built against and we can't rule out conflicts with Forge.
