### ISSUE TITLE
Blueprint and Workbench 1.18.2 NOT 1.19.2 I just need a fix

### ISSUE THREAD

**Issue by trellew** [BluSunrize/ImmersiveEngineering#5781]
### Minecraft Version

1.19.2

### Immersive Engineering Version

9.4.1

### How did it happen?

When i insert a blueprint into the engineers workbench from immersive engineering my game crashed and now I cant join the world. 1.18.2

### Crash Log

https://pastebin.com/YZMda5Xk

**Comment by mindforger** [comment]
remove optifine to fix

**Comment by BluSunrize** [comment]
You can try disabling the VBO / Vertex Buffer config setting in IE's client config, that may fix your issue.

Beyond that, no idea, Optifine is not supported.

**Comment by SirWalkerCZ** [comment]
Ran into the same issue, except with rubidium and later embedium. VBO didnt help, so I added a simple config flag that stops the function BlueprintRenderer() into the code and it seems to be working fine for me. 
[Here is the link with the updated jar.](https://drive.google.com/file/d/1vSTqr4kQnpcl0WKSuDTMgA1h0Qg0wcsa/view?usp=sharing)
Just drop it into the mods folder, launch the game, then go into the config folder, there should be a file called immersive engineering client, open it and look for:

`#Disables the rendering of blueprints when placed in engineers workbench.
#May fix some shaders related issues
disableBlueprintEngiWorkbench = false`

Set that to true and you should be good to go

**Comment by LegendaryZotar** [comment]
@SirWalkerCZ Can you reupload it?

**Comment by SirWalkerCZ** [comment]
Sure, give me 5 minutes

**Comment by SirWalkerCZ** [comment]
@LegendaryZotar https://drive.google.com/file/d/1vMoPSlfAEvxkgPCX-KCMV6LZHEtdAJVK/view?usp=sharing
here it is

**Comment by BluSunrize** [comment]
Reuploading IE builds without our permission is a license violation.
