### ISSUE TITLE
Furnace heater is not working

### ISSUE THREAD

**Issue by kft12** [BluSunrize/ImmersiveEngineering#5782]
### Minecraft Version

1.20.1

### Immersive Engineering Version

10.0.0-169

### Expected Behavior

Vanilla furnace working fast when place next to furnace heater.
And working without fuel.

### Actual Behavior

Vanilla furnace doesn't work.

### Steps to reproduce

![2023-10-16_11 52 12_2](https://github.com/BluSunrize/ImmersiveEngineering/assets/39037630/8ea30603-a13d-41da-9d78-9ab800864036)
![2023-10-16_11 52 16](https://github.com/BluSunrize/ImmersiveEngineering/assets/39037630/fd62d6d5-4957-43a8-9829-d6269b7c388d)
Charger is working, but furnace (and furnace heater) is not working.
(And by the way, the wire doesn't show up)

![2023-10-16_11 52 27](https://github.com/BluSunrize/ImmersiveEngineering/assets/39037630/6e28b395-b0c5-46ea-819f-864fcac33899)
(Screenshot after breaking the Wire Connector)
Connecting ports are fine.

### Debug Crash Log

https://gist.github.com/kft12/6cb8fb5f4857b374cc673f07e5983c24

**Comment by BluSunrize** [comment]
Can you please try it without Optifine and see if it works then?

**Comment by kft12** [comment]
I could play just fine without Optifine.
Thank you!
