### ISSUE TITLE
Crash On Creating New World

### ISSUE THREAD

**Issue by DinnerBeef** [BluSunrize/ImmersiveEngineering#5783]
### Minecraft Version

1.20.1

### Immersive Engineering Version

ImmersiveEngineering-1.20.1-10.0.0-169

### How did it happen?

When I create a new world. It Crashes the game

### Crash Log

https://s.dinnerbeef.com/gOXe5/wAnObILE81.txt

**Comment by BluSunrize** [comment]
Looks like something in your mod list (or a datapack?) is causing a tag to be empty.

Do you have anything in your log before the crash that indicates tags not loading?

**Comment by DinnerBeef** [comment]
https://s.dinnerbeef.com/gOXe5/zuVisUwE49.txt/raw

**Comment by BluSunrize** [comment]
Hmm, pretty solid chance that something in KubeJS breaks stuff here.
IE isn't in the Direwolf pack by default, afaik, so likely they didn't account for it when writing their KubeJs scripts...

**Comment by DinnerBeef** [comment]
Hmm, interesting. I am the pack dev for that pack dev. Guess I will have to look into the issue a bit more then.

**Comment by BluSunrize** [comment]
Closing this, assuming to be invalid.
