### ISSUE TITLE
Crash with Chargingstation

### ISSUE THREAD

**Issue by Gensokian** [BluSunrize/ImmersiveEngineering#5784]
### Minecraft Version

1.20.1

### Immersive Engineering Version

ImmersiveEngineering-1.20.1-10.0.0-169

### How did it happen?

# Step 0.5
Install Rubidium and Occulus (I dont think Oculus is needed)

# Step 1
Add a **magnetic glove** and **shock emitters** to a **heavy plated shield**

# Step 2
Shove **upgraded shield** into **charging station**

# Step 3
~~Profit!~~ Crash to desktop

---
Note:
I believe this is caused due to the rendering changes in Occulus/Rubidium, but after reading the crash it seems that IE is using a different vertexBufferWriter which is required for compatibility with sodium (in this case Rubidium)

Note 2:
~~I was unable to select 1.20.1 as a version in the dropdown; I also highly doubt that this new version is no longer supported 🙃 in case of unsupport; you shall gladly close this issue :)~~ Update: manually changed this

Note 3:
Whilst writing Note 1 I felt like an AI writing it.... help...

### Crash Log

https://pastebin.com/B7iqmFDB

**Comment by Gensokian** [comment]
Addition:
This crash happens with anything inside the chargingstation whilst rubidium is installed

**Comment by XFactHD** [comment]
You need to update Rubidium. Sodium made a change a while ago that entirely breaks any mod that needs to apply special behaviour to item rendering and doesn't account for Sodium's change explicitly. This has since been mitigated in Sodium and Rubidium.

**Comment by Gensokian** [comment]
Might this be a Sodium change which has never been implemented to the forgeport, rubidium? Anyhoo, closing due to user error 🙃

**Comment by XFactHD** [comment]
No, this was definitely implemented in Rubidium, I myself was fighting this issue with my own projects and validated that Rubidium 0.7.0 and later do fix it.
