### ISSUE TITLE
Garden cloche crashes the game with Rubidium

### ISSUE THREAD

**Issue by reshmaretu** [BluSunrize/ImmersiveEngineering#5785]
### Minecraft Version

1.20.1

### Immersive Engineering Version

ImmersiveEngineering-1.20.1-10.0.0-169

### How did it happen?

powering a garden cloche with any crops inside crashes the game with rubidium 1.20.1-0.7.0+

### Crash Log

https://pastebin.com/gjVZX1qh

**Comment by malte0811** [comment]
This is a bug in Rubidium, not in IE. There is a [fork of Rubidium](https://www.curseforge.com/minecraft/mc-mods/embeddium) which fixes this as well as some other issues, I would recommend switching to that. However, that fork is still not officially supported by IE (same as with other Sodium ports), so bugs only happening with Sodium ports will not necessarily be fixed.

**Comment by reshmaretu** [comment]
oh thank you.
