### ISSUE TITLE
Crash after form a multiblock Squeezer

### ISSUE THREAD

**Issue by dhgameryt** [BluSunrize/ImmersiveEngineering#5786]
### Minecraft Version

1.20.1

### Immersive Engineering Version

1.20.1-10.0.0-169

### How did it happen?

After right click with hammer on the barrel of the Squeezer to form the multiblock, it crash without any log in the lastest or crash report.

After that, game instant crash when i enter giving a crash report, making the world usesless, lucky i use simple backups mod, i think its a incompatibility issue with Rubidium mod.

### Crash Log

https://gist.github.com/dhgameryt/4705f447471fdd85fb02cfe72bb3016e

**Comment by malte0811** [comment]
This is a bug in Rubidium, not in IE. There is a [fork of Rubidium](https://www.curseforge.com/minecraft/mc-mods/embeddium) which fixes this as well as some other issues, I would recommend switching to that. However, that fork is still not officially supported by IE (same as with other Sodium ports), so bugs only happening with Sodium ports will not necessarily be fixed.

**Comment by dhgameryt** [comment]
i understand, thanks.
