### ISSUE TITLE
1.20.1 drill can't mine 3x3

### ISSUE THREAD

**Issue by lordi-erez** [BluSunrize/ImmersiveEngineering#5788]
### Minecraft Version

1.20.1

### Immersive Engineering Version

1.0.0.0-169

### Expected Behavior

when drill is set to mine multiple blocks, it mines a 2x2 or a 3x3

### Actual Behavior

when a drill is set to multiple blocks, it mines just the block im looking at

### Steps to reproduce

1. i got a drill
2. i put a drill head
3. i made sure it's set to multiple-block mode
4. i mined a block w/ the indicator showing a 3x3 or 2x2 area

### Debug Crash Log

https://paste.ee/p/Oa3gx

**Comment by BluSunrize** [comment]
Works perfectly fine on my end.

Can you try it in an instance with just Immersive Engineering installed?
If the issue persists there, a screenshot / video would be helpful.

**Comment by malte0811** [comment]
Did you also add fuel (biodiesel) to the drill? It currently shows the breaking animation on all blocks even if it does not have fuel and therefore only breaks the center block. I will change that to only show the breaking animation on the additional blocks if there is some fuel.

**Comment by BluSunrize** [comment]
Closing this due to lack of user input
