### ISSUE TITLE
[Suggestion] ... can you add an option to turn off illagers spawning?

### ISSUE THREAD

**Issue by SonicTheHedgehog58987276** [BluSunrize/ImmersiveEngineering#5789]
### Explain your idea

.

**Comment by BluSunrize** [comment]
They only spawn after you kill one of them with an IE weapon.
The advancement tells you about this.

If you don't want stronger enemies, don't engage them with strong weapons =P

**Comment by SonicTheHedgehog58987276** [comment]
i'm no longer allowed to play with guns in mc

**Comment by SonicTheHedgehog58987276** [comment]
unless they're space guns

**Comment by SonicTheHedgehog58987276** [comment]
or if i'm only using flares or firework cartridges as long as i don't shoot living targets
