### ISSUE TITLE
[Suggestion] FluidValve/WallTap

### ISSUE THREAD

**Issue by mindforger** [BluSunrize/ImmersiveEngineering#579]
How about an hand/redstone driven valve with a nifty turning animation?
It's hammerable to make it go 90° in any direction or straight
it shall only autoconnect to 2 subsequent placed ot detected IFluid/Pipes 
it shall only has always 2 in/out ports

the idea is to control the flow of liquids 
and additionally to have some sort of fluid tap function for auto ejecting fluid containers, so i could place it on a IE tank and whenever i have an portable Tank f.E. i can place it underneath, open the valve/tap and fill the portable tank without having a partial tube sticking out of the botom of the tank that occasionally connects to the tank i place beneath

It could function like the seared faucet from tinkers construct. Just more pretty!

**Comment by XFactHD** [comment]
+1 for the idea
There could be multiple versions of it:
1: Pipeline Valve: Does only connect to IE pipes and can control the flow
2: Intersection Valve: Would be usable if a setup like described above would be used in the middle of a pipeline
3: Direction Valve: Does only connect to IE pipes. Needs at least three pipes and can switch to which of n pipes the fluid goes or which of n pipes supplies the output pipe.

PS: I know that the naming is awful 😏.

**Comment by Sukasa** [comment]
Having a two-way valve, and a 3-way diverting L-valve, would be pretty cool.

A two-way valve (which would probably be a butterfly valve, for ease of crafting) is simply a plate in the pipe connected to a lever.  Turn the lever to open or close the valve..  or tack on an actuator and control it remotely with redstone!

A 3-way Diverting L-valve is a valve where a valve is shaped a bit like this: \_|_.  It uses the top connection as Common, and either of the side connections is routed to the common at one time, with the other connection being blocked off.  Careful not to dead-head your pumps if you use one of these valves, it' very bad for the motors!
