### ISSUE TITLE
[1.20.1] Items output on to belt as dropped item using either extractor or hopper

### ISSUE THREAD

**Issue by cranberriez** [BluSunrize/ImmersiveEngineering#5790]
### Minecraft Version

1.20.1

### Immersive Engineering Version

10.0.0-169

### Expected Behavior

Items will be smoothly put onto the belts as a texture with animation like with the press.

### Actual Behavior

Items are dropped onto the belt when using either a hopper or extracting belt. This shouldn't be caused by the hopper dropping items.

### Steps to reproduce

1. First I connected a hopper or extracting belt to a chest.
2. I connected said hopper to a regular belt
3. Item is output onto the belt as dropped item

[https://youtu.be/4RCL-xENLUc](https://youtu.be/4RCL-xENLUc)

### Debug Crash Log

https://pastebin.com/4H40Pv4i

**Comment by mindforger** [comment]
isn't that how belts are working by default? the animation of items as flat objects on the machine-belt is just to keep them visible as they entered the machine inventory and can not be picked up in contrast to the items on the normal belts which can be picked up

**Comment by BluSunrize** [comment]
This is intended behavior.

Our belts simply move entities around. They have no internal storage, and will never receive it. Any item "inserted" into a belt, will be spawned as an entity upon it.

This is by design.
