### ISSUE TITLE
Can this mod be unofficially ported too 1.20.1?

### ISSUE THREAD

**Issue by Acat1234** [BluSunrize/ImmersiveEngineering#5792]
### Explain your idea

^

**Comment by BluSunrize** [comment]
This mod is released on 1.20.1 aldready, you can find it here:

https://www.curseforge.com/minecraft/mc-mods/immersive-engineering/files/4782978

https://modrinth.com/mod/immersiveengineering/version/1.20.1-10.0.0-169

**Comment by Acat1234** [comment]
like for forge

**Comment by Acat1234** [comment]
not neoforge

**Comment by BluSunrize** [comment]
NeoForge was founded by ex-Forge teammembers. They left the project for good reason and forked it, to deliver better work with better leadership.

We will be staying on NeoForged.

**Comment by Acat1234** [comment]
well it works on forge for me at least so ill take it
