### ISSUE TITLE
[1.19.2] Mineral Veins don't generate in a Skyblock Enviroment

### ISSUE THREAD

**Issue by ParaMotor** [BluSunrize/ImmersiveEngineering#5793]
### Minecraft Version

1.19.2

### Immersive Engineering Version

9.2.3-167

### Expected Behavior

Mineral Veins should generate in a Skyblock Enviroment.

### Actual Behavior

Mineral Veins do not generate in a Skyblock Enviroment.

### Steps to reproduce

1. Create a new Skyblock World (either use Vanilla Superflat and delete all block layers or use Mod "SkyblockBuilder-1.19.2-4.2.18".
2. Check surrounding area for Mineral Veins
3. Find nothing

I made a second test on a cleaner Minecraft Instance - it doesn't work either: https://pastebin.com/3hgRLX2R

### Debug Crash Log

https://pastebin.com/LtY8y18w

**Comment by TeamSpen210** [comment]
Well, this kinda makes logical sense - it's not like there's any stone to contain minerals. But gameplay wise that's not that satisfying if you manage to build one.

**Comment by BluSunrize** [comment]
Mineral veins spawn with world gen. A skyblock has no world gen, and thus the veins don't spawn.

This is a sideeffect based on how we perform generation of veins, and there isn't much to be done about it.
