### ISSUE TITLE
 no textures with shaders 1.19.2

### ISSUE THREAD

**Issue by idkwhoisit** [BluSunrize/ImmersiveEngineering#5794]
### Minecraft Version

1.19.2

### Immersive Engineering Version

1.19.2-9.2.3-167

### Expected Behavior

displaying textures of a spinning mill and a water wheel with shaders enabled

### Actual Behavior

no textures with shaders 

### Steps to reproduce

I put a block

didn't see the texture

tried other shaders

did not help
![Screenshot_2](https://github.com/BluSunrize/ImmersiveEngineering/assets/61099534/dc26b4fe-1fc0-462b-b0a5-926b38b68ce9)
![Screenshot_1](https://github.com/BluSunrize/ImmersiveEngineering/assets/61099534/21e7ca24-7103-4487-a357-ccf50a0ffece)

turned off shaders and textures appeared

### Debug Crash Log

https://gist.github.com/idkwhoisit/60e194ce2a6a699b26325ffabbae15e7

**Comment by BluSunrize** [comment]
Yeah shaders aren't supported.

You can try to tinker with the options for Rubidium or Oculus, and you can try to look at IE's client config and see if changing options related to the render buffer helps you.
