### ISSUE TITLE
[Suggestion] Add configurable biome whitelist/blacklist to mineral deposits

### ISSUE THREAD

**Issue by dudebehinddude** [BluSunrize/ImmersiveEngineering#5795]
### Explain your idea

Currently, you can control how mineral veins spawn by dimension, weight, and fail chance. That gives a decent amount of customization, but it doesn't let you do things like add an ore deposit that consists mostly of different kinds of prismarine in the ocean, add deposits of terracotta to badlands, or add mineral deposits in the end that only exist on the end islands themselves instead of in the void. All of those are vanilla uses for this that I think could integrate into the base mod quite well, but this would also be very useful for modpack creators as well. (Also, this is something that Immersive Petroleum has implemented for fluid reservoirs.) For instance, in a modpack I am creating, I want to encourage exploration (and also increase immersion) by changing the uranite mineral deposit to only spawn in the toxic caves biome from alex's biomes, but that is not really possible with the current system.
The only issue that I can see with this is with how biomes can change depending on the height, although I think the best ways to deal with this would be to either check the biome at a certain point (like y=-64 or something) or to consider all the biomes vertically when choosing what deposits spawn there (so if you had a lush cave under an ocean, deposits that either spawn in both oceans or lush caves could generate).

**Comment by BluSunrize** [comment]
Closed by #5902, will be part of the 1.20.4 release
