### ISSUE TITLE
Colliding entity with block crash

### ISSUE THREAD

**Issue by YukiRainee** [BluSunrize/ImmersiveEngineering#5799]
### Minecraft Version

1.20.1

### Immersive Engineering Version

ImmersiveEngineering-1.20.1-10.0.0-169.jar

### How did it happen?

Attempting to create a world or loading an existing one causes the game to crash with Colliding entity with block

### Crash Log

https://mclo.gs/SlBNXhx

**Comment by malte0811** [comment]
Something is very strange here, every level should have a network attached to it. Please reproduce this on NeoForge\* and provide a full debug log.

\* LexForge is not supported by IE, and  47.2.1 is not an existing NeoForge version.

**Comment by YukiRainee** [comment]
seems like its working fine on neoforge.. I guess I should begin moving everything over to neoforge... just gotta get used to the modrinth ui despite it still being a bit of a learning curve

**Comment by YukiRainee** [comment]
[Crash log](https://mclo.gs/TsMLdrS) seems like its happening again I have neoforge installed version 47.1.79

https://mclo.gs/HBmEQhB
