### ISSUE TITLE
Rightclicking on a fluid tank places liquid in the world

### ISSUE THREAD

**Issue by angelnc1989** [BluSunrize/ImmersiveEngineering#580]
https://www.youtube.com/watch?v=uZC2rSxdjXQ&feature=youtu.be

**Comment by cobra** [comment]
fixed already, wait for the next release.

**Comment by angelnc1989** [comment]
Nice. Another related thing is, in creative mode it places the bucket in the world and in the tank when rightclicking. I guess it's the same issue so it's probably fixed too.
