### ISSUE TITLE
[1.20.1] Crusher subtitle does not play (and a related accessibility suggestion)

### ISSUE THREAD

**Issue by EvergreenSystems** [BluSunrize/ImmersiveEngineering#5800]
### Minecraft Version

1.20.1

### Immersive Engineering Version

1.20.1-10.0.0-169

### Expected Behavior

When the crusher activates, one would expect a subtitle to play (in the past I believe it was "crusher rumbles").

### Actual Behavior

In the current version, no subtitle plays. This seems isolated to the crusher, as other machines that have an associated subtitle such as the metal press behave as normal. 

On a related note: in the past, the subtitle has played once upon activation, but has not persisted if the machine remains on (such as when processing multiple stacks of items, the sub plays for about 5 seconds and then does not play again). For someone who relies on subtitles (like myself, very hard of hearing), this makes determining if the crusher is running difficult as I have to climb the machine and visually verify if it is on.

What I propose is either 1) ensuring that the subtitle is persistent (though this poses another issue, that of the sub cluttering up the subtitle box, causing an already difficult to parse system to be even more annoying to rely on ;-;), or 2) putting some sort of indicator on the texture of the multiblock, such as a light on the end of the crusher that accepts power or by the output. I don't by any means expect or demand such a feature, but as someone who is very accessibility minded the crusher has always posed a bit of an issue.

### Steps to reproduce

(neoforge version 47.1.79)

1. Power a crusher, and insert items for processing
2. Observe the resulting subtitles; the crusher will not produce a sub, while other machines will. This is especially evident when the crusher is underpowered, and repeatedly powering on and off as it attempts to process. I would expect a subtitle each time it activates, but none are produced.

### Debug Crash Log

https://gist.github.com/Shedao-Shai/14a999d6622f9062ae84adebe6add852

**Comment by EvergreenSystems** [comment]
For example, have an indicator similar to the red or green lights on the side on the front face (where the vent is, probably above it) that actually behaves like an indicator. 
![image](https://github.com/BluSunrize/ImmersiveEngineering/assets/23658767/163409dc-f6cf-4833-b446-403259982936)

**Comment by BluSunrize** [comment]
@voidsong-dragonfly this seems to affect the Improved Blastfurnace as well.
I suspect it may be due to changes to the sounds in your recent PRs?
Do you have the capability (and spoons) to look into this, or should I?

**Comment by BluSunrize** [comment]
Oh this is reproducable in 1.19.2 btw.

**Comment by BluSunrize** [comment]
Fixed for upcoming releases of 1.19 and 1.20
