### ISSUE TITLE
Gunpowder Barrel bug

### ISSUE THREAD

**Issue by mournfulBenn** [BluSunrize/ImmersiveEngineering#5801]
### Minecraft Version

1.19.2

### Immersive Engineering Version

1.18.2-8.4.0-161

### How did it happen?

Gunpowder Barrel have a high chance of throwing a ConcurrentModificationException and crashing on the player's side when they are blasting rocks of TerraFirmaCraft.

And if the barrel is in bud infinite activation (e.g. load it into a tnt replicator), there is a high chance that the player who loaded the machine chunks will flashback, forming a forbidden zone.

The only single player solution is to delete the block, find a backup or let the machine blow itself up (at least crash dozens of times), but I have never tested the server.

### Crash Log

https://pastebin.com/hdpMg5CY

**Comment by malte0811** [comment]
This is fixed on 1.19.2 (d16e7cb4910d5bb281f2b1d2c6467388e2bc18b8), and 1.18.2 is not supported any more.
