### ISSUE TITLE
The mod does not start on 1.12.2

### ISSUE THREAD

**Issue by DocktorWindows** [BluSunrize/ImmersiveEngineering#5802]
### Minecraft Version

1.19.2

### Immersive Engineering Version

0.12.98

### How did it happen?

I created a build with the Immersive engenering mod and launched it. As a result, the mine crashed, it was the Phosphor mod, I deleted it, I launch a crash in the crash report, there is an error with immersive engenering, I replace it with the old version of minecraft, it starts, but mods requiring immersive engenering require a new version

### Crash Log

1

**Comment by BluSunrize** [comment]
Support for 1.12 was ended about 4 years ago.
There's nothing we can do for you, our development focus is on the current versions of Minecraft.
