### ISSUE TITLE
Crash when try to break bottling_machine

### ISSUE THREAD

**Issue by dhgameryt** [BluSunrize/ImmersiveEngineering#5805]
### Minecraft Version

1.20.1

### Immersive Engineering Version

1.20.1-10.0.0-169

### How did it happen?

occurs at the instant i left click in (its not necesarry finish the block break, it happen instantly)  the bottling_machine multiblock
This happens whether you have the embeddium, oculus or you do not have either of the two, if you do not have those mods installed there is no crash report.
i upload the crash report (when embeddium its installed)
and the latest log when embeddium and oculus its not installed
https://gist.github.com/dhgameryt/195c554c8d4beea36430f85db6975cb8 (latest)

### Crash Log

https://gist.github.com/dhgameryt/3d02a4d076bcd1a5ddcdda8a5362bfff

**Comment by BluSunrize** [comment]
Much like Optifine, Oculus is not supported!
