### ISSUE TITLE
Getting buckets out of thin air

### ISSUE THREAD

**Issue by BloodInAs** [BluSunrize/ImmersiveEngineering#5807]
### Minecraft Version

1.20.1

### Immersive Engineering Version

ImmersiveEngineering-1.20.1-10.0.0-169

### Expected Behavior

When trying to craft water capsules, the capsule is taken away and a filled capsule is given 

### Actual Behavior

Duplicating buckets through the immersive collector. When you try to craft water capsules, the capsule is taken away, and a filled capsule and an empty bucket are given

### Steps to reproduce

https://youtu.be/cf50fuyvIyY

### Debug Crash Log

-

**Comment by BluSunrize** [comment]
What mod are those capsules from?

**Comment by BloodInAs** [comment]
https://wiki.industrial-craft.net/index.php/Water_Cell
ic2

**Comment by BluSunrize** [comment]
Can you please provide the debug crash that the report asked for?

**Comment by BloodInAs** [comment]
к сожалению такую информацию предоставить не могу

**Comment by BloodInAs** [comment]
Unfortunately I can't provide debugging

**Comment by BluSunrize** [comment]
Yes you can. Generate a debug crash by holding down F3 and C for 10 seconds.

The issue report template told you to do this and you havent' yet.

**Comment by BloodInAs** [comment]
[21.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/13367635/21.txt)

**Comment by BluSunrize** [comment]
Industrial Craft 3 is not a mod I am familiar with. The IC2 team has never released that.
I have to assume that this mod is the source of the issue. Where did you get it from?

**Comment by BloodInAs** [comment]
This is a note from our developer.

**Comment by BluSunrize** [comment]
As far as I am aware, "Industrial Craft 3" is an unlicensed mod that has taken both name and assets from the original creators without permission to do so.
Its source code is also not visible anywhere, and its downloads are only available to a specific Russian Minecraft community, making it impossible for us to debug this further.

I am hereby labeling "Industrial Craft 3" as unsupported, and closing this issue.
