### ISSUE TITLE
1.20.1 Infinite receipt of pillars

### ISSUE THREAD

**Issue by BloodInAs** [BluSunrize/ImmersiveEngineering#5808]
### Minecraft Version

1.20.1

### Immersive Engineering Version

ImmersiveEngineering-1.20.1-10.0.0-169

### Expected Behavior

https://youtu.be/M7zVN84h7KA

The proliferation of pillars is endless, the vulnerability is serious because you can get steel and aluminum in this way endlessly
"immersiveengineering:alu_post' 
'immersiveengineering:treated_post'
'immersiveengineering:steel_post'
"

### Actual Behavior

-

### Steps to reproduce

https://youtu.be/M7zVN84h7KA

### Debug Crash Log

-

**Comment by BluSunrize** [comment]
Can you reproduce this with a different tool to whatever you are using there?

Also please provide the debug crash as requested.

**Comment by BloodInAs** [comment]
[r.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/13367187/r.txt)
any tool, including vanilla pickaxe and ax

**Comment by BluSunrize** [comment]
You're not running on NeoForged, we only built for that.

Can you please try to replicate this issue with a NeoForge instance instead of Forge?
