### ISSUE TITLE
Incorrect operation of the filling machine

### ISSUE THREAD

**Issue by DesiRe234** [BluSunrize/ImmersiveEngineering#5809]
### Minecraft Version

1.20.1

### Immersive Engineering Version

ImmersiveEngineering-1.20.1-10.0.0-169

### Expected Behavior

Filling machine: If you throw more than 1 capsule, it will take everything and give out all the capsules.
As for the animation, it is expected that the capsules will not go beyond the mechanism

### Actual Behavior

Filling machine: If you throw more than 1 capsule, it will take everything and give out only one.
Animation is broken, capsules go beyond the mechanism
Video: https://youtu.be/t1EjpwegLuk

### Steps to reproduce

Assemble the design of the filling mechanism, then throw more than one capsule into it.

### Debug Crash Log

ㅤ

**Comment by BluSunrize** [comment]
Please provide a debug crash, as instructed by the issue template.

**Comment by DesiRe234** [comment]
https://pastebin.com/KdKSXzVZ

**Comment by BluSunrize** [comment]
Where did you download this modpack from?
I am unable to find a source on the IndustrialCraft 3 mod in your modlist.

I have to assume that their side of the code is not operating correctly, and I also have reason to believe that they are in violation of IndustrialCraft's license, using their assets without permission.

**Comment by BluSunrize** [comment]
As far as I am aware, "Industrial Craft 3" is an unlicensed mod that has taken both name and assets from the original creators without permission to do so.
Its source code is also not visible anywhere, and its downloads are only available to a specific Russian Minecraft community, making it impossible for us to debug this further.

I am hereby labeling "Industrial Craft 3" as unsupported, and closing this issue.
