### ISSUE TITLE
Drill head + saw vanish

### ISSUE THREAD

**Issue by Acat1234** [BluSunrize/ImmersiveEngineering#5811]
### Minecraft Version

1.20.1

### Immersive Engineering Version

Latest

### Expected Behavior

For it to not vanish

### Actual Behavior

Poof gone

### Steps to reproduce

1. play multiplayer
2. get a drill or saw with a head
3. it vanishes

### Debug Crash Log

idk

**Comment by BluSunrize** [comment]
Did you spawn the items in creative mode?

Also please provide a debug crash, as instructed by the issue template.

**Comment by Acat1234** [comment]
sorry

**Comment by BluSunrize** [comment]
...sorry what?
Please *provide the crashlog* and answer the question I asked. Otherwise we can not help you debug this further!

**Comment by Acat1234** [comment]
It doesnt crash

**Comment by mindforger** [comment]
![grafik](https://github.com/BluSunrize/ImmersiveEngineering/assets/2683555/b9109ec5-24d5-4033-9760-286f2ec51d2e)

**Comment by Acat1234** [comment]
oh but the other player wont play so I cant test it

**Comment by Acat1234** [comment]
Oh notepad wont work so I cant send the data

**Comment by BluSunrize** [comment]
Then we can't help you
