### ISSUE TITLE
Server Crashed Ticking entity

### ISSUE THREAD

**Issue by mkZH0740** [BluSunrize/ImmersiveEngineering#5813]
### Minecraft Version

1.20.1

### Immersive Engineering Version

1.20.1-10.0.0-169

### How did it happen?

Unfortunately this crash happened on a server, and I was not online when the crash happened. I would like to ask if this is a compatibility issue or something else. Thank you!

### Crash Log

https://pastebin.com/bttwGsKJ

**Comment by BluSunrize** [comment]
We built IE against NeoForge, not the old Forge.

Can you please test with that and see if the issue persists?

**Comment by mkZH0740** [comment]
> We built IE against NeoForge, not the old Forge.
> 
> Can you please test with that and see if the issue persists?

Thank you for the reply! We are not sure how to reproduce this issue and it never happened again in the past few days, so I'll just close this issue for now.
