### ISSUE TITLE
Magnet upgrade for the Capacitor Backpack

### ISSUE THREAD

**Issue by AbsorbingSafe11** [BluSunrize/ImmersiveEngineering#5817]
### Explain your idea

Simple idea of an item magnet upgrade (that uses energy) for the capacitor backpack to increase utility, with the look on the backpack being either a large horseshoe shaped magnet or a more realistic electromagnet. (whichever looks better and/or is more feasible)

**Comment by AbsorbingSafe11** [comment]
Sorry in advance, for any Github faux pas, as I don't use the site very often

**Comment by RosaryMala** [comment]
I feel like this would require first fixing magnets picking up things from belts.

**Comment by AbsorbingSafe11** [comment]
I thought that issue was fixed ages ago, but if not, then it would help IE set a standard for other magnet mods to not pick stuff up from conveyor belts, as well as test issues from its own method of resisting magnets

**Comment by BluSunrize** [comment]
IE *has* set that standard.
Back in the day, Vazkii (Botania), WayOfTime (Blood Magic), myself and some other devs agreed on how to tag an item as "invalid for magnet pickup".
We've been going strong with that, it's not our fault when a bunch of other mods don't put that effort in >_>

**Comment by AbsorbingSafe11** [comment]
so I was right in thinking it got fixed, but other modders broke it
good to know

**Comment by BluSunrize** [comment]
@RosaryMala do you know _which_ magnets are having problems with IE conveyors?

Would be nice if I could contact the respective mod devs and ask them to respect the `PreventRemoteMovement` NBT tag

**Comment by RosaryMala** [comment]
Yeah, it's https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks

**Comment by BluSunrize** [comment]
Cool, I've already opened an issue with them =)
