### ISSUE TITLE
Conveyer Belts Issues

### ISSUE THREAD

**Issue by ravenstormchaser** [BluSunrize/ImmersiveEngineering#582]
Currently whenever i put down a new belt im running into issues. When put down it displays, and runs, in the direction I'm facing which is good. If i attempt to change the orientation with the hammer though the belt displays having changed but the items still route the old way. Made trying to set up my crusher a nightmare since I couldn't figure out what was going on till i loaded out and came back to see the belts facing different directions.

**Comment by beringtom** [comment]
Can confirm this with version 0.6.0, texture is rotated, but the belt "function" is not  :)

**Comment by mindforger** [comment]
i would guess this is related to the wires, that do not update properly, stay tuned
https://github.com/BluSunrize/ImmersiveEngineering/issues/585

**Comment by cobra** [comment]
Is this a server or singleplayer setup?

**Comment by beringtom** [comment]
Server setup here

**Comment by ravenstormchaser** [comment]
Single player setup here.

**Comment by cobra** [comment]
Reproduced in my dev environment both in single- and multiplayer. Updating adjacent blocks doesn't help.

**Comment by Sukasa** [comment]
I found that no matter what I did with the hammer, the belts never rotated and would have to be broken / placed again in the right orientation to work propery, in SSP.

**Comment by cobra** [comment]
That's exactly what I'm looking at just now. WTF?

**Comment by Sukasa** [comment]
I haven't tried it in SMP, but I had similar issues in 0.5.4 with items getting stuck.  I originally chalked it up to bugs with ramps and mildly worked around it, but now I'm thinking it was due to this bug.

**Comment by cobra** [comment]
Yep, this issue seems to be the root cause for a lot of problems, including bottling machines not forming.

**Comment by cobra** [comment]
I've found the bug. Still needs a fix, but I'm fairly certain this one is dead rather soon. The bottling machine claims it can be formed when clicking a single conveyor, catching the rightclick and preventing it from reaching the conveyor itself.

**Comment by cobra** [comment]
aaaaand it's fixed.

**Comment by Sukasa** [comment]
You're making me a happy crafter :)
