### ISSUE TITLE
[Suggestion] add JEI support for the diesel gen (viable fuels indicator)

### ISSUE THREAD

**Issue by EvergreenSystems** [BluSunrize/ImmersiveEngineering#5821]
### Explain your idea

(discord convo that this originates from: https://canary.discord.com/channels/270295681829306369/339127815666532352/1183929293437415444)

The diesel generator by default has two viable fuels (both from IE); however, some fluids from other mods also function as fuels, but determining what fluids are usable is difficult. My (and Angle's) suggestion is: either list some common fuels from other mods in the manual, or add JEI support to provide such details (since this is IE we are talking about there's no need for statistics on efficiency or etc, just a  list of accepted fluids).
This is purely a QoL suggestion, but one that could add a level of accessibility to the diesel gen that is otherwise lacking in heavily modded scenarios. ^,^

**Comment by BluSunrize** [comment]
It's been added to the manual instead!
