### ISSUE TITLE
missinng tags

### ISSUE THREAD

**Issue by Mikecolle** [BluSunrize/ImmersiveEngineering#5823]
### Minecraft Version

1.19.2

### Immersive Engineering Version

9.2.3-167

### Expected Behavior

items being craftable

### Actual Behavior

unable to craft item due to missing tag 
item is displayed as a red crossed circle and name Empty Tag: forge:plates/plastic

### Steps to reproduce

1.19.2 strux smp pack im unable to craft anything with plastic

### Debug Crash Log

n/a

**Comment by BluSunrize** [comment]
That means something in that pack is impacting / breaking the loading of tags.

Try it in an instance with just IE, it should work fine.
This needs to be reported to the makers of the modpack =)
