### ISSUE TITLE
The railgun can destroy worlds (HELP ME PLS!)

### ISSUE THREAD

**Issue by ELJOKER900** [BluSunrize/ImmersiveEngineering#5825]
### Minecraft Version

1.20.1

### Immersive Engineering Version

1.20.1-10.0.0-169

### How did it happen?

when I was in my world with many optimizing mods (not the optifine because I had an incompatible mob) and then I was going to use the rail loader but when I put it to load the world froze and I crashed, and I can't go back but it wasn't an important one , here the mods screenshot 
![Captura de pantalla 2023-12-16 161208](https://github.com/BluSunrize/ImmersiveEngineering/assets/121907632/b39587fe-9bd6-44bc-8acc-d0c9973aeb81)

### Crash Log

https://pastebin.com/GMLGPaHU

**Comment by ELJOKER900** [comment]
I think the problem is rubidium because at the beginning of the log it says -- Head --
Thread: Render thread
Suspected Mods:
Rubidium (rubidium), Version: 0.7.1a
at TRANSFORMER/rubidium@0.7.1a/net.caffeinemc.mods.sodium.api.vertex.buffer.VertexBufferWriter.createUnsupportedVertexConsumerThrowable(VertexBufferWriter.java:46)
 
Immersive Engineering (immersiveengineering), Version: 1.20.1-10.0.0-169
Issue tracker URL: https://github.com/BluSunrize/ImmersiveEngineering/issues
at TRANSFORMER/immersiveengineering@1.20.1-10.0.0-169/blusunrize.immersiveengineering.client.fx.CustomParticleManager.render(CustomParticleManager.java:75)
Stacktrace:

**Comment by ELJOKER900** [comment]
Yeah the problem is rubidium but pls try to add an compatibility

**Comment by BluSunrize** [comment]
Rubidium isn't supported, much like Optifine. Also you're using Forge, and we only built for NeoForge.
Nothing much we can do here.
