### ISSUE TITLE
[Suggestion] Allow Collapsible Glider (and Elytra?) as a Accumulator Backpack upgrade.

### ISSUE THREAD

**Issue by OhBrod** [BluSunrize/ImmersiveEngineering#5826]
### Explain your idea

This would allow the glider to work in the back slot so we can use it with an armor piece, maybe disable the ability to attach the backpack to armor if the glider is installed for balancing.
Alternatively maybe simply allow the glider to attach to armor like the backpack.

**Comment by BluSunrize** [comment]
Nah.

I like vanilla forcing you to make the choice between armor and flight. I don't mind that extending to the accumulator either.
