### ISSUE TITLE
[Suggestion] ... Realistic Substations

### ISSUE THREAD

**Issue by NikoG12** [BluSunrize/ImmersiveEngineering#5827]
### Explain your idea

1. It would be great if there was LV ,MV and HV busbars in the game that transmit RF. This would make building large substations look cleaner and realistic as seen below:

![What-is-Electrical-Busbar-_-Types-Of-Electrical-Busbar-_-Advantage-Disadvantage](https://github.com/BluSunrize/ImmersiveEngineering/assets/154694061/e5658d83-6fa2-4bc8-8686-544eb476ce6d)

2. Current transformers should output a Redstone signal proportional to the rf that passes through it so we can get an accurate reading on gages from the control engineering mod.

**Comment by malte0811** [comment]
> 2. Current transformers should output a Redstone signal proportional to the rf that passes through it so we can get an accurate reading on gages from the control engineering mod.

This already exists, but you need to use a comparator to get the value out of the CT.

**Comment by BluSunrize** [comment]
I'm not adding busbars.
