### ISSUE TITLE
Crashs with Sodium / Rubidium

### ISSUE THREAD

**Issue by RinCat** [BluSunrize/ImmersiveEngineering#5828]
### Minecraft Version

1.20.1

### Immersive Engineering Version

10.0.0-169

### How did it happen?

I visit a player home with a lot of Immersive Engineering blocks.
`java.lang.IllegalArgumentException: The class blusunrize.immersiveengineering.client.utils.TransformingVertexBuilder does not implement interface VertexBufferWriter, which is required for compatibility with Sodium`

### Crash Log

https://gist.github.com/RinCat/c19fa858e3c32895f3a7ba918865a43e

**Comment by BluSunrize** [comment]
Rubidium is not supported. You can try Embeddium and see if that works better, but overall we do not work around mods that impact rendering.

**Comment by RinCat** [comment]
Thanks. Embeddium seems works good with Immersive Engineering.
