### ISSUE TITLE
Crusher does not work

### ISSUE THREAD

**Issue by SergioInToronto** [BluSunrize/ImmersiveEngineering#5830]
### Minecraft Version

1.20.1

### Immersive Engineering Version

10.0.0-169

### Expected Behavior

Crusher should process or destroy items

### Actual Behavior

Nothing happens. See video: https://www.youtube.com/watch?v=MwWqhZ6i30I

Items fall through the machine as if it weren't there. I can collect the items by walking around behind the crusher.

### Steps to reproduce

1. Build machine
2. Let machine charge to full
3. Throw in ores, or any items
4. Expect it to process/destroy items

### Debug Crash Log

https://gist.github.com/SergioInToronto/82c4efff1fb73c7a98940c87230c448f

**Comment by SergioInToronto** [comment]
OK they don't crush players, and they don't destroy items, but they do work. My apologies for the misleading bug report.

**Comment by Vulkanus-Maximus** [comment]
G'day!

I am now having the same issue. I know this is marked as completed but I'm still hoping for a fix; 
There is power (full 32 kFE) and levered to ON, but the Crusher is not crushing cobble stone blocks (nor any other blocks), not any ores, and jumping into it does not even harm me.
I tested the Crusher out both on my survival world and on my creative world, but unfortunately to no avail.
Modpack: DeceasedCraft - Modern Zombie Apocalypse:
Game Version: 1.18.2
forge: 40.2.4
Picture:

![2024-07-15_14 36 52](https://github.com/user-attachments/assets/5c5b72d3-74cf-485c-88e6-5f7ceab61771)
