### ISSUE TITLE
[Suggestion] ... Please optimize the drill. It's eating the cpu for my server alive.

### ISSUE THREAD

**Issue by BokChewy** [BluSunrize/ImmersiveEngineering#5831]
### Explain your idea

IE version: 1.20.1-10.0.0-169
MC version: 1.20.1
Forge Version: 47.2.0 (with sinytra connector)

I've been having constant TPS explosions on my server for the last week or two which have caused multiple timeout related crashes. I've come to find out the sources is when a player uses the drill.

The server usually only takes up 30-50% of my cpu, but when someone is using the drill, that shoots up to 100%. 

(player seen here with TPS reading via ['observable'](https://www.curseforge.com/minecraft/mc-mods/observable)
![2023-12-26_21 38 35](https://github.com/BluSunrize/ImmersiveEngineering/assets/109487599/261bae07-80e0-41b9-970d-5538e9934314)

I'd like to keep IE on my server, but not if people keep crashing the server with drills.

**Comment by malte0811** [comment]
1. Only NeoForge is supported on 1.20.1 and above.
2. Please provide actual profiling data using [Spark](https://www.curseforge.com/minecraft/mc-mods/spark). The only thing your screenshot shows is that far too much time is spent on the player entity, but that could be just about anything.

**Comment by BokChewy** [comment]
Sorry for the late reply, here you go!

Spark profile
https://spark.lucko.me/XdnRxhIZqa

Observable profile
https://o.tas.sh/#9NOY8

**Comment by malte0811** [comment]
Neither of those two remotely matches the value in the screenshot, did you profile while actually using the drill? In the spark profile the player tick is at less than 1% of tick time, in the observable profile it is still "only" 5ms/tick (not nothing, but also not 38ms/tick). In both profiles total tick time is in the 20-30ms/tick region, which is perfectly fine.

Btw, no need to excuse the "late reply", it was a fast one by my standards. Timezones combined with IRL schedules mean that only getting one message across per day is perfectly normal, and a few days delay is also not unusual (especially around Christmas when people are not necessarily at home).

**Comment by BokChewy** [comment]
Hey so last night I wiped my mods and re-installed them one at a time to see if there was some sort of conflict going on and found out that there were some client side mods in the server's mod folder. Getting rid of those seems to have fixed everything. Sorry for wasting your time!

**Comment by BluSunrize** [comment]
I suppose we'll consider this one resolved then...
