### ISSUE TITLE
Garden Cloche doesn't support fertilizers from Thermal Series

### ISSUE THREAD

**Issue by HydrogenC** [BluSunrize/ImmersiveEngineering#5832]
### Minecraft Version

1.20.1

### Immersive Engineering Version

10.0.0-169

### Expected Behavior

Fertilizers from Thermal Series can be used in Garden Cloche. 

### Actual Behavior

Fertilizers from Thermal Series cannot be used in Garden Cloche. 

### Steps to reproduce

Try to insert fertilizers from Thermal Series into Garden Cloche. 

### Debug Crash Log

N/A

**Comment by BluSunrize** [comment]
You can fix that yourself by making a datapack that adds a recipe for Thermal's fertilizer. =)
See here for an example:
https://github.com/BluSunrize/ImmersiveEngineering/blob/1.19.2/src/generated/resources/data/immersiveengineering/recipes/fertilizer/fertilizer.json
