### ISSUE TITLE
Villagers names on trading tab JEI/REI/EMI are not translated

### ISSUE THREAD

**Issue by ffuentesm** [BluSunrize/ImmersiveEngineering#5837]
### Explain your idea

Would be nice to fix this long string name for their proper name. 
![image](https://github.com/BluSunrize/ImmersiveEngineering/assets/44974827/b3235c64-f3b4-4421-a2f9-278fa42f370c)

**Comment by BluSunrize** [comment]
This shouldn't have been a suggestion, it's clearly a bug report.

This feature is not part of JEI itself, it must be one of its addons. Can you please identify which one it is?
Also, which version of Minecraft did you produce this in?

**Comment by ffuentesm** [comment]
I am on 1.20.1
I am using EMI Trades, and this also appears on the JER trading tab.
![image](https://github.com/BluSunrize/ImmersiveEngineering/assets/44974827/c19548aa-772a-46c5-8f7b-f0cf5686ba7b)
![image](https://github.com/BluSunrize/ImmersiveEngineering/assets/44974827/7042eb56-93bf-4782-a1c2-9577139652e8)
