### ISSUE TITLE
Bottling Machine not accepting items, and missing recipes.

### ISSUE THREAD

**Issue by Filvandrel** [BluSunrize/ImmersiveEngineering#584]
Bottling machine does not accept items dropped on the conveyor belt. They just bump on the entry point continiously or fling themselves back to the entry point. Multiblock itself forms, accepts power and liquids, but does not fill anything. Also, it appers to have missing recipe handlers, cause NEI does show only Thermal Expansion filling recipes (at first I thought it does not show any, but Thermal Expansion ones appear). There are no recipes for bottled water, nor filled jerrycan etc.

![2015-11-03_23 36 19](https://cloud.githubusercontent.com/assets/14860878/10924025/5fef59f0-8284-11e5-8f35-601aef461dc3.png)
The item just sits in this spot, and jump up and down.

![2015-11-03_23 36 31](https://cloud.githubusercontent.com/assets/14860878/10924041/74c69d7a-8284-11e5-9985-d085ab3147e5.png)

Sorry for screenshots at night, I forgot to switch to day, and I don't have time atm to load minecraft again, cause it's really late up here, and I'm off to work.

**Comment by BluSunrize** [comment]
try it with a straight conveyor leading into it?

**Comment by Filvandrel** [comment]
Tried that too. Straight one from behind or sides. Neither works.

**Comment by Ayrrow** [comment]
this seems to be similar to the issue described in #565 with inventories not accepting items from conveyor belts.

**Comment by Filvandrel** [comment]
I somehow managed to get it working. After deleting config file and restarting minecraft client, straight conveyor leading to the machine started to work.

**Comment by BluSunrize** [comment]
as for NEI: 
the bottling machine can fill any fluid container, so it doesn't show recipes for that. Only 'explicit' recipes, like filling Thermal Expansion's Cell Frames are listed. The others aren't really recipes, but just a dynamic functionaility of the machine.

**Comment by ravenstormchaser** [comment]
This looks like the issue i was having with the conveyor belts not being oriented correctly to what the animation shows as per #582? . This kind of dropping off or bumping is exactly what was happening when i tried to get things to input with belts. Have you tried removing the belt and placing it back in a direct line into the machine without using the hammer on it to adjust it?
