### ISSUE TITLE
The drill does not dig 3x3x1 and 2x2x1

### ISSUE THREAD

**Issue by FOLLOO** [BluSunrize/ImmersiveEngineering#5840]
### Minecraft Version

1.20.1

### Immersive Engineering Version

1.20.1-10.0.0-169

### Expected Behavior

A drill with a 3x3x1 nozzle should dig 3x3x1

### Actual Behavior

The drill with a 3x3x1 nozzle does not dig properly. Digs 1x1. It's the same with 2x2x1

https://github.com/BluSunrize/ImmersiveEngineering/assets/60042643/c6145763-8c81-438f-a0b7-1f560ab2094c

### Steps to reproduce

I installed a drill. 
I filled it up.

### Debug Crash Log

https://pastebin.com/qdvyxCeE

**Comment by voidsong-dragonfly** [comment]
Your paste is either private or pending moderation, could you clarify if you're using Optifine for shaders? If you are, please remove it and test with just IE.

**Comment by FOLLOO** [comment]
> Your paste is either private or pending moderation, could you clarify if you're using Optifine for shaders? If you are, please remove it and test with just IE.

No Optifine is not used for shaders

**Comment by BluSunrize** [comment]
1) Can you reproduce this in an instance with just IE?
2) Please provide an actually visible crashlog, as voidsong requested.
