### ISSUE TITLE
unable to creat arc furnace

### ISSUE THREAD

**Issue by Tsumiki129** [BluSunrize/ImmersiveEngineering#5849]
### Minecraft Version

1.20.1

### Immersive Engineering Version

1.20.1-10.0.0-199.jar

### Expected Behavior

arc furnace multiblock should form wen hitting cauldron with hammer

### Actual Behavior

arc furnace multiblock not forming wen hit with hammer and double checked build is correct

### Steps to reproduce

1. built multiblock exactly how the book shows
2. hit with hammer on caldron as book says
3. nothing happens 
4. double check diagram in book and repeat stage 2
5. multiblock still doesn't form

### Debug Crash Log

https://mclo.gs/pdVwnR0

**Comment by Tsumiki129** [comment]
update to my post the arc furnace is also buged in forming on neo forge

**Comment by mindforger** [comment]
could you add one or more screenshots, jsut to be sure everything is right (just in case there might be some misunderstanding, no offense, just to be 100% sure)

**Comment by Tsumiki129** [comment]
of the crash log or the build in game

**Comment by mindforger** [comment]
The build in game

**Comment by Tsumiki129** [comment]
hear is each stage as i build it including the complete to make it easy to see if i have a mistake but it dosnt form at the end wen right clicking with hammer

![2024-01-18_17 45 41](https://github.com/BluSunrize/ImmersiveEngineering/assets/147937268/6884f47f-498b-420d-a08e-dfe444ef3ee7)
![2024-01-18_17 46 34](https://github.com/BluSunrize/ImmersiveEngineering/assets/147937268/5da538b2-c4bb-4118-add8-db90c9add8ea)
![2024-01-18_17 47 31](https://github.com/BluSunrize/ImmersiveEngineering/assets/147937268/a241dfc6-ed58-42b8-b9ac-a8cd3cf35e97)
![2024-01-18_17 48 02](https://github.com/BluSunrize/ImmersiveEngineering/assets/147937268/3884342b-ce16-4525-8ccc-c48efb8dc466)
![2024-01-18_17 48 41](https://github.com/BluSunrize/ImmersiveEngineering/assets/147937268/54e3acb9-141d-4f28-af14-13f86e9a17c4)
![2024-01-18_17 49 03](https://github.com/BluSunrize/ImmersiveEngineering/assets/147937268/66d66caf-18eb-4d7a-86f5-fe9346bacfce)

**Comment by Tsumiki129** [comment]
on second thought i just relised after posting i missed some blocks

**Comment by Tsumiki129** [comment]
we do have this part of a mod pack on forge and someone had said it didnt work clearly i made a mistake myself wen building it and compleatly miss saw my error but i will see if its still an isue for the main pack

**Comment by Tsumiki129** [comment]
eddit: after a little more trying i have relised it is a mistake i made and didnt quite see evrything within the book correctly and its not a bug im sorry for the mix up and mistake

**Comment by mindforger** [comment]
You could close this, and make a New suggestion issue linking to this if you finde the book Display confusing... Hence i asked for Screenshots
