### ISSUE TITLE
Wire attaching/cutting doesn't cause chunk updates and re-rendering.

### ISSUE THREAD

**Issue by Cypher121** [BluSunrize/ImmersiveEngineering#585]
Well, title. Newly attached wires don't render until I place a block, F3+A or cause any other chunk update.

Also how the hell that got into release version is beyond me. But whatever.

**Comment by mindforger** [comment]
it is still beta, don't rant on a sacrificially working mod dev! love it or leave it! he does not owe you anything

**Comment by cobra** [comment]
Ranting is a sure way to get your report ignored. I wired a lot of stuff during the last development phase and this never ever happened to me. So… optifine? fastcraft? What other mods?

**Comment by malte0811** [comment]
I have seen this, but only on a dedicated server. Maybe the update packets are not working correctly? You would probably not have noticed that in development. I was using fastcraft on both server and client.

**Comment by cobra** [comment]
I tested with both server and client, especially for some of the sync and world loading issues, but haven't wired that much. I'll test that later.

**Comment by cobra** [comment]
Confirmed.

**Comment by BluSunrize** [comment]
On the topic of how this got into a release: It's a beta mod and I have a life, shut up, ingrate.

To the problem at hand: Seems we have sync issues. No idea why though, I thought the block event stuff was solid...

**Comment by Cypher121** [comment]
I wasn't ranting, I was genuinely surprised that no one placed a single wire after changing render type. After seeing that it's only a dedicated server problem and how you react to it, I'm surprised no longer.

**Comment by BluSunrize** [comment]
You think I don't test my shit? Seriously? I've been spending the best part of the last 6 months on this! Do you have any idea how much work this project is? Not to mention how much literalyl any other mod can interfere? 10% of my git issues are filed under "Update your Forge","Update your Forestry" or "Stop using goddamn Optifine"

I /do/ test my work. Quite a lot too. I have never encountered the issue described above. And you good sir, seem to be lacking any respect for the time me and the entire team put into this.

**Comment by Cypher121** [comment]
Just test your stuff on dedicated server. Everything that works on dedicated works on integrated too.

**Comment by cobra** [comment]
That's rather unsurprising, it's the other direction in which things are breaking or behaving different than the integrated server. Still, thanks for testing. Did you notice any other bugs while doing this?

**Comment by Cypher121** [comment]
Well, there was some strange issue with something draining my capacitor banks of power at a constant rate, but I'll make a separate issue for it later with some screenshots.
