### ISSUE TITLE
[Suggestion] Add armor swapping to Glider

### ISSUE THREAD

**Issue by Zahkriiven** [BluSunrize/ImmersiveEngineering#5855]
### Explain your idea

Armor and elytras have the ability to swap the current armor piece by right clicking with it. Glider does not. Seems reasonable for it to do the same.

**Comment by BluSunrize** [comment]
On the contrary, I think it's **good** that this makes the Elytra "better".

The glider is never supposed to replace it, just to provide an early game alternative until people unlock End Cities

**Comment by musicbynumbers** [comment]
Just to add to this and plea for you to reconsider. I love climbing a mountain and then using your glider to fly down it (not interested in Elytra as it; breaks the immersion for me) but the glider is a good mix between walking and fast travel.

The only one annoyance is not being able to swap the glider and armor out quickly, this would be a great quality of life update for some :)

**Comment by BluSunrize** [comment]
I stand by what I said 2 years ago.
