### ISSUE TITLE
Circuit Table shortcut key shifted

### ISSUE THREAD

**Issue by Sam2451** [BluSunrize/ImmersiveEngineering#5856]
### Minecraft Version

1.19.2

### Immersive Engineering Version

9.2.3-167

### Expected Behavior

Pressing numbers should set the corresponding register of the same index, and pressing letters should set the color with the same initial (colors with the same initial are selected based on the order from white to brown, for example blue is before brown, pressing B the first time should set blue, if pressed again brown, subsequent inputs of the same key should repeat the sequence)

### Actual Behavior

The matrix or arrays or the for loop that bind the keys and the register/channel setting are offset by 1 forward from the key prospective.
Example 1: B(1)->Blue, B(2)->Brown (Expected); B(1)->Brown, B(2)->R0 (Actual)
Example 2: 0->R0, 1->R1, 2->R2 (Expected); 0->R1, 1->R2, 2->R3 (Actual)
Example 3: O->Orange, M->Magenta (Expected); O->Magenta, M->Light Blue (Actual)

### Steps to reproduce

Open an Engineer's Circuit Table in this version and try it yourself

### Debug Crash Log

.

**Comment by BluSunrize** [comment]
We're not maintaining 1.19 anymore, but this has been fixed in the latest 1.20.4 release =)
