### ISSUE TITLE
[1.16+][Suggestion] Exponential power decay for HV cables (and maybe other types too).

### ISSUE THREAD

**Issue by PeterKitsune** [BluSunrize/ImmersiveEngineering#5857]
### Explain your idea

Basically <https://github.com/BluSunrize/ImmersiveEngineering/issues/3426> but for 1.16+ (since 1.12 is, sadly, dead).

So currently (at least in 1.16 and according to the linked issue also in 1.12), power loss is linear - i.e. every chunk you loose a fixed percentage of the original power. Meaning however many millions of FE you throw down the wire, it will travel a certain number of chunks and then stop.

Realistically, you loose a percentage of the power *traveling through that chunk*. Meaning it has technically infinite range, although after sufficient distance (dependent on energy transfer rate) you have less than 1 FE, which depending on whether IE uses ``floor``, ``ceil``, or ``round`` in its calculations results in either 1 FE/t or 0 FE/t

### Mathematical analysis:
Lets say you configured the power loss to be 10% per chunk for ease of calculation (I know the default is 2.5% but 10 is easier to calculate with)
And lets say you are putting 1'000 FE/t through the wires.
I'll assume it uses ``floor`` again for simplicity, although the numbers aren't massively changed if it uses ``ceil`` or ``round``
- Using the current calculations, you loose 10% **of 1'000 FE/t** every chunk. So after one chunk, you have 900, after two chunks 800, after three chunks 700, etc., eventually reaching ten chunks = 0 FE/t.
- Using this alternative method, after one chunk you have 900 again, but after two chunks you loose 10% **of 900**, i.e. 810. After three chunks you have 729, after four chunks 656, five chunks 590, six chunks 531, etc., etc. As you can see, long distance power distribution is now actually plausible.

**Comment by PeterKitsune** [comment]
also how the heck do I add any labels to this thing?

**Comment by PeterKitsune** [comment]
its not completed because I specifically requested 1.16 and you only fixed it for 1.20+

Are you seriously telling me that 1.16 is not supported either?

(sorry for late reply I don't go on github that frequently)

**Comment by BluSunrize** [comment]
Yes, it hasn't been getting updates for nearly 3 years.
