### ISSUE TITLE
Heavy Plated Shield window is not see trough

### ISSUE THREAD

**Issue by BigGame2004** [BluSunrize/ImmersiveEngineering#5858]
### Minecraft Version

1.20.1

### Immersive Engineering Version

10.0.0-169

### Expected Behavior

The pixels representing the window should be transparent like stained glass.

### Actual Behavior

The transparency is ignored making the window opaque.

### Steps to reproduce

1. Boot up the latest version of either Forge or NeoForge for 1.20.1
2. Equip the Heavy Plated Shield and right click

### Debug Crash Log

https://pastebin.com/PWLat8sm

**Comment by zaeonNineZero** [comment]
Confirmed on 1.19.2, version 9.2.3-167. It also applies to transparent textures on other handheld items/weapons, including the Railgun and the Revolver when the Amplifier Tubes are added.
