### ISSUE TITLE
[Suggestion] minecraft:shields tag for heavy plated shield

### ISSUE THREAD

**Issue by idksomeone351** [BluSunrize/ImmersiveEngineering#5859]
### Explain your idea

It would be nice if heavy plated shield had minecraft:shields tag because it makes better mod compatibility(for example origins mod uses minecraft:shields tag to prevent some classes to use shields)

**Comment by BluSunrize** [comment]
There is no official `minecraft:shields` tag, Mojang does not implement it (or if they do, it's not documented on their wiki).

There is however `forge:tools/shields`, so I have added it to that =)
