### ISSUE TITLE
Odd Unicode font issue.

### ISSUE THREAD

**Issue by border999** [BluSunrize/ImmersiveEngineering#5860]
### Minecraft Version

1.20.1

### Immersive Engineering Version

ImmersiveEngineering-1.20.1-10.0.0-169

### Expected Behavior

Forge loading Immersive Engineering Unicode font properly.

### Actual Behavior

Fails to load.

### Steps to reproduce

Just have 'em both this in your modlist as far as I know.

### Debug Crash Log

https://gist.github.com/border999/22ac167a45a2596c8f8096ded64cf865

**Comment by SynfulChaot** [comment]
This appears to be due to the `legacy_unicode` font provider being deprecated in [Java Edition 23w17a](https://minecraft.wiki/w/Java_Edition_23w17a).
