### ISSUE TITLE
World doesn't render when shaders are enabled

### ISSUE THREAD

**Issue by Chicken1996** [BluSunrize/ImmersiveEngineering#5861]
### Minecraft Version

1.20.1

### Immersive Engineering Version

1.20.1-10.0.0-169

### Expected Behavior

<img width="1728" alt="Shader Render" src="https://github.com/BluSunrize/ImmersiveEngineering/assets/39061806/c7f6a8ff-9db4-4bac-b2fb-213e29165657">

### Actual Behavior

<img width="1728" alt="No render" src="https://github.com/BluSunrize/ImmersiveEngineering/assets/39061806/5afcd917-ebfd-45f9-aff4-67f58e72df0c">

### Steps to reproduce

-1. Have the Modpack "Better Minecraft" BMC4 installed.
0. Install Immersive Engineering.
1. Load a world: World loads as expected. No errors. 
2. Notice that blocks don't render: When shaders are enabled none of the blocks render. Turning off VBO doesn't help. Tested with ComplementaryReimagined r5.1.1, Sildurs Vibrant shaders V1.51 Medium, and BSL V8.2.07.1. They don't work either. 
3. Disable shaders: The world/all the blocks render fine now.

<img width="1728" alt="No Shader Render" src="https://github.com/BluSunrize/ImmersiveEngineering/assets/39061806/e81ca6f8-cdf2-4472-829e-1f6aa69ee9d2">

4. Re-enable shaders: They don't render again.

Since I'm playing with a modpack there is a lot of mods installed but this happens only when IE is enabled so I think it can be attributed to that. I also tested breaking blocks, F3+A, F3+T, and moving between chunks. They didn't seem to have an effect.

### Debug Crash Log

https://pastebin.com/5vJHsjgr

**Comment by BluSunrize** [comment]
Shader mods like Optifine are not supported =)

**Comment by Chicken1996** [comment]
> Shader mods like Optifine are not supported =)

Thanks for letting me know! I heard about optifine breaking everything but I didn't know it applied to Iris/Sodium as well.
