### ISSUE TITLE
Marked only as NeoForge on Curseforge for 1.20.1, but not forge (even though it does work)

### ISSUE THREAD

**Issue by Goldenlion5648** [BluSunrize/ImmersiveEngineering#5862]
### Minecraft Version

1.20.1

### Immersive Engineering Version

1.20.1-10.0.0-169

### Expected Behavior

I expected the mod to be marked as forge compatible, because it does already work with forge on 1.20.1. 

### Actual Behavior

The mod is not marked as "forge" on curseforge. This means the mod does not show up when searching for forge mods on curseforge.

### Steps to reproduce

1. Go here https://www.curseforge.com/minecraft/mc-mods/immersive-engineering/files/4782978

2. See that it only says neoforge

### Debug Crash Log

NA

**Comment by BluSunrize** [comment]
That's intentional.

We built on NeoForge, and so we can not guarantee full compat to old Forge.

**Comment by Goldenlion5648** [comment]
Oh I thought neoforge itself maintained compatibility with regular forge in 1.20.1, and only broke compatibility in the minecraft versions following?

Either way, thanks for the reply! I get it's extra work to built against multiple mod loaders, so no worries
