### ISSUE TITLE
Invisible water wheel

### ISSUE THREAD

**Issue by idksomeone351** [BluSunrize/ImmersiveEngineering#5865]
### Minecraft Version

1.20.1

### Immersive Engineering Version

10.0.0-169

### Expected Behavior

Water wheel on kynetic dynamo

### Actual Behavior

Water wheel is invisible

### Steps to reproduce

1.Play on custom modpack(mod list is in log file)
2.Place kynetic dynamo and water wheel on it
3.Water wheel is invisible(when rejoin world it becomes visible for a second but then becomes invisible again)

### Debug Crash Log

https://gist.github.com/idksomeone351/5f6659d63b00eab6a40f90abdf54f911

**Comment by idksomeone351** [comment]
If i install just immersive engineering everything works fine but when i play on my  modpack water wheel is invisible

**Comment by idksomeone351** [comment]
![Снимок экрана (46)](https://github.com/BluSunrize/ImmersiveEngineering/assets/158578802/80a49675-56fa-489d-8a91-1cf35e98b0c8)
Screenshot of this bug

**Comment by mindforger** [comment]
that is not a debug log, that is your normal logfile and not very usefull, please make e debug crash-log by pressing and holding F3 +C until the game crashes and upload that crash-log... i assume you have some rendering optimization mod installed like optifine, that is probabaly causing this

**Comment by BluSunrize** [comment]
Try removing Rubidium.

**Comment by idksomeone351** [comment]
heres crash report
https://gist.github.com/idksomeone351/af580f0638493c32b647cb9cd31358d0

**Comment by idksomeone351** [comment]
and i cant remove rubidium because without it my modpack works at 20-30fps(and with rubidium it works at 60-70 fps)

**Comment by idksomeone351** [comment]
and i tested installing just rubidium and immersive and water wheel is visible
![Снимок экрана (47)](https://github.com/BluSunrize/ImmersiveEngineering/assets/158578802/ff0e414c-1766-405c-8ed9-3fdb255dd547)

**Comment by idksomeone351** [comment]
ok something is wrong with my world because water wheel works perfectly in test world but not in my survival world

**Comment by idksomeone351** [comment]
yeah something is wrong with that world because sometimes it shows that errors in datapacks prevent it from loading(only happens with that world) but after closing and opening minecraft again it doesnt show this error

**Comment by idksomeone351** [comment]
![2024-02-10_18 15 53](https://github.com/BluSunrize/ImmersiveEngineering/assets/158578802/23676fea-f52b-4c29-a560-0b76d59bc927)
whater wheel is not invisible its just inside bio generator for some reason

**Comment by BluSunrize** [comment]
If this isn't reproducible with just IE, I'm gonna consider this not our error.
