### ISSUE TITLE
External Heater not heating

### ISSUE THREAD

**Issue by Latency2** [BluSunrize/ImmersiveEngineering#5866]
### Minecraft Version

1.19.3

### Immersive Engineering Version

1.19.3-9.3.0-163

### Expected Behavior

As I understand it should heat furnaces placed right next to the heater.

### Actual Behavior

 Nothing is happening. I have the furnaces loaded with stuff I want to smelt and outputs empty. The heater is connected to power and it has power inside stored. Even it I activate it with redstone, no response.
![2024-02-09_20 21 17](https://github.com/BluSunrize/ImmersiveEngineering/assets/34490561/4a469794-4227-4f24-ad18-c9ce83bbc7c2)

### Steps to reproduce

1. Place down any accumulator.
2. Place heater with furnaces around.
3. Connect heater to power lines.
4. Observe the issue

### Debug Crash Log

https://pastebin.com/mmxfT215

**Comment by TeamSpen210** [comment]
Is the connector attached on the right side? There's one side with a copper dot, the connector needs to go there. Also note that it does not work with the Blast Furnace or Smoker, only the regular Furnace. Might want to also check that it has power with a voltmeter.

**Comment by Latency2** [comment]
The copper dot is on the top side of my heater. I know it works only with regular furnace, I just didn´t know what else might be wrong, so I tried whatever came to my mind. I also checked the heater with multimeter, thats why Im saying that it has power stored inside in the original report.

**Comment by BluSunrize** [comment]
Can you please provide the full crashlog that has the full modlist in it?
Also, can you reproduce this issue with just IE installed?

**Comment by Latency2** [comment]
Yes, I just replicated the issue without any additional mod (just forge and IE). Also there it the crash log I just created https://pastebin.com/S9h50P0j

**Comment by Latency2** [comment]
I also created crash log while recreating this issue without any additional mods, thought it might come to use.
https://pastebin.com/LYVsf3vy

**Comment by voidsong-dragonfly** [comment]
You have (or had, and some part is sticking around) Optifine. Optifine breaks the External Heater, and it's their fault.
Blast Furnaces and Smokers also do not work with the External Heater, which is working as intended.

**Comment by Latency2** [comment]
You are right, optifine broke it. Didn´t realise I added it manually when I cloned my modpack, so I forgot to delete it. So deleting optifine fixed it for me. Thanks
