### ISSUE TITLE
Multiblocks 1.19.2 Forge

### ISSUE THREAD

**Issue by Krimatoria** [BluSunrize/ImmersiveEngineering#5868]
engineeredcompatibility-1.1.1.jar
Engineers Delight 1.19.2 B.1.2.jar
ImmersiveEngineering-1.19.2-9.2.3-167.jar
[Log 9.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/14323793/Log.9.txt)

> [ImmersiveEngineering-1.19.2-9.2.3-167.jar%23584!/:?]
> 	at blusunrize.immersiveengineering.common.IEContent.lambda$populateAPI$5(IEContent.java:289) ~[ImmersiveEngineering-1.19.2-9.2.3-167.jar%23584!/:?]
> 	at blusunrize.immersiveengineering.api.multiblocks.TemplateMultiblock.getTemplate(TemplateMultiblock.java:115) ~[ImmersiveEngineering-1.19.2-9.2.3-167.jar%23584!/:?]
> 	at blusunrize.immersiveengineering.api.multiblocks.TemplateMultiblock.getTemplate(TemplateMultiblock.java:102) ~[ImmersiveEngineering-1.19.2-9.2.3-167.jar%23584!/:?]
> 	at blusunrize.immersiveengineering.common.blocks.multiblocks.IETemplateMultiblock.getTemplate(IETemplateMultiblock.java:97) ~[ImmersiveEngineering-1.19.2-9.2.3-167.jar%23584!/:?]
> 	at blusunrize.immersiveengineering.api.multiblocks.TemplateMultiblock.getStructure(TemplateMultiblock.java:224) ~[ImmersiveEngineering-1.19.2-9.2.3-167.jar%23584!/:?]
> 	at blusunrize.immersiveengineering.client.utils.BasicClientProperties.getTotalMaterials(BasicClientProperties.java:64) ~[ImmersiveEngineering-1.19.2-9.2.3-167.jar%23584!/:?]
> 	at sguest.jeimultiblocks.jei.MultiblockRecipeCategory.setRecipe(MultiblockRecipeCategory.java:82) ~[jeimultiblocks-1.19.2-0.0.3.jar%23593!/:1.19.2-0.0.3]
> 	at sguest.jeimultiblocks.jei.MultiblockRecipeCategory.setRecipe(MultiblockRecipeCategory.java:29) ~[jeimultiblocks-1.19.2-0.0.3.jar%23593!/:1.19.2-0.0.3]
> 	at mezz.jei.library.util.IngredientSupplierHelper.getIngredientSupplier(IngredientSupplierHelper.java:22) ~[jei-1.19.2-forge-11.6.0.1019.jar%23592!/:11.6.0.1019]
> 	at mezz.jei.library.recipes.RecipeManagerInternal.lambda$addRecipes$0(RecipeManagerInternal.java:115) ~[jei-1.19.2-forge-11.6.0.1019.jar%23592!/:11.6.0.1019]
> 	at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
> 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?]
> 	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
> 	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
> 	at java.util.stream.AbstractPipeline.evaluateToArrayNode(Unknown Source) ~[?:?]
> 	at java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:?]
> 	at java.util.stream.ReferencePipeline.toArray(Unknown Source) ~[?:?]
> 	at java.util.stream.ReferencePipeline.toList(Unknown Source) ~[?:?]
> 	at mezz.jei.library.recipes.RecipeManagerInternal.addRecipes(RecipeManagerInternal.java:121) ~[jei-1.19.2-forge-11.6.0.1019.jar%23592!/:11.6.0.1019]
> 	at mezz.jei.library.recipes.RecipeManagerInternal.addRecipes(RecipeManagerInternal.java:103) ~[jei-1.19.2-forge-11.6.0.1019.jar%23592!/:11.6.0.1019]
> 	at mezz.jei.library.load.registration.RecipeRegistration.addRecipes(RecipeRegistration.java:64) ~[jei-1.19.2-forge-11.6.0.1019.jar%23592!/:11.6.0.1019]
> 	at sguest.jeimultiblocks.jei.JeiModPlugin.registerRecipes(JeiModPlugin.java:50) ~[jeimultiblocks-1.19.2-0.0.3.jar%23593!/:1.19.2-0.0.3]
> 	at mezz.jei.library.load.PluginLoader.lambda$createRecipeManager$10(PluginLoader.java:140) ~[jei-1.19.2-forge-11.6.0.1019.jar%23592!/:11.6.0.1019]
> 	at mezz.jei.library.load.PluginCaller.redirect$clk000$callOnPlugins(PluginCaller.java:541) ~[jei-1.19.2-forge-11.6.0.1019.jar%23592!/:11.6.0.1019]
> 	at mezz.jei.library.load.PluginCaller.callOnPlugins(PluginCaller.java:25) ~[jei-1.19.2-forge-11.6.0.1019.jar%23592!/:11.6.0.1019]
> 	at mezz.jei.library.load.PluginLoader.createRecipeManager(PluginLoader.java:140) ~[jei-1.19.2-forge-11.6.0.1019.jar%23592!/:11.6.0.1019]
> 	at mezz.jei.library.startup.JeiStarter.start(JeiStarter.java:114) ~[jei-1.19.2-forge-11.6.0.1019.jar%23592!/:11.6.0.1019]
> 	at mezz.jei.forge.startup.StartEventObserver.transitionState(StartEventObserver.java:137) ~[jei-1.19.2-forge-11.6.0.1019.jar%23592!/:11.6.0.1019]
> 	at mezz.jei.forge.startup.StartEventObserver.onEvent(StartEventObserver.java:100) ~[jei-1.19.2-forge-11.6.0.1019.jar%23592!/:11.6.0.1019]
> 	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.3.jar%2385!/:?]
> 	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.3.jar%2385!/:?]
> 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2385!/:?]
> 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2385!/:?]
> 	at net.minecraft.client.multiplayer.ClientPacketListener.m_5859_(ClientPacketListener.java:1321) ~[client-1.19.2-20220805.130853-srg.jar%23731!/:?]
> 	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:35) ~[client-1.19.2-20220805.130853-srg.jar%23731!/:?]
> 	at net.minecraft.network.protocol.game.ClientboundUpdateTagsPacket.m_5797_(ClientboundUpdateTagsPacket.java:11) ~[client-1.19.2-20220805.130853-srg.jar%23731!/:?]
> 	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.19.2-20220805.130853-srg.jar%23731!/:?]
> 	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23731!/:?]
> 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.2-20220805.130853-srg.jar%23731!/:?]
> 	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19.2-20220805.130853-srg.jar%23731!/:?]
> 	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.19.2-20220805.130853-srg.jar%23731!/:?]
> 	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1072) ~[client-1.19.2-20220805.130853-srg.jar%23731!/:?]
> 	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23731!/:?]
> 	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23731!/:?]
> 	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23731!/:?]
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
> 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
> 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
> 	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.5.jar%23101!/:?]
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?]
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?]
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?]
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?]
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?]
> 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?]
> 	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?]
> 	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
>

**Comment by BluSunrize** [comment]
Seems to be an issue with jeimultiblocks, not much we can do there.
