### ISSUE TITLE
Wires and ropes are not visually displayed when Rubidium is enabled.

### ISSUE THREAD

**Issue by 4u4aaa** [BluSunrize/ImmersiveEngineering#5872]
### Minecraft Version

1.20.1

### Immersive Engineering Version

1.20.1-10.0.0-169

### Expected Behavior

So the problem is that the wires themselves from Immersive notify that they are being attached, but you can't see it visually. However, the same problem with ropes.
If you disable Rubidium in optional modifications, the problem disappears. All wires become visible.

### Actual Behavior

.

### Steps to reproduce

.

### Debug Crash Log

.

**Comment by BluSunrize** [comment]
Yeah Rubidium isn't really supported.
