### ISSUE TITLE
Dup any stuff using bags and arc furnace.

### ISSUE THREAD

**Issue by 4u4aaa** [BluSunrize/ImmersiveEngineering#5873]
### Minecraft Version

1.20.1

### Immersive Engineering Version

1.20.1-10.0.0-169

### Expected Behavior

.

### Actual Behavior

The arc furnace is a huge 5x4x4 ( guess) multi-block, consists of 8 different blocks.
The player threw with the help of a perfect logistic transporter from the chest threw bags into the arc furnace (the faster you put in the chest, the more bags stacked), and already in the interface of the arc furnace (multiblock of immersive) they were stacked. In the stacked bag put the items that needed to be duped, then spread the bag on the slots (the bag itself is non-stacking), and in each bag stored items.

### Steps to reproduce

.

### Debug Crash Log

.

**Comment by BluSunrize** [comment]
I...I have not the slightest idea what you are saying, I'm sorry.

Can you try to phrase that again in multiple, puncuated sentences?
Maybe provide some pictures or video?

**Comment by 4u4aaa** [comment]
https://www.youtube.com/watch?v=Ok14zinIyv8

**Comment by voidsong-dragonfly** [comment]
This seems like a problem with the transporters or the bag mod, not with IE. Arc furnace input slots extend `SlotItemHandlerIE`, which has [this](https://github.com/BluSunrize/ImmersiveEngineering/blob/4713f3e07697bf5df026d43ac6f6e09051007650/src/main/java/blusunrize/immersiveengineering/common/gui/IESlot.java#L750) line for `getMaxStackSize(@NotNull ItemStack stack)`
```java
return Math.min(Math.min(this.getMaxStackSize(), stack.getMaxStackSize()), super.getMaxStackSize(stack));
```
So it seems to me like either Mekanism transporters are inserting more than they should be able to or the bags are not regulating their stacking properly?

**Comment by BluSunrize** [comment]
Yeah I'm going with void's assessment here. I don't think there is much we can do.
