### ISSUE TITLE
[Suggestion] 1.20.1 Forge version (I know its been asked once but please read anyway)

### ISSUE THREAD

**Issue by Joshernoob** [BluSunrize/ImmersiveEngineering#5874]
### Explain your idea

I get this been said before as i checked but, it needs to be said again, we need a 1.20.1 Forge version along with the neoforge vesion, if not just a tag fix.

Neoforge as of typing this is way to new for pack dev to even consider using let alone most of the other large mods move over to it until the devs of the mods know what will happen. 
because of this neoforge is basicly bair-bone making it even harder for pack devs to have a reason to use it as of now.

My point is there nothing wrong with being the first to make the move but thats making it hard on the pack devs that want to use this mod, and blaming that on curse forge won't work as neoforge it like any other diffrent loader you can not miss and match the mods even if the 1.20.1 version are compatable. Meaning its on the Mod creators back if there a problem. 

This mean someone can't just grab the mod and move it over to a new forge profile and expect the pack to pass upload. that be fixed with a forge version or a line of code.

Not trying to seem rude with this just hoping to get the mod in forge even if its not perfect as I'm one of the modpack creators getting effected not being able to use this mod.

**Comment by BluSunrize** [comment]
No.
Move your pack to NeoForge.

**Comment by Joshernoob** [comment]
This is not possable I explained why in detail
you are losing thousands of pack devs do to this aregents. them having to remove this mod. 

In the end this does not effect us pack devs only you the mod that relys on us for stable downloads.

anyways thanks for reading and good luck in neoforge with no other mod there!

**Comment by BluSunrize** [comment]
Literally every major mod is moving to NeoForge with 1.20.4.
You're betting on the wrong horse here.
