### ISSUE TITLE
Faraday Suit and Steel  Suit have no name

### ISSUE THREAD

**Issue by Lantern377** [BluSunrize/ImmersiveEngineering#5876]
### Minecraft Version

1.20.1

### Immersive Engineering Version

1.20.1-10.0.0-169

### Expected Behavior

Every item of faraday suit and steel suit has its name like "Faraday Helmet" and "Steel Chestplate".

### Actual Behavior

Faraday suit and steel suit have no name like "Faraday Helmet", but "item.immersiveengineering.armor_faraday_head" and "item.immersiveengineering.armor_steel_chest". 
![2024-02-22_16 55 09](https://github.com/BluSunrize/ImmersiveEngineering/assets/82046179/a875a002-c2c0-4fa3-8525-cfd48a351398)
![2024-02-22_16 55 13](https://github.com/BluSunrize/ImmersiveEngineering/assets/82046179/81ead66e-0292-4075-8c5e-8803ce7041cf)

### Steps to reproduce

1. First I created a new world with creative mode.
2. Then I picked up a Faraday Helmet and a Steel Chestplate from creative inventory.
3. And they have no name.

### Debug Crash Log

https://gist.github.com/Lantern377/b881f7db0f8ef5233bdb60bad4a0c58c

**Comment by BluSunrize** [comment]
Was already fixed in 8012c8ecf24b1bcf5529b35b02b44e28b63ad336
Will be resolved by the next release.
