### ISSUE TITLE
[Suggestion] High tier item sorter

### ISSUE THREAD

**Issue by beringtom** [BluSunrize/ImmersiveEngineering#588]
I would like to suggest a machine that can sort items based on a filter, I know you got the sorting block but thats just a 1x1x1, My suggestion is a multiblock machine that can utilize the conveyors even better and might fit the style of IE.

Now the main idear would be that the "item" goes in the input slot, get's scanned and then goes on the conveyor, when it reaches the side I needs to be output on it will get pushed of the machine onto the ground or conveyor. It could get pushed by a mechanical arm or a simple jet of air (particales?)

Now, the machine should require power, and would be a 3x3x2 multiblock. Suggestion for a recipe could be something like this: http://imgur.com/a/G0QGe
(direction of the belts could be changed like the botteling machine)

now since this machine can only output 3 ways + 1 input, it should offer more slots for items, or some kind of "incoder" to mark the blocks that should be sorted out.
Should a "item" enter without being set in the filter, i should not be accepted into the machine, the filter needs to remain empty to allow items to go that way as a default exit.

**Comment by BluSunrize** [comment]
That is...100% what the current item router does.
It sorts based on a filter, has OreDict sorting and probably gets meta+NBT filtering in the future
Your suggestion carries no advantage while being a unnecessary multiblock.

**Comment by beringtom** [comment]
Well, can't hurt to ask, you can close this :)
