### ISSUE TITLE
cant add players to blacklist in turrets

### ISSUE THREAD

**Issue by Monstris1Krystian** [BluSunrize/ImmersiveEngineering#5882]
### Minecraft Version

1.20.1

### Immersive Engineering Version

ImmersiveEngineering-1.20.1-10.0.0-169

### Expected Behavior

let turrets work properly

### Actual Behavior

on my friend server we wanted to make turrets but let them dont shoot each other. when we tried to add us to blacklist we cant.
any idea what we can do?

### Steps to reproduce

1. place turret
2. try to add any player
3. you realise you cant

### Debug Crash Log

f

**Comment by BluSunrize** [comment]
Has already been fixed: https://github.com/BluSunrize/ImmersiveEngineering/commit/1e2d066bcc935fa67f62c04fb270218037e3a5e7

Next release will resolve this.
