### ISSUE TITLE
Game crashed from explosion and will not re-open

### ISSUE THREAD

**Issue by Sasktor** [BluSunrize/ImmersiveEngineering#5889]
### Minecraft Version

1.19.2

### Immersive Engineering Version

1.19.2-9.2.3-167

### How did it happen?

What is the bug? The game crashed after damaging my power supplies, and my world will no longer open without instantly crashing.

What did you do to make it happen? A creeper explosion hit my HV connections, wires, and generators.

Does it happen every time you do this? Does it happen if you do something else as well?

Did this happen on a dedicated server (multiplayer servers), in LAN multiplayer or in singleplayer? I was playing alone on my local essential server.

### Crash Log

https://pastebin.com/AHzD08dq

**Comment by BluSunrize** [comment]
Was fixed in 5fe6c995a8dc2b605441a120fee822a669bba284

Will be resolved by upcoming release
