### ISSUE TITLE
Some power connections not working on chunk load/unload

### ISSUE THREAD

**Issue by 1skandar** [BluSunrize/ImmersiveEngineering#589]
I'm not sure what is going on, but I have a MV connection between two MV capacitors that simply stops working if the chunk unloads/reloads. I have to break the connection and replace the wire for it to start working again.

**Comment by 1skandar** [comment]
Ok, on closer inspection it looks like power connections made across chunk boundaries just don't work all the times. If I have a MV connector just on one side of a chunk boundary and the other MV connector on the other side even though the wire makes it look like it is connected it actually isn't.

This looks like the old bug that caused the wires to flat disappear, except now it is fixed enough that the wires stick around, just the connection still breaks.

**Comment by theunkn0wn1** [comment]
Unable to reproduce, Haven't experienced this during any of my testing. My setup consists of two MV capacitors that are 3 meters from a chunk boundry, the output of the full one discharging into the input of the other. I left the area as to unload the chunks (also reloaded world)  and all the power, provided some lost due to cable resistance, was present in the target capacitor. Setup below

![image](https://cloud.githubusercontent.com/assets/3110986/10960632/15b599ce-833a-11e5-9dca-a50d7bbeb2a5.png)

 I presume you are using the 0.6 release? Can we get the list of mods you are using? Can we get a few pictures of your bug-inducing setup?

**Comment by 1skandar** [comment]
http://forum.feed-the-beast.com/threads/1-7-10-modular-mayhem.120584/ for the list of mods. As far as pictures:
![2015-11-05_00 41 29](https://cloud.githubusercontent.com/assets/4127779/10960841/0b5a77d0-8356-11e5-84a9-c3dba1f97467.png)
![2015-11-05_00 41 58](https://cloud.githubusercontent.com/assets/4127779/10960842/0b632a88-8356-11e5-9572-c8eaec459622.png)

In the first picture you can clearly see the floodlight on the left is working and the flood light on the right is not. Note the connector is right up against the chunk boundary.

In the second picture note that I rewired to get around the bug. Power was not transferring from the capacitor to the pole and, again, note the connector is right on top of the chunk boundary. 

and yes, this is the 0.6.0 release.

**Comment by theunkn0wn1** [comment]
Managed to reproduce with build 7e64713 (release) and build a7485ca (latest).

===============
Setup is as follows:
![image](https://cloud.githubusercontent.com/assets/3110986/10961394/14edae4c-8343-11e5-8fcd-82970a48e76f.png)
post is on a chink boundry, floodlights are pointed down 11 meters offset by 8 meters higher than the base of the post. power is reaching both of these consumers, yet they are not updating within a timely fashion.

==============
Workaround: Wack the malfunctioning Floodlight with the hammer, causes it to update (and tilt out of orientation)
----------------
Due to how expensive lighting recalc is Blu made them update infrequently, a chunk reload is not neccesary to reproduce this issue.

Also, you can save power by using one floodlight on one of the sides pointing into the room, more efficient use of resources. You can also point the Floodlight at non-polar angles and the projected light blocks will follow.

**Comment by 1skandar** [comment]
Actually it isn't just the floodlight. In my second screen shot power was not being transmitted to the connector on the pole from the connector on the capacitor on the right edge (you can't see the capacitor, just the connector). I had to wire around it with another mod's wires which is why there is another capacitor in the ground by the pole.

**Comment by theunkn0wn1** [comment]
You sure you have enough RF to power the lot? power IO is limited per connection, and the machines you have hooked up, based from what I can see, can chew through most of what one RF input can carry. Have you tried placing a second input on the circuit?

Also, upon reviewing the images, you sure the capacitor built into the wall is set to output on both sides? I cannot quite tell from the angles provided.

My above test case was based on the OP and what I could derive from the images initially

**Comment by 1skandar** [comment]
In both cases the setup was working just fine until I exited out. When I came back in power stopped being transmitted. The only fix was to break and replace the wire involved which fixed the issue just fine...until I exited the game again. I imagine loading/unloading the chunks would cause the same problem, I just have a chunk loader so that never happens.

The second shot was where I discovered the problem initially. After reporting the problem I got tired of having to continually break and replace that section of wiring and kludged around it. That is, btw, all MV so power transfer and capacity really isn't an issue. 

Up until now I though that was the end of it, the rest of my wiring was behaving. Today I wired up some floodlights and crashed out of the game. When I came back I realized half of my floodlights weren't working. Again, breaking and replacing the wire involved solves the problem. This time, with the floodlights on the ceiling 9 ish blocks up, I'm not exactly sure how to wire a way around this issue,

From what I can tell this appears to be exactly the same problem with connections pre-0.6.0 where connections would randomly break. The only thing that has changed is that while the connection still breaks the wire doesn't vanish. Which is an improvement, sort of, outside of the fact I now have no clue that a connection is broken until I notiice a machine stops working. Oh, and it should be noted that I had wires break in the pre 0.6 version....just not these wires. 

Oh, and it should be noted that when I said that the entire area is chunk loaded that means both sides of the problem wire. The failure is not across one chunk that is loaded versus another that is not.

**Comment by 1skandar** [comment]
Oh, and if you want to see this in action, um, the pack I am using is public. When I update the pack tomorrow the world will be compatible with the public version. I can upload the world and you can poke it yourself. It is a very frustrating issue because the failure points were both very, very critical points in my power map.

**Comment by theunkn0wn1** [comment]
Yeah, having the world would be of use to me, remote debugging is quite ineffective and images only go so far. I'll grab the pack tomorrow and see if I can figure out exactly where the problem lies.

**Comment by 1skandar** [comment]
Actually if you are comfortable manually updating, the current pack with a manually updated IE and Immersive Integration to 0.6.0 should be compatible enough with my world. Give me a second and I'll report back.

**Comment by theunkn0wn1** [comment]
I have no problem with manually updating mods, though I have run out of time today (technically yesterday) to bug hunt. I'm sure if I don't get to it other regulars of this repository will get to this within a timely manner.

**Comment by 1skandar** [comment]
Right enough. Well, I'll leave this here. If I don't get 1.9 out in time, the 1.8.1 version of Modular Mayhem on the Curse launcher updated with the 0.6 versions of IE and Immersive Integration is compatible (you'll also have to add Translocators, or, well, not. I don't think it is critical in this case).

The save is here: https://dl.dropboxusercontent.com/u/46780505/Let%27s%20Play.zip

I've added to capacitors to illustrate the problem:
![2015-11-05_03 08 47](https://cloud.githubusercontent.com/assets/4127779/10963029/14ae3816-836b-11e5-9b0a-80fec690c95c.png)
![2015-11-05_03 08 55](https://cloud.githubusercontent.com/assets/4127779/10963030/14af156a-836b-11e5-9161-9ed3c20bca4e.png)

You'll notice they won't be charging on world load, but if you break and replace the connectors they wiull charge just fine. Exiting the world will stop them from charging again.

**Comment by theunkn0wn1** [comment]
Alright, retrieved the modpack and the world in question.

 I can confirm, even after updating IE to the latest builds, that your described error is occurring though I am unable to reproduce it outside your provided world. I reproduced the position (orientation and chunk positioning)and angle of the Floodlights on a separate test world and the described bug did not manifest itself. 

Any update to the power network, any addition or deletion of any IE element from any IE cable circuit seems to 'fix' the floodlights. 

=========================

Temporary workaround: Place a breaker switch on the wall, wire it into the network if you wish. Whenever this bug occurs, toggle it on and off again.
-------------------------

**Comment by 1skandar** [comment]
I'm wondering if it is an Immersive Integration bug? I can't necessarily test that in my current world without breaking stuff. Ugh. Well, I can back things up and see.

**Comment by theunkn0wn1** [comment]
I removed II, I tested without that mod. That was one of my first thoughts.

**Comment by 1skandar** [comment]
Dammit. Found the interaction. If it wasn't II there was one other mod that could be messing with things, my chunk loader from Chicken Chunks. Guess what I found when I removed the chunk loader? Yeah, problem went bye bye.

Um, not sure how to proceed here. This probably means the problem isn't on your end, because Chicken Chunks has a long unfortunate history of causing problems like this. And i kinda need that chunk loader. Oh well, we now know the cause of the problem at least, if not the solution.

**Comment by theunkn0wn1** [comment]
well that explains perfectly why I could not reproduce this bug, I wasn't looking for force-loaded chunks nonetheless ChickenChunks. ;{  Guess you will need to find a different chunk loader mod now. Might want to go report this to Chicken Bones, as it appears to be his mod.

*facepalm* When I went to add a chunkloader from CC into my test world to confirm your findings , found a seperate CC induced IE NPE crash... lol

**Root cause: Bad interaction between ChickenChunks and Immersive Engineering.**

Might I suggest adding Railcraft to the mix? it includes reasonable chunkloader abilities

**Comment by 1skandar** [comment]
Dimensional Anchor works and does not cause this problem, so I found my own solution. Well, thanks for sticking with me on this end. Yeah, I'll see about reporting this on his end.

**Comment by theunkn0wn1** [comment]
No problem, was fun and found a pack I might enjoy in the process :3

 might want to mark this thread as closed, saves Blu the hassle later when he goes through this and arrives at the same conclusion as us.

**Comment by mindforger** [comment]
chicken chunks, huh? ... they sure cause strange problems, especially on world start and dimension first loading (they soemtimes do not load dimensions properly on server start -.-) ... i kinda licke chickenbones stuff especially NEI is a must have but this and the wireless redstone (NEVER play with the wireless redstone jammer, they can make your world unplayable unless you know how to modify the NBT savegames to remove that deadloop, even removing the mod does not help) always are the first things i throw out of my modlist
