### ISSUE TITLE
Please tag Immersive Engineering for Forge as well as Neoforge in Curseforge.

### ISSUE THREAD

**Issue by ArkenorOakshadow** [BluSunrize/ImmersiveEngineering#5892]
### Explain your idea

Assuming that it is true that Neoforge and Forge are still compatible, please tag the mod for Forge as well, so we can find and install it.

**Comment by BluSunrize** [comment]
No. We are NeoForge only from here on.
Just go to Neo, your Forge mods should work fine on it.
