### ISSUE TITLE
Suddently connecting a lot of lamps creates masive power surge

### ISSUE THREAD

**Issue by Daniel-AmaFa** [BluSunrize/ImmersiveEngineering#5894]
### Minecraft Version

1.19.2

### Immersive Engineering Version

ImmersiveEngineering-1.19.2-9.2.3-167

### Expected Behavior

I have a lighting grid of 35 powered lanterns, it spans about 20 chunks arround my house and my village.
It's connected throug HV->MV->LV transformers to a HV line that can supply the full 32krf/t.
However the lighting only consumes 75rf/t and it's completely made  out of insulated wires, so there's no way it could consume more than the max 2krf/t for LV wires and burn.

### Actual Behavior

 However I found out after I had a problem and all power was temporary lost, that when the lanterns reconect from 0 the LV wires connecting to the transformer will burn.
 
Connecting the lamps to a capacitor or something that can give less than the 2krf/t _and then_ connecting them to the transformer will work just fine.

Sometimes the issue not only happes when disconnecting then recconecting the lanterns, but also wen going far away and returning, when returning from other dimensions or when the world is just started.

At some point I added a current transformer and a redstone breaker before the HV, and the whole connection from the furthest lantern to the HV line back to the power plant blew up. the line had about 2krf/t so the power surge that burned the line was of about 30krf/t just from the power lanterns in the LV line.

### Steps to reproduce

This is how the lanterns are connected:
![tdhcnxbffbfxnfxm](https://github.com/BluSunrize/ImmersiveEngineering/assets/57429817/3ecd0970-18a9-4d05-90b9-bc0ed4d1e7e5)
![xdndxnazdmzzbn](https://github.com/BluSunrize/ImmersiveEngineering/assets/57429817/f346d2a2-50e8-4757-9763-3eb90a0aeb95)
![yjgygjykyglgyl](https://github.com/BluSunrize/ImmersiveEngineering/assets/57429817/182ae03c-6321-46c4-8470-2f93da843c1c)

Now it seems that changes in how the HV-MV and the MV-LV transformers are connected sometimes fixed the issue (?) when I added current transformer and other things between the HV and the MV transformers to see how much energy the lamps used and tried to replicate the issue nothing happened, however I was able to replicate the issue tens of times at different times and even with different setups, sometimes the same setup would seem to solve the issue and then a second after it returned to burn the LV wires.

At some point after adding a breaker and a current transformer before the HV transformer, the LV line, the MV line and the HV line all blew up
this is the part that blew up:
![fcnmfc,cf,cf](https://github.com/BluSunrize/ImmersiveEngineering/assets/57429817/51db0d80-4826-4c68-bdd9-325da7af13c2)

the simulation distance is set to 7 wich is less that the distance bewteen where I was (just below the HV transformers) and the last lantern up to wich the wires burned. so it could be because part of the lantern grid was outside the generation distance. although the whole area is within the spawn chunks.

The world is running on a forge server in a different computer, is not multiplayer, it's just so both the world and my game run smoother.

the worldspawn is located strategically so that the whole base is within spawnchunks, the command /forceload was used on the worldspawn to keep the spawnchunks loaded.
the simulation distance is set to 7 chunks.

### Debug Crash Log

I don't how to get this, the world is on a dedicated forge server in another computer, but here are the system details from a previous crash: https://pastebin.com/qTvwcTPi

**Comment by voidsong-dragonfly** [comment]
This seems like semi-intentional behavior. Transformers do not limit total current flowing through them, so your circuit can theoretically pull 32kIF/t through it. On startup, every lamp likely tries to fill its entire buffer at once, generating "inrush current" of `(# of lamps)*256IF/t)` - of which the total draw will be >2048IF/t. Thus, the HV wires provide the current needed to burn the LV wires. This inrush current phenomenon is a little exaggerated in IE, but it's also somewhat intentional behavior - it's been tacitly accepted, even if it may not be directly in the system design docs.

To fix this, I would suggest somehow limiting throughput to the LV section, of which (sadly) the best way is a connector on an accumulator to max out at N IF/t and not 'the max I can insert'.
