### ISSUE TITLE
Loading error

### ISSUE THREAD

**Issue by Marksman-hub** [BluSunrize/ImmersiveEngineering#5896]
### Minecraft Version

1.20.1

### Immersive Engineering Version

none

### How did it happen?

I did not add Immersive Engineering to my pack on CF but I am getting the "tmted requires Immersive Engineering" error.
Here is the log
[2024-03-20-5.log.gz](https://github.com/BluSunrize/ImmersiveEngineering/files/14673228/2024-03-20-5.log.gz)

### Crash Log

https://pastebin.com/2KDEvssY

**Comment by mindforger** [comment]
Your crashlog is not public

**Comment by Marksman-hub** [comment]
Hi thank you for reaching back out, unfortunately the pack I was attempting to make for myself corrupted so I started over again. I have not had the error again. It may have been Immersive Delight causing the error if I were to guess.
