### ISSUE TITLE
Crate weirdness

### ISSUE THREAD

**Issue by BarbasTheDog** [BluSunrize/ImmersiveEngineering#59]
When right-clicking to open a crate with a block in hand, the client thinks, just for a second, that you actually placed the block instead.

As another consequence, you can't open a crate with a placeable block on hand unless you're at least one block away from it.

**Comment by BluSunrize** [comment]
yep, I noticed that one myself and fixed it yesterday :D

**Comment by BarbasTheDog** [comment]
ah, neat! ^ ^
