### ISSUE TITLE
Internal Server Error / Revolver Engineers Workbench

### ISSUE THREAD

**Issue by aikpoppel** [BluSunrize/ImmersiveEngineering#590]
Hey Blu,

if i try to put the revolver in the workbench i lost the connection to the server (Internal Server Error). In SSP it works perfectly.

Serverlog: http://pastebin.com/nSRUKdrU

Edit: I use Version 0.6.0 and Forge 10.13.4.1448
LG Aik

**Comment by cobra** [comment]
I see the problem: trying to access an icon which is only present on the client.

**Comment by BluSunrize** [comment]
Oh yeah, that /is/ an issue... .~.

**Comment by BluSunrize** [comment]
that should do the trick.

**Comment by angelnc1989** [comment]
This by the way also dupes the Revolver.

**Comment by BluSunrize** [comment]
It's fixed, so that's irrelevant.
