### ISSUE TITLE
flying without a glider

### ISSUE THREAD

**Issue by YuriS1l** [BluSunrize/ImmersiveEngineering#5900]
### Minecraft Version

1.20.1

### Immersive Engineering Version

10.0.0-169

### Expected Behavior

when removing the Collapsible Glider, the flight must stop.

### Actual Behavior

after the start of planning, if you remove the Collapsible Glider, then planning continues until the moment of landing.

### Steps to reproduce

1.Start planning with a Collapsible Glider
2.Remove the glider

<details>
<summary><h2> video:</h2></summary>

https://www.youtube.com/watch?v=xRbMGzCHBq0

</details>

### Debug Crash Log

NO

**Comment by BluSunrize** [comment]
I can't reproduce this in my instance. Flying ends the moment the glider is unequipped.

Please try to reproduce this in a NeoForge instance with just IE installed, otherwise we have to assume a cross-mod issue here.

**Comment by BluSunrize** [comment]
Closing this due to lack of feedback
