### ISSUE TITLE
[Suggestion] Kerosene lighter and hand warmer

### ISSUE THREAD

**Issue by kwaitsing** [BluSunrize/ImmersiveEngineering#5901]
### Explain your idea

Kerosene lighter and kerosene hand warmer is
-  Retro (well....they both burn kerosene and other volatile liquid fuels)
-  Useful (lighter:a replacement for flintstones, hand warmer: Alleviating freezing damage in mountains...?)
-  Easy to implement (they're just tiny gadgets ^^)

**Comment by BluSunrize** [comment]
Well IE technically doesn't have kerosene in it, and diesel *isn't* something you'd put in a lighter.
I could see this potentially using Ethanol?

I'm intrigued by you mentioning "freezing damage in mountains". The only thing I know of in Minecraft regarding that is powder snow, which slows you down and hurts you with extended exposure. But it's very rarely even found in the world, and somewhat easy to circumvent, as far as I know?

**Comment by kwaitsing** [comment]
You're right about the hand warmer (pretty useless)

But I think kerosene is a good idea tho.

It drives a lot of retro gadgets like kerosene lamps, and can also be used as fuel.

**Comment by BluSunrize** [comment]
Yes but kerosene requires raw oil, which in turn needs to be distilled to fracture into components. Immersive Petroleum already does all this. I am not adding it to IE.

I'm closing this, given that the "warming" feature is also discarded.

@TwistedGate freebie for you, if you wanna add it!

**Comment by TwistedGate** [comment]
> It drives a lot of retro gadgets like kerosene lamps, and can also be used as fuel.

Kerosene lamp sounds cool in theory, but in practice the electric lamps are more practical in my opinion

the Kerosene Lighter on the other hand sounds like a nice alternative to flint & steel
(even tho that is stupid simple to craft but atleast it would give kerosene an alternative use~)
