### ISSUE TITLE
Diesel generators have serious bugs.Water and milk should not be fuel！！

### ISSUE THREAD

**Issue by AWAKEN-1** [BluSunrize/ImmersiveEngineering#5905]
### Minecraft Version

1.20.1

### Immersive Engineering Version

ImmersiveEngineering-1.20.1-10.0.0-169

### Expected Behavior

Water and milk should not be fuel！！！

### Actual Behavior

Water and milk can be used as fuel

### Steps to reproduce

![2024-04-02_22 28 46](https://github.com/BluSunrize/ImmersiveEngineering/assets/77484596/3667cf34-39ca-49cc-b52a-e11617d63681)
![2024-04-02_22 28 48](https://github.com/BluSunrize/ImmersiveEngineering/assets/77484596/e15c75b6-748c-4fb6-b2c7-3dce9a34ce8c)
![2024-04-02_22 37 59](https://github.com/BluSunrize/ImmersiveEngineering/assets/77484596/d49296a8-d750-4721-9bc1-547fcc1657d9)
![2024-04-02_22 38 01](https://github.com/BluSunrize/ImmersiveEngineering/assets/77484596/c3266727-65fc-47be-910f-8f75dbde6211)

### Debug Crash Log

no

**Comment by AWAKEN-1** [comment]
I thought this would be fixed in Immersive Engineering-1.20.1-10.1.0-171, but it wasn't, when I filled the bucket with water or milk, and then right-clicked the generator with the Engineer's hammer, the generator would still absorb the fluid and produce energy. At the same time, this update seems to have broken Jade's ability to see fluid information in diesel generators

**Comment by Zahkriiven** [comment]
Confirmed in 1.20.4. Even then, crashlog is recommended to see the modlist.

**Comment by BluSunrize** [comment]
Resolved for future releases
