### ISSUE TITLE
[1.20.1]Any fluid can destroy any multi-block structure

### ISSUE THREAD

**Issue by AWAKEN-1** [BluSunrize/ImmersiveEngineering#5906]
### Minecraft Version

1.20.1

### Immersive Engineering Version

ImmersiveEngineering-1.20.1-10.1.0-171

### Expected Behavior

The multi-block structure should be a little stronger and not be destroyed so easily by fluids

### Actual Behavior

When the fluid is placed, the flow will directly destroy the multi-block structure, like washing away the block like a carpet, and in the case of biodiesel, ethanol, etc., the destroyed block will disappear directly. It's not clear to me if this was done on purpose (diesel is corrosive?)

### Steps to reproduce

https://github.com/BluSunrize/ImmersiveEngineering/assets/77484596/8fb46622-953a-44e5-880d-3946a97267f6

This is just one example, as all multi-block structures in the game can be destroyed like this by any fluid that can flow.
Silent tears for my lost 1000B biodiesel ╥﹏╥

### Debug Crash Log

Honestly, I don't think the crash log should be useful

**Comment by Zahkriiven** [comment]
Confirmed in 1.20.4 too.

**Comment by BluSunrize** [comment]
Resolved for future releases
