### ISSUE TITLE
[1.20.1] Filling Immersive Engineering wooden barrel with cresorte oil from railcraft reborn causes crash

### ISSUE THREAD

**Issue by DoctorMage** [BluSunrize/ImmersiveEngineering#5908]
### Minecraft Version

1.20.1

### Immersive Engineering Version

ImmersiveEngineering-1.20.1-10.1.0-171.jar

### Expected Behavior

Begin to put cresorte oil inside barrel once filled game will not crash

### Actual Behavior

Filling wooden barrel to capcity will cause crash

### Steps to reproduce

1. Place wooden barrel
2. get cresorte oil from railcraft
3. begin to put cresorte into barrel
4. after being filled to capcity game crashes

### Debug Crash Log

https://gist.github.com/DoctorMage/0f496a15d507cc4b00955a2661270009

**Comment by BluSunrize** [comment]
Doesn't look like our fault?
The stacktrace is all railcraft, go report to them.
