### ISSUE TITLE
Blacklist fluids for jerrycan?

### ISSUE THREAD

**Issue by TheQuantumGeneral** [BluSunrize/ImmersiveEngineering#591]
Would a fluid blacklist be possible? or config to disable in world fluid placement with the jerry can? Server has a pretty good ecosystem of using carts or pipelines to deliver oil, becomes redundant when people can carry 10 buckets worth in a single slot

edit: actually, could do the same thing with barrels too with a bit of effort, might just minetweak them both out.

**Comment by beringtom** [comment]
Sounds like something you should disable with minetweaker or something similar.
A blacklist of fluids "might" be usefull.

**Comment by johnfg12** [comment]
a blacklist would be useful

**Comment by PrincessRTFM** [comment]
Controlling what fluids could be put into a jerrycan would be useful, I agree. Not sure how hard it would be though...
