### ISSUE TITLE
[1.20.4] Placing a covered vertical belt causes client to crash immediately and on subsequent reloads of the world.

### ISSUE THREAD

**Issue by maker-dude** [BluSunrize/ImmersiveEngineering#5910]
### Minecraft Version

1.20.4

### Immersive Engineering Version

11.1.0-172

### How did it happen?

Placing a standard covered vertical conveyor into the world.

### Crash Log

https://gist.github.com/maker-dude/ea8819885aa8c2457b57eb1443f53f8e

**Comment by maker-dude** [comment]
As requested, here is a crash log with only immersive engineering enabled.
In addition this on a brand new world single player world with the only placed block being a covered vertical conveyer belt. Glad to provide the world as well if desired.

https://gist.github.com/maker-dude/2b243956685eb7ffd7158afe50dd789c

**Comment by BluSunrize** [comment]
Fixed for future releases
