### ISSUE TITLE
[1.20.1] IRecipe#matches issue

### ISSUE THREAD

**Issue by border999** [BluSunrize/ImmersiveEngineering#5913]
### Minecraft Version

1.20.1

### Immersive Engineering Version

ImmersiveEngineering-1.20.1-10.1.0-171

### Expected Behavior

None lag parade. 

### Actual Behavior

keep getting lag spikes that lock up my game for small stretches of time before letting me go about my business.

### Steps to reproduce

Please check around the bottom of the log.

### Debug Crash Log

https://gist.github.com/border999/b9ec0102ee390ccc3c2d24d406d0b9f7

**Comment by BluSunrize** [comment]
Looks like `verdantartifice` is querying a bunch of recipes, and doing so with an incorrect recipe container.
We don't allow that for our fluid recipes.

But this isn't us causing the issue.
