### ISSUE TITLE
Redstone Interface Connector not working with CC: Tweaked in 1.20.4

### ISSUE THREAD

**Issue by Sharparam** [BluSunrize/ImmersiveEngineering#5914]
### Minecraft Version

1.20.4

### Immersive Engineering Version

11.1.0-172

### Expected Behavior

Should be able to set the redstone values on the interface connector, just like in 1.20.1.		

### Actual Behavior

Nothing gets set on the interface connector.

### Steps to reproduce

1. Place a CC: Tweaked computer
2. Place a Redstone Interface Connector on top
3. Place a redstone lamp next to the computer
4. Place a Redstone Wire Connector on top of the lamp
5. Connect the interface to the wire connector with Redstone Wire Coil
6. Configure the connector on top of the lamp to be "output - red"
7. Set the top redstone output on the computer: `rs set top red true`

### Debug Crash Log

https://gist.github.com/Sharparam/b45c9678a0e9f2d258e73b595fdebbd9

**Comment by BluSunrize** [comment]
@malte0811 CC:Tweaked Compat seems to have been fully removed.

As far as I can see, it should be able to restore it, but the changes to capability registration and our own Multiblock logic necessitate some changes to everything.
I'm assigning this one to you, but it's low-prio, don't stress yourself.

**Comment by malte0811** [comment]
Fixed by 2952ec85343c3ad53b15eae764c16f442776f4b8 and 98320a36858c8e21e5e23f8ac0e573bd6279a79b
