### ISSUE TITLE
[Suggestion] ... Conductive Coil Blocks

### ISSUE THREAD

**Issue by jacobeman5872** [BluSunrize/ImmersiveEngineering#5916]
### Description
Allow the coil blocks (Copper Coil Block, Electrum Coil Block, High-Voltage Coil Block) to pass power through them like a relay.
I was kind of thought this would already be a feature

In the modpack I'm playing at the moment (FTB Skies Expert), the accumulators are not craftable. I wanted to pass a wire through a wall, and thought the coil block should be able to do that.

### Use case
- Running wires through walls via coil block.
- Budget tesla coil.
- Cooler powerlines 😎

**Comment by BluSunrize** [comment]
Accumulators not being craftable is a major flaw in whatever modpack you are playing. Play better modpacks =P

Also, to route a wire through the wall, simply use a Feedthrough Insulator. It's described on the last page of the "Basic Wiring" entry in the manual =)

**Comment by mindforger** [comment]
Mhhhh.... Wire coil blocks, when powered, attract metal blocks like electromagnets, imagine the anvil trap XD i know this already is possible with piston...

**Comment by BluSunrize** [comment]
> Mhhhh.... Wire coil blocks, when powered, attract metal blocks like electromagnets, imagine the anvil trap XD i know this already is possible with piston...

We literally have an electro magnet block in 1.201. :/
