### ISSUE TITLE
The game crashed whilst tesselating block model

### ISSUE THREAD

**Issue by Razvedka2020** [BluSunrize/ImmersiveEngineering#5923]
### Minecraft Version

1.20.4

### Immersive Engineering Version

11.1.0-172

### How did it happen?

When installing a vertical conveyor into the world.

### Crash Log

https://gist.github.com/Razvedka2020/08d2b188e331859dd2bbde783ef49d31

**Comment by BluSunrize** [comment]
Duplicate of #5910

Already fixed for future releases =)
