### ISSUE TITLE
shaders aint rendering some of the mods items

### ISSUE THREAD

**Issue by yolatcomehere** [BluSunrize/ImmersiveEngineering#5926]
### Minecraft Version

1.20.1

### Immersive Engineering Version

1.18.2

### Expected Behavior

so i was play a survival i build a windmill and the windmill was not there so i wondering why

### Actual Behavior

then the rendering for other items is not working either here all the item i found so far projector, windmill, water wheel 

### Steps to reproduce

steps in the expected behavior

### Debug Crash Log

na

**Comment by BluSunrize** [comment]
1) Shaders are not supported
2) 1.18 is not supported
3) The projector isn't even from this mod
