### ISSUE TITLE
idea add the forge files back for 1.20.1 don't need support just need it

### ISSUE THREAD

**Issue by rrazfraz123** [BluSunrize/ImmersiveEngineering#5927]
### Explain your idea

please

**Comment by rrazfraz123** [comment]
really need 1.20.1 forge ie back

**Comment by rrazfraz123** [comment]
don't get why the files were removed

**Comment by BluSunrize** [comment]
They weren't removed, they never existed.

We've been on NeoForge since 1.20.1, old Forge is not supported anymore. We have never released a Forge based build on 1.20.1.

**Comment by rrazfraz123** [comment]
never existed eh?

this is forge 1.20.1 with all the mods 9 so how is there no  file?

 @[BluSunrize](https://github.com/BluSunrize)
![Screenshot 2024-05-08 170315](https://github.com/BluSunrize/ImmersiveEngineering/assets/44677608/783b318f-d5eb-4cdc-bb64-5911edcbb8a4)

**Comment by rrazfraz123** [comment]
but alr great work on the mod btw

**Comment by rrazfraz123** [comment]
oh lol the mod works on this version imma test the newer

**Comment by rrazfraz123** [comment]
newest version of the mod works on forge by newest i mean the newest one for the neoforge 1.20.1

**Comment by rrazfraz123** [comment]
or at least the parts i tried worked

**Comment by BluSunrize** [comment]
> never existed eh?
> 
> this is forge 1.20.1 with all the mods 9 so how is there no file?
> 
> @[BluSunrize](https://github.com/BluSunrize) ![Screenshot 2024-05-08 170315](https://private-user-images.githubusercontent.com/44677608/329085529-783b318f-d5eb-4cdc-bb64-5911edcbb8a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0NjMyOTksIm5iZiI6MTcxNTQ2Mjk5OSwicGF0aCI6Ii80NDY3NzYwOC8zMjkwODU1MjktNzgzYjMxOGYtZDVlYi00Y2RjLWJiNjQtNTkxMWVkY2JiOGE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDIxMjk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0M2E2MDNhNDQ1Yjc0NmUyMmVhYjNlNzFlZmU5NzM0YTZjOGJhMGE5MWVhYzIyNThlNGZlY2YwMjExZWE5NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sFrU-emanD965gg16jEK91jvXcdQ_D4pgm4pDdZzSKo)

That's still a NeoForge release for goodness sake. We never published on Forge, I would know this **because I publish the mod.**
