### ISSUE TITLE
Neoforge 1.20.4 Latest version of Immersive causes a crash on servers at launch

### ISSUE THREAD

**Issue by Saereth** [BluSunrize/ImmersiveEngineering#5928]
### Minecraft Version

1.20.4

### Immersive Engineering Version

ImmersiveEngineering-1.20.4-11.2.0-173

### Expected Behavior

Mod and pack to load

### Actual Behavior

Pack fails to load

### Steps to reproduce

Upgraded Immersive to the latest build, this issue does not occur on build ImmersiveEngineering-1.20.4-11.2.0-172
The pack also loads fine in single player

### Debug Crash Log

https://mclo.gs/0LQcQEu

**Comment by BluSunrize** [comment]
Can you please try removing Polylib and see if that resolves the issue?

**Comment by Saereth** [comment]
yep I was able to confrrm that with polylib disabled it doesnt crash. I've got an issue open over on polylib's as well as I wasnt quite sure where the issue was happening. 

Presently downgrading IE causes it not to crash anymore or Removing Polylib doesnt cause it to crash

https://github.com/CreeperHost/PolyLib/issues/46

**Comment by Saereth** [comment]
looks like this got fixed on polylib's end so we're good to go now, thanks for having a look!

**Comment by Saereth** [comment]
They have fixed the issue in polylib now so it doesnt crash there however if I actually place a machine interface on a server now it still crashes,
https://mclo.gs/KN3T69r

specifically while calling calling org/apache/commons/compress/utils/Lists on the server
