### ISSUE TITLE
Vertical conveyor belt with steel scaffolding cover crashes the game

### ISSUE THREAD

**Issue by mctoozle** [BluSunrize/ImmersiveEngineering#5929]
### Minecraft Version

1.20.4

### Immersive Engineering Version

ImmersiveEngineering-1.20.4-11.1.0-172

### Expected Behavior

To place down the vertical conveyor block

### Actual Behavior

As soon as you place it the client crashes because of a tesselation/render issue. 

### Steps to reproduce

pretty clearly already stated above

### Debug Crash Log

https://gist.github.com/mctoozle/1d0d045d1383870f06e415c84c016390

**Comment by BluSunrize** [comment]
Update IE, this is fixed already!

**Comment by mctoozle** [comment]
I have the latest version for neoforge(you can see this in the crash report
no?). I don't know where it's possible to get a newer version?

**Comment by BluSunrize** [comment]
No, you don't have the newest version. The most recent release for 1.20.4 is **11.2.0-173**, which was published on May 1st and is available on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/immersive-engineering/files/5306499) and [Modrinth](https://modrinth.com/mod/immersiveengineering/version/11.2.0-173).

**Comment by mctoozle** [comment]
Ah, I wasn't aware the curseforge site just changes the latest download for
the same 1.20.4 drop-down option.

It's all working now - thanks!
