### ISSUE TITLE
Engineer's Crafting Table UI[Suggestion] ... 

### ISSUE THREAD

**Issue by Black-Mage01** [BluSunrize/ImmersiveEngineering#5930]
### Explain your idea

I would like to adjust the wood/brick looking UI because it's a bit busy for me. something a bit more smooth or standard... it's by far and away the best crafting bench before Applied Energistics in my modpack (Ultimate Progression, MC ver1.16.5)

I'm not sure how difficult it would be to push an update to all of the different version of MC you support but this shouldn't be too difficult. Maybe there could be a section of the config where a pattern or color could be chosen by the player.

**Comment by mindforger** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/tree/1.20.1/src/main/resources/assets/immersiveengineering/textures/gui
you can use a datapack to change it yourself and send a PR if you like :D

**Comment by BluSunrize** [comment]
Yeah resource packs can just do this. Don't see us making a config for that.
