### ISSUE TITLE
Unable to build silos/tanks

### ISSUE THREAD

**Issue by Zigster191** [BluSunrize/ImmersiveEngineering#5935]
### Minecraft Version

1.20.1

### Immersive Engineering Version

ImmersiveEngineering-1.20.1-10.1.0-171

### Expected Behavior

Should be able to build a silo, but I can't. I've also tried previous version of Immersive Engineering for 1.20.1 MC without success. I am running Better Minecraft v26 with pam's harvestcraft, boiledegg, mobcatcher, and travelersbackpack client side and grieflogger, clearlag, and letmedespawn server side.

![immersive](https://github.com/BluSunrize/ImmersiveEngineering/assets/90150861/c4e80570-ce73-4ef4-9412-29242f896f4e)

### Actual Behavior

Unable to build silo or water tanks. No game crashes.

### Steps to reproduce

Unable to build silo

### Debug Crash Log

https://pastebin.com/R8mUyBVH

**Comment by BluSunrize** [comment]
Can you reproduce this in an instance with just IE installed and no other mods?

**Comment by Zigster191** [comment]
I tried and I couldn't. I switched to singleplayer with all the mods enabled and it worked so it must be something to do with server mods. I guess I'll get to testing.

**Comment by BluSunrize** [comment]
My first instinct is always to take of any shader mods such as rubdium or optifine, we've seen those be the cause of issues plenty before.
Beyond that, binary search is your best friend, removing half the mod list and seeing if the issue persists, but even with it being low complexity, it's still a _lot_ of work to do on a server ^^"
