### ISSUE TITLE
Can you add a config options to modify recipes in IE?

### ISSUE THREAD

**Issue by NeoForce0** [BluSunrize/ImmersiveEngineering#5939]
### I do enjoy using IE... but I'd like to modify many of the recipes you have on this project. 

Such as 2 ingots per plate to match other mods rather than 1 ingot per plate. Also alloy recipes for example 9copper-1Tin for 10 bronze. I'm setting up the ratios of ores in the configs to closer to realism and rarity. 

I can't find anyway to manually modify these values in config files.

**Comment by TeamSpen210** [comment]
These are all defined in recipes, you can override them in a datapack.

**Comment by BluSunrize** [comment]
"Most other" mods use a single ingot actually =p
