### ISSUE TITLE
The excavator is not working

### ISSUE THREAD

**Issue by Mifr1l3551** [BluSunrize/ImmersiveEngineering#5948]
### Minecraft Version

1.20.1

### Immersive Engineering Version

ImmersiveEngineering-1.20.1-10.0.0-169

### Expected Behavior

the problem is in the multi-block structure itself.
the excavator does not see the bucket and cannot dig because of this, although the bucket is actually present.
![image](https://github.com/BluSunrize/ImmersiveEngineering/assets/166610642/7014fd01-463f-499d-a62c-550d657174a7)

### Actual Behavior

I built an excavator and a bucket, started it by pressing the engineer's hammer, the bucket became invisible, but it was actually present, I applied electricity and it did not work

### Steps to reproduce

build excavator

### Debug Crash Log

.

**Comment by BluSunrize** [comment]
Since you didn't provide a debug crash, we don't have a modlist from you.
If you are using Optifine or Rubidium, that may very well be why the bucket wheel is invisible.

Additionally, did you take a core sample where the excavator is placed? What minerals are you expecting there?
