### ISSUE TITLE
[1.20.4] model for offhand Revolver and Railgun look inside out

### ISSUE THREAD

**Issue by MalkContent** [BluSunrize/ImmersiveEngineering#5949]
### Minecraft Version

1.20.4

### Immersive Engineering Version

6e50a71f0c141dea10452fd00e2808b41c167b0c

### Expected Behavior

They look the same as when in the main hand, but mirrored.

### Actual Behavior

They look inverted. Everything is mirrored?
This affects both first and third person offhand models.

### Steps to reproduce

Place Revolver/Railgun in offhand.

### Debug Crash Log

N/A

**Comment by BluSunrize** [comment]
Technically a duplicate of #5943, but that issue is compounding three different things
