### ISSUE TITLE
Aluminium recipes not using oreDictionnary

### ISSUE THREAD

**Issue by LemADEC** [BluSunrize/ImmersiveEngineering#596]
As observed with ImmersiveEngineering-0.5.4 and gregtech_1.7.10-5.09.09, when using IE with GregTech, IE recipes requiring aluminium (HV wire coil for example) will only accept IE's aluminium.
Other metal ingots seems to work fine according to NEI, so there's probably something wrong specifically with Aluminium.

**Comment by cobra** [comment]
All wire coils are registered the same way as oredict'ed recipes. Looks more like an issue with the other aluminium. You can use NEI Integration to check whether it is in the oreDictiionary (either by enabling the recipe handler → oredict setting or by enabling the oredict tooltips).

**Comment by BluSunrize** [comment]
No, this is Greg's fault. He refuses the unspoken consensus of ore registration. Every mod developer but him registers as "ingotAluminum", making the US spelling the common and widely accepted OreDict entry.
Greg registers as "ingotAluminium", the British spelling. While I prefer BE myself and use it for actual naming of the items, the OreDict is still done with the key that EVERYONE ELSE uses. Greg, once again wants to be a special snowflake, so his registration breaks things.

I'll fix this is a jiffy, don't worry.
