### ISSUE TITLE
empty tag forge 

### ISSUE THREAD

**Issue by snlumi** [BluSunrize/ImmersiveEngineering#5962]
### Minecraft Version

1.20.1

### Immersive Engineering Version

171

### Expected Behavior

Items cannot be combined

### Actual Behavior

I added this mod to my modpack.

### Steps to reproduce

I added this mod to my modpack and played it.
However, while playing I noticed that some recipes in Immersive Engineering were broken and all steel tags were missing.
I thought the tag was the problem and tried to solve it, but it didn't work, and I found out that the combination of breaking the ore into dust with a hammer was also broken (the dust tag was normal).

### Debug Crash Log

[crash-2024-06-20_17.50.11-client.txt](https://github.com/user-attachments/files/15911349/crash-2024-06-20_17.50.11-client.txt)

**Comment by BluSunrize** [comment]
Something else is breaking your tag loading.
You can try using [Load My F*** Tags](https://www.curseforge.com/minecraft/mc-mods/lmft) to fix this.
Otherwise you'll have to try and identify which mod in your pack is breaking it.
