### ISSUE TITLE
Chutes don't insert into composter

### ISSUE THREAD

**Issue by Gammel2013** [BluSunrize/ImmersiveEngineering#5969]
### Minecraft Version

1.20.4

### Immersive Engineering Version

11.4.1-176

### Expected Behavior

I expect chutes leading into composters to behave similar to hoppers, and to start composting items if they are valid inputs for the composter.

### Actual Behavior

Currently chutes drop the items into the composter, where they're lying around in the world, instead of being used to compost:
![grafik](https://github.com/BluSunrize/ImmersiveEngineering/assets/160730477/8520e5ab-4b26-4487-9c70-2b110bbf6efa)

### Steps to reproduce

Place down composter.
Place down chute above.
Throw compostable items into chute

### Debug Crash Log

https://pastebin.com/8BW3Z1Ck

**Comment by BluSunrize** [comment]
Somewhat intentional, the chute can only insert when the items collide with a block underneath (such as a chest).
The composter has a hole in the middle, so the items fall inside and only collide with it when they are outside the chute.
