### ISSUE TITLE
Smelting Grit Provides 0 Experience

### ISSUE THREAD

**Issue by AriaElidove** [BluSunrize/ImmersiveEngineering#5975]
### Minecraft Version

1.20.4

### Immersive Engineering Version

11.4.3-178

### Expected Behavior

Blasting/Smelting material grits into ingots should provide Experience, just like how their raw variants do. 

### Actual Behavior

0 experience is gained from smelting grit. Using JEI, it shows there is no value, which I assume either means that the value is null, or zero intentionally

![image](https://github.com/BluSunrize/ImmersiveEngineering/assets/144502047/67f8afe5-91fb-482a-bd84-f8f786a5c312)

### Steps to reproduce

Smelt Grit. Get 0 XP

### Debug Crash Log

Only JEI and IE were used in the testing of this.

**Comment by TeamSpen210** [comment]
This does need to be zero, because you can repeatedly crush ingots back into grit, producing infinite XP.

**Comment by BluSunrize** [comment]
Correct, this is intended behaviour =)
