### ISSUE TITLE
Immersive Engineering not showing up

### ISSUE THREAD

**Issue by PaytonBlip** [BluSunrize/ImmersiveEngineering#5995]
### Minecraft Version

1.20.1

### Immersive Engineering Version

.

### How did it happen?

Immersive Engineering isn't crashing my game; rather, the problem is that it doesn't appear when you try to add the mod to a 1.20.1 mod pack on Curse Forge.

### Crash Log

.

**Comment by BluSunrize** [comment]
Because we don't release for Forge. Only for NeoForge.

**Comment by PaytonBlip** [comment]
However, it indicates that it is for Curse Forge 1.20.1 and other versions, and my friends and I had previously utilized Immersive Engineering on Curse Forge.

**Comment by Papaturts** [comment]
its on curseforge, but wasnt released for forge, only neoforge for now on

**Comment by BluSunrize** [comment]
> However, it indicates that it is for Curse Forge 1.20.1 and other versions, and my friends and I had previously utilized Immersive Engineering on Curse Forge.

"CurseForge" has nothing to do with the Minecraft modding APIs "Minecraft Forge" and "NeoForge".
Curse is simply the place we host our mods, which are also found on Modrinth.

IE is only releasing for NeoForge from here on, so if you have a Minecraft Forge instance, we offer no support.
