### ISSUE TITLE
Crafting Treated Wood Planks consumes the creosote container.

### ISSUE THREAD

**Issue by BarbasTheDog** [BluSunrize/ImmersiveEngineering#6]
Title pretty much says it all.

Mod is looking pretty snazzy :)

**Comment by BluSunrize** [comment]
Long since fixed =P

**Comment by BarbasTheDog** [comment]
But I just compiled it yesterday

**Comment by mallrat208** [comment]
Not all changes are reflected by the code currently in the repo. Blu's been
doing' the work

**Comment by BluSunrize** [comment]
^ This.
I usually push to git when I compile the mod.

**Comment by BarbasTheDog** [comment]
ah, makes sense. ^ ^
