### ISSUE TITLE
Possible Bug

### ISSUE THREAD

**Issue by wesker1213** [BluSunrize/ImmersiveEngineering#60]
I have a lightning rod created, and it works fine when using mv capacitors, and electrum wires. However, when using hv wire's, I get a client crash. I am using this mod in conjunction with the direwolf20 pack. 

Pastebin link to the crash log : http://pastebin.com/YsxHAsCm

What do you think is the cause? Do note, I am going to try on a fresh install of the pack as I've been on this one for a while now.

**Comment by BluSunrize** [comment]
Oh, that's a derp on my side, I forgot a null check there. Thank you =)

**Comment by wesker1213** [comment]
Not a problem. Having seen Direwolf use the mod, I was surprised to see it. Do you happen to know when version 1.17 is being released?

**Comment by BluSunrize** [comment]
Next one will be named 0.2.0, and hopefully till the weekend.
