### ISSUE TITLE
[Manual / QoL] - Engineer's Handbook Searching

### ISSUE THREAD

**Issue by AriaElidove** [BluSunrize/ImmersiveEngineering#6000]
### Explain your idea

Allow the Engineer's Handbook to search while in a specific page's topic. You can currently search while on the main manual page or in a subcategory, but when you attempt to search something while within a content page, you will not be able to do so. This suggestion requests that this be changed.

----
In Main Page:
![image](https://github.com/BluSunrize/ImmersiveEngineering/assets/144502047/18a3e23f-5dd1-4d43-91b9-9eefb3c8a18e)

In Sub-Category:
![image](https://github.com/BluSunrize/ImmersiveEngineering/assets/144502047/8b49c553-2dd1-4209-b216-ab8260fa19c3)

In Content Page:
![image](https://github.com/BluSunrize/ImmersiveEngineering/assets/144502047/e955f330-8dfe-40a4-bf7e-9f71d81e652b)

**Comment by BluSunrize** [comment]
The search results replace the page content.
When you are searching in an entry, you'd lose the entry itself, and entries are a *lot* more complicated than the lists of page / category titles.
That's why this is not possible.
