### ISSUE TITLE
[Suggestion] 1.20.1 Support

### ISSUE THREAD

**Issue by Casalyz** [BluSunrize/ImmersiveEngineering#6002]
### Explain your idea

Neoforge Team Specifically says to use the forge modloader for 1.20.1

"We also apologise for not providing the stable 1.20.1 environment we promised. After 1.20.2 was released, we neglected 1.20.1 and still are. Development efforts on 1.20.1 are better spent on Forge rather than NeoForge." https://neoforged.net/news/2023-retrospection/

If you try to download Neoforge for 1.20.1 it installs forge 47.1.106 there is no neoforge file released anywhere on their website for 1.20.1 so can we please have an IE release for forge 1.20.1? idk how ATM 9 has IE for 1.20.1 because IE crashes on load up for 1.20.1 and it will not work.

**Comment by BluSunrize** [comment]
No. We are not releasing for Forge.
