### ISSUE TITLE
[GUI / QOL] - Arc Furnace Completeness Values 

### ISSUE THREAD

**Issue by AriaElidove** [BluSunrize/ImmersiveEngineering#6005]
### Explain your idea

Show percentages when hovering over the red fill-up bar for Arc Furnace items. This allows for more accurate and clear information to the player.

If implimented, whenever my mouse hovers over the red bar, it should show a percentage of it's completion (1-99%)
![image](https://github.com/BluSunrize/ImmersiveEngineering/assets/144502047/1da32149-02f3-43b3-89f9-3f329d44478c)

**Comment by BluSunrize** [comment]
![grafik](https://github.com/user-attachments/assets/74babc00-1519-43e3-9f53-888e6dc6842c)

Got chu.
