### ISSUE TITLE
Unable to Craft any Accumulators

### ISSUE THREAD

**Issue by CTCrafter3** [BluSunrize/ImmersiveEngineering#6009]
### Minecraft Version

1.20.1

### Immersive Engineering Version

1.20.1-10.1.0-171

### Expected Behavior

I am trying to craft an Accumulator/capacitor to progress with the mod. I am using the Mod within Valhelsia 6

### Actual Behavior

I put the required ingredients into the crafting table, but it does not show up, I've seen the accumulator show up for a split second, but it disappears before I can craft it

### Steps to reproduce

1. I tried to input the materials manually into the crafting table it didn't work.
2. I tried to use JEI to input the items for me into the crafting table. Still didn't work.
3. I tried using the Engineer's crafting table. Still didn't work there

![Accumulator Screenshot](https://github.com/BluSunrize/ImmersiveEngineering/assets/174908911/574cc658-6a0f-463a-8c83-73891391d659)

Here's an image showing the materials in the crafting table, but nothing's showing up.

### Debug Crash Log

https://pastebin.com/Nu9hsfRg

**Comment by TeamSpen210** [comment]
Accumulators need a bucket of Redstone Acid in the middle, you're missing that. It's crafted with 4 redstone + water bucket.

**Comment by AriaElidove** [comment]
> I tried to use JEI to input the items for me into the crafting table. Still didn't work.

JEI and the Recipe Book *should* have brought up the mention of the Redstone Acid, so that is a bit odd. UNLESS Valhelsia 6 changed the recipes, then this isn't an issue :)

**Comment by BluSunrize** [comment]
Yeah I'm closing this because it's likely not an issue on our end.
