### ISSUE TITLE
Crash when IE turret activated.

### ISSUE THREAD

**Issue by KingSejong25** [BluSunrize/ImmersiveEngineering#6010]
### Minecraft Version

1.20.1

### Immersive Engineering Version

ImmersiveEngineering-1.20.1-10.1.0-171

### How did it happen?

Crash occurred when the IE turret was activated.
But I don't know the cause of this problem.  ......Acedium? or Embeddium?
I'm sorry, but can I ask you to check it?

It was written by a Korean using Google Translator.
Thanks.

### Crash Log

https://gist.github.com/KingSejong25/673440b64d1c83eeade07d744738e797

**Comment by BluSunrize** [comment]
Can you reproduce this issue with NeoForge?

Because we don't support Minecraft Forge anymore.

**Comment by KingSejong25** [comment]
@BluSunrize 
Thanks!
Now, it works fine!

**Comment by KingSejong25** [comment]
@BluSunrize 
I apologize for the late answer.
I didn't know about what happened with Forge and Neoforge.

Now, it works better than before.
The crash still occurs, but the frequency has decreased.

I've seen that it happens more often when pausing game(esc key) after changing the shader.

### Crash Log
https://gist.github.com/KingSejong25/faa378b931de1136c55434509ec02eba

Thanks a lot!

**Comment by BluSunrize** [comment]
Shaders are also not supported =p

**Comment by KingSejong25** [comment]
@BluSunrize 
Oh, Sorry.
I didn't think of it.

Thank you for your response!
