### ISSUE TITLE
Crusher won't do anything despite all requirements

### ISSUE THREAD

**Issue by Vulkanus-Maximus** [BluSunrize/ImmersiveEngineering#6022]
### Minecraft Version

1.20.1

### Immersive Engineering Version

1.18.2-8.4.0-161

### Expected Behavior

Crusher crushing blocks into dusts, ores into ingots, possibly damaging the player.

### Actual Behavior

None of the above.

### Steps to reproduce

1. Built the structure
2. Provide sufficient power
3. Turn on the machine via lever (or without)
4. No action
5. Test both on my Survival world and Creative world
6. Still no actions.

Modpack (and modlist): DeceasedCraft - Modern Zombie Apocalypse:
Game Version: 1.18.2
forge: 40.2.4
Picture:
![2024-07-15_14 36 52](https://github.com/user-attachments/assets/77af7f6f-ace4-4274-b8d3-c72575e7163f)

### Debug Crash Log

<script src="https://gist.github.com/Vulkanus-Maximus/06390fafb89b9423e86b6fce82e57a22.js"></script>

**Comment by BluSunrize** [comment]
The lever turns the machine off, it says so in the manual =P

Also 1.18 is long out of support, sorry!

**Comment by Vulkanus-Maximus** [comment]
> The lever turns the machine off, it says so in the manual =P
> 
> Also 1.18 is long out of support, sorry!
Thanks for letting me know, but I did try it with and without the lever. On and off, everything I can think of.
I see nothing else around that could help a 1.18 problem, so I guess the Crusher is just a loss cause. I wonder why DeceasedCrafts stays in 1.18 with no one else asking or having the same problem as I.
Either way, thanks!
