### ISSUE TITLE
Ear Defenders not muffling machines

### ISSUE THREAD

**Issue by PiecewiseLantern** [BluSunrize/ImmersiveEngineering#6025]
### Minecraft Version

1.20.1

### Immersive Engineering Version

10.1.0-171

### Expected Behavior

With the Ear Defenders equipped, all specified sound categories, including IE machines, should be muffled at the noise gate threshold.

### Actual Behavior

The specified Minecraft sound channels are muffled but IE machines are not.

### Steps to reproduce

1. Turn on loud machine (Arc Furnace smelting multiple items at once, Diesel Generator, etc.)
2. Configure Ear Defenders' noise gate to 100%
3. Equip Ear Defenders
4. Loud machine is not muffled

### Debug Crash Log

https://gist.github.com/PiecewiseLantern/60679d2aa59846a035fd14a263d95583

**Comment by DrUltraLux** [comment]
Can confirm they don't seem to be working at all.

**Comment by BluSunrize** [comment]
Yep, was fixed on 1.20.4, but can't easily be backported.
Sorry, wont fix.
