### ISSUE TITLE
Breaker switch needs an update

### ISSUE THREAD

**Issue by IIIpl4sm4III** [BluSunrize/ImmersiveEngineering#6026]
The breaker switch not being able to do high voltage lines makes it essentially useless. The book suggesting "used to separate power-hungry machinery from the network..." also implies this is really only useful for machines likely only hooked up by HV. There are usually other mods added in packs that accomplish the same thing, I would just like to use IE with it just because its the same ecosystem. Also, breaker switches in a high voltage environment is [definitely a thing](https://www.volcano-electrical.com/uploads/201920665/outdoor-high-voltage-vacuum-load-break-switch07485230637.jpg).

The trigger sound for it could also use an [update](https://freesound.org/people/jessepash/sounds/139970/), an in-joke running nearly a decade remaining unchanged is pretty funny though.

**Comment by TeamSpen210** [comment]
You don't really need HV for most machines, only the Excavator and Arc Furnace. If you really do need to switch HV, you can use the more isolated Redstone Breaker. Note that the breaker switch also produces a redstone signal, so it's nice to use as a more industrial lever.

**Comment by IIIpl4sm4III** [comment]
> You don't really need HV for most machines, only the Excavator and Arc Furnace. If you really do need to switch HV, you can use the more isolated Redstone Breaker. Note that the breaker switch also produces a redstone signal, so it's nice to use as a more industrial lever.

Yeah, Its just clunky because it needs a direct redstone wire for it to be connected up to a normal lever. I would certainly not being using those as normal levers for the audio reasons. Personal preference I suppose? I just feel like thats relegated an otherwise useful item to a relatively niche purpose. If you have a decent amount of factories that span several chunks, running 'HV everywhere' is kind of the only viable way to make the network have enough throughput to handle most machines at the same time on a few generators.

**Comment by voidsong-dragonfly** [comment]
I fundamentally disagree with that, running HV trunk lines and MV branch lines works just fine for even the largest factories. The breaker switch works fine for the intended use case, which is for isolating parts of the network manually in places the player will be personally - the player is not intended to be near HV wire, and even being _close_ will shock you, so it makes sense that the manual breaker doesn't handle HV.

**Comment by BluSunrize** [comment]
You can just use a redstone breaker and redstone wiring to do it with a bit of distance.

So no, I don't think this needs any change.
