### ISSUE TITLE
Excavator should give spoils when no vein present

### ISSUE THREAD

**Issue by spiffyalligator** [BluSunrize/ImmersiveEngineering#6027]
### Explain your idea

When there is no mineral vein, the excavator should still excavate biome-related spoils rather than pulling up empty buckets. Could this be added as a 'background vein', for compatibility with other biomes/dimensions? (ex. sandstone, netherrack, end stone, and customizable for biomes added by other mods).

**Comment by BluSunrize** [comment]
If there isn't a vein, we don't know what the spoils should be!

Problem with using a "background vein" is that veins are generated at world-gen and using a hardcoded one as a fallback doesn't feel very good to me, from a developer perspective.

**Comment by spiffyalligator** [comment]
Hmm, I can see why you wouldn't want to hard code it in.
Is there a best way to increase the % of spoils in a vein? Since, it seems like if I find a vein, the center will have 100% saturation and give only the ores/loot.
I'm thinking I'd like to still give a lot of spoils even when I find the center, but it looks like I just have to move the spoils up in with the ores which isn't super clean.

**Comment by voidsong-dragonfly** [comment]
> Is there a best way to increase the % of spoils in a vein? Since, it seems like if I find a vein, the center will have 100% saturation and give only the ores/loot.
I'm thinking I'd like to still give a lot of spoils even when I find the center, but it looks like I just have to move the spoils up in with the ores which isn't super clean.


There's a `failChance` value in the recipe definition. That's the chance of the ore to 'fail' and be replaced with spoils while still being extracted. Up that, and up the total number of ores in veins, and that should work for your purposes.

**Comment by spiffyalligator** [comment]
Oh thank you! I misinterpreted and thought that a high failchance would cause it to pull up an empty bucket.

**Comment by voidsong-dragonfly** [comment]
> Oh thank you! I misinterpreted and thought that a high failchance would cause it to pull up an empty bucket.

It used to, but it got replaced with it being spoils back when I added spoils, I believe?

I do want to address this for a short amount, Blu:
> If there isn't a vein, we don't know what the spoils should be!
> 
> Problem with using a "background vein" is that veins are generated at world-gen and using a hardcoded one as a fallback doesn't feel very good to me, from a developer perspective.

I think pulling from datapack value where you can define one per biome and that one is used for that biome would be a reasonable solution, as you could have hardened clay mixed with stone in mesas, or sandstone mixed with stone in deserts, or blackstone mixed with basalt in basalt deltas.

Biome specificity should be enough, and then a default one to fall back to based on biome _tags_, ie "all nether biomes are netherrack" or "overworld biomes are dirt, cobble, deepslate", but I can see that being a lot of work for minimal effort.

It would also let IE generate "infinite" (large amounts) of stone-based building materials, which many other mods can but IE cannot, which would fill another gap in IE, even if it is a relatively small one.
