### ISSUE TITLE
(Curseforge bug) Immersive Engineering not downloadable from Curseforge Standalone App, using Add Content to Profile

### ISSUE THREAD

**Issue by MorganaLaLuna** [BluSunrize/ImmersiveEngineering#6028]
### Minecraft Version

1.20.1

### Immersive Engineering Version

N/A

### Expected Behavior

I realise this isn't a mod bug, but there's no category for this issue.

Expected behaviour is that the Immersive Engineering mod has versions to download through the Curseforge app.

### Actual Behavior

![image](https://github.com/user-attachments/assets/619538d7-5a30-4f7d-a098-9ce39817c8d1)

### Steps to reproduce

Should be obvious but:
1. Open Curseforge App
2. Open a custom profile
3. Click Add Content button (The puzzle piece)
4. Search for BluSunrize (I tried Immersive Engineering without version filters, it didn't appear)
5. Click on IE
6. No install button or versions available.

NOTE:
 I only realised as I was typing but, non of BluSunrize's mods have install buttons or version. Or release dates. Same with all but one of Sky_Som's mods. Malte0811's mods are fine though. Has curseforge targeted you guys, or is this a widespread bug affecting mod authors?

EDIT: This seems to be a bug when adding content to a profile. When just searching the mods outside of add content, it works as normal. I have altered the report to reflect this.

### Debug Crash Log

N/A

**Comment by BluSunrize** [comment]
IE is not available for Minecraft Forge.

We only release on NeoForge.
