### ISSUE TITLE
[Bug] Storage Crate not closing GUI when broken

### ISSUE THREAD

**Issue by Matryoshika** [BluSunrize/ImmersiveEngineering#603]
IE Version: 0.5.4
As the crates' GUI does not close when the crate is mined, it is possible to remove items after the crate is mined by another player and/or blockbreaker.
The original items still exist in the crate when placed back down, meaning that you can duplicate items using this block.

Simple fix: Force the GUI to close when the block is mined.

**Comment by mindforger** [comment]
will this really help? is `isUseableByPlayer` called every tick or on every interaction? would an invalidation/forced close of all depending inventorys in a blockbreak event handler be the smarter solution? Can your crate be moved with the dolly from extra utilities? Should also be checked imho :)
i am refering to the alreay opened GUI as @Matryoshika stated

**Comment by BluSunrize** [comment]
Yes. It is called every tick. onUpdate on the EntityPlayer does so. This is how vanilla GUIs handle closing ;)

**Comment by mindforger** [comment]
uh okay i may be spoiled by programming bukkit plugins far ago too much :P those were also sometimes a bitch, especially when dealing with mods

**Comment by BluSunrize** [comment]
EntityPlayer.class, line 329

>if (!this.worldObj.isRemote && this.openContainer != null && !ForgeHooks.canInteractWith(this, >this.openContainer))
>        {
>            this.closeScreen();
>            this.openContainer = this.inventoryContainer;
>        }

I was very confused by it myself. Took me a good time to find it xD
