### ISSUE TITLE
[Suggestion] Mouse sensitivity setting for the railgun scope

### ISSUE THREAD

**Issue by EvergreenSystems** [BluSunrize/ImmersiveEngineering#6034]
### Explain your idea

Another quality-of-life suggestion: the ability to tone down mouse sensitivity for when you are scoped in while using a railgun. Especially at max magnification, it can be hard to precisely aim (especially if you are like me and have spasticity issues, I can only use about half of the scopes magnification as it is right now). Having an option in the client config to tune the mouses sensitivity, or the option to do so in the engineers workbench like you can with ear defenders, would be fantastic.
Thank you for the amazing mod! :)

**Comment by BluSunrize** [comment]
Unforunately not an easy way for us to do that, see here:
#5836 

Closing this as duplicate ^^
