### ISSUE TITLE
Distant Horizons + Shaders Invalid framebuffer operation every frame

### ISSUE THREAD

**Issue by Hastagaspatcho** [BluSunrize/ImmersiveEngineering#6037]
### Minecraft Version

1.20.1

### Immersive Engineering Version

1.20.1-10.1.0-171

### Expected Behavior

No framebuffer errors when using these mods together and resizing windows.

### Actual Behavior

Upon resizing the Minecraft window while in a world it continuously spams the console with `OpenGL debug message: id=1286, source=API, type=ERROR, severity=HIGH,` every single frame until Minecraft is closed. Not sure if there's any other side effects but I assume considering the error type there's at minimum some visual bug somewhere

### Steps to reproduce

1. Install minecraft 1.20.1
- Forge 47.3.0 (or NeoForge 47.1.106)
- Distant Horizions 2.1.2-a
- Embedddium 0.3.29+ mc 1.20.1
- Embeddium++ 1.2.13
- Immersive engineering 1.20.1-10.1.0-171
- Oculus 1.7.0
- Complementary Unbound r5.2.2 shader

2. Launch minecraft.
3. Start or create a world.
4. Enable shader.
5. Resize window
6. Enjoy console spam/gigabyte sized log files
7. Relaunch any amount of times and continue to create invalid framebuffer operations in the logs

### Debug Crash Log

https://pastebin.com/F0dzUV9A

**Comment by BluSunrize** [comment]
Shaders are not supported!

**Comment by Hastagaspatcho** [comment]
Solved it myself in case someone comes across this in the future.
Set the stencilBufferEnabled = false in immersiveengineering-client.toml

**Comment by muddykat-tech** [comment]
> Solved it myself in case someone comes across this in the future. Set the stencilBufferEnabled = false in immersiveengineering-client.toml

Using Distant Horizons 2.3.0-b-1.20.1 and IE standalone also causes this issue; The fix you mentioned still works.
