### ISSUE TITLE
Potential Hydraulicraft Hemp Trolley issue

### ISSUE THREAD

**Issue by 1skandar** [BluSunrize/ImmersiveEngineering#604]
Not sure if this is intended or not, but I figured I'd ask.

Ok, the way I harvest hemp manually is to break the top part and leave the bottom part to regrow. This seems to be intended behavior given how long it takes the hemp plant to mature from a seed and how quickly it regrows the top bit when it is broken. 

If that is the intended mechanic the Hydraulicraft hemp trolley is doing things wrong as  it breaks both the top and bottom bits, and then replants. This takes 3 actions, each with a reset afterward. This is slow and means that a hemp farm produces a woeful amount of seeds and hemp versus a wheat farm producing wheat and seeds. 

In my opinion the hemp trolley should mimic sugar cane and only break the top bit. This means one action and a return versus three and no replanting which means more seeds being output which should raise the return high enough to make it viable.

**Comment by mindforger** [comment]
imho it is relevant what you want to achive, if you neet fibers only, harvesting the top part is enough
but if you want to have a decend seed oil production it would be better to completeley harvest the plant as the top part never yields any seeds to squeeze

**Comment by 1skandar** [comment]
Um, you'd be wrong. The top part does indeed produce seeds. From what I can tell, both the top part and the bottom part yield 1 seed each when broken.

**Comment by mindforger** [comment]
huh O_o thats kinda new when did that change?

**Comment by 1skandar** [comment]
It's been that way since at least 0.5.4. Breaking the top part of the plant seems to only set it back to 50% maturtity, which means the tops regrow much, much faster than the entire plant, which means just running through and breaking the top bits can get you a ton of seeds if you do it manually. Or, you know, shooting, say, a Botania mana burst that breaks blocks. no replanting needed, produces a ton of seeds in a hurry.

**Comment by BluSunrize** [comment]
The behaviour of the trolley is intentional. I wrote it how I did with good reason.
