### ISSUE TITLE
[Suggestion] Immersive Engineering - Mekanism combination for energy

### ISSUE THREAD

**Issue by NewAgeSoldier** [BluSunrize/ImmersiveEngineering#6041]
### Explain your idea

Mekanism holds the power to Fissile Reactors, there used to be an addon to IE for 1.12.2 that has turbines, this is unfortunately when Mekanism was just starting to become big and had not yet reached the levels of Fissile Reactions. Which is why I would like to suggest a turbine that can allow Mekanism and Immersive Engineering combined power generation.

It feels weird suggesting this, mainly because Immersive Engineering and Create is already doing things really well together from the get go, I found that one a bit weird

**Comment by BluSunrize** [comment]
No plans to add this, sorry.
