### ISSUE TITLE
Charging Station crash

### ISSUE THREAD

**Issue by anakinblood** [BluSunrize/ImmersiveEngineering#6045]
### Minecraft Version

1.20.1

### Immersive Engineering Version

10.1.0-171 (I'm not too confident this is right)

### How did it happen?

I'm looking at the CurseForge page and now I'm a little confused, the 1.20.1 forge version is just gone. Anyway as I said in the title the Charging Station crashed my game, putting the railgun into the Charging Station causes the crash I've had.

### Crash Log

https://pastebin.com/Y4JGRN88

**Comment by mindforger** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/5784
i suppose

i think remedy was using embeddium

**Comment by anakinblood** [comment]
Embeddium just causes my game to not launch, so no luck there

**Comment by mindforger** [comment]
thats unfortunate, maybe you find another solution or have to play without this kind of render optimization mods

**Comment by malte0811** [comment]
This one is definitely Rubidiums fault.

**Comment by anakinblood** [comment]
Removing Rubidium worked, thanks.
