### ISSUE TITLE
Cable render

### ISSUE THREAD

**Issue by glougloudu77** [BluSunrize/ImmersiveEngineering#6049]
### Minecraft Version

1.18.2

### Immersive Engineering Version

1.18.2-8.4.0-161

### Expected Behavior

![2024-09-12_17 53 34](https://github.com/user-attachments/assets/a2cce5fc-9700-45ab-a204-14389d5df0da)

### Actual Behavior

I set the max cable length to 128 and the middle is not displayed as shown in the screenshot I attached 
I don't have any mods like optifine or rubidium installed

**Comment by malte0811** [comment]
1.18.2 is no longer supported, and if it's the bug I'm thinking of, this is fixed in 1.20.4 and above.
