### ISSUE TITLE
[question, clarification] Excavator Minetweaker when will it update?

### ISSUE THREAD

**Issue by mindforger** [BluSunrize/ImmersiveEngineering#605]
So we decided to go full force into the minetweaker area with the excavator and replace all mineral configs with more sophisticated ones that never have empty shovels, instead outputting ore related junk you will have to deal with

something like "Dirty Quartzite" results in 10% Netherquartz, 5% Certus, 50% Sand, 25% Gravel, 10% Dirt with a deposit of 50000 at a runspeed for calculated 2 RT days straight

but we already HAVE a world ported from 0.5.4 ... is there a way to let the mineral deposit calculator recalculate and reset the depletions?

if no, i know now where i find both entrys in the nbt storage of the world, can i just remove them and the mod recalculates them on reboot?

**Comment by BluSunrize** [comment]
You will have lost veins from before 0.6 anyway. In 0.5.4 the calculation was entirely different /and/ veins were not cached. Now, in 0.6 they are calculated once upon request and then cached to NBT to make them persist even if addon mods are installed that might change the order of minerals.

0.5.4 veins are effectively gone, you will need to find new ones. Depletion of chunsk persisted however, this depletion can be reset with the relevant commands

**Comment by Nagapito** [comment]
On a side note, I would suggest adding to MineTweaker support methods to change the power consummation, speed and general fail chance of an Excavator, so this options could be tweaked in Infinity Expert mode without affecting Normal mode, for example

**Comment by mindforger** [comment]
everything you want is already in the config, speed in rad/tick, consumption and the general fail chance is defined by the vein ... 
but i still don't get how this is used
you have config-fail and vein-fail .. will vein-fail override config-fail or will on top of vein-fail a chance of config-fail occur?

**Comment by BluSunrize** [comment]
They run separately. The fail in the config is a global fail chance, the vein one is specific to that vein. only if both check out it'll fill the bucket.
