### ISSUE TITLE
[Suggestion] Forge port

### ISSUE THREAD

**Issue by Filippide8864** [BluSunrize/ImmersiveEngineering#6050]
### Explain your idea

Would it be possible to create the version for forge 1.20.1?
If possible please do it I would need it for my industrial server.

**Comment by mindforger** [comment]
you should also search for closed issues too, this has been denied severals times now :)

**Comment by Filippide8864** [comment]
Why don't you want to bring it to forge?

**Comment by mindforger** [comment]
please search the other issues for explanation, there is plenty

and close this one, it is unneccesary work for the dev to respond the same again and again (PS: i am not a dev)
