### ISSUE TITLE
Disabled pipe connections reset on server restart

### ISSUE THREAD

**Issue by angelnc1989** [BluSunrize/ImmersiveEngineering#606]
I noticed today, that the pipe connections I disabled with the hammer reset on every server restart.
Not sure if it's just visual.

**Comment by BluSunrize** [comment]
See here:
https://github.com/BluSunrize/ImmersiveEngineering/issues/569#issuecomment-153145915

And I /think/ I might have fixed that with some other bug in that issue.

**Comment by BluSunrize** [comment]
Closed unless bug reappears?
