### ISSUE TITLE
Chunk corrupted when adding precision scope to revolver

### ISSUE THREAD

**Issue by threadproc** [BluSunrize/ImmersiveEngineering#6067]
### Minecraft Version

1.20.1

### Immersive Engineering Version

11.6.1-181 (git)

### How did it happen?

If you place a revolver in a workbench, and add a bayonet and then a precision scope, the client is immediately disconnected with a packet decoding error (see the gist). Upon rejoining, the chunk cannot be loaded by the server successfully, giving errors in all entities in the chunk, and stating that the chunk is misaligned.

Originally encountered this with the latest build from Jenkins with several other mods, but I have recreated it using the 1.21.1 git branch running in debug mode.

### Crash Log

https://gist.github.com/threadproc/179b2a07ea6a75d212eb884c91168144

**Comment by malte0811** [comment]
3cd7fd39db0168a5e4b39c82ea2175c0190ab3c0
