### ISSUE TITLE
Item Router configuration not persisted after restart

### ISSUE THREAD

**Issue by threadproc** [BluSunrize/ImmersiveEngineering#6069]
### Minecraft Version

1.20.1

### Immersive Engineering Version

11.6.1-181 (git)

### Expected Behavior

Item Routers should maintain their filters when the server is restarted or the chunks are reloaded

### Actual Behavior

Item Routers have blank config after chunk reload

### Steps to reproduce

1. Place item router
2. set filters
3. restart server

### Debug Crash Log

no logs

**Comment by malte0811** [comment]
31a3f9af9746d344a52dcd8b0ae4d2aba39a033d
