### ISSUE TITLE
[Suggestion] Update 1.21.x and some features.

### ISSUE THREAD

**Issue by NumpaMC** [BluSunrize/ImmersiveEngineering#6071]
### Explain your idea
1. LV and MV wires will have their protective layer peeled off after a while and we will get an electric shock.
2. Battery life and performance depend on environment
3. 3.Nuclear reactor, creating a furnace that can use nuclear energy to create energy.
4. Solar energy, using solar energy to generate electricity.
5. Can update 1.21.x pls

**Comment by BluSunrize** [comment]
No to all your suggestions.

1.21 is in progress, just be patient.

**Comment by RIExJonny** [comment]
thanks for all the work you  have done.. I can not  wait for 1.21 as i know you do have IRL priority's as work and family and stuff mostlily and may not always have time to work on this but wanted to post this also in here for others to see and know that as well..
