### ISSUE TITLE
[Suggestion] Ore vein searching (read description)

### ISSUE THREAD

**Issue by kienerxyzzy** [BluSunrize/ImmersiveEngineering#6073]
### Explain your idea

I'd like a feature where you could search up a mineral vein based on its minerals.
I searched through the manual three times and I still haven't known if you can excavate mekanism osmium. (answer that if possible)

**Comment by mindforger** [comment]
All veins should be listed, if not you might need to add them

**Comment by kienerxyzzy** [comment]
> All veins should be listed, if not you might need to add them

I know that part of the manual, but I search through all of the ore veins but I still don't trust myself
Also: How do you add ore veins?

**Comment by TeamSpen210** [comment]
Ore veins are just [recipes](https://github.com/BluSunrize/ImmersiveEngineering/tree/9420177bab085c1475f3a3e30d6d7787dcab3fc1/src/generated/resources/data/immersiveengineering/recipes/mineral), so you can use a datapack to add more.

**Comment by kienerxyzzy** [comment]
how do I place the vein tho?
(i'm in creative and I don't see it's name)

**Comment by kienerxyzzy** [comment]
also it is ok to add via kubejs?

**Comment by voidsong-dragonfly** [comment]
> how do I place the vein tho?
(i'm in creative and I don't see it's name)

The `/ie mineral put` command can be used to place veins in Creative. You'll need to go off of the resourcelocation and not the vein's 'name' as it is localized.

> also it is ok to add via kubejs?

You _can_ add veins via KubeJS, but seeing as how KubeJS has broken things with IE many times before, we do not recommend KubeJS. The recommendation is to use _datapacks_, of which a tutorial can be found [here](https://minecraft.wiki/w/Tutorials/Creating_a_data_pack) on the Minecraft Wiki.

**Comment by BluSunrize** [comment]
I'll close this, since the question was answered.

Future discussion is better placed in our discord:
https://discord.com/invite/SnUp97WUrN
