### ISSUE TITLE
Villager Errors

### ISSUE THREAD

**Issue by kienerxyzzy** [BluSunrize/ImmersiveEngineering#6074]
### Minecraft Version

1.20.1

### Immersive Engineering Version

10.1.0-171

### Expected Behavior

Look in [ACTUAL BEHAVIOR] section

### Actual Behavior

![image](https://github.com/user-attachments/assets/3537b1a8-b6e3-47d8-8cf4-6f6e07b43cf4)
I don't have air to trade with...

### Steps to reproduce

I cured a zombie villager and now it's trading air for emeralds

### Debug Crash Log

none

**Comment by kienerxyzzy** [comment]
The other trade was 1 emerald -> 1 screwdriver and after getting 10 screwdrivers the villager offered another air to emerals trade
this is so broken

**Comment by BluSunrize** [comment]
You have another mod in your pack that breaks tag loading. Not much we can do about that.

**Comment by kienerxyzzy** [comment]
> You have another mod in your pack that breaks tag loading. Not much we can do about that.

Thanks for the feedback, but what mods have been confirmed to break tag loading? (My modpack has mekanism and AE2 in it, so I just want to know for the next time I make an IE modpack)
