### ISSUE TITLE
[Question]: Recipe Modification

### ISSUE THREAD

**Issue by kienerxyzzy** [BluSunrize/ImmersiveEngineering#6076]
### Explain your idea

After #6073 and #6074 I decided to create a new modpack. This time I had Thermal in it, so I wanted to change the mechanical component recipes. The shaped recipes were easy to change, but the engineer's workbench recipe did not get added by KubeJS.

How do I modify recipes?

**Comment by BluSunrize** [comment]
By using a **data pack**, the vanilla Minecraft mechanic for custom recipes:

You can find information on how to make and structure such a datapack here:
https://minecraft.wiki/w/Data_pack

And you can find examples of what IE's own recipe files look like here:
https://github.com/BluSunrize/ImmersiveEngineering/tree/1.20.4/src/generated/resources/data/immersiveengineering/recipes

This is the only way of recipe modification we actually endorse, KubeJS and Craftweaker have proven too volatile in the past.
