### ISSUE TITLE
[Suggestion]  Underground Cables to build power grids

### ISSUE THREAD

**Issue by MystikMaster** [BluSunrize/ImmersiveEngineering#6080]
### Explain your idea

First of all I would like to thank the producers of this mod for their great work!

I've been using your mod for a few years now, but in a different way.

I have supplied my entire city with electricity (even street lighting) and use self-built power stations and control cabinets. 
So far I have partly used cables, which are available in your mod, but also Mekanism cables. The big disadvantage is that Mekanism cables are very unrealistic as they store electricity. I would like cables that can be laid underground and only transfer electricity like normal LV, MV, HV cables. This would enable a large new division to use this mod. You can create large power grids and transfer electricity over larger distances.
I work for a power grid operator, which is why your mod really inspired me to power my entire map!

I am using 1.18.2 Forge at the moment.
I hope I was able to inspire you with my idea!

Here are a few examples:

Power Station:
<img width="1229" alt="image" src="https://github.com/user-attachments/assets/f4e76866-a3f9-4b14-b753-39c3510decea">

Power Cabinet:
<img width="1117" alt="image" src="https://github.com/user-attachments/assets/95fa587d-3b9e-451f-87bd-fc47ec84e503">

Electricity substation:
<img width="1148" alt="image" src="https://github.com/user-attachments/assets/9ef913f3-c076-49ed-a2c7-61a4d96362ff">

A small part of my Map at night with Street Lights:
<img width="1163" alt="image" src="https://github.com/user-attachments/assets/4eb9b8e3-739d-49ca-a473-4326c315977a">

Power Cabinet:
<img width="874" alt="image" src="https://github.com/user-attachments/assets/d5117ad8-a2f2-4e45-ae5f-0c9475217db8">

Street Lights:
<img width="1043" alt="image" src="https://github.com/user-attachments/assets/fe858616-0efd-464c-bda7-609ca0c1b865">

**Comment by BluSunrize** [comment]
You can already lay IE wires underground. Just dig a tunnel for them.

We are never adding block-based energy conduits in any form. IE is *defined* by its wires, I see no reason to ever offer an alternative to them =)
