### ISSUE TITLE
[Suggestion] ... Can I upload Language-update here?

### ISSUE THREAD

**Issue by willis1030** [BluSunrize/ImmersiveEngineering#6094]
### Explain your idea

Can I upload Language-update here? because I am not a collaborator, I can't use Pull requests.
version: ImmersiveEngineering-1.21.1-12.0.0-182

[zh_tw.json](https://github.com/user-attachments/files/17586323/zh_tw.json)
[manual-1.21.1-zh_tw.zip](https://github.com/user-attachments/files/17586325/manual-1.21.1-zh_tw.zip)

**Comment by BluSunrize** [comment]
You don't need to be a colaborator to submit pullrequests, you just have to fork the repository.

We only accept translations via PR.
