### ISSUE TITLE
Fruid router problem

### ISSUE THREAD

**Issue by willis1030** [BluSunrize/ImmersiveEngineering#6097]
### Minecraft Version

1.21.1

### Immersive Engineering Version

ImmersiveEngineering-1.21.1-12.0.0-182

### Expected Behavior

Fluid Router 

### Actual Behavior

Fluid Router can't set liquids. It not work!

### Steps to reproduce

![image](https://github.com/user-attachments/assets/799e6ea8-71e3-4494-bb8d-d381420fb1bc)

### Debug Crash Log

none

**Comment by malte0811** [comment]
![2024-11-02_11 31 03](https://github.com/user-attachments/assets/65addb24-f8b4-4dec-845c-6852102450c5)

Unable to reproduce. The reason we ask for a debug crash (including instructions on generating it) is that it includes a full modlist, which makes it much easier to track down potential cross-mod issues.
