### ISSUE TITLE
[Suggestion] Ability to create a temporarily water source with water outlet

### ISSUE THREAD

**Issue by therealhoodboy** [BluSunrize/ImmersiveEngineering#6099]
### Explain your idea

In our world I would like to create flowing water by pumping it from elswere without the water outlet creating many fixed water sources. 
Imaging living somewhere in the mountains and being dependent on pumps constantly transporting water to your height to provide your town/ city with nice rivers or waterfalls. 
You could disable the rivers for (fictional) maintainance work or cleaning the river beds. 
Would this be a possible feature to implement in the 1.20.1 version of IE?
This feature would maybe also enable toggleable waterwheels and would add furthermore a cosmetic enhancement. 
I would love to hear you opinion

**Comment by BluSunrize** [comment]
Water sources in Minecraft are infinite. There is no point in pumping "flowing water", not to mention it would be bad for performance.
And no, we are not doing new features on 1.20.1.
