### ISSUE TITLE
MV wire connector crash

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#61]
When connecting an MV connector to another in a particular way, i have managed to consistently produce a rendering crash.
When i attempt to connect the connector outlined in blue to ~~the one outlined in red, I consistently get a crash~~ After further testing it appears after establishing about 5 connections, the next one induces the crash
![image](https://cloud.githubusercontent.com/assets/3110986/8142981/3be6d69c-114a-11e5-91f5-2b1909eab1c2.png)

crashlog here: https://www.dropbox.com/s/9maqwrif1s442de/crashlog.log?dl=0.

after restarting the client I can load the world without further  issue.

**Comment by BluSunrize** [comment]
I /think/ I've fixed that one already. We'll have to see if it persists after public release.

**Comment by theunkn0wn1** [comment]
One way to find out!

**Comment by BluSunrize** [comment]
Reopen if it's found in the public release
