### ISSUE TITLE
[Request] Nightly Build

### ISSUE THREAD

**Issue by webmilio** [BluSunrize/ImmersiveEngineering#610]
Hello there!

I'd like to suggest a Nightly Build server. It would help people who want to help but don't know how to build. Since this github does not provide help on how to build IE, it can be difficult for them to build the mod themselves.

Webmilio.

**Comment by theunkn0wn1** [comment]
As @BluSunrize wrote:
> If you can figure out the dependencies on your own, you're also qualified enough to give me decent bug reports and code assistance


Blu does not want just anyone readily building his mod for historical reasons, so I doubt he would approve of this. See #593. For the same reason he provides no assistance how to build the mod from this repository, I find it highly unlikely he would approve of the compiled pre-release versions being public.

**Comment by cobra** [comment]
These versions tend to have really nasty bugs (stuff like crashing on each world load), debug code, dirty hacks, unfinished stuff, untested changes, etc. Sometimes, despite constantly pulling in and observing changes, I had problems getting it to launch at all (without some of the mods supported, but not required). Yes, this can happen in other peoples' jenkins instances as well, but then you have to deal with certain people who don't understand this and the errors they encounter, which is time-consuming. I can't speak for BluSunrize, but the time between the next releases probably won't get as long as it did for 0.5.4 → 0.6.0.
Also, the only thing needed for a build is figuring out the dependencies from the error messages (protip: look at the mod compat modules before to avoid a whole lot of them) and getting their deobf jars either into gradle (very simple once you know the absolute basics) or the java IDE of your choice. There's nothing else, no overly specific versions, no other config or environment needed.

**Comment by webmilio** [comment]
I already have my own builds, the thing is super easy, I just messed up one jar at first. I'm saying this for myself, I'm only saying this as a suggestion for other people who may not have the same knowledge as you, me and other people who build themselves do.

**Comment by BluSunrize** [comment]
Which is the point. The people without the knowledge wont be able to help.

**Comment by webmilio** [comment]
I see your point. Thank you for your clear and quick answers!
