### ISSUE TITLE
1.21.1 Neofroge Cash on world load

### ISSUE THREAD

**Issue by Zelioth** [BluSunrize/ImmersiveEngineering#6107]
### Minecraft Version

1.21.1

### Immersive Engineering Version

12.0.0-180

### How did it happen?

installing mods, Friends United 2.1 mod pack. Crash when world load. 

### Crash Log

https://gist.github.com/Zelioth/a7afd470425bea5dc2d95e9a139a7d5f

**Comment by malte0811** [comment]
Already fixed for the next release. This is caused by some other mod shipping outdated (cloche?) recipes, and IEs codecs not handling that properly.
