### ISSUE TITLE
[required] unlimited energy source

### ISSUE THREAD

**Issue by anar4732** [BluSunrize/ImmersiveEngineering#611]
required:
unlimited energy source for creative mode

**Comment by mindforger** [comment]
make that an [request] to not sound like a know-it-better-than-the-dev-douche ;)

**Comment by BluSunrize** [comment]
And I'd argue that we have other mods for that, really .-.

**Comment by anar4732** [comment]
@BluSunrize @mindforger 

me the English language sucks
write more understandable ?

I know this is possible with other modes of infinite energy
but it would be better if you add this mode

**Comment by angelnc1989** [comment]
I'm running a pack, where I don't have another mod, that adds a creative infinite energy source.
It would be really helpful for testing builds.
