### ISSUE TITLE
[Suggestion] Add Treated Wood Tag to 1.21+

### ISSUE THREAD

**Issue by wendall911** [BluSunrize/ImmersiveEngineering#6113]
### Explain your idea

treated_wood tag existed in prior versions of IE, it doesn't appear it made it back into 1.21.1. 

Reference:
https://github.com/BluSunrize/ImmersiveEngineering/blob/1.20.1/src/generated/resources/data/forge/tags/items/treated_wood.json

**Comment by ffuentesm** [comment]
They exist, it just moved from the Forge to the IE family tag. 
![image](https://github.com/user-attachments/assets/e17e862d-8ae3-4332-be84-6122c9d17d36)

**Comment by wendall911** [comment]
Oh, very sorry, no idea how I missed this!
