### ISSUE TITLE
[Question] Multiblock Additional Components?

### ISSUE THREAD

**Issue by kienerxyzzy** [BluSunrize/ImmersiveEngineering#6115]
### Explain your idea

How do I include other mod's blocks in IE's multiblocks?
(Ex: Create pipe instead of IE pipe in refinery)
Also, how do I change the block that appears after breaking the multiblock?
(Ex: When I build a arc furnace using Mekanism steel blocks, then destroy it, it returns IE steel blocks)

**Comment by BluSunrize** [comment]
Multiblock templates are defined in structure files.
You can theoretically override them with a datapack, but we do not offer explicit support for that.
