### ISSUE TITLE
disconnection with table

### ISSUE THREAD

**Issue by VaporeonScripts** [BluSunrize/ImmersiveEngineering#6118]
### Minecraft Version

1.21.1

### Immersive Engineering Version

latest

### Expected Behavior

to not crash

### Actual Behavior

crash

### Steps to reproduce

install the mod

### Debug Crash Log

https://mclo.gs/W7GpZm3

**Comment by malte0811** [comment]
TeamMidnightDust/VisualOverhaul#86 and #6082
