### ISSUE TITLE
Compatibility issue with Forestry?

### ISSUE THREAD

**Issue by Xiaminou** [BluSunrize/ImmersiveEngineering#612]
Crash on startup in my modpack.

Forge: 1492
Immersive Engineering: 0.6.0
Forestry: 3.6.11.2

crash log: http://pastebin.com/rM36LzPU

**Comment by BluSunrize** [comment]
Has been reported multiple time, check the past issues. Update your forestry, disable Forestry compat in the IE config or wait for IE 0.6.1

**Comment by Xiaminou** [comment]
oh right, my bad, thank you for the quick answer
