### ISSUE TITLE
Crash on Startup With Dye Depot

### ISSUE THREAD

**Issue by CraftyZombie** [BluSunrize/ImmersiveEngineering#6132]
### Minecraft Version

1.20.1

### Immersive Engineering Version

10.1.0-171

### How did it happen?

Forge 47.3.12

Kind of weird situation. The mod crashes on startup with Dye Depot, but I personally encountered a version of this crash after the original issue was suppressed by other mods.
Here are the wacky crashes I first experienced: https://gist.github.com/CraftyZombie/eda6a76e6adef07bd26362b36f8fc031
The normal crash and logs are in the Crash Log section.

This is most likely Dye Depot's fault, but I thought I'd put this here to keep track anyway.

https://github.com/N1nn1/dye_depot/issues/50

### Crash Log

https://gist.github.com/CraftyZombie/e3f3a5d3eddc4ef274e550902536b6ec

**Comment by BluSunrize** [comment]
Sorry, but I refuse to account for mods that modify a core game enum that was not meant to be extendable.

**Comment by CraftyZombie** [comment]
No worries. Like I said, I assumed this would be on them.
