### ISSUE TITLE
[Suggestion] ... add 1.20.1 compatibility

### ISSUE THREAD

**Issue by maygan36** [BluSunrize/ImmersiveEngineering#6135]
### Explain your idea

I created 2 1.20.1 modpacks and the only thing messing from the puzzles piece is the 1.20.1 forge  for both immersive engineering and petroleum. i cant live without these beasts

**Comment by CraftyZombie** [comment]
Immersive Engineering is available on Forge 1.20.1, just use the jar marked as NeoForge-compatible.
