### ISSUE TITLE
windmill and waterwheel dissapers

### ISSUE THREAD

**Issue by Eimonte** [BluSunrize/ImmersiveEngineering#6136]
### Minecraft Version

1.20.1

### Immersive Engineering Version

1.20.1-10.1.0-171

### Expected Behavior

when i turn on the shaders i see
![Screenshot 2024-12-27 193533](https://github.com/user-attachments/assets/bddf5426-95d2-4762-8d45-dc3ff5e0d8ef)
this

### Actual Behavior

and when i turn the shaders off i see this
![Screenshot 2024-12-27 193602](https://github.com/user-attachments/assets/6745f1ee-6e96-442e-ba9e-f52f8cd53a9c)

### Steps to reproduce

i started with shaders it did not show up then i turn then off i started to see them

### Debug Crash Log

.

**Comment by BluSunrize** [comment]
Shaders are not supported.
