### ISSUE TITLE
Tank Updating

### ISSUE THREAD

**Issue by rupeezfodayz99** [BluSunrize/ImmersiveEngineering#615]
When i hold a bucket or bottle in my hand and look at the tank, the number doesnt update unless i put more fluid in. even if i switch items, or come back later, it doesnt update.

**Comment by James-T-Oudvoure** [comment]
I've been having this same problem too, I've actually mentioned it in one of my other reports before. If it helps solve it, if you save and quit and then re-enter the world, the number updates.

**Comment by cobra** [comment]
Only when draining it by auto-outputting. Filling or pulling fluids with things like ExU transfer nodes or Thermal Dynamics fluidcuts does update the number shown. Will look into it.

**Comment by BluSunrize** [comment]
probably missing a markDirty()
I'll leave this to you if you don't mind, @cobra

**Comment by cobra** [comment]
Guess what I just inserted :D
