### ISSUE TITLE
[Suggestion] Redstone-controlled relay/contactor

### ISSUE THREAD

**Issue by Sukasa** [BluSunrize/ImmersiveEngineering#617]
Small suggestion; an object similar to the breaker but instead of emitting a redstone signal when on, requires a redstone signal to turn on.  Would be a nice way to automatically manage circuits/etc.  "Relay" for LV, "Contactor" for MV/HV to reflect the relative interrupting capacities of each.

**Comment by theunkn0wn1** [comment]
+1

We, for those of us whom automate all the things, the existing breaker is kinda pointless IMHO.

Could we get a variant of the existing breaker that responds to Redstone rather than emit it?

**Comment by XFactHD** [comment]
+1
But the block would have to look like a real electronic relay, somewhat like the relays from electrical age.

**Comment by mindforger** [comment]
i support this idea! http://img.directindustry.de/images_di/photo-g/elektromechanisches-relais-leistung-leiterplatte-dpdt-65144-2703747.jpg

**Comment by BluSunrize** [comment]
Old suggestions is old:

https://github.com/BluSunrize/ImmersiveEngineering/issues/340

And as I said before: Talk to Damien. I don't art.

**Comment by mindforger** [comment]
well that was the idea of a HV hand controlled switchset but yes you are right in general :D

**Comment by theunkn0wn1** [comment]
Yeah... It appears as if you forgot about that and the other older yet
still open issues. Why can't we just use the existing breaker texture with
minor alterations as a placeholder until we get s proper texture for it?

**Comment by BluSunrize** [comment]
I didn't forget. There are just quite a few thinhs to do on this project, as you have surely noticed. xD

**Comment by theunkn0wn1** [comment]
Yeah, there have been quite a few big changes recently and the original
request was low priority. It was just the lack of any posts upon the
subject since August led me to the false impression :/

By `project `you referring to IE in general right?

I do hope this is the next thing you add, it is the only remaining self
evident hole in the ability to automate IE that I can currently see

**Comment by BluSunrize** [comment]
redstone controlled breaker switch is a thing now =)
