### ISSUE TITLE
Client Crash with InvTweaks and Crusher Recipes.

### ISSUE THREAD

**Issue by Bunsan** [BluSunrize/ImmersiveEngineering#619]
So this is a very bizarre crash. I'm replicating this with forestry, but I experienced it with other mods as well. This is specifically caused by InvTweaks (inventorytweaks-1.59-dev-152), but the stacktrace makes no sense.

To replicate load InvTweaks in an instance with: 
IE 0.6.0 
CCC-1.7.10-1.0.7.47-universal
NEI-1.7.10-1.0.5.111-universal
Forestry_1.7.10-4.1.1.46

Use either right click or "U" on Forestery Tin Ingot or Bronze Ingot. All other items seem fine. The best guess I have is that certain metal and alloy name trigger that a crusher recipe should be made, but if IE, the mod itself or another mod don't introduce a dust form of that metal/alloy it crashes. Testing showed that for TFC without other mods: Bronze, Brass (both listed as common alloys and having recipes in IERecipes.java) and Tin(in excavator code) caused the client to crash. However in combination with mods that do have dusts for these metal/alloys the client does not crash. Why this only occurs with InvTweaks installed in client is beyond me.

The crash reports were generated by hitting U on Forestry Tin Ingot.
Forge 1448 http://pastebin.com/fTGUqXZR
Forge 1541 http://pastebin.com/CwhENSAV

**Comment by BluSunrize** [comment]
Known and fixed already, see here:
https://github.com/BluSunrize/ImmersiveEngineering/issues/601

**Comment by Bunsan** [comment]
Apologies. Didn't realize it was that crash as I could only replicate with Inv Tweaks present.

**Comment by BluSunrize** [comment]
It's fine =P

The issue is the same, even if the cause might be different, so the fix should work for both
