### ISSUE TITLE
Conveyer belts some time don't transfer items properly!

### ISSUE THREAD

**Issue by QBedPanda** [BluSunrize/ImmersiveEngineering#620]
Items get stuck for no reason on the conveyers or glitch through them and fall. Happends mostly when items go uphill.

**Comment by mindforger** [comment]
double check if they are rotated the right way(even try loggin out and in again), there is a known bug currently that rotating is desynced

on the other hand i had this issue on a pretty much older release too but did not noticed it since then, will re-evaluate this evening .. i suppose other mod interaction probably

also remove fastcraft from your mods if present and also make sure you are you are not using kcauldron as server or any other mods that interfere with dropped items (f.E. there are optimizing mods that change the merge radius of items that could probably cause this issue)

**Comment by QBedPanda** [comment]
It happends sometimes but its not that big of a deal. Anyways thanks mindforger.

**Comment by BluSunrize** [comment]
As far as I am aware, @cobra fixed these desync issues, the next build should clear this up.

**Comment by QBedPanda** [comment]
Thanks for letting me know BluSunrize!

**Comment by cobra** [comment]
If breaking and replacing them in the correct direction without using the hammer helps, it's what I fixed. If it's a single conveyor in a long line that is doing weird stuff, check for redstone signals - these will stop them from transporting items (the animation isn't ever stopped).

**Comment by BluSunrize** [comment]
I can't stop the animation of textures, sadly.

**Comment by cobra** [comment]
Wouldn't registering a second, non-animated version of the belt texture and switching to that one help? (which would need a rerender…)

**Comment by BluSunrize** [comment]
yeah needs a rerender, and it wouldn't stop where it was =P

**Comment by mindforger** [comment]
but ... can't you access the information at which frame the animation currently is? 
you could temporarily store this info to make an texture offset on the stillstanding (oversized) non animated texture to make it stop where the animation was? 

By the way there is an tiny texture error with belts, the edge on both sides are both pointing downwards, where only the "incoming" side has to go downwards and the "going" side has to go upwards! 

warning: this is just an idea and has no knowledge substance as i am not familiar with rendering stuff at all :P

**Comment by BluSunrize** [comment]
IIcons do their animation without me contributing anything, so I literally have /no/ control over it xD

**Comment by mindforger** [comment]
uuhh i was misunderstanding the context, i thought the texture of the belt animation not the item on conveyor animation >_<
still, could you have a look at the conveyor belt textures or was this fixed anywhere between 0.5.4 and 0.6.x?

**Comment by BluSunrize** [comment]
I'll look into it later

**Comment by Sukasa** [comment]
Going to echo some similar issues I'm having - items are still falling through belts that are going upwards and/or getting stuck.  One thing I've noticed is that it *only* happens when an item is trying to go up an inclined belt, after it took at least one 90° turn before reaching that belt.

**Comment by Dreminon** [comment]
The belts where working fine for me till last update now anywhere they go uphill it just shoots them out straight under the belts. I have replaced the belt and all. still does not fix them.

**Comment by ProsperCraft** [comment]
I can confirm this is still a problem with 6.4, items are being dropped when the belt goes up.

**Comment by cobra** [comment]
I've used conveyor a lot and this has never happened to me. Could this be a cross-mod issue? Could you please post your mod lists? Please use gist or pastebin if they are longer than just a handful of lines.

**Comment by ProsperCraft** [comment]
Here is a download for the modpack if you want a testing environment
https://www.dropbox.com/sh/snk8f9pzasbgq4n/AACzY2dv4Ejrn-iUPcF6u056a?dl=1
this is a multimc instance.

Here is a modlist https://docs.google.com/spreadsheets/d/1zMP3m5yYTaV1fkRT8mQmtxzHVcBv3K7iKqqbOQi-1zE/edit?usp=sharing

**Comment by ProsperCraft** [comment]
Testers are not reporting that it is working after the world reset, will keep you updated.

**Comment by Joshi120** [comment]
I can confirm this is still a problem with 6.4, items are being dropped when the belt goes up.


Aye I have the same problem on the Revolution pack

**Comment by XFactHD** [comment]
Tell the modpack dev to update IE, 0.6.4 is goddamn old.

**Comment by mindforger** [comment]
@Joshi120 if you want to help, you can make a fresh new world, reproduce the issue with minimal setup and then remove one mod after another ... it is a cross mod issue which occurs very very rarely and is almost impossible to reproduce!

another related issue was solved during this time because the rotation of the belts was not synchronized to the clients, visually letting the items drop off the belt when they were stuck between 2 belts in different directions

**Comment by Joshi120** [comment]
i found the cause now  its a Clearlag issue so i guess nothing you can do something against :/

**Comment by mgwerner** [comment]
I am having this issue in Immersive Engineering v0.7.7, custom modpack, SMP, no Clearlag plugin.  I have tried laying without the hammer, with the hammer, logging out and in.  Items either drop off the belt when the hit an upward incline, or get glitched in a loop until I step up to the initial incline which allows the item to be picked up into inventory.  1.7.10 Forge 1558.

**Comment by mindforger** [comment]
Single or Multiplayer?
If Single, force a crash by holding F3 and C for at least 6 seconds to force a crash and attach the rashlog or post it via pastebin, there has to be some foreign culprit for sure :)

**Comment by mgwerner** [comment]
SMP - multiplayer.

**Comment by mindforger** [comment]
well :D time to write a crashme mod XD
