### ISSUE TITLE
Milo shader

### ISSUE THREAD

**Issue by xbony2** [BluSunrize/ImmersiveEngineering#622]
The Shader called "Miló" [in the code](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/items/ItemShader.java#L45) appears as "Milï¿½" in the game, which I assume is a bug.

Tested with 0.6.1.

**Comment by theunkn0wn1** [comment]
Can confirm this in build 018bb22
![image](https://cloud.githubusercontent.com/assets/3110986/11082594/7347b658-87db-11e5-8f01-8837c63ea566.png)


If i replace the accented 'o' with the English counterpart (without the accent) the bug does not manifest itself.

**Comment by BluSunrize** [comment]
Yes, duh, obviously changing it to another letter fixes it.
But it's an existing name and a clear reference, so that is not an option.
I'll fix this in due time, I blame java for compiling the damn files in windows default CP1252 ._.

**Comment by cobra** [comment]
It was broken on my linux box as well, but in a different way - yep, looks like java breaks something while compiling.

**Comment by BluSunrize** [comment]
java compiles on the default system formatting or whatever. And that happens to not like Unicode or ASCII characters =P

**Comment by cobra** [comment]
Your files aren't utf-8, they are ISO-8859 (at least `file`is telling me that). Looks like you somehow broke the encoding, I think we should check that in IRC.

**Comment by BluSunrize** [comment]
No they are system default. Which for me, on windows, is CP1252. I know how to fix it, I just need to do it.

**Comment by BluSunrize** [comment]
I fixed this btw, with this commit:

https://github.com/BluSunrize/ImmersiveEngineering/commit/00ecb6ba766a80ae792801b139f460d20800f16b

It uses the manual's spellchecking to fix itself ^^
