### ISSUE TITLE
Arc furnace not excepting from conveyor belts

### ISSUE THREAD

**Issue by James-T-Oudvoure** [BluSunrize/ImmersiveEngineering#623]
According to the engineer's manual, "Inputs and additives are inserted through the two hatches at the top of the structure, to the left and right of the electrodes."
This is my current setup:
![2015-11-09_19 52 08](https://cloud.githubusercontent.com/assets/14304823/11052201/a1f1fb32-871b-11e5-8230-e2d2c10cc792.png)
As you can tell, the iron ingots are not entering the furnace. I'm not sure if I'm doing this wrong or if this is a legitimate bug.

**Comment by malte0811** [comment]
Try placing hoppers on top of the hatches.
Conveyor belts only insert into the block in front of them, so the block above the hatch.

**Comment by James-T-Oudvoure** [comment]
Alright, it works now, thanks.

**Comment by rahangar** [comment]
By "it works now", do you mean with a hopper?  or did you somehow get the conveyor belt to work without a hopper?

**Comment by malte0811** [comment]
I asume he meant that it works with a hopper and a conveyor. But @cobra implemented a dropping conveyor belt some time ago, it should be in the newer versions of IE. Using that may be a bit nicer for the design.

**Comment by cobra** [comment]
You can even build loops with this to avoid items building up when the input is full. The dropping conveyor belt will try to insert the items on it into an inventory below and move them like a normal conveyor belt if inserting is not possible.
