### ISSUE TITLE
Dedicated server support lost?

### ISSUE THREAD

**Issue by LemADEC** [BluSunrize/ImmersiveEngineering#624]
After upgrading to 0.6.0, power no longer flow on our dedicated server while it works in single player.
I've updated to 0.6.1 and removed nearly all mods, issue is still reproduced with:
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
CoFHCore-[1.7.10]3.0.3-303.jar
ComputerCraft1.74.jar
gregtech-5.09.11.jar
ImmersiveEngineering-0.6.1.jar
industrialcraft-2-2.2.791-experimental.jar
Mantle-1.7.10-0.3.2b.jar

Here's a screenshot of my test setup:
- 3 watermills and a thermo connected to a capacitor
- a IC2 Geothermal connected to another capacitor
Both MV and LV connectors/wires show the issue.
Apparently, the Geothermal loose a bit of power on server boot (or chunkloading?), but both capacitors remains empty.
![image](https://cloud.githubusercontent.com/assets/4776032/11052188/282c8732-8756-11e5-9f38-830894da29d4.png)

**Comment by malte0811** [comment]
Have you set the capacitors to input mode (blue dot) on the faces you want to insert power into? If you did not, right click that side with an engineers hammer until it shows a blue dot.

**Comment by LemADEC** [comment]
There's a network desync when using the hammer:
- the first time you right click a face with the hammer, client isn't updated
- the second time, client receive the previous "1st update"
- the third time, client receive the "2nd update"
- etc.
If you place a block next to the capacitor to force a block update, then the side appears properly.

Now, if I force the block update to confirm blue/orange dot, I can make the network flow properly.

**Comment by mindforger** [comment]
try the newes 0.6.1 right out of the oven, should fix a lot of desync

**Comment by LemADEC** [comment]
I still see it with 0.6.1 in my full pack.
All 3 capacitors have the issue, looks like rendering issue client side since I can place a block anywhere to fix it.

**Comment by LemADEC** [comment]
Block update needs to be close by to refresh it.

**Comment by LemADEC** [comment]
Here's a screenshot of the wooden post issue:
![image](https://cloud.githubusercontent.com/assets/4776032/11060225/1294c2ce-879f-11e5-82d8-4e87487a772e.png)
I happens when hammering the wooden post in clockwise direction around it. Apparently, the position of the second 'extension' is miscalculated.

**Comment by cobra** [comment]
I tested the capacitors while investigating and fixing a lot of these rerender issues and it worked for me. Strange.

**Comment by cobra** [comment]
found and fixed. That was still fallout (hah!) from the great getTileEntityPurge. cc: @malte0811

**Comment by cobra** [comment]
I really can't reproduce this capacitor issue on my debug server, they are all updating immediately without any problem - and that is also true for all observing players, not only the one hitting it with the hammer. I can't see any problem in the code either, that should definitely not happen at all.

**Comment by LemADEC** [comment]
I had CoFH and ArsMagica2 installed along with IE on a Cauldron server with no plugins when reproducing it.

**Comment by cobra** [comment]
might be something with cauldron. Doesn't happen with the normal server.

**Comment by LemADEC** [comment]
I'm reproducing it on a Forge server (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) and the following mods:
1.7.10/[1.7.10]bspkrsCore-universal-6.16.jar
1.7.10/CodeChickenLib-1.7.10-1.1.3.138-universal.jar
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
CoFHCore-[1.7.10]3.0.3-303.jar
ComputerCraft1.74.jar
gregtech-5.09.11.jar
ImmersiveEngineering-0.6.1.jar
industrialcraft-2-2.2.791-experimental.jar
Mantle-1.7.10-0.3.2b.jar

**Comment by LemADEC** [comment]
Original issue can be reproduced with just forge-1.7.10-10.13.4.1558-1.7.10-universal.jar and ImmersiveEngineering-0.6.1.jar on a dedicated server, same mods on client side.

**Comment by mindforger** [comment]
@LemADEC which issues exactly, the "ghost poles" were indeed buged but cobra claimed the capacitors were not, do they still bug you out

**Comment by cobra** [comment]
That would be the capacitor issue, I'll try it. Good to know that it doesn't depend on other mods which potentially don't have deobf versions, that makes it rather easy to debug.

**Comment by cobra** [comment]
Interesting, I had to disable nearly all mods for this, but could reproduce it from time to time, but not always, but that might be caused by running server and client on the same machine. I think this was caused by sending the block event for triggering a render update before the tile entity update packet. The block event arrived every time, but the texture wasn't changed always. Changed the order a bit to update before rerendering, now it works reliably every time.

**Comment by LemADEC** [comment]
yes, it might have been intermittent, do you have a test build I can try out?

**Comment by cobra** [comment]
Test build from the current master branch with this patch: [ImmersiveEngineering-0.6.1-pre+gitd48b129.jar](https://www.dropbox.com/s/v8cxcba69vq9zkd/ImmersiveEngineering-0.6.1-pre%2Bgitd48b129.jar?dl=1)

**Comment by LemADEC** [comment]
I've tried your patch on both client and server.
It seemed to work initially, but server crashed rapidly after:
```
[17:36:21] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
>       at blusunrize.immersiveengineering.api.energy.ImmersiveNetHandler.getRelevantDimensions(ImmersiveNetHandler.java:109) ~[ImmersiveNetHandler.class:?]
>       at blusunrize.immersiveengineering.common.IESaveData.func_76187_b(IESaveData.java:84) ~[IESaveData.class:?]
>       at net.minecraft.world.storage.MapStorage.func_75747_a(SourceFile:87) ~[azq.class:?]
>       at net.minecraft.world.storage.MapStorage.func_75744_a(SourceFile:75) ~[azq.class:?]
>       at net.minecraft.world.WorldServer.func_73042_a(WorldServer.java:838) ~[mt.class:?]
>       at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:802) ~[mt.class:?]
>       at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) ~[MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569) ~[MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[17:36:21] [Server thread/ERROR]: This crash report has been saved to: /home/wwm/_beta/./crash-reports/crash-2015-11-11_17.36.21-server.txt
[17:36:21] [Server thread/INFO]: Stopping server
[17:36:21] [Server thread/INFO]: Saving players
[17:36:21] [Server thread/INFO]: Saving worlds
[17:36:21] [Server thread/INFO]: Saving chunks for level 'MiningTime'/Overworld
[17:36:21] [Server thread/ERROR]: Exception stopping the server
java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
>       at blusunrize.immersiveengineering.api.energy.ImmersiveNetHandler.getRelevantDimensions(ImmersiveNetHandler.java:109) ~[ImmersiveNetHandler.class:?]
>       at blusunrize.immersiveengineering.common.IESaveData.func_76187_b(IESaveData.java:84) ~[IESaveData.class:?]
>       at net.minecraft.world.storage.MapStorage.func_75747_a(SourceFile:87) ~[azq.class:?]
>       at net.minecraft.world.storage.MapStorage.func_75744_a(SourceFile:75) ~[azq.class:?]
>       at net.minecraft.world.WorldServer.func_73042_a(WorldServer.java:838) ~[mt.class:?]
>       at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:802) ~[mt.class:?]
>       at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) ~[MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:350) ~[MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:480) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Nov 11, 2015 5:36:21 PM exterminatorJeff.undergroundBiomes.common.UndergroundBiomes adjustMappings
INFO: remapping
```

Rebooting the server and it crashed again:
```
[17:39:39] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
>       at blusunrize.immersiveengineering.api.energy.ImmersiveNetHandler.getRelevantDimensions(ImmersiveNetHandler.java:109) ~[ImmersiveNetHandler.class:?]
>       at blusunrize.immersiveengineering.common.IESaveData.func_76187_b(IESaveData.java:84) ~[IESaveData.class:?]
>       at net.minecraft.world.storage.MapStorage.func_75747_a(SourceFile:87) ~[azq.class:?]
>       at net.minecraft.world.storage.MapStorage.func_75744_a(SourceFile:75) ~[azq.class:?]
>       at net.minecraft.world.WorldServer.func_73042_a(WorldServer.java:838) ~[mt.class:?]
>       at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:802) ~[mt.class:?]
>       at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) ~[MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:569) ~[MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
[17:39:39] [Server thread/ERROR]: This crash report has been saved to: /home/wwm/_beta/./crash-reports/crash-2015-11-11_17.39.39-server.txt
[17:39:39] [Server thread/INFO]: Stopping server
[17:39:39] [Server thread/INFO]: Saving players
[17:39:39] [Server thread/INFO]: Saving worlds
[17:39:39] [Server thread/INFO]: Saving chunks for level 'MiningTime'/Overworld
[17:39:39] [Server thread/ERROR]: Exception stopping the server
java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
>       at blusunrize.immersiveengineering.api.energy.ImmersiveNetHandler.getRelevantDimensions(ImmersiveNetHandler.java:109) ~[ImmersiveNetHandler.class:?]
>       at blusunrize.immersiveengineering.common.IESaveData.func_76187_b(IESaveData.java:84) ~[IESaveData.class:?]
>       at net.minecraft.world.storage.MapStorage.func_75747_a(SourceFile:87) ~[azq.class:?]
>       at net.minecraft.world.storage.MapStorage.func_75744_a(SourceFile:75) ~[azq.class:?]
>       at net.minecraft.world.WorldServer.func_73042_a(WorldServer.java:838) ~[mt.class:?]
>       at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:802) ~[mt.class:?]
>       at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:318) ~[MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:350) ~[MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:480) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Nov 11, 2015 5:39:39 PM exterminatorJeff.undergroundBiomes.common.UndergroundBiomes adjustMappings
INFO: remapping
[17:39:39] [Server thread/INFO] [FML]: Applying holder lookups
```

This happens while holding hammer on right click and moving between 3 capacitors (one of each tier).

**Comment by LemADEC** [comment]
scratch, the server crash on its own, no need to connect to crash it

**Comment by cobra** [comment]
You're using Java 7, right? I built this version with my default JDK 8 and that seems to be a problem. Apparently the return type of keySet() was changed in version 8.

**Comment by LemADEC** [comment]
Server is Java 8, Client is Java 7

**Comment by cobra** [comment]
I rebuilt the same version using openJDK 7 [here](https://www.dropbox.com/s/sy2plnlpuelv85f/ImmersiveEngineering-0.6.1-pre%2Bgitd48b129_java7.jar?dl=1).

**Comment by LemADEC** [comment]
Ok, crash is gone.
Original issue is fixed with a Forge setup. I'll try with plugin later on.

**Comment by LemADEC** [comment]
Issue is fixed with Cauldron and plugins too, thanks!
