### ISSUE TITLE
Assembler not outputting assembled objects

### ISSUE THREAD

**Issue by James-T-Oudvoure** [BluSunrize/ImmersiveEngineering#627]
I've constructed an assembler in a creative world, fed it the components for concrete, and when it assembled the concrete, it never output it. Instead, it simply stored it and had to be removed manually.

**Comment by cobra** [comment]
Did you connect either conveyor belts or an inventory like a chest to the output?

**Comment by James-T-Oudvoure** [comment]
Yes, my setup for output looks like this:
![2015-11-10_16 33 04](https://cloud.githubusercontent.com/assets/14304823/11078011/c868c3e2-87c8-11e5-93ff-700635277dfb.png)

**Comment by cobra** [comment]
you can't use angled conveyors here, the first one has to be on the same level as the output. Technically, your angled belt is sitting on the ground.

**Comment by James-T-Oudvoure** [comment]
Isn't that technically a bug?

**Comment by BluSunrize** [comment]
No it isn't because I can't possible simulate an inventory above the conveyorbelt.

**Comment by James-T-Oudvoure** [comment]
Why exactly doesn't it recognize the angled conveyor?

**Comment by cobra** [comment]
The conveyor is in the block below the one in which the assembler is looking for an inventory. That one is simply air.

**Comment by James-T-Oudvoure** [comment]
Alright then, thank you.
