### ISSUE TITLE
Crusher animation/proccessing issue

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#63]
crusher appears to run even without power, will munch on anything i give it.

Crusher runs the processing animation. particles and all and the sound effect when given any valid ore, regardless of the fact it is unpowered. However: it will keep munching on that item until it receives power, completing the action as expected.

**Comment by DoughnutDev** [comment]
This has long been fixed in newer version.

**Comment by theunkn0wn1** [comment]
ok
