### ISSUE TITLE
Suggestion: hemp to string nerfing

### ISSUE THREAD

**Issue by starg09** [BluSunrize/ImmersiveEngineering#631]
Just an idea, which may cause some people to hate me :D

Basically, I think maybe you could nerf the hemp to string recipe: 1 to 1 is too generous compared to other mods (I.e.: Natura's cotton requires 3 per string, and 9 per wool block; Pam's works almost the same IIRC). Maybe you can just auto tweak it if it detects one of these mods.

I know it's something a little bit trivial, but I wanted to suggest it nonetheless :P

**Comment by starg09** [comment]
PS: I know minetweaker exists. I meant it as something for people who just downloads the mod, and puts it together with one of those mods who also offer string crops...

**Comment by theunkn0wn1** [comment]
+1

Yeah, minetweaker exists for those recipes you dislike however, I do agree 1:1 is too generous given how readily Hemp can get cultivated even without automation; its easier than hunting spiders!

I suggest going withthe 3:1 ratio as 9:1 is quite aggressive for the casual player imho

**Comment by BluSunrize** [comment]
I like it, tbh. Because I hate fighting spiders .-.

I'll take it into consideration though ^^

**Comment by OneEyeMaker** [comment]
That's interesting idea. But making crafting recipe harder (3:1 instead of 1:1) doesn't make a big sense, doesn't create entirely new content. Maybe, you can add some machinery for that purpose (and not only for this)? Yarn Spinning Machine, maybe...

P. S. Sorry for my English, I'm from Russia.

**Comment by James-T-Oudvoure** [comment]
I've always supported adding textile-working machinery.

**Comment by starg09** [comment]
This machine idea sounds way better! It would be a good way for doing it :D

**Comment by OneEyeMaker** [comment]
If this machine will be added, I suggest to change some mod recipes to use it (Tough Fabric, for example).

**Comment by theunkn0wn1** [comment]
Adding a new machine would be a little overkill for just one crafting recipe. Plus, since Blu does not do his own art ( I don't blame you Blu, I am horrible at it myself), it will be a while before a new machine could be added as his artist appears of have both a backlog and a life :3

=========
 I do agree the 1:1 could greatly use with changing as irl string is made of multiple fibres spun together therefore making 1:1 overly unrealistic. 2:1 of even 3:1 would add a sense of difficulty/progression to an otherwise mundane part of the modification.

**Comment by BluSunrize** [comment]
Well I do do my own art. I did the Assembler and Bottling machine, as well as 90% of the revolver skins and every shader ^^

But I do agree that adding a machine for this is pointless, so instead I'm just gonna nerf the exchange rate.

**Comment by starg09** [comment]
Nice, thanks! =)

**Comment by theunkn0wn1** [comment]
Ah, sorry Blu. Was getting my impressions from another thread #617 
I am sorry for my ignorance :sob: 
>And as I said before: Talk to Damien. I don't art.

:confused: 

Thanks for the Nerf though.

**Comment by BluSunrize** [comment]
@theunkn0wn1 I'm just incredibly lazy and far less talented in terms of textures. If you'll look at the assembler and bottling machine you'll see that they are basically 90% hazards existing textures, recut to fit my model. Coming up with something "new" like the breaker I can't be bothered to do x3
