### ISSUE TITLE
Crash On Startup

### ISSUE THREAD

**Issue by TheXWolf** [BluSunrize/ImmersiveEngineering#632]
At first I thought it was because I modified the config wrong, or even that it was modified at all since I disabled a lot of the oregen in IE (due to duplicates.) But after deleting the config file completely the same thing happens. Here's the crash and stacktrace:
http://pastebin.com/gQWeKRv7

**Comment by theunkn0wn1** [comment]
Can we please get the full crash log, the link in your OP is incomplete.

May I ask what version of Forge, IE, and what other mods you have mounted please?

**Comment by TheXWolf** [comment]
Tried IE 0.61 and 0.60 on both forge 1492 and 1541. In an attempt to find the incompatibility, I tried removing multiple mods at a time, but it seems that it's fine with any 1, but after a few of them are put in this happens.
[CrashReport11102015.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/31509/CrashReport11102015.txt)

**Comment by theunkn0wn1** [comment]
Which ones?

**Comment by TheXWolf** [comment]
Never just 1, for example I tried it with IC2 and ThermalExpansion(+TF+TD etc) and Nether Ores etc by themselves one at a time, but when they're all in it crashes. If I have time this week I'll check one by one with the newest of everything.

**Comment by theunkn0wn1** [comment]
Several of your mods are out of date. I would suggest updating Nether ores first and try again. I added the latest available versions of the mods mentioned above (TE and its children;NO;and IC2:E) and was unable to induce the crash.

**Comment by mindforger** [comment]
also please update your java installation! build 25 vs build 65 .. you are way outdated with that too!

**Comment by BluSunrize** [comment]
It's a crash in the generation of an UniqueIdentifier, resulting from the registry being unable to find a name for it. The only way I could see that happen is if some block or item is registered in the OreDictionary but not in the Item/Block Registry...

**Comment by TheXWolf** [comment]
Judging by the crash log, I would agree with Blu, see as it's a null stack reference. Well my original point was that I had no crash despite changing my own personal mods a couple times a week, an IE induced it by itself. Keep in mind that according to forge it only works with Java 7 not 8, I have 7u80 installed, but for giggles updated to u65. Also for the point of testing tried it without mods I could do without...same error.
[CrashReport_111120152.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/32029/CrashReport_111120152.txt)

**Comment by BluSunrize** [comment]
allright, try removing one mod after the other, to identify which of them has compat-issues.

**Comment by TheXWolf** [comment]
>Never just 1, for example I tried it with IC2 and ThermalExpansion(+TF+TD etc) and Nether Ores etc by themselves one at a time, but when they're all in it crashes.

I did try one at a time, and you have my list of mods in my crash dump. If you insist **I do it** later this week I'll do it again with the newer versions.

**Comment by BluSunrize** [comment]
Sorry, I missed that part, my mistake. I am still utterly confused as to how this happens though. I also have EIO and Thermal's in my enviroment and have never had this happen. It's a crash in Forge's internals which makes this even more confusing .-.

**Comment by XFactHD** [comment]
Could this be the culprit: http://pastebin.com/yCcgiXPm at src/main/java/blusunrize/immersiveengineering/common/IERecipes.java?
