### ISSUE TITLE
Fluid pipe NPE

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#633]
Sorry Blu, got no idea how to reproduce this, was one-off. IE is all over the crashlog, though FastCraft is present. 

here is the [gist](https://gist.github.com/theunkn0wn1/c0cb1efbd317765a4569)

IE build  018bb22

**Comment by mindforger** [comment]
this is pretty sure caused by fastcraft, it's part of the call chain resulting in this

**Comment by BluSunrize** [comment]
It's an NPE pointing to "indirectConnections" from what I can see, but that map should never be null...

**Comment by theunkn0wn1** [comment]
If it makes any difference, this was on world load. This world has quite a few pumps, pipes, and tanks in active use stored within. No forced chunkloading was being done.

**Comment by BluSunrize** [comment]
the map is static though, it should be present constantly :/

**Comment by AEnterprise** [comment]
you could make the map static and final, that way once constructed the map can't disapear

**Comment by mindforger** [comment]
i want to sidenote here the immense use of "getTileEntitity" without checking of loaded chunks may lead to the same forceloading of ghost chunks like enderIO did in the past! @BluSunrize  you fixed that ghostlöoading in your power code but the pipe code seems to still be prone to this issue

**Comment by theunkn0wn1** [comment]
Lack of reproducibility, seemingly not being investigated, issue no longer relevant to the current state. Issue closed
