### ISSUE TITLE
Mineral deposits on server

### ISSUE THREAD

**Issue by Pilchard123** [BluSunrize/ImmersiveEngineering#636]
From what I've read, roughly one in eight chunks should contain something; I've sampled about two dozen and found nothing. Should I be unable to find mineral deposits on a server, or have I just been really unlucky?

I'm using 0.5.2 because that's the one that comes with the Resonant Rise pack, and my config file is attached. I can easily change the config or update if necessary (I'll probably update to the latest 1.7.10-compatible version anyway).

[ImmersiveEngineering.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/32260/ImmersiveEngineering.txt)

**Comment by BluSunrize** [comment]
Try not running an outdated version. 0.5.2 is way outdated.
