### ISSUE TITLE
Unable to connect connectors in some cases

### ISSUE THREAD

**Issue by Glassmaker** [BluSunrize/ImmersiveEngineering#639]
Credits to Techtronic on IRC for finding this one.

For some reason it works fine at these coords
![2015-11-12_10 30 22](https://cloud.githubusercontent.com/assets/5352172/11113203/dfe2cf72-892b-11e5-9496-c29adc5ea7ad.png)

And doesn't connect at these coords
![2015-11-12_10 30 01](https://cloud.githubusercontent.com/assets/5352172/11113211/f328dcb6-892b-11e5-9e5d-864b19628b53.png)

**Comment by cobra** [comment]
This might be related to a bug in the raytracer which I found, that one has already been fixed.

Example, the red blocks had to be removed to get the connection:
![](https://cloud.githubusercontent.com/assets/163331/11116827/5228d92e-8935-11e5-91ea-862e59ba6ddc.png)

 I tested this setup, even at the same location and didn't have any problem:

**Comment by BluSunrize** [comment]
I'll consider this fixed then.
