### ISSUE TITLE
0.2.1 Fermenter Server Crash

### ISSUE THREAD

**Issue by Thorinori** [BluSunrize/ImmersiveEngineering#64]
So I started up my server with IE 0.2.1 on it, wander around for a minute or so then the server crashes. Here is the log.
http://pastebin.com/UCDchqQB

I am assuming it is the fermenter, the error in the console mentioned it. Once I destroyed my fermenter after getting back on, I haven't crashed yet.

**Comment by DoughnutDev** [comment]
Yeah I having the same thing.

**Comment by BluSunrize** [comment]
Interesting. I'll add another check there, but it's hard for me to test this, because I have no old worlds :/

**Comment by Thorinori** [comment]
If you want I can zip up my world from my server and send it to you. The fermenter is incomplete now on it though, I havent tried putting it back together yet since I didn't want to crash the server again.

**Comment by BluSunrize** [comment]
Try with the new build

**Comment by DoughnutDev** [comment]
I put my back together and it didn't crash tell I hooked up power to it.
But like the squeezer was fine.

**Comment by BluSunrize** [comment]
okay, pictures of the setup, what was in the squeezer and full crashlog please. If I can't reproduce it I can't fix it.

**Comment by jolllyroger** [comment]
I had a similar experience with the fermenter.  It didn't crash my game but caused massive tick lag.  Here's a pic of the setup:
https://dl.dropboxusercontent.com/u/6051179/2015-06-22_18.39.12.png

Basically, the game gets to the point where you can't interact with anything or open nei.  When you attempt to quit the game, it hangs on shutting down the server.

I ran warmroast while it was hanging like this and here's the result:
https://dl.dropboxusercontent.com/u/6051179/fermenter.jpg

Hope that helps.

**Comment by BluSunrize** [comment]
I think I've fixed this in 0.2.2

**Comment by BluSunrize** [comment]
Reopen this if the bug persists with version 0.2.4 and later
