### ISSUE TITLE
Assembler consumes TFC Tools

### ISSUE THREAD

**Issue by Bunsan** [BluSunrize/ImmersiveEngineering#640]
This is tested in IE 0.6.1 in a Forge 1558 environment.

If TFC tools are used in an assembler recipe they are consumed on the first craft. This is due to TFC setting the tool's stack size to 2 instead of using a container. This issue also occurred with Forestry's Worktable. The relevant fix can be found https://github.com/ForestryMC/ForestryMC/commit/3e0cf7c302005ddae700cf71ce695fc3b902c2bd 

I've spoken to KittyChanley and she is looking to change TFC to use container instead of changing item stack. However this also seems to be an issue with Minetweaker scripts that use tool durability in crafting recipes.  
Example script 
`recipes.addShapeless(<minecraft:boat>, [<ore:logWood>, <ore:logWood>, <ore:logWood>, <minecraft:stone_axe>.anyDamage().transformDamage()]);`
The an stone axe of any durability is accepted, however it is consumed in the first craft.

**Comment by cobra** [comment]
Their crafting handler isn't event triggered, so this won't work by just importing this change. The tool's stack size is still 1.

**Comment by Bunsan** [comment]
Thank you. I've informed KittyChanley about the crafting event handler issue. She is already looking to change it to use container, using EE3 code as a guide. So hopefully it will be fixed on their end.  Not sure about minetweaker, I'll have to go look at their code to figure out what they are doing. All I know right now is that tools in MT scripts are eaten too.

**Comment by cobra** [comment]
Do these minetweaker scripts work in the cyclic assembler or other autocrafting machines?

Not firing a crafting event is somewhat inherent to autocrafting - the event contains a player reference. This could be worked around, but depending on the other mods, this might mess with their content (for example skill systems or usage of power networks like Blood Magics LP network).

**Comment by BluSunrize** [comment]
I'll look into it tomorrow, I didn't get time today.

**Comment by Bunsan** [comment]
The development on TFC has stopped and the changes necessary to fix this issue will break add ons and so will not be adopted. We've introduced itemContainer into our fork to fix the issue. Closing issue.
