### ISSUE TITLE
Bottling conflicts with flud transposer from Thermal Expansion in NEI

### ISSUE THREAD

**Issue by mskurnik** [BluSunrize/ImmersiveEngineering#642]
I would like the ability to disabled some of the multiblock structures that you provide.  While they are really cool, they conflict with already established machines that we have in our mod pack.  Most notably is the new Bottling structure that conflicts with recipes that you would use the Fluid Transposer from Thermal Expansion for.  While I am not 100% sure this is your fault, in NEI the display for crating some items show only the Bottling Machine to fill it with a fluid instead of showing both the Transposer and the Bottling Machine.

It seems to only be an issue where the IDs are shared between multiple items.  For example, the Fluctuating Itemduct ID is 1110:6 (on my server) and is shared between it and its sub versions of dense and vacuum fluctuating itemduct. So in the end 3 items have the same ID of 1110:6.

I am fairly certain it is something to do with Immersive Engineering as the Team COFH mods haven't been updated recently.

**Comment by BluSunrize** [comment]
That seems quite impossible. I do not change the CoFH recipes, nor do I even interact with them. The bottling machine exists in parallel, offering you another solution. But it does not replace or override anything.

**Comment by mskurnik** [comment]
Well it was worth a shot to ask.  It would be nice to disable certain machines in the config however.
