### ISSUE TITLE
Internal Server Error when placing Revolver on Engineer's Workbench

### ISSUE THREAD

**Issue by FrauTaviKeppler** [BluSunrize/ImmersiveEngineering#644]
Does not crash when placing blueprints and such on table. Only the revolver. Playing on a modified FtB Infinity server.

**Comment by theunkn0wn1** [comment]
Unable to reproduce with provided data. Is this on a integrated server (SSP) or an MP (dedicated server) environment? Can we please get a copy of the client/server logs?

Attempted to reproduce with FTB Infinity 2.0.0 (magic mods removed, updated IE to build f2d5441) and was unsuccessful. Placed down a workbench and spawned a revolver from NEI, placed said revolver into the workbench and no crash/internal error occurred.

**Comment by BluSunrize** [comment]
I get the feeling this may be the shader-slot error. Client access and such.
I'll need version number and crashlog though.

**Comment by BluSunrize** [comment]
No further info given, so: Closed.
