### ISSUE TITLE
I translate the zh_CN.lang language file for you 

### ISSUE THREAD

**Issue by bitterly369** [BluSunrize/ImmersiveEngineering#645]
Can I sent it to you ?
[zh_CN.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/34546/zh_CN.txt)

**Comment by theunkn0wn1** [comment]
If you wish to contribute code, including language files,  please create a pull request with the new/modified files.

**Comment by BluSunrize** [comment]
what @theunkn0wn1 said. Pullrequests only, I don't manage lang files manually.
