### ISSUE TITLE
[minor] Rendering oddities with the book

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#646]
When viewing any page within the "Mineral Deposists" chapter of the Engineer's Manual that contains a table, the Table's vertical component continues past the last entry and off the paper; this is not repeated in later tables.

![image](https://cloud.githubusercontent.com/assets/3110986/11162347/aea7bda0-8a52-11e5-8164-2157c0ed21e7.png)
![image](https://cloud.githubusercontent.com/assets/3110986/11162349/b51b569c-8a52-11e5-95a2-fb15efd5f395.png)

![image](https://cloud.githubusercontent.com/assets/3110986/11162361/d27c81e8-8a52-11e5-99d3-3c16985c9206.png)

===========
IE build f2d5441

**Comment by malte0811** [comment]
This is a mixture of multiple bugs, at least one concerning the adding of ores to the manual (fixed) and one concerning multi-line table entries (fixing now).

**Comment by BluSunrize** [comment]
This has been fixed locally. But that manual entry is getting a major overhaul anyway, so don't worry about it.
