### ISSUE TITLE
Possible Issue

### ISSUE THREAD

**Issue by Thorinori** [BluSunrize/ImmersiveEngineering#65]
So I have had a Lightning Rod sitting in a dimension I created using RFTools specifically for constant rain and thunderstorms for the past 2 days, and it has yet to get struck by lightning. It has nearly 2 stacks of steel fences on it, so I think it could possibly be a bug, or maybe I am just SUPER unlucky?

**Comment by BluSunrize** [comment]
Probably super unlucky, or at least I'd hope so. x3

**Comment by Thorinori** [comment]
Hopefully it is just bad luck. Is there a max height for the rod to up the chances, or how does it work? The manual is kind of vague in my opinion.

**Comment by DoughnutDev** [comment]
I have had the same luck

**Comment by JAWSAWN** [comment]
I cast the Witchery ritual on 9 lightning rods. Most of the lightnings hit the middle blocks but no power.
Did you coded it like that? Or they are not working?

**Comment by BluSunrize** [comment]
might be broken, I'll look into it
