### ISSUE TITLE
Config option to disable electric lamp mob spawn prevention

### ISSUE THREAD

**Issue by WolfieWaffle** [BluSunrize/ImmersiveEngineering#650]
I like the addition of the electric lamp, but if it's easy enough to do, I would like a config option to make it work just like a normal lamp without the spawn restriction. I think it would be useful for mod packs where torches burn out or similar things. It could also be OP in some cases, so just as a safety thing it would be good to have it configurable.

**Comment by BluSunrize** [comment]
I can see how this'd be useful. Will be added.
