### ISSUE TITLE
[Crash] Problem with Matter Overdrive

### ISSUE THREAD

**Issue by AegisLesha** [BluSunrize/ImmersiveEngineering#651]
The game crashes when Matter Overdrive is present
Here's the log: http://pastebin.com/C1iyqz5H
Appears to be related to rendering
Also, pinging @simeonradivoev

**Comment by simeonradivoev** [comment]
Strange problem. It seems to be a problem with immersive engineering. When does the crash occur ?

**Comment by AegisLesha** [comment]
When the game is loading, at the texture loading part I think

**Comment by BluSunrize** [comment]
Your Immersive Integration is outdated. Not a Matter Overdrive error, and not IE either. Update II.
