### ISSUE TITLE
Issue reported by someone playing my mod pack containing this mod

### ISSUE THREAD

**Issue by MJRLegends** [BluSunrize/ImmersiveEngineering#653]
See - https://github.com/MJRLegends/Space-Astronomy-Feedback-/issues/99

**Comment by theunkn0wn1** [comment]
You using IE0.5.x? There is a known issue in 0.5.x and earlier that might be causing your issue. see #461

**Comment by MJRLegends** [comment]
Yeah thats what i was thinking thats why i said to the person wait and see if its fixed for the next update of the mod pack which will contain the latest version of this mod.
