### ISSUE TITLE
[question] Pam's Harvestcraft support

### ISSUE THREAD

**Issue by James-T-Oudvoure** [BluSunrize/ImmersiveEngineering#654]
How exactly is the mod compatible with Pam's Harvestcraft? I've read that industrial squeezer and fermenter were added, but what are they? There isn't even any mention of it in the manual.

**Comment by cobra** [comment]
Look under Biodiesel.

**Comment by James-T-Oudvoure** [comment]
I don't see anything.

**Comment by cobra** [comment]
Heavy Machinery - Biodiesel, or use the integrated search. The documentation for squeezer and fermenter is on pages 2-6.

**Comment by James-T-Oudvoure** [comment]
I looked there, but still, no mention of Harvestcraft.

**Comment by WolfieWaffle** [comment]
The seeds can be used in one of the machines if I remember correctly, compatability with Harvestcraft is not explicitly stated in the manual.

**Comment by James-T-Oudvoure** [comment]
Alright, I converted a whole stack of barley, rye, and corn into seeds and neither the industrial squeezer nor the fermenter will do anything with them.

**Comment by mindforger** [comment]
you should post your used IE version you are probably outdated?!

**Comment by James-T-Oudvoure** [comment]
Alright, I updated to 0.6.2 from 0.6.1 and the seeds work in the industrial squeezer. I also noted that rye, barley, and oats non-seed forms could be fermented. Bizarrely enough, corn of all things doesn't work in it.

**Comment by mindforger** [comment]
@James-T-Oudvoure this is because they are grouped via "oredictionary" ... except its not ores ... but i can't remember the entry name ... its all based on minetweaker, you can happily manipulate the materials used in fermenter and squeezer to your own desire (even the outcome na dtime to proceed)
