### ISSUE TITLE
Breakers

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#655]
I know its a freshly introduced feature...

The original Breaker Switch (the manual one) has wording in the manual that states it cannot handle HV lines, yet it can.

![image](https://cloud.githubusercontent.com/assets/3110986/11172248/de6794d6-8bb8-11e5-9f3d-ffecc5a0760c.png)

build caf843d

============
EDIT: Also, The Redstone breaker will not accept indirect redstone signals, as in redstone signal applied to the block adjacent to it such as the face it is placed against.

**Comment by WolfieWaffle** [comment]
Personally, I think it should be able to handle HV, but I agree that the manual should be changed to whatever is correct.

**Comment by theunkn0wn1** [comment]
Personally, I agree with the change, HV should be too dangerous to put your
hands near IMHO. The book states HV should be incompatible, yet the change
appears not to have been made yet, thus this issue thread was spawned

**Comment by cobra** [comment]
The change has been made, `canTakeHV` returns false, but it's never checked, because it overrides `canConnectCable` which is normally doing these checks and doesn't implement them. It was a bit late ;)

**Comment by BluSunrize** [comment]
Ah, damn. I missed that part. So yeah, it was suggested many time and since we have an HV breaker not it's definitely intentional that the knife-switches shouldn't take HV anymore. I just didn't test it properly and I built at 1:40 am .~.

**Comment by WolfieWaffle** [comment]
Wait, there's an HV breaker now? I didn't see it.

**Comment by theunkn0wn1** [comment]
Yeah, the Redstone breaker, Blu added it to 0.6.2

**Comment by BluSunrize** [comment]
fixed the HV with https://github.com/BluSunrize/ImmersiveEngineering/commit/a9f334b69247decfd8bd98219c0f7e6008abf7a2
