### ISSUE TITLE
0.6.2 is useless on a server with the MT 3.0.10B requirement

### ISSUE THREAD

**Issue by tgstyle** [BluSunrize/ImmersiveEngineering#659]
3.0.10B of Minetweaker Dev version is broken, a server does not even start with it. Essentially makes 0.6.2 useless for anyone running a server.

**Comment by AnodeCathode** [comment]
Are we talking about 3.0.10B or 3.1? 3.0.10B does indeed work fine on a server. Our servers all run it without issue.

**Comment by tgstyle** [comment]
Sorry, yes 3.0.10B I cannot get it to run on a server. It may be that I use modteaker as well.

**Comment by tgstyle** [comment]
I just tested a server with nothing but MT 3.0.10B and it crashed. So I am not sure how your servers are working.

**Comment by tgstyle** [comment]
OK I found out what was up. Their site does not have the 3.0.10B release on it, just the dev version. Seems you have to go to curse now to get the latest release. This seems to work.
