### ISSUE TITLE
[question] The bock

### ISSUE THREAD

**Issue by Xnetsrac** [BluSunrize/ImmersiveEngineering#662]
In welcher Datei in der .jar finde ich die Einträge für den Inhalt der  Erzvorkommen, damit ich diese im Buch umschreiben kann...
---------------------------------------

In which file in the .jar I find the items for the content of the ore , so I can rewrite this in the book

**Comment by XFactHD** [comment]
You can find them in the Lang files.

**Comment by mindforger** [comment]
@Xnetsrac i am on it, i get online around 18:00 Obstkuchen's script needs some fine tuning as there were added some parameters
