### ISSUE TITLE
Arc Furnace invisible

### ISSUE THREAD

**Issue by KindarConrath** [BluSunrize/ImmersiveEngineering#665]
This is more of a placeholder right now unless someone figures it out. I am still hunting down the issue.

Where: On my server, near my base.
What: When formed, the Arc Furnace goes invisible, or more accurately doesn't render.

Also seems to happen in some single player worlds...

Problem is, I haven't been able to find the source of the issue yet. 

* It does not render near my base (Site 0)
* It does not render north of my base (Test Site 1)
* It DOES render west of my base (Test Site 2)
* It DOES render west of my base (Test Site 2) in every direction (orientation).
* OTHER IE MultiBlocks DO render at my base (Site 0)

I haven't yet found a specific block that causes it not to draw.

I am assuming that it is another mod that is interfering with the render of the Arc Furnace.
It also seems to be something that exists on world gen, as it is not just affected by my base.

I have also tried removing mods, with very little success so far.

I tried to figure out what mod might be causing it by going into a single player world and building an Arc Furnace (it went invisible) then breaking a block, leaving game, removing some mods and then going in and re-finishing the furnace.  
Even stripped down to JUST CoFHCore-3.0.3-303 and ImmersiveEngineering-0.6.2 it still went invisible, which leads me to suspect what ever is causing it messes with the MultiBlock TE...

I think my next step is to do that again, but re-build the Arc Furnace from scratch every time... 

NO I do NOT use Optifine, and I AM using a vanilla forge server.

MC: 1.7.10
Forge: 10.13.4.1541

Mod List:

(1.7.10 Folder)

File | Version
-------- | -----------
bspkrsCore | 6.15
Baubles | 1.0.1.10
CodeChickenLib | 1.1.3.138
commons codec | 1.9
commons-compress | 1.8.1
Forge Multipart | 1.2.0.345
Forge Relocation | 0.0.1.4
Forge Relocation FMP | 0.0.1.2
MrTJPCore | 1.1.0.31
slick-util | 0.0b9db0b2
vorbis-java-core | 0.8-20150201.161816-1

Mod | Version
------ | ----------
ArmorStatusHUD | 1.28
DamageIndicatorsMod | 3.2.3
StatusEffectHUD | 1.27
MB_Battlegear 2 | 1.0.8.2
AgriCraft | 1.4.5
AppliedEnergistics 2 | RV2-stable-10
backpack | 2.0.1
bdlib | 1.9.3.107
BiblioCraft | 1.11.4
BigReactors | 0.4.3A
BloodMagic | 1.3.3-17
ChickenChunks | 1.3.4.19
Chisel2 | 2.5.1.44
CodeChickenCore | 1.0.7.47
CoFHCore | 3.0.3-303
CoFHLib | 1.0.3-175
CoFHTweaks | 1.0.1-37
ComputerCraft | 1.74
CraftingTweaks | 1.0.49
Decocraft | 2.2.1
EnderCore | 0.2.0.31_beta
EnderIO | 2.3.0.419
EnderStorage | 1.4.7.37
EnderZoo | 1.0.15.32
EquivalentExchange3 | 0.3.507
ExtraCells | 2.2.73b129
ExtraTiC | 1.4.5
extrautilities | 1.2.12
Forbidden Magic | 0.571
Forestry | 4.1.1.46
GalacticraftCore | 3.0.11.333
Galacticraft - Planets | 3.0.11.333
Gendustry | 1.6.2.127
Growthcraft | 2.3.1
Guide-API | 1.0.1-20
Hats | 4.0.1
HatStand | 4.0.0
HQM | 4.4.1
iChunUtil | 4.2.2
IguanaTinkerTweaks | 2.1.5
ImmersiveEngineering | 0.6.2
ImmersiveIntegration | 0.6.1
INpureCore | 1.0.0B9-62
InventoryTweaks | 1.59-dev-152
Ironchest | 6.0.62.742
Jabba | 1.2.1a
JourneyMap | 5.1.0
LogisticsPipes | 0.9.3.69
MagicBees | 2.4.0
Mantle | 0.3.2b
mcjtylib | 1.7.0
MicdoodleCore | 3.0.11.333
MineFactoryReloaded | 2.8.0-104
MmmMmmMmmMmm | 1.9
MobiusCore | 1.2.5
ModularPowersuits QMX | 0.11.0.7
ModularPowersuitsAddons QMX | 0.11.0.7
Morph Beta | 0.9.2
Morpheus | 1.6.10
natura | 2.2.0.1
neiaddons | 1.12.14.40
neiintegration | 1.0.13
notenoughfixes | 1.2.0.2
notenoughitems | 1.0.5.118
numina QMX | 0.4.0.7
OggAudioData | 0.1.0
OpenBlocks | 1.4.4
OpenModsLib | 0.8
OpenPeripheralAddons | 0.4
OpenPeripheralIntegration | 0.3
Pam's HarvestCraft | 1.7.10k
PlayerAPI | 1.4
PneumaticCraft | 1.11.19.141
Prattle | 0.0.9a
ProjectRed: Base, Compat, Integration, Lighting, Mechanical, World | 4.7.0pre9.92
Railcraft | 9.8.0.0
RedstoneArsenal | 1.1.1-89
rftools | 4.01
Ruins | ??
Sanguimancy | 1.1.9-31
ServerTools-CORE | 2.2.0.79
SimilsaxTranstructors | 1.7.10.15
SimplyJetpacks | 1.5.2
StevesAddons | 0.10.16
StevesFactoryManager | A93
StevesWorkshop | 0.5.1
tcnodetracker | 1.1.2
TConstruct | 1.8.8
Thaumcraft | 4.2.3.5
thaumcraftneiplugin | 1.7a
ThaumicExploration | 1.1-53
ThaumicTinkerer | 2.5-1.7.10-164
ThermalDynamics | 1.1.0-161
ThermalExpansion | 4.0.3B1-218
ThermalFoundation | 1.2.0-102
TicTooltips | 1.2.5
TMechworks | 0.2.14.100
TravellersGear | 1.16.6
UpdateCheckerMod | ??
VeinMiner | 0.30.1
Waila | 1.5.10
WailaHarvestability | 1.1.5
WAILAPlugins | 0.2.0-23
witchery | 0.24.1
WR-CBE | 1.4.1.9

**Comment by mindforger** [comment]
make a copy of the world and if you're able, locate the depending world save file and upload it somewhere i have a strong guess hats happening there but i need the actual nbt file to this chunk

for a workaround(keep the saved world anywhere), try placing blocks around the whole multiblock and after completely covering it, remove them,
note which block you placed the moment it started to reappear ... i can use this in combination with the save file ... in all occasions i encountered this, blockupdates on some key blocks fixed the rendering for me

**Comment by KindarConrath** [comment]
It IS happening in one of my single player test worlds, so I can send a copy of that too you. Tonight I'll try the workaround, see if it works and let you know which block it was that causes it to reappear.

**Comment by mindforger** [comment]
if you upload the full world, note down the coordinates for me :) makes search in save games so much easier

**Comment by KindarConrath** [comment]
That one might be tricky, the world that I did the testing in is my multiplayer server, that file might be a bit bigger :P I'll see how big it is zipped up and if its not TOO big, i'll include it.

Bah, why must I be at work? I'd rather be bug testing mods any day!

**Comment by KindarConrath** [comment]
So, to update, the Furnace is invisible unless there is a block placed adjacent to it on any of 3 sides, or the top.

in my test, a block placed adjacent to the furnace on the W,S,E sides (Front, Right, Back) or Top on any layer other than the bottom layer of the Furnace, will make it visible.  the other side North (Left) (The side that the toggle switch is on (not the front)) does not.  It does go invisible again if I break the block.

**Comment by KindarConrath** [comment]
My base is 503,64,59 X,Y,Z
I was testing it on the sand patch in front of my base.

https://dl.dropboxusercontent.com/u/35944685/Overworld.zip

Word of warning, it is 321mb (I know thats not an overly large world file, but its still a big file.)
If you want a copy of my Mod pack to test with, I can send it too you, but its private so I can't post it on here publicly.

**Comment by mindforger** [comment]
thanks, i am looking forward to dig into it .. but in 9h at best :P ... i'll analyze it manually via NBT editor, i noticed some odds in the multiblocks in my world earlier this way

**Comment by KindarConrath** [comment]
I just realized, there isn't a furnace there right now, I'll have to add one and update the file.

**Comment by BluSunrize** [comment]
Fixed with Version 0.7.1.2
