### ISSUE TITLE
Crash with search bar

### ISSUE THREAD

**Issue by WolfieWaffle** [BluSunrize/ImmersiveEngineering#666]
I got this crash when searching for something in the search bar:

http://pastebin.com/Ve5RSkAE

**Comment by KindarConrath** [comment]
This error appears to be with a ZettaIndustries mod called OCWires 

java.lang.NoSuchMethodError: blusunrize.immersiveengineering.client.ClientUtils.renderStaticWavefrontModel(Lnet/minecraft/tileentity/TileEntity;Lnet/minecraftforge/client/model/obj/WavefrontObject;Lnet/minecraft/client/renderer/Tessellator;Lblusunrize/immersiveengineering/common/util/chickenbones/Matrix4;Lblusunrize/immersiveengineering/common/util/chickenbones/Matrix4;ZZ[Ljava/lang/String;)V
        at com.bymarcin.*zettaindustries.mods.ocwires*.render.RenderTelecommunicationConnector.renderStatic(RenderTelecommunicationConnector.java:47)

**Comment by WolfieWaffle** [comment]
Sorry! I thought it was IE because of the first part, the blusunrize.immersiveengineering etc. part.

**Comment by KindarConrath** [comment]
Thats ok, took me a moment too, then i realized that ocwires was calling IE's renderStaticWavefrontModel function

**Comment by WolfieWaffle** [comment]
Ah, ok. I'll update zetta industries and if the problem remains I'll make an issue on their tracker instead.
