### ISSUE TITLE
Invisible Excavator

### ISSUE THREAD

**Issue by angelnc1989** [BluSunrize/ImmersiveEngineering#667]
ImmersiveEngineering-0.6.2
I built an Excavator on my server and the Excavator part is completly invisible until I place a block/Wire Connector on it. The Bucket Wheel however is perfectly fine.
The issue is present with and without Optifine.
I wasn't able to reproduce it in my single player test world.

**Comment by mindforger** [comment]
related to https://github.com/BluSunrize/ImmersiveEngineering/issues/665
try my workaround there and see if it helps

**Comment by BluSunrize** [comment]
Fixed with Version 0.7.1.2
