### ISSUE TITLE
Localization: Spanish

### ISSUE THREAD

**Issue by berinhardt** [BluSunrize/ImmersiveEngineering#669]
I'm sure it's not perfect, but I needed to localize this to play with some friends that only understand spanish, and thought maybe you wanted to add it to the mod. If that's the case, feel free to do it

[es_ES.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/38353/es_ES.txt)

**Comment by BluSunrize** [comment]
please submit a pullrequest. I do not want to manually manage these localizations.
