### ISSUE TITLE
Capacitor tick death

### ISSUE THREAD

**Issue by ShadowDrakken** [BluSunrize/ImmersiveEngineering#67]
I'm not sure if this is an issue with the capacitors themselves or with the RF system, and it may already be fixed in your internal version if you've noticed it happening as well.

But anyway, long story short is I that had 3x LV Capacitors hooked up to an Immersive Engineering only power network and found that over time more and more tick lag would build up ("Can't keep up", "skipping X number of ticks", etc)

Over the course of about an hour it was bad enough to noticably affect gameplay. Overnight with no users logged in, by morning it was skipping more than 6,000 ticks, with spikes over 22,000 ticks.

I swapped the LV capacitors out for Leadstone Cells (Thermal Expansion) and the tick death seems to be cleared up, or at least reduced to the point of not being noticeable over normal gameplay sessions.

**Comment by DoughnutDev** [comment]
If you are running 0.1.9 this has long been fixed because there was a
massive memory leak that would do this to servers.

**Comment by ShadowDrakken** [comment]
Gotcha, that's sort of what I suspected, but I didn't see an issue opened for it yet. I'm hoping Github sees a newer build some time before release, but I know the public upload fiasco kind of soured the chances of that pretty bad too, so just reporting what bugs I do find.
