### ISSUE TITLE
[Suggestion] Plant oil / Seed oil

### ISSUE THREAD

**Issue by whitestarx0312** [BluSunrize/ImmersiveEngineering#672]
Just a simple suggestion to make plant oil compatible with seed oil from Forestry. I already have my IE squeezer set up and it would be awesome if I could use that to make my apiaries! :)

**Comment by mindforger** [comment]
try https://github.com/BluSunrize/ImmersiveEngineering/issues/502

**Comment by whitestarx0312** [comment]
I would do that, but I play on a server and I am not the owner. Furthermore we play a specific modpack and I don't think it has minetweaker.
