### ISSUE TITLE
Wires disappearing in RFTools Dimension

### ISSUE THREAD

**Issue by TanteEmma** [BluSunrize/ImmersiveEngineering#673]
Test on 6.02. added to DW20 Modpack

I know there are issues open atm about related stuff, but I could not find any in 6.0+ versions so I've opened one, hope this is ok.
So I've noticed that after client restart every wire disappears in an RFT Dimension, also HV Connectors  and both Transformers won't accept any cables, with the message showing "You can't attach this here" (or something like that) LV / MW connectors  and HV Relays are fine and accept cables.
Tested in a fresh world with nothing but RFTools and IE placed.
I don't know if it's a problem with the Dimension saving/loading on RFTs side or if it's on IEs side, hope someone can help.
In both my worlds (Singleplayer and Testing) the Overworld is fine and cables stay connected.

**Comment by mindforger** [comment]
RFTools is doing strange stuff ... maybe the way their dimensions are unloaded causes not only this but the problem with cables not loading after ending and starting a single player world again

**Comment by malte0811** [comment]
I am able to reproduce this, testing now

**Comment by TanteEmma** [comment]
@mindforger what do you mean with "save-all" ?! And completely closing my client is the problem. Just re-entering the world from the Mc "Homescreen" and everything is fine. 
I'm on the FTB Launcher if that is of interest.

**Comment by mindforger** [comment]
save-all as command ingame .. i was suspecting and older problem may have reappeared, this sounds new, but malte is on it :D

**Comment by TanteEmma** [comment]
Tried the "save-all" command but it says "unknown command".

**Comment by TanteEmma** [comment]
Dumb question maybe, but how do I get the fixed version ?

**Comment by BluSunrize** [comment]
either compile your own or wait for my next build.
