### ISSUE TITLE
[Unknown] IE stalls on world load?

### ISSUE THREAD

**Issue by Valgorn** [BluSunrize/ImmersiveEngineering#676]
When trying to place the revolver into the engineers workbench there is an internal server error and the player is kicked from the server. This only happens when on the server, in single player it works as intended.

**Comment by BluSunrize** [comment]
I need your log and your version number of IE.

**Comment by Valgorn** [comment]
It doesn't crash the game so there is no report for me to give, the version of IE I am using is 0.6.0.

**Comment by BluSunrize** [comment]
There is always a log. in the logs folder, right next to the mods folder, put the latest on pastebin and link it to me.
Also, I feel like I new which issue this is, so try updating your IE to fix it.

**Comment by Valgorn** [comment]
i go into the log folder and there isn't one for when it kicks me form my server and send me back to the server menu. ill try updating IE but my friend told me of how it causes his world to stall on loading.

**Comment by Valgorn** [comment]
Tried running 0.6.2 and it does stall on loading in a world, weather its an existing or brand new one, Specifically on "Building Terrain".

**Comment by BluSunrize** [comment]
And once again, you are not providing me with the log which I /know/ exists. That's what the log folder is for. I can't help you if you don't give me the relevant info.

**Comment by BluSunrize** [comment]
I'm also renaming this issue since the revolver bug was definitely fixed for 0.6.1 and later.

**Comment by Valgorn** [comment]
Here is the Latest Log http://pastebin.com/sQAdsxav

**Comment by mindforger** [comment]
was that a server on localhost or a launched single player? i am somehow missing the "mystcraft is baking a cake" message ... 
from my point of view 4 things:
1. if it is single player, did you wait for mystcraft to complete (there should be a loading bar in your menu)
2. if it is a server, did you check if mystcraft finished it's work? this takes up to an hour especially when you run __both__ server and client on the same machine, thats kind of deadly and could lead to the described "stall"
3. why is Java 1.8.0_25 so utterly common, it has dozends of security issues and 2 issue regarding file name spaces that hit forge in the past, please update it, current is 65 not 25
4. i spot liteloader, i expect this is for voxelmap, i'd recommend remove __both__ voxelmap is prone to overload rendering and liteloader modifys the client in undefined ways

**Comment by Valgorn** [comment]
This was one a server, no ones started mystcraft but i guess that doesn't mean it not just doing something. Though it works fine in singleplayer, the stall was trying to load up a single player world, either form scratch or a pre-existing one. ill go about updating java and removing mystcraft and seeing how that fairs.

**Comment by Valgorn** [comment]
Alright so here is how the issue started, during 0.6.0 placing the revolver on the workbench causes an internal server error, but only if your playing on a server. We tried updating to 0.6.2 and that causes the world loading/creation bug. The world loading issue doesn't happen in 0.6.0 just the "Placing the revolver into the Engineers Workbench kicking you from the server" bug.

**Comment by BluSunrize** [comment]
Yes. As I said, that bug has been fixed with v0.6.1 and onwards.

I have yet to get any other reports on the stalling or any logs of it, so I can do literally nothing. What I did see in that log however was the liteloader that @mindforger mentioned already. Please do try again with that removed

**Comment by Valgorn** [comment]
loaded a version of forge that wouldn't load litemod and disabled the voxel mapping mod. The game still stalls of loading a world in. It leaves a process of minecraft running even after forcing it to close. After closing the process there is this at the end of the log. http://pastebin.com/syapy7tD

**Comment by Valgorn** [comment]
Ive now tried it with removing mystcraft as well and the same stall happens

**Comment by Valgorn** [comment]
So I found out what the issue is for me, apparently the arc furnace stalls at world load when it tries to make a recycling recipe for armor that already smelts into something. Disabling it allows the world to load in as normal.

**Comment by mindforger** [comment]
this brings up memories :D good ol times when the squeezer brought the world to a halt :D .. and by halt i mean halt .. not stuck, nt crash .. just beeing rpetty but not ticking at all

**Comment by BluSunrize** [comment]
I'll need to look into that profiler again then. I was pretty sure I gave every while loop a timeout...

**Comment by cobra** [comment]
@Valgorn what mods are involved in that armor smelting recipe?

**Comment by malte0811** [comment]
I have added debug output, @Valgorn please use [this](https://www.dropbox.com/s/88xgk3fh5sdi4ld/ImmersiveEngineering-0.6.2_M2.jar?dl=0) version once, it should not fix anything (the only real change i made was to cut it down to use no more than one thread, for easier understanding of the log). When loading a world, it is going to open a small window telling you to kill minecraft 10 seconds after CLOSING that dialog. During these 10 seconds (took about 1 1/4 seconds in my dev enviroment, 10 seconds should be plenty) it will produce a ton of log, please upload that log to pastebin or gist (I think gist can work with larger files).

**Comment by Valgorn** [comment]
https://gist.github.com/Valgorn/9ae2d7ee66463e3c9575 heres what is spit out.

**Comment by cobra** [comment]
What is "jerrysExtremeEquipment"? I can't find anything useful for that. Do you have a link to that mod?

**Comment by malte0811** [comment]
From the log i guess that the alghorithm isn't stuck, it's just extremly slow. I guess the stackMatchesObject calls are at fault, I'll try profiling that later today. Caching the results of isValidForRecycling may help

**Comment by cobra** [comment]
it's not even THAT slow, the entire log spam is only three seconds. 22k recipes is still a lot.

**Comment by malte0811** [comment]
I expected the log to be 10 seconds worth of log since i told him to wait 10 seconds. Yes, given that the log lasts only 3 seconds, that performance improvement isnt too necessary.
@Valgorn please upload the full log (or the last 7 seconds of it) since the part of the log we have means that either you didnt wait for 10 seconds or the log is incomplete. Cobra is right, 22k recipes is a lot, but the except of the log we have is perfectly normal. If the remaining log is to large even for gist, try uploading the log file to dropbox or some other way of sharing general files.

**Comment by cobra** [comment]
Splitting the log into multiple files and uploading them into a single gist would also be okay.

**Comment by Valgorn** [comment]
https://gist.github.com/Valgorn/01949f00b33e8b9b9997 it was a bit to large but i noticed a loop happening in the background.

**Comment by cobra** [comment]
@Valgorn could you please tell us where you got that jerrysExtremeEquipment mod from? Nobody knows anything about it and I can't get google to find me anything about that either. Debugging this will be A LOT easier when we have this mod.

**Comment by BluSunrize** [comment]
I'm closing this issue because the original poster seems to show no interest in helping us resolve this.
