### ISSUE TITLE
Silo/AE conflict

### ISSUE THREAD

**Issue by 1skandar** [BluSunrize/ImmersiveEngineering#678]
Built a silo for cobblestone storage, placing storage buses on top (insert) and bottom (extract). Works great, AE can see and pull cobblestone just fine. However, *storing* anything isn't working, the items just vanish when placed into the AE system. Worse, because I wanted to be sure cobblestone would go into the silo preferentially I set the insert storage bus to a high priority. Which, since the silo could only hold one item, should have meant that it would try grabbing only cobblestone. Instead EVERYTHING put into the AE system was being grabbed to be inserted into the silo....and also vanishing.

**Comment by 1skandar** [comment]
And, as a note, apparently the book is wrong. It says items must be input through the top and extracted through the bottom. Apparently an AE storage bus can both extract AND insert through the bottom. This restores the silo to correct behavior of actually storing items, only storing the correct items, and not actually eating anything and everything put into the AE system.

Oh, another minor bug: the silo does NOT update its inventory displayed on the side when items are stored/extracted by an AE system.

**Comment by BluSunrize** [comment]
I blame that stupid IDeepStorage interface from MFR .-.
But I'll look into it. Thanks for the report.

**Comment by PrincessRTFM** [comment]
Similar problem with Logistics Pipes - I ran a basic logistics pipe to the top and set it up to sink the item I wanted to store, and the items would route properly and seem to enter the silo, but the silo would not actually store them. I had to put a hopper on top of the silo to work around it. I'm guessing that most non-vanilla methods of putting items into the silo will have the same problem.

**Comment by malte0811** [comment]
fixed. Will include the fix in the PR regarding speedloaders
