### ISSUE TITLE
[Request] Config option(s) for mineral veins

### ISSUE THREAD

**Issue by PrincessRTFM** [BluSunrize/ImmersiveEngineering#680]
I just started playing with the core sampler and bucket wheel excavator, and while I like the features, I'd really appreciate it if there were a way to set the chance of a mineral vein being detected in a chunk, or a command to reset a chunk so a new core sample can be taken (if that's even possible, I don't know how you're handling that). It would also be cool if players could configure the probability of each type of vein.

**Comment by mindforger** [comment]
you can use minetweaker to achive this :) but currently there is a wiki missing for that :(
syntax is pretty simple
'mods.immersiveengineering.Excavator.removeMineral('Platinum');'
to remove the default platinum vein

'val myGravelOreDict = <ore:myGravelOreDict >;
myGravelOreDict .add(<minecraft:gravel>);'
this makes not ore dicted blocks ore dicted to that particular name

'mods.immersiveengineering.Excavator.addMineral('Redstone', 100, 0, ["cobblestone","stone","myGravelOreDict","oreRedstone","oreChargedCertusQuartz"] ,[55,20,10,14.5,0.5],[1],false);'

the first string is the name of the vein 

the second number is the weight of the vein, the higher it is, the more often you will find it (no fractional number allowed)

the third is the failchance of the vein to bring up an empty shovel this is 1.0 for 100% and 0.01 for 1%
(advice from BluSunrize, the global failchance in the config works in parallel, if either the global OR the vein failchance hits you it ends in an emtpy shovel, so it somewhat adds up)

the fourth and fifth are 2 arrays depending on each other, the fourth contains the oreDict Name without "ore:" in front, the fifth contains according to the order of the other the chances for the ore (like the fail chance)

the sixth and seventh are optional you do not need to specify them, the sixth is an array of dimension numbers, the seventh specifys "true" if the list is a blacklist or "false" if it is a whitelist

**Comment by BluSunrize** [comment]
The wiki for that very much exists:

http://minetweaker3.powerofbytes.com/wiki/Mods:Immersive_Engineering_Support

And as I've sated multiple times, global fail chance and vein specific one are handled completely separately.

And since the Minetweaker integration exists, I will not add config options for it.
Config is even messier.

**Comment by mindforger** [comment]
i must have missed that update sorry :P

**Comment by PrincessRTFM** [comment]
Whoops, I missed that too. In that case, is there any way for me to see what vein names are currently registered? Not the contents, the registration name that you'd have to pass to .remove() in minetweaker.

**Comment by BluSunrize** [comment]
there's a command for that =P
/ie mineral list

**Comment by PrincessRTFM** [comment]
Thanks!
