### ISSUE TITLE
[Utility Mod] Connection Rendering as a separate mod 

### ISSUE THREAD

**Issue by Tarig0** [BluSunrize/ImmersiveEngineering#684]
Hey Blu

I have been looking for code that will be able to render connections between two TEs, without using entities as Botania does. Your code looks to be exactly what I am looking for, since I'll basically be copying your code, I would rather be dependent on a utility mod version of your connection code rather than steal/plagiarize. 

If you don't want to split off the connection code into a utility mod, will it be alright if I copy it into my own mod.

**Comment by BluSunrize** [comment]
Wait, you basically want to copy the wires from IE? Just the connection mapping or the rendering too?

**Comment by Tarig0** [comment]
renderAttachedConnections onward.

**Comment by Tarig0** [comment]
ah I see what you mean, I would rather inject my own connection mapping handler, or at least inject the function call to get connections.

My connections will be stored on the Tile Entity instead of in the worldmap

**Comment by BluSunrize** [comment]
To be honest, I don't feel so great about it. The curving wires are one of IE's defining features, and one that took a /lot/ of time to develop. Could you give me an outlook as to what you want to create with it? Because simply making another powerline mod with the same renderbase feels a little like a knockoff, tbh.

**Comment by Tarig0** [comment]
The mod I am trying to add this to is a transportation mod, with a essentially Wonka elevator that can traverse through a tree of waypoints/stops. These are not meant to be powerlines only visual representation that block 0 is connected to  block 1,(0-0-0),(0-1-0) and block 1 is connected to block 2.

https://www.youtube.com/watch?v=h37xaw1cCKs (current version of DT)

**Comment by BluSunrize** [comment]
hrrm. I guess, go ahead. Credit where it's due, of course
