### ISSUE TITLE
[FATAL] Chemthrower + lava IAE

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#688]
When the Chemical thrower is loaded with vanilla lava and fired at a living entity, upon projectile contact the game crashes with an Illegal Access Error. Worse yet, upon attempting to reload the world the crash occured on, the same IAE occurs causing the client to crash.

[crashlog](https://gist.github.com/theunkn0wn1/5ee1c449bd23309f56bf)

IE build 5d32377

Edit: also appears to occur with Blazing pyrothium :/

**Comment by cobra** [comment]
Your build setup is probably broken, BluSunrize added an access transformer. I wonder how you could build that. Rerun gradle setup<whatever you picked>Workspace.

**Comment by BluSunrize** [comment]
Yeah, there's an access transformer for it.

**Comment by theunkn0wn1** [comment]
Requesting this to be re-opened. managed to reproduce after rebuilding IE with that Access transformer (ran `gradle setupCIWorkspace` before rebuilding with ae1d377 as the latest pulled commit)

However, the means to trigger the IAE are a little different. I loaded a chemical thrower with a flameable fluid such as BioDiesel, turned on the pilot light, and sprayed the fluid at a living entity.

**Comment by BluSunrize** [comment]
It's your workspace. The access transformer works. Try setupDecompWorkspace
