### ISSUE TITLE
[minor] Chemthrower particles are... flamable...

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#689]
Loaded the Chemical thrower with water and fired said Chemical thrower at fire to see what happened. Turnes out that water burns!

![image](https://cloud.githubusercontent.com/assets/3110986/11328247/687452f4-913b-11e5-9f76-deee0892ef57.png)

IE build 5d32377

**Comment by BluSunrize** [comment]
Right, I'll need to add a check for that.
