### ISSUE TITLE
Chemical thrower inefficiencies

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#690]
Something I have noticed during my testing: The chemical thrower is horrible inefficient as a flamethrower (or lavathrower or whatever...)

Continual spray of fluid can drain the tank in a matter of seconds, yet **burst-fire lasts greatly longer** and does **more damage**

See https://youtu.be/dGMiMzopo7c

IE build 5d32377

**Comment by BluSunrize** [comment]
Kinda intentional? Why would you autofire it? Burst fire is always a sensible choice!

**Comment by theunkn0wn1** [comment]
Because fire burns. So if fire (heat) burns and does damage, why doesn't
more fire cause more damage?

Unlike with kinetic weaponry, do firing in burst should make little to no
difference in functionality. In the end, the same amount of fluid is
expended, regardless of exactly how the thing is used. It just does not
make sense that the target becomes immune for, based on observation, approx
1 second before it can be hit again. If you don't intend on the device
being used as a flamethrower, please don't make it act as one.

**Comment by BluSunrize** [comment]
You do realize that Minecraft has an invulnerability timer on entities, right? Now I'm already modifying it slightly. Simple resetting it (to emulate constant damage) results in /instant kill/ both with continuous and burstfire.
This isn't just about making the item behave like a realistic flamethrower, this is also a question of delicate balance.

**Comment by theunkn0wn1** [comment]
I suspected such a timer existed, though experienced damage more constant
then what we have now, perhaps by halving the timer rather than resetting
it would lead to better results?

A different solution is to limit the firing rate of the chemthrower based
on the viscosity of the loaded fluid so thicker fluids such as lava would
expel slower than fluids like water? By limiting the rate of discharge,
this would offset for the invulin timer as well as increase efficiency of
the device.
