### ISSUE TITLE
[Suggestion] additional Chemthrower abilities

### ISSUE THREAD

**Issue by mindforger** [BluSunrize/ImmersiveEngineering#692]
i dunno if the ChemThrower yet is able to achive something like this, but how about some effects map-able to user defined liquids:

-bonemeal effect (when using some liquid form of bonemeal ... no idea yet which mod adds something like this, but you could probably use sewage from MFR)
-tick rate increasing (probably at a definable rate like the "normal" rate of a watering can when using water and an increased rate like the advanced watering can when using MFR Sewage)
-smelting existing blocks into smelted counterpart when using lava (makes lava in the chem thrower a semi usefull but also dangerous tool)
-<agricraft compat> weed ex effect ... still would need some implementation of a fluid for that

**Comment by BluSunrize** [comment]
Bonemeal: Only if you present me with a mod that has a proper fluid, sewage doesn't count
Water: Probably doable, I'll look into it
Lava: Nah, I don't like that idea
Weed Ex: I think Greg has the fluid for it, I'll look into it.

**Comment by mindforger** [comment]
forestry has a growth medium that utilizes bonemeal .. but it's main purpose is normally for bacteria .. 
still somewhat a nice imagination to shoot a burst onto an treefarm make it (same way as normal bone meal) almost insta grow or spray it on the ground and grow grass and stuff

and the water growing ticks increase thing: you remember https://github.com/BluSunrize/ImmersiveEngineering/issues/690 this could then probably need an adjustment :P

it was the original thread where my ideas came from

lava was just an idea :) i don't like that behaviour either just mentioned it for completion as other people will suggest it i can imagine

weed ex ... yeah i wrote `<agricraft/ic2 compat>` in front of it .. but you know .. github markup munched it away .. also only an idea

**Comment by BluSunrize** [comment]
Autonomous Activator totally works. I've tried that. x3

Yeah the problem with weedex is that I'll need ot look into how IC2 and Agri do it internally .~.
