### ISSUE TITLE
[suggestion] Nixie tube RF visualizer

### ISSUE THREAD

**Issue by LogLeg** [BluSunrize/ImmersiveEngineering#693]
As I am a great fan of nixie tubes and have never seen it in mineraft, I thought it would be cool to suggest it for this mod. I think the tubes fit perfectly in the art style of IE and as a visualizer for RF usage or other things it would be pretty useful too, since there isn't anything else except for the Engineers Voltmeter. 

Here's a picture of a clock made of nixie tubes

![temp](https://cloud.githubusercontent.com/assets/15978611/11334649/b4b3677c-91d6-11e5-85bf-734ae45e328d.JPG)

Keep up the great work, its the best tech mod i've seen in a while :)

**Comment by BluSunrize** [comment]
There is an energy meter already in development, Damien is modelling+texturing it, and I'm sad to say I don't think it looks like that ^^
I'd also suggest taking that up with him =P

**Comment by mindforger** [comment]
*drool*

**Comment by LogLeg** [comment]
such a quick reply :D good to hear such things are coming atleast, even if they dont have nixie tubes :)

**Comment by BluSunrize** [comment]
closed since the Current Transformer is implemented
