### ISSUE TITLE
[suggestion] Make Item router to pull items from nearby containers

### ISSUE THREAD

**Issue by berinhardt** [BluSunrize/ImmersiveEngineering#694]
Using Immersive Engineering without any other mods lacks some kind of directional hopper, and you can only extract items from below an inventory. It would be great to be able to put a crate somewhere and let the contraption take all its contents without the wacky looks of a hopper aiming to an angled conveior belt.

**Comment by BluSunrize** [comment]
The item router won't get a pull function, since it's literally just that: a router. The option of a pulling conveyor has been brought up before, but I wasn't too interested in the idea because vanilla hoppers already do the job. Requiring them to be placed below isn't that big of an inconvenience. But 'll mull it over again.

**Comment by AEnterprise** [comment]
maybe a good solution would be a block that just passes an item intro a belt? would only be allowed to insert intro a conveyer and would basicly act as a connection block to fix the aestetic connection part?

**Comment by PrincessRTFM** [comment]
What about something similar(ish) to MFR's ejector block? On redstone rising edge, it pulls an item from the adjacent inventory and tosses it out the side with the ejector port texture. I'm no modeller, but maybe some kind of mechanical arm, if that's (reasonably) possible?

**Comment by Bitterholz** [comment]
@PrincessRTFM @BluSunrize So basicly the Mechanical Arms from Pneumaticraft?

**Comment by cobra** [comment]
Magneticraft already has factorio-style arms.

**Comment by BluSunrize** [comment]
I wouldn't know, I never looked at Magneticraft.

**Comment by jinks** [comment]
Why not go with something akin to the fluid pump.

I'm thinking of a "hatch" or "chute". (Yes, I know BC already has a chute, but who uses that any more?)
Have it work the same way as a pump. Unpowered it slowly extracts items from an inventory and puts them onto a belt, powered it goes faster.

**Comment by AEnterprise** [comment]
something like a chute for the belts could be neat

@jinks the BC chute isn't being used anymore as the MC hopper (that was based on the chute) kinda replaces it

**Comment by Bitterholz** [comment]
Id like a Chute as well! Because the Minecraft Hopper looks kinda unimmersive, is hard to control and very laggy especially when backlogged.

So jeah an IE Chute would be Gold!

**Comment by beringtom** [comment]
RIght now, hoppers are just not outputting fast enough to keep up with larger systems, would love to see and "immersive" way of fixing that :P

**Comment by MalkContent** [comment]
I'd be just happy if the router would link inventories not just for pushing items, but for drawing, too.
That way you could just put a hopper onto an item router. Probably would have other nifty applications, too.
