### ISSUE TITLE
Creosote piping.

### ISSUE THREAD

**Issue by James-T-Oudvoure** [BluSunrize/ImmersiveEngineering#695]
I'm not sure if this is intended, but using my current setup:
![2015-11-23_15 36 57](https://cloud.githubusercontent.com/assets/14304823/11350660/44572302-91f8-11e5-8522-8ead3eae49c8.png)
I am unable to extract the creosote oil from those coke ovens. The pipes auto-connect to the ovens, but the barrels are still empty.

**Comment by BluSunrize** [comment]
Pipes don't pull fluids, pumps do.
