### ISSUE TITLE
[Question] Gregtech Power Transfer

### ISSUE THREAD

**Issue by RoloEdits** [BluSunrize/ImmersiveEngineering#697]
I have a few question with regards to the way IE wires transfer GT EU. Does it automatically convert from RF to GT EU? What about IC2 EU? How does the energy packet work with the wires? I have a few more but I want to see the answer to these before I ask.

**Comment by BluSunrize** [comment]
Yes it converts automatically unless you disable it, and it turns one sending of RF into a single packet, so 1 packet per tick.

**Comment by RoloEdits** [comment]
When I connected the wires to the machines and ran RF trough them they(machines) simply disappeared, is there something I am doing wrong?

**Comment by BluSunrize** [comment]
First of all: Make it a habbit to write in your issues what version of IE you are using.
Also, IC2 and GT power are different so when you say you connected it "to machines" I need to know if IC2 or Greg.

**Comment by RoloEdits** [comment]
Yes, sorry, I am using Immersive Engineering 0.6.2, and GT 5 Unofficial gregtech-5.09.12 and connecting to GT machines.

**Comment by RoloEdits** [comment]
![bb2600517d1445774ec3b72bf96c62c6](https://cloud.githubusercontent.com/assets/12489689/11363193/1f9eef86-924d-11e5-88df-d16fc1a0a9a7.png)
![792371e55b61f02c15a8ae98985203cf](https://cloud.githubusercontent.com/assets/12489689/11363199/2344415e-924d-11e5-951a-3539df582c22.png)
 These are my GT configs

**Comment by BluSunrize** [comment]
GregTech power transfer should have been fixed to no longer draw energy. I'm not sure I can reproduce the issue. Detailed setup of the machines maybe? screenshots?

**Comment by RoloEdits** [comment]
![3b99d74a9df36a5770eee2077e45600c](https://cloud.githubusercontent.com/assets/12489689/11363247/7c143618-924d-11e5-9204-e733b5af2792.png)
![a00ec4692f5b9a4066b50f73fbe51c1d](https://cloud.githubusercontent.com/assets/12489689/11363248/7cd0c5da-924d-11e5-8b14-38d9fb1173cd.png)

**Comment by RoloEdits** [comment]
Yes, I will try to test multiple tiers as well.

**Comment by RoloEdits** [comment]
When you say "GregTech power transfer should have been fixed to no longer draw energy" what do you mean?

**Comment by BluSunrize** [comment]
Oh! Wow! Wait a second!
You said the machines disappeared? You probably gave them too much power then! xD
Gregtech stuff explodes when you give it too high of a voltage!

**Comment by RoloEdits** [comment]
I have a creative energy cell with an LV connector attached to it, and another one attached to a basic macerator, as soon as I attached the wire from the cell to the macerator it disappears.
![2015-11-24_02 07 01](https://cloud.githubusercontent.com/assets/12489689/11363730/8c046d38-9250-11e5-82b8-7cd4348c3731.png)
![2015-11-24_02 07 05](https://cloud.githubusercontent.com/assets/12489689/11363732/8d40ef8c-9250-11e5-9726-fab65c3c7bf6.png)

**Comment by RoloEdits** [comment]
I know but with RF explosions turned off wouldn't that stop that?

**Comment by RoloEdits** [comment]
You can do it through TE energy cells and ender io capacitors but that is very tedious. Is there anyway to simplify the conversion and only send as much as needed?

**Comment by BluSunrize** [comment]
did you change the configs on IE, how much wires can transfer?

**Comment by RoloEdits** [comment]
Yes
![97638b982828081646d95fa91a9a3d02](https://cloud.githubusercontent.com/assets/12489689/11363946/c1278dfa-9251-11e5-9826-147a728986d9.png)

**Comment by BluSunrize** [comment]
That's the cable rate, I meant the connectors.

**Comment by RoloEdits** [comment]
Yeah I put them all to 2147483647

**Comment by BluSunrize** [comment]
That's your problem then genius. Not only are you completely ruining IE's balance, you're also inputting vast amounts of energy into machines that can't deal with it.

Closed because user error.

**Comment by RoloEdits** [comment]
Balance? I just didn't want any bottle necks on connectors, for my own edification could you explain what these values means?

**Comment by RoloEdits** [comment]
And also, back to the original question, is it just from inputting to much RF? Would restoring the connector values fix it?

**Comment by BluSunrize** [comment]
Oh so you didn't read the manual either. Joy. Love those users.
Sarcasm aside, IE has two different values for transfer. The In- and Output values of the connectors and the transferrates of the wires. In and out determines how much you can put in per transfer operation and the transferrate of the wires determines how many inputs can me "unified" into one wire before it burns up.
And IE has a distinct concept of LV, MV and HV. You completely negated that by making the in and output values of connectors effectively infinite. Not only does this blow up GT machines, it'd also fry all your wires since they don't support that much. If you don't know what a config value is for, maybe not change it.

**Comment by Drullkus** [comment]
![http://i.imgur.com/AWeesOD.gif](http://i.imgur.com/AWeesOD.gif)

10/10 Would consider unchanging those numbers in the config files.

**Comment by RoloEdits** [comment]
Sorry for all the trouble, I did read the handbook but when I read it I interpreted in differently, that is my mistake. It makes sense to me now. Just to make sure should I set them to the transfer rate of the wires? and is this the main problem as to why the machines are blowing up? If I were to reset the values or make them the same as the wires would this solve the problem?

**Comment by BluSunrize** [comment]
I'd recommend leaving them on default. That way, IE's LV matches up best with Greg's LV.
And by default the transferrate of wires is 8 times that of connectors. Setting them to be the same would mean that you need a separate wire for everything and couldn't run a combined line for your generators.

**Comment by RoloEdits** [comment]
OK, thanks for your help once again.
