### ISSUE TITLE
Power Network Issue

### ISSUE THREAD

**Issue by aikpoppel** [BluSunrize/ImmersiveEngineering#698]
Hey Blu,
a guy on our server has found an issue. i have make a screen to show you: http://imgur.com/Lpqr9OL
you see two Thermoelectric Generator both with two water and lava source blocks an connected to a vibrant capacitor bank from ender io (tested with TE too).

The left on is connected via ender energy conduit (same with TE Ducts), the bank shows 30 RF/T Input.
The right on is connected via HV Cable and Connector (same with LV, MV), the bank shows 15 RF/T Input.

I dont know whats wrong...
Sry for my English, I hope you understand me.

EDIT: Forge 10.13.4.1558, Immersive Engineering 0.6.2

**Comment by malte0811** [comment]
Can reproduce with newest master version, looking into it now

**Comment by malte0811** [comment]
fixed, it's actually the thermoelectric generator that was sort of broken (it called `transferEnergy` for each pair of heat sources and therefore twice in this situation). I'll put this in a PR with the wire lighting in a minute

**Comment by aikpoppel** [comment]
Great thank you!
