### ISSUE TITLE
Crash when try connect wire

### ISSUE THREAD

**Issue by Udosa** [BluSunrize/ImmersiveEngineering#70]
![2015-06-24_20 14 56](https://cloud.githubusercontent.com/assets/4757891/8334031/33b45774-1aaf-11e5-98b8-e8b4743db997.png)
When i place one more ConnectorLV on Center and try connect more then 4 other connector i have this Crash
http://pastebin.com/4wVjHhHe

**Comment by BarbasTheDog** [comment]
that's the java.lang.blackMagicException.

It's what you get for making pentagrams.

**Comment by Udosa** [comment]
Lol, i dont want summon Evil

**Comment by BluSunrize** [comment]
Was unable to reproduce, but hopefully fixed for 0.2.4
Reopen if bug persists
