### ISSUE TITLE
[Performance] Hotspot in ClientUtils.calculateBlockLighting

### ISSUE THREAD

**Issue by codewarrior0** [BluSunrize/ImmersiveEngineering#701]
Performance hotspot found in `ClientUtils.calculateBlockLighting` called from `ClientUtils.renderStaticWavefrontModel` using VisualVM. 

IE version is 0.6.2, Minecraft 1.7.10 on 64-bit Java 8u45.

This sample scene contains 76 wiring connectors. Breaking all connectors resulted in a 40% increase in FPS, or a 30% decrease in frame time:

![image](https://cloud.githubusercontent.com/assets/307683/11407140/e8a512d6-9354-11e5-9373-8491dee5484c.png)

Call tree:

![image](https://cloud.githubusercontent.com/assets/307683/11407151/f9086574-9354-11e5-9e70-9bfe337055d9.png)

Backtraces:

![image](https://cloud.githubusercontent.com/assets/307683/11407159/0774c4a4-9355-11e5-8b94-0db3d2aeb0e5.png)

Hot spots:

![image](https://cloud.githubusercontent.com/assets/307683/11407171/18a5ea50-9355-11e5-82df-14460e38b3e3.png)

I would try moving the cache [`HashMap<String,BlockLightingInfo> light`](HashMap<String,BlockLightingInfo> light) to the top level of the `renderStaticWavefrontModel` method and changing it to be keyed on (side, vertex.x, vertex.y, vertex.z) instead of (vertex.x, vertex.y, vertex.z), so it doesn't have to be reset for each face in the model.

**Comment by mindforger** [comment]
this could potentially decrease garbage collecting by a huge amount .. every new discards the old hasmap .. but i am yet unsure if it is beeing recycled in any way ...

**Comment by BluSunrize** [comment]
This might be quite different now since my lighting calc changed. Feel free to do new tests.

**Comment by cobra** [comment]
I can't see anything suspicious now, running 17f3470d51aa6af258e1e1c9812d431f2e28a5fd. The first IE entry in the hotspots view is ArcFurnaceRecipe.matches() - with 0% CPU time. I did the profiling in debug mode with my test world (containing everything from IE) with two 7x7 grids of MV connectors all wired up 1:1 (98 connectors, 49 connections) in front of me.
I did not yet try to reproduce the original report with an older version, so I can't confirm 100% that this is gone now, but I'm fairly certain it is.

**Comment by codewarrior0** [comment]
The setup was in a busy part of my base. In particular, I had a multiblock Capacitor Bank from EnderIO with a comparator measuring its charge level, in order to send excess RF to a IC2 Mass Fabricator. So there were a lot of chunk updates going on.

I created a new test world like yours with 100 connectors and didn't observe any IE hotspots. Then, I added a redstone subtractor-clock in the same chunk as the connectors and noticed the FPS drop immediately. The FPS readout only dropped from 60 to 50, but the game felt tangibly laggy.

**Comment by BluSunrize** [comment]
So redstone causes more lag that IE. I can live with that.

**Comment by malte0811** [comment]
Nope. He uses redstone to trigger chunk updates. I did the same thing when testing this, got 50fps in a chunk with a clock and 64 connectors and 60 fps in a chunk with just a clock. The clock is necessary since you are rendering the connectors as isbrh or whatever it is called and therefore only rerender on chunk updates.

**Comment by cobra** [comment]
Okay, triggering block updates is something completely different. I added fast self-resetting piston clock spamming block updates - 10.8% of the CPU time is spent on this method.
Screenshot of visualvm for your pleasure:
![](https://cloud.githubusercontent.com/assets/163331/11475570/5fccfbe4-977e-11e5-8c1a-79115fb8bdc0.png)

**Comment by BluSunrize** [comment]
Well yeah, DUH.
Btu that's why it's ISRBH. they dont't update unless the chunk does a renderupdate. which is rare unless you're stupid enough to setup those clocks in survival >_>

**Comment by codewarrior0** [comment]
Connector performance is not noticeably better in 0.6.4.

Isn't there anything else you can do about this? `calculateBlockLighting` by itself seems to weigh as much as the ISBRH rendering for every other block in the area.
