### ISSUE TITLE
Coke oven and Blast Furnace GUI broken.

### ISSUE THREAD

**Issue by SuperKael** [BluSunrize/ImmersiveEngineering#703]
The GUI for the coke oven and blast furnace is bugged, the item slots and creosote tank on the coke oven don't render their contents. additionally, the progress icon doesn't show. I am playing on TechNodeFirmaCraft, in case that matters.

Steps to reproduce: Simply put anything inside a coke oven or blast furnace. TechNodeFirmaCraft may be required.

My idea: I have done a little bit of modding, and this looks like it is probably a client-server problem. additionally, I might note that the WAILA mod correctly tells how much creosote is in the coke oven.

There is coke in the output slot, but it doesn't show:
![2015-11-26_11 58 37](https://cloud.githubusercontent.com/assets/10406707/11428009/5f7e4aea-9435-11e5-8dd1-7f48e98f9171.png)

I click it and it becomes visible, and I can move it to my inventory:
![2015-11-26_11 58 44](https://cloud.githubusercontent.com/assets/10406707/11428010/5f8540a2-9435-11e5-9f76-ba2db70d2112.png)

There is steel in the output slot, but it doesn't show:
![2015-11-26_11 58 52](https://cloud.githubusercontent.com/assets/10406707/11428011/5f8722aa-9435-11e5-8ef8-bde19f0bc1a8.png)

I click it and it becomes visible, and I can move it to my inventory:
![2015-11-26_11 58 54](https://cloud.githubusercontent.com/assets/10406707/11428012/5f8bccba-9435-11e5-98a9-ca1e2787fd28.png)

The creosote tank says it's empty:
![2015-11-26_12 03 18](https://cloud.githubusercontent.com/assets/10406707/11428068/afeb14fe-9435-11e5-8d28-2b89e562c5cb.png)

I put in a bucket:
![2015-11-26_12 03 08](https://cloud.githubusercontent.com/assets/10406707/11428085/ce07713a-9435-11e5-8202-a913dabcbd48.png)

The bucket dissapears:
![2015-11-26_12 03 12](https://cloud.githubusercontent.com/assets/10406707/11428082/c8c4d8ca-9435-11e5-973a-25ff2c57e518.png)

I click the bottom slot and I get a creosote bucket:
![2015-11-26_12 03 14](https://cloud.githubusercontent.com/assets/10406707/11428088/dcb4ee92-9435-11e5-9f70-61333adae0b9.png)

**Comment by malte0811** [comment]
According to its ATLauncher page, your pack contains Optifine.  Please try removing it since optifine does strange things to rendering. The coke oven works (on a dedicated server) with the modpack i use, so it's not a general sync problem.

**Comment by SuperKael** [comment]
after reloading my game a few times for unrelated reasons, suddenly everything works...  I don't even know. anyways, can confirm works ok with Optifine though!
