### ISSUE TITLE
[Bug] FakeLights from the floodlight being washed away by water

### ISSUE THREAD

**Issue by LogLeg** [BluSunrize/ImmersiveEngineering#704]
The fake lights created by the floodlight get washed away apparently. I aimed it at my farm and when I went to harvest it, the lights were also harvested lol. I was able to pick them up and even place them on a wall, where they would then emit light. 

![ie bug](https://cloud.githubusercontent.com/assets/15978611/11429015/2cd1560e-9472-11e5-8698-fe05e943846e.png)

I was able to recreate the bug as shown down below.

![ie bug2](https://cloud.githubusercontent.com/assets/15978611/11429074/00c98ddc-9473-11e5-8d3e-8858d6c8b839.png)

![ie bug3](https://cloud.githubusercontent.com/assets/15978611/11429083/1aca45dc-9473-11e5-916a-5a4f80b256d9.png)

**Comment by BluSunrize** [comment]
Already fixed.
