### ISSUE TITLE
HV Transformer attached on a Wooden Post

### ISSUE THREAD

**Issue by korti11** [BluSunrize/ImmersiveEngineering#71]
If you attache a HV Transformer on a Wooden Post, the model has not the right bounding box.
![2015-06-24_18 22 37](https://cloud.githubusercontent.com/assets/5838137/8335538/9b62715a-1a9e-11e5-97b3-5f4f4cb56cc2.png)

**Comment by BluSunrize** [comment]
HV transformers shouldn't even go on poles. Thanks for the info.

**Comment by BluSunrize** [comment]
Fixed in the next release
