### ISSUE TITLE
[Request] Allow Excavator Minetweaker support to specify qty

### ISSUE THREAD

**Issue by Haggle1996** [BluSunrize/ImmersiveEngineering#710]
With minetweaker scripts, I would like to be able to specify a quantity. For example,

mods.immersiveengineering.Excavator.addMineral("Redstone", 100, 0, ["dustRedstone * 7"], [100], [0], false);

Even better, would be allow me a range of quantity, e.g., 4-9 dust. I can hack this by adding dustRedstone multiple times, with a chance for each, but then the display in the book is off.

**Comment by BluSunrize** [comment]
Nope. The Excavator mines ores, not redstone dust. Quantities are not intended and would be a hassle to handle because the Excavator's internals are purely built with strings as well.
