### ISSUE TITLE
Chemthrower large tank

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#711]
If the Chemthrower was filled with any valid fluid whilst the "large tank" upgrade was installed and afterward the upgrade removed, the chemthrower retains the fluid and "breaks" the fill meter.
![image](https://cloud.githubusercontent.com/assets/3110986/11449515/96af950c-952d-11e5-927c-aa9013d4ab03.png)
![image](https://cloud.githubusercontent.com/assets/3110986/11449518/a393a646-952d-11e5-9e0d-211b72305dc9.png)
![image](https://cloud.githubusercontent.com/assets/3110986/11449521/b96465d2-952d-11e5-9061-25490a18da1b.png)

IE build 17f3470

**Comment by BluSunrize** [comment]
Nicely spotted, will fix
