### ISSUE TITLE
[0.6.2] Startup server crash in IE dealing with minetweaker

### ISSUE THREAD

**Issue by lashtear** [BluSunrize/ImmersiveEngineering#712]
See http://openeye.openmods.info/crashes/7bb91e602216e5eb549678cb0a0cae7b ... quick summary:

```
java.lang.NoSuchMethodError: minetweaker.MineTweakerImplementationAPI.onPostReload(Lminetweaker/util/IEventHandler;)Lminetweaker/api/event/IEventHandle;
    at blusunrize.immersiveengineering.common.util.compat.minetweaker.MTHelper.postInit(MTHelper.java:47)
```

The set of mods and all versions are included in that; can provide more logs via a gist if that would help.

Encountered this wen updating an existing modpack (forge update, IE update, etc); removing minetweaker+modtweaker got things working again, but that can be kinda a severe step to take.  Running with minetweaker and no change scripts did not work, but others seem to be using IE with minetweaker.  Are you depending on a newer version of it?  The latest minetweaker I see in 3.0.9C.

**Comment by cobra** [comment]
Please update Minetweaker to 3.0.10b or later.

**Comment by Kazekai** [comment]
Wow. I thought I did update it but turns out I put it in the wrong folder. That was embarrassing.

Sorry about that, thanks for responding.
