### ISSUE TITLE
[Suggestion] Change recipe handling of Arc Furnace.

### ISSUE THREAD

**Issue by OneEyeMaker** [BluSunrize/ImmersiveEngineering#713]
Hello.
I have suggestion for recipe handling of Arc Furnace. For now if alloying recipe contains some items of one type, these items should be registered in recipe separately (as different items).
For example:``` Tin + additives: [Copper + Copper + Copper] = 4 * Bronze``` (instead of ```Tin + [3 * Copper] = 4 * Bronze```).
If I register recipe (with MineTweaker, for example) using stack with specified amount of items, (```Ingot1 + [2 * Ingot2 + 3 * Ingot3] = 6 * Ingot4```), it doesn't work properly in Arc Furnace: this machine consumes one item of each type (```Ingot1 + [Ingot2 + Ingot3] = 6 * Ingot4``` instead of ```Ingot1 + [2 * Ingot2 + 3 * Ingot3] = 6 * Ingot4```).
Please, change this machanics in recipe handler of Arc Furnace. That allows to register recipes with big amount of items but limited amount of types of items (```Silver + [2 * Tin + Platinum + 4 * Ender Pearl + 2 * Pyrotheum dust] = 4 * Enderium]```, for example).

//And add ```@Optional String recipeType``` [here](https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/util/compat/minetweaker/ArcFurnace.java#L19) to specify type of recipe (regular/ore processing/alloying/recycling).

P. S. Sorry for my English, I'm from Russia.

**Comment by BluSunrize** [comment]
No it doesn't?
I literally just used the script
ArcFurnace.addRecipe(<minecraft:dragon_egg>, <minecraft:obsidian>, null, 100, 512, [<minecraft:ender_pearl>*4]);
And it consumed 4 pearls and the obsidian.

Also, keep in mind that the Furnace only has enough slots to support 4 different additives.

**Comment by OneEyeMaker** [comment]
Sorry, my bad. (I confused IOreDictionaryEntry and IItemStack, and tried to register recipe with <ore:oreName> * N instead of [<ore:oreName>, ] N times).

**Comment by BluSunrize** [comment]
Yeah, OreDict can't support amounts. Minetweaker is not designed to.
