### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by DoctahFrank** [BluSunrize/ImmersiveEngineering#714]
Every time I try putting Immersive Engineering into my modpack, any worlds immediately crash upon loading:

http://pastebin.com/J1PxxFH0

I just updated forge to the most recent recommended version and it didn't help, any ideas?

**Comment by malte0811** [comment]
Update IE, #587, #630

**Comment by DoctahFrank** [comment]
Awesome, that worked. Thanks!
