### ISSUE TITLE
[Mod Interaction?] Some more disappearing wires

### ISSUE THREAD

**Issue by jinks** [BluSunrize/ImmersiveEngineering#716]
I have a "narrow" case of wires disappearing on server restarts.

While wires in the overworld are fine over server restarts all wires in my several RFTools dimensions disappear.

I'm not sure if RFTools uses a custom save handler, but it **does** enumerate all it's dimensions on start and shutdown so there might be something funky it does that interferes with IE wires saving and loading properly.

**Comment by malte0811** [comment]
What version are you using? because i remember fixing that bug some time ago

**Comment by BluSunrize** [comment]
yeah RFTools problems should be fixed.
