### ISSUE TITLE
Coke Oven will not accept charcoal

### ISSUE THREAD

**Issue by Zsashas** [BluSunrize/ImmersiveEngineering#717]
Is this intended?

Also, is there a way to change the recipes? In my pack, Acacia and Dark Oak logs smelt into 4 charcoal instead of 1 (other logs have varying amounts). But in the Coke Oven, still only one.

**Comment by theunkn0wn1** [comment]
That is intentional. If you want to change the recipe, do so via MineTweaker. The coke oven by design will not accept charcoal.

**Comment by Zsashas** [comment]
How can I change Coke Oven recipes with MineTweaker?

**Comment by BluSunrize** [comment]
Try google.
