### ISSUE TITLE
Pump not working

### ISSUE THREAD

**Issue by Zsashas** [BluSunrize/ImmersiveEngineering#718]
I have the side touching the tank set to blue, an the side on the pipe set to orange. Tried with and without power, with and without redstone signal, items constantly cycling through the Bottler...nothing makes it transfer Creosote.

![2015-11-29_11 33 52](https://cloud.githubusercontent.com/assets/6917535/11460018/19e6735c-9699-11e5-9e31-6eae67e2b4bb.png)
![2015-11-29_12 56 35](https://cloud.githubusercontent.com/assets/6917535/11460017/19e5099a-9699-11e5-972e-5a149cc76490.png)

**Comment by BluSunrize** [comment]
Because the Bottling Machine is bugged in the version that you have. This is fixed already.
as an intermediary, Thermal Dynamics will work, because they just disregard any check for insertion validity.

**Comment by Zsashas** [comment]
Ah...unfortunately I don't have any CoFH mods. Is there another way to fill items with Creosote?

**Comment by BluSunrize** [comment]
click the tank with a glass bottle?

**Comment by Zsashas** [comment]
The item I am trying to fill is the Impulse Boots from Arcane Engineering. They apparently require Creosote but I couldn't figure out how to fill them.

**Comment by BluSunrize** [comment]
I find that mod absolutely terrible, and I guess I can't help you then. Wait for IE to update or find a different way of filling containers?

**Comment by Zsashas** [comment]
Alright, fair enough. time to delve further into NEI...
