### ISSUE TITLE
[Potential bug] HV Wire Connectors converting to EU (Conversion too high)

### ISSUE THREAD

**Issue by koalalord9999** [BluSunrize/ImmersiveEngineering#721]
This may have been posted before, not too sure, but here it goes.

Version: ImmersiveEngineering-0.5.4
Pack: FTB Infinity Evolved 2.1.3

I have 5 HV Wire Connectors on my Molecular Transformer, connected directly to an Energy Pylon from Draconic Evolution (Transports infinite rf/t) with 5 more HV Wire Connectors, bridged obviously with HV Wires, and it says that the Molecular Transformer is receiving 8166 eu/t when it should only be just over 5k eu/t based on wiki conversion rates. So, it's draining 32k rf/t with 5 cables, which max out should be only 20k rf/t. Is this some kind of calculation error on the wires? Or am I just going crazy thinking 1024 x 5 is 5k, not 8k? xD

**Comment by koalalord9999** [comment]
PS I also have 8 Mass Fabricators connected in the same way (5 HV cables on a pylon 5 on Mass Fab) and I have no idea how much it's pulling out, but 8 mass fabs is pulling out way more power then I'm producing (Almost 1m rf/t) and I know 40x4k is not even close to 1 million. lol

**Comment by BluSunrize** [comment]
First off: This is FTB Infinity. They apparently incapable of updating their mods, IE 0.5.4 is woefully outdated.
Secondly: This is FTB Infinity. They change every goddamn config known to man.

So
A) I don't do support on an IE version as old as that. Chances are whatever you are encountering was fixed months ago.
B) I'm not liable if someone fucked up the configs.

**Comment by bookerthegeek** [comment]
FYI update for infinity etc is 2dec. They are updating to the latest and yeah it already got fixed.

@blusunrize amazing mod! Look forward to playing with the new toys.
