### ISSUE TITLE
Excavator Support for TFC Ores

### ISSUE THREAD

**Issue by dexman545** [BluSunrize/ImmersiveEngineering#722]
Would it be possible to have the excavator detect Terrafirmacraft ore veins and mine them out? Currently, the excavator seems to only produce IE/vanilla ores, which cannot be used with TFC by default.

Thank you, 
Dex

**Comment by bookerthegeek** [comment]
You can use the modtweaker scripts to remove all the current veins and create ones that produce the TFC ores.

**Comment by BluSunrize** [comment]
If TFC can't use vanilla ores at all, a Minetweaker script is indeed your best bet. I don't see myself writing a compat module to completely replace Excavator veins with whatever TFC needs.

**Comment by bookerthegeek** [comment]
Also, I believe he wanted the in world ores mined out vs your hidden veins.
