### ISSUE TITLE
[Enhancement] Dirt and Gravel Upgrade for Mining Drill

### ISSUE THREAD

**Issue by mikeloeven** [BluSunrize/ImmersiveEngineering#724]
The mining drill lacks a upgrade for handling dirt and gravel

**Comment by BluSunrize** [comment]
It doesn't need one? It works on dirt by default. It's a giant drill, it really doesn't care about materials. xD

**Comment by mikeloeven** [comment]
Then i must have encountered a bug because it was not mining dirt blocks at its normal rate and would only remove one at a time instead of the 3x3

**Comment by BluSunrize** [comment]
Grass is the only one that it wouldn't work on, because I forgot to add it to the list. But dirt and gravel should (theoreticaly) work...
