### ISSUE TITLE
Crash with MineTweaker

### ISSUE THREAD

**Issue by Kazekai** [BluSunrize/ImmersiveEngineering#726]
http://pastebin.com/4yE0Piy6 crash log
http://www.mediafire.com/view/55x0m83proc5q3u/multimc%20console%20log.txt multiMC console log

It only happens when these 2 mods are on a server together, running latest versions of both. Can't find anything about it elsewhere.

**Comment by cobra** [comment]
update to minetweaker 3.0.10b

**Comment by cobra** [comment]
Also: [searching for the relevant part of the crash log](https://github.com/BluSunrize/ImmersiveEngineering/search?q=minetweaker.MineTweakerImplementationAPI.onPostReload%28Lminetweaker%2Futil%2FIEventHandler%3B%29Lminetweaker%2Fapi%2Fevent%2FIEventHandle%3B&type=Issues&utf8=%E2%9C%93) does return other issues.
