### ISSUE TITLE
[Enhancement] Add support for heating Refinery from PneumaticCraft

### ISSUE THREAD

**Issue by miuirussia** [BluSunrize/ImmersiveEngineering#728]
Add support for heating Refinery from PneumaticCraft with External Heater
![2015-12-03_12 45 06](https://cloud.githubusercontent.com/assets/1270028/11557103/faa5523a-99bb-11e5-885e-70ce0841f6c0.png)

**Comment by BluSunrize** [comment]
1) There's this nice little word called "please".
2) MineMaarten's heat system is far more complex than a simple furnace, which is why I didn't do this.

**Comment by shobu9** [comment]
"Please, add support for heating Refinery from PneumaticCraft with External Heater"
He did say please :P

**Comment by miuirussia** [comment]
☺️

**Comment by BluSunrize** [comment]
No, he didn't. He edited his post. I have the original email, I'm not stupid.
