### ISSUE TITLE
[request] Make generators pipe compatible

### ISSUE THREAD

**Issue by medsal15** [BluSunrize/ImmersiveEngineering#73]
I found 1 generator compatible with BC kinesis pipes. Can you make the same for other generators?

**Comment by BluSunrize** [comment]
You'd help me a lot if you told me which of the generators works with it ;)

**Comment by medsal15** [comment]
The lightning generator. I'm not even sure it works but it connects with BC pipes.

**Comment by AEnterprise** [comment]
for compat with BC kinesis pipes: the pipes will automaticly connect if it detects the RF interface but will not pull on it's own, the generator would need to send the energy to the pipe (it's internal buffer)

**Comment by BluSunrize** [comment]
Yeah I talked to asie, I know how to fix it.

**Comment by BluSunrize** [comment]
Feature added for coming releases

**Comment by AEnterprise** [comment]
i'm guessing this will also make things like EiO conduits connect?

**Comment by BluSunrize** [comment]
I'd hope so
