### ISSUE TITLE
Pump does not seem to be working with other mods

### ISSUE THREAD

**Issue by WolfieWaffle** [BluSunrize/ImmersiveEngineering#732]
I can get the pump to work fine with barrels, but it does not seem to extract from any other source. The specific things I tried it with were iron tanks from Railcraft and the steam converter from Flaxbeard's Steam Power. Sorry I don't have much info on this issue, but jut try using the pump with other mods.

**Comment by cobra** [comment]
make sure to properly configure the sides and apply a redstone signal. Sneak while using the hammer to change the side opposite of the one you're hitting. Usually: hit the front (opposite of the block you're trying to pump from) twice, sneak, hit it again once. Proof:
![](https://cloud.githubusercontent.com/assets/163331/11610505/c7d72a82-9ba4-11e5-91d6-26c056e133f0.png)

**Comment by BluSunrize** [comment]
Closed until further proof of issue is given

**Comment by WolfieWaffle** [comment]
Ok, I don't think I was applying a redstone signal. The barrels did not seem to require one so I didn't know it even had redstone support. In that case, the issue is solved.
