### ISSUE TITLE
Pipes are pretty glitchy.

### ISSUE THREAD

**Issue by tehFoxx0rz** [BluSunrize/ImmersiveEngineering#733]
Apologies if this has been reported or is known about already, I looked back through the previous pages.

Pipes have some bothersome connectivity bugs - I have this setup https://dl.dropboxusercontent.com/u/66131226/2015-12-06_13.55.34.png after detaching all the pipes not connected to an inlet/outlet.  There's a switch on the bottom block of the tank out of sight.  I then turn on the redstone to output liquid into the barrel, and this happens... https://dl.dropboxusercontent.com/u/66131226/2015-12-06_13.58.28.png https://dl.dropboxusercontent.com/u/66131226/2015-12-06_13.58.33.png .
And then even when I try to fix them, disconnecting one of the connections causes another to bug connected again!  I know it probably wouldn't make a difference to liquid transit, but it's naturally quite irksome when everything else looks so lovely!
(It's be great if pipes would only ever connect to where there are openings to begin with, but I'm not sure how simple that would be to implement, especially with the blocks with configurable openings!)

And not directly related to this bug but still a pipe glitch - placing a pipe down in certain situations (like this - https://dl.dropboxusercontent.com/u/66131226/2015-12-06_14.01.14.png ) causes it to display its connections incorrectly.  It fixes when I remove one of the connections, but when I put that connection back how it was it turns back like this.

But thanks and keep up the good work, and I'm looking forward to the exciting changes I've been hearing about for the next version!

**Comment by BluSunrize** [comment]
Which version of IE are you using?

A more intelligent connection system should be in the next release, courtesy of @cobra

**Comment by cobra** [comment]
Yeah, connections to parts not doing anything with fluids will be gone in the next release.
I don't know what's happening with the resetting connections, I didn't see this behaviour before and can't reproduce it. This should not be possible, even in older versions.

Are you using something like optifine?

**Comment by LogLeg** [comment]
I have this issue aswell, on version 0.6.2 with optifine and a lot of other mods

**Comment by tehFoxx0rz** [comment]
No Optifine, 0.6.2, though I think I saw it when pipes were first added.  I am using quite a few other mods, though I'm not sure which ones could be messing with this.  I suppose the closest type of thing to Optifine I have is Fastcraft.  It doesn't seem like a purely visual thing though because the bounding boxes for the connection elements changes appropriately as well.

Hopefully the connection system improvements should help things out though, and it sounds great either way! :D Maybe it'll even fix it, but we'll see!

**Comment by tehFoxx0rz** [comment]
So with the new pipe connectivity logic, the primary issue here seems to be resolved! Pipes are not connecting oddly and block updates don't seem to change them.

The only thing left is that the pipes still visually glitch when connected as in the last picture in the original post; above, below and on two adjacent sides. (version 0.6.5.1). https://dl.dropboxusercontent.com/u/66131226/2015-12-31_22.06.27.png

**Comment by tehFoxx0rz** [comment]
Just posting again to inform that the above issue (visual pipe glitch) is still true as of 0.7.0, just in case it got missed!
