### ISSUE TITLE
EnderIO Energy Conduits and HV Capacitor

### ISSUE THREAD

**Issue by ryanpeters74** [BluSunrize/ImmersiveEngineering#734]
I don't believe the output of energy from the HV Capacitor works with EnderIO Energy Conduits. 

When the HV Capcaitor is set as Input (orange and blue) the conduits work; when set to Output (orange and orange) the connection fails.

When using a LV Capcaitor the Input and Outputs work with the EnderIO conduits.

Verified with EnderIO capacitor banks.

**Comment by BluSunrize** [comment]
I'm not quite sure what issue you are describing. Please provide pictures and tell me which version of IE you are using

**Comment by ryanpeters74** [comment]
I got it working now. Sometimes the enderio conduit will connect to the output face and sometimes it does not. I'm yet to be able to reproduce the problem the same way more then once. I'll chalk it up to ignorance on my part. Please close the issue.

Incredible mod. Thank you for your time.

**Comment by BluSunrize** [comment]
cheers!
