### ISSUE TITLE
[medium] Skyhook documentation is unreadible

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#736]
![image](https://cloud.githubusercontent.com/assets/3110986/11648246/ed01b8bc-9d26-11e5-85f7-9f0781f8e6e6.png)
Image and title say it all.

IE build cc3c69e202664f6abdf5

EDIT: whilst I am on the subject: is the recipe for the Skyhook not fully implemented? The page shows the chemthrower recipe...

**Comment by BluSunrize** [comment]
It's not even done yet you derp. I just was way to tired to finish it at 1 am.
