### ISSUE TITLE
Rendering glitch between Crusher and Arc Furnace (?)

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#737]
For some reason, if a crusher and a Arc Furnace are formed within a certain chunk on my test world the Arc Furnace ceases to render until the crusher is destroyed. I am using no means of chunk loading or the sort in the vicinity of the chunk in question. If the Crusher is moved from its bug-inducing location the bug does not get induced while the exact location and orientation of the Arc Furnace is irrelevant.

Below are some pictures of the bug-inducing setup.
![image](https://cloud.githubusercontent.com/assets/3110986/11648401/0867004c-9d29-11e5-9aea-35f9c803d868.png)
![image](https://cloud.githubusercontent.com/assets/3110986/11648420/24a68412-9d29-11e5-8b91-b2b488625ff3.png)

The crusher farthest from the camera does not induce the bug, whist the nearer crusher does. 

this glitch began to manifest itself after I updated IE from build 7f521c5 to d16e262 but does manifest with build cc3c69e

**Comment by mindforger** [comment]
can you do me a favor:
-go to your savegame
-use https://dinnerbone.com/minecraft/tools/coordinates/ to calculate the .mca-file containing your machines and upload it somewhere for me?
-also note down the most exact coodinates of the cauldron of the furnace (this one is the master block for the structure)

there is something up with the multiblock "element position" and i am searching for more nbt files containing malicious multiblocks to get behind this XD ... the last few people did either not provide the required files or did already remove the multiblock

**Comment by theunkn0wn1** [comment]
Used the linked tool, inputted the coordinates and it outputted a .mca file, compressed that into a .7z archive and [here is the link](https://www.dropbox.com/s/8a0k3l2zcdcuu5t/mca.7z?dl=0)

If you need, I am willing to provide the world if that would help

**Comment by Bitterholz** [comment]
Hey. Got a huge FPS drop with the Arc Furnace as well. Whenever its running or not having Electrodes im down from 100 to 20 FPS.

Ill provide Chunk, .mca and coordinate Intelligence later.(Currently at University)

**Comment by Bitterholz** [comment]
Oh I forgot to mention. Placing the Arc Furnace in SMP gets me the Drops. SSP its fine, havent yet confirmed it being chunk induced. Need to place the Arc Furnace in some other chunks first.

**Comment by mindforger** [comment]
is your Arc Furnace disappearing? i don't think while reading your other issue, so would not fit this issue

i would guess some oddities with TESR render part or some renderpass issues maybe, i'll leave this to the render specialists :P

**Comment by mindforger** [comment]
okay, first analysis about the arc furnace complete
http://puu.sh/lQg25/dd20d5a33b.jpg
both are identical i amtrying out ifplacing it 1 block deep into water does anything have to do with it

**Comment by malte0811** [comment]
I thight i fixed the graphite electrode thing... i'll check the pr i made

**Comment by theunkn0wn1** [comment]
Yes, the MCA should contain the malfunctioning arc furnace.

**Comment by mindforger** [comment]
@malte0811 i derped, i used the copied folder with 0.6.2 instead of the active 0.6.4 :P will check back if it persist, see it fixed if not :P

**Comment by BluSunrize** [comment]
Fixed with Version 0.7.1.2
