### ISSUE TITLE
[Suggestion] - Upgrades on the crusher

### ISSUE THREAD

**Issue by lapin-b** [BluSunrize/ImmersiveEngineering#738]
Hello,
Playing around with the crusher, I thought it would be great to have upgrades on the crusher (speed upgrade for instance) because it's kidna "slow" espacially when you have a heavy load of ores to crush. Obiviously, the energy consumption would be higher.

Thanks
PS: _English isn't my native language and I'm still learning it, sorry for stupid misspelling._

**Comment by BluSunrize** [comment]
Has been brought up before, see:
https://github.com/BluSunrize/ImmersiveEngineering/issues/511

**Comment by XFactHD** [comment]
@lapin-b if you really need to make it faster you can crank the power consumption up in the config.
