### ISSUE TITLE
Shadow's on Stairs

### ISSUE THREAD

**Issue by Solace7** [BluSunrize/ImmersiveEngineering#739]
Shadows appear on stairs no matter where or which way they are placed.

![2015-12-06_09 31 27](https://cloud.githubusercontent.com/assets/9976088/11657550/60058b4a-9d72-11e5-9bc8-8be5a078eb08.png)

**Comment by BluSunrize** [comment]
I cannot replicate this. What version of IE are you using and what other mods are involved?
Are you using optifine?

**Comment by cobra** [comment]
Workaround: turn on smooth lighting.

**Comment by Solace7** [comment]
Latest version of IE 0.6.2, no optifine.
Smooth lightning workaround, works.

**Comment by BluSunrize** [comment]
already fixed it =P
