### ISSUE TITLE
[0.6.2] Pumps cant extract from Sheetmetal Tanks

### ISSUE THREAD

**Issue by Bitterholz** [BluSunrize/ImmersiveEngineering#740]
As the Title states:
Pumps can not extract fluids from Sheetmetal Tank Multiblocks. The only point you can Attach a Pump to is the Top since the Bottom is blocked off by the Structure and you can't rotate the Pump upside down(Wich would be really nice! Just make it rotateable arround its bottom block).
I tried every Combination:
- Pump Powered, Redstone on/off = No Extraction
-- Tank Bottom Redstone on/off = No Exctraction
- Pump Unpowered, Redstone on/off = No Extraction
-- Tank Bottom Redstone on/off = No Extraction

The Pump on the Top looks extremely nice and id love to be able to extract from there!

**Comment by BluSunrize** [comment]
The tank can autoutput, you don't need the pump for that. Just give it a redstone signal on the output block.

**Comment by Bitterholz** [comment]
Jeah but its super slow though and the pump on top is super cool :D Id just love to be able to fasten the extraction and not having to use anything but IE blocks

**Comment by BluSunrize** [comment]
Well, slow is relative. I think 144mb per tick is alright =P

**Comment by Bitterholz** [comment]
OK thats quite fast actually
