### ISSUE TITLE
Diesel Generator not working part 2: the sequel!

### ISSUE THREAD

**Issue by James-T-Oudvoure** [BluSunrize/ImmersiveEngineering#742]
Using this setup:
![2015-12-08_20 54 52](https://cloud.githubusercontent.com/assets/14304823/11675282/015c0f84-9dee-11e5-98dd-c55403168c54.png)

I am unable to make the diesel generator run.

**Comment by malte0811** [comment]
Try placing the capacitors directly on the output of the generator. If that works, this is the same as #743

**Comment by theunkn0wn1** [comment]
You need a pump extracting fluid from the barrel?

**Comment by malte0811** [comment]
I think they have auto-output when the side is marked orange

**Comment by theunkn0wn1** [comment]
If it is marked orange, I cant tell from this angle, last I checked only the bottom face could be set for auto-output ( the sheet metal tanks on 0.6.2 acted this way).  But if it is auto-exporting then your above might apply

**Comment by James-T-Oudvoure** [comment]
No, it is configured right, it took diesel out of the barrel as I was filling it. Even this setup won't work:
![2015-12-09_14 51 17](https://cloud.githubusercontent.com/assets/14304823/11698473/5762f9ec-9e84-11e5-9784-121a5d8bc139.png)

This does work:
![2015-12-09_14 52 43](https://cloud.githubusercontent.com/assets/14304823/11698515/94bc2cd2-9e84-11e5-84fe-7b6dadb4bbfd.png)

**Comment by cobra** [comment]
See #743 - solved, wait for 0.6.4 (soon)

**Comment by malte0811** [comment]
Yep, that was fixed a few hours ago, i guess @BluSunrize will release a bugfix update soon. This is, as i stated above, a duplicate, but it's not your fault, the other one was reported later.

**Comment by BluSunrize** [comment]
And tripple post. This has been fixed, I'm closing the issue, 0.6.4 will be fine.
