### ISSUE TITLE
Arc furnace suggestion + enderio alloy bug

### ISSUE THREAD

**Issue by Keridos** [BluSunrize/ImmersiveEngineering#745]
The arc furnace for me is not creating vibrant alloys with gold, redstone, glowstone, and any of the ender "powders"

And can I somehow make it faster (either ingame or via config). Did not find any way to do that until now.

Using IE 0.6.2, EnderIO 0.2.0.421_beta

**Comment by XFactHD** [comment]
You can make it faster by cranking the power consumption up in the config. Bit I really think that monster of a furnace is fast enough.

**Comment by Keridos** [comment]
For me making EnderIO alloys is about the same speed as the vanilla enderio Alloy Smelter with upgrades (which imo is really slow).

**Comment by BluSunrize** [comment]
If it's too slow,  you're not giving it enough power,  or you're really impatient.

**Comment by Keridos** [comment]
How much power does it use max? It is not in the configs btw.

**Comment by cloakable** [comment]
512RF/t per slot. So 512RF/t (1 slot) to 6144RF/t (all 12 slots)

**Comment by Keridos** [comment]
Ok I just now noticed it uses all slots simultaneously, Can we get autosplitting stacks for that maybe?

**Comment by cobra** [comment]
Already implemented for automatic inputs (hopper, dropping conveyors, any item pipes, AE2).

**Comment by BluSunrize** [comment]
Exactly. IE 0.6.4 has autosplit inputs.

**Comment by Keridos** [comment]
Okay, thanks a lot :)
