### ISSUE TITLE
[0.6.2] Wires burning out when connecting to transformers

### ISSUE THREAD

**Issue by codewarrior0** [BluSunrize/ImmersiveEngineering#748]
I have a HV transformer connected to a capacitor on the HV side. Nearby, I have a machine drained of energy with an LV connector on it. When I connect the LV wire to the transformer, it instantly burns out. 4,277 RF is transferred to the machine each time I reconnect the LV wire.

**Comment by malte0811** [comment]
Update IE, this was (afaik) fixed in 0.6.3

**Comment by codewarrior0** [comment]
After reading #743 and #746, I'm wary of updating to 0.6.3. Maybe in a few days I'll try the latest master.

**Comment by cobra** [comment]
Update to 0.6.4 once it's out, should be coming out rather soon.

**Comment by codewarrior0** [comment]
Looks like this is fixed in 0.6.4.

The machine is even drawing exactly 256RF/t from an LV connector.
