### ISSUE TITLE
Feature Suggestion: Elevator

### ISSUE THREAD

**Issue by karakufire** [BluSunrize/ImmersiveEngineering#753]
Scaffold and Wires, I can't help imagining elevator in such as construction site or factory.

**Comment by mindforger** [comment]
... on a minecart, mobile building platform *drool

**Comment by karakufire** [comment]
why command blocks... it's disable in survival...

**Comment by jinks** [comment]
I thought about suggesting an elevator myself a few days ago. I have a build that could really use a vertical mode of entry but noting in other mods is... well... immersive :)

But I was thing more of a paternoster elevator: [Wikipedia](https://en.wikipedia.org/wiki/Paternoster)

I think that would fit well with IE. Kinetic motor on top and bottom and a "belt" crafted similar to conveyors to which you can add compartments to step into.

**Comment by cobra** [comment]
You could use the skyhook for traveling up.

**Comment by BluSunrize** [comment]
^ That

Entity Movement is a bitch, I wont work on an elevator for quite some time.

**Comment by karakufire** [comment]
yep... also I guess this too hard to implement...
I'm glad if you consider my suggestion.

**Comment by shobu9** [comment]
karakufire: install pneumaticraft XD
