### ISSUE TITLE
[0.6.4] Energy Transfer Client Side Kills FPS

### ISSUE THREAD

**Issue by Bitterholz** [BluSunrize/ImmersiveEngineering#754]
Hi,
Me and my fellow Minecrafters on my Server just managed to get an Arc Furnace together.
We formed it and immediately lost ~80% FPS.
(Independant of GPU and CPU Type)
Once the Electrodes get inserted, FPS is back to normal again.

Though as soon as we started feeding it some ore, the Drop re-occures as long as the Furnace is working.
Tried rotating the Multiblock in all 4 Directions...didnt do anything about it.

Fun Fact: in SSP nothing like that happened! Im suspecting it to be either specific to SMP or Chunk based...

Additionally, the furnace doesnt Balance out its input, just as a sidenote.

**Comment by Bitterholz** [comment]
Will try moving the Arc Furnace around to other chunks and Update you on what happens. Will also revert to 0.6.2 and test again.

**Comment by mindforger** [comment]
i can not confirm yet neither SSP nor SMP, are you using optifine by chance or any other core mod?

can you profile your situation using Java VisualVM or the Java Mission Control

**Comment by Bitterholz** [comment]
Just Moved the Furnace to another Chunk, FPS decrease went from 80% to about 10%... Visual VM the client eh? I could do that jeah.

**Comment by mindforger** [comment]
nah not VMware or such, java SDK is shipping with VissualVM and since someupdate also with mission control, both can profile running java apps and determine hotspots

**Comment by Bitterholz** [comment]
Ahright, will VisualVM my Client with the Arc Furnace

**Comment by cobra** [comment]
Could you find any suspect parts so far?

**Comment by Bitterholz** [comment]
@cobra  Sadly, I couldnt identify ANYTHING that would easy catch the eye...but it seems like something be messing with fastcraft.
The following Snapshot by VisualVM of my Client shows nothing really laggy.
https://www.dropbox.com/s/wznvgp9zxol1zj8/IE_ARCFUR_FPS_SnapCPU.nps?dl=0

 Though when i put my ARC furnace on the Server in that exact spot or anywhere arround that, i get this huge 80%-ish FPS loss without noticable call spams...

**Comment by Bitterholz** [comment]
I will now place a arc furnace in that exact location in a SSP

**Comment by Bitterholz** [comment]
Nice server just got Crashed by a LV Connector NPE XD

**Comment by cobra** [comment]
#746?

**Comment by Bitterholz** [comment]
Exactly that one @cobra

**Comment by cobra** [comment]
Can you produce a laggy snapshot without fastcraft?

**Comment by Bitterholz** [comment]
Let me try that next!

**Comment by Bitterholz** [comment]
Exactly ZERO impact without fastcraft. Actually worse when looking arround!
https://www.dropbox.com/s/w2p8i1x0326ifu8/IE_ARCFUR_FPS_NOFC_SnapCPU.nps?dl=0

Its super wierd. It seems like the chunk the Furnace is in by 60% of its structure is having a problem.

**Comment by Bitterholz** [comment]
Fun fact: Another Arc Furnace placed like 2-3Chunks away is just fine and has no impact on the FPS

**Comment by cobra** [comment]
6.7% IE lighting calculation, but 14.1% agricraft block rendering. Still, nothing odd.

**Comment by Bitterholz** [comment]
guess some chunk is broken...because it happens exactly and ONLY in that position

**Comment by Bitterholz** [comment]
Can now confirm its Chunk Specific! Only happens if any part of a Multiblock is located in the chunk (15,-22)

**Comment by malte0811** [comment]
@cobra 6% for lighting would mean that something in that chunk is spamming chunk updates... Also "any part of a multiblock" doesnt make much sense since only the master should do any rendering
@bitterholz is it happening in that chunk in any world or just on that server? I'm not at my computer right now, so i can't check. If it is just on that server, what else is in that chunk? Especially stuff like redstone clocks and farms, anything causing block updates

**Comment by Bitterholz** [comment]
Is happening just in that specific Chunk and ONLY on the Server. Havent tested if it happens if i put the master Tile in another Chunk.

Yes there is an Agricraft 5x5 10-10-10-Pumpkin Farm in the Chunk, its half quarried out and BC robots are working there.

**Comment by Bitterholz** [comment]
Arround 80 Chunk Updates there

**Comment by malte0811** [comment]
This may sound like it doesnt make sense, but what are you using to power that arc furnace? If the number of chunk updates increases, it is probably our code causing them and if something is trying to insert energy into it on the client side, that could cause it.

**Comment by Bitterholz** [comment]
Using  the IE Wires running High Voltage from a Diesel gen

**Comment by XFactHD** [comment]
Could you try making a backup of the world, run it on the server and destroy the agricraft farm and then build the arc furnace? I have a big agricraft farm in the overworld and it brings my fps from 100 down to 8.

**Comment by malte0811** [comment]
Don't bother, I have fixed it and will PR the fix in a minute

**Comment by Bitterholz** [comment]
What was the cause if one may Ask?

**Comment by malte0811** [comment]
As I guessed above, energy was being transfered on the client side. This was because of commit 516a4c6425b0f80a7ae173ad1468bbc5125611b1, which is the same commit that broke all energy transfer without ic2 in 0.6.3. @BluSunrize at what time of day did you write that code? :smile:

**Comment by Bitterholz** [comment]
Thanks @malte0811 You just saved me from getting hanged by 25 people on my Server XD
Even though I allready got hanged by Blu for asking where to put the deps XD

**Comment by Bitterholz** [comment]
@malte0811 well sadly this didnt make it into 0.6.4 :(

**Comment by malte0811** [comment]
Yeah, that's why i haven't pr'ed it already. I'm now adding some sync stuff for the engineers voltmeter

**Comment by Bitterholz** [comment]
Sounds good :)
Meanwhile ill try calming the crowd XD

**Comment by malte0811** [comment]
try putting a capacitor in between the furnace and the connectors, that might help

**Comment by Bitterholz** [comment]
Will try

**Comment by Bitterholz** [comment]
@malte can you get us a compiled version of that fix :D

**Comment by malte0811** [comment]
@cobra and I are currently suspecting that my fix doesnt work, @BluSunrize will publish a build once we are done

**Comment by Bitterholz** [comment]
Damn. Don't want to put you guys into a rush but this is really gamebreaking...Hope you'll fin a fix soon. Meanwhile Fingers Crossed for you :+1:
