### ISSUE TITLE
[0.6.3]Build File v1.9 is missing the Minetweaker API

### ISSUE THREAD

**Issue by Bitterholz** [BluSunrize/ImmersiveEngineering#757]
cannot build IE locally because of a missing Minetweaker API

**Comment by BluSunrize** [comment]
You're also missing a lot of other libraries.
The saying goes: If you can't figure the dependencies out, you probably shouldn't be building it anyway.

**Comment by Bitterholz** [comment]
Figured out the dependecies, now where to put? cuz adding them to the build path in eclipse did exactly...well NOTHING

**Comment by BluSunrize** [comment]
libs folder

**Comment by Bitterholz** [comment]
@BluSunrize Well im sad to report: There are no "libs" named folders ANYWHERE in the project. Thats why im properly confused...

**Comment by Bitterholz** [comment]
@BluSunrize You know ive worked for Logistics Pipes before, so im not to incompetent, but this is totally different for me...thats why it confuses the hell outta me. No libs folder whatsoever

**Comment by BluSunrize** [comment]
Then you MAKE ONE. Right next to the mods folder.
See? This is why I let people figure this out themselves. Because those that know how to setup their environment can actually provide proper reports and fixes.

**Comment by Bitterholz** [comment]
The f*** do I know where to put it? If it would be clear i wouldnt ask! Gosh!
I did never mean to report or fix anything. All I want is a self-compiled version that stops my Server from being unplayable because your wires in 0.6.3 are broken(no offense)

Not being familliar with how to set up the damn Minecraft environment since I never actually made a bigger mod myself doesn't impose I'm 100% incompetent of reporting and/or fixing stuff. 

I was once wanting to maybe contribute to this mod, give oppinions and ideas, fix stuff but nah not after this.

Anyways, thanks for the tip

**Comment by BluSunrize** [comment]
Pro tip: 0.6.4 is out. And it was out by the time you posted that =P

**Comment by Bitterholz** [comment]
Jeah immideatly grabbed that since twitter senpai noticed me
sadly the energy transfer is still client side :(
Until thats fixed i hate to say but the mod is unplayable
