### ISSUE TITLE
Coke Oven Bug

### ISSUE THREAD

**Issue by porteriscool** [BluSunrize/ImmersiveEngineering#76]
When I have items in the coke oven, it runs while it uses up the coal block to make the coke coal block, however, after running through one progress or two at most, I have the problem in which the coke oven does not continue to run unless updated by taking out the coal block and putting it back in, then the coke oven runs again, but has to be updated after every process or so. The internal buffer for the Creosote Oil is not full whatsoever and the internal buffer to hold the output item is not full either.

**Comment by BluSunrize** [comment]
It will only start the process if enough space is in the tank.
Coal Blocks make for 5000mB of Creosote, the tank can hold a maximum of 12k. After two blocks there is not enough space for another whole block to be processed.
