### ISSUE TITLE
[Suggestion] Decontamination Chamber

### ISSUE THREAD

**Issue by MechanicalPath** [BluSunrize/ImmersiveEngineering#760]
You have mentioned previously that you would like nuclear power to never be safe.  I don't know how exactly you want to implement that but here is the idea.  You first create a block based version of the chem thrower that way you can spray yourself with water to get rid of some of the radiation on your person.

**Comment by BluSunrize** [comment]
I'm not working on nuclear at all yet. And that suggestion is long since planned anyway.
