### ISSUE TITLE
[Suggestion] Config for the new Minetweaker Dev Requirment.

### ISSUE THREAD

**Issue by MechanicalPath** [BluSunrize/ImmersiveEngineering#761]
Simply put I cannot run the dev version of minetweaker that you require due to the version of forge I am running, I believe.  Thus I have to disable your minetweaker integration to be able to run the game.   I would much appreciate a config to disable this requirement so that I can run the game with normal minetweaker and your minetweaker integration, even if its capabilities are decreased.

**Comment by BluSunrize** [comment]
No. It's not about capabilities being decresed it's about integration being broken without the latest Minetweaker. I /need/ that reload event for everything to work right.
However, I'd be interested to know why you can't use the latest MT. From what I know it works jsut as well as the versions before it.

**Comment by cobra** [comment]
Also, using an outdated forge version is not a good idea and definitely asking for trouble. Even the relatively current version IE is currently built against, 10.13.4.1448, has some bugs which hit IE - using the current latest is highly recommended.

**Comment by MechanicalPath** [comment]
That is the same version of forge that I am running.  Here is the pastbin of the crash http://pastebin.com/dsukPjAY.  Even with only this version of minetweaker in the mods folder it prints the same crash.  I could not figure it out and just figured it was the version of forge.

**Comment by MechanicalPath** [comment]
I can however run the same version of minetweaker that is not the dev version just fine.

**Comment by cobra** [comment]
What the heck are you using? Use [this one from the minetweaker startpage](http://minetweaker3.powerofbytes.com/download/MineTweaker3-1.7.10-3.0.10B.jar).

**Comment by MechanicalPath** [comment]
I was using the "MineTweaker 3.0.10B (Dev, full) for Minecraft 1.7.10" from this page http://minetweaker3.powerofbytes.com/downloads.html.  I did not realize that they were different, but changing to the one you just mentioned fixed the problem, Thanks!

**Comment by cobra** [comment]
"dev" or "deobf" versions are not able to run in normal instance, they are for mod development purposes only. Do NOT use these ever.

**Comment by MechanicalPath** [comment]
Ok, thanks for your help
