### ISSUE TITLE
[0.6.4] Crash on SMP world Load

### ISSUE THREAD

**Issue by Bitterholz** [BluSunrize/ImmersiveEngineering#762]
Got a Crash on my server using the freshly compiled version of IE d39897b1ac268205b321b658e2b8ce8c91267253

http://pastebin.com/BKmHbVPS
Any help with resolving this? :)

**Comment by Bitterholz** [comment]
And like allways: SSP Works just fine -.-

**Comment by cobra** [comment]
That is the same error that popped up after a version I built with java 8 was run on java 7, there is [some incompatibility](http://valery-frolov.blogspot.de/2015/04/javalangnosuchmethoderror.html).

What are your java versions? Are you by chance building on 8, testing SSP on 8, but running the server with 7?

**Comment by Bitterholz** [comment]
well apparently the case -.-

**Comment by Bitterholz** [comment]
so how can I resolve that?

**Comment by cobra** [comment]
Build on 7. Or upgrade everything to 8.

**Comment by Bitterholz** [comment]
So Home path to a jdk7 and then compile eh?

**Comment by Bitterholz** [comment]
Guess i can then close this

**Comment by BluSunrize** [comment]
Note btw.: When using custom built versions don't flag your issues as [0.6.4], because you're not using one of my official versions.

**Comment by Bitterholz** [comment]
Im sorry,
0.6.4 was the latest milestone. Wasnt sure if I should have gone for something like 0.6.5 or 0.6.4a or just "Latest"
