### ISSUE TITLE
Core Sample drill message incorrect kind of

### ISSUE THREAD

**Issue by NEXUS2345** [BluSunrize/ImmersiveEngineering#764]
Basically I found a Cassiterite deposit and it spat this out instead of the standard string.
https://gyazo.com/37c00083a36d3fd3a99e041332f17bca
This was with 0.6.2 on Infinity Evolved Expert mode.

**Comment by PrincessRTFM** [comment]
That's a localization error. I checked the code and found that it's part of vanilla IE, but a search over the whole repo turns up no other occurrences. When I try a search for 'quartzite' instead, I get the registration of the Quartzite vein and localization in a number of language files, so my guess is Cassiterite was missed when adding localization.
