### ISSUE TITLE
Crash at start up

### ISSUE THREAD

**Issue by darklordwonton** [BluSunrize/ImmersiveEngineering#768]
I tried to load the game but I crashed at stage two of mod building. here's the crash report: http://pastebin.com/7ttT1E05. I have terrafirmacraft installed if that's important to know

**Comment by mindforger** [comment]
>MineTweaker3{3.0.9B} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.9C.jar) 

update it to at least 3.0.10A ... better 3.0.10B

**Comment by BluSunrize** [comment]
That is not what is causing this error though. Null fluids are something that shouldn't be happening....

As for Minetweaker: It must be 3.0.10b. the "b" is /very/ important. It'll break without it.

**Comment by BluSunrize** [comment]
I can't reproduce this issue, with TerraFirma installed, so it's got to be something else that's causing it.
@darklordwonton you'll have to help us on this by finding out which mod is causing it. First off update your Minetweaker, then take half of the mods out of the folder and launch (obviously keep IE in)
If it works, try the other half. If it crashes, split that one into quarters again and repeat. Do that until you find out which mod is causing the crash.

**Comment by mindforger** [comment]
i remember there was soemthing odd with null fluids regarding worlds beeing upgraded but last time it was railcraft, can you upload the level.dat of your world ?

**Comment by darklordwonton** [comment]
I didn't make it to any worlds, it crashed before the game finished loading

**Comment by darklordwonton** [comment]
Okay I removed TFC tweak and it seemed to do the trick, it must be the way it unifies tfc fluids and vanilla fluids that was messing with Immersive Engineering. Thx everybody!

**Comment by cobra** [comment]
Your version of TFC tweaks is rather old, there have been some updates, I see one related to railcraft 9.8 - which is the version that changed the fluid registration of railcraft. Try updating to the latest version and if it still crashes, report that to the author.

**Comment by BluSunrize** [comment]
Closed because fixed?
