### ISSUE TITLE
[Suggestion] Mining Drill - Multitool

### ISSUE THREAD

**Issue by aikpoppel** [BluSunrize/ImmersiveEngineering#772]
Hey Blu and Engi`s,
i´ll have an idea to make mining drill to a multitool, if you add a saw blade in place of borehead you can cut off trees like using a lumber axe from Tinkers'.

And...

maybe a toggle switch for area harvesting or singleblock harvesting, like on chemthrower.
Than we'll have an awesome looking All-in-one Tool :D

my english is terrible, sry for that. i hope you understand my idea :D
LG Aik

**Comment by theunkn0wn1** [comment]
I highly doubt Blu would accept area harvesting for anything but trees for obvious reasons. However, being able to put a different drill bit onto the device to allow it to cut wood is a fair idea. I don't see a reason why not to have such a feature.

**Comment by BluSunrize** [comment]
Plans for a chainsaw have been brought up before. I just lack a model for it.

**Comment by aikpoppel** [comment]
oh ok i dont know that. im sure hazard makes a awesome thing :)
