### ISSUE TITLE
Crash with GT6

### ISSUE THREAD

**Issue by BobZplus** [BluSunrize/ImmersiveEngineering#773]
I was tinkering around with baloons, hemp wires and structured connectors when suddenly got this:
http://pastebin.com/Y3QpFM40

**Comment by Bitterholz** [comment]
Are you using GT6?
Because as far as I know IE 0.6.4 is compiled against GT 5 API.
GT5 API and GT6 API are differnt so you crash once the method gets called...

**Comment by BluSunrize** [comment]
Correct. GT6 is not supported, because GT5 is the prominent version.

**Comment by LionZXY** [comment]
GT6 support (Extract this in mod file)
Warning! This path use deprecated api! 
http://vds.lionzxy.ru/GT6Path-ImmersiveEngineering.zip

**Comment by BluSunrize** [comment]
OI! THAT IS MODIFICATION AND DISTRIBUTION OF MY CODE WITHOUT PERMISSION.
YOU HAVE NO RIGHT TO THAT.
THAT FILE IS TO BE REMOVED IMMEDIATELY.

**Comment by LionZXY** [comment]
OK :((( Sorry...

**Comment by LionZXY** [comment]
Maybe you add support gregtech 6?

**Comment by BluSunrize** [comment]
No. I won't. I very specifically support GT5 because it's the prominent version. GT6 is in pre-alpha and therefore unsupported.

**Comment by LionZXY** [comment]
Hmmm... Why you don't add gt5/gt6 support? If gregtech 5 is load use gregtech 5 api

**Comment by BluSunrize** [comment]
Dude. GT5 is supported. GT6 isn't. Deal with it.
