### ISSUE TITLE
[Enhancement] Better sound loop for Crusher

### ISSUE THREAD

**Issue by Bitterholz** [BluSunrize/ImmersiveEngineering#774]
Id like to see the Crusher getting an improved sound loop. Cause if it finishes crushing an Item, but still has more to process, the sound stops and restarts rather than goin in a nice loop until the last Item is processed.
The stopping and restarting creates an ugly "Bummm" sound each time an Item has processed since th sound starts over.

Would really like if you could manage to Loop the sound so it better fits an ongoingly running machine. Maybe by determining if there are still items left since you cant extract items inserted.

**Comment by malte0811** [comment]
I noticed something similiar with the arc furnace, i will include a fix in the general tileentity bugfix pr.

**Comment by BluSunrize** [comment]
...the Arc Furnace has no sound .-.

**Comment by cobra** [comment]
The arc furnace will switch to the inactive texture for a moment before switching back on. Somewhat inherent to how the processing is done. Changing this might or might not get a bit messy.

**Comment by malte0811** [comment]
Yes, thats what i meant.
It's pretty easy actually, I've done it for the arc furnace already. Havent looked into the crusher yet.

**Comment by cobra** [comment]
The crusher processing state management was a bit tricky AFAIR.

**Comment by Bitterholz** [comment]
After all, its a cosmetic Change.
But it would hugely boost the "Immersiveness" of the Crusher. Because soundscapes are the most vital thing for immersing a Player into a Virtual world.
