### ISSUE TITLE
Fire hose

### ISSUE THREAD

**Issue by xbony2** [BluSunrize/ImmersiveEngineering#776]
So, since the Chemical Thrower can be filled and sprayed with Water, it would make sense if the sprayed water put out fires, like a hose. Plus, then the Chemical Thrower can't only be used for evil, smiting people who complain about it :P

**Comment by BluSunrize** [comment]
Done with this:
https://github.com/BluSunrize/ImmersiveEngineering/commit/6fde0b9dec29acc75da271d47ede3c2bf55b6f1e
