### ISSUE TITLE
Client Crash Voltmeter

### ISSUE THREAD

**Issue by aikpoppel** [BluSunrize/ImmersiveEngineering#777]
Hey Blu,
if i walk around with the voltmeter in my hands my client crashes...
i have look at the rusty ladder from Malisis' Doors.
http://pastebin.com/M8eZFmw9
Version: 0.6.4
LG Aik

**Comment by BluSunrize** [comment]
You're using Optifine. Can you replicate this without it installed?

**Comment by aikpoppel** [comment]
Without Optifine same crash.

**Comment by cobra** [comment]
Can you reproduce this reliably?

**Comment by aikpoppel** [comment]
@cobra here the crashlog without optifine. http://pastebin.com/ZVx6NMv7

**Comment by cobra** [comment]
Yeah, same crash, thanks - but does it happen every time?

**Comment by aikpoppel** [comment]
yes.

**Comment by cobra** [comment]
Perfect! Could you please test this [test build](https://www.dropbox.com/s/g8i136nx78o1wm0/ImmersiveEngineering-0.6.5-pre%2Bgit5d5852a.jar?dl=1) then? (based on 0.6.4, for testing only, do not redistribute)
Do what you need to do for the crash and look for "ItemRenderVoltmeter: mop is null!" in the log. If things fail like we expect, this should appear and prevent the crash.

**Comment by aikpoppel** [comment]
Tested! here the log: http://pastebin.com/KJ9UsaBS

**Comment by cobra** [comment]
Thank you! Looks like vanilla bug to me. Will catch.
