### ISSUE TITLE
[Enhanchement] Cobble in the Crusher

### ISSUE THREAD

**Issue by Bitterholz** [BluSunrize/ImmersiveEngineering#778]
I'd love to see the Crusher Process Cobblestone into Gravel FIRST and then Gravl into Sand. Its a real nucence getting enough Gravel together for creating Concrete for our Floors.

Appreachiate if you could change it.

**Comment by BluSunrize** [comment]
valid complaint. Will do.

**Comment by Bitterholz** [comment]
Huge :+1:

**Comment by Bitterholz** [comment]
Damn you @BluSunrize ! I was about to PR it right this moment XD But thanks man!

**Comment by BluSunrize** [comment]
I told you I'd do it...

**Comment by Bitterholz** [comment]
Much apprechiated! :+1:
BTW just to ask you may I Compile and distribute IE within a Private modpack for me and a handfull of my Friends?

**Comment by BluSunrize** [comment]
No, I'd rather you not. I have had bad experiences with leaks and custom compilations in the past.

**Comment by Bitterholz** [comment]
Allright. not even for absolutely restricted access? (It would only be available to Invited people on Dropbox)
All credits to you.

**Comment by Bitterholz** [comment]
Don't get me wrong if you say absolutely no ill respect that fully, but we desperately need this Gravel thing and the Diesel Dupe Fix.

**Comment by BluSunrize** [comment]
Then I grant you explicit permission. This goes /only/ for you and your group, the fixed version is /not/ to be distributed anywhere else. And this is the only time I will ever make this exception.

**Comment by Bitterholz** [comment]
HUGE :+1:
Thank you very much!
