### ISSUE TITLE
Hammer Turning Ores into Copper Bars 

### ISSUE THREAD

**Issue by fullphaser** [BluSunrize/ImmersiveEngineering#779]
http://imgur.com/MtId9Lv

This is in the latest version of the Tame the World Modpack, you should be able to take a look at the Mod List / etc. here https://github.com/fullphaser/Tame-The-World (Fastcraft is installed) 

Not sure which interaction is causing this or if it's an interaction at all.

**Comment by malte0811** [comment]
#766, fixed already

**Comment by fullphaser** [comment]
Oh well known bug! Hooray at least I don't feel terribly stupid
