### ISSUE TITLE
HV Transformer and Steel Fence

### ISSUE THREAD

**Issue by porteriscool** [BluSunrize/ImmersiveEngineering#78]
In my minecraft world, I also appear to have the hv transformer side by side with a steel fence, however, the steel fence does not connect to the transformer. Is this a bug, or is this intentional?
![2015-06-24_16 45 59](https://cloud.githubusercontent.com/assets/12450943/8341088/b62126ac-1a90-11e5-8527-475c0c3120ae.png)

**Comment by BluSunrize** [comment]
Wouldn't really call it a bug. Since the transformer shares its block id with multiple other block that do not fill an entire space, the fences won't connect.

**Comment by porteriscool** [comment]
Ahhh, that makes sense, okay, good to know.
