### ISSUE TITLE
Emasher new Fluid physics in engeneers toolbox hampers waterwheel

### ISSUE THREAD

**Issue by purplemonday** [BluSunrize/ImmersiveEngineering#781]
the Mod "EngineersToolbox-1.2.3.0-BETA" interduces a new fluid mechanic that basicly makes your sourceblocks run down hill. 
the waterwheel is extremely hard to use with it,.almost inposible to get the full gain of 3 wheels without your water running off. 

best case youll endup with a encased wheel and soon you place a block/walk past it the sourceblock goes true the waterwheel downwards, still even then its hard to place the water source blocks.

placement of sourceblocks is just normal, however the waterwheel "activates" them somehow to start running and not even consistend. to give an exsample, rieka's rotarycraft hydrokenitic engines do not suffer from this.

im fully aware that i might be the only one using this mod combo as last ftb pack toolbox whas in whas monster, but i love toolbox as its replaces alot of redpower's features, 
i would love it correctly working with SE

tad olderversion of this pack im working on i have uploaded here.youll still need to still add your mod to it to see the results.(realy this is verry WIP and im still ironing out issue's, play/crash at own risk, and yeah i know about the 8 types of copper)

https://www.dropbox.com/s/9zh04xy0unjhapp/purplepack0.3%20pre1.zip?dl=1

**Comment by BluSunrize** [comment]
How the heck do you expect me to fix this? xD
Of course the waterwheel isn't goinh to work with "real" fluid dynamics. I can't fix that. I just hope for your sake that ET has a config for that, or else your waterwheels are useless :D

**Comment by purplemonday** [comment]
as i stated reika whas able to fix this.. how i dunno..
its likely couse the source block isnt in contact etc

i dont expect you to fix this fast. i expect you to give it a thought and
perhapse fix it.

**Comment by BluSunrize** [comment]
I can't even replicate this. Are you sure it's Engineer's Toolbox? Because I have 1.2.3.0-BETA and my water behaves like always.

Also, Reika's hydrokinetic engines work entirely different from my waterwheel.

**Comment by cobra** [comment]
I could not find anything about these water mechanics. The closest thing I could find is "slickwater", but that's something else than water and apparently not replacing it. I don't think this is coming from Emasher's mods - this hasn't been updated in a while and noone else has reported this problem.

**Comment by OneEyeMaker** [comment]
@purplemonday 
It's not *new* mechanics of ET, it's old mechanics of IHL Tools&Machines.

**Comment by purplemonday** [comment]
aprently oneeyemaker is correct i whas totaly off. gues tomuch issues at
once to make sense off. my bad
