### ISSUE TITLE
Core sample drill provides information without taking a new sample

### ISSUE THREAD

**Issue by rahangar** [BluSunrize/ImmersiveEngineering#782]
After the initial sample extraction the core sample drill seems to continue to provide updated values whenever I right-click on it, BUT without having extracted a new sample.
I even removed the power source, and the drill continued to remain at 8000/8000 RF according to wala, while giving updated information... again without taking a new sample.

Not sure if this is intended.  It seems a bit strange.

I'm running 0.6.2.

**Comment by rahangar** [comment]
![2015-12-13_19 25 44](https://cloud.githubusercontent.com/assets/3137077/11770937/664e4d82-a1cf-11e5-9aca-9020280721a2.png)

**Comment by malte0811** [comment]
That is intended

**Comment by BluSunrize** [comment]
^ what he said. I couldn't be bothered to force you to re-probe. I need to come up with a better system for that anyway.
