### ISSUE TITLE
Crash on start up

### ISSUE THREAD

**Issue by Frito660** [BluSunrize/ImmersiveEngineering#783]
Hello, 
I have been trying to update to the latest version from v0.5.4 but every version that is newer crashes on loading. I am still pretty new to the whole thing so any help is appreciated. 

My last Crash log
[crash-2015-12-13_20.18.05-client.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/60810/crash-2015-12-13_20.18.05-client.txt)

**Comment by malte0811** [comment]
Update immersive integration

**Comment by Frito660** [comment]
Thanks alot :) that fix worked
