### ISSUE TITLE
[Suggestion] Aluminium fused salt electrolysis

### ISSUE THREAD

**Issue by Bitterholz** [BluSunrize/ImmersiveEngineering#784]
How about aluminium requiring a fused salt electrolysis Machine.
All mods do it wrong! There is no Aluminium Ore and you can't just smelt it to gain Aluminium in pure Form.
As IE is semi-realistic, I'd love to see one actually require this Machine to make Aluminium. Or at least the need of Kryolith Salt as alloying Material for Bauxite in the Arc Furnace to extract Aluminium.

**Comment by Bitterholz** [comment]
Something like this:
![Fused Slat Electrolysis](http://e-learnforum.net/Bilder/SiteAl/Schmelzfluss.gif)

**Comment by BluSunrize** [comment]
No.
Plain and simple. Far too complex, breaks the mold by way too much.

**Comment by Bitterholz** [comment]
Allright
