### ISSUE TITLE
[suggestion] Tiered Engineer's Hammer

### ISSUE THREAD

**Issue by tgstyle** [BluSunrize/ImmersiveEngineering#786]
Just a thought for modpacks to have an option for a Tiered Hammer. One that only works for low level multi-block like the coke oven, one that works for mid level machines and lower, and one that works for high level machines and lower.

**Comment by James-T-Oudvoure** [comment]
What purpose would such an addition serve?

**Comment by tgstyle** [comment]
If a modpack has a progressive tech ability, and uses a questing mode, it could come in handy to award tiers to players as they progress higher in questing.

**Comment by malte0811** [comment]
In a questing mode pack you can achieve something like that by adding recipes for hammers with nbt tags: a nbt tag list with the name "multiblockInterdiction" containing the names of all multiblocks that cant be formed with that hammer.

**Comment by tgstyle** [comment]
hmm OK, could you give me an example with MineTweaker? Just the crafted item nbt for say a coke oven and blast furnace, don't need the whole line.

**Comment by tgstyle** [comment]
I think I have this right for the script after looking at the code. I just did a quick test. It loads fine plus crafts, but the multiblock still forms.

https://gist.github.com/tgstyle/4884542e78ee9579c59e

**Comment by BluSunrize** [comment]
Wrong script as well as wrong names.
All my multiblocks start with "IE:", so it's "IE:Excavator".
And it's a TagList, not a TagCompound, so it's written like the Lore tag:
.withTag({multiblockInterdiction: ["IE:Excavator", "IE:ExcavatorDemo"]});
