### ISSUE TITLE
can't extract from top of immersive fluid tank

### ISSUE THREAD

**Issue by quentfr21** [BluSunrize/ImmersiveEngineering#788]
hello
immersive 0.6.4

i try to extract from the top of fluid tank with an immersive pump and that don't work
pump extract fluid from the world and from another fluid container without pb
i think pb come with the fluid tank because i try to extract with ender io fluid conduit and nothing was extracted from the top output (other output work but pump can't be placed at bottom of tank)

thanks in advance

**Comment by BluSunrize** [comment]
You can't extract from the top, only from the bottom. Read the manual.

**Comment by quentfr21** [comment]
that ok sorry
but how do you extract from tank you can't place pump directly to the bottom output you need to place a fluid pipe between tank and pump like that http://rousteurs.free.fr/extarctpb.png but extract not work

sorry if i miss something

**Comment by BluSunrize** [comment]
Tanks will auto-output if you give them a redstone signal on the bottom block

**Comment by quentfr21** [comment]
i just see that sorry again
