### ISSUE TITLE
[suggestion] spawn commands for IE machines

### ISSUE THREAD

**Issue by alucard87pl** [BluSunrize/ImmersiveEngineering#789]
Hi,

I've grown to like Immersive Engineering and it's multiblock philosophy a lot. However, building a test setup on a creative world can sometimes be a hassle.

Would it be hard to add spawn commands to build the machines in the world, sort of like how OpenComputers has  `/oc_SpawnComputer` which spawns a basic computer - useful when you're designing a network and just want a bunch of computers.

**Comment by malte0811** [comment]
I like that idea, it would be usefull especially when testing with the arc furnace or the excavator, maybe even with more than one. Implementing this shouldnt be to hard, just iterate through the manual array and place the blocks accordingly

**Comment by BluSunrize** [comment]
And where would I start? Every multiblock has a different trigger after all

**Comment by alucard87pl** [comment]
If you mean hitting the structure to form it into the final form, that's not too much of a deal. Currently in my modset i use WorldEdit to copy and paste the unformed structures and then hammer them. the command would just plop the blocks in place, just like WE. Hammering them is easy compared to memorizing the structure or constantly looking through the Manual :)

**Comment by BluSunrize** [comment]
No, I'm saying that every structure has different proportions and I can already hear people bitching at me for spawning it into their buildings/not knowing which way it'll spawn.

**Comment by alucard87pl** [comment]
You know how Botania has a build helper (visualize I believe it was called) for the Elven Gateway? A feature like that could be used with the Manual when in Creative (click a button to visualize the structure in phantom blocks then place it with a right click)

**Comment by BluSunrize** [comment]
I do beleive I explained this before, I'm /not/ doign ghostblocks.
To be quite frank, I don't like this "Spawn multiblocks" thing. It's really not that hard to remember these structures. When you're in creative, you can build them in less than a minute.

**Comment by alucard87pl** [comment]
Oh well, WE it is...

**Comment by cobra** [comment]
Alternatives:
- the good old buildcraft builder
- [schematica](http://www.curse.com/mc-mods/minecraft/225603-schematica)
