### ISSUE TITLE
Crash on boot

### ISSUE THREAD

**Issue by Adraxas** [BluSunrize/ImmersiveEngineering#79]
Crashes when i try to boot the game
http://pastebin.com/AvNNpdbG

**Comment by BluSunrize** [comment]
Try updating your Forge. You're on a pretty old version.

**Comment by Kolatra** [comment]
With the latest versions of Reika's mods, 1291 is the recommended version and the version he builds on due to some of what he does in his mods, and certain methods that are required are not available past 1291.

**Comment by bdudek** [comment]
I also get this crash an im not able to update pack to a newer forge due to growthcraft latest i can use is the 1291.

**Comment by BluSunrize** [comment]
Well then blame Reika. That Forge Version is old and since then Forge has seen many improvements. I built on the new one and I can' t really add backwards compat.
