### ISSUE TITLE
getTankInfo returns empty table after upgrade to 0.6.4

### ISSUE THREAD

**Issue by rahangar** [BluSunrize/ImmersiveEngineering#792]
I went from 0.6.2 to 0.6.4, and through a couple of hours of troubleshooting, discovered that getTankInfo() no longer works as it did before.

1.  On the refinery it looks like only specific connection points (namely those under the fluid ports) are, in 0.6.4, the only connection points that return non-empty tables.  And even those points now seem to be specific to the type of fluid.  So whereas before, I could get the info on all 3 tanks via one network/modem connection (i.e. getTankInfo() gave me all 3 tanks), it seems that now I have to have two separate connections.

2.  The biodiesel generator getTankInfo() used to return the amount, so it obviously has a tank, but now returns an empty table.

The changes to the biodiesel generator.... is this a bug?  or is it intended to hide the obvious tank within the generator?  I'm raising this issue in case this is a bug.

Comments/questions:
A) The changes to the refinery make sense, but it would have saved me some time were it mentioned in the change log. 

B) Is there a GUI planned for the biodiesel generator?  It would be nice to see it's stats, including how much power it is generating, and it's biodiesel tank buffer.

C) General question:   Do you have any suggestions on the best way of getting stats on the various machines?  I'm using computercraft and open peripherals, but was wondering if a different method is preferred by the mod author(s)?

Thanks!

**Comment by cobra** [comment]
This will only work on parts of the multiblock accepting or outputting fluids. Reason: fluid pipes would connect everywhere without being able to in/output fluid there. Some mods don't use proper checks and still connect (namely buildcraft and enderio), but others do more sensible checks to determine which blocks they should connect to.

There are plans for computer support, but nothing has been decided or coded yet.

**Comment by BluSunrize** [comment]
Correct. Those changes were written for the smart fluid pipe connection and they will stay like this.
Shoutout to @cobra who made pipes 200% cooler with that =3

**Comment by rahangar** [comment]
Thanks for the reply.   I understand. 

I didn't see a response to question B.  Namely, it seems to have an internal tank, but getTankInfo() returns an empty table.  That was the main reason why I raised this issue:  An excerpt from above: 

The changes to the biodiesel generator.... is this a bug? or is it intended to hide the obvious tank within the generator? I'm raising this issue in case this is a bug.

Does the biodiesel generator has a multiblock part that outputs the correct tank info when connected?   I tried various parts, but no luck.

**Comment by cobra** [comment]
I think you forgot to include the direction. getTankInfo will only return something else than an empty array for the correct block position and direction - the same way it will accept or output fluids. That is, a diesel generator won't return anything from the smaller side or below.
Without any modification,
OpenComputers:
![](https://cloud.githubusercontent.com/assets/163331/11849289/641a0df8-a427-11e5-84b6-5f871bbd8eb6.png)
ComputerCraft:
![](https://cloud.githubusercontent.com/assets/163331/11849288/64187ef2-a427-11e5-9ad4-5c581ca7834c.png)
Setup for ComputerCraft, I used an Adapter block in the same position as the CC computer for OpenComputers:
![](https://cloud.githubusercontent.com/assets/163331/11849444/29e82524-a428-11e5-8edd-d7379cdc23df.png)

**Comment by rahangar** [comment]
Awesome.  Thanks for the tip. 

BTW, I didn't have to provide the direction in 0.6.2.  I guess this might be a consequence of related changes.

Thanks again for going through the trouble of pasting the images above.  Much appreciated.
