### ISSUE TITLE
Crash when adding multiple secondary crusher outputs

### ISSUE THREAD

**Issue by lawremi** [BluSunrize/ImmersiveEngineering#793]
Getting this crash when attempting to add a second secondary crusher output:
```
java.lang.ArrayIndexOutOfBoundsException: 1
	at blusunrize.immersiveengineering.api.crafting.CrusherRecipe.addToSecondaryOutput(CrusherRecipe.java:47)
```

The bug is pretty obvious. You might just use `Arrays.asList()` to copy the existing array into the ArrayList.

Btw, I was planning on making a PR, but your build configuration does not automatically install compile-time dependencies. That makes direct contribution very difficult. The OpenComputers `build.gradle` has a good example.

**Comment by BluSunrize** [comment]
My gradle is dependency less on purpose.
Also I'd like to see your code to evaluate what went wrong.

**Comment by lawremi** [comment]
Here is the code:

```
CrusherRecipe recipe = CrusherRecipe.addRecipe(output, input, energy);
for (ChanceStack secondary : secondaries) {
    recipe.addToSecondaryOutput(secondary.itemStack, secondary.chance);	
}
```

The subscript into the `secondaryOutput` and `secondaryChance` arrays needs to be just `i`.

**Comment by BluSunrize** [comment]
Ah, I see my mistake now. And I could not have used asList() because that gives a fixed size immuteable, so I can't work with that ^^

**Comment by BluSunrize** [comment]
last question: What's this for anyway if I may ask? I'm always interested to know what mods have IE compat =3

**Comment by lawremi** [comment]
I meant that you could use `asList` to pass an argument to `addAll` or the ArrayList constructor. Anyway, this is for "Per Fabrica Ad Astra". It adds many realistic minerals in realistic formations and uses other mods (like this one) to process them.

**Comment by BluSunrize** [comment]
there we go!
