### ISSUE TITLE
capacitor/Voltmeter incorrectly displaying energy amount.

### ISSUE THREAD

**Issue by killerscorpion** [BluSunrize/ImmersiveEngineering#796]
Apologies if this has already been reported. 

Using IE 0.6.4 and Forge 10.13.4.1566

When using a waterwheel in conjunction with an MV capacitor, the voltmeter is displaying the correct RF in the chat line, but does not display the correct amount in the Nixie Tube display. I have not tested this with the other capacitors. I think the pictures are self explanatory to this issue. 
![2015-12-16_22 19 59](https://cloud.githubusercontent.com/assets/10732882/11862940/b67ad3ee-a444-11e5-83f5-adda9e72e0c0.png)
![2015-12-16_22 21 20](https://cloud.githubusercontent.com/assets/10732882/11862944/b9a213f2-a444-11e5-95e5-8c8e66552a89.png)

**Comment by cobra** [comment]
This should have been fixed in commit baf858b2db7166d92c661acc2de0d8d5d42be8e5 by @malte0811 for the next release.

**Comment by malte0811** [comment]
Yes, that is exactly the bug fixed by that commit.

**Comment by killerscorpion** [comment]
Awesome! glad to know its fixed.

**Comment by BluSunrize** [comment]
Closed then ^^
