### ISSUE TITLE
Pump Creates Cobblestone?

### ISSUE THREAD

**Issue by ZeekDaGeek** [BluSunrize/ImmersiveEngineering#798]
I'm not exactly sure why but the Immersive Engineering Pump is creating cobblestone for no reason I can possible think of. I'm attempting to use the pump as part of a tank however, it destroys the ability for the tank to function by placing cobblestone all over the place some of the time.

Tank: http://zeekdageek.tv/ss/zG8Y4.png
Random Cobble: http://zeekdageek.tv/ss/IuHAL.png

**Comment by BluSunrize** [comment]
that's 100% intentional. This way it prevents lag of flowing fluids. Enderthermic Pump from Extra Utils does the same thing.

**Comment by ZeekDaGeek** [comment]
Is there any way to make this an option as opposed to something forced on players?

**Comment by BluSunrize** [comment]
Well it's supposed to be lag prevention and I rather like that.

**Comment by ZeekDaGeek** [comment]
Something along the lines of crafting it with a Steel Mechanical Component instead of an Iron Mechanical Component to have both functionalities or something.

If you want to talk about lagless pumps this thing right now is creating a lack of flow that results in MASSIVE lag when not enough fluid is provided and it's not doing it's task. It would also be great to have a pump that allows for in world tank designs like I'm attempting to make.

**Comment by ZeekDaGeek** [comment]
Also Endothermic pumps are a hideous creation that destroys nethers, no one wants another one of those things around. ;D

**Comment by BluSunrize** [comment]
How does a lack of flow create lag? That's not how pumps work.

**Comment by ZeekDaGeek** [comment]
In this specific instance the pump is preventing additional fluids from being placed within it's pumping range, decreasing the amount of fluids it can pump and causing Steam Generators to cause a large number of explosions with particles and flickering machinery and causing fluids to get higher and higher around it.

Not necessarily in every instance is blocking flow going to prevent latency.

**Comment by BluSunrize** [comment]
It really doesn't. It checks the entire area and starts at the furthest block. And it will only pump source blocks, so stuff flowing into its area wouldn't work anyway.
