### ISSUE TITLE
[Suggestion] Hook for computercraft/opencomputers on the core samplers.

### ISSUE THREAD

**Issue by NachtRaben** [BluSunrize/ImmersiveEngineering#799]
* Automate the finding of veins instead of very tedious searching
* Allow the ability to notify a player that the vein has finished
* Someone could eventually find something else to do with it

**Comment by cobra** [comment]
Computer support is planned, but not totally trivial.

**Comment by malte0811** [comment]
I thought blu didnt want the coredrill to be automated. If that isnt true I can look into adding support this afternoon.
Also: why wouldnt it be trivial? I worked with the cc api some time ago, it didnt seem that complicated

**Comment by NachtRaben** [comment]
I've seen a few twitch streamers and youtubers request the feature. Didn't see anything on the tracker about it so i figured i'd ask about it in their stead.

**Comment by BluSunrize** [comment]
Obviously the people that do request it are those playing with Infintiy, which nerfs the everloving fuck out of IE.
But yeah, cobra and me have disucssed it, some basic hooks are planned,

**Comment by rahangar** [comment]
Hi Blu, 
Interesting you should mention nerfing IE.  I don't play infinity, but I do have other mods that I use with IE, computercraft being one of them.  I often find myself wondering what the mod-author had in mind, and whether he would feel my other mods are diminishing the fun of IE.   It is off topic here, but I'm very curious about your thoughts on that.   It would be nice to get your vision ... a description of how you imagined the mod would be played.  And maybe even a list of other high level functions (e.g. power generation, automation, etc) that you think should not be obtained via other mods.  I know that's asking a lot of you, so I won't hold my breath.   But I would appreciate it if you consider it.

**Comment by malte0811** [comment]
@BluSunrize you can close this now
