### ISSUE TITLE
Some reflections

### ISSUE THREAD

**Issue by tjsd** [BluSunrize/ImmersiveEngineering#8]
Edit: First off, I love the mod - the multiblocks and visuals are amazing!

I have been watching people play with this mod on FC2 for some days now, and I have been testing it myself in single player. I know its alpha and you have a lot of stuff to add and fix.

My "issue" is the ores, you add copper, bauxite, silver, lead and nickle. But only copper have some real use in your recipes. This is kind of strange adding 5 ores to world gen while almost not  using any of the ores except copper. This is no problem in big packs that uses all these ores already, but for small packs (like one I am working on) this is the only mod that uses non vanilla ores, and adding 4 ores with 3-4 uses seems very exaggerated. I guess you plan to add more stuff that uses the other ores later, but is all 5 needed? 

The constant Grit dust could maybe be made by copper and redstone dust. That would remove all use of Nickle in the mod. 

Aluminum is used in High Voltage parts, but those few could be exchanged with steel. 
You also use aluminum grit for cartridges in the revolver, but that could easily be iron dust.

Electrum is made with silver and gold, that is the only use of silver. Could that maybe be made by gold, redstone and copper dust. 

These are just musings, and I know the final mod would probably have more use of the ores. And I could always use minetweaker to do these changes. But I think it is worth considering if it is needed with 5 extra ores, maybe you can do like Ender IO. If they do not detect Copper in world gen they use iron in the recipes instead. I feel copper has a real use in the mod so far, but the other 4 ores seems more excessive then needed.

**Comment by BluSunrize** [comment]
Alrighty.
So first off: Our recipes have contextual background based on real world situations.
Electrum is not fictional alloy, it exists, and is comprised from gold and silver.
High-voltage landlines are also comprised from steel and aluminium.
Nickel is needed to make Constantan, another real world alloy, one of the few thermoelectric alloys at that.
Aluminium grit is used for dragonsbreath ammunition, which is also an actual existing ammunition made with flammable metal dust like aluminium. And iron grit is already used for buckshot.

We (this means Damien Hazard more than anything) have tried to make this mod resemble actual, real world engineering and electricity (with the obvious exception of having the energy system use RF), and as such our recipes are based on it.

I appreciate the input, but our ores will stay in ^^
