### ISSUE TITLE
[suggestion] Immersive Engineer Toolbox

### ISSUE THREAD

**Issue by Samji** [BluSunrize/ImmersiveEngineering#800]
A request for an Immersive Engineer Toolbox for all your engineering tools.

**Comment by aikpoppel** [comment]
+

**Comment by James-T-Oudvoure** [comment]
While I certainly would find this aesthetically pleasing, wouldn't storing them in a normal chest be good enough? If you want something nicer looking, you could use a Bibliocraft tool rack, you could even use a paneler and give it a Treated Wood Planks texture.

**Comment by Samji** [comment]
It wouldn't be a stationary storage like a chest - We have enough of them!
No it would be kept in your inventory and you would right click to open it - the gui could even look like a toolbox with space for your coiled wires, connectors and hammer.

Date: Sat, 19 Dec 2015 21:15:45 -0800

**Comment by Bitterholz** [comment]
Huge :+1: in this!
A toolbox for all the Wires, Connectors and other Tools would be nice!

**Comment by AEnterprise** [comment]
not sure how doable it is but it would be cool if it would even be made so it fits in your chestplate slot so it's like a toolbox you can put over your sholder

**Comment by Samji** [comment]
Aah like a tool belt - so two ideas then. The tool belt could be placed in your belt slot in the baubles gui but takes up your belt slot. The toolbox on the other hand takes an inventory slot.
I'm going more towards the tool belt now as you wouldn't need it all the time..

Sent from Outlook Mobile




On Sun, Dec 20, 2015 at 12:20 PM -0800, "AEnterprise" <notifications@github.com> wrote:





not sure how doable it is but it would be cool if it would even be made so it fits in your chestplate slot so it's like a toolbox you can put over your sholder

---

**Comment by BluSunrize** [comment]
Alright, lemme get my statement in here:
1) Totally doable
2) I like the general concept
3) I'd absolutely make it a bauble, but not a chestpiece, and I don't want a hard dependency on Baubles either, so it'd be optional
4) @Samji if you really feel the need to use the mail reply feature rather than spend a minute of opening this website, at least remove the previous messages, alright? That just looks silly.
5) This is not a priority right now, so it might be a few days till you see progress on it.

**Comment by Samji** [comment]
1) Sorry! - forgot my password..
2) Anything would be AMAZING!
3) Wow thanks for even allocating a thought process towards this idea!

**Comment by codewarrior0** [comment]
:+1:

Messing around with wires takes a lot of inventory slots:

- Power posts
- Hammer to extend post arms
- Wire cutters
- Voltmeter
- HV coils
- MV coils
- LV coils
- HV Relays
- HV Connectors
- MV Connectors
- LV Connectors
- The steel thing for hanging HV Relays on a wall, I forget what it's called.


A bag to keep this stuff in would be wonderful. Another :+1: if it sucks up items like the Forestry backpacks.

**Comment by BluSunrize** [comment]
Oh right toolboxes are a thing now btw., so closed =P
