### ISSUE TITLE
Client Crash with Thaumcraft

### ISSUE THREAD

**Issue by aikpoppel** [BluSunrize/ImmersiveEngineering#801]
Hey Blu,
when i try to scan hv capacitor with thaumometer client crash http://pastebin.com/YAkk29vx

another guy on my server has hv capacitor in inventory and try mouseover shift, client crash, he has capacitor already scan. http://pastebin.com/YwLtF9CU

dont know its on ie side or thaumcraft. if not ie's fault i´ll report it to azanor.
LG Aik

Forge 10.13.4.1558, IE 0.6.4, Thaumcraft 4.2.3.5

**Comment by BluSunrize** [comment]
Hmm... it's an infinite loop in TC's aspects.
You have Witching Gadgets in there, have you tried going into the configs and disabling the transmutations?

**Comment by aikpoppel** [comment]
ok, i´ve disabled transmutation and no crash. thank you!
can be closed.

**Comment by BluSunrize** [comment]
yeah Thaucmraft error, WG brings it out =P
