### ISSUE TITLE
java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays

### ISSUE THREAD

**Issue by xKillerbees** [BluSunrize/ImmersiveEngineering#804]
http://pastebin.com/5kPR8T19
Using the latest compile, this is the crash report. The link below is the last commit made when compiled.
https://github.com/BluSunrize/ImmersiveEngineering/commit/5dd3d2f5561177b3fe0adb59f573eaacd0204398
forge-1.7.10-10.13.4.1558-1.7.10-universal.jar

**Comment by BluSunrize** [comment]
Damn those scala imports!
Will be fixed in a moment

**Comment by BluSunrize** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/b4cf398a0d477142d82b9de4eb342b8e981bca89

^ there
