### ISSUE TITLE
[0.6.4] IE creates a bunch of Orphaned Tileentities

### ISSUE THREAD

**Issue by Bitterholz** [BluSunrize/ImmersiveEngineering#805]
Analyzed my Base with Opis, found a metric f*load of orphaned Tileenteties caused by IE.

Mostly caused by Coke Ovens and the workbench.

**Comment by malte0811** [comment]
Can opis figure out where said tileentities are? If it can, is there something special about these locations? Also remember that every block of the multiblocks has it's own tileentity. Are there multible tileentities in the same place?

**Comment by Bitterholz** [comment]
Nothing special about the position of the Blocks. The coke Ovens are 1 Block apart and the workbench is nowhere near them.

what ive noticed is that Opis lists all the Orphaned TE's multiple times with the same hash and Coordinates.

Ill try with the latest commits and give more feedback!

**Comment by BluSunrize** [comment]
Yeah. ClientSided ones. For rendering stuff in your inventory. >_>

**Comment by Bitterholz** [comment]
So do you need to fix this or is it some User induced problem?

**Comment by malte0811** [comment]
I am not sure, but i havent looked into this yet. If this is on a server, then it is probably a bug, if it is in singleplayer, i don't know. A question: are the locations of the tileentities correct (there is stuff there that should have this tileentity) or are they in places with completly unrelated stuff?

**Comment by Bitterholz** [comment]
Its on a Dedicated Server yes. Cooradinates are within the corresponding Multiblock.

**Comment by malte0811** [comment]
And Opis is reporting more than one TileEntity at the same position? How many (rough guess is enough, >100, >75, >50, >10, <10)?

**Comment by Bitterholz** [comment]
It repeats them 205 Times to be exact.
Each time same Hash and position.
each Time 54 Entries with their position exactly matching every block of the 2 Coce Ovens I have sitting in my base.
