### ISSUE TITLE
Mineral Deposit Rate Not 1/9

### ISSUE THREAD

**Issue by Vesperiine** [BluSunrize/ImmersiveEngineering#806]
So I've seen this personally, and also from curse and reddit, but mineral deposit rates are definitely not spawning at 1/8 chunk rate.  My current rate is closer to 1/30 (after scanning 150 chunks).

Note: This may be an infinity evolved issue.

http://www.minecraftmods.win/mc-mods/minecraft/231951-immersive-engineering
https://www.reddit.com/r/feedthebeast/comments/3vjdf0/ftb_infinity_evolved_ie_core_sampler_not_working/
https://www.reddit.com/r/feedthebeast/comments/3wnhms/infinity_evolved_expert_the_new_vein_distribution/

Some people have suggested features such as an ore compass, or ore radar, that lets you know if a region has an ore, before you drill the specific chunks.

**Comment by PrincessRTFM** [comment]
Have you checked the IE config file AND looked through any minetweaker scripts included in the pack? IE allows MT scripts to unregister existing ores and register custom veins with their own probabilities.
