### ISSUE TITLE
[0.6.4] Ethanol Production to ressource hungry

### ISSUE THREAD

**Issue by Bitterholz** [BluSunrize/ImmersiveEngineering#807]
I've got the slight feeling that Enthanol Production is a bit to nerfed. Getting 80mb of ethanol per Piece of Melon/Surgarcane (Wich are allready quite good to farm when you combine Forestry and 10* Seeds from Agricraft can not statisfy the needs of a single Fermenter running at full Speed.

And the farm im using is a 10* melon Farm with effective 272 Blocks of productive farmland. (Agricraft 10* melons produce 4Slices each time they grow) 

I think Melons should be buffed over Sugarcane and Apples over Melons. because the effort needed to produce a large enough amount to keep a single refinery running steady is HUGE

**Comment by cloakable** [comment]
To run a refinery at full tilt you need to provide an input material to the squeezer and fermenter an average of one a second. If you can't do that using a 10/10/10 watermelon farm, something is very wrong in your pack.

**Comment by Bitterholz** [comment]
Nothing wrong with ma pack since you cannot configure the Amount of Luquid gained per Item or combination of liquids in the Squeezer, Fermenter or Refinery.

Still 10* melons do not produce enough to keep things running at full tilt my backlog of tanks is getting decimated quickly
:/

**Comment by cloakable** [comment]
You alter squeezer/fermenter/refinery recipes in MineTweaker.

**Comment by Bitterholz** [comment]
Allright, found it was a issue on our side regarding pipeing problems. /close
