### ISSUE TITLE
If a tank and diesel generator are in different chunks fuel will disappear 

### ISSUE THREAD

**Issue by jhultgre** [BluSunrize/ImmersiveEngineering#808]
I put the generator and a tank in the same chunk then when the generators internal tank filled up the tank stopped draining.

If the generator was a couple of chunks away the tank would continue to drain until it was empty even though the generator was switched off with a lever.

**Comment by jhultgre** [comment]
it looks like the issue is with the fluid pipes. if I put a tank from ender io near the tank with fluid pipes in between it fills up and stops draining.

further away when connected by fluid pipes the tank only fills up to 15999 mb and the tank will drain until it is empty.

**Comment by theunkn0wn1** [comment]
Can we please get a few pictures of the setup, the version of IE in use, and the modpack in use (if applicable)?

Attempted to reproduce with a BC tank that was placed over two chunks away piping into a generator; described bug did not occur. Using IE build 92f1bb7
Setup below:
![image](https://cloud.githubusercontent.com/assets/3110986/12008374/85fd3186-abeb-11e5-8b01-36d7727a5aeb.png)

**Comment by codewarrior0** [comment]
I had a problem similar to this in 0.6.2. I found it was related to the way fluid pipes would automatically connect to the non-inputting/non-outputting blocks and sides of multiblock diesels and fluid tanks. I'm using 0.6.5 now so I can't reproduce it,
