### ISSUE TITLE
water will drop the floodlight's fake lights

### ISSUE THREAD

**Issue by 3Pixel** [BluSunrize/ImmersiveEngineering#809]
i managed to get a "fake light" item from the Floodlight.
you can make it drop like a torch with water.

to reproduce: place water near a invisible fake light and it should "drop"

**Comment by BluSunrize** [comment]
That's already been fixed. What version are you on?

**Comment by 3Pixel** [comment]
0.6.2  I know thats a old version but i didn't saw it fixed i the changelogs in the newer versions

**Comment by BluSunrize** [comment]
But you also didn't try it on an actual current version. Bug is fixed, issue closed.
