### ISSUE TITLE
Placing of Treated Wood Items Bug

### ISSUE THREAD

**Issue by porteriscool** [BluSunrize/ImmersiveEngineering#81]
Whenever I place down a treated wood item, such as the treated wood plank, and I also jump at the same time while placing the block below me, the blocks place at a faster pace than other blocks being placed, and I DO NOT have auto clicker. As you can see, not only am I looking at the hitbox of the treated wood plank, but I am inside of the block as well. Not sure if this bug is known of, but here it is. If you need anymore information, please feel free to ask.
![2015-06-24_17 47 30](https://cloud.githubusercontent.com/assets/12450943/8342322/3533d202-1a99-11e5-9a86-5e0ce3e03573.png)

**Comment by BluSunrize** [comment]
That's because the block isn't solid, no easy way to fix that, not really a bug
