### ISSUE TITLE
[Bug: Immersive Engineering 0.6.4]: Ore crushing changes from 0.6.3 did not take effect

### ISSUE THREAD

**Issue by Carbon-Key** [BluSunrize/ImmersiveEngineering#810]
Hello,

Sorry if this is just a misunderstanding of the patch notes, but I am confused about these lines from the 0.6.3 Changelog:

- changed ingots to no longer be crushable
- changed ores to only crush into a single piece of dust

After reading this I expected ores dropped into the crusher to only return one grit per ore block and for ingots to no longer be able to ground back into grit using the crusher. In 0.6.4 however I see no trace of these changes, and in fact the entry for the crusher in the manual also still refers to it as an ore doubling mechanic. I was just wondering if those ideas got scrapped and just remained in the changelog by accident or if those changes were accidentally not included in the release. I was excited about this change as it encouraged ore management and building of the Arc Furnace as the sole ore-doubling mechanic. Just wanted to clarify this feature; I hope labeling it as a bug wasn't the wrong thing to do. It seemed like it was behavior counter to what was supposed to be part of the release. Thank you for taking the time to read my report, and thank you again for the amazing mod!

Hope to hear from you soon,

Carbon

**Comment by malte0811** [comment]
Those changes where about crushing ores with the engineers hammer, although i agree that it isnt made very clear in the changelog. The crusher is intended to be an ore doubling mechanic.

**Comment by Carbon-Key** [comment]
Ah, all right, if that is indeed the case then I will mark this issue as closed. That is definitely a bit confusing but I understand now.
