### ISSUE TITLE
[Crash: Immersive Engineering 0.6.4] ClientSide Voltmeter render crash (NullPointerException)

### ISSUE THREAD

**Issue by Carbon-Key** [BluSunrize/ImmersiveEngineering#811]
Hello,

I was playing around with the new Voltmeter (which is AWESOME) and I ran into a pretty nasty crash. It is only clientside but it would crash me on world-load as it tried to render the voltmeter in my hands. Initially I fixed it by deleting my inventory tags in level.dat and playerdata, that let me load the world again. I eventually figured out that I can spam the hotkey for an empty inventory slot as the world is loading to avoid the crash without needing to edit the nbt files. Here is one of the crash logs, they seem to all be identical but I have about 20 of them if you want to see more:

http://pastebin.com/VM1VHHyq

I am also obligated to inform you that I am running Fastcraft by Player from the IC2 team alongside your mod.

I've been messing around with it for an hour or so and I finally think I figured out how to reproduce it, I will try to use pictures to explain. The crash seems to occur when, with the voltmeter in hand, I switch from targeting the four-post bed from Decocraft to targeting the Decobench (also from Decocraft :P). It only occurs however when I am a specific distance from both of them. I am running Decocraft 2.2.1 and forge 1566.

When I look back and forth between the two blocks at this distance nothing happens:

![2015-12-23_02 38 06](https://cloud.githubusercontent.com/assets/10481639/11972954/7366bdd4-a921-11e5-864f-fa7758c369cd.png)

However when I stand back a ways and do the same motion I get the crash:

![2015-12-23_02 38 14](https://cloud.githubusercontent.com/assets/10481639/11972959/8231c444-a921-11e5-8c27-e3f829db48e6.png)

I've tried to include all the blocks that would be rendered in the same frame from a different angle here:

![2015-12-23_02 32 06](https://cloud.githubusercontent.com/assets/10481639/11972964/9691f92c-a921-11e5-880b-8c8aed82db45.png)

I tried disabling the targeting outline for the decocraft blocks in case that might be causing some issue, but I reproduced the crash in the exact same manner afterwards. I'm sort of stumped as to what could be causing the crash, but I would classify it as relatively severe as I was almost locked out of my world by it.  If you would like any further information from me I would be happy to give it, just let me know.

Hope to hear from you soon,

Carbon

**Comment by malte0811** [comment]
Duplicate of #777
We still don't really know what was going on, but @cobra added a workaround/null-check in #780, so it shouldn't crash any more

**Comment by cobra** [comment]
I have a suspicion what is causing this, will test that in a bit to satisfy my curiosity. That is a really nice test case, so it should be easy enough.

Nevertheless, this bug has been fixed in the upcoming IE release. If you want, you can test the [test version](https://www.dropbox.com/s/g8i136nx78o1wm0/ImmersiveEngineering-0.6.5-pre%2Bgit5d5852a.jar?dl=1) I built for the other issue - it might spam the log a bit, causing minor lag. Please be aware that this is an unofficial version, so do not distribute it or report bugs against it.

**Comment by Carbon-Key** [comment]
Ah, ok, thanks. I'll wait for the release, I think I can refrain from looking back and forth between a bed and a decobench with a voltmeter until then. :P Sorry for the duplicate, I guess I tried the wrong search terms or I am a noob at using the github search. Thanks again!

**Comment by cobra** [comment]
I could not reproduce this, no matter what I tried. The other crash log contained fastcraft as well, maybe that's the culprit here.
