### ISSUE TITLE
[Issue] Crusher is Invisible

### ISSUE THREAD

**Issue by AFaftFlyingWhale** [BluSunrize/ImmersiveEngineering#812]
When making a crusher, i am having a texture issue where it is rendering invisible. This is only happening when the excavator is rendered in the same chunk.

**Comment by cobra** [comment]
Can you please give some more information? I can build a crusher and an excavator in the same chunk and both are being rendered without any problem.

1. What version of IE are you using?
2. Is this a server or a singleplayer instance? Can you create a backup of this world in case someone needs a part of it? If yes, please do so before proceeding.
3. Does restarting the server or the client help?
4. What mods do you use? Any optimisation/tweak mods like optifine, fastcraft, fpsplus, cofhtweaks? If yes, does it happen without them?
5. Could you please provide a screenshot of your build setup, ideally before forming the multiblock with visible blocks? Preferably with the debug screen (F3) and, if you have NEI, chunk boundaries (press F9 until you get the green grid, F9 once more to get rid of it again) shown as well.
6. Did this happen only once or does it occur each time you break and re-form the multiblock?
7. Does it happen only at this position or can you move one or both machines some blocks and they are still invisible?
Does it matter in which orientation the two structures are built or whether they are mirrored?
8. When does it occur? Only when both are formed? Does the order of forming matter?
9. Does placing blocks directly adjacent to multiblock blocks change anything?

Possible duplicates: #737, #667, #665; paging @mindforger.

**Comment by mindforger** [comment]
if possible use https://dinnerbone.com/minecraft/tools/coordinates/ to estimate the file in your savegame and upload it somewhere ... i am yet not having any usable files from anyone unfortunately ... the only file i got contained "magically fixed" machines or machines that "were not present/built in that save"

**Comment by malte0811** [comment]
Maybe upload the `level.dat` file as well since that is where the block id's are stored. If i have both of those files, i should be able to look at the crusher in question in-game which would make debugging easier.

**Comment by mindforger** [comment]
i do not need the block ID, i need the stored Tiles with their corresponding "pos" value, as i spotted some irregularitys in "broken" multiblocks VS "working" multiblocks ... but i have no damn clue how this is even possible ... and the 2 examples i had so far looked like the structure were mirrored but i have no further proove as one was an excavator and the other was an arc furnace

**Comment by malte0811** [comment]
I wanted to look at these multiblocks ingame since i can actually see what happens to rendering then including setting breakpoints. And that doesnt work without block id's (i tried with the mca file we have, it was riddiculous, exploding fluids everywhere).
Also, do you know any program that runs on debian and preferably isn't too big (my internet connection is shit) that allows me to view those mca files?

**Comment by mindforger** [comment]
NBTExplorer is the only i know that works flawless with moddded and big stuff 
https://github.com/jaquadro/NBTExplorer

**Comment by BluSunrize** [comment]
Fixed with Version 0.7.1.2
