### ISSUE TITLE
LV power to GT wires on server not transferring power

### ISSUE THREAD

**Issue by bear989** [BluSunrize/ImmersiveEngineering#814]
I hooked a lv connector and wire to a GT 4x tin wire and there was no power transferred. After hat I connected straight to the LV distillery and it blew up. We then attempted to connect to the MV side of a GT transformer with the lv connector and wire and it still blew up. This is using GT5u5.09.16 and ImmersiveEngineering-0.6.1. we finally connected to a IC2 lv transformer and it showed input of 32.5 eu/t.

**Comment by BluSunrize** [comment]
did you change the config on IE wires?

**Comment by bear989** [comment]
no it is untouched, this is only a problem I found on a server. I have a MV
connector hooked to HV GT wire in SP and it is fine.

**Comment by Bitterholz** [comment]
@BluSunrize Didn't 0.6.1 have the transfer issues Cobra fixed in 0.6.3/4 too? 

@bear989 Have you tried upgrading to the latest Public Version? a.k.a 0.6.4 available [Here!](http://minecraft.curseforge.com/projects/immersive-engineering/files)

**Comment by bear989** [comment]
sorry I coppied the name incorrectly we are on 0.6.4 of IE

**Comment by bear989** [comment]
I just tried commecting HV wire (IE) to HV transformer (GT5) inverted to be HV in EV out and it blew up.strangely I have a MV (IE) connection to a HV (GT) battery buffer with no issues. these are both in SP. It was recorded if you want to see the connections
