### ISSUE TITLE
IE manual alters Ender IO stuff 

### ISSUE THREAD

**Issue by b0bst3r** [BluSunrize/ImmersiveEngineering#817]
Not sure if this is a bug with IE or EnderIO so (ping) @MatthiasMann.

ImmersiveEngineering-0.6.4.jar
immersiveintegration-0.6.6.jar
EnderIO-1.7.10-2.3.0.422_beta.jar
EnderCore-1.7.10-0.2.0.31_beta.jar

When holding the IE manual it makes EnderIO cables visible within EnderIO facade blocks (like holding the yeta wrench).

When right clicking on an EnderIO machine with the IE manual in hand it changes the side input/output properties.

It would appear the manual has some wrench properties :)

**Comment by BluSunrize** [comment]
Yeah, the Manual shares the same ItemClass as the Engineer's Hammer, and implements CoFH's IToolHammer. I /do/ however override "isUsable" to only work on getItemDamage()==0 and I feel like EIO might not check that =P

**Comment by cobra** [comment]
[There we go](https://github.com/SleepyTrousers/EnderIO/blob/master/src/main/java/crazypants/enderio/tool/ToolUtil.java#L98), exactly like this. EIO checks the class, but nothing else.

**Comment by BluSunrize** [comment]
Absolutely an EIO issue then =P
