### ISSUE TITLE
Crash when placing Router Rebourn Pickaxe in Charger (java.lang.ArithmeticException: / by zero)

### ISSUE THREAD

**Issue by Dyonovan** [BluSunrize/ImmersiveEngineering#819]
Crashlog: http://pastebin.com/upHpywjv

**Comment by cobra** [comment]
If container.getMaxEnergyStored seems to return 0, why is this item even implementing IEnergyContainerItem? What the hell is the dev doing there?

Independently of why it occurs, this should be caught by a trivial fix.

**Comment by BluSunrize** [comment]
Well cobra, it makes sense if you want to have an item class that has the energy containment optional. Think Tinker's Tools or EIO's DarkSteel.
The thing is that the space calculation is max-current, and that should not be >0 if max==0;
So I'll have to assume that Router Reborn (never heard of it btw.) returns a negative value for getEnergyStored(), which also sounds like a massive flaw on their side.

**Comment by cobra** [comment]
It appears that they abuse RF to repair item damage. There aren't negative values, but the value `getMaxEnergyStored()` returns (which is just `return getItemDamage()*10`) changes during processing. `getEnergyStored()` is always returning 0. Totally agreed, this is stupid.

**Comment by BluSunrize** [comment]
Yeah I looked at the source too, it's pretty bad. I'm tryign to find hte author on IRC, no luck so far.
