### ISSUE TITLE
Squeezer freezes server

### ISSUE THREAD

**Issue by Wikid** [BluSunrize/ImmersiveEngineering#82]
Placed a BC tank on one of the ports right next to the squeezer and it causes the server to freeze. It never gives a crash log.  Just disconnects everyone from the server and have to hard reboot the server. The fermenter has no problem with BC tanks. Also tried to place a Thermal Expansion tank right on a port also caused the server to freeze.

Wikid

**Comment by porteriscool** [comment]
Work around for time should be to place some type of piping that will extract from the squeezer and input from the piping into the tank.

**Comment by Wikid** [comment]
Just tried that and it still froze but I also did not realize it updated I was still on .1.9

**Comment by porteriscool** [comment]
You should update to the current release, and then inform this repository what occurs from there.

**Comment by Wikid** [comment]
Looks like it is semi fixed in the 2.3 release. it outputs to pipes just fine, but will not output to an adjacent tank. It will spit 144mb but will not continue. However no more server freezes, so was my fault for not upgrading first.

Wikid

**Comment by mindforger** [comment]
then please hit the close button on this issue and open a new one if really needed :)

**Comment by BluSunrize** [comment]
Exactly. Don't report on old versions.
