### ISSUE TITLE
Unable to set Arc Furnace special recipe type via Minetweaker

### ISSUE THREAD

**Issue by mdfntr** [BluSunrize/ImmersiveEngineering#820]
The Arc Furnace now has special recipe types that can be applied via the `setSpecialRecipeType` method on `ArcFurnaceRecipe`. Would it be possible to allow recipes created with Minetweaker to have special recipe types?

**Comment by mdfntr** [comment]
I am trying to create a pull request for this issue, but I am unable to set up a working dev workspace. Is there a list of required libraries somewhere?

**Comment by BluSunrize** [comment]
Yeah, I'll look into it.
