### ISSUE TITLE
High tickrate

### ISSUE THREAD

**Issue by ArcasCZ** [BluSunrize/ImmersiveEngineering#822]
Hello there!

Few days ago we found, that somethink is causing lags on server. We did dome investigation and got this: https://ctrlv.cz/shots/2015/12/28/5uU4.png

Do you know, where is a problem?

Server is running at KCauldron.

**Comment by BluSunrize** [comment]
What version of IE?

**Comment by ArcasCZ** [comment]
0.6.4

**Comment by Bitterholz** [comment]
can you run a VisualVM Smapling on your Server? That would be very helpfullif it coms to large amounts of Method calls.

@BluSunrize i'll double check this on our server!

**Comment by ArcasCZ** [comment]
It's not possible. We have only console and remote connection simply doesn't work. Today my friend and me tried to fix it, but it's almost impossible...
