### ISSUE TITLE
[v0.6.4] Engineer's Hammer giving 10 copper ingots per ore.

### ISSUE THREAD

**Issue by steamboat28** [BluSunrize/ImmersiveEngineering#823]
In a modpack I recently created, I noticed that ore processing with the Engineer's Hammer is on by default now, which pleased me. Until I went to process some copper ore and it spat out 10 copper ingots per ore. Full ingots, not dust. When I went to process my bauxite ore, it gave me 11 *copper* ingots each; no dust, no aluminum anything. Just tons of copper.

Thinking this was a mod interaction, I created a brand new vanilla Minecraft world where IE 0.6.4 was the only mod installed, and got the same reaction out of both copper and bauxite. I'll be disabling the hammer processing in the configs, but this is an item I thought should be posted.

**Comment by BluSunrize** [comment]
#795 
#779 
#766

Check previous issues.
