### ISSUE TITLE
Powered Lantern's not emitting light

### ISSUE THREAD

**Issue by Solace7** [BluSunrize/ImmersiveEngineering#825]
When provided with energy powered lanterns don't emit light or prevent mob spawns.

![2015-12-30_03 38 16](https://cloud.githubusercontent.com/assets/9976088/12050254/06f466f2-aea7-11e5-9478-a495d36de111.png)

**Comment by BluSunrize** [comment]
Yeah and you know why? Because you didn't read the book =)
It clearly states on the page for powered lanterns:
"To run these, you need to connect them directly to your power grid using wires."
You don't use connectors, you rightclick them with a wire.

**Comment by Solace7** [comment]
Ah, whenever I tried to connect them I'd use MV wire which doesn't connect. Had to use LV. Thanks!
