### ISSUE TITLE
[Suggestion] Rail gun Headshots

### ISSUE THREAD

**Issue by XFactHD** [BluSunrize/ImmersiveEngineering#827]
I know that the rail gun is still heavily WIP but today whilst shooting some mobs with the railgun I thought that it would be fun if I could headshot the bad guys.

**Comment by shobu9** [comment]
Like if you do a headshot it does a one shot kill ?

**Comment by BluSunrize** [comment]
Naaaah. Headshots are already in revolvers. Doing the same thing twice is kinda boring.

**Comment by XFactHD** [comment]
I agree with that.

**Comment by NanoCats** [comment]
That's kinda narrow minded isn't it? "One gun shouldn't headshot because this other one does"

what kinda logic is that.

**Comment by Alaberti** [comment]
There are a couple mods, Iblis and Iblis Headshots, that handle headshots. See if one of those meets your needs?
