### ISSUE TITLE
Connector outputs don't line up well with GT tiers

### ISSUE THREAD

**Issue by adudney** [BluSunrize/ImmersiveEngineering#829]
The default output levels of 256, 1024, and 4096 work fine for RF, but when converted to GT they are exactly twice the voltage expected (64 = 2 x LV, 256 = 2 x MV, 1024 = 2 x HV). Could the connectors utilize the GT amperage system to allow the connectors to connect to the equivalent GT tier? Since the throughput is configurable it might not always work as expected, but at least at the defaults it should output to the expected tier without exploding.

Perhaps as a workaround until a better solution is found, change https://github.com/BluSunrize/ImmersiveEngineering/blob/5dd3d2f5561177b3fe0adb59f573eaacd0204398/src/main/java/blusunrize/immersiveengineering/common/blocks/metal/TileEntityConnectorLV.java#L124 to send 2 amps of half voltage and change https://github.com/BluSunrize/ImmersiveEngineering/blob/195ac6b9c7e49746a54da801d34ddf67b1baa3d4/src/main/java/blusunrize/immersiveengineering/common/util/compat/GregTechHelper.java#L144 to utilize amperage? This might require using IEnergyConnected rather than IBasicEnergyContainer. ( https://github.com/Blood-Asp/GT5-Unofficial/blob/4fd0a7f47340b496ae2c24c0e43e8fead0407f50/src/main/java/gregtech/api/interfaces/tileentity/IEnergyConnected.java#L30 ) This is what GT uses internally for its cables.

**Comment by BluSunrize** [comment]
Nope. I know of the fact that IE wires are double, (or half of hte next step, if you will), but I don't intend to change that.
