### ISSUE TITLE
Blast Furnace doesn't accept charcoal

### ISSUE THREAD

**Issue by pixlepix** [BluSunrize/ImmersiveEngineering#83]
Despite the in-book description, the blast furnace doesn't accept charcoal. Coal coke works fine.

**Comment by porteriscool** [comment]
What version are you on, cause I just used the blast furnace with charcoal and it worked properly. Also, are you sure you used charcoal, you didn't use coal. Just making sure about that as well.

**Comment by pixlepix** [comment]
Version 0.2.3, literaly no other mods installed. And yes, it's charcoal.

**Comment by pixlepix** [comment]
Worth noting that a tooltip is present on coal coke but not charcoal

**Comment by porteriscool** [comment]
Can you take a screenshot of these problems.

**Comment by pixlepix** [comment]
Really not much to screenshot: http://puu.sh/iBvS9.png

(The burning progress bar is from using coal coke)

**Comment by DoughnutDev** [comment]
No were in the book does it say it accepts charcoal it only accepts coal http://puu.sh/iBEPn/8e18d8b49d.png

**Comment by pixlepix** [comment]
Think thats the coke oven.

ie.manual.entry.blastfurnace0=The Blast Furnace is used to increase the carbon contents in iron, turning it into steel. To achieve this, only pure, high-carbon fuels may be used for the furnace, specifically coal coke and charcoal.<br>The steel created in the blast furnace is an integral part of high-voltage architecture.

**Comment by DoughnutDev** [comment]
Oh your talking about the blast furnace sorry I miss read

**Comment by BluSunrize** [comment]
Charcoal in the Blast Furnace works perfectly fine for me.
http://puu.sh/iC1G5/2ad803b477.jpg

**Comment by BluSunrize** [comment]
Closed unless proven otherwise

**Comment by BluSunrize** [comment]
Alright, reported again in #148, but I think I've found the bug.
