### ISSUE TITLE
Workbench glitch

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#831]
Seriously have no idea how confine the issue to words, but [this video](https://youtu.be/xjnmXRDSfvg) (youtube) shows the glitch in full.

===================
IE build e7ad9eacec25f52b4168cc2adac4c8554c36f8f6

----------------------
EDIT: found some wording. If the user attempts to place the work bench into a position that the workbench cannot occupy, such as a 1m^3 space, the workbench will delete itself from the location the user attempted to put it but leave the second half, now orphaned, to replace the block that had obstructed the original placement. Take the below setup for example, if the user attempts to place the workbench in the gap between the four scaffolds, one of the scaffolds ends up being replaced by the orphaned Workbench tile entity; this change only persists until a block update occurs then the original block returns.
![image](https://cloud.githubusercontent.com/assets/3110986/12068885/24926ad4-afcd-11e5-9bf6-b1bdaa3dbafb.png)
![image](https://cloud.githubusercontent.com/assets/3110986/12068891/4b923876-afcd-11e5-8f71-0fa7461e1cd0.png)
![image](https://cloud.githubusercontent.com/assets/3110986/12068895/57933d50-afcd-11e5-8d20-a11ade49f6f9.png)

**Comment by BluSunrize** [comment]
long fixed
