### ISSUE TITLE
HV Relay consumes power

### ISSUE THREAD

**Issue by blarghhh** [BluSunrize/ImmersiveEngineering#833]
for some unknown reason, the HV relay consumes power.

ref:http://imgur.com/a/qXlZl

**Comment by blarghhh** [comment]
the wire coils constantly move power around, causing a looped power effect. similar to BC power transport pipes

**Comment by cobra** [comment]
Why did you close this?

**Comment by blarghhh** [comment]
Because it is not the relay consuming power. It is a power looping effect.

**Comment by BluSunrize** [comment]
Well then stop looping the power? x3

**Comment by tzpb8** [comment]
I had a similar problem but in my case it was solved by stopping to providing IC2 EU to the electric heat generator, even with just 1 copper coil, it sucks a lot of eu ( i only have hobbyist engine as a power source lmao, i need to work on that today!)

My capacitors was draining like crazy (even the HV ones) so i broke the power loop and it was fixed i think. Not sure if it was the electric heat generator or the power loop that was the problem tho :P

**Comment by empirebuilder1** [comment]
The mod accounts for power losses in cables, I think the default is 0.025% power lost per 16 blocks travelled for copper/electrum wires and 0.010% for aluminum (HV) wires. If power is looped, the losses will infinitely stack until there is no power left in the system.
