### ISSUE TITLE
Battlegear 2 Compatibility [Graphical Glitch]

### ISSUE THREAD

**Issue by Alaberti** [BluSunrize/ImmersiveEngineering#835]
Versions: 0.6.5.1 IE, 1.0.8.2 Battlegear 2

Seems holstering IE weapons on the hip or back causes the below graphical glitches. Not sure if it's them or you, but seemed reasonable to start here. May also affect iChun's backtools, untested though.

![2016-01-01_15 56 23](https://cloud.githubusercontent.com/assets/10929796/12071223/a6fe4a0a-b0a0-11e5-9015-a7ff34d5303b.png)
![2016-01-01_15 56 38](https://cloud.githubusercontent.com/assets/10929796/12071222/a6fd0a64-b0a0-11e5-99a0-690024ccf34e.png)
![2016-01-01_15 56 47](https://cloud.githubusercontent.com/assets/10929796/12071224/a6fed5ce-b0a0-11e5-9030-ae70d7bf6ac1.png)
![2016-01-01_15 56 11](https://cloud.githubusercontent.com/assets/10929796/12071225/a700990e-b0a0-11e5-92bc-5f4b6c69231f.png)

**Comment by XFactHD** [comment]
The railgun is blacklisted for backtools but I don't know if it is possible to do the same thing for battlegear.

**Comment by BluSunrize** [comment]
If Battlegear has IMC I'll fix it, otherwise, I won't bother.

**Comment by Alaberti** [comment]
Looks like it does: https://github.com/Mine-and-blade-admin/Battlegear2/blob/1.7.10/battlegear%20mod%20src/minecraft/mods/battlegear2/Battlegear.java

**Comment by BluSunrize** [comment]
UUh. No. It doesn't. There is no message to prevent rendering.
You're shit outta luck, buddy x3

**Comment by Alaberti** [comment]
Can't say I didn't try haha alright thanks for looking into it!
