### ISSUE TITLE
Can't use hopper anymore for electrode insertion

### ISSUE THREAD

**Issue by rahangar** [BluSunrize/ImmersiveEngineering#836]
Today I upgraded from 0.6.4 to 0.6.5.1. Not sure when this changed, as I have not used the arc furnace in a while.  But I used to be able to drop a bunch of electrodes into a hopper, which is placed above the electrodes.  And the arc furnace accepted them as the old ones were used up.  The arc furnace doesn't seem to accept insertions from hoppers anymore.  Was this an intentional change?

Also, in the latest changelog I saw this comment:
- fixed ArcFurnace manual entry stating automatic insertion of electrodes as possible

The above comment can be read two ways.  
1.  The manual was incorrectly indicating that the automatic insertion is possible
2.  The manual was fixed, indicating that automatic insertion is possible.

But when I went to the manual, I did not see an update section for 0.6.5.

**Comment by XFactHD** [comment]
This is intended. It was changed for 0.6.4 IIRC.

**Comment by cobra** [comment]
This is very much intended. The insertion possibility was removed, but the manual wasn't updated when this happened. Now everything is as it should be.

**Comment by rahangar** [comment]
ok; thanks.  Any tips on how to automate?  I tried talking to the arc furnace via computercraft, but no luck.

Having said this, I half enjoy my trips to the arc furnaces (to feed it electrodes) since they are so fun to watch.

**Comment by cobra** [comment]
The electrodes are intended to be non-automatable, you have to do manual maintenance.
Computer support is coming in the future, but won't change this.

**Comment by BluSunrize** [comment]
Yeah what cobra said ^^

**Comment by RobLoughrey** [comment]
Not a fan of this change. Most of the fun in FTB for me is making a giant automated factory. Having to walk around doing nothing more than effectively pushing a button to keep my refining going is boring. If you want to go this way why bother allowing me to automaticly insert the ores? You might as well, because I'm still going to have to babysit the machine.

**Comment by BluSunrize** [comment]
Mate, this change 1.5 years old. Do you really think I'm changing my opinion *now*?

**Comment by RobLoughrey** [comment]
Nope, but I still get to have mine. Sorry you don't want the feedback. I love your mod otherwise, I've been mesmerized by watching my 5 metal formers stamping things out.

**Comment by SuperSandro2000** [comment]
> Do you really think I'm changing my opinion now?

yes

**Comment by Pelotrio** [comment]
https://user-images.githubusercontent.com/45769595/189549181-ba9c751b-42d5-46e0-8a19-04ad4433c633.mp4

Found a workaround

**Comment by BluSunrize** [comment]
I mean, yes, cheating is a viable workaround to most things ;)
