### ISSUE TITLE
arc furnace shows electrodes externally even when they have depleted

### ISSUE THREAD

**Issue by rahangar** [BluSunrize/ImmersiveEngineering#837]
Please see the image in the background - all 3 electrodes are visible externally even though two have been depleted.

![2016-01-01_11 18 39](https://cloud.githubusercontent.com/assets/3137077/12071591/a6f25b22-b079-11e5-854a-092d21dd1cf7.png)

Here's a different arc furnace with a similar problem.  In this case all 3 are depleted.

![2016-01-01_11 21 17](https://cloud.githubusercontent.com/assets/3137077/12071593/d8266116-b079-11e5-8124-079b7a8e68c1.png)

A third arc furnace, that seems to be working properly:

![2016-01-01_11 23 28](https://cloud.githubusercontent.com/assets/3137077/12071599/137614e6-b07a-11e5-8f7f-b20b472b4eee.png)

**Comment by BluSunrize** [comment]
Intentional. Electrode instertion is no longer automateable. That change was deliberate and it was detailed in the changelog.

**Comment by cobra** [comment]
@BluSunrize did you just mix up #836 and this one? This issue looks like a bug, probably missing a rerender trigger somewhere.

**Comment by BluSunrize** [comment]
I absolutely did. Sorry 'bout that.

**Comment by malte0811** [comment]
This is my fault, you need to add `updateClient = true;` to the code that runs when an electrode depletes. I forgot about that case when i fixed the fps lag with running arc furnaces.

**Comment by BluSunrize** [comment]
kay, I'll see to it
