### ISSUE TITLE
Dropping conveyor doesn't spread items out in Arc furnace.

### ISSUE THREAD

**Issue by BrizzleMFD** [BluSunrize/ImmersiveEngineering#839]
FTB infinity 2.3.3
Immersive Intergration 0.6.5.1

Update to make the arc furnace spread items out rather then place them in the first slot works fine if using hopper. The new Dropping Conveyor belt however doesn't work the same and continues to place in first slot without spreading.

**Comment by cobra** [comment]
This does not make any sense. There is no distinction between what is inserting, each insert operation uses the next slot. Be aware that stacks of items won't get split up when they are inserted at once.

**Comment by BrizzleMFD** [comment]
Oh I see. So the dropping conveyor inserts however much it receives at once. That's why the vanilla hopper is able to get them to spread out in the inventory. That makes since. At least now I understand how the spreading out in inventory works.
