### ISSUE TITLE
[Suggestion] Vertical Item Transport

### ISSUE THREAD

**Issue by pip69** [BluSunrize/ImmersiveEngineering#840]
Just something to send items straight up.
If it was 2x1 it could have an up & down side
Right click a section with an Item Router to install that ability.
Add a reverse Dropping Conveyor as a new item or have that option when you right click with the hammer. This would be good on its own,allowing a Router to move items up 1 block.

**Comment by AEnterprise** [comment]
you can make something that goes up and down in an 3x3 area,  one conveyer looping around going up, an open crate or similar can be used to drop items down though the hole in the middle

**Comment by PrincessRTFM** [comment]
I did that on my world, just with a couple random (cool-looking) items as a display feature :P
