### ISSUE TITLE
[Suggestion] Fluid pipes with glass windows.

### ISSUE THREAD

**Issue by codewarrior0** [BluSunrize/ImmersiveEngineering#841]
I'd like to see a craftable variant of the fluid pipe that adds a glass window, for seeing which fluid is in the pipe and how full the pipe is.

Similar to Factorio's fluid pipes:

![example-oil-cracking](https://cloud.githubusercontent.com/assets/307683/12080663/9d6d2ff4-b205-11e5-974d-22e4092c69dc.png)

**Comment by BluSunrize** [comment]
Pipes don't store fluids internally.
Also, IE is /not/ the Factorio mod.

**Comment by codewarrior0** [comment]
Huh. So I can use the same fluid pipe to transport multiple liquids, like an EIO fluid conduit? That's surprising.

**Comment by BluSunrize** [comment]
Considering that it transfers fluids pretty much instantly, yes it can.
