### ISSUE TITLE
Arc Furnace not producing Vibrant Alloy

### ISSUE THREAD

**Issue by DrWookie** [BluSunrize/ImmersiveEngineering#843]
Not getting Vibrant Alloy from Arc Furnace using recipe stated. 
Running:
ImmersiveEngineering-0.6.5.1.jar

![novibrantenderdust](https://cloud.githubusercontent.com/assets/16535423/12085373/9e94ad2c-b27c-11e5-8de7-64bbf6eaa9cc.jpg)
![novibrantenderpowder](https://cloud.githubusercontent.com/assets/16535423/12085346/52808406-b27c-11e5-9423-7375ce2c2d6d.jpg)

Tried both ender powder/dust.

**Comment by BluSunrize** [comment]
Yeah, recipe conflict with the energetic one. I'll fix it.

**Comment by DrWookie** [comment]
Thnx.

**Comment by Haggle1996** [comment]
This is still not fixed as of 0.7.7

**Comment by mallrat208** [comment]
The Fix was to Change the recipe. To get Phased Gold you have to run an Energetic Alloy  in with enderpearl dust.

**Comment by Haggle1996** [comment]
Ah, yes, my derp. I have a minetweaker script that's breaking it. Nevermind. Nothing to see here. Move along. :S
