### ISSUE TITLE
[Suggestion] Conveyor Splitter

### ISSUE THREAD

**Issue by Bitterholz** [BluSunrize/ImmersiveEngineering#844]
I'd like to see a Small Conveyor Multiblock named the "Conveyor Splitter".
It would serve as a in-line splitter splitting the contents of one Conveyor 50/50 into 2 parallel Conveyors.
Would be real nice not to have to do it via Hoppers since they can't guarantee a steady 50/50 split of the incoming ressources.

**Comment by BluSunrize** [comment]
ItemRouter splits randomly, and Immersive Integration has a RoundRobinRouter.
