### ISSUE TITLE
Item loss in assembler if all slot are full

### ISSUE THREAD

**Issue by quentfr21** [BluSunrize/ImmersiveEngineering#846]
hello

ImmersiveEngineering-0.6.5.1

easy to reproduce 
just try that without ouput on assembler 
http://rousteurs.free.fr/itemloss.png
and gold ingot was just lose

thanks

**Comment by quentfr21** [comment]
probably fixed in 0.7 

9c2e111

**Comment by BluSunrize** [comment]
Correct. I just didn't close this yet because I haven't merged the branch with master.

**Comment by quentfr21** [comment]
fixed in 0.7
thank
