### ISSUE TITLE
Revolver Barrel / Base Panel recipe issue

### ISSUE THREAD

**Issue by tecer0** [BluSunrize/ImmersiveEngineering#847]
Hello,
i updated immersive at last build ImmersiveEngineering-0.6.5.1 (from 0.6.4) and now i have a problem with recipe "Base Panel" of rotary craft (RotaryCraft 1.7.10 V10d)

Base Panel of rotary required 3 HSLA Steel Ingot
Revolver Barrel of immersive required 3 Steel Ingot

When i try to craft base panel i see it as a result but i always get Revolver Barrel

i tried with vanilla crafting table, machinist workbench (thermal expansion) and crafting terminal (applied energistics).

thanks in advance,
TeCer

**Comment by XFactHD** [comment]
This should actually not happen as RCs HSLA Steel is for balance reasons not ore-dicted the same as IEs Steel. This means that another mod has probably fucked up the ore dictionary.

**Comment by BluSunrize** [comment]
Yeah, and there /are/ crafting tables that can work against conflicts I'm pretty sure.
I'm also not changing that recipe for RotaryCraft alone, so you'll have to Minetweak it if you must.
