### ISSUE TITLE
Forming Excavator multiblock

### ISSUE THREAD

**Issue by Staegrin** [BluSunrize/ImmersiveEngineering#85]
Playing in single player and testing all the things.

The bucket wheel and excavator multiblocks won't form in new worlds generated after the mod (immersive engineering) has been installed. Worlds that were created before the mod was installed allow the multiblock to be formed.

![2015-06-25_01 02 44](https://cloud.githubusercontent.com/assets/8494635/8343470/f11daa10-1ad5-11e5-9e55-ff6d6493442c.png)
Old world shift right clicking forms the multiblock.

![2015-06-25_01 03 39](https://cloud.githubusercontent.com/assets/8494635/8343493/20c54aca-1ad6-11e5-936a-ca2cf14c1e5f.png)
New world Shift right clicking does nothing.

Have tested with 4 worlds. 2 created before the mod was installed and 2 created afterwards.

**Comment by BluSunrize** [comment]
Structure forms fine for me. Overall screenshot of the structure please?

**Comment by Staegrin** [comment]
Sorry for the time this response took (was at work). After restarting the game two times it will now work. Still have no idea why I didn't want to work in the first place. Thanks for the help and sorry for wasting your time.
