### ISSUE TITLE
Java error with "ModelShaderMinecart"

### ISSUE THREAD

**Issue by hilerjm** [BluSunrize/ImmersiveEngineering#851]
Just found a bug while playing on the SpaceAstronomy Pack. 

I have a computercraft program running to control EnhancedPortals3 and when I open a portal to go to the space station from Galacticraft, it crashes giving me this error:

Java Exception Thrown:
java.lang.NoClassDefFoundError: blusunrize/immersiveengineering/client/models/ModelShaderMinecart

I don't know if this is caused by your mod, computercraft, enhancedportals or galacticraft but I figured I would post It here and see what you guys think.

Mods:
ImmersiveEngineering-0.6.4
GalacticraftCore-1.7-3.0.12.404
Galacticraft-Planets-1.7-3.0.12.404
ComputerCraft1.75

**Comment by BluSunrize** [comment]
I'd like the whole log, and as a pastebin please.

**Comment by hilerjm** [comment]
I apologize, its the computercraft program that is crashing not the pack. So there is no log. Do you think this is a computercraft issue? I'm sorry for wasting your time, I just didn't know where to start trying to figure this out.

**Comment by BluSunrize** [comment]
I said: Give me the log.

**Comment by BluSunrize** [comment]
Also, show me the CC program. Also a pastebin.

**Comment by hilerjm** [comment]
computercraft program: http://pastebin.com/vE5wdWy9
direwolf20 buttonapi: http://pastebin.com/wexewXBT
ServerLog(snippit): http://pastebin.com/hQ5uFQEQ
ServerLogFull: https://www.dropbox.com/s/27ovly5swj2evwd/fml-server-latest.log?dl=0
Its the only log I can find, with the error in it, the whole thing was too large for pastebin. 
Screenshots:
http://tinypic.com/r/2yzmq8n/9
http://tinypic.com/r/73fgqe/9
http://tinypic.com/r/25inp7n/9

**Comment by BluSunrize** [comment]
Very interesting. I can identify the error in this. The program accesses functions of the portal frame which force a world load. And because this happens on the ComputerCraft thread, it is mistakenly identified as a clientside thread, even though it's serverside.
I will probably be able to fix this, but the next release of IE is still a few days off, sicne I plan to move the version number to 0.7 rather than 0.6.6. So you might have to live with this issue for a while :/

**Comment by hilerjm** [comment]
I can live with it, thank you for the info though that's an interesting bug. Hope you get it fixed, good luck and can't wait to see what you have planned for the future!

**Comment by BluSunrize** [comment]
Fixed!
