### ISSUE TITLE
not sure if this this mod but crash on world start D:

### ISSUE THREAD

**Issue by monkeybee11** [BluSunrize/ImmersiveEngineering#853]
not sure if it is this mod casuing the crash or if its a conflight with some other mod but it was only after adding this mod it started crashing

http://pastebin.com/2ZA2dsNC

**Comment by BluSunrize** [comment]
I don't see anything pointing to IE here...

**Comment by cobra** [comment]
Me neither, this must be caused by some other, probably outdated, mod still using modstats.

OT, unrelated to this crash: you should update java, 8u66 is the current one.

**Comment by monkeybee11** [comment]
it must of just been timing that it started crashing after adding this mod sorta found out what was causing it ever Reliquary or thaumic exploration sry for wasting your time D: will go report to both of them now :3

**Comment by monkeybee11** [comment]
http://pastebin.com/UcSkU1GF
this is a crash report that has this mods name in it tho but me was downdating the mod at 1 point of trying to get my game to work but it was happeneing on the newest verion of the mod as well (got a long list of crash reports from removing mods)

**Comment by cobra** [comment]
Looks like the original issue is caused by Reliquary, they seem to be using modstats [here](https://github.com/TrainerGuy22/Reliquary/blob/a439a2a3726473e5010b52f67ffeb8eb50554dc6/src/main/java/xreliquary/Reliquary.java#L75).

I don't know what happened in the second log you posted, that doesn't make much sense for me.

**Comment by monkeybee11** [comment]
same as the 1st happened at world start but the only reason me am posting that 1 there is purly 

at blusunrize.immersiveengineering.common.EventHandler.onLoad(EventHandler.java:88)

and thx for letting me know what mod was causing teh crashing :)

**Comment by XFactHD** [comment]
Could you please try redownloading the mod, it seems that the .jar is corrupted.

**Comment by monkeybee11** [comment]
what 1 ? ie? as me said that crash report was from where me was trying to downgrade it to see if it was just a bad verion seeing its still in beta  so its been redownloaded like 4 times :P but ya its working now
