### ISSUE TITLE
[API] IExternalHeatable mistakable

### ISSUE THREAD

**Issue by MrRiegel** [BluSunrize/ImmersiveEngineering#854]
Hi,
in your interface you wrote: 
'@return the amount of RF consumed that tick. Should be lower or equal to "energyAvailable", obviously'.
That's mistakable cause you only could consume maxExtract of the external heater (256 default).
Would you mind to add this information?
I needed 2 days to realize why my implementation isn't work.

edit: maybe you could change the method to
public int doHeatTick(int energyAvailable, int maxExtract, boolean redstone)

**Comment by BluSunrize** [comment]
Well tbf, what /does/ require 256 RF/t?

**Comment by MrRiegel** [comment]
A Furnace that cooks a stack of items in 10 seconds ;)

**Comment by BluSunrize** [comment]
which is hilariously overpowered. xD

Anyway, you figured it out, I'm sure others will.
