### ISSUE TITLE
Tile entities timing a bit high overall

### ISSUE THREAD

**Issue by Axylxys** [BluSunrize/ImmersiveEngineering#855]
Using IM 0.6.4 and doing a regular opis check on the server while we're progressing, i found out that overall most of the IM blocks tend to be a bit high on their timing.

Note that this is just a general feeling, not a server crash, huge lag spike or anything, i'm just used to monitor carefully the timings to pick the best blocks when i have a choice, and so far what i noticed:

-the crusher has an average 30-35μs. While understandable because of its multiblock nature, it seems way too high for what it actually does. Any basic Mekanism/Thermal/EnderIO machine clocks at around 5μs
-the connectors have a 12 μs mean value, and they're quite easy to spam everywhere. That makes the IM cables cost a lot more server ressource than anything else and a single connector actually has more tick time than entire machines from some mods
-the HV capacitor clocks 3 μs for a single battery block, making it a much worse general battery than the EnderIO highest tier capacitor clocking at 1,8 μs

All of these add up quite fast in a large base.

I really like the mod ideas and visuals but i'm a bit scared with these early results, that's why i thought about that report, is it a known issue or something subject to improvement later on ? With a big modpack, paying attention to server tick time is a basic rule to make sure the game remains playable, and it's quite a letdown to see IM clocking so high with even first tier machines. A max tier Mekanism factory running at full speed and processing a ton of stuff clocks lower than a single LV connector with a cable, that seems a bit scary.

So i hope something can be done for server performance as i envisionned using mainly IM for cables and infrastructure and i fear it's gonna end up as a huge lagfest. I would really like using IM blocks rather than their counterpart from other mods but, with such a performance difference it seems hard to justify. :( That's a bit sad as this mod is really awesome for looks and feels and i wish i could use it everywhere !

**Comment by XFactHD** [comment]
Please retest this with the latest version and report back.

**Comment by Axylxys** [comment]
I just updated, i made the modpack on 29th december so i totally missed the last version, sorry for that !

However, the issue remains, after the update only the crushers went down a bit in tick time (to an average 25-27μs). The connectors especially remain quite high (12-15μs).

About those though, while testing stuff around, i noticed they went down a bit when i removed the Powered Lamp from the chain.

I had a chain like that: Power Source (Mekanism power cable) with a connector on it, then another connector, then the lamp, and a last connector giving the power to the AE system. All of them LV connectors, linked with LV cable. Replacing the lamp with another connector brought the mean value down to 10μs from 15μs.

So it seems most of the 0.6.4 observations remain valid, though there is room for fiddling and i suspect the results could change drastically with the setup.

**Comment by XFactHD** [comment]
One thing I have to tell you: You can't compare the tick time of a multiblock with the tick time of a single block machine and in terms of the connectors, two of them with a wire in between produce much less load then the 16 or 32 blocks of EnderIO conduit you need for the same connection.

**Comment by Bitterholz** [comment]
You can't compare the tick time of a multiblock with the tick time of a single block machine and in terms of the connectors, two of them with a wire in between produce much less load then the 16 or 32 blocks of EnderIO conduit you need for the same connection.
^^^^
THIS

**Comment by BluSunrize** [comment]
the connectors check a whole net for outputs. A conduit just transmits to the next block.
People really need to stop comparing tech mods like this. Every author is different, every code style is different, every resultign code differs in performance.
If you don't like IE's performance, you are free to fix it with pull requests. But you can't just go "Your tick times are high, fix it." Do you really think I don't program for optimal efficiency? I write my code to the best of my abilities, you can't just ask me to suddenly improve it beyond that.

**Comment by Axylxys** [comment]
Well, no need to get defensive on this, i didn't mean this as a useless "your mod is badly optimized and sucks" post, more a constructive feedback to maybe help you find some overlooked issues or something, or even test stuff on my own if you ever needed that (because it's a beta, right ?). I know most peoples don't monitor stuff with Opis or pay attention to this, i do and i thought making a report could help, as i've done previously with other mods. That's about all there was to it.

As a matter of fact, i like IM overall, the ideas and visuals are great and it was a new pick for me so i'm monitoring it to find out how it's doing, and since i like the mod, trying to bring some contribution felt natural.

As for the long distance load, that was indeed the idea i got after checking the Opis reports: use IM for long range power transfer and looks. Now i think that remains a weak spot of the mod, i'm not saying it's badly coded or whatever (i'm not a modder myself and i wouldn't step on that field), just pointing out something that looks odd as a mod user. If that's fine for you and you feel it doesn't need improvement, i'll just accept that fact and deal with it. That's your mod and your work, please don't feel offended because of a simple report, there was no mean purpose behind. Actually, if i didn't like the mod i wouldn't take that time to bother and just uninstall it like i've done so many times.

I think comparing mods can be healthy though, especially with large mod packs being quite popular. I think IM has some very clever and original design choices (i said quite a few times while testing the mod "woah, that's indeed a nice idea there !) with a strong emphasis on look and feel, i would just be sad if in the end the mod isn't all that useful. And it's more likely heading that way because, let's be honest, it's vastly underpowered compared to most of the new mods. I feel like it's balanced with the 1.4.7 standard, where Railcraft boilers were all the hype. 

Now, as much as i like the feeling of the mod, it's a bit hard to justify using most of the stuff IM brings into a modded environement. That was the ultimate reason behind this post, as i don't even mind that much for the scaling (i'd rather use a x2 ores than a x10 if i find that more fun and fitting in my base), but being punished on server side too feels a bit much (even if it's not that bad, i'm not trying to overdo it). And while the mod looks awesome, it just feels wrong to use it only as decorative blocks and fancy cables when it could be sooooo much more.

That's just my point of view though, and if anything i hope this mod will keep improving as it's one of the greatest ones i've seen in a while when it comes to ideas and design.

**Comment by XFactHD** [comment]
I wouldn't say that it is hard to justify the usage of IE machines. I am building a completely OP void dim base in survival but I am using the arc furnace over the induction smelter from TE just because it looks cooler, even though it is massive compared to the one block space the induction smelter needs.
To be honest, no matter how OP your base is, IE always offers some things that you can use in your base.

**Comment by malte0811** [comment]
@Axylxys I tried some things to improve the performance of the crusher in IE version 0.7, could you check whether tick time is still high in 0.7? In my test cases the crusher was rarely above 15 us (with the old code), but i didn't use Opis for measuring since that doesn't work in a development environment (my method of measuring is probably even better than using opis, but only possible with have access to the code).

**Comment by Axylxys** [comment]
I just updated to 0.7.1 and tested that, the crusher tick time has been nearly halved !

I'm using two crushers, one of them processing ores and random stuff, and one of them acting as a mob grinder with endermen and various mobs falling into it, the mean value per block is about 0,8μs and the total for both crushers is sitting at around 42μs with both being active at the same time.

Before, i got them as high as 120μs total, with average being around 80, not sure why it used to vary like that. Anyway right now it's much better, so thanks a lot of that, whatever you changed seems effective.

**Comment by mskurnik** [comment]
I am on version 0.7.5 and my LV connectors are getting 10-333μs.  It would be nice if we could attach TD power duct to the lamps or even a powered wooden post where I can feed power to everything from underground.  Anyways I have to agree with @Axylxys, the tick times for some of the machines do seem to be a bit wonky.
