### ISSUE TITLE
Blast Furnace doesn't process Minetweaker ItemStack with multiple items

### ISSUE THREAD

**Issue by Haggle1996** [BluSunrize/ImmersiveEngineering#857]
Using Minetweaker to add a material to the blast furnace:
mods.immersiveengineering.BlastFurnace.addRecipe(<HarderOres:dummyOreIron>,<HarderOres:ore_chunk:8> * 3, 4800);

Note, the input stack is set at 3 items. This correctly displays in NEI, showing that three items are needed. However, the Blast Furnace only consumes 1 item per operation.

**Comment by BluSunrize** [comment]
Well it was never really designed to do multiples. However, since I've rewritten it for 0.7, it'll be fixed wit the next major version.

**Comment by Haggle1996** [comment]
You, sir, continue to be awesome. Thank you and thank you for the awesome mods.

**Comment by BluSunrize** [comment]
Fixed!

**Comment by Haggle1996** [comment]
Related issue: It now accepts multiples per the minetweaker script; however. If a partial stack exists, it will process the recipe as normal. For example, the minetweaker recipe says you need 4 blocks in to get 1 block out. If only 1 is in the furnace, it will process as if all 4 blocks were present.
