### ISSUE TITLE
[suggestion] Shader to sheep

### ISSUE THREAD

**Issue by karakufire** [BluSunrize/ImmersiveEngineering#859]
make colorful sheep.

**Comment by BluSunrize** [comment]
No. I already replaced cart renders, and that was a pain in the ass.

**Comment by James-T-Oudvoure** [comment]
Besides, that would look ugly as all hell.

**Comment by karakufire** [comment]
I see

**Comment by karakufire** [comment]
I'm just knowing [AtomicBlom/ShearMadness](https://github.com/AtomicBlom/ShearMadness) mod.  
Could you consider the idea again? I guess this mod teaches us what is "colorful" sheap.

**Comment by BluSunrize** [comment]
I might consider it. Won't nail myself down on it rn

**Comment by karakufire** [comment]
Thank you for positive answering.
