### ISSUE TITLE
[Suggestion] Redstone Breaker

### ISSUE THREAD

**Issue by DrWookie** [BluSunrize/ImmersiveEngineering#860]
I was slightly disappointed to find out the Breaker Switch no longer accepted HV wire. As this block alone looks awesome and "flipping" the switch on or off gives a real world sense that your actually shutting something off (or on). I notice now the new connection for HV wire is the Redstone Breaker which is fine in my book as you've keep the ability in-game for HV connections thus you've thought ahead and I congratulate you on such a fine design. However, I feel the block should have a name change to "HV Breaker / HV Breaker Switch" and include an actual switch or light switch type added to the block itself instead of adding an outside source to trigger the blocks functions. I've included a pic of where the switch could be placed if implemented.

![rsb](https://cloud.githubusercontent.com/assets/16535423/12224011/b01a0ce6-b7a3-11e5-89bf-304f88147b50.jpg)

In-fact with the way the texture sits in the picture it almost seems like there's a button you could press above the redstone input.

**Comment by BluSunrize** [comment]
your voice would have been required before, when this topic was actually being discussed.
I don't want to have to change these functionalities again, instead, you can easily use the normal breaker switch as a lever (it outputs redstone signals) and use it to control an RS Breaker.
