### ISSUE TITLE
Workbench munches first item fed to it via conveyors

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#861]
When an item is inserted into the workbench (either block) via the conveyor for the first time since placing the workbench, regardless of if the item is even valid to be accepted (such as cobblestone or inversely the RailGun), said item is destroyed without indication. After consuming the item, the workbench refuses to accept any further items from any side of the block until it is break-replaced.

=========================
On a side note: i am quite sure the below is not intended functionality...
![image](https://cloud.githubusercontent.com/assets/3110986/12227283/cf3e5498-b7de-11e5-8bc0-4360328ec3e9.png)

==============
tested against IE build a86ffd0

**Comment by BluSunrize** [comment]
I can see Malte fixing this, so I'm not gonna bother. x3
