### ISSUE TITLE
stuck in loading ...

### ISSUE THREAD

**Issue by abdullamu** [BluSunrize/ImmersiveEngineering#863]
hello its been half year since i last played minecraft because of IM after some update which i forgot which one everytime i try to load minecraft it stuck in immersive engineering loading forever until i close it and today i came back hoping its fixed but nothing , i turned every mod off except IM and fastcraft 1.16 to find out theres problem between both IM doesnt load and get stuck when fast craft exists fastcraft is really important mod for me as it gives me 20 fps boost to make minecraft playable  can you please fix it because its been half year or less this is really not nice since im enjoying IM and Fastcraft
thank you 

http://pastebin.com/Ebfmy1Vp

**Comment by BluSunrize** [comment]
First of: Immersive Engineering is abbreviated IE, not IM. That's just gonna cause confusion.
If your FPS are bad, maybe consider not using a ResourcePack, from your log it looks like you are.
Then, are you sure this is the complete log? It looks somewhat incomplete.
Finally: Could I get a modlist? Because your log doesn't provide one.

**Comment by abdullamu** [comment]
sorry its too late now here in europe and im sleepy, yes you are right IE,
 my fps are bad either way but with fastcraft it makes it work steady 25-30 fps without fastcraft its from 1 -30 goes down when generating new terrain or moving ,
 the mods are only 2 was activate at the time of the log IE and Fastcraft everything else was off and the log is not complete because its stuck like this forever nothing happens but when i turn off fast craft everything loads fine and the issue was after one of the updates for immersive engineering the issue started .

**Comment by BluSunrize** [comment]
Try disabling "Arc Furnace: Recycling" in the config.
What version of IE is this?

**Comment by abdullamu** [comment]
the latest IE 0.6.5.1 and i think the issue started after 0.4 and its stuck when forge loading the textures .

**Comment by theunkn0wn1** [comment]
Your log states that your minecraft instance is corrupted or has otherwise been tampered with. Please attempt to reproduce the issue after retrieving a fresh MineCraft installation
```
[23:43:13] [main/INFO] [FML]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
[23:43:13] [main/ERROR] [FML]: The minecraft jar file:/D:/Games/Minecraft/Install/versions/forge-10.13.4.1614/forge-10.13.4.1614.jar!/net/minecraft/client/ClientBrandRetriever.class appears to be corrupt! There has been CRITICAL TAMPERING WITH MINECRAFT, it is highly unlikely minecraft will work! STOP NOW, get a clean copy and try again!
[23:43:13] [main/ERROR] [FML]: FML has been ordered to ignore the invalid or missing minecraft certificate. This is very likely to cause a problem!
[23:43:13] [main/ERROR] [FML]: Technical information: ClientBrandRetriever was at jar:file:/D:/Games/Minecraft/Install/versions/forge-10.13.4.1614/forge-10.13.4.1614.jar!/net/minecraft/client/ClientBrandRetriever.class, there were 0 certificates for it
```

**Comment by abdullamu** [comment]
i did what you asked , first disabling the arc furnace didnt do it still getting stuck
making fresh installation didnt do it still getting stuck in loading - initializing mods phase 2 , initialization - immersive engineering , texture creation - stitching 1/3
3rd updating fastcraft to 1.21 fix the problem but 1.21 is a big problem because it makes minecraft looks ugly and make it preform really bad .

**Comment by XFactHD** [comment]
This could be caused by the texture maps of the revolver and Fastcraft eventually not taking into account that some modder could be using them. The last thing the log says is that IE attempts the potion array, but Fastcraft shouldn't influence that.

**Comment by abdullamu** [comment]
Yes its always used to get stuck in revolver texture and it happened after revolvers added to the mod and i was looking into the config to disable it bcz its useless for me i want the machines and this thing causing problems ,i hope in the future there will be option to disable enable every item in the mod like some other mod that do that . anyway thank you all and i hope it will be fixed and thanks alot to the modders for the great mod .:)

**Comment by BluSunrize** [comment]
I /can't/ fix it. As far as I am aware, I'm doing everything right. If an updated fastcraft fixes it, update your fastcraft. And if you game runs like crap, maybe you just don't have the PC to play modded Minecraft with.
But my revolver sheet stitching has worked perfectly fine for literally everyone else, this is the first time I hear of this (in fact, if the issue is really that old, why did you never report it before?), so don't ask me to fix what I can't even discover to be broken.

**Comment by mindforger** [comment]
>>making fresh installation didnt do it still getting stuck in loading

can you provide a new log ?

**Comment by abdullamu** [comment]
@mindforger  here you go its the same the log is short because there are 2 mods only and it gets stuck in loading IE https://gist.github.com/abdullamu/cf180710f896b36c8d95
i dont know if its worth noting but when my pc STUCK in this point it becomes very very slow everything i do takes 2 mints to execute which is not normal in my case .
@BluSunrize i didnt know it will not be fixed at that time i thought its bug interduced with the new version which was 0.4 and it will be solved by time and i didnt have time to play minecraft again until this holiday since im medical student so it was difficult to report earlier .
with fastcraft updated to latest they use different rendering modes which render only whats infront of you and when i turn everything show up but takes some seconds which reduces my frame rates updates in these mods doesn't mean its for the best always and its locked to 10 or 15 blocks of distance render .

**Comment by BluSunrize** [comment]
Yeah, honestly? Your PC is probably just not strong enough for Minecraft, sorry to say.
There's really nothing I can do about that.

**Comment by abdullamu** [comment]
if you say so ,well than i'll have to wait for 1.8 mods and see thank you

**Comment by AEnterprise** [comment]
there are already plenty of 1.8(.9) mods, not all are complete and alot of alpha/beta's are in circulation but most mods are playable, lots of new stuff as well @abdullamu

**Comment by XFactHD** [comment]
After looking at the log, I would say the problem is the graphics card.
Also, there is something funny going on: Those lines are abnormal:
[17:15:05] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, FastCraft, ImmersiveEngineering] at CLIENT
[17:15:05] [Client thread/INFO] [FML]: Attempting connection with missing mods [mcp, FML, Forge, FastCraft, ImmersiveEngineering] at SERVER
The brackets should actually contain nothing.

**Comment by abdullamu** [comment]
@XFactHD maybe you are right because i had similar problem with botania

**Comment by mindforger** [comment]
`[17:14:37] [main/ERROR] [FML]: The minecraft jar file:/D:/Games/Minecraft/Install/versions/forge-10.13.4.1614/forge-10.13.4.1614.jar!/net/minecraft/client/ClientBrandRetriever.class appears to be corrupt! There has been CRITICAL TAMPERING WITH MINECRAFT, it is highly unlikely minecraft will work! STOP NOW, get a clean copy and try again!` 

@abdullamu this is still present, i again recommend you to go into you appdata/roaming folder, remove or rename the .minecraft folder, and make a complet new installation of both minecraft AND forge!

i also recommend you to whenever you make a new "modpack" to always create a new profile and select a new "game directory" (just put that hook up there in the profile config) ... this will help you to maintain your modpacks easier and avoids any modifications of the original minecraft installation

(when installing forge after installing minecraft, do NOT change the folder during installation! only chang it in the corresponding profile)
