### ISSUE TITLE
Add config option for energy usage (voltage) of Arc Furnace.

### ISSUE THREAD

**Issue by OneEyeMaker** [BluSunrize/ImmersiveEngineering#864]
Please, add config option to change energy usage of Arc Furnace.
Now this value is hardcoded to 512 RF/t for all standard recipes. But (I hope, that you understand me) for some modpacks this value is too high and for some modpacks - too low.
Of course, I can manually replace all recipes with MineTweaker, but it's silly and boring work (especially for recycling recipes). And I think, that adding config option for Arc Furnace energy usage would be the logical solution.
//As an option, you can use voltage of MV wire for this value instead. (In any case, it's better than hardcoded 512 RF/t).

P. S. Sorry for my English, I'm from Russia.

**Comment by BluSunrize** [comment]
Exactly what Minetweaker is for. A config option only doubles my effort.
Default values should be honored, or  if you can't bare them, Minetweaker is the tedious option.
