### ISSUE TITLE
New Fluid pipe with storage request (enchantment)

### ISSUE THREAD

**Issue by tzpb8** [BluSunrize/ImmersiveEngineering#865]
Hi, i just wanted to request an additional pipe that has similar storage in them as the Tinker Construct cast channels, i'm using Immersive Engineering fluid pipes but because they don't have any storage (it seems) it means that the searing faucets will stop pretty quickly.

The reason for an additional pipe over changing the existing one is that its wildly different and might start to create lag the same as cast channels in Tinkers Construct, which is the reason for this request in the first place.

If there was an additional pipe with storage in them, i could use them as straight replacement for cast channels, but now i have to use the fluid pumps (which i love) to make SURE that the liquid keeps flowing even when the cast tables and cast basins are full.

A simple searing faucet could be used instead of a fluid pump is what i'm getting at IF there was fluid pipes with storage, now i'm forced to use pumps for all the smeltery drains (kinda cool in it self but it gets expensive and seeing floating fluid pumps everywhere is kinda... weird.

I'm avoiding to use cast channels because they create HUGE lag (TiC issue) and now that i'm not using searing faucets (because a pain to automate, why do they have to stop every time an inventory is full? i wish there was a way to change this) i'm now using fluid pumps instead of searing faucets.

Now that i think about it, gregtech fluid pipes has storage and it doesn't lag, should be possible.

Correct me if i'm wrong about IE fluid pipes, it might just be that they are much faster so they fill up quickly and the searing faucets see all inventories as "full" and stops there.. in that case a new pipe with more liquid storage could solve it, or a way to control the flowspeed... maybe i should just request a faucet change lol...

**Comment by BluSunrize** [comment]
I can't really do that since they are instant transfer. But you did answer the question yourself: Use Fluid Pumps, it's what they're there for!
