### ISSUE TITLE
Engineer's Manual incorrect GUI scale.

### ISSUE THREAD

**Issue by ViciousVinnyD** [BluSunrize/ImmersiveEngineering#867]
Version: 0.6.2 (Minecraft 1.7.10)

When the Engineer's Manual is opened it changes the gui scale.
   Small gets changed to Normal.
   Normal remains the same.
   Large gets changed to Normal.
   Auto remains the same.

This occured on the FTB Infinity Evolved modpack (v2.2.2)

**Comment by BluSunrize** [comment]
Yes. That's an intentional feature. And there is a config option for it.
