### ISSUE TITLE
watermill wheel disappear

### ISSUE THREAD

**Issue by AngelCry** [BluSunrize/ImmersiveEngineering#868]
i dont know if is been already reported or not, but looks like i got annoying bug - from time to time one of wheels just disappear. i mean not some kind graphical glitch, is actually disappear (water falling on its place, RF output decreased). also is not "mined" somehow - at least i never found any wheel in water pool. sadly i cant provide some really useful info - there nothing in logs, game not crashing, nothing happens (except disappeared wheel). im sure is not related to chunk loading/unloading because is happens even when i just in few blocks from it. i play SP so is not griefing for sure. weird thing - every time disappear same wheel (closest to dinamo). two other wheels on this dynamo as well as 3 on second dynamo (i have simply setup, 2 dynamos with 3 wheels on each) works with no issues while this one i already replaced few times.
i dont know if is can be related somehow but is started to happen when power load become uneven - most time i have RF generated more than used, but sometime i connect Ender IO capacitor (5kk RF) for charge and while is charging "load spike" happens.
i understand, my explanation not point to anything useful, but may be is something (relatively) easy to find (like something overlooked). or may be i can do something on my side to track down (may be some debug option)?

**Comment by BluSunrize** [comment]
Wow, there's almost no punctuation or capitalization in that text, it's really hard to read.
And I have no idea what'd cause this. Are you usinh it with normal water or a different fluid? Can you provide a screenshot? Also, your version of IE.

**Comment by AngelCry** [comment]
uh, sorry, english not my first language so i often make some mistakes. i do my best but still... and capitalization... i just accustomed type this way. sorry again.
yes, i used just water. MC 1.7.10, IE v0.6.5.1, Forge v10.13.4.1558. anything else?
and here how is looks like:
![Imgur](http://i.imgur.com/96bIOVD.png)
![Imgur](http://i.imgur.com/NbFWCDk.png)
and again, i fully understand how useless my report, but at least now you know is (potentially) can happen (if is happened to me, then can happen to others)

**Comment by AngelCry** [comment]
just found, dynamos and wheels are in different chunks (somewhy i never check it before)
![Imgur](http://i.imgur.com/181vv9o.png)
what you think, is can be related? (and there no wheel again. this time - is first time when both dynamos lost one wheel)

**Comment by AngelCry** [comment]
I watched lately and now want share my observations: first of, fastcraft makes issue MUCH worse. at first i even think is only fastcraft related, because once i removed FC i have all wheels on their places for long time. but now i can say: no, FC just makes is worse, but wheels still disappear even without FC, though is happens rare.
so i guess issue is about entitys loading/unloading and (may be) is why FC makes is worse - i guess (again) FC unloads chunks more often.

**Comment by mindforger** [comment]
thanks for noticing fastcraft and chunkloading we just had this WE an issue with fast reloading chunks i should dive into that issue also :)
