### ISSUE TITLE
Breaking the Reinforced Blast Furnace drops it [1.7.10/0.7]

### ISSUE THREAD

**Issue by Akiishi** [BluSunrize/ImmersiveEngineering#873]
I've downloaded the newest version of IE and after i've build up the Reinforced Blast Furnace to take a look on it. After i have destroyed the first block the whole multiblock structure dropped

**Comment by James-T-Oudvoure** [comment]
What do you mean "the whole multiblock structure dropped"?

**Comment by malte0811** [comment]
You are talking about it dropping an item called "Improved blast furnace" that looks like the furnace? If so, I know what is causing that: [This code](https://github.com/BluSunrize/ImmersiveEngineering/blob/113c5d66efe3f02080f6c25b11a4853f1dbcb69b/src/main/java/blusunrize/immersiveengineering/common/blocks/stone/BlockStoneDevices.java#L75-L80) does not account for the existence of the new blast furnace.
