### ISSUE TITLE
MineTweaker Module for Metal Press

### ISSUE THREAD

**Issue by Bunsan** [BluSunrize/ImmersiveEngineering#875]
Would be nice to have this module to add and modify the recipes.

**Comment by BluSunrize** [comment]
Been there, done that, will be in the next release

**Comment by kane-thornwyrd** [comment]
Pleeeeaaaaaasse Blu-sama

**Comment by BluSunrize** [comment]
The fuck are you on about? It's released already!

**Comment by kane-thornwyrd** [comment]
nvm was on the wrong branche, weird. THANKS ! Now I can kill railcraft in my modpack ! :smile:

**Comment by kane-thornwyrd** [comment]
What "@Optional int inputSize" is supposed to do ? Allow like 4 ingots for one plate ?

**Comment by BluSunrize** [comment]
If you specify the input to be an ore, you cannot define a size. This allows you to do so, so it requires ore:ingotIron x 4

**Comment by kane-thornwyrd** [comment]
should I make another issue ticket is this doesn't work ? I know you're tired of saying "last revision" and you want to work on the 1.8.

**Comment by kane-thornwyrd** [comment]
Could I create another issue if this does not work ? I know you're tired of saying "last revision for 1.7.10" and you want to work on the 1.8 :cry:

**Comment by BluSunrize** [comment]
Yes you could, but what exactly isn't working?

**Comment by kane-thornwyrd** [comment]
I wrote: ```
var ferromagneticIngot = <ReactorCraft:reactorcraft_item_crafting:10>;
var ferromagneticPlate = <ReactorCraft:reactorcraft_item_crafting:5>;

recipes.remove(ferromagneticPlate);

var ingotFerromagnetic = <ore:ingotFerromagnetic>;
ingotFerromagnetic.add(ferromagneticIngot);

var plateMold = <ImmersiveEngineering:mold>;

mods.immersiveengineering.MetalPress.addRecipe(ferromagneticPlate, ingotFerromagnetic, plateMold, 10000, 4);
```
The press *sometime* allow an ingot to be *pressed* but instead, no power is consumed and the ingot is outputted pristine, no plate. It work as expected without the optional parameter.

**Comment by BluSunrize** [comment]
IT needs to get the 4 ingots as a single stack, otherwise it will not work. There is no way for me to handle that differently.

**Comment by kane-thornwyrd** [comment]
yes, but the press doesn't want to input more than one item at a time.

**Comment by kane-thornwyrd** [comment]
I can make a "4ingots items" with content tweaker, you see, that would block me really
