### ISSUE TITLE
recipe of arc furnace in engineer's manual 

### ISSUE THREAD

**Issue by quentfr21** [BluSunrize/ImmersiveEngineering#877]
hello

recipe of arc furnace in engineer's manual not show all block needed when hovering the "?" 

thanks

http://rousteurs.free.fr/img.png

**Comment by BluSunrize** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/commit/e301065cda792208ad489f39d1783753876bf79d

Fixed.
