### ISSUE TITLE
Improved blast furnace visual glitch

### ISSUE THREAD

**Issue by MisterGrimDeath** [BluSunrize/ImmersiveEngineering#878]
so...i have this weird problem, and the furnace is not even functional, its like a pile of furnaces 
![2016-01-14_17 13 10](https://cloud.githubusercontent.com/assets/16712394/12343036/d9b70c84-bb0e-11e5-932c-afe0367b4131.png)

**Comment by killerscorpion** [comment]
Im also dealing with this problem. Removing Optifine fixes it.

**Comment by XFactHD** [comment]
Then you will have to play without Optifine as there is no possibility to make things work with the changes Optifine does.

**Comment by BluSunrize** [comment]
Correct. Optifine sucks and I refuse to even try to adapt to it.
