### ISSUE TITLE
[Issue] Hotbar 'GUI Scale: Normal' when reading Engineer's Manual

### ISSUE THREAD

**Issue by Samji** [BluSunrize/ImmersiveEngineering#885]
The engineer's Manual remains the same size and does not scale when any GUI Scale other than 'auto' is used in Minecraft.
However the hotbar gui underneath will change to 'GUI Scale: Normal' when reading the Engineer's Manual when GUI Scale: 'Small' or 'Large' is set.

Basically the hotbar gui changes to the 'Normal' size when reading the Engineer's Manual if the GUI Setting is either 'Small' or 'Large' in Minecraft, thereby shrinking or growing whenever you read the Manual.

(Wow this was difficult to articulate..)

The included picture shows the hotbar gui size change when the Engineer's Manual is opened. *(difference marked with a red border / GUI set to 'Large' in Minecraft's settings)*

![gui scales](https://cloud.githubusercontent.com/assets/8977840/12374214/880bd480-bc8c-11e5-94f5-0629ed508ee7.jpg)

**Comment by cobra** [comment]
#867

**Comment by BluSunrize** [comment]
Check past issues and check the config.
