### ISSUE TITLE
[Crash] NoClassDefFoundError caused when structuring bottling machine

### ISSUE THREAD

**Issue by karakufire** [BluSunrize/ImmersiveEngineering#886]
IE0.7.1
Here's Crash report
http://pastebin.com/5hA49Vyn

**Comment by cobra** [comment]
Workaround: install computercraft.
Fix: @malte0811, wtf. :P

**Comment by malte0811** [comment]
The `getEmpty/FilledCannister` methods in the TileEntity still throw `LuaException`'s, that needs to be changed to an `IllegalArgumentException`, which should be cought in the `invoke` method of the peripheral and "rethrown" as a `LuaException` for consistency, also because I don't know how well CC handles random Exceptions in the peripherals.

**Comment by cobra** [comment]
Out of curiosity, I just tested it by changing the exception from `LuaException` to `IllegalArgumentException` and then unconditionally throwing this from `TileEntityBottlingMachine#getEmptyCannister`. Result:
````
lua>p.getEmptyCannister(1)
Java Exception Thrown:
java.lang.IllegalArgumentException: Not enough empty cannisters found
lua>
````
Not totally nice, but no crashes either. Rethrowing it is then, I think.

**Comment by BluSunrize** [comment]
Welp. Glad I didn't cause that one. xD

**Comment by malte0811** [comment]
I won't fix this until this afternoon, if anyone wants to implement the fix i described above (i think a hotfix update would be a good idea for this), go ahead.

**Comment by cobra** [comment]
I've got half (getEmptyCanister intentionallybroken for testing) of this running right now, will do.

**Comment by cobra** [comment]
See #888, didn't hit #

**Comment by karakufire** [comment]
@cobra nice fix, and strange appearence caused...(´・ω・`)
screenshot -> http://i.imgur.com/LLpfb5G.png

**Comment by karakufire** [comment]
@cobra nice fix!

**Comment by BluSunrize** [comment]
Fixed.
