### ISSUE TITLE
[Suggestion] Add the ability to change the generated energy

### ISSUE THREAD

**Issue by Tsyklop** [BluSunrize/ImmersiveEngineering#887]
Add the ability to change the energy produced in wind and water mills in the config

**Comment by BluSunrize** [comment]
That's already in, check the config again >_<

**Comment by Tsyklop** [comment]
this?
`    # The base RF that is output by the dynamo. This will be modified by the rotation modifier of the attached water- or windmill
    D:"Dynamo: Output"=1.0
`

**Comment by BluSunrize** [comment]
Bingo.

**Comment by Tsyklop** [comment]
@BluSunrize thanks
