### ISSUE TITLE
Server Crash Crusher

### ISSUE THREAD

**Issue by aikpoppel** [BluSunrize/ImmersiveEngineering#889]
Hey Blu,
if a invalid item (Diamond Chest from IronChests Mod) get in crusher my server get crashed, tested in SSP same issue. Tested with 0.7.1 and 0.7.1.1.
AND
Server get crashed again when chunk gets loaded...

Forge: 10.13.4.1558
log: http://pastebin.com/Rj7s7nin
LG Aik

**Comment by BluSunrize** [comment]
Yep, known issue.
