### ISSUE TITLE
[Suggestion] Add ores/blocks to be processed by crusher to config

### ISSUE THREAD

**Issue by Slither88** [BluSunrize/ImmersiveEngineering#89]
Hi

First off congrats on the release of your mod! From what I've seen on forgecraft and just the whole progress of the mod so far it looks as though your mod could become the next big thing.

I have a suggestion that might be awesome! 

If the grit texture was to be 'colorless' and you/players/modpack creators could add an ore and the color code of the grit texture you/they desire, your mod could be used in any modpack with any combination of ores and resources, even the ones that are not currently supported by addons like AOBD and the like. You could even go one step further and allow for the amount of output grit to be configured as well.

The idea could be dumb, I have been awake for some time, but at least it is out there now! :-P

**Comment by BarbasTheDog** [comment]
You might be happy to know that IE has native Minetweaker integration. As for your other suggestions, I can't say anything, of course, but I'd imagine the author would find them being outside of the scope of the mod.

**Comment by Slither88** [comment]
Oh. Thanks. I had no idea minetweaker was supported out of the box! Thanx! Will check it out!

**Comment by Slither88** [comment]
Any idea where I can find documentation on the minetweaker support?

**Comment by BarbasTheDog** [comment]
MT functions are marked with the @ZenScript annotation, so I imagine that if you search the code in the repo for that, you'll find the correspondent methods.

**Comment by Yulife** [comment]
Maybe I'll document it later.

**Comment by BluSunrize** [comment]
Yeah, that's not really what IE is about. IF you need more dusts, use AOBD, it was made specifically for that =P

**Comment by Yulife** [comment]
@BluSunrize removeFuel does not work - it does not throw an error. I tried both Coke Block and Item.

**Comment by BluSunrize** [comment]
All fixed. MinetWeaker support with fuel+crusher is in 0.2.4

**Comment by Yulife** [comment]
:clap:
