### ISSUE TITLE
0.7.1 crusher crashing server

### ISSUE THREAD

**Issue by Axylxys** [BluSunrize/ImmersiveEngineering#891]
Well the title sums it up. Updated to 0.7.1 and after a few hours the server closed suddenly.

Here's the crash report:

http://pastebin.com/UVzhkwiT

We have 2 crushers: one is inactive currently and the second one is crushing various mobs, endermen and whatever spawns in the dark room.

Edit: currently unable to restart server, it crashes at world load before anyone can even try to connect.

**Comment by cobra** [comment]
#889 #890

**Comment by BluSunrize** [comment]
^ that
