### ISSUE TITLE
Ingame manual crash

### ISSUE THREAD

**Issue by therealtkh** [BluSunrize/ImmersiveEngineering#892]
Clicked "What's new in 0.7.1" in the Engineer's Manual crash my game, 100% repeateable in two tries.

Crashlog: http://pastebin.com/QPhq0UVH

**Comment by cobra** [comment]
…and another bug caused by missing computer mods. The computer support section is missing, but linked to.

**Comment by BluSunrize** [comment]
I added a sanity check for it already cobra, no worries.
The update log is fairly unimportant apart from computers anyway, so it's not an important fix.

**Comment by cobra** [comment]
Yeah, it's fairly trivial. Still, good catch, I didn't think of trying that yet.
