### ISSUE TITLE
Crash when looking up recipes in NEI on blast furnace

### ISSUE THREAD

**Issue by Haggle1996** [BluSunrize/ImmersiveEngineering#895]
Received this crash http://pastebin.com/dAuKLS7q when looking up uses for an ore in NEI that I added to the IE blast furnace using minetweaker.

This is the line from my minetweaker script:
mods.immersiveengineering.BlastFurnace.addRecipe(<HarderOres:dummyOreIron>,<HarderOres:ore_chunk:8> * 3, 4800);

Not sure if it's my fault or an issue in IE.

**Comment by Haggle1996** [comment]
This may be related to #857 -- the change you made to allow the blast furnace to consume multiple inputs.

**Comment by BluSunrize** [comment]
Nope, entirely unrelated to that.
I know the issues, i cab fix it. As a temporary solution, just make sure to add slag in your minetweaker function, so: add "minecraft:cobblestone" behind the time value, or something like that.

**Comment by tehFoxx0rz** [comment]
Getting a crash myself, with a Minetweakered metal press recipe: https://dl.dropboxusercontent.com/u/66131226/crash-2016-01-18_18.43.09-client.txt

And Minetweaker seems to complain when I don't specify an additive stack for the arc furnace (whether "null" or entirely absent); is that a required field now?

**Comment by BluSunrize** [comment]
That crash doesn't show any reference to IE .-.

**Comment by AEnterprise** [comment]
@tehFoxx0rz you got a crashing crash with that report, a full log will be required, something is crashing in such a way that the crashreport generator crashes as well, masking the original crashing error

**Comment by tehFoxx0rz** [comment]
I'd never had a problem with it until now so it didn't occur to me, but Mine&Blade is known to crash the crashlog generator, and I removed that and now have a much more relevant-looking report:
https://dl.dropboxusercontent.com/u/66131226/crash-2016-01-19_20.34.39-client.txt

**Comment by BluSunrize** [comment]
Oh so it's Mine&Blade that completely fucks up error reports. I'll have to remember that for other people with logs like that. xD
That also makes identifying the issue easier, I can deal with it.
