### ISSUE TITLE
Crash from Crusher Taking in Non-Crushable Items

### ISSUE THREAD

**Issue by NFinET** [BluSunrize/ImmersiveEngineering#896]
Found a bug while using version 0.7.0 in a custom modpack I've been working on while testing things in singleplayer, if a crusher takes in ANY item that does not have a valid crusher "recipe", it crashes the game. Any attempts to load the save again only result in further crashes. 

Full crash log here: 
[crash-2016-01-18_04.54.56-server.txt](https://github.com/BluSunrize/ImmersiveEngineering/files/94075/crash-2016-01-18_04.54.56-server.txt)
or, alternatively, here (same log)
http://pastebin.com/vcczpi1K

Tested using: Iron Grit (Accidentally fell back onto the conveyor belt), Chest (Vanilla), Light Engineering Block, and a few other items I forgot to record.

Method was to make a new save, build a crusher in creative, place a chest on the output and use HV connectors to hook up a creative energy cell (Thermal Expansion), before tossing in an object. Every time if the object was not a mob or an ore, the game crashed and the save could not be re-loaded without further, identical crashes.

I haven't tested what happens if an ore is tossed in that is not a vanilla or IE ore, haven't had time to do so yet.

**Comment by XFactHD** [comment]
Known and fixed. Use the latest version when reporting bugs.

**Comment by BluSunrize** [comment]
^ that
