### ISSUE TITLE
Buildcraft oil Feature?

### ISSUE THREAD

**Issue by Cracks777** [BluSunrize/ImmersiveEngineering#897]
Is it possible to refine buildcraft oil in the refinery?

**Comment by XFactHD** [comment]
Should be possible, did you try it?

**Comment by Cracks777** [comment]
yes but it does not take it into the refinery?

**Comment by Cracks777** [comment]
ok, well using minetweaker i have added a recipe.

**Comment by AEnterprise** [comment]
@Cracks777 you sure you where using buildcraft oil and not oil from galacticraft (or even sludge witch people sometimes mistakenly see for oil)

**Comment by Cracks777** [comment]
yes i am positive. the refinery requires 2 fuel inputs doesn't it?

**Comment by BluSunrize** [comment]
Correct. The refinery is designed for two inputs, not one.
So either you make it require water with a size of 0, resulting in it requiring water but never consuming it, or you don't. But it wont allow 2 of the same fluid for components. It was not ever designed to do so.

**Comment by BluSunrize** [comment]
Correct. The refinery is designed for two inputs, not one.
So either you make it require water with a size of 0, resulting in it requiring water but never consuming it, or you don't. But it wont allow 2 of the same fluid for components. It was not ever designed to do so.

**Comment by mindforger** [comment]
@BluSunrize this reminds me of a question to stuff like this, is there a "cleaning drain" function?! :) i mean can i remove stuff from the tanks by just reversing the flow?
