### ISSUE TITLE
ModTweaker: Metal Press not working with "stack of items"

### ISSUE THREAD

**Issue by kane-thornwyrd** [BluSunrize/ImmersiveEngineering#899]
If you're in that case:

```
var ferromagneticIngot = <ReactorCraft:reactorcraft_item_crafting:10>;
var ferromagneticPlate = <ReactorCraft:reactorcraft_item_crafting:5>;

recipes.remove(ferromagneticPlate);

var ingotFerromagnetic = <ore:ingotFerromagnetic>;
ingotFerromagnetic.add(ferromagneticIngot);

var plateMold = <ImmersiveEngineering:mold>;

mods.immersiveengineering.MetalPress.addRecipe(ferromagneticPlate, ingotFerromagnetic, plateMold, 10000, 4);
```

The press *sometime* allow an ingot to be *pressed* but instead, no power is consumed and the ingot is outputted pristine, no plate. It work as expected without the optional parameter. (the mold is in place).

Same with : 
```
mods.immersiveengineering.MetalPress.addRecipe(ferromagneticPlate, ingotFerromagnetic*4, plateMold, 10000, 4);
```

Every-times only 1 item is "imputed" by the press, pressed for 0 RF then outputted.

The goal here being to output a ferromagnetic plate for 4 ferromagnetic ingots.

**Comment by BluSunrize** [comment]
Yeah I see where the error stems from, I think I can fix that.

**Comment by kane-thornwyrd** [comment]
thank you a lot ! You close with the commit ?

**Comment by kane-thornwyrd** [comment]
thanks @malte0811 , @BluSunrize , guys, any clue about the next release milestone ?
