### ISSUE TITLE
Energy loss doesn't seem to be working

### ISSUE THREAD

**Issue by BarbasTheDog** [BluSunrize/ImmersiveEngineering#9]
According to the Voltmeter, this connection should have a loss of 18.438 RF, but the initial and final values were identical: 
https://imgur.com/a/rkvQa 

(Also tested with IE capacitors)

**Comment by BluSunrize** [comment]
Huh, that was a fun and tricky bug. I did loss-calcualtions all right, but then I returned the value I had transmitted, which includes loss. So capacitors only took amount the amount of power /minus/ the loss out effectively losing nothing.

Thanks for reporting it =)
