### ISSUE TITLE
Arc furnace causes frame lag when structure is formed.

### ISSUE THREAD

**Issue by Macropyre** [BluSunrize/ImmersiveEngineering#900]
Just-formed Arc Furnace.
http://puu.sh/mCbaR/d6609a0512.jpg

Arc furnace before being formed.
http://puu.sh/mCbeG/a632acecd6.jpg

Chunk updates fluctuating like crazy when it was built too  (from 0-4 normally, to 30-120). I'm not sure what could be causing the issue.

**Comment by BluSunrize** [comment]
Me neither with that report. Could you maybe provide versions, modlist, and proper evaluations with Opis or something like that?

**Comment by Macropyre** [comment]
Alrighty.
Modpack list:
http://puu.sh/mCcMI/1fa184eadb.png
Forge 10.13.4.1558
IE Version 0.6.4
No Opis on server, couldn't check.

**Comment by Macropyre** [comment]
Alrighty.
Modpack list:
http://puu.sh/mCcMI/1fa184eadb.png
Forge 10.13.4.1558
IE Version 0.6.4
No Opis on server, couldn't check.

**Comment by BluSunrize** [comment]
Your IE is /severly/ outdated. You should only ever file issues when testing with the current release.

**Comment by Macropyre** [comment]
I'll ask our server owner to update, and will check back in.

**Comment by malte0811** [comment]
Until you update, 1. Either leave the arc furnace unformed or 2. Insert electrodes and don't run it (if you want it partially for decoration). I am pretty sure that i fixed this in a newer version.

**Comment by malte0811** [comment]
#754
I know it says stuff about client side energy transfer, that turned out to be wrong. This has been fixed and therefore can be closed
