### ISSUE TITLE
[minor] Multiple manual references with same name

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#902]
Several entries when searched for, such as the Arc furnace and the, result in two identical results with no clear distinction which one is which without manually opening each result to find the exact page in question. I DO understand if browsing to the entries manually the distinction is clear however, for the sake of handy search feature, multiple entries with the same name is simply confusing to the player. 

![image](https://cloud.githubusercontent.com/assets/3110986/12440233/3e9dd334-beee-11e5-9226-126510d8d4d3.png)
![image](https://cloud.githubusercontent.com/assets/3110986/12440235/468b61f6-beee-11e5-8ae6-ba9a47348e21.png)

IE build 9af592c9166bbb6890b0008bcd905c22edc791c2

**Comment by malte0811** [comment]
I didn't think of that when adding the computer documentation to the manual. I will possibly make another computer PR today (for capacitors), i could rename the entries then.

**Comment by theunkn0wn1** [comment]
Perfectly understandable @malte0811.

Whilst we are here I have a question about the CC support you and cobra implemented, for IE's muiltblock structures where exactly do I need to place the computer upon the structure to gain access to the documented functions? Attaching a CC computer (golden) to any random side of an Arc Furnace leads to both unexpected and ugly results.

**Comment by malte0811** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/resources/assets/immersiveengineering/lang/en_US.lang#L935
What do you mean by "both unexpected and ugly results"? It didn't provide any peripheral to me when i tried connecting somewhere else.

**Comment by theunkn0wn1** [comment]
By unexpected i mean the peripheral calls exposed to the computer are not what I was expecting, either the correct calls or none at all where expected; instead only inventory calls are provided.

![image](https://cloud.githubusercontent.com/assets/3110986/12466691/26ce8062-bf8b-11e5-99b2-a7746894b808.png)
This is with proper CC placement directly on the RS port (thanks... was horribly unobservant when looking earlier...)
![image](https://cloud.githubusercontent.com/assets/3110986/12466707/4729c3a8-bf8b-11e5-879d-799222bebcc5.png)
improper placement using a well known (perhaps proper?) command to list peripheral calls ```m.listMethods()``` as it existed
![image](https://cloud.githubusercontent.com/assets/3110986/12466817/eb2c16e0-bf8b-11e5-94ed-85951a37299e.png)

Either way, the output for an improper placement call was not what i was expecting, hence the 
>... unexpected...


The "...ugly...' part was on me, CC was not what i remembered from a long time ago ^^

**Comment by malte0811** [comment]
That is openperipherals, i don't think i can stop them from recognizing the arc furnace as an inventory without adding sort of a "null"-peripheral that wouldn't be nil but also wouldnt provide any methods. It also explains why i was not having that issue, i don't have OP in my dev environment.
