### ISSUE TITLE
More control over village building.

### ISSUE THREAD

**Issue by Claycorp** [BluSunrize/ImmersiveEngineering#904]
It would be great if we could disable the village building and disable/edit the crates that spawn.

**Comment by Fortist** [comment]
Seconding this, I just want to be able to disable it completely.

**Comment by Robijnvogel** [comment]
Third this. I really need that functionality to disable all technological plants, ores and structures for my modpack. (I'm on MC 1.7.10 by the way.)

Can't you edit the contents of that crate with MineTweaker though? If not, registering it as a loot-chest should automatically fix that.

**Comment by Robijnvogel** [comment]
Did you also register the crate in the general loot-table so its contents can be found by and adjusted with MineTweaker?

**Comment by BluSunrize** [comment]
Yes. Check the changelog.

**Comment by Robijnvogel** [comment]
Oops
Good work though!
One more question, is this only "fixed" for 1.8.9, or for 1.7.10 as well?

**Comment by BluSunrize** [comment]
Wat? 1.7.10 build was released a few hours ago. Check my Twitter/Curseforge.
1.8.9 isn't on github yet, so that's not being released currently.

**Comment by Robijnvogel** [comment]
I watch DireWolf20 and haven't really built a 1.8.9 pack yet, so I'm not aware of what mods are officially released and what mods are only being beta-tested. There's between 100 and 300 mods I use on a regular basis (on 1.7.10) and I'm not omniscient.
But this is good to know and I'm looking forward to using the new version.

Keep up the good work!
