### ISSUE TITLE
[Request] Config for Windmill rotation speeds

### ISSUE THREAD

**Issue by Aedda** [BluSunrize/ImmersiveEngineering#905]
The default speed of the windmill seems too high to me, but I do not doubt others would disagree. An additional option for speed during storms would be nice too.

**Comment by JCLaHoot** [comment]
:+1: +1 vote for this

**Comment by BluSunrize** [comment]
No. There is a power modifier for kinetic dynamos, that should suffice.

**Comment by Aedda** [comment]
That affects the visual spinning speed of the blades?

**Comment by BluSunrize** [comment]
No, but the request didn't sound like adjustable rendering. In which case still a no, since rendering rotation is sorta linked to the energy production, and I don't wanna go through the effort of dividing that up.
Not everything needs a config.
