### ISSUE TITLE
HV transformer burning out LV wires

### ISSUE THREAD

**Issue by tzpb8** [BluSunrize/ImmersiveEngineering#908]
Hi, i have come across a problem.. Since i started using HV wires and a transformer to down step to LV wires then into ic2 machines, the wires burn out.

If i switch out the the wires going from transformer -> ic2 machine to MV wire, it doesn't burn out.

But even if the ic2 machines is going at full power (32eu * 4 = 128RF) the wire should be FAR from burning out since 2048RF/t is max for LV wires and besides, why does the wires figure out that the machine desires higher than 2048RF/t? it clearly says 32eu max and 10eu per operation.

Is this a problem with variable machine power usage?

I have even tried to connect to a ic2 transformer first to solve this, but alas: it still burns out.

My guess: The HV transformer isn't doing its job to properly down step the HV to LV (and using a MV transformer after the HV one doesn't help either).

My second guess: transformers don't actually restrict RF flow, they just allow to step up or step down wire types but it will STILL attempt to send a HV current into a LV line.

So how do i step down from a high energy flow into a lower one where i can safely connect my machines?

Possible solution i'll try next: Put down a capacitor as a buffer, it will eat up the HV and send it out with a LV connector, this should work! (i'll try it now)

edit: tried it, works beautifully! :D

Conclusion: Capacitors are the true transformers.

**Comment by Nova001Sol** [comment]
That's one way to do things. I recommend using HV>LV only when you have less than 2046RF/t flowing through your HV cable. Otherwise, use multiple transformers.

**Comment by tzpb8** [comment]
Not sure how transformers spit, will i need a power consumer to keep the 2nd transformer busy? or will it kill off half the original energy flow? (say from random 3000RF/t to a safe level of 1500RF/t)

So the original wire will only output 1500RF/t because it detects 2 transformers at the end so no extra energy is actually wasted because of 2 transformers?

**Comment by BluSunrize** [comment]
Pictures of your setup would be helpful >_>

**Comment by tzpb8** [comment]
Okay here you go, but i fixed it somehow by using a HV breaker before the transformer, not sure if the breaker limits the output to something lower or not tho.

![2016-01-20_22 00 02 - kopia](https://cloud.githubusercontent.com/assets/9417797/12463176/5ace68b4-bfc2-11e5-98e3-7fea8558d670.png)

**Comment by malte0811** [comment]
What version are you using? This may have been fixed in 0.6.3, but I'm not sure whether it is the same bug

**Comment by tzpb8** [comment]
IE version 0.6.5.1
Immersive Integration 0.6.6

I'm playing on the Infinity Evolved 2.3.5 (latest and last version before 1.8.9 update)
It may have changed values, i'll try to find them.

**Comment by malte0811** [comment]
Forget it, I just managed to reproduce this in my testing world.

**Comment by tzpb8** [comment]
Found it, i think it is default values:


    # The maximum amount of RF that can be input into a high-voltage capacitor (by IE net or other means)
    I:"Capacitor HV: Input"=4096

    # The maximum amount of RF that can be output from a high-voltage capacitor (by IE net or other means)
    I:"Capacitor HV: Output"=4096

    # The maximum amount of RF that can be stored in a high-voltage capacitor
    I:"Capacitor HV: RF Storage"=4000000

    # The maximum amount of RF that can be input into a low-voltage capacitor (by IE net or other means)
    I:"Capacitor LV: Input"=256

    # The maximum amount of RF that can be output from a low-voltage capacitor (by IE net or other means)
    I:"Capacitor LV: Output"=256

    # The maximum amount of RF that can be stored in a low-voltage capacitor
    I:"Capacitor LV: RF Storage"=100000

    # The maximum amount of RF that can be input into a medium-voltage capacitor (by IE net or other means)
    I:"Capacitor MV: Input"=1024

    # The maximum amount of RF that can be output from a medium-voltage capacitor (by IE net or other means)
    I:"Capacitor MV: Output"=1024

    # The maximum amount of RF that can be stored in a medium-voltage capacitor
    I:"Capacitor MV: RF Storage"=1000000




    # In- and output rates of LV,MV and HV Wire Conenctors. This is independant of the transferrate of the wires.
    I:"Wire Connector Input" <
        256
        1024
        4096
     >
