### ISSUE TITLE
Railgun not charging properly from HV Capacitor in a Box

### ISSUE THREAD

**Issue by arfink** [BluSunrize/ImmersiveEngineering#909]
I'm running Infinity Evolved 2.3.5, which IIRC has version 0.6.5 of IE. As the title says, the railgun isn't recharging from the HV capacitor in a box, from Immersive Integration. It also doesn't seem to charge properly from Flux Capacitors in my testing. It is not only a visual glitch, because when the tool tip reports 0RF charge it will not fire. However, it will report a full charge immediately if you remove it from the active hotbar slot and then put it back again.

**Comment by theunkn0wn1** [comment]
Please update IE to the current release before reporting issues. Also: issues with EE should be reported to EE's developer.
