### ISSUE TITLE
Engineer's Workbench Rendering

### ISSUE THREAD

**Issue by porteriscool** [BluSunrize/ImmersiveEngineering#91]
Obviously a rendering bug, two mining drills on one engineer's workbench, when only one is in the workbench. If any info is needed on any other rendering problem, ask away, and I will try to get the information for Blu or anyone else to fix the problem.
![2015-06-24_23 44 14](https://cloud.githubusercontent.com/assets/12450943/8346474/1a264e86-1acb-11e5-806f-0381da7b0910.png)

**Comment by BluSunrize** [comment]
Can't reproduce. Replace the workbench and see if the bug persists?
Also which side did you click to input?

**Comment by porteriscool** [comment]
Still continues to have the rendering bug occur. I am click on the engineer's workbench from each side to input the item. Also, in the previous picture, the bench was facing the east. In this image below, the bench was facing the north. Also, what direction are you refering to with the vice?
![2015-06-25_10 55 07](https://cloud.githubusercontent.com/assets/12450943/8357390/b4a0e13a-1b28-11e5-8d66-de0c38e48a43.png)

**Comment by BluSunrize** [comment]
I really can't reproduce this .~.

**Comment by AEnterprise** [comment]
maybe another mod like optifine is messing with it?

**Comment by porteriscool** [comment]
Optifine is not installed.

**Comment by porteriscool** [comment]
Also, I can even reproduce this rendering bug with the revolver.
![2015-06-25_12 05 52](https://cloud.githubusercontent.com/assets/12450943/8359138/8fac3e10-1b32-11e5-86a6-17531f7fdec2.png)

**Comment by BluSunrize** [comment]
Well yeah, if it happens for one item, it's not surprising that it happens for others. I just don't know what causes this.

**Comment by porteriscool** [comment]
Maybe it has to do with rendering when placed inside the workbench, it may be possible that when it is placed inside the workbench it wants to render both renderings because there might not be a condition that states how to render the object once placed inside the workbench. A work around might be to create a condition that states how to render it, and how not to; if that's even possible though.

**Comment by BluSunrize** [comment]
It is all stated. It works fine in my dev environment

**Comment by porteriscool** [comment]
Hmmm, I'll see what I can get information wise on how to possibly fix this, and also, why it's also occurring.

**Comment by theunkn0wn1** [comment]
@BluSunrize  @porteriscool 
Managed to repo in my test world,
Running FTB Infinity (manually added latest version from curse)

No mods added besides IE and what came with Infinity by default.
placed workbench while facing EAST, right clicked on the right block (see below) and inserted revolver straight from NEI into the inventory slot.

![image](https://cloud.githubusercontent.com/assets/3110986/8370648/b08fdf54-1b7f-11e5-848b-4118f7ea8567.png)
![image](https://cloud.githubusercontent.com/assets/3110986/8370661/cb4380c6-1b7f-11e5-969e-c5a54c466131.png)
![image](https://cloud.githubusercontent.com/assets/3110986/8370666/ed13b680-1b7f-11e5-9fcc-d2f96af3343f.png)
![image](https://cloud.githubusercontent.com/assets/3110986/8370669/fa5d3abe-1b7f-11e5-9a31-a2f809555a22.png)

link to log: http://paste.feed-the-beast.com/view/1fe70e67

**Comment by BluSunrize** [comment]
So apparently I'm stupid and found my bug. YAY!
Will fix it in the next release

**Comment by porteriscool** [comment]
Oh perfect, and I just looked at what you changed and it looks like it should fix the problem. Thanks for fixing that rendering bug Blu.
