### ISSUE TITLE
[Suggestion] Railgun damage adjustable in the configs

### ISSUE THREAD

**Issue by arfink** [BluSunrize/ImmersiveEngineering#910]
Can we get a config option to adjust railgun damage? I feel like 10 damage with steel rods is not enough considering the complexity and cost of the railgun recipe, and would like to be able to adjust this upwards on my server.

**Comment by theunkn0wn1** [comment]
+1 I second this motion. For the expense, complexity, and darned cool looking of the FireArm the amount of damage the RailGun is just anti-climatic. Please expose the damage output of the railgun as a configurable element of IE.
