### ISSUE TITLE
[Suggestion]Coal Coke -ore dic-

### ISSUE THREAD

**Issue by EndermanParty** [BluSunrize/ImmersiveEngineering#912]
Your coal coke and the railcraft counterpart is not inter-changable. I was going to use your Improved Blast Furnace but sadly it is so frustrating to use sometimes that I decided to go Railcraft instead for steel production. However, I come to find out that your Coal Coke can't be placed in their blast furnace. I have the Automatic Ore-Dic converter mod installed and was going to use it to change between the two but I come to find that your coal coke is all alone. It doesn't have any counterparts in the list... So is this a bug or something on my end?

**Comment by BluSunrize** [comment]
Tell Railcraft. I use the ore dictionary, my coke is registered as "fuelCoke", and I allow anything registered to that name to work as a fuel in my blast furnaces. If Railcraft's stuff doesn't work, that's their fault, not mine.

**Comment by EndermanParty** [comment]
Okay, Thank you.
