### ISSUE TITLE
excavator bug

### ISSUE THREAD

**Issue by quentfr21** [BluSunrize/ImmersiveEngineering#914]
hello 

forge 1614
immersive 0.7.1.2

i'm in a chunk with lead minerals deposit, excavator run but no mineral was extracted

thanks

**Comment by BluSunrize** [comment]
Pictures of your setup.

**Comment by quentfr21** [comment]
http://rousteurs.free.fr/excav1.png
http://rousteurs.free.fr/excav2.png

thanks

**Comment by cobra** [comment]
I suppose `/ie mineral get` is also returning lead, right?

**Comment by quentfr21** [comment]
hello

@cobra 
just tested command and it's return

chunk contains:lead, override:null, depletion: 0

**Comment by malte0811** [comment]
Is the wheel moving? It should be moving even if it doesn't find any minerals

**Comment by quentfr21** [comment]
hello
@malte0811 
yes wheel move and at start just get some sand and after nothing always empty

**Comment by malte0811** [comment]
![2016-01-24_20 35 31](https://cloud.githubusercontent.com/assets/10406104/12538447/07516e3c-c2da-11e5-8b62-5f4ea0e93579.png)
Are there blocks 2 blocks below the lowest point of the wheel (so the ones i replaced by diamond in the screenshot)? If some are missing, place some blocks (i.e. cobblestone) and see if that fixes it. If it does, it is not a bug.

**Comment by quentfr21** [comment]
hello

@malte0811 

thanks it's work now so no issue
