### ISSUE TITLE
Arc Furnace recycling isn't editable via minetweaker.

### ISSUE THREAD

**Issue by Claycorp** [BluSunrize/ImmersiveEngineering#915]
With #911 causing issues I thought I would do a quick temporary fix via minetweaker till a new build is put out.
Issue is though you can't edit recycling recipes via minetweaker at all.

I understand that you can turn it off and write all of your own to replace it but that is unnecessary work just to fix a few that might pop up.

**Comment by BluSunrize** [comment]
Recycling recipes work a bit differently, so they probably wouldn't be removeable anyway, no matter what I did to the Minetweaker support...

**Comment by Claycorp** [comment]
Hm.. I guess I'll just shut it off and re-do everything by hand.
