### ISSUE TITLE
Creative items to spawn multiblock structures.

### ISSUE THREAD

**Issue by Claycorp** [BluSunrize/ImmersiveEngineering#916]
It would be great if you could add creative items or an item that generates the whole multi-block on right click.

It would be extremely useful for server ops, pack devs and testing.

**Comment by OneEyeMaker** [comment]
#789

**Comment by Claycorp** [comment]
I guess my search wasn't good enough.
Ah.... I see. Silly that he is so against this idea... Perhaps i'll go ask Immersive integration.

**Comment by cobra** [comment]
As I wrote over there, you can use the Buildcraft builder or Schematica with the "raw" blocks, works like a charm for nearly everything. I'm doing it all the time when testing things. Slopes and conveyors might need manual placement or adjustment, though. This could be fixed, but 1.7.10 development slowed down a lot or has even been finished for some mods, so I won't do that.

**Comment by XFactHD** [comment]
Little side note: If you search for ImmersiveEngineering in the github search, the second result is a repository with schematica schematics for the multiblocks. 😏

**Comment by kane-thornwyrd** [comment]
you can use blockproperties to spawn a schematic on break of a block, let imagine a block from Quadrum or ContentTweaker... THERE YOU HAVE IT !
