### ISSUE TITLE
Wire linking.

### ISSUE THREAD

**Issue by Claycorp** [BluSunrize/ImmersiveEngineering#919]
Currently if you place down a connector or relay you go to connect a wire and it doesn't work there is no way to cancel this interaction. Reloading the world, throwing the item out of the inventory, shift clicking the air, clicking the air all gives nothing. I looked in the book and could not find anything about canceling a linkage.

Because of this inability to cancel the link you can end up with odd things that shouldn't be possible.
![](http://i.imgur.com/izbE6aP.png)
Why you would ever do this? I have no clue. You can even stack the points with different levels/item stacks.
![](http://i.imgur.com/A030Gdc.png)

How to Reproduce:
* Place connector
* Start wire link
* Mine the connector
* Place whatever connector you wish. (or possibly machine. Have not tested this)
* Place the other connector of the same level of wire you used.
Bam! Goofy wire connections that don't make sense and work!

**Comment by BluSunrize** [comment]
Well as you said: Noone in their right mind ever does that.
Solution: Be smart about it?

**Comment by Claycorp** [comment]
The issue is you can't stop linking wires. You MUST link two things together to cancel it. It would be nice if you can shift click the air or the ground or something to stop the linkage. The rest is just an goofy bug because of it.

**Comment by BluSunrize** [comment]
you can stop by just clicking the same connector you started on, it's as easy as that.

**Comment by Claycorp** [comment]
-.- Why did I not try/think of that...
