### ISSUE TITLE
Rendering Issue

### ISSUE THREAD

**Issue by enlightened22** [BluSunrize/ImmersiveEngineering#92]
I just created a fresh minecraft world with the recommended version of forge 1.7.10 and IE. However when I created a world I got a bunch of issues with both vanilla and IE blocks. I'm not the best with mods so sorry if this is a stupid mistake on my side.
![2015-06-25_10 03 27](https://cloud.githubusercontent.com/assets/13052168/8359277/44e18c4a-1b33-11e5-99d8-16a8b7d6e7cf.png)
![2015-06-25_10 04 01](https://cloud.githubusercontent.com/assets/13052168/8359279/44e91c08-1b33-11e5-9883-30a639bbc401.png)
![2015-06-25_10 04 17](https://cloud.githubusercontent.com/assets/13052168/8359278/44e70b16-1b33-11e5-8d98-980ea6daad42.png)

**Comment by porteriscool** [comment]
What current versions of IE and Forge are you running, recommended versions sometimes might not be the best, just sometimes.

**Comment by enlightened22** [comment]
I'm running Immersive Engineering v0.2.3 and tried both forge 10.13.4.1472 and 10.13.4.1448

**Comment by BluSunrize** [comment]
You using Optifine or Shaders or something?

**Comment by enlightened22** [comment]
I am not. I installed forge, on the launcher I added a new profile using that version of forge, and added IE to my mods folder. That is all. Also I'm on a mac, which shouldn't make a difference.

**Comment by porteriscool** [comment]
Try using forge version forge-1.7.10-10.13.3.1389 as it is the version that is put in place in the build gradle:
https://github.com/BluSunrize/ImmersiveEngineering/blob/945c50938e8c5e94c9fb2a0c757cc277e63682c4/build.gradle

**Comment by BluSunrize** [comment]
ForgeCraft is running on 1401 and we don't have issue there either.

**Comment by porteriscool** [comment]
True, from what I can tell from people who post content on YouTube, and those who stream either on Twitch TV/ Beam, there is no issue.

**Comment by enlightened22** [comment]
I tried using forge 10.13.3.1389 and now the textures aren't missing for me, but a lot of textures are wrong. In case there was something weird with my minecraft folder I deleted it and downloaded a new copy of minecraft. 

This didn't make a difference and here are some pictures of how it looks now. Basically a bunch of blocks have their textures switched around.

**Comment by BluSunrize** [comment]
Are there any mods installed apart from IE, and are you playing with a build downloaded from CurseForge?

**Comment by enlightened22** [comment]
I have no other mods installed. I am playing with the build from curseforge that was linked to in the reddit post a few days ago.

**Comment by enlightened22** [comment]
To add on to what I said before I also just tried out v0.2.4, downloaded from curseforge, and it didn't make a difference for me.

**Comment by mindforger** [comment]
maybe make a "large" pastebin of your startup log, i guess it's probably a memory issue or some issue with your gfx device ... last time i've seen this was when i had too many mods installed and my ram settings were too low, thus corrupting the textures loaded to the gfx

**Comment by AEnterprise** [comment]
the latest forge versions 'skips' (not realy skipping, but some things are not loaded) the first texture loading and stiching pass, try what heapens if you dissable that, maybe that's the cause here

**Comment by enlightened22** [comment]
For AEnterprise, how do I disable that feature of forge?

For Mindforger, This is the copy of fml-client-latest.log from my logs folder http://pastebin.com/saAauSNp. Browsing through it myself I see texture errors at the end, but no "nonc crashing."

**Comment by AEnterprise** [comment]
to dissable it add -Dfml.skipFirstTextureLoad=false to your run arguments

**Comment by enlightened22** [comment]
I added that and it still didn't work. I'm assuming location in the run arguments doesn't matter, because I just added it to the end.

**Comment by mindforger** [comment]
sorry i've overseen this issue, you posted the wrong log, the longer one is required, as it contains all errors thrown during texture registration. also please post your full arguments to be sure everything else is okay. 
how many gigs of RAM do you actually have physically installed and lastly is this on a regular gfx or maybe an laptop gfx with shared memory?

**Comment by JAWSAWN** [comment]
What is your computers coding language? I know some languages messing up with Thermal Expansion but shouldn't be with vanilla.

**Comment by enlightened22** [comment]
So I'm on a 2012 macbook with 8 GB of RAM and intel HD graphics 4000, I'm not sure if its shared memory or not, and don't know how to figure it out. Here's my startup argument "-Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M -Dfml.skipFirstTextureLoad=false". Additionally I have changed the startup arguments to "-Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1G -Dfml.skipFirstTextureLoad=false", which did not help either. Where do I find the longer log? I used the latest zip file in the logs folder and didn't see anywhere else to get a log from.

I believe the coding language is objective C, as another note I have been able to run every mod I've tried (100's of them) including thermal expansion on this machine.

**Comment by mindforger** [comment]
in the same folder with the logs there is always a "latest" log file present, open it and search for the startup of your last launch and copy from there ... and after google i would say your HD 4000 is running with very few shared memory and thus probably running out of VRAM .. could probably be an issue with IE but this needs to be profiled and need the proper logfiles to check ... maybe someone with equivalent HW can test this
