### ISSUE TITLE
Windmills generating different amounts of power. [pebkac]

### ISSUE THREAD

**Issue by Dead2** [BluSunrize/ImmersiveEngineering#921]
I am unsure whether this is a bug or us managing to do something wrong somehow, but it seems like one or possibly two bugs to me.

We had 4 windmills when we decided to move them to a location about 20 blocks higher, at the same time we added 4 new windmills. The 4 old ones are on one circuit and the 4 new ones on another. Both setups are pretty much exactly identical, only differing very slightly in total cable length.

The old ones generate 72RF/t (18 per windmill) and the new ones generate 96RF/t (24 per windmill).
Do the old ones remember their first, lower location?
Some or all of the old ones are from before the 0.7 upgrade. The new ones are all from 0.7.1.2. Do the old ones remember something from their old version?

Our setup is like this: 4 windmills on LV -> transformer to MV -> long cables -> current transformer -> capacitor bank -> transformer back to LV

Currently those two sets are connected together after the current transformer, if we didn't then one capacitor bank set would be empty before any power was drawn from the next set of windmills. (Some round-robin method for this would be nice)

I have taken some screenshots of our setup here: http://imgur.com/a/cstEV
The leftmost windmill is in one chunk, then 5 in the next chunk, then the last two in another chunk, so the chunks does not seem to matter.

The single non-improved windmill still at the old location is generating 16RF/t, this also seems odd since the improved ones should double that plus get a bonus from elevation. The extra length of cabling should not matter that much (approx 9 stretches of less than 16 blocks, thus less than 0.4% total loss I think).

PS: We have:
D:"Dynamo: Output"=3.5
There are other changes too, for balancing, but I can not think of anything that should affect this.

**Comment by malte0811** [comment]
Your setup is quite inefficient: if a windmill finds another windmill (center block) within an octahedron with a diagonal length of 12 with the center block of the first windmill in the middle, the speed of both windmills will be significantly lowered. I haven't done the math for this or tested your setup in game, but I suspect that this is causing your setup to produce less power than expected.

**Comment by BluSunrize** [comment]
They don't remember any locations, that's for sure. it's probably just the amount of interference blocks they get. As @malte0811 said, windmills check hte area for things that could "block" the flow of air and lessen their power according to that. if you build a wall infront of a windmill, it'll stop.

**Comment by Dead2** [comment]
After I posted this, I thought that this might cause problems. But if what you say is correct then the front and the back group should produce identically. It seems like it checks more/only to the front, since the front ones produce more than the back ones. (That does seem more realistic though).

I wish things like this was documented somewhere though, I am currently using FTB wiki [1] for reference but it is often lacking details and sometimes seems to be inaccurate. They also reference a reddit post [2] that says you can connect two windmills to a generator, however that does not seem to work, is that really possible?

The mod itself is awesome, it just seems to lack in documentation :)

[1]: http://ftb.gamepedia.com/Immersive_Engineering
[2]: https://www.reddit.com/r/feedthebeast/comments/3bkvzx/immersive_engineering_numbers/

**Comment by XFactHD** [comment]
Have you looked at the Engineers' Manual? It's the documentation you are looking for.

**Comment by BluSunrize** [comment]
Correct. IE has a very nice ingame book that has all you really need to know. THe reddit post is 6 months old too, btw., so yeah, completely crap info really. Then again, never trust reddit. Half the time they don't know wtf they're talking about.
Each generator supports ONE device, be it water- or windmill, and only on the side that looks like the top of a coil. All of that should be quite self explanatory, considering how it's all textured.

IE has just as much documentation as it needs. Because you can easily figure everything out ingame.

**Comment by Dead2** [comment]
Now that I know of this book (I had not noticed it in NEI and have not seen any references to it), I agree that it is awesome. Really good work on that manual, easily the best one I have seen in-game so far.

It lacks a bit of concrete numbers to give references to what kind of power you can expect a windmill to generate versus waterwheel and thermo-gen though. I would not expect a list of power for different conditions, but perhaps a number for a good typical installation and a suggestion that it can be improved upon with better conditions. Otherwise you cannot know what to expect from them in relation to each other unless you google it and find reddit posts etc.

I suggest mentioning the manual in the readme.md file to make it more obvious, although I might be the only one that missed it ;)

It would also be great if the multimeter would print how much power a generator can create in the current circumstances, and possibly how much of that is being used. Troubleshooting a large installation is currently very cumbersome, and I find myself having to disconnect everything and use a current transformer to perform a reading for each and every generator. It could also require the generator to have an 'current sensor' upgrade installed to allow these readings, something that reflects reality nicely. Measuring the power traveling in a cable would be an alternative, but since those are not blocks, it would probably be harder to do and use.

And some way to balance power draw from multiple capacitors/generators would be great, since the current solution of emptying one before jumping to the next is very unrealistic and can cause gameplay issues in setups like mine. Round-robin or random would be good. The best would of course be some solution that emulates resistance, and pulls more from nearby sources than from the more distant ones. This would give gameplay another factor for big nets, so players could design their nets with this in mind to reduce cable loss.
I assume that power is consumed from the closest source currently, at least that is what the behavior seems to be in my net currently.

I hope you take these suggestions constructively, I mean no offence.

Thank you all for answering my questions, I really appreciate it. Keep up the good work.

**Comment by BluSunrize** [comment]
I have absolutely how you managed to miss the book. I really don't.

I don't disclose the full power output because
1) it's configurable
2) it's situationally dependant
3) it's boring, figure it out yourself.

There is no power drawn. Ever. Redstone Flux is a push based system (there are extraction methods, but those are generally not used in energy nets). If your capacitors empty in a line rather than evenly, that sounds more like a wonky wire setup.
And as for resistance and realistic wire physics? We have like 5 closed issues on this github about that, feel free to browse. the tl;dr; is "Nope."

**Comment by Dead2** [comment]
Picture 5-7 on my imgur post shows our capacitor setup, each capacitor is connected by wire together into one wire going into our processing room. Two of the banks have transformers in between too, but the issue shows more easily by only having the four LV capacitors connected.
First the top one near the wall is emptied, then the bottom one, then the next row and so on.

With the MV+transformer ones connected, those are emptied before the LV ones start doing anything. Well, actually one of the LV capacitors is contributing by 2RF/t while one MV capacitor is doing around 300RF/t, the rest of the 5x MV and 3x LV capacitors are idle and are not losing any capacity and thus also not engaging their generators.

I honestly cannot see how this cable setup is wonky.
```
MV CAP \
MV CAP -> Transformer -> connector  \
MV CAP /                             \
                                      \
MV CAP \                               \
MV CAP -> Transformer -> connector    \|
MV CAP /                              ||
                                      ||
LV CAP \                              ||
LV CAP ->                connector   \||
                                     |||
LV CAP \                             |||
LV CAP ->                connector  \|||
                                    connector -> connector -> crusher
```
Each cap also has a connector attached to it of course, but I did not draw those into the above diagram. The diagram is a supplement to explain the screenshots.

I already read a lot of the issues here both open and closed, and as a programmer I completely understand why you don't want to implement realistic wire resistance. I just wish my capacitors worked properly, I guess I'll google it some more and visit some reddit threads ;)

I know RF is a push system, that distinction does not really make any difference here though.
