### ISSUE TITLE
Conveyor Belt blocked by a fence placed beneath

### ISSUE THREAD

**Issue by therealtkh** [BluSunrize/ImmersiveEngineering#922]
For decorative purposes I placed some fence beneath a conveyor belt. Turned out that this blocked the belt completely. Tried a few solid blocks and it worked fine, but fences (and possibly other blocks as well?) makes the belt segment totally blocked.

Using 0.7.1.2.

See screenshot for an example, all ingots will get stucked above the fence. (Items are moving from left to right.)

![2016-01-24_23 26 32](https://cloud.githubusercontent.com/assets/9653254/12539454/2eaf5246-c2f3-11e5-995a-a00fa4892d97.png)

**Comment by BluSunrize** [comment]
It's a friggin fence. They have a 1.5 high bounding box. That's how they block creatures even when they jump. Vanilla knowledge, yo.

That's intended behaviour, not a bug >_<

**Comment by therealtkh** [comment]
Yeah, I know how the fence works, thanks :P I just didn't expect the bounding box to be "active" through the belt.

But if it works as intended then I'll just have to find some other blocks to use for the elevated belts. Any chance of a decorative block similar to a single fence block perhaps? *wink wink* The Structural Arm would have looked nice for sloped belts, but I suspect it might be difficult or a lot of work.

**Comment by BluSunrize** [comment]
yeah, sorta needless amount of work. Have you tried scaffolding? =3

**Comment by therealtkh** [comment]
Don't get me wrong, it doesn't look bad with scaffolding. I just had an idea of having "fence poles" for my viaducts with belts. 

But it would have looked truly awesome with sloped treated wood scaffolds (like the structural arm) beneath the sloped belts, but again, I understand that the amount of work required perhaps isn't worth the outcome :)

![2016-01-25_16 35 37](https://cloud.githubusercontent.com/assets/9653254/12555514/da637494-c381-11e5-83c1-41adde9c2c34.png)

**Comment by cobra** [comment]
Adapting the behaviour from scaffold-covered pipes tp angled conveyors would look awesome, but it will get rather complex - and the rendering code for conveyors is already large.

**Comment by BluSunrize** [comment]
And definitely not a 1.7 feature.

**Comment by therealtkh** [comment]
Fair enough, just expressing my oppinions :)

Let's hope for this feature in the future.
/out

**Comment by mindforger** [comment]
mh just out of curiosity, is shift+rightclick on conveyors already in use ?

just as idea:
could probably toggle a "fill block" mode when angled ?! (and probably adapting neighbour texture of scaffolds or default to wooden scaffold)
