### ISSUE TITLE
[suggestion] limit arc furnace input port from accessing both metal and additive

### ISSUE THREAD

**Issue by zuoanqh** [BluSunrize/ImmersiveEngineering#925]
there's several items can both be smelted and used as an additive, namely obsidian dust with tinker's construct ingot (also used as EnderIO dark steel's additive), gold and silver for electrum, iron for TE's invar and other metal dust as additive.

as of 0.6.5.1 with FTB infinity evolved expert, when i insert from the right input port with any of the 12 metal slots open, items goes to both metal and additive slot, causing smelting of the intended additive instead of moving to additive slot. This would be fixed if the left port can only insert into metal, right port only additive without limiting the function of arc furnace.

**Comment by BluSunrize** [comment]
First off: Always test on latest.
Secondly, I don't account for that because I literally cannot account for every friggin crossmod bug. And doing left/right differently is very unintuitive.

**Comment by zuoanqh** [comment]
well, the metal is on the left on the interface and the additive on the right, i actually thought that was the way when i set it up, just so you know.

it dont have to be cross mod for it to have a problem, you have gold and silver grit and electrum, the same could happen.

i did not test on the latest, but i did read all the change log to make sure its not changed, maybe i get some points for that?

**Comment by zuoanqh** [comment]
in fact if you intend to make the two input the exact same, why not have only one input port to avoid confusing people like me :) one is enough anyway.

**Comment by Bitterholz** [comment]
Well you figured that out did you? no need to over-simplyfy everything!

**Comment by Bitterholz** [comment]
But in General, I Support the Idea of making one of the Inputs restricted to the Additive. 
@BluSunrize I don't know how much you intended the ARC Furnace to be automatable especially when it comes to Alloying. Wich is one of its most prominent uses actually, especially when it comes to Steel making.

Thinking Immersively, it would only be logical to allow a Conveyor line(or sth else) to insert into a dedicated slot for Alloying.

**Comment by theunkn0wn1** [comment]
I third this idea. IE adds alloys that can only be produced within the Arc Furnace, provided no other mods except it's dependents are mounted. If the Arc Furnace is to be believed to be as automated as it is made out to be, we as players **need** means to draw a line between an input that is the primary ingredient and the input that is for additives. Just because IE's core additives can only be inserted one way, doesn't mean that is *the only* way items can be inserted. 

here is an idea to keep things intuitive: Have a look at how Thermal Energistics does multi-input: The inputs are colored and are configurable. By having the two inputs be colored differently, the player can differentiate between what the input drops into in as an intuitive manor as is possible short of completely changing the Arc Furnace structure/View Model that I can come up with.

**Comment by Bitterholz** [comment]
@theunkn0wn1I wouldn't even color it. Positions of the input is enough for its definition. Especially since we have the Ingame Manual.

A Single Input hatch infront of the electrodes for Example, would suffice

**Comment by cobra** [comment]
I'd like some form of locking as well. I accidentally alloyed crushed ores because the arc furnace didn't have any free slots, so one dust (which happened to be gold) went into an additives slot - creating electrum from silver dust in the input slots.

**Comment by codewarrior0** [comment]
+1 for separate input for additives.

**Comment by thorsummoner** [comment]
So according to this wiki page: http://ftb.gamepedia.com/Arc_Furnace_(Immersive_Engineering)
Additives go in on the right, which I setup and nop, ark furnace smelts the obsidian dust instead of using it as additive. If the top right input isn't for additives, which port is?

**Comment by theunkn0wn1** [comment]
@thorsummoner Things reported on third party sites are null if the official in game documentation does not support it. Last I observed, the two input slots are not dedicated one for main and one for additives and given how neither Blu or the OP have closed this thread nor has this thread been referenced by any commits I can see. Thus, this issue thread was born. The OP and various others, including myself, have expressed interest in the feature that 3rd party site reports existing.

The official source, as it appears in 9e7f713, States the following
>Inputs and additives are inserted through the two hatches at the top of the structure, to the left and right of the electrodes.

Where exactly the 3rd party got the impression of the importance of siding I have little idea beyond this thread

**Comment by BluSunrize** [comment]
Yeah what @theunkn0wn1 said. If wiki and book differ, the book is always right.

**Comment by thorsummoner** [comment]
Documentation aside, my real complaint is that there is no way to aromatically craft alloys with the ark furnace, it would be possible if the addatives could be intentionally added. Until this has been addressed the ark furnace simply cannot be used for unattended metalurgy.

**Comment by mindforger** [comment]
i know how you do not like beeing compared to other mods, but how about an button to switch between "normal" "smelt only" and "alloys only" like EIO

only problem i see here would be, what if there is a 3 component and a 2 component alloy sharing the same resources ... in this case the smelting should probably delay for a few ticks and then procceed with the largest possible recipe or simply ignore this fact and make the other mod/modpack author think about and workaround :)

**Comment by BluSunrize** [comment]
Nah, GUI buttons are a pain in the butt, not doing that. =P

Doing the side based input is a thing I can easily do though, I just haven't gotten around to it. 1.8 is taking time.

**Comment by BluSunrize** [comment]
Oh this is totally a thing these days.

**Comment by zuoanqh** [comment]
glad to see that totally a thing these days lol
