### ISSUE TITLE
[suggestion][1.8] Industrial Cable Elevator

### ISSUE THREAD

**Issue by kane-thornwyrd** [BluSunrize/ImmersiveEngineering#926]
That would be very beautiful...
![](https://s-media-cache-ak0.pinimg.com/736x/6e/1c/7e/6e1c7e23b831cc963b419884f4d49470.jpg)
And a good excuse to use the cables, then the "only" things to add would be:
* Engine(s)
* Sheave(s)
* 2 Multi-blocks: 
 - The "rails" using steel scaffolds and sheaves...
 - the Cabin using steel anchors...

How to use it: first build the rails, build the cabin, connect steel cables from the cabin to the sheave to the engine.

Could be "tier"-ed for speed + dimensions.

**Comment by BluSunrize** [comment]
You have skyhooks that do all this for free.

**Comment by kane-thornwyrd** [comment]
@UnwrittenFun just in case... even if I know you won't do it in IE, at least.
Well I have to learn java and how to work with both your APIs then, I hope I'll have the time :pray: .

**Comment by karakufire** [comment]
I already suggested that....... #753 and I was encouraged to use Pneumaticraft...

**Comment by kane-thornwyrd** [comment]
yes, but as Blu said "Entity Movement is a bitch, I wont work on an elevator for quite some time" the 1.8.9 resolve a number of issues about that if my memory serve, hence the [1.8] tag.
