### ISSUE TITLE
Arc Furnace graphite electrodes showing as deprecated after taking damage

### ISSUE THREAD

**Issue by NEXUS2345** [BluSunrize/ImmersiveEngineering#933]
When the Graphite Electrodes in the Arc Furnace suffer damage, they state that they are deprecated and to place them into your inventory. Once you do that and they take damage again, they show the same message.

https://imgur.com/a/Rq9DN

Occurs on version 0.7.1.2

**Comment by malte0811** [comment]
I assume this is happening on a dedicated server? (from the chat message in the screenshot)

**Comment by NEXUS2345** [comment]
Yes, this is occurring on a dedicated server

**Comment by NEXUS2345** [comment]
It appears that this issue has resolved itself after a relog for some reason. Apologies.

**Comment by malte0811** [comment]
You don't have to apologize, and I am not saying that to be polite. This is a bug, I am able to reproduce it in my development environment and it is definitely not the intended behavior. I have an idea on how to fix this, I'll try it tomorrow. But it is certainly an interesting bug.
And it is quite possible that a bug only happens under some conditions that may depend on "the mood the computer is in" (even though this probably isn't the case here), but that wouldn't make it not be a bug any more.

**Comment by NEXUS2345** [comment]
Ok then, I will reopen the issue for now then.
