### ISSUE TITLE
Recursive log on server, aparently IE it's involved

### ISSUE THREAD

**Issue by frenchiveruti** [BluSunrize/ImmersiveEngineering#935]
Hello, I'm sorry if this doesn't belong here, but I can't find any other mod that points to this except yours because of a line in the text wall.  
Here's the log: http://pastebin.com/687ESRfQ  
Is there any solution? What causes it?  
Do you need the files?  
Let me know, thanks.  
FTB Infinity with IE 0.6.5.1

**Comment by theunkn0wn1** [comment]
Might i suggest updating IE to the latest build? You are a full version behind the current release, 1.7.1.2

If the issue persists please tell us what version of FTB Infinity you are using, and any modifications from the official pack you may have made.

**Comment by frenchiveruti** [comment]
Well! I've updated and the problem is solved, sorry for the inconvenience!


Enviado desde Android






On Mon, Feb 1, 2016 at 10:58 PM -0800, "theunkn0wn1" <notifications@github.com> wrote:





Might i suggest updating IE to the latest build? You are a full version behind the current release, 1.7.1.2

If the issue persists please tell us what version of FTB Infinity you are using, and any modifications from the official pack you may have made.

---
