### ISSUE TITLE
[Crash] Forestry 4.2.6 (latest)

### ISSUE THREAD

**Issue by iRhuel** [BluSunrize/ImmersiveEngineering#936]
Crashing with latest build of Forestry. 

Things I've tried (to remove):
Forestry (works)
gendustry
magicbees
all bdew mods including ae2stuff, neiaddons and bdlib
minetweaker (3.0.10) and modtweaker
Optifine HD_U_D1
removing Forestry compat in IE config file

crash log with said mods: http://pastebin.com/B7yTMYar

without: http://pastebin.com/WLikdL6T

**Comment by mindforger** [comment]
thank you for posting a pastebinned crashlog, this has become a rarity in the past :)

but are you sure this pastebin is related? it doesn't state anything about IE at all

zettaindustries is having a clash with forestry here (be adviced binnie did not update it's mods to the newest forestry yet causing several crossmod problems with forestry integrations)
also, you still have optifine installed and you are warned from the crashlog itself to NOT post it until you tested without it
`    Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client:
Optifine
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.`

**Comment by BluSunrize** [comment]
Yep, this is a Zetta Industries error, not an IE one. Report it to them.

**Comment by iRhuel** [comment]
> thank you for posting a pastebinned crashlog, this has become a rarity in the past
Oh I definitely noticed, combing through your past tickets :3

The second pastebin I posted is without optifine and all of the mods listed above. Will try removing Zetta and testing.

Interesting. Crash log now points to minetweaker, I'm updated to 2nd most recent. Will update and retry.

Stable. Reintroducing Zetta.

Crash. :( log points to Forestry, specifically zetta's backpack mod. disabling mod.

Stable. :) There we go. It's the Forestry Backpacks Module of Zetta. Disabling it in Zetta config clears up the conflict with Forestry 4.2.6. Mystery solved. Thank God, I love the Quarry Fixer and Big Battery, didn't wanna have to give those up. What's interesting to me is that the crash only manifests (for me) with IE installed.

Thanks for all the help. Hope this helps somebody in the future.

**Comment by mindforger** [comment]
i am not 100% sure but you truly need the MineTweaker3-1.7.10-3.0.10**B** Version of Minetweaker
