### ISSUE TITLE
NEI related crash for Metal Press Minetweaker Scripts

### ISSUE THREAD

**Issue by Bunsan** [BluSunrize/ImmersiveEngineering#940]
Forge 1558
IE 0.7.1.2
CodeChickenCore-1.7.10-1.0.7.47-universal
NotEnoughItems-1.7.10-1.0.5.111-universal
MineTweaker3-1.7.10-3.0.10B 

I've entered the following scripts:
`mods.immersiveengineering.MetalPress.removeRecipeByMold(<ImmersiveEngineering:mold>);

mods.immersiveengineering.MetalPress.addRecipe(<minecraft:iron_ingot>, <minecraft:iron_ore>, <ImmersiveEngineering:mold>, 2400, 2);`

which crashes on NEI lookup, the recipe is able to complete as expected.
http://pastebin.com/1utF7VyZ

However if I use:
`mods.immersiveengineering.MetalPress.removeRecipeByMold(<ImmersiveEngineering:mold>);

mods.immersiveengineering.MetalPress.addRecipe(<minecraft:iron_ingot>, <ore:oreIron>, <ImmersiveEngineering:mold>, 2400, 2);`

The NEI lookup works. I even tried using a simple array where I set the `<minecraft:iron_ore>` as an IIngredient and it still crashes.

**Comment by laz2727** [comment]
The real mystery there is why all the dots are removed

2016-02-04 20:53 GMT+05:00 Bunsan <notifications@github.com>:

**Comment by malte0811** [comment]
Known and fixed in eede9454dfba94c0d5a7215f44186895ff3e1241 (but never officially reported).

**Comment by Bunsan** [comment]
Well that was fast. :D
