### ISSUE TITLE
Bio-diesel doesn't have a burn time.

### ISSUE THREAD

**Issue by border999** [BluSunrize/ImmersiveEngineering#942]
I know that you probably haven't done this for a reason but it's rather annoying when an obviously very combustible. If at some point you would add a burn time to Bio-diesel, it would be appreciated as then I could use it to run Railcraft's liquid-fueled firebox.

**Comment by hron84** [comment]
Absolute +1. Many mods could use Biodiesel if it would be really combustible.

**Comment by BluSunrize** [comment]
There is no global burn time on fluids, @hron84, every mod handles it separately. I'll look into how it's done for Railcraft, but every other mod requires specific itneraction.

**Comment by PrincessRTFM** [comment]
I thought the forge liquid dictionary allowed that to be specified in liquid properties? If not, maybe it should. Some kind of central core mechanic to indicate fluid burn time would be pretty useful.

**Comment by BluSunrize** [comment]
Feel free to PR that to Forge, and see how far you get with it =P

**Comment by bookerthegeek** [comment]
Wow.... somebody does not know Sarcasm when they read it.

**Comment by BluSunrize** [comment]
Yeah I was being incredibly sarcastic about that. I saw that reaction from Lex coming a mile away .-.

**Comment by BluSunrize** [comment]
Woops, I should leave this open as a todo.
