### ISSUE TITLE
[minor] Steep cables rendered only on one plane and can appear invisible

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#943]
If a wire connection is made between two points that are far apart and have a steep slope between them but is not vertical, the cable is only rendered on one plane. The cables are only rendered parallel to the face of the hypotenuse of the triangle formed between the two points. As a result, the cable can be overly difficult to see from the sides and really stood out. Take the below for example:

![image](https://cloud.githubusercontent.com/assets/3110986/12835588/69d5965c-cb66-11e5-90ad-15eb70dc08a5.png)
![image](https://cloud.githubusercontent.com/assets/3110986/12835614/a38faf72-cb66-11e5-98c0-e468f027bc6c.png)
![image](https://cloud.githubusercontent.com/assets/3110986/12835771/e595cd74-cb67-11e5-834c-535524f02765.png)

-----------
However, when the slope is shallower or vertical it renders as expected:
![image](https://cloud.githubusercontent.com/assets/3110986/12835739/97484ac0-cb67-11e5-9753-e445dcbf3eeb.png)

This issue does NOT affect the functionality of the cable, but can (and did for me) break the immersion factor. 

IE build 8b379db3dd4d22bbd14a406755c902646e6bed3f

**Comment by XFactHD** [comment]
I am also seeing this with horizontal cables that span over long distances, even if the connectors are on the same height.

**Comment by malte0811** [comment]
The commit above should fix this as well as making the rendering more acurate (the sections of the wires have a radius of precisly (except for rounding errors...) the radius specified for the used wire). Wire rendering will be a little bit slower because of this, but it shouldn't be noticable.
