### ISSUE TITLE
Wooden post rendering issue(+1)

### ISSUE THREAD

**Issue by theunkn0wn1** [BluSunrize/ImmersiveEngineering#944]
Two issues for the price of one!

Issue 1: One can place wire connectors both above **AND** below a wooden post extension, allowing the second issue to occur. It was unexpected that the wooden post extension would render twice nonetheless allow this kind of connection to occur :/ Due to this line in the manual:

> Placing blocks below the arms of the wooden post  will **flip** the arms upside down.

 

=================
Issue 2:
When the two extension legs, arrived to by issue 1, are rendered some Z-Fighting occurs.
![image](https://cloud.githubusercontent.com/assets/3110986/12836235/b74746ce-cb6b-11e5-9f51-711fdc5f74e0.png)

--------------
IE build 8b379db

**Comment by BluSunrize** [comment]
Yeah, I know. Not easily fixable, because I won't limit connectivity again. Live with it.
