### ISSUE TITLE
mod not loading.

### ISSUE THREAD

**Issue by DanPaladin12** [BluSunrize/ImmersiveEngineering#949]
Hello everyone,

I've got a problem, after updating my IE to version 0.7.1.2 my server and single player games dont want to load. During loading its stuck on: starting recipe profiler for Arc Recycling, using 4 Threads. I dont know what to do other than reverting to the older version I used before.

I have tried creating a new world as I thought the problem might have been with the world itself and I have removed the config file, yet this did not work.

If anyone knows how to fix this problem please tell me, I would love to know.

**Comment by BluSunrize** [comment]
There's a config to disable the arcfurnaces recycling function.
