### ISSUE TITLE
(v0.2.4) [Major Issue/Derp] Engineer's Hammer doesn't pulverize ores

### ISSUE THREAD

**Issue by JAWSAWN** [BluSunrize/ImmersiveEngineering#95]
The hammer does not work on ore and ingots except Nickel and Lead. And when used with nickel and lead the hammer doesn't return but lost in the recipe (isn't it suppose to get damaged?)
Also this shown in the guide.

**Comment by BluSunrize** [comment]
It only works on Ores that don't have a dust added by other mods. That recipes is only for using IE standalone.

**Comment by JAWSAWN** [comment]
Can I enable that somehow to ignore other mods? That thing you said kinda made no sense. If you can pulverize iron why that machine cannot pulverize lead or nickel?
Also what if I want to only use IE by itself with other mods?

**Comment by BluSunrize** [comment]
It works like this: If another mod adds a metal dust, that metal won't be crushable with a hammer. Because crushing ores with a hammer is way too easy and should only work when IE is being used on its own.

**Comment by JAWSAWN** [comment]
But that other mod can also crush lead dust, but it didn't add any lead dust. Like metallurgy, adds a crusher that can crush lead but lead recipe with hammer is still there.
Also isn't that makes the mod like.. addon-ish? 
Maybe you should add simple handheld crusher that runs of from manpower like ae2? Also losing the hammer after crushing of ores is a bit odd and wrong. Just giving suggestions and feedback :)

**Comment by BluSunrize** [comment]
I cannot check if there is a recipe for pulverization. I can only check if the dust exists. There's hundreds of mods that allow you to crush/pulverize/macerate ores, and each has a different recipe handler. It's a logistical imposibility.

**Comment by gjgfuj** [comment]
Would it hurt to add config options to ignore if it exists?

**Comment by BluSunrize** [comment]
Yeah, since it severly messes with balance =)

**Comment by gjgfuj** [comment]
Yes but config options bypass balance. If you set a config option then the
unbalancedness is on your head.
