### ISSUE TITLE
[Bug][0.7.1.2]Shift clicking from Engineer's Workbench causes item loss

### ISSUE THREAD

**Issue by NEXUS2345** [BluSunrize/ImmersiveEngineering#950]
Steps to reproduce:
1. Fill one row of inventory
2. Place Engineer's Workbench with Graphite Electrode Blueprint
3. Place in 2 stacks of HOP graphite ingots
4. Shift click electrodes out
5. You should receive 27 instead of the 32 you should get
6. No items left inside the Workbench, 20 ingots of HOP graphite lost

Forge 1614 server, Forge 1566 client

**Comment by malte0811** [comment]
Um, I am unable to reproduce this. What exactly do you mean by 

> 1. Fill one row of inventory

? Do you mean that I have to have an item in every slot of my hotbar? And are the input items vanishing immediately or do you have to close and reopen the GUI (or try to click on an input stack or something like that) for them to stop being rendered?

**Comment by NEXUS2345** [comment]
Fill 9 slots of your inventory with other items. Then shift click the items out of the workbench. Instead of getting 32 electrodes from 2 stacks of HOP Graphite, you will only receive 27. There will be no graphite left inside the workbench, therefore you have lost 20 ingots of graphite.

**Comment by malte0811** [comment]
Ok, so the electrodes automatically unstack when they go into your inventory? They stay as a stack of 32 for me. What other mods do you have installed?

**Comment by NEXUS2345** [comment]
Modlist: http://www.technicpack.net/modpack/aeon-pack.767504/mods

Yeah, they won't stack for me.
