### ISSUE TITLE
Remove config option to remove effects

### ISSUE THREAD

**Issue by Joshwoo69** [BluSunrize/ImmersiveEngineering#951]
the effect slippery is very annoying to players "including me" adding a option to disable it would be good.

**Comment by theunkn0wn1** [comment]
1. Please learn some manners. 
2. can you please elaborate on 'the effect slippery', I am finding it difficult to understand what you mean.
3. Your title is both confusing and apparently opposite of what you are asking for :confused:

**Comment by BluSunrize** [comment]
He is talking about the potion effect @theunkn0wn1:
The potion effect that is ONLY applied when someone uses a chemical thrower with lubricant or oil on you. There is no other way that effect should ever hit you. So if you really have a player constantly covering you in lube, maybe just ask them to stop?

**Comment by Joshwoo69** [comment]
Okay let me explain..
I did not use the chemical thrower. Eating food from pam's harvestcraft or drinking bottled water has sometimes the effect of being slippery (intended?)

**Comment by AlterAkima** [comment]
This certainly is not intended, must be a potion id conflict.

**Comment by Joshwoo69** [comment]
I think I know what is the problem....the food should give me "well feed" buff. But looks like it is conflicting with the Immersive Engineering buff. Which is "slippery" debuff. Thus thus occurs.

**Comment by BluSunrize** [comment]
Fix your potion ID conflicts then, lol. That's not my fault!
