### ISSUE TITLE
Crusher produces wrong amounts for minetweaker items.

### ISSUE THREAD

**Issue by Haggle1996** [BluSunrize/ImmersiveEngineering#952]
I have a section of minetweaker script that provides a custom output for Harder Ores ore. Specifically, Harder Ores uses metadata to indicate the richness of the block (with metadata 15 being the richest, and 0 being the poorest). I setup minetweaker scripts so that an ore block has a different output for each metadata, as noted below. However, whichever metadata is put in the crusher first, the crusher will remember and ONLY output that amount. E.g., if the first ore put in has metadata 15, the crusher will always output 64 raw ore, even if a metadata 4 is put in next (which should result in 20).

```
mods.immersiveengineering.Crusher.addRecipe(<HarderOres:ore_chunk:8> * 64,<HarderOres:ore_iron:15>, 25600, <minecraft:cobblestone>, 0.25);
mods.immersiveengineering.Crusher.addRecipe(<HarderOres:ore_chunk:8> * 60,<HarderOres:ore_iron:14>, 24000, <minecraft:cobblestone>, 0.25);
mods.immersiveengineering.Crusher.addRecipe(<HarderOres:ore_chunk:8> * 56,<HarderOres:ore_iron:13>, 22400, <minecraft:cobblestone>, 0.25);
mods.immersiveengineering.Crusher.addRecipe(<HarderOres:ore_chunk:8> * 52,<HarderOres:ore_iron:12>, 20800, <minecraft:cobblestone>, 0.25);
mods.immersiveengineering.Crusher.addRecipe(<HarderOres:ore_chunk:8> * 48,<HarderOres:ore_iron:11>, 19200, <minecraft:cobblestone>, 0.25);
mods.immersiveengineering.Crusher.addRecipe(<HarderOres:ore_chunk:8> * 44,<HarderOres:ore_iron:10>, 17600, <minecraft:cobblestone>, 0.25);
mods.immersiveengineering.Crusher.addRecipe(<HarderOres:ore_chunk:8> * 40,<HarderOres:ore_iron:9>, 16000, <minecraft:cobblestone>, 0.25);
mods.immersiveengineering.Crusher.addRecipe(<HarderOres:ore_chunk:8> * 36,<HarderOres:ore_iron:8>, 14400, <minecraft:cobblestone>, 0.25);
mods.immersiveengineering.Crusher.addRecipe(<HarderOres:ore_chunk:8> * 32,<HarderOres:ore_iron:7>, 12800, <minecraft:cobblestone>, 0.25);
mods.immersiveengineering.Crusher.addRecipe(<HarderOres:ore_chunk:8> * 28,<HarderOres:ore_iron:6>, 11200, <minecraft:cobblestone>, 0.25);
mods.immersiveengineering.Crusher.addRecipe(<HarderOres:ore_chunk:8> * 24,<HarderOres:ore_iron:5>, 9600, <minecraft:cobblestone>, 0.25);
mods.immersiveengineering.Crusher.addRecipe(<HarderOres:ore_chunk:8> * 20,<HarderOres:ore_iron:4>, 8000, <minecraft:cobblestone>, 0.25);
mods.immersiveengineering.Crusher.addRecipe(<HarderOres:ore_chunk:8> * 16,<HarderOres:ore_iron:3>, 6400, <minecraft:cobblestone>, 0.25);
mods.immersiveengineering.Crusher.addRecipe(<HarderOres:ore_chunk:8> * 12,<HarderOres:ore_iron:2>, 4800, <minecraft:cobblestone>, 0.25);
mods.immersiveengineering.Crusher.addRecipe(<HarderOres:ore_chunk:8> * 8,<HarderOres:ore_iron:1>, 3200, <minecraft:cobblestone>, 0.25);
mods.immersiveengineering.Crusher.addRecipe(<HarderOres:ore_chunk:8> * 4,<HarderOres:ore_iron:0>, 1600, <minecraft:cobblestone>, 0.25);
```

**Comment by theunkn0wn1** [comment]
I have noticed something similar without the use of MineTweaker, so it might be the same bug.

==============
if two different Nether ores, with two different output rates, are entered into the Crusher around the same time, The output of the second Nether ore is permanently lowered to that of the first ore, even without the outputs being modified by MineTweaker. The unintended modification persists until the server is restarted.

-------------
Steps to reproduce:
[1] Construct, activate, and power a valid crusher
[2] Place 5 Nether Coal ore (apparent default output of 5) into crusher
[3] place 5 Nether Lapis (Apparent default output of 24) into crusher while the Coal is still being proccessed.
[4] Once all proccessing is complete, note the outputs and the NEI recipe changes.

---------------

IE build 773334b3ecc3e889f22b004995bb459211dbe762

**Comment by Haggle1996** [comment]
I believe it is related to this line:

https://github.com/BluSunrize/ImmersiveEngineering/blob/33a2412ec297cdf0c889404d53a8795419a7ed27/src/main/java/blusunrize/immersiveengineering/common/blocks/metal/TileEntityCrusher.java#L264

**Comment by Haggle1996** [comment]
Nevermind...after reverse engineering your dependencies so I could build Immersive Engineering locally (no trivial task, thank you very much! :P ) and then stepping through your code, turns out the problem is that the ores are all in the same ore dictionary, so they never even get to the line to compare their metas. Please forgive me. :D

**Comment by BluSunrize** [comment]
OreID takes priority over Hash, yeah
