### ISSUE TITLE
[Bug] FTB Infinity Evolution Assemblers can turn dirt (or any microblock) into any other block

### ISSUE THREAD

**Issue by Leasara** [BluSunrize/ImmersiveEngineering#954]
By making Microblock Slabs of something like a Diamond or Emerald or Enderium block, then making a pattern to craft the slabs back into blocks, you can input dirt slabs and get Diamond or Emerald or Enderium blocks.  If you can make a microblock of it, you can turn worthless blocks into that block.

**Comment by BluSunrize** [comment]
Aaah. Seems like there might be an NBT check in order...
