### ISSUE TITLE
[Bug] GUI Problem (7.1.2)

### ISSUE THREAD

**Issue by SIBIROK** [BluSunrize/ImmersiveEngineering#956]
GUI is static. There is no animation of burning time etc
When i created Coke Oven and right-clicked it with Hammer, there was no texture swap.
When i opened gui and added coal and ingotts they just "dissappeared"
After save reload all ingots appeared again but gui is static.
Everything is working without animations.
Maybe its OptiFine problems. Need to check.

**Comment by SIBIROK** [comment]
That was optifine problem.

**Comment by XFactHD** [comment]
Please close the issue if you solved it.
