### ISSUE TITLE
[Suggestion] Hidden Multiblocks for cables

### ISSUE THREAD

**Issue by ThomasRules2000** [BluSunrize/ImmersiveEngineering#958]
For the cables, would it be possible to create invisible multiblocks that follow the line along as a solution to placing blocks in the cables. This would allow the cable to be preserved without causing the lag from constant raytraces.

**Comment by XFactHD** [comment]
This request is useless because it is possible to place blocks where the cable is and the raytracing is only happening once when the cable is placed.

**Comment by BluSunrize** [comment]
No. It's not possible. Nor do I want it.

**Comment by ThomasRules2000** [comment]
It was just a thought about how to stop people placing blocks in the cables, as there doesn't appear to be a way, currently, to stop that

**Comment by BluSunrize** [comment]
I don't want to stop that O_o
People are already bitching that I don't have hidable wires
