### ISSUE TITLE
Coke Oven Bug?

### ISSUE THREAD

**Issue by Akull9** [BluSunrize/ImmersiveEngineering#96]
When I use the Coke oven in any operation, it nearly instantaneously completes whatever it was doing...
Looking in NEI it states that most operations take a couple thousand ticks...
I'm Using v0.2.4 of Immersive Engineering with a bunch of other mods, I can put together a list if requested to do so

**Comment by BluSunrize** [comment]
Sugar! That was a debug feature I didn't remove! :D
