### ISSUE TITLE
Do you think more machine which use IE electric power.

### ISSUE THREAD

**Issue by brkdgl07** [BluSunrize/ImmersiveEngineering#961]
There are many energy sources. I like it, there are also many machine using them. but mostly using for generating more power. would be great if you add more machines help making something easier . I have been waiting a farming machine for a month man :D

in addition, when hammer constructs multiblock machine,  a sound effect like anvil would be better.

**Comment by BluSunrize** [comment]
And I've been waiting to move to 1.8 for a year. So you'll get to wait a bit longer.
