### ISSUE TITLE
[Bug] Excavoator only digs dirt

### ISSUE THREAD

**Issue by beakerwade** [BluSunrize/ImmersiveEngineering#962]
The excavator will only dig out the frst couple of dirft blocks but then just comes up empty and I've tried to fix it but it won't work
![2016-02-15_20 27 08](https://cloud.githubusercontent.com/assets/14164457/13064627/9a858748-d422-11e5-8445-5a5cb2a7f935.png)

**Comment by AlterAkima** [comment]
Have you tried using the Core Sample Drill to check if the chunk does have minerals?

**Comment by beakerwade** [comment]
No i am new to this mod so how do these work?

**Comment by AlterAkima** [comment]
Place the Sample Drill in the same chunk as the Excavator, give power, then click the Drill when it charges.
Or use /ie mineral get if you can.

**Comment by beakerwade** [comment]
No there isn't any (I checked thanks :) )but would you know why because it is a normal world with normal minerals but none are detected

**Comment by AlterAkima** [comment]
The minerals are distributed through chunks, there are places that have, others that don't have, you can check what ores the type of mineral the chunk have in the Excavator's page in the book.

**Comment by beakerwade** [comment]
ok thanks for your help it was me and notthe mod (duhhhh)

**Comment by mindforger** [comment]
if your problem is solved then, you should close the issue :)

**Comment by BluSunrize** [comment]
Read a damn book next time, it would have answered all these questions.

**Comment by mindforger** [comment]
@BluSunrize inhibit the ability to form the multiblock prior having the achievement RTFM :D ... whenever you use the hammer to form a multiblock prior RTFM you could spam the user with RTFM!!! XD
