### ISSUE TITLE
Advanced Hydroelectric Generators [Suggestion]

### ISSUE THREAD

**Issue by tylerjcw** [BluSunrize/ImmersiveEngineering#964]
I had the thought that maybe a new block (maybe multiblock) should be added that is a more advanced version of the waterwheel (Like a Hydroelectric turbine). Said block could generate maybe 100RF/t at the lowest to 300RF/t at the highest. This would keep it quite balanced with the already implemented waterwheel, which in my tests produces about 90RF/t with three waterwheels to one turbine. The new hydroelectric generator i propose could possibly look something like this:

![Three Gorges Dam](http://p3.img.cctvpic.com/20110603/images/1307083266393_1307083266393_r.jpg)

![Turbine Cut-Away](http://www.climatetechwiki.org/sites/climatetechwiki.org/files/images/extra/media_image_2_14.png)

I personally would like to build a massive dam and put a few of these inside of it. I think that would look quite awesome. Plus, we already have the Advanced Windmill, why not the "Advanced Waterwheel"?

**Comment by theunkn0wn1** [comment]
I support the addition of an advanced form of the watermills perhaps as an MV multi block appliance that resembles the OP's references. I really like the idea of making huge hydroelectric power generation facilities not unlike those of the real world even if simplified. 

+1

**Comment by tylerjcw** [comment]
If we wanted to take it to extreme levels, this could be a more end-mid to end game generator, producing pretty large quantities of power (Maybe 1000 RF/t). Obviously the material costs would be rather high, but putting a few of these together would generate an adequate supply of power for a mid-tier player base.

**Comment by mindforger** [comment]
i'll just leave thislink , as i think it contains enough inspiration to find an adequate solution :D 
https://de.wikipedia.org/wiki/Wasserturbine << contains better graphics
https://en.wikipedia.org/wiki/Water_turbine

**Comment by BluSunrize** [comment]
Overpowered as heck.
Waterwheel were already nerfed due to the massive amounts of free energy they provide, upping taht to 300 Flux/t seems like a terrible imbalance.

**Comment by laz2727** [comment]
Just make them exactly as space-efficient. Basically just bigger.

**Comment by BluSunrize** [comment]
at that point you can just make more waterwheels >__________<

**Comment by laz2727** [comment]
They aren't as lag-efficient and they look cheap.

**Comment by BluSunrize** [comment]
The heck do you know about my lag efficiency?
and if they look cheap, use a texture pack or give them a nice metal wrapper?

**Comment by laz2727** [comment]
Five times the size means five times less potentially ticking tiles per
rf/t.
Doesn't stop them from being wooden waterwheels.

2016-02-18 19:40 GMT+05:00 BluSunrize <notifications@github.com>:

**Comment by BluSunrize** [comment]
You literally have no idea how my mutliblocks work, do you?
TileEntities!=Lag. Even a ticking tile doesn't explicitely cause lag as long as it's not actually performing any work. And mine don't if they don't have to.
6 Waterwheels or 1 turbine the size of 6 waterwheels make a negligeable difference in lag.

As for your second issue: Write your own mod then.

**Comment by laz2727** [comment]
I *know* how they work(kinda). And even though it's small, it's still 6
times smaller.

 As for second issue: i don't really care that much, i just want to argue
over nothing.

2016-02-18 19:48 GMT+05:00 BluSunrize <notifications@github.com>:

**Comment by BluSunrize** [comment]
Then get the fuck off my github because I don't have time to humor trolls.

**Comment by laz2727** [comment]
You really need to rest. Your answers are worse than lex's and i wasn't
even trolling.

2016-02-18 19:55 GMT+05:00 BluSunrize <notifications@github.com>:

**Comment by SkySom** [comment]
"I just want to argue over nothing" If that's not trolling, then what is?

**Comment by laz2727** [comment]
I wasn't trolling. I was defending a suggestion that i don't see as a huge
improvement.

2016-02-18 20:01 GMT+05:00 Skylar Sommers <notifications@github.com>:

**Comment by theunkn0wn1** [comment]
Guys, calm down. Blu has spoken and he has the authority here and you need to respect that if you want anything from him.
 Waterwheels are the way they are because they make sense and are balanced as they are. They are intended to get the player of the ground, not sustain an ME system or whatever. As much ai would like better power generation from the wheels, I can always add more. Generating MV levels of RF from free water just cannot be balanced imho

If you really want an advanced form do it yourself as an IE add-on. 

Bickering will not help your case @laz2727 your messages haven't been awfully constructive and I do agree with Blu's labeling of them.

**Comment by BluSunrize** [comment]
Cheers @theunkn0wn1

Yeah, my final word is : No upgraded waterwheels planned. All higher tier energy generation should come at the expense of resources, e.g. Diesel Gen.

**Comment by tylerjcw** [comment]
Well, it was worth a shot. Thanks for taking a look at the suggestion though. As a final note: Maybe make it so oil or some sort of lubricant needs to be pumped in and consumed to keep it running?
This MIGHT balance it out, as it would be kind of like a fuel.

**Comment by theunkn0wn1** [comment]
That would give use to the pumps and an additional usage for seed
oil...perhaps the turbine would require a large sum of steel to build and
even more to maintain via consumable turbine blades...

**Comment by AEnterprise** [comment]
maybe something that requires large amounts of seed oil as lubricant to keep running?

**Comment by bookerthegeek** [comment]
@BluSunrize you have a patron? I just want to give you money do to how blunt you are with stupid people. It is refreshing.

Also cause you have a great mod.

**Comment by BluSunrize** [comment]
patreon.com/BluSunrize

And you can get a cool revolver skin too =P

**Comment by bookerthegeek** [comment]
That I will like. :) keep up the amazing work, don't let the haters bring you down. Know that for every person who complains hundreds are just to lazy to say thanks.

KKCO

**Comment by Cracks777** [comment]
after creating a pledge to you how do we get access to your dev dropbox?

**Comment by BluSunrize** [comment]
I update those lists at the start of every new month, and you'll need to send me your dropbox email. It tells you that when you're pledging.
