### ISSUE TITLE
Silver and Lead ore not ore dicting for tcon smeltery recipes

### ISSUE THREAD

**Issue by JetstormLP** [BluSunrize/ImmersiveEngineering#965]
Using IE 0.7.1.2 and Tcon 1.7.10-1.8.8 versions, the silver and lead ores from IE are not getting smeltery recipes for melting into liquid forms despite all other ores using the correct recipes.

**Comment by AlterAkima** [comment]
Liquid lead/silver and the respective parts only load if Thermal Expansion is present.

**Comment by JetstormLP** [comment]
So then would it be a Tcon issue that they aren't allowing for IE lead/silver?

**Comment by AlterAkima** [comment]
It's their compatibility decision, not an actual issue.
