### ISSUE TITLE
[Bug] FTB Infinity Evolution Item Robin entity overflow

### ISSUE THREAD

**Issue by Leasara** [BluSunrize/ImmersiveEngineering#966]
A player on our server was using an Item Robin to do something with Natura Blueberries being fed through the Item Robin into EnderIO Crafters.  The Item Robin seems to have buffered some crazy amount (at least 120k) of blueberries and when the player tried to move the Item Robin it dropped its buffer and the exploding entity count crashed the server.

**Comment by aikpoppel** [comment]
@Leasara
try "/gamerule doTileDrops false" break the router and after that set it to true again

Do you mean Item Robin or Item Router, because the Item Robin is from Immersive Integration MOD.

**Comment by BluSunrize** [comment]
The Item Robin is from Immersive Integration, not IE. Report it to @UnwrittenFun
