### ISSUE TITLE
Thermoelectric piles not recognizing heat\cold blocks properly

### ISSUE THREAD

**Issue by Maxiride** [BluSunrize/ImmersiveEngineering#968]
I've noticed that placing 2 heat sources with 2 cold sources doubles the rf/t output of the themopile, that's fine and I suppose it's how it's meant to work.

However when I built the pattern shown in the screenshot I initially had 1178 rf/tick, (18 thermopiles * 31*2 rf/t + 2 thermopiles at 31 rf/t) using blazing pyrotheum and gelid cryotheum on 4 sides of each thermopile (except 2). After a while however the rf output dropped to 700 rf/t. So I imagine that some of the thermopiles are not recognizing the surrounding source blocks.

Of course the flux energy conduit are properly tiered to transmit the rf/t.

[imgur screenshots](https://imgur.com/a/VluEI) 

EDIT:
As a futher proof if I isolate one group of 4 thermopiles I get 248 rf/t, exactly the amount expected from 62*4.
Added images to the imgur album.

**Comment by BluSunrize** [comment]
As far as I'm aware, not an issue on my side...

**Comment by Maxiride** [comment]
Uh, that's unexpected. Any suggestion on how can I try to troubleshoot the issue?

**Comment by BluSunrize** [comment]
More energy meters on the connections between hardened and redstone conduits maybe. Identify the faulty cell.

**Comment by Maxiride** [comment]
If I do a test for each group of 4 piles the rf meters shows up the right amount of rf/t. However when they are all attached some redstone flux conduits get filled and sum doesn't match anymore. I'll try to troubleshoot it more but I can confirm it's not an issue on the Immersive Engineering side ;)
