### ISSUE TITLE
Mineral Deposits probability

### ISSUE THREAD

**Issue by Maxiride** [BluSunrize/ImmersiveEngineering#969]
After some time I eventually scanned a whole region (16x16 chunks) and found out interesting numbers which I don't necessarily consider proper\improper.

For a total of 256 chunks scanned, 32 veins have been found (12.5% of the total) and their relative chance against the total 32 veins, [here a screen of the map](http://i.imgur.com/TgIbecc.png)
- Bauxite 4 12.5%
- Silver 1 3.1%
- Coal 2 6.3%
- Magnetite 4 12.5%
- Copper 2 6.3%
- Gold 4 12.5%
- Lead 1 3.13%
- Pyrite 2 6.3%
- Galena 3 9.4%
- Nickel 2 6.3%
- Cassiterite 2 6.3%
- Lapis 1 3.13%

Given the amount of resources a vein can provide I honestly consider this percentages good, what left me a bit disappointed on the other hand is that on the such vast scale of a region not all the veins can be found. In particular, two veins are missing: Platinum and Quarzite. The percentages are already very low (both the chance of finding a vein, and the chance of finding a different vein), if these two veins have an even lower chance it's almost impossibile to find them! Making even the research worthless.

Is the difficulty in finding Quarzite and Platinum veins intentional or thee might be some random function to tailor better in the mod?

**Comment by Berserker66** [comment]
I'd like to see all those numbers to be tweak-able in the config file. I'd also love the ability to set a chance for infinite veins.

**Comment by mindforger** [comment]
>I'd like to see all those numbers to be tweak-able in the config file. I'd also love the ability to set a chance for infinite veins.

use minetweaker, we have a whole lot of "reality style" veins in our modpack, that never have 0% fail chance but contain vast amounts of dirt,gravel,stone and all that kind of tashy stuff in it ... aluminium f.E. is found in a red sand vein, containing vast amounts of sand and red sand and about 5% aluminium ore

**Comment by toric55** [comment]
@mindforger, what version is your pack? im making one for 1.7, (waiting for logisticspipes) is the minetweaker support in that version? would you mind sending me your config?

**Comment by mindforger** [comment]
i need to grab my old configs when i am home and upload them somewhere, please open an issue on my IE fork, so we not disturb BluSun with our conversation :D
https://github.com/mindforger/ImmersiveEngineering
