### ISSUE TITLE
Crash when linking with voltmeter

### ISSUE THREAD

**Issue by JCLaHoot** [BluSunrize/ImmersiveEngineering#970]
I've been having an issue where when I try to figure out the energy loss between two connectors, using the voltmeter, the game crashes. It doesn't happen when I'm just linking cables without the reading...

I'm using the FTB infinity modpack, on a mac. 

I'm not sure if this is important, but the power network mixes A LOT of mods. there's some Thermal Dynamics energy ducts, an Ender IO capacitor bank, some Thermal Expansion machines, some Forestry ones, some BC Transport pipes being powered, and a Railcraft machine. The links I was trying to test have powered lanterns running through them. It's important to note that the voltmeter was working several days ago when I used it last, but my network of machines has become more complex since then.

Here's some log files: They seem to have lines that point to an IE error, but this is the first time that I made a bug report for Minecraft, so I apologize in advance if I sent too much / not enough.
[logs.zip](https://github.com/BluSunrize/ImmersiveEngineering/files/139869/logs.zip)

**Comment by XFactHD** [comment]
IE version?

**Comment by JCLaHoot** [comment]
0.6.5.1, though it's the most up to date version of the mudpack... I also haven't seen anything about this particular crash in the changelogs, unless it's one of the mysterious hotfixes...

**Comment by XFactHD** [comment]
Poke FTB to update their goddamn modpacks.

**Comment by malte0811** [comment]
I think I know what is happening, did you replace the connector you first clicked on with a kinetic dynamo before clicking on the second connector? If you did so, I know how to fix it.

**Comment by mindforger** [comment]
uuuhhhhh i already saw that one long ago with the "HV multi connection bug" but i totally forgot about it! there was never checked again if the source connector is still present anymore when clicking the second connector ...
