### ISSUE TITLE
Add heater compatibility with modded furnaces

### ISSUE THREAD

**Issue by SadChimera** [BluSunrize/ImmersiveEngineering#971]
Such as Steve's Workshop crafting table and/or Ewy's Workshop crafting tables.

**Comment by BluSunrize** [comment]
There wasn't even a "please" in there.
It works with Natura's Furnace and it works with Thaumcraft's Essentia Smelter. Others are not my priority but it features an API that allows other mods to add this compat themselves or you to make an addon for crossmod.
