### ISSUE TITLE
[Suggestion] Piezo-Electric Generator

### ISSUE THREAD

**Issue by baconofspam** [BluSunrize/ImmersiveEngineering#972]
Thinking of a block, crafted with a block or more of quartz, that will generate a small amount of electricity when pressed against by a piston or jumped on by an entity. 

It would be a minor amount of energy, possibly comparable to four redstone engines from BC and about as hard to build, but it would give a good option for remote machines like oil pumps. 

Just thinking of a form of power I haven't seen in other mods yet that could fit well within IE. 

Would be cool if it could be crafted with boots of some sort to generate power when walking and running, too, but not when flying.  This would let players recharge their jetpacks and tools by running for awhile.

**Comment by theunkn0wn1** [comment]
For those remote installations just make a bank of watermills to provide the power. Watermills already provide the means to generate energy from nothing and adding the requested might upset the balance of things as well as promoting tick rate killing practices to populated servers... Being able to recharge the railgun just by retreating during combat just doesn't sound right....

Imho, Cool concept but I don't think it truly fits the theme Blu has in mind for IE

**Comment by BluSunrize** [comment]
Yeah the piston spam is what bothers me quite a bit. Pistons and redstone are incredibly laggy and I'd rather not encourage that. Add that to the fact that IE already already has a lot of passive gen, and therefore, this probably won't be implemented.
