### ISSUE TITLE
Creosote showing negative in coke oven.  [0.6.6] in FTB infinity 2.3.3

### ISSUE THREAD

**Issue by defakto** [BluSunrize/ImmersiveEngineering#979]
While running the coke oven I noticed it was pushing -20,000 mb of creosote oil.  The value increased for a while then stopped at -1536.

It started with a weird issue creating coal coke.  For some reason one channel pushed out two pieces of coal coke and also the system was outputting 3000 mb of creosote for every 4 coal coke made.

![2016-02-28_11 44 04](https://cloud.githubusercontent.com/assets/2061658/13380816/d15386a6-de10-11e5-8f0e-6fd0b4daff2c.png)

**Comment by laz2727** [comment]
Iirc this coke oven makes more coke per coal.

**Comment by Cracks777** [comment]
this is not from this mod its from
https://github.com/UnwrittenFun/ImmersiveIntegration

**Comment by defakto** [comment]
You know what, too many tabs open. Sorry about that.

**Comment by theunkn0wn1** [comment]
Is that the vanilla IE coke oven or is that the one from II? Last I checked IE's oven doesn't cook more than one item at a time...


I suggest reporting this to @UnwrittenFun as the MB in question is apparently one of his

**Comment by BluSunrize** [comment]
That's Immersive Integration as such I'm closing this.

Please move this to the II issue tracker over here:
https://github.com/UnwrittenFun/ImmersiveIntegration/issues
