### ISSUE TITLE
Crash in manual when clicking what's new stuff

### ISSUE THREAD

**Issue by Ozzymud** [BluSunrize/ImmersiveEngineering#981]
Custom pack, crafted the manual, opened it up, clicked "Update News", then upon clicking "What's new in 0.7.1" it crashes the client. Using the manual other then the one 0.7.1 entry seems to work fine so far.

crashlog: http://pastebin.com/ev5e8mqF

**Comment by malte0811** [comment]
#974, #892
Please check whether a bug has already been reported before reporting it.

**Comment by Ozzymud** [comment]
Sorry, I only checked open issues, those 2 are closed
