### ISSUE TITLE
Engineer's Manual: Null Crash when a given IRecipe does not match any of the expected recipe types

### ISSUE THREAD

**Issue by Joshwoo69** [BluSunrize/ImmersiveEngineering#985]
pastebin crash log : http://pastebin.com/BgWxaPAb

**Comment by BluSunrize** [comment]
Update to the latest version of Minetweaker.

**Comment by Joshwoo69** [comment]
thanks i swore i updated to latest version.

**Comment by BluSunrize** [comment]
You'll want 3.0.10b

**Comment by Joshwoo69** [comment]
Yeah got that version works like a charm now.

**Comment by Joshwoo69** [comment]
hmm still crashed when workd loads up world : http://pastebin.com/45k4iQ9Z

**Comment by mindforger** [comment]
@Joshwoo69 you managed to provoke an probably impossible situation
@BluSunrize yo could use a nullcheck if you do not have 100% assurance that you if block could probably fallthrough https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/lib/manual/ManualPages.java#L449-L472 this If-elseIf-elseIf could use a concluding "else: fail with reason or ignore" or just a simple nullcheck :)

**Comment by Joshwoo69** [comment]
@mindforger explain? so i like poked a thing that cannot so called "exist"?

**Comment by mindforger** [comment]
the recipe you forced a check on is for some (myself unknown) reason neither an ShapelessRecipes, nor an ShapelessOreRecipe, nor an ShapedOreRecipe, or an ShapedRecipes 
it's more like a unsafe handling inside the code here but you must have some sort of strange recipe in your scripts causing this, can you show your scripts somehow?

**Comment by Joshwoo69** [comment]
@mindforger havent done anything with scripts.

**Comment by mindforger** [comment]
then it's some other mod tempering with recipes ... you'll probably need to run this with a custom version of IE to get behind this issue because debugging a whole modpack is a tough or almost impossible task

**Comment by Joshwoo69** [comment]
@mindforger what kind of special version of IE?

**Comment by Joshwoo69** [comment]
filed a issue in the minetweaker issues list.

**Comment by BluSunrize** [comment]
@mindforger has a point here. This could be avoided with a check, I will definitely include one with the next build, but I don't see myself doing a build just for this one fix.

I'm also re-opening this issue, as a reminder for myself =P

**Comment by jaredlll08** [comment]
@BluSunrize was about to comment here that this has nothing to do with us, I'll close the issue on my end

**Comment by BluSunrize** [comment]
Oh yeah, absolutely not your side jared. Just me being oblivious to the fact that anyone can implement IRecipe (even though I do it myself xD)
