### ISSUE TITLE
Crash while loading

### ISSUE THREAD

**Issue by Alex33212** [BluSunrize/ImmersiveEngineering#989]
I recently put this, along with Optifine, into the Mods folder of my install of Tekkit Legends. However, I get a crash upon loading that mentions Immersive Engineering:

http://pastebin.com/g6z4Jswa

**Comment by malte0811** [comment]
Update Minetweaker to the latest version. And in the future check whether a bug has been reported before before reporting it.

**Comment by BluSunrize** [comment]
^ what he said.

**Comment by Alex33212** [comment]
I have switched out the installed version (3.0.10) for the newest version (3.0.10B), and it worked! Thanks!
