### ISSUE TITLE
Wrong Improved blast furnace model

### ISSUE THREAD

**Issue by sybershot** [BluSunrize/ImmersiveEngineering#990]
Using Immersive Ingineering 0.7.2_Java7_2, when i form Improved blast furnace i get this...
![2016-03-04_09 53 32](https://cloud.githubusercontent.com/assets/5563058/13521199/edbc5328-e1f7-11e5-9c55-9e5ef76bf70a.png)
Java version: 7, u79.
Forge version: 10.13.4.1566
Also, Guis of both, Crude BF and Improved BF seem to not updating.

**Comment by AlterAkima** [comment]
Most likely Optifine's fault

**Comment by BluSunrize** [comment]
OI. THE FUCK ARE YOU USING THE EXCLUSIVE BUILD FOR.
that build was SOLELY made for the two people who were involved in the issue. You ASK before you use that, numbskull.
Also, yeah stop using Optifine. That has been reported like 5 times now.
