### ISSUE TITLE
[Bug] [0.7.2] Metal Press and Item Router

### ISSUE THREAD

**Issue by mysticdrew** [BluSunrize/ImmersiveEngineering#991]
With the update to 0.7.2 when items come out of the router onto the belt, only one ingot sicks to the belt. Previous to 0.7.2, 4 ingots would stick to the belt for making gears. 

Tossing the ingots on by hand works fine mostly, but it still breaks now and then. This bug breaks automation with the metal press.

If you need more info I'm in irc.esper.net as mysticdrew.

**Comment by BluSunrize** [comment]
Pictures of the setup?

**Comment by malte0811** [comment]
Looking into it now, I'll include the fix in my PR (given that I can reproduce and fix this), so don't merge it yet.

**Comment by mysticdrew** [comment]
http://puu.sh/ntOvu/ec2590c92a.png

This was working before the the server updated to 0.7.2, we were on 0.7.1.2

**Comment by malte0811** [comment]
Wait, you can put in no more than ONE ingot? I just found and fixed a bug that prevents more than three out of 4 ingots (it's actually a bug in the router), but I have been able to put in 3 ingots from the start.

**Comment by mysticdrew** [comment]
Right if the router throws a stack of ingots on the belt, only one sticks. I have to throw the other 3 down manually to make a gear. 4 ingots for a gear on Infinity Evolved Expert Skyblock

**Comment by mysticdrew** [comment]
I have video from my stream of it happening last night, I will find it for you. Do you guys have a public IRC channel?

**Comment by BluSunrize** [comment]
#BluSunrize on esper

**Comment by malte0811** [comment]
Fixed
