### ISSUE TITLE
Tinkers construct compat

### ISSUE THREAD

**Issue by InfinityRaider** [BluSunrize/ImmersiveEngineering#995]
This is a feature request for some TiC compat, I'd love to see all recipes for Tinkers Construct tool parts in the metal press by pressing an ingot (or multiple) to produce the part corresponding with the cast used as a mold.

**Comment by BluSunrize** [comment]
You can minetweaker that yourself =3

**Comment by InfinityRaider** [comment]
I know I could MT it, but doing it for everything is quite a lot of work compared to putting it in a loop in code. I'll have a look at your API and see what I can do.
