### ISSUE TITLE
rendering issue with optifine

### ISSUE THREAD

**Issue by escman1999** [BluSunrize/ImmersiveEngineering#998]
i don't know if this needs to be fixed on your side or optifine's, but when i right click a multiblock, like a blast furnace or coke oven with an IE hammer, the multiblock is still blank, but it still allows me to open the GUI. someone on the optifine thread said that the block texture isn't updating correctly with optifine installed. when i leave the world and come back, the issue is gone. i don't expect this to be fixed, but could you please look into it? i need optifine for it's connected textures and FPS boost.
![2016-03-03_17 44 19](https://cloud.githubusercontent.com/assets/6901624/13576609/8d1a0dd2-e45c-11e5-989a-fd542aa708aa.png)

**Comment by laz2727** [comment]
Well, you ARE using Optifine...

2016-03-07 22:03 GMT+05:00 escman1999 <notifications@github.com>:

**Comment by XFactHD** [comment]
There are most likely other mods providing the kind of connected textures Optifine provides. For the fps boost you might want to try out CoFHTweaks.

**Comment by BluSunrize** [comment]
I don't support Optifine bugs.
